crypto/asn1/a_bitstr.c File Reference
a_bitstr.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include "asn1_locl.h"
Functions
int ASN1_BIT_STRING_set (ASN1_BIT_STRING *x, unsigned char *d, int len)
int i2c_ASN1_BIT_STRING (ASN1_BIT_STRING *a, unsigned char **pp)
ASN1_BIT_STRING * c2i_ASN1_BIT_STRING (ASN1_BIT_STRING **a, const unsigned char **pp, long len)
int ASN1_BIT_STRING_set_bit (ASN1_BIT_STRING *a, int n, int value)
int ASN1_BIT_STRING_get_bit (const ASN1_BIT_STRING *a, int n)
int ASN1_BIT_STRING_check (const ASN1_BIT_STRING *a, const unsigned char *flags, int flags_len)
Function Documentation
ASN1_BIT_STRING_check()
int ASN1_BIT_STRING_check (const ASN1_BIT_STRING * a, const unsigned char * flags, int flags_len)
Definition at line 192 of file a_bitstr.c.
ASN1_BIT_STRING_get_bit()
int ASN1_BIT_STRING_get_bit (const ASN1_BIT_STRING * a, int n)
Definition at line 175 of file a_bitstr.c.
References NULL.
ASN1_BIT_STRING_set()
int ASN1_BIT_STRING_set (ASN1_BIT_STRING * x, unsigned char * d, int len)
Definition at line 15 of file a_bitstr.c.
References ASN1_STRING_set().
ASN1_BIT_STRING_set_bit()
int ASN1_BIT_STRING_set_bit (ASN1_BIT_STRING * a, int n, int value)
Definition at line 140 of file a_bitstr.c.
Referenced by ASN1_BIT_STRING_set_asc(), TS_RESP_CTX_add_failure_info(), and v2i_ASN1_BIT_STRING().
c2i_ASN1_BIT_STRING()
ASN1_BIT_STRING* c2i_ASN1_BIT_STRING (ASN1_BIT_STRING ** a, const unsigned char ** pp, long len)
Definition at line 78 of file a_bitstr.c.
i2c_ASN1_BIT_STRING()
int i2c_ASN1_BIT_STRING (ASN1_BIT_STRING * a, unsigned char ** pp)
Definition at line 20 of file a_bitstr.c.