crypto/asn1/a_d2i_fp.c File Reference
a_d2i_fp.c File Reference
#include <stdio.h>
#include <limits.h>
#include "internal/cryptlib.h"
#include "internal/numbers.h"
#include <openssl/buffer.h>
#include <openssl/asn1.h>
Macros
#define HEADER_SIZE 8
#define ASN1_CHUNK_INITIAL_SIZE (16 * 1024)
Functions
void * ASN1_d2i_fp (void *(*xnew)(void), d2i_of_void *d2i, FILE *in, void **x)
void * ASN1_d2i_bio (void *(*xnew)(void), d2i_of_void *d2i, BIO *in, void **x)
void * ASN1_item_d2i_bio (const ASN1_ITEM *it, BIO *in, void *x)
void * ASN1_item_d2i_fp (const ASN1_ITEM *it, FILE *in, void *x)
Macro Definition Documentation
ASN1_CHUNK_INITIAL_SIZE
#define ASN1_CHUNK_INITIAL_SIZE (16 * 1024)
Definition at line 94 of file a_d2i_fp.c.
HEADER_SIZE
#define HEADER_SIZE 8
Definition at line 93 of file a_d2i_fp.c.
Function Documentation
ASN1_d2i_bio()
void* ASN1_d2i_bio (void *(*)(void) xnew, d2i_of_void * d2i, BIO * in, void ** x)
Definition at line 38 of file a_d2i_fp.c.
References NULL.
ASN1_d2i_fp()
void* ASN1_d2i_fp (void *(*)(void) xnew, d2i_of_void * d2i, FILE * in, void ** x)
Definition at line 22 of file a_d2i_fp.c.
Referenced by d2i_RSA_PUBKEY_fp().
ASN1_item_d2i_bio()
void* ASN1_item_d2i_bio (const ASN1_ITEM * it, BIO * in, void * x)
Definition at line 58 of file a_d2i_fp.c.
References NULL.
Referenced by d2i_CMS_bio(), d2i_PKCS12_bio(), d2i_PKCS7_bio(), d2i_RSAPrivateKey_bio(), d2i_RSAPublicKey_bio(), d2i_X509_bio(), d2i_X509_CRL_bio(), and d2i_X509_REQ_bio().
ASN1_item_d2i_fp()
void* ASN1_item_d2i_fp (const ASN1_ITEM * it, FILE * in, void * x)
Definition at line 77 of file a_d2i_fp.c.
Referenced by d2i_PKCS12_fp(), d2i_PKCS7_fp(), d2i_RSAPrivateKey_fp(), d2i_RSAPublicKey_fp(), d2i_X509_CRL_fp(), d2i_X509_fp(), and d2i_X509_REQ_fp().