crypto/asn1/a_gentm.c File Reference
a_gentm.c File Reference
#include <stdio.h>
#include <time.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include "asn1_locl.h"
Functions
int asn1_generalizedtime_to_tm (struct tm *tm, const ASN1_GENERALIZEDTIME *d)
int ASN1_GENERALIZEDTIME_check (const ASN1_GENERALIZEDTIME *d)
int ASN1_GENERALIZEDTIME_set_string (ASN1_GENERALIZEDTIME *s, const char *str)
ASN1_GENERALIZEDTIME * ASN1_GENERALIZEDTIME_set (ASN1_GENERALIZEDTIME *s, time_t t)
ASN1_GENERALIZEDTIME * ASN1_GENERALIZEDTIME_adj (ASN1_GENERALIZEDTIME *s, time_t t, int offset_day, long offset_sec)
int ASN1_GENERALIZEDTIME_print (BIO *bp, const ASN1_GENERALIZEDTIME *tm)
Variables
const char * _asn1_mon [12]
Function Documentation
ASN1_GENERALIZEDTIME_adj()
ASN1_GENERALIZEDTIME* ASN1_GENERALIZEDTIME_adj (ASN1_GENERALIZEDTIME * s, time_t t, int offset_day, long offset_sec)
Definition at line 166 of file a_gentm.c.
References ASN1_F_ASN1_GENERALIZEDTIME_ADJ, ASN1err, BIO_snprintf(), ebcdic2ascii(), ERR_R_MALLOC_FAILURE, if(), len, NULL, OPENSSL_free, OPENSSL_gmtime(), OPENSSL_gmtime_adj(), OPENSSL_malloc, and V_ASN1_GENERALIZEDTIME.
Referenced by ASN1_GENERALIZEDTIME_set(), ASN1_TIME_adj(), and X509_time_adj_ex().
ASN1_GENERALIZEDTIME_check()
int ASN1_GENERALIZEDTIME_check (const ASN1_GENERALIZEDTIME * d)
Definition at line 137 of file a_gentm.c.
References asn1_generalizedtime_to_tm(), and NULL.
Referenced by ASN1_GENERALIZEDTIME_set_string(), and ASN1_TIME_check().
ASN1_GENERALIZEDTIME_print()
int ASN1_GENERALIZEDTIME_print (BIO * bp, const ASN1_GENERALIZEDTIME * tm)
Definition at line 223 of file a_gentm.c.
References _asn1_mon, BIO_printf(), BIO_write(), h, if(), and NULL.
Referenced by ASN1_TIME_print(), and TS_TST_INFO_print_bio().
ASN1_GENERALIZEDTIME_set()
ASN1_GENERALIZEDTIME* ASN1_GENERALIZEDTIME_set (ASN1_GENERALIZEDTIME * s, time_t t)
Definition at line 160 of file a_gentm.c.
References ASN1_GENERALIZEDTIME_adj().
ASN1_GENERALIZEDTIME_set_string()
int ASN1_GENERALIZEDTIME_set_string (ASN1_GENERALIZEDTIME * s, const char * str)
Definition at line 142 of file a_gentm.c.
References ASN1_GENERALIZEDTIME_check(), ASN1_STRING_set(), NULL, t, and V_ASN1_GENERALIZEDTIME.
Referenced by OCSP_archive_cutoff_new(), and OCSP_crlID_new().
asn1_generalizedtime_to_tm()
int asn1_generalizedtime_to_tm (struct tm * tm, const ASN1_GENERALIZEDTIME * d)
Definition at line 20 of file a_gentm.c.
References if(), max, min, OPENSSL_gmtime_adj(), and V_ASN1_GENERALIZEDTIME.
Referenced by ASN1_GENERALIZEDTIME_check().
Variable Documentation
_asn1_mon
const char* _asn1_mon[12]
Initial value:
= {
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
}
Definition at line 218 of file a_gentm.c.
Referenced by ASN1_GENERALIZEDTIME_print(), and ASN1_UTCTIME_print().