crypto/asn1/a_i2d_fp.c File Reference
a_i2d_fp.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/buffer.h>
#include <openssl/asn1.h>
Functions
int ASN1_i2d_fp (i2d_of_void *i2d, FILE *out, void *x)
int ASN1_i2d_bio (i2d_of_void *i2d, BIO *out, unsigned char *x)
int ASN1_item_i2d_fp (const ASN1_ITEM *it, FILE *out, void *x)
int ASN1_item_i2d_bio (const ASN1_ITEM *it, BIO *out, void *x)
Function Documentation
ASN1_i2d_bio()
int ASN1_i2d_bio (i2d_of_void * i2d, BIO * out, unsigned char * x)
Definition at line 34 of file a_i2d_fp.c.
ASN1_i2d_fp()
int ASN1_i2d_fp (i2d_of_void * i2d, FILE * out, void * x)
Definition at line 18 of file a_i2d_fp.c.
Referenced by i2d_RSA_PUBKEY_fp().
ASN1_item_i2d_bio()
int ASN1_item_i2d_bio (const ASN1_ITEM * it, BIO * out, void * x)
Definition at line 84 of file a_i2d_fp.c.
Referenced by i2d_CMS_bio(), i2d_PKCS12_bio(), i2d_PKCS7_bio(), i2d_RSAPrivateKey_bio(), i2d_RSAPublicKey_bio(), i2d_X509_bio(), i2d_X509_CRL_bio(), i2d_X509_REQ_bio(), and OCSP_REQ_CTX_i2d().
ASN1_item_i2d_fp()
int ASN1_item_i2d_fp (const ASN1_ITEM * it, FILE * out, void * x)
Definition at line 68 of file a_i2d_fp.c.
Referenced by i2d_PKCS12_fp(), i2d_PKCS7_fp(), i2d_RSAPrivateKey_fp(), i2d_RSAPublicKey_fp(), i2d_X509_CRL_fp(), i2d_X509_fp(), and i2d_X509_REQ_fp().