crypto/asn1/a_int.c File Reference
a_int.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include "internal/numbers.h"
#include <limits.h>
#include <openssl/asn1.h>
#include <openssl/bn.h>
#include "asn1_locl.h"
Macros
#define ABS_INT64_MIN ((uint64_t)INT64_MAX + (uint64_t)(-(INT64_MIN + INT64_MAX)))
Functions
ASN1_INTEGER * ASN1_INTEGER_dup (const ASN1_INTEGER *x)
int ASN1_INTEGER_cmp (const ASN1_INTEGER *x, const ASN1_INTEGER *y)
int i2c_ASN1_INTEGER (ASN1_INTEGER *a, unsigned char **pp)
ASN1_INTEGER * c2i_ASN1_INTEGER (ASN1_INTEGER **a, const unsigned char **pp, long len)
ASN1_INTEGER * d2i_ASN1_UINTEGER (ASN1_INTEGER **a, const unsigned char **pp, long length)
int ASN1_INTEGER_get_int64 (int64_t *pr, const ASN1_INTEGER *a)
int ASN1_INTEGER_set_int64 (ASN1_INTEGER *a, int64_t r)
int ASN1_INTEGER_get_uint64 (uint64_t *pr, const ASN1_INTEGER *a)
int ASN1_INTEGER_set_uint64 (ASN1_INTEGER *a, uint64_t r)
int ASN1_INTEGER_set (ASN1_INTEGER *a, long v)
long ASN1_INTEGER_get (const ASN1_INTEGER *a)
ASN1_INTEGER * BN_to_ASN1_INTEGER (const BIGNUM *bn, ASN1_INTEGER *ai)
BIGNUM * ASN1_INTEGER_to_BN (const ASN1_INTEGER *ai, BIGNUM *bn)
int ASN1_ENUMERATED_get_int64 (int64_t *pr, const ASN1_ENUMERATED *a)
int ASN1_ENUMERATED_set_int64 (ASN1_ENUMERATED *a, int64_t r)
int ASN1_ENUMERATED_set (ASN1_ENUMERATED *a, long v)
long ASN1_ENUMERATED_get (const ASN1_ENUMERATED *a)
ASN1_ENUMERATED * BN_to_ASN1_ENUMERATED (const BIGNUM *bn, ASN1_ENUMERATED *ai)
BIGNUM * ASN1_ENUMERATED_to_BN (const ASN1_ENUMERATED *ai, BIGNUM *bn)
Macro Definition Documentation
ABS_INT64_MIN
#define ABS_INT64_MIN ((uint64_t)INT64_MAX + (uint64_t)(-(INT64_MIN + INT64_MAX)))
Definition at line 277 of file a_int.c.
Function Documentation
ASN1_ENUMERATED_get()
long ASN1_ENUMERATED_get (const ASN1_ENUMERATED * a)
Definition at line 598 of file a_int.c.
References ASN1_ENUMERATED_get_int64(), NULL, V_ASN1_ENUMERATED, and V_ASN1_NEG.
Referenced by i2s_ASN1_ENUMERATED_TABLE(), and OCSP_response_status().
ASN1_ENUMERATED_get_int64()
int ASN1_ENUMERATED_get_int64 (int64_t * pr, const ASN1_ENUMERATED * a)
Definition at line 583 of file a_int.c.
Referenced by ASN1_ENUMERATED_get().
ASN1_ENUMERATED_set()
int ASN1_ENUMERATED_set (ASN1_ENUMERATED * a, long v)
Definition at line 593 of file a_int.c.
References ASN1_ENUMERATED_set_int64().
Referenced by OCSP_basic_add1_status(), and OCSP_response_create().
ASN1_ENUMERATED_set_int64()
int ASN1_ENUMERATED_set_int64 (ASN1_ENUMERATED * a, int64_t r)
Definition at line 588 of file a_int.c.
Referenced by ASN1_ENUMERATED_set().
ASN1_ENUMERATED_to_BN()
BIGNUM* ASN1_ENUMERATED_to_BN (const ASN1_ENUMERATED * ai, BIGNUM * bn)
Definition at line 621 of file a_int.c.
Referenced by i2s_ASN1_ENUMERATED().
ASN1_INTEGER_cmp()
int ASN1_INTEGER_cmp (const ASN1_INTEGER * x, const ASN1_INTEGER * y)
Definition at line 23 of file a_int.c.
Referenced by X509_check_akid(), and X509_issuer_and_serial_cmp().
ASN1_INTEGER_dup()
ASN1_INTEGER* ASN1_INTEGER_dup (const ASN1_INTEGER * x)
Definition at line 18 of file a_int.c.
References ASN1_STRING_dup().
Referenced by TS_ACCURACY_set_micros(), TS_ACCURACY_set_millis(), TS_ACCURACY_set_seconds(), TS_REQ_set_nonce(), TS_TST_INFO_set_nonce(), and TS_TST_INFO_set_serial().
ASN1_INTEGER_get()
long ASN1_INTEGER_get (const ASN1_INTEGER * a)
Definition at line 559 of file a_int.c.
References ASN1_INTEGER_get_int64(), and NULL.
Referenced by asn1_do_adb(), OCSP_REQUEST_print(), TS_REQ_get_version(), TS_STATUS_INFO_print_bio(), TS_TST_INFO_get_version(), TS_TST_INFO_print_bio(), X509_CRL_get_version(), X509_get_version(), and X509_REQ_get_version().
ASN1_INTEGER_get_int64()
int ASN1_INTEGER_get_int64 (int64_t * pr, const ASN1_INTEGER * a)
Definition at line 534 of file a_int.c.
Referenced by ASN1_INTEGER_get().
ASN1_INTEGER_get_uint64()
int ASN1_INTEGER_get_uint64 (uint64_t * pr, const ASN1_INTEGER * a)
Definition at line 544 of file a_int.c.
ASN1_INTEGER_set()
int ASN1_INTEGER_set (ASN1_INTEGER * a, long v)
Definition at line 554 of file a_int.c.
References ASN1_INTEGER_set_int64().
Referenced by CMS_add_simple_smimecap(), OCSP_crlID_new(), PKCS12_init(), PKCS12_setup_mac(), PKCS7_set_type(), rsa_pss_params_create(), TS_REQ_set_version(), TS_RESP_CTX_set_accuracy(), TS_STATUS_INFO_set_status(), TS_TST_INFO_set_version(), X509_CRL_set_version(), X509_REQ_set_version(), and X509_set_version().
ASN1_INTEGER_set_int64()
int ASN1_INTEGER_set_int64 (ASN1_INTEGER * a, int64_t r)
Definition at line 539 of file a_int.c.
Referenced by ASN1_INTEGER_set().
ASN1_INTEGER_set_uint64()
int ASN1_INTEGER_set_uint64 (ASN1_INTEGER * a, uint64_t r)
Definition at line 549 of file a_int.c.
ASN1_INTEGER_to_BN()
BIGNUM* ASN1_INTEGER_to_BN (const ASN1_INTEGER * ai, BIGNUM * bn)
Definition at line 578 of file a_int.c.
Referenced by i2s_ASN1_INTEGER(), and TS_ASN1_INTEGER_print_bio().
BN_to_ASN1_ENUMERATED()
ASN1_ENUMERATED* BN_to_ASN1_ENUMERATED (const BIGNUM * bn, ASN1_ENUMERATED * ai)
Definition at line 616 of file a_int.c.
BN_to_ASN1_INTEGER()
ASN1_INTEGER* BN_to_ASN1_INTEGER (const BIGNUM * bn, ASN1_INTEGER * ai)
Definition at line 573 of file a_int.c.
c2i_ASN1_INTEGER()
ASN1_INTEGER* c2i_ASN1_INTEGER (ASN1_INTEGER ** a, const unsigned char ** pp, long len)
Definition at line 304 of file a_int.c.
d2i_ASN1_UINTEGER()
ASN1_INTEGER* d2i_ASN1_UINTEGER (ASN1_INTEGER ** a, const unsigned char ** pp, long length)
Definition at line 408 of file a_int.c.
i2c_ASN1_INTEGER()
int i2c_ASN1_INTEGER (ASN1_INTEGER * a, unsigned char ** pp)
Definition at line 220 of file a_int.c.