crypto/asn1/a_object.c File Reference
a_object.c File Reference
#include <stdio.h>
#include <limits.h>
#include "internal/cryptlib.h"
#include <openssl/buffer.h>
#include <openssl/asn1.h>
#include <openssl/objects.h>
#include <openssl/bn.h>
#include "internal/asn1_int.h"
#include "asn1_locl.h"
Functions
int i2d_ASN1_OBJECT (const ASN1_OBJECT *a, unsigned char **pp)
int a2d_ASN1_OBJECT (unsigned char *out, int olen, const char *buf, int num)
int i2t_ASN1_OBJECT (char *buf, int buf_len, const ASN1_OBJECT *a)
int i2a_ASN1_OBJECT (BIO *bp, const ASN1_OBJECT *a)
ASN1_OBJECT * d2i_ASN1_OBJECT (ASN1_OBJECT **a, const unsigned char **pp, long length)
ASN1_OBJECT * c2i_ASN1_OBJECT (ASN1_OBJECT **a, const unsigned char **pp, long len)
ASN1_OBJECT * ASN1_OBJECT_new (void)
void ASN1_OBJECT_free (ASN1_OBJECT *a)
ASN1_OBJECT * ASN1_OBJECT_create (int nid, unsigned char *data, int len, const char *sn, const char *ln)
Function Documentation
a2d_ASN1_OBJECT()
int a2d_ASN1_OBJECT (unsigned char * out, int olen, const char * buf, int num)
Definition at line 41 of file a_object.c.
ASN1_OBJECT_create()
ASN1_OBJECT* ASN1_OBJECT_create (int nid, unsigned char * data, int len, const char * sn, const char * ln)
Definition at line 357 of file a_object.c.
References ASN1_OBJECT_FLAG_DYNAMIC, ASN1_OBJECT_FLAG_DYNAMIC_DATA, ASN1_OBJECT_FLAG_DYNAMIC_STRINGS, data, len, nid, and OBJ_dup().
ASN1_OBJECT_free()
void ASN1_OBJECT_free (ASN1_OBJECT * a)
Definition at line 335 of file a_object.c.
References ASN1_OBJECT_FLAG_DYNAMIC, ASN1_OBJECT_FLAG_DYNAMIC_DATA, ASN1_OBJECT_FLAG_DYNAMIC_STRINGS, NULL, and OPENSSL_free.
Referenced by asn1_primitive_free(), ASN1_sign(), EVP_CIPHER_type(), OBJ_create(), OBJ_dup(), OBJ_txt2nid(), OCSP_accept_responses_new(), policy_data_free(), TS_REQ_set_policy_id(), TS_RESP_CTX_add_policy(), TS_RESP_CTX_free(), TS_RESP_CTX_set_def_policy(), TS_TST_INFO_set_policy_id(), TS_VERIFY_CTX_cleanup(), X509_ATTRIBUTE_create_by_txt(), X509_ATTRIBUTE_set1_object(), X509_EXTENSION_set_object(), X509_NAME_ENTRY_create_by_NID(), X509_NAME_ENTRY_create_by_txt(), X509_NAME_ENTRY_set_object(), and X509_VERIFY_PARAM_free().
ASN1_OBJECT_new()
ASN1_OBJECT* ASN1_OBJECT_new (void)
Definition at line 322 of file a_object.c.
Referenced by OBJ_dup().
c2i_ASN1_OBJECT()
ASN1_OBJECT* c2i_ASN1_OBJECT (ASN1_OBJECT ** a, const unsigned char ** pp, long len)
Definition at line 226 of file a_object.c.
d2i_ASN1_OBJECT()
ASN1_OBJECT* d2i_ASN1_OBJECT (ASN1_OBJECT ** a, const unsigned char ** pp, long length)
Definition at line 198 of file a_object.c.
References len.
i2a_ASN1_OBJECT()
int i2a_ASN1_OBJECT (BIO * bp, const ASN1_OBJECT * a)
Definition at line 173 of file a_object.c.
Referenced by print_attribs(), TS_ext_print_bio(), X509_REQ_print_ex(), and X509_signature_print().
i2d_ASN1_OBJECT()
int i2d_ASN1_OBJECT (const ASN1_OBJECT * a, unsigned char ** pp)
Definition at line 20 of file a_object.c.
References ASN1_object_size(), ASN1_put_object(), NULL, pp, V_ASN1_OBJECT, and V_ASN1_UNIVERSAL.
i2t_ASN1_OBJECT()
int i2t_ASN1_OBJECT (char * buf, int buf_len, const ASN1_OBJECT * a)
Definition at line 168 of file a_object.c.
Referenced by EVP_PKCS82PKEY().