crypto/asn1/a_octet.c File Reference
a_octet.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
Functions
ASN1_OCTET_STRING * ASN1_OCTET_STRING_dup (const ASN1_OCTET_STRING *x)
int ASN1_OCTET_STRING_cmp (const ASN1_OCTET_STRING *a, const ASN1_OCTET_STRING *b)
int ASN1_OCTET_STRING_set (ASN1_OCTET_STRING *x, const unsigned char *d, int len)
Function Documentation
ASN1_OCTET_STRING_cmp()
int ASN1_OCTET_STRING_cmp (const ASN1_OCTET_STRING * a, const ASN1_OCTET_STRING * b)
Definition at line 19 of file a_octet.c.
References ASN1_STRING_cmp().
Referenced by CMS_RecipientInfo_kekri_id_cmp(), OCSP_check_nonce(), and X509_check_akid().
ASN1_OCTET_STRING_dup()
ASN1_OCTET_STRING* ASN1_OCTET_STRING_dup (const ASN1_OCTET_STRING * x)
Definition at line 14 of file a_octet.c.
References ASN1_STRING_dup().
ASN1_OCTET_STRING_set()
int ASN1_OCTET_STRING_set (ASN1_OCTET_STRING * x, const unsigned char * d, int len)
Definition at line 25 of file a_octet.c.
References ASN1_STRING_set().
Referenced by ASN1_TYPE_set_octetstring(), TS_MSG_IMPRINT_set_msg(), and X509_EXTENSION_set_data().