crypto/asn1/a_print.c File Reference
a_print.c File Reference
#include <stdio.h>
#include <ctype.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
Functions
int ASN1_PRINTABLE_type (const unsigned char *s, int len)
int ASN1_UNIVERSALSTRING_to_string (ASN1_UNIVERSALSTRING *s)
int ASN1_STRING_print (BIO *bp, const ASN1_STRING *v)
Function Documentation
ASN1_PRINTABLE_type()
int ASN1_PRINTABLE_type (const unsigned char * s, int len)
Definition at line 15 of file a_print.c.
Referenced by ASN1_UNIVERSALSTRING_to_string(), and X509_NAME_ENTRY_set_data().
ASN1_STRING_print()
int ASN1_STRING_print (BIO * bp, const ASN1_STRING * v)
Definition at line 82 of file a_print.c.
Referenced by TS_ext_print_bio(), and X509_REQ_print_ex().
ASN1_UNIVERSALSTRING_to_string()
int ASN1_UNIVERSALSTRING_to_string (ASN1_UNIVERSALSTRING * s)
Definition at line 54 of file a_print.c.
References ASN1_PRINTABLE_type(), and V_ASN1_UNIVERSALSTRING.