crypto/asn1/a_sign.c File Reference
a_sign.c File Reference
#include <stdio.h>
#include <time.h>
#include "internal/cryptlib.h"
#include <sys/types.h>
#include <openssl/bn.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include <openssl/objects.h>
#include <openssl/buffer.h>
#include "internal/asn1_int.h"
#include "internal/evp_int.h"
Functions
int ASN1_sign (i2d_of_void *i2d, X509_ALGOR *algor1, X509_ALGOR *algor2, ASN1_BIT_STRING *signature, char *data, EVP_PKEY *pkey, const EVP_MD *type)
int ASN1_item_sign (const ASN1_ITEM *it, X509_ALGOR *algor1, X509_ALGOR *algor2, ASN1_BIT_STRING *signature, void *asn, EVP_PKEY *pkey, const EVP_MD *type)
int ASN1_item_sign_ctx (const ASN1_ITEM *it, X509_ALGOR *algor1, X509_ALGOR *algor2, ASN1_BIT_STRING *signature, void *asn, EVP_MD_CTX *ctx)
Function Documentation
ASN1_item_sign()
int ASN1_item_sign (const ASN1_ITEM * it, X509_ALGOR * algor1, X509_ALGOR * algor2, ASN1_BIT_STRING * signature, void * asn, EVP_PKEY * pkey, const EVP_MD * type)
Definition at line 114 of file a_sign.c.
References ASN1_F_ASN1_ITEM_SIGN, ASN1_item_sign_ctx(), ASN1err, ctx, ERR_R_MALLOC_FAILURE, EVP_DigestSignInit(), EVP_MD_CTX_free(), EVP_MD_CTX_new(), and NULL.
ASN1_item_sign_ctx()
int ASN1_item_sign_ctx (const ASN1_ITEM * it, X509_ALGOR * algor1, X509_ALGOR * algor2, ASN1_BIT_STRING * signature, void * asn, EVP_MD_CTX * ctx)
Definition at line 136 of file a_sign.c.
References ASN1_F_ASN1_ITEM_SIGN_CTX, ASN1_item_i2d(), ASN1_PKEY_SIGPARAM_NULL, ASN1_R_CONTEXT_NOT_INITIALISED, ASN1_R_DIGEST_AND_KEY_TYPE_NOT_SUPPORTED, ASN1_STRING_FLAG_BITS_LEFT, ASN1err, ERR_R_EVP_LIB, ERR_R_MALLOC_FAILURE, EVP_DigestSignFinal(), EVP_DigestSignUpdate, EVP_MD_CTX_md(), EVP_MD_CTX_pkey_ctx(), EVP_MD_nid, EVP_PKEY_CTX_get0_pkey(), EVP_PKEY_size(), NULL, OBJ_find_sigid_by_algs(), OBJ_nid2obj(), OPENSSL_clear_free, OPENSSL_free, OPENSSL_malloc, type, V_ASN1_NULL, V_ASN1_UNDEF, and X509_ALGOR_set0().
Referenced by ASN1_item_sign(), X509_CRL_sign_ctx(), X509_REQ_sign_ctx(), and X509_sign_ctx().
ASN1_sign()
int ASN1_sign (i2d_of_void * i2d, X509_ALGOR * algor1, X509_ALGOR * algor2, ASN1_BIT_STRING * signature, char * data, EVP_PKEY * pkey, const EVP_MD * type)
Definition at line 29 of file a_sign.c.
References ASN1_F_ASN1_SIGN, ASN1_OBJECT_free(), ASN1_R_THE_ASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD, ASN1_R_UNKNOWN_OBJECT_TYPE, ASN1_STRING_FLAG_BITS_LEFT, ASN1err, ctx, ERR_R_EVP_LIB, ERR_R_MALLOC_FAILURE, EVP_MD_CTX_free(), EVP_MD_CTX_new(), EVP_PKEY_size(), EVP_SignFinal(), EVP_SignInit_ex, EVP_SignUpdate, NID_dsaWithSHA1, NULL, OBJ_nid2obj(), OPENSSL_clear_free, OPENSSL_free, OPENSSL_malloc, and V_ASN1_NULL.