crypto/asn1/a_strex.c File Reference
a_strex.c File Reference
#include <stdio.h>
#include <string.h>
#include "internal/cryptlib.h"
#include "internal/asn1_int.h"
#include <openssl/crypto.h>
#include <openssl/x509.h>
#include <openssl/asn1.h>
#include "charmap.h"
Macros
#define CHARTYPE_BS_ESC (ASN1_STRFLGS_ESC_2253 | CHARTYPE_FIRST_ESC_2253 | CHARTYPE_LAST_ESC_2253)
#define ESC_FLAGS
#define BUF_TYPE_WIDTH_MASK 0x7
#define BUF_TYPE_CONVUTF8 0x8
#define FN_WIDTH_LN 25
#define FN_WIDTH_SN 10
Typedefs
typedef int char_io(void *arg, const void *buf, int len)
Functions
int X509_NAME_print_ex (BIO *out, const X509_NAME *nm, int indent, unsigned long flags)
int X509_NAME_print_ex_fp (FILE *fp, const X509_NAME *nm, int indent, unsigned long flags)
int ASN1_STRING_print_ex (BIO *out, const ASN1_STRING *str, unsigned long flags)
int ASN1_STRING_print_ex_fp (FILE *fp, const ASN1_STRING *str, unsigned long flags)
int ASN1_STRING_to_UTF8 (unsigned char **out, const ASN1_STRING *in)
int asn1_valid_host (const ASN1_STRING *host)
Macro Definition Documentation
BUF_TYPE_CONVUTF8
#define BUF_TYPE_CONVUTF8 0x8
Definition at line 130 of file a_strex.c.
BUF_TYPE_WIDTH_MASK
#define BUF_TYPE_WIDTH_MASK 0x7
Definition at line 129 of file a_strex.c.
CHARTYPE_BS_ESC
#define CHARTYPE_BS_ESC (ASN1_STRFLGS_ESC_2253 | CHARTYPE_FIRST_ESC_2253 | CHARTYPE_LAST_ESC_2253)
Definition at line 26 of file a_strex.c.
ESC_FLAGS
#define ESC_FLAGS
Value:
(ASN1_STRFLGS_ESC_2253 | \
                  ASN1_STRFLGS_ESC_2254 | \
                  ASN1_STRFLGS_ESC_QUOTE | \
                  ASN1_STRFLGS_ESC_CTRL | \
                  ASN1_STRFLGS_ESC_MSB)
Definition at line 28 of file a_strex.c.
FN_WIDTH_LN
#define FN_WIDTH_LN 25
Definition at line 388 of file a_strex.c.
FN_WIDTH_SN
#define FN_WIDTH_SN 10
Definition at line 389 of file a_strex.c.
Typedef Documentation
char_io
typedef int char_io(void *arg, const void *buf, int len)
Definition at line 58 of file a_strex.c.
Function Documentation
ASN1_STRING_print_ex()
int ASN1_STRING_print_ex (BIO * out, const ASN1_STRING * str, unsigned long flags)
Definition at line 555 of file a_strex.c.
Referenced by TS_STATUS_INFO_print_bio().
ASN1_STRING_print_ex_fp()
int ASN1_STRING_print_ex_fp (FILE * fp, const ASN1_STRING * str, unsigned long flags)
Definition at line 561 of file a_strex.c.
ASN1_STRING_to_UTF8()
int ASN1_STRING_to_UTF8 (unsigned char ** out, const ASN1_STRING * in)
Definition at line 572 of file a_strex.c.
asn1_valid_host()
int asn1_valid_host (const ASN1_STRING * host)
Definition at line 598 of file a_strex.c.
References type.
X509_NAME_print_ex()
int X509_NAME_print_ex (BIO * out, const X509_NAME * nm, int indent, unsigned long flags)
Definition at line 529 of file a_strex.c.
Referenced by verify_callback(), and X509_REQ_print_ex().
X509_NAME_print_ex_fp()
int X509_NAME_print_ex_fp (FILE * fp, const X509_NAME * nm, int indent, unsigned long flags)
Definition at line 538 of file a_strex.c.
References XN_FLAG_COMPAT.