crypto/asn1/a_strnid.c File Reference
a_strnid.c File Reference
#include <stdio.h>
#include <ctype.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include <openssl/objects.h>
#include "tbl_standard.h"
Functions
unsigned long ASN1_STRING_get_default_mask (void)
int ASN1_STRING_set_default_mask_asc (const char *p)
ASN1_STRING * ASN1_STRING_set_by_NID (ASN1_STRING **out, const unsigned char *in, int inlen, int inform, int nid)
DECLARE_OBJ_BSEARCH_CMP_FN (ASN1_STRING_TABLE, ASN1_STRING_TABLE, table)
IMPLEMENT_OBJ_BSEARCH_CMP_FN (ASN1_STRING_TABLE, ASN1_STRING_TABLE, table)
ASN1_STRING_TABLE * ASN1_STRING_TABLE_get (int nid)
int ASN1_STRING_TABLE_add (int nid, long minsize, long maxsize, unsigned long mask, unsigned long flags)
void ASN1_STRING_TABLE_cleanup (void)
Function Documentation
ASN1_STRING_get_default_mask()
unsigned long ASN1_STRING_get_default_mask (void)
Definition at line 34 of file a_strnid.c.
ASN1_STRING_set_by_NID()
ASN1_STRING* ASN1_STRING_set_by_NID (ASN1_STRING ** out, const unsigned char * in, int inlen, int inform, int nid)
Definition at line 79 of file a_strnid.c.
Referenced by X509_ATTRIBUTE_set1_data(), and X509_NAME_ENTRY_set_data().
ASN1_STRING_set_default_mask_asc()
int ASN1_STRING_set_default_mask_asc (const char * p)
Definition at line 49 of file a_strnid.c.
References ASN1_STRING_set_default_mask(), B_ASN1_BMPSTRING, B_ASN1_T61STRING, and B_ASN1_UTF8STRING.
ASN1_STRING_TABLE_add()
int ASN1_STRING_TABLE_add (int nid, long minsize, long maxsize, unsigned long mask, unsigned long flags)
Definition at line 177 of file a_strnid.c.
ASN1_STRING_TABLE_cleanup()
void ASN1_STRING_TABLE_cleanup (void)
Definition at line 198 of file a_strnid.c.
ASN1_STRING_TABLE_get()
ASN1_STRING_TABLE* ASN1_STRING_TABLE_get (int nid)
Definition at line 126 of file a_strnid.c.
DECLARE_OBJ_BSEARCH_CMP_FN()
DECLARE_OBJ_BSEARCH_CMP_FN (ASN1_STRING_TABLE , ASN1_STRING_TABLE , table)
IMPLEMENT_OBJ_BSEARCH_CMP_FN()
IMPLEMENT_OBJ_BSEARCH_CMP_FN (ASN1_STRING_TABLE , ASN1_STRING_TABLE , table)