crypto/asn1/a_type.c File Reference
a_type.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/asn1t.h>
#include <openssl/objects.h>
#include "asn1_locl.h"
Functions
int ASN1_TYPE_get (const ASN1_TYPE *a)
void ASN1_TYPE_set (ASN1_TYPE *a, int type, void *value)
int ASN1_TYPE_set1 (ASN1_TYPE *a, int type, const void *value)
int ASN1_TYPE_cmp (const ASN1_TYPE *a, const ASN1_TYPE *b)
ASN1_TYPE * ASN1_TYPE_pack_sequence (const ASN1_ITEM *it, void *s, ASN1_TYPE **t)
void * ASN1_TYPE_unpack_sequence (const ASN1_ITEM *it, const ASN1_TYPE *t)
Function Documentation
ASN1_TYPE_cmp()
int ASN1_TYPE_cmp (const ASN1_TYPE * a, const ASN1_TYPE * b)
Definition at line 59 of file a_type.c.
References ASN1_STRING_cmp(), ASN1_TYPE::boolean, OBJ_cmp(), ASN1_TYPE::object, ASN1_TYPE::ptr, ASN1_TYPE::type, V_ASN1_BIT_STRING, V_ASN1_BMPSTRING, V_ASN1_BOOLEAN, V_ASN1_ENUMERATED, V_ASN1_GENERALIZEDTIME, V_ASN1_GENERALSTRING, V_ASN1_GRAPHICSTRING, V_ASN1_IA5STRING, V_ASN1_INTEGER, V_ASN1_NULL, V_ASN1_NUMERICSTRING, V_ASN1_OBJECT, V_ASN1_OCTET_STRING, V_ASN1_OTHER, V_ASN1_PRINTABLESTRING, V_ASN1_SEQUENCE, V_ASN1_SET, V_ASN1_T61STRING, V_ASN1_UNIVERSALSTRING, V_ASN1_UTCTIME, V_ASN1_UTF8STRING, V_ASN1_VIDEOTEXSTRING, V_ASN1_VISIBLESTRING, and ASN1_TYPE::value.
ASN1_TYPE_get()
int ASN1_TYPE_get (const ASN1_TYPE * a)
Definition at line 16 of file a_type.c.
References NULL, ASN1_TYPE::ptr, ASN1_TYPE::type, V_ASN1_NULL, and ASN1_TYPE::value.
ASN1_TYPE_pack_sequence()
ASN1_TYPE* ASN1_TYPE_pack_sequence (const ASN1_ITEM * it, void * s, ASN1_TYPE ** t)
Definition at line 105 of file a_type.c.
References ASN1_item_pack(), ASN1_TYPE_set(), NULL, t, and V_ASN1_SEQUENCE.
ASN1_TYPE_set()
void ASN1_TYPE_set (ASN1_TYPE * a, int type, void * value)
Definition at line 24 of file a_type.c.
References asn1_primitive_free(), ASN1_TYPE::boolean, NULL, ASN1_TYPE::ptr, ASN1_TYPE::type, type, V_ASN1_BOOLEAN, and ASN1_TYPE::value.
Referenced by ASN1_TYPE_pack_sequence(), ASN1_TYPE_set1(), ASN1_TYPE_set_octetstring(), and X509_ATTRIBUTE_set1_data().
ASN1_TYPE_set1()
int ASN1_TYPE_set1 (ASN1_TYPE * a, int type, const void * value)
Definition at line 37 of file a_type.c.
References ASN1_STRING_dup(), ASN1_TYPE_set(), OBJ_dup(), V_ASN1_BOOLEAN, and V_ASN1_OBJECT.
Referenced by X509_ATTRIBUTE_set1_data().
ASN1_TYPE_unpack_sequence()
void* ASN1_TYPE_unpack_sequence (const ASN1_ITEM * it, const ASN1_TYPE * t)
Definition at line 129 of file a_type.c.
References ASN1_item_unpack(), NULL, ASN1_TYPE::sequence, ASN1_TYPE::type, V_ASN1_SEQUENCE, and ASN1_TYPE::value.
Referenced by cms_RecipientInfo_pwri_crypt().