crypto/asn1/a_time.c File Reference
a_time.c File Reference
#include <stdio.h>
#include <time.h>
#include "internal/cryptlib.h"
#include <openssl/asn1t.h>
#include "asn1_locl.h"
Functions
ASN1_TIME * ASN1_TIME_set (ASN1_TIME *s, time_t t)
ASN1_TIME * ASN1_TIME_adj (ASN1_TIME *s, time_t t, int offset_day, long offset_sec)
int ASN1_TIME_check (const ASN1_TIME *t)
ASN1_GENERALIZEDTIME * ASN1_TIME_to_generalizedtime (ASN1_TIME *t, ASN1_GENERALIZEDTIME **out)
int ASN1_TIME_set_string (ASN1_TIME *s, const char *str)
int ASN1_TIME_diff (int *pday, int *psec, const ASN1_TIME *from, const ASN1_TIME *to)
int ASN1_TIME_print (BIO *bp, const ASN1_TIME *tm)
Function Documentation
ASN1_TIME_adj()
ASN1_TIME* ASN1_TIME_adj (ASN1_TIME * s, time_t t, int offset_day, long offset_sec)
Definition at line 32 of file a_time.c.
References ASN1_F_ASN1_TIME_ADJ, ASN1_GENERALIZEDTIME_adj(), ASN1_R_ERROR_GETTING_TIME, ASN1_UTCTIME_adj(), ASN1err, NULL, OPENSSL_gmtime(), and OPENSSL_gmtime_adj().
Referenced by ASN1_TIME_set(), and X509_time_adj_ex().
ASN1_TIME_check()
int ASN1_TIME_check (const ASN1_TIME * t)
Definition at line 52 of file a_time.c.
References ASN1_GENERALIZEDTIME_check(), ASN1_UTCTIME_check(), V_ASN1_GENERALIZEDTIME, and V_ASN1_UTCTIME.
Referenced by ASN1_TIME_set_string().
ASN1_TIME_diff()
int ASN1_TIME_diff (int * pday, int * psec, const ASN1_TIME * from, const ASN1_TIME * to)
Definition at line 144 of file a_time.c.
ASN1_TIME_print()
int ASN1_TIME_print (BIO * bp, const ASN1_TIME * tm)
Definition at line 155 of file a_time.c.
References ASN1_GENERALIZEDTIME_print(), ASN1_UTCTIME_print(), BIO_write(), V_ASN1_GENERALIZEDTIME, and V_ASN1_UTCTIME.
Referenced by verify_callback().
ASN1_TIME_set()
ASN1_TIME* ASN1_TIME_set (ASN1_TIME * s, time_t t)
Definition at line 27 of file a_time.c.
References ASN1_TIME_adj().
ASN1_TIME_set_string()
int ASN1_TIME_set_string (ASN1_TIME * s, const char * str)
Definition at line 104 of file a_time.c.
References ASN1_STRING_copy(), ASN1_TIME_check(), t, V_ASN1_GENERALIZEDTIME, and V_ASN1_UTCTIME.
Referenced by set_cert_times().
ASN1_TIME_to_generalizedtime()
ASN1_GENERALIZEDTIME* ASN1_TIME_to_generalizedtime (ASN1_TIME * t, ASN1_GENERALIZEDTIME ** out)
Definition at line 62 of file a_time.c.
Referenced by OCSP_basic_add1_status().