crypto/asn1/a_utctm.c File Reference
a_utctm.c File Reference
#include <stdio.h>
#include <time.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include "asn1_locl.h"
Functions
int asn1_utctime_to_tm (struct tm *tm, const ASN1_UTCTIME *d)
int ASN1_UTCTIME_check (const ASN1_UTCTIME *d)
int ASN1_UTCTIME_set_string (ASN1_UTCTIME *s, const char *str)
ASN1_UTCTIME * ASN1_UTCTIME_set (ASN1_UTCTIME *s, time_t t)
ASN1_UTCTIME * ASN1_UTCTIME_adj (ASN1_UTCTIME *s, time_t t, int offset_day, long offset_sec)
int ASN1_UTCTIME_cmp_time_t (const ASN1_UTCTIME *s, time_t t)
int ASN1_UTCTIME_print (BIO *bp, const ASN1_UTCTIME *tm)
Function Documentation
ASN1_UTCTIME_adj()
ASN1_UTCTIME* ASN1_UTCTIME_adj (ASN1_UTCTIME * s, time_t t, int offset_day, long offset_sec)
Definition at line 136 of file a_utctm.c.
References ASN1_F_ASN1_UTCTIME_ADJ, ASN1err, BIO_snprintf(), ebcdic2ascii(), ERR_R_MALLOC_FAILURE, if(), len, NULL, OPENSSL_free, OPENSSL_gmtime(), OPENSSL_gmtime_adj(), OPENSSL_malloc, and V_ASN1_UTCTIME.
Referenced by ASN1_TIME_adj(), ASN1_UTCTIME_set(), and X509_time_adj_ex().
ASN1_UTCTIME_check()
int ASN1_UTCTIME_check (const ASN1_UTCTIME * d)
Definition at line 108 of file a_utctm.c.
References asn1_utctime_to_tm(), and NULL.
Referenced by ASN1_TIME_check(), and ASN1_UTCTIME_set_string().
ASN1_UTCTIME_cmp_time_t()
int ASN1_UTCTIME_cmp_time_t (const ASN1_UTCTIME * s, time_t t)
Definition at line 190 of file a_utctm.c.
References asn1_utctime_to_tm(), OPENSSL_gmtime(), and OPENSSL_gmtime_diff().
ASN1_UTCTIME_print()
int ASN1_UTCTIME_print (BIO * bp, const ASN1_UTCTIME * tm)
Definition at line 215 of file a_utctm.c.
References _asn1_mon, BIO_printf(), BIO_write(), h, and if().
Referenced by ASN1_TIME_print().
ASN1_UTCTIME_set()
ASN1_UTCTIME* ASN1_UTCTIME_set (ASN1_UTCTIME * s, time_t t)
Definition at line 131 of file a_utctm.c.
References ASN1_UTCTIME_adj().
ASN1_UTCTIME_set_string()
int ASN1_UTCTIME_set_string (ASN1_UTCTIME * s, const char * str)
Definition at line 113 of file a_utctm.c.
References ASN1_STRING_set(), ASN1_UTCTIME_check(), NULL, t, and V_ASN1_UTCTIME.
asn1_utctime_to_tm()
int asn1_utctime_to_tm (struct tm * tm, const ASN1_UTCTIME * d)
Definition at line 16 of file a_utctm.c.
References if(), max, min, OPENSSL_gmtime_adj(), and V_ASN1_UTCTIME.
Referenced by ASN1_UTCTIME_check(), and ASN1_UTCTIME_cmp_time_t().