crypto/asn1/a_verify.c File Reference
a_verify.c File Reference
#include <stdio.h>
#include <time.h>
#include "internal/cryptlib.h"
#include <sys/types.h>
#include <openssl/bn.h>
#include <openssl/x509.h>
#include <openssl/objects.h>
#include <openssl/buffer.h>
#include <openssl/evp.h>
#include "internal/asn1_int.h"
#include "internal/evp_int.h"
Functions
int ASN1_verify (i2d_of_void *i2d, X509_ALGOR *a, ASN1_BIT_STRING *signature, char *data, EVP_PKEY *pkey)
int ASN1_item_verify (const ASN1_ITEM *it, X509_ALGOR *a, ASN1_BIT_STRING *signature, void *asn, EVP_PKEY *pkey)
Function Documentation
ASN1_item_verify()
int ASN1_item_verify (const ASN1_ITEM * it, X509_ALGOR * a, ASN1_BIT_STRING * signature, void * asn, EVP_PKEY * pkey)
Definition at line 87 of file a_verify.c.
References ctx, and NULL.
Referenced by NETSCAPE_SPKI_verify(), X509_REQ_verify(), and X509_verify().
ASN1_verify()
int ASN1_verify (i2d_of_void * i2d, X509_ALGOR * a, ASN1_BIT_STRING * signature, char * data, EVP_PKEY * pkey)
Definition at line 29 of file a_verify.c.
References ctx, EVP_MD_CTX_new(), NULL, and type.