crypto/aes/aes_core.c File Reference
aes_core.c File Reference
#include <assert.h>
#include <stdlib.h>
#include <openssl/crypto.h>
#include <openssl/aes.h>
#include "aes_locl.h"
Functions
int AES_set_encrypt_key (const unsigned char *userKey, const int bits, AES_KEY *key)
int AES_set_decrypt_key (const unsigned char *userKey, const int bits, AES_KEY *key)
void AES_encrypt (const unsigned char *in, unsigned char *out, const AES_KEY *key)
void AES_decrypt (const unsigned char *in, unsigned char *out, const AES_KEY *key)
Function Documentation
AES_decrypt()
void AES_decrypt (const unsigned char * in, unsigned char * out, const AES_KEY * key)
Definition at line 978 of file aes_core.c.
Referenced by if().
AES_encrypt()
void AES_encrypt (const unsigned char * in, unsigned char * out, const AES_KEY * key)
Definition at line 787 of file aes_core.c.
Referenced by if().
AES_set_decrypt_key()
int AES_set_decrypt_key (const unsigned char * userKey, const int bits, AES_KEY * key)
Expand the cipher key into the decryption key schedule.
Definition at line 734 of file aes_core.c.
Referenced by if().
AES_set_encrypt_key()
int AES_set_encrypt_key (const unsigned char * userKey, const int bits, AES_KEY * key)
Expand the cipher key into the encryption key schedule.
Definition at line 632 of file aes_core.c.
Referenced by AES_set_decrypt_key(), and if().