crypto/asn1/ameth_lib.c File Reference
ameth_lib.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/asn1t.h>
#include <openssl/x509.h>
#include <openssl/engine.h>
#include "internal/asn1_int.h"
#include "internal/evp_int.h"
#include "standard_methods.h"
Typedefs
typedef int sk_cmp_fn_type(const char *const *a, const char *const *b)
Functions
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const EVP_PKEY_ASN1_METHOD *, const EVP_PKEY_ASN1_METHOD *, ameth)
int EVP_PKEY_asn1_get_count (void)
const EVP_PKEY_ASN1_METHOD * EVP_PKEY_asn1_get0 (int idx)
const EVP_PKEY_ASN1_METHOD * EVP_PKEY_asn1_find (ENGINE **pe, int type)
const EVP_PKEY_ASN1_METHOD * EVP_PKEY_asn1_find_str (ENGINE **pe, const char *str, int len)
int EVP_PKEY_asn1_add0 (const EVP_PKEY_ASN1_METHOD *ameth)
int EVP_PKEY_asn1_add_alias (int to, int from)
int EVP_PKEY_asn1_get0_info (int *ppkey_id, int *ppkey_base_id, int *ppkey_flags, const char **pinfo, const char **ppem_str, const EVP_PKEY_ASN1_METHOD *ameth)
const EVP_PKEY_ASN1_METHOD * EVP_PKEY_get0_asn1 (const EVP_PKEY *pkey)
EVP_PKEY_ASN1_METHOD * EVP_PKEY_asn1_new (int id, int flags, const char *pem_str, const char *info)
void EVP_PKEY_asn1_copy (EVP_PKEY_ASN1_METHOD *dst, const EVP_PKEY_ASN1_METHOD *src)
void EVP_PKEY_asn1_free (EVP_PKEY_ASN1_METHOD *ameth)
void EVP_PKEY_asn1_set_public (EVP_PKEY_ASN1_METHOD *ameth, int(*pub_decode)(EVP_PKEY *pk, X509_PUBKEY *pub), int(*pub_encode)(X509_PUBKEY *pub, const EVP_PKEY *pk), int(*pub_cmp)(const EVP_PKEY *a, const EVP_PKEY *b), int(*pub_print)(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx), int(*pkey_size)(const EVP_PKEY *pk), int(*pkey_bits)(const EVP_PKEY *pk))
void EVP_PKEY_asn1_set_private (EVP_PKEY_ASN1_METHOD *ameth, int(*priv_decode)(EVP_PKEY *pk, const PKCS8_PRIV_KEY_INFO *p8inf), int(*priv_encode)(PKCS8_PRIV_KEY_INFO *p8, const EVP_PKEY *pk), int(*priv_print)(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx))
void EVP_PKEY_asn1_set_param (EVP_PKEY_ASN1_METHOD *ameth, int(*param_decode)(EVP_PKEY *pkey, const unsigned char **pder, int derlen), int(*param_encode)(const EVP_PKEY *pkey, unsigned char **pder), int(*param_missing)(const EVP_PKEY *pk), int(*param_copy)(EVP_PKEY *to, const EVP_PKEY *from), int(*param_cmp)(const EVP_PKEY *a, const EVP_PKEY *b), int(*param_print)(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx))
void EVP_PKEY_asn1_set_free (EVP_PKEY_ASN1_METHOD *ameth, void(*pkey_free)(EVP_PKEY *pkey))
void EVP_PKEY_asn1_set_ctrl (EVP_PKEY_ASN1_METHOD *ameth, int(*pkey_ctrl)(EVP_PKEY *pkey, int op, long arg1, void *arg2))
void EVP_PKEY_asn1_set_security_bits (EVP_PKEY_ASN1_METHOD *ameth, int(*pkey_security_bits)(const EVP_PKEY *pk))
void EVP_PKEY_asn1_set_item (EVP_PKEY_ASN1_METHOD *ameth, int(*item_verify)(EVP_MD_CTX *ctx, const ASN1_ITEM *it, void *asn, X509_ALGOR *a, ASN1_BIT_STRING *sig, EVP_PKEY *pkey), int(*item_sign)(EVP_MD_CTX *ctx, const ASN1_ITEM *it, void *asn, X509_ALGOR *alg1, X509_ALGOR *alg2, ASN1_BIT_STRING *sig))
Typedef Documentation
sk_cmp_fn_type
typedef int sk_cmp_fn_type(const char *const *a, const char *const *b)
Definition at line 20 of file ameth_lib.c.
Function Documentation
EVP_PKEY_asn1_add0()
int EVP_PKEY_asn1_add0 (const EVP_PKEY_ASN1_METHOD * ameth)
Definition at line 137 of file ameth_lib.c.
References NULL.
Referenced by EVP_PKEY_asn1_add_alias().
EVP_PKEY_asn1_add_alias()
int EVP_PKEY_asn1_add_alias (int to, int from)
Definition at line 150 of file ameth_lib.c.
References ASN1_PKEY_ALIAS, EVP_PKEY_asn1_add0(), EVP_PKEY_asn1_free(), EVP_PKEY_asn1_new(), and NULL.
EVP_PKEY_asn1_copy()
void EVP_PKEY_asn1_copy (EVP_PKEY_ASN1_METHOD * dst, const EVP_PKEY_ASN1_METHOD * src)
Definition at line 221 of file ameth_lib.c.
EVP_PKEY_asn1_find()
const EVP_PKEY_ASN1_METHOD* EVP_PKEY_asn1_find (ENGINE ** pe, int type)
Definition at line 77 of file ameth_lib.c.
References t.
Referenced by X509_signature_print().
EVP_PKEY_asn1_find_str()
const EVP_PKEY_ASN1_METHOD* EVP_PKEY_asn1_find_str (ENGINE ** pe, const char * str, int len)
Definition at line 102 of file ameth_lib.c.
References ASN1_PKEY_ALIAS, e, ENGINE_free(), ENGINE_init(), ENGINE_pkey_asn1_find_str(), EVP_PKEY_asn1_get0(), EVP_PKEY_asn1_get_count(), and NULL.
EVP_PKEY_asn1_free()
void EVP_PKEY_asn1_free (EVP_PKEY_ASN1_METHOD * ameth)
Definition at line 255 of file ameth_lib.c.
References ASN1_PKEY_DYNAMIC, and OPENSSL_free.
Referenced by engine_pkey_asn1_meths_free(), EVP_PKEY_asn1_add_alias(), and EVP_PKEY_asn1_new().
EVP_PKEY_asn1_get0()
const EVP_PKEY_ASN1_METHOD* EVP_PKEY_asn1_get0 (int idx)
Definition at line 43 of file ameth_lib.c.
Referenced by EVP_PKEY_asn1_find_str().
EVP_PKEY_asn1_get0_info()
int EVP_PKEY_asn1_get0_info (int * ppkey_id, int * ppkey_base_id, int * ppkey_flags, const char ** pinfo, const char ** ppem_str, const EVP_PKEY_ASN1_METHOD * ameth)
Definition at line 164 of file ameth_lib.c.
EVP_PKEY_asn1_get_count()
int EVP_PKEY_asn1_get_count (void)
Definition at line 35 of file ameth_lib.c.
References OSSL_NELEM.
Referenced by EVP_PKEY_asn1_find_str().
EVP_PKEY_asn1_new()
EVP_PKEY_ASN1_METHOD* EVP_PKEY_asn1_new (int id, int flags, const char * pem_str, const char * info)
Definition at line 189 of file ameth_lib.c.
References ASN1_PKEY_DYNAMIC, EVP_PKEY_asn1_free(), NULL, OPENSSL_strdup, and OPENSSL_zalloc.
Referenced by EVP_PKEY_asn1_add_alias().
EVP_PKEY_asn1_set_ctrl()
void EVP_PKEY_asn1_set_ctrl (EVP_PKEY_ASN1_METHOD * ameth, int(*)(EVP_PKEY *pkey, int op, long arg1, void *arg2) pkey_ctrl)
Definition at line 330 of file ameth_lib.c.
EVP_PKEY_asn1_set_free()
void EVP_PKEY_asn1_set_free (EVP_PKEY_ASN1_METHOD * ameth, void(*)(EVP_PKEY *pkey) pkey_free)
Definition at line 324 of file ameth_lib.c.
EVP_PKEY_asn1_set_item()
void EVP_PKEY_asn1_set_item (EVP_PKEY_ASN1_METHOD * ameth, int(*)(EVP_MD_CTX *ctx, const ASN1_ITEM *it, void *asn, X509_ALGOR *a, ASN1_BIT_STRING *sig, EVP_PKEY *pkey) item_verify, int(*)(EVP_MD_CTX *ctx, const ASN1_ITEM *it, void *asn, X509_ALGOR *alg1, X509_ALGOR *alg2, ASN1_BIT_STRING *sig) item_sign)
Definition at line 344 of file ameth_lib.c.
EVP_PKEY_asn1_set_param()
void EVP_PKEY_asn1_set_param (EVP_PKEY_ASN1_METHOD * ameth, int(*)(EVP_PKEY *pkey, const unsigned char **pder, int derlen) param_decode, int(*)(const EVP_PKEY *pkey, unsigned char **pder) param_encode, int(*)(const EVP_PKEY *pk) param_missing, int(*)(EVP_PKEY *to, const EVP_PKEY *from) param_copy, int(*)(const EVP_PKEY *a, const EVP_PKEY *b) param_cmp, int(*)(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx) param_print)
Definition at line 301 of file ameth_lib.c.
EVP_PKEY_asn1_set_private()
void EVP_PKEY_asn1_set_private (EVP_PKEY_ASN1_METHOD * ameth, int(*)(EVP_PKEY *pk, const PKCS8_PRIV_KEY_INFO *p8inf) priv_decode, int(*)(PKCS8_PRIV_KEY_INFO *p8, const EVP_PKEY *pk) priv_encode, int(*)(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx) priv_print)
Definition at line 285 of file ameth_lib.c.
EVP_PKEY_asn1_set_public()
void EVP_PKEY_asn1_set_public (EVP_PKEY_ASN1_METHOD * ameth, int(*)(EVP_PKEY *pk, X509_PUBKEY *pub) pub_decode, int(*)(X509_PUBKEY *pub, const EVP_PKEY *pk) pub_encode, int(*)(const EVP_PKEY *a, const EVP_PKEY *b) pub_cmp, int(*)(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx) pub_print, int(*)(const EVP_PKEY *pk) pkey_size, int(*)(const EVP_PKEY *pk) pkey_bits)
Definition at line 264 of file ameth_lib.c.
EVP_PKEY_asn1_set_security_bits()
void EVP_PKEY_asn1_set_security_bits (EVP_PKEY_ASN1_METHOD * ameth, int(*)(const EVP_PKEY *pk) pkey_security_bits)
Definition at line 337 of file ameth_lib.c.
EVP_PKEY_get0_asn1()
const EVP_PKEY_ASN1_METHOD* EVP_PKEY_get0_asn1 (const EVP_PKEY * pkey)
Definition at line 184 of file ameth_lib.c.
IMPLEMENT_OBJ_BSEARCH_CMP_FN()
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const EVP_PKEY_ASN1_METHOD * , const EVP_PKEY_ASN1_METHOD * , ameth)