apps/app_rand.c File Reference
app_rand.c File Reference
#include "apps.h"
#include <openssl/bio.h>
#include <openssl/rand.h>
Functions
int app_RAND_load_file (const char *file, int dont_warn)
long app_RAND_load_files (char *name)
int app_RAND_write_file (const char *file)
void app_RAND_allow_write_file (void)
Function Documentation
app_RAND_allow_write_file()
void app_RAND_allow_write_file (void)
Definition at line 112 of file app_rand.c.
Referenced by app_RAND_load_files().
app_RAND_load_file()
int app_RAND_load_file (const char * file, int dont_warn)
Definition at line 17 of file app_rand.c.
References NULL, RAND_egd(), and RAND_file_name().
app_RAND_load_files()
long app_RAND_load_files (char * name)
Definition at line 56 of file app_rand.c.
References app_RAND_allow_write_file(), LIST_SEPARATOR_CHAR, RAND_egd(), and RAND_load_file().
app_RAND_write_file()
int app_RAND_write_file (const char * file)
Definition at line 91 of file app_rand.c.