apps/apps.h File Reference
apps.h File Reference
#include "e_os.h"
#include <assert.h>
#include <openssl/e_os2.h>
#include <openssl/ossl_typ.h>
#include <openssl/bio.h>
#include <openssl/x509.h>
#include <openssl/lhash.h>
#include <openssl/conf.h>
#include <openssl/txt_db.h>
#include <openssl/engine.h>
#include <openssl/ocsp.h>
#include <signal.h>
#include "progs.h"
Data Structures
struct OPTIONS
struct STRINT_PAIR
struct ARGS
struct PW_CB_DATA
struct DB_ATTR
struct CA_DB
struct VERIFY_CB_ARGS
Macros
#define openssl_fdset(a, b) FD_SET(a, b)
#define _UC(c) ((unsigned char)(c))
#define OPT_V_ENUM
#define OPT_V_OPTIONS
#define OPT_V_CASES
#define OPT_X_ENUM
#define OPT_X_OPTIONS
#define OPT_X_CASES
#define OPT_S_ENUM
#define OPT_S_OPTIONS
#define OPT_S_CASES
#define IS_NO_PROT_FLAG(o)
#define OPT_FMT_PEMDER (1L << 1)
#define OPT_FMT_PKCS12 (1L << 2)
#define OPT_FMT_SMIME (1L << 3)
#define OPT_FMT_ENGINE (1L << 4)
#define OPT_FMT_MSBLOB (1L << 5)
#define OPT_FMT_NETSCAPE (1L << 6)
#define OPT_FMT_NSS (1L << 7)
#define OPT_FMT_TEXT (1L << 8)
#define OPT_FMT_HTTP (1L << 9)
#define OPT_FMT_PVK (1L << 10)
#define OPT_FMT_PDE (OPT_FMT_PEMDER | OPT_FMT_ENGINE)
#define OPT_FMT_PDS (OPT_FMT_PEMDER | OPT_FMT_SMIME)
#define OPT_FMT_ANY
#define opt_imax opt_long
#define opt_umax opt_ulong
#define intmax_t long
#define uintmax_t unsigned long
#define PW_MIN_LENGTH 4
#define DB_type 0
#define DB_exp_date 1
#define DB_rev_date 2
#define DB_serial 3 /* index - unique */
#define DB_file 4
#define DB_name
#define DB_NUMBER 6
#define DB_TYPE_REV 'R' /* Revoked */
#define DB_TYPE_EXP 'E' /* Expired */
#define DB_TYPE_VAL 'V' /* Valid ; inserted with: ca ... -valid */
#define DB_TYPE_SUSP 'S' /* Suspended */
#define index_name_cmp_noconst(a, b)
#define B_FORMAT_TEXT 0x8000
#define FORMAT_UNDEF 0
#define FORMAT_TEXT (1 | B_FORMAT_TEXT) /* Generic text */
#define FORMAT_BINARY 2 /* Generic binary */
#define FORMAT_BASE64 (3 | B_FORMAT_TEXT) /* Base64 */
#define FORMAT_ASN1 4 /* ASN.1/DER */
#define FORMAT_PEM (5 | B_FORMAT_TEXT)
#define FORMAT_PKCS12 6
#define FORMAT_SMIME (7 | B_FORMAT_TEXT)
#define FORMAT_ENGINE 8 /* Not really a file format */
#define FORMAT_PEMRSA (9 | B_FORMAT_TEXT) /* PEM RSAPubicKey format */
#define FORMAT_ASN1RSA 10 /* DER RSAPubicKey format */
#define FORMAT_MSBLOB 11 /* MS Key blob format */
#define FORMAT_PVK 12 /* MS PVK file format */
#define FORMAT_HTTP 13 /* Download using HTTP */
#define FORMAT_NSS 14 /* NSS keylog format */
#define EXT_COPY_NONE 0
#define EXT_COPY_ADD 1
#define EXT_COPY_ALL 2
#define NETSCAPE_CERT_HDR "certificate"
#define APP_PASS_LEN 1024
#define SERIAL_RAND_BITS 64
#define TM_START 0
#define TM_STOP 1
Functions
int app_RAND_load_file (const char *file, int dont_warn)
int app_RAND_write_file (const char *file)
void app_RAND_allow_write_file (void)
long app_RAND_load_files (char *file)
BIO * dup_bio_in (int format)
BIO * dup_bio_out (int format)
BIO * dup_bio_err (int format)
BIO * bio_open_owner (const char *filename, int format, int private)
BIO * bio_open_default (const char *filename, char mode, int format)
BIO * bio_open_default_quiet (const char *filename, char mode, int format)
CONF * app_load_config (const char *filename)
CONF * app_load_config_quiet (const char *filename)
int app_load_modules (const CONF *config)
void unbuffer (FILE *fp)
void wait_for_async (SSL *s)
void corrupt_signature (const ASN1_STRING *signature)
int set_cert_times (X509 *x, const char *startdate, const char *enddate, int days)
char * opt_progname (const char *argv0)
char * opt_getprog (void)
char * opt_init (int ac, char **av, const OPTIONS *o)
int opt_next (void)
int opt_format (const char *s, unsigned long flags, int *result)
int opt_int (const char *arg, int *result)
int opt_ulong (const char *arg, unsigned long *result)
int opt_long (const char *arg, long *result)
int opt_pair (const char *arg, const OPT_PAIR *pairs, int *result)
int opt_cipher (const char *name, const EVP_CIPHER **cipherp)
int opt_md (const char *name, const EVP_MD **mdp)
char * opt_arg (void)
char * opt_flag (void)
char * opt_unknown (void)
char * opt_reset (void)
char ** opt_rest (void)
int opt_num_rest (void)
int opt_verify (int i, X509_VERIFY_PARAM *vpm)
void opt_help (const OPTIONS *list)
int opt_format_error (const char *s, unsigned long flags)
char ** copy_argv (int *argc, char *argv[])
void win32_utf8argv (int *argc, char **argv[])
int password_callback (char *buf, int bufsiz, int verify, PW_CB_DATA *cb_data)
int setup_ui_method (void)
void destroy_ui_method (void)
const UI_METHOD * get_ui_method (void)
int chopup_args (ARGS *arg, char *buf)
void print_bignum_var (BIO *, const BIGNUM *, const char *, int, unsigned char *)
void print_array (BIO *, const char *, int, const unsigned char *)
int set_cert_ex (unsigned long *flags, const char *arg)
int set_name_ex (unsigned long *flags, const char *arg)
int set_ext_copy (int *copy_type, const char *arg)
int copy_extensions (X509 *x, X509_REQ *req, int copy_type)
int app_passwd (const char *arg1, const char *arg2, char **pass1, char **pass2)
int add_oid_section (CONF *conf)
X509 * load_cert (const char *file, int format, const char *cert_descrip)
X509_CRL * load_crl (const char *infile, int format)
EVP_PKEY * load_key (const char *file, int format, int maybe_stdin, const char *pass, ENGINE *e, const char *key_descrip)
EVP_PKEY * load_pubkey (const char *file, int format, int maybe_stdin, const char *pass, ENGINE *e, const char *key_descrip)
int load_certs (const char *file, STACK_OF(X509) **certs, int format, const char *pass, const char *cert_descrip)
int load_crls (const char *file, STACK_OF(X509_CRL) **crls, int format, const char *pass, const char *cert_descrip)
X509_STORE * setup_verify (const char *CAfile, const char *CApath, int noCAfile, int noCApath)
__owur int ctx_set_verify_locations (SSL_CTX *ctx, const char *CAfile, const char *CApath, int noCAfile, int noCApath)
__owur int ctx_set_ctlog_list_file (SSL_CTX *ctx, const char *path)
ENGINE * setup_engine (const char *engine, int debug)
void release_engine (ENGINE *e)
OCSP_RESPONSE * process_responder (OCSP_REQUEST *req, const char *host, const char *path, const char *port, int use_ssl, STACK_OF(CONF_VALUE) *headers, int req_timeout)
int unpack_revinfo (ASN1_TIME **prevtm, int *preason, ASN1_OBJECT **phold, ASN1_GENERALIZEDTIME **pinvtm, const char *str)
void * app_malloc (int sz, const char *what)
BIGNUM * load_serial (const char *serialfile, int create, ASN1_INTEGER **retai)
int save_serial (const char *serialfile, const char *suffix, const BIGNUM *serial, ASN1_INTEGER **retai)
int rotate_serial (const char *serialfile, const char *new_suffix, const char *old_suffix)
int rand_serial (BIGNUM *b, ASN1_INTEGER *ai)
CA_DB * load_index (const char *dbfile, DB_ATTR *dbattr)
int index_index (CA_DB *db)
int save_index (const char *dbfile, const char *suffix, CA_DB *db)
int rotate_index (const char *dbfile, const char *new_suffix, const char *old_suffix)
void free_index (CA_DB *db)
int index_name_cmp (const OPENSSL_CSTRING *a, const OPENSSL_CSTRING *b)
int parse_yesno (const char *str, int def)
X509_NAME * parse_name (const char *str, long chtype, int multirdn)
int args_verify (char ***pargs, int *pargc, int *badarg, X509_VERIFY_PARAM **pm)
void policies_print (X509_STORE_CTX *ctx)
int bio_to_mem (unsigned char **out, int maxlen, BIO *in)
int pkey_ctrl_string (EVP_PKEY_CTX *ctx, const char *value)
int init_gen_str (EVP_PKEY_CTX **pctx, const char *algname, ENGINE *e, int do_param)
int do_X509_sign (X509 *x, EVP_PKEY *pkey, const EVP_MD *md, STACK_OF(OPENSSL_STRING) *sigopts)
int do_X509_REQ_sign (X509_REQ *x, EVP_PKEY *pkey, const EVP_MD *md, STACK_OF(OPENSSL_STRING) *sigopts)
int do_X509_CRL_sign (X509_CRL *x, EVP_PKEY *pkey, const EVP_MD *md, STACK_OF(OPENSSL_STRING) *sigopts)
unsigned char * next_protos_parse (size_t *outlen, const char *in)
void print_cert_checks (BIO *bio, X509 *x, const char *checkhost, const char *checkemail, const char *checkip)
void store_setup_crl_download (X509_STORE *st)
int app_isdir (const char *)
int app_access (const char *, int flag)
int fileno_stdin (void)
int fileno_stdout (void)
int raw_read_stdin (void *, int)
int raw_write_stdout (const void *, int)
double app_tminterval (int stop, int usertime)
void make_uppercase (char *string)
Variables
char * default_config_file
BIO * bio_in
BIO * bio_out
BIO * bio_err
const char OPT_HELP_STR []
const char OPT_MORE_STR []
char * psk_key
VERIFY_CB_ARGS verify_args
Macro Definition Documentation
_UC
#define _UC (c) ((unsigned char)(c))
Definition at line 41 of file apps.h.
APP_PASS_LEN
#define APP_PASS_LEN 1024
Definition at line 547 of file apps.h.
B_FORMAT_TEXT
#define B_FORMAT_TEXT 0x8000
Definition at line 524 of file apps.h.
DB_exp_date
#define DB_exp_date 1
Definition at line 452 of file apps.h.
DB_file
#define DB_file 4
Definition at line 455 of file apps.h.
DB_name
#define DB_name
Value:
5      /* index - unique when active and not
                                 * disabled */
Definition at line 456 of file apps.h.
Referenced by index_index(), and index_name_cmp().
DB_NUMBER
#define DB_NUMBER 6
Definition at line 458 of file apps.h.
Referenced by SRP_VBASE_init().
DB_rev_date
#define DB_rev_date 2
Definition at line 453 of file apps.h.
DB_serial
#define DB_serial 3 /* index - unique */
Definition at line 454 of file apps.h.
Referenced by index_index().
DB_type
#define DB_type 0
Definition at line 451 of file apps.h.
DB_TYPE_EXP
#define DB_TYPE_EXP 'E' /* Expired */
Definition at line 461 of file apps.h.
DB_TYPE_REV
#define DB_TYPE_REV 'R' /* Revoked */
Definition at line 460 of file apps.h.
DB_TYPE_SUSP
#define DB_TYPE_SUSP 'S' /* Suspended */
Definition at line 463 of file apps.h.
DB_TYPE_VAL
#define DB_TYPE_VAL 'V' /* Valid ; inserted with: ca ... -valid */
Definition at line 462 of file apps.h.
EXT_COPY_ADD
#define EXT_COPY_ADD 1
Definition at line 542 of file apps.h.
EXT_COPY_ALL
#define EXT_COPY_ALL 2
Definition at line 543 of file apps.h.
EXT_COPY_NONE
#define EXT_COPY_NONE 0
Definition at line 541 of file apps.h.
FORMAT_ASN1
#define FORMAT_ASN1 4 /* ASN.1/DER */
Definition at line 529 of file apps.h.
Referenced by opt_format().
FORMAT_ASN1RSA
#define FORMAT_ASN1RSA 10 /* DER RSAPubicKey format */
Definition at line 535 of file apps.h.
FORMAT_BASE64
#define FORMAT_BASE64 (3 | B_FORMAT_TEXT) /* Base64 */
Definition at line 528 of file apps.h.
FORMAT_BINARY
#define FORMAT_BINARY 2 /* Generic binary */
Definition at line 527 of file apps.h.
FORMAT_ENGINE
#define FORMAT_ENGINE 8 /* Not really a file format */
Definition at line 533 of file apps.h.
Referenced by load_key(), load_pubkey(), and opt_format().
FORMAT_HTTP
#define FORMAT_HTTP 13 /* Download using HTTP */
Definition at line 538 of file apps.h.
Referenced by load_crl(), and opt_format().
FORMAT_MSBLOB
#define FORMAT_MSBLOB 11 /* MS Key blob format */
Definition at line 536 of file apps.h.
Referenced by opt_format().
FORMAT_NSS
#define FORMAT_NSS 14 /* NSS keylog format */
Definition at line 539 of file apps.h.
Referenced by opt_format().
FORMAT_PEM
#define FORMAT_PEM (5 | B_FORMAT_TEXT)
Definition at line 530 of file apps.h.
Referenced by load_excert(), and opt_format().
FORMAT_PEMRSA
#define FORMAT_PEMRSA (9 | B_FORMAT_TEXT) /* PEM RSAPubicKey format */
Definition at line 534 of file apps.h.
FORMAT_PKCS12
#define FORMAT_PKCS12 6
Definition at line 531 of file apps.h.
Referenced by opt_format().
FORMAT_PVK
#define FORMAT_PVK 12 /* MS PVK file format */
Definition at line 537 of file apps.h.
Referenced by opt_format().
FORMAT_SMIME
#define FORMAT_SMIME (7 | B_FORMAT_TEXT)
Definition at line 532 of file apps.h.
Referenced by opt_format().
FORMAT_TEXT
#define FORMAT_TEXT (1 | B_FORMAT_TEXT) /* Generic text */
Definition at line 526 of file apps.h.
Referenced by opt_format().
FORMAT_UNDEF
#define FORMAT_UNDEF 0
Definition at line 525 of file apps.h.
index_name_cmp_noconst
#define index_name_cmp_noconst (a, b)
Value:
index_name_cmp((const OPENSSL_CSTRING *)CHECKED_PTR_OF(OPENSSL_STRING, a), \
        (const OPENSSL_CSTRING *)CHECKED_PTR_OF(OPENSSL_STRING, b))
Definition at line 486 of file apps.h.
intmax_t
#define intmax_t long
Definition at line 347 of file apps.h.
IS_NO_PROT_FLAG
#define IS_NO_PROT_FLAG (o)
Value:
(o == OPT_S_NOSSL3 || o == OPT_S_NOTLS1 || o == OPT_S_NOTLS1_1 \
  || o == OPT_S_NOTLS1_2 || o == OPT_S_NOTLS1_3)
Definition at line 282 of file apps.h.
NETSCAPE_CERT_HDR
#define NETSCAPE_CERT_HDR "certificate"
Definition at line 545 of file apps.h.
openssl_fdset
#define openssl_fdset (a, b) FD_SET(a, b)
Definition at line 33 of file apps.h.
Referenced by wait_for_async().
OPT_FMT_ANY
#define OPT_FMT_ANY
Value:
(\
        OPT_FMT_PEMDER | OPT_FMT_PKCS12 | OPT_FMT_SMIME | \
        OPT_FMT_ENGINE | OPT_FMT_MSBLOB | OPT_FMT_NETSCAPE | \
        OPT_FMT_NSS | OPT_FMT_TEXT | OPT_FMT_HTTP | OPT_FMT_PVK)
Definition at line 327 of file apps.h.
OPT_FMT_ENGINE
#define OPT_FMT_ENGINE (1L << 4)
Definition at line 318 of file apps.h.
Referenced by opt_format().
OPT_FMT_HTTP
#define OPT_FMT_HTTP (1L << 9)
Definition at line 323 of file apps.h.
Referenced by opt_format().
OPT_FMT_MSBLOB
#define OPT_FMT_MSBLOB (1L << 5)
Definition at line 319 of file apps.h.
Referenced by opt_format().
OPT_FMT_NETSCAPE
#define OPT_FMT_NETSCAPE (1L << 6)
Definition at line 320 of file apps.h.
OPT_FMT_NSS
#define OPT_FMT_NSS (1L << 7)
Definition at line 321 of file apps.h.
Referenced by opt_format().
OPT_FMT_PDE
#define OPT_FMT_PDE (OPT_FMT_PEMDER | OPT_FMT_ENGINE)
Definition at line 325 of file apps.h.
OPT_FMT_PDS
#define OPT_FMT_PDS (OPT_FMT_PEMDER | OPT_FMT_SMIME)
Definition at line 326 of file apps.h.
OPT_FMT_PEMDER
#define OPT_FMT_PEMDER (1L << 1)
Definition at line 315 of file apps.h.
Referenced by opt_format(), and opt_format_error().
OPT_FMT_PKCS12
#define OPT_FMT_PKCS12 (1L << 2)
Definition at line 316 of file apps.h.
Referenced by opt_format().
OPT_FMT_PVK
#define OPT_FMT_PVK (1L << 10)
Definition at line 324 of file apps.h.
Referenced by opt_format().
OPT_FMT_SMIME
#define OPT_FMT_SMIME (1L << 3)
Definition at line 317 of file apps.h.
Referenced by opt_format().
OPT_FMT_TEXT
#define OPT_FMT_TEXT (1L << 8)
Definition at line 322 of file apps.h.
Referenced by opt_format().
opt_imax
#define opt_imax opt_long
Definition at line 345 of file apps.h.
OPT_S_CASES
#define OPT_S_CASES
Value:
OPT_S__FIRST: case OPT_S__LAST: break; \
        case OPT_S_NOSSL3: \
        case OPT_S_NOTLS1: \
        case OPT_S_NOTLS1_1: \
        case OPT_S_NOTLS1_2: \
        case OPT_S_NOTLS1_3: \
        case OPT_S_BUGS: \
        case OPT_S_NO_COMP: \
        case OPT_S_COMP: \
        case OPT_S_NOTICKET: \
        case OPT_S_SERVERPREF: \
        case OPT_S_LEGACYRENEG: \
        case OPT_S_LEGACYCONN: \
        case OPT_S_ONRESUMP: \
        case OPT_S_NOLEGACYCONN: \
        case OPT_S_STRICT: \
        case OPT_S_SIGALGS: \
        case OPT_S_CLIENTSIGALGS: \
        case OPT_S_CURVES: \
        case OPT_S_NAMEDCURVE: \
        case OPT_S_CIPHER: \
        case OPT_S_DHPARAM: \
        case OPT_S_DEBUGBROKE
Definition at line 257 of file apps.h.
OPT_S_ENUM
#define OPT_S_ENUM
Value:
OPT_S__FIRST=3000, \
        OPT_S_NOSSL3, OPT_S_NOTLS1, OPT_S_NOTLS1_1, OPT_S_NOTLS1_2, \
        OPT_S_NOTLS1_3, OPT_S_BUGS, OPT_S_NO_COMP, OPT_S_NOTICKET, \
        OPT_S_SERVERPREF, OPT_S_LEGACYRENEG, OPT_S_LEGACYCONN, \
        OPT_S_ONRESUMP, OPT_S_NOLEGACYCONN, OPT_S_STRICT, OPT_S_SIGALGS, \
        OPT_S_CLIENTSIGALGS, OPT_S_CURVES, OPT_S_NAMEDCURVE, OPT_S_CIPHER, \
        OPT_S_DHPARAM, OPT_S_DEBUGBROKE, OPT_S_COMP, \
        OPT_S__LAST
Definition at line 210 of file apps.h.
OPT_S_OPTIONS
#define OPT_S_OPTIONS
Definition at line 220 of file apps.h.
opt_umax
#define opt_umax opt_ulong
Definition at line 346 of file apps.h.
OPT_V_CASES
#define OPT_V_CASES
Definition at line 144 of file apps.h.
OPT_V_ENUM
#define OPT_V_ENUM
Value:
OPT_V__FIRST=2000, \
        OPT_V_POLICY, OPT_V_PURPOSE, OPT_V_VERIFY_NAME, OPT_V_VERIFY_DEPTH, \
        OPT_V_ATTIME, OPT_V_VERIFY_HOSTNAME, OPT_V_VERIFY_EMAIL, \
        OPT_V_VERIFY_IP, OPT_V_IGNORE_CRITICAL, OPT_V_ISSUER_CHECKS, \
        OPT_V_CRL_CHECK, OPT_V_CRL_CHECK_ALL, OPT_V_POLICY_CHECK, \
        OPT_V_EXPLICIT_POLICY, OPT_V_INHIBIT_ANY, OPT_V_INHIBIT_MAP, \
        OPT_V_X509_STRICT, OPT_V_EXTENDED_CRL, OPT_V_USE_DELTAS, \
        OPT_V_POLICY_PRINT, OPT_V_CHECK_SS_SIG, OPT_V_TRUSTED_FIRST, \
        OPT_V_SUITEB_128_ONLY, OPT_V_SUITEB_128, OPT_V_SUITEB_192, \
        OPT_V_PARTIAL_CHAIN, OPT_V_NO_ALT_CHAINS, OPT_V_NO_CHECK_TIME, \
        OPT_V_VERIFY_AUTH_LEVEL, OPT_V_ALLOW_PROXY_CERTS, \
        OPT_V__LAST
Definition at line 80 of file apps.h.
OPT_V_OPTIONS
#define OPT_V_OPTIONS
Definition at line 94 of file apps.h.
OPT_X_CASES
#define OPT_X_CASES
Value:
OPT_X__FIRST: case OPT_X__LAST: break; \
        case OPT_X_KEY: \
        case OPT_X_CERT: \
        case OPT_X_CHAIN: \
        case OPT_X_CHAIN_BUILD: \
        case OPT_X_CERTFORM: \
        case OPT_X_KEYFORM
Definition at line 197 of file apps.h.
OPT_X_ENUM
#define OPT_X_ENUM
Value:
OPT_X__FIRST=1000, \
        OPT_X_KEY, OPT_X_CERT, OPT_X_CHAIN, OPT_X_CHAIN_BUILD, \
        OPT_X_CERTFORM, OPT_X_KEYFORM, \
        OPT_X__LAST
Definition at line 180 of file apps.h.
OPT_X_OPTIONS
#define OPT_X_OPTIONS
Value:
{ "xkey", OPT_X_KEY, '<', "key for Extended certificates"}, \
        { "xcert", OPT_X_CERT, '<', "cert for Extended certificates"}, \
        { "xchain", OPT_X_CHAIN, '<', "chain for Extended certificates"}, \
        { "xchain_build", OPT_X_CHAIN_BUILD, '-', \
            "build certificate chain for the extended certificates"}, \
        { "xcertform", OPT_X_CERTFORM, 'F', \
            "format of Extended certificate (PEM or DER) PEM default " }, \
        { "xkeyform", OPT_X_KEYFORM, 'F', \
            "format of Extended certificate's key (PEM or DER) PEM default"}
Definition at line 186 of file apps.h.
PW_MIN_LENGTH
#define PW_MIN_LENGTH 4
Definition at line 382 of file apps.h.
SERIAL_RAND_BITS
#define SERIAL_RAND_BITS 64
Definition at line 549 of file apps.h.
TM_START
#define TM_START 0
Definition at line 558 of file apps.h.
TM_STOP
#define TM_STOP 1
Definition at line 559 of file apps.h.
uintmax_t
#define uintmax_t unsigned long
Definition at line 348 of file apps.h.
Function Documentation
add_oid_section()
int add_oid_section (CONF * conf)
Definition at line 493 of file apps.c.
app_access()
int app_access (const char * , int flag)
Definition at line 2258 of file apps.c.
app_isdir()
int app_isdir (const char *)
Definition at line 2305 of file apps.c.
References fileno_stdin(), S_ISDIR, TERM_SOCK_CREATE, TERM_SOCK_DELETE, and TerminalSocket().
app_load_config()
CONF* app_load_config (const char * filename)
Definition at line 447 of file apps.c.
References in.
app_load_config_quiet()
CONF* app_load_config_quiet (const char * filename)
Definition at line 460 of file apps.c.
References in.
app_load_modules()
int app_load_modules (const CONF * config)
Definition at line 474 of file apps.c.
app_malloc()
void* app_malloc (int sz, const char * what)
Definition at line 925 of file apps.c.
References bio_err, BIO_printf(), ERR_print_errors(), NULL, OPENSSL_malloc, and opt_getprog().
Referenced by ssl_print_groups(), and wait_for_async().
app_passwd()
int app_passwd (const char * arg1, const char * arg2, char ** pass1, char ** pass2)
Definition at line 332 of file apps.c.
app_RAND_allow_write_file()
void app_RAND_allow_write_file (void)
Definition at line 112 of file app_rand.c.
Referenced by app_RAND_load_files().
app_RAND_load_file()
int app_RAND_load_file (const char * file, int dont_warn)
Definition at line 17 of file app_rand.c.
References NULL, RAND_egd(), and RAND_file_name().
app_RAND_load_files()
long app_RAND_load_files (char * file)
Definition at line 56 of file app_rand.c.
References app_RAND_allow_write_file(), LIST_SEPARATOR_CHAR, RAND_egd(), and RAND_load_file().
app_RAND_write_file()
int app_RAND_write_file (const char * file)
Definition at line 91 of file app_rand.c.
app_tminterval()
double app_tminterval (int stop, int usertime)
Definition at line 2236 of file apps.c.
args_verify()
int args_verify (char *** pargs, int * pargc, int * badarg, X509_VERIFY_PARAM ** pm)
bio_open_default()
BIO* bio_open_default (const char * filename, char mode, int format)
Definition at line 2573 of file apps.c.
Referenced by bio_open_owner().
bio_open_default_quiet()
BIO* bio_open_default_quiet (const char * filename, char mode, int format)
Definition at line 2578 of file apps.c.
bio_open_owner()
BIO* bio_open_owner (const char * filename, int format, int private)
Definition at line 2481 of file apps.c.
References bio_open_default(), fp, and NULL.
bio_to_mem()
int bio_to_mem (unsigned char ** out, int maxlen, BIO * in)
Definition at line 1801 of file apps.c.
chopup_args()
int chopup_args (ARGS * arg, char * buf)
Definition at line 70 of file apps.c.
copy_argv()
char** copy_argv (int * argc, char * argv[])
copy_extensions()
int copy_extensions (X509 * x, X509_REQ * req, int copy_type)
Definition at line 1048 of file apps.c.
corrupt_signature()
void corrupt_signature (const ASN1_STRING * signature)
Definition at line 2642 of file apps.c.
ctx_set_ctlog_list_file()
__owur int ctx_set_ctlog_list_file (SSL_CTX * ctx, const char * path)
Definition at line 141 of file apps.c.
References NULL, SSL_CTX_set_ctlog_list_file(), and SSL_CTX_set_default_ctlog_list_file().
ctx_set_verify_locations()
__owur int ctx_set_verify_locations (SSL_CTX * ctx, const char * CAfile, const char * CApath, int noCAfile, int noCApath)
Definition at line 125 of file apps.c.
References NULL, SSL_CTX_load_verify_locations(), SSL_CTX_set_default_verify_dir(), and SSL_CTX_set_default_verify_file().
destroy_ui_method()
void destroy_ui_method (void)
Definition at line 241 of file apps.c.
do_X509_CRL_sign()
int do_X509_CRL_sign (X509_CRL * x, EVP_PKEY * pkey, const EVP_MD * md, STACK_OF(OPENSSL_STRING) * sigopts)
Definition at line 1498 of file req.c.
References EVP_MD_CTX_new().
do_X509_REQ_sign()
int do_X509_REQ_sign (X509_REQ * x, EVP_PKEY * pkey, const EVP_MD * md, STACK_OF(OPENSSL_STRING) * sigopts)
Definition at line 1486 of file req.c.
References EVP_MD_CTX_new().
do_X509_sign()
int do_X509_sign (X509 * x, EVP_PKEY * pkey, const EVP_MD * md, STACK_OF(OPENSSL_STRING) * sigopts)
Definition at line 1473 of file req.c.
References EVP_MD_CTX_new().
dup_bio_err()
BIO* dup_bio_err (int format)
Definition at line 2419 of file apps.c.
References BIO_new_fp(), and BIO_NOCLOSE.
dup_bio_in()
BIO* dup_bio_in (int format)
Definition at line 2402 of file apps.c.
References BIO_new_fp(), and BIO_NOCLOSE.
dup_bio_out()
BIO* dup_bio_out (int format)
Definition at line 2408 of file apps.c.
References BIO_new_fp(), and BIO_NOCLOSE.
fileno_stdin()
int fileno_stdin (void)
Definition at line 2340 of file apps.c.
Referenced by app_isdir(), and raw_read_stdin().
fileno_stdout()
int fileno_stdout (void)
Definition at line 2346 of file apps.c.
References raw_read_stdin().
Referenced by raw_write_stdout().
free_index()
void free_index (CA_DB * db)
Definition at line 1685 of file apps.c.
References CA_DB::db, OPENSSL_free, and TXT_DB_free().
get_ui_method()
const UI_METHOD* get_ui_method (void)
Definition at line 249 of file apps.c.
index_index()
int index_index (CA_DB * db)
Definition at line 1551 of file apps.c.
References TXT_DB::arg1, TXT_DB::arg2, CA_DB::attributes, bio_err, BIO_printf(), CA_DB::db, DB_name, DB_serial, TXT_DB::error, LHASH_COMP_FN, LHASH_HASH_FN, NULL, TXT_DB_create_index(), and DB_ATTR::unique_subject.
index_name_cmp()
int index_name_cmp (const OPENSSL_CSTRING * a, const OPENSSL_CSTRING * b)
Definition at line 1328 of file apps.c.
References DB_name, IMPLEMENT_LHASH_COMP_FN, IMPLEMENT_LHASH_HASH_FN, in, load_serial(), and NULL.
init_gen_str()
int init_gen_str (EVP_PKEY_CTX ** pctx, const char * algname, ENGINE * e, int do_param)
Definition at line 243 of file genpkey.c.
load_cert()
X509* load_cert (const char * file, int format, const char * cert_descrip)
Definition at line 608 of file apps.c.
References NULL.
Referenced by load_excert().
load_certs()
int load_certs (const char * file, STACK_OF(X509) ** certs, int format, const char * pass, const char * cert_descrip)
Definition at line 941 of file apps.c.
Referenced by load_excert().
load_crl()
X509_CRL* load_crl (const char * infile, int format)
Definition at line 649 of file apps.c.
References FORMAT_HTTP, in, and NULL.
load_crls()
int load_crls (const char * file, STACK_OF(X509_CRL) ** crls, int format, const char * pass, const char * cert_descrip)
Definition at line 950 of file apps.c.
load_index()
CA_DB* load_index (const char * dbfile, DB_ATTR * dbattr)
Definition at line 1505 of file apps.c.
References in, and NULL.
load_key()
EVP_PKEY* load_key (const char * file, int format, int maybe_stdin, const char * pass, ENGINE * e, const char * key_descrip)
Definition at line 683 of file apps.c.
References bio_err, BIO_printf(), ENGINE_init(), ENGINE_load_private_key(), file, FORMAT_ENGINE, key, NULL, pass, PW_CB_DATA::password, and PW_CB_DATA::prompt_info.
Referenced by load_excert().
load_pubkey()
EVP_PKEY* load_pubkey (const char * file, int format, int maybe_stdin, const char * pass, ENGINE * e, const char * key_descrip)
Definition at line 756 of file apps.c.
References bio_err, BIO_printf(), ENGINE_load_public_key(), file, FORMAT_ENGINE, key, NULL, pass, PW_CB_DATA::password, and PW_CB_DATA::prompt_info.
load_serial()
BIGNUM* load_serial (const char * serialfile, int create, ASN1_INTEGER ** retai)
Referenced by index_name_cmp().
make_uppercase()
void make_uppercase (char * string)
Definition at line 2668 of file apps.c.
next_protos_parse()
unsigned char* next_protos_parse (size_t * outlen, const char * in)
Definition at line 1893 of file apps.c.
References len.
opt_arg()
char* opt_arg (void)
Definition at line 750 of file opt.c.
Referenced by opt_verify().
opt_cipher()
int opt_cipher (const char * name, const EVP_CIPHER ** cipherp)
Definition at line 277 of file opt.c.
References bio_err, BIO_printf(), and EVP_get_cipherbyname().
opt_flag()
char* opt_flag (void)
Definition at line 756 of file opt.c.
opt_format()
int opt_format (const char * s, unsigned long flags, int * result)
Definition at line 200 of file opt.c.
References FORMAT_ASN1, FORMAT_ENGINE, FORMAT_HTTP, FORMAT_MSBLOB, FORMAT_NSS, FORMAT_PEM, FORMAT_PKCS12, FORMAT_PVK, FORMAT_SMIME, FORMAT_TEXT, OPT_FMT_ENGINE, OPT_FMT_HTTP, OPT_FMT_MSBLOB, OPT_FMT_NSS, OPT_FMT_PEMDER, OPT_FMT_PKCS12, OPT_FMT_PVK, OPT_FMT_SMIME, OPT_FMT_TEXT, and opt_format_error().
opt_format_error()
int opt_format_error (const char * s, unsigned long flags)
Definition at line 182 of file opt.c.
References bio_err, BIO_printf(), and OPT_FMT_PEMDER.
Referenced by opt_format().
opt_getprog()
char* opt_getprog (void)
Definition at line 110 of file opt.c.
Referenced by app_malloc(), and parse_name().
opt_help()
void opt_help (const OPTIONS * list)
Definition at line 821 of file opt.c.
References OPTIONS::name, OPT_HELP_STR, OPT_MORE_STR, and OPTIONS::valtype.
opt_init()
char* opt_init (int ac, char ** av, const OPTIONS * o)
Definition at line 116 of file opt.c.
opt_int()
int opt_int (const char * arg, int * result)
Definition at line 315 of file opt.c.
References bio_err, BIO_printf(), and opt_long().
opt_long()
int opt_long (const char * arg, long * result)
Definition at line 331 of file opt.c.
References bio_err, BIO_printf(), and errno.
Referenced by opt_int().
opt_md()
int opt_md (const char * name, const EVP_MD ** mdp)
Definition at line 289 of file opt.c.
References bio_err, BIO_printf(), and EVP_get_digestbyname().
opt_next()
int opt_next (void)
Definition at line 595 of file opt.c.
opt_num_rest()
int opt_num_rest (void)
Definition at line 774 of file opt.c.
References opt_rest(), and pp.
opt_pair()
int opt_pair (const char * arg, const OPT_PAIR * pairs, int * result)
Definition at line 299 of file opt.c.
References bio_err, BIO_printf(), and pp.
opt_progname()
char* opt_progname (const char * argv0)
Definition at line 94 of file opt.c.
opt_reset()
char* opt_reset (void)
opt_rest()
char** opt_rest (void)
Definition at line 768 of file opt.c.
Referenced by opt_num_rest().
opt_ulong()
int opt_ulong (const char * arg, unsigned long * result)
Definition at line 406 of file opt.c.
References bio_err, BIO_printf(), and errno.
opt_unknown()
char* opt_unknown (void)
Definition at line 762 of file opt.c.
opt_verify()
int opt_verify (int i, X509_VERIFY_PARAM * vpm)
Definition at line 435 of file opt.c.
References bio_err, BIO_printf(), NULL, OBJ_txt2obj(), opt_arg(), and t.
parse_name()
X509_NAME* parse_name (const char * str, long chtype, int multirdn)
Definition at line 1718 of file apps.c.
References bio_err, BIO_printf(), bp, nid, NID_undef, NULL, OBJ_txt2nid(), OPENSSL_free, OPENSSL_strdup, opt_getprog(), and X509_NAME_add_entry_by_NID().
parse_yesno()
int parse_yesno (const char * str, int def)
Definition at line 1693 of file apps.c.
password_callback()
int password_callback (char * buf, int bufsiz, int verify, PW_CB_DATA * cb_data)
Definition at line 255 of file apps.c.
pkey_ctrl_string()
int pkey_ctrl_string (EVP_PKEY_CTX * ctx, const char * value)
Definition at line 1837 of file apps.c.
References EVP_PKEY_CTX_ctrl_str(), NULL, OPENSSL_free, and OPENSSL_strdup.
policies_print()
void policies_print (X509_STORE_CTX * ctx)
Definition at line 1870 of file apps.c.
References bio_err, BIO_printf(), X509_STORE_CTX_get0_policy_tree(), and X509_STORE_CTX_get_explicit_policy().
Referenced by verify_callback().
print_array()
void print_array (BIO * , const char * , int , const unsigned char *)
Definition at line 1182 of file apps.c.
print_bignum_var()
void print_bignum_var (BIO * , const BIGNUM * , const char * , int , unsigned char *)
Definition at line 1161 of file apps.c.
print_cert_checks()
void print_cert_checks (BIO * bio, X509 * x, const char * checkhost, const char * checkemail, const char * checkip)
Definition at line 1920 of file apps.c.
References BIO_printf(), NULL, X509_check_email(), X509_check_host(), and X509_check_ip_asc().
process_responder()
OCSP_RESPONSE* process_responder (OCSP_REQUEST * req, const char * host, const char * path, const char * port, int use_ssl, STACK_OF(CONF_VALUE) * headers, int req_timeout)
Definition at line 1251 of file ocsp.c.
References bio_err, BIO_new_connect(), BIO_new_ssl(), BIO_printf(), BIO_push(), BIO_set_conn_port, ctx, NULL, SSL_CTX_new(), SSL_CTX_set_mode, SSL_MODE_AUTO_RETRY, and TLS_client_method().
rand_serial()
int rand_serial (BIGNUM * b, ASN1_INTEGER * ai)
Definition at line 1477 of file apps.c.
raw_read_stdin()
int raw_read_stdin (void * , int)
Definition at line 2368 of file apps.c.
References fileno_stdin(), NULL, and raw_write_stdout().
Referenced by fileno_stdout().
raw_write_stdout()
int raw_write_stdout (const void * , int)
Definition at line 2384 of file apps.c.
References fileno_stdout().
Referenced by raw_read_stdin().
release_engine()
void release_engine (ENGINE * e)
Definition at line 1289 of file apps.c.
References ENGINE_free(), and NULL.
rotate_index()
int rotate_index (const char * dbfile, const char * new_suffix, const char * old_suffix)
Definition at line 1619 of file apps.c.
rotate_serial()
int rotate_serial (const char * serialfile, const char * new_suffix, const char * old_suffix)
Definition at line 1434 of file apps.c.
save_index()
int save_index (const char * dbfile, const char * suffix, CA_DB * db)
Definition at line 1573 of file apps.c.
save_serial()
int save_serial (const char * serialfile, const char * suffix, const BIGNUM * serial, ASN1_INTEGER ** retai)
Definition at line 1384 of file apps.c.
set_cert_ex()
int set_cert_ex (unsigned long * flags, const char * arg)
Definition at line 969 of file apps.c.
set_cert_times()
int set_cert_times (X509 * x, const char * startdate, const char * enddate, int days)
Definition at line 2648 of file apps.c.
References ASN1_TIME_set_string(), NULL, X509_getm_notAfter(), X509_getm_notBefore(), X509_gmtime_adj(), and X509_time_adj_ex().
set_ext_copy()
int set_ext_copy (int * copy_type, const char * arg)
Definition at line 1035 of file apps.c.
set_name_ex()
int set_name_ex (unsigned long * flags, const char * arg)
Definition at line 995 of file apps.c.
setup_engine()
ENGINE* setup_engine (const char * engine, int debug)
Definition at line 1255 of file apps.c.
setup_ui_method()
int setup_ui_method (void)
Definition at line 231 of file apps.c.
setup_verify()
X509_STORE* setup_verify (const char * CAfile, const char * CApath, int noCAfile, int noCApath)
Definition at line 1198 of file apps.c.
References X509_STORE_new().
store_setup_crl_download()
void store_setup_crl_download (X509_STORE * st)
Definition at line 2020 of file apps.c.
References NULL, and X509_STORE_set_lookup_crls_cb.
unbuffer()
void unbuffer (FILE * fp)
Definition at line 2430 of file apps.c.
References NULL.
unpack_revinfo()
int unpack_revinfo (ASN1_TIME ** prevtm, int * preason, ASN1_OBJECT ** phold, ASN1_GENERALIZEDTIME ** pinvtm, const char * str)
Definition at line 2452 of file ca.c.
References NULL.
wait_for_async()
void wait_for_async (SSL * s)
Definition at line 2583 of file apps.c.
References app_malloc(), NULL, openssl_fdset, OPENSSL_free, OSSL_ASYNC_FD, and SSL_get_all_async_fds().
win32_utf8argv()
void win32_utf8argv (int * argc, char ** argv[])
Definition at line 305 of file win32_init.c.
Variable Documentation
bio_err
BIO* bio_err
Definition at line 38 of file uitest.c.
Referenced by app_malloc(), index_index(), load_excert(), load_key(), load_pubkey(), main(), opt_cipher(), opt_format_error(), opt_int(), opt_long(), opt_md(), opt_pair(), opt_ulong(), opt_verify(), parse_name(), policies_print(), process_responder(), rehash_main(), set_cert_stuff(), and verify_callback().
bio_in
BIO* bio_in
bio_out
BIO* bio_out
Referenced by FuzzerCleanup().
default_config_file
char* default_config_file
Definition at line 37 of file uitest.c.
OPT_HELP_STR
const char OPT_HELP_STR[]
Definition at line 25 of file opt.c.
Referenced by opt_help().
OPT_MORE_STR
const char OPT_MORE_STR[]
Definition at line 26 of file opt.c.
Referenced by opt_help().
psk_key
char* psk_key
Definition at line 148 of file s_server.c.
verify_args
VERIFY_CB_ARGS verify_args
Definition at line 29 of file s_cb.c.