apps/apps.c File Reference
apps.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <ctype.h>
#include <errno.h>
#include <openssl/err.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/pem.h>
#include <openssl/pkcs12.h>
#include <openssl/ui.h>
#include <openssl/safestack.h>
#include <openssl/engine.h>
#include <openssl/rsa.h>
#include <openssl/bn.h>
#include <openssl/ssl.h>
#include "s_apps.h"
#include "apps.h"
#include <sys/time.h>
#include <sys/resource.h>
Data Structures
struct NAME_EX_TBL
Macros
#define X509V3_EXT_UNKNOWN_MASK (0xfL << 16)
#define X509V3_EXT_DEFAULT 0
#define X509V3_EXT_ERROR_UNKNOWN (1L << 16)
#define X509V3_EXT_PARSE_UNKNOWN (2L << 16)
#define X509V3_EXT_DUMP_UNKNOWN (3L << 16)
#define X509_FLAG_CA
#define BSIZE 256
#define S_ISDIR(a) (((a) & S_IFMT) == S_IFDIR)
Functions
int app_init (long mesgwin)
int chopup_args (ARGS *arg, char *buf)
int ctx_set_verify_locations (SSL_CTX *ctx, const char *CAfile, const char *CApath, int noCAfile, int noCApath)
int ctx_set_ctlog_list_file (SSL_CTX *ctx, const char *path)
int dump_cert_text (BIO *out, X509 *x)
int setup_ui_method (void)
void destroy_ui_method (void)
const UI_METHOD * get_ui_method (void)
int password_callback (char *buf, int bufsiz, int verify, PW_CB_DATA *cb_tmp)
int app_passwd (const char *arg1, const char *arg2, char **pass1, char **pass2)
CONF * app_load_config (const char *filename)
CONF * app_load_config_quiet (const char *filename)
int app_load_modules (const CONF *config)
int add_oid_section (CONF *conf)
X509 * load_cert (const char *file, int format, const char *cert_descrip)
X509_CRL * load_crl (const char *infile, int format)
EVP_PKEY * load_key (const char *file, int format, int maybe_stdin, const char *pass, ENGINE *e, const char *key_descrip)
EVP_PKEY * load_pubkey (const char *file, int format, int maybe_stdin, const char *pass, ENGINE *e, const char *key_descrip)
void * app_malloc (int sz, const char *what)
int load_certs (const char *file, STACK_OF(X509) **certs, int format, const char *pass, const char *desc)
int load_crls (const char *file, STACK_OF(X509_CRL) **crls, int format, const char *pass, const char *desc)
int set_cert_ex (unsigned long *flags, const char *arg)
int set_name_ex (unsigned long *flags, const char *arg)
int set_ext_copy (int *copy_type, const char *arg)
int copy_extensions (X509 *x, X509_REQ *req, int copy_type)
void print_name (BIO *out, const char *title, X509_NAME *nm, unsigned long lflags)
void print_bignum_var (BIO *out, const BIGNUM *in, const char *var, int len, unsigned char *buffer)
void print_array (BIO *out, const char *title, int len, const unsigned char *d)
X509_STORE * setup_verify (const char *CAfile, const char *CApath, int noCAfile, int noCApath)
ENGINE * setup_engine (const char *engine, int debug)
void release_engine (ENGINE *e)
int index_name_cmp (const OPENSSL_CSTRING *a, const OPENSSL_CSTRING *b)
int save_serial (const char *serialfile, const char *suffix, const BIGNUM *serial, ASN1_INTEGER **retai)
int rotate_serial (const char *serialfile, const char *new_suffix, const char *old_suffix)
int rand_serial (BIGNUM *b, ASN1_INTEGER *ai)
CA_DB * load_index (const char *dbfile, DB_ATTR *db_attr)
int index_index (CA_DB *db)
int save_index (const char *dbfile, const char *suffix, CA_DB *db)
int rotate_index (const char *dbfile, const char *new_suffix, const char *old_suffix)
void free_index (CA_DB *db)
int parse_yesno (const char *str, int def)
X509_NAME * parse_name (const char *cp, long chtype, int canmulti)
int bio_to_mem (unsigned char **out, int maxlen, BIO *in)
int pkey_ctrl_string (EVP_PKEY_CTX *ctx, const char *value)
void policies_print (X509_STORE_CTX *ctx)
unsigned char * next_protos_parse (size_t *outlen, const char *in)
void print_cert_checks (BIO *bio, X509 *x, const char *checkhost, const char *checkemail, const char *checkip)
void store_setup_crl_download (X509_STORE *st)
double app_tminterval (int stop, int usertime)
int app_access (const char *name, int flag)
int app_isdir (const char *name)
int fileno_stdin (void)
int fileno_stdout (void)
int raw_read_stdin (void *buf, int siz)
int raw_write_stdout (const void *buf, int siz)
BIO * dup_bio_in (int format)
BIO * dup_bio_out (int format)
BIO * dup_bio_err (int format)
void unbuffer (FILE *fp)
BIO * bio_open_owner (const char *filename, int format, int private)
BIO * bio_open_default (const char *filename, char mode, int format)
BIO * bio_open_default_quiet (const char *filename, char mode, int format)
void wait_for_async (SSL *s)
void corrupt_signature (const ASN1_STRING *signature)
int set_cert_times (X509 *x, const char *startdate, const char *enddate, int days)
void make_uppercase (char *string)
Macro Definition Documentation
BSIZE
#define BSIZE 256
S_ISDIR
#define S_ISDIR (a) (((a) & S_IFMT) == S_IFDIR)
Definition at line 2301 of file apps.c.
Referenced by app_isdir().
X509_FLAG_CA
#define X509_FLAG_CA
Value:
(X509_FLAG_NO_ISSUER | X509_FLAG_NO_PUBKEY | \
                         X509_FLAG_NO_HEADER | X509_FLAG_NO_VERSION)
Definition at line 966 of file apps.c.
X509V3_EXT_DEFAULT
#define X509V3_EXT_DEFAULT 0
Definition at line 958 of file apps.c.
X509V3_EXT_DUMP_UNKNOWN
#define X509V3_EXT_DUMP_UNKNOWN (3L << 16)
Definition at line 964 of file apps.c.
X509V3_EXT_ERROR_UNKNOWN
#define X509V3_EXT_ERROR_UNKNOWN (1L << 16)
Definition at line 960 of file apps.c.
X509V3_EXT_PARSE_UNKNOWN
#define X509V3_EXT_PARSE_UNKNOWN (2L << 16)
Definition at line 962 of file apps.c.
X509V3_EXT_UNKNOWN_MASK
#define X509V3_EXT_UNKNOWN_MASK (0xfL << 16)
Definition at line 956 of file apps.c.
Function Documentation
add_oid_section()
int add_oid_section (CONF * conf)
Definition at line 493 of file apps.c.
app_access()
int app_access (const char * name, int flag)
Definition at line 2258 of file apps.c.
app_init()
int app_init (long mesgwin)
Definition at line 119 of file apps.c.
app_isdir()
int app_isdir (const char * name)
Definition at line 2305 of file apps.c.
References fileno_stdin(), S_ISDIR, TERM_SOCK_CREATE, TERM_SOCK_DELETE, and TerminalSocket().
app_load_config()
CONF* app_load_config (const char * filename)
Definition at line 447 of file apps.c.
References in.
app_load_config_quiet()
CONF* app_load_config_quiet (const char * filename)
Definition at line 460 of file apps.c.
References in.
app_load_modules()
int app_load_modules (const CONF * config)
Definition at line 474 of file apps.c.
app_malloc()
void* app_malloc (int sz, const char * what)
Definition at line 925 of file apps.c.
References bio_err, BIO_printf(), ERR_print_errors(), NULL, OPENSSL_malloc, and opt_getprog().
Referenced by ssl_print_groups(), and wait_for_async().
app_passwd()
int app_passwd (const char * arg1, const char * arg2, char ** pass1, char ** pass2)
Definition at line 332 of file apps.c.
app_tminterval()
double app_tminterval (int stop, int usertime)
Definition at line 2236 of file apps.c.
bio_open_default()
BIO* bio_open_default (const char * filename, char mode, int format)
Definition at line 2573 of file apps.c.
Referenced by bio_open_owner().
bio_open_default_quiet()
BIO* bio_open_default_quiet (const char * filename, char mode, int format)
Definition at line 2578 of file apps.c.
bio_open_owner()
BIO* bio_open_owner (const char * filename, int format, int private)
Definition at line 2481 of file apps.c.
References bio_open_default(), fp, and NULL.
bio_to_mem()
int bio_to_mem (unsigned char ** out, int maxlen, BIO * in)
Definition at line 1801 of file apps.c.
chopup_args()
int chopup_args (ARGS * arg, char * buf)
Definition at line 70 of file apps.c.
copy_extensions()
int copy_extensions (X509 * x, X509_REQ * req, int copy_type)
Definition at line 1048 of file apps.c.
corrupt_signature()
void corrupt_signature (const ASN1_STRING * signature)
Definition at line 2642 of file apps.c.
ctx_set_ctlog_list_file()
int ctx_set_ctlog_list_file (SSL_CTX * ctx, const char * path)
Definition at line 141 of file apps.c.
References NULL, SSL_CTX_set_ctlog_list_file(), and SSL_CTX_set_default_ctlog_list_file().
ctx_set_verify_locations()
int ctx_set_verify_locations (SSL_CTX * ctx, const char * CAfile, const char * CApath, int noCAfile, int noCApath)
Definition at line 125 of file apps.c.
References NULL, SSL_CTX_load_verify_locations(), SSL_CTX_set_default_verify_dir(), and SSL_CTX_set_default_verify_file().
destroy_ui_method()
void destroy_ui_method (void)
Definition at line 241 of file apps.c.
dump_cert_text()
int dump_cert_text (BIO * out, X509 * x)
Definition at line 152 of file apps.c.
dup_bio_err()
BIO* dup_bio_err (int format)
Definition at line 2419 of file apps.c.
References BIO_new_fp(), and BIO_NOCLOSE.
dup_bio_in()
BIO* dup_bio_in (int format)
Definition at line 2402 of file apps.c.
References BIO_new_fp(), and BIO_NOCLOSE.
dup_bio_out()
BIO* dup_bio_out (int format)
Definition at line 2408 of file apps.c.
References BIO_new_fp(), and BIO_NOCLOSE.
fileno_stdin()
int fileno_stdin (void)
Definition at line 2340 of file apps.c.
Referenced by app_isdir(), and raw_read_stdin().
fileno_stdout()
int fileno_stdout (void)
Definition at line 2346 of file apps.c.
References raw_read_stdin().
Referenced by raw_write_stdout().
free_index()
void free_index (CA_DB * db)
Definition at line 1685 of file apps.c.
References CA_DB::db, OPENSSL_free, and TXT_DB_free().
get_ui_method()
const UI_METHOD* get_ui_method (void)
Definition at line 249 of file apps.c.
index_index()
int index_index (CA_DB * db)
Definition at line 1551 of file apps.c.
References TXT_DB::arg1, TXT_DB::arg2, CA_DB::attributes, bio_err, BIO_printf(), CA_DB::db, DB_name, DB_serial, TXT_DB::error, LHASH_COMP_FN, LHASH_HASH_FN, NULL, TXT_DB_create_index(), and DB_ATTR::unique_subject.
index_name_cmp()
int index_name_cmp (const OPENSSL_CSTRING * a, const OPENSSL_CSTRING * b)
Definition at line 1328 of file apps.c.
References DB_name, IMPLEMENT_LHASH_COMP_FN, IMPLEMENT_LHASH_HASH_FN, in, load_serial(), and NULL.
load_cert()
X509* load_cert (const char * file, int format, const char * cert_descrip)
Definition at line 608 of file apps.c.
References NULL.
Referenced by load_excert().
load_certs()
int load_certs (const char * file, STACK_OF(X509) ** certs, int format, const char * pass, const char * desc)
Definition at line 941 of file apps.c.
Referenced by load_excert().
load_crl()
X509_CRL* load_crl (const char * infile, int format)
Definition at line 649 of file apps.c.
References FORMAT_HTTP, in, and NULL.
load_crls()
int load_crls (const char * file, STACK_OF(X509_CRL) ** crls, int format, const char * pass, const char * desc)
Definition at line 950 of file apps.c.
load_index()
CA_DB* load_index (const char * dbfile, DB_ATTR * db_attr)
Definition at line 1505 of file apps.c.
References in, and NULL.
load_key()
EVP_PKEY* load_key (const char * file, int format, int maybe_stdin, const char * pass, ENGINE * e, const char * key_descrip)
Definition at line 683 of file apps.c.
References bio_err, BIO_printf(), ENGINE_init(), ENGINE_load_private_key(), file, FORMAT_ENGINE, key, NULL, pass, PW_CB_DATA::password, and PW_CB_DATA::prompt_info.
Referenced by load_excert().
load_pubkey()
EVP_PKEY* load_pubkey (const char * file, int format, int maybe_stdin, const char * pass, ENGINE * e, const char * key_descrip)
Definition at line 756 of file apps.c.
References bio_err, BIO_printf(), ENGINE_load_public_key(), file, FORMAT_ENGINE, key, NULL, pass, PW_CB_DATA::password, and PW_CB_DATA::prompt_info.
make_uppercase()
void make_uppercase (char * string)
Definition at line 2668 of file apps.c.
next_protos_parse()
unsigned char* next_protos_parse (size_t * outlen, const char * in)
Definition at line 1893 of file apps.c.
References len.
parse_name()
X509_NAME* parse_name (const char * cp, long chtype, int canmulti)
Definition at line 1718 of file apps.c.
References bio_err, BIO_printf(), bp, nid, NID_undef, NULL, OBJ_txt2nid(), OPENSSL_free, OPENSSL_strdup, opt_getprog(), and X509_NAME_add_entry_by_NID().
parse_yesno()
int parse_yesno (const char * str, int def)
Definition at line 1693 of file apps.c.
password_callback()
int password_callback (char * buf, int bufsiz, int verify, PW_CB_DATA * cb_tmp)
Definition at line 255 of file apps.c.
pkey_ctrl_string()
int pkey_ctrl_string (EVP_PKEY_CTX * ctx, const char * value)
Definition at line 1837 of file apps.c.
References EVP_PKEY_CTX_ctrl_str(), NULL, OPENSSL_free, and OPENSSL_strdup.
policies_print()
void policies_print (X509_STORE_CTX * ctx)
Definition at line 1870 of file apps.c.
References bio_err, BIO_printf(), X509_STORE_CTX_get0_policy_tree(), and X509_STORE_CTX_get_explicit_policy().
Referenced by verify_callback().
print_array()
void print_array (BIO * out, const char * title, int len, const unsigned char * d)
Definition at line 1182 of file apps.c.
print_bignum_var()
void print_bignum_var (BIO * out, const BIGNUM * in, const char * var, int len, unsigned char * buffer)
Definition at line 1161 of file apps.c.
print_cert_checks()
void print_cert_checks (BIO * bio, X509 * x, const char * checkhost, const char * checkemail, const char * checkip)
Definition at line 1920 of file apps.c.
References BIO_printf(), NULL, X509_check_email(), X509_check_host(), and X509_check_ip_asc().
print_name()
void print_name (BIO * out, const char * title, X509_NAME * nm, unsigned long lflags)
Definition at line 1135 of file apps.c.
rand_serial()
int rand_serial (BIGNUM * b, ASN1_INTEGER * ai)
Definition at line 1477 of file apps.c.
raw_read_stdin()
int raw_read_stdin (void * buf, int siz)
Definition at line 2368 of file apps.c.
References fileno_stdin(), NULL, and raw_write_stdout().
Referenced by fileno_stdout().
raw_write_stdout()
int raw_write_stdout (const void * buf, int siz)
Definition at line 2384 of file apps.c.
References fileno_stdout().
Referenced by raw_read_stdin().
release_engine()
void release_engine (ENGINE * e)
Definition at line 1289 of file apps.c.
References ENGINE_free(), and NULL.
rotate_index()
int rotate_index (const char * dbfile, const char * new_suffix, const char * old_suffix)
Definition at line 1619 of file apps.c.
rotate_serial()
int rotate_serial (const char * serialfile, const char * new_suffix, const char * old_suffix)
Definition at line 1434 of file apps.c.
save_index()
int save_index (const char * dbfile, const char * suffix, CA_DB * db)
Definition at line 1573 of file apps.c.
save_serial()
int save_serial (const char * serialfile, const char * suffix, const BIGNUM * serial, ASN1_INTEGER ** retai)
Definition at line 1384 of file apps.c.
set_cert_ex()
int set_cert_ex (unsigned long * flags, const char * arg)
Definition at line 969 of file apps.c.
set_cert_times()
int set_cert_times (X509 * x, const char * startdate, const char * enddate, int days)
Definition at line 2648 of file apps.c.
References ASN1_TIME_set_string(), NULL, X509_getm_notAfter(), X509_getm_notBefore(), X509_gmtime_adj(), and X509_time_adj_ex().
set_ext_copy()
int set_ext_copy (int * copy_type, const char * arg)
Definition at line 1035 of file apps.c.
set_name_ex()
int set_name_ex (unsigned long * flags, const char * arg)
Definition at line 995 of file apps.c.
setup_engine()
ENGINE* setup_engine (const char * engine, int debug)
Definition at line 1255 of file apps.c.
setup_ui_method()
int setup_ui_method (void)
Definition at line 231 of file apps.c.
setup_verify()
X509_STORE* setup_verify (const char * CAfile, const char * CApath, int noCAfile, int noCApath)
Definition at line 1198 of file apps.c.
References X509_STORE_new().
store_setup_crl_download()
void store_setup_crl_download (X509_STORE * st)
Definition at line 2020 of file apps.c.
References NULL, and X509_STORE_set_lookup_crls_cb.
unbuffer()
void unbuffer (FILE * fp)
Definition at line 2430 of file apps.c.
References NULL.
wait_for_async()
void wait_for_async (SSL * s)
Definition at line 2583 of file apps.c.
References app_malloc(), NULL, openssl_fdset, OPENSSL_free, OSSL_ASYNC_FD, and SSL_get_all_async_fds().