crypto/asn1/asn1_gen.c File Reference
asn1_gen.c File Reference
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include <openssl/x509v3.h>
Data Structures
struct tag_name_st
struct tag_exp_type
struct tag_exp_arg
Macros
#define ASN1_GEN_FLAG 0x10000
#define ASN1_GEN_FLAG_IMP (ASN1_GEN_FLAG|1)
#define ASN1_GEN_FLAG_EXP (ASN1_GEN_FLAG|2)
#define ASN1_GEN_FLAG_TAG (ASN1_GEN_FLAG|3)
#define ASN1_GEN_FLAG_BITWRAP (ASN1_GEN_FLAG|4)
#define ASN1_GEN_FLAG_OCTWRAP (ASN1_GEN_FLAG|5)
#define ASN1_GEN_FLAG_SEQWRAP (ASN1_GEN_FLAG|6)
#define ASN1_GEN_FLAG_SETWRAP (ASN1_GEN_FLAG|7)
#define ASN1_GEN_FLAG_FORMAT (ASN1_GEN_FLAG|8)
#define ASN1_GEN_STR(str, val) {str, sizeof(str) - 1, val}
#define ASN1_FLAG_EXP_MAX 20
#define ASN1_GEN_SEQ_MAX_DEPTH 50
#define ASN1_GEN_FORMAT_ASCII 1
#define ASN1_GEN_FORMAT_UTF8 2
#define ASN1_GEN_FORMAT_HEX 3
#define ASN1_GEN_FORMAT_BITLIST 4
Functions
ASN1_TYPE * ASN1_generate_nconf (const char *str, CONF *nconf)
ASN1_TYPE * ASN1_generate_v3 (const char *str, X509V3_CTX *cnf)
int ASN1_str2mask (const char *str, unsigned long *pmask)
Macro Definition Documentation
ASN1_FLAG_EXP_MAX
#define ASN1_FLAG_EXP_MAX 20
Definition at line 26 of file asn1_gen.c.
ASN1_GEN_FLAG
#define ASN1_GEN_FLAG 0x10000
Definition at line 14 of file asn1_gen.c.
ASN1_GEN_FLAG_BITWRAP
#define ASN1_GEN_FLAG_BITWRAP (ASN1_GEN_FLAG|4)
Definition at line 18 of file asn1_gen.c.
ASN1_GEN_FLAG_EXP
#define ASN1_GEN_FLAG_EXP (ASN1_GEN_FLAG|2)
Definition at line 16 of file asn1_gen.c.
ASN1_GEN_FLAG_FORMAT
#define ASN1_GEN_FLAG_FORMAT (ASN1_GEN_FLAG|8)
Definition at line 22 of file asn1_gen.c.
ASN1_GEN_FLAG_IMP
#define ASN1_GEN_FLAG_IMP (ASN1_GEN_FLAG|1)
Definition at line 15 of file asn1_gen.c.
ASN1_GEN_FLAG_OCTWRAP
#define ASN1_GEN_FLAG_OCTWRAP (ASN1_GEN_FLAG|5)
Definition at line 19 of file asn1_gen.c.
ASN1_GEN_FLAG_SEQWRAP
#define ASN1_GEN_FLAG_SEQWRAP (ASN1_GEN_FLAG|6)
Definition at line 20 of file asn1_gen.c.
ASN1_GEN_FLAG_SETWRAP
#define ASN1_GEN_FLAG_SETWRAP (ASN1_GEN_FLAG|7)
Definition at line 21 of file asn1_gen.c.
ASN1_GEN_FLAG_TAG
#define ASN1_GEN_FLAG_TAG (ASN1_GEN_FLAG|3)
Definition at line 17 of file asn1_gen.c.
ASN1_GEN_FORMAT_ASCII
#define ASN1_GEN_FORMAT_ASCII 1
Definition at line 33 of file asn1_gen.c.
ASN1_GEN_FORMAT_BITLIST
#define ASN1_GEN_FORMAT_BITLIST 4
Definition at line 39 of file asn1_gen.c.
ASN1_GEN_FORMAT_HEX
#define ASN1_GEN_FORMAT_HEX 3
Definition at line 37 of file asn1_gen.c.
ASN1_GEN_FORMAT_UTF8
#define ASN1_GEN_FORMAT_UTF8 2
Definition at line 35 of file asn1_gen.c.
ASN1_GEN_SEQ_MAX_DEPTH
#define ASN1_GEN_SEQ_MAX_DEPTH 50
Definition at line 28 of file asn1_gen.c.
ASN1_GEN_STR
#define ASN1_GEN_STR (str, val) {str, sizeof(str) - 1, val}
Definition at line 24 of file asn1_gen.c.
Function Documentation
ASN1_generate_nconf()
ASN1_TYPE* ASN1_generate_nconf (const char * str, CONF * nconf)
Definition at line 78 of file asn1_gen.c.
References ASN1_generate_v3(), NULL, and X509V3_set_nconf().
ASN1_generate_v3()
ASN1_TYPE* ASN1_generate_v3 (const char * str, X509V3_CTX * cnf)
Definition at line 89 of file asn1_gen.c.
Referenced by ASN1_generate_nconf().
ASN1_str2mask()
int ASN1_str2mask (const char * str, unsigned long * pmask)
Definition at line 785 of file asn1_gen.c.
References CONF_parse_list().