crypto/asn1/asn1_lib.c File Reference
asn1_lib.c File Reference
#include <stdio.h>
#include <limits.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include "asn1_locl.h"
Functions
int ASN1_check_infinite_end (unsigned char **p, long len)
int ASN1_const_check_infinite_end (const unsigned char **p, long len)
int ASN1_get_object (const unsigned char **pp, long *plength, int *ptag, int *pclass, long omax)
void ASN1_put_object (unsigned char **pp, int constructed, int length, int tag, int xclass)
int ASN1_put_eoc (unsigned char **pp)
int ASN1_object_size (int constructed, int length, int tag)
int ASN1_STRING_copy (ASN1_STRING *dst, const ASN1_STRING *str)
ASN1_STRING * ASN1_STRING_dup (const ASN1_STRING *str)
int ASN1_STRING_set (ASN1_STRING *str, const void *_data, int len)
void ASN1_STRING_set0 (ASN1_STRING *str, void *data, int len)
ASN1_STRING * ASN1_STRING_new (void)
ASN1_STRING * ASN1_STRING_type_new (int type)
void asn1_string_embed_free (ASN1_STRING *a, int embed)
void ASN1_STRING_free (ASN1_STRING *a)
void ASN1_STRING_clear_free (ASN1_STRING *a)
int ASN1_STRING_cmp (const ASN1_STRING *a, const ASN1_STRING *b)
int ASN1_STRING_length (const ASN1_STRING *x)
void ASN1_STRING_length_set (ASN1_STRING *x, int len)
int ASN1_STRING_type (const ASN1_STRING *x)
const unsigned char * ASN1_STRING_get0_data (const ASN1_STRING *x)
unsigned char * ASN1_STRING_data (ASN1_STRING *x)
Function Documentation
ASN1_check_infinite_end()
int ASN1_check_infinite_end (unsigned char ** p, long len)
Definition at line 34 of file asn1_lib.c.
ASN1_const_check_infinite_end()
int ASN1_const_check_infinite_end (const unsigned char ** p, long len)
Definition at line 39 of file asn1_lib.c.
ASN1_get_object()
int ASN1_get_object (const unsigned char ** pp, long * plength, int * ptag, int * pclass, long omax)
Definition at line 44 of file asn1_lib.c.
ASN1_object_size()
int ASN1_object_size (int constructed, int length, int tag)
Definition at line 208 of file asn1_lib.c.
Referenced by i2d_ASN1_OBJECT().
ASN1_put_eoc()
int ASN1_put_eoc (unsigned char ** pp)
Definition at line 178 of file asn1_lib.c.
References pp.
ASN1_put_object()
void ASN1_put_object (unsigned char ** pp, int constructed, int length, int tag, int xclass)
Definition at line 148 of file asn1_lib.c.
References pp, V_ASN1_CONSTRUCTED, V_ASN1_PRIMITIVE_TAG, and V_ASN1_PRIVATE.
Referenced by i2d_ASN1_OBJECT().
ASN1_STRING_clear_free()
void ASN1_STRING_clear_free (ASN1_STRING * a)
Definition at line 335 of file asn1_lib.c.
References ASN1_STRING_FLAG_NDEF, ASN1_STRING_free(), NULL, and OPENSSL_cleanse().
ASN1_STRING_cmp()
int ASN1_STRING_cmp (const ASN1_STRING * a, const ASN1_STRING * b)
Definition at line 344 of file asn1_lib.c.
Referenced by ASN1_OCTET_STRING_cmp(), ASN1_TYPE_cmp(), and cms_Receipt_verify().
ASN1_STRING_copy()
int ASN1_STRING_copy (ASN1_STRING * dst, const ASN1_STRING * str)
Definition at line 236 of file asn1_lib.c.
References ASN1_STRING_FLAG_EMBED, ASN1_STRING_set(), and NULL.
Referenced by ASN1_TIME_set_string(), X509_REVOKED_set_serialNumber(), and X509_set_serialNumber().
ASN1_STRING_data()
unsigned char* ASN1_STRING_data (ASN1_STRING * x)
Definition at line 380 of file asn1_lib.c.
ASN1_STRING_dup()
ASN1_STRING* ASN1_STRING_dup (const ASN1_STRING * str)
Definition at line 249 of file asn1_lib.c.
Referenced by ASN1_INTEGER_dup(), ASN1_OCTET_STRING_dup(), ASN1_TYPE_set1(), TS_TST_INFO_set_time(), X509_REVOKED_set_revocationDate(), and x509_set1_time().
asn1_string_embed_free()
void asn1_string_embed_free (ASN1_STRING * a, int embed)
Definition at line 318 of file asn1_lib.c.
References ASN1_STRING_FLAG_NDEF, NULL, and OPENSSL_free.
Referenced by asn1_primitive_free(), and ASN1_STRING_free().
ASN1_STRING_free()
void ASN1_STRING_free (ASN1_STRING * a)
Definition at line 328 of file asn1_lib.c.
References asn1_string_embed_free(), ASN1_STRING_FLAG_EMBED, and NULL.
Referenced by ASN1_item_pack(), ASN1_STRING_clear_free(), and X509_ATTRIBUTE_set1_data().
ASN1_STRING_get0_data()
const unsigned char* ASN1_STRING_get0_data (const ASN1_STRING * x)
Definition at line 374 of file asn1_lib.c.
Referenced by X509_ocspid_print(), and X509V3_EXT_d2i().
ASN1_STRING_length()
int ASN1_STRING_length (const ASN1_STRING * x)
Definition at line 359 of file asn1_lib.c.
Referenced by X509_ocspid_print(), and X509V3_EXT_d2i().
ASN1_STRING_length_set()
void ASN1_STRING_length_set (ASN1_STRING * x, int len)
Definition at line 364 of file asn1_lib.c.
References len.
ASN1_STRING_new()
ASN1_STRING* ASN1_STRING_new (void)
Definition at line 300 of file asn1_lib.c.
References ASN1_STRING_type_new(), and V_ASN1_OCTET_STRING.
Referenced by ASN1_item_pack(), and PKCS7_add_attrib_smimecap().
ASN1_STRING_set()
int ASN1_STRING_set (ASN1_STRING * str, const void * _data, int len)
Definition at line 264 of file asn1_lib.c.
Referenced by ASN1_BIT_STRING_set(), ASN1_GENERALIZEDTIME_set_string(), ASN1_OCTET_STRING_set(), ASN1_STRING_copy(), ASN1_UTCTIME_set_string(), CMS_ReceiptRequest_create0(), OCSP_crlID_new(), OCSP_url_svcloc_new(), s2i_ASN1_IA5STRING(), X509_ATTRIBUTE_set1_data(), and X509_NAME_ENTRY_set_data().
ASN1_STRING_set0()
void ASN1_STRING_set0 (ASN1_STRING * str, void * data, int len)
Definition at line 293 of file asn1_lib.c.
References data, len, and OPENSSL_free.
Referenced by CMS_dataFinal(), and CMS_ReceiptRequest_create0().
ASN1_STRING_type()
int ASN1_STRING_type (const ASN1_STRING * x)
Definition at line 369 of file asn1_lib.c.
ASN1_STRING_type_new()
ASN1_STRING* ASN1_STRING_type_new (int type)
Definition at line 305 of file asn1_lib.c.
Referenced by ASN1_STRING_new(), and X509_ATTRIBUTE_set1_data().