include/openssl/asn1.h File Reference
asn1.h File Reference
#include <time.h>
#include <openssl/e_os2.h>
#include <openssl/opensslconf.h>
#include <openssl/bio.h>
#include <openssl/stack.h>
#include <openssl/safestack.h>
#include <openssl/symhacks.h>
#include <openssl/ossl_typ.h>
#include <openssl/bn.h>
Data Structures
struct ASN1_STRING
struct ASN1_ENCODING
struct ASN1_STRING_TABLE
struct ASN1_TYPE
struct BIT_STRING_BITNAME
Macros
#define V_ASN1_UNIVERSAL 0x00
#define V_ASN1_APPLICATION 0x40
#define V_ASN1_CONTEXT_SPECIFIC 0x80
#define V_ASN1_PRIVATE 0xc0
#define V_ASN1_CONSTRUCTED 0x20
#define V_ASN1_PRIMITIVE_TAG 0x1f
#define V_ASN1_PRIMATIVE_TAG 0x1f
#define V_ASN1_APP_CHOOSE -2/* let the recipient choose */
#define V_ASN1_OTHER -3/* used in ASN1_TYPE */
#define V_ASN1_ANY -4/* used in ASN1 template code */
#define V_ASN1_UNDEF -1
#define V_ASN1_EOC 0
#define V_ASN1_BOOLEAN 1
#define V_ASN1_INTEGER 2
#define V_ASN1_BIT_STRING 3
#define V_ASN1_OCTET_STRING 4
#define V_ASN1_NULL 5
#define V_ASN1_OBJECT 6
#define V_ASN1_OBJECT_DESCRIPTOR 7
#define V_ASN1_EXTERNAL 8
#define V_ASN1_REAL 9
#define V_ASN1_ENUMERATED 10
#define V_ASN1_UTF8STRING 12
#define V_ASN1_SEQUENCE 16
#define V_ASN1_SET 17
#define V_ASN1_NUMERICSTRING 18
#define V_ASN1_PRINTABLESTRING 19
#define V_ASN1_T61STRING 20
#define V_ASN1_TELETEXSTRING 20/* alias */
#define V_ASN1_VIDEOTEXSTRING 21
#define V_ASN1_IA5STRING 22
#define V_ASN1_UTCTIME 23
#define V_ASN1_GENERALIZEDTIME 24
#define V_ASN1_GRAPHICSTRING 25
#define V_ASN1_ISO64STRING 26
#define V_ASN1_VISIBLESTRING 26/* alias */
#define V_ASN1_GENERALSTRING 27
#define V_ASN1_UNIVERSALSTRING 28
#define V_ASN1_BMPSTRING 30
#define V_ASN1_NEG 0x100
#define V_ASN1_NEG_INTEGER (2 | V_ASN1_NEG)
#define V_ASN1_NEG_ENUMERATED (10 | V_ASN1_NEG)
#define B_ASN1_NUMERICSTRING 0x0001
#define B_ASN1_PRINTABLESTRING 0x0002
#define B_ASN1_T61STRING 0x0004
#define B_ASN1_TELETEXSTRING 0x0004
#define B_ASN1_VIDEOTEXSTRING 0x0008
#define B_ASN1_IA5STRING 0x0010
#define B_ASN1_GRAPHICSTRING 0x0020
#define B_ASN1_ISO64STRING 0x0040
#define B_ASN1_VISIBLESTRING 0x0040
#define B_ASN1_GENERALSTRING 0x0080
#define B_ASN1_UNIVERSALSTRING 0x0100
#define B_ASN1_OCTET_STRING 0x0200
#define B_ASN1_BIT_STRING 0x0400
#define B_ASN1_BMPSTRING 0x0800
#define B_ASN1_UNKNOWN 0x1000
#define B_ASN1_UTF8STRING 0x2000
#define B_ASN1_UTCTIME 0x4000
#define B_ASN1_GENERALIZEDTIME 0x8000
#define B_ASN1_SEQUENCE 0x10000
#define MBSTRING_FLAG 0x1000
#define MBSTRING_UTF8 (MBSTRING_FLAG)
#define MBSTRING_ASC (MBSTRING_FLAG|1)
#define MBSTRING_BMP (MBSTRING_FLAG|2)
#define MBSTRING_UNIV (MBSTRING_FLAG|4)
#define SMIME_OLDMIME 0x400
#define SMIME_CRLFEOL 0x800
#define SMIME_STREAM 0x1000
#define ASN1_STRING_FLAG_BITS_LEFT 0x08/* Set if 0x07 has bits left value */
#define ASN1_STRING_FLAG_NDEF 0x010
#define ASN1_STRING_FLAG_CONT 0x020
#define ASN1_STRING_FLAG_MSTRING 0x040
#define ASN1_STRING_FLAG_EMBED 0x080
#define ASN1_LONG_UNDEF 0x7fffffffL
#define STABLE_FLAGS_MALLOC 0x01
#define STABLE_FLAGS_CLEAR STABLE_FLAGS_MALLOC
#define STABLE_NO_MASK 0x02
#define DIRSTRING_TYPE (B_ASN1_PRINTABLESTRING|B_ASN1_T61STRING|B_ASN1_BMPSTRING|B_ASN1_UTF8STRING)
#define PKCS9STRING_TYPE (DIRSTRING_TYPE|B_ASN1_IA5STRING)
#define ub_name 32768
#define ub_common_name 64
#define ub_locality_name 128
#define ub_state_name 128
#define ub_organization_name 64
#define ub_organization_unit_name 64
#define ub_title 64
#define ub_email_address 128
#define DECLARE_ASN1_FUNCTIONS(type) DECLARE_ASN1_FUNCTIONS_name(type, type)
#define DECLARE_ASN1_ALLOC_FUNCTIONS(type) DECLARE_ASN1_ALLOC_FUNCTIONS_name(type, type)
#define DECLARE_ASN1_FUNCTIONS_name(type, name)
#define DECLARE_ASN1_FUNCTIONS_fname(type, itname, name)
#define DECLARE_ASN1_ENCODE_FUNCTIONS(type, itname, name)
#define DECLARE_ASN1_ENCODE_FUNCTIONS_const(type, name)
#define DECLARE_ASN1_NDEF_FUNCTION(name) int i2d_##name##_NDEF(name *a, unsigned char **out);
#define DECLARE_ASN1_FUNCTIONS_const(name)
#define DECLARE_ASN1_ALLOC_FUNCTIONS_name(type, name)
#define DECLARE_ASN1_PRINT_FUNCTION(stname) DECLARE_ASN1_PRINT_FUNCTION_fname(stname, stname)
#define DECLARE_ASN1_PRINT_FUNCTION_fname(stname, fname)
#define D2I_OF(type) type *(*)(type **,const unsigned char **,long)
#define I2D_OF(type) int (*)(type *,unsigned char **)
#define I2D_OF_const(type) int (*)(const type *,unsigned char **)
#define CHECKED_D2I_OF(type, d2i) ((d2i_of_void*) (1 ? d2i : ((D2I_OF(type))0)))
#define CHECKED_I2D_OF(type, i2d) ((i2d_of_void*) (1 ? i2d : ((I2D_OF(type))0)))
#define CHECKED_NEW_OF(type, xnew) ((void *(*)(void)) (1 ? xnew : ((type *(*)(void))0)))
#define CHECKED_PTR_OF(type, p) ((void*) (1 ? p : (type*)0))
#define CHECKED_PPTR_OF(type, p) ((void**) (1 ? p : (type**)0))
#define TYPEDEF_D2I_OF(type) typedef type *d2i_of_##type(type **,const unsigned char **,long)
#define TYPEDEF_I2D_OF(type) typedef int i2d_of_##type(type *,unsigned char **)
#define TYPEDEF_D2I2D_OF(type) TYPEDEF_D2I_OF(type); TYPEDEF_I2D_OF(type)
#define ASN1_ITEM_ptr(iptr) (iptr)
#define ASN1_ITEM_ref(iptr) (&(iptr##_it))
#define ASN1_ITEM_rptr(ref) (&(ref##_it))
#define DECLARE_ASN1_ITEM(name) OPENSSL_EXTERN const ASN1_ITEM name##_it;
#define ASN1_STRFLGS_ESC_2253 1
#define ASN1_STRFLGS_ESC_CTRL 2
#define ASN1_STRFLGS_ESC_MSB 4
#define ASN1_STRFLGS_ESC_QUOTE 8
#define CHARTYPE_PRINTABLESTRING 0x10
#define CHARTYPE_FIRST_ESC_2253 0x20
#define CHARTYPE_LAST_ESC_2253 0x40
#define ASN1_STRFLGS_UTF8_CONVERT 0x10
#define ASN1_STRFLGS_IGNORE_TYPE 0x20
#define ASN1_STRFLGS_SHOW_TYPE 0x40
#define ASN1_STRFLGS_DUMP_ALL 0x80
#define ASN1_STRFLGS_DUMP_UNKNOWN 0x100
#define ASN1_STRFLGS_DUMP_DER 0x200
#define ASN1_STRFLGS_ESC_2254 0x400
#define ASN1_STRFLGS_RFC2253
#define B_ASN1_TIME
#define B_ASN1_PRINTABLE
#define B_ASN1_DIRECTORYSTRING
#define B_ASN1_DISPLAYTEXT
#define ASN1_dup_of(type, i2d, d2i, x)
#define ASN1_dup_of_const(type, i2d, d2i, x)
#define M_ASN1_new_of(type) (type *)ASN1_item_new(ASN1_ITEM_rptr(type))
#define M_ASN1_free_of(x, type) ASN1_item_free(CHECKED_PTR_OF(type, x), ASN1_ITEM_rptr(type))
#define ASN1_d2i_fp_of(type, xnew, d2i, in, x)
#define ASN1_i2d_fp_of(type, i2d, out, x)
#define ASN1_i2d_fp_of_const(type, i2d, out, x)
#define ASN1_d2i_bio_of(type, xnew, d2i, in, x)
#define ASN1_i2d_bio_of(type, i2d, out, x)
#define ASN1_i2d_bio_of_const(type, i2d, out, x)
#define ASN1_PCTX_FLAGS_SHOW_ABSENT 0x001
#define ASN1_PCTX_FLAGS_SHOW_SEQUENCE 0x002
#define ASN1_PCTX_FLAGS_SHOW_SSOF 0x004
#define ASN1_PCTX_FLAGS_SHOW_TYPE 0x008
#define ASN1_PCTX_FLAGS_NO_ANY_TYPE 0x010
#define ASN1_PCTX_FLAGS_NO_MSTRING_TYPE 0x020
#define ASN1_PCTX_FLAGS_NO_FIELD_NAME 0x040
#define ASN1_PCTX_FLAGS_SHOW_FIELD_STRUCT_NAME 0x080
#define ASN1_PCTX_FLAGS_NO_STRUCT_NAME 0x100
#define ASN1_F_A2D_ASN1_OBJECT 100
#define ASN1_F_A2I_ASN1_INTEGER 102
#define ASN1_F_A2I_ASN1_STRING 103
#define ASN1_F_APPEND_EXP 176
#define ASN1_F_ASN1_BIT_STRING_SET_BIT 183
#define ASN1_F_ASN1_CB 177
#define ASN1_F_ASN1_CHECK_TLEN 104
#define ASN1_F_ASN1_COLLECT 106
#define ASN1_F_ASN1_D2I_EX_PRIMITIVE 108
#define ASN1_F_ASN1_D2I_FP 109
#define ASN1_F_ASN1_D2I_READ_BIO 107
#define ASN1_F_ASN1_DIGEST 184
#define ASN1_F_ASN1_DO_ADB 110
#define ASN1_F_ASN1_DO_LOCK 233
#define ASN1_F_ASN1_DUP 111
#define ASN1_F_ASN1_EX_C2I 204
#define ASN1_F_ASN1_FIND_END 190
#define ASN1_F_ASN1_GENERALIZEDTIME_ADJ 216
#define ASN1_F_ASN1_GENERATE_V3 178
#define ASN1_F_ASN1_GET_INT64 224
#define ASN1_F_ASN1_GET_OBJECT 114
#define ASN1_F_ASN1_GET_UINT64 225
#define ASN1_F_ASN1_I2D_BIO 116
#define ASN1_F_ASN1_I2D_FP 117
#define ASN1_F_ASN1_ITEM_D2I_FP 206
#define ASN1_F_ASN1_ITEM_DUP 191
#define ASN1_F_ASN1_ITEM_EMBED_D2I 120
#define ASN1_F_ASN1_ITEM_EMBED_NEW 121
#define ASN1_F_ASN1_ITEM_I2D_BIO 192
#define ASN1_F_ASN1_ITEM_I2D_FP 193
#define ASN1_F_ASN1_ITEM_PACK 198
#define ASN1_F_ASN1_ITEM_SIGN 195
#define ASN1_F_ASN1_ITEM_SIGN_CTX 220
#define ASN1_F_ASN1_ITEM_UNPACK 199
#define ASN1_F_ASN1_ITEM_VERIFY 197
#define ASN1_F_ASN1_MBSTRING_NCOPY 122
#define ASN1_F_ASN1_OBJECT_NEW 123
#define ASN1_F_ASN1_OUTPUT_DATA 214
#define ASN1_F_ASN1_PCTX_NEW 205
#define ASN1_F_ASN1_SCTX_NEW 221
#define ASN1_F_ASN1_SIGN 128
#define ASN1_F_ASN1_STR2TYPE 179
#define ASN1_F_ASN1_STRING_GET_INT64 227
#define ASN1_F_ASN1_STRING_GET_UINT64 230
#define ASN1_F_ASN1_STRING_SET 186
#define ASN1_F_ASN1_STRING_TABLE_ADD 129
#define ASN1_F_ASN1_STRING_TO_BN 228
#define ASN1_F_ASN1_STRING_TYPE_NEW 130
#define ASN1_F_ASN1_TEMPLATE_EX_D2I 132
#define ASN1_F_ASN1_TEMPLATE_NEW 133
#define ASN1_F_ASN1_TEMPLATE_NOEXP_D2I 131
#define ASN1_F_ASN1_TIME_ADJ 217
#define ASN1_F_ASN1_TYPE_GET_INT_OCTETSTRING 134
#define ASN1_F_ASN1_TYPE_GET_OCTETSTRING 135
#define ASN1_F_ASN1_UTCTIME_ADJ 218
#define ASN1_F_ASN1_VERIFY 137
#define ASN1_F_B64_READ_ASN1 209
#define ASN1_F_B64_WRITE_ASN1 210
#define ASN1_F_BIO_NEW_NDEF 208
#define ASN1_F_BITSTR_CB 180
#define ASN1_F_BN_TO_ASN1_STRING 229
#define ASN1_F_C2I_ASN1_BIT_STRING 189
#define ASN1_F_C2I_ASN1_INTEGER 194
#define ASN1_F_C2I_ASN1_OBJECT 196
#define ASN1_F_C2I_IBUF 226
#define ASN1_F_COLLECT_DATA 140
#define ASN1_F_D2I_ASN1_OBJECT 147
#define ASN1_F_D2I_ASN1_UINTEGER 150
#define ASN1_F_D2I_AUTOPRIVATEKEY 207
#define ASN1_F_D2I_PRIVATEKEY 154
#define ASN1_F_D2I_PUBLICKEY 155
#define ASN1_F_DO_TCREATE 222
#define ASN1_F_I2D_ASN1_BIO_STREAM 211
#define ASN1_F_I2D_DSA_PUBKEY 161
#define ASN1_F_I2D_EC_PUBKEY 181
#define ASN1_F_I2D_PRIVATEKEY 163
#define ASN1_F_I2D_PUBLICKEY 164
#define ASN1_F_I2D_RSA_PUBKEY 165
#define ASN1_F_LONG_C2I 166
#define ASN1_F_OID_MODULE_INIT 174
#define ASN1_F_PARSE_TAGGING 182
#define ASN1_F_PKCS5_PBE2_SET_IV 167
#define ASN1_F_PKCS5_PBE2_SET_SCRYPT 231
#define ASN1_F_PKCS5_PBE_SET 202
#define ASN1_F_PKCS5_PBE_SET0_ALGOR 215
#define ASN1_F_PKCS5_PBKDF2_SET 219
#define ASN1_F_PKCS5_SCRYPT_SET 232
#define ASN1_F_SMIME_READ_ASN1 212
#define ASN1_F_SMIME_TEXT 213
#define ASN1_F_STBL_MODULE_INIT 223
#define ASN1_F_X509_CRL_ADD0_REVOKED 169
#define ASN1_F_X509_INFO_NEW 170
#define ASN1_F_X509_NAME_ENCODE 203
#define ASN1_F_X509_NAME_EX_D2I 158
#define ASN1_F_X509_NAME_EX_NEW 171
#define ASN1_F_X509_PKEY_NEW 173
#define ASN1_R_ADDING_OBJECT 171
#define ASN1_R_ASN1_PARSE_ERROR 203
#define ASN1_R_ASN1_SIG_PARSE_ERROR 204
#define ASN1_R_AUX_ERROR 100
#define ASN1_R_BAD_OBJECT_HEADER 102
#define ASN1_R_BMPSTRING_IS_WRONG_LENGTH 214
#define ASN1_R_BN_LIB 105
#define ASN1_R_BOOLEAN_IS_WRONG_LENGTH 106
#define ASN1_R_BUFFER_TOO_SMALL 107
#define ASN1_R_CIPHER_HAS_NO_OBJECT_IDENTIFIER 108
#define ASN1_R_CONTEXT_NOT_INITIALISED 217
#define ASN1_R_DATA_IS_WRONG 109
#define ASN1_R_DECODE_ERROR 110
#define ASN1_R_DEPTH_EXCEEDED 174
#define ASN1_R_DIGEST_AND_KEY_TYPE_NOT_SUPPORTED 198
#define ASN1_R_ENCODE_ERROR 112
#define ASN1_R_ERROR_GETTING_TIME 173
#define ASN1_R_ERROR_LOADING_SECTION 172
#define ASN1_R_ERROR_SETTING_CIPHER_PARAMS 114
#define ASN1_R_EXPECTING_AN_INTEGER 115
#define ASN1_R_EXPECTING_AN_OBJECT 116
#define ASN1_R_EXPLICIT_LENGTH_MISMATCH 119
#define ASN1_R_EXPLICIT_TAG_NOT_CONSTRUCTED 120
#define ASN1_R_FIELD_MISSING 121
#define ASN1_R_FIRST_NUM_TOO_LARGE 122
#define ASN1_R_HEADER_TOO_LONG 123
#define ASN1_R_ILLEGAL_BITSTRING_FORMAT 175
#define ASN1_R_ILLEGAL_BOOLEAN 176
#define ASN1_R_ILLEGAL_CHARACTERS 124
#define ASN1_R_ILLEGAL_FORMAT 177
#define ASN1_R_ILLEGAL_HEX 178
#define ASN1_R_ILLEGAL_IMPLICIT_TAG 179
#define ASN1_R_ILLEGAL_INTEGER 180
#define ASN1_R_ILLEGAL_NEGATIVE_VALUE 226
#define ASN1_R_ILLEGAL_NESTED_TAGGING 181
#define ASN1_R_ILLEGAL_NULL 125
#define ASN1_R_ILLEGAL_NULL_VALUE 182
#define ASN1_R_ILLEGAL_OBJECT 183
#define ASN1_R_ILLEGAL_OPTIONAL_ANY 126
#define ASN1_R_ILLEGAL_OPTIONS_ON_ITEM_TEMPLATE 170
#define ASN1_R_ILLEGAL_PADDING 221
#define ASN1_R_ILLEGAL_TAGGED_ANY 127
#define ASN1_R_ILLEGAL_TIME_VALUE 184
#define ASN1_R_ILLEGAL_ZERO_CONTENT 222
#define ASN1_R_INTEGER_NOT_ASCII_FORMAT 185
#define ASN1_R_INTEGER_TOO_LARGE_FOR_LONG 128
#define ASN1_R_INVALID_BIT_STRING_BITS_LEFT 220
#define ASN1_R_INVALID_BMPSTRING_LENGTH 129
#define ASN1_R_INVALID_DIGIT 130
#define ASN1_R_INVALID_MIME_TYPE 205
#define ASN1_R_INVALID_MODIFIER 186
#define ASN1_R_INVALID_NUMBER 187
#define ASN1_R_INVALID_OBJECT_ENCODING 216
#define ASN1_R_INVALID_SCRYPT_PARAMETERS 227
#define ASN1_R_INVALID_SEPARATOR 131
#define ASN1_R_INVALID_STRING_TABLE_VALUE 218
#define ASN1_R_INVALID_UNIVERSALSTRING_LENGTH 133
#define ASN1_R_INVALID_UTF8STRING 134
#define ASN1_R_INVALID_VALUE 219
#define ASN1_R_LIST_ERROR 188
#define ASN1_R_MIME_NO_CONTENT_TYPE 206
#define ASN1_R_MIME_PARSE_ERROR 207
#define ASN1_R_MIME_SIG_PARSE_ERROR 208
#define ASN1_R_MISSING_EOC 137
#define ASN1_R_MISSING_SECOND_NUMBER 138
#define ASN1_R_MISSING_VALUE 189
#define ASN1_R_MSTRING_NOT_UNIVERSAL 139
#define ASN1_R_MSTRING_WRONG_TAG 140
#define ASN1_R_NESTED_ASN1_STRING 197
#define ASN1_R_NON_HEX_CHARACTERS 141
#define ASN1_R_NOT_ASCII_FORMAT 190
#define ASN1_R_NOT_ENOUGH_DATA 142
#define ASN1_R_NO_CONTENT_TYPE 209
#define ASN1_R_NO_MATCHING_CHOICE_TYPE 143
#define ASN1_R_NO_MULTIPART_BODY_FAILURE 210
#define ASN1_R_NO_MULTIPART_BOUNDARY 211
#define ASN1_R_NO_SIG_CONTENT_TYPE 212
#define ASN1_R_NULL_IS_WRONG_LENGTH 144
#define ASN1_R_OBJECT_NOT_ASCII_FORMAT 191
#define ASN1_R_ODD_NUMBER_OF_CHARS 145
#define ASN1_R_SECOND_NUMBER_TOO_LARGE 147
#define ASN1_R_SEQUENCE_LENGTH_MISMATCH 148
#define ASN1_R_SEQUENCE_NOT_CONSTRUCTED 149
#define ASN1_R_SEQUENCE_OR_SET_NEEDS_CONFIG 192
#define ASN1_R_SHORT_LINE 150
#define ASN1_R_SIG_INVALID_MIME_TYPE 213
#define ASN1_R_STREAMING_NOT_SUPPORTED 202
#define ASN1_R_STRING_TOO_LONG 151
#define ASN1_R_STRING_TOO_SHORT 152
#define ASN1_R_THE_ASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD 154
#define ASN1_R_TIME_NOT_ASCII_FORMAT 193
#define ASN1_R_TOO_LARGE 223
#define ASN1_R_TOO_LONG 155
#define ASN1_R_TOO_SMALL 224
#define ASN1_R_TYPE_NOT_CONSTRUCTED 156
#define ASN1_R_TYPE_NOT_PRIMITIVE 195
#define ASN1_R_UNEXPECTED_EOC 159
#define ASN1_R_UNIVERSALSTRING_IS_WRONG_LENGTH 215
#define ASN1_R_UNKNOWN_FORMAT 160
#define ASN1_R_UNKNOWN_MESSAGE_DIGEST_ALGORITHM 161
#define ASN1_R_UNKNOWN_OBJECT_TYPE 162
#define ASN1_R_UNKNOWN_PUBLIC_KEY_TYPE 163
#define ASN1_R_UNKNOWN_SIGNATURE_ALGORITHM 199
#define ASN1_R_UNKNOWN_TAG 194
#define ASN1_R_UNSUPPORTED_ANY_DEFINED_BY_TYPE 164
#define ASN1_R_UNSUPPORTED_PUBLIC_KEY_TYPE 167
#define ASN1_R_UNSUPPORTED_TYPE 196
#define ASN1_R_WRONG_INTEGER_TYPE 225
#define ASN1_R_WRONG_PUBLIC_KEY_TYPE 200
#define ASN1_R_WRONG_TAG 168
Typedefs
typedef struct ASN1_VALUE_st ASN1_VALUE
typedef const ASN1_ITEM ASN1_ITEM_EXP
Functions
TYPEDEF_D2I2D_OF (void)
typedef STACK_OF (ASN1_TYPE) ASN1_SEQUENCE_ANY
DECLARE_ASN1_ENCODE_FUNCTIONS_const (ASN1_SEQUENCE_ANY, ASN1_SEQUENCE_ANY) DECLARE_ASN1_ENCODE_FUNCTIONS_const(ASN1_SEQUENCE_ANY
DECLARE_ASN1_FUNCTIONS_fname (ASN1_TYPE, ASN1_ANY, ASN1_TYPE) int ASN1_TYPE_get(const ASN1_TYPE *a)
void ASN1_TYPE_set (ASN1_TYPE *a, int type, void *value)
int ASN1_TYPE_set1 (ASN1_TYPE *a, int type, const void *value)
int ASN1_TYPE_cmp (const ASN1_TYPE *a, const ASN1_TYPE *b)
ASN1_TYPE * ASN1_TYPE_pack_sequence (const ASN1_ITEM *it, void *s, ASN1_TYPE **t)
void * ASN1_TYPE_unpack_sequence (const ASN1_ITEM *it, const ASN1_TYPE *t)
ASN1_OBJECT * ASN1_OBJECT_new (void)
void ASN1_OBJECT_free (ASN1_OBJECT *a)
int i2d_ASN1_OBJECT (const ASN1_OBJECT *a, unsigned char **pp)
ASN1_OBJECT * d2i_ASN1_OBJECT (ASN1_OBJECT **a, const unsigned char **pp, long length)
ASN1_STRING * ASN1_STRING_new (void)
void ASN1_STRING_free (ASN1_STRING *a)
void ASN1_STRING_clear_free (ASN1_STRING *a)
int ASN1_STRING_copy (ASN1_STRING *dst, const ASN1_STRING *str)
ASN1_STRING * ASN1_STRING_dup (const ASN1_STRING *a)
ASN1_STRING * ASN1_STRING_type_new (int type)
int ASN1_STRING_cmp (const ASN1_STRING *a, const ASN1_STRING *b)
int ASN1_STRING_set (ASN1_STRING *str, const void *data, int len)
void ASN1_STRING_set0 (ASN1_STRING *str, void *data, int len)
int ASN1_STRING_length (const ASN1_STRING *x)
void ASN1_STRING_length_set (ASN1_STRING *x, int n)
int ASN1_STRING_type (const ASN1_STRING *x)
const unsigned char * ASN1_STRING_get0_data (const ASN1_STRING *x)
int ASN1_BIT_STRING_set (ASN1_BIT_STRING *a, unsigned char *d, int length)
int ASN1_BIT_STRING_set_bit (ASN1_BIT_STRING *a, int n, int value)
int ASN1_BIT_STRING_get_bit (const ASN1_BIT_STRING *a, int n)
int ASN1_BIT_STRING_check (const ASN1_BIT_STRING *a, const unsigned char *flags, int flags_len)
int ASN1_BIT_STRING_name_print (BIO *out, ASN1_BIT_STRING *bs, BIT_STRING_BITNAME *tbl, int indent)
int ASN1_BIT_STRING_num_asc (const char *name, BIT_STRING_BITNAME *tbl)
int ASN1_BIT_STRING_set_asc (ASN1_BIT_STRING *bs, const char *name, int value, BIT_STRING_BITNAME *tbl)
ASN1_INTEGER * d2i_ASN1_UINTEGER (ASN1_INTEGER **a, const unsigned char **pp, long length)
ASN1_INTEGER * ASN1_INTEGER_dup (const ASN1_INTEGER *x)
int ASN1_INTEGER_cmp (const ASN1_INTEGER *x, const ASN1_INTEGER *y)
int ASN1_UTCTIME_check (const ASN1_UTCTIME *a)
ASN1_UTCTIME * ASN1_UTCTIME_set (ASN1_UTCTIME *s, time_t t)
ASN1_UTCTIME * ASN1_UTCTIME_adj (ASN1_UTCTIME *s, time_t t, int offset_day, long offset_sec)
int ASN1_UTCTIME_set_string (ASN1_UTCTIME *s, const char *str)
int ASN1_UTCTIME_cmp_time_t (const ASN1_UTCTIME *s, time_t t)
int ASN1_GENERALIZEDTIME_check (const ASN1_GENERALIZEDTIME *a)
ASN1_GENERALIZEDTIME * ASN1_GENERALIZEDTIME_set (ASN1_GENERALIZEDTIME *s, time_t t)
ASN1_GENERALIZEDTIME * ASN1_GENERALIZEDTIME_adj (ASN1_GENERALIZEDTIME *s, time_t t, int offset_day, long offset_sec)
int ASN1_GENERALIZEDTIME_set_string (ASN1_GENERALIZEDTIME *s, const char *str)
int ASN1_TIME_diff (int *pday, int *psec, const ASN1_TIME *from, const ASN1_TIME *to)
ASN1_OCTET_STRING * ASN1_OCTET_STRING_dup (const ASN1_OCTET_STRING *a)
int ASN1_OCTET_STRING_cmp (const ASN1_OCTET_STRING *a, const ASN1_OCTET_STRING *b)
int ASN1_OCTET_STRING_set (ASN1_OCTET_STRING *str, const unsigned char *data, int len)
int UTF8_getc (const unsigned char *str, int len, unsigned long *val)
int UTF8_putc (unsigned char *str, int len, unsigned long value)
DECLARE_ASN1_FUNCTIONS_name (ASN1_STRING, ASN1_PRINTABLE) DECLARE_ASN1_FUNCTIONS_name(ASN1_STRING
DIRECTORYSTRING DECLARE_ASN1_FUNCTIONS_name (ASN1_STRING, DISPLAYTEXT) ASN1_TIME *ASN1_TIME_set(ASN1_TIME *s
ASN1_TIME * ASN1_TIME_adj (ASN1_TIME *s, time_t t, int offset_day, long offset_sec)
int ASN1_TIME_check (const ASN1_TIME *t)
ASN1_GENERALIZEDTIME * ASN1_TIME_to_generalizedtime (ASN1_TIME *t, ASN1_GENERALIZEDTIME **out)
int ASN1_TIME_set_string (ASN1_TIME *s, const char *str)
int i2a_ASN1_INTEGER (BIO *bp, const ASN1_INTEGER *a)
int a2i_ASN1_INTEGER (BIO *bp, ASN1_INTEGER *bs, char *buf, int size)
int i2a_ASN1_ENUMERATED (BIO *bp, const ASN1_ENUMERATED *a)
int a2i_ASN1_ENUMERATED (BIO *bp, ASN1_ENUMERATED *bs, char *buf, int size)
int i2a_ASN1_OBJECT (BIO *bp, const ASN1_OBJECT *a)
int a2i_ASN1_STRING (BIO *bp, ASN1_STRING *bs, char *buf, int size)
int i2a_ASN1_STRING (BIO *bp, const ASN1_STRING *a, int type)
int i2t_ASN1_OBJECT (char *buf, int buf_len, const ASN1_OBJECT *a)
int a2d_ASN1_OBJECT (unsigned char *out, int olen, const char *buf, int num)
ASN1_OBJECT * ASN1_OBJECT_create (int nid, unsigned char *data, int len, const char *sn, const char *ln)
int ASN1_INTEGER_get_int64 (int64_t *pr, const ASN1_INTEGER *a)
int ASN1_INTEGER_set_int64 (ASN1_INTEGER *a, int64_t r)
int ASN1_INTEGER_get_uint64 (uint64_t *pr, const ASN1_INTEGER *a)
int ASN1_INTEGER_set_uint64 (ASN1_INTEGER *a, uint64_t r)
int ASN1_INTEGER_set (ASN1_INTEGER *a, long v)
long ASN1_INTEGER_get (const ASN1_INTEGER *a)
ASN1_INTEGER * BN_to_ASN1_INTEGER (const BIGNUM *bn, ASN1_INTEGER *ai)
BIGNUM * ASN1_INTEGER_to_BN (const ASN1_INTEGER *ai, BIGNUM *bn)
int ASN1_ENUMERATED_get_int64 (int64_t *pr, const ASN1_ENUMERATED *a)
int ASN1_ENUMERATED_set_int64 (ASN1_ENUMERATED *a, int64_t r)
int ASN1_ENUMERATED_set (ASN1_ENUMERATED *a, long v)
long ASN1_ENUMERATED_get (const ASN1_ENUMERATED *a)
ASN1_ENUMERATED * BN_to_ASN1_ENUMERATED (const BIGNUM *bn, ASN1_ENUMERATED *ai)
BIGNUM * ASN1_ENUMERATED_to_BN (const ASN1_ENUMERATED *ai, BIGNUM *bn)
int ASN1_PRINTABLE_type (const unsigned char *s, int max)
unsigned long ASN1_tag2bit (int tag)
int ASN1_get_object (const unsigned char **pp, long *plength, int *ptag, int *pclass, long omax)
int ASN1_check_infinite_end (unsigned char **p, long len)
int ASN1_const_check_infinite_end (const unsigned char **p, long len)
void ASN1_put_object (unsigned char **pp, int constructed, int length, int tag, int xclass)
int ASN1_put_eoc (unsigned char **pp)
int ASN1_object_size (int constructed, int length, int tag)
void * ASN1_dup (i2d_of_void *i2d, d2i_of_void *d2i, void *x)
void * ASN1_item_dup (const ASN1_ITEM *it, void *x)
void * ASN1_d2i_fp (void *(*xnew)(void), d2i_of_void *d2i, FILE *in, void **x)
void * ASN1_item_d2i_fp (const ASN1_ITEM *it, FILE *in, void *x)
int ASN1_i2d_fp (i2d_of_void *i2d, FILE *out, void *x)
int ASN1_item_i2d_fp (const ASN1_ITEM *it, FILE *out, void *x)
int ASN1_STRING_print_ex_fp (FILE *fp, const ASN1_STRING *str, unsigned long flags)
int ASN1_STRING_to_UTF8 (unsigned char **out, const ASN1_STRING *in)
void * ASN1_d2i_bio (void *(*xnew)(void), d2i_of_void *d2i, BIO *in, void **x)
void * ASN1_item_d2i_bio (const ASN1_ITEM *it, BIO *in, void *x)
int ASN1_i2d_bio (i2d_of_void *i2d, BIO *out, unsigned char *x)
int ASN1_item_i2d_bio (const ASN1_ITEM *it, BIO *out, void *x)
int ASN1_UTCTIME_print (BIO *fp, const ASN1_UTCTIME *a)
int ASN1_GENERALIZEDTIME_print (BIO *fp, const ASN1_GENERALIZEDTIME *a)
int ASN1_TIME_print (BIO *fp, const ASN1_TIME *a)
int ASN1_STRING_print (BIO *bp, const ASN1_STRING *v)
int ASN1_STRING_print_ex (BIO *out, const ASN1_STRING *str, unsigned long flags)
int ASN1_buf_print (BIO *bp, const unsigned char *buf, size_t buflen, int off)
int ASN1_bn_print (BIO *bp, const char *number, const BIGNUM *num, unsigned char *buf, int off)
int ASN1_parse (BIO *bp, const unsigned char *pp, long len, int indent)
int ASN1_parse_dump (BIO *bp, const unsigned char *pp, long len, int indent, int dump)
const char * ASN1_tag2str (int tag)
int ASN1_UNIVERSALSTRING_to_string (ASN1_UNIVERSALSTRING *s)
int ASN1_TYPE_set_octetstring (ASN1_TYPE *a, unsigned char *data, int len)
int ASN1_TYPE_get_octetstring (const ASN1_TYPE *a, unsigned char *data, int max_len)
int ASN1_TYPE_set_int_octetstring (ASN1_TYPE *a, long num, unsigned char *data, int len)
int ASN1_TYPE_get_int_octetstring (const ASN1_TYPE *a, long *num, unsigned char *data, int max_len)
void * ASN1_item_unpack (const ASN1_STRING *oct, const ASN1_ITEM *it)
ASN1_STRING * ASN1_item_pack (void *obj, const ASN1_ITEM *it, ASN1_OCTET_STRING **oct)
void ASN1_STRING_set_default_mask (unsigned long mask)
int ASN1_STRING_set_default_mask_asc (const char *p)
unsigned long ASN1_STRING_get_default_mask (void)
int ASN1_mbstring_copy (ASN1_STRING **out, const unsigned char *in, int len, int inform, unsigned long mask)
int ASN1_mbstring_ncopy (ASN1_STRING **out, const unsigned char *in, int len, int inform, unsigned long mask, long minsize, long maxsize)
ASN1_STRING * ASN1_STRING_set_by_NID (ASN1_STRING **out, const unsigned char *in, int inlen, int inform, int nid)
ASN1_STRING_TABLE * ASN1_STRING_TABLE_get (int nid)
int ASN1_STRING_TABLE_add (int, long, long, unsigned long, unsigned long)
void ASN1_STRING_TABLE_cleanup (void)
ASN1_VALUE * ASN1_item_new (const ASN1_ITEM *it)
void ASN1_item_free (ASN1_VALUE *val, const ASN1_ITEM *it)
ASN1_VALUE * ASN1_item_d2i (ASN1_VALUE **val, const unsigned char **in, long len, const ASN1_ITEM *it)
int ASN1_item_i2d (ASN1_VALUE *val, unsigned char **out, const ASN1_ITEM *it)
int ASN1_item_ndef_i2d (ASN1_VALUE *val, unsigned char **out, const ASN1_ITEM *it)
void ASN1_add_oid_module (void)
void ASN1_add_stable_module (void)
ASN1_TYPE * ASN1_generate_nconf (const char *str, CONF *nconf)
ASN1_TYPE * ASN1_generate_v3 (const char *str, X509V3_CTX *cnf)
int ASN1_str2mask (const char *str, unsigned long *pmask)
int ASN1_item_print (BIO *out, ASN1_VALUE *ifld, int indent, const ASN1_ITEM *it, const ASN1_PCTX *pctx)
ASN1_PCTX * ASN1_PCTX_new (void)
void ASN1_PCTX_free (ASN1_PCTX *p)
unsigned long ASN1_PCTX_get_flags (const ASN1_PCTX *p)
void ASN1_PCTX_set_flags (ASN1_PCTX *p, unsigned long flags)
unsigned long ASN1_PCTX_get_nm_flags (const ASN1_PCTX *p)
void ASN1_PCTX_set_nm_flags (ASN1_PCTX *p, unsigned long flags)
unsigned long ASN1_PCTX_get_cert_flags (const ASN1_PCTX *p)
void ASN1_PCTX_set_cert_flags (ASN1_PCTX *p, unsigned long flags)
unsigned long ASN1_PCTX_get_oid_flags (const ASN1_PCTX *p)
void ASN1_PCTX_set_oid_flags (ASN1_PCTX *p, unsigned long flags)
unsigned long ASN1_PCTX_get_str_flags (const ASN1_PCTX *p)
void ASN1_PCTX_set_str_flags (ASN1_PCTX *p, unsigned long flags)
ASN1_SCTX * ASN1_SCTX_new (int(*scan_cb)(ASN1_SCTX *ctx))
void ASN1_SCTX_free (ASN1_SCTX *p)
const ASN1_ITEM * ASN1_SCTX_get_item (ASN1_SCTX *p)
const ASN1_TEMPLATE * ASN1_SCTX_get_template (ASN1_SCTX *p)
unsigned long ASN1_SCTX_get_flags (ASN1_SCTX *p)
void ASN1_SCTX_set_app_data (ASN1_SCTX *p, void *data)
void * ASN1_SCTX_get_app_data (ASN1_SCTX *p)
const BIO_METHOD * BIO_f_asn1 (void)
BIO * BIO_new_NDEF (BIO *out, ASN1_VALUE *val, const ASN1_ITEM *it)
int i2d_ASN1_bio_stream (BIO *out, ASN1_VALUE *val, BIO *in, int flags, const ASN1_ITEM *it)
int PEM_write_bio_ASN1_stream (BIO *out, ASN1_VALUE *val, BIO *in, int flags, const char *hdr, const ASN1_ITEM *it)
int SMIME_write_ASN1 (BIO *bio, ASN1_VALUE *val, BIO *data, int flags, int ctype_nid, int econt_nid, STACK_OF(X509_ALGOR) *mdalgs, const ASN1_ITEM *it)
ASN1_VALUE * SMIME_read_ASN1 (BIO *bio, BIO **bcont, const ASN1_ITEM *it)
int SMIME_crlf_copy (BIO *in, BIO *out, int flags)
int SMIME_text (BIO *in, BIO *out)
const ASN1_ITEM * ASN1_ITEM_lookup (const char *name)
const ASN1_ITEM * ASN1_ITEM_get (size_t i)
int ERR_load_ASN1_strings (void)
Variables
DIRECTORYSTRING time_t t
Macro Definition Documentation
ASN1_d2i_bio_of
#define ASN1_d2i_bio_of (type, xnew, d2i, in, x)
Value:
((type*)ASN1_d2i_bio(CHECKED_NEW_OF(type, xnew), \
                          CHECKED_D2I_OF(type, d2i), \
                          in, \
                          CHECKED_PPTR_OF(type, x)))
Definition at line 731 of file asn1.h.
Referenced by d2i_DSA_PUBKEY_bio(), d2i_DSAPrivateKey_bio(), d2i_EC_PUBKEY_bio(), d2i_ECPrivateKey_bio(), d2i_PKCS8_bio(), d2i_PKCS8_PRIV_KEY_INFO_bio(), d2i_PrivateKey_bio(), d2i_PUBKEY_bio(), and d2i_RSA_PUBKEY_bio().
ASN1_d2i_fp_of
#define ASN1_d2i_fp_of (type, xnew, d2i, in, x)
Value:
((type*)ASN1_d2i_fp(CHECKED_NEW_OF(type, xnew), \
                        CHECKED_D2I_OF(type, d2i), \
                        in, \
                        CHECKED_PPTR_OF(type, x)))
Definition at line 704 of file asn1.h.
Referenced by d2i_DSA_PUBKEY_fp(), d2i_DSAPrivateKey_fp(), d2i_EC_PUBKEY_fp(), d2i_ECPrivateKey_fp(), d2i_PKCS8_fp(), d2i_PKCS8_PRIV_KEY_INFO_fp(), d2i_PrivateKey_fp(), and d2i_PUBKEY_fp().
ASN1_dup_of
#define ASN1_dup_of (type, i2d, d2i, x)
Value:
((type*)ASN1_dup(CHECKED_I2D_OF(type, i2d), \
                     CHECKED_D2I_OF(type, d2i), \
                     CHECKED_PTR_OF(type, x)))
Definition at line 683 of file asn1.h.
ASN1_dup_of_const
#define ASN1_dup_of_const (type, i2d, d2i, x)
Value:
((type*)ASN1_dup(CHECKED_I2D_OF(const type, i2d), \
                     CHECKED_D2I_OF(type, d2i), \
                     CHECKED_PTR_OF(const type, x)))
Definition at line 688 of file asn1.h.
ASN1_F_A2D_ASN1_OBJECT
#define ASN1_F_A2D_ASN1_OBJECT 100
Definition at line 887 of file asn1.h.
ASN1_F_A2I_ASN1_INTEGER
#define ASN1_F_A2I_ASN1_INTEGER 102
Definition at line 888 of file asn1.h.
ASN1_F_A2I_ASN1_STRING
#define ASN1_F_A2I_ASN1_STRING 103
Definition at line 889 of file asn1.h.
ASN1_F_APPEND_EXP
#define ASN1_F_APPEND_EXP 176
Definition at line 890 of file asn1.h.
ASN1_F_ASN1_BIT_STRING_SET_BIT
#define ASN1_F_ASN1_BIT_STRING_SET_BIT 183
Definition at line 891 of file asn1.h.
ASN1_F_ASN1_CB
#define ASN1_F_ASN1_CB 177
Definition at line 892 of file asn1.h.
ASN1_F_ASN1_CHECK_TLEN
#define ASN1_F_ASN1_CHECK_TLEN 104
Definition at line 893 of file asn1.h.
ASN1_F_ASN1_COLLECT
#define ASN1_F_ASN1_COLLECT 106
Definition at line 894 of file asn1.h.
ASN1_F_ASN1_D2I_EX_PRIMITIVE
#define ASN1_F_ASN1_D2I_EX_PRIMITIVE 108
Definition at line 895 of file asn1.h.
ASN1_F_ASN1_D2I_FP
#define ASN1_F_ASN1_D2I_FP 109
Definition at line 896 of file asn1.h.
ASN1_F_ASN1_D2I_READ_BIO
#define ASN1_F_ASN1_D2I_READ_BIO 107
Definition at line 897 of file asn1.h.
ASN1_F_ASN1_DIGEST
#define ASN1_F_ASN1_DIGEST 184
Definition at line 898 of file asn1.h.
ASN1_F_ASN1_DO_ADB
#define ASN1_F_ASN1_DO_ADB 110
Definition at line 899 of file asn1.h.
Referenced by asn1_do_adb().
ASN1_F_ASN1_DO_LOCK
#define ASN1_F_ASN1_DO_LOCK 233
Definition at line 900 of file asn1.h.
ASN1_F_ASN1_DUP
#define ASN1_F_ASN1_DUP 111
Definition at line 901 of file asn1.h.
ASN1_F_ASN1_EX_C2I
#define ASN1_F_ASN1_EX_C2I 204
Definition at line 902 of file asn1.h.
ASN1_F_ASN1_FIND_END
#define ASN1_F_ASN1_FIND_END 190
Definition at line 903 of file asn1.h.
ASN1_F_ASN1_GENERALIZEDTIME_ADJ
#define ASN1_F_ASN1_GENERALIZEDTIME_ADJ 216
Definition at line 904 of file asn1.h.
Referenced by ASN1_GENERALIZEDTIME_adj().
ASN1_F_ASN1_GENERATE_V3
#define ASN1_F_ASN1_GENERATE_V3 178
Definition at line 905 of file asn1.h.
ASN1_F_ASN1_GET_INT64
#define ASN1_F_ASN1_GET_INT64 224
Definition at line 906 of file asn1.h.
ASN1_F_ASN1_GET_OBJECT
#define ASN1_F_ASN1_GET_OBJECT 114
Definition at line 907 of file asn1.h.
ASN1_F_ASN1_GET_UINT64
#define ASN1_F_ASN1_GET_UINT64 225
Definition at line 908 of file asn1.h.
ASN1_F_ASN1_I2D_BIO
#define ASN1_F_ASN1_I2D_BIO 116
Definition at line 909 of file asn1.h.
ASN1_F_ASN1_I2D_FP
#define ASN1_F_ASN1_I2D_FP 117
Definition at line 910 of file asn1.h.
ASN1_F_ASN1_ITEM_D2I_FP
#define ASN1_F_ASN1_ITEM_D2I_FP 206
Definition at line 911 of file asn1.h.
ASN1_F_ASN1_ITEM_DUP
#define ASN1_F_ASN1_ITEM_DUP 191
Definition at line 912 of file asn1.h.
ASN1_F_ASN1_ITEM_EMBED_D2I
#define ASN1_F_ASN1_ITEM_EMBED_D2I 120
Definition at line 913 of file asn1.h.
ASN1_F_ASN1_ITEM_EMBED_NEW
#define ASN1_F_ASN1_ITEM_EMBED_NEW 121
Definition at line 914 of file asn1.h.
ASN1_F_ASN1_ITEM_I2D_BIO
#define ASN1_F_ASN1_ITEM_I2D_BIO 192
Definition at line 915 of file asn1.h.
ASN1_F_ASN1_ITEM_I2D_FP
#define ASN1_F_ASN1_ITEM_I2D_FP 193
Definition at line 916 of file asn1.h.
ASN1_F_ASN1_ITEM_PACK
#define ASN1_F_ASN1_ITEM_PACK 198
Definition at line 917 of file asn1.h.
Referenced by ASN1_item_pack().
ASN1_F_ASN1_ITEM_SIGN
#define ASN1_F_ASN1_ITEM_SIGN 195
Definition at line 918 of file asn1.h.
Referenced by ASN1_item_sign().
ASN1_F_ASN1_ITEM_SIGN_CTX
#define ASN1_F_ASN1_ITEM_SIGN_CTX 220
Definition at line 919 of file asn1.h.
Referenced by ASN1_item_sign_ctx().
ASN1_F_ASN1_ITEM_UNPACK
#define ASN1_F_ASN1_ITEM_UNPACK 199
Definition at line 920 of file asn1.h.
ASN1_F_ASN1_ITEM_VERIFY
#define ASN1_F_ASN1_ITEM_VERIFY 197
Definition at line 921 of file asn1.h.
ASN1_F_ASN1_MBSTRING_NCOPY
#define ASN1_F_ASN1_MBSTRING_NCOPY 122
Definition at line 922 of file asn1.h.
ASN1_F_ASN1_OBJECT_NEW
#define ASN1_F_ASN1_OBJECT_NEW 123
Definition at line 923 of file asn1.h.
ASN1_F_ASN1_OUTPUT_DATA
#define ASN1_F_ASN1_OUTPUT_DATA 214
Definition at line 924 of file asn1.h.
ASN1_F_ASN1_PCTX_NEW
#define ASN1_F_ASN1_PCTX_NEW 205
Definition at line 925 of file asn1.h.
ASN1_F_ASN1_SCTX_NEW
#define ASN1_F_ASN1_SCTX_NEW 221
Definition at line 926 of file asn1.h.
ASN1_F_ASN1_SIGN
#define ASN1_F_ASN1_SIGN 128
Definition at line 927 of file asn1.h.
Referenced by ASN1_sign().
ASN1_F_ASN1_STR2TYPE
#define ASN1_F_ASN1_STR2TYPE 179
Definition at line 928 of file asn1.h.
ASN1_F_ASN1_STRING_GET_INT64
#define ASN1_F_ASN1_STRING_GET_INT64 227
Definition at line 929 of file asn1.h.
ASN1_F_ASN1_STRING_GET_UINT64
#define ASN1_F_ASN1_STRING_GET_UINT64 230
Definition at line 930 of file asn1.h.
ASN1_F_ASN1_STRING_SET
#define ASN1_F_ASN1_STRING_SET 186
Definition at line 931 of file asn1.h.
ASN1_F_ASN1_STRING_TABLE_ADD
#define ASN1_F_ASN1_STRING_TABLE_ADD 129
Definition at line 932 of file asn1.h.
ASN1_F_ASN1_STRING_TO_BN
#define ASN1_F_ASN1_STRING_TO_BN 228
Definition at line 933 of file asn1.h.
ASN1_F_ASN1_STRING_TYPE_NEW
#define ASN1_F_ASN1_STRING_TYPE_NEW 130
Definition at line 934 of file asn1.h.
ASN1_F_ASN1_TEMPLATE_EX_D2I
#define ASN1_F_ASN1_TEMPLATE_EX_D2I 132
Definition at line 935 of file asn1.h.
ASN1_F_ASN1_TEMPLATE_NEW
#define ASN1_F_ASN1_TEMPLATE_NEW 133
Definition at line 936 of file asn1.h.
ASN1_F_ASN1_TEMPLATE_NOEXP_D2I
#define ASN1_F_ASN1_TEMPLATE_NOEXP_D2I 131
Definition at line 937 of file asn1.h.
ASN1_F_ASN1_TIME_ADJ
#define ASN1_F_ASN1_TIME_ADJ 217
Definition at line 938 of file asn1.h.
Referenced by ASN1_TIME_adj().
ASN1_F_ASN1_TYPE_GET_INT_OCTETSTRING
#define ASN1_F_ASN1_TYPE_GET_INT_OCTETSTRING 134
Definition at line 939 of file asn1.h.
ASN1_F_ASN1_TYPE_GET_OCTETSTRING
#define ASN1_F_ASN1_TYPE_GET_OCTETSTRING 135
Definition at line 940 of file asn1.h.
ASN1_F_ASN1_UTCTIME_ADJ
#define ASN1_F_ASN1_UTCTIME_ADJ 218
Definition at line 941 of file asn1.h.
Referenced by ASN1_UTCTIME_adj().
ASN1_F_ASN1_VERIFY
#define ASN1_F_ASN1_VERIFY 137
Definition at line 942 of file asn1.h.
ASN1_F_B64_READ_ASN1
#define ASN1_F_B64_READ_ASN1 209
Definition at line 943 of file asn1.h.
ASN1_F_B64_WRITE_ASN1
#define ASN1_F_B64_WRITE_ASN1 210
Definition at line 944 of file asn1.h.
ASN1_F_BIO_NEW_NDEF
#define ASN1_F_BIO_NEW_NDEF 208
Definition at line 945 of file asn1.h.
ASN1_F_BITSTR_CB
#define ASN1_F_BITSTR_CB 180
Definition at line 946 of file asn1.h.
ASN1_F_BN_TO_ASN1_STRING
#define ASN1_F_BN_TO_ASN1_STRING 229
Definition at line 947 of file asn1.h.
ASN1_F_C2I_ASN1_BIT_STRING
#define ASN1_F_C2I_ASN1_BIT_STRING 189
Definition at line 948 of file asn1.h.
ASN1_F_C2I_ASN1_INTEGER
#define ASN1_F_C2I_ASN1_INTEGER 194
Definition at line 949 of file asn1.h.
ASN1_F_C2I_ASN1_OBJECT
#define ASN1_F_C2I_ASN1_OBJECT 196
Definition at line 950 of file asn1.h.
ASN1_F_C2I_IBUF
#define ASN1_F_C2I_IBUF 226
Definition at line 951 of file asn1.h.
ASN1_F_COLLECT_DATA
#define ASN1_F_COLLECT_DATA 140
Definition at line 952 of file asn1.h.
ASN1_F_D2I_ASN1_OBJECT
#define ASN1_F_D2I_ASN1_OBJECT 147
Definition at line 953 of file asn1.h.
ASN1_F_D2I_ASN1_UINTEGER
#define ASN1_F_D2I_ASN1_UINTEGER 150
Definition at line 954 of file asn1.h.
ASN1_F_D2I_AUTOPRIVATEKEY
#define ASN1_F_D2I_AUTOPRIVATEKEY 207
Definition at line 955 of file asn1.h.
ASN1_F_D2I_PRIVATEKEY
#define ASN1_F_D2I_PRIVATEKEY 154
Definition at line 956 of file asn1.h.
ASN1_F_D2I_PUBLICKEY
#define ASN1_F_D2I_PUBLICKEY 155
Definition at line 957 of file asn1.h.
ASN1_F_DO_TCREATE
#define ASN1_F_DO_TCREATE 222
Definition at line 958 of file asn1.h.
ASN1_F_I2D_ASN1_BIO_STREAM
#define ASN1_F_I2D_ASN1_BIO_STREAM 211
Definition at line 959 of file asn1.h.
ASN1_F_I2D_DSA_PUBKEY
#define ASN1_F_I2D_DSA_PUBKEY 161
Definition at line 960 of file asn1.h.
ASN1_F_I2D_EC_PUBKEY
#define ASN1_F_I2D_EC_PUBKEY 181
Definition at line 961 of file asn1.h.
ASN1_F_I2D_PRIVATEKEY
#define ASN1_F_I2D_PRIVATEKEY 163
Definition at line 962 of file asn1.h.
ASN1_F_I2D_PUBLICKEY
#define ASN1_F_I2D_PUBLICKEY 164
Definition at line 963 of file asn1.h.
Referenced by i2d_PublicKey().
ASN1_F_I2D_RSA_PUBKEY
#define ASN1_F_I2D_RSA_PUBKEY 165
Definition at line 964 of file asn1.h.
ASN1_F_LONG_C2I
#define ASN1_F_LONG_C2I 166
Definition at line 965 of file asn1.h.
ASN1_F_OID_MODULE_INIT
#define ASN1_F_OID_MODULE_INIT 174
Definition at line 966 of file asn1.h.
ASN1_F_PARSE_TAGGING
#define ASN1_F_PARSE_TAGGING 182
Definition at line 967 of file asn1.h.
ASN1_F_PKCS5_PBE2_SET_IV
#define ASN1_F_PKCS5_PBE2_SET_IV 167
Definition at line 968 of file asn1.h.
ASN1_F_PKCS5_PBE2_SET_SCRYPT
#define ASN1_F_PKCS5_PBE2_SET_SCRYPT 231
Definition at line 969 of file asn1.h.
ASN1_F_PKCS5_PBE_SET
#define ASN1_F_PKCS5_PBE_SET 202
Definition at line 970 of file asn1.h.
ASN1_F_PKCS5_PBE_SET0_ALGOR
#define ASN1_F_PKCS5_PBE_SET0_ALGOR 215
Definition at line 971 of file asn1.h.
ASN1_F_PKCS5_PBKDF2_SET
#define ASN1_F_PKCS5_PBKDF2_SET 219
Definition at line 972 of file asn1.h.
ASN1_F_PKCS5_SCRYPT_SET
#define ASN1_F_PKCS5_SCRYPT_SET 232
Definition at line 973 of file asn1.h.
ASN1_F_SMIME_READ_ASN1
#define ASN1_F_SMIME_READ_ASN1 212
Definition at line 974 of file asn1.h.
ASN1_F_SMIME_TEXT
#define ASN1_F_SMIME_TEXT 213
Definition at line 975 of file asn1.h.
ASN1_F_STBL_MODULE_INIT
#define ASN1_F_STBL_MODULE_INIT 223
Definition at line 976 of file asn1.h.
ASN1_F_X509_CRL_ADD0_REVOKED
#define ASN1_F_X509_CRL_ADD0_REVOKED 169
Definition at line 977 of file asn1.h.
ASN1_F_X509_INFO_NEW
#define ASN1_F_X509_INFO_NEW 170
Definition at line 978 of file asn1.h.
ASN1_F_X509_NAME_ENCODE
#define ASN1_F_X509_NAME_ENCODE 203
Definition at line 979 of file asn1.h.
ASN1_F_X509_NAME_EX_D2I
#define ASN1_F_X509_NAME_EX_D2I 158
Definition at line 980 of file asn1.h.
ASN1_F_X509_NAME_EX_NEW
#define ASN1_F_X509_NAME_EX_NEW 171
Definition at line 981 of file asn1.h.
ASN1_F_X509_PKEY_NEW
#define ASN1_F_X509_PKEY_NEW 173
Definition at line 982 of file asn1.h.
ASN1_i2d_bio_of
#define ASN1_i2d_bio_of (type, i2d, out, x)
Value:
(ASN1_i2d_bio(CHECKED_I2D_OF(type, i2d), \
                  out, \
                  CHECKED_PTR_OF(type, x)))
Definition at line 740 of file asn1.h.
Referenced by i2d_DSA_PUBKEY_bio(), i2d_EC_PUBKEY_bio(), i2d_ECPrivateKey_bio(), i2d_PKCS8_bio(), i2d_PKCS8_PRIV_KEY_INFO_bio(), i2d_PrivateKey_bio(), i2d_PUBKEY_bio(), and i2d_RSA_PUBKEY_bio().
ASN1_i2d_bio_of_const
#define ASN1_i2d_bio_of_const (type, i2d, out, x)
Value:
(ASN1_i2d_bio(CHECKED_I2D_OF(const type, i2d), \
                  out, \
                  CHECKED_PTR_OF(const type, x)))
Definition at line 745 of file asn1.h.
Referenced by i2d_DSAPrivateKey_bio().
ASN1_i2d_fp_of
#define ASN1_i2d_fp_of (type, i2d, out, x)
Value:
(ASN1_i2d_fp(CHECKED_I2D_OF(type, i2d), \
                 out, \
                 CHECKED_PTR_OF(type, x)))
Definition at line 713 of file asn1.h.
Referenced by i2d_DSA_PUBKEY_fp(), i2d_EC_PUBKEY_fp(), i2d_ECPrivateKey_fp(), i2d_PKCS8_fp(), i2d_PKCS8_PRIV_KEY_INFO_fp(), i2d_PrivateKey_fp(), and i2d_PUBKEY_fp().
ASN1_i2d_fp_of_const
#define ASN1_i2d_fp_of_const (type, i2d, out, x)
Value:
(ASN1_i2d_fp(CHECKED_I2D_OF(const type, i2d), \
                 out, \
                 CHECKED_PTR_OF(const type, x)))
Definition at line 718 of file asn1.h.
Referenced by i2d_DSAPrivateKey_fp().
ASN1_ITEM_ptr
#define ASN1_ITEM_ptr (iptr) (iptr)
Definition at line 320 of file asn1.h.
Referenced by X509V3_EXT_d2i().
ASN1_ITEM_ref
#define ASN1_ITEM_ref (iptr) (&(iptr##_it))
Definition at line 323 of file asn1.h.
ASN1_ITEM_rptr
#define ASN1_ITEM_rptr (ref) (&(ref##_it))
Definition at line 325 of file asn1.h.
Referenced by cms_encode_Receipt(), CMS_get1_ReceiptRequest(), cms_Receipt_verify(), cms_RecipientInfo_pwri_crypt(), d2i_CMS_bio(), d2i_PKCS12_bio(), d2i_PKCS12_fp(), d2i_PKCS7_bio(), d2i_PKCS7_fp(), d2i_RSAPrivateKey_bio(), d2i_RSAPrivateKey_fp(), d2i_RSAPublicKey_bio(), d2i_RSAPublicKey_fp(), d2i_X509_bio(), d2i_X509_CRL_bio(), d2i_X509_CRL_fp(), d2i_X509_fp(), d2i_X509_REQ_bio(), d2i_X509_REQ_fp(), i2d_CMS_bio(), i2d_PKCS12_bio(), i2d_PKCS12_fp(), i2d_PKCS7_bio(), i2d_PKCS7_fp(), i2d_RSAPrivateKey_bio(), i2d_RSAPrivateKey_fp(), i2d_RSAPublicKey_bio(), i2d_RSAPublicKey_fp(), i2d_X509_bio(), i2d_X509_CRL_bio(), i2d_X509_CRL_fp(), i2d_X509_fp(), i2d_X509_REQ_bio(), i2d_X509_REQ_fp(), NETSCAPE_SPKI_verify(), OCSP_REQ_CTX_set1_req(), OCSP_response_create(), OCSP_response_get1_basic(), OCSP_sendreq_nbio(), PKCS12_pack_authsafes(), PKCS12_pack_p7data(), PKCS12_pack_p7encdata(), PKCS12_SAFEBAG_create_cert(), PKCS12_SAFEBAG_create_crl(), PKCS12_SAFEBAG_get1_cert(), PKCS12_SAFEBAG_get1_crl(), PKCS7_add_attrib_smimecap(), PKCS7_signatureVerify(), PKCS8_decrypt(), PKCS8_set0_pbe(), SMIME_read_CMS(), SMIME_read_PKCS7(), SMIME_write_CMS(), SMIME_write_PKCS7(), STACK_OF(), X509_CRL_http_nbio(), X509_CRL_sign_ctx(), X509_http_nbio(), X509_REQ_add_extensions_nid(), X509_REQ_sign_ctx(), X509_REQ_verify(), X509_sign_ctx(), and X509_verify().
ASN1_LONG_UNDEF
#define ASN1_LONG_UNDEF 0x7fffffffL
Definition at line 170 of file asn1.h.
ASN1_PCTX_FLAGS_NO_ANY_TYPE
#define ASN1_PCTX_FLAGS_NO_ANY_TYPE 0x010
Definition at line 825 of file asn1.h.
ASN1_PCTX_FLAGS_NO_FIELD_NAME
#define ASN1_PCTX_FLAGS_NO_FIELD_NAME 0x040
Definition at line 829 of file asn1.h.
ASN1_PCTX_FLAGS_NO_MSTRING_TYPE
#define ASN1_PCTX_FLAGS_NO_MSTRING_TYPE 0x020
Definition at line 827 of file asn1.h.
ASN1_PCTX_FLAGS_NO_STRUCT_NAME
#define ASN1_PCTX_FLAGS_NO_STRUCT_NAME 0x100
Definition at line 833 of file asn1.h.
ASN1_PCTX_FLAGS_SHOW_ABSENT
#define ASN1_PCTX_FLAGS_SHOW_ABSENT 0x001
Definition at line 817 of file asn1.h.
ASN1_PCTX_FLAGS_SHOW_FIELD_STRUCT_NAME
#define ASN1_PCTX_FLAGS_SHOW_FIELD_STRUCT_NAME 0x080
Definition at line 831 of file asn1.h.
ASN1_PCTX_FLAGS_SHOW_SEQUENCE
#define ASN1_PCTX_FLAGS_SHOW_SEQUENCE 0x002
Definition at line 819 of file asn1.h.
ASN1_PCTX_FLAGS_SHOW_SSOF
#define ASN1_PCTX_FLAGS_SHOW_SSOF 0x004
Definition at line 821 of file asn1.h.
ASN1_PCTX_FLAGS_SHOW_TYPE
#define ASN1_PCTX_FLAGS_SHOW_TYPE 0x008
Definition at line 823 of file asn1.h.
ASN1_R_ADDING_OBJECT
#define ASN1_R_ADDING_OBJECT 171
Definition at line 985 of file asn1.h.
ASN1_R_ASN1_PARSE_ERROR
#define ASN1_R_ASN1_PARSE_ERROR 203
Definition at line 986 of file asn1.h.
ASN1_R_ASN1_SIG_PARSE_ERROR
#define ASN1_R_ASN1_SIG_PARSE_ERROR 204
Definition at line 987 of file asn1.h.
ASN1_R_AUX_ERROR
#define ASN1_R_AUX_ERROR 100
Definition at line 988 of file asn1.h.
ASN1_R_BAD_OBJECT_HEADER
#define ASN1_R_BAD_OBJECT_HEADER 102
Definition at line 989 of file asn1.h.
ASN1_R_BMPSTRING_IS_WRONG_LENGTH
#define ASN1_R_BMPSTRING_IS_WRONG_LENGTH 214
Definition at line 990 of file asn1.h.
ASN1_R_BN_LIB
#define ASN1_R_BN_LIB 105
Definition at line 991 of file asn1.h.
ASN1_R_BOOLEAN_IS_WRONG_LENGTH
#define ASN1_R_BOOLEAN_IS_WRONG_LENGTH 106
Definition at line 992 of file asn1.h.
ASN1_R_BUFFER_TOO_SMALL
#define ASN1_R_BUFFER_TOO_SMALL 107
Definition at line 993 of file asn1.h.
ASN1_R_CIPHER_HAS_NO_OBJECT_IDENTIFIER
#define ASN1_R_CIPHER_HAS_NO_OBJECT_IDENTIFIER 108
Definition at line 994 of file asn1.h.
ASN1_R_CONTEXT_NOT_INITIALISED
#define ASN1_R_CONTEXT_NOT_INITIALISED 217
Definition at line 995 of file asn1.h.
Referenced by ASN1_item_sign_ctx().
ASN1_R_DATA_IS_WRONG
#define ASN1_R_DATA_IS_WRONG 109
Definition at line 996 of file asn1.h.
ASN1_R_DECODE_ERROR
#define ASN1_R_DECODE_ERROR 110
Definition at line 997 of file asn1.h.
ASN1_R_DEPTH_EXCEEDED
#define ASN1_R_DEPTH_EXCEEDED 174
Definition at line 998 of file asn1.h.
ASN1_R_DIGEST_AND_KEY_TYPE_NOT_SUPPORTED
#define ASN1_R_DIGEST_AND_KEY_TYPE_NOT_SUPPORTED 198
Definition at line 999 of file asn1.h.
Referenced by ASN1_item_sign_ctx().
ASN1_R_ENCODE_ERROR
#define ASN1_R_ENCODE_ERROR 112
Definition at line 1000 of file asn1.h.
Referenced by ASN1_item_pack().
ASN1_R_ERROR_GETTING_TIME
#define ASN1_R_ERROR_GETTING_TIME 173
Definition at line 1001 of file asn1.h.
Referenced by ASN1_TIME_adj().
ASN1_R_ERROR_LOADING_SECTION
#define ASN1_R_ERROR_LOADING_SECTION 172
Definition at line 1002 of file asn1.h.
ASN1_R_ERROR_SETTING_CIPHER_PARAMS
#define ASN1_R_ERROR_SETTING_CIPHER_PARAMS 114
Definition at line 1003 of file asn1.h.
ASN1_R_EXPECTING_AN_INTEGER
#define ASN1_R_EXPECTING_AN_INTEGER 115
Definition at line 1004 of file asn1.h.
ASN1_R_EXPECTING_AN_OBJECT
#define ASN1_R_EXPECTING_AN_OBJECT 116
Definition at line 1005 of file asn1.h.
ASN1_R_EXPLICIT_LENGTH_MISMATCH
#define ASN1_R_EXPLICIT_LENGTH_MISMATCH 119
Definition at line 1006 of file asn1.h.
ASN1_R_EXPLICIT_TAG_NOT_CONSTRUCTED
#define ASN1_R_EXPLICIT_TAG_NOT_CONSTRUCTED 120
Definition at line 1007 of file asn1.h.
ASN1_R_FIELD_MISSING
#define ASN1_R_FIELD_MISSING 121
Definition at line 1008 of file asn1.h.
ASN1_R_FIRST_NUM_TOO_LARGE
#define ASN1_R_FIRST_NUM_TOO_LARGE 122
Definition at line 1009 of file asn1.h.
ASN1_R_HEADER_TOO_LONG
#define ASN1_R_HEADER_TOO_LONG 123
Definition at line 1010 of file asn1.h.
ASN1_R_ILLEGAL_BITSTRING_FORMAT
#define ASN1_R_ILLEGAL_BITSTRING_FORMAT 175
Definition at line 1011 of file asn1.h.
ASN1_R_ILLEGAL_BOOLEAN
#define ASN1_R_ILLEGAL_BOOLEAN 176
Definition at line 1012 of file asn1.h.
ASN1_R_ILLEGAL_CHARACTERS
#define ASN1_R_ILLEGAL_CHARACTERS 124
Definition at line 1013 of file asn1.h.
ASN1_R_ILLEGAL_FORMAT
#define ASN1_R_ILLEGAL_FORMAT 177
Definition at line 1014 of file asn1.h.
ASN1_R_ILLEGAL_HEX
#define ASN1_R_ILLEGAL_HEX 178
Definition at line 1015 of file asn1.h.
ASN1_R_ILLEGAL_IMPLICIT_TAG
#define ASN1_R_ILLEGAL_IMPLICIT_TAG 179
Definition at line 1016 of file asn1.h.
ASN1_R_ILLEGAL_INTEGER
#define ASN1_R_ILLEGAL_INTEGER 180
Definition at line 1017 of file asn1.h.
ASN1_R_ILLEGAL_NEGATIVE_VALUE
#define ASN1_R_ILLEGAL_NEGATIVE_VALUE 226
Definition at line 1018 of file asn1.h.
ASN1_R_ILLEGAL_NESTED_TAGGING
#define ASN1_R_ILLEGAL_NESTED_TAGGING 181
Definition at line 1019 of file asn1.h.
ASN1_R_ILLEGAL_NULL
#define ASN1_R_ILLEGAL_NULL 125
Definition at line 1020 of file asn1.h.
ASN1_R_ILLEGAL_NULL_VALUE
#define ASN1_R_ILLEGAL_NULL_VALUE 182
Definition at line 1021 of file asn1.h.
ASN1_R_ILLEGAL_OBJECT
#define ASN1_R_ILLEGAL_OBJECT 183
Definition at line 1022 of file asn1.h.
ASN1_R_ILLEGAL_OPTIONAL_ANY
#define ASN1_R_ILLEGAL_OPTIONAL_ANY 126
Definition at line 1023 of file asn1.h.
ASN1_R_ILLEGAL_OPTIONS_ON_ITEM_TEMPLATE
#define ASN1_R_ILLEGAL_OPTIONS_ON_ITEM_TEMPLATE 170
Definition at line 1024 of file asn1.h.
ASN1_R_ILLEGAL_PADDING
#define ASN1_R_ILLEGAL_PADDING 221
Definition at line 1025 of file asn1.h.
ASN1_R_ILLEGAL_TAGGED_ANY
#define ASN1_R_ILLEGAL_TAGGED_ANY 127
Definition at line 1026 of file asn1.h.
ASN1_R_ILLEGAL_TIME_VALUE
#define ASN1_R_ILLEGAL_TIME_VALUE 184
Definition at line 1027 of file asn1.h.
ASN1_R_ILLEGAL_ZERO_CONTENT
#define ASN1_R_ILLEGAL_ZERO_CONTENT 222
Definition at line 1028 of file asn1.h.
ASN1_R_INTEGER_NOT_ASCII_FORMAT
#define ASN1_R_INTEGER_NOT_ASCII_FORMAT 185
Definition at line 1029 of file asn1.h.
ASN1_R_INTEGER_TOO_LARGE_FOR_LONG
#define ASN1_R_INTEGER_TOO_LARGE_FOR_LONG 128
Definition at line 1030 of file asn1.h.
ASN1_R_INVALID_BIT_STRING_BITS_LEFT
#define ASN1_R_INVALID_BIT_STRING_BITS_LEFT 220
Definition at line 1031 of file asn1.h.
ASN1_R_INVALID_BMPSTRING_LENGTH
#define ASN1_R_INVALID_BMPSTRING_LENGTH 129
Definition at line 1032 of file asn1.h.
ASN1_R_INVALID_DIGIT
#define ASN1_R_INVALID_DIGIT 130
Definition at line 1033 of file asn1.h.
ASN1_R_INVALID_MIME_TYPE
#define ASN1_R_INVALID_MIME_TYPE 205
Definition at line 1034 of file asn1.h.
ASN1_R_INVALID_MODIFIER
#define ASN1_R_INVALID_MODIFIER 186
Definition at line 1035 of file asn1.h.
ASN1_R_INVALID_NUMBER
#define ASN1_R_INVALID_NUMBER 187
Definition at line 1036 of file asn1.h.
ASN1_R_INVALID_OBJECT_ENCODING
#define ASN1_R_INVALID_OBJECT_ENCODING 216
Definition at line 1037 of file asn1.h.
ASN1_R_INVALID_SCRYPT_PARAMETERS
#define ASN1_R_INVALID_SCRYPT_PARAMETERS 227
Definition at line 1038 of file asn1.h.
ASN1_R_INVALID_SEPARATOR
#define ASN1_R_INVALID_SEPARATOR 131
Definition at line 1039 of file asn1.h.
ASN1_R_INVALID_STRING_TABLE_VALUE
#define ASN1_R_INVALID_STRING_TABLE_VALUE 218
Definition at line 1040 of file asn1.h.
ASN1_R_INVALID_UNIVERSALSTRING_LENGTH
#define ASN1_R_INVALID_UNIVERSALSTRING_LENGTH 133
Definition at line 1041 of file asn1.h.
ASN1_R_INVALID_UTF8STRING
#define ASN1_R_INVALID_UTF8STRING 134
Definition at line 1042 of file asn1.h.
ASN1_R_INVALID_VALUE
#define ASN1_R_INVALID_VALUE 219
Definition at line 1043 of file asn1.h.
ASN1_R_LIST_ERROR
#define ASN1_R_LIST_ERROR 188
Definition at line 1044 of file asn1.h.
ASN1_R_MIME_NO_CONTENT_TYPE
#define ASN1_R_MIME_NO_CONTENT_TYPE 206
Definition at line 1045 of file asn1.h.
ASN1_R_MIME_PARSE_ERROR
#define ASN1_R_MIME_PARSE_ERROR 207
Definition at line 1046 of file asn1.h.
ASN1_R_MIME_SIG_PARSE_ERROR
#define ASN1_R_MIME_SIG_PARSE_ERROR 208
Definition at line 1047 of file asn1.h.
ASN1_R_MISSING_EOC
#define ASN1_R_MISSING_EOC 137
Definition at line 1048 of file asn1.h.
ASN1_R_MISSING_SECOND_NUMBER
#define ASN1_R_MISSING_SECOND_NUMBER 138
Definition at line 1049 of file asn1.h.
ASN1_R_MISSING_VALUE
#define ASN1_R_MISSING_VALUE 189
Definition at line 1050 of file asn1.h.
ASN1_R_MSTRING_NOT_UNIVERSAL
#define ASN1_R_MSTRING_NOT_UNIVERSAL 139
Definition at line 1051 of file asn1.h.
ASN1_R_MSTRING_WRONG_TAG
#define ASN1_R_MSTRING_WRONG_TAG 140
Definition at line 1052 of file asn1.h.
ASN1_R_NESTED_ASN1_STRING
#define ASN1_R_NESTED_ASN1_STRING 197
Definition at line 1053 of file asn1.h.
ASN1_R_NO_CONTENT_TYPE
#define ASN1_R_NO_CONTENT_TYPE 209
Definition at line 1057 of file asn1.h.
ASN1_R_NO_MATCHING_CHOICE_TYPE
#define ASN1_R_NO_MATCHING_CHOICE_TYPE 143
Definition at line 1058 of file asn1.h.
ASN1_R_NO_MULTIPART_BODY_FAILURE
#define ASN1_R_NO_MULTIPART_BODY_FAILURE 210
Definition at line 1059 of file asn1.h.
ASN1_R_NO_MULTIPART_BOUNDARY
#define ASN1_R_NO_MULTIPART_BOUNDARY 211
Definition at line 1060 of file asn1.h.
ASN1_R_NO_SIG_CONTENT_TYPE
#define ASN1_R_NO_SIG_CONTENT_TYPE 212
Definition at line 1061 of file asn1.h.
ASN1_R_NON_HEX_CHARACTERS
#define ASN1_R_NON_HEX_CHARACTERS 141
Definition at line 1054 of file asn1.h.
ASN1_R_NOT_ASCII_FORMAT
#define ASN1_R_NOT_ASCII_FORMAT 190
Definition at line 1055 of file asn1.h.
ASN1_R_NOT_ENOUGH_DATA
#define ASN1_R_NOT_ENOUGH_DATA 142
Definition at line 1056 of file asn1.h.
ASN1_R_NULL_IS_WRONG_LENGTH
#define ASN1_R_NULL_IS_WRONG_LENGTH 144
Definition at line 1062 of file asn1.h.
ASN1_R_OBJECT_NOT_ASCII_FORMAT
#define ASN1_R_OBJECT_NOT_ASCII_FORMAT 191
Definition at line 1063 of file asn1.h.
ASN1_R_ODD_NUMBER_OF_CHARS
#define ASN1_R_ODD_NUMBER_OF_CHARS 145
Definition at line 1064 of file asn1.h.
ASN1_R_SECOND_NUMBER_TOO_LARGE
#define ASN1_R_SECOND_NUMBER_TOO_LARGE 147
Definition at line 1065 of file asn1.h.
ASN1_R_SEQUENCE_LENGTH_MISMATCH
#define ASN1_R_SEQUENCE_LENGTH_MISMATCH 148
Definition at line 1066 of file asn1.h.
ASN1_R_SEQUENCE_NOT_CONSTRUCTED
#define ASN1_R_SEQUENCE_NOT_CONSTRUCTED 149
Definition at line 1067 of file asn1.h.
ASN1_R_SEQUENCE_OR_SET_NEEDS_CONFIG
#define ASN1_R_SEQUENCE_OR_SET_NEEDS_CONFIG 192
Definition at line 1068 of file asn1.h.
ASN1_R_SHORT_LINE
#define ASN1_R_SHORT_LINE 150
Definition at line 1069 of file asn1.h.
ASN1_R_SIG_INVALID_MIME_TYPE
#define ASN1_R_SIG_INVALID_MIME_TYPE 213
Definition at line 1070 of file asn1.h.
ASN1_R_STREAMING_NOT_SUPPORTED
#define ASN1_R_STREAMING_NOT_SUPPORTED 202
Definition at line 1071 of file asn1.h.
ASN1_R_STRING_TOO_LONG
#define ASN1_R_STRING_TOO_LONG 151
Definition at line 1072 of file asn1.h.
ASN1_R_STRING_TOO_SHORT
#define ASN1_R_STRING_TOO_SHORT 152
Definition at line 1073 of file asn1.h.
ASN1_R_THE_ASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD
#define ASN1_R_THE_ASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD 154
Definition at line 1074 of file asn1.h.
Referenced by ASN1_sign().
ASN1_R_TIME_NOT_ASCII_FORMAT
#define ASN1_R_TIME_NOT_ASCII_FORMAT 193
Definition at line 1075 of file asn1.h.
ASN1_R_TOO_LARGE
#define ASN1_R_TOO_LARGE 223
Definition at line 1076 of file asn1.h.
ASN1_R_TOO_LONG
#define ASN1_R_TOO_LONG 155
Definition at line 1077 of file asn1.h.
ASN1_R_TOO_SMALL
#define ASN1_R_TOO_SMALL 224
Definition at line 1078 of file asn1.h.
ASN1_R_TYPE_NOT_CONSTRUCTED
#define ASN1_R_TYPE_NOT_CONSTRUCTED 156
Definition at line 1079 of file asn1.h.
ASN1_R_TYPE_NOT_PRIMITIVE
#define ASN1_R_TYPE_NOT_PRIMITIVE 195
Definition at line 1080 of file asn1.h.
ASN1_R_UNEXPECTED_EOC
#define ASN1_R_UNEXPECTED_EOC 159
Definition at line 1081 of file asn1.h.
ASN1_R_UNIVERSALSTRING_IS_WRONG_LENGTH
#define ASN1_R_UNIVERSALSTRING_IS_WRONG_LENGTH 215
Definition at line 1082 of file asn1.h.
ASN1_R_UNKNOWN_FORMAT
#define ASN1_R_UNKNOWN_FORMAT 160
Definition at line 1083 of file asn1.h.
ASN1_R_UNKNOWN_MESSAGE_DIGEST_ALGORITHM
#define ASN1_R_UNKNOWN_MESSAGE_DIGEST_ALGORITHM 161
Definition at line 1084 of file asn1.h.
ASN1_R_UNKNOWN_OBJECT_TYPE
#define ASN1_R_UNKNOWN_OBJECT_TYPE 162
Definition at line 1085 of file asn1.h.
Referenced by ASN1_sign().
ASN1_R_UNKNOWN_PUBLIC_KEY_TYPE
#define ASN1_R_UNKNOWN_PUBLIC_KEY_TYPE 163
Definition at line 1086 of file asn1.h.
ASN1_R_UNKNOWN_SIGNATURE_ALGORITHM
#define ASN1_R_UNKNOWN_SIGNATURE_ALGORITHM 199
Definition at line 1087 of file asn1.h.
ASN1_R_UNKNOWN_TAG
#define ASN1_R_UNKNOWN_TAG 194
Definition at line 1088 of file asn1.h.
ASN1_R_UNSUPPORTED_ANY_DEFINED_BY_TYPE
#define ASN1_R_UNSUPPORTED_ANY_DEFINED_BY_TYPE 164
Definition at line 1089 of file asn1.h.
Referenced by asn1_do_adb().
ASN1_R_UNSUPPORTED_PUBLIC_KEY_TYPE
#define ASN1_R_UNSUPPORTED_PUBLIC_KEY_TYPE 167
Definition at line 1090 of file asn1.h.
Referenced by i2d_PublicKey().
ASN1_R_UNSUPPORTED_TYPE
#define ASN1_R_UNSUPPORTED_TYPE 196
Definition at line 1091 of file asn1.h.
ASN1_R_WRONG_INTEGER_TYPE
#define ASN1_R_WRONG_INTEGER_TYPE 225
Definition at line 1092 of file asn1.h.
ASN1_R_WRONG_PUBLIC_KEY_TYPE
#define ASN1_R_WRONG_PUBLIC_KEY_TYPE 200
Definition at line 1093 of file asn1.h.
ASN1_R_WRONG_TAG
#define ASN1_R_WRONG_TAG 168
Definition at line 1094 of file asn1.h.
ASN1_STRFLGS_DUMP_ALL
#define ASN1_STRFLGS_DUMP_ALL 0x80
Definition at line 410 of file asn1.h.
ASN1_STRFLGS_DUMP_DER
#define ASN1_STRFLGS_DUMP_DER 0x200
Definition at line 418 of file asn1.h.
ASN1_STRFLGS_DUMP_UNKNOWN
#define ASN1_STRFLGS_DUMP_UNKNOWN 0x100
Definition at line 411 of file asn1.h.
ASN1_STRFLGS_ESC_2253
#define ASN1_STRFLGS_ESC_2253 1
Definition at line 360 of file asn1.h.
ASN1_STRFLGS_ESC_2254
#define ASN1_STRFLGS_ESC_2254 0x400
Definition at line 423 of file asn1.h.
ASN1_STRFLGS_ESC_CTRL
#define ASN1_STRFLGS_ESC_CTRL 2
Definition at line 361 of file asn1.h.
ASN1_STRFLGS_ESC_MSB
#define ASN1_STRFLGS_ESC_MSB 4
Definition at line 362 of file asn1.h.
ASN1_STRFLGS_ESC_QUOTE
#define ASN1_STRFLGS_ESC_QUOTE 8
Definition at line 369 of file asn1.h.
ASN1_STRFLGS_IGNORE_TYPE
#define ASN1_STRFLGS_IGNORE_TYPE 0x20
Definition at line 397 of file asn1.h.
ASN1_STRFLGS_RFC2253
#define ASN1_STRFLGS_RFC2253
Value:
(ASN1_STRFLGS_ESC_2253 | \
                                ASN1_STRFLGS_ESC_CTRL | \
                                ASN1_STRFLGS_ESC_MSB | \
                                ASN1_STRFLGS_UTF8_CONVERT | \
                                ASN1_STRFLGS_DUMP_UNKNOWN | \
                                ASN1_STRFLGS_DUMP_DER)
Definition at line 430 of file asn1.h.
ASN1_STRFLGS_SHOW_TYPE
#define ASN1_STRFLGS_SHOW_TYPE 0x40
Definition at line 400 of file asn1.h.
ASN1_STRFLGS_UTF8_CONVERT
#define ASN1_STRFLGS_UTF8_CONVERT 0x10
Definition at line 389 of file asn1.h.
ASN1_STRING_FLAG_BITS_LEFT
#define ASN1_STRING_FLAG_BITS_LEFT 0x08/* Set if 0x07 has bits left value */
Definition at line 122 of file asn1.h.
Referenced by ASN1_item_sign_ctx(), ASN1_sign(), and i2d_DHxparams().
ASN1_STRING_FLAG_CONT
#define ASN1_STRING_FLAG_CONT 0x020
Definition at line 136 of file asn1.h.
Referenced by cms_content_bio(), CMS_dataFinal(), CMS_set_detached(), and CMS_stream().
ASN1_STRING_FLAG_EMBED
#define ASN1_STRING_FLAG_EMBED 0x080
Definition at line 143 of file asn1.h.
Referenced by ASN1_STRING_copy(), and ASN1_STRING_free().
ASN1_STRING_FLAG_MSTRING
#define ASN1_STRING_FLAG_MSTRING 0x040
Definition at line 141 of file asn1.h.
Referenced by X509_time_adj_ex().
ASN1_STRING_FLAG_NDEF
#define ASN1_STRING_FLAG_NDEF 0x010
Definition at line 128 of file asn1.h.
Referenced by ASN1_STRING_clear_free(), asn1_string_embed_free(), CMS_stream(), and PKCS7_stream().
B_ASN1_BIT_STRING
#define B_ASN1_BIT_STRING 0x0400
Definition at line 103 of file asn1.h.
B_ASN1_BMPSTRING
#define B_ASN1_BMPSTRING 0x0800
Definition at line 104 of file asn1.h.
Referenced by ASN1_STRING_set_default_mask_asc().
B_ASN1_DIRECTORYSTRING
#define B_ASN1_DIRECTORYSTRING
Value:
B_ASN1_PRINTABLESTRING| \
                        B_ASN1_TELETEXSTRING|\
                        B_ASN1_BMPSTRING|\
                        B_ASN1_UNIVERSALSTRING|\
                        B_ASN1_UTF8STRING
Definition at line 504 of file asn1.h.
B_ASN1_DISPLAYTEXT
#define B_ASN1_DISPLAYTEXT
Value:
B_ASN1_IA5STRING| \
                        B_ASN1_VISIBLESTRING| \
                        B_ASN1_BMPSTRING|\
                        B_ASN1_UTF8STRING
Definition at line 511 of file asn1.h.
B_ASN1_GENERALIZEDTIME
#define B_ASN1_GENERALIZEDTIME 0x8000
Definition at line 108 of file asn1.h.
B_ASN1_GENERALSTRING
#define B_ASN1_GENERALSTRING 0x0080
Definition at line 100 of file asn1.h.
B_ASN1_GRAPHICSTRING
#define B_ASN1_GRAPHICSTRING 0x0020
Definition at line 97 of file asn1.h.
B_ASN1_IA5STRING
#define B_ASN1_IA5STRING 0x0010
Definition at line 96 of file asn1.h.
B_ASN1_ISO64STRING
#define B_ASN1_ISO64STRING 0x0040
Definition at line 98 of file asn1.h.
B_ASN1_NUMERICSTRING
#define B_ASN1_NUMERICSTRING 0x0001
Definition at line 91 of file asn1.h.
B_ASN1_OCTET_STRING
#define B_ASN1_OCTET_STRING 0x0200
Definition at line 102 of file asn1.h.
B_ASN1_PRINTABLE
#define B_ASN1_PRINTABLE
Value:
B_ASN1_NUMERICSTRING| \
                        B_ASN1_PRINTABLESTRING| \
                        B_ASN1_T61STRING| \
                        B_ASN1_IA5STRING| \
                        B_ASN1_BIT_STRING| \
                        B_ASN1_UNIVERSALSTRING|\
                        B_ASN1_BMPSTRING|\
                        B_ASN1_UTF8STRING|\
                        B_ASN1_SEQUENCE|\
                        B_ASN1_UNKNOWN
Definition at line 492 of file asn1.h.
B_ASN1_PRINTABLESTRING
#define B_ASN1_PRINTABLESTRING 0x0002
Definition at line 92 of file asn1.h.
B_ASN1_SEQUENCE
#define B_ASN1_SEQUENCE 0x10000
Definition at line 109 of file asn1.h.
B_ASN1_T61STRING
#define B_ASN1_T61STRING 0x0004
Definition at line 93 of file asn1.h.
Referenced by ASN1_STRING_set_default_mask_asc().
B_ASN1_TELETEXSTRING
#define B_ASN1_TELETEXSTRING 0x0004
Definition at line 94 of file asn1.h.
B_ASN1_TIME
#define B_ASN1_TIME
Value:
B_ASN1_UTCTIME | \
                        B_ASN1_GENERALIZEDTIME
Definition at line 488 of file asn1.h.
B_ASN1_UNIVERSALSTRING
#define B_ASN1_UNIVERSALSTRING 0x0100
Definition at line 101 of file asn1.h.
B_ASN1_UNKNOWN
#define B_ASN1_UNKNOWN 0x1000
Definition at line 105 of file asn1.h.
B_ASN1_UTCTIME
#define B_ASN1_UTCTIME 0x4000
Definition at line 107 of file asn1.h.
B_ASN1_UTF8STRING
#define B_ASN1_UTF8STRING 0x2000
Definition at line 106 of file asn1.h.
Referenced by ASN1_STRING_set_default_mask_asc().
B_ASN1_VIDEOTEXSTRING
#define B_ASN1_VIDEOTEXSTRING 0x0008
Definition at line 95 of file asn1.h.
B_ASN1_VISIBLESTRING
#define B_ASN1_VISIBLESTRING 0x0040
Definition at line 99 of file asn1.h.
CHARTYPE_FIRST_ESC_2253
#define CHARTYPE_FIRST_ESC_2253 0x20
Definition at line 376 of file asn1.h.
CHARTYPE_LAST_ESC_2253
#define CHARTYPE_LAST_ESC_2253 0x40
Definition at line 378 of file asn1.h.
CHARTYPE_PRINTABLESTRING
#define CHARTYPE_PRINTABLESTRING 0x10
Definition at line 374 of file asn1.h.
CHECKED_D2I_OF
#define CHECKED_D2I_OF (type, d2i) ((d2i_of_void*) (1 ? d2i : ((D2I_OF(type))0)))
Definition at line 261 of file asn1.h.
CHECKED_I2D_OF
#define CHECKED_I2D_OF (type, i2d) ((i2d_of_void*) (1 ? i2d : ((I2D_OF(type))0)))
Definition at line 263 of file asn1.h.
CHECKED_NEW_OF
#define CHECKED_NEW_OF (type, xnew) ((void *(*)(void)) (1 ? xnew : ((type *(*)(void))0)))
Definition at line 265 of file asn1.h.
CHECKED_PPTR_OF
#define CHECKED_PPTR_OF (type, p) ((void**) (1 ? p : (type**)0))
Definition at line 269 of file asn1.h.
CHECKED_PTR_OF
#define CHECKED_PTR_OF (type, p) ((void*) (1 ? p : (type*)0))
Definition at line 267 of file asn1.h.
D2I_OF
#define D2I_OF (type) type *(*)(type **,const unsigned char **,long)
Definition at line 257 of file asn1.h.
Referenced by d2i_RSA_PUBKEY_fp().
DECLARE_ASN1_ALLOC_FUNCTIONS
#define DECLARE_ASN1_ALLOC_FUNCTIONS (type) DECLARE_ASN1_ALLOC_FUNCTIONS_name(type, type)
Definition at line 218 of file asn1.h.
DECLARE_ASN1_ALLOC_FUNCTIONS_name
#define DECLARE_ASN1_ALLOC_FUNCTIONS_name (type, name)
Value:
type *name##_new(void); \
        void name##_free(type *a);
Definition at line 246 of file asn1.h.
DECLARE_ASN1_ENCODE_FUNCTIONS
#define DECLARE_ASN1_ENCODE_FUNCTIONS (type, itname, name)
Value:
type *d2i_##name(type **a, const unsigned char **in, long len); \
        int i2d_##name(type *a, unsigned char **out); \
        DECLARE_ASN1_ITEM(itname)
Definition at line 229 of file asn1.h.
DECLARE_ASN1_ENCODE_FUNCTIONS_const
#define DECLARE_ASN1_ENCODE_FUNCTIONS_const (type, name)
Value:
type *d2i_##name(type **a, const unsigned char **in, long len); \
        int i2d_##name(const type *a, unsigned char **out); \
        DECLARE_ASN1_ITEM(name)
Definition at line 234 of file asn1.h.
DECLARE_ASN1_FUNCTIONS
#define DECLARE_ASN1_FUNCTIONS (type) DECLARE_ASN1_FUNCTIONS_name(type, type)
Definition at line 216 of file asn1.h.
DECLARE_ASN1_FUNCTIONS_const
#define DECLARE_ASN1_FUNCTIONS_const (name)
Value:
DECLARE_ASN1_ALLOC_FUNCTIONS(name) \
        DECLARE_ASN1_ENCODE_FUNCTIONS_const(name, name)
Definition at line 242 of file asn1.h.
DECLARE_ASN1_FUNCTIONS_fname
#define DECLARE_ASN1_FUNCTIONS_fname (type, itname, name)
Value:
DECLARE_ASN1_ALLOC_FUNCTIONS_name(type, name) \
        DECLARE_ASN1_ENCODE_FUNCTIONS(type, itname, name)
Definition at line 225 of file asn1.h.
DECLARE_ASN1_FUNCTIONS_name
#define DECLARE_ASN1_FUNCTIONS_name (type, name)
Value:
DECLARE_ASN1_ALLOC_FUNCTIONS_name(type, name) \
        DECLARE_ASN1_ENCODE_FUNCTIONS(type, name, name)
Definition at line 221 of file asn1.h.
DECLARE_ASN1_ITEM
#define DECLARE_ASN1_ITEM (name) OPENSSL_EXTERN const ASN1_ITEM name##_it;
Definition at line 327 of file asn1.h.
DECLARE_ASN1_NDEF_FUNCTION
#define DECLARE_ASN1_NDEF_FUNCTION (name) int i2d_##name##_NDEF(name *a, unsigned char **out);
Definition at line 239 of file asn1.h.
DECLARE_ASN1_PRINT_FUNCTION
#define DECLARE_ASN1_PRINT_FUNCTION (stname) DECLARE_ASN1_PRINT_FUNCTION_fname(stname, stname)
Definition at line 250 of file asn1.h.
DECLARE_ASN1_PRINT_FUNCTION_fname
#define DECLARE_ASN1_PRINT_FUNCTION_fname (stname, fname)
Value:
int fname##_print_ctx(BIO *out, stname *x, int indent, \
                                         const ASN1_PCTX *pctx);
Definition at line 253 of file asn1.h.
DIRSTRING_TYPE
#define DIRSTRING_TYPE (B_ASN1_PRINTABLESTRING|B_ASN1_T61STRING|B_ASN1_BMPSTRING|B_ASN1_UTF8STRING)
Definition at line 181 of file asn1.h.
I2D_OF
#define I2D_OF (type) int (*)(type *,unsigned char **)
Definition at line 258 of file asn1.h.
Referenced by i2d_RSA_PUBKEY_fp().
I2D_OF_const
#define I2D_OF_const (type) int (*)(const type *,unsigned char **)
Definition at line 259 of file asn1.h.
M_ASN1_free_of
#define M_ASN1_free_of (x, type) ASN1_item_free(CHECKED_PTR_OF(type, x), ASN1_ITEM_rptr(type))
Definition at line 698 of file asn1.h.
Referenced by CMS_add0_CertificateChoices(), CMS_add0_RevocationInfoChoice(), and cms_RecipientInfo_kari_init().
M_ASN1_new_of
#define M_ASN1_new_of (type) (type *)ASN1_item_new(ASN1_ITEM_rptr(type))
Definition at line 697 of file asn1.h.
Referenced by CMS_add0_CertificateChoices(), CMS_add0_RevocationInfoChoice(), CMS_add1_recipient_cert(), CMS_EncryptedData_set1_key(), and cms_RecipientInfo_kari_init().
MBSTRING_ASC
#define MBSTRING_ASC (MBSTRING_FLAG|1)
Definition at line 113 of file asn1.h.
Referenced by PKCS12_add_CSPName_asc(), and PKCS12_add_friendlyname_asc().
MBSTRING_BMP
#define MBSTRING_BMP (MBSTRING_FLAG|2)
Definition at line 114 of file asn1.h.
Referenced by PKCS12_add_friendlyname_uni().
MBSTRING_FLAG
#define MBSTRING_FLAG 0x1000
Definition at line 111 of file asn1.h.
Referenced by X509_ATTRIBUTE_set1_data(), and X509_NAME_ENTRY_set_data().
MBSTRING_UNIV
#define MBSTRING_UNIV (MBSTRING_FLAG|4)
Definition at line 115 of file asn1.h.
MBSTRING_UTF8
#define MBSTRING_UTF8 (MBSTRING_FLAG)
Definition at line 112 of file asn1.h.
Referenced by PKCS12_add_friendlyname_utf8().
PKCS9STRING_TYPE
#define PKCS9STRING_TYPE (DIRSTRING_TYPE|B_ASN1_IA5STRING)
Definition at line 183 of file asn1.h.
SMIME_CRLFEOL
#define SMIME_CRLFEOL 0x800
Definition at line 117 of file asn1.h.
SMIME_OLDMIME
#define SMIME_OLDMIME 0x400
Definition at line 116 of file asn1.h.
Referenced by SMIME_write_PKCS7().
SMIME_STREAM
#define SMIME_STREAM 0x1000
Definition at line 118 of file asn1.h.
STABLE_FLAGS_CLEAR
#define STABLE_FLAGS_CLEAR STABLE_FLAGS_MALLOC
Definition at line 179 of file asn1.h.
STABLE_FLAGS_MALLOC
#define STABLE_FLAGS_MALLOC 0x01
Definition at line 172 of file asn1.h.
STABLE_NO_MASK
#define STABLE_NO_MASK 0x02
Definition at line 180 of file asn1.h.
TYPEDEF_D2I2D_OF
#define TYPEDEF_D2I2D_OF (type) TYPEDEF_D2I_OF(type); TYPEDEF_I2D_OF(type)
Definition at line 274 of file asn1.h.
TYPEDEF_D2I_OF
#define TYPEDEF_D2I_OF (type) typedef type *d2i_of_##type(type **,const unsigned char **,long)
Definition at line 272 of file asn1.h.
TYPEDEF_I2D_OF
#define TYPEDEF_I2D_OF (type) typedef int i2d_of_##type(type *,unsigned char **)
Definition at line 273 of file asn1.h.
ub_common_name
#define ub_common_name 64
Definition at line 198 of file asn1.h.
ub_email_address
#define ub_email_address 128
Definition at line 204 of file asn1.h.
ub_locality_name
#define ub_locality_name 128
Definition at line 199 of file asn1.h.
ub_name
#define ub_name 32768
Definition at line 197 of file asn1.h.
ub_organization_name
#define ub_organization_name 64
Definition at line 201 of file asn1.h.
ub_organization_unit_name
#define ub_organization_unit_name 64
Definition at line 202 of file asn1.h.
ub_state_name
#define ub_state_name 128
Definition at line 200 of file asn1.h.
ub_title
#define ub_title 64
Definition at line 203 of file asn1.h.
V_ASN1_ANY
#define V_ASN1_ANY -4/* used in ASN1 template code */
Definition at line 47 of file asn1.h.
Referenced by asn1_primitive_free().
V_ASN1_APP_CHOOSE
#define V_ASN1_APP_CHOOSE -2/* let the recipient choose */
Definition at line 45 of file asn1.h.
Referenced by X509_NAME_ENTRY_set_data().
V_ASN1_APPLICATION
#define V_ASN1_APPLICATION 0x40
Definition at line 37 of file asn1.h.
V_ASN1_BIT_STRING
#define V_ASN1_BIT_STRING 3
Definition at line 54 of file asn1.h.
Referenced by ASN1_TYPE_cmp(), PKCS8_add_keyusage(), and print_attribs().
V_ASN1_BMPSTRING
#define V_ASN1_BMPSTRING 30
Definition at line 78 of file asn1.h.
Referenced by ASN1_TYPE_cmp(), PKCS12_get_friendlyname(), and print_attribs().
V_ASN1_BOOLEAN
#define V_ASN1_BOOLEAN 1
Definition at line 52 of file asn1.h.
Referenced by asn1_primitive_free(), ASN1_TYPE_cmp(), ASN1_TYPE_set(), and ASN1_TYPE_set1().
V_ASN1_CONSTRUCTED
#define V_ASN1_CONSTRUCTED 0x20
Definition at line 41 of file asn1.h.
Referenced by ASN1_put_object().
V_ASN1_CONTEXT_SPECIFIC
#define V_ASN1_CONTEXT_SPECIFIC 0x80
Definition at line 38 of file asn1.h.
V_ASN1_ENUMERATED
#define V_ASN1_ENUMERATED 10
Definition at line 61 of file asn1.h.
Referenced by ASN1_ENUMERATED_get(), and ASN1_TYPE_cmp().
V_ASN1_EOC
#define V_ASN1_EOC 0
Definition at line 51 of file asn1.h.
V_ASN1_EXTERNAL
#define V_ASN1_EXTERNAL 8
Definition at line 59 of file asn1.h.
V_ASN1_GENERALIZEDTIME
#define V_ASN1_GENERALIZEDTIME 24
Definition at line 72 of file asn1.h.
Referenced by ASN1_GENERALIZEDTIME_adj(), ASN1_GENERALIZEDTIME_set_string(), asn1_generalizedtime_to_tm(), ASN1_TIME_check(), ASN1_TIME_print(), ASN1_TIME_set_string(), ASN1_TYPE_cmp(), and X509_time_adj_ex().
V_ASN1_GENERALSTRING
#define V_ASN1_GENERALSTRING 27
Definition at line 76 of file asn1.h.
Referenced by ASN1_TYPE_cmp().
V_ASN1_GRAPHICSTRING
#define V_ASN1_GRAPHICSTRING 25
Definition at line 73 of file asn1.h.
Referenced by ASN1_TYPE_cmp().
V_ASN1_IA5STRING
#define V_ASN1_IA5STRING 22
Definition at line 70 of file asn1.h.
Referenced by ASN1_TYPE_cmp(), and X509_REQ_print_ex().
V_ASN1_INTEGER
#define V_ASN1_INTEGER 2
Definition at line 53 of file asn1.h.
Referenced by ASN1_TYPE_cmp(), and CMS_add_simple_smimecap().
V_ASN1_ISO64STRING
#define V_ASN1_ISO64STRING 26
Definition at line 74 of file asn1.h.
V_ASN1_NEG
#define V_ASN1_NEG 0x100
Definition at line 86 of file asn1.h.
Referenced by ASN1_ENUMERATED_get().
V_ASN1_NEG_ENUMERATED
#define V_ASN1_NEG_ENUMERATED (10 | V_ASN1_NEG)
Definition at line 88 of file asn1.h.
Referenced by ASN1_tag2str().
V_ASN1_NEG_INTEGER
#define V_ASN1_NEG_INTEGER (2 | V_ASN1_NEG)
Definition at line 87 of file asn1.h.
Referenced by ASN1_tag2str().
V_ASN1_NULL
#define V_ASN1_NULL 5
Definition at line 56 of file asn1.h.
Referenced by ASN1_item_sign_ctx(), asn1_primitive_free(), ASN1_sign(), ASN1_TYPE_cmp(), ASN1_TYPE_get(), PKCS12_setup_mac(), and PKCS7_add_signer().
V_ASN1_NUMERICSTRING
#define V_ASN1_NUMERICSTRING 18
Definition at line 65 of file asn1.h.
Referenced by ASN1_TYPE_cmp().
V_ASN1_OBJECT
#define V_ASN1_OBJECT 6
Definition at line 57 of file asn1.h.
Referenced by asn1_primitive_free(), ASN1_TYPE_cmp(), ASN1_TYPE_set1(), cms_encode_Receipt(), i2d_ASN1_OBJECT(), and PKCS7_add_attrib_content_type().
V_ASN1_OBJECT_DESCRIPTOR
#define V_ASN1_OBJECT_DESCRIPTOR 7
Definition at line 58 of file asn1.h.
V_ASN1_OCTET_STRING
#define V_ASN1_OCTET_STRING 4
Definition at line 55 of file asn1.h.
Referenced by ASN1_STRING_new(), ASN1_TYPE_cmp(), ASN1_TYPE_set_octetstring(), CMS_get0_content(), cms_Receipt_verify(), CMS_RecipientInfo_kekri_id_cmp(), CMS_SignerInfo_verify_content(), PKCS12_add_localkeyid(), and print_attribs().
V_ASN1_OTHER
#define V_ASN1_OTHER -3/* used in ASN1_TYPE */
Definition at line 46 of file asn1.h.
Referenced by ASN1_TYPE_cmp().
V_ASN1_PRIMATIVE_TAG
#define V_ASN1_PRIMATIVE_TAG 0x1f
Definition at line 43 of file asn1.h.
V_ASN1_PRIMITIVE_TAG
#define V_ASN1_PRIMITIVE_TAG 0x1f
Definition at line 42 of file asn1.h.
Referenced by ASN1_put_object().
V_ASN1_PRINTABLESTRING
#define V_ASN1_PRINTABLESTRING 19
Definition at line 66 of file asn1.h.
Referenced by ASN1_TYPE_cmp(), and X509_REQ_print_ex().
V_ASN1_PRIVATE
#define V_ASN1_PRIVATE 0xc0
Definition at line 39 of file asn1.h.
Referenced by ASN1_put_object().
V_ASN1_REAL
#define V_ASN1_REAL 9
Definition at line 60 of file asn1.h.
V_ASN1_SEQUENCE
#define V_ASN1_SEQUENCE 16
Definition at line 63 of file asn1.h.
Referenced by ASN1_TYPE_cmp(), ASN1_TYPE_pack_sequence(), ASN1_TYPE_unpack_sequence(), CMS_add1_ReceiptRequest(), CMS_add_smimecap(), CMS_get1_ReceiptRequest(), PKCS7_add_attrib_smimecap(), STACK_OF(), and X509_REQ_add_extensions_nid().
V_ASN1_SET
#define V_ASN1_SET 17
Definition at line 64 of file asn1.h.
Referenced by ASN1_TYPE_cmp().
V_ASN1_T61STRING
#define V_ASN1_T61STRING 20
Definition at line 67 of file asn1.h.
Referenced by ASN1_TYPE_cmp(), and X509_REQ_print_ex().
V_ASN1_TELETEXSTRING
#define V_ASN1_TELETEXSTRING 20/* alias */
Definition at line 68 of file asn1.h.
V_ASN1_UNDEF
#define V_ASN1_UNDEF -1
Definition at line 49 of file asn1.h.
Referenced by ASN1_item_sign_ctx(), CMS_add_simple_smimecap(), and X509_NAME_ENTRY_set_data().
V_ASN1_UNIVERSAL
#define V_ASN1_UNIVERSAL 0x00
Definition at line 36 of file asn1.h.
Referenced by i2d_ASN1_OBJECT().
V_ASN1_UNIVERSALSTRING
#define V_ASN1_UNIVERSALSTRING 28
Definition at line 77 of file asn1.h.
Referenced by ASN1_TYPE_cmp(), and ASN1_UNIVERSALSTRING_to_string().
V_ASN1_UTCTIME
#define V_ASN1_UTCTIME 23
Definition at line 71 of file asn1.h.
Referenced by ASN1_TIME_check(), ASN1_TIME_print(), ASN1_TIME_set_string(), ASN1_TYPE_cmp(), ASN1_UTCTIME_adj(), ASN1_UTCTIME_set_string(), asn1_utctime_to_tm(), PKCS7_add0_attrib_signing_time(), X509_cmp_time(), and X509_time_adj_ex().
V_ASN1_UTF8STRING
#define V_ASN1_UTF8STRING 12
Definition at line 62 of file asn1.h.
Referenced by ASN1_TYPE_cmp(), and X509_REQ_print_ex().
V_ASN1_VIDEOTEXSTRING
#define V_ASN1_VIDEOTEXSTRING 21
Definition at line 69 of file asn1.h.
Referenced by ASN1_TYPE_cmp().
V_ASN1_VISIBLESTRING
#define V_ASN1_VISIBLESTRING 26/* alias */
Definition at line 75 of file asn1.h.
Referenced by ASN1_TYPE_cmp().
Typedef Documentation
ASN1_ITEM_EXP
typedef const ASN1_ITEM ASN1_ITEM_EXP
Definition at line 317 of file asn1.h.
ASN1_VALUE
typedef struct ASN1_VALUE_st ASN1_VALUE
Definition at line 212 of file asn1.h.
Function Documentation
a2d_ASN1_OBJECT()
int a2d_ASN1_OBJECT (unsigned char * out, int olen, const char * buf, int num)
Definition at line 41 of file a_object.c.
a2i_ASN1_ENUMERATED()
int a2i_ASN1_ENUMERATED (BIO * bp, ASN1_ENUMERATED * bs, char * buf, int size)
Definition at line 161 of file f_int.c.
a2i_ASN1_INTEGER()
int a2i_ASN1_INTEGER (BIO * bp, ASN1_INTEGER * bs, char * buf, int size)
Definition at line 54 of file f_int.c.
a2i_ASN1_STRING()
int a2i_ASN1_STRING (BIO * bp, ASN1_STRING * bs, char * buf, int size)
Definition at line 48 of file f_string.c.
ASN1_add_oid_module()
void ASN1_add_oid_module (void)
Definition at line 49 of file asn_moid.c.
References CONF_module_add().
Referenced by OPENSSL_load_builtin_modules().
ASN1_add_stable_module()
void ASN1_add_stable_module (void)
Definition at line 48 of file asn_mstbl.c.
References CONF_module_add().
Referenced by OPENSSL_load_builtin_modules().
ASN1_BIT_STRING_check()
int ASN1_BIT_STRING_check (const ASN1_BIT_STRING * a, const unsigned char * flags, int flags_len)
Definition at line 192 of file a_bitstr.c.
ASN1_BIT_STRING_get_bit()
int ASN1_BIT_STRING_get_bit (const ASN1_BIT_STRING * a, int n)
Definition at line 175 of file a_bitstr.c.
References NULL.
ASN1_BIT_STRING_name_print()
int ASN1_BIT_STRING_name_print (BIO * out, ASN1_BIT_STRING * bs, BIT_STRING_BITNAME * tbl, int indent)
Definition at line 15 of file t_bitst.c.
ASN1_BIT_STRING_num_asc()
int ASN1_BIT_STRING_num_asc (const char * name, BIT_STRING_BITNAME * tbl)
Definition at line 47 of file t_bitst.c.
References BIT_STRING_BITNAME::bitnum, BIT_STRING_BITNAME::lname, and BIT_STRING_BITNAME::sname.
Referenced by ASN1_BIT_STRING_set_asc().
ASN1_BIT_STRING_set()
int ASN1_BIT_STRING_set (ASN1_BIT_STRING * a, unsigned char * d, int length)
Definition at line 15 of file a_bitstr.c.
References ASN1_STRING_set().
ASN1_BIT_STRING_set_asc()
int ASN1_BIT_STRING_set_asc (ASN1_BIT_STRING * bs, const char * name, int value, BIT_STRING_BITNAME * tbl)
Definition at line 33 of file t_bitst.c.
References ASN1_BIT_STRING_num_asc(), and ASN1_BIT_STRING_set_bit().
ASN1_BIT_STRING_set_bit()
int ASN1_BIT_STRING_set_bit (ASN1_BIT_STRING * a, int n, int value)
Definition at line 140 of file a_bitstr.c.
Referenced by ASN1_BIT_STRING_set_asc(), TS_RESP_CTX_add_failure_info(), and v2i_ASN1_BIT_STRING().
ASN1_bn_print()
int ASN1_bn_print (BIO * bp, const char * number, const BIGNUM * num, unsigned char * buf, int off)
Definition at line 45 of file t_pkey.c.
ASN1_buf_print()
int ASN1_buf_print (BIO * bp, const unsigned char * buf, size_t buflen, int off)
Definition at line 21 of file t_pkey.c.
ASN1_check_infinite_end()
int ASN1_check_infinite_end (unsigned char ** p, long len)
Definition at line 34 of file asn1_lib.c.
ASN1_const_check_infinite_end()
int ASN1_const_check_infinite_end (const unsigned char ** p, long len)
Definition at line 39 of file asn1_lib.c.
ASN1_d2i_bio()
void* ASN1_d2i_bio (void *(*)(void) xnew, d2i_of_void * d2i, BIO * in, void ** x)
Definition at line 38 of file a_d2i_fp.c.
References NULL.
ASN1_d2i_fp()
void* ASN1_d2i_fp (void *(*)(void) xnew, d2i_of_void * d2i, FILE * in, void ** x)
Definition at line 22 of file a_d2i_fp.c.
Referenced by d2i_RSA_PUBKEY_fp().
ASN1_dup()
void* ASN1_dup (i2d_of_void * i2d, d2i_of_void * d2i, void * x)
Definition at line 16 of file a_dup.c.
ASN1_ENUMERATED_get()
long ASN1_ENUMERATED_get (const ASN1_ENUMERATED * a)
Definition at line 598 of file a_int.c.
References ASN1_ENUMERATED_get_int64(), NULL, V_ASN1_ENUMERATED, and V_ASN1_NEG.
Referenced by i2s_ASN1_ENUMERATED_TABLE(), and OCSP_response_status().
ASN1_ENUMERATED_get_int64()
int ASN1_ENUMERATED_get_int64 (int64_t * pr, const ASN1_ENUMERATED * a)
Definition at line 583 of file a_int.c.
Referenced by ASN1_ENUMERATED_get().
ASN1_ENUMERATED_set()
int ASN1_ENUMERATED_set (ASN1_ENUMERATED * a, long v)
Definition at line 593 of file a_int.c.
References ASN1_ENUMERATED_set_int64().
Referenced by OCSP_basic_add1_status(), and OCSP_response_create().
ASN1_ENUMERATED_set_int64()
int ASN1_ENUMERATED_set_int64 (ASN1_ENUMERATED * a, int64_t r)
Definition at line 588 of file a_int.c.
Referenced by ASN1_ENUMERATED_set().
ASN1_ENUMERATED_to_BN()
BIGNUM* ASN1_ENUMERATED_to_BN (const ASN1_ENUMERATED * ai, BIGNUM * bn)
Definition at line 621 of file a_int.c.
Referenced by i2s_ASN1_ENUMERATED().
ASN1_GENERALIZEDTIME_adj()
ASN1_GENERALIZEDTIME* ASN1_GENERALIZEDTIME_adj (ASN1_GENERALIZEDTIME * s, time_t t, int offset_day, long offset_sec)
Definition at line 166 of file a_gentm.c.
References ASN1_F_ASN1_GENERALIZEDTIME_ADJ, ASN1err, BIO_snprintf(), ebcdic2ascii(), ERR_R_MALLOC_FAILURE, if(), len, NULL, OPENSSL_free, OPENSSL_gmtime(), OPENSSL_gmtime_adj(), OPENSSL_malloc, and V_ASN1_GENERALIZEDTIME.
Referenced by ASN1_GENERALIZEDTIME_set(), ASN1_TIME_adj(), and X509_time_adj_ex().
ASN1_GENERALIZEDTIME_check()
int ASN1_GENERALIZEDTIME_check (const ASN1_GENERALIZEDTIME * a)
Definition at line 137 of file a_gentm.c.
References asn1_generalizedtime_to_tm(), and NULL.
Referenced by ASN1_GENERALIZEDTIME_set_string(), and ASN1_TIME_check().
ASN1_GENERALIZEDTIME_print()
int ASN1_GENERALIZEDTIME_print (BIO * fp, const ASN1_GENERALIZEDTIME * a)
Definition at line 223 of file a_gentm.c.
References _asn1_mon, BIO_printf(), BIO_write(), h, if(), and NULL.
Referenced by ASN1_TIME_print(), and TS_TST_INFO_print_bio().
ASN1_GENERALIZEDTIME_set()
ASN1_GENERALIZEDTIME* ASN1_GENERALIZEDTIME_set (ASN1_GENERALIZEDTIME * s, time_t t)
Definition at line 160 of file a_gentm.c.
References ASN1_GENERALIZEDTIME_adj().
ASN1_GENERALIZEDTIME_set_string()
int ASN1_GENERALIZEDTIME_set_string (ASN1_GENERALIZEDTIME * s, const char * str)
Definition at line 142 of file a_gentm.c.
References ASN1_GENERALIZEDTIME_check(), ASN1_STRING_set(), NULL, t, and V_ASN1_GENERALIZEDTIME.
Referenced by OCSP_archive_cutoff_new(), and OCSP_crlID_new().
ASN1_generate_nconf()
ASN1_TYPE* ASN1_generate_nconf (const char * str, CONF * nconf)
Definition at line 78 of file asn1_gen.c.
References ASN1_generate_v3(), NULL, and X509V3_set_nconf().
ASN1_generate_v3()
ASN1_TYPE* ASN1_generate_v3 (const char * str, X509V3_CTX * cnf)
Definition at line 89 of file asn1_gen.c.
Referenced by ASN1_generate_nconf().
ASN1_get_object()
int ASN1_get_object (const unsigned char ** pp, long * plength, int * ptag, int * pclass, long omax)
Definition at line 44 of file asn1_lib.c.
ASN1_i2d_bio()
int ASN1_i2d_bio (i2d_of_void * i2d, BIO * out, unsigned char * x)
Definition at line 34 of file a_i2d_fp.c.
ASN1_i2d_fp()
int ASN1_i2d_fp (i2d_of_void * i2d, FILE * out, void * x)
Definition at line 18 of file a_i2d_fp.c.
Referenced by i2d_RSA_PUBKEY_fp().
ASN1_INTEGER_cmp()
int ASN1_INTEGER_cmp (const ASN1_INTEGER * x, const ASN1_INTEGER * y)
Definition at line 23 of file a_int.c.
Referenced by X509_check_akid(), and X509_issuer_and_serial_cmp().
ASN1_INTEGER_dup()
ASN1_INTEGER* ASN1_INTEGER_dup (const ASN1_INTEGER * x)
Definition at line 18 of file a_int.c.
References ASN1_STRING_dup().
Referenced by TS_ACCURACY_set_micros(), TS_ACCURACY_set_millis(), TS_ACCURACY_set_seconds(), TS_REQ_set_nonce(), TS_TST_INFO_set_nonce(), and TS_TST_INFO_set_serial().
ASN1_INTEGER_get()
long ASN1_INTEGER_get (const ASN1_INTEGER * a)
Definition at line 559 of file a_int.c.
References ASN1_INTEGER_get_int64(), and NULL.
Referenced by asn1_do_adb(), OCSP_REQUEST_print(), TS_REQ_get_version(), TS_STATUS_INFO_print_bio(), TS_TST_INFO_get_version(), TS_TST_INFO_print_bio(), X509_CRL_get_version(), X509_get_version(), and X509_REQ_get_version().
ASN1_INTEGER_get_int64()
int ASN1_INTEGER_get_int64 (int64_t * pr, const ASN1_INTEGER * a)
Definition at line 534 of file a_int.c.
Referenced by ASN1_INTEGER_get().
ASN1_INTEGER_get_uint64()
int ASN1_INTEGER_get_uint64 (uint64_t * pr, const ASN1_INTEGER * a)
Definition at line 544 of file a_int.c.
ASN1_INTEGER_set()
int ASN1_INTEGER_set (ASN1_INTEGER * a, long v)
Definition at line 554 of file a_int.c.
References ASN1_INTEGER_set_int64().
Referenced by CMS_add_simple_smimecap(), OCSP_crlID_new(), PKCS12_init(), PKCS12_setup_mac(), PKCS7_set_type(), rsa_pss_params_create(), TS_REQ_set_version(), TS_RESP_CTX_set_accuracy(), TS_STATUS_INFO_set_status(), TS_TST_INFO_set_version(), X509_CRL_set_version(), X509_REQ_set_version(), and X509_set_version().
ASN1_INTEGER_set_int64()
int ASN1_INTEGER_set_int64 (ASN1_INTEGER * a, int64_t r)
Definition at line 539 of file a_int.c.
Referenced by ASN1_INTEGER_set().
ASN1_INTEGER_set_uint64()
int ASN1_INTEGER_set_uint64 (ASN1_INTEGER * a, uint64_t r)
Definition at line 549 of file a_int.c.
ASN1_INTEGER_to_BN()
BIGNUM* ASN1_INTEGER_to_BN (const ASN1_INTEGER * ai, BIGNUM * bn)
Definition at line 578 of file a_int.c.
Referenced by i2s_ASN1_INTEGER(), and TS_ASN1_INTEGER_print_bio().
ASN1_item_d2i()
ASN1_VALUE* ASN1_item_d2i (ASN1_VALUE ** val, const unsigned char ** in, long len, const ASN1_ITEM * it)
Definition at line 95 of file tasn_dec.c.
Referenced by OCSP_REQ_CTX_nbio_d2i(), STACK_OF(), and X509V3_EXT_d2i().
ASN1_item_d2i_bio()
void* ASN1_item_d2i_bio (const ASN1_ITEM * it, BIO * in, void * x)
Definition at line 58 of file a_d2i_fp.c.
References NULL.
Referenced by d2i_CMS_bio(), d2i_PKCS12_bio(), d2i_PKCS7_bio(), d2i_RSAPrivateKey_bio(), d2i_RSAPublicKey_bio(), d2i_X509_bio(), d2i_X509_CRL_bio(), and d2i_X509_REQ_bio().
ASN1_item_d2i_fp()
void* ASN1_item_d2i_fp (const ASN1_ITEM * it, FILE * in, void * x)
Definition at line 77 of file a_d2i_fp.c.
Referenced by d2i_PKCS12_fp(), d2i_PKCS7_fp(), d2i_RSAPrivateKey_fp(), d2i_RSAPublicKey_fp(), d2i_X509_CRL_fp(), d2i_X509_fp(), and d2i_X509_REQ_fp().
ASN1_item_dup()
void* ASN1_item_dup (const ASN1_ITEM * it, void * x)
Definition at line 49 of file a_dup.c.
References NULL.
ASN1_item_free()
void ASN1_item_free (ASN1_VALUE * val, const ASN1_ITEM * it)
Definition at line 21 of file tasn_fre.c.
ASN1_ITEM_get()
const ASN1_ITEM* ASN1_ITEM_get (size_t i)
Definition at line 37 of file asn1_item_list.c.
References OSSL_NELEM.
ASN1_item_i2d()
int ASN1_item_i2d (ASN1_VALUE * val, unsigned char ** out, const ASN1_ITEM * it)
Definition at line 42 of file tasn_enc.c.
Referenced by ASN1_item_pack(), ASN1_item_sign_ctx(), OCSP_REQ_CTX_i2d(), PKCS12_item_i2d_encrypt(), PKCS7_add_attrib_smimecap(), PKCS7_signatureVerify(), and X509_REQ_add_extensions_nid().
ASN1_item_i2d_bio()
int ASN1_item_i2d_bio (const ASN1_ITEM * it, BIO * out, void * x)
Definition at line 84 of file a_i2d_fp.c.
Referenced by i2d_CMS_bio(), i2d_PKCS12_bio(), i2d_PKCS7_bio(), i2d_RSAPrivateKey_bio(), i2d_RSAPublicKey_bio(), i2d_X509_bio(), i2d_X509_CRL_bio(), i2d_X509_REQ_bio(), and OCSP_REQ_CTX_i2d().
ASN1_item_i2d_fp()
int ASN1_item_i2d_fp (const ASN1_ITEM * it, FILE * out, void * x)
Definition at line 68 of file a_i2d_fp.c.
Referenced by i2d_PKCS12_fp(), i2d_PKCS7_fp(), i2d_RSAPrivateKey_fp(), i2d_RSAPublicKey_fp(), i2d_X509_CRL_fp(), i2d_X509_fp(), and i2d_X509_REQ_fp().
ASN1_ITEM_lookup()
const ASN1_ITEM* ASN1_ITEM_lookup (const char * name)
Definition at line 24 of file asn1_item_list.c.
References OSSL_NELEM.
ASN1_item_ndef_i2d()
int ASN1_item_ndef_i2d (ASN1_VALUE * val, unsigned char ** out, const ASN1_ITEM * it)
Definition at line 36 of file tasn_enc.c.
ASN1_item_new()
ASN1_VALUE* ASN1_item_new (const ASN1_ITEM * it)
Definition at line 27 of file tasn_new.c.
ASN1_item_pack()
ASN1_STRING* ASN1_item_pack (void * obj, const ASN1_ITEM * it, ASN1_OCTET_STRING ** oct)
ASN1_item_print()
int ASN1_item_print (BIO * out, ASN1_VALUE * ifld, int indent, const ASN1_ITEM * it, const ASN1_PCTX * pctx)
Definition at line 121 of file tasn_prn.c.
ASN1_item_unpack()
void* ASN1_item_unpack (const ASN1_STRING * oct, const ASN1_ITEM * it)
Definition at line 53 of file asn_pack.c.
Referenced by ASN1_TYPE_unpack_sequence(), CMS_get1_ReceiptRequest(), cms_Receipt_verify(), OCSP_response_get1_basic(), PKCS12_SAFEBAG_get1_cert(), PKCS12_SAFEBAG_get1_crl(), and STACK_OF().
ASN1_mbstring_copy()
int ASN1_mbstring_copy (ASN1_STRING ** out, const unsigned char * in, int len, int inform, unsigned long mask)
Definition at line 37 of file a_mbstr.c.
ASN1_mbstring_ncopy()
int ASN1_mbstring_ncopy (ASN1_STRING ** out, const unsigned char * in, int len, int inform, unsigned long mask, long minsize, long maxsize)
Definition at line 43 of file a_mbstr.c.
ASN1_OBJECT_create()
ASN1_OBJECT* ASN1_OBJECT_create (int nid, unsigned char * data, int len, const char * sn, const char * ln)
Definition at line 357 of file a_object.c.
References ASN1_OBJECT_FLAG_DYNAMIC, ASN1_OBJECT_FLAG_DYNAMIC_DATA, ASN1_OBJECT_FLAG_DYNAMIC_STRINGS, data, len, nid, and OBJ_dup().
ASN1_OBJECT_free()
void ASN1_OBJECT_free (ASN1_OBJECT * a)
Definition at line 335 of file a_object.c.
References ASN1_OBJECT_FLAG_DYNAMIC, ASN1_OBJECT_FLAG_DYNAMIC_DATA, ASN1_OBJECT_FLAG_DYNAMIC_STRINGS, NULL, and OPENSSL_free.
Referenced by asn1_primitive_free(), ASN1_sign(), EVP_CIPHER_type(), OBJ_create(), OBJ_dup(), OBJ_txt2nid(), OCSP_accept_responses_new(), policy_data_free(), TS_REQ_set_policy_id(), TS_RESP_CTX_add_policy(), TS_RESP_CTX_free(), TS_RESP_CTX_set_def_policy(), TS_TST_INFO_set_policy_id(), TS_VERIFY_CTX_cleanup(), X509_ATTRIBUTE_create_by_txt(), X509_ATTRIBUTE_set1_object(), X509_EXTENSION_set_object(), X509_NAME_ENTRY_create_by_NID(), X509_NAME_ENTRY_create_by_txt(), X509_NAME_ENTRY_set_object(), and X509_VERIFY_PARAM_free().
ASN1_OBJECT_new()
ASN1_OBJECT* ASN1_OBJECT_new (void)
Definition at line 322 of file a_object.c.
Referenced by OBJ_dup().
ASN1_object_size()
int ASN1_object_size (int constructed, int length, int tag)
Definition at line 208 of file asn1_lib.c.
Referenced by i2d_ASN1_OBJECT().
ASN1_OCTET_STRING_cmp()
int ASN1_OCTET_STRING_cmp (const ASN1_OCTET_STRING * a, const ASN1_OCTET_STRING * b)
Definition at line 19 of file a_octet.c.
References ASN1_STRING_cmp().
Referenced by CMS_RecipientInfo_kekri_id_cmp(), OCSP_check_nonce(), and X509_check_akid().
ASN1_OCTET_STRING_dup()
ASN1_OCTET_STRING* ASN1_OCTET_STRING_dup (const ASN1_OCTET_STRING * a)
Definition at line 14 of file a_octet.c.
References ASN1_STRING_dup().
ASN1_OCTET_STRING_set()
int ASN1_OCTET_STRING_set (ASN1_OCTET_STRING * str, const unsigned char * data, int len)
Definition at line 25 of file a_octet.c.
References ASN1_STRING_set().
Referenced by ASN1_TYPE_set_octetstring(), TS_MSG_IMPRINT_set_msg(), and X509_EXTENSION_set_data().
ASN1_parse()
int ASN1_parse (BIO * bp, const unsigned char * pp, long len, int indent)
Definition at line 58 of file asn1_par.c.
ASN1_parse_dump()
int ASN1_parse_dump (BIO * bp, const unsigned char * pp, long len, int indent, int dump)
Definition at line 63 of file asn1_par.c.
ASN1_PCTX_free()
void ASN1_PCTX_free (ASN1_PCTX * p)
Definition at line 47 of file tasn_prn.c.
References OPENSSL_free.
Referenced by FuzzerCleanup().
ASN1_PCTX_get_cert_flags()
unsigned long ASN1_PCTX_get_cert_flags (const ASN1_PCTX * p)
Definition at line 72 of file tasn_prn.c.
ASN1_PCTX_get_flags()
unsigned long ASN1_PCTX_get_flags (const ASN1_PCTX * p)
Definition at line 52 of file tasn_prn.c.
ASN1_PCTX_get_nm_flags()
unsigned long ASN1_PCTX_get_nm_flags (const ASN1_PCTX * p)
Definition at line 62 of file tasn_prn.c.
ASN1_PCTX_get_oid_flags()
unsigned long ASN1_PCTX_get_oid_flags (const ASN1_PCTX * p)
Definition at line 82 of file tasn_prn.c.
ASN1_PCTX_get_str_flags()
unsigned long ASN1_PCTX_get_str_flags (const ASN1_PCTX * p)
Definition at line 92 of file tasn_prn.c.
ASN1_PCTX_new()
ASN1_PCTX* ASN1_PCTX_new (void)
Definition at line 35 of file tasn_prn.c.
ASN1_PCTX_set_cert_flags()
void ASN1_PCTX_set_cert_flags (ASN1_PCTX * p, unsigned long flags)
Definition at line 77 of file tasn_prn.c.
References flags.
ASN1_PCTX_set_flags()
void ASN1_PCTX_set_flags (ASN1_PCTX * p, unsigned long flags)
Definition at line 57 of file tasn_prn.c.
References flags.
ASN1_PCTX_set_nm_flags()
void ASN1_PCTX_set_nm_flags (ASN1_PCTX * p, unsigned long flags)
Definition at line 67 of file tasn_prn.c.
References flags.
ASN1_PCTX_set_oid_flags()
void ASN1_PCTX_set_oid_flags (ASN1_PCTX * p, unsigned long flags)
Definition at line 87 of file tasn_prn.c.
References flags.
ASN1_PCTX_set_str_flags()
void ASN1_PCTX_set_str_flags (ASN1_PCTX * p, unsigned long flags)
Definition at line 97 of file tasn_prn.c.
References flags.
ASN1_PRINTABLE_type()
int ASN1_PRINTABLE_type (const unsigned char * s, int max)
Definition at line 15 of file a_print.c.
Referenced by ASN1_UNIVERSALSTRING_to_string(), and X509_NAME_ENTRY_set_data().
ASN1_put_eoc()
int ASN1_put_eoc (unsigned char ** pp)
Definition at line 178 of file asn1_lib.c.
References pp.
ASN1_put_object()
void ASN1_put_object (unsigned char ** pp, int constructed, int length, int tag, int xclass)
Definition at line 148 of file asn1_lib.c.
References pp, V_ASN1_CONSTRUCTED, V_ASN1_PRIMITIVE_TAG, and V_ASN1_PRIVATE.
Referenced by i2d_ASN1_OBJECT().
ASN1_SCTX_free()
void ASN1_SCTX_free (ASN1_SCTX * p)
Definition at line 37 of file tasn_scn.c.
References OPENSSL_free.
ASN1_SCTX_get_app_data()
void* ASN1_SCTX_get_app_data (ASN1_SCTX * p)
Definition at line 62 of file tasn_scn.c.
ASN1_SCTX_get_flags()
unsigned long ASN1_SCTX_get_flags (ASN1_SCTX * p)
Definition at line 52 of file tasn_scn.c.
ASN1_SCTX_get_item()
const ASN1_ITEM* ASN1_SCTX_get_item (ASN1_SCTX * p)
Definition at line 42 of file tasn_scn.c.
ASN1_SCTX_get_template()
const ASN1_TEMPLATE* ASN1_SCTX_get_template (ASN1_SCTX * p)
Definition at line 47 of file tasn_scn.c.
ASN1_SCTX_new()
ASN1_SCTX* ASN1_SCTX_new (int(*)(ASN1_SCTX *ctx) scan_cb)
Definition at line 25 of file tasn_scn.c.
ASN1_SCTX_set_app_data()
void ASN1_SCTX_set_app_data (ASN1_SCTX * p, void * data)
Definition at line 57 of file tasn_scn.c.
References data.
ASN1_str2mask()
int ASN1_str2mask (const char * str, unsigned long * pmask)
Definition at line 785 of file asn1_gen.c.
References CONF_parse_list().
ASN1_STRING_clear_free()
void ASN1_STRING_clear_free (ASN1_STRING * a)
Definition at line 335 of file asn1_lib.c.
References ASN1_STRING_FLAG_NDEF, ASN1_STRING_free(), NULL, and OPENSSL_cleanse().
ASN1_STRING_cmp()
int ASN1_STRING_cmp (const ASN1_STRING * a, const ASN1_STRING * b)
Definition at line 344 of file asn1_lib.c.
Referenced by ASN1_OCTET_STRING_cmp(), ASN1_TYPE_cmp(), and cms_Receipt_verify().
ASN1_STRING_copy()
int ASN1_STRING_copy (ASN1_STRING * dst, const ASN1_STRING * str)
Definition at line 236 of file asn1_lib.c.
References ASN1_STRING_FLAG_EMBED, ASN1_STRING_set(), and NULL.
Referenced by ASN1_TIME_set_string(), X509_REVOKED_set_serialNumber(), and X509_set_serialNumber().
ASN1_STRING_dup()
ASN1_STRING* ASN1_STRING_dup (const ASN1_STRING * a)
Definition at line 249 of file asn1_lib.c.
Referenced by ASN1_INTEGER_dup(), ASN1_OCTET_STRING_dup(), ASN1_TYPE_set1(), TS_TST_INFO_set_time(), X509_REVOKED_set_revocationDate(), and x509_set1_time().
ASN1_STRING_free()
void ASN1_STRING_free (ASN1_STRING * a)
Definition at line 328 of file asn1_lib.c.
References asn1_string_embed_free(), ASN1_STRING_FLAG_EMBED, and NULL.
Referenced by ASN1_item_pack(), ASN1_STRING_clear_free(), and X509_ATTRIBUTE_set1_data().
ASN1_STRING_get0_data()
const unsigned char* ASN1_STRING_get0_data (const ASN1_STRING * x)
Definition at line 374 of file asn1_lib.c.
Referenced by X509_ocspid_print(), and X509V3_EXT_d2i().
ASN1_STRING_get_default_mask()
unsigned long ASN1_STRING_get_default_mask (void)
Definition at line 34 of file a_strnid.c.
ASN1_STRING_length()
int ASN1_STRING_length (const ASN1_STRING * x)
Definition at line 359 of file asn1_lib.c.
Referenced by X509_ocspid_print(), and X509V3_EXT_d2i().
ASN1_STRING_length_set()
void ASN1_STRING_length_set (ASN1_STRING * x, int n)
Definition at line 364 of file asn1_lib.c.
References len.
ASN1_STRING_new()
ASN1_STRING* ASN1_STRING_new (void)
Definition at line 300 of file asn1_lib.c.
References ASN1_STRING_type_new(), and V_ASN1_OCTET_STRING.
Referenced by ASN1_item_pack(), and PKCS7_add_attrib_smimecap().
ASN1_STRING_print()
int ASN1_STRING_print (BIO * bp, const ASN1_STRING * v)
Definition at line 82 of file a_print.c.
Referenced by TS_ext_print_bio(), and X509_REQ_print_ex().
ASN1_STRING_print_ex()
int ASN1_STRING_print_ex (BIO * out, const ASN1_STRING * str, unsigned long flags)
Definition at line 555 of file a_strex.c.
Referenced by TS_STATUS_INFO_print_bio().
ASN1_STRING_print_ex_fp()
int ASN1_STRING_print_ex_fp (FILE * fp, const ASN1_STRING * str, unsigned long flags)
Definition at line 561 of file a_strex.c.
ASN1_STRING_set()
int ASN1_STRING_set (ASN1_STRING * str, const void * data, int len)
Definition at line 264 of file asn1_lib.c.
Referenced by ASN1_BIT_STRING_set(), ASN1_GENERALIZEDTIME_set_string(), ASN1_OCTET_STRING_set(), ASN1_STRING_copy(), ASN1_UTCTIME_set_string(), CMS_ReceiptRequest_create0(), OCSP_crlID_new(), OCSP_url_svcloc_new(), s2i_ASN1_IA5STRING(), X509_ATTRIBUTE_set1_data(), and X509_NAME_ENTRY_set_data().
ASN1_STRING_set0()
void ASN1_STRING_set0 (ASN1_STRING * str, void * data, int len)
Definition at line 293 of file asn1_lib.c.
References data, len, and OPENSSL_free.
Referenced by CMS_dataFinal(), and CMS_ReceiptRequest_create0().
ASN1_STRING_set_by_NID()
ASN1_STRING* ASN1_STRING_set_by_NID (ASN1_STRING ** out, const unsigned char * in, int inlen, int inform, int nid)
Definition at line 79 of file a_strnid.c.
Referenced by X509_ATTRIBUTE_set1_data(), and X509_NAME_ENTRY_set_data().
ASN1_STRING_set_default_mask()
void ASN1_STRING_set_default_mask (unsigned long mask)
Referenced by ASN1_STRING_set_default_mask_asc().
ASN1_STRING_set_default_mask_asc()
int ASN1_STRING_set_default_mask_asc (const char * p)
Definition at line 49 of file a_strnid.c.
References ASN1_STRING_set_default_mask(), B_ASN1_BMPSTRING, B_ASN1_T61STRING, and B_ASN1_UTF8STRING.
ASN1_STRING_TABLE_add()
int ASN1_STRING_TABLE_add (int , long , long , unsigned long, unsigned long)
Definition at line 177 of file a_strnid.c.
ASN1_STRING_TABLE_cleanup()
void ASN1_STRING_TABLE_cleanup (void)
Definition at line 198 of file a_strnid.c.
ASN1_STRING_TABLE_get()
ASN1_STRING_TABLE* ASN1_STRING_TABLE_get (int nid)
Definition at line 126 of file a_strnid.c.
ASN1_STRING_to_UTF8()
int ASN1_STRING_to_UTF8 (unsigned char ** out, const ASN1_STRING * in)
Definition at line 572 of file a_strex.c.
ASN1_STRING_type()
int ASN1_STRING_type (const ASN1_STRING * x)
Definition at line 369 of file asn1_lib.c.
ASN1_STRING_type_new()
ASN1_STRING* ASN1_STRING_type_new (int type)
Definition at line 305 of file asn1_lib.c.
Referenced by ASN1_STRING_new(), and X509_ATTRIBUTE_set1_data().
ASN1_tag2bit()
unsigned long ASN1_tag2bit (int tag)
Definition at line 75 of file tasn_dec.c.
ASN1_tag2str()
const char* ASN1_tag2str (int tag)
Definition at line 348 of file asn1_par.c.
References V_ASN1_NEG_ENUMERATED, and V_ASN1_NEG_INTEGER.
ASN1_TIME_adj()
ASN1_TIME* ASN1_TIME_adj (ASN1_TIME * s, time_t t, int offset_day, long offset_sec)
Definition at line 32 of file a_time.c.
References ASN1_F_ASN1_TIME_ADJ, ASN1_GENERALIZEDTIME_adj(), ASN1_R_ERROR_GETTING_TIME, ASN1_UTCTIME_adj(), ASN1err, NULL, OPENSSL_gmtime(), and OPENSSL_gmtime_adj().
Referenced by ASN1_TIME_set(), and X509_time_adj_ex().
ASN1_TIME_check()
int ASN1_TIME_check (const ASN1_TIME * t)
Definition at line 52 of file a_time.c.
References ASN1_GENERALIZEDTIME_check(), ASN1_UTCTIME_check(), V_ASN1_GENERALIZEDTIME, and V_ASN1_UTCTIME.
Referenced by ASN1_TIME_set_string().
ASN1_TIME_diff()
int ASN1_TIME_diff (int * pday, int * psec, const ASN1_TIME * from, const ASN1_TIME * to)
Definition at line 144 of file a_time.c.
ASN1_TIME_print()
int ASN1_TIME_print (BIO * fp, const ASN1_TIME * a)
Definition at line 155 of file a_time.c.
References ASN1_GENERALIZEDTIME_print(), ASN1_UTCTIME_print(), BIO_write(), V_ASN1_GENERALIZEDTIME, and V_ASN1_UTCTIME.
Referenced by verify_callback().
ASN1_TIME_set_string()
int ASN1_TIME_set_string (ASN1_TIME * s, const char * str)
Definition at line 104 of file a_time.c.
References ASN1_STRING_copy(), ASN1_TIME_check(), t, V_ASN1_GENERALIZEDTIME, and V_ASN1_UTCTIME.
Referenced by set_cert_times().
ASN1_TIME_to_generalizedtime()
ASN1_GENERALIZEDTIME* ASN1_TIME_to_generalizedtime (ASN1_TIME * t, ASN1_GENERALIZEDTIME ** out)
Definition at line 62 of file a_time.c.
Referenced by OCSP_basic_add1_status().
ASN1_TYPE_cmp()
int ASN1_TYPE_cmp (const ASN1_TYPE * a, const ASN1_TYPE * b)
Definition at line 59 of file a_type.c.
References ASN1_STRING_cmp(), ASN1_TYPE::boolean, OBJ_cmp(), ASN1_TYPE::object, ASN1_TYPE::ptr, ASN1_TYPE::type, V_ASN1_BIT_STRING, V_ASN1_BMPSTRING, V_ASN1_BOOLEAN, V_ASN1_ENUMERATED, V_ASN1_GENERALIZEDTIME, V_ASN1_GENERALSTRING, V_ASN1_GRAPHICSTRING, V_ASN1_IA5STRING, V_ASN1_INTEGER, V_ASN1_NULL, V_ASN1_NUMERICSTRING, V_ASN1_OBJECT, V_ASN1_OCTET_STRING, V_ASN1_OTHER, V_ASN1_PRINTABLESTRING, V_ASN1_SEQUENCE, V_ASN1_SET, V_ASN1_T61STRING, V_ASN1_UNIVERSALSTRING, V_ASN1_UTCTIME, V_ASN1_UTF8STRING, V_ASN1_VIDEOTEXSTRING, V_ASN1_VISIBLESTRING, and ASN1_TYPE::value.
ASN1_TYPE_get_int_octetstring()
int ASN1_TYPE_get_int_octetstring (const ASN1_TYPE * a, long * num, unsigned char * data, int max_len)
ASN1_TYPE_get_octetstring()
int ASN1_TYPE_get_octetstring (const ASN1_TYPE * a, unsigned char * data, int max_len)
Definition at line 30 of file evp_asn1.c.
ASN1_TYPE_pack_sequence()
ASN1_TYPE* ASN1_TYPE_pack_sequence (const ASN1_ITEM * it, void * s, ASN1_TYPE ** t)
Definition at line 105 of file a_type.c.
References ASN1_item_pack(), ASN1_TYPE_set(), NULL, t, and V_ASN1_SEQUENCE.
ASN1_TYPE_set()
void ASN1_TYPE_set (ASN1_TYPE * a, int type, void * value)
Definition at line 24 of file a_type.c.
References asn1_primitive_free(), ASN1_TYPE::boolean, NULL, ASN1_TYPE::ptr, ASN1_TYPE::type, type, V_ASN1_BOOLEAN, and ASN1_TYPE::value.
Referenced by ASN1_TYPE_pack_sequence(), ASN1_TYPE_set1(), ASN1_TYPE_set_octetstring(), and X509_ATTRIBUTE_set1_data().
ASN1_TYPE_set1()
int ASN1_TYPE_set1 (ASN1_TYPE * a, int type, const void * value)
Definition at line 37 of file a_type.c.
References ASN1_STRING_dup(), ASN1_TYPE_set(), OBJ_dup(), V_ASN1_BOOLEAN, and V_ASN1_OBJECT.
Referenced by X509_ATTRIBUTE_set1_data().
ASN1_TYPE_set_int_octetstring()
int ASN1_TYPE_set_int_octetstring (ASN1_TYPE * a, long num, unsigned char * data, int len)
ASN1_TYPE_set_octetstring()
int ASN1_TYPE_set_octetstring (ASN1_TYPE * a, unsigned char * data, int len)
Definition at line 15 of file evp_asn1.c.
References ASN1_OCTET_STRING_set(), ASN1_TYPE_set(), NULL, and V_ASN1_OCTET_STRING.
ASN1_TYPE_unpack_sequence()
void* ASN1_TYPE_unpack_sequence (const ASN1_ITEM * it, const ASN1_TYPE * t)
Definition at line 129 of file a_type.c.
References ASN1_item_unpack(), NULL, ASN1_TYPE::sequence, ASN1_TYPE::type, V_ASN1_SEQUENCE, and ASN1_TYPE::value.
Referenced by cms_RecipientInfo_pwri_crypt().
ASN1_UNIVERSALSTRING_to_string()
int ASN1_UNIVERSALSTRING_to_string (ASN1_UNIVERSALSTRING * s)
Definition at line 54 of file a_print.c.
References ASN1_PRINTABLE_type(), and V_ASN1_UNIVERSALSTRING.
ASN1_UTCTIME_adj()
ASN1_UTCTIME* ASN1_UTCTIME_adj (ASN1_UTCTIME * s, time_t t, int offset_day, long offset_sec)
Definition at line 136 of file a_utctm.c.
References ASN1_F_ASN1_UTCTIME_ADJ, ASN1err, BIO_snprintf(), ebcdic2ascii(), ERR_R_MALLOC_FAILURE, if(), len, NULL, OPENSSL_free, OPENSSL_gmtime(), OPENSSL_gmtime_adj(), OPENSSL_malloc, and V_ASN1_UTCTIME.
Referenced by ASN1_TIME_adj(), ASN1_UTCTIME_set(), and X509_time_adj_ex().
ASN1_UTCTIME_check()
int ASN1_UTCTIME_check (const ASN1_UTCTIME * a)
Definition at line 108 of file a_utctm.c.
References asn1_utctime_to_tm(), and NULL.
Referenced by ASN1_TIME_check(), and ASN1_UTCTIME_set_string().
ASN1_UTCTIME_cmp_time_t()
int ASN1_UTCTIME_cmp_time_t (const ASN1_UTCTIME * s, time_t t)
Definition at line 190 of file a_utctm.c.
References asn1_utctime_to_tm(), OPENSSL_gmtime(), and OPENSSL_gmtime_diff().
ASN1_UTCTIME_print()
int ASN1_UTCTIME_print (BIO * fp, const ASN1_UTCTIME * a)
Definition at line 215 of file a_utctm.c.
References _asn1_mon, BIO_printf(), BIO_write(), h, and if().
Referenced by ASN1_TIME_print().
ASN1_UTCTIME_set()
ASN1_UTCTIME* ASN1_UTCTIME_set (ASN1_UTCTIME * s, time_t t)
Definition at line 131 of file a_utctm.c.
References ASN1_UTCTIME_adj().
ASN1_UTCTIME_set_string()
int ASN1_UTCTIME_set_string (ASN1_UTCTIME * s, const char * str)
Definition at line 113 of file a_utctm.c.
References ASN1_STRING_set(), ASN1_UTCTIME_check(), NULL, t, and V_ASN1_UTCTIME.
BIO_f_asn1()
const BIO_METHOD* BIO_f_asn1 (void)
Definition at line 95 of file bio_asn1.c.
BIO_new_NDEF()
BIO* BIO_new_NDEF (BIO * out, ASN1_VALUE * val, const ASN1_ITEM * it)
Definition at line 52 of file bio_ndef.c.
BN_to_ASN1_ENUMERATED()
ASN1_ENUMERATED* BN_to_ASN1_ENUMERATED (const BIGNUM * bn, ASN1_ENUMERATED * ai)
Definition at line 616 of file a_int.c.
BN_to_ASN1_INTEGER()
ASN1_INTEGER* BN_to_ASN1_INTEGER (const BIGNUM * bn, ASN1_INTEGER * ai)
Definition at line 573 of file a_int.c.
d2i_ASN1_OBJECT()
ASN1_OBJECT* d2i_ASN1_OBJECT (ASN1_OBJECT ** a, const unsigned char ** pp, long length)
Definition at line 198 of file a_object.c.
References len.
d2i_ASN1_UINTEGER()
ASN1_INTEGER* d2i_ASN1_UINTEGER (ASN1_INTEGER ** a, const unsigned char ** pp, long length)
Definition at line 408 of file a_int.c.
DECLARE_ASN1_ENCODE_FUNCTIONS_const()
DECLARE_ASN1_ENCODE_FUNCTIONS_const (ASN1_SEQUENCE_ANY , ASN1_SEQUENCE_ANY)
DECLARE_ASN1_FUNCTIONS_fname()
DECLARE_ASN1_FUNCTIONS_fname (ASN1_TYPE , ASN1_ANY , ASN1_TYPE) const
DECLARE_ASN1_FUNCTIONS_name() [1/2]
DECLARE_ASN1_FUNCTIONS_name (ASN1_STRING , ASN1_PRINTABLE)
DECLARE_ASN1_FUNCTIONS_name() [2/2]
DIRECTORYSTRING DECLARE_ASN1_FUNCTIONS_name (ASN1_STRING , DISPLAYTEXT)
ERR_load_ASN1_strings()
int ERR_load_ASN1_strings (void)
Definition at line 257 of file asn1_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
i2a_ASN1_ENUMERATED()
int i2a_ASN1_ENUMERATED (BIO * bp, const ASN1_ENUMERATED * a)
Definition at line 156 of file f_int.c.
References i2a_ASN1_INTEGER().
i2a_ASN1_INTEGER()
int i2a_ASN1_INTEGER (BIO * bp, const ASN1_INTEGER * a)
Definition at line 16 of file f_int.c.
References h.
Referenced by i2a_ASN1_ENUMERATED().
i2a_ASN1_OBJECT()
int i2a_ASN1_OBJECT (BIO * bp, const ASN1_OBJECT * a)
Definition at line 173 of file a_object.c.
Referenced by print_attribs(), TS_ext_print_bio(), X509_REQ_print_ex(), and X509_signature_print().
i2a_ASN1_STRING()
int i2a_ASN1_STRING (BIO * bp, const ASN1_STRING * a, int type)
Definition at line 16 of file f_string.c.
References h.
i2d_ASN1_bio_stream()
int i2d_ASN1_bio_stream (BIO * out, ASN1_VALUE * val, BIO * in, int flags, const ASN1_ITEM * it)
i2d_ASN1_OBJECT()
int i2d_ASN1_OBJECT (const ASN1_OBJECT * a, unsigned char ** pp)
Definition at line 20 of file a_object.c.
References ASN1_object_size(), ASN1_put_object(), NULL, pp, V_ASN1_OBJECT, and V_ASN1_UNIVERSAL.
i2t_ASN1_OBJECT()
int i2t_ASN1_OBJECT (char * buf, int buf_len, const ASN1_OBJECT * a)
Definition at line 168 of file a_object.c.
Referenced by EVP_PKCS82PKEY().
PEM_write_bio_ASN1_stream()
int PEM_write_bio_ASN1_stream (BIO * out, ASN1_VALUE * val, BIO * in, int flags, const char * hdr, const ASN1_ITEM * it)
Definition at line 121 of file asn_mime.c.
References BIO_printf().
SMIME_crlf_copy()
int SMIME_crlf_copy (BIO * in, BIO * out, int flags)
Definition at line 477 of file asn_mime.c.
References BIO_f_buffer(), BIO_gets(), BIO_new(), BIO_printf(), BIO_push(), BIO_read(), BIO_write(), len, MAX_SMLEN, NULL, SMIME_BINARY, and SMIME_TEXT.
SMIME_read_ASN1()
ASN1_VALUE* SMIME_read_ASN1 (BIO * bio, BIO ** bcont, const ASN1_ITEM * it)
Definition at line 370 of file asn_mime.c.
Referenced by SMIME_read_CMS(), and SMIME_read_PKCS7().
SMIME_text()
int SMIME_text (BIO * in, BIO * out)
Definition at line 524 of file asn_mime.c.
References len.
SMIME_write_ASN1()
int SMIME_write_ASN1 (BIO * bio, ASN1_VALUE * val, BIO * data, int flags, int ctype_nid, int econt_nid, STACK_OF(X509_ALGOR) * mdalgs, const ASN1_ITEM * it)
Definition at line 222 of file asn_mime.c.
Referenced by SMIME_write_CMS(), and SMIME_write_PKCS7().
STACK_OF()
typedef STACK_OF (ASN1_TYPE)
TYPEDEF_D2I2D_OF()
TYPEDEF_D2I2D_OF (void)
UTF8_getc()
int UTF8_getc (const unsigned char * str, int len, unsigned long * val)
Definition at line 27 of file a_utf8.c.
UTF8_putc()
int UTF8_putc (unsigned char * str, int len, unsigned long value)
Definition at line 124 of file a_utf8.c.
Variable Documentation
t
DIRECTORYSTRING time_t t
Definition at line 624 of file asn1.h.
Referenced by ASN1_GENERALIZEDTIME_set_string(), ASN1_TIME_set_string(), ASN1_TYPE_pack_sequence(), ASN1_UTCTIME_set_string(), BN_consttime_swap(), BN_dup(), BN_lshift(), BN_lshift1(), BN_mod_mul(), bn_mul_part_recursive(), bn_mul_recursive(), BN_rshift(), BN_rshift1(), bn_sqr_comba4(), bn_sqr_recursive(), BN_X931_generate_Xpq(), CAST_decrypt(), CAST_encrypt(), DES_encrypt1(), DES_encrypt2(), ec_GF2m_simple_add(), EC_GROUP_dup(), EC_POINT_dup(), EVP_PKEY_asn1_find(), EVP_PKEY_meth_find(), IDEA_set_decrypt_key(), OBJ_find_sigid_by_algs(), OPENSSL_gmtime(), opt_verify(), poly1305_emit(), RC2_decrypt(), RC2_encrypt(), SSL_CTX_flush_sessions(), SSL_CTX_set_timeout(), ssl_load_ciphers(), SSL_SESSION_set_time(), SSL_SESSION_set_timeout(), X509_time_adj_ex(), X509_VERIFY_PARAM_set_time(), and X509V3_EXT_get_nid().