crypto/asn1/asn1_locl.h File Reference
asn1_locl.h File Reference
Data Structures
struct ASN1_SCTX
Functions
int asn1_utctime_to_tm (struct tm *tm, const ASN1_UTCTIME *d)
int asn1_generalizedtime_to_tm (struct tm *tm, const ASN1_GENERALIZEDTIME *d)
void asn1_string_embed_free (ASN1_STRING *a, int embed)
int asn1_get_choice_selector (ASN1_VALUE **pval, const ASN1_ITEM *it)
int asn1_set_choice_selector (ASN1_VALUE **pval, int value, const ASN1_ITEM *it)
ASN1_VALUE ** asn1_get_field_ptr (ASN1_VALUE **pval, const ASN1_TEMPLATE *tt)
const ASN1_TEMPLATE * asn1_do_adb (ASN1_VALUE **pval, const ASN1_TEMPLATE *tt, int nullerr)
int asn1_do_lock (ASN1_VALUE **pval, int op, const ASN1_ITEM *it)
void asn1_enc_init (ASN1_VALUE **pval, const ASN1_ITEM *it)
void asn1_enc_free (ASN1_VALUE **pval, const ASN1_ITEM *it)
int asn1_enc_restore (int *len, unsigned char **out, ASN1_VALUE **pval, const ASN1_ITEM *it)
int asn1_enc_save (ASN1_VALUE **pval, const unsigned char *in, int inlen, const ASN1_ITEM *it)
void asn1_primitive_free (ASN1_VALUE **pval, const ASN1_ITEM *it, int embed)
void asn1_template_free (ASN1_VALUE **pval, const ASN1_TEMPLATE *tt)
ASN1_OBJECT * c2i_ASN1_OBJECT (ASN1_OBJECT **a, const unsigned char **pp, long length)
int i2c_ASN1_BIT_STRING (ASN1_BIT_STRING *a, unsigned char **pp)
ASN1_BIT_STRING * c2i_ASN1_BIT_STRING (ASN1_BIT_STRING **a, const unsigned char **pp, long length)
int i2c_ASN1_INTEGER (ASN1_INTEGER *a, unsigned char **pp)
ASN1_INTEGER * c2i_ASN1_INTEGER (ASN1_INTEGER **a, const unsigned char **pp, long length)
Variables
const char * _asn1_mon [12]
Function Documentation
asn1_do_adb()
const ASN1_TEMPLATE* asn1_do_adb (ASN1_VALUE ** pval, const ASN1_TEMPLATE * tt, int nullerr)
Definition at line 178 of file tasn_utl.c.
References ASN1_ADB, ASN1_ADB_ptr, ASN1_F_ASN1_DO_ADB, ASN1_INTEGER_get(), ASN1_R_UNSUPPORTED_ANY_DEFINED_BY_TYPE, ASN1_TFLG_ADB_MASK, ASN1_TFLG_ADB_OID, ASN1err, NULL, OBJ_obj2nid(), and offset2ptr.
asn1_do_lock()
int asn1_do_lock (ASN1_VALUE ** pval, int op, const ASN1_ITEM * it)
Definition at line 57 of file tasn_utl.c.
asn1_enc_free()
void asn1_enc_free (ASN1_VALUE ** pval, const ASN1_ITEM * it)
Definition at line 114 of file tasn_utl.c.
asn1_enc_init()
void asn1_enc_init (ASN1_VALUE ** pval, const ASN1_ITEM * it)
Definition at line 103 of file tasn_utl.c.
asn1_enc_restore()
int asn1_enc_restore (int * len, unsigned char ** out, ASN1_VALUE ** pval, const ASN1_ITEM * it)
Definition at line 145 of file tasn_utl.c.
asn1_enc_save()
int asn1_enc_save (ASN1_VALUE ** pval, const unsigned char * in, int inlen, const ASN1_ITEM * it)
Definition at line 126 of file tasn_utl.c.
asn1_generalizedtime_to_tm()
int asn1_generalizedtime_to_tm (struct tm * tm, const ASN1_GENERALIZEDTIME * d)
Definition at line 20 of file a_gentm.c.
References if(), max, min, OPENSSL_gmtime_adj(), and V_ASN1_GENERALIZEDTIME.
Referenced by ASN1_GENERALIZEDTIME_check().
asn1_get_choice_selector()
int asn1_get_choice_selector (ASN1_VALUE ** pval, const ASN1_ITEM * it)
Definition at line 28 of file tasn_utl.c.
References offset2ptr.
asn1_get_field_ptr()
ASN1_VALUE** asn1_get_field_ptr (ASN1_VALUE ** pval, const ASN1_TEMPLATE * tt)
Definition at line 162 of file tasn_utl.c.
References offset2ptr.
asn1_primitive_free()
void asn1_primitive_free (ASN1_VALUE ** pval, const ASN1_ITEM * it, int embed)
Definition at line 150 of file tasn_fre.c.
References ASN1_ITYPE_MSTRING, ASN1_OBJECT_free(), asn1_string_embed_free(), ASN1_TYPE::asn1_value, NULL, OPENSSL_free, ASN1_PRIMITIVE_FUNCS::prim_free, ASN1_TYPE::type, V_ASN1_ANY, V_ASN1_BOOLEAN, V_ASN1_NULL, V_ASN1_OBJECT, and ASN1_TYPE::value.
Referenced by ASN1_TYPE_set().
asn1_set_choice_selector()
int asn1_set_choice_selector (ASN1_VALUE ** pval, int value, const ASN1_ITEM * it)
Definition at line 38 of file tasn_utl.c.
asn1_string_embed_free()
void asn1_string_embed_free (ASN1_STRING * a, int embed)
Definition at line 318 of file asn1_lib.c.
References ASN1_STRING_FLAG_NDEF, NULL, and OPENSSL_free.
Referenced by asn1_primitive_free(), and ASN1_STRING_free().
asn1_template_free()
void asn1_template_free (ASN1_VALUE ** pval, const ASN1_TEMPLATE * tt)
Definition at line 126 of file tasn_fre.c.
References ASN1_TFLG_EMBED, ASN1_TFLG_SK_MASK, and STACK_OF.
asn1_utctime_to_tm()
int asn1_utctime_to_tm (struct tm * tm, const ASN1_UTCTIME * d)
Definition at line 16 of file a_utctm.c.
References if(), max, min, OPENSSL_gmtime_adj(), and V_ASN1_UTCTIME.
Referenced by ASN1_UTCTIME_check(), and ASN1_UTCTIME_cmp_time_t().
c2i_ASN1_BIT_STRING()
ASN1_BIT_STRING* c2i_ASN1_BIT_STRING (ASN1_BIT_STRING ** a, const unsigned char ** pp, long length)
Definition at line 78 of file a_bitstr.c.
c2i_ASN1_INTEGER()
ASN1_INTEGER* c2i_ASN1_INTEGER (ASN1_INTEGER ** a, const unsigned char ** pp, long length)
Definition at line 304 of file a_int.c.
c2i_ASN1_OBJECT()
ASN1_OBJECT* c2i_ASN1_OBJECT (ASN1_OBJECT ** a, const unsigned char ** pp, long length)
Definition at line 226 of file a_object.c.
i2c_ASN1_BIT_STRING()
int i2c_ASN1_BIT_STRING (ASN1_BIT_STRING * a, unsigned char ** pp)
Definition at line 20 of file a_bitstr.c.
i2c_ASN1_INTEGER()
int i2c_ASN1_INTEGER (ASN1_INTEGER * a, unsigned char ** pp)
Definition at line 220 of file a_int.c.
Variable Documentation
_asn1_mon
const char* _asn1_mon[12]
Definition at line 218 of file a_gentm.c.
Referenced by ASN1_GENERALIZEDTIME_print(), and ASN1_UTCTIME_print().