crypto/asn1/asn_pack.c File Reference
asn_pack.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
Functions
ASN1_STRING * ASN1_item_pack (void *obj, const ASN1_ITEM *it, ASN1_STRING **oct)
void * ASN1_item_unpack (const ASN1_STRING *oct, const ASN1_ITEM *it)
Function Documentation
ASN1_item_pack()
ASN1_STRING* ASN1_item_pack (void * obj, const ASN1_ITEM * it, ASN1_STRING ** oct)
Definition at line 16 of file asn_pack.c.
References ASN1_F_ASN1_ITEM_PACK, ASN1_item_i2d(), ASN1_R_ENCODE_ERROR, ASN1_STRING_free(), ASN1_STRING_new(), ASN1err, ERR_R_MALLOC_FAILURE, NULL, and OPENSSL_free.
Referenced by ASN1_TYPE_pack_sequence(), cms_encode_Receipt(), OCSP_response_create(), PKCS12_item_pack_safebag(), PKCS12_pack_authsafes(), and PKCS12_pack_p7data().
ASN1_item_unpack()
void* ASN1_item_unpack (const ASN1_STRING * oct, const ASN1_ITEM * it)
Definition at line 53 of file asn_pack.c.
Referenced by ASN1_TYPE_unpack_sequence(), CMS_get1_ReceiptRequest(), cms_Receipt_verify(), OCSP_response_get1_basic(), PKCS12_SAFEBAG_get1_cert(), PKCS12_SAFEBAG_get1_crl(), and STACK_OF().