crypto/asn1/asn_mime.c File Reference
asn_mime.c File Reference
#include <stdio.h>
#include <ctype.h>
#include "internal/cryptlib.h"
#include <openssl/rand.h>
#include <openssl/x509.h>
#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include "internal/evp_int.h"
#include "internal/bio.h"
#include "asn1_locl.h"
Data Structures
struct MIME_PARAM
struct MIME_HEADER
Macros
#define MAX_SMLEN 1024
#define mime_debug(x) /* x */
#define MIME_INVALID 0
#define MIME_START 1
#define MIME_TYPE 2
#define MIME_NAME 3
#define MIME_VALUE 4
#define MIME_QUOTE 5
#define MIME_COMMENT 6
Functions
int PEM_write_bio_ASN1_stream (BIO *out, ASN1_VALUE *val, BIO *in, int flags, const char *hdr, const ASN1_ITEM *it)
int SMIME_write_ASN1 (BIO *bio, ASN1_VALUE *val, BIO *data, int flags, int ctype_nid, int econt_nid, STACK_OF(X509_ALGOR) *mdalgs, const ASN1_ITEM *it)
ASN1_VALUE * SMIME_read_ASN1 (BIO *bio, BIO **bcont, const ASN1_ITEM *it)
int SMIME_crlf_copy (BIO *in, BIO *out, int flags)
int SMIME_text (BIO *in, BIO *out)
Macro Definition Documentation
MAX_SMLEN
#define MAX_SMLEN 1024
Referenced by SMIME_crlf_copy().
MIME_COMMENT
#define MIME_COMMENT 6
Definition at line 621 of file asn_mime.c.
mime_debug
#define mime_debug (x) /* x */
MIME_INVALID
#define MIME_INVALID 0
Definition at line 615 of file asn_mime.c.
MIME_NAME
#define MIME_NAME 3
Definition at line 618 of file asn_mime.c.
MIME_QUOTE
#define MIME_QUOTE 5
Definition at line 620 of file asn_mime.c.
MIME_START
#define MIME_START 1
Definition at line 616 of file asn_mime.c.
MIME_TYPE
#define MIME_TYPE 2
Definition at line 617 of file asn_mime.c.
MIME_VALUE
#define MIME_VALUE 4
Definition at line 619 of file asn_mime.c.
Function Documentation
PEM_write_bio_ASN1_stream()
int PEM_write_bio_ASN1_stream (BIO * out, ASN1_VALUE * val, BIO * in, int flags, const char * hdr, const ASN1_ITEM * it)
Definition at line 121 of file asn_mime.c.
References BIO_printf().
SMIME_crlf_copy()
int SMIME_crlf_copy (BIO * in, BIO * out, int flags)
Definition at line 477 of file asn_mime.c.
References BIO_f_buffer(), BIO_gets(), BIO_new(), BIO_printf(), BIO_push(), BIO_read(), BIO_write(), len, MAX_SMLEN, NULL, SMIME_BINARY, and SMIME_TEXT.
SMIME_read_ASN1()
ASN1_VALUE* SMIME_read_ASN1 (BIO * bio, BIO ** bcont, const ASN1_ITEM * it)
Definition at line 370 of file asn_mime.c.
Referenced by SMIME_read_CMS(), and SMIME_read_PKCS7().
SMIME_text()
int SMIME_text (BIO * in, BIO * out)
Definition at line 524 of file asn_mime.c.
References len.
SMIME_write_ASN1()
int SMIME_write_ASN1 (BIO * bio, ASN1_VALUE * val, BIO * data, int flags, int ctype_nid, int econt_nid, STACK_OF(X509_ALGOR) * mdalgs, const ASN1_ITEM * it)
Definition at line 222 of file asn_mime.c.
Referenced by SMIME_write_CMS(), and SMIME_write_PKCS7().