crypto/async/async.c File Reference
async.c File Reference
#include "async_locl.h"
#include <openssl/err.h>
#include <internal/cryptlib_int.h>
#include <string.h>
Macros
#define ASYNC_JOB_RUNNING 0
#define ASYNC_JOB_PAUSING 1
#define ASYNC_JOB_PAUSED 2
#define ASYNC_JOB_STOPPING 3
Functions
async_ctx * async_get_ctx (void)
void async_start_func (void)
int ASYNC_start_job (ASYNC_JOB **job, ASYNC_WAIT_CTX *wctx, int *ret, int(*func)(void *), void *args, size_t size)
int ASYNC_pause_job (void)
int async_init (void)
void async_deinit (void)
int ASYNC_init_thread (size_t max_size, size_t init_size)
void ASYNC_cleanup_thread (void)
ASYNC_JOB * ASYNC_get_current_job (void)
ASYNC_WAIT_CTX * ASYNC_get_wait_ctx (ASYNC_JOB *job)
void ASYNC_block_pause (void)
void ASYNC_unblock_pause (void)
Macro Definition Documentation
ASYNC_JOB_PAUSED
#define ASYNC_JOB_PAUSED 2
Definition at line 27 of file async.c.
ASYNC_JOB_PAUSING
#define ASYNC_JOB_PAUSING 1
Definition at line 26 of file async.c.
Referenced by ASYNC_pause_job().
ASYNC_JOB_RUNNING
#define ASYNC_JOB_RUNNING 0
Definition at line 25 of file async.c.
ASYNC_JOB_STOPPING
#define ASYNC_JOB_STOPPING 3
Definition at line 28 of file async.c.
Referenced by async_start_func().
Function Documentation
ASYNC_block_pause()
void ASYNC_block_pause (void)
Definition at line 410 of file async.c.
References async_get_ctx(), ctx, and NULL.
ASYNC_cleanup_thread()
void ASYNC_cleanup_thread (void)
Definition at line 389 of file async.c.
async_deinit()
void async_deinit (void)
Definition at line 310 of file async.c.
References CRYPTO_THREAD_cleanup_local().
async_get_ctx()
async_ctx* async_get_ctx (void)
Definition at line 58 of file async.c.
References CRYPTO_THREAD_get_local(), NULL, OPENSSL_INIT_ASYNC, and OPENSSL_init_crypto().
Referenced by ASYNC_block_pause(), ASYNC_get_current_job(), ASYNC_pause_job(), async_start_func(), and ASYNC_unblock_pause().
ASYNC_get_current_job()
ASYNC_JOB* ASYNC_get_current_job (void)
Definition at line 394 of file async.c.
References async_get_ctx(), ctx, and NULL.
Referenced by SSL_peek_ex(), SSL_read_ex(), SSL_shutdown(), and SSL_write_ex().
ASYNC_get_wait_ctx()
ASYNC_WAIT_CTX* ASYNC_get_wait_ctx (ASYNC_JOB * job)
Definition at line 405 of file async.c.
async_init()
int async_init (void)
Definition at line 297 of file async.c.
References CRYPTO_THREAD_init_local().
Referenced by DEFINE_RUN_ONCE_STATIC().
ASYNC_init_thread()
int ASYNC_init_thread (size_t max_size, size_t init_size)
Definition at line 316 of file async.c.
References ASYNC_F_ASYNC_INIT_THREAD, ASYNC_R_INVALID_POOL_SIZE, ASYNCerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_INIT_ASYNC, OPENSSL_init_crypto(), OPENSSL_INIT_THREAD_ASYNC, OPENSSL_zalloc, and ossl_init_thread_start().
ASYNC_pause_job()
int ASYNC_pause_job (void)
Definition at line 255 of file async.c.
References ASYNC_F_ASYNC_PAUSE_JOB, async_fibre_swapcontext, async_get_ctx(), ASYNC_JOB_PAUSING, ASYNC_R_FAILED_TO_SWAP_CONTEXT, async_wait_ctx_reset_counts(), ASYNCerr, ctx, and NULL.
async_start_func()
void async_start_func (void)
Definition at line 146 of file async.c.
References ASYNC_F_ASYNC_START_FUNC, async_fibre_swapcontext, async_get_ctx(), ASYNC_JOB_STOPPING, ASYNC_R_FAILED_TO_SWAP_CONTEXT, ASYNCerr, and ctx.
ASYNC_start_job()
int ASYNC_start_job (ASYNC_JOB ** job, ASYNC_WAIT_CTX * wctx, int * ret, int(*)(void *) func, void * args, size_t size)
Definition at line 169 of file async.c.
ASYNC_unblock_pause()
void ASYNC_unblock_pause (void)
Definition at line 422 of file async.c.
References async_get_ctx(), ctx, and NULL.