crypto/async/async_locl.h File Reference
async_locl.h File Reference
#include <internal/async.h>
#include <openssl/crypto.h>
#include "arch/async_win.h"
#include "arch/async_posix.h"
#include "arch/async_null.h"
Data Structures
struct async_ctx
struct ASYNC_JOB
struct fd_lookup_st
struct ASYNC_WAIT_CTX
struct async_pool
Functions
void async_local_cleanup (void)
void async_start_func (void)
async_ctx * async_get_ctx (void)
void async_wait_ctx_reset_counts (ASYNC_WAIT_CTX *ctx)
Function Documentation
async_get_ctx()
async_ctx* async_get_ctx (void)
Definition at line 58 of file async.c.
References CRYPTO_THREAD_get_local(), NULL, OPENSSL_INIT_ASYNC, and OPENSSL_init_crypto().
Referenced by ASYNC_block_pause(), ASYNC_get_current_job(), ASYNC_pause_job(), async_start_func(), and ASYNC_unblock_pause().
async_local_cleanup()
void async_local_cleanup (void)
Definition at line 19 of file async_null.c.
async_start_func()
void async_start_func (void)
Definition at line 146 of file async.c.
References ASYNC_F_ASYNC_START_FUNC, async_fibre_swapcontext, async_get_ctx(), ASYNC_JOB_STOPPING, ASYNC_R_FAILED_TO_SWAP_CONTEXT, ASYNCerr, and ctx.
async_wait_ctx_reset_counts()
void async_wait_ctx_reset_counts (ASYNC_WAIT_CTX * ctx)
Definition at line 183 of file async_wait.c.
References fd_lookup_st::add, fd_lookup_st::del, fd_lookup_st::next, NULL, and OPENSSL_free.
Referenced by ASYNC_pause_job().