crypto/async/async_wait.c File Reference
async_wait.c File Reference
#include "async_locl.h"
#include <openssl/err.h>
Functions
ASYNC_WAIT_CTX * ASYNC_WAIT_CTX_new (void)
void ASYNC_WAIT_CTX_free (ASYNC_WAIT_CTX *ctx)
int ASYNC_WAIT_CTX_set_wait_fd (ASYNC_WAIT_CTX *ctx, const void *key, OSSL_ASYNC_FD fd, void *custom_data, void(*cleanup)(ASYNC_WAIT_CTX *, const void *, OSSL_ASYNC_FD, void *))
int ASYNC_WAIT_CTX_get_fd (ASYNC_WAIT_CTX *ctx, const void *key, OSSL_ASYNC_FD *fd, void **custom_data)
int ASYNC_WAIT_CTX_get_all_fds (ASYNC_WAIT_CTX *ctx, OSSL_ASYNC_FD *fd, size_t *numfds)
int ASYNC_WAIT_CTX_get_changed_fds (ASYNC_WAIT_CTX *ctx, OSSL_ASYNC_FD *addfd, size_t *numaddfds, OSSL_ASYNC_FD *delfd, size_t *numdelfds)
int ASYNC_WAIT_CTX_clear_fd (ASYNC_WAIT_CTX *ctx, const void *key)
void async_wait_ctx_reset_counts (ASYNC_WAIT_CTX *ctx)
Function Documentation
ASYNC_WAIT_CTX_clear_fd()
int ASYNC_WAIT_CTX_clear_fd (ASYNC_WAIT_CTX * ctx, const void * key)
Definition at line 139 of file async_wait.c.
References fd_lookup_st::add, fd_lookup_st::del, fd_lookup_st::key, fd_lookup_st::next, NULL, and OPENSSL_free.
ASYNC_WAIT_CTX_free()
void ASYNC_WAIT_CTX_free (ASYNC_WAIT_CTX * ctx)
Definition at line 20 of file async_wait.c.
References fd_lookup_st::cleanup, fd_lookup_st::custom_data, fd_lookup_st::del, fd_lookup_st::fd, fd_lookup_st::key, fd_lookup_st::next, NULL, and OPENSSL_free.
ASYNC_WAIT_CTX_get_all_fds()
int ASYNC_WAIT_CTX_get_all_fds (ASYNC_WAIT_CTX * ctx, OSSL_ASYNC_FD * fd, size_t * numfds)
Definition at line 87 of file async_wait.c.
References fd_lookup_st::del, fd_lookup_st::fd, fd_lookup_st::next, and NULL.
Referenced by SSL_get_all_async_fds().
ASYNC_WAIT_CTX_get_changed_fds()
int ASYNC_WAIT_CTX_get_changed_fds (ASYNC_WAIT_CTX * ctx, OSSL_ASYNC_FD * addfd, size_t * numaddfds, OSSL_ASYNC_FD * delfd, size_t * numdelfds)
Definition at line 110 of file async_wait.c.
References fd_lookup_st::add, fd_lookup_st::del, fd_lookup_st::fd, fd_lookup_st::next, and NULL.
Referenced by SSL_get_changed_async_fds().
ASYNC_WAIT_CTX_get_fd()
int ASYNC_WAIT_CTX_get_fd (ASYNC_WAIT_CTX * ctx, const void * key, OSSL_ASYNC_FD * fd, void ** custom_data)
Definition at line 65 of file async_wait.c.
References fd_lookup_st::custom_data, fd_lookup_st::del, fd_lookup_st::fd, fd_lookup_st::key, fd_lookup_st::next, and NULL.
ASYNC_WAIT_CTX_new()
ASYNC_WAIT_CTX* ASYNC_WAIT_CTX_new (void)
Definition at line 15 of file async_wait.c.
References OPENSSL_zalloc.
async_wait_ctx_reset_counts()
void async_wait_ctx_reset_counts (ASYNC_WAIT_CTX * ctx)
Definition at line 183 of file async_wait.c.
References fd_lookup_st::add, fd_lookup_st::del, fd_lookup_st::next, NULL, and OPENSSL_free.
Referenced by ASYNC_pause_job().
ASYNC_WAIT_CTX_set_wait_fd()
int ASYNC_WAIT_CTX_set_wait_fd (ASYNC_WAIT_CTX * ctx, const void * key, OSSL_ASYNC_FD fd, void * custom_data, void(*)(ASYNC_WAIT_CTX *, const void *, OSSL_ASYNC_FD, void *) cleanup)
Definition at line 43 of file async_wait.c.