crypto/bio/b_addr.c File Reference
b_addr.c File Reference
#include <string.h>
#include "bio_lcl.h"
#include <openssl/crypto.h>
#include <openssl/err.h>
#include <openssl/buffer.h>
#include <internal/thread_once.h>
#include <ctype.h>
Functions
BIO_ADDR * BIO_ADDR_new (void)
void BIO_ADDR_free (BIO_ADDR *ap)
void BIO_ADDR_clear (BIO_ADDR *ap)
int BIO_ADDR_make (BIO_ADDR *ap, const struct sockaddr *sa)
int BIO_ADDR_rawmake (BIO_ADDR *ap, int family, const void *where, size_t wherelen, unsigned short port)
int BIO_ADDR_family (const BIO_ADDR *ap)
int BIO_ADDR_rawaddress (const BIO_ADDR *ap, void *p, size_t *l)
unsigned short BIO_ADDR_rawport (const BIO_ADDR *ap)
char * BIO_ADDR_hostname_string (const BIO_ADDR *ap, int numeric)
char * BIO_ADDR_service_string (const BIO_ADDR *ap, int numeric)
char * BIO_ADDR_path_string (const BIO_ADDR *ap)
const struct sockaddr * BIO_ADDR_sockaddr (const BIO_ADDR *ap)
struct sockaddr * BIO_ADDR_sockaddr_noconst (BIO_ADDR *ap)
socklen_t BIO_ADDR_sockaddr_size (const BIO_ADDR *ap)
const BIO_ADDRINFO * BIO_ADDRINFO_next (const BIO_ADDRINFO *bai)
int BIO_ADDRINFO_family (const BIO_ADDRINFO *bai)
int BIO_ADDRINFO_socktype (const BIO_ADDRINFO *bai)
int BIO_ADDRINFO_protocol (const BIO_ADDRINFO *bai)
socklen_t BIO_ADDRINFO_sockaddr_size (const BIO_ADDRINFO *bai)
const struct sockaddr * BIO_ADDRINFO_sockaddr (const BIO_ADDRINFO *bai)
const BIO_ADDR * BIO_ADDRINFO_address (const BIO_ADDRINFO *bai)
void BIO_ADDRINFO_free (BIO_ADDRINFO *bai)
int BIO_parse_hostserv (const char *hostserv, char **host, char **service, enum BIO_hostserv_priorities hostserv_prio)
DEFINE_RUN_ONCE_STATIC (do_bio_lookup_init)
int BIO_lookup (const char *host, const char *service, enum BIO_lookup_type lookup_type, int family, int socktype, BIO_ADDRINFO **res)
Variables
CRYPTO_RWLOCK * bio_lookup_lock
Function Documentation
BIO_ADDR_clear()
void BIO_ADDR_clear (BIO_ADDR * ap)
Definition at line 80 of file b_addr.c.
BIO_ADDR_family()
int BIO_ADDR_family (const BIO_ADDR * ap)
Definition at line 150 of file b_addr.c.
Referenced by BIO_listen().
BIO_ADDR_free()
void BIO_ADDR_free (BIO_ADDR * ap)
Definition at line 75 of file b_addr.c.
References OPENSSL_free.
BIO_ADDR_hostname_string()
char* BIO_ADDR_hostname_string (const BIO_ADDR * ap, int numeric)
Definition at line 288 of file b_addr.c.
References NULL.
BIO_ADDR_make()
int BIO_ADDR_make (BIO_ADDR * ap, const struct sockaddr * sa)
Definition at line 90 of file b_addr.c.
BIO_ADDR_new()
BIO_ADDR* BIO_ADDR_new (void)
Definition at line 62 of file b_addr.c.
Referenced by main().
BIO_ADDR_path_string()
char* BIO_ADDR_path_string (const BIO_ADDR * ap)
Definition at line 308 of file b_addr.c.
References NULL, and OPENSSL_strdup.
BIO_ADDR_rawaddress()
int BIO_ADDR_rawaddress (const BIO_ADDR * ap, void * p, size_t * l)
Definition at line 155 of file b_addr.c.
References len, and NULL.
BIO_ADDR_rawmake()
int BIO_ADDR_rawmake (BIO_ADDR * ap, int family, const void * where, size_t wherelen, unsigned short port)
Definition at line 112 of file b_addr.c.
BIO_ADDR_rawport()
unsigned short BIO_ADDR_rawport (const BIO_ADDR * ap)
Definition at line 189 of file b_addr.c.
BIO_ADDR_service_string()
char* BIO_ADDR_service_string (const BIO_ADDR * ap, int numeric)
Definition at line 298 of file b_addr.c.
References NULL.
BIO_ADDR_sockaddr()
const struct sockaddr* BIO_ADDR_sockaddr (const BIO_ADDR * ap)
Definition at line 322 of file b_addr.c.
Referenced by BIO_connect(), and BIO_listen().
BIO_ADDR_sockaddr_noconst()
struct sockaddr* BIO_ADDR_sockaddr_noconst (BIO_ADDR * ap)
Definition at line 333 of file b_addr.c.
Referenced by BIO_accept_ex().
BIO_ADDR_sockaddr_size()
socklen_t BIO_ADDR_sockaddr_size (const BIO_ADDR * ap)
Definition at line 344 of file b_addr.c.
Referenced by BIO_connect(), and BIO_listen().
BIO_ADDRINFO_address()
const BIO_ADDR* BIO_ADDRINFO_address (const BIO_ADDRINFO * bai)
Definition at line 431 of file b_addr.c.
References NULL.
Referenced by BIO_get_accept_socket().
BIO_ADDRINFO_family()
int BIO_ADDRINFO_family (const BIO_ADDRINFO * bai)
Definition at line 372 of file b_addr.c.
References NULL.
Referenced by BIO_get_accept_socket().
BIO_ADDRINFO_free()
void BIO_ADDRINFO_free (BIO_ADDRINFO * bai)
Definition at line 438 of file b_addr.c.
References NULL, and OPENSSL_free.
Referenced by BIO_CONNECT_free(), and BIO_get_accept_socket().
BIO_ADDRINFO_next()
const BIO_ADDRINFO* BIO_ADDRINFO_next (const BIO_ADDRINFO * bai)
Definition at line 365 of file b_addr.c.
References NULL.
BIO_ADDRINFO_protocol()
int BIO_ADDRINFO_protocol (const BIO_ADDRINFO * bai)
Definition at line 386 of file b_addr.c.
References NULL.
Referenced by BIO_get_accept_socket().
BIO_ADDRINFO_sockaddr()
const struct sockaddr* BIO_ADDRINFO_sockaddr (const BIO_ADDRINFO * bai)
Definition at line 424 of file b_addr.c.
References NULL.
BIO_ADDRINFO_sockaddr_size()
socklen_t BIO_ADDRINFO_sockaddr_size (const BIO_ADDRINFO * bai)
Definition at line 413 of file b_addr.c.
References NULL.
BIO_ADDRINFO_socktype()
int BIO_ADDRINFO_socktype (const BIO_ADDRINFO * bai)
Definition at line 379 of file b_addr.c.
References NULL.
Referenced by BIO_get_accept_socket().
BIO_lookup()
int BIO_lookup (const char * host, const char * service, enum BIO_lookup_type lookup_type, int family, int socktype, BIO_ADDRINFO ** res)
Definition at line 654 of file b_addr.c.
Referenced by BIO_get_accept_socket().
BIO_parse_hostserv()
int BIO_parse_hostserv (const char * hostserv, char ** host, char ** service, enum BIO_hostserv_priorities hostserv_prio)
Definition at line 491 of file b_addr.c.
References BIO_F_BIO_PARSE_HOSTSERV, BIO_PARSE_PRIO_HOST, BIO_R_AMBIGUOUS_HOST_OR_SERVICE, BIO_R_MALFORMED_HOST_OR_SERVICE, BIOerr, ERR_R_MALLOC_FAILURE, h, NULL, and OPENSSL_strndup.
Referenced by BIO_get_accept_socket().
DEFINE_RUN_ONCE_STATIC()
DEFINE_RUN_ONCE_STATIC (do_bio_lookup_init)
Definition at line 629 of file b_addr.c.
References CRYPTO_THREAD_lock_new(), NULL, and OPENSSL_init_crypto().
Variable Documentation
bio_lookup_lock
CRYPTO_RWLOCK* bio_lookup_lock
Definition at line 45 of file b_addr.c.
Referenced by bio_cleanup().