crypto/bio/b_dump.c File Reference
b_dump.c File Reference
#include <stdio.h>
#include "bio_lcl.h"
Macros
#define TRUNCATE
#define DUMP_WIDTH 16
#define DUMP_WIDTH_LESS_INDENT(i) (DUMP_WIDTH-((i-(i>6?6:i)+3)/4))
Functions
int BIO_dump_cb (int(*cb)(const void *data, size_t len, void *u), void *u, const char *s, int len)
int BIO_dump_indent_cb (int(*cb)(const void *data, size_t len, void *u), void *u, const char *s, int len, int indent)
int BIO_dump_fp (FILE *fp, const char *s, int len)
int BIO_dump_indent_fp (FILE *fp, const char *s, int len, int indent)
int BIO_dump (BIO *bp, const char *s, int len)
int BIO_dump_indent (BIO *bp, const char *s, int len, int indent)
int BIO_hex_string (BIO *out, int indent, int width, unsigned char *data, int datalen)
Macro Definition Documentation
DUMP_WIDTH
#define DUMP_WIDTH 16
Definition at line 18 of file b_dump.c.
DUMP_WIDTH_LESS_INDENT
#define DUMP_WIDTH_LESS_INDENT (i) (DUMP_WIDTH-((i-(i>6?6:i)+3)/4))
Definition at line 19 of file b_dump.c.
TRUNCATE
#define TRUNCATE
Definition at line 17 of file b_dump.c.
Function Documentation
BIO_dump()
int BIO_dump (BIO * bp, const char * s, int len)
Definition at line 125 of file b_dump.c.
References BIO_dump_cb().
BIO_dump_cb()
int BIO_dump_cb (int(*)(const void *data, size_t len, void *u) cb, void * u, const char * s, int len)
Definition at line 21 of file b_dump.c.
References BIO_dump_indent_cb(), and cb.
Referenced by BIO_dump(), and BIO_dump_fp().
BIO_dump_fp()
int BIO_dump_fp (FILE * fp, const char * s, int len)
Definition at line 109 of file b_dump.c.
References BIO_dump_cb().
Referenced by aes_ccm_decrypt(), aes_ccm_encrypt(), aes_gcm_decrypt(), aes_gcm_encrypt(), and tls1_generate_master_secret().
BIO_dump_indent()
int BIO_dump_indent (BIO * bp, const char * s, int len, int indent)
Definition at line 130 of file b_dump.c.
References BIO_dump_indent_cb().
Referenced by SSL_SESSION_print().
BIO_dump_indent_cb()
int BIO_dump_indent_cb (int(*)(const void *data, size_t len, void *u) cb, void * u, const char * s, int len, int indent)
Definition at line 27 of file b_dump.c.
Referenced by BIO_dump_cb(), BIO_dump_indent(), and BIO_dump_indent_fp().
BIO_dump_indent_fp()
int BIO_dump_indent_fp (FILE * fp, const char * s, int len, int indent)
Definition at line 114 of file b_dump.c.
References BIO_dump_indent_cb().
BIO_hex_string()
int BIO_hex_string (BIO * out, int indent, int width, unsigned char * data, int datalen)
Definition at line 135 of file b_dump.c.
Referenced by SCT_print().