crypto/bio/b_print.c File Reference
b_print.c File Reference
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "internal/numbers.h"
#include "internal/cryptlib.h"
#include <sys/types.h>
#include <openssl/bn.h>
#include <openssl/bio.h>
Macros
#define LDOUBLE double
#define LLONG long
#define DP_S_DEFAULT 0
#define DP_S_FLAGS 1
#define DP_S_MIN 2
#define DP_S_DOT 3
#define DP_S_MAX 4
#define DP_S_MOD 5
#define DP_S_CONV 6
#define DP_S_DONE 7
#define DP_F_MINUS (1 << 0)
#define DP_F_PLUS (1 << 1)
#define DP_F_SPACE (1 << 2)
#define DP_F_NUM (1 << 3)
#define DP_F_ZERO (1 << 4)
#define DP_F_UP (1 << 5)
#define DP_F_UNSIGNED (1 << 6)
#define DP_C_SHORT 1
#define DP_C_LONG 2
#define DP_C_LDOUBLE 3
#define DP_C_LLONG 4
#define F_FORMAT 0
#define E_FORMAT 1
#define G_FORMAT 2
#define char_to_int(p) (p - '0')
#define OSSL_MAX(p, q) ((p >= q) ? p : q)
#define BUFFER_INC 1024
Functions
int BIO_printf (BIO *bio, const char *format,...)
int BIO_vprintf (BIO *bio, const char *format, va_list args)
int BIO_snprintf (char *buf, size_t n, const char *format,...)
int BIO_vsnprintf (char *buf, size_t n, const char *format, va_list args)
Macro Definition Documentation
BUFFER_INC
#define BUFFER_INC 1024
Definition at line 820 of file b_print.c.
char_to_int
#define char_to_int (p) (p - '0')
Definition at line 99 of file b_print.c.
DP_C_LDOUBLE
#define DP_C_LDOUBLE 3
Definition at line 90 of file b_print.c.
DP_C_LLONG
#define DP_C_LLONG 4
Definition at line 91 of file b_print.c.
DP_C_LONG
#define DP_C_LONG 2
Definition at line 89 of file b_print.c.
DP_C_SHORT
#define DP_C_SHORT 1
Definition at line 88 of file b_print.c.
DP_F_MINUS
#define DP_F_MINUS (1 << 0)
Definition at line 73 of file b_print.c.
DP_F_NUM
#define DP_F_NUM (1 << 3)
Definition at line 79 of file b_print.c.
DP_F_PLUS
#define DP_F_PLUS (1 << 1)
Definition at line 75 of file b_print.c.
DP_F_SPACE
#define DP_F_SPACE (1 << 2)
Definition at line 77 of file b_print.c.
DP_F_UNSIGNED
#define DP_F_UNSIGNED (1 << 6)
Definition at line 85 of file b_print.c.
DP_F_UP
#define DP_F_UP (1 << 5)
Definition at line 83 of file b_print.c.
DP_F_ZERO
#define DP_F_ZERO (1 << 4)
Definition at line 81 of file b_print.c.
DP_S_CONV
#define DP_S_CONV 6
Definition at line 68 of file b_print.c.
DP_S_DEFAULT
#define DP_S_DEFAULT 0
Definition at line 62 of file b_print.c.
DP_S_DONE
#define DP_S_DONE 7
Definition at line 69 of file b_print.c.
DP_S_DOT
#define DP_S_DOT 3
Definition at line 65 of file b_print.c.
DP_S_FLAGS
#define DP_S_FLAGS 1
Definition at line 63 of file b_print.c.
DP_S_MAX
#define DP_S_MAX 4
Definition at line 66 of file b_print.c.
DP_S_MIN
#define DP_S_MIN 2
Definition at line 64 of file b_print.c.
DP_S_MOD
#define DP_S_MOD 5
Definition at line 67 of file b_print.c.
E_FORMAT
#define E_FORMAT 1
Definition at line 95 of file b_print.c.
F_FORMAT
#define F_FORMAT 0
Definition at line 94 of file b_print.c.
G_FORMAT
#define G_FORMAT 2
Definition at line 96 of file b_print.c.
LDOUBLE
#define LDOUBLE double
Definition at line 37 of file b_print.c.
LLONG
#define LLONG long
Definition at line 47 of file b_print.c.
OSSL_MAX
#define OSSL_MAX (p, q) ((p >= q) ? p : q)
Definition at line 100 of file b_print.c.
Function Documentation
BIO_printf()
int BIO_printf (BIO * bio, const char * format, ...)
Definition at line 867 of file b_print.c.
Referenced by app_malloc(), ASN1_GENERALIZEDTIME_print(), ASN1_UTCTIME_print(), index_index(), load_excert(), load_key(), load_pubkey(), OCSP_REQ_CTX_http(), OCSP_REQ_CTX_i2d(), OCSP_REQUEST_print(), opt_cipher(), opt_format_error(), opt_int(), opt_long(), opt_md(), opt_pair(), opt_ulong(), opt_verify(), parse_name(), PEM_write_bio_ASN1_stream(), policies_print(), print_attribs(), print_cert_checks(), process_responder(), rehash_main(), SCT_LIST_print(), SCT_print(), set_cert_stuff(), SMIME_crlf_copy(), ssl_print_groups(), ssl_print_point_formats(), ssl_print_tmp_key(), SSL_SESSION_print(), SSL_SESSION_print_keylog(), TS_ext_print_bio(), TS_OBJ_print_bio(), TS_REQ_print_bio(), TS_RESP_print_bio(), TS_STATUS_INFO_print_bio(), TS_TST_INFO_print_bio(), TS_X509_ALGOR_print_bio(), verify_callback(), X509_ocspid_print(), X509_REQ_print_ex(), and X509_signature_dump().
BIO_snprintf()
int BIO_snprintf (char * buf, size_t n, const char * format, ...)
Definition at line 913 of file b_print.c.
Referenced by ASN1_GENERALIZEDTIME_adj(), ASN1_UTCTIME_adj(), PEM_write_bio_Parameters(), PEM_write_bio_PrivateKey_traditional(), and UI_set_result().
BIO_vprintf()
int BIO_vprintf (BIO * bio, const char * format, va_list args)
Definition at line 880 of file b_print.c.
BIO_vsnprintf()
int BIO_vsnprintf (char * buf, size_t n, const char * format, va_list args)
Definition at line 926 of file b_print.c.