crypto/bio/b_sock.c File Reference
b_sock.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include "bio_lcl.h"
Macros
#define SOCKET_PROTOCOL IPPROTO_TCP
#define MAX_LISTEN 32
#define ARG arg
Functions
int BIO_get_host_ip (const char *str, unsigned char *ip)
int BIO_get_port (const char *str, unsigned short *port_ptr)
int BIO_sock_error (int sock)
struct hostent * BIO_gethostbyname (const char *name)
int BIO_sock_init (void)
void bio_sock_cleanup_int (void)
int BIO_socket_ioctl (int fd, long type, void *arg)
int BIO_get_accept_socket (char *host, int bind_mode)
int BIO_accept (int sock, char **ip_port)
int BIO_set_tcp_ndelay (int s, int on)
int BIO_socket_nbio (int s, int mode)
int BIO_sock_info (int sock, enum BIO_sock_info_type type, union BIO_sock_info_u *info)
Macro Definition Documentation
ARG
#define ARG arg
MAX_LISTEN
#define MAX_LISTEN 32
Definition at line 25 of file b_sock.c.
SOCKET_PROTOCOL
#define SOCKET_PROTOCOL IPPROTO_TCP
Definition at line 19 of file b_sock.c.
Function Documentation
BIO_accept()
int BIO_accept (int sock, char ** ip_port)
Definition at line 247 of file b_sock.c.
BIO_get_accept_socket()
int BIO_get_accept_socket (char * host, int bind_mode)
Definition at line 212 of file b_sock.c.
References BIO_ADDRINFO_address(), BIO_ADDRINFO_family(), BIO_ADDRINFO_free(), BIO_ADDRINFO_protocol(), BIO_ADDRINFO_socktype(), BIO_closesocket(), BIO_listen(), BIO_lookup(), BIO_LOOKUP_SERVER, BIO_parse_hostserv(), BIO_PARSE_PRIO_SERV, BIO_sock_init(), BIO_SOCK_REUSEADDR, BIO_socket(), h, NULL, and OPENSSL_free.
BIO_get_host_ip()
int BIO_get_host_ip (const char * str, unsigned char * ip)
Definition at line 32 of file b_sock.c.
References NULL.
BIO_get_port()
int BIO_get_port (const char * str, unsigned short * port_ptr)
Definition at line 63 of file b_sock.c.
References NULL.
BIO_gethostbyname()
struct hostent* BIO_gethostbyname (const char * name)
Definition at line 112 of file b_sock.c.
BIO_set_tcp_ndelay()
int BIO_set_tcp_ndelay (int s, int on)
Definition at line 289 of file b_sock.c.
bio_sock_cleanup_int()
void bio_sock_cleanup_int (void)
Definition at line 160 of file b_sock.c.
Referenced by bio_cleanup().
BIO_sock_error()
int BIO_sock_error (int sock)
Definition at line 93 of file b_sock.c.
References get_last_socket_error.
BIO_sock_info()
int BIO_sock_info (int sock, enum BIO_sock_info_type type, union BIO_sock_info_u * info)
Definition at line 352 of file b_sock.c.
References BIO_SOCK_INFO_ADDRESS.
BIO_sock_init()
int BIO_sock_init (void)
Definition at line 126 of file b_sock.c.
References BIO_F_BIO_SOCK_INIT, BIO_R_WSASTARTUP, BIOerr, SYS_F_WSASTARTUP, and SYSerr.
Referenced by BIO_get_accept_socket(), and BIO_socket().
BIO_socket_ioctl()
int BIO_socket_ioctl (int fd, long type, void * arg)
Definition at line 172 of file b_sock.c.
BIO_socket_nbio()
int BIO_socket_nbio (int s, int mode)
Definition at line 308 of file b_sock.c.
Referenced by BIO_accept_ex(), BIO_connect(), and BIO_listen().