crypto/bio/b_sock2.c File Reference
b_sock2.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include "bio_lcl.h"
#include <openssl/err.h>
Macros
#define MAX_LISTEN 32
Functions
int BIO_socket (int domain, int socktype, int protocol, int options)
int BIO_connect (int sock, const BIO_ADDR *addr, int options)
int BIO_listen (int sock, const BIO_ADDR *addr, int options)
int BIO_accept_ex (int accept_sock, BIO_ADDR *addr_, int options)
int BIO_closesocket (int sock)
Macro Definition Documentation
MAX_LISTEN
#define MAX_LISTEN 32
Definition at line 24 of file b_sock2.c.
Referenced by BIO_listen().
Function Documentation
BIO_accept_ex()
int BIO_accept_ex (int accept_sock, BIO_ADDR * addr_, int options)
Definition at line 234 of file b_sock2.c.
References BIO_ADDR_sockaddr_noconst(), BIO_F_BIO_ACCEPT_EX, BIO_R_ACCEPT_ERROR, BIO_SOCK_NONBLOCK, BIO_sock_should_retry(), BIO_socket_nbio(), BIOerr, closesocket, get_last_socket_error, len, NULL, SYS_F_ACCEPT, and SYSerr.
BIO_closesocket()
int BIO_closesocket (int sock)
Definition at line 264 of file b_sock2.c.
References closesocket.
Referenced by BIO_get_accept_socket().
BIO_connect()
int BIO_connect (int sock, const BIO_ADDR * addr, int options)
Definition at line 77 of file b_sock2.c.
References BIO_ADDR_sockaddr(), BIO_ADDR_sockaddr_size(), BIO_F_BIO_CONNECT, BIO_R_CONNECT_ERROR, BIO_R_INVALID_SOCKET, BIO_R_UNABLE_TO_KEEPALIVE, BIO_R_UNABLE_TO_NODELAY, BIO_SOCK_KEEPALIVE, BIO_SOCK_NODELAY, BIO_SOCK_NONBLOCK, BIO_sock_should_retry(), BIO_socket_nbio(), BIOerr, get_last_socket_error, SYS_F_CONNECT, SYS_F_SETSOCKOPT, and SYSerr.
BIO_listen()
int BIO_listen (int sock, const BIO_ADDR * addr, int options)
Definition at line 153 of file b_sock2.c.
References BIO_ADDR_family(), BIO_ADDR_sockaddr(), BIO_ADDR_sockaddr_size(), BIO_F_BIO_LISTEN, BIO_R_GETTING_SOCKTYPE, BIO_R_INVALID_SOCKET, BIO_R_LISTEN_V6_ONLY, BIO_R_UNABLE_TO_BIND_SOCKET, BIO_R_UNABLE_TO_KEEPALIVE, BIO_R_UNABLE_TO_LISTEN_SOCKET, BIO_R_UNABLE_TO_NODELAY, BIO_R_UNABLE_TO_REUSEADDR, BIO_SOCK_KEEPALIVE, BIO_SOCK_NODELAY, BIO_SOCK_NONBLOCK, BIO_SOCK_REUSEADDR, BIO_SOCK_V6_ONLY, BIO_socket_nbio(), BIOerr, get_last_socket_error, MAX_LISTEN, SYS_F_BIND, SYS_F_GETSOCKOPT, SYS_F_LISTEN, SYS_F_SETSOCKOPT, and SYSerr.
Referenced by BIO_get_accept_socket().
BIO_socket()
int BIO_socket (int domain, int socktype, int protocol, int options)
Definition at line 40 of file b_sock2.c.
References BIO_F_BIO_SOCKET, BIO_R_UNABLE_TO_CREATE_SOCKET, BIO_sock_init(), BIOerr, get_last_socket_error, SYS_F_SOCKET, and SYSerr.
Referenced by BIO_get_accept_socket().