crypto/bio/bio_lib.c File Reference
bio_lib.c File Reference
#include <stdio.h>
#include <errno.h>
#include <openssl/crypto.h>
#include "bio_lcl.h"
#include "internal/cryptlib.h"
Macros
#define HAS_LEN_OPER(o)
Functions
BIO * BIO_new (const BIO_METHOD *method)
int BIO_free (BIO *a)
void BIO_set_data (BIO *a, void *ptr)
void * BIO_get_data (BIO *a)
void BIO_set_init (BIO *a, int init)
int BIO_get_init (BIO *a)
void BIO_set_shutdown (BIO *a, int shut)
int BIO_get_shutdown (BIO *a)
void BIO_vfree (BIO *a)
int BIO_up_ref (BIO *a)
void BIO_clear_flags (BIO *b, int flags)
int BIO_test_flags (const BIO *b, int flags)
void BIO_set_flags (BIO *b, int flags)
BIO_callback_fn BIO_get_callback (const BIO *b)
void BIO_set_callback (BIO *b, BIO_callback_fn cb)
BIO_callback_fn_ex BIO_get_callback_ex (const BIO *b)
void BIO_set_callback_ex (BIO *b, BIO_callback_fn_ex cb)
void BIO_set_callback_arg (BIO *b, char *arg)
char * BIO_get_callback_arg (const BIO *b)
const char * BIO_method_name (const BIO *b)
int BIO_method_type (const BIO *b)
int BIO_read (BIO *b, void *data, int dlen)
int BIO_read_ex (BIO *b, void *data, size_t dlen, size_t *readbytes)
int BIO_write (BIO *b, const void *data, int dlen)
int BIO_write_ex (BIO *b, const void *data, size_t dlen, size_t *written)
int BIO_puts (BIO *b, const char *buf)
int BIO_gets (BIO *b, char *buf, int size)
int BIO_indent (BIO *b, int indent, int max)
long BIO_int_ctrl (BIO *b, int cmd, long larg, int iarg)
void * BIO_ptr_ctrl (BIO *b, int cmd, long larg)
long BIO_ctrl (BIO *b, int cmd, long larg, void *parg)
long BIO_callback_ctrl (BIO *b, int cmd, void(*fp)(struct bio_st *, int, const char *, int, long, long))
size_t BIO_ctrl_pending (BIO *bio)
size_t BIO_ctrl_wpending (BIO *bio)
BIO * BIO_push (BIO *b, BIO *bio)
BIO * BIO_pop (BIO *b)
BIO * BIO_get_retry_BIO (BIO *bio, int *reason)
int BIO_get_retry_reason (BIO *bio)
void BIO_set_retry_reason (BIO *bio, int reason)
BIO * BIO_find_type (BIO *bio, int type)
BIO * BIO_next (BIO *b)
void BIO_set_next (BIO *b, BIO *next)
void BIO_free_all (BIO *bio)
BIO * BIO_dup_chain (BIO *in)
void BIO_copy_next_retry (BIO *b)
int BIO_set_ex_data (BIO *bio, int idx, void *data)
void * BIO_get_ex_data (BIO *bio, int idx)
uint64_t BIO_number_read (BIO *bio)
uint64_t BIO_number_written (BIO *bio)
void bio_free_ex_data (BIO *bio)
void bio_cleanup (void)
Macro Definition Documentation
HAS_LEN_OPER
#define HAS_LEN_OPER (o)
Value:
((o) == BIO_CB_READ || (o) == BIO_CB_WRITE || \
                                (o) == BIO_CB_GETS)
Definition at line 21 of file bio_lib.c.
Function Documentation
BIO_callback_ctrl()
long BIO_callback_ctrl (BIO * b, int cmd, void(*)(struct bio_st *, int, const char *, int, long, long) fp)
Definition at line 536 of file bio_lib.c.
bio_cleanup()
void bio_cleanup (void)
Definition at line 777 of file bio_lib.c.
References bio_lookup_lock, bio_sock_cleanup_int(), bio_type_lock, CRYPTO_THREAD_lock_free(), and NULL.
BIO_clear_flags()
void BIO_clear_flags (BIO * b, int flags)
Definition at line 189 of file bio_lib.c.
BIO_copy_next_retry()
void BIO_copy_next_retry (BIO * b)
Definition at line 742 of file bio_lib.c.
References BIO_get_retry_flags, and BIO_set_flags().
BIO_ctrl()
long BIO_ctrl (BIO * b, int cmd, long larg, void * parg)
Definition at line 509 of file bio_lib.c.
Referenced by BIO_ctrl_get_read_request(), BIO_ctrl_get_write_guarantee(), BIO_ctrl_pending(), BIO_ctrl_reset_read_request(), BIO_ctrl_wpending(), BIO_int_ctrl(), BIO_ptr_ctrl(), BIO_push(), dtls1_buffer_record(), dtls1_check_timeout_num(), dtls1_query_mtu(), dtls1_stop_timer(), ossl_statem_client_post_work(), ossl_statem_server_post_work(), tls_client_key_exchange_post_work(), and tls_post_process_client_key_exchange().
BIO_ctrl_pending()
size_t BIO_ctrl_pending (BIO * bio)
Definition at line 571 of file bio_lib.c.
References BIO_ctrl(), BIO_CTRL_PENDING, and NULL.
BIO_ctrl_wpending()
size_t BIO_ctrl_wpending (BIO * bio)
Definition at line 576 of file bio_lib.c.
References BIO_ctrl(), BIO_CTRL_WPENDING, and NULL.
BIO_dup_chain()
BIO* BIO_dup_chain (BIO * in)
Definition at line 698 of file bio_lib.c.
BIO_find_type()
BIO* BIO_find_type (BIO * bio, int type)
Definition at line 648 of file bio_lib.c.
References NULL.
Referenced by BIO_ssl_copy_session_id(), BIO_ssl_shutdown(), CMS_dataFinal(), cms_DigestAlgorithm_find_ctx(), and PKCS7_signatureVerify().
BIO_free()
int BIO_free (BIO * a)
Definition at line 109 of file bio_lib.c.
Referenced by BIO_free_all(), BIO_vfree(), CMS_dataInit(), cms_DigestAlgorithm_init_bio(), CMS_sign_receipt(), create_ssl_objects(), FuzzerCleanup(), LHASH_OF(), OCSP_REQ_CTX_free(), OPENSSL_LH_node_stats(), OPENSSL_LH_node_usage_stats(), OPENSSL_LH_stats(), ssl3_free_digest_list(), ssl_free_wbio_buffer(), ssl_init_wbio_buffer(), STACK_OF(), TS_CONF_load_key(), and X509_load_cert_crl_file().
BIO_free_all()
void BIO_free_all (BIO * bio)
Definition at line 682 of file bio_lib.c.
References BIO_free(), and NULL.
Referenced by set_keylog_file(), SSL_set0_rbio(), SSL_set0_wbio(), and TS_VERIFY_CTX_cleanup().
bio_free_ex_data()
void bio_free_ex_data (BIO * bio)
Definition at line 772 of file bio_lib.c.
References CRYPTO_EX_INDEX_BIO, and CRYPTO_free_ex_data().
Referenced by CRYPTO_mem_leaks().
BIO_get_callback()
BIO_callback_fn BIO_get_callback (const BIO * b)
Definition at line 204 of file bio_lib.c.
BIO_get_callback_arg()
char* BIO_get_callback_arg (const BIO * b)
Definition at line 229 of file bio_lib.c.
BIO_get_callback_ex()
BIO_callback_fn_ex BIO_get_callback_ex (const BIO * b)
Definition at line 214 of file bio_lib.c.
BIO_get_data()
void* BIO_get_data (BIO * a)
Definition at line 147 of file bio_lib.c.
Referenced by BIO_ssl_copy_session_id(), BIO_ssl_shutdown(), comp_zlib_cleanup_int(), and mempacket_test_inject().
BIO_get_ex_data()
void* BIO_get_ex_data (BIO * bio, int idx)
Definition at line 753 of file bio_lib.c.
BIO_get_init()
int BIO_get_init (BIO * a)
Definition at line 157 of file bio_lib.c.
BIO_get_retry_BIO()
BIO* BIO_get_retry_BIO (BIO * bio, int * reason)
Definition at line 620 of file bio_lib.c.
References BIO_should_retry, and NULL.
BIO_get_retry_reason()
int BIO_get_retry_reason (BIO * bio)
Definition at line 638 of file bio_lib.c.
Referenced by SSL_get_error().
BIO_get_shutdown()
int BIO_get_shutdown (BIO * a)
Definition at line 167 of file bio_lib.c.
BIO_gets()
int BIO_gets (BIO * b, char * buf, int size)
Definition at line 431 of file bio_lib.c.
Referenced by OCSP_REQ_CTX_nbio(), and SMIME_crlf_copy().
BIO_indent()
int BIO_indent (BIO * b, int indent, int max)
Definition at line 479 of file bio_lib.c.
References BIO_puts(), and max.
Referenced by X509_signature_dump().
BIO_int_ctrl()
long BIO_int_ctrl (BIO * b, int cmd, long larg, int iarg)
Definition at line 491 of file bio_lib.c.
References BIO_ctrl().
BIO_method_name()
const char* BIO_method_name (const BIO * b)
Definition at line 234 of file bio_lib.c.
BIO_method_type()
int BIO_method_type (const BIO * b)
Definition at line 239 of file bio_lib.c.
Referenced by BIO_dgram_is_sctp(), SSL_set_rfd(), and SSL_set_wfd().
BIO_new()
BIO* BIO_new (const BIO_METHOD * method)
Definition at line 72 of file bio_lib.c.
References BIO_F_BIO_NEW, BIOerr, CRYPTO_EX_INDEX_BIO, CRYPTO_free_ex_data(), CRYPTO_new_ex_data(), CRYPTO_THREAD_lock_free(), CRYPTO_THREAD_lock_new(), ERR_R_INIT_FAIL, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, and OPENSSL_zalloc.
Referenced by cms_content_bio(), cms_DigestAlgorithm_init_bio(), create_ssl_objects(), OCSP_REQ_CTX_new(), OPENSSL_LH_node_stats(), OPENSSL_LH_node_usage_stats(), OPENSSL_LH_stats(), SMIME_crlf_copy(), SRP_VBASE_init(), ssl3_init_finished_mac(), ssl_init_wbio_buffer(), SSL_set_rfd(), and SSL_set_wfd().
BIO_next()
BIO* BIO_next (BIO * b)
Definition at line 670 of file bio_lib.c.
References NULL.
Referenced by cms_DigestAlgorithm_find_ctx(), PKCS7_signatureVerify(), and SSL_get_wbio().
BIO_number_read()
uint64_t BIO_number_read (BIO * bio)
Definition at line 758 of file bio_lib.c.
BIO_number_written()
uint64_t BIO_number_written (BIO * bio)
Definition at line 765 of file bio_lib.c.
BIO_pop()
BIO* BIO_pop (BIO * b)
Definition at line 600 of file bio_lib.c.
Referenced by ssl_free_wbio_buffer(), and SSL_set0_wbio().
BIO_ptr_ctrl()
void* BIO_ptr_ctrl (BIO * b, int cmd, long larg)
Definition at line 499 of file bio_lib.c.
References BIO_ctrl(), and NULL.
BIO_push()
BIO* BIO_push (BIO * b, BIO * bio)
Definition at line 582 of file bio_lib.c.
References BIO_ctrl(), BIO_CTRL_PUSH, and NULL.
Referenced by CMS_dataInit(), create_ssl_objects(), process_responder(), SMIME_crlf_copy(), ssl_init_wbio_buffer(), and SSL_set0_wbio().
BIO_puts()
int BIO_puts (BIO * b, const char * buf)
Definition at line 386 of file bio_lib.c.
Referenced by BIO_indent(), OCSP_REQ_CTX_add1_header(), ssl_print_groups(), ssl_print_point_formats(), ssl_print_tmp_key(), SSL_SESSION_print(), SSL_SESSION_print_keylog(), TS_STATUS_INFO_print_bio(), verify_callback(), X509_REQ_print_ex(), and X509_signature_print().
BIO_read()
int BIO_read (BIO * b, void * data, int dlen)
Definition at line 287 of file bio_lib.c.
Referenced by b2i_PVK_bio(), OCSP_REQ_CTX_nbio(), and SMIME_crlf_copy().
BIO_read_ex()
int BIO_read_ex (BIO * b, void * data, size_t dlen, size_t * readbytes)
Definition at line 305 of file bio_lib.c.
BIO_set_callback()
void BIO_set_callback (BIO * b, BIO_callback_fn cb)
Definition at line 209 of file bio_lib.c.
References cb.
BIO_set_callback_arg()
void BIO_set_callback_arg (BIO * b, char * arg)
Definition at line 224 of file bio_lib.c.
BIO_set_callback_ex()
void BIO_set_callback_ex (BIO * b, BIO_callback_fn_ex cb)
Definition at line 219 of file bio_lib.c.
References cb.
BIO_set_data()
void BIO_set_data (BIO * a, void * ptr)
Definition at line 142 of file bio_lib.c.
References ptr.
Referenced by comp_zlib_cleanup_int().
BIO_set_ex_data()
int BIO_set_ex_data (BIO * bio, int idx, void * data)
Definition at line 748 of file bio_lib.c.
BIO_set_flags()
void BIO_set_flags (BIO * b, int flags)
Definition at line 199 of file bio_lib.c.
References flags.
Referenced by BIO_copy_next_retry(), CMS_dataFinal(), and dtls1_read_failed().
BIO_set_init()
void BIO_set_init (BIO * a, int init)
Definition at line 152 of file bio_lib.c.
Referenced by comp_zlib_cleanup_int().
BIO_set_next()
void BIO_set_next (BIO * b, BIO * next)
Definition at line 677 of file bio_lib.c.
BIO_set_retry_reason()
void BIO_set_retry_reason (BIO * bio, int reason)
Definition at line 643 of file bio_lib.c.
BIO_set_shutdown()
void BIO_set_shutdown (BIO * a, int shut)
Definition at line 162 of file bio_lib.c.
BIO_test_flags()
int BIO_test_flags (const BIO * b, int flags)
Definition at line 194 of file bio_lib.c.
BIO_up_ref()
int BIO_up_ref (BIO * a)
Definition at line 177 of file bio_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by create_ssl_objects(), SSL_set_bio(), SSL_set_rfd(), and SSL_set_wfd().
BIO_vfree()
void BIO_vfree (BIO * a)
Definition at line 172 of file bio_lib.c.
References BIO_free().
BIO_write()
int BIO_write (BIO * b, const void * data, int dlen)
Definition at line 354 of file bio_lib.c.
Referenced by ASN1_GENERALIZEDTIME_print(), ASN1_TIME_print(), ASN1_UTCTIME_print(), OCSP_REQ_CTX_add1_header(), OCSP_REQ_CTX_nbio(), OCSP_REQUEST_print(), SMIME_crlf_copy(), TS_ASN1_INTEGER_print_bio(), TS_ext_print_bio(), TS_REQ_print_bio(), TS_TST_INFO_print_bio(), X509_REQ_print_ex(), and X509_signature_dump().
BIO_write_ex()
int BIO_write_ex (BIO * b, const void * data, size_t dlen, size_t * written)
Definition at line 372 of file bio_lib.c.