crypto/bio/bio_lcl.h File Reference
bio_lcl.h File Reference
#include "e_os.h"
#include "internal/refcount.h"
#include "internal/cryptlib.h"
#include <internal/bio.h>
Data Structures
struct BIO_ADDRINFO
union BIO_ADDR
struct BIO_F_BUFFER_CTX
struct BIO
Macros
#define USE_SOCKETS
#define UP_stdin stdin
#define UP_stdout stdout
#define UP_stderr stderr
#define UP_fprintf fprintf
#define UP_fgets fgets
#define UP_fread fread
#define UP_fwrite fwrite
#define UP_feof feof
#define UP_fclose fclose
#define UP_fopen fopen
#define UP_fseek fseek
#define UP_ftell ftell
#define UP_fflush fflush
#define UP_ferror ferror
#define UP_fileno fileno
#define UP_open open
#define UP_read read
#define UP_write write
#define UP_lseek lseek
#define UP_close close
Functions
int BIO_ADDR_make (BIO_ADDR *ap, const struct sockaddr *sa)
const struct sockaddr * BIO_ADDR_sockaddr (const BIO_ADDR *ap)
struct sockaddr * BIO_ADDR_sockaddr_noconst (BIO_ADDR *ap)
socklen_t BIO_ADDR_sockaddr_size (const BIO_ADDR *ap)
socklen_t BIO_ADDRINFO_sockaddr_size (const BIO_ADDRINFO *bai)
const struct sockaddr * BIO_ADDRINFO_sockaddr (const BIO_ADDRINFO *bai)
void bio_sock_cleanup_int (void)
Variables
CRYPTO_RWLOCK * bio_lookup_lock
CRYPTO_RWLOCK * bio_type_lock
Macro Definition Documentation
UP_close
#define UP_close close
Definition at line 186 of file bio_lcl.h.
UP_fclose
#define UP_fclose fclose
Definition at line 166 of file bio_lcl.h.
UP_feof
#define UP_feof feof
Definition at line 165 of file bio_lcl.h.
UP_ferror
#define UP_ferror ferror
Definition at line 172 of file bio_lcl.h.
UP_fflush
#define UP_fflush fflush
Definition at line 171 of file bio_lcl.h.
UP_fgets
#define UP_fgets fgets
Definition at line 161 of file bio_lcl.h.
UP_fileno
#define UP_fileno fileno
Definition at line 181 of file bio_lcl.h.
UP_fopen
#define UP_fopen fopen
Definition at line 168 of file bio_lcl.h.
UP_fprintf
#define UP_fprintf fprintf
Definition at line 160 of file bio_lcl.h.
UP_fread
#define UP_fread fread
Definition at line 162 of file bio_lcl.h.
UP_fseek
#define UP_fseek fseek
Definition at line 169 of file bio_lcl.h.
UP_ftell
#define UP_ftell ftell
Definition at line 170 of file bio_lcl.h.
UP_fwrite
#define UP_fwrite fwrite
Definition at line 163 of file bio_lcl.h.
UP_lseek
#define UP_lseek lseek
Definition at line 185 of file bio_lcl.h.
UP_open
#define UP_open open
Definition at line 182 of file bio_lcl.h.
UP_read
#define UP_read read
Definition at line 183 of file bio_lcl.h.
UP_stderr
#define UP_stderr stderr
Definition at line 159 of file bio_lcl.h.
UP_stdin
#define UP_stdin stdin
Definition at line 157 of file bio_lcl.h.
UP_stdout
#define UP_stdout stdout
Definition at line 158 of file bio_lcl.h.
UP_write
#define UP_write write
Definition at line 184 of file bio_lcl.h.
USE_SOCKETS
#define USE_SOCKETS
Definition at line 10 of file bio_lcl.h.
Function Documentation
BIO_ADDR_make()
int BIO_ADDR_make (BIO_ADDR * ap, const struct sockaddr * sa)
Definition at line 90 of file b_addr.c.
BIO_ADDR_sockaddr()
const struct sockaddr* BIO_ADDR_sockaddr (const BIO_ADDR * ap)
Definition at line 322 of file b_addr.c.
Referenced by BIO_connect(), and BIO_listen().
BIO_ADDR_sockaddr_noconst()
struct sockaddr* BIO_ADDR_sockaddr_noconst (BIO_ADDR * ap)
Definition at line 333 of file b_addr.c.
Referenced by BIO_accept_ex().
BIO_ADDR_sockaddr_size()
socklen_t BIO_ADDR_sockaddr_size (const BIO_ADDR * ap)
Definition at line 344 of file b_addr.c.
Referenced by BIO_connect(), and BIO_listen().
BIO_ADDRINFO_sockaddr()
const struct sockaddr* BIO_ADDRINFO_sockaddr (const BIO_ADDRINFO * bai)
Definition at line 424 of file b_addr.c.
References NULL.
BIO_ADDRINFO_sockaddr_size()
socklen_t BIO_ADDRINFO_sockaddr_size (const BIO_ADDRINFO * bai)
Definition at line 413 of file b_addr.c.
References NULL.
bio_sock_cleanup_int()
void bio_sock_cleanup_int (void)
Definition at line 160 of file b_sock.c.
Referenced by bio_cleanup().
Variable Documentation
bio_lookup_lock
CRYPTO_RWLOCK* bio_lookup_lock
Definition at line 45 of file b_addr.c.
Referenced by bio_cleanup().
bio_type_lock
CRYPTO_RWLOCK* bio_type_lock
Definition at line 13 of file bio_meth.c.
Referenced by bio_cleanup(), and DEFINE_RUN_ONCE_STATIC().