ssl/bio_ssl.c File Reference
bio_ssl.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <openssl/crypto.h>
#include "internal/bio.h"
#include <openssl/err.h>
#include "ssl_locl.h"
Data Structures
struct BIO_SSL
Functions
const BIO_METHOD * BIO_f_ssl (void)
BIO * BIO_new_buffer_ssl_connect (SSL_CTX *ctx)
BIO * BIO_new_ssl_connect (SSL_CTX *ctx)
BIO * BIO_new_ssl (SSL_CTX *ctx, int client)
int BIO_ssl_copy_session_id (BIO *t, BIO *f)
void BIO_ssl_shutdown (BIO *b)
Function Documentation
BIO_f_ssl()
const BIO_METHOD* BIO_f_ssl (void)
Definition at line 50 of file bio_ssl.c.
BIO_new_buffer_ssl_connect()
BIO* BIO_new_buffer_ssl_connect (SSL_CTX * ctx)
Definition at line 442 of file bio_ssl.c.
BIO_new_ssl()
BIO* BIO_new_ssl (SSL_CTX * ctx, int client)
Definition at line 479 of file bio_ssl.c.
Referenced by process_responder().
BIO_new_ssl_connect()
BIO* BIO_new_ssl_connect (SSL_CTX * ctx)
Definition at line 461 of file bio_ssl.c.
BIO_ssl_copy_session_id()
int BIO_ssl_copy_session_id (BIO * t, BIO * f)
Definition at line 499 of file bio_ssl.c.
References BIO_find_type(), BIO_get_data(), BIO_TYPE_SSL, NULL, BIO_SSL::ssl, and SSL_copy_session_id().
BIO_ssl_shutdown()
void BIO_ssl_shutdown (BIO * b)
Definition at line 515 of file bio_ssl.c.
References BIO_find_type(), BIO_get_data(), BIO_TYPE_SSL, NULL, and SSL_shutdown().