crypto/bio/bio_meth.c File Reference
bio_meth.c File Reference
#include "bio_lcl.h"
#include <internal/thread_once.h>
Functions
DEFINE_RUN_ONCE_STATIC (do_bio_type_init)
int BIO_get_new_index ()
BIO_METHOD * BIO_meth_new (int type, const char *name)
void BIO_meth_free (BIO_METHOD *biom)
int bwrite_conv (BIO *bio, const char *data, size_t datal, size_t *written)
int BIO_meth_set_write (BIO_METHOD *biom, int(*bwrite)(BIO *, const char *, int))
int BIO_meth_set_write_ex (BIO_METHOD *biom, int(*bwrite)(BIO *, const char *, size_t, size_t *))
int bread_conv (BIO *bio, char *data, size_t datal, size_t *readbytes)
int BIO_meth_set_read (BIO_METHOD *biom, int(*bread)(BIO *, char *, int))
int BIO_meth_set_read_ex (BIO_METHOD *biom, int(*bread)(BIO *, char *, size_t, size_t *))
int BIO_meth_set_puts (BIO_METHOD *biom, int(*bputs)(BIO *, const char *))
int BIO_meth_set_gets (BIO_METHOD *biom, int(*bgets)(BIO *, char *, int))
int BIO_meth_set_ctrl (BIO_METHOD *biom, long(*ctrl)(BIO *, int, long, void *))
int BIO_meth_set_create (BIO_METHOD *biom, int(*create)(BIO *))
int BIO_meth_set_destroy (BIO_METHOD *biom, int(*destroy)(BIO *))
int BIO_meth_set_callback_ctrl (BIO_METHOD *biom, long(*callback_ctrl)(BIO *, int, bio_info_cb *))
Variables
CRYPTO_RWLOCK * bio_type_lock = NULL
int(*)(BIO *, const char *, int) BIO_meth_get_write (BIO_METHOD *biom)
int(*)(BIO *, const char *, size_t, size_t *) BIO_meth_get_write_ex (BIO_METHOD *biom)
int(*)(BIO *, char *, int) BIO_meth_get_read (BIO_METHOD *biom)
int(*)(BIO *, char *, size_t, size_t *) BIO_meth_get_read_ex (BIO_METHOD *biom)
int(*)(BIO *, const char *) BIO_meth_get_puts (BIO_METHOD *biom)
int(*)(BIO *, char *, int) BIO_meth_get_gets (BIO_METHOD *biom)
long(*)(BIO *, int, long, void *) BIO_meth_get_ctrl (BIO_METHOD *biom)
int(*)(BIO *) BIO_meth_get_create (BIO_METHOD *biom)
int(*)(BIO *) BIO_meth_get_destroy (BIO_METHOD *biom)
long(*)(BIO *, int, bio_info_cb *) BIO_meth_get_callback_ctrl (BIO_METHOD *biom)
Function Documentation
BIO_get_new_index()
int BIO_get_new_index (void)
Definition at line 22 of file bio_meth.c.
References BIO_TYPE_START, and RUN_ONCE.
BIO_meth_free()
void BIO_meth_free (BIO_METHOD * biom)
Definition at line 47 of file bio_meth.c.
References OPENSSL_free.
Referenced by bio_f_tls_dump_filter_free(), and bio_s_mempacket_test_free().
BIO_meth_new()
BIO_METHOD* BIO_meth_new (int type, const char * name)
Definition at line 36 of file bio_meth.c.
References NULL, OPENSSL_zalloc, and type.
BIO_meth_set_callback_ctrl()
int BIO_meth_set_callback_ctrl (BIO_METHOD * biom, long(*)(BIO *, int, bio_info_cb *) callback_ctrl)
Definition at line 208 of file bio_meth.c.
BIO_meth_set_create()
int BIO_meth_set_create (BIO_METHOD * biom, int(*)(BIO *) create)
Definition at line 186 of file bio_meth.c.
BIO_meth_set_ctrl()
int BIO_meth_set_ctrl (BIO_METHOD * biom, long(*)(BIO *, int, long, void *) ctrl)
Definition at line 174 of file bio_meth.c.
BIO_meth_set_destroy()
int BIO_meth_set_destroy (BIO_METHOD * biom, int(*)(BIO *) destroy)
Definition at line 197 of file bio_meth.c.
BIO_meth_set_gets()
int BIO_meth_set_gets (BIO_METHOD * biom, int(*)(BIO *, char *, int) bgets)
Definition at line 162 of file bio_meth.c.
BIO_meth_set_puts()
int BIO_meth_set_puts (BIO_METHOD * biom, int(*)(BIO *, const char *) bputs)
Definition at line 150 of file bio_meth.c.
BIO_meth_set_read()
int BIO_meth_set_read (BIO_METHOD * biom, int(*)(BIO *, char *, int) bread)
Definition at line 129 of file bio_meth.c.
References bread_conv().
BIO_meth_set_read_ex()
int BIO_meth_set_read_ex (BIO_METHOD * biom, int(*)(BIO *, char *, size_t, size_t *) bread)
Definition at line 137 of file bio_meth.c.
References NULL.
BIO_meth_set_write()
int BIO_meth_set_write (BIO_METHOD * biom, int(*)(BIO *, const char *, int) bwrite)
Definition at line 83 of file bio_meth.c.
References bwrite_conv().
BIO_meth_set_write_ex()
int BIO_meth_set_write_ex (BIO_METHOD * biom, int(*)(BIO *, const char *, size_t, size_t *) bwrite)
Definition at line 91 of file bio_meth.c.
References NULL.
bread_conv()
int bread_conv (BIO * bio, char * data, size_t datal, size_t * readbytes)
Definition at line 110 of file bio_meth.c.
Referenced by BIO_meth_set_read(), and comp_zlib_cleanup_int().
bwrite_conv()
int bwrite_conv (BIO * bio, const char * data, size_t datal, size_t * written)
Definition at line 64 of file bio_meth.c.
Referenced by BIO_meth_set_write(), and comp_zlib_cleanup_int().
DEFINE_RUN_ONCE_STATIC()
DEFINE_RUN_ONCE_STATIC (do_bio_type_init)
Definition at line 16 of file bio_meth.c.
References bio_type_lock, CRYPTO_THREAD_lock_new(), and NULL.
Variable Documentation
BIO_meth_get_callback_ctrl
long(*)(BIO *, int, bio_info_cb *) BIO_meth_get_callback_ctrl(BIO_METHOD *biom)
Definition at line 203 of file bio_meth.c.
BIO_meth_get_create
int(*)(BIO *) BIO_meth_get_create(BIO_METHOD *biom)
Definition at line 181 of file bio_meth.c.
BIO_meth_get_ctrl
long(*)(BIO *, int, long, void *) BIO_meth_get_ctrl(BIO_METHOD *biom)
Definition at line 169 of file bio_meth.c.
BIO_meth_get_destroy
int(*)(BIO *) BIO_meth_get_destroy(BIO_METHOD *biom)
Definition at line 192 of file bio_meth.c.
BIO_meth_get_gets
int(*)(BIO *, char *, int) BIO_meth_get_gets(BIO_METHOD *biom)
Definition at line 157 of file bio_meth.c.
BIO_meth_get_puts
int(*)(BIO *, const char *) BIO_meth_get_puts(BIO_METHOD *biom)
Definition at line 145 of file bio_meth.c.
BIO_meth_get_read
int(*)(BIO *, char *, int) BIO_meth_get_read(BIO_METHOD *biom)
Definition at line 99 of file bio_meth.c.
BIO_meth_get_read_ex
int(*)(BIO *, char *, size_t, size_t *) BIO_meth_get_read_ex(BIO_METHOD *biom)
Definition at line 104 of file bio_meth.c.
BIO_meth_get_write
int(*)(BIO *, const char *, int) BIO_meth_get_write(BIO_METHOD *biom)
Definition at line 52 of file bio_meth.c.
BIO_meth_get_write_ex
int(*)(BIO *, const char *, size_t, size_t *) BIO_meth_get_write_ex(BIO_METHOD *biom)
Definition at line 57 of file bio_meth.c.
bio_type_lock
CRYPTO_RWLOCK* bio_type_lock = NULL
Definition at line 13 of file bio_meth.c.
Referenced by bio_cleanup(), and DEFINE_RUN_ONCE_STATIC().