include/openssl/bn.h File Reference
bn.h File Reference
#include <openssl/e_os2.h>
#include <stdio.h>
#include <openssl/opensslconf.h>
#include <openssl/ossl_typ.h>
#include <openssl/crypto.h>
Macros
#define BN_BITS2 (BN_BYTES * 8)
#define BN_BITS (BN_BITS2 * 2)
#define BN_TBIT ((BN_ULONG)1 << (BN_BITS2 - 1))
#define BN_FLG_MALLOCED 0x01
#define BN_FLG_STATIC_DATA 0x02
#define BN_FLG_CONSTTIME 0x04
#define BN_FLG_SECURE 0x08
#define BN_FLG_EXP_CONSTTIME BN_FLG_CONSTTIME
#define BN_FLG_FREE 0x8000 /* used for debugging */
#define BN_RAND_TOP_ANY -1
#define BN_RAND_TOP_ONE 0
#define BN_RAND_TOP_TWO 1
#define BN_RAND_BOTTOM_ANY 0
#define BN_RAND_BOTTOM_ODD 1
#define BN_prime_checks
#define BN_prime_checks_for_size(b)
#define BN_num_bytes(a) ((BN_num_bits(a)+7)/8)
#define BN_one(a) (BN_set_word((a),1))
#define BN_zero(a) (BN_set_word((a),0))
#define BN_mod(rem, m, d, ctx) BN_div(NULL,(rem),(m),(d),(ctx))
#define BN_BLINDING_NO_UPDATE 0x00000001
#define BN_BLINDING_NO_RECREATE 0x00000002
#define BN_GF2m_sub(r, a, b) BN_GF2m_add(r, a, b)
#define BN_GF2m_cmp(a, b) BN_ucmp((a), (b))
#define get_rfc2409_prime_768 BN_get_rfc2409_prime_768
#define get_rfc2409_prime_1024 BN_get_rfc2409_prime_1024
#define get_rfc3526_prime_1536 BN_get_rfc3526_prime_1536
#define get_rfc3526_prime_2048 BN_get_rfc3526_prime_2048
#define get_rfc3526_prime_3072 BN_get_rfc3526_prime_3072
#define get_rfc3526_prime_4096 BN_get_rfc3526_prime_4096
#define get_rfc3526_prime_6144 BN_get_rfc3526_prime_6144
#define get_rfc3526_prime_8192 BN_get_rfc3526_prime_8192
#define BN_F_BNRAND 127
#define BN_F_BN_BLINDING_CONVERT_EX 100
#define BN_F_BN_BLINDING_CREATE_PARAM 128
#define BN_F_BN_BLINDING_INVERT_EX 101
#define BN_F_BN_BLINDING_NEW 102
#define BN_F_BN_BLINDING_UPDATE 103
#define BN_F_BN_BN2DEC 104
#define BN_F_BN_BN2HEX 105
#define BN_F_BN_COMPUTE_WNAF 142
#define BN_F_BN_CTX_GET 116
#define BN_F_BN_CTX_NEW 106
#define BN_F_BN_CTX_START 129
#define BN_F_BN_DIV 107
#define BN_F_BN_DIV_RECP 130
#define BN_F_BN_EXP 123
#define BN_F_BN_EXPAND_INTERNAL 120
#define BN_F_BN_GENCB_NEW 143
#define BN_F_BN_GENERATE_DSA_NONCE 140
#define BN_F_BN_GENERATE_PRIME_EX 141
#define BN_F_BN_GF2M_MOD 131
#define BN_F_BN_GF2M_MOD_EXP 132
#define BN_F_BN_GF2M_MOD_MUL 133
#define BN_F_BN_GF2M_MOD_SOLVE_QUAD 134
#define BN_F_BN_GF2M_MOD_SOLVE_QUAD_ARR 135
#define BN_F_BN_GF2M_MOD_SQR 136
#define BN_F_BN_GF2M_MOD_SQRT 137
#define BN_F_BN_LSHIFT 145
#define BN_F_BN_MOD_EXP2_MONT 118
#define BN_F_BN_MOD_EXP_MONT 109
#define BN_F_BN_MOD_EXP_MONT_CONSTTIME 124
#define BN_F_BN_MOD_EXP_MONT_WORD 117
#define BN_F_BN_MOD_EXP_RECP 125
#define BN_F_BN_MOD_EXP_SIMPLE 126
#define BN_F_BN_MOD_INVERSE 110
#define BN_F_BN_MOD_INVERSE_NO_BRANCH 139
#define BN_F_BN_MOD_LSHIFT_QUICK 119
#define BN_F_BN_MOD_SQRT 121
#define BN_F_BN_MPI2BN 112
#define BN_F_BN_NEW 113
#define BN_F_BN_RAND 114
#define BN_F_BN_RAND_RANGE 122
#define BN_F_BN_RSHIFT 146
#define BN_F_BN_SET_WORDS 144
#define BN_F_BN_USUB 115
#define BN_R_ARG2_LT_ARG3 100
#define BN_R_BAD_RECIPROCAL 101
#define BN_R_BIGNUM_TOO_LONG 114
#define BN_R_BITS_TOO_SMALL 118
#define BN_R_CALLED_WITH_EVEN_MODULUS 102
#define BN_R_DIV_BY_ZERO 103
#define BN_R_ENCODING_ERROR 104
#define BN_R_EXPAND_ON_STATIC_BIGNUM_DATA 105
#define BN_R_INPUT_NOT_REDUCED 110
#define BN_R_INVALID_LENGTH 106
#define BN_R_INVALID_RANGE 115
#define BN_R_INVALID_SHIFT 119
#define BN_R_NOT_A_SQUARE 111
#define BN_R_NOT_INITIALIZED 107
#define BN_R_NO_INVERSE 108
#define BN_R_NO_SOLUTION 116
#define BN_R_PRIVATE_KEY_TOO_LARGE 117
#define BN_R_P_IS_NOT_PRIME 112
#define BN_R_TOO_MANY_ITERATIONS 113
#define BN_R_TOO_MANY_TEMPORARY_VARIABLES 109
Functions
void BN_set_flags (BIGNUM *b, int n)
int BN_get_flags (const BIGNUM *b, int n)
void BN_with_flags (BIGNUM *dest, const BIGNUM *b, int flags)
int BN_GENCB_call (BN_GENCB *cb, int a, int b)
BN_GENCB * BN_GENCB_new (void)
void BN_GENCB_free (BN_GENCB *cb)
void BN_GENCB_set_old (BN_GENCB *gencb, void(*callback)(int, int, void *), void *cb_arg)
void BN_GENCB_set (BN_GENCB *gencb, int(*callback)(int, int, BN_GENCB *), void *cb_arg)
void * BN_GENCB_get_arg (BN_GENCB *cb)
int BN_abs_is_word (const BIGNUM *a, const BN_ULONG w)
int BN_is_zero (const BIGNUM *a)
int BN_is_one (const BIGNUM *a)
int BN_is_word (const BIGNUM *a, const BN_ULONG w)
int BN_is_odd (const BIGNUM *a)
void BN_zero_ex (BIGNUM *a)
const BIGNUM * BN_value_one (void)
char * BN_options (void)
BN_CTX * BN_CTX_new (void)
BN_CTX * BN_CTX_secure_new (void)
void BN_CTX_free (BN_CTX *c)
void BN_CTX_start (BN_CTX *ctx)
BIGNUM * BN_CTX_get (BN_CTX *ctx)
void BN_CTX_end (BN_CTX *ctx)
int BN_rand (BIGNUM *rnd, int bits, int top, int bottom)
int BN_pseudo_rand (BIGNUM *rnd, int bits, int top, int bottom)
int BN_rand_range (BIGNUM *rnd, const BIGNUM *range)
int BN_pseudo_rand_range (BIGNUM *rnd, const BIGNUM *range)
int BN_num_bits (const BIGNUM *a)
int BN_num_bits_word (BN_ULONG l)
int BN_security_bits (int L, int N)
BIGNUM * BN_new (void)
BIGNUM * BN_secure_new (void)
void BN_clear_free (BIGNUM *a)
BIGNUM * BN_copy (BIGNUM *a, const BIGNUM *b)
void BN_swap (BIGNUM *a, BIGNUM *b)
BIGNUM * BN_bin2bn (const unsigned char *s, int len, BIGNUM *ret)
int BN_bn2bin (const BIGNUM *a, unsigned char *to)
int BN_bn2binpad (const BIGNUM *a, unsigned char *to, int tolen)
BIGNUM * BN_lebin2bn (const unsigned char *s, int len, BIGNUM *ret)
int BN_bn2lebinpad (const BIGNUM *a, unsigned char *to, int tolen)
BIGNUM * BN_mpi2bn (const unsigned char *s, int len, BIGNUM *ret)
int BN_bn2mpi (const BIGNUM *a, unsigned char *to)
int BN_sub (BIGNUM *r, const BIGNUM *a, const BIGNUM *b)
int BN_usub (BIGNUM *r, const BIGNUM *a, const BIGNUM *b)
int BN_uadd (BIGNUM *r, const BIGNUM *a, const BIGNUM *b)
int BN_add (BIGNUM *r, const BIGNUM *a, const BIGNUM *b)
int BN_mul (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int BN_sqr (BIGNUM *r, const BIGNUM *a, BN_CTX *ctx)
void BN_set_negative (BIGNUM *b, int n)
int BN_is_negative (const BIGNUM *b)
int BN_div (BIGNUM *dv, BIGNUM *rem, const BIGNUM *m, const BIGNUM *d, BN_CTX *ctx)
int BN_nnmod (BIGNUM *r, const BIGNUM *m, const BIGNUM *d, BN_CTX *ctx)
int BN_mod_add (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *m, BN_CTX *ctx)
int BN_mod_add_quick (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *m)
int BN_mod_sub (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *m, BN_CTX *ctx)
int BN_mod_sub_quick (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *m)
int BN_mod_mul (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *m, BN_CTX *ctx)
int BN_mod_sqr (BIGNUM *r, const BIGNUM *a, const BIGNUM *m, BN_CTX *ctx)
int BN_mod_lshift1 (BIGNUM *r, const BIGNUM *a, const BIGNUM *m, BN_CTX *ctx)
int BN_mod_lshift1_quick (BIGNUM *r, const BIGNUM *a, const BIGNUM *m)
int BN_mod_lshift (BIGNUM *r, const BIGNUM *a, int n, const BIGNUM *m, BN_CTX *ctx)
int BN_mod_lshift_quick (BIGNUM *r, const BIGNUM *a, int n, const BIGNUM *m)
BN_ULONG BN_mod_word (const BIGNUM *a, BN_ULONG w)
BN_ULONG BN_div_word (BIGNUM *a, BN_ULONG w)
int BN_mul_word (BIGNUM *a, BN_ULONG w)
int BN_add_word (BIGNUM *a, BN_ULONG w)
int BN_sub_word (BIGNUM *a, BN_ULONG w)
int BN_set_word (BIGNUM *a, BN_ULONG w)
BN_ULONG BN_get_word (const BIGNUM *a)
int BN_cmp (const BIGNUM *a, const BIGNUM *b)
void BN_free (BIGNUM *a)
int BN_is_bit_set (const BIGNUM *a, int n)
int BN_lshift (BIGNUM *r, const BIGNUM *a, int n)
int BN_lshift1 (BIGNUM *r, const BIGNUM *a)
int BN_exp (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, BN_CTX *ctx)
int BN_mod_exp (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx)
int BN_mod_exp_mont (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *m_ctx)
int BN_mod_exp_mont_consttime (BIGNUM *rr, const BIGNUM *a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *in_mont)
int BN_mod_exp_mont_word (BIGNUM *r, BN_ULONG a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *m_ctx)
int BN_mod_exp2_mont (BIGNUM *r, const BIGNUM *a1, const BIGNUM *p1, const BIGNUM *a2, const BIGNUM *p2, const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *m_ctx)
int BN_mod_exp_simple (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx)
int BN_mask_bits (BIGNUM *a, int n)
int BN_print_fp (FILE *fp, const BIGNUM *a)
int BN_print (BIO *bio, const BIGNUM *a)
int BN_reciprocal (BIGNUM *r, const BIGNUM *m, int len, BN_CTX *ctx)
int BN_rshift (BIGNUM *r, const BIGNUM *a, int n)
int BN_rshift1 (BIGNUM *r, const BIGNUM *a)
void BN_clear (BIGNUM *a)
BIGNUM * BN_dup (const BIGNUM *a)
int BN_ucmp (const BIGNUM *a, const BIGNUM *b)
int BN_set_bit (BIGNUM *a, int n)
int BN_clear_bit (BIGNUM *a, int n)
char * BN_bn2hex (const BIGNUM *a)
char * BN_bn2dec (const BIGNUM *a)
int BN_hex2bn (BIGNUM **a, const char *str)
int BN_dec2bn (BIGNUM **a, const char *str)
int BN_asc2bn (BIGNUM **a, const char *str)
int BN_gcd (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int BN_kronecker (const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
BIGNUM * BN_mod_inverse (BIGNUM *ret, const BIGNUM *a, const BIGNUM *n, BN_CTX *ctx)
BIGNUM * BN_mod_sqrt (BIGNUM *ret, const BIGNUM *a, const BIGNUM *n, BN_CTX *ctx)
void BN_consttime_swap (BN_ULONG swap, BIGNUM *a, BIGNUM *b, int nwords)
DEPRECATEDIN_0_9_8 (BIGNUM *BN_generate_prime(BIGNUM *ret, int bits, int safe, const BIGNUM *add, const BIGNUM *rem, void(*callback)(int, int, void *), void *cb_arg)) DEPRECATEDIN_0_9_8(int BN_is_prime(const BIGNUM *p
int BN_is_prime_ex (const BIGNUM *p, int nchecks, BN_CTX *ctx, BN_GENCB *cb)
int BN_is_prime_fasttest_ex (const BIGNUM *p, int nchecks, BN_CTX *ctx, int do_trial_division, BN_GENCB *cb)
int BN_X931_generate_Xpq (BIGNUM *Xp, BIGNUM *Xq, int nbits, BN_CTX *ctx)
int BN_X931_derive_prime_ex (BIGNUM *p, BIGNUM *p1, BIGNUM *p2, const BIGNUM *Xp, const BIGNUM *Xp1, const BIGNUM *Xp2, const BIGNUM *e, BN_CTX *ctx, BN_GENCB *cb)
int BN_X931_generate_prime_ex (BIGNUM *p, BIGNUM *p1, BIGNUM *p2, BIGNUM *Xp1, BIGNUM *Xp2, const BIGNUM *Xp, const BIGNUM *e, BN_CTX *ctx, BN_GENCB *cb)
BN_MONT_CTX * BN_MONT_CTX_new (void)
int BN_mod_mul_montgomery (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_MONT_CTX *mont, BN_CTX *ctx)
int BN_to_montgomery (BIGNUM *r, const BIGNUM *a, BN_MONT_CTX *mont, BN_CTX *ctx)
int BN_from_montgomery (BIGNUM *r, const BIGNUM *a, BN_MONT_CTX *mont, BN_CTX *ctx)
void BN_MONT_CTX_free (BN_MONT_CTX *mont)
int BN_MONT_CTX_set (BN_MONT_CTX *mont, const BIGNUM *mod, BN_CTX *ctx)
BN_MONT_CTX * BN_MONT_CTX_copy (BN_MONT_CTX *to, BN_MONT_CTX *from)
BN_MONT_CTX * BN_MONT_CTX_set_locked (BN_MONT_CTX **pmont, CRYPTO_RWLOCK *lock, const BIGNUM *mod, BN_CTX *ctx)
BN_BLINDING * BN_BLINDING_new (const BIGNUM *A, const BIGNUM *Ai, BIGNUM *mod)
void BN_BLINDING_free (BN_BLINDING *b)
int BN_BLINDING_update (BN_BLINDING *b, BN_CTX *ctx)
int BN_BLINDING_convert (BIGNUM *n, BN_BLINDING *b, BN_CTX *ctx)
int BN_BLINDING_invert (BIGNUM *n, BN_BLINDING *b, BN_CTX *ctx)
int BN_BLINDING_convert_ex (BIGNUM *n, BIGNUM *r, BN_BLINDING *b, BN_CTX *)
int BN_BLINDING_invert_ex (BIGNUM *n, const BIGNUM *r, BN_BLINDING *b, BN_CTX *)
int BN_BLINDING_is_current_thread (BN_BLINDING *b)
void BN_BLINDING_set_current_thread (BN_BLINDING *b)
int BN_BLINDING_lock (BN_BLINDING *b)
int BN_BLINDING_unlock (BN_BLINDING *b)
unsigned long BN_BLINDING_get_flags (const BN_BLINDING *)
void BN_BLINDING_set_flags (BN_BLINDING *, unsigned long)
BN_BLINDING * BN_BLINDING_create_param (BN_BLINDING *b, const BIGNUM *e, BIGNUM *m, BN_CTX *ctx, int(*bn_mod_exp)(BIGNUM *r, const BIGNUM *a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *m_ctx), BN_MONT_CTX *m_ctx)
DEPRECATEDIN_0_9_8 (int BN_get_params(int which)) BN_RECP_CTX *BN_RECP_CTX_new(void)
void BN_RECP_CTX_free (BN_RECP_CTX *recp)
int BN_RECP_CTX_set (BN_RECP_CTX *recp, const BIGNUM *rdiv, BN_CTX *ctx)
int BN_mod_mul_reciprocal (BIGNUM *r, const BIGNUM *x, const BIGNUM *y, BN_RECP_CTX *recp, BN_CTX *ctx)
int BN_mod_exp_recp (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx)
int BN_div_recp (BIGNUM *dv, BIGNUM *rem, const BIGNUM *m, BN_RECP_CTX *recp, BN_CTX *ctx)
int BN_GF2m_add (BIGNUM *r, const BIGNUM *a, const BIGNUM *b)
int BN_GF2m_mod (BIGNUM *r, const BIGNUM *a, const BIGNUM *p)
int BN_GF2m_mod_mul (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_mod_sqr (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_mod_inv (BIGNUM *r, const BIGNUM *b, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_mod_div (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_mod_exp (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_mod_sqrt (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_mod_solve_quad (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_mod_arr (BIGNUM *r, const BIGNUM *a, const int p[])
int BN_GF2m_mod_mul_arr (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const int p[], BN_CTX *ctx)
int BN_GF2m_mod_sqr_arr (BIGNUM *r, const BIGNUM *a, const int p[], BN_CTX *ctx)
int BN_GF2m_mod_inv_arr (BIGNUM *r, const BIGNUM *b, const int p[], BN_CTX *ctx)
int BN_GF2m_mod_div_arr (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const int p[], BN_CTX *ctx)
int BN_GF2m_mod_exp_arr (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const int p[], BN_CTX *ctx)
int BN_GF2m_mod_sqrt_arr (BIGNUM *r, const BIGNUM *a, const int p[], BN_CTX *ctx)
int BN_GF2m_mod_solve_quad_arr (BIGNUM *r, const BIGNUM *a, const int p[], BN_CTX *ctx)
int BN_GF2m_poly2arr (const BIGNUM *a, int p[], int max)
int BN_GF2m_arr2poly (const int p[], BIGNUM *a)
int BN_nist_mod_192 (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, BN_CTX *ctx)
int BN_nist_mod_224 (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, BN_CTX *ctx)
int BN_nist_mod_256 (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, BN_CTX *ctx)
int BN_nist_mod_384 (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, BN_CTX *ctx)
int BN_nist_mod_521 (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, BN_CTX *ctx)
const BIGNUM * BN_get0_nist_prime_192 (void)
const BIGNUM * BN_get0_nist_prime_224 (void)
const BIGNUM * BN_get0_nist_prime_256 (void)
const BIGNUM * BN_get0_nist_prime_384 (void)
const BIGNUM * BN_get0_nist_prime_521 (void)
int BN_generate_dsa_nonce (BIGNUM *out, const BIGNUM *range, const BIGNUM *priv, const unsigned char *message, size_t message_len, BN_CTX *ctx)
BIGNUM * BN_get_rfc2409_prime_768 (BIGNUM *bn)
BIGNUM * BN_get_rfc2409_prime_1024 (BIGNUM *bn)
BIGNUM * BN_get_rfc3526_prime_1536 (BIGNUM *bn)
BIGNUM * BN_get_rfc3526_prime_2048 (BIGNUM *bn)
BIGNUM * BN_get_rfc3526_prime_3072 (BIGNUM *bn)
BIGNUM * BN_get_rfc3526_prime_4096 (BIGNUM *bn)
BIGNUM * BN_get_rfc3526_prime_6144 (BIGNUM *bn)
BIGNUM * BN_get_rfc3526_prime_8192 (BIGNUM *bn)
int BN_bntest_rand (BIGNUM *rnd, int bits, int top, int bottom)
int ERR_load_BN_strings (void)
Variables
int nchecks
int void(* callback)(int, int, void *)
int void(*) BN_CTX ctx)
int void(*) BN_CTX void *cb_ar DEPRECATEDIN_0_9_8)(int BN_is_prime_fasttest(const BIGNUM *p, int nchecks, void(*callback)(int, int, void *), BN_CTX *ctx, void *cb_arg, int do_trial_division)) int BN_generate_prime_ex(BIGNUM *ret
int void(*) BN_CTX void *cb_arg in bits)
int void(*) BN_CTX void *cb_arg int in safe)
int void(*) BN_CTX void *cb_arg int int const BIGNUM add)
int void(*) BN_CTX void *cb_arg int int const BIGNUM const BIGNUM rem)
int void(*) BN_CTX void *cb_arg int int const BIGNUM const BIGNUM BN_GENCB cb)
int(*)(BIGNUM *r, const BIGNUM *a, const BIGNUM *field, BN_CTX *ctx) BN_nist_mod_func (const BIGNUM *p)
Macro Definition Documentation
BN_BITS
#define BN_BITS (BN_BITS2 * 2)
Definition at line 61 of file bn.h.
BN_BITS2
#define BN_BITS2 (BN_BYTES * 8)
Definition at line 60 of file bn.h.
Referenced by BN_clear_bit(), BN_consttime_swap(), BN_div(), BN_is_bit_set(), BN_lshift(), BN_mask_bits(), BN_num_bits(), BN_rshift(), bn_sqr_words(), and ec_GF2m_simple_group_copy().
BN_BLINDING_NO_RECREATE
#define BN_BLINDING_NO_RECREATE 0x00000002
Definition at line 333 of file bn.h.
BN_BLINDING_NO_UPDATE
#define BN_BLINDING_NO_UPDATE 0x00000001
Definition at line 332 of file bn.h.
BN_F_BN_BLINDING_CONVERT_EX
#define BN_F_BN_BLINDING_CONVERT_EX 100
Definition at line 506 of file bn.h.
BN_F_BN_BLINDING_CREATE_PARAM
#define BN_F_BN_BLINDING_CREATE_PARAM 128
Definition at line 507 of file bn.h.
BN_F_BN_BLINDING_INVERT_EX
#define BN_F_BN_BLINDING_INVERT_EX 101
Definition at line 508 of file bn.h.
BN_F_BN_BLINDING_NEW
#define BN_F_BN_BLINDING_NEW 102
Definition at line 509 of file bn.h.
BN_F_BN_BLINDING_UPDATE
#define BN_F_BN_BLINDING_UPDATE 103
Definition at line 510 of file bn.h.
BN_F_BN_BN2DEC
#define BN_F_BN_BN2DEC 104
Definition at line 511 of file bn.h.
BN_F_BN_BN2HEX
#define BN_F_BN_BN2HEX 105
Definition at line 512 of file bn.h.
BN_F_BN_COMPUTE_WNAF
#define BN_F_BN_COMPUTE_WNAF 142
Definition at line 513 of file bn.h.
BN_F_BN_CTX_GET
#define BN_F_BN_CTX_GET 116
Definition at line 514 of file bn.h.
BN_F_BN_CTX_NEW
#define BN_F_BN_CTX_NEW 106
Definition at line 515 of file bn.h.
BN_F_BN_CTX_START
#define BN_F_BN_CTX_START 129
Definition at line 516 of file bn.h.
BN_F_BN_DIV
#define BN_F_BN_DIV 107
Definition at line 517 of file bn.h.
Referenced by BN_div().
BN_F_BN_DIV_RECP
#define BN_F_BN_DIV_RECP 130
Definition at line 518 of file bn.h.
BN_F_BN_EXP
#define BN_F_BN_EXP 123
Definition at line 519 of file bn.h.
BN_F_BN_EXPAND_INTERNAL
#define BN_F_BN_EXPAND_INTERNAL 120
Definition at line 520 of file bn.h.
BN_F_BN_GENCB_NEW
#define BN_F_BN_GENCB_NEW 143
Definition at line 521 of file bn.h.
BN_F_BN_GENERATE_DSA_NONCE
#define BN_F_BN_GENERATE_DSA_NONCE 140
Definition at line 522 of file bn.h.
BN_F_BN_GENERATE_PRIME_EX
#define BN_F_BN_GENERATE_PRIME_EX 141
Definition at line 523 of file bn.h.
BN_F_BN_GF2M_MOD
#define BN_F_BN_GF2M_MOD 131
Definition at line 524 of file bn.h.
BN_F_BN_GF2M_MOD_EXP
#define BN_F_BN_GF2M_MOD_EXP 132
Definition at line 525 of file bn.h.
BN_F_BN_GF2M_MOD_MUL
#define BN_F_BN_GF2M_MOD_MUL 133
Definition at line 526 of file bn.h.
BN_F_BN_GF2M_MOD_SOLVE_QUAD
#define BN_F_BN_GF2M_MOD_SOLVE_QUAD 134
Definition at line 527 of file bn.h.
BN_F_BN_GF2M_MOD_SOLVE_QUAD_ARR
#define BN_F_BN_GF2M_MOD_SOLVE_QUAD_ARR 135
Definition at line 528 of file bn.h.
BN_F_BN_GF2M_MOD_SQR
#define BN_F_BN_GF2M_MOD_SQR 136
Definition at line 529 of file bn.h.
BN_F_BN_GF2M_MOD_SQRT
#define BN_F_BN_GF2M_MOD_SQRT 137
Definition at line 530 of file bn.h.
BN_F_BN_LSHIFT
#define BN_F_BN_LSHIFT 145
Definition at line 531 of file bn.h.
Referenced by BN_lshift().
BN_F_BN_MOD_EXP2_MONT
#define BN_F_BN_MOD_EXP2_MONT 118
Definition at line 532 of file bn.h.
BN_F_BN_MOD_EXP_MONT
#define BN_F_BN_MOD_EXP_MONT 109
Definition at line 533 of file bn.h.
BN_F_BN_MOD_EXP_MONT_CONSTTIME
#define BN_F_BN_MOD_EXP_MONT_CONSTTIME 124
Definition at line 534 of file bn.h.
BN_F_BN_MOD_EXP_MONT_WORD
#define BN_F_BN_MOD_EXP_MONT_WORD 117
Definition at line 535 of file bn.h.
BN_F_BN_MOD_EXP_RECP
#define BN_F_BN_MOD_EXP_RECP 125
Definition at line 536 of file bn.h.
BN_F_BN_MOD_EXP_SIMPLE
#define BN_F_BN_MOD_EXP_SIMPLE 126
Definition at line 537 of file bn.h.
BN_F_BN_MOD_INVERSE
#define BN_F_BN_MOD_INVERSE 110
Definition at line 538 of file bn.h.
Referenced by BN_mod_inverse().
BN_F_BN_MOD_INVERSE_NO_BRANCH
#define BN_F_BN_MOD_INVERSE_NO_BRANCH 139
Definition at line 539 of file bn.h.
BN_F_BN_MOD_LSHIFT_QUICK
#define BN_F_BN_MOD_LSHIFT_QUICK 119
Definition at line 540 of file bn.h.
Referenced by BN_mod_lshift_quick().
BN_F_BN_MOD_SQRT
#define BN_F_BN_MOD_SQRT 121
Definition at line 541 of file bn.h.
BN_F_BN_MPI2BN
#define BN_F_BN_MPI2BN 112
Definition at line 542 of file bn.h.
Referenced by BN_mpi2bn().
BN_F_BN_NEW
#define BN_F_BN_NEW 113
Definition at line 543 of file bn.h.
BN_F_BN_RAND
#define BN_F_BN_RAND 114
Definition at line 544 of file bn.h.
BN_F_BN_RAND_RANGE
#define BN_F_BN_RAND_RANGE 122
Definition at line 545 of file bn.h.
BN_F_BN_RSHIFT
#define BN_F_BN_RSHIFT 146
Definition at line 546 of file bn.h.
Referenced by BN_rshift().
BN_F_BN_SET_WORDS
#define BN_F_BN_SET_WORDS 144
Definition at line 547 of file bn.h.
Referenced by bn_set_words().
BN_F_BN_USUB
#define BN_F_BN_USUB 115
Definition at line 548 of file bn.h.
Referenced by BN_usub().
BN_F_BNRAND
#define BN_F_BNRAND 127
Definition at line 505 of file bn.h.
BN_FLG_CONSTTIME
#define BN_FLG_CONSTTIME 0x04
Definition at line 73 of file bn.h.
Referenced by BN_div().
BN_FLG_EXP_CONSTTIME
#define BN_FLG_EXP_CONSTTIME BN_FLG_CONSTTIME
Definition at line 78 of file bn.h.
BN_FLG_FREE
#define BN_FLG_FREE 0x8000 /* used for debugging */
Definition at line 79 of file bn.h.
BN_FLG_MALLOCED
#define BN_FLG_MALLOCED 0x01
Definition at line 64 of file bn.h.
Referenced by BN_MONT_CTX_free(), BN_RECP_CTX_free(), BN_swap(), and BN_with_flags().
BN_FLG_SECURE
#define BN_FLG_SECURE 0x08
Definition at line 74 of file bn.h.
Referenced by BN_dup().
BN_FLG_STATIC_DATA
#define BN_FLG_STATIC_DATA 0x02
Definition at line 65 of file bn.h.
Referenced by BN_clear_free(), BN_free(), BN_nist_mod_521(), bn_set_static_words(), BN_swap(), BN_value_one(), and BN_with_flags().
BN_GF2m_cmp
#define BN_GF2m_cmp (a, b) BN_ucmp((a), (b))
Definition at line 412 of file bn.h.
BN_GF2m_sub
#define BN_GF2m_sub (r, a, b) BN_GF2m_add(r, a, b)
Definition at line 388 of file bn.h.
BN_mod
#define BN_mod (rem, m, d, ctx) BN_div(NULL,(rem),(m),(d),(ctx))
Definition at line 206 of file bn.h.
Referenced by BN_mod_sqr(), and BN_nnmod().
BN_num_bytes
#define BN_num_bytes (a) ((BN_num_bits(a)+7)/8)
Definition at line 142 of file bn.h.
Referenced by BN_bn2lebinpad(), DH_compute_key_padded(), DH_size(), RSA_size(), and SRP_Calc_x().
BN_one
#define BN_one (a) (BN_set_word((a),1))
Definition at line 150 of file bn.h.
BN_prime_checks
#define BN_prime_checks
Value:
0      /* default: select number of iterations based
                                 * on the size of the number */
Definition at line 118 of file bn.h.
BN_prime_checks_for_size
#define BN_prime_checks_for_size (b)
Value:
((b) >= 1300 ?  2 : \
                                (b) >=  850 ?  3 : \
                                (b) >=  650 ?  4 : \
                                (b) >=  550 ?  5 : \
                                (b) >=  450 ?  6 : \
                                (b) >=  400 ?  7 : \
                                (b) >=  350 ?  8 : \
                                (b) >=  300 ?  9 : \
                                (b) >=  250 ? 12 : \
                                (b) >=  200 ? 15 : \
                                (b) >=  150 ? 18 : \
                                /* b >= 100 */ 27)
Definition at line 129 of file bn.h.
BN_R_ARG2_LT_ARG3
#define BN_R_ARG2_LT_ARG3 100
Definition at line 551 of file bn.h.
Referenced by BN_usub().
BN_R_BAD_RECIPROCAL
#define BN_R_BAD_RECIPROCAL 101
Definition at line 552 of file bn.h.
BN_R_BIGNUM_TOO_LONG
#define BN_R_BIGNUM_TOO_LONG 114
Definition at line 553 of file bn.h.
BN_R_BITS_TOO_SMALL
#define BN_R_BITS_TOO_SMALL 118
Definition at line 554 of file bn.h.
BN_R_CALLED_WITH_EVEN_MODULUS
#define BN_R_CALLED_WITH_EVEN_MODULUS 102
Definition at line 555 of file bn.h.
BN_R_DIV_BY_ZERO
#define BN_R_DIV_BY_ZERO 103
Definition at line 556 of file bn.h.
Referenced by BN_div().
BN_R_ENCODING_ERROR
#define BN_R_ENCODING_ERROR 104
Definition at line 557 of file bn.h.
Referenced by BN_mpi2bn().
BN_R_EXPAND_ON_STATIC_BIGNUM_DATA
#define BN_R_EXPAND_ON_STATIC_BIGNUM_DATA 105
Definition at line 558 of file bn.h.
BN_R_INPUT_NOT_REDUCED
#define BN_R_INPUT_NOT_REDUCED 110
Definition at line 559 of file bn.h.
Referenced by BN_mod_lshift_quick().
BN_R_INVALID_LENGTH
#define BN_R_INVALID_LENGTH 106
Definition at line 560 of file bn.h.
Referenced by BN_mpi2bn().
BN_R_INVALID_RANGE
#define BN_R_INVALID_RANGE 115
Definition at line 561 of file bn.h.
BN_R_INVALID_SHIFT
#define BN_R_INVALID_SHIFT 119
Definition at line 562 of file bn.h.
Referenced by BN_lshift(), and BN_rshift().
BN_R_NO_INVERSE
#define BN_R_NO_INVERSE 108
Definition at line 565 of file bn.h.
Referenced by BN_mod_inverse().
BN_R_NO_SOLUTION
#define BN_R_NO_SOLUTION 116
Definition at line 566 of file bn.h.
BN_R_NOT_A_SQUARE
#define BN_R_NOT_A_SQUARE 111
Definition at line 563 of file bn.h.
BN_R_NOT_INITIALIZED
#define BN_R_NOT_INITIALIZED 107
Definition at line 564 of file bn.h.
Referenced by BN_div().
BN_R_P_IS_NOT_PRIME
#define BN_R_P_IS_NOT_PRIME 112
Definition at line 568 of file bn.h.
BN_R_PRIVATE_KEY_TOO_LARGE
#define BN_R_PRIVATE_KEY_TOO_LARGE 117
Definition at line 567 of file bn.h.
BN_R_TOO_MANY_ITERATIONS
#define BN_R_TOO_MANY_ITERATIONS 113
Definition at line 569 of file bn.h.
BN_R_TOO_MANY_TEMPORARY_VARIABLES
#define BN_R_TOO_MANY_TEMPORARY_VARIABLES 109
Definition at line 570 of file bn.h.
BN_RAND_BOTTOM_ANY
#define BN_RAND_BOTTOM_ANY 0
Definition at line 91 of file bn.h.
Referenced by BN_X931_generate_Xpq().
BN_RAND_BOTTOM_ODD
#define BN_RAND_BOTTOM_ODD 1
Definition at line 92 of file bn.h.
BN_RAND_TOP_ANY
#define BN_RAND_TOP_ANY -1
Definition at line 86 of file bn.h.
BN_RAND_TOP_ONE
#define BN_RAND_TOP_ONE 0
Definition at line 87 of file bn.h.
BN_RAND_TOP_TWO
#define BN_RAND_TOP_TWO 1
Definition at line 88 of file bn.h.
Referenced by BN_X931_generate_Xpq().
BN_TBIT
#define BN_TBIT ((BN_ULONG)1 << (BN_BITS2 - 1))
Definition at line 62 of file bn.h.
BN_zero
#define BN_zero (a) (BN_set_word((a),0))
Definition at line 157 of file bn.h.
Referenced by BN_div(), BN_GF2m_arr2poly(), BN_mul_word(), BN_RECP_CTX_set(), BN_rshift(), ec_GF2m_simple_point_set_to_infinity(), and ec_GFp_simple_point_set_to_infinity().
get_rfc2409_prime_1024
#define get_rfc2409_prime_1024 BN_get_rfc2409_prime_1024
Definition at line 483 of file bn.h.
get_rfc2409_prime_768
#define get_rfc2409_prime_768 BN_get_rfc2409_prime_768
Definition at line 482 of file bn.h.
get_rfc3526_prime_1536
#define get_rfc3526_prime_1536 BN_get_rfc3526_prime_1536
Definition at line 484 of file bn.h.
get_rfc3526_prime_2048
#define get_rfc3526_prime_2048 BN_get_rfc3526_prime_2048
Definition at line 485 of file bn.h.
get_rfc3526_prime_3072
#define get_rfc3526_prime_3072 BN_get_rfc3526_prime_3072
Definition at line 486 of file bn.h.
get_rfc3526_prime_4096
#define get_rfc3526_prime_4096 BN_get_rfc3526_prime_4096
Definition at line 487 of file bn.h.
get_rfc3526_prime_6144
#define get_rfc3526_prime_6144 BN_get_rfc3526_prime_6144
Definition at line 488 of file bn.h.
get_rfc3526_prime_8192
#define get_rfc3526_prime_8192 BN_get_rfc3526_prime_8192
Definition at line 489 of file bn.h.
Function Documentation
BN_abs_is_word()
int BN_abs_is_word (const BIGNUM * a, const BN_ULONG w)
Definition at line 915 of file bn_lib.c.
Referenced by BN_is_one(), and BN_is_word().
BN_add()
int BN_add (BIGNUM * r, const BIGNUM * a, const BIGNUM * b)
Definition at line 14 of file bn_add.c.
Referenced by BN_mod_add(), BN_mod_sub_quick(), and BN_nnmod().
BN_add_word()
int BN_add_word (BIGNUM * a, BN_ULONG w)
Definition at line 98 of file bn_word.c.
References bn_check_top, BN_is_zero(), BN_set_word(), BN_sub_word(), bn_wexpand(), and NULL.
Referenced by BN_sub_word().
BN_asc2bn()
int BN_asc2bn (BIGNUM ** a, const char * str)
Definition at line 269 of file bn_print.c.
References BN_dec2bn(), and BN_hex2bn().
BN_bin2bn()
BIGNUM* BN_bin2bn (const unsigned char * s, int len, BIGNUM * ret)
Definition at line 475 of file bn_lib.c.
Referenced by BN_get_rfc2409_prime_1024(), BN_get_rfc2409_prime_768(), BN_get_rfc3526_prime_1536(), BN_get_rfc3526_prime_2048(), BN_get_rfc3526_prime_3072(), BN_get_rfc3526_prime_4096(), BN_get_rfc3526_prime_6144(), BN_get_rfc3526_prime_8192(), BN_mpi2bn(), get_dsa1024(), get_dsa2048(), get_dsa512(), SRP_Calc_A_param(), SRP_Calc_x(), SRP_create_verifier_BN(), and SSL_srp_server_param_with_username().
BN_BLINDING_convert()
int BN_BLINDING_convert (BIGNUM * n, BN_BLINDING * b, BN_CTX * ctx)
Definition at line 125 of file bn_blind.c.
References BN_BLINDING_convert_ex(), and NULL.
BN_BLINDING_convert_ex()
int BN_BLINDING_convert_ex (BIGNUM * n, BIGNUM * r, BN_BLINDING * b, BN_CTX *)
Definition at line 130 of file bn_blind.c.
Referenced by BN_BLINDING_convert().
BN_BLINDING_create_param()
BN_BLINDING* BN_BLINDING_create_param (BN_BLINDING * b, const BIGNUM * e, BIGNUM * m, BN_CTX * ctx, int(*)(BIGNUM *r, const BIGNUM *a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *m_ctx) bn_mod_exp, BN_MONT_CTX * m_ctx)
Definition at line 214 of file bn_blind.c.
BN_BLINDING_free()
void BN_BLINDING_free (BN_BLINDING * b)
Definition at line 81 of file bn_blind.c.
References BN_free(), CRYPTO_THREAD_lock_free(), NULL, and OPENSSL_free.
Referenced by RSA_blinding_off(), and RSA_free().
BN_BLINDING_get_flags()
unsigned long BN_BLINDING_get_flags (const BN_BLINDING *)
Definition at line 204 of file bn_blind.c.
BN_BLINDING_invert()
int BN_BLINDING_invert (BIGNUM * n, BN_BLINDING * b, BN_CTX * ctx)
Definition at line 158 of file bn_blind.c.
References BN_BLINDING_invert_ex(), and NULL.
BN_BLINDING_invert_ex()
int BN_BLINDING_invert_ex (BIGNUM * n, const BIGNUM * r, BN_BLINDING * b, BN_CTX *)
Definition at line 163 of file bn_blind.c.
Referenced by BN_BLINDING_invert().
BN_BLINDING_is_current_thread()
int BN_BLINDING_is_current_thread (BN_BLINDING * b)
Definition at line 184 of file bn_blind.c.
References CRYPTO_THREAD_compare_id(), and CRYPTO_THREAD_get_current_id().
BN_BLINDING_lock()
int BN_BLINDING_lock (BN_BLINDING * b)
Definition at line 194 of file bn_blind.c.
References CRYPTO_THREAD_write_lock().
BN_BLINDING_new()
BN_BLINDING* BN_BLINDING_new (const BIGNUM * A, const BIGNUM * Ai, BIGNUM * mod)
Definition at line 30 of file bn_blind.c.
BN_BLINDING_set_current_thread()
void BN_BLINDING_set_current_thread (BN_BLINDING * b)
Definition at line 189 of file bn_blind.c.
References CRYPTO_THREAD_get_current_id().
BN_BLINDING_set_flags()
void BN_BLINDING_set_flags (BN_BLINDING * , unsigned long)
Definition at line 209 of file bn_blind.c.
References BN_BLINDING::flags.
BN_BLINDING_unlock()
int BN_BLINDING_unlock (BN_BLINDING * b)
Definition at line 199 of file bn_blind.c.
References CRYPTO_THREAD_unlock().
BN_BLINDING_update()
int BN_BLINDING_update (BN_BLINDING * b, BN_CTX * ctx)
Definition at line 94 of file bn_blind.c.
BN_bn2bin()
int BN_bn2bin (const BIGNUM * a, unsigned char * to)
Definition at line 551 of file bn_lib.c.
Referenced by BN_bn2mpi(), and SRP_Calc_x().
BN_bn2binpad()
int BN_bn2binpad (const BIGNUM * a, unsigned char * to, int tolen)
Definition at line 544 of file bn_lib.c.
BN_bn2dec()
char* BN_bn2dec (const BIGNUM * a)
Definition at line 55 of file bn_print.c.
Referenced by i2s_ASN1_ENUMERATED(), and i2s_ASN1_INTEGER().
BN_bn2hex()
char* BN_bn2hex (const BIGNUM * a)
Definition at line 20 of file bn_print.c.
Referenced by TS_ASN1_INTEGER_print_bio().
BN_bn2lebinpad()
int BN_bn2lebinpad (const BIGNUM * a, unsigned char * to, int tolen)
Definition at line 603 of file bn_lib.c.
References bn_check_top, and BN_num_bytes.
BN_bn2mpi()
int BN_bn2mpi (const BIGNUM * a, unsigned char * to)
Definition at line 14 of file bn_mpi.c.
References bits, BN_bn2bin(), BN_num_bits(), and NULL.
BN_bntest_rand()
int BN_bntest_rand (BIGNUM * rnd, int bits, int top, int bottom)
Definition at line 106 of file bn_rand.c.
BN_clear()
void BN_clear (BIGNUM * a)
Definition at line 444 of file bn_lib.c.
References bn_check_top, NULL, and OPENSSL_cleanse().
BN_clear_bit()
int BN_clear_bit (BIGNUM * a, int n)
Definition at line 714 of file bn_lib.c.
References BN_BITS2, bn_check_top, and bn_correct_top().
Referenced by BN_mpi2bn().
BN_clear_free()
void BN_clear_free (BIGNUM * a)
Definition at line 180 of file bn_lib.c.
References bn_check_top, BN_FLG_STATIC_DATA, BN_get_flags(), NULL, and OPENSSL_cleanse().
Referenced by BN_MONT_CTX_free(), DH_free(), DSA_free(), ec_GF2m_simple_group_clear_finish(), ec_GF2m_simple_point_clear_finish(), ec_GFp_mont_group_clear_finish(), ec_GFp_mont_group_copy(), ec_GFp_simple_group_clear_finish(), ec_GFp_simple_point_clear_finish(), EC_GROUP_clear_free(), EC_KEY_free(), EC_KEY_set_private_key(), RSA_free(), SRP_create_verifier_BN(), SRP_user_pwd_free(), and SSL_set_srp_server_param_pw().
BN_cmp()
int BN_cmp (const BIGNUM * a, const BIGNUM * b)
Definition at line 645 of file bn_lib.c.
References bn_check_top, and NULL.
Referenced by BN_mod_lshift1_quick(), BN_mod_lshift_quick(), EC_KEY_set_public_key_affine_coordinates(), and SRP_check_known_gN_param().
BN_consttime_swap()
void BN_consttime_swap (BN_ULONG swap, BIGNUM * a, BIGNUM * b, int nwords)
Definition at line 830 of file bn_lib.c.
References BN_BITS2, BN_CONSTTIME_SWAP, bn_wcheck_size, and t.
BN_copy()
BIGNUM* BN_copy (BIGNUM * a, const BIGNUM * b)
Definition at line 362 of file bn_lib.c.
References B, bn_check_top, bn_wexpand(), and NULL.
Referenced by BN_div(), BN_dup(), BN_mod_lshift_quick(), BN_MONT_CTX_copy(), BN_RECP_CTX_set(), ec_GF2m_simple_group_copy(), ec_GF2m_simple_point_copy(), ec_GFp_mont_field_set_to_one(), ec_GFp_simple_group_copy(), ec_GFp_simple_point_copy(), EC_GROUP_copy(), EC_GROUP_get_cofactor(), EC_KEY_copy(), and SSL_set_srp_server_param().
BN_CTX_end()
void BN_CTX_end (BN_CTX * ctx)
Definition at line 195 of file bn_ctx.c.
References CTXDBG_ENTRY, and fp.
Referenced by BN_div(), BN_X931_generate_Xpq(), EC_KEY_set_public_key_affine_coordinates(), and RSA_X931_generate_key_ex().
BN_CTX_free()
void BN_CTX_free (BN_CTX * c)
Definition at line 157 of file bn_ctx.c.
References BN_CTX_POOL_SIZE, BN_POOL_ITEM::next, NULL, and BN_POOL_ITEM::vals.
Referenced by EC_KEY_set_public_key_affine_coordinates(), RSA_X931_generate_key_ex(), SRP_Calc_A(), and SRP_create_verifier_BN().
BN_CTX_get()
BIGNUM* BN_CTX_get (BN_CTX * ctx)
Definition at line 212 of file bn_ctx.c.
Referenced by BN_div(), BN_X931_generate_Xpq(), EC_KEY_set_public_key_affine_coordinates(), and RSA_X931_generate_key_ex().
BN_CTX_new()
BN_CTX* BN_CTX_new (void)
Definition at line 134 of file bn_ctx.c.
Referenced by ec_GF2m_simple_mul(), EC_KEY_set_public_key_affine_coordinates(), ec_precompute_mont_data(), RSA_X931_generate_key_ex(), SRP_Calc_A(), and SRP_create_verifier_BN().
BN_CTX_secure_new()
BN_CTX* BN_CTX_secure_new (void)
Definition at line 148 of file bn_ctx.c.
BN_CTX_start()
void BN_CTX_start (BN_CTX * ctx)
Definition at line 181 of file bn_ctx.c.
References CTXDBG_ENTRY.
Referenced by BN_div(), BN_X931_generate_Xpq(), EC_KEY_set_public_key_affine_coordinates(), and RSA_X931_generate_key_ex().
BN_dec2bn()
int BN_dec2bn (BIGNUM ** a, const char * str)
Definition at line 199 of file bn_print.c.
Referenced by BN_asc2bn().
BN_div()
int BN_div (BIGNUM * dv, BIGNUM * rem, const BIGNUM * m, const BIGNUM * d, BN_CTX * ctx)
Definition at line 140 of file bn_div.c.
References bn_add_words(), BN_BITS2, bn_check_top, bn_clear_top2max, BN_copy(), bn_correct_top(), BN_CTX_end(), BN_CTX_get(), BN_CTX_start(), bn_div_words(), BN_F_BN_DIV, BN_FLG_CONSTTIME, BN_get_flags(), BN_is_zero(), BN_lshift(), bn_mul_words(), BN_num_bits(), BN_R_DIV_BY_ZERO, BN_R_NOT_INITIALIZED, BN_rshift(), bn_sub_words(), BN_ucmp(), bn_wexpand(), BN_zero, BNerr, HBITS, LBITS, mul64, NULL, and q.
BN_div_recp()
int BN_div_recp (BIGNUM * dv, BIGNUM * rem, const BIGNUM * m, BN_RECP_CTX * recp, BN_CTX * ctx)
Definition at line 83 of file bn_recp.c.
BN_div_word()
BN_ULONG BN_div_word (BIGNUM * a, BN_ULONG w)
Definition at line 61 of file bn_word.c.
BN_dup()
BIGNUM* BN_dup (const BIGNUM * a)
Definition at line 343 of file bn_lib.c.
References bn_check_top, BN_copy(), BN_FLG_SECURE, BN_free(), BN_get_flags(), BN_new(), BN_secure_new(), NULL, and t.
Referenced by ec_GFp_mont_group_copy(), EC_KEY_set_private_key(), SSL_set_srp_server_param(), SSL_set_srp_server_param_pw(), and SSL_SRP_CTX_init().
BN_exp()
int BN_exp (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, BN_CTX * ctx)
Definition at line 41 of file bn_exp.c.
References bits.
BN_free()
void BN_free (BIGNUM * a)
Definition at line 198 of file bn_lib.c.
References bn_check_top, BN_FLG_STATIC_DATA, BN_get_flags(), and NULL.
Referenced by BN_BLINDING_free(), BN_dup(), BN_mpi2bn(), BN_RECP_CTX_free(), DH_set0_key(), DH_set0_pqg(), DSA_set0_key(), DSA_set0_pqg(), ec_GF2m_simple_group_finish(), ec_GF2m_simple_group_init(), ec_GF2m_simple_point_finish(), ec_GF2m_simple_point_init(), ec_GFp_mont_group_finish(), ec_GFp_simple_group_finish(), ec_GFp_simple_group_init(), ec_GFp_simple_point_finish(), ec_GFp_simple_point_init(), EC_GROUP_free(), FuzzerCleanup(), i2s_ASN1_ENUMERATED(), i2s_ASN1_INTEGER(), RSA_generate_key(), RSA_set0_crt_params(), RSA_set0_factors(), RSA_set0_key(), SRP_Calc_A(), SRP_user_pwd_free(), SSL_CTX_SRP_CTX_free(), ssl_get_auto_dh(), SSL_set_srp_server_param(), SSL_SRP_CTX_free(), SSL_SRP_CTX_init(), and TS_ASN1_INTEGER_print_bio().
BN_from_montgomery()
int BN_from_montgomery (BIGNUM * r, const BIGNUM * a, BN_MONT_CTX * mont, BN_CTX * ctx)
Definition at line 166 of file bn_mont.c.
Referenced by ec_GFp_mont_field_decode().
BN_gcd()
int BN_gcd (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Definition at line 15 of file bn_gcd.c.
BN_GENCB_call()
int BN_GENCB_call (BN_GENCB * cb, int a, int b)
Definition at line 79 of file bn_prime.c.
BN_GENCB_free()
void BN_GENCB_free (BN_GENCB * cb)
Definition at line 974 of file bn_lib.c.
References NULL, and OPENSSL_free.
Referenced by RSA_generate_key().
BN_GENCB_get_arg()
void* BN_GENCB_get_arg (BN_GENCB * cb)
Definition at line 1011 of file bn_lib.c.
BN_GENCB_new()
BN_GENCB* BN_GENCB_new (void)
Definition at line 962 of file bn_lib.c.
Referenced by RSA_generate_key().
BN_GENCB_set()
void BN_GENCB_set (BN_GENCB * gencb, int(*)(int, int, BN_GENCB *) callback, void * cb_arg)
Definition at line 1002 of file bn_lib.c.
References callback.
Referenced by evp_pkey_set_cb_translate().
BN_GENCB_set_old()
void BN_GENCB_set_old (BN_GENCB * gencb, void(*)(int, int, void *) callback, void * cb_arg)
Definition at line 992 of file bn_lib.c.
References callback.
Referenced by BN_is_prime(), BN_is_prime_fasttest(), and RSA_generate_key().
BN_generate_dsa_nonce()
int BN_generate_dsa_nonce (BIGNUM * out, const BIGNUM * range, const BIGNUM * priv, const unsigned char * message, size_t message_len, BN_CTX * ctx)
Definition at line 195 of file bn_rand.c.
BN_get0_nist_prime_192()
const BIGNUM* BN_get0_nist_prime_192 (void)
Definition at line 227 of file bn_nist.c.
BN_get0_nist_prime_224()
const BIGNUM* BN_get0_nist_prime_224 (void)
Definition at line 232 of file bn_nist.c.
BN_get0_nist_prime_256()
const BIGNUM* BN_get0_nist_prime_256 (void)
Definition at line 237 of file bn_nist.c.
BN_get0_nist_prime_384()
const BIGNUM* BN_get0_nist_prime_384 (void)
Definition at line 242 of file bn_nist.c.
BN_get0_nist_prime_521()
const BIGNUM* BN_get0_nist_prime_521 (void)
Definition at line 247 of file bn_nist.c.
BN_get_flags()
int BN_get_flags (const BIGNUM * b, int n)
Definition at line 986 of file bn_lib.c.
Referenced by BN_clear_free(), BN_div(), BN_dup(), and BN_free().
BN_get_rfc2409_prime_1024()
BIGNUM* BN_get_rfc2409_prime_1024 (BIGNUM * bn)
Definition at line 49 of file bn_const.c.
References BN_bin2bn().
BN_get_rfc2409_prime_768()
BIGNUM* BN_get_rfc2409_prime_768 (BIGNUM * bn)
Definition at line 21 of file bn_const.c.
References BN_bin2bn().
BN_get_rfc3526_prime_1536()
BIGNUM* BN_get_rfc3526_prime_1536 (BIGNUM * bn)
Definition at line 81 of file bn_const.c.
References BN_bin2bn().
BN_get_rfc3526_prime_2048()
BIGNUM* BN_get_rfc3526_prime_2048 (BIGNUM * bn)
Definition at line 120 of file bn_const.c.
References BN_bin2bn().
BN_get_rfc3526_prime_3072()
BIGNUM* BN_get_rfc3526_prime_3072 (BIGNUM * bn)
Definition at line 167 of file bn_const.c.
References BN_bin2bn().
Referenced by ssl_get_auto_dh().
BN_get_rfc3526_prime_4096()
BIGNUM* BN_get_rfc3526_prime_4096 (BIGNUM * bn)
Definition at line 230 of file bn_const.c.
References BN_bin2bn().
BN_get_rfc3526_prime_6144()
BIGNUM* BN_get_rfc3526_prime_6144 (BIGNUM * bn)
Definition at line 309 of file bn_const.c.
References BN_bin2bn().
BN_get_rfc3526_prime_8192()
BIGNUM* BN_get_rfc3526_prime_8192 (BIGNUM * bn)
Definition at line 420 of file bn_const.c.
References BN_bin2bn().
Referenced by ssl_get_auto_dh().
BN_get_word()
BN_ULONG BN_get_word (const BIGNUM * a)
Definition at line 453 of file bn_lib.c.
BN_GF2m_add()
int BN_GF2m_add (BIGNUM * r, const BIGNUM * a, const BIGNUM * b)
Definition at line 260 of file bn_gf2m.c.
References bn_check_top, bn_correct_top(), bn_wexpand(), and NULL.
Referenced by ec_GF2m_simple_invert().
BN_GF2m_arr2poly()
int BN_GF2m_arr2poly (const int p[], BIGNUM * a)
Definition at line 1209 of file bn_gf2m.c.
References bn_check_top, BN_set_bit(), and BN_zero.
BN_GF2m_mod()
int BN_GF2m_mod (BIGNUM * r, const BIGNUM * a, const BIGNUM * p)
Definition at line 398 of file bn_gf2m.c.
BN_GF2m_mod_arr()
int BN_GF2m_mod_arr (BIGNUM * r, const BIGNUM * a, const int p[])
Definition at line 300 of file bn_gf2m.c.
BN_GF2m_mod_div()
int BN_GF2m_mod_div (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * p, BN_CTX * ctx)
Definition at line 760 of file bn_gf2m.c.
References NULL.
Referenced by ec_GF2m_simple_field_div().
BN_GF2m_mod_div_arr()
int BN_GF2m_mod_div_arr (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const int p[], BN_CTX * ctx)
Definition at line 881 of file bn_gf2m.c.
BN_GF2m_mod_exp()
int BN_GF2m_mod_exp (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * p, BN_CTX * ctx)
Definition at line 955 of file bn_gf2m.c.
BN_GF2m_mod_exp_arr()
int BN_GF2m_mod_exp_arr (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const int p[], BN_CTX * ctx)
Definition at line 909 of file bn_gf2m.c.
BN_GF2m_mod_inv()
int BN_GF2m_mod_inv (BIGNUM * r, const BIGNUM * b, const BIGNUM * p, BN_CTX * ctx)
Definition at line 560 of file bn_gf2m.c.
BN_GF2m_mod_inv_arr()
int BN_GF2m_mod_inv_arr (BIGNUM * r, const BIGNUM * b, const int p[], BN_CTX * ctx)
Definition at line 734 of file bn_gf2m.c.
BN_GF2m_mod_mul()
int BN_GF2m_mod_mul (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * p, BN_CTX * ctx)
Definition at line 473 of file bn_gf2m.c.
BN_GF2m_mod_mul_arr()
int BN_GF2m_mod_mul_arr (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const int p[], BN_CTX * ctx)
Definition at line 418 of file bn_gf2m.c.
Referenced by ec_GF2m_simple_field_mul().
BN_GF2m_mod_solve_quad()
int BN_GF2m_mod_solve_quad (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, BN_CTX * ctx)
Definition at line 1145 of file bn_gf2m.c.
BN_GF2m_mod_solve_quad_arr()
int BN_GF2m_mod_solve_quad_arr (BIGNUM * r, const BIGNUM * a, const int p[], BN_CTX * ctx)
Definition at line 1041 of file bn_gf2m.c.
BN_GF2m_mod_sqr()
int BN_GF2m_mod_sqr (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, BN_CTX * ctx)
Definition at line 532 of file bn_gf2m.c.
BN_GF2m_mod_sqr_arr()
int BN_GF2m_mod_sqr_arr (BIGNUM * r, const BIGNUM * a, const int p[], BN_CTX * ctx)
Definition at line 497 of file bn_gf2m.c.
Referenced by ec_GF2m_simple_field_sqr().
BN_GF2m_mod_sqrt()
int BN_GF2m_mod_sqrt (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, BN_CTX * ctx)
Definition at line 1016 of file bn_gf2m.c.
BN_GF2m_mod_sqrt_arr()
int BN_GF2m_mod_sqrt_arr (BIGNUM * r, const BIGNUM * a, const int p[], BN_CTX * ctx)
Definition at line 982 of file bn_gf2m.c.
BN_GF2m_poly2arr()
int BN_GF2m_poly2arr (const BIGNUM * a, int p[], int max)
Definition at line 1174 of file bn_gf2m.c.
BN_hex2bn()
int BN_hex2bn (BIGNUM ** a, const char * str)
Definition at line 126 of file bn_print.c.
Referenced by BN_asc2bn().
BN_is_bit_set()
int BN_is_bit_set (const BIGNUM * a, int n)
Definition at line 732 of file bn_lib.c.
References BN_BITS2, and bn_check_top.
BN_is_negative()
int BN_is_negative (const BIGNUM * b)
BN_is_negative returns 1 if the BIGNUM is negative
Parameters
a pointer to the BIGNUM object
Returns
1 if a < 0 and 0 otherwise
Definition at line 940 of file bn_lib.c.
BN_is_odd()
int BN_is_odd (const BIGNUM * a)
Definition at line 935 of file bn_lib.c.
BN_is_one()
int BN_is_one (const BIGNUM * a)
Definition at line 925 of file bn_lib.c.
References BN_abs_is_word().
BN_is_prime_ex()
int BN_is_prime_ex (const BIGNUM * p, int nchecks, BN_CTX * ctx, BN_GENCB * cb)
Definition at line 194 of file bn_prime.c.
References BN_is_prime_fasttest_ex().
Referenced by BN_is_prime().
BN_is_prime_fasttest_ex()
int BN_is_prime_fasttest_ex (const BIGNUM * p, int nchecks, BN_CTX * ctx, int do_trial_division, BN_GENCB * cb)
Definition at line 200 of file bn_prime.c.
Referenced by BN_is_prime_ex(), and BN_is_prime_fasttest().
BN_is_word()
int BN_is_word (const BIGNUM * a, const BN_ULONG w)
Definition at line 930 of file bn_lib.c.
References BN_abs_is_word().
BN_is_zero()
int BN_is_zero (const BIGNUM * a)
Definition at line 920 of file bn_lib.c.
Referenced by BN_add_word(), BN_div(), BN_num_bits(), BN_set_negative(), BN_sub_word(), ec_GF2m_simple_invert(), ec_GF2m_simple_is_at_infinity(), ec_GFp_simple_invert(), ec_GFp_simple_is_at_infinity(), EC_GROUP_get_cofactor(), and srp_verify_server_param().
BN_kronecker()
int BN_kronecker (const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Definition at line 17 of file bn_kron.c.
BN_lebin2bn()
BIGNUM* BN_lebin2bn (const unsigned char * s, int len, BIGNUM * ret)
Definition at line 556 of file bn_lib.c.
BN_lshift()
int BN_lshift (BIGNUM * r, const BIGNUM * a, int n)
Definition at line 83 of file bn_shift.c.
References BN_BITS2, bn_check_top, bn_correct_top(), BN_F_BN_LSHIFT, BN_R_INVALID_SHIFT, bn_wexpand(), BNerr, NULL, and t.
Referenced by BN_div(), and BN_mod_lshift_quick().
BN_lshift1()
int BN_lshift1 (BIGNUM * r, const BIGNUM * a)
Definition at line 13 of file bn_shift.c.
References t.
Referenced by BN_mod_lshift1(), BN_mod_lshift1_quick(), and BN_mod_lshift_quick().
BN_mask_bits()
int BN_mask_bits (BIGNUM * a, int n)
Definition at line 746 of file bn_lib.c.
References BN_BITS2, bn_check_top, and bn_correct_top().
BN_mod_add()
int BN_mod_add (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * m, BN_CTX * ctx)
Definition at line 28 of file bn_mod.c.
References BN_add(), and BN_nnmod().
BN_mod_add_quick()
int BN_mod_add_quick (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * m)
Definition at line 40 of file bn_mod.c.
References BN_uadd(), BN_ucmp(), and BN_usub().
BN_mod_exp()
int BN_mod_exp (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, const BIGNUM * m, BN_CTX * ctx)
Definition at line 91 of file bn_exp.c.
Referenced by SRP_Calc_A(), and SRP_create_verifier_BN().
BN_mod_exp2_mont()
int BN_mod_exp2_mont (BIGNUM * r, const BIGNUM * a1, const BIGNUM * p1, const BIGNUM * a2, const BIGNUM * p2, const BIGNUM * m, BN_CTX * ctx, BN_MONT_CTX * m_ctx)
Definition at line 16 of file bn_exp2.c.
References bits.
BN_mod_exp_mont()
int BN_mod_exp_mont (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, const BIGNUM * m, BN_CTX * ctx, BN_MONT_CTX * m_ctx)
Definition at line 301 of file bn_exp.c.
References bits.
BN_mod_exp_mont_consttime()
int BN_mod_exp_mont_consttime (BIGNUM * rr, const BIGNUM * a, const BIGNUM * p, const BIGNUM * m, BN_CTX * ctx, BN_MONT_CTX * in_mont)
Definition at line 601 of file bn_exp.c.
References bits.
BN_mod_exp_mont_word()
int BN_mod_exp_mont_word (BIGNUM * r, BN_ULONG a, const BIGNUM * p, const BIGNUM * m, BN_CTX * ctx, BN_MONT_CTX * m_ctx)
Definition at line 1098 of file bn_exp.c.
References bits, and NULL.
BN_mod_exp_recp()
int BN_mod_exp_recp (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, const BIGNUM * m, BN_CTX * ctx)
Definition at line 168 of file bn_exp.c.
References bits.
BN_mod_exp_simple()
int BN_mod_exp_simple (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, const BIGNUM * m, BN_CTX * ctx)
Definition at line 1246 of file bn_exp.c.
References bits.
BN_mod_inverse()
BIGNUM* BN_mod_inverse (BIGNUM * ret, const BIGNUM * a, const BIGNUM * n, BN_CTX * ctx)
Definition at line 124 of file bn_gcd.c.
References BN_F_BN_MOD_INVERSE, BN_R_NO_INVERSE, BNerr, and int_bn_mod_inverse().
BN_mod_lshift()
int BN_mod_lshift (BIGNUM * r, const BIGNUM * a, int n, const BIGNUM * m, BN_CTX * ctx)
Definition at line 132 of file bn_mod.c.
References NULL.
BN_mod_lshift1()
int BN_mod_lshift1 (BIGNUM * r, const BIGNUM * a, const BIGNUM * m, BN_CTX * ctx)
Definition at line 110 of file bn_mod.c.
References bn_check_top, BN_lshift1(), and BN_nnmod().
BN_mod_lshift1_quick()
int BN_mod_lshift1_quick (BIGNUM * r, const BIGNUM * a, const BIGNUM * m)
Definition at line 122 of file bn_mod.c.
References bn_check_top, BN_cmp(), BN_lshift1(), and BN_sub().
BN_mod_lshift_quick()
int BN_mod_lshift_quick (BIGNUM * r, const BIGNUM * a, int n, const BIGNUM * m)
Definition at line 159 of file bn_mod.c.
References bn_check_top, BN_cmp(), BN_copy(), BN_F_BN_MOD_LSHIFT_QUICK, BN_lshift(), BN_lshift1(), BN_num_bits(), BN_R_INPUT_NOT_REDUCED, BN_sub(), BNerr, and NULL.
BN_mod_mul()
int BN_mod_mul (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * m, BN_CTX * ctx)
Definition at line 73 of file bn_mod.c.
References t.
Referenced by ec_GFp_simple_field_mul().
BN_mod_mul_montgomery()
int BN_mod_mul_montgomery (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_MONT_CTX * mont, BN_CTX * ctx)
Definition at line 26 of file bn_mont.c.
Referenced by BN_to_montgomery(), ec_GFp_mont_field_mul(), and ec_GFp_mont_field_sqr().
BN_mod_mul_reciprocal()
int BN_mod_mul_reciprocal (BIGNUM * r, const BIGNUM * x, const BIGNUM * y, BN_RECP_CTX * recp, BN_CTX * ctx)
Definition at line 54 of file bn_recp.c.
BN_mod_sqr()
int BN_mod_sqr (BIGNUM * r, const BIGNUM * a, const BIGNUM * m, BN_CTX * ctx)
Definition at line 102 of file bn_mod.c.
References BN_mod, and BN_sqr().
Referenced by ec_GFp_simple_field_sqr().
BN_mod_sqrt()
BIGNUM* BN_mod_sqrt (BIGNUM * ret, const BIGNUM * a, const BIGNUM * n, BN_CTX * ctx)
Definition at line 13 of file bn_sqrt.c.
BN_mod_sub()
int BN_mod_sub (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * m, BN_CTX * ctx)
Definition at line 50 of file bn_mod.c.
References BN_nnmod(), and BN_sub().
BN_mod_sub_quick()
int BN_mod_sub_quick (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * m)
Definition at line 62 of file bn_mod.c.
References BN_add(), and BN_sub().
BN_mod_word()
BN_ULONG BN_mod_word (const BIGNUM * a, BN_ULONG w)
Definition at line 13 of file bn_word.c.
BN_MONT_CTX_copy()
BN_MONT_CTX* BN_MONT_CTX_copy (BN_MONT_CTX * to, BN_MONT_CTX * from)
Definition at line 381 of file bn_mont.c.
References BN_copy(), and NULL.
Referenced by ec_GFp_mont_group_copy(), and EC_GROUP_copy().
BN_MONT_CTX_free()
void BN_MONT_CTX_free (BN_MONT_CTX * mont)
Definition at line 235 of file bn_mont.c.
References BN_clear_free(), BN_FLG_MALLOCED, NULL, and OPENSSL_free.
Referenced by ec_GFp_mont_group_clear_finish(), ec_GFp_mont_group_copy(), ec_GFp_mont_group_finish(), EC_GROUP_clear_free(), EC_GROUP_copy(), and EC_GROUP_free().
BN_MONT_CTX_new()
BN_MONT_CTX* BN_MONT_CTX_new (void)
Definition at line 213 of file bn_mont.c.
Referenced by ec_GFp_mont_group_copy(), and EC_GROUP_copy().
BN_MONT_CTX_set()
int BN_MONT_CTX_set (BN_MONT_CTX * mont, const BIGNUM * mod, BN_CTX * ctx)
Definition at line 247 of file bn_mont.c.
BN_MONT_CTX_set_locked()
BN_MONT_CTX* BN_MONT_CTX_set_locked (BN_MONT_CTX ** pmont, CRYPTO_RWLOCK * lock, const BIGNUM * mod, BN_CTX * ctx)
Definition at line 398 of file bn_mont.c.
BN_mpi2bn()
BIGNUM* BN_mpi2bn (const unsigned char * s, int len, BIGNUM * ret)
Definition at line 42 of file bn_mpi.c.
References BN_bin2bn(), bn_check_top, BN_clear_bit(), BN_F_BN_MPI2BN, BN_free(), BN_new(), BN_num_bits(), BN_R_ENCODING_ERROR, BN_R_INVALID_LENGTH, BNerr, len, and NULL.
BN_mul()
int BN_mul (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Definition at line 828 of file bn_mul.c.
BN_mul_word()
int BN_mul_word (BIGNUM * a, BN_ULONG w)
Definition at line 181 of file bn_word.c.
References bn_check_top, bn_mul_words(), bn_wexpand(), BN_zero, and NULL.
BN_new()
BIGNUM* BN_new (void)
Definition at line 223 of file bn_lib.c.
Referenced by BN_dup(), BN_mpi2bn(), ec_GF2m_simple_group_init(), ec_GF2m_simple_point_init(), ec_GFp_simple_group_init(), ec_GFp_simple_point_init(), EC_KEY_copy(), RSA_generate_key(), RSA_X931_generate_key_ex(), SRP_Calc_A(), SRP_create_verifier_BN(), ssl_get_auto_dh(), and TS_ASN1_INTEGER_print_bio().
BN_nist_mod_192()
int BN_nist_mod_192 (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, BN_CTX * ctx)
Definition at line 318 of file bn_nist.c.
References BN_NIST_192_TOP.
BN_nist_mod_224()
int BN_nist_mod_224 (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, BN_CTX * ctx)
Definition at line 459 of file bn_nist.c.
References BN_NIST_224_TOP.
BN_nist_mod_256()
int BN_nist_mod_256 (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, BN_CTX * ctx)
Definition at line 640 of file bn_nist.c.
References BN_NIST_256_TOP.
BN_nist_mod_384()
int BN_nist_mod_384 (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, BN_CTX * ctx)
Definition at line 886 of file bn_nist.c.
References BN_NIST_384_TOP.
BN_nist_mod_521()
int BN_nist_mod_521 (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, BN_CTX * ctx)
Definition at line 1155 of file bn_nist.c.
References BN_FLG_STATIC_DATA, BN_NIST_521_TOP, OSSL_NELEM, and PTR_SIZE_INT.
BN_nnmod()
int BN_nnmod (BIGNUM * r, const BIGNUM * m, const BIGNUM * d, BN_CTX * ctx)
Definition at line 13 of file bn_mod.c.
References BN_add(), BN_mod, and BN_sub().
Referenced by BN_mod_add(), BN_mod_lshift1(), and BN_mod_sub().
BN_num_bits()
int BN_num_bits (const BIGNUM * a)
Definition at line 161 of file bn_lib.c.
References BN_BITS2, bn_check_top, BN_is_zero(), and BN_num_bits_word().
Referenced by BN_bn2mpi(), BN_div(), BN_mod_lshift_quick(), BN_mpi2bn(), BN_RECP_CTX_set(), BN_rshift(), BN_X931_generate_Xpq(), DH_bits(), DH_security_bits(), DH_set0_pqg(), DSA_bits(), DSA_security_bits(), ec_GF2m_simple_group_get_degree(), ec_GFp_simple_group_get_degree(), ec_group_simple_order_bits(), RSA_bits(), RSA_security_bits(), and srp_verify_server_param().
BN_num_bits_word()
int BN_num_bits_word (BN_ULONG l)
Definition at line 89 of file bn_lib.c.
References bits.
Referenced by BN_num_bits().
BN_options()
char* BN_options (void)
Definition at line 329 of file bn_print.c.
BN_print()
int BN_print (BIO * bio, const BIGNUM * a)
Definition at line 304 of file bn_print.c.
BN_print_fp()
int BN_print_fp (FILE * fp, const BIGNUM * a)
Definition at line 290 of file bn_print.c.
BN_pseudo_rand()
int BN_pseudo_rand (BIGNUM * rnd, int bits, int top, int bottom)
Definition at line 101 of file bn_rand.c.
BN_pseudo_rand_range()
int BN_pseudo_rand_range (BIGNUM * rnd, const BIGNUM * range)
Definition at line 182 of file bn_rand.c.
BN_rand()
int BN_rand (BIGNUM * rnd, int bits, int top, int bottom)
Definition at line 96 of file bn_rand.c.
Referenced by BN_X931_generate_Xpq().
BN_rand_range()
int BN_rand_range (BIGNUM * rnd, const BIGNUM * range)
Definition at line 177 of file bn_rand.c.
BN_reciprocal()
int BN_reciprocal (BIGNUM * r, const BIGNUM * m, int len, BN_CTX * ctx)
Definition at line 179 of file bn_recp.c.
BN_RECP_CTX_free()
void BN_RECP_CTX_free (BN_RECP_CTX * recp)
Definition at line 33 of file bn_recp.c.
References BN_FLG_MALLOCED, BN_free(), NULL, and OPENSSL_free.
BN_RECP_CTX_set()
int BN_RECP_CTX_set (BN_RECP_CTX * recp, const BIGNUM * rdiv, BN_CTX * ctx)
Definition at line 44 of file bn_recp.c.
References BN_copy(), BN_num_bits(), and BN_zero.
BN_rshift()
int BN_rshift (BIGNUM * r, const BIGNUM * a, int n)
Definition at line 122 of file bn_shift.c.
References BN_BITS2, bn_check_top, BN_F_BN_RSHIFT, BN_num_bits(), BN_R_INVALID_SHIFT, bn_wexpand(), BN_zero, BNerr, NULL, and t.
Referenced by BN_div().
BN_rshift1()
int BN_rshift1 (BIGNUM * r, const BIGNUM * a)
Definition at line 46 of file bn_shift.c.
References t.
BN_secure_new()
BIGNUM* BN_secure_new (void)
Definition at line 236 of file bn_lib.c.
Referenced by BN_dup().
BN_security_bits()
int BN_security_bits (int L, int N)
Definition at line 886 of file bn_lib.c.
References bits.
Referenced by DH_security_bits(), DSA_security_bits(), and RSA_security_bits().
BN_set_bit()
int BN_set_bit (BIGNUM * a, int n)
Definition at line 692 of file bn_lib.c.
Referenced by BN_GF2m_arr2poly(), and RSA_generate_key().
BN_set_flags()
void BN_set_flags (BIGNUM * b, int n)
Definition at line 981 of file bn_lib.c.
BN_set_negative()
void BN_set_negative (BIGNUM * b, int n)
BN_set_negative sets sign of a BIGNUM
Parameters
b pointer to the BIGNUM object
n 0 if the BIGNUM b should be positive and a value != 0 otherwise
Definition at line 768 of file bn_lib.c.
References BN_is_zero().
Referenced by BN_sub_word().
BN_set_word()
int BN_set_word (BIGNUM * a, BN_ULONG w)
Definition at line 463 of file bn_lib.c.
References bn_check_top.
Referenced by BN_add_word(), BN_sub_word(), and ssl_get_auto_dh().
BN_sqr()
int BN_sqr (BIGNUM * r, const BIGNUM * a, BN_CTX * ctx)
Definition at line 17 of file bn_sqr.c.
References max.
Referenced by BN_mod_sqr().
BN_sub()
int BN_sub (BIGNUM * r, const BIGNUM * a, const BIGNUM * b)
Definition at line 150 of file bn_add.c.
References add, bn_check_top, BN_uadd(), BN_ucmp(), BN_usub(), bn_wexpand(), if(), max, and NULL.
Referenced by BN_mod_lshift1_quick(), BN_mod_lshift_quick(), BN_mod_sub(), BN_mod_sub_quick(), BN_nnmod(), and BN_X931_generate_Xpq().
BN_sub_word()
int BN_sub_word (BIGNUM * a, BN_ULONG w)
Definition at line 134 of file bn_word.c.
References BN_add_word(), bn_check_top, BN_is_zero(), BN_set_negative(), and BN_set_word().
Referenced by BN_add_word().
BN_swap()
void BN_swap (BIGNUM * a, BIGNUM * b)
Definition at line 409 of file bn_lib.c.
References bn_check_top, BN_FLG_MALLOCED, and BN_FLG_STATIC_DATA.
BN_to_montgomery()
int BN_to_montgomery (BIGNUM * r, const BIGNUM * a, BN_MONT_CTX * mont, BN_CTX * ctx)
Definition at line 945 of file bn_lib.c.
References BN_mod_mul_montgomery().
Referenced by ec_GFp_mont_field_encode().
BN_uadd()
int BN_uadd (BIGNUM * r, const BIGNUM * a, const BIGNUM * b)
Definition at line 58 of file bn_add.c.
References bn_add_words(), bn_check_top, bn_wexpand(), bp, max, min, and NULL.
Referenced by BN_mod_add_quick(), and BN_sub().
BN_ucmp()
int BN_ucmp (const BIGNUM * a, const BIGNUM * b)
Definition at line 623 of file bn_lib.c.
References bn_check_top, and bp.
Referenced by BN_div(), BN_mod_add_quick(), BN_sub(), and srp_verify_server_param().
BN_usub()
int BN_usub (BIGNUM * r, const BIGNUM * a, const BIGNUM * b)
Definition at line 107 of file bn_add.c.
References bn_check_top, bn_correct_top(), BN_F_BN_USUB, BN_R_ARG2_LT_ARG3, bn_sub_words(), bn_wexpand(), BNerr, bp, max, min, and NULL.
Referenced by BN_mod_add_quick(), BN_sub(), and ec_GFp_simple_invert().
BN_value_one()
const BIGNUM* BN_value_one (void)
Definition at line 80 of file bn_lib.c.
References BN_FLG_STATIC_DATA.
Referenced by ec_GFp_simple_point_set_affine_coordinates().
BN_with_flags()
void BN_with_flags (BIGNUM * dest, const BIGNUM * b, int flags)
Definition at line 951 of file bn_lib.c.
References BN_FLG_MALLOCED, BN_FLG_STATIC_DATA, and flags.
BN_X931_derive_prime_ex()
int BN_X931_derive_prime_ex (BIGNUM * p, BIGNUM * p1, BIGNUM * p2, const BIGNUM * Xp, const BIGNUM * Xp1, const BIGNUM * Xp2, const BIGNUM * e, BN_CTX * ctx, BN_GENCB * cb)
Definition at line 51 of file bn_x931p.c.
BN_X931_generate_prime_ex()
int BN_X931_generate_prime_ex (BIGNUM * p, BIGNUM * p1, BIGNUM * p2, BIGNUM * Xp1, BIGNUM * Xp2, const BIGNUM * Xp, const BIGNUM * e, BN_CTX * ctx, BN_GENCB * cb)
Definition at line 211 of file bn_x931p.c.
Referenced by RSA_X931_generate_key_ex().
BN_X931_generate_Xpq()
int BN_X931_generate_Xpq (BIGNUM * Xp, BIGNUM * Xq, int nbits, BN_CTX * ctx)
Definition at line 160 of file bn_x931p.c.
References BN_CTX_end(), BN_CTX_get(), BN_CTX_start(), BN_num_bits(), BN_rand(), BN_RAND_BOTTOM_ANY, BN_RAND_TOP_TWO, BN_sub(), and t.
Referenced by RSA_X931_generate_key_ex().
BN_zero_ex()
void BN_zero_ex (BIGNUM * a)
Definition at line 909 of file bn_lib.c.
DEPRECATEDIN_0_9_8() [1/2]
DEPRECATEDIN_0_9_8 (BIGNUM * BN_generate_primeBIGNUM *ret, int bits, int safe, const BIGNUM *add, const BIGNUM *rem, void(*callback)(int, int, void *), void *cb_arg) const
DEPRECATEDIN_0_9_8() [2/2]
DEPRECATEDIN_0_9_8 (int BN_get_paramsint which)
ERR_load_BN_strings()
int ERR_load_BN_strings (void)
Definition at line 97 of file bn_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
Variable Documentation
add
int void(*) BN_CTX void* cb_arg int int const BIGNUM add)
Definition at line 302 of file bn.h.
Referenced by BN_sub().
bits
int void(*) BN_CTX void* cb_arg in bits)
Definition at line 302 of file bn.h.
Referenced by BN_bn2mpi(), BN_exp(), BN_mod_exp2_mont(), BN_mod_exp_mont(), BN_mod_exp_mont_consttime(), BN_mod_exp_mont_word(), BN_mod_exp_recp(), BN_mod_exp_simple(), BN_num_bits_word(), and BN_security_bits().
BN_nist_mod_func
int(*)(BIGNUM *r, const BIGNUM *a, const BIGNUM *field, BN_CTX *ctx) BN_nist_mod_func(const BIGNUM *p)
Definition at line 462 of file bn.h.
callback
int void(* callback) (int, int, void *)
Definition at line 293 of file bn.h.
Referenced by BN_GENCB_set(), BN_GENCB_set_old(), BN_is_prime(), BN_is_prime_fasttest(), RSA_generate_key(), and SSL_set_verify().
cb
static int cb
Definition at line 302 of file bn.h.
Referenced by BIO_dump_cb(), BIO_set_callback(), BIO_set_callback_ex(), BN_is_prime(), BN_is_prime_fasttest(), DH_generate_parameters(), DSA_generate_parameters(), dtls1_dispatch_alert(), EVP_PKEY_CTX_set_cb(), main(), RSA_generate_key(), ssl3_dispatch_alert(), SSL_CTX_sess_set_get_cb(), SSL_CTX_sess_set_new_cb(), SSL_CTX_sess_set_remove_cb(), SSL_CTX_set_client_cert_cb(), SSL_CTX_set_default_passwd_cb(), SSL_CTX_set_generate_session_id(), SSL_CTX_set_info_callback(), SSL_CTX_set_keylog_callback(), SSL_CTX_set_not_resumable_session_callback(), SSL_CTX_set_psk_client_callback(), SSL_CTX_set_psk_server_callback(), SSL_CTX_set_security_callback(), SSL_CTX_set_srp_client_pwd_callback(), SSL_CTX_set_srp_username_callback(), SSL_CTX_set_srp_verify_param_callback(), SSL_CTX_set_verify(), ssl_get_new_session(), SSL_set_default_passwd_cb(), SSL_set_generate_session_id(), SSL_set_info_callback(), SSL_set_not_resumable_session_callback(), SSL_set_psk_client_callback(), SSL_set_psk_server_callback(), SSL_set_security_callback(), tls_finish_handshake(), TS_RESP_CTX_set_extension_cb(), TS_RESP_CTX_set_serial_cb(), and TS_RESP_CTX_set_time_cb().
ctx
int void(*) BN_CTX ctx)
Definition at line 294 of file bn.h.
Referenced by aes_ccm_decrypt(), aes_ccm_encrypt(), aes_gcm_decrypt(), aes_gcm_encrypt(), ASN1_item_sign(), ASN1_item_verify(), ASN1_sign(), ASN1_verify(), ASYNC_block_pause(), ASYNC_get_current_job(), ASYNC_pause_job(), async_start_func(), ASYNC_unblock_pause(), CMAC_CTX_new(), CMS_add0_recipient_password(), cms_EncryptedContent_init_bio(), comp_zlib_cleanup_int(), CT_POLICY_EVAL_CTX_new(), EC_KEY_set_public_key_affine_coordinates(), ec_key_simple_check_key(), ec_key_simple_generate_key(), ec_precompute_mont_data(), ecdh_simple_compute_key(), engine_load_cryptodev_int(), HMAC_CTX_new(), main(), mempacket_test_inject(), OCSP_basic_verify(), OCSP_request_verify(), OCSP_sendreq_bio(), PEM_ASN1_write_bio(), PEM_read_bio(), process_responder(), RSA_setup_blinding(), RSA_X931_derive_ex(), RSA_X931_generate_key_ex(), SCT_CTX_verify(), sha256_block_data_order(), SSL_CONF_CTX_set_ssl_ctx(), SSL_get_all_async_fds(), SSL_get_changed_async_fds(), SSL_new(), SSL_set_SSL_CTX(), SSL_SRP_CTX_init(), SSL_TEST_CTX_create(), tls13_enc(), tls_construct_new_session_ticket(), TS_RESP_CTX_new(), TS_VERIFY_CTX_new(), and X509_STORE_CTX_new().
DEPRECATEDIN_0_9_8
int void(*) BN_CTX void* cb_ar DEPRECATEDIN_0_9_8) (int BN_is_prime_fasttest(const BIGNUM *p, int nchecks, void(*callback)(int, int, void *), BN_CTX *ctx, void *cb_arg, int do_trial_division)) int BN_generate_prime_ex(BIGNUM *ret
Definition at line 295 of file bn.h.
nchecks
int nchecks
Definition at line 292 of file bn.h.
rem
int void(*) BN_CTX void* cb_arg int int const BIGNUM const BIGNUM rem)
Definition at line 302 of file bn.h.
Referenced by Poly1305_Update().
safe
int void(*) BN_CTX void* cb_arg int in safe)
Definition at line 302 of file bn.h.