crypto/include/internal/bn_int.h File Reference
bn_int.h File Reference
#include <openssl/bn.h>
#include <limits.h>
Functions
BIGNUM * bn_wexpand (BIGNUM *a, int words)
BIGNUM * bn_expand2 (BIGNUM *a, int words)
void bn_correct_top (BIGNUM *a)
signed char * bn_compute_wNAF (const BIGNUM *scalar, int w, size_t *ret_len)
int bn_get_top (const BIGNUM *a)
void bn_set_top (BIGNUM *a, int top)
int bn_get_dmax (const BIGNUM *a)
void bn_set_all_zero (BIGNUM *a)
int bn_copy_words (BN_ULONG *out, const BIGNUM *in, int size)
BN_ULONG * bn_get_words (const BIGNUM *a)
void bn_set_static_words (BIGNUM *a, BN_ULONG *words, int size)
int bn_set_words (BIGNUM *a, BN_ULONG *words, int num_words)
size_t bn_sizeof_BIGNUM (void)
BIGNUM * bn_array_el (BIGNUM *base, int el)
Function Documentation
bn_array_el()
BIGNUM* bn_array_el (BIGNUM * base, int el)
Definition at line 207 of file bn_intern.c.
bn_compute_wNAF()
signed char* bn_compute_wNAF (const BIGNUM * scalar, int w, size_t * ret_len)
Definition at line 22 of file bn_intern.c.
References NULL.
bn_copy_words()
int bn_copy_words (BN_ULONG * out, const BIGNUM * in, int size)
Definition at line 164 of file bn_intern.c.
bn_correct_top()
void bn_correct_top (BIGNUM * a)
Definition at line 1021 of file bn_lib.c.
References bn_pollute.
Referenced by BN_clear_bit(), BN_div(), BN_GF2m_add(), BN_lshift(), BN_mask_bits(), bn_set_static_words(), bn_set_words(), and BN_usub().
bn_expand2()
BIGNUM* bn_expand2 (BIGNUM * a, int words)
Definition at line 323 of file bn_lib.c.
References bn_check_top, and NULL.
Referenced by bn_wexpand().
bn_get_dmax()
int bn_get_dmax (const BIGNUM * a)
Definition at line 151 of file bn_intern.c.
bn_get_top()
int bn_get_top (const BIGNUM * a)
Definition at line 141 of file bn_intern.c.
bn_get_words()
BN_ULONG* bn_get_words (const BIGNUM * a)
Definition at line 175 of file bn_intern.c.
bn_set_all_zero()
void bn_set_all_zero (BIGNUM * a)
Definition at line 156 of file bn_intern.c.
Referenced by ec_GF2m_simple_group_copy().
bn_set_static_words()
void bn_set_static_words (BIGNUM * a, BN_ULONG * words, int size)
Definition at line 180 of file bn_intern.c.
References bn_correct_top(), and BN_FLG_STATIC_DATA.
bn_set_top()
void bn_set_top (BIGNUM * a, int top)
Definition at line 146 of file bn_intern.c.
bn_set_words()
int bn_set_words (BIGNUM * a, BN_ULONG * words, int num_words)
Definition at line 189 of file bn_intern.c.
References bn_correct_top(), BN_F_BN_SET_WORDS, bn_wexpand(), BNerr, ERR_R_MALLOC_FAILURE, and NULL.
bn_sizeof_BIGNUM()
size_t bn_sizeof_BIGNUM (void)
Definition at line 202 of file bn_intern.c.
bn_wexpand()
BIGNUM* bn_wexpand (BIGNUM * a, int words)
Definition at line 1016 of file bn_lib.c.
References bn_expand2().
Referenced by BN_add_word(), BN_copy(), BN_div(), BN_GF2m_add(), BN_lshift(), BN_mul_word(), BN_rshift(), bn_set_words(), BN_sub(), BN_uadd(), BN_usub(), and ec_GF2m_simple_group_copy().