crypto/bn/bn_word.c File Reference
bn_word.c File Reference
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Functions
BN_ULONG BN_mod_word (const BIGNUM *a, BN_ULONG w)
BN_ULONG BN_div_word (BIGNUM *a, BN_ULONG w)
int BN_add_word (BIGNUM *a, BN_ULONG w)
int BN_sub_word (BIGNUM *a, BN_ULONG w)
int BN_mul_word (BIGNUM *a, BN_ULONG w)
Function Documentation
BN_add_word()
int BN_add_word (BIGNUM * a, BN_ULONG w)
Definition at line 98 of file bn_word.c.
References bn_check_top, BN_is_zero(), BN_set_word(), BN_sub_word(), bn_wexpand(), and NULL.
Referenced by BN_sub_word().
BN_div_word()
BN_ULONG BN_div_word (BIGNUM * a, BN_ULONG w)
Definition at line 61 of file bn_word.c.
BN_mod_word()
BN_ULONG BN_mod_word (const BIGNUM * a, BN_ULONG w)
Definition at line 13 of file bn_word.c.
BN_mul_word()
int BN_mul_word (BIGNUM * a, BN_ULONG w)
Definition at line 181 of file bn_word.c.
References bn_check_top, bn_mul_words(), bn_wexpand(), BN_zero, and NULL.
BN_sub_word()
int BN_sub_word (BIGNUM * a, BN_ULONG w)
Definition at line 134 of file bn_word.c.
References BN_add_word(), bn_check_top, BN_is_zero(), BN_set_negative(), and BN_set_word().
Referenced by BN_add_word().