crypto/bn/bn_add.c File Reference
bn_add.c File Reference
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Functions
int BN_add (BIGNUM *r, const BIGNUM *a, const BIGNUM *b)
int BN_uadd (BIGNUM *r, const BIGNUM *a, const BIGNUM *b)
int BN_usub (BIGNUM *r, const BIGNUM *a, const BIGNUM *b)
int BN_sub (BIGNUM *r, const BIGNUM *a, const BIGNUM *b)
Function Documentation
BN_add()
int BN_add (BIGNUM * r, const BIGNUM * a, const BIGNUM * b)
Definition at line 14 of file bn_add.c.
Referenced by BN_mod_add(), BN_mod_sub_quick(), and BN_nnmod().
BN_sub()
int BN_sub (BIGNUM * r, const BIGNUM * a, const BIGNUM * b)
Definition at line 150 of file bn_add.c.
References add, bn_check_top, BN_uadd(), BN_ucmp(), BN_usub(), bn_wexpand(), if(), max, and NULL.
Referenced by BN_mod_lshift1_quick(), BN_mod_lshift_quick(), BN_mod_sub(), BN_mod_sub_quick(), BN_nnmod(), and BN_X931_generate_Xpq().
BN_uadd()
int BN_uadd (BIGNUM * r, const BIGNUM * a, const BIGNUM * b)
Definition at line 58 of file bn_add.c.
References bn_add_words(), bn_check_top, bn_wexpand(), bp, max, min, and NULL.
Referenced by BN_mod_add_quick(), and BN_sub().
BN_usub()
int BN_usub (BIGNUM * r, const BIGNUM * a, const BIGNUM * b)
Definition at line 107 of file bn_add.c.
References bn_check_top, bn_correct_top(), BN_F_BN_USUB, BN_R_ARG2_LT_ARG3, bn_sub_words(), bn_wexpand(), BNerr, bp, max, min, and NULL.
Referenced by BN_mod_add_quick(), BN_sub(), and ec_GFp_simple_invert().