crypto/bn/bn_depr.c File Reference
bn_depr.c File Reference
#include <openssl/opensslconf.h>
#include <stdio.h>
#include <time.h>
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Functions
BIGNUM * BN_generate_prime (BIGNUM *ret, int bits, int safe, const BIGNUM *add, const BIGNUM *rem, void(*callback)(int, int, void *), void *cb_arg)
int BN_is_prime (const BIGNUM *a, int checks, void(*callback)(int, int, void *), BN_CTX *ctx_passed, void *cb_arg)
int BN_is_prime_fasttest (const BIGNUM *a, int checks, void(*callback)(int, int, void *), BN_CTX *ctx_passed, void *cb_arg, int do_trial_division)
Function Documentation
BN_generate_prime()
BIGNUM* BN_generate_prime (BIGNUM * ret, int bits, int safe, const BIGNUM * add, const BIGNUM * rem, void(*)(int, int, void *) callback, void * cb_arg)
Definition at line 25 of file bn_depr.c.
BN_is_prime()
int BN_is_prime (const BIGNUM * a, int checks, void(*)(int, int, void *) callback, BN_CTX * ctx_passed, void * cb_arg)
Definition at line 49 of file bn_depr.c.
References BN_GENCB_set_old(), BN_is_prime_ex(), callback, and cb.
BN_is_prime_fasttest()
int BN_is_prime_fasttest (const BIGNUM * a, int checks, void(*)(int, int, void *) callback, BN_CTX * ctx_passed, void * cb_arg, int do_trial_division)
Definition at line 58 of file bn_depr.c.
References BN_GENCB_set_old(), BN_is_prime_fasttest_ex(), callback, and cb.