crypto/bn/bn_mul.c File Reference
bn_mul.c File Reference
#include <assert.h>
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Functions
BN_ULONG bn_sub_part_words (BN_ULONG *r, const BN_ULONG *a, const BN_ULONG *b, int cl, int dl)
BN_ULONG bn_add_part_words (BN_ULONG *r, const BN_ULONG *a, const BN_ULONG *b, int cl, int dl)
void bn_mul_recursive (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b, int n2, int dna, int dnb, BN_ULONG *t)
void bn_mul_part_recursive (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b, int n, int tna, int tnb, BN_ULONG *t)
void bn_mul_low_recursive (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b, int n2, BN_ULONG *t)
void bn_mul_high (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b, BN_ULONG *l, int n2, BN_ULONG *t)
int BN_mul (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
void bn_mul_normal (BN_ULONG *r, BN_ULONG *a, int na, BN_ULONG *b, int nb)
void bn_mul_low_normal (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b, int n)
Function Documentation
bn_add_part_words()
BN_ULONG bn_add_part_words (BN_ULONG * r, const BN_ULONG * a, const BN_ULONG * b, int cl, int dl)
Definition at line 155 of file bn_mul.c.
BN_mul()
int BN_mul (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Definition at line 828 of file bn_mul.c.
bn_mul_high()
void bn_mul_high (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b, BN_ULONG * l, int n2, BN_ULONG * t)
Definition at line 663 of file bn_mul.c.
References bn_add_words(), bn_cmp_words(), bn_mul_comba8(), bn_mul_recursive(), bn_sub_words(), and NULL.
bn_mul_low_normal()
void bn_mul_low_normal (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b, int n)
Definition at line 1025 of file bn_mul.c.
References bn_mul_add_words(), and bn_mul_words().
Referenced by bn_mul_low_recursive().
bn_mul_low_recursive()
void bn_mul_low_recursive (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b, int n2, BN_ULONG * t)
Definition at line 638 of file bn_mul.c.
References bn_add_words(), bn_mul_low_normal(), BN_MUL_LOW_RECURSIVE_SIZE_NORMAL, and bn_mul_recursive().
bn_mul_normal()
void bn_mul_normal (BN_ULONG * r, BN_ULONG * a, int na, BN_ULONG * b, int nb)
Definition at line 983 of file bn_mul.c.
References bn_mul_add_words(), and bn_mul_words().
Referenced by bn_mul_part_recursive(), and bn_mul_recursive().
bn_mul_part_recursive()
void bn_mul_part_recursive (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b, int n, int tna, int tnb, BN_ULONG * t)
Definition at line 480 of file bn_mul.c.
References bn_add_words(), bn_cmp_part_words(), bn_mul_comba4(), bn_mul_comba8(), bn_mul_normal(), bn_mul_recursive(), BN_MUL_RECURSIVE_SIZE_NORMAL, bn_sub_part_words(), bn_sub_words(), and t.
bn_mul_recursive()
void bn_mul_recursive (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b, int n2, int dna, int dnb, BN_ULONG * t)
Definition at line 333 of file bn_mul.c.
References bn_add_words(), bn_cmp_part_words(), bn_mul_comba4(), bn_mul_comba8(), bn_mul_normal(), BN_MUL_RECURSIVE_SIZE_NORMAL, bn_sub_part_words(), bn_sub_words(), and t.
Referenced by bn_mul_high(), bn_mul_low_recursive(), and bn_mul_part_recursive().
bn_sub_part_words()
BN_ULONG bn_sub_part_words (BN_ULONG * r, const BN_ULONG * a, const BN_ULONG * b, int cl, int dl)
Definition at line 27 of file bn_mul.c.
Referenced by bn_mul_part_recursive(), and bn_mul_recursive().