crypto/bn/bn_recp.c File Reference
bn_recp.c File Reference
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Functions
void BN_RECP_CTX_init (BN_RECP_CTX *recp)
BN_RECP_CTX * BN_RECP_CTX_new (void)
void BN_RECP_CTX_free (BN_RECP_CTX *recp)
int BN_RECP_CTX_set (BN_RECP_CTX *recp, const BIGNUM *d, BN_CTX *ctx)
int BN_mod_mul_reciprocal (BIGNUM *r, const BIGNUM *x, const BIGNUM *y, BN_RECP_CTX *recp, BN_CTX *ctx)
int BN_div_recp (BIGNUM *dv, BIGNUM *rem, const BIGNUM *m, BN_RECP_CTX *recp, BN_CTX *ctx)
int BN_reciprocal (BIGNUM *r, const BIGNUM *m, int len, BN_CTX *ctx)
Function Documentation
BN_div_recp()
int BN_div_recp (BIGNUM * dv, BIGNUM * rem, const BIGNUM * m, BN_RECP_CTX * recp, BN_CTX * ctx)
Definition at line 83 of file bn_recp.c.
BN_mod_mul_reciprocal()
int BN_mod_mul_reciprocal (BIGNUM * r, const BIGNUM * x, const BIGNUM * y, BN_RECP_CTX * recp, BN_CTX * ctx)
Definition at line 54 of file bn_recp.c.
BN_reciprocal()
int BN_reciprocal (BIGNUM * r, const BIGNUM * m, int len, BN_CTX * ctx)
Definition at line 179 of file bn_recp.c.
BN_RECP_CTX_free()
void BN_RECP_CTX_free (BN_RECP_CTX * recp)
Definition at line 33 of file bn_recp.c.
References BN_FLG_MALLOCED, BN_free(), NULL, and OPENSSL_free.
BN_RECP_CTX_init()
void BN_RECP_CTX_init (BN_RECP_CTX * recp)
Definition at line 13 of file bn_recp.c.
References bn_init().
BN_RECP_CTX_new()
BN_RECP_CTX* BN_RECP_CTX_new (void)
Definition at line 20 of file bn_recp.c.
BN_RECP_CTX_set()
int BN_RECP_CTX_set (BN_RECP_CTX * recp, const BIGNUM * d, BN_CTX * ctx)
Definition at line 44 of file bn_recp.c.
References BN_copy(), BN_num_bits(), and BN_zero.