crypto/bn/bn_mont.c File Reference
bn_mont.c File Reference
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Macros
#define MONT_WORD /* use the faster word-based algorithm */
#define BRANCH_FREE 1
Functions
int BN_mod_mul_montgomery (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_MONT_CTX *mont, BN_CTX *ctx)
int BN_from_montgomery (BIGNUM *ret, const BIGNUM *a, BN_MONT_CTX *mont, BN_CTX *ctx)
BN_MONT_CTX * BN_MONT_CTX_new (void)
void BN_MONT_CTX_init (BN_MONT_CTX *ctx)
void BN_MONT_CTX_free (BN_MONT_CTX *mont)
int BN_MONT_CTX_set (BN_MONT_CTX *mont, const BIGNUM *mod, BN_CTX *ctx)
BN_MONT_CTX * BN_MONT_CTX_copy (BN_MONT_CTX *to, BN_MONT_CTX *from)
BN_MONT_CTX * BN_MONT_CTX_set_locked (BN_MONT_CTX **pmont, CRYPTO_RWLOCK *lock, const BIGNUM *mod, BN_CTX *ctx)
Macro Definition Documentation
BRANCH_FREE
#define BRANCH_FREE 1
MONT_WORD
#define MONT_WORD /* use the faster word-based algorithm */
Definition at line 20 of file bn_mont.c.
Function Documentation
BN_from_montgomery()
int BN_from_montgomery (BIGNUM * ret, const BIGNUM * a, BN_MONT_CTX * mont, BN_CTX * ctx)
Definition at line 166 of file bn_mont.c.
Referenced by ec_GFp_mont_field_decode().
BN_mod_mul_montgomery()
int BN_mod_mul_montgomery (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_MONT_CTX * mont, BN_CTX * ctx)
Definition at line 26 of file bn_mont.c.
Referenced by BN_to_montgomery(), ec_GFp_mont_field_mul(), and ec_GFp_mont_field_sqr().
BN_MONT_CTX_copy()
BN_MONT_CTX* BN_MONT_CTX_copy (BN_MONT_CTX * to, BN_MONT_CTX * from)
Definition at line 381 of file bn_mont.c.
References BN_copy(), and NULL.
Referenced by ec_GFp_mont_group_copy(), and EC_GROUP_copy().
BN_MONT_CTX_free()
void BN_MONT_CTX_free (BN_MONT_CTX * mont)
Definition at line 235 of file bn_mont.c.
References BN_clear_free(), BN_FLG_MALLOCED, NULL, and OPENSSL_free.
Referenced by ec_GFp_mont_group_clear_finish(), ec_GFp_mont_group_copy(), ec_GFp_mont_group_finish(), EC_GROUP_clear_free(), EC_GROUP_copy(), and EC_GROUP_free().
BN_MONT_CTX_init()
void BN_MONT_CTX_init (BN_MONT_CTX * ctx)
Definition at line 225 of file bn_mont.c.
References bn_init().
BN_MONT_CTX_new()
BN_MONT_CTX* BN_MONT_CTX_new (void)
Definition at line 213 of file bn_mont.c.
Referenced by ec_GFp_mont_group_copy(), and EC_GROUP_copy().
BN_MONT_CTX_set()
int BN_MONT_CTX_set (BN_MONT_CTX * mont, const BIGNUM * mod, BN_CTX * ctx)
Definition at line 247 of file bn_mont.c.
BN_MONT_CTX_set_locked()
BN_MONT_CTX* BN_MONT_CTX_set_locked (BN_MONT_CTX ** pmont, CRYPTO_RWLOCK * lock, const BIGNUM * mod, BN_CTX * ctx)
Definition at line 398 of file bn_mont.c.