crypto/bn/bn_mpi.c File Reference
bn_mpi.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Functions
int BN_bn2mpi (const BIGNUM *a, unsigned char *d)
BIGNUM * BN_mpi2bn (const unsigned char *d, int n, BIGNUM *ain)
Function Documentation
BN_bn2mpi()
int BN_bn2mpi (const BIGNUM * a, unsigned char * d)
Definition at line 14 of file bn_mpi.c.
References bits, BN_bn2bin(), BN_num_bits(), and NULL.
BN_mpi2bn()
BIGNUM* BN_mpi2bn (const unsigned char * d, int n, BIGNUM * ain)
Definition at line 42 of file bn_mpi.c.
References BN_bin2bn(), bn_check_top, BN_clear_bit(), BN_F_BN_MPI2BN, BN_free(), BN_new(), BN_num_bits(), BN_R_ENCODING_ERROR, BN_R_INVALID_LENGTH, BNerr, len, and NULL.