crypto/bn/bn_x931p.c File Reference
bn_x931p.c File Reference
#include <stdio.h>
#include <openssl/bn.h>
#include "bn_lcl.h"
Functions
int BN_X931_derive_prime_ex (BIGNUM *p, BIGNUM *p1, BIGNUM *p2, const BIGNUM *Xp, const BIGNUM *Xp1, const BIGNUM *Xp2, const BIGNUM *e, BN_CTX *ctx, BN_GENCB *cb)
int BN_X931_generate_Xpq (BIGNUM *Xp, BIGNUM *Xq, int nbits, BN_CTX *ctx)
int BN_X931_generate_prime_ex (BIGNUM *p, BIGNUM *p1, BIGNUM *p2, BIGNUM *Xp1, BIGNUM *Xp2, const BIGNUM *Xp, const BIGNUM *e, BN_CTX *ctx, BN_GENCB *cb)
Function Documentation
BN_X931_derive_prime_ex()
int BN_X931_derive_prime_ex (BIGNUM * p, BIGNUM * p1, BIGNUM * p2, const BIGNUM * Xp, const BIGNUM * Xp1, const BIGNUM * Xp2, const BIGNUM * e, BN_CTX * ctx, BN_GENCB * cb)
Definition at line 51 of file bn_x931p.c.
BN_X931_generate_prime_ex()
int BN_X931_generate_prime_ex (BIGNUM * p, BIGNUM * p1, BIGNUM * p2, BIGNUM * Xp1, BIGNUM * Xp2, const BIGNUM * Xp, const BIGNUM * e, BN_CTX * ctx, BN_GENCB * cb)
Definition at line 211 of file bn_x931p.c.
Referenced by RSA_X931_generate_key_ex().
BN_X931_generate_Xpq()
int BN_X931_generate_Xpq (BIGNUM * Xp, BIGNUM * Xq, int nbits, BN_CTX * ctx)
Definition at line 160 of file bn_x931p.c.
References BN_CTX_end(), BN_CTX_get(), BN_CTX_start(), BN_num_bits(), BN_rand(), BN_RAND_BOTTOM_ANY, BN_RAND_TOP_TWO, BN_sub(), and t.
Referenced by RSA_X931_generate_key_ex().