crypto/bn/bn_prime.c File Reference
bn_prime.c File Reference
#include <stdio.h>
#include <time.h>
#include "internal/cryptlib.h"
#include "bn_lcl.h"
#include "bn_prime.h"
Functions
int BN_GENCB_call (BN_GENCB *cb, int a, int b)
int BN_generate_prime_ex (BIGNUM *ret, int bits, int safe, const BIGNUM *add, const BIGNUM *rem, BN_GENCB *cb)
int BN_is_prime_ex (const BIGNUM *a, int checks, BN_CTX *ctx_passed, BN_GENCB *cb)
int BN_is_prime_fasttest_ex (const BIGNUM *a, int checks, BN_CTX *ctx_passed, int do_trial_division, BN_GENCB *cb)
int bn_probable_prime_dh_retry (BIGNUM *rnd, int bits, BN_CTX *ctx)
int bn_probable_prime_dh_coprime (BIGNUM *rnd, int bits, BN_CTX *ctx)
int bn_probable_prime_dh (BIGNUM *rnd, int bits, const BIGNUM *add, const BIGNUM *rem, BN_CTX *ctx)
Function Documentation
BN_GENCB_call()
int BN_GENCB_call (BN_GENCB * cb, int a, int b)
Definition at line 79 of file bn_prime.c.
BN_generate_prime_ex()
int BN_generate_prime_ex (BIGNUM * ret, int bits, int safe, const BIGNUM * add, const BIGNUM * rem, BN_GENCB * cb)
Definition at line 101 of file bn_prime.c.
BN_is_prime_ex()
int BN_is_prime_ex (const BIGNUM * a, int checks, BN_CTX * ctx_passed, BN_GENCB * cb)
Definition at line 194 of file bn_prime.c.
References BN_is_prime_fasttest_ex().
Referenced by BN_is_prime().
BN_is_prime_fasttest_ex()
int BN_is_prime_fasttest_ex (const BIGNUM * a, int checks, BN_CTX * ctx_passed, int do_trial_division, BN_GENCB * cb)
Definition at line 200 of file bn_prime.c.
Referenced by BN_is_prime_ex(), and BN_is_prime_fasttest().
bn_probable_prime_dh()
int bn_probable_prime_dh (BIGNUM * rnd, int bits, const BIGNUM * add, const BIGNUM * rem, BN_CTX * ctx)
Definition at line 494 of file bn_prime.c.
bn_probable_prime_dh_coprime()
int bn_probable_prime_dh_coprime (BIGNUM * rnd, int bits, BN_CTX * ctx)
Definition at line 335 of file bn_prime.c.
bn_probable_prime_dh_retry()
int bn_probable_prime_dh_retry (BIGNUM * rnd, int bits, BN_CTX * ctx)
Definition at line 308 of file bn_prime.c.