crypto/bn/bn_sqr.c File Reference
bn_sqr.c File Reference
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Functions
int BN_sqr (BIGNUM *r, const BIGNUM *a, BN_CTX *ctx)
void bn_sqr_normal (BN_ULONG *r, const BN_ULONG *a, int n, BN_ULONG *tmp)
void bn_sqr_recursive (BN_ULONG *r, const BN_ULONG *a, int n2, BN_ULONG *t)
Function Documentation
BN_sqr()
int BN_sqr (BIGNUM * r, const BIGNUM * a, BN_CTX * ctx)
Definition at line 17 of file bn_sqr.c.
References max.
Referenced by BN_mod_sqr().
bn_sqr_normal()
void bn_sqr_normal (BN_ULONG * r, const BN_ULONG * a, int n, BN_ULONG * tmp)
Definition at line 105 of file bn_sqr.c.
References bn_add_words(), bn_mul_add_words(), bn_mul_words(), bn_sqr_words(), and max.
Referenced by bn_sqr_comba4(), and bn_sqr_recursive().
bn_sqr_recursive()
void bn_sqr_recursive (BN_ULONG * r, const BN_ULONG * a, int n2, BN_ULONG * t)
Definition at line 152 of file bn_sqr.c.
References bn_add_words(), bn_cmp_words(), bn_sqr_comba4(), bn_sqr_comba8(), bn_sqr_normal(), BN_SQR_RECURSIVE_SIZE_NORMAL, bn_sub_words(), and t.