crypto/bn/bn_ctx.c File Reference
bn_ctx.c File Reference
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Data Structures
struct BN_POOL_ITEM
struct BN_POOL
struct BN_STACK
struct BN_CTX
Macros
#define BN_CTX_POOL_SIZE 16
#define BN_CTX_START_FRAMES 32
#define CTXDBG_ENTRY(str, ctx)
#define CTXDBG_EXIT(ctx)
#define CTXDBG_RET(ctx, ret)
Functions
BN_CTX * BN_CTX_new (void)
BN_CTX * BN_CTX_secure_new (void)
void BN_CTX_free (BN_CTX *ctx)
void BN_CTX_start (BN_CTX *ctx)
void BN_CTX_end (BN_CTX *ctx)
BIGNUM * BN_CTX_get (BN_CTX *ctx)
Macro Definition Documentation
BN_CTX_POOL_SIZE
#define BN_CTX_POOL_SIZE 16
Definition at line 27 of file bn_ctx.c.
Referenced by BN_CTX_free().
BN_CTX_START_FRAMES
#define BN_CTX_START_FRAMES 32
Definition at line 29 of file bn_ctx.c.
CTXDBG_ENTRY
#define CTXDBG_ENTRY (str, ctx)
Definition at line 128 of file bn_ctx.c.
Referenced by BN_CTX_end(), and BN_CTX_start().
CTXDBG_EXIT
#define CTXDBG_EXIT (ctx)
Definition at line 129 of file bn_ctx.c.
CTXDBG_RET
#define CTXDBG_RET (ctx, ret)
Definition at line 130 of file bn_ctx.c.
Function Documentation
BN_CTX_end()
void BN_CTX_end (BN_CTX * ctx)
Definition at line 195 of file bn_ctx.c.
References CTXDBG_ENTRY, and fp.
Referenced by BN_div(), BN_X931_generate_Xpq(), EC_KEY_set_public_key_affine_coordinates(), and RSA_X931_generate_key_ex().
BN_CTX_free()
void BN_CTX_free (BN_CTX * ctx)
Definition at line 157 of file bn_ctx.c.
References BN_CTX_POOL_SIZE, BN_POOL_ITEM::next, NULL, and BN_POOL_ITEM::vals.
Referenced by EC_KEY_set_public_key_affine_coordinates(), RSA_X931_generate_key_ex(), SRP_Calc_A(), and SRP_create_verifier_BN().
BN_CTX_get()
BIGNUM* BN_CTX_get (BN_CTX * ctx)
Definition at line 212 of file bn_ctx.c.
Referenced by BN_div(), BN_X931_generate_Xpq(), EC_KEY_set_public_key_affine_coordinates(), and RSA_X931_generate_key_ex().
BN_CTX_new()
BN_CTX* BN_CTX_new (void)
Definition at line 134 of file bn_ctx.c.
Referenced by ec_GF2m_simple_mul(), EC_KEY_set_public_key_affine_coordinates(), ec_precompute_mont_data(), RSA_X931_generate_key_ex(), SRP_Calc_A(), and SRP_create_verifier_BN().
BN_CTX_secure_new()
BN_CTX* BN_CTX_secure_new (void)
Definition at line 148 of file bn_ctx.c.
BN_CTX_start()
void BN_CTX_start (BN_CTX * ctx)
Definition at line 181 of file bn_ctx.c.
References CTXDBG_ENTRY.
Referenced by BN_div(), BN_X931_generate_Xpq(), EC_KEY_set_public_key_affine_coordinates(), and RSA_X931_generate_key_ex().