crypto/bn/bn_print.c File Reference
bn_print.c File Reference
#include <stdio.h>
#include <ctype.h>
#include <limits.h>
#include "internal/cryptlib.h"
#include <openssl/buffer.h>
#include "bn_lcl.h"
Macros
#define BUF_REMAIN (num+3 - (size_t)(p - buf))
Functions
char * BN_bn2hex (const BIGNUM *a)
char * BN_bn2dec (const BIGNUM *a)
int BN_hex2bn (BIGNUM **bn, const char *a)
int BN_dec2bn (BIGNUM **bn, const char *a)
int BN_asc2bn (BIGNUM **bn, const char *a)
int BN_print_fp (FILE *fp, const BIGNUM *a)
int BN_print (BIO *bp, const BIGNUM *a)
char * BN_options (void)
Macro Definition Documentation
BUF_REMAIN
#define BUF_REMAIN (num+3 - (size_t)(p - buf))
Function Documentation
BN_asc2bn()
int BN_asc2bn (BIGNUM ** bn, const char * a)
Definition at line 269 of file bn_print.c.
References BN_dec2bn(), and BN_hex2bn().
BN_bn2dec()
char* BN_bn2dec (const BIGNUM * a)
Definition at line 55 of file bn_print.c.
Referenced by i2s_ASN1_ENUMERATED(), and i2s_ASN1_INTEGER().
BN_bn2hex()
char* BN_bn2hex (const BIGNUM * a)
Definition at line 20 of file bn_print.c.
Referenced by TS_ASN1_INTEGER_print_bio().
BN_dec2bn()
int BN_dec2bn (BIGNUM ** bn, const char * a)
Definition at line 199 of file bn_print.c.
Referenced by BN_asc2bn().
BN_hex2bn()
int BN_hex2bn (BIGNUM ** bn, const char * a)
Definition at line 126 of file bn_print.c.
Referenced by BN_asc2bn().
BN_options()
char* BN_options (void)
Definition at line 329 of file bn_print.c.
BN_print()
int BN_print (BIO * bp, const BIGNUM * a)
Definition at line 304 of file bn_print.c.
BN_print_fp()
int BN_print_fp (FILE * fp, const BIGNUM * a)
Definition at line 290 of file bn_print.c.