crypto/bn/bn_gf2m.c File Reference
bn_gf2m.c File Reference
#include <assert.h>
#include <limits.h>
#include <stdio.h>
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Macros
#define MAX_ITERATIONS 50
Functions
int BN_GF2m_add (BIGNUM *r, const BIGNUM *a, const BIGNUM *b)
int BN_GF2m_mod_arr (BIGNUM *r, const BIGNUM *a, const int p[])
int BN_GF2m_mod (BIGNUM *r, const BIGNUM *a, const BIGNUM *p)
int BN_GF2m_mod_mul_arr (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const int p[], BN_CTX *ctx)
int BN_GF2m_mod_mul (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_mod_sqr_arr (BIGNUM *r, const BIGNUM *a, const int p[], BN_CTX *ctx)
int BN_GF2m_mod_sqr (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_mod_inv (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_mod_inv_arr (BIGNUM *r, const BIGNUM *xx, const int p[], BN_CTX *ctx)
int BN_GF2m_mod_div (BIGNUM *r, const BIGNUM *y, const BIGNUM *x, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_mod_div_arr (BIGNUM *r, const BIGNUM *yy, const BIGNUM *xx, const int p[], BN_CTX *ctx)
int BN_GF2m_mod_exp_arr (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const int p[], BN_CTX *ctx)
int BN_GF2m_mod_exp (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_mod_sqrt_arr (BIGNUM *r, const BIGNUM *a, const int p[], BN_CTX *ctx)
int BN_GF2m_mod_sqrt (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_mod_solve_quad_arr (BIGNUM *r, const BIGNUM *a_, const int p[], BN_CTX *ctx)
int BN_GF2m_mod_solve_quad (BIGNUM *r, const BIGNUM *a, const BIGNUM *p, BN_CTX *ctx)
int BN_GF2m_poly2arr (const BIGNUM *a, int p[], int max)
int BN_GF2m_arr2poly (const int p[], BIGNUM *a)
Macro Definition Documentation
MAX_ITERATIONS
#define MAX_ITERATIONS 50
Definition at line 33 of file bn_gf2m.c.
Function Documentation
BN_GF2m_add()
int BN_GF2m_add (BIGNUM * r, const BIGNUM * a, const BIGNUM * b)
Definition at line 260 of file bn_gf2m.c.
References bn_check_top, bn_correct_top(), bn_wexpand(), and NULL.
Referenced by ec_GF2m_simple_invert().
BN_GF2m_arr2poly()
int BN_GF2m_arr2poly (const int p[], BIGNUM * a)
Definition at line 1209 of file bn_gf2m.c.
References bn_check_top, BN_set_bit(), and BN_zero.
BN_GF2m_mod()
int BN_GF2m_mod (BIGNUM * r, const BIGNUM * a, const BIGNUM * p)
Definition at line 398 of file bn_gf2m.c.
BN_GF2m_mod_arr()
int BN_GF2m_mod_arr (BIGNUM * r, const BIGNUM * a, const int p[])
Definition at line 300 of file bn_gf2m.c.
BN_GF2m_mod_div()
int BN_GF2m_mod_div (BIGNUM * r, const BIGNUM * y, const BIGNUM * x, const BIGNUM * p, BN_CTX * ctx)
Definition at line 760 of file bn_gf2m.c.
References NULL.
Referenced by ec_GF2m_simple_field_div().
BN_GF2m_mod_div_arr()
int BN_GF2m_mod_div_arr (BIGNUM * r, const BIGNUM * yy, const BIGNUM * xx, const int p[], BN_CTX * ctx)
Definition at line 881 of file bn_gf2m.c.
BN_GF2m_mod_exp()
int BN_GF2m_mod_exp (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * p, BN_CTX * ctx)
Definition at line 955 of file bn_gf2m.c.
BN_GF2m_mod_exp_arr()
int BN_GF2m_mod_exp_arr (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const int p[], BN_CTX * ctx)
Definition at line 909 of file bn_gf2m.c.
BN_GF2m_mod_inv()
int BN_GF2m_mod_inv (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, BN_CTX * ctx)
Definition at line 560 of file bn_gf2m.c.
BN_GF2m_mod_inv_arr()
int BN_GF2m_mod_inv_arr (BIGNUM * r, const BIGNUM * xx, const int p[], BN_CTX * ctx)
Definition at line 734 of file bn_gf2m.c.
BN_GF2m_mod_mul()
int BN_GF2m_mod_mul (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * p, BN_CTX * ctx)
Definition at line 473 of file bn_gf2m.c.
BN_GF2m_mod_mul_arr()
int BN_GF2m_mod_mul_arr (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const int p[], BN_CTX * ctx)
Definition at line 418 of file bn_gf2m.c.
Referenced by ec_GF2m_simple_field_mul().
BN_GF2m_mod_solve_quad()
int BN_GF2m_mod_solve_quad (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, BN_CTX * ctx)
Definition at line 1145 of file bn_gf2m.c.
BN_GF2m_mod_solve_quad_arr()
int BN_GF2m_mod_solve_quad_arr (BIGNUM * r, const BIGNUM * a_, const int p[], BN_CTX * ctx)
Definition at line 1041 of file bn_gf2m.c.
BN_GF2m_mod_sqr()
int BN_GF2m_mod_sqr (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, BN_CTX * ctx)
Definition at line 532 of file bn_gf2m.c.
BN_GF2m_mod_sqr_arr()
int BN_GF2m_mod_sqr_arr (BIGNUM * r, const BIGNUM * a, const int p[], BN_CTX * ctx)
Definition at line 497 of file bn_gf2m.c.
Referenced by ec_GF2m_simple_field_sqr().
BN_GF2m_mod_sqrt()
int BN_GF2m_mod_sqrt (BIGNUM * r, const BIGNUM * a, const BIGNUM * p, BN_CTX * ctx)
Definition at line 1016 of file bn_gf2m.c.
BN_GF2m_mod_sqrt_arr()
int BN_GF2m_mod_sqrt_arr (BIGNUM * r, const BIGNUM * a, const int p[], BN_CTX * ctx)
Definition at line 982 of file bn_gf2m.c.
BN_GF2m_poly2arr()
int BN_GF2m_poly2arr (const BIGNUM * a, int p[], int max)
Definition at line 1174 of file bn_gf2m.c.