crypto/bn/bn_mod.c File Reference
bn_mod.c File Reference
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Functions
int BN_nnmod (BIGNUM *r, const BIGNUM *m, const BIGNUM *d, BN_CTX *ctx)
int BN_mod_add (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *m, BN_CTX *ctx)
int BN_mod_add_quick (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *m)
int BN_mod_sub (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *m, BN_CTX *ctx)
int BN_mod_sub_quick (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *m)
int BN_mod_mul (BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *m, BN_CTX *ctx)
int BN_mod_sqr (BIGNUM *r, const BIGNUM *a, const BIGNUM *m, BN_CTX *ctx)
int BN_mod_lshift1 (BIGNUM *r, const BIGNUM *a, const BIGNUM *m, BN_CTX *ctx)
int BN_mod_lshift1_quick (BIGNUM *r, const BIGNUM *a, const BIGNUM *m)
int BN_mod_lshift (BIGNUM *r, const BIGNUM *a, int n, const BIGNUM *m, BN_CTX *ctx)
int BN_mod_lshift_quick (BIGNUM *r, const BIGNUM *a, int n, const BIGNUM *m)
Function Documentation
BN_mod_add()
int BN_mod_add (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * m, BN_CTX * ctx)
Definition at line 28 of file bn_mod.c.
References BN_add(), and BN_nnmod().
BN_mod_add_quick()
int BN_mod_add_quick (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * m)
Definition at line 40 of file bn_mod.c.
References BN_uadd(), BN_ucmp(), and BN_usub().
BN_mod_lshift()
int BN_mod_lshift (BIGNUM * r, const BIGNUM * a, int n, const BIGNUM * m, BN_CTX * ctx)
Definition at line 132 of file bn_mod.c.
References NULL.
BN_mod_lshift1()
int BN_mod_lshift1 (BIGNUM * r, const BIGNUM * a, const BIGNUM * m, BN_CTX * ctx)
Definition at line 110 of file bn_mod.c.
References bn_check_top, BN_lshift1(), and BN_nnmod().
BN_mod_lshift1_quick()
int BN_mod_lshift1_quick (BIGNUM * r, const BIGNUM * a, const BIGNUM * m)
Definition at line 122 of file bn_mod.c.
References bn_check_top, BN_cmp(), BN_lshift1(), and BN_sub().
BN_mod_lshift_quick()
int BN_mod_lshift_quick (BIGNUM * r, const BIGNUM * a, int n, const BIGNUM * m)
Definition at line 159 of file bn_mod.c.
References bn_check_top, BN_cmp(), BN_copy(), BN_F_BN_MOD_LSHIFT_QUICK, BN_lshift(), BN_lshift1(), BN_num_bits(), BN_R_INPUT_NOT_REDUCED, BN_sub(), BNerr, and NULL.
BN_mod_mul()
int BN_mod_mul (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * m, BN_CTX * ctx)
Definition at line 73 of file bn_mod.c.
References t.
Referenced by ec_GFp_simple_field_mul().
BN_mod_sqr()
int BN_mod_sqr (BIGNUM * r, const BIGNUM * a, const BIGNUM * m, BN_CTX * ctx)
Definition at line 102 of file bn_mod.c.
References BN_mod, and BN_sqr().
Referenced by ec_GFp_simple_field_sqr().
BN_mod_sub()
int BN_mod_sub (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * m, BN_CTX * ctx)
Definition at line 50 of file bn_mod.c.
References BN_nnmod(), and BN_sub().
BN_mod_sub_quick()
int BN_mod_sub_quick (BIGNUM * r, const BIGNUM * a, const BIGNUM * b, const BIGNUM * m)
Definition at line 62 of file bn_mod.c.
References BN_add(), and BN_sub().
BN_nnmod()
int BN_nnmod (BIGNUM * r, const BIGNUM * m, const BIGNUM * d, BN_CTX * ctx)
Definition at line 13 of file bn_mod.c.
References BN_add(), BN_mod, and BN_sub().
Referenced by BN_mod_add(), BN_mod_lshift1(), and BN_mod_sub().