crypto/bn/bn_lcl.h File Reference
bn_lcl.h File Reference
#include <openssl/opensslconf.h>
#include "internal/bn_conf.h"
#include "internal/bn_int.h"
Data Structures
struct BIGNUM
struct BN_MONT_CTX
struct BN_RECP_CTX
struct BN_GENCB
Macros
#define BN_MUL_COMBA
#define BN_SQR_COMBA
#define BN_RECURSION
#define bn_pollute(a)
#define bn_check_top(a)
#define bn_fix_top(a) bn_correct_top(a)
#define bn_check_size(bn, bits)
#define bn_wcheck_size(bn, words)
#define BN_window_bits_for_exponent_size(b)
#define MOD_EXP_CTIME_MIN_CACHE_LINE_WIDTH (64)
#define MOD_EXP_CTIME_MIN_CACHE_LINE_MASK (MOD_EXP_CTIME_MIN_CACHE_LINE_WIDTH - 1)
#define BN_window_bits_for_ctime_exponent_size(b)
#define BN_MAX_WINDOW_BITS_FOR_CTIME_EXPONENT_SIZE (6)
#define BN_MULL_SIZE_NORMAL (16)/* 32 */
#define BN_MUL_RECURSIVE_SIZE_NORMAL (16)/* 32 less than */
#define BN_SQR_RECURSIVE_SIZE_NORMAL (16)/* 32 */
#define BN_MUL_LOW_RECURSIVE_SIZE_NORMAL (32)/* 32 */
#define BN_MONT_CTX_SET_SIZE_WORD (64)/* 32 */
#define PTR_SIZE_INT size_t
#define Lw(t) (((BN_ULONG)(t))&BN_MASK2)
#define Hw(t) (((BN_ULONG)((t)>>BN_BITS2))&BN_MASK2)
#define bn_clear_top2max(a)
#define LBITS(a) ((a)&BN_MASK2l)
#define HBITS(a) (((a)>>BN_BITS4)&BN_MASK2l)
#define L2HBITS(a) (((a)<<BN_BITS4)&BN_MASK2)
#define LLBITS(a) ((a)&BN_MASKl)
#define LHBITS(a) (((a)>>BN_BITS2)&BN_MASKl)
#define LL2HBITS(a) ((BN_ULLONG)((a)&BN_MASKl)<<BN_BITS2)
#define mul64(l, h, bl, bh)
#define sqr64(lo, ho, in)
#define mul_add(r, a, bl, bh, c)
#define mul(r, a, bl, bh, c)
Functions
BN_ULONG bn_mul_add_words (BN_ULONG *rp, const BN_ULONG *ap, int num, BN_ULONG w)
BN_ULONG bn_mul_words (BN_ULONG *rp, const BN_ULONG *ap, int num, BN_ULONG w)
void bn_sqr_words (BN_ULONG *rp, const BN_ULONG *ap, int num)
BN_ULONG bn_div_words (BN_ULONG h, BN_ULONG l, BN_ULONG d)
BN_ULONG bn_add_words (BN_ULONG *rp, const BN_ULONG *ap, const BN_ULONG *bp, int num)
BN_ULONG bn_sub_words (BN_ULONG *rp, const BN_ULONG *ap, const BN_ULONG *bp, int num)
void BN_RECP_CTX_init (BN_RECP_CTX *recp)
void BN_MONT_CTX_init (BN_MONT_CTX *ctx)
void bn_init (BIGNUM *a)
void bn_mul_normal (BN_ULONG *r, BN_ULONG *a, int na, BN_ULONG *b, int nb)
void bn_mul_comba8 (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b)
void bn_mul_comba4 (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b)
void bn_sqr_normal (BN_ULONG *r, const BN_ULONG *a, int n, BN_ULONG *tmp)
void bn_sqr_comba8 (BN_ULONG *r, const BN_ULONG *a)
void bn_sqr_comba4 (BN_ULONG *r, const BN_ULONG *a)
int bn_cmp_words (const BN_ULONG *a, const BN_ULONG *b, int n)
int bn_cmp_part_words (const BN_ULONG *a, const BN_ULONG *b, int cl, int dl)
void bn_mul_recursive (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b, int n2, int dna, int dnb, BN_ULONG *t)
void bn_mul_part_recursive (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b, int n, int tna, int tnb, BN_ULONG *t)
void bn_sqr_recursive (BN_ULONG *r, const BN_ULONG *a, int n2, BN_ULONG *t)
void bn_mul_low_normal (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b, int n)
void bn_mul_low_recursive (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b, int n2, BN_ULONG *t)
void bn_mul_high (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b, BN_ULONG *l, int n2, BN_ULONG *t)
BN_ULONG bn_add_part_words (BN_ULONG *r, const BN_ULONG *a, const BN_ULONG *b, int cl, int dl)
BN_ULONG bn_sub_part_words (BN_ULONG *r, const BN_ULONG *a, const BN_ULONG *b, int cl, int dl)
int bn_mul_mont (BN_ULONG *rp, const BN_ULONG *ap, const BN_ULONG *bp, const BN_ULONG *np, const BN_ULONG *n0, int num)
BIGNUM * int_bn_mod_inverse (BIGNUM *in, const BIGNUM *a, const BIGNUM *n, BN_CTX *ctx, int *noinv)
int bn_probable_prime_dh (BIGNUM *rnd, int bits, const BIGNUM *add, const BIGNUM *rem, BN_CTX *ctx)
int bn_probable_prime_dh_retry (BIGNUM *rnd, int bits, BN_CTX *ctx)
int bn_probable_prime_dh_coprime (BIGNUM *rnd, int bits, BN_CTX *ctx)
Macro Definition Documentation
bn_check_size
#define bn_check_size (bn, bits)
Definition at line 203 of file bn_lcl.h.
bn_check_top
#define bn_check_top (a)
Definition at line 201 of file bn_lcl.h.
Referenced by BN_add_word(), BN_bn2lebinpad(), BN_clear(), BN_clear_bit(), BN_clear_free(), BN_cmp(), BN_copy(), BN_div(), BN_dup(), bn_expand2(), BN_free(), BN_GF2m_add(), BN_GF2m_arr2poly(), bn_init(), BN_is_bit_set(), BN_lshift(), BN_mask_bits(), BN_mod_lshift1(), BN_mod_lshift1_quick(), BN_mod_lshift_quick(), BN_mpi2bn(), BN_mul_word(), BN_num_bits(), BN_rshift(), BN_set_word(), BN_sub(), BN_sub_word(), BN_swap(), BN_uadd(), BN_ucmp(), and BN_usub().
bn_clear_top2max
#define bn_clear_top2max (a)
Definition at line 475 of file bn_lcl.h.
Referenced by BN_div().
bn_fix_top
#define bn_fix_top (a) bn_correct_top(a)
Definition at line 202 of file bn_lcl.h.
BN_MAX_WINDOW_BITS_FOR_CTIME_EXPONENT_SIZE
#define BN_MAX_WINDOW_BITS_FOR_CTIME_EXPONENT_SIZE (6)
Definition at line 319 of file bn_lcl.h.
BN_MONT_CTX_SET_SIZE_WORD
#define BN_MONT_CTX_SET_SIZE_WORD (64)/* 32 */
Definition at line 337 of file bn_lcl.h.
BN_MUL_COMBA
#define BN_MUL_COMBA
Definition at line 43 of file bn_lcl.h.
BN_MUL_LOW_RECURSIVE_SIZE_NORMAL
#define BN_MUL_LOW_RECURSIVE_SIZE_NORMAL (32)/* 32 */
Definition at line 336 of file bn_lcl.h.
Referenced by bn_mul_low_recursive().
BN_MUL_RECURSIVE_SIZE_NORMAL
#define BN_MUL_RECURSIVE_SIZE_NORMAL (16)/* 32 less than */
Definition at line 334 of file bn_lcl.h.
Referenced by bn_mul_part_recursive(), and bn_mul_recursive().
BN_MULL_SIZE_NORMAL
#define BN_MULL_SIZE_NORMAL (16)/* 32 */
Definition at line 333 of file bn_lcl.h.
bn_pollute
#define bn_pollute (a)
Definition at line 200 of file bn_lcl.h.
Referenced by bn_correct_top().
BN_RECURSION
#define BN_RECURSION
Definition at line 45 of file bn_lcl.h.
BN_SQR_COMBA
#define BN_SQR_COMBA
Definition at line 44 of file bn_lcl.h.
BN_SQR_RECURSIVE_SIZE_NORMAL
#define BN_SQR_RECURSIVE_SIZE_NORMAL (16)/* 32 */
Definition at line 335 of file bn_lcl.h.
Referenced by bn_sqr_recursive().
bn_wcheck_size
#define bn_wcheck_size (bn, words)
Definition at line 204 of file bn_lcl.h.
Referenced by BN_consttime_swap().
BN_window_bits_for_ctime_exponent_size
#define BN_window_bits_for_ctime_exponent_size (b)
Value:
((b) > 937 ? 6 : \
                 (b) > 306 ? 5 : \
                 (b) >  89 ? 4 : \
                 (b) >  22 ? 3 : 1)
Definition at line 314 of file bn_lcl.h.
BN_window_bits_for_exponent_size
#define BN_window_bits_for_exponent_size (b)
Value:
((b) > 671 ? 6 : \
                 (b) > 239 ? 5 : \
                 (b) >  79 ? 4 : \
                 (b) >  23 ? 3 : 1)
Definition at line 290 of file bn_lcl.h.
HBITS
#define HBITS (a) (((a)>>BN_BITS4)&BN_MASK2l)
Definition at line 563 of file bn_lcl.h.
Referenced by BN_div(), bn_mul_words(), and bn_sqr_comba4().
Hw
#define Hw (t) (((BN_ULONG)((t)>>BN_BITS2))&BN_MASK2)
Definition at line 464 of file bn_lcl.h.
L2HBITS
#define L2HBITS (a) (((a)<<BN_BITS4)&BN_MASK2)
Definition at line 564 of file bn_lcl.h.
LBITS
#define LBITS (a) ((a)&BN_MASK2l)
Definition at line 562 of file bn_lcl.h.
Referenced by BN_div(), bn_mul_words(), and bn_sqr_comba4().
LHBITS
#define LHBITS (a) (((a)>>BN_BITS2)&BN_MASKl)
Definition at line 567 of file bn_lcl.h.
LL2HBITS
#define LL2HBITS (a) ((BN_ULLONG)((a)&BN_MASKl)<<BN_BITS2)
Definition at line 568 of file bn_lcl.h.
LLBITS
#define LLBITS (a) ((a)&BN_MASKl)
Definition at line 566 of file bn_lcl.h.
Lw
#define Lw (t) (((BN_ULONG)(t))&BN_MASK2)
Definition at line 463 of file bn_lcl.h.
MOD_EXP_CTIME_MIN_CACHE_LINE_MASK
#define MOD_EXP_CTIME_MIN_CACHE_LINE_MASK (MOD_EXP_CTIME_MIN_CACHE_LINE_WIDTH - 1)
Definition at line 301 of file bn_lcl.h.
MOD_EXP_CTIME_MIN_CACHE_LINE_WIDTH
#define MOD_EXP_CTIME_MIN_CACHE_LINE_WIDTH (64)
Definition at line 300 of file bn_lcl.h.
mul
#define mul (r, a, bl, bh, c)
Value:
{ \
        BN_ULONG l,h; \
 \
        h= (a); \
        l=LBITS(h); \
        h=HBITS(h); \
        mul64(l,h,(bl),(bh)); \
 \
        /* non-multiply part */ \
        l+=(c); if ((l&BN_MASK2) < (c)) h++; \
        (c)=h&BN_MASK2; \
        (r)=l&BN_MASK2; \
        }
Definition at line 621 of file bn_lcl.h.
Referenced by bn_mul_words(), and bn_sqr_comba4().
mul64
#define mul64 (l, h, bl, bh)
Value:
{ \
        BN_ULONG m,m1,lt,ht; \
 \
        lt=l; \
        ht=h; \
        m =(bh)*(lt); \
        lt=(bl)*(lt); \
        m1=(bl)*(ht); \
        ht =(bh)*(ht); \
        m=(m+m1)&BN_MASK2; if (m < m1) ht+=L2HBITS((BN_ULONG)1); \
        ht+=HBITS(m); \
        m1=L2HBITS(m); \
        lt=(lt+m1)&BN_MASK2; if (lt < m1) ht++; \
        (l)=lt; \
        (h)=ht; \
        }
Definition at line 570 of file bn_lcl.h.
Referenced by BN_div().
mul_add
#define mul_add (r, a, bl, bh, c)
Value:
{ \
        BN_ULONG l,h; \
 \
        h= (a); \
        l=LBITS(h); \
        h=HBITS(h); \
        mul64(l,h,(bl),(bh)); \
 \
        /* non-multiply part */ \
        l=(l+(c))&BN_MASK2; if (l < (c)) h++; \
        (c)=(r); \
        l=(l+(c))&BN_MASK2; if (l < (c)) h++; \
        (c)=h&BN_MASK2; \
        (r)=l; \
        }
Definition at line 605 of file bn_lcl.h.
Referenced by bn_sqr_comba4().
PTR_SIZE_INT
#define PTR_SIZE_INT size_t
Definition at line 354 of file bn_lcl.h.
Referenced by BN_nist_mod_521().
sqr64
#define sqr64 (lo, ho, in)
Value:
{ \
        BN_ULONG l,h,m; \
 \
        h=(in); \
        l=LBITS(h); \
        h=HBITS(h); \
        m =(l)*(h); \
        l*=l; \
        h*=h; \
        h+=(m&BN_MASK2h1)>>(BN_BITS4-1); \
        m =(m&BN_MASK2l)<<(BN_BITS4+1); \
        l=(l+m)&BN_MASK2; if (l < m) h++; \
        (lo)=l; \
        (ho)=h; \
        }
Definition at line 588 of file bn_lcl.h.
Referenced by bn_sqr_words().
Function Documentation
bn_add_part_words()
BN_ULONG bn_add_part_words (BN_ULONG * r, const BN_ULONG * a, const BN_ULONG * b, int cl, int dl)
Definition at line 155 of file bn_mul.c.
bn_add_words()
BN_ULONG bn_add_words (BN_ULONG * rp, const BN_ULONG * ap, const BN_ULONG * bp, int num)
Definition at line 313 of file bn_asm.c.
Referenced by BN_div(), bn_mul_high(), bn_mul_low_recursive(), bn_mul_part_recursive(), bn_mul_recursive(), bn_sqr_normal(), bn_sqr_recursive(), and BN_uadd().
bn_cmp_part_words()
int bn_cmp_part_words (const BN_ULONG * a, const BN_ULONG * b, int cl, int dl)
Definition at line 803 of file bn_lib.c.
References bn_cmp_words().
Referenced by bn_mul_part_recursive(), and bn_mul_recursive().
bn_cmp_words()
int bn_cmp_words (const BN_ULONG * a, const BN_ULONG * b, int n)
Definition at line 776 of file bn_lib.c.
Referenced by bn_cmp_part_words(), bn_mul_high(), and bn_sqr_recursive().
bn_div_words()
BN_ULONG bn_div_words (BN_ULONG h, BN_ULONG l, BN_ULONG d)
Definition at line 207 of file bn_asm.c.
References q.
Referenced by BN_div(), and bn_sqr_words().
bn_init()
void bn_init (BIGNUM * a)
Definition at line 215 of file bn_lib.c.
References bn_check_top.
Referenced by BN_MONT_CTX_init(), and BN_RECP_CTX_init().
BN_MONT_CTX_init()
void BN_MONT_CTX_init (BN_MONT_CTX * ctx)
Definition at line 225 of file bn_mont.c.
References bn_init().
bn_mul_add_words()
BN_ULONG bn_mul_add_words (BN_ULONG * rp, const BN_ULONG * ap, int num, BN_ULONG w)
Definition at line 103 of file bn_asm.c.
Referenced by bn_mul_low_normal(), bn_mul_normal(), bn_sqr_comba4(), and bn_sqr_normal().
bn_mul_comba4()
void bn_mul_comba4 (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b)
Definition at line 684 of file bn_asm.c.
References mul_add_c.
Referenced by bn_mul_part_recursive(), bn_mul_recursive(), and bn_sqr_comba4().
bn_mul_comba8()
void bn_mul_comba8 (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b)
Definition at line 581 of file bn_asm.c.
References mul_add_c.
Referenced by bn_mul_high(), bn_mul_part_recursive(), bn_mul_recursive(), and bn_sqr_comba4().
bn_mul_high()
void bn_mul_high (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b, BN_ULONG * l, int n2, BN_ULONG * t)
Definition at line 663 of file bn_mul.c.
References bn_add_words(), bn_cmp_words(), bn_mul_comba8(), bn_mul_recursive(), bn_sub_words(), and NULL.
bn_mul_low_normal()
void bn_mul_low_normal (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b, int n)
Definition at line 1025 of file bn_mul.c.
References bn_mul_add_words(), and bn_mul_words().
Referenced by bn_mul_low_recursive().
bn_mul_low_recursive()
void bn_mul_low_recursive (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b, int n2, BN_ULONG * t)
Definition at line 638 of file bn_mul.c.
References bn_add_words(), bn_mul_low_normal(), BN_MUL_LOW_RECURSIVE_SIZE_NORMAL, and bn_mul_recursive().
bn_mul_mont()
int bn_mul_mont (BN_ULONG * rp, const BN_ULONG * ap, const BN_ULONG * bp, const BN_ULONG * np, const BN_ULONG * n0, int num)
Definition at line 26 of file sparcv9cap.c.
References _sparcv9_fjaesx_probe(), _sparcv9_fmadd_probe(), _sparcv9_random(), _sparcv9_rdcfr(), _sparcv9_rdtick(), _sparcv9_vis1_instrument(), _sparcv9_vis1_instrument_bus(), _sparcv9_vis1_instrument_bus2(), _sparcv9_vis1_probe(), _sparcv9_vis2_probe(), _sparcv9_vis3_probe(), bp, CFR_MONTMUL, CFR_MONTSQR, SPARCV9_FMADD, SPARCV9_PREFER_FPU, SPARCV9_VIS1, and SPARCV9_VIS3.
Referenced by bn_sqr_comba4().
bn_mul_normal()
void bn_mul_normal (BN_ULONG * r, BN_ULONG * a, int na, BN_ULONG * b, int nb)
Definition at line 983 of file bn_mul.c.
References bn_mul_add_words(), and bn_mul_words().
Referenced by bn_mul_part_recursive(), and bn_mul_recursive().
bn_mul_part_recursive()
void bn_mul_part_recursive (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b, int n, int tna, int tnb, BN_ULONG * t)
Definition at line 480 of file bn_mul.c.
References bn_add_words(), bn_cmp_part_words(), bn_mul_comba4(), bn_mul_comba8(), bn_mul_normal(), bn_mul_recursive(), BN_MUL_RECURSIVE_SIZE_NORMAL, bn_sub_part_words(), bn_sub_words(), and t.
bn_mul_recursive()
void bn_mul_recursive (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b, int n2, int dna, int dnb, BN_ULONG * t)
Definition at line 333 of file bn_mul.c.
References bn_add_words(), bn_cmp_part_words(), bn_mul_comba4(), bn_mul_comba8(), bn_mul_normal(), BN_MUL_RECURSIVE_SIZE_NORMAL, bn_sub_part_words(), bn_sub_words(), and t.
Referenced by bn_mul_high(), bn_mul_low_recursive(), and bn_mul_part_recursive().
bn_mul_words()
BN_ULONG bn_mul_words (BN_ULONG * rp, const BN_ULONG * ap, int num, BN_ULONG w)
Definition at line 136 of file bn_asm.c.
References HBITS, LBITS, and mul.
Referenced by BN_div(), bn_mul_low_normal(), bn_mul_normal(), BN_mul_word(), bn_sqr_comba4(), and bn_sqr_normal().
bn_probable_prime_dh()
int bn_probable_prime_dh (BIGNUM * rnd, int bits, const BIGNUM * add, const BIGNUM * rem, BN_CTX * ctx)
Definition at line 494 of file bn_prime.c.
bn_probable_prime_dh_coprime()
int bn_probable_prime_dh_coprime (BIGNUM * rnd, int bits, BN_CTX * ctx)
Definition at line 335 of file bn_prime.c.
bn_probable_prime_dh_retry()
int bn_probable_prime_dh_retry (BIGNUM * rnd, int bits, BN_CTX * ctx)
Definition at line 308 of file bn_prime.c.
BN_RECP_CTX_init()
void BN_RECP_CTX_init (BN_RECP_CTX * recp)
Definition at line 13 of file bn_recp.c.
References bn_init().
bn_sqr_comba4()
void bn_sqr_comba4 (BN_ULONG * r, const BN_ULONG * a)
Definition at line 798 of file bn_asm.c.
References bn_mul_add_words(), bn_mul_comba4(), bn_mul_comba8(), bn_mul_mont(), bn_mul_words(), bn_sqr_comba4(), bn_sqr_comba8(), bn_sqr_normal(), bn_sub_words(), bp, HBITS, LBITS, mh, ml, mul, mul_add, sqr_add_c, sqr_add_c2, and t.
Referenced by bn_sqr_comba4(), and bn_sqr_recursive().
bn_sqr_comba8()
void bn_sqr_comba8 (BN_ULONG * r, const BN_ULONG * a)
Definition at line 723 of file bn_asm.c.
References sqr_add_c, and sqr_add_c2.
Referenced by bn_sqr_comba4(), and bn_sqr_recursive().
bn_sqr_normal()
void bn_sqr_normal (BN_ULONG * r, const BN_ULONG * a, int n, BN_ULONG * tmp)
Definition at line 105 of file bn_sqr.c.
References bn_add_words(), bn_mul_add_words(), bn_mul_words(), bn_sqr_words(), and max.
Referenced by bn_sqr_comba4(), and bn_sqr_recursive().
bn_sqr_recursive()
void bn_sqr_recursive (BN_ULONG * r, const BN_ULONG * a, int n2, BN_ULONG * t)
Definition at line 152 of file bn_sqr.c.
References bn_add_words(), bn_cmp_words(), bn_sqr_comba4(), bn_sqr_comba8(), bn_sqr_normal(), BN_SQR_RECURSIVE_SIZE_NORMAL, bn_sub_words(), and t.
bn_sqr_words()
void bn_sqr_words (BN_ULONG * rp, const BN_ULONG * ap, int num)
Definition at line 168 of file bn_asm.c.
References BN_BITS2, bn_div_words(), h, and sqr64.
Referenced by bn_sqr_normal().
bn_sub_part_words()
BN_ULONG bn_sub_part_words (BN_ULONG * r, const BN_ULONG * a, const BN_ULONG * b, int cl, int dl)
Definition at line 27 of file bn_mul.c.
Referenced by bn_mul_part_recursive(), and bn_mul_recursive().
bn_sub_words()
BN_ULONG bn_sub_words (BN_ULONG * rp, const BN_ULONG * ap, const BN_ULONG * bp, int num)
Definition at line 371 of file bn_asm.c.
Referenced by BN_div(), bn_mul_high(), bn_mul_part_recursive(), bn_mul_recursive(), bn_sqr_comba4(), bn_sqr_recursive(), and BN_usub().
int_bn_mod_inverse()
BIGNUM* int_bn_mod_inverse (BIGNUM * in, const BIGNUM * a, const BIGNUM * n, BN_CTX * ctx, int * noinv)
Definition at line 135 of file bn_gcd.c.
References B, NULL, R, X, and Y.
Referenced by BN_mod_inverse().