crypto/bn/bn_asm.c File Reference
bn_asm.c File Reference
#include <assert.h>
#include <openssl/crypto.h>
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Macros
#define mul_add_c(a, b, c0, c1, c2)
#define mul_add_c2(a, b, c0, c1, c2)
#define sqr_add_c(a, i, c0, c1, c2)
#define sqr_add_c2(a, i, j, c0, c1, c2) mul_add_c2((a)[i],(a)[j],c0,c1,c2)
Functions
BN_ULONG bn_mul_add_words (BN_ULONG *rp, const BN_ULONG *ap, int num, BN_ULONG w)
BN_ULONG bn_mul_words (BN_ULONG *rp, const BN_ULONG *ap, int num, BN_ULONG w)
void bn_sqr_words (BN_ULONG *r, const BN_ULONG *a, int n)
BN_ULONG bn_div_words (BN_ULONG h, BN_ULONG l, BN_ULONG d)
BN_ULONG bn_add_words (BN_ULONG *r, const BN_ULONG *a, const BN_ULONG *b, int n)
BN_ULONG bn_sub_words (BN_ULONG *r, const BN_ULONG *a, const BN_ULONG *b, int n)
void bn_mul_comba8 (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b)
void bn_mul_comba4 (BN_ULONG *r, BN_ULONG *a, BN_ULONG *b)
void bn_sqr_comba8 (BN_ULONG *r, const BN_ULONG *a)
void bn_sqr_comba4 (BN_ULONG *r, const BN_ULONG *a)
Macro Definition Documentation
mul_add_c
#define mul_add_c (a, b, c0, c1, c2)
Value:
do {    \
        BN_ULONG lo = LBITS(a), hi = HBITS(a);  \
        BN_ULONG bl = LBITS(b), bh = HBITS(b);  \
        mul64(lo,hi,bl,bh);                     \
        c0 = (c0+lo)&BN_MASK2; if (c0<lo) hi++; \
        c1 = (c1+hi)&BN_MASK2; if (c1<hi) c2++; \
        } while(0)
Definition at line 550 of file bn_asm.c.
Referenced by bn_mul_comba4(), and bn_mul_comba8().
mul_add_c2
#define mul_add_c2 (a, b, c0, c1, c2)
Value:
do {    \
        BN_ULONG tt;                            \
        BN_ULONG lo = LBITS(a), hi = HBITS(a);  \
        BN_ULONG bl = LBITS(b), bh = HBITS(b);  \
        mul64(lo,hi,bl,bh);                     \
        tt = hi;                                \
        c0 = (c0+lo)&BN_MASK2; if (c0<lo) tt++; \
        c1 = (c1+tt)&BN_MASK2; if (c1<tt) c2++; \
        c0 = (c0+lo)&BN_MASK2; if (c0<lo) hi++; \
        c1 = (c1+hi)&BN_MASK2; if (c1<hi) c2++; \
        } while(0)
Definition at line 558 of file bn_asm.c.
sqr_add_c
#define sqr_add_c (a, i, c0, c1, c2)
Value:
do {    \
        BN_ULONG lo, hi;                        \
        sqr64(lo,hi,(a)[i]);                    \
        c0 = (c0+lo)&BN_MASK2; if (c0<lo) hi++; \
        c1 = (c1+hi)&BN_MASK2; if (c1<hi) c2++; \
        } while(0)
Definition at line 570 of file bn_asm.c.
Referenced by bn_sqr_comba4(), and bn_sqr_comba8().
sqr_add_c2
#define sqr_add_c2 (a, i, j, c0, c1, c2) mul_add_c2((a)[i],(a)[j],c0,c1,c2)
Definition at line 577 of file bn_asm.c.
Referenced by bn_sqr_comba4(), and bn_sqr_comba8().
Function Documentation
bn_add_words()
BN_ULONG bn_add_words (BN_ULONG * r, const BN_ULONG * a, const BN_ULONG * b, int n)
Definition at line 313 of file bn_asm.c.
Referenced by BN_div(), bn_mul_high(), bn_mul_low_recursive(), bn_mul_part_recursive(), bn_mul_recursive(), bn_sqr_normal(), bn_sqr_recursive(), and BN_uadd().
bn_div_words()
BN_ULONG bn_div_words (BN_ULONG h, BN_ULONG l, BN_ULONG d)
Definition at line 207 of file bn_asm.c.
References q.
Referenced by BN_div(), and bn_sqr_words().
bn_mul_add_words()
BN_ULONG bn_mul_add_words (BN_ULONG * rp, const BN_ULONG * ap, int num, BN_ULONG w)
Definition at line 103 of file bn_asm.c.
Referenced by bn_mul_low_normal(), bn_mul_normal(), bn_sqr_comba4(), and bn_sqr_normal().
bn_mul_comba4()
void bn_mul_comba4 (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b)
Definition at line 684 of file bn_asm.c.
References mul_add_c.
Referenced by bn_mul_part_recursive(), bn_mul_recursive(), and bn_sqr_comba4().
bn_mul_comba8()
void bn_mul_comba8 (BN_ULONG * r, BN_ULONG * a, BN_ULONG * b)
Definition at line 581 of file bn_asm.c.
References mul_add_c.
Referenced by bn_mul_high(), bn_mul_part_recursive(), bn_mul_recursive(), and bn_sqr_comba4().
bn_mul_words()
BN_ULONG bn_mul_words (BN_ULONG * rp, const BN_ULONG * ap, int num, BN_ULONG w)
Definition at line 136 of file bn_asm.c.
References HBITS, LBITS, and mul.
Referenced by BN_div(), bn_mul_low_normal(), bn_mul_normal(), BN_mul_word(), bn_sqr_comba4(), and bn_sqr_normal().
bn_sqr_comba4()
void bn_sqr_comba4 (BN_ULONG * r, const BN_ULONG * a)
Definition at line 798 of file bn_asm.c.
References bn_mul_add_words(), bn_mul_comba4(), bn_mul_comba8(), bn_mul_mont(), bn_mul_words(), bn_sqr_comba4(), bn_sqr_comba8(), bn_sqr_normal(), bn_sub_words(), bp, HBITS, LBITS, mh, ml, mul, mul_add, sqr_add_c, sqr_add_c2, and t.
Referenced by bn_sqr_comba4(), and bn_sqr_recursive().
bn_sqr_comba8()
void bn_sqr_comba8 (BN_ULONG * r, const BN_ULONG * a)
Definition at line 723 of file bn_asm.c.
References sqr_add_c, and sqr_add_c2.
Referenced by bn_sqr_comba4(), and bn_sqr_recursive().
bn_sqr_words()
void bn_sqr_words (BN_ULONG * r, const BN_ULONG * a, int n)
Definition at line 168 of file bn_asm.c.
References BN_BITS2, bn_div_words(), h, and sqr64.
Referenced by bn_sqr_normal().
bn_sub_words()
BN_ULONG bn_sub_words (BN_ULONG * r, const BN_ULONG * a, const BN_ULONG * b, int n)
Definition at line 371 of file bn_asm.c.
Referenced by BN_div(), bn_mul_high(), bn_mul_part_recursive(), bn_mul_recursive(), bn_sqr_comba4(), bn_sqr_recursive(), and BN_usub().