crypto/bn/bn_const.c File Reference
bn_const.c File Reference
#include <openssl/bn.h>
Functions
BIGNUM * BN_get_rfc2409_prime_768 (BIGNUM *bn)
BIGNUM * BN_get_rfc2409_prime_1024 (BIGNUM *bn)
BIGNUM * BN_get_rfc3526_prime_1536 (BIGNUM *bn)
BIGNUM * BN_get_rfc3526_prime_2048 (BIGNUM *bn)
BIGNUM * BN_get_rfc3526_prime_3072 (BIGNUM *bn)
BIGNUM * BN_get_rfc3526_prime_4096 (BIGNUM *bn)
BIGNUM * BN_get_rfc3526_prime_6144 (BIGNUM *bn)
BIGNUM * BN_get_rfc3526_prime_8192 (BIGNUM *bn)
Function Documentation
BN_get_rfc2409_prime_1024()
BIGNUM* BN_get_rfc2409_prime_1024 (BIGNUM * bn)
Definition at line 49 of file bn_const.c.
References BN_bin2bn().
BN_get_rfc2409_prime_768()
BIGNUM* BN_get_rfc2409_prime_768 (BIGNUM * bn)
Definition at line 21 of file bn_const.c.
References BN_bin2bn().
BN_get_rfc3526_prime_1536()
BIGNUM* BN_get_rfc3526_prime_1536 (BIGNUM * bn)
Definition at line 81 of file bn_const.c.
References BN_bin2bn().
BN_get_rfc3526_prime_2048()
BIGNUM* BN_get_rfc3526_prime_2048 (BIGNUM * bn)
Definition at line 120 of file bn_const.c.
References BN_bin2bn().
BN_get_rfc3526_prime_3072()
BIGNUM* BN_get_rfc3526_prime_3072 (BIGNUM * bn)
Definition at line 167 of file bn_const.c.
References BN_bin2bn().
Referenced by ssl_get_auto_dh().
BN_get_rfc3526_prime_4096()
BIGNUM* BN_get_rfc3526_prime_4096 (BIGNUM * bn)
Definition at line 230 of file bn_const.c.
References BN_bin2bn().
BN_get_rfc3526_prime_6144()
BIGNUM* BN_get_rfc3526_prime_6144 (BIGNUM * bn)
Definition at line 309 of file bn_const.c.
References BN_bin2bn().
BN_get_rfc3526_prime_8192()
BIGNUM* BN_get_rfc3526_prime_8192 (BIGNUM * bn)
Definition at line 420 of file bn_const.c.
References BN_bin2bn().
Referenced by ssl_get_auto_dh().