crypto/bn/bn_lib.c File Reference
bn_lib.c File Reference
#include <assert.h>
#include <limits.h>
#include "internal/cryptlib.h"
#include "bn_lcl.h"
#include <openssl/opensslconf.h>
Macros
#define BN_CONSTTIME_SWAP(ind)
Functions
void BN_set_params (int mult, int high, int low, int mont)
int BN_get_params (int which)
const BIGNUM * BN_value_one (void)
int BN_num_bits_word (BN_ULONG l)
int BN_num_bits (const BIGNUM *a)
void BN_clear_free (BIGNUM *a)
void BN_free (BIGNUM *a)
void bn_init (BIGNUM *a)
BIGNUM * BN_new (void)
BIGNUM * BN_secure_new (void)
BIGNUM * bn_expand2 (BIGNUM *b, int words)
BIGNUM * BN_dup (const BIGNUM *a)
BIGNUM * BN_copy (BIGNUM *a, const BIGNUM *b)
void BN_swap (BIGNUM *a, BIGNUM *b)
void BN_clear (BIGNUM *a)
BN_ULONG BN_get_word (const BIGNUM *a)
int BN_set_word (BIGNUM *a, BN_ULONG w)
BIGNUM * BN_bin2bn (const unsigned char *s, int len, BIGNUM *ret)
int BN_bn2binpad (const BIGNUM *a, unsigned char *to, int tolen)
int BN_bn2bin (const BIGNUM *a, unsigned char *to)
BIGNUM * BN_lebin2bn (const unsigned char *s, int len, BIGNUM *ret)
int BN_bn2lebinpad (const BIGNUM *a, unsigned char *to, int tolen)
int BN_ucmp (const BIGNUM *a, const BIGNUM *b)
int BN_cmp (const BIGNUM *a, const BIGNUM *b)
int BN_set_bit (BIGNUM *a, int n)
int BN_clear_bit (BIGNUM *a, int n)
int BN_is_bit_set (const BIGNUM *a, int n)
int BN_mask_bits (BIGNUM *a, int n)
void BN_set_negative (BIGNUM *a, int b)
int bn_cmp_words (const BN_ULONG *a, const BN_ULONG *b, int n)
int bn_cmp_part_words (const BN_ULONG *a, const BN_ULONG *b, int cl, int dl)
void BN_consttime_swap (BN_ULONG condition, BIGNUM *a, BIGNUM *b, int nwords)
int BN_security_bits (int L, int N)
void BN_zero_ex (BIGNUM *a)
int BN_abs_is_word (const BIGNUM *a, const BN_ULONG w)
int BN_is_zero (const BIGNUM *a)
int BN_is_one (const BIGNUM *a)
int BN_is_word (const BIGNUM *a, const BN_ULONG w)
int BN_is_odd (const BIGNUM *a)
int BN_is_negative (const BIGNUM *a)
int BN_to_montgomery (BIGNUM *r, const BIGNUM *a, BN_MONT_CTX *mont, BN_CTX *ctx)
void BN_with_flags (BIGNUM *dest, const BIGNUM *b, int flags)
BN_GENCB * BN_GENCB_new (void)
void BN_GENCB_free (BN_GENCB *cb)
void BN_set_flags (BIGNUM *b, int n)
int BN_get_flags (const BIGNUM *b, int n)
void BN_GENCB_set_old (BN_GENCB *gencb, void(*callback)(int, int, void *), void *cb_arg)
void BN_GENCB_set (BN_GENCB *gencb, int(*callback)(int, int, BN_GENCB *), void *cb_arg)
void * BN_GENCB_get_arg (BN_GENCB *cb)
BIGNUM * bn_wexpand (BIGNUM *a, int words)
void bn_correct_top (BIGNUM *a)
Macro Definition Documentation
BN_CONSTTIME_SWAP
#define BN_CONSTTIME_SWAP (ind)
Value:
do { \
                t = (a->d[ind] ^ b->d[ind]) & condition; \
                a->d[ind] ^= t; \
                b->d[ind] ^= t; \
        } while (0)
Referenced by BN_consttime_swap().
Function Documentation
BN_abs_is_word()
int BN_abs_is_word (const BIGNUM * a, const BN_ULONG w)
Definition at line 915 of file bn_lib.c.
Referenced by BN_is_one(), and BN_is_word().
BN_bin2bn()
BIGNUM* BN_bin2bn (const unsigned char * s, int len, BIGNUM * ret)
Definition at line 475 of file bn_lib.c.
Referenced by BN_get_rfc2409_prime_1024(), BN_get_rfc2409_prime_768(), BN_get_rfc3526_prime_1536(), BN_get_rfc3526_prime_2048(), BN_get_rfc3526_prime_3072(), BN_get_rfc3526_prime_4096(), BN_get_rfc3526_prime_6144(), BN_get_rfc3526_prime_8192(), BN_mpi2bn(), get_dsa1024(), get_dsa2048(), get_dsa512(), SRP_Calc_A_param(), SRP_Calc_x(), SRP_create_verifier_BN(), and SSL_srp_server_param_with_username().
BN_bn2bin()
int BN_bn2bin (const BIGNUM * a, unsigned char * to)
Definition at line 551 of file bn_lib.c.
Referenced by BN_bn2mpi(), and SRP_Calc_x().
BN_bn2binpad()
int BN_bn2binpad (const BIGNUM * a, unsigned char * to, int tolen)
Definition at line 544 of file bn_lib.c.
BN_bn2lebinpad()
int BN_bn2lebinpad (const BIGNUM * a, unsigned char * to, int tolen)
Definition at line 603 of file bn_lib.c.
References bn_check_top, and BN_num_bytes.
BN_clear()
void BN_clear (BIGNUM * a)
Definition at line 444 of file bn_lib.c.
References bn_check_top, NULL, and OPENSSL_cleanse().
BN_clear_bit()
int BN_clear_bit (BIGNUM * a, int n)
Definition at line 714 of file bn_lib.c.
References BN_BITS2, bn_check_top, and bn_correct_top().
Referenced by BN_mpi2bn().
BN_clear_free()
void BN_clear_free (BIGNUM * a)
Definition at line 180 of file bn_lib.c.
References bn_check_top, BN_FLG_STATIC_DATA, BN_get_flags(), NULL, and OPENSSL_cleanse().
Referenced by BN_MONT_CTX_free(), DH_free(), DSA_free(), ec_GF2m_simple_group_clear_finish(), ec_GF2m_simple_point_clear_finish(), ec_GFp_mont_group_clear_finish(), ec_GFp_mont_group_copy(), ec_GFp_simple_group_clear_finish(), ec_GFp_simple_point_clear_finish(), EC_GROUP_clear_free(), EC_KEY_free(), EC_KEY_set_private_key(), RSA_free(), SRP_create_verifier_BN(), SRP_user_pwd_free(), and SSL_set_srp_server_param_pw().
BN_cmp()
int BN_cmp (const BIGNUM * a, const BIGNUM * b)
Definition at line 645 of file bn_lib.c.
References bn_check_top, and NULL.
Referenced by BN_mod_lshift1_quick(), BN_mod_lshift_quick(), EC_KEY_set_public_key_affine_coordinates(), and SRP_check_known_gN_param().
bn_cmp_part_words()
int bn_cmp_part_words (const BN_ULONG * a, const BN_ULONG * b, int cl, int dl)
Definition at line 803 of file bn_lib.c.
References bn_cmp_words().
Referenced by bn_mul_part_recursive(), and bn_mul_recursive().
bn_cmp_words()
int bn_cmp_words (const BN_ULONG * a, const BN_ULONG * b, int n)
Definition at line 776 of file bn_lib.c.
Referenced by bn_cmp_part_words(), bn_mul_high(), and bn_sqr_recursive().
BN_consttime_swap()
void BN_consttime_swap (BN_ULONG condition, BIGNUM * a, BIGNUM * b, int nwords)
Definition at line 830 of file bn_lib.c.
References BN_BITS2, BN_CONSTTIME_SWAP, bn_wcheck_size, and t.
BN_copy()
BIGNUM* BN_copy (BIGNUM * a, const BIGNUM * b)
Definition at line 362 of file bn_lib.c.
References B, bn_check_top, bn_wexpand(), and NULL.
Referenced by BN_div(), BN_dup(), BN_mod_lshift_quick(), BN_MONT_CTX_copy(), BN_RECP_CTX_set(), ec_GF2m_simple_group_copy(), ec_GF2m_simple_point_copy(), ec_GFp_mont_field_set_to_one(), ec_GFp_simple_group_copy(), ec_GFp_simple_point_copy(), EC_GROUP_copy(), EC_GROUP_get_cofactor(), EC_KEY_copy(), and SSL_set_srp_server_param().
bn_correct_top()
void bn_correct_top (BIGNUM * a)
Definition at line 1021 of file bn_lib.c.
References bn_pollute.
Referenced by BN_clear_bit(), BN_div(), BN_GF2m_add(), BN_lshift(), BN_mask_bits(), bn_set_static_words(), bn_set_words(), and BN_usub().
BN_dup()
BIGNUM* BN_dup (const BIGNUM * a)
Definition at line 343 of file bn_lib.c.
References bn_check_top, BN_copy(), BN_FLG_SECURE, BN_free(), BN_get_flags(), BN_new(), BN_secure_new(), NULL, and t.
Referenced by ec_GFp_mont_group_copy(), EC_KEY_set_private_key(), SSL_set_srp_server_param(), SSL_set_srp_server_param_pw(), and SSL_SRP_CTX_init().
bn_expand2()
BIGNUM * bn_expand2 (BIGNUM * b, int words)
Definition at line 323 of file bn_lib.c.
Referenced by bn_wexpand().
BN_free()
void BN_free (BIGNUM * a)
Definition at line 198 of file bn_lib.c.
References bn_check_top, BN_FLG_STATIC_DATA, BN_get_flags(), and NULL.
Referenced by BN_BLINDING_free(), BN_dup(), BN_mpi2bn(), BN_RECP_CTX_free(), DH_set0_key(), DH_set0_pqg(), DSA_set0_key(), DSA_set0_pqg(), ec_GF2m_simple_group_finish(), ec_GF2m_simple_group_init(), ec_GF2m_simple_point_finish(), ec_GF2m_simple_point_init(), ec_GFp_mont_group_finish(), ec_GFp_simple_group_finish(), ec_GFp_simple_group_init(), ec_GFp_simple_point_finish(), ec_GFp_simple_point_init(), EC_GROUP_free(), FuzzerCleanup(), i2s_ASN1_ENUMERATED(), i2s_ASN1_INTEGER(), RSA_generate_key(), RSA_set0_crt_params(), RSA_set0_factors(), RSA_set0_key(), SRP_Calc_A(), SRP_user_pwd_free(), SSL_CTX_SRP_CTX_free(), ssl_get_auto_dh(), SSL_set_srp_server_param(), SSL_SRP_CTX_free(), SSL_SRP_CTX_init(), and TS_ASN1_INTEGER_print_bio().
BN_GENCB_free()
void BN_GENCB_free (BN_GENCB * cb)
Definition at line 974 of file bn_lib.c.
References NULL, and OPENSSL_free.
Referenced by RSA_generate_key().
BN_GENCB_get_arg()
void* BN_GENCB_get_arg (BN_GENCB * cb)
Definition at line 1011 of file bn_lib.c.
BN_GENCB_new()
BN_GENCB* BN_GENCB_new (void)
Definition at line 962 of file bn_lib.c.
Referenced by RSA_generate_key().
BN_GENCB_set()
void BN_GENCB_set (BN_GENCB * gencb, int(*)(int, int, BN_GENCB *) callback, void * cb_arg)
Definition at line 1002 of file bn_lib.c.
References callback.
Referenced by evp_pkey_set_cb_translate().
BN_GENCB_set_old()
void BN_GENCB_set_old (BN_GENCB * gencb, void(*)(int, int, void *) callback, void * cb_arg)
Definition at line 992 of file bn_lib.c.
References callback.
Referenced by BN_is_prime(), BN_is_prime_fasttest(), and RSA_generate_key().
BN_get_flags()
int BN_get_flags (const BIGNUM * b, int n)
Definition at line 986 of file bn_lib.c.
Referenced by BN_clear_free(), BN_div(), BN_dup(), and BN_free().
BN_get_params()
int BN_get_params (int which)
Definition at line 65 of file bn_lib.c.
BN_get_word()
BN_ULONG BN_get_word (const BIGNUM * a)
Definition at line 453 of file bn_lib.c.
bn_init()
void bn_init (BIGNUM * a)
Definition at line 215 of file bn_lib.c.
References bn_check_top.
Referenced by BN_MONT_CTX_init(), and BN_RECP_CTX_init().
BN_is_bit_set()
int BN_is_bit_set (const BIGNUM * a, int n)
Definition at line 732 of file bn_lib.c.
References BN_BITS2, and bn_check_top.
BN_is_negative()
int BN_is_negative (const BIGNUM * b)
BN_is_negative returns 1 if the BIGNUM is negative
Parameters
a pointer to the BIGNUM object
Returns
1 if a < 0 and 0 otherwise
Definition at line 940 of file bn_lib.c.
BN_is_odd()
int BN_is_odd (const BIGNUM * a)
Definition at line 935 of file bn_lib.c.
BN_is_one()
int BN_is_one (const BIGNUM * a)
Definition at line 925 of file bn_lib.c.
References BN_abs_is_word().
BN_is_word()
int BN_is_word (const BIGNUM * a, const BN_ULONG w)
Definition at line 930 of file bn_lib.c.
References BN_abs_is_word().
BN_is_zero()
int BN_is_zero (const BIGNUM * a)
Definition at line 920 of file bn_lib.c.
Referenced by BN_add_word(), BN_div(), BN_num_bits(), BN_set_negative(), BN_sub_word(), ec_GF2m_simple_invert(), ec_GF2m_simple_is_at_infinity(), ec_GFp_simple_invert(), ec_GFp_simple_is_at_infinity(), EC_GROUP_get_cofactor(), and srp_verify_server_param().
BN_lebin2bn()
BIGNUM* BN_lebin2bn (const unsigned char * s, int len, BIGNUM * ret)
Definition at line 556 of file bn_lib.c.
BN_mask_bits()
int BN_mask_bits (BIGNUM * a, int n)
Definition at line 746 of file bn_lib.c.
References BN_BITS2, bn_check_top, and bn_correct_top().
BN_new()
BIGNUM* BN_new (void)
Definition at line 223 of file bn_lib.c.
Referenced by BN_dup(), BN_mpi2bn(), ec_GF2m_simple_group_init(), ec_GF2m_simple_point_init(), ec_GFp_simple_group_init(), ec_GFp_simple_point_init(), EC_KEY_copy(), RSA_generate_key(), RSA_X931_generate_key_ex(), SRP_Calc_A(), SRP_create_verifier_BN(), ssl_get_auto_dh(), and TS_ASN1_INTEGER_print_bio().
BN_num_bits()
int BN_num_bits (const BIGNUM * a)
Definition at line 161 of file bn_lib.c.
References BN_BITS2, bn_check_top, BN_is_zero(), and BN_num_bits_word().
Referenced by BN_bn2mpi(), BN_div(), BN_mod_lshift_quick(), BN_mpi2bn(), BN_RECP_CTX_set(), BN_rshift(), BN_X931_generate_Xpq(), DH_bits(), DH_security_bits(), DH_set0_pqg(), DSA_bits(), DSA_security_bits(), ec_GF2m_simple_group_get_degree(), ec_GFp_simple_group_get_degree(), ec_group_simple_order_bits(), RSA_bits(), RSA_security_bits(), and srp_verify_server_param().
BN_num_bits_word()
int BN_num_bits_word (BN_ULONG l)
Definition at line 89 of file bn_lib.c.
References bits.
Referenced by BN_num_bits().
BN_secure_new()
BIGNUM* BN_secure_new (void)
Definition at line 236 of file bn_lib.c.
Referenced by BN_dup().
BN_security_bits()
int BN_security_bits (int L, int N)
Definition at line 886 of file bn_lib.c.
References bits.
Referenced by DH_security_bits(), DSA_security_bits(), and RSA_security_bits().
BN_set_bit()
int BN_set_bit (BIGNUM * a, int n)
Definition at line 692 of file bn_lib.c.
Referenced by BN_GF2m_arr2poly(), and RSA_generate_key().
BN_set_flags()
void BN_set_flags (BIGNUM * b, int n)
Definition at line 981 of file bn_lib.c.
BN_set_negative()
void BN_set_negative (BIGNUM * b, int n)
BN_set_negative sets sign of a BIGNUM
Parameters
b pointer to the BIGNUM object
n 0 if the BIGNUM b should be positive and a value != 0 otherwise
Definition at line 768 of file bn_lib.c.
References BN_is_zero().
Referenced by BN_sub_word().
BN_set_params()
void BN_set_params (int mult, int high, int low, int mont)
Definition at line 37 of file bn_lib.c.
BN_set_word()
int BN_set_word (BIGNUM * a, BN_ULONG w)
Definition at line 463 of file bn_lib.c.
References bn_check_top.
Referenced by BN_add_word(), BN_sub_word(), and ssl_get_auto_dh().
BN_swap()
void BN_swap (BIGNUM * a, BIGNUM * b)
Definition at line 409 of file bn_lib.c.
References bn_check_top, BN_FLG_MALLOCED, and BN_FLG_STATIC_DATA.
BN_to_montgomery()
int BN_to_montgomery (BIGNUM * r, const BIGNUM * a, BN_MONT_CTX * mont, BN_CTX * ctx)
Definition at line 945 of file bn_lib.c.
References BN_mod_mul_montgomery().
Referenced by ec_GFp_mont_field_encode().
BN_ucmp()
int BN_ucmp (const BIGNUM * a, const BIGNUM * b)
Definition at line 623 of file bn_lib.c.
References bn_check_top, and bp.
Referenced by BN_div(), BN_mod_add_quick(), BN_sub(), and srp_verify_server_param().
BN_value_one()
const BIGNUM* BN_value_one (void)
Definition at line 80 of file bn_lib.c.
References BN_FLG_STATIC_DATA.
Referenced by ec_GFp_simple_point_set_affine_coordinates().
bn_wexpand()
BIGNUM* bn_wexpand (BIGNUM * a, int words)
Definition at line 1016 of file bn_lib.c.
References bn_expand2().
Referenced by BN_add_word(), BN_copy(), BN_div(), BN_GF2m_add(), BN_lshift(), BN_mul_word(), BN_rshift(), bn_set_words(), BN_sub(), BN_uadd(), BN_usub(), and ec_GF2m_simple_group_copy().
BN_with_flags()
void BN_with_flags (BIGNUM * dest, const BIGNUM * b, int flags)
Definition at line 951 of file bn_lib.c.
References BN_FLG_MALLOCED, BN_FLG_STATIC_DATA, and flags.
BN_zero_ex()
void BN_zero_ex (BIGNUM * a)
Definition at line 909 of file bn_lib.c.