crypto/bn/bn_div.c File Reference
bn_div.c File Reference
#include <openssl/bn.h>
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Functions
int BN_div (BIGNUM *dv, BIGNUM *rm, const BIGNUM *num, const BIGNUM *divisor, BN_CTX *ctx)
Function Documentation
BN_div()
int BN_div (BIGNUM * dv, BIGNUM * rm, const BIGNUM * num, const BIGNUM * divisor, BN_CTX * ctx)
Definition at line 140 of file bn_div.c.
References bn_add_words(), BN_BITS2, bn_check_top, bn_clear_top2max, BN_copy(), bn_correct_top(), BN_CTX_end(), BN_CTX_get(), BN_CTX_start(), bn_div_words(), BN_F_BN_DIV, BN_FLG_CONSTTIME, BN_get_flags(), BN_is_zero(), BN_lshift(), bn_mul_words(), BN_num_bits(), BN_R_DIV_BY_ZERO, BN_R_NOT_INITIALIZED, BN_rshift(), bn_sub_words(), BN_ucmp(), bn_wexpand(), BN_zero, BNerr, HBITS, LBITS, mul64, NULL, and q.