crypto/bn/bn_shift.c File Reference
bn_shift.c File Reference
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Functions
int BN_lshift1 (BIGNUM *r, const BIGNUM *a)
int BN_rshift1 (BIGNUM *r, const BIGNUM *a)
int BN_lshift (BIGNUM *r, const BIGNUM *a, int n)
int BN_rshift (BIGNUM *r, const BIGNUM *a, int n)
Function Documentation
BN_lshift()
int BN_lshift (BIGNUM * r, const BIGNUM * a, int n)
Definition at line 83 of file bn_shift.c.
References BN_BITS2, bn_check_top, bn_correct_top(), BN_F_BN_LSHIFT, BN_R_INVALID_SHIFT, bn_wexpand(), BNerr, NULL, and t.
Referenced by BN_div(), and BN_mod_lshift_quick().
BN_lshift1()
int BN_lshift1 (BIGNUM * r, const BIGNUM * a)
Definition at line 13 of file bn_shift.c.
References t.
Referenced by BN_mod_lshift1(), BN_mod_lshift1_quick(), and BN_mod_lshift_quick().
BN_rshift()
int BN_rshift (BIGNUM * r, const BIGNUM * a, int n)
Definition at line 122 of file bn_shift.c.
References BN_BITS2, bn_check_top, BN_F_BN_RSHIFT, BN_num_bits(), BN_R_INVALID_SHIFT, bn_wexpand(), BN_zero, BNerr, NULL, and t.
Referenced by BN_div().
BN_rshift1()
int BN_rshift1 (BIGNUM * r, const BIGNUM * a)
Definition at line 46 of file bn_shift.c.
References t.