crypto/bn/bn_blind.c File Reference
bn_blind.c File Reference
#include <openssl/opensslconf.h>
#include "internal/cryptlib.h"
#include "bn_lcl.h"
Data Structures
struct BN_BLINDING
Macros
#define BN_BLINDING_COUNTER 32
Functions
BN_BLINDING * BN_BLINDING_new (const BIGNUM *A, const BIGNUM *Ai, BIGNUM *mod)
void BN_BLINDING_free (BN_BLINDING *r)
int BN_BLINDING_update (BN_BLINDING *b, BN_CTX *ctx)
int BN_BLINDING_convert (BIGNUM *n, BN_BLINDING *b, BN_CTX *ctx)
int BN_BLINDING_convert_ex (BIGNUM *n, BIGNUM *r, BN_BLINDING *b, BN_CTX *ctx)
int BN_BLINDING_invert (BIGNUM *n, BN_BLINDING *b, BN_CTX *ctx)
int BN_BLINDING_invert_ex (BIGNUM *n, const BIGNUM *r, BN_BLINDING *b, BN_CTX *ctx)
int BN_BLINDING_is_current_thread (BN_BLINDING *b)
void BN_BLINDING_set_current_thread (BN_BLINDING *b)
int BN_BLINDING_lock (BN_BLINDING *b)
int BN_BLINDING_unlock (BN_BLINDING *b)
unsigned long BN_BLINDING_get_flags (const BN_BLINDING *b)
void BN_BLINDING_set_flags (BN_BLINDING *b, unsigned long flags)
BN_BLINDING * BN_BLINDING_create_param (BN_BLINDING *b, const BIGNUM *e, BIGNUM *m, BN_CTX *ctx, int(*bn_mod_exp)(BIGNUM *r, const BIGNUM *a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *m_ctx), BN_MONT_CTX *m_ctx)
Macro Definition Documentation
BN_BLINDING_COUNTER
#define BN_BLINDING_COUNTER 32
Definition at line 14 of file bn_blind.c.
Function Documentation
BN_BLINDING_convert()
int BN_BLINDING_convert (BIGNUM * n, BN_BLINDING * b, BN_CTX * ctx)
Definition at line 125 of file bn_blind.c.
References BN_BLINDING_convert_ex(), and NULL.
BN_BLINDING_convert_ex()
int BN_BLINDING_convert_ex (BIGNUM * n, BIGNUM * r, BN_BLINDING * b, BN_CTX * ctx)
Definition at line 130 of file bn_blind.c.
Referenced by BN_BLINDING_convert().
BN_BLINDING_create_param()
BN_BLINDING* BN_BLINDING_create_param (BN_BLINDING * b, const BIGNUM * e, BIGNUM * m, BN_CTX * ctx, int(*)(BIGNUM *r, const BIGNUM *a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *m_ctx) bn_mod_exp, BN_MONT_CTX * m_ctx)
Definition at line 214 of file bn_blind.c.
BN_BLINDING_free()
void BN_BLINDING_free (BN_BLINDING * r)
Definition at line 81 of file bn_blind.c.
References BN_free(), CRYPTO_THREAD_lock_free(), NULL, and OPENSSL_free.
Referenced by RSA_blinding_off(), and RSA_free().
BN_BLINDING_get_flags()
unsigned long BN_BLINDING_get_flags (const BN_BLINDING * b)
Definition at line 204 of file bn_blind.c.
BN_BLINDING_invert()
int BN_BLINDING_invert (BIGNUM * n, BN_BLINDING * b, BN_CTX * ctx)
Definition at line 158 of file bn_blind.c.
References BN_BLINDING_invert_ex(), and NULL.
BN_BLINDING_invert_ex()
int BN_BLINDING_invert_ex (BIGNUM * n, const BIGNUM * r, BN_BLINDING * b, BN_CTX * ctx)
Definition at line 163 of file bn_blind.c.
Referenced by BN_BLINDING_invert().
BN_BLINDING_is_current_thread()
int BN_BLINDING_is_current_thread (BN_BLINDING * b)
Definition at line 184 of file bn_blind.c.
References CRYPTO_THREAD_compare_id(), and CRYPTO_THREAD_get_current_id().
BN_BLINDING_lock()
int BN_BLINDING_lock (BN_BLINDING * b)
Definition at line 194 of file bn_blind.c.
References CRYPTO_THREAD_write_lock().
BN_BLINDING_new()
BN_BLINDING* BN_BLINDING_new (const BIGNUM * A, const BIGNUM * Ai, BIGNUM * mod)
Definition at line 30 of file bn_blind.c.
BN_BLINDING_set_current_thread()
void BN_BLINDING_set_current_thread (BN_BLINDING * b)
Definition at line 189 of file bn_blind.c.
References CRYPTO_THREAD_get_current_id().
BN_BLINDING_set_flags()
void BN_BLINDING_set_flags (BN_BLINDING * b, unsigned long flags)
Definition at line 209 of file bn_blind.c.
References BN_BLINDING::flags.
BN_BLINDING_unlock()
int BN_BLINDING_unlock (BN_BLINDING * b)
Definition at line 199 of file bn_blind.c.
References CRYPTO_THREAD_unlock().
BN_BLINDING_update()
int BN_BLINDING_update (BN_BLINDING * b, BN_CTX * ctx)
Definition at line 94 of file bn_blind.c.