crypto/bio/bss_file.c File Reference
bss_file.c File Reference
#include <stdio.h>
#include <errno.h>
#include "bio_lcl.h"
#include <openssl/err.h>
Macros
#define HEADER_BSS_FILE_C
Functions
BIO * BIO_new_file (const char *filename, const char *mode)
BIO * BIO_new_fp (FILE *stream, int close_flag)
const BIO_METHOD * BIO_s_file (void)
Macro Definition Documentation
HEADER_BSS_FILE_C
#define HEADER_BSS_FILE_C
Definition at line 17 of file bss_file.c.
Function Documentation
BIO_new_file()
BIO* BIO_new_file (const char * filename, const char * mode)
Definition at line 68 of file bss_file.c.
Referenced by LHASH_OF(), STACK_OF(), TS_CONF_load_key(), and X509_load_cert_crl_file().
BIO_new_fp()
BIO* BIO_new_fp (FILE * stream, int close_flag)
Definition at line 101 of file bss_file.c.
Referenced by dup_bio_err(), dup_bio_in(), dup_bio_out(), ERR_print_errors_fp(), LHASH_OF(), and main().
BIO_s_file()
const BIO_METHOD* BIO_s_file (void)
Definition at line 114 of file bss_file.c.
Referenced by OPENSSL_LH_node_stats(), OPENSSL_LH_node_usage_stats(), OPENSSL_LH_stats(), and SRP_VBASE_init().