crypto/bio/bss_sock.c File Reference
bss_sock.c File Reference
#include <stdio.h>
#include <errno.h>
#include "bio_lcl.h"
#include "internal/cryptlib.h"
#include <openssl/bio.h>
Macros
#define USE_SOCKETS
Functions
int BIO_sock_should_retry (int s)
const BIO_METHOD * BIO_s_socket (void)
BIO * BIO_new_socket (int fd, int close_flag)
int BIO_sock_non_fatal_error (int err)
Macro Definition Documentation
USE_SOCKETS
#define USE_SOCKETS
Definition at line 12 of file bss_sock.c.
Function Documentation
BIO_new_socket()
BIO* BIO_new_socket (int fd, int close_flag)
Definition at line 60 of file bss_sock.c.
BIO_s_socket()
const BIO_METHOD* BIO_s_socket (void)
Definition at line 55 of file bss_sock.c.
Referenced by SSL_set_rfd(), and SSL_set_wfd().
BIO_sock_non_fatal_error()
int BIO_sock_non_fatal_error (int err)
Definition at line 183 of file bss_sock.c.
Referenced by BIO_sock_should_retry().
BIO_sock_should_retry()
int BIO_sock_should_retry (int s)
Definition at line 171 of file bss_sock.c.
References BIO_sock_non_fatal_error(), and get_last_socket_error.
Referenced by BIO_accept_ex(), and BIO_connect().