crypto/bio/bss_bio.c File Reference
bss_bio.c File Reference
#include <assert.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include "bio_lcl.h"
#include <openssl/err.h>
#include <openssl/crypto.h>
#include "e_os.h"
Data Structures
struct bio_bio_st
Functions
const BIO_METHOD * BIO_s_bio (void)
int BIO_new_bio_pair (BIO **bio1_p, size_t writebuf1, BIO **bio2_p, size_t writebuf2)
size_t BIO_ctrl_get_write_guarantee (BIO *bio)
size_t BIO_ctrl_get_read_request (BIO *bio)
int BIO_ctrl_reset_read_request (BIO *bio)
int BIO_nread0 (BIO *bio, char **buf)
int BIO_nread (BIO *bio, char **buf, int num)
int BIO_nwrite0 (BIO *bio, char **buf)
int BIO_nwrite (BIO *bio, char **buf, int num)
Function Documentation
BIO_ctrl_get_read_request()
size_t BIO_ctrl_get_read_request (BIO * bio)
Definition at line 734 of file bss_bio.c.
References BIO_C_GET_READ_REQUEST, BIO_ctrl(), and NULL.
BIO_ctrl_get_write_guarantee()
size_t BIO_ctrl_get_write_guarantee (BIO * bio)
Definition at line 729 of file bss_bio.c.
References BIO_C_GET_WRITE_GUARANTEE, BIO_ctrl(), and NULL.
BIO_ctrl_reset_read_request()
int BIO_ctrl_reset_read_request (BIO * bio)
Definition at line 739 of file bss_bio.c.
References BIO_C_RESET_READ_REQUEST, BIO_ctrl(), and NULL.
BIO_new_bio_pair()
int BIO_new_bio_pair (BIO ** bio1_p, size_t writebuf1, BIO ** bio2_p, size_t writebuf2)
Definition at line 686 of file bss_bio.c.
References NULL.
BIO_nread()
int BIO_nread (BIO * bio, char ** buf, int num)
Definition at line 765 of file bss_bio.c.
BIO_nread0()
int BIO_nread0 (BIO * bio, char ** buf)
Definition at line 749 of file bss_bio.c.
BIO_nwrite()
int BIO_nwrite (BIO * bio, char ** buf, int num)
Definition at line 796 of file bss_bio.c.
BIO_nwrite0()
int BIO_nwrite0 (BIO * bio, char ** buf)
Definition at line 780 of file bss_bio.c.
BIO_s_bio()
const BIO_METHOD* BIO_s_bio (void)
Definition at line 56 of file bss_bio.c.