crypto/bio/bss_mem.c File Reference
bss_mem.c File Reference
#include <stdio.h>
#include <errno.h>
#include "bio_lcl.h"
#include "internal/cryptlib.h"
Data Structures
struct BIO_BUF_MEM
Functions
const BIO_METHOD * BIO_s_mem (void)
const BIO_METHOD * BIO_s_secmem (void)
BIO * BIO_new_mem_buf (const void *buf, int len)
Function Documentation
BIO_new_mem_buf()
BIO* BIO_new_mem_buf (const void * buf, int len)
Definition at line 81 of file bss_mem.c.
Referenced by cms_content_bio(), and CMS_sign_receipt().
BIO_s_mem()
const BIO_METHOD* BIO_s_mem (void)
Definition at line 71 of file bss_mem.c.
Referenced by cms_content_bio(), create_ssl_objects(), OCSP_REQ_CTX_new(), and ssl3_init_finished_mac().
BIO_s_secmem()
const BIO_METHOD* BIO_s_secmem (void)
Definition at line 76 of file bss_mem.c.