crypto/bio/bss_dgram.c File Reference
bss_dgram.c File Reference
#include <stdio.h>
#include <errno.h>
#include "bio_lcl.h"
#include <sys/time.h>
#include <netinet/sctp.h>
#include <fcntl.h>
Data Structures
struct bio_dgram_data
struct bio_dgram_sctp_save_message
struct bio_dgram_sctp_data
Macros
#define OPENSSL_SCTP_DATA_CHUNK_TYPE 0x00
#define OPENSSL_SCTP_FORWARD_CUM_TSN_CHUNK_TYPE 0xc0
Functions
const BIO_METHOD * BIO_s_datagram (void)
BIO * BIO_new_dgram (int fd, int close_flag)
const BIO_METHOD * BIO_s_datagram_sctp (void)
BIO * BIO_new_dgram_sctp (int fd, int close_flag)
int BIO_dgram_is_sctp (BIO *bio)
int BIO_dgram_sctp_notification_cb (BIO *b, void(*handle_notifications)(BIO *bio, void *context, void *buf), void *context)
int BIO_dgram_sctp_wait_for_dry (BIO *b)
int BIO_dgram_sctp_msg_waiting (BIO *b)
int BIO_dgram_non_fatal_error (int err)
Macro Definition Documentation
OPENSSL_SCTP_DATA_CHUNK_TYPE
#define OPENSSL_SCTP_DATA_CHUNK_TYPE 0x00
Definition at line 26 of file bss_dgram.c.
OPENSSL_SCTP_FORWARD_CUM_TSN_CHUNK_TYPE
#define OPENSSL_SCTP_FORWARD_CUM_TSN_CHUNK_TYPE 0xc0
Definition at line 27 of file bss_dgram.c.
Function Documentation
BIO_dgram_is_sctp()
int BIO_dgram_is_sctp (BIO * bio)
Definition at line 940 of file bss_dgram.c.
References BIO_method_type(), and BIO_TYPE_DGRAM_SCTP.
Referenced by dtls1_buffer_record(), dtls1_get_record(), dtls1_process_buffered_records(), dtls1_start_timer(), dtls1_write_app_data_bytes(), ossl_statem_client_pre_work(), ossl_statem_server_post_process_message(), ossl_statem_server_pre_work(), tls_finish_handshake(), and tls_post_process_client_key_exchange().
BIO_dgram_non_fatal_error()
int BIO_dgram_non_fatal_error (int err)
Definition at line 1875 of file bss_dgram.c.
BIO_dgram_sctp_msg_waiting()
int BIO_dgram_sctp_msg_waiting (BIO * b)
Definition at line 1786 of file bss_dgram.c.
References NULL.
Referenced by ossl_statem_client_post_process_message(), ossl_statem_server_post_process_message(), and tls_post_process_client_key_exchange().
BIO_dgram_sctp_notification_cb()
int BIO_dgram_sctp_notification_cb (BIO * b, void(*)(BIO *bio, void *context, void *buf) handle_notifications, void * context)
Definition at line 1597 of file bss_dgram.c.
BIO_dgram_sctp_wait_for_dry()
int BIO_dgram_sctp_wait_for_dry (BIO * b)
Definition at line 1628 of file bss_dgram.c.
BIO_new_dgram()
BIO* BIO_new_dgram (int fd, int close_flag)
Definition at line 150 of file bss_dgram.c.
BIO_new_dgram_sctp()
BIO* BIO_new_dgram_sctp (int fd, int close_flag)
Definition at line 819 of file bss_dgram.c.
BIO_s_datagram()
const BIO_METHOD* BIO_s_datagram (void)
Definition at line 145 of file bss_dgram.c.
BIO_s_datagram_sctp()
const BIO_METHOD* BIO_s_datagram_sctp (void)
Definition at line 814 of file bss_dgram.c.