include/openssl/buffer.h File Reference
buffer.h File Reference
#include <openssl/ossl_typ.h>
#include <openssl/crypto.h>
#include <stddef.h>
#include <sys/types.h>
Data Structures
struct BUF_MEM
Macros
#define BUF_strdup(s) OPENSSL_strdup(s)
#define BUF_strndup(s, size) OPENSSL_strndup(s, size)
#define BUF_memdup(data, size) OPENSSL_memdup(data, size)
#define BUF_strlcpy(dst, src, size) OPENSSL_strlcpy(dst, src, size)
#define BUF_strlcat(dst, src, size) OPENSSL_strlcat(dst, src, size)
#define BUF_strnlen(str, maxlen) OPENSSL_strnlen(str, maxlen)
#define BUF_MEM_FLAG_SECURE 0x01
#define BUF_F_BUF_MEM_GROW 100
#define BUF_F_BUF_MEM_GROW_CLEAN 105
#define BUF_F_BUF_MEM_NEW 101
Functions
BUF_MEM * BUF_MEM_new (void)
BUF_MEM * BUF_MEM_new_ex (unsigned long flags)
void BUF_MEM_free (BUF_MEM *a)
size_t BUF_MEM_grow (BUF_MEM *str, size_t len)
size_t BUF_MEM_grow_clean (BUF_MEM *str, size_t len)
void BUF_reverse (unsigned char *out, const unsigned char *in, size_t siz)
int ERR_load_BUF_strings (void)
Macro Definition Documentation
BUF_F_BUF_MEM_GROW
#define BUF_F_BUF_MEM_GROW 100
Definition at line 67 of file buffer.h.
BUF_F_BUF_MEM_GROW_CLEAN
#define BUF_F_BUF_MEM_GROW_CLEAN 105
Definition at line 68 of file buffer.h.
BUF_F_BUF_MEM_NEW
#define BUF_F_BUF_MEM_NEW 101
Definition at line 69 of file buffer.h.
BUF_MEM_FLAG_SECURE
#define BUF_MEM_FLAG_SECURE 0x01
Definition at line 47 of file buffer.h.
Referenced by BUF_MEM_free().
BUF_memdup
#define BUF_memdup (data, size) OPENSSL_memdup(data, size)
Definition at line 35 of file buffer.h.
Referenced by o2i_SCT().
BUF_strdup
#define BUF_strdup (s) OPENSSL_strdup(s)
Definition at line 33 of file buffer.h.
BUF_strlcat
#define BUF_strlcat (dst, src, size) OPENSSL_strlcat(dst, src, size)
Definition at line 37 of file buffer.h.
BUF_strlcpy
#define BUF_strlcpy (dst, src, size) OPENSSL_strlcpy(dst, src, size)
Definition at line 36 of file buffer.h.
BUF_strndup
#define BUF_strndup (s, size) OPENSSL_strndup(s, size)
Definition at line 34 of file buffer.h.
BUF_strnlen
#define BUF_strnlen (str, maxlen) OPENSSL_strnlen(str, maxlen)
Definition at line 38 of file buffer.h.
Function Documentation
BUF_MEM_free()
void BUF_MEM_free (BUF_MEM * a)
Definition at line 43 of file buffer.c.
References BUF_MEM_FLAG_SECURE, NULL, OPENSSL_clear_free, OPENSSL_free, and OPENSSL_secure_free.
Referenced by SSL_clear().
BUF_MEM_grow()
size_t BUF_MEM_grow (BUF_MEM * str, size_t len)
Definition at line 72 of file buffer.c.
Referenced by WPACKET_reserve_bytes().
BUF_MEM_grow_clean()
size_t BUF_MEM_grow_clean (BUF_MEM * str, size_t len)
Definition at line 109 of file buffer.c.
BUF_MEM_new()
BUF_MEM* BUF_MEM_new (void)
Definition at line 31 of file buffer.c.
BUF_MEM_new_ex()
BUF_MEM* BUF_MEM_new_ex (unsigned long flags)
Definition at line 21 of file buffer.c.
BUF_reverse()
void BUF_reverse (unsigned char * out, const unsigned char * in, size_t siz)
Definition at line 147 of file buffer.c.
ERR_load_BUF_strings()
int ERR_load_BUF_strings (void)
Definition at line 34 of file buf_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().