crypto/x509/by_file.c File Reference
by_file.c File Reference
#include <stdio.h>
#include <time.h>
#include <errno.h>
#include "internal/cryptlib.h"
#include <openssl/lhash.h>
#include <openssl/buffer.h>
#include <openssl/x509.h>
#include <openssl/pem.h>
#include "x509_lcl.h"
Functions
X509_LOOKUP_METHOD * X509_LOOKUP_file (void)
int X509_load_cert_file (X509_LOOKUP *ctx, const char *file, int type)
int X509_load_crl_file (X509_LOOKUP *ctx, const char *file, int type)
int X509_load_cert_crl_file (X509_LOOKUP *ctx, const char *file, int type)
Function Documentation
X509_load_cert_crl_file()
int X509_load_cert_crl_file (X509_LOOKUP * ctx, const char * file, int type)
Definition at line 189 of file by_file.c.
References BIO_free(), BIO_new_file(), X509_INFO::crl, ERR_R_PEM_LIB, ERR_R_SYS_LIB, in, NULL, STACK_OF, X509_INFO::x509, X509_F_X509_LOAD_CERT_CRL_FILE, X509_FILETYPE_PEM, X509_INFO_free(), X509_load_cert_file(), X509_STORE_add_cert(), X509_STORE_add_crl(), and X509err.
X509_load_cert_file()
int X509_load_cert_file (X509_LOOKUP * ctx, const char * file, int type)
Definition at line 75 of file by_file.c.
Referenced by X509_load_cert_crl_file().
X509_load_crl_file()
int X509_load_crl_file (X509_LOOKUP * ctx, const char * file, int type)
Definition at line 132 of file by_file.c.
X509_LOOKUP_file()
X509_LOOKUP_METHOD* X509_LOOKUP_file (void)
Definition at line 36 of file by_file.c.