crypto/comp/c_zlib.c File Reference
c_zlib.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <openssl/objects.h>
#include "internal/comp.h"
#include <openssl/err.h>
#include "internal/cryptlib_int.h"
#include "internal/bio.h"
#include "comp_lcl.h"
Functions
COMP_METHOD * COMP_zlib (void)
void comp_zlib_cleanup_int (void)
Function Documentation
COMP_zlib()
COMP_METHOD * COMP_zlib (void)
Definition at line 209 of file c_zlib.c.
Referenced by comp_zlib_cleanup_int(), and DEFINE_RUN_ONCE_STATIC().
comp_zlib_cleanup_int()
void comp_zlib_cleanup_int (void)
Definition at line 262 of file c_zlib.c.
References BIO_get_data(), BIO_set_data(), BIO_set_init(), BIO_TYPE_COMP, bread_conv(), bwrite_conv(), COMP_F_BIO_ZLIB_NEW, COMP_R_ZLIB_NOT_SUPPORTED, COMP_zlib(), COMPerr, ctx, DSO_free(), ERR_R_MALLOC_FAILURE, fp, NULL, OPENSSL_free, OPENSSL_zalloc, and ptr.