crypto/camellia/camellia.c File Reference
camellia.c File Reference
#include <openssl/camellia.h>
#include "cmll_locl.h"
#include <string.h>
#include <stdlib.h>
Macros
#define RightRotate(x, s) (((x) >> (s)) + ((x) << (32 - s)))
#define LeftRotate(x, s) (((x) << (s)) + ((x) >> (32 - s)))
#define GETU32(p) (((u32)(p)[0] << 24) ^ ((u32)(p)[1] << 16) ^ ((u32)(p)[2] << 8) ^ ((u32)(p)[3]))
#define PUTU32(p, v) ((p)[0] = (u8)((v) >> 24), (p)[1] = (u8)((v) >> 16), (p)[2] = (u8)((v) >> 8), (p)[3] = (u8)(v))
#define SBOX1_1110 Camellia_SBOX[0]
#define SBOX4_4404 Camellia_SBOX[1]
#define SBOX2_0222 Camellia_SBOX[2]
#define SBOX3_3033 Camellia_SBOX[3]
#define Camellia_Feistel(_s0, _s1, _s2, _s3, _key)
#define RotLeft128(_s0, _s1, _s2, _s3, _n)
Functions
int Camellia_Ekeygen (int keyBitLength, const u8 *rawKey, KEY_TABLE_TYPE k)
void Camellia_EncryptBlock_Rounds (int grandRounds, const u8 plaintext[], const KEY_TABLE_TYPE keyTable, u8 ciphertext[])
void Camellia_EncryptBlock (int keyBitLength, const u8 plaintext[], const KEY_TABLE_TYPE keyTable, u8 ciphertext[])
void Camellia_DecryptBlock_Rounds (int grandRounds, const u8 ciphertext[], const KEY_TABLE_TYPE keyTable, u8 plaintext[])
void Camellia_DecryptBlock (int keyBitLength, const u8 plaintext[], const KEY_TABLE_TYPE keyTable, u8 ciphertext[])
Macro Definition Documentation
Camellia_Feistel
#define Camellia_Feistel (_s0, _s1, _s2, _s3, _key)
Value:
do {\
        register u32 _t0,_t1,_t2,_t3;\
\
        _t0  = _s0 ^ (_key)[0];\
        _t3  = SBOX4_4404[_t0&0xff];\
        _t1  = _s1 ^ (_key)[1];\
        _t3 ^= SBOX3_3033[(_t0 >> 8)&0xff];\
        _t2  = SBOX1_1110[_t1&0xff];\
        _t3 ^= SBOX2_0222[(_t0 >> 16)&0xff];\
        _t2 ^= SBOX4_4404[(_t1 >> 8)&0xff];\
        _t3 ^= SBOX1_1110[(_t0 >> 24)];\
        _t2 ^= _t3;\
        _t3  = RightRotate(_t3,8);\
        _t2 ^= SBOX3_3033[(_t1 >> 16)&0xff];\
        _s3 ^= _t3;\
        _t2 ^= SBOX2_0222[(_t1 >> 24)];\
        _s2 ^= _t2; \
        _s3 ^= _t2;\
} while(0)
Definition at line 287 of file camellia.c.
GETU32
#define GETU32 (p) (((u32)(p)[0] << 24) ^ ((u32)(p)[1] << 16) ^ ((u32)(p)[2] << 8) ^ ((u32)(p)[3]))
Definition at line 89 of file camellia.c.
LeftRotate
#define LeftRotate (x, s) (((x) << (s)) + ((x) >> (32 - s)))
Definition at line 85 of file camellia.c.
PUTU32
#define PUTU32 (p, v) ((p)[0] = (u8)((v) >> 24), (p)[1] = (u8)((v) >> 16), (p)[2] = (u8)((v) >> 8), (p)[3] = (u8)(v))
Definition at line 90 of file camellia.c.
RightRotate
#define RightRotate (x, s) (((x) >> (s)) + ((x) << (32 - s)))
Definition at line 84 of file camellia.c.
RotLeft128
#define RotLeft128 (_s0, _s1, _s2, _s3, _n)
Value:
do {\
        u32 _t0=_s0>>(32-_n);\
        _s0 = (_s0<<_n) | (_s1>>(32-_n));\
        _s1 = (_s1<<_n) | (_s2>>(32-_n));\
        _s2 = (_s2<<_n) | (_s3>>(32-_n));\
        _s3 = (_s3<<_n) | _t0;\
} while (0)
Definition at line 312 of file camellia.c.
SBOX1_1110
#define SBOX1_1110 Camellia_SBOX[0]
Definition at line 94 of file camellia.c.
SBOX2_0222
#define SBOX2_0222 Camellia_SBOX[2]
Definition at line 96 of file camellia.c.
SBOX3_3033
#define SBOX3_3033 Camellia_SBOX[3]
Definition at line 97 of file camellia.c.
SBOX4_4404
#define SBOX4_4404 Camellia_SBOX[1]
Definition at line 95 of file camellia.c.
Function Documentation
Camellia_DecryptBlock()
void Camellia_DecryptBlock (int keyBitLength, const u8 plaintext[], const KEY_TABLE_TYPE keyTable, u8 ciphertext[])
Definition at line 536 of file camellia.c.
References Camellia_DecryptBlock_Rounds().
Camellia_DecryptBlock_Rounds()
void Camellia_DecryptBlock_Rounds (int grandRounds, const u8 ciphertext[], const KEY_TABLE_TYPE keyTable, u8 plaintext[])
Definition at line 490 of file camellia.c.
Referenced by Camellia_DecryptBlock().
Camellia_Ekeygen()
int Camellia_Ekeygen (int keyBitLength, const u8 * rawKey, KEY_TABLE_TYPE k)
Definition at line 320 of file camellia.c.
Referenced by Camellia_set_key().
Camellia_EncryptBlock()
void Camellia_EncryptBlock (int keyBitLength, const u8 plaintext[], const KEY_TABLE_TYPE keyTable, u8 ciphertext[])
Definition at line 483 of file camellia.c.
References Camellia_EncryptBlock_Rounds().
Camellia_EncryptBlock_Rounds()
void Camellia_EncryptBlock_Rounds (int grandRounds, const u8 plaintext[], const KEY_TABLE_TYPE keyTable, u8 ciphertext[])
Definition at line 437 of file camellia.c.
Referenced by Camellia_EncryptBlock().