test/cipher_overhead_test.c File Reference
cipher_overhead_test.c File Reference
#include <stdio.h>
#include "../ssl/ssl_locl.h"
Functions
int main (void)
Function Documentation
main()
int main (void)
Definition at line 14 of file cipher_overhead_test.c.
References ex, in, OSSLzu, ssl3_get_cipher(), ssl3_num_ciphers(), and ssl_cipher_get_overhead().