crypto/cmac/cmac.c File Reference
cmac.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "internal/cryptlib.h"
#include <openssl/cmac.h>
Data Structures
struct CMAC_CTX
Functions
CMAC_CTX * CMAC_CTX_new (void)
void CMAC_CTX_cleanup (CMAC_CTX *ctx)
EVP_CIPHER_CTX * CMAC_CTX_get0_cipher_ctx (CMAC_CTX *ctx)
void CMAC_CTX_free (CMAC_CTX *ctx)
int CMAC_CTX_copy (CMAC_CTX *out, const CMAC_CTX *in)
int CMAC_Init (CMAC_CTX *ctx, const void *key, size_t keylen, const EVP_CIPHER *cipher, ENGINE *impl)
int CMAC_Update (CMAC_CTX *ctx, const void *in, size_t dlen)
int CMAC_Final (CMAC_CTX *ctx, unsigned char *out, size_t *poutlen)
int CMAC_resume (CMAC_CTX *ctx)
Function Documentation
CMAC_CTX_cleanup()
void CMAC_CTX_cleanup (CMAC_CTX * ctx)
Definition at line 61 of file cmac.c.
References EVP_CIPHER_CTX_free(), EVP_MAX_BLOCK_LENGTH, and OPENSSL_cleanse().
Referenced by CMAC_CTX_free().
CMAC_CTX_copy()
int CMAC_CTX_copy (CMAC_CTX * out, const CMAC_CTX * in)
Definition at line 84 of file cmac.c.
CMAC_CTX_free()
void CMAC_CTX_free (CMAC_CTX * ctx)
Definition at line 76 of file cmac.c.
References CMAC_CTX_cleanup(), and OPENSSL_free.
CMAC_CTX_get0_cipher_ctx()
EVP_CIPHER_CTX* CMAC_CTX_get0_cipher_ctx (CMAC_CTX * ctx)
Definition at line 71 of file cmac.c.
CMAC_CTX_new()
CMAC_CTX* CMAC_CTX_new (void)
Definition at line 45 of file cmac.c.
References ctx, EVP_CIPHER_CTX_new(), NULL, OPENSSL_free, and OPENSSL_malloc.
CMAC_Final()
int CMAC_Final (CMAC_CTX * ctx, unsigned char * out, size_t * poutlen)
Definition at line 183 of file cmac.c.
CMAC_Init()
int CMAC_Init (CMAC_CTX * ctx, const void * key, size_t keylen, const EVP_CIPHER * cipher, ENGINE * impl)
Definition at line 100 of file cmac.c.
CMAC_resume()
int CMAC_resume (CMAC_CTX * ctx)
Definition at line 211 of file cmac.c.
References EVP_EncryptInit_ex(), and NULL.
CMAC_Update()
int CMAC_Update (CMAC_CTX * ctx, const void * in, size_t dlen)
Definition at line 143 of file cmac.c.
References data, EVP_Cipher(), EVP_CIPHER_CTX_block_size(), and in.