crypto/camellia/cmll_locl.h File Reference
cmll_locl.h File Reference
Typedefs
typedef unsigned int u32
typedef unsigned char u8
Functions
int Camellia_Ekeygen (int keyBitLength, const u8 *rawKey, KEY_TABLE_TYPE keyTable)
void Camellia_EncryptBlock_Rounds (int grandRounds, const u8 plaintext[], const KEY_TABLE_TYPE keyTable, u8 ciphertext[])
void Camellia_DecryptBlock_Rounds (int grandRounds, const u8 ciphertext[], const KEY_TABLE_TYPE keyTable, u8 plaintext[])
void Camellia_EncryptBlock (int keyBitLength, const u8 plaintext[], const KEY_TABLE_TYPE keyTable, u8 ciphertext[])
void Camellia_DecryptBlock (int keyBitLength, const u8 ciphertext[], const KEY_TABLE_TYPE keyTable, u8 plaintext[])
Typedef Documentation
u32
typedef unsigned int u32
Definition at line 28 of file cmll_locl.h.
u8
typedef unsigned char u8
Definition at line 29 of file cmll_locl.h.
Function Documentation
Camellia_DecryptBlock()
void Camellia_DecryptBlock (int keyBitLength, const u8 ciphertext[], const KEY_TABLE_TYPE keyTable, u8 plaintext[])
Definition at line 536 of file camellia.c.
References Camellia_DecryptBlock_Rounds().
Camellia_DecryptBlock_Rounds()
void Camellia_DecryptBlock_Rounds (int grandRounds, const u8 ciphertext[], const KEY_TABLE_TYPE keyTable, u8 plaintext[])
Definition at line 490 of file camellia.c.
Referenced by Camellia_DecryptBlock().
Camellia_Ekeygen()
int Camellia_Ekeygen (int keyBitLength, const u8 * rawKey, KEY_TABLE_TYPE keyTable)
Definition at line 320 of file camellia.c.
Referenced by Camellia_set_key().
Camellia_EncryptBlock()
void Camellia_EncryptBlock (int keyBitLength, const u8 plaintext[], const KEY_TABLE_TYPE keyTable, u8 ciphertext[])
Definition at line 483 of file camellia.c.
References Camellia_EncryptBlock_Rounds().
Camellia_EncryptBlock_Rounds()
void Camellia_EncryptBlock_Rounds (int grandRounds, const u8 plaintext[], const KEY_TABLE_TYPE keyTable, u8 ciphertext[])
Definition at line 437 of file camellia.c.
Referenced by Camellia_EncryptBlock().