crypto/cms/cms_env.c File Reference
cms_env.c File Reference
#include "internal/cryptlib.h"
#include <openssl/asn1t.h>
#include <openssl/pem.h>
#include <openssl/x509v3.h>
#include <openssl/err.h>
#include <openssl/cms.h>
#include <openssl/aes.h>
#include "cms_lcl.h"
#include "internal/asn1_int.h"
#include "internal/evp_int.h"
Functions
CMS_EnvelopedData * cms_get0_enveloped (CMS_ContentInfo *cms)
int cms_env_asn1_ctrl (CMS_RecipientInfo *ri, int cmd)
STACK_OF (CMS_RecipientInfo)
int CMS_RecipientInfo_type (CMS_RecipientInfo *ri)
EVP_PKEY_CTX * CMS_RecipientInfo_get0_pkey_ctx (CMS_RecipientInfo *ri)
CMS_ContentInfo * CMS_EnvelopedData_create (const EVP_CIPHER *cipher)
CMS_RecipientInfo * CMS_add1_recipient_cert (CMS_ContentInfo *cms, X509 *recip, unsigned int flags)
int CMS_RecipientInfo_ktri_get0_algs (CMS_RecipientInfo *ri, EVP_PKEY **pk, X509 **recip, X509_ALGOR **palg)
int CMS_RecipientInfo_ktri_get0_signer_id (CMS_RecipientInfo *ri, ASN1_OCTET_STRING **keyid, X509_NAME **issuer, ASN1_INTEGER **sno)
int CMS_RecipientInfo_ktri_cert_cmp (CMS_RecipientInfo *ri, X509 *cert)
int CMS_RecipientInfo_set0_pkey (CMS_RecipientInfo *ri, EVP_PKEY *pkey)
int CMS_RecipientInfo_kekri_id_cmp (CMS_RecipientInfo *ri, const unsigned char *id, size_t idlen)
CMS_RecipientInfo * CMS_add0_recipient_key (CMS_ContentInfo *cms, int nid, unsigned char *key, size_t keylen, unsigned char *id, size_t idlen, ASN1_GENERALIZEDTIME *date, ASN1_OBJECT *otherTypeId, ASN1_TYPE *otherType)
int CMS_RecipientInfo_kekri_get0_id (CMS_RecipientInfo *ri, X509_ALGOR **palg, ASN1_OCTET_STRING **pid, ASN1_GENERALIZEDTIME **pdate, ASN1_OBJECT **potherid, ASN1_TYPE **pothertype)
int CMS_RecipientInfo_set0_key (CMS_RecipientInfo *ri, unsigned char *key, size_t keylen)
int CMS_RecipientInfo_decrypt (CMS_ContentInfo *cms, CMS_RecipientInfo *ri)
int CMS_RecipientInfo_encrypt (CMS_ContentInfo *cms, CMS_RecipientInfo *ri)
BIO * cms_EnvelopedData_init_bio (CMS_ContentInfo *cms)
int cms_pkey_get_ri_type (EVP_PKEY *pk)
Function Documentation
CMS_add0_recipient_key()
CMS_RecipientInfo* CMS_add0_recipient_key (CMS_ContentInfo * cms, int nid, unsigned char * key, size_t keylen, unsigned char * id, size_t idlen, ASN1_GENERALIZEDTIME * date, ASN1_OBJECT * otherTypeId, ASN1_TYPE * otherType)
Definition at line 461 of file cms_env.c.
References CMS_F_CMS_ADD0_RECIPIENT_KEY, cms_get0_enveloped(), CMS_R_INVALID_KEY_LENGTH, CMSerr, NID_id_aes128_wrap, NID_id_aes192_wrap, NID_id_aes256_wrap, NID_undef, and NULL.
CMS_add1_recipient_cert()
CMS_RecipientInfo* CMS_add1_recipient_cert (CMS_ContentInfo * cms, X509 * recip, unsigned int flags)
Definition at line 178 of file cms_env.c.
References CMS_F_CMS_ADD1_RECIPIENT_CERT, cms_get0_enveloped(), cms_pkey_get_ri_type(), CMS_R_ERROR_GETTING_PUBLIC_KEY, CMS_RECIPINFO_TRANS, CMSerr, M_ASN1_new_of, NULL, and X509_get0_pubkey().
cms_env_asn1_ctrl()
int cms_env_asn1_ctrl (CMS_RecipientInfo * ri, int cmd)
Definition at line 51 of file cms_env.c.
References CMS_RECIPINFO_AGREE, and CMS_RECIPINFO_TRANS.
Referenced by CMS_RecipientInfo_kari_decrypt().
CMS_EnvelopedData_create()
CMS_ContentInfo* CMS_EnvelopedData_create (const EVP_CIPHER * cipher)
Definition at line 104 of file cms_env.c.
cms_EnvelopedData_init_bio()
BIO* cms_EnvelopedData_init_bio (CMS_ContentInfo * cms)
Definition at line 842 of file cms_env.c.
References STACK_OF().
Referenced by CMS_dataInit().
cms_get0_enveloped()
CMS_EnvelopedData* cms_get0_enveloped (CMS_ContentInfo * cms)
Definition at line 23 of file cms_env.c.
References CMS_F_CMS_GET0_ENVELOPED, CMS_R_CONTENT_TYPE_NOT_ENVELOPED_DATA, CMSerr, NID_pkcs7_enveloped, NULL, and OBJ_obj2nid().
Referenced by CMS_add0_recipient_key(), CMS_add1_recipient_cert(), and STACK_OF().
cms_pkey_get_ri_type()
int cms_pkey_get_ri_type (EVP_PKEY * pk)
Definition at line 893 of file cms_env.c.
References ASN1_PKEY_CTRL_CMS_RI_TYPE, and CMS_RECIPINFO_TRANS.
Referenced by CMS_add1_recipient_cert().
CMS_RecipientInfo_decrypt()
int CMS_RecipientInfo_decrypt (CMS_ContentInfo * cms, CMS_RecipientInfo * ri)
Definition at line 738 of file cms_env.c.
References CMS_RECIPINFO_TRANS.
Referenced by CMS_decrypt_set1_key(), and CMS_decrypt_set1_password().
CMS_RecipientInfo_encrypt()
int CMS_RecipientInfo_encrypt (CMS_ContentInfo * cms, CMS_RecipientInfo * ri)
Definition at line 757 of file cms_env.c.
References CMS_RECIPINFO_TRANS.
CMS_RecipientInfo_get0_pkey_ctx()
EVP_PKEY_CTX* CMS_RecipientInfo_get0_pkey_ctx (CMS_RecipientInfo * ri)
Definition at line 95 of file cms_env.c.
References CMS_RECIPINFO_AGREE, CMS_RECIPINFO_TRANS, and NULL.
CMS_RecipientInfo_kekri_get0_id()
int CMS_RecipientInfo_kekri_get0_id (CMS_RecipientInfo * ri, X509_ALGOR ** palg, ASN1_OCTET_STRING ** pid, ASN1_GENERALIZEDTIME ** pdate, ASN1_OBJECT ** potherid, ASN1_TYPE ** pothertype)
Definition at line 561 of file cms_env.c.
References CMS_F_CMS_RECIPIENTINFO_KEKRI_GET0_ID, CMS_R_NOT_KEK, CMS_RECIPINFO_KEK, CMSerr, and NULL.
CMS_RecipientInfo_kekri_id_cmp()
int CMS_RecipientInfo_kekri_id_cmp (CMS_RecipientInfo * ri, const unsigned char * id, size_t idlen)
Definition at line 425 of file cms_env.c.
References ASN1_OCTET_STRING_cmp(), CMS_F_CMS_RECIPIENTINFO_KEKRI_ID_CMP, CMS_R_NOT_KEK, CMS_RECIPINFO_KEK, CMSerr, and V_ASN1_OCTET_STRING.
Referenced by CMS_decrypt_set1_key().
CMS_RecipientInfo_ktri_cert_cmp()
int CMS_RecipientInfo_ktri_cert_cmp (CMS_RecipientInfo * ri, X509 * cert)
Definition at line 269 of file cms_env.c.
CMS_RecipientInfo_ktri_get0_algs()
int CMS_RecipientInfo_ktri_get0_algs (CMS_RecipientInfo * ri, EVP_PKEY ** pk, X509 ** recip, X509_ALGOR ** palg)
Definition at line 231 of file cms_env.c.
References CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_ALGS, CMS_R_NOT_KEY_TRANSPORT, CMS_RECIPINFO_TRANS, and CMSerr.
CMS_RecipientInfo_ktri_get0_signer_id()
int CMS_RecipientInfo_ktri_get0_signer_id (CMS_RecipientInfo * ri, ASN1_OCTET_STRING ** keyid, X509_NAME ** issuer, ASN1_INTEGER ** sno)
Definition at line 253 of file cms_env.c.
References CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_SIGNER_ID, CMS_R_NOT_KEY_TRANSPORT, CMS_RECIPINFO_TRANS, cms_SignerIdentifier_get0_signer_id(), and CMSerr.
CMS_RecipientInfo_set0_key()
int CMS_RecipientInfo_set0_key (CMS_RecipientInfo * ri, unsigned char * key, size_t keylen)
Definition at line 595 of file cms_env.c.
References CMS_F_CMS_RECIPIENTINFO_SET0_KEY, CMS_R_NOT_KEK, CMS_RECIPINFO_KEK, CMSerr, and key.
Referenced by CMS_decrypt_set1_key().
CMS_RecipientInfo_set0_pkey()
int CMS_RecipientInfo_set0_pkey (CMS_RecipientInfo * ri, EVP_PKEY * pkey)
Definition at line 279 of file cms_env.c.
References CMS_F_CMS_RECIPIENTINFO_SET0_PKEY, CMS_R_NOT_KEY_TRANSPORT, CMS_RECIPINFO_TRANS, and CMSerr.
CMS_RecipientInfo_type()
int CMS_RecipientInfo_type (CMS_RecipientInfo * ri)
Definition at line 90 of file cms_env.c.
Referenced by CMS_decrypt_set1_key(), and CMS_decrypt_set1_password().
STACK_OF()
STACK_OF (CMS_RecipientInfo)
Definition at line 81 of file cms_env.c.
References cms_get0_enveloped(), and NULL.
Referenced by cms_EnvelopedData_init_bio().