crypto/cms/cms_smime.c File Reference
cms_smime.c File Reference
#include "internal/cryptlib.h"
#include <openssl/asn1t.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/err.h>
#include <openssl/cms.h>
#include "cms_lcl.h"
#include "internal/asn1_int.h"
Functions
int CMS_data (CMS_ContentInfo *cms, BIO *out, unsigned int flags)
CMS_ContentInfo * CMS_data_create (BIO *in, unsigned int flags)
int CMS_digest_verify (CMS_ContentInfo *cms, BIO *dcont, BIO *out, unsigned int flags)
CMS_ContentInfo * CMS_digest_create (BIO *in, const EVP_MD *md, unsigned int flags)
int CMS_EncryptedData_decrypt (CMS_ContentInfo *cms, const unsigned char *key, size_t keylen, BIO *dcont, BIO *out, unsigned int flags)
CMS_ContentInfo * CMS_EncryptedData_encrypt (BIO *in, const EVP_CIPHER *cipher, const unsigned char *key, size_t keylen, unsigned int flags)
int CMS_verify (CMS_ContentInfo *cms, STACK_OF(X509) *certs, X509_STORE *store, BIO *dcont, BIO *out, unsigned int flags)
int CMS_verify_receipt (CMS_ContentInfo *rcms, CMS_ContentInfo *ocms, STACK_OF(X509) *certs, X509_STORE *store, unsigned int flags)
CMS_ContentInfo * CMS_sign (X509 *signcert, EVP_PKEY *pkey, STACK_OF(X509) *certs, BIO *data, unsigned int flags)
CMS_ContentInfo * CMS_sign_receipt (CMS_SignerInfo *si, X509 *signcert, EVP_PKEY *pkey, STACK_OF(X509) *certs, unsigned int flags)
CMS_ContentInfo * CMS_encrypt (STACK_OF(X509) *certs, BIO *data, const EVP_CIPHER *cipher, unsigned int flags)
int CMS_decrypt_set1_pkey (CMS_ContentInfo *cms, EVP_PKEY *pk, X509 *cert)
int CMS_decrypt_set1_key (CMS_ContentInfo *cms, unsigned char *key, size_t keylen, const unsigned char *id, size_t idlen)
int CMS_decrypt_set1_password (CMS_ContentInfo *cms, unsigned char *pass, ossl_ssize_t passlen)
int CMS_decrypt (CMS_ContentInfo *cms, EVP_PKEY *pk, X509 *cert, BIO *dcont, BIO *out, unsigned int flags)
int CMS_final (CMS_ContentInfo *cms, BIO *data, BIO *dcont, unsigned int flags)
int CMS_uncompress (CMS_ContentInfo *cms, BIO *dcont, BIO *out, unsigned int flags)
CMS_ContentInfo * CMS_compress (BIO *in, int comp_nid, unsigned int flags)
Function Documentation
CMS_compress()
CMS_ContentInfo* CMS_compress (BIO * in, int comp_nid, unsigned int flags)
Definition at line 838 of file cms_smime.c.
References CMS_F_CMS_COMPRESS, CMS_R_UNSUPPORTED_COMPRESSION_ALGORITHM, CMSerr, and NULL.
CMS_data()
int CMS_data (CMS_ContentInfo * cms, BIO * out, unsigned int flags)
Definition at line 102 of file cms_smime.c.
References CMS_dataInit(), CMS_F_CMS_DATA, CMS_get0_type(), CMS_R_TYPE_NOT_DATA, CMSerr, NID_pkcs7_data, NULL, and OBJ_obj2nid().
CMS_data_create()
CMS_ContentInfo* CMS_data_create (BIO * in, unsigned int flags)
Definition at line 118 of file cms_smime.c.
References cms_Data_create(), CMS_final(), CMS_STREAM, and NULL.
CMS_decrypt()
int CMS_decrypt (CMS_ContentInfo * cms, EVP_PKEY * pk, X509 * cert, BIO * dcont, BIO * out, unsigned int flags)
Definition at line 732 of file cms_smime.c.
References CMS_F_CMS_DECRYPT, CMS_get0_type(), CMS_R_TYPE_NOT_ENVELOPED_DATA, CMSerr, NID_pkcs7_enveloped, and OBJ_obj2nid().
CMS_decrypt_set1_key()
int CMS_decrypt_set1_key (CMS_ContentInfo * cms, unsigned char * key, size_t keylen, const unsigned char * id, size_t idlen)
Definition at line 673 of file cms_smime.c.
References CMS_F_CMS_DECRYPT_SET1_KEY, CMS_R_DECRYPT_ERROR, CMS_R_NO_MATCHING_RECIPIENT, CMS_RecipientInfo_decrypt(), CMS_RecipientInfo_kekri_id_cmp(), CMS_RecipientInfo_set0_key(), CMS_RecipientInfo_type(), CMS_RECIPINFO_KEK, CMSerr, ERR_clear_error(), NULL, and STACK_OF.
CMS_decrypt_set1_password()
int CMS_decrypt_set1_password (CMS_ContentInfo * cms, unsigned char * pass, ossl_ssize_t passlen)
Definition at line 709 of file cms_smime.c.
References CMS_F_CMS_DECRYPT_SET1_PASSWORD, CMS_R_NO_MATCHING_RECIPIENT, CMS_RecipientInfo_decrypt(), CMS_RecipientInfo_set0_password(), CMS_RecipientInfo_type(), CMS_RECIPINFO_PASS, CMSerr, NULL, and STACK_OF.
CMS_decrypt_set1_pkey()
int CMS_decrypt_set1_pkey (CMS_ContentInfo * cms, EVP_PKEY * pk, X509 * cert)
Definition at line 603 of file cms_smime.c.
References STACK_OF.
CMS_digest_create()
CMS_ContentInfo* CMS_digest_create (BIO * in, const EVP_MD * md, unsigned int flags)
Definition at line 156 of file cms_smime.c.
CMS_digest_verify()
int CMS_digest_verify (CMS_ContentInfo * cms, BIO * dcont, BIO * out, unsigned int flags)
Definition at line 133 of file cms_smime.c.
References CMS_F_CMS_DIGEST_VERIFY, CMS_get0_type(), CMS_R_TYPE_NOT_DIGESTED_DATA, CMSerr, NID_pkcs7_digest, and OBJ_obj2nid().
CMS_encrypt()
CMS_ContentInfo* CMS_encrypt (STACK_OF(X509) * certs, BIO * data, const EVP_CIPHER * cipher, unsigned int flags)
Definition at line 546 of file cms_smime.c.
CMS_EncryptedData_decrypt()
int CMS_EncryptedData_decrypt (CMS_ContentInfo * cms, const unsigned char * key, size_t keylen, BIO * dcont, BIO * out, unsigned int flags)
Definition at line 176 of file cms_smime.c.
References CMS_F_CMS_ENCRYPTEDDATA_DECRYPT, CMS_get0_type(), CMS_R_TYPE_NOT_ENCRYPTED_DATA, CMSerr, NID_pkcs7_encrypted, and OBJ_obj2nid().
CMS_EncryptedData_encrypt()
CMS_ContentInfo* CMS_EncryptedData_encrypt (BIO * in, const EVP_CIPHER * cipher, const unsigned char * key, size_t keylen, unsigned int flags)
Definition at line 201 of file cms_smime.c.
CMS_final()
int CMS_final (CMS_ContentInfo * cms, BIO * data, BIO * dcont, unsigned int flags)
Definition at line 759 of file cms_smime.c.
Referenced by CMS_data_create(), CMS_sign(), and CMS_sign_receipt().
CMS_sign()
CMS_ContentInfo* CMS_sign (X509 * signcert, EVP_PKEY * pkey, STACK_OF(X509) * certs, BIO * data, unsigned int flags)
Definition at line 435 of file cms_smime.c.
References CMS_add1_cert(), CMS_add1_signer(), CMS_ASCIICRLF, CMS_DETACHED, CMS_F_CMS_SIGN, CMS_final(), CMS_PARTIAL, CMS_R_ADD_SIGNER_ERROR, CMS_set1_eContentType(), CMS_set_detached(), CMS_SignedData_init(), CMS_STREAM, CMSerr, ERR_R_MALLOC_FAILURE, NID_id_ct_asciiTextWithCRLF, NULL, and OBJ_nid2obj().
Referenced by CMS_sign_receipt().
CMS_sign_receipt()
CMS_ContentInfo* CMS_sign_receipt (CMS_SignerInfo * si, X509 * signcert, EVP_PKEY * pkey, STACK_OF(X509) * certs, unsigned int flags)
Definition at line 478 of file cms_smime.c.
References BIO_free(), BIO_new_mem_buf(), CMS_add1_signer(), CMS_BINARY, CMS_DETACHED, cms_encode_Receipt(), CMS_F_CMS_SIGN_RECEIPT, CMS_final(), CMS_get0_content(), cms_msgSigDigest_add1(), CMS_PARTIAL, CMS_R_ADD_SIGNER_ERROR, CMS_R_NO_KEY_OR_CERT, CMS_set1_eContentType(), CMS_sign(), CMS_STREAM, CMS_TEXT, CMSerr, NID_id_smime_ct_receipt, NULL, and OBJ_nid2obj().
CMS_uncompress()
int CMS_uncompress (CMS_ContentInfo * cms, BIO * dcont, BIO * out, unsigned int flags)
Definition at line 831 of file cms_smime.c.
References CMS_F_CMS_UNCOMPRESS, CMS_R_UNSUPPORTED_COMPRESSION_ALGORITHM, and CMSerr.
CMS_verify()
int CMS_verify (CMS_ContentInfo * cms, STACK_OF(X509) * certs, X509_STORE * store, BIO * dcont, BIO * out, unsigned int flags)
Definition at line 265 of file cms_smime.c.
References NULL, and STACK_OF.
Referenced by CMS_verify_receipt().
CMS_verify_receipt()
int CMS_verify_receipt (CMS_ContentInfo * rcms, CMS_ContentInfo * ocms, STACK_OF(X509) * certs, X509_STORE * store, unsigned int flags)
Definition at line 423 of file cms_smime.c.
References CMS_DETACHED, cms_Receipt_verify(), CMS_TEXT, CMS_verify(), and NULL.