crypto/cms/cms_kari.c File Reference
cms_kari.c File Reference
#include "internal/cryptlib.h"
#include <openssl/asn1t.h>
#include <openssl/pem.h>
#include <openssl/x509v3.h>
#include <openssl/err.h>
#include <openssl/cms.h>
#include <openssl/aes.h>
#include "cms_lcl.h"
#include "internal/asn1_int.h"
Functions
int CMS_RecipientInfo_kari_get0_alg (CMS_RecipientInfo *ri, X509_ALGOR **palg, ASN1_OCTET_STRING **pukm)
* CMS_RecipientInfo_kari_get0_reks (CMS_RecipientInfo *ri)
int CMS_RecipientInfo_kari_get0_orig_id (CMS_RecipientInfo *ri, X509_ALGOR **pubalg, ASN1_BIT_STRING **pubkey, ASN1_OCTET_STRING **keyid, X509_NAME **issuer, ASN1_INTEGER **sno)
int CMS_RecipientInfo_kari_orig_id_cmp (CMS_RecipientInfo *ri, X509 *cert)
int CMS_RecipientEncryptedKey_get0_id (CMS_RecipientEncryptedKey *rek, ASN1_OCTET_STRING **keyid, ASN1_GENERALIZEDTIME **tm, CMS_OtherKeyAttribute **other, X509_NAME **issuer, ASN1_INTEGER **sno)
int CMS_RecipientEncryptedKey_cert_cmp (CMS_RecipientEncryptedKey *rek, X509 *cert)
int CMS_RecipientInfo_kari_set0_pkey (CMS_RecipientInfo *ri, EVP_PKEY *pk)
EVP_CIPHER_CTX * CMS_RecipientInfo_kari_get0_ctx (CMS_RecipientInfo *ri)
int CMS_RecipientInfo_kari_decrypt (CMS_ContentInfo *cms, CMS_RecipientInfo *ri, CMS_RecipientEncryptedKey *rek)
int cms_RecipientInfo_kari_init (CMS_RecipientInfo *ri, X509 *recip, EVP_PKEY *pk, unsigned int flags)
int cms_RecipientInfo_kari_encrypt (CMS_ContentInfo *cms, CMS_RecipientInfo *ri)
Function Documentation
CMS_RecipientEncryptedKey_cert_cmp()
int CMS_RecipientEncryptedKey_cert_cmp (CMS_RecipientEncryptedKey * rek, X509 * cert)
Definition at line 143 of file cms_kari.c.
CMS_RecipientEncryptedKey_get0_id()
int CMS_RecipientEncryptedKey_get0_id (CMS_RecipientEncryptedKey * rek, ASN1_OCTET_STRING ** keyid, ASN1_GENERALIZEDTIME ** tm, CMS_OtherKeyAttribute ** other, X509_NAME ** issuer, ASN1_INTEGER ** sno)
Definition at line 109 of file cms_kari.c.
References CMS_REK_ISSUER_SERIAL, CMS_REK_KEYIDENTIFIER, and NULL.
CMS_RecipientInfo_kari_decrypt()
int CMS_RecipientInfo_kari_decrypt (CMS_ContentInfo * cms, CMS_RecipientInfo * ri, CMS_RecipientEncryptedKey * rek)
Definition at line 228 of file cms_kari.c.
References cms_env_asn1_ctrl(), and NULL.
cms_RecipientInfo_kari_encrypt()
int cms_RecipientInfo_kari_encrypt (CMS_ContentInfo * cms, CMS_RecipientInfo * ri)
Definition at line 363 of file cms_kari.c.
References CMS_F_CMS_RECIPIENTINFO_KARI_ENCRYPT, CMS_R_NOT_KEY_AGREEMENT, CMS_RECIPINFO_AGREE, CMSerr, and STACK_OF.
CMS_RecipientInfo_kari_get0_alg()
int CMS_RecipientInfo_kari_get0_alg (CMS_RecipientInfo * ri, X509_ALGOR ** palg, ASN1_OCTET_STRING ** pukm)
Definition at line 22 of file cms_kari.c.
References CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ALG, CMS_R_NOT_KEY_AGREEMENT, CMS_RECIPINFO_AGREE, CMSerr, and STACK_OF.
CMS_RecipientInfo_kari_get0_ctx()
EVP_CIPHER_CTX* CMS_RecipientInfo_kari_get0_ctx (CMS_RecipientInfo * ri)
Definition at line 174 of file cms_kari.c.
References CMS_RECIPINFO_AGREE, and NULL.
CMS_RecipientInfo_kari_get0_orig_id()
int CMS_RecipientInfo_kari_get0_orig_id (CMS_RecipientInfo * ri, X509_ALGOR ** pubalg, ASN1_BIT_STRING ** pubkey, ASN1_OCTET_STRING ** keyid, X509_NAME ** issuer, ASN1_INTEGER ** sno)
Definition at line 51 of file cms_kari.c.
References CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ORIG_ID, CMS_OIK_ISSUER_SERIAL, CMS_OIK_KEYIDENTIFIER, CMS_OIK_PUBKEY, CMS_R_NOT_KEY_AGREEMENT, CMS_RECIPINFO_AGREE, CMSerr, and NULL.
CMS_RecipientInfo_kari_get0_reks()
* CMS_RecipientInfo_kari_get0_reks (CMS_RecipientInfo * ri)
Definition at line 41 of file cms_kari.c.
References CMS_F_CMS_RECIPIENTINFO_KARI_GET0_REKS, CMS_R_NOT_KEY_AGREEMENT, CMS_RECIPINFO_AGREE, CMSerr, and NULL.
cms_RecipientInfo_kari_init()
int cms_RecipientInfo_kari_init (CMS_RecipientInfo * ri, X509 * recip, EVP_PKEY * pk, unsigned int flags)
Definition at line 287 of file cms_kari.c.
References CMS_RECIPINFO_AGREE, CMS_REK_ISSUER_SERIAL, CMS_REK_KEYIDENTIFIER, cms_set1_ias(), cms_set1_keyid(), CMS_USE_KEYID, M_ASN1_free_of, M_ASN1_new_of, and NULL.
CMS_RecipientInfo_kari_orig_id_cmp()
int CMS_RecipientInfo_kari_orig_id_cmp (CMS_RecipientInfo * ri, X509 * cert)
Definition at line 93 of file cms_kari.c.
CMS_RecipientInfo_kari_set0_pkey()
int CMS_RecipientInfo_kari_set0_pkey (CMS_RecipientInfo * ri, EVP_PKEY * pk)
Definition at line 155 of file cms_kari.c.