include/openssl/cms.h File Reference
cms.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
Macros
#define CMS_SIGNERINFO_ISSUER_SERIAL 0
#define CMS_SIGNERINFO_KEYIDENTIFIER 1
#define CMS_RECIPINFO_NONE -1
#define CMS_RECIPINFO_TRANS 0
#define CMS_RECIPINFO_AGREE 1
#define CMS_RECIPINFO_KEK 2
#define CMS_RECIPINFO_PASS 3
#define CMS_RECIPINFO_OTHER 4
#define CMS_TEXT 0x1
#define CMS_NOCERTS 0x2
#define CMS_NO_CONTENT_VERIFY 0x4
#define CMS_NO_ATTR_VERIFY 0x8
#define CMS_NOSIGS (CMS_NO_CONTENT_VERIFY|CMS_NO_ATTR_VERIFY)
#define CMS_NOINTERN 0x10
#define CMS_NO_SIGNER_CERT_VERIFY 0x20
#define CMS_NOVERIFY 0x20
#define CMS_DETACHED 0x40
#define CMS_BINARY 0x80
#define CMS_NOATTR 0x100
#define CMS_NOSMIMECAP 0x200
#define CMS_NOOLDMIMETYPE 0x400
#define CMS_CRLFEOL 0x800
#define CMS_STREAM 0x1000
#define CMS_NOCRL 0x2000
#define CMS_PARTIAL 0x4000
#define CMS_REUSE_DIGEST 0x8000
#define CMS_USE_KEYID 0x10000
#define CMS_DEBUG_DECRYPT 0x20000
#define CMS_KEY_PARAM 0x40000
#define CMS_ASCIICRLF 0x80000
#define CMS_F_CHECK_CONTENT 99
#define CMS_F_CMS_ADD0_CERT 164
#define CMS_F_CMS_ADD0_RECIPIENT_KEY 100
#define CMS_F_CMS_ADD0_RECIPIENT_PASSWORD 165
#define CMS_F_CMS_ADD1_RECEIPTREQUEST 158
#define CMS_F_CMS_ADD1_RECIPIENT_CERT 101
#define CMS_F_CMS_ADD1_SIGNER 102
#define CMS_F_CMS_ADD1_SIGNINGTIME 103
#define CMS_F_CMS_COMPRESS 104
#define CMS_F_CMS_COMPRESSEDDATA_CREATE 105
#define CMS_F_CMS_COMPRESSEDDATA_INIT_BIO 106
#define CMS_F_CMS_COPY_CONTENT 107
#define CMS_F_CMS_COPY_MESSAGEDIGEST 108
#define CMS_F_CMS_DATA 109
#define CMS_F_CMS_DATAFINAL 110
#define CMS_F_CMS_DATAINIT 111
#define CMS_F_CMS_DECRYPT 112
#define CMS_F_CMS_DECRYPT_SET1_KEY 113
#define CMS_F_CMS_DECRYPT_SET1_PASSWORD 166
#define CMS_F_CMS_DECRYPT_SET1_PKEY 114
#define CMS_F_CMS_DIGESTALGORITHM_FIND_CTX 115
#define CMS_F_CMS_DIGESTALGORITHM_INIT_BIO 116
#define CMS_F_CMS_DIGESTEDDATA_DO_FINAL 117
#define CMS_F_CMS_DIGEST_VERIFY 118
#define CMS_F_CMS_ENCODE_RECEIPT 161
#define CMS_F_CMS_ENCRYPT 119
#define CMS_F_CMS_ENCRYPTEDCONTENT_INIT_BIO 120
#define CMS_F_CMS_ENCRYPTEDDATA_DECRYPT 121
#define CMS_F_CMS_ENCRYPTEDDATA_ENCRYPT 122
#define CMS_F_CMS_ENCRYPTEDDATA_SET1_KEY 123
#define CMS_F_CMS_ENVELOPEDDATA_CREATE 124
#define CMS_F_CMS_ENVELOPEDDATA_INIT_BIO 125
#define CMS_F_CMS_ENVELOPED_DATA_INIT 126
#define CMS_F_CMS_ENV_ASN1_CTRL 171
#define CMS_F_CMS_FINAL 127
#define CMS_F_CMS_GET0_CERTIFICATE_CHOICES 128
#define CMS_F_CMS_GET0_CONTENT 129
#define CMS_F_CMS_GET0_ECONTENT_TYPE 130
#define CMS_F_CMS_GET0_ENVELOPED 131
#define CMS_F_CMS_GET0_REVOCATION_CHOICES 132
#define CMS_F_CMS_GET0_SIGNED 133
#define CMS_F_CMS_MSGSIGDIGEST_ADD1 162
#define CMS_F_CMS_RECEIPTREQUEST_CREATE0 159
#define CMS_F_CMS_RECEIPT_VERIFY 160
#define CMS_F_CMS_RECIPIENTINFO_DECRYPT 134
#define CMS_F_CMS_RECIPIENTINFO_ENCRYPT 169
#define CMS_F_CMS_RECIPIENTINFO_KARI_ENCRYPT 178
#define CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ALG 175
#define CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ORIG_ID 173
#define CMS_F_CMS_RECIPIENTINFO_KARI_GET0_REKS 172
#define CMS_F_CMS_RECIPIENTINFO_KARI_ORIG_ID_CMP 174
#define CMS_F_CMS_RECIPIENTINFO_KEKRI_DECRYPT 135
#define CMS_F_CMS_RECIPIENTINFO_KEKRI_ENCRYPT 136
#define CMS_F_CMS_RECIPIENTINFO_KEKRI_GET0_ID 137
#define CMS_F_CMS_RECIPIENTINFO_KEKRI_ID_CMP 138
#define CMS_F_CMS_RECIPIENTINFO_KTRI_CERT_CMP 139
#define CMS_F_CMS_RECIPIENTINFO_KTRI_DECRYPT 140
#define CMS_F_CMS_RECIPIENTINFO_KTRI_ENCRYPT 141
#define CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_ALGS 142
#define CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_SIGNER_ID 143
#define CMS_F_CMS_RECIPIENTINFO_PWRI_CRYPT 167
#define CMS_F_CMS_RECIPIENTINFO_SET0_KEY 144
#define CMS_F_CMS_RECIPIENTINFO_SET0_PASSWORD 168
#define CMS_F_CMS_RECIPIENTINFO_SET0_PKEY 145
#define CMS_F_CMS_SD_ASN1_CTRL 170
#define CMS_F_CMS_SET1_IAS 176
#define CMS_F_CMS_SET1_KEYID 177
#define CMS_F_CMS_SET1_SIGNERIDENTIFIER 146
#define CMS_F_CMS_SET_DETACHED 147
#define CMS_F_CMS_SIGN 148
#define CMS_F_CMS_SIGNED_DATA_INIT 149
#define CMS_F_CMS_SIGNERINFO_CONTENT_SIGN 150
#define CMS_F_CMS_SIGNERINFO_SIGN 151
#define CMS_F_CMS_SIGNERINFO_VERIFY 152
#define CMS_F_CMS_SIGNERINFO_VERIFY_CERT 153
#define CMS_F_CMS_SIGNERINFO_VERIFY_CONTENT 154
#define CMS_F_CMS_SIGN_RECEIPT 163
#define CMS_F_CMS_STREAM 155
#define CMS_F_CMS_UNCOMPRESS 156
#define CMS_F_CMS_VERIFY 157
#define CMS_R_ADD_SIGNER_ERROR 99
#define CMS_R_CERTIFICATE_ALREADY_PRESENT 175
#define CMS_R_CERTIFICATE_HAS_NO_KEYID 160
#define CMS_R_CERTIFICATE_VERIFY_ERROR 100
#define CMS_R_CIPHER_INITIALISATION_ERROR 101
#define CMS_R_CIPHER_PARAMETER_INITIALISATION_ERROR 102
#define CMS_R_CMS_DATAFINAL_ERROR 103
#define CMS_R_CMS_LIB 104
#define CMS_R_CONTENTIDENTIFIER_MISMATCH 170
#define CMS_R_CONTENT_NOT_FOUND 105
#define CMS_R_CONTENT_TYPE_MISMATCH 171
#define CMS_R_CONTENT_TYPE_NOT_COMPRESSED_DATA 106
#define CMS_R_CONTENT_TYPE_NOT_ENVELOPED_DATA 107
#define CMS_R_CONTENT_TYPE_NOT_SIGNED_DATA 108
#define CMS_R_CONTENT_VERIFY_ERROR 109
#define CMS_R_CTRL_ERROR 110
#define CMS_R_CTRL_FAILURE 111
#define CMS_R_DECRYPT_ERROR 112
#define CMS_R_ERROR_GETTING_PUBLIC_KEY 113
#define CMS_R_ERROR_READING_MESSAGEDIGEST_ATTRIBUTE 114
#define CMS_R_ERROR_SETTING_KEY 115
#define CMS_R_ERROR_SETTING_RECIPIENTINFO 116
#define CMS_R_INVALID_ENCRYPTED_KEY_LENGTH 117
#define CMS_R_INVALID_KEY_ENCRYPTION_PARAMETER 176
#define CMS_R_INVALID_KEY_LENGTH 118
#define CMS_R_MD_BIO_INIT_ERROR 119
#define CMS_R_MESSAGEDIGEST_ATTRIBUTE_WRONG_LENGTH 120
#define CMS_R_MESSAGEDIGEST_WRONG_LENGTH 121
#define CMS_R_MSGSIGDIGEST_ERROR 172
#define CMS_R_MSGSIGDIGEST_VERIFICATION_FAILURE 162
#define CMS_R_MSGSIGDIGEST_WRONG_LENGTH 163
#define CMS_R_NEED_ONE_SIGNER 164
#define CMS_R_NOT_A_SIGNED_RECEIPT 165
#define CMS_R_NOT_ENCRYPTED_DATA 122
#define CMS_R_NOT_KEK 123
#define CMS_R_NOT_KEY_AGREEMENT 181
#define CMS_R_NOT_KEY_TRANSPORT 124
#define CMS_R_NOT_PWRI 177
#define CMS_R_NOT_SUPPORTED_FOR_THIS_KEY_TYPE 125
#define CMS_R_NO_CIPHER 126
#define CMS_R_NO_CONTENT 127
#define CMS_R_NO_CONTENT_TYPE 173
#define CMS_R_NO_DEFAULT_DIGEST 128
#define CMS_R_NO_DIGEST_SET 129
#define CMS_R_NO_KEY 130
#define CMS_R_NO_KEY_OR_CERT 174
#define CMS_R_NO_MATCHING_DIGEST 131
#define CMS_R_NO_MATCHING_RECIPIENT 132
#define CMS_R_NO_MATCHING_SIGNATURE 166
#define CMS_R_NO_MSGSIGDIGEST 167
#define CMS_R_NO_PASSWORD 178
#define CMS_R_NO_PRIVATE_KEY 133
#define CMS_R_NO_PUBLIC_KEY 134
#define CMS_R_NO_RECEIPT_REQUEST 168
#define CMS_R_NO_SIGNERS 135
#define CMS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE 136
#define CMS_R_RECEIPT_DECODE_ERROR 169
#define CMS_R_RECIPIENT_ERROR 137
#define CMS_R_SIGNER_CERTIFICATE_NOT_FOUND 138
#define CMS_R_SIGNFINAL_ERROR 139
#define CMS_R_SMIME_TEXT_ERROR 140
#define CMS_R_STORE_INIT_ERROR 141
#define CMS_R_TYPE_NOT_COMPRESSED_DATA 142
#define CMS_R_TYPE_NOT_DATA 143
#define CMS_R_TYPE_NOT_DIGESTED_DATA 144
#define CMS_R_TYPE_NOT_ENCRYPTED_DATA 145
#define CMS_R_TYPE_NOT_ENVELOPED_DATA 146
#define CMS_R_UNABLE_TO_FINALIZE_CONTEXT 147
#define CMS_R_UNKNOWN_CIPHER 148
#define CMS_R_UNKNOWN_DIGEST_ALGORIHM 149
#define CMS_R_UNKNOWN_ID 150
#define CMS_R_UNSUPPORTED_COMPRESSION_ALGORITHM 151
#define CMS_R_UNSUPPORTED_CONTENT_TYPE 152
#define CMS_R_UNSUPPORTED_KEK_ALGORITHM 153
#define CMS_R_UNSUPPORTED_KEY_ENCRYPTION_ALGORITHM 179
#define CMS_R_UNSUPPORTED_RECIPIENT_TYPE 154
#define CMS_R_UNSUPPORTED_RECPIENTINFO_TYPE 155
#define CMS_R_UNSUPPORTED_TYPE 156
#define CMS_R_UNWRAP_ERROR 157
#define CMS_R_UNWRAP_FAILURE 180
#define CMS_R_VERIFICATION_FAILURE 158
#define CMS_R_WRAP_ERROR 159
Typedefs
typedef struct CMS_ReceiptRequest_st CMS_ReceiptRequest
Functions
const ASN1_OBJECT * CMS_get0_type (const CMS_ContentInfo *cms)
BIO * CMS_dataInit (CMS_ContentInfo *cms, BIO *icont)
int CMS_dataFinal (CMS_ContentInfo *cms, BIO *bio)
ASN1_OCTET_STRING ** CMS_get0_content (CMS_ContentInfo *cms)
int CMS_is_detached (CMS_ContentInfo *cms)
int CMS_set_detached (CMS_ContentInfo *cms, int detached)
int CMS_stream (unsigned char ***boundary, CMS_ContentInfo *cms)
CMS_ContentInfo * d2i_CMS_bio (BIO *bp, CMS_ContentInfo **cms)
int i2d_CMS_bio (BIO *bp, CMS_ContentInfo *cms)
BIO * BIO_new_CMS (BIO *out, CMS_ContentInfo *cms)
int i2d_CMS_bio_stream (BIO *out, CMS_ContentInfo *cms, BIO *in, int flags)
int PEM_write_bio_CMS_stream (BIO *out, CMS_ContentInfo *cms, BIO *in, int flags)
CMS_ContentInfo * SMIME_read_CMS (BIO *bio, BIO **bcont)
int SMIME_write_CMS (BIO *bio, CMS_ContentInfo *cms, BIO *data, int flags)
int CMS_final (CMS_ContentInfo *cms, BIO *data, BIO *dcont, unsigned int flags)
CMS_ContentInfo * CMS_sign (X509 *signcert, EVP_PKEY *pkey, STACK_OF(X509) *certs, BIO *data, unsigned int flags)
CMS_ContentInfo * CMS_sign_receipt (CMS_SignerInfo *si, X509 *signcert, EVP_PKEY *pkey, STACK_OF(X509) *certs, unsigned int flags)
int CMS_data (CMS_ContentInfo *cms, BIO *out, unsigned int flags)
CMS_ContentInfo * CMS_data_create (BIO *in, unsigned int flags)
int CMS_digest_verify (CMS_ContentInfo *cms, BIO *dcont, BIO *out, unsigned int flags)
CMS_ContentInfo * CMS_digest_create (BIO *in, const EVP_MD *md, unsigned int flags)
int CMS_EncryptedData_decrypt (CMS_ContentInfo *cms, const unsigned char *key, size_t keylen, BIO *dcont, BIO *out, unsigned int flags)
CMS_ContentInfo * CMS_EncryptedData_encrypt (BIO *in, const EVP_CIPHER *cipher, const unsigned char *key, size_t keylen, unsigned int flags)
int CMS_EncryptedData_set1_key (CMS_ContentInfo *cms, const EVP_CIPHER *ciph, const unsigned char *key, size_t keylen)
int CMS_verify (CMS_ContentInfo *cms, STACK_OF(X509) *certs, X509_STORE *store, BIO *dcont, BIO *out, unsigned int flags)
int CMS_verify_receipt (CMS_ContentInfo *rcms, CMS_ContentInfo *ocms, STACK_OF(X509) *certs, X509_STORE *store, unsigned int flags)
STACK_OF (X509) *CMS_get0_signers(CMS_ContentInfo *cms)
CMS_ContentInfo * CMS_encrypt (STACK_OF(X509) *certs, BIO *in, const EVP_CIPHER *cipher, unsigned int flags)
int CMS_decrypt (CMS_ContentInfo *cms, EVP_PKEY *pkey, X509 *cert, BIO *dcont, BIO *out, unsigned int flags)
int CMS_decrypt_set1_pkey (CMS_ContentInfo *cms, EVP_PKEY *pk, X509 *cert)
int CMS_decrypt_set1_key (CMS_ContentInfo *cms, unsigned char *key, size_t keylen, const unsigned char *id, size_t idlen)
int CMS_decrypt_set1_password (CMS_ContentInfo *cms, unsigned char *pass, ossl_ssize_t passlen)
STACK_OF (CMS_RecipientInfo) *CMS_get0_RecipientInfos(CMS_ContentInfo *cms)
int CMS_RecipientInfo_type (CMS_RecipientInfo *ri)
EVP_PKEY_CTX * CMS_RecipientInfo_get0_pkey_ctx (CMS_RecipientInfo *ri)
CMS_ContentInfo * CMS_EnvelopedData_create (const EVP_CIPHER *cipher)
CMS_RecipientInfo * CMS_add1_recipient_cert (CMS_ContentInfo *cms, X509 *recip, unsigned int flags)
int CMS_RecipientInfo_set0_pkey (CMS_RecipientInfo *ri, EVP_PKEY *pkey)
int CMS_RecipientInfo_ktri_cert_cmp (CMS_RecipientInfo *ri, X509 *cert)
int CMS_RecipientInfo_ktri_get0_algs (CMS_RecipientInfo *ri, EVP_PKEY **pk, X509 **recip, X509_ALGOR **palg)
int CMS_RecipientInfo_ktri_get0_signer_id (CMS_RecipientInfo *ri, ASN1_OCTET_STRING **keyid, X509_NAME **issuer, ASN1_INTEGER **sno)
CMS_RecipientInfo * CMS_add0_recipient_key (CMS_ContentInfo *cms, int nid, unsigned char *key, size_t keylen, unsigned char *id, size_t idlen, ASN1_GENERALIZEDTIME *date, ASN1_OBJECT *otherTypeId, ASN1_TYPE *otherType)
int CMS_RecipientInfo_kekri_get0_id (CMS_RecipientInfo *ri, X509_ALGOR **palg, ASN1_OCTET_STRING **pid, ASN1_GENERALIZEDTIME **pdate, ASN1_OBJECT **potherid, ASN1_TYPE **pothertype)
int CMS_RecipientInfo_set0_key (CMS_RecipientInfo *ri, unsigned char *key, size_t keylen)
int CMS_RecipientInfo_kekri_id_cmp (CMS_RecipientInfo *ri, const unsigned char *id, size_t idlen)
int CMS_RecipientInfo_set0_password (CMS_RecipientInfo *ri, unsigned char *pass, ossl_ssize_t passlen)
CMS_RecipientInfo * CMS_add0_recipient_password (CMS_ContentInfo *cms, int iter, int wrap_nid, int pbe_nid, unsigned char *pass, ossl_ssize_t passlen, const EVP_CIPHER *kekciph)
int CMS_RecipientInfo_decrypt (CMS_ContentInfo *cms, CMS_RecipientInfo *ri)
int CMS_RecipientInfo_encrypt (CMS_ContentInfo *cms, CMS_RecipientInfo *ri)
int CMS_uncompress (CMS_ContentInfo *cms, BIO *dcont, BIO *out, unsigned int flags)
CMS_ContentInfo * CMS_compress (BIO *in, int comp_nid, unsigned int flags)
int CMS_set1_eContentType (CMS_ContentInfo *cms, const ASN1_OBJECT *oid)
const ASN1_OBJECT * CMS_get0_eContentType (CMS_ContentInfo *cms)
CMS_CertificateChoices * CMS_add0_CertificateChoices (CMS_ContentInfo *cms)
int CMS_add0_cert (CMS_ContentInfo *cms, X509 *cert)
int CMS_add1_cert (CMS_ContentInfo *cms, X509 *cert)
CMS_RevocationInfoChoice * CMS_add0_RevocationInfoChoice (CMS_ContentInfo *cms)
int CMS_add0_crl (CMS_ContentInfo *cms, X509_CRL *crl)
int CMS_add1_crl (CMS_ContentInfo *cms, X509_CRL *crl)
STACK_OF (X509_CRL) *CMS_get1_crls(CMS_ContentInfo *cms)
int CMS_SignedData_init (CMS_ContentInfo *cms)
CMS_SignerInfo * CMS_add1_signer (CMS_ContentInfo *cms, X509 *signer, EVP_PKEY *pk, const EVP_MD *md, unsigned int flags)
EVP_PKEY_CTX * CMS_SignerInfo_get0_pkey_ctx (CMS_SignerInfo *si)
EVP_MD_CTX * CMS_SignerInfo_get0_md_ctx (CMS_SignerInfo *si)
STACK_OF (CMS_SignerInfo) *CMS_get0_SignerInfos(CMS_ContentInfo *cms)
void CMS_SignerInfo_set1_signer_cert (CMS_SignerInfo *si, X509 *signer)
int CMS_SignerInfo_get0_signer_id (CMS_SignerInfo *si, ASN1_OCTET_STRING **keyid, X509_NAME **issuer, ASN1_INTEGER **sno)
int CMS_SignerInfo_cert_cmp (CMS_SignerInfo *si, X509 *cert)
int CMS_set1_signers_certs (CMS_ContentInfo *cms, STACK_OF(X509) *certs, unsigned int flags)
void CMS_SignerInfo_get0_algs (CMS_SignerInfo *si, EVP_PKEY **pk, X509 **signer, X509_ALGOR **pdig, X509_ALGOR **psig)
ASN1_OCTET_STRING * CMS_SignerInfo_get0_signature (CMS_SignerInfo *si)
int CMS_SignerInfo_sign (CMS_SignerInfo *si)
int CMS_SignerInfo_verify (CMS_SignerInfo *si)
int CMS_SignerInfo_verify_content (CMS_SignerInfo *si, BIO *chain)
int CMS_add_smimecap (CMS_SignerInfo *si, STACK_OF(X509_ALGOR) *algs)
int CMS_add_simple_smimecap (STACK_OF(X509_ALGOR) **algs, int algnid, int keysize)
int CMS_add_standard_smimecap (STACK_OF(X509_ALGOR) **smcap)
int CMS_signed_get_attr_count (const CMS_SignerInfo *si)
int CMS_signed_get_attr_by_NID (const CMS_SignerInfo *si, int nid, int lastpos)
int CMS_signed_get_attr_by_OBJ (const CMS_SignerInfo *si, const ASN1_OBJECT *obj, int lastpos)
X509_ATTRIBUTE * CMS_signed_get_attr (const CMS_SignerInfo *si, int loc)
X509_ATTRIBUTE * CMS_signed_delete_attr (CMS_SignerInfo *si, int loc)
int CMS_signed_add1_attr (CMS_SignerInfo *si, X509_ATTRIBUTE *attr)
int CMS_signed_add1_attr_by_OBJ (CMS_SignerInfo *si, const ASN1_OBJECT *obj, int type, const void *bytes, int len)
int CMS_signed_add1_attr_by_NID (CMS_SignerInfo *si, int nid, int type, const void *bytes, int len)
int CMS_signed_add1_attr_by_txt (CMS_SignerInfo *si, const char *attrname, int type, const void *bytes, int len)
void * CMS_signed_get0_data_by_OBJ (CMS_SignerInfo *si, const ASN1_OBJECT *oid, int lastpos, int type)
int CMS_unsigned_get_attr_count (const CMS_SignerInfo *si)
int CMS_unsigned_get_attr_by_NID (const CMS_SignerInfo *si, int nid, int lastpos)
int CMS_unsigned_get_attr_by_OBJ (const CMS_SignerInfo *si, const ASN1_OBJECT *obj, int lastpos)
X509_ATTRIBUTE * CMS_unsigned_get_attr (const CMS_SignerInfo *si, int loc)
X509_ATTRIBUTE * CMS_unsigned_delete_attr (CMS_SignerInfo *si, int loc)
int CMS_unsigned_add1_attr (CMS_SignerInfo *si, X509_ATTRIBUTE *attr)
int CMS_unsigned_add1_attr_by_OBJ (CMS_SignerInfo *si, const ASN1_OBJECT *obj, int type, const void *bytes, int len)
int CMS_unsigned_add1_attr_by_NID (CMS_SignerInfo *si, int nid, int type, const void *bytes, int len)
int CMS_unsigned_add1_attr_by_txt (CMS_SignerInfo *si, const char *attrname, int type, const void *bytes, int len)
void * CMS_unsigned_get0_data_by_OBJ (CMS_SignerInfo *si, ASN1_OBJECT *oid, int lastpos, int type)
int CMS_RecipientInfo_kari_get0_alg (CMS_RecipientInfo *ri, X509_ALGOR **palg, ASN1_OCTET_STRING **pukm)
* CMS_RecipientInfo_kari_get0_reks (CMS_RecipientInfo *ri)
int CMS_RecipientInfo_kari_get0_orig_id (CMS_RecipientInfo *ri, X509_ALGOR **pubalg, ASN1_BIT_STRING **pubkey, ASN1_OCTET_STRING **keyid, X509_NAME **issuer, ASN1_INTEGER **sno)
int CMS_RecipientInfo_kari_orig_id_cmp (CMS_RecipientInfo *ri, X509 *cert)
int CMS_RecipientEncryptedKey_get0_id (CMS_RecipientEncryptedKey *rek, ASN1_OCTET_STRING **keyid, ASN1_GENERALIZEDTIME **tm, CMS_OtherKeyAttribute **other, X509_NAME **issuer, ASN1_INTEGER **sno)
int CMS_RecipientEncryptedKey_cert_cmp (CMS_RecipientEncryptedKey *rek, X509 *cert)
int CMS_RecipientInfo_kari_set0_pkey (CMS_RecipientInfo *ri, EVP_PKEY *pk)
EVP_CIPHER_CTX * CMS_RecipientInfo_kari_get0_ctx (CMS_RecipientInfo *ri)
int CMS_RecipientInfo_kari_decrypt (CMS_ContentInfo *cms, CMS_RecipientInfo *ri, CMS_RecipientEncryptedKey *rek)
int CMS_SharedInfo_encode (unsigned char **pder, X509_ALGOR *kekalg, ASN1_OCTET_STRING *ukm, int keylen)
int ERR_load_CMS_strings (void)
Macro Definition Documentation
CMS_ASCIICRLF
#define CMS_ASCIICRLF 0x80000
Definition at line 74 of file cms.h.
Referenced by CMS_sign().
CMS_BINARY
#define CMS_BINARY 0x80
Definition at line 62 of file cms.h.
Referenced by CMS_sign_receipt().
CMS_CRLFEOL
#define CMS_CRLFEOL 0x800
Definition at line 66 of file cms.h.
CMS_DEBUG_DECRYPT
#define CMS_DEBUG_DECRYPT 0x20000
Definition at line 72 of file cms.h.
CMS_DETACHED
#define CMS_DETACHED 0x40
Definition at line 61 of file cms.h.
Referenced by CMS_sign(), CMS_sign_receipt(), and CMS_verify_receipt().
CMS_F_CHECK_CONTENT
#define CMS_F_CHECK_CONTENT 99
Definition at line 343 of file cms.h.
CMS_F_CMS_ADD0_CERT
#define CMS_F_CMS_ADD0_CERT 164
Definition at line 344 of file cms.h.
CMS_F_CMS_ADD0_RECIPIENT_KEY
#define CMS_F_CMS_ADD0_RECIPIENT_KEY 100
Definition at line 345 of file cms.h.
Referenced by CMS_add0_recipient_key().
CMS_F_CMS_ADD0_RECIPIENT_PASSWORD
#define CMS_F_CMS_ADD0_RECIPIENT_PASSWORD 165
Definition at line 346 of file cms.h.
CMS_F_CMS_ADD1_RECEIPTREQUEST
#define CMS_F_CMS_ADD1_RECEIPTREQUEST 158
Definition at line 347 of file cms.h.
Referenced by CMS_add1_ReceiptRequest().
CMS_F_CMS_ADD1_RECIPIENT_CERT
#define CMS_F_CMS_ADD1_RECIPIENT_CERT 101
Definition at line 348 of file cms.h.
Referenced by CMS_add1_recipient_cert().
CMS_F_CMS_ADD1_SIGNER
#define CMS_F_CMS_ADD1_SIGNER 102
Definition at line 349 of file cms.h.
CMS_F_CMS_ADD1_SIGNINGTIME
#define CMS_F_CMS_ADD1_SIGNINGTIME 103
Definition at line 350 of file cms.h.
CMS_F_CMS_COMPRESS
#define CMS_F_CMS_COMPRESS 104
Definition at line 351 of file cms.h.
Referenced by CMS_compress().
CMS_F_CMS_COMPRESSEDDATA_CREATE
#define CMS_F_CMS_COMPRESSEDDATA_CREATE 105
Definition at line 352 of file cms.h.
CMS_F_CMS_COMPRESSEDDATA_INIT_BIO
#define CMS_F_CMS_COMPRESSEDDATA_INIT_BIO 106
Definition at line 353 of file cms.h.
CMS_F_CMS_COPY_CONTENT
#define CMS_F_CMS_COPY_CONTENT 107
Definition at line 354 of file cms.h.
CMS_F_CMS_COPY_MESSAGEDIGEST
#define CMS_F_CMS_COPY_MESSAGEDIGEST 108
Definition at line 355 of file cms.h.
CMS_F_CMS_DATA
#define CMS_F_CMS_DATA 109
Definition at line 356 of file cms.h.
Referenced by CMS_data().
CMS_F_CMS_DATAFINAL
#define CMS_F_CMS_DATAFINAL 110
Definition at line 357 of file cms.h.
Referenced by CMS_dataFinal().
CMS_F_CMS_DATAINIT
#define CMS_F_CMS_DATAINIT 111
Definition at line 358 of file cms.h.
Referenced by CMS_dataInit().
CMS_F_CMS_DECRYPT
#define CMS_F_CMS_DECRYPT 112
Definition at line 359 of file cms.h.
Referenced by CMS_decrypt().
CMS_F_CMS_DECRYPT_SET1_KEY
#define CMS_F_CMS_DECRYPT_SET1_KEY 113
Definition at line 360 of file cms.h.
Referenced by CMS_decrypt_set1_key().
CMS_F_CMS_DECRYPT_SET1_PASSWORD
#define CMS_F_CMS_DECRYPT_SET1_PASSWORD 166
Definition at line 361 of file cms.h.
Referenced by CMS_decrypt_set1_password().
CMS_F_CMS_DECRYPT_SET1_PKEY
#define CMS_F_CMS_DECRYPT_SET1_PKEY 114
Definition at line 362 of file cms.h.
CMS_F_CMS_DIGEST_VERIFY
#define CMS_F_CMS_DIGEST_VERIFY 118
Definition at line 366 of file cms.h.
Referenced by CMS_digest_verify().
CMS_F_CMS_DIGESTALGORITHM_FIND_CTX
#define CMS_F_CMS_DIGESTALGORITHM_FIND_CTX 115
Definition at line 363 of file cms.h.
Referenced by cms_DigestAlgorithm_find_ctx().
CMS_F_CMS_DIGESTALGORITHM_INIT_BIO
#define CMS_F_CMS_DIGESTALGORITHM_INIT_BIO 116
Definition at line 364 of file cms.h.
Referenced by cms_DigestAlgorithm_init_bio().
CMS_F_CMS_DIGESTEDDATA_DO_FINAL
#define CMS_F_CMS_DIGESTEDDATA_DO_FINAL 117
Definition at line 365 of file cms.h.
CMS_F_CMS_ENCODE_RECEIPT
#define CMS_F_CMS_ENCODE_RECEIPT 161
Definition at line 367 of file cms.h.
Referenced by cms_encode_Receipt().
CMS_F_CMS_ENCRYPT
#define CMS_F_CMS_ENCRYPT 119
Definition at line 368 of file cms.h.
CMS_F_CMS_ENCRYPTEDCONTENT_INIT_BIO
#define CMS_F_CMS_ENCRYPTEDCONTENT_INIT_BIO 120
Definition at line 369 of file cms.h.
CMS_F_CMS_ENCRYPTEDDATA_DECRYPT
#define CMS_F_CMS_ENCRYPTEDDATA_DECRYPT 121
Definition at line 370 of file cms.h.
Referenced by CMS_EncryptedData_decrypt().
CMS_F_CMS_ENCRYPTEDDATA_ENCRYPT
#define CMS_F_CMS_ENCRYPTEDDATA_ENCRYPT 122
Definition at line 371 of file cms.h.
CMS_F_CMS_ENCRYPTEDDATA_SET1_KEY
#define CMS_F_CMS_ENCRYPTEDDATA_SET1_KEY 123
Definition at line 372 of file cms.h.
Referenced by CMS_EncryptedData_set1_key().
CMS_F_CMS_ENV_ASN1_CTRL
#define CMS_F_CMS_ENV_ASN1_CTRL 171
Definition at line 376 of file cms.h.
CMS_F_CMS_ENVELOPED_DATA_INIT
#define CMS_F_CMS_ENVELOPED_DATA_INIT 126
Definition at line 375 of file cms.h.
CMS_F_CMS_ENVELOPEDDATA_CREATE
#define CMS_F_CMS_ENVELOPEDDATA_CREATE 124
Definition at line 373 of file cms.h.
CMS_F_CMS_ENVELOPEDDATA_INIT_BIO
#define CMS_F_CMS_ENVELOPEDDATA_INIT_BIO 125
Definition at line 374 of file cms.h.
CMS_F_CMS_FINAL
#define CMS_F_CMS_FINAL 127
Definition at line 377 of file cms.h.
CMS_F_CMS_GET0_CERTIFICATE_CHOICES
#define CMS_F_CMS_GET0_CERTIFICATE_CHOICES 128
Definition at line 378 of file cms.h.
Referenced by cms_DigestAlgorithm_find_ctx().
CMS_F_CMS_GET0_CONTENT
#define CMS_F_CMS_GET0_CONTENT 129
Definition at line 379 of file cms.h.
Referenced by CMS_get0_content().
CMS_F_CMS_GET0_ECONTENT_TYPE
#define CMS_F_CMS_GET0_ECONTENT_TYPE 130
Definition at line 380 of file cms.h.
CMS_F_CMS_GET0_ENVELOPED
#define CMS_F_CMS_GET0_ENVELOPED 131
Definition at line 381 of file cms.h.
Referenced by cms_get0_enveloped().
CMS_F_CMS_GET0_REVOCATION_CHOICES
#define CMS_F_CMS_GET0_REVOCATION_CHOICES 132
Definition at line 382 of file cms.h.
CMS_F_CMS_GET0_SIGNED
#define CMS_F_CMS_GET0_SIGNED 133
Definition at line 383 of file cms.h.
CMS_F_CMS_MSGSIGDIGEST_ADD1
#define CMS_F_CMS_MSGSIGDIGEST_ADD1 162
Definition at line 384 of file cms.h.
CMS_F_CMS_RECEIPT_VERIFY
#define CMS_F_CMS_RECEIPT_VERIFY 160
Definition at line 386 of file cms.h.
Referenced by cms_Receipt_verify().
CMS_F_CMS_RECEIPTREQUEST_CREATE0
#define CMS_F_CMS_RECEIPTREQUEST_CREATE0 159
Definition at line 385 of file cms.h.
Referenced by CMS_ReceiptRequest_create0().
CMS_F_CMS_RECIPIENTINFO_DECRYPT
#define CMS_F_CMS_RECIPIENTINFO_DECRYPT 134
Definition at line 387 of file cms.h.
CMS_F_CMS_RECIPIENTINFO_ENCRYPT
#define CMS_F_CMS_RECIPIENTINFO_ENCRYPT 169
Definition at line 388 of file cms.h.
CMS_F_CMS_RECIPIENTINFO_KARI_ENCRYPT
#define CMS_F_CMS_RECIPIENTINFO_KARI_ENCRYPT 178
Definition at line 389 of file cms.h.
Referenced by cms_RecipientInfo_kari_encrypt().
CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ALG
#define CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ALG 175
Definition at line 390 of file cms.h.
Referenced by CMS_RecipientInfo_kari_get0_alg().
CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ORIG_ID
#define CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ORIG_ID 173
Definition at line 391 of file cms.h.
Referenced by CMS_RecipientInfo_kari_get0_orig_id().
CMS_F_CMS_RECIPIENTINFO_KARI_GET0_REKS
#define CMS_F_CMS_RECIPIENTINFO_KARI_GET0_REKS 172
Definition at line 392 of file cms.h.
Referenced by CMS_RecipientInfo_kari_get0_reks().
CMS_F_CMS_RECIPIENTINFO_KARI_ORIG_ID_CMP
#define CMS_F_CMS_RECIPIENTINFO_KARI_ORIG_ID_CMP 174
Definition at line 393 of file cms.h.
CMS_F_CMS_RECIPIENTINFO_KEKRI_DECRYPT
#define CMS_F_CMS_RECIPIENTINFO_KEKRI_DECRYPT 135
Definition at line 394 of file cms.h.
CMS_F_CMS_RECIPIENTINFO_KEKRI_ENCRYPT
#define CMS_F_CMS_RECIPIENTINFO_KEKRI_ENCRYPT 136
Definition at line 395 of file cms.h.
CMS_F_CMS_RECIPIENTINFO_KEKRI_GET0_ID
#define CMS_F_CMS_RECIPIENTINFO_KEKRI_GET0_ID 137
Definition at line 396 of file cms.h.
Referenced by CMS_RecipientInfo_kekri_get0_id().
CMS_F_CMS_RECIPIENTINFO_KEKRI_ID_CMP
#define CMS_F_CMS_RECIPIENTINFO_KEKRI_ID_CMP 138
Definition at line 397 of file cms.h.
Referenced by CMS_RecipientInfo_kekri_id_cmp().
CMS_F_CMS_RECIPIENTINFO_KTRI_CERT_CMP
#define CMS_F_CMS_RECIPIENTINFO_KTRI_CERT_CMP 139
Definition at line 398 of file cms.h.
CMS_F_CMS_RECIPIENTINFO_KTRI_DECRYPT
#define CMS_F_CMS_RECIPIENTINFO_KTRI_DECRYPT 140
Definition at line 399 of file cms.h.
CMS_F_CMS_RECIPIENTINFO_KTRI_ENCRYPT
#define CMS_F_CMS_RECIPIENTINFO_KTRI_ENCRYPT 141
Definition at line 400 of file cms.h.
CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_ALGS
#define CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_ALGS 142
Definition at line 401 of file cms.h.
Referenced by CMS_RecipientInfo_ktri_get0_algs().
CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_SIGNER_ID
#define CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_SIGNER_ID 143
Definition at line 402 of file cms.h.
Referenced by CMS_RecipientInfo_ktri_get0_signer_id().
CMS_F_CMS_RECIPIENTINFO_PWRI_CRYPT
#define CMS_F_CMS_RECIPIENTINFO_PWRI_CRYPT 167
Definition at line 403 of file cms.h.
Referenced by cms_RecipientInfo_pwri_crypt().
CMS_F_CMS_RECIPIENTINFO_SET0_KEY
#define CMS_F_CMS_RECIPIENTINFO_SET0_KEY 144
Definition at line 404 of file cms.h.
Referenced by CMS_RecipientInfo_set0_key().
CMS_F_CMS_RECIPIENTINFO_SET0_PASSWORD
#define CMS_F_CMS_RECIPIENTINFO_SET0_PASSWORD 168
Definition at line 405 of file cms.h.
Referenced by CMS_RecipientInfo_set0_password().
CMS_F_CMS_RECIPIENTINFO_SET0_PKEY
#define CMS_F_CMS_RECIPIENTINFO_SET0_PKEY 145
Definition at line 406 of file cms.h.
Referenced by CMS_RecipientInfo_set0_pkey().
CMS_F_CMS_SD_ASN1_CTRL
#define CMS_F_CMS_SD_ASN1_CTRL 170
Definition at line 407 of file cms.h.
CMS_F_CMS_SET1_IAS
#define CMS_F_CMS_SET1_IAS 176
Definition at line 408 of file cms.h.
CMS_F_CMS_SET1_KEYID
#define CMS_F_CMS_SET1_KEYID 177
Definition at line 409 of file cms.h.
CMS_F_CMS_SET1_SIGNERIDENTIFIER
#define CMS_F_CMS_SET1_SIGNERIDENTIFIER 146
Definition at line 410 of file cms.h.
CMS_F_CMS_SET_DETACHED
#define CMS_F_CMS_SET_DETACHED 147
Definition at line 411 of file cms.h.
Referenced by CMS_set_detached().
CMS_F_CMS_SIGN
#define CMS_F_CMS_SIGN 148
Definition at line 412 of file cms.h.
Referenced by CMS_sign().
CMS_F_CMS_SIGN_RECEIPT
#define CMS_F_CMS_SIGN_RECEIPT 163
Definition at line 419 of file cms.h.
Referenced by CMS_sign_receipt().
CMS_F_CMS_SIGNED_DATA_INIT
#define CMS_F_CMS_SIGNED_DATA_INIT 149
Definition at line 413 of file cms.h.
CMS_F_CMS_SIGNERINFO_CONTENT_SIGN
#define CMS_F_CMS_SIGNERINFO_CONTENT_SIGN 150
Definition at line 414 of file cms.h.
CMS_F_CMS_SIGNERINFO_SIGN
#define CMS_F_CMS_SIGNERINFO_SIGN 151
Definition at line 415 of file cms.h.
CMS_F_CMS_SIGNERINFO_VERIFY
#define CMS_F_CMS_SIGNERINFO_VERIFY 152
Definition at line 416 of file cms.h.
CMS_F_CMS_SIGNERINFO_VERIFY_CERT
#define CMS_F_CMS_SIGNERINFO_VERIFY_CERT 153
Definition at line 417 of file cms.h.
CMS_F_CMS_SIGNERINFO_VERIFY_CONTENT
#define CMS_F_CMS_SIGNERINFO_VERIFY_CONTENT 154
Definition at line 418 of file cms.h.
Referenced by CMS_SignerInfo_verify_content().
CMS_F_CMS_STREAM
#define CMS_F_CMS_STREAM 155
Definition at line 420 of file cms.h.
Referenced by CMS_stream().
CMS_F_CMS_UNCOMPRESS
#define CMS_F_CMS_UNCOMPRESS 156
Definition at line 421 of file cms.h.
Referenced by CMS_uncompress().
CMS_F_CMS_VERIFY
#define CMS_F_CMS_VERIFY 157
Definition at line 422 of file cms.h.
CMS_KEY_PARAM
#define CMS_KEY_PARAM 0x40000
Definition at line 73 of file cms.h.
CMS_NO_ATTR_VERIFY
#define CMS_NO_ATTR_VERIFY 0x8
Definition at line 55 of file cms.h.
CMS_NO_CONTENT_VERIFY
#define CMS_NO_CONTENT_VERIFY 0x4
Definition at line 54 of file cms.h.
CMS_NO_SIGNER_CERT_VERIFY
#define CMS_NO_SIGNER_CERT_VERIFY 0x20
Definition at line 59 of file cms.h.
CMS_NOATTR
#define CMS_NOATTR 0x100
Definition at line 63 of file cms.h.
CMS_NOCERTS
#define CMS_NOCERTS 0x2
Definition at line 53 of file cms.h.
CMS_NOCRL
#define CMS_NOCRL 0x2000
Definition at line 68 of file cms.h.
CMS_NOINTERN
#define CMS_NOINTERN 0x10
Definition at line 58 of file cms.h.
CMS_NOOLDMIMETYPE
#define CMS_NOOLDMIMETYPE 0x400
Definition at line 65 of file cms.h.
CMS_NOSIGS
#define CMS_NOSIGS (CMS_NO_CONTENT_VERIFY|CMS_NO_ATTR_VERIFY)
Definition at line 56 of file cms.h.
CMS_NOSMIMECAP
#define CMS_NOSMIMECAP 0x200
Definition at line 64 of file cms.h.
CMS_NOVERIFY
#define CMS_NOVERIFY 0x20
Definition at line 60 of file cms.h.
CMS_PARTIAL
#define CMS_PARTIAL 0x4000
Definition at line 69 of file cms.h.
Referenced by CMS_sign(), and CMS_sign_receipt().
CMS_R_ADD_SIGNER_ERROR
#define CMS_R_ADD_SIGNER_ERROR 99
Definition at line 425 of file cms.h.
Referenced by CMS_sign(), and CMS_sign_receipt().
CMS_R_CERTIFICATE_ALREADY_PRESENT
#define CMS_R_CERTIFICATE_ALREADY_PRESENT 175
Definition at line 426 of file cms.h.
CMS_R_CERTIFICATE_HAS_NO_KEYID
#define CMS_R_CERTIFICATE_HAS_NO_KEYID 160
Definition at line 427 of file cms.h.
CMS_R_CERTIFICATE_VERIFY_ERROR
#define CMS_R_CERTIFICATE_VERIFY_ERROR 100
Definition at line 428 of file cms.h.
CMS_R_CIPHER_INITIALISATION_ERROR
#define CMS_R_CIPHER_INITIALISATION_ERROR 101
Definition at line 429 of file cms.h.
CMS_R_CIPHER_PARAMETER_INITIALISATION_ERROR
#define CMS_R_CIPHER_PARAMETER_INITIALISATION_ERROR 102
Definition at line 430 of file cms.h.
Referenced by cms_RecipientInfo_pwri_crypt().
CMS_R_CMS_DATAFINAL_ERROR
#define CMS_R_CMS_DATAFINAL_ERROR 103
Definition at line 431 of file cms.h.
CMS_R_CMS_LIB
#define CMS_R_CMS_LIB 104
Definition at line 432 of file cms.h.
CMS_R_CONTENT_NOT_FOUND
#define CMS_R_CONTENT_NOT_FOUND 105
Definition at line 434 of file cms.h.
Referenced by CMS_dataFinal().
CMS_R_CONTENT_TYPE_MISMATCH
#define CMS_R_CONTENT_TYPE_MISMATCH 171
Definition at line 435 of file cms.h.
CMS_R_CONTENT_TYPE_NOT_COMPRESSED_DATA
#define CMS_R_CONTENT_TYPE_NOT_COMPRESSED_DATA 106
Definition at line 436 of file cms.h.
CMS_R_CONTENT_TYPE_NOT_ENVELOPED_DATA
#define CMS_R_CONTENT_TYPE_NOT_ENVELOPED_DATA 107
Definition at line 437 of file cms.h.
Referenced by cms_get0_enveloped().
CMS_R_CONTENT_TYPE_NOT_SIGNED_DATA
#define CMS_R_CONTENT_TYPE_NOT_SIGNED_DATA 108
Definition at line 438 of file cms.h.
CMS_R_CONTENT_VERIFY_ERROR
#define CMS_R_CONTENT_VERIFY_ERROR 109
Definition at line 439 of file cms.h.
CMS_R_CONTENTIDENTIFIER_MISMATCH
#define CMS_R_CONTENTIDENTIFIER_MISMATCH 170
Definition at line 433 of file cms.h.
CMS_R_CTRL_ERROR
#define CMS_R_CTRL_ERROR 110
Definition at line 440 of file cms.h.
CMS_R_CTRL_FAILURE
#define CMS_R_CTRL_FAILURE 111
Definition at line 441 of file cms.h.
CMS_R_DECRYPT_ERROR
#define CMS_R_DECRYPT_ERROR 112
Definition at line 442 of file cms.h.
Referenced by CMS_decrypt_set1_key().
CMS_R_ERROR_GETTING_PUBLIC_KEY
#define CMS_R_ERROR_GETTING_PUBLIC_KEY 113
Definition at line 443 of file cms.h.
Referenced by CMS_add1_recipient_cert().
CMS_R_ERROR_READING_MESSAGEDIGEST_ATTRIBUTE
#define CMS_R_ERROR_READING_MESSAGEDIGEST_ATTRIBUTE 114
Definition at line 444 of file cms.h.
Referenced by CMS_SignerInfo_verify_content().
CMS_R_ERROR_SETTING_KEY
#define CMS_R_ERROR_SETTING_KEY 115
Definition at line 445 of file cms.h.
CMS_R_ERROR_SETTING_RECIPIENTINFO
#define CMS_R_ERROR_SETTING_RECIPIENTINFO 116
Definition at line 446 of file cms.h.
CMS_R_INVALID_ENCRYPTED_KEY_LENGTH
#define CMS_R_INVALID_ENCRYPTED_KEY_LENGTH 117
Definition at line 447 of file cms.h.
CMS_R_INVALID_KEY_ENCRYPTION_PARAMETER
#define CMS_R_INVALID_KEY_ENCRYPTION_PARAMETER 176
Definition at line 448 of file cms.h.
Referenced by cms_RecipientInfo_pwri_crypt().
CMS_R_INVALID_KEY_LENGTH
#define CMS_R_INVALID_KEY_LENGTH 118
Definition at line 449 of file cms.h.
Referenced by CMS_add0_recipient_key().
CMS_R_MD_BIO_INIT_ERROR
#define CMS_R_MD_BIO_INIT_ERROR 119
Definition at line 450 of file cms.h.
Referenced by cms_DigestAlgorithm_init_bio().
CMS_R_MESSAGEDIGEST_ATTRIBUTE_WRONG_LENGTH
#define CMS_R_MESSAGEDIGEST_ATTRIBUTE_WRONG_LENGTH 120
Definition at line 451 of file cms.h.
Referenced by CMS_SignerInfo_verify_content().
CMS_R_MESSAGEDIGEST_WRONG_LENGTH
#define CMS_R_MESSAGEDIGEST_WRONG_LENGTH 121
Definition at line 452 of file cms.h.
CMS_R_MSGSIGDIGEST_ERROR
#define CMS_R_MSGSIGDIGEST_ERROR 172
Definition at line 453 of file cms.h.
CMS_R_MSGSIGDIGEST_VERIFICATION_FAILURE
#define CMS_R_MSGSIGDIGEST_VERIFICATION_FAILURE 162
Definition at line 454 of file cms.h.
CMS_R_MSGSIGDIGEST_WRONG_LENGTH
#define CMS_R_MSGSIGDIGEST_WRONG_LENGTH 163
Definition at line 455 of file cms.h.
CMS_R_NEED_ONE_SIGNER
#define CMS_R_NEED_ONE_SIGNER 164
Definition at line 456 of file cms.h.
Referenced by cms_Receipt_verify().
CMS_R_NO_CIPHER
#define CMS_R_NO_CIPHER 126
Definition at line 464 of file cms.h.
CMS_R_NO_CONTENT
#define CMS_R_NO_CONTENT 127
Definition at line 465 of file cms.h.
Referenced by CMS_dataInit(), and cms_Receipt_verify().
CMS_R_NO_CONTENT_TYPE
#define CMS_R_NO_CONTENT_TYPE 173
Definition at line 466 of file cms.h.
Referenced by cms_encode_Receipt().
CMS_R_NO_DEFAULT_DIGEST
#define CMS_R_NO_DEFAULT_DIGEST 128
Definition at line 467 of file cms.h.
CMS_R_NO_DIGEST_SET
#define CMS_R_NO_DIGEST_SET 129
Definition at line 468 of file cms.h.
CMS_R_NO_KEY
#define CMS_R_NO_KEY 130
Definition at line 469 of file cms.h.
Referenced by CMS_EncryptedData_set1_key().
CMS_R_NO_KEY_OR_CERT
#define CMS_R_NO_KEY_OR_CERT 174
Definition at line 470 of file cms.h.
Referenced by CMS_sign_receipt().
CMS_R_NO_MATCHING_DIGEST
#define CMS_R_NO_MATCHING_DIGEST 131
Definition at line 471 of file cms.h.
Referenced by cms_DigestAlgorithm_find_ctx().
CMS_R_NO_MATCHING_RECIPIENT
#define CMS_R_NO_MATCHING_RECIPIENT 132
Definition at line 472 of file cms.h.
Referenced by CMS_decrypt_set1_key(), and CMS_decrypt_set1_password().
CMS_R_NO_MATCHING_SIGNATURE
#define CMS_R_NO_MATCHING_SIGNATURE 166
Definition at line 473 of file cms.h.
Referenced by cms_Receipt_verify().
CMS_R_NO_MSGSIGDIGEST
#define CMS_R_NO_MSGSIGDIGEST 167
Definition at line 474 of file cms.h.
Referenced by cms_Receipt_verify().
CMS_R_NO_PASSWORD
#define CMS_R_NO_PASSWORD 178
Definition at line 475 of file cms.h.
Referenced by cms_RecipientInfo_pwri_crypt().
CMS_R_NO_PRIVATE_KEY
#define CMS_R_NO_PRIVATE_KEY 133
Definition at line 476 of file cms.h.
CMS_R_NO_PUBLIC_KEY
#define CMS_R_NO_PUBLIC_KEY 134
Definition at line 477 of file cms.h.
CMS_R_NO_RECEIPT_REQUEST
#define CMS_R_NO_RECEIPT_REQUEST 168
Definition at line 478 of file cms.h.
Referenced by cms_encode_Receipt().
CMS_R_NO_SIGNERS
#define CMS_R_NO_SIGNERS 135
Definition at line 479 of file cms.h.
CMS_R_NOT_A_SIGNED_RECEIPT
#define CMS_R_NOT_A_SIGNED_RECEIPT 165
Definition at line 457 of file cms.h.
Referenced by cms_Receipt_verify().
CMS_R_NOT_ENCRYPTED_DATA
#define CMS_R_NOT_ENCRYPTED_DATA 122
Definition at line 458 of file cms.h.
Referenced by CMS_EncryptedData_set1_key().
CMS_R_NOT_KEK
#define CMS_R_NOT_KEK 123
Definition at line 459 of file cms.h.
Referenced by CMS_RecipientInfo_kekri_get0_id(), CMS_RecipientInfo_kekri_id_cmp(), and CMS_RecipientInfo_set0_key().
CMS_R_NOT_KEY_AGREEMENT
#define CMS_R_NOT_KEY_AGREEMENT 181
Definition at line 460 of file cms.h.
Referenced by cms_RecipientInfo_kari_encrypt(), CMS_RecipientInfo_kari_get0_alg(), CMS_RecipientInfo_kari_get0_orig_id(), and CMS_RecipientInfo_kari_get0_reks().
CMS_R_NOT_KEY_TRANSPORT
#define CMS_R_NOT_KEY_TRANSPORT 124
Definition at line 461 of file cms.h.
Referenced by CMS_RecipientInfo_ktri_get0_algs(), CMS_RecipientInfo_ktri_get0_signer_id(), and CMS_RecipientInfo_set0_pkey().
CMS_R_NOT_PWRI
#define CMS_R_NOT_PWRI 177
Definition at line 462 of file cms.h.
Referenced by CMS_RecipientInfo_set0_password().
CMS_R_NOT_SUPPORTED_FOR_THIS_KEY_TYPE
#define CMS_R_NOT_SUPPORTED_FOR_THIS_KEY_TYPE 125
Definition at line 463 of file cms.h.
CMS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE
#define CMS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE 136
Definition at line 480 of file cms.h.
CMS_R_RECEIPT_DECODE_ERROR
#define CMS_R_RECEIPT_DECODE_ERROR 169
Definition at line 481 of file cms.h.
Referenced by cms_Receipt_verify().
CMS_R_RECIPIENT_ERROR
#define CMS_R_RECIPIENT_ERROR 137
Definition at line 482 of file cms.h.
CMS_R_SIGNER_CERTIFICATE_NOT_FOUND
#define CMS_R_SIGNER_CERTIFICATE_NOT_FOUND 138
Definition at line 483 of file cms.h.
CMS_R_SIGNFINAL_ERROR
#define CMS_R_SIGNFINAL_ERROR 139
Definition at line 484 of file cms.h.
CMS_R_SMIME_TEXT_ERROR
#define CMS_R_SMIME_TEXT_ERROR 140
Definition at line 485 of file cms.h.
CMS_R_STORE_INIT_ERROR
#define CMS_R_STORE_INIT_ERROR 141
Definition at line 486 of file cms.h.
CMS_R_TYPE_NOT_COMPRESSED_DATA
#define CMS_R_TYPE_NOT_COMPRESSED_DATA 142
Definition at line 487 of file cms.h.
CMS_R_TYPE_NOT_DATA
#define CMS_R_TYPE_NOT_DATA 143
Definition at line 488 of file cms.h.
Referenced by CMS_data().
CMS_R_TYPE_NOT_DIGESTED_DATA
#define CMS_R_TYPE_NOT_DIGESTED_DATA 144
Definition at line 489 of file cms.h.
Referenced by CMS_digest_verify().
CMS_R_TYPE_NOT_ENCRYPTED_DATA
#define CMS_R_TYPE_NOT_ENCRYPTED_DATA 145
Definition at line 490 of file cms.h.
Referenced by CMS_EncryptedData_decrypt().
CMS_R_TYPE_NOT_ENVELOPED_DATA
#define CMS_R_TYPE_NOT_ENVELOPED_DATA 146
Definition at line 491 of file cms.h.
Referenced by CMS_decrypt().
CMS_R_UNABLE_TO_FINALIZE_CONTEXT
#define CMS_R_UNABLE_TO_FINALIZE_CONTEXT 147
Definition at line 492 of file cms.h.
Referenced by CMS_SignerInfo_verify_content().
CMS_R_UNKNOWN_CIPHER
#define CMS_R_UNKNOWN_CIPHER 148
Definition at line 493 of file cms.h.
Referenced by cms_RecipientInfo_pwri_crypt().
CMS_R_UNKNOWN_DIGEST_ALGORIHM
#define CMS_R_UNKNOWN_DIGEST_ALGORIHM 149
Definition at line 494 of file cms.h.
Referenced by cms_DigestAlgorithm_init_bio().
CMS_R_UNKNOWN_ID
#define CMS_R_UNKNOWN_ID 150
Definition at line 495 of file cms.h.
CMS_R_UNSUPPORTED_COMPRESSION_ALGORITHM
#define CMS_R_UNSUPPORTED_COMPRESSION_ALGORITHM 151
Definition at line 496 of file cms.h.
Referenced by CMS_compress(), and CMS_uncompress().
CMS_R_UNSUPPORTED_CONTENT_TYPE
#define CMS_R_UNSUPPORTED_CONTENT_TYPE 152
Definition at line 497 of file cms.h.
Referenced by cms_DigestAlgorithm_find_ctx(), and CMS_get0_content().
CMS_R_UNSUPPORTED_KEK_ALGORITHM
#define CMS_R_UNSUPPORTED_KEK_ALGORITHM 153
Definition at line 498 of file cms.h.
CMS_R_UNSUPPORTED_KEY_ENCRYPTION_ALGORITHM
#define CMS_R_UNSUPPORTED_KEY_ENCRYPTION_ALGORITHM 179
Definition at line 499 of file cms.h.
Referenced by cms_RecipientInfo_pwri_crypt().
CMS_R_UNSUPPORTED_RECIPIENT_TYPE
#define CMS_R_UNSUPPORTED_RECIPIENT_TYPE 154
Definition at line 500 of file cms.h.
CMS_R_UNSUPPORTED_RECPIENTINFO_TYPE
#define CMS_R_UNSUPPORTED_RECPIENTINFO_TYPE 155
Definition at line 501 of file cms.h.
CMS_R_UNSUPPORTED_TYPE
#define CMS_R_UNSUPPORTED_TYPE 156
Definition at line 502 of file cms.h.
Referenced by CMS_dataFinal(), and CMS_dataInit().
CMS_R_UNWRAP_ERROR
#define CMS_R_UNWRAP_ERROR 157
Definition at line 503 of file cms.h.
CMS_R_UNWRAP_FAILURE
#define CMS_R_UNWRAP_FAILURE 180
Definition at line 504 of file cms.h.
CMS_R_VERIFICATION_FAILURE
#define CMS_R_VERIFICATION_FAILURE 158
Definition at line 505 of file cms.h.
Referenced by CMS_SignerInfo_verify_content().
CMS_R_WRAP_ERROR
#define CMS_R_WRAP_ERROR 159
Definition at line 506 of file cms.h.
CMS_RECIPINFO_AGREE
#define CMS_RECIPINFO_AGREE 1
Definition at line 45 of file cms.h.
Referenced by cms_env_asn1_ctrl(), CMS_RecipientInfo_get0_pkey_ctx(), cms_RecipientInfo_kari_encrypt(), CMS_RecipientInfo_kari_get0_alg(), CMS_RecipientInfo_kari_get0_ctx(), CMS_RecipientInfo_kari_get0_orig_id(), CMS_RecipientInfo_kari_get0_reks(), and cms_RecipientInfo_kari_init().
CMS_RECIPINFO_KEK
#define CMS_RECIPINFO_KEK 2
Definition at line 46 of file cms.h.
Referenced by CMS_decrypt_set1_key(), CMS_RecipientInfo_kekri_get0_id(), CMS_RecipientInfo_kekri_id_cmp(), and CMS_RecipientInfo_set0_key().
CMS_RECIPINFO_NONE
#define CMS_RECIPINFO_NONE -1
Definition at line 43 of file cms.h.
CMS_RECIPINFO_OTHER
#define CMS_RECIPINFO_OTHER 4
Definition at line 48 of file cms.h.
CMS_RECIPINFO_PASS
#define CMS_RECIPINFO_PASS 3
Definition at line 47 of file cms.h.
Referenced by CMS_decrypt_set1_password(), and CMS_RecipientInfo_set0_password().
CMS_RECIPINFO_TRANS
#define CMS_RECIPINFO_TRANS 0
Definition at line 44 of file cms.h.
Referenced by CMS_add1_recipient_cert(), cms_env_asn1_ctrl(), cms_pkey_get_ri_type(), CMS_RecipientInfo_decrypt(), CMS_RecipientInfo_encrypt(), CMS_RecipientInfo_get0_pkey_ctx(), CMS_RecipientInfo_ktri_get0_algs(), CMS_RecipientInfo_ktri_get0_signer_id(), and CMS_RecipientInfo_set0_pkey().
CMS_REUSE_DIGEST
#define CMS_REUSE_DIGEST 0x8000
Definition at line 70 of file cms.h.
CMS_SIGNERINFO_ISSUER_SERIAL
#define CMS_SIGNERINFO_ISSUER_SERIAL 0
Definition at line 40 of file cms.h.
CMS_SIGNERINFO_KEYIDENTIFIER
#define CMS_SIGNERINFO_KEYIDENTIFIER 1
Definition at line 41 of file cms.h.
CMS_STREAM
#define CMS_STREAM 0x1000
Definition at line 67 of file cms.h.
Referenced by CMS_data_create(), CMS_sign(), and CMS_sign_receipt().
CMS_TEXT
#define CMS_TEXT 0x1
Definition at line 52 of file cms.h.
Referenced by CMS_sign_receipt(), and CMS_verify_receipt().
CMS_USE_KEYID
#define CMS_USE_KEYID 0x10000
Definition at line 71 of file cms.h.
Referenced by cms_RecipientInfo_kari_init().
Typedef Documentation
CMS_ReceiptRequest
typedef struct CMS_ReceiptRequest_st CMS_ReceiptRequest
Definition at line 27 of file cms.h.
Function Documentation
BIO_new_CMS()
BIO* BIO_new_CMS (BIO * out, CMS_ContentInfo * cms)
CMS_add0_cert()
int CMS_add0_cert (CMS_ContentInfo * cms, X509 * cert)
Definition at line 381 of file cms_lib.c.
CMS_add0_CertificateChoices()
CMS_CertificateChoices* CMS_add0_CertificateChoices (CMS_ContentInfo * cms)
Definition at line 360 of file cms_lib.c.
References M_ASN1_free_of, M_ASN1_new_of, NULL, and STACK_OF().
CMS_add0_crl()
int CMS_add0_crl (CMS_ContentInfo * cms, X509_CRL * crl)
Definition at line 458 of file cms_lib.c.
References CMS_add0_RevocationInfoChoice(), and CMS_REVCHOICE_CRL.
Referenced by CMS_add1_crl().
CMS_add0_recipient_key()
CMS_RecipientInfo* CMS_add0_recipient_key (CMS_ContentInfo * cms, int nid, unsigned char * key, size_t keylen, unsigned char * id, size_t idlen, ASN1_GENERALIZEDTIME * date, ASN1_OBJECT * otherTypeId, ASN1_TYPE * otherType)
Definition at line 461 of file cms_env.c.
References CMS_F_CMS_ADD0_RECIPIENT_KEY, cms_get0_enveloped(), CMS_R_INVALID_KEY_LENGTH, CMSerr, NID_id_aes128_wrap, NID_id_aes192_wrap, NID_id_aes256_wrap, NID_undef, and NULL.
CMS_add0_recipient_password()
CMS_RecipientInfo* CMS_add0_recipient_password (CMS_ContentInfo * cms, int iter, int wrap_nid, int pbe_nid, unsigned char * pass, ossl_ssize_t passlen, const EVP_CIPHER * kekciph)
Definition at line 38 of file cms_pwri.c.
References ctx, and NULL.
CMS_add0_RevocationInfoChoice()
CMS_RevocationInfoChoice* CMS_add0_RevocationInfoChoice (CMS_ContentInfo * cms)
Definition at line 437 of file cms_lib.c.
References M_ASN1_free_of, M_ASN1_new_of, NULL, and STACK_OF().
Referenced by CMS_add0_crl().
CMS_add1_cert()
int CMS_add1_cert (CMS_ContentInfo * cms, X509 * cert)
Definition at line 407 of file cms_lib.c.
Referenced by CMS_sign().
CMS_add1_crl()
int CMS_add1_crl (CMS_ContentInfo * cms, X509_CRL * crl)
Definition at line 469 of file cms_lib.c.
References CMS_add0_crl(), and X509_CRL_up_ref().
CMS_add1_recipient_cert()
CMS_RecipientInfo* CMS_add1_recipient_cert (CMS_ContentInfo * cms, X509 * recip, unsigned int flags)
Definition at line 178 of file cms_env.c.
References CMS_F_CMS_ADD1_RECIPIENT_CERT, cms_get0_enveloped(), cms_pkey_get_ri_type(), CMS_R_ERROR_GETTING_PUBLIC_KEY, CMS_RECIPINFO_TRANS, CMSerr, M_ASN1_new_of, NULL, and X509_get0_pubkey().
CMS_add1_signer()
CMS_SignerInfo* CMS_add1_signer (CMS_ContentInfo * cms, X509 * signer, EVP_PKEY * pk, const EVP_MD * md, unsigned int flags)
Definition at line 220 of file cms_sd.c.
Referenced by CMS_sign(), and CMS_sign_receipt().
CMS_add_simple_smimecap()
int CMS_add_simple_smimecap (STACK_OF(X509_ALGOR) ** algs, int algnid, int keysize)
Definition at line 865 of file cms_sd.c.
References ASN1_INTEGER_set(), key, NULL, OBJ_nid2obj(), V_ASN1_INTEGER, V_ASN1_UNDEF, and X509_ALGOR_set0().
CMS_add_smimecap()
int CMS_add_smimecap (CMS_SignerInfo * si, STACK_OF(X509_ALGOR) * algs)
Definition at line 852 of file cms_sd.c.
References CMS_signed_add1_attr_by_NID(), NID_SMIMECapabilities, NULL, OPENSSL_free, and V_ASN1_SEQUENCE.
CMS_add_standard_smimecap()
int CMS_add_standard_smimecap (STACK_OF(X509_ALGOR) ** smcap)
Definition at line 908 of file cms_sd.c.
CMS_compress()
CMS_ContentInfo* CMS_compress (BIO * in, int comp_nid, unsigned int flags)
Definition at line 838 of file cms_smime.c.
References CMS_F_CMS_COMPRESS, CMS_R_UNSUPPORTED_COMPRESSION_ALGORITHM, CMSerr, and NULL.
CMS_data()
int CMS_data (CMS_ContentInfo * cms, BIO * out, unsigned int flags)
Definition at line 102 of file cms_smime.c.
References CMS_dataInit(), CMS_F_CMS_DATA, CMS_get0_type(), CMS_R_TYPE_NOT_DATA, CMSerr, NID_pkcs7_data, NULL, and OBJ_obj2nid().
CMS_data_create()
CMS_ContentInfo* CMS_data_create (BIO * in, unsigned int flags)
Definition at line 118 of file cms_smime.c.
References cms_Data_create(), CMS_final(), CMS_STREAM, and NULL.
CMS_dataFinal()
int CMS_dataFinal (CMS_ContentInfo * cms, BIO * bio)
Definition at line 107 of file cms_lib.c.
References ASN1_STRING_FLAG_CONT, ASN1_STRING_set0(), BIO_find_type(), BIO_FLAGS_MEM_RDONLY, BIO_get_mem_data, BIO_set_flags(), BIO_set_mem_eof_return, BIO_TYPE_MEM, cms_DigestedData_do_final(), CMS_F_CMS_DATAFINAL, CMS_get0_content(), CMS_R_CONTENT_NOT_FOUND, CMS_R_UNSUPPORTED_TYPE, cms_SignedData_final(), CMSerr, NID_id_smime_ct_compressedData, NID_pkcs7_data, NID_pkcs7_digest, NID_pkcs7_encrypted, NID_pkcs7_enveloped, NID_pkcs7_signed, and OBJ_obj2nid().
CMS_dataInit()
BIO* CMS_dataInit (CMS_ContentInfo * cms, BIO * icont)
Definition at line 56 of file cms_lib.c.
References BIO_free(), BIO_push(), cms_CompressedData_init_bio(), cms_content_bio(), cms_DigestedData_init_bio(), cms_EncryptedData_init_bio(), cms_EnvelopedData_init_bio(), CMS_F_CMS_DATAINIT, CMS_R_NO_CONTENT, CMS_R_UNSUPPORTED_TYPE, cms_SignedData_init_bio(), CMSerr, NID_id_smime_ct_compressedData, NID_pkcs7_data, NID_pkcs7_digest, NID_pkcs7_encrypted, NID_pkcs7_enveloped, NID_pkcs7_signed, NULL, and OBJ_obj2nid().
Referenced by CMS_data().
CMS_decrypt()
int CMS_decrypt (CMS_ContentInfo * cms, EVP_PKEY * pkey, X509 * cert, BIO * dcont, BIO * out, unsigned int flags)
Definition at line 732 of file cms_smime.c.
References CMS_F_CMS_DECRYPT, CMS_get0_type(), CMS_R_TYPE_NOT_ENVELOPED_DATA, CMSerr, NID_pkcs7_enveloped, and OBJ_obj2nid().
CMS_decrypt_set1_key()
int CMS_decrypt_set1_key (CMS_ContentInfo * cms, unsigned char * key, size_t keylen, const unsigned char * id, size_t idlen)
Definition at line 673 of file cms_smime.c.
References CMS_F_CMS_DECRYPT_SET1_KEY, CMS_R_DECRYPT_ERROR, CMS_R_NO_MATCHING_RECIPIENT, CMS_RecipientInfo_decrypt(), CMS_RecipientInfo_kekri_id_cmp(), CMS_RecipientInfo_set0_key(), CMS_RecipientInfo_type(), CMS_RECIPINFO_KEK, CMSerr, ERR_clear_error(), NULL, and STACK_OF.
CMS_decrypt_set1_password()
int CMS_decrypt_set1_password (CMS_ContentInfo * cms, unsigned char * pass, ossl_ssize_t passlen)
Definition at line 709 of file cms_smime.c.
References CMS_F_CMS_DECRYPT_SET1_PASSWORD, CMS_R_NO_MATCHING_RECIPIENT, CMS_RecipientInfo_decrypt(), CMS_RecipientInfo_set0_password(), CMS_RecipientInfo_type(), CMS_RECIPINFO_PASS, CMSerr, NULL, and STACK_OF.
CMS_decrypt_set1_pkey()
int CMS_decrypt_set1_pkey (CMS_ContentInfo * cms, EVP_PKEY * pk, X509 * cert)
Definition at line 603 of file cms_smime.c.
References STACK_OF.
CMS_digest_create()
CMS_ContentInfo* CMS_digest_create (BIO * in, const EVP_MD * md, unsigned int flags)
Definition at line 156 of file cms_smime.c.
CMS_digest_verify()
int CMS_digest_verify (CMS_ContentInfo * cms, BIO * dcont, BIO * out, unsigned int flags)
Definition at line 133 of file cms_smime.c.
References CMS_F_CMS_DIGEST_VERIFY, CMS_get0_type(), CMS_R_TYPE_NOT_DIGESTED_DATA, CMSerr, NID_pkcs7_digest, and OBJ_obj2nid().
CMS_encrypt()
CMS_ContentInfo* CMS_encrypt (STACK_OF(X509) * certs, BIO * in, const EVP_CIPHER * cipher, unsigned int flags)
Definition at line 546 of file cms_smime.c.
CMS_EncryptedData_decrypt()
int CMS_EncryptedData_decrypt (CMS_ContentInfo * cms, const unsigned char * key, size_t keylen, BIO * dcont, BIO * out, unsigned int flags)
Definition at line 176 of file cms_smime.c.
References CMS_F_CMS_ENCRYPTEDDATA_DECRYPT, CMS_get0_type(), CMS_R_TYPE_NOT_ENCRYPTED_DATA, CMSerr, NID_pkcs7_encrypted, and OBJ_obj2nid().
CMS_EncryptedData_encrypt()
CMS_ContentInfo* CMS_EncryptedData_encrypt (BIO * in, const EVP_CIPHER * cipher, const unsigned char * key, size_t keylen, unsigned int flags)
Definition at line 201 of file cms_smime.c.
CMS_EncryptedData_set1_key()
int CMS_EncryptedData_set1_key (CMS_ContentInfo * cms, const EVP_CIPHER * ciph, const unsigned char * key, size_t keylen)
Definition at line 182 of file cms_enc.c.
References cms_EncryptedContent_init(), CMS_F_CMS_ENCRYPTEDDATA_SET1_KEY, CMS_R_NO_KEY, CMS_R_NOT_ENCRYPTED_DATA, CMSerr, ERR_R_MALLOC_FAILURE, M_ASN1_new_of, NID_pkcs7_encrypted, OBJ_nid2obj(), and OBJ_obj2nid().
CMS_EnvelopedData_create()
CMS_ContentInfo* CMS_EnvelopedData_create (const EVP_CIPHER * cipher)
Definition at line 104 of file cms_env.c.
CMS_final()
int CMS_final (CMS_ContentInfo * cms, BIO * data, BIO * dcont, unsigned int flags)
Definition at line 759 of file cms_smime.c.
Referenced by CMS_data_create(), CMS_sign(), and CMS_sign_receipt().
CMS_get0_content()
ASN1_OCTET_STRING** CMS_get0_content (CMS_ContentInfo * cms)
Definition at line 156 of file cms_lib.c.
References CMS_F_CMS_GET0_CONTENT, CMS_R_UNSUPPORTED_CONTENT_TYPE, CMSerr, NID_id_smime_ct_authData, NID_id_smime_ct_compressedData, NID_pkcs7_data, NID_pkcs7_digest, NID_pkcs7_encrypted, NID_pkcs7_enveloped, NID_pkcs7_signed, NULL, OBJ_obj2nid(), and V_ASN1_OCTET_STRING.
Referenced by cms_content_bio(), CMS_dataFinal(), CMS_is_detached(), cms_Receipt_verify(), CMS_set_detached(), CMS_sign_receipt(), and CMS_stream().
CMS_get0_eContentType()
const ASN1_OBJECT* CMS_get0_eContentType (CMS_ContentInfo * cms)
Definition at line 224 of file cms_lib.c.
Referenced by cms_Receipt_verify(), and SMIME_write_CMS().
CMS_get0_type()
const ASN1_OBJECT* CMS_get0_type (const CMS_ContentInfo * cms)
Definition at line 22 of file cms_lib.c.
Referenced by CMS_data(), CMS_decrypt(), CMS_digest_verify(), and CMS_EncryptedData_decrypt().
CMS_is_detached()
int CMS_is_detached (CMS_ContentInfo * cms)
Definition at line 249 of file cms_lib.c.
References CMS_get0_content().
CMS_RecipientEncryptedKey_cert_cmp()
int CMS_RecipientEncryptedKey_cert_cmp (CMS_RecipientEncryptedKey * rek, X509 * cert)
Definition at line 143 of file cms_kari.c.
CMS_RecipientEncryptedKey_get0_id()
int CMS_RecipientEncryptedKey_get0_id (CMS_RecipientEncryptedKey * rek, ASN1_OCTET_STRING ** keyid, ASN1_GENERALIZEDTIME ** tm, CMS_OtherKeyAttribute ** other, X509_NAME ** issuer, ASN1_INTEGER ** sno)
Definition at line 109 of file cms_kari.c.
References CMS_REK_ISSUER_SERIAL, CMS_REK_KEYIDENTIFIER, and NULL.
CMS_RecipientInfo_decrypt()
int CMS_RecipientInfo_decrypt (CMS_ContentInfo * cms, CMS_RecipientInfo * ri)
Definition at line 738 of file cms_env.c.
References CMS_RECIPINFO_TRANS.
Referenced by CMS_decrypt_set1_key(), and CMS_decrypt_set1_password().
CMS_RecipientInfo_encrypt()
int CMS_RecipientInfo_encrypt (CMS_ContentInfo * cms, CMS_RecipientInfo * ri)
Definition at line 757 of file cms_env.c.
References CMS_RECIPINFO_TRANS.
CMS_RecipientInfo_get0_pkey_ctx()
EVP_PKEY_CTX* CMS_RecipientInfo_get0_pkey_ctx (CMS_RecipientInfo * ri)
Definition at line 95 of file cms_env.c.
References CMS_RECIPINFO_AGREE, CMS_RECIPINFO_TRANS, and NULL.
CMS_RecipientInfo_kari_decrypt()
int CMS_RecipientInfo_kari_decrypt (CMS_ContentInfo * cms, CMS_RecipientInfo * ri, CMS_RecipientEncryptedKey * rek)
Definition at line 228 of file cms_kari.c.
References cms_env_asn1_ctrl(), and NULL.
CMS_RecipientInfo_kari_get0_alg()
int CMS_RecipientInfo_kari_get0_alg (CMS_RecipientInfo * ri, X509_ALGOR ** palg, ASN1_OCTET_STRING ** pukm)
Definition at line 22 of file cms_kari.c.
References CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ALG, CMS_R_NOT_KEY_AGREEMENT, CMS_RECIPINFO_AGREE, CMSerr, and STACK_OF.
CMS_RecipientInfo_kari_get0_ctx()
EVP_CIPHER_CTX* CMS_RecipientInfo_kari_get0_ctx (CMS_RecipientInfo * ri)
Definition at line 174 of file cms_kari.c.
References CMS_RECIPINFO_AGREE, and NULL.
CMS_RecipientInfo_kari_get0_orig_id()
int CMS_RecipientInfo_kari_get0_orig_id (CMS_RecipientInfo * ri, X509_ALGOR ** pubalg, ASN1_BIT_STRING ** pubkey, ASN1_OCTET_STRING ** keyid, X509_NAME ** issuer, ASN1_INTEGER ** sno)
Definition at line 51 of file cms_kari.c.
References CMS_F_CMS_RECIPIENTINFO_KARI_GET0_ORIG_ID, CMS_OIK_ISSUER_SERIAL, CMS_OIK_KEYIDENTIFIER, CMS_OIK_PUBKEY, CMS_R_NOT_KEY_AGREEMENT, CMS_RECIPINFO_AGREE, CMSerr, and NULL.
CMS_RecipientInfo_kari_get0_reks()
* CMS_RecipientInfo_kari_get0_reks (CMS_RecipientInfo * ri)
Definition at line 41 of file cms_kari.c.
References CMS_F_CMS_RECIPIENTINFO_KARI_GET0_REKS, CMS_R_NOT_KEY_AGREEMENT, CMS_RECIPINFO_AGREE, CMSerr, and NULL.
CMS_RecipientInfo_kari_orig_id_cmp()
int CMS_RecipientInfo_kari_orig_id_cmp (CMS_RecipientInfo * ri, X509 * cert)
Definition at line 93 of file cms_kari.c.
CMS_RecipientInfo_kari_set0_pkey()
int CMS_RecipientInfo_kari_set0_pkey (CMS_RecipientInfo * ri, EVP_PKEY * pk)
Definition at line 155 of file cms_kari.c.
CMS_RecipientInfo_kekri_get0_id()
int CMS_RecipientInfo_kekri_get0_id (CMS_RecipientInfo * ri, X509_ALGOR ** palg, ASN1_OCTET_STRING ** pid, ASN1_GENERALIZEDTIME ** pdate, ASN1_OBJECT ** potherid, ASN1_TYPE ** pothertype)
Definition at line 561 of file cms_env.c.
References CMS_F_CMS_RECIPIENTINFO_KEKRI_GET0_ID, CMS_R_NOT_KEK, CMS_RECIPINFO_KEK, CMSerr, and NULL.
CMS_RecipientInfo_kekri_id_cmp()
int CMS_RecipientInfo_kekri_id_cmp (CMS_RecipientInfo * ri, const unsigned char * id, size_t idlen)
Definition at line 425 of file cms_env.c.
References ASN1_OCTET_STRING_cmp(), CMS_F_CMS_RECIPIENTINFO_KEKRI_ID_CMP, CMS_R_NOT_KEK, CMS_RECIPINFO_KEK, CMSerr, and V_ASN1_OCTET_STRING.
Referenced by CMS_decrypt_set1_key().
CMS_RecipientInfo_ktri_cert_cmp()
int CMS_RecipientInfo_ktri_cert_cmp (CMS_RecipientInfo * ri, X509 * cert)
Definition at line 269 of file cms_env.c.
CMS_RecipientInfo_ktri_get0_algs()
int CMS_RecipientInfo_ktri_get0_algs (CMS_RecipientInfo * ri, EVP_PKEY ** pk, X509 ** recip, X509_ALGOR ** palg)
Definition at line 231 of file cms_env.c.
References CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_ALGS, CMS_R_NOT_KEY_TRANSPORT, CMS_RECIPINFO_TRANS, and CMSerr.
CMS_RecipientInfo_ktri_get0_signer_id()
int CMS_RecipientInfo_ktri_get0_signer_id (CMS_RecipientInfo * ri, ASN1_OCTET_STRING ** keyid, X509_NAME ** issuer, ASN1_INTEGER ** sno)
Definition at line 253 of file cms_env.c.
References CMS_F_CMS_RECIPIENTINFO_KTRI_GET0_SIGNER_ID, CMS_R_NOT_KEY_TRANSPORT, CMS_RECIPINFO_TRANS, cms_SignerIdentifier_get0_signer_id(), and CMSerr.
CMS_RecipientInfo_set0_key()
int CMS_RecipientInfo_set0_key (CMS_RecipientInfo * ri, unsigned char * key, size_t keylen)
Definition at line 595 of file cms_env.c.
References CMS_F_CMS_RECIPIENTINFO_SET0_KEY, CMS_R_NOT_KEK, CMS_RECIPINFO_KEK, CMSerr, and key.
Referenced by CMS_decrypt_set1_key().
CMS_RecipientInfo_set0_password()
int CMS_RecipientInfo_set0_password (CMS_RecipientInfo * ri, unsigned char * pass, ossl_ssize_t passlen)
Definition at line 21 of file cms_pwri.c.
References CMS_F_CMS_RECIPIENTINFO_SET0_PASSWORD, CMS_R_NOT_PWRI, CMS_RECIPINFO_PASS, CMSerr, pass, and passlen.
Referenced by CMS_decrypt_set1_password().
CMS_RecipientInfo_set0_pkey()
int CMS_RecipientInfo_set0_pkey (CMS_RecipientInfo * ri, EVP_PKEY * pkey)
Definition at line 279 of file cms_env.c.
References CMS_F_CMS_RECIPIENTINFO_SET0_PKEY, CMS_R_NOT_KEY_TRANSPORT, CMS_RECIPINFO_TRANS, and CMSerr.
CMS_RecipientInfo_type()
int CMS_RecipientInfo_type (CMS_RecipientInfo * ri)
Definition at line 90 of file cms_env.c.
Referenced by CMS_decrypt_set1_key(), and CMS_decrypt_set1_password().
CMS_set1_eContentType()
int CMS_set1_eContentType (CMS_ContentInfo * cms, const ASN1_OBJECT * oid)
Definition at line 233 of file cms_lib.c.
Referenced by CMS_sign(), and CMS_sign_receipt().
CMS_set1_signers_certs()
int CMS_set1_signers_certs (CMS_ContentInfo * cms, STACK_OF(X509) * certs, unsigned int flags)
Definition at line 468 of file cms_sd.c.
References STACK_OF().
CMS_set_detached()
int CMS_set_detached (CMS_ContentInfo * cms, int detached)
Definition at line 260 of file cms_lib.c.
References ASN1_STRING_FLAG_CONT, CMS_F_CMS_SET_DETACHED, CMS_get0_content(), CMSerr, ERR_R_MALLOC_FAILURE, and NULL.
Referenced by cms_Data_create(), and CMS_sign().
CMS_SharedInfo_encode()
int CMS_SharedInfo_encode (unsigned char ** pder, X509_ALGOR * kekalg, ASN1_OCTET_STRING * ukm, int keylen)
CMS_sign()
CMS_ContentInfo* CMS_sign (X509 * signcert, EVP_PKEY * pkey, STACK_OF(X509) * certs, BIO * data, unsigned int flags)
Definition at line 435 of file cms_smime.c.
References CMS_add1_cert(), CMS_add1_signer(), CMS_ASCIICRLF, CMS_DETACHED, CMS_F_CMS_SIGN, CMS_final(), CMS_PARTIAL, CMS_R_ADD_SIGNER_ERROR, CMS_set1_eContentType(), CMS_set_detached(), CMS_SignedData_init(), CMS_STREAM, CMSerr, ERR_R_MALLOC_FAILURE, NID_id_ct_asciiTextWithCRLF, NULL, and OBJ_nid2obj().
Referenced by CMS_sign_receipt().
CMS_sign_receipt()
CMS_ContentInfo* CMS_sign_receipt (CMS_SignerInfo * si, X509 * signcert, EVP_PKEY * pkey, STACK_OF(X509) * certs, unsigned int flags)
Definition at line 478 of file cms_smime.c.
References BIO_free(), BIO_new_mem_buf(), CMS_add1_signer(), CMS_BINARY, CMS_DETACHED, cms_encode_Receipt(), CMS_F_CMS_SIGN_RECEIPT, CMS_final(), CMS_get0_content(), cms_msgSigDigest_add1(), CMS_PARTIAL, CMS_R_ADD_SIGNER_ERROR, CMS_R_NO_KEY_OR_CERT, CMS_set1_eContentType(), CMS_sign(), CMS_STREAM, CMS_TEXT, CMSerr, NID_id_smime_ct_receipt, NULL, and OBJ_nid2obj().
CMS_signed_add1_attr()
int CMS_signed_add1_attr (CMS_SignerInfo * si, X509_ATTRIBUTE * attr)
Definition at line 45 of file cms_att.c.
CMS_signed_add1_attr_by_NID()
int CMS_signed_add1_attr_by_NID (CMS_SignerInfo * si, int nid, int type, const void * bytes, int len)
Definition at line 61 of file cms_att.c.
Referenced by CMS_add1_ReceiptRequest(), and CMS_add_smimecap().
CMS_signed_add1_attr_by_OBJ()
int CMS_signed_add1_attr_by_OBJ (CMS_SignerInfo * si, const ASN1_OBJECT * obj, int type, const void * bytes, int len)
Definition at line 52 of file cms_att.c.
CMS_signed_add1_attr_by_txt()
int CMS_signed_add1_attr_by_txt (CMS_SignerInfo * si, const char * attrname, int type, const void * bytes, int len)
Definition at line 69 of file cms_att.c.
CMS_signed_delete_attr()
X509_ATTRIBUTE* CMS_signed_delete_attr (CMS_SignerInfo * si, int loc)
Definition at line 40 of file cms_att.c.
References X509at_delete_attr().
CMS_signed_get0_data_by_OBJ()
void* CMS_signed_get0_data_by_OBJ (CMS_SignerInfo * si, const ASN1_OBJECT * oid, int lastpos, int type)
Definition at line 78 of file cms_att.c.
References X509at_get0_data_by_OBJ().
Referenced by cms_encode_Receipt(), CMS_get1_ReceiptRequest(), cms_Receipt_verify(), and CMS_SignerInfo_verify_content().
CMS_signed_get_attr()
X509_ATTRIBUTE* CMS_signed_get_attr (const CMS_SignerInfo * si, int loc)
Definition at line 35 of file cms_att.c.
References X509at_get_attr().
CMS_signed_get_attr_by_NID()
int CMS_signed_get_attr_by_NID (const CMS_SignerInfo * si, int nid, int lastpos)
Definition at line 24 of file cms_att.c.
References X509at_get_attr_by_NID().
CMS_signed_get_attr_by_OBJ()
int CMS_signed_get_attr_by_OBJ (const CMS_SignerInfo * si, const ASN1_OBJECT * obj, int lastpos)
Definition at line 29 of file cms_att.c.
References X509at_get_attr_by_OBJ().
CMS_signed_get_attr_count()
int CMS_signed_get_attr_count (const CMS_SignerInfo * si)
Definition at line 19 of file cms_att.c.
References X509at_get_attr_count().
Referenced by CMS_SignerInfo_verify_content().
CMS_SignedData_init()
int CMS_SignedData_init (CMS_ContentInfo * cms)
Definition at line 53 of file cms_sd.c.
Referenced by CMS_sign().
CMS_SignerInfo_cert_cmp()
int CMS_SignerInfo_cert_cmp (CMS_SignerInfo * si, X509 * cert)
Definition at line 463 of file cms_sd.c.
CMS_SignerInfo_get0_algs()
void CMS_SignerInfo_get0_algs (CMS_SignerInfo * si, EVP_PKEY ** pk, X509 ** signer, X509_ALGOR ** pdig, X509_ALGOR ** psig)
Definition at line 514 of file cms_sd.c.
CMS_SignerInfo_get0_md_ctx()
EVP_MD_CTX* CMS_SignerInfo_get0_md_ctx (CMS_SignerInfo * si)
Definition at line 407 of file cms_sd.c.
CMS_SignerInfo_get0_pkey_ctx()
EVP_PKEY_CTX* CMS_SignerInfo_get0_pkey_ctx (CMS_SignerInfo * si)
Definition at line 402 of file cms_sd.c.
CMS_SignerInfo_get0_signature()
ASN1_OCTET_STRING* CMS_SignerInfo_get0_signature (CMS_SignerInfo * si)
Definition at line 528 of file cms_sd.c.
CMS_SignerInfo_get0_signer_id()
int CMS_SignerInfo_get0_signer_id (CMS_SignerInfo * si, ASN1_OCTET_STRING ** keyid, X509_NAME ** issuer, ASN1_INTEGER ** sno)
Definition at line 456 of file cms_sd.c.
References cms_SignerIdentifier_get0_signer_id().
CMS_SignerInfo_set1_signer_cert()
void CMS_SignerInfo_set1_signer_cert (CMS_SignerInfo * si, X509 * signer)
Definition at line 445 of file cms_sd.c.
References EVP_PKEY_free(), X509_get_pubkey(), and X509_up_ref().
CMS_SignerInfo_sign()
int CMS_SignerInfo_sign (CMS_SignerInfo * si)
Definition at line 635 of file cms_sd.c.
CMS_SignerInfo_verify()
int CMS_SignerInfo_verify (CMS_SignerInfo * si)
Definition at line 702 of file cms_sd.c.
References NULL.
CMS_SignerInfo_verify_content()
int CMS_SignerInfo_verify_content (CMS_SignerInfo * si, BIO * chain)
Definition at line 775 of file cms_sd.c.
References cms_DigestAlgorithm_find_ctx(), CMS_F_CMS_SIGNERINFO_VERIFY_CONTENT, CMS_R_ERROR_READING_MESSAGEDIGEST_ATTRIBUTE, CMS_R_MESSAGEDIGEST_ATTRIBUTE_WRONG_LENGTH, CMS_R_UNABLE_TO_FINALIZE_CONTEXT, CMS_R_VERIFICATION_FAILURE, CMS_signed_get0_data_by_OBJ(), CMS_signed_get_attr_count(), CMSerr, ERR_R_MALLOC_FAILURE, EVP_DigestFinal_ex(), EVP_MAX_MD_SIZE, EVP_MD_CTX_new(), NID_pkcs9_messageDigest, NULL, OBJ_nid2obj(), and V_ASN1_OCTET_STRING.
CMS_stream()
int CMS_stream (unsigned char *** boundary, CMS_ContentInfo * cms)
Definition at line 17 of file cms_io.c.
References ASN1_STRING_FLAG_CONT, ASN1_STRING_FLAG_NDEF, CMS_F_CMS_STREAM, CMS_get0_content(), CMSerr, ERR_R_MALLOC_FAILURE, and NULL.
CMS_uncompress()
int CMS_uncompress (CMS_ContentInfo * cms, BIO * dcont, BIO * out, unsigned int flags)
Definition at line 831 of file cms_smime.c.
References CMS_F_CMS_UNCOMPRESS, CMS_R_UNSUPPORTED_COMPRESSION_ALGORITHM, and CMSerr.
CMS_unsigned_add1_attr()
int CMS_unsigned_add1_attr (CMS_SignerInfo * si, X509_ATTRIBUTE * attr)
Definition at line 111 of file cms_att.c.
CMS_unsigned_add1_attr_by_NID()
int CMS_unsigned_add1_attr_by_NID (CMS_SignerInfo * si, int nid, int type, const void * bytes, int len)
Definition at line 127 of file cms_att.c.
CMS_unsigned_add1_attr_by_OBJ()
int CMS_unsigned_add1_attr_by_OBJ (CMS_SignerInfo * si, const ASN1_OBJECT * obj, int type, const void * bytes, int len)
Definition at line 118 of file cms_att.c.
CMS_unsigned_add1_attr_by_txt()
int CMS_unsigned_add1_attr_by_txt (CMS_SignerInfo * si, const char * attrname, int type, const void * bytes, int len)
Definition at line 136 of file cms_att.c.
CMS_unsigned_delete_attr()
X509_ATTRIBUTE* CMS_unsigned_delete_attr (CMS_SignerInfo * si, int loc)
Definition at line 106 of file cms_att.c.
References X509at_delete_attr().
CMS_unsigned_get0_data_by_OBJ()
void* CMS_unsigned_get0_data_by_OBJ (CMS_SignerInfo * si, ASN1_OBJECT * oid, int lastpos, int type)
Definition at line 146 of file cms_att.c.
References X509at_get0_data_by_OBJ().
CMS_unsigned_get_attr()
X509_ATTRIBUTE* CMS_unsigned_get_attr (const CMS_SignerInfo * si, int loc)
Definition at line 101 of file cms_att.c.
References X509at_get_attr().
CMS_unsigned_get_attr_by_NID()
int CMS_unsigned_get_attr_by_NID (const CMS_SignerInfo * si, int nid, int lastpos)
Definition at line 89 of file cms_att.c.
References X509at_get_attr_by_NID().
CMS_unsigned_get_attr_by_OBJ()
int CMS_unsigned_get_attr_by_OBJ (const CMS_SignerInfo * si, const ASN1_OBJECT * obj, int lastpos)
Definition at line 95 of file cms_att.c.
References X509at_get_attr_by_OBJ().
CMS_unsigned_get_attr_count()
int CMS_unsigned_get_attr_count (const CMS_SignerInfo * si)
Definition at line 84 of file cms_att.c.
References X509at_get_attr_count().
CMS_verify()
int CMS_verify (CMS_ContentInfo * cms, STACK_OF(X509) * certs, X509_STORE * store, BIO * dcont, BIO * out, unsigned int flags)
Definition at line 265 of file cms_smime.c.
References NULL, and STACK_OF.
Referenced by CMS_verify_receipt().
CMS_verify_receipt()
int CMS_verify_receipt (CMS_ContentInfo * rcms, CMS_ContentInfo * ocms, STACK_OF(X509) * certs, X509_STORE * store, unsigned int flags)
Definition at line 423 of file cms_smime.c.
References CMS_DETACHED, cms_Receipt_verify(), CMS_TEXT, CMS_verify(), and NULL.
d2i_CMS_bio()
CMS_ContentInfo* d2i_CMS_bio (BIO * bp, CMS_ContentInfo ** cms)
Definition at line 35 of file cms_io.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
ERR_load_CMS_strings()
int ERR_load_CMS_strings (void)
Definition at line 248 of file cms_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
i2d_CMS_bio()
int i2d_CMS_bio (BIO * bp, CMS_ContentInfo * cms)
Definition at line 40 of file cms_io.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_CMS_bio_stream()
int i2d_CMS_bio_stream (BIO * out, CMS_ContentInfo * cms, BIO * in, int flags)
Definition at line 55 of file cms_io.c.
PEM_write_bio_CMS_stream()
int PEM_write_bio_CMS_stream (BIO * out, CMS_ContentInfo * cms, BIO * in, int flags)
Definition at line 61 of file cms_io.c.
SMIME_read_CMS()
CMS_ContentInfo* SMIME_read_CMS (BIO * bio, BIO ** bcont)
Definition at line 83 of file cms_io.c.
References ASN1_ITEM_rptr, and SMIME_read_ASN1().
SMIME_write_CMS()
int SMIME_write_CMS (BIO * bio, CMS_ContentInfo * cms, BIO * data, int flags)
Definition at line 68 of file cms_io.c.
References ASN1_ITEM_rptr, CMS_get0_eContentType(), NID_pkcs7_signed, NULL, OBJ_obj2nid(), SMIME_write_ASN1(), and STACK_OF.
STACK_OF() [1/4]
STACK_OF (X509)
Definition at line 478 of file cms_lib.c.
STACK_OF() [2/4]
STACK_OF (CMS_RecipientInfo)
Definition at line 81 of file cms_env.c.
References cms_get0_enveloped(), and NULL.
Referenced by cms_EnvelopedData_init_bio().
STACK_OF() [3/4]
STACK_OF (X509_CRL)
Definition at line 506 of file cms_lib.c.
References NULL, STACK_OF(), and X509_CRL_up_ref().
STACK_OF() [4/4]
STACK_OF (CMS_SignerInfo)
Definition at line 412 of file cms_sd.c.
Referenced by CMS_set1_signers_certs(), cms_SignedData_final(), and STACK_OF().