crypto/cms/cms_pwri.c File Reference
cms_pwri.c File Reference
#include "internal/cryptlib.h"
#include <openssl/asn1t.h>
#include <openssl/pem.h>
#include <openssl/x509v3.h>
#include <openssl/err.h>
#include <openssl/cms.h>
#include <openssl/rand.h>
#include <openssl/aes.h>
#include "cms_lcl.h"
#include "internal/asn1_int.h"
Functions
int CMS_RecipientInfo_set0_password (CMS_RecipientInfo *ri, unsigned char *pass, ossl_ssize_t passlen)
CMS_RecipientInfo * CMS_add0_recipient_password (CMS_ContentInfo *cms, int iter, int wrap_nid, int pbe_nid, unsigned char *pass, ossl_ssize_t passlen, const EVP_CIPHER *kekciph)
int cms_RecipientInfo_pwri_crypt (CMS_ContentInfo *cms, CMS_RecipientInfo *ri, int en_de)
Function Documentation
CMS_add0_recipient_password()
CMS_RecipientInfo* CMS_add0_recipient_password (CMS_ContentInfo * cms, int iter, int wrap_nid, int pbe_nid, unsigned char * pass, ossl_ssize_t passlen, const EVP_CIPHER * kekciph)
Definition at line 38 of file cms_pwri.c.
References ctx, and NULL.
cms_RecipientInfo_pwri_crypt()
int cms_RecipientInfo_pwri_crypt (CMS_ContentInfo * cms, CMS_RecipientInfo * ri, int en_de)
Definition at line 275 of file cms_pwri.c.
References ASN1_ITEM_rptr, ASN1_TYPE_unpack_sequence(), CMS_F_CMS_RECIPIENTINFO_PWRI_CRYPT, CMS_R_CIPHER_PARAMETER_INITIALISATION_ERROR, CMS_R_INVALID_KEY_ENCRYPTION_PARAMETER, CMS_R_NO_PASSWORD, CMS_R_UNKNOWN_CIPHER, CMS_R_UNSUPPORTED_KEY_ENCRYPTION_ALGORITHM, CMSerr, ERR_R_EVP_LIB, ERR_R_MALLOC_FAILURE, EVP_CIPHER_asn1_to_param(), EVP_CIPHER_CTX_new(), EVP_CIPHER_CTX_set_padding(), EVP_CipherInit_ex(), EVP_get_cipherbyobj, EVP_PBE_CipherInit(), key, NID_id_alg_PWRI_KEK, NULL, and OBJ_obj2nid().
CMS_RecipientInfo_set0_password()
int CMS_RecipientInfo_set0_password (CMS_RecipientInfo * ri, unsigned char * pass, ossl_ssize_t passlen)
Definition at line 21 of file cms_pwri.c.
References CMS_F_CMS_RECIPIENTINFO_SET0_PASSWORD, CMS_R_NOT_PWRI, CMS_RECIPINFO_PASS, CMSerr, pass, and passlen.
Referenced by CMS_decrypt_set1_password().