crypto/cms/cms_lib.c File Reference
cms_lib.c File Reference
#include <openssl/asn1t.h>
#include <openssl/x509v3.h>
#include <openssl/err.h>
#include <openssl/pem.h>
#include <openssl/bio.h>
#include <openssl/asn1.h>
#include <openssl/cms.h>
#include "cms_lcl.h"
Functions
const ASN1_OBJECT * CMS_get0_type (const CMS_ContentInfo *cms)
CMS_ContentInfo * cms_Data_create (void)
BIO * cms_content_bio (CMS_ContentInfo *cms)
BIO * CMS_dataInit (CMS_ContentInfo *cms, BIO *icont)
int CMS_dataFinal (CMS_ContentInfo *cms, BIO *cmsbio)
ASN1_OCTET_STRING ** CMS_get0_content (CMS_ContentInfo *cms)
const ASN1_OBJECT * CMS_get0_eContentType (CMS_ContentInfo *cms)
int CMS_set1_eContentType (CMS_ContentInfo *cms, const ASN1_OBJECT *oid)
int CMS_is_detached (CMS_ContentInfo *cms)
int CMS_set_detached (CMS_ContentInfo *cms, int detached)
BIO * cms_DigestAlgorithm_init_bio (X509_ALGOR *digestAlgorithm)
int cms_DigestAlgorithm_find_ctx (EVP_MD_CTX *mctx, BIO *chain, X509_ALGOR *mdalg)
CMS_CertificateChoices * CMS_add0_CertificateChoices (CMS_ContentInfo *cms)
int CMS_add0_cert (CMS_ContentInfo *cms, X509 *cert)
int CMS_add1_cert (CMS_ContentInfo *cms, X509 *cert)
CMS_RevocationInfoChoice * CMS_add0_RevocationInfoChoice (CMS_ContentInfo *cms)
int CMS_add0_crl (CMS_ContentInfo *cms, X509_CRL *crl)
int CMS_add1_crl (CMS_ContentInfo *cms, X509_CRL *crl)
STACK_OF (X509)
STACK_OF (X509_CRL)
int cms_ias_cert_cmp (CMS_IssuerAndSerialNumber *ias, X509 *cert)
int cms_keyid_cert_cmp (ASN1_OCTET_STRING *keyid, X509 *cert)
int cms_set1_ias (CMS_IssuerAndSerialNumber **pias, X509 *cert)
int cms_set1_keyid (ASN1_OCTET_STRING **pkeyid, X509 *cert)
Function Documentation
CMS_add0_cert()
int CMS_add0_cert (CMS_ContentInfo * cms, X509 * cert)
Definition at line 381 of file cms_lib.c.
CMS_add0_CertificateChoices()
CMS_CertificateChoices* CMS_add0_CertificateChoices (CMS_ContentInfo * cms)
Definition at line 360 of file cms_lib.c.
References M_ASN1_free_of, M_ASN1_new_of, NULL, and STACK_OF().
CMS_add0_crl()
int CMS_add0_crl (CMS_ContentInfo * cms, X509_CRL * crl)
Definition at line 458 of file cms_lib.c.
References CMS_add0_RevocationInfoChoice(), and CMS_REVCHOICE_CRL.
Referenced by CMS_add1_crl().
CMS_add0_RevocationInfoChoice()
CMS_RevocationInfoChoice* CMS_add0_RevocationInfoChoice (CMS_ContentInfo * cms)
Definition at line 437 of file cms_lib.c.
References M_ASN1_free_of, M_ASN1_new_of, NULL, and STACK_OF().
Referenced by CMS_add0_crl().
CMS_add1_cert()
int CMS_add1_cert (CMS_ContentInfo * cms, X509 * cert)
Definition at line 407 of file cms_lib.c.
Referenced by CMS_sign().
CMS_add1_crl()
int CMS_add1_crl (CMS_ContentInfo * cms, X509_CRL * crl)
Definition at line 469 of file cms_lib.c.
References CMS_add0_crl(), and X509_CRL_up_ref().
cms_content_bio()
BIO* cms_content_bio (CMS_ContentInfo * cms)
Definition at line 39 of file cms_lib.c.
References ASN1_STRING_FLAG_CONT, BIO_new(), BIO_new_mem_buf(), BIO_s_mem(), BIO_s_null(), CMS_get0_content(), and NULL.
Referenced by CMS_dataInit().
cms_Data_create()
CMS_ContentInfo* cms_Data_create (void)
Definition at line 27 of file cms_lib.c.
References CMS_set_detached(), NID_pkcs7_data, NULL, and OBJ_nid2obj().
Referenced by CMS_data_create().
CMS_dataFinal()
int CMS_dataFinal (CMS_ContentInfo * cms, BIO * cmsbio)
Definition at line 107 of file cms_lib.c.
References ASN1_STRING_FLAG_CONT, ASN1_STRING_set0(), BIO_find_type(), BIO_FLAGS_MEM_RDONLY, BIO_get_mem_data, BIO_set_flags(), BIO_set_mem_eof_return, BIO_TYPE_MEM, cms_DigestedData_do_final(), CMS_F_CMS_DATAFINAL, CMS_get0_content(), CMS_R_CONTENT_NOT_FOUND, CMS_R_UNSUPPORTED_TYPE, cms_SignedData_final(), CMSerr, NID_id_smime_ct_compressedData, NID_pkcs7_data, NID_pkcs7_digest, NID_pkcs7_encrypted, NID_pkcs7_enveloped, NID_pkcs7_signed, and OBJ_obj2nid().
CMS_dataInit()
BIO* CMS_dataInit (CMS_ContentInfo * cms, BIO * icont)
Definition at line 56 of file cms_lib.c.
References BIO_free(), BIO_push(), cms_CompressedData_init_bio(), cms_content_bio(), cms_DigestedData_init_bio(), cms_EncryptedData_init_bio(), cms_EnvelopedData_init_bio(), CMS_F_CMS_DATAINIT, CMS_R_NO_CONTENT, CMS_R_UNSUPPORTED_TYPE, cms_SignedData_init_bio(), CMSerr, NID_id_smime_ct_compressedData, NID_pkcs7_data, NID_pkcs7_digest, NID_pkcs7_encrypted, NID_pkcs7_enveloped, NID_pkcs7_signed, NULL, and OBJ_obj2nid().
Referenced by CMS_data().
cms_DigestAlgorithm_find_ctx()
int cms_DigestAlgorithm_find_ctx (EVP_MD_CTX * mctx, BIO * chain, X509_ALGOR * mdalg)
Definition at line 311 of file cms_lib.c.
References BIO_find_type(), BIO_get_md_ctx, BIO_next(), BIO_TYPE_MD, CMS_F_CMS_DIGESTALGORITHM_FIND_CTX, CMS_F_CMS_GET0_CERTIFICATE_CHOICES, CMS_R_NO_MATCHING_DIGEST, CMS_R_UNSUPPORTED_CONTENT_TYPE, CMSerr, EVP_MD_CTX_copy_ex(), EVP_MD_CTX_md(), EVP_MD_CTX_type, EVP_MD_pkey_type(), nid, NID_pkcs7_enveloped, NID_pkcs7_signed, NULL, OBJ_obj2nid(), STACK_OF(), and X509_ALGOR_get0().
Referenced by CMS_SignerInfo_verify_content().
cms_DigestAlgorithm_init_bio()
BIO* cms_DigestAlgorithm_init_bio (X509_ALGOR * digestAlgorithm)
Definition at line 286 of file cms_lib.c.
References BIO_f_md(), BIO_free(), BIO_new(), BIO_set_md, CMS_F_CMS_DIGESTALGORITHM_INIT_BIO, CMS_R_MD_BIO_INIT_ERROR, CMS_R_UNKNOWN_DIGEST_ALGORIHM, CMSerr, EVP_get_digestbyobj, NULL, and X509_ALGOR_get0().
Referenced by cms_DigestedData_init_bio().
CMS_get0_content()
ASN1_OCTET_STRING** CMS_get0_content (CMS_ContentInfo * cms)
Definition at line 156 of file cms_lib.c.
References CMS_F_CMS_GET0_CONTENT, CMS_R_UNSUPPORTED_CONTENT_TYPE, CMSerr, NID_id_smime_ct_authData, NID_id_smime_ct_compressedData, NID_pkcs7_data, NID_pkcs7_digest, NID_pkcs7_encrypted, NID_pkcs7_enveloped, NID_pkcs7_signed, NULL, OBJ_obj2nid(), and V_ASN1_OCTET_STRING.
Referenced by cms_content_bio(), CMS_dataFinal(), CMS_is_detached(), cms_Receipt_verify(), CMS_set_detached(), CMS_sign_receipt(), and CMS_stream().
CMS_get0_eContentType()
const ASN1_OBJECT* CMS_get0_eContentType (CMS_ContentInfo * cms)
Definition at line 224 of file cms_lib.c.
Referenced by cms_Receipt_verify(), and SMIME_write_CMS().
CMS_get0_type()
const ASN1_OBJECT* CMS_get0_type (const CMS_ContentInfo * cms)
Definition at line 22 of file cms_lib.c.
Referenced by CMS_data(), CMS_decrypt(), CMS_digest_verify(), and CMS_EncryptedData_decrypt().
cms_ias_cert_cmp()
int cms_ias_cert_cmp (CMS_IssuerAndSerialNumber * ias, X509 * cert)
Definition at line 533 of file cms_lib.c.
CMS_is_detached()
int CMS_is_detached (CMS_ContentInfo * cms)
Definition at line 249 of file cms_lib.c.
References CMS_get0_content().
cms_keyid_cert_cmp()
int cms_keyid_cert_cmp (ASN1_OCTET_STRING * keyid, X509 * cert)
Definition at line 542 of file cms_lib.c.
CMS_set1_eContentType()
int CMS_set1_eContentType (CMS_ContentInfo * cms, const ASN1_OBJECT * oid)
Definition at line 233 of file cms_lib.c.
Referenced by CMS_sign(), and CMS_sign_receipt().
cms_set1_ias()
int cms_set1_ias (CMS_IssuerAndSerialNumber ** pias, X509 * cert)
Definition at line 551 of file cms_lib.c.
Referenced by cms_RecipientInfo_kari_init().
cms_set1_keyid()
int cms_set1_keyid (ASN1_OCTET_STRING ** pkeyid, X509 * cert)
Definition at line 570 of file cms_lib.c.
Referenced by cms_RecipientInfo_kari_init().
CMS_set_detached()
int CMS_set_detached (CMS_ContentInfo * cms, int detached)
Definition at line 260 of file cms_lib.c.
References ASN1_STRING_FLAG_CONT, CMS_F_CMS_SET_DETACHED, CMS_get0_content(), CMSerr, ERR_R_MALLOC_FAILURE, and NULL.
Referenced by cms_Data_create(), and CMS_sign().
STACK_OF() [1/2]
STACK_OF (X509)
Definition at line 478 of file cms_lib.c.
Referenced by CMS_add0_CertificateChoices(), CMS_add0_RevocationInfoChoice(), cms_DigestAlgorithm_find_ctx(), and STACK_OF().
STACK_OF() [2/2]
STACK_OF (X509_CRL)
Definition at line 506 of file cms_lib.c.