crypto/cms/cms_lcl.h File Reference
cms_lcl.h File Reference
#include <openssl/x509.h>
Data Structures
struct CMS_ContentInfo
struct CMS_SignedData
struct CMS_EncapsulatedContentInfo
struct CMS_SignerInfo
struct CMS_SignerIdentifier
struct CMS_EnvelopedData
struct CMS_OriginatorInfo
struct CMS_EncryptedContentInfo
struct CMS_RecipientInfo
struct CMS_KeyTransRecipientInfo
struct CMS_KeyAgreeRecipientInfo
struct CMS_OriginatorIdentifierOrKey
struct CMS_OriginatorPublicKey
struct CMS_RecipientEncryptedKey
struct CMS_KeyAgreeRecipientIdentifier
struct CMS_RecipientKeyIdentifier
struct CMS_KEKRecipientInfo
struct CMS_KEKIdentifier
struct CMS_PasswordRecipientInfo
struct CMS_OtherRecipientInfo
struct CMS_DigestedData
struct CMS_EncryptedData
struct CMS_AuthenticatedData
struct CMS_CompressedData
struct CMS_RevocationInfoChoice
struct CMS_OtherRevocationInfoFormat
struct CMS_CertificateChoices
struct CMS_OtherCertificateFormat
struct CMS_IssuerAndSerialNumber
struct CMS_OtherKeyAttribute
struct CMS_Receipt
Macros
#define CMS_REVCHOICE_CRL 0
#define CMS_REVCHOICE_OTHER 1
#define CMS_CERTCHOICE_CERT 0
#define CMS_CERTCHOICE_EXCERT 1
#define CMS_CERTCHOICE_V1ACERT 2
#define CMS_CERTCHOICE_V2ACERT 3
#define CMS_CERTCHOICE_OTHER 4
#define CMS_SIGNERINFO_ISSUER_SERIAL 0
#define CMS_SIGNERINFO_KEYIDENTIFIER 1
#define CMS_RECIPINFO_ISSUER_SERIAL 0
#define CMS_RECIPINFO_KEYIDENTIFIER 1
#define CMS_REK_ISSUER_SERIAL 0
#define CMS_REK_KEYIDENTIFIER 1
#define CMS_OIK_ISSUER_SERIAL 0
#define CMS_OIK_KEYIDENTIFIER 1
#define CMS_OIK_PUBKEY 2
Typedefs
typedef struct CMS_ReceiptsFrom_st CMS_ReceiptsFrom
typedef CMS_SignerIdentifier CMS_RecipientIdentifier
Functions
BIO * cms_content_bio (CMS_ContentInfo *cms)
CMS_ContentInfo * cms_Data_create (void)
CMS_ContentInfo * cms_DigestedData_create (const EVP_MD *md)
BIO * cms_DigestedData_init_bio (CMS_ContentInfo *cms)
int cms_DigestedData_do_final (CMS_ContentInfo *cms, BIO *chain, int verify)
BIO * cms_SignedData_init_bio (CMS_ContentInfo *cms)
int cms_SignedData_final (CMS_ContentInfo *cms, BIO *chain)
int cms_set1_SignerIdentifier (CMS_SignerIdentifier *sid, X509 *cert, int type)
int cms_SignerIdentifier_get0_signer_id (CMS_SignerIdentifier *sid, ASN1_OCTET_STRING **keyid, X509_NAME **issuer, ASN1_INTEGER **sno)
int cms_SignerIdentifier_cert_cmp (CMS_SignerIdentifier *sid, X509 *cert)
CMS_ContentInfo * cms_CompressedData_create (int comp_nid)
BIO * cms_CompressedData_init_bio (CMS_ContentInfo *cms)
BIO * cms_DigestAlgorithm_init_bio (X509_ALGOR *digestAlgorithm)
int cms_DigestAlgorithm_find_ctx (EVP_MD_CTX *mctx, BIO *chain, X509_ALGOR *mdalg)
int cms_ias_cert_cmp (CMS_IssuerAndSerialNumber *ias, X509 *cert)
int cms_keyid_cert_cmp (ASN1_OCTET_STRING *keyid, X509 *cert)
int cms_set1_ias (CMS_IssuerAndSerialNumber **pias, X509 *cert)
int cms_set1_keyid (ASN1_OCTET_STRING **pkeyid, X509 *cert)
BIO * cms_EncryptedContent_init_bio (CMS_EncryptedContentInfo *ec)
BIO * cms_EncryptedData_init_bio (CMS_ContentInfo *cms)
int cms_EncryptedContent_init (CMS_EncryptedContentInfo *ec, const EVP_CIPHER *cipher, const unsigned char *key, size_t keylen)
int cms_Receipt_verify (CMS_ContentInfo *cms, CMS_ContentInfo *req_cms)
int cms_msgSigDigest_add1 (CMS_SignerInfo *dest, CMS_SignerInfo *src)
ASN1_OCTET_STRING * cms_encode_Receipt (CMS_SignerInfo *si)
BIO * cms_EnvelopedData_init_bio (CMS_ContentInfo *cms)
CMS_EnvelopedData * cms_get0_enveloped (CMS_ContentInfo *cms)
int cms_env_asn1_ctrl (CMS_RecipientInfo *ri, int cmd)
int cms_pkey_get_ri_type (EVP_PKEY *pk)
int cms_RecipientInfo_kari_init (CMS_RecipientInfo *ri, X509 *recip, EVP_PKEY *pk, unsigned int flags)
int cms_RecipientInfo_kari_encrypt (CMS_ContentInfo *cms, CMS_RecipientInfo *ri)
int cms_RecipientInfo_pwri_crypt (CMS_ContentInfo *cms, CMS_RecipientInfo *ri, int en_de)
Macro Definition Documentation
CMS_CERTCHOICE_CERT
#define CMS_CERTCHOICE_CERT 0
Definition at line 296 of file cms_lcl.h.
CMS_CERTCHOICE_EXCERT
#define CMS_CERTCHOICE_EXCERT 1
Definition at line 297 of file cms_lcl.h.
CMS_CERTCHOICE_OTHER
#define CMS_CERTCHOICE_OTHER 4
Definition at line 300 of file cms_lcl.h.
CMS_CERTCHOICE_V1ACERT
#define CMS_CERTCHOICE_V1ACERT 2
Definition at line 298 of file cms_lcl.h.
CMS_CERTCHOICE_V2ACERT
#define CMS_CERTCHOICE_V2ACERT 3
Definition at line 299 of file cms_lcl.h.
CMS_OIK_ISSUER_SERIAL
#define CMS_OIK_ISSUER_SERIAL 0
Definition at line 366 of file cms_lcl.h.
Referenced by CMS_RecipientInfo_kari_get0_orig_id().
CMS_OIK_KEYIDENTIFIER
#define CMS_OIK_KEYIDENTIFIER 1
Definition at line 367 of file cms_lcl.h.
Referenced by CMS_RecipientInfo_kari_get0_orig_id().
CMS_OIK_PUBKEY
#define CMS_OIK_PUBKEY 2
Definition at line 368 of file cms_lcl.h.
Referenced by CMS_RecipientInfo_kari_get0_orig_id().
CMS_RECIPINFO_ISSUER_SERIAL
#define CMS_RECIPINFO_ISSUER_SERIAL 0
Definition at line 360 of file cms_lcl.h.
CMS_RECIPINFO_KEYIDENTIFIER
#define CMS_RECIPINFO_KEYIDENTIFIER 1
Definition at line 361 of file cms_lcl.h.
CMS_REK_ISSUER_SERIAL
#define CMS_REK_ISSUER_SERIAL 0
Definition at line 363 of file cms_lcl.h.
Referenced by CMS_RecipientEncryptedKey_get0_id(), and cms_RecipientInfo_kari_init().
CMS_REK_KEYIDENTIFIER
#define CMS_REK_KEYIDENTIFIER 1
Definition at line 364 of file cms_lcl.h.
Referenced by CMS_RecipientEncryptedKey_get0_id(), and cms_RecipientInfo_kari_init().
CMS_REVCHOICE_CRL
#define CMS_REVCHOICE_CRL 0
Definition at line 277 of file cms_lcl.h.
Referenced by CMS_add0_crl().
CMS_REVCHOICE_OTHER
#define CMS_REVCHOICE_OTHER 1
Definition at line 278 of file cms_lcl.h.
CMS_SIGNERINFO_ISSUER_SERIAL
#define CMS_SIGNERINFO_ISSUER_SERIAL 0
Definition at line 357 of file cms_lcl.h.
Referenced by cms_SignerIdentifier_get0_signer_id().
CMS_SIGNERINFO_KEYIDENTIFIER
#define CMS_SIGNERINFO_KEYIDENTIFIER 1
Definition at line 358 of file cms_lcl.h.
Referenced by cms_SignerIdentifier_get0_signer_id().
Typedef Documentation
CMS_ReceiptsFrom
typedef struct CMS_ReceiptsFrom_st CMS_ReceiptsFrom
Definition at line 49 of file cms_lcl.h.
CMS_RecipientIdentifier
typedef CMS_SignerIdentifier CMS_RecipientIdentifier
Definition at line 145 of file cms_lcl.h.
Function Documentation
cms_CompressedData_create()
CMS_ContentInfo* cms_CompressedData_create (int comp_nid)
cms_CompressedData_init_bio()
BIO* cms_CompressedData_init_bio (CMS_ContentInfo * cms)
Referenced by CMS_dataInit().
cms_content_bio()
BIO* cms_content_bio (CMS_ContentInfo * cms)
Definition at line 39 of file cms_lib.c.
References ASN1_STRING_FLAG_CONT, BIO_new(), BIO_new_mem_buf(), BIO_s_mem(), BIO_s_null(), CMS_get0_content(), and NULL.
Referenced by CMS_dataInit().
cms_Data_create()
CMS_ContentInfo* cms_Data_create (void)
Definition at line 27 of file cms_lib.c.
References CMS_set_detached(), NID_pkcs7_data, NULL, and OBJ_nid2obj().
Referenced by CMS_data_create().
cms_DigestAlgorithm_find_ctx()
int cms_DigestAlgorithm_find_ctx (EVP_MD_CTX * mctx, BIO * chain, X509_ALGOR * mdalg)
Definition at line 311 of file cms_lib.c.
References BIO_find_type(), BIO_get_md_ctx, BIO_next(), BIO_TYPE_MD, CMS_F_CMS_DIGESTALGORITHM_FIND_CTX, CMS_F_CMS_GET0_CERTIFICATE_CHOICES, CMS_R_NO_MATCHING_DIGEST, CMS_R_UNSUPPORTED_CONTENT_TYPE, CMSerr, EVP_MD_CTX_copy_ex(), EVP_MD_CTX_md(), EVP_MD_CTX_type, EVP_MD_pkey_type(), nid, NID_pkcs7_enveloped, NID_pkcs7_signed, NULL, OBJ_obj2nid(), STACK_OF(), and X509_ALGOR_get0().
Referenced by CMS_SignerInfo_verify_content().
cms_DigestAlgorithm_init_bio()
BIO* cms_DigestAlgorithm_init_bio (X509_ALGOR * digestAlgorithm)
Definition at line 286 of file cms_lib.c.
References BIO_f_md(), BIO_free(), BIO_new(), BIO_set_md, CMS_F_CMS_DIGESTALGORITHM_INIT_BIO, CMS_R_MD_BIO_INIT_ERROR, CMS_R_UNKNOWN_DIGEST_ALGORIHM, CMSerr, EVP_get_digestbyobj, NULL, and X509_ALGOR_get0().
Referenced by cms_DigestedData_init_bio().
cms_DigestedData_create()
CMS_ContentInfo* cms_DigestedData_create (const EVP_MD * md)
Definition at line 20 of file cms_dd.c.
cms_DigestedData_do_final()
int cms_DigestedData_do_final (CMS_ContentInfo * cms, BIO * chain, int verify)
Definition at line 55 of file cms_dd.c.
Referenced by CMS_dataFinal().
cms_DigestedData_init_bio()
BIO* cms_DigestedData_init_bio (CMS_ContentInfo * cms)
Definition at line 48 of file cms_dd.c.
References cms_DigestAlgorithm_init_bio().
Referenced by CMS_dataInit().
cms_encode_Receipt()
ASN1_OCTET_STRING* cms_encode_Receipt (CMS_SignerInfo * si)
Definition at line 301 of file cms_ess.c.
References ASN1_item_pack(), ASN1_ITEM_rptr, CMS_F_CMS_ENCODE_RECEIPT, CMS_get1_ReceiptRequest(), CMS_R_NO_CONTENT_TYPE, CMS_R_NO_RECEIPT_REQUEST, CMS_signed_get0_data_by_OBJ(), CMSerr, NID_pkcs9_contentType, NULL, OBJ_nid2obj(), and V_ASN1_OBJECT.
Referenced by CMS_sign_receipt().
cms_EncryptedContent_init()
int cms_EncryptedContent_init (CMS_EncryptedContentInfo * ec, const EVP_CIPHER * cipher, const unsigned char * key, size_t keylen)
Definition at line 165 of file cms_enc.c.
Referenced by CMS_EncryptedData_set1_key().
cms_EncryptedContent_init_bio()
BIO* cms_EncryptedContent_init_bio (CMS_EncryptedContentInfo * ec)
Definition at line 23 of file cms_enc.c.
References ctx.
Referenced by cms_EncryptedData_init_bio().
cms_EncryptedData_init_bio()
BIO* cms_EncryptedData_init_bio (CMS_ContentInfo * cms)
Definition at line 206 of file cms_enc.c.
References cms_EncryptedContent_init_bio().
Referenced by CMS_dataInit().
cms_env_asn1_ctrl()
int cms_env_asn1_ctrl (CMS_RecipientInfo * ri, int cmd)
Definition at line 51 of file cms_env.c.
References CMS_RECIPINFO_AGREE, and CMS_RECIPINFO_TRANS.
Referenced by CMS_RecipientInfo_kari_decrypt().
cms_EnvelopedData_init_bio()
BIO* cms_EnvelopedData_init_bio (CMS_ContentInfo * cms)
Definition at line 842 of file cms_env.c.
References STACK_OF().
Referenced by CMS_dataInit().
cms_get0_enveloped()
CMS_EnvelopedData* cms_get0_enveloped (CMS_ContentInfo * cms)
Definition at line 23 of file cms_env.c.
References CMS_F_CMS_GET0_ENVELOPED, CMS_R_CONTENT_TYPE_NOT_ENVELOPED_DATA, CMSerr, NID_pkcs7_enveloped, NULL, and OBJ_obj2nid().
Referenced by CMS_add0_recipient_key(), CMS_add1_recipient_cert(), and STACK_OF().
cms_ias_cert_cmp()
int cms_ias_cert_cmp (CMS_IssuerAndSerialNumber * ias, X509 * cert)
Definition at line 533 of file cms_lib.c.
cms_keyid_cert_cmp()
int cms_keyid_cert_cmp (ASN1_OCTET_STRING * keyid, X509 * cert)
Definition at line 542 of file cms_lib.c.
cms_msgSigDigest_add1()
int cms_msgSigDigest_add1 (CMS_SignerInfo * dest, CMS_SignerInfo * src)
Definition at line 153 of file cms_ess.c.
References EVP_MAX_MD_SIZE.
Referenced by CMS_sign_receipt().
cms_pkey_get_ri_type()
int cms_pkey_get_ri_type (EVP_PKEY * pk)
Definition at line 893 of file cms_env.c.
References ASN1_PKEY_CTRL_CMS_RI_TYPE, and CMS_RECIPINFO_TRANS.
Referenced by CMS_add1_recipient_cert().
cms_Receipt_verify()
int cms_Receipt_verify (CMS_ContentInfo * cms, CMS_ContentInfo * req_cms)
Definition at line 171 of file cms_ess.c.
References ASN1_ITEM_rptr, ASN1_item_unpack(), ASN1_STRING_cmp(), CMS_F_CMS_RECEIPT_VERIFY, CMS_get0_content(), CMS_get0_eContentType(), CMS_R_NEED_ONE_SIGNER, CMS_R_NO_CONTENT, CMS_R_NO_MATCHING_SIGNATURE, CMS_R_NO_MSGSIGDIGEST, CMS_R_NOT_A_SIGNED_RECEIPT, CMS_R_RECEIPT_DECODE_ERROR, CMS_signed_get0_data_by_OBJ(), CMSerr, EVP_MAX_MD_SIZE, NID_id_smime_aa_msgSigDigest, NID_id_smime_ct_receipt, NULL, OBJ_nid2obj(), OBJ_obj2nid(), STACK_OF, and V_ASN1_OCTET_STRING.
Referenced by CMS_verify_receipt().
cms_RecipientInfo_kari_encrypt()
int cms_RecipientInfo_kari_encrypt (CMS_ContentInfo * cms, CMS_RecipientInfo * ri)
Definition at line 363 of file cms_kari.c.
References CMS_F_CMS_RECIPIENTINFO_KARI_ENCRYPT, CMS_R_NOT_KEY_AGREEMENT, CMS_RECIPINFO_AGREE, CMSerr, and STACK_OF.
cms_RecipientInfo_kari_init()
int cms_RecipientInfo_kari_init (CMS_RecipientInfo * ri, X509 * recip, EVP_PKEY * pk, unsigned int flags)
Definition at line 287 of file cms_kari.c.
References CMS_RECIPINFO_AGREE, CMS_REK_ISSUER_SERIAL, CMS_REK_KEYIDENTIFIER, cms_set1_ias(), cms_set1_keyid(), CMS_USE_KEYID, M_ASN1_free_of, M_ASN1_new_of, and NULL.
cms_RecipientInfo_pwri_crypt()
int cms_RecipientInfo_pwri_crypt (CMS_ContentInfo * cms, CMS_RecipientInfo * ri, int en_de)
Definition at line 275 of file cms_pwri.c.
References ASN1_ITEM_rptr, ASN1_TYPE_unpack_sequence(), CMS_F_CMS_RECIPIENTINFO_PWRI_CRYPT, CMS_R_CIPHER_PARAMETER_INITIALISATION_ERROR, CMS_R_INVALID_KEY_ENCRYPTION_PARAMETER, CMS_R_NO_PASSWORD, CMS_R_UNKNOWN_CIPHER, CMS_R_UNSUPPORTED_KEY_ENCRYPTION_ALGORITHM, CMSerr, ERR_R_EVP_LIB, ERR_R_MALLOC_FAILURE, EVP_CIPHER_asn1_to_param(), EVP_CIPHER_CTX_new(), EVP_CIPHER_CTX_set_padding(), EVP_CipherInit_ex(), EVP_get_cipherbyobj, EVP_PBE_CipherInit(), key, NID_id_alg_PWRI_KEK, NULL, and OBJ_obj2nid().
cms_set1_ias()
int cms_set1_ias (CMS_IssuerAndSerialNumber ** pias, X509 * cert)
Definition at line 551 of file cms_lib.c.
Referenced by cms_RecipientInfo_kari_init().
cms_set1_keyid()
int cms_set1_keyid (ASN1_OCTET_STRING ** pkeyid, X509 * cert)
Definition at line 570 of file cms_lib.c.
Referenced by cms_RecipientInfo_kari_init().
cms_set1_SignerIdentifier()
int cms_set1_SignerIdentifier (CMS_SignerIdentifier * sid, X509 * cert, int type)
Definition at line 151 of file cms_sd.c.
cms_SignedData_final()
int cms_SignedData_final (CMS_ContentInfo * cms, BIO * chain)
Definition at line 620 of file cms_sd.c.
References STACK_OF().
Referenced by CMS_dataFinal().
cms_SignedData_init_bio()
BIO* cms_SignedData_init_bio (CMS_ContentInfo * cms)
Definition at line 747 of file cms_sd.c.
References NULL.
Referenced by CMS_dataInit().
cms_SignerIdentifier_cert_cmp()
int cms_SignerIdentifier_cert_cmp (CMS_SignerIdentifier * sid, X509 * cert)
Definition at line 192 of file cms_sd.c.
cms_SignerIdentifier_get0_signer_id()
int cms_SignerIdentifier_get0_signer_id (CMS_SignerIdentifier * sid, ASN1_OCTET_STRING ** keyid, X509_NAME ** issuer, ASN1_INTEGER ** sno)
Definition at line 174 of file cms_sd.c.
References CMS_SIGNERINFO_ISSUER_SERIAL, and CMS_SIGNERINFO_KEYIDENTIFIER.
Referenced by CMS_RecipientInfo_ktri_get0_signer_id(), and CMS_SignerInfo_get0_signer_id().