crypto/cms/cms_att.c File Reference
cms_att.c File Reference
#include <openssl/asn1t.h>
#include <openssl/pem.h>
#include <openssl/x509v3.h>
#include <openssl/err.h>
#include <openssl/cms.h>
#include "cms_lcl.h"
Functions
int CMS_signed_get_attr_count (const CMS_SignerInfo *si)
int CMS_signed_get_attr_by_NID (const CMS_SignerInfo *si, int nid, int lastpos)
int CMS_signed_get_attr_by_OBJ (const CMS_SignerInfo *si, const ASN1_OBJECT *obj, int lastpos)
X509_ATTRIBUTE * CMS_signed_get_attr (const CMS_SignerInfo *si, int loc)
X509_ATTRIBUTE * CMS_signed_delete_attr (CMS_SignerInfo *si, int loc)
int CMS_signed_add1_attr (CMS_SignerInfo *si, X509_ATTRIBUTE *attr)
int CMS_signed_add1_attr_by_OBJ (CMS_SignerInfo *si, const ASN1_OBJECT *obj, int type, const void *bytes, int len)
int CMS_signed_add1_attr_by_NID (CMS_SignerInfo *si, int nid, int type, const void *bytes, int len)
int CMS_signed_add1_attr_by_txt (CMS_SignerInfo *si, const char *attrname, int type, const void *bytes, int len)
void * CMS_signed_get0_data_by_OBJ (CMS_SignerInfo *si, const ASN1_OBJECT *oid, int lastpos, int type)
int CMS_unsigned_get_attr_count (const CMS_SignerInfo *si)
int CMS_unsigned_get_attr_by_NID (const CMS_SignerInfo *si, int nid, int lastpos)
int CMS_unsigned_get_attr_by_OBJ (const CMS_SignerInfo *si, const ASN1_OBJECT *obj, int lastpos)
X509_ATTRIBUTE * CMS_unsigned_get_attr (const CMS_SignerInfo *si, int loc)
X509_ATTRIBUTE * CMS_unsigned_delete_attr (CMS_SignerInfo *si, int loc)
int CMS_unsigned_add1_attr (CMS_SignerInfo *si, X509_ATTRIBUTE *attr)
int CMS_unsigned_add1_attr_by_OBJ (CMS_SignerInfo *si, const ASN1_OBJECT *obj, int type, const void *bytes, int len)
int CMS_unsigned_add1_attr_by_NID (CMS_SignerInfo *si, int nid, int type, const void *bytes, int len)
int CMS_unsigned_add1_attr_by_txt (CMS_SignerInfo *si, const char *attrname, int type, const void *bytes, int len)
void * CMS_unsigned_get0_data_by_OBJ (CMS_SignerInfo *si, ASN1_OBJECT *oid, int lastpos, int type)
Function Documentation
CMS_signed_add1_attr()
int CMS_signed_add1_attr (CMS_SignerInfo * si, X509_ATTRIBUTE * attr)
Definition at line 45 of file cms_att.c.
CMS_signed_add1_attr_by_NID()
int CMS_signed_add1_attr_by_NID (CMS_SignerInfo * si, int nid, int type, const void * bytes, int len)
Definition at line 61 of file cms_att.c.
Referenced by CMS_add1_ReceiptRequest(), and CMS_add_smimecap().
CMS_signed_add1_attr_by_OBJ()
int CMS_signed_add1_attr_by_OBJ (CMS_SignerInfo * si, const ASN1_OBJECT * obj, int type, const void * bytes, int len)
Definition at line 52 of file cms_att.c.
CMS_signed_add1_attr_by_txt()
int CMS_signed_add1_attr_by_txt (CMS_SignerInfo * si, const char * attrname, int type, const void * bytes, int len)
Definition at line 69 of file cms_att.c.
CMS_signed_delete_attr()
X509_ATTRIBUTE* CMS_signed_delete_attr (CMS_SignerInfo * si, int loc)
Definition at line 40 of file cms_att.c.
References X509at_delete_attr().
CMS_signed_get0_data_by_OBJ()
void* CMS_signed_get0_data_by_OBJ (CMS_SignerInfo * si, const ASN1_OBJECT * oid, int lastpos, int type)
Definition at line 78 of file cms_att.c.
References X509at_get0_data_by_OBJ().
Referenced by cms_encode_Receipt(), CMS_get1_ReceiptRequest(), cms_Receipt_verify(), and CMS_SignerInfo_verify_content().
CMS_signed_get_attr()
X509_ATTRIBUTE* CMS_signed_get_attr (const CMS_SignerInfo * si, int loc)
Definition at line 35 of file cms_att.c.
References X509at_get_attr().
CMS_signed_get_attr_by_NID()
int CMS_signed_get_attr_by_NID (const CMS_SignerInfo * si, int nid, int lastpos)
Definition at line 24 of file cms_att.c.
References X509at_get_attr_by_NID().
CMS_signed_get_attr_by_OBJ()
int CMS_signed_get_attr_by_OBJ (const CMS_SignerInfo * si, const ASN1_OBJECT * obj, int lastpos)
Definition at line 29 of file cms_att.c.
References X509at_get_attr_by_OBJ().
CMS_signed_get_attr_count()
int CMS_signed_get_attr_count (const CMS_SignerInfo * si)
Definition at line 19 of file cms_att.c.
References X509at_get_attr_count().
Referenced by CMS_SignerInfo_verify_content().
CMS_unsigned_add1_attr()
int CMS_unsigned_add1_attr (CMS_SignerInfo * si, X509_ATTRIBUTE * attr)
Definition at line 111 of file cms_att.c.
CMS_unsigned_add1_attr_by_NID()
int CMS_unsigned_add1_attr_by_NID (CMS_SignerInfo * si, int nid, int type, const void * bytes, int len)
Definition at line 127 of file cms_att.c.
CMS_unsigned_add1_attr_by_OBJ()
int CMS_unsigned_add1_attr_by_OBJ (CMS_SignerInfo * si, const ASN1_OBJECT * obj, int type, const void * bytes, int len)
Definition at line 118 of file cms_att.c.
CMS_unsigned_add1_attr_by_txt()
int CMS_unsigned_add1_attr_by_txt (CMS_SignerInfo * si, const char * attrname, int type, const void * bytes, int len)
Definition at line 136 of file cms_att.c.
CMS_unsigned_delete_attr()
X509_ATTRIBUTE* CMS_unsigned_delete_attr (CMS_SignerInfo * si, int loc)
Definition at line 106 of file cms_att.c.
References X509at_delete_attr().
CMS_unsigned_get0_data_by_OBJ()
void* CMS_unsigned_get0_data_by_OBJ (CMS_SignerInfo * si, ASN1_OBJECT * oid, int lastpos, int type)
Definition at line 146 of file cms_att.c.
References X509at_get0_data_by_OBJ().
CMS_unsigned_get_attr()
X509_ATTRIBUTE* CMS_unsigned_get_attr (const CMS_SignerInfo * si, int loc)
Definition at line 101 of file cms_att.c.
References X509at_get_attr().
CMS_unsigned_get_attr_by_NID()
int CMS_unsigned_get_attr_by_NID (const CMS_SignerInfo * si, int nid, int lastpos)
Definition at line 89 of file cms_att.c.
References X509at_get_attr_by_NID().
CMS_unsigned_get_attr_by_OBJ()
int CMS_unsigned_get_attr_by_OBJ (const CMS_SignerInfo * si, const ASN1_OBJECT * obj, int lastpos)
Definition at line 95 of file cms_att.c.
References X509at_get_attr_by_OBJ().
CMS_unsigned_get_attr_count()
int CMS_unsigned_get_attr_count (const CMS_SignerInfo * si)
Definition at line 84 of file cms_att.c.
References X509at_get_attr_count().