crypto/cms/cms_ess.c File Reference
cms_ess.c File Reference
#include "internal/cryptlib.h"
#include <openssl/asn1t.h>
#include <openssl/pem.h>
#include <openssl/rand.h>
#include <openssl/x509v3.h>
#include <openssl/err.h>
#include <openssl/cms.h>
#include "cms_lcl.h"
Functions
int CMS_get1_ReceiptRequest (CMS_SignerInfo *si, CMS_ReceiptRequest **prr)
CMS_ReceiptRequest * CMS_ReceiptRequest_create0 (unsigned char *id, int idlen, int allorfirst, *receiptList, STACK_OF(GENERAL_NAMES) *receiptsTo)
int CMS_add1_ReceiptRequest (CMS_SignerInfo *si, CMS_ReceiptRequest *rr)
void CMS_ReceiptRequest_get0_values (CMS_ReceiptRequest *rr, ASN1_STRING **pcid, int *pallorfirst, STACK_OF(GENERAL_NAMES) **plist, STACK_OF(GENERAL_NAMES) **prto)
int cms_msgSigDigest_add1 (CMS_SignerInfo *dest, CMS_SignerInfo *src)
int cms_Receipt_verify (CMS_ContentInfo *cms, CMS_ContentInfo *req_cms)
ASN1_OCTET_STRING * cms_encode_Receipt (CMS_SignerInfo *si)
Function Documentation
CMS_add1_ReceiptRequest()
int CMS_add1_ReceiptRequest (CMS_SignerInfo * si, CMS_ReceiptRequest * rr)
Definition at line 88 of file cms_ess.c.
References CMS_F_CMS_ADD1_RECEIPTREQUEST, CMS_signed_add1_attr_by_NID(), CMSerr, ERR_R_MALLOC_FAILURE, NID_id_smime_aa_receiptRequest, NULL, OPENSSL_free, and V_ASN1_SEQUENCE.
cms_encode_Receipt()
ASN1_OCTET_STRING* cms_encode_Receipt (CMS_SignerInfo * si)
Definition at line 301 of file cms_ess.c.
References ASN1_item_pack(), ASN1_ITEM_rptr, CMS_F_CMS_ENCODE_RECEIPT, CMS_get1_ReceiptRequest(), CMS_R_NO_CONTENT_TYPE, CMS_R_NO_RECEIPT_REQUEST, CMS_signed_get0_data_by_OBJ(), CMSerr, NID_pkcs9_contentType, NULL, OBJ_nid2obj(), and V_ASN1_OBJECT.
Referenced by CMS_sign_receipt().
CMS_get1_ReceiptRequest()
int CMS_get1_ReceiptRequest (CMS_SignerInfo * si, CMS_ReceiptRequest ** prr)
Definition at line 23 of file cms_ess.c.
References ASN1_ITEM_rptr, ASN1_item_unpack(), CMS_signed_get0_data_by_OBJ(), NID_id_smime_aa_receiptRequest, NULL, OBJ_nid2obj(), and V_ASN1_SEQUENCE.
Referenced by cms_encode_Receipt().
cms_msgSigDigest_add1()
int cms_msgSigDigest_add1 (CMS_SignerInfo * dest, CMS_SignerInfo * src)
Definition at line 153 of file cms_ess.c.
References EVP_MAX_MD_SIZE.
Referenced by CMS_sign_receipt().
cms_Receipt_verify()
int cms_Receipt_verify (CMS_ContentInfo * cms, CMS_ContentInfo * req_cms)
Definition at line 171 of file cms_ess.c.
References ASN1_ITEM_rptr, ASN1_item_unpack(), ASN1_STRING_cmp(), CMS_F_CMS_RECEIPT_VERIFY, CMS_get0_content(), CMS_get0_eContentType(), CMS_R_NEED_ONE_SIGNER, CMS_R_NO_CONTENT, CMS_R_NO_MATCHING_SIGNATURE, CMS_R_NO_MSGSIGDIGEST, CMS_R_NOT_A_SIGNED_RECEIPT, CMS_R_RECEIPT_DECODE_ERROR, CMS_signed_get0_data_by_OBJ(), CMSerr, EVP_MAX_MD_SIZE, NID_id_smime_aa_msgSigDigest, NID_id_smime_ct_receipt, NULL, OBJ_nid2obj(), OBJ_obj2nid(), STACK_OF, and V_ASN1_OCTET_STRING.
Referenced by CMS_verify_receipt().
CMS_ReceiptRequest_create0()
CMS_ReceiptRequest* CMS_ReceiptRequest_create0 (unsigned char * id, int idlen, int allorfirst, * receiptList, STACK_OF(GENERAL_NAMES) * receiptsTo)
Definition at line 46 of file cms_ess.c.
References ASN1_STRING_set(), ASN1_STRING_set0(), CMS_F_CMS_RECEIPTREQUEST_CREATE0, CMSerr, ERR_R_MALLOC_FAILURE, NULL, and RAND_bytes().
CMS_ReceiptRequest_get0_values()
void CMS_ReceiptRequest_get0_values (CMS_ReceiptRequest * rr, ASN1_STRING ** pcid, int * pallorfirst, STACK_OF(GENERAL_NAMES) ** plist, STACK_OF(GENERAL_NAMES) ** prto)
Definition at line 113 of file cms_ess.c.
References if(), and NULL.