crypto/cms/cms_dd.c File Reference
cms_dd.c File Reference
#include "internal/cryptlib.h"
#include <openssl/asn1t.h>
#include <openssl/pem.h>
#include <openssl/x509v3.h>
#include <openssl/err.h>
#include <openssl/cms.h>
#include "cms_lcl.h"
Functions
CMS_ContentInfo * cms_DigestedData_create (const EVP_MD *md)
BIO * cms_DigestedData_init_bio (CMS_ContentInfo *cms)
int cms_DigestedData_do_final (CMS_ContentInfo *cms, BIO *chain, int verify)
Function Documentation
cms_DigestedData_create()
CMS_ContentInfo* cms_DigestedData_create (const EVP_MD * md)
Definition at line 20 of file cms_dd.c.
cms_DigestedData_do_final()
int cms_DigestedData_do_final (CMS_ContentInfo * cms, BIO * chain, int verify)
Definition at line 55 of file cms_dd.c.
Referenced by CMS_dataFinal().
cms_DigestedData_init_bio()
BIO* cms_DigestedData_init_bio (CMS_ContentInfo * cms)
Definition at line 48 of file cms_dd.c.
References cms_DigestAlgorithm_init_bio().
Referenced by CMS_dataInit().