crypto/cms/cms_io.c File Reference
cms_io.c File Reference
#include <openssl/asn1t.h>
#include <openssl/x509.h>
#include <openssl/err.h>
#include <openssl/pem.h>
#include <openssl/cms.h>
#include "cms_lcl.h"
Functions
int CMS_stream (unsigned char ***boundary, CMS_ContentInfo *cms)
CMS_ContentInfo * d2i_CMS_bio (BIO *bp, CMS_ContentInfo **cms)
int i2d_CMS_bio (BIO *bp, CMS_ContentInfo *cms)
IMPLEMENT_PEM_rw_const (CMS, CMS_ContentInfo, PEM_STRING_CMS, CMS_ContentInfo)
int i2d_CMS_bio_stream (BIO *out, CMS_ContentInfo *cms, BIO *in, int flags)
int PEM_write_bio_CMS_stream (BIO *out, CMS_ContentInfo *cms, BIO *in, int flags)
int SMIME_write_CMS (BIO *bio, CMS_ContentInfo *cms, BIO *data, int flags)
CMS_ContentInfo * SMIME_read_CMS (BIO *bio, BIO **bcont)
Function Documentation
CMS_stream()
int CMS_stream (unsigned char *** boundary, CMS_ContentInfo * cms)
Definition at line 17 of file cms_io.c.
References ASN1_STRING_FLAG_CONT, ASN1_STRING_FLAG_NDEF, CMS_F_CMS_STREAM, CMS_get0_content(), CMSerr, ERR_R_MALLOC_FAILURE, and NULL.
d2i_CMS_bio()
CMS_ContentInfo* d2i_CMS_bio (BIO * bp, CMS_ContentInfo ** cms)
Definition at line 35 of file cms_io.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
i2d_CMS_bio()
int i2d_CMS_bio (BIO * bp, CMS_ContentInfo * cms)
Definition at line 40 of file cms_io.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_CMS_bio_stream()
int i2d_CMS_bio_stream (BIO * out, CMS_ContentInfo * cms, BIO * in, int flags)
Definition at line 55 of file cms_io.c.
IMPLEMENT_PEM_rw_const()
IMPLEMENT_PEM_rw_const (CMS , CMS_ContentInfo , PEM_STRING_CMS , CMS_ContentInfo)
Definition at line 45 of file cms_io.c.
PEM_write_bio_CMS_stream()
int PEM_write_bio_CMS_stream (BIO * out, CMS_ContentInfo * cms, BIO * in, int flags)
Definition at line 61 of file cms_io.c.
SMIME_read_CMS()
CMS_ContentInfo* SMIME_read_CMS (BIO * bio, BIO ** bcont)
Definition at line 83 of file cms_io.c.
References ASN1_ITEM_rptr, and SMIME_read_ASN1().
SMIME_write_CMS()
int SMIME_write_CMS (BIO * bio, CMS_ContentInfo * cms, BIO * data, int flags)
Definition at line 68 of file cms_io.c.
References ASN1_ITEM_rptr, CMS_get0_eContentType(), NID_pkcs7_signed, NULL, OBJ_obj2nid(), SMIME_write_ASN1(), and STACK_OF.