crypto/cms/cms_sd.c File Reference
cms_sd.c File Reference
#include "internal/cryptlib.h"
#include <openssl/asn1t.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/err.h>
#include <openssl/cms.h>
#include "cms_lcl.h"
#include "internal/asn1_int.h"
#include "internal/evp_int.h"
Functions
int CMS_SignedData_init (CMS_ContentInfo *cms)
int cms_set1_SignerIdentifier (CMS_SignerIdentifier *sid, X509 *cert, int type)
int cms_SignerIdentifier_get0_signer_id (CMS_SignerIdentifier *sid, ASN1_OCTET_STRING **keyid, X509_NAME **issuer, ASN1_INTEGER **sno)
int cms_SignerIdentifier_cert_cmp (CMS_SignerIdentifier *sid, X509 *cert)
CMS_SignerInfo * CMS_add1_signer (CMS_ContentInfo *cms, X509 *signer, EVP_PKEY *pk, const EVP_MD *md, unsigned int flags)
EVP_PKEY_CTX * CMS_SignerInfo_get0_pkey_ctx (CMS_SignerInfo *si)
EVP_MD_CTX * CMS_SignerInfo_get0_md_ctx (CMS_SignerInfo *si)
STACK_OF (CMS_SignerInfo)
STACK_OF (X509)
void CMS_SignerInfo_set1_signer_cert (CMS_SignerInfo *si, X509 *signer)
int CMS_SignerInfo_get0_signer_id (CMS_SignerInfo *si, ASN1_OCTET_STRING **keyid, X509_NAME **issuer, ASN1_INTEGER **sno)
int CMS_SignerInfo_cert_cmp (CMS_SignerInfo *si, X509 *cert)
int CMS_set1_signers_certs (CMS_ContentInfo *cms, STACK_OF(X509) *scerts, unsigned int flags)
void CMS_SignerInfo_get0_algs (CMS_SignerInfo *si, EVP_PKEY **pk, X509 **signer, X509_ALGOR **pdig, X509_ALGOR **psig)
ASN1_OCTET_STRING * CMS_SignerInfo_get0_signature (CMS_SignerInfo *si)
int cms_SignedData_final (CMS_ContentInfo *cms, BIO *chain)
int CMS_SignerInfo_sign (CMS_SignerInfo *si)
int CMS_SignerInfo_verify (CMS_SignerInfo *si)
BIO * cms_SignedData_init_bio (CMS_ContentInfo *cms)
int CMS_SignerInfo_verify_content (CMS_SignerInfo *si, BIO *chain)
int CMS_add_smimecap (CMS_SignerInfo *si, STACK_OF(X509_ALGOR) *algs)
int CMS_add_simple_smimecap (STACK_OF(X509_ALGOR) **algs, int algnid, int keysize)
int CMS_add_standard_smimecap (STACK_OF(X509_ALGOR) **smcap)
Function Documentation
CMS_add1_signer()
CMS_SignerInfo* CMS_add1_signer (CMS_ContentInfo * cms, X509 * signer, EVP_PKEY * pk, const EVP_MD * md, unsigned int flags)
Definition at line 220 of file cms_sd.c.
Referenced by CMS_sign(), and CMS_sign_receipt().
CMS_add_simple_smimecap()
int CMS_add_simple_smimecap (STACK_OF(X509_ALGOR) ** algs, int algnid, int keysize)
Definition at line 865 of file cms_sd.c.
References ASN1_INTEGER_set(), key, NULL, OBJ_nid2obj(), V_ASN1_INTEGER, V_ASN1_UNDEF, and X509_ALGOR_set0().
CMS_add_smimecap()
int CMS_add_smimecap (CMS_SignerInfo * si, STACK_OF(X509_ALGOR) * algs)
Definition at line 852 of file cms_sd.c.
References CMS_signed_add1_attr_by_NID(), NID_SMIMECapabilities, NULL, OPENSSL_free, and V_ASN1_SEQUENCE.
CMS_add_standard_smimecap()
int CMS_add_standard_smimecap (STACK_OF(X509_ALGOR) ** smcap)
Definition at line 908 of file cms_sd.c.
cms_set1_SignerIdentifier()
int cms_set1_SignerIdentifier (CMS_SignerIdentifier * sid, X509 * cert, int type)
Definition at line 151 of file cms_sd.c.
CMS_set1_signers_certs()
int CMS_set1_signers_certs (CMS_ContentInfo * cms, STACK_OF(X509) * scerts, unsigned int flags)
Definition at line 468 of file cms_sd.c.
References STACK_OF().
cms_SignedData_final()
int cms_SignedData_final (CMS_ContentInfo * cms, BIO * chain)
Definition at line 620 of file cms_sd.c.
References STACK_OF().
Referenced by CMS_dataFinal().
CMS_SignedData_init()
int CMS_SignedData_init (CMS_ContentInfo * cms)
Definition at line 53 of file cms_sd.c.
Referenced by CMS_sign().
cms_SignedData_init_bio()
BIO* cms_SignedData_init_bio (CMS_ContentInfo * cms)
Definition at line 747 of file cms_sd.c.
References NULL.
Referenced by CMS_dataInit().
cms_SignerIdentifier_cert_cmp()
int cms_SignerIdentifier_cert_cmp (CMS_SignerIdentifier * sid, X509 * cert)
Definition at line 192 of file cms_sd.c.
cms_SignerIdentifier_get0_signer_id()
int cms_SignerIdentifier_get0_signer_id (CMS_SignerIdentifier * sid, ASN1_OCTET_STRING ** keyid, X509_NAME ** issuer, ASN1_INTEGER ** sno)
Definition at line 174 of file cms_sd.c.
References CMS_SIGNERINFO_ISSUER_SERIAL, and CMS_SIGNERINFO_KEYIDENTIFIER.
Referenced by CMS_RecipientInfo_ktri_get0_signer_id(), and CMS_SignerInfo_get0_signer_id().
CMS_SignerInfo_cert_cmp()
int CMS_SignerInfo_cert_cmp (CMS_SignerInfo * si, X509 * cert)
Definition at line 463 of file cms_sd.c.
CMS_SignerInfo_get0_algs()
void CMS_SignerInfo_get0_algs (CMS_SignerInfo * si, EVP_PKEY ** pk, X509 ** signer, X509_ALGOR ** pdig, X509_ALGOR ** psig)
Definition at line 514 of file cms_sd.c.
CMS_SignerInfo_get0_md_ctx()
EVP_MD_CTX* CMS_SignerInfo_get0_md_ctx (CMS_SignerInfo * si)
Definition at line 407 of file cms_sd.c.
CMS_SignerInfo_get0_pkey_ctx()
EVP_PKEY_CTX* CMS_SignerInfo_get0_pkey_ctx (CMS_SignerInfo * si)
Definition at line 402 of file cms_sd.c.
CMS_SignerInfo_get0_signature()
ASN1_OCTET_STRING* CMS_SignerInfo_get0_signature (CMS_SignerInfo * si)
Definition at line 528 of file cms_sd.c.
CMS_SignerInfo_get0_signer_id()
int CMS_SignerInfo_get0_signer_id (CMS_SignerInfo * si, ASN1_OCTET_STRING ** keyid, X509_NAME ** issuer, ASN1_INTEGER ** sno)
Definition at line 456 of file cms_sd.c.
References cms_SignerIdentifier_get0_signer_id().
CMS_SignerInfo_set1_signer_cert()
void CMS_SignerInfo_set1_signer_cert (CMS_SignerInfo * si, X509 * signer)
Definition at line 445 of file cms_sd.c.
References EVP_PKEY_free(), X509_get_pubkey(), and X509_up_ref().
CMS_SignerInfo_sign()
int CMS_SignerInfo_sign (CMS_SignerInfo * si)
Definition at line 635 of file cms_sd.c.
CMS_SignerInfo_verify()
int CMS_SignerInfo_verify (CMS_SignerInfo * si)
Definition at line 702 of file cms_sd.c.
References NULL.
CMS_SignerInfo_verify_content()
int CMS_SignerInfo_verify_content (CMS_SignerInfo * si, BIO * chain)
Definition at line 775 of file cms_sd.c.
References cms_DigestAlgorithm_find_ctx(), CMS_F_CMS_SIGNERINFO_VERIFY_CONTENT, CMS_R_ERROR_READING_MESSAGEDIGEST_ATTRIBUTE, CMS_R_MESSAGEDIGEST_ATTRIBUTE_WRONG_LENGTH, CMS_R_UNABLE_TO_FINALIZE_CONTEXT, CMS_R_VERIFICATION_FAILURE, CMS_signed_get0_data_by_OBJ(), CMS_signed_get_attr_count(), CMSerr, ERR_R_MALLOC_FAILURE, EVP_DigestFinal_ex(), EVP_MAX_MD_SIZE, EVP_MD_CTX_new(), NID_pkcs9_messageDigest, NULL, OBJ_nid2obj(), and V_ASN1_OCTET_STRING.
STACK_OF() [1/2]
STACK_OF (CMS_SignerInfo)
Definition at line 412 of file cms_sd.c.
Referenced by CMS_set1_signers_certs(), cms_SignedData_final(), and STACK_OF().
STACK_OF() [2/2]
STACK_OF (X509)
Definition at line 421 of file cms_sd.c.
References NULL, and STACK_OF().