crypto/comp/comp_lib.c File Reference
comp_lib.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <openssl/objects.h>
#include <openssl/comp.h>
#include "comp_lcl.h"
Functions
COMP_CTX * COMP_CTX_new (COMP_METHOD *meth)
const COMP_METHOD * COMP_CTX_get_method (const COMP_CTX *ctx)
int COMP_get_type (const COMP_METHOD *meth)
const char * COMP_get_name (const COMP_METHOD *meth)
void COMP_CTX_free (COMP_CTX *ctx)
int COMP_compress_block (COMP_CTX *ctx, unsigned char *out, int olen, unsigned char *in, int ilen)
int COMP_expand_block (COMP_CTX *ctx, unsigned char *out, int olen, unsigned char *in, int ilen)
int COMP_CTX_get_type (const COMP_CTX *comp)
Function Documentation
COMP_compress_block()
int COMP_compress_block (COMP_CTX * ctx, unsigned char * out, int olen, unsigned char * in, int ilen)
Definition at line 57 of file comp_lib.c.
Referenced by ssl3_do_compress().
COMP_CTX_free()
void COMP_CTX_free (COMP_CTX * ctx)
Definition at line 46 of file comp_lib.c.
References NULL, and OPENSSL_free.
Referenced by ssl_clear_cipher_ctx().
COMP_CTX_get_method()
const COMP_METHOD* COMP_CTX_get_method (const COMP_CTX * ctx)
Definition at line 31 of file comp_lib.c.
Referenced by SSL_get_current_compression(), and SSL_get_current_expansion().
COMP_CTX_get_type()
int COMP_CTX_get_type (const COMP_CTX * comp)
Definition at line 88 of file comp_lib.c.
References NID_undef.
COMP_CTX_new()
COMP_CTX* COMP_CTX_new (COMP_METHOD * meth)
Definition at line 17 of file comp_lib.c.
COMP_expand_block()
int COMP_expand_block (COMP_CTX * ctx, unsigned char * out, int olen, unsigned char * in, int ilen)
Definition at line 72 of file comp_lib.c.
Referenced by ssl3_do_uncompress().
COMP_get_name()
const char* COMP_get_name (const COMP_METHOD * meth)
Definition at line 41 of file comp_lib.c.
Referenced by SSL_COMP_get_name().
COMP_get_type()
int COMP_get_type (const COMP_METHOD * meth)
Definition at line 36 of file comp_lib.c.
Referenced by SSL_COMP_add_compression_method().