crypto/conf/conf_mod.c File Reference
conf_mod.c File Reference
#include <stdio.h>
#include <ctype.h>
#include <openssl/crypto.h>
#include "internal/cryptlib.h"
#include "internal/conf.h"
#include "internal/dso.h"
#include <openssl/x509.h>
Data Structures
struct CONF_MODULE
struct CONF_IMODULE
Macros
#define DSO_mod_init_name "OPENSSL_init"
#define DSO_mod_finish_name "OPENSSL_finish"
Functions
int CONF_modules_load_file (const char *filename, const char *appname, unsigned long flags)
void CONF_modules_unload (int all)
void CONF_modules_finish (void)
int CONF_module_add (const char *name, conf_init_func *ifunc, conf_finish_func *ffunc)
void conf_modules_free_int (void)
const char * CONF_imodule_get_name (const CONF_IMODULE *md)
const char * CONF_imodule_get_value (const CONF_IMODULE *md)
void * CONF_imodule_get_usr_data (const CONF_IMODULE *md)
void CONF_imodule_set_usr_data (CONF_IMODULE *md, void *usr_data)
CONF_MODULE * CONF_imodule_get_module (const CONF_IMODULE *md)
unsigned long CONF_imodule_get_flags (const CONF_IMODULE *md)
void CONF_imodule_set_flags (CONF_IMODULE *md, unsigned long flags)
void * CONF_module_get_usr_data (CONF_MODULE *pmod)
void CONF_module_set_usr_data (CONF_MODULE *pmod, void *usr_data)
char * CONF_get1_default_config_file (void)
int CONF_parse_list (const char *list_, int sep, int nospc, int(*list_cb)(const char *elem, int len, void *usr), void *arg)
Macro Definition Documentation
DSO_mod_finish_name
#define DSO_mod_finish_name "OPENSSL_finish"
Definition at line 19 of file conf_mod.c.
DSO_mod_init_name
#define DSO_mod_init_name "OPENSSL_init"
Definition at line 18 of file conf_mod.c.
Function Documentation
CONF_get1_default_config_file()
char* CONF_get1_default_config_file (void)
Definition at line 476 of file conf_mod.c.
References file, len, NULL, OPENSSL_CONF, OPENSSL_malloc, OPENSSL_strdup, OPENSSL_strlcat(), OPENSSL_strlcpy(), and X509_get_default_cert_area().
CONF_imodule_get_flags()
unsigned long CONF_imodule_get_flags (const CONF_IMODULE * md)
Definition at line 454 of file conf_mod.c.
CONF_imodule_get_module()
CONF_MODULE* CONF_imodule_get_module (const CONF_IMODULE * md)
Definition at line 449 of file conf_mod.c.
CONF_imodule_get_name()
const char* CONF_imodule_get_name (const CONF_IMODULE * md)
Definition at line 429 of file conf_mod.c.
CONF_imodule_get_usr_data()
void* CONF_imodule_get_usr_data (const CONF_IMODULE * md)
Definition at line 439 of file conf_mod.c.
CONF_imodule_get_value()
const char* CONF_imodule_get_value (const CONF_IMODULE * md)
Definition at line 434 of file conf_mod.c.
CONF_imodule_set_flags()
void CONF_imodule_set_flags (CONF_IMODULE * md, unsigned long flags)
Definition at line 459 of file conf_mod.c.
References flags.
CONF_imodule_set_usr_data()
void CONF_imodule_set_usr_data (CONF_IMODULE * md, void * usr_data)
Definition at line 444 of file conf_mod.c.
References CONF_MODULE::usr_data.
CONF_module_add()
int CONF_module_add (const char * name, conf_init_func * ifunc, conf_finish_func * ffunc)
Definition at line 412 of file conf_mod.c.
Referenced by ASN1_add_oid_module(), ASN1_add_stable_module(), ENGINE_add_conf_module(), EVP_add_alg_module(), and SSL_add_ssl_module().
CONF_module_get_usr_data()
void* CONF_module_get_usr_data (CONF_MODULE * pmod)
Definition at line 464 of file conf_mod.c.
CONF_module_set_usr_data()
void CONF_module_set_usr_data (CONF_MODULE * pmod, void * usr_data)
Definition at line 469 of file conf_mod.c.
References CONF_MODULE::usr_data.
CONF_modules_finish()
void CONF_modules_finish (void)
Definition at line 385 of file conf_mod.c.
Referenced by conf_modules_free_int().
conf_modules_free_int()
void conf_modules_free_int (void)
Definition at line 421 of file conf_mod.c.
References CONF_modules_finish(), and CONF_modules_unload().
CONF_modules_load_file()
int CONF_modules_load_file (const char * filename, const char * appname, unsigned long flags)
Definition at line 112 of file conf_mod.c.
References file, and NULL.
CONF_modules_unload()
void CONF_modules_unload (int all)
Definition at line 354 of file conf_mod.c.
Referenced by conf_modules_free_int().
CONF_parse_list()
int CONF_parse_list (const char * list_, int sep, int nospc, int(*)(const char *elem, int len, void *usr) list_cb, void * arg)
Definition at line 511 of file conf_mod.c.
Referenced by ASN1_str2mask(), ENGINE_set_default_string(), and tls1_set_groups_list().