crypto/conf/conf_lib.c File Reference
conf_lib.c File Reference
#include <stdio.h>
#include <string.h>
#include <internal/conf.h>
#include <openssl/crypto.h>
#include <openssl/err.h>
#include <openssl/conf.h>
#include <openssl/conf_api.h>
#include <openssl/lhash.h>
#include "e_os.h"
Functions
void CONF_set_nconf (CONF *conf, LHASH_OF(CONF_VALUE) *hash)
int CONF_set_default_method (CONF_METHOD *meth)
LHASH_OF (CONF_VALUE)
STACK_OF (CONF_VALUE)
char * CONF_get_string (LHASH_OF(CONF_VALUE) *conf, const char *group, const char *name)
long CONF_get_number (LHASH_OF(CONF_VALUE) *conf, const char *group, const char *name)
void CONF_free (LHASH_OF(CONF_VALUE) *conf)
int CONF_dump_fp (LHASH_OF(CONF_VALUE) *conf, FILE *out)
int CONF_dump_bio (LHASH_OF(CONF_VALUE) *conf, BIO *out)
CONF * NCONF_new (CONF_METHOD *meth)
void NCONF_free (CONF *conf)
void NCONF_free_data (CONF *conf)
int NCONF_load (CONF *conf, const char *file, long *eline)
int NCONF_load_fp (CONF *conf, FILE *fp, long *eline)
int NCONF_load_bio (CONF *conf, BIO *bp, long *eline)
char * NCONF_get_string (const CONF *conf, const char *group, const char *name)
int NCONF_get_number_e (const CONF *conf, const char *group, const char *name, long *result)
int NCONF_dump_fp (const CONF *conf, FILE *out)
int NCONF_dump_bio (const CONF *conf, BIO *out)
OPENSSL_INIT_SETTINGS * OPENSSL_INIT_new (void)
int OPENSSL_INIT_set_config_appname (OPENSSL_INIT_SETTINGS *settings, const char *appname)
void OPENSSL_INIT_free (OPENSSL_INIT_SETTINGS *settings)
Function Documentation
CONF_dump_bio()
int CONF_dump_bio (LHASH_OF(CONF_VALUE) * conf, BIO * out)
Definition at line 164 of file conf_lib.c.
CONF_dump_fp()
int CONF_dump_fp (LHASH_OF(CONF_VALUE) * conf, FILE * out)
Definition at line 149 of file conf_lib.c.
CONF_free()
void CONF_free (LHASH_OF(CONF_VALUE) * conf)
Definition at line 141 of file conf_lib.c.
References CONF_set_nconf(), and NCONF_free_data().
CONF_get_number()
long CONF_get_number (LHASH_OF(CONF_VALUE) * conf, const char * group, const char * name)
Definition at line 120 of file conf_lib.c.
References CONF_set_nconf(), ERR_clear_error(), NCONF_get_number_e(), and NULL.
CONF_get_string()
char* CONF_get_string (LHASH_OF(CONF_VALUE) * conf, const char * group, const char * name)
Definition at line 108 of file conf_lib.c.
References CONF_set_nconf(), NCONF_get_string(), and NULL.
CONF_set_default_method()
int CONF_set_default_method (CONF_METHOD * meth)
Definition at line 38 of file conf_lib.c.
CONF_set_nconf()
void CONF_set_nconf (CONF * conf, LHASH_OF(CONF_VALUE) * hash)
Definition at line 24 of file conf_lib.c.
Referenced by CONF_free(), CONF_get_number(), CONF_get_string(), STACK_OF(), X509V3_EXT_conf(), X509V3_EXT_conf_nid(), X509V3_EXT_CRL_add_conf(), and X509V3_EXT_REQ_add_conf().
LHASH_OF()
LHASH_OF (CONF_VALUE)
Definition at line 44 of file conf_lib.c.
References BIO_free(), BIO_new_file(), BIO_new_fp(), BIO_NOCLOSE, bp, CONF_F_CONF_LOAD, CONF_F_CONF_LOAD_FP, CONFerr, eline, ERR_R_BUF_LIB, ERR_R_SYS_LIB, fp, in, and NULL.
NCONF_dump_bio()
int NCONF_dump_bio (const CONF * conf, BIO * out)
Definition at line 318 of file conf_lib.c.
NCONF_dump_fp()
int NCONF_dump_fp (const CONF * conf, FILE * out)
Definition at line 304 of file conf_lib.c.
NCONF_free()
void NCONF_free (CONF * conf)
Definition at line 195 of file conf_lib.c.
References NULL.
NCONF_free_data()
void NCONF_free_data (CONF * conf)
Definition at line 202 of file conf_lib.c.
References NULL.
Referenced by CONF_free().
NCONF_get_number_e()
int NCONF_get_number_e (const CONF * conf, const char * group, const char * name, long * result)
Definition at line 280 of file conf_lib.c.
References CONF_F_NCONF_GET_NUMBER_E, CONFerr, ERR_R_PASSED_NULL_PARAMETER, NCONF_get_string(), and NULL.
Referenced by CONF_get_number().
NCONF_get_string()
char* NCONF_get_string (const CONF * conf, const char * group, const char * name)
Definition at line 259 of file conf_lib.c.
References _CONF_get_string(), CONF_F_NCONF_GET_STRING, CONF_R_NO_CONF_OR_ENVIRONMENT_VARIABLE, CONF_R_NO_VALUE, CONFerr, ERR_add_error_data(), and NULL.
Referenced by CONF_get_string(), and NCONF_get_number_e().
NCONF_load()
int NCONF_load (CONF * conf, const char * file, long * eline)
Definition at line 209 of file conf_lib.c.
References CONF_F_NCONF_LOAD, CONF_R_NO_CONF, CONFerr, and NULL.
NCONF_load_bio()
int NCONF_load_bio (CONF * conf, BIO * bp, long * eline)
Definition at line 234 of file conf_lib.c.
References CONF_F_NCONF_GET_SECTION, CONF_F_NCONF_LOAD_BIO, CONF_R_NO_CONF, CONF_R_NO_SECTION, CONFerr, NULL, section, and STACK_OF().
NCONF_load_fp()
int NCONF_load_fp (CONF * conf, FILE * fp, long * eline)
Definition at line 220 of file conf_lib.c.
NCONF_new()
CONF* NCONF_new (CONF_METHOD * meth)
Definition at line 179 of file conf_lib.c.
OPENSSL_INIT_free()
void OPENSSL_INIT_free (OPENSSL_INIT_SETTINGS * settings)
Definition at line 361 of file conf_lib.c.
OPENSSL_INIT_new()
OPENSSL_INIT_SETTINGS* OPENSSL_INIT_new (void)
Definition at line 332 of file conf_lib.c.
OPENSSL_INIT_set_config_appname()
int OPENSSL_INIT_set_config_appname (OPENSSL_INIT_SETTINGS * settings, const char * appname)
Definition at line 343 of file conf_lib.c.
STACK_OF()
STACK_OF (CONF_VALUE)
Definition at line 96 of file conf_lib.c.
References CONF_set_nconf(), and NULL.
Referenced by NCONF_load_bio().