crypto/conf/conf_api.c File Reference
conf_api.c File Reference
#include <stdlib.h>
#include <string.h>
#include <openssl/conf.h>
#include <openssl/conf_api.h>
#include "e_os.h"
Functions
CONF_VALUE * _CONF_get_section (const CONF *conf, const char *section)
STACK_OF (CONF_VALUE)
int _CONF_add_string (CONF *conf, CONF_VALUE *section, CONF_VALUE *value)
char * _CONF_get_string (const CONF *conf, const char *section, const char *name)
int _CONF_new_data (CONF *conf)
typedef LHASH_OF (IMPLEMENT_LHASH_DOALL_ARG_CONST(CONF_VALUE)
CONF_VALUE * _CONF_new_section (CONF *conf, const char *section)
Function Documentation
_CONF_add_string()
int _CONF_add_string (CONF * conf, CONF_VALUE * section, CONF_VALUE * value)
Definition at line 47 of file conf_api.c.
_CONF_get_section()
CONF_VALUE* _CONF_get_section (const CONF * conf, const char * section)
Definition at line 22 of file conf_api.c.
_CONF_get_string()
char* _CONF_get_string (const CONF * conf, const char * section, const char * name)
Definition at line 69 of file conf_api.c.
Referenced by NCONF_get_string().
_CONF_new_data()
int _CONF_new_data (CONF * conf)
Definition at line 125 of file conf_api.c.
_CONF_new_section()
CONF_VALUE* _CONF_new_section (CONF * conf, const char * section)
Definition at line 188 of file conf_api.c.
References CONF_VALUE::name, NULL, OPENSSL_assert, OPENSSL_free, OPENSSL_malloc, CONF_VALUE::section, STACK_OF(), and CONF_VALUE::value.
LHASH_OF()
typedef LHASH_OF (IMPLEMENT_LHASH_DOALL_ARG_CONST(CONF_VALUE)
Definition at line 138 of file conf_api.c.
STACK_OF()
STACK_OF (CONF_VALUE)
Definition at line 35 of file conf_api.c.
Referenced by _CONF_new_section().