crypto/cryptlib.c File Reference
cryptlib.c File Reference
#include "internal/cryptlib_int.h"
#include <openssl/safestack.h>
Functions
void OPENSSL_cpuid_setup (void)
void OPENSSL_showfatal (const char *fmta,...)
int OPENSSL_isservice (void)
void OPENSSL_die (const char *message, const char *file, int line)
int CRYPTO_memcmp (const volatile void *volatile in_a, const volatile void *volatile in_b, size_t len)
Variables
int OPENSSL_NONPIC_relocated = 0
Function Documentation
CRYPTO_memcmp()
int CRYPTO_memcmp (const volatile void *volatile in_a, const volatile void *volatile in_b, size_t len)
Definition at line 327 of file cryptlib.c.
Referenced by CRYPTO_gcm128_finish(), and CRYPTO_ocb128_finish().
OPENSSL_cpuid_setup()
void OPENSSL_cpuid_setup (void)
Definition at line 82 of file cryptlib.c.
References h, len, NULL, OPENSSL_isservice(), and OPENSSL_showfatal().
OPENSSL_die()
void OPENSSL_die (const char * message, const char * file, int line)
Definition at line 292 of file cryptlib.c.
References OPENSSL_showfatal().
OPENSSL_isservice()
int OPENSSL_isservice (void)
Definition at line 286 of file cryptlib.c.
Referenced by OPENSSL_cpuid_setup().
OPENSSL_showfatal()
void OPENSSL_showfatal (const char * fmta, ...)
Definition at line 275 of file cryptlib.c.
Referenced by OPENSSL_cpuid_setup(), and OPENSSL_die().
Variable Documentation
OPENSSL_NONPIC_relocated
int OPENSSL_NONPIC_relocated = 0
Definition at line 80 of file cryptlib.c.