crypto/cms/cms_enc.c File Reference
cms_enc.c File Reference
#include "internal/cryptlib.h"
#include <openssl/asn1t.h>
#include <openssl/pem.h>
#include <openssl/x509v3.h>
#include <openssl/err.h>
#include <openssl/cms.h>
#include <openssl/rand.h>
#include "cms_lcl.h"
Functions
BIO * cms_EncryptedContent_init_bio (CMS_EncryptedContentInfo *ec)
int cms_EncryptedContent_init (CMS_EncryptedContentInfo *ec, const EVP_CIPHER *cipher, const unsigned char *key, size_t keylen)
int CMS_EncryptedData_set1_key (CMS_ContentInfo *cms, const EVP_CIPHER *ciph, const unsigned char *key, size_t keylen)
BIO * cms_EncryptedData_init_bio (CMS_ContentInfo *cms)
Function Documentation
cms_EncryptedContent_init()
int cms_EncryptedContent_init (CMS_EncryptedContentInfo * ec, const EVP_CIPHER * cipher, const unsigned char * key, size_t keylen)
Definition at line 165 of file cms_enc.c.
Referenced by CMS_EncryptedData_set1_key().
cms_EncryptedContent_init_bio()
BIO* cms_EncryptedContent_init_bio (CMS_EncryptedContentInfo * ec)
Definition at line 23 of file cms_enc.c.
References ctx.
Referenced by cms_EncryptedData_init_bio().
cms_EncryptedData_init_bio()
BIO* cms_EncryptedData_init_bio (CMS_ContentInfo * cms)
Definition at line 206 of file cms_enc.c.
References cms_EncryptedContent_init_bio().
Referenced by CMS_dataInit().
CMS_EncryptedData_set1_key()
int CMS_EncryptedData_set1_key (CMS_ContentInfo * cms, const EVP_CIPHER * ciph, const unsigned char * key, size_t keylen)
Definition at line 182 of file cms_enc.c.
References cms_EncryptedContent_init(), CMS_F_CMS_ENCRYPTEDDATA_SET1_KEY, CMS_R_NO_KEY, CMS_R_NOT_ENCRYPTED_DATA, CMSerr, ERR_R_MALLOC_FAILURE, M_ASN1_new_of, NID_pkcs7_encrypted, OBJ_nid2obj(), and OBJ_obj2nid().