crypto/include/internal/async.h File Reference
async.h File Reference
#include <openssl/async.h>
Functions
int async_init (void)
void async_deinit (void)
Function Documentation
async_deinit()
void async_deinit (void)
Definition at line 310 of file async.c.
References CRYPTO_THREAD_cleanup_local().
async_init()
int async_init (void)
Definition at line 297 of file async.c.
References CRYPTO_THREAD_init_local().
Referenced by DEFINE_RUN_ONCE_STATIC().