include/openssl/ct.h File Reference
ct.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/ossl_typ.h>
#include <openssl/safestack.h>
#include <openssl/x509.h>
Macros
#define SCT_MIN_RSA_BITS 2048
#define CT_V1_HASHLEN SHA256_DIGEST_LENGTH
#define CT_F_CTLOG_NEW 117
#define CT_F_CTLOG_NEW_FROM_BASE64 118
#define CT_F_CTLOG_NEW_FROM_CONF 119
#define CT_F_CTLOG_STORE_LOAD_CTX_NEW 122
#define CT_F_CTLOG_STORE_LOAD_FILE 123
#define CT_F_CTLOG_STORE_LOAD_LOG 130
#define CT_F_CTLOG_STORE_NEW 131
#define CT_F_CT_BASE64_DECODE 124
#define CT_F_CT_POLICY_EVAL_CTX_NEW 133
#define CT_F_CT_V1_LOG_ID_FROM_PKEY 125
#define CT_F_I2O_SCT 107
#define CT_F_I2O_SCT_LIST 108
#define CT_F_I2O_SCT_SIGNATURE 109
#define CT_F_O2I_SCT 110
#define CT_F_O2I_SCT_LIST 111
#define CT_F_O2I_SCT_SIGNATURE 112
#define CT_F_SCT_CTX_NEW 126
#define CT_F_SCT_CTX_VERIFY 128
#define CT_F_SCT_NEW 100
#define CT_F_SCT_NEW_FROM_BASE64 127
#define CT_F_SCT_SET0_LOG_ID 101
#define CT_F_SCT_SET1_EXTENSIONS 114
#define CT_F_SCT_SET1_LOG_ID 115
#define CT_F_SCT_SET1_SIGNATURE 116
#define CT_F_SCT_SET_LOG_ENTRY_TYPE 102
#define CT_F_SCT_SET_SIGNATURE_NID 103
#define CT_F_SCT_SET_VERSION 104
#define CT_R_BASE64_DECODE_ERROR 108
#define CT_R_INVALID_LOG_ID_LENGTH 100
#define CT_R_LOG_CONF_INVALID 109
#define CT_R_LOG_CONF_INVALID_KEY 110
#define CT_R_LOG_CONF_MISSING_DESCRIPTION 111
#define CT_R_LOG_CONF_MISSING_KEY 112
#define CT_R_LOG_KEY_INVALID 113
#define CT_R_SCT_FUTURE_TIMESTAMP 116
#define CT_R_SCT_INVALID 104
#define CT_R_SCT_INVALID_SIGNATURE 107
#define CT_R_SCT_LIST_INVALID 105
#define CT_R_SCT_LOG_ID_MISMATCH 114
#define CT_R_SCT_NOT_SET 106
#define CT_R_SCT_UNSUPPORTED_VERSION 115
#define CT_R_UNRECOGNIZED_SIGNATURE_NID 101
#define CT_R_UNSUPPORTED_ENTRY_TYPE 102
#define CT_R_UNSUPPORTED_VERSION 103
Enumerations
enum ct_log_entry_type_t { CT_LOG_ENTRY_TYPE_NOT_SET = -1, CT_LOG_ENTRY_TYPE_X509 = 0, CT_LOG_ENTRY_TYPE_PRECERT = 1 }
enum sct_version_t { SCT_VERSION_NOT_SET = -1, SCT_VERSION_V1 = 0 }
enum sct_source_t { SCT_SOURCE_UNKNOWN, SCT_SOURCE_TLS_EXTENSION, SCT_SOURCE_X509V3_EXTENSION, SCT_SOURCE_OCSP_STAPLED_RESPONSE }
enum sct_validation_status_t {
SCT_VALIDATION_STATUS_NOT_SET, SCT_VALIDATION_STATUS_UNKNOWN_LOG, SCT_VALIDATION_STATUS_VALID, SCT_VALIDATION_STATUS_INVALID,
SCT_VALIDATION_STATUS_UNVERIFIED, SCT_VALIDATION_STATUS_UNKNOWN_VERSION
}
Functions
CT_POLICY_EVAL_CTX * CT_POLICY_EVAL_CTX_new (void)
void CT_POLICY_EVAL_CTX_free (CT_POLICY_EVAL_CTX *ctx)
X509 * CT_POLICY_EVAL_CTX_get0_cert (const CT_POLICY_EVAL_CTX *ctx)
int CT_POLICY_EVAL_CTX_set1_cert (CT_POLICY_EVAL_CTX *ctx, X509 *cert)
X509 * CT_POLICY_EVAL_CTX_get0_issuer (const CT_POLICY_EVAL_CTX *ctx)
int CT_POLICY_EVAL_CTX_set1_issuer (CT_POLICY_EVAL_CTX *ctx, X509 *issuer)
const CTLOG_STORE * CT_POLICY_EVAL_CTX_get0_log_store (const CT_POLICY_EVAL_CTX *ctx)
void CT_POLICY_EVAL_CTX_set_shared_CTLOG_STORE (CT_POLICY_EVAL_CTX *ctx, CTLOG_STORE *log_store)
uint64_t CT_POLICY_EVAL_CTX_get_time (const CT_POLICY_EVAL_CTX *ctx)
void CT_POLICY_EVAL_CTX_set_time (CT_POLICY_EVAL_CTX *ctx, uint64_t time_in_ms)
SCT * SCT_new (void)
SCT * SCT_new_from_base64 (unsigned char version, const char *logid_base64, ct_log_entry_type_t entry_type, uint64_t timestamp, const char *extensions_base64, const char *signature_base64)
void SCT_free (SCT *sct)
void SCT_LIST_free (STACK_OF(SCT) *a)
sct_version_t SCT_get_version (const SCT *sct)
__owur int SCT_set_version (SCT *sct, sct_version_t version)
ct_log_entry_type_t SCT_get_log_entry_type (const SCT *sct)
__owur int SCT_set_log_entry_type (SCT *sct, ct_log_entry_type_t entry_type)
size_t SCT_get0_log_id (const SCT *sct, unsigned char **log_id)
__owur int SCT_set0_log_id (SCT *sct, unsigned char *log_id, size_t log_id_len)
__owur int SCT_set1_log_id (SCT *sct, const unsigned char *log_id, size_t log_id_len)
uint64_t SCT_get_timestamp (const SCT *sct)
void SCT_set_timestamp (SCT *sct, uint64_t timestamp)
int SCT_get_signature_nid (const SCT *sct)
__owur int SCT_set_signature_nid (SCT *sct, int nid)
size_t SCT_get0_extensions (const SCT *sct, unsigned char **ext)
void SCT_set0_extensions (SCT *sct, unsigned char *ext, size_t ext_len)
__owur int SCT_set1_extensions (SCT *sct, const unsigned char *ext, size_t ext_len)
size_t SCT_get0_signature (const SCT *sct, unsigned char **sig)
void SCT_set0_signature (SCT *sct, unsigned char *sig, size_t sig_len)
__owur int SCT_set1_signature (SCT *sct, const unsigned char *sig, size_t sig_len)
sct_source_t SCT_get_source (const SCT *sct)
__owur int SCT_set_source (SCT *sct, sct_source_t source)
const char * SCT_validation_status_string (const SCT *sct)
void SCT_print (const SCT *sct, BIO *out, int indent, const CTLOG_STORE *logs)
void SCT_LIST_print (const STACK_OF(SCT) *sct_list, BIO *out, int indent, const char *separator, const CTLOG_STORE *logs)
sct_validation_status_t SCT_get_validation_status (const SCT *sct)
__owur int SCT_validate (SCT *sct, const CT_POLICY_EVAL_CTX *ctx)
__owur int SCT_LIST_validate (const STACK_OF(SCT) *scts, CT_POLICY_EVAL_CTX *ctx)
__owur int i2o_SCT_LIST (const STACK_OF(SCT) *a, unsigned char **pp)
STACK_OF (SCT) *o2i_SCT_LIST(STACK_OF(SCT) **a
__owur int i2d_SCT_LIST (const STACK_OF(SCT) *a, unsigned char **pp)
__owur int i2o_SCT (const SCT *sct, unsigned char **out)
SCT * o2i_SCT (SCT **psct, const unsigned char **in, size_t len)
CTLOG * CTLOG_new (EVP_PKEY *public_key, const char *name)
int CTLOG_new_from_base64 (CTLOG **ct_log, const char *pkey_base64, const char *name)
void CTLOG_free (CTLOG *log)
const char * CTLOG_get0_name (const CTLOG *log)
void CTLOG_get0_log_id (const CTLOG *log, const uint8_t **log_id, size_t *log_id_len)
EVP_PKEY * CTLOG_get0_public_key (const CTLOG *log)
CTLOG_STORE * CTLOG_STORE_new (void)
void CTLOG_STORE_free (CTLOG_STORE *store)
const CTLOG * CTLOG_STORE_get0_log_by_id (const CTLOG_STORE *store, const uint8_t *log_id, size_t log_id_len)
__owur int CTLOG_STORE_load_file (CTLOG_STORE *store, const char *file)
__owur int CTLOG_STORE_load_default_file (CTLOG_STORE *store)
int ERR_load_CT_strings (void)
Variables
const unsigned char ** pp
const unsigned char size_t len
Macro Definition Documentation
CT_F_CT_BASE64_DECODE
#define CT_F_CT_BASE64_DECODE 124
Definition at line 489 of file ct.h.
CT_F_CT_POLICY_EVAL_CTX_NEW
#define CT_F_CT_POLICY_EVAL_CTX_NEW 133
Definition at line 490 of file ct.h.
Referenced by CT_POLICY_EVAL_CTX_new().
CT_F_CT_V1_LOG_ID_FROM_PKEY
#define CT_F_CT_V1_LOG_ID_FROM_PKEY 125
Definition at line 491 of file ct.h.
CT_F_CTLOG_NEW
#define CT_F_CTLOG_NEW 117
Definition at line 482 of file ct.h.
Referenced by CTLOG_new().
CT_F_CTLOG_NEW_FROM_BASE64
#define CT_F_CTLOG_NEW_FROM_BASE64 118
Definition at line 483 of file ct.h.
CT_F_CTLOG_NEW_FROM_CONF
#define CT_F_CTLOG_NEW_FROM_CONF 119
Definition at line 484 of file ct.h.
CT_F_CTLOG_STORE_LOAD_CTX_NEW
#define CT_F_CTLOG_STORE_LOAD_CTX_NEW 122
Definition at line 485 of file ct.h.
CT_F_CTLOG_STORE_LOAD_FILE
#define CT_F_CTLOG_STORE_LOAD_FILE 123
Definition at line 486 of file ct.h.
CT_F_CTLOG_STORE_LOAD_LOG
#define CT_F_CTLOG_STORE_LOAD_LOG 130
Definition at line 487 of file ct.h.
CT_F_CTLOG_STORE_NEW
#define CT_F_CTLOG_STORE_NEW 131
Definition at line 488 of file ct.h.
Referenced by CTLOG_STORE_new().
CT_F_I2O_SCT
#define CT_F_I2O_SCT 107
Definition at line 492 of file ct.h.
CT_F_I2O_SCT_LIST
#define CT_F_I2O_SCT_LIST 108
Definition at line 493 of file ct.h.
Referenced by i2o_SCT_LIST().
CT_F_I2O_SCT_SIGNATURE
#define CT_F_I2O_SCT_SIGNATURE 109
Definition at line 494 of file ct.h.
CT_F_O2I_SCT
#define CT_F_O2I_SCT 110
Definition at line 495 of file ct.h.
Referenced by o2i_SCT().
CT_F_O2I_SCT_LIST
#define CT_F_O2I_SCT_LIST 111
Definition at line 496 of file ct.h.
Referenced by STACK_OF().
CT_F_O2I_SCT_SIGNATURE
#define CT_F_O2I_SCT_SIGNATURE 112
Definition at line 497 of file ct.h.
Referenced by o2i_SCT_signature().
CT_F_SCT_CTX_NEW
#define CT_F_SCT_CTX_NEW 126
Definition at line 498 of file ct.h.
Referenced by SCT_CTX_new().
CT_F_SCT_CTX_VERIFY
#define CT_F_SCT_CTX_VERIFY 128
Definition at line 499 of file ct.h.
CT_F_SCT_NEW
#define CT_F_SCT_NEW 100
Definition at line 500 of file ct.h.
Referenced by SCT_new().
CT_F_SCT_NEW_FROM_BASE64
#define CT_F_SCT_NEW_FROM_BASE64 127
Definition at line 501 of file ct.h.
Referenced by SCT_new_from_base64().
CT_F_SCT_SET0_LOG_ID
#define CT_F_SCT_SET0_LOG_ID 101
Definition at line 502 of file ct.h.
Referenced by SCT_set0_log_id().
CT_F_SCT_SET1_EXTENSIONS
#define CT_F_SCT_SET1_EXTENSIONS 114
Definition at line 503 of file ct.h.
Referenced by SCT_set1_extensions().
CT_F_SCT_SET1_LOG_ID
#define CT_F_SCT_SET1_LOG_ID 115
Definition at line 504 of file ct.h.
Referenced by SCT_set1_log_id().
CT_F_SCT_SET1_SIGNATURE
#define CT_F_SCT_SET1_SIGNATURE 116
Definition at line 505 of file ct.h.
Referenced by SCT_set1_signature().
CT_F_SCT_SET_LOG_ENTRY_TYPE
#define CT_F_SCT_SET_LOG_ENTRY_TYPE 102
Definition at line 506 of file ct.h.
Referenced by SCT_set_log_entry_type().
CT_F_SCT_SET_SIGNATURE_NID
#define CT_F_SCT_SET_SIGNATURE_NID 103
Definition at line 507 of file ct.h.
Referenced by SCT_set_signature_nid().
CT_F_SCT_SET_VERSION
#define CT_F_SCT_SET_VERSION 104
Definition at line 508 of file ct.h.
Referenced by SCT_set_version().
CT_R_BASE64_DECODE_ERROR
#define CT_R_BASE64_DECODE_ERROR 108
Definition at line 511 of file ct.h.
CT_R_INVALID_LOG_ID_LENGTH
#define CT_R_INVALID_LOG_ID_LENGTH 100
Definition at line 512 of file ct.h.
Referenced by SCT_set0_log_id(), and SCT_set1_log_id().
CT_R_LOG_CONF_INVALID
#define CT_R_LOG_CONF_INVALID 109
Definition at line 513 of file ct.h.
CT_R_LOG_CONF_INVALID_KEY
#define CT_R_LOG_CONF_INVALID_KEY 110
Definition at line 514 of file ct.h.
CT_R_LOG_CONF_MISSING_DESCRIPTION
#define CT_R_LOG_CONF_MISSING_DESCRIPTION 111
Definition at line 515 of file ct.h.
CT_R_LOG_CONF_MISSING_KEY
#define CT_R_LOG_CONF_MISSING_KEY 112
Definition at line 516 of file ct.h.
CT_R_LOG_KEY_INVALID
#define CT_R_LOG_KEY_INVALID 113
Definition at line 517 of file ct.h.
CT_R_SCT_FUTURE_TIMESTAMP
#define CT_R_SCT_FUTURE_TIMESTAMP 116
Definition at line 518 of file ct.h.
CT_R_SCT_INVALID
#define CT_R_SCT_INVALID 104
Definition at line 519 of file ct.h.
Referenced by o2i_SCT().
CT_R_SCT_INVALID_SIGNATURE
#define CT_R_SCT_INVALID_SIGNATURE 107
Definition at line 520 of file ct.h.
Referenced by o2i_SCT_signature().
CT_R_SCT_LIST_INVALID
#define CT_R_SCT_LIST_INVALID 105
Definition at line 521 of file ct.h.
Referenced by i2o_SCT_LIST(), and STACK_OF().
CT_R_SCT_LOG_ID_MISMATCH
#define CT_R_SCT_LOG_ID_MISMATCH 114
Definition at line 522 of file ct.h.
CT_R_SCT_NOT_SET
#define CT_R_SCT_NOT_SET 106
Definition at line 523 of file ct.h.
CT_R_SCT_UNSUPPORTED_VERSION
#define CT_R_SCT_UNSUPPORTED_VERSION 115
Definition at line 524 of file ct.h.
Referenced by SCT_new_from_base64().
CT_R_UNRECOGNIZED_SIGNATURE_NID
#define CT_R_UNRECOGNIZED_SIGNATURE_NID 101
Definition at line 525 of file ct.h.
Referenced by SCT_set_signature_nid().
CT_R_UNSUPPORTED_ENTRY_TYPE
#define CT_R_UNSUPPORTED_ENTRY_TYPE 102
Definition at line 526 of file ct.h.
Referenced by SCT_set_log_entry_type().
CT_R_UNSUPPORTED_VERSION
#define CT_R_UNSUPPORTED_VERSION 103
Definition at line 527 of file ct.h.
Referenced by o2i_SCT_signature(), and SCT_set_version().
CT_V1_HASHLEN
#define CT_V1_HASHLEN SHA256_DIGEST_LENGTH
Definition at line 28 of file ct.h.
Referenced by CTLOG_get0_log_id(), o2i_SCT(), SCT_set0_log_id(), and SCT_set1_log_id().
SCT_MIN_RSA_BITS
#define SCT_MIN_RSA_BITS 2048
Definition at line 25 of file ct.h.
Enumeration Type Documentation
ct_log_entry_type_t
enum ct_log_entry_type_t
Enumerator
CT_LOG_ENTRY_TYPE_NOT_SET
CT_LOG_ENTRY_TYPE_X509
CT_LOG_ENTRY_TYPE_PRECERT
Definition at line 30 of file ct.h.
sct_source_t
enum sct_source_t
Enumerator
SCT_SOURCE_UNKNOWN
SCT_SOURCE_TLS_EXTENSION
SCT_SOURCE_X509V3_EXTENSION
SCT_SOURCE_OCSP_STAPLED_RESPONSE
Definition at line 41 of file ct.h.
sct_validation_status_t
enum sct_validation_status_t
Enumerator
SCT_VALIDATION_STATUS_NOT_SET
SCT_VALIDATION_STATUS_UNKNOWN_LOG
SCT_VALIDATION_STATUS_VALID
SCT_VALIDATION_STATUS_INVALID
SCT_VALIDATION_STATUS_UNVERIFIED
SCT_VALIDATION_STATUS_UNKNOWN_VERSION
Definition at line 48 of file ct.h.
sct_version_t
enum sct_version_t
Enumerator
SCT_VERSION_NOT_SET
SCT_VERSION_V1
Definition at line 36 of file ct.h.
Function Documentation
CT_POLICY_EVAL_CTX_free()
void CT_POLICY_EVAL_CTX_free (CT_POLICY_EVAL_CTX * ctx)
Definition at line 44 of file ct_policy.c.
References NULL, and OPENSSL_free.
CT_POLICY_EVAL_CTX_get0_cert()
X509* CT_POLICY_EVAL_CTX_get0_cert (const CT_POLICY_EVAL_CTX * ctx)
Definition at line 80 of file ct_policy.c.
CT_POLICY_EVAL_CTX_get0_issuer()
X509* CT_POLICY_EVAL_CTX_get0_issuer (const CT_POLICY_EVAL_CTX * ctx)
Definition at line 85 of file ct_policy.c.
CT_POLICY_EVAL_CTX_get0_log_store()
const CTLOG_STORE* CT_POLICY_EVAL_CTX_get0_log_store (const CT_POLICY_EVAL_CTX * ctx)
Definition at line 90 of file ct_policy.c.
CT_POLICY_EVAL_CTX_get_time()
uint64_t CT_POLICY_EVAL_CTX_get_time (const CT_POLICY_EVAL_CTX * ctx)
Definition at line 95 of file ct_policy.c.
CT_POLICY_EVAL_CTX_new()
CT_POLICY_EVAL_CTX* CT_POLICY_EVAL_CTX_new (void)
Definition at line 28 of file ct_policy.c.
References CT_F_CT_POLICY_EVAL_CTX_NEW, CTerr, ctx, ERR_R_MALLOC_FAILURE, NULL, and OPENSSL_zalloc.
CT_POLICY_EVAL_CTX_set1_cert()
int CT_POLICY_EVAL_CTX_set1_cert (CT_POLICY_EVAL_CTX * ctx, X509 * cert)
Definition at line 53 of file ct_policy.c.
CT_POLICY_EVAL_CTX_set1_issuer()
int CT_POLICY_EVAL_CTX_set1_issuer (CT_POLICY_EVAL_CTX * ctx, X509 * issuer)
Definition at line 61 of file ct_policy.c.
References X509_up_ref().
CT_POLICY_EVAL_CTX_set_shared_CTLOG_STORE()
void CT_POLICY_EVAL_CTX_set_shared_CTLOG_STORE (CT_POLICY_EVAL_CTX * ctx, CTLOG_STORE * log_store)
Definition at line 69 of file ct_policy.c.
CT_POLICY_EVAL_CTX_set_time()
void CT_POLICY_EVAL_CTX_set_time (CT_POLICY_EVAL_CTX * ctx, uint64_t time_in_ms)
Definition at line 75 of file ct_policy.c.
CTLOG_free()
void CTLOG_free (CTLOG * log)
Definition at line 261 of file ct_log.c.
References EVP_PKEY_free(), NULL, and OPENSSL_free.
Referenced by CTLOG_STORE_free().
CTLOG_get0_log_id()
void CTLOG_get0_log_id (const CTLOG * log, const uint8_t ** log_id, size_t * log_id_len)
Definition at line 275 of file ct_log.c.
References CT_V1_HASHLEN.
CTLOG_get0_name()
const char* CTLOG_get0_name (const CTLOG * log)
Definition at line 270 of file ct_log.c.
Referenced by SCT_print().
CTLOG_get0_public_key()
EVP_PKEY* CTLOG_get0_public_key (const CTLOG * log)
Definition at line 282 of file ct_log.c.
Referenced by SCT_validate().
CTLOG_new()
CTLOG* CTLOG_new (EVP_PKEY * public_key, const char * name)
Definition at line 235 of file ct_log.c.
References CT_F_CTLOG_NEW, CTerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_strdup, and OPENSSL_zalloc.
CTLOG_new_from_base64()
int CTLOG_new_from_base64 (CTLOG ** ct_log, const char * pkey_base64, const char * name)
Definition at line 132 of file ct_b64.c.
References NULL.
CTLOG_STORE_free()
void CTLOG_STORE_free (CTLOG_STORE * store)
Definition at line 111 of file ct_log.c.
References CTLOG_free(), NULL, and OPENSSL_free.
Referenced by SSL_CTX_set0_ctlog_store().
CTLOG_STORE_get0_log_by_id()
const CTLOG* CTLOG_STORE_get0_log_by_id (const CTLOG_STORE * store, const uint8_t * log_id, size_t log_id_len)
Definition at line 291 of file ct_log.c.
References NULL.
Referenced by SCT_print(), and SCT_validate().
CTLOG_STORE_load_default_file()
__owur int CTLOG_STORE_load_default_file (CTLOG_STORE * store)
Definition at line 138 of file ct_log.c.
References CTLOG_FILE, CTLOG_FILE_EVP, CTLOG_STORE_load_file(), and NULL.
Referenced by SSL_CTX_set_default_ctlog_list_file().
CTLOG_STORE_load_file()
__owur int CTLOG_STORE_load_file (CTLOG_STORE * store, const char * file)
Definition at line 195 of file ct_log.c.
Referenced by CTLOG_STORE_load_default_file(), and SSL_CTX_set_ctlog_list_file().
CTLOG_STORE_new()
CTLOG_STORE* CTLOG_STORE_new (void)
Definition at line 92 of file ct_log.c.
References CT_F_CTLOG_STORE_NEW, CTerr, ERR_R_MALLOC_FAILURE, NULL, and OPENSSL_zalloc.
ERR_load_CT_strings()
int ERR_load_CT_strings (void)
Definition at line 77 of file ct_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
i2d_SCT_LIST()
__owur int i2d_SCT_LIST (const STACK_OF(SCT) * a, unsigned char ** pp)
Definition at line 395 of file ct_oct.c.
i2o_SCT()
__owur int i2o_SCT (const SCT * sct, unsigned char ** out)
Definition at line 200 of file ct_oct.c.
Referenced by i2o_SCT_LIST().
i2o_SCT_LIST()
__owur int i2o_SCT_LIST (const STACK_OF(SCT) * a, unsigned char ** pp)
Definition at line 321 of file ct_oct.c.
References CT_F_I2O_SCT_LIST, CT_R_SCT_LIST_INVALID, CTerr, ERR_R_MALLOC_FAILURE, i2o_SCT(), i2o_SCT_LIST(), len, MAX_SCT_LIST_SIZE, NULL, OPENSSL_free, OPENSSL_malloc, pp, s2n, and STACK_OF().
Referenced by i2o_SCT_LIST().
o2i_SCT()
SCT* o2i_SCT (SCT ** psct, const unsigned char ** in, size_t len)
Definition at line 70 of file ct_oct.c.
References BUF_memdup, CT_F_O2I_SCT, CT_R_SCT_INVALID, CT_V1_HASHLEN, CTerr, in, len, MAX_SCT_SIZE, n2l8, n2s, NULL, o2i_SCT_signature(), SCT_free(), SCT_new(), and SCT_VERSION_V1.
Referenced by STACK_OF().
SCT_free()
void SCT_free (SCT * sct)
Definition at line 36 of file ct_sct.c.
References NULL, and OPENSSL_free.
Referenced by o2i_SCT(), SCT_LIST_free(), and STACK_OF().
SCT_get0_extensions()
size_t SCT_get0_extensions (const SCT * sct, unsigned char ** ext)
Definition at line 233 of file ct_sct.c.
SCT_get0_log_id()
size_t SCT_get0_log_id (const SCT * sct, unsigned char ** log_id)
Definition at line 205 of file ct_sct.c.
SCT_get0_signature()
size_t SCT_get0_signature (const SCT * sct, unsigned char ** sig)
Definition at line 239 of file ct_sct.c.
SCT_get_log_entry_type()
ct_log_entry_type_t SCT_get_log_entry_type (const SCT * sct)
Definition at line 200 of file ct_sct.c.
Referenced by SCT_validate().
SCT_get_signature_nid()
int SCT_get_signature_nid (const SCT * sct)
Definition at line 216 of file ct_sct.c.
References NID_ecdsa_with_SHA256, NID_sha256WithRSAEncryption, NID_undef, SCT_VERSION_V1, TLSEXT_hash_sha256, TLSEXT_signature_ecdsa, and TLSEXT_signature_rsa.
Referenced by o2i_SCT_signature(), and SCT_signature_is_complete().
SCT_get_source()
sct_source_t SCT_get_source (const SCT * sct)
Definition at line 263 of file ct_sct.c.
SCT_get_timestamp()
uint64_t SCT_get_timestamp (const SCT * sct)
Definition at line 211 of file ct_sct.c.
SCT_get_validation_status()
sct_validation_status_t SCT_get_validation_status (const SCT * sct)
Definition at line 285 of file ct_sct.c.
Referenced by SCT_validation_status_string().
SCT_get_version()
sct_version_t SCT_get_version (const SCT * sct)
Definition at line 195 of file ct_sct.c.
SCT_LIST_free()
void SCT_LIST_free (STACK_OF(SCT) * a)
Definition at line 48 of file ct_sct.c.
References SCT_free().
Referenced by STACK_OF().
SCT_LIST_print()
void SCT_LIST_print (const STACK_OF(SCT) * sct_list, BIO * out, int indent, const char * separator, const CTLOG_STORE * logs)
Definition at line 114 of file ct_prn.c.
References BIO_printf(), and SCT_print().
SCT_LIST_validate()
__owur int SCT_LIST_validate (const STACK_OF(SCT) * scts, CT_POLICY_EVAL_CTX * ctx)
Definition at line 376 of file ct_sct.c.
References NULL, and SCT_validate().
SCT_new()
SCT* SCT_new (void)
Definition at line 22 of file ct_sct.c.
References CT_F_SCT_NEW, CT_LOG_ENTRY_TYPE_NOT_SET, CTerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_zalloc, and SCT_VERSION_NOT_SET.
Referenced by o2i_SCT(), and SCT_new_from_base64().
SCT_new_from_base64()
SCT* SCT_new_from_base64 (unsigned char version, const char * logid_base64, ct_log_entry_type_t entry_type, uint64_t timestamp, const char * extensions_base64, const char * signature_base64)
Definition at line 60 of file ct_b64.c.
References CT_F_SCT_NEW_FROM_BASE64, CT_R_SCT_UNSUPPORTED_VERSION, CTerr, ERR_R_MALLOC_FAILURE, NULL, SCT_new(), and SCT_set_version().
SCT_print()
void SCT_print (const SCT * sct, BIO * out, int indent, const CTLOG_STORE * logs)
Definition at line 70 of file ct_prn.c.
References BIO_hex_string(), BIO_printf(), CTLOG_get0_name(), CTLOG_STORE_get0_log_by_id(), NULL, and SCT_VERSION_V1.
Referenced by SCT_LIST_print().
SCT_set0_extensions()
void SCT_set0_extensions (SCT * sct, unsigned char * ext, size_t ext_len)
Definition at line 143 of file ct_sct.c.
References OPENSSL_free, and SCT_VALIDATION_STATUS_NOT_SET.
SCT_set0_log_id()
__owur int SCT_set0_log_id (SCT * sct, unsigned char * log_id, size_t log_id_len)
Definition at line 80 of file ct_sct.c.
References CT_F_SCT_SET0_LOG_ID, CT_R_INVALID_LOG_ID_LENGTH, CT_V1_HASHLEN, CTerr, OPENSSL_free, SCT_VALIDATION_STATUS_NOT_SET, and SCT_VERSION_V1.
SCT_set0_signature()
void SCT_set0_signature (SCT * sct, unsigned char * sig, size_t sig_len)
Definition at line 169 of file ct_sct.c.
References OPENSSL_free, and SCT_VALIDATION_STATUS_NOT_SET.
SCT_set1_extensions()
__owur int SCT_set1_extensions (SCT * sct, const unsigned char * ext, size_t ext_len)
Definition at line 151 of file ct_sct.c.
References CT_F_SCT_SET1_EXTENSIONS, CTerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_memdup, and SCT_VALIDATION_STATUS_NOT_SET.
SCT_set1_log_id()
__owur int SCT_set1_log_id (SCT * sct, const unsigned char * log_id, size_t log_id_len)
Definition at line 94 of file ct_sct.c.
References CT_F_SCT_SET1_LOG_ID, CT_R_INVALID_LOG_ID_LENGTH, CT_V1_HASHLEN, CTerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_memdup, SCT_VALIDATION_STATUS_NOT_SET, and SCT_VERSION_V1.
SCT_set1_signature()
__owur int SCT_set1_signature (SCT * sct, const unsigned char * sig, size_t sig_len)
Definition at line 177 of file ct_sct.c.
References CT_F_SCT_SET1_SIGNATURE, CTerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_memdup, and SCT_VALIDATION_STATUS_NOT_SET.
Referenced by o2i_SCT_signature().
SCT_set_log_entry_type()
__owur int SCT_set_log_entry_type (SCT * sct, ct_log_entry_type_t entry_type)
Definition at line 64 of file ct_sct.c.
References CT_F_SCT_SET_LOG_ENTRY_TYPE, CT_LOG_ENTRY_TYPE_NOT_SET, CT_LOG_ENTRY_TYPE_PRECERT, CT_LOG_ENTRY_TYPE_X509, CT_R_UNSUPPORTED_ENTRY_TYPE, CTerr, and SCT_VALIDATION_STATUS_NOT_SET.
Referenced by SCT_set_source().
SCT_set_signature_nid()
__owur int SCT_set_signature_nid (SCT * sct, int nid)
Definition at line 124 of file ct_sct.c.
References CT_F_SCT_SET_SIGNATURE_NID, CT_R_UNRECOGNIZED_SIGNATURE_NID, CTerr, NID_ecdsa_with_SHA256, NID_sha256WithRSAEncryption, SCT_VALIDATION_STATUS_NOT_SET, TLSEXT_hash_sha256, TLSEXT_signature_ecdsa, and TLSEXT_signature_rsa.
SCT_set_source()
__owur int SCT_set_source (SCT * sct, sct_source_t source)
Definition at line 268 of file ct_sct.c.
References CT_LOG_ENTRY_TYPE_PRECERT, CT_LOG_ENTRY_TYPE_X509, SCT_set_log_entry_type(), SCT_SOURCE_OCSP_STAPLED_RESPONSE, SCT_SOURCE_TLS_EXTENSION, SCT_SOURCE_UNKNOWN, SCT_SOURCE_X509V3_EXTENSION, and SCT_VALIDATION_STATUS_NOT_SET.
SCT_set_timestamp()
void SCT_set_timestamp (SCT * sct, uint64_t timestamp)
Definition at line 118 of file ct_sct.c.
References SCT_VALIDATION_STATUS_NOT_SET.
SCT_set_version()
__owur int SCT_set_version (SCT * sct, sct_version_t version)
Definition at line 53 of file ct_sct.c.
References CT_F_SCT_SET_VERSION, CT_R_UNSUPPORTED_VERSION, CTerr, SCT_VALIDATION_STATUS_NOT_SET, and SCT_VERSION_V1.
Referenced by SCT_new_from_base64().
SCT_validate()
__owur int SCT_validate (SCT * sct, const CT_POLICY_EVAL_CTX * ctx)
Definition at line 290 of file ct_sct.c.
References CT_LOG_ENTRY_TYPE_PRECERT, CTLOG_get0_public_key(), CTLOG_STORE_get0_log_by_id(), NULL, SCT_CTX_free(), SCT_CTX_new(), SCT_CTX_set1_cert(), SCT_CTX_set1_issuer_pubkey(), SCT_CTX_set1_pubkey(), SCT_CTX_set_time(), SCT_CTX_verify(), SCT_get_log_entry_type(), SCT_VALIDATION_STATUS_INVALID, SCT_VALIDATION_STATUS_UNKNOWN_LOG, SCT_VALIDATION_STATUS_UNKNOWN_VERSION, SCT_VALIDATION_STATUS_UNVERIFIED, SCT_VALIDATION_STATUS_VALID, SCT_VERSION_V1, X509_get0_pubkey(), and X509_PUBKEY_set().
Referenced by SCT_LIST_validate().
SCT_validation_status_string()
const char* SCT_validation_status_string (const SCT * sct)
Definition at line 50 of file ct_prn.c.
References SCT_get_validation_status(), SCT_VALIDATION_STATUS_INVALID, SCT_VALIDATION_STATUS_NOT_SET, SCT_VALIDATION_STATUS_UNKNOWN_LOG, SCT_VALIDATION_STATUS_UNKNOWN_VERSION, SCT_VALIDATION_STATUS_UNVERIFIED, and SCT_VALIDATION_STATUS_VALID.
STACK_OF()
STACK_OF (SCT)
Definition at line 257 of file ct_oct.c.
Variable Documentation
len
const char int const unsigned char int len
Definition at line 346 of file ct.h.
Referenced by ASN1_GENERALIZEDTIME_adj(), ASN1_OBJECT_create(), ASN1_STRING_length_set(), ASN1_STRING_set0(), ASN1_UTCTIME_adj(), BIO_accept_ex(), BIO_ADDR_rawaddress(), BN_mpi2bn(), CONF_get1_default_config_file(), CRYPTO_gcm128_aad(), d2i_ASN1_OBJECT(), DSO_dsobyaddr(), EC_GROUP_get_ecparameters(), EC_GROUP_set_seed(), EC_KEY_priv2buf(), EC_POINT_point2buf(), ENGINE_pkey_asn1_find_str(), EVP_PKEY_CTX_str2ctrl(), i2o_SCT_LIST(), name_cmp(), next_protos_parse(), o2i_SCT(), o2i_SCT_signature(), OCSP_REQ_CTX_nbio_d2i(), OCSP_set_max_response_length(), OPENSSL_buf2hexstr(), OPENSSL_cpuid_setup(), OPENSSL_Uplink(), PEM_ASN1_read_bio(), PEM_read_bio_DHparams(), PEM_read_bio_Parameters(), PEM_read_bio_PrivateKey(), sha256_block_data_order(), SHA3_absorb(), SMIME_crlf_copy(), SMIME_text(), SRP_create_verifier(), ssl3_read_n(), ssl3_setup_read_buffer(), ssl3_setup_write_buffer(), SSL_callback_ctrl(), SSL_CTX_callback_ctrl(), SSL_CTX_set_default_read_buffer_len(), STACK_OF(), tls_construct_new_session_ticket(), tls_construct_next_proto(), tls_construct_server_hello(), tls_parse_stoc_alpn(), TS_VERIFY_CTX_set_imprint(), UI_construct_prompt(), and WPACKET_allocate_bytes().
pp
const unsigned char ** pp
Definition at line 346 of file ct.h.
Referenced by ASN1_put_eoc(), ASN1_put_object(), d2i_AutoPrivateKey(), i2d_ASN1_OBJECT(), i2o_SCT_LIST(), opt_num_rest(), opt_pair(), and SRP_VBASE_init().