crypto/ct/ct_prn.c File Reference
ct_prn.c File Reference
#include <openssl/asn1.h>
#include <openssl/bio.h>
#include "ct_locl.h"
Functions
const char * SCT_validation_status_string (const SCT *sct)
void SCT_print (const SCT *sct, BIO *out, int indent, const CTLOG_STORE *log_store)
void SCT_LIST_print (const STACK_OF(SCT) *sct_list, BIO *out, int indent, const char *separator, const CTLOG_STORE *log_store)
Function Documentation
SCT_LIST_print()
void SCT_LIST_print (const STACK_OF(SCT) * sct_list, BIO * out, int indent, const char * separator, const CTLOG_STORE * log_store)
Definition at line 114 of file ct_prn.c.
References BIO_printf(), and SCT_print().
SCT_print()
void SCT_print (const SCT * sct, BIO * out, int indent, const CTLOG_STORE * log_store)
Definition at line 70 of file ct_prn.c.
References BIO_hex_string(), BIO_printf(), CTLOG_get0_name(), CTLOG_STORE_get0_log_by_id(), NULL, and SCT_VERSION_V1.
Referenced by SCT_LIST_print().
SCT_validation_status_string()
const char* SCT_validation_status_string (const SCT * sct)
Definition at line 50 of file ct_prn.c.
References SCT_get_validation_status(), SCT_VALIDATION_STATUS_INVALID, SCT_VALIDATION_STATUS_NOT_SET, SCT_VALIDATION_STATUS_UNKNOWN_LOG, SCT_VALIDATION_STATUS_UNKNOWN_VERSION, SCT_VALIDATION_STATUS_UNVERIFIED, and SCT_VALIDATION_STATUS_VALID.