crypto/ct/ct_log.c File Reference
ct_log.c File Reference
#include <stdlib.h>
#include <string.h>
#include <openssl/conf.h>
#include <openssl/ct.h>
#include <openssl/err.h>
#include <openssl/evp.h>
#include <openssl/safestack.h>
#include "internal/cryptlib.h"
Data Structures
struct CTLOG
struct CTLOG_STORE
struct CTLOG_STORE_LOAD_CTX
Functions
CTLOG_STORE * CTLOG_STORE_new (void)
void CTLOG_STORE_free (CTLOG_STORE *store)
int CTLOG_STORE_load_default_file (CTLOG_STORE *store)
int CTLOG_STORE_load_file (CTLOG_STORE *store, const char *file)
CTLOG * CTLOG_new (EVP_PKEY *public_key, const char *name)
void CTLOG_free (CTLOG *log)
const char * CTLOG_get0_name (const CTLOG *log)
void CTLOG_get0_log_id (const CTLOG *log, const uint8_t **log_id, size_t *log_id_len)
EVP_PKEY * CTLOG_get0_public_key (const CTLOG *log)
const CTLOG * CTLOG_STORE_get0_log_by_id (const CTLOG_STORE *store, const uint8_t *log_id, size_t log_id_len)
Function Documentation
CTLOG_free()
void CTLOG_free (CTLOG * log)
Definition at line 261 of file ct_log.c.
References EVP_PKEY_free(), NULL, and OPENSSL_free.
Referenced by CTLOG_STORE_free().
CTLOG_get0_log_id()
void CTLOG_get0_log_id (const CTLOG * log, const uint8_t ** log_id, size_t * log_id_len)
Definition at line 275 of file ct_log.c.
References CT_V1_HASHLEN.
CTLOG_get0_name()
const char* CTLOG_get0_name (const CTLOG * log)
Definition at line 270 of file ct_log.c.
Referenced by SCT_print().
CTLOG_get0_public_key()
EVP_PKEY* CTLOG_get0_public_key (const CTLOG * log)
Definition at line 282 of file ct_log.c.
Referenced by SCT_validate().
CTLOG_new()
CTLOG* CTLOG_new (EVP_PKEY * public_key, const char * name)
Definition at line 235 of file ct_log.c.
References CT_F_CTLOG_NEW, CTerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_strdup, and OPENSSL_zalloc.
CTLOG_STORE_free()
void CTLOG_STORE_free (CTLOG_STORE * store)
Definition at line 111 of file ct_log.c.
References CTLOG_free(), NULL, and OPENSSL_free.
Referenced by SSL_CTX_set0_ctlog_store().
CTLOG_STORE_get0_log_by_id()
const CTLOG* CTLOG_STORE_get0_log_by_id (const CTLOG_STORE * store, const uint8_t * log_id, size_t log_id_len)
Definition at line 291 of file ct_log.c.
References NULL.
Referenced by SCT_print(), and SCT_validate().
CTLOG_STORE_load_default_file()
int CTLOG_STORE_load_default_file (CTLOG_STORE * store)
Definition at line 138 of file ct_log.c.
References CTLOG_FILE, CTLOG_FILE_EVP, CTLOG_STORE_load_file(), and NULL.
Referenced by SSL_CTX_set_default_ctlog_list_file().
CTLOG_STORE_load_file()
int CTLOG_STORE_load_file (CTLOG_STORE * store, const char * file)
Definition at line 195 of file ct_log.c.
Referenced by CTLOG_STORE_load_default_file(), and SSL_CTX_set_ctlog_list_file().
CTLOG_STORE_new()
CTLOG_STORE* CTLOG_STORE_new (void)
Definition at line 92 of file ct_log.c.
References CT_F_CTLOG_STORE_NEW, CTerr, ERR_R_MALLOC_FAILURE, NULL, and OPENSSL_zalloc.