crypto/ct/ct_locl.h File Reference
ct_locl.h File Reference
#include <stddef.h>
#include <openssl/ct.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/safestack.h>
Data Structures
struct SCT
struct SCT_CTX
struct CT_POLICY_EVAL_CTX
Macros
#define MAX_SCT_SIZE 65535
#define MAX_SCT_LIST_SIZE MAX_SCT_SIZE
#define n2s(c, s)
#define s2n(s, c)
#define l2n3(l, c)
#define n2l8(c, l)
#define l2n8(l, c)
Functions
SCT_CTX * SCT_CTX_new (void)
void SCT_CTX_free (SCT_CTX *sctx)
__owur int SCT_CTX_set1_cert (SCT_CTX *sctx, X509 *cert, X509 *presigner)
__owur int SCT_CTX_set1_issuer (SCT_CTX *sctx, const X509 *issuer)
__owur int SCT_CTX_set1_issuer_pubkey (SCT_CTX *sctx, X509_PUBKEY *pubkey)
__owur int SCT_CTX_set1_pubkey (SCT_CTX *sctx, X509_PUBKEY *pubkey)
void SCT_CTX_set_time (SCT_CTX *sctx, uint64_t time_in_ms)
__owur int SCT_CTX_verify (const SCT_CTX *sctx, const SCT *sct)
__owur int SCT_is_complete (const SCT *sct)
__owur int SCT_signature_is_complete (const SCT *sct)
__owur int i2o_SCT_signature (const SCT *sct, unsigned char **out)
__owur int o2i_SCT_signature (SCT *sct, const unsigned char **in, size_t len)
Variables
const X509V3_EXT_METHOD v3_ct_scts [3]
Macro Definition Documentation
l2n3
#define l2n3 (l, c)
Value:
((c[0]=(unsigned char)(((l)>>16)&0xff), \
                          c[1]=(unsigned char)(((l)>> 8)&0xff), \
                          c[2]=(unsigned char)(((l)    )&0xff)),c+=3)
Definition at line 34 of file ct_locl.h.
l2n8
#define l2n8 (l, c)
Value:
(*((c)++)=(unsigned char)(((l)>>56)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>48)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>40)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>32)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>24)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>16)&0xff), \
                         *((c)++)=(unsigned char)(((l)>> 8)&0xff), \
                         *((c)++)=(unsigned char)(((l)    )&0xff))
Definition at line 47 of file ct_locl.h.
MAX_SCT_LIST_SIZE
#define MAX_SCT_LIST_SIZE MAX_SCT_SIZE
Definition at line 22 of file ct_locl.h.
Referenced by i2o_SCT_LIST(), and STACK_OF().
MAX_SCT_SIZE
#define MAX_SCT_SIZE 65535
Definition at line 21 of file ct_locl.h.
Referenced by o2i_SCT().
n2l8
#define n2l8 (c, l)
Value:
(l =((uint64_t)(*((c)++)))<<56, \
                         l|=((uint64_t)(*((c)++)))<<48, \
                         l|=((uint64_t)(*((c)++)))<<40, \
                         l|=((uint64_t)(*((c)++)))<<32, \
                         l|=((uint64_t)(*((c)++)))<<24, \
                         l|=((uint64_t)(*((c)++)))<<16, \
                         l|=((uint64_t)(*((c)++)))<< 8, \
                         l|=((uint64_t)(*((c)++))))
Definition at line 38 of file ct_locl.h.
Referenced by o2i_SCT().
n2s
#define n2s (c, s)
Value:
((s=(((unsigned int)((c)[0]))<< 8)| \
                            (((unsigned int)((c)[1]))    )),c+=2)
Definition at line 28 of file ct_locl.h.
Referenced by dtls1_get_message_header(), dtls1_get_record(), IDEA_set_encrypt_key(), o2i_SCT(), o2i_SCT_signature(), and STACK_OF().
s2n
#define s2n (s, c)
Value:
((c[0]=(unsigned char)(((s)>> 8)&0xff), \
                          c[1]=(unsigned char)(((s)    )&0xff)),c+=2)
Definition at line 31 of file ct_locl.h.
Referenced by i2o_SCT_LIST(), and tls1_set_groups().
Function Documentation
i2o_SCT_signature()
__owur int i2o_SCT_signature (const SCT * sct, unsigned char ** out)
Definition at line 153 of file ct_oct.c.
o2i_SCT_signature()
__owur int o2i_SCT_signature (SCT * sct, const unsigned char ** in, size_t len)
Definition at line 24 of file ct_oct.c.
References CT_F_O2I_SCT_SIGNATURE, CT_R_SCT_INVALID_SIGNATURE, CT_R_UNSUPPORTED_VERSION, CTerr, in, len, n2s, NID_undef, SCT_get_signature_nid(), SCT_set1_signature(), and SCT_VERSION_V1.
Referenced by o2i_SCT().
SCT_CTX_free()
void SCT_CTX_free (SCT_CTX * sctx)
Definition at line 33 of file ct_sct_ctx.c.
References EVP_PKEY_free(), NULL, and OPENSSL_free.
Referenced by SCT_validate().
SCT_CTX_new()
SCT_CTX* SCT_CTX_new (void)
Definition at line 23 of file ct_sct_ctx.c.
References CT_F_SCT_CTX_NEW, CTerr, ERR_R_MALLOC_FAILURE, NULL, and OPENSSL_zalloc.
Referenced by SCT_validate().
SCT_CTX_set1_cert()
__owur int SCT_CTX_set1_cert (SCT_CTX * sctx, X509 * cert, X509 * presigner)
Definition at line 109 of file ct_sct_ctx.c.
Referenced by SCT_validate().
SCT_CTX_set1_issuer()
__owur int SCT_CTX_set1_issuer (SCT_CTX * sctx, const X509 * issuer)
Definition at line 233 of file ct_sct_ctx.c.
References SCT_CTX_set1_issuer_pubkey(), and X509_get_X509_PUBKEY().
SCT_CTX_set1_issuer_pubkey()
__owur int SCT_CTX_set1_issuer_pubkey (SCT_CTX * sctx, X509_PUBKEY * pubkey)
Definition at line 238 of file ct_sct_ctx.c.
Referenced by SCT_CTX_set1_issuer(), and SCT_validate().
SCT_CTX_set1_pubkey()
__owur int SCT_CTX_set1_pubkey (SCT_CTX * sctx, X509_PUBKEY * pubkey)
Definition at line 243 of file ct_sct_ctx.c.
References NULL, and X509_PUBKEY_get().
Referenced by SCT_validate().
SCT_CTX_set_time()
void SCT_CTX_set_time (SCT_CTX * sctx, uint64_t time_in_ms)
Definition at line 260 of file ct_sct_ctx.c.
Referenced by SCT_validate().
SCT_CTX_verify()
__owur int SCT_CTX_verify (const SCT_CTX * sctx, const SCT * sct)
Definition at line 96 of file ct_vfy.c.
References ctx, and NULL.
Referenced by SCT_validate().
SCT_is_complete()
__owur int SCT_is_complete (const SCT * sct)
Definition at line 245 of file ct_sct.c.
References NULL, SCT_signature_is_complete(), SCT_VERSION_NOT_SET, and SCT_VERSION_V1.
SCT_signature_is_complete()
__owur int SCT_signature_is_complete (const SCT * sct)
Definition at line 257 of file ct_sct.c.
References NID_undef, NULL, and SCT_get_signature_nid().
Referenced by SCT_is_complete().
Variable Documentation
v3_ct_scts
const X509V3_EXT_METHOD v3_ct_scts[3]
Definition at line 34 of file ct_x509v3.c.