crypto/ct/ct_sct_ctx.c File Reference
ct_sct_ctx.c File Reference
#include <stddef.h>
#include <string.h>
#include <openssl/err.h>
#include <openssl/obj_mac.h>
#include <openssl/x509.h>
#include "ct_locl.h"
Functions
SCT_CTX * SCT_CTX_new (void)
void SCT_CTX_free (SCT_CTX *sctx)
int SCT_CTX_set1_cert (SCT_CTX *sctx, X509 *cert, X509 *presigner)
int SCT_CTX_set1_issuer (SCT_CTX *sctx, const X509 *issuer)
int SCT_CTX_set1_issuer_pubkey (SCT_CTX *sctx, X509_PUBKEY *pubkey)
int SCT_CTX_set1_pubkey (SCT_CTX *sctx, X509_PUBKEY *pubkey)
void SCT_CTX_set_time (SCT_CTX *sctx, uint64_t time_in_ms)
Function Documentation
SCT_CTX_free()
void SCT_CTX_free (SCT_CTX * sctx)
Definition at line 33 of file ct_sct_ctx.c.
References EVP_PKEY_free(), NULL, and OPENSSL_free.
Referenced by SCT_validate().
SCT_CTX_new()
SCT_CTX* SCT_CTX_new (void)
Definition at line 23 of file ct_sct_ctx.c.
References CT_F_SCT_CTX_NEW, CTerr, ERR_R_MALLOC_FAILURE, NULL, and OPENSSL_zalloc.
Referenced by SCT_validate().
SCT_CTX_set1_cert()
int SCT_CTX_set1_cert (SCT_CTX * sctx, X509 * cert, X509 * presigner)
Definition at line 109 of file ct_sct_ctx.c.
Referenced by SCT_validate().
SCT_CTX_set1_issuer()
int SCT_CTX_set1_issuer (SCT_CTX * sctx, const X509 * issuer)
Definition at line 233 of file ct_sct_ctx.c.
References SCT_CTX_set1_issuer_pubkey(), and X509_get_X509_PUBKEY().
SCT_CTX_set1_issuer_pubkey()
int SCT_CTX_set1_issuer_pubkey (SCT_CTX * sctx, X509_PUBKEY * pubkey)
Definition at line 238 of file ct_sct_ctx.c.
Referenced by SCT_CTX_set1_issuer(), and SCT_validate().
SCT_CTX_set1_pubkey()
int SCT_CTX_set1_pubkey (SCT_CTX * sctx, X509_PUBKEY * pubkey)
Definition at line 243 of file ct_sct_ctx.c.
References NULL, and X509_PUBKEY_get().
Referenced by SCT_validate().
SCT_CTX_set_time()
void SCT_CTX_set_time (SCT_CTX * sctx, uint64_t time_in_ms)
Definition at line 260 of file ct_sct_ctx.c.
Referenced by SCT_validate().