crypto/ct/ct_sct.c File Reference
ct_sct.c File Reference
#include <openssl/ct.h>
#include <openssl/err.h>
#include <openssl/evp.h>
#include <openssl/tls1.h>
#include <openssl/x509.h>
#include "ct_locl.h"
Functions
SCT * SCT_new (void)
void SCT_free (SCT *sct)
void SCT_LIST_free (STACK_OF(SCT) *a)
int SCT_set_version (SCT *sct, sct_version_t version)
int SCT_set_log_entry_type (SCT *sct, ct_log_entry_type_t entry_type)
int SCT_set0_log_id (SCT *sct, unsigned char *log_id, size_t log_id_len)
int SCT_set1_log_id (SCT *sct, const unsigned char *log_id, size_t log_id_len)
void SCT_set_timestamp (SCT *sct, uint64_t timestamp)
int SCT_set_signature_nid (SCT *sct, int nid)
void SCT_set0_extensions (SCT *sct, unsigned char *ext, size_t ext_len)
int SCT_set1_extensions (SCT *sct, const unsigned char *ext, size_t ext_len)
void SCT_set0_signature (SCT *sct, unsigned char *sig, size_t sig_len)
int SCT_set1_signature (SCT *sct, const unsigned char *sig, size_t sig_len)
sct_version_t SCT_get_version (const SCT *sct)
ct_log_entry_type_t SCT_get_log_entry_type (const SCT *sct)
size_t SCT_get0_log_id (const SCT *sct, unsigned char **log_id)
uint64_t SCT_get_timestamp (const SCT *sct)
int SCT_get_signature_nid (const SCT *sct)
size_t SCT_get0_extensions (const SCT *sct, unsigned char **ext)
size_t SCT_get0_signature (const SCT *sct, unsigned char **sig)
int SCT_is_complete (const SCT *sct)
int SCT_signature_is_complete (const SCT *sct)
sct_source_t SCT_get_source (const SCT *sct)
int SCT_set_source (SCT *sct, sct_source_t source)
sct_validation_status_t SCT_get_validation_status (const SCT *sct)
int SCT_validate (SCT *sct, const CT_POLICY_EVAL_CTX *ctx)
int SCT_LIST_validate (const STACK_OF(SCT) *scts, CT_POLICY_EVAL_CTX *ctx)
Function Documentation
SCT_free()
void SCT_free (SCT * sct)
Definition at line 36 of file ct_sct.c.
References NULL, and OPENSSL_free.
Referenced by o2i_SCT(), SCT_LIST_free(), and STACK_OF().
SCT_get0_extensions()
size_t SCT_get0_extensions (const SCT * sct, unsigned char ** ext)
Definition at line 233 of file ct_sct.c.
SCT_get0_log_id()
size_t SCT_get0_log_id (const SCT * sct, unsigned char ** log_id)
Definition at line 205 of file ct_sct.c.
SCT_get0_signature()
size_t SCT_get0_signature (const SCT * sct, unsigned char ** sig)
Definition at line 239 of file ct_sct.c.
SCT_get_log_entry_type()
ct_log_entry_type_t SCT_get_log_entry_type (const SCT * sct)
Definition at line 200 of file ct_sct.c.
Referenced by SCT_validate().
SCT_get_signature_nid()
int SCT_get_signature_nid (const SCT * sct)
Definition at line 216 of file ct_sct.c.
References NID_ecdsa_with_SHA256, NID_sha256WithRSAEncryption, NID_undef, SCT_VERSION_V1, TLSEXT_hash_sha256, TLSEXT_signature_ecdsa, and TLSEXT_signature_rsa.
Referenced by o2i_SCT_signature(), and SCT_signature_is_complete().
SCT_get_source()
sct_source_t SCT_get_source (const SCT * sct)
Definition at line 263 of file ct_sct.c.
SCT_get_timestamp()
uint64_t SCT_get_timestamp (const SCT * sct)
Definition at line 211 of file ct_sct.c.
SCT_get_validation_status()
sct_validation_status_t SCT_get_validation_status (const SCT * sct)
Definition at line 285 of file ct_sct.c.
Referenced by SCT_validation_status_string().
SCT_get_version()
sct_version_t SCT_get_version (const SCT * sct)
Definition at line 195 of file ct_sct.c.
SCT_is_complete()
int SCT_is_complete (const SCT * sct)
Definition at line 245 of file ct_sct.c.
References NULL, SCT_signature_is_complete(), SCT_VERSION_NOT_SET, and SCT_VERSION_V1.
SCT_LIST_free()
void SCT_LIST_free (STACK_OF(SCT) * a)
Definition at line 48 of file ct_sct.c.
References SCT_free().
Referenced by STACK_OF().
SCT_LIST_validate()
int SCT_LIST_validate (const STACK_OF(SCT) * scts, CT_POLICY_EVAL_CTX * ctx)
Definition at line 376 of file ct_sct.c.
References NULL, and SCT_validate().
SCT_new()
SCT* SCT_new (void)
Definition at line 22 of file ct_sct.c.
References CT_F_SCT_NEW, CT_LOG_ENTRY_TYPE_NOT_SET, CTerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_zalloc, and SCT_VERSION_NOT_SET.
Referenced by o2i_SCT(), and SCT_new_from_base64().
SCT_set0_extensions()
void SCT_set0_extensions (SCT * sct, unsigned char * ext, size_t ext_len)
Definition at line 143 of file ct_sct.c.
References OPENSSL_free, and SCT_VALIDATION_STATUS_NOT_SET.
SCT_set0_log_id()
int SCT_set0_log_id (SCT * sct, unsigned char * log_id, size_t log_id_len)
Definition at line 80 of file ct_sct.c.
References CT_F_SCT_SET0_LOG_ID, CT_R_INVALID_LOG_ID_LENGTH, CT_V1_HASHLEN, CTerr, OPENSSL_free, SCT_VALIDATION_STATUS_NOT_SET, and SCT_VERSION_V1.
SCT_set0_signature()
void SCT_set0_signature (SCT * sct, unsigned char * sig, size_t sig_len)
Definition at line 169 of file ct_sct.c.
References OPENSSL_free, and SCT_VALIDATION_STATUS_NOT_SET.
SCT_set1_extensions()
int SCT_set1_extensions (SCT * sct, const unsigned char * ext, size_t ext_len)
Definition at line 151 of file ct_sct.c.
References CT_F_SCT_SET1_EXTENSIONS, CTerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_memdup, and SCT_VALIDATION_STATUS_NOT_SET.
SCT_set1_log_id()
int SCT_set1_log_id (SCT * sct, const unsigned char * log_id, size_t log_id_len)
Definition at line 94 of file ct_sct.c.
References CT_F_SCT_SET1_LOG_ID, CT_R_INVALID_LOG_ID_LENGTH, CT_V1_HASHLEN, CTerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_memdup, SCT_VALIDATION_STATUS_NOT_SET, and SCT_VERSION_V1.
SCT_set1_signature()
int SCT_set1_signature (SCT * sct, const unsigned char * sig, size_t sig_len)
Definition at line 177 of file ct_sct.c.
References CT_F_SCT_SET1_SIGNATURE, CTerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_memdup, and SCT_VALIDATION_STATUS_NOT_SET.
Referenced by o2i_SCT_signature().
SCT_set_log_entry_type()
int SCT_set_log_entry_type (SCT * sct, ct_log_entry_type_t entry_type)
Definition at line 64 of file ct_sct.c.
References CT_F_SCT_SET_LOG_ENTRY_TYPE, CT_LOG_ENTRY_TYPE_NOT_SET, CT_LOG_ENTRY_TYPE_PRECERT, CT_LOG_ENTRY_TYPE_X509, CT_R_UNSUPPORTED_ENTRY_TYPE, CTerr, and SCT_VALIDATION_STATUS_NOT_SET.
Referenced by SCT_set_source().
SCT_set_signature_nid()
int SCT_set_signature_nid (SCT * sct, int nid)
Definition at line 124 of file ct_sct.c.
References CT_F_SCT_SET_SIGNATURE_NID, CT_R_UNRECOGNIZED_SIGNATURE_NID, CTerr, NID_ecdsa_with_SHA256, NID_sha256WithRSAEncryption, SCT_VALIDATION_STATUS_NOT_SET, TLSEXT_hash_sha256, TLSEXT_signature_ecdsa, and TLSEXT_signature_rsa.
SCT_set_source()
int SCT_set_source (SCT * sct, sct_source_t source)
Definition at line 268 of file ct_sct.c.
References CT_LOG_ENTRY_TYPE_PRECERT, CT_LOG_ENTRY_TYPE_X509, SCT_set_log_entry_type(), SCT_SOURCE_OCSP_STAPLED_RESPONSE, SCT_SOURCE_TLS_EXTENSION, SCT_SOURCE_UNKNOWN, SCT_SOURCE_X509V3_EXTENSION, and SCT_VALIDATION_STATUS_NOT_SET.
SCT_set_timestamp()
void SCT_set_timestamp (SCT * sct, uint64_t timestamp)
Definition at line 118 of file ct_sct.c.
References SCT_VALIDATION_STATUS_NOT_SET.
SCT_set_version()
int SCT_set_version (SCT * sct, sct_version_t version)
Definition at line 53 of file ct_sct.c.
References CT_F_SCT_SET_VERSION, CT_R_UNSUPPORTED_VERSION, CTerr, SCT_VALIDATION_STATUS_NOT_SET, and SCT_VERSION_V1.
Referenced by SCT_new_from_base64().
SCT_signature_is_complete()
int SCT_signature_is_complete (const SCT * sct)
Definition at line 257 of file ct_sct.c.
References NID_undef, NULL, and SCT_get_signature_nid().
Referenced by SCT_is_complete().
SCT_validate()
int SCT_validate (SCT * sct, const CT_POLICY_EVAL_CTX * ctx)
Definition at line 290 of file ct_sct.c.
References CT_LOG_ENTRY_TYPE_PRECERT, CTLOG_get0_public_key(), CTLOG_STORE_get0_log_by_id(), NULL, SCT_CTX_free(), SCT_CTX_new(), SCT_CTX_set1_cert(), SCT_CTX_set1_issuer_pubkey(), SCT_CTX_set1_pubkey(), SCT_CTX_set_time(), SCT_CTX_verify(), SCT_get_log_entry_type(), SCT_VALIDATION_STATUS_INVALID, SCT_VALIDATION_STATUS_UNKNOWN_LOG, SCT_VALIDATION_STATUS_UNKNOWN_VERSION, SCT_VALIDATION_STATUS_UNVERIFIED, SCT_VALIDATION_STATUS_VALID, SCT_VERSION_V1, X509_get0_pubkey(), and X509_PUBKEY_set().
Referenced by SCT_LIST_validate().