crypto/ct/ct_oct.c File Reference
ct_oct.c File Reference
#include <limits.h>
#include <string.h>
#include <openssl/asn1.h>
#include <openssl/buffer.h>
#include <openssl/ct.h>
#include <openssl/err.h>
#include "ct_locl.h"
Functions
int o2i_SCT_signature (SCT *sct, const unsigned char **in, size_t len)
SCT * o2i_SCT (SCT **psct, const unsigned char **in, size_t len)
int i2o_SCT_signature (const SCT *sct, unsigned char **out)
int i2o_SCT (const SCT *sct, unsigned char **out)
STACK_OF (SCT)
int i2o_SCT_LIST (const STACK_OF(SCT) *a, unsigned char **pp)
int i2d_SCT_LIST (const STACK_OF(SCT) *a, unsigned char **out)
Function Documentation
i2d_SCT_LIST()
int i2d_SCT_LIST (const STACK_OF(SCT) * a, unsigned char ** out)
Definition at line 395 of file ct_oct.c.
i2o_SCT()
int i2o_SCT (const SCT * sct, unsigned char ** out)
Definition at line 200 of file ct_oct.c.
Referenced by i2o_SCT_LIST().
i2o_SCT_LIST()
int i2o_SCT_LIST (const STACK_OF(SCT) * a, unsigned char ** pp)
Definition at line 321 of file ct_oct.c.
References CT_F_I2O_SCT_LIST, CT_R_SCT_LIST_INVALID, CTerr, ERR_R_MALLOC_FAILURE, i2o_SCT(), i2o_SCT_LIST(), len, MAX_SCT_LIST_SIZE, NULL, OPENSSL_free, OPENSSL_malloc, pp, s2n, and STACK_OF().
Referenced by i2o_SCT_LIST().
i2o_SCT_signature()
int i2o_SCT_signature (const SCT * sct, unsigned char ** out)
Definition at line 153 of file ct_oct.c.
o2i_SCT()
SCT* o2i_SCT (SCT ** psct, const unsigned char ** in, size_t len)
Definition at line 70 of file ct_oct.c.
References BUF_memdup, CT_F_O2I_SCT, CT_R_SCT_INVALID, CT_V1_HASHLEN, CTerr, in, len, MAX_SCT_SIZE, n2l8, n2s, NULL, o2i_SCT_signature(), SCT_free(), SCT_new(), and SCT_VERSION_V1.
Referenced by STACK_OF().
o2i_SCT_signature()
int o2i_SCT_signature (SCT * sct, const unsigned char ** in, size_t len)
Definition at line 24 of file ct_oct.c.
References CT_F_O2I_SCT_SIGNATURE, CT_R_SCT_INVALID_SIGNATURE, CT_R_UNSUPPORTED_VERSION, CTerr, in, len, n2s, NID_undef, SCT_get_signature_nid(), SCT_set1_signature(), and SCT_VERSION_V1.
Referenced by o2i_SCT().
STACK_OF()
STACK_OF (SCT)
Definition at line 257 of file ct_oct.c.
Referenced by i2o_SCT_LIST(), and STACK_OF().