ssl/d1_msg.c File Reference
d1_msg.c File Reference
#include "ssl_locl.h"
Macros
#define USE_SOCKETS
Functions
int dtls1_write_app_data_bytes (SSL *s, int type, const void *buf_, size_t len, size_t *written)
int dtls1_dispatch_alert (SSL *s)
Macro Definition Documentation
USE_SOCKETS
#define USE_SOCKETS
Definition at line 10 of file d1_msg.c.
Function Documentation
dtls1_dispatch_alert()
int dtls1_dispatch_alert (SSL * s)
Definition at line 48 of file d1_msg.c.
References cb, NULL, and type.
dtls1_write_app_data_bytes()
int dtls1_write_app_data_bytes (SSL * s, int type, const void * buf_, size_t len, size_t * written)
Definition at line 13 of file d1_msg.c.
References BIO_dgram_is_sctp(), dtls1_write_bytes(), ossl_statem_get_in_handshake(), ossl_statem_in_sctp_read_sock(), SSL3_RT_MAX_PLAIN_LENGTH, SSL_F_DTLS1_WRITE_APP_DATA_BYTES, SSL_get_wbio(), SSL_in_init(), SSL_R_DTLS_MESSAGE_TOO_BIG, SSL_R_SSL_HANDSHAKE_FAILURE, and SSLerr.