ssl/d1_lib.c File Reference
d1_lib.c File Reference
#include <stdio.h>
#include <openssl/objects.h>
#include <openssl/rand.h>
#include "ssl_locl.h"
#include <sys/time.h>
Macros
#define USE_SOCKETS
#define LISTEN_SUCCESS 2
#define LISTEN_SEND_VERIFY_REQUEST 1
Functions
long dtls1_default_timeout (void)
int dtls1_new (SSL *s)
void dtls1_clear_received_buffer (SSL *s)
void dtls1_clear_sent_buffer (SSL *s)
void dtls1_free (SSL *s)
void dtls1_clear (SSL *s)
long dtls1_ctrl (SSL *s, int cmd, long larg, void *parg)
void dtls1_start_timer (SSL *s)
struct timeval * dtls1_get_timeout (SSL *s, struct timeval *timeleft)
int dtls1_is_timer_expired (SSL *s)
void dtls1_double_timeout (SSL *s)
void dtls1_stop_timer (SSL *s)
int dtls1_check_timeout_num (SSL *s)
int dtls1_handle_timeout (SSL *s)
int DTLSv1_listen (SSL *s, BIO_ADDR *client)
int dtls1_shutdown (SSL *s)
int dtls1_query_mtu (SSL *s)
size_t dtls1_min_mtu (SSL *s)
size_t DTLS_get_data_mtu (const SSL *s)
Variables
const SSL3_ENC_METHOD DTLSv1_enc_data
const SSL3_ENC_METHOD DTLSv1_2_enc_data
Macro Definition Documentation
LISTEN_SEND_VERIFY_REQUEST
#define LISTEN_SEND_VERIFY_REQUEST 1
Definition at line 418 of file d1_lib.c.
LISTEN_SUCCESS
#define LISTEN_SUCCESS 2
Definition at line 417 of file d1_lib.c.
USE_SOCKETS
#define USE_SOCKETS
Definition at line 11 of file d1_lib.c.
Function Documentation
dtls1_check_timeout_num()
int dtls1_check_timeout_num (SSL * s)
Definition at line 341 of file d1_lib.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_GET_FALLBACK_MTU, DTLS1_TMO_ALERT_COUNT, NULL, SSL_F_DTLS1_CHECK_TIMEOUT_NUM, SSL_get_options(), SSL_get_wbio(), SSL_OP_NO_QUERY_MTU, SSL_R_READ_TIMEOUT_EXPIRED, and SSLerr.
Referenced by dtls1_handle_timeout().
dtls1_clear()
void dtls1_clear (SSL * s)
Definition at line 159 of file d1_lib.c.
References DTLS_RECORD_LAYER_clear().
dtls1_clear_received_buffer()
void dtls1_clear_received_buffer (SSL * s)
Definition at line 119 of file d1_lib.c.
References dtls1_hm_fragment_free(), NULL, pitem_free(), and pqueue_pop().
Referenced by dtls1_reset_seq_numbers().
dtls1_clear_sent_buffer()
void dtls1_clear_sent_buffer (SSL * s)
Definition at line 131 of file d1_lib.c.
References dtls1_hm_fragment_free(), NULL, pitem_free(), and pqueue_pop().
Referenced by dtls1_stop_timer(), and ossl_statem_server_pre_work().
dtls1_ctrl()
long dtls1_ctrl (SSL * s, int cmd, long larg, void * parg)
Definition at line 203 of file d1_lib.c.
dtls1_default_timeout()
long dtls1_default_timeout (void)
Definition at line 66 of file d1_lib.c.
dtls1_double_timeout()
void dtls1_double_timeout (SSL * s)
Definition at line 321 of file d1_lib.c.
References dtls1_start_timer().
Referenced by dtls1_handle_timeout().
dtls1_free()
void dtls1_free (SSL * s)
Definition at line 144 of file d1_lib.c.
References DTLS_RECORD_LAYER_free(), and ssl3_free().
dtls1_get_timeout()
struct timeval* dtls1_get_timeout (SSL * s, struct timeval * timeleft)
Definition at line 263 of file d1_lib.c.
References NULL.
Referenced by dtls1_is_timer_expired().
dtls1_handle_timeout()
int dtls1_handle_timeout (SSL * s)
Definition at line 365 of file d1_lib.c.
References dtls1_check_timeout_num(), dtls1_double_timeout(), dtls1_is_timer_expired(), dtls1_retransmit_buffered_messages(), dtls1_start_timer(), and DTLS1_TMO_READ_COUNT.
Referenced by dtls1_read_failed().
dtls1_is_timer_expired()
int dtls1_is_timer_expired (SSL * s)
Definition at line 303 of file d1_lib.c.
References dtls1_get_timeout(), and NULL.
Referenced by dtls1_handle_timeout(), and dtls1_read_failed().
dtls1_min_mtu()
size_t dtls1_min_mtu (SSL * s)
Definition at line 922 of file d1_lib.c.
Referenced by dtls1_query_mtu().
dtls1_new()
int dtls1_new (SSL * s)
Definition at line 75 of file d1_lib.c.
References DTLS1_STATE::buffered_messages, DTLS1_STATE::cookie_len, DTLS_RECORD_LAYER_new(), DTLS1_STATE::link_mtu, DTLS1_STATE::mtu, NULL, OPENSSL_free, OPENSSL_zalloc, pqueue_free(), pqueue_new(), DTLS1_STATE::sent_messages, ssl3_free(), and ssl3_new().
dtls1_query_mtu()
int dtls1_query_mtu (SSL * s)
Definition at line 886 of file d1_lib.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_QUERY_MTU, BIO_CTRL_DGRAM_SET_MTU, BIO_dgram_get_mtu_overhead, dtls1_min_mtu(), NULL, SSL_get_options(), SSL_get_wbio(), and SSL_OP_NO_QUERY_MTU.
dtls1_shutdown()
int dtls1_shutdown (SSL * s)
Definition at line 861 of file d1_lib.c.
dtls1_start_timer()
void dtls1_start_timer (SSL * s)
Definition at line 239 of file d1_lib.c.
References BIO_dgram_is_sctp(), and SSL_get_wbio().
Referenced by dtls1_double_timeout(), and dtls1_handle_timeout().
dtls1_stop_timer()
void dtls1_stop_timer (SSL * s)
Definition at line 329 of file d1_lib.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_SET_NEXT_TIMEOUT, dtls1_clear_sent_buffer(), and SSL_get_rbio().
DTLS_get_data_mtu()
size_t DTLS_get_data_mtu (const SSL * s)
Definition at line 927 of file d1_lib.c.
References DTLS1_RT_HEADER_LENGTH, NULL, ssl_cipher_get_overhead(), SSL_get_current_cipher(), and SSL_READ_ETM.
DTLSv1_listen()
int DTLSv1_listen (SSL * s, BIO_ADDR * client)
Definition at line 421 of file d1_lib.c.
Variable Documentation
DTLSv1_2_enc_data
const SSL3_ENC_METHOD DTLSv1_2_enc_data
Initial value:
= {
    tls1_enc,
    tls1_mac,
    tls1_setup_key_block,
    tls1_generate_master_secret,
    tls1_change_cipher_state,
    tls1_final_finish_mac,
    TLS_MD_CLIENT_FINISH_CONST, TLS_MD_CLIENT_FINISH_CONST_SIZE,
    TLS_MD_SERVER_FINISH_CONST, TLS_MD_SERVER_FINISH_CONST_SIZE,
    tls1_alert_code,
    tls1_export_keying_material,
    SSL_ENC_FLAG_DTLS | SSL_ENC_FLAG_EXPLICIT_IV | SSL_ENC_FLAG_SIGALGS
        | SSL_ENC_FLAG_SHA256_PRF | SSL_ENC_FLAG_TLS1_2_CIPHERS,
    dtls1_set_handshake_header,
    dtls1_close_construct_packet,
    dtls1_handshake_write
}
Definition at line 48 of file d1_lib.c.
DTLSv1_enc_data
const SSL3_ENC_METHOD DTLSv1_enc_data
Initial value:
= {
    tls1_enc,
    tls1_mac,
    tls1_setup_key_block,
    tls1_generate_master_secret,
    tls1_change_cipher_state,
    tls1_final_finish_mac,
    TLS_MD_CLIENT_FINISH_CONST, TLS_MD_CLIENT_FINISH_CONST_SIZE,
    TLS_MD_SERVER_FINISH_CONST, TLS_MD_SERVER_FINISH_CONST_SIZE,
    tls1_alert_code,
    tls1_export_keying_material,
    SSL_ENC_FLAG_DTLS | SSL_ENC_FLAG_EXPLICIT_IV,
    dtls1_set_handshake_header,
    dtls1_close_construct_packet,
    dtls1_handshake_write
}
Definition at line 31 of file d1_lib.c.