crypto/des/des_enc.c File Reference
des_enc.c File Reference
#include <openssl/crypto.h>
#include "des_locl.h"
#include "spr.h"
#include "ncbc_enc.c"
Functions
void DES_encrypt1 (DES_LONG *data, DES_key_schedule *ks, int enc)
void DES_encrypt2 (DES_LONG *data, DES_key_schedule *ks, int enc)
void DES_encrypt3 (DES_LONG *data, DES_key_schedule *ks1, DES_key_schedule *ks2, DES_key_schedule *ks3)
void DES_decrypt3 (DES_LONG *data, DES_key_schedule *ks1, DES_key_schedule *ks2, DES_key_schedule *ks3)
void DES_ede3_cbc_encrypt (const unsigned char *input, unsigned char *output, long length, DES_key_schedule *ks1, DES_key_schedule *ks2, DES_key_schedule *ks3, DES_cblock *ivec, int enc)
Function Documentation
DES_decrypt3()
void DES_decrypt3 (DES_LONG * data, DES_key_schedule * ks1, DES_key_schedule * ks2, DES_key_schedule * ks3)
Definition at line 171 of file des_enc.c.
References DES_DECRYPT, DES_ENCRYPT, DES_encrypt2(), FP, and IP.
DES_ede3_cbc_encrypt()
void DES_ede3_cbc_encrypt (const unsigned char * input, unsigned char * output, long length, DES_key_schedule * ks1, DES_key_schedule * ks2, DES_key_schedule * ks3, DES_cblock * ivec, int enc)
Definition at line 196 of file des_enc.c.
DES_encrypt1()
void DES_encrypt1 (DES_LONG * data, DES_key_schedule * ks, int enc)
Definition at line 14 of file des_enc.c.
References D_ENCRYPT, DES_key_schedule::deslong, FP, IP, DES_key_schedule::ks, ROTATE, t, and u.
DES_encrypt2()
void DES_encrypt2 (DES_LONG * data, DES_key_schedule * ks, int enc)
Definition at line 86 of file des_enc.c.
References D_ENCRYPT, DES_key_schedule::deslong, DES_key_schedule::ks, ROTATE, t, and u.
Referenced by DES_decrypt3(), and DES_encrypt3().
DES_encrypt3()
void DES_encrypt3 (DES_LONG * data, DES_key_schedule * ks1, DES_key_schedule * ks2, DES_key_schedule * ks3)
Definition at line 151 of file des_enc.c.
References DES_DECRYPT, DES_ENCRYPT, DES_encrypt2(), FP, and IP.