include/openssl/des.h File Reference
des.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/e_os2.h>
Data Structures
struct DES_key_schedule
Macros
#define DES_KEY_SZ (sizeof(DES_cblock))
#define DES_SCHEDULE_SZ (sizeof(DES_key_schedule))
#define DES_ENCRYPT 1
#define DES_DECRYPT 0
#define DES_CBC_MODE 0
#define DES_PCBC_MODE 1
#define DES_ecb2_encrypt(i, o, k1, k2, e) DES_ecb3_encrypt((i),(o),(k1),(k2),(k1),(e))
#define DES_ede2_cbc_encrypt(i, o, l, k1, k2, iv, e) DES_ede3_cbc_encrypt((i),(o),(l),(k1),(k2),(k1),(iv),(e))
#define DES_ede2_cfb64_encrypt(i, o, l, k1, k2, iv, n, e) DES_ede3_cfb64_encrypt((i),(o),(l),(k1),(k2),(k1),(iv),(n),(e))
#define DES_ede2_ofb64_encrypt(i, o, l, k1, k2, iv, n) DES_ede3_ofb64_encrypt((i),(o),(l),(k1),(k2),(k1),(iv),(n))
#define DES_check_key OPENSSL_GLOBAL_REF(DES_check_key)
#define DES_fixup_key_parity DES_set_odd_parity
Typedefs
typedef unsigned int DES_LONG
typedef unsigned char DES_cblock[8]
typedef unsigned char const_DES_cblock[8]
Functions
OPENSSL_DECLARE_GLOBAL (int, DES_check_key)
const char * DES_options (void)
void DES_ecb3_encrypt (const_DES_cblock *input, DES_cblock *output, DES_key_schedule *ks1, DES_key_schedule *ks2, DES_key_schedule *ks3, int enc)
DES_LONG DES_cbc_cksum (const unsigned char *input, DES_cblock *output, long length, DES_key_schedule *schedule, const_DES_cblock *ivec)
void DES_cbc_encrypt (const unsigned char *input, unsigned char *output, long length, DES_key_schedule *schedule, DES_cblock *ivec, int enc)
void DES_ncbc_encrypt (const unsigned char *input, unsigned char *output, long length, DES_key_schedule *schedule, DES_cblock *ivec, int enc)
void DES_xcbc_encrypt (const unsigned char *input, unsigned char *output, long length, DES_key_schedule *schedule, DES_cblock *ivec, const_DES_cblock *inw, const_DES_cblock *outw, int enc)
void DES_cfb_encrypt (const unsigned char *in, unsigned char *out, int numbits, long length, DES_key_schedule *schedule, DES_cblock *ivec, int enc)
void DES_ecb_encrypt (const_DES_cblock *input, DES_cblock *output, DES_key_schedule *ks, int enc)
void DES_encrypt1 (DES_LONG *data, DES_key_schedule *ks, int enc)
void DES_encrypt2 (DES_LONG *data, DES_key_schedule *ks, int enc)
void DES_encrypt3 (DES_LONG *data, DES_key_schedule *ks1, DES_key_schedule *ks2, DES_key_schedule *ks3)
void DES_decrypt3 (DES_LONG *data, DES_key_schedule *ks1, DES_key_schedule *ks2, DES_key_schedule *ks3)
void DES_ede3_cbc_encrypt (const unsigned char *input, unsigned char *output, long length, DES_key_schedule *ks1, DES_key_schedule *ks2, DES_key_schedule *ks3, DES_cblock *ivec, int enc)
void DES_ede3_cfb64_encrypt (const unsigned char *in, unsigned char *out, long length, DES_key_schedule *ks1, DES_key_schedule *ks2, DES_key_schedule *ks3, DES_cblock *ivec, int *num, int enc)
void DES_ede3_cfb_encrypt (const unsigned char *in, unsigned char *out, int numbits, long length, DES_key_schedule *ks1, DES_key_schedule *ks2, DES_key_schedule *ks3, DES_cblock *ivec, int enc)
void DES_ede3_ofb64_encrypt (const unsigned char *in, unsigned char *out, long length, DES_key_schedule *ks1, DES_key_schedule *ks2, DES_key_schedule *ks3, DES_cblock *ivec, int *num)
char * DES_fcrypt (const char *buf, const char *salt, char *ret)
char * DES_crypt (const char *buf, const char *salt)
void DES_ofb_encrypt (const unsigned char *in, unsigned char *out, int numbits, long length, DES_key_schedule *schedule, DES_cblock *ivec)
void DES_pcbc_encrypt (const unsigned char *input, unsigned char *output, long length, DES_key_schedule *schedule, DES_cblock *ivec, int enc)
DES_LONG DES_quad_cksum (const unsigned char *input, DES_cblock output[], long length, int out_count, DES_cblock *seed)
int DES_random_key (DES_cblock *ret)
void DES_set_odd_parity (DES_cblock *key)
int DES_check_key_parity (const_DES_cblock *key)
int DES_is_weak_key (const_DES_cblock *key)
int DES_set_key (const_DES_cblock *key, DES_key_schedule *schedule)
int DES_key_sched (const_DES_cblock *key, DES_key_schedule *schedule)
int DES_set_key_checked (const_DES_cblock *key, DES_key_schedule *schedule)
void DES_set_key_unchecked (const_DES_cblock *key, DES_key_schedule *schedule)
void DES_string_to_key (const char *str, DES_cblock *key)
void DES_string_to_2keys (const char *str, DES_cblock *key1, DES_cblock *key2)
void DES_cfb64_encrypt (const unsigned char *in, unsigned char *out, long length, DES_key_schedule *schedule, DES_cblock *ivec, int *num, int enc)
void DES_ofb64_encrypt (const unsigned char *in, unsigned char *out, long length, DES_key_schedule *schedule, DES_cblock *ivec, int *num)
Macro Definition Documentation
DES_CBC_MODE
#define DES_CBC_MODE 0
Definition at line 51 of file des.h.
DES_check_key
#define DES_check_key OPENSSL_GLOBAL_REF(DES_check_key)
Definition at line 67 of file des.h.
Referenced by DES_set_key().
DES_DECRYPT
#define DES_DECRYPT 0
Definition at line 49 of file des.h.
Referenced by DES_decrypt3(), and DES_encrypt3().
DES_ecb2_encrypt
#define DES_ecb2_encrypt (i, o, k1, k2, e) DES_ecb3_encrypt((i),(o),(k1),(k2),(k1),(e))
Definition at line 54 of file des.h.
DES_ede2_cbc_encrypt
#define DES_ede2_cbc_encrypt (i, o, l, k1, k2, iv, e) DES_ede3_cbc_encrypt((i),(o),(l),(k1),(k2),(k1),(iv),(e))
Definition at line 57 of file des.h.
DES_ede2_cfb64_encrypt
#define DES_ede2_cfb64_encrypt (i, o, l, k1, k2, iv, n, e) DES_ede3_cfb64_encrypt((i),(o),(l),(k1),(k2),(k1),(iv),(n),(e))
Definition at line 60 of file des.h.
DES_ede2_ofb64_encrypt
#define DES_ede2_ofb64_encrypt (i, o, l, k1, k2, iv, n) DES_ede3_ofb64_encrypt((i),(o),(l),(k1),(k2),(k1),(iv),(n))
Definition at line 63 of file des.h.
DES_ENCRYPT
#define DES_ENCRYPT 1
Definition at line 48 of file des.h.
Referenced by DES_decrypt3(), and DES_encrypt3().
DES_fixup_key_parity
#define DES_fixup_key_parity DES_set_odd_parity
Definition at line 167 of file des.h.
DES_KEY_SZ
#define DES_KEY_SZ (sizeof(DES_cblock))
Definition at line 45 of file des.h.
Referenced by DES_check_key_parity(), and DES_set_odd_parity().
DES_PCBC_MODE
#define DES_PCBC_MODE 1
Definition at line 52 of file des.h.
DES_SCHEDULE_SZ
#define DES_SCHEDULE_SZ (sizeof(DES_key_schedule))
Definition at line 46 of file des.h.
Typedef Documentation
const_DES_cblock
typedef unsigned char const_DES_cblock[8]
Definition at line 29 of file des.h.
DES_cblock
typedef unsigned char DES_cblock[8]
Definition at line 28 of file des.h.
DES_LONG
typedef unsigned int DES_LONG
Definition at line 21 of file des.h.
Function Documentation
DES_cbc_cksum()
DES_LONG DES_cbc_cksum (const unsigned char * input, DES_cblock * output, long length, DES_key_schedule * schedule, const_DES_cblock * ivec)
Definition at line 12 of file cbc_cksm.c.
Referenced by DES_string_to_key().
DES_cbc_encrypt()
void DES_cbc_encrypt (const unsigned char * input, unsigned char * output, long length, DES_key_schedule * schedule, DES_cblock * ivec, int enc)
DES_cfb64_encrypt()
void DES_cfb64_encrypt (const unsigned char * in, unsigned char * out, long length, DES_key_schedule * schedule, DES_cblock * ivec, int * num, int enc)
Definition at line 18 of file cfb64enc.c.
DES_cfb_encrypt()
void DES_cfb_encrypt (const unsigned char * in, unsigned char * out, int numbits, long length, DES_key_schedule * schedule, DES_cblock * ivec, int enc)
Definition at line 24 of file cfb_enc.c.
DES_check_key_parity()
int DES_check_key_parity (const_DES_cblock * key)
Definition at line 62 of file set_key.c.
References DES_KEY_SZ.
Referenced by DES_set_key_checked().
DES_crypt()
char* DES_crypt (const char * buf, const char * salt)
Definition at line 58 of file fcrypt.c.
DES_decrypt3()
void DES_decrypt3 (DES_LONG * data, DES_key_schedule * ks1, DES_key_schedule * ks2, DES_key_schedule * ks3)
Definition at line 171 of file des_enc.c.
References DES_DECRYPT, DES_ENCRYPT, DES_encrypt2(), FP, and IP.
DES_ecb3_encrypt()
void DES_ecb3_encrypt (const_DES_cblock * input, DES_cblock * output, DES_key_schedule * ks1, DES_key_schedule * ks2, DES_key_schedule * ks3, int enc)
Definition at line 12 of file ecb3_enc.c.
DES_ecb_encrypt()
void DES_ecb_encrypt (const_DES_cblock * input, DES_cblock * output, DES_key_schedule * ks, int enc)
Definition at line 33 of file ecb_enc.c.
DES_ede3_cbc_encrypt()
void DES_ede3_cbc_encrypt (const unsigned char * input, unsigned char * output, long length, DES_key_schedule * ks1, DES_key_schedule * ks2, DES_key_schedule * ks3, DES_cblock * ivec, int enc)
Definition at line 196 of file des_enc.c.
DES_ede3_cfb64_encrypt()
void DES_ede3_cfb64_encrypt (const unsigned char * in, unsigned char * out, long length, DES_key_schedule * ks1, DES_key_schedule * ks2, DES_key_schedule * ks3, DES_cblock * ivec, int * num, int enc)
Definition at line 19 of file cfb64ede.c.
DES_ede3_cfb_encrypt()
void DES_ede3_cfb_encrypt (const unsigned char * in, unsigned char * out, int numbits, long length, DES_key_schedule * ks1, DES_key_schedule * ks2, DES_key_schedule * ks3, DES_cblock * ivec, int enc)
Definition at line 86 of file cfb64ede.c.
DES_ede3_ofb64_encrypt()
void DES_ede3_ofb64_encrypt (const unsigned char * in, unsigned char * out, long length, DES_key_schedule * ks1, DES_key_schedule * ks2, DES_key_schedule * ks3, DES_cblock * ivec, int * num)
DES_encrypt1()
void DES_encrypt1 (DES_LONG * data, DES_key_schedule * ks, int enc)
Definition at line 14 of file des_enc.c.
References D_ENCRYPT, DES_key_schedule::deslong, FP, IP, DES_key_schedule::ks, ROTATE, t, and u.
DES_encrypt2()
void DES_encrypt2 (DES_LONG * data, DES_key_schedule * ks, int enc)
Definition at line 86 of file des_enc.c.
References D_ENCRYPT, DES_key_schedule::deslong, DES_key_schedule::ks, ROTATE, t, and u.
Referenced by DES_decrypt3(), and DES_encrypt3().
DES_encrypt3()
void DES_encrypt3 (DES_LONG * data, DES_key_schedule * ks1, DES_key_schedule * ks2, DES_key_schedule * ks3)
Definition at line 151 of file des_enc.c.
References DES_DECRYPT, DES_ENCRYPT, DES_encrypt2(), FP, and IP.
DES_fcrypt()
char* DES_fcrypt (const char * buf, const char * salt, char * ret)
Definition at line 91 of file fcrypt.c.
DES_is_weak_key()
int DES_is_weak_key (const_DES_cblock * key)
Definition at line 105 of file set_key.c.
References NUM_WEAK_KEY.
Referenced by DES_set_key_checked().
DES_key_sched()
int DES_key_sched (const_DES_cblock * key, DES_key_schedule * schedule)
Definition at line 378 of file set_key.c.
References DES_set_key().
DES_ncbc_encrypt()
void DES_ncbc_encrypt (const unsigned char * input, unsigned char * output, long length, DES_key_schedule * schedule, DES_cblock * ivec, int enc)
Definition at line 22 of file ncbc_enc.c.
DES_ofb64_encrypt()
void DES_ofb64_encrypt (const unsigned char * in, unsigned char * out, long length, DES_key_schedule * schedule, DES_cblock * ivec, int * num)
DES_ofb_encrypt()
void DES_ofb_encrypt (const unsigned char * in, unsigned char * out, int numbits, long length, DES_key_schedule * schedule, DES_cblock * ivec)
Definition at line 18 of file ofb_enc.c.
DES_options()
const char* DES_options (void)
Definition at line 15 of file ecb_enc.c.
DES_pcbc_encrypt()
void DES_pcbc_encrypt (const unsigned char * input, unsigned char * output, long length, DES_key_schedule * schedule, DES_cblock * ivec, int enc)
Definition at line 12 of file pcbc_enc.c.
DES_quad_cksum()
DES_LONG DES_quad_cksum (const unsigned char * input, DES_cblock output[], long length, int out_count, DES_cblock * seed)
Definition at line 28 of file qud_cksm.c.
DES_random_key()
int DES_random_key (DES_cblock * ret)
Definition at line 13 of file rand_key.c.
DES_set_key()
int DES_set_key (const_DES_cblock * key, DES_key_schedule * schedule)
Definition at line 287 of file set_key.c.
References DES_check_key, DES_set_key_checked(), and DES_set_key_unchecked().
Referenced by DES_key_sched().
DES_set_key_checked()
int DES_set_key_checked (const_DES_cblock * key, DES_key_schedule * schedule)
Definition at line 302 of file set_key.c.
References DES_check_key_parity(), DES_is_weak_key(), and DES_set_key_unchecked().
Referenced by DES_set_key().
DES_set_key_unchecked()
void DES_set_key_unchecked (const_DES_cblock * key, DES_key_schedule * schedule)
Definition at line 312 of file set_key.c.
Referenced by DES_set_key(), DES_set_key_checked(), and DES_string_to_key().
DES_set_odd_parity()
void DES_set_odd_parity (DES_cblock * key)
Definition at line 54 of file set_key.c.
References DES_KEY_SZ.
Referenced by DES_string_to_key().
DES_string_to_2keys()
void DES_string_to_2keys (const char * str, DES_cblock * key1, DES_cblock * key2)
Definition at line 45 of file str2key.c.
DES_string_to_key()
void DES_string_to_key (const char * str, DES_cblock * key)
Definition at line 13 of file str2key.c.
References DES_cbc_cksum(), DES_set_key_unchecked(), DES_set_odd_parity(), and OPENSSL_cleanse().
DES_xcbc_encrypt()
void DES_xcbc_encrypt (const unsigned char * input, unsigned char * output, long length, DES_key_schedule * schedule, DES_cblock * ivec, const_DES_cblock * inw, const_DES_cblock * outw, int enc)
Definition at line 14 of file xcbc_enc.c.
OPENSSL_DECLARE_GLOBAL()
OPENSSL_DECLARE_GLOBAL (int , DES_check_key)