include/openssl/dh.h File Reference
dh.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/e_os2.h>
#include <openssl/bio.h>
#include <openssl/asn1.h>
#include <openssl/ossl_typ.h>
#include <openssl/bn.h>
Macros
#define OPENSSL_DH_MAX_MODULUS_BITS 10000
#define OPENSSL_DH_FIPS_MIN_MODULUS_BITS 1024
#define DH_FLAG_CACHE_MONT_P 0x01
#define DH_FLAG_NO_EXP_CONSTTIME 0x00
#define DH_FLAG_FIPS_METHOD 0x0400
#define DH_FLAG_NON_FIPS_ALLOW 0x0400
#define DH_GENERATOR_2 2
#define DH_GENERATOR_5 5
#define DH_CHECK_P_NOT_PRIME 0x01
#define DH_CHECK_P_NOT_SAFE_PRIME 0x02
#define DH_UNABLE_TO_CHECK_GENERATOR 0x04
#define DH_NOT_SUITABLE_GENERATOR 0x08
#define DH_CHECK_Q_NOT_PRIME 0x10
#define DH_CHECK_INVALID_Q_VALUE 0x20
#define DH_CHECK_INVALID_J_VALUE 0x40
#define DH_CHECK_PUBKEY_TOO_SMALL 0x01
#define DH_CHECK_PUBKEY_TOO_LARGE 0x02
#define DH_CHECK_PUBKEY_INVALID 0x04
#define DH_CHECK_P_NOT_STRONG_PRIME DH_CHECK_P_NOT_SAFE_PRIME
#define d2i_DHparams_fp(fp, x)
#define i2d_DHparams_fp(fp, x)
#define d2i_DHparams_bio(bp, x) ASN1_d2i_bio_of(DH,DH_new,d2i_DHparams,bp,x)
#define i2d_DHparams_bio(bp, x) ASN1_i2d_bio_of_const(DH,i2d_DHparams,bp,x)
#define DH_get_ex_new_index(l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_DH, l, p, newf, dupf, freef)
#define EVP_PKEY_CTX_set_dh_paramgen_prime_len(ctx, len)
#define EVP_PKEY_CTX_set_dh_paramgen_subprime_len(ctx, len)
#define EVP_PKEY_CTX_set_dh_paramgen_type(ctx, typ)
#define EVP_PKEY_CTX_set_dh_paramgen_generator(ctx, gen)
#define EVP_PKEY_CTX_set_dh_rfc5114(ctx, gen)
#define EVP_PKEY_CTX_set_dhx_rfc5114(ctx, gen)
#define EVP_PKEY_CTX_set_dh_kdf_type(ctx, kdf)
#define EVP_PKEY_CTX_get_dh_kdf_type(ctx)
#define EVP_PKEY_CTX_set0_dh_kdf_oid(ctx, oid)
#define EVP_PKEY_CTX_get0_dh_kdf_oid(ctx, poid)
#define EVP_PKEY_CTX_set_dh_kdf_md(ctx, md)
#define EVP_PKEY_CTX_get_dh_kdf_md(ctx, pmd)
#define EVP_PKEY_CTX_set_dh_kdf_outlen(ctx, len)
#define EVP_PKEY_CTX_get_dh_kdf_outlen(ctx, plen)
#define EVP_PKEY_CTX_set0_dh_kdf_ukm(ctx, p, plen)
#define EVP_PKEY_CTX_get0_dh_kdf_ukm(ctx, p)
#define EVP_PKEY_CTRL_DH_PARAMGEN_PRIME_LEN (EVP_PKEY_ALG_CTRL + 1)
#define EVP_PKEY_CTRL_DH_PARAMGEN_GENERATOR (EVP_PKEY_ALG_CTRL + 2)
#define EVP_PKEY_CTRL_DH_RFC5114 (EVP_PKEY_ALG_CTRL + 3)
#define EVP_PKEY_CTRL_DH_PARAMGEN_SUBPRIME_LEN (EVP_PKEY_ALG_CTRL + 4)
#define EVP_PKEY_CTRL_DH_PARAMGEN_TYPE (EVP_PKEY_ALG_CTRL + 5)
#define EVP_PKEY_CTRL_DH_KDF_TYPE (EVP_PKEY_ALG_CTRL + 6)
#define EVP_PKEY_CTRL_DH_KDF_MD (EVP_PKEY_ALG_CTRL + 7)
#define EVP_PKEY_CTRL_GET_DH_KDF_MD (EVP_PKEY_ALG_CTRL + 8)
#define EVP_PKEY_CTRL_DH_KDF_OUTLEN (EVP_PKEY_ALG_CTRL + 9)
#define EVP_PKEY_CTRL_GET_DH_KDF_OUTLEN (EVP_PKEY_ALG_CTRL + 10)
#define EVP_PKEY_CTRL_DH_KDF_UKM (EVP_PKEY_ALG_CTRL + 11)
#define EVP_PKEY_CTRL_GET_DH_KDF_UKM (EVP_PKEY_ALG_CTRL + 12)
#define EVP_PKEY_CTRL_DH_KDF_OID (EVP_PKEY_ALG_CTRL + 13)
#define EVP_PKEY_CTRL_GET_DH_KDF_OID (EVP_PKEY_ALG_CTRL + 14)
#define EVP_PKEY_DH_KDF_NONE 1
#define EVP_PKEY_DH_KDF_X9_42 2
#define DH_F_COMPUTE_KEY 102
#define DH_F_DHPARAMS_PRINT_FP 101
#define DH_F_DH_BUILTIN_GENPARAMS 106
#define DH_F_DH_CMS_DECRYPT 114
#define DH_F_DH_CMS_SET_PEERKEY 115
#define DH_F_DH_CMS_SET_SHARED_INFO 116
#define DH_F_DH_METH_DUP 117
#define DH_F_DH_METH_NEW 118
#define DH_F_DH_METH_SET1_NAME 119
#define DH_F_DH_NEW_METHOD 105
#define DH_F_DH_PARAM_DECODE 107
#define DH_F_DH_PRIV_DECODE 110
#define DH_F_DH_PRIV_ENCODE 111
#define DH_F_DH_PUB_DECODE 108
#define DH_F_DH_PUB_ENCODE 109
#define DH_F_DO_DH_PRINT 100
#define DH_F_GENERATE_KEY 103
#define DH_F_PKEY_DH_DERIVE 112
#define DH_F_PKEY_DH_KEYGEN 113
#define DH_R_BAD_GENERATOR 101
#define DH_R_BN_DECODE_ERROR 109
#define DH_R_BN_ERROR 106
#define DH_R_DECODE_ERROR 104
#define DH_R_INVALID_PUBKEY 102
#define DH_R_KDF_PARAMETER_ERROR 112
#define DH_R_KEYS_NOT_SET 108
#define DH_R_MODULUS_TOO_LARGE 103
#define DH_R_NO_PARAMETERS_SET 107
#define DH_R_NO_PRIVATE_VALUE 100
#define DH_R_PARAMETER_ENCODING_ERROR 105
#define DH_R_PEER_KEY_ERROR 111
#define DH_R_SHARED_INFO_ERROR 113
Functions
DH * DHparams_dup (DH *)
const DH_METHOD * DH_OpenSSL (void)
void DH_set_default_method (const DH_METHOD *meth)
const DH_METHOD * DH_get_default_method (void)
int DH_set_method (DH *dh, const DH_METHOD *meth)
DH * DH_new_method (ENGINE *engine)
DH * DH_new (void)
void DH_free (DH *dh)
int DH_up_ref (DH *dh)
int DH_bits (const DH *dh)
int DH_size (const DH *dh)
int DH_security_bits (const DH *dh)
int DH_set_ex_data (DH *d, int idx, void *arg)
void * DH_get_ex_data (DH *d, int idx)
DEPRECATEDIN_0_9_8 (DH *DH_generate_parameters(int prime_len, int generator, void(*callback)(int, int, void *), void *cb_arg)) int DH_generate_parameters_ex(DH *dh
int DH_check_params (const DH *dh, int *ret)
int DH_check (const DH *dh, int *codes)
int DH_check_pub_key (const DH *dh, const BIGNUM *pub_key, int *codes)
int DH_generate_key (DH *dh)
int DH_compute_key (unsigned char *key, const BIGNUM *pub_key, DH *dh)
int DH_compute_key_padded (unsigned char *key, const BIGNUM *pub_key, DH *dh)
DH * d2i_DHparams (DH **a, const unsigned char **pp, long length)
int i2d_DHparams (const DH *a, unsigned char **pp)
DH * d2i_DHxparams (DH **a, const unsigned char **pp, long length)
int i2d_DHxparams (const DH *a, unsigned char **pp)
int DHparams_print_fp (FILE *fp, const DH *x)
int DHparams_print (BIO *bp, const DH *x)
DH * DH_get_1024_160 (void)
DH * DH_get_2048_224 (void)
DH * DH_get_2048_256 (void)
int DH_KDF_X9_42 (unsigned char *out, size_t outlen, const unsigned char *Z, size_t Zlen, ASN1_OBJECT *key_oid, const unsigned char *ukm, size_t ukmlen, const EVP_MD *md)
void DH_get0_pqg (const DH *dh, const BIGNUM **p, const BIGNUM **q, const BIGNUM **g)
int DH_set0_pqg (DH *dh, BIGNUM *p, BIGNUM *q, BIGNUM *g)
void DH_get0_key (const DH *dh, const BIGNUM **pub_key, const BIGNUM **priv_key)
int DH_set0_key (DH *dh, BIGNUM *pub_key, BIGNUM *priv_key)
void DH_clear_flags (DH *dh, int flags)
int DH_test_flags (const DH *dh, int flags)
void DH_set_flags (DH *dh, int flags)
ENGINE * DH_get0_engine (DH *d)
long DH_get_length (const DH *dh)
int DH_set_length (DH *dh, long length)
DH_METHOD * DH_meth_new (const char *name, int flags)
void DH_meth_free (DH_METHOD *dhm)
DH_METHOD * DH_meth_dup (const DH_METHOD *dhm)
const char * DH_meth_get0_name (const DH_METHOD *dhm)
int DH_meth_set1_name (DH_METHOD *dhm, const char *name)
int DH_meth_get_flags (DH_METHOD *dhm)
int DH_meth_set_flags (DH_METHOD *dhm, int flags)
void * DH_meth_get0_app_data (const DH_METHOD *dhm)
int DH_meth_set0_app_data (DH_METHOD *dhm, void *app_data)
int DH_meth_set_generate_key (DH_METHOD *dhm, int(*generate_key)(DH *))
int DH_meth_set_compute_key (DH_METHOD *dhm, int(*compute_key)(unsigned char *key, const BIGNUM *pub_key, DH *dh))
int DH_meth_set_bn_mod_exp (DH_METHOD *dhm, int(*bn_mod_exp)(const DH *, BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *, BN_MONT_CTX *))
int DH_meth_set_init (DH_METHOD *dhm, int(*init)(DH *))
int DH_meth_set_finish (DH_METHOD *dhm, int(*finish)(DH *))
int DH_meth_set_generate_params (DH_METHOD *dhm, int(*generate_params)(DH *, int, int, BN_GENCB *))
int ERR_load_DH_strings (void)
Variables
int prime_len
int int generator
int int BN_GENCB * cb
int(*)(DH *) DH_meth_get_generate_key (const DH_METHOD *dhm)
int(*)(unsigned char *key, const BIGNUM *pub_key, DH *dh) DH_meth_get_compute_key (const DH_METHOD *dhm)
int(*)(const DH *, BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *, BN_MONT_CTX *) DH_meth_get_bn_mod_exp (const DH_METHOD *dhm)
int(*)(DH *) DH_meth_get_init (const DH_METHOD *dhm)
int(*)(DH *) DH_meth_get_finish (const DH_METHOD *dhm)
int(*)(DH *, int, int, BN_GENCB *) DH_meth_get_generate_params (const DH_METHOD *dhm)
Macro Definition Documentation
d2i_DHparams_bio
#define d2i_DHparams_bio (bp, x) ASN1_d2i_bio_of(DH,DH_new,d2i_DHparams,bp,x)
Definition at line 94 of file dh.h.
d2i_DHparams_fp
#define d2i_DHparams_fp (fp, x)
Value:
(DH *)ASN1_d2i_fp((char *(*)())DH_new, \
                (char *(*)())d2i_DHparams,(fp),(unsigned char **)(x))
Definition at line 90 of file dh.h.
DH_CHECK_INVALID_J_VALUE
#define DH_CHECK_INVALID_J_VALUE 0x40
Definition at line 77 of file dh.h.
DH_CHECK_INVALID_Q_VALUE
#define DH_CHECK_INVALID_Q_VALUE 0x20
Definition at line 76 of file dh.h.
DH_CHECK_P_NOT_PRIME
#define DH_CHECK_P_NOT_PRIME 0x01
Definition at line 71 of file dh.h.
DH_CHECK_P_NOT_SAFE_PRIME
#define DH_CHECK_P_NOT_SAFE_PRIME 0x02
Definition at line 72 of file dh.h.
DH_CHECK_P_NOT_STRONG_PRIME
#define DH_CHECK_P_NOT_STRONG_PRIME DH_CHECK_P_NOT_SAFE_PRIME
Definition at line 88 of file dh.h.
DH_CHECK_PUBKEY_INVALID
#define DH_CHECK_PUBKEY_INVALID 0x04
Definition at line 82 of file dh.h.
DH_CHECK_PUBKEY_TOO_LARGE
#define DH_CHECK_PUBKEY_TOO_LARGE 0x02
Definition at line 81 of file dh.h.
DH_CHECK_PUBKEY_TOO_SMALL
#define DH_CHECK_PUBKEY_TOO_SMALL 0x01
Definition at line 80 of file dh.h.
DH_CHECK_Q_NOT_PRIME
#define DH_CHECK_Q_NOT_PRIME 0x10
Definition at line 75 of file dh.h.
DH_F_COMPUTE_KEY
#define DH_F_COMPUTE_KEY 102
Definition at line 305 of file dh.h.
DH_F_DH_BUILTIN_GENPARAMS
#define DH_F_DH_BUILTIN_GENPARAMS 106
Definition at line 307 of file dh.h.
DH_F_DH_CMS_DECRYPT
#define DH_F_DH_CMS_DECRYPT 114
Definition at line 308 of file dh.h.
DH_F_DH_CMS_SET_PEERKEY
#define DH_F_DH_CMS_SET_PEERKEY 115
Definition at line 309 of file dh.h.
DH_F_DH_CMS_SET_SHARED_INFO
#define DH_F_DH_CMS_SET_SHARED_INFO 116
Definition at line 310 of file dh.h.
DH_F_DH_METH_DUP
#define DH_F_DH_METH_DUP 117
Definition at line 311 of file dh.h.
DH_F_DH_METH_NEW
#define DH_F_DH_METH_NEW 118
Definition at line 312 of file dh.h.
Referenced by DH_meth_new().
DH_F_DH_METH_SET1_NAME
#define DH_F_DH_METH_SET1_NAME 119
Definition at line 313 of file dh.h.
Referenced by DH_meth_set1_name().
DH_F_DH_NEW_METHOD
#define DH_F_DH_NEW_METHOD 105
Definition at line 314 of file dh.h.
DH_F_DH_PARAM_DECODE
#define DH_F_DH_PARAM_DECODE 107
Definition at line 315 of file dh.h.
DH_F_DH_PRIV_DECODE
#define DH_F_DH_PRIV_DECODE 110
Definition at line 316 of file dh.h.
DH_F_DH_PRIV_ENCODE
#define DH_F_DH_PRIV_ENCODE 111
Definition at line 317 of file dh.h.
DH_F_DH_PUB_DECODE
#define DH_F_DH_PUB_DECODE 108
Definition at line 318 of file dh.h.
DH_F_DH_PUB_ENCODE
#define DH_F_DH_PUB_ENCODE 109
Definition at line 319 of file dh.h.
DH_F_DHPARAMS_PRINT_FP
#define DH_F_DHPARAMS_PRINT_FP 101
Definition at line 306 of file dh.h.
DH_F_DO_DH_PRINT
#define DH_F_DO_DH_PRINT 100
Definition at line 320 of file dh.h.
DH_F_GENERATE_KEY
#define DH_F_GENERATE_KEY 103
Definition at line 321 of file dh.h.
DH_F_PKEY_DH_DERIVE
#define DH_F_PKEY_DH_DERIVE 112
Definition at line 322 of file dh.h.
DH_F_PKEY_DH_KEYGEN
#define DH_F_PKEY_DH_KEYGEN 113
Definition at line 323 of file dh.h.
DH_FLAG_CACHE_MONT_P
#define DH_FLAG_CACHE_MONT_P 0x01
Definition at line 34 of file dh.h.
DH_FLAG_FIPS_METHOD
#define DH_FLAG_FIPS_METHOD 0x0400
Definition at line 50 of file dh.h.
DH_FLAG_NO_EXP_CONSTTIME
#define DH_FLAG_NO_EXP_CONSTTIME 0x00
Definition at line 40 of file dh.h.
DH_FLAG_NON_FIPS_ALLOW
#define DH_FLAG_NON_FIPS_ALLOW 0x0400
Definition at line 58 of file dh.h.
DH_GENERATOR_2
#define DH_GENERATOR_2 2
Definition at line 66 of file dh.h.
DH_GENERATOR_5
#define DH_GENERATOR_5 5
Definition at line 68 of file dh.h.
DH_get_ex_new_index
#define DH_get_ex_new_index (l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_DH, l, p, newf, dupf, freef)
Definition at line 112 of file dh.h.
DH_NOT_SUITABLE_GENERATOR
#define DH_NOT_SUITABLE_GENERATOR 0x08
Definition at line 74 of file dh.h.
DH_R_BAD_GENERATOR
#define DH_R_BAD_GENERATOR 101
Definition at line 326 of file dh.h.
DH_R_BN_DECODE_ERROR
#define DH_R_BN_DECODE_ERROR 109
Definition at line 327 of file dh.h.
DH_R_BN_ERROR
#define DH_R_BN_ERROR 106
Definition at line 328 of file dh.h.
DH_R_DECODE_ERROR
#define DH_R_DECODE_ERROR 104
Definition at line 329 of file dh.h.
DH_R_INVALID_PUBKEY
#define DH_R_INVALID_PUBKEY 102
Definition at line 330 of file dh.h.
DH_R_KDF_PARAMETER_ERROR
#define DH_R_KDF_PARAMETER_ERROR 112
Definition at line 331 of file dh.h.
DH_R_KEYS_NOT_SET
#define DH_R_KEYS_NOT_SET 108
Definition at line 332 of file dh.h.
DH_R_MODULUS_TOO_LARGE
#define DH_R_MODULUS_TOO_LARGE 103
Definition at line 333 of file dh.h.
DH_R_NO_PARAMETERS_SET
#define DH_R_NO_PARAMETERS_SET 107
Definition at line 334 of file dh.h.
DH_R_NO_PRIVATE_VALUE
#define DH_R_NO_PRIVATE_VALUE 100
Definition at line 335 of file dh.h.
DH_R_PARAMETER_ENCODING_ERROR
#define DH_R_PARAMETER_ENCODING_ERROR 105
Definition at line 336 of file dh.h.
DH_R_PEER_KEY_ERROR
#define DH_R_PEER_KEY_ERROR 111
Definition at line 337 of file dh.h.
DH_R_SHARED_INFO_ERROR
#define DH_R_SHARED_INFO_ERROR 113
Definition at line 338 of file dh.h.
DH_UNABLE_TO_CHECK_GENERATOR
#define DH_UNABLE_TO_CHECK_GENERATOR 0x04
Definition at line 73 of file dh.h.
EVP_PKEY_CTRL_DH_KDF_MD
#define EVP_PKEY_CTRL_DH_KDF_MD (EVP_PKEY_ALG_CTRL + 7)
Definition at line 279 of file dh.h.
EVP_PKEY_CTRL_DH_KDF_OID
#define EVP_PKEY_CTRL_DH_KDF_OID (EVP_PKEY_ALG_CTRL + 13)
Definition at line 285 of file dh.h.
EVP_PKEY_CTRL_DH_KDF_OUTLEN
#define EVP_PKEY_CTRL_DH_KDF_OUTLEN (EVP_PKEY_ALG_CTRL + 9)
Definition at line 281 of file dh.h.
EVP_PKEY_CTRL_DH_KDF_TYPE
#define EVP_PKEY_CTRL_DH_KDF_TYPE (EVP_PKEY_ALG_CTRL + 6)
Definition at line 278 of file dh.h.
EVP_PKEY_CTRL_DH_KDF_UKM
#define EVP_PKEY_CTRL_DH_KDF_UKM (EVP_PKEY_ALG_CTRL + 11)
Definition at line 283 of file dh.h.
EVP_PKEY_CTRL_DH_PARAMGEN_GENERATOR
#define EVP_PKEY_CTRL_DH_PARAMGEN_GENERATOR (EVP_PKEY_ALG_CTRL + 2)
Definition at line 274 of file dh.h.
EVP_PKEY_CTRL_DH_PARAMGEN_PRIME_LEN
#define EVP_PKEY_CTRL_DH_PARAMGEN_PRIME_LEN (EVP_PKEY_ALG_CTRL + 1)
Definition at line 273 of file dh.h.
EVP_PKEY_CTRL_DH_PARAMGEN_SUBPRIME_LEN
#define EVP_PKEY_CTRL_DH_PARAMGEN_SUBPRIME_LEN (EVP_PKEY_ALG_CTRL + 4)
Definition at line 276 of file dh.h.
EVP_PKEY_CTRL_DH_PARAMGEN_TYPE
#define EVP_PKEY_CTRL_DH_PARAMGEN_TYPE (EVP_PKEY_ALG_CTRL + 5)
Definition at line 277 of file dh.h.
EVP_PKEY_CTRL_DH_RFC5114
#define EVP_PKEY_CTRL_DH_RFC5114 (EVP_PKEY_ALG_CTRL + 3)
Definition at line 275 of file dh.h.
EVP_PKEY_CTRL_GET_DH_KDF_MD
#define EVP_PKEY_CTRL_GET_DH_KDF_MD (EVP_PKEY_ALG_CTRL + 8)
Definition at line 280 of file dh.h.
EVP_PKEY_CTRL_GET_DH_KDF_OID
#define EVP_PKEY_CTRL_GET_DH_KDF_OID (EVP_PKEY_ALG_CTRL + 14)
Definition at line 286 of file dh.h.
EVP_PKEY_CTRL_GET_DH_KDF_OUTLEN
#define EVP_PKEY_CTRL_GET_DH_KDF_OUTLEN (EVP_PKEY_ALG_CTRL + 10)
Definition at line 282 of file dh.h.
EVP_PKEY_CTRL_GET_DH_KDF_UKM
#define EVP_PKEY_CTRL_GET_DH_KDF_UKM (EVP_PKEY_ALG_CTRL + 12)
Definition at line 284 of file dh.h.
EVP_PKEY_CTX_get0_dh_kdf_oid
#define EVP_PKEY_CTX_get0_dh_kdf_oid (ctx, poid)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DHX, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_GET_DH_KDF_OID, 0, (void *)poid)
Definition at line 238 of file dh.h.
EVP_PKEY_CTX_get0_dh_kdf_ukm
#define EVP_PKEY_CTX_get0_dh_kdf_ukm (ctx, p)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DHX, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_GET_DH_KDF_UKM, 0, (void *)p)
Definition at line 268 of file dh.h.
EVP_PKEY_CTX_get_dh_kdf_md
#define EVP_PKEY_CTX_get_dh_kdf_md (ctx, pmd)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DHX, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_GET_DH_KDF_MD, 0, (void *)pmd)
Definition at line 248 of file dh.h.
EVP_PKEY_CTX_get_dh_kdf_outlen
#define EVP_PKEY_CTX_get_dh_kdf_outlen (ctx, plen)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DHX, \
                                EVP_PKEY_OP_DERIVE, \
                        EVP_PKEY_CTRL_GET_DH_KDF_OUTLEN, 0, (void *)plen)
Definition at line 258 of file dh.h.
EVP_PKEY_CTX_get_dh_kdf_type
#define EVP_PKEY_CTX_get_dh_kdf_type (ctx)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DHX, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_DH_KDF_TYPE, -2, NULL)
Definition at line 228 of file dh.h.
EVP_PKEY_CTX_set0_dh_kdf_oid
#define EVP_PKEY_CTX_set0_dh_kdf_oid (ctx, oid)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DHX, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_DH_KDF_OID, 0, (void *)oid)
Definition at line 233 of file dh.h.
EVP_PKEY_CTX_set0_dh_kdf_ukm
#define EVP_PKEY_CTX_set0_dh_kdf_ukm (ctx, p, plen)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DHX, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_DH_KDF_UKM, plen, (void *)p)
Definition at line 263 of file dh.h.
EVP_PKEY_CTX_set_dh_kdf_md
#define EVP_PKEY_CTX_set_dh_kdf_md (ctx, md)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DHX, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_DH_KDF_MD, 0, (void *)md)
Definition at line 243 of file dh.h.
EVP_PKEY_CTX_set_dh_kdf_outlen
#define EVP_PKEY_CTX_set_dh_kdf_outlen (ctx, len)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DHX, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_DH_KDF_OUTLEN, len, NULL)
Definition at line 253 of file dh.h.
EVP_PKEY_CTX_set_dh_kdf_type
#define EVP_PKEY_CTX_set_dh_kdf_type (ctx, kdf)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DHX, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_DH_KDF_TYPE, kdf, NULL)
Definition at line 223 of file dh.h.
EVP_PKEY_CTX_set_dh_paramgen_generator
#define EVP_PKEY_CTX_set_dh_paramgen_generator (ctx, gen)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DH, EVP_PKEY_OP_PARAMGEN, \
                        EVP_PKEY_CTRL_DH_PARAMGEN_GENERATOR, gen, NULL)
Definition at line 211 of file dh.h.
EVP_PKEY_CTX_set_dh_paramgen_prime_len
#define EVP_PKEY_CTX_set_dh_paramgen_prime_len (ctx, len)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DH, EVP_PKEY_OP_PARAMGEN, \
                        EVP_PKEY_CTRL_DH_PARAMGEN_PRIME_LEN, len, NULL)
Definition at line 199 of file dh.h.
EVP_PKEY_CTX_set_dh_paramgen_subprime_len
#define EVP_PKEY_CTX_set_dh_paramgen_subprime_len (ctx, len)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DH, EVP_PKEY_OP_PARAMGEN, \
                        EVP_PKEY_CTRL_DH_PARAMGEN_SUBPRIME_LEN, len, NULL)
Definition at line 203 of file dh.h.
EVP_PKEY_CTX_set_dh_paramgen_type
#define EVP_PKEY_CTX_set_dh_paramgen_type (ctx, typ)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DH, EVP_PKEY_OP_PARAMGEN, \
                        EVP_PKEY_CTRL_DH_PARAMGEN_TYPE, typ, NULL)
Definition at line 207 of file dh.h.
EVP_PKEY_CTX_set_dh_rfc5114
#define EVP_PKEY_CTX_set_dh_rfc5114 (ctx, gen)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DHX, EVP_PKEY_OP_PARAMGEN, \
                        EVP_PKEY_CTRL_DH_RFC5114, gen, NULL)
Definition at line 215 of file dh.h.
EVP_PKEY_CTX_set_dhx_rfc5114
#define EVP_PKEY_CTX_set_dhx_rfc5114 (ctx, gen)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DHX, EVP_PKEY_OP_PARAMGEN, \
                        EVP_PKEY_CTRL_DH_RFC5114, gen, NULL)
Definition at line 219 of file dh.h.
EVP_PKEY_DH_KDF_NONE
#define EVP_PKEY_DH_KDF_NONE 1
Definition at line 289 of file dh.h.
EVP_PKEY_DH_KDF_X9_42
#define EVP_PKEY_DH_KDF_X9_42 2
Definition at line 291 of file dh.h.
i2d_DHparams_bio
#define i2d_DHparams_bio (bp, x) ASN1_i2d_bio_of_const(DH,i2d_DHparams,bp,x)
Definition at line 95 of file dh.h.
i2d_DHparams_fp
#define i2d_DHparams_fp (fp, x)
Value:
ASN1_i2d_fp(i2d_DHparams,(fp), \
                (unsigned char *)(x))
Definition at line 92 of file dh.h.
OPENSSL_DH_FIPS_MIN_MODULUS_BITS
#define OPENSSL_DH_FIPS_MIN_MODULUS_BITS 1024
Definition at line 32 of file dh.h.
OPENSSL_DH_MAX_MODULUS_BITS
#define OPENSSL_DH_MAX_MODULUS_BITS 10000
Definition at line 29 of file dh.h.
Function Documentation
d2i_DHparams()
DH* d2i_DHparams (DH ** a, const unsigned char ** pp, long length)
d2i_DHxparams()
DH* d2i_DHxparams (DH ** a, const unsigned char ** pp, long length)
DEPRECATEDIN_0_9_8()
DEPRECATEDIN_0_9_8 (DH * DH_generate_parametersint prime_len, int generator, void(*callback)(int, int, void *), void *cb_arg)
DH_bits()
int DH_bits (const DH * dh)
Definition at line 163 of file dh_lib.c.
References BN_num_bits().
DH_check()
int DH_check (const DH * dh, int * codes)
Definition at line 65 of file dh_check.c.
DH_check_params()
int DH_check_params (const DH * dh, int * ret)
Definition at line 22 of file dh_check.c.
DH_check_pub_key()
int DH_check_pub_key (const DH * dh, const BIGNUM * pub_key, int * codes)
Definition at line 147 of file dh_check.c.
DH_clear_flags()
void DH_clear_flags (DH * dh, int flags)
Definition at line 266 of file dh_lib.c.
DH_compute_key()
int DH_compute_key (unsigned char * key, const BIGNUM * pub_key, DH * dh)
Definition at line 28 of file dh_key.c.
DH_compute_key_padded()
int DH_compute_key_padded (unsigned char * key, const BIGNUM * pub_key, DH * dh)
Definition at line 33 of file dh_key.c.
References BN_num_bytes.
DH_free()
void DH_free (DH * dh)
Definition at line 107 of file dh_lib.c.
References BN_clear_free(), CRYPTO_DOWN_REF, CRYPTO_EX_INDEX_DH, CRYPTO_free_ex_data(), CRYPTO_THREAD_lock_free(), ENGINE_finish(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by IMPLEMENT_ASN1_ENCODE_FUNCTIONS_const_fname(), and ssl_get_auto_dh().
DH_generate_key()
int DH_generate_key (DH * dh)
Definition at line 23 of file dh_key.c.
DH_get0_engine()
ENGINE* DH_get0_engine (DH * d)
Definition at line 281 of file dh_lib.c.
DH_get0_key()
void DH_get0_key (const DH * dh, const BIGNUM ** pub_key, const BIGNUM ** priv_key)
Definition at line 237 of file dh_lib.c.
References NULL.
DH_get0_pqg()
void DH_get0_pqg (const DH * dh, const BIGNUM ** p, const BIGNUM ** q, const BIGNUM ** g)
Definition at line 186 of file dh_lib.c.
References NULL.
DH_get_1024_160()
DH* DH_get_1024_160 (void)
Referenced by ssl_get_auto_dh().
DH_get_2048_224()
DH* DH_get_2048_224 (void)
Referenced by ssl_get_auto_dh().
DH_get_2048_256()
DH* DH_get_2048_256 (void)
DH_get_default_method()
const DH_METHOD* DH_get_default_method (void)
Definition at line 23 of file dh_lib.c.
DH_get_ex_data()
void* DH_get_ex_data (DH * d, int idx)
Definition at line 158 of file dh_lib.c.
DH_get_length()
long DH_get_length (const DH * dh)
Definition at line 226 of file dh_lib.c.
DH_KDF_X9_42()
int DH_KDF_X9_42 (unsigned char * out, size_t outlen, const unsigned char * Z, size_t Zlen, ASN1_OBJECT * key_oid, const unsigned char * ukm, size_t ukmlen, const EVP_MD * md)
Definition at line 98 of file dh_kdf.c.
DH_meth_dup()
DH_METHOD* DH_meth_dup (const DH_METHOD * dhm)
Definition at line 40 of file dh_meth.c.
DH_meth_free()
void DH_meth_free (DH_METHOD * dhm)
Definition at line 32 of file dh_meth.c.
References NULL, and OPENSSL_free.
DH_meth_get0_app_data()
void* DH_meth_get0_app_data (const DH_METHOD * dhm)
Definition at line 89 of file dh_meth.c.
DH_meth_get0_name()
const char* DH_meth_get0_name (const DH_METHOD * dhm)
Definition at line 58 of file dh_meth.c.
DH_meth_get_flags()
int DH_meth_get_flags (DH_METHOD * dhm)
Definition at line 78 of file dh_meth.c.
DH_meth_new()
DH_METHOD* DH_meth_new (const char * name, int flags)
Definition at line 14 of file dh_meth.c.
References DH_F_DH_METH_NEW, DHerr, ERR_R_MALLOC_FAILURE, flags, NULL, OPENSSL_free, OPENSSL_strdup, and OPENSSL_zalloc.
DH_meth_set0_app_data()
int DH_meth_set0_app_data (DH_METHOD * dhm, void * app_data)
Definition at line 94 of file dh_meth.c.
DH_meth_set1_name()
int DH_meth_set1_name (DH_METHOD * dhm, const char * name)
Definition at line 63 of file dh_meth.c.
References DH_F_DH_METH_SET1_NAME, DHerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, and OPENSSL_strdup.
DH_meth_set_bn_mod_exp()
int DH_meth_set_bn_mod_exp (DH_METHOD * dhm, int(*)(const DH *, BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *, BN_MONT_CTX *) bn_mod_exp)
Definition at line 132 of file dh_meth.c.
DH_meth_set_compute_key()
int DH_meth_set_compute_key (DH_METHOD * dhm, int(*)(unsigned char *key, const BIGNUM *pub_key, DH *dh) compute_key)
Definition at line 117 of file dh_meth.c.
DH_meth_set_finish()
int DH_meth_set_finish (DH_METHOD * dhm, int(*)(DH *) finish)
Definition at line 156 of file dh_meth.c.
DH_meth_set_flags()
int DH_meth_set_flags (DH_METHOD * dhm, int flags)
Definition at line 83 of file dh_meth.c.
References flags.
DH_meth_set_generate_key()
int DH_meth_set_generate_key (DH_METHOD * dhm, int(*)(DH *) generate_key)
Definition at line 105 of file dh_meth.c.
DH_meth_set_generate_params()
int DH_meth_set_generate_params (DH_METHOD * dhm, int(*)(DH *, int, int, BN_GENCB *) generate_params)
Definition at line 168 of file dh_meth.c.
DH_meth_set_init()
int DH_meth_set_init (DH_METHOD * dhm, int(*)(DH *) init)
Definition at line 145 of file dh_meth.c.
DH_new()
DH* DH_new (void)
Definition at line 50 of file dh_lib.c.
References DH_new_method(), and NULL.
Referenced by IMPLEMENT_ASN1_ENCODE_FUNCTIONS_const_fname(), and ssl_get_auto_dh().
DH_new_method()
DH* DH_new_method (ENGINE * engine)
Definition at line 55 of file dh_lib.c.
Referenced by DH_new().
DH_OpenSSL()
const DH_METHOD* DH_OpenSSL (void)
Definition at line 59 of file dh_key.c.
DH_security_bits()
int DH_security_bits (const DH * dh)
Definition at line 173 of file dh_lib.c.
References BN_num_bits(), BN_security_bits(), and N.
DH_set0_key()
int DH_set0_key (DH * dh, BIGNUM * pub_key, BIGNUM * priv_key)
Definition at line 245 of file dh_lib.c.
References BN_free(), and NULL.
DH_set0_pqg()
int DH_set0_pqg (DH * dh, BIGNUM * p, BIGNUM * q, BIGNUM * g)
Definition at line 197 of file dh_lib.c.
References BN_free(), BN_num_bits(), NULL, and q.
Referenced by ssl_get_auto_dh().
DH_set_default_method()
void DH_set_default_method (const DH_METHOD * meth)
Definition at line 18 of file dh_lib.c.
DH_set_ex_data()
int DH_set_ex_data (DH * d, int idx, void * arg)
Definition at line 153 of file dh_lib.c.
DH_set_flags()
void DH_set_flags (DH * dh, int flags)
Definition at line 276 of file dh_lib.c.
References flags.
DH_set_length()
int DH_set_length (DH * dh, long length)
Definition at line 231 of file dh_lib.c.
DH_set_method()
int DH_set_method (DH * dh, const DH_METHOD * meth)
Definition at line 30 of file dh_lib.c.
References ENGINE_finish(), and NULL.
DH_size()
int DH_size (const DH * dh)
Definition at line 168 of file dh_lib.c.
References BN_num_bytes.
DH_test_flags()
int DH_test_flags (const DH * dh, int flags)
Definition at line 271 of file dh_lib.c.
References flags.
DH_up_ref()
int DH_up_ref (DH * dh)
Definition at line 141 of file dh_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
DHparams_dup()
DH* DHparams_dup (DH *)
Definition at line 415 of file dh_ameth.c.
DHparams_print()
int DHparams_print (BIO * bp, const DH * x)
Definition at line 474 of file dh_ameth.c.
DHparams_print_fp()
int DHparams_print_fp (FILE * fp, const DH * x)
Definition at line 16 of file dh_prn.c.
ERR_load_DH_strings()
int ERR_load_DH_strings (void)
Definition at line 63 of file dh_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
i2d_DHparams()
int i2d_DHparams (const DH * a, unsigned char ** pp)
i2d_DHxparams()
int i2d_DHxparams (const DH * a, unsigned char ** pp)
Definition at line 118 of file dh_asn1.c.
References ASN1_STRING_FLAG_BITS_LEFT, int_dhx942_dh::g, i2d_int_dhx(), int_dhx942_dh::j, NULL, int_dhx942_dh::p, int_dhx942_dh::q, and int_dhx942_dh::vparams.
Variable Documentation
cb
int int BN_GENCB* cb
Definition at line 124 of file dh.h.
DH_meth_get_bn_mod_exp
int(*)(const DH *, BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *, BN_MONT_CTX *) DH_meth_get_bn_mod_exp(const DH_METHOD *dhm)
Definition at line 183 of file dh.h.
DH_meth_get_compute_key
int(*)(unsigned char *key, const BIGNUM *pub_key, DH *dh) DH_meth_get_compute_key(const DH_METHOD *dhm)
Definition at line 179 of file dh.h.
DH_meth_get_finish
int(*)(DH *) DH_meth_get_finish(const DH_METHOD *dhm)
Definition at line 191 of file dh.h.
DH_meth_get_generate_key
int(*)(DH *) DH_meth_get_generate_key(const DH_METHOD *dhm)
Definition at line 177 of file dh.h.
DH_meth_get_generate_params
int(*)(DH *, int, int, BN_GENCB *) DH_meth_get_generate_params(const DH_METHOD *dhm)
Definition at line 193 of file dh.h.
DH_meth_get_init
int(*)(DH *) DH_meth_get_init(const DH_METHOD *dhm)
Definition at line 189 of file dh.h.
generator
int int generator
Definition at line 124 of file dh.h.
Referenced by ec_wNAF_mul(), and ec_wNAF_precompute_mult().
prime_len
int prime_len
Definition at line 124 of file dh.h.