crypto/dh/dh_lib.c File Reference
dh_lib.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/bn.h>
#include "dh_locl.h"
#include <openssl/engine.h>
Functions
void DH_set_default_method (const DH_METHOD *meth)
const DH_METHOD * DH_get_default_method (void)
int DH_set_method (DH *dh, const DH_METHOD *meth)
DH * DH_new (void)
DH * DH_new_method (ENGINE *engine)
void DH_free (DH *r)
int DH_up_ref (DH *r)
int DH_set_ex_data (DH *d, int idx, void *arg)
void * DH_get_ex_data (DH *d, int idx)
int DH_bits (const DH *dh)
int DH_size (const DH *dh)
int DH_security_bits (const DH *dh)
void DH_get0_pqg (const DH *dh, const BIGNUM **p, const BIGNUM **q, const BIGNUM **g)
int DH_set0_pqg (DH *dh, BIGNUM *p, BIGNUM *q, BIGNUM *g)
long DH_get_length (const DH *dh)
int DH_set_length (DH *dh, long length)
void DH_get0_key (const DH *dh, const BIGNUM **pub_key, const BIGNUM **priv_key)
int DH_set0_key (DH *dh, BIGNUM *pub_key, BIGNUM *priv_key)
void DH_clear_flags (DH *dh, int flags)
int DH_test_flags (const DH *dh, int flags)
void DH_set_flags (DH *dh, int flags)
ENGINE * DH_get0_engine (DH *dh)
Function Documentation
DH_bits()
int DH_bits (const DH * dh)
Definition at line 163 of file dh_lib.c.
References BN_num_bits().
DH_clear_flags()
void DH_clear_flags (DH * dh, int flags)
Definition at line 266 of file dh_lib.c.
DH_free()
void DH_free (DH * r)
Definition at line 107 of file dh_lib.c.
References BN_clear_free(), CRYPTO_DOWN_REF, CRYPTO_EX_INDEX_DH, CRYPTO_free_ex_data(), CRYPTO_THREAD_lock_free(), ENGINE_finish(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by IMPLEMENT_ASN1_ENCODE_FUNCTIONS_const_fname(), and ssl_get_auto_dh().
DH_get0_engine()
ENGINE* DH_get0_engine (DH * dh)
Definition at line 281 of file dh_lib.c.
DH_get0_key()
void DH_get0_key (const DH * dh, const BIGNUM ** pub_key, const BIGNUM ** priv_key)
Definition at line 237 of file dh_lib.c.
References NULL.
DH_get0_pqg()
void DH_get0_pqg (const DH * dh, const BIGNUM ** p, const BIGNUM ** q, const BIGNUM ** g)
Definition at line 186 of file dh_lib.c.
References NULL.
DH_get_default_method()
const DH_METHOD* DH_get_default_method (void)
Definition at line 23 of file dh_lib.c.
DH_get_ex_data()
void* DH_get_ex_data (DH * d, int idx)
Definition at line 158 of file dh_lib.c.
DH_get_length()
long DH_get_length (const DH * dh)
Definition at line 226 of file dh_lib.c.
DH_new()
DH* DH_new (void)
Definition at line 50 of file dh_lib.c.
References DH_new_method(), and NULL.
Referenced by IMPLEMENT_ASN1_ENCODE_FUNCTIONS_const_fname(), and ssl_get_auto_dh().
DH_new_method()
DH* DH_new_method (ENGINE * engine)
Definition at line 55 of file dh_lib.c.
Referenced by DH_new().
DH_security_bits()
int DH_security_bits (const DH * dh)
Definition at line 173 of file dh_lib.c.
References BN_num_bits(), BN_security_bits(), and N.
DH_set0_key()
int DH_set0_key (DH * dh, BIGNUM * pub_key, BIGNUM * priv_key)
Definition at line 245 of file dh_lib.c.
References BN_free(), and NULL.
DH_set0_pqg()
int DH_set0_pqg (DH * dh, BIGNUM * p, BIGNUM * q, BIGNUM * g)
Definition at line 197 of file dh_lib.c.
References BN_free(), BN_num_bits(), NULL, and q.
Referenced by ssl_get_auto_dh().
DH_set_default_method()
void DH_set_default_method (const DH_METHOD * meth)
Definition at line 18 of file dh_lib.c.
DH_set_ex_data()
int DH_set_ex_data (DH * d, int idx, void * arg)
Definition at line 153 of file dh_lib.c.
DH_set_flags()
void DH_set_flags (DH * dh, int flags)
Definition at line 276 of file dh_lib.c.
References flags.
DH_set_length()
int DH_set_length (DH * dh, long length)
Definition at line 231 of file dh_lib.c.
DH_set_method()
int DH_set_method (DH * dh, const DH_METHOD * meth)
Definition at line 30 of file dh_lib.c.
References ENGINE_finish(), and NULL.
DH_size()
int DH_size (const DH * dh)
Definition at line 168 of file dh_lib.c.
References BN_num_bytes.
DH_test_flags()
int DH_test_flags (const DH * dh, int flags)
Definition at line 271 of file dh_lib.c.
References flags.
DH_up_ref()
int DH_up_ref (DH * r)
Definition at line 141 of file dh_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.