crypto/dh/dh_asn1.c File Reference
dh_asn1.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/bn.h>
#include "dh_locl.h"
#include <openssl/objects.h>
#include <openssl/asn1t.h>
Data Structures
struct int_dhx942_dh
Functions
ASN1_SEQUENCE_cb (DHparams, dh_cb)
ASN1_SEQUENCE (DHvparams)
int i2d_int_dhx (const int_dhx942_dh *a, unsigned char **pp)
IMPLEMENT_ASN1_ENCODE_FUNCTIONS_const_fname (int_dhx942_dh, DHxparams, int_dhx)
int i2d_DHxparams (const DH *dh, unsigned char **pp)
Function Documentation
ASN1_SEQUENCE()
ASN1_SEQUENCE (DHvparams)
ASN1_SEQUENCE_cb()
ASN1_SEQUENCE_cb (DHparams , dh_cb)
i2d_DHxparams()
int i2d_DHxparams (const DH * dh, unsigned char ** pp)
Definition at line 118 of file dh_asn1.c.
References ASN1_STRING_FLAG_BITS_LEFT, int_dhx942_dh::g, i2d_int_dhx(), int_dhx942_dh::j, NULL, int_dhx942_dh::p, int_dhx942_dh::q, and int_dhx942_dh::vparams.
i2d_int_dhx()
int i2d_int_dhx (const int_dhx942_dh * a, unsigned char ** pp)
Referenced by i2d_DHxparams().
IMPLEMENT_ASN1_ENCODE_FUNCTIONS_const_fname()
IMPLEMENT_ASN1_ENCODE_FUNCTIONS_const_fname (int_dhx942_dh , DHxparams , int_dhx)
Definition at line 77 of file dh_asn1.c.
References DH_free(), DH_new(), int_dhx942_dh::g, int_dhx942_dh::j, NULL, OPENSSL_free, int_dhx942_dh::p, int_dhx942_dh::q, and int_dhx942_dh::vparams.