crypto/evp/digest.c File Reference
digest.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/engine.h>
#include "internal/evp_int.h"
#include "evp_locl.h"
Functions
int EVP_MD_CTX_reset (EVP_MD_CTX *ctx)
EVP_MD_CTX * EVP_MD_CTX_new (void)
void EVP_MD_CTX_free (EVP_MD_CTX *ctx)
int EVP_DigestInit (EVP_MD_CTX *ctx, const EVP_MD *type)
int EVP_DigestInit_ex (EVP_MD_CTX *ctx, const EVP_MD *type, ENGINE *impl)
int EVP_DigestUpdate (EVP_MD_CTX *ctx, const void *data, size_t count)
int EVP_DigestFinal (EVP_MD_CTX *ctx, unsigned char *md, unsigned int *size)
int EVP_DigestFinal_ex (EVP_MD_CTX *ctx, unsigned char *md, unsigned int *size)
int EVP_MD_CTX_copy (EVP_MD_CTX *out, const EVP_MD_CTX *in)
int EVP_MD_CTX_copy_ex (EVP_MD_CTX *out, const EVP_MD_CTX *in)
int EVP_Digest (const void *data, size_t count, unsigned char *md, unsigned int *size, const EVP_MD *type, ENGINE *impl)
int EVP_MD_CTX_ctrl (EVP_MD_CTX *ctx, int cmd, int p1, void *p2)
Function Documentation
EVP_Digest()
int EVP_Digest (const void * data, size_t count, unsigned char * md, unsigned int * size, const EVP_MD * type, ENGINE * impl)
Definition at line 242 of file digest.c.
Referenced by X509_ocspid_print().
EVP_DigestFinal()
int EVP_DigestFinal (EVP_MD_CTX * ctx, unsigned char * md, unsigned int * size)
Definition at line 152 of file digest.c.
EVP_DigestFinal_ex()
int EVP_DigestFinal_ex (EVP_MD_CTX * ctx, unsigned char * md, unsigned int * size)
Definition at line 161 of file digest.c.
Referenced by CMS_SignerInfo_verify_content(), EVP_SignFinal(), EVP_VerifyFinal(), PKCS7_signatureVerify(), and SRP_Calc_x().
EVP_DigestInit()
int EVP_DigestInit (EVP_MD_CTX * ctx, const EVP_MD * type)
Definition at line 55 of file digest.c.
References EVP_DigestInit_ex(), EVP_MD_CTX_reset(), and NULL.
EVP_DigestInit_ex()
int EVP_DigestInit_ex (EVP_MD_CTX * ctx, const EVP_MD * type, ENGINE * impl)
Definition at line 61 of file digest.c.
References ENGINE_finish(), ENGINE_get_digest(), ENGINE_get_digest_engine(), ENGINE_init(), ERR_R_MALLOC_FAILURE, EVP_F_EVP_DIGESTINIT_EX, EVP_MD_CTX_clear_flags(), EVP_MD_CTX_FLAG_CLEANED, EVP_MD_CTX_FLAG_NO_INIT, EVP_PKEY_CTRL_DIGESTINIT, EVP_PKEY_CTX_ctrl(), EVP_PKEY_OP_TYPE_SIG, EVP_R_INITIALIZATION_ERROR, EVP_R_NO_DIGEST_SET, EVPerr, impl, NULL, OPENSSL_clear_free, OPENSSL_zalloc, and type.
Referenced by EVP_DigestInit(), PEM_SignInit(), and SRP_Calc_x().
EVP_DigestUpdate()
int EVP_DigestUpdate (EVP_MD_CTX * ctx, const void * data, size_t count)
Definition at line 146 of file digest.c.
Referenced by HMAC_Update(), PEM_SignUpdate(), and SRP_Calc_x().
EVP_MD_CTX_copy()
int EVP_MD_CTX_copy (EVP_MD_CTX * out, const EVP_MD_CTX * in)
Definition at line 177 of file digest.c.
EVP_MD_CTX_copy_ex()
int EVP_MD_CTX_copy_ex (EVP_MD_CTX * out, const EVP_MD_CTX * in)
Definition at line 183 of file digest.c.
Referenced by cms_DigestAlgorithm_find_ctx(), EVP_SignFinal(), EVP_VerifyFinal(), HMAC_CTX_copy(), and PKCS7_signatureVerify().
EVP_MD_CTX_ctrl()
int EVP_MD_CTX_ctrl (EVP_MD_CTX * ctx, int cmd, int p1, void * p2)
Definition at line 260 of file digest.c.
EVP_MD_CTX_free()
void EVP_MD_CTX_free (EVP_MD_CTX * ctx)
Definition at line 49 of file digest.c.
References EVP_MD_CTX_reset(), and OPENSSL_free.
Referenced by ASN1_item_sign(), ASN1_sign(), dtls1_hm_fragment_free(), EVP_SignFinal(), EVP_VerifyFinal(), PKCS7_signatureVerify(), SRP_Calc_x(), ssl3_free_digest_list(), and ssl_clear_hash_ctx().
EVP_MD_CTX_new()
EVP_MD_CTX* EVP_MD_CTX_new (void)
Definition at line 44 of file digest.c.
References OPENSSL_zalloc.
Referenced by ASN1_item_sign(), ASN1_sign(), ASN1_verify(), CMS_SignerInfo_verify_content(), do_X509_CRL_sign(), do_X509_REQ_sign(), do_X509_sign(), EVP_SignFinal(), EVP_VerifyFinal(), PKCS7_dataFinal(), PKCS7_signatureVerify(), SRP_Calc_x(), tls_construct_server_key_exchange(), and X509_NAME_hash_old().
EVP_MD_CTX_reset()
int EVP_MD_CTX_reset (EVP_MD_CTX * ctx)
Definition at line 19 of file digest.c.
References ENGINE_finish(), EVP_MD_CTX_FLAG_CLEANED, EVP_MD_CTX_FLAG_REUSE, EVP_MD_CTX_test_flags(), EVP_PKEY_CTX_free(), NULL, OPENSSL_cleanse(), and OPENSSL_clear_free.
Referenced by EVP_DigestInit(), and EVP_MD_CTX_free().