include/openssl/dsa.h File Reference
dsa.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/e_os2.h>
#include <openssl/bio.h>
#include <openssl/crypto.h>
#include <openssl/ossl_typ.h>
#include <openssl/bn.h>
#include <openssl/dh.h>
Macros
#define OPENSSL_DSA_MAX_MODULUS_BITS 10000
#define OPENSSL_DSA_FIPS_MIN_MODULUS_BITS 1024
#define DSA_FLAG_CACHE_MONT_P 0x01
#define DSA_FLAG_NO_EXP_CONSTTIME 0x00
#define DSA_FLAG_FIPS_METHOD 0x0400
#define DSA_FLAG_NON_FIPS_ALLOW 0x0400
#define DSA_FLAG_FIPS_CHECKED 0x0800
#define d2i_DSAparams_fp(fp, x)
#define i2d_DSAparams_fp(fp, x)
#define d2i_DSAparams_bio(bp, x) ASN1_d2i_bio_of(DSA,DSA_new,d2i_DSAparams,bp,x)
#define i2d_DSAparams_bio(bp, x) ASN1_i2d_bio_of_const(DSA,i2d_DSAparams,bp,x)
#define DSA_get_ex_new_index(l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_DSA, l, p, newf, dupf, freef)
#define DSS_prime_checks 50
#define DSA_is_prime(n, callback, cb_arg) BN_is_prime(n, DSS_prime_checks, callback, NULL, cb_arg)
#define EVP_PKEY_CTX_set_dsa_paramgen_bits(ctx, nbits)
#define EVP_PKEY_CTRL_DSA_PARAMGEN_BITS (EVP_PKEY_ALG_CTRL + 1)
#define EVP_PKEY_CTRL_DSA_PARAMGEN_Q_BITS (EVP_PKEY_ALG_CTRL + 2)
#define EVP_PKEY_CTRL_DSA_PARAMGEN_MD (EVP_PKEY_ALG_CTRL + 3)
#define DSA_F_DSAPARAMS_PRINT 100
#define DSA_F_DSAPARAMS_PRINT_FP 101
#define DSA_F_DSA_BUILTIN_PARAMGEN 125
#define DSA_F_DSA_BUILTIN_PARAMGEN2 126
#define DSA_F_DSA_DO_SIGN 112
#define DSA_F_DSA_DO_VERIFY 113
#define DSA_F_DSA_METH_DUP 127
#define DSA_F_DSA_METH_NEW 128
#define DSA_F_DSA_METH_SET1_NAME 129
#define DSA_F_DSA_NEW_METHOD 103
#define DSA_F_DSA_PARAM_DECODE 119
#define DSA_F_DSA_PRINT_FP 105
#define DSA_F_DSA_PRIV_DECODE 115
#define DSA_F_DSA_PRIV_ENCODE 116
#define DSA_F_DSA_PUB_DECODE 117
#define DSA_F_DSA_PUB_ENCODE 118
#define DSA_F_DSA_SIGN 106
#define DSA_F_DSA_SIGN_SETUP 107
#define DSA_F_DSA_SIG_NEW 102
#define DSA_F_OLD_DSA_PRIV_DECODE 122
#define DSA_F_PKEY_DSA_CTRL 120
#define DSA_F_PKEY_DSA_KEYGEN 121
#define DSA_R_BAD_Q_VALUE 102
#define DSA_R_BN_DECODE_ERROR 108
#define DSA_R_BN_ERROR 109
#define DSA_R_DECODE_ERROR 104
#define DSA_R_INVALID_DIGEST_TYPE 106
#define DSA_R_INVALID_PARAMETERS 112
#define DSA_R_MISSING_PARAMETERS 101
#define DSA_R_MODULUS_TOO_LARGE 103
#define DSA_R_NO_PARAMETERS_SET 107
#define DSA_R_PARAMETER_ENCODING_ERROR 105
#define DSA_R_Q_NOT_PRIME 113
#define DSA_R_SEED_LEN_SMALL 110
Functions
DSA * DSAparams_dup (DSA *x)
DSA_SIG * DSA_SIG_new (void)
void DSA_SIG_free (DSA_SIG *a)
int i2d_DSA_SIG (const DSA_SIG *a, unsigned char **pp)
DSA_SIG * d2i_DSA_SIG (DSA_SIG **v, const unsigned char **pp, long length)
void DSA_SIG_get0 (const DSA_SIG *sig, const BIGNUM **pr, const BIGNUM **ps)
int DSA_SIG_set0 (DSA_SIG *sig, BIGNUM *r, BIGNUM *s)
DSA_SIG * DSA_do_sign (const unsigned char *dgst, int dlen, DSA *dsa)
int DSA_do_verify (const unsigned char *dgst, int dgst_len, DSA_SIG *sig, DSA *dsa)
const DSA_METHOD * DSA_OpenSSL (void)
void DSA_set_default_method (const DSA_METHOD *)
const DSA_METHOD * DSA_get_default_method (void)
int DSA_set_method (DSA *dsa, const DSA_METHOD *)
const DSA_METHOD * DSA_get_method (DSA *d)
DSA * DSA_new (void)
DSA * DSA_new_method (ENGINE *engine)
void DSA_free (DSA *r)
int DSA_up_ref (DSA *r)
int DSA_size (const DSA *)
int DSA_bits (const DSA *d)
int DSA_security_bits (const DSA *d)
int DSA_sign_setup (DSA *dsa, BN_CTX *ctx_in, BIGNUM **kinvp, BIGNUM **rp)
int DSA_sign (int type, const unsigned char *dgst, int dlen, unsigned char *sig, unsigned int *siglen, DSA *dsa)
int DSA_verify (int type, const unsigned char *dgst, int dgst_len, const unsigned char *sigbuf, int siglen, DSA *dsa)
int DSA_set_ex_data (DSA *d, int idx, void *arg)
void * DSA_get_ex_data (DSA *d, int idx)
DSA * d2i_DSAPublicKey (DSA **a, const unsigned char **pp, long length)
DSA * d2i_DSAPrivateKey (DSA **a, const unsigned char **pp, long length)
DSA * d2i_DSAparams (DSA **a, const unsigned char **pp, long length)
DEPRECATEDIN_0_9_8 (DSA *DSA_generate_parameters(int bits, unsigned char *seed, int seed_len, int *counter_ret, unsigned long *h_ret, void(*callback)(int, int, void *), void *cb_arg)) int DSA_generate_parameters_ex(DSA *dsa
int DSA_generate_key (DSA *a)
int i2d_DSAPublicKey (const DSA *a, unsigned char **pp)
int i2d_DSAPrivateKey (const DSA *a, unsigned char **pp)
int i2d_DSAparams (const DSA *a, unsigned char **pp)
int DSAparams_print (BIO *bp, const DSA *x)
int DSA_print (BIO *bp, const DSA *x, int off)
int DSAparams_print_fp (FILE *fp, const DSA *x)
int DSA_print_fp (FILE *bp, const DSA *x, int off)
DH * DSA_dup_DH (const DSA *r)
void DSA_get0_pqg (const DSA *d, const BIGNUM **p, const BIGNUM **q, const BIGNUM **g)
int DSA_set0_pqg (DSA *d, BIGNUM *p, BIGNUM *q, BIGNUM *g)
void DSA_get0_key (const DSA *d, const BIGNUM **pub_key, const BIGNUM **priv_key)
int DSA_set0_key (DSA *d, BIGNUM *pub_key, BIGNUM *priv_key)
void DSA_clear_flags (DSA *d, int flags)
int DSA_test_flags (const DSA *d, int flags)
void DSA_set_flags (DSA *d, int flags)
ENGINE * DSA_get0_engine (DSA *d)
DSA_METHOD * DSA_meth_new (const char *name, int flags)
void DSA_meth_free (DSA_METHOD *dsam)
DSA_METHOD * DSA_meth_dup (const DSA_METHOD *dsam)
const char * DSA_meth_get0_name (const DSA_METHOD *dsam)
int DSA_meth_set1_name (DSA_METHOD *dsam, const char *name)
int DSA_meth_get_flags (DSA_METHOD *dsam)
int DSA_meth_set_flags (DSA_METHOD *dsam, int flags)
void * DSA_meth_get0_app_data (const DSA_METHOD *dsam)
int DSA_meth_set0_app_data (DSA_METHOD *dsam, void *app_data)
int DSA_meth_set_sign (DSA_METHOD *dsam, DSA_SIG *(*sign)(const unsigned char *, int, DSA *))
int DSA_meth_set_sign_setup (DSA_METHOD *dsam, int(*sign_setup)(DSA *, BN_CTX *, BIGNUM **, BIGNUM **))
int DSA_meth_set_verify (DSA_METHOD *dsam, int(*verify)(const unsigned char *, int, DSA_SIG *, DSA *))
int DSA_meth_set_mod_exp (DSA_METHOD *dsam, int(*mod_exp)(DSA *, BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *, BN_MONT_CTX *))
int DSA_meth_set_bn_mod_exp (DSA_METHOD *dsam, int(*bn_mod_exp)(DSA *, BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *, BN_MONT_CTX *))
int DSA_meth_set_init (DSA_METHOD *dsam, int(*init)(DSA *))
int DSA_meth_set_finish (DSA_METHOD *dsam, int(*finish)(DSA *))
int DSA_meth_set_paramgen (DSA_METHOD *dsam, int(*paramgen)(DSA *, int, const unsigned char *, int, int *, unsigned long *, BN_GENCB *))
int DSA_meth_set_keygen (DSA_METHOD *dsam, int(*keygen)(DSA *))
int ERR_load_DSA_strings (void)
Variables
int bits
int const unsigned char * seed
int const unsigned char int seed_len
int const unsigned char int int * counter_ret
int const unsigned char int int unsigned long * h_ret
int const unsigned char int int unsigned long BN_GENCB * cb
DSA_SIG *(*)(const unsigned char *, int, DSA *) DSA_meth_get_sign (const DSA_METHOD *dsam)
int(*)(DSA *, BN_CTX *, BIGNUM **, BIGNUM **) DSA_meth_get_sign_setup (const DSA_METHOD *dsam)
int(*)(const unsigned char *, int, DSA_SIG *, DSA *) DSA_meth_get_verify (const DSA_METHOD *dsam)
int(*)(DSA *, BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *, BN_MONT_CTX *) DSA_meth_get_mod_exp (const DSA_METHOD *dsam)
int(*)(DSA *, BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *, BN_MONT_CTX *) DSA_meth_get_bn_mod_exp (const DSA_METHOD *dsam)
int(*)(DSA *) DSA_meth_get_init (const DSA_METHOD *dsam)
int(*)(DSA *) DSA_meth_get_finish (const DSA_METHOD *dsam)
int(*)(DSA *, int, const unsigned char *, int, int *, unsigned long *, BN_GENCB *) DSA_meth_get_paramgen (const DSA_METHOD *dsam)
int(*)(DSA *) DSA_meth_get_keygen (const DSA_METHOD *dsam)
Macro Definition Documentation
d2i_DSAparams_bio
#define d2i_DSAparams_bio (bp, x) ASN1_d2i_bio_of(DSA,DSA_new,d2i_DSAparams,bp,x)
Definition at line 76 of file dsa.h.
d2i_DSAparams_fp
#define d2i_DSAparams_fp (fp, x)
Value:
(DSA *)ASN1_d2i_fp((char *(*)())DSA_new, \
                (char *(*)())d2i_DSAparams,(fp),(unsigned char **)(x))
Definition at line 72 of file dsa.h.
DSA_F_DSA_BUILTIN_PARAMGEN
#define DSA_F_DSA_BUILTIN_PARAMGEN 125
Definition at line 244 of file dsa.h.
DSA_F_DSA_BUILTIN_PARAMGEN2
#define DSA_F_DSA_BUILTIN_PARAMGEN2 126
Definition at line 245 of file dsa.h.
DSA_F_DSA_DO_SIGN
#define DSA_F_DSA_DO_SIGN 112
Definition at line 246 of file dsa.h.
DSA_F_DSA_DO_VERIFY
#define DSA_F_DSA_DO_VERIFY 113
Definition at line 247 of file dsa.h.
DSA_F_DSA_METH_DUP
#define DSA_F_DSA_METH_DUP 127
Definition at line 248 of file dsa.h.
DSA_F_DSA_METH_NEW
#define DSA_F_DSA_METH_NEW 128
Definition at line 249 of file dsa.h.
Referenced by DSA_meth_new().
DSA_F_DSA_METH_SET1_NAME
#define DSA_F_DSA_METH_SET1_NAME 129
Definition at line 250 of file dsa.h.
Referenced by DSA_meth_set1_name().
DSA_F_DSA_NEW_METHOD
#define DSA_F_DSA_NEW_METHOD 103
Definition at line 251 of file dsa.h.
DSA_F_DSA_PARAM_DECODE
#define DSA_F_DSA_PARAM_DECODE 119
Definition at line 252 of file dsa.h.
DSA_F_DSA_PRINT_FP
#define DSA_F_DSA_PRINT_FP 105
Definition at line 253 of file dsa.h.
DSA_F_DSA_PRIV_DECODE
#define DSA_F_DSA_PRIV_DECODE 115
Definition at line 254 of file dsa.h.
DSA_F_DSA_PRIV_ENCODE
#define DSA_F_DSA_PRIV_ENCODE 116
Definition at line 255 of file dsa.h.
DSA_F_DSA_PUB_DECODE
#define DSA_F_DSA_PUB_DECODE 117
Definition at line 256 of file dsa.h.
DSA_F_DSA_PUB_ENCODE
#define DSA_F_DSA_PUB_ENCODE 118
Definition at line 257 of file dsa.h.
DSA_F_DSA_SIG_NEW
#define DSA_F_DSA_SIG_NEW 102
Definition at line 260 of file dsa.h.
DSA_F_DSA_SIGN
#define DSA_F_DSA_SIGN 106
Definition at line 258 of file dsa.h.
DSA_F_DSA_SIGN_SETUP
#define DSA_F_DSA_SIGN_SETUP 107
Definition at line 259 of file dsa.h.
DSA_F_DSAPARAMS_PRINT
#define DSA_F_DSAPARAMS_PRINT 100
Definition at line 242 of file dsa.h.
DSA_F_DSAPARAMS_PRINT_FP
#define DSA_F_DSAPARAMS_PRINT_FP 101
Definition at line 243 of file dsa.h.
DSA_F_OLD_DSA_PRIV_DECODE
#define DSA_F_OLD_DSA_PRIV_DECODE 122
Definition at line 261 of file dsa.h.
DSA_F_PKEY_DSA_CTRL
#define DSA_F_PKEY_DSA_CTRL 120
Definition at line 262 of file dsa.h.
DSA_F_PKEY_DSA_KEYGEN
#define DSA_F_PKEY_DSA_KEYGEN 121
Definition at line 263 of file dsa.h.
DSA_FLAG_CACHE_MONT_P
#define DSA_FLAG_CACHE_MONT_P 0x01
Definition at line 40 of file dsa.h.
DSA_FLAG_FIPS_CHECKED
#define DSA_FLAG_FIPS_CHECKED 0x0800
Definition at line 64 of file dsa.h.
DSA_FLAG_FIPS_METHOD
#define DSA_FLAG_FIPS_METHOD 0x0400
Definition at line 55 of file dsa.h.
DSA_FLAG_NO_EXP_CONSTTIME
#define DSA_FLAG_NO_EXP_CONSTTIME 0x00
Definition at line 45 of file dsa.h.
DSA_FLAG_NON_FIPS_ALLOW
#define DSA_FLAG_NON_FIPS_ALLOW 0x0400
Definition at line 63 of file dsa.h.
DSA_get_ex_new_index
#define DSA_get_ex_new_index (l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_DSA, l, p, newf, dupf, freef)
Definition at line 112 of file dsa.h.
DSA_is_prime
#define DSA_is_prime (n, callback, cb_arg) BN_is_prime(n, DSS_prime_checks, callback, NULL, cb_arg)
Definition at line 154 of file dsa.h.
DSA_R_BAD_Q_VALUE
#define DSA_R_BAD_Q_VALUE 102
Definition at line 266 of file dsa.h.
DSA_R_BN_DECODE_ERROR
#define DSA_R_BN_DECODE_ERROR 108
Definition at line 267 of file dsa.h.
DSA_R_BN_ERROR
#define DSA_R_BN_ERROR 109
Definition at line 268 of file dsa.h.
DSA_R_DECODE_ERROR
#define DSA_R_DECODE_ERROR 104
Definition at line 269 of file dsa.h.
DSA_R_INVALID_DIGEST_TYPE
#define DSA_R_INVALID_DIGEST_TYPE 106
Definition at line 270 of file dsa.h.
DSA_R_INVALID_PARAMETERS
#define DSA_R_INVALID_PARAMETERS 112
Definition at line 271 of file dsa.h.
DSA_R_MISSING_PARAMETERS
#define DSA_R_MISSING_PARAMETERS 101
Definition at line 272 of file dsa.h.
DSA_R_MODULUS_TOO_LARGE
#define DSA_R_MODULUS_TOO_LARGE 103
Definition at line 273 of file dsa.h.
DSA_R_NO_PARAMETERS_SET
#define DSA_R_NO_PARAMETERS_SET 107
Definition at line 274 of file dsa.h.
DSA_R_PARAMETER_ENCODING_ERROR
#define DSA_R_PARAMETER_ENCODING_ERROR 105
Definition at line 275 of file dsa.h.
DSA_R_Q_NOT_PRIME
#define DSA_R_Q_NOT_PRIME 113
Definition at line 276 of file dsa.h.
DSA_R_SEED_LEN_SMALL
#define DSA_R_SEED_LEN_SMALL 110
Definition at line 277 of file dsa.h.
DSS_prime_checks
#define DSS_prime_checks 50
Definition at line 149 of file dsa.h.
EVP_PKEY_CTRL_DSA_PARAMGEN_BITS
#define EVP_PKEY_CTRL_DSA_PARAMGEN_BITS (EVP_PKEY_ALG_CTRL + 1)
Definition at line 169 of file dsa.h.
EVP_PKEY_CTRL_DSA_PARAMGEN_MD
#define EVP_PKEY_CTRL_DSA_PARAMGEN_MD (EVP_PKEY_ALG_CTRL + 3)
Definition at line 171 of file dsa.h.
EVP_PKEY_CTRL_DSA_PARAMGEN_Q_BITS
#define EVP_PKEY_CTRL_DSA_PARAMGEN_Q_BITS (EVP_PKEY_ALG_CTRL + 2)
Definition at line 170 of file dsa.h.
EVP_PKEY_CTX_set_dsa_paramgen_bits
#define EVP_PKEY_CTX_set_dsa_paramgen_bits (ctx, nbits)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_DSA, EVP_PKEY_OP_PARAMGEN, \
                                EVP_PKEY_CTRL_DSA_PARAMGEN_BITS, nbits, NULL)
Definition at line 165 of file dsa.h.
i2d_DSAparams_bio
#define i2d_DSAparams_bio (bp, x) ASN1_i2d_bio_of_const(DSA,i2d_DSAparams,bp,x)
Definition at line 77 of file dsa.h.
i2d_DSAparams_fp
#define i2d_DSAparams_fp (fp, x)
Value:
ASN1_i2d_fp(i2d_DSAparams,(fp), \
                (unsigned char *)(x))
Definition at line 74 of file dsa.h.
OPENSSL_DSA_FIPS_MIN_MODULUS_BITS
#define OPENSSL_DSA_FIPS_MIN_MODULUS_BITS 1024
Definition at line 38 of file dsa.h.
OPENSSL_DSA_MAX_MODULUS_BITS
#define OPENSSL_DSA_MAX_MODULUS_BITS 10000
Definition at line 35 of file dsa.h.
Function Documentation
d2i_DSA_SIG()
DSA_SIG* d2i_DSA_SIG (DSA_SIG ** v, const unsigned char ** pp, long length)
d2i_DSAparams()
DSA* d2i_DSAparams (DSA ** a, const unsigned char ** pp, long length)
d2i_DSAPrivateKey()
DSA* d2i_DSAPrivateKey (DSA ** a, const unsigned char ** pp, long length)
Referenced by d2i_DSAPrivateKey_bio(), and d2i_DSAPrivateKey_fp().
d2i_DSAPublicKey()
DSA* d2i_DSAPublicKey (DSA ** a, const unsigned char ** pp, long length)
DEPRECATEDIN_0_9_8()
DEPRECATEDIN_0_9_8 (DSA * DSA_generate_parametersint bits, unsigned char *seed, int seed_len, int *counter_ret, unsigned long *h_ret, void(*callback)(int, int, void *), void *cb_arg)
DSA_bits()
int DSA_bits (const DSA * d)
Definition at line 343 of file dsa_lib.c.
References BN_num_bits().
DSA_clear_flags()
void DSA_clear_flags (DSA * d, int flags)
Definition at line 323 of file dsa_lib.c.
DSA_do_sign()
DSA_SIG* DSA_do_sign (const unsigned char * dgst, int dlen, DSA * dsa)
Definition at line 16 of file dsa_sign.c.
DSA_do_verify()
int DSA_do_verify (const unsigned char * dgst, int dgst_len, DSA_SIG * sig, DSA * dsa)
Definition at line 15 of file dsa_vrf.c.
DSA_dup_DH()
DH* DSA_dup_DH (const DSA * r)
Definition at line 199 of file dsa_lib.c.
DSA_free()
void DSA_free (DSA * r)
Definition at line 116 of file dsa_lib.c.
References BN_clear_free(), CRYPTO_DOWN_REF, CRYPTO_EX_INDEX_DSA, CRYPTO_free_ex_data(), CRYPTO_THREAD_lock_free(), ENGINE_finish(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
DSA_generate_key()
int DSA_generate_key (DSA * a)
Definition at line 18 of file dsa_key.c.
DSA_get0_engine()
ENGINE* DSA_get0_engine (DSA * d)
Definition at line 338 of file dsa_lib.c.
DSA_get0_key()
void DSA_get0_key (const DSA * d, const BIGNUM ** pub_key, const BIGNUM ** priv_key)
Definition at line 293 of file dsa_lib.c.
References NULL.
DSA_get0_pqg()
void DSA_get0_pqg (const DSA * d, const BIGNUM ** p, const BIGNUM ** q, const BIGNUM ** g)
Definition at line 256 of file dsa_lib.c.
References NULL.
DSA_get_default_method()
const DSA_METHOD* DSA_get_default_method (void)
Definition at line 27 of file dsa_lib.c.
DSA_get_ex_data()
void* DSA_get_ex_data (DSA * d, int idx)
Definition at line 186 of file dsa_lib.c.
DSA_get_method()
const DSA_METHOD* DSA_get_method (DSA * d)
Definition at line 59 of file dsa_lib.c.
DSA_meth_dup()
DSA_METHOD* DSA_meth_dup (const DSA_METHOD * dsam)
Definition at line 48 of file dsa_meth.c.
DSA_meth_free()
void DSA_meth_free (DSA_METHOD * dsam)
Definition at line 40 of file dsa_meth.c.
References NULL, and OPENSSL_free.
DSA_meth_get0_app_data()
void* DSA_meth_get0_app_data (const DSA_METHOD * dsam)
Definition at line 97 of file dsa_meth.c.
DSA_meth_get0_name()
const char* DSA_meth_get0_name (const DSA_METHOD * dsam)
Definition at line 66 of file dsa_meth.c.
DSA_meth_get_flags()
int DSA_meth_get_flags (DSA_METHOD * dsam)
Definition at line 86 of file dsa_meth.c.
DSA_meth_new()
DSA_METHOD* DSA_meth_new (const char * name, int flags)
Definition at line 22 of file dsa_meth.c.
References DSA_F_DSA_METH_NEW, DSAerr, ERR_R_MALLOC_FAILURE, flags, NULL, OPENSSL_free, OPENSSL_strdup, and OPENSSL_zalloc.
DSA_meth_set0_app_data()
int DSA_meth_set0_app_data (DSA_METHOD * dsam, void * app_data)
Definition at line 102 of file dsa_meth.c.
DSA_meth_set1_name()
int DSA_meth_set1_name (DSA_METHOD * dsam, const char * name)
Definition at line 71 of file dsa_meth.c.
References DSA_F_DSA_METH_SET1_NAME, DSAerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, and OPENSSL_strdup.
DSA_meth_set_bn_mod_exp()
int DSA_meth_set_bn_mod_exp (DSA_METHOD * dsam, int(*)(DSA *, BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *, BN_MONT_CTX *) bn_mod_exp)
Definition at line 170 of file dsa_meth.c.
DSA_meth_set_finish()
int DSA_meth_set_finish (DSA_METHOD * dsam, int(*)(DSA *) finish)
Definition at line 194 of file dsa_meth.c.
DSA_meth_set_flags()
int DSA_meth_set_flags (DSA_METHOD * dsam, int flags)
Definition at line 91 of file dsa_meth.c.
References flags.
DSA_meth_set_init()
int DSA_meth_set_init (DSA_METHOD * dsam, int(*)(DSA *) init)
Definition at line 183 of file dsa_meth.c.
DSA_meth_set_keygen()
int DSA_meth_set_keygen (DSA_METHOD * dsam, int(*)(DSA *) keygen)
Definition at line 220 of file dsa_meth.c.
DSA_meth_set_mod_exp()
int DSA_meth_set_mod_exp (DSA_METHOD * dsam, int(*)(DSA *, BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *, BN_MONT_CTX *) mod_exp)
Definition at line 154 of file dsa_meth.c.
DSA_meth_set_paramgen()
int DSA_meth_set_paramgen (DSA_METHOD * dsam, int(*)(DSA *, int, const unsigned char *, int, int *, unsigned long *, BN_GENCB *) paramgen)
Definition at line 207 of file dsa_meth.c.
DSA_meth_set_sign()
int DSA_meth_set_sign (DSA_METHOD * dsam, DSA_SIG *(*)(const unsigned char *, int, DSA *) sign)
Definition at line 114 of file dsa_meth.c.
DSA_meth_set_sign_setup()
int DSA_meth_set_sign_setup (DSA_METHOD * dsam, int(*)(DSA *, BN_CTX *, BIGNUM **, BIGNUM **) sign_setup)
Definition at line 127 of file dsa_meth.c.
DSA_meth_set_verify()
int DSA_meth_set_verify (DSA_METHOD * dsam, int(*)(const unsigned char *, int, DSA_SIG *, DSA *) verify)
Definition at line 140 of file dsa_meth.c.
DSA_new()
DSA* DSA_new (void)
Definition at line 34 of file dsa_lib.c.
References DSA_new_method(), and NULL.
Referenced by d2i_DSA_PUBKEY_bio(), d2i_DSA_PUBKEY_fp(), d2i_DSAPrivateKey_bio(), d2i_DSAPrivateKey_fp(), get_dsa1024(), get_dsa2048(), and get_dsa512().
DSA_new_method()
DSA* DSA_new_method (ENGINE * engine)
Definition at line 64 of file dsa_lib.c.
Referenced by DSA_new().
DSA_OpenSSL()
const DSA_METHOD* DSA_OpenSSL (void)
Definition at line 44 of file dsa_ossl.c.
DSA_print()
int DSA_print (BIO * bp, const DSA * x, int off)
Definition at line 47 of file dsa_prn.c.
DSA_print_fp()
int DSA_print_fp (FILE * bp, const DSA * x, int off)
Definition at line 16 of file dsa_prn.c.
DSA_security_bits()
int DSA_security_bits (const DSA * d)
Definition at line 191 of file dsa_lib.c.
References BN_num_bits(), and BN_security_bits().
DSA_set0_key()
int DSA_set0_key (DSA * d, BIGNUM * pub_key, BIGNUM * priv_key)
Definition at line 302 of file dsa_lib.c.
References BN_free(), and NULL.
DSA_set0_pqg()
int DSA_set0_pqg (DSA * d, BIGNUM * p, BIGNUM * q, BIGNUM * g)
Definition at line 267 of file dsa_lib.c.
References BN_free(), NULL, and q.
DSA_set_default_method()
void DSA_set_default_method (const DSA_METHOD *)
Definition at line 22 of file dsa_lib.c.
DSA_set_ex_data()
int DSA_set_ex_data (DSA * d, int idx, void * arg)
Definition at line 181 of file dsa_lib.c.
DSA_set_flags()
void DSA_set_flags (DSA * d, int flags)
Definition at line 333 of file dsa_lib.c.
References flags.
DSA_set_method()
int DSA_set_method (DSA * dsa, const DSA_METHOD *)
Definition at line 39 of file dsa_lib.c.
References ENGINE_finish(), and NULL.
DSA_SIG_free()
void DSA_SIG_free (DSA_SIG * a)
DSA_SIG_get0()
void DSA_SIG_get0 (const DSA_SIG * sig, const BIGNUM ** pr, const BIGNUM ** ps)
DSA_SIG_new()
DSA_SIG* DSA_SIG_new (void)
DSA_SIG_set0()
int DSA_SIG_set0 (DSA_SIG * sig, BIGNUM * r, BIGNUM * s)
DSA_sign()
int DSA_sign (int type, const unsigned char * dgst, int dlen, unsigned char * sig, unsigned int * siglen, DSA * dsa)
DSA_sign_setup()
int DSA_sign_setup (DSA * dsa, BN_CTX * ctx_in, BIGNUM ** kinvp, BIGNUM ** rp)
Definition at line 21 of file dsa_sign.c.
DSA_size()
int DSA_size (const DSA *)
Definition at line 159 of file dsa_lib.c.
DSA_test_flags()
int DSA_test_flags (const DSA * d, int flags)
Definition at line 328 of file dsa_lib.c.
References flags.
DSA_up_ref()
int DSA_up_ref (DSA * r)
Definition at line 147 of file dsa_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
DSA_verify()
int DSA_verify (int type, const unsigned char * dgst, int dgst_len, const unsigned char * sigbuf, int siglen, DSA * dsa)
DSAparams_dup()
DSA* DSAparams_dup (DSA * x)
DSAparams_print()
int DSAparams_print (BIO * bp, const DSA * x)
Definition at line 59 of file dsa_prn.c.
DSAparams_print_fp()
int DSAparams_print_fp (FILE * fp, const DSA * x)
Definition at line 31 of file dsa_prn.c.
ERR_load_DSA_strings()
int ERR_load_DSA_strings (void)
Definition at line 66 of file dsa_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
i2d_DSA_SIG()
int i2d_DSA_SIG (const DSA_SIG * a, unsigned char ** pp)
i2d_DSAparams()
int i2d_DSAparams (const DSA * a, unsigned char ** pp)
i2d_DSAPrivateKey()
int i2d_DSAPrivateKey (const DSA * a, unsigned char ** pp)
Referenced by i2d_DSAPrivateKey_bio(), and i2d_DSAPrivateKey_fp().
i2d_DSAPublicKey()
int i2d_DSAPublicKey (const DSA * a, unsigned char ** pp)
Referenced by i2d_PublicKey().
Variable Documentation
bits
int bits
Definition at line 132 of file dsa.h.
cb
int const unsigned char int int unsigned long BN_GENCB* cb
Definition at line 132 of file dsa.h.
counter_ret
int const unsigned char int int* counter_ret
Definition at line 132 of file dsa.h.
DSA_meth_get_bn_mod_exp
int(*)(DSA *, BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *, BN_MONT_CTX *) DSA_meth_get_bn_mod_exp(const DSA_METHOD *dsam)
Definition at line 212 of file dsa.h.
DSA_meth_get_finish
int(*)(DSA *) DSA_meth_get_finish(const DSA_METHOD *dsam)
Definition at line 220 of file dsa.h.
DSA_meth_get_init
int(*)(DSA *) DSA_meth_get_init(const DSA_METHOD *dsam)
Definition at line 218 of file dsa.h.
DSA_meth_get_keygen
int(*)(DSA *) DSA_meth_get_keygen(const DSA_METHOD *dsam)
Definition at line 228 of file dsa.h.
DSA_meth_get_mod_exp
int(*)(DSA *, BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *, BN_MONT_CTX *) DSA_meth_get_mod_exp(const DSA_METHOD *dsam)
Definition at line 205 of file dsa.h.
DSA_meth_get_paramgen
int(*)(DSA *, int, const unsigned char *, int, int *, unsigned long *, BN_GENCB *) DSA_meth_get_paramgen(const DSA_METHOD *dsam)
Definition at line 222 of file dsa.h.
DSA_meth_get_sign
DSA_SIG*(*)(const unsigned char *, int, DSA *) DSA_meth_get_sign(const DSA_METHOD *dsam)
Definition at line 193 of file dsa.h.
DSA_meth_get_sign_setup
int(*)(DSA *, BN_CTX *, BIGNUM **, BIGNUM **) DSA_meth_get_sign_setup(const DSA_METHOD *dsam)
Definition at line 197 of file dsa.h.
DSA_meth_get_verify
int(*)(const unsigned char *, int, DSA_SIG *, DSA *) DSA_meth_get_verify(const DSA_METHOD *dsam)
Definition at line 201 of file dsa.h.
h_ret
int const unsigned char int int unsigned long* h_ret
Definition at line 132 of file dsa.h.
seed
int const unsigned char* seed
Definition at line 132 of file dsa.h.
seed_len
int const unsigned char int seed_len
Definition at line 132 of file dsa.h.