crypto/dsa/dsa_lib.c File Reference
dsa_lib.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/bn.h>
#include "dsa_locl.h"
#include <openssl/asn1.h>
#include <openssl/engine.h>
#include <openssl/dh.h>
Functions
void DSA_set_default_method (const DSA_METHOD *meth)
const DSA_METHOD * DSA_get_default_method (void)
DSA * DSA_new (void)
int DSA_set_method (DSA *dsa, const DSA_METHOD *meth)
const DSA_METHOD * DSA_get_method (DSA *d)
DSA * DSA_new_method (ENGINE *engine)
void DSA_free (DSA *r)
int DSA_up_ref (DSA *r)
int DSA_size (const DSA *r)
int DSA_set_ex_data (DSA *d, int idx, void *arg)
void * DSA_get_ex_data (DSA *d, int idx)
int DSA_security_bits (const DSA *d)
DH * DSA_dup_DH (const DSA *r)
void DSA_get0_pqg (const DSA *d, const BIGNUM **p, const BIGNUM **q, const BIGNUM **g)
int DSA_set0_pqg (DSA *d, BIGNUM *p, BIGNUM *q, BIGNUM *g)
void DSA_get0_key (const DSA *d, const BIGNUM **pub_key, const BIGNUM **priv_key)
int DSA_set0_key (DSA *d, BIGNUM *pub_key, BIGNUM *priv_key)
void DSA_clear_flags (DSA *d, int flags)
int DSA_test_flags (const DSA *d, int flags)
void DSA_set_flags (DSA *d, int flags)
ENGINE * DSA_get0_engine (DSA *d)
int DSA_bits (const DSA *dsa)
Function Documentation
DSA_bits()
int DSA_bits (const DSA * dsa)
Definition at line 343 of file dsa_lib.c.
References BN_num_bits().
DSA_clear_flags()
void DSA_clear_flags (DSA * d, int flags)
Definition at line 323 of file dsa_lib.c.
DSA_dup_DH()
DH* DSA_dup_DH (const DSA * r)
Definition at line 199 of file dsa_lib.c.
DSA_free()
void DSA_free (DSA * r)
Definition at line 116 of file dsa_lib.c.
References BN_clear_free(), CRYPTO_DOWN_REF, CRYPTO_EX_INDEX_DSA, CRYPTO_free_ex_data(), CRYPTO_THREAD_lock_free(), ENGINE_finish(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
DSA_get0_engine()
ENGINE* DSA_get0_engine (DSA * d)
Definition at line 338 of file dsa_lib.c.
DSA_get0_key()
void DSA_get0_key (const DSA * d, const BIGNUM ** pub_key, const BIGNUM ** priv_key)
Definition at line 293 of file dsa_lib.c.
References NULL.
DSA_get0_pqg()
void DSA_get0_pqg (const DSA * d, const BIGNUM ** p, const BIGNUM ** q, const BIGNUM ** g)
Definition at line 256 of file dsa_lib.c.
References NULL.
DSA_get_default_method()
const DSA_METHOD* DSA_get_default_method (void)
Definition at line 27 of file dsa_lib.c.
DSA_get_ex_data()
void* DSA_get_ex_data (DSA * d, int idx)
Definition at line 186 of file dsa_lib.c.
DSA_get_method()
const DSA_METHOD* DSA_get_method (DSA * d)
Definition at line 59 of file dsa_lib.c.
DSA_new()
DSA* DSA_new (void)
Definition at line 34 of file dsa_lib.c.
References DSA_new_method(), and NULL.
Referenced by d2i_DSA_PUBKEY_bio(), d2i_DSA_PUBKEY_fp(), d2i_DSAPrivateKey_bio(), d2i_DSAPrivateKey_fp(), get_dsa1024(), get_dsa2048(), and get_dsa512().
DSA_new_method()
DSA* DSA_new_method (ENGINE * engine)
Definition at line 64 of file dsa_lib.c.
Referenced by DSA_new().
DSA_security_bits()
int DSA_security_bits (const DSA * d)
Definition at line 191 of file dsa_lib.c.
References BN_num_bits(), and BN_security_bits().
DSA_set0_key()
int DSA_set0_key (DSA * d, BIGNUM * pub_key, BIGNUM * priv_key)
Definition at line 302 of file dsa_lib.c.
References BN_free(), and NULL.
DSA_set0_pqg()
int DSA_set0_pqg (DSA * d, BIGNUM * p, BIGNUM * q, BIGNUM * g)
Definition at line 267 of file dsa_lib.c.
References BN_free(), NULL, and q.
DSA_set_default_method()
void DSA_set_default_method (const DSA_METHOD * meth)
Definition at line 22 of file dsa_lib.c.
DSA_set_ex_data()
int DSA_set_ex_data (DSA * d, int idx, void * arg)
Definition at line 181 of file dsa_lib.c.
DSA_set_flags()
void DSA_set_flags (DSA * d, int flags)
Definition at line 333 of file dsa_lib.c.
References flags.
DSA_set_method()
int DSA_set_method (DSA * dsa, const DSA_METHOD * meth)
Definition at line 39 of file dsa_lib.c.
References ENGINE_finish(), and NULL.
DSA_size()
int DSA_size (const DSA * r)
Definition at line 159 of file dsa_lib.c.
DSA_test_flags()
int DSA_test_flags (const DSA * d, int flags)
Definition at line 328 of file dsa_lib.c.
References flags.
DSA_up_ref()
int DSA_up_ref (DSA * r)
Definition at line 147 of file dsa_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.