crypto/dso/dso_lib.c File Reference
dso_lib.c File Reference
#include "dso_locl.h"
Functions
DSO * DSO_new (void)
int DSO_free (DSO *dso)
int DSO_flags (DSO *dso)
int DSO_up_ref (DSO *dso)
DSO * DSO_load (DSO *dso, const char *filename, DSO_METHOD *meth, int flags)
DSO_FUNC_TYPE DSO_bind_func (DSO *dso, const char *symname)
long DSO_ctrl (DSO *dso, int cmd, long larg, void *parg)
const char * DSO_get_filename (DSO *dso)
int DSO_set_filename (DSO *dso, const char *filename)
char * DSO_merge (DSO *dso, const char *filespec1, const char *filespec2)
char * DSO_convert_filename (DSO *dso, const char *filename)
int DSO_pathbyaddr (void *addr, char *path, int sz)
DSO * DSO_dsobyaddr (void *addr, int flags)
void * DSO_global_lookup (const char *name)
Function Documentation
DSO_bind_func()
DSO_FUNC_TYPE DSO_bind_func (DSO * dso, const char * symname)
Definition at line 172 of file dso_lib.c.
References DSO_F_DSO_BIND_FUNC, DSO_R_SYM_FAILURE, DSO_R_UNSUPPORTED, DSOerr, ERR_R_PASSED_NULL_PARAMETER, and NULL.
DSO_convert_filename()
char* DSO_convert_filename (DSO * dso, const char * filename)
Definition at line 279 of file dso_lib.c.
References DSO_F_DSO_CONVERT_FILENAME, DSO_FLAG_NO_NAME_TRANSLATION, DSO_R_NO_FILENAME, DSOerr, ERR_R_MALLOC_FAILURE, ERR_R_PASSED_NULL_PARAMETER, NULL, and OPENSSL_strdup.
DSO_ctrl()
long DSO_ctrl (DSO * dso, int cmd, long larg, void * parg)
Definition at line 201 of file dso_lib.c.
References DSO_CTRL_GET_FLAGS, DSO_CTRL_OR_FLAGS, DSO_CTRL_SET_FLAGS, DSO_F_DSO_CTRL, DSO_R_UNSUPPORTED, DSOerr, ERR_R_PASSED_NULL_PARAMETER, and NULL.
DSO_dsobyaddr()
DSO* DSO_dsobyaddr (void * addr, int flags)
Definition at line 321 of file dso_lib.c.
References DSO_load(), DSO_pathbyaddr(), len, NULL, OPENSSL_free, and OPENSSL_malloc.
DSO_flags()
int DSO_flags (DSO * dso)
Definition at line 96 of file dso_lib.c.
References NULL.
DSO_free()
int DSO_free (DSO * dso)
Definition at line 61 of file dso_lib.c.
References CRYPTO_DOWN_REF, CRYPTO_THREAD_lock_free(), DSO_F_DSO_FREE, DSO_FLAG_NO_UNLOAD_ON_FREE, DSO_R_FINISH_FAILED, DSO_R_UNLOAD_FAILED, DSOerr, NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by comp_zlib_cleanup_int().
DSO_get_filename()
const char* DSO_get_filename (DSO * dso)
Definition at line 230 of file dso_lib.c.
References DSO_F_DSO_GET_FILENAME, DSOerr, ERR_R_PASSED_NULL_PARAMETER, and NULL.
DSO_global_lookup()
void* DSO_global_lookup (const char * name)
Definition at line 339 of file dso_lib.c.
DSO_load()
DSO* DSO_load (DSO * dso, const char * filename, DSO_METHOD * meth, int flags)
Definition at line 118 of file dso_lib.c.
Referenced by DSO_dsobyaddr().
DSO_merge()
char* DSO_merge (DSO * dso, const char * filespec1, const char * filespec2)
Definition at line 262 of file dso_lib.c.
References DSO_F_DSO_MERGE, DSO_FLAG_NO_NAME_TRANSLATION, DSOerr, ERR_R_PASSED_NULL_PARAMETER, and NULL.
DSO_new()
DSO* DSO_new (void)
Definition at line 56 of file dso_lib.c.
DSO_pathbyaddr()
int DSO_pathbyaddr (void * addr, char * path, int sz)
Definition at line 309 of file dso_lib.c.
Referenced by DSO_dsobyaddr().
DSO_set_filename()
int DSO_set_filename (DSO * dso, const char * filename)
Definition at line 239 of file dso_lib.c.
References DSO_F_DSO_SET_FILENAME, DSO_R_DSO_ALREADY_LOADED, DSOerr, ERR_R_MALLOC_FAILURE, ERR_R_PASSED_NULL_PARAMETER, NULL, OPENSSL_free, and OPENSSL_strdup.
DSO_up_ref()
int DSO_up_ref (DSO * dso)
Definition at line 101 of file dso_lib.c.
References CRYPTO_UP_REF, DSO_F_DSO_UP_REF, DSOerr, ERR_R_PASSED_NULL_PARAMETER, NULL, REF_ASSERT_ISNT, and REF_PRINT_COUNT.