crypto/evp/e_aes.c File Reference
e_aes.c File Reference
#include <openssl/opensslconf.h>
#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <openssl/err.h>
#include <string.h>
#include <assert.h>
#include <openssl/aes.h>
#include "internal/evp_int.h"
#include "modes_lcl.h"
#include <openssl/rand.h>
#include "evp_locl.h"
Data Structures
struct EVP_AES_KEY
struct EVP_AES_GCM_CTX
struct EVP_AES_XTS_CTX
struct EVP_AES_CCM_CTX
struct EVP_AES_OCB_CTX
Macros
#define MAXBITCHUNK ((size_t)1<<(sizeof(size_t)*8-4))
#define BLOCK_CIPHER_generic(nid, keylen, blocksize, ivlen, nmode, mode, MODE, flags)
#define BLOCK_CIPHER_custom(nid, keylen, blocksize, ivlen, mode, MODE, flags)
#define BLOCK_CIPHER_generic_pack(nid, keylen, flags)
#define CUSTOM_FLAGS
#define aes_xts_cleanup NULL
#define XTS_FLAGS
#define aes_ccm_cleanup NULL
#define WRAP_FLAGS
Functions
BLOCK_CIPHER_generic_pack (BLOCK_CIPHER_generic_pack(NID_aes, 128, 0)
BLOCK_CIPHER_custom (NID_aes, 128, 1, 12, gcm, GCM, EVP_CIPH_FLAG_AEAD_CIPHER|CUSTOM_FLAGS) BLOCK_CIPHER_custom(NID_aes
EVP_CIPH_FLAG_AEAD_CIPHER CUSTOM_FLAGS BLOCK_CIPHER_custom (NID_aes, 256, 1, 12, gcm, GCM, EVP_CIPH_FLAG_AEAD_CIPHER|CUSTOM_FLAGS) static int aes_xts_ctrl(EVP_CIPHER_CTX *c
if (type==EVP_CTRL_COPY)
else if (type !=EVP_CTRL_INIT)
BLOCK_CIPHER_custom (BLOCK_CIPHER_custom(NID_aes, 128, BLOCK_CIPHER_custom(1, BLOCK_CIPHER_custom(16, BLOCK_CIPHER_custom(xts, BLOCK_CIPHER_custom(XTS, XTS_FLAGS)
BLOCK_CIPHER_custom (NID_aes, 128, 1, 12, ccm, CCM, EVP_CIPH_FLAG_AEAD_CIPHER|CUSTOM_FLAGS) BLOCK_CIPHER_custom(NID_aes
EVP_CIPH_FLAG_AEAD_CIPHER CUSTOM_FLAGS BLOCK_CIPHER_custom (NID_aes, 256, 1, 12, ccm, CCM, EVP_CIPH_FLAG_AEAD_CIPHER|CUSTOM_FLAGS) typedef struct
const EVP_CIPHER * EVP_aes_128_wrap (void)
const EVP_CIPHER * EVP_aes_192_wrap (void)
const EVP_CIPHER * EVP_aes_256_wrap (void)
const EVP_CIPHER * EVP_aes_128_wrap_pad (void)
const EVP_CIPHER * EVP_aes_192_wrap_pad (void)
const EVP_CIPHER * EVP_aes_256_wrap_pad (void)
BLOCK_CIPHER_custom (NID_aes, 128, 16, 12, ocb, OCB, EVP_CIPH_FLAG_AEAD_CIPHER|CUSTOM_FLAGS) BLOCK_CIPHER_custom(NID_aes
Variables
gcm
GCM
EVP_CIPH_FLAG_AEAD_CIPHER CUSTOM_FLAGS int type
EVP_CIPH_FLAG_AEAD_CIPHER CUSTOM_FLAGS int int arg
EVP_CIPH_FLAG_AEAD_CIPHER CUSTOM_FLAGS int int void * ptr
ccm
CCM
EVP_AES_WRAP_CTX
ocb
OCB
Macro Definition Documentation
aes_ccm_cleanup
#define aes_ccm_cleanup NULL
Definition at line 2190 of file e_aes.c.
aes_xts_cleanup
#define aes_xts_cleanup NULL
Definition at line 1922 of file e_aes.c.
BLOCK_CIPHER_custom
#define BLOCK_CIPHER_custom (nid, keylen, blocksize, ivlen, mode, MODE, flags)
Value:
static const EVP_CIPHER aes_##keylen##_##mode = { \
        nid##_##keylen##_##mode,blocksize, \
        (EVP_CIPH_##MODE##_MODE==EVP_CIPH_XTS_MODE?2:1)*keylen/8, ivlen, \
        flags|EVP_CIPH_##MODE##_MODE,   \
        aes_##mode##_init_key,          \
        aes_##mode##_cipher,            \
        aes_##mode##_cleanup,           \
        sizeof(EVP_AES_##MODE##_CTX),   \
        NULL,NULL,aes_##mode##_ctrl,NULL }; \
const EVP_CIPHER *EVP_aes_##keylen##_##mode(void) \
{ return &aes_##keylen##_##mode; }
Definition at line 967 of file e_aes.c.
BLOCK_CIPHER_generic
#define BLOCK_CIPHER_generic (nid, keylen, blocksize, ivlen, nmode, mode, MODE, flags)
Value:
static const EVP_CIPHER aes_##keylen##_##mode = { \
        nid##_##keylen##_##nmode,blocksize,keylen/8,ivlen, \
        flags|EVP_CIPH_##MODE##_MODE,   \
        aes_init_key,                   \
        aes_##mode##_cipher,            \
        NULL,                           \
        sizeof(EVP_AES_KEY),            \
        NULL,NULL,NULL,NULL }; \
const EVP_CIPHER *EVP_aes_##keylen##_##mode(void) \
{ return &aes_##keylen##_##mode; }
Definition at line 955 of file e_aes.c.
BLOCK_CIPHER_generic_pack
#define BLOCK_CIPHER_generic_pack (nid, keylen, flags)
Value:
BLOCK_CIPHER_generic(nid,keylen,16,16,cbc,cbc,CBC,flags|EVP_CIPH_FLAG_DEFAULT_ASN1)     \
        BLOCK_CIPHER_generic(nid,keylen,16,0,ecb,ecb,ECB,flags|EVP_CIPH_FLAG_DEFAULT_ASN1)      \
        BLOCK_CIPHER_generic(nid,keylen,1,16,ofb128,ofb,OFB,flags|EVP_CIPH_FLAG_DEFAULT_ASN1)   \
        BLOCK_CIPHER_generic(nid,keylen,1,16,cfb128,cfb,CFB,flags|EVP_CIPH_FLAG_DEFAULT_ASN1)   \
        BLOCK_CIPHER_generic(nid,keylen,1,16,cfb1,cfb1,CFB,flags)       \
        BLOCK_CIPHER_generic(nid,keylen,1,16,cfb8,cfb8,CFB,flags)       \
        BLOCK_CIPHER_generic(nid,keylen,1,16,ctr,ctr,CTR,flags)
Definition at line 1024 of file e_aes.c.
CUSTOM_FLAGS
#define CUSTOM_FLAGS
Value:
(EVP_CIPH_FLAG_DEFAULT_ASN1 \
                | EVP_CIPH_CUSTOM_IV | EVP_CIPH_FLAG_CUSTOM_CIPHER \
                | EVP_CIPH_ALWAYS_CALL_INIT | EVP_CIPH_CTRL_INIT \
                | EVP_CIPH_CUSTOM_COPY)
Definition at line 1766 of file e_aes.c.
MAXBITCHUNK
#define MAXBITCHUNK ((size_t)1<<(sizeof(size_t)*8-4))
Definition at line 101 of file e_aes.c.
WRAP_FLAGS
#define WRAP_FLAGS
Value:
(EVP_CIPH_WRAP_MODE \
                | EVP_CIPH_CUSTOM_IV | EVP_CIPH_FLAG_CUSTOM_CIPHER \
                | EVP_CIPH_ALWAYS_CALL_INIT | EVP_CIPH_FLAG_DEFAULT_ASN1)
Definition at line 2290 of file e_aes.c.
XTS_FLAGS
#define XTS_FLAGS
Value:
(EVP_CIPH_FLAG_DEFAULT_ASN1 | EVP_CIPH_CUSTOM_IV \
                         | EVP_CIPH_ALWAYS_CALL_INIT | EVP_CIPH_CTRL_INIT \
                         | EVP_CIPH_CUSTOM_COPY)
Definition at line 1924 of file e_aes.c.
Function Documentation
BLOCK_CIPHER_custom() [1/6]
BLOCK_CIPHER_custom (NID_aes , 128 , 1 , 12 , gcm , GCM , EVP_CIPH_FLAG_AEAD_CIPHER| CUSTOM_FLAGS)
BLOCK_CIPHER_custom() [2/6]
EVP_CIPH_FLAG_AEAD_CIPHER CUSTOM_FLAGS BLOCK_CIPHER_custom (NID_aes , 256 , 1 , 12 , gcm , GCM , EVP_CIPH_FLAG_AEAD_CIPHER| CUSTOM_FLAGS)
BLOCK_CIPHER_custom() [3/6]
BLOCK_CIPHER_custom (BLOCK_CIPHER_custom(NID_aes, 128 , BLOCK_CIPHER_custom(1, BLOCK_CIPHER_custom(16, BLOCK_CIPHER_custom(xts, BLOCK_CIPHER_custom(XTS, XTS_FLAGS)
Definition at line 1928 of file e_aes.c.
References arg, EVP_AES_CCM_CTX::ccm, CRYPTO_ccm128_tag(), EVP_AEAD_TLS1_AAD_LEN, EVP_C_DATA, EVP_CCM_TLS_EXPLICIT_IV_LEN, EVP_CCM_TLS_FIXED_IV_LEN, EVP_CIPHER_CTX_buf_noconst(), EVP_CIPHER_CTX_encrypting(), EVP_CIPHER_CTX_iv_noconst(), EVP_CTRL_AEAD_GET_TAG, EVP_CTRL_AEAD_SET_IVLEN, EVP_CTRL_AEAD_SET_TAG, EVP_CTRL_AEAD_TLS1_AAD, EVP_CTRL_CCM_SET_IV_FIXED, EVP_CTRL_CCM_SET_L, EVP_CTRL_COPY, EVP_CTRL_INIT, EVP_AES_CCM_CTX::iv_set, EVP_AES_CCM_CTX::key_set, EVP_AES_CCM_CTX::ks, EVP_AES_CCM_CTX::L, EVP_AES_CCM_CTX::len_set, EVP_AES_CCM_CTX::M, ptr, EVP_AES_CCM_CTX::tag_set, and EVP_AES_CCM_CTX::tls_aad_len.
BLOCK_CIPHER_custom() [4/6]
BLOCK_CIPHER_custom (NID_aes , 128 , 1 , 12 , ccm , CCM , EVP_CIPH_FLAG_AEAD_CIPHER| CUSTOM_FLAGS)
BLOCK_CIPHER_custom() [5/6]
EVP_CIPH_FLAG_AEAD_CIPHER CUSTOM_FLAGS BLOCK_CIPHER_custom (NID_aes , 256 , 1 , 12 , ccm , CCM , EVP_CIPH_FLAG_AEAD_CIPHER| CUSTOM_FLAGS)
Definition at line 2196 of file e_aes.c.
BLOCK_CIPHER_custom() [6/6]
BLOCK_CIPHER_custom (NID_aes , 128 , 16 , 12 , ocb , OCB , EVP_CIPH_FLAG_AEAD_CIPHER| CUSTOM_FLAGS)
BLOCK_CIPHER_generic_pack()
BLOCK_CIPHER_generic_pack (BLOCK_CIPHER_generic_pack(NID_aes, 128 , 0)
Definition at line 1264 of file e_aes.c.
EVP_aes_128_wrap()
const EVP_CIPHER* EVP_aes_128_wrap (void)
Definition at line 2303 of file e_aes.c.
Referenced by openssl_add_all_ciphers_int().
EVP_aes_128_wrap_pad()
const EVP_CIPHER* EVP_aes_128_wrap_pad (void)
Definition at line 2345 of file e_aes.c.
Referenced by openssl_add_all_ciphers_int().
EVP_aes_192_wrap()
const EVP_CIPHER* EVP_aes_192_wrap (void)
Definition at line 2317 of file e_aes.c.
Referenced by openssl_add_all_ciphers_int().
EVP_aes_192_wrap_pad()
const EVP_CIPHER* EVP_aes_192_wrap_pad (void)
Definition at line 2359 of file e_aes.c.
Referenced by openssl_add_all_ciphers_int().
EVP_aes_256_wrap()
const EVP_CIPHER* EVP_aes_256_wrap (void)
Definition at line 2331 of file e_aes.c.
Referenced by openssl_add_all_ciphers_int().
EVP_aes_256_wrap_pad()
const EVP_CIPHER* EVP_aes_256_wrap_pad (void)
Definition at line 2373 of file e_aes.c.
Referenced by openssl_add_all_ciphers_int().
if() [1/2]
if (type = = EVP_CTRL_COPY)
Definition at line 1781 of file e_aes.c.
References EVP_C_DATA, EVP_AES_XTS_CTX::ks1, EVP_AES_XTS_CTX::ks2, ptr, and EVP_AES_XTS_CTX::xts.
Referenced by ASN1_GENERALIZEDTIME_adj(), ASN1_GENERALIZEDTIME_print(), asn1_generalizedtime_to_tm(), ASN1_UTCTIME_adj(), ASN1_UTCTIME_print(), asn1_utctime_to_tm(), BN_sub(), CMS_ReceiptRequest_get0_values(), CRYPTO_ccm128_aad(), CRYPTO_gcm128_aad(), CRYPTO_gcm128_finish(), EC_KEY_set_method(), WPACKET_reserve_bytes(), X509_cmp_time(), X509_NAME_get0_der(), and X509_VERIFY_PARAM_move_peername().
if() [2/2]
else if (type ! = EVP_CTRL_INIT)
Definition at line 1795 of file e_aes.c.
References AES_decrypt(), AES_encrypt(), AES_set_decrypt_key(), AES_set_encrypt_key(), EVP_C_DATA, EVP_CIPHER_CTX_iv_noconst(), EVP_CIPHER_CTX_key_length(), EVP_AES_XTS_CTX::ks, EVP_AES_XTS_CTX::ks1, EVP_AES_XTS_CTX::ks2, NULL, EVP_AES_XTS_CTX::stream, and EVP_AES_XTS_CTX::xts.
Variable Documentation
arg
EVP_CIPH_FLAG_AEAD_CIPHER CUSTOM_FLAGS int int arg
Definition at line 1778 of file e_aes.c.
Referenced by BLOCK_CIPHER_custom().
ccm
ccm
Definition at line 2194 of file e_aes.c.
CCM
CCM
Definition at line 2194 of file e_aes.c.
EVP_AES_WRAP_CTX
EVP_AES_WRAP_CTX
Definition at line 2206 of file e_aes.c.
GCM
GCM
Definition at line 1773 of file e_aes.c.
gcm
gcm
Definition at line 1773 of file e_aes.c.
OCB
OCB
Definition at line 2699 of file e_aes.c.
ocb
ocb
Definition at line 2699 of file e_aes.c.
ptr
EVP_CIPH_FLAG_AEAD_CIPHER CUSTOM_FLAGS int int void* ptr
Initial value:
{
    EVP_AES_XTS_CTX *xctx = EVP_C_DATA(EVP_AES_XTS_CTX,c)
Definition at line 1779 of file e_aes.c.
Referenced by BIO_set_data(), BLOCK_CIPHER_custom(), comp_zlib_cleanup_int(), CRYPTO_dup_ex_data(), CRYPTO_free_ex_data(), CRYPTO_new_ex_data(), CRYPTO_secure_actual_size(), engine_load_afalg_int(), and if().
type
const char int type
Definition at line 1778 of file e_aes.c.
Referenced by ASN1_item_sign_ctx(), ASN1_TYPE_set(), asn1_valid_host(), ASN1_verify(), BIO_meth_new(), dtls1_dispatch_alert(), EVP_DigestInit_ex(), EVP_PBE_find(), OBJ_NAME_cleanup(), ssl3_dispatch_alert(), STACK_OF(), tls_construct_server_key_exchange(), tls_finish_handshake(), tls_process_cert_status_body(), X509_NAME_ENTRY_set_data(), X509_REQ_print_ex(), and X509V3_NAME_from_section().