crypto/evp/e_aes_cbc_hmac_sha256.c File Reference
e_aes_cbc_hmac_sha256.c File Reference
#include <openssl/opensslconf.h>
#include <stdio.h>
#include <string.h>
#include <openssl/evp.h>
#include <openssl/objects.h>
#include <openssl/aes.h>
#include <openssl/sha.h>
#include <openssl/rand.h>
#include "modes_lcl.h"
#include "internal/constant_time_locl.h"
#include "internal/evp_int.h"
Data Structures
struct EVP_AES_HMAC_SHA256
Macros
#define NO_PAYLOAD_LENGTH ((size_t)-1)
Functions
const EVP_CIPHER * EVP_aes_128_cbc_hmac_sha256 (void)
const EVP_CIPHER * EVP_aes_256_cbc_hmac_sha256 (void)
Macro Definition Documentation
NO_PAYLOAD_LENGTH
#define NO_PAYLOAD_LENGTH ((size_t)-1)
Definition at line 35 of file e_aes_cbc_hmac_sha256.c.
Function Documentation
EVP_aes_128_cbc_hmac_sha256()
const EVP_CIPHER* EVP_aes_128_cbc_hmac_sha256 (void)
Definition at line 930 of file e_aes_cbc_hmac_sha256.c.
References NULL.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_aes_256_cbc_hmac_sha256()
const EVP_CIPHER* EVP_aes_256_cbc_hmac_sha256 (void)
Definition at line 935 of file e_aes_cbc_hmac_sha256.c.
References NULL.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().