crypto/evp/e_chacha20_poly1305.c File Reference
e_chacha20_poly1305.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/evp.h>
#include <openssl/objects.h>
#include "evp_locl.h"
#include "internal/evp_int.h"
#include "internal/chacha.h"
#include "internal/poly1305.h"
Data Structures
struct EVP_CHACHA_KEY
struct EVP_CHACHA_AEAD_CTX
Macros
#define data(ctx) ((EVP_CHACHA_KEY *)(ctx)->cipher_data)
#define NO_TLS_PAYLOAD_LENGTH ((size_t)-1)
#define aead_data(ctx) ((EVP_CHACHA_AEAD_CTX *)(ctx)->cipher_data)
#define POLY1305_ctx(actx) ((POLY1305 *)(actx + 1))
Functions
const EVP_CIPHER * EVP_chacha20 (void)
const EVP_CIPHER * EVP_chacha20_poly1305 (void)
Macro Definition Documentation
aead_data
#define aead_data (ctx) ((EVP_CHACHA_AEAD_CTX *)(ctx)->cipher_data)
Definition at line 159 of file e_chacha20_poly1305.c.
data
#define data (ctx) ((EVP_CHACHA_KEY *)(ctx)->cipher_data)
Definition at line 31 of file e_chacha20_poly1305.c.
NO_TLS_PAYLOAD_LENGTH
#define NO_TLS_PAYLOAD_LENGTH ((size_t)-1)
Definition at line 158 of file e_chacha20_poly1305.c.
POLY1305_ctx
#define POLY1305_ctx (actx) ((POLY1305 *)(actx + 1))
Definition at line 160 of file e_chacha20_poly1305.c.
Function Documentation
EVP_chacha20()
const EVP_CIPHER* EVP_chacha20 (void)
Definition at line 141 of file e_chacha20_poly1305.c.
Referenced by openssl_add_all_ciphers_int().
EVP_chacha20_poly1305()
const EVP_CIPHER* EVP_chacha20_poly1305 (void)
Definition at line 449 of file e_chacha20_poly1305.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().