include/openssl/ebcdic.h File Reference
ebcdic.h File Reference
#include <stdlib.h>
Macros
#define os_toascii _openssl_os_toascii
#define os_toebcdic _openssl_os_toebcdic
#define ebcdic2ascii _openssl_ebcdic2ascii
#define ascii2ebcdic _openssl_ascii2ebcdic
Functions
void * ebcdic2ascii (void *dest, const void *srce, size_t count)
void * ascii2ebcdic (void *dest, const void *srce, size_t count)
Variables
const unsigned char os_toascii [256]
const unsigned char os_toebcdic [256]
Macro Definition Documentation
ascii2ebcdic
#define ascii2ebcdic _openssl_ascii2ebcdic
Definition at line 23 of file ebcdic.h.
ebcdic2ascii
#define ebcdic2ascii _openssl_ebcdic2ascii
Definition at line 22 of file ebcdic.h.
os_toascii
#define os_toascii _openssl_os_toascii
Definition at line 20 of file ebcdic.h.
os_toebcdic
#define os_toebcdic _openssl_os_toebcdic
Definition at line 21 of file ebcdic.h.
Function Documentation
ascii2ebcdic()
void* ascii2ebcdic (void * dest, const void * srce, size_t count)
ebcdic2ascii()
void* ebcdic2ascii (void * dest, const void * srce, size_t count)
Referenced by ASN1_GENERALIZEDTIME_adj(), ASN1_UTCTIME_adj(), OPENSSL_buf2hexstr(), and s2i_ASN1_IA5STRING().
Variable Documentation
os_toascii
const unsigned char os_toascii[256]
Referenced by X509V3_NAME_from_section().
os_toebcdic
const unsigned char os_toebcdic[256]