crypto/ec/ec2_smpl.c File Reference
ec2_smpl.c File Reference
#include <openssl/err.h>
#include "internal/bn_int.h"
#include "ec_lcl.h"
Functions
const EC_METHOD * EC_GF2m_simple_method (void)
int ec_GF2m_simple_group_init (EC_GROUP *group)
void ec_GF2m_simple_group_finish (EC_GROUP *group)
void ec_GF2m_simple_group_clear_finish (EC_GROUP *group)
int ec_GF2m_simple_group_copy (EC_GROUP *dest, const EC_GROUP *src)
int ec_GF2m_simple_group_set_curve (EC_GROUP *group, const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int ec_GF2m_simple_group_get_curve (const EC_GROUP *group, BIGNUM *p, BIGNUM *a, BIGNUM *b, BN_CTX *ctx)
int ec_GF2m_simple_group_get_degree (const EC_GROUP *group)
int ec_GF2m_simple_group_check_discriminant (const EC_GROUP *group, BN_CTX *ctx)
int ec_GF2m_simple_point_init (EC_POINT *point)
void ec_GF2m_simple_point_finish (EC_POINT *point)
void ec_GF2m_simple_point_clear_finish (EC_POINT *point)
int ec_GF2m_simple_point_copy (EC_POINT *dest, const EC_POINT *src)
int ec_GF2m_simple_point_set_to_infinity (const EC_GROUP *group, EC_POINT *point)
int ec_GF2m_simple_point_set_affine_coordinates (const EC_GROUP *group, EC_POINT *point, const BIGNUM *x, const BIGNUM *y, BN_CTX *ctx)
int ec_GF2m_simple_point_get_affine_coordinates (const EC_GROUP *group, const EC_POINT *point, BIGNUM *x, BIGNUM *y, BN_CTX *ctx)
int ec_GF2m_simple_add (const EC_GROUP *group, EC_POINT *r, const EC_POINT *a, const EC_POINT *b, BN_CTX *ctx)
int ec_GF2m_simple_dbl (const EC_GROUP *group, EC_POINT *r, const EC_POINT *a, BN_CTX *ctx)
int ec_GF2m_simple_invert (const EC_GROUP *group, EC_POINT *point, BN_CTX *ctx)
int ec_GF2m_simple_is_at_infinity (const EC_GROUP *group, const EC_POINT *point)
int ec_GF2m_simple_is_on_curve (const EC_GROUP *group, const EC_POINT *point, BN_CTX *ctx)
int ec_GF2m_simple_cmp (const EC_GROUP *group, const EC_POINT *a, const EC_POINT *b, BN_CTX *ctx)
int ec_GF2m_simple_make_affine (const EC_GROUP *group, EC_POINT *point, BN_CTX *ctx)
int ec_GF2m_simple_points_make_affine (const EC_GROUP *group, size_t num, EC_POINT *points[], BN_CTX *ctx)
int ec_GF2m_simple_field_mul (const EC_GROUP *group, BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int ec_GF2m_simple_field_sqr (const EC_GROUP *group, BIGNUM *r, const BIGNUM *a, BN_CTX *ctx)
int ec_GF2m_simple_field_div (const EC_GROUP *group, BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
Function Documentation
ec_GF2m_simple_add()
int ec_GF2m_simple_add (const EC_GROUP * group, EC_POINT * r, const EC_POINT * a, const EC_POINT * b, BN_CTX * ctx)
Definition at line 423 of file ec2_smpl.c.
References NULL, and t.
Referenced by ec_GF2m_simple_dbl().
ec_GF2m_simple_cmp()
int ec_GF2m_simple_cmp (const EC_GROUP * group, const EC_POINT * a, const EC_POINT * b, BN_CTX * ctx)
Definition at line 634 of file ec2_smpl.c.
References NULL.
ec_GF2m_simple_dbl()
int ec_GF2m_simple_dbl (const EC_GROUP * group, EC_POINT * r, const EC_POINT * a, BN_CTX * ctx)
Definition at line 538 of file ec2_smpl.c.
References ec_GF2m_simple_add().
ec_GF2m_simple_field_div()
int ec_GF2m_simple_field_div (const EC_GROUP * group, BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Definition at line 752 of file ec2_smpl.c.
References BN_GF2m_mod_div().
ec_GF2m_simple_field_mul()
int ec_GF2m_simple_field_mul (const EC_GROUP * group, BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Definition at line 738 of file ec2_smpl.c.
References BN_GF2m_mod_mul_arr().
ec_GF2m_simple_field_sqr()
int ec_GF2m_simple_field_sqr (const EC_GROUP * group, BIGNUM * r, const BIGNUM * a, BN_CTX * ctx)
Definition at line 745 of file ec2_smpl.c.
References BN_GF2m_mod_sqr_arr().
ec_GF2m_simple_group_check_discriminant()
int ec_GF2m_simple_group_check_discriminant (const EC_GROUP * group, BN_CTX * ctx)
Definition at line 248 of file ec2_smpl.c.
ec_GF2m_simple_group_clear_finish()
void ec_GF2m_simple_group_clear_finish (EC_GROUP * group)
Definition at line 126 of file ec2_smpl.c.
References BN_clear_free().
ec_GF2m_simple_group_copy()
int ec_GF2m_simple_group_copy (EC_GROUP * dest, const EC_GROUP * src)
Definition at line 143 of file ec2_smpl.c.
References BN_BITS2, BN_copy(), bn_set_all_zero(), bn_wexpand(), and NULL.
ec_GF2m_simple_group_finish()
void ec_GF2m_simple_group_finish (EC_GROUP * group)
Definition at line 115 of file ec2_smpl.c.
References BN_free().
ec_GF2m_simple_group_get_curve()
int ec_GF2m_simple_group_get_curve (const EC_GROUP * group, BIGNUM * p, BIGNUM * a, BIGNUM * b, BN_CTX * ctx)
Definition at line 209 of file ec2_smpl.c.
ec_GF2m_simple_group_get_degree()
int ec_GF2m_simple_group_get_degree (const EC_GROUP * group)
Definition at line 239 of file ec2_smpl.c.
References BN_num_bits().
ec_GF2m_simple_group_init()
int ec_GF2m_simple_group_init (EC_GROUP * group)
Definition at line 96 of file ec2_smpl.c.
References BN_free(), BN_new(), and NULL.
ec_GF2m_simple_group_set_curve()
int ec_GF2m_simple_group_set_curve (EC_GROUP * group, const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Definition at line 169 of file ec2_smpl.c.
ec_GF2m_simple_invert()
int ec_GF2m_simple_invert (const EC_GROUP * group, EC_POINT * point, BN_CTX * ctx)
Definition at line 544 of file ec2_smpl.c.
References BN_GF2m_add(), BN_is_zero(), EC_POINT_is_at_infinity(), and EC_POINT_make_affine().
ec_GF2m_simple_is_at_infinity()
int ec_GF2m_simple_is_at_infinity (const EC_GROUP * group, const EC_POINT * point)
Definition at line 556 of file ec2_smpl.c.
References BN_is_zero().
ec_GF2m_simple_is_on_curve()
int ec_GF2m_simple_is_on_curve (const EC_GROUP * group, const EC_POINT * point, BN_CTX * ctx)
Definition at line 567 of file ec2_smpl.c.
ec_GF2m_simple_make_affine()
int ec_GF2m_simple_make_affine (const EC_GROUP * group, EC_POINT * point, BN_CTX * ctx)
Definition at line 680 of file ec2_smpl.c.
References NULL.
EC_GF2m_simple_method()
const EC_METHOD* EC_GF2m_simple_method (void)
Returns the basic GF2m ec method
Returns
EC_METHOD object
Definition at line 32 of file ec2_smpl.c.
ec_GF2m_simple_point_clear_finish()
void ec_GF2m_simple_point_clear_finish (EC_POINT * point)
Definition at line 312 of file ec2_smpl.c.
References BN_clear_free().
ec_GF2m_simple_point_copy()
int ec_GF2m_simple_point_copy (EC_POINT * dest, const EC_POINT * src)
Definition at line 324 of file ec2_smpl.c.
References BN_copy().
ec_GF2m_simple_point_finish()
void ec_GF2m_simple_point_finish (EC_POINT * point)
Definition at line 304 of file ec2_smpl.c.
References BN_free().
ec_GF2m_simple_point_get_affine_coordinates()
int ec_GF2m_simple_point_get_affine_coordinates (const EC_GROUP * group, const EC_POINT * point, BIGNUM * x, BIGNUM * y, BN_CTX * ctx)
Definition at line 385 of file ec2_smpl.c.
ec_GF2m_simple_point_init()
int ec_GF2m_simple_point_init (EC_POINT * point)
Definition at line 288 of file ec2_smpl.c.
References BN_free(), BN_new(), and NULL.
ec_GF2m_simple_point_set_affine_coordinates()
int ec_GF2m_simple_point_set_affine_coordinates (const EC_GROUP * group, EC_POINT * point, const BIGNUM * x, const BIGNUM * y, BN_CTX * ctx)
Definition at line 353 of file ec2_smpl.c.
ec_GF2m_simple_point_set_to_infinity()
int ec_GF2m_simple_point_set_to_infinity (const EC_GROUP * group, EC_POINT * point)
Definition at line 341 of file ec2_smpl.c.
References BN_zero.
ec_GF2m_simple_points_make_affine()
int ec_GF2m_simple_points_make_affine (const EC_GROUP * group, size_t num, EC_POINT * points[], BN_CTX * ctx)
Definition at line 724 of file ec2_smpl.c.