crypto/ec/ec2_mult.c File Reference
ec2_mult.c File Reference
#include <openssl/err.h>
#include "internal/bn_int.h"
#include "ec_lcl.h"
Functions
int ec_GF2m_simple_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *scalar, size_t num, const EC_POINT *points[], const BIGNUM *scalars[], BN_CTX *ctx)
int ec_GF2m_precompute_mult (EC_GROUP *group, BN_CTX *ctx)
int ec_GF2m_have_precompute_mult (const EC_GROUP *group)
Function Documentation
ec_GF2m_have_precompute_mult()
int ec_GF2m_have_precompute_mult (const EC_GROUP * group)
Definition at line 413 of file ec2_mult.c.
References ec_wNAF_have_precompute_mult().
ec_GF2m_precompute_mult()
int ec_GF2m_precompute_mult (EC_GROUP * group, BN_CTX * ctx)
Definition at line 408 of file ec2_mult.c.
References ec_wNAF_precompute_mult().
ec_GF2m_simple_mul()
int ec_GF2m_simple_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * scalar, size_t num, const EC_POINT * points[], const BIGNUM * scalars[], BN_CTX * ctx)
Definition at line 332 of file ec2_mult.c.
References BN_CTX_new(), EC_GROUP_have_precompute_mult(), EC_POINT_new(), EC_POINT_set_to_infinity(), ec_wNAF_mul(), and NULL.