include/openssl/ec.h File Reference
ec.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/asn1.h>
#include <openssl/symhacks.h>
#include <openssl/bn.h>
Data Structures
struct EC_builtin_curve
Macros
#define OPENSSL_ECC_MAX_FIELD_BITS 661
#define OPENSSL_EC_EXPLICIT_CURVE 0x000
#define OPENSSL_EC_NAMED_CURVE 0x001
#define d2i_ECPKParameters_bio(bp, x) ASN1_d2i_bio_of(EC_GROUP,NULL,d2i_ECPKParameters,bp,x)
#define i2d_ECPKParameters_bio(bp, x) ASN1_i2d_bio_of_const(EC_GROUP,i2d_ECPKParameters,bp,x)
#define d2i_ECPKParameters_fp(fp, x)
#define i2d_ECPKParameters_fp(fp, x)
#define EC_PKEY_NO_PARAMETERS 0x001
#define EC_PKEY_NO_PUBKEY 0x002
#define EC_FLAG_NON_FIPS_ALLOW 0x1
#define EC_FLAG_FIPS_CHECKED 0x2
#define EC_FLAG_COFACTOR_ECDH 0x1000
#define EC_KEY_get_ex_new_index(l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_EC_KEY, l, p, newf, dupf, freef)
#define ECParameters_dup(x) ASN1_dup_of(EC_KEY,i2d_ECParameters,d2i_ECParameters,x)
#define EVP_PKEY_CTX_set_ec_paramgen_curve_nid(ctx, nid)
#define EVP_PKEY_CTX_set_ec_param_enc(ctx, flag)
#define EVP_PKEY_CTX_set_ecdh_cofactor_mode(ctx, flag)
#define EVP_PKEY_CTX_get_ecdh_cofactor_mode(ctx)
#define EVP_PKEY_CTX_set_ecdh_kdf_type(ctx, kdf)
#define EVP_PKEY_CTX_get_ecdh_kdf_type(ctx)
#define EVP_PKEY_CTX_set_ecdh_kdf_md(ctx, md)
#define EVP_PKEY_CTX_get_ecdh_kdf_md(ctx, pmd)
#define EVP_PKEY_CTX_set_ecdh_kdf_outlen(ctx, len)
#define EVP_PKEY_CTX_get_ecdh_kdf_outlen(ctx, plen)
#define EVP_PKEY_CTX_set0_ecdh_kdf_ukm(ctx, p, plen)
#define EVP_PKEY_CTX_get0_ecdh_kdf_ukm(ctx, p)
#define EVP_PKEY_CTRL_EC_PARAMGEN_CURVE_NID (EVP_PKEY_ALG_CTRL + 1)
#define EVP_PKEY_CTRL_EC_PARAM_ENC (EVP_PKEY_ALG_CTRL + 2)
#define EVP_PKEY_CTRL_EC_ECDH_COFACTOR (EVP_PKEY_ALG_CTRL + 3)
#define EVP_PKEY_CTRL_EC_KDF_TYPE (EVP_PKEY_ALG_CTRL + 4)
#define EVP_PKEY_CTRL_EC_KDF_MD (EVP_PKEY_ALG_CTRL + 5)
#define EVP_PKEY_CTRL_GET_EC_KDF_MD (EVP_PKEY_ALG_CTRL + 6)
#define EVP_PKEY_CTRL_EC_KDF_OUTLEN (EVP_PKEY_ALG_CTRL + 7)
#define EVP_PKEY_CTRL_GET_EC_KDF_OUTLEN (EVP_PKEY_ALG_CTRL + 8)
#define EVP_PKEY_CTRL_EC_KDF_UKM (EVP_PKEY_ALG_CTRL + 9)
#define EVP_PKEY_CTRL_GET_EC_KDF_UKM (EVP_PKEY_ALG_CTRL + 10)
#define EVP_PKEY_ECDH_KDF_NONE 1
#define EVP_PKEY_ECDH_KDF_X9_62 2
#define EC_F_BN_TO_FELEM 224
#define EC_F_D2I_ECPARAMETERS 144
#define EC_F_D2I_ECPKPARAMETERS 145
#define EC_F_D2I_ECPRIVATEKEY 146
#define EC_F_DO_EC_KEY_PRINT 221
#define EC_F_ECDH_CMS_DECRYPT 238
#define EC_F_ECDH_CMS_SET_SHARED_INFO 239
#define EC_F_ECDH_COMPUTE_KEY 246
#define EC_F_ECDH_SIMPLE_COMPUTE_KEY 257
#define EC_F_ECDSA_DO_SIGN_EX 251
#define EC_F_ECDSA_DO_VERIFY 252
#define EC_F_ECDSA_SIGN_EX 254
#define EC_F_ECDSA_SIGN_SETUP 248
#define EC_F_ECDSA_SIG_NEW 265
#define EC_F_ECDSA_VERIFY 253
#define EC_F_ECKEY_PARAM2TYPE 223
#define EC_F_ECKEY_PARAM_DECODE 212
#define EC_F_ECKEY_PRIV_DECODE 213
#define EC_F_ECKEY_PRIV_ENCODE 214
#define EC_F_ECKEY_PUB_DECODE 215
#define EC_F_ECKEY_PUB_ENCODE 216
#define EC_F_ECKEY_TYPE2PARAM 220
#define EC_F_ECPARAMETERS_PRINT 147
#define EC_F_ECPARAMETERS_PRINT_FP 148
#define EC_F_ECPKPARAMETERS_PRINT 149
#define EC_F_ECPKPARAMETERS_PRINT_FP 150
#define EC_F_ECP_NISTZ256_GET_AFFINE 240
#define EC_F_ECP_NISTZ256_MULT_PRECOMPUTE 243
#define EC_F_ECP_NISTZ256_POINTS_MUL 241
#define EC_F_ECP_NISTZ256_PRE_COMP_NEW 244
#define EC_F_ECP_NISTZ256_WINDOWED_MUL 242
#define EC_F_ECX_KEY_OP 266
#define EC_F_ECX_PRIV_ENCODE 267
#define EC_F_ECX_PUB_ENCODE 268
#define EC_F_EC_ASN1_GROUP2CURVE 153
#define EC_F_EC_ASN1_GROUP2FIELDID 154
#define EC_F_EC_GF2M_MONTGOMERY_POINT_MULTIPLY 208
#define EC_F_EC_GF2M_SIMPLE_GROUP_CHECK_DISCRIMINANT 159
#define EC_F_EC_GF2M_SIMPLE_GROUP_SET_CURVE 195
#define EC_F_EC_GF2M_SIMPLE_OCT2POINT 160
#define EC_F_EC_GF2M_SIMPLE_POINT2OCT 161
#define EC_F_EC_GF2M_SIMPLE_POINT_GET_AFFINE_COORDINATES 162
#define EC_F_EC_GF2M_SIMPLE_POINT_SET_AFFINE_COORDINATES 163
#define EC_F_EC_GF2M_SIMPLE_SET_COMPRESSED_COORDINATES 164
#define EC_F_EC_GFP_MONT_FIELD_DECODE 133
#define EC_F_EC_GFP_MONT_FIELD_ENCODE 134
#define EC_F_EC_GFP_MONT_FIELD_MUL 131
#define EC_F_EC_GFP_MONT_FIELD_SET_TO_ONE 209
#define EC_F_EC_GFP_MONT_FIELD_SQR 132
#define EC_F_EC_GFP_MONT_GROUP_SET_CURVE 189
#define EC_F_EC_GFP_NISTP224_GROUP_SET_CURVE 225
#define EC_F_EC_GFP_NISTP224_POINTS_MUL 228
#define EC_F_EC_GFP_NISTP224_POINT_GET_AFFINE_COORDINATES 226
#define EC_F_EC_GFP_NISTP256_GROUP_SET_CURVE 230
#define EC_F_EC_GFP_NISTP256_POINTS_MUL 231
#define EC_F_EC_GFP_NISTP256_POINT_GET_AFFINE_COORDINATES 232
#define EC_F_EC_GFP_NISTP521_GROUP_SET_CURVE 233
#define EC_F_EC_GFP_NISTP521_POINTS_MUL 234
#define EC_F_EC_GFP_NISTP521_POINT_GET_AFFINE_COORDINATES 235
#define EC_F_EC_GFP_NIST_FIELD_MUL 200
#define EC_F_EC_GFP_NIST_FIELD_SQR 201
#define EC_F_EC_GFP_NIST_GROUP_SET_CURVE 202
#define EC_F_EC_GFP_SIMPLE_GROUP_CHECK_DISCRIMINANT 165
#define EC_F_EC_GFP_SIMPLE_GROUP_SET_CURVE 166
#define EC_F_EC_GFP_SIMPLE_MAKE_AFFINE 102
#define EC_F_EC_GFP_SIMPLE_OCT2POINT 103
#define EC_F_EC_GFP_SIMPLE_POINT2OCT 104
#define EC_F_EC_GFP_SIMPLE_POINTS_MAKE_AFFINE 137
#define EC_F_EC_GFP_SIMPLE_POINT_GET_AFFINE_COORDINATES 167
#define EC_F_EC_GFP_SIMPLE_POINT_SET_AFFINE_COORDINATES 168
#define EC_F_EC_GFP_SIMPLE_SET_COMPRESSED_COORDINATES 169
#define EC_F_EC_GROUP_CHECK 170
#define EC_F_EC_GROUP_CHECK_DISCRIMINANT 171
#define EC_F_EC_GROUP_COPY 106
#define EC_F_EC_GROUP_GET_CURVE_GF2M 172
#define EC_F_EC_GROUP_GET_CURVE_GFP 130
#define EC_F_EC_GROUP_GET_DEGREE 173
#define EC_F_EC_GROUP_GET_ECPARAMETERS 261
#define EC_F_EC_GROUP_GET_ECPKPARAMETERS 262
#define EC_F_EC_GROUP_GET_PENTANOMIAL_BASIS 193
#define EC_F_EC_GROUP_GET_TRINOMIAL_BASIS 194
#define EC_F_EC_GROUP_NEW 108
#define EC_F_EC_GROUP_NEW_BY_CURVE_NAME 174
#define EC_F_EC_GROUP_NEW_FROM_DATA 175
#define EC_F_EC_GROUP_NEW_FROM_ECPARAMETERS 263
#define EC_F_EC_GROUP_NEW_FROM_ECPKPARAMETERS 264
#define EC_F_EC_GROUP_SET_CURVE_GF2M 176
#define EC_F_EC_GROUP_SET_CURVE_GFP 109
#define EC_F_EC_GROUP_SET_GENERATOR 111
#define EC_F_EC_KEY_CHECK_KEY 177
#define EC_F_EC_KEY_COPY 178
#define EC_F_EC_KEY_GENERATE_KEY 179
#define EC_F_EC_KEY_NEW 182
#define EC_F_EC_KEY_NEW_METHOD 245
#define EC_F_EC_KEY_OCT2PRIV 255
#define EC_F_EC_KEY_PRINT 180
#define EC_F_EC_KEY_PRINT_FP 181
#define EC_F_EC_KEY_PRIV2OCT 256
#define EC_F_EC_KEY_SET_PUBLIC_KEY_AFFINE_COORDINATES 229
#define EC_F_EC_KEY_SIMPLE_CHECK_KEY 258
#define EC_F_EC_KEY_SIMPLE_OCT2PRIV 259
#define EC_F_EC_KEY_SIMPLE_PRIV2OCT 260
#define EC_F_EC_POINTS_MAKE_AFFINE 136
#define EC_F_EC_POINT_ADD 112
#define EC_F_EC_POINT_CMP 113
#define EC_F_EC_POINT_COPY 114
#define EC_F_EC_POINT_DBL 115
#define EC_F_EC_POINT_GET_AFFINE_COORDINATES_GF2M 183
#define EC_F_EC_POINT_GET_AFFINE_COORDINATES_GFP 116
#define EC_F_EC_POINT_GET_JPROJECTIVE_COORDINATES_GFP 117
#define EC_F_EC_POINT_INVERT 210
#define EC_F_EC_POINT_IS_AT_INFINITY 118
#define EC_F_EC_POINT_IS_ON_CURVE 119
#define EC_F_EC_POINT_MAKE_AFFINE 120
#define EC_F_EC_POINT_NEW 121
#define EC_F_EC_POINT_OCT2POINT 122
#define EC_F_EC_POINT_POINT2OCT 123
#define EC_F_EC_POINT_SET_AFFINE_COORDINATES_GF2M 185
#define EC_F_EC_POINT_SET_AFFINE_COORDINATES_GFP 124
#define EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GF2M 186
#define EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GFP 125
#define EC_F_EC_POINT_SET_JPROJECTIVE_COORDINATES_GFP 126
#define EC_F_EC_POINT_SET_TO_INFINITY 127
#define EC_F_EC_PRE_COMP_NEW 196
#define EC_F_EC_WNAF_MUL 187
#define EC_F_EC_WNAF_PRECOMPUTE_MULT 188
#define EC_F_I2D_ECPARAMETERS 190
#define EC_F_I2D_ECPKPARAMETERS 191
#define EC_F_I2D_ECPRIVATEKEY 192
#define EC_F_I2O_ECPUBLICKEY 151
#define EC_F_NISTP224_PRE_COMP_NEW 227
#define EC_F_NISTP256_PRE_COMP_NEW 236
#define EC_F_NISTP521_PRE_COMP_NEW 237
#define EC_F_O2I_ECPUBLICKEY 152
#define EC_F_OLD_EC_PRIV_DECODE 222
#define EC_F_OSSL_ECDH_COMPUTE_KEY 247
#define EC_F_OSSL_ECDSA_SIGN_SIG 249
#define EC_F_OSSL_ECDSA_VERIFY_SIG 250
#define EC_F_PKEY_ECX_DERIVE 269
#define EC_F_PKEY_EC_CTRL 197
#define EC_F_PKEY_EC_CTRL_STR 198
#define EC_F_PKEY_EC_DERIVE 217
#define EC_F_PKEY_EC_KEYGEN 199
#define EC_F_PKEY_EC_PARAMGEN 219
#define EC_F_PKEY_EC_SIGN 218
#define EC_R_ASN1_ERROR 115
#define EC_R_BAD_SIGNATURE 156
#define EC_R_BIGNUM_OUT_OF_RANGE 144
#define EC_R_BUFFER_TOO_SMALL 100
#define EC_R_COORDINATES_OUT_OF_RANGE 146
#define EC_R_CURVE_DOES_NOT_SUPPORT_ECDH 160
#define EC_R_CURVE_DOES_NOT_SUPPORT_SIGNING 159
#define EC_R_D2I_ECPKPARAMETERS_FAILURE 117
#define EC_R_DECODE_ERROR 142
#define EC_R_DISCRIMINANT_IS_ZERO 118
#define EC_R_EC_GROUP_NEW_BY_NAME_FAILURE 119
#define EC_R_FIELD_TOO_LARGE 143
#define EC_R_GF2M_NOT_SUPPORTED 147
#define EC_R_GROUP2PKPARAMETERS_FAILURE 120
#define EC_R_I2D_ECPKPARAMETERS_FAILURE 121
#define EC_R_INCOMPATIBLE_OBJECTS 101
#define EC_R_INVALID_ARGUMENT 112
#define EC_R_INVALID_COMPRESSED_POINT 110
#define EC_R_INVALID_COMPRESSION_BIT 109
#define EC_R_INVALID_CURVE 141
#define EC_R_INVALID_DIGEST 151
#define EC_R_INVALID_DIGEST_TYPE 138
#define EC_R_INVALID_ENCODING 102
#define EC_R_INVALID_FIELD 103
#define EC_R_INVALID_FORM 104
#define EC_R_INVALID_GROUP_ORDER 122
#define EC_R_INVALID_KEY 116
#define EC_R_INVALID_OUTPUT_LENGTH 161
#define EC_R_INVALID_PEER_KEY 133
#define EC_R_INVALID_PENTANOMIAL_BASIS 132
#define EC_R_INVALID_PRIVATE_KEY 123
#define EC_R_INVALID_TRINOMIAL_BASIS 137
#define EC_R_KDF_PARAMETER_ERROR 148
#define EC_R_KEYS_NOT_SET 140
#define EC_R_MISSING_PARAMETERS 124
#define EC_R_MISSING_PRIVATE_KEY 125
#define EC_R_NEED_NEW_SETUP_VALUES 157
#define EC_R_NOT_A_NIST_PRIME 135
#define EC_R_NOT_IMPLEMENTED 126
#define EC_R_NOT_INITIALIZED 111
#define EC_R_NO_PARAMETERS_SET 139
#define EC_R_NO_PRIVATE_VALUE 154
#define EC_R_OPERATION_NOT_SUPPORTED 152
#define EC_R_PASSED_NULL_PARAMETER 134
#define EC_R_PEER_KEY_ERROR 149
#define EC_R_PKPARAMETERS2GROUP_FAILURE 127
#define EC_R_POINT_ARITHMETIC_FAILURE 155
#define EC_R_POINT_AT_INFINITY 106
#define EC_R_POINT_IS_NOT_ON_CURVE 107
#define EC_R_RANDOM_NUMBER_GENERATION_FAILED 158
#define EC_R_SHARED_INFO_ERROR 150
#define EC_R_SLOT_FULL 108
#define EC_R_UNDEFINED_GENERATOR 113
#define EC_R_UNDEFINED_ORDER 128
#define EC_R_UNKNOWN_GROUP 129
#define EC_R_UNKNOWN_ORDER 114
#define EC_R_UNSUPPORTED_FIELD 131
#define EC_R_WRONG_CURVE_PARAMETERS 145
#define EC_R_WRONG_ORDER 130
Enumerations
enum point_conversion_form_t { POINT_CONVERSION_COMPRESSED = 2, POINT_CONVERSION_UNCOMPRESSED = 4, POINT_CONVERSION_HYBRID = 6 }
Functions
const EC_METHOD * EC_GFp_simple_method (void)
const EC_METHOD * EC_GFp_mont_method (void)
const EC_METHOD * EC_GFp_nist_method (void)
const EC_METHOD * EC_GFp_nistp224_method (void)
const EC_METHOD * EC_GFp_nistp256_method (void)
const EC_METHOD * EC_GFp_nistp521_method (void)
const EC_METHOD * EC_GF2m_simple_method (void)
EC_GROUP * EC_GROUP_new (const EC_METHOD *meth)
void EC_GROUP_free (EC_GROUP *group)
void EC_GROUP_clear_free (EC_GROUP *group)
int EC_GROUP_copy (EC_GROUP *dst, const EC_GROUP *src)
EC_GROUP * EC_GROUP_dup (const EC_GROUP *src)
const EC_METHOD * EC_GROUP_method_of (const EC_GROUP *group)
int EC_METHOD_get_field_type (const EC_METHOD *meth)
int EC_GROUP_set_generator (EC_GROUP *group, const EC_POINT *generator, const BIGNUM *order, const BIGNUM *cofactor)
const EC_POINT * EC_GROUP_get0_generator (const EC_GROUP *group)
BN_MONT_CTX * EC_GROUP_get_mont_data (const EC_GROUP *group)
int EC_GROUP_get_order (const EC_GROUP *group, BIGNUM *order, BN_CTX *ctx)
const BIGNUM * EC_GROUP_get0_order (const EC_GROUP *group)
int EC_GROUP_order_bits (const EC_GROUP *group)
int EC_GROUP_get_cofactor (const EC_GROUP *group, BIGNUM *cofactor, BN_CTX *ctx)
const BIGNUM * EC_GROUP_get0_cofactor (const EC_GROUP *group)
void EC_GROUP_set_curve_name (EC_GROUP *group, int nid)
int EC_GROUP_get_curve_name (const EC_GROUP *group)
void EC_GROUP_set_asn1_flag (EC_GROUP *group, int flag)
int EC_GROUP_get_asn1_flag (const EC_GROUP *group)
void EC_GROUP_set_point_conversion_form (EC_GROUP *group, point_conversion_form_t form)
point_conversion_form_t EC_GROUP_get_point_conversion_form (const EC_GROUP *)
unsigned char * EC_GROUP_get0_seed (const EC_GROUP *x)
size_t EC_GROUP_get_seed_len (const EC_GROUP *)
size_t EC_GROUP_set_seed (EC_GROUP *, const unsigned char *, size_t len)
int EC_GROUP_set_curve_GFp (EC_GROUP *group, const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int EC_GROUP_get_curve_GFp (const EC_GROUP *group, BIGNUM *p, BIGNUM *a, BIGNUM *b, BN_CTX *ctx)
int EC_GROUP_set_curve_GF2m (EC_GROUP *group, const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int EC_GROUP_get_curve_GF2m (const EC_GROUP *group, BIGNUM *p, BIGNUM *a, BIGNUM *b, BN_CTX *ctx)
int EC_GROUP_get_degree (const EC_GROUP *group)
int EC_GROUP_check (const EC_GROUP *group, BN_CTX *ctx)
int EC_GROUP_check_discriminant (const EC_GROUP *group, BN_CTX *ctx)
int EC_GROUP_cmp (const EC_GROUP *a, const EC_GROUP *b, BN_CTX *ctx)
EC_GROUP * EC_GROUP_new_curve_GFp (const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
EC_GROUP * EC_GROUP_new_curve_GF2m (const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
EC_GROUP * EC_GROUP_new_by_curve_name (int nid)
EC_GROUP * EC_GROUP_new_from_ecparameters (const ECPARAMETERS *params)
ECPARAMETERS * EC_GROUP_get_ecparameters (const EC_GROUP *group, ECPARAMETERS *params)
EC_GROUP * EC_GROUP_new_from_ecpkparameters (const ECPKPARAMETERS *params)
ECPKPARAMETERS * EC_GROUP_get_ecpkparameters (const EC_GROUP *group, ECPKPARAMETERS *params)
size_t EC_get_builtin_curves (EC_builtin_curve *r, size_t nitems)
const char * EC_curve_nid2nist (int nid)
int EC_curve_nist2nid (const char *name)
EC_POINT * EC_POINT_new (const EC_GROUP *group)
void EC_POINT_free (EC_POINT *point)
void EC_POINT_clear_free (EC_POINT *point)
int EC_POINT_copy (EC_POINT *dst, const EC_POINT *src)
EC_POINT * EC_POINT_dup (const EC_POINT *src, const EC_GROUP *group)
const EC_METHOD * EC_POINT_method_of (const EC_POINT *point)
int EC_POINT_set_to_infinity (const EC_GROUP *group, EC_POINT *point)
int EC_POINT_set_Jprojective_coordinates_GFp (const EC_GROUP *group, EC_POINT *p, const BIGNUM *x, const BIGNUM *y, const BIGNUM *z, BN_CTX *ctx)
int EC_POINT_get_Jprojective_coordinates_GFp (const EC_GROUP *group, const EC_POINT *p, BIGNUM *x, BIGNUM *y, BIGNUM *z, BN_CTX *ctx)
int EC_POINT_set_affine_coordinates_GFp (const EC_GROUP *group, EC_POINT *p, const BIGNUM *x, const BIGNUM *y, BN_CTX *ctx)
int EC_POINT_get_affine_coordinates_GFp (const EC_GROUP *group, const EC_POINT *p, BIGNUM *x, BIGNUM *y, BN_CTX *ctx)
int EC_POINT_set_compressed_coordinates_GFp (const EC_GROUP *group, EC_POINT *p, const BIGNUM *x, int y_bit, BN_CTX *ctx)
int EC_POINT_set_affine_coordinates_GF2m (const EC_GROUP *group, EC_POINT *p, const BIGNUM *x, const BIGNUM *y, BN_CTX *ctx)
int EC_POINT_get_affine_coordinates_GF2m (const EC_GROUP *group, const EC_POINT *p, BIGNUM *x, BIGNUM *y, BN_CTX *ctx)
int EC_POINT_set_compressed_coordinates_GF2m (const EC_GROUP *group, EC_POINT *p, const BIGNUM *x, int y_bit, BN_CTX *ctx)
size_t EC_POINT_point2oct (const EC_GROUP *group, const EC_POINT *p, point_conversion_form_t form, unsigned char *buf, size_t len, BN_CTX *ctx)
int EC_POINT_oct2point (const EC_GROUP *group, EC_POINT *p, const unsigned char *buf, size_t len, BN_CTX *ctx)
size_t EC_POINT_point2buf (const EC_GROUP *group, const EC_POINT *point, point_conversion_form_t form, unsigned char **pbuf, BN_CTX *ctx)
BIGNUM * EC_POINT_point2bn (const EC_GROUP *, const EC_POINT *, point_conversion_form_t form, BIGNUM *, BN_CTX *)
EC_POINT * EC_POINT_bn2point (const EC_GROUP *, const BIGNUM *, EC_POINT *, BN_CTX *)
char * EC_POINT_point2hex (const EC_GROUP *, const EC_POINT *, point_conversion_form_t form, BN_CTX *)
EC_POINT * EC_POINT_hex2point (const EC_GROUP *, const char *, EC_POINT *, BN_CTX *)
int EC_POINT_add (const EC_GROUP *group, EC_POINT *r, const EC_POINT *a, const EC_POINT *b, BN_CTX *ctx)
int EC_POINT_dbl (const EC_GROUP *group, EC_POINT *r, const EC_POINT *a, BN_CTX *ctx)
int EC_POINT_invert (const EC_GROUP *group, EC_POINT *a, BN_CTX *ctx)
int EC_POINT_is_at_infinity (const EC_GROUP *group, const EC_POINT *p)
int EC_POINT_is_on_curve (const EC_GROUP *group, const EC_POINT *point, BN_CTX *ctx)
int EC_POINT_cmp (const EC_GROUP *group, const EC_POINT *a, const EC_POINT *b, BN_CTX *ctx)
int EC_POINT_make_affine (const EC_GROUP *group, EC_POINT *point, BN_CTX *ctx)
int EC_POINTs_make_affine (const EC_GROUP *group, size_t num, EC_POINT *points[], BN_CTX *ctx)
int EC_POINTs_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *n, size_t num, const EC_POINT *p[], const BIGNUM *m[], BN_CTX *ctx)
int EC_POINT_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *n, const EC_POINT *q, const BIGNUM *m, BN_CTX *ctx)
int EC_GROUP_precompute_mult (EC_GROUP *group, BN_CTX *ctx)
int EC_GROUP_have_precompute_mult (const EC_GROUP *group)
int EC_GROUP_get_basis_type (const EC_GROUP *)
int EC_GROUP_get_trinomial_basis (const EC_GROUP *, unsigned int *k)
int EC_GROUP_get_pentanomial_basis (const EC_GROUP *, unsigned int *k1, unsigned int *k2, unsigned int *k3)
EC_GROUP * d2i_ECPKParameters (EC_GROUP **, const unsigned char **in, long len)
int i2d_ECPKParameters (const EC_GROUP *, unsigned char **out)
int ECPKParameters_print (BIO *bp, const EC_GROUP *x, int off)
int ECPKParameters_print_fp (FILE *fp, const EC_GROUP *x, int off)
EC_KEY * EC_KEY_new (void)
int EC_KEY_get_flags (const EC_KEY *key)
void EC_KEY_set_flags (EC_KEY *key, int flags)
void EC_KEY_clear_flags (EC_KEY *key, int flags)
EC_KEY * EC_KEY_new_by_curve_name (int nid)
void EC_KEY_free (EC_KEY *key)
EC_KEY * EC_KEY_copy (EC_KEY *dst, const EC_KEY *src)
EC_KEY * EC_KEY_dup (const EC_KEY *src)
int EC_KEY_up_ref (EC_KEY *key)
const EC_GROUP * EC_KEY_get0_group (const EC_KEY *key)
int EC_KEY_set_group (EC_KEY *key, const EC_GROUP *group)
const BIGNUM * EC_KEY_get0_private_key (const EC_KEY *key)
int EC_KEY_set_private_key (EC_KEY *key, const BIGNUM *prv)
const EC_POINT * EC_KEY_get0_public_key (const EC_KEY *key)
int EC_KEY_set_public_key (EC_KEY *key, const EC_POINT *pub)
unsigned EC_KEY_get_enc_flags (const EC_KEY *key)
void EC_KEY_set_enc_flags (EC_KEY *eckey, unsigned int flags)
point_conversion_form_t EC_KEY_get_conv_form (const EC_KEY *key)
void EC_KEY_set_conv_form (EC_KEY *eckey, point_conversion_form_t cform)
int EC_KEY_set_ex_data (EC_KEY *key, int idx, void *arg)
void * EC_KEY_get_ex_data (const EC_KEY *key, int idx)
void EC_KEY_set_asn1_flag (EC_KEY *eckey, int asn1_flag)
int EC_KEY_precompute_mult (EC_KEY *key, BN_CTX *ctx)
int EC_KEY_generate_key (EC_KEY *key)
int EC_KEY_check_key (const EC_KEY *key)
int EC_KEY_can_sign (const EC_KEY *eckey)
int EC_KEY_set_public_key_affine_coordinates (EC_KEY *key, BIGNUM *x, BIGNUM *y)
size_t EC_KEY_key2buf (const EC_KEY *key, point_conversion_form_t form, unsigned char **pbuf, BN_CTX *ctx)
int EC_KEY_oct2key (EC_KEY *key, const unsigned char *buf, size_t len, BN_CTX *ctx)
int EC_KEY_oct2priv (EC_KEY *key, const unsigned char *buf, size_t len)
size_t EC_KEY_priv2oct (const EC_KEY *key, unsigned char *buf, size_t len)
size_t EC_KEY_priv2buf (const EC_KEY *eckey, unsigned char **pbuf)
EC_KEY * d2i_ECPrivateKey (EC_KEY **key, const unsigned char **in, long len)
int i2d_ECPrivateKey (EC_KEY *key, unsigned char **out)
EC_KEY * d2i_ECParameters (EC_KEY **key, const unsigned char **in, long len)
int i2d_ECParameters (EC_KEY *key, unsigned char **out)
EC_KEY * o2i_ECPublicKey (EC_KEY **key, const unsigned char **in, long len)
int i2o_ECPublicKey (const EC_KEY *key, unsigned char **out)
int ECParameters_print (BIO *bp, const EC_KEY *key)
int EC_KEY_print (BIO *bp, const EC_KEY *key, int off)
int ECParameters_print_fp (FILE *fp, const EC_KEY *key)
int EC_KEY_print_fp (FILE *fp, const EC_KEY *key, int off)
const EC_KEY_METHOD * EC_KEY_OpenSSL (void)
const EC_KEY_METHOD * EC_KEY_get_default_method (void)
void EC_KEY_set_default_method (const EC_KEY_METHOD *meth)
const EC_KEY_METHOD * EC_KEY_get_method (const EC_KEY *key)
int EC_KEY_set_method (EC_KEY *key, const EC_KEY_METHOD *meth)
EC_KEY * EC_KEY_new_method (ENGINE *engine)
int ECDH_KDF_X9_62 (unsigned char *out, size_t outlen, const unsigned char *Z, size_t Zlen, const unsigned char *sinfo, size_t sinfolen, const EVP_MD *md)
int ECDH_compute_key (void *out, size_t outlen, const EC_POINT *pub_key, const EC_KEY *ecdh, void *(*KDF)(const void *in, size_t inlen, void *out, size_t *outlen))
ECDSA_SIG * ECDSA_SIG_new (void)
void ECDSA_SIG_free (ECDSA_SIG *sig)
int i2d_ECDSA_SIG (const ECDSA_SIG *sig, unsigned char **pp)
ECDSA_SIG * d2i_ECDSA_SIG (ECDSA_SIG **sig, const unsigned char **pp, long len)
void ECDSA_SIG_get0 (const ECDSA_SIG *sig, const BIGNUM **pr, const BIGNUM **ps)
int ECDSA_SIG_set0 (ECDSA_SIG *sig, BIGNUM *r, BIGNUM *s)
ECDSA_SIG * ECDSA_do_sign (const unsigned char *dgst, int dgst_len, EC_KEY *eckey)
ECDSA_SIG * ECDSA_do_sign_ex (const unsigned char *dgst, int dgstlen, const BIGNUM *kinv, const BIGNUM *rp, EC_KEY *eckey)
int ECDSA_do_verify (const unsigned char *dgst, int dgst_len, const ECDSA_SIG *sig, EC_KEY *eckey)
int ECDSA_sign_setup (EC_KEY *eckey, BN_CTX *ctx, BIGNUM **kinv, BIGNUM **rp)
int ECDSA_sign (int type, const unsigned char *dgst, int dgstlen, unsigned char *sig, unsigned int *siglen, EC_KEY *eckey)
int ECDSA_sign_ex (int type, const unsigned char *dgst, int dgstlen, unsigned char *sig, unsigned int *siglen, const BIGNUM *kinv, const BIGNUM *rp, EC_KEY *eckey)
int ECDSA_verify (int type, const unsigned char *dgst, int dgstlen, const unsigned char *sig, int siglen, EC_KEY *eckey)
int ECDSA_size (const EC_KEY *eckey)
EC_KEY_METHOD * EC_KEY_METHOD_new (const EC_KEY_METHOD *meth)
void EC_KEY_METHOD_free (EC_KEY_METHOD *meth)
void EC_KEY_METHOD_set_init (EC_KEY_METHOD *meth, int(*init)(EC_KEY *key), void(*finish)(EC_KEY *key), int(*copy)(EC_KEY *dest, const EC_KEY *src), int(*set_group)(EC_KEY *key, const EC_GROUP *grp), int(*set_private)(EC_KEY *key, const BIGNUM *priv_key), int(*set_public)(EC_KEY *key, const EC_POINT *pub_key))
void EC_KEY_METHOD_set_keygen (EC_KEY_METHOD *meth, int(*keygen)(EC_KEY *key))
void EC_KEY_METHOD_set_compute_key (EC_KEY_METHOD *meth, int(*ckey)(unsigned char **psec, size_t *pseclen, const EC_POINT *pub_key, const EC_KEY *ecdh))
void EC_KEY_METHOD_set_sign (EC_KEY_METHOD *meth, int(*sign)(int type, const unsigned char *dgst, int dlen, unsigned char *sig, unsigned int *siglen, const BIGNUM *kinv, const BIGNUM *r, EC_KEY *eckey), int(*sign_setup)(EC_KEY *eckey, BN_CTX *ctx_in, BIGNUM **kinvp, BIGNUM **rp), ECDSA_SIG *(*sign_sig)(const unsigned char *dgst, int dgst_len, const BIGNUM *in_kinv, const BIGNUM *in_r, EC_KEY *eckey))
void EC_KEY_METHOD_set_verify (EC_KEY_METHOD *meth, int(*verify)(int type, const unsigned char *dgst, int dgst_len, const unsigned char *sigbuf, int sig_len, EC_KEY *eckey), int(*verify_sig)(const unsigned char *dgst, int dgst_len, const ECDSA_SIG *sig, EC_KEY *eckey))
void EC_KEY_METHOD_get_init (EC_KEY_METHOD *meth, int(**pinit)(EC_KEY *key), void(**pfinish)(EC_KEY *key), int(**pcopy)(EC_KEY *dest, const EC_KEY *src), int(**pset_group)(EC_KEY *key, const EC_GROUP *grp), int(**pset_private)(EC_KEY *key, const BIGNUM *priv_key), int(**pset_public)(EC_KEY *key, const EC_POINT *pub_key))
void EC_KEY_METHOD_get_keygen (EC_KEY_METHOD *meth, int(**pkeygen)(EC_KEY *key))
void EC_KEY_METHOD_get_compute_key (EC_KEY_METHOD *meth, int(**pck)(unsigned char **psec, size_t *pseclen, const EC_POINT *pub_key, const EC_KEY *ecdh))
void EC_KEY_METHOD_get_sign (EC_KEY_METHOD *meth, int(**psign)(int type, const unsigned char *dgst, int dlen, unsigned char *sig, unsigned int *siglen, const BIGNUM *kinv, const BIGNUM *r, EC_KEY *eckey), int(**psign_setup)(EC_KEY *eckey, BN_CTX *ctx_in, BIGNUM **kinvp, BIGNUM **rp), ECDSA_SIG *(**psign_sig)(const unsigned char *dgst, int dgst_len, const BIGNUM *in_kinv, const BIGNUM *in_r, EC_KEY *eckey))
void EC_KEY_METHOD_get_verify (EC_KEY_METHOD *meth, int(**pverify)(int type, const unsigned char *dgst, int dgst_len, const unsigned char *sigbuf, int sig_len, EC_KEY *eckey), int(**pverify_sig)(const unsigned char *dgst, int dgst_len, const ECDSA_SIG *sig, EC_KEY *eckey))
int ERR_load_EC_strings (void)
Macro Definition Documentation
d2i_ECPKParameters_bio
#define d2i_ECPKParameters_bio (bp, x) ASN1_d2i_bio_of(EC_GROUP,NULL,d2i_ECPKParameters,bp,x)
Definition at line 723 of file ec.h.
d2i_ECPKParameters_fp
#define d2i_ECPKParameters_fp (fp, x)
Value:
(EC_GROUP *)ASN1_d2i_fp(NULL, \
                (char *(*)())d2i_ECPKParameters,(fp),(unsigned char **)(x))
Definition at line 725 of file ec.h.
EC_F_BN_TO_FELEM
#define EC_F_BN_TO_FELEM 224
Definition at line 1370 of file ec.h.
EC_F_D2I_ECPARAMETERS
#define EC_F_D2I_ECPARAMETERS 144
Definition at line 1371 of file ec.h.
EC_F_D2I_ECPKPARAMETERS
#define EC_F_D2I_ECPKPARAMETERS 145
Definition at line 1372 of file ec.h.
Referenced by d2i_ECPKParameters().
EC_F_D2I_ECPRIVATEKEY
#define EC_F_D2I_ECPRIVATEKEY 146
Definition at line 1373 of file ec.h.
EC_F_DO_EC_KEY_PRINT
#define EC_F_DO_EC_KEY_PRINT 221
Definition at line 1374 of file ec.h.
EC_F_EC_ASN1_GROUP2CURVE
#define EC_F_EC_ASN1_GROUP2CURVE 153
Definition at line 1404 of file ec.h.
EC_F_EC_ASN1_GROUP2FIELDID
#define EC_F_EC_ASN1_GROUP2FIELDID 154
Definition at line 1405 of file ec.h.
EC_F_EC_GF2M_MONTGOMERY_POINT_MULTIPLY
#define EC_F_EC_GF2M_MONTGOMERY_POINT_MULTIPLY 208
Definition at line 1406 of file ec.h.
EC_F_EC_GF2M_SIMPLE_GROUP_CHECK_DISCRIMINANT
#define EC_F_EC_GF2M_SIMPLE_GROUP_CHECK_DISCRIMINANT 159
Definition at line 1407 of file ec.h.
EC_F_EC_GF2M_SIMPLE_GROUP_SET_CURVE
#define EC_F_EC_GF2M_SIMPLE_GROUP_SET_CURVE 195
Definition at line 1408 of file ec.h.
EC_F_EC_GF2M_SIMPLE_OCT2POINT
#define EC_F_EC_GF2M_SIMPLE_OCT2POINT 160
Definition at line 1409 of file ec.h.
EC_F_EC_GF2M_SIMPLE_POINT2OCT
#define EC_F_EC_GF2M_SIMPLE_POINT2OCT 161
Definition at line 1410 of file ec.h.
EC_F_EC_GF2M_SIMPLE_POINT_GET_AFFINE_COORDINATES
#define EC_F_EC_GF2M_SIMPLE_POINT_GET_AFFINE_COORDINATES 162
Definition at line 1411 of file ec.h.
EC_F_EC_GF2M_SIMPLE_POINT_SET_AFFINE_COORDINATES
#define EC_F_EC_GF2M_SIMPLE_POINT_SET_AFFINE_COORDINATES 163
Definition at line 1412 of file ec.h.
EC_F_EC_GF2M_SIMPLE_SET_COMPRESSED_COORDINATES
#define EC_F_EC_GF2M_SIMPLE_SET_COMPRESSED_COORDINATES 164
Definition at line 1413 of file ec.h.
EC_F_EC_GFP_MONT_FIELD_DECODE
#define EC_F_EC_GFP_MONT_FIELD_DECODE 133
Definition at line 1414 of file ec.h.
Referenced by ec_GFp_mont_field_decode().
EC_F_EC_GFP_MONT_FIELD_ENCODE
#define EC_F_EC_GFP_MONT_FIELD_ENCODE 134
Definition at line 1415 of file ec.h.
Referenced by ec_GFp_mont_field_encode().
EC_F_EC_GFP_MONT_FIELD_MUL
#define EC_F_EC_GFP_MONT_FIELD_MUL 131
Definition at line 1416 of file ec.h.
Referenced by ec_GFp_mont_field_mul().
EC_F_EC_GFP_MONT_FIELD_SET_TO_ONE
#define EC_F_EC_GFP_MONT_FIELD_SET_TO_ONE 209
Definition at line 1417 of file ec.h.
Referenced by ec_GFp_mont_field_set_to_one().
EC_F_EC_GFP_MONT_FIELD_SQR
#define EC_F_EC_GFP_MONT_FIELD_SQR 132
Definition at line 1418 of file ec.h.
Referenced by ec_GFp_mont_field_sqr().
EC_F_EC_GFP_MONT_GROUP_SET_CURVE
#define EC_F_EC_GFP_MONT_GROUP_SET_CURVE 189
Definition at line 1419 of file ec.h.
EC_F_EC_GFP_NIST_FIELD_MUL
#define EC_F_EC_GFP_NIST_FIELD_MUL 200
Definition at line 1429 of file ec.h.
EC_F_EC_GFP_NIST_FIELD_SQR
#define EC_F_EC_GFP_NIST_FIELD_SQR 201
Definition at line 1430 of file ec.h.
EC_F_EC_GFP_NIST_GROUP_SET_CURVE
#define EC_F_EC_GFP_NIST_GROUP_SET_CURVE 202
Definition at line 1431 of file ec.h.
EC_F_EC_GFP_NISTP224_GROUP_SET_CURVE
#define EC_F_EC_GFP_NISTP224_GROUP_SET_CURVE 225
Definition at line 1420 of file ec.h.
EC_F_EC_GFP_NISTP224_POINT_GET_AFFINE_COORDINATES
#define EC_F_EC_GFP_NISTP224_POINT_GET_AFFINE_COORDINATES 226
Definition at line 1422 of file ec.h.
Referenced by ec_GFp_nistp224_point_get_affine_coordinates().
EC_F_EC_GFP_NISTP224_POINTS_MUL
#define EC_F_EC_GFP_NISTP224_POINTS_MUL 228
Definition at line 1421 of file ec.h.
EC_F_EC_GFP_NISTP256_GROUP_SET_CURVE
#define EC_F_EC_GFP_NISTP256_GROUP_SET_CURVE 230
Definition at line 1423 of file ec.h.
EC_F_EC_GFP_NISTP256_POINT_GET_AFFINE_COORDINATES
#define EC_F_EC_GFP_NISTP256_POINT_GET_AFFINE_COORDINATES 232
Definition at line 1425 of file ec.h.
Referenced by ec_GFp_nistp256_point_get_affine_coordinates().
EC_F_EC_GFP_NISTP256_POINTS_MUL
#define EC_F_EC_GFP_NISTP256_POINTS_MUL 231
Definition at line 1424 of file ec.h.
EC_F_EC_GFP_NISTP521_GROUP_SET_CURVE
#define EC_F_EC_GFP_NISTP521_GROUP_SET_CURVE 233
Definition at line 1426 of file ec.h.
EC_F_EC_GFP_NISTP521_POINT_GET_AFFINE_COORDINATES
#define EC_F_EC_GFP_NISTP521_POINT_GET_AFFINE_COORDINATES 235
Definition at line 1428 of file ec.h.
Referenced by ec_GFp_nistp521_point_get_affine_coordinates().
EC_F_EC_GFP_NISTP521_POINTS_MUL
#define EC_F_EC_GFP_NISTP521_POINTS_MUL 234
Definition at line 1427 of file ec.h.
EC_F_EC_GFP_SIMPLE_GROUP_CHECK_DISCRIMINANT
#define EC_F_EC_GFP_SIMPLE_GROUP_CHECK_DISCRIMINANT 165
Definition at line 1432 of file ec.h.
EC_F_EC_GFP_SIMPLE_GROUP_SET_CURVE
#define EC_F_EC_GFP_SIMPLE_GROUP_SET_CURVE 166
Definition at line 1433 of file ec.h.
EC_F_EC_GFP_SIMPLE_MAKE_AFFINE
#define EC_F_EC_GFP_SIMPLE_MAKE_AFFINE 102
Definition at line 1434 of file ec.h.
EC_F_EC_GFP_SIMPLE_OCT2POINT
#define EC_F_EC_GFP_SIMPLE_OCT2POINT 103
Definition at line 1435 of file ec.h.
EC_F_EC_GFP_SIMPLE_POINT2OCT
#define EC_F_EC_GFP_SIMPLE_POINT2OCT 104
Definition at line 1436 of file ec.h.
EC_F_EC_GFP_SIMPLE_POINT_GET_AFFINE_COORDINATES
#define EC_F_EC_GFP_SIMPLE_POINT_GET_AFFINE_COORDINATES 167
Definition at line 1438 of file ec.h.
EC_F_EC_GFP_SIMPLE_POINT_SET_AFFINE_COORDINATES
#define EC_F_EC_GFP_SIMPLE_POINT_SET_AFFINE_COORDINATES 168
Definition at line 1439 of file ec.h.
Referenced by ec_GFp_simple_point_set_affine_coordinates().
EC_F_EC_GFP_SIMPLE_POINTS_MAKE_AFFINE
#define EC_F_EC_GFP_SIMPLE_POINTS_MAKE_AFFINE 137
Definition at line 1437 of file ec.h.
EC_F_EC_GFP_SIMPLE_SET_COMPRESSED_COORDINATES
#define EC_F_EC_GFP_SIMPLE_SET_COMPRESSED_COORDINATES 169
Definition at line 1440 of file ec.h.
EC_F_EC_GROUP_CHECK
#define EC_F_EC_GROUP_CHECK 170
Definition at line 1441 of file ec.h.
EC_F_EC_GROUP_CHECK_DISCRIMINANT
#define EC_F_EC_GROUP_CHECK_DISCRIMINANT 171
Definition at line 1442 of file ec.h.
Referenced by EC_GROUP_check_discriminant().
EC_F_EC_GROUP_COPY
#define EC_F_EC_GROUP_COPY 106
Definition at line 1443 of file ec.h.
Referenced by EC_GROUP_copy().
EC_F_EC_GROUP_GET_CURVE_GF2M
#define EC_F_EC_GROUP_GET_CURVE_GF2M 172
Definition at line 1444 of file ec.h.
Referenced by EC_GROUP_get_curve_GF2m().
EC_F_EC_GROUP_GET_CURVE_GFP
#define EC_F_EC_GROUP_GET_CURVE_GFP 130
Definition at line 1445 of file ec.h.
Referenced by EC_GROUP_get_curve_GFp().
EC_F_EC_GROUP_GET_DEGREE
#define EC_F_EC_GROUP_GET_DEGREE 173
Definition at line 1446 of file ec.h.
Referenced by EC_GROUP_get_degree().
EC_F_EC_GROUP_GET_ECPARAMETERS
#define EC_F_EC_GROUP_GET_ECPARAMETERS 261
Definition at line 1447 of file ec.h.
EC_F_EC_GROUP_GET_ECPKPARAMETERS
#define EC_F_EC_GROUP_GET_ECPKPARAMETERS 262
Definition at line 1448 of file ec.h.
EC_F_EC_GROUP_GET_PENTANOMIAL_BASIS
#define EC_F_EC_GROUP_GET_PENTANOMIAL_BASIS 193
Definition at line 1449 of file ec.h.
Referenced by EC_GROUP_get_pentanomial_basis().
EC_F_EC_GROUP_GET_TRINOMIAL_BASIS
#define EC_F_EC_GROUP_GET_TRINOMIAL_BASIS 194
Definition at line 1450 of file ec.h.
EC_F_EC_GROUP_NEW
#define EC_F_EC_GROUP_NEW 108
Definition at line 1451 of file ec.h.
EC_F_EC_GROUP_NEW_BY_CURVE_NAME
#define EC_F_EC_GROUP_NEW_BY_CURVE_NAME 174
Definition at line 1452 of file ec.h.
EC_F_EC_GROUP_NEW_FROM_DATA
#define EC_F_EC_GROUP_NEW_FROM_DATA 175
Definition at line 1453 of file ec.h.
EC_F_EC_GROUP_NEW_FROM_ECPARAMETERS
#define EC_F_EC_GROUP_NEW_FROM_ECPARAMETERS 263
Definition at line 1454 of file ec.h.
EC_F_EC_GROUP_NEW_FROM_ECPKPARAMETERS
#define EC_F_EC_GROUP_NEW_FROM_ECPKPARAMETERS 264
Definition at line 1455 of file ec.h.
EC_F_EC_GROUP_SET_CURVE_GF2M
#define EC_F_EC_GROUP_SET_CURVE_GF2M 176
Definition at line 1456 of file ec.h.
Referenced by EC_GROUP_set_curve_GF2m().
EC_F_EC_GROUP_SET_CURVE_GFP
#define EC_F_EC_GROUP_SET_CURVE_GFP 109
Definition at line 1457 of file ec.h.
Referenced by EC_GROUP_set_curve_GFp().
EC_F_EC_GROUP_SET_GENERATOR
#define EC_F_EC_GROUP_SET_GENERATOR 111
Definition at line 1458 of file ec.h.
EC_F_EC_KEY_CHECK_KEY
#define EC_F_EC_KEY_CHECK_KEY 177
Definition at line 1459 of file ec.h.
Referenced by EC_KEY_check_key().
EC_F_EC_KEY_COPY
#define EC_F_EC_KEY_COPY 178
Definition at line 1460 of file ec.h.
Referenced by EC_KEY_copy().
EC_F_EC_KEY_GENERATE_KEY
#define EC_F_EC_KEY_GENERATE_KEY 179
Definition at line 1461 of file ec.h.
Referenced by EC_KEY_generate_key().
EC_F_EC_KEY_NEW
#define EC_F_EC_KEY_NEW 182
Definition at line 1462 of file ec.h.
EC_F_EC_KEY_NEW_METHOD
#define EC_F_EC_KEY_NEW_METHOD 245
Definition at line 1463 of file ec.h.
EC_F_EC_KEY_OCT2PRIV
#define EC_F_EC_KEY_OCT2PRIV 255
Definition at line 1464 of file ec.h.
EC_F_EC_KEY_PRINT
#define EC_F_EC_KEY_PRINT 180
Definition at line 1465 of file ec.h.
EC_F_EC_KEY_PRINT_FP
#define EC_F_EC_KEY_PRINT_FP 181
Definition at line 1466 of file ec.h.
EC_F_EC_KEY_PRIV2OCT
#define EC_F_EC_KEY_PRIV2OCT 256
Definition at line 1467 of file ec.h.
EC_F_EC_KEY_SET_PUBLIC_KEY_AFFINE_COORDINATES
#define EC_F_EC_KEY_SET_PUBLIC_KEY_AFFINE_COORDINATES 229
Definition at line 1468 of file ec.h.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_F_EC_KEY_SIMPLE_CHECK_KEY
#define EC_F_EC_KEY_SIMPLE_CHECK_KEY 258
Definition at line 1469 of file ec.h.
EC_F_EC_KEY_SIMPLE_OCT2PRIV
#define EC_F_EC_KEY_SIMPLE_OCT2PRIV 259
Definition at line 1470 of file ec.h.
EC_F_EC_KEY_SIMPLE_PRIV2OCT
#define EC_F_EC_KEY_SIMPLE_PRIV2OCT 260
Definition at line 1471 of file ec.h.
EC_F_EC_POINT_ADD
#define EC_F_EC_POINT_ADD 112
Definition at line 1473 of file ec.h.
Referenced by EC_POINT_add().
EC_F_EC_POINT_CMP
#define EC_F_EC_POINT_CMP 113
Definition at line 1474 of file ec.h.
Referenced by EC_POINT_cmp().
EC_F_EC_POINT_COPY
#define EC_F_EC_POINT_COPY 114
Definition at line 1475 of file ec.h.
Referenced by EC_POINT_copy().
EC_F_EC_POINT_DBL
#define EC_F_EC_POINT_DBL 115
Definition at line 1476 of file ec.h.
Referenced by EC_POINT_dbl().
EC_F_EC_POINT_GET_AFFINE_COORDINATES_GF2M
#define EC_F_EC_POINT_GET_AFFINE_COORDINATES_GF2M 183
Definition at line 1477 of file ec.h.
Referenced by EC_POINT_get_affine_coordinates_GF2m().
EC_F_EC_POINT_GET_AFFINE_COORDINATES_GFP
#define EC_F_EC_POINT_GET_AFFINE_COORDINATES_GFP 116
Definition at line 1478 of file ec.h.
Referenced by EC_POINT_get_affine_coordinates_GFp().
EC_F_EC_POINT_GET_JPROJECTIVE_COORDINATES_GFP
#define EC_F_EC_POINT_GET_JPROJECTIVE_COORDINATES_GFP 117
Definition at line 1479 of file ec.h.
Referenced by EC_POINT_get_Jprojective_coordinates_GFp().
EC_F_EC_POINT_INVERT
#define EC_F_EC_POINT_INVERT 210
Definition at line 1480 of file ec.h.
Referenced by EC_POINT_invert().
EC_F_EC_POINT_IS_AT_INFINITY
#define EC_F_EC_POINT_IS_AT_INFINITY 118
Definition at line 1481 of file ec.h.
Referenced by EC_POINT_is_at_infinity().
EC_F_EC_POINT_IS_ON_CURVE
#define EC_F_EC_POINT_IS_ON_CURVE 119
Definition at line 1482 of file ec.h.
Referenced by EC_POINT_is_on_curve().
EC_F_EC_POINT_MAKE_AFFINE
#define EC_F_EC_POINT_MAKE_AFFINE 120
Definition at line 1483 of file ec.h.
Referenced by EC_POINT_make_affine().
EC_F_EC_POINT_NEW
#define EC_F_EC_POINT_NEW 121
Definition at line 1484 of file ec.h.
EC_F_EC_POINT_OCT2POINT
#define EC_F_EC_POINT_OCT2POINT 122
Definition at line 1485 of file ec.h.
EC_F_EC_POINT_POINT2OCT
#define EC_F_EC_POINT_POINT2OCT 123
Definition at line 1486 of file ec.h.
EC_F_EC_POINT_SET_AFFINE_COORDINATES_GF2M
#define EC_F_EC_POINT_SET_AFFINE_COORDINATES_GF2M 185
Definition at line 1487 of file ec.h.
Referenced by EC_POINT_set_affine_coordinates_GF2m().
EC_F_EC_POINT_SET_AFFINE_COORDINATES_GFP
#define EC_F_EC_POINT_SET_AFFINE_COORDINATES_GFP 124
Definition at line 1488 of file ec.h.
Referenced by EC_POINT_set_affine_coordinates_GFp().
EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GF2M
#define EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GF2M 186
Definition at line 1489 of file ec.h.
Referenced by EC_POINT_set_compressed_coordinates_GF2m().
EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GFP
#define EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GFP 125
Definition at line 1490 of file ec.h.
Referenced by EC_POINT_set_compressed_coordinates_GFp().
EC_F_EC_POINT_SET_JPROJECTIVE_COORDINATES_GFP
#define EC_F_EC_POINT_SET_JPROJECTIVE_COORDINATES_GFP 126
Definition at line 1491 of file ec.h.
Referenced by EC_POINT_set_Jprojective_coordinates_GFp().
EC_F_EC_POINT_SET_TO_INFINITY
#define EC_F_EC_POINT_SET_TO_INFINITY 127
Definition at line 1492 of file ec.h.
Referenced by EC_POINT_set_to_infinity().
EC_F_EC_POINTS_MAKE_AFFINE
#define EC_F_EC_POINTS_MAKE_AFFINE 136
Definition at line 1472 of file ec.h.
Referenced by EC_POINTs_make_affine().
EC_F_EC_PRE_COMP_NEW
#define EC_F_EC_PRE_COMP_NEW 196
Definition at line 1493 of file ec.h.
EC_F_EC_WNAF_MUL
#define EC_F_EC_WNAF_MUL 187
Definition at line 1494 of file ec.h.
EC_F_EC_WNAF_PRECOMPUTE_MULT
#define EC_F_EC_WNAF_PRECOMPUTE_MULT 188
Definition at line 1495 of file ec.h.
EC_F_ECDH_CMS_DECRYPT
#define EC_F_ECDH_CMS_DECRYPT 238
Definition at line 1375 of file ec.h.
EC_F_ECDH_CMS_SET_SHARED_INFO
#define EC_F_ECDH_CMS_SET_SHARED_INFO 239
Definition at line 1376 of file ec.h.
EC_F_ECDH_COMPUTE_KEY
#define EC_F_ECDH_COMPUTE_KEY 246
Definition at line 1377 of file ec.h.
EC_F_ECDH_SIMPLE_COMPUTE_KEY
#define EC_F_ECDH_SIMPLE_COMPUTE_KEY 257
Definition at line 1378 of file ec.h.
EC_F_ECDSA_DO_SIGN_EX
#define EC_F_ECDSA_DO_SIGN_EX 251
Definition at line 1379 of file ec.h.
Referenced by ECDSA_do_sign_ex().
EC_F_ECDSA_DO_VERIFY
#define EC_F_ECDSA_DO_VERIFY 252
Definition at line 1380 of file ec.h.
Referenced by ECDSA_do_verify().
EC_F_ECDSA_SIG_NEW
#define EC_F_ECDSA_SIG_NEW 265
Definition at line 1383 of file ec.h.
EC_F_ECDSA_SIGN_EX
#define EC_F_ECDSA_SIGN_EX 254
Definition at line 1381 of file ec.h.
Referenced by ECDSA_sign_ex().
EC_F_ECDSA_SIGN_SETUP
#define EC_F_ECDSA_SIGN_SETUP 248
Definition at line 1382 of file ec.h.
Referenced by ECDSA_sign_setup().
EC_F_ECDSA_VERIFY
#define EC_F_ECDSA_VERIFY 253
Definition at line 1384 of file ec.h.
Referenced by ECDSA_verify().
EC_F_ECKEY_PARAM2TYPE
#define EC_F_ECKEY_PARAM2TYPE 223
Definition at line 1385 of file ec.h.
EC_F_ECKEY_PARAM_DECODE
#define EC_F_ECKEY_PARAM_DECODE 212
Definition at line 1386 of file ec.h.
EC_F_ECKEY_PRIV_DECODE
#define EC_F_ECKEY_PRIV_DECODE 213
Definition at line 1387 of file ec.h.
EC_F_ECKEY_PRIV_ENCODE
#define EC_F_ECKEY_PRIV_ENCODE 214
Definition at line 1388 of file ec.h.
EC_F_ECKEY_PUB_DECODE
#define EC_F_ECKEY_PUB_DECODE 215
Definition at line 1389 of file ec.h.
EC_F_ECKEY_PUB_ENCODE
#define EC_F_ECKEY_PUB_ENCODE 216
Definition at line 1390 of file ec.h.
EC_F_ECKEY_TYPE2PARAM
#define EC_F_ECKEY_TYPE2PARAM 220
Definition at line 1391 of file ec.h.
EC_F_ECP_NISTZ256_GET_AFFINE
#define EC_F_ECP_NISTZ256_GET_AFFINE 240
Definition at line 1396 of file ec.h.
EC_F_ECP_NISTZ256_MULT_PRECOMPUTE
#define EC_F_ECP_NISTZ256_MULT_PRECOMPUTE 243
Definition at line 1397 of file ec.h.
EC_F_ECP_NISTZ256_POINTS_MUL
#define EC_F_ECP_NISTZ256_POINTS_MUL 241
Definition at line 1398 of file ec.h.
EC_F_ECP_NISTZ256_PRE_COMP_NEW
#define EC_F_ECP_NISTZ256_PRE_COMP_NEW 244
Definition at line 1399 of file ec.h.
EC_F_ECP_NISTZ256_WINDOWED_MUL
#define EC_F_ECP_NISTZ256_WINDOWED_MUL 242
Definition at line 1400 of file ec.h.
EC_F_ECPARAMETERS_PRINT
#define EC_F_ECPARAMETERS_PRINT 147
Definition at line 1392 of file ec.h.
EC_F_ECPARAMETERS_PRINT_FP
#define EC_F_ECPARAMETERS_PRINT_FP 148
Definition at line 1393 of file ec.h.
EC_F_ECPKPARAMETERS_PRINT
#define EC_F_ECPKPARAMETERS_PRINT 149
Definition at line 1394 of file ec.h.
EC_F_ECPKPARAMETERS_PRINT_FP
#define EC_F_ECPKPARAMETERS_PRINT_FP 150
Definition at line 1395 of file ec.h.
EC_F_ECX_KEY_OP
#define EC_F_ECX_KEY_OP 266
Definition at line 1401 of file ec.h.
EC_F_ECX_PRIV_ENCODE
#define EC_F_ECX_PRIV_ENCODE 267
Definition at line 1402 of file ec.h.
EC_F_ECX_PUB_ENCODE
#define EC_F_ECX_PUB_ENCODE 268
Definition at line 1403 of file ec.h.
EC_F_I2D_ECPARAMETERS
#define EC_F_I2D_ECPARAMETERS 190
Definition at line 1496 of file ec.h.
EC_F_I2D_ECPKPARAMETERS
#define EC_F_I2D_ECPKPARAMETERS 191
Definition at line 1497 of file ec.h.
EC_F_I2D_ECPRIVATEKEY
#define EC_F_I2D_ECPRIVATEKEY 192
Definition at line 1498 of file ec.h.
EC_F_I2O_ECPUBLICKEY
#define EC_F_I2O_ECPUBLICKEY 151
Definition at line 1499 of file ec.h.
EC_F_NISTP224_PRE_COMP_NEW
#define EC_F_NISTP224_PRE_COMP_NEW 227
Definition at line 1500 of file ec.h.
EC_F_NISTP256_PRE_COMP_NEW
#define EC_F_NISTP256_PRE_COMP_NEW 236
Definition at line 1501 of file ec.h.
EC_F_NISTP521_PRE_COMP_NEW
#define EC_F_NISTP521_PRE_COMP_NEW 237
Definition at line 1502 of file ec.h.
EC_F_O2I_ECPUBLICKEY
#define EC_F_O2I_ECPUBLICKEY 152
Definition at line 1503 of file ec.h.
EC_F_OLD_EC_PRIV_DECODE
#define EC_F_OLD_EC_PRIV_DECODE 222
Definition at line 1504 of file ec.h.
EC_F_OSSL_ECDH_COMPUTE_KEY
#define EC_F_OSSL_ECDH_COMPUTE_KEY 247
Definition at line 1505 of file ec.h.
Referenced by ossl_ecdh_compute_key().
EC_F_OSSL_ECDSA_SIGN_SIG
#define EC_F_OSSL_ECDSA_SIGN_SIG 249
Definition at line 1506 of file ec.h.
EC_F_OSSL_ECDSA_VERIFY_SIG
#define EC_F_OSSL_ECDSA_VERIFY_SIG 250
Definition at line 1507 of file ec.h.
EC_F_PKEY_EC_CTRL
#define EC_F_PKEY_EC_CTRL 197
Definition at line 1509 of file ec.h.
EC_F_PKEY_EC_CTRL_STR
#define EC_F_PKEY_EC_CTRL_STR 198
Definition at line 1510 of file ec.h.
EC_F_PKEY_EC_DERIVE
#define EC_F_PKEY_EC_DERIVE 217
Definition at line 1511 of file ec.h.
EC_F_PKEY_EC_KEYGEN
#define EC_F_PKEY_EC_KEYGEN 199
Definition at line 1512 of file ec.h.
EC_F_PKEY_EC_PARAMGEN
#define EC_F_PKEY_EC_PARAMGEN 219
Definition at line 1513 of file ec.h.
EC_F_PKEY_EC_SIGN
#define EC_F_PKEY_EC_SIGN 218
Definition at line 1514 of file ec.h.
EC_F_PKEY_ECX_DERIVE
#define EC_F_PKEY_ECX_DERIVE 269
Definition at line 1508 of file ec.h.
EC_FLAG_COFACTOR_ECDH
#define EC_FLAG_COFACTOR_ECDH 0x1000
Definition at line 746 of file ec.h.
EC_FLAG_FIPS_CHECKED
#define EC_FLAG_FIPS_CHECKED 0x2
Definition at line 745 of file ec.h.
EC_FLAG_NON_FIPS_ALLOW
#define EC_FLAG_NON_FIPS_ALLOW 0x1
Definition at line 744 of file ec.h.
EC_KEY_get_ex_new_index
#define EC_KEY_get_ex_new_index (l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_EC_KEY, l, p, newf, dupf, freef)
Definition at line 837 of file ec.h.
EC_PKEY_NO_PARAMETERS
#define EC_PKEY_NO_PARAMETERS 0x001
Definition at line 740 of file ec.h.
EC_PKEY_NO_PUBKEY
#define EC_PKEY_NO_PUBKEY 0x002
Definition at line 741 of file ec.h.
EC_R_ASN1_ERROR
#define EC_R_ASN1_ERROR 115
Definition at line 1517 of file ec.h.
EC_R_BAD_SIGNATURE
#define EC_R_BAD_SIGNATURE 156
Definition at line 1518 of file ec.h.
EC_R_BIGNUM_OUT_OF_RANGE
#define EC_R_BIGNUM_OUT_OF_RANGE 144
Definition at line 1519 of file ec.h.
EC_R_BUFFER_TOO_SMALL
#define EC_R_BUFFER_TOO_SMALL 100
Definition at line 1520 of file ec.h.
EC_R_COORDINATES_OUT_OF_RANGE
#define EC_R_COORDINATES_OUT_OF_RANGE 146
Definition at line 1521 of file ec.h.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_R_CURVE_DOES_NOT_SUPPORT_ECDH
#define EC_R_CURVE_DOES_NOT_SUPPORT_ECDH 160
Definition at line 1522 of file ec.h.
Referenced by ossl_ecdh_compute_key().
EC_R_CURVE_DOES_NOT_SUPPORT_SIGNING
#define EC_R_CURVE_DOES_NOT_SUPPORT_SIGNING 159
Definition at line 1523 of file ec.h.
EC_R_D2I_ECPKPARAMETERS_FAILURE
#define EC_R_D2I_ECPKPARAMETERS_FAILURE 117
Definition at line 1524 of file ec.h.
Referenced by d2i_ECPKParameters().
EC_R_DECODE_ERROR
#define EC_R_DECODE_ERROR 142
Definition at line 1525 of file ec.h.
EC_R_DISCRIMINANT_IS_ZERO
#define EC_R_DISCRIMINANT_IS_ZERO 118
Definition at line 1526 of file ec.h.
EC_R_EC_GROUP_NEW_BY_NAME_FAILURE
#define EC_R_EC_GROUP_NEW_BY_NAME_FAILURE 119
Definition at line 1527 of file ec.h.
EC_R_FIELD_TOO_LARGE
#define EC_R_FIELD_TOO_LARGE 143
Definition at line 1528 of file ec.h.
EC_R_GF2M_NOT_SUPPORTED
#define EC_R_GF2M_NOT_SUPPORTED 147
Definition at line 1529 of file ec.h.
Referenced by EC_POINT_set_compressed_coordinates_GFp().
EC_R_GROUP2PKPARAMETERS_FAILURE
#define EC_R_GROUP2PKPARAMETERS_FAILURE 120
Definition at line 1530 of file ec.h.
EC_R_I2D_ECPKPARAMETERS_FAILURE
#define EC_R_I2D_ECPKPARAMETERS_FAILURE 121
Definition at line 1531 of file ec.h.
EC_R_INCOMPATIBLE_OBJECTS
#define EC_R_INCOMPATIBLE_OBJECTS 101
Definition at line 1532 of file ec.h.
Referenced by EC_GROUP_copy(), EC_POINT_add(), EC_POINT_cmp(), EC_POINT_copy(), EC_POINT_dbl(), EC_POINT_get_affine_coordinates_GF2m(), EC_POINT_get_affine_coordinates_GFp(), EC_POINT_get_Jprojective_coordinates_GFp(), EC_POINT_invert(), EC_POINT_is_at_infinity(), EC_POINT_is_on_curve(), EC_POINT_make_affine(), EC_POINT_set_affine_coordinates_GF2m(), EC_POINT_set_affine_coordinates_GFp(), EC_POINT_set_compressed_coordinates_GF2m(), EC_POINT_set_compressed_coordinates_GFp(), EC_POINT_set_Jprojective_coordinates_GFp(), EC_POINT_set_to_infinity(), and EC_POINTs_make_affine().
EC_R_INVALID_ARGUMENT
#define EC_R_INVALID_ARGUMENT 112
Definition at line 1533 of file ec.h.
EC_R_INVALID_COMPRESSED_POINT
#define EC_R_INVALID_COMPRESSED_POINT 110
Definition at line 1534 of file ec.h.
EC_R_INVALID_COMPRESSION_BIT
#define EC_R_INVALID_COMPRESSION_BIT 109
Definition at line 1535 of file ec.h.
EC_R_INVALID_CURVE
#define EC_R_INVALID_CURVE 141
Definition at line 1536 of file ec.h.
EC_R_INVALID_DIGEST
#define EC_R_INVALID_DIGEST 151
Definition at line 1537 of file ec.h.
EC_R_INVALID_DIGEST_TYPE
#define EC_R_INVALID_DIGEST_TYPE 138
Definition at line 1538 of file ec.h.
EC_R_INVALID_ENCODING
#define EC_R_INVALID_ENCODING 102
Definition at line 1539 of file ec.h.
EC_R_INVALID_FIELD
#define EC_R_INVALID_FIELD 103
Definition at line 1540 of file ec.h.
EC_R_INVALID_FORM
#define EC_R_INVALID_FORM 104
Definition at line 1541 of file ec.h.
EC_R_INVALID_GROUP_ORDER
#define EC_R_INVALID_GROUP_ORDER 122
Definition at line 1542 of file ec.h.
EC_R_INVALID_KEY
#define EC_R_INVALID_KEY 116
Definition at line 1543 of file ec.h.
EC_R_INVALID_OUTPUT_LENGTH
#define EC_R_INVALID_OUTPUT_LENGTH 161
Definition at line 1544 of file ec.h.
EC_R_INVALID_PEER_KEY
#define EC_R_INVALID_PEER_KEY 133
Definition at line 1545 of file ec.h.
EC_R_INVALID_PENTANOMIAL_BASIS
#define EC_R_INVALID_PENTANOMIAL_BASIS 132
Definition at line 1546 of file ec.h.
EC_R_INVALID_PRIVATE_KEY
#define EC_R_INVALID_PRIVATE_KEY 123
Definition at line 1547 of file ec.h.
EC_R_INVALID_TRINOMIAL_BASIS
#define EC_R_INVALID_TRINOMIAL_BASIS 137
Definition at line 1548 of file ec.h.
EC_R_KDF_PARAMETER_ERROR
#define EC_R_KDF_PARAMETER_ERROR 148
Definition at line 1549 of file ec.h.
EC_R_KEYS_NOT_SET
#define EC_R_KEYS_NOT_SET 140
Definition at line 1550 of file ec.h.
EC_R_MISSING_PARAMETERS
#define EC_R_MISSING_PARAMETERS 124
Definition at line 1551 of file ec.h.
Referenced by ssl3_ctx_ctrl().
EC_R_MISSING_PRIVATE_KEY
#define EC_R_MISSING_PRIVATE_KEY 125
Definition at line 1552 of file ec.h.
EC_R_NEED_NEW_SETUP_VALUES
#define EC_R_NEED_NEW_SETUP_VALUES 157
Definition at line 1553 of file ec.h.
EC_R_NO_PARAMETERS_SET
#define EC_R_NO_PARAMETERS_SET 139
Definition at line 1557 of file ec.h.
EC_R_NO_PRIVATE_VALUE
#define EC_R_NO_PRIVATE_VALUE 154
Definition at line 1558 of file ec.h.
EC_R_NOT_A_NIST_PRIME
#define EC_R_NOT_A_NIST_PRIME 135
Definition at line 1554 of file ec.h.
EC_R_NOT_IMPLEMENTED
#define EC_R_NOT_IMPLEMENTED 126
Definition at line 1555 of file ec.h.
EC_R_NOT_INITIALIZED
#define EC_R_NOT_INITIALIZED 111
Definition at line 1556 of file ec.h.
Referenced by ec_GFp_mont_field_decode(), ec_GFp_mont_field_encode(), ec_GFp_mont_field_mul(), ec_GFp_mont_field_set_to_one(), and ec_GFp_mont_field_sqr().
EC_R_OPERATION_NOT_SUPPORTED
#define EC_R_OPERATION_NOT_SUPPORTED 152
Definition at line 1559 of file ec.h.
Referenced by EC_KEY_generate_key(), ECDSA_do_sign_ex(), ECDSA_do_verify(), ECDSA_sign_ex(), ECDSA_sign_setup(), and ECDSA_verify().
EC_R_PASSED_NULL_PARAMETER
#define EC_R_PASSED_NULL_PARAMETER 134
Definition at line 1560 of file ec.h.
EC_R_PEER_KEY_ERROR
#define EC_R_PEER_KEY_ERROR 149
Definition at line 1561 of file ec.h.
EC_R_PKPARAMETERS2GROUP_FAILURE
#define EC_R_PKPARAMETERS2GROUP_FAILURE 127
Definition at line 1562 of file ec.h.
Referenced by d2i_ECPKParameters().
EC_R_POINT_ARITHMETIC_FAILURE
#define EC_R_POINT_ARITHMETIC_FAILURE 155
Definition at line 1563 of file ec.h.
EC_R_POINT_AT_INFINITY
#define EC_R_POINT_AT_INFINITY 106
Definition at line 1564 of file ec.h.
Referenced by ec_GFp_nistp224_point_get_affine_coordinates(), ec_GFp_nistp256_point_get_affine_coordinates(), and ec_GFp_nistp521_point_get_affine_coordinates().
EC_R_POINT_IS_NOT_ON_CURVE
#define EC_R_POINT_IS_NOT_ON_CURVE 107
Definition at line 1565 of file ec.h.
Referenced by EC_POINT_set_affine_coordinates_GF2m(), and EC_POINT_set_affine_coordinates_GFp().
EC_R_RANDOM_NUMBER_GENERATION_FAILED
#define EC_R_RANDOM_NUMBER_GENERATION_FAILED 158
Definition at line 1566 of file ec.h.
EC_R_SHARED_INFO_ERROR
#define EC_R_SHARED_INFO_ERROR 150
Definition at line 1567 of file ec.h.
EC_R_SLOT_FULL
#define EC_R_SLOT_FULL 108
Definition at line 1568 of file ec.h.
EC_R_UNDEFINED_GENERATOR
#define EC_R_UNDEFINED_GENERATOR 113
Definition at line 1569 of file ec.h.
EC_R_UNDEFINED_ORDER
#define EC_R_UNDEFINED_ORDER 128
Definition at line 1570 of file ec.h.
EC_R_UNKNOWN_GROUP
#define EC_R_UNKNOWN_GROUP 129
Definition at line 1571 of file ec.h.
EC_R_UNKNOWN_ORDER
#define EC_R_UNKNOWN_ORDER 114
Definition at line 1572 of file ec.h.
EC_R_UNSUPPORTED_FIELD
#define EC_R_UNSUPPORTED_FIELD 131
Definition at line 1573 of file ec.h.
EC_R_WRONG_CURVE_PARAMETERS
#define EC_R_WRONG_CURVE_PARAMETERS 145
Definition at line 1574 of file ec.h.
EC_R_WRONG_ORDER
#define EC_R_WRONG_ORDER 130
Definition at line 1575 of file ec.h.
ECParameters_dup
#define ECParameters_dup (x) ASN1_dup_of(EC_KEY,i2d_ECParameters,d2i_ECParameters,x)
Definition at line 1275 of file ec.h.
EVP_PKEY_CTRL_EC_ECDH_COFACTOR
#define EVP_PKEY_CTRL_EC_ECDH_COFACTOR (EVP_PKEY_ALG_CTRL + 3)
Definition at line 1347 of file ec.h.
EVP_PKEY_CTRL_EC_KDF_MD
#define EVP_PKEY_CTRL_EC_KDF_MD (EVP_PKEY_ALG_CTRL + 5)
Definition at line 1349 of file ec.h.
EVP_PKEY_CTRL_EC_KDF_OUTLEN
#define EVP_PKEY_CTRL_EC_KDF_OUTLEN (EVP_PKEY_ALG_CTRL + 7)
Definition at line 1351 of file ec.h.
EVP_PKEY_CTRL_EC_KDF_TYPE
#define EVP_PKEY_CTRL_EC_KDF_TYPE (EVP_PKEY_ALG_CTRL + 4)
Definition at line 1348 of file ec.h.
EVP_PKEY_CTRL_EC_KDF_UKM
#define EVP_PKEY_CTRL_EC_KDF_UKM (EVP_PKEY_ALG_CTRL + 9)
Definition at line 1353 of file ec.h.
EVP_PKEY_CTRL_EC_PARAM_ENC
#define EVP_PKEY_CTRL_EC_PARAM_ENC (EVP_PKEY_ALG_CTRL + 2)
Definition at line 1346 of file ec.h.
EVP_PKEY_CTRL_EC_PARAMGEN_CURVE_NID
#define EVP_PKEY_CTRL_EC_PARAMGEN_CURVE_NID (EVP_PKEY_ALG_CTRL + 1)
Definition at line 1345 of file ec.h.
EVP_PKEY_CTRL_GET_EC_KDF_MD
#define EVP_PKEY_CTRL_GET_EC_KDF_MD (EVP_PKEY_ALG_CTRL + 6)
Definition at line 1350 of file ec.h.
EVP_PKEY_CTRL_GET_EC_KDF_OUTLEN
#define EVP_PKEY_CTRL_GET_EC_KDF_OUTLEN (EVP_PKEY_ALG_CTRL + 8)
Definition at line 1352 of file ec.h.
EVP_PKEY_CTRL_GET_EC_KDF_UKM
#define EVP_PKEY_CTRL_GET_EC_KDF_UKM (EVP_PKEY_ALG_CTRL + 10)
Definition at line 1354 of file ec.h.
EVP_PKEY_CTX_get0_ecdh_kdf_ukm
#define EVP_PKEY_CTX_get0_ecdh_kdf_ukm (ctx, p)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_EC, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_GET_EC_KDF_UKM, 0, (void *)p)
Definition at line 1340 of file ec.h.
EVP_PKEY_CTX_get_ecdh_cofactor_mode
#define EVP_PKEY_CTX_get_ecdh_cofactor_mode (ctx)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_EC, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_EC_ECDH_COFACTOR, -2, NULL)
Definition at line 1300 of file ec.h.
EVP_PKEY_CTX_get_ecdh_kdf_md
#define EVP_PKEY_CTX_get_ecdh_kdf_md (ctx, pmd)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_EC, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_GET_EC_KDF_MD, 0, (void *)pmd)
Definition at line 1320 of file ec.h.
EVP_PKEY_CTX_get_ecdh_kdf_outlen
#define EVP_PKEY_CTX_get_ecdh_kdf_outlen (ctx, plen)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_EC, \
                                EVP_PKEY_OP_DERIVE, \
                        EVP_PKEY_CTRL_GET_EC_KDF_OUTLEN, 0, (void *)plen)
Definition at line 1330 of file ec.h.
EVP_PKEY_CTX_get_ecdh_kdf_type
#define EVP_PKEY_CTX_get_ecdh_kdf_type (ctx)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_EC, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_EC_KDF_TYPE, -2, NULL)
Definition at line 1310 of file ec.h.
EVP_PKEY_CTX_set0_ecdh_kdf_ukm
#define EVP_PKEY_CTX_set0_ecdh_kdf_ukm (ctx, p, plen)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_EC, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_EC_KDF_UKM, plen, (void *)p)
Definition at line 1335 of file ec.h.
EVP_PKEY_CTX_set_ec_param_enc
#define EVP_PKEY_CTX_set_ec_param_enc (ctx, flag)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_EC, \
                                EVP_PKEY_OP_PARAMGEN|EVP_PKEY_OP_KEYGEN, \
                                EVP_PKEY_CTRL_EC_PARAM_ENC, flag, NULL)
Definition at line 1290 of file ec.h.
EVP_PKEY_CTX_set_ec_paramgen_curve_nid
#define EVP_PKEY_CTX_set_ec_paramgen_curve_nid (ctx, nid)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_EC, \
                                EVP_PKEY_OP_PARAMGEN|EVP_PKEY_OP_KEYGEN, \
                                EVP_PKEY_CTRL_EC_PARAMGEN_CURVE_NID, nid, NULL)
Definition at line 1285 of file ec.h.
EVP_PKEY_CTX_set_ecdh_cofactor_mode
#define EVP_PKEY_CTX_set_ecdh_cofactor_mode (ctx, flag)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_EC, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_EC_ECDH_COFACTOR, flag, NULL)
Definition at line 1295 of file ec.h.
EVP_PKEY_CTX_set_ecdh_kdf_md
#define EVP_PKEY_CTX_set_ecdh_kdf_md (ctx, md)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_EC, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_EC_KDF_MD, 0, (void *)md)
Definition at line 1315 of file ec.h.
EVP_PKEY_CTX_set_ecdh_kdf_outlen
#define EVP_PKEY_CTX_set_ecdh_kdf_outlen (ctx, len)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_EC, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_EC_KDF_OUTLEN, len, NULL)
Definition at line 1325 of file ec.h.
EVP_PKEY_CTX_set_ecdh_kdf_type
#define EVP_PKEY_CTX_set_ecdh_kdf_type (ctx, kdf)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_EC, \
                                EVP_PKEY_OP_DERIVE, \
                                EVP_PKEY_CTRL_EC_KDF_TYPE, kdf, NULL)
Definition at line 1305 of file ec.h.
EVP_PKEY_ECDH_KDF_NONE
#define EVP_PKEY_ECDH_KDF_NONE 1
Definition at line 1356 of file ec.h.
EVP_PKEY_ECDH_KDF_X9_62
#define EVP_PKEY_ECDH_KDF_X9_62 2
Definition at line 1357 of file ec.h.
i2d_ECPKParameters_bio
#define i2d_ECPKParameters_bio (bp, x) ASN1_i2d_bio_of_const(EC_GROUP,i2d_ECPKParameters,bp,x)
Definition at line 724 of file ec.h.
i2d_ECPKParameters_fp
#define i2d_ECPKParameters_fp (fp, x)
Value:
ASN1_i2d_fp(i2d_ECPKParameters,(fp), \
                (unsigned char *)(x))
Definition at line 727 of file ec.h.
OPENSSL_EC_EXPLICIT_CURVE
#define OPENSSL_EC_EXPLICIT_CURVE 0x000
Definition at line 717 of file ec.h.
OPENSSL_EC_NAMED_CURVE
#define OPENSSL_EC_NAMED_CURVE 0x001
Definition at line 718 of file ec.h.
OPENSSL_ECC_MAX_FIELD_BITS
#define OPENSSL_ECC_MAX_FIELD_BITS 661
Definition at line 40 of file ec.h.
Enumeration Type Documentation
point_conversion_form_t
enum point_conversion_form_t
Enum for the point conversion form as defined in X9.62 (ECDSA) for the encoding of a elliptic curve point (x,y)
Enumerator
POINT_CONVERSION_COMPRESSED
the point is encoded as z||x, where the octet z specifies which solution of the quadratic equation y is
POINT_CONVERSION_UNCOMPRESSED
the point is encoded as z||x||y, where z is the octet 0x04
POINT_CONVERSION_HYBRID
the point is encoded as z||x||y, where the octet z specifies which solution of the quadratic equation y is
Definition at line 45 of file ec.h.
Function Documentation
d2i_ECDSA_SIG()
ECDSA_SIG* d2i_ECDSA_SIG (ECDSA_SIG ** sig, const unsigned char ** pp, long len)
Decodes a DER encoded ECDSA signature (note: this function changes *pp (*pp += len)).
Parameters
sig pointer to ECDSA_SIG pointer (may be NULL)
pp memory buffer with the DER encoded signature
len length of the buffer
Returns
pointer to the decoded ECDSA_SIG structure (or NULL)
d2i_ECParameters()
EC_KEY* d2i_ECParameters (EC_KEY ** key, const unsigned char ** in, long len)
Decodes ec parameter from a memory buffer.
Parameters
key a pointer to a EC_KEY object which should be used (or NULL)
in pointer to memory with the DER encoded ec parameters
len length of the DER encoded ec parameters
Returns
a EC_KEY object with the decoded parameters or NULL if an error occurred.
Definition at line 1075 of file ec_asn1.c.
d2i_ECPKParameters()
EC_GROUP* d2i_ECPKParameters (EC_GROUP ** , const unsigned char ** in, long len)
Definition at line 868 of file ec_asn1.c.
References EC_F_D2I_ECPKPARAMETERS, EC_GROUP_clear_free(), EC_GROUP_new_from_ecpkparameters(), EC_R_D2I_ECPKPARAMETERS_FAILURE, EC_R_PKPARAMETERS2GROUP_FAILURE, ECerr, in, and NULL.
d2i_ECPrivateKey()
EC_KEY* d2i_ECPrivateKey (EC_KEY ** key, const unsigned char ** in, long len)
Decodes a private key from a memory buffer.
Parameters
key a pointer to a EC_KEY object which should be used (or NULL)
in pointer to memory with the DER encoded private key
len length of the DER encoded private key
Returns
the decoded private key or NULL if an error occurred.
Definition at line 915 of file ec_asn1.c.
Referenced by d2i_ECPrivateKey_bio(), and d2i_ECPrivateKey_fp().
EC_curve_nid2nist()
const char* EC_curve_nid2nist (int nid)
Definition at line 3151 of file ec_curve.c.
References EC_NIST_NAME::name, NULL, and OSSL_NELEM.
Referenced by ssl_print_groups(), and ssl_print_tmp_key().
EC_curve_nist2nid()
int EC_curve_nist2nid (const char * name)
Definition at line 3161 of file ec_curve.c.
References nid, NID_undef, and OSSL_NELEM.
EC_get_builtin_curves()
size_t EC_get_builtin_curves (EC_builtin_curve * r, size_t nitems)
Definition at line 3109 of file ec_curve.c.
References EC_builtin_curve::comment, ec_list_element::comment, curve_list_length, min, EC_builtin_curve::nid, ec_list_element::nid, and NULL.
EC_GF2m_simple_method()
const EC_METHOD* EC_GF2m_simple_method (void)
Returns the basic GF2m ec method
Returns
EC_METHOD object
Definition at line 32 of file ec2_smpl.c.
EC_GFp_mont_method()
const EC_METHOD* EC_GFp_mont_method (void)
Returns GFp methods using montgomery multiplication.
Returns
EC_METHOD object
Definition at line 20 of file ecp_mont.c.
EC_GFp_nist_method()
const EC_METHOD* EC_GFp_nist_method (void)
Returns GFp methods using optimized methods for NIST recommended curves
Returns
EC_METHOD object
Definition at line 22 of file ecp_nist.c.
EC_GFp_nistp224_method()
const EC_METHOD* EC_GFp_nistp224_method (void)
Returns 64-bit optimized methods for nistp224
Returns
EC_METHOD object
Definition at line 243 of file ecp_nistp224.c.
EC_GFp_nistp256_method()
const EC_METHOD* EC_GFp_nistp256_method (void)
Returns 64-bit optimized methods for nistp256
Returns
EC_METHOD object
Definition at line 1772 of file ecp_nistp256.c.
EC_GFp_nistp521_method()
const EC_METHOD* EC_GFp_nistp521_method (void)
Returns 64-bit optimized methods for nistp521
Returns
EC_METHOD object
Definition at line 1601 of file ecp_nistp521.c.
EC_GFp_simple_method()
const EC_METHOD* EC_GFp_simple_method (void)
Returns the basic GFp ec methods which provides the basis for the optimized methods.
Returns
EC_METHOD object
Definition at line 21 of file ecp_smpl.c.
EC_GROUP_check()
int EC_GROUP_check (const EC_GROUP * group, BN_CTX * ctx)
Checks whether the parameter in the EC_GROUP define a valid ec group
Parameters
group EC_GROUP object
ctx BN_CTX object (optional)
Returns
1 if group is a valid ec group and 0 otherwise
Definition at line 13 of file ec_check.c.
EC_GROUP_check_discriminant()
int EC_GROUP_check_discriminant (const EC_GROUP * group, BN_CTX * ctx)
Checks whether the discriminant of the elliptic curve is zero or not
Parameters
group EC_GROUP object
ctx BN_CTX object (optional)
Returns
1 if the discriminant is not zero and 0 otherwise
Definition at line 471 of file ec_lib.c.
References EC_F_EC_GROUP_CHECK_DISCRIMINANT, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_GROUP_clear_free()
void EC_GROUP_clear_free (EC_GROUP * group)
Clears and frees a EC_GROUP object
Parameters
group EC_GROUP object to be cleared and freed.
Definition at line 116 of file ec_lib.c.
References BN_clear_free(), BN_MONT_CTX_free(), EC_POINT_clear_free(), EC_pre_comp_free(), and OPENSSL_clear_free.
Referenced by d2i_ECPKParameters().
EC_GROUP_cmp()
int EC_GROUP_cmp (const EC_GROUP * a, const EC_GROUP * b, BN_CTX * ctx)
Compares two EC_GROUP objects
Parameters
a first EC_GROUP object
b second EC_GROUP object
ctx BN_CTX object (optional)
Returns
0 if the groups are equal, 1 if not, or -1 on error
Definition at line 481 of file ec_lib.c.
EC_GROUP_copy()
int EC_GROUP_copy (EC_GROUP * dst, const EC_GROUP * src)
Copies EC_GROUP objects. Note: both EC_GROUPs must use the same EC_METHOD.
Parameters
dst destination EC_GROUP object
src source EC_GROUP object
Returns
1 on success and 0 if an error occurred.
Definition at line 135 of file ec_lib.c.
References BN_copy(), BN_MONT_CTX_copy(), BN_MONT_CTX_free(), BN_MONT_CTX_new(), EC_ec_pre_comp_dup(), EC_F_EC_GROUP_COPY, EC_FLAGS_CUSTOM_CURVE, EC_nistp224_pre_comp_dup(), EC_nistp256_pre_comp_dup(), EC_nistp521_pre_comp_dup(), EC_nistz256_pre_comp_dup(), EC_POINT_clear_free(), EC_POINT_copy(), EC_POINT_new(), EC_R_INCOMPATIBLE_OBJECTS, ECerr, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, NULL, OPENSSL_free, and OPENSSL_malloc.
Referenced by EC_GROUP_dup(), and EC_KEY_copy().
EC_GROUP_dup()
EC_GROUP* EC_GROUP_dup (const EC_GROUP * src)
Creates a new EC_GROUP object and copies the copies the content form src to the newly created EC_KEY object
Parameters
src source EC_GROUP object
Returns
newly created EC_GROUP object or NULL in case of an error.
Definition at line 236 of file ec_lib.c.
References EC_GROUP_copy(), EC_GROUP_free(), EC_GROUP_new(), NULL, and t.
Referenced by EC_KEY_set_group().
EC_GROUP_free()
void EC_GROUP_free (EC_GROUP * group)
Frees a EC_GROUP object
Parameters
group EC_GROUP object to be freed.
Definition at line 99 of file ec_lib.c.
References BN_free(), BN_MONT_CTX_free(), EC_POINT_free(), EC_pre_comp_free(), and OPENSSL_free.
Referenced by EC_GROUP_dup(), EC_KEY_copy(), EC_KEY_free(), and EC_KEY_set_group().
EC_GROUP_get0_cofactor()
const BIGNUM* EC_GROUP_get0_cofactor (const EC_GROUP * group)
Gets the cofactor of an EC_GROUP
Parameters
group EC_GROUP object
Returns
the group cofactor
Definition at line 354 of file ec_lib.c.
EC_GROUP_get0_generator()
const EC_POINT* EC_GROUP_get0_generator (const EC_GROUP * group)
Returns the generator of a EC_GROUP object.
Parameters
group EC_GROUP object
Returns
the currently used generator (possibly NULL).
Definition at line 311 of file ec_lib.c.
EC_GROUP_get0_order()
const BIGNUM* EC_GROUP_get0_order (const EC_GROUP * group)
Gets the order of an EC_GROUP
Parameters
group EC_GROUP object
Returns
the group order
Definition at line 331 of file ec_lib.c.
EC_GROUP_get0_seed()
unsigned char* EC_GROUP_get0_seed (const EC_GROUP * x)
Definition at line 408 of file ec_lib.c.
EC_GROUP_get_asn1_flag()
int EC_GROUP_get_asn1_flag (const EC_GROUP * group)
Definition at line 374 of file ec_lib.c.
EC_GROUP_get_basis_type()
int EC_GROUP_get_basis_type (const EC_GROUP *)
Definition at line 16 of file ec_asn1.c.
References EC_GROUP_method_of(), EC_METHOD_get_field_type(), NID_X9_62_characteristic_two_field, NID_X9_62_ppBasis, and NID_X9_62_tpBasis.
EC_GROUP_get_cofactor()
int EC_GROUP_get_cofactor (const EC_GROUP * group, BIGNUM * cofactor, BN_CTX * ctx)
Gets the cofactor of a EC_GROUP
Parameters
group EC_GROUP object
cofactor BIGNUM to which the cofactor is copied
ctx unused
Returns
1 on success and 0 if an error occurred
Definition at line 342 of file ec_lib.c.
References BN_copy(), BN_is_zero(), and NULL.
EC_GROUP_get_curve_GF2m()
int EC_GROUP_get_curve_GF2m (const EC_GROUP * group, BIGNUM * p, BIGNUM * a, BIGNUM * b, BN_CTX * ctx)
Gets the parameter of the ec over GF2m defined by y^2 + x*y = x^3 + a*x^2 + b
Parameters
group EC_GROUP object
p BIGNUM for the polynomial defining the underlying field
a BIGNUM for parameter a of the equation
b BIGNUM for parameter b of the equation
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 450 of file ec_lib.c.
References EC_F_EC_GROUP_GET_CURVE_GF2M, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_GROUP_get_curve_GFp()
int EC_GROUP_get_curve_GFp (const EC_GROUP * group, BIGNUM * p, BIGNUM * a, BIGNUM * b, BN_CTX * ctx)
Gets the parameter of the ec over GFp defined by y^2 = x^3 + a*x + b
Parameters
group EC_GROUP object
p BIGNUM for the prime number
a BIGNUM for parameter a of the equation
b BIGNUM for parameter b of the equation
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 428 of file ec_lib.c.
References EC_F_EC_GROUP_GET_CURVE_GFP, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_GROUP_get_curve_name()
int EC_GROUP_get_curve_name (const EC_GROUP * group)
Returns the curve name of a EC_GROUP object
Parameters
group EC_GROUP object
Returns
NID of the curve name OID or 0 if not set.
Definition at line 364 of file ec_lib.c.
Referenced by ssl3_ctx_ctrl(), and ssl_print_tmp_key().
EC_GROUP_get_degree()
int EC_GROUP_get_degree (const EC_GROUP * group)
Returns the number of bits needed to represent a field element
Parameters
group EC_GROUP object
Returns
number of bits needed to represent a field element
Definition at line 462 of file ec_lib.c.
References EC_F_EC_GROUP_GET_DEGREE, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_GROUP_get_ecparameters()
ECPARAMETERS* EC_GROUP_get_ecparameters (const EC_GROUP * group, ECPARAMETERS * params)
Creates an ECPARAMETERS object for the the given EC_GROUP object.
Parameters
group pointer to the EC_GROUP object
params pointer to an existing ECPARAMETERS object or NULL
Returns
pointer to the new ECPARAMETERS object or NULL if an error occurred.
Definition at line 468 of file ec_asn1.c.
References len.
EC_GROUP_get_ecpkparameters()
ECPKPARAMETERS* EC_GROUP_get_ecpkparameters (const EC_GROUP * group, ECPKPARAMETERS * params)
Creates an ECPKPARAMETERS object for the the given EC_GROUP object.
Parameters
group pointer to the EC_GROUP object
params pointer to an existing ECPKPARAMETERS object or NULL
Returns
pointer to the new ECPKPARAMETERS object or NULL if an error occurred.
Definition at line 551 of file ec_asn1.c.
EC_GROUP_get_mont_data()
BN_MONT_CTX* EC_GROUP_get_mont_data (const EC_GROUP * group)
Returns the montgomery data for order(Generator)
Parameters
group EC_GROUP object
Returns
the currently used montgomery data (possibly NULL).
Definition at line 316 of file ec_lib.c.
EC_GROUP_get_order()
int EC_GROUP_get_order (const EC_GROUP * group, BIGNUM * order, BN_CTX * ctx)
Gets the order of a EC_GROUP
Parameters
group EC_GROUP object
order BIGNUM to which the order is copied
ctx unused
Returns
1 on success and 0 if an error occurred
Definition at line 321 of file ec_lib.c.
EC_GROUP_get_pentanomial_basis()
int EC_GROUP_get_pentanomial_basis (const EC_GROUP * , unsigned int * k1, unsigned int * k2, unsigned int * k3)
Definition at line 58 of file ec_asn1.c.
References EC_F_EC_GROUP_GET_PENTANOMIAL_BASIS, EC_GROUP_method_of(), EC_METHOD_get_field_type(), ECerr, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, NID_X9_62_characteristic_two_field, and NULL.
EC_GROUP_get_point_conversion_form()
point_conversion_form_t EC_GROUP_get_point_conversion_form (const EC_GROUP *)
Definition at line 385 of file ec_lib.c.
EC_GROUP_get_seed_len()
size_t EC_GROUP_get_seed_len (const EC_GROUP *)
Definition at line 413 of file ec_lib.c.
EC_GROUP_get_trinomial_basis()
int EC_GROUP_get_trinomial_basis (const EC_GROUP * , unsigned int * k)
Definition at line 38 of file ec_asn1.c.
EC_GROUP_have_precompute_mult()
int EC_GROUP_have_precompute_mult (const EC_GROUP * group)
Reports whether a precomputation has been done
Parameters
group EC_GROUP object
Returns
1 if a pre-computation has been done and 0 otherwise
Definition at line 953 of file ec_lib.c.
References ec_wNAF_have_precompute_mult().
Referenced by ec_GF2m_simple_mul().
EC_GROUP_method_of()
const EC_METHOD* EC_GROUP_method_of (const EC_GROUP * group)
Returns the EC_METHOD of the EC_GROUP object.
Parameters
group EC_GROUP object
Returns
EC_METHOD used in this EC_GROUP object.
Definition at line 259 of file ec_lib.c.
Referenced by EC_GROUP_get_basis_type(), EC_GROUP_get_pentanomial_basis(), EC_KEY_copy(), and EC_KEY_set_public_key_affine_coordinates().
EC_GROUP_new()
EC_GROUP* EC_GROUP_new (const EC_METHOD * meth)
Creates a new EC_GROUP object
Parameters
meth EC_METHOD to use
Returns
newly created EC_GROUP object or NULL in case of an error.
Definition at line 25 of file ec_lib.c.
Referenced by EC_GROUP_dup(), and EC_KEY_copy().
EC_GROUP_new_by_curve_name()
EC_GROUP* EC_GROUP_new_by_curve_name (int nid)
Creates a EC_GROUP object with a curve specified by a NID
Parameters
nid NID of the OID of the curve name
Returns
newly created EC_GROUP object with specified curve or NULL if an error occurred
Definition at line 3085 of file ec_curve.c.
EC_GROUP_new_curve_GF2m()
EC_GROUP* EC_GROUP_new_curve_GF2m (const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Creates a new EC_GROUP object with the specified parameters defined over GF2m (defined by the equation y^2 + x*y = x^3 + a*x^2 + b)
Parameters
p BIGNUM with the polynomial defining the underlying field
a BIGNUM with the parameter a of the equation
b BIGNUM with the parameter b of the equation
ctx BN_CTX object (optional)
Returns
newly created EC_GROUP object with the specified parameters
Definition at line 76 of file ec_cvt.c.
EC_GROUP_new_curve_GFp()
EC_GROUP* EC_GROUP_new_curve_GFp (const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Creates a new EC_GROUP object with the specified parameters defined over GFp (defined by the equation y^2 = x^3 + a*x + b)
Parameters
p BIGNUM with the prime number
a BIGNUM with the parameter a of the equation
b BIGNUM with the parameter b of the equation
ctx BN_CTX object (optional)
Returns
newly created EC_GROUP object with the specified parameters
Definition at line 27 of file ec_cvt.c.
EC_GROUP_new_from_ecparameters()
EC_GROUP* EC_GROUP_new_from_ecparameters (const ECPARAMETERS * params)
Creates a new EC_GROUP object from an ECPARAMETERS object
Parameters
params pointer to the ECPARAMETERS object
Returns
newly created EC_GROUP object with specified curve or NULL if an error occurred
Definition at line 596 of file ec_asn1.c.
EC_GROUP_new_from_ecpkparameters()
EC_GROUP* EC_GROUP_new_from_ecpkparameters (const ECPKPARAMETERS * params)
Creates a new EC_GROUP object from an ECPKPARAMETERS object
Parameters
params pointer to an existing ECPKPARAMETERS object, or NULL
Returns
newly created EC_GROUP object with specified curve, or NULL if an error occurred
Definition at line 830 of file ec_asn1.c.
Referenced by d2i_ECPKParameters().
EC_GROUP_order_bits()
int EC_GROUP_order_bits (const EC_GROUP * group)
Gets the number of bits of the order of an EC_GROUP
Parameters
group EC_GROUP object
Returns
number of bits of group order.
Definition at line 336 of file ec_lib.c.
References NULL, and OPENSSL_assert.
EC_GROUP_precompute_mult()
int EC_GROUP_precompute_mult (EC_GROUP * group, BN_CTX * ctx)
Stores multiples of generator for faster point multiplication
Parameters
group EC_GROUP object
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 941 of file ec_lib.c.
References ec_wNAF_precompute_mult().
Referenced by EC_KEY_precompute_mult().
EC_GROUP_set_asn1_flag()
void EC_GROUP_set_asn1_flag (EC_GROUP * group, int flag)
Definition at line 369 of file ec_lib.c.
EC_GROUP_set_curve_GF2m()
int EC_GROUP_set_curve_GF2m (EC_GROUP * group, const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Sets the parameter of a ec over GF2m defined by y^2 + x*y = x^3 + a*x^2 + b
Parameters
group EC_GROUP object
p BIGNUM with the polynomial defining the underlying field
a BIGNUM with parameter a of the equation
b BIGNUM with parameter b of the equation
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 439 of file ec_lib.c.
References EC_F_EC_GROUP_SET_CURVE_GF2M, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_GROUP_set_curve_GFp()
int EC_GROUP_set_curve_GFp (EC_GROUP * group, const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Sets the parameter of a ec over GFp defined by y^2 = x^3 + a*x + b
Parameters
group EC_GROUP object
p BIGNUM with the prime number
a BIGNUM with parameter a of the equation
b BIGNUM with parameter b of the equation
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 418 of file ec_lib.c.
References EC_F_EC_GROUP_SET_CURVE_GFP, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_GROUP_set_curve_name()
void EC_GROUP_set_curve_name (EC_GROUP * group, int nid)
Sets the name of a EC_GROUP object
Parameters
group EC_GROUP object
nid NID of the curve name OID
Definition at line 359 of file ec_lib.c.
References nid.
EC_GROUP_set_generator()
int EC_GROUP_set_generator (EC_GROUP * group, const EC_POINT * generator, const BIGNUM * order, const BIGNUM * cofactor)
Sets the generator and it's order/cofactor of a EC_GROUP object.
Parameters
group EC_GROUP object
generator EC_POINT object with the generator.
order the order of the group generated by the generator.
cofactor the index of the sub-group generated by the generator in the group of all points on the elliptic curve.
Returns
1 on success and 0 if an error occurred
Definition at line 269 of file ec_lib.c.
EC_GROUP_set_point_conversion_form()
void EC_GROUP_set_point_conversion_form (EC_GROUP * group, point_conversion_form_t form)
Definition at line 379 of file ec_lib.c.
Referenced by EC_KEY_set_conv_form().
EC_GROUP_set_seed()
size_t EC_GROUP_set_seed (EC_GROUP * , const unsigned char * , size_t len)
Definition at line 391 of file ec_lib.c.
References len, NULL, OPENSSL_free, and OPENSSL_malloc.
EC_KEY_can_sign()
int EC_KEY_can_sign (const EC_KEY * eckey)
Indicates if an EC_KEY can be used for signing.
Parameters
key the EC_KEY object
Returns
1 if can can sign and 0 otherwise.
Definition at line 631 of file ec_key.c.
References EC_FLAGS_NO_SIGN, and NULL.
EC_KEY_check_key()
int EC_KEY_check_key (const EC_KEY * key)
Verifies that a private and/or public key is valid.
Parameters
key the EC_KEY object
Returns
1 on success and 0 otherwise.
Definition at line 255 of file ec_key.c.
References EC_F_EC_KEY_CHECK_KEY, ECerr, ERR_R_PASSED_NULL_PARAMETER, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, and NULL.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_KEY_clear_flags()
void EC_KEY_clear_flags (EC_KEY * key, int flags)
Definition at line 513 of file ec_key.c.
EC_KEY_copy()
EC_KEY* EC_KEY_copy (EC_KEY * dst, const EC_KEY * src)
Copies a EC_KEY object.
Parameters
dst destination EC_KEY object
src src EC_KEY object
Returns
dst or NULL if an error occurred.
Definition at line 77 of file ec_key.c.
References BN_copy(), BN_new(), CRYPTO_dup_ex_data(), CRYPTO_EX_INDEX_EC_KEY, EC_F_EC_KEY_COPY, EC_GROUP_copy(), EC_GROUP_free(), EC_GROUP_method_of(), EC_GROUP_new(), EC_POINT_copy(), EC_POINT_free(), EC_POINT_new(), ECerr, ENGINE_finish(), ENGINE_init(), ERR_R_PASSED_NULL_PARAMETER, and NULL.
EC_KEY_dup()
EC_KEY* EC_KEY_dup (const EC_KEY * src)
Creates a new EC_KEY object and copies the content from src to it.
Parameters
src the source EC_KEY object
Returns
newly created EC_KEY object or NULL if an error occurred.
Definition at line 154 of file ec_key.c.
EC_KEY_free()
void EC_KEY_free (EC_KEY * key)
Frees a EC_KEY object.
Parameters
key EC_KEY object to be freed.
Definition at line 45 of file ec_key.c.
References BN_clear_free(), CRYPTO_DOWN_REF, CRYPTO_EX_INDEX_EC_KEY, CRYPTO_free_ex_data(), CRYPTO_THREAD_lock_free(), EC_GROUP_free(), EC_POINT_free(), ENGINE_finish(), NULL, OPENSSL_clear_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by ssl_print_tmp_key().
EC_KEY_generate_key()
int EC_KEY_generate_key (EC_KEY * key)
Creates a new ec private (and optional a new public) key.
Parameters
key EC_KEY object
Returns
1 on success and 0 if an error occurred.
Definition at line 180 of file ec_key.c.
References EC_F_EC_KEY_GENERATE_KEY, EC_R_OPERATION_NOT_SUPPORTED, ECerr, ERR_R_PASSED_NULL_PARAMETER, and NULL.
EC_KEY_get0_group()
const EC_GROUP* EC_KEY_get0_group (const EC_KEY * key)
Returns the EC_GROUP object of a EC_KEY object
Parameters
key EC_KEY object
Returns
the EC_GROUP object (possibly NULL).
Definition at line 419 of file ec_key.c.
Referenced by ssl3_ctx_ctrl(), and ssl_print_tmp_key().
EC_KEY_get0_private_key()
const BIGNUM* EC_KEY_get0_private_key (const EC_KEY * key)
Returns the private key of a EC_KEY object.
Parameters
key EC_KEY object
Returns
a BIGNUM with the private key (possibly NULL).
Definition at line 433 of file ec_key.c.
Referenced by EC_KEY_print().
EC_KEY_get0_public_key()
const EC_POINT* EC_KEY_get0_public_key (const EC_KEY * key)
Returns the public key of a EC_KEY object.
Parameters
key the EC_KEY object
Returns
a EC_POINT object with the public key (possibly NULL)
Definition at line 453 of file ec_key.c.
EC_KEY_get_conv_form()
point_conversion_form_t EC_KEY_get_conv_form (const EC_KEY * key)
Definition at line 478 of file ec_key.c.
EC_KEY_get_default_method()
const EC_KEY_METHOD* EC_KEY_get_default_method (void)
Definition at line 37 of file ec_kmeth.c.
EC_KEY_get_enc_flags()
unsigned EC_KEY_get_enc_flags (const EC_KEY * key)
Definition at line 468 of file ec_key.c.
EC_KEY_get_ex_data()
void* EC_KEY_get_ex_data (const EC_KEY * key, int idx)
Definition at line 1004 of file ec_lib.c.
EC_KEY_get_flags()
int EC_KEY_get_flags (const EC_KEY * key)
Definition at line 503 of file ec_key.c.
EC_KEY_get_method()
const EC_KEY_METHOD* EC_KEY_get_method (const EC_KEY * key)
Definition at line 50 of file ec_kmeth.c.
EC_KEY_key2buf()
size_t EC_KEY_key2buf (const EC_KEY * key, point_conversion_form_t form, unsigned char ** pbuf, BN_CTX * ctx)
Encodes an EC_KEY public key to an allocated octet string
Parameters
key key to encode
form point conversion form
pbuf returns pointer to allocated buffer
len length of the memory buffer
ctx BN_CTX object (optional)
Returns
the length of the encoded octet string or 0 if an error occurred
Definition at line 518 of file ec_key.c.
References EC_POINT_point2buf(), and NULL.
EC_KEY_METHOD_free()
void EC_KEY_METHOD_free (EC_KEY_METHOD * meth)
Definition at line 167 of file ec_kmeth.c.
References EC_KEY_METHOD_DYNAMIC, and OPENSSL_free.
EC_KEY_METHOD_get_compute_key()
void EC_KEY_METHOD_get_compute_key (EC_KEY_METHOD * meth, int(**)(unsigned char **psec, size_t *pseclen, const EC_POINT *pub_key, const EC_KEY *ecdh) pck)
EC_KEY_METHOD_get_init()
void EC_KEY_METHOD_get_init (EC_KEY_METHOD * meth, int(**)(EC_KEY *key) pinit, void(**)(EC_KEY *key) pfinish, int(**)(EC_KEY *dest, const EC_KEY *src) pcopy, int(**)(EC_KEY *key, const EC_GROUP *grp) pset_group, int(**)(EC_KEY *key, const BIGNUM *priv_key) pset_private, int(**)(EC_KEY *key, const EC_POINT *pub_key) pset_public)
Definition at line 239 of file ec_kmeth.c.
References NULL.
EC_KEY_METHOD_get_keygen()
void EC_KEY_METHOD_get_keygen (EC_KEY_METHOD * meth, int(**)(EC_KEY *key) pkeygen)
Definition at line 264 of file ec_kmeth.c.
References NULL.
EC_KEY_METHOD_get_sign()
void EC_KEY_METHOD_get_sign (EC_KEY_METHOD * meth, int(**)(int type, const unsigned char *dgst, int dlen, unsigned char *sig, unsigned int *siglen, const BIGNUM *kinv, const BIGNUM *r, EC_KEY *eckey) psign, int(**)(EC_KEY *eckey, BN_CTX *ctx_in, BIGNUM **kinvp, BIGNUM **rp) psign_setup, ECDSA_SIG *(**)(const unsigned char *dgst, int dgst_len, const BIGNUM *in_kinv, const BIGNUM *in_r, EC_KEY *eckey) psign_sig)
Definition at line 281 of file ec_kmeth.c.
References NULL.
EC_KEY_METHOD_get_verify()
void EC_KEY_METHOD_get_verify (EC_KEY_METHOD * meth, int(**)(int type, const unsigned char *dgst, int dgst_len, const unsigned char *sigbuf, int sig_len, EC_KEY *eckey) pverify, int(**)(const unsigned char *dgst, int dgst_len, const ECDSA_SIG *sig, EC_KEY *eckey) pverify_sig)
Definition at line 303 of file ec_kmeth.c.
References NULL.
EC_KEY_METHOD_new()
EC_KEY_METHOD* EC_KEY_METHOD_new (const EC_KEY_METHOD * meth)
Definition at line 155 of file ec_kmeth.c.
EC_KEY_METHOD_set_compute_key()
void EC_KEY_METHOD_set_compute_key (EC_KEY_METHOD * meth, int(*)(unsigned char **psec, size_t *pseclen, const EC_POINT *pub_key, const EC_KEY *ecdh) ckey)
Definition at line 197 of file ec_kmeth.c.
EC_KEY_METHOD_set_init()
void EC_KEY_METHOD_set_init (EC_KEY_METHOD * meth, int(*)(EC_KEY *key) init, void(*)(EC_KEY *key) finish, int(*)(EC_KEY *dest, const EC_KEY *src) copy, int(*)(EC_KEY *key, const EC_GROUP *grp) set_group, int(*)(EC_KEY *key, const BIGNUM *priv_key) set_private, int(*)(EC_KEY *key, const EC_POINT *pub_key) set_public)
Definition at line 173 of file ec_kmeth.c.
EC_KEY_METHOD_set_keygen()
void EC_KEY_METHOD_set_keygen (EC_KEY_METHOD * meth, int(*)(EC_KEY *key) keygen)
Definition at line 191 of file ec_kmeth.c.
EC_KEY_METHOD_set_sign()
void EC_KEY_METHOD_set_sign (EC_KEY_METHOD * meth, int(*)(int type, const unsigned char *dgst, int dlen, unsigned char *sig, unsigned int *siglen, const BIGNUM *kinv, const BIGNUM *r, EC_KEY *eckey) sign, int(*)(EC_KEY *eckey, BN_CTX *ctx_in, BIGNUM **kinvp, BIGNUM **rp) sign_setup, ECDSA_SIG *(*)(const unsigned char *dgst, int dgst_len, const BIGNUM *in_kinv, const BIGNUM *in_r, EC_KEY *eckey) sign_sig)
Definition at line 206 of file ec_kmeth.c.
EC_KEY_METHOD_set_verify()
void EC_KEY_METHOD_set_verify (EC_KEY_METHOD * meth, int(*)(int type, const unsigned char *dgst, int dgst_len, const unsigned char *sigbuf, int sig_len, EC_KEY *eckey) verify, int(*)(const unsigned char *dgst, int dgst_len, const ECDSA_SIG *sig, EC_KEY *eckey) verify_sig)
Definition at line 225 of file ec_kmeth.c.
EC_KEY_new()
EC_KEY* EC_KEY_new (void)
Creates a new EC_KEY object.
Returns
EC_KEY object or NULL if an error occurred.
Definition at line 22 of file ec_key.c.
References EC_KEY_new_method(), and NULL.
Referenced by d2i_EC_PUBKEY_bio(), d2i_EC_PUBKEY_fp(), d2i_ECPrivateKey_bio(), and d2i_ECPrivateKey_fp().
EC_KEY_new_by_curve_name()
EC_KEY* EC_KEY_new_by_curve_name (int nid)
Creates a new EC_KEY object using a named curve as underlying EC_GROUP object.
Parameters
nid NID of the named curve.
Returns
EC_KEY object or NULL if an error occurred.
Definition at line 27 of file ec_key.c.
EC_KEY_new_method()
EC_KEY* EC_KEY_new_method (ENGINE * engine)
Definition at line 73 of file ec_kmeth.c.
Referenced by EC_KEY_new().
EC_KEY_oct2key()
int EC_KEY_oct2key (EC_KEY * key, const unsigned char * buf, size_t len, BN_CTX * ctx)
Decodes a EC_KEY public key from a octet string
Parameters
key key to decode
buf memory buffer with the encoded ec point
len length of the encoded ec point
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 526 of file ec_key.c.
EC_KEY_oct2priv()
int EC_KEY_oct2priv (EC_KEY * key, const unsigned char * buf, size_t len)
Decodes an EC_KEY private key from an octet string
Parameters
key key to decode
buf memory buffer with the encoded private key
len length of the encoded key
Returns
1 on success and 0 if an error occurred
Definition at line 585 of file ec_key.c.
EC_KEY_OpenSSL()
const EC_KEY_METHOD* EC_KEY_OpenSSL (void)
Definition at line 32 of file ec_kmeth.c.
EC_KEY_precompute_mult()
int EC_KEY_precompute_mult (EC_KEY * key, BN_CTX * ctx)
Creates a table of pre-computed multiples of the generator to accelerate further EC_KEY operations.
Parameters
key EC_KEY object
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred.
Definition at line 496 of file ec_key.c.
References EC_GROUP_precompute_mult(), and NULL.
EC_KEY_print()
int EC_KEY_print (BIO * bp, const EC_KEY * key, int off)
Prints out the contents of a EC_KEY object
Parameters
bp BIO object to which the information is printed
key EC_KEY object
off line offset
Returns
1 on success and 0 if an error occurred
Definition at line 553 of file ec_ameth.c.
References EC_KEY_get0_private_key(), and NULL.
EC_KEY_print_fp()
int EC_KEY_print_fp (FILE * fp, const EC_KEY * key, int off)
Prints out the contents of a EC_KEY object
Parameters
fp file descriptor to which the information is printed
key EC_KEY object
off line offset
Returns
1 on success and 0 if an error occurred
Definition at line 38 of file eck_prn.c.
EC_KEY_priv2buf()
size_t EC_KEY_priv2buf (const EC_KEY * eckey, unsigned char ** pbuf)
Encodes an EC_KEY private key to an allocated octet string
Parameters
key key to encode
pbuf returns pointer to allocated buffer
Returns
the length of the encoded octet string or 0 if an error occurred
Definition at line 612 of file ec_key.c.
References len.
EC_KEY_priv2oct()
size_t EC_KEY_priv2oct (const EC_KEY * key, unsigned char * buf, size_t len)
Encodes a EC_KEY private key to an octet string
Parameters
key key to encode
buf memory buffer for the result. If NULL the function returns required buffer size.
len length of the memory buffer
Returns
the length of the encoded octet string or 0 if an error occurred
Definition at line 549 of file ec_key.c.
EC_KEY_set_asn1_flag()
void EC_KEY_set_asn1_flag (EC_KEY * eckey, int asn1_flag)
Definition at line 490 of file ec_key.c.
EC_KEY_set_conv_form()
void EC_KEY_set_conv_form (EC_KEY * eckey, point_conversion_form_t cform)
Definition at line 483 of file ec_key.c.
References EC_GROUP_set_point_conversion_form(), and NULL.
EC_KEY_set_default_method()
void EC_KEY_set_default_method (const EC_KEY_METHOD * meth)
Definition at line 42 of file ec_kmeth.c.
References NULL.
EC_KEY_set_enc_flags()
void EC_KEY_set_enc_flags (EC_KEY * eckey, unsigned int flags)
Definition at line 473 of file ec_key.c.
References flags.
EC_KEY_set_ex_data()
int EC_KEY_set_ex_data (EC_KEY * key, int idx, void * arg)
Definition at line 999 of file ec_lib.c.
EC_KEY_set_flags()
void EC_KEY_set_flags (EC_KEY * key, int flags)
Definition at line 508 of file ec_key.c.
References flags.
EC_KEY_set_group()
int EC_KEY_set_group (EC_KEY * key, const EC_GROUP * group)
Sets the EC_GROUP of a EC_KEY object.
Parameters
key EC_KEY object
group EC_GROUP to use in the EC_KEY object (note: the EC_KEY object will use an own copy of the EC_GROUP).
Returns
1 on success and 0 if an error occurred.
Definition at line 424 of file ec_key.c.
References EC_GROUP_dup(), EC_GROUP_free(), and NULL.
EC_KEY_set_method()
int EC_KEY_set_method (EC_KEY * key, const EC_KEY_METHOD * meth)
Definition at line 55 of file ec_kmeth.c.
References ENGINE_finish(), if(), key, and NULL.
EC_KEY_set_private_key()
int EC_KEY_set_private_key (EC_KEY * key, const BIGNUM * prv)
Sets the private key of a EC_KEY object.
Parameters
key EC_KEY object
prv BIGNUM with the private key (note: the EC_KEY object will use an own copy of the BIGNUM).
Returns
1 on success and 0 if an error occurred.
Definition at line 438 of file ec_key.c.
References BN_clear_free(), BN_dup(), and NULL.
EC_KEY_set_public_key()
int EC_KEY_set_public_key (EC_KEY * key, const EC_POINT * pub)
Sets the public key of a EC_KEY object.
Parameters
key EC_KEY object
pub EC_POINT object with the public key (note: the EC_KEY object will use an own copy of the EC_POINT object).
Returns
1 on success and 0 if an error occurred.
Definition at line 458 of file ec_key.c.
References EC_POINT_dup(), EC_POINT_free(), and NULL.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_KEY_set_public_key_affine_coordinates()
int EC_KEY_set_public_key_affine_coordinates (EC_KEY * key, BIGNUM * x, BIGNUM * y)
Sets a public key from affine coordinates performing necessary NIST PKV tests.
Parameters
key the EC_KEY object
x public key x coordinate
y public key y coordinate
Returns
1 on success and 0 otherwise.
Definition at line 337 of file ec_key.c.
References BN_cmp(), BN_CTX_end(), BN_CTX_free(), BN_CTX_get(), BN_CTX_new(), BN_CTX_start(), ctx, EC_F_EC_KEY_SET_PUBLIC_KEY_AFFINE_COORDINATES, EC_GROUP_method_of(), EC_KEY_check_key(), EC_KEY_set_public_key(), EC_METHOD_get_field_type(), EC_POINT_free(), EC_POINT_get_affine_coordinates_GF2m(), EC_POINT_get_affine_coordinates_GFp(), EC_POINT_new(), EC_POINT_set_affine_coordinates_GF2m(), EC_POINT_set_affine_coordinates_GFp(), EC_R_COORDINATES_OUT_OF_RANGE, ECerr, ERR_R_PASSED_NULL_PARAMETER, NID_X9_62_characteristic_two_field, and NULL.
EC_KEY_up_ref()
int EC_KEY_up_ref (EC_KEY * key)
Increases the internal reference count of a EC_KEY object.
Parameters
key EC_KEY object
Returns
1 on success and 0 if an error occurred.
Definition at line 168 of file ec_key.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
EC_METHOD_get_field_type()
int EC_METHOD_get_field_type (const EC_METHOD * meth)
Returns the field type of the EC_METHOD.
Parameters
meth EC_METHOD object
Returns
NID of the underlying field type OID.
Definition at line 264 of file ec_lib.c.
Referenced by EC_GROUP_get_basis_type(), EC_GROUP_get_pentanomial_basis(), and EC_KEY_set_public_key_affine_coordinates().
EC_POINT_add()
int EC_POINT_add (const EC_GROUP * group, EC_POINT * r, const EC_POINT * a, const EC_POINT * b, BN_CTX * ctx)
Computes the sum of two EC_POINT
Parameters
group underlying EC_GROUP object
r EC_POINT object for the result (r = a + b)
a EC_POINT object with the first summand
b EC_POINT object with the second summand
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 786 of file ec_lib.c.
References EC_F_EC_POINT_ADD, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_POINT_bn2point()
EC_POINT* EC_POINT_bn2point (const EC_GROUP * , const BIGNUM * , EC_POINT * , BN_CTX *)
Definition at line 33 of file ec_print.c.
EC_POINT_clear_free()
void EC_POINT_clear_free (EC_POINT * point)
Clears and frees a EC_POINT object
Parameters
point EC_POINT object to be cleared and freed
Definition at line 595 of file ec_lib.c.
References OPENSSL_clear_free.
Referenced by EC_GROUP_clear_free(), and EC_GROUP_copy().
EC_POINT_cmp()
int EC_POINT_cmp (const EC_GROUP * group, const EC_POINT * a, const EC_POINT * b, BN_CTX * ctx)
Compares two EC_POINTs
Parameters
group underlying EC_GROUP object
a first EC_POINT object
b second EC_POINT object
ctx BN_CTX object (optional)
Returns
1 if the points are not equal, 0 if they are, or -1 on error
Definition at line 863 of file ec_lib.c.
References EC_F_EC_POINT_CMP, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_POINT_copy()
int EC_POINT_copy (EC_POINT * dst, const EC_POINT * src)
Copies EC_POINT object
Parameters
dst destination EC_POINT object
src source EC_POINT object
Returns
1 on success and 0 if an error occurred
Definition at line 607 of file ec_lib.c.
References EC_F_EC_POINT_COPY, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by EC_GROUP_copy(), EC_KEY_copy(), and EC_POINT_dup().
EC_POINT_dbl()
int EC_POINT_dbl (const EC_GROUP * group, EC_POINT * r, const EC_POINT * a, BN_CTX * ctx)
Computes the double of a EC_POINT
Parameters
group underlying EC_GROUP object
r EC_POINT object for the result (r = 2 * a)
a EC_POINT object
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 801 of file ec_lib.c.
References EC_F_EC_POINT_DBL, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_POINT_dup()
EC_POINT* EC_POINT_dup (const EC_POINT * src, const EC_GROUP * group)
Creates a new EC_POINT object and copies the content of the supplied EC_POINT
Parameters
src source EC_POINT object
group underlying the EC_GROUP object
Returns
newly created EC_POINT object or NULL if an error occurred
Definition at line 622 of file ec_lib.c.
References EC_POINT_copy(), EC_POINT_free(), EC_POINT_new(), NULL, and t.
Referenced by EC_KEY_set_public_key().
EC_POINT_free()
void EC_POINT_free (EC_POINT * point)
Frees a EC_POINT object
Parameters
point EC_POINT object to be freed
Definition at line 585 of file ec_lib.c.
References OPENSSL_free.
Referenced by EC_ec_pre_comp_free(), EC_GROUP_free(), EC_KEY_copy(), EC_KEY_free(), EC_KEY_set_public_key(), EC_KEY_set_public_key_affine_coordinates(), and EC_POINT_dup().
EC_POINT_get_affine_coordinates_GF2m()
int EC_POINT_get_affine_coordinates_GF2m (const EC_GROUP * group, const EC_POINT * p, BIGNUM * x, BIGNUM * y, BN_CTX * ctx)
Gets the affine coordinates of a EC_POINT over GF2m
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM for the x-coordinate
y BIGNUM for the y-coordinate
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 768 of file ec_lib.c.
References EC_F_EC_POINT_GET_AFFINE_COORDINATES_GF2M, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_POINT_get_affine_coordinates_GFp()
int EC_POINT_get_affine_coordinates_GFp (const EC_GROUP * group, const EC_POINT * p, BIGNUM * x, BIGNUM * y, BN_CTX * ctx)
Gets the affine coordinates of a EC_POINT over GFp
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM for the x-coordinate
y BIGNUM for the y-coordinate
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 750 of file ec_lib.c.
References EC_F_EC_POINT_GET_AFFINE_COORDINATES_GFP, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_POINT_get_Jprojective_coordinates_GFp()
int EC_POINT_get_Jprojective_coordinates_GFp (const EC_GROUP * group, const EC_POINT * p, BIGNUM * x, BIGNUM * y, BIGNUM * z, BN_CTX * ctx)
Gets the jacobian projective coordinates of a EC_POINT over GFp
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM for the x-coordinate
y BIGNUM for the y-coordinate
z BIGNUM for the z-coordinate
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 679 of file ec_lib.c.
References EC_F_EC_POINT_GET_JPROJECTIVE_COORDINATES_GFP, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_POINT_hex2point()
EC_POINT* EC_POINT_hex2point (const EC_GROUP * , const char * , EC_POINT * , BN_CTX *)
Definition at line 105 of file ec_print.c.
EC_POINT_invert()
int EC_POINT_invert (const EC_GROUP * group, EC_POINT * a, BN_CTX * ctx)
Computes the inverse of a EC_POINT
Parameters
group underlying EC_GROUP object
a EC_POINT object to be inverted (it's used for the result as well)
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 815 of file ec_lib.c.
References EC_F_EC_POINT_INVERT, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_POINT_is_at_infinity()
int EC_POINT_is_at_infinity (const EC_GROUP * group, const EC_POINT * p)
Checks whether the point is the neutral element of the group
Parameters
group the underlying EC_GROUP object
p EC_POINT object
Returns
1 if the point is the neutral element and 0 otherwise
Definition at line 828 of file ec_lib.c.
References EC_F_EC_POINT_IS_AT_INFINITY, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by ec_GF2m_simple_invert(), ec_GFp_nistp224_point_get_affine_coordinates(), ec_GFp_nistp256_point_get_affine_coordinates(), ec_GFp_nistp521_point_get_affine_coordinates(), and ec_GFp_simple_invert().
EC_POINT_is_on_curve()
int EC_POINT_is_on_curve (const EC_GROUP * group, const EC_POINT * point, BN_CTX * ctx)
Checks whether the point is on the curve
Parameters
group underlying EC_GROUP object
point EC_POINT object to check
ctx BN_CTX object (optional)
Returns
1 if the point is on the curve, 0 if not, or -1 on error
Definition at line 849 of file ec_lib.c.
References EC_F_EC_POINT_IS_ON_CURVE, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by EC_POINT_set_affine_coordinates_GF2m(), and EC_POINT_set_affine_coordinates_GFp().
EC_POINT_make_affine()
int EC_POINT_make_affine (const EC_GROUP * group, EC_POINT * point, BN_CTX * ctx)
Definition at line 877 of file ec_lib.c.
References EC_F_EC_POINT_MAKE_AFFINE, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by ec_GF2m_simple_invert().
EC_POINT_method_of()
const EC_METHOD* EC_POINT_method_of (const EC_POINT * point)
Returns the EC_METHOD used in EC_POINT object
Parameters
point EC_POINT object
Returns
the EC_METHOD used
Definition at line 641 of file ec_lib.c.
EC_POINT_mul()
int EC_POINT_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * n, const EC_POINT * q, const BIGNUM * m, BN_CTX * ctx)
Computes r = generator * n + q * m
Parameters
group underlying EC_GROUP object
r EC_POINT object for the result
n BIGNUM with the multiplier for the group generator (optional)
q EC_POINT object with the first factor of the second summand
m BIGNUM with the second factor of the second summand
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 925 of file ec_lib.c.
References EC_POINTs_mul(), and NULL.
Referenced by ec_key_simple_generate_public_key().
EC_POINT_new()
EC_POINT* EC_POINT_new (const EC_GROUP * group)
Creates a new EC_POINT object for the specified EC_GROUP
Parameters
group EC_GROUP the underlying EC_GROUP object
Returns
newly created EC_POINT object or NULL if an error occurred
Definition at line 556 of file ec_lib.c.
Referenced by ec_GF2m_simple_mul(), EC_GROUP_copy(), EC_KEY_copy(), EC_KEY_set_public_key_affine_coordinates(), and EC_POINT_dup().
EC_POINT_oct2point()
int EC_POINT_oct2point (const EC_GROUP * group, EC_POINT * p, const unsigned char * buf, size_t len, BN_CTX * ctx)
Decodes a EC_POINT from a octet string
Parameters
group underlying EC_GROUP object
p EC_POINT object
buf memory buffer with the encoded ec point
len length of the encoded ec point
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 118 of file ec_oct.c.
EC_POINT_point2bn()
BIGNUM* EC_POINT_point2bn (const EC_GROUP * , const EC_POINT * , point_conversion_form_t form, BIGNUM * , BN_CTX *)
Definition at line 13 of file ec_print.c.
EC_POINT_point2buf()
size_t EC_POINT_point2buf (const EC_GROUP * group, const EC_POINT * point, point_conversion_form_t form, unsigned char ** pbuf, BN_CTX * ctx)
Encodes an EC_POINT object to an allocated octet string
Parameters
group underlying EC_GROUP object
point EC_POINT object
form point conversion form
pbuf returns pointer to allocated buffer
len length of the memory buffer
ctx BN_CTX object (optional)
Returns
the length of the encoded octet string or 0 if an error occurred
Definition at line 146 of file ec_oct.c.
References len.
Referenced by EC_KEY_key2buf().
EC_POINT_point2hex()
char* EC_POINT_point2hex (const EC_GROUP * , const EC_POINT * , point_conversion_form_t form, BN_CTX *)
Definition at line 73 of file ec_print.c.
EC_POINT_point2oct()
size_t EC_POINT_point2oct (const EC_GROUP * group, const EC_POINT * p, point_conversion_form_t form, unsigned char * buf, size_t len, BN_CTX * ctx)
Encodes a EC_POINT object to a octet string
Parameters
group underlying EC_GROUP object
p EC_POINT object
form point conversion form
buf memory buffer for the result. If NULL the function returns required buffer size.
len length of the memory buffer
ctx BN_CTX object (optional)
Returns
the length of the encoded octet string or 0 if an error occurred
Definition at line 87 of file ec_oct.c.
EC_POINT_set_affine_coordinates_GF2m()
int EC_POINT_set_affine_coordinates_GF2m (const EC_GROUP * group, EC_POINT * p, const BIGNUM * x, const BIGNUM * y, BN_CTX * ctx)
Sets the affine coordinates of a EC_POINT over GF2m
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM with the x-coordinate
y BIGNUM with the y-coordinate
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 724 of file ec_lib.c.
References EC_F_EC_POINT_SET_AFFINE_COORDINATES_GF2M, EC_POINT_is_on_curve(), EC_R_INCOMPATIBLE_OBJECTS, EC_R_POINT_IS_NOT_ON_CURVE, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_POINT_set_affine_coordinates_GFp()
int EC_POINT_set_affine_coordinates_GFp (const EC_GROUP * group, EC_POINT * p, const BIGNUM * x, const BIGNUM * y, BN_CTX * ctx)
Sets the affine coordinates of a EC_POINT over GFp
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM with the x-coordinate
y BIGNUM with the y-coordinate
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 698 of file ec_lib.c.
References EC_F_EC_POINT_SET_AFFINE_COORDINATES_GFP, EC_POINT_is_on_curve(), EC_R_INCOMPATIBLE_OBJECTS, EC_R_POINT_IS_NOT_ON_CURVE, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_POINT_set_compressed_coordinates_GF2m()
int EC_POINT_set_compressed_coordinates_GF2m (const EC_GROUP * group, EC_POINT * p, const BIGNUM * x, int y_bit, BN_CTX * ctx)
Sets the x9.62 compressed coordinates of a EC_POINT over GF2m
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM with x-coordinate
y_bit integer with the y-Bit (either 0 or 1)
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 59 of file ec_oct.c.
References EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GF2M, EC_FLAGS_DEFAULT_OCT, ec_GF2m_simple_set_compressed_coordinates(), ec_GFp_simple_set_compressed_coordinates(), EC_R_INCOMPATIBLE_OBJECTS, ECerr, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, and NID_X9_62_prime_field.
EC_POINT_set_compressed_coordinates_GFp()
int EC_POINT_set_compressed_coordinates_GFp (const EC_GROUP * group, EC_POINT * p, const BIGNUM * x, int y_bit, BN_CTX * ctx)
Sets the x9.62 compressed coordinates of a EC_POINT over GFp
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM with x-coordinate
y_bit integer with the y-Bit (either 0 or 1)
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 23 of file ec_oct.c.
References EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GFP, EC_FLAGS_DEFAULT_OCT, ec_GF2m_simple_set_compressed_coordinates(), ec_GFp_simple_set_compressed_coordinates(), EC_R_GF2M_NOT_SUPPORTED, EC_R_INCOMPATIBLE_OBJECTS, ECerr, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, and NID_X9_62_prime_field.
EC_POINT_set_Jprojective_coordinates_GFp()
int EC_POINT_set_Jprojective_coordinates_GFp (const EC_GROUP * group, EC_POINT * p, const BIGNUM * x, const BIGNUM * y, const BIGNUM * z, BN_CTX * ctx)
Sets the jacobian projective coordinates of a EC_POINT over GFp
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM with the x-coordinate
y BIGNUM with the y-coordinate
z BIGNUM with the z-coordinate
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 660 of file ec_lib.c.
References EC_F_EC_POINT_SET_JPROJECTIVE_COORDINATES_GFP, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by ec_GFp_simple_point_set_affine_coordinates().
EC_POINT_set_to_infinity()
int EC_POINT_set_to_infinity (const EC_GROUP * group, EC_POINT * point)
Sets a point to infinity (neutral element)
Parameters
group underlying EC_GROUP object
point EC_POINT to set to infinity
Returns
1 on success and 0 if an error occurred
Definition at line 646 of file ec_lib.c.
References EC_F_EC_POINT_SET_TO_INFINITY, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by ec_GF2m_simple_mul().
EC_POINTs_make_affine()
int EC_POINTs_make_affine (const EC_GROUP * group, size_t num, EC_POINT * points[], BN_CTX * ctx)
Definition at line 890 of file ec_lib.c.
References EC_F_EC_POINTS_MAKE_AFFINE, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_POINTs_mul()
int EC_POINTs_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * n, size_t num, const EC_POINT * p[], const BIGNUM * m[], BN_CTX * ctx)
Computes r = generator * n + sum_{i=0}^{num-1} p[i] * m[i]
Parameters
group underlying EC_GROUP object
r EC_POINT object for the result
n BIGNUM with the multiplier for the group generator (optional)
num number further summands
p array of size num of EC_POINT objects
m array of size num of BIGNUM objects
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 914 of file ec_lib.c.
References ec_wNAF_mul().
Referenced by EC_POINT_mul().
ECDH_compute_key()
int ECDH_compute_key (void * out, size_t outlen, const EC_POINT * pub_key, const EC_KEY * ecdh, void *(*)(const void *in, size_t inlen, void *out, size_t *outlen) KDF)
Definition at line 127 of file ec_kmeth.c.
ECDH_KDF_X9_62()
int ECDH_KDF_X9_62 (unsigned char * out, size_t outlen, const unsigned char * Z, size_t Zlen, const unsigned char * sinfo, size_t sinfolen, const EVP_MD * md)
Definition at line 18 of file ecdh_kdf.c.
ECDSA_do_sign()
ECDSA_SIG* ECDSA_do_sign (const unsigned char * dgst, int dgst_len, EC_KEY * eckey)
Computes the ECDSA signature of the given hash value using the supplied private key and returns the created signature.
Parameters
dgst pointer to the hash value
dgst_len length of the hash value
eckey EC_KEY object containing a private EC key
Returns
pointer to a ECDSA_SIG structure or NULL if an error occurred
Definition at line 14 of file ecdsa_sign.c.
References ECDSA_do_sign_ex(), and NULL.
ECDSA_do_sign_ex()
ECDSA_SIG* ECDSA_do_sign_ex (const unsigned char * dgst, int dgstlen, const BIGNUM * kinv, const BIGNUM * rp, EC_KEY * eckey)
Computes ECDSA signature of a given hash value using the supplied private key (note: sig must point to ECDSA_size(eckey) bytes of memory).
Parameters
dgst pointer to the hash value to sign
dgstlen length of the hash value
kinv BIGNUM with a pre-computed inverse k (optional)
rp BIGNUM with a pre-computed rp value (optional), see ECDSA_sign_setup
eckey EC_KEY object containing a private EC key
Returns
pointer to a ECDSA_SIG structure or NULL if an error occurred
Definition at line 19 of file ecdsa_sign.c.
References EC_F_ECDSA_DO_SIGN_EX, EC_R_OPERATION_NOT_SUPPORTED, ECerr, and NULL.
Referenced by ECDSA_do_sign(), and ossl_ecdsa_sign().
ECDSA_do_verify()
int ECDSA_do_verify (const unsigned char * dgst, int dgst_len, const ECDSA_SIG * sig, EC_KEY * eckey)
Verifies that the supplied signature is a valid ECDSA signature of the supplied hash value using the supplied public key.
Parameters
dgst pointer to the hash value
dgst_len length of the hash value
sig ECDSA_SIG structure
eckey EC_KEY object containing a public EC key
Returns
1 if the signature is valid, 0 if the signature is invalid and -1 on error
Definition at line 20 of file ecdsa_vrf.c.
References EC_F_ECDSA_DO_VERIFY, EC_R_OPERATION_NOT_SUPPORTED, ECerr, and NULL.
ECDSA_SIG_free()
void ECDSA_SIG_free (ECDSA_SIG * sig)
frees a ECDSA_SIG structure
Parameters
sig pointer to the ECDSA_SIG structure
Referenced by ossl_ecdsa_sign().
ECDSA_SIG_get0()
void ECDSA_SIG_get0 (const ECDSA_SIG * sig, const BIGNUM ** pr, const BIGNUM ** ps)
Accessor for r and s fields of ECDSA_SIG
Parameters
sig pointer to ECDSA_SIG pointer
pr pointer to BIGNUM pointer for r (may be NULL)
ps pointer to BIGNUM pointer for s (may be NULL)
ECDSA_SIG_new()
ECDSA_SIG* ECDSA_SIG_new (void)
Allocates and initialize a ECDSA_SIG structure
Returns
pointer to a ECDSA_SIG structure or NULL if an error occurred
ECDSA_SIG_set0()
int ECDSA_SIG_set0 (ECDSA_SIG * sig, BIGNUM * r, BIGNUM * s)
Setter for r and s fields of ECDSA_SIG
Parameters
sig pointer to ECDSA_SIG pointer
r pointer to BIGNUM for r (may be NULL)
s pointer to BIGNUM for s (may be NULL)
ECDSA_sign()
int ECDSA_sign (int type, const unsigned char * dgst, int dgstlen, unsigned char * sig, unsigned int * siglen, EC_KEY * eckey)
Computes ECDSA signature of a given hash value using the supplied private key (note: sig must point to ECDSA_size(eckey) bytes of memory).
Parameters
type this parameter is ignored
dgst pointer to the hash value to sign
dgstlen length of the hash value
sig memory for the DER encoded created signature
siglen pointer to the length of the returned signature
eckey EC_KEY object containing a private EC key
Returns
1 on success and 0 otherwise
Definition at line 29 of file ecdsa_sign.c.
References ECDSA_sign_ex(), and NULL.
ECDSA_sign_ex()
int ECDSA_sign_ex (int type, const unsigned char * dgst, int dgstlen, unsigned char * sig, unsigned int * siglen, const BIGNUM * kinv, const BIGNUM * rp, EC_KEY * eckey)
Computes ECDSA signature of a given hash value using the supplied private key (note: sig must point to ECDSA_size(eckey) bytes of memory).
Parameters
type this parameter is ignored
dgst pointer to the hash value to sign
dgstlen length of the hash value
sig buffer to hold the DER encoded signature
siglen pointer to the length of the returned signature
kinv BIGNUM with a pre-computed inverse k (optional)
rp BIGNUM with a pre-computed rp value (optional), see ECDSA_sign_setup
eckey EC_KEY object containing a private EC key
Returns
1 on success and 0 otherwise
Definition at line 35 of file ecdsa_sign.c.
References EC_F_ECDSA_SIGN_EX, EC_R_OPERATION_NOT_SUPPORTED, ECerr, and NULL.
Referenced by ECDSA_sign().
ECDSA_sign_setup()
int ECDSA_sign_setup (EC_KEY * eckey, BN_CTX * ctx, BIGNUM ** kinv, BIGNUM ** rp)
Precompute parts of the signing operation
Parameters
eckey EC_KEY object containing a private EC key
ctx BN_CTX object (optional)
kinv BIGNUM pointer for the inverse of k
rp BIGNUM pointer for x coordinate of k * generator
Returns
1 on success and 0 otherwise
Definition at line 45 of file ecdsa_sign.c.
References EC_F_ECDSA_SIGN_SETUP, EC_R_OPERATION_NOT_SUPPORTED, ECerr, and NULL.
ECDSA_size()
int ECDSA_size (const EC_KEY * eckey)
Returns the maximum length of the DER encoded signature
Parameters
eckey EC_KEY object
Returns
numbers of bytes required for the DER encoded signature
ECDSA_verify()
int ECDSA_verify (int type, const unsigned char * dgst, int dgstlen, const unsigned char * sig, int siglen, EC_KEY * eckey)
Verifies that the given signature is valid ECDSA signature of the supplied hash value using the specified public key.
Parameters
type this parameter is ignored
dgst pointer to the hash value
dgstlen length of the hash value
sig pointer to the DER encoded signature
siglen length of the DER encoded signature
eckey EC_KEY object containing a public EC key
Returns
1 if the signature is valid, 0 if the signature is invalid and -1 on error
Definition at line 35 of file ecdsa_vrf.c.
References EC_F_ECDSA_VERIFY, EC_R_OPERATION_NOT_SUPPORTED, ECerr, and NULL.
ECParameters_print()
int ECParameters_print (BIO * bp, const EC_KEY * key)
Prints out the ec parameters on human readable form.
Parameters
bp BIO object to which the information is printed
key EC_KEY object
Returns
1 on success and 0 if an error occurred
Definition at line 561 of file ec_ameth.c.
ECParameters_print_fp()
int ECParameters_print_fp (FILE * fp, const EC_KEY * key)
Prints out the ec parameters on human readable form.
Parameters
fp file descriptor to which the information is printed
key EC_KEY object
Returns
1 on success and 0 if an error occurred
Definition at line 53 of file eck_prn.c.
ECPKParameters_print()
int ECPKParameters_print (BIO * bp, const EC_GROUP * x, int off)
Definition at line 72 of file eck_prn.c.
ECPKParameters_print_fp()
int ECPKParameters_print_fp (FILE * fp, const EC_GROUP * x, int off)
Definition at line 23 of file eck_prn.c.
ERR_load_EC_strings()
int ERR_load_EC_strings (void)
Definition at line 280 of file ec_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
i2d_ECDSA_SIG()
int i2d_ECDSA_SIG (const ECDSA_SIG * sig, unsigned char ** pp)
DER encode content of ECDSA_SIG object (note: this function modifies *pp (*pp += length of the DER encoded signature)).
Parameters
sig pointer to the ECDSA_SIG object
pp pointer to a unsigned char pointer for the output or NULL
Returns
the length of the DER encoded ECDSA_SIG object or 0
Referenced by ossl_ecdsa_sign().
i2d_ECParameters()
int i2d_ECParameters (EC_KEY * key, unsigned char ** out)
Encodes ec parameter and stores the result in a buffer.
Parameters
key the EC_KEY object with ec parameters to encode
out the buffer for the result (if NULL the function returns number of bytes needed).
Returns
1 on success and 0 if an error occurred.
Definition at line 1066 of file ec_asn1.c.
i2d_ECPKParameters()
int i2d_ECPKParameters (const EC_GROUP * , unsigned char ** out)
Definition at line 896 of file ec_asn1.c.
i2d_ECPrivateKey()
int i2d_ECPrivateKey (EC_KEY * key, unsigned char ** out)
Encodes a private key object and stores the result in a buffer.
Parameters
key the EC_KEY object to encode
out the buffer for the result (if NULL the function returns number of bytes needed).
Returns
1 on success and 0 if an error occurred.
Definition at line 994 of file ec_asn1.c.
Referenced by i2d_ECPrivateKey_bio(), and i2d_ECPrivateKey_fp().
i2o_ECPublicKey()
int i2o_ECPublicKey (const EC_KEY * key, unsigned char ** out)
Encodes a ec public key in an octet string.
Parameters
key the EC_KEY object with the public key
out the buffer for the result (if NULL the function returns number of bytes needed).
Returns
1 on success and 0 if an error occurred
Definition at line 1125 of file ec_asn1.c.
Referenced by i2d_PublicKey().
o2i_ECPublicKey()
EC_KEY* o2i_ECPublicKey (EC_KEY ** key, const unsigned char ** in, long len)
Decodes a ec public key from a octet string.
Parameters
key a pointer to a EC_KEY object which should be used
in memory buffer with the encoded public key
len length of the encoded public key
Returns
EC_KEY object with decoded public key or NULL if an error occurred.
Definition at line 1105 of file ec_asn1.c.