crypto/ec/ec_asn1.c File Reference
ec_asn1.c File Reference
#include <string.h>
#include "ec_lcl.h"
#include <openssl/err.h>
#include <openssl/asn1t.h>
#include <openssl/objects.h>
Data Structures
struct X9_62_PENTANOMIAL
struct X9_62_CHARACTERISTIC_TWO
struct X9_62_FIELDID
struct X9_62_CURVE
struct ECPARAMETERS
struct ECPKPARAMETERS
struct EC_PRIVATEKEY
Functions
int EC_GROUP_get_basis_type (const EC_GROUP *group)
int EC_GROUP_get_trinomial_basis (const EC_GROUP *group, unsigned int *k)
int EC_GROUP_get_pentanomial_basis (const EC_GROUP *group, unsigned int *k1, unsigned int *k2, unsigned int *k3)
ASN1_SEQUENCE (X9_62_PENTANOMIAL)
ASN1_ADB (X9_62_CHARACTERISTIC_TWO)
ASN1_SEQUENCE (X9_62_CHARACTERISTIC_TWO)
ASN1_ADB (X9_62_FIELDID)
ASN1_SEQUENCE (X9_62_FIELDID)
ECPARAMETERS * EC_GROUP_get_ecparameters (const EC_GROUP *group, ECPARAMETERS *params)
ECPKPARAMETERS * EC_GROUP_get_ecpkparameters (const EC_GROUP *group, ECPKPARAMETERS *params)
EC_GROUP * EC_GROUP_new_from_ecparameters (const ECPARAMETERS *params)
EC_GROUP * EC_GROUP_new_from_ecpkparameters (const ECPKPARAMETERS *params)
EC_GROUP * d2i_ECPKParameters (EC_GROUP **a, const unsigned char **in, long len)
int i2d_ECPKParameters (const EC_GROUP *a, unsigned char **out)
EC_KEY * d2i_ECPrivateKey (EC_KEY **a, const unsigned char **in, long len)
int i2d_ECPrivateKey (EC_KEY *a, unsigned char **out)
int i2d_ECParameters (EC_KEY *a, unsigned char **out)
EC_KEY * d2i_ECParameters (EC_KEY **a, const unsigned char **in, long len)
EC_KEY * o2i_ECPublicKey (EC_KEY **a, const unsigned char **in, long len)
int i2o_ECPublicKey (const EC_KEY *a, unsigned char **out)
Function Documentation
ASN1_ADB() [1/2]
ASN1_ADB (X9_62_CHARACTERISTIC_TWO)
ASN1_ADB() [2/2]
ASN1_ADB (X9_62_FIELDID)
ASN1_SEQUENCE() [1/3]
ASN1_SEQUENCE (X9_62_PENTANOMIAL)
ASN1_SEQUENCE() [2/3]
ASN1_SEQUENCE (X9_62_CHARACTERISTIC_TWO)
ASN1_SEQUENCE() [3/3]
ASN1_SEQUENCE (X9_62_FIELDID)
d2i_ECParameters()
EC_KEY* d2i_ECParameters (EC_KEY ** key, const unsigned char ** in, long len)
Decodes ec parameter from a memory buffer.
Parameters
key a pointer to a EC_KEY object which should be used (or NULL)
in pointer to memory with the DER encoded ec parameters
len length of the DER encoded ec parameters
Returns
a EC_KEY object with the decoded parameters or NULL if an error occurred.
Definition at line 1075 of file ec_asn1.c.
d2i_ECPKParameters()
EC_GROUP* d2i_ECPKParameters (EC_GROUP ** a, const unsigned char ** in, long len)
Definition at line 868 of file ec_asn1.c.
References EC_F_D2I_ECPKPARAMETERS, EC_GROUP_clear_free(), EC_GROUP_new_from_ecpkparameters(), EC_R_D2I_ECPKPARAMETERS_FAILURE, EC_R_PKPARAMETERS2GROUP_FAILURE, ECerr, in, and NULL.
d2i_ECPrivateKey()
EC_KEY* d2i_ECPrivateKey (EC_KEY ** key, const unsigned char ** in, long len)
Decodes a private key from a memory buffer.
Parameters
key a pointer to a EC_KEY object which should be used (or NULL)
in pointer to memory with the DER encoded private key
len length of the DER encoded private key
Returns
the decoded private key or NULL if an error occurred.
Definition at line 915 of file ec_asn1.c.
Referenced by d2i_ECPrivateKey_bio(), and d2i_ECPrivateKey_fp().
EC_GROUP_get_basis_type()
int EC_GROUP_get_basis_type (const EC_GROUP * group)
Definition at line 16 of file ec_asn1.c.
References EC_GROUP_method_of(), EC_METHOD_get_field_type(), NID_X9_62_characteristic_two_field, NID_X9_62_ppBasis, and NID_X9_62_tpBasis.
EC_GROUP_get_ecparameters()
ECPARAMETERS* EC_GROUP_get_ecparameters (const EC_GROUP * group, ECPARAMETERS * params)
Creates an ECPARAMETERS object for the the given EC_GROUP object.
Parameters
group pointer to the EC_GROUP object
params pointer to an existing ECPARAMETERS object or NULL
Returns
pointer to the new ECPARAMETERS object or NULL if an error occurred.
Definition at line 468 of file ec_asn1.c.
References len.
EC_GROUP_get_ecpkparameters()
ECPKPARAMETERS* EC_GROUP_get_ecpkparameters (const EC_GROUP * group, ECPKPARAMETERS * params)
Creates an ECPKPARAMETERS object for the the given EC_GROUP object.
Parameters
group pointer to the EC_GROUP object
params pointer to an existing ECPKPARAMETERS object or NULL
Returns
pointer to the new ECPKPARAMETERS object or NULL if an error occurred.
Definition at line 551 of file ec_asn1.c.
EC_GROUP_get_pentanomial_basis()
int EC_GROUP_get_pentanomial_basis (const EC_GROUP * group, unsigned int * k1, unsigned int * k2, unsigned int * k3)
Definition at line 58 of file ec_asn1.c.
References EC_F_EC_GROUP_GET_PENTANOMIAL_BASIS, EC_GROUP_method_of(), EC_METHOD_get_field_type(), ECerr, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, NID_X9_62_characteristic_two_field, and NULL.
EC_GROUP_get_trinomial_basis()
int EC_GROUP_get_trinomial_basis (const EC_GROUP * group, unsigned int * k)
Definition at line 38 of file ec_asn1.c.
EC_GROUP_new_from_ecparameters()
EC_GROUP* EC_GROUP_new_from_ecparameters (const ECPARAMETERS * params)
Creates a new EC_GROUP object from an ECPARAMETERS object
Parameters
params pointer to the ECPARAMETERS object
Returns
newly created EC_GROUP object with specified curve or NULL if an error occurred
Definition at line 596 of file ec_asn1.c.
EC_GROUP_new_from_ecpkparameters()
EC_GROUP* EC_GROUP_new_from_ecpkparameters (const ECPKPARAMETERS * params)
Creates a new EC_GROUP object from an ECPKPARAMETERS object
Parameters
params pointer to an existing ECPKPARAMETERS object, or NULL
Returns
newly created EC_GROUP object with specified curve, or NULL if an error occurred
Definition at line 830 of file ec_asn1.c.
Referenced by d2i_ECPKParameters().
i2d_ECParameters()
int i2d_ECParameters (EC_KEY * key, unsigned char ** out)
Encodes ec parameter and stores the result in a buffer.
Parameters
key the EC_KEY object with ec parameters to encode
out the buffer for the result (if NULL the function returns number of bytes needed).
Returns
1 on success and 0 if an error occurred.
Definition at line 1066 of file ec_asn1.c.
i2d_ECPKParameters()
int i2d_ECPKParameters (const EC_GROUP * a, unsigned char ** out)
Definition at line 896 of file ec_asn1.c.
i2d_ECPrivateKey()
int i2d_ECPrivateKey (EC_KEY * key, unsigned char ** out)
Encodes a private key object and stores the result in a buffer.
Parameters
key the EC_KEY object to encode
out the buffer for the result (if NULL the function returns number of bytes needed).
Returns
1 on success and 0 if an error occurred.
Definition at line 994 of file ec_asn1.c.
Referenced by i2d_ECPrivateKey_bio(), and i2d_ECPrivateKey_fp().
i2o_ECPublicKey()
int i2o_ECPublicKey (const EC_KEY * key, unsigned char ** out)
Encodes a ec public key in an octet string.
Parameters
key the EC_KEY object with the public key
out the buffer for the result (if NULL the function returns number of bytes needed).
Returns
1 on success and 0 if an error occurred
Definition at line 1125 of file ec_asn1.c.
Referenced by i2d_PublicKey().
o2i_ECPublicKey()
EC_KEY* o2i_ECPublicKey (EC_KEY ** key, const unsigned char ** in, long len)
Decodes a ec public key from a octet string.
Parameters
key a pointer to a EC_KEY object which should be used
in memory buffer with the encoded public key
len length of the encoded public key
Returns
EC_KEY object with decoded public key or NULL if an error occurred.
Definition at line 1105 of file ec_asn1.c.