crypto/ec/ec_mult.c File Reference
ec_mult.c File Reference
#include <string.h>
#include <openssl/err.h>
#include "internal/cryptlib.h"
#include "internal/bn_int.h"
#include "ec_lcl.h"
Data Structures
struct EC_PRE_COMP
Macros
#define EC_window_bits_for_scalar_size(b)
Functions
EC_PRE_COMP * EC_ec_pre_comp_dup (EC_PRE_COMP *pre)
void EC_ec_pre_comp_free (EC_PRE_COMP *pre)
int ec_wNAF_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *scalar, size_t num, const EC_POINT *points[], const BIGNUM *scalars[], BN_CTX *ctx)
int ec_wNAF_precompute_mult (EC_GROUP *group, BN_CTX *ctx)
int ec_wNAF_have_precompute_mult (const EC_GROUP *group)
Macro Definition Documentation
EC_window_bits_for_scalar_size
#define EC_window_bits_for_scalar_size (b)
Value:
((size_t) \
                 ((b) >= 2000 ? 6 : \
                  (b) >=  800 ? 5 : \
                  (b) >=  300 ? 4 : \
                  (b) >=   70 ? 3 : \
                  (b) >=   20 ? 2 : \
                  1))
Definition at line 109 of file ec_mult.c.
Function Documentation
EC_ec_pre_comp_dup()
EC_PRE_COMP* EC_ec_pre_comp_dup (EC_PRE_COMP * pre)
Definition at line 72 of file ec_mult.c.
References CRYPTO_UP_REF, and NULL.
Referenced by EC_GROUP_copy().
EC_ec_pre_comp_free()
void EC_ec_pre_comp_free (EC_PRE_COMP * pre)
Definition at line 80 of file ec_mult.c.
References CRYPTO_DOWN_REF, CRYPTO_THREAD_lock_free(), EC_POINT_free(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by EC_pre_comp_free().
ec_wNAF_have_precompute_mult()
int ec_wNAF_have_precompute_mult (const EC_GROUP * group)
Definition at line 677 of file ec_mult.c.
References HAVEPRECOMP.
Referenced by ec_GF2m_have_precompute_mult(), and EC_GROUP_have_precompute_mult().
ec_wNAF_mul()
int ec_wNAF_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * scalar, size_t num, const EC_POINT * points[], const BIGNUM * scalars[], BN_CTX * ctx)
Definition at line 125 of file ec_mult.c.
References EC_PRE_COMP::blocksize, generator, NULL, and EC_PRE_COMP::numblocks.
Referenced by ec_GF2m_simple_mul(), and EC_POINTs_mul().
ec_wNAF_precompute_mult()
int ec_wNAF_precompute_mult (EC_GROUP * group, BN_CTX * ctx)
Definition at line 524 of file ec_mult.c.
References generator, and NULL.
Referenced by ec_GF2m_precompute_mult(), and EC_GROUP_precompute_mult().