crypto/ec/ec_oct.c File Reference
ec_oct.c File Reference
#include <string.h>
#include <openssl/err.h>
#include <openssl/opensslv.h>
#include "ec_lcl.h"
Functions
int EC_POINT_set_compressed_coordinates_GFp (const EC_GROUP *group, EC_POINT *point, const BIGNUM *x, int y_bit, BN_CTX *ctx)
int EC_POINT_set_compressed_coordinates_GF2m (const EC_GROUP *group, EC_POINT *point, const BIGNUM *x, int y_bit, BN_CTX *ctx)
size_t EC_POINT_point2oct (const EC_GROUP *group, const EC_POINT *point, point_conversion_form_t form, unsigned char *buf, size_t len, BN_CTX *ctx)
int EC_POINT_oct2point (const EC_GROUP *group, EC_POINT *point, const unsigned char *buf, size_t len, BN_CTX *ctx)
size_t EC_POINT_point2buf (const EC_GROUP *group, const EC_POINT *point, point_conversion_form_t form, unsigned char **pbuf, BN_CTX *ctx)
Function Documentation
EC_POINT_oct2point()
int EC_POINT_oct2point (const EC_GROUP * group, EC_POINT * p, const unsigned char * buf, size_t len, BN_CTX * ctx)
Decodes a EC_POINT from a octet string
Parameters
group underlying EC_GROUP object
p EC_POINT object
buf memory buffer with the encoded ec point
len length of the encoded ec point
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 118 of file ec_oct.c.
EC_POINT_point2buf()
size_t EC_POINT_point2buf (const EC_GROUP * group, const EC_POINT * point, point_conversion_form_t form, unsigned char ** pbuf, BN_CTX * ctx)
Encodes an EC_POINT object to an allocated octet string
Parameters
group underlying EC_GROUP object
point EC_POINT object
form point conversion form
pbuf returns pointer to allocated buffer
len length of the memory buffer
ctx BN_CTX object (optional)
Returns
the length of the encoded octet string or 0 if an error occurred
Definition at line 146 of file ec_oct.c.
References len.
Referenced by EC_KEY_key2buf().
EC_POINT_point2oct()
size_t EC_POINT_point2oct (const EC_GROUP * group, const EC_POINT * p, point_conversion_form_t form, unsigned char * buf, size_t len, BN_CTX * ctx)
Encodes a EC_POINT object to a octet string
Parameters
group underlying EC_GROUP object
p EC_POINT object
form point conversion form
buf memory buffer for the result. If NULL the function returns required buffer size.
len length of the memory buffer
ctx BN_CTX object (optional)
Returns
the length of the encoded octet string or 0 if an error occurred
Definition at line 87 of file ec_oct.c.
EC_POINT_set_compressed_coordinates_GF2m()
int EC_POINT_set_compressed_coordinates_GF2m (const EC_GROUP * group, EC_POINT * p, const BIGNUM * x, int y_bit, BN_CTX * ctx)
Sets the x9.62 compressed coordinates of a EC_POINT over GF2m
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM with x-coordinate
y_bit integer with the y-Bit (either 0 or 1)
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 59 of file ec_oct.c.
References EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GF2M, EC_FLAGS_DEFAULT_OCT, ec_GF2m_simple_set_compressed_coordinates(), ec_GFp_simple_set_compressed_coordinates(), EC_R_INCOMPATIBLE_OBJECTS, ECerr, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, and NID_X9_62_prime_field.
EC_POINT_set_compressed_coordinates_GFp()
int EC_POINT_set_compressed_coordinates_GFp (const EC_GROUP * group, EC_POINT * p, const BIGNUM * x, int y_bit, BN_CTX * ctx)
Sets the x9.62 compressed coordinates of a EC_POINT over GFp
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM with x-coordinate
y_bit integer with the y-Bit (either 0 or 1)
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 23 of file ec_oct.c.
References EC_F_EC_POINT_SET_COMPRESSED_COORDINATES_GFP, EC_FLAGS_DEFAULT_OCT, ec_GF2m_simple_set_compressed_coordinates(), ec_GFp_simple_set_compressed_coordinates(), EC_R_GF2M_NOT_SUPPORTED, EC_R_INCOMPATIBLE_OBJECTS, ECerr, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, and NID_X9_62_prime_field.