crypto/ec/ec_key.c File Reference
ec_key.c File Reference
#include <internal/cryptlib.h>
#include <string.h>
#include "ec_lcl.h"
#include <openssl/err.h>
#include <openssl/engine.h>
Functions
EC_KEY * EC_KEY_new (void)
EC_KEY * EC_KEY_new_by_curve_name (int nid)
void EC_KEY_free (EC_KEY *r)
EC_KEY * EC_KEY_copy (EC_KEY *dest, const EC_KEY *src)
EC_KEY * EC_KEY_dup (const EC_KEY *ec_key)
int EC_KEY_up_ref (EC_KEY *r)
int EC_KEY_generate_key (EC_KEY *eckey)
int ossl_ec_key_gen (EC_KEY *eckey)
int ec_key_simple_generate_key (EC_KEY *eckey)
int ec_key_simple_generate_public_key (EC_KEY *eckey)
int EC_KEY_check_key (const EC_KEY *eckey)
int ec_key_simple_check_key (const EC_KEY *eckey)
int EC_KEY_set_public_key_affine_coordinates (EC_KEY *key, BIGNUM *x, BIGNUM *y)
const EC_GROUP * EC_KEY_get0_group (const EC_KEY *key)
int EC_KEY_set_group (EC_KEY *key, const EC_GROUP *group)
const BIGNUM * EC_KEY_get0_private_key (const EC_KEY *key)
int EC_KEY_set_private_key (EC_KEY *key, const BIGNUM *priv_key)
const EC_POINT * EC_KEY_get0_public_key (const EC_KEY *key)
int EC_KEY_set_public_key (EC_KEY *key, const EC_POINT *pub_key)
unsigned int EC_KEY_get_enc_flags (const EC_KEY *key)
void EC_KEY_set_enc_flags (EC_KEY *key, unsigned int flags)
point_conversion_form_t EC_KEY_get_conv_form (const EC_KEY *key)
void EC_KEY_set_conv_form (EC_KEY *key, point_conversion_form_t cform)
void EC_KEY_set_asn1_flag (EC_KEY *key, int flag)
int EC_KEY_precompute_mult (EC_KEY *key, BN_CTX *ctx)
int EC_KEY_get_flags (const EC_KEY *key)
void EC_KEY_set_flags (EC_KEY *key, int flags)
void EC_KEY_clear_flags (EC_KEY *key, int flags)
size_t EC_KEY_key2buf (const EC_KEY *key, point_conversion_form_t form, unsigned char **pbuf, BN_CTX *ctx)
int EC_KEY_oct2key (EC_KEY *key, const unsigned char *buf, size_t len, BN_CTX *ctx)
size_t EC_KEY_priv2oct (const EC_KEY *eckey, unsigned char *buf, size_t len)
size_t ec_key_simple_priv2oct (const EC_KEY *eckey, unsigned char *buf, size_t len)
int EC_KEY_oct2priv (EC_KEY *eckey, const unsigned char *buf, size_t len)
int ec_key_simple_oct2priv (EC_KEY *eckey, const unsigned char *buf, size_t len)
size_t EC_KEY_priv2buf (const EC_KEY *eckey, unsigned char **pbuf)
int EC_KEY_can_sign (const EC_KEY *eckey)
Function Documentation
EC_KEY_can_sign()
int EC_KEY_can_sign (const EC_KEY * eckey)
Indicates if an EC_KEY can be used for signing.
Parameters
key the EC_KEY object
Returns
1 if can can sign and 0 otherwise.
Definition at line 631 of file ec_key.c.
References EC_FLAGS_NO_SIGN, and NULL.
EC_KEY_check_key()
int EC_KEY_check_key (const EC_KEY * key)
Verifies that a private and/or public key is valid.
Parameters
key the EC_KEY object
Returns
1 on success and 0 otherwise.
Definition at line 255 of file ec_key.c.
References EC_F_EC_KEY_CHECK_KEY, ECerr, ERR_R_PASSED_NULL_PARAMETER, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, and NULL.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_KEY_clear_flags()
void EC_KEY_clear_flags (EC_KEY * key, int flags)
Definition at line 513 of file ec_key.c.
EC_KEY_copy()
EC_KEY* EC_KEY_copy (EC_KEY * dst, const EC_KEY * src)
Copies a EC_KEY object.
Parameters
dst destination EC_KEY object
src src EC_KEY object
Returns
dst or NULL if an error occurred.
Definition at line 77 of file ec_key.c.
References BN_copy(), BN_new(), CRYPTO_dup_ex_data(), CRYPTO_EX_INDEX_EC_KEY, EC_F_EC_KEY_COPY, EC_GROUP_copy(), EC_GROUP_free(), EC_GROUP_method_of(), EC_GROUP_new(), EC_POINT_copy(), EC_POINT_free(), EC_POINT_new(), ECerr, ENGINE_finish(), ENGINE_init(), ERR_R_PASSED_NULL_PARAMETER, and NULL.
EC_KEY_dup()
EC_KEY* EC_KEY_dup (const EC_KEY * src)
Creates a new EC_KEY object and copies the content from src to it.
Parameters
src the source EC_KEY object
Returns
newly created EC_KEY object or NULL if an error occurred.
Definition at line 154 of file ec_key.c.
EC_KEY_free()
void EC_KEY_free (EC_KEY * key)
Frees a EC_KEY object.
Parameters
key EC_KEY object to be freed.
Definition at line 45 of file ec_key.c.
References BN_clear_free(), CRYPTO_DOWN_REF, CRYPTO_EX_INDEX_EC_KEY, CRYPTO_free_ex_data(), CRYPTO_THREAD_lock_free(), EC_GROUP_free(), EC_POINT_free(), ENGINE_finish(), NULL, OPENSSL_clear_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by ssl_print_tmp_key().
EC_KEY_generate_key()
int EC_KEY_generate_key (EC_KEY * key)
Creates a new ec private (and optional a new public) key.
Parameters
key EC_KEY object
Returns
1 on success and 0 if an error occurred.
Definition at line 180 of file ec_key.c.
References EC_F_EC_KEY_GENERATE_KEY, EC_R_OPERATION_NOT_SUPPORTED, ECerr, ERR_R_PASSED_NULL_PARAMETER, and NULL.
EC_KEY_get0_group()
const EC_GROUP* EC_KEY_get0_group (const EC_KEY * key)
Returns the EC_GROUP object of a EC_KEY object
Parameters
key EC_KEY object
Returns
the EC_GROUP object (possibly NULL).
Definition at line 419 of file ec_key.c.
Referenced by ssl3_ctx_ctrl(), and ssl_print_tmp_key().
EC_KEY_get0_private_key()
const BIGNUM* EC_KEY_get0_private_key (const EC_KEY * key)
Returns the private key of a EC_KEY object.
Parameters
key EC_KEY object
Returns
a BIGNUM with the private key (possibly NULL).
Definition at line 433 of file ec_key.c.
Referenced by EC_KEY_print().
EC_KEY_get0_public_key()
const EC_POINT* EC_KEY_get0_public_key (const EC_KEY * key)
Returns the public key of a EC_KEY object.
Parameters
key the EC_KEY object
Returns
a EC_POINT object with the public key (possibly NULL)
Definition at line 453 of file ec_key.c.
EC_KEY_get_conv_form()
point_conversion_form_t EC_KEY_get_conv_form (const EC_KEY * key)
Definition at line 478 of file ec_key.c.
EC_KEY_get_enc_flags()
unsigned int EC_KEY_get_enc_flags (const EC_KEY * key)
Definition at line 468 of file ec_key.c.
EC_KEY_get_flags()
int EC_KEY_get_flags (const EC_KEY * key)
Definition at line 503 of file ec_key.c.
EC_KEY_key2buf()
size_t EC_KEY_key2buf (const EC_KEY * key, point_conversion_form_t form, unsigned char ** pbuf, BN_CTX * ctx)
Encodes an EC_KEY public key to an allocated octet string
Parameters
key key to encode
form point conversion form
pbuf returns pointer to allocated buffer
len length of the memory buffer
ctx BN_CTX object (optional)
Returns
the length of the encoded octet string or 0 if an error occurred
Definition at line 518 of file ec_key.c.
References EC_POINT_point2buf(), and NULL.
EC_KEY_new()
EC_KEY* EC_KEY_new (void)
Creates a new EC_KEY object.
Returns
EC_KEY object or NULL if an error occurred.
Definition at line 22 of file ec_key.c.
References EC_KEY_new_method(), and NULL.
Referenced by d2i_EC_PUBKEY_bio(), d2i_EC_PUBKEY_fp(), d2i_ECPrivateKey_bio(), and d2i_ECPrivateKey_fp().
EC_KEY_new_by_curve_name()
EC_KEY* EC_KEY_new_by_curve_name (int nid)
Creates a new EC_KEY object using a named curve as underlying EC_GROUP object.
Parameters
nid NID of the named curve.
Returns
EC_KEY object or NULL if an error occurred.
Definition at line 27 of file ec_key.c.
EC_KEY_oct2key()
int EC_KEY_oct2key (EC_KEY * key, const unsigned char * buf, size_t len, BN_CTX * ctx)
Decodes a EC_KEY public key from a octet string
Parameters
key key to decode
buf memory buffer with the encoded ec point
len length of the encoded ec point
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 526 of file ec_key.c.
EC_KEY_oct2priv()
int EC_KEY_oct2priv (EC_KEY * key, const unsigned char * buf, size_t len)
Decodes an EC_KEY private key from an octet string
Parameters
key key to decode
buf memory buffer with the encoded private key
len length of the encoded key
Returns
1 on success and 0 if an error occurred
Definition at line 585 of file ec_key.c.
EC_KEY_precompute_mult()
int EC_KEY_precompute_mult (EC_KEY * key, BN_CTX * ctx)
Creates a table of pre-computed multiples of the generator to accelerate further EC_KEY operations.
Parameters
key EC_KEY object
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred.
Definition at line 496 of file ec_key.c.
References EC_GROUP_precompute_mult(), and NULL.
EC_KEY_priv2buf()
size_t EC_KEY_priv2buf (const EC_KEY * eckey, unsigned char ** pbuf)
Encodes an EC_KEY private key to an allocated octet string
Parameters
key key to encode
pbuf returns pointer to allocated buffer
Returns
the length of the encoded octet string or 0 if an error occurred
Definition at line 612 of file ec_key.c.
References len.
EC_KEY_priv2oct()
size_t EC_KEY_priv2oct (const EC_KEY * key, unsigned char * buf, size_t len)
Encodes a EC_KEY private key to an octet string
Parameters
key key to encode
buf memory buffer for the result. If NULL the function returns required buffer size.
len length of the memory buffer
Returns
the length of the encoded octet string or 0 if an error occurred
Definition at line 549 of file ec_key.c.
EC_KEY_set_asn1_flag()
void EC_KEY_set_asn1_flag (EC_KEY * key, int flag)
Definition at line 490 of file ec_key.c.
EC_KEY_set_conv_form()
void EC_KEY_set_conv_form (EC_KEY * key, point_conversion_form_t cform)
Definition at line 483 of file ec_key.c.
References EC_GROUP_set_point_conversion_form(), and NULL.
EC_KEY_set_enc_flags()
void EC_KEY_set_enc_flags (EC_KEY * key, unsigned int flags)
Definition at line 473 of file ec_key.c.
References flags.
EC_KEY_set_flags()
void EC_KEY_set_flags (EC_KEY * key, int flags)
Definition at line 508 of file ec_key.c.
References flags.
EC_KEY_set_group()
int EC_KEY_set_group (EC_KEY * key, const EC_GROUP * group)
Sets the EC_GROUP of a EC_KEY object.
Parameters
key EC_KEY object
group EC_GROUP to use in the EC_KEY object (note: the EC_KEY object will use an own copy of the EC_GROUP).
Returns
1 on success and 0 if an error occurred.
Definition at line 424 of file ec_key.c.
References EC_GROUP_dup(), EC_GROUP_free(), and NULL.
EC_KEY_set_private_key()
int EC_KEY_set_private_key (EC_KEY * key, const BIGNUM * prv)
Sets the private key of a EC_KEY object.
Parameters
key EC_KEY object
prv BIGNUM with the private key (note: the EC_KEY object will use an own copy of the BIGNUM).
Returns
1 on success and 0 if an error occurred.
Definition at line 438 of file ec_key.c.
References BN_clear_free(), BN_dup(), and NULL.
EC_KEY_set_public_key()
int EC_KEY_set_public_key (EC_KEY * key, const EC_POINT * pub)
Sets the public key of a EC_KEY object.
Parameters
key EC_KEY object
pub EC_POINT object with the public key (note: the EC_KEY object will use an own copy of the EC_POINT object).
Returns
1 on success and 0 if an error occurred.
Definition at line 458 of file ec_key.c.
References EC_POINT_dup(), EC_POINT_free(), and NULL.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_KEY_set_public_key_affine_coordinates()
int EC_KEY_set_public_key_affine_coordinates (EC_KEY * key, BIGNUM * x, BIGNUM * y)
Sets a public key from affine coordinates performing necessary NIST PKV tests.
Parameters
key the EC_KEY object
x public key x coordinate
y public key y coordinate
Returns
1 on success and 0 otherwise.
Definition at line 337 of file ec_key.c.
References BN_cmp(), BN_CTX_end(), BN_CTX_free(), BN_CTX_get(), BN_CTX_new(), BN_CTX_start(), ctx, EC_F_EC_KEY_SET_PUBLIC_KEY_AFFINE_COORDINATES, EC_GROUP_method_of(), EC_KEY_check_key(), EC_KEY_set_public_key(), EC_METHOD_get_field_type(), EC_POINT_free(), EC_POINT_get_affine_coordinates_GF2m(), EC_POINT_get_affine_coordinates_GFp(), EC_POINT_new(), EC_POINT_set_affine_coordinates_GF2m(), EC_POINT_set_affine_coordinates_GFp(), EC_R_COORDINATES_OUT_OF_RANGE, ECerr, ERR_R_PASSED_NULL_PARAMETER, NID_X9_62_characteristic_two_field, and NULL.
ec_key_simple_check_key()
int ec_key_simple_check_key (const EC_KEY * eckey)
Definition at line 270 of file ec_key.c.
References ctx, and NULL.
ec_key_simple_generate_key()
int ec_key_simple_generate_key (EC_KEY * eckey)
Definition at line 198 of file ec_key.c.
References ctx, and NULL.
ec_key_simple_generate_public_key()
int ec_key_simple_generate_public_key (EC_KEY * eckey)
Definition at line 249 of file ec_key.c.
References EC_POINT_mul(), and NULL.
ec_key_simple_oct2priv()
int ec_key_simple_oct2priv (EC_KEY * eckey, const unsigned char * buf, size_t len)
Definition at line 596 of file ec_key.c.
ec_key_simple_priv2oct()
size_t ec_key_simple_priv2oct (const EC_KEY * eckey, unsigned char * buf, size_t len)
Definition at line 562 of file ec_key.c.
EC_KEY_up_ref()
int EC_KEY_up_ref (EC_KEY * key)
Increases the internal reference count of a EC_KEY object.
Parameters
key EC_KEY object
Returns
1 on success and 0 if an error occurred.
Definition at line 168 of file ec_key.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
ossl_ec_key_gen()
int ossl_ec_key_gen (EC_KEY * eckey)
Definition at line 192 of file ec_key.c.
References NULL, and OPENSSL_assert.