crypto/ec/ec_lcl.h File Reference
ec_lcl.h File Reference
#include <stdlib.h>
#include <openssl/obj_mac.h>
#include <openssl/ec.h>
#include <openssl/bn.h>
#include "internal/refcount.h"
#include "e_os.h"
Data Structures
struct EC_METHOD
struct EC_GROUP
struct EC_KEY
struct EC_POINT
struct EC_KEY_METHOD
struct ECDSA_SIG
Macros
#define EC_FLAGS_DEFAULT_OCT 0x1
#define EC_FLAGS_CUSTOM_CURVE 0x2
#define EC_FLAGS_NO_SIGN 0x4
#define SETPRECOMP(g, type, pre) g->pre_comp_type = PCT_##type, g->pre_comp.type = pre
#define HAVEPRECOMP(g, type) g->pre_comp_type == PCT_##type && g->pre_comp.type != NULL
#define EC_KEY_METHOD_DYNAMIC 1
Functions
NISTP224_PRE_COMP * EC_nistp224_pre_comp_dup (NISTP224_PRE_COMP *)
NISTP256_PRE_COMP * EC_nistp256_pre_comp_dup (NISTP256_PRE_COMP *)
NISTP521_PRE_COMP * EC_nistp521_pre_comp_dup (NISTP521_PRE_COMP *)
NISTZ256_PRE_COMP * EC_nistz256_pre_comp_dup (NISTZ256_PRE_COMP *)
EC_PRE_COMP * EC_ec_pre_comp_dup (EC_PRE_COMP *)
void EC_pre_comp_free (EC_GROUP *group)
void EC_nistp224_pre_comp_free (NISTP224_PRE_COMP *)
void EC_nistp256_pre_comp_free (NISTP256_PRE_COMP *)
void EC_nistp521_pre_comp_free (NISTP521_PRE_COMP *)
void EC_nistz256_pre_comp_free (NISTZ256_PRE_COMP *)
void EC_ec_pre_comp_free (EC_PRE_COMP *)
int ec_wNAF_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *scalar, size_t num, const EC_POINT *points[], const BIGNUM *scalars[], BN_CTX *)
int ec_wNAF_precompute_mult (EC_GROUP *group, BN_CTX *)
int ec_wNAF_have_precompute_mult (const EC_GROUP *group)
int ec_GFp_simple_group_init (EC_GROUP *)
void ec_GFp_simple_group_finish (EC_GROUP *)
void ec_GFp_simple_group_clear_finish (EC_GROUP *)
int ec_GFp_simple_group_copy (EC_GROUP *, const EC_GROUP *)
int ec_GFp_simple_group_set_curve (EC_GROUP *, const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *)
int ec_GFp_simple_group_get_curve (const EC_GROUP *, BIGNUM *p, BIGNUM *a, BIGNUM *b, BN_CTX *)
int ec_GFp_simple_group_get_degree (const EC_GROUP *)
int ec_GFp_simple_group_check_discriminant (const EC_GROUP *, BN_CTX *)
int ec_GFp_simple_point_init (EC_POINT *)
void ec_GFp_simple_point_finish (EC_POINT *)
void ec_GFp_simple_point_clear_finish (EC_POINT *)
int ec_GFp_simple_point_copy (EC_POINT *, const EC_POINT *)
int ec_GFp_simple_point_set_to_infinity (const EC_GROUP *, EC_POINT *)
int ec_GFp_simple_set_Jprojective_coordinates_GFp (const EC_GROUP *, EC_POINT *, const BIGNUM *x, const BIGNUM *y, const BIGNUM *z, BN_CTX *)
int ec_GFp_simple_get_Jprojective_coordinates_GFp (const EC_GROUP *, const EC_POINT *, BIGNUM *x, BIGNUM *y, BIGNUM *z, BN_CTX *)
int ec_GFp_simple_point_set_affine_coordinates (const EC_GROUP *, EC_POINT *, const BIGNUM *x, const BIGNUM *y, BN_CTX *)
int ec_GFp_simple_point_get_affine_coordinates (const EC_GROUP *, const EC_POINT *, BIGNUM *x, BIGNUM *y, BN_CTX *)
int ec_GFp_simple_set_compressed_coordinates (const EC_GROUP *, EC_POINT *, const BIGNUM *x, int y_bit, BN_CTX *)
size_t ec_GFp_simple_point2oct (const EC_GROUP *, const EC_POINT *, point_conversion_form_t form, unsigned char *buf, size_t len, BN_CTX *)
int ec_GFp_simple_oct2point (const EC_GROUP *, EC_POINT *, const unsigned char *buf, size_t len, BN_CTX *)
int ec_GFp_simple_add (const EC_GROUP *, EC_POINT *r, const EC_POINT *a, const EC_POINT *b, BN_CTX *)
int ec_GFp_simple_dbl (const EC_GROUP *, EC_POINT *r, const EC_POINT *a, BN_CTX *)
int ec_GFp_simple_invert (const EC_GROUP *, EC_POINT *, BN_CTX *)
int ec_GFp_simple_is_at_infinity (const EC_GROUP *, const EC_POINT *)
int ec_GFp_simple_is_on_curve (const EC_GROUP *, const EC_POINT *, BN_CTX *)
int ec_GFp_simple_cmp (const EC_GROUP *, const EC_POINT *a, const EC_POINT *b, BN_CTX *)
int ec_GFp_simple_make_affine (const EC_GROUP *, EC_POINT *, BN_CTX *)
int ec_GFp_simple_points_make_affine (const EC_GROUP *, size_t num, EC_POINT *[], BN_CTX *)
int ec_GFp_simple_field_mul (const EC_GROUP *, BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_CTX *)
int ec_GFp_simple_field_sqr (const EC_GROUP *, BIGNUM *r, const BIGNUM *a, BN_CTX *)
int ec_GFp_mont_group_init (EC_GROUP *)
int ec_GFp_mont_group_set_curve (EC_GROUP *, const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *)
void ec_GFp_mont_group_finish (EC_GROUP *)
void ec_GFp_mont_group_clear_finish (EC_GROUP *)
int ec_GFp_mont_group_copy (EC_GROUP *, const EC_GROUP *)
int ec_GFp_mont_field_mul (const EC_GROUP *, BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_CTX *)
int ec_GFp_mont_field_sqr (const EC_GROUP *, BIGNUM *r, const BIGNUM *a, BN_CTX *)
int ec_GFp_mont_field_encode (const EC_GROUP *, BIGNUM *r, const BIGNUM *a, BN_CTX *)
int ec_GFp_mont_field_decode (const EC_GROUP *, BIGNUM *r, const BIGNUM *a, BN_CTX *)
int ec_GFp_mont_field_set_to_one (const EC_GROUP *, BIGNUM *r, BN_CTX *)
int ec_GFp_nist_group_copy (EC_GROUP *dest, const EC_GROUP *src)
int ec_GFp_nist_group_set_curve (EC_GROUP *, const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *)
int ec_GFp_nist_field_mul (const EC_GROUP *, BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_CTX *)
int ec_GFp_nist_field_sqr (const EC_GROUP *, BIGNUM *r, const BIGNUM *a, BN_CTX *)
int ec_GF2m_simple_group_init (EC_GROUP *)
void ec_GF2m_simple_group_finish (EC_GROUP *)
void ec_GF2m_simple_group_clear_finish (EC_GROUP *)
int ec_GF2m_simple_group_copy (EC_GROUP *, const EC_GROUP *)
int ec_GF2m_simple_group_set_curve (EC_GROUP *, const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *)
int ec_GF2m_simple_group_get_curve (const EC_GROUP *, BIGNUM *p, BIGNUM *a, BIGNUM *b, BN_CTX *)
int ec_GF2m_simple_group_get_degree (const EC_GROUP *)
int ec_GF2m_simple_group_check_discriminant (const EC_GROUP *, BN_CTX *)
int ec_GF2m_simple_point_init (EC_POINT *)
void ec_GF2m_simple_point_finish (EC_POINT *)
void ec_GF2m_simple_point_clear_finish (EC_POINT *)
int ec_GF2m_simple_point_copy (EC_POINT *, const EC_POINT *)
int ec_GF2m_simple_point_set_to_infinity (const EC_GROUP *, EC_POINT *)
int ec_GF2m_simple_point_set_affine_coordinates (const EC_GROUP *, EC_POINT *, const BIGNUM *x, const BIGNUM *y, BN_CTX *)
int ec_GF2m_simple_point_get_affine_coordinates (const EC_GROUP *, const EC_POINT *, BIGNUM *x, BIGNUM *y, BN_CTX *)
int ec_GF2m_simple_set_compressed_coordinates (const EC_GROUP *, EC_POINT *, const BIGNUM *x, int y_bit, BN_CTX *)
size_t ec_GF2m_simple_point2oct (const EC_GROUP *, const EC_POINT *, point_conversion_form_t form, unsigned char *buf, size_t len, BN_CTX *)
int ec_GF2m_simple_oct2point (const EC_GROUP *, EC_POINT *, const unsigned char *buf, size_t len, BN_CTX *)
int ec_GF2m_simple_add (const EC_GROUP *, EC_POINT *r, const EC_POINT *a, const EC_POINT *b, BN_CTX *)
int ec_GF2m_simple_dbl (const EC_GROUP *, EC_POINT *r, const EC_POINT *a, BN_CTX *)
int ec_GF2m_simple_invert (const EC_GROUP *, EC_POINT *, BN_CTX *)
int ec_GF2m_simple_is_at_infinity (const EC_GROUP *, const EC_POINT *)
int ec_GF2m_simple_is_on_curve (const EC_GROUP *, const EC_POINT *, BN_CTX *)
int ec_GF2m_simple_cmp (const EC_GROUP *, const EC_POINT *a, const EC_POINT *b, BN_CTX *)
int ec_GF2m_simple_make_affine (const EC_GROUP *, EC_POINT *, BN_CTX *)
int ec_GF2m_simple_points_make_affine (const EC_GROUP *, size_t num, EC_POINT *[], BN_CTX *)
int ec_GF2m_simple_field_mul (const EC_GROUP *, BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_CTX *)
int ec_GF2m_simple_field_sqr (const EC_GROUP *, BIGNUM *r, const BIGNUM *a, BN_CTX *)
int ec_GF2m_simple_field_div (const EC_GROUP *, BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_CTX *)
int ec_GF2m_simple_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *scalar, size_t num, const EC_POINT *points[], const BIGNUM *scalars[], BN_CTX *)
int ec_GF2m_precompute_mult (EC_GROUP *group, BN_CTX *ctx)
int ec_GF2m_have_precompute_mult (const EC_GROUP *group)
int ec_GFp_nistp224_group_init (EC_GROUP *group)
int ec_GFp_nistp224_group_set_curve (EC_GROUP *group, const BIGNUM *p, const BIGNUM *a, const BIGNUM *n, BN_CTX *)
int ec_GFp_nistp224_point_get_affine_coordinates (const EC_GROUP *group, const EC_POINT *point, BIGNUM *x, BIGNUM *y, BN_CTX *ctx)
int ec_GFp_nistp224_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *scalar, size_t num, const EC_POINT *points[], const BIGNUM *scalars[], BN_CTX *)
int ec_GFp_nistp224_points_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *scalar, size_t num, const EC_POINT *points[], const BIGNUM *scalars[], BN_CTX *ctx)
int ec_GFp_nistp224_precompute_mult (EC_GROUP *group, BN_CTX *ctx)
int ec_GFp_nistp224_have_precompute_mult (const EC_GROUP *group)
int ec_GFp_nistp256_group_init (EC_GROUP *group)
int ec_GFp_nistp256_group_set_curve (EC_GROUP *group, const BIGNUM *p, const BIGNUM *a, const BIGNUM *n, BN_CTX *)
int ec_GFp_nistp256_point_get_affine_coordinates (const EC_GROUP *group, const EC_POINT *point, BIGNUM *x, BIGNUM *y, BN_CTX *ctx)
int ec_GFp_nistp256_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *scalar, size_t num, const EC_POINT *points[], const BIGNUM *scalars[], BN_CTX *)
int ec_GFp_nistp256_points_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *scalar, size_t num, const EC_POINT *points[], const BIGNUM *scalars[], BN_CTX *ctx)
int ec_GFp_nistp256_precompute_mult (EC_GROUP *group, BN_CTX *ctx)
int ec_GFp_nistp256_have_precompute_mult (const EC_GROUP *group)
int ec_GFp_nistp521_group_init (EC_GROUP *group)
int ec_GFp_nistp521_group_set_curve (EC_GROUP *group, const BIGNUM *p, const BIGNUM *a, const BIGNUM *n, BN_CTX *)
int ec_GFp_nistp521_point_get_affine_coordinates (const EC_GROUP *group, const EC_POINT *point, BIGNUM *x, BIGNUM *y, BN_CTX *ctx)
int ec_GFp_nistp521_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *scalar, size_t num, const EC_POINT *points[], const BIGNUM *scalars[], BN_CTX *)
int ec_GFp_nistp521_points_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *scalar, size_t num, const EC_POINT *points[], const BIGNUM *scalars[], BN_CTX *ctx)
int ec_GFp_nistp521_precompute_mult (EC_GROUP *group, BN_CTX *ctx)
int ec_GFp_nistp521_have_precompute_mult (const EC_GROUP *group)
void ec_GFp_nistp_points_make_affine_internal (size_t num, void *point_array, size_t felem_size, void *tmp_felems, void(*felem_one)(void *out), int(*felem_is_zero)(const void *in), void(*felem_assign)(void *out, const void *in), void(*felem_square)(void *out, const void *in), void(*felem_mul)(void *out, const void *in1, const void *in2), void(*felem_inv)(void *out, const void *in), void(*felem_contract)(void *out, const void *in))
void ec_GFp_nistp_recode_scalar_bits (unsigned char *sign, unsigned char *digit, unsigned char in)
int ec_precompute_mont_data (EC_GROUP *)
int ec_group_simple_order_bits (const EC_GROUP *group)
size_t ec_key_simple_priv2oct (const EC_KEY *eckey, unsigned char *buf, size_t len)
int ec_key_simple_oct2priv (EC_KEY *eckey, const unsigned char *buf, size_t len)
int ec_key_simple_generate_key (EC_KEY *eckey)
int ec_key_simple_generate_public_key (EC_KEY *eckey)
int ec_key_simple_check_key (const EC_KEY *eckey)
int ossl_ec_key_gen (EC_KEY *eckey)
int ossl_ecdh_compute_key (unsigned char **pout, size_t *poutlen, const EC_POINT *pub_key, const EC_KEY *ecdh)
int ecdh_simple_compute_key (unsigned char **pout, size_t *poutlen, const EC_POINT *pub_key, const EC_KEY *ecdh)
int ossl_ecdsa_sign_setup (EC_KEY *eckey, BN_CTX *ctx_in, BIGNUM **kinvp, BIGNUM **rp)
int ossl_ecdsa_sign (int type, const unsigned char *dgst, int dlen, unsigned char *sig, unsigned int *siglen, const BIGNUM *kinv, const BIGNUM *r, EC_KEY *eckey)
ECDSA_SIG * ossl_ecdsa_sign_sig (const unsigned char *dgst, int dgst_len, const BIGNUM *in_kinv, const BIGNUM *in_r, EC_KEY *eckey)
int ossl_ecdsa_verify (int type, const unsigned char *dgst, int dgst_len, const unsigned char *sigbuf, int sig_len, EC_KEY *eckey)
int ossl_ecdsa_verify_sig (const unsigned char *dgst, int dgst_len, const ECDSA_SIG *sig, EC_KEY *eckey)
int X25519 (uint8_t out_shared_key[32], const uint8_t private_key[32], const uint8_t peer_public_value[32])
void X25519_public_from_private (uint8_t out_public_value[32], const uint8_t private_key[32])
Macro Definition Documentation
EC_FLAGS_CUSTOM_CURVE
#define EC_FLAGS_CUSTOM_CURVE 0x2
Definition at line 43 of file ec_lcl.h.
Referenced by EC_GROUP_copy().
EC_FLAGS_DEFAULT_OCT
#define EC_FLAGS_DEFAULT_OCT 0x1
Definition at line 40 of file ec_lcl.h.
Referenced by EC_GFp_nistz256_method(), EC_POINT_set_compressed_coordinates_GF2m(), and EC_POINT_set_compressed_coordinates_GFp().
EC_FLAGS_NO_SIGN
#define EC_FLAGS_NO_SIGN 0x4
Definition at line 46 of file ec_lcl.h.
Referenced by EC_KEY_can_sign().
EC_KEY_METHOD_DYNAMIC
#define EC_KEY_METHOD_DYNAMIC 1
Definition at line 585 of file ec_lcl.h.
Referenced by EC_KEY_METHOD_free().
HAVEPRECOMP
#define HAVEPRECOMP (g, type) g->pre_comp_type == PCT_##type && g->pre_comp.type != NULL
Definition at line 253 of file ec_lcl.h.
Referenced by ec_GFp_nistp224_have_precompute_mult(), ec_GFp_nistp256_have_precompute_mult(), ec_GFp_nistp521_have_precompute_mult(), and ec_wNAF_have_precompute_mult().
SETPRECOMP
#define SETPRECOMP (g, type, pre) g->pre_comp_type = PCT_##type, g->pre_comp.type = pre
Definition at line 251 of file ec_lcl.h.
Function Documentation
EC_ec_pre_comp_dup()
EC_PRE_COMP* EC_ec_pre_comp_dup (EC_PRE_COMP *)
Definition at line 72 of file ec_mult.c.
References CRYPTO_UP_REF, and NULL.
Referenced by EC_GROUP_copy().
EC_ec_pre_comp_free()
void EC_ec_pre_comp_free (EC_PRE_COMP *)
Definition at line 80 of file ec_mult.c.
References CRYPTO_DOWN_REF, CRYPTO_THREAD_lock_free(), EC_POINT_free(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by EC_pre_comp_free().
ec_GF2m_have_precompute_mult()
int ec_GF2m_have_precompute_mult (const EC_GROUP * group)
Definition at line 413 of file ec2_mult.c.
References ec_wNAF_have_precompute_mult().
ec_GF2m_precompute_mult()
int ec_GF2m_precompute_mult (EC_GROUP * group, BN_CTX * ctx)
Definition at line 408 of file ec2_mult.c.
References ec_wNAF_precompute_mult().
ec_GF2m_simple_add()
int ec_GF2m_simple_add (const EC_GROUP * , EC_POINT * r, const EC_POINT * a, const EC_POINT * b, BN_CTX *)
Definition at line 423 of file ec2_smpl.c.
References NULL, and t.
Referenced by ec_GF2m_simple_dbl().
ec_GF2m_simple_cmp()
int ec_GF2m_simple_cmp (const EC_GROUP * , const EC_POINT * a, const EC_POINT * b, BN_CTX *)
Definition at line 634 of file ec2_smpl.c.
References NULL.
ec_GF2m_simple_dbl()
int ec_GF2m_simple_dbl (const EC_GROUP * , EC_POINT * r, const EC_POINT * a, BN_CTX *)
Definition at line 538 of file ec2_smpl.c.
References ec_GF2m_simple_add().
ec_GF2m_simple_field_div()
int ec_GF2m_simple_field_div (const EC_GROUP * , BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_CTX *)
Definition at line 752 of file ec2_smpl.c.
References BN_GF2m_mod_div().
ec_GF2m_simple_field_mul()
int ec_GF2m_simple_field_mul (const EC_GROUP * , BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_CTX *)
Definition at line 738 of file ec2_smpl.c.
References BN_GF2m_mod_mul_arr().
ec_GF2m_simple_field_sqr()
int ec_GF2m_simple_field_sqr (const EC_GROUP * , BIGNUM * r, const BIGNUM * a, BN_CTX *)
Definition at line 745 of file ec2_smpl.c.
References BN_GF2m_mod_sqr_arr().
ec_GF2m_simple_group_check_discriminant()
int ec_GF2m_simple_group_check_discriminant (const EC_GROUP * , BN_CTX *)
Definition at line 248 of file ec2_smpl.c.
ec_GF2m_simple_group_clear_finish()
void ec_GF2m_simple_group_clear_finish (EC_GROUP *)
Definition at line 126 of file ec2_smpl.c.
References BN_clear_free().
ec_GF2m_simple_group_copy()
int ec_GF2m_simple_group_copy (EC_GROUP * , const EC_GROUP *)
Definition at line 143 of file ec2_smpl.c.
References BN_BITS2, BN_copy(), bn_set_all_zero(), bn_wexpand(), and NULL.
ec_GF2m_simple_group_finish()
void ec_GF2m_simple_group_finish (EC_GROUP *)
Definition at line 115 of file ec2_smpl.c.
References BN_free().
ec_GF2m_simple_group_get_curve()
int ec_GF2m_simple_group_get_curve (const EC_GROUP * , BIGNUM * p, BIGNUM * a, BIGNUM * b, BN_CTX *)
Definition at line 209 of file ec2_smpl.c.
ec_GF2m_simple_group_get_degree()
int ec_GF2m_simple_group_get_degree (const EC_GROUP *)
Definition at line 239 of file ec2_smpl.c.
References BN_num_bits().
ec_GF2m_simple_group_init()
int ec_GF2m_simple_group_init (EC_GROUP *)
Definition at line 96 of file ec2_smpl.c.
References BN_free(), BN_new(), and NULL.
ec_GF2m_simple_group_set_curve()
int ec_GF2m_simple_group_set_curve (EC_GROUP * , const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX *)
Definition at line 169 of file ec2_smpl.c.
ec_GF2m_simple_invert()
int ec_GF2m_simple_invert (const EC_GROUP * , EC_POINT * , BN_CTX *)
Definition at line 544 of file ec2_smpl.c.
References BN_GF2m_add(), BN_is_zero(), EC_POINT_is_at_infinity(), and EC_POINT_make_affine().
ec_GF2m_simple_is_at_infinity()
int ec_GF2m_simple_is_at_infinity (const EC_GROUP * , const EC_POINT *)
Definition at line 556 of file ec2_smpl.c.
References BN_is_zero().
ec_GF2m_simple_is_on_curve()
int ec_GF2m_simple_is_on_curve (const EC_GROUP * , const EC_POINT * , BN_CTX *)
Definition at line 567 of file ec2_smpl.c.
ec_GF2m_simple_make_affine()
int ec_GF2m_simple_make_affine (const EC_GROUP * , EC_POINT * , BN_CTX *)
Definition at line 680 of file ec2_smpl.c.
References NULL.
ec_GF2m_simple_mul()
int ec_GF2m_simple_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * scalar, size_t num, const EC_POINT * points[], const BIGNUM * scalars[], BN_CTX *)
Definition at line 332 of file ec2_mult.c.
References BN_CTX_new(), EC_GROUP_have_precompute_mult(), EC_POINT_new(), EC_POINT_set_to_infinity(), ec_wNAF_mul(), and NULL.
ec_GF2m_simple_oct2point()
int ec_GF2m_simple_oct2point (const EC_GROUP * , EC_POINT * , const unsigned char * buf, size_t len, BN_CTX *)
Definition at line 249 of file ec2_oct.c.
ec_GF2m_simple_point2oct()
size_t ec_GF2m_simple_point2oct (const EC_GROUP * , const EC_POINT * , point_conversion_form_t form, unsigned char * buf, size_t len, BN_CTX *)
Definition at line 127 of file ec2_oct.c.
ec_GF2m_simple_point_clear_finish()
void ec_GF2m_simple_point_clear_finish (EC_POINT *)
Definition at line 312 of file ec2_smpl.c.
References BN_clear_free().
ec_GF2m_simple_point_copy()
int ec_GF2m_simple_point_copy (EC_POINT * , const EC_POINT *)
Definition at line 324 of file ec2_smpl.c.
References BN_copy().
ec_GF2m_simple_point_finish()
void ec_GF2m_simple_point_finish (EC_POINT *)
Definition at line 304 of file ec2_smpl.c.
References BN_free().
ec_GF2m_simple_point_get_affine_coordinates()
int ec_GF2m_simple_point_get_affine_coordinates (const EC_GROUP * , const EC_POINT * , BIGNUM * x, BIGNUM * y, BN_CTX *)
Definition at line 385 of file ec2_smpl.c.
ec_GF2m_simple_point_init()
int ec_GF2m_simple_point_init (EC_POINT *)
Definition at line 288 of file ec2_smpl.c.
References BN_free(), BN_new(), and NULL.
ec_GF2m_simple_point_set_affine_coordinates()
int ec_GF2m_simple_point_set_affine_coordinates (const EC_GROUP * , EC_POINT * , const BIGNUM * x, const BIGNUM * y, BN_CTX *)
Definition at line 353 of file ec2_smpl.c.
ec_GF2m_simple_point_set_to_infinity()
int ec_GF2m_simple_point_set_to_infinity (const EC_GROUP * , EC_POINT *)
Definition at line 341 of file ec2_smpl.c.
References BN_zero.
ec_GF2m_simple_points_make_affine()
int ec_GF2m_simple_points_make_affine (const EC_GROUP * , size_t num, EC_POINT * [], BN_CTX *)
Definition at line 724 of file ec2_smpl.c.
ec_GF2m_simple_set_compressed_coordinates()
int ec_GF2m_simple_set_compressed_coordinates (const EC_GROUP * , EC_POINT * , const BIGNUM * x, int y_bit, BN_CTX *)
Definition at line 47 of file ec2_oct.c.
References NULL.
Referenced by EC_POINT_set_compressed_coordinates_GF2m(), and EC_POINT_set_compressed_coordinates_GFp().
ec_GFp_mont_field_decode()
int ec_GFp_mont_field_decode (const EC_GROUP * , BIGNUM * r, const BIGNUM * a, BN_CTX *)
Definition at line 220 of file ecp_mont.c.
References BN_from_montgomery(), EC_F_EC_GFP_MONT_FIELD_DECODE, EC_R_NOT_INITIALIZED, ECerr, and NULL.
ec_GFp_mont_field_encode()
int ec_GFp_mont_field_encode (const EC_GROUP * , BIGNUM * r, const BIGNUM * a, BN_CTX *)
Definition at line 209 of file ecp_mont.c.
References BN_to_montgomery(), EC_F_EC_GFP_MONT_FIELD_ENCODE, EC_R_NOT_INITIALIZED, ECerr, and NULL.
ec_GFp_mont_field_mul()
int ec_GFp_mont_field_mul (const EC_GROUP * , BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_CTX *)
Definition at line 187 of file ecp_mont.c.
References BN_mod_mul_montgomery(), EC_F_EC_GFP_MONT_FIELD_MUL, EC_R_NOT_INITIALIZED, ECerr, and NULL.
ec_GFp_mont_field_set_to_one()
int ec_GFp_mont_field_set_to_one (const EC_GROUP * , BIGNUM * r, BN_CTX *)
Definition at line 231 of file ecp_mont.c.
References BN_copy(), EC_F_EC_GFP_MONT_FIELD_SET_TO_ONE, EC_R_NOT_INITIALIZED, ECerr, and NULL.
ec_GFp_mont_field_sqr()
int ec_GFp_mont_field_sqr (const EC_GROUP * , BIGNUM * r, const BIGNUM * a, BN_CTX *)
Definition at line 198 of file ecp_mont.c.
References BN_mod_mul_montgomery(), EC_F_EC_GFP_MONT_FIELD_SQR, EC_R_NOT_INITIALIZED, ECerr, and NULL.
ec_GFp_mont_group_clear_finish()
void ec_GFp_mont_group_clear_finish (EC_GROUP *)
Definition at line 94 of file ecp_mont.c.
References BN_clear_free(), BN_MONT_CTX_free(), ec_GFp_simple_group_clear_finish(), and NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_mont_group_copy()
int ec_GFp_mont_group_copy (EC_GROUP * , const EC_GROUP *)
Definition at line 103 of file ecp_mont.c.
References BN_clear_free(), BN_dup(), BN_MONT_CTX_copy(), BN_MONT_CTX_free(), BN_MONT_CTX_new(), ec_GFp_simple_group_copy(), and NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_mont_group_finish()
void ec_GFp_mont_group_finish (EC_GROUP *)
Definition at line 85 of file ecp_mont.c.
References BN_free(), BN_MONT_CTX_free(), ec_GFp_simple_group_finish(), and NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_mont_group_init()
int ec_GFp_mont_group_init (EC_GROUP *)
Definition at line 75 of file ecp_mont.c.
References ec_GFp_simple_group_init(), and NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_mont_group_set_curve()
int ec_GFp_mont_group_set_curve (EC_GROUP * , const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX *)
Definition at line 134 of file ecp_mont.c.
References NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_nist_field_mul()
int ec_GFp_nist_field_mul (const EC_GROUP * , BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_CTX *)
Definition at line 119 of file ecp_nist.c.
ec_GFp_nist_field_sqr()
int ec_GFp_nist_field_sqr (const EC_GROUP * , BIGNUM * r, const BIGNUM * a, BN_CTX *)
Definition at line 144 of file ecp_nist.c.
ec_GFp_nist_group_copy()
int ec_GFp_nist_group_copy (EC_GROUP * dest, const EC_GROUP * src)
Definition at line 77 of file ecp_nist.c.
References ec_GFp_simple_group_copy().
ec_GFp_nist_group_set_curve()
int ec_GFp_nist_group_set_curve (EC_GROUP * , const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX *)
Definition at line 84 of file ecp_nist.c.
ec_GFp_nistp224_group_init()
int ec_GFp_nistp224_group_init (EC_GROUP * group)
Definition at line 1268 of file ecp_nistp224.c.
ec_GFp_nistp224_group_set_curve()
int ec_GFp_nistp224_group_set_curve (EC_GROUP * group, const BIGNUM * p, const BIGNUM * a, const BIGNUM * n, BN_CTX *)
Definition at line 1276 of file ecp_nistp224.c.
ec_GFp_nistp224_have_precompute_mult()
int ec_GFp_nistp224_have_precompute_mult (const EC_GROUP * group)
Definition at line 1712 of file ecp_nistp224.c.
References HAVEPRECOMP.
ec_GFp_nistp224_mul()
int ec_GFp_nistp224_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * scalar, size_t num, const EC_POINT * points[], const BIGNUM * scalars[], BN_CTX *)
ec_GFp_nistp224_point_get_affine_coordinates()
int ec_GFp_nistp224_point_get_affine_coordinates (const EC_GROUP * group, const EC_POINT * point, BIGNUM * x, BIGNUM * y, BN_CTX * ctx)
Definition at line 1312 of file ecp_nistp224.c.
References EC_F_EC_GFP_NISTP224_POINT_GET_AFFINE_COORDINATES, EC_POINT_is_at_infinity(), EC_R_POINT_AT_INFINITY, and ECerr.
ec_GFp_nistp224_points_mul()
int ec_GFp_nistp224_points_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * scalar, size_t num, const EC_POINT * points[], const BIGNUM * scalars[], BN_CTX * ctx)
Definition at line 1390 of file ecp_nistp224.c.
ec_GFp_nistp224_precompute_mult()
int ec_GFp_nistp224_precompute_mult (EC_GROUP * group, BN_CTX * ctx)
Definition at line 1587 of file ecp_nistp224.c.
ec_GFp_nistp256_group_init()
int ec_GFp_nistp256_group_init (EC_GROUP * group)
Definition at line 1884 of file ecp_nistp256.c.
ec_GFp_nistp256_group_set_curve()
int ec_GFp_nistp256_group_set_curve (EC_GROUP * group, const BIGNUM * p, const BIGNUM * a, const BIGNUM * n, BN_CTX *)
Definition at line 1892 of file ecp_nistp256.c.
ec_GFp_nistp256_have_precompute_mult()
int ec_GFp_nistp256_have_precompute_mult (const EC_GROUP * group)
Definition at line 2346 of file ecp_nistp256.c.
References HAVEPRECOMP.
ec_GFp_nistp256_mul()
int ec_GFp_nistp256_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * scalar, size_t num, const EC_POINT * points[], const BIGNUM * scalars[], BN_CTX *)
ec_GFp_nistp256_point_get_affine_coordinates()
int ec_GFp_nistp256_point_get_affine_coordinates (const EC_GROUP * group, const EC_POINT * point, BIGNUM * x, BIGNUM * y, BN_CTX * ctx)
Definition at line 1928 of file ecp_nistp256.c.
References EC_F_EC_GFP_NISTP256_POINT_GET_AFFINE_COORDINATES, EC_POINT_is_at_infinity(), EC_R_POINT_AT_INFINITY, and ECerr.
ec_GFp_nistp256_points_mul()
int ec_GFp_nistp256_points_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * scalar, size_t num, const EC_POINT * points[], const BIGNUM * scalars[], BN_CTX * ctx)
Definition at line 2007 of file ecp_nistp256.c.
ec_GFp_nistp256_precompute_mult()
int ec_GFp_nistp256_precompute_mult (EC_GROUP * group, BN_CTX * ctx)
Definition at line 2210 of file ecp_nistp256.c.
ec_GFp_nistp521_group_init()
int ec_GFp_nistp521_group_init (EC_GROUP * group)
Definition at line 1713 of file ecp_nistp521.c.
ec_GFp_nistp521_group_set_curve()
int ec_GFp_nistp521_group_set_curve (EC_GROUP * group, const BIGNUM * p, const BIGNUM * a, const BIGNUM * n, BN_CTX *)
Definition at line 1721 of file ecp_nistp521.c.
ec_GFp_nistp521_have_precompute_mult()
int ec_GFp_nistp521_have_precompute_mult (const EC_GROUP * group)
Definition at line 2141 of file ecp_nistp521.c.
References HAVEPRECOMP.
ec_GFp_nistp521_mul()
int ec_GFp_nistp521_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * scalar, size_t num, const EC_POINT * points[], const BIGNUM * scalars[], BN_CTX *)
ec_GFp_nistp521_point_get_affine_coordinates()
int ec_GFp_nistp521_point_get_affine_coordinates (const EC_GROUP * group, const EC_POINT * point, BIGNUM * x, BIGNUM * y, BN_CTX * ctx)
Definition at line 1757 of file ecp_nistp521.c.
References EC_F_EC_GFP_NISTP521_POINT_GET_AFFINE_COORDINATES, EC_POINT_is_at_infinity(), EC_R_POINT_AT_INFINITY, and ECerr.
ec_GFp_nistp521_points_mul()
int ec_GFp_nistp521_points_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * scalar, size_t num, const EC_POINT * points[], const BIGNUM * scalars[], BN_CTX * ctx)
Definition at line 1836 of file ecp_nistp521.c.
ec_GFp_nistp521_precompute_mult()
int ec_GFp_nistp521_precompute_mult (EC_GROUP * group, BN_CTX * ctx)
Definition at line 2036 of file ecp_nistp521.c.
ec_GFp_nistp_points_make_affine_internal()
void ec_GFp_nistp_points_make_affine_internal (size_t num, void * point_array, size_t felem_size, void * tmp_felems, void(*)(void *out) felem_one, int(*)(const void *in) felem_is_zero, void(*)(void *out, const void *in) felem_assign, void(*)(void *out, const void *in) felem_square, void(*)(void *out, const void *in1, const void *in2) felem_mul, void(*)(void *out, const void *in) felem_inv, void(*)(void *out, const void *in) felem_contract)
Definition at line 49 of file ecp_nistputil.c.
ec_GFp_nistp_recode_scalar_bits()
void ec_GFp_nistp_recode_scalar_bits (unsigned char * sign, unsigned char * digit, unsigned char in)
Definition at line 209 of file ecp_nistputil.c.
ec_GFp_simple_add()
int ec_GFp_simple_add (const EC_GROUP * , EC_POINT * r, const EC_POINT * a, const EC_POINT * b, BN_CTX *)
Definition at line 608 of file ecp_smpl.c.
References NULL.
ec_GFp_simple_cmp()
int ec_GFp_simple_cmp (const EC_GROUP * , const EC_POINT * a, const EC_POINT * b, BN_CTX *)
Definition at line 1053 of file ecp_smpl.c.
References NULL.
ec_GFp_simple_dbl()
int ec_GFp_simple_dbl (const EC_GROUP * , EC_POINT * r, const EC_POINT * a, BN_CTX *)
Definition at line 794 of file ecp_smpl.c.
References NULL.
ec_GFp_simple_field_mul()
int ec_GFp_simple_field_mul (const EC_GROUP * , BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_CTX *)
Definition at line 1359 of file ecp_smpl.c.
References BN_mod_mul().
ec_GFp_simple_field_sqr()
int ec_GFp_simple_field_sqr (const EC_GROUP * , BIGNUM * r, const BIGNUM * a, BN_CTX *)
Definition at line 1365 of file ecp_smpl.c.
References BN_mod_sqr().
ec_GFp_simple_get_Jprojective_coordinates_GFp()
int ec_GFp_simple_get_Jprojective_coordinates_GFp (const EC_GROUP * , const EC_POINT * , BIGNUM * x, BIGNUM * y, BIGNUM * z, BN_CTX *)
Definition at line 427 of file ecp_smpl.c.
References NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_group_check_discriminant()
int ec_GFp_simple_group_check_discriminant (const EC_GROUP * , BN_CTX *)
Definition at line 242 of file ecp_smpl.c.
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_group_clear_finish()
void ec_GFp_simple_group_clear_finish (EC_GROUP *)
Definition at line 112 of file ecp_smpl.c.
References BN_clear_free().
Referenced by ec_GFp_mont_group_clear_finish().
ec_GFp_simple_group_copy()
int ec_GFp_simple_group_copy (EC_GROUP * , const EC_GROUP *)
Definition at line 119 of file ecp_smpl.c.
References BN_copy().
Referenced by ec_GFp_mont_group_copy(), and ec_GFp_nist_group_copy().
ec_GFp_simple_group_finish()
void ec_GFp_simple_group_finish (EC_GROUP *)
Definition at line 105 of file ecp_smpl.c.
References BN_free().
Referenced by ec_GFp_mont_group_finish().
ec_GFp_simple_group_get_curve()
int ec_GFp_simple_group_get_curve (const EC_GROUP * , BIGNUM * p, BIGNUM * a, BIGNUM * b, BN_CTX *)
Definition at line 192 of file ecp_smpl.c.
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_group_get_degree()
int ec_GFp_simple_group_get_degree (const EC_GROUP *)
Definition at line 237 of file ecp_smpl.c.
References BN_num_bits().
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_group_init()
int ec_GFp_simple_group_init (EC_GROUP *)
Definition at line 90 of file ecp_smpl.c.
References BN_free(), BN_new(), and NULL.
Referenced by ec_GFp_mont_group_init().
ec_GFp_simple_group_set_curve()
int ec_GFp_simple_group_set_curve (EC_GROUP * , const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX *)
Definition at line 133 of file ecp_smpl.c.
ec_GFp_simple_invert()
int ec_GFp_simple_invert (const EC_GROUP * , EC_POINT * , BN_CTX *)
Definition at line 936 of file ecp_smpl.c.
References BN_is_zero(), BN_usub(), and EC_POINT_is_at_infinity().
ec_GFp_simple_is_at_infinity()
int ec_GFp_simple_is_at_infinity (const EC_GROUP * , const EC_POINT *)
Definition at line 945 of file ecp_smpl.c.
References BN_is_zero().
ec_GFp_simple_is_on_curve()
int ec_GFp_simple_is_on_curve (const EC_GROUP * , const EC_POINT * , BN_CTX *)
Definition at line 950 of file ecp_smpl.c.
References NULL.
ec_GFp_simple_make_affine()
int ec_GFp_simple_make_affine (const EC_GROUP * , EC_POINT * , BN_CTX *)
Definition at line 1161 of file ecp_smpl.c.
References NULL.
ec_GFp_simple_oct2point()
int ec_GFp_simple_oct2point (const EC_GROUP * , EC_POINT * , const unsigned char * buf, size_t len, BN_CTX *)
Definition at line 274 of file ecp_oct.c.
ec_GFp_simple_point2oct()
size_t ec_GFp_simple_point2oct (const EC_GROUP * , const EC_POINT * , point_conversion_form_t form, unsigned char * buf, size_t len, BN_CTX *)
Definition at line 159 of file ecp_oct.c.
ec_GFp_simple_point_clear_finish()
void ec_GFp_simple_point_clear_finish (EC_POINT *)
Definition at line 338 of file ecp_smpl.c.
References BN_clear_free().
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_point_copy()
int ec_GFp_simple_point_copy (EC_POINT * , const EC_POINT *)
Definition at line 346 of file ecp_smpl.c.
References BN_copy().
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_point_finish()
void ec_GFp_simple_point_finish (EC_POINT *)
Definition at line 331 of file ecp_smpl.c.
References BN_free().
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_point_get_affine_coordinates()
int ec_GFp_simple_point_get_affine_coordinates (const EC_GROUP * , const EC_POINT * , BIGNUM * x, BIGNUM * y, BN_CTX *)
Definition at line 494 of file ecp_smpl.c.
References NULL, and Z.
ec_GFp_simple_point_init()
int ec_GFp_simple_point_init (EC_POINT *)
Definition at line 315 of file ecp_smpl.c.
References BN_free(), BN_new(), and NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_point_set_affine_coordinates()
int ec_GFp_simple_point_set_affine_coordinates (const EC_GROUP * , EC_POINT * , const BIGNUM * x, const BIGNUM * y, BN_CTX *)
Definition at line 476 of file ecp_smpl.c.
References BN_value_one(), EC_F_EC_GFP_SIMPLE_POINT_SET_AFFINE_COORDINATES, EC_POINT_set_Jprojective_coordinates_GFp(), ECerr, ERR_R_PASSED_NULL_PARAMETER, and NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_point_set_to_infinity()
int ec_GFp_simple_point_set_to_infinity (const EC_GROUP * , EC_POINT *)
Definition at line 359 of file ecp_smpl.c.
References BN_zero.
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_points_make_affine()
int ec_GFp_simple_points_make_affine (const EC_GROUP * , size_t num, EC_POINT * [], BN_CTX *)
Definition at line 1200 of file ecp_smpl.c.
References NULL.
ec_GFp_simple_set_compressed_coordinates()
int ec_GFp_simple_set_compressed_coordinates (const EC_GROUP * , EC_POINT * , const BIGNUM * x, int y_bit, BN_CTX *)
Definition at line 21 of file ecp_oct.c.
References NULL.
Referenced by EC_POINT_set_compressed_coordinates_GF2m(), and EC_POINT_set_compressed_coordinates_GFp().
ec_GFp_simple_set_Jprojective_coordinates_GFp()
int ec_GFp_simple_set_Jprojective_coordinates_GFp (const EC_GROUP * , EC_POINT * , const BIGNUM * x, const BIGNUM * y, const BIGNUM * z, BN_CTX *)
Definition at line 367 of file ecp_smpl.c.
References NULL.
Referenced by EC_GFp_nistz256_method().
ec_group_simple_order_bits()
int ec_group_simple_order_bits (const EC_GROUP * group)
Definition at line 1009 of file ec_lib.c.
References BN_num_bits(), and NULL.
Referenced by EC_GFp_nistz256_method().
ec_key_simple_check_key()
int ec_key_simple_check_key (const EC_KEY * eckey)
Definition at line 270 of file ec_key.c.
References ctx, and NULL.
ec_key_simple_generate_key()
int ec_key_simple_generate_key (EC_KEY * eckey)
Definition at line 198 of file ec_key.c.
References ctx, and NULL.
ec_key_simple_generate_public_key()
int ec_key_simple_generate_public_key (EC_KEY * eckey)
Definition at line 249 of file ec_key.c.
References EC_POINT_mul(), and NULL.
ec_key_simple_oct2priv()
int ec_key_simple_oct2priv (EC_KEY * eckey, const unsigned char * buf, size_t len)
Definition at line 596 of file ec_key.c.
ec_key_simple_priv2oct()
size_t ec_key_simple_priv2oct (const EC_KEY * eckey, unsigned char * buf, size_t len)
Definition at line 562 of file ec_key.c.
EC_nistp224_pre_comp_dup()
NISTP224_PRE_COMP* EC_nistp224_pre_comp_dup (NISTP224_PRE_COMP *)
Definition at line 1238 of file ecp_nistp224.c.
References CRYPTO_UP_REF, and NULL.
Referenced by EC_GROUP_copy().
EC_nistp224_pre_comp_free()
void EC_nistp224_pre_comp_free (NISTP224_PRE_COMP *)
Definition at line 1246 of file ecp_nistp224.c.
References CRYPTO_DOWN_REF, CRYPTO_THREAD_lock_free(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by EC_pre_comp_free().
EC_nistp256_pre_comp_dup()
NISTP256_PRE_COMP * EC_nistp256_pre_comp_dup (NISTP256_PRE_COMP *)
Definition at line 1854 of file ecp_nistp256.c.
References CRYPTO_UP_REF, and NULL.
Referenced by EC_GROUP_copy().
EC_nistp256_pre_comp_free()
void EC_nistp256_pre_comp_free (NISTP256_PRE_COMP *)
Definition at line 1862 of file ecp_nistp256.c.
References CRYPTO_DOWN_REF, CRYPTO_THREAD_lock_free(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by EC_pre_comp_free().
EC_nistp521_pre_comp_dup()
NISTP521_PRE_COMP* EC_nistp521_pre_comp_dup (NISTP521_PRE_COMP *)
Definition at line 1683 of file ecp_nistp521.c.
References CRYPTO_UP_REF, and NULL.
Referenced by EC_GROUP_copy().
EC_nistp521_pre_comp_free()
void EC_nistp521_pre_comp_free (NISTP521_PRE_COMP *)
Definition at line 1691 of file ecp_nistp521.c.
References CRYPTO_DOWN_REF, CRYPTO_THREAD_lock_free(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by EC_pre_comp_free().
EC_nistz256_pre_comp_dup()
NISTZ256_PRE_COMP* EC_nistz256_pre_comp_dup (NISTZ256_PRE_COMP *)
Definition at line 1476 of file ecp_nistz256.c.
References CRYPTO_UP_REF, and NULL.
Referenced by EC_GROUP_copy().
EC_nistz256_pre_comp_free()
void EC_nistz256_pre_comp_free (NISTZ256_PRE_COMP *)
Definition at line 1484 of file ecp_nistz256.c.
References CRYPTO_DOWN_REF, CRYPTO_THREAD_lock_free(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by EC_pre_comp_free().
EC_pre_comp_free()
void EC_pre_comp_free (EC_GROUP * group)
Definition at line 66 of file ec_lib.c.
References EC_ec_pre_comp_free(), EC_nistp224_pre_comp_free(), EC_nistp256_pre_comp_free(), EC_nistp521_pre_comp_free(), EC_nistz256_pre_comp_free(), and NULL.
Referenced by EC_GROUP_clear_free(), and EC_GROUP_free().
ec_precompute_mont_data()
int ec_precompute_mont_data (EC_GROUP *)
Definition at line 970 of file ec_lib.c.
References BN_CTX_new(), and ctx.
ec_wNAF_have_precompute_mult()
int ec_wNAF_have_precompute_mult (const EC_GROUP * group)
Definition at line 677 of file ec_mult.c.
References HAVEPRECOMP.
Referenced by ec_GF2m_have_precompute_mult(), and EC_GROUP_have_precompute_mult().
ec_wNAF_mul()
int ec_wNAF_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * scalar, size_t num, const EC_POINT * points[], const BIGNUM * scalars[], BN_CTX *)
Definition at line 125 of file ec_mult.c.
References EC_PRE_COMP::blocksize, generator, NULL, and EC_PRE_COMP::numblocks.
Referenced by ec_GF2m_simple_mul(), and EC_POINTs_mul().
ec_wNAF_precompute_mult()
int ec_wNAF_precompute_mult (EC_GROUP * group, BN_CTX *)
Definition at line 524 of file ec_mult.c.
References generator, and NULL.
Referenced by ec_GF2m_precompute_mult(), and EC_GROUP_precompute_mult().
ecdh_simple_compute_key()
int ecdh_simple_compute_key (unsigned char ** pout, size_t * poutlen, const EC_POINT * pub_key, const EC_KEY * ecdh)
Definition at line 52 of file ecdh_ossl.c.
References ctx, and NULL.
ossl_ec_key_gen()
int ossl_ec_key_gen (EC_KEY * eckey)
Definition at line 192 of file ec_key.c.
References NULL, and OPENSSL_assert.
ossl_ecdh_compute_key()
int ossl_ecdh_compute_key (unsigned char ** pout, size_t * poutlen, const EC_POINT * pub_key, const EC_KEY * ecdh)
Definition at line 36 of file ecdh_ossl.c.
References EC_F_OSSL_ECDH_COMPUTE_KEY, EC_R_CURVE_DOES_NOT_SUPPORT_ECDH, ECerr, and NULL.
ossl_ecdsa_sign()
int ossl_ecdsa_sign (int type, const unsigned char * dgst, int dlen, unsigned char * sig, unsigned int * siglen, const BIGNUM * kinv, const BIGNUM * r, EC_KEY * eckey)
Definition at line 18 of file ecdsa_ossl.c.
References ECDSA_do_sign_ex(), ECDSA_SIG_free(), i2d_ECDSA_SIG(), NULL, and RAND_seed().
ossl_ecdsa_sign_setup()
int ossl_ecdsa_sign_setup (EC_KEY * eckey, BN_CTX * ctx_in, BIGNUM ** kinvp, BIGNUM ** rp)
Definition at line 188 of file ecdsa_ossl.c.
ossl_ecdsa_sign_sig()
ECDSA_SIG* ossl_ecdsa_sign_sig (const unsigned char * dgst, int dgst_len, const BIGNUM * in_kinv, const BIGNUM * in_r, EC_KEY * eckey)
Definition at line 194 of file ecdsa_ossl.c.
References NULL.
ossl_ecdsa_verify()
int ossl_ecdsa_verify (int type, const unsigned char * dgst, int dgst_len, const unsigned char * sigbuf, int sig_len, EC_KEY * eckey)
Definition at line 319 of file ecdsa_ossl.c.
References NULL.
ossl_ecdsa_verify_sig()
int ossl_ecdsa_verify_sig (const unsigned char * dgst, int dgst_len, const ECDSA_SIG * sig, EC_KEY * eckey)
Definition at line 344 of file ecdsa_ossl.c.
X25519()
int X25519 (uint8_t out_shared_key[32], const uint8_t private_key[32], const uint8_t peer_public_value[32])
Definition at line 3366 of file curve25519.c.
X25519_public_from_private()
void X25519_public_from_private (uint8_t out_public_value[32], const uint8_t private_key[32])
Definition at line 3374 of file curve25519.c.
References e.