crypto/ec/ec_kmeth.c File Reference
ec_kmeth.c File Reference
#include <string.h>
#include <openssl/ec.h>
#include <openssl/engine.h>
#include <openssl/err.h>
#include "ec_lcl.h"
Functions
const EC_KEY_METHOD * EC_KEY_OpenSSL (void)
const EC_KEY_METHOD * EC_KEY_get_default_method (void)
void EC_KEY_set_default_method (const EC_KEY_METHOD *meth)
const EC_KEY_METHOD * EC_KEY_get_method (const EC_KEY *key)
int EC_KEY_set_method (EC_KEY *key, const EC_KEY_METHOD *meth)
EC_KEY * EC_KEY_new_method (ENGINE *engine)
int ECDH_compute_key (void *out, size_t outlen, const EC_POINT *pub_key, const EC_KEY *eckey, void *(*KDF)(const void *in, size_t inlen, void *out, size_t *outlen))
EC_KEY_METHOD * EC_KEY_METHOD_new (const EC_KEY_METHOD *meth)
void EC_KEY_METHOD_free (EC_KEY_METHOD *meth)
void EC_KEY_METHOD_set_init (EC_KEY_METHOD *meth, int(*init)(EC_KEY *key), void(*finish)(EC_KEY *key), int(*copy)(EC_KEY *dest, const EC_KEY *src), int(*set_group)(EC_KEY *key, const EC_GROUP *grp), int(*set_private)(EC_KEY *key, const BIGNUM *priv_key), int(*set_public)(EC_KEY *key, const EC_POINT *pub_key))
void EC_KEY_METHOD_set_keygen (EC_KEY_METHOD *meth, int(*keygen)(EC_KEY *key))
void EC_KEY_METHOD_set_compute_key (EC_KEY_METHOD *meth, int(*ckey)(unsigned char **psec, size_t *pseclen, const EC_POINT *pub_key, const EC_KEY *ecdh))
void EC_KEY_METHOD_set_sign (EC_KEY_METHOD *meth, int(*sign)(int type, const unsigned char *dgst, int dlen, unsigned char *sig, unsigned int *siglen, const BIGNUM *kinv, const BIGNUM *r, EC_KEY *eckey), int(*sign_setup)(EC_KEY *eckey, BN_CTX *ctx_in, BIGNUM **kinvp, BIGNUM **rp), ECDSA_SIG *(*sign_sig)(const unsigned char *dgst, int dgst_len, const BIGNUM *in_kinv, const BIGNUM *in_r, EC_KEY *eckey))
void EC_KEY_METHOD_set_verify (EC_KEY_METHOD *meth, int(*verify)(int type, const unsigned char *dgst, int dgst_len, const unsigned char *sigbuf, int sig_len, EC_KEY *eckey), int(*verify_sig)(const unsigned char *dgst, int dgst_len, const ECDSA_SIG *sig, EC_KEY *eckey))
void EC_KEY_METHOD_get_init (EC_KEY_METHOD *meth, int(**pinit)(EC_KEY *key), void(**pfinish)(EC_KEY *key), int(**pcopy)(EC_KEY *dest, const EC_KEY *src), int(**pset_group)(EC_KEY *key, const EC_GROUP *grp), int(**pset_private)(EC_KEY *key, const BIGNUM *priv_key), int(**pset_public)(EC_KEY *key, const EC_POINT *pub_key))
void EC_KEY_METHOD_get_keygen (EC_KEY_METHOD *meth, int(**pkeygen)(EC_KEY *key))
void EC_KEY_METHOD_get_compute_key (EC_KEY_METHOD *meth, int(**pck)(unsigned char **pout, size_t *poutlen, const EC_POINT *pub_key, const EC_KEY *ecdh))
void EC_KEY_METHOD_get_sign (EC_KEY_METHOD *meth, int(**psign)(int type, const unsigned char *dgst, int dlen, unsigned char *sig, unsigned int *siglen, const BIGNUM *kinv, const BIGNUM *r, EC_KEY *eckey), int(**psign_setup)(EC_KEY *eckey, BN_CTX *ctx_in, BIGNUM **kinvp, BIGNUM **rp), ECDSA_SIG *(**psign_sig)(const unsigned char *dgst, int dgst_len, const BIGNUM *in_kinv, const BIGNUM *in_r, EC_KEY *eckey))
void EC_KEY_METHOD_get_verify (EC_KEY_METHOD *meth, int(**pverify)(int type, const unsigned char *dgst, int dgst_len, const unsigned char *sigbuf, int sig_len, EC_KEY *eckey), int(**pverify_sig)(const unsigned char *dgst, int dgst_len, const ECDSA_SIG *sig, EC_KEY *eckey))
Function Documentation
EC_KEY_get_default_method()
const EC_KEY_METHOD* EC_KEY_get_default_method (void)
Definition at line 37 of file ec_kmeth.c.
EC_KEY_get_method()
const EC_KEY_METHOD* EC_KEY_get_method (const EC_KEY * key)
Definition at line 50 of file ec_kmeth.c.
EC_KEY_METHOD_free()
void EC_KEY_METHOD_free (EC_KEY_METHOD * meth)
Definition at line 167 of file ec_kmeth.c.
References EC_KEY_METHOD_DYNAMIC, and OPENSSL_free.
EC_KEY_METHOD_get_compute_key()
void EC_KEY_METHOD_get_compute_key (EC_KEY_METHOD * meth, int(**)(unsigned char **pout, size_t *poutlen, const EC_POINT *pub_key, const EC_KEY *ecdh) pck)
Definition at line 271 of file ec_kmeth.c.
References NULL.
EC_KEY_METHOD_get_init()
void EC_KEY_METHOD_get_init (EC_KEY_METHOD * meth, int(**)(EC_KEY *key) pinit, void(**)(EC_KEY *key) pfinish, int(**)(EC_KEY *dest, const EC_KEY *src) pcopy, int(**)(EC_KEY *key, const EC_GROUP *grp) pset_group, int(**)(EC_KEY *key, const BIGNUM *priv_key) pset_private, int(**)(EC_KEY *key, const EC_POINT *pub_key) pset_public)
Definition at line 239 of file ec_kmeth.c.
References NULL.
EC_KEY_METHOD_get_keygen()
void EC_KEY_METHOD_get_keygen (EC_KEY_METHOD * meth, int(**)(EC_KEY *key) pkeygen)
Definition at line 264 of file ec_kmeth.c.
References NULL.
EC_KEY_METHOD_get_sign()
void EC_KEY_METHOD_get_sign (EC_KEY_METHOD * meth, int(**)(int type, const unsigned char *dgst, int dlen, unsigned char *sig, unsigned int *siglen, const BIGNUM *kinv, const BIGNUM *r, EC_KEY *eckey) psign, int(**)(EC_KEY *eckey, BN_CTX *ctx_in, BIGNUM **kinvp, BIGNUM **rp) psign_setup, ECDSA_SIG *(**)(const unsigned char *dgst, int dgst_len, const BIGNUM *in_kinv, const BIGNUM *in_r, EC_KEY *eckey) psign_sig)
Definition at line 281 of file ec_kmeth.c.
References NULL.
EC_KEY_METHOD_get_verify()
void EC_KEY_METHOD_get_verify (EC_KEY_METHOD * meth, int(**)(int type, const unsigned char *dgst, int dgst_len, const unsigned char *sigbuf, int sig_len, EC_KEY *eckey) pverify, int(**)(const unsigned char *dgst, int dgst_len, const ECDSA_SIG *sig, EC_KEY *eckey) pverify_sig)
Definition at line 303 of file ec_kmeth.c.
References NULL.
EC_KEY_METHOD_new()
EC_KEY_METHOD* EC_KEY_METHOD_new (const EC_KEY_METHOD * meth)
Definition at line 155 of file ec_kmeth.c.
EC_KEY_METHOD_set_compute_key()
void EC_KEY_METHOD_set_compute_key (EC_KEY_METHOD * meth, int(*)(unsigned char **psec, size_t *pseclen, const EC_POINT *pub_key, const EC_KEY *ecdh) ckey)
Definition at line 197 of file ec_kmeth.c.
EC_KEY_METHOD_set_init()
void EC_KEY_METHOD_set_init (EC_KEY_METHOD * meth, int(*)(EC_KEY *key) init, void(*)(EC_KEY *key) finish, int(*)(EC_KEY *dest, const EC_KEY *src) copy, int(*)(EC_KEY *key, const EC_GROUP *grp) set_group, int(*)(EC_KEY *key, const BIGNUM *priv_key) set_private, int(*)(EC_KEY *key, const EC_POINT *pub_key) set_public)
Definition at line 173 of file ec_kmeth.c.
EC_KEY_METHOD_set_keygen()
void EC_KEY_METHOD_set_keygen (EC_KEY_METHOD * meth, int(*)(EC_KEY *key) keygen)
Definition at line 191 of file ec_kmeth.c.
EC_KEY_METHOD_set_sign()
void EC_KEY_METHOD_set_sign (EC_KEY_METHOD * meth, int(*)(int type, const unsigned char *dgst, int dlen, unsigned char *sig, unsigned int *siglen, const BIGNUM *kinv, const BIGNUM *r, EC_KEY *eckey) sign, int(*)(EC_KEY *eckey, BN_CTX *ctx_in, BIGNUM **kinvp, BIGNUM **rp) sign_setup, ECDSA_SIG *(*)(const unsigned char *dgst, int dgst_len, const BIGNUM *in_kinv, const BIGNUM *in_r, EC_KEY *eckey) sign_sig)
Definition at line 206 of file ec_kmeth.c.
EC_KEY_METHOD_set_verify()
void EC_KEY_METHOD_set_verify (EC_KEY_METHOD * meth, int(*)(int type, const unsigned char *dgst, int dgst_len, const unsigned char *sigbuf, int sig_len, EC_KEY *eckey) verify, int(*)(const unsigned char *dgst, int dgst_len, const ECDSA_SIG *sig, EC_KEY *eckey) verify_sig)
Definition at line 225 of file ec_kmeth.c.
EC_KEY_new_method()
EC_KEY* EC_KEY_new_method (ENGINE * engine)
Definition at line 73 of file ec_kmeth.c.
Referenced by EC_KEY_new().
EC_KEY_OpenSSL()
const EC_KEY_METHOD* EC_KEY_OpenSSL (void)
Definition at line 32 of file ec_kmeth.c.
EC_KEY_set_default_method()
void EC_KEY_set_default_method (const EC_KEY_METHOD * meth)
Definition at line 42 of file ec_kmeth.c.
References NULL.
EC_KEY_set_method()
int EC_KEY_set_method (EC_KEY * key, const EC_KEY_METHOD * meth)
Definition at line 55 of file ec_kmeth.c.
References ENGINE_finish(), if(), key, and NULL.
ECDH_compute_key()
int ECDH_compute_key (void * out, size_t outlen, const EC_POINT * pub_key, const EC_KEY * eckey, void *(*)(const void *in, size_t inlen, void *out, size_t *outlen) KDF)
Definition at line 127 of file ec_kmeth.c.