crypto/ec/ec_lib.c File Reference
ec_lib.c File Reference
#include <string.h>
#include <openssl/err.h>
#include <openssl/opensslv.h>
#include "ec_lcl.h"
Functions
EC_GROUP * EC_GROUP_new (const EC_METHOD *meth)
void EC_pre_comp_free (EC_GROUP *group)
void EC_GROUP_free (EC_GROUP *group)
void EC_GROUP_clear_free (EC_GROUP *group)
int EC_GROUP_copy (EC_GROUP *dest, const EC_GROUP *src)
EC_GROUP * EC_GROUP_dup (const EC_GROUP *a)
const EC_METHOD * EC_GROUP_method_of (const EC_GROUP *group)
int EC_METHOD_get_field_type (const EC_METHOD *meth)
int EC_GROUP_set_generator (EC_GROUP *group, const EC_POINT *generator, const BIGNUM *order, const BIGNUM *cofactor)
const EC_POINT * EC_GROUP_get0_generator (const EC_GROUP *group)
BN_MONT_CTX * EC_GROUP_get_mont_data (const EC_GROUP *group)
int EC_GROUP_get_order (const EC_GROUP *group, BIGNUM *order, BN_CTX *ctx)
const BIGNUM * EC_GROUP_get0_order (const EC_GROUP *group)
int EC_GROUP_order_bits (const EC_GROUP *group)
int EC_GROUP_get_cofactor (const EC_GROUP *group, BIGNUM *cofactor, BN_CTX *ctx)
const BIGNUM * EC_GROUP_get0_cofactor (const EC_GROUP *group)
void EC_GROUP_set_curve_name (EC_GROUP *group, int nid)
int EC_GROUP_get_curve_name (const EC_GROUP *group)
void EC_GROUP_set_asn1_flag (EC_GROUP *group, int flag)
int EC_GROUP_get_asn1_flag (const EC_GROUP *group)
void EC_GROUP_set_point_conversion_form (EC_GROUP *group, point_conversion_form_t form)
point_conversion_form_t EC_GROUP_get_point_conversion_form (const EC_GROUP *group)
size_t EC_GROUP_set_seed (EC_GROUP *group, const unsigned char *p, size_t len)
unsigned char * EC_GROUP_get0_seed (const EC_GROUP *group)
size_t EC_GROUP_get_seed_len (const EC_GROUP *group)
int EC_GROUP_set_curve_GFp (EC_GROUP *group, const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int EC_GROUP_get_curve_GFp (const EC_GROUP *group, BIGNUM *p, BIGNUM *a, BIGNUM *b, BN_CTX *ctx)
int EC_GROUP_set_curve_GF2m (EC_GROUP *group, const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int EC_GROUP_get_curve_GF2m (const EC_GROUP *group, BIGNUM *p, BIGNUM *a, BIGNUM *b, BN_CTX *ctx)
int EC_GROUP_get_degree (const EC_GROUP *group)
int EC_GROUP_check_discriminant (const EC_GROUP *group, BN_CTX *ctx)
int EC_GROUP_cmp (const EC_GROUP *a, const EC_GROUP *b, BN_CTX *ctx)
EC_POINT * EC_POINT_new (const EC_GROUP *group)
void EC_POINT_free (EC_POINT *point)
void EC_POINT_clear_free (EC_POINT *point)
int EC_POINT_copy (EC_POINT *dest, const EC_POINT *src)
EC_POINT * EC_POINT_dup (const EC_POINT *a, const EC_GROUP *group)
const EC_METHOD * EC_POINT_method_of (const EC_POINT *point)
int EC_POINT_set_to_infinity (const EC_GROUP *group, EC_POINT *point)
int EC_POINT_set_Jprojective_coordinates_GFp (const EC_GROUP *group, EC_POINT *point, const BIGNUM *x, const BIGNUM *y, const BIGNUM *z, BN_CTX *ctx)
int EC_POINT_get_Jprojective_coordinates_GFp (const EC_GROUP *group, const EC_POINT *point, BIGNUM *x, BIGNUM *y, BIGNUM *z, BN_CTX *ctx)
int EC_POINT_set_affine_coordinates_GFp (const EC_GROUP *group, EC_POINT *point, const BIGNUM *x, const BIGNUM *y, BN_CTX *ctx)
int EC_POINT_set_affine_coordinates_GF2m (const EC_GROUP *group, EC_POINT *point, const BIGNUM *x, const BIGNUM *y, BN_CTX *ctx)
int EC_POINT_get_affine_coordinates_GFp (const EC_GROUP *group, const EC_POINT *point, BIGNUM *x, BIGNUM *y, BN_CTX *ctx)
int EC_POINT_get_affine_coordinates_GF2m (const EC_GROUP *group, const EC_POINT *point, BIGNUM *x, BIGNUM *y, BN_CTX *ctx)
int EC_POINT_add (const EC_GROUP *group, EC_POINT *r, const EC_POINT *a, const EC_POINT *b, BN_CTX *ctx)
int EC_POINT_dbl (const EC_GROUP *group, EC_POINT *r, const EC_POINT *a, BN_CTX *ctx)
int EC_POINT_invert (const EC_GROUP *group, EC_POINT *a, BN_CTX *ctx)
int EC_POINT_is_at_infinity (const EC_GROUP *group, const EC_POINT *point)
int EC_POINT_is_on_curve (const EC_GROUP *group, const EC_POINT *point, BN_CTX *ctx)
int EC_POINT_cmp (const EC_GROUP *group, const EC_POINT *a, const EC_POINT *b, BN_CTX *ctx)
int EC_POINT_make_affine (const EC_GROUP *group, EC_POINT *point, BN_CTX *ctx)
int EC_POINTs_make_affine (const EC_GROUP *group, size_t num, EC_POINT *points[], BN_CTX *ctx)
int EC_POINTs_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *scalar, size_t num, const EC_POINT *points[], const BIGNUM *scalars[], BN_CTX *ctx)
int EC_POINT_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *g_scalar, const EC_POINT *point, const BIGNUM *p_scalar, BN_CTX *ctx)
int EC_GROUP_precompute_mult (EC_GROUP *group, BN_CTX *ctx)
int EC_GROUP_have_precompute_mult (const EC_GROUP *group)
int ec_precompute_mont_data (EC_GROUP *group)
int EC_KEY_set_ex_data (EC_KEY *key, int idx, void *arg)
void * EC_KEY_get_ex_data (const EC_KEY *key, int idx)
int ec_group_simple_order_bits (const EC_GROUP *group)
Function Documentation
EC_GROUP_check_discriminant()
int EC_GROUP_check_discriminant (const EC_GROUP * group, BN_CTX * ctx)
Checks whether the discriminant of the elliptic curve is zero or not
Parameters
group EC_GROUP object
ctx BN_CTX object (optional)
Returns
1 if the discriminant is not zero and 0 otherwise
Definition at line 471 of file ec_lib.c.
References EC_F_EC_GROUP_CHECK_DISCRIMINANT, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_GROUP_clear_free()
void EC_GROUP_clear_free (EC_GROUP * group)
Clears and frees a EC_GROUP object
Parameters
group EC_GROUP object to be cleared and freed.
Definition at line 116 of file ec_lib.c.
References BN_clear_free(), BN_MONT_CTX_free(), EC_POINT_clear_free(), EC_pre_comp_free(), and OPENSSL_clear_free.
Referenced by d2i_ECPKParameters().
EC_GROUP_cmp()
int EC_GROUP_cmp (const EC_GROUP * a, const EC_GROUP * b, BN_CTX * ctx)
Compares two EC_GROUP objects
Parameters
a first EC_GROUP object
b second EC_GROUP object
ctx BN_CTX object (optional)
Returns
0 if the groups are equal, 1 if not, or -1 on error
Definition at line 481 of file ec_lib.c.
EC_GROUP_copy()
int EC_GROUP_copy (EC_GROUP * dst, const EC_GROUP * src)
Copies EC_GROUP objects. Note: both EC_GROUPs must use the same EC_METHOD.
Parameters
dst destination EC_GROUP object
src source EC_GROUP object
Returns
1 on success and 0 if an error occurred.
Definition at line 135 of file ec_lib.c.
References BN_copy(), BN_MONT_CTX_copy(), BN_MONT_CTX_free(), BN_MONT_CTX_new(), EC_ec_pre_comp_dup(), EC_F_EC_GROUP_COPY, EC_FLAGS_CUSTOM_CURVE, EC_nistp224_pre_comp_dup(), EC_nistp256_pre_comp_dup(), EC_nistp521_pre_comp_dup(), EC_nistz256_pre_comp_dup(), EC_POINT_clear_free(), EC_POINT_copy(), EC_POINT_new(), EC_R_INCOMPATIBLE_OBJECTS, ECerr, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, NULL, OPENSSL_free, and OPENSSL_malloc.
Referenced by EC_GROUP_dup(), and EC_KEY_copy().
EC_GROUP_dup()
EC_GROUP* EC_GROUP_dup (const EC_GROUP * src)
Creates a new EC_GROUP object and copies the copies the content form src to the newly created EC_KEY object
Parameters
src source EC_GROUP object
Returns
newly created EC_GROUP object or NULL in case of an error.
Definition at line 236 of file ec_lib.c.
References EC_GROUP_copy(), EC_GROUP_free(), EC_GROUP_new(), NULL, and t.
Referenced by EC_KEY_set_group().
EC_GROUP_free()
void EC_GROUP_free (EC_GROUP * group)
Frees a EC_GROUP object
Parameters
group EC_GROUP object to be freed.
Definition at line 99 of file ec_lib.c.
References BN_free(), BN_MONT_CTX_free(), EC_POINT_free(), EC_pre_comp_free(), and OPENSSL_free.
Referenced by EC_GROUP_dup(), EC_KEY_copy(), EC_KEY_free(), and EC_KEY_set_group().
EC_GROUP_get0_cofactor()
const BIGNUM* EC_GROUP_get0_cofactor (const EC_GROUP * group)
Gets the cofactor of an EC_GROUP
Parameters
group EC_GROUP object
Returns
the group cofactor
Definition at line 354 of file ec_lib.c.
EC_GROUP_get0_generator()
const EC_POINT* EC_GROUP_get0_generator (const EC_GROUP * group)
Returns the generator of a EC_GROUP object.
Parameters
group EC_GROUP object
Returns
the currently used generator (possibly NULL).
Definition at line 311 of file ec_lib.c.
EC_GROUP_get0_order()
const BIGNUM* EC_GROUP_get0_order (const EC_GROUP * group)
Gets the order of an EC_GROUP
Parameters
group EC_GROUP object
Returns
the group order
Definition at line 331 of file ec_lib.c.
EC_GROUP_get0_seed()
unsigned char* EC_GROUP_get0_seed (const EC_GROUP * group)
Definition at line 408 of file ec_lib.c.
EC_GROUP_get_asn1_flag()
int EC_GROUP_get_asn1_flag (const EC_GROUP * group)
Definition at line 374 of file ec_lib.c.
EC_GROUP_get_cofactor()
int EC_GROUP_get_cofactor (const EC_GROUP * group, BIGNUM * cofactor, BN_CTX * ctx)
Gets the cofactor of a EC_GROUP
Parameters
group EC_GROUP object
cofactor BIGNUM to which the cofactor is copied
ctx unused
Returns
1 on success and 0 if an error occurred
Definition at line 342 of file ec_lib.c.
References BN_copy(), BN_is_zero(), and NULL.
EC_GROUP_get_curve_GF2m()
int EC_GROUP_get_curve_GF2m (const EC_GROUP * group, BIGNUM * p, BIGNUM * a, BIGNUM * b, BN_CTX * ctx)
Gets the parameter of the ec over GF2m defined by y^2 + x*y = x^3 + a*x^2 + b
Parameters
group EC_GROUP object
p BIGNUM for the polynomial defining the underlying field
a BIGNUM for parameter a of the equation
b BIGNUM for parameter b of the equation
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 450 of file ec_lib.c.
References EC_F_EC_GROUP_GET_CURVE_GF2M, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_GROUP_get_curve_GFp()
int EC_GROUP_get_curve_GFp (const EC_GROUP * group, BIGNUM * p, BIGNUM * a, BIGNUM * b, BN_CTX * ctx)
Gets the parameter of the ec over GFp defined by y^2 = x^3 + a*x + b
Parameters
group EC_GROUP object
p BIGNUM for the prime number
a BIGNUM for parameter a of the equation
b BIGNUM for parameter b of the equation
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 428 of file ec_lib.c.
References EC_F_EC_GROUP_GET_CURVE_GFP, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_GROUP_get_curve_name()
int EC_GROUP_get_curve_name (const EC_GROUP * group)
Returns the curve name of a EC_GROUP object
Parameters
group EC_GROUP object
Returns
NID of the curve name OID or 0 if not set.
Definition at line 364 of file ec_lib.c.
Referenced by ssl3_ctx_ctrl(), and ssl_print_tmp_key().
EC_GROUP_get_degree()
int EC_GROUP_get_degree (const EC_GROUP * group)
Returns the number of bits needed to represent a field element
Parameters
group EC_GROUP object
Returns
number of bits needed to represent a field element
Definition at line 462 of file ec_lib.c.
References EC_F_EC_GROUP_GET_DEGREE, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_GROUP_get_mont_data()
BN_MONT_CTX* EC_GROUP_get_mont_data (const EC_GROUP * group)
Returns the montgomery data for order(Generator)
Parameters
group EC_GROUP object
Returns
the currently used montgomery data (possibly NULL).
Definition at line 316 of file ec_lib.c.
EC_GROUP_get_order()
int EC_GROUP_get_order (const EC_GROUP * group, BIGNUM * order, BN_CTX * ctx)
Gets the order of a EC_GROUP
Parameters
group EC_GROUP object
order BIGNUM to which the order is copied
ctx unused
Returns
1 on success and 0 if an error occurred
Definition at line 321 of file ec_lib.c.
EC_GROUP_get_point_conversion_form()
point_conversion_form_t EC_GROUP_get_point_conversion_form (const EC_GROUP * group)
Definition at line 385 of file ec_lib.c.
EC_GROUP_get_seed_len()
size_t EC_GROUP_get_seed_len (const EC_GROUP * group)
Definition at line 413 of file ec_lib.c.
EC_GROUP_have_precompute_mult()
int EC_GROUP_have_precompute_mult (const EC_GROUP * group)
Reports whether a precomputation has been done
Parameters
group EC_GROUP object
Returns
1 if a pre-computation has been done and 0 otherwise
Definition at line 953 of file ec_lib.c.
References ec_wNAF_have_precompute_mult().
Referenced by ec_GF2m_simple_mul().
EC_GROUP_method_of()
const EC_METHOD* EC_GROUP_method_of (const EC_GROUP * group)
Returns the EC_METHOD of the EC_GROUP object.
Parameters
group EC_GROUP object
Returns
EC_METHOD used in this EC_GROUP object.
Definition at line 259 of file ec_lib.c.
Referenced by EC_GROUP_get_basis_type(), EC_GROUP_get_pentanomial_basis(), EC_KEY_copy(), and EC_KEY_set_public_key_affine_coordinates().
EC_GROUP_new()
EC_GROUP* EC_GROUP_new (const EC_METHOD * meth)
Creates a new EC_GROUP object
Parameters
meth EC_METHOD to use
Returns
newly created EC_GROUP object or NULL in case of an error.
Definition at line 25 of file ec_lib.c.
Referenced by EC_GROUP_dup(), and EC_KEY_copy().
EC_GROUP_order_bits()
int EC_GROUP_order_bits (const EC_GROUP * group)
Gets the number of bits of the order of an EC_GROUP
Parameters
group EC_GROUP object
Returns
number of bits of group order.
Definition at line 336 of file ec_lib.c.
References NULL, and OPENSSL_assert.
EC_GROUP_precompute_mult()
int EC_GROUP_precompute_mult (EC_GROUP * group, BN_CTX * ctx)
Stores multiples of generator for faster point multiplication
Parameters
group EC_GROUP object
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 941 of file ec_lib.c.
References ec_wNAF_precompute_mult().
Referenced by EC_KEY_precompute_mult().
EC_GROUP_set_asn1_flag()
void EC_GROUP_set_asn1_flag (EC_GROUP * group, int flag)
Definition at line 369 of file ec_lib.c.
EC_GROUP_set_curve_GF2m()
int EC_GROUP_set_curve_GF2m (EC_GROUP * group, const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Sets the parameter of a ec over GF2m defined by y^2 + x*y = x^3 + a*x^2 + b
Parameters
group EC_GROUP object
p BIGNUM with the polynomial defining the underlying field
a BIGNUM with parameter a of the equation
b BIGNUM with parameter b of the equation
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 439 of file ec_lib.c.
References EC_F_EC_GROUP_SET_CURVE_GF2M, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_GROUP_set_curve_GFp()
int EC_GROUP_set_curve_GFp (EC_GROUP * group, const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Sets the parameter of a ec over GFp defined by y^2 = x^3 + a*x + b
Parameters
group EC_GROUP object
p BIGNUM with the prime number
a BIGNUM with parameter a of the equation
b BIGNUM with parameter b of the equation
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 418 of file ec_lib.c.
References EC_F_EC_GROUP_SET_CURVE_GFP, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_GROUP_set_curve_name()
void EC_GROUP_set_curve_name (EC_GROUP * group, int nid)
Sets the name of a EC_GROUP object
Parameters
group EC_GROUP object
nid NID of the curve name OID
Definition at line 359 of file ec_lib.c.
References nid.
EC_GROUP_set_generator()
int EC_GROUP_set_generator (EC_GROUP * group, const EC_POINT * generator, const BIGNUM * order, const BIGNUM * cofactor)
Sets the generator and it's order/cofactor of a EC_GROUP object.
Parameters
group EC_GROUP object
generator EC_POINT object with the generator.
order the order of the group generated by the generator.
cofactor the index of the sub-group generated by the generator in the group of all points on the elliptic curve.
Returns
1 on success and 0 if an error occurred
Definition at line 269 of file ec_lib.c.
EC_GROUP_set_point_conversion_form()
void EC_GROUP_set_point_conversion_form (EC_GROUP * group, point_conversion_form_t form)
Definition at line 379 of file ec_lib.c.
Referenced by EC_KEY_set_conv_form().
EC_GROUP_set_seed()
size_t EC_GROUP_set_seed (EC_GROUP * group, const unsigned char * p, size_t len)
Definition at line 391 of file ec_lib.c.
References len, NULL, OPENSSL_free, and OPENSSL_malloc.
ec_group_simple_order_bits()
int ec_group_simple_order_bits (const EC_GROUP * group)
Definition at line 1009 of file ec_lib.c.
References BN_num_bits(), and NULL.
Referenced by EC_GFp_nistz256_method().
EC_KEY_get_ex_data()
void* EC_KEY_get_ex_data (const EC_KEY * key, int idx)
Definition at line 1004 of file ec_lib.c.
EC_KEY_set_ex_data()
int EC_KEY_set_ex_data (EC_KEY * key, int idx, void * arg)
Definition at line 999 of file ec_lib.c.
EC_METHOD_get_field_type()
int EC_METHOD_get_field_type (const EC_METHOD * meth)
Returns the field type of the EC_METHOD.
Parameters
meth EC_METHOD object
Returns
NID of the underlying field type OID.
Definition at line 264 of file ec_lib.c.
Referenced by EC_GROUP_get_basis_type(), EC_GROUP_get_pentanomial_basis(), and EC_KEY_set_public_key_affine_coordinates().
EC_POINT_add()
int EC_POINT_add (const EC_GROUP * group, EC_POINT * r, const EC_POINT * a, const EC_POINT * b, BN_CTX * ctx)
Computes the sum of two EC_POINT
Parameters
group underlying EC_GROUP object
r EC_POINT object for the result (r = a + b)
a EC_POINT object with the first summand
b EC_POINT object with the second summand
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 786 of file ec_lib.c.
References EC_F_EC_POINT_ADD, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_POINT_clear_free()
void EC_POINT_clear_free (EC_POINT * point)
Clears and frees a EC_POINT object
Parameters
point EC_POINT object to be cleared and freed
Definition at line 595 of file ec_lib.c.
References OPENSSL_clear_free.
Referenced by EC_GROUP_clear_free(), and EC_GROUP_copy().
EC_POINT_cmp()
int EC_POINT_cmp (const EC_GROUP * group, const EC_POINT * a, const EC_POINT * b, BN_CTX * ctx)
Compares two EC_POINTs
Parameters
group underlying EC_GROUP object
a first EC_POINT object
b second EC_POINT object
ctx BN_CTX object (optional)
Returns
1 if the points are not equal, 0 if they are, or -1 on error
Definition at line 863 of file ec_lib.c.
References EC_F_EC_POINT_CMP, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_POINT_copy()
int EC_POINT_copy (EC_POINT * dst, const EC_POINT * src)
Copies EC_POINT object
Parameters
dst destination EC_POINT object
src source EC_POINT object
Returns
1 on success and 0 if an error occurred
Definition at line 607 of file ec_lib.c.
References EC_F_EC_POINT_COPY, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by EC_GROUP_copy(), EC_KEY_copy(), and EC_POINT_dup().
EC_POINT_dbl()
int EC_POINT_dbl (const EC_GROUP * group, EC_POINT * r, const EC_POINT * a, BN_CTX * ctx)
Computes the double of a EC_POINT
Parameters
group underlying EC_GROUP object
r EC_POINT object for the result (r = 2 * a)
a EC_POINT object
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 801 of file ec_lib.c.
References EC_F_EC_POINT_DBL, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_POINT_dup()
EC_POINT* EC_POINT_dup (const EC_POINT * src, const EC_GROUP * group)
Creates a new EC_POINT object and copies the content of the supplied EC_POINT
Parameters
src source EC_POINT object
group underlying the EC_GROUP object
Returns
newly created EC_POINT object or NULL if an error occurred
Definition at line 622 of file ec_lib.c.
References EC_POINT_copy(), EC_POINT_free(), EC_POINT_new(), NULL, and t.
Referenced by EC_KEY_set_public_key().
EC_POINT_free()
void EC_POINT_free (EC_POINT * point)
Frees a EC_POINT object
Parameters
point EC_POINT object to be freed
Definition at line 585 of file ec_lib.c.
References OPENSSL_free.
Referenced by EC_ec_pre_comp_free(), EC_GROUP_free(), EC_KEY_copy(), EC_KEY_free(), EC_KEY_set_public_key(), EC_KEY_set_public_key_affine_coordinates(), and EC_POINT_dup().
EC_POINT_get_affine_coordinates_GF2m()
int EC_POINT_get_affine_coordinates_GF2m (const EC_GROUP * group, const EC_POINT * p, BIGNUM * x, BIGNUM * y, BN_CTX * ctx)
Gets the affine coordinates of a EC_POINT over GF2m
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM for the x-coordinate
y BIGNUM for the y-coordinate
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 768 of file ec_lib.c.
References EC_F_EC_POINT_GET_AFFINE_COORDINATES_GF2M, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_POINT_get_affine_coordinates_GFp()
int EC_POINT_get_affine_coordinates_GFp (const EC_GROUP * group, const EC_POINT * p, BIGNUM * x, BIGNUM * y, BN_CTX * ctx)
Gets the affine coordinates of a EC_POINT over GFp
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM for the x-coordinate
y BIGNUM for the y-coordinate
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 750 of file ec_lib.c.
References EC_F_EC_POINT_GET_AFFINE_COORDINATES_GFP, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_POINT_get_Jprojective_coordinates_GFp()
int EC_POINT_get_Jprojective_coordinates_GFp (const EC_GROUP * group, const EC_POINT * p, BIGNUM * x, BIGNUM * y, BIGNUM * z, BN_CTX * ctx)
Gets the jacobian projective coordinates of a EC_POINT over GFp
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM for the x-coordinate
y BIGNUM for the y-coordinate
z BIGNUM for the z-coordinate
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 679 of file ec_lib.c.
References EC_F_EC_POINT_GET_JPROJECTIVE_COORDINATES_GFP, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_POINT_invert()
int EC_POINT_invert (const EC_GROUP * group, EC_POINT * a, BN_CTX * ctx)
Computes the inverse of a EC_POINT
Parameters
group underlying EC_GROUP object
a EC_POINT object to be inverted (it's used for the result as well)
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 815 of file ec_lib.c.
References EC_F_EC_POINT_INVERT, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_POINT_is_at_infinity()
int EC_POINT_is_at_infinity (const EC_GROUP * group, const EC_POINT * p)
Checks whether the point is the neutral element of the group
Parameters
group the underlying EC_GROUP object
p EC_POINT object
Returns
1 if the point is the neutral element and 0 otherwise
Definition at line 828 of file ec_lib.c.
References EC_F_EC_POINT_IS_AT_INFINITY, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by ec_GF2m_simple_invert(), ec_GFp_nistp224_point_get_affine_coordinates(), ec_GFp_nistp256_point_get_affine_coordinates(), ec_GFp_nistp521_point_get_affine_coordinates(), and ec_GFp_simple_invert().
EC_POINT_is_on_curve()
int EC_POINT_is_on_curve (const EC_GROUP * group, const EC_POINT * point, BN_CTX * ctx)
Checks whether the point is on the curve
Parameters
group underlying EC_GROUP object
point EC_POINT object to check
ctx BN_CTX object (optional)
Returns
1 if the point is on the curve, 0 if not, or -1 on error
Definition at line 849 of file ec_lib.c.
References EC_F_EC_POINT_IS_ON_CURVE, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by EC_POINT_set_affine_coordinates_GF2m(), and EC_POINT_set_affine_coordinates_GFp().
EC_POINT_make_affine()
int EC_POINT_make_affine (const EC_GROUP * group, EC_POINT * point, BN_CTX * ctx)
Definition at line 877 of file ec_lib.c.
References EC_F_EC_POINT_MAKE_AFFINE, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by ec_GF2m_simple_invert().
EC_POINT_method_of()
const EC_METHOD* EC_POINT_method_of (const EC_POINT * point)
Returns the EC_METHOD used in EC_POINT object
Parameters
point EC_POINT object
Returns
the EC_METHOD used
Definition at line 641 of file ec_lib.c.
EC_POINT_mul()
int EC_POINT_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * n, const EC_POINT * q, const BIGNUM * m, BN_CTX * ctx)
Computes r = generator * n + q * m
Parameters
group underlying EC_GROUP object
r EC_POINT object for the result
n BIGNUM with the multiplier for the group generator (optional)
q EC_POINT object with the first factor of the second summand
m BIGNUM with the second factor of the second summand
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 925 of file ec_lib.c.
References EC_POINTs_mul(), and NULL.
Referenced by ec_key_simple_generate_public_key().
EC_POINT_new()
EC_POINT* EC_POINT_new (const EC_GROUP * group)
Creates a new EC_POINT object for the specified EC_GROUP
Parameters
group EC_GROUP the underlying EC_GROUP object
Returns
newly created EC_POINT object or NULL if an error occurred
Definition at line 556 of file ec_lib.c.
Referenced by ec_GF2m_simple_mul(), EC_GROUP_copy(), EC_KEY_copy(), EC_KEY_set_public_key_affine_coordinates(), and EC_POINT_dup().
EC_POINT_set_affine_coordinates_GF2m()
int EC_POINT_set_affine_coordinates_GF2m (const EC_GROUP * group, EC_POINT * p, const BIGNUM * x, const BIGNUM * y, BN_CTX * ctx)
Sets the affine coordinates of a EC_POINT over GF2m
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM with the x-coordinate
y BIGNUM with the y-coordinate
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 724 of file ec_lib.c.
References EC_F_EC_POINT_SET_AFFINE_COORDINATES_GF2M, EC_POINT_is_on_curve(), EC_R_INCOMPATIBLE_OBJECTS, EC_R_POINT_IS_NOT_ON_CURVE, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_POINT_set_affine_coordinates_GFp()
int EC_POINT_set_affine_coordinates_GFp (const EC_GROUP * group, EC_POINT * p, const BIGNUM * x, const BIGNUM * y, BN_CTX * ctx)
Sets the affine coordinates of a EC_POINT over GFp
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM with the x-coordinate
y BIGNUM with the y-coordinate
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 698 of file ec_lib.c.
References EC_F_EC_POINT_SET_AFFINE_COORDINATES_GFP, EC_POINT_is_on_curve(), EC_R_INCOMPATIBLE_OBJECTS, EC_R_POINT_IS_NOT_ON_CURVE, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by EC_KEY_set_public_key_affine_coordinates().
EC_POINT_set_Jprojective_coordinates_GFp()
int EC_POINT_set_Jprojective_coordinates_GFp (const EC_GROUP * group, EC_POINT * p, const BIGNUM * x, const BIGNUM * y, const BIGNUM * z, BN_CTX * ctx)
Sets the jacobian projective coordinates of a EC_POINT over GFp
Parameters
group underlying EC_GROUP object
p EC_POINT object
x BIGNUM with the x-coordinate
y BIGNUM with the y-coordinate
z BIGNUM with the z-coordinate
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 660 of file ec_lib.c.
References EC_F_EC_POINT_SET_JPROJECTIVE_COORDINATES_GFP, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by ec_GFp_simple_point_set_affine_coordinates().
EC_POINT_set_to_infinity()
int EC_POINT_set_to_infinity (const EC_GROUP * group, EC_POINT * point)
Sets a point to infinity (neutral element)
Parameters
group underlying EC_GROUP object
point EC_POINT to set to infinity
Returns
1 on success and 0 if an error occurred
Definition at line 646 of file ec_lib.c.
References EC_F_EC_POINT_SET_TO_INFINITY, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
Referenced by ec_GF2m_simple_mul().
EC_POINTs_make_affine()
int EC_POINTs_make_affine (const EC_GROUP * group, size_t num, EC_POINT * points[], BN_CTX * ctx)
Definition at line 890 of file ec_lib.c.
References EC_F_EC_POINTS_MAKE_AFFINE, EC_R_INCOMPATIBLE_OBJECTS, ECerr, and ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED.
EC_POINTs_mul()
int EC_POINTs_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * n, size_t num, const EC_POINT * p[], const BIGNUM * m[], BN_CTX * ctx)
Computes r = generator * n + sum_{i=0}^{num-1} p[i] * m[i]
Parameters
group underlying EC_GROUP object
r EC_POINT object for the result
n BIGNUM with the multiplier for the group generator (optional)
num number further summands
p array of size num of EC_POINT objects
m array of size num of BIGNUM objects
ctx BN_CTX object (optional)
Returns
1 on success and 0 if an error occurred
Definition at line 914 of file ec_lib.c.
References ec_wNAF_mul().
Referenced by EC_POINT_mul().
EC_pre_comp_free()
void EC_pre_comp_free (EC_GROUP * group)
Definition at line 66 of file ec_lib.c.
References EC_ec_pre_comp_free(), EC_nistp224_pre_comp_free(), EC_nistp256_pre_comp_free(), EC_nistp521_pre_comp_free(), EC_nistz256_pre_comp_free(), and NULL.
Referenced by EC_GROUP_clear_free(), and EC_GROUP_free().
ec_precompute_mont_data()
int ec_precompute_mont_data (EC_GROUP * group)
Definition at line 970 of file ec_lib.c.
References BN_CTX_new(), and ctx.