crypto/ec/ecdsa_sign.c File Reference
ecdsa_sign.c File Reference
#include <openssl/ec.h>
#include "ec_lcl.h"
#include <openssl/err.h>
Functions
ECDSA_SIG * ECDSA_do_sign (const unsigned char *dgst, int dlen, EC_KEY *eckey)
ECDSA_SIG * ECDSA_do_sign_ex (const unsigned char *dgst, int dlen, const BIGNUM *kinv, const BIGNUM *rp, EC_KEY *eckey)
int ECDSA_sign (int type, const unsigned char *dgst, int dlen, unsigned char *sig, unsigned int *siglen, EC_KEY *eckey)
int ECDSA_sign_ex (int type, const unsigned char *dgst, int dlen, unsigned char *sig, unsigned int *siglen, const BIGNUM *kinv, const BIGNUM *r, EC_KEY *eckey)
int ECDSA_sign_setup (EC_KEY *eckey, BN_CTX *ctx_in, BIGNUM **kinvp, BIGNUM **rp)
Function Documentation
ECDSA_do_sign()
ECDSA_SIG* ECDSA_do_sign (const unsigned char * dgst, int dgst_len, EC_KEY * eckey)
Computes the ECDSA signature of the given hash value using the supplied private key and returns the created signature.
Parameters
dgst pointer to the hash value
dgst_len length of the hash value
eckey EC_KEY object containing a private EC key
Returns
pointer to a ECDSA_SIG structure or NULL if an error occurred
Definition at line 14 of file ecdsa_sign.c.
References ECDSA_do_sign_ex(), and NULL.
ECDSA_do_sign_ex()
ECDSA_SIG* ECDSA_do_sign_ex (const unsigned char * dgst, int dgstlen, const BIGNUM * kinv, const BIGNUM * rp, EC_KEY * eckey)
Computes ECDSA signature of a given hash value using the supplied private key (note: sig must point to ECDSA_size(eckey) bytes of memory).
Parameters
dgst pointer to the hash value to sign
dgstlen length of the hash value
kinv BIGNUM with a pre-computed inverse k (optional)
rp BIGNUM with a pre-computed rp value (optional), see ECDSA_sign_setup
eckey EC_KEY object containing a private EC key
Returns
pointer to a ECDSA_SIG structure or NULL if an error occurred
Definition at line 19 of file ecdsa_sign.c.
References EC_F_ECDSA_DO_SIGN_EX, EC_R_OPERATION_NOT_SUPPORTED, ECerr, and NULL.
Referenced by ECDSA_do_sign(), and ossl_ecdsa_sign().
ECDSA_sign()
int ECDSA_sign (int type, const unsigned char * dgst, int dgstlen, unsigned char * sig, unsigned int * siglen, EC_KEY * eckey)
Computes ECDSA signature of a given hash value using the supplied private key (note: sig must point to ECDSA_size(eckey) bytes of memory).
Parameters
type this parameter is ignored
dgst pointer to the hash value to sign
dgstlen length of the hash value
sig memory for the DER encoded created signature
siglen pointer to the length of the returned signature
eckey EC_KEY object containing a private EC key
Returns
1 on success and 0 otherwise
Definition at line 29 of file ecdsa_sign.c.
References ECDSA_sign_ex(), and NULL.
ECDSA_sign_ex()
int ECDSA_sign_ex (int type, const unsigned char * dgst, int dgstlen, unsigned char * sig, unsigned int * siglen, const BIGNUM * kinv, const BIGNUM * rp, EC_KEY * eckey)
Computes ECDSA signature of a given hash value using the supplied private key (note: sig must point to ECDSA_size(eckey) bytes of memory).
Parameters
type this parameter is ignored
dgst pointer to the hash value to sign
dgstlen length of the hash value
sig buffer to hold the DER encoded signature
siglen pointer to the length of the returned signature
kinv BIGNUM with a pre-computed inverse k (optional)
rp BIGNUM with a pre-computed rp value (optional), see ECDSA_sign_setup
eckey EC_KEY object containing a private EC key
Returns
1 on success and 0 otherwise
Definition at line 35 of file ecdsa_sign.c.
References EC_F_ECDSA_SIGN_EX, EC_R_OPERATION_NOT_SUPPORTED, ECerr, and NULL.
Referenced by ECDSA_sign().
ECDSA_sign_setup()
int ECDSA_sign_setup (EC_KEY * eckey, BN_CTX * ctx, BIGNUM ** kinv, BIGNUM ** rp)
Precompute parts of the signing operation
Parameters
eckey EC_KEY object containing a private EC key
ctx BN_CTX object (optional)
kinv BIGNUM pointer for the inverse of k
rp BIGNUM pointer for x coordinate of k * generator
Returns
1 on success and 0 otherwise
Definition at line 45 of file ecdsa_sign.c.
References EC_F_ECDSA_SIGN_SETUP, EC_R_OPERATION_NOT_SUPPORTED, ECerr, and NULL.