crypto/ec/ecdsa_ossl.c File Reference
ecdsa_ossl.c File Reference
#include <string.h>
#include <openssl/err.h>
#include <openssl/obj_mac.h>
#include <openssl/bn.h>
#include <openssl/rand.h>
#include <openssl/ec.h>
#include "ec_lcl.h"
Functions
int ossl_ecdsa_sign (int type, const unsigned char *dgst, int dlen, unsigned char *sig, unsigned int *siglen, const BIGNUM *kinv, const BIGNUM *r, EC_KEY *eckey)
int ossl_ecdsa_sign_setup (EC_KEY *eckey, BN_CTX *ctx_in, BIGNUM **kinvp, BIGNUM **rp)
ECDSA_SIG * ossl_ecdsa_sign_sig (const unsigned char *dgst, int dgst_len, const BIGNUM *in_kinv, const BIGNUM *in_r, EC_KEY *eckey)
int ossl_ecdsa_verify (int type, const unsigned char *dgst, int dgst_len, const unsigned char *sigbuf, int sig_len, EC_KEY *eckey)
int ossl_ecdsa_verify_sig (const unsigned char *dgst, int dgst_len, const ECDSA_SIG *sig, EC_KEY *eckey)
Function Documentation
ossl_ecdsa_sign()
int ossl_ecdsa_sign (int type, const unsigned char * dgst, int dlen, unsigned char * sig, unsigned int * siglen, const BIGNUM * kinv, const BIGNUM * r, EC_KEY * eckey)
Definition at line 18 of file ecdsa_ossl.c.
References ECDSA_do_sign_ex(), ECDSA_SIG_free(), i2d_ECDSA_SIG(), NULL, and RAND_seed().
ossl_ecdsa_sign_setup()
int ossl_ecdsa_sign_setup (EC_KEY * eckey, BN_CTX * ctx_in, BIGNUM ** kinvp, BIGNUM ** rp)
Definition at line 188 of file ecdsa_ossl.c.
ossl_ecdsa_sign_sig()
ECDSA_SIG* ossl_ecdsa_sign_sig (const unsigned char * dgst, int dgst_len, const BIGNUM * in_kinv, const BIGNUM * in_r, EC_KEY * eckey)
Definition at line 194 of file ecdsa_ossl.c.
References NULL.
ossl_ecdsa_verify()
int ossl_ecdsa_verify (int type, const unsigned char * dgst, int dgst_len, const unsigned char * sigbuf, int sig_len, EC_KEY * eckey)
Definition at line 319 of file ecdsa_ossl.c.
References NULL.
ossl_ecdsa_verify_sig()
int ossl_ecdsa_verify_sig (const unsigned char * dgst, int dgst_len, const ECDSA_SIG * sig, EC_KEY * eckey)
Definition at line 344 of file ecdsa_ossl.c.