crypto/ec/ecp_mont.c File Reference
ecp_mont.c File Reference
#include <openssl/err.h>
#include "ec_lcl.h"
Functions
const EC_METHOD * EC_GFp_mont_method (void)
int ec_GFp_mont_group_init (EC_GROUP *group)
void ec_GFp_mont_group_finish (EC_GROUP *group)
void ec_GFp_mont_group_clear_finish (EC_GROUP *group)
int ec_GFp_mont_group_copy (EC_GROUP *dest, const EC_GROUP *src)
int ec_GFp_mont_group_set_curve (EC_GROUP *group, const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int ec_GFp_mont_field_mul (const EC_GROUP *group, BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int ec_GFp_mont_field_sqr (const EC_GROUP *group, BIGNUM *r, const BIGNUM *a, BN_CTX *ctx)
int ec_GFp_mont_field_encode (const EC_GROUP *group, BIGNUM *r, const BIGNUM *a, BN_CTX *ctx)
int ec_GFp_mont_field_decode (const EC_GROUP *group, BIGNUM *r, const BIGNUM *a, BN_CTX *ctx)
int ec_GFp_mont_field_set_to_one (const EC_GROUP *group, BIGNUM *r, BN_CTX *ctx)
Function Documentation
ec_GFp_mont_field_decode()
int ec_GFp_mont_field_decode (const EC_GROUP * group, BIGNUM * r, const BIGNUM * a, BN_CTX * ctx)
Definition at line 220 of file ecp_mont.c.
References BN_from_montgomery(), EC_F_EC_GFP_MONT_FIELD_DECODE, EC_R_NOT_INITIALIZED, ECerr, and NULL.
ec_GFp_mont_field_encode()
int ec_GFp_mont_field_encode (const EC_GROUP * group, BIGNUM * r, const BIGNUM * a, BN_CTX * ctx)
Definition at line 209 of file ecp_mont.c.
References BN_to_montgomery(), EC_F_EC_GFP_MONT_FIELD_ENCODE, EC_R_NOT_INITIALIZED, ECerr, and NULL.
ec_GFp_mont_field_mul()
int ec_GFp_mont_field_mul (const EC_GROUP * group, BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Definition at line 187 of file ecp_mont.c.
References BN_mod_mul_montgomery(), EC_F_EC_GFP_MONT_FIELD_MUL, EC_R_NOT_INITIALIZED, ECerr, and NULL.
ec_GFp_mont_field_set_to_one()
int ec_GFp_mont_field_set_to_one (const EC_GROUP * group, BIGNUM * r, BN_CTX * ctx)
Definition at line 231 of file ecp_mont.c.
References BN_copy(), EC_F_EC_GFP_MONT_FIELD_SET_TO_ONE, EC_R_NOT_INITIALIZED, ECerr, and NULL.
ec_GFp_mont_field_sqr()
int ec_GFp_mont_field_sqr (const EC_GROUP * group, BIGNUM * r, const BIGNUM * a, BN_CTX * ctx)
Definition at line 198 of file ecp_mont.c.
References BN_mod_mul_montgomery(), EC_F_EC_GFP_MONT_FIELD_SQR, EC_R_NOT_INITIALIZED, ECerr, and NULL.
ec_GFp_mont_group_clear_finish()
void ec_GFp_mont_group_clear_finish (EC_GROUP * group)
Definition at line 94 of file ecp_mont.c.
References BN_clear_free(), BN_MONT_CTX_free(), ec_GFp_simple_group_clear_finish(), and NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_mont_group_copy()
int ec_GFp_mont_group_copy (EC_GROUP * dest, const EC_GROUP * src)
Definition at line 103 of file ecp_mont.c.
References BN_clear_free(), BN_dup(), BN_MONT_CTX_copy(), BN_MONT_CTX_free(), BN_MONT_CTX_new(), ec_GFp_simple_group_copy(), and NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_mont_group_finish()
void ec_GFp_mont_group_finish (EC_GROUP * group)
Definition at line 85 of file ecp_mont.c.
References BN_free(), BN_MONT_CTX_free(), ec_GFp_simple_group_finish(), and NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_mont_group_init()
int ec_GFp_mont_group_init (EC_GROUP * group)
Definition at line 75 of file ecp_mont.c.
References ec_GFp_simple_group_init(), and NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_mont_group_set_curve()
int ec_GFp_mont_group_set_curve (EC_GROUP * group, const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Definition at line 134 of file ecp_mont.c.
References NULL.
Referenced by EC_GFp_nistz256_method().
EC_GFp_mont_method()
const EC_METHOD* EC_GFp_mont_method (void)
Returns GFp methods using montgomery multiplication.
Returns
EC_METHOD object
Definition at line 20 of file ecp_mont.c.