crypto/ec/ecp_nistp224.c File Reference
ecp_nistp224.c File Reference
#include <openssl/opensslconf.h>
#include <stdint.h>
#include <string.h>
#include <openssl/err.h>
#include "ec_lcl.h"
Data Structures
struct NISTP224_PRE_COMP
Typedefs
typedef uint8_t u8
typedef uint64_t u64
typedef int64_t s64
typedef uint64_t limb
typedef uint128_t widelimb
typedef limb felem[4]
typedef widelimb widefelem[7]
typedef u8 felem_bytearray[28]
Functions
const EC_METHOD * EC_GFp_nistp224_method (void)
NISTP224_PRE_COMP * EC_nistp224_pre_comp_dup (NISTP224_PRE_COMP *p)
void EC_nistp224_pre_comp_free (NISTP224_PRE_COMP *p)
int ec_GFp_nistp224_group_init (EC_GROUP *group)
int ec_GFp_nistp224_group_set_curve (EC_GROUP *group, const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int ec_GFp_nistp224_point_get_affine_coordinates (const EC_GROUP *group, const EC_POINT *point, BIGNUM *x, BIGNUM *y, BN_CTX *ctx)
int ec_GFp_nistp224_points_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *scalar, size_t num, const EC_POINT *points[], const BIGNUM *scalars[], BN_CTX *ctx)
int ec_GFp_nistp224_precompute_mult (EC_GROUP *group, BN_CTX *ctx)
int ec_GFp_nistp224_have_precompute_mult (const EC_GROUP *group)
Typedef Documentation
felem
typedef limb felem[4]
Definition at line 78 of file ecp_nistp224.c.
felem_bytearray
typedef u8 felem_bytearray[28]
Definition at line 86 of file ecp_nistp224.c.
limb
typedef uint64_t limb
Definition at line 75 of file ecp_nistp224.c.
s64
typedef int64_t s64
Definition at line 53 of file ecp_nistp224.c.
u64
typedef uint64_t u64
Definition at line 52 of file ecp_nistp224.c.
u8
typedef uint8_t u8
Definition at line 51 of file ecp_nistp224.c.
widefelem
typedef widelimb widefelem[7]
Definition at line 79 of file ecp_nistp224.c.
widelimb
typedef uint128_t widelimb
Definition at line 76 of file ecp_nistp224.c.
Function Documentation
ec_GFp_nistp224_group_init()
int ec_GFp_nistp224_group_init (EC_GROUP * group)
Definition at line 1268 of file ecp_nistp224.c.
ec_GFp_nistp224_group_set_curve()
int ec_GFp_nistp224_group_set_curve (EC_GROUP * group, const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Definition at line 1276 of file ecp_nistp224.c.
ec_GFp_nistp224_have_precompute_mult()
int ec_GFp_nistp224_have_precompute_mult (const EC_GROUP * group)
Definition at line 1712 of file ecp_nistp224.c.
References HAVEPRECOMP.
EC_GFp_nistp224_method()
const EC_METHOD* EC_GFp_nistp224_method (void)
Returns 64-bit optimized methods for nistp224
Returns
EC_METHOD object
Definition at line 243 of file ecp_nistp224.c.
ec_GFp_nistp224_point_get_affine_coordinates()
int ec_GFp_nistp224_point_get_affine_coordinates (const EC_GROUP * group, const EC_POINT * point, BIGNUM * x, BIGNUM * y, BN_CTX * ctx)
Definition at line 1312 of file ecp_nistp224.c.
References EC_F_EC_GFP_NISTP224_POINT_GET_AFFINE_COORDINATES, EC_POINT_is_at_infinity(), EC_R_POINT_AT_INFINITY, and ECerr.
ec_GFp_nistp224_points_mul()
int ec_GFp_nistp224_points_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * scalar, size_t num, const EC_POINT * points[], const BIGNUM * scalars[], BN_CTX * ctx)
Definition at line 1390 of file ecp_nistp224.c.
ec_GFp_nistp224_precompute_mult()
int ec_GFp_nistp224_precompute_mult (EC_GROUP * group, BN_CTX * ctx)
Definition at line 1587 of file ecp_nistp224.c.
EC_nistp224_pre_comp_dup()
NISTP224_PRE_COMP* EC_nistp224_pre_comp_dup (NISTP224_PRE_COMP * p)
Definition at line 1238 of file ecp_nistp224.c.
References CRYPTO_UP_REF, and NULL.
Referenced by EC_GROUP_copy().
EC_nistp224_pre_comp_free()
void EC_nistp224_pre_comp_free (NISTP224_PRE_COMP * p)
Definition at line 1246 of file ecp_nistp224.c.
References CRYPTO_DOWN_REF, CRYPTO_THREAD_lock_free(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by EC_pre_comp_free().