crypto/ec/ecp_smpl.c File Reference
ecp_smpl.c File Reference
#include <openssl/err.h>
#include <openssl/symhacks.h>
#include "ec_lcl.h"
Functions
const EC_METHOD * EC_GFp_simple_method (void)
int ec_GFp_simple_group_init (EC_GROUP *group)
void ec_GFp_simple_group_finish (EC_GROUP *group)
void ec_GFp_simple_group_clear_finish (EC_GROUP *group)
int ec_GFp_simple_group_copy (EC_GROUP *dest, const EC_GROUP *src)
int ec_GFp_simple_group_set_curve (EC_GROUP *group, const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int ec_GFp_simple_group_get_curve (const EC_GROUP *group, BIGNUM *p, BIGNUM *a, BIGNUM *b, BN_CTX *ctx)
int ec_GFp_simple_group_get_degree (const EC_GROUP *group)
int ec_GFp_simple_group_check_discriminant (const EC_GROUP *group, BN_CTX *ctx)
int ec_GFp_simple_point_init (EC_POINT *point)
void ec_GFp_simple_point_finish (EC_POINT *point)
void ec_GFp_simple_point_clear_finish (EC_POINT *point)
int ec_GFp_simple_point_copy (EC_POINT *dest, const EC_POINT *src)
int ec_GFp_simple_point_set_to_infinity (const EC_GROUP *group, EC_POINT *point)
int ec_GFp_simple_set_Jprojective_coordinates_GFp (const EC_GROUP *group, EC_POINT *point, const BIGNUM *x, const BIGNUM *y, const BIGNUM *z, BN_CTX *ctx)
int ec_GFp_simple_get_Jprojective_coordinates_GFp (const EC_GROUP *group, const EC_POINT *point, BIGNUM *x, BIGNUM *y, BIGNUM *z, BN_CTX *ctx)
int ec_GFp_simple_point_set_affine_coordinates (const EC_GROUP *group, EC_POINT *point, const BIGNUM *x, const BIGNUM *y, BN_CTX *ctx)
int ec_GFp_simple_point_get_affine_coordinates (const EC_GROUP *group, const EC_POINT *point, BIGNUM *x, BIGNUM *y, BN_CTX *ctx)
int ec_GFp_simple_add (const EC_GROUP *group, EC_POINT *r, const EC_POINT *a, const EC_POINT *b, BN_CTX *ctx)
int ec_GFp_simple_dbl (const EC_GROUP *group, EC_POINT *r, const EC_POINT *a, BN_CTX *ctx)
int ec_GFp_simple_invert (const EC_GROUP *group, EC_POINT *point, BN_CTX *ctx)
int ec_GFp_simple_is_at_infinity (const EC_GROUP *group, const EC_POINT *point)
int ec_GFp_simple_is_on_curve (const EC_GROUP *group, const EC_POINT *point, BN_CTX *ctx)
int ec_GFp_simple_cmp (const EC_GROUP *group, const EC_POINT *a, const EC_POINT *b, BN_CTX *ctx)
int ec_GFp_simple_make_affine (const EC_GROUP *group, EC_POINT *point, BN_CTX *ctx)
int ec_GFp_simple_points_make_affine (const EC_GROUP *group, size_t num, EC_POINT *points[], BN_CTX *ctx)
int ec_GFp_simple_field_mul (const EC_GROUP *group, BIGNUM *r, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int ec_GFp_simple_field_sqr (const EC_GROUP *group, BIGNUM *r, const BIGNUM *a, BN_CTX *ctx)
Function Documentation
ec_GFp_simple_add()
int ec_GFp_simple_add (const EC_GROUP * group, EC_POINT * r, const EC_POINT * a, const EC_POINT * b, BN_CTX * ctx)
Definition at line 608 of file ecp_smpl.c.
References NULL.
ec_GFp_simple_cmp()
int ec_GFp_simple_cmp (const EC_GROUP * group, const EC_POINT * a, const EC_POINT * b, BN_CTX * ctx)
Definition at line 1053 of file ecp_smpl.c.
References NULL.
ec_GFp_simple_dbl()
int ec_GFp_simple_dbl (const EC_GROUP * group, EC_POINT * r, const EC_POINT * a, BN_CTX * ctx)
Definition at line 794 of file ecp_smpl.c.
References NULL.
ec_GFp_simple_field_mul()
int ec_GFp_simple_field_mul (const EC_GROUP * group, BIGNUM * r, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Definition at line 1359 of file ecp_smpl.c.
References BN_mod_mul().
ec_GFp_simple_field_sqr()
int ec_GFp_simple_field_sqr (const EC_GROUP * group, BIGNUM * r, const BIGNUM * a, BN_CTX * ctx)
Definition at line 1365 of file ecp_smpl.c.
References BN_mod_sqr().
ec_GFp_simple_get_Jprojective_coordinates_GFp()
int ec_GFp_simple_get_Jprojective_coordinates_GFp (const EC_GROUP * group, const EC_POINT * point, BIGNUM * x, BIGNUM * y, BIGNUM * z, BN_CTX * ctx)
Definition at line 427 of file ecp_smpl.c.
References NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_group_check_discriminant()
int ec_GFp_simple_group_check_discriminant (const EC_GROUP * group, BN_CTX * ctx)
Definition at line 242 of file ecp_smpl.c.
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_group_clear_finish()
void ec_GFp_simple_group_clear_finish (EC_GROUP * group)
Definition at line 112 of file ecp_smpl.c.
References BN_clear_free().
Referenced by ec_GFp_mont_group_clear_finish().
ec_GFp_simple_group_copy()
int ec_GFp_simple_group_copy (EC_GROUP * dest, const EC_GROUP * src)
Definition at line 119 of file ecp_smpl.c.
References BN_copy().
Referenced by ec_GFp_mont_group_copy(), and ec_GFp_nist_group_copy().
ec_GFp_simple_group_finish()
void ec_GFp_simple_group_finish (EC_GROUP * group)
Definition at line 105 of file ecp_smpl.c.
References BN_free().
Referenced by ec_GFp_mont_group_finish().
ec_GFp_simple_group_get_curve()
int ec_GFp_simple_group_get_curve (const EC_GROUP * group, BIGNUM * p, BIGNUM * a, BIGNUM * b, BN_CTX * ctx)
Definition at line 192 of file ecp_smpl.c.
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_group_get_degree()
int ec_GFp_simple_group_get_degree (const EC_GROUP * group)
Definition at line 237 of file ecp_smpl.c.
References BN_num_bits().
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_group_init()
int ec_GFp_simple_group_init (EC_GROUP * group)
Definition at line 90 of file ecp_smpl.c.
References BN_free(), BN_new(), and NULL.
Referenced by ec_GFp_mont_group_init().
ec_GFp_simple_group_set_curve()
int ec_GFp_simple_group_set_curve (EC_GROUP * group, const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Definition at line 133 of file ecp_smpl.c.
ec_GFp_simple_invert()
int ec_GFp_simple_invert (const EC_GROUP * group, EC_POINT * point, BN_CTX * ctx)
Definition at line 936 of file ecp_smpl.c.
References BN_is_zero(), BN_usub(), and EC_POINT_is_at_infinity().
ec_GFp_simple_is_at_infinity()
int ec_GFp_simple_is_at_infinity (const EC_GROUP * group, const EC_POINT * point)
Definition at line 945 of file ecp_smpl.c.
References BN_is_zero().
ec_GFp_simple_is_on_curve()
int ec_GFp_simple_is_on_curve (const EC_GROUP * group, const EC_POINT * point, BN_CTX * ctx)
Definition at line 950 of file ecp_smpl.c.
References NULL.
ec_GFp_simple_make_affine()
int ec_GFp_simple_make_affine (const EC_GROUP * group, EC_POINT * point, BN_CTX * ctx)
Definition at line 1161 of file ecp_smpl.c.
References NULL.
EC_GFp_simple_method()
const EC_METHOD* EC_GFp_simple_method (void)
Returns the basic GFp ec methods which provides the basis for the optimized methods.
Returns
EC_METHOD object
Definition at line 21 of file ecp_smpl.c.
ec_GFp_simple_point_clear_finish()
void ec_GFp_simple_point_clear_finish (EC_POINT * point)
Definition at line 338 of file ecp_smpl.c.
References BN_clear_free().
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_point_copy()
int ec_GFp_simple_point_copy (EC_POINT * dest, const EC_POINT * src)
Definition at line 346 of file ecp_smpl.c.
References BN_copy().
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_point_finish()
void ec_GFp_simple_point_finish (EC_POINT * point)
Definition at line 331 of file ecp_smpl.c.
References BN_free().
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_point_get_affine_coordinates()
int ec_GFp_simple_point_get_affine_coordinates (const EC_GROUP * group, const EC_POINT * point, BIGNUM * x, BIGNUM * y, BN_CTX * ctx)
Definition at line 494 of file ecp_smpl.c.
References NULL, and Z.
ec_GFp_simple_point_init()
int ec_GFp_simple_point_init (EC_POINT * point)
Definition at line 315 of file ecp_smpl.c.
References BN_free(), BN_new(), and NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_point_set_affine_coordinates()
int ec_GFp_simple_point_set_affine_coordinates (const EC_GROUP * group, EC_POINT * point, const BIGNUM * x, const BIGNUM * y, BN_CTX * ctx)
Definition at line 476 of file ecp_smpl.c.
References BN_value_one(), EC_F_EC_GFP_SIMPLE_POINT_SET_AFFINE_COORDINATES, EC_POINT_set_Jprojective_coordinates_GFp(), ECerr, ERR_R_PASSED_NULL_PARAMETER, and NULL.
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_point_set_to_infinity()
int ec_GFp_simple_point_set_to_infinity (const EC_GROUP * group, EC_POINT * point)
Definition at line 359 of file ecp_smpl.c.
References BN_zero.
Referenced by EC_GFp_nistz256_method().
ec_GFp_simple_points_make_affine()
int ec_GFp_simple_points_make_affine (const EC_GROUP * group, size_t num, EC_POINT * points[], BN_CTX * ctx)
Definition at line 1200 of file ecp_smpl.c.
References NULL.
ec_GFp_simple_set_Jprojective_coordinates_GFp()
int ec_GFp_simple_set_Jprojective_coordinates_GFp (const EC_GROUP * group, EC_POINT * point, const BIGNUM * x, const BIGNUM * y, const BIGNUM * z, BN_CTX * ctx)
Definition at line 367 of file ecp_smpl.c.
References NULL.
Referenced by EC_GFp_nistz256_method().