crypto/ec/ecp_nistp256.c File Reference
ecp_nistp256.c File Reference
#include <openssl/opensslconf.h>
#include <stdint.h>
#include <string.h>
#include <openssl/err.h>
#include "ec_lcl.h"
Data Structures
struct NISTP256_PRE_COMP
Macros
#define NLIMBS 4
#define two105m41m9 (((limb)1) << 105) - (((limb)1) << 41) - (((limb)1) << 9)
#define two105 (((limb)1) << 105)
#define two105m41p9 (((limb)1) << 105) - (((limb)1) << 41) + (((limb)1) << 9)
#define two107m43m11 (((limb)1) << 107) - (((limb)1) << 43) - (((limb)1) << 11)
#define two107 (((limb)1) << 107)
#define two107m43p11 (((limb)1) << 107) - (((limb)1) << 43) + (((limb)1) << 11)
#define two64m0 (((limb)1) << 64) - 1
#define two110p32m0 (((limb)1) << 110) + (((limb)1) << 32) - 1
#define two64m46 (((limb)1) << 64) - (((limb)1) << 46)
#define two64m32 (((limb)1) << 64) - (((limb)1) << 32)
#define two100m36m4 (((limb)1) << 100) - (((limb)1) << 36) - (((limb)1) << 4)
#define two100 (((limb)1) << 100)
#define two100m36p4 (((limb)1) << 100) - (((limb)1) << 36) + (((limb)1) << 4)
Typedefs
typedef uint8_t u8
typedef uint32_t u32
typedef uint64_t u64
typedef int64_t s64
typedef u8 felem_bytearray[32]
typedef uint128_t limb
typedef limb felem[NLIMBS]
typedef limb longfelem[NLIMBS *2]
typedef u64 smallfelem[NLIMBS]
Functions
const EC_METHOD * EC_GFp_nistp256_method (void)
NISTP256_PRE_COMP * EC_nistp256_pre_comp_dup (NISTP256_PRE_COMP *p)
void EC_nistp256_pre_comp_free (NISTP256_PRE_COMP *pre)
int ec_GFp_nistp256_group_init (EC_GROUP *group)
int ec_GFp_nistp256_group_set_curve (EC_GROUP *group, const BIGNUM *p, const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx)
int ec_GFp_nistp256_point_get_affine_coordinates (const EC_GROUP *group, const EC_POINT *point, BIGNUM *x, BIGNUM *y, BN_CTX *ctx)
int ec_GFp_nistp256_points_mul (const EC_GROUP *group, EC_POINT *r, const BIGNUM *scalar, size_t num, const EC_POINT *points[], const BIGNUM *scalars[], BN_CTX *ctx)
int ec_GFp_nistp256_precompute_mult (EC_GROUP *group, BN_CTX *ctx)
int ec_GFp_nistp256_have_precompute_mult (const EC_GROUP *group)
Macro Definition Documentation
NLIMBS
#define NLIMBS 4
Definition at line 114 of file ecp_nistp256.c.
two100
#define two100 (((limb)1) << 100)
Definition at line 728 of file ecp_nistp256.c.
two100m36m4
#define two100m36m4 (((limb)1) << 100) - (((limb)1) << 36) - (((limb)1) << 4)
Definition at line 727 of file ecp_nistp256.c.
two100m36p4
#define two100m36p4 (((limb)1) << 100) - (((limb)1) << 36) + (((limb)1) << 4)
Definition at line 729 of file ecp_nistp256.c.
two105
#define two105 (((limb)1) << 105)
Definition at line 261 of file ecp_nistp256.c.
two105m41m9
#define two105m41m9 (((limb)1) << 105) - (((limb)1) << 41) - (((limb)1) << 9)
Definition at line 260 of file ecp_nistp256.c.
two105m41p9
#define two105m41p9 (((limb)1) << 105) - (((limb)1) << 41) + (((limb)1) << 9)
Definition at line 262 of file ecp_nistp256.c.
two107
#define two107 (((limb)1) << 107)
Definition at line 306 of file ecp_nistp256.c.
two107m43m11
#define two107m43m11 (((limb)1) << 107) - (((limb)1) << 43) - (((limb)1) << 11)
Definition at line 305 of file ecp_nistp256.c.
two107m43p11
#define two107m43p11 (((limb)1) << 107) - (((limb)1) << 43) + (((limb)1) << 11)
Definition at line 307 of file ecp_nistp256.c.
two110p32m0
#define two110p32m0 (((limb)1) << 110) + (((limb)1) << 32) - 1
Definition at line 377 of file ecp_nistp256.c.
two64m0
#define two64m0 (((limb)1) << 64) - 1
Definition at line 376 of file ecp_nistp256.c.
two64m32
#define two64m32 (((limb)1) << 64) - (((limb)1) << 32)
Definition at line 379 of file ecp_nistp256.c.
two64m46
#define two64m46 (((limb)1) << 64) - (((limb)1) << 46)
Definition at line 378 of file ecp_nistp256.c.
Typedef Documentation
felem
typedef limb felem[NLIMBS]
Definition at line 117 of file ecp_nistp256.c.
felem_bytearray
typedef u8 felem_bytearray[32]
Definition at line 64 of file ecp_nistp256.c.
limb
typedef uint128_t limb
Definition at line 116 of file ecp_nistp256.c.
longfelem
typedef limb longfelem[NLIMBS *2]
Definition at line 118 of file ecp_nistp256.c.
s64
typedef int64_t s64
Definition at line 56 of file ecp_nistp256.c.
smallfelem
typedef u64 smallfelem[NLIMBS]
Definition at line 119 of file ecp_nistp256.c.
u32
typedef uint32_t u32
Definition at line 54 of file ecp_nistp256.c.
u64
typedef uint64_t u64
Definition at line 55 of file ecp_nistp256.c.
u8
typedef uint8_t u8
Definition at line 53 of file ecp_nistp256.c.
Function Documentation
ec_GFp_nistp256_group_init()
int ec_GFp_nistp256_group_init (EC_GROUP * group)
Definition at line 1884 of file ecp_nistp256.c.
ec_GFp_nistp256_group_set_curve()
int ec_GFp_nistp256_group_set_curve (EC_GROUP * group, const BIGNUM * p, const BIGNUM * a, const BIGNUM * b, BN_CTX * ctx)
Definition at line 1892 of file ecp_nistp256.c.
ec_GFp_nistp256_have_precompute_mult()
int ec_GFp_nistp256_have_precompute_mult (const EC_GROUP * group)
Definition at line 2346 of file ecp_nistp256.c.
References HAVEPRECOMP.
EC_GFp_nistp256_method()
const EC_METHOD* EC_GFp_nistp256_method (void)
Returns 64-bit optimized methods for nistp256
Returns
EC_METHOD object
Definition at line 1772 of file ecp_nistp256.c.
ec_GFp_nistp256_point_get_affine_coordinates()
int ec_GFp_nistp256_point_get_affine_coordinates (const EC_GROUP * group, const EC_POINT * point, BIGNUM * x, BIGNUM * y, BN_CTX * ctx)
Definition at line 1928 of file ecp_nistp256.c.
References EC_F_EC_GFP_NISTP256_POINT_GET_AFFINE_COORDINATES, EC_POINT_is_at_infinity(), EC_R_POINT_AT_INFINITY, and ECerr.
ec_GFp_nistp256_points_mul()
int ec_GFp_nistp256_points_mul (const EC_GROUP * group, EC_POINT * r, const BIGNUM * scalar, size_t num, const EC_POINT * points[], const BIGNUM * scalars[], BN_CTX * ctx)
Definition at line 2007 of file ecp_nistp256.c.
ec_GFp_nistp256_precompute_mult()
int ec_GFp_nistp256_precompute_mult (EC_GROUP * group, BN_CTX * ctx)
Definition at line 2210 of file ecp_nistp256.c.
EC_nistp256_pre_comp_dup()
NISTP256_PRE_COMP* EC_nistp256_pre_comp_dup (NISTP256_PRE_COMP * p)
Definition at line 1854 of file ecp_nistp256.c.
References CRYPTO_UP_REF, and NULL.
Referenced by EC_GROUP_copy().
EC_nistp256_pre_comp_free()
void EC_nistp256_pre_comp_free (NISTP256_PRE_COMP * pre)
Definition at line 1862 of file ecp_nistp256.c.
References CRYPTO_DOWN_REF, CRYPTO_THREAD_lock_free(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by EC_pre_comp_free().