crypto/ec/ecp_nistz256.c File Reference
ecp_nistz256.c File Reference
#include <string.h>
#include "internal/cryptlib.h"
#include "internal/bn_int.h"
#include "ec_lcl.h"
Data Structures
struct P256_POINT
struct P256_POINT_AFFINE
struct NISTZ256_PRE_COMP
Macros
#define TOBN(hi, lo) lo,hi
#define ALIGN32
#define ALIGNPTR(p, N) ((unsigned char *)p+N-(size_t)p%N)
#define P256_LIMBS (256/BN_BITS2)
Typedefs
typedef unsigned short u16
typedef P256_POINT_AFFINE PRECOMP256_ROW[64]
Functions
void ecp_nistz256_add (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS], const BN_ULONG b[P256_LIMBS])
void ecp_nistz256_mul_by_2 (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS])
void ecp_nistz256_mul_by_3 (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS])
void ecp_nistz256_div_by_2 (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS])
void ecp_nistz256_sub (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS], const BN_ULONG b[P256_LIMBS])
void ecp_nistz256_neg (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS])
void ecp_nistz256_mul_mont (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS], const BN_ULONG b[P256_LIMBS])
void ecp_nistz256_sqr_mont (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS])
void ecp_nistz256_from_mont (BN_ULONG res[P256_LIMBS], const BN_ULONG in[P256_LIMBS])
void ecp_nistz256_to_mont (BN_ULONG res[P256_LIMBS], const BN_ULONG in[P256_LIMBS])
void ecp_nistz256_scatter_w5 (P256_POINT *val, const P256_POINT *in_t, int idx)
void ecp_nistz256_gather_w5 (P256_POINT *val, const P256_POINT *in_t, int idx)
void ecp_nistz256_scatter_w7 (P256_POINT_AFFINE *val, const P256_POINT_AFFINE *in_t, int idx)
void ecp_nistz256_gather_w7 (P256_POINT_AFFINE *val, const P256_POINT_AFFINE *in_t, int idx)
void ecp_nistz256_point_double (P256_POINT *r, const P256_POINT *a)
void ecp_nistz256_point_add (P256_POINT *r, const P256_POINT *a, const P256_POINT *b)
void ecp_nistz256_point_add_affine (P256_POINT *r, const P256_POINT *a, const P256_POINT_AFFINE *b)
NISTZ256_PRE_COMP * EC_nistz256_pre_comp_dup (NISTZ256_PRE_COMP *p)
void EC_nistz256_pre_comp_free (NISTZ256_PRE_COMP *pre)
const EC_METHOD * EC_GFp_nistz256_method (void)
Variables
const PRECOMP256_ROW ecp_nistz256_precomputed [37]
Macro Definition Documentation
ALIGN32
#define ALIGN32
Definition at line 55 of file ecp_nistz256.c.
ALIGNPTR
#define ALIGNPTR (p, N) ((unsigned char *)p+N-(size_t)p%N)
Definition at line 58 of file ecp_nistz256.c.
P256_LIMBS
#define P256_LIMBS (256/BN_BITS2)
Definition at line 59 of file ecp_nistz256.c.
TOBN
#define TOBN (hi, lo) lo,hi
Definition at line 45 of file ecp_nistz256.c.
Typedef Documentation
PRECOMP256_ROW
typedef P256_POINT_AFFINE PRECOMP256_ROW[64]
Definition at line 74 of file ecp_nistz256.c.
u16
typedef unsigned short u16
Definition at line 61 of file ecp_nistz256.c.
Function Documentation
EC_GFp_nistz256_method()
const EC_METHOD* EC_GFp_nistz256_method (void)
Definition at line 1516 of file ecp_nistz256.c.
References EC_FLAGS_DEFAULT_OCT, ec_GFp_mont_group_clear_finish(), ec_GFp_mont_group_copy(), ec_GFp_mont_group_finish(), ec_GFp_mont_group_init(), ec_GFp_mont_group_set_curve(), ec_GFp_simple_get_Jprojective_coordinates_GFp(), ec_GFp_simple_group_check_discriminant(), ec_GFp_simple_group_get_curve(), ec_GFp_simple_group_get_degree(), ec_GFp_simple_point_clear_finish(), ec_GFp_simple_point_copy(), ec_GFp_simple_point_finish(), ec_GFp_simple_point_init(), ec_GFp_simple_point_set_affine_coordinates(), ec_GFp_simple_point_set_to_infinity(), ec_GFp_simple_set_Jprojective_coordinates_GFp(), ec_group_simple_order_bits(), and NID_X9_62_prime_field.
EC_nistz256_pre_comp_dup()
NISTZ256_PRE_COMP* EC_nistz256_pre_comp_dup (NISTZ256_PRE_COMP * p)
Definition at line 1476 of file ecp_nistz256.c.
References CRYPTO_UP_REF, and NULL.
Referenced by EC_GROUP_copy().
EC_nistz256_pre_comp_free()
void EC_nistz256_pre_comp_free (NISTZ256_PRE_COMP * pre)
Definition at line 1484 of file ecp_nistz256.c.
References CRYPTO_DOWN_REF, CRYPTO_THREAD_lock_free(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by EC_pre_comp_free().
ecp_nistz256_add()
void ecp_nistz256_add (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS], const BN_ULONG b[P256_LIMBS])
ecp_nistz256_div_by_2()
void ecp_nistz256_div_by_2 (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS])
ecp_nistz256_from_mont()
void ecp_nistz256_from_mont (BN_ULONG res[P256_LIMBS], const BN_ULONG in[P256_LIMBS])
Referenced by poly1305_init().
ecp_nistz256_gather_w5()
void ecp_nistz256_gather_w5 (P256_POINT * val, const P256_POINT * in_t, int idx)
ecp_nistz256_gather_w7()
void ecp_nistz256_gather_w7 (P256_POINT_AFFINE * val, const P256_POINT_AFFINE * in_t, int idx)
ecp_nistz256_mul_by_2()
void ecp_nistz256_mul_by_2 (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS])
ecp_nistz256_mul_by_3()
void ecp_nistz256_mul_by_3 (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS])
ecp_nistz256_mul_mont()
void ecp_nistz256_mul_mont (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS], const BN_ULONG b[P256_LIMBS])
Referenced by poly1305_init().
ecp_nistz256_neg()
void ecp_nistz256_neg (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS])
ecp_nistz256_point_add()
void ecp_nistz256_point_add (P256_POINT * r, const P256_POINT * a, const P256_POINT * b)
ecp_nistz256_point_add_affine()
void ecp_nistz256_point_add_affine (P256_POINT * r, const P256_POINT * a, const P256_POINT_AFFINE * b)
ecp_nistz256_point_double()
void ecp_nistz256_point_double (P256_POINT * r, const P256_POINT * a)
ecp_nistz256_scatter_w5()
void ecp_nistz256_scatter_w5 (P256_POINT * val, const P256_POINT * in_t, int idx)
ecp_nistz256_scatter_w7()
void ecp_nistz256_scatter_w7 (P256_POINT_AFFINE * val, const P256_POINT_AFFINE * in_t, int idx)
ecp_nistz256_sqr_mont()
void ecp_nistz256_sqr_mont (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS])
ecp_nistz256_sub()
void ecp_nistz256_sub (BN_ULONG res[P256_LIMBS], const BN_ULONG a[P256_LIMBS], const BN_ULONG b[P256_LIMBS])
ecp_nistz256_to_mont()
void ecp_nistz256_to_mont (BN_ULONG res[P256_LIMBS], const BN_ULONG in[P256_LIMBS])
Referenced by poly1305_init().
Variable Documentation
ecp_nistz256_precomputed
const PRECOMP256_ROW ecp_nistz256_precomputed[37]