crypto/evp/encode.c File Reference
encode.c File Reference
#include <stdio.h>
#include <limits.h>
#include "internal/cryptlib.h"
#include <openssl/evp.h>
#include "evp_locl.h"
Macros
#define conv_bin2ascii(a) (data_bin2ascii[(a)&0x3f])
#define BIN_PER_LINE (64/4*3)
#define CHUNKS_PER_LINE (64/4)
#define CHAR_PER_LINE (64+1)
#define B64_EOLN 0xF0
#define B64_CR 0xF1
#define B64_EOF 0xF2
#define B64_WS 0xE0
#define B64_ERROR 0xFF
#define B64_NOT_BASE64(a) (((a)|0x13) == 0xF3)
#define B64_BASE64(a) (!B64_NOT_BASE64(a))
Functions
EVP_ENCODE_CTX * EVP_ENCODE_CTX_new (void)
void EVP_ENCODE_CTX_free (EVP_ENCODE_CTX *ctx)
int EVP_ENCODE_CTX_copy (EVP_ENCODE_CTX *dctx, EVP_ENCODE_CTX *sctx)
int EVP_ENCODE_CTX_num (EVP_ENCODE_CTX *ctx)
void EVP_EncodeInit (EVP_ENCODE_CTX *ctx)
int EVP_EncodeUpdate (EVP_ENCODE_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl)
void EVP_EncodeFinal (EVP_ENCODE_CTX *ctx, unsigned char *out, int *outl)
int EVP_EncodeBlock (unsigned char *t, const unsigned char *f, int dlen)
void EVP_DecodeInit (EVP_ENCODE_CTX *ctx)
int EVP_DecodeUpdate (EVP_ENCODE_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl)
int EVP_DecodeBlock (unsigned char *t, const unsigned char *f, int n)
int EVP_DecodeFinal (EVP_ENCODE_CTX *ctx, unsigned char *out, int *outl)
Macro Definition Documentation
B64_BASE64
#define B64_BASE64 (a) (!B64_NOT_BASE64(a))
Definition at line 58 of file encode.c.
B64_CR
#define B64_CR 0xF1
Definition at line 53 of file encode.c.
B64_EOF
#define B64_EOF 0xF2
Definition at line 54 of file encode.c.
B64_EOLN
#define B64_EOLN 0xF0
Definition at line 52 of file encode.c.
B64_ERROR
#define B64_ERROR 0xFF
Definition at line 56 of file encode.c.
B64_NOT_BASE64
#define B64_NOT_BASE64 (a) (((a)|0x13) == 0xF3)
Definition at line 57 of file encode.c.
B64_WS
#define B64_WS 0xE0
Definition at line 55 of file encode.c.
BIN_PER_LINE
#define BIN_PER_LINE (64/4*3)
Definition at line 37 of file encode.c.
CHAR_PER_LINE
#define CHAR_PER_LINE (64+1)
Definition at line 39 of file encode.c.
CHUNKS_PER_LINE
#define CHUNKS_PER_LINE (64/4)
Definition at line 38 of file encode.c.
conv_bin2ascii
#define conv_bin2ascii (a) (data_bin2ascii[(a)&0x3f])
Definition at line 18 of file encode.c.
Function Documentation
EVP_DecodeBlock()
int EVP_DecodeBlock (unsigned char * t, const unsigned char * f, int n)
Definition at line 351 of file encode.c.
Referenced by NETSCAPE_SPKI_b64_decode().
EVP_DecodeFinal()
int EVP_DecodeFinal (EVP_ENCODE_CTX * ctx, unsigned char * out, int * outl)
Definition at line 390 of file encode.c.
EVP_DecodeInit()
void EVP_DecodeInit (EVP_ENCODE_CTX * ctx)
Definition at line 218 of file encode.c.
EVP_DecodeUpdate()
int EVP_DecodeUpdate (EVP_ENCODE_CTX * ctx, unsigned char * out, int * outl, const unsigned char * in, int inl)
Definition at line 247 of file encode.c.
EVP_ENCODE_CTX_copy()
int EVP_ENCODE_CTX_copy (EVP_ENCODE_CTX * dctx, EVP_ENCODE_CTX * sctx)
Definition at line 106 of file encode.c.
EVP_ENCODE_CTX_free()
void EVP_ENCODE_CTX_free (EVP_ENCODE_CTX * ctx)
Definition at line 101 of file encode.c.
References OPENSSL_free.
EVP_ENCODE_CTX_new()
EVP_ENCODE_CTX* EVP_ENCODE_CTX_new (void)
Definition at line 96 of file encode.c.
References OPENSSL_zalloc.
Referenced by PEM_read_bio().
EVP_ENCODE_CTX_num()
int EVP_ENCODE_CTX_num (EVP_ENCODE_CTX * ctx)
Definition at line 113 of file encode.c.
EVP_EncodeBlock()
int EVP_EncodeBlock (unsigned char * t, const unsigned char * f, int dlen)
Definition at line 187 of file encode.c.
Referenced by NETSCAPE_SPKI_b64_encode().
EVP_EncodeFinal()
void EVP_EncodeFinal (EVP_ENCODE_CTX * ctx, unsigned char * out, int * outl)
Definition at line 174 of file encode.c.
EVP_EncodeInit()
void EVP_EncodeInit (EVP_ENCODE_CTX * ctx)
Definition at line 118 of file encode.c.
EVP_EncodeUpdate()
int EVP_EncodeUpdate (EVP_ENCODE_CTX * ctx, unsigned char * out, int * outl, const unsigned char * in, int inl)
Definition at line 125 of file encode.c.