crypto/engine/eng_list.c File Reference
eng_list.c File Reference
#include "eng_int.h"
Functions
ENGINE * ENGINE_get_first (void)
ENGINE * ENGINE_get_last (void)
ENGINE * ENGINE_get_next (ENGINE *e)
ENGINE * ENGINE_get_prev (ENGINE *e)
int ENGINE_add (ENGINE *e)
int ENGINE_remove (ENGINE *e)
ENGINE * ENGINE_by_id (const char *id)
int ENGINE_up_ref (ENGINE *e)
Function Documentation
ENGINE_add()
int ENGINE_add (ENGINE * e)
Definition at line 215 of file eng_list.c.
References CRYPTO_THREAD_write_lock(), ENGINE_F_ENGINE_ADD, ENGINE_R_ID_OR_NAME_MISSING, ENGINEerr, ERR_R_PASSED_NULL_PARAMETER, global_engine_lock, and NULL.
ENGINE_by_id()
ENGINE* ENGINE_by_id (const char * id)
Definition at line 282 of file eng_list.c.
References CRYPTO_THREAD_write_lock(), ENGINE_F_ENGINE_BY_ID, engine_lock_init, ENGINEerr, ERR_R_MALLOC_FAILURE, ERR_R_PASSED_NULL_PARAMETER, global_engine_lock, NULL, and RUN_ONCE.
ENGINE_get_first()
ENGINE* ENGINE_get_first (void)
Definition at line 135 of file eng_list.c.
Referenced by ENGINE_register_all_ciphers(), ENGINE_register_all_complete(), ENGINE_register_all_DH(), ENGINE_register_all_digests(), ENGINE_register_all_DSA(), ENGINE_register_all_EC(), ENGINE_register_all_pkey_asn1_meths(), ENGINE_register_all_pkey_meths(), ENGINE_register_all_RAND(), and ENGINE_register_all_RSA().
ENGINE_get_last()
ENGINE* ENGINE_get_last (void)
Definition at line 154 of file eng_list.c.
ENGINE_get_next()
ENGINE* ENGINE_get_next (ENGINE * e)
Definition at line 174 of file eng_list.c.
Referenced by ENGINE_register_all_ciphers(), ENGINE_register_all_complete(), ENGINE_register_all_DH(), ENGINE_register_all_digests(), ENGINE_register_all_DSA(), ENGINE_register_all_EC(), ENGINE_register_all_pkey_asn1_meths(), ENGINE_register_all_pkey_meths(), ENGINE_register_all_RAND(), and ENGINE_register_all_RSA().
ENGINE_get_prev()
ENGINE* ENGINE_get_prev (ENGINE * e)
Definition at line 194 of file eng_list.c.
ENGINE_remove()
int ENGINE_remove (ENGINE * e)
Definition at line 236 of file eng_list.c.
References CRYPTO_THREAD_write_lock(), ENGINE_F_ENGINE_REMOVE, ENGINEerr, ERR_R_PASSED_NULL_PARAMETER, global_engine_lock, and NULL.
ENGINE_up_ref()
int ENGINE_up_ref (ENGINE * e)
Definition at line 345 of file eng_list.c.
References CRYPTO_UP_REF, ENGINE_F_ENGINE_UP_REF, ENGINEerr, ERR_R_PASSED_NULL_PARAMETER, global_engine_lock, and NULL.