crypto/engine/eng_table.c File Reference
eng_table.c File Reference
#include "internal/cryptlib.h"
#include <openssl/evp.h>
#include <openssl/lhash.h>
#include "eng_int.h"
Data Structures
struct ENGINE_PILE
struct ENGINE_TABLE
struct ENGINE_PILE_DOALL
Functions
unsigned int ENGINE_get_table_flags (void)
void ENGINE_set_table_flags (unsigned int flags)
int engine_table_register (ENGINE_TABLE **table, ENGINE_CLEANUP_CB *cleanup, ENGINE *e, const int *nids, int num_nids, int setdefault)
IMPLEMENT_LHASH_DOALL_ARG (ENGINE_PILE, ENGINE)
void engine_table_unregister (ENGINE_TABLE **table, ENGINE *e)
void engine_table_cleanup (ENGINE_TABLE **table)
ENGINE * engine_table_select (ENGINE_TABLE **table, int nid)
IMPLEMENT_LHASH_DOALL_ARG_CONST (ENGINE_PILE, ENGINE_PILE_DOALL)
void engine_table_doall (ENGINE_TABLE *table, engine_table_doall_cb *cb, void *arg)
Function Documentation
ENGINE_get_table_flags()
unsigned int ENGINE_get_table_flags (void)
Definition at line 43 of file eng_table.c.
ENGINE_set_table_flags()
void ENGINE_set_table_flags (unsigned int flags)
Definition at line 48 of file eng_table.c.
engine_table_cleanup()
void engine_table_cleanup (ENGINE_TABLE ** table)
Definition at line 175 of file eng_table.c.
References CRYPTO_THREAD_write_lock(), and global_engine_lock.
engine_table_doall()
void engine_table_doall (ENGINE_TABLE * table, engine_table_doall_cb * cb, void * arg)
Definition at line 295 of file eng_table.c.
Referenced by ENGINE_pkey_asn1_find_str().
engine_table_register()
int engine_table_register (ENGINE_TABLE ** table, ENGINE_CLEANUP_CB * cleanup, ENGINE * e, const int * nids, int num_nids, int setdefault)
Definition at line 82 of file eng_table.c.
Referenced by ENGINE_register_ciphers(), ENGINE_register_DH(), ENGINE_register_digests(), ENGINE_register_DSA(), ENGINE_register_EC(), ENGINE_register_pkey_asn1_meths(), ENGINE_register_pkey_meths(), ENGINE_register_RAND(), ENGINE_register_RSA(), ENGINE_set_default_ciphers(), ENGINE_set_default_DH(), ENGINE_set_default_digests(), ENGINE_set_default_DSA(), ENGINE_set_default_EC(), ENGINE_set_default_pkey_asn1_meths(), ENGINE_set_default_pkey_meths(), ENGINE_set_default_RAND(), and ENGINE_set_default_RSA().
engine_table_select()
ENGINE* engine_table_select (ENGINE_TABLE ** table, int nid)
Definition at line 188 of file eng_table.c.
Referenced by ENGINE_get_cipher_engine(), ENGINE_get_default_DH(), ENGINE_get_default_DSA(), ENGINE_get_default_EC(), ENGINE_get_default_RAND(), ENGINE_get_default_RSA(), ENGINE_get_digest_engine(), ENGINE_get_pkey_asn1_meth_engine(), and ENGINE_get_pkey_meth_engine().
engine_table_unregister()
void engine_table_unregister (ENGINE_TABLE ** table, ENGINE * e)
Definition at line 157 of file eng_table.c.
References CRYPTO_THREAD_write_lock(), and global_engine_lock.
Referenced by ENGINE_unregister_ciphers(), ENGINE_unregister_DH(), ENGINE_unregister_digests(), ENGINE_unregister_DSA(), ENGINE_unregister_EC(), ENGINE_unregister_pkey_asn1_meths(), ENGINE_unregister_pkey_meths(), ENGINE_unregister_RAND(), and ENGINE_unregister_RSA().
IMPLEMENT_LHASH_DOALL_ARG()
IMPLEMENT_LHASH_DOALL_ARG (ENGINE_PILE , ENGINE)
IMPLEMENT_LHASH_DOALL_ARG_CONST()
IMPLEMENT_LHASH_DOALL_ARG_CONST (ENGINE_PILE , ENGINE_PILE_DOALL)