crypto/engine/eng_pkey.c File Reference
eng_pkey.c File Reference
#include "eng_int.h"
Functions
int ENGINE_set_load_privkey_function (ENGINE *e, ENGINE_LOAD_KEY_PTR loadpriv_f)
int ENGINE_set_load_pubkey_function (ENGINE *e, ENGINE_LOAD_KEY_PTR loadpub_f)
int ENGINE_set_load_ssl_client_cert_function (ENGINE *e, ENGINE_SSL_CLIENT_CERT_PTR loadssl_f)
ENGINE_LOAD_KEY_PTR ENGINE_get_load_privkey_function (const ENGINE *e)
ENGINE_LOAD_KEY_PTR ENGINE_get_load_pubkey_function (const ENGINE *e)
ENGINE_SSL_CLIENT_CERT_PTR ENGINE_get_ssl_client_cert_function (const ENGINE *e)
EVP_PKEY * ENGINE_load_private_key (ENGINE *e, const char *key_id, UI_METHOD *ui_method, void *callback_data)
EVP_PKEY * ENGINE_load_public_key (ENGINE *e, const char *key_id, UI_METHOD *ui_method, void *callback_data)
int ENGINE_load_ssl_client_cert (ENGINE *e, SSL *s, STACK_OF(X509_NAME) *ca_dn, X509 **pcert, EVP_PKEY **ppkey, STACK_OF(X509) **pother, UI_METHOD *ui_method, void *callback_data)
Function Documentation
ENGINE_get_load_privkey_function()
ENGINE_LOAD_KEY_PTR ENGINE_get_load_privkey_function (const ENGINE * e)
Definition at line 35 of file eng_pkey.c.
ENGINE_get_load_pubkey_function()
ENGINE_LOAD_KEY_PTR ENGINE_get_load_pubkey_function (const ENGINE * e)
Definition at line 40 of file eng_pkey.c.
ENGINE_get_ssl_client_cert_function()
ENGINE_SSL_CLIENT_CERT_PTR ENGINE_get_ssl_client_cert_function (const ENGINE * e)
Definition at line 45 of file eng_pkey.c.
Referenced by SSL_CTX_set_client_cert_engine().
ENGINE_load_private_key()
EVP_PKEY* ENGINE_load_private_key (ENGINE * e, const char * key_id, UI_METHOD * ui_method, void * callback_data)
Definition at line 53 of file eng_pkey.c.
Referenced by load_key().
ENGINE_load_public_key()
EVP_PKEY* ENGINE_load_public_key (ENGINE * e, const char * key_id, UI_METHOD * ui_method, void * callback_data)
Definition at line 84 of file eng_pkey.c.
Referenced by load_pubkey().
ENGINE_load_ssl_client_cert()
int ENGINE_load_ssl_client_cert (ENGINE * e, SSL * s, STACK_OF(X509_NAME) * ca_dn, X509 ** pcert, EVP_PKEY ** ppkey, STACK_OF(X509) ** pother, UI_METHOD * ui_method, void * callback_data)
Definition at line 114 of file eng_pkey.c.
Referenced by ssl_do_client_cert_cb().
ENGINE_set_load_privkey_function()
int ENGINE_set_load_privkey_function (ENGINE * e, ENGINE_LOAD_KEY_PTR loadpriv_f)
Definition at line 14 of file eng_pkey.c.
ENGINE_set_load_pubkey_function()
int ENGINE_set_load_pubkey_function (ENGINE * e, ENGINE_LOAD_KEY_PTR loadpub_f)
Definition at line 21 of file eng_pkey.c.
ENGINE_set_load_ssl_client_cert_function()
int ENGINE_set_load_ssl_client_cert_function (ENGINE * e, ENGINE_SSL_CLIENT_CERT_PTR loadssl_f)
Definition at line 27 of file eng_pkey.c.