crypto/engine/eng_lib.c File Reference
eng_lib.c File Reference
#include "eng_int.h"
#include <openssl/rand.h>
#include "internal/refcount.h"
Functions
DEFINE_RUN_ONCE (do_engine_lock_init)
ENGINE * ENGINE_new (void)
void engine_set_all_null (ENGINE *e)
int engine_free_util (ENGINE *e, int not_locked)
int ENGINE_free (ENGINE *e)
void engine_cleanup_add_first (ENGINE_CLEANUP_CB *cb)
void engine_cleanup_add_last (ENGINE_CLEANUP_CB *cb)
void engine_cleanup_int (void)
int ENGINE_set_ex_data (ENGINE *e, int idx, void *arg)
void * ENGINE_get_ex_data (const ENGINE *e, int idx)
int ENGINE_set_id (ENGINE *e, const char *id)
int ENGINE_set_name (ENGINE *e, const char *name)
int ENGINE_set_destroy_function (ENGINE *e, ENGINE_GEN_INT_FUNC_PTR destroy_f)
int ENGINE_set_init_function (ENGINE *e, ENGINE_GEN_INT_FUNC_PTR init_f)
int ENGINE_set_finish_function (ENGINE *e, ENGINE_GEN_INT_FUNC_PTR finish_f)
int ENGINE_set_ctrl_function (ENGINE *e, ENGINE_CTRL_FUNC_PTR ctrl_f)
int ENGINE_set_flags (ENGINE *e, int flags)
int ENGINE_set_cmd_defns (ENGINE *e, const ENGINE_CMD_DEFN *defns)
const char * ENGINE_get_id (const ENGINE *e)
const char * ENGINE_get_name (const ENGINE *e)
ENGINE_GEN_INT_FUNC_PTR ENGINE_get_destroy_function (const ENGINE *e)
ENGINE_GEN_INT_FUNC_PTR ENGINE_get_init_function (const ENGINE *e)
ENGINE_GEN_INT_FUNC_PTR ENGINE_get_finish_function (const ENGINE *e)
ENGINE_CTRL_FUNC_PTR ENGINE_get_ctrl_function (const ENGINE *e)
int ENGINE_get_flags (const ENGINE *e)
const ENGINE_CMD_DEFN * ENGINE_get_cmd_defns (const ENGINE *e)
void * ENGINE_get_static_state (void)
Variables
CRYPTO_RWLOCK * global_engine_lock
CRYPTO_ONCE engine_lock_init = CRYPTO_ONCE_STATIC_INIT
Function Documentation
DEFINE_RUN_ONCE()
DEFINE_RUN_ONCE (do_engine_lock_init)
Definition at line 20 of file eng_lib.c.
References CRYPTO_THREAD_lock_new(), global_engine_lock, NULL, and OPENSSL_init_crypto().
engine_cleanup_add_first()
void engine_cleanup_add_first (ENGINE_CLEANUP_CB * cb)
Definition at line 135 of file eng_lib.c.
engine_cleanup_add_last()
void engine_cleanup_add_last (ENGINE_CLEANUP_CB * cb)
Definition at line 145 of file eng_lib.c.
engine_cleanup_int()
void engine_cleanup_int (void)
Definition at line 162 of file eng_lib.c.
ENGINE_free()
int ENGINE_free (ENGINE * e)
Definition at line 102 of file eng_lib.c.
References engine_free_util().
Referenced by EVP_PKEY_asn1_find_str(), and release_engine().
engine_free_util()
int engine_free_util (ENGINE * e, int not_locked)
Definition at line 70 of file eng_lib.c.
References CRYPTO_atomic_add(), CRYPTO_DOWN_REF, CRYPTO_EX_INDEX_ENGINE, CRYPTO_free_ex_data(), engine_pkey_asn1_meths_free(), engine_pkey_meths_free(), engine_ref_debug, global_engine_lock, NULL, OPENSSL_free, and REF_ASSERT_ISNT.
Referenced by ENGINE_free(), and engine_unlocked_finish().
ENGINE_get_cmd_defns()
const ENGINE_CMD_DEFN* ENGINE_get_cmd_defns (const ENGINE * e)
Definition at line 285 of file eng_lib.c.
ENGINE_get_ctrl_function()
ENGINE_CTRL_FUNC_PTR ENGINE_get_ctrl_function (const ENGINE * e)
Definition at line 275 of file eng_lib.c.
ENGINE_get_destroy_function()
ENGINE_GEN_INT_FUNC_PTR ENGINE_get_destroy_function (const ENGINE * e)
Definition at line 260 of file eng_lib.c.
ENGINE_get_ex_data()
void* ENGINE_get_ex_data (const ENGINE * e, int idx)
Definition at line 184 of file eng_lib.c.
ENGINE_get_finish_function()
ENGINE_GEN_INT_FUNC_PTR ENGINE_get_finish_function (const ENGINE * e)
Definition at line 270 of file eng_lib.c.
ENGINE_get_flags()
int ENGINE_get_flags (const ENGINE * e)
Definition at line 280 of file eng_lib.c.
ENGINE_get_id()
const char* ENGINE_get_id (const ENGINE * e)
Definition at line 250 of file eng_lib.c.
ENGINE_get_init_function()
ENGINE_GEN_INT_FUNC_PTR ENGINE_get_init_function (const ENGINE * e)
Definition at line 265 of file eng_lib.c.
ENGINE_get_name()
const char* ENGINE_get_name (const ENGINE * e)
Definition at line 255 of file eng_lib.c.
ENGINE_get_static_state()
void* ENGINE_get_static_state (void)
Definition at line 297 of file eng_lib.c.
ENGINE_new()
ENGINE* ENGINE_new (void)
Definition at line 27 of file eng_lib.c.
engine_set_all_null()
void engine_set_all_null (ENGINE * e)
Definition at line 50 of file eng_lib.c.
References NULL.
ENGINE_set_cmd_defns()
int ENGINE_set_cmd_defns (ENGINE * e, const ENGINE_CMD_DEFN * defns)
Definition at line 244 of file eng_lib.c.
ENGINE_set_ctrl_function()
int ENGINE_set_ctrl_function (ENGINE * e, ENGINE_CTRL_FUNC_PTR ctrl_f)
Definition at line 232 of file eng_lib.c.
ENGINE_set_destroy_function()
int ENGINE_set_destroy_function (ENGINE * e, ENGINE_GEN_INT_FUNC_PTR destroy_f)
Definition at line 214 of file eng_lib.c.
ENGINE_set_ex_data()
int ENGINE_set_ex_data (ENGINE * e, int idx, void * arg)
Definition at line 179 of file eng_lib.c.
ENGINE_set_finish_function()
int ENGINE_set_finish_function (ENGINE * e, ENGINE_GEN_INT_FUNC_PTR finish_f)
Definition at line 226 of file eng_lib.c.
ENGINE_set_flags()
int ENGINE_set_flags (ENGINE * e, int flags)
Definition at line 238 of file eng_lib.c.
References flags.
ENGINE_set_id()
int ENGINE_set_id (ENGINE * e, const char * id)
Definition at line 194 of file eng_lib.c.
References ENGINE_F_ENGINE_SET_ID, ENGINEerr, ERR_R_PASSED_NULL_PARAMETER, and NULL.
ENGINE_set_init_function()
int ENGINE_set_init_function (ENGINE * e, ENGINE_GEN_INT_FUNC_PTR init_f)
Definition at line 220 of file eng_lib.c.
ENGINE_set_name()
int ENGINE_set_name (ENGINE * e, const char * name)
Definition at line 204 of file eng_lib.c.
References ENGINE_F_ENGINE_SET_NAME, ENGINEerr, ERR_R_PASSED_NULL_PARAMETER, and NULL.
Variable Documentation
engine_lock_init
CRYPTO_ONCE engine_lock_init = CRYPTO_ONCE_STATIC_INIT
Definition at line 16 of file eng_lib.c.
Referenced by ENGINE_by_id(), and ENGINE_pkey_asn1_find_str().
global_engine_lock
CRYPTO_RWLOCK* global_engine_lock
Definition at line 14 of file eng_lib.c.
Referenced by DEFINE_RUN_ONCE(), ENGINE_add(), ENGINE_by_id(), ENGINE_ctrl(), ENGINE_finish(), engine_free_util(), ENGINE_pkey_asn1_find_str(), ENGINE_remove(), engine_table_cleanup(), engine_table_unregister(), engine_unlocked_finish(), and ENGINE_up_ref().