crypto/engine/eng_err.c File Reference
eng_err.c File Reference
#include <stdio.h>
#include <openssl/err.h>
#include <openssl/engine.h>
Macros
#define ERR_FUNC(func) ERR_PACK(ERR_LIB_ENGINE,func,0)
#define ERR_REASON(reason) ERR_PACK(ERR_LIB_ENGINE,0,reason)
Functions
int ERR_load_ENGINE_strings (void)
Macro Definition Documentation
ERR_FUNC
#define ERR_FUNC (func) ERR_PACK(ERR_LIB_ENGINE,func,0)
Definition at line 18 of file eng_err.c.
ERR_REASON
#define ERR_REASON (reason) ERR_PACK(ERR_LIB_ENGINE,0,reason)
Definition at line 19 of file eng_err.c.
Function Documentation
ERR_load_ENGINE_strings()
int ERR_load_ENGINE_strings (void)
Definition at line 113 of file eng_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().