crypto/engine/eng_ctrl.c File Reference
eng_ctrl.c File Reference
#include "eng_int.h"
Functions
int ENGINE_ctrl (ENGINE *e, int cmd, long i, void *p, void(*f)(void))
int ENGINE_cmd_is_executable (ENGINE *e, int cmd)
int ENGINE_ctrl_cmd (ENGINE *e, const char *cmd_name, long i, void *p, void(*f)(void), int cmd_optional)
int ENGINE_ctrl_cmd_string (ENGINE *e, const char *cmd_name, const char *arg, int cmd_optional)
Function Documentation
ENGINE_cmd_is_executable()
int ENGINE_cmd_is_executable (ENGINE * e, int cmd)
Definition at line 185 of file eng_ctrl.c.
References ENGINE_CMD_FLAG_NO_INPUT, ENGINE_CMD_FLAG_NUMERIC, ENGINE_CMD_FLAG_STRING, ENGINE_ctrl(), ENGINE_CTRL_GET_CMD_FLAGS, ENGINE_F_ENGINE_CMD_IS_EXECUTABLE, ENGINE_R_INVALID_CMD_NUMBER, ENGINEerr, flags, and NULL.
ENGINE_ctrl()
int ENGINE_ctrl (ENGINE * e, int cmd, long i, void * p, void(*)(void) f)
Definition at line 133 of file eng_ctrl.c.
References CRYPTO_THREAD_unlock(), CRYPTO_THREAD_write_lock(), ENGINE_CTRL_GET_CMD_FLAGS, ENGINE_CTRL_GET_CMD_FROM_NAME, ENGINE_CTRL_GET_DESC_FROM_CMD, ENGINE_CTRL_GET_DESC_LEN_FROM_CMD, ENGINE_CTRL_GET_FIRST_CMD_TYPE, ENGINE_CTRL_GET_NAME_FROM_CMD, ENGINE_CTRL_GET_NAME_LEN_FROM_CMD, ENGINE_CTRL_GET_NEXT_CMD_TYPE, ENGINE_CTRL_HAS_CTRL_FUNCTION, ENGINE_F_ENGINE_CTRL, ENGINE_FLAGS_MANUAL_CMD_CTRL, ENGINE_R_NO_REFERENCE, ENGINEerr, ERR_R_PASSED_NULL_PARAMETER, global_engine_lock, and NULL.
Referenced by ENGINE_cmd_is_executable(), and ENGINE_ctrl_cmd().
ENGINE_ctrl_cmd()
int ENGINE_ctrl_cmd (ENGINE * e, const char * cmd_name, long i, void * p, void(*)(void) f, int cmd_optional)
Definition at line 201 of file eng_ctrl.c.
References ENGINE_ctrl(), ENGINE_CTRL_GET_CMD_FROM_NAME, ENGINE_F_ENGINE_CTRL_CMD, ENGINE_R_INVALID_CMD_NAME, ENGINEerr, ERR_clear_error(), ERR_R_PASSED_NULL_PARAMETER, and NULL.
ENGINE_ctrl_cmd_string()
int ENGINE_ctrl_cmd_string (ENGINE * e, const char * cmd_name, const char * arg, int cmd_optional)
Definition at line 237 of file eng_ctrl.c.