crypto/engine/eng_init.c File Reference
eng_init.c File Reference
#include "eng_int.h"
Functions
int engine_unlocked_init (ENGINE *e)
int engine_unlocked_finish (ENGINE *e, int unlock_for_handlers)
int ENGINE_init (ENGINE *e)
int ENGINE_finish (ENGINE *e)
Function Documentation
ENGINE_finish()
int ENGINE_finish (ENGINE * e)
Definition at line 94 of file eng_init.c.
References CRYPTO_THREAD_unlock(), CRYPTO_THREAD_write_lock(), ENGINE_F_ENGINE_FINISH, ENGINE_R_FINISH_FAILED, engine_unlocked_finish(), ENGINEerr, global_engine_lock, and NULL.
Referenced by DH_free(), DH_set_method(), DSA_free(), DSA_set_method(), EC_KEY_copy(), EC_KEY_free(), EC_KEY_set_method(), EVP_DigestInit_ex(), EVP_MD_CTX_reset(), EVP_PKEY_CTX_free(), RAND_set_rand_engine(), RAND_set_rand_method(), RSA_free(), RSA_set_method(), and SSL_CTX_set_client_cert_engine().
ENGINE_init()
int ENGINE_init (ENGINE * e)
Definition at line 76 of file eng_init.c.
Referenced by EC_KEY_copy(), EVP_DigestInit_ex(), EVP_PKEY_asn1_find_str(), load_key(), RAND_set_rand_engine(), and SSL_CTX_set_client_cert_engine().
engine_unlocked_finish()
int engine_unlocked_finish (ENGINE * e, int unlock_for_handlers)
Definition at line 43 of file eng_init.c.
References CRYPTO_THREAD_unlock(), CRYPTO_THREAD_write_lock(), ENGINE_F_ENGINE_UNLOCKED_FINISH, engine_free_util(), ENGINE_R_FINISH_FAILED, engine_ref_debug, ENGINEerr, global_engine_lock, and REF_ASSERT_ISNT.
Referenced by ENGINE_finish().
engine_unlocked_init()
int engine_unlocked_init (ENGINE * e)
Definition at line 16 of file eng_init.c.
References engine_ref_debug.