crypto/engine/eng_int.h File Reference
eng_int.h File Reference
#include "internal/cryptlib.h"
#include <internal/engine.h>
#include <internal/thread_once.h>
#include "internal/refcount.h"
Data Structures
struct ENGINE_CLEANUP_ITEM
struct ENGINE
Macros
#define engine_ref_debug(e, isfunct, diff)
Typedefs
typedef void(ENGINE_CLEANUP_CB) (void)
typedef void(engine_table_doall_cb) (int nid, STACK_OF(ENGINE) *sk, ENGINE *def, void *arg)
Functions
void engine_cleanup_add_first (ENGINE_CLEANUP_CB *cb)
void engine_cleanup_add_last (ENGINE_CLEANUP_CB *cb)
int engine_table_register (ENGINE_TABLE **table, ENGINE_CLEANUP_CB *cleanup, ENGINE *e, const int *nids, int num_nids, int setdefault)
void engine_table_unregister (ENGINE_TABLE **table, ENGINE *e)
void engine_table_cleanup (ENGINE_TABLE **table)
ENGINE * engine_table_select (ENGINE_TABLE **table, int nid)
void engine_table_doall (ENGINE_TABLE *table, engine_table_doall_cb *cb, void *arg)
int engine_unlocked_init (ENGINE *e)
int engine_unlocked_finish (ENGINE *e, int unlock_for_handlers)
int engine_free_util (ENGINE *e, int not_locked)
void engine_set_all_null (ENGINE *e)
void engine_pkey_meths_free (ENGINE *e)
void engine_pkey_asn1_meths_free (ENGINE *e)
DEFINE_LHASH_OF (ENGINE_PILE)
Variables
CRYPTO_RWLOCK * global_engine_lock
CRYPTO_ONCE engine_lock_init
Macro Definition Documentation
engine_ref_debug
#define engine_ref_debug (e, isfunct, diff)
Definition at line 49 of file eng_int.h.
Referenced by engine_free_util(), engine_unlocked_finish(), and engine_unlocked_init().
Typedef Documentation
ENGINE_CLEANUP_CB
typedef void(ENGINE_CLEANUP_CB) (void)
Definition at line 59 of file eng_int.h.
engine_table_doall_cb
typedef void(engine_table_doall_cb) (int nid, STACK_OF(ENGINE) *sk, ENGINE *def, void *arg)
Definition at line 95 of file eng_int.h.
Function Documentation
DEFINE_LHASH_OF()
DEFINE_LHASH_OF (ENGINE_PILE)
engine_cleanup_add_first()
void engine_cleanup_add_first (ENGINE_CLEANUP_CB * cb)
Definition at line 135 of file eng_lib.c.
engine_cleanup_add_last()
void engine_cleanup_add_last (ENGINE_CLEANUP_CB * cb)
Definition at line 145 of file eng_lib.c.
engine_free_util()
int engine_free_util (ENGINE * e, int not_locked)
Definition at line 70 of file eng_lib.c.
References CRYPTO_atomic_add(), CRYPTO_DOWN_REF, CRYPTO_EX_INDEX_ENGINE, CRYPTO_free_ex_data(), engine_pkey_asn1_meths_free(), engine_pkey_meths_free(), engine_ref_debug, global_engine_lock, NULL, OPENSSL_free, and REF_ASSERT_ISNT.
Referenced by ENGINE_free(), and engine_unlocked_finish().
engine_pkey_asn1_meths_free()
void engine_pkey_asn1_meths_free (ENGINE * e)
Definition at line 112 of file tb_asnmth.c.
References EVP_PKEY_asn1_free(), and NULL.
Referenced by engine_free_util().
engine_pkey_meths_free()
void engine_pkey_meths_free (ENGINE * e)
Definition at line 100 of file tb_pkmeth.c.
References EVP_PKEY_meth_free(), and NULL.
Referenced by engine_free_util().
engine_set_all_null()
void engine_set_all_null (ENGINE * e)
Definition at line 50 of file eng_lib.c.
References NULL.
engine_table_cleanup()
void engine_table_cleanup (ENGINE_TABLE ** table)
Definition at line 175 of file eng_table.c.
References CRYPTO_THREAD_write_lock(), and global_engine_lock.
engine_table_doall()
void engine_table_doall (ENGINE_TABLE * table, engine_table_doall_cb * cb, void * arg)
Definition at line 295 of file eng_table.c.
Referenced by ENGINE_pkey_asn1_find_str().
engine_table_register()
int engine_table_register (ENGINE_TABLE ** table, ENGINE_CLEANUP_CB * cleanup, ENGINE * e, const int * nids, int num_nids, int setdefault)
Definition at line 82 of file eng_table.c.
Referenced by ENGINE_register_ciphers(), ENGINE_register_DH(), ENGINE_register_digests(), ENGINE_register_DSA(), ENGINE_register_EC(), ENGINE_register_pkey_asn1_meths(), ENGINE_register_pkey_meths(), ENGINE_register_RAND(), ENGINE_register_RSA(), ENGINE_set_default_ciphers(), ENGINE_set_default_DH(), ENGINE_set_default_digests(), ENGINE_set_default_DSA(), ENGINE_set_default_EC(), ENGINE_set_default_pkey_asn1_meths(), ENGINE_set_default_pkey_meths(), ENGINE_set_default_RAND(), and ENGINE_set_default_RSA().
engine_table_select()
ENGINE* engine_table_select (ENGINE_TABLE ** table, int nid)
Definition at line 188 of file eng_table.c.
Referenced by ENGINE_get_cipher_engine(), ENGINE_get_default_DH(), ENGINE_get_default_DSA(), ENGINE_get_default_EC(), ENGINE_get_default_RAND(), ENGINE_get_default_RSA(), ENGINE_get_digest_engine(), ENGINE_get_pkey_asn1_meth_engine(), and ENGINE_get_pkey_meth_engine().
engine_table_unregister()
void engine_table_unregister (ENGINE_TABLE ** table, ENGINE * e)
Definition at line 157 of file eng_table.c.
References CRYPTO_THREAD_write_lock(), and global_engine_lock.
Referenced by ENGINE_unregister_ciphers(), ENGINE_unregister_DH(), ENGINE_unregister_digests(), ENGINE_unregister_DSA(), ENGINE_unregister_EC(), ENGINE_unregister_pkey_asn1_meths(), ENGINE_unregister_pkey_meths(), ENGINE_unregister_RAND(), and ENGINE_unregister_RSA().
engine_unlocked_finish()
int engine_unlocked_finish (ENGINE * e, int unlock_for_handlers)
Definition at line 43 of file eng_init.c.
References CRYPTO_THREAD_unlock(), CRYPTO_THREAD_write_lock(), ENGINE_F_ENGINE_UNLOCKED_FINISH, engine_free_util(), ENGINE_R_FINISH_FAILED, engine_ref_debug, ENGINEerr, global_engine_lock, and REF_ASSERT_ISNT.
Referenced by ENGINE_finish().
engine_unlocked_init()
int engine_unlocked_init (ENGINE * e)
Definition at line 16 of file eng_init.c.
References engine_ref_debug.
Variable Documentation
engine_lock_init
CRYPTO_ONCE engine_lock_init
Definition at line 16 of file eng_lib.c.
Referenced by ENGINE_by_id(), and ENGINE_pkey_asn1_find_str().
global_engine_lock
CRYPTO_RWLOCK* global_engine_lock
Definition at line 14 of file eng_lib.c.
Referenced by DEFINE_RUN_ONCE(), ENGINE_add(), ENGINE_by_id(), ENGINE_ctrl(), ENGINE_finish(), engine_free_util(), ENGINE_pkey_asn1_find_str(), ENGINE_remove(), engine_table_cleanup(), engine_table_unregister(), engine_unlocked_finish(), and ENGINE_up_ref().