crypto/err/err.c File Reference
err.c File Reference
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <internal/cryptlib_int.h>
#include <internal/err.h>
#include <internal/err_int.h>
#include <openssl/lhash.h>
#include <openssl/crypto.h>
#include <openssl/buffer.h>
#include <openssl/bio.h>
#include <openssl/opensslconf.h>
#include <internal/thread_once.h>
Macros
#define NUM_SYS_STR_REASONS 127
#define LEN_SYS_STR_REASON 32
#define err_clear_data(p, i)
#define err_clear(p, i)
#define NUM_COLONS 4
Functions
DEFINE_RUN_ONCE_STATIC (do_err_strings_init)
void err_cleanup (void)
int ERR_load_ERR_strings (void)
int ERR_load_strings (int lib, ERR_STRING_DATA *str)
int ERR_unload_strings (int lib, ERR_STRING_DATA *str)
void err_free_strings_int (void)
void ERR_put_error (int lib, int func, int reason, const char *file, int line)
void ERR_clear_error (void)
unsigned long ERR_get_error (void)
unsigned long ERR_get_error_line (const char **file, int *line)
unsigned long ERR_get_error_line_data (const char **file, int *line, const char **data, int *flags)
unsigned long ERR_peek_error (void)
unsigned long ERR_peek_error_line (const char **file, int *line)
unsigned long ERR_peek_error_line_data (const char **file, int *line, const char **data, int *flags)
unsigned long ERR_peek_last_error (void)
unsigned long ERR_peek_last_error_line (const char **file, int *line)
unsigned long ERR_peek_last_error_line_data (const char **file, int *line, const char **data, int *flags)
void ERR_error_string_n (unsigned long e, char *buf, size_t len)
char * ERR_error_string (unsigned long e, char *ret)
const char * ERR_lib_error_string (unsigned long e)
const char * ERR_func_error_string (unsigned long e)
const char * ERR_reason_error_string (unsigned long e)
void err_delete_thread_state (void)
void ERR_remove_thread_state (void *dummy)
void ERR_remove_state (unsigned long pid)
DEFINE_RUN_ONCE_STATIC (err_do_init)
ERR_STATE * ERR_get_state (void)
int ERR_get_next_error_library (void)
void ERR_set_error_data (char *data, int flags)
void ERR_add_error_data (int num,...)
void ERR_add_error_vdata (int num, va_list args)
int ERR_set_mark (void)
int ERR_pop_to_mark (void)
Macro Definition Documentation
err_clear
#define err_clear (p, i)
Value:
do { \
        (p)->err_flags[i]=0; \
        (p)->err_buffer[i]=0; \
        err_clear_data(p,i); \
        (p)->err_file[i]=NULL; \
        (p)->err_line[i]= -1; \
        } while(0)
Definition at line 231 of file err.c.
Referenced by ERR_clear_error(), and ERR_pop_to_mark().
err_clear_data
#define err_clear_data (p, i)
Value:
do { \
        if ((p)->err_data_flags[i] & ERR_TXT_MALLOCED) \
                {  \
                OPENSSL_free((p)->err_data[i]); \
                (p)->err_data[i]=NULL; \
                } \
        (p)->err_data_flags[i]=0; \
        } while(0)
Definition at line 221 of file err.c.
Referenced by ERR_put_error(), and ERR_set_error_data().
LEN_SYS_STR_REASON
#define LEN_SYS_STR_REASON 32
Definition at line 171 of file err.c.
NUM_COLONS
#define NUM_COLONS 4
NUM_SYS_STR_REASONS
#define NUM_SYS_STR_REASONS 127
Definition at line 170 of file err.c.
Function Documentation
DEFINE_RUN_ONCE_STATIC() [1/2]
DEFINE_RUN_ONCE_STATIC (do_err_strings_init)
Definition at line 253 of file err.c.
References NULL, and OPENSSL_init_crypto().
DEFINE_RUN_ONCE_STATIC() [2/2]
DEFINE_RUN_ONCE_STATIC (err_do_init)
Definition at line 638 of file err.c.
References CRYPTO_THREAD_init_local().
ERR_add_error_data()
void ERR_add_error_data (int num, ...)
Definition at line 700 of file err.c.
References ERR_add_error_vdata().
Referenced by EVP_PKCS82PKEY(), NCONF_get_string(), ssl_build_cert_chain(), UI_set_result(), X509_ATTRIBUTE_create_by_txt(), and X509_NAME_ENTRY_create_by_txt().
ERR_add_error_vdata()
void ERR_add_error_vdata (int num, va_list args)
Definition at line 708 of file err.c.
References ERR_set_error_data(), ERR_TXT_MALLOCED, ERR_TXT_STRING, NULL, OPENSSL_free, OPENSSL_malloc, OPENSSL_realloc, and OPENSSL_strlcat().
Referenced by ERR_add_error_data(), and err_load_crypto_strings_int().
err_cleanup()
void err_cleanup (void)
Definition at line 260 of file err.c.
References CRYPTO_THREAD_lock_free().
ERR_clear_error()
void ERR_clear_error (void)
Definition at line 371 of file err.c.
References ERR_STATE::bottom, err_clear, ERR_get_state(), ERR_NUM_ERRORS, and ERR_STATE::top.
Referenced by CMS_decrypt_set1_key(), CONF_get_number(), ENGINE_ctrl_cmd(), and ssl_build_cert_chain().
err_delete_thread_state()
void err_delete_thread_state (void)
Definition at line 616 of file err.c.
ERR_error_string()
char* ERR_error_string (unsigned long e, char * ret)
Definition at line 554 of file err.c.
ERR_error_string_n()
void ERR_error_string_n (unsigned long e, char * buf, size_t len)
Definition at line 498 of file err.c.
err_free_strings_int()
void err_free_strings_int (void)
Definition at line 323 of file err.c.
References RUN_ONCE.
ERR_func_error_string()
const char* ERR_func_error_string (unsigned long e)
Definition at line 580 of file err.c.
References RUN_ONCE.
Referenced by ERR_load_ASN1_strings(), ERR_load_ASYNC_strings(), ERR_load_BIO_strings(), ERR_load_BN_strings(), ERR_load_BUF_strings(), ERR_load_CMS_strings(), ERR_load_COMP_strings(), ERR_load_CONF_strings(), ERR_load_CRYPTO_strings(), ERR_load_CT_strings(), ERR_load_DH_strings(), ERR_load_DSA_strings(), ERR_load_DSO_strings(), ERR_load_EC_strings(), ERR_load_ENGINE_strings(), ERR_load_EVP_strings(), ERR_load_KDF_strings(), ERR_load_OBJ_strings(), ERR_load_OCSP_strings(), ERR_load_PEM_strings(), ERR_load_PKCS12_strings(), ERR_load_PKCS7_strings(), ERR_load_RAND_strings(), ERR_load_RSA_strings(), ERR_load_SSL_strings(), ERR_load_TS_strings(), ERR_load_UI_strings(), ERR_load_X509_strings(), and ERR_load_X509V3_strings().
ERR_get_error()
unsigned long ERR_get_error (void)
Definition at line 384 of file err.c.
ERR_get_error_line()
unsigned long ERR_get_error_line (const char ** file, int * line)
Definition at line 389 of file err.c.
ERR_get_error_line_data()
unsigned long ERR_get_error_line_data (const char ** file, int * line, const char ** data, int * flags)
Definition at line 394 of file err.c.
ERR_get_next_error_library()
int ERR_get_next_error_library (void)
Definition at line 670 of file err.c.
ERR_get_state()
ERR_STATE* ERR_get_state (void)
Definition at line 643 of file err.c.
Referenced by ERR_clear_error(), ERR_pop_to_mark(), ERR_put_error(), ERR_set_error_data(), and ERR_set_mark().
ERR_lib_error_string()
const char* ERR_lib_error_string (unsigned long e)
Definition at line 565 of file err.c.
References RUN_ONCE.
ERR_load_ERR_strings()
int ERR_load_ERR_strings (void)
Definition at line 266 of file err.c.
References RUN_ONCE.
Referenced by err_load_crypto_strings_int(), and ERR_load_strings().
ERR_load_strings()
int ERR_load_strings (int lib, ERR_STRING_DATA * str)
Definition at line 297 of file err.c.
References ERR_load_ERR_strings().
Referenced by ERR_load_ASN1_strings(), ERR_load_ASYNC_strings(), ERR_load_BIO_strings(), ERR_load_BN_strings(), ERR_load_BUF_strings(), ERR_load_CMS_strings(), ERR_load_COMP_strings(), ERR_load_CONF_strings(), ERR_load_CRYPTO_strings(), ERR_load_CT_strings(), ERR_load_DH_strings(), ERR_load_DSA_strings(), ERR_load_DSO_strings(), ERR_load_EC_strings(), ERR_load_ENGINE_strings(), ERR_load_EVP_strings(), ERR_load_KDF_strings(), ERR_load_OBJ_strings(), ERR_load_OCSP_strings(), ERR_load_PEM_strings(), ERR_load_PKCS12_strings(), ERR_load_PKCS7_strings(), ERR_load_RAND_strings(), ERR_load_RSA_strings(), ERR_load_SSL_strings(), ERR_load_TS_strings(), ERR_load_UI_strings(), ERR_load_X509_strings(), and ERR_load_X509V3_strings().
ERR_peek_error()
unsigned long ERR_peek_error (void)
Definition at line 400 of file err.c.
Referenced by SSL_get_error().
ERR_peek_error_line()
unsigned long ERR_peek_error_line (const char ** file, int * line)
Definition at line 405 of file err.c.
ERR_peek_error_line_data()
unsigned long ERR_peek_error_line_data (const char ** file, int * line, const char ** data, int * flags)
Definition at line 410 of file err.c.
ERR_peek_last_error()
unsigned long ERR_peek_last_error (void)
Definition at line 416 of file err.c.
Referenced by ssl_build_cert_chain().
ERR_peek_last_error_line()
unsigned long ERR_peek_last_error_line (const char ** file, int * line)
Definition at line 421 of file err.c.
ERR_peek_last_error_line_data()
unsigned long ERR_peek_last_error_line_data (const char ** file, int * line, const char ** data, int * flags)
Definition at line 426 of file err.c.
ERR_pop_to_mark()
int ERR_pop_to_mark (void)
Definition at line 752 of file err.c.
References ERR_STATE::bottom, err_clear, ERR_FLAG_MARK, ERR_STATE::err_flags, ERR_get_state(), ERR_NUM_ERRORS, and ERR_STATE::top.
ERR_put_error()
void ERR_put_error (int lib, int func, int reason, const char * file, int line)
Definition at line 336 of file err.c.
References ERR_STATE::bottom, ERR_STATE::err_buffer, err_clear_data, ERR_STATE::err_file, ERR_STATE::err_flags, ERR_get_state(), ERR_STATE::err_line, ERR_NUM_ERRORS, ERR_PACK, file, NULL, and ERR_STATE::top.
Referenced by err_load_crypto_strings_int().
ERR_reason_error_string()
const char* ERR_reason_error_string (unsigned long e)
Definition at line 596 of file err.c.
References NULL, and RUN_ONCE.
ERR_remove_state()
void ERR_remove_state (unsigned long pid)
Definition at line 633 of file err.c.
ERR_remove_thread_state()
void ERR_remove_thread_state (void * dummy)
Definition at line 627 of file err.c.
ERR_set_error_data()
void ERR_set_error_data (char * data, int flags)
Definition at line 684 of file err.c.
References data, err_clear_data, ERR_STATE::err_data, ERR_STATE::err_data_flags, ERR_get_state(), ERR_NUM_ERRORS, flags, and ERR_STATE::top.
Referenced by ERR_add_error_vdata().
ERR_set_mark()
int ERR_set_mark (void)
Definition at line 740 of file err.c.
References ERR_STATE::bottom, ERR_FLAG_MARK, ERR_STATE::err_flags, ERR_get_state(), and ERR_STATE::top.
ERR_unload_strings()
int ERR_unload_strings (int lib, ERR_STRING_DATA * str)
Definition at line 305 of file err.c.
References RUN_ONCE.