crypto/err/err_prn.c File Reference
err_prn.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/lhash.h>
#include <openssl/crypto.h>
#include <openssl/buffer.h>
#include <openssl/err.h>
Functions
void ERR_print_errors_cb (int(*cb)(const char *str, size_t len, void *u), void *u)
void ERR_print_errors (BIO *bp)
void ERR_print_errors_fp (FILE *fp)
Function Documentation
ERR_print_errors()
void ERR_print_errors (BIO * bp)
Definition at line 51 of file err_prn.c.
References ERR_print_errors_cb().
Referenced by app_malloc(), set_cert_stuff(), and X509_REQ_print_ex().
ERR_print_errors_cb()
void ERR_print_errors_cb (int(*)(const char *str, size_t len, void *u) cb, void * u)
Definition at line 17 of file err_prn.c.
Referenced by ERR_print_errors(), and ERR_print_errors_fp().
ERR_print_errors_fp()
void ERR_print_errors_fp (FILE * fp)
Definition at line 57 of file err_prn.c.
References BIO_new_fp(), BIO_NOCLOSE, ERR_print_errors_cb(), and NULL.