crypto/evp/evp_enc.c File Reference
evp_enc.c File Reference
#include <stdio.h>
#include <assert.h>
#include "internal/cryptlib.h"
#include <openssl/evp.h>
#include <openssl/err.h>
#include <openssl/rand.h>
#include <openssl/engine.h>
#include "internal/evp_int.h"
#include "evp_locl.h"
Macros
#define PTRDIFF_T size_t
Functions
int EVP_CIPHER_CTX_reset (EVP_CIPHER_CTX *c)
EVP_CIPHER_CTX * EVP_CIPHER_CTX_new (void)
void EVP_CIPHER_CTX_free (EVP_CIPHER_CTX *ctx)
int EVP_CipherInit (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, const unsigned char *key, const unsigned char *iv, int enc)
int EVP_CipherInit_ex (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, ENGINE *impl, const unsigned char *key, const unsigned char *iv, int enc)
int EVP_CipherUpdate (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl)
int EVP_CipherFinal_ex (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl)
int EVP_CipherFinal (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl)
int EVP_EncryptInit (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, const unsigned char *key, const unsigned char *iv)
int EVP_EncryptInit_ex (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, ENGINE *impl, const unsigned char *key, const unsigned char *iv)
int EVP_DecryptInit (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, const unsigned char *key, const unsigned char *iv)
int EVP_DecryptInit_ex (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, ENGINE *impl, const unsigned char *key, const unsigned char *iv)
int is_partially_overlapping (const void *ptr1, const void *ptr2, int len)
int EVP_EncryptUpdate (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl)
int EVP_EncryptFinal (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl)
int EVP_EncryptFinal_ex (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl)
int EVP_DecryptUpdate (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl)
int EVP_DecryptFinal (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl)
int EVP_DecryptFinal_ex (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl)
int EVP_CIPHER_CTX_set_key_length (EVP_CIPHER_CTX *c, int keylen)
int EVP_CIPHER_CTX_set_padding (EVP_CIPHER_CTX *ctx, int pad)
int EVP_CIPHER_CTX_ctrl (EVP_CIPHER_CTX *ctx, int type, int arg, void *ptr)
int EVP_CIPHER_CTX_rand_key (EVP_CIPHER_CTX *ctx, unsigned char *key)
int EVP_CIPHER_CTX_copy (EVP_CIPHER_CTX *out, const EVP_CIPHER_CTX *in)
Macro Definition Documentation
PTRDIFF_T
#define PTRDIFF_T size_t
Definition at line 278 of file evp_enc.c.
Referenced by is_partially_overlapping().
Function Documentation
EVP_CIPHER_CTX_copy()
int EVP_CIPHER_CTX_copy (EVP_CIPHER_CTX * out, const EVP_CIPHER_CTX * in)
Definition at line 607 of file evp_enc.c.
EVP_CIPHER_CTX_ctrl()
int EVP_CIPHER_CTX_ctrl (EVP_CIPHER_CTX * ctx, int type, int arg, void * ptr)
Definition at line 576 of file evp_enc.c.
Referenced by EVP_CIPHER_CTX_rand_key().
EVP_CIPHER_CTX_free()
void EVP_CIPHER_CTX_free (EVP_CIPHER_CTX * ctx)
Definition at line 44 of file evp_enc.c.
References EVP_CIPHER_CTX_reset(), and OPENSSL_free.
Referenced by CMAC_CTX_cleanup(), dtls1_hm_fragment_free(), and ssl_clear_cipher_ctx().
EVP_CIPHER_CTX_new()
EVP_CIPHER_CTX* EVP_CIPHER_CTX_new (void)
Definition at line 39 of file evp_enc.c.
References OPENSSL_zalloc.
Referenced by CMAC_CTX_new(), and cms_RecipientInfo_pwri_crypt().
EVP_CIPHER_CTX_rand_key()
int EVP_CIPHER_CTX_rand_key (EVP_CIPHER_CTX * ctx, unsigned char * key)
Definition at line 598 of file evp_enc.c.
References EVP_CIPH_RAND_KEY, EVP_CIPHER_CTX_ctrl(), EVP_CTRL_RAND_KEY, and RAND_bytes().
EVP_CIPHER_CTX_reset()
int EVP_CIPHER_CTX_reset (EVP_CIPHER_CTX * c)
Definition at line 20 of file evp_enc.c.
Referenced by EVP_CIPHER_CTX_free().
EVP_CIPHER_CTX_set_key_length()
int EVP_CIPHER_CTX_set_key_length (EVP_CIPHER_CTX * c, int keylen)
Definition at line 553 of file evp_enc.c.
EVP_CIPHER_CTX_set_padding()
int EVP_CIPHER_CTX_set_padding (EVP_CIPHER_CTX * ctx, int pad)
Definition at line 567 of file evp_enc.c.
References EVP_CIPH_NO_PADDING.
Referenced by cms_RecipientInfo_pwri_crypt().
EVP_CipherFinal()
int EVP_CipherFinal (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl)
Definition at line 224 of file evp_enc.c.
EVP_CipherFinal_ex()
int EVP_CipherFinal_ex (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl)
Definition at line 216 of file evp_enc.c.
EVP_CipherInit()
int EVP_CipherInit (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * cipher, const unsigned char * key, const unsigned char * iv, int enc)
Definition at line 50 of file evp_enc.c.
EVP_CipherInit_ex()
int EVP_CipherInit_ex (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * cipher, ENGINE * impl, const unsigned char * key, const unsigned char * iv, int enc)
Definition at line 57 of file evp_enc.c.
Referenced by cms_RecipientInfo_pwri_crypt().
EVP_CipherUpdate()
int EVP_CipherUpdate (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl, const unsigned char * in, int inl)
Definition at line 207 of file evp_enc.c.
EVP_DecryptFinal()
int EVP_DecryptFinal (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl)
Definition at line 490 of file evp_enc.c.
EVP_DecryptFinal_ex()
int EVP_DecryptFinal_ex (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl)
Definition at line 497 of file evp_enc.c.
EVP_DecryptInit()
int EVP_DecryptInit (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * cipher, const unsigned char * key, const unsigned char * iv)
Definition at line 245 of file evp_enc.c.
EVP_DecryptInit_ex()
int EVP_DecryptInit_ex (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * cipher, ENGINE * impl, const unsigned char * key, const unsigned char * iv)
Definition at line 251 of file evp_enc.c.
EVP_DecryptUpdate()
int EVP_DecryptUpdate (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl, const unsigned char * in, int inl)
Definition at line 421 of file evp_enc.c.
EVP_EncryptFinal()
int EVP_EncryptFinal (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl)
Definition at line 372 of file evp_enc.c.
EVP_EncryptFinal_ex()
int EVP_EncryptFinal_ex (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl)
Definition at line 379 of file evp_enc.c.
EVP_EncryptInit()
int EVP_EncryptInit (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * cipher, const unsigned char * key, const unsigned char * iv)
Definition at line 232 of file evp_enc.c.
EVP_EncryptInit_ex()
int EVP_EncryptInit_ex (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * cipher, ENGINE * impl, const unsigned char * key, const unsigned char * iv)
Definition at line 238 of file evp_enc.c.
Referenced by CMAC_resume().
EVP_EncryptUpdate()
int EVP_EncryptUpdate (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl, const unsigned char * in, int inl)
Definition at line 295 of file evp_enc.c.
is_partially_overlapping()
int is_partially_overlapping (const void * ptr1, const void * ptr2, int len)
Definition at line 281 of file evp_enc.c.
References PTRDIFF_T.