include/openssl/evp.h File Reference
evp.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/ossl_typ.h>
#include <openssl/symhacks.h>
#include <openssl/bio.h>
#include <openssl/objects.h>
Data Structures
struct EVP_CTRL_TLS1_1_MULTIBLOCK_PARAM
struct EVP_CIPHER_INFO
Macros
#define EVP_MAX_MD_SIZE 64/* longest known is SHA512 */
#define EVP_MAX_KEY_LENGTH 64
#define EVP_MAX_IV_LENGTH 16
#define EVP_MAX_BLOCK_LENGTH 32
#define PKCS5_SALT_LEN 8
#define PKCS5_DEFAULT_ITER 2048
#define EVP_PK_RSA 0x0001
#define EVP_PK_DSA 0x0002
#define EVP_PK_DH 0x0004
#define EVP_PK_EC 0x0008
#define EVP_PKT_SIGN 0x0010
#define EVP_PKT_ENC 0x0020
#define EVP_PKT_EXCH 0x0040
#define EVP_PKS_RSA 0x0100
#define EVP_PKS_DSA 0x0200
#define EVP_PKS_EC 0x0400
#define EVP_PKEY_NONE NID_undef
#define EVP_PKEY_RSA NID_rsaEncryption
#define EVP_PKEY_RSA2 NID_rsa
#define EVP_PKEY_RSA_PSS NID_rsassaPss
#define EVP_PKEY_DSA NID_dsa
#define EVP_PKEY_DSA1 NID_dsa_2
#define EVP_PKEY_DSA2 NID_dsaWithSHA
#define EVP_PKEY_DSA3 NID_dsaWithSHA1
#define EVP_PKEY_DSA4 NID_dsaWithSHA1_2
#define EVP_PKEY_DH NID_dhKeyAgreement
#define EVP_PKEY_DHX NID_dhpublicnumber
#define EVP_PKEY_EC NID_X9_62_id_ecPublicKey
#define EVP_PKEY_HMAC NID_hmac
#define EVP_PKEY_CMAC NID_cmac
#define EVP_PKEY_TLS1_PRF NID_tls1_prf
#define EVP_PKEY_HKDF NID_hkdf
#define EVP_PKEY_POLY1305 NID_poly1305
#define EVP_PKEY_SIPHASH NID_siphash
#define EVP_PKEY_MO_SIGN 0x0001
#define EVP_PKEY_MO_VERIFY 0x0002
#define EVP_PKEY_MO_ENCRYPT 0x0004
#define EVP_PKEY_MO_DECRYPT 0x0008
#define EVP_MD_FLAG_ONESHOT 0x0001
#define EVP_MD_FLAG_DIGALGID_MASK 0x0018
#define EVP_MD_FLAG_DIGALGID_NULL 0x0000
#define EVP_MD_FLAG_DIGALGID_ABSENT 0x0008
#define EVP_MD_FLAG_DIGALGID_CUSTOM 0x0018
#define EVP_MD_FLAG_FIPS 0x0400
#define EVP_MD_CTRL_DIGALGID 0x1
#define EVP_MD_CTRL_MICALG 0x2
#define EVP_MD_CTRL_ALG_CTRL 0x1000
#define EVP_MD_CTX_FLAG_ONESHOT
#define EVP_MD_CTX_FLAG_CLEANED
#define EVP_MD_CTX_FLAG_REUSE
#define EVP_MD_CTX_FLAG_NON_FIPS_ALLOW
#define EVP_MD_CTX_FLAG_PAD_MASK 0xF0/* RSA mode to use */
#define EVP_MD_CTX_FLAG_PAD_PKCS1 0x00/* PKCS#1 v1.5 mode */
#define EVP_MD_CTX_FLAG_PAD_X931 0x10/* X9.31 mode */
#define EVP_MD_CTX_FLAG_PAD_PSS 0x20/* PSS mode */
#define EVP_MD_CTX_FLAG_NO_INIT 0x0100/* Don't initialize md_data */
#define EVP_MD_CTX_FLAG_FINALISE 0x0200
#define EVP_CIPH_STREAM_CIPHER 0x0
#define EVP_CIPH_ECB_MODE 0x1
#define EVP_CIPH_CBC_MODE 0x2
#define EVP_CIPH_CFB_MODE 0x3
#define EVP_CIPH_OFB_MODE 0x4
#define EVP_CIPH_CTR_MODE 0x5
#define EVP_CIPH_GCM_MODE 0x6
#define EVP_CIPH_CCM_MODE 0x7
#define EVP_CIPH_XTS_MODE 0x10001
#define EVP_CIPH_WRAP_MODE 0x10002
#define EVP_CIPH_OCB_MODE 0x10003
#define EVP_CIPH_MODE 0xF0007
#define EVP_CIPH_VARIABLE_LENGTH 0x8
#define EVP_CIPH_CUSTOM_IV 0x10
#define EVP_CIPH_ALWAYS_CALL_INIT 0x20
#define EVP_CIPH_CTRL_INIT 0x40
#define EVP_CIPH_CUSTOM_KEY_LENGTH 0x80
#define EVP_CIPH_NO_PADDING 0x100
#define EVP_CIPH_RAND_KEY 0x200
#define EVP_CIPH_CUSTOM_COPY 0x400
#define EVP_CIPH_FLAG_DEFAULT_ASN1 0x1000
#define EVP_CIPH_FLAG_LENGTH_BITS 0x2000
#define EVP_CIPH_FLAG_FIPS 0x4000
#define EVP_CIPH_FLAG_NON_FIPS_ALLOW 0x8000
#define EVP_CIPH_FLAG_CUSTOM_CIPHER 0x100000
#define EVP_CIPH_FLAG_AEAD_CIPHER 0x200000
#define EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK 0x400000
#define EVP_CIPH_FLAG_PIPELINE 0X800000
#define EVP_CIPHER_CTX_FLAG_WRAP_ALLOW 0x1
#define EVP_CTRL_INIT 0x0
#define EVP_CTRL_SET_KEY_LENGTH 0x1
#define EVP_CTRL_GET_RC2_KEY_BITS 0x2
#define EVP_CTRL_SET_RC2_KEY_BITS 0x3
#define EVP_CTRL_GET_RC5_ROUNDS 0x4
#define EVP_CTRL_SET_RC5_ROUNDS 0x5
#define EVP_CTRL_RAND_KEY 0x6
#define EVP_CTRL_PBE_PRF_NID 0x7
#define EVP_CTRL_COPY 0x8
#define EVP_CTRL_AEAD_SET_IVLEN 0x9
#define EVP_CTRL_AEAD_GET_TAG 0x10
#define EVP_CTRL_AEAD_SET_TAG 0x11
#define EVP_CTRL_AEAD_SET_IV_FIXED 0x12
#define EVP_CTRL_GCM_SET_IVLEN EVP_CTRL_AEAD_SET_IVLEN
#define EVP_CTRL_GCM_GET_TAG EVP_CTRL_AEAD_GET_TAG
#define EVP_CTRL_GCM_SET_TAG EVP_CTRL_AEAD_SET_TAG
#define EVP_CTRL_GCM_SET_IV_FIXED EVP_CTRL_AEAD_SET_IV_FIXED
#define EVP_CTRL_GCM_IV_GEN 0x13
#define EVP_CTRL_CCM_SET_IVLEN EVP_CTRL_AEAD_SET_IVLEN
#define EVP_CTRL_CCM_GET_TAG EVP_CTRL_AEAD_GET_TAG
#define EVP_CTRL_CCM_SET_TAG EVP_CTRL_AEAD_SET_TAG
#define EVP_CTRL_CCM_SET_IV_FIXED EVP_CTRL_AEAD_SET_IV_FIXED
#define EVP_CTRL_CCM_SET_L 0x14
#define EVP_CTRL_CCM_SET_MSGLEN 0x15
#define EVP_CTRL_AEAD_TLS1_AAD 0x16
#define EVP_CTRL_AEAD_SET_MAC_KEY 0x17
#define EVP_CTRL_GCM_SET_IV_INV 0x18
#define EVP_CTRL_TLS1_1_MULTIBLOCK_AAD 0x19
#define EVP_CTRL_TLS1_1_MULTIBLOCK_ENCRYPT 0x1a
#define EVP_CTRL_TLS1_1_MULTIBLOCK_DECRYPT 0x1b
#define EVP_CTRL_TLS1_1_MULTIBLOCK_MAX_BUFSIZE 0x1c
#define EVP_CTRL_SSL3_MASTER_SECRET 0x1d
#define EVP_CTRL_SET_SBOX 0x1e
#define EVP_CTRL_SBOX_USED 0x1f
#define EVP_CTRL_KEY_MESH 0x20
#define EVP_CTRL_BLOCK_PADDING_MODE 0x21
#define EVP_CTRL_SET_PIPELINE_OUTPUT_BUFS 0x22
#define EVP_CTRL_SET_PIPELINE_INPUT_BUFS 0x23
#define EVP_CTRL_SET_PIPELINE_INPUT_LENS 0x24
#define EVP_PADDING_PKCS7 1
#define EVP_PADDING_ISO7816_4 2
#define EVP_PADDING_ANSI923 3
#define EVP_PADDING_ISO10126 4
#define EVP_PADDING_ZERO 5
#define EVP_AEAD_TLS1_AAD_LEN 13
#define EVP_GCM_TLS_FIXED_IV_LEN 4
#define EVP_GCM_TLS_EXPLICIT_IV_LEN 8
#define EVP_GCM_TLS_TAG_LEN 16
#define EVP_CCM_TLS_FIXED_IV_LEN 4
#define EVP_CCM_TLS_EXPLICIT_IV_LEN 8
#define EVP_CCM_TLS_IV_LEN 12
#define EVP_CCM_TLS_TAG_LEN 16
#define EVP_CCM8_TLS_TAG_LEN 8
#define EVP_CHACHAPOLY_TLS_TAG_LEN 16
#define EVP_PKEY_assign_RSA(pkey, rsa)
#define EVP_PKEY_assign_DSA(pkey, dsa)
#define EVP_PKEY_assign_DH(pkey, dh)
#define EVP_PKEY_assign_EC_KEY(pkey, eckey)
#define EVP_PKEY_assign_SIPHASH(pkey, shkey)
#define EVP_PKEY_assign_POLY1305(pkey, polykey)
#define EVP_get_digestbynid(a) EVP_get_digestbyname(OBJ_nid2sn(a))
#define EVP_get_digestbyobj(a) EVP_get_digestbynid(OBJ_obj2nid(a))
#define EVP_get_cipherbynid(a) EVP_get_cipherbyname(OBJ_nid2sn(a))
#define EVP_get_cipherbyobj(a) EVP_get_cipherbynid(OBJ_obj2nid(a))
#define EVP_MD_nid(e) EVP_MD_type(e)
#define EVP_MD_name(e) OBJ_nid2sn(EVP_MD_nid(e))
#define EVP_MD_CTX_size(e) EVP_MD_size(EVP_MD_CTX_md(e))
#define EVP_MD_CTX_block_size(e) EVP_MD_block_size(EVP_MD_CTX_md(e))
#define EVP_MD_CTX_type(e) EVP_MD_type(EVP_MD_CTX_md(e))
#define EVP_CIPHER_name(e) OBJ_nid2sn(EVP_CIPHER_nid(e))
#define EVP_CIPHER_mode(e) (EVP_CIPHER_flags(e) & EVP_CIPH_MODE)
#define EVP_CIPHER_CTX_type(c) EVP_CIPHER_type(EVP_CIPHER_CTX_cipher(c))
#define EVP_CIPHER_CTX_flags(c) EVP_CIPHER_flags(EVP_CIPHER_CTX_cipher(c))
#define EVP_CIPHER_CTX_mode(c) EVP_CIPHER_mode(EVP_CIPHER_CTX_cipher(c))
#define EVP_ENCODE_LENGTH(l) (((l+2)/3*4)+(l/48+1)*2+80)
#define EVP_DECODE_LENGTH(l) ((l+3)/4*3+80)
#define EVP_SignInit_ex(a, b, c) EVP_DigestInit_ex(a,b,c)
#define EVP_SignInit(a, b) EVP_DigestInit(a,b)
#define EVP_SignUpdate(a, b, c) EVP_DigestUpdate(a,b,c)
#define EVP_VerifyInit_ex(a, b, c) EVP_DigestInit_ex(a,b,c)
#define EVP_VerifyInit(a, b) EVP_DigestInit(a,b)
#define EVP_VerifyUpdate(a, b, c) EVP_DigestUpdate(a,b,c)
#define EVP_OpenUpdate(a, b, c, d, e) EVP_DecryptUpdate(a,b,c,d,e)
#define EVP_SealUpdate(a, b, c, d, e) EVP_EncryptUpdate(a,b,c,d,e)
#define EVP_DigestSignUpdate(a, b, c) EVP_DigestUpdate(a,b,c)
#define EVP_DigestVerifyUpdate(a, b, c) EVP_DigestUpdate(a,b,c)
#define BIO_set_md(b, md) BIO_ctrl(b,BIO_C_SET_MD,0,(char *)md)
#define BIO_get_md(b, mdp) BIO_ctrl(b,BIO_C_GET_MD,0,(char *)mdp)
#define BIO_get_md_ctx(b, mdcp) BIO_ctrl(b,BIO_C_GET_MD_CTX,0,(char *)mdcp)
#define BIO_set_md_ctx(b, mdcp) BIO_ctrl(b,BIO_C_SET_MD_CTX,0,(char *)mdcp)
#define BIO_get_cipher_status(b) BIO_ctrl(b,BIO_C_GET_CIPHER_STATUS,0,NULL)
#define BIO_get_cipher_ctx(b, c_pp) BIO_ctrl(b,BIO_C_GET_CIPHER_CTX,0,(char *)c_pp)
#define EVP_add_cipher_alias(n, alias) OBJ_NAME_add((alias),OBJ_NAME_TYPE_CIPHER_METH|OBJ_NAME_ALIAS,(n))
#define EVP_add_digest_alias(n, alias) OBJ_NAME_add((alias),OBJ_NAME_TYPE_MD_METH|OBJ_NAME_ALIAS,(n))
#define EVP_delete_cipher_alias(alias) OBJ_NAME_remove(alias,OBJ_NAME_TYPE_CIPHER_METH|OBJ_NAME_ALIAS);
#define EVP_delete_digest_alias(alias) OBJ_NAME_remove(alias,OBJ_NAME_TYPE_MD_METH|OBJ_NAME_ALIAS);
#define EVP_MD_CTX_create() EVP_MD_CTX_new()
#define EVP_MD_CTX_init(ctx) EVP_MD_CTX_reset((ctx))
#define EVP_MD_CTX_destroy(ctx) EVP_MD_CTX_free((ctx))
#define EVP_CIPHER_CTX_init(c) EVP_CIPHER_CTX_reset(c)
#define EVP_CIPHER_CTX_cleanup(c) EVP_CIPHER_CTX_reset(c)
#define EVP_des_cfb EVP_des_cfb64
#define EVP_des_ede_cfb EVP_des_ede_cfb64
#define EVP_des_ede3_cfb EVP_des_ede3_cfb64
#define EVP_idea_cfb EVP_idea_cfb64
#define EVP_rc2_cfb EVP_rc2_cfb64
#define EVP_bf_cfb EVP_bf_cfb64
#define EVP_cast5_cfb EVP_cast5_cfb64
#define EVP_rc5_32_12_16_cfb EVP_rc5_32_12_16_cfb64
#define EVP_aes_128_cfb EVP_aes_128_cfb128
#define EVP_aes_192_cfb EVP_aes_192_cfb128
#define EVP_aes_256_cfb EVP_aes_256_cfb128
#define EVP_camellia_128_cfb EVP_camellia_128_cfb128
#define EVP_camellia_192_cfb EVP_camellia_192_cfb128
#define EVP_camellia_256_cfb EVP_camellia_256_cfb128
#define EVP_seed_cfb EVP_seed_cfb128
#define OPENSSL_add_all_algorithms_conf()
#define OPENSSL_add_all_algorithms_noconf()
#define OpenSSL_add_all_algorithms()
#define OpenSSL_add_all_ciphers() OPENSSL_init_crypto(OPENSSL_INIT_ADD_ALL_CIPHERS, NULL)
#define OpenSSL_add_all_digests() OPENSSL_init_crypto(OPENSSL_INIT_ADD_ALL_DIGESTS, NULL)
#define EVP_cleanup() while(0) continue
#define EVP_PBE_TYPE_OUTER 0x0
#define EVP_PBE_TYPE_PRF 0x1
#define EVP_PBE_TYPE_KDF 0x2
#define ASN1_PKEY_ALIAS 0x1
#define ASN1_PKEY_DYNAMIC 0x2
#define ASN1_PKEY_SIGPARAM_NULL 0x4
#define ASN1_PKEY_CTRL_PKCS7_SIGN 0x1
#define ASN1_PKEY_CTRL_PKCS7_ENCRYPT 0x2
#define ASN1_PKEY_CTRL_DEFAULT_MD_NID 0x3
#define ASN1_PKEY_CTRL_CMS_SIGN 0x5
#define ASN1_PKEY_CTRL_CMS_ENVELOPE 0x7
#define ASN1_PKEY_CTRL_CMS_RI_TYPE 0x8
#define ASN1_PKEY_CTRL_SET1_TLS_ENCPT 0x9
#define ASN1_PKEY_CTRL_GET1_TLS_ENCPT 0xa
#define EVP_PKEY_OP_UNDEFINED 0
#define EVP_PKEY_OP_PARAMGEN (1<<1)
#define EVP_PKEY_OP_KEYGEN (1<<2)
#define EVP_PKEY_OP_SIGN (1<<3)
#define EVP_PKEY_OP_VERIFY (1<<4)
#define EVP_PKEY_OP_VERIFYRECOVER (1<<5)
#define EVP_PKEY_OP_SIGNCTX (1<<6)
#define EVP_PKEY_OP_VERIFYCTX (1<<7)
#define EVP_PKEY_OP_ENCRYPT (1<<8)
#define EVP_PKEY_OP_DECRYPT (1<<9)
#define EVP_PKEY_OP_DERIVE (1<<10)
#define EVP_PKEY_OP_TYPE_SIG
#define EVP_PKEY_OP_TYPE_CRYPT (EVP_PKEY_OP_ENCRYPT | EVP_PKEY_OP_DECRYPT)
#define EVP_PKEY_OP_TYPE_NOGEN (EVP_PKEY_OP_TYPE_SIG | EVP_PKEY_OP_TYPE_CRYPT | EVP_PKEY_OP_DERIVE)
#define EVP_PKEY_OP_TYPE_GEN (EVP_PKEY_OP_PARAMGEN | EVP_PKEY_OP_KEYGEN)
#define EVP_PKEY_CTX_set_signature_md(ctx, md)
#define EVP_PKEY_CTX_get_signature_md(ctx, pmd)
#define EVP_PKEY_CTX_set_mac_key(ctx, key, len)
#define EVP_PKEY_CTRL_MD 1
#define EVP_PKEY_CTRL_PEER_KEY 2
#define EVP_PKEY_CTRL_PKCS7_ENCRYPT 3
#define EVP_PKEY_CTRL_PKCS7_DECRYPT 4
#define EVP_PKEY_CTRL_PKCS7_SIGN 5
#define EVP_PKEY_CTRL_SET_MAC_KEY 6
#define EVP_PKEY_CTRL_DIGESTINIT 7
#define EVP_PKEY_CTRL_SET_IV 8
#define EVP_PKEY_CTRL_CMS_ENCRYPT 9
#define EVP_PKEY_CTRL_CMS_DECRYPT 10
#define EVP_PKEY_CTRL_CMS_SIGN 11
#define EVP_PKEY_CTRL_CIPHER 12
#define EVP_PKEY_CTRL_GET_MD 13
#define EVP_PKEY_CTRL_SET_DIGEST_SIZE 14
#define EVP_PKEY_ALG_CTRL 0x1000
#define EVP_PKEY_FLAG_AUTOARGLEN 2
#define EVP_PKEY_FLAG_SIGCTX_CUSTOM 4
#define EVP_F_AESNI_INIT_KEY 165
#define EVP_F_AES_INIT_KEY 133
#define EVP_F_AES_OCB_CIPHER 169
#define EVP_F_AES_T4_INIT_KEY 178
#define EVP_F_AES_WRAP_CIPHER 170
#define EVP_F_ALG_MODULE_INIT 177
#define EVP_F_CAMELLIA_INIT_KEY 159
#define EVP_F_CHACHA20_POLY1305_CTRL 182
#define EVP_F_CMLL_T4_INIT_KEY 179
#define EVP_F_DES_EDE3_WRAP_CIPHER 171
#define EVP_F_DO_SIGVER_INIT 161
#define EVP_F_EVP_CIPHERINIT_EX 123
#define EVP_F_EVP_CIPHER_CTX_COPY 163
#define EVP_F_EVP_CIPHER_CTX_CTRL 124
#define EVP_F_EVP_CIPHER_CTX_SET_KEY_LENGTH 122
#define EVP_F_EVP_DECRYPTFINAL_EX 101
#define EVP_F_EVP_DECRYPTUPDATE 166
#define EVP_F_EVP_DIGESTINIT_EX 128
#define EVP_F_EVP_ENCRYPTFINAL_EX 127
#define EVP_F_EVP_ENCRYPTUPDATE 167
#define EVP_F_EVP_MD_CTX_COPY_EX 110
#define EVP_F_EVP_MD_SIZE 162
#define EVP_F_EVP_OPENINIT 102
#define EVP_F_EVP_PBE_ALG_ADD 115
#define EVP_F_EVP_PBE_ALG_ADD_TYPE 160
#define EVP_F_EVP_PBE_CIPHERINIT 116
#define EVP_F_EVP_PBE_SCRYPT 181
#define EVP_F_EVP_PKCS82PKEY 111
#define EVP_F_EVP_PKEY2PKCS8 113
#define EVP_F_EVP_PKEY_COPY_PARAMETERS 103
#define EVP_F_EVP_PKEY_CTX_CTRL 137
#define EVP_F_EVP_PKEY_CTX_CTRL_STR 150
#define EVP_F_EVP_PKEY_CTX_DUP 156
#define EVP_F_EVP_PKEY_CTX_MD 168
#define EVP_F_EVP_PKEY_DECRYPT 104
#define EVP_F_EVP_PKEY_DECRYPT_INIT 138
#define EVP_F_EVP_PKEY_DECRYPT_OLD 151
#define EVP_F_EVP_PKEY_DERIVE 153
#define EVP_F_EVP_PKEY_DERIVE_INIT 154
#define EVP_F_EVP_PKEY_DERIVE_SET_PEER 155
#define EVP_F_EVP_PKEY_ENCRYPT 105
#define EVP_F_EVP_PKEY_ENCRYPT_INIT 139
#define EVP_F_EVP_PKEY_ENCRYPT_OLD 152
#define EVP_F_EVP_PKEY_GET0_DH 119
#define EVP_F_EVP_PKEY_GET0_DSA 120
#define EVP_F_EVP_PKEY_GET0_EC_KEY 131
#define EVP_F_EVP_PKEY_GET0_HMAC 183
#define EVP_F_EVP_PKEY_GET0_POLY1305 184
#define EVP_F_EVP_PKEY_GET0_RSA 121
#define EVP_F_EVP_PKEY_GET0_SIPHASH 172
#define EVP_F_EVP_PKEY_KEYGEN 146
#define EVP_F_EVP_PKEY_KEYGEN_INIT 147
#define EVP_F_EVP_PKEY_NEW 106
#define EVP_F_EVP_PKEY_PARAMGEN 148
#define EVP_F_EVP_PKEY_PARAMGEN_INIT 149
#define EVP_F_EVP_PKEY_SIGN 140
#define EVP_F_EVP_PKEY_SIGN_INIT 141
#define EVP_F_EVP_PKEY_VERIFY 142
#define EVP_F_EVP_PKEY_VERIFY_INIT 143
#define EVP_F_EVP_PKEY_VERIFY_RECOVER 144
#define EVP_F_EVP_PKEY_VERIFY_RECOVER_INIT 145
#define EVP_F_EVP_SIGNFINAL 107
#define EVP_F_EVP_VERIFYFINAL 108
#define EVP_F_INT_CTX_NEW 157
#define EVP_F_PKCS5_PBE_KEYIVGEN 117
#define EVP_F_PKCS5_V2_PBE_KEYIVGEN 118
#define EVP_F_PKCS5_V2_PBKDF2_KEYIVGEN 164
#define EVP_F_PKCS5_V2_SCRYPT_KEYIVGEN 180
#define EVP_F_PKEY_SET_TYPE 158
#define EVP_F_RC2_MAGIC_TO_METH 109
#define EVP_F_RC5_CTRL 125
#define EVP_R_AES_KEY_SETUP_FAILED 143
#define EVP_R_BAD_DECRYPT 100
#define EVP_R_BUFFER_TOO_SMALL 155
#define EVP_R_CAMELLIA_KEY_SETUP_FAILED 157
#define EVP_R_CIPHER_PARAMETER_ERROR 122
#define EVP_R_COMMAND_NOT_SUPPORTED 147
#define EVP_R_COPY_ERROR 173
#define EVP_R_CTRL_NOT_IMPLEMENTED 132
#define EVP_R_CTRL_OPERATION_NOT_IMPLEMENTED 133
#define EVP_R_DATA_NOT_MULTIPLE_OF_BLOCK_LENGTH 138
#define EVP_R_DECODE_ERROR 114
#define EVP_R_DIFFERENT_KEY_TYPES 101
#define EVP_R_DIFFERENT_PARAMETERS 153
#define EVP_R_ERROR_LOADING_SECTION 165
#define EVP_R_ERROR_SETTING_FIPS_MODE 166
#define EVP_R_EXPECTING_AN_HMAC_KEY 174
#define EVP_R_EXPECTING_AN_RSA_KEY 127
#define EVP_R_EXPECTING_A_DH_KEY 128
#define EVP_R_EXPECTING_A_DSA_KEY 129
#define EVP_R_EXPECTING_A_EC_KEY 142
#define EVP_R_EXPECTING_A_POLY1305_KEY 164
#define EVP_R_EXPECTING_A_SIPHASH_KEY 175
#define EVP_R_FIPS_MODE_NOT_SUPPORTED 167
#define EVP_R_ILLEGAL_SCRYPT_PARAMETERS 171
#define EVP_R_INITIALIZATION_ERROR 134
#define EVP_R_INPUT_NOT_INITIALIZED 111
#define EVP_R_INVALID_DIGEST 152
#define EVP_R_INVALID_FIPS_MODE 168
#define EVP_R_INVALID_KEY 163
#define EVP_R_INVALID_KEY_LENGTH 130
#define EVP_R_INVALID_OPERATION 148
#define EVP_R_KEYGEN_FAILURE 120
#define EVP_R_MEMORY_LIMIT_EXCEEDED 172
#define EVP_R_MESSAGE_DIGEST_IS_NULL 159
#define EVP_R_METHOD_NOT_SUPPORTED 144
#define EVP_R_MISSING_PARAMETERS 103
#define EVP_R_NO_CIPHER_SET 131
#define EVP_R_NO_DEFAULT_DIGEST 158
#define EVP_R_NO_DIGEST_SET 139
#define EVP_R_NO_KEY_SET 154
#define EVP_R_NO_OPERATION_SET 149
#define EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE 150
#define EVP_R_OPERATON_NOT_INITIALIZED 151
#define EVP_R_PARTIALLY_OVERLAPPING 162
#define EVP_R_PRIVATE_KEY_DECODE_ERROR 145
#define EVP_R_PRIVATE_KEY_ENCODE_ERROR 146
#define EVP_R_PUBLIC_KEY_NOT_RSA 106
#define EVP_R_UNKNOWN_CIPHER 160
#define EVP_R_UNKNOWN_DIGEST 161
#define EVP_R_UNKNOWN_OPTION 169
#define EVP_R_UNKNOWN_PBE_ALGORITHM 121
#define EVP_R_UNSUPPORTED_ALGORITHM 156
#define EVP_R_UNSUPPORTED_CIPHER 107
#define EVP_R_UNSUPPORTED_KEYLENGTH 123
#define EVP_R_UNSUPPORTED_KEY_DERIVATION_FUNCTION 124
#define EVP_R_UNSUPPORTED_KEY_SIZE 108
#define EVP_R_UNSUPPORTED_NUMBER_OF_ROUNDS 135
#define EVP_R_UNSUPPORTED_PRF 125
#define EVP_R_UNSUPPORTED_PRIVATE_KEY_ALGORITHM 118
#define EVP_R_UNSUPPORTED_SALT_TYPE 126
#define EVP_R_WRAP_MODE_NOT_ALLOWED 170
#define EVP_R_WRONG_FINAL_BLOCK_LENGTH 109
Typedefs
typedef int(EVP_PBE_KEYGEN) (EVP_CIPHER_CTX *ctx, const char *pass, int passlen, ASN1_TYPE *param, const EVP_CIPHER *cipher, const EVP_MD *md, int en_de)
typedef int EVP_PKEY_gen_cb(EVP_PKEY_CTX *ctx)
Functions
EVP_MD * EVP_MD_meth_new (int md_type, int pkey_type)
EVP_MD * EVP_MD_meth_dup (const EVP_MD *md)
void EVP_MD_meth_free (EVP_MD *md)
int EVP_MD_meth_set_input_blocksize (EVP_MD *md, int blocksize)
int EVP_MD_meth_set_result_size (EVP_MD *md, int resultsize)
int EVP_MD_meth_set_app_datasize (EVP_MD *md, int datasize)
int EVP_MD_meth_set_flags (EVP_MD *md, unsigned long flags)
int EVP_MD_meth_set_init (EVP_MD *md, int(*init)(EVP_MD_CTX *ctx))
int EVP_MD_meth_set_update (EVP_MD *md, int(*update)(EVP_MD_CTX *ctx, const void *data, size_t count))
int EVP_MD_meth_set_final (EVP_MD *md, int(*final)(EVP_MD_CTX *ctx, unsigned char *md))
int EVP_MD_meth_set_copy (EVP_MD *md, int(*copy)(EVP_MD_CTX *to, const EVP_MD_CTX *from))
int EVP_MD_meth_set_cleanup (EVP_MD *md, int(*cleanup)(EVP_MD_CTX *ctx))
int EVP_MD_meth_set_ctrl (EVP_MD *md, int(*ctrl)(EVP_MD_CTX *ctx, int cmd, int p1, void *p2))
int EVP_MD_meth_get_input_blocksize (const EVP_MD *md)
int EVP_MD_meth_get_result_size (const EVP_MD *md)
int EVP_MD_meth_get_app_datasize (const EVP_MD *md)
unsigned long EVP_MD_meth_get_flags (const EVP_MD *md)
EVP_CIPHER * EVP_CIPHER_meth_new (int cipher_type, int block_size, int key_len)
EVP_CIPHER * EVP_CIPHER_meth_dup (const EVP_CIPHER *cipher)
void EVP_CIPHER_meth_free (EVP_CIPHER *cipher)
int EVP_CIPHER_meth_set_iv_length (EVP_CIPHER *cipher, int iv_len)
int EVP_CIPHER_meth_set_flags (EVP_CIPHER *cipher, unsigned long flags)
int EVP_CIPHER_meth_set_impl_ctx_size (EVP_CIPHER *cipher, int ctx_size)
int EVP_CIPHER_meth_set_init (EVP_CIPHER *cipher, int(*init)(EVP_CIPHER_CTX *ctx, const unsigned char *key, const unsigned char *iv, int enc))
int EVP_CIPHER_meth_set_do_cipher (EVP_CIPHER *cipher, int(*do_cipher)(EVP_CIPHER_CTX *ctx, unsigned char *out, const unsigned char *in, size_t inl))
int EVP_CIPHER_meth_set_cleanup (EVP_CIPHER *cipher, int(*cleanup)(EVP_CIPHER_CTX *))
int EVP_CIPHER_meth_set_set_asn1_params (EVP_CIPHER *cipher, int(*set_asn1_parameters)(EVP_CIPHER_CTX *, ASN1_TYPE *))
int EVP_CIPHER_meth_set_get_asn1_params (EVP_CIPHER *cipher, int(*get_asn1_parameters)(EVP_CIPHER_CTX *, ASN1_TYPE *))
int EVP_CIPHER_meth_set_ctrl (EVP_CIPHER *cipher, int(*ctrl)(EVP_CIPHER_CTX *, int type, int arg, void *ptr))
int EVP_MD_type (const EVP_MD *md)
int EVP_MD_pkey_type (const EVP_MD *md)
int EVP_MD_size (const EVP_MD *md)
int EVP_MD_block_size (const EVP_MD *md)
unsigned long EVP_MD_flags (const EVP_MD *md)
const EVP_MD * EVP_MD_CTX_md (const EVP_MD_CTX *ctx)
void EVP_MD_CTX_set_update_fn (EVP_MD_CTX *ctx, int(*update)(EVP_MD_CTX *ctx, const void *data, size_t count))
EVP_PKEY_CTX * EVP_MD_CTX_pkey_ctx (const EVP_MD_CTX *ctx)
void * EVP_MD_CTX_md_data (const EVP_MD_CTX *ctx)
int EVP_CIPHER_nid (const EVP_CIPHER *cipher)
int EVP_CIPHER_block_size (const EVP_CIPHER *cipher)
int EVP_CIPHER_impl_ctx_size (const EVP_CIPHER *cipher)
int EVP_CIPHER_key_length (const EVP_CIPHER *cipher)
int EVP_CIPHER_iv_length (const EVP_CIPHER *cipher)
unsigned long EVP_CIPHER_flags (const EVP_CIPHER *cipher)
const EVP_CIPHER * EVP_CIPHER_CTX_cipher (const EVP_CIPHER_CTX *ctx)
int EVP_CIPHER_CTX_encrypting (const EVP_CIPHER_CTX *ctx)
int EVP_CIPHER_CTX_nid (const EVP_CIPHER_CTX *ctx)
int EVP_CIPHER_CTX_block_size (const EVP_CIPHER_CTX *ctx)
int EVP_CIPHER_CTX_key_length (const EVP_CIPHER_CTX *ctx)
int EVP_CIPHER_CTX_iv_length (const EVP_CIPHER_CTX *ctx)
const unsigned char * EVP_CIPHER_CTX_iv (const EVP_CIPHER_CTX *ctx)
const unsigned char * EVP_CIPHER_CTX_original_iv (const EVP_CIPHER_CTX *ctx)
unsigned char * EVP_CIPHER_CTX_iv_noconst (EVP_CIPHER_CTX *ctx)
unsigned char * EVP_CIPHER_CTX_buf_noconst (EVP_CIPHER_CTX *ctx)
int EVP_CIPHER_CTX_num (const EVP_CIPHER_CTX *ctx)
void EVP_CIPHER_CTX_set_num (EVP_CIPHER_CTX *ctx, int num)
int EVP_CIPHER_CTX_copy (EVP_CIPHER_CTX *out, const EVP_CIPHER_CTX *in)
void * EVP_CIPHER_CTX_get_app_data (const EVP_CIPHER_CTX *ctx)
void EVP_CIPHER_CTX_set_app_data (EVP_CIPHER_CTX *ctx, void *data)
void * EVP_CIPHER_CTX_get_cipher_data (const EVP_CIPHER_CTX *ctx)
void * EVP_CIPHER_CTX_set_cipher_data (EVP_CIPHER_CTX *ctx, void *cipher_data)
int EVP_Cipher (EVP_CIPHER_CTX *c, unsigned char *out, const unsigned char *in, unsigned int inl)
int EVP_MD_CTX_ctrl (EVP_MD_CTX *ctx, int cmd, int p1, void *p2)
EVP_MD_CTX * EVP_MD_CTX_new (void)
int EVP_MD_CTX_reset (EVP_MD_CTX *ctx)
void EVP_MD_CTX_free (EVP_MD_CTX *ctx)
__owur int EVP_MD_CTX_copy_ex (EVP_MD_CTX *out, const EVP_MD_CTX *in)
void EVP_MD_CTX_set_flags (EVP_MD_CTX *ctx, int flags)
void EVP_MD_CTX_clear_flags (EVP_MD_CTX *ctx, int flags)
int EVP_MD_CTX_test_flags (const EVP_MD_CTX *ctx, int flags)
__owur int EVP_DigestInit_ex (EVP_MD_CTX *ctx, const EVP_MD *type, ENGINE *impl)
__owur int EVP_DigestUpdate (EVP_MD_CTX *ctx, const void *d, size_t cnt)
__owur int EVP_DigestFinal_ex (EVP_MD_CTX *ctx, unsigned char *md, unsigned int *s)
__owur int EVP_Digest (const void *data, size_t count, unsigned char *md, unsigned int *size, const EVP_MD *type, ENGINE *impl)
__owur int EVP_MD_CTX_copy (EVP_MD_CTX *out, const EVP_MD_CTX *in)
__owur int EVP_DigestInit (EVP_MD_CTX *ctx, const EVP_MD *type)
__owur int EVP_DigestFinal (EVP_MD_CTX *ctx, unsigned char *md, unsigned int *s)
int EVP_read_pw_string (char *buf, int length, const char *prompt, int verify)
int EVP_read_pw_string_min (char *buf, int minlen, int maxlen, const char *prompt, int verify)
void EVP_set_pw_prompt (const char *prompt)
char * EVP_get_pw_prompt (void)
__owur int EVP_BytesToKey (const EVP_CIPHER *type, const EVP_MD *md, const unsigned char *salt, const unsigned char *data, int datal, int count, unsigned char *key, unsigned char *iv)
void EVP_CIPHER_CTX_set_flags (EVP_CIPHER_CTX *ctx, int flags)
void EVP_CIPHER_CTX_clear_flags (EVP_CIPHER_CTX *ctx, int flags)
int EVP_CIPHER_CTX_test_flags (const EVP_CIPHER_CTX *ctx, int flags)
__owur int EVP_EncryptInit (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, const unsigned char *key, const unsigned char *iv)
int EVP_EncryptInit_ex (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, ENGINE *impl, const unsigned char *key, const unsigned char *iv)
int EVP_EncryptUpdate (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl)
int EVP_EncryptFinal_ex (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl)
int EVP_EncryptFinal (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl)
__owur int EVP_DecryptInit (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, const unsigned char *key, const unsigned char *iv)
int EVP_DecryptInit_ex (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, ENGINE *impl, const unsigned char *key, const unsigned char *iv)
int EVP_DecryptUpdate (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl)
__owur int EVP_DecryptFinal (EVP_CIPHER_CTX *ctx, unsigned char *outm, int *outl)
int EVP_DecryptFinal_ex (EVP_CIPHER_CTX *ctx, unsigned char *outm, int *outl)
__owur int EVP_CipherInit (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, const unsigned char *key, const unsigned char *iv, int enc)
int EVP_CipherInit_ex (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher, ENGINE *impl, const unsigned char *key, const unsigned char *iv, int enc)
__owur int EVP_CipherUpdate (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl)
__owur int EVP_CipherFinal (EVP_CIPHER_CTX *ctx, unsigned char *outm, int *outl)
__owur int EVP_CipherFinal_ex (EVP_CIPHER_CTX *ctx, unsigned char *outm, int *outl)
__owur int EVP_SignFinal (EVP_MD_CTX *ctx, unsigned char *md, unsigned int *s, EVP_PKEY *pkey)
__owur int EVP_VerifyFinal (EVP_MD_CTX *ctx, const unsigned char *sigbuf, unsigned int siglen, EVP_PKEY *pkey)
int EVP_DigestSignInit (EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx, const EVP_MD *type, ENGINE *e, EVP_PKEY *pkey)
__owur int EVP_DigestSignFinal (EVP_MD_CTX *ctx, unsigned char *sigret, size_t *siglen)
__owur int EVP_DigestVerifyInit (EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx, const EVP_MD *type, ENGINE *e, EVP_PKEY *pkey)
__owur int EVP_DigestVerifyFinal (EVP_MD_CTX *ctx, const unsigned char *sig, size_t siglen)
__owur int EVP_OpenInit (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *type, const unsigned char *ek, int ekl, const unsigned char *iv, EVP_PKEY *priv)
__owur int EVP_OpenFinal (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl)
__owur int EVP_SealInit (EVP_CIPHER_CTX *ctx, const EVP_CIPHER *type, unsigned char **ek, int *ekl, unsigned char *iv, EVP_PKEY **pubk, int npubk)
__owur int EVP_SealFinal (EVP_CIPHER_CTX *ctx, unsigned char *out, int *outl)
EVP_ENCODE_CTX * EVP_ENCODE_CTX_new (void)
void EVP_ENCODE_CTX_free (EVP_ENCODE_CTX *ctx)
int EVP_ENCODE_CTX_copy (EVP_ENCODE_CTX *dctx, EVP_ENCODE_CTX *sctx)
int EVP_ENCODE_CTX_num (EVP_ENCODE_CTX *ctx)
void EVP_EncodeInit (EVP_ENCODE_CTX *ctx)
int EVP_EncodeUpdate (EVP_ENCODE_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl)
void EVP_EncodeFinal (EVP_ENCODE_CTX *ctx, unsigned char *out, int *outl)
int EVP_EncodeBlock (unsigned char *t, const unsigned char *f, int n)
void EVP_DecodeInit (EVP_ENCODE_CTX *ctx)
int EVP_DecodeUpdate (EVP_ENCODE_CTX *ctx, unsigned char *out, int *outl, const unsigned char *in, int inl)
int EVP_DecodeFinal (EVP_ENCODE_CTX *ctx, unsigned char *out, int *outl)
int EVP_DecodeBlock (unsigned char *t, const unsigned char *f, int n)
EVP_CIPHER_CTX * EVP_CIPHER_CTX_new (void)
int EVP_CIPHER_CTX_reset (EVP_CIPHER_CTX *c)
void EVP_CIPHER_CTX_free (EVP_CIPHER_CTX *c)
int EVP_CIPHER_CTX_set_key_length (EVP_CIPHER_CTX *x, int keylen)
int EVP_CIPHER_CTX_set_padding (EVP_CIPHER_CTX *c, int pad)
int EVP_CIPHER_CTX_ctrl (EVP_CIPHER_CTX *ctx, int type, int arg, void *ptr)
int EVP_CIPHER_CTX_rand_key (EVP_CIPHER_CTX *ctx, unsigned char *key)
const BIO_METHOD * BIO_f_md (void)
const BIO_METHOD * BIO_f_base64 (void)
const BIO_METHOD * BIO_f_cipher (void)
const BIO_METHOD * BIO_f_reliable (void)
__owur int BIO_set_cipher (BIO *b, const EVP_CIPHER *c, const unsigned char *k, const unsigned char *i, int enc)
const EVP_MD * EVP_md_null (void)
const EVP_MD * EVP_md2 (void)
const EVP_MD * EVP_md4 (void)
const EVP_MD * EVP_md5 (void)
const EVP_MD * EVP_md5_sha1 (void)
const EVP_MD * EVP_blake2b512 (void)
const EVP_MD * EVP_blake2s256 (void)
const EVP_MD * EVP_sha1 (void)
const EVP_MD * EVP_sha224 (void)
const EVP_MD * EVP_sha256 (void)
const EVP_MD * EVP_sha384 (void)
const EVP_MD * EVP_sha512 (void)
const EVP_MD * EVP_mdc2 (void)
const EVP_MD * EVP_ripemd160 (void)
const EVP_MD * EVP_whirlpool (void)
const EVP_CIPHER * EVP_enc_null (void)
const EVP_CIPHER * EVP_des_ecb (void)
const EVP_CIPHER * EVP_des_ede (void)
const EVP_CIPHER * EVP_des_ede3 (void)
const EVP_CIPHER * EVP_des_ede_ecb (void)
const EVP_CIPHER * EVP_des_ede3_ecb (void)
const EVP_CIPHER * EVP_des_cfb64 (void)
const EVP_CIPHER * EVP_des_cfb1 (void)
const EVP_CIPHER * EVP_des_cfb8 (void)
const EVP_CIPHER * EVP_des_ede_cfb64 (void)
const EVP_CIPHER * EVP_des_ede3_cfb64 (void)
const EVP_CIPHER * EVP_des_ede3_cfb1 (void)
const EVP_CIPHER * EVP_des_ede3_cfb8 (void)
const EVP_CIPHER * EVP_des_ofb (void)
const EVP_CIPHER * EVP_des_ede_ofb (void)
const EVP_CIPHER * EVP_des_ede3_ofb (void)
const EVP_CIPHER * EVP_des_cbc (void)
const EVP_CIPHER * EVP_des_ede_cbc (void)
const EVP_CIPHER * EVP_des_ede3_cbc (void)
const EVP_CIPHER * EVP_desx_cbc (void)
const EVP_CIPHER * EVP_des_ede3_wrap (void)
const EVP_CIPHER * EVP_rc4 (void)
const EVP_CIPHER * EVP_rc4_40 (void)
const EVP_CIPHER * EVP_rc4_hmac_md5 (void)
const EVP_CIPHER * EVP_idea_ecb (void)
const EVP_CIPHER * EVP_idea_cfb64 (void)
const EVP_CIPHER * EVP_idea_ofb (void)
const EVP_CIPHER * EVP_idea_cbc (void)
const EVP_CIPHER * EVP_rc2_ecb (void)
const EVP_CIPHER * EVP_rc2_cbc (void)
const EVP_CIPHER * EVP_rc2_40_cbc (void)
const EVP_CIPHER * EVP_rc2_64_cbc (void)
const EVP_CIPHER * EVP_rc2_cfb64 (void)
const EVP_CIPHER * EVP_rc2_ofb (void)
const EVP_CIPHER * EVP_bf_ecb (void)
const EVP_CIPHER * EVP_bf_cbc (void)
const EVP_CIPHER * EVP_bf_cfb64 (void)
const EVP_CIPHER * EVP_bf_ofb (void)
const EVP_CIPHER * EVP_cast5_ecb (void)
const EVP_CIPHER * EVP_cast5_cbc (void)
const EVP_CIPHER * EVP_cast5_cfb64 (void)
const EVP_CIPHER * EVP_cast5_ofb (void)
const EVP_CIPHER * EVP_rc5_32_12_16_cbc (void)
const EVP_CIPHER * EVP_rc5_32_12_16_ecb (void)
const EVP_CIPHER * EVP_rc5_32_12_16_cfb64 (void)
const EVP_CIPHER * EVP_rc5_32_12_16_ofb (void)
const EVP_CIPHER * EVP_aes_128_ecb (void)
const EVP_CIPHER * EVP_aes_128_cbc (void)
const EVP_CIPHER * EVP_aes_128_cfb1 (void)
const EVP_CIPHER * EVP_aes_128_cfb8 (void)
const EVP_CIPHER * EVP_aes_128_cfb128 (void)
const EVP_CIPHER * EVP_aes_128_ofb (void)
const EVP_CIPHER * EVP_aes_128_ctr (void)
const EVP_CIPHER * EVP_aes_128_ccm (void)
const EVP_CIPHER * EVP_aes_128_gcm (void)
const EVP_CIPHER * EVP_aes_128_xts (void)
const EVP_CIPHER * EVP_aes_128_wrap (void)
const EVP_CIPHER * EVP_aes_128_wrap_pad (void)
const EVP_CIPHER * EVP_aes_128_ocb (void)
const EVP_CIPHER * EVP_aes_192_ecb (void)
const EVP_CIPHER * EVP_aes_192_cbc (void)
const EVP_CIPHER * EVP_aes_192_cfb1 (void)
const EVP_CIPHER * EVP_aes_192_cfb8 (void)
const EVP_CIPHER * EVP_aes_192_cfb128 (void)
const EVP_CIPHER * EVP_aes_192_ofb (void)
const EVP_CIPHER * EVP_aes_192_ctr (void)
const EVP_CIPHER * EVP_aes_192_ccm (void)
const EVP_CIPHER * EVP_aes_192_gcm (void)
const EVP_CIPHER * EVP_aes_192_wrap (void)
const EVP_CIPHER * EVP_aes_192_wrap_pad (void)
const EVP_CIPHER * EVP_aes_192_ocb (void)
const EVP_CIPHER * EVP_aes_256_ecb (void)
const EVP_CIPHER * EVP_aes_256_cbc (void)
const EVP_CIPHER * EVP_aes_256_cfb1 (void)
const EVP_CIPHER * EVP_aes_256_cfb8 (void)
const EVP_CIPHER * EVP_aes_256_cfb128 (void)
const EVP_CIPHER * EVP_aes_256_ofb (void)
const EVP_CIPHER * EVP_aes_256_ctr (void)
const EVP_CIPHER * EVP_aes_256_ccm (void)
const EVP_CIPHER * EVP_aes_256_gcm (void)
const EVP_CIPHER * EVP_aes_256_xts (void)
const EVP_CIPHER * EVP_aes_256_wrap (void)
const EVP_CIPHER * EVP_aes_256_wrap_pad (void)
const EVP_CIPHER * EVP_aes_256_ocb (void)
const EVP_CIPHER * EVP_aes_128_cbc_hmac_sha1 (void)
const EVP_CIPHER * EVP_aes_256_cbc_hmac_sha1 (void)
const EVP_CIPHER * EVP_aes_128_cbc_hmac_sha256 (void)
const EVP_CIPHER * EVP_aes_256_cbc_hmac_sha256 (void)
const EVP_CIPHER * EVP_camellia_128_ecb (void)
const EVP_CIPHER * EVP_camellia_128_cbc (void)
const EVP_CIPHER * EVP_camellia_128_cfb1 (void)
const EVP_CIPHER * EVP_camellia_128_cfb8 (void)
const EVP_CIPHER * EVP_camellia_128_cfb128 (void)
const EVP_CIPHER * EVP_camellia_128_ofb (void)
const EVP_CIPHER * EVP_camellia_128_ctr (void)
const EVP_CIPHER * EVP_camellia_192_ecb (void)
const EVP_CIPHER * EVP_camellia_192_cbc (void)
const EVP_CIPHER * EVP_camellia_192_cfb1 (void)
const EVP_CIPHER * EVP_camellia_192_cfb8 (void)
const EVP_CIPHER * EVP_camellia_192_cfb128 (void)
const EVP_CIPHER * EVP_camellia_192_ofb (void)
const EVP_CIPHER * EVP_camellia_192_ctr (void)
const EVP_CIPHER * EVP_camellia_256_ecb (void)
const EVP_CIPHER * EVP_camellia_256_cbc (void)
const EVP_CIPHER * EVP_camellia_256_cfb1 (void)
const EVP_CIPHER * EVP_camellia_256_cfb8 (void)
const EVP_CIPHER * EVP_camellia_256_cfb128 (void)
const EVP_CIPHER * EVP_camellia_256_ofb (void)
const EVP_CIPHER * EVP_camellia_256_ctr (void)
const EVP_CIPHER * EVP_chacha20 (void)
const EVP_CIPHER * EVP_chacha20_poly1305 (void)
const EVP_CIPHER * EVP_seed_ecb (void)
const EVP_CIPHER * EVP_seed_cbc (void)
const EVP_CIPHER * EVP_seed_cfb128 (void)
const EVP_CIPHER * EVP_seed_ofb (void)
int EVP_add_cipher (const EVP_CIPHER *cipher)
int EVP_add_digest (const EVP_MD *digest)
const EVP_CIPHER * EVP_get_cipherbyname (const char *name)
const EVP_MD * EVP_get_digestbyname (const char *name)
void EVP_CIPHER_do_all (void(*fn)(const EVP_CIPHER *ciph, const char *from, const char *to, void *x), void *arg)
void EVP_CIPHER_do_all_sorted (void(*fn)(const EVP_CIPHER *ciph, const char *from, const char *to, void *x), void *arg)
void EVP_MD_do_all (void(*fn)(const EVP_MD *ciph, const char *from, const char *to, void *x), void *arg)
void EVP_MD_do_all_sorted (void(*fn)(const EVP_MD *ciph, const char *from, const char *to, void *x), void *arg)
int EVP_PKEY_decrypt_old (unsigned char *dec_key, const unsigned char *enc_key, int enc_key_len, EVP_PKEY *private_key)
int EVP_PKEY_encrypt_old (unsigned char *enc_key, const unsigned char *key, int key_len, EVP_PKEY *pub_key)
int EVP_PKEY_type (int type)
int EVP_PKEY_id (const EVP_PKEY *pkey)
int EVP_PKEY_base_id (const EVP_PKEY *pkey)
int EVP_PKEY_bits (const EVP_PKEY *pkey)
int EVP_PKEY_security_bits (const EVP_PKEY *pkey)
int EVP_PKEY_size (EVP_PKEY *pkey)
int EVP_PKEY_set_type (EVP_PKEY *pkey, int type)
int EVP_PKEY_set_type_str (EVP_PKEY *pkey, const char *str, int len)
int EVP_PKEY_assign (EVP_PKEY *pkey, int type, void *key)
void * EVP_PKEY_get0 (const EVP_PKEY *pkey)
const unsigned char * EVP_PKEY_get0_hmac (const EVP_PKEY *pkey, size_t *len)
const unsigned char * EVP_PKEY_get0_poly1305 (const EVP_PKEY *pkey, size_t *len)
const unsigned char * EVP_PKEY_get0_siphash (const EVP_PKEY *pkey, size_t *len)
int EVP_PKEY_set1_RSA (EVP_PKEY *pkey, struct rsa_st *key)
struct rsa_st * EVP_PKEY_get0_RSA (EVP_PKEY *pkey)
struct rsa_st * EVP_PKEY_get1_RSA (EVP_PKEY *pkey)
int EVP_PKEY_set1_DSA (EVP_PKEY *pkey, struct dsa_st *key)
struct dsa_st * EVP_PKEY_get0_DSA (EVP_PKEY *pkey)
struct dsa_st * EVP_PKEY_get1_DSA (EVP_PKEY *pkey)
int EVP_PKEY_set1_DH (EVP_PKEY *pkey, struct dh_st *key)
struct dh_st * EVP_PKEY_get0_DH (EVP_PKEY *pkey)
struct dh_st * EVP_PKEY_get1_DH (EVP_PKEY *pkey)
int EVP_PKEY_set1_EC_KEY (EVP_PKEY *pkey, struct ec_key_st *key)
struct ec_key_st * EVP_PKEY_get0_EC_KEY (EVP_PKEY *pkey)
struct ec_key_st * EVP_PKEY_get1_EC_KEY (EVP_PKEY *pkey)
EVP_PKEY * EVP_PKEY_new (void)
int EVP_PKEY_up_ref (EVP_PKEY *pkey)
void EVP_PKEY_free (EVP_PKEY *pkey)
EVP_PKEY * d2i_PublicKey (int type, EVP_PKEY **a, const unsigned char **pp, long length)
int i2d_PublicKey (EVP_PKEY *a, unsigned char **pp)
EVP_PKEY * d2i_PrivateKey (int type, EVP_PKEY **a, const unsigned char **pp, long length)
EVP_PKEY * d2i_AutoPrivateKey (EVP_PKEY **a, const unsigned char **pp, long length)
int i2d_PrivateKey (EVP_PKEY *a, unsigned char **pp)
int EVP_PKEY_copy_parameters (EVP_PKEY *to, const EVP_PKEY *from)
int EVP_PKEY_missing_parameters (const EVP_PKEY *pkey)
int EVP_PKEY_save_parameters (EVP_PKEY *pkey, int mode)
int EVP_PKEY_cmp_parameters (const EVP_PKEY *a, const EVP_PKEY *b)
int EVP_PKEY_cmp (const EVP_PKEY *a, const EVP_PKEY *b)
int EVP_PKEY_print_public (BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx)
int EVP_PKEY_print_private (BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx)
int EVP_PKEY_print_params (BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx)
int EVP_PKEY_get_default_digest_nid (EVP_PKEY *pkey, int *pnid)
int EVP_PKEY_set1_tls_encodedpoint (EVP_PKEY *pkey, const unsigned char *pt, size_t ptlen)
size_t EVP_PKEY_get1_tls_encodedpoint (EVP_PKEY *pkey, unsigned char **ppt)
int EVP_CIPHER_type (const EVP_CIPHER *ctx)
int EVP_CIPHER_param_to_asn1 (EVP_CIPHER_CTX *c, ASN1_TYPE *type)
int EVP_CIPHER_asn1_to_param (EVP_CIPHER_CTX *c, ASN1_TYPE *type)
int EVP_CIPHER_set_asn1_iv (EVP_CIPHER_CTX *c, ASN1_TYPE *type)
int EVP_CIPHER_get_asn1_iv (EVP_CIPHER_CTX *c, ASN1_TYPE *type)
int PKCS5_PBE_keyivgen (EVP_CIPHER_CTX *ctx, const char *pass, int passlen, ASN1_TYPE *param, const EVP_CIPHER *cipher, const EVP_MD *md, int en_de)
int PKCS5_PBKDF2_HMAC_SHA1 (const char *pass, int passlen, const unsigned char *salt, int saltlen, int iter, int keylen, unsigned char *out)
int PKCS5_PBKDF2_HMAC (const char *pass, int passlen, const unsigned char *salt, int saltlen, int iter, const EVP_MD *digest, int keylen, unsigned char *out)
int PKCS5_v2_PBE_keyivgen (EVP_CIPHER_CTX *ctx, const char *pass, int passlen, ASN1_TYPE *param, const EVP_CIPHER *cipher, const EVP_MD *md, int en_de)
int EVP_PBE_scrypt (const char *pass, size_t passlen, const unsigned char *salt, size_t saltlen, uint64_t N, uint64_t r, uint64_t p, uint64_t maxmem, unsigned char *key, size_t keylen)
int PKCS5_v2_scrypt_keyivgen (EVP_CIPHER_CTX *ctx, const char *pass, int passlen, ASN1_TYPE *param, const EVP_CIPHER *c, const EVP_MD *md, int en_de)
void PKCS5_PBE_add (void)
int EVP_PBE_CipherInit (ASN1_OBJECT *pbe_obj, const char *pass, int passlen, ASN1_TYPE *param, EVP_CIPHER_CTX *ctx, int en_de)
int EVP_PBE_alg_add_type (int pbe_type, int pbe_nid, int cipher_nid, int md_nid, EVP_PBE_KEYGEN *keygen)
int EVP_PBE_alg_add (int nid, const EVP_CIPHER *cipher, const EVP_MD *md, EVP_PBE_KEYGEN *keygen)
int EVP_PBE_find (int type, int pbe_nid, int *pcnid, int *pmnid, EVP_PBE_KEYGEN **pkeygen)
void EVP_PBE_cleanup (void)
int EVP_PBE_get (int *ptype, int *ppbe_nid, size_t num)
int EVP_PKEY_asn1_get_count (void)
const EVP_PKEY_ASN1_METHOD * EVP_PKEY_asn1_get0 (int idx)
const EVP_PKEY_ASN1_METHOD * EVP_PKEY_asn1_find (ENGINE **pe, int type)
const EVP_PKEY_ASN1_METHOD * EVP_PKEY_asn1_find_str (ENGINE **pe, const char *str, int len)
int EVP_PKEY_asn1_add0 (const EVP_PKEY_ASN1_METHOD *ameth)
int EVP_PKEY_asn1_add_alias (int to, int from)
int EVP_PKEY_asn1_get0_info (int *ppkey_id, int *pkey_base_id, int *ppkey_flags, const char **pinfo, const char **ppem_str, const EVP_PKEY_ASN1_METHOD *ameth)
const EVP_PKEY_ASN1_METHOD * EVP_PKEY_get0_asn1 (const EVP_PKEY *pkey)
EVP_PKEY_ASN1_METHOD * EVP_PKEY_asn1_new (int id, int flags, const char *pem_str, const char *info)
void EVP_PKEY_asn1_copy (EVP_PKEY_ASN1_METHOD *dst, const EVP_PKEY_ASN1_METHOD *src)
void EVP_PKEY_asn1_free (EVP_PKEY_ASN1_METHOD *ameth)
void EVP_PKEY_asn1_set_public (EVP_PKEY_ASN1_METHOD *ameth, int(*pub_decode)(EVP_PKEY *pk, X509_PUBKEY *pub), int(*pub_encode)(X509_PUBKEY *pub, const EVP_PKEY *pk), int(*pub_cmp)(const EVP_PKEY *a, const EVP_PKEY *b), int(*pub_print)(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx), int(*pkey_size)(const EVP_PKEY *pk), int(*pkey_bits)(const EVP_PKEY *pk))
void EVP_PKEY_asn1_set_private (EVP_PKEY_ASN1_METHOD *ameth, int(*priv_decode)(EVP_PKEY *pk, const PKCS8_PRIV_KEY_INFO *p8inf), int(*priv_encode)(PKCS8_PRIV_KEY_INFO *p8, const EVP_PKEY *pk), int(*priv_print)(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx))
void EVP_PKEY_asn1_set_param (EVP_PKEY_ASN1_METHOD *ameth, int(*param_decode)(EVP_PKEY *pkey, const unsigned char **pder, int derlen), int(*param_encode)(const EVP_PKEY *pkey, unsigned char **pder), int(*param_missing)(const EVP_PKEY *pk), int(*param_copy)(EVP_PKEY *to, const EVP_PKEY *from), int(*param_cmp)(const EVP_PKEY *a, const EVP_PKEY *b), int(*param_print)(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx))
void EVP_PKEY_asn1_set_free (EVP_PKEY_ASN1_METHOD *ameth, void(*pkey_free)(EVP_PKEY *pkey))
void EVP_PKEY_asn1_set_ctrl (EVP_PKEY_ASN1_METHOD *ameth, int(*pkey_ctrl)(EVP_PKEY *pkey, int op, long arg1, void *arg2))
void EVP_PKEY_asn1_set_item (EVP_PKEY_ASN1_METHOD *ameth, int(*item_verify)(EVP_MD_CTX *ctx, const ASN1_ITEM *it, void *asn, X509_ALGOR *a, ASN1_BIT_STRING *sig, EVP_PKEY *pkey), int(*item_sign)(EVP_MD_CTX *ctx, const ASN1_ITEM *it, void *asn, X509_ALGOR *alg1, X509_ALGOR *alg2, ASN1_BIT_STRING *sig))
void EVP_PKEY_asn1_set_security_bits (EVP_PKEY_ASN1_METHOD *ameth, int(*pkey_security_bits)(const EVP_PKEY *pk))
const EVP_PKEY_METHOD * EVP_PKEY_meth_find (int type)
EVP_PKEY_METHOD * EVP_PKEY_meth_new (int id, int flags)
void EVP_PKEY_meth_get0_info (int *ppkey_id, int *pflags, const EVP_PKEY_METHOD *meth)
void EVP_PKEY_meth_copy (EVP_PKEY_METHOD *dst, const EVP_PKEY_METHOD *src)
void EVP_PKEY_meth_free (EVP_PKEY_METHOD *pmeth)
int EVP_PKEY_meth_add0 (const EVP_PKEY_METHOD *pmeth)
EVP_PKEY_CTX * EVP_PKEY_CTX_new (EVP_PKEY *pkey, ENGINE *e)
EVP_PKEY_CTX * EVP_PKEY_CTX_new_id (int id, ENGINE *e)
EVP_PKEY_CTX * EVP_PKEY_CTX_dup (EVP_PKEY_CTX *ctx)
void EVP_PKEY_CTX_free (EVP_PKEY_CTX *ctx)
int EVP_PKEY_CTX_ctrl (EVP_PKEY_CTX *ctx, int keytype, int optype, int cmd, int p1, void *p2)
int EVP_PKEY_CTX_ctrl_str (EVP_PKEY_CTX *ctx, const char *type, const char *value)
int EVP_PKEY_CTX_str2ctrl (EVP_PKEY_CTX *ctx, int cmd, const char *str)
int EVP_PKEY_CTX_hex2ctrl (EVP_PKEY_CTX *ctx, int cmd, const char *hex)
int EVP_PKEY_CTX_md (EVP_PKEY_CTX *ctx, int optype, int cmd, const char *md)
int EVP_PKEY_CTX_get_operation (EVP_PKEY_CTX *ctx)
void EVP_PKEY_CTX_set0_keygen_info (EVP_PKEY_CTX *ctx, int *dat, int datlen)
EVP_PKEY * EVP_PKEY_new_mac_key (int type, ENGINE *e, const unsigned char *key, int keylen)
void EVP_PKEY_CTX_set_data (EVP_PKEY_CTX *ctx, void *data)
void * EVP_PKEY_CTX_get_data (EVP_PKEY_CTX *ctx)
EVP_PKEY * EVP_PKEY_CTX_get0_pkey (EVP_PKEY_CTX *ctx)
EVP_PKEY * EVP_PKEY_CTX_get0_peerkey (EVP_PKEY_CTX *ctx)
void EVP_PKEY_CTX_set_app_data (EVP_PKEY_CTX *ctx, void *data)
void * EVP_PKEY_CTX_get_app_data (EVP_PKEY_CTX *ctx)
int EVP_PKEY_sign_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_sign (EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen)
int EVP_PKEY_verify_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_verify (EVP_PKEY_CTX *ctx, const unsigned char *sig, size_t siglen, const unsigned char *tbs, size_t tbslen)
int EVP_PKEY_verify_recover_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_verify_recover (EVP_PKEY_CTX *ctx, unsigned char *rout, size_t *routlen, const unsigned char *sig, size_t siglen)
int EVP_PKEY_encrypt_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_encrypt (EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen)
int EVP_PKEY_decrypt_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_decrypt (EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen)
int EVP_PKEY_derive_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_derive_set_peer (EVP_PKEY_CTX *ctx, EVP_PKEY *peer)
int EVP_PKEY_derive (EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen)
int EVP_PKEY_paramgen_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_paramgen (EVP_PKEY_CTX *ctx, EVP_PKEY **ppkey)
int EVP_PKEY_keygen_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_keygen (EVP_PKEY_CTX *ctx, EVP_PKEY **ppkey)
void EVP_PKEY_CTX_set_cb (EVP_PKEY_CTX *ctx, EVP_PKEY_gen_cb *cb)
EVP_PKEY_gen_cb * EVP_PKEY_CTX_get_cb (EVP_PKEY_CTX *ctx)
int EVP_PKEY_CTX_get_keygen_info (EVP_PKEY_CTX *ctx, int idx)
void EVP_PKEY_meth_set_init (EVP_PKEY_METHOD *pmeth, int(*init)(EVP_PKEY_CTX *ctx))
void EVP_PKEY_meth_set_copy (EVP_PKEY_METHOD *pmeth, int(*copy)(EVP_PKEY_CTX *dst, EVP_PKEY_CTX *src))
void EVP_PKEY_meth_set_cleanup (EVP_PKEY_METHOD *pmeth, void(*cleanup)(EVP_PKEY_CTX *ctx))
void EVP_PKEY_meth_set_paramgen (EVP_PKEY_METHOD *pmeth, int(*paramgen_init)(EVP_PKEY_CTX *ctx), int(*paramgen)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey))
void EVP_PKEY_meth_set_keygen (EVP_PKEY_METHOD *pmeth, int(*keygen_init)(EVP_PKEY_CTX *ctx), int(*keygen)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey))
void EVP_PKEY_meth_set_sign (EVP_PKEY_METHOD *pmeth, int(*sign_init)(EVP_PKEY_CTX *ctx), int(*sign)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen))
void EVP_PKEY_meth_set_verify (EVP_PKEY_METHOD *pmeth, int(*verify_init)(EVP_PKEY_CTX *ctx), int(*verify)(EVP_PKEY_CTX *ctx, const unsigned char *sig, size_t siglen, const unsigned char *tbs, size_t tbslen))
void EVP_PKEY_meth_set_verify_recover (EVP_PKEY_METHOD *pmeth, int(*verify_recover_init)(EVP_PKEY_CTX *ctx), int(*verify_recover)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen))
void EVP_PKEY_meth_set_signctx (EVP_PKEY_METHOD *pmeth, int(*signctx_init)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx), int(*signctx)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, EVP_MD_CTX *mctx))
void EVP_PKEY_meth_set_verifyctx (EVP_PKEY_METHOD *pmeth, int(*verifyctx_init)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx), int(*verifyctx)(EVP_PKEY_CTX *ctx, const unsigned char *sig, int siglen, EVP_MD_CTX *mctx))
void EVP_PKEY_meth_set_encrypt (EVP_PKEY_METHOD *pmeth, int(*encrypt_init)(EVP_PKEY_CTX *ctx), int(*encryptfn)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen))
void EVP_PKEY_meth_set_decrypt (EVP_PKEY_METHOD *pmeth, int(*decrypt_init)(EVP_PKEY_CTX *ctx), int(*decrypt)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen))
void EVP_PKEY_meth_set_derive (EVP_PKEY_METHOD *pmeth, int(*derive_init)(EVP_PKEY_CTX *ctx), int(*derive)(EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen))
void EVP_PKEY_meth_set_ctrl (EVP_PKEY_METHOD *pmeth, int(*ctrl)(EVP_PKEY_CTX *ctx, int type, int p1, void *p2), int(*ctrl_str)(EVP_PKEY_CTX *ctx, const char *type, const char *value))
void EVP_PKEY_meth_get_init (EVP_PKEY_METHOD *pmeth, int(**pinit)(EVP_PKEY_CTX *ctx))
void EVP_PKEY_meth_get_copy (EVP_PKEY_METHOD *pmeth, int(**pcopy)(EVP_PKEY_CTX *dst, EVP_PKEY_CTX *src))
void EVP_PKEY_meth_get_cleanup (EVP_PKEY_METHOD *pmeth, void(**pcleanup)(EVP_PKEY_CTX *ctx))
void EVP_PKEY_meth_get_paramgen (EVP_PKEY_METHOD *pmeth, int(**pparamgen_init)(EVP_PKEY_CTX *ctx), int(**pparamgen)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey))
void EVP_PKEY_meth_get_keygen (EVP_PKEY_METHOD *pmeth, int(**pkeygen_init)(EVP_PKEY_CTX *ctx), int(**pkeygen)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey))
void EVP_PKEY_meth_get_sign (EVP_PKEY_METHOD *pmeth, int(**psign_init)(EVP_PKEY_CTX *ctx), int(**psign)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen))
void EVP_PKEY_meth_get_verify (EVP_PKEY_METHOD *pmeth, int(**pverify_init)(EVP_PKEY_CTX *ctx), int(**pverify)(EVP_PKEY_CTX *ctx, const unsigned char *sig, size_t siglen, const unsigned char *tbs, size_t tbslen))
void EVP_PKEY_meth_get_verify_recover (EVP_PKEY_METHOD *pmeth, int(**pverify_recover_init)(EVP_PKEY_CTX *ctx), int(**pverify_recover)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen))
void EVP_PKEY_meth_get_signctx (EVP_PKEY_METHOD *pmeth, int(**psignctx_init)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx), int(**psignctx)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, EVP_MD_CTX *mctx))
void EVP_PKEY_meth_get_verifyctx (EVP_PKEY_METHOD *pmeth, int(**pverifyctx_init)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx), int(**pverifyctx)(EVP_PKEY_CTX *ctx, const unsigned char *sig, int siglen, EVP_MD_CTX *mctx))
void EVP_PKEY_meth_get_encrypt (EVP_PKEY_METHOD *pmeth, int(**pencrypt_init)(EVP_PKEY_CTX *ctx), int(**pencryptfn)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen))
void EVP_PKEY_meth_get_decrypt (EVP_PKEY_METHOD *pmeth, int(**pdecrypt_init)(EVP_PKEY_CTX *ctx), int(**pdecrypt)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen))
void EVP_PKEY_meth_get_derive (EVP_PKEY_METHOD *pmeth, int(**pderive_init)(EVP_PKEY_CTX *ctx), int(**pderive)(EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen))
void EVP_PKEY_meth_get_ctrl (EVP_PKEY_METHOD *pmeth, int(**pctrl)(EVP_PKEY_CTX *ctx, int type, int p1, void *p2), int(**pctrl_str)(EVP_PKEY_CTX *ctx, const char *type, const char *value))
void EVP_add_alg_module (void)
int ERR_load_EVP_strings (void)
Variables
int(*)(EVP_MD_CTX *ctx) EVP_MD_meth_get_init (const EVP_MD *md)
int(*)(EVP_MD_CTX *ctx, const void *data, size_t count) EVP_MD_meth_get_update (const EVP_MD *md)
int(*)(EVP_MD_CTX *ctx, unsigned char *md) EVP_MD_meth_get_final (const EVP_MD *md)
int(*)(EVP_MD_CTX *to, const EVP_MD_CTX *from) EVP_MD_meth_get_copy (const EVP_MD *md)
int(*)(EVP_MD_CTX *ctx) EVP_MD_meth_get_cleanup (const EVP_MD *md)
int(*)(EVP_MD_CTX *ctx, int cmd, int p1, void *p2) EVP_MD_meth_get_ctrl (const EVP_MD *md)
int(*)(EVP_CIPHER_CTX *ctx, const unsigned char *key, const unsigned char *iv, int enc) EVP_CIPHER_meth_get_init (const EVP_CIPHER *cipher)
int(*)(EVP_CIPHER_CTX *ctx, unsigned char *out, const unsigned char *in, size_t inl) EVP_CIPHER_meth_get_do_cipher (const EVP_CIPHER *cipher)
int(*)(EVP_CIPHER_CTX *) EVP_CIPHER_meth_get_cleanup (const EVP_CIPHER *cipher)
int(*)(EVP_CIPHER_CTX *, ASN1_TYPE *) EVP_CIPHER_meth_get_set_asn1_params (const EVP_CIPHER *cipher)
int(*)(EVP_CIPHER_CTX *, ASN1_TYPE *) EVP_CIPHER_meth_get_get_asn1_params (const EVP_CIPHER *cipher)
int(*)(EVP_CIPHER_CTX *, int type, int arg, void *ptr) EVP_CIPHER_meth_get_ctrl (const EVP_CIPHER *cipher)
int(*)(EVP_MD_CTX *ctx, const void *data, size_t count) EVP_MD_CTX_update_fn (EVP_MD_CTX *ctx)
Macro Definition Documentation
ASN1_PKEY_ALIAS
#define ASN1_PKEY_ALIAS 0x1
Definition at line 1051 of file evp.h.
Referenced by EVP_PKEY_asn1_add_alias(), and EVP_PKEY_asn1_find_str().
ASN1_PKEY_CTRL_CMS_ENVELOPE
#define ASN1_PKEY_CTRL_CMS_ENVELOPE 0x7
Definition at line 1059 of file evp.h.
ASN1_PKEY_CTRL_CMS_RI_TYPE
#define ASN1_PKEY_CTRL_CMS_RI_TYPE 0x8
Definition at line 1060 of file evp.h.
Referenced by cms_pkey_get_ri_type().
ASN1_PKEY_CTRL_CMS_SIGN
#define ASN1_PKEY_CTRL_CMS_SIGN 0x5
Definition at line 1058 of file evp.h.
ASN1_PKEY_CTRL_DEFAULT_MD_NID
#define ASN1_PKEY_CTRL_DEFAULT_MD_NID 0x3
Definition at line 1057 of file evp.h.
ASN1_PKEY_CTRL_GET1_TLS_ENCPT
#define ASN1_PKEY_CTRL_GET1_TLS_ENCPT 0xa
Definition at line 1063 of file evp.h.
ASN1_PKEY_CTRL_PKCS7_ENCRYPT
#define ASN1_PKEY_CTRL_PKCS7_ENCRYPT 0x2
Definition at line 1056 of file evp.h.
ASN1_PKEY_CTRL_PKCS7_SIGN
#define ASN1_PKEY_CTRL_PKCS7_SIGN 0x1
Definition at line 1055 of file evp.h.
ASN1_PKEY_CTRL_SET1_TLS_ENCPT
#define ASN1_PKEY_CTRL_SET1_TLS_ENCPT 0x9
Definition at line 1062 of file evp.h.
ASN1_PKEY_DYNAMIC
#define ASN1_PKEY_DYNAMIC 0x2
Definition at line 1052 of file evp.h.
Referenced by EVP_PKEY_asn1_free(), and EVP_PKEY_asn1_new().
ASN1_PKEY_SIGPARAM_NULL
#define ASN1_PKEY_SIGPARAM_NULL 0x4
Definition at line 1053 of file evp.h.
Referenced by ASN1_item_sign_ctx().
BIO_get_cipher_ctx
#define BIO_get_cipher_ctx (b, c_pp) BIO_ctrl(b,BIO_C_GET_CIPHER_CTX,0,(char *)c_pp)
Definition at line 502 of file evp.h.
BIO_get_cipher_status
#define BIO_get_cipher_status (b) BIO_ctrl(b,BIO_C_GET_CIPHER_STATUS,0,NULL)
Definition at line 501 of file evp.h.
BIO_get_md
#define BIO_get_md (b, mdp) BIO_ctrl(b,BIO_C_GET_MD,0,(char *)mdp)
Definition at line 498 of file evp.h.
BIO_get_md_ctx
#define BIO_get_md_ctx (b, mdcp) BIO_ctrl(b,BIO_C_GET_MD_CTX,0,(char *)mdcp)
Definition at line 499 of file evp.h.
Referenced by cms_DigestAlgorithm_find_ctx(), and PKCS7_signatureVerify().
BIO_set_md
#define BIO_set_md (b, md) BIO_ctrl(b,BIO_C_SET_MD,0,(char *)md)
Definition at line 496 of file evp.h.
Referenced by cms_DigestAlgorithm_init_bio().
BIO_set_md_ctx
#define BIO_set_md_ctx (b, mdcp) BIO_ctrl(b,BIO_C_SET_MD_CTX,0,(char *)mdcp)
Definition at line 500 of file evp.h.
EVP_add_cipher_alias
#define EVP_add_cipher_alias (n, alias) OBJ_NAME_add((alias),OBJ_NAME_TYPE_CIPHER_METH|OBJ_NAME_ALIAS,(n))
Definition at line 508 of file evp.h.
Referenced by openssl_add_all_ciphers_int().
EVP_add_digest_alias
#define EVP_add_digest_alias (n, alias) OBJ_NAME_add((alias),OBJ_NAME_TYPE_MD_METH|OBJ_NAME_ALIAS,(n))
Definition at line 510 of file evp.h.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_digests_int().
EVP_AEAD_TLS1_AAD_LEN
#define EVP_AEAD_TLS1_AAD_LEN 13
Definition at line 348 of file evp.h.
Referenced by BLOCK_CIPHER_custom().
EVP_aes_128_cfb
#define EVP_aes_128_cfb EVP_aes_128_cfb128
Definition at line 775 of file evp.h.
EVP_aes_192_cfb
#define EVP_aes_192_cfb EVP_aes_192_cfb128
Definition at line 791 of file evp.h.
EVP_aes_256_cfb
#define EVP_aes_256_cfb EVP_aes_256_cfb128
Definition at line 806 of file evp.h.
EVP_bf_cfb
#define EVP_bf_cfb EVP_bf_cfb64
Definition at line 753 of file evp.h.
EVP_camellia_128_cfb
#define EVP_camellia_128_cfb EVP_camellia_128_cfb128
Definition at line 827 of file evp.h.
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_192_cfb
#define EVP_camellia_192_cfb EVP_camellia_192_cfb128
Definition at line 835 of file evp.h.
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_256_cfb
#define EVP_camellia_256_cfb EVP_camellia_256_cfb128
Definition at line 843 of file evp.h.
Referenced by openssl_add_all_ciphers_int().
EVP_cast5_cfb
#define EVP_cast5_cfb EVP_cast5_cfb64
Definition at line 760 of file evp.h.
EVP_CCM8_TLS_TAG_LEN
#define EVP_CCM8_TLS_TAG_LEN 8
Definition at line 375 of file evp.h.
EVP_CCM_TLS_EXPLICIT_IV_LEN
#define EVP_CCM_TLS_EXPLICIT_IV_LEN 8
Definition at line 369 of file evp.h.
Referenced by BLOCK_CIPHER_custom().
EVP_CCM_TLS_FIXED_IV_LEN
#define EVP_CCM_TLS_FIXED_IV_LEN 4
Definition at line 367 of file evp.h.
Referenced by BLOCK_CIPHER_custom().
EVP_CCM_TLS_IV_LEN
#define EVP_CCM_TLS_IV_LEN 12
Definition at line 371 of file evp.h.
EVP_CCM_TLS_TAG_LEN
#define EVP_CCM_TLS_TAG_LEN 16
Definition at line 373 of file evp.h.
EVP_CHACHAPOLY_TLS_TAG_LEN
#define EVP_CHACHAPOLY_TLS_TAG_LEN 16
Definition at line 378 of file evp.h.
EVP_CIPH_ALWAYS_CALL_INIT
#define EVP_CIPH_ALWAYS_CALL_INIT 0x20
Definition at line 240 of file evp.h.
EVP_CIPH_CBC_MODE
#define EVP_CIPH_CBC_MODE 0x2
Definition at line 225 of file evp.h.
EVP_CIPH_CCM_MODE
#define EVP_CIPH_CCM_MODE 0x7
Definition at line 230 of file evp.h.
EVP_CIPH_CFB_MODE
#define EVP_CIPH_CFB_MODE 0x3
Definition at line 226 of file evp.h.
EVP_CIPH_CTR_MODE
#define EVP_CIPH_CTR_MODE 0x5
Definition at line 228 of file evp.h.
EVP_CIPH_CTRL_INIT
#define EVP_CIPH_CTRL_INIT 0x40
Definition at line 242 of file evp.h.
EVP_CIPH_CUSTOM_COPY
#define EVP_CIPH_CUSTOM_COPY 0x400
Definition at line 250 of file evp.h.
EVP_CIPH_CUSTOM_IV
#define EVP_CIPH_CUSTOM_IV 0x10
Definition at line 238 of file evp.h.
EVP_CIPH_CUSTOM_KEY_LENGTH
#define EVP_CIPH_CUSTOM_KEY_LENGTH 0x80
Definition at line 244 of file evp.h.
EVP_CIPH_ECB_MODE
#define EVP_CIPH_ECB_MODE 0x1
Definition at line 224 of file evp.h.
EVP_CIPH_FLAG_AEAD_CIPHER
#define EVP_CIPH_FLAG_AEAD_CIPHER 0x200000
Definition at line 263 of file evp.h.
Referenced by tls1_cbc_remove_padding().
EVP_CIPH_FLAG_CUSTOM_CIPHER
#define EVP_CIPH_FLAG_CUSTOM_CIPHER 0x100000
Definition at line 262 of file evp.h.
EVP_CIPH_FLAG_DEFAULT_ASN1
EVP_CIPH_RAND_KEY des3_ctrl EVP_CIPH_RAND_KEY EVP_CIPH_FLAG_DEFAULT_ASN1 0x1000
Definition at line 252 of file evp.h.
EVP_CIPH_FLAG_FIPS
#define EVP_CIPH_FLAG_FIPS 0x4000
Definition at line 256 of file evp.h.
EVP_CIPH_FLAG_LENGTH_BITS
#define EVP_CIPH_FLAG_LENGTH_BITS 0x2000
Definition at line 254 of file evp.h.
EVP_CIPH_FLAG_NON_FIPS_ALLOW
#define EVP_CIPH_FLAG_NON_FIPS_ALLOW 0x8000
Definition at line 258 of file evp.h.
EVP_CIPH_FLAG_PIPELINE
#define EVP_CIPH_FLAG_PIPELINE 0X800000
Definition at line 266 of file evp.h.
EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK
#define EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK 0x400000
Definition at line 264 of file evp.h.
EVP_CIPH_GCM_MODE
#define EVP_CIPH_GCM_MODE 0x6
Definition at line 229 of file evp.h.
EVP_CIPH_MODE
#define EVP_CIPH_MODE 0xF0007
Definition at line 234 of file evp.h.
EVP_CIPH_NO_PADDING
#define EVP_CIPH_NO_PADDING 0x100
Definition at line 246 of file evp.h.
Referenced by EVP_CIPHER_CTX_set_padding().
EVP_CIPH_OCB_MODE
#define EVP_CIPH_OCB_MODE 0x10003
Definition at line 233 of file evp.h.
EVP_CIPH_OFB_MODE
#define EVP_CIPH_OFB_MODE 0x4
Definition at line 227 of file evp.h.
EVP_CIPH_RAND_KEY
#define EVP_CIPH_RAND_KEY 0x200
Definition at line 248 of file evp.h.
Referenced by EVP_CIPHER_CTX_rand_key().
EVP_CIPH_STREAM_CIPHER
#define EVP_CIPH_STREAM_CIPHER 0x0
Definition at line 223 of file evp.h.
EVP_CIPH_VARIABLE_LENGTH
#define EVP_CIPH_VARIABLE_LENGTH 0x8
Definition at line 236 of file evp.h.
EVP_CIPH_WRAP_MODE
#define EVP_CIPH_WRAP_MODE 0x10002
Definition at line 232 of file evp.h.
EVP_CIPH_XTS_MODE
#define EVP_CIPH_XTS_MODE 0x10001
Definition at line 231 of file evp.h.
EVP_CIPHER_CTX_cleanup
#define EVP_CIPHER_CTX_cleanup (c) EVP_CIPHER_CTX_reset(c)
Definition at line 649 of file evp.h.
EVP_CIPHER_CTX_FLAG_WRAP_ALLOW
#define EVP_CIPHER_CTX_FLAG_WRAP_ALLOW 0x1
Definition at line 273 of file evp.h.
EVP_CIPHER_CTX_flags
#define EVP_CIPHER_CTX_flags (c) EVP_CIPHER_flags(EVP_CIPHER_CTX_cipher(c))
Definition at line 475 of file evp.h.
EVP_CIPHER_CTX_init
#define EVP_CIPHER_CTX_init (c) EVP_CIPHER_CTX_reset(c)
Definition at line 648 of file evp.h.
EVP_CIPHER_CTX_mode
#define EVP_CIPHER_CTX_mode (c) EVP_CIPHER_mode(EVP_CIPHER_CTX_cipher(c))
Definition at line 477 of file evp.h.
EVP_CIPHER_CTX_type
#define EVP_CIPHER_CTX_type (c) EVP_CIPHER_type(EVP_CIPHER_CTX_cipher(c))
Definition at line 473 of file evp.h.
EVP_CIPHER_mode
#define EVP_CIPHER_mode (e) (EVP_CIPHER_flags(e) & EVP_CIPH_MODE)
Definition at line 454 of file evp.h.
EVP_CIPHER_name
#define EVP_CIPHER_name (e) OBJ_nid2sn(EVP_CIPHER_nid(e))
Definition at line 448 of file evp.h.
EVP_cleanup
#define EVP_cleanup () while(0) continue
Definition at line 887 of file evp.h.
EVP_CTRL_AEAD_GET_TAG
#define EVP_CTRL_AEAD_GET_TAG 0x10
Definition at line 287 of file evp.h.
Referenced by BLOCK_CIPHER_custom().
EVP_CTRL_AEAD_SET_IV_FIXED
#define EVP_CTRL_AEAD_SET_IV_FIXED 0x12
Definition at line 289 of file evp.h.
EVP_CTRL_AEAD_SET_IVLEN
#define EVP_CTRL_AEAD_SET_IVLEN 0x9
Definition at line 286 of file evp.h.
Referenced by BLOCK_CIPHER_custom().
EVP_CTRL_AEAD_SET_MAC_KEY
#define EVP_CTRL_AEAD_SET_MAC_KEY 0x17
Definition at line 308 of file evp.h.
EVP_CTRL_AEAD_SET_TAG
#define EVP_CTRL_AEAD_SET_TAG 0x11
Definition at line 288 of file evp.h.
Referenced by BLOCK_CIPHER_custom().
EVP_CTRL_AEAD_TLS1_AAD
#define EVP_CTRL_AEAD_TLS1_AAD 0x16
Definition at line 306 of file evp.h.
Referenced by BLOCK_CIPHER_custom().
EVP_CTRL_BLOCK_PADDING_MODE
#define EVP_CTRL_BLOCK_PADDING_MODE 0x21
Definition at line 331 of file evp.h.
EVP_CTRL_CCM_GET_TAG
#define EVP_CTRL_CCM_GET_TAG EVP_CTRL_AEAD_GET_TAG
Definition at line 296 of file evp.h.
EVP_CTRL_CCM_SET_IV_FIXED
#define EVP_CTRL_CCM_SET_IV_FIXED EVP_CTRL_AEAD_SET_IV_FIXED
Definition at line 298 of file evp.h.
Referenced by BLOCK_CIPHER_custom().
EVP_CTRL_CCM_SET_IVLEN
#define EVP_CTRL_CCM_SET_IVLEN EVP_CTRL_AEAD_SET_IVLEN
Definition at line 295 of file evp.h.
EVP_CTRL_CCM_SET_L
#define EVP_CTRL_CCM_SET_L 0x14
Definition at line 299 of file evp.h.
Referenced by BLOCK_CIPHER_custom().
EVP_CTRL_CCM_SET_MSGLEN
#define EVP_CTRL_CCM_SET_MSGLEN 0x15
Definition at line 300 of file evp.h.
EVP_CTRL_CCM_SET_TAG
#define EVP_CTRL_CCM_SET_TAG EVP_CTRL_AEAD_SET_TAG
Definition at line 297 of file evp.h.
EVP_CTRL_COPY
#define EVP_CTRL_COPY 0x8
Definition at line 285 of file evp.h.
Referenced by BLOCK_CIPHER_custom().
EVP_CTRL_GCM_GET_TAG
#define EVP_CTRL_GCM_GET_TAG EVP_CTRL_AEAD_GET_TAG
Definition at line 291 of file evp.h.
EVP_CTRL_GCM_IV_GEN
#define EVP_CTRL_GCM_IV_GEN 0x13
Definition at line 294 of file evp.h.
EVP_CTRL_GCM_SET_IV_FIXED
#define EVP_CTRL_GCM_SET_IV_FIXED EVP_CTRL_AEAD_SET_IV_FIXED
Definition at line 293 of file evp.h.
EVP_CTRL_GCM_SET_IV_INV
#define EVP_CTRL_GCM_SET_IV_INV 0x18
Definition at line 310 of file evp.h.
EVP_CTRL_GCM_SET_IVLEN
#define EVP_CTRL_GCM_SET_IVLEN EVP_CTRL_AEAD_SET_IVLEN
Definition at line 290 of file evp.h.
EVP_CTRL_GCM_SET_TAG
#define EVP_CTRL_GCM_SET_TAG EVP_CTRL_AEAD_SET_TAG
Definition at line 292 of file evp.h.
EVP_CTRL_GET_RC2_KEY_BITS
#define EVP_CTRL_GET_RC2_KEY_BITS 0x2
Definition at line 279 of file evp.h.
EVP_CTRL_GET_RC5_ROUNDS
#define EVP_CTRL_GET_RC5_ROUNDS 0x4
Definition at line 281 of file evp.h.
EVP_CTRL_INIT
#define EVP_CTRL_INIT 0x0
Definition at line 277 of file evp.h.
Referenced by BLOCK_CIPHER_custom().
EVP_CTRL_KEY_MESH
#define EVP_CTRL_KEY_MESH 0x20
Definition at line 329 of file evp.h.
EVP_CTRL_PBE_PRF_NID
#define EVP_CTRL_PBE_PRF_NID 0x7
Definition at line 284 of file evp.h.
EVP_CTRL_RAND_KEY
#define EVP_CTRL_RAND_KEY 0x6
Definition at line 283 of file evp.h.
Referenced by EVP_CIPHER_CTX_rand_key().
EVP_CTRL_SBOX_USED
#define EVP_CTRL_SBOX_USED 0x1f
Definition at line 325 of file evp.h.
EVP_CTRL_SET_KEY_LENGTH
#define EVP_CTRL_SET_KEY_LENGTH 0x1
Definition at line 278 of file evp.h.
EVP_CTRL_SET_PIPELINE_INPUT_BUFS
#define EVP_CTRL_SET_PIPELINE_INPUT_BUFS 0x23
Definition at line 336 of file evp.h.
EVP_CTRL_SET_PIPELINE_INPUT_LENS
#define EVP_CTRL_SET_PIPELINE_INPUT_LENS 0x24
Definition at line 338 of file evp.h.
EVP_CTRL_SET_PIPELINE_OUTPUT_BUFS
#define EVP_CTRL_SET_PIPELINE_OUTPUT_BUFS 0x22
Definition at line 334 of file evp.h.
EVP_CTRL_SET_RC2_KEY_BITS
#define EVP_CTRL_SET_RC2_KEY_BITS 0x3
Definition at line 280 of file evp.h.
EVP_CTRL_SET_RC5_ROUNDS
#define EVP_CTRL_SET_RC5_ROUNDS 0x5
Definition at line 282 of file evp.h.
EVP_CTRL_SET_SBOX
#define EVP_CTRL_SET_SBOX 0x1e
Definition at line 320 of file evp.h.
EVP_CTRL_SSL3_MASTER_SECRET
#define EVP_CTRL_SSL3_MASTER_SECRET 0x1d
Definition at line 317 of file evp.h.
EVP_CTRL_TLS1_1_MULTIBLOCK_AAD
#define EVP_CTRL_TLS1_1_MULTIBLOCK_AAD 0x19
Definition at line 312 of file evp.h.
EVP_CTRL_TLS1_1_MULTIBLOCK_DECRYPT
#define EVP_CTRL_TLS1_1_MULTIBLOCK_DECRYPT 0x1b
Definition at line 314 of file evp.h.
EVP_CTRL_TLS1_1_MULTIBLOCK_ENCRYPT
#define EVP_CTRL_TLS1_1_MULTIBLOCK_ENCRYPT 0x1a
Definition at line 313 of file evp.h.
EVP_CTRL_TLS1_1_MULTIBLOCK_MAX_BUFSIZE
#define EVP_CTRL_TLS1_1_MULTIBLOCK_MAX_BUFSIZE 0x1c
Definition at line 315 of file evp.h.
EVP_DECODE_LENGTH
#define EVP_DECODE_LENGTH (l) ((l+3)/4*3+80)
Definition at line 480 of file evp.h.
EVP_delete_cipher_alias
#define EVP_delete_cipher_alias (alias) OBJ_NAME_remove(alias,OBJ_NAME_TYPE_CIPHER_METH|OBJ_NAME_ALIAS);
Definition at line 512 of file evp.h.
EVP_delete_digest_alias
#define EVP_delete_digest_alias (alias) OBJ_NAME_remove(alias,OBJ_NAME_TYPE_MD_METH|OBJ_NAME_ALIAS);
Definition at line 514 of file evp.h.
EVP_des_cfb
#define EVP_des_cfb EVP_des_cfb64
Definition at line 703 of file evp.h.
EVP_des_ede3_cfb
#define EVP_des_ede3_cfb EVP_des_ede3_cfb64
Definition at line 709 of file evp.h.
EVP_des_ede_cfb
#define EVP_des_ede_cfb EVP_des_ede_cfb64
Definition at line 707 of file evp.h.
EVP_DigestSignUpdate
#define EVP_DigestSignUpdate (a, b, c) EVP_DigestUpdate(a,b,c)
Definition at line 490 of file evp.h.
Referenced by ASN1_item_sign_ctx().
EVP_DigestVerifyUpdate
#define EVP_DigestVerifyUpdate (a, b, c) EVP_DigestUpdate(a,b,c)
Definition at line 491 of file evp.h.
EVP_ENCODE_LENGTH
#define EVP_ENCODE_LENGTH (l) (((l+2)/3*4)+(l/48+1)*2+80)
Definition at line 479 of file evp.h.
EVP_F_AES_INIT_KEY
#define EVP_F_AES_INIT_KEY 133
Definition at line 1488 of file evp.h.
EVP_F_AES_OCB_CIPHER
#define EVP_F_AES_OCB_CIPHER 169
Definition at line 1489 of file evp.h.
EVP_F_AES_T4_INIT_KEY
#define EVP_F_AES_T4_INIT_KEY 178
Definition at line 1490 of file evp.h.
EVP_F_AES_WRAP_CIPHER
#define EVP_F_AES_WRAP_CIPHER 170
Definition at line 1491 of file evp.h.
EVP_F_AESNI_INIT_KEY
#define EVP_F_AESNI_INIT_KEY 165
Definition at line 1487 of file evp.h.
EVP_F_ALG_MODULE_INIT
#define EVP_F_ALG_MODULE_INIT 177
Definition at line 1492 of file evp.h.
EVP_F_CAMELLIA_INIT_KEY
#define EVP_F_CAMELLIA_INIT_KEY 159
Definition at line 1493 of file evp.h.
EVP_F_CHACHA20_POLY1305_CTRL
#define EVP_F_CHACHA20_POLY1305_CTRL 182
Definition at line 1494 of file evp.h.
EVP_F_CMLL_T4_INIT_KEY
#define EVP_F_CMLL_T4_INIT_KEY 179
Definition at line 1495 of file evp.h.
EVP_F_DES_EDE3_WRAP_CIPHER
#define EVP_F_DES_EDE3_WRAP_CIPHER 171
Definition at line 1496 of file evp.h.
EVP_F_DO_SIGVER_INIT
#define EVP_F_DO_SIGVER_INIT 161
Definition at line 1497 of file evp.h.
EVP_F_EVP_CIPHER_CTX_COPY
#define EVP_F_EVP_CIPHER_CTX_COPY 163
Definition at line 1499 of file evp.h.
EVP_F_EVP_CIPHER_CTX_CTRL
#define EVP_F_EVP_CIPHER_CTX_CTRL 124
Definition at line 1500 of file evp.h.
EVP_F_EVP_CIPHER_CTX_SET_KEY_LENGTH
#define EVP_F_EVP_CIPHER_CTX_SET_KEY_LENGTH 122
Definition at line 1501 of file evp.h.
EVP_F_EVP_CIPHERINIT_EX
#define EVP_F_EVP_CIPHERINIT_EX 123
Definition at line 1498 of file evp.h.
EVP_F_EVP_DECRYPTFINAL_EX
#define EVP_F_EVP_DECRYPTFINAL_EX 101
Definition at line 1502 of file evp.h.
EVP_F_EVP_DECRYPTUPDATE
#define EVP_F_EVP_DECRYPTUPDATE 166
Definition at line 1503 of file evp.h.
EVP_F_EVP_DIGESTINIT_EX
#define EVP_F_EVP_DIGESTINIT_EX 128
Definition at line 1504 of file evp.h.
Referenced by EVP_DigestInit_ex().
EVP_F_EVP_ENCRYPTFINAL_EX
#define EVP_F_EVP_ENCRYPTFINAL_EX 127
Definition at line 1505 of file evp.h.
EVP_F_EVP_ENCRYPTUPDATE
#define EVP_F_EVP_ENCRYPTUPDATE 167
Definition at line 1506 of file evp.h.
EVP_F_EVP_MD_CTX_COPY_EX
#define EVP_F_EVP_MD_CTX_COPY_EX 110
Definition at line 1507 of file evp.h.
EVP_F_EVP_MD_SIZE
#define EVP_F_EVP_MD_SIZE 162
Definition at line 1508 of file evp.h.
EVP_F_EVP_OPENINIT
#define EVP_F_EVP_OPENINIT 102
Definition at line 1509 of file evp.h.
EVP_F_EVP_PBE_ALG_ADD
#define EVP_F_EVP_PBE_ALG_ADD 115
Definition at line 1510 of file evp.h.
EVP_F_EVP_PBE_ALG_ADD_TYPE
#define EVP_F_EVP_PBE_ALG_ADD_TYPE 160
Definition at line 1511 of file evp.h.
EVP_F_EVP_PBE_CIPHERINIT
#define EVP_F_EVP_PBE_CIPHERINIT 116
Definition at line 1512 of file evp.h.
EVP_F_EVP_PBE_SCRYPT
#define EVP_F_EVP_PBE_SCRYPT 181
Definition at line 1513 of file evp.h.
Referenced by EVP_PBE_scrypt().
EVP_F_EVP_PKCS82PKEY
#define EVP_F_EVP_PKCS82PKEY 111
Definition at line 1514 of file evp.h.
Referenced by EVP_PKCS82PKEY().
EVP_F_EVP_PKEY2PKCS8
#define EVP_F_EVP_PKEY2PKCS8 113
Definition at line 1515 of file evp.h.
Referenced by EVP_PKEY2PKCS8().
EVP_F_EVP_PKEY_COPY_PARAMETERS
#define EVP_F_EVP_PKEY_COPY_PARAMETERS 103
Definition at line 1516 of file evp.h.
Referenced by EVP_PKEY_copy_parameters().
EVP_F_EVP_PKEY_CTX_CTRL
#define EVP_F_EVP_PKEY_CTX_CTRL 137
Definition at line 1517 of file evp.h.
EVP_F_EVP_PKEY_CTX_CTRL_STR
#define EVP_F_EVP_PKEY_CTX_CTRL_STR 150
Definition at line 1518 of file evp.h.
Referenced by EVP_PKEY_CTX_ctrl_str().
EVP_F_EVP_PKEY_CTX_DUP
#define EVP_F_EVP_PKEY_CTX_DUP 156
Definition at line 1519 of file evp.h.
EVP_F_EVP_PKEY_CTX_MD
#define EVP_F_EVP_PKEY_CTX_MD 168
Definition at line 1520 of file evp.h.
EVP_F_EVP_PKEY_DECRYPT
#define EVP_F_EVP_PKEY_DECRYPT 104
Definition at line 1521 of file evp.h.
EVP_F_EVP_PKEY_DECRYPT_INIT
#define EVP_F_EVP_PKEY_DECRYPT_INIT 138
Definition at line 1522 of file evp.h.
EVP_F_EVP_PKEY_DECRYPT_OLD
#define EVP_F_EVP_PKEY_DECRYPT_OLD 151
Definition at line 1523 of file evp.h.
EVP_F_EVP_PKEY_DERIVE
#define EVP_F_EVP_PKEY_DERIVE 153
Definition at line 1524 of file evp.h.
Referenced by EVP_PKEY_derive().
EVP_F_EVP_PKEY_DERIVE_INIT
#define EVP_F_EVP_PKEY_DERIVE_INIT 154
Definition at line 1525 of file evp.h.
EVP_F_EVP_PKEY_DERIVE_SET_PEER
#define EVP_F_EVP_PKEY_DERIVE_SET_PEER 155
Definition at line 1526 of file evp.h.
EVP_F_EVP_PKEY_ENCRYPT
#define EVP_F_EVP_PKEY_ENCRYPT 105
Definition at line 1527 of file evp.h.
EVP_F_EVP_PKEY_ENCRYPT_INIT
#define EVP_F_EVP_PKEY_ENCRYPT_INIT 139
Definition at line 1528 of file evp.h.
EVP_F_EVP_PKEY_ENCRYPT_OLD
#define EVP_F_EVP_PKEY_ENCRYPT_OLD 152
Definition at line 1529 of file evp.h.
EVP_F_EVP_PKEY_GET0_DH
#define EVP_F_EVP_PKEY_GET0_DH 119
Definition at line 1530 of file evp.h.
Referenced by EVP_PKEY_get0_DH().
EVP_F_EVP_PKEY_GET0_DSA
#define EVP_F_EVP_PKEY_GET0_DSA 120
Definition at line 1531 of file evp.h.
Referenced by EVP_PKEY_get0_DSA().
EVP_F_EVP_PKEY_GET0_EC_KEY
#define EVP_F_EVP_PKEY_GET0_EC_KEY 131
Definition at line 1532 of file evp.h.
Referenced by EVP_PKEY_get0_EC_KEY().
EVP_F_EVP_PKEY_GET0_HMAC
#define EVP_F_EVP_PKEY_GET0_HMAC 183
Definition at line 1533 of file evp.h.
Referenced by EVP_PKEY_get0_hmac().
EVP_F_EVP_PKEY_GET0_POLY1305
#define EVP_F_EVP_PKEY_GET0_POLY1305 184
Definition at line 1534 of file evp.h.
Referenced by EVP_PKEY_get0_poly1305().
EVP_F_EVP_PKEY_GET0_RSA
#define EVP_F_EVP_PKEY_GET0_RSA 121
Definition at line 1535 of file evp.h.
Referenced by EVP_PKEY_get0_RSA().
EVP_F_EVP_PKEY_GET0_SIPHASH
#define EVP_F_EVP_PKEY_GET0_SIPHASH 172
Definition at line 1536 of file evp.h.
Referenced by EVP_PKEY_get0_siphash().
EVP_F_EVP_PKEY_KEYGEN
#define EVP_F_EVP_PKEY_KEYGEN 146
Definition at line 1537 of file evp.h.
EVP_F_EVP_PKEY_KEYGEN_INIT
#define EVP_F_EVP_PKEY_KEYGEN_INIT 147
Definition at line 1538 of file evp.h.
EVP_F_EVP_PKEY_NEW
#define EVP_F_EVP_PKEY_NEW 106
Definition at line 1539 of file evp.h.
EVP_F_EVP_PKEY_PARAMGEN
#define EVP_F_EVP_PKEY_PARAMGEN 148
Definition at line 1540 of file evp.h.
EVP_F_EVP_PKEY_PARAMGEN_INIT
#define EVP_F_EVP_PKEY_PARAMGEN_INIT 149
Definition at line 1541 of file evp.h.
EVP_F_EVP_PKEY_SIGN
#define EVP_F_EVP_PKEY_SIGN 140
Definition at line 1542 of file evp.h.
Referenced by EVP_PKEY_sign().
EVP_F_EVP_PKEY_SIGN_INIT
#define EVP_F_EVP_PKEY_SIGN_INIT 141
Definition at line 1543 of file evp.h.
EVP_F_EVP_PKEY_VERIFY
#define EVP_F_EVP_PKEY_VERIFY 142
Definition at line 1544 of file evp.h.
Referenced by EVP_PKEY_verify().
EVP_F_EVP_PKEY_VERIFY_INIT
#define EVP_F_EVP_PKEY_VERIFY_INIT 143
Definition at line 1545 of file evp.h.
EVP_F_EVP_PKEY_VERIFY_RECOVER
#define EVP_F_EVP_PKEY_VERIFY_RECOVER 144
Definition at line 1546 of file evp.h.
Referenced by EVP_PKEY_verify_recover().
EVP_F_EVP_PKEY_VERIFY_RECOVER_INIT
#define EVP_F_EVP_PKEY_VERIFY_RECOVER_INIT 145
Definition at line 1547 of file evp.h.
EVP_F_EVP_SIGNFINAL
#define EVP_F_EVP_SIGNFINAL 107
Definition at line 1548 of file evp.h.
Referenced by EVP_SignFinal().
EVP_F_EVP_VERIFYFINAL
#define EVP_F_EVP_VERIFYFINAL 108
Definition at line 1549 of file evp.h.
Referenced by EVP_VerifyFinal().
EVP_F_INT_CTX_NEW
#define EVP_F_INT_CTX_NEW 157
Definition at line 1550 of file evp.h.
EVP_F_PKCS5_PBE_KEYIVGEN
#define EVP_F_PKCS5_PBE_KEYIVGEN 117
Definition at line 1551 of file evp.h.
EVP_F_PKCS5_V2_PBE_KEYIVGEN
#define EVP_F_PKCS5_V2_PBE_KEYIVGEN 118
Definition at line 1552 of file evp.h.
EVP_F_PKCS5_V2_PBKDF2_KEYIVGEN
#define EVP_F_PKCS5_V2_PBKDF2_KEYIVGEN 164
Definition at line 1553 of file evp.h.
EVP_F_PKCS5_V2_SCRYPT_KEYIVGEN
#define EVP_F_PKCS5_V2_SCRYPT_KEYIVGEN 180
Definition at line 1554 of file evp.h.
EVP_F_PKEY_SET_TYPE
#define EVP_F_PKEY_SET_TYPE 158
Definition at line 1555 of file evp.h.
EVP_F_RC2_MAGIC_TO_METH
#define EVP_F_RC2_MAGIC_TO_METH 109
Definition at line 1556 of file evp.h.
EVP_F_RC5_CTRL
#define EVP_F_RC5_CTRL 125
Definition at line 1557 of file evp.h.
EVP_GCM_TLS_EXPLICIT_IV_LEN
#define EVP_GCM_TLS_EXPLICIT_IV_LEN 8
Definition at line 361 of file evp.h.
EVP_GCM_TLS_FIXED_IV_LEN
#define EVP_GCM_TLS_FIXED_IV_LEN 4
Definition at line 359 of file evp.h.
EVP_GCM_TLS_TAG_LEN
#define EVP_GCM_TLS_TAG_LEN 16
Definition at line 363 of file evp.h.
EVP_get_cipherbynid
#define EVP_get_cipherbynid (a) EVP_get_cipherbyname(OBJ_nid2sn(a))
Definition at line 424 of file evp.h.
Referenced by PKCS12_pack_p7encdata(), and PKCS12_SAFEBAG_create_pkcs8_encrypt().
EVP_get_cipherbyobj
#define EVP_get_cipherbyobj (a) EVP_get_cipherbynid(OBJ_obj2nid(a))
Definition at line 425 of file evp.h.
Referenced by cms_RecipientInfo_pwri_crypt().
EVP_get_digestbynid
#define EVP_get_digestbynid (a) EVP_get_digestbyname(OBJ_nid2sn(a))
Definition at line 422 of file evp.h.
Referenced by PKCS7_add_signature(), and PKCS7_signatureVerify().
EVP_get_digestbyobj
#define EVP_get_digestbyobj (a) EVP_get_digestbynid(OBJ_obj2nid(a))
Definition at line 423 of file evp.h.
Referenced by cms_DigestAlgorithm_init_bio().
EVP_idea_cfb
#define EVP_idea_cfb EVP_idea_cfb64
Definition at line 736 of file evp.h.
EVP_MAX_BLOCK_LENGTH
#define EVP_MAX_BLOCK_LENGTH 32
Definition at line 21 of file evp.h.
Referenced by CMAC_CTX_cleanup().
EVP_MAX_IV_LENGTH
#define EVP_MAX_IV_LENGTH 16
Definition at line 20 of file evp.h.
Referenced by ssl3_change_cipher_state(), and tls1_change_cipher_state().
EVP_MAX_KEY_LENGTH
#define EVP_MAX_KEY_LENGTH 64
Definition at line 19 of file evp.h.
Referenced by ssl3_change_cipher_state(), and tls1_change_cipher_state().
EVP_MAX_MD_SIZE
#define EVP_MAX_MD_SIZE 64/* longest known is SHA512 */
Definition at line 18 of file evp.h.
Referenced by cms_msgSigDigest_add1(), cms_Receipt_verify(), CMS_SignerInfo_verify_content(), EVP_SignFinal(), EVP_VerifyFinal(), PKCS12_set_mac(), PKCS12_verify_mac(), PKCS7_signatureVerify(), tls1_final_finish_mac(), tls1_generate_master_secret(), and tls_construct_finished().
EVP_MD_CTRL_ALG_CTRL
#define EVP_MD_CTRL_ALG_CTRL 0x1000
Definition at line 134 of file evp.h.
EVP_MD_CTRL_DIGALGID
#define EVP_MD_CTRL_DIGALGID 0x1
Definition at line 129 of file evp.h.
EVP_MD_CTRL_MICALG
#define EVP_MD_CTRL_MICALG 0x2
Definition at line 130 of file evp.h.
EVP_MD_CTX_block_size
#define EVP_MD_CTX_block_size (e) EVP_MD_block_size(EVP_MD_CTX_md(e))
Definition at line 442 of file evp.h.
EVP_MD_CTX_create
#define EVP_MD_CTX_create () EVP_MD_CTX_new()
Definition at line 521 of file evp.h.
EVP_MD_CTX_destroy
#define EVP_MD_CTX_destroy (ctx) EVP_MD_CTX_free((ctx))
Definition at line 523 of file evp.h.
EVP_MD_CTX_FLAG_CLEANED
#define EVP_MD_CTX_FLAG_CLEANED
Value:
0x0002/* context has already been
                                                * cleaned */
Definition at line 142 of file evp.h.
Referenced by EVP_DigestInit_ex(), and EVP_MD_CTX_reset().
EVP_MD_CTX_FLAG_FINALISE
#define EVP_MD_CTX_FLAG_FINALISE 0x0200
Definition at line 171 of file evp.h.
Referenced by EVP_DigestSignFinal(), EVP_SignFinal(), and EVP_VerifyFinal().
EVP_MD_CTX_FLAG_NO_INIT
#define EVP_MD_CTX_FLAG_NO_INIT 0x0100/* Don't initialize md_data */
Definition at line 164 of file evp.h.
Referenced by EVP_DigestInit_ex().
EVP_MD_CTX_FLAG_NON_FIPS_ALLOW
#define EVP_MD_CTX_FLAG_NON_FIPS_ALLOW
Value:
0x0008/* Allow use of non FIPS
                                                * digest in FIPS mode */
Definition at line 151 of file evp.h.
EVP_MD_CTX_FLAG_ONESHOT
#define EVP_MD_CTX_FLAG_ONESHOT
Value:
0x0001/* digest update will be
                                                * called once only */
Definition at line 140 of file evp.h.
EVP_MD_CTX_FLAG_PAD_MASK
#define EVP_MD_CTX_FLAG_PAD_MASK 0xF0/* RSA mode to use */
Definition at line 159 of file evp.h.
EVP_MD_CTX_FLAG_PAD_PKCS1
#define EVP_MD_CTX_FLAG_PAD_PKCS1 0x00/* PKCS#1 v1.5 mode */
Definition at line 160 of file evp.h.
EVP_MD_CTX_FLAG_PAD_PSS
#define EVP_MD_CTX_FLAG_PAD_PSS 0x20/* PSS mode */
Definition at line 162 of file evp.h.
EVP_MD_CTX_FLAG_PAD_X931
#define EVP_MD_CTX_FLAG_PAD_X931 0x10/* X9.31 mode */
Definition at line 161 of file evp.h.
EVP_MD_CTX_FLAG_REUSE
#define EVP_MD_CTX_FLAG_REUSE
Value:
0x0004/* Don't free up ctx->md_data
                                                * in EVP_MD_CTX_reset */
Definition at line 144 of file evp.h.
Referenced by EVP_MD_CTX_reset().
EVP_MD_CTX_init
#define EVP_MD_CTX_init (ctx) EVP_MD_CTX_reset((ctx))
Definition at line 522 of file evp.h.
EVP_MD_CTX_size
#define EVP_MD_CTX_size (e) EVP_MD_size(EVP_MD_CTX_md(e))
Definition at line 441 of file evp.h.
Referenced by ssl3_enc().
EVP_MD_CTX_type
#define EVP_MD_CTX_type (e) EVP_MD_type(EVP_MD_CTX_md(e))
Definition at line 443 of file evp.h.
Referenced by cms_DigestAlgorithm_find_ctx(), PKCS7_signatureVerify(), and ssl3_cbc_record_digest_supported().
EVP_MD_FLAG_DIGALGID_ABSENT
#define EVP_MD_FLAG_DIGALGID_ABSENT 0x0008
Definition at line 118 of file evp.h.
EVP_MD_FLAG_DIGALGID_CUSTOM
#define EVP_MD_FLAG_DIGALGID_CUSTOM 0x0018
Definition at line 122 of file evp.h.
EVP_MD_FLAG_DIGALGID_MASK
#define EVP_MD_FLAG_DIGALGID_MASK 0x0018
Definition at line 110 of file evp.h.
EVP_MD_FLAG_DIGALGID_NULL
#define EVP_MD_FLAG_DIGALGID_NULL 0x0000
Definition at line 114 of file evp.h.
EVP_MD_FLAG_FIPS
#define EVP_MD_FLAG_FIPS 0x0400
Definition at line 125 of file evp.h.
EVP_MD_FLAG_ONESHOT
#define EVP_MD_FLAG_ONESHOT 0x0001
Definition at line 106 of file evp.h.
EVP_MD_name
#define EVP_MD_name (e) OBJ_nid2sn(EVP_MD_nid(e))
Definition at line 429 of file evp.h.
EVP_MD_nid
#define EVP_MD_nid (e) EVP_MD_type(e)
Definition at line 428 of file evp.h.
Referenced by ASN1_item_sign_ctx().
EVP_OpenUpdate
#define EVP_OpenUpdate (a, b, c, d, e) EVP_DecryptUpdate(a,b,c,d,e)
Definition at line 488 of file evp.h.
EVP_PADDING_ANSI923
#define EVP_PADDING_ANSI923 3
Definition at line 343 of file evp.h.
EVP_PADDING_ISO10126
#define EVP_PADDING_ISO10126 4
Definition at line 344 of file evp.h.
EVP_PADDING_ISO7816_4
#define EVP_PADDING_ISO7816_4 2
Definition at line 342 of file evp.h.
EVP_PADDING_PKCS7
#define EVP_PADDING_PKCS7 1
Definition at line 341 of file evp.h.
EVP_PADDING_ZERO
#define EVP_PADDING_ZERO 5
Definition at line 345 of file evp.h.
EVP_PBE_TYPE_KDF
#define EVP_PBE_TYPE_KDF 0x2
Definition at line 1040 of file evp.h.
EVP_PBE_TYPE_OUTER
#define EVP_PBE_TYPE_OUTER 0x0
Definition at line 1036 of file evp.h.
EVP_PBE_TYPE_PRF
#define EVP_PBE_TYPE_PRF 0x1
Definition at line 1038 of file evp.h.
EVP_PK_DH
#define EVP_PK_DH 0x0004
Definition at line 31 of file evp.h.
EVP_PK_DSA
#define EVP_PK_DSA 0x0002
Definition at line 30 of file evp.h.
EVP_PK_EC
#define EVP_PK_EC 0x0008
Definition at line 32 of file evp.h.
EVP_PK_RSA
#define EVP_PK_RSA 0x0001
Definition at line 29 of file evp.h.
EVP_PKEY_ALG_CTRL
#define EVP_PKEY_ALG_CTRL 0x1000
Definition at line 1207 of file evp.h.
EVP_PKEY_assign_DH
#define EVP_PKEY_assign_DH (pkey, dh)
Value:
EVP_PKEY_assign((pkey),EVP_PKEY_DH,\
                                        (char *)(dh))
Definition at line 403 of file evp.h.
EVP_PKEY_assign_DSA
#define EVP_PKEY_assign_DSA (pkey, dsa)
Value:
EVP_PKEY_assign((pkey),EVP_PKEY_DSA,\
                                        (char *)(dsa))
Definition at line 398 of file evp.h.
EVP_PKEY_assign_EC_KEY
#define EVP_PKEY_assign_EC_KEY (pkey, eckey)
Value:
EVP_PKEY_assign((pkey),EVP_PKEY_EC,\
                                        (char *)(eckey))
Definition at line 408 of file evp.h.
EVP_PKEY_assign_POLY1305
#define EVP_PKEY_assign_POLY1305 (pkey, polykey)
Value:
EVP_PKEY_assign((pkey),EVP_PKEY_POLY1305,\
                                        (char *)(polykey))
Definition at line 417 of file evp.h.
EVP_PKEY_assign_RSA
#define EVP_PKEY_assign_RSA (pkey, rsa)
Value:
EVP_PKEY_assign((pkey),EVP_PKEY_RSA,\
                                        (char *)(rsa))
Definition at line 393 of file evp.h.
EVP_PKEY_assign_SIPHASH
#define EVP_PKEY_assign_SIPHASH (pkey, shkey)
Value:
EVP_PKEY_assign((pkey),EVP_PKEY_SIPHASH,\
                                        (char *)(shkey))
Definition at line 412 of file evp.h.
EVP_PKEY_CMAC
#define EVP_PKEY_CMAC NID_cmac
Definition at line 53 of file evp.h.
EVP_PKEY_CTRL_CIPHER
#define EVP_PKEY_CTRL_CIPHER 12
Definition at line 1201 of file evp.h.
EVP_PKEY_CTRL_CMS_DECRYPT
#define EVP_PKEY_CTRL_CMS_DECRYPT 10
Definition at line 1198 of file evp.h.
EVP_PKEY_CTRL_CMS_ENCRYPT
#define EVP_PKEY_CTRL_CMS_ENCRYPT 9
Definition at line 1197 of file evp.h.
EVP_PKEY_CTRL_CMS_SIGN
#define EVP_PKEY_CTRL_CMS_SIGN 11
Definition at line 1199 of file evp.h.
EVP_PKEY_CTRL_DIGESTINIT
#define EVP_PKEY_CTRL_DIGESTINIT 7
Definition at line 1192 of file evp.h.
Referenced by EVP_DigestInit_ex().
EVP_PKEY_CTRL_GET_MD
#define EVP_PKEY_CTRL_GET_MD 13
Definition at line 1203 of file evp.h.
EVP_PKEY_CTRL_MD
#define EVP_PKEY_CTRL_MD 1
Definition at line 1182 of file evp.h.
Referenced by EVP_PKEY_CTX_ctrl_str().
EVP_PKEY_CTRL_PEER_KEY
#define EVP_PKEY_CTRL_PEER_KEY 2
Definition at line 1183 of file evp.h.
EVP_PKEY_CTRL_PKCS7_DECRYPT
#define EVP_PKEY_CTRL_PKCS7_DECRYPT 4
Definition at line 1186 of file evp.h.
EVP_PKEY_CTRL_PKCS7_ENCRYPT
#define EVP_PKEY_CTRL_PKCS7_ENCRYPT 3
Definition at line 1185 of file evp.h.
EVP_PKEY_CTRL_PKCS7_SIGN
#define EVP_PKEY_CTRL_PKCS7_SIGN 5
Definition at line 1188 of file evp.h.
EVP_PKEY_CTRL_SET_DIGEST_SIZE
#define EVP_PKEY_CTRL_SET_DIGEST_SIZE 14
Definition at line 1205 of file evp.h.
EVP_PKEY_CTRL_SET_IV
#define EVP_PKEY_CTRL_SET_IV 8
Definition at line 1195 of file evp.h.
EVP_PKEY_CTRL_SET_MAC_KEY
#define EVP_PKEY_CTRL_SET_MAC_KEY 6
Definition at line 1190 of file evp.h.
EVP_PKEY_CTX_get_signature_md
#define EVP_PKEY_CTX_get_signature_md (ctx, pmd)
Value:
EVP_PKEY_CTX_ctrl(ctx, -1, EVP_PKEY_OP_TYPE_SIG,  \
                                        EVP_PKEY_CTRL_GET_MD, 0, (void *)pmd)
Definition at line 1174 of file evp.h.
EVP_PKEY_CTX_set_mac_key
#define EVP_PKEY_CTX_set_mac_key (ctx, key, len)
Value:
EVP_PKEY_CTX_ctrl(ctx, -1, EVP_PKEY_OP_KEYGEN,  \
                                  EVP_PKEY_CTRL_SET_MAC_KEY, len, (void *)key)
Definition at line 1178 of file evp.h.
Referenced by EVP_PKEY_new_mac_key().
EVP_PKEY_CTX_set_signature_md
#define EVP_PKEY_CTX_set_signature_md (ctx, md)
Value:
EVP_PKEY_CTX_ctrl(ctx, -1, EVP_PKEY_OP_TYPE_SIG,  \
                                        EVP_PKEY_CTRL_MD, 0, (void *)md)
Definition at line 1170 of file evp.h.
Referenced by EVP_SignFinal(), and EVP_VerifyFinal().
EVP_PKEY_DH
#define EVP_PKEY_DH NID_dhKeyAgreement
Definition at line 49 of file evp.h.
Referenced by EVP_PKEY_get0_DH(), and ssl_print_tmp_key().
EVP_PKEY_DHX
#define EVP_PKEY_DHX NID_dhpublicnumber
Definition at line 50 of file evp.h.
Referenced by EVP_PKEY_get0_DH().
EVP_PKEY_DSA
#define EVP_PKEY_DSA NID_dsa
Definition at line 44 of file evp.h.
Referenced by d2i_AutoPrivateKey(), EVP_PKEY_get0_DSA(), EVP_PKEY_save_parameters(), i2d_PublicKey(), and ssl_cert_type().
EVP_PKEY_DSA1
#define EVP_PKEY_DSA1 NID_dsa_2
Definition at line 45 of file evp.h.
EVP_PKEY_DSA2
#define EVP_PKEY_DSA2 NID_dsaWithSHA
Definition at line 46 of file evp.h.
EVP_PKEY_DSA3
#define EVP_PKEY_DSA3 NID_dsaWithSHA1
Definition at line 47 of file evp.h.
EVP_PKEY_DSA4
#define EVP_PKEY_DSA4 NID_dsaWithSHA1_2
Definition at line 48 of file evp.h.
EVP_PKEY_EC
#define EVP_PKEY_EC NID_X9_62_id_ecPublicKey
Definition at line 51 of file evp.h.
Referenced by d2i_AutoPrivateKey(), EVP_PKEY_get0_EC_KEY(), i2d_PublicKey(), ssl_cert_type(), and ssl_print_tmp_key().
EVP_PKEY_FLAG_AUTOARGLEN
#define EVP_PKEY_FLAG_AUTOARGLEN 2
Definition at line 1209 of file evp.h.
EVP_PKEY_FLAG_SIGCTX_CUSTOM
#define EVP_PKEY_FLAG_SIGCTX_CUSTOM 4
Definition at line 1213 of file evp.h.
Referenced by EVP_DigestSignFinal().
EVP_PKEY_HKDF
#define EVP_PKEY_HKDF NID_hkdf
Definition at line 55 of file evp.h.
EVP_PKEY_HMAC
#define EVP_PKEY_HMAC NID_hmac
Definition at line 52 of file evp.h.
Referenced by EVP_PKEY_get0_hmac().
EVP_PKEY_MO_DECRYPT
#define EVP_PKEY_MO_DECRYPT 0x0008
Definition at line 66 of file evp.h.
EVP_PKEY_MO_ENCRYPT
#define EVP_PKEY_MO_ENCRYPT 0x0004
Definition at line 65 of file evp.h.
EVP_PKEY_MO_SIGN
#define EVP_PKEY_MO_SIGN 0x0001
Definition at line 63 of file evp.h.
EVP_PKEY_MO_VERIFY
#define EVP_PKEY_MO_VERIFY 0x0002
Definition at line 64 of file evp.h.
EVP_PKEY_NONE
#define EVP_PKEY_NONE NID_undef
Definition at line 40 of file evp.h.
Referenced by EVP_PKEY_copy_parameters().
EVP_PKEY_OP_DECRYPT
#define EVP_PKEY_OP_DECRYPT (1<<9)
Definition at line 1154 of file evp.h.
EVP_PKEY_OP_DERIVE
#define EVP_PKEY_OP_DERIVE (1<<10)
Definition at line 1155 of file evp.h.
Referenced by EVP_PKEY_derive().
EVP_PKEY_OP_ENCRYPT
#define EVP_PKEY_OP_ENCRYPT (1<<8)
Definition at line 1153 of file evp.h.
EVP_PKEY_OP_KEYGEN
#define EVP_PKEY_OP_KEYGEN (1<<2)
Definition at line 1147 of file evp.h.
EVP_PKEY_OP_PARAMGEN
#define EVP_PKEY_OP_PARAMGEN (1<<1)
Definition at line 1146 of file evp.h.
EVP_PKEY_OP_SIGN
#define EVP_PKEY_OP_SIGN (1<<3)
Definition at line 1148 of file evp.h.
Referenced by EVP_PKEY_sign().
EVP_PKEY_OP_SIGNCTX
#define EVP_PKEY_OP_SIGNCTX (1<<6)
Definition at line 1151 of file evp.h.
EVP_PKEY_OP_TYPE_CRYPT
#define EVP_PKEY_OP_TYPE_CRYPT (EVP_PKEY_OP_ENCRYPT | EVP_PKEY_OP_DECRYPT)
Definition at line 1161 of file evp.h.
EVP_PKEY_OP_TYPE_GEN
#define EVP_PKEY_OP_TYPE_GEN (EVP_PKEY_OP_PARAMGEN | EVP_PKEY_OP_KEYGEN)
Definition at line 1167 of file evp.h.
EVP_PKEY_OP_TYPE_NOGEN
#define EVP_PKEY_OP_TYPE_NOGEN (EVP_PKEY_OP_TYPE_SIG | EVP_PKEY_OP_TYPE_CRYPT | EVP_PKEY_OP_DERIVE)
Definition at line 1164 of file evp.h.
EVP_PKEY_OP_TYPE_SIG
#define EVP_PKEY_OP_TYPE_SIG
Value:
(EVP_PKEY_OP_SIGN | EVP_PKEY_OP_VERIFY | EVP_PKEY_OP_VERIFYRECOVER \
                | EVP_PKEY_OP_SIGNCTX | EVP_PKEY_OP_VERIFYCTX)
Definition at line 1157 of file evp.h.
Referenced by EVP_DigestInit_ex(), and EVP_PKEY_CTX_ctrl_str().
EVP_PKEY_OP_UNDEFINED
#define EVP_PKEY_OP_UNDEFINED 0
Definition at line 1145 of file evp.h.
EVP_PKEY_OP_VERIFY
#define EVP_PKEY_OP_VERIFY (1<<4)
Definition at line 1149 of file evp.h.
Referenced by EVP_PKEY_verify().
EVP_PKEY_OP_VERIFYCTX
#define EVP_PKEY_OP_VERIFYCTX (1<<7)
Definition at line 1152 of file evp.h.
EVP_PKEY_OP_VERIFYRECOVER
#define EVP_PKEY_OP_VERIFYRECOVER (1<<5)
Definition at line 1150 of file evp.h.
Referenced by EVP_PKEY_verify_recover().
EVP_PKEY_POLY1305
#define EVP_PKEY_POLY1305 NID_poly1305
Definition at line 56 of file evp.h.
Referenced by EVP_PKEY_get0_poly1305().
EVP_PKEY_RSA
#define EVP_PKEY_RSA NID_rsaEncryption
Definition at line 41 of file evp.h.
Referenced by EVP_PKEY_get0_RSA(), i2d_PublicKey(), RSA_pkey_ctx_ctrl(), ssl_cert_type(), and ssl_print_tmp_key().
EVP_PKEY_RSA2
#define EVP_PKEY_RSA2 NID_rsa
Definition at line 42 of file evp.h.
EVP_PKEY_RSA_PSS
#define EVP_PKEY_RSA_PSS NID_rsassaPss
Definition at line 43 of file evp.h.
Referenced by RSA_pkey_ctx_ctrl().
EVP_PKEY_SIPHASH
#define EVP_PKEY_SIPHASH NID_siphash
Definition at line 57 of file evp.h.
Referenced by EVP_PKEY_get0_siphash().
EVP_PKEY_TLS1_PRF
#define EVP_PKEY_TLS1_PRF NID_tls1_prf
Definition at line 54 of file evp.h.
EVP_PKS_DSA
#define EVP_PKS_DSA 0x0200
Definition at line 37 of file evp.h.
EVP_PKS_EC
#define EVP_PKS_EC 0x0400
Definition at line 38 of file evp.h.
EVP_PKS_RSA
#define EVP_PKS_RSA 0x0100
Definition at line 36 of file evp.h.
EVP_PKT_ENC
#define EVP_PKT_ENC 0x0020
Definition at line 34 of file evp.h.
EVP_PKT_EXCH
#define EVP_PKT_EXCH 0x0040
Definition at line 35 of file evp.h.
EVP_PKT_SIGN
#define EVP_PKT_SIGN 0x0010
Definition at line 33 of file evp.h.
EVP_R_AES_KEY_SETUP_FAILED
#define EVP_R_AES_KEY_SETUP_FAILED 143
Definition at line 1560 of file evp.h.
EVP_R_BAD_DECRYPT
#define EVP_R_BAD_DECRYPT 100
Definition at line 1561 of file evp.h.
EVP_R_BUFFER_TOO_SMALL
#define EVP_R_BUFFER_TOO_SMALL 155
Definition at line 1562 of file evp.h.
EVP_R_CAMELLIA_KEY_SETUP_FAILED
#define EVP_R_CAMELLIA_KEY_SETUP_FAILED 157
Definition at line 1563 of file evp.h.
EVP_R_CIPHER_PARAMETER_ERROR
#define EVP_R_CIPHER_PARAMETER_ERROR 122
Definition at line 1564 of file evp.h.
EVP_R_COMMAND_NOT_SUPPORTED
#define EVP_R_COMMAND_NOT_SUPPORTED 147
Definition at line 1565 of file evp.h.
Referenced by EVP_PKEY_CTX_ctrl_str().
EVP_R_COPY_ERROR
#define EVP_R_COPY_ERROR 173
Definition at line 1566 of file evp.h.
EVP_R_CTRL_NOT_IMPLEMENTED
#define EVP_R_CTRL_NOT_IMPLEMENTED 132
Definition at line 1567 of file evp.h.
EVP_R_CTRL_OPERATION_NOT_IMPLEMENTED
#define EVP_R_CTRL_OPERATION_NOT_IMPLEMENTED 133
Definition at line 1568 of file evp.h.
EVP_R_DATA_NOT_MULTIPLE_OF_BLOCK_LENGTH
#define EVP_R_DATA_NOT_MULTIPLE_OF_BLOCK_LENGTH 138
Definition at line 1569 of file evp.h.
EVP_R_DECODE_ERROR
#define EVP_R_DECODE_ERROR 114
Definition at line 1570 of file evp.h.
EVP_R_DIFFERENT_KEY_TYPES
#define EVP_R_DIFFERENT_KEY_TYPES 101
Definition at line 1571 of file evp.h.
Referenced by EVP_PKEY_copy_parameters().
EVP_R_DIFFERENT_PARAMETERS
#define EVP_R_DIFFERENT_PARAMETERS 153
Definition at line 1572 of file evp.h.
Referenced by EVP_PKEY_copy_parameters().
EVP_R_ERROR_LOADING_SECTION
#define EVP_R_ERROR_LOADING_SECTION 165
Definition at line 1573 of file evp.h.
EVP_R_ERROR_SETTING_FIPS_MODE
#define EVP_R_ERROR_SETTING_FIPS_MODE 166
Definition at line 1574 of file evp.h.
EVP_R_EXPECTING_A_DH_KEY
#define EVP_R_EXPECTING_A_DH_KEY 128
Definition at line 1577 of file evp.h.
Referenced by EVP_PKEY_get0_DH().
EVP_R_EXPECTING_A_DSA_KEY
#define EVP_R_EXPECTING_A_DSA_KEY 129
Definition at line 1578 of file evp.h.
Referenced by EVP_PKEY_get0_DSA().
EVP_R_EXPECTING_A_EC_KEY
#define EVP_R_EXPECTING_A_EC_KEY 142
Definition at line 1579 of file evp.h.
Referenced by EVP_PKEY_get0_EC_KEY().
EVP_R_EXPECTING_A_POLY1305_KEY
#define EVP_R_EXPECTING_A_POLY1305_KEY 164
Definition at line 1580 of file evp.h.
Referenced by EVP_PKEY_get0_poly1305().
EVP_R_EXPECTING_A_SIPHASH_KEY
#define EVP_R_EXPECTING_A_SIPHASH_KEY 175
Definition at line 1581 of file evp.h.
Referenced by EVP_PKEY_get0_siphash().
EVP_R_EXPECTING_AN_HMAC_KEY
#define EVP_R_EXPECTING_AN_HMAC_KEY 174
Definition at line 1575 of file evp.h.
Referenced by EVP_PKEY_get0_hmac().
EVP_R_EXPECTING_AN_RSA_KEY
#define EVP_R_EXPECTING_AN_RSA_KEY 127
Definition at line 1576 of file evp.h.
Referenced by EVP_PKEY_get0_RSA().
EVP_R_FIPS_MODE_NOT_SUPPORTED
#define EVP_R_FIPS_MODE_NOT_SUPPORTED 167
Definition at line 1582 of file evp.h.
EVP_R_ILLEGAL_SCRYPT_PARAMETERS
#define EVP_R_ILLEGAL_SCRYPT_PARAMETERS 171
Definition at line 1583 of file evp.h.
EVP_R_INITIALIZATION_ERROR
#define EVP_R_INITIALIZATION_ERROR 134
Definition at line 1584 of file evp.h.
Referenced by EVP_DigestInit_ex().
EVP_R_INPUT_NOT_INITIALIZED
#define EVP_R_INPUT_NOT_INITIALIZED 111
Definition at line 1585 of file evp.h.
EVP_R_INVALID_DIGEST
#define EVP_R_INVALID_DIGEST 152
Definition at line 1586 of file evp.h.
EVP_R_INVALID_FIPS_MODE
#define EVP_R_INVALID_FIPS_MODE 168
Definition at line 1587 of file evp.h.
EVP_R_INVALID_KEY
#define EVP_R_INVALID_KEY 163
Definition at line 1588 of file evp.h.
EVP_R_INVALID_KEY_LENGTH
#define EVP_R_INVALID_KEY_LENGTH 130
Definition at line 1589 of file evp.h.
EVP_R_INVALID_OPERATION
#define EVP_R_INVALID_OPERATION 148
Definition at line 1590 of file evp.h.
EVP_R_KEYGEN_FAILURE
#define EVP_R_KEYGEN_FAILURE 120
Definition at line 1591 of file evp.h.
EVP_R_MEMORY_LIMIT_EXCEEDED
#define EVP_R_MEMORY_LIMIT_EXCEEDED 172
Definition at line 1592 of file evp.h.
Referenced by EVP_PBE_scrypt().
EVP_R_MESSAGE_DIGEST_IS_NULL
#define EVP_R_MESSAGE_DIGEST_IS_NULL 159
Definition at line 1593 of file evp.h.
EVP_R_METHOD_NOT_SUPPORTED
#define EVP_R_METHOD_NOT_SUPPORTED 144
Definition at line 1594 of file evp.h.
Referenced by EVP_PKCS82PKEY(), and EVP_PKEY2PKCS8().
EVP_R_MISSING_PARAMETERS
#define EVP_R_MISSING_PARAMETERS 103
Definition at line 1595 of file evp.h.
Referenced by EVP_PKEY_copy_parameters().
EVP_R_NO_CIPHER_SET
#define EVP_R_NO_CIPHER_SET 131
Definition at line 1596 of file evp.h.
EVP_R_NO_DEFAULT_DIGEST
#define EVP_R_NO_DEFAULT_DIGEST 158
Definition at line 1597 of file evp.h.
EVP_R_NO_DIGEST_SET
#define EVP_R_NO_DIGEST_SET 139
Definition at line 1598 of file evp.h.
Referenced by EVP_DigestInit_ex().
EVP_R_NO_KEY_SET
#define EVP_R_NO_KEY_SET 154
Definition at line 1599 of file evp.h.
EVP_R_NO_OPERATION_SET
#define EVP_R_NO_OPERATION_SET 149
Definition at line 1600 of file evp.h.
EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE
#define EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE 150
Definition at line 1601 of file evp.h.
Referenced by EVP_PKEY_derive(), EVP_PKEY_sign(), EVP_PKEY_verify(), and EVP_PKEY_verify_recover().
EVP_R_OPERATON_NOT_INITIALIZED
#define EVP_R_OPERATON_NOT_INITIALIZED 151
Definition at line 1602 of file evp.h.
Referenced by EVP_PKEY_derive(), EVP_PKEY_sign(), EVP_PKEY_verify(), and EVP_PKEY_verify_recover().
EVP_R_PARTIALLY_OVERLAPPING
#define EVP_R_PARTIALLY_OVERLAPPING 162
Definition at line 1603 of file evp.h.
EVP_R_PRIVATE_KEY_DECODE_ERROR
#define EVP_R_PRIVATE_KEY_DECODE_ERROR 145
Definition at line 1604 of file evp.h.
Referenced by EVP_PKCS82PKEY().
EVP_R_PRIVATE_KEY_ENCODE_ERROR
#define EVP_R_PRIVATE_KEY_ENCODE_ERROR 146
Definition at line 1605 of file evp.h.
Referenced by EVP_PKEY2PKCS8().
EVP_R_PUBLIC_KEY_NOT_RSA
#define EVP_R_PUBLIC_KEY_NOT_RSA 106
Definition at line 1606 of file evp.h.
EVP_R_UNKNOWN_CIPHER
#define EVP_R_UNKNOWN_CIPHER 160
Definition at line 1607 of file evp.h.
EVP_R_UNKNOWN_DIGEST
#define EVP_R_UNKNOWN_DIGEST 161
Definition at line 1608 of file evp.h.
EVP_R_UNKNOWN_OPTION
#define EVP_R_UNKNOWN_OPTION 169
Definition at line 1609 of file evp.h.
EVP_R_UNKNOWN_PBE_ALGORITHM
#define EVP_R_UNKNOWN_PBE_ALGORITHM 121
Definition at line 1610 of file evp.h.
EVP_R_UNSUPPORTED_ALGORITHM
#define EVP_R_UNSUPPORTED_ALGORITHM 156
Definition at line 1611 of file evp.h.
EVP_R_UNSUPPORTED_CIPHER
#define EVP_R_UNSUPPORTED_CIPHER 107
Definition at line 1612 of file evp.h.
EVP_R_UNSUPPORTED_KEY_DERIVATION_FUNCTION
#define EVP_R_UNSUPPORTED_KEY_DERIVATION_FUNCTION 124
Definition at line 1614 of file evp.h.
EVP_R_UNSUPPORTED_KEY_SIZE
#define EVP_R_UNSUPPORTED_KEY_SIZE 108
Definition at line 1615 of file evp.h.
EVP_R_UNSUPPORTED_KEYLENGTH
#define EVP_R_UNSUPPORTED_KEYLENGTH 123
Definition at line 1613 of file evp.h.
EVP_R_UNSUPPORTED_NUMBER_OF_ROUNDS
#define EVP_R_UNSUPPORTED_NUMBER_OF_ROUNDS 135
Definition at line 1616 of file evp.h.
EVP_R_UNSUPPORTED_PRF
#define EVP_R_UNSUPPORTED_PRF 125
Definition at line 1617 of file evp.h.
EVP_R_UNSUPPORTED_PRIVATE_KEY_ALGORITHM
#define EVP_R_UNSUPPORTED_PRIVATE_KEY_ALGORITHM 118
Definition at line 1618 of file evp.h.
Referenced by EVP_PKCS82PKEY(), and EVP_PKEY2PKCS8().
EVP_R_UNSUPPORTED_SALT_TYPE
#define EVP_R_UNSUPPORTED_SALT_TYPE 126
Definition at line 1619 of file evp.h.
EVP_R_WRAP_MODE_NOT_ALLOWED
#define EVP_R_WRAP_MODE_NOT_ALLOWED 170
Definition at line 1620 of file evp.h.
EVP_R_WRONG_FINAL_BLOCK_LENGTH
#define EVP_R_WRONG_FINAL_BLOCK_LENGTH 109
Definition at line 1621 of file evp.h.
EVP_rc2_cfb
#define EVP_rc2_cfb EVP_rc2_cfb64
Definition at line 746 of file evp.h.
EVP_rc5_32_12_16_cfb
#define EVP_rc5_32_12_16_cfb EVP_rc5_32_12_16_cfb64
Definition at line 767 of file evp.h.
EVP_SealUpdate
#define EVP_SealUpdate (a, b, c, d, e) EVP_EncryptUpdate(a,b,c,d,e)
Definition at line 489 of file evp.h.
EVP_seed_cfb
#define EVP_seed_cfb EVP_seed_cfb128
Definition at line 858 of file evp.h.
Referenced by openssl_add_all_ciphers_int().
EVP_SignInit
#define EVP_SignInit (a, b) EVP_DigestInit(a,b)
Definition at line 483 of file evp.h.
EVP_SignInit_ex
#define EVP_SignInit_ex (a, b, c) EVP_DigestInit_ex(a,b,c)
Definition at line 482 of file evp.h.
Referenced by ASN1_sign().
EVP_SignUpdate
#define EVP_SignUpdate (a, b, c) EVP_DigestUpdate(a,b,c)
Definition at line 484 of file evp.h.
Referenced by ASN1_sign().
EVP_VerifyInit
#define EVP_VerifyInit (a, b) EVP_DigestInit(a,b)
Definition at line 486 of file evp.h.
EVP_VerifyInit_ex
#define EVP_VerifyInit_ex (a, b, c) EVP_DigestInit_ex(a,b,c)
Definition at line 485 of file evp.h.
Referenced by PKCS7_signatureVerify().
EVP_VerifyUpdate
#define EVP_VerifyUpdate (a, b, c) EVP_DigestUpdate(a,b,c)
Definition at line 487 of file evp.h.
Referenced by PKCS7_signatureVerify().
OpenSSL_add_all_algorithms
#define OpenSSL_add_all_algorithms ()
Value:
OPENSSL_init_crypto(OPENSSL_INIT_ADD_ALL_CIPHERS \
                        | OPENSSL_INIT_ADD_ALL_DIGESTS, NULL)
Definition at line 877 of file evp.h.
OPENSSL_add_all_algorithms_conf
#define OPENSSL_add_all_algorithms_conf ()
Value:
OPENSSL_init_crypto(OPENSSL_INIT_ADD_ALL_CIPHERS \
                        | OPENSSL_INIT_ADD_ALL_DIGESTS \
                        | OPENSSL_INIT_LOAD_CONFIG, NULL)
Definition at line 863 of file evp.h.
OPENSSL_add_all_algorithms_noconf
#define OPENSSL_add_all_algorithms_noconf ()
Value:
OPENSSL_init_crypto(OPENSSL_INIT_ADD_ALL_CIPHERS \
                        | OPENSSL_INIT_ADD_ALL_DIGESTS, NULL)
Definition at line 867 of file evp.h.
OpenSSL_add_all_ciphers
#define OpenSSL_add_all_ciphers () OPENSSL_init_crypto(OPENSSL_INIT_ADD_ALL_CIPHERS, NULL)
Definition at line 882 of file evp.h.
OpenSSL_add_all_digests
#define OpenSSL_add_all_digests () OPENSSL_init_crypto(OPENSSL_INIT_ADD_ALL_DIGESTS, NULL)
Definition at line 884 of file evp.h.
PKCS5_DEFAULT_ITER
#define PKCS5_DEFAULT_ITER 2048
Definition at line 25 of file evp.h.
PKCS5_SALT_LEN
#define PKCS5_SALT_LEN 8
Definition at line 23 of file evp.h.
Typedef Documentation
EVP_PBE_KEYGEN
typedef int(EVP_PBE_KEYGEN) (EVP_CIPHER_CTX *ctx, const char *pass, int passlen, ASN1_TYPE *param, const EVP_CIPHER *cipher, const EVP_MD *md, int en_de)
Definition at line 387 of file evp.h.
EVP_PKEY_gen_cb
typedef int EVP_PKEY_gen_cb(EVP_PKEY_CTX *ctx)
Definition at line 1278 of file evp.h.
Function Documentation
BIO_f_base64()
const BIO_METHOD* BIO_f_base64 (void)
Definition at line 66 of file bio_b64.c.
BIO_f_cipher()
const BIO_METHOD* BIO_f_cipher (void)
Definition at line 64 of file bio_enc.c.
BIO_f_md()
const BIO_METHOD* BIO_f_md (void)
Definition at line 50 of file bio_md.c.
Referenced by cms_DigestAlgorithm_init_bio().
BIO_f_reliable()
const BIO_METHOD* BIO_f_reliable (void)
Definition at line 126 of file bio_ok.c.
BIO_set_cipher()
__owur int BIO_set_cipher (BIO * b, const EVP_CIPHER * c, const unsigned char * k, const unsigned char * i, int enc)
Definition at line 428 of file bio_enc.c.
d2i_AutoPrivateKey()
EVP_PKEY* d2i_AutoPrivateKey (EVP_PKEY ** a, const unsigned char ** pp, long length)
Definition at line 79 of file d2i_pr.c.
References EVP_PKEY_DSA, EVP_PKEY_EC, NULL, pp, and STACK_OF.
Referenced by d2i_PrivateKey_bio(), and d2i_PrivateKey_fp().
d2i_PrivateKey()
EVP_PKEY* d2i_PrivateKey (int type, EVP_PKEY ** a, const unsigned char ** pp, long length)
Definition at line 21 of file d2i_pr.c.
d2i_PublicKey()
EVP_PKEY* d2i_PublicKey (int type, EVP_PKEY ** a, const unsigned char ** pp, long length)
Definition at line 22 of file d2i_pu.c.
ERR_load_EVP_strings()
int ERR_load_EVP_strings (void)
Definition at line 175 of file evp_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
EVP_add_alg_module()
void EVP_add_alg_module (void)
Definition at line 62 of file evp_cnf.c.
References CONF_module_add().
Referenced by OPENSSL_load_builtin_modules().
EVP_add_cipher()
int EVP_add_cipher (const EVP_CIPHER * cipher)
Definition at line 17 of file names.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_add_digest()
int EVP_add_digest (const EVP_MD * digest)
Definition at line 33 of file names.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_digests_int().
EVP_aes_128_cbc()
const EVP_CIPHER* EVP_aes_128_cbc (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_aes_128_cbc_hmac_sha1()
const EVP_CIPHER* EVP_aes_128_cbc_hmac_sha1 (void)
Definition at line 948 of file e_aes_cbc_hmac_sha1.c.
References NULL.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_aes_128_cbc_hmac_sha256()
const EVP_CIPHER* EVP_aes_128_cbc_hmac_sha256 (void)
Definition at line 930 of file e_aes_cbc_hmac_sha256.c.
References NULL.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_aes_128_ccm()
const EVP_CIPHER* EVP_aes_128_ccm (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_aes_128_cfb1()
const EVP_CIPHER* EVP_aes_128_cfb1 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_128_cfb128()
const EVP_CIPHER* EVP_aes_128_cfb128 (void)
Referenced by EVP_aes_128_cfb().
EVP_aes_128_cfb8()
const EVP_CIPHER* EVP_aes_128_cfb8 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_128_ctr()
const EVP_CIPHER* EVP_aes_128_ctr (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_128_ecb()
const EVP_CIPHER* EVP_aes_128_ecb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_128_gcm()
const EVP_CIPHER* EVP_aes_128_gcm (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_aes_128_ocb()
const EVP_CIPHER* EVP_aes_128_ocb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_128_ofb()
const EVP_CIPHER* EVP_aes_128_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_128_wrap()
const EVP_CIPHER* EVP_aes_128_wrap (void)
Definition at line 2303 of file e_aes.c.
Referenced by openssl_add_all_ciphers_int().
EVP_aes_128_wrap_pad()
const EVP_CIPHER* EVP_aes_128_wrap_pad (void)
Definition at line 2345 of file e_aes.c.
Referenced by openssl_add_all_ciphers_int().
EVP_aes_128_xts()
const EVP_CIPHER* EVP_aes_128_xts (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_192_cbc()
const EVP_CIPHER* EVP_aes_192_cbc (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_aes_192_ccm()
const EVP_CIPHER* EVP_aes_192_ccm (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_192_cfb1()
const EVP_CIPHER* EVP_aes_192_cfb1 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_192_cfb128()
const EVP_CIPHER* EVP_aes_192_cfb128 (void)
Referenced by EVP_aes_192_cfb().
EVP_aes_192_cfb8()
const EVP_CIPHER* EVP_aes_192_cfb8 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_192_ctr()
const EVP_CIPHER* EVP_aes_192_ctr (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_192_ecb()
const EVP_CIPHER* EVP_aes_192_ecb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_192_gcm()
const EVP_CIPHER* EVP_aes_192_gcm (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_192_ocb()
const EVP_CIPHER* EVP_aes_192_ocb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_192_ofb()
const EVP_CIPHER* EVP_aes_192_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_192_wrap()
const EVP_CIPHER* EVP_aes_192_wrap (void)
Definition at line 2317 of file e_aes.c.
Referenced by openssl_add_all_ciphers_int().
EVP_aes_192_wrap_pad()
const EVP_CIPHER* EVP_aes_192_wrap_pad (void)
Definition at line 2359 of file e_aes.c.
Referenced by openssl_add_all_ciphers_int().
EVP_aes_256_cbc()
const EVP_CIPHER* EVP_aes_256_cbc (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_aes_256_cbc_hmac_sha1()
const EVP_CIPHER* EVP_aes_256_cbc_hmac_sha1 (void)
Definition at line 953 of file e_aes_cbc_hmac_sha1.c.
References NULL.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_aes_256_cbc_hmac_sha256()
const EVP_CIPHER* EVP_aes_256_cbc_hmac_sha256 (void)
Definition at line 935 of file e_aes_cbc_hmac_sha256.c.
References NULL.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_aes_256_ccm()
const EVP_CIPHER* EVP_aes_256_ccm (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_aes_256_cfb1()
const EVP_CIPHER* EVP_aes_256_cfb1 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_256_cfb128()
const EVP_CIPHER* EVP_aes_256_cfb128 (void)
Referenced by EVP_aes_256_cfb().
EVP_aes_256_cfb8()
const EVP_CIPHER* EVP_aes_256_cfb8 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_256_ctr()
const EVP_CIPHER* EVP_aes_256_ctr (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_256_ecb()
const EVP_CIPHER* EVP_aes_256_ecb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_256_gcm()
const EVP_CIPHER* EVP_aes_256_gcm (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_aes_256_ocb()
const EVP_CIPHER* EVP_aes_256_ocb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_256_ofb()
const EVP_CIPHER* EVP_aes_256_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_aes_256_wrap()
const EVP_CIPHER* EVP_aes_256_wrap (void)
Definition at line 2331 of file e_aes.c.
Referenced by openssl_add_all_ciphers_int().
EVP_aes_256_wrap_pad()
const EVP_CIPHER* EVP_aes_256_wrap_pad (void)
Definition at line 2373 of file e_aes.c.
Referenced by openssl_add_all_ciphers_int().
EVP_aes_256_xts()
const EVP_CIPHER* EVP_aes_256_xts (void)
Referenced by openssl_add_all_ciphers_int().
EVP_bf_cbc()
const EVP_CIPHER* EVP_bf_cbc (void)
Referenced by openssl_add_all_ciphers_int().
EVP_bf_cfb64()
const EVP_CIPHER* EVP_bf_cfb64 (void)
Referenced by EVP_bf_cfb().
EVP_bf_ecb()
const EVP_CIPHER* EVP_bf_ecb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_bf_ofb()
const EVP_CIPHER* EVP_bf_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_blake2b512()
const EVP_MD* EVP_blake2b512 (void)
Definition at line 55 of file m_blake2b.c.
Referenced by openssl_add_all_digests_int().
EVP_blake2s256()
const EVP_MD* EVP_blake2s256 (void)
Definition at line 55 of file m_blake2s.c.
Referenced by openssl_add_all_digests_int().
EVP_BytesToKey()
__owur int EVP_BytesToKey (const EVP_CIPHER * type, const EVP_MD * md, const unsigned char * salt, const unsigned char * data, int datal, int count, unsigned char * key, unsigned char * iv)
Definition at line 74 of file evp_key.c.
EVP_camellia_128_cbc()
const EVP_CIPHER* EVP_camellia_128_cbc (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_camellia_128_cfb1()
const EVP_CIPHER* EVP_camellia_128_cfb1 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_128_cfb128()
const EVP_CIPHER* EVP_camellia_128_cfb128 (void)
EVP_camellia_128_cfb8()
const EVP_CIPHER* EVP_camellia_128_cfb8 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_128_ctr()
const EVP_CIPHER* EVP_camellia_128_ctr (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_128_ecb()
const EVP_CIPHER* EVP_camellia_128_ecb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_128_ofb()
const EVP_CIPHER* EVP_camellia_128_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_192_cbc()
const EVP_CIPHER* EVP_camellia_192_cbc (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_192_cfb1()
const EVP_CIPHER* EVP_camellia_192_cfb1 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_192_cfb128()
const EVP_CIPHER* EVP_camellia_192_cfb128 (void)
EVP_camellia_192_cfb8()
const EVP_CIPHER* EVP_camellia_192_cfb8 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_192_ctr()
const EVP_CIPHER* EVP_camellia_192_ctr (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_192_ecb()
const EVP_CIPHER* EVP_camellia_192_ecb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_192_ofb()
const EVP_CIPHER* EVP_camellia_192_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_256_cbc()
const EVP_CIPHER* EVP_camellia_256_cbc (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_camellia_256_cfb1()
const EVP_CIPHER* EVP_camellia_256_cfb1 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_256_cfb128()
const EVP_CIPHER* EVP_camellia_256_cfb128 (void)
EVP_camellia_256_cfb8()
const EVP_CIPHER* EVP_camellia_256_cfb8 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_256_ctr()
const EVP_CIPHER* EVP_camellia_256_ctr (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_256_ecb()
const EVP_CIPHER* EVP_camellia_256_ecb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_camellia_256_ofb()
const EVP_CIPHER* EVP_camellia_256_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_cast5_cbc()
const EVP_CIPHER* EVP_cast5_cbc (void)
Referenced by openssl_add_all_ciphers_int().
EVP_cast5_cfb64()
const EVP_CIPHER* EVP_cast5_cfb64 (void)
Referenced by EVP_cast5_cfb().
EVP_cast5_ecb()
const EVP_CIPHER* EVP_cast5_ecb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_cast5_ofb()
const EVP_CIPHER* EVP_cast5_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_chacha20()
const EVP_CIPHER* EVP_chacha20 (void)
Definition at line 141 of file e_chacha20_poly1305.c.
Referenced by openssl_add_all_ciphers_int().
EVP_chacha20_poly1305()
const EVP_CIPHER* EVP_chacha20_poly1305 (void)
Definition at line 449 of file e_chacha20_poly1305.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_Cipher()
int EVP_Cipher (EVP_CIPHER_CTX * c, unsigned char * out, const unsigned char * in, unsigned int inl)
Definition at line 180 of file evp_lib.c.
Referenced by CMAC_Update(), and ssl3_enc().
EVP_CIPHER_asn1_to_param()
int EVP_CIPHER_asn1_to_param (EVP_CIPHER_CTX * c, ASN1_TYPE * type)
Definition at line 46 of file evp_lib.c.
Referenced by cms_RecipientInfo_pwri_crypt().
EVP_CIPHER_block_size()
int EVP_CIPHER_block_size (const EVP_CIPHER * cipher)
Definition at line 165 of file evp_lib.c.
EVP_CIPHER_CTX_block_size()
int EVP_CIPHER_CTX_block_size (const EVP_CIPHER_CTX * ctx)
Definition at line 170 of file evp_lib.c.
Referenced by CMAC_Update(), and ssl3_enc().
EVP_CIPHER_CTX_buf_noconst()
unsigned char* EVP_CIPHER_CTX_buf_noconst (EVP_CIPHER_CTX * ctx)
Definition at line 251 of file evp_lib.c.
Referenced by BLOCK_CIPHER_custom().
EVP_CIPHER_CTX_cipher()
const EVP_CIPHER* EVP_CIPHER_CTX_cipher (const EVP_CIPHER_CTX * ctx)
Definition at line 186 of file evp_lib.c.
Referenced by ssl3_enc(), and tls1_cbc_remove_padding().
EVP_CIPHER_CTX_clear_flags()
void EVP_CIPHER_CTX_clear_flags (EVP_CIPHER_CTX * ctx, int flags)
Definition at line 489 of file evp_lib.c.
EVP_CIPHER_CTX_copy()
int EVP_CIPHER_CTX_copy (EVP_CIPHER_CTX * out, const EVP_CIPHER_CTX * in)
Definition at line 607 of file evp_enc.c.
EVP_CIPHER_CTX_ctrl()
int EVP_CIPHER_CTX_ctrl (EVP_CIPHER_CTX * ctx, int type, int arg, void * ptr)
Definition at line 576 of file evp_enc.c.
Referenced by EVP_CIPHER_CTX_rand_key().
EVP_CIPHER_CTX_encrypting()
int EVP_CIPHER_CTX_encrypting (const EVP_CIPHER_CTX * ctx)
Definition at line 191 of file evp_lib.c.
Referenced by BLOCK_CIPHER_custom().
EVP_CIPHER_CTX_free()
void EVP_CIPHER_CTX_free (EVP_CIPHER_CTX * c)
Definition at line 44 of file evp_enc.c.
References EVP_CIPHER_CTX_reset(), and OPENSSL_free.
Referenced by CMAC_CTX_cleanup(), dtls1_hm_fragment_free(), and ssl_clear_cipher_ctx().
EVP_CIPHER_CTX_get_app_data()
void* EVP_CIPHER_CTX_get_app_data (const EVP_CIPHER_CTX * ctx)
Definition at line 201 of file evp_lib.c.
EVP_CIPHER_CTX_get_cipher_data()
void* EVP_CIPHER_CTX_get_cipher_data (const EVP_CIPHER_CTX * ctx)
Definition at line 211 of file evp_lib.c.
EVP_CIPHER_CTX_iv()
const unsigned char* EVP_CIPHER_CTX_iv (const EVP_CIPHER_CTX * ctx)
Definition at line 241 of file evp_lib.c.
EVP_CIPHER_CTX_iv_length()
int EVP_CIPHER_CTX_iv_length (const EVP_CIPHER_CTX * ctx)
Definition at line 231 of file evp_lib.c.
EVP_CIPHER_CTX_iv_noconst()
unsigned char* EVP_CIPHER_CTX_iv_noconst (EVP_CIPHER_CTX * ctx)
Definition at line 246 of file evp_lib.c.
Referenced by BLOCK_CIPHER_custom(), and if().
EVP_CIPHER_CTX_key_length()
int EVP_CIPHER_CTX_key_length (const EVP_CIPHER_CTX * ctx)
Definition at line 271 of file evp_lib.c.
Referenced by if().
EVP_CIPHER_CTX_new()
EVP_CIPHER_CTX* EVP_CIPHER_CTX_new (void)
Definition at line 39 of file evp_enc.c.
References OPENSSL_zalloc.
Referenced by CMAC_CTX_new(), and cms_RecipientInfo_pwri_crypt().
EVP_CIPHER_CTX_nid()
int EVP_CIPHER_CTX_nid (const EVP_CIPHER_CTX * ctx)
Definition at line 281 of file evp_lib.c.
EVP_CIPHER_CTX_num()
int EVP_CIPHER_CTX_num (const EVP_CIPHER_CTX * ctx)
Definition at line 256 of file evp_lib.c.
EVP_CIPHER_CTX_original_iv()
const unsigned char* EVP_CIPHER_CTX_original_iv (const EVP_CIPHER_CTX * ctx)
Definition at line 236 of file evp_lib.c.
EVP_CIPHER_CTX_rand_key()
int EVP_CIPHER_CTX_rand_key (EVP_CIPHER_CTX * ctx, unsigned char * key)
Definition at line 598 of file evp_enc.c.
References EVP_CIPH_RAND_KEY, EVP_CIPHER_CTX_ctrl(), EVP_CTRL_RAND_KEY, and RAND_bytes().
EVP_CIPHER_CTX_reset()
int EVP_CIPHER_CTX_reset (EVP_CIPHER_CTX * c)
Definition at line 20 of file evp_enc.c.
Referenced by EVP_CIPHER_CTX_free().
EVP_CIPHER_CTX_set_app_data()
void EVP_CIPHER_CTX_set_app_data (EVP_CIPHER_CTX * ctx, void * data)
Definition at line 206 of file evp_lib.c.
References data.
EVP_CIPHER_CTX_set_cipher_data()
void* EVP_CIPHER_CTX_set_cipher_data (EVP_CIPHER_CTX * ctx, void * cipher_data)
Definition at line 216 of file evp_lib.c.
EVP_CIPHER_CTX_set_flags()
void EVP_CIPHER_CTX_set_flags (EVP_CIPHER_CTX * ctx, int flags)
Definition at line 484 of file evp_lib.c.
References flags.
EVP_CIPHER_CTX_set_key_length()
int EVP_CIPHER_CTX_set_key_length (EVP_CIPHER_CTX * x, int keylen)
Definition at line 553 of file evp_enc.c.
EVP_CIPHER_CTX_set_num()
void EVP_CIPHER_CTX_set_num (EVP_CIPHER_CTX * ctx, int num)
Definition at line 261 of file evp_lib.c.
EVP_CIPHER_CTX_set_padding()
int EVP_CIPHER_CTX_set_padding (EVP_CIPHER_CTX * c, int pad)
Definition at line 567 of file evp_enc.c.
References EVP_CIPH_NO_PADDING.
Referenced by cms_RecipientInfo_pwri_crypt().
EVP_CIPHER_CTX_test_flags()
int EVP_CIPHER_CTX_test_flags (const EVP_CIPHER_CTX * ctx, int flags)
Definition at line 494 of file evp_lib.c.
EVP_CIPHER_do_all()
void EVP_CIPHER_do_all (void(*)(const EVP_CIPHER *ciph, const char *from, const char *to, void *x) fn, void * arg)
Definition at line 110 of file names.c.
References doall_cipher::arg, doall_cipher::fn, NULL, OBJ_NAME_do_all(), OBJ_NAME_TYPE_CIPHER_METH, OPENSSL_INIT_ADD_ALL_CIPHERS, and OPENSSL_init_crypto().
EVP_CIPHER_do_all_sorted()
void EVP_CIPHER_do_all_sorted (void(*)(const EVP_CIPHER *ciph, const char *from, const char *to, void *x) fn, void * arg)
Definition at line 124 of file names.c.
References doall_cipher::arg, doall_cipher::fn, NULL, OBJ_NAME_do_all_sorted(), OBJ_NAME_TYPE_CIPHER_METH, OPENSSL_INIT_ADD_ALL_CIPHERS, and OPENSSL_init_crypto().
EVP_CIPHER_flags()
unsigned long EVP_CIPHER_flags (const EVP_CIPHER * cipher)
Definition at line 196 of file evp_lib.c.
Referenced by tls1_cbc_remove_padding().
EVP_CIPHER_get_asn1_iv()
int EVP_CIPHER_get_asn1_iv (EVP_CIPHER_CTX * c, ASN1_TYPE * type)
Definition at line 75 of file evp_lib.c.
EVP_CIPHER_impl_ctx_size()
int EVP_CIPHER_impl_ctx_size (const EVP_CIPHER * cipher)
Definition at line 175 of file evp_lib.c.
EVP_CIPHER_iv_length()
int EVP_CIPHER_iv_length (const EVP_CIPHER * cipher)
Definition at line 226 of file evp_lib.c.
EVP_CIPHER_key_length()
int EVP_CIPHER_key_length (const EVP_CIPHER * cipher)
Definition at line 266 of file evp_lib.c.
EVP_CIPHER_meth_dup()
EVP_CIPHER* EVP_CIPHER_meth_dup (const EVP_CIPHER * cipher)
Definition at line 28 of file cmeth_lib.c.
EVP_CIPHER_meth_free()
void EVP_CIPHER_meth_free (EVP_CIPHER * cipher)
Definition at line 38 of file cmeth_lib.c.
EVP_CIPHER_meth_new()
EVP_CIPHER* EVP_CIPHER_meth_new (int cipher_type, int block_size, int key_len)
Definition at line 16 of file cmeth_lib.c.
EVP_CIPHER_meth_set_cleanup()
int EVP_CIPHER_meth_set_cleanup (EVP_CIPHER * cipher, int(*)(EVP_CIPHER_CTX *) cleanup)
Definition at line 81 of file cmeth_lib.c.
EVP_CIPHER_meth_set_ctrl()
int EVP_CIPHER_meth_set_ctrl (EVP_CIPHER * cipher, int(*)(EVP_CIPHER_CTX *, int type, int arg, void *ptr) ctrl)
Definition at line 104 of file cmeth_lib.c.
EVP_CIPHER_meth_set_do_cipher()
int EVP_CIPHER_meth_set_do_cipher (EVP_CIPHER * cipher, int(*)(EVP_CIPHER_CTX *ctx, unsigned char *out, const unsigned char *in, size_t inl) do_cipher)
Definition at line 71 of file cmeth_lib.c.
EVP_CIPHER_meth_set_flags()
int EVP_CIPHER_meth_set_flags (EVP_CIPHER * cipher, unsigned long flags)
Definition at line 49 of file cmeth_lib.c.
EVP_CIPHER_meth_set_get_asn1_params()
int EVP_CIPHER_meth_set_get_asn1_params (EVP_CIPHER * cipher, int(*)(EVP_CIPHER_CTX *, ASN1_TYPE *) get_asn1_parameters)
Definition at line 96 of file cmeth_lib.c.
EVP_CIPHER_meth_set_impl_ctx_size()
int EVP_CIPHER_meth_set_impl_ctx_size (EVP_CIPHER * cipher, int ctx_size)
Definition at line 55 of file cmeth_lib.c.
EVP_CIPHER_meth_set_init()
int EVP_CIPHER_meth_set_init (EVP_CIPHER * cipher, int(*)(EVP_CIPHER_CTX *ctx, const unsigned char *key, const unsigned char *iv, int enc) init)
Definition at line 61 of file cmeth_lib.c.
EVP_CIPHER_meth_set_iv_length()
int EVP_CIPHER_meth_set_iv_length (EVP_CIPHER * cipher, int iv_len)
Definition at line 43 of file cmeth_lib.c.
EVP_CIPHER_meth_set_set_asn1_params()
int EVP_CIPHER_meth_set_set_asn1_params (EVP_CIPHER * cipher, int(*)(EVP_CIPHER_CTX *, ASN1_TYPE *) set_asn1_parameters)
Definition at line 88 of file cmeth_lib.c.
EVP_CIPHER_nid()
int EVP_CIPHER_nid (const EVP_CIPHER * cipher)
Definition at line 276 of file evp_lib.c.
Referenced by EVP_CIPHER_type().
EVP_CIPHER_param_to_asn1()
int EVP_CIPHER_param_to_asn1 (EVP_CIPHER_CTX * c, ASN1_TYPE * type)
Definition at line 17 of file evp_lib.c.
EVP_CIPHER_set_asn1_iv()
int EVP_CIPHER_set_asn1_iv (EVP_CIPHER_CTX * c, ASN1_TYPE * type)
Definition at line 92 of file evp_lib.c.
EVP_CIPHER_type()
int EVP_CIPHER_type (const EVP_CIPHER * ctx)
Definition at line 106 of file evp_lib.c.
References ASN1_OBJECT_free(), EVP_CIPHER_nid(), nid, NID_aes_128_cfb1, NID_aes_128_cfb128, NID_aes_128_cfb8, NID_aes_192_cfb1, NID_aes_192_cfb128, NID_aes_192_cfb8, NID_aes_256_cfb1, NID_aes_256_cfb128, NID_aes_256_cfb8, NID_des_cfb1, NID_des_cfb64, NID_des_cfb8, NID_des_ede3_cfb1, NID_des_ede3_cfb64, NID_des_ede3_cfb8, NID_rc2_40_cbc, NID_rc2_64_cbc, NID_rc2_cbc, NID_rc4, NID_rc4_40, NID_undef, NULL, OBJ_get0_data(), and OBJ_nid2obj().
EVP_CipherFinal()
__owur int EVP_CipherFinal (EVP_CIPHER_CTX * ctx, unsigned char * outm, int * outl)
Definition at line 224 of file evp_enc.c.
EVP_CipherFinal_ex()
__owur int EVP_CipherFinal_ex (EVP_CIPHER_CTX * ctx, unsigned char * outm, int * outl)
Definition at line 216 of file evp_enc.c.
EVP_CipherInit()
__owur int EVP_CipherInit (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * cipher, const unsigned char * key, const unsigned char * iv, int enc)
Definition at line 50 of file evp_enc.c.
EVP_CipherInit_ex()
int EVP_CipherInit_ex (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * cipher, ENGINE * impl, const unsigned char * key, const unsigned char * iv, int enc)
Definition at line 57 of file evp_enc.c.
Referenced by cms_RecipientInfo_pwri_crypt().
EVP_CipherUpdate()
__owur int EVP_CipherUpdate (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl, const unsigned char * in, int inl)
Definition at line 207 of file evp_enc.c.
EVP_DecodeBlock()
int EVP_DecodeBlock (unsigned char * t, const unsigned char * f, int n)
Definition at line 351 of file encode.c.
Referenced by NETSCAPE_SPKI_b64_decode().
EVP_DecodeFinal()
int EVP_DecodeFinal (EVP_ENCODE_CTX * ctx, unsigned char * out, int * outl)
Definition at line 390 of file encode.c.
EVP_DecodeInit()
void EVP_DecodeInit (EVP_ENCODE_CTX * ctx)
Definition at line 218 of file encode.c.
EVP_DecodeUpdate()
int EVP_DecodeUpdate (EVP_ENCODE_CTX * ctx, unsigned char * out, int * outl, const unsigned char * in, int inl)
Definition at line 247 of file encode.c.
EVP_DecryptFinal()
__owur int EVP_DecryptFinal (EVP_CIPHER_CTX * ctx, unsigned char * outm, int * outl)
Definition at line 490 of file evp_enc.c.
EVP_DecryptFinal_ex()
int EVP_DecryptFinal_ex (EVP_CIPHER_CTX * ctx, unsigned char * outm, int * outl)
Definition at line 497 of file evp_enc.c.
EVP_DecryptInit()
__owur int EVP_DecryptInit (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * cipher, const unsigned char * key, const unsigned char * iv)
Definition at line 245 of file evp_enc.c.
EVP_DecryptInit_ex()
int EVP_DecryptInit_ex (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * cipher, ENGINE * impl, const unsigned char * key, const unsigned char * iv)
Definition at line 251 of file evp_enc.c.
EVP_DecryptUpdate()
int EVP_DecryptUpdate (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl, const unsigned char * in, int inl)
Definition at line 421 of file evp_enc.c.
EVP_des_cbc()
const EVP_CIPHER* EVP_des_cbc (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_des_cfb1()
const EVP_CIPHER* EVP_des_cfb1 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_des_cfb64()
const EVP_CIPHER* EVP_des_cfb64 (void)
Referenced by EVP_des_cfb().
EVP_des_cfb8()
const EVP_CIPHER* EVP_des_cfb8 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_des_ecb()
const EVP_CIPHER* EVP_des_ecb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_des_ede()
const EVP_CIPHER* EVP_des_ede (void)
Definition at line 300 of file e_des3.c.
Referenced by openssl_add_all_ciphers_int().
EVP_des_ede3()
const EVP_CIPHER* EVP_des_ede3 (void)
Definition at line 305 of file e_des3.c.
Referenced by openssl_add_all_ciphers_int().
EVP_des_ede3_cbc()
const EVP_CIPHER* EVP_des_ede3_cbc (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_des_ede3_cfb1()
const EVP_CIPHER* EVP_des_ede3_cfb1 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_des_ede3_cfb64()
const EVP_CIPHER* EVP_des_ede3_cfb64 (void)
Referenced by EVP_des_ede3_cfb().
EVP_des_ede3_cfb8()
const EVP_CIPHER* EVP_des_ede3_cfb8 (void)
Referenced by openssl_add_all_ciphers_int().
EVP_des_ede3_ecb()
const EVP_CIPHER* EVP_des_ede3_ecb (void)
EVP_des_ede3_ofb()
const EVP_CIPHER* EVP_des_ede3_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_des_ede3_wrap()
const EVP_CIPHER* EVP_des_ede3_wrap (void)
Definition at line 419 of file e_des3.c.
Referenced by openssl_add_all_ciphers_int().
EVP_des_ede_cbc()
const EVP_CIPHER* EVP_des_ede_cbc (void)
Referenced by openssl_add_all_ciphers_int().
EVP_des_ede_cfb64()
const EVP_CIPHER* EVP_des_ede_cfb64 (void)
Referenced by EVP_des_ede_cfb().
EVP_des_ede_ecb()
const EVP_CIPHER* EVP_des_ede_ecb (void)
EVP_des_ede_ofb()
const EVP_CIPHER* EVP_des_ede_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_des_ofb()
const EVP_CIPHER* EVP_des_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_desx_cbc()
const EVP_CIPHER* EVP_desx_cbc (void)
Definition at line 47 of file e_xcbc_d.c.
Referenced by openssl_add_all_ciphers_int().
EVP_Digest()
__owur int EVP_Digest (const void * data, size_t count, unsigned char * md, unsigned int * size, const EVP_MD * type, ENGINE * impl)
Definition at line 242 of file digest.c.
Referenced by X509_ocspid_print().
EVP_DigestFinal()
__owur int EVP_DigestFinal (EVP_MD_CTX * ctx, unsigned char * md, unsigned int * s)
Definition at line 152 of file digest.c.
EVP_DigestFinal_ex()
__owur int EVP_DigestFinal_ex (EVP_MD_CTX * ctx, unsigned char * md, unsigned int * s)
Definition at line 161 of file digest.c.
Referenced by CMS_SignerInfo_verify_content(), EVP_SignFinal(), EVP_VerifyFinal(), PKCS7_signatureVerify(), and SRP_Calc_x().
EVP_DigestInit()
__owur int EVP_DigestInit (EVP_MD_CTX * ctx, const EVP_MD * type)
Definition at line 55 of file digest.c.
References EVP_DigestInit_ex(), EVP_MD_CTX_reset(), and NULL.
EVP_DigestInit_ex()
__owur int EVP_DigestInit_ex (EVP_MD_CTX * ctx, const EVP_MD * type, ENGINE * impl)
Definition at line 61 of file digest.c.
References ENGINE_finish(), ENGINE_get_digest(), ENGINE_get_digest_engine(), ENGINE_init(), ERR_R_MALLOC_FAILURE, EVP_F_EVP_DIGESTINIT_EX, EVP_MD_CTX_clear_flags(), EVP_MD_CTX_FLAG_CLEANED, EVP_MD_CTX_FLAG_NO_INIT, EVP_PKEY_CTRL_DIGESTINIT, EVP_PKEY_CTX_ctrl(), EVP_PKEY_OP_TYPE_SIG, EVP_R_INITIALIZATION_ERROR, EVP_R_NO_DIGEST_SET, EVPerr, impl, NULL, OPENSSL_clear_free, OPENSSL_zalloc, and type.
Referenced by EVP_DigestInit(), PEM_SignInit(), and SRP_Calc_x().
EVP_DigestSignFinal()
__owur int EVP_DigestSignFinal (EVP_MD_CTX * ctx, unsigned char * sigret, size_t * siglen)
Definition at line 79 of file m_sigver.c.
References EVP_MD_CTX_FLAG_FINALISE, EVP_PKEY_CTX_dup(), EVP_PKEY_CTX_free(), and EVP_PKEY_FLAG_SIGCTX_CUSTOM.
Referenced by ASN1_item_sign_ctx().
EVP_DigestSignInit()
int EVP_DigestSignInit (EVP_MD_CTX * ctx, EVP_PKEY_CTX ** pctx, const EVP_MD * type, ENGINE * e, EVP_PKEY * pkey)
Definition at line 67 of file m_sigver.c.
Referenced by ASN1_item_sign().
EVP_DigestUpdate()
__owur int EVP_DigestUpdate (EVP_MD_CTX * ctx, const void * d, size_t cnt)
Definition at line 146 of file digest.c.
Referenced by HMAC_Update(), PEM_SignUpdate(), and SRP_Calc_x().
EVP_DigestVerifyFinal()
__owur int EVP_DigestVerifyFinal (EVP_MD_CTX * ctx, const unsigned char * sig, size_t siglen)
Definition at line 138 of file m_sigver.c.
EVP_DigestVerifyInit()
__owur int EVP_DigestVerifyInit (EVP_MD_CTX * ctx, EVP_PKEY_CTX ** pctx, const EVP_MD * type, ENGINE * e, EVP_PKEY * pkey)
Definition at line 73 of file m_sigver.c.
EVP_enc_null()
const EVP_CIPHER* EVP_enc_null (void)
Definition at line 33 of file e_null.c.
EVP_ENCODE_CTX_copy()
int EVP_ENCODE_CTX_copy (EVP_ENCODE_CTX * dctx, EVP_ENCODE_CTX * sctx)
Definition at line 106 of file encode.c.
EVP_ENCODE_CTX_free()
void EVP_ENCODE_CTX_free (EVP_ENCODE_CTX * ctx)
Definition at line 101 of file encode.c.
References OPENSSL_free.
EVP_ENCODE_CTX_new()
EVP_ENCODE_CTX* EVP_ENCODE_CTX_new (void)
Definition at line 96 of file encode.c.
References OPENSSL_zalloc.
Referenced by PEM_read_bio().
EVP_ENCODE_CTX_num()
int EVP_ENCODE_CTX_num (EVP_ENCODE_CTX * ctx)
Definition at line 113 of file encode.c.
EVP_EncodeBlock()
int EVP_EncodeBlock (unsigned char * t, const unsigned char * f, int n)
Definition at line 187 of file encode.c.
Referenced by NETSCAPE_SPKI_b64_encode().
EVP_EncodeFinal()
void EVP_EncodeFinal (EVP_ENCODE_CTX * ctx, unsigned char * out, int * outl)
Definition at line 174 of file encode.c.
EVP_EncodeInit()
void EVP_EncodeInit (EVP_ENCODE_CTX * ctx)
Definition at line 118 of file encode.c.
EVP_EncodeUpdate()
int EVP_EncodeUpdate (EVP_ENCODE_CTX * ctx, unsigned char * out, int * outl, const unsigned char * in, int inl)
Definition at line 125 of file encode.c.
EVP_EncryptFinal()
int EVP_EncryptFinal (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl)
Definition at line 372 of file evp_enc.c.
EVP_EncryptFinal_ex()
int EVP_EncryptFinal_ex (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl)
Definition at line 379 of file evp_enc.c.
EVP_EncryptInit()
__owur int EVP_EncryptInit (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * cipher, const unsigned char * key, const unsigned char * iv)
Definition at line 232 of file evp_enc.c.
EVP_EncryptInit_ex()
int EVP_EncryptInit_ex (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * cipher, ENGINE * impl, const unsigned char * key, const unsigned char * iv)
Definition at line 238 of file evp_enc.c.
Referenced by CMAC_resume().
EVP_EncryptUpdate()
int EVP_EncryptUpdate (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl, const unsigned char * in, int inl)
Definition at line 295 of file evp_enc.c.
EVP_get_cipherbyname()
const EVP_CIPHER* EVP_get_cipherbyname (const char * name)
Definition at line 58 of file names.c.
References NULL, OBJ_NAME_get(), OBJ_NAME_TYPE_CIPHER_METH, OPENSSL_INIT_ADD_ALL_CIPHERS, and OPENSSL_init_crypto().
Referenced by opt_cipher().
EVP_get_digestbyname()
const EVP_MD* EVP_get_digestbyname (const char * name)
Definition at line 69 of file names.c.
References NULL, OBJ_NAME_get(), OBJ_NAME_TYPE_MD_METH, OPENSSL_INIT_ADD_ALL_DIGESTS, and OPENSSL_init_crypto().
Referenced by opt_md().
EVP_get_pw_prompt()
char* EVP_get_pw_prompt (void)
Definition at line 31 of file evp_key.c.
EVP_idea_cbc()
const EVP_CIPHER* EVP_idea_cbc (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_idea_cfb64()
const EVP_CIPHER* EVP_idea_cfb64 (void)
Referenced by EVP_idea_cfb().
EVP_idea_ecb()
const EVP_CIPHER* EVP_idea_ecb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_idea_ofb()
const EVP_CIPHER* EVP_idea_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_md2()
const EVP_MD* EVP_md2 (void)
Definition at line 52 of file m_md2.c.
EVP_md4()
const EVP_MD* EVP_md4 (void)
Definition at line 51 of file m_md4.c.
Referenced by openssl_add_all_digests_int().
EVP_md5()
const EVP_MD* EVP_md5 (void)
Definition at line 51 of file m_md5.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_digests_int().
EVP_md5_sha1()
const EVP_MD* EVP_md5_sha1 (void)
Definition at line 138 of file m_md5_sha1.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_digests_int().
EVP_MD_block_size()
int EVP_MD_block_size (const EVP_MD * md)
Definition at line 286 of file evp_lib.c.
EVP_MD_CTX_clear_flags()
void EVP_MD_CTX_clear_flags (EVP_MD_CTX * ctx, int flags)
Definition at line 474 of file evp_lib.c.
Referenced by EVP_DigestInit_ex().
EVP_MD_CTX_copy()
__owur int EVP_MD_CTX_copy (EVP_MD_CTX * out, const EVP_MD_CTX * in)
Definition at line 177 of file digest.c.
EVP_MD_CTX_copy_ex()
__owur int EVP_MD_CTX_copy_ex (EVP_MD_CTX * out, const EVP_MD_CTX * in)
Definition at line 183 of file digest.c.
Referenced by cms_DigestAlgorithm_find_ctx(), EVP_SignFinal(), EVP_VerifyFinal(), HMAC_CTX_copy(), and PKCS7_signatureVerify().
EVP_MD_CTX_ctrl()
int EVP_MD_CTX_ctrl (EVP_MD_CTX * ctx, int cmd, int p1, void * p2)
Definition at line 260 of file digest.c.
EVP_MD_CTX_free()
void EVP_MD_CTX_free (EVP_MD_CTX * ctx)
Definition at line 49 of file digest.c.
References EVP_MD_CTX_reset(), and OPENSSL_free.
Referenced by ASN1_item_sign(), ASN1_sign(), dtls1_hm_fragment_free(), EVP_SignFinal(), EVP_VerifyFinal(), PKCS7_signatureVerify(), SRP_Calc_x(), ssl3_free_digest_list(), and ssl_clear_hash_ctx().
EVP_MD_CTX_md()
const EVP_MD* EVP_MD_CTX_md (const EVP_MD_CTX * ctx)
Definition at line 439 of file evp_lib.c.
References NULL.
Referenced by ASN1_item_sign_ctx(), cms_DigestAlgorithm_find_ctx(), EVP_SignFinal(), EVP_VerifyFinal(), PKCS7_signatureVerify(), and ssl3_enc().
EVP_MD_CTX_md_data()
void* EVP_MD_CTX_md_data (const EVP_MD_CTX * ctx)
Definition at line 451 of file evp_lib.c.
EVP_MD_CTX_new()
EVP_MD_CTX* EVP_MD_CTX_new (void)
Definition at line 44 of file digest.c.
References OPENSSL_zalloc.
Referenced by ASN1_item_sign(), ASN1_sign(), ASN1_verify(), CMS_SignerInfo_verify_content(), do_X509_CRL_sign(), do_X509_REQ_sign(), do_X509_sign(), EVP_SignFinal(), EVP_VerifyFinal(), PKCS7_dataFinal(), PKCS7_signatureVerify(), SRP_Calc_x(), tls_construct_server_key_exchange(), and X509_NAME_hash_old().
EVP_MD_CTX_pkey_ctx()
EVP_PKEY_CTX* EVP_MD_CTX_pkey_ctx (const EVP_MD_CTX * ctx)
Definition at line 446 of file evp_lib.c.
Referenced by ASN1_item_sign_ctx().
EVP_MD_CTX_reset()
int EVP_MD_CTX_reset (EVP_MD_CTX * ctx)
Definition at line 19 of file digest.c.
References ENGINE_finish(), EVP_MD_CTX_FLAG_CLEANED, EVP_MD_CTX_FLAG_REUSE, EVP_MD_CTX_test_flags(), EVP_PKEY_CTX_free(), NULL, OPENSSL_cleanse(), and OPENSSL_clear_free.
Referenced by EVP_DigestInit(), and EVP_MD_CTX_free().
EVP_MD_CTX_set_flags()
void EVP_MD_CTX_set_flags (EVP_MD_CTX * ctx, int flags)
Definition at line 469 of file evp_lib.c.
References flags.
Referenced by HMAC_CTX_set_flags().
EVP_MD_CTX_set_update_fn()
void EVP_MD_CTX_set_update_fn (EVP_MD_CTX * ctx, int(*)(EVP_MD_CTX *ctx, const void *data, size_t count) update)
Definition at line 462 of file evp_lib.c.
EVP_MD_CTX_test_flags()
int EVP_MD_CTX_test_flags (const EVP_MD_CTX * ctx, int flags)
Definition at line 479 of file evp_lib.c.
Referenced by EVP_MD_CTX_reset(), EVP_SignFinal(), and EVP_VerifyFinal().
EVP_MD_do_all()
void EVP_MD_do_all (void(*)(const EVP_MD *ciph, const char *from, const char *to, void *x) fn, void * arg)
EVP_MD_do_all_sorted()
void EVP_MD_do_all_sorted (void(*)(const EVP_MD *ciph, const char *from, const char *to, void *x) fn, void * arg)
EVP_MD_flags()
unsigned long EVP_MD_flags (const EVP_MD * md)
Definition at line 310 of file evp_lib.c.
EVP_MD_meth_dup()
EVP_MD* EVP_MD_meth_dup (const EVP_MD * md)
Definition at line 325 of file evp_lib.c.
EVP_MD_meth_free()
void EVP_MD_meth_free (EVP_MD * md)
Definition at line 333 of file evp_lib.c.
EVP_MD_meth_get_app_datasize()
int EVP_MD_meth_get_app_datasize (const EVP_MD * md)
Definition at line 401 of file evp_lib.c.
EVP_MD_meth_get_flags()
unsigned long EVP_MD_meth_get_flags (const EVP_MD * md)
Definition at line 405 of file evp_lib.c.
EVP_MD_meth_get_input_blocksize()
int EVP_MD_meth_get_input_blocksize (const EVP_MD * md)
Definition at line 393 of file evp_lib.c.
EVP_MD_meth_get_result_size()
int EVP_MD_meth_get_result_size (const EVP_MD * md)
Definition at line 397 of file evp_lib.c.
EVP_MD_meth_new()
EVP_MD* EVP_MD_meth_new (int md_type, int pkey_type)
Definition at line 315 of file evp_lib.c.
EVP_MD_meth_set_app_datasize()
int EVP_MD_meth_set_app_datasize (EVP_MD * md, int datasize)
Definition at line 347 of file evp_lib.c.
EVP_MD_meth_set_cleanup()
int EVP_MD_meth_set_cleanup (EVP_MD * md, int(*)(EVP_MD_CTX *ctx) cleanup)
Definition at line 381 of file evp_lib.c.
EVP_MD_meth_set_copy()
int EVP_MD_meth_set_copy (EVP_MD * md, int(*)(EVP_MD_CTX *to, const EVP_MD_CTX *from) copy)
Definition at line 375 of file evp_lib.c.
EVP_MD_meth_set_ctrl()
int EVP_MD_meth_set_ctrl (EVP_MD * md, int(*)(EVP_MD_CTX *ctx, int cmd, int p1, void *p2) ctrl)
Definition at line 386 of file evp_lib.c.
EVP_MD_meth_set_final()
int EVP_MD_meth_set_final (EVP_MD * md, int(*)(EVP_MD_CTX *ctx, unsigned char *md) final)
Definition at line 369 of file evp_lib.c.
EVP_MD_meth_set_flags()
int EVP_MD_meth_set_flags (EVP_MD * md, unsigned long flags)
Definition at line 352 of file evp_lib.c.
EVP_MD_meth_set_init()
int EVP_MD_meth_set_init (EVP_MD * md, int(*)(EVP_MD_CTX *ctx) init)
Definition at line 357 of file evp_lib.c.
EVP_MD_meth_set_input_blocksize()
int EVP_MD_meth_set_input_blocksize (EVP_MD * md, int blocksize)
Definition at line 337 of file evp_lib.c.
EVP_MD_meth_set_result_size()
int EVP_MD_meth_set_result_size (EVP_MD * md, int resultsize)
Definition at line 342 of file evp_lib.c.
EVP_MD_meth_set_update()
int EVP_MD_meth_set_update (EVP_MD * md, int(*)(EVP_MD_CTX *ctx, const void *data, size_t count) update)
Definition at line 362 of file evp_lib.c.
EVP_md_null()
const EVP_MD* EVP_md_null (void)
Definition at line 46 of file m_null.c.
EVP_MD_pkey_type()
int EVP_MD_pkey_type (const EVP_MD * md)
Definition at line 296 of file evp_lib.c.
Referenced by cms_DigestAlgorithm_find_ctx(), and PKCS7_signatureVerify().
EVP_MD_size()
int EVP_MD_size (const EVP_MD * md)
Definition at line 301 of file evp_lib.c.
Referenced by HMAC_size().
EVP_MD_type()
int EVP_MD_type (const EVP_MD * md)
Definition at line 291 of file evp_lib.c.
Referenced by PKCS12_setup_mac().
EVP_mdc2()
const EVP_MD* EVP_mdc2 (void)
Definition at line 51 of file m_mdc2.c.
Referenced by openssl_add_all_digests_int().
EVP_OpenFinal()
__owur int EVP_OpenFinal (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl)
Definition at line 64 of file p_open.c.
EVP_OpenInit()
__owur int EVP_OpenInit (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * type, const unsigned char * ek, int ekl, const unsigned char * iv, EVP_PKEY * priv)
Definition at line 21 of file p_open.c.
EVP_PBE_alg_add()
int EVP_PBE_alg_add (int nid, const EVP_CIPHER * cipher, const EVP_MD * md, EVP_PBE_KEYGEN * keygen)
Definition at line 187 of file evp_pbe.c.
EVP_PBE_alg_add_type()
int EVP_PBE_alg_add_type (int pbe_type, int pbe_nid, int cipher_nid, int md_nid, EVP_PBE_KEYGEN * keygen)
Definition at line 156 of file evp_pbe.c.
References NULL.
EVP_PBE_CipherInit()
int EVP_PBE_CipherInit (ASN1_OBJECT * pbe_obj, const char * pass, int passlen, ASN1_TYPE * param, EVP_CIPHER_CTX * ctx, int en_de)
Definition at line 80 of file evp_pbe.c.
Referenced by cms_RecipientInfo_pwri_crypt().
EVP_PBE_cleanup()
void EVP_PBE_cleanup (void)
Definition at line 240 of file evp_pbe.c.
Referenced by evp_cleanup_int().
EVP_PBE_find()
int EVP_PBE_find (int type, int pbe_nid, int * pcnid, int * pmnid, EVP_PBE_KEYGEN ** pkeygen)
Definition at line 205 of file evp_pbe.c.
References NID_undef, NULL, OSSL_NELEM, EVP_PBE_CTL::pbe_nid, and type.
EVP_PBE_get()
int EVP_PBE_get (int * ptype, int * ppbe_nid, size_t num)
Definition at line 246 of file evp_pbe.c.
References OSSL_NELEM.
EVP_PBE_scrypt()
int EVP_PBE_scrypt (const char * pass, size_t passlen, const unsigned char * salt, size_t saltlen, uint64_t N, uint64_t r, uint64_t p, uint64_t maxmem, unsigned char * key, size_t keylen)
Definition at line 158 of file scrypt.c.
References B, EVP_F_EVP_PBE_SCRYPT, EVP_R_MEMORY_LIMIT_EXCEEDED, EVP_sha256(), EVPerr, LOG2_UINT64_MAX, NULL, OPENSSL_malloc, PKCS5_PBKDF2_HMAC(), SCRYPT_MAX_MEM, SCRYPT_PR_MAX, SIZE_MAX, UINT64_MAX, and X.
EVP_PKEY_asn1_add0()
int EVP_PKEY_asn1_add0 (const EVP_PKEY_ASN1_METHOD * ameth)
Definition at line 137 of file ameth_lib.c.
References NULL.
Referenced by EVP_PKEY_asn1_add_alias().
EVP_PKEY_asn1_add_alias()
int EVP_PKEY_asn1_add_alias (int to, int from)
Definition at line 150 of file ameth_lib.c.
References ASN1_PKEY_ALIAS, EVP_PKEY_asn1_add0(), EVP_PKEY_asn1_free(), EVP_PKEY_asn1_new(), and NULL.
EVP_PKEY_asn1_copy()
void EVP_PKEY_asn1_copy (EVP_PKEY_ASN1_METHOD * dst, const EVP_PKEY_ASN1_METHOD * src)
Definition at line 221 of file ameth_lib.c.
EVP_PKEY_asn1_find()
const EVP_PKEY_ASN1_METHOD* EVP_PKEY_asn1_find (ENGINE ** pe, int type)
Definition at line 77 of file ameth_lib.c.
References t.
Referenced by X509_signature_print().
EVP_PKEY_asn1_find_str()
const EVP_PKEY_ASN1_METHOD* EVP_PKEY_asn1_find_str (ENGINE ** pe, const char * str, int len)
Definition at line 102 of file ameth_lib.c.
References ASN1_PKEY_ALIAS, e, ENGINE_free(), ENGINE_init(), ENGINE_pkey_asn1_find_str(), EVP_PKEY_asn1_get0(), EVP_PKEY_asn1_get_count(), and NULL.
EVP_PKEY_asn1_free()
void EVP_PKEY_asn1_free (EVP_PKEY_ASN1_METHOD * ameth)
Definition at line 255 of file ameth_lib.c.
References ASN1_PKEY_DYNAMIC, and OPENSSL_free.
Referenced by engine_pkey_asn1_meths_free(), EVP_PKEY_asn1_add_alias(), and EVP_PKEY_asn1_new().
EVP_PKEY_asn1_get0()
const EVP_PKEY_ASN1_METHOD* EVP_PKEY_asn1_get0 (int idx)
Definition at line 43 of file ameth_lib.c.
Referenced by EVP_PKEY_asn1_find_str().
EVP_PKEY_asn1_get0_info()
int EVP_PKEY_asn1_get0_info (int * ppkey_id, int * pkey_base_id, int * ppkey_flags, const char ** pinfo, const char ** ppem_str, const EVP_PKEY_ASN1_METHOD * ameth)
Definition at line 164 of file ameth_lib.c.
EVP_PKEY_asn1_get_count()
int EVP_PKEY_asn1_get_count (void)
Definition at line 35 of file ameth_lib.c.
References OSSL_NELEM.
Referenced by EVP_PKEY_asn1_find_str().
EVP_PKEY_asn1_new()
EVP_PKEY_ASN1_METHOD* EVP_PKEY_asn1_new (int id, int flags, const char * pem_str, const char * info)
Definition at line 189 of file ameth_lib.c.
References ASN1_PKEY_DYNAMIC, EVP_PKEY_asn1_free(), NULL, OPENSSL_strdup, and OPENSSL_zalloc.
Referenced by EVP_PKEY_asn1_add_alias().
EVP_PKEY_asn1_set_ctrl()
void EVP_PKEY_asn1_set_ctrl (EVP_PKEY_ASN1_METHOD * ameth, int(*)(EVP_PKEY *pkey, int op, long arg1, void *arg2) pkey_ctrl)
Definition at line 330 of file ameth_lib.c.
EVP_PKEY_asn1_set_free()
void EVP_PKEY_asn1_set_free (EVP_PKEY_ASN1_METHOD * ameth, void(*)(EVP_PKEY *pkey) pkey_free)
Definition at line 324 of file ameth_lib.c.
EVP_PKEY_asn1_set_item()
void EVP_PKEY_asn1_set_item (EVP_PKEY_ASN1_METHOD * ameth, int(*)(EVP_MD_CTX *ctx, const ASN1_ITEM *it, void *asn, X509_ALGOR *a, ASN1_BIT_STRING *sig, EVP_PKEY *pkey) item_verify, int(*)(EVP_MD_CTX *ctx, const ASN1_ITEM *it, void *asn, X509_ALGOR *alg1, X509_ALGOR *alg2, ASN1_BIT_STRING *sig) item_sign)
Definition at line 344 of file ameth_lib.c.
EVP_PKEY_asn1_set_param()
void EVP_PKEY_asn1_set_param (EVP_PKEY_ASN1_METHOD * ameth, int(*)(EVP_PKEY *pkey, const unsigned char **pder, int derlen) param_decode, int(*)(const EVP_PKEY *pkey, unsigned char **pder) param_encode, int(*)(const EVP_PKEY *pk) param_missing, int(*)(EVP_PKEY *to, const EVP_PKEY *from) param_copy, int(*)(const EVP_PKEY *a, const EVP_PKEY *b) param_cmp, int(*)(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx) param_print)
Definition at line 301 of file ameth_lib.c.
EVP_PKEY_asn1_set_private()
void EVP_PKEY_asn1_set_private (EVP_PKEY_ASN1_METHOD * ameth, int(*)(EVP_PKEY *pk, const PKCS8_PRIV_KEY_INFO *p8inf) priv_decode, int(*)(PKCS8_PRIV_KEY_INFO *p8, const EVP_PKEY *pk) priv_encode, int(*)(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx) priv_print)
Definition at line 285 of file ameth_lib.c.
EVP_PKEY_asn1_set_public()
void EVP_PKEY_asn1_set_public (EVP_PKEY_ASN1_METHOD * ameth, int(*)(EVP_PKEY *pk, X509_PUBKEY *pub) pub_decode, int(*)(X509_PUBKEY *pub, const EVP_PKEY *pk) pub_encode, int(*)(const EVP_PKEY *a, const EVP_PKEY *b) pub_cmp, int(*)(BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx) pub_print, int(*)(const EVP_PKEY *pk) pkey_size, int(*)(const EVP_PKEY *pk) pkey_bits)
Definition at line 264 of file ameth_lib.c.
EVP_PKEY_asn1_set_security_bits()
void EVP_PKEY_asn1_set_security_bits (EVP_PKEY_ASN1_METHOD * ameth, int(*)(const EVP_PKEY *pk) pkey_security_bits)
Definition at line 337 of file ameth_lib.c.
EVP_PKEY_assign()
int EVP_PKEY_assign (EVP_PKEY * pkey, int type, void * key)
Definition at line 227 of file p_lib.c.
References EVP_PKEY_set_type(), key, and NULL.
EVP_PKEY_base_id()
int EVP_PKEY_base_id (const EVP_PKEY * pkey)
Definition at line 412 of file p_lib.c.
References EVP_PKEY_type().
EVP_PKEY_bits()
int EVP_PKEY_bits (const EVP_PKEY * pkey)
Definition at line 27 of file p_lib.c.
Referenced by ssl_print_tmp_key().
EVP_PKEY_cmp()
int EVP_PKEY_cmp (const EVP_PKEY * a, const EVP_PKEY * b)
Definition at line 117 of file p_lib.c.
EVP_PKEY_cmp_parameters()
int EVP_PKEY_cmp_parameters (const EVP_PKEY * a, const EVP_PKEY * b)
Definition at line 108 of file p_lib.c.
Referenced by EVP_PKEY_copy_parameters().
EVP_PKEY_copy_parameters()
int EVP_PKEY_copy_parameters (EVP_PKEY * to, const EVP_PKEY * from)
Definition at line 73 of file p_lib.c.
References EVP_F_EVP_PKEY_COPY_PARAMETERS, EVP_PKEY_cmp_parameters(), EVP_PKEY_missing_parameters(), EVP_PKEY_NONE, EVP_PKEY_set_type(), EVP_R_DIFFERENT_KEY_TYPES, EVP_R_DIFFERENT_PARAMETERS, EVP_R_MISSING_PARAMETERS, and EVPerr.
EVP_PKEY_CTX_ctrl()
int EVP_PKEY_CTX_ctrl (EVP_PKEY_CTX * ctx, int keytype, int optype, int cmd, int p1, void * p2)
Definition at line 304 of file pmeth_lib.c.
Referenced by EVP_DigestInit_ex(), and RSA_pkey_ctx_ctrl().
EVP_PKEY_CTX_ctrl_str()
int EVP_PKEY_CTX_ctrl_str (EVP_PKEY_CTX * ctx, const char * type, const char * value)
Definition at line 334 of file pmeth_lib.c.
References EVP_F_EVP_PKEY_CTX_CTRL_STR, EVP_PKEY_CTRL_MD, EVP_PKEY_CTX_md(), EVP_PKEY_OP_TYPE_SIG, EVP_R_COMMAND_NOT_SUPPORTED, and EVPerr.
Referenced by pkey_ctrl_string().
EVP_PKEY_CTX_dup()
EVP_PKEY_CTX* EVP_PKEY_CTX_dup (EVP_PKEY_CTX * ctx)
Definition at line 233 of file pmeth_lib.c.
Referenced by EVP_DigestSignFinal().
EVP_PKEY_CTX_free()
void EVP_PKEY_CTX_free (EVP_PKEY_CTX * ctx)
Definition at line 290 of file pmeth_lib.c.
References ENGINE_finish(), EVP_PKEY_free(), NULL, and OPENSSL_free.
Referenced by EVP_DigestSignFinal(), EVP_MD_CTX_reset(), EVP_PKEY_new_mac_key(), EVP_SignFinal(), and EVP_VerifyFinal().
EVP_PKEY_CTX_get0_peerkey()
EVP_PKEY* EVP_PKEY_CTX_get0_peerkey (EVP_PKEY_CTX * ctx)
Definition at line 412 of file pmeth_lib.c.
EVP_PKEY_CTX_get0_pkey()
EVP_PKEY* EVP_PKEY_CTX_get0_pkey (EVP_PKEY_CTX * ctx)
Definition at line 407 of file pmeth_lib.c.
Referenced by ASN1_item_sign_ctx().
EVP_PKEY_CTX_get_app_data()
void* EVP_PKEY_CTX_get_app_data (EVP_PKEY_CTX * ctx)
Definition at line 422 of file pmeth_lib.c.
EVP_PKEY_CTX_get_cb()
EVP_PKEY_gen_cb* EVP_PKEY_CTX_get_cb (EVP_PKEY_CTX * ctx)
Definition at line 120 of file pmeth_gn.c.
EVP_PKEY_CTX_get_data()
void* EVP_PKEY_CTX_get_data (EVP_PKEY_CTX * ctx)
Definition at line 402 of file pmeth_lib.c.
EVP_PKEY_CTX_get_keygen_info()
int EVP_PKEY_CTX_get_keygen_info (EVP_PKEY_CTX * ctx, int idx)
Definition at line 143 of file pmeth_gn.c.
EVP_PKEY_CTX_get_operation()
int EVP_PKEY_CTX_get_operation (EVP_PKEY_CTX * ctx)
Definition at line 386 of file pmeth_lib.c.
EVP_PKEY_CTX_hex2ctrl()
int EVP_PKEY_CTX_hex2ctrl (EVP_PKEY_CTX * ctx, int cmd, const char * hex)
Definition at line 359 of file pmeth_lib.c.
References NULL, OPENSSL_free, and OPENSSL_hexstr2buf().
EVP_PKEY_CTX_md()
int EVP_PKEY_CTX_md (EVP_PKEY_CTX * ctx, int optype, int cmd, const char * md)
Definition at line 375 of file pmeth_lib.c.
Referenced by EVP_PKEY_CTX_ctrl_str().
EVP_PKEY_CTX_new()
EVP_PKEY_CTX* EVP_PKEY_CTX_new (EVP_PKEY * pkey, ENGINE * e)
Definition at line 223 of file pmeth_lib.c.
Referenced by EVP_SignFinal(), and EVP_VerifyFinal().
EVP_PKEY_CTX_new_id()
EVP_PKEY_CTX* EVP_PKEY_CTX_new_id (int id, ENGINE * e)
Definition at line 228 of file pmeth_lib.c.
Referenced by EVP_PKEY_new_mac_key().
EVP_PKEY_CTX_set0_keygen_info()
void EVP_PKEY_CTX_set0_keygen_info (EVP_PKEY_CTX * ctx, int * dat, int datlen)
Definition at line 391 of file pmeth_lib.c.
EVP_PKEY_CTX_set_app_data()
void EVP_PKEY_CTX_set_app_data (EVP_PKEY_CTX * ctx, void * data)
Definition at line 417 of file pmeth_lib.c.
References data.
EVP_PKEY_CTX_set_cb()
void EVP_PKEY_CTX_set_cb (EVP_PKEY_CTX * ctx, EVP_PKEY_gen_cb * cb)
Definition at line 115 of file pmeth_gn.c.
References cb.
EVP_PKEY_CTX_set_data()
void EVP_PKEY_CTX_set_data (EVP_PKEY_CTX * ctx, void * data)
Definition at line 397 of file pmeth_lib.c.
References data.
EVP_PKEY_CTX_str2ctrl()
int EVP_PKEY_CTX_str2ctrl (EVP_PKEY_CTX * ctx, int cmd, const char * str)
Definition at line 349 of file pmeth_lib.c.
References len.
EVP_PKEY_decrypt()
int EVP_PKEY_decrypt (EVP_PKEY_CTX * ctx, unsigned char * out, size_t * outlen, const unsigned char * in, size_t inlen)
Definition at line 187 of file pmeth_fn.c.
EVP_PKEY_decrypt_init()
int EVP_PKEY_decrypt_init (EVP_PKEY_CTX * ctx)
Definition at line 170 of file pmeth_fn.c.
EVP_PKEY_decrypt_old()
int EVP_PKEY_decrypt_old (unsigned char * dec_key, const unsigned char * enc_key, int enc_key_len, EVP_PKEY * private_key)
Definition at line 17 of file p_dec.c.
EVP_PKEY_derive()
int EVP_PKEY_derive (EVP_PKEY_CTX * ctx, unsigned char * key, size_t * keylen)
Definition at line 284 of file pmeth_fn.c.
References EVP_F_EVP_PKEY_DERIVE, EVP_PKEY_OP_DERIVE, EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE, EVP_R_OPERATON_NOT_INITIALIZED, EVPerr, and M_check_autoarg.
EVP_PKEY_derive_init()
int EVP_PKEY_derive_init (EVP_PKEY_CTX * ctx)
Definition at line 204 of file pmeth_fn.c.
EVP_PKEY_derive_set_peer()
int EVP_PKEY_derive_set_peer (EVP_PKEY_CTX * ctx, EVP_PKEY * peer)
Definition at line 221 of file pmeth_fn.c.
EVP_PKEY_encrypt()
int EVP_PKEY_encrypt (EVP_PKEY_CTX * ctx, unsigned char * out, size_t * outlen, const unsigned char * in, size_t inlen)
Definition at line 153 of file pmeth_fn.c.
EVP_PKEY_encrypt_init()
int EVP_PKEY_encrypt_init (EVP_PKEY_CTX * ctx)
Definition at line 136 of file pmeth_fn.c.
EVP_PKEY_encrypt_old()
int EVP_PKEY_encrypt_old (unsigned char * enc_key, const unsigned char * key, int key_len, EVP_PKEY * pub_key)
Definition at line 17 of file p_enc.c.
EVP_PKEY_free()
void EVP_PKEY_free (EVP_PKEY * pkey)
Definition at line 417 of file p_lib.c.
References CRYPTO_DOWN_REF, NULL, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by CMS_SignerInfo_set1_signer_cert(), CTLOG_free(), EVP_PKCS82PKEY(), EVP_PKEY_CTX_free(), SCT_CTX_free(), ssl3_clear(), ssl3_ctx_ctrl(), ssl3_free(), ssl_excert_free(), ssl_print_tmp_key(), tls_construct_stoc_key_share(), TS_RESP_CTX_free(), TS_RESP_CTX_set_signer_key(), and X509_PKEY_free().
EVP_PKEY_get0()
void* EVP_PKEY_get0 (const EVP_PKEY * pkey)
Definition at line 235 of file p_lib.c.
Referenced by EVP_PKEY_get0_hmac(), EVP_PKEY_get0_poly1305(), and EVP_PKEY_get0_siphash().
EVP_PKEY_get0_asn1()
const EVP_PKEY_ASN1_METHOD* EVP_PKEY_get0_asn1 (const EVP_PKEY * pkey)
Definition at line 184 of file ameth_lib.c.
EVP_PKEY_get0_DH()
struct dh_st* EVP_PKEY_get0_DH (EVP_PKEY * pkey)
Definition at line 373 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_DH, EVP_PKEY_DH, EVP_PKEY_DHX, EVP_R_EXPECTING_A_DH_KEY, EVPerr, and NULL.
EVP_PKEY_get0_DSA()
struct dsa_st* EVP_PKEY_get0_DSA (EVP_PKEY * pkey)
Definition at line 317 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_DSA, EVP_PKEY_DSA, EVP_R_EXPECTING_A_DSA_KEY, EVPerr, and NULL.
Referenced by i2d_PublicKey().
EVP_PKEY_get0_EC_KEY()
struct ec_key_st* EVP_PKEY_get0_EC_KEY (EVP_PKEY * pkey)
Definition at line 345 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_EC_KEY, EVP_PKEY_EC, EVP_R_EXPECTING_A_EC_KEY, EVPerr, and NULL.
Referenced by i2d_PublicKey().
EVP_PKEY_get0_hmac()
const unsigned char* EVP_PKEY_get0_hmac (const EVP_PKEY * pkey, size_t * len)
Definition at line 240 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_HMAC, EVP_PKEY_get0(), EVP_PKEY_HMAC, EVP_R_EXPECTING_AN_HMAC_KEY, EVPerr, and NULL.
EVP_PKEY_get0_poly1305()
const unsigned char* EVP_PKEY_get0_poly1305 (const EVP_PKEY * pkey, size_t * len)
Definition at line 253 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_POLY1305, EVP_PKEY_get0(), EVP_PKEY_POLY1305, EVP_R_EXPECTING_A_POLY1305_KEY, EVPerr, and NULL.
EVP_PKEY_get0_RSA()
struct rsa_st* EVP_PKEY_get0_RSA (EVP_PKEY * pkey)
Definition at line 290 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_RSA, EVP_PKEY_RSA, EVP_R_EXPECTING_AN_RSA_KEY, EVPerr, and NULL.
Referenced by i2d_PublicKey().
EVP_PKEY_get0_siphash()
const unsigned char* EVP_PKEY_get0_siphash (const EVP_PKEY * pkey, size_t * len)
Definition at line 267 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_SIPHASH, EVP_PKEY_get0(), EVP_PKEY_SIPHASH, EVP_R_EXPECTING_A_SIPHASH_KEY, EVPerr, and NULL.
EVP_PKEY_get1_DH()
struct dh_st* EVP_PKEY_get1_DH (EVP_PKEY * pkey)
Definition at line 382 of file p_lib.c.
EVP_PKEY_get1_DSA()
struct dsa_st* EVP_PKEY_get1_DSA (EVP_PKEY * pkey)
Definition at line 326 of file p_lib.c.
EVP_PKEY_get1_EC_KEY()
struct ec_key_st* EVP_PKEY_get1_EC_KEY (EVP_PKEY * pkey)
Definition at line 354 of file p_lib.c.
Referenced by ssl_print_tmp_key().
EVP_PKEY_get1_RSA()
struct rsa_st* EVP_PKEY_get1_RSA (EVP_PKEY * pkey)
Definition at line 299 of file p_lib.c.
EVP_PKEY_get1_tls_encodedpoint()
size_t EVP_PKEY_get1_tls_encodedpoint (EVP_PKEY * pkey, unsigned char ** ppt)
Definition at line 506 of file p_lib.c.
Referenced by tls_construct_stoc_key_share().
EVP_PKEY_get_default_digest_nid()
int EVP_PKEY_get_default_digest_nid (EVP_PKEY * pkey, int * pnid)
Definition at line 490 of file p_lib.c.
Referenced by PKCS7_add_signature().
EVP_PKEY_id()
int EVP_PKEY_id (const EVP_PKEY * pkey)
Definition at line 407 of file p_lib.c.
Referenced by i2d_PublicKey(), ssl_cert_type(), and ssl_print_tmp_key().
EVP_PKEY_keygen()
int EVP_PKEY_keygen (EVP_PKEY_CTX * ctx, EVP_PKEY ** ppkey)
Definition at line 85 of file pmeth_gn.c.
Referenced by EVP_PKEY_new_mac_key().
EVP_PKEY_keygen_init()
int EVP_PKEY_keygen_init (EVP_PKEY_CTX * ctx)
Definition at line 68 of file pmeth_gn.c.
Referenced by EVP_PKEY_new_mac_key().
EVP_PKEY_meth_add0()
int EVP_PKEY_meth_add0 (const EVP_PKEY_METHOD * pmeth)
Definition at line 277 of file pmeth_lib.c.
References NULL.
EVP_PKEY_meth_copy()
void EVP_PKEY_meth_copy (EVP_PKEY_METHOD * dst, const EVP_PKEY_METHOD * src)
Definition at line 176 of file pmeth_lib.c.
EVP_PKEY_meth_find()
const EVP_PKEY_METHOD* EVP_PKEY_meth_find (int type)
Definition at line 72 of file pmeth_lib.c.
References t.
EVP_PKEY_meth_free()
void EVP_PKEY_meth_free (EVP_PKEY_METHOD * pmeth)
Definition at line 217 of file pmeth_lib.c.
References EVP_PKEY_FLAG_DYNAMIC, and OPENSSL_free.
Referenced by engine_pkey_meths_free().
EVP_PKEY_meth_get0_info()
void EVP_PKEY_meth_get0_info (int * ppkey_id, int * pflags, const EVP_PKEY_METHOD * meth)
Definition at line 167 of file pmeth_lib.c.
EVP_PKEY_meth_get_cleanup()
void EVP_PKEY_meth_get_cleanup (EVP_PKEY_METHOD * pmeth, void(**)(EVP_PKEY_CTX *ctx) pcleanup)
Definition at line 585 of file pmeth_lib.c.
EVP_PKEY_meth_get_copy()
void EVP_PKEY_meth_get_copy (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *dst, EVP_PKEY_CTX *src) pcopy)
Definition at line 578 of file pmeth_lib.c.
EVP_PKEY_meth_get_ctrl()
void EVP_PKEY_meth_get_ctrl (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx, int type, int p1, void *p2) pctrl, int(**)(EVP_PKEY_CTX *ctx, const char *type, const char *value) pctrl_str)
Definition at line 726 of file pmeth_lib.c.
EVP_PKEY_meth_get_decrypt()
void EVP_PKEY_meth_get_decrypt (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pdecrypt_init, int(**)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen) pdecrypt)
Definition at line 700 of file pmeth_lib.c.
EVP_PKEY_meth_get_derive()
void EVP_PKEY_meth_get_derive (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pderive_init, int(**)(EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen) pderive)
Definition at line 714 of file pmeth_lib.c.
EVP_PKEY_meth_get_encrypt()
void EVP_PKEY_meth_get_encrypt (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pencrypt_init, int(**)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen) pencryptfn)
Definition at line 686 of file pmeth_lib.c.
EVP_PKEY_meth_get_init()
void EVP_PKEY_meth_get_init (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pinit)
Definition at line 572 of file pmeth_lib.c.
EVP_PKEY_meth_get_keygen()
void EVP_PKEY_meth_get_keygen (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pkeygen_init, int(**)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey) pkeygen)
Definition at line 602 of file pmeth_lib.c.
EVP_PKEY_meth_get_paramgen()
void EVP_PKEY_meth_get_paramgen (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pparamgen_init, int(**)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey) pparamgen)
Definition at line 591 of file pmeth_lib.c.
EVP_PKEY_meth_get_sign()
void EVP_PKEY_meth_get_sign (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) psign_init, int(**)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen) psign)
Definition at line 613 of file pmeth_lib.c.
EVP_PKEY_meth_get_signctx()
void EVP_PKEY_meth_get_signctx (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx) psignctx_init, int(**)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, EVP_MD_CTX *mctx) psignctx)
Definition at line 658 of file pmeth_lib.c.
EVP_PKEY_meth_get_verify()
void EVP_PKEY_meth_get_verify (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pverify_init, int(**)(EVP_PKEY_CTX *ctx, const unsigned char *sig, size_t siglen, const unsigned char *tbs, size_t tbslen) pverify)
Definition at line 626 of file pmeth_lib.c.
EVP_PKEY_meth_get_verify_recover()
void EVP_PKEY_meth_get_verify_recover (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pverify_recover_init, int(**)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen) pverify_recover)
Definition at line 640 of file pmeth_lib.c.
EVP_PKEY_meth_get_verifyctx()
void EVP_PKEY_meth_get_verifyctx (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx) pverifyctx_init, int(**)(EVP_PKEY_CTX *ctx, const unsigned char *sig, int siglen, EVP_MD_CTX *mctx) pverifyctx)
Definition at line 672 of file pmeth_lib.c.
EVP_PKEY_meth_new()
EVP_PKEY_METHOD* EVP_PKEY_meth_new (int id, int flags)
Definition at line 154 of file pmeth_lib.c.
References EVP_PKEY_FLAG_DYNAMIC, NULL, and OPENSSL_zalloc.
EVP_PKEY_meth_set_cleanup()
void EVP_PKEY_meth_set_cleanup (EVP_PKEY_METHOD * pmeth, void(*)(EVP_PKEY_CTX *ctx) cleanup)
Definition at line 440 of file pmeth_lib.c.
EVP_PKEY_meth_set_copy()
void EVP_PKEY_meth_set_copy (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *dst, EVP_PKEY_CTX *src) copy)
Definition at line 433 of file pmeth_lib.c.
EVP_PKEY_meth_set_ctrl()
void EVP_PKEY_meth_set_ctrl (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx, int type, int p1, void *p2) ctrl, int(*)(EVP_PKEY_CTX *ctx, const char *type, const char *value) ctrl_str)
Definition at line 561 of file pmeth_lib.c.
EVP_PKEY_meth_set_decrypt()
void EVP_PKEY_meth_set_decrypt (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) decrypt_init, int(*)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen) decrypt)
Definition at line 539 of file pmeth_lib.c.
EVP_PKEY_meth_set_derive()
void EVP_PKEY_meth_set_derive (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) derive_init, int(*)(EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen) derive)
Definition at line 551 of file pmeth_lib.c.
EVP_PKEY_meth_set_encrypt()
void EVP_PKEY_meth_set_encrypt (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) encrypt_init, int(*)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen) encryptfn)
Definition at line 527 of file pmeth_lib.c.
EVP_PKEY_meth_set_init()
void EVP_PKEY_meth_set_init (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) init)
Definition at line 427 of file pmeth_lib.c.
EVP_PKEY_meth_set_keygen()
void EVP_PKEY_meth_set_keygen (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) keygen_init, int(*)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey) keygen)
Definition at line 455 of file pmeth_lib.c.
EVP_PKEY_meth_set_paramgen()
void EVP_PKEY_meth_set_paramgen (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) paramgen_init, int(*)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey) paramgen)
Definition at line 446 of file pmeth_lib.c.
EVP_PKEY_meth_set_sign()
void EVP_PKEY_meth_set_sign (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) sign_init, int(*)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen) sign)
Definition at line 464 of file pmeth_lib.c.
EVP_PKEY_meth_set_signctx()
void EVP_PKEY_meth_set_signctx (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx) signctx_init, int(*)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, EVP_MD_CTX *mctx) signctx)
Definition at line 503 of file pmeth_lib.c.
EVP_PKEY_meth_set_verify()
void EVP_PKEY_meth_set_verify (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) verify_init, int(*)(EVP_PKEY_CTX *ctx, const unsigned char *sig, size_t siglen, const unsigned char *tbs, size_t tbslen) verify)
Definition at line 475 of file pmeth_lib.c.
EVP_PKEY_meth_set_verify_recover()
void EVP_PKEY_meth_set_verify_recover (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) verify_recover_init, int(*)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen) verify_recover)
Definition at line 487 of file pmeth_lib.c.
EVP_PKEY_meth_set_verifyctx()
void EVP_PKEY_meth_set_verifyctx (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx) verifyctx_init, int(*)(EVP_PKEY_CTX *ctx, const unsigned char *sig, int siglen, EVP_MD_CTX *mctx) verifyctx)
Definition at line 515 of file pmeth_lib.c.
EVP_PKEY_missing_parameters()
int EVP_PKEY_missing_parameters (const EVP_PKEY * pkey)
Definition at line 101 of file p_lib.c.
Referenced by EVP_PKEY_copy_parameters().
EVP_PKEY_new()
EVP_PKEY* EVP_PKEY_new (void)
Definition at line 138 of file p_lib.c.
Referenced by d2i_PrivateKey_bio(), d2i_PrivateKey_fp(), d2i_PUBKEY_bio(), d2i_PUBKEY_fp(), and EVP_PKCS82PKEY().
EVP_PKEY_new_mac_key()
EVP_PKEY* EVP_PKEY_new_mac_key (int type, ENGINE * e, const unsigned char * key, int keylen)
Definition at line 152 of file pmeth_gn.c.
References EVP_PKEY_CTX_free(), EVP_PKEY_CTX_new_id(), EVP_PKEY_CTX_set_mac_key, EVP_PKEY_keygen(), EVP_PKEY_keygen_init(), mac_key, and NULL.
EVP_PKEY_paramgen()
int EVP_PKEY_paramgen (EVP_PKEY_CTX * ctx, EVP_PKEY ** ppkey)
Definition at line 35 of file pmeth_gn.c.
EVP_PKEY_paramgen_init()
int EVP_PKEY_paramgen_init (EVP_PKEY_CTX * ctx)
Definition at line 18 of file pmeth_gn.c.
EVP_PKEY_print_params()
int EVP_PKEY_print_params (BIO * out, const EVP_PKEY * pkey, int indent, ASN1_PCTX * pctx)
Definition at line 475 of file p_lib.c.
EVP_PKEY_print_private()
int EVP_PKEY_print_private (BIO * out, const EVP_PKEY * pkey, int indent, ASN1_PCTX * pctx)
Definition at line 466 of file p_lib.c.
EVP_PKEY_print_public()
int EVP_PKEY_print_public (BIO * out, const EVP_PKEY * pkey, int indent, ASN1_PCTX * pctx)
Definition at line 457 of file p_lib.c.
Referenced by X509_REQ_print_ex().
EVP_PKEY_save_parameters()
int EVP_PKEY_save_parameters (EVP_PKEY * pkey, int mode)
Definition at line 50 of file p_lib.c.
References EVP_PKEY_DSA.
EVP_PKEY_security_bits()
int EVP_PKEY_security_bits (const EVP_PKEY * pkey)
Definition at line 34 of file p_lib.c.
References NULL.
Referenced by ssl3_ctx_ctrl(), and ssl_get_auto_dh().
EVP_PKEY_set1_DH()
int EVP_PKEY_set1_DH (EVP_PKEY * pkey, struct dh_st * key)
EVP_PKEY_set1_DSA()
int EVP_PKEY_set1_DSA (EVP_PKEY * pkey, struct dsa_st * key)
EVP_PKEY_set1_EC_KEY()
int EVP_PKEY_set1_EC_KEY (EVP_PKEY * pkey, struct ec_key_st * key)
EVP_PKEY_set1_RSA()
int EVP_PKEY_set1_RSA (EVP_PKEY * pkey, struct rsa_st * key)
EVP_PKEY_set1_tls_encodedpoint()
int EVP_PKEY_set1_tls_encodedpoint (EVP_PKEY * pkey, const unsigned char * pt, size_t ptlen)
Definition at line 495 of file p_lib.c.
EVP_PKEY_set_type()
int EVP_PKEY_set_type (EVP_PKEY * pkey, int type)
Definition at line 217 of file p_lib.c.
Referenced by EVP_PKCS82PKEY(), EVP_PKEY_assign(), and EVP_PKEY_copy_parameters().
EVP_PKEY_set_type_str()
int EVP_PKEY_set_type_str (EVP_PKEY * pkey, const char * str, int len)
Definition at line 222 of file p_lib.c.
EVP_PKEY_sign()
int EVP_PKEY_sign (EVP_PKEY_CTX * ctx, unsigned char * sig, size_t * siglen, const unsigned char * tbs, size_t tbslen)
Definition at line 52 of file pmeth_fn.c.
References EVP_F_EVP_PKEY_SIGN, EVP_PKEY_OP_SIGN, EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE, EVP_R_OPERATON_NOT_INITIALIZED, EVPerr, and M_check_autoarg.
Referenced by EVP_SignFinal().
EVP_PKEY_sign_init()
int EVP_PKEY_sign_init (EVP_PKEY_CTX * ctx)
Definition at line 35 of file pmeth_fn.c.
Referenced by EVP_SignFinal().
EVP_PKEY_size()
int EVP_PKEY_size (EVP_PKEY * pkey)
Definition at line 43 of file p_lib.c.
Referenced by ASN1_item_sign_ctx(), ASN1_sign(), and EVP_SignFinal().
EVP_PKEY_type()
int EVP_PKEY_type (int type)
Definition at line 391 of file p_lib.c.
Referenced by EVP_PKEY_base_id(), and X509_get_signature_type().
EVP_PKEY_up_ref()
int EVP_PKEY_up_ref (EVP_PKEY * pkey)
Definition at line 159 of file p_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by TS_RESP_CTX_set_signer_key().
EVP_PKEY_verify()
int EVP_PKEY_verify (EVP_PKEY_CTX * ctx, const unsigned char * sig, size_t siglen, const unsigned char * tbs, size_t tbslen)
Definition at line 86 of file pmeth_fn.c.
References EVP_F_EVP_PKEY_VERIFY, EVP_PKEY_OP_VERIFY, EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE, EVP_R_OPERATON_NOT_INITIALIZED, and EVPerr.
Referenced by EVP_VerifyFinal().
EVP_PKEY_verify_init()
int EVP_PKEY_verify_init (EVP_PKEY_CTX * ctx)
Definition at line 69 of file pmeth_fn.c.
Referenced by EVP_VerifyFinal().
EVP_PKEY_verify_recover()
int EVP_PKEY_verify_recover (EVP_PKEY_CTX * ctx, unsigned char * rout, size_t * routlen, const unsigned char * sig, size_t siglen)
Definition at line 119 of file pmeth_fn.c.
References EVP_F_EVP_PKEY_VERIFY_RECOVER, EVP_PKEY_OP_VERIFYRECOVER, EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE, EVP_R_OPERATON_NOT_INITIALIZED, EVPerr, and M_check_autoarg.
EVP_PKEY_verify_recover_init()
int EVP_PKEY_verify_recover_init (EVP_PKEY_CTX * ctx)
Definition at line 102 of file pmeth_fn.c.
EVP_rc2_40_cbc()
const EVP_CIPHER* EVP_rc2_40_cbc (void)
Definition at line 78 of file e_rc2.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_rc2_64_cbc()
const EVP_CIPHER* EVP_rc2_64_cbc (void)
Definition at line 73 of file e_rc2.c.
Referenced by openssl_add_all_ciphers_int().
EVP_rc2_cbc()
const EVP_CIPHER* EVP_rc2_cbc (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_rc2_cfb64()
const EVP_CIPHER* EVP_rc2_cfb64 (void)
Referenced by EVP_rc2_cfb().
EVP_rc2_ecb()
const EVP_CIPHER* EVP_rc2_ecb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_rc2_ofb()
const EVP_CIPHER* EVP_rc2_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_rc4()
const EVP_CIPHER* EVP_rc4 (void)
Definition at line 59 of file e_rc4.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_rc4_40()
const EVP_CIPHER* EVP_rc4_40 (void)
Definition at line 64 of file e_rc4.c.
Referenced by openssl_add_all_ciphers_int().
EVP_rc4_hmac_md5()
const EVP_CIPHER* EVP_rc4_hmac_md5 (void)
Definition at line 258 of file e_rc4_hmac_md5.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_rc5_32_12_16_cbc()
const EVP_CIPHER* EVP_rc5_32_12_16_cbc (void)
Referenced by openssl_add_all_ciphers_int().
EVP_rc5_32_12_16_cfb64()
const EVP_CIPHER* EVP_rc5_32_12_16_cfb64 (void)
Referenced by EVP_rc5_32_12_16_cfb().
EVP_rc5_32_12_16_ecb()
const EVP_CIPHER* EVP_rc5_32_12_16_ecb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_rc5_32_12_16_ofb()
const EVP_CIPHER* EVP_rc5_32_12_16_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_read_pw_string()
int EVP_read_pw_string (char * buf, int length, const char * prompt, int verify)
Definition at line 44 of file evp_key.c.
EVP_read_pw_string_min()
int EVP_read_pw_string_min (char * buf, int minlen, int maxlen, const char * prompt, int verify)
Definition at line 49 of file evp_key.c.
EVP_ripemd160()
const EVP_MD* EVP_ripemd160 (void)
Definition at line 51 of file m_ripemd.c.
Referenced by openssl_add_all_digests_int().
EVP_SealFinal()
__owur int EVP_SealFinal (EVP_CIPHER_CTX * ctx, unsigned char * out, int * outl)
Definition at line 63 of file p_seal.c.
EVP_SealInit()
__owur int EVP_SealInit (EVP_CIPHER_CTX * ctx, const EVP_CIPHER * type, unsigned char ** ek, int * ekl, unsigned char * iv, EVP_PKEY ** pubk, int npubk)
Definition at line 18 of file p_seal.c.
EVP_seed_cbc()
const EVP_CIPHER* EVP_seed_cbc (void)
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_seed_cfb128()
const EVP_CIPHER* EVP_seed_cfb128 (void)
EVP_seed_ecb()
const EVP_CIPHER* EVP_seed_ecb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_seed_ofb()
const EVP_CIPHER* EVP_seed_ofb (void)
Referenced by openssl_add_all_ciphers_int().
EVP_set_pw_prompt()
void EVP_set_pw_prompt (const char * prompt)
Definition at line 21 of file evp_key.c.
References NULL.
EVP_sha1()
const EVP_MD* EVP_sha1 (void)
Definition at line 108 of file m_sha1.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), OCSP_cert_to_id(), openssl_add_all_digests_int(), PKCS12_set_mac(), SRP_Calc_x(), and X509_ocspid_print().
EVP_sha224()
const EVP_MD* EVP_sha224 (void)
Definition at line 152 of file m_sha1.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_digests_int().
EVP_sha256()
const EVP_MD* EVP_sha256 (void)
Definition at line 171 of file m_sha1.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), EVP_PBE_scrypt(), openssl_add_all_digests_int(), ssl_handshake_md(), and TS_RESP_CTX_new().
EVP_sha384()
const EVP_MD* EVP_sha384 (void)
Definition at line 211 of file m_sha1.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_digests_int().
EVP_sha512()
const EVP_MD* EVP_sha512 (void)
Definition at line 230 of file m_sha1.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_digests_int().
EVP_SignFinal()
__owur int EVP_SignFinal (EVP_MD_CTX * ctx, unsigned char * md, unsigned int * s, EVP_PKEY * pkey)
Definition at line 17 of file p_sign.c.
References ERR_R_MALLOC_FAILURE, EVP_DigestFinal_ex(), EVP_F_EVP_SIGNFINAL, EVP_MAX_MD_SIZE, EVP_MD_CTX_copy_ex(), EVP_MD_CTX_FLAG_FINALISE, EVP_MD_CTX_free(), EVP_MD_CTX_md(), EVP_MD_CTX_new(), EVP_MD_CTX_test_flags(), EVP_PKEY_CTX_free(), EVP_PKEY_CTX_new(), EVP_PKEY_CTX_set_signature_md, EVP_PKEY_sign(), EVP_PKEY_sign_init(), EVP_PKEY_size(), EVPerr, and NULL.
Referenced by ASN1_sign().
EVP_VerifyFinal()
__owur int EVP_VerifyFinal (EVP_MD_CTX * ctx, const unsigned char * sigbuf, unsigned int siglen, EVP_PKEY * pkey)
Definition at line 17 of file p_verify.c.
References ERR_R_MALLOC_FAILURE, EVP_DigestFinal_ex(), EVP_F_EVP_VERIFYFINAL, EVP_MAX_MD_SIZE, EVP_MD_CTX_copy_ex(), EVP_MD_CTX_FLAG_FINALISE, EVP_MD_CTX_free(), EVP_MD_CTX_md(), EVP_MD_CTX_new(), EVP_MD_CTX_test_flags(), EVP_PKEY_CTX_free(), EVP_PKEY_CTX_new(), EVP_PKEY_CTX_set_signature_md, EVP_PKEY_verify(), EVP_PKEY_verify_init(), EVPerr, and NULL.
Referenced by PKCS7_signatureVerify().
EVP_whirlpool()
const EVP_MD* EVP_whirlpool (void)
Definition at line 50 of file m_wp.c.
Referenced by openssl_add_all_digests_int().
i2d_PrivateKey()
int i2d_PrivateKey (EVP_PKEY * a, unsigned char ** pp)
Definition at line 17 of file i2d_pr.c.
References EVP_PKEY2PKCS8().
Referenced by i2d_PrivateKey_bio(), i2d_PrivateKey_fp(), and PEM_write_bio_PrivateKey_traditional().
i2d_PublicKey()
int i2d_PublicKey (EVP_PKEY * a, unsigned char ** pp)
Definition at line 19 of file i2d_pu.c.
References ASN1_F_I2D_PUBLICKEY, ASN1_R_UNSUPPORTED_PUBLIC_KEY_TYPE, ASN1err, EVP_PKEY_DSA, EVP_PKEY_EC, EVP_PKEY_get0_DSA(), EVP_PKEY_get0_EC_KEY(), EVP_PKEY_get0_RSA(), EVP_PKEY_id(), EVP_PKEY_RSA, i2d_DSAPublicKey(), and i2o_ECPublicKey().
PKCS5_PBE_add()
void PKCS5_PBE_add (void)
Definition at line 20 of file p5_crpt.c.
PKCS5_PBE_keyivgen()
int PKCS5_PBE_keyivgen (EVP_CIPHER_CTX * ctx, const char * pass, int passlen, ASN1_TYPE * param, const EVP_CIPHER * cipher, const EVP_MD * md, int en_de)
Definition at line 24 of file p5_crpt.c.
PKCS5_PBKDF2_HMAC()
int PKCS5_PBKDF2_HMAC (const char * pass, int passlen, const unsigned char * salt, int saltlen, int iter, const EVP_MD * digest, int keylen, unsigned char * out)
Definition at line 32 of file p5_crpt2.c.
Referenced by EVP_PBE_scrypt().
PKCS5_PBKDF2_HMAC_SHA1()
int PKCS5_PBKDF2_HMAC_SHA1 (const char * pass, int passlen, const unsigned char * salt, int saltlen, int iter, int keylen, unsigned char * out)
Definition at line 124 of file p5_crpt2.c.
PKCS5_v2_PBE_keyivgen()
int PKCS5_v2_PBE_keyivgen (EVP_CIPHER_CTX * ctx, const char * pass, int passlen, ASN1_TYPE * param, const EVP_CIPHER * cipher, const EVP_MD * md, int en_de)
Definition at line 138 of file p5_crpt2.c.
PKCS5_v2_scrypt_keyivgen()
int PKCS5_v2_scrypt_keyivgen (EVP_CIPHER_CTX * ctx, const char * pass, int passlen, ASN1_TYPE * param, const EVP_CIPHER * c, const EVP_MD * md, int en_de)
Definition at line 221 of file p5_scrypt.c.
Variable Documentation
EVP_CIPHER_meth_get_cleanup
int(*)(EVP_CIPHER_CTX *) EVP_CIPHER_meth_get_cleanup(const EVP_CIPHER *cipher)
Definition at line 210 of file evp.h.
EVP_CIPHER_meth_get_ctrl
int(*)(EVP_CIPHER_CTX *, int type, int arg, void *ptr) EVP_CIPHER_meth_get_ctrl(const EVP_CIPHER *cipher)
Definition at line 215 of file evp.h.
EVP_CIPHER_meth_get_do_cipher
int(*)(EVP_CIPHER_CTX *ctx, unsigned char *out, const unsigned char *in, size_t inl) EVP_CIPHER_meth_get_do_cipher(const EVP_CIPHER *cipher)
Definition at line 206 of file evp.h.
EVP_CIPHER_meth_get_get_asn1_params
int(*)(EVP_CIPHER_CTX *, ASN1_TYPE *) EVP_CIPHER_meth_get_get_asn1_params(const EVP_CIPHER *cipher)
Definition at line 213 of file evp.h.
EVP_CIPHER_meth_get_init
int(*)(EVP_CIPHER_CTX *ctx, const unsigned char *key, const unsigned char *iv, int enc) EVP_CIPHER_meth_get_init(const EVP_CIPHER *cipher)
Definition at line 202 of file evp.h.
EVP_CIPHER_meth_get_set_asn1_params
int(*)(EVP_CIPHER_CTX *, ASN1_TYPE *) EVP_CIPHER_meth_get_set_asn1_params(const EVP_CIPHER *cipher)
Definition at line 211 of file evp.h.
EVP_MD_CTX_update_fn
int(*)(EVP_MD_CTX *ctx, const void *data, size_t count) EVP_MD_CTX_update_fn(EVP_MD_CTX *ctx)
Definition at line 436 of file evp.h.
EVP_MD_meth_get_cleanup
int(*)(EVP_MD_CTX *ctx) EVP_MD_meth_get_cleanup(const EVP_MD *md)
Definition at line 101 of file evp.h.
EVP_MD_meth_get_copy
int(*)(EVP_MD_CTX *to, const EVP_MD_CTX *from) EVP_MD_meth_get_copy(const EVP_MD *md)
Definition at line 99 of file evp.h.
EVP_MD_meth_get_ctrl
int(*)(EVP_MD_CTX *ctx, int cmd, int p1, void *p2) EVP_MD_meth_get_ctrl(const EVP_MD *md)
Definition at line 102 of file evp.h.
EVP_MD_meth_get_final
int(*)(EVP_MD_CTX *ctx, unsigned char *md) EVP_MD_meth_get_final(const EVP_MD *md)
Definition at line 97 of file evp.h.
EVP_MD_meth_get_init
int(*)(EVP_MD_CTX *ctx) EVP_MD_meth_get_init(const EVP_MD *md)
Definition at line 93 of file evp.h.
EVP_MD_meth_get_update
int(*)(EVP_MD_CTX *ctx, const void *data, size_t count) EVP_MD_meth_get_update(const EVP_MD *md)
Definition at line 94 of file evp.h.