crypto/evp/evp_pkey.c File Reference
evp_pkey.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "internal/cryptlib.h"
#include <openssl/x509.h>
#include <openssl/rand.h>
#include "internal/asn1_int.h"
#include "internal/evp_int.h"
#include "internal/x509_int.h"
Functions
EVP_PKEY * EVP_PKCS82PKEY (const PKCS8_PRIV_KEY_INFO *p8)
PKCS8_PRIV_KEY_INFO * EVP_PKEY2PKCS8 (EVP_PKEY *pkey)
int EVP_PKEY_get_attr_count (const EVP_PKEY *key)
int EVP_PKEY_get_attr_by_NID (const EVP_PKEY *key, int nid, int lastpos)
int EVP_PKEY_get_attr_by_OBJ (const EVP_PKEY *key, const ASN1_OBJECT *obj, int lastpos)
X509_ATTRIBUTE * EVP_PKEY_get_attr (const EVP_PKEY *key, int loc)
X509_ATTRIBUTE * EVP_PKEY_delete_attr (EVP_PKEY *key, int loc)
int EVP_PKEY_add1_attr (EVP_PKEY *key, X509_ATTRIBUTE *attr)
int EVP_PKEY_add1_attr_by_OBJ (EVP_PKEY *key, const ASN1_OBJECT *obj, int type, const unsigned char *bytes, int len)
int EVP_PKEY_add1_attr_by_NID (EVP_PKEY *key, int nid, int type, const unsigned char *bytes, int len)
int EVP_PKEY_add1_attr_by_txt (EVP_PKEY *key, const char *attrname, int type, const unsigned char *bytes, int len)
Function Documentation
EVP_PKCS82PKEY()
EVP_PKEY* EVP_PKCS82PKEY (const PKCS8_PRIV_KEY_INFO * p8)
Definition at line 21 of file evp_pkey.c.
References ERR_add_error_data(), ERR_R_MALLOC_FAILURE, EVP_F_EVP_PKCS82PKEY, EVP_PKEY_free(), EVP_PKEY_new(), EVP_PKEY_set_type(), EVP_R_METHOD_NOT_SUPPORTED, EVP_R_PRIVATE_KEY_DECODE_ERROR, EVP_R_UNSUPPORTED_PRIVATE_KEY_ALGORITHM, EVPerr, i2t_ASN1_OBJECT(), NULL, OBJ_obj2nid(), and PKCS8_pkey_get0().
EVP_PKEY2PKCS8()
PKCS8_PRIV_KEY_INFO* EVP_PKEY2PKCS8 (EVP_PKEY * pkey)
Definition at line 61 of file evp_pkey.c.
References ERR_R_MALLOC_FAILURE, EVP_F_EVP_PKEY2PKCS8, EVP_R_METHOD_NOT_SUPPORTED, EVP_R_PRIVATE_KEY_ENCODE_ERROR, EVP_R_UNSUPPORTED_PRIVATE_KEY_ALGORITHM, EVPerr, NULL, and RAND_add().
Referenced by i2d_PrivateKey(), and PKCS12_add_key().
EVP_PKEY_add1_attr()
int EVP_PKEY_add1_attr (EVP_PKEY * key, X509_ATTRIBUTE * attr)
Definition at line 118 of file evp_pkey.c.
EVP_PKEY_add1_attr_by_NID()
int EVP_PKEY_add1_attr_by_NID (EVP_PKEY * key, int nid, int type, const unsigned char * bytes, int len)
Definition at line 134 of file evp_pkey.c.
EVP_PKEY_add1_attr_by_OBJ()
int EVP_PKEY_add1_attr_by_OBJ (EVP_PKEY * key, const ASN1_OBJECT * obj, int type, const unsigned char * bytes, int len)
Definition at line 125 of file evp_pkey.c.
EVP_PKEY_add1_attr_by_txt()
int EVP_PKEY_add1_attr_by_txt (EVP_PKEY * key, const char * attrname, int type, const unsigned char * bytes, int len)
Definition at line 143 of file evp_pkey.c.
EVP_PKEY_delete_attr()
X509_ATTRIBUTE* EVP_PKEY_delete_attr (EVP_PKEY * key, int loc)
Definition at line 113 of file evp_pkey.c.
References X509at_delete_attr().
EVP_PKEY_get_attr()
X509_ATTRIBUTE* EVP_PKEY_get_attr (const EVP_PKEY * key, int loc)
Definition at line 108 of file evp_pkey.c.
References X509at_get_attr().
EVP_PKEY_get_attr_by_NID()
int EVP_PKEY_get_attr_by_NID (const EVP_PKEY * key, int nid, int lastpos)
Definition at line 97 of file evp_pkey.c.
References X509at_get_attr_by_NID().
EVP_PKEY_get_attr_by_OBJ()
int EVP_PKEY_get_attr_by_OBJ (const EVP_PKEY * key, const ASN1_OBJECT * obj, int lastpos)
Definition at line 102 of file evp_pkey.c.
References X509at_get_attr_by_OBJ().
EVP_PKEY_get_attr_count()
int EVP_PKEY_get_attr_count (const EVP_PKEY * key)
Definition at line 92 of file evp_pkey.c.
References X509at_get_attr_count().