crypto/evp/evp_lib.c File Reference
evp_lib.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/evp.h>
#include <openssl/objects.h>
#include "internal/evp_int.h"
#include "evp_locl.h"
Functions
int EVP_CIPHER_param_to_asn1 (EVP_CIPHER_CTX *c, ASN1_TYPE *type)
int EVP_CIPHER_asn1_to_param (EVP_CIPHER_CTX *c, ASN1_TYPE *type)
int EVP_CIPHER_get_asn1_iv (EVP_CIPHER_CTX *c, ASN1_TYPE *type)
int EVP_CIPHER_set_asn1_iv (EVP_CIPHER_CTX *c, ASN1_TYPE *type)
int EVP_CIPHER_type (const EVP_CIPHER *ctx)
int EVP_CIPHER_block_size (const EVP_CIPHER *e)
int EVP_CIPHER_CTX_block_size (const EVP_CIPHER_CTX *ctx)
int EVP_CIPHER_impl_ctx_size (const EVP_CIPHER *e)
int EVP_Cipher (EVP_CIPHER_CTX *ctx, unsigned char *out, const unsigned char *in, unsigned int inl)
const EVP_CIPHER * EVP_CIPHER_CTX_cipher (const EVP_CIPHER_CTX *ctx)
int EVP_CIPHER_CTX_encrypting (const EVP_CIPHER_CTX *ctx)
unsigned long EVP_CIPHER_flags (const EVP_CIPHER *cipher)
void * EVP_CIPHER_CTX_get_app_data (const EVP_CIPHER_CTX *ctx)
void EVP_CIPHER_CTX_set_app_data (EVP_CIPHER_CTX *ctx, void *data)
void * EVP_CIPHER_CTX_get_cipher_data (const EVP_CIPHER_CTX *ctx)
void * EVP_CIPHER_CTX_set_cipher_data (EVP_CIPHER_CTX *ctx, void *cipher_data)
int EVP_CIPHER_iv_length (const EVP_CIPHER *cipher)
int EVP_CIPHER_CTX_iv_length (const EVP_CIPHER_CTX *ctx)
const unsigned char * EVP_CIPHER_CTX_original_iv (const EVP_CIPHER_CTX *ctx)
const unsigned char * EVP_CIPHER_CTX_iv (const EVP_CIPHER_CTX *ctx)
unsigned char * EVP_CIPHER_CTX_iv_noconst (EVP_CIPHER_CTX *ctx)
unsigned char * EVP_CIPHER_CTX_buf_noconst (EVP_CIPHER_CTX *ctx)
int EVP_CIPHER_CTX_num (const EVP_CIPHER_CTX *ctx)
void EVP_CIPHER_CTX_set_num (EVP_CIPHER_CTX *ctx, int num)
int EVP_CIPHER_key_length (const EVP_CIPHER *cipher)
int EVP_CIPHER_CTX_key_length (const EVP_CIPHER_CTX *ctx)
int EVP_CIPHER_nid (const EVP_CIPHER *cipher)
int EVP_CIPHER_CTX_nid (const EVP_CIPHER_CTX *ctx)
int EVP_MD_block_size (const EVP_MD *md)
int EVP_MD_type (const EVP_MD *md)
int EVP_MD_pkey_type (const EVP_MD *md)
int EVP_MD_size (const EVP_MD *md)
unsigned long EVP_MD_flags (const EVP_MD *md)
EVP_MD * EVP_MD_meth_new (int md_type, int pkey_type)
EVP_MD * EVP_MD_meth_dup (const EVP_MD *md)
void EVP_MD_meth_free (EVP_MD *md)
int EVP_MD_meth_set_input_blocksize (EVP_MD *md, int blocksize)
int EVP_MD_meth_set_result_size (EVP_MD *md, int resultsize)
int EVP_MD_meth_set_app_datasize (EVP_MD *md, int datasize)
int EVP_MD_meth_set_flags (EVP_MD *md, unsigned long flags)
int EVP_MD_meth_set_init (EVP_MD *md, int(*init)(EVP_MD_CTX *ctx))
int EVP_MD_meth_set_update (EVP_MD *md, int(*update)(EVP_MD_CTX *ctx, const void *data, size_t count))
int EVP_MD_meth_set_final (EVP_MD *md, int(*final)(EVP_MD_CTX *ctx, unsigned char *md))
int EVP_MD_meth_set_copy (EVP_MD *md, int(*copy)(EVP_MD_CTX *to, const EVP_MD_CTX *from))
int EVP_MD_meth_set_cleanup (EVP_MD *md, int(*cleanup)(EVP_MD_CTX *ctx))
int EVP_MD_meth_set_ctrl (EVP_MD *md, int(*ctrl)(EVP_MD_CTX *ctx, int cmd, int p1, void *p2))
int EVP_MD_meth_get_input_blocksize (const EVP_MD *md)
int EVP_MD_meth_get_result_size (const EVP_MD *md)
int EVP_MD_meth_get_app_datasize (const EVP_MD *md)
unsigned long EVP_MD_meth_get_flags (const EVP_MD *md)
const EVP_MD * EVP_MD_CTX_md (const EVP_MD_CTX *ctx)
EVP_PKEY_CTX * EVP_MD_CTX_pkey_ctx (const EVP_MD_CTX *ctx)
void * EVP_MD_CTX_md_data (const EVP_MD_CTX *ctx)
void EVP_MD_CTX_set_update_fn (EVP_MD_CTX *ctx, int(*update)(EVP_MD_CTX *ctx, const void *data, size_t count))
void EVP_MD_CTX_set_flags (EVP_MD_CTX *ctx, int flags)
void EVP_MD_CTX_clear_flags (EVP_MD_CTX *ctx, int flags)
int EVP_MD_CTX_test_flags (const EVP_MD_CTX *ctx, int flags)
void EVP_CIPHER_CTX_set_flags (EVP_CIPHER_CTX *ctx, int flags)
void EVP_CIPHER_CTX_clear_flags (EVP_CIPHER_CTX *ctx, int flags)
int EVP_CIPHER_CTX_test_flags (const EVP_CIPHER_CTX *ctx, int flags)
Variables
int(*)(EVP_MD_CTX *ctx) EVP_MD_meth_get_init (const EVP_MD *md)
int(*)(EVP_MD_CTX *ctx, const void *data, size_t count) EVP_MD_meth_get_update (const EVP_MD *md)
int(*)(EVP_MD_CTX *ctx, unsigned char *md) EVP_MD_meth_get_final (const EVP_MD *md)
int(*)(EVP_MD_CTX *to, const EVP_MD_CTX *from) EVP_MD_meth_get_copy (const EVP_MD *md)
int(*)(EVP_MD_CTX *ctx) EVP_MD_meth_get_cleanup (const EVP_MD *md)
int(*)(EVP_MD_CTX *ctx, int cmd, int p1, void *p2) EVP_MD_meth_get_ctrl (const EVP_MD *md)
int(*)(EVP_MD_CTX *ctx, const void *data, size_t count) EVP_MD_CTX_update_fn (EVP_MD_CTX *ctx)
Function Documentation
EVP_Cipher()
int EVP_Cipher (EVP_CIPHER_CTX * ctx, unsigned char * out, const unsigned char * in, unsigned int inl)
Definition at line 180 of file evp_lib.c.
Referenced by CMAC_Update(), and ssl3_enc().
EVP_CIPHER_asn1_to_param()
int EVP_CIPHER_asn1_to_param (EVP_CIPHER_CTX * c, ASN1_TYPE * type)
Definition at line 46 of file evp_lib.c.
Referenced by cms_RecipientInfo_pwri_crypt().
EVP_CIPHER_block_size()
int EVP_CIPHER_block_size (const EVP_CIPHER * e)
Definition at line 165 of file evp_lib.c.
EVP_CIPHER_CTX_block_size()
int EVP_CIPHER_CTX_block_size (const EVP_CIPHER_CTX * ctx)
Definition at line 170 of file evp_lib.c.
Referenced by CMAC_Update(), and ssl3_enc().
EVP_CIPHER_CTX_buf_noconst()
unsigned char* EVP_CIPHER_CTX_buf_noconst (EVP_CIPHER_CTX * ctx)
Definition at line 251 of file evp_lib.c.
Referenced by BLOCK_CIPHER_custom().
EVP_CIPHER_CTX_cipher()
const EVP_CIPHER* EVP_CIPHER_CTX_cipher (const EVP_CIPHER_CTX * ctx)
Definition at line 186 of file evp_lib.c.
Referenced by ssl3_enc(), and tls1_cbc_remove_padding().
EVP_CIPHER_CTX_clear_flags()
void EVP_CIPHER_CTX_clear_flags (EVP_CIPHER_CTX * ctx, int flags)
Definition at line 489 of file evp_lib.c.
EVP_CIPHER_CTX_encrypting()
int EVP_CIPHER_CTX_encrypting (const EVP_CIPHER_CTX * ctx)
Definition at line 191 of file evp_lib.c.
Referenced by BLOCK_CIPHER_custom().
EVP_CIPHER_CTX_get_app_data()
void* EVP_CIPHER_CTX_get_app_data (const EVP_CIPHER_CTX * ctx)
Definition at line 201 of file evp_lib.c.
EVP_CIPHER_CTX_get_cipher_data()
void* EVP_CIPHER_CTX_get_cipher_data (const EVP_CIPHER_CTX * ctx)
Definition at line 211 of file evp_lib.c.
EVP_CIPHER_CTX_iv()
const unsigned char* EVP_CIPHER_CTX_iv (const EVP_CIPHER_CTX * ctx)
Definition at line 241 of file evp_lib.c.
EVP_CIPHER_CTX_iv_length()
int EVP_CIPHER_CTX_iv_length (const EVP_CIPHER_CTX * ctx)
Definition at line 231 of file evp_lib.c.
EVP_CIPHER_CTX_iv_noconst()
unsigned char* EVP_CIPHER_CTX_iv_noconst (EVP_CIPHER_CTX * ctx)
Definition at line 246 of file evp_lib.c.
Referenced by BLOCK_CIPHER_custom(), and if().
EVP_CIPHER_CTX_key_length()
int EVP_CIPHER_CTX_key_length (const EVP_CIPHER_CTX * ctx)
Definition at line 271 of file evp_lib.c.
Referenced by if().
EVP_CIPHER_CTX_nid()
int EVP_CIPHER_CTX_nid (const EVP_CIPHER_CTX * ctx)
Definition at line 281 of file evp_lib.c.
EVP_CIPHER_CTX_num()
int EVP_CIPHER_CTX_num (const EVP_CIPHER_CTX * ctx)
Definition at line 256 of file evp_lib.c.
EVP_CIPHER_CTX_original_iv()
const unsigned char* EVP_CIPHER_CTX_original_iv (const EVP_CIPHER_CTX * ctx)
Definition at line 236 of file evp_lib.c.
EVP_CIPHER_CTX_set_app_data()
void EVP_CIPHER_CTX_set_app_data (EVP_CIPHER_CTX * ctx, void * data)
Definition at line 206 of file evp_lib.c.
References data.
EVP_CIPHER_CTX_set_cipher_data()
void* EVP_CIPHER_CTX_set_cipher_data (EVP_CIPHER_CTX * ctx, void * cipher_data)
Definition at line 216 of file evp_lib.c.
EVP_CIPHER_CTX_set_flags()
void EVP_CIPHER_CTX_set_flags (EVP_CIPHER_CTX * ctx, int flags)
Definition at line 484 of file evp_lib.c.
References flags.
EVP_CIPHER_CTX_set_num()
void EVP_CIPHER_CTX_set_num (EVP_CIPHER_CTX * ctx, int num)
Definition at line 261 of file evp_lib.c.
EVP_CIPHER_CTX_test_flags()
int EVP_CIPHER_CTX_test_flags (const EVP_CIPHER_CTX * ctx, int flags)
Definition at line 494 of file evp_lib.c.
EVP_CIPHER_flags()
unsigned long EVP_CIPHER_flags (const EVP_CIPHER * cipher)
Definition at line 196 of file evp_lib.c.
Referenced by tls1_cbc_remove_padding().
EVP_CIPHER_get_asn1_iv()
int EVP_CIPHER_get_asn1_iv (EVP_CIPHER_CTX * c, ASN1_TYPE * type)
Definition at line 75 of file evp_lib.c.
EVP_CIPHER_impl_ctx_size()
int EVP_CIPHER_impl_ctx_size (const EVP_CIPHER * e)
Definition at line 175 of file evp_lib.c.
EVP_CIPHER_iv_length()
int EVP_CIPHER_iv_length (const EVP_CIPHER * cipher)
Definition at line 226 of file evp_lib.c.
EVP_CIPHER_key_length()
int EVP_CIPHER_key_length (const EVP_CIPHER * cipher)
Definition at line 266 of file evp_lib.c.
EVP_CIPHER_nid()
int EVP_CIPHER_nid (const EVP_CIPHER * cipher)
Definition at line 276 of file evp_lib.c.
Referenced by EVP_CIPHER_type().
EVP_CIPHER_param_to_asn1()
int EVP_CIPHER_param_to_asn1 (EVP_CIPHER_CTX * c, ASN1_TYPE * type)
Definition at line 17 of file evp_lib.c.
EVP_CIPHER_set_asn1_iv()
int EVP_CIPHER_set_asn1_iv (EVP_CIPHER_CTX * c, ASN1_TYPE * type)
Definition at line 92 of file evp_lib.c.
EVP_CIPHER_type()
int EVP_CIPHER_type (const EVP_CIPHER * ctx)
Definition at line 106 of file evp_lib.c.
References ASN1_OBJECT_free(), EVP_CIPHER_nid(), nid, NID_aes_128_cfb1, NID_aes_128_cfb128, NID_aes_128_cfb8, NID_aes_192_cfb1, NID_aes_192_cfb128, NID_aes_192_cfb8, NID_aes_256_cfb1, NID_aes_256_cfb128, NID_aes_256_cfb8, NID_des_cfb1, NID_des_cfb64, NID_des_cfb8, NID_des_ede3_cfb1, NID_des_ede3_cfb64, NID_des_ede3_cfb8, NID_rc2_40_cbc, NID_rc2_64_cbc, NID_rc2_cbc, NID_rc4, NID_rc4_40, NID_undef, NULL, OBJ_get0_data(), and OBJ_nid2obj().
EVP_MD_block_size()
int EVP_MD_block_size (const EVP_MD * md)
Definition at line 286 of file evp_lib.c.
EVP_MD_CTX_clear_flags()
void EVP_MD_CTX_clear_flags (EVP_MD_CTX * ctx, int flags)
Definition at line 474 of file evp_lib.c.
Referenced by EVP_DigestInit_ex().
EVP_MD_CTX_md()
const EVP_MD* EVP_MD_CTX_md (const EVP_MD_CTX * ctx)
Definition at line 439 of file evp_lib.c.
References NULL.
Referenced by ASN1_item_sign_ctx(), cms_DigestAlgorithm_find_ctx(), EVP_SignFinal(), EVP_VerifyFinal(), PKCS7_signatureVerify(), and ssl3_enc().
EVP_MD_CTX_md_data()
void* EVP_MD_CTX_md_data (const EVP_MD_CTX * ctx)
Definition at line 451 of file evp_lib.c.
EVP_MD_CTX_pkey_ctx()
EVP_PKEY_CTX* EVP_MD_CTX_pkey_ctx (const EVP_MD_CTX * ctx)
Definition at line 446 of file evp_lib.c.
Referenced by ASN1_item_sign_ctx().
EVP_MD_CTX_set_flags()
void EVP_MD_CTX_set_flags (EVP_MD_CTX * ctx, int flags)
Definition at line 469 of file evp_lib.c.
References flags.
Referenced by HMAC_CTX_set_flags().
EVP_MD_CTX_set_update_fn()
void EVP_MD_CTX_set_update_fn (EVP_MD_CTX * ctx, int(*)(EVP_MD_CTX *ctx, const void *data, size_t count) update)
Definition at line 462 of file evp_lib.c.
EVP_MD_CTX_test_flags()
int EVP_MD_CTX_test_flags (const EVP_MD_CTX * ctx, int flags)
Definition at line 479 of file evp_lib.c.
Referenced by EVP_MD_CTX_reset(), EVP_SignFinal(), and EVP_VerifyFinal().
EVP_MD_flags()
unsigned long EVP_MD_flags (const EVP_MD * md)
Definition at line 310 of file evp_lib.c.
EVP_MD_meth_dup()
EVP_MD* EVP_MD_meth_dup (const EVP_MD * md)
Definition at line 325 of file evp_lib.c.
EVP_MD_meth_free()
void EVP_MD_meth_free (EVP_MD * md)
Definition at line 333 of file evp_lib.c.
EVP_MD_meth_get_app_datasize()
int EVP_MD_meth_get_app_datasize (const EVP_MD * md)
Definition at line 401 of file evp_lib.c.
EVP_MD_meth_get_flags()
unsigned long EVP_MD_meth_get_flags (const EVP_MD * md)
Definition at line 405 of file evp_lib.c.
EVP_MD_meth_get_input_blocksize()
int EVP_MD_meth_get_input_blocksize (const EVP_MD * md)
Definition at line 393 of file evp_lib.c.
EVP_MD_meth_get_result_size()
int EVP_MD_meth_get_result_size (const EVP_MD * md)
Definition at line 397 of file evp_lib.c.
EVP_MD_meth_new()
EVP_MD* EVP_MD_meth_new (int md_type, int pkey_type)
Definition at line 315 of file evp_lib.c.
EVP_MD_meth_set_app_datasize()
int EVP_MD_meth_set_app_datasize (EVP_MD * md, int datasize)
Definition at line 347 of file evp_lib.c.
EVP_MD_meth_set_cleanup()
int EVP_MD_meth_set_cleanup (EVP_MD * md, int(*)(EVP_MD_CTX *ctx) cleanup)
Definition at line 381 of file evp_lib.c.
EVP_MD_meth_set_copy()
int EVP_MD_meth_set_copy (EVP_MD * md, int(*)(EVP_MD_CTX *to, const EVP_MD_CTX *from) copy)
Definition at line 375 of file evp_lib.c.
EVP_MD_meth_set_ctrl()
int EVP_MD_meth_set_ctrl (EVP_MD * md, int(*)(EVP_MD_CTX *ctx, int cmd, int p1, void *p2) ctrl)
Definition at line 386 of file evp_lib.c.
EVP_MD_meth_set_final()
int EVP_MD_meth_set_final (EVP_MD * md, int(*)(EVP_MD_CTX *ctx, unsigned char *md) final)
Definition at line 369 of file evp_lib.c.
EVP_MD_meth_set_flags()
int EVP_MD_meth_set_flags (EVP_MD * md, unsigned long flags)
Definition at line 352 of file evp_lib.c.
EVP_MD_meth_set_init()
int EVP_MD_meth_set_init (EVP_MD * md, int(*)(EVP_MD_CTX *ctx) init)
Definition at line 357 of file evp_lib.c.
EVP_MD_meth_set_input_blocksize()
int EVP_MD_meth_set_input_blocksize (EVP_MD * md, int blocksize)
Definition at line 337 of file evp_lib.c.
EVP_MD_meth_set_result_size()
int EVP_MD_meth_set_result_size (EVP_MD * md, int resultsize)
Definition at line 342 of file evp_lib.c.
EVP_MD_meth_set_update()
int EVP_MD_meth_set_update (EVP_MD * md, int(*)(EVP_MD_CTX *ctx, const void *data, size_t count) update)
Definition at line 362 of file evp_lib.c.
EVP_MD_pkey_type()
int EVP_MD_pkey_type (const EVP_MD * md)
Definition at line 296 of file evp_lib.c.
Referenced by cms_DigestAlgorithm_find_ctx(), and PKCS7_signatureVerify().
EVP_MD_size()
int EVP_MD_size (const EVP_MD * md)
Definition at line 301 of file evp_lib.c.
Referenced by HMAC_size().
EVP_MD_type()
int EVP_MD_type (const EVP_MD * md)
Definition at line 291 of file evp_lib.c.
Referenced by PKCS12_setup_mac().
Variable Documentation
EVP_MD_CTX_update_fn
int(*)(EVP_MD_CTX *ctx, const void *data, size_t count) EVP_MD_CTX_update_fn(EVP_MD_CTX *ctx)
Definition at line 456 of file evp_lib.c.
EVP_MD_meth_get_cleanup
int(*)(EVP_MD_CTX *ctx) EVP_MD_meth_get_cleanup(const EVP_MD *md)
Definition at line 429 of file evp_lib.c.
EVP_MD_meth_get_copy
int(*)(EVP_MD_CTX *to, const EVP_MD_CTX *from) EVP_MD_meth_get_copy(const EVP_MD *md)
Definition at line 424 of file evp_lib.c.
EVP_MD_meth_get_ctrl
int(*)(EVP_MD_CTX *ctx, int cmd, int p1, void *p2) EVP_MD_meth_get_ctrl(const EVP_MD *md)
Definition at line 433 of file evp_lib.c.
EVP_MD_meth_get_final
int(*)(EVP_MD_CTX *ctx, unsigned char *md) EVP_MD_meth_get_final(const EVP_MD *md)
Definition at line 419 of file evp_lib.c.
EVP_MD_meth_get_init
int(*)(EVP_MD_CTX *ctx) EVP_MD_meth_get_init(const EVP_MD *md)
Definition at line 409 of file evp_lib.c.
EVP_MD_meth_get_update
int(*)(EVP_MD_CTX *ctx, const void *data, size_t count) EVP_MD_meth_get_update(const EVP_MD *md)
Definition at line 413 of file evp_lib.c.