crypto/include/internal/evp_int.h File Reference
evp_int.h File Reference
#include "internal/refcount.h"
Data Structures
struct EVP_PKEY_CTX
struct EVP_PKEY_METHOD
struct EVP_MD
struct EVP_CIPHER
struct EVP_PKEY
Macros
#define EVP_PKEY_FLAG_DYNAMIC 1
#define EVP_C_DATA(kstruct, ctx) ((kstruct *)EVP_CIPHER_CTX_get_cipher_data(ctx))
#define BLOCK_CIPHER_ecb_loop()
#define BLOCK_CIPHER_func_ecb(cname, cprefix, kstruct, ksched)
#define EVP_MAXCHUNK ((size_t)1<<(sizeof(long)*8-2))
#define BLOCK_CIPHER_func_ofb(cname, cprefix, cbits, kstruct, ksched)
#define BLOCK_CIPHER_func_cbc(cname, cprefix, kstruct, ksched)
#define BLOCK_CIPHER_func_cfb(cname, cprefix, cbits, kstruct, ksched)
#define BLOCK_CIPHER_all_funcs(cname, cprefix, cbits, kstruct, ksched)
#define BLOCK_CIPHER_def1(cname, nmode, mode, MODE, kstruct, nid, block_size, key_len, iv_len, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
#define BLOCK_CIPHER_def_cbc(cname, kstruct, nid, block_size, key_len, iv_len, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
#define BLOCK_CIPHER_def_cfb(cname, kstruct, nid, key_len, iv_len, cbits, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
#define BLOCK_CIPHER_def_ofb(cname, kstruct, nid, key_len, iv_len, cbits, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
#define BLOCK_CIPHER_def_ecb(cname, kstruct, nid, block_size, key_len, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
#define BLOCK_CIPHER_defs(cname, kstruct, nid, block_size, key_len, iv_len, cbits, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
#define IMPLEMENT_BLOCK_CIPHER(cname, ksched, cprefix, kstruct, nid, block_size, key_len, iv_len, cbits, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
#define IMPLEMENT_CFBR(cipher, cprefix, kstruct, ksched, keysize, cbits, iv_len, fl)
#define EVP_RC4_KEY_SIZE 16
#define TLS1_1_VERSION 0x0302
Functions
void evp_pkey_set_cb_translate (BN_GENCB *cb, EVP_PKEY_CTX *ctx)
void openssl_add_all_ciphers_int (void)
void openssl_add_all_digests_int (void)
void evp_cleanup_int (void)
Variables
const EVP_PKEY_METHOD cmac_pkey_meth
const EVP_PKEY_METHOD dh_pkey_meth
const EVP_PKEY_METHOD dhx_pkey_meth
const EVP_PKEY_METHOD dsa_pkey_meth
const EVP_PKEY_METHOD ec_pkey_meth
const EVP_PKEY_METHOD ecx25519_pkey_meth
const EVP_PKEY_METHOD hmac_pkey_meth
const EVP_PKEY_METHOD rsa_pkey_meth
const EVP_PKEY_METHOD rsa_pss_pkey_meth
const EVP_PKEY_METHOD tls1_prf_pkey_meth
const EVP_PKEY_METHOD hkdf_pkey_meth
const EVP_PKEY_METHOD poly1305_pkey_meth
const EVP_PKEY_METHOD siphash_pkey_meth
Macro Definition Documentation
BLOCK_CIPHER_all_funcs
#define BLOCK_CIPHER_all_funcs (cname, cprefix, cbits, kstruct, ksched)
Value:
BLOCK_CIPHER_func_cbc(cname, cprefix, kstruct, ksched) \
        BLOCK_CIPHER_func_cfb(cname, cprefix, cbits, kstruct, ksched) \
        BLOCK_CIPHER_func_ecb(cname, cprefix, kstruct, ksched) \
        BLOCK_CIPHER_func_ofb(cname, cprefix, cbits, kstruct, ksched)
Definition at line 219 of file evp_int.h.
BLOCK_CIPHER_def1
#define BLOCK_CIPHER_def1 (cname, nmode, mode, MODE, kstruct, nid, block_size, key_len, iv_len, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
Value:
static const EVP_CIPHER cname##_##mode = { \
        nid##_##nmode, block_size, key_len, iv_len, \
        flags | EVP_CIPH_##MODE##_MODE, \
        init_key, \
        cname##_##mode##_cipher, \
        cleanup, \
        sizeof(kstruct), \
        set_asn1, get_asn1,\
        ctrl, \
        NULL \
}; \
const EVP_CIPHER *EVP_##cname##_##mode(void) { return &cname##_##mode; }
Definition at line 225 of file evp_int.h.
BLOCK_CIPHER_def_cbc
#define BLOCK_CIPHER_def_cbc (cname, kstruct, nid, block_size, key_len, iv_len, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
Value:
BLOCK_CIPHER_def1(cname, cbc, cbc, CBC, kstruct, nid, block_size, key_len, \
                  iv_len, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
Definition at line 241 of file evp_int.h.
BLOCK_CIPHER_def_cfb
#define BLOCK_CIPHER_def_cfb (cname, kstruct, nid, key_len, iv_len, cbits, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
Value:
BLOCK_CIPHER_def1(cname, cfb##cbits, cfb##cbits, CFB, kstruct, nid, 1, \
                  key_len, iv_len, flags, init_key, cleanup, set_asn1, \
                  get_asn1, ctrl)
Definition at line 247 of file evp_int.h.
BLOCK_CIPHER_def_ecb
#define BLOCK_CIPHER_def_ecb (cname, kstruct, nid, block_size, key_len, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
Value:
BLOCK_CIPHER_def1(cname, ecb, ecb, ECB, kstruct, nid, block_size, key_len, \
                  0, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
Definition at line 261 of file evp_int.h.
BLOCK_CIPHER_def_ofb
#define BLOCK_CIPHER_def_ofb (cname, kstruct, nid, key_len, iv_len, cbits, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
Value:
BLOCK_CIPHER_def1(cname, ofb##cbits, ofb, OFB, kstruct, nid, 1, \
                  key_len, iv_len, flags, init_key, cleanup, set_asn1, \
                  get_asn1, ctrl)
Definition at line 254 of file evp_int.h.
BLOCK_CIPHER_defs
#define BLOCK_CIPHER_defs (cname, kstruct, nid, block_size, key_len, iv_len, cbits, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
Value:
BLOCK_CIPHER_def_cbc(cname, kstruct, nid, block_size, key_len, iv_len, flags, \
                     init_key, cleanup, set_asn1, get_asn1, ctrl) \
BLOCK_CIPHER_def_cfb(cname, kstruct, nid, key_len, iv_len, cbits, \
                     flags, init_key, cleanup, set_asn1, get_asn1, ctrl) \
BLOCK_CIPHER_def_ofb(cname, kstruct, nid, key_len, iv_len, cbits, \
                     flags, init_key, cleanup, set_asn1, get_asn1, ctrl) \
BLOCK_CIPHER_def_ecb(cname, kstruct, nid, block_size, key_len, flags, \
                     init_key, cleanup, set_asn1, get_asn1, ctrl)
Definition at line 267 of file evp_int.h.
BLOCK_CIPHER_ecb_loop
#define BLOCK_CIPHER_ecb_loop ()
Value:
size_t i, bl; \
        bl = EVP_CIPHER_CTX_cipher(ctx)->block_size;    \
        if (inl < bl) return 1;\
        inl -= bl; \
        for (i=0; i <= inl; i+=bl)
Definition at line 144 of file evp_int.h.
BLOCK_CIPHER_func_cbc
#define BLOCK_CIPHER_func_cbc (cname, cprefix, kstruct, ksched)
Value:
static int cname##_cbc_cipher(EVP_CIPHER_CTX *ctx, unsigned char *out, const unsigned char *in, size_t inl) \
{\
        while(inl>=EVP_MAXCHUNK) \
            {\
            cprefix##_cbc_encrypt(in, out, (long)EVP_MAXCHUNK, &EVP_C_DATA(kstruct,ctx)->ksched, EVP_CIPHER_CTX_iv_noconst(ctx), EVP_CIPHER_CTX_encrypting(ctx));\
            inl-=EVP_MAXCHUNK;\
            in +=EVP_MAXCHUNK;\
            out+=EVP_MAXCHUNK;\
            }\
        if (inl)\
            cprefix##_cbc_encrypt(in, out, (long)inl, &EVP_C_DATA(kstruct,ctx)->ksched, EVP_CIPHER_CTX_iv_noconst(ctx), EVP_CIPHER_CTX_encrypting(ctx));\
        return 1;\
}
Definition at line 180 of file evp_int.h.
BLOCK_CIPHER_func_cfb
#define BLOCK_CIPHER_func_cfb (cname, cprefix, cbits, kstruct, ksched)
Value:
static int cname##_cfb##cbits##_cipher(EVP_CIPHER_CTX *ctx, unsigned char *out, const unsigned char *in, size_t inl) \
{\
    size_t chunk = EVP_MAXCHUNK;\
    if (cbits == 1)  chunk >>= 3;\
    if (inl < chunk) chunk = inl;\
    while (inl && inl >= chunk)\
    {\
        int num = EVP_CIPHER_CTX_num(ctx);\
        cprefix##_cfb##cbits##_encrypt(in, out, (long) \
            ((cbits == 1) \
                && !EVP_CIPHER_CTX_test_flags(ctx, EVP_CIPH_FLAG_LENGTH_BITS) \
                ? inl*8 : inl), \
            &EVP_C_DATA(kstruct, ctx)->ksched, EVP_CIPHER_CTX_iv_noconst(ctx),\
            &num, EVP_CIPHER_CTX_encrypting(ctx));\
        EVP_CIPHER_CTX_set_num(ctx, num);\
        inl -= chunk;\
        in += chunk;\
        out += chunk;\
        if (inl < chunk) chunk = inl;\
    }\
    return 1;\
}
Definition at line 195 of file evp_int.h.
BLOCK_CIPHER_func_ecb
#define BLOCK_CIPHER_func_ecb (cname, cprefix, kstruct, ksched)
Value:
static int cname##_ecb_cipher(EVP_CIPHER_CTX *ctx, unsigned char *out, const unsigned char *in, size_t inl) \
{\
        BLOCK_CIPHER_ecb_loop() \
            cprefix##_ecb_encrypt(in + i, out + i, &EVP_C_DATA(kstruct,ctx)->ksched, EVP_CIPHER_CTX_encrypting(ctx)); \
        return 1;\
}
Definition at line 151 of file evp_int.h.
BLOCK_CIPHER_func_ofb
#define BLOCK_CIPHER_func_ofb (cname, cprefix, cbits, kstruct, ksched)
Value:
static int cname##_ofb_cipher(EVP_CIPHER_CTX *ctx, unsigned char *out, const unsigned char *in, size_t inl) \
{\
        while(inl>=EVP_MAXCHUNK) {\
            int num = EVP_CIPHER_CTX_num(ctx);\
            cprefix##_ofb##cbits##_encrypt(in, out, (long)EVP_MAXCHUNK, &EVP_C_DATA(kstruct,ctx)->ksched, EVP_CIPHER_CTX_iv_noconst(ctx), &num); \
            EVP_CIPHER_CTX_set_num(ctx, num);\
            inl-=EVP_MAXCHUNK;\
            in +=EVP_MAXCHUNK;\
            out+=EVP_MAXCHUNK;\
        }\
        if (inl) {\
            int num = EVP_CIPHER_CTX_num(ctx);\
            cprefix##_ofb##cbits##_encrypt(in, out, (long)inl, &EVP_C_DATA(kstruct,ctx)->ksched, EVP_CIPHER_CTX_iv_noconst(ctx), &num); \
            EVP_CIPHER_CTX_set_num(ctx, num);\
        }\
        return 1;\
}
Definition at line 161 of file evp_int.h.
EVP_C_DATA
#define EVP_C_DATA (kstruct, ctx) ((kstruct *)EVP_CIPHER_CTX_get_cipher_data(ctx))
Definition at line 141 of file evp_int.h.
Referenced by BLOCK_CIPHER_custom(), and if().
EVP_MAXCHUNK
#define EVP_MAXCHUNK ((size_t)1<<(sizeof(long)*8-2))
Definition at line 159 of file evp_int.h.
EVP_PKEY_FLAG_DYNAMIC
#define EVP_PKEY_FLAG_DYNAMIC 1
Definition at line 34 of file evp_int.h.
Referenced by EVP_PKEY_meth_free(), and EVP_PKEY_meth_new().
EVP_RC4_KEY_SIZE
#define EVP_RC4_KEY_SIZE 16
Definition at line 391 of file evp_int.h.
IMPLEMENT_BLOCK_CIPHER
#define IMPLEMENT_BLOCK_CIPHER (cname, ksched, cprefix, kstruct, nid, block_size, key_len, iv_len, cbits, flags, init_key, cleanup, set_asn1, get_asn1, ctrl)
Value:
BLOCK_CIPHER_all_funcs(cname, cprefix, cbits, kstruct, ksched) \
        BLOCK_CIPHER_defs(cname, kstruct, nid, block_size, key_len, iv_len, \
                          cbits, flags, init_key, cleanup, set_asn1, \
                          get_asn1, ctrl)
Definition at line 337 of file evp_int.h.
IMPLEMENT_CFBR
#define IMPLEMENT_CFBR (cipher, cprefix, kstruct, ksched, keysize, cbits, iv_len, fl)
Value:
BLOCK_CIPHER_func_cfb(cipher##_##keysize,cprefix,cbits,kstruct,ksched) \
        BLOCK_CIPHER_def_cfb(cipher##_##keysize,kstruct, \
                             NID_##cipher##_##keysize, keysize/8, iv_len, cbits, \
                             (fl)|EVP_CIPH_FLAG_DEFAULT_ASN1, \
                             cipher##_init_key, NULL, NULL, NULL, NULL)
Definition at line 346 of file evp_int.h.
TLS1_1_VERSION
#define TLS1_1_VERSION 0x0302
Definition at line 393 of file evp_int.h.
Referenced by ssl_protocol_to_string().
Function Documentation
evp_cleanup_int()
void evp_cleanup_int (void)
Definition at line 80 of file names.c.
References EVP_PBE_cleanup(), OBJ_NAME_cleanup(), OBJ_NAME_TYPE_CIPHER_METH, OBJ_NAME_TYPE_MD_METH, and OBJ_sigid_free().
evp_pkey_set_cb_translate()
void evp_pkey_set_cb_translate (BN_GENCB * cb, EVP_PKEY_CTX * ctx)
Definition at line 138 of file pmeth_gn.c.
References BN_GENCB_set().
openssl_add_all_ciphers_int()
void openssl_add_all_ciphers_int (void)
Definition at line 17 of file c_allc.c.
References EVP_add_cipher(), EVP_add_cipher_alias, EVP_aes_128_cbc(), EVP_aes_128_cbc_hmac_sha1(), EVP_aes_128_cbc_hmac_sha256(), EVP_aes_128_ccm(), EVP_aes_128_cfb(), EVP_aes_128_cfb1(), EVP_aes_128_cfb8(), EVP_aes_128_ctr(), EVP_aes_128_ecb(), EVP_aes_128_gcm(), EVP_aes_128_ocb(), EVP_aes_128_ofb(), EVP_aes_128_wrap(), EVP_aes_128_wrap_pad(), EVP_aes_128_xts(), EVP_aes_192_cbc(), EVP_aes_192_ccm(), EVP_aes_192_cfb(), EVP_aes_192_cfb1(), EVP_aes_192_cfb8(), EVP_aes_192_ctr(), EVP_aes_192_ecb(), EVP_aes_192_gcm(), EVP_aes_192_ocb(), EVP_aes_192_ofb(), EVP_aes_192_wrap(), EVP_aes_192_wrap_pad(), EVP_aes_256_cbc(), EVP_aes_256_cbc_hmac_sha1(), EVP_aes_256_cbc_hmac_sha256(), EVP_aes_256_ccm(), EVP_aes_256_cfb(), EVP_aes_256_cfb1(), EVP_aes_256_cfb8(), EVP_aes_256_ctr(), EVP_aes_256_ecb(), EVP_aes_256_gcm(), EVP_aes_256_ocb(), EVP_aes_256_ofb(), EVP_aes_256_wrap(), EVP_aes_256_wrap_pad(), EVP_aes_256_xts(), EVP_bf_cbc(), EVP_bf_cfb(), EVP_bf_ecb(), EVP_bf_ofb(), EVP_camellia_128_cbc(), EVP_camellia_128_cfb, EVP_camellia_128_cfb1(), EVP_camellia_128_cfb8(), EVP_camellia_128_ctr(), EVP_camellia_128_ecb(), EVP_camellia_128_ofb(), EVP_camellia_192_cbc(), EVP_camellia_192_cfb, EVP_camellia_192_cfb1(), EVP_camellia_192_cfb8(), EVP_camellia_192_ctr(), EVP_camellia_192_ecb(), EVP_camellia_192_ofb(), EVP_camellia_256_cbc(), EVP_camellia_256_cfb, EVP_camellia_256_cfb1(), EVP_camellia_256_cfb8(), EVP_camellia_256_ctr(), EVP_camellia_256_ecb(), EVP_camellia_256_ofb(), EVP_cast5_cbc(), EVP_cast5_cfb(), EVP_cast5_ecb(), EVP_cast5_ofb(), EVP_chacha20(), EVP_chacha20_poly1305(), EVP_des_cbc(), EVP_des_cfb(), EVP_des_cfb1(), EVP_des_cfb8(), EVP_des_ecb(), EVP_des_ede(), EVP_des_ede3(), EVP_des_ede3_cbc(), EVP_des_ede3_cfb(), EVP_des_ede3_cfb1(), EVP_des_ede3_cfb8(), EVP_des_ede3_ofb(), EVP_des_ede3_wrap(), EVP_des_ede_cbc(), EVP_des_ede_cfb(), EVP_des_ede_ofb(), EVP_des_ofb(), EVP_desx_cbc(), EVP_idea_cbc(), EVP_idea_cfb(), EVP_idea_ecb(), EVP_idea_ofb(), EVP_rc2_40_cbc(), EVP_rc2_64_cbc(), EVP_rc2_cbc(), EVP_rc2_cfb(), EVP_rc2_ecb(), EVP_rc2_ofb(), EVP_rc4(), EVP_rc4_40(), EVP_rc4_hmac_md5(), EVP_rc5_32_12_16_cbc(), EVP_rc5_32_12_16_cfb(), EVP_rc5_32_12_16_ecb(), EVP_rc5_32_12_16_ofb(), EVP_seed_cbc(), EVP_seed_cfb, EVP_seed_ecb(), EVP_seed_ofb(), SN_aes_128_cbc, SN_aes_192_cbc, SN_aes_256_cbc, SN_bf_cbc, SN_camellia_128_cbc, SN_camellia_192_cbc, SN_camellia_256_cbc, SN_cast5_cbc, SN_des_cbc, SN_des_ede3_cbc, SN_des_ede3_ecb, SN_des_ede_ecb, SN_desx_cbc, SN_id_aes128_wrap, SN_id_aes192_wrap, SN_id_aes256_wrap, SN_id_smime_alg_CMS3DESwrap, SN_idea_cbc, SN_rc2_40_cbc, SN_rc2_64_cbc, SN_rc2_cbc, SN_rc5_cbc, and SN_seed_cbc.
Referenced by DEFINE_RUN_ONCE_STATIC().
openssl_add_all_digests_int()
void openssl_add_all_digests_int (void)
Definition at line 17 of file c_alld.c.
References EVP_add_digest(), EVP_add_digest_alias, EVP_blake2b512(), EVP_blake2s256(), EVP_md4(), EVP_md5(), EVP_md5_sha1(), EVP_mdc2(), EVP_ripemd160(), EVP_sha1(), EVP_sha224(), EVP_sha256(), EVP_sha384(), EVP_sha512(), EVP_whirlpool(), SN_md5, SN_ripemd160, SN_sha1, SN_sha1WithRSA, and SN_sha1WithRSAEncryption.
Referenced by DEFINE_RUN_ONCE_STATIC().
Variable Documentation
cmac_pkey_meth
const EVP_PKEY_METHOD cmac_pkey_meth
Definition at line 130 of file cm_pmeth.c.
dh_pkey_meth
const EVP_PKEY_METHOD dh_pkey_meth
Definition at line 435 of file dh_pmeth.c.
dhx_pkey_meth
const EVP_PKEY_METHOD dhx_pkey_meth
Definition at line 469 of file dh_pmeth.c.
dsa_pkey_meth
const EVP_PKEY_METHOD dsa_pkey_meth
Definition at line 246 of file dsa_pmeth.c.
ec_pkey_meth
const EVP_PKEY_METHOD ec_pkey_meth
Definition at line 428 of file ec_pmeth.c.
ecx25519_pkey_meth
const EVP_PKEY_METHOD ecx25519_pkey_meth
Definition at line 365 of file ecx_meth.c.
hkdf_pkey_meth
const EVP_PKEY_METHOD hkdf_pkey_meth
Definition at line 206 of file hkdf.c.
hmac_pkey_meth
const EVP_PKEY_METHOD hmac_pkey_meth
Definition at line 179 of file hm_pmeth.c.
poly1305_pkey_meth
const EVP_PKEY_METHOD poly1305_pkey_meth
Definition at line 161 of file poly1305_pmeth.c.
rsa_pkey_meth
const EVP_PKEY_METHOD rsa_pkey_meth
Definition at line 726 of file rsa_pmeth.c.
rsa_pss_pkey_meth
const EVP_PKEY_METHOD rsa_pss_pkey_meth
Definition at line 808 of file rsa_pmeth.c.
siphash_pkey_meth
const EVP_PKEY_METHOD siphash_pkey_meth
Definition at line 175 of file siphash_pmeth.c.
tls1_prf_pkey_meth
const EVP_PKEY_METHOD tls1_prf_pkey_meth
Definition at line 134 of file tls1_prf.c.