crypto/ex_data.c File Reference
ex_data.c File Reference
#include "internal/cryptlib_int.h"
#include "internal/thread_once.h"
#include <openssl/lhash.h>
Data Structures
struct EX_CALLBACK
struct EX_CALLBACKS
Functions
DEFINE_RUN_ONCE_STATIC (do_ex_data_init)
void crypto_cleanup_all_ex_data_int (void)
int CRYPTO_free_ex_index (int class_index, int idx)
int CRYPTO_get_ex_new_index (int class_index, long argl, void *argp, CRYPTO_EX_new *new_func, CRYPTO_EX_dup *dup_func, CRYPTO_EX_free *free_func)
int CRYPTO_new_ex_data (int class_index, void *obj, CRYPTO_EX_DATA *ad)
int CRYPTO_dup_ex_data (int class_index, CRYPTO_EX_DATA *to, const CRYPTO_EX_DATA *from)
void CRYPTO_free_ex_data (int class_index, void *obj, CRYPTO_EX_DATA *ad)
int CRYPTO_set_ex_data (CRYPTO_EX_DATA *ad, int idx, void *val)
void * CRYPTO_get_ex_data (const CRYPTO_EX_DATA *ad, int idx)
Function Documentation
crypto_cleanup_all_ex_data_int()
void crypto_cleanup_all_ex_data_int (void)
Definition at line 93 of file ex_data.c.
References CRYPTO_EX_INDEX__COUNT.
CRYPTO_dup_ex_data()
int CRYPTO_dup_ex_data (int class_index, CRYPTO_EX_DATA * to, const CRYPTO_EX_DATA * from)
Definition at line 253 of file ex_data.c.
References NULL, and ptr.
Referenced by EC_KEY_copy(), and ssl_session_dup().
CRYPTO_free_ex_data()
void CRYPTO_free_ex_data (int class_index, void * obj, CRYPTO_EX_DATA * ad)
Definition at line 305 of file ex_data.c.
References NULL, and ptr.
Referenced by bio_free_ex_data(), BIO_new(), DH_free(), DSA_free(), EC_KEY_free(), engine_free_util(), RSA_free(), SSL_SESSION_free(), and X509_STORE_CTX_cleanup().
CRYPTO_free_ex_index()
int CRYPTO_free_ex_index (int class_index, int idx)
Definition at line 130 of file ex_data.c.
CRYPTO_get_ex_data()
void* CRYPTO_get_ex_data (const CRYPTO_EX_DATA * ad, int idx)
Definition at line 379 of file ex_data.c.
CRYPTO_get_ex_new_index()
int CRYPTO_get_ex_new_index (int class_index, long argl, void * argp, CRYPTO_EX_new * new_func, CRYPTO_EX_dup * dup_func, CRYPTO_EX_free * free_func)
Definition at line 155 of file ex_data.c.
CRYPTO_new_ex_data()
int CRYPTO_new_ex_data (int class_index, void * obj, CRYPTO_EX_DATA * ad)
Definition at line 208 of file ex_data.c.
References NULL, and ptr.
Referenced by BIO_new(), SSL_new(), and SSL_SESSION_new().
CRYPTO_set_ex_data()
int CRYPTO_set_ex_data (CRYPTO_EX_DATA * ad, int idx, void * val)
Definition at line 354 of file ex_data.c.
DEFINE_RUN_ONCE_STATIC()
DEFINE_RUN_ONCE_STATIC (do_ex_data_init)
Definition at line 39 of file ex_data.c.
References NULL, and OPENSSL_init_crypto().