ssl/statem/extensions.c File Reference
extensions.c File Reference
#include "../ssl_locl.h"
#include "statem_locl.h"
Data Structures
struct EXTENSION_DEFINITION
Macros
#define INVALID_EXTENSION { 0x10000, 0, NULL, NULL, NULL, NULL, NULL, NULL }
Functions
int tls_collect_extensions (SSL *s, PACKET *packet, unsigned int context, RAW_EXTENSION **res, int *al)
int tls_parse_extension (SSL *s, TLSEXT_INDEX idx, int context, RAW_EXTENSION *exts, X509 *x, size_t chainidx, int *al)
int tls_parse_all_extensions (SSL *s, int context, RAW_EXTENSION *exts, X509 *x, size_t chainidx, int *al)
int tls_construct_extensions (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_psk_do_binder (SSL *s, const EVP_MD *md, const unsigned char *msgstart, size_t binderoffset, const unsigned char *binderin, unsigned char *binderout, SSL_SESSION *sess, int sign)
Macro Definition Documentation
INVALID_EXTENSION
#define INVALID_EXTENSION { 0x10000, 0, NULL, NULL, NULL, NULL, NULL, NULL }
Definition at line 104 of file extensions.c.
Function Documentation
tls_collect_extensions()
int tls_collect_extensions (SSL * s, PACKET * packet, unsigned int context, RAW_EXTENSION ** res, int * al)
Definition at line 384 of file extensions.c.
References custom_ext_init(), ERR_R_MALLOC_FAILURE, EXT_CLIENT_HELLO, EXT_TLS1_2_SERVER_HELLO, custom_ext_methods::meths_count, NULL, OPENSSL_zalloc, OSSL_NELEM, SSL_AD_INTERNAL_ERROR, SSL_F_TLS_COLLECT_EXTENSIONS, and SSLerr.
tls_construct_extensions()
int tls_construct_extensions (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 587 of file extensions.c.
References EXTENSION_DEFINITION::construct_ctos, EXTENSION_DEFINITION::construct_stoc, EXTENSION_DEFINITION::context, custom_ext_add(), custom_ext_init(), ERR_R_INTERNAL_ERROR, EXT_CLIENT_HELLO, EXT_SSL3_ALLOWED, EXT_TLS1_2_AND_BELOW_ONLY, EXT_TLS1_2_SERVER_HELLO, EXT_TLS1_3_ONLY, EXT_TLS_IMPLEMENTATION_ONLY, NULL, OSSL_NELEM, SSL3_VERSION, SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_EXTENSIONS, ssl_get_client_min_max_version(), SSL_IS_DTLS, SSL_IS_TLS13, SSLerr, TLS1_3_VERSION, WPACKET_close(), WPACKET_FLAGS_ABANDON_ON_ZERO_LENGTH, WPACKET_set_flags(), and WPACKET_start_sub_packet_u16.
Referenced by tls_construct_server_hello().
tls_parse_all_extensions()
int tls_parse_all_extensions (SSL * s, int context, RAW_EXTENSION * exts, X509 * x, size_t chainidx, int * al)
Definition at line 545 of file extensions.c.
References EXTENSION_DEFINITION::context, EXT_CLIENT_HELLO, EXT_TLS1_2_SERVER_HELLO, EXTENSION_DEFINITION::final, NULL, OSSL_NELEM, and tls_parse_extension().
tls_parse_extension()
int tls_parse_extension (SSL * s, TLSEXT_INDEX idx, int context, RAW_EXTENSION * exts, X509 * x, size_t chainidx, int * al)
Definition at line 475 of file extensions.c.
Referenced by tls_parse_all_extensions().
tls_psk_do_binder()
int tls_psk_do_binder (SSL * s, const EVP_MD * md, const unsigned char * msgstart, size_t binderoffset, const unsigned char * binderin, unsigned char * binderout, SSL_SESSION * sess, int sign)
Definition at line 1093 of file extensions.c.