ssl/statem/extensions_clnt.c File Reference
extensions_clnt.c File Reference
#include <assert.h>
#include <openssl/ocsp.h>
#include "../ssl_locl.h"
#include "statem_locl.h"
Macros
#define F5_WORKAROUND_MIN_MSG_LEN 0xff
#define F5_WORKAROUND_MAX_MSG_LEN 0x200
Functions
int tls_construct_ctos_renegotiate (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_server_name (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_srp (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_ec_pt_formats (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_supported_groups (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_session_ticket (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_sig_algs (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_status_request (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_npn (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_alpn (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_use_srtp (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_etm (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_sct (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_ems (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_supported_versions (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_psk_kex_modes (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_key_share (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_padding (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_psk (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_renegotiate (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_server_name (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_ec_pt_formats (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_session_ticket (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_status_request (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_sct (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_npn (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_alpn (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_use_srtp (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_etm (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_ems (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_key_share (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_psk (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
Macro Definition Documentation
F5_WORKAROUND_MAX_MSG_LEN
#define F5_WORKAROUND_MAX_MSG_LEN 0x200
Definition at line 640 of file extensions_clnt.c.
Referenced by tls_construct_ctos_padding().
F5_WORKAROUND_MIN_MSG_LEN
#define F5_WORKAROUND_MIN_MSG_LEN 0xff
Definition at line 639 of file extensions_clnt.c.
Referenced by tls_construct_ctos_padding().
Function Documentation
tls_construct_ctos_alpn()
int tls_construct_ctos_alpn (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 342 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_ALPN, SSL_IS_FIRST_HANDSHAKE, SSLerr, TLSEXT_TYPE_application_layer_protocol_negotiation, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_sub_memcpy_u16.
tls_construct_ctos_ec_pt_formats()
int tls_construct_ctos_ec_pt_formats (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 111 of file extensions_clnt.c.
tls_construct_ctos_ems()
int tls_construct_ctos_ems (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 442 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CTOS_EMS, SSLerr, TLSEXT_TYPE_extended_master_secret, and WPACKET_put_bytes_u16.
tls_construct_ctos_etm()
int tls_construct_ctos_etm (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 406 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CTOS_ETM, SSL_OP_NO_ENCRYPT_THEN_MAC, SSLerr, TLSEXT_TYPE_encrypt_then_mac, and WPACKET_put_bytes_u16.
tls_construct_ctos_key_share()
int tls_construct_ctos_key_share (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 575 of file extensions_clnt.c.
References bytestogroup, ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_KEY_SHARE, SSL_R_NO_SUITABLE_KEY_SHARE, SSL_SECOP_CURVE_SUPPORTED, SSLerr, tls1_get_curvelist(), tls_curve_allowed(), TLSEXT_TYPE_key_share, WPACKET_put_bytes_u16, and WPACKET_start_sub_packet_u16.
tls_construct_ctos_npn()
int tls_construct_ctos_npn (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 322 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_NPN, SSL_IS_FIRST_HANDSHAKE, SSLerr, TLSEXT_TYPE_next_proto_neg, and WPACKET_put_bytes_u16.
tls_construct_ctos_padding()
int tls_construct_ctos_padding (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 642 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, F5_WORKAROUND_MAX_MSG_LEN, F5_WORKAROUND_MIN_MSG_LEN, SSL_F_TLS_CONSTRUCT_CTOS_PADDING, SSL_OP_TLSEXT_PADDING, SSLerr, TLSEXT_TYPE_padding, WPACKET_get_total_written(), WPACKET_put_bytes_u16, and WPACKET_sub_allocate_bytes_u16.
tls_construct_ctos_psk()
int tls_construct_ctos_psk (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 689 of file extensions_clnt.c.
References NULL.
tls_construct_ctos_psk_kex_modes()
int tls_construct_ctos_psk_kex_modes (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 506 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CTOS_PSK_KEX_MODES, SSLerr, TLSEXT_KEX_MODE_FLAG_KE, TLSEXT_KEX_MODE_FLAG_KE_DHE, TLSEXT_KEX_MODE_KE, TLSEXT_KEX_MODE_KE_DHE, TLSEXT_TYPE_psk_kex_modes, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_put_bytes_u8, WPACKET_start_sub_packet_u16, and WPACKET_start_sub_packet_u8.
tls_construct_ctos_renegotiate()
int tls_construct_ctos_renegotiate (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 15 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CTOS_RENEGOTIATE, SSLerr, TLSEXT_TYPE_renegotiate, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_sub_memcpy_u8.
tls_construct_ctos_sct()
int tls_construct_ctos_sct (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 422 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_SCT, SSLerr, TLSEXT_TYPE_signed_certificate_timestamp, and WPACKET_put_bytes_u16.
tls_construct_ctos_server_name()
int tls_construct_ctos_server_name (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 34 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_SERVER_NAME, SSLerr, TLSEXT_NAMETYPE_host_name, TLSEXT_TYPE_server_name, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_put_bytes_u8, WPACKET_start_sub_packet_u16, and WPACKET_sub_memcpy_u16.
tls_construct_ctos_session_ticket()
int tls_construct_ctos_session_ticket (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 186 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, OPENSSL_malloc, SSL_F_TLS_CONSTRUCT_CTOS_SESSION_TICKET, SSLerr, TLS1_3_VERSION, tls_use_ticket(), TLSEXT_TYPE_session_ticket, WPACKET_put_bytes_u16, and WPACKET_sub_memcpy_u16.
tls_construct_ctos_sig_algs()
int tls_construct_ctos_sig_algs (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 228 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SSL_CLIENT_USE_SIGALGS, SSL_F_TLS_CONSTRUCT_CTOS_SIG_ALGS, SSLerr, tls12_copy_sigalgs(), tls12_get_psigalgs(), TLSEXT_TYPE_signature_algorithms, WPACKET_close(), WPACKET_put_bytes_u16, and WPACKET_start_sub_packet_u16.
tls_construct_ctos_srp()
int tls_construct_ctos_srp (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 59 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_SRP, SSLerr, TLSEXT_TYPE_srp, WPACKET_close(), WPACKET_FLAGS_NON_ZERO_LENGTH, WPACKET_memcpy(), WPACKET_put_bytes_u16, WPACKET_set_flags(), WPACKET_start_sub_packet_u16, and WPACKET_start_sub_packet_u8.
tls_construct_ctos_status_request()
int tls_construct_ctos_status_request (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 254 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_STATUS_REQUEST, SSLerr, TLSEXT_STATUSTYPE_ocsp, TLSEXT_TYPE_status_request, WPACKET_allocate_bytes(), WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_put_bytes_u8, WPACKET_start_sub_packet_u16, and WPACKET_sub_allocate_bytes_u16.
tls_construct_ctos_supported_groups()
int tls_construct_ctos_supported_groups (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 135 of file extensions_clnt.c.
References NULL.
tls_construct_ctos_supported_versions()
int tls_construct_ctos_supported_versions (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 454 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CTOS_SUPPORTED_VERSIONS, ssl_get_client_min_max_version(), SSLerr, TLS1_3_VERSION, TLS1_3_VERSION_DRAFT, TLSEXT_TYPE_supported_versions, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_start_sub_packet_u8.
tls_construct_ctos_use_srtp()
int tls_construct_ctos_use_srtp (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 366 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SRTP_PROTECTION_PROFILE::id, NULL, SSL_F_TLS_CONSTRUCT_CTOS_USE_SRTP, SSLerr, STACK_OF, TLSEXT_TYPE_use_srtp, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_put_bytes_u8, and WPACKET_start_sub_packet_u16.
tls_parse_stoc_alpn()
int tls_parse_stoc_alpn (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1076 of file extensions_clnt.c.
References len, and SSL_AD_UNSUPPORTED_EXTENSION.
tls_parse_stoc_ec_pt_formats()
int tls_parse_stoc_ec_pt_formats (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 883 of file extensions_clnt.c.
tls_parse_stoc_ems()
int tls_parse_stoc_ems (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1180 of file extensions_clnt.c.
References SSL_SESS_FLAG_EXTMS, and TLS1_FLAGS_RECEIVED_EXTMS.
tls_parse_stoc_etm()
int tls_parse_stoc_etm (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1168 of file extensions_clnt.c.
References SSL_AEAD, SSL_OP_NO_ENCRYPT_THEN_MAC, and SSL_RC4.
tls_parse_stoc_key_share()
int tls_parse_stoc_key_share (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1190 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_AD_INTERNAL_ERROR, SSL_F_TLS_PARSE_STOC_KEY_SHARE, and SSLerr.
tls_parse_stoc_npn()
int tls_parse_stoc_npn (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1025 of file extensions_clnt.c.
References NULL, SSL_AD_UNSUPPORTED_EXTENSION, and SSL_IS_FIRST_HANDSHAKE.
tls_parse_stoc_psk()
int tls_parse_stoc_psk (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1297 of file extensions_clnt.c.
tls_parse_stoc_renegotiate()
int tls_parse_stoc_renegotiate (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 801 of file extensions_clnt.c.
References data.
tls_parse_stoc_sct()
int tls_parse_stoc_sct (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 971 of file extensions_clnt.c.
References NULL.
tls_parse_stoc_server_name()
int tls_parse_stoc_server_name (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 859 of file extensions_clnt.c.
References NULL.
tls_parse_stoc_session_ticket()
int tls_parse_stoc_session_ticket (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 918 of file extensions_clnt.c.
References NULL.
tls_parse_stoc_status_request()
int tls_parse_stoc_status_request (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 940 of file extensions_clnt.c.
References SSL_IS_TLS13, and TLSEXT_STATUSTYPE_nothing.
tls_parse_stoc_use_srtp()
int tls_parse_stoc_use_srtp (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1114 of file extensions_clnt.c.
References STACK_OF.