ssl/statem/extensions_srvr.c File Reference
extensions_srvr.c File Reference
#include <openssl/ocsp.h>
#include "../ssl_locl.h"
#include "statem_locl.h"
Functions
int tls_parse_ctos_renegotiate (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_server_name (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_srp (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_ec_pt_formats (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_session_ticket (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_sig_algs (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_status_request (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_npn (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_alpn (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_use_srtp (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_etm (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_psk_kex_modes (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_key_share (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_supported_groups (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_ems (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_psk (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_renegotiate (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_server_name (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_ec_pt_formats (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_session_ticket (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_status_request (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_next_proto_neg (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_alpn (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_use_srtp (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_etm (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_ems (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_key_share (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_cryptopro_bug (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_psk (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
Function Documentation
tls_construct_stoc_alpn()
int tls_construct_stoc_alpn (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 911 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_STOC_ALPN, SSLerr, TLSEXT_TYPE_application_layer_protocol_negotiation, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_sub_memcpy_u8.
tls_construct_stoc_cryptopro_bug()
int tls_construct_stoc_cryptopro_bug (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1068 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_STOC_CRYPTOPRO_BUG, SSL_get_options(), SSL_OP_CRYPTOPRO_TLSEXT_BUG, SSLerr, and WPACKET_memcpy().
tls_construct_stoc_ec_pt_formats()
int tls_construct_stoc_ec_pt_formats (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 805 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_aECDSA, SSL_F_TLS_CONSTRUCT_STOC_EC_PT_FORMATS, SSL_kECDHE, SSLerr, tls1_get_formatlist(), TLSEXT_TYPE_ec_point_formats, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_sub_memcpy_u8.
tls_construct_stoc_ems()
int tls_construct_stoc_ems (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 980 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_STOC_EMS, SSLerr, TLS1_FLAGS_RECEIVED_EXTMS, TLSEXT_TYPE_extended_master_secret, and WPACKET_put_bytes_u16.
tls_construct_stoc_etm()
int tls_construct_stoc_etm (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 953 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_AEAD, SSL_eGOST2814789CNT, SSL_eGOST2814789CNT12, SSL_F_TLS_CONSTRUCT_STOC_ETM, SSL_RC4, SSLerr, TLSEXT_TYPE_encrypt_then_mac, and WPACKET_put_bytes_u16.
tls_construct_stoc_key_share()
int tls_construct_stoc_key_share (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 995 of file extensions_srvr.c.
References ERR_R_EC_LIB, ERR_R_INTERNAL_ERROR, ERR_R_MALLOC_FAILURE, EVP_PKEY_free(), EVP_PKEY_get1_tls_encodedpoint(), NULL, OPENSSL_free, SSL_AD_INTERNAL_ERROR, ssl_derive(), SSL_F_TLS_CONSTRUCT_STOC_KEY_SHARE, ssl_generate_pkey(), SSLerr, tls13_generate_handshake_secret(), TLSEXT_TYPE_key_share, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_sub_memcpy_u16.
tls_construct_stoc_next_proto_neg()
int tls_construct_stoc_next_proto_neg (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 882 of file extensions_srvr.c.
tls_construct_stoc_psk()
int tls_construct_stoc_psk (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1093 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_STOC_PSK, SSLerr, TLSEXT_TYPE_psk, WPACKET_close(), WPACKET_put_bytes_u16, and WPACKET_start_sub_packet_u16.
tls_construct_stoc_renegotiate()
int tls_construct_stoc_renegotiate (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 766 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_STOC_RENEGOTIATE, SSLerr, TLSEXT_TYPE_renegotiate, WPACKET_close(), WPACKET_memcpy(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_start_sub_packet_u8.
tls_construct_stoc_server_name()
int tls_construct_stoc_server_name (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 788 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_STOC_SERVER_NAME, SSLerr, TLSEXT_TYPE_server_name, and WPACKET_put_bytes_u16.
tls_construct_stoc_session_ticket()
int tls_construct_stoc_session_ticket (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 831 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_STOC_SESSION_TICKET, SSLerr, tls_use_ticket(), TLSEXT_TYPE_session_ticket, and WPACKET_put_bytes_u16.
tls_construct_stoc_status_request()
int tls_construct_stoc_status_request (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 850 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_STOC_STATUS_REQUEST, SSL_IS_TLS13, SSLerr, tls_construct_cert_status_body(), TLSEXT_TYPE_status_request, WPACKET_close(), WPACKET_put_bytes_u16, and WPACKET_start_sub_packet_u16.
tls_construct_stoc_use_srtp()
int tls_construct_stoc_use_srtp (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 933 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_STOC_USE_SRTP, SSLerr, TLSEXT_TYPE_use_srtp, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_put_bytes_u8, and WPACKET_start_sub_packet_u16.
tls_parse_ctos_alpn()
int tls_parse_ctos_alpn (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 342 of file extensions_srvr.c.
References SSL_IS_FIRST_HANDSHAKE.
tls_parse_ctos_ec_pt_formats()
int tls_parse_ctos_ec_pt_formats (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 166 of file extensions_srvr.c.
tls_parse_ctos_ems()
int tls_parse_ctos_ems (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 650 of file extensions_srvr.c.
tls_parse_ctos_etm()
int tls_parse_ctos_etm (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 450 of file extensions_srvr.c.
References SSL_OP_NO_ENCRYPT_THEN_MAC.
tls_parse_ctos_key_share()
int tls_parse_ctos_key_share (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 493 of file extensions_srvr.c.
tls_parse_ctos_npn()
int tls_parse_ctos_npn (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 323 of file extensions_srvr.c.
References SSL_IS_FIRST_HANDSHAKE.
tls_parse_ctos_psk()
int tls_parse_ctos_psk (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 664 of file extensions_srvr.c.
References NULL.
tls_parse_ctos_psk_kex_modes()
int tls_parse_ctos_psk_kex_modes (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 464 of file extensions_srvr.c.
tls_parse_ctos_renegotiate()
int tls_parse_ctos_renegotiate (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 17 of file extensions_srvr.c.
References data.
tls_parse_ctos_server_name()
int tls_parse_ctos_server_name (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 76 of file extensions_srvr.c.
tls_parse_ctos_session_ticket()
int tls_parse_ctos_session_ticket (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 190 of file extensions_srvr.c.
tls_parse_ctos_sig_algs()
int tls_parse_ctos_sig_algs (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 204 of file extensions_srvr.c.
tls_parse_ctos_srp()
int tls_parse_ctos_srp (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 141 of file extensions_srvr.c.
tls_parse_ctos_status_request()
int tls_parse_ctos_status_request (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 224 of file extensions_srvr.c.
References NULL.
tls_parse_ctos_supported_groups()
int tls_parse_ctos_supported_groups (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 623 of file extensions_srvr.c.
tls_parse_ctos_use_srtp()
int tls_parse_ctos_use_srtp (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 379 of file extensions_srvr.c.
References NULL, and STACK_OF.