fuzz/fuzzer.h File Reference
fuzzer.h File Reference
Functions
int FuzzerTestOneInput (const uint8_t *buf, size_t len)
int FuzzerInitialize (int *argc, char ***argv)
void FuzzerCleanup (void)
Function Documentation
FuzzerCleanup()
void FuzzerCleanup (void)
Definition at line 233 of file asn1.c.
References ASN1_PCTX_free(), BIO_free(), bio_out, and BN_free().
FuzzerInitialize()
int FuzzerInitialize (int * argc, char *** argv)
Definition at line 189 of file asn1.c.
FuzzerTestOneInput()
int FuzzerTestOneInput (const uint8_t * buf, size_t len)
Definition at line 205 of file asn1.c.