crypto/modes/gcm128.c File Reference
gcm128.c File Reference
#include <openssl/crypto.h>
#include "modes_lcl.h"
#include <string.h>
Macros
#define PACK(s) ((size_t)(s)<<(sizeof(size_t)*8-16))
#define REDUCE1BIT(V)
#define GCM_MUL(ctx, Xi) gcm_gmult_4bit(ctx->Xi.u,ctx->Htable)
#define GHASH(ctx, in, len) gcm_ghash_4bit((ctx)->Xi.u,(ctx)->Htable,in,len)
#define GHASH_CHUNK (3*1024)
#define CTX__GHASH(f) (ctx->ghash = (f))
Functions
void CRYPTO_gcm128_init (GCM128_CONTEXT *ctx, void *key, block128_f block)
void CRYPTO_gcm128_setiv (GCM128_CONTEXT *ctx, const unsigned char *iv, size_t len)
int CRYPTO_gcm128_aad (GCM128_CONTEXT *ctx, const unsigned char *aad, size_t len)
int CRYPTO_gcm128_encrypt (GCM128_CONTEXT *ctx, const unsigned char *in, unsigned char *out, size_t len)
int CRYPTO_gcm128_decrypt (GCM128_CONTEXT *ctx, const unsigned char *in, unsigned char *out, size_t len)
int CRYPTO_gcm128_encrypt_ctr32 (GCM128_CONTEXT *ctx, const unsigned char *in, unsigned char *out, size_t len, ctr128_f stream)
int CRYPTO_gcm128_decrypt_ctr32 (GCM128_CONTEXT *ctx, const unsigned char *in, unsigned char *out, size_t len, ctr128_f stream)
int CRYPTO_gcm128_finish (GCM128_CONTEXT *ctx, const unsigned char *tag, size_t len)
void CRYPTO_gcm128_tag (GCM128_CONTEXT *ctx, unsigned char *tag, size_t len)
GCM128_CONTEXT * CRYPTO_gcm128_new (void *key, block128_f block)
void CRYPTO_gcm128_release (GCM128_CONTEXT *ctx)
Macro Definition Documentation
CTX__GHASH
#define CTX__GHASH (f) (ctx->ghash = (f))
Referenced by CRYPTO_gcm128_init().
GCM_MUL
#define GCM_MUL (ctx, Xi) gcm_gmult_4bit(ctx->Xi.u,ctx->Htable)
Definition at line 553 of file gcm128.c.
Referenced by CRYPTO_gcm128_aad(), and CRYPTO_gcm128_finish().
GHASH
#define GHASH (ctx, in, len) gcm_ghash_4bit((ctx)->Xi.u,(ctx)->Htable,in,len)
Definition at line 555 of file gcm128.c.
Referenced by CRYPTO_gcm128_aad().
GHASH_CHUNK
#define GHASH_CHUNK (3*1024)
Definition at line 561 of file gcm128.c.
PACK
#define PACK (s) ((size_t)(s)<<(sizeof(size_t)*8-16))
Definition at line 22 of file gcm128.c.
REDUCE1BIT
#define REDUCE1BIT (V)
Value:
do { \
        if (sizeof(size_t)==8) { \
                u64 T = U64(0xe100000000000000) & (0-(V.lo&1)); \
                V.lo  = (V.hi<<63)|(V.lo>>1); \
                V.hi  = (V.hi>>1 )^T; \
        } \
        else { \
                u32 T = 0xe1000000U & (0-(u32)(V.lo&1)); \
                V.lo  = (V.hi<<63)|(V.lo>>1); \
                V.hi  = (V.hi>>1 )^((u64)T<<32); \
        } \
} while(0)
Definition at line 23 of file gcm128.c.
Function Documentation
CRYPTO_gcm128_aad()
int CRYPTO_gcm128_aad (GCM128_CONTEXT * ctx, const unsigned char * aad, size_t len)
Definition at line 910 of file gcm128.c.
References GCM_MUL, GHASH, if(), len, and U64.
CRYPTO_gcm128_decrypt()
int CRYPTO_gcm128_decrypt (GCM128_CONTEXT * ctx, const unsigned char * in, unsigned char * out, size_t len)
Definition at line 1155 of file gcm128.c.
CRYPTO_gcm128_decrypt_ctr32()
int CRYPTO_gcm128_decrypt_ctr32 (GCM128_CONTEXT * ctx, const unsigned char * in, unsigned char * out, size_t len, ctr128_f stream)
Definition at line 1471 of file gcm128.c.
CRYPTO_gcm128_encrypt()
int CRYPTO_gcm128_encrypt (GCM128_CONTEXT * ctx, const unsigned char * in, unsigned char * out, size_t len)
Definition at line 971 of file gcm128.c.
CRYPTO_gcm128_encrypt_ctr32()
int CRYPTO_gcm128_encrypt_ctr32 (GCM128_CONTEXT * ctx, const unsigned char * in, unsigned char * out, size_t len, ctr128_f stream)
Definition at line 1347 of file gcm128.c.
CRYPTO_gcm128_finish()
int CRYPTO_gcm128_finish (GCM128_CONTEXT * ctx, const unsigned char * tag, size_t len)
Definition at line 1602 of file gcm128.c.
References CRYPTO_memcmp(), GCM_MUL, GETU32, and if().
Referenced by CRYPTO_gcm128_tag().
CRYPTO_gcm128_init()
void CRYPTO_gcm128_init (GCM128_CONTEXT * ctx, void * key, block128_f block)
Definition at line 713 of file gcm128.c.
References CTX__GHASH, GETU32, and key.
CRYPTO_gcm128_new()
GCM128_CONTEXT* CRYPTO_gcm128_new (void * key, block128_f block)
Definition at line 1653 of file gcm128.c.
CRYPTO_gcm128_release()
void CRYPTO_gcm128_release (GCM128_CONTEXT * ctx)
Definition at line 1663 of file gcm128.c.
References OPENSSL_clear_free.
CRYPTO_gcm128_setiv()
void CRYPTO_gcm128_setiv (GCM128_CONTEXT * ctx, const unsigned char * iv, size_t len)
Definition at line 828 of file gcm128.c.
CRYPTO_gcm128_tag()
void CRYPTO_gcm128_tag (GCM128_CONTEXT * ctx, unsigned char * tag, size_t len)
Definition at line 1646 of file gcm128.c.
References CRYPTO_gcm128_finish(), and NULL.