crypto/hmac/hmac.c File Reference
hmac.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "internal/cryptlib.h"
#include <openssl/hmac.h>
#include <openssl/opensslconf.h>
#include "hmac_lcl.h"
Functions
int HMAC_Init_ex (HMAC_CTX *ctx, const void *key, int len, const EVP_MD *md, ENGINE *impl)
int HMAC_Init (HMAC_CTX *ctx, const void *key, int len, const EVP_MD *md)
int HMAC_Update (HMAC_CTX *ctx, const unsigned char *data, size_t len)
int HMAC_Final (HMAC_CTX *ctx, unsigned char *md, unsigned int *len)
size_t HMAC_size (const HMAC_CTX *ctx)
HMAC_CTX * HMAC_CTX_new (void)
void HMAC_CTX_free (HMAC_CTX *ctx)
int HMAC_CTX_reset (HMAC_CTX *ctx)
int HMAC_CTX_copy (HMAC_CTX *dctx, HMAC_CTX *sctx)
unsigned char * HMAC (const EVP_MD *evp_md, const void *key, int key_len, const unsigned char *d, size_t n, unsigned char *md, unsigned int *md_len)
void HMAC_CTX_set_flags (HMAC_CTX *ctx, unsigned long flags)
const EVP_MD * HMAC_CTX_get_md (const HMAC_CTX *ctx)
Function Documentation
HMAC()
unsigned char* HMAC (const EVP_MD * evp_md, const void * key, int key_len, const unsigned char * d, size_t n, unsigned char * md, unsigned int * md_len)
Definition at line 201 of file hmac.c.
HMAC_CTX_copy()
int HMAC_CTX_copy (HMAC_CTX * dctx, HMAC_CTX * sctx)
Definition at line 182 of file hmac.c.
References EVP_MD_CTX_copy_ex(), HMAC_CTX_reset(), and HMAC_MAX_MD_CBLOCK.
HMAC_CTX_free()
void HMAC_CTX_free (HMAC_CTX * ctx)
Definition at line 149 of file hmac.c.
References NULL.
Referenced by HMAC_CTX_new().
HMAC_CTX_get_md()
const EVP_MD* HMAC_CTX_get_md (const HMAC_CTX * ctx)
Definition at line 239 of file hmac.c.
HMAC_CTX_new()
HMAC_CTX* HMAC_CTX_new (void)
Definition at line 126 of file hmac.c.
References ctx, HMAC_CTX_free(), HMAC_CTX_reset(), NULL, and OPENSSL_zalloc.
HMAC_CTX_reset()
int HMAC_CTX_reset (HMAC_CTX * ctx)
Definition at line 160 of file hmac.c.
Referenced by HMAC_CTX_copy(), and HMAC_CTX_new().
HMAC_CTX_set_flags()
void HMAC_CTX_set_flags (HMAC_CTX * ctx, unsigned long flags)
Definition at line 232 of file hmac.c.
References EVP_MD_CTX_set_flags().
HMAC_Final()
int HMAC_Final (HMAC_CTX * ctx, unsigned char * md, unsigned int * len)
Definition at line 98 of file hmac.c.
HMAC_Init()
int HMAC_Init (HMAC_CTX * ctx, const void * key, int len, const EVP_MD * md)
Definition at line 83 of file hmac.c.
HMAC_Init_ex()
int HMAC_Init_ex (HMAC_CTX * ctx, const void * key, int len, const EVP_MD * md, ENGINE * impl)
Definition at line 18 of file hmac.c.
HMAC_size()
size_t HMAC_size (const HMAC_CTX * ctx)
Definition at line 119 of file hmac.c.
References EVP_MD_size().
HMAC_Update()
int HMAC_Update (HMAC_CTX * ctx, const unsigned char * data, size_t len)
Definition at line 91 of file hmac.c.
References EVP_DigestUpdate().