include/openssl/hmac.h File Reference
hmac.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/evp.h>
Macros
#define HMAC_MAX_MD_CBLOCK 128/* largest known is SHA512 */
Functions
size_t HMAC_size (const HMAC_CTX *e)
HMAC_CTX * HMAC_CTX_new (void)
int HMAC_CTX_reset (HMAC_CTX *ctx)
void HMAC_CTX_free (HMAC_CTX *ctx)
DEPRECATEDIN_1_1_0 (__owur int HMAC_Init(HMAC_CTX *ctx, const void *key, int len, const EVP_MD *md)) int HMAC_Init_ex(HMAC_CTX *ctx
int HMAC_Update (HMAC_CTX *ctx, const unsigned char *data, size_t len)
int HMAC_Final (HMAC_CTX *ctx, unsigned char *md, unsigned int *len)
unsigned char * HMAC (const EVP_MD *evp_md, const void *key, int key_len, const unsigned char *d, size_t n, unsigned char *md, unsigned int *md_len)
__owur int HMAC_CTX_copy (HMAC_CTX *dctx, HMAC_CTX *sctx)
void HMAC_CTX_set_flags (HMAC_CTX *ctx, unsigned long flags)
const EVP_MD * HMAC_CTX_get_md (const HMAC_CTX *ctx)
Variables
const void * key
const void int len
const void int const EVP_MD * md
const void int const EVP_MD ENGINE * impl
Macro Definition Documentation
HMAC_MAX_MD_CBLOCK
#define HMAC_MAX_MD_CBLOCK 128/* largest known is SHA512 */
Definition at line 17 of file hmac.h.
Referenced by HMAC_CTX_copy().
Function Documentation
DEPRECATEDIN_1_1_0()
DEPRECATEDIN_1_1_0 (__owur int HMAC_InitHMAC_CTX *ctx, const void *key, int len, const EVP_MD *md)
HMAC()
unsigned char* HMAC (const EVP_MD * evp_md, const void * key, int key_len, const unsigned char * d, size_t n, unsigned char * md, unsigned int * md_len)
Definition at line 201 of file hmac.c.
HMAC_CTX_copy()
__owur int HMAC_CTX_copy (HMAC_CTX * dctx, HMAC_CTX * sctx)
Definition at line 182 of file hmac.c.
References EVP_MD_CTX_copy_ex(), HMAC_CTX_reset(), and HMAC_MAX_MD_CBLOCK.
HMAC_CTX_free()
void HMAC_CTX_free (HMAC_CTX * ctx)
Definition at line 149 of file hmac.c.
References NULL.
Referenced by HMAC_CTX_new().
HMAC_CTX_get_md()
const EVP_MD* HMAC_CTX_get_md (const HMAC_CTX * ctx)
Definition at line 239 of file hmac.c.
HMAC_CTX_new()
HMAC_CTX* HMAC_CTX_new (void)
Definition at line 126 of file hmac.c.
References ctx, HMAC_CTX_free(), HMAC_CTX_reset(), NULL, and OPENSSL_zalloc.
HMAC_CTX_reset()
int HMAC_CTX_reset (HMAC_CTX * ctx)
Definition at line 160 of file hmac.c.
Referenced by HMAC_CTX_copy(), and HMAC_CTX_new().
HMAC_CTX_set_flags()
void HMAC_CTX_set_flags (HMAC_CTX * ctx, unsigned long flags)
Definition at line 232 of file hmac.c.
References EVP_MD_CTX_set_flags().
HMAC_Final()
int HMAC_Final (HMAC_CTX * ctx, unsigned char * md, unsigned int * len)
Definition at line 98 of file hmac.c.
HMAC_size()
size_t HMAC_size (const HMAC_CTX * e)
Definition at line 119 of file hmac.c.
References EVP_MD_size().
HMAC_Update()
int HMAC_Update (HMAC_CTX * ctx, const unsigned char * data, size_t len)
Definition at line 91 of file hmac.c.
References EVP_DigestUpdate().
Variable Documentation
impl
const void int const EVP_MD ENGINE* impl
Definition at line 31 of file hmac.h.
Referenced by EVP_DigestInit_ex().
key
const void* key
Definition at line 31 of file hmac.h.
Referenced by CMS_add_simple_smimecap(), cms_RecipientInfo_pwri_crypt(), CMS_RecipientInfo_set0_key(), CRYPTO_ccm128_init(), CRYPTO_gcm128_init(), CRYPTO_THREAD_get_local(), CRYPTO_THREAD_set_local(), EC_KEY_set_method(), EVP_PKEY_assign(), load_key(), load_pubkey(), main(), ssl3_change_cipher_state(), ssl_print_tmp_key(), tls1_change_cipher_state(), TS_CONF_load_key(), and TS_RESP_CTX_set_signer_key().
len
const void int len
Definition at line 31 of file hmac.h.
md
const void int const EVP_MD* md
Definition at line 31 of file hmac.h.