crypto/asn1/i2d_pr.c File Reference
i2d_pr.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/evp.h>
#include <openssl/x509.h>
#include "internal/asn1_int.h"
#include "internal/evp_int.h"
Functions
int i2d_PrivateKey (EVP_PKEY *a, unsigned char **pp)
Function Documentation
i2d_PrivateKey()
int i2d_PrivateKey (EVP_PKEY * a, unsigned char ** pp)
Definition at line 17 of file i2d_pr.c.
References EVP_PKEY2PKCS8().
Referenced by i2d_PrivateKey_bio(), i2d_PrivateKey_fp(), and PEM_write_bio_PrivateKey_traditional().