include/openssl/async.h File Reference
async.h File Reference
#include <stdlib.h>
Macros
#define OSSL_ASYNC_FD int
#define OSSL_BAD_ASYNC_FD -1
#define ASYNC_ERR 0
#define ASYNC_NO_JOBS 1
#define ASYNC_PAUSE 2
#define ASYNC_FINISH 3
#define ASYNC_F_ASYNC_CTX_NEW 100
#define ASYNC_F_ASYNC_INIT_THREAD 101
#define ASYNC_F_ASYNC_JOB_NEW 102
#define ASYNC_F_ASYNC_PAUSE_JOB 103
#define ASYNC_F_ASYNC_START_FUNC 104
#define ASYNC_F_ASYNC_START_JOB 105
#define ASYNC_R_FAILED_TO_SET_POOL 101
#define ASYNC_R_FAILED_TO_SWAP_CONTEXT 102
#define ASYNC_R_INIT_FAILED 105
#define ASYNC_R_INVALID_POOL_SIZE 103
Functions
int ASYNC_init_thread (size_t max_size, size_t init_size)
void ASYNC_cleanup_thread (void)
ASYNC_WAIT_CTX * ASYNC_WAIT_CTX_new (void)
void ASYNC_WAIT_CTX_free (ASYNC_WAIT_CTX *ctx)
int ASYNC_WAIT_CTX_set_wait_fd (ASYNC_WAIT_CTX *ctx, const void *key, OSSL_ASYNC_FD fd, void *custom_data, void(*cleanup)(ASYNC_WAIT_CTX *, const void *, OSSL_ASYNC_FD, void *))
int ASYNC_WAIT_CTX_get_fd (ASYNC_WAIT_CTX *ctx, const void *key, OSSL_ASYNC_FD *fd, void **custom_data)
int ASYNC_WAIT_CTX_get_all_fds (ASYNC_WAIT_CTX *ctx, OSSL_ASYNC_FD *fd, size_t *numfds)
int ASYNC_WAIT_CTX_get_changed_fds (ASYNC_WAIT_CTX *ctx, OSSL_ASYNC_FD *addfd, size_t *numaddfds, OSSL_ASYNC_FD *delfd, size_t *numdelfds)
int ASYNC_WAIT_CTX_clear_fd (ASYNC_WAIT_CTX *ctx, const void *key)
int ASYNC_is_capable (void)
int ASYNC_start_job (ASYNC_JOB **job, ASYNC_WAIT_CTX *ctx, int *ret, int(*func)(void *), void *args, size_t size)
int ASYNC_pause_job (void)
ASYNC_JOB * ASYNC_get_current_job (void)
ASYNC_WAIT_CTX * ASYNC_get_wait_ctx (ASYNC_JOB *job)
void ASYNC_block_pause (void)
void ASYNC_unblock_pause (void)
int ERR_load_ASYNC_strings (void)
Macro Definition Documentation
ASYNC_ERR
#define ASYNC_ERR 0
Definition at line 34 of file async.h.
ASYNC_F_ASYNC_CTX_NEW
#define ASYNC_F_ASYNC_CTX_NEW 100
Definition at line 82 of file async.h.
ASYNC_F_ASYNC_INIT_THREAD
#define ASYNC_F_ASYNC_INIT_THREAD 101
Definition at line 83 of file async.h.
Referenced by ASYNC_init_thread().
ASYNC_F_ASYNC_JOB_NEW
#define ASYNC_F_ASYNC_JOB_NEW 102
Definition at line 84 of file async.h.
ASYNC_F_ASYNC_PAUSE_JOB
#define ASYNC_F_ASYNC_PAUSE_JOB 103
Definition at line 85 of file async.h.
Referenced by ASYNC_pause_job().
ASYNC_F_ASYNC_START_FUNC
#define ASYNC_F_ASYNC_START_FUNC 104
Definition at line 86 of file async.h.
Referenced by async_start_func().
ASYNC_F_ASYNC_START_JOB
#define ASYNC_F_ASYNC_START_JOB 105
Definition at line 87 of file async.h.
ASYNC_FINISH
#define ASYNC_FINISH 3
Definition at line 37 of file async.h.
ASYNC_NO_JOBS
#define ASYNC_NO_JOBS 1
Definition at line 35 of file async.h.
ASYNC_PAUSE
#define ASYNC_PAUSE 2
Definition at line 36 of file async.h.
ASYNC_R_FAILED_TO_SET_POOL
#define ASYNC_R_FAILED_TO_SET_POOL 101
Definition at line 90 of file async.h.
ASYNC_R_FAILED_TO_SWAP_CONTEXT
#define ASYNC_R_FAILED_TO_SWAP_CONTEXT 102
Definition at line 91 of file async.h.
Referenced by ASYNC_pause_job(), and async_start_func().
ASYNC_R_INIT_FAILED
#define ASYNC_R_INIT_FAILED 105
Definition at line 92 of file async.h.
ASYNC_R_INVALID_POOL_SIZE
#define ASYNC_R_INVALID_POOL_SIZE 103
Definition at line 93 of file async.h.
Referenced by ASYNC_init_thread().
OSSL_ASYNC_FD
#define OSSL_ASYNC_FD int
Definition at line 22 of file async.h.
Referenced by wait_for_async().
OSSL_BAD_ASYNC_FD
#define OSSL_BAD_ASYNC_FD -1
Definition at line 23 of file async.h.
Function Documentation
ASYNC_block_pause()
void ASYNC_block_pause (void)
Definition at line 410 of file async.c.
References async_get_ctx(), ctx, and NULL.
ASYNC_cleanup_thread()
void ASYNC_cleanup_thread (void)
Definition at line 389 of file async.c.
ASYNC_get_current_job()
ASYNC_JOB* ASYNC_get_current_job (void)
Definition at line 394 of file async.c.
References async_get_ctx(), ctx, and NULL.
Referenced by SSL_peek_ex(), SSL_read_ex(), SSL_shutdown(), and SSL_write_ex().
ASYNC_get_wait_ctx()
ASYNC_WAIT_CTX* ASYNC_get_wait_ctx (ASYNC_JOB * job)
Definition at line 405 of file async.c.
ASYNC_init_thread()
int ASYNC_init_thread (size_t max_size, size_t init_size)
Definition at line 316 of file async.c.
References ASYNC_F_ASYNC_INIT_THREAD, ASYNC_R_INVALID_POOL_SIZE, ASYNCerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_INIT_ASYNC, OPENSSL_init_crypto(), OPENSSL_INIT_THREAD_ASYNC, OPENSSL_zalloc, and ossl_init_thread_start().
ASYNC_is_capable()
int ASYNC_is_capable (void)
Definition at line 14 of file async_null.c.
ASYNC_pause_job()
int ASYNC_pause_job (void)
Definition at line 255 of file async.c.
References ASYNC_F_ASYNC_PAUSE_JOB, async_fibre_swapcontext, async_get_ctx(), ASYNC_JOB_PAUSING, ASYNC_R_FAILED_TO_SWAP_CONTEXT, async_wait_ctx_reset_counts(), ASYNCerr, ctx, and NULL.
ASYNC_start_job()
int ASYNC_start_job (ASYNC_JOB ** job, ASYNC_WAIT_CTX * ctx, int * ret, int(*)(void *) func, void * args, size_t size)
Definition at line 169 of file async.c.
ASYNC_unblock_pause()
void ASYNC_unblock_pause (void)
Definition at line 422 of file async.c.
References async_get_ctx(), ctx, and NULL.
ASYNC_WAIT_CTX_clear_fd()
int ASYNC_WAIT_CTX_clear_fd (ASYNC_WAIT_CTX * ctx, const void * key)
Definition at line 139 of file async_wait.c.
References fd_lookup_st::add, fd_lookup_st::del, fd_lookup_st::key, fd_lookup_st::next, NULL, and OPENSSL_free.
ASYNC_WAIT_CTX_free()
void ASYNC_WAIT_CTX_free (ASYNC_WAIT_CTX * ctx)
Definition at line 20 of file async_wait.c.
References fd_lookup_st::cleanup, fd_lookup_st::custom_data, fd_lookup_st::del, fd_lookup_st::fd, fd_lookup_st::key, fd_lookup_st::next, NULL, and OPENSSL_free.
ASYNC_WAIT_CTX_get_all_fds()
int ASYNC_WAIT_CTX_get_all_fds (ASYNC_WAIT_CTX * ctx, OSSL_ASYNC_FD * fd, size_t * numfds)
Definition at line 87 of file async_wait.c.
References fd_lookup_st::del, fd_lookup_st::fd, fd_lookup_st::next, and NULL.
Referenced by SSL_get_all_async_fds().
ASYNC_WAIT_CTX_get_changed_fds()
int ASYNC_WAIT_CTX_get_changed_fds (ASYNC_WAIT_CTX * ctx, OSSL_ASYNC_FD * addfd, size_t * numaddfds, OSSL_ASYNC_FD * delfd, size_t * numdelfds)
Definition at line 110 of file async_wait.c.
References fd_lookup_st::add, fd_lookup_st::del, fd_lookup_st::fd, fd_lookup_st::next, and NULL.
Referenced by SSL_get_changed_async_fds().
ASYNC_WAIT_CTX_get_fd()
int ASYNC_WAIT_CTX_get_fd (ASYNC_WAIT_CTX * ctx, const void * key, OSSL_ASYNC_FD * fd, void ** custom_data)
Definition at line 65 of file async_wait.c.
References fd_lookup_st::custom_data, fd_lookup_st::del, fd_lookup_st::fd, fd_lookup_st::key, fd_lookup_st::next, and NULL.
ASYNC_WAIT_CTX_new()
ASYNC_WAIT_CTX* ASYNC_WAIT_CTX_new (void)
Definition at line 15 of file async_wait.c.
References OPENSSL_zalloc.
ASYNC_WAIT_CTX_set_wait_fd()
int ASYNC_WAIT_CTX_set_wait_fd (ASYNC_WAIT_CTX * ctx, const void * key, OSSL_ASYNC_FD fd, void * custom_data, void(*)(ASYNC_WAIT_CTX *, const void *, OSSL_ASYNC_FD, void *) cleanup)
Definition at line 43 of file async_wait.c.
ERR_load_ASYNC_strings()
int ERR_load_ASYNC_strings (void)
Definition at line 41 of file async_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().