include/openssl/objects.h File Reference
objects.h File Reference
#include <openssl/obj_mac.h>
#include <openssl/bio.h>
#include <openssl/asn1.h>
Data Structures
struct OBJ_NAME
Macros
#define USE_OBJ_MAC
#define OBJ_NAME_TYPE_UNDEF 0x00
#define OBJ_NAME_TYPE_MD_METH 0x01
#define OBJ_NAME_TYPE_CIPHER_METH 0x02
#define OBJ_NAME_TYPE_PKEY_METH 0x03
#define OBJ_NAME_TYPE_COMP_METH 0x04
#define OBJ_NAME_TYPE_NUM 0x05
#define OBJ_NAME_ALIAS 0x8000
#define OBJ_BSEARCH_VALUE_ON_NOMATCH 0x01
#define OBJ_BSEARCH_FIRST_VALUE_ON_MATCH 0x02
#define OBJ_create_and_add_object(a, b, c) OBJ_create(a,b,c)
#define _DECLARE_OBJ_BSEARCH_CMP_FN(scope, type1, type2, nm)
#define DECLARE_OBJ_BSEARCH_CMP_FN(type1, type2, cmp) _DECLARE_OBJ_BSEARCH_CMP_FN(static, type1, type2, cmp)
#define DECLARE_OBJ_BSEARCH_GLOBAL_CMP_FN(type1, type2, nm) type2 * OBJ_bsearch_##nm(type1 *key, type2 const *base, int num)
#define IMPLEMENT_OBJ_BSEARCH_CMP_FN(type1, type2, nm)
#define IMPLEMENT_OBJ_BSEARCH_GLOBAL_CMP_FN(type1, type2, nm)
#define OBJ_bsearch(type1, key, type2, base, num, cmp)
#define OBJ_bsearch_ex(type1, key, type2, base, num, cmp, flags)
#define OBJ_cleanup() while(0) continue
#define OBJ_F_OBJ_ADD_OBJECT 105
#define OBJ_F_OBJ_CREATE 100
#define OBJ_F_OBJ_DUP 101
#define OBJ_F_OBJ_NAME_NEW_INDEX 106
#define OBJ_F_OBJ_NID2LN 102
#define OBJ_F_OBJ_NID2OBJ 103
#define OBJ_F_OBJ_NID2SN 104
#define OBJ_R_OID_EXISTS 102
#define OBJ_R_UNKNOWN_NID 101
Functions
int OBJ_NAME_init (void)
int OBJ_NAME_new_index (unsigned long(*hash_func)(const char *), int(*cmp_func)(const char *, const char *), void(*free_func)(const char *, int, const char *))
const char * OBJ_NAME_get (const char *name, int type)
int OBJ_NAME_add (const char *name, int type, const char *data)
int OBJ_NAME_remove (const char *name, int type)
void OBJ_NAME_cleanup (int type)
void OBJ_NAME_do_all (int type, void(*fn)(const OBJ_NAME *, void *arg), void *arg)
void OBJ_NAME_do_all_sorted (int type, void(*fn)(const OBJ_NAME *, void *arg), void *arg)
ASN1_OBJECT * OBJ_dup (const ASN1_OBJECT *o)
ASN1_OBJECT * OBJ_nid2obj (int n)
const char * OBJ_nid2ln (int n)
const char * OBJ_nid2sn (int n)
int OBJ_obj2nid (const ASN1_OBJECT *o)
ASN1_OBJECT * OBJ_txt2obj (const char *s, int no_name)
int OBJ_obj2txt (char *buf, int buf_len, const ASN1_OBJECT *a, int no_name)
int OBJ_txt2nid (const char *s)
int OBJ_ln2nid (const char *s)
int OBJ_sn2nid (const char *s)
int OBJ_cmp (const ASN1_OBJECT *a, const ASN1_OBJECT *b)
const void * OBJ_bsearch_ (const void *key, const void *base, int num, int size, int(*cmp)(const void *, const void *))
const void * OBJ_bsearch_ex_ (const void *key, const void *base, int num, int size, int(*cmp)(const void *, const void *), int flags)
int OBJ_new_nid (int num)
int OBJ_add_object (const ASN1_OBJECT *obj)
int OBJ_create (const char *oid, const char *sn, const char *ln)
int OBJ_create_objects (BIO *in)
size_t OBJ_length (const ASN1_OBJECT *obj)
const unsigned char * OBJ_get0_data (const ASN1_OBJECT *obj)
int OBJ_find_sigid_algs (int signid, int *pdig_nid, int *ppkey_nid)
int OBJ_find_sigid_by_algs (int *psignid, int dig_nid, int pkey_nid)
int OBJ_add_sigid (int signid, int dig_id, int pkey_id)
void OBJ_sigid_free (void)
int ERR_load_OBJ_strings (void)
Macro Definition Documentation
_DECLARE_OBJ_BSEARCH_CMP_FN
#define _DECLARE_OBJ_BSEARCH_CMP_FN (scope, type1, type2, nm)
Value:
static int nm##_cmp_BSEARCH_CMP_FN(const void *, const void *); \
  static int nm##_cmp(type1 const *, type2 const *); \
  scope type2 * OBJ_bsearch_##nm(type1 *key, type2 const *base, int num)
Definition at line 976 of file objects.h.
DECLARE_OBJ_BSEARCH_CMP_FN
#define DECLARE_OBJ_BSEARCH_CMP_FN (type1, type2, cmp) _DECLARE_OBJ_BSEARCH_CMP_FN(static, type1, type2, cmp)
Definition at line 981 of file objects.h.
DECLARE_OBJ_BSEARCH_GLOBAL_CMP_FN
#define DECLARE_OBJ_BSEARCH_GLOBAL_CMP_FN (type1, type2, nm) type2 * OBJ_bsearch_##nm(type1 *key, type2 const *base, int num)
Definition at line 983 of file objects.h.
IMPLEMENT_OBJ_BSEARCH_CMP_FN
#define IMPLEMENT_OBJ_BSEARCH_CMP_FN (type1, type2, nm)
Value:
static int nm##_cmp_BSEARCH_CMP_FN(const void *a_, const void *b_)    \
      { \
      type1 const *a = a_; \
      type2 const *b = b_; \
      return nm##_cmp(a,b); \
      } \
  static type2 *OBJ_bsearch_##nm(type1 *key, type2 const *base, int num) \
      { \
      return (type2 *)OBJ_bsearch_(key, base, num, sizeof(type2), \
                                        nm##_cmp_BSEARCH_CMP_FN); \
      } \
      extern void dummy_prototype(void)
Definition at line 1013 of file objects.h.
IMPLEMENT_OBJ_BSEARCH_GLOBAL_CMP_FN
#define IMPLEMENT_OBJ_BSEARCH_GLOBAL_CMP_FN (type1, type2, nm)
Value:
static int nm##_cmp_BSEARCH_CMP_FN(const void *a_, const void *b_)    \
      { \
      type1 const *a = a_; \
      type2 const *b = b_; \
      return nm##_cmp(a,b); \
      } \
  type2 *OBJ_bsearch_##nm(type1 *key, type2 const *base, int num) \
      { \
      return (type2 *)OBJ_bsearch_(key, base, num, sizeof(type2), \
                                        nm##_cmp_BSEARCH_CMP_FN); \
      } \
      extern void dummy_prototype(void)
Definition at line 1027 of file objects.h.
OBJ_bsearch
#define OBJ_bsearch (type1, key, type2, base, num, cmp)
Value:
((type2 *)OBJ_bsearch_(CHECKED_PTR_OF(type1,key),CHECKED_PTR_OF(type2,base), \
                         num,sizeof(type2),                             \
                         ((void)CHECKED_PTR_OF(type1,cmp##_type_1),     \
                          (void)CHECKED_PTR_OF(type2,cmp##_type_2),     \
                          cmp##_BSEARCH_CMP_FN)))
Definition at line 1041 of file objects.h.
OBJ_bsearch_ex
#define OBJ_bsearch_ex (type1, key, type2, base, num, cmp, flags)
Value:
((type2 *)OBJ_bsearch_ex_(CHECKED_PTR_OF(type1,key),CHECKED_PTR_OF(type2,base), \
                         num,sizeof(type2),                             \
                         ((void)CHECKED_PTR_OF(type1,cmp##_type_1),     \
                          (void)type_2=CHECKED_PTR_OF(type2,cmp##_type_2), \
                          cmp##_BSEARCH_CMP_FN)),flags)
Definition at line 1048 of file objects.h.
OBJ_BSEARCH_FIRST_VALUE_ON_MATCH
#define OBJ_BSEARCH_FIRST_VALUE_ON_MATCH 0x02
Definition at line 928 of file objects.h.
OBJ_BSEARCH_VALUE_ON_NOMATCH
#define OBJ_BSEARCH_VALUE_ON_NOMATCH 0x01
Definition at line 927 of file objects.h.
OBJ_cleanup
#define OBJ_cleanup () while(0) continue
Definition at line 1059 of file objects.h.
OBJ_create_and_add_object
#define OBJ_create_and_add_object (a, b, c) OBJ_create(a,b,c)
Definition at line 942 of file objects.h.
OBJ_F_OBJ_ADD_OBJECT
#define OBJ_F_OBJ_ADD_OBJECT 105
Definition at line 1082 of file objects.h.
OBJ_F_OBJ_CREATE
#define OBJ_F_OBJ_CREATE 100
Definition at line 1083 of file objects.h.
Referenced by OBJ_create().
OBJ_F_OBJ_DUP
#define OBJ_F_OBJ_DUP 101
Definition at line 1084 of file objects.h.
Referenced by OBJ_dup().
OBJ_F_OBJ_NAME_NEW_INDEX
#define OBJ_F_OBJ_NAME_NEW_INDEX 106
Definition at line 1085 of file objects.h.
OBJ_F_OBJ_NID2LN
#define OBJ_F_OBJ_NID2LN 102
Definition at line 1086 of file objects.h.
OBJ_F_OBJ_NID2OBJ
#define OBJ_F_OBJ_NID2OBJ 103
Definition at line 1087 of file objects.h.
OBJ_F_OBJ_NID2SN
#define OBJ_F_OBJ_NID2SN 104
Definition at line 1088 of file objects.h.
OBJ_NAME_ALIAS
#define OBJ_NAME_ALIAS 0x8000
Definition at line 925 of file objects.h.
OBJ_NAME_TYPE_CIPHER_METH
#define OBJ_NAME_TYPE_CIPHER_METH 0x02
Definition at line 920 of file objects.h.
Referenced by EVP_CIPHER_do_all(), EVP_CIPHER_do_all_sorted(), evp_cleanup_int(), and EVP_get_cipherbyname().
OBJ_NAME_TYPE_COMP_METH
#define OBJ_NAME_TYPE_COMP_METH 0x04
Definition at line 922 of file objects.h.
OBJ_NAME_TYPE_MD_METH
#define OBJ_NAME_TYPE_MD_METH 0x01
Definition at line 919 of file objects.h.
Referenced by evp_cleanup_int(), and EVP_get_digestbyname().
OBJ_NAME_TYPE_NUM
#define OBJ_NAME_TYPE_NUM 0x05
Definition at line 923 of file objects.h.
OBJ_NAME_TYPE_PKEY_METH
#define OBJ_NAME_TYPE_PKEY_METH 0x03
Definition at line 921 of file objects.h.
OBJ_NAME_TYPE_UNDEF
#define OBJ_NAME_TYPE_UNDEF 0x00
Definition at line 918 of file objects.h.
OBJ_R_OID_EXISTS
#define OBJ_R_OID_EXISTS 102
Definition at line 1091 of file objects.h.
Referenced by OBJ_create().
OBJ_R_UNKNOWN_NID
#define OBJ_R_UNKNOWN_NID 101
Definition at line 1092 of file objects.h.
USE_OBJ_MAC
#define USE_OBJ_MAC
Definition at line 13 of file objects.h.
Function Documentation
ERR_load_OBJ_strings()
int ERR_load_OBJ_strings (void)
Definition at line 40 of file obj_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
OBJ_add_object()
int OBJ_add_object (const ASN1_OBJECT * obj)
Definition at line 174 of file obj_dat.c.
References NULL.
Referenced by OBJ_create().
OBJ_add_sigid()
int OBJ_add_sigid (int signid, int dig_id, int pkey_id)
Definition at line 95 of file obj_xref.c.
References NULL.
OBJ_bsearch_()
const void* OBJ_bsearch_ (const void * key, const void * base, int num, int size, int(*)(const void *, const void *) cmp)
Definition at line 580 of file obj_dat.c.
OBJ_bsearch_ex_()
const void* OBJ_bsearch_ex_ (const void * key, const void * base, int num, int size, int(*)(const void *, const void *) cmp, int flags)
Definition at line 586 of file obj_dat.c.
References h.
OBJ_cmp()
int OBJ_cmp (const ASN1_OBJECT * a, const ASN1_OBJECT * b)
Definition at line 58 of file obj_lib.c.
Referenced by ASN1_TYPE_cmp(), level_find_node(), policy_node_match(), X509_NAME_get_index_by_OBJ(), X509at_get_attr_by_OBJ(), and X509v3_get_ext_by_OBJ().
OBJ_create()
int OBJ_create (const char * oid, const char * sn, const char * ln)
Definition at line 682 of file obj_dat.c.
References ASN1_OBJECT_free(), NID_undef, NULL, OBJ_add_object(), OBJ_F_OBJ_CREATE, OBJ_ln2nid(), OBJ_new_nid(), OBJ_obj2nid(), OBJ_R_OID_EXISTS, OBJ_sn2nid(), OBJ_txt2obj(), and OBJerr.
OBJ_create_objects()
int OBJ_create_objects (BIO * in)
Definition at line 635 of file obj_dat.c.
OBJ_dup()
ASN1_OBJECT* OBJ_dup (const ASN1_OBJECT * o)
Definition at line 17 of file obj_lib.c.
References ASN1_OBJECT_FLAG_DYNAMIC, ASN1_OBJECT_FLAG_DYNAMIC_DATA, ASN1_OBJECT_FLAG_DYNAMIC_STRINGS, ASN1_OBJECT_free(), ASN1_OBJECT_new(), ERR_R_ASN1_LIB, ERR_R_MALLOC_FAILURE, NULL, OBJ_F_OBJ_DUP, OBJerr, OPENSSL_memdup, and OPENSSL_strdup.
Referenced by ASN1_OBJECT_create(), ASN1_TYPE_set1(), TS_REQ_set_policy_id(), TS_RESP_CTX_add_policy(), TS_RESP_CTX_set_def_policy(), TS_TST_INFO_set_policy_id(), X509_ATTRIBUTE_set1_object(), X509_EXTENSION_set_object(), and X509_NAME_ENTRY_set_object().
OBJ_find_sigid_algs()
int OBJ_find_sigid_algs (int signid, int * pdig_nid, int * ppkey_nid)
Definition at line 42 of file obj_xref.c.
References NULL, and nid_triple::sign_id.
Referenced by X509_signature_print().
OBJ_find_sigid_by_algs()
int OBJ_find_sigid_by_algs (int * psignid, int dig_nid, int pkey_nid)
Definition at line 67 of file obj_xref.c.
References nid_triple::hash_id, NULL, nid_triple::pkey_id, and t.
Referenced by ASN1_item_sign_ctx().
OBJ_get0_data()
const unsigned char* OBJ_get0_data (const ASN1_OBJECT * obj)
Definition at line 723 of file obj_dat.c.
References NULL.
Referenced by EVP_CIPHER_type().
OBJ_length()
size_t OBJ_length (const ASN1_OBJECT * obj)
Definition at line 716 of file obj_dat.c.
References NULL.
OBJ_ln2nid()
int OBJ_ln2nid (const char * s)
Definition at line 538 of file obj_dat.c.
References ADDED_LNAME, and NULL.
Referenced by OBJ_create().
OBJ_NAME_add()
int OBJ_NAME_add (const char * name, int type, const char * data)
Definition at line 186 of file o_names.c.
OBJ_NAME_cleanup()
void OBJ_NAME_cleanup (int type)
Definition at line 351 of file o_names.c.
References NULL, and type.
Referenced by evp_cleanup_int().
OBJ_NAME_do_all()
void OBJ_NAME_do_all (int type, void(*)(const OBJ_NAME *, void *arg) fn, void * arg)
Definition at line 275 of file o_names.c.
Referenced by EVP_CIPHER_do_all().
OBJ_NAME_do_all_sorted()
void OBJ_NAME_do_all_sorted (int type, void(*)(const OBJ_NAME *, void *arg) fn, void * arg)
Definition at line 311 of file o_names.c.
Referenced by EVP_CIPHER_do_all_sorted().
OBJ_NAME_get()
const char* OBJ_NAME_get (const char * name, int type)
Definition at line 156 of file o_names.c.
Referenced by EVP_get_cipherbyname(), and EVP_get_digestbyname().
OBJ_NAME_init()
int OBJ_NAME_init (void)
OBJ_NAME_new_index()
int OBJ_NAME_new_index (unsigned long(*)(const char *) hash_func, int(*)(const char *, const char *) cmp_func, void(*)(const char *, int, const char *) free_func)
Definition at line 75 of file o_names.c.
OBJ_NAME_remove()
int OBJ_NAME_remove (const char * name, int type)
Definition at line 232 of file o_names.c.
OBJ_new_nid()
int OBJ_new_nid (int num)
Definition at line 165 of file obj_dat.c.
Referenced by OBJ_create().
OBJ_nid2ln()
const char* OBJ_nid2ln (int n)
Definition at line 274 of file obj_dat.c.
References NID_undef, and NUM_NID.
Referenced by print_attribs(), and TS_X509_ALGOR_print_bio().
OBJ_nid2obj()
ASN1_OBJECT* OBJ_nid2obj (int n)
Definition at line 220 of file obj_dat.c.
References NID_undef, and NUM_NID.
Referenced by ASN1_item_sign_ctx(), ASN1_sign(), CMS_add_simple_smimecap(), cms_Data_create(), cms_encode_Receipt(), CMS_EncryptedData_set1_key(), CMS_get1_ReceiptRequest(), cms_Receipt_verify(), CMS_sign(), CMS_sign_receipt(), CMS_SignerInfo_verify_content(), EVP_CIPHER_type(), OCSP_accept_responses_new(), OCSP_response_create(), OCSP_url_svcloc_new(), PKCS12_init(), PKCS12_item_pack_safebag(), PKCS12_pack_p7data(), PKCS12_SAFEBAG_create0_p8inf(), PKCS12_SAFEBAG_create0_pkcs8(), PKCS12_setup_mac(), PKCS7_add_attrib_content_type(), PKCS7_add_signer(), PKCS7_set0_type_other(), PKCS7_set_type(), X509_NAME_ENTRY_create_by_NID(), X509_NAME_get_index_by_NID(), X509at_get_attr_by_NID(), and X509v3_get_ext_by_NID().
OBJ_nid2sn()
const char* OBJ_nid2sn (int n)
Definition at line 247 of file obj_dat.c.
References NID_undef, and NUM_NID.
Referenced by ssl_print_groups(), and ssl_print_tmp_key().
OBJ_obj2nid()
int OBJ_obj2nid (const ASN1_OBJECT * o)
Definition at line 317 of file obj_dat.c.
References ADDED_DATA, NID_undef, and NULL.
Referenced by asn1_do_adb(), CMS_data(), CMS_dataFinal(), CMS_dataInit(), CMS_decrypt(), CMS_digest_verify(), cms_DigestAlgorithm_find_ctx(), CMS_EncryptedData_decrypt(), CMS_EncryptedData_set1_key(), CMS_get0_content(), cms_get0_enveloped(), cms_Receipt_verify(), cms_RecipientInfo_pwri_crypt(), EVP_PKCS82PKEY(), level_add_node(), OBJ_create(), OBJ_txt2nid(), OCSP_response_get1_basic(), PKCS12_SAFEBAG_get0_pkcs8(), PKCS12_SAFEBAG_get1_cert(), PKCS12_SAFEBAG_get1_crl(), PKCS12_SAFEBAG_get_bag_nid(), PKCS12_SAFEBAG_get_nid(), PKCS7_add_certificate(), PKCS7_add_crl(), PKCS7_add_recipient_info(), PKCS7_add_signer(), PKCS7_dataFinal(), PKCS7_set_content(), PKCS7_signatureVerify(), PKCS7_stream(), print_attribs(), SMIME_write_CMS(), SMIME_write_PKCS7(), STACK_OF(), TS_X509_ALGOR_print_bio(), X509_ATTRIBUTE_set1_data(), X509_CRL_check_suiteb(), X509_CRL_get_signature_nid(), X509_get_signature_type(), X509_NAME_ENTRY_set_data(), X509_REQ_get_signature_nid(), X509_REQ_print_ex(), X509_signature_print(), X509_supported_extension(), and X509V3_EXT_get().
OBJ_obj2txt()
int OBJ_obj2txt (char * buf, int buf_len, const ASN1_OBJECT * a, int no_name)
Definition at line 394 of file obj_dat.c.
Referenced by TS_OBJ_print_bio().
OBJ_sigid_free()
void OBJ_sigid_free (void)
Definition at line 132 of file obj_xref.c.
Referenced by evp_cleanup_int().
OBJ_sn2nid()
int OBJ_sn2nid (const char * s)
Definition at line 559 of file obj_dat.c.
References ADDED_SNAME, and NULL.
Referenced by OBJ_create().
OBJ_txt2nid()
int OBJ_txt2nid (const char * s)
Definition at line 528 of file obj_dat.c.
References ASN1_OBJECT_free(), nid, ADDED_OBJ::obj, OBJ_obj2nid(), and OBJ_txt2obj().
Referenced by OCSP_accept_responses_new(), and parse_name().
OBJ_txt2obj()
ASN1_OBJECT* OBJ_txt2obj (const char * s, int no_name)
Definition at line 350 of file obj_dat.c.
References nid, NID_undef, and NULL.
Referenced by OBJ_create(), OBJ_txt2nid(), opt_verify(), X509_ATTRIBUTE_create_by_txt(), and X509_NAME_ENTRY_create_by_txt().