include/openssl/rand.h File Reference
rand.h File Reference
#include <stdlib.h>
#include <openssl/ossl_typ.h>
#include <openssl/e_os2.h>
Data Structures
struct RAND_METHOD
Macros
#define RAND_cleanup() while(0) continue
#define RAND_F_RAND_BYTES 100
#define RAND_R_PRNG_NOT_SEEDED 100
Functions
int RAND_set_rand_method (const RAND_METHOD *meth)
const RAND_METHOD * RAND_get_rand_method (void)
int RAND_set_rand_engine (ENGINE *engine)
RAND_METHOD * RAND_OpenSSL (void)
int RAND_bytes (unsigned char *buf, int num)
void RAND_seed (const void *buf, int num)
void RAND_add (const void *buf, int num, double entropy)
int RAND_load_file (const char *file, long max_bytes)
int RAND_write_file (const char *file)
const char * RAND_file_name (char *file, size_t num)
int RAND_status (void)
int RAND_query_egd_bytes (const char *path, unsigned char *buf, int bytes)
int RAND_egd (const char *path)
int RAND_egd_bytes (const char *path, int bytes)
int RAND_poll (void)
int ERR_load_RAND_strings (void)
Macro Definition Documentation
RAND_cleanup
#define RAND_cleanup () while(0) continue
Definition at line 44 of file rand.h.
RAND_F_RAND_BYTES
#define RAND_F_RAND_BYTES 100
Definition at line 81 of file rand.h.
RAND_R_PRNG_NOT_SEEDED
#define RAND_R_PRNG_NOT_SEEDED 100
Definition at line 84 of file rand.h.
Function Documentation
ERR_load_RAND_strings()
int ERR_load_RAND_strings (void)
Definition at line 33 of file rand_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
RAND_add()
void RAND_add (const void * buf, int num, double entropy)
Definition at line 95 of file rand_lib.c.
Referenced by EVP_PKEY2PKCS8().
RAND_bytes()
int RAND_bytes (unsigned char * buf, int num)
Definition at line 102 of file rand_lib.c.
Referenced by CMS_ReceiptRequest_create0(), EVP_CIPHER_CTX_rand_key(), PKCS12_setup_mac(), RSA_padding_add_PKCS1_type_2(), RSA_padding_add_SSLv23(), SRP_Calc_A_param(), SRP_create_verifier_BN(), ssl_fill_hello_random(), and SSL_srp_server_param_with_username().
RAND_egd()
int RAND_egd (const char * path)
Definition at line 242 of file rand_egd.c.
References RAND_egd_bytes().
Referenced by app_RAND_load_file(), and app_RAND_load_files().
RAND_egd_bytes()
int RAND_egd_bytes (const char * path, int bytes)
Definition at line 229 of file rand_egd.c.
Referenced by RAND_egd().
RAND_file_name()
const char* RAND_file_name (char * file, size_t num)
Definition at line 282 of file randfile.c.
Referenced by app_RAND_load_file().
RAND_get_rand_method()
const RAND_METHOD* RAND_get_rand_method (void)
Definition at line 39 of file rand_lib.c.
Referenced by rand_cleanup_int(), and RAND_status().
RAND_load_file()
int RAND_load_file (const char * file, long max_bytes)
Definition at line 112 of file randfile.c.
Referenced by app_RAND_load_files().
RAND_OpenSSL()
RAND_METHOD* RAND_OpenSSL (void)
Definition at line 98 of file md_rand.c.
RAND_poll()
int RAND_poll (void)
Definition at line 142 of file rand_unix.c.
References DEVRANDOM, DEVRANDOM_EGD, ENTROPY_NEEDED, and NULL.
RAND_query_egd_bytes()
int RAND_query_egd_bytes (const char * path, unsigned char * buf, int bytes)
Definition at line 92 of file rand_egd.c.
RAND_seed()
void RAND_seed (const void * buf, int num)
Definition at line 88 of file rand_lib.c.
Referenced by main(), and ossl_ecdsa_sign().
RAND_set_rand_engine()
int RAND_set_rand_engine (ENGINE * engine)
Definition at line 61 of file rand_lib.c.
References ENGINE_finish(), ENGINE_get_RAND(), ENGINE_init(), NULL, and RAND_set_rand_method().
RAND_set_rand_method()
int RAND_set_rand_method (const RAND_METHOD * meth)
Definition at line 29 of file rand_lib.c.
References ENGINE_finish().
Referenced by rand_cleanup_int(), RAND_set_rand_engine(), and restore_rand().
RAND_status()
int RAND_status (void)
Definition at line 120 of file rand_lib.c.
References RAND_get_rand_method().
RAND_write_file()
int RAND_write_file (const char * file)
Definition at line 184 of file randfile.c.