include/openssl/engine.h File Reference
engine.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/bn.h>
#include <openssl/rsa.h>
#include <openssl/dsa.h>
#include <openssl/dh.h>
#include <openssl/ec.h>
#include <openssl/rand.h>
#include <openssl/ui.h>
#include <openssl/err.h>
#include <openssl/ossl_typ.h>
#include <openssl/symhacks.h>
#include <openssl/x509.h>
Data Structures
struct ENGINE_CMD_DEFN
struct dynamic_MEM_fns
struct dynamic_fns
Macros
#define ENGINE_METHOD_RSA (unsigned int)0x0001
#define ENGINE_METHOD_DSA (unsigned int)0x0002
#define ENGINE_METHOD_DH (unsigned int)0x0004
#define ENGINE_METHOD_RAND (unsigned int)0x0008
#define ENGINE_METHOD_CIPHERS (unsigned int)0x0040
#define ENGINE_METHOD_DIGESTS (unsigned int)0x0080
#define ENGINE_METHOD_PKEY_METHS (unsigned int)0x0200
#define ENGINE_METHOD_PKEY_ASN1_METHS (unsigned int)0x0400
#define ENGINE_METHOD_EC (unsigned int)0x0800
#define ENGINE_METHOD_ALL (unsigned int)0xFFFF
#define ENGINE_METHOD_NONE (unsigned int)0x0000
#define ENGINE_TABLE_FLAG_NOINIT (unsigned int)0x0001
#define ENGINE_FLAGS_MANUAL_CMD_CTRL (int)0x0002
#define ENGINE_FLAGS_BY_ID_COPY (int)0x0004
#define ENGINE_FLAGS_NO_REGISTER_ALL (int)0x0008
#define ENGINE_CMD_FLAG_NUMERIC (unsigned int)0x0001
#define ENGINE_CMD_FLAG_STRING (unsigned int)0x0002
#define ENGINE_CMD_FLAG_NO_INPUT (unsigned int)0x0004
#define ENGINE_CMD_FLAG_INTERNAL (unsigned int)0x0008
#define ENGINE_CTRL_SET_LOGSTREAM 1
#define ENGINE_CTRL_SET_PASSWORD_CALLBACK 2
#define ENGINE_CTRL_HUP
#define ENGINE_CTRL_SET_USER_INTERFACE 4/* Alternative to callback */
#define ENGINE_CTRL_SET_CALLBACK_DATA
#define ENGINE_CTRL_LOAD_CONFIGURATION
#define ENGINE_CTRL_LOAD_SECTION
#define ENGINE_CTRL_HAS_CTRL_FUNCTION 10
#define ENGINE_CTRL_GET_FIRST_CMD_TYPE 11
#define ENGINE_CTRL_GET_NEXT_CMD_TYPE 12
#define ENGINE_CTRL_GET_CMD_FROM_NAME 13
#define ENGINE_CTRL_GET_NAME_LEN_FROM_CMD 14
#define ENGINE_CTRL_GET_NAME_FROM_CMD 15
#define ENGINE_CTRL_GET_DESC_LEN_FROM_CMD 16
#define ENGINE_CTRL_GET_DESC_FROM_CMD 17
#define ENGINE_CTRL_GET_CMD_FLAGS 18
#define ENGINE_CMD_BASE 200
#define ENGINE_CTRL_CHIL_SET_FORKCHECK 100
#define ENGINE_CTRL_CHIL_NO_LOCKING 101
#define ENGINE_load_openssl() OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_OPENSSL, NULL)
#define ENGINE_load_dynamic() OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_DYNAMIC, NULL)
#define ENGINE_load_padlock() OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_PADLOCK, NULL)
#define ENGINE_load_capi() OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_CAPI, NULL)
#define ENGINE_load_afalg() OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_AFALG, NULL)
#define ENGINE_load_cryptodev() OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_CRYPTODEV, NULL)
#define ENGINE_load_rdrand() OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_RDRAND, NULL)
#define ENGINE_get_ex_new_index(l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_ENGINE, l, p, newf, dupf, freef)
#define ENGINE_cleanup() while(0) continue
#define OSSL_DYNAMIC_VERSION (unsigned long)0x00030000
#define OSSL_DYNAMIC_OLDEST (unsigned long)0x00030000
#define IMPLEMENT_DYNAMIC_CHECK_FN()
#define IMPLEMENT_DYNAMIC_BIND_FN(fn)
#define ENGINE_F_DYNAMIC_CTRL 180
#define ENGINE_F_DYNAMIC_GET_DATA_CTX 181
#define ENGINE_F_DYNAMIC_LOAD 182
#define ENGINE_F_DYNAMIC_SET_DATA_CTX 183
#define ENGINE_F_ENGINE_ADD 105
#define ENGINE_F_ENGINE_BY_ID 106
#define ENGINE_F_ENGINE_CMD_IS_EXECUTABLE 170
#define ENGINE_F_ENGINE_CTRL 142
#define ENGINE_F_ENGINE_CTRL_CMD 178
#define ENGINE_F_ENGINE_CTRL_CMD_STRING 171
#define ENGINE_F_ENGINE_FINISH 107
#define ENGINE_F_ENGINE_GET_CIPHER 185
#define ENGINE_F_ENGINE_GET_DIGEST 186
#define ENGINE_F_ENGINE_GET_FIRST 195
#define ENGINE_F_ENGINE_GET_LAST 196
#define ENGINE_F_ENGINE_GET_NEXT 115
#define ENGINE_F_ENGINE_GET_PKEY_ASN1_METH 193
#define ENGINE_F_ENGINE_GET_PKEY_METH 192
#define ENGINE_F_ENGINE_GET_PREV 116
#define ENGINE_F_ENGINE_INIT 119
#define ENGINE_F_ENGINE_LIST_ADD 120
#define ENGINE_F_ENGINE_LIST_REMOVE 121
#define ENGINE_F_ENGINE_LOAD_PRIVATE_KEY 150
#define ENGINE_F_ENGINE_LOAD_PUBLIC_KEY 151
#define ENGINE_F_ENGINE_LOAD_SSL_CLIENT_CERT 194
#define ENGINE_F_ENGINE_NEW 122
#define ENGINE_F_ENGINE_PKEY_ASN1_FIND_STR 197
#define ENGINE_F_ENGINE_REMOVE 123
#define ENGINE_F_ENGINE_SET_DEFAULT_STRING 189
#define ENGINE_F_ENGINE_SET_ID 129
#define ENGINE_F_ENGINE_SET_NAME 130
#define ENGINE_F_ENGINE_TABLE_REGISTER 184
#define ENGINE_F_ENGINE_UNLOCKED_FINISH 191
#define ENGINE_F_ENGINE_UP_REF 190
#define ENGINE_F_INT_CTRL_HELPER 172
#define ENGINE_F_INT_ENGINE_CONFIGURE 188
#define ENGINE_F_INT_ENGINE_MODULE_INIT 187
#define ENGINE_R_ALREADY_LOADED 100
#define ENGINE_R_ARGUMENT_IS_NOT_A_NUMBER 133
#define ENGINE_R_CMD_NOT_EXECUTABLE 134
#define ENGINE_R_COMMAND_TAKES_INPUT 135
#define ENGINE_R_COMMAND_TAKES_NO_INPUT 136
#define ENGINE_R_CONFLICTING_ENGINE_ID 103
#define ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED 119
#define ENGINE_R_DSO_FAILURE 104
#define ENGINE_R_DSO_NOT_FOUND 132
#define ENGINE_R_ENGINES_SECTION_ERROR 148
#define ENGINE_R_ENGINE_CONFIGURATION_ERROR 102
#define ENGINE_R_ENGINE_IS_NOT_IN_LIST 105
#define ENGINE_R_ENGINE_SECTION_ERROR 149
#define ENGINE_R_FAILED_LOADING_PRIVATE_KEY 128
#define ENGINE_R_FAILED_LOADING_PUBLIC_KEY 129
#define ENGINE_R_FINISH_FAILED 106
#define ENGINE_R_ID_OR_NAME_MISSING 108
#define ENGINE_R_INIT_FAILED 109
#define ENGINE_R_INTERNAL_LIST_ERROR 110
#define ENGINE_R_INVALID_ARGUMENT 143
#define ENGINE_R_INVALID_CMD_NAME 137
#define ENGINE_R_INVALID_CMD_NUMBER 138
#define ENGINE_R_INVALID_INIT_VALUE 151
#define ENGINE_R_INVALID_STRING 150
#define ENGINE_R_NOT_INITIALISED 117
#define ENGINE_R_NOT_LOADED 112
#define ENGINE_R_NO_CONTROL_FUNCTION 120
#define ENGINE_R_NO_INDEX 144
#define ENGINE_R_NO_LOAD_FUNCTION 125
#define ENGINE_R_NO_REFERENCE 130
#define ENGINE_R_NO_SUCH_ENGINE 116
#define ENGINE_R_UNIMPLEMENTED_CIPHER 146
#define ENGINE_R_UNIMPLEMENTED_DIGEST 147
#define ENGINE_R_UNIMPLEMENTED_PUBLIC_KEY_METHOD 101
#define ENGINE_R_VERSION_INCOMPATIBILITY 145
Typedefs
typedef int(* ENGINE_GEN_FUNC_PTR) (void)
typedef int(* ENGINE_GEN_INT_FUNC_PTR) (ENGINE *)
typedef int(* ENGINE_CTRL_FUNC_PTR) (ENGINE *, int, long, void *, void(*f) (void))
typedef EVP_PKEY *(* ENGINE_LOAD_KEY_PTR) (ENGINE *, const char *, UI_METHOD *ui_method, void *callback_data)
typedef int(* ENGINE_SSL_CLIENT_CERT_PTR) (ENGINE *, SSL *ssl, STACK_OF(X509_NAME) *ca_dn, X509 **pcert, EVP_PKEY **pkey, STACK_OF(X509) **pother, UI_METHOD *ui_method, void *callback_data)
typedef int(* ENGINE_CIPHERS_PTR) (ENGINE *, const EVP_CIPHER **, const int **, int)
typedef int(* ENGINE_DIGESTS_PTR) (ENGINE *, const EVP_MD **, const int **, int)
typedef int(* ENGINE_PKEY_METHS_PTR) (ENGINE *, EVP_PKEY_METHOD **, const int **, int)
typedef int(* ENGINE_PKEY_ASN1_METHS_PTR) (ENGINE *, EVP_PKEY_ASN1_METHOD **, const int **, int)
typedef void *(* dyn_MEM_malloc_fn) (size_t, const char *, int)
typedef void *(* dyn_MEM_realloc_fn) (void *, size_t, const char *, int)
typedef void(* dyn_MEM_free_fn) (void *, const char *, int)
typedef unsigned long(* dynamic_v_check_fn) (unsigned long ossl_version)
typedef int(* dynamic_bind_engine) (ENGINE *e, const char *id, const dynamic_fns *fns)
Functions
ENGINE * ENGINE_get_first (void)
ENGINE * ENGINE_get_last (void)
ENGINE * ENGINE_get_next (ENGINE *e)
ENGINE * ENGINE_get_prev (ENGINE *e)
int ENGINE_add (ENGINE *e)
int ENGINE_remove (ENGINE *e)
ENGINE * ENGINE_by_id (const char *id)
void ENGINE_load_builtin_engines (void)
unsigned int ENGINE_get_table_flags (void)
void ENGINE_set_table_flags (unsigned int flags)
int ENGINE_register_RSA (ENGINE *e)
void ENGINE_unregister_RSA (ENGINE *e)
void ENGINE_register_all_RSA (void)
int ENGINE_register_DSA (ENGINE *e)
void ENGINE_unregister_DSA (ENGINE *e)
void ENGINE_register_all_DSA (void)
int ENGINE_register_EC (ENGINE *e)
void ENGINE_unregister_EC (ENGINE *e)
void ENGINE_register_all_EC (void)
int ENGINE_register_DH (ENGINE *e)
void ENGINE_unregister_DH (ENGINE *e)
void ENGINE_register_all_DH (void)
int ENGINE_register_RAND (ENGINE *e)
void ENGINE_unregister_RAND (ENGINE *e)
void ENGINE_register_all_RAND (void)
int ENGINE_register_ciphers (ENGINE *e)
void ENGINE_unregister_ciphers (ENGINE *e)
void ENGINE_register_all_ciphers (void)
int ENGINE_register_digests (ENGINE *e)
void ENGINE_unregister_digests (ENGINE *e)
void ENGINE_register_all_digests (void)
int ENGINE_register_pkey_meths (ENGINE *e)
void ENGINE_unregister_pkey_meths (ENGINE *e)
void ENGINE_register_all_pkey_meths (void)
int ENGINE_register_pkey_asn1_meths (ENGINE *e)
void ENGINE_unregister_pkey_asn1_meths (ENGINE *e)
void ENGINE_register_all_pkey_asn1_meths (void)
int ENGINE_register_complete (ENGINE *e)
int ENGINE_register_all_complete (void)
int ENGINE_ctrl (ENGINE *e, int cmd, long i, void *p, void(*f)(void))
int ENGINE_cmd_is_executable (ENGINE *e, int cmd)
int ENGINE_ctrl_cmd (ENGINE *e, const char *cmd_name, long i, void *p, void(*f)(void), int cmd_optional)
int ENGINE_ctrl_cmd_string (ENGINE *e, const char *cmd_name, const char *arg, int cmd_optional)
ENGINE * ENGINE_new (void)
int ENGINE_free (ENGINE *e)
int ENGINE_up_ref (ENGINE *e)
int ENGINE_set_id (ENGINE *e, const char *id)
int ENGINE_set_name (ENGINE *e, const char *name)
int ENGINE_set_RSA (ENGINE *e, const RSA_METHOD *rsa_meth)
int ENGINE_set_DSA (ENGINE *e, const DSA_METHOD *dsa_meth)
int ENGINE_set_EC (ENGINE *e, const EC_KEY_METHOD *ecdsa_meth)
int ENGINE_set_DH (ENGINE *e, const DH_METHOD *dh_meth)
int ENGINE_set_RAND (ENGINE *e, const RAND_METHOD *rand_meth)
int ENGINE_set_destroy_function (ENGINE *e, ENGINE_GEN_INT_FUNC_PTR destroy_f)
int ENGINE_set_init_function (ENGINE *e, ENGINE_GEN_INT_FUNC_PTR init_f)
int ENGINE_set_finish_function (ENGINE *e, ENGINE_GEN_INT_FUNC_PTR finish_f)
int ENGINE_set_ctrl_function (ENGINE *e, ENGINE_CTRL_FUNC_PTR ctrl_f)
int ENGINE_set_load_privkey_function (ENGINE *e, ENGINE_LOAD_KEY_PTR loadpriv_f)
int ENGINE_set_load_pubkey_function (ENGINE *e, ENGINE_LOAD_KEY_PTR loadpub_f)
int ENGINE_set_load_ssl_client_cert_function (ENGINE *e, ENGINE_SSL_CLIENT_CERT_PTR loadssl_f)
int ENGINE_set_ciphers (ENGINE *e, ENGINE_CIPHERS_PTR f)
int ENGINE_set_digests (ENGINE *e, ENGINE_DIGESTS_PTR f)
int ENGINE_set_pkey_meths (ENGINE *e, ENGINE_PKEY_METHS_PTR f)
int ENGINE_set_pkey_asn1_meths (ENGINE *e, ENGINE_PKEY_ASN1_METHS_PTR f)
int ENGINE_set_flags (ENGINE *e, int flags)
int ENGINE_set_cmd_defns (ENGINE *e, const ENGINE_CMD_DEFN *defns)
int ENGINE_set_ex_data (ENGINE *e, int idx, void *arg)
void * ENGINE_get_ex_data (const ENGINE *e, int idx)
const char * ENGINE_get_id (const ENGINE *e)
const char * ENGINE_get_name (const ENGINE *e)
const RSA_METHOD * ENGINE_get_RSA (const ENGINE *e)
const DSA_METHOD * ENGINE_get_DSA (const ENGINE *e)
const EC_KEY_METHOD * ENGINE_get_EC (const ENGINE *e)
const DH_METHOD * ENGINE_get_DH (const ENGINE *e)
const RAND_METHOD * ENGINE_get_RAND (const ENGINE *e)
ENGINE_GEN_INT_FUNC_PTR ENGINE_get_destroy_function (const ENGINE *e)
ENGINE_GEN_INT_FUNC_PTR ENGINE_get_init_function (const ENGINE *e)
ENGINE_GEN_INT_FUNC_PTR ENGINE_get_finish_function (const ENGINE *e)
ENGINE_CTRL_FUNC_PTR ENGINE_get_ctrl_function (const ENGINE *e)
ENGINE_LOAD_KEY_PTR ENGINE_get_load_privkey_function (const ENGINE *e)
ENGINE_LOAD_KEY_PTR ENGINE_get_load_pubkey_function (const ENGINE *e)
ENGINE_SSL_CLIENT_CERT_PTR ENGINE_get_ssl_client_cert_function (const ENGINE *e)
ENGINE_CIPHERS_PTR ENGINE_get_ciphers (const ENGINE *e)
ENGINE_DIGESTS_PTR ENGINE_get_digests (const ENGINE *e)
ENGINE_PKEY_METHS_PTR ENGINE_get_pkey_meths (const ENGINE *e)
ENGINE_PKEY_ASN1_METHS_PTR ENGINE_get_pkey_asn1_meths (const ENGINE *e)
const EVP_CIPHER * ENGINE_get_cipher (ENGINE *e, int nid)
const EVP_MD * ENGINE_get_digest (ENGINE *e, int nid)
const EVP_PKEY_METHOD * ENGINE_get_pkey_meth (ENGINE *e, int nid)
const EVP_PKEY_ASN1_METHOD * ENGINE_get_pkey_asn1_meth (ENGINE *e, int nid)
const EVP_PKEY_ASN1_METHOD * ENGINE_get_pkey_asn1_meth_str (ENGINE *e, const char *str, int len)
const EVP_PKEY_ASN1_METHOD * ENGINE_pkey_asn1_find_str (ENGINE **pe, const char *str, int len)
const ENGINE_CMD_DEFN * ENGINE_get_cmd_defns (const ENGINE *e)
int ENGINE_get_flags (const ENGINE *e)
int ENGINE_init (ENGINE *e)
int ENGINE_finish (ENGINE *e)
EVP_PKEY * ENGINE_load_private_key (ENGINE *e, const char *key_id, UI_METHOD *ui_method, void *callback_data)
EVP_PKEY * ENGINE_load_public_key (ENGINE *e, const char *key_id, UI_METHOD *ui_method, void *callback_data)
int ENGINE_load_ssl_client_cert (ENGINE *e, SSL *s, STACK_OF(X509_NAME) *ca_dn, X509 **pcert, EVP_PKEY **ppkey, STACK_OF(X509) **pother, UI_METHOD *ui_method, void *callback_data)
ENGINE * ENGINE_get_default_RSA (void)
ENGINE * ENGINE_get_default_DSA (void)
ENGINE * ENGINE_get_default_EC (void)
ENGINE * ENGINE_get_default_DH (void)
ENGINE * ENGINE_get_default_RAND (void)
ENGINE * ENGINE_get_cipher_engine (int nid)
ENGINE * ENGINE_get_digest_engine (int nid)
ENGINE * ENGINE_get_pkey_meth_engine (int nid)
ENGINE * ENGINE_get_pkey_asn1_meth_engine (int nid)
int ENGINE_set_default_RSA (ENGINE *e)
int ENGINE_set_default_string (ENGINE *e, const char *def_list)
int ENGINE_set_default_DSA (ENGINE *e)
int ENGINE_set_default_EC (ENGINE *e)
int ENGINE_set_default_DH (ENGINE *e)
int ENGINE_set_default_RAND (ENGINE *e)
int ENGINE_set_default_ciphers (ENGINE *e)
int ENGINE_set_default_digests (ENGINE *e)
int ENGINE_set_default_pkey_meths (ENGINE *e)
int ENGINE_set_default_pkey_asn1_meths (ENGINE *e)
int ENGINE_set_default (ENGINE *e, unsigned int flags)
void ENGINE_add_conf_module (void)
void * ENGINE_get_static_state (void)
int ERR_load_ENGINE_strings (void)
Macro Definition Documentation
ENGINE_cleanup
#define ENGINE_cleanup () while(0) continue
Definition at line 506 of file engine.h.
ENGINE_CMD_BASE
#define ENGINE_CMD_BASE 200
Definition at line 222 of file engine.h.
ENGINE_CMD_FLAG_INTERNAL
#define ENGINE_CMD_FLAG_INTERNAL (unsigned int)0x0008
Definition at line 125 of file engine.h.
ENGINE_CMD_FLAG_NO_INPUT
#define ENGINE_CMD_FLAG_NO_INPUT (unsigned int)0x0004
Definition at line 119 of file engine.h.
Referenced by ENGINE_cmd_is_executable().
ENGINE_CMD_FLAG_NUMERIC
#define ENGINE_CMD_FLAG_NUMERIC (unsigned int)0x0001
Definition at line 109 of file engine.h.
Referenced by ENGINE_cmd_is_executable().
ENGINE_CMD_FLAG_STRING
#define ENGINE_CMD_FLAG_STRING (unsigned int)0x0002
Definition at line 114 of file engine.h.
Referenced by ENGINE_cmd_is_executable().
ENGINE_CTRL_CHIL_NO_LOCKING
#define ENGINE_CTRL_CHIL_NO_LOCKING 101
Definition at line 239 of file engine.h.
ENGINE_CTRL_CHIL_SET_FORKCHECK
#define ENGINE_CTRL_CHIL_SET_FORKCHECK 100
Definition at line 233 of file engine.h.
ENGINE_CTRL_GET_CMD_FLAGS
#define ENGINE_CTRL_GET_CMD_FLAGS 18
Definition at line 216 of file engine.h.
Referenced by ENGINE_cmd_is_executable(), and ENGINE_ctrl().
ENGINE_CTRL_GET_CMD_FROM_NAME
#define ENGINE_CTRL_GET_CMD_FROM_NAME 13
Definition at line 197 of file engine.h.
Referenced by ENGINE_ctrl(), and ENGINE_ctrl_cmd().
ENGINE_CTRL_GET_DESC_FROM_CMD
#define ENGINE_CTRL_GET_DESC_FROM_CMD 17
Definition at line 210 of file engine.h.
Referenced by ENGINE_ctrl().
ENGINE_CTRL_GET_DESC_LEN_FROM_CMD
#define ENGINE_CTRL_GET_DESC_LEN_FROM_CMD 16
Definition at line 209 of file engine.h.
Referenced by ENGINE_ctrl().
ENGINE_CTRL_GET_FIRST_CMD_TYPE
#define ENGINE_CTRL_GET_FIRST_CMD_TYPE 11
Definition at line 187 of file engine.h.
Referenced by ENGINE_ctrl().
ENGINE_CTRL_GET_NAME_FROM_CMD
#define ENGINE_CTRL_GET_NAME_FROM_CMD 15
Definition at line 207 of file engine.h.
Referenced by ENGINE_ctrl().
ENGINE_CTRL_GET_NAME_LEN_FROM_CMD
#define ENGINE_CTRL_GET_NAME_LEN_FROM_CMD 14
Definition at line 206 of file engine.h.
Referenced by ENGINE_ctrl().
ENGINE_CTRL_GET_NEXT_CMD_TYPE
#define ENGINE_CTRL_GET_NEXT_CMD_TYPE 12
Definition at line 192 of file engine.h.
Referenced by ENGINE_ctrl().
ENGINE_CTRL_HAS_CTRL_FUNCTION
#define ENGINE_CTRL_HAS_CTRL_FUNCTION 10
Definition at line 182 of file engine.h.
Referenced by ENGINE_ctrl().
ENGINE_CTRL_HUP
#define ENGINE_CTRL_HUP
Value:
3/* Close and reinitialise
                                                   * any handles/connections
                                                   * etc. */
Definition at line 146 of file engine.h.
ENGINE_CTRL_LOAD_CONFIGURATION
#define ENGINE_CTRL_LOAD_CONFIGURATION
Value:
6/* Load a configuration,
                                                   * given a string that
                                                   * represents a file name
                                                   * or so */
Definition at line 154 of file engine.h.
ENGINE_CTRL_LOAD_SECTION
#define ENGINE_CTRL_LOAD_SECTION
Value:
7/* Load data from a given
                                                   * section in the already
                                                   * loaded configuration */
Definition at line 158 of file engine.h.
ENGINE_CTRL_SET_CALLBACK_DATA
#define ENGINE_CTRL_SET_CALLBACK_DATA
Value:
5/* User-specific data, used
                                                   * when calling the password
                                                   * callback and the user
                                                   * interface */
Definition at line 150 of file engine.h.
ENGINE_CTRL_SET_LOGSTREAM
#define ENGINE_CTRL_SET_LOGSTREAM 1
Definition at line 144 of file engine.h.
ENGINE_CTRL_SET_PASSWORD_CALLBACK
#define ENGINE_CTRL_SET_PASSWORD_CALLBACK 2
Definition at line 145 of file engine.h.
ENGINE_CTRL_SET_USER_INTERFACE
#define ENGINE_CTRL_SET_USER_INTERFACE 4/* Alternative to callback */
Definition at line 149 of file engine.h.
ENGINE_F_DYNAMIC_CTRL
#define ENGINE_F_DYNAMIC_CTRL 180
Definition at line 761 of file engine.h.
ENGINE_F_DYNAMIC_GET_DATA_CTX
#define ENGINE_F_DYNAMIC_GET_DATA_CTX 181
Definition at line 762 of file engine.h.
ENGINE_F_DYNAMIC_LOAD
#define ENGINE_F_DYNAMIC_LOAD 182
Definition at line 763 of file engine.h.
ENGINE_F_DYNAMIC_SET_DATA_CTX
#define ENGINE_F_DYNAMIC_SET_DATA_CTX 183
Definition at line 764 of file engine.h.
ENGINE_F_ENGINE_ADD
#define ENGINE_F_ENGINE_ADD 105
Definition at line 765 of file engine.h.
Referenced by ENGINE_add().
ENGINE_F_ENGINE_BY_ID
#define ENGINE_F_ENGINE_BY_ID 106
Definition at line 766 of file engine.h.
Referenced by ENGINE_by_id().
ENGINE_F_ENGINE_CMD_IS_EXECUTABLE
#define ENGINE_F_ENGINE_CMD_IS_EXECUTABLE 170
Definition at line 767 of file engine.h.
Referenced by ENGINE_cmd_is_executable().
ENGINE_F_ENGINE_CTRL
#define ENGINE_F_ENGINE_CTRL 142
Definition at line 768 of file engine.h.
Referenced by ENGINE_ctrl().
ENGINE_F_ENGINE_CTRL_CMD
#define ENGINE_F_ENGINE_CTRL_CMD 178
Definition at line 769 of file engine.h.
Referenced by ENGINE_ctrl_cmd().
ENGINE_F_ENGINE_CTRL_CMD_STRING
#define ENGINE_F_ENGINE_CTRL_CMD_STRING 171
Definition at line 770 of file engine.h.
ENGINE_F_ENGINE_FINISH
#define ENGINE_F_ENGINE_FINISH 107
Definition at line 771 of file engine.h.
Referenced by ENGINE_finish().
ENGINE_F_ENGINE_GET_CIPHER
#define ENGINE_F_ENGINE_GET_CIPHER 185
Definition at line 772 of file engine.h.
ENGINE_F_ENGINE_GET_DIGEST
#define ENGINE_F_ENGINE_GET_DIGEST 186
Definition at line 773 of file engine.h.
ENGINE_F_ENGINE_GET_FIRST
#define ENGINE_F_ENGINE_GET_FIRST 195
Definition at line 774 of file engine.h.
ENGINE_F_ENGINE_GET_LAST
#define ENGINE_F_ENGINE_GET_LAST 196
Definition at line 775 of file engine.h.
ENGINE_F_ENGINE_GET_NEXT
#define ENGINE_F_ENGINE_GET_NEXT 115
Definition at line 776 of file engine.h.
ENGINE_F_ENGINE_GET_PKEY_ASN1_METH
#define ENGINE_F_ENGINE_GET_PKEY_ASN1_METH 193
Definition at line 777 of file engine.h.
ENGINE_F_ENGINE_GET_PKEY_METH
#define ENGINE_F_ENGINE_GET_PKEY_METH 192
Definition at line 778 of file engine.h.
ENGINE_F_ENGINE_GET_PREV
#define ENGINE_F_ENGINE_GET_PREV 116
Definition at line 779 of file engine.h.
ENGINE_F_ENGINE_INIT
#define ENGINE_F_ENGINE_INIT 119
Definition at line 780 of file engine.h.
ENGINE_F_ENGINE_LIST_ADD
#define ENGINE_F_ENGINE_LIST_ADD 120
Definition at line 781 of file engine.h.
ENGINE_F_ENGINE_LIST_REMOVE
#define ENGINE_F_ENGINE_LIST_REMOVE 121
Definition at line 782 of file engine.h.
ENGINE_F_ENGINE_LOAD_PRIVATE_KEY
#define ENGINE_F_ENGINE_LOAD_PRIVATE_KEY 150
Definition at line 783 of file engine.h.
ENGINE_F_ENGINE_LOAD_PUBLIC_KEY
#define ENGINE_F_ENGINE_LOAD_PUBLIC_KEY 151
Definition at line 784 of file engine.h.
ENGINE_F_ENGINE_LOAD_SSL_CLIENT_CERT
#define ENGINE_F_ENGINE_LOAD_SSL_CLIENT_CERT 194
Definition at line 785 of file engine.h.
ENGINE_F_ENGINE_NEW
#define ENGINE_F_ENGINE_NEW 122
Definition at line 786 of file engine.h.
ENGINE_F_ENGINE_PKEY_ASN1_FIND_STR
#define ENGINE_F_ENGINE_PKEY_ASN1_FIND_STR 197
Definition at line 787 of file engine.h.
Referenced by ENGINE_pkey_asn1_find_str().
ENGINE_F_ENGINE_REMOVE
#define ENGINE_F_ENGINE_REMOVE 123
Definition at line 788 of file engine.h.
Referenced by ENGINE_remove().
ENGINE_F_ENGINE_SET_DEFAULT_STRING
#define ENGINE_F_ENGINE_SET_DEFAULT_STRING 189
Definition at line 789 of file engine.h.
ENGINE_F_ENGINE_SET_ID
#define ENGINE_F_ENGINE_SET_ID 129
Definition at line 790 of file engine.h.
Referenced by ENGINE_set_id().
ENGINE_F_ENGINE_SET_NAME
#define ENGINE_F_ENGINE_SET_NAME 130
Definition at line 791 of file engine.h.
Referenced by ENGINE_set_name().
ENGINE_F_ENGINE_TABLE_REGISTER
#define ENGINE_F_ENGINE_TABLE_REGISTER 184
Definition at line 792 of file engine.h.
ENGINE_F_ENGINE_UNLOCKED_FINISH
#define ENGINE_F_ENGINE_UNLOCKED_FINISH 191
Definition at line 793 of file engine.h.
Referenced by engine_unlocked_finish().
ENGINE_F_ENGINE_UP_REF
#define ENGINE_F_ENGINE_UP_REF 190
Definition at line 794 of file engine.h.
Referenced by ENGINE_up_ref().
ENGINE_F_INT_CTRL_HELPER
#define ENGINE_F_INT_CTRL_HELPER 172
Definition at line 795 of file engine.h.
ENGINE_F_INT_ENGINE_CONFIGURE
#define ENGINE_F_INT_ENGINE_CONFIGURE 188
Definition at line 796 of file engine.h.
ENGINE_F_INT_ENGINE_MODULE_INIT
#define ENGINE_F_INT_ENGINE_MODULE_INIT 187
Definition at line 797 of file engine.h.
ENGINE_FLAGS_BY_ID_COPY
#define ENGINE_FLAGS_BY_ID_COPY (int)0x0004
Definition at line 86 of file engine.h.
ENGINE_FLAGS_MANUAL_CMD_CTRL
#define ENGINE_FLAGS_MANUAL_CMD_CTRL (int)0x0002
Definition at line 74 of file engine.h.
Referenced by ENGINE_ctrl().
ENGINE_FLAGS_NO_REGISTER_ALL
#define ENGINE_FLAGS_NO_REGISTER_ALL (int)0x0008
Definition at line 94 of file engine.h.
Referenced by ENGINE_register_all_complete().
ENGINE_get_ex_new_index
#define ENGINE_get_ex_new_index (l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_ENGINE, l, p, newf, dupf, freef)
Definition at line 496 of file engine.h.
ENGINE_load_afalg
#define ENGINE_load_afalg () OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_AFALG, NULL)
Definition at line 337 of file engine.h.
ENGINE_load_capi
#define ENGINE_load_capi () OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_CAPI, NULL)
Definition at line 335 of file engine.h.
ENGINE_load_cryptodev
#define ENGINE_load_cryptodev () OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_CRYPTODEV, NULL)
Definition at line 340 of file engine.h.
ENGINE_load_dynamic
#define ENGINE_load_dynamic () OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_DYNAMIC, NULL)
Definition at line 330 of file engine.h.
ENGINE_load_openssl
#define ENGINE_load_openssl () OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_OPENSSL, NULL)
Definition at line 328 of file engine.h.
ENGINE_load_padlock
#define ENGINE_load_padlock () OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_PADLOCK, NULL)
Definition at line 333 of file engine.h.
ENGINE_load_rdrand
#define ENGINE_load_rdrand () OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_RDRAND, NULL)
Definition at line 342 of file engine.h.
ENGINE_METHOD_ALL
#define ENGINE_METHOD_ALL (unsigned int)0xFFFF
Definition at line 53 of file engine.h.
ENGINE_METHOD_CIPHERS
#define ENGINE_METHOD_CIPHERS (unsigned int)0x0040
Definition at line 47 of file engine.h.
Referenced by ENGINE_set_default().
ENGINE_METHOD_DH
#define ENGINE_METHOD_DH (unsigned int)0x0004
Definition at line 45 of file engine.h.
Referenced by ENGINE_set_default().
ENGINE_METHOD_DIGESTS
#define ENGINE_METHOD_DIGESTS (unsigned int)0x0080
Definition at line 48 of file engine.h.
Referenced by ENGINE_set_default().
ENGINE_METHOD_DSA
#define ENGINE_METHOD_DSA (unsigned int)0x0002
Definition at line 44 of file engine.h.
Referenced by ENGINE_set_default().
ENGINE_METHOD_EC
#define ENGINE_METHOD_EC (unsigned int)0x0800
Definition at line 51 of file engine.h.
Referenced by ENGINE_set_default().
ENGINE_METHOD_NONE
#define ENGINE_METHOD_NONE (unsigned int)0x0000
Definition at line 54 of file engine.h.
ENGINE_METHOD_PKEY_ASN1_METHS
#define ENGINE_METHOD_PKEY_ASN1_METHS (unsigned int)0x0400
Definition at line 50 of file engine.h.
Referenced by ENGINE_set_default().
ENGINE_METHOD_PKEY_METHS
#define ENGINE_METHOD_PKEY_METHS (unsigned int)0x0200
Definition at line 49 of file engine.h.
Referenced by ENGINE_set_default().
ENGINE_METHOD_RAND
#define ENGINE_METHOD_RAND (unsigned int)0x0008
Definition at line 46 of file engine.h.
Referenced by ENGINE_set_default().
ENGINE_METHOD_RSA
#define ENGINE_METHOD_RSA (unsigned int)0x0001
Definition at line 43 of file engine.h.
Referenced by ENGINE_set_default().
ENGINE_R_ALREADY_LOADED
#define ENGINE_R_ALREADY_LOADED 100
Definition at line 800 of file engine.h.
ENGINE_R_ARGUMENT_IS_NOT_A_NUMBER
#define ENGINE_R_ARGUMENT_IS_NOT_A_NUMBER 133
Definition at line 801 of file engine.h.
ENGINE_R_CMD_NOT_EXECUTABLE
#define ENGINE_R_CMD_NOT_EXECUTABLE 134
Definition at line 802 of file engine.h.
ENGINE_R_COMMAND_TAKES_INPUT
#define ENGINE_R_COMMAND_TAKES_INPUT 135
Definition at line 803 of file engine.h.
ENGINE_R_COMMAND_TAKES_NO_INPUT
#define ENGINE_R_COMMAND_TAKES_NO_INPUT 136
Definition at line 804 of file engine.h.
ENGINE_R_CONFLICTING_ENGINE_ID
#define ENGINE_R_CONFLICTING_ENGINE_ID 103
Definition at line 805 of file engine.h.
ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED
#define ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED 119
Definition at line 806 of file engine.h.
ENGINE_R_DSO_FAILURE
#define ENGINE_R_DSO_FAILURE 104
Definition at line 807 of file engine.h.
ENGINE_R_DSO_NOT_FOUND
#define ENGINE_R_DSO_NOT_FOUND 132
Definition at line 808 of file engine.h.
ENGINE_R_ENGINE_CONFIGURATION_ERROR
#define ENGINE_R_ENGINE_CONFIGURATION_ERROR 102
Definition at line 810 of file engine.h.
ENGINE_R_ENGINE_IS_NOT_IN_LIST
#define ENGINE_R_ENGINE_IS_NOT_IN_LIST 105
Definition at line 811 of file engine.h.
ENGINE_R_ENGINE_SECTION_ERROR
#define ENGINE_R_ENGINE_SECTION_ERROR 149
Definition at line 812 of file engine.h.
ENGINE_R_ENGINES_SECTION_ERROR
#define ENGINE_R_ENGINES_SECTION_ERROR 148
Definition at line 809 of file engine.h.
ENGINE_R_FAILED_LOADING_PRIVATE_KEY
#define ENGINE_R_FAILED_LOADING_PRIVATE_KEY 128
Definition at line 813 of file engine.h.
ENGINE_R_FAILED_LOADING_PUBLIC_KEY
#define ENGINE_R_FAILED_LOADING_PUBLIC_KEY 129
Definition at line 814 of file engine.h.
ENGINE_R_FINISH_FAILED
#define ENGINE_R_FINISH_FAILED 106
Definition at line 815 of file engine.h.
Referenced by ENGINE_finish(), and engine_unlocked_finish().
ENGINE_R_ID_OR_NAME_MISSING
#define ENGINE_R_ID_OR_NAME_MISSING 108
Definition at line 816 of file engine.h.
Referenced by ENGINE_add().
ENGINE_R_INIT_FAILED
#define ENGINE_R_INIT_FAILED 109
Definition at line 817 of file engine.h.
ENGINE_R_INTERNAL_LIST_ERROR
#define ENGINE_R_INTERNAL_LIST_ERROR 110
Definition at line 818 of file engine.h.
ENGINE_R_INVALID_ARGUMENT
#define ENGINE_R_INVALID_ARGUMENT 143
Definition at line 819 of file engine.h.
ENGINE_R_INVALID_CMD_NAME
#define ENGINE_R_INVALID_CMD_NAME 137
Definition at line 820 of file engine.h.
Referenced by ENGINE_ctrl_cmd().
ENGINE_R_INVALID_CMD_NUMBER
#define ENGINE_R_INVALID_CMD_NUMBER 138
Definition at line 821 of file engine.h.
Referenced by ENGINE_cmd_is_executable().
ENGINE_R_INVALID_INIT_VALUE
#define ENGINE_R_INVALID_INIT_VALUE 151
Definition at line 822 of file engine.h.
ENGINE_R_INVALID_STRING
#define ENGINE_R_INVALID_STRING 150
Definition at line 823 of file engine.h.
ENGINE_R_NO_CONTROL_FUNCTION
#define ENGINE_R_NO_CONTROL_FUNCTION 120
Definition at line 826 of file engine.h.
ENGINE_R_NO_INDEX
#define ENGINE_R_NO_INDEX 144
Definition at line 827 of file engine.h.
ENGINE_R_NO_LOAD_FUNCTION
#define ENGINE_R_NO_LOAD_FUNCTION 125
Definition at line 828 of file engine.h.
ENGINE_R_NO_REFERENCE
#define ENGINE_R_NO_REFERENCE 130
Definition at line 829 of file engine.h.
Referenced by ENGINE_ctrl().
ENGINE_R_NO_SUCH_ENGINE
#define ENGINE_R_NO_SUCH_ENGINE 116
Definition at line 830 of file engine.h.
ENGINE_R_NOT_INITIALISED
#define ENGINE_R_NOT_INITIALISED 117
Definition at line 824 of file engine.h.
ENGINE_R_NOT_LOADED
#define ENGINE_R_NOT_LOADED 112
Definition at line 825 of file engine.h.
ENGINE_R_UNIMPLEMENTED_CIPHER
#define ENGINE_R_UNIMPLEMENTED_CIPHER 146
Definition at line 831 of file engine.h.
ENGINE_R_UNIMPLEMENTED_DIGEST
#define ENGINE_R_UNIMPLEMENTED_DIGEST 147
Definition at line 832 of file engine.h.
ENGINE_R_UNIMPLEMENTED_PUBLIC_KEY_METHOD
#define ENGINE_R_UNIMPLEMENTED_PUBLIC_KEY_METHOD 101
Definition at line 833 of file engine.h.
ENGINE_R_VERSION_INCOMPATIBILITY
#define ENGINE_R_VERSION_INCOMPATIBILITY 145
Definition at line 834 of file engine.h.
ENGINE_TABLE_FLAG_NOINIT
#define ENGINE_TABLE_FLAG_NOINIT (unsigned int)0x0001
Definition at line 62 of file engine.h.
IMPLEMENT_DYNAMIC_BIND_FN
#define IMPLEMENT_DYNAMIC_BIND_FN (fn)
Value:
OPENSSL_EXPORT \
        int bind_engine(ENGINE *e, const char *id, const dynamic_fns *fns); \
        OPENSSL_EXPORT \
        int bind_engine(ENGINE *e, const char *id, const dynamic_fns *fns) { \
            if (ENGINE_get_static_state() == fns->static_state) goto skip_cbs; \
            CRYPTO_set_mem_functions(fns->mem_fns.malloc_fn, \
                                     fns->mem_fns.realloc_fn, \
                                     fns->mem_fns.free_fn); \
        skip_cbs: \
            if (!fn(e, id)) return 0; \
            return 1; }
Definition at line 720 of file engine.h.
IMPLEMENT_DYNAMIC_CHECK_FN
#define IMPLEMENT_DYNAMIC_CHECK_FN ()
Value:
OPENSSL_EXPORT unsigned long v_check(unsigned long v); \
        OPENSSL_EXPORT unsigned long v_check(unsigned long v) { \
                if (v >= OSSL_DYNAMIC_OLDEST) return OSSL_DYNAMIC_VERSION; \
                return 0; }
Definition at line 694 of file engine.h.
Referenced by bind_engine().
OSSL_DYNAMIC_OLDEST
#define OSSL_DYNAMIC_OLDEST (unsigned long)0x00030000
Definition at line 650 of file engine.h.
OSSL_DYNAMIC_VERSION
#define OSSL_DYNAMIC_VERSION (unsigned long)0x00030000
Definition at line 645 of file engine.h.
Typedef Documentation
dyn_MEM_free_fn
typedef void(* dyn_MEM_free_fn) (void *, const char *, int)
Definition at line 665 of file engine.h.
dyn_MEM_malloc_fn
typedef void*(* dyn_MEM_malloc_fn) (size_t, const char *, int)
Definition at line 663 of file engine.h.
dyn_MEM_realloc_fn
typedef void*(* dyn_MEM_realloc_fn) (void *, size_t, const char *, int)
Definition at line 664 of file engine.h.
dynamic_bind_engine
typedef int(* dynamic_bind_engine) (ENGINE *e, const char *id, const dynamic_fns *fns)
Definition at line 718 of file engine.h.
dynamic_v_check_fn
typedef unsigned long(* dynamic_v_check_fn) (unsigned long ossl_version)
Definition at line 693 of file engine.h.
ENGINE_CIPHERS_PTR
typedef int(* ENGINE_CIPHERS_PTR) (ENGINE *, const EVP_CIPHER **, const int **, int)
Definition at line 294 of file engine.h.
ENGINE_CTRL_FUNC_PTR
typedef int(* ENGINE_CTRL_FUNC_PTR) (ENGINE *, int, long, void *, void(*f)(void))
Definition at line 267 of file engine.h.
ENGINE_DIGESTS_PTR
typedef int(* ENGINE_DIGESTS_PTR) (ENGINE *, const EVP_MD **, const int **, int)
Definition at line 296 of file engine.h.
ENGINE_GEN_FUNC_PTR
typedef int(* ENGINE_GEN_FUNC_PTR) (void)
Definition at line 263 of file engine.h.
ENGINE_GEN_INT_FUNC_PTR
typedef int(* ENGINE_GEN_INT_FUNC_PTR) (ENGINE *)
Definition at line 265 of file engine.h.
ENGINE_LOAD_KEY_PTR
typedef EVP_PKEY*(* ENGINE_LOAD_KEY_PTR) (ENGINE *, const char *, UI_METHOD *ui_method, void *callback_data)
Definition at line 270 of file engine.h.
ENGINE_PKEY_ASN1_METHS_PTR
typedef int(* ENGINE_PKEY_ASN1_METHS_PTR) (ENGINE *, EVP_PKEY_ASN1_METHOD **, const int **, int)
Definition at line 300 of file engine.h.
ENGINE_PKEY_METHS_PTR
typedef int(* ENGINE_PKEY_METHS_PTR) (ENGINE *, EVP_PKEY_METHOD **, const int **, int)
Definition at line 298 of file engine.h.
ENGINE_SSL_CLIENT_CERT_PTR
typedef int(* ENGINE_SSL_CLIENT_CERT_PTR) (ENGINE *, SSL *ssl, STACK_OF(X509_NAME) *ca_dn, X509 **pcert, EVP_PKEY **pkey, STACK_OF(X509) **pother, UI_METHOD *ui_method, void *callback_data)
Definition at line 273 of file engine.h.
Function Documentation
ENGINE_add()
int ENGINE_add (ENGINE * e)
Definition at line 215 of file eng_list.c.
References CRYPTO_THREAD_write_lock(), ENGINE_F_ENGINE_ADD, ENGINE_R_ID_OR_NAME_MISSING, ENGINEerr, ERR_R_PASSED_NULL_PARAMETER, global_engine_lock, and NULL.
ENGINE_add_conf_module()
void ENGINE_add_conf_module (void)
Definition at line 188 of file eng_cnf.c.
References CONF_module_add().
Referenced by OPENSSL_load_builtin_modules().
ENGINE_by_id()
ENGINE* ENGINE_by_id (const char * id)
Definition at line 282 of file eng_list.c.
References CRYPTO_THREAD_write_lock(), ENGINE_F_ENGINE_BY_ID, engine_lock_init, ENGINEerr, ERR_R_MALLOC_FAILURE, ERR_R_PASSED_NULL_PARAMETER, global_engine_lock, NULL, and RUN_ONCE.
ENGINE_cmd_is_executable()
int ENGINE_cmd_is_executable (ENGINE * e, int cmd)
Definition at line 185 of file eng_ctrl.c.
References ENGINE_CMD_FLAG_NO_INPUT, ENGINE_CMD_FLAG_NUMERIC, ENGINE_CMD_FLAG_STRING, ENGINE_ctrl(), ENGINE_CTRL_GET_CMD_FLAGS, ENGINE_F_ENGINE_CMD_IS_EXECUTABLE, ENGINE_R_INVALID_CMD_NUMBER, ENGINEerr, flags, and NULL.
ENGINE_ctrl()
int ENGINE_ctrl (ENGINE * e, int cmd, long i, void * p, void(*)(void) f)
Definition at line 133 of file eng_ctrl.c.
References CRYPTO_THREAD_unlock(), CRYPTO_THREAD_write_lock(), ENGINE_CTRL_GET_CMD_FLAGS, ENGINE_CTRL_GET_CMD_FROM_NAME, ENGINE_CTRL_GET_DESC_FROM_CMD, ENGINE_CTRL_GET_DESC_LEN_FROM_CMD, ENGINE_CTRL_GET_FIRST_CMD_TYPE, ENGINE_CTRL_GET_NAME_FROM_CMD, ENGINE_CTRL_GET_NAME_LEN_FROM_CMD, ENGINE_CTRL_GET_NEXT_CMD_TYPE, ENGINE_CTRL_HAS_CTRL_FUNCTION, ENGINE_F_ENGINE_CTRL, ENGINE_FLAGS_MANUAL_CMD_CTRL, ENGINE_R_NO_REFERENCE, ENGINEerr, ERR_R_PASSED_NULL_PARAMETER, global_engine_lock, and NULL.
Referenced by ENGINE_cmd_is_executable(), and ENGINE_ctrl_cmd().
ENGINE_ctrl_cmd()
int ENGINE_ctrl_cmd (ENGINE * e, const char * cmd_name, long i, void * p, void(*)(void) f, int cmd_optional)
Definition at line 201 of file eng_ctrl.c.
References ENGINE_ctrl(), ENGINE_CTRL_GET_CMD_FROM_NAME, ENGINE_F_ENGINE_CTRL_CMD, ENGINE_R_INVALID_CMD_NAME, ENGINEerr, ERR_clear_error(), ERR_R_PASSED_NULL_PARAMETER, and NULL.
ENGINE_ctrl_cmd_string()
int ENGINE_ctrl_cmd_string (ENGINE * e, const char * cmd_name, const char * arg, int cmd_optional)
Definition at line 237 of file eng_ctrl.c.
ENGINE_finish()
int ENGINE_finish (ENGINE * e)
Definition at line 94 of file eng_init.c.
References CRYPTO_THREAD_unlock(), CRYPTO_THREAD_write_lock(), ENGINE_F_ENGINE_FINISH, ENGINE_R_FINISH_FAILED, engine_unlocked_finish(), ENGINEerr, global_engine_lock, and NULL.
Referenced by DH_free(), DH_set_method(), DSA_free(), DSA_set_method(), EC_KEY_copy(), EC_KEY_free(), EC_KEY_set_method(), EVP_DigestInit_ex(), EVP_MD_CTX_reset(), EVP_PKEY_CTX_free(), RAND_set_rand_engine(), RAND_set_rand_method(), RSA_free(), RSA_set_method(), and SSL_CTX_set_client_cert_engine().
ENGINE_free()
int ENGINE_free (ENGINE * e)
Definition at line 102 of file eng_lib.c.
References engine_free_util().
Referenced by EVP_PKEY_asn1_find_str(), and release_engine().
ENGINE_get_cipher()
const EVP_CIPHER* ENGINE_get_cipher (ENGINE * e, int nid)
Definition at line 69 of file tb_cipher.c.
ENGINE_get_cipher_engine()
ENGINE* ENGINE_get_cipher_engine (int nid)
Definition at line 63 of file tb_cipher.c.
References engine_table_select().
ENGINE_get_ciphers()
ENGINE_CIPHERS_PTR ENGINE_get_ciphers (const ENGINE * e)
Definition at line 81 of file tb_cipher.c.
ENGINE_get_cmd_defns()
const ENGINE_CMD_DEFN* ENGINE_get_cmd_defns (const ENGINE * e)
Definition at line 285 of file eng_lib.c.
ENGINE_get_ctrl_function()
ENGINE_CTRL_FUNC_PTR ENGINE_get_ctrl_function (const ENGINE * e)
Definition at line 275 of file eng_lib.c.
ENGINE_get_default_DH()
ENGINE* ENGINE_get_default_DH (void)
Definition at line 56 of file tb_dh.c.
References engine_table_select().
ENGINE_get_default_DSA()
ENGINE* ENGINE_get_default_DSA (void)
Definition at line 56 of file tb_dsa.c.
References engine_table_select().
ENGINE_get_default_EC()
ENGINE* ENGINE_get_default_EC (void)
Definition at line 56 of file tb_eckey.c.
References engine_table_select().
ENGINE_get_default_RAND()
ENGINE* ENGINE_get_default_RAND (void)
Definition at line 56 of file tb_rand.c.
References engine_table_select().
ENGINE_get_default_RSA()
ENGINE* ENGINE_get_default_RSA (void)
Definition at line 56 of file tb_rsa.c.
References engine_table_select().
ENGINE_get_destroy_function()
ENGINE_GEN_INT_FUNC_PTR ENGINE_get_destroy_function (const ENGINE * e)
Definition at line 260 of file eng_lib.c.
ENGINE_get_DH()
const DH_METHOD* ENGINE_get_DH (const ENGINE * e)
Definition at line 62 of file tb_dh.c.
ENGINE_get_digest()
const EVP_MD* ENGINE_get_digest (ENGINE * e, int nid)
Definition at line 69 of file tb_digest.c.
Referenced by EVP_DigestInit_ex().
ENGINE_get_digest_engine()
ENGINE* ENGINE_get_digest_engine (int nid)
Definition at line 63 of file tb_digest.c.
References engine_table_select().
Referenced by EVP_DigestInit_ex().
ENGINE_get_digests()
ENGINE_DIGESTS_PTR ENGINE_get_digests (const ENGINE * e)
Definition at line 81 of file tb_digest.c.
ENGINE_get_DSA()
const DSA_METHOD* ENGINE_get_DSA (const ENGINE * e)
Definition at line 62 of file tb_dsa.c.
ENGINE_get_EC()
const EC_KEY_METHOD* ENGINE_get_EC (const ENGINE * e)
Definition at line 62 of file tb_eckey.c.
ENGINE_get_ex_data()
void* ENGINE_get_ex_data (const ENGINE * e, int idx)
Definition at line 184 of file eng_lib.c.
ENGINE_get_finish_function()
ENGINE_GEN_INT_FUNC_PTR ENGINE_get_finish_function (const ENGINE * e)
Definition at line 270 of file eng_lib.c.
ENGINE_get_first()
ENGINE* ENGINE_get_first (void)
Definition at line 135 of file eng_list.c.
Referenced by ENGINE_register_all_ciphers(), ENGINE_register_all_complete(), ENGINE_register_all_DH(), ENGINE_register_all_digests(), ENGINE_register_all_DSA(), ENGINE_register_all_EC(), ENGINE_register_all_pkey_asn1_meths(), ENGINE_register_all_pkey_meths(), ENGINE_register_all_RAND(), and ENGINE_register_all_RSA().
ENGINE_get_flags()
int ENGINE_get_flags (const ENGINE * e)
Definition at line 280 of file eng_lib.c.
ENGINE_get_id()
const char* ENGINE_get_id (const ENGINE * e)
Definition at line 250 of file eng_lib.c.
ENGINE_get_init_function()
ENGINE_GEN_INT_FUNC_PTR ENGINE_get_init_function (const ENGINE * e)
Definition at line 265 of file eng_lib.c.
ENGINE_get_last()
ENGINE* ENGINE_get_last (void)
Definition at line 154 of file eng_list.c.
ENGINE_get_load_privkey_function()
ENGINE_LOAD_KEY_PTR ENGINE_get_load_privkey_function (const ENGINE * e)
Definition at line 35 of file eng_pkey.c.
ENGINE_get_load_pubkey_function()
ENGINE_LOAD_KEY_PTR ENGINE_get_load_pubkey_function (const ENGINE * e)
Definition at line 40 of file eng_pkey.c.
ENGINE_get_name()
const char* ENGINE_get_name (const ENGINE * e)
Definition at line 255 of file eng_lib.c.
ENGINE_get_next()
ENGINE* ENGINE_get_next (ENGINE * e)
Definition at line 174 of file eng_list.c.
Referenced by ENGINE_register_all_ciphers(), ENGINE_register_all_complete(), ENGINE_register_all_DH(), ENGINE_register_all_digests(), ENGINE_register_all_DSA(), ENGINE_register_all_EC(), ENGINE_register_all_pkey_asn1_meths(), ENGINE_register_all_pkey_meths(), ENGINE_register_all_RAND(), and ENGINE_register_all_RSA().
ENGINE_get_pkey_asn1_meth()
const EVP_PKEY_ASN1_METHOD* ENGINE_get_pkey_asn1_meth (ENGINE * e, int nid)
Definition at line 82 of file tb_asnmth.c.
ENGINE_get_pkey_asn1_meth_engine()
ENGINE* ENGINE_get_pkey_asn1_meth_engine (int nid)
Definition at line 73 of file tb_asnmth.c.
References engine_table_select().
ENGINE_get_pkey_asn1_meth_str()
const EVP_PKEY_ASN1_METHOD* ENGINE_get_pkey_asn1_meth_str (ENGINE * e, const char * str, int len)
Definition at line 135 of file tb_asnmth.c.
References NULL.
ENGINE_get_pkey_asn1_meths()
ENGINE_PKEY_ASN1_METHS_PTR ENGINE_get_pkey_asn1_meths (const ENGINE * e)
Definition at line 95 of file tb_asnmth.c.
ENGINE_get_pkey_meth()
const EVP_PKEY_METHOD* ENGINE_get_pkey_meth (ENGINE * e, int nid)
Definition at line 70 of file tb_pkmeth.c.
ENGINE_get_pkey_meth_engine()
ENGINE* ENGINE_get_pkey_meth_engine (int nid)
Definition at line 64 of file tb_pkmeth.c.
References engine_table_select().
ENGINE_get_pkey_meths()
ENGINE_PKEY_METHS_PTR ENGINE_get_pkey_meths (const ENGINE * e)
Definition at line 83 of file tb_pkmeth.c.
ENGINE_get_prev()
ENGINE* ENGINE_get_prev (ENGINE * e)
Definition at line 194 of file eng_list.c.
ENGINE_get_RAND()
const RAND_METHOD* ENGINE_get_RAND (const ENGINE * e)
Definition at line 62 of file tb_rand.c.
Referenced by RAND_set_rand_engine().
ENGINE_get_RSA()
const RSA_METHOD* ENGINE_get_RSA (const ENGINE * e)
Definition at line 62 of file tb_rsa.c.
ENGINE_get_ssl_client_cert_function()
ENGINE_SSL_CLIENT_CERT_PTR ENGINE_get_ssl_client_cert_function (const ENGINE * e)
Definition at line 45 of file eng_pkey.c.
Referenced by SSL_CTX_set_client_cert_engine().
ENGINE_get_static_state()
void* ENGINE_get_static_state (void)
Definition at line 297 of file eng_lib.c.
ENGINE_get_table_flags()
unsigned int ENGINE_get_table_flags (void)
Definition at line 43 of file eng_table.c.
ENGINE_init()
int ENGINE_init (ENGINE * e)
Definition at line 76 of file eng_init.c.
Referenced by EC_KEY_copy(), EVP_DigestInit_ex(), EVP_PKEY_asn1_find_str(), load_key(), RAND_set_rand_engine(), and SSL_CTX_set_client_cert_engine().
ENGINE_load_builtin_engines()
void ENGINE_load_builtin_engines (void)
Definition at line 13 of file eng_all.c.
References ENGINE_register_all_complete(), NULL, OPENSSL_cpuid_setup(), OPENSSL_init_crypto(), OPENSSL_INIT_ENGINE_ALL_BUILTIN, and OPENSSL_INIT_ENGINE_CRYPTODEV.
ENGINE_load_private_key()
EVP_PKEY* ENGINE_load_private_key (ENGINE * e, const char * key_id, UI_METHOD * ui_method, void * callback_data)
Definition at line 53 of file eng_pkey.c.
Referenced by load_key().
ENGINE_load_public_key()
EVP_PKEY* ENGINE_load_public_key (ENGINE * e, const char * key_id, UI_METHOD * ui_method, void * callback_data)
Definition at line 84 of file eng_pkey.c.
Referenced by load_pubkey().
ENGINE_load_ssl_client_cert()
int ENGINE_load_ssl_client_cert (ENGINE * e, SSL * s, STACK_OF(X509_NAME) * ca_dn, X509 ** pcert, EVP_PKEY ** ppkey, STACK_OF(X509) ** pother, UI_METHOD * ui_method, void * callback_data)
Definition at line 114 of file eng_pkey.c.
Referenced by ssl_do_client_cert_cb().
ENGINE_new()
ENGINE* ENGINE_new (void)
Definition at line 27 of file eng_lib.c.
ENGINE_pkey_asn1_find_str()
const EVP_PKEY_ASN1_METHOD* ENGINE_pkey_asn1_find_str (ENGINE ** pe, const char * str, int len)
Definition at line 182 of file tb_asnmth.c.
References ENGINE_FIND_STR::ameth, CRYPTO_THREAD_write_lock(), ENGINE_FIND_STR::e, ENGINE_F_ENGINE_PKEY_ASN1_FIND_STR, engine_lock_init, engine_table_doall(), ENGINEerr, ERR_R_MALLOC_FAILURE, global_engine_lock, ENGINE_FIND_STR::len, len, NULL, RUN_ONCE, and ENGINE_FIND_STR::str.
Referenced by EVP_PKEY_asn1_find_str().
ENGINE_register_all_ciphers()
void ENGINE_register_all_ciphers (void)
Definition at line 37 of file tb_cipher.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_ciphers().
ENGINE_register_all_complete()
int ENGINE_register_all_complete (void)
Definition at line 119 of file eng_fat.c.
References e, ENGINE_FLAGS_NO_REGISTER_ALL, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_complete().
Referenced by ENGINE_load_builtin_engines().
ENGINE_register_all_DH()
void ENGINE_register_all_DH (void)
Definition at line 34 of file tb_dh.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_DH().
ENGINE_register_all_digests()
void ENGINE_register_all_digests (void)
Definition at line 37 of file tb_digest.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_digests().
ENGINE_register_all_DSA()
void ENGINE_register_all_DSA (void)
Definition at line 34 of file tb_dsa.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_DSA().
ENGINE_register_all_EC()
void ENGINE_register_all_EC (void)
Definition at line 34 of file tb_eckey.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_EC().
ENGINE_register_all_pkey_asn1_meths()
void ENGINE_register_all_pkey_asn1_meths (void)
Definition at line 47 of file tb_asnmth.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_pkey_asn1_meths().
ENGINE_register_all_pkey_meths()
void ENGINE_register_all_pkey_meths (void)
Definition at line 38 of file tb_pkmeth.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_pkey_meths().
ENGINE_register_all_RAND()
void ENGINE_register_all_RAND (void)
Definition at line 34 of file tb_rand.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_RAND().
ENGINE_register_all_RSA()
void ENGINE_register_all_RSA (void)
Definition at line 34 of file tb_rsa.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_RSA().
ENGINE_register_ciphers()
int ENGINE_register_ciphers (ENGINE * e)
Definition at line 24 of file tb_cipher.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_register_all_ciphers(), and ENGINE_register_complete().
ENGINE_register_complete()
int ENGINE_register_complete (ENGINE * e)
Definition at line 98 of file eng_fat.c.
References ENGINE_register_ciphers(), ENGINE_register_DH(), ENGINE_register_digests(), ENGINE_register_DSA(), ENGINE_register_EC(), ENGINE_register_pkey_meths(), ENGINE_register_RAND(), and ENGINE_register_RSA().
Referenced by ENGINE_register_all_complete().
ENGINE_register_DH()
int ENGINE_register_DH (ENGINE * e)
Definition at line 25 of file tb_dh.c.
References engine_table_register().
Referenced by ENGINE_register_all_DH(), and ENGINE_register_complete().
ENGINE_register_digests()
int ENGINE_register_digests (ENGINE * e)
Definition at line 24 of file tb_digest.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_register_all_digests(), and ENGINE_register_complete().
ENGINE_register_DSA()
int ENGINE_register_DSA (ENGINE * e)
Definition at line 25 of file tb_dsa.c.
References engine_table_register().
Referenced by ENGINE_register_all_DSA(), and ENGINE_register_complete().
ENGINE_register_EC()
int ENGINE_register_EC (ENGINE * e)
Definition at line 25 of file tb_eckey.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_register_all_EC(), and ENGINE_register_complete().
ENGINE_register_pkey_asn1_meths()
int ENGINE_register_pkey_asn1_meths (ENGINE * e)
Definition at line 34 of file tb_asnmth.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_register_all_pkey_asn1_meths().
ENGINE_register_pkey_meths()
int ENGINE_register_pkey_meths (ENGINE * e)
Definition at line 25 of file tb_pkmeth.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_register_all_pkey_meths(), and ENGINE_register_complete().
ENGINE_register_RAND()
int ENGINE_register_RAND (ENGINE * e)
Definition at line 25 of file tb_rand.c.
References engine_table_register().
Referenced by ENGINE_register_all_RAND(), and ENGINE_register_complete().
ENGINE_register_RSA()
int ENGINE_register_RSA (ENGINE * e)
Definition at line 25 of file tb_rsa.c.
References engine_table_register().
Referenced by ENGINE_register_all_RSA(), and ENGINE_register_complete().
ENGINE_remove()
int ENGINE_remove (ENGINE * e)
Definition at line 236 of file eng_list.c.
References CRYPTO_THREAD_write_lock(), ENGINE_F_ENGINE_REMOVE, ENGINEerr, ERR_R_PASSED_NULL_PARAMETER, global_engine_lock, and NULL.
ENGINE_set_ciphers()
int ENGINE_set_ciphers (ENGINE * e, ENGINE_CIPHERS_PTR f)
Definition at line 87 of file tb_cipher.c.
ENGINE_set_cmd_defns()
int ENGINE_set_cmd_defns (ENGINE * e, const ENGINE_CMD_DEFN * defns)
Definition at line 244 of file eng_lib.c.
ENGINE_set_ctrl_function()
int ENGINE_set_ctrl_function (ENGINE * e, ENGINE_CTRL_FUNC_PTR ctrl_f)
Definition at line 232 of file eng_lib.c.
ENGINE_set_default()
int ENGINE_set_default (ENGINE * e, unsigned int flags)
Definition at line 19 of file eng_fat.c.
References ENGINE_METHOD_CIPHERS, ENGINE_METHOD_DH, ENGINE_METHOD_DIGESTS, ENGINE_METHOD_DSA, ENGINE_METHOD_EC, ENGINE_METHOD_PKEY_ASN1_METHS, ENGINE_METHOD_PKEY_METHS, ENGINE_METHOD_RAND, ENGINE_METHOD_RSA, ENGINE_set_default_ciphers(), ENGINE_set_default_DH(), ENGINE_set_default_digests(), ENGINE_set_default_DSA(), ENGINE_set_default_EC(), ENGINE_set_default_pkey_asn1_meths(), ENGINE_set_default_pkey_meths(), ENGINE_set_default_RAND(), and ENGINE_set_default_RSA().
ENGINE_set_default_ciphers()
int ENGINE_set_default_ciphers (ENGINE * e)
Definition at line 45 of file tb_cipher.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_set_default().
ENGINE_set_default_DH()
int ENGINE_set_default_DH (ENGINE * e)
Definition at line 42 of file tb_dh.c.
References engine_table_register().
Referenced by ENGINE_set_default().
ENGINE_set_default_digests()
int ENGINE_set_default_digests (ENGINE * e)
Definition at line 45 of file tb_digest.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_set_default().
ENGINE_set_default_DSA()
int ENGINE_set_default_DSA (ENGINE * e)
Definition at line 42 of file tb_dsa.c.
References engine_table_register().
Referenced by ENGINE_set_default().
ENGINE_set_default_EC()
int ENGINE_set_default_EC (ENGINE * e)
Definition at line 42 of file tb_eckey.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_set_default().
ENGINE_set_default_pkey_asn1_meths()
int ENGINE_set_default_pkey_asn1_meths (ENGINE * e)
Definition at line 55 of file tb_asnmth.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_set_default().
ENGINE_set_default_pkey_meths()
int ENGINE_set_default_pkey_meths (ENGINE * e)
Definition at line 46 of file tb_pkmeth.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_set_default().
ENGINE_set_default_RAND()
int ENGINE_set_default_RAND (ENGINE * e)
Definition at line 42 of file tb_rand.c.
References engine_table_register().
Referenced by ENGINE_set_default().
ENGINE_set_default_RSA()
int ENGINE_set_default_RSA (ENGINE * e)
Definition at line 42 of file tb_rsa.c.
References engine_table_register().
Referenced by ENGINE_set_default().
ENGINE_set_default_string()
int ENGINE_set_default_string (ENGINE * e, const char * def_list)
Definition at line 86 of file eng_fat.c.
References CONF_parse_list(), and flags.
ENGINE_set_destroy_function()
int ENGINE_set_destroy_function (ENGINE * e, ENGINE_GEN_INT_FUNC_PTR destroy_f)
Definition at line 214 of file eng_lib.c.
ENGINE_set_DH()
int ENGINE_set_DH (ENGINE * e, const DH_METHOD * dh_meth)
Definition at line 68 of file tb_dh.c.
ENGINE_set_digests()
int ENGINE_set_digests (ENGINE * e, ENGINE_DIGESTS_PTR f)
Definition at line 87 of file tb_digest.c.
ENGINE_set_DSA()
int ENGINE_set_DSA (ENGINE * e, const DSA_METHOD * dsa_meth)
Definition at line 68 of file tb_dsa.c.
ENGINE_set_EC()
int ENGINE_set_EC (ENGINE * e, const EC_KEY_METHOD * ecdsa_meth)
Definition at line 68 of file tb_eckey.c.
ENGINE_set_ex_data()
int ENGINE_set_ex_data (ENGINE * e, int idx, void * arg)
Definition at line 179 of file eng_lib.c.
ENGINE_set_finish_function()
int ENGINE_set_finish_function (ENGINE * e, ENGINE_GEN_INT_FUNC_PTR finish_f)
Definition at line 226 of file eng_lib.c.
ENGINE_set_flags()
int ENGINE_set_flags (ENGINE * e, int flags)
Definition at line 238 of file eng_lib.c.
References flags.
ENGINE_set_id()
int ENGINE_set_id (ENGINE * e, const char * id)
Definition at line 194 of file eng_lib.c.
References ENGINE_F_ENGINE_SET_ID, ENGINEerr, ERR_R_PASSED_NULL_PARAMETER, and NULL.
ENGINE_set_init_function()
int ENGINE_set_init_function (ENGINE * e, ENGINE_GEN_INT_FUNC_PTR init_f)
Definition at line 220 of file eng_lib.c.
ENGINE_set_load_privkey_function()
int ENGINE_set_load_privkey_function (ENGINE * e, ENGINE_LOAD_KEY_PTR loadpriv_f)
Definition at line 14 of file eng_pkey.c.
ENGINE_set_load_pubkey_function()
int ENGINE_set_load_pubkey_function (ENGINE * e, ENGINE_LOAD_KEY_PTR loadpub_f)
Definition at line 21 of file eng_pkey.c.
ENGINE_set_load_ssl_client_cert_function()
int ENGINE_set_load_ssl_client_cert_function (ENGINE * e, ENGINE_SSL_CLIENT_CERT_PTR loadssl_f)
Definition at line 27 of file eng_pkey.c.
ENGINE_set_name()
int ENGINE_set_name (ENGINE * e, const char * name)
Definition at line 204 of file eng_lib.c.
References ENGINE_F_ENGINE_SET_NAME, ENGINEerr, ERR_R_PASSED_NULL_PARAMETER, and NULL.
ENGINE_set_pkey_asn1_meths()
int ENGINE_set_pkey_asn1_meths (ENGINE * e, ENGINE_PKEY_ASN1_METHS_PTR f)
Definition at line 101 of file tb_asnmth.c.
ENGINE_set_pkey_meths()
int ENGINE_set_pkey_meths (ENGINE * e, ENGINE_PKEY_METHS_PTR f)
Definition at line 89 of file tb_pkmeth.c.
ENGINE_set_RAND()
int ENGINE_set_RAND (ENGINE * e, const RAND_METHOD * rand_meth)
Definition at line 68 of file tb_rand.c.
ENGINE_set_RSA()
int ENGINE_set_RSA (ENGINE * e, const RSA_METHOD * rsa_meth)
Definition at line 68 of file tb_rsa.c.
ENGINE_set_table_flags()
void ENGINE_set_table_flags (unsigned int flags)
Definition at line 48 of file eng_table.c.
ENGINE_unregister_ciphers()
void ENGINE_unregister_ciphers (ENGINE * e)
Definition at line 14 of file tb_cipher.c.
References engine_table_unregister().
ENGINE_unregister_DH()
void ENGINE_unregister_DH (ENGINE * e)
Definition at line 15 of file tb_dh.c.
References engine_table_unregister().
ENGINE_unregister_digests()
void ENGINE_unregister_digests (ENGINE * e)
Definition at line 14 of file tb_digest.c.
References engine_table_unregister().
ENGINE_unregister_DSA()
void ENGINE_unregister_DSA (ENGINE * e)
Definition at line 15 of file tb_dsa.c.
References engine_table_unregister().
ENGINE_unregister_EC()
void ENGINE_unregister_EC (ENGINE * e)
Definition at line 15 of file tb_eckey.c.
References engine_table_unregister().
ENGINE_unregister_pkey_asn1_meths()
void ENGINE_unregister_pkey_asn1_meths (ENGINE * e)
Definition at line 24 of file tb_asnmth.c.
References engine_table_unregister().
ENGINE_unregister_pkey_meths()
void ENGINE_unregister_pkey_meths (ENGINE * e)
Definition at line 15 of file tb_pkmeth.c.
References engine_table_unregister().
ENGINE_unregister_RAND()
void ENGINE_unregister_RAND (ENGINE * e)
Definition at line 15 of file tb_rand.c.
References engine_table_unregister().
ENGINE_unregister_RSA()
void ENGINE_unregister_RSA (ENGINE * e)
Definition at line 15 of file tb_rsa.c.
References engine_table_unregister().
ENGINE_up_ref()
int ENGINE_up_ref (ENGINE * e)
Definition at line 345 of file eng_list.c.
References CRYPTO_UP_REF, ENGINE_F_ENGINE_UP_REF, ENGINEerr, ERR_R_PASSED_NULL_PARAMETER, global_engine_lock, and NULL.
ERR_load_ENGINE_strings()
int ERR_load_ENGINE_strings (void)
Definition at line 113 of file eng_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().