crypto/init.c File Reference
init.c File Reference
#include <internal/cryptlib_int.h>
#include <openssl/err.h>
#include <internal/rand.h>
#include <internal/bio.h>
#include <openssl/evp.h>
#include <internal/evp_int.h>
#include <internal/conf.h>
#include <internal/async.h>
#include <internal/engine.h>
#include <internal/comp.h>
#include <internal/err.h>
#include <internal/err_int.h>
#include <internal/objects.h>
#include <stdlib.h>
#include <assert.h>
#include <internal/thread_once.h>
#include <internal/dso.h>
Data Structures
struct OPENSSL_INIT_STOP
Functions
DEFINE_RUN_ONCE_STATIC (ossl_init_base)
DEFINE_RUN_ONCE_STATIC (ossl_init_no_load_crypto_strings)
DEFINE_RUN_ONCE_STATIC (ossl_init_load_crypto_strings)
DEFINE_RUN_ONCE_STATIC (ossl_init_add_all_ciphers)
DEFINE_RUN_ONCE_STATIC (ossl_init_add_all_digests)
DEFINE_RUN_ONCE_STATIC (ossl_init_no_add_algs)
DEFINE_RUN_ONCE_STATIC (ossl_init_config)
DEFINE_RUN_ONCE_STATIC (ossl_init_no_config)
DEFINE_RUN_ONCE_STATIC (ossl_init_async)
DEFINE_RUN_ONCE_STATIC (ossl_init_engine_openssl)
DEFINE_RUN_ONCE_STATIC (ossl_init_engine_rdrand)
DEFINE_RUN_ONCE_STATIC (ossl_init_engine_dynamic)
DEFINE_RUN_ONCE_STATIC (ossl_init_engine_padlock)
DEFINE_RUN_ONCE_STATIC (ossl_init_engine_afalg)
DEFINE_RUN_ONCE_STATIC (ossl_init_zlib)
void OPENSSL_thread_stop (void)
int ossl_init_thread_start (uint64_t opts)
void OPENSSL_cleanup (void)
int OPENSSL_init_crypto (uint64_t opts, const OPENSSL_INIT_SETTINGS *settings)
int OPENSSL_atexit (void(*handler)(void))
Function Documentation
DEFINE_RUN_ONCE_STATIC() [1/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_base)
Definition at line 66 of file init.c.
References CRYPTO_THREAD_init_local(), and ossl_malloc_setup_failures().
Referenced by DEFINE_RUN_ONCE_STATIC().
DEFINE_RUN_ONCE_STATIC() [2/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_no_load_crypto_strings)
Definition at line 126 of file init.c.
DEFINE_RUN_ONCE_STATIC() [3/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_load_crypto_strings)
Definition at line 132 of file init.c.
DEFINE_RUN_ONCE_STATIC() [4/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_add_all_ciphers)
Definition at line 151 of file init.c.
References openssl_add_all_ciphers_int().
DEFINE_RUN_ONCE_STATIC() [5/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_add_all_digests)
Definition at line 168 of file init.c.
References openssl_add_all_digests_int().
DEFINE_RUN_ONCE_STATIC() [6/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_no_add_algs)
Definition at line 184 of file init.c.
DEFINE_RUN_ONCE_STATIC() [7/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_config)
Definition at line 193 of file init.c.
References NULL, and openssl_config_int().
DEFINE_RUN_ONCE_STATIC() [8/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_no_config)
Definition at line 204 of file init.c.
References openssl_no_config_int().
DEFINE_RUN_ONCE_STATIC() [9/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_async)
Definition at line 217 of file init.c.
References async_init().
DEFINE_RUN_ONCE_STATIC() [10/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_engine_openssl)
Definition at line 230 of file init.c.
References CRYPTO_ONCE_STATIC_INIT, DEFINE_RUN_ONCE_STATIC(), engine_load_cryptodev_int(), and engine_load_openssl_int().
DEFINE_RUN_ONCE_STATIC() [11/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_engine_rdrand)
Definition at line 255 of file init.c.
References engine_load_rdrand_int().
DEFINE_RUN_ONCE_STATIC() [12/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_engine_dynamic)
Definition at line 266 of file init.c.
References engine_load_dynamic_int().
DEFINE_RUN_ONCE_STATIC() [13/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_engine_padlock)
Definition at line 278 of file init.c.
References CRYPTO_ONCE_STATIC_INIT, DEFINE_RUN_ONCE_STATIC(), engine_load_capi_int(), and engine_load_padlock_int().
DEFINE_RUN_ONCE_STATIC() [14/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_engine_afalg)
Definition at line 302 of file init.c.
References engine_load_afalg_int().
DEFINE_RUN_ONCE_STATIC() [15/15]
DEFINE_RUN_ONCE_STATIC (ossl_init_zlib)
Definition at line 319 of file init.c.
OPENSSL_atexit()
int OPENSSL_atexit (void(*)(void) handler)
Definition at line 613 of file init.c.
References OPENSSL_INIT_STOP::handler, and NULL.
Referenced by DEFINE_RUN_ONCE_STATIC().
OPENSSL_cleanup()
void OPENSSL_cleanup (void)
Definition at line 384 of file init.c.
Referenced by CRYPTO_mem_leaks().
OPENSSL_init_crypto()
int OPENSSL_init_crypto (uint64_t opts, const OPENSSL_INIT_SETTINGS * settings)
Definition at line 499 of file init.c.
Referenced by async_get_ctx(), ASYNC_init_thread(), DEFINE_RUN_ONCE(), DEFINE_RUN_ONCE_STATIC(), ENGINE_load_builtin_engines(), EVP_CIPHER_do_all(), EVP_CIPHER_do_all_sorted(), EVP_get_cipherbyname(), and EVP_get_digestbyname().
OPENSSL_thread_stop()
void OPENSSL_thread_stop (void)
Definition at line 352 of file init.c.
ossl_init_thread_start()
int ossl_init_thread_start (uint64_t opts)
Definition at line 358 of file init.c.
Referenced by ASYNC_init_thread().