include/internal/bio.h File Reference
bio.h File Reference
#include <openssl/bio.h>
Data Structures
struct BIO_METHOD
Functions
void bio_free_ex_data (BIO *bio)
void bio_cleanup (void)
int bwrite_conv (BIO *bio, const char *data, size_t datal, size_t *written)
int bread_conv (BIO *bio, char *data, size_t datal, size_t *read)
Function Documentation
bio_cleanup()
void bio_cleanup (void)
Definition at line 777 of file bio_lib.c.
References bio_lookup_lock, bio_sock_cleanup_int(), bio_type_lock, CRYPTO_THREAD_lock_free(), and NULL.
bio_free_ex_data()
void bio_free_ex_data (BIO * bio)
Definition at line 772 of file bio_lib.c.
References CRYPTO_EX_INDEX_BIO, and CRYPTO_free_ex_data().
Referenced by CRYPTO_mem_leaks().
bread_conv()
int bread_conv (BIO * bio, char * data, size_t datal, size_t * read)
Definition at line 110 of file bio_meth.c.
Referenced by BIO_meth_set_read(), and comp_zlib_cleanup_int().
bwrite_conv()
int bwrite_conv (BIO * bio, const char * data, size_t datal, size_t * written)
Definition at line 64 of file bio_meth.c.
Referenced by BIO_meth_set_write(), and comp_zlib_cleanup_int().