include/internal/comp.h File Reference
comp.h File Reference
#include <openssl/comp.h>
Functions
void comp_zlib_cleanup_int (void)
Function Documentation
comp_zlib_cleanup_int()
void comp_zlib_cleanup_int (void)
Definition at line 262 of file c_zlib.c.
References BIO_get_data(), BIO_set_data(), BIO_set_init(), BIO_TYPE_COMP, bread_conv(), bwrite_conv(), COMP_F_BIO_ZLIB_NEW, COMP_R_ZLIB_NOT_SUPPORTED, COMP_zlib(), COMPerr, ctx, DSO_free(), ERR_R_MALLOC_FAILURE, fp, NULL, OPENSSL_free, OPENSSL_zalloc, and ptr.