include/openssl/kdf.h File Reference
kdf.h File Reference
Macros
#define EVP_PKEY_CTRL_TLS_MD (EVP_PKEY_ALG_CTRL)
#define EVP_PKEY_CTRL_TLS_SECRET (EVP_PKEY_ALG_CTRL + 1)
#define EVP_PKEY_CTRL_TLS_SEED (EVP_PKEY_ALG_CTRL + 2)
#define EVP_PKEY_CTRL_HKDF_MD (EVP_PKEY_ALG_CTRL + 3)
#define EVP_PKEY_CTRL_HKDF_SALT (EVP_PKEY_ALG_CTRL + 4)
#define EVP_PKEY_CTRL_HKDF_KEY (EVP_PKEY_ALG_CTRL + 5)
#define EVP_PKEY_CTRL_HKDF_INFO (EVP_PKEY_ALG_CTRL + 6)
#define EVP_PKEY_CTRL_HKDF_MODE (EVP_PKEY_ALG_CTRL + 7)
#define EVP_PKEY_HKDEF_MODE_EXTRACT_AND_EXPAND 0
#define EVP_PKEY_HKDEF_MODE_EXTRACT_ONLY 1
#define EVP_PKEY_HKDEF_MODE_EXPAND_ONLY 2
#define EVP_PKEY_CTX_set_tls1_prf_md(pctx, md)
#define EVP_PKEY_CTX_set1_tls1_prf_secret(pctx, sec, seclen)
#define EVP_PKEY_CTX_add1_tls1_prf_seed(pctx, seed, seedlen)
#define EVP_PKEY_CTX_set_hkdf_md(pctx, md)
#define EVP_PKEY_CTX_set1_hkdf_salt(pctx, salt, saltlen)
#define EVP_PKEY_CTX_set1_hkdf_key(pctx, key, keylen)
#define EVP_PKEY_CTX_add1_hkdf_info(pctx, info, infolen)
#define EVP_PKEY_CTX_hkdf_mode(pctx, mode)
#define KDF_F_PKEY_TLS1_PRF_CTRL_STR 100
#define KDF_F_PKEY_TLS1_PRF_DERIVE 101
#define KDF_R_INVALID_DIGEST 100
#define KDF_R_MISSING_PARAMETER 101
#define KDF_R_VALUE_MISSING 102
Functions
int ERR_load_KDF_strings (void)
Macro Definition Documentation
EVP_PKEY_CTRL_HKDF_INFO
#define EVP_PKEY_CTRL_HKDF_INFO (EVP_PKEY_ALG_CTRL + 6)
Definition at line 23 of file kdf.h.
EVP_PKEY_CTRL_HKDF_KEY
#define EVP_PKEY_CTRL_HKDF_KEY (EVP_PKEY_ALG_CTRL + 5)
Definition at line 22 of file kdf.h.
EVP_PKEY_CTRL_HKDF_MD
#define EVP_PKEY_CTRL_HKDF_MD (EVP_PKEY_ALG_CTRL + 3)
Definition at line 20 of file kdf.h.
EVP_PKEY_CTRL_HKDF_MODE
#define EVP_PKEY_CTRL_HKDF_MODE (EVP_PKEY_ALG_CTRL + 7)
Definition at line 24 of file kdf.h.
EVP_PKEY_CTRL_HKDF_SALT
#define EVP_PKEY_CTRL_HKDF_SALT (EVP_PKEY_ALG_CTRL + 4)
Definition at line 21 of file kdf.h.
EVP_PKEY_CTRL_TLS_MD
#define EVP_PKEY_CTRL_TLS_MD (EVP_PKEY_ALG_CTRL)
Definition at line 17 of file kdf.h.
EVP_PKEY_CTRL_TLS_SECRET
#define EVP_PKEY_CTRL_TLS_SECRET (EVP_PKEY_ALG_CTRL + 1)
Definition at line 18 of file kdf.h.
EVP_PKEY_CTRL_TLS_SEED
#define EVP_PKEY_CTRL_TLS_SEED (EVP_PKEY_ALG_CTRL + 2)
Definition at line 19 of file kdf.h.
EVP_PKEY_CTX_add1_hkdf_info
#define EVP_PKEY_CTX_add1_hkdf_info (pctx, info, infolen)
Value:
EVP_PKEY_CTX_ctrl(pctx, -1, EVP_PKEY_OP_DERIVE, \
                              EVP_PKEY_CTRL_HKDF_INFO, infolen, (void *)info)
Definition at line 54 of file kdf.h.
EVP_PKEY_CTX_add1_tls1_prf_seed
#define EVP_PKEY_CTX_add1_tls1_prf_seed (pctx, seed, seedlen)
Value:
EVP_PKEY_CTX_ctrl(pctx, -1, EVP_PKEY_OP_DERIVE, \
                              EVP_PKEY_CTRL_TLS_SEED, seedlen, (void *)seed)
Definition at line 38 of file kdf.h.
EVP_PKEY_CTX_hkdf_mode
#define EVP_PKEY_CTX_hkdf_mode (pctx, mode)
Value:
EVP_PKEY_CTX_ctrl(pctx, -1, EVP_PKEY_OP_DERIVE, \
                              EVP_PKEY_CTRL_HKDF_MODE, mode, NULL)
Definition at line 58 of file kdf.h.
EVP_PKEY_CTX_set1_hkdf_key
#define EVP_PKEY_CTX_set1_hkdf_key (pctx, key, keylen)
Value:
EVP_PKEY_CTX_ctrl(pctx, -1, EVP_PKEY_OP_DERIVE, \
                              EVP_PKEY_CTRL_HKDF_KEY, keylen, (void *)key)
Definition at line 50 of file kdf.h.
EVP_PKEY_CTX_set1_hkdf_salt
#define EVP_PKEY_CTX_set1_hkdf_salt (pctx, salt, saltlen)
Value:
EVP_PKEY_CTX_ctrl(pctx, -1, EVP_PKEY_OP_DERIVE, \
                              EVP_PKEY_CTRL_HKDF_SALT, saltlen, (void *)salt)
Definition at line 46 of file kdf.h.
EVP_PKEY_CTX_set1_tls1_prf_secret
#define EVP_PKEY_CTX_set1_tls1_prf_secret (pctx, sec, seclen)
Value:
EVP_PKEY_CTX_ctrl(pctx, -1, EVP_PKEY_OP_DERIVE, \
                              EVP_PKEY_CTRL_TLS_SECRET, seclen, (void *)sec)
Definition at line 34 of file kdf.h.
EVP_PKEY_CTX_set_hkdf_md
#define EVP_PKEY_CTX_set_hkdf_md (pctx, md)
Value:
EVP_PKEY_CTX_ctrl(pctx, -1, EVP_PKEY_OP_DERIVE, \
                              EVP_PKEY_CTRL_HKDF_MD, 0, (void *)md)
Definition at line 42 of file kdf.h.
EVP_PKEY_CTX_set_tls1_prf_md
#define EVP_PKEY_CTX_set_tls1_prf_md (pctx, md)
Value:
EVP_PKEY_CTX_ctrl(pctx, -1, EVP_PKEY_OP_DERIVE, \
                              EVP_PKEY_CTRL_TLS_MD, 0, (void *)md)
Definition at line 30 of file kdf.h.
EVP_PKEY_HKDEF_MODE_EXPAND_ONLY
#define EVP_PKEY_HKDEF_MODE_EXPAND_ONLY 2
Definition at line 28 of file kdf.h.
EVP_PKEY_HKDEF_MODE_EXTRACT_AND_EXPAND
#define EVP_PKEY_HKDEF_MODE_EXTRACT_AND_EXPAND 0
Definition at line 26 of file kdf.h.
EVP_PKEY_HKDEF_MODE_EXTRACT_ONLY
#define EVP_PKEY_HKDEF_MODE_EXTRACT_ONLY 1
Definition at line 27 of file kdf.h.
KDF_F_PKEY_TLS1_PRF_CTRL_STR
#define KDF_F_PKEY_TLS1_PRF_CTRL_STR 100
Definition at line 73 of file kdf.h.
KDF_F_PKEY_TLS1_PRF_DERIVE
#define KDF_F_PKEY_TLS1_PRF_DERIVE 101
Definition at line 74 of file kdf.h.
KDF_R_INVALID_DIGEST
#define KDF_R_INVALID_DIGEST 100
Definition at line 77 of file kdf.h.
KDF_R_MISSING_PARAMETER
#define KDF_R_MISSING_PARAMETER 101
Definition at line 78 of file kdf.h.
KDF_R_VALUE_MISSING
#define KDF_R_VALUE_MISSING 102
Definition at line 79 of file kdf.h.
Function Documentation
ERR_load_KDF_strings()
int ERR_load_KDF_strings (void)
Definition at line 36 of file kdf_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().