include/openssl/lhash.h File Reference
lhash.h File Reference
#include <openssl/e_os2.h>
#include <openssl/bio.h>
Macros
#define DECLARE_LHASH_HASH_FN(name, o_type) unsigned long name##_LHASH_HASH(const void *);
#define IMPLEMENT_LHASH_HASH_FN(name, o_type)
#define LHASH_HASH_FN(name) name##_LHASH_HASH
#define DECLARE_LHASH_COMP_FN(name, o_type) int name##_LHASH_COMP(const void *, const void *);
#define IMPLEMENT_LHASH_COMP_FN(name, o_type)
#define LHASH_COMP_FN(name) name##_LHASH_COMP
#define DECLARE_LHASH_DOALL_ARG_FN(name, o_type, a_type) void name##_LHASH_DOALL_ARG(void *, void *);
#define IMPLEMENT_LHASH_DOALL_ARG_FN(name, o_type, a_type)
#define LHASH_DOALL_ARG_FN(name) name##_LHASH_DOALL_ARG
#define LH_LOAD_MULT 256
#define _LHASH OPENSSL_LHASH
#define LHASH_NODE OPENSSL_LH_NODE
#define lh_error OPENSSL_LH_error
#define lh_new OPENSSL_lh_new
#define lh_free OPENSSL_LH_free
#define lh_insert OPENSSL_LH_insert
#define lh_delete OPENSSL_LH_delete
#define lh_retrieve OPENSSL_LH_retrieve
#define lh_doall OPENSSL_LH_doall
#define lh_doall_arg OPENSSL_LH_doall_arg
#define lh_strhash OPENSSL_LH_strhash
#define lh_num_items OPENSSL_LH_num_items
#define lh_stats OPENSSL_LH_stats
#define lh_node_stats OPENSSL_LH_node_stats
#define lh_node_usage_stats OPENSSL_LH_node_usage_stats
#define lh_stats_bio OPENSSL_LH_stats_bio
#define lh_node_stats_bio OPENSSL_LH_node_stats_bio
#define lh_node_usage_stats_bio OPENSSL_LH_node_usage_stats_bio
#define LHASH_OF(type) struct lhash_st_##type
#define DEFINE_LHASH_OF(type)
#define IMPLEMENT_LHASH_DOALL_ARG_CONST(type, argtype) int_implement_lhash_doall(type, argtype, const type)
#define IMPLEMENT_LHASH_DOALL_ARG(type, argtype) int_implement_lhash_doall(type, argtype, type)
#define int_implement_lhash_doall(type, argtype, cbargtype)
Typedefs
typedef int(* OPENSSL_LH_COMPFUNC) (const void *, const void *)
typedef unsigned long(* OPENSSL_LH_HASHFUNC) (const void *)
typedef void(* OPENSSL_LH_DOALL_FUNC) (void *)
typedef void(* OPENSSL_LH_DOALL_FUNCARG) (void *, void *)
Functions
int OPENSSL_LH_error (OPENSSL_LHASH *lh)
OPENSSL_LHASH * OPENSSL_LH_new (OPENSSL_LH_HASHFUNC h, OPENSSL_LH_COMPFUNC c)
void OPENSSL_LH_free (OPENSSL_LHASH *lh)
void * OPENSSL_LH_insert (OPENSSL_LHASH *lh, void *data)
void * OPENSSL_LH_delete (OPENSSL_LHASH *lh, const void *data)
void * OPENSSL_LH_retrieve (OPENSSL_LHASH *lh, const void *data)
void OPENSSL_LH_doall (OPENSSL_LHASH *lh, OPENSSL_LH_DOALL_FUNC func)
void OPENSSL_LH_doall_arg (OPENSSL_LHASH *lh, OPENSSL_LH_DOALL_FUNCARG func, void *arg)
unsigned long OPENSSL_LH_strhash (const char *c)
unsigned long OPENSSL_LH_num_items (const OPENSSL_LHASH *lh)
unsigned long OPENSSL_LH_get_down_load (const OPENSSL_LHASH *lh)
void OPENSSL_LH_set_down_load (OPENSSL_LHASH *lh, unsigned long down_load)
void OPENSSL_LH_stats (const OPENSSL_LHASH *lh, FILE *fp)
void OPENSSL_LH_node_stats (const OPENSSL_LHASH *lh, FILE *fp)
void OPENSSL_LH_node_usage_stats (const OPENSSL_LHASH *lh, FILE *fp)
void OPENSSL_LH_stats_bio (const OPENSSL_LHASH *lh, BIO *out)
void OPENSSL_LH_node_stats_bio (const OPENSSL_LHASH *lh, BIO *out)
void OPENSSL_LH_node_usage_stats_bio (const OPENSSL_LHASH *lh, BIO *out)
DEFINE_LHASH_OF (OPENSSL_STRING)
DEFINE_LHASH_OF (OPENSSL_CSTRING)
Macro Definition Documentation
_LHASH
#define _LHASH OPENSSL_LHASH
Definition at line 95 of file lhash.h.
DECLARE_LHASH_COMP_FN
#define DECLARE_LHASH_COMP_FN (name, o_type) int name##_LHASH_COMP(const void *, const void *);
Definition at line 50 of file lhash.h.
DECLARE_LHASH_DOALL_ARG_FN
#define DECLARE_LHASH_DOALL_ARG_FN (name, o_type, a_type) void name##_LHASH_DOALL_ARG(void *, void *);
Definition at line 60 of file lhash.h.
DECLARE_LHASH_HASH_FN
#define DECLARE_LHASH_HASH_FN (name, o_type) unsigned long name##_LHASH_HASH(const void *);
Definition at line 41 of file lhash.h.
DEFINE_LHASH_OF
#define DEFINE_LHASH_OF (type)
Definition at line 121 of file lhash.h.
IMPLEMENT_LHASH_COMP_FN
#define IMPLEMENT_LHASH_COMP_FN (name, o_type)
Value:
int name##_LHASH_COMP(const void *arg1, const void *arg2) { \
                const o_type *a = arg1;             \
                const o_type *b = arg2; \
                return name##_cmp(a,b); }
Definition at line 52 of file lhash.h.
Referenced by index_name_cmp().
IMPLEMENT_LHASH_DOALL_ARG
#define IMPLEMENT_LHASH_DOALL_ARG (type, argtype) int_implement_lhash_doall(type, argtype, type)
Definition at line 184 of file lhash.h.
IMPLEMENT_LHASH_DOALL_ARG_CONST
#define IMPLEMENT_LHASH_DOALL_ARG_CONST (type, argtype) int_implement_lhash_doall(type, argtype, const type)
Definition at line 181 of file lhash.h.
IMPLEMENT_LHASH_DOALL_ARG_FN
#define IMPLEMENT_LHASH_DOALL_ARG_FN (name, o_type, a_type)
Value:
void name##_LHASH_DOALL_ARG(void *arg1, void *arg2) { \
                o_type *a = arg1; \
                a_type *b = arg2; \
                name##_doall_arg(a, b); }
Definition at line 62 of file lhash.h.
IMPLEMENT_LHASH_HASH_FN
#define IMPLEMENT_LHASH_HASH_FN (name, o_type)
Value:
unsigned long name##_LHASH_HASH(const void *arg) { \
                const o_type *a = arg; \
                return name##_hash(a); }
Definition at line 43 of file lhash.h.
Referenced by index_name_cmp().
int_implement_lhash_doall
#define int_implement_lhash_doall (type, argtype, cbargtype)
Value:
static ossl_inline void \
        lh_##type##_doall_##argtype(LHASH_OF(type) *lh, \
                                   void (*fn)(cbargtype *, argtype *), \
                                   argtype *arg) \
    { \
        OPENSSL_LH_doall_arg((OPENSSL_LHASH *)lh, (OPENSSL_LH_DOALL_FUNCARG)fn, (void *)arg); \
    } \
    LHASH_OF(type)
Definition at line 187 of file lhash.h.
lh_delete
#define lh_delete OPENSSL_LH_delete
Definition at line 101 of file lhash.h.
lh_doall
#define lh_doall OPENSSL_LH_doall
Definition at line 103 of file lhash.h.
lh_doall_arg
#define lh_doall_arg OPENSSL_LH_doall_arg
Definition at line 104 of file lhash.h.
lh_error
#define lh_error OPENSSL_LH_error
Definition at line 97 of file lhash.h.
lh_free
#define lh_free OPENSSL_LH_free
Definition at line 99 of file lhash.h.
lh_insert
#define lh_insert OPENSSL_LH_insert
Definition at line 100 of file lhash.h.
LH_LOAD_MULT
#define LH_LOAD_MULT 256
Definition at line 70 of file lhash.h.
lh_new
#define lh_new OPENSSL_lh_new
Definition at line 98 of file lhash.h.
lh_node_stats
#define lh_node_stats OPENSSL_LH_node_stats
Definition at line 109 of file lhash.h.
lh_node_stats_bio
#define lh_node_stats_bio OPENSSL_LH_node_stats_bio
Definition at line 113 of file lhash.h.
lh_node_usage_stats
#define lh_node_usage_stats OPENSSL_LH_node_usage_stats
Definition at line 110 of file lhash.h.
lh_node_usage_stats_bio
#define lh_node_usage_stats_bio OPENSSL_LH_node_usage_stats_bio
Definition at line 114 of file lhash.h.
lh_num_items
#define lh_num_items OPENSSL_LH_num_items
Definition at line 106 of file lhash.h.
lh_retrieve
#define lh_retrieve OPENSSL_LH_retrieve
Definition at line 102 of file lhash.h.
lh_stats
#define lh_stats OPENSSL_LH_stats
Definition at line 108 of file lhash.h.
lh_stats_bio
#define lh_stats_bio OPENSSL_LH_stats_bio
Definition at line 112 of file lhash.h.
lh_strhash
#define lh_strhash OPENSSL_LH_strhash
Definition at line 105 of file lhash.h.
LHASH_COMP_FN
#define LHASH_COMP_FN (name) name##_LHASH_COMP
Definition at line 57 of file lhash.h.
Referenced by index_index().
LHASH_DOALL_ARG_FN
#define LHASH_DOALL_ARG_FN (name) name##_LHASH_DOALL_ARG
Definition at line 67 of file lhash.h.
LHASH_HASH_FN
#define LHASH_HASH_FN (name) name##_LHASH_HASH
Definition at line 47 of file lhash.h.
Referenced by index_index().
LHASH_NODE
#define LHASH_NODE OPENSSL_LH_NODE
Definition at line 96 of file lhash.h.
LHASH_OF
#define LHASH_OF (type) struct lhash_st_##type
Definition at line 119 of file lhash.h.
Referenced by TXT_DB_create_index().
Typedef Documentation
OPENSSL_LH_COMPFUNC
typedef int(* OPENSSL_LH_COMPFUNC) (const void *, const void *)
Definition at line 25 of file lhash.h.
OPENSSL_LH_DOALL_FUNC
typedef void(* OPENSSL_LH_DOALL_FUNC) (void *)
Definition at line 27 of file lhash.h.
OPENSSL_LH_DOALL_FUNCARG
typedef void(* OPENSSL_LH_DOALL_FUNCARG) (void *, void *)
Definition at line 28 of file lhash.h.
OPENSSL_LH_HASHFUNC
typedef unsigned long(* OPENSSL_LH_HASHFUNC) (const void *)
Definition at line 26 of file lhash.h.
Function Documentation
DEFINE_LHASH_OF() [1/2]
DEFINE_LHASH_OF (OPENSSL_STRING)
DEFINE_LHASH_OF() [2/2]
DEFINE_LHASH_OF (OPENSSL_CSTRING)
OPENSSL_LH_delete()
void* OPENSSL_LH_delete (OPENSSL_LHASH * lh, const void * data)
Definition at line 103 of file lhash.c.
OPENSSL_LH_doall()
void OPENSSL_LH_doall (OPENSSL_LHASH * lh, OPENSSL_LH_DOALL_FUNC func)
Definition at line 177 of file lhash.c.
OPENSSL_LH_doall_arg()
void OPENSSL_LH_doall_arg (OPENSSL_LHASH * lh, OPENSSL_LH_DOALL_FUNCARG func, void * arg)
Definition at line 182 of file lhash.c.
OPENSSL_LH_error()
int OPENSSL_LH_error (OPENSSL_LHASH * lh)
Definition at line 346 of file lhash.c.
OPENSSL_LH_free()
void OPENSSL_LH_free (OPENSSL_LHASH * lh)
Definition at line 50 of file lhash.c.
References NULL, and OPENSSL_free.
OPENSSL_LH_get_down_load()
unsigned long OPENSSL_LH_get_down_load (const OPENSSL_LHASH * lh)
Definition at line 336 of file lhash.c.
OPENSSL_LH_insert()
void* OPENSSL_LH_insert (OPENSSL_LHASH * lh, void * data)
Definition at line 70 of file lhash.c.
OPENSSL_LH_new()
OPENSSL_LHASH* OPENSSL_LH_new (OPENSSL_LH_HASHFUNC h, OPENSSL_LH_COMPFUNC c)
Definition at line 27 of file lhash.c.
OPENSSL_LH_node_stats()
void OPENSSL_LH_node_stats (const OPENSSL_LHASH * lh, FILE * fp)
Definition at line 36 of file lh_stats.c.
References BIO_free(), BIO_new(), BIO_NOCLOSE, BIO_s_file(), BIO_set_fp, bp, NULL, and OPENSSL_LH_node_stats_bio().
OPENSSL_LH_node_stats_bio()
void OPENSSL_LH_node_stats_bio (const OPENSSL_LHASH * lh, BIO * out)
Definition at line 83 of file lh_stats.c.
Referenced by OPENSSL_LH_node_stats().
OPENSSL_LH_node_usage_stats()
void OPENSSL_LH_node_usage_stats (const OPENSSL_LHASH * lh, FILE * fp)
Definition at line 48 of file lh_stats.c.
References BIO_free(), BIO_new(), BIO_NOCLOSE, BIO_s_file(), BIO_set_fp, bp, NULL, and OPENSSL_LH_node_usage_stats_bio().
OPENSSL_LH_node_usage_stats_bio()
void OPENSSL_LH_node_usage_stats_bio (const OPENSSL_LHASH * lh, BIO * out)
Definition at line 95 of file lh_stats.c.
Referenced by OPENSSL_LH_node_usage_stats().
OPENSSL_LH_num_items()
unsigned long OPENSSL_LH_num_items (const OPENSSL_LHASH * lh)
Definition at line 331 of file lhash.c.
OPENSSL_LH_retrieve()
void* OPENSSL_LH_retrieve (OPENSSL_LHASH * lh, const void * data)
Definition at line 131 of file lhash.c.
OPENSSL_LH_set_down_load()
void OPENSSL_LH_set_down_load (OPENSSL_LHASH * lh, unsigned long down_load)
Definition at line 341 of file lhash.c.
OPENSSL_LH_stats()
void OPENSSL_LH_stats (const OPENSSL_LHASH * lh, FILE * fp)
Definition at line 24 of file lh_stats.c.
References BIO_free(), BIO_new(), BIO_NOCLOSE, BIO_s_file(), BIO_set_fp, bp, NULL, and OPENSSL_LH_stats_bio().
OPENSSL_LH_stats_bio()
void OPENSSL_LH_stats_bio (const OPENSSL_LHASH * lh, BIO * out)
Definition at line 62 of file lh_stats.c.
Referenced by OPENSSL_LH_stats().
OPENSSL_LH_strhash()
unsigned long OPENSSL_LH_strhash (const char * c)
Definition at line 303 of file lhash.c.