crypto/evp/m_sigver.c File Reference
m_sigver.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/evp.h>
#include <openssl/objects.h>
#include <openssl/x509.h>
#include "internal/evp_int.h"
#include "evp_locl.h"
Functions
int EVP_DigestSignInit (EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx, const EVP_MD *type, ENGINE *e, EVP_PKEY *pkey)
int EVP_DigestVerifyInit (EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx, const EVP_MD *type, ENGINE *e, EVP_PKEY *pkey)
int EVP_DigestSignFinal (EVP_MD_CTX *ctx, unsigned char *sigret, size_t *siglen)
int EVP_DigestVerifyFinal (EVP_MD_CTX *ctx, const unsigned char *sig, size_t siglen)
Function Documentation
EVP_DigestSignFinal()
int EVP_DigestSignFinal (EVP_MD_CTX * ctx, unsigned char * sigret, size_t * siglen)
Definition at line 79 of file m_sigver.c.
References EVP_MD_CTX_FLAG_FINALISE, EVP_PKEY_CTX_dup(), EVP_PKEY_CTX_free(), and EVP_PKEY_FLAG_SIGCTX_CUSTOM.
Referenced by ASN1_item_sign_ctx().
EVP_DigestSignInit()
int EVP_DigestSignInit (EVP_MD_CTX * ctx, EVP_PKEY_CTX ** pctx, const EVP_MD * type, ENGINE * e, EVP_PKEY * pkey)
Definition at line 67 of file m_sigver.c.
Referenced by ASN1_item_sign().
EVP_DigestVerifyFinal()
int EVP_DigestVerifyFinal (EVP_MD_CTX * ctx, const unsigned char * sig, size_t siglen)
Definition at line 138 of file m_sigver.c.
EVP_DigestVerifyInit()
int EVP_DigestVerifyInit (EVP_MD_CTX * ctx, EVP_PKEY_CTX ** pctx, const EVP_MD * type, ENGINE * e, EVP_PKEY * pkey)
Definition at line 73 of file m_sigver.c.