crypto/mem_sec.c File Reference
mem_sec.c File Reference
#include <openssl/crypto.h>
#include <e_os.h>
#include <string.h>
Macros
#define CLEAR(p, s) OPENSSL_cleanse(p, s)
#define PAGE_SIZE 4096
Functions
int CRYPTO_secure_malloc_init (size_t size, int minsize)
int CRYPTO_secure_malloc_done ()
int CRYPTO_secure_malloc_initialized ()
void * CRYPTO_secure_malloc (size_t num, const char *file, int line)
void * CRYPTO_secure_zalloc (size_t num, const char *file, int line)
void CRYPTO_secure_free (void *ptr, const char *file, int line)
int CRYPTO_secure_allocated (const void *ptr)
size_t CRYPTO_secure_used ()
size_t CRYPTO_secure_actual_size (void *ptr)
Macro Definition Documentation
CLEAR
#define CLEAR (p, s) OPENSSL_cleanse(p, s)
Definition at line 39 of file mem_sec.c.
Referenced by CRYPTO_secure_free().
PAGE_SIZE
#define PAGE_SIZE 4096
Definition at line 41 of file mem_sec.c.
Function Documentation
CRYPTO_secure_actual_size()
size_t CRYPTO_secure_actual_size (void * ptr)
Definition at line 179 of file mem_sec.c.
References CRYPTO_THREAD_unlock(), CRYPTO_THREAD_write_lock(), OPENSSL_assert, ossl_ssize_t, and ptr.
CRYPTO_secure_allocated()
int CRYPTO_secure_allocated (const void * ptr)
Definition at line 154 of file mem_sec.c.
Referenced by CRYPTO_secure_free().
CRYPTO_secure_free()
void CRYPTO_secure_free (void * ptr, const char * file, int line)
Definition at line 132 of file mem_sec.c.
References CLEAR, CRYPTO_free(), CRYPTO_secure_allocated(), CRYPTO_THREAD_unlock(), CRYPTO_THREAD_write_lock(), and NULL.
CRYPTO_secure_malloc()
void* CRYPTO_secure_malloc (size_t num, const char * file, int line)
Definition at line 103 of file mem_sec.c.
CRYPTO_secure_malloc_done()
int CRYPTO_secure_malloc_done (void)
Definition at line 81 of file mem_sec.c.
References CRYPTO_THREAD_lock_free().
CRYPTO_secure_malloc_init()
int CRYPTO_secure_malloc_init (size_t size, int minsize)
Definition at line 62 of file mem_sec.c.
CRYPTO_secure_malloc_initialized()
int CRYPTO_secure_malloc_initialized (void)
Definition at line 94 of file mem_sec.c.
CRYPTO_secure_used()
size_t CRYPTO_secure_used (void)
Definition at line 170 of file mem_sec.c.
CRYPTO_secure_zalloc()
void* CRYPTO_secure_zalloc (size_t num, const char * file, int line)
Definition at line 123 of file mem_sec.c.