crypto/mem_clr.c File Reference
mem_clr.c File Reference
#include <string.h>
#include <openssl/crypto.h>
Typedefs
typedef void *(* memset_t) (void *, int, size_t)
Functions
void OPENSSL_cleanse (void *ptr, size_t len)
Typedef Documentation
memset_t
typedef void*(* memset_t) (void *, int, size_t)
Definition at line 18 of file mem_clr.c.
Function Documentation
OPENSSL_cleanse()
void OPENSSL_cleanse (void * ptr, size_t len)
Definition at line 22 of file mem_clr.c.
Referenced by ASN1_STRING_clear_free(), BN_clear(), BN_clear_free(), CMAC_CTX_cleanup(), CRYPTO_clear_free(), CRYPTO_ocb128_cleanup(), DES_string_to_key(), EVP_MD_CTX_reset(), PKCS12_item_i2d_encrypt(), SRP_Calc_A_param(), SSL_SESSION_free(), and SSL_srp_server_param_with_username().