crypto/mem.c File Reference
mem.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <openssl/crypto.h>
#include "internal/cryptlib.h"
#include "internal/cryptlib_int.h"
#include <execinfo.h>
Macros
#define FAILTEST() if (shouldfail()) return NULL
Functions
int CRYPTO_set_mem_functions (void *(*m)(size_t, const char *, int), void *(*r)(void *, size_t, const char *, int), void(*f)(void *, const char *, int))
int CRYPTO_set_mem_debug (int flag)
void CRYPTO_get_mem_functions (void *(**m)(size_t, const char *, int), void *(**r)(void *, size_t, const char *, int), void(**f)(void *, const char *, int))
void ossl_malloc_setup_failures (void)
void * CRYPTO_malloc (size_t num, const char *file, int line)
void * CRYPTO_zalloc (size_t num, const char *file, int line)
void * CRYPTO_realloc (void *str, size_t num, const char *file, int line)
void * CRYPTO_clear_realloc (void *str, size_t old_len, size_t num, const char *file, int line)
void CRYPTO_free (void *str, const char *file, int line)
void CRYPTO_clear_free (void *str, size_t num, const char *file, int line)
Macro Definition Documentation
FAILTEST
#define FAILTEST () if (shouldfail()) return NULL
Definition at line 42 of file mem.c.
Function Documentation
CRYPTO_clear_free()
void CRYPTO_clear_free (void * str, size_t num, const char * file, int line)
Definition at line 273 of file mem.c.
References CRYPTO_free(), NULL, and OPENSSL_cleanse().
CRYPTO_clear_realloc()
void* CRYPTO_clear_realloc (void * str, size_t old_len, size_t num, const char * file, int line)
Definition at line 226 of file mem.c.
CRYPTO_free()
void CRYPTO_free (void * str, const char * file, int line)
Definition at line 253 of file mem.c.
Referenced by CRYPTO_clear_free(), and CRYPTO_secure_free().
CRYPTO_get_mem_functions()
void CRYPTO_get_mem_functions (void *(**)(size_t, const char *, int) m, void *(**)(void *, size_t, const char *, int) r, void(**)(void *, const char *, int) f)
Definition at line 74 of file mem.c.
References NULL.
CRYPTO_malloc()
void* CRYPTO_malloc (size_t num, const char * file, int line)
Definition at line 158 of file mem.c.
CRYPTO_realloc()
void* CRYPTO_realloc (void * str, size_t num, const char * file, int line)
Definition at line 196 of file mem.c.
CRYPTO_set_mem_debug()
int CRYPTO_set_mem_debug (int flag)
Definition at line 66 of file mem.c.
Referenced by main().
CRYPTO_set_mem_functions()
int CRYPTO_set_mem_functions (void *(*)(size_t, const char *, int) m, void *(*)(void *, size_t, const char *, int) r, void(*)(void *, const char *, int) f)
Definition at line 50 of file mem.c.
CRYPTO_zalloc()
void* CRYPTO_zalloc (size_t num, const char * file, int line)
Definition at line 186 of file mem.c.
ossl_malloc_setup_failures()
void ossl_malloc_setup_failures (void)
Definition at line 147 of file mem.c.
References NULL.
Referenced by DEFINE_RUN_ONCE_STATIC().