crypto/mem_dbg.c File Reference
mem_dbg.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "internal/cryptlib.h"
#include "internal/thread_once.h"
#include <openssl/crypto.h>
#include <openssl/buffer.h>
#include "internal/bio.h"
#include <openssl/lhash.h>
#include <execinfo.h>
Data Structures
struct APP_INFO
struct MEM
struct MEM_LEAK
Macros
#define BUF_REMAIN (sizeof buf - (size_t)(bufp - buf))
Functions
int CRYPTO_mem_ctrl (int mode)
int CRYPTO_mem_debug_push (const char *info, const char *file, int line)
int CRYPTO_mem_debug_pop (void)
void CRYPTO_mem_debug_malloc (void *addr, size_t num, int before_p, const char *file, int line)
void CRYPTO_mem_debug_free (void *addr, int before_p, const char *file, int line)
void CRYPTO_mem_debug_realloc (void *addr1, void *addr2, size_t num, int before_p, const char *file, int line)
IMPLEMENT_LHASH_DOALL_ARG_CONST (MEM, MEM_LEAK)
int CRYPTO_mem_leaks (BIO *b)
int CRYPTO_mem_leaks_fp (FILE *fp)
Macro Definition Documentation
BUF_REMAIN
#define BUF_REMAIN (sizeof buf - (size_t)(bufp - buf))
Function Documentation
CRYPTO_mem_ctrl()
int CRYPTO_mem_ctrl (int mode)
Definition at line 117 of file mem_dbg.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), main(), and SSL_COMP_add_compression_method().
CRYPTO_mem_debug_free()
void CRYPTO_mem_debug_free (void * addr, int before_p, const char * file, int line)
Definition at line 379 of file mem_dbg.c.
References NULL.
CRYPTO_mem_debug_malloc()
void CRYPTO_mem_debug_malloc (void * addr, size_t num, int before_p, const char * file, int line)
Definition at line 312 of file mem_dbg.c.
References NULL.
Referenced by CRYPTO_mem_debug_realloc().
CRYPTO_mem_debug_pop()
int CRYPTO_mem_debug_pop (void)
Definition at line 298 of file mem_dbg.c.
CRYPTO_mem_debug_push()
int CRYPTO_mem_debug_push (const char * info, const char * file, int line)
Definition at line 266 of file mem_dbg.c.
CRYPTO_mem_debug_realloc()
void CRYPTO_mem_debug_realloc (void * addr1, void * addr2, size_t num, int before_p, const char * file, int line)
Definition at line 407 of file mem_dbg.c.
References CRYPTO_mem_debug_malloc(), and NULL.
CRYPTO_mem_leaks()
int CRYPTO_mem_leaks (BIO * b)
Definition at line 544 of file mem_dbg.c.
References bio_free_ex_data(), ml, OPENSSL_cleanup(), and RUN_ONCE.
CRYPTO_mem_leaks_fp()
int CRYPTO_mem_leaks_fp (FILE * fp)
Definition at line 607 of file mem_dbg.c.
IMPLEMENT_LHASH_DOALL_ARG_CONST()
IMPLEMENT_LHASH_DOALL_ARG_CONST (MEM , MEM_LEAK)