ssl/methods.c File Reference
methods.c File Reference
#include <stdio.h>
#include <openssl/objects.h>
#include "ssl_locl.h"
Functions
IMPLEMENT_tls_meth_func (TLS_ANY_VERSION, IMPLEMENT_tls_meth_func(0, IMPLEMENT_tls_meth_func(0, TLS_method, IMPLEMENT_tls_meth_func(ossl_statem_accept, IMPLEMENT_tls_meth_func(ossl_statem_connect, TLSv1_2_enc_data)
const SSL_METHOD * TLSv1_2_server_method (void)
const SSL_METHOD * TLSv1_2_client_method (void)
const SSL_METHOD * TLSv1_1_method (void)
const SSL_METHOD * TLSv1_1_server_method (void)
const SSL_METHOD * TLSv1_1_client_method (void)
const SSL_METHOD * TLSv1_method (void)
const SSL_METHOD * TLSv1_server_method (void)
const SSL_METHOD * TLSv1_client_method (void)
const SSL_METHOD * SSLv3_method (void)
const SSL_METHOD * SSLv3_server_method (void)
const SSL_METHOD * SSLv3_client_method (void)
const SSL_METHOD * DTLSv1_2_method (void)
const SSL_METHOD * DTLSv1_2_server_method (void)
const SSL_METHOD * DTLSv1_2_client_method (void)
const SSL_METHOD * DTLSv1_method (void)
const SSL_METHOD * DTLSv1_server_method (void)
const SSL_METHOD * DTLSv1_client_method (void)
Function Documentation
DTLSv1_2_client_method()
const SSL_METHOD* DTLSv1_2_client_method (void)
Definition at line 261 of file methods.c.
References dtlsv1_2_client_method().
DTLSv1_2_method()
const SSL_METHOD* DTLSv1_2_method (void)
Definition at line 251 of file methods.c.
References dtlsv1_2_method().
DTLSv1_2_server_method()
const SSL_METHOD* DTLSv1_2_server_method (void)
Definition at line 256 of file methods.c.
References dtlsv1_2_server_method().
DTLSv1_client_method()
const SSL_METHOD* DTLSv1_client_method (void)
Definition at line 278 of file methods.c.
References dtlsv1_client_method().
DTLSv1_method()
const SSL_METHOD* DTLSv1_method (void)
Definition at line 268 of file methods.c.
References dtlsv1_method().
DTLSv1_server_method()
const SSL_METHOD* DTLSv1_server_method (void)
Definition at line 273 of file methods.c.
References dtlsv1_server_method().
IMPLEMENT_tls_meth_func()
IMPLEMENT_tls_meth_func (TLS_ANY_VERSION , IMPLEMENT_tls_meth_func(0, IMPLEMENT_tls_meth_func(0, TLS_method , IMPLEMENT_tls_meth_func(ossl_statem_accept, IMPLEMENT_tls_meth_func(ossl_statem_connect, TLSv1_2_enc_data)
Definition at line 18 of file methods.c.
References tlsv1_2_method().
SSLv3_client_method()
const SSL_METHOD* SSLv3_client_method (void)
Definition at line 244 of file methods.c.
References sslv3_client_method().
SSLv3_method()
const SSL_METHOD* SSLv3_method (void)
Definition at line 234 of file methods.c.
References sslv3_method().
SSLv3_server_method()
const SSL_METHOD* SSLv3_server_method (void)
Definition at line 239 of file methods.c.
References sslv3_server_method().
TLSv1_1_client_method()
const SSL_METHOD* TLSv1_1_client_method (void)
Definition at line 210 of file methods.c.
References tlsv1_1_client_method().
TLSv1_1_method()
const SSL_METHOD* TLSv1_1_method (void)
Definition at line 200 of file methods.c.
References tlsv1_1_method().
TLSv1_1_server_method()
const SSL_METHOD* TLSv1_1_server_method (void)
Definition at line 205 of file methods.c.
References tlsv1_1_server_method().
TLSv1_2_client_method()
const SSL_METHOD* TLSv1_2_client_method (void)
Definition at line 193 of file methods.c.
References tlsv1_2_client_method().
TLSv1_2_server_method()
const SSL_METHOD* TLSv1_2_server_method (void)
Definition at line 188 of file methods.c.
References tlsv1_2_server_method().
TLSv1_client_method()
const SSL_METHOD* TLSv1_client_method (void)
Definition at line 227 of file methods.c.
References tlsv1_client_method().
TLSv1_method()
const SSL_METHOD* TLSv1_method (void)
Definition at line 217 of file methods.c.
References tlsv1_method().
TLSv1_server_method()
const SSL_METHOD* TLSv1_server_method (void)
Definition at line 222 of file methods.c.
References tlsv1_server_method().