include/openssl/modes.h File Reference
modes.h File Reference
#include <stddef.h>
Typedefs
typedef void(* block128_f) (const unsigned char in[16], unsigned char out[16], const void *key)
typedef void(* cbc128_f) (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], int enc)
typedef void(* ctr128_f) (const unsigned char *in, unsigned char *out, size_t blocks, const void *key, const unsigned char ivec[16])
typedef void(* ccm128_f) (const unsigned char *in, unsigned char *out, size_t blocks, const void *key, const unsigned char ivec[16], unsigned char cmac[16])
typedef void(* ocb128_f) (const unsigned char *in, unsigned char *out, size_t blocks, const void *key, size_t start_block_num, unsigned char offset_i[16], const unsigned char L_[][16], unsigned char checksum[16])
Functions
void CRYPTO_cbc128_encrypt (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], block128_f block)
void CRYPTO_cbc128_decrypt (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], block128_f block)
void CRYPTO_ctr128_encrypt (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], unsigned char ecount_buf[16], unsigned int *num, block128_f block)
void CRYPTO_ctr128_encrypt_ctr32 (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], unsigned char ecount_buf[16], unsigned int *num, ctr128_f ctr)
void CRYPTO_ofb128_encrypt (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], int *num, block128_f block)
void CRYPTO_cfb128_encrypt (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], int *num, int enc, block128_f block)
void CRYPTO_cfb128_8_encrypt (const unsigned char *in, unsigned char *out, size_t length, const void *key, unsigned char ivec[16], int *num, int enc, block128_f block)
void CRYPTO_cfb128_1_encrypt (const unsigned char *in, unsigned char *out, size_t bits, const void *key, unsigned char ivec[16], int *num, int enc, block128_f block)
size_t CRYPTO_cts128_encrypt_block (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], block128_f block)
size_t CRYPTO_cts128_encrypt (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], cbc128_f cbc)
size_t CRYPTO_cts128_decrypt_block (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], block128_f block)
size_t CRYPTO_cts128_decrypt (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], cbc128_f cbc)
size_t CRYPTO_nistcts128_encrypt_block (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], block128_f block)
size_t CRYPTO_nistcts128_encrypt (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], cbc128_f cbc)
size_t CRYPTO_nistcts128_decrypt_block (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], block128_f block)
size_t CRYPTO_nistcts128_decrypt (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], cbc128_f cbc)
GCM128_CONTEXT * CRYPTO_gcm128_new (void *key, block128_f block)
void CRYPTO_gcm128_init (GCM128_CONTEXT *ctx, void *key, block128_f block)
void CRYPTO_gcm128_setiv (GCM128_CONTEXT *ctx, const unsigned char *iv, size_t len)
int CRYPTO_gcm128_aad (GCM128_CONTEXT *ctx, const unsigned char *aad, size_t len)
int CRYPTO_gcm128_encrypt (GCM128_CONTEXT *ctx, const unsigned char *in, unsigned char *out, size_t len)
int CRYPTO_gcm128_decrypt (GCM128_CONTEXT *ctx, const unsigned char *in, unsigned char *out, size_t len)
int CRYPTO_gcm128_encrypt_ctr32 (GCM128_CONTEXT *ctx, const unsigned char *in, unsigned char *out, size_t len, ctr128_f stream)
int CRYPTO_gcm128_decrypt_ctr32 (GCM128_CONTEXT *ctx, const unsigned char *in, unsigned char *out, size_t len, ctr128_f stream)
int CRYPTO_gcm128_finish (GCM128_CONTEXT *ctx, const unsigned char *tag, size_t len)
void CRYPTO_gcm128_tag (GCM128_CONTEXT *ctx, unsigned char *tag, size_t len)
void CRYPTO_gcm128_release (GCM128_CONTEXT *ctx)
void CRYPTO_ccm128_init (CCM128_CONTEXT *ctx, unsigned int M, unsigned int L, void *key, block128_f block)
int CRYPTO_ccm128_setiv (CCM128_CONTEXT *ctx, const unsigned char *nonce, size_t nlen, size_t mlen)
void CRYPTO_ccm128_aad (CCM128_CONTEXT *ctx, const unsigned char *aad, size_t alen)
int CRYPTO_ccm128_encrypt (CCM128_CONTEXT *ctx, const unsigned char *inp, unsigned char *out, size_t len)
int CRYPTO_ccm128_decrypt (CCM128_CONTEXT *ctx, const unsigned char *inp, unsigned char *out, size_t len)
int CRYPTO_ccm128_encrypt_ccm64 (CCM128_CONTEXT *ctx, const unsigned char *inp, unsigned char *out, size_t len, ccm128_f stream)
int CRYPTO_ccm128_decrypt_ccm64 (CCM128_CONTEXT *ctx, const unsigned char *inp, unsigned char *out, size_t len, ccm128_f stream)
size_t CRYPTO_ccm128_tag (CCM128_CONTEXT *ctx, unsigned char *tag, size_t len)
int CRYPTO_xts128_encrypt (const XTS128_CONTEXT *ctx, const unsigned char iv[16], const unsigned char *inp, unsigned char *out, size_t len, int enc)
size_t CRYPTO_128_wrap (void *key, const unsigned char *iv, unsigned char *out, const unsigned char *in, size_t inlen, block128_f block)
size_t CRYPTO_128_unwrap (void *key, const unsigned char *iv, unsigned char *out, const unsigned char *in, size_t inlen, block128_f block)
size_t CRYPTO_128_wrap_pad (void *key, const unsigned char *icv, unsigned char *out, const unsigned char *in, size_t inlen, block128_f block)
size_t CRYPTO_128_unwrap_pad (void *key, const unsigned char *icv, unsigned char *out, const unsigned char *in, size_t inlen, block128_f block)
OCB128_CONTEXT * CRYPTO_ocb128_new (void *keyenc, void *keydec, block128_f encrypt, block128_f decrypt, ocb128_f stream)
int CRYPTO_ocb128_init (OCB128_CONTEXT *ctx, void *keyenc, void *keydec, block128_f encrypt, block128_f decrypt, ocb128_f stream)
int CRYPTO_ocb128_copy_ctx (OCB128_CONTEXT *dest, OCB128_CONTEXT *src, void *keyenc, void *keydec)
int CRYPTO_ocb128_setiv (OCB128_CONTEXT *ctx, const unsigned char *iv, size_t len, size_t taglen)
int CRYPTO_ocb128_aad (OCB128_CONTEXT *ctx, const unsigned char *aad, size_t len)
int CRYPTO_ocb128_encrypt (OCB128_CONTEXT *ctx, const unsigned char *in, unsigned char *out, size_t len)
int CRYPTO_ocb128_decrypt (OCB128_CONTEXT *ctx, const unsigned char *in, unsigned char *out, size_t len)
int CRYPTO_ocb128_finish (OCB128_CONTEXT *ctx, const unsigned char *tag, size_t len)
int CRYPTO_ocb128_tag (OCB128_CONTEXT *ctx, unsigned char *tag, size_t len)
void CRYPTO_ocb128_cleanup (OCB128_CONTEXT *ctx)
Typedef Documentation
block128_f
typedef void(* block128_f) (const unsigned char in[16], unsigned char out[16], const void *key)
Definition at line 18 of file modes.h.
cbc128_f
typedef void(* cbc128_f) (const unsigned char *in, unsigned char *out, size_t len, const void *key, unsigned char ivec[16], int enc)
Definition at line 21 of file modes.h.
ccm128_f
typedef void(* ccm128_f) (const unsigned char *in, unsigned char *out, size_t blocks, const void *key, const unsigned char ivec[16], unsigned char cmac[16])
Definition at line 29 of file modes.h.
ctr128_f
typedef void(* ctr128_f) (const unsigned char *in, unsigned char *out, size_t blocks, const void *key, const unsigned char ivec[16])
Definition at line 25 of file modes.h.
ocb128_f
typedef void(* ocb128_f) (const unsigned char *in, unsigned char *out, size_t blocks, const void *key, size_t start_block_num, unsigned char offset_i[16], const unsigned char L_[][16], unsigned char checksum[16])
Definition at line 175 of file modes.h.
Function Documentation
CRYPTO_128_unwrap()
size_t CRYPTO_128_unwrap (void * key, const unsigned char * iv, unsigned char * out, const unsigned char * in, size_t inlen, block128_f block)
Unwrapping according to RFC 3394 section 2.2.2, including the IV check. The first block of plaintext has to match the supplied IV, otherwise an error is returned.
Parameters
[in] key Key value.
[out] iv IV value to match against. Length = 8 bytes. NULL = use default_iv.
[out] out Plaintext without IV. Minimal buffer length = (inlen - 8) bytes. Input and output buffers can overlap if block function supports that.
[in] in Ciphertext as n 64-bit blocks.
[in] inlen Length of in.
[in] block Block processing function.
Returns
0 if inlen is out of range [24, CRYPTO128_WRAP_MAX] or if inlen is not a multiple of 8 or if IV doesn't match expected value. Output length otherwise.
Definition at line 150 of file wrap128.c.
CRYPTO_128_unwrap_pad()
size_t CRYPTO_128_unwrap_pad (void * key, const unsigned char * icv, unsigned char * out, const unsigned char * in, size_t inlen, block128_f block)
Unwrapping according to RFC 5649 section 4.2.
Parameters
[in] key Key value.
[in] icv (Non-standard) IV, 4 bytes. NULL = use default_aiv.
[out] out Plaintext. Minimal buffer length = inlen bytes. Input and output buffers can overlap if block function supports that.
[in] in Ciphertext as n 64-bit blocks.
[in] inlen Length of in.
[in] block Block processing function.
Returns
0 if inlen is out of range [16, CRYPTO128_WRAP_MAX], or if inlen is not a multiple of 8 or if IV and message length indicator doesn't match. Output length if unwrapping succeeded and IV matches.
Definition at line 251 of file wrap128.c.
CRYPTO_128_wrap()
size_t CRYPTO_128_wrap (void * key, const unsigned char * iv, unsigned char * out, const unsigned char * in, size_t inlen, block128_f block)
Wrapping according to RFC 3394 section 2.2.1.
Parameters
[in] key Key value.
[in] iv IV value. Length = 8 bytes. NULL = use default_iv.
[in] in Plaintext as n 64-bit blocks, n >= 2.
[in] inlen Length of in.
[out] out Ciphertext. Minimal buffer length = (inlen + 8) bytes. Input and output buffers can overlap if block function supports that.
[in] block Block processing function.
Returns
0 if inlen does not consist of n 64-bit blocks, n >= 2. or if inlen > CRYPTO128_WRAP_MAX. Output length if wrapping succeeded.
Definition at line 48 of file wrap128.c.
CRYPTO_128_wrap_pad()
size_t CRYPTO_128_wrap_pad (void * key, const unsigned char * icv, unsigned char * out, const unsigned char * in, size_t inlen, block128_f block)
Wrapping according to RFC 5649 section 4.1.
Parameters
[in] key Key value.
[in] icv (Non-standard) IV, 4 bytes. NULL = use default_aiv.
[out] out Ciphertext. Minimal buffer length = (inlen + 15) bytes. Input and output buffers can overlap if block function supports that.
[in] in Plaintext as n 64-bit blocks, n >= 2.
[in] inlen Length of in.
[in] block Block processing function.
Returns
0 if inlen is out of range [1, CRYPTO128_WRAP_MAX]. Output length if wrapping succeeded.
Definition at line 183 of file wrap128.c.
CRYPTO_cbc128_decrypt()
void CRYPTO_cbc128_decrypt (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], block128_f block)
Definition at line 66 of file cbc128.c.
CRYPTO_cbc128_encrypt()
void CRYPTO_cbc128_encrypt (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], block128_f block)
Definition at line 18 of file cbc128.c.
CRYPTO_ccm128_aad()
void CRYPTO_ccm128_aad (CCM128_CONTEXT * ctx, const unsigned char * aad, size_t alen)
Definition at line 60 of file ccm128.c.
References if().
CRYPTO_ccm128_decrypt()
int CRYPTO_ccm128_decrypt (CCM128_CONTEXT * ctx, const unsigned char * inp, unsigned char * out, size_t len)
Definition at line 213 of file ccm128.c.
CRYPTO_ccm128_decrypt_ccm64()
int CRYPTO_ccm128_decrypt_ccm64 (CCM128_CONTEXT * ctx, const unsigned char * inp, unsigned char * out, size_t len, ccm128_f stream)
Definition at line 364 of file ccm128.c.
CRYPTO_ccm128_encrypt()
int CRYPTO_ccm128_encrypt (CCM128_CONTEXT * ctx, const unsigned char * inp, unsigned char * out, size_t len)
Definition at line 129 of file ccm128.c.
CRYPTO_ccm128_encrypt_ccm64()
int CRYPTO_ccm128_encrypt_ccm64 (CCM128_CONTEXT * ctx, const unsigned char * inp, unsigned char * out, size_t len, ccm128_f stream)
Definition at line 300 of file ccm128.c.
CRYPTO_ccm128_init()
void CRYPTO_ccm128_init (CCM128_CONTEXT * ctx, unsigned int M, unsigned int L, void * key, block128_f block)
Definition at line 18 of file ccm128.c.
References key.
CRYPTO_ccm128_setiv()
int CRYPTO_ccm128_setiv (CCM128_CONTEXT * ctx, const unsigned char * nonce, size_t nlen, size_t mlen)
Definition at line 32 of file ccm128.c.
CRYPTO_ccm128_tag()
size_t CRYPTO_ccm128_tag (CCM128_CONTEXT * ctx, unsigned char * tag, size_t len)
Definition at line 422 of file ccm128.c.
Referenced by BLOCK_CIPHER_custom().
CRYPTO_cfb128_1_encrypt()
void CRYPTO_cfb128_1_encrypt (const unsigned char * in, unsigned char * out, size_t bits, const void * key, unsigned char ivec[16], int * num, int enc, block128_f block)
Definition at line 173 of file cfb128.c.
CRYPTO_cfb128_8_encrypt()
void CRYPTO_cfb128_8_encrypt (const unsigned char * in, unsigned char * out, size_t length, const void * key, unsigned char ivec[16], int * num, int enc, block128_f block)
Definition at line 189 of file cfb128.c.
CRYPTO_cfb128_encrypt()
void CRYPTO_cfb128_encrypt (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], int * num, int enc, block128_f block)
Definition at line 19 of file cfb128.c.
CRYPTO_ctr128_encrypt()
void CRYPTO_ctr128_encrypt (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], unsigned char ecount_buf[16], unsigned int * num, block128_f block)
Definition at line 71 of file ctr128.c.
CRYPTO_ctr128_encrypt_ctr32()
void CRYPTO_ctr128_encrypt_ctr32 (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], unsigned char ecount_buf[16], unsigned int * num, ctr128_f ctr)
Definition at line 147 of file ctr128.c.
CRYPTO_cts128_decrypt()
size_t CRYPTO_cts128_decrypt (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], cbc128_f cbc)
Definition at line 248 of file cts128.c.
CRYPTO_cts128_decrypt_block()
size_t CRYPTO_cts128_decrypt_block (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], block128_f block)
Definition at line 158 of file cts128.c.
CRYPTO_cts128_encrypt()
size_t CRYPTO_cts128_encrypt (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], cbc128_f cbc)
Definition at line 87 of file cts128.c.
CRYPTO_cts128_encrypt_block()
size_t CRYPTO_cts128_encrypt_block (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], block128_f block)
Definition at line 27 of file cts128.c.
CRYPTO_gcm128_aad()
int CRYPTO_gcm128_aad (GCM128_CONTEXT * ctx, const unsigned char * aad, size_t len)
Definition at line 910 of file gcm128.c.
References GCM_MUL, GHASH, if(), len, and U64.
CRYPTO_gcm128_decrypt()
int CRYPTO_gcm128_decrypt (GCM128_CONTEXT * ctx, const unsigned char * in, unsigned char * out, size_t len)
Definition at line 1155 of file gcm128.c.
CRYPTO_gcm128_decrypt_ctr32()
int CRYPTO_gcm128_decrypt_ctr32 (GCM128_CONTEXT * ctx, const unsigned char * in, unsigned char * out, size_t len, ctr128_f stream)
Definition at line 1471 of file gcm128.c.
CRYPTO_gcm128_encrypt()
int CRYPTO_gcm128_encrypt (GCM128_CONTEXT * ctx, const unsigned char * in, unsigned char * out, size_t len)
Definition at line 971 of file gcm128.c.
CRYPTO_gcm128_encrypt_ctr32()
int CRYPTO_gcm128_encrypt_ctr32 (GCM128_CONTEXT * ctx, const unsigned char * in, unsigned char * out, size_t len, ctr128_f stream)
Definition at line 1347 of file gcm128.c.
CRYPTO_gcm128_finish()
int CRYPTO_gcm128_finish (GCM128_CONTEXT * ctx, const unsigned char * tag, size_t len)
Definition at line 1602 of file gcm128.c.
References CRYPTO_memcmp(), GCM_MUL, GETU32, and if().
Referenced by CRYPTO_gcm128_tag().
CRYPTO_gcm128_init()
void CRYPTO_gcm128_init (GCM128_CONTEXT * ctx, void * key, block128_f block)
Definition at line 713 of file gcm128.c.
References CTX__GHASH, GETU32, and key.
CRYPTO_gcm128_new()
GCM128_CONTEXT* CRYPTO_gcm128_new (void * key, block128_f block)
Definition at line 1653 of file gcm128.c.
CRYPTO_gcm128_release()
void CRYPTO_gcm128_release (GCM128_CONTEXT * ctx)
Definition at line 1663 of file gcm128.c.
References OPENSSL_clear_free.
CRYPTO_gcm128_setiv()
void CRYPTO_gcm128_setiv (GCM128_CONTEXT * ctx, const unsigned char * iv, size_t len)
Definition at line 828 of file gcm128.c.
CRYPTO_gcm128_tag()
void CRYPTO_gcm128_tag (GCM128_CONTEXT * ctx, unsigned char * tag, size_t len)
Definition at line 1646 of file gcm128.c.
References CRYPTO_gcm128_finish(), and NULL.
CRYPTO_nistcts128_decrypt()
size_t CRYPTO_nistcts128_decrypt (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], cbc128_f cbc)
Definition at line 288 of file cts128.c.
CRYPTO_nistcts128_decrypt_block()
size_t CRYPTO_nistcts128_decrypt_block (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], block128_f block)
Definition at line 200 of file cts128.c.
CRYPTO_nistcts128_encrypt()
size_t CRYPTO_nistcts128_encrypt (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], cbc128_f cbc)
Definition at line 123 of file cts128.c.
CRYPTO_nistcts128_encrypt_block()
size_t CRYPTO_nistcts128_encrypt_block (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], block128_f block)
Definition at line 56 of file cts128.c.
CRYPTO_ocb128_aad()
int CRYPTO_ocb128_aad (OCB128_CONTEXT * ctx, const unsigned char * aad, size_t len)
Definition at line 272 of file ocb128.c.
CRYPTO_ocb128_cleanup()
void CRYPTO_ocb128_cleanup (OCB128_CONTEXT * ctx)
Definition at line 560 of file ocb128.c.
References OPENSSL_cleanse(), and OPENSSL_clear_free.
CRYPTO_ocb128_copy_ctx()
int CRYPTO_ocb128_copy_ctx (OCB128_CONTEXT * dest, OCB128_CONTEXT * src, void * keyenc, void * keydec)
Definition at line 204 of file ocb128.c.
References NULL, and OPENSSL_malloc.
CRYPTO_ocb128_decrypt()
int CRYPTO_ocb128_decrypt (OCB128_CONTEXT * ctx, const unsigned char * in, unsigned char * out, size_t len)
Definition at line 424 of file ocb128.c.
References NULL.
CRYPTO_ocb128_encrypt()
int CRYPTO_ocb128_encrypt (OCB128_CONTEXT * ctx, const unsigned char * in, unsigned char * out, size_t len)
Definition at line 332 of file ocb128.c.
References NULL.
CRYPTO_ocb128_finish()
int CRYPTO_ocb128_finish (OCB128_CONTEXT * ctx, const unsigned char * tag, size_t len)
Definition at line 515 of file ocb128.c.
References OCB_BLOCK::c, CRYPTO_memcmp(), and ocb_block16_xor.
Referenced by CRYPTO_ocb128_tag().
CRYPTO_ocb128_init()
int CRYPTO_ocb128_init (OCB128_CONTEXT * ctx, void * keyenc, void * keydec, block128_f encrypt, block128_f decrypt, ocb128_f stream)
Definition at line 160 of file ocb128.c.
CRYPTO_ocb128_new()
OCB128_CONTEXT* CRYPTO_ocb128_new (void * keyenc, void * keydec, block128_f encrypt, block128_f decrypt, ocb128_f stream)
Definition at line 139 of file ocb128.c.
CRYPTO_ocb128_setiv()
int CRYPTO_ocb128_setiv (OCB128_CONTEXT * ctx, const unsigned char * iv, size_t len, size_t taglen)
Definition at line 224 of file ocb128.c.
CRYPTO_ocb128_tag()
int CRYPTO_ocb128_tag (OCB128_CONTEXT * ctx, unsigned char * tag, size_t len)
Definition at line 542 of file ocb128.c.
References CRYPTO_ocb128_finish(), and NULL.
CRYPTO_ofb128_encrypt()
void CRYPTO_ofb128_encrypt (const unsigned char * in, unsigned char * out, size_t len, const void * key, unsigned char ivec[16], int * num, block128_f block)
Definition at line 19 of file ofb128.c.
CRYPTO_xts128_encrypt()
int CRYPTO_xts128_encrypt (const XTS128_CONTEXT * ctx, const unsigned char iv[16], const unsigned char * inp, unsigned char * out, size_t len, int enc)
Definition at line 14 of file xts128.c.