crypto/evp/names.c File Reference
names.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/evp.h>
#include <internal/objects.h>
#include <openssl/x509.h>
#include "internal/evp_int.h"
Data Structures
struct doall_cipher
struct doall_md
Functions
int EVP_add_cipher (const EVP_CIPHER *c)
int EVP_add_digest (const EVP_MD *md)
const EVP_CIPHER * EVP_get_cipherbyname (const char *name)
const EVP_MD * EVP_get_digestbyname (const char *name)
void evp_cleanup_int (void)
void EVP_CIPHER_do_all (void(*fn)(const EVP_CIPHER *ciph, const char *from, const char *to, void *x), void *arg)
void EVP_CIPHER_do_all_sorted (void(*fn)(const EVP_CIPHER *ciph, const char *from, const char *to, void *x), void *arg)
void EVP_MD_do_all (void(*fn)(const EVP_MD *md, const char *from, const char *to, void *x), void *arg)
void EVP_MD_do_all_sorted (void(*fn)(const EVP_MD *md, const char *from, const char *to, void *x), void *arg)
Function Documentation
EVP_add_cipher()
int EVP_add_cipher (const EVP_CIPHER * c)
Definition at line 17 of file names.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_ciphers_int().
EVP_add_digest()
int EVP_add_digest (const EVP_MD * md)
Definition at line 33 of file names.c.
Referenced by DEFINE_RUN_ONCE_STATIC(), and openssl_add_all_digests_int().
EVP_CIPHER_do_all()
void EVP_CIPHER_do_all (void(*)(const EVP_CIPHER *ciph, const char *from, const char *to, void *x) fn, void * arg)
Definition at line 110 of file names.c.
References doall_cipher::arg, doall_cipher::fn, NULL, OBJ_NAME_do_all(), OBJ_NAME_TYPE_CIPHER_METH, OPENSSL_INIT_ADD_ALL_CIPHERS, and OPENSSL_init_crypto().
EVP_CIPHER_do_all_sorted()
void EVP_CIPHER_do_all_sorted (void(*)(const EVP_CIPHER *ciph, const char *from, const char *to, void *x) fn, void * arg)
Definition at line 124 of file names.c.
References doall_cipher::arg, doall_cipher::fn, NULL, OBJ_NAME_do_all_sorted(), OBJ_NAME_TYPE_CIPHER_METH, OPENSSL_INIT_ADD_ALL_CIPHERS, and OPENSSL_init_crypto().
evp_cleanup_int()
void evp_cleanup_int (void)
Definition at line 80 of file names.c.
References EVP_PBE_cleanup(), OBJ_NAME_cleanup(), OBJ_NAME_TYPE_CIPHER_METH, OBJ_NAME_TYPE_MD_METH, and OBJ_sigid_free().
EVP_get_cipherbyname()
const EVP_CIPHER* EVP_get_cipherbyname (const char * name)
Definition at line 58 of file names.c.
References NULL, OBJ_NAME_get(), OBJ_NAME_TYPE_CIPHER_METH, OPENSSL_INIT_ADD_ALL_CIPHERS, and OPENSSL_init_crypto().
Referenced by opt_cipher().
EVP_get_digestbyname()
const EVP_MD* EVP_get_digestbyname (const char * name)
Definition at line 69 of file names.c.
References NULL, OBJ_NAME_get(), OBJ_NAME_TYPE_MD_METH, OPENSSL_INIT_ADD_ALL_DIGESTS, and OPENSSL_init_crypto().
Referenced by opt_md().
EVP_MD_do_all()
void EVP_MD_do_all (void(*)(const EVP_MD *md, const char *from, const char *to, void *x) fn, void * arg)
Definition at line 153 of file names.c.
EVP_MD_do_all_sorted()
void EVP_MD_do_all_sorted (void(*)(const EVP_MD *md, const char *from, const char *to, void *x) fn, void * arg)
Definition at line 167 of file names.c.