crypto/objects/o_names.c File Reference
o_names.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <openssl/err.h>
#include <openssl/lhash.h>
#include <openssl/objects.h>
#include <openssl/safestack.h>
#include <openssl/e_os2.h>
#include "obj_lcl.h"
Data Structures
struct OBJ_DOALL
struct doall_sorted
Macros
#define obj_strcmp strcmp
Functions
int OBJ_NAME_new_index (unsigned long(*hash_func)(const char *), int(*cmp_func)(const char *, const char *), void(*free_func)(const char *, int, const char *))
const char * OBJ_NAME_get (const char *name, int type)
int OBJ_NAME_add (const char *name, int type, const char *data)
int OBJ_NAME_remove (const char *name, int type)
IMPLEMENT_LHASH_DOALL_ARG_CONST (OBJ_NAME, OBJ_DOALL)
void OBJ_NAME_do_all (int type, void(*fn)(const OBJ_NAME *, void *arg), void *arg)
void OBJ_NAME_do_all_sorted (int type, void(*fn)(const OBJ_NAME *, void *arg), void *arg)
void OBJ_NAME_cleanup (int type)
Macro Definition Documentation
obj_strcmp
#define obj_strcmp strcmp
Definition at line 38 of file o_names.c.
Function Documentation
IMPLEMENT_LHASH_DOALL_ARG_CONST()
IMPLEMENT_LHASH_DOALL_ARG_CONST (OBJ_NAME , OBJ_DOALL)
OBJ_NAME_add()
int OBJ_NAME_add (const char * name, int type, const char * data)
Definition at line 186 of file o_names.c.
OBJ_NAME_cleanup()
void OBJ_NAME_cleanup (int type)
Definition at line 351 of file o_names.c.
References NULL, and type.
Referenced by evp_cleanup_int().
OBJ_NAME_do_all()
void OBJ_NAME_do_all (int type, void(*)(const OBJ_NAME *, void *arg) fn, void * arg)
Definition at line 275 of file o_names.c.
Referenced by EVP_CIPHER_do_all().
OBJ_NAME_do_all_sorted()
void OBJ_NAME_do_all_sorted (int type, void(*)(const OBJ_NAME *, void *arg) fn, void * arg)
Definition at line 311 of file o_names.c.
Referenced by EVP_CIPHER_do_all_sorted().
OBJ_NAME_get()
const char* OBJ_NAME_get (const char * name, int type)
Definition at line 156 of file o_names.c.
Referenced by EVP_get_cipherbyname(), and EVP_get_digestbyname().
OBJ_NAME_new_index()
int OBJ_NAME_new_index (unsigned long(*)(const char *) hash_func, int(*)(const char *, const char *) cmp_func, void(*)(const char *, int, const char *) free_func)
Definition at line 75 of file o_names.c.
OBJ_NAME_remove()
int OBJ_NAME_remove (const char * name, int type)
Definition at line 232 of file o_names.c.