crypto/o_str.c File Reference
o_str.c File Reference
#include <ctype.h>
#include <limits.h>
#include <e_os.h>
#include <openssl/crypto.h>
#include "internal/cryptlib.h"
#include "internal/o_str.h"
Functions
int OPENSSL_memcmp (const void *v1, const void *v2, size_t n)
char * CRYPTO_strdup (const char *str, const char *file, int line)
char * CRYPTO_strndup (const char *str, size_t s, const char *file, int line)
void * CRYPTO_memdup (const void *data, size_t siz, const char *file, int line)
size_t OPENSSL_strnlen (const char *str, size_t maxlen)
size_t OPENSSL_strlcpy (char *dst, const char *src, size_t size)
size_t OPENSSL_strlcat (char *dst, const char *src, size_t size)
int OPENSSL_hexchar2int (unsigned char c)
unsigned char * OPENSSL_hexstr2buf (const char *str, long *len)
char * OPENSSL_buf2hexstr (const unsigned char *buffer, long len)
int openssl_strerror_r (int errnum, char *buf, size_t buflen)
Function Documentation
CRYPTO_memdup()
void* CRYPTO_memdup (const void * data, size_t siz, const char * file, int line)
Definition at line 60 of file o_str.c.
CRYPTO_strdup()
char* CRYPTO_strdup (const char * str, const char * file, int line)
Definition at line 28 of file o_str.c.
CRYPTO_strndup()
char* CRYPTO_strndup (const char * str, size_t s, const char * file, int line)
Definition at line 42 of file o_str.c.
OPENSSL_buf2hexstr()
char* OPENSSL_buf2hexstr (const unsigned char * buffer, long len)
Definition at line 194 of file o_str.c.
References CRYPTO_F_OPENSSL_BUF2HEXSTR, CRYPTOerr, ebcdic2ascii(), ERR_R_MALLOC_FAILURE, len, NULL, OPENSSL_malloc, OPENSSL_zalloc, and q.
Referenced by i2s_ASN1_OCTET_STRING().
OPENSSL_hexchar2int()
int OPENSSL_hexchar2int (unsigned char c)
Definition at line 104 of file o_str.c.
Referenced by OPENSSL_hexstr2buf().
OPENSSL_hexstr2buf()
unsigned char* OPENSSL_hexstr2buf (const char * str, long * len)
Definition at line 150 of file o_str.c.
References CRYPTO_F_OPENSSL_HEXSTR2BUF, CRYPTO_R_ILLEGAL_HEX_DIGIT, CRYPTO_R_ODD_NUMBER_OF_DIGITS, CRYPTOerr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_hexchar2int(), OPENSSL_malloc, and q.
Referenced by EVP_PKEY_CTX_hex2ctrl(), and s2i_ASN1_OCTET_STRING().
OPENSSL_memcmp()
int OPENSSL_memcmp (const void * v1, const void * v2, size_t n)
Definition at line 17 of file o_str.c.
openssl_strerror_r()
int openssl_strerror_r (int errnum, char * buf, size_t buflen)
Definition at line 224 of file o_str.c.
OPENSSL_strlcat()
size_t OPENSSL_strlcat (char * dst, const char * src, size_t size)
Definition at line 96 of file o_str.c.
References OPENSSL_strlcpy().
Referenced by CONF_get1_default_config_file(), ERR_add_error_vdata(), and UI_construct_prompt().
OPENSSL_strlcpy()
size_t OPENSSL_strlcpy (char * dst, const char * src, size_t size)
Definition at line 84 of file o_str.c.
Referenced by CONF_get1_default_config_file(), OPENSSL_strlcat(), UI_construct_prompt(), and UI_set_result().
OPENSSL_strnlen()
size_t OPENSSL_strnlen (const char * str, size_t maxlen)
Definition at line 75 of file o_str.c.