crypto/o_time.c File Reference
o_time.c File Reference
#include <openssl/e_os2.h>
#include <string.h>
#include <openssl/crypto.h>
Macros
#define SECS_PER_DAY (24 * 60 * 60)
Functions
struct tm * OPENSSL_gmtime (const time_t *timer, struct tm *result)
int OPENSSL_gmtime_adj (struct tm *tm, int off_day, long offset_sec)
int OPENSSL_gmtime_diff (int *pday, int *psec, const struct tm *from, const struct tm *to)
Macro Definition Documentation
SECS_PER_DAY
#define SECS_PER_DAY (24 * 60 * 60)
Definition at line 225 of file o_time.c.
Function Documentation
OPENSSL_gmtime()
struct tm* OPENSSL_gmtime (const time_t * timer, struct tm * result)
Definition at line 50 of file o_time.c.
References NULL, and t.
Referenced by ASN1_GENERALIZEDTIME_adj(), ASN1_TIME_adj(), ASN1_UTCTIME_adj(), and ASN1_UTCTIME_cmp_time_t().
OPENSSL_gmtime_adj()
int OPENSSL_gmtime_adj (struct tm * tm, int off_day, long offset_sec)
Definition at line 232 of file o_time.c.
Referenced by ASN1_GENERALIZEDTIME_adj(), asn1_generalizedtime_to_tm(), ASN1_TIME_adj(), ASN1_UTCTIME_adj(), and asn1_utctime_to_tm().
OPENSSL_gmtime_diff()
int OPENSSL_gmtime_diff (int * pday, int * psec, const struct tm * from, const struct tm * to)
Definition at line 262 of file o_time.c.
Referenced by ASN1_UTCTIME_cmp_time_t().