crypto/objects/obj_xref.c File Reference
obj_xref.c File Reference
#include <openssl/objects.h>
#include "obj_xref.h"
#include "e_os.h"
Functions
DECLARE_OBJ_BSEARCH_CMP_FN (nid_triple, nid_triple, sig)
IMPLEMENT_OBJ_BSEARCH_CMP_FN (nid_triple, nid_triple, sig)
DECLARE_OBJ_BSEARCH_CMP_FN (const nid_triple *, const nid_triple *, sigx)
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const nid_triple *, const nid_triple *, sigx)
int OBJ_find_sigid_algs (int signid, int *pdig_nid, int *ppkey_nid)
int OBJ_find_sigid_by_algs (int *psignid, int dig_nid, int pkey_nid)
int OBJ_add_sigid (int signid, int dig_id, int pkey_id)
void OBJ_sigid_free (void)
Function Documentation
DECLARE_OBJ_BSEARCH_CMP_FN() [1/2]
DECLARE_OBJ_BSEARCH_CMP_FN (nid_triple , nid_triple , sig)
DECLARE_OBJ_BSEARCH_CMP_FN() [2/2]
DECLARE_OBJ_BSEARCH_CMP_FN (const nid_triple * , const nid_triple * , sigx)
IMPLEMENT_OBJ_BSEARCH_CMP_FN() [1/2]
IMPLEMENT_OBJ_BSEARCH_CMP_FN (nid_triple , nid_triple , sig)
IMPLEMENT_OBJ_BSEARCH_CMP_FN() [2/2]
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const nid_triple * , const nid_triple * , sigx)
OBJ_add_sigid()
int OBJ_add_sigid (int signid, int dig_id, int pkey_id)
Definition at line 95 of file obj_xref.c.
References NULL.
OBJ_find_sigid_algs()
int OBJ_find_sigid_algs (int signid, int * pdig_nid, int * ppkey_nid)
Definition at line 42 of file obj_xref.c.
References NULL, and nid_triple::sign_id.
Referenced by X509_signature_print().
OBJ_find_sigid_by_algs()
int OBJ_find_sigid_by_algs (int * psignid, int dig_nid, int pkey_nid)
Definition at line 67 of file obj_xref.c.
References nid_triple::hash_id, NULL, nid_triple::pkey_id, and t.
Referenced by ASN1_item_sign_ctx().
OBJ_sigid_free()
void OBJ_sigid_free (void)
Definition at line 132 of file obj_xref.c.
Referenced by evp_cleanup_int().