crypto/objects/obj_lib.c File Reference
obj_lib.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/lhash.h>
#include <openssl/objects.h>
#include <openssl/buffer.h>
#include "internal/asn1_int.h"
Functions
ASN1_OBJECT * OBJ_dup (const ASN1_OBJECT *o)
int OBJ_cmp (const ASN1_OBJECT *a, const ASN1_OBJECT *b)
Function Documentation
OBJ_cmp()
int OBJ_cmp (const ASN1_OBJECT * a, const ASN1_OBJECT * b)
Definition at line 58 of file obj_lib.c.
Referenced by ASN1_TYPE_cmp(), level_find_node(), policy_node_match(), X509_NAME_get_index_by_OBJ(), X509at_get_attr_by_OBJ(), and X509v3_get_ext_by_OBJ().
OBJ_dup()
ASN1_OBJECT* OBJ_dup (const ASN1_OBJECT * o)
Definition at line 17 of file obj_lib.c.
References ASN1_OBJECT_FLAG_DYNAMIC, ASN1_OBJECT_FLAG_DYNAMIC_DATA, ASN1_OBJECT_FLAG_DYNAMIC_STRINGS, ASN1_OBJECT_free(), ASN1_OBJECT_new(), ERR_R_ASN1_LIB, ERR_R_MALLOC_FAILURE, NULL, OBJ_F_OBJ_DUP, OBJerr, OPENSSL_memdup, and OPENSSL_strdup.
Referenced by ASN1_OBJECT_create(), ASN1_TYPE_set1(), TS_REQ_set_policy_id(), TS_RESP_CTX_add_policy(), TS_RESP_CTX_set_def_policy(), TS_TST_INFO_set_policy_id(), X509_ATTRIBUTE_set1_object(), X509_EXTENSION_set_object(), and X509_NAME_ENTRY_set_object().