crypto/objects/obj_dat.c File Reference
obj_dat.c File Reference
#include <stdio.h>
#include <ctype.h>
#include <limits.h>
#include "internal/cryptlib.h"
#include <openssl/lhash.h>
#include <openssl/asn1.h>
#include "internal/objects.h"
#include <openssl/bn.h>
#include "internal/asn1_int.h"
#include "obj_lcl.h"
#include "obj_dat.h"
Data Structures
struct ADDED_OBJ
Macros
#define ADDED_DATA 0
#define ADDED_SNAME 1
#define ADDED_LNAME 2
#define ADDED_NID 3
Functions
DECLARE_OBJ_BSEARCH_CMP_FN (const ASN1_OBJECT *, unsigned int, sn)
DECLARE_OBJ_BSEARCH_CMP_FN (const ASN1_OBJECT *, unsigned int, ln)
DECLARE_OBJ_BSEARCH_CMP_FN (const ASN1_OBJECT *, unsigned int, obj)
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const ASN1_OBJECT *, unsigned int, sn)
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const ASN1_OBJECT *, unsigned int, ln)
void obj_cleanup_int (void)
int OBJ_new_nid (int num)
int OBJ_add_object (const ASN1_OBJECT *obj)
ASN1_OBJECT * OBJ_nid2obj (int n)
const char * OBJ_nid2sn (int n)
const char * OBJ_nid2ln (int n)
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const ASN1_OBJECT *, unsigned int, obj)
int OBJ_obj2nid (const ASN1_OBJECT *a)
ASN1_OBJECT * OBJ_txt2obj (const char *s, int no_name)
int OBJ_obj2txt (char *buf, int buf_len, const ASN1_OBJECT *a, int no_name)
int OBJ_txt2nid (const char *s)
int OBJ_ln2nid (const char *s)
int OBJ_sn2nid (const char *s)
const void * OBJ_bsearch_ (const void *key, const void *base, int num, int size, int(*cmp)(const void *, const void *))
const void * OBJ_bsearch_ex_ (const void *key, const void *base_, int num, int size, int(*cmp)(const void *, const void *), int flags)
int OBJ_create_objects (BIO *in)
int OBJ_create (const char *oid, const char *sn, const char *ln)
size_t OBJ_length (const ASN1_OBJECT *obj)
const unsigned char * OBJ_get0_data (const ASN1_OBJECT *obj)
Macro Definition Documentation
ADDED_DATA
#define ADDED_DATA 0
Definition at line 28 of file obj_dat.c.
Referenced by OBJ_obj2nid().
ADDED_LNAME
#define ADDED_LNAME 2
Definition at line 30 of file obj_dat.c.
Referenced by OBJ_ln2nid().
ADDED_NID
#define ADDED_NID 3
Definition at line 31 of file obj_dat.c.
ADDED_SNAME
#define ADDED_SNAME 1
Definition at line 29 of file obj_dat.c.
Referenced by OBJ_sn2nid().
Function Documentation
DECLARE_OBJ_BSEARCH_CMP_FN() [1/3]
DECLARE_OBJ_BSEARCH_CMP_FN (const ASN1_OBJECT * , unsigned int, sn)
DECLARE_OBJ_BSEARCH_CMP_FN() [2/3]
DECLARE_OBJ_BSEARCH_CMP_FN (const ASN1_OBJECT * , unsigned int, ln)
DECLARE_OBJ_BSEARCH_CMP_FN() [3/3]
DECLARE_OBJ_BSEARCH_CMP_FN (const ASN1_OBJECT * , unsigned int, obj)
IMPLEMENT_OBJ_BSEARCH_CMP_FN() [1/3]
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const ASN1_OBJECT * , unsigned int, sn)
IMPLEMENT_OBJ_BSEARCH_CMP_FN() [2/3]
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const ASN1_OBJECT * , unsigned int, ln)
IMPLEMENT_OBJ_BSEARCH_CMP_FN() [3/3]
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const ASN1_OBJECT * , unsigned int, obj)
OBJ_add_object()
int OBJ_add_object (const ASN1_OBJECT * obj)
Definition at line 174 of file obj_dat.c.
References NULL.
Referenced by OBJ_create().
OBJ_bsearch_()
const void* OBJ_bsearch_ (const void * key, const void * base, int num, int size, int(*)(const void *, const void *) cmp)
Definition at line 580 of file obj_dat.c.
OBJ_bsearch_ex_()
const void* OBJ_bsearch_ex_ (const void * key, const void * base_, int num, int size, int(*)(const void *, const void *) cmp, int flags)
Definition at line 586 of file obj_dat.c.
References h.
obj_cleanup_int()
void obj_cleanup_int (void)
Definition at line 153 of file obj_dat.c.
References NULL.
OBJ_create()
int OBJ_create (const char * oid, const char * sn, const char * ln)
Definition at line 682 of file obj_dat.c.
References ASN1_OBJECT_free(), NID_undef, NULL, OBJ_add_object(), OBJ_F_OBJ_CREATE, OBJ_ln2nid(), OBJ_new_nid(), OBJ_obj2nid(), OBJ_R_OID_EXISTS, OBJ_sn2nid(), OBJ_txt2obj(), and OBJerr.
OBJ_create_objects()
int OBJ_create_objects (BIO * in)
Definition at line 635 of file obj_dat.c.
OBJ_get0_data()
const unsigned char* OBJ_get0_data (const ASN1_OBJECT * obj)
Definition at line 723 of file obj_dat.c.
References NULL.
Referenced by EVP_CIPHER_type().
OBJ_length()
size_t OBJ_length (const ASN1_OBJECT * obj)
Definition at line 716 of file obj_dat.c.
References NULL.
OBJ_ln2nid()
int OBJ_ln2nid (const char * s)
Definition at line 538 of file obj_dat.c.
References ADDED_LNAME, and NULL.
Referenced by OBJ_create().
OBJ_new_nid()
int OBJ_new_nid (int num)
Definition at line 165 of file obj_dat.c.
Referenced by OBJ_create().
OBJ_nid2ln()
const char* OBJ_nid2ln (int n)
Definition at line 274 of file obj_dat.c.
References NID_undef, and NUM_NID.
Referenced by print_attribs(), and TS_X509_ALGOR_print_bio().
OBJ_nid2obj()
ASN1_OBJECT* OBJ_nid2obj (int n)
Definition at line 220 of file obj_dat.c.
References NID_undef, and NUM_NID.
Referenced by ASN1_item_sign_ctx(), ASN1_sign(), CMS_add_simple_smimecap(), cms_Data_create(), cms_encode_Receipt(), CMS_EncryptedData_set1_key(), CMS_get1_ReceiptRequest(), cms_Receipt_verify(), CMS_sign(), CMS_sign_receipt(), CMS_SignerInfo_verify_content(), EVP_CIPHER_type(), OCSP_accept_responses_new(), OCSP_response_create(), OCSP_url_svcloc_new(), PKCS12_init(), PKCS12_item_pack_safebag(), PKCS12_pack_p7data(), PKCS12_SAFEBAG_create0_p8inf(), PKCS12_SAFEBAG_create0_pkcs8(), PKCS12_setup_mac(), PKCS7_add_attrib_content_type(), PKCS7_add_signer(), PKCS7_set0_type_other(), PKCS7_set_type(), X509_NAME_ENTRY_create_by_NID(), X509_NAME_get_index_by_NID(), X509at_get_attr_by_NID(), and X509v3_get_ext_by_NID().
OBJ_nid2sn()
const char* OBJ_nid2sn (int n)
Definition at line 247 of file obj_dat.c.
References NID_undef, and NUM_NID.
Referenced by ssl_print_groups(), and ssl_print_tmp_key().
OBJ_obj2nid()
int OBJ_obj2nid (const ASN1_OBJECT * a)
Definition at line 317 of file obj_dat.c.
References ADDED_DATA, NID_undef, and NULL.
Referenced by asn1_do_adb(), CMS_data(), CMS_dataFinal(), CMS_dataInit(), CMS_decrypt(), CMS_digest_verify(), cms_DigestAlgorithm_find_ctx(), CMS_EncryptedData_decrypt(), CMS_EncryptedData_set1_key(), CMS_get0_content(), cms_get0_enveloped(), cms_Receipt_verify(), cms_RecipientInfo_pwri_crypt(), EVP_PKCS82PKEY(), level_add_node(), OBJ_create(), OBJ_txt2nid(), OCSP_response_get1_basic(), PKCS12_SAFEBAG_get0_pkcs8(), PKCS12_SAFEBAG_get1_cert(), PKCS12_SAFEBAG_get1_crl(), PKCS12_SAFEBAG_get_bag_nid(), PKCS12_SAFEBAG_get_nid(), PKCS7_add_certificate(), PKCS7_add_crl(), PKCS7_add_recipient_info(), PKCS7_add_signer(), PKCS7_dataFinal(), PKCS7_set_content(), PKCS7_signatureVerify(), PKCS7_stream(), print_attribs(), SMIME_write_CMS(), SMIME_write_PKCS7(), STACK_OF(), TS_X509_ALGOR_print_bio(), X509_ATTRIBUTE_set1_data(), X509_CRL_check_suiteb(), X509_CRL_get_signature_nid(), X509_get_signature_type(), X509_NAME_ENTRY_set_data(), X509_REQ_get_signature_nid(), X509_REQ_print_ex(), X509_signature_print(), X509_supported_extension(), and X509V3_EXT_get().
OBJ_obj2txt()
int OBJ_obj2txt (char * buf, int buf_len, const ASN1_OBJECT * a, int no_name)
Definition at line 394 of file obj_dat.c.
Referenced by TS_OBJ_print_bio().
OBJ_sn2nid()
int OBJ_sn2nid (const char * s)
Definition at line 559 of file obj_dat.c.
References ADDED_SNAME, and NULL.
Referenced by OBJ_create().
OBJ_txt2nid()
int OBJ_txt2nid (const char * s)
Definition at line 528 of file obj_dat.c.
References ASN1_OBJECT_free(), nid, ADDED_OBJ::obj, OBJ_obj2nid(), and OBJ_txt2obj().
Referenced by OCSP_accept_responses_new(), and parse_name().
OBJ_txt2obj()
ASN1_OBJECT* OBJ_txt2obj (const char * s, int no_name)
Definition at line 350 of file obj_dat.c.
References nid, NID_undef, and NULL.
Referenced by OBJ_create(), OBJ_txt2nid(), opt_verify(), X509_ATTRIBUTE_create_by_txt(), and X509_NAME_ENTRY_create_by_txt().