crypto/modes/ocb128.c File Reference
ocb128.c File Reference
#include <string.h>
#include <openssl/crypto.h>
#include "modes_lcl.h"
Functions
OCB128_CONTEXT * CRYPTO_ocb128_new (void *keyenc, void *keydec, block128_f encrypt, block128_f decrypt, ocb128_f stream)
int CRYPTO_ocb128_init (OCB128_CONTEXT *ctx, void *keyenc, void *keydec, block128_f encrypt, block128_f decrypt, ocb128_f stream)
int CRYPTO_ocb128_copy_ctx (OCB128_CONTEXT *dest, OCB128_CONTEXT *src, void *keyenc, void *keydec)
int CRYPTO_ocb128_setiv (OCB128_CONTEXT *ctx, const unsigned char *iv, size_t len, size_t taglen)
int CRYPTO_ocb128_aad (OCB128_CONTEXT *ctx, const unsigned char *aad, size_t len)
int CRYPTO_ocb128_encrypt (OCB128_CONTEXT *ctx, const unsigned char *in, unsigned char *out, size_t len)
int CRYPTO_ocb128_decrypt (OCB128_CONTEXT *ctx, const unsigned char *in, unsigned char *out, size_t len)
int CRYPTO_ocb128_finish (OCB128_CONTEXT *ctx, const unsigned char *tag, size_t len)
int CRYPTO_ocb128_tag (OCB128_CONTEXT *ctx, unsigned char *tag, size_t len)
void CRYPTO_ocb128_cleanup (OCB128_CONTEXT *ctx)
Function Documentation
CRYPTO_ocb128_aad()
int CRYPTO_ocb128_aad (OCB128_CONTEXT * ctx, const unsigned char * aad, size_t len)
Definition at line 272 of file ocb128.c.
CRYPTO_ocb128_cleanup()
void CRYPTO_ocb128_cleanup (OCB128_CONTEXT * ctx)
Definition at line 560 of file ocb128.c.
References OPENSSL_cleanse(), and OPENSSL_clear_free.
CRYPTO_ocb128_copy_ctx()
int CRYPTO_ocb128_copy_ctx (OCB128_CONTEXT * dest, OCB128_CONTEXT * src, void * keyenc, void * keydec)
Definition at line 204 of file ocb128.c.
References NULL, and OPENSSL_malloc.
CRYPTO_ocb128_decrypt()
int CRYPTO_ocb128_decrypt (OCB128_CONTEXT * ctx, const unsigned char * in, unsigned char * out, size_t len)
Definition at line 424 of file ocb128.c.
References NULL.
CRYPTO_ocb128_encrypt()
int CRYPTO_ocb128_encrypt (OCB128_CONTEXT * ctx, const unsigned char * in, unsigned char * out, size_t len)
Definition at line 332 of file ocb128.c.
References NULL.
CRYPTO_ocb128_finish()
int CRYPTO_ocb128_finish (OCB128_CONTEXT * ctx, const unsigned char * tag, size_t len)
Definition at line 515 of file ocb128.c.
References OCB_BLOCK::c, CRYPTO_memcmp(), and ocb_block16_xor.
Referenced by CRYPTO_ocb128_tag().
CRYPTO_ocb128_init()
int CRYPTO_ocb128_init (OCB128_CONTEXT * ctx, void * keyenc, void * keydec, block128_f encrypt, block128_f decrypt, ocb128_f stream)
Definition at line 160 of file ocb128.c.
CRYPTO_ocb128_new()
OCB128_CONTEXT* CRYPTO_ocb128_new (void * keyenc, void * keydec, block128_f encrypt, block128_f decrypt, ocb128_f stream)
Definition at line 139 of file ocb128.c.
CRYPTO_ocb128_setiv()
int CRYPTO_ocb128_setiv (OCB128_CONTEXT * ctx, const unsigned char * iv, size_t len, size_t taglen)
Definition at line 224 of file ocb128.c.
CRYPTO_ocb128_tag()
int CRYPTO_ocb128_tag (OCB128_CONTEXT * ctx, unsigned char * tag, size_t len)
Definition at line 542 of file ocb128.c.
References CRYPTO_ocb128_finish(), and NULL.