crypto/ocsp/ocsp_lib.c File Reference
ocsp_lib.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/x509.h>
#include <openssl/pem.h>
#include <openssl/x509v3.h>
#include <openssl/ocsp.h>
#include "ocsp_lcl.h"
#include <openssl/asn1t.h>
Functions
OCSP_CERTID * OCSP_cert_to_id (const EVP_MD *dgst, const X509 *subject, const X509 *issuer)
OCSP_CERTID * OCSP_cert_id_new (const EVP_MD *dgst, const X509_NAME *issuerName, const ASN1_BIT_STRING *issuerKey, const ASN1_INTEGER *serialNumber)
int OCSP_id_issuer_cmp (OCSP_CERTID *a, OCSP_CERTID *b)
int OCSP_id_cmp (OCSP_CERTID *a, OCSP_CERTID *b)
int OCSP_parse_url (const char *url, char **phost, char **pport, char **ppath, int *pssl)
Function Documentation
OCSP_cert_id_new()
OCSP_CERTID* OCSP_cert_id_new (const EVP_MD * dgst, const X509_NAME * issuerName, const ASN1_BIT_STRING * issuerKey, const ASN1_INTEGER * serialNumber)
Definition at line 41 of file ocsp_lib.c.
References nid, and NULL.
Referenced by OCSP_cert_to_id().
OCSP_cert_to_id()
OCSP_CERTID* OCSP_cert_to_id (const EVP_MD * dgst, const X509 * subject, const X509 * issuer)
Definition at line 22 of file ocsp_lib.c.
References EVP_sha1(), NULL, OCSP_cert_id_new(), X509_get0_pubkey_bitstr(), X509_get0_serialNumber(), X509_get_issuer_name(), and X509_get_subject_name().
OCSP_id_cmp()
int OCSP_id_cmp (OCSP_CERTID * a, OCSP_CERTID * b)
Definition at line 103 of file ocsp_lib.c.
Referenced by OCSP_resp_find().
OCSP_id_issuer_cmp()
int OCSP_id_issuer_cmp (OCSP_CERTID * a, OCSP_CERTID * b)
Definition at line 91 of file ocsp_lib.c.
OCSP_parse_url()
int OCSP_parse_url (const char * url, char ** phost, char ** pport, char ** ppath, int * pssl)
Definition at line 117 of file ocsp_lib.c.