include/openssl/ocsp.h File Reference
ocsp.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/ossl_typ.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/safestack.h>
Macros
#define OCSP_REVOKED_STATUS_NOSTATUS -1
#define OCSP_REVOKED_STATUS_UNSPECIFIED 0
#define OCSP_REVOKED_STATUS_KEYCOMPROMISE 1
#define OCSP_REVOKED_STATUS_CACOMPROMISE 2
#define OCSP_REVOKED_STATUS_AFFILIATIONCHANGED 3
#define OCSP_REVOKED_STATUS_SUPERSEDED 4
#define OCSP_REVOKED_STATUS_CESSATIONOFOPERATION 5
#define OCSP_REVOKED_STATUS_CERTIFICATEHOLD 6
#define OCSP_REVOKED_STATUS_REMOVEFROMCRL 8
#define OCSP_DEFAULT_NONCE_LENGTH 16
#define OCSP_NOCERTS 0x1
#define OCSP_NOINTERN 0x2
#define OCSP_NOSIGS 0x4
#define OCSP_NOCHAIN 0x8
#define OCSP_NOVERIFY 0x10
#define OCSP_NOEXPLICIT 0x20
#define OCSP_NOCASIGN 0x40
#define OCSP_NODELEGATED 0x80
#define OCSP_NOCHECKS 0x100
#define OCSP_TRUSTOTHER 0x200
#define OCSP_RESPID_KEY 0x400
#define OCSP_NOTIME 0x800
#define OCSP_RESPONSE_STATUS_SUCCESSFUL 0
#define OCSP_RESPONSE_STATUS_MALFORMEDREQUEST 1
#define OCSP_RESPONSE_STATUS_INTERNALERROR 2
#define OCSP_RESPONSE_STATUS_TRYLATER 3
#define OCSP_RESPONSE_STATUS_SIGREQUIRED 5
#define OCSP_RESPONSE_STATUS_UNAUTHORIZED 6
#define V_OCSP_RESPID_NAME 0
#define V_OCSP_RESPID_KEY 1
#define V_OCSP_CERTSTATUS_GOOD 0
#define V_OCSP_CERTSTATUS_REVOKED 1
#define V_OCSP_CERTSTATUS_UNKNOWN 2
#define PEM_STRING_OCSP_REQUEST "OCSP REQUEST"
#define PEM_STRING_OCSP_RESPONSE "OCSP RESPONSE"
#define d2i_OCSP_REQUEST_bio(bp, p) ASN1_d2i_bio_of(OCSP_REQUEST,OCSP_REQUEST_new,d2i_OCSP_REQUEST,bp,p)
#define d2i_OCSP_RESPONSE_bio(bp, p) ASN1_d2i_bio_of(OCSP_RESPONSE,OCSP_RESPONSE_new,d2i_OCSP_RESPONSE,bp,p)
#define PEM_read_bio_OCSP_REQUEST(bp, x, cb)
#define PEM_read_bio_OCSP_RESPONSE(bp, x, cb)
#define PEM_write_bio_OCSP_REQUEST(bp, o)
#define PEM_write_bio_OCSP_RESPONSE(bp, o)
#define i2d_OCSP_RESPONSE_bio(bp, o) ASN1_i2d_bio_of(OCSP_RESPONSE,i2d_OCSP_RESPONSE,bp,o)
#define i2d_OCSP_REQUEST_bio(bp, o) ASN1_i2d_bio_of(OCSP_REQUEST,i2d_OCSP_REQUEST,bp,o)
#define OCSP_REQUEST_sign(o, pkey, md)
#define OCSP_BASICRESP_sign(o, pkey, md, d)
#define OCSP_REQUEST_verify(a, r)
#define OCSP_BASICRESP_verify(a, r, d)
#define ASN1_BIT_STRING_digest(data, type, md, len) ASN1_item_digest(ASN1_ITEM_rptr(ASN1_BIT_STRING),type,data,md,len)
#define OCSP_CERTSTATUS_dup(cs)
#define OCSP_F_D2I_OCSP_NONCE 102
#define OCSP_F_OCSP_BASIC_ADD1_STATUS 103
#define OCSP_F_OCSP_BASIC_SIGN 104
#define OCSP_F_OCSP_BASIC_VERIFY 105
#define OCSP_F_OCSP_CERT_ID_NEW 101
#define OCSP_F_OCSP_CHECK_DELEGATED 106
#define OCSP_F_OCSP_CHECK_IDS 107
#define OCSP_F_OCSP_CHECK_ISSUER 108
#define OCSP_F_OCSP_CHECK_VALIDITY 115
#define OCSP_F_OCSP_MATCH_ISSUERID 109
#define OCSP_F_OCSP_PARSE_URL 114
#define OCSP_F_OCSP_REQUEST_SIGN 110
#define OCSP_F_OCSP_REQUEST_VERIFY 116
#define OCSP_F_OCSP_RESPONSE_GET1_BASIC 111
#define OCSP_F_PARSE_HTTP_LINE1 118
#define OCSP_R_CERTIFICATE_VERIFY_ERROR 101
#define OCSP_R_DIGEST_ERR 102
#define OCSP_R_ERROR_IN_NEXTUPDATE_FIELD 122
#define OCSP_R_ERROR_IN_THISUPDATE_FIELD 123
#define OCSP_R_ERROR_PARSING_URL 121
#define OCSP_R_MISSING_OCSPSIGNING_USAGE 103
#define OCSP_R_NEXTUPDATE_BEFORE_THISUPDATE 124
#define OCSP_R_NOT_BASIC_RESPONSE 104
#define OCSP_R_NO_CERTIFICATES_IN_CHAIN 105
#define OCSP_R_NO_RESPONSE_DATA 108
#define OCSP_R_NO_REVOKED_TIME 109
#define OCSP_R_NO_SIGNER_KEY 130
#define OCSP_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE 110
#define OCSP_R_REQUEST_NOT_SIGNED 128
#define OCSP_R_RESPONSE_CONTAINS_NO_REVOCATION_DATA 111
#define OCSP_R_ROOT_CA_NOT_TRUSTED 112
#define OCSP_R_SERVER_RESPONSE_ERROR 114
#define OCSP_R_SERVER_RESPONSE_PARSE_ERROR 115
#define OCSP_R_SIGNATURE_FAILURE 117
#define OCSP_R_SIGNER_CERTIFICATE_NOT_FOUND 118
#define OCSP_R_STATUS_EXPIRED 125
#define OCSP_R_STATUS_NOT_YET_VALID 126
#define OCSP_R_STATUS_TOO_OLD 127
#define OCSP_R_UNKNOWN_MESSAGE_DIGEST 119
#define OCSP_R_UNKNOWN_NID 120
#define OCSP_R_UNSUPPORTED_REQUESTORNAME_TYPE 129
Functions
OCSP_CERTID * OCSP_CERTID_dup (OCSP_CERTID *id)
OCSP_RESPONSE * OCSP_sendreq_bio (BIO *b, const char *path, OCSP_REQUEST *req)
OCSP_REQ_CTX * OCSP_sendreq_new (BIO *io, const char *path, OCSP_REQUEST *req, int maxline)
int OCSP_REQ_CTX_nbio (OCSP_REQ_CTX *rctx)
int OCSP_sendreq_nbio (OCSP_RESPONSE **presp, OCSP_REQ_CTX *rctx)
OCSP_REQ_CTX * OCSP_REQ_CTX_new (BIO *io, int maxline)
void OCSP_REQ_CTX_free (OCSP_REQ_CTX *rctx)
void OCSP_set_max_response_length (OCSP_REQ_CTX *rctx, unsigned long len)
int OCSP_REQ_CTX_i2d (OCSP_REQ_CTX *rctx, const ASN1_ITEM *it, ASN1_VALUE *val)
int OCSP_REQ_CTX_nbio_d2i (OCSP_REQ_CTX *rctx, ASN1_VALUE **pval, const ASN1_ITEM *it)
BIO * OCSP_REQ_CTX_get0_mem_bio (OCSP_REQ_CTX *rctx)
int OCSP_REQ_CTX_http (OCSP_REQ_CTX *rctx, const char *op, const char *path)
int OCSP_REQ_CTX_set1_req (OCSP_REQ_CTX *rctx, OCSP_REQUEST *req)
int OCSP_REQ_CTX_add1_header (OCSP_REQ_CTX *rctx, const char *name, const char *value)
OCSP_CERTID * OCSP_cert_to_id (const EVP_MD *dgst, const X509 *subject, const X509 *issuer)
OCSP_CERTID * OCSP_cert_id_new (const EVP_MD *dgst, const X509_NAME *issuerName, const ASN1_BIT_STRING *issuerKey, const ASN1_INTEGER *serialNumber)
OCSP_ONEREQ * OCSP_request_add0_id (OCSP_REQUEST *req, OCSP_CERTID *cid)
int OCSP_request_add1_nonce (OCSP_REQUEST *req, unsigned char *val, int len)
int OCSP_basic_add1_nonce (OCSP_BASICRESP *resp, unsigned char *val, int len)
int OCSP_check_nonce (OCSP_REQUEST *req, OCSP_BASICRESP *bs)
int OCSP_copy_nonce (OCSP_BASICRESP *resp, OCSP_REQUEST *req)
int OCSP_request_set1_name (OCSP_REQUEST *req, X509_NAME *nm)
int OCSP_request_add1_cert (OCSP_REQUEST *req, X509 *cert)
int OCSP_request_sign (OCSP_REQUEST *req, X509 *signer, EVP_PKEY *key, const EVP_MD *dgst, STACK_OF(X509) *certs, unsigned long flags)
int OCSP_response_status (OCSP_RESPONSE *resp)
OCSP_BASICRESP * OCSP_response_get1_basic (OCSP_RESPONSE *resp)
const ASN1_OCTET_STRING * OCSP_resp_get0_signature (const OCSP_BASICRESP *bs)
int OCSP_resp_count (OCSP_BASICRESP *bs)
OCSP_SINGLERESP * OCSP_resp_get0 (OCSP_BASICRESP *bs, int idx)
const ASN1_GENERALIZEDTIME * OCSP_resp_get0_produced_at (const OCSP_BASICRESP *bs)
const STACK_OF (X509) *OCSP_resp_get0_certs(const OCSP_BASICRESP *bs)
int OCSP_resp_get0_id (const OCSP_BASICRESP *bs, const ASN1_OCTET_STRING **pid, const X509_NAME **pname)
int OCSP_resp_find (OCSP_BASICRESP *bs, OCSP_CERTID *id, int last)
int OCSP_single_get0_status (OCSP_SINGLERESP *single, int *reason, ASN1_GENERALIZEDTIME **revtime, ASN1_GENERALIZEDTIME **thisupd, ASN1_GENERALIZEDTIME **nextupd)
int OCSP_resp_find_status (OCSP_BASICRESP *bs, OCSP_CERTID *id, int *status, int *reason, ASN1_GENERALIZEDTIME **revtime, ASN1_GENERALIZEDTIME **thisupd, ASN1_GENERALIZEDTIME **nextupd)
int OCSP_check_validity (ASN1_GENERALIZEDTIME *thisupd, ASN1_GENERALIZEDTIME *nextupd, long sec, long maxsec)
int OCSP_request_verify (OCSP_REQUEST *req, STACK_OF(X509) *certs, X509_STORE *store, unsigned long flags)
int OCSP_parse_url (const char *url, char **phost, char **pport, char **ppath, int *pssl)
int OCSP_id_issuer_cmp (OCSP_CERTID *a, OCSP_CERTID *b)
int OCSP_id_cmp (OCSP_CERTID *a, OCSP_CERTID *b)
int OCSP_request_onereq_count (OCSP_REQUEST *req)
OCSP_ONEREQ * OCSP_request_onereq_get0 (OCSP_REQUEST *req, int i)
OCSP_CERTID * OCSP_onereq_get0_id (OCSP_ONEREQ *one)
int OCSP_id_get0_info (ASN1_OCTET_STRING **piNameHash, ASN1_OBJECT **pmd, ASN1_OCTET_STRING **pikeyHash, ASN1_INTEGER **pserial, OCSP_CERTID *cid)
int OCSP_request_is_signed (OCSP_REQUEST *req)
OCSP_RESPONSE * OCSP_response_create (int status, OCSP_BASICRESP *bs)
OCSP_SINGLERESP * OCSP_basic_add1_status (OCSP_BASICRESP *rsp, OCSP_CERTID *cid, int status, int reason, ASN1_TIME *revtime, ASN1_TIME *thisupd, ASN1_TIME *nextupd)
int OCSP_basic_add1_cert (OCSP_BASICRESP *resp, X509 *cert)
int OCSP_basic_sign (OCSP_BASICRESP *brsp, X509 *signer, EVP_PKEY *key, const EVP_MD *dgst, STACK_OF(X509) *certs, unsigned long flags)
int OCSP_RESPID_set_by_name (OCSP_RESPID *respid, X509 *cert)
int OCSP_RESPID_set_by_key (OCSP_RESPID *respid, X509 *cert)
int OCSP_RESPID_match (OCSP_RESPID *respid, X509 *cert)
X509_EXTENSION * OCSP_crlID_new (const char *url, long *n, char *tim)
X509_EXTENSION * OCSP_accept_responses_new (char **oids)
X509_EXTENSION * OCSP_archive_cutoff_new (char *tim)
X509_EXTENSION * OCSP_url_svcloc_new (X509_NAME *issuer, const char **urls)
int OCSP_REQUEST_get_ext_count (OCSP_REQUEST *x)
int OCSP_REQUEST_get_ext_by_NID (OCSP_REQUEST *x, int nid, int lastpos)
int OCSP_REQUEST_get_ext_by_OBJ (OCSP_REQUEST *x, const ASN1_OBJECT *obj, int lastpos)
int OCSP_REQUEST_get_ext_by_critical (OCSP_REQUEST *x, int crit, int lastpos)
X509_EXTENSION * OCSP_REQUEST_get_ext (OCSP_REQUEST *x, int loc)
X509_EXTENSION * OCSP_REQUEST_delete_ext (OCSP_REQUEST *x, int loc)
void * OCSP_REQUEST_get1_ext_d2i (OCSP_REQUEST *x, int nid, int *crit, int *idx)
int OCSP_REQUEST_add1_ext_i2d (OCSP_REQUEST *x, int nid, void *value, int crit, unsigned long flags)
int OCSP_REQUEST_add_ext (OCSP_REQUEST *x, X509_EXTENSION *ex, int loc)
int OCSP_ONEREQ_get_ext_count (OCSP_ONEREQ *x)
int OCSP_ONEREQ_get_ext_by_NID (OCSP_ONEREQ *x, int nid, int lastpos)
int OCSP_ONEREQ_get_ext_by_OBJ (OCSP_ONEREQ *x, const ASN1_OBJECT *obj, int lastpos)
int OCSP_ONEREQ_get_ext_by_critical (OCSP_ONEREQ *x, int crit, int lastpos)
X509_EXTENSION * OCSP_ONEREQ_get_ext (OCSP_ONEREQ *x, int loc)
X509_EXTENSION * OCSP_ONEREQ_delete_ext (OCSP_ONEREQ *x, int loc)
void * OCSP_ONEREQ_get1_ext_d2i (OCSP_ONEREQ *x, int nid, int *crit, int *idx)
int OCSP_ONEREQ_add1_ext_i2d (OCSP_ONEREQ *x, int nid, void *value, int crit, unsigned long flags)
int OCSP_ONEREQ_add_ext (OCSP_ONEREQ *x, X509_EXTENSION *ex, int loc)
int OCSP_BASICRESP_get_ext_count (OCSP_BASICRESP *x)
int OCSP_BASICRESP_get_ext_by_NID (OCSP_BASICRESP *x, int nid, int lastpos)
int OCSP_BASICRESP_get_ext_by_OBJ (OCSP_BASICRESP *x, const ASN1_OBJECT *obj, int lastpos)
int OCSP_BASICRESP_get_ext_by_critical (OCSP_BASICRESP *x, int crit, int lastpos)
X509_EXTENSION * OCSP_BASICRESP_get_ext (OCSP_BASICRESP *x, int loc)
X509_EXTENSION * OCSP_BASICRESP_delete_ext (OCSP_BASICRESP *x, int loc)
void * OCSP_BASICRESP_get1_ext_d2i (OCSP_BASICRESP *x, int nid, int *crit, int *idx)
int OCSP_BASICRESP_add1_ext_i2d (OCSP_BASICRESP *x, int nid, void *value, int crit, unsigned long flags)
int OCSP_BASICRESP_add_ext (OCSP_BASICRESP *x, X509_EXTENSION *ex, int loc)
int OCSP_SINGLERESP_get_ext_count (OCSP_SINGLERESP *x)
int OCSP_SINGLERESP_get_ext_by_NID (OCSP_SINGLERESP *x, int nid, int lastpos)
int OCSP_SINGLERESP_get_ext_by_OBJ (OCSP_SINGLERESP *x, const ASN1_OBJECT *obj, int lastpos)
int OCSP_SINGLERESP_get_ext_by_critical (OCSP_SINGLERESP *x, int crit, int lastpos)
X509_EXTENSION * OCSP_SINGLERESP_get_ext (OCSP_SINGLERESP *x, int loc)
X509_EXTENSION * OCSP_SINGLERESP_delete_ext (OCSP_SINGLERESP *x, int loc)
void * OCSP_SINGLERESP_get1_ext_d2i (OCSP_SINGLERESP *x, int nid, int *crit, int *idx)
int OCSP_SINGLERESP_add1_ext_i2d (OCSP_SINGLERESP *x, int nid, void *value, int crit, unsigned long flags)
int OCSP_SINGLERESP_add_ext (OCSP_SINGLERESP *x, X509_EXTENSION *ex, int loc)
const OCSP_CERTID * OCSP_SINGLERESP_get0_id (const OCSP_SINGLERESP *x)
const char * OCSP_response_status_str (long s)
const char * OCSP_cert_status_str (long s)
const char * OCSP_crl_reason_str (long s)
int OCSP_REQUEST_print (BIO *bp, OCSP_REQUEST *a, unsigned long flags)
int OCSP_RESPONSE_print (BIO *bp, OCSP_RESPONSE *o, unsigned long flags)
int OCSP_basic_verify (OCSP_BASICRESP *bs, STACK_OF(X509) *certs, X509_STORE *st, unsigned long flags)
int ERR_load_OCSP_strings (void)
Macro Definition Documentation
ASN1_BIT_STRING_digest
#define ASN1_BIT_STRING_digest (data, type, md, len) ASN1_item_digest(ASN1_ITEM_rptr(ASN1_BIT_STRING),type,data,md,len)
Definition at line 156 of file ocsp.h.
d2i_OCSP_REQUEST_bio
#define d2i_OCSP_REQUEST_bio (bp, p) ASN1_d2i_bio_of(OCSP_REQUEST,OCSP_REQUEST_new,d2i_OCSP_REQUEST,bp,p)
Definition at line 118 of file ocsp.h.
d2i_OCSP_RESPONSE_bio
#define d2i_OCSP_RESPONSE_bio (bp, p) ASN1_d2i_bio_of(OCSP_RESPONSE,OCSP_RESPONSE_new,d2i_OCSP_RESPONSE,bp,p)
Definition at line 120 of file ocsp.h.
i2d_OCSP_REQUEST_bio
#define i2d_OCSP_REQUEST_bio (bp, o) ASN1_i2d_bio_of(OCSP_REQUEST,i2d_OCSP_REQUEST,bp,o)
Definition at line 138 of file ocsp.h.
i2d_OCSP_RESPONSE_bio
#define i2d_OCSP_RESPONSE_bio (bp, o) ASN1_i2d_bio_of(OCSP_RESPONSE,i2d_OCSP_RESPONSE,bp,o)
Definition at line 136 of file ocsp.h.
OCSP_BASICRESP_sign
#define OCSP_BASICRESP_sign (o, pkey, md, d)
Value:
ASN1_item_sign(ASN1_ITEM_rptr(OCSP_RESPDATA),&o->signatureAlgorithm,NULL,\
                o->signature,&o->tbsResponseData,pkey,md)
Definition at line 145 of file ocsp.h.
Referenced by OCSP_basic_sign().
OCSP_BASICRESP_verify
#define OCSP_BASICRESP_verify (a, r, d)
Value:
ASN1_item_verify(ASN1_ITEM_rptr(OCSP_RESPDATA),\
        &a->signatureAlgorithm,a->signature,&a->tbsResponseData,r)
Definition at line 153 of file ocsp.h.
OCSP_CERTSTATUS_dup
#define OCSP_CERTSTATUS_dup (cs)
Value:
(OCSP_CERTSTATUS*)ASN1_dup((int(*)())i2d_OCSP_CERTSTATUS,\
                (char *(*)())d2i_OCSP_CERTSTATUS,(char *)(cs))
Definition at line 159 of file ocsp.h.
OCSP_DEFAULT_NONCE_LENGTH
#define OCSP_DEFAULT_NONCE_LENGTH 16
Definition at line 55 of file ocsp.h.
OCSP_F_D2I_OCSP_NONCE
#define OCSP_F_D2I_OCSP_NONCE 102
Definition at line 364 of file ocsp.h.
OCSP_F_OCSP_BASIC_ADD1_STATUS
#define OCSP_F_OCSP_BASIC_ADD1_STATUS 103
Definition at line 365 of file ocsp.h.
Referenced by OCSP_basic_add1_status().
OCSP_F_OCSP_BASIC_SIGN
#define OCSP_F_OCSP_BASIC_SIGN 104
Definition at line 366 of file ocsp.h.
Referenced by OCSP_basic_sign().
OCSP_F_OCSP_BASIC_VERIFY
#define OCSP_F_OCSP_BASIC_VERIFY 105
Definition at line 367 of file ocsp.h.
OCSP_F_OCSP_CERT_ID_NEW
#define OCSP_F_OCSP_CERT_ID_NEW 101
Definition at line 368 of file ocsp.h.
OCSP_F_OCSP_CHECK_DELEGATED
#define OCSP_F_OCSP_CHECK_DELEGATED 106
Definition at line 369 of file ocsp.h.
OCSP_F_OCSP_CHECK_IDS
#define OCSP_F_OCSP_CHECK_IDS 107
Definition at line 370 of file ocsp.h.
OCSP_F_OCSP_CHECK_ISSUER
#define OCSP_F_OCSP_CHECK_ISSUER 108
Definition at line 371 of file ocsp.h.
OCSP_F_OCSP_CHECK_VALIDITY
#define OCSP_F_OCSP_CHECK_VALIDITY 115
Definition at line 372 of file ocsp.h.
OCSP_F_OCSP_MATCH_ISSUERID
#define OCSP_F_OCSP_MATCH_ISSUERID 109
Definition at line 373 of file ocsp.h.
OCSP_F_OCSP_PARSE_URL
#define OCSP_F_OCSP_PARSE_URL 114
Definition at line 374 of file ocsp.h.
OCSP_F_OCSP_REQUEST_SIGN
#define OCSP_F_OCSP_REQUEST_SIGN 110
Definition at line 375 of file ocsp.h.
Referenced by OCSP_request_sign().
OCSP_F_OCSP_REQUEST_VERIFY
#define OCSP_F_OCSP_REQUEST_VERIFY 116
Definition at line 376 of file ocsp.h.
Referenced by OCSP_request_verify().
OCSP_F_OCSP_RESPONSE_GET1_BASIC
#define OCSP_F_OCSP_RESPONSE_GET1_BASIC 111
Definition at line 377 of file ocsp.h.
Referenced by OCSP_response_get1_basic().
OCSP_F_PARSE_HTTP_LINE1
#define OCSP_F_PARSE_HTTP_LINE1 118
Definition at line 378 of file ocsp.h.
OCSP_NOCASIGN
#define OCSP_NOCASIGN 0x40
Definition at line 63 of file ocsp.h.
OCSP_NOCERTS
#define OCSP_NOCERTS 0x1
Definition at line 57 of file ocsp.h.
Referenced by OCSP_basic_sign(), and OCSP_request_sign().
OCSP_NOCHAIN
#define OCSP_NOCHAIN 0x8
Definition at line 60 of file ocsp.h.
OCSP_NOCHECKS
#define OCSP_NOCHECKS 0x100
Definition at line 65 of file ocsp.h.
OCSP_NODELEGATED
#define OCSP_NODELEGATED 0x80
Definition at line 64 of file ocsp.h.
OCSP_NOEXPLICIT
#define OCSP_NOEXPLICIT 0x20
Definition at line 62 of file ocsp.h.
OCSP_NOINTERN
#define OCSP_NOINTERN 0x2
Definition at line 58 of file ocsp.h.
OCSP_NOSIGS
#define OCSP_NOSIGS 0x4
Definition at line 59 of file ocsp.h.
OCSP_NOTIME
#define OCSP_NOTIME 0x800
Definition at line 68 of file ocsp.h.
Referenced by OCSP_basic_sign().
OCSP_NOVERIFY
#define OCSP_NOVERIFY 0x10
Definition at line 61 of file ocsp.h.
OCSP_R_CERTIFICATE_VERIFY_ERROR
#define OCSP_R_CERTIFICATE_VERIFY_ERROR 101
Definition at line 381 of file ocsp.h.
OCSP_R_DIGEST_ERR
#define OCSP_R_DIGEST_ERR 102
Definition at line 382 of file ocsp.h.
OCSP_R_ERROR_IN_NEXTUPDATE_FIELD
#define OCSP_R_ERROR_IN_NEXTUPDATE_FIELD 122
Definition at line 383 of file ocsp.h.
OCSP_R_ERROR_IN_THISUPDATE_FIELD
#define OCSP_R_ERROR_IN_THISUPDATE_FIELD 123
Definition at line 384 of file ocsp.h.
OCSP_R_ERROR_PARSING_URL
#define OCSP_R_ERROR_PARSING_URL 121
Definition at line 385 of file ocsp.h.
OCSP_R_MISSING_OCSPSIGNING_USAGE
#define OCSP_R_MISSING_OCSPSIGNING_USAGE 103
Definition at line 386 of file ocsp.h.
OCSP_R_NEXTUPDATE_BEFORE_THISUPDATE
#define OCSP_R_NEXTUPDATE_BEFORE_THISUPDATE 124
Definition at line 387 of file ocsp.h.
OCSP_R_NO_CERTIFICATES_IN_CHAIN
#define OCSP_R_NO_CERTIFICATES_IN_CHAIN 105
Definition at line 389 of file ocsp.h.
OCSP_R_NO_RESPONSE_DATA
#define OCSP_R_NO_RESPONSE_DATA 108
Definition at line 390 of file ocsp.h.
Referenced by OCSP_response_get1_basic().
OCSP_R_NO_REVOKED_TIME
#define OCSP_R_NO_REVOKED_TIME 109
Definition at line 391 of file ocsp.h.
Referenced by OCSP_basic_add1_status().
OCSP_R_NO_SIGNER_KEY
#define OCSP_R_NO_SIGNER_KEY 130
Definition at line 392 of file ocsp.h.
OCSP_R_NOT_BASIC_RESPONSE
#define OCSP_R_NOT_BASIC_RESPONSE 104
Definition at line 388 of file ocsp.h.
Referenced by OCSP_response_get1_basic().
OCSP_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE
#define OCSP_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE 110
Definition at line 393 of file ocsp.h.
Referenced by OCSP_basic_sign(), and OCSP_request_sign().
OCSP_R_REQUEST_NOT_SIGNED
#define OCSP_R_REQUEST_NOT_SIGNED 128
Definition at line 394 of file ocsp.h.
Referenced by OCSP_request_verify().
OCSP_R_RESPONSE_CONTAINS_NO_REVOCATION_DATA
#define OCSP_R_RESPONSE_CONTAINS_NO_REVOCATION_DATA 111
Definition at line 395 of file ocsp.h.
OCSP_R_ROOT_CA_NOT_TRUSTED
#define OCSP_R_ROOT_CA_NOT_TRUSTED 112
Definition at line 396 of file ocsp.h.
OCSP_R_SERVER_RESPONSE_ERROR
#define OCSP_R_SERVER_RESPONSE_ERROR 114
Definition at line 397 of file ocsp.h.
OCSP_R_SERVER_RESPONSE_PARSE_ERROR
#define OCSP_R_SERVER_RESPONSE_PARSE_ERROR 115
Definition at line 398 of file ocsp.h.
OCSP_R_SIGNATURE_FAILURE
#define OCSP_R_SIGNATURE_FAILURE 117
Definition at line 399 of file ocsp.h.
OCSP_R_SIGNER_CERTIFICATE_NOT_FOUND
#define OCSP_R_SIGNER_CERTIFICATE_NOT_FOUND 118
Definition at line 400 of file ocsp.h.
OCSP_R_STATUS_EXPIRED
#define OCSP_R_STATUS_EXPIRED 125
Definition at line 401 of file ocsp.h.
OCSP_R_STATUS_NOT_YET_VALID
#define OCSP_R_STATUS_NOT_YET_VALID 126
Definition at line 402 of file ocsp.h.
OCSP_R_STATUS_TOO_OLD
#define OCSP_R_STATUS_TOO_OLD 127
Definition at line 403 of file ocsp.h.
OCSP_R_UNKNOWN_MESSAGE_DIGEST
#define OCSP_R_UNKNOWN_MESSAGE_DIGEST 119
Definition at line 404 of file ocsp.h.
OCSP_R_UNKNOWN_NID
#define OCSP_R_UNKNOWN_NID 120
Definition at line 405 of file ocsp.h.
OCSP_R_UNSUPPORTED_REQUESTORNAME_TYPE
#define OCSP_R_UNSUPPORTED_REQUESTORNAME_TYPE 129
Definition at line 406 of file ocsp.h.
Referenced by OCSP_request_verify().
OCSP_REQUEST_sign
#define OCSP_REQUEST_sign (o, pkey, md)
Value:
ASN1_item_sign(ASN1_ITEM_rptr(OCSP_REQINFO),\
                &o->optionalSignature->signatureAlgorithm,NULL,\
                o->optionalSignature->signature,&o->tbsRequest,pkey,md)
Definition at line 140 of file ocsp.h.
Referenced by OCSP_request_sign().
OCSP_REQUEST_verify
#define OCSP_REQUEST_verify (a, r)
Value:
ASN1_item_verify(ASN1_ITEM_rptr(OCSP_REQINFO),\
        &a->optionalSignature->signatureAlgorithm,\
        a->optionalSignature->signature,&a->tbsRequest,r)
Definition at line 149 of file ocsp.h.
OCSP_RESPID_KEY
#define OCSP_RESPID_KEY 0x400
Definition at line 67 of file ocsp.h.
Referenced by OCSP_basic_sign().
OCSP_RESPONSE_STATUS_INTERNALERROR
#define OCSP_RESPONSE_STATUS_INTERNALERROR 2
Definition at line 84 of file ocsp.h.
Referenced by OCSP_response_status_str().
OCSP_RESPONSE_STATUS_MALFORMEDREQUEST
#define OCSP_RESPONSE_STATUS_MALFORMEDREQUEST 1
Definition at line 83 of file ocsp.h.
Referenced by OCSP_response_status_str().
OCSP_RESPONSE_STATUS_SIGREQUIRED
#define OCSP_RESPONSE_STATUS_SIGREQUIRED 5
Definition at line 86 of file ocsp.h.
Referenced by OCSP_response_status_str().
OCSP_RESPONSE_STATUS_SUCCESSFUL
#define OCSP_RESPONSE_STATUS_SUCCESSFUL 0
Definition at line 82 of file ocsp.h.
Referenced by OCSP_response_status_str().
OCSP_RESPONSE_STATUS_TRYLATER
#define OCSP_RESPONSE_STATUS_TRYLATER 3
Definition at line 85 of file ocsp.h.
Referenced by OCSP_response_status_str().
OCSP_RESPONSE_STATUS_UNAUTHORIZED
#define OCSP_RESPONSE_STATUS_UNAUTHORIZED 6
Definition at line 87 of file ocsp.h.
Referenced by OCSP_response_status_str().
OCSP_REVOKED_STATUS_AFFILIATIONCHANGED
#define OCSP_REVOKED_STATUS_AFFILIATIONCHANGED 3
Definition at line 35 of file ocsp.h.
Referenced by OCSP_crl_reason_str().
OCSP_REVOKED_STATUS_CACOMPROMISE
#define OCSP_REVOKED_STATUS_CACOMPROMISE 2
Definition at line 34 of file ocsp.h.
Referenced by OCSP_crl_reason_str().
OCSP_REVOKED_STATUS_CERTIFICATEHOLD
#define OCSP_REVOKED_STATUS_CERTIFICATEHOLD 6
Definition at line 38 of file ocsp.h.
Referenced by OCSP_crl_reason_str().
OCSP_REVOKED_STATUS_CESSATIONOFOPERATION
#define OCSP_REVOKED_STATUS_CESSATIONOFOPERATION 5
Definition at line 37 of file ocsp.h.
Referenced by OCSP_crl_reason_str().
OCSP_REVOKED_STATUS_KEYCOMPROMISE
#define OCSP_REVOKED_STATUS_KEYCOMPROMISE 1
Definition at line 33 of file ocsp.h.
Referenced by OCSP_crl_reason_str().
OCSP_REVOKED_STATUS_NOSTATUS
#define OCSP_REVOKED_STATUS_NOSTATUS -1
Definition at line 31 of file ocsp.h.
Referenced by OCSP_basic_add1_status().
OCSP_REVOKED_STATUS_REMOVEFROMCRL
#define OCSP_REVOKED_STATUS_REMOVEFROMCRL 8
Definition at line 39 of file ocsp.h.
Referenced by OCSP_crl_reason_str().
OCSP_REVOKED_STATUS_SUPERSEDED
#define OCSP_REVOKED_STATUS_SUPERSEDED 4
Definition at line 36 of file ocsp.h.
Referenced by OCSP_crl_reason_str().
OCSP_REVOKED_STATUS_UNSPECIFIED
#define OCSP_REVOKED_STATUS_UNSPECIFIED 0
Definition at line 32 of file ocsp.h.
Referenced by OCSP_crl_reason_str().
OCSP_TRUSTOTHER
#define OCSP_TRUSTOTHER 0x200
Definition at line 66 of file ocsp.h.
PEM_read_bio_OCSP_REQUEST
#define PEM_read_bio_OCSP_REQUEST (bp, x, cb)
Value:
(OCSP_REQUEST *)PEM_ASN1_read_bio(\
     (char *(*)())d2i_OCSP_REQUEST,PEM_STRING_OCSP_REQUEST,bp,(char **)x,cb,NULL)
Definition at line 122 of file ocsp.h.
PEM_read_bio_OCSP_RESPONSE
#define PEM_read_bio_OCSP_RESPONSE (bp, x, cb)
Value:
(OCSP_RESPONSE *)PEM_ASN1_read_bio(\
     (char *(*)())d2i_OCSP_RESPONSE,PEM_STRING_OCSP_RESPONSE,bp,(char **)x,cb,NULL)
Definition at line 125 of file ocsp.h.
PEM_STRING_OCSP_REQUEST
#define PEM_STRING_OCSP_REQUEST "OCSP REQUEST"
Definition at line 115 of file ocsp.h.
PEM_STRING_OCSP_RESPONSE
#define PEM_STRING_OCSP_RESPONSE "OCSP RESPONSE"
Definition at line 116 of file ocsp.h.
PEM_write_bio_OCSP_REQUEST
#define PEM_write_bio_OCSP_REQUEST (bp, o)
Value:
PEM_ASN1_write_bio((int (*)())i2d_OCSP_REQUEST,PEM_STRING_OCSP_REQUEST,\
                        bp,(char *)o, NULL,NULL,0,NULL,NULL)
Definition at line 128 of file ocsp.h.
PEM_write_bio_OCSP_RESPONSE
#define PEM_write_bio_OCSP_RESPONSE (bp, o)
Value:
PEM_ASN1_write_bio((int (*)())i2d_OCSP_RESPONSE,PEM_STRING_OCSP_RESPONSE,\
                        bp,(char *)o, NULL,NULL,0,NULL,NULL)
Definition at line 132 of file ocsp.h.
V_OCSP_CERTSTATUS_GOOD
#define V_OCSP_CERTSTATUS_GOOD 0
Definition at line 99 of file ocsp.h.
Referenced by OCSP_basic_add1_status(), and OCSP_cert_status_str().
V_OCSP_CERTSTATUS_REVOKED
#define V_OCSP_CERTSTATUS_REVOKED 1
Definition at line 100 of file ocsp.h.
Referenced by OCSP_basic_add1_status(), and OCSP_cert_status_str().
V_OCSP_CERTSTATUS_UNKNOWN
#define V_OCSP_CERTSTATUS_UNKNOWN 2
Definition at line 101 of file ocsp.h.
Referenced by OCSP_basic_add1_status(), and OCSP_cert_status_str().
V_OCSP_RESPID_KEY
#define V_OCSP_RESPID_KEY 1
Definition at line 92 of file ocsp.h.
Referenced by OCSP_resp_get0_id().
V_OCSP_RESPID_NAME
#define V_OCSP_RESPID_NAME 0
Definition at line 91 of file ocsp.h.
Referenced by OCSP_resp_get0_id().
Function Documentation
ERR_load_OCSP_strings()
int ERR_load_OCSP_strings (void)
Definition at line 81 of file ocsp_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
OCSP_accept_responses_new()
X509_EXTENSION* OCSP_accept_responses_new (char ** oids)
Definition at line 392 of file ocsp_ext.c.
References ASN1_OBJECT_free(), nid, NID_id_pkix_OCSP_acceptableResponses, NID_undef, NULL, OBJ_nid2obj(), OBJ_txt2nid(), STACK_OF, and X509V3_EXT_i2d().
OCSP_archive_cutoff_new()
X509_EXTENSION* OCSP_archive_cutoff_new (char * tim)
Definition at line 413 of file ocsp_ext.c.
References ASN1_GENERALIZEDTIME_set_string(), NID_id_pkix_OCSP_archiveCutoff, NULL, and X509V3_EXT_i2d().
OCSP_basic_add1_cert()
int OCSP_basic_add1_cert (OCSP_BASICRESP * resp, X509 * cert)
Definition at line 159 of file ocsp_srv.c.
Referenced by OCSP_basic_sign().
OCSP_basic_add1_nonce()
int OCSP_basic_add1_nonce (OCSP_BASICRESP * resp, unsigned char * val, int len)
Definition at line 289 of file ocsp_ext.c.
OCSP_basic_add1_status()
OCSP_SINGLERESP* OCSP_basic_add1_status (OCSP_BASICRESP * rsp, OCSP_CERTID * cid, int status, int reason, ASN1_TIME * revtime, ASN1_TIME * thisupd, ASN1_TIME * nextupd)
Definition at line 86 of file ocsp_srv.c.
References ASN1_ENUMERATED_set(), ASN1_TIME_to_generalizedtime(), NULL, OCSP_CERTID_dup(), OCSP_F_OCSP_BASIC_ADD1_STATUS, OCSP_R_NO_REVOKED_TIME, OCSP_REVOKED_STATUS_NOSTATUS, OCSPerr, V_OCSP_CERTSTATUS_GOOD, V_OCSP_CERTSTATUS_REVOKED, and V_OCSP_CERTSTATUS_UNKNOWN.
OCSP_basic_sign()
int OCSP_basic_sign (OCSP_BASICRESP * brsp, X509 * signer, EVP_PKEY * key, const EVP_MD * dgst, STACK_OF(X509) * certs, unsigned long flags)
Definition at line 171 of file ocsp_srv.c.
References OCSP_basic_add1_cert(), OCSP_BASICRESP_sign, OCSP_F_OCSP_BASIC_SIGN, OCSP_NOCERTS, OCSP_NOTIME, OCSP_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE, OCSP_RESPID_KEY, OCSP_RESPID_set_by_key(), OCSP_RESPID_set_by_name(), OCSPerr, X509_check_private_key(), and X509_gmtime_adj().
OCSP_basic_verify()
int OCSP_basic_verify (OCSP_BASICRESP * bs, STACK_OF(X509) * certs, X509_STORE * st, unsigned long flags)
Definition at line 30 of file ocsp_vfy.c.
References ctx, NULL, and STACK_OF.
OCSP_BASICRESP_add1_ext_i2d()
int OCSP_BASICRESP_add1_ext_i2d (OCSP_BASICRESP * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 170 of file ocsp_ext.c.
References X509V3_add1_i2d().
OCSP_BASICRESP_add_ext()
int OCSP_BASICRESP_add_ext (OCSP_BASICRESP * x, X509_EXTENSION * ex, int loc)
Definition at line 177 of file ocsp_ext.c.
References NULL.
Referenced by OCSP_copy_nonce().
OCSP_BASICRESP_delete_ext()
X509_EXTENSION* OCSP_BASICRESP_delete_ext (OCSP_BASICRESP * x, int loc)
Definition at line 158 of file ocsp_ext.c.
References X509v3_delete_ext().
OCSP_BASICRESP_get1_ext_d2i()
void* OCSP_BASICRESP_get1_ext_d2i (OCSP_BASICRESP * x, int nid, int * crit, int * idx)
Definition at line 163 of file ocsp_ext.c.
OCSP_BASICRESP_get_ext()
X509_EXTENSION* OCSP_BASICRESP_get_ext (OCSP_BASICRESP * x, int loc)
Definition at line 153 of file ocsp_ext.c.
References X509v3_get_ext().
Referenced by OCSP_check_nonce().
OCSP_BASICRESP_get_ext_by_critical()
int OCSP_BASICRESP_get_ext_by_critical (OCSP_BASICRESP * x, int crit, int lastpos)
Definition at line 146 of file ocsp_ext.c.
References X509v3_get_ext_by_critical().
OCSP_BASICRESP_get_ext_by_NID()
int OCSP_BASICRESP_get_ext_by_NID (OCSP_BASICRESP * x, int nid, int lastpos)
Definition at line 133 of file ocsp_ext.c.
References X509v3_get_ext_by_NID().
Referenced by OCSP_check_nonce().
OCSP_BASICRESP_get_ext_by_OBJ()
int OCSP_BASICRESP_get_ext_by_OBJ (OCSP_BASICRESP * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 139 of file ocsp_ext.c.
References X509v3_get_ext_by_OBJ().
OCSP_BASICRESP_get_ext_count()
int OCSP_BASICRESP_get_ext_count (OCSP_BASICRESP * x)
Definition at line 128 of file ocsp_ext.c.
References X509v3_get_ext_count().
OCSP_cert_id_new()
OCSP_CERTID* OCSP_cert_id_new (const EVP_MD * dgst, const X509_NAME * issuerName, const ASN1_BIT_STRING * issuerKey, const ASN1_INTEGER * serialNumber)
Definition at line 41 of file ocsp_lib.c.
References nid, and NULL.
Referenced by OCSP_cert_to_id().
OCSP_cert_status_str()
const char* OCSP_cert_status_str (long s)
Definition at line 62 of file ocsp_prn.c.
References table2string, V_OCSP_CERTSTATUS_GOOD, V_OCSP_CERTSTATUS_REVOKED, and V_OCSP_CERTSTATUS_UNKNOWN.
OCSP_cert_to_id()
OCSP_CERTID* OCSP_cert_to_id (const EVP_MD * dgst, const X509 * subject, const X509 * issuer)
Definition at line 22 of file ocsp_lib.c.
References EVP_sha1(), NULL, OCSP_cert_id_new(), X509_get0_pubkey_bitstr(), X509_get0_serialNumber(), X509_get_issuer_name(), and X509_get_subject_name().
OCSP_CERTID_dup()
OCSP_CERTID* OCSP_CERTID_dup (OCSP_CERTID * id)
Referenced by OCSP_basic_add1_status().
OCSP_check_nonce()
int OCSP_check_nonce (OCSP_REQUEST * req, OCSP_BASICRESP * bs)
Definition at line 309 of file ocsp_ext.c.
References ASN1_OCTET_STRING_cmp(), NID_id_pkix_OCSP_Nonce, OCSP_BASICRESP_get_ext(), OCSP_BASICRESP_get_ext_by_NID(), OCSP_REQUEST_get_ext(), OCSP_REQUEST_get_ext_by_NID(), and X509_EXTENSION_get_data().
OCSP_check_validity()
int OCSP_check_validity (ASN1_GENERALIZEDTIME * thisupd, ASN1_GENERALIZEDTIME * nextupd, long sec, long maxsec)
Definition at line 307 of file ocsp_cl.c.
OCSP_copy_nonce()
int OCSP_copy_nonce (OCSP_BASICRESP * resp, OCSP_REQUEST * req)
Definition at line 347 of file ocsp_ext.c.
References NID_id_pkix_OCSP_Nonce, OCSP_BASICRESP_add_ext(), OCSP_REQUEST_get_ext(), and OCSP_REQUEST_get_ext_by_NID().
OCSP_crl_reason_str()
const char* OCSP_crl_reason_str (long s)
Definition at line 72 of file ocsp_prn.c.
References OCSP_REVOKED_STATUS_AFFILIATIONCHANGED, OCSP_REVOKED_STATUS_CACOMPROMISE, OCSP_REVOKED_STATUS_CERTIFICATEHOLD, OCSP_REVOKED_STATUS_CESSATIONOFOPERATION, OCSP_REVOKED_STATUS_KEYCOMPROMISE, OCSP_REVOKED_STATUS_REMOVEFROMCRL, OCSP_REVOKED_STATUS_SUPERSEDED, OCSP_REVOKED_STATUS_UNSPECIFIED, and table2string.
OCSP_crlID_new()
X509_EXTENSION* OCSP_crlID_new (const char * url, long * n, char * tim)
Definition at line 360 of file ocsp_ext.c.
References ASN1_GENERALIZEDTIME_set_string(), ASN1_INTEGER_set(), ASN1_STRING_set(), NID_id_pkix_OCSP_CrlID, NULL, and X509V3_EXT_i2d().
OCSP_id_cmp()
int OCSP_id_cmp (OCSP_CERTID * a, OCSP_CERTID * b)
Definition at line 103 of file ocsp_lib.c.
Referenced by OCSP_resp_find().
OCSP_id_get0_info()
int OCSP_id_get0_info (ASN1_OCTET_STRING ** piNameHash, ASN1_OBJECT ** pmd, ASN1_OCTET_STRING ** pikeyHash, ASN1_INTEGER ** pserial, OCSP_CERTID * cid)
Definition at line 39 of file ocsp_srv.c.
OCSP_id_issuer_cmp()
int OCSP_id_issuer_cmp (OCSP_CERTID * a, OCSP_CERTID * b)
Definition at line 91 of file ocsp_lib.c.
OCSP_ONEREQ_add1_ext_i2d()
int OCSP_ONEREQ_add1_ext_i2d (OCSP_ONEREQ * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 114 of file ocsp_ext.c.
References X509V3_add1_i2d().
OCSP_ONEREQ_add_ext()
int OCSP_ONEREQ_add_ext (OCSP_ONEREQ * x, X509_EXTENSION * ex, int loc)
Definition at line 121 of file ocsp_ext.c.
References NULL.
OCSP_ONEREQ_delete_ext()
X509_EXTENSION* OCSP_ONEREQ_delete_ext (OCSP_ONEREQ * x, int loc)
Definition at line 104 of file ocsp_ext.c.
References X509v3_delete_ext().
OCSP_onereq_get0_id()
OCSP_CERTID* OCSP_onereq_get0_id (OCSP_ONEREQ * one)
Definition at line 34 of file ocsp_srv.c.
OCSP_ONEREQ_get1_ext_d2i()
void* OCSP_ONEREQ_get1_ext_d2i (OCSP_ONEREQ * x, int nid, int * crit, int * idx)
Definition at line 109 of file ocsp_ext.c.
OCSP_ONEREQ_get_ext()
X509_EXTENSION* OCSP_ONEREQ_get_ext (OCSP_ONEREQ * x, int loc)
Definition at line 99 of file ocsp_ext.c.
References X509v3_get_ext().
OCSP_ONEREQ_get_ext_by_critical()
int OCSP_ONEREQ_get_ext_by_critical (OCSP_ONEREQ * x, int crit, int lastpos)
Definition at line 93 of file ocsp_ext.c.
References X509v3_get_ext_by_critical().
OCSP_ONEREQ_get_ext_by_NID()
int OCSP_ONEREQ_get_ext_by_NID (OCSP_ONEREQ * x, int nid, int lastpos)
Definition at line 82 of file ocsp_ext.c.
References X509v3_get_ext_by_NID().
OCSP_ONEREQ_get_ext_by_OBJ()
int OCSP_ONEREQ_get_ext_by_OBJ (OCSP_ONEREQ * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 87 of file ocsp_ext.c.
References X509v3_get_ext_by_OBJ().
OCSP_ONEREQ_get_ext_count()
int OCSP_ONEREQ_get_ext_count (OCSP_ONEREQ * x)
Definition at line 77 of file ocsp_ext.c.
References X509v3_get_ext_count().
OCSP_parse_url()
int OCSP_parse_url (const char * url, char ** phost, char ** pport, char ** ppath, int * pssl)
Definition at line 117 of file ocsp_lib.c.
OCSP_REQ_CTX_add1_header()
int OCSP_REQ_CTX_add1_header (OCSP_REQ_CTX * rctx, const char * name, const char * value)
Definition at line 160 of file ocsp_ht.c.
References BIO_puts(), BIO_write(), and OHS_HTTP_HEADER.
OCSP_REQ_CTX_free()
void OCSP_REQ_CTX_free (OCSP_REQ_CTX * rctx)
Definition at line 86 of file ocsp_ht.c.
References BIO_free(), and OPENSSL_free.
Referenced by OCSP_REQ_CTX_new(), OCSP_sendreq_bio(), and OCSP_sendreq_new().
OCSP_REQ_CTX_get0_mem_bio()
BIO* OCSP_REQ_CTX_get0_mem_bio (OCSP_REQ_CTX * rctx)
Definition at line 95 of file ocsp_ht.c.
OCSP_REQ_CTX_http()
int OCSP_REQ_CTX_http (OCSP_REQ_CTX * rctx, const char * op, const char * path)
Definition at line 141 of file ocsp_ht.c.
References BIO_printf(), and OHS_HTTP_HEADER.
Referenced by OCSP_sendreq_new().
OCSP_REQ_CTX_i2d()
int OCSP_REQ_CTX_i2d (OCSP_REQ_CTX * rctx, const ASN1_ITEM * it, ASN1_VALUE * val)
Definition at line 108 of file ocsp_ht.c.
References ASN1_item_i2d(), ASN1_item_i2d_bio(), BIO_printf(), NULL, and OHS_ASN1_WRITE_INIT.
Referenced by OCSP_REQ_CTX_set1_req().
OCSP_REQ_CTX_nbio()
int OCSP_REQ_CTX_nbio (OCSP_REQ_CTX * rctx)
Definition at line 272 of file ocsp_ht.c.
References BIO_flush, BIO_get_mem_data, BIO_gets(), BIO_read(), BIO_reset, BIO_should_retry, BIO_write(), NULL, OHS_ASN1_FLUSH, OHS_ASN1_WRITE, OHS_ASN1_WRITE_INIT, OHS_ERROR, OHS_FIRSTLINE, OHS_HEADERS, OHS_HTTP_HEADER, and OHS_NOREAD.
Referenced by OCSP_REQ_CTX_nbio_d2i().
OCSP_REQ_CTX_nbio_d2i()
int OCSP_REQ_CTX_nbio_d2i (OCSP_REQ_CTX * rctx, ASN1_VALUE ** pval, const ASN1_ITEM * it)
Definition at line 122 of file ocsp_ht.c.
References ASN1_item_d2i(), BIO_get_mem_data, len, NULL, OCSP_REQ_CTX_nbio(), and OHS_ERROR.
Referenced by OCSP_sendreq_nbio(), X509_CRL_http_nbio(), and X509_http_nbio().
OCSP_REQ_CTX_new()
OCSP_REQ_CTX* OCSP_REQ_CTX_new (BIO * io, int maxline)
Definition at line 64 of file ocsp_ht.c.
References BIO_new(), BIO_s_mem(), OCSP_REQ_CTX::io, NULL, OCSP_MAX_LINE_LEN, OCSP_MAX_RESP_LENGTH, OCSP_REQ_CTX_free(), OHS_ERROR, OPENSSL_malloc, and OPENSSL_zalloc.
Referenced by OCSP_sendreq_new().
OCSP_REQ_CTX_set1_req()
int OCSP_REQ_CTX_set1_req (OCSP_REQ_CTX * rctx, OCSP_REQUEST * req)
Definition at line 154 of file ocsp_ht.c.
References ASN1_ITEM_rptr, and OCSP_REQ_CTX_i2d().
Referenced by OCSP_sendreq_new().
OCSP_request_add0_id()
OCSP_ONEREQ* OCSP_request_add0_id (OCSP_REQUEST * req, OCSP_CERTID * cid)
Definition at line 30 of file ocsp_cl.c.
References NULL.
OCSP_request_add1_cert()
int OCSP_request_add1_cert (OCSP_REQUEST * req, X509 * cert)
Definition at line 69 of file ocsp_cl.c.
Referenced by OCSP_request_sign().
OCSP_REQUEST_add1_ext_i2d()
int OCSP_REQUEST_add1_ext_i2d (OCSP_REQUEST * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 62 of file ocsp_ext.c.
References X509V3_add1_i2d().
OCSP_request_add1_nonce()
int OCSP_request_add1_nonce (OCSP_REQUEST * req, unsigned char * val, int len)
Definition at line 282 of file ocsp_ext.c.
OCSP_REQUEST_add_ext()
int OCSP_REQUEST_add_ext (OCSP_REQUEST * x, X509_EXTENSION * ex, int loc)
Definition at line 69 of file ocsp_ext.c.
References NULL.
OCSP_REQUEST_delete_ext()
X509_EXTENSION* OCSP_REQUEST_delete_ext (OCSP_REQUEST * x, int loc)
Definition at line 52 of file ocsp_ext.c.
References X509v3_delete_ext().
OCSP_REQUEST_get1_ext_d2i()
void* OCSP_REQUEST_get1_ext_d2i (OCSP_REQUEST * x, int nid, int * crit, int * idx)
Definition at line 57 of file ocsp_ext.c.
OCSP_REQUEST_get_ext()
X509_EXTENSION* OCSP_REQUEST_get_ext (OCSP_REQUEST * x, int loc)
Definition at line 47 of file ocsp_ext.c.
References X509v3_get_ext().
Referenced by OCSP_check_nonce(), and OCSP_copy_nonce().
OCSP_REQUEST_get_ext_by_critical()
int OCSP_REQUEST_get_ext_by_critical (OCSP_REQUEST * x, int crit, int lastpos)
Definition at line 41 of file ocsp_ext.c.
References X509v3_get_ext_by_critical().
OCSP_REQUEST_get_ext_by_NID()
int OCSP_REQUEST_get_ext_by_NID (OCSP_REQUEST * x, int nid, int lastpos)
Definition at line 28 of file ocsp_ext.c.
References X509v3_get_ext_by_NID().
Referenced by OCSP_check_nonce(), and OCSP_copy_nonce().
OCSP_REQUEST_get_ext_by_OBJ()
int OCSP_REQUEST_get_ext_by_OBJ (OCSP_REQUEST * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 34 of file ocsp_ext.c.
References X509v3_get_ext_by_OBJ().
OCSP_REQUEST_get_ext_count()
int OCSP_REQUEST_get_ext_count (OCSP_REQUEST * x)
Definition at line 23 of file ocsp_ext.c.
References X509v3_get_ext_count().
OCSP_request_is_signed()
int OCSP_request_is_signed (OCSP_REQUEST * req)
Definition at line 56 of file ocsp_srv.c.
OCSP_request_onereq_count()
int OCSP_request_onereq_count (OCSP_REQUEST * req)
Definition at line 24 of file ocsp_srv.c.
OCSP_request_onereq_get0()
OCSP_ONEREQ* OCSP_request_onereq_get0 (OCSP_REQUEST * req, int i)
Definition at line 29 of file ocsp_srv.c.
OCSP_REQUEST_print()
int OCSP_REQUEST_print (BIO * bp, OCSP_REQUEST * a, unsigned long flags)
Definition at line 87 of file ocsp_prn.c.
References ASN1_INTEGER_get(), BIO_printf(), BIO_write(), GENERAL_NAME_print(), and NULL.
OCSP_request_set1_name()
int OCSP_request_set1_name (OCSP_REQUEST * req, X509_NAME * nm)
Definition at line 50 of file ocsp_cl.c.
References GENERAL_NAME::d, GENERAL_NAME::directoryName, gen, GEN_DIRNAME, NULL, GENERAL_NAME::type, and X509_NAME_set().
Referenced by OCSP_request_sign().
OCSP_request_sign()
int OCSP_request_sign (OCSP_REQUEST * req, X509 * signer, EVP_PKEY * key, const EVP_MD * dgst, STACK_OF(X509) * certs, unsigned long flags)
Definition at line 95 of file ocsp_cl.c.
References NULL, OCSP_F_OCSP_REQUEST_SIGN, OCSP_NOCERTS, OCSP_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE, OCSP_request_add1_cert(), OCSP_request_set1_name(), OCSP_REQUEST_sign, OCSPerr, X509_check_private_key(), and X509_get_subject_name().
OCSP_request_verify()
int OCSP_request_verify (OCSP_REQUEST * req, STACK_OF(X509) * certs, X509_STORE * store, unsigned long flags)
Definition at line 328 of file ocsp_vfy.c.
References ctx, GENERAL_NAME::d, GENERAL_NAME::directoryName, ERR_R_MALLOC_FAILURE, gen, GEN_DIRNAME, NULL, OCSP_F_OCSP_REQUEST_VERIFY, OCSP_R_REQUEST_NOT_SIGNED, OCSP_R_UNSUPPORTED_REQUESTORNAME_TYPE, OCSPerr, GENERAL_NAME::type, and X509_STORE_CTX_new().
OCSP_resp_count()
int OCSP_resp_count (OCSP_BASICRESP * bs)
Definition at line 173 of file ocsp_cl.c.
OCSP_resp_find()
int OCSP_resp_find (OCSP_BASICRESP * bs, OCSP_CERTID * id, int last)
Definition at line 219 of file ocsp_cl.c.
References OCSP_id_cmp(), and STACK_OF().
Referenced by OCSP_resp_find_status().
OCSP_resp_find_status()
int OCSP_resp_find_status (OCSP_BASICRESP * bs, OCSP_CERTID * id, int * status, int * reason, ASN1_GENERALIZEDTIME ** revtime, ASN1_GENERALIZEDTIME ** thisupd, ASN1_GENERALIZEDTIME ** nextupd)
Definition at line 279 of file ocsp_cl.c.
References OCSP_resp_find(), OCSP_resp_get0(), and OCSP_single_get0_status().
OCSP_resp_get0()
OCSP_SINGLERESP* OCSP_resp_get0 (OCSP_BASICRESP * bs, int idx)
Definition at line 182 of file ocsp_cl.c.
Referenced by OCSP_resp_find_status().
OCSP_resp_get0_id()
int OCSP_resp_get0_id (const OCSP_BASICRESP * bs, const ASN1_OCTET_STRING ** pid, const X509_NAME ** pname)
Definition at line 199 of file ocsp_cl.c.
References NULL, V_OCSP_RESPID_KEY, and V_OCSP_RESPID_NAME.
OCSP_resp_get0_produced_at()
const ASN1_GENERALIZEDTIME* OCSP_resp_get0_produced_at (const OCSP_BASICRESP * bs)
Definition at line 189 of file ocsp_cl.c.
OCSP_resp_get0_signature()
const ASN1_OCTET_STRING* OCSP_resp_get0_signature (const OCSP_BASICRESP * bs)
Definition at line 164 of file ocsp_cl.c.
OCSP_RESPID_match()
int OCSP_RESPID_match (OCSP_RESPID * respid, X509 * cert)
Definition at line 253 of file ocsp_srv.c.
OCSP_RESPID_set_by_key()
int OCSP_RESPID_set_by_key (OCSP_RESPID * respid, X509 * cert)
Definition at line 229 of file ocsp_srv.c.
Referenced by OCSP_basic_sign().
OCSP_RESPID_set_by_name()
int OCSP_RESPID_set_by_name (OCSP_RESPID * respid, X509 * cert)
Definition at line 219 of file ocsp_srv.c.
Referenced by OCSP_basic_sign().
OCSP_response_create()
OCSP_RESPONSE* OCSP_response_create (int status, OCSP_BASICRESP * bs)
Definition at line 64 of file ocsp_srv.c.
References ASN1_ENUMERATED_set(), ASN1_item_pack(), ASN1_ITEM_rptr, NID_id_pkix_OCSP_basic, NULL, and OBJ_nid2obj().
OCSP_response_get1_basic()
OCSP_BASICRESP* OCSP_response_get1_basic (OCSP_RESPONSE * resp)
Definition at line 148 of file ocsp_cl.c.
References ASN1_ITEM_rptr, ASN1_item_unpack(), NID_id_pkix_OCSP_basic, NULL, OBJ_obj2nid(), OCSP_F_OCSP_RESPONSE_GET1_BASIC, OCSP_R_NO_RESPONSE_DATA, OCSP_R_NOT_BASIC_RESPONSE, and OCSPerr.
OCSP_RESPONSE_print()
int OCSP_RESPONSE_print (BIO * bp, OCSP_RESPONSE * o, unsigned long flags)
Definition at line 132 of file ocsp_prn.c.
OCSP_response_status()
int OCSP_response_status (OCSP_RESPONSE * resp)
Definition at line 138 of file ocsp_cl.c.
References ASN1_ENUMERATED_get().
OCSP_response_status_str()
const char* OCSP_response_status_str (long s)
Definition at line 49 of file ocsp_prn.c.
References OCSP_RESPONSE_STATUS_INTERNALERROR, OCSP_RESPONSE_STATUS_MALFORMEDREQUEST, OCSP_RESPONSE_STATUS_SIGREQUIRED, OCSP_RESPONSE_STATUS_SUCCESSFUL, OCSP_RESPONSE_STATUS_TRYLATER, OCSP_RESPONSE_STATUS_UNAUTHORIZED, and table2string.
OCSP_sendreq_bio()
OCSP_RESPONSE* OCSP_sendreq_bio (BIO * b, const char * path, OCSP_REQUEST * req)
Definition at line 478 of file ocsp_ht.c.
References BIO_should_retry, ctx, NULL, OCSP_REQ_CTX_free(), OCSP_sendreq_nbio(), and OCSP_sendreq_new().
OCSP_sendreq_nbio()
int OCSP_sendreq_nbio (OCSP_RESPONSE ** presp, OCSP_REQ_CTX * rctx)
Definition at line 469 of file ocsp_ht.c.
References ASN1_ITEM_rptr, and OCSP_REQ_CTX_nbio_d2i().
Referenced by OCSP_sendreq_bio().
OCSP_sendreq_new()
OCSP_REQ_CTX* OCSP_sendreq_new (BIO * io, const char * path, OCSP_REQUEST * req, int maxline)
Definition at line 179 of file ocsp_ht.c.
References NULL, OCSP_REQ_CTX_free(), OCSP_REQ_CTX_http(), OCSP_REQ_CTX_new(), and OCSP_REQ_CTX_set1_req().
Referenced by OCSP_sendreq_bio().
OCSP_set_max_response_length()
void OCSP_set_max_response_length (OCSP_REQ_CTX * rctx, unsigned long len)
Definition at line 100 of file ocsp_ht.c.
References len, and OCSP_MAX_RESP_LENGTH.
OCSP_single_get0_status()
int OCSP_single_get0_status (OCSP_SINGLERESP * single, int * reason, ASN1_GENERALIZEDTIME ** revtime, ASN1_GENERALIZEDTIME ** thisupd, ASN1_GENERALIZEDTIME ** nextupd)
Definition at line 245 of file ocsp_cl.c.
Referenced by OCSP_resp_find_status().
OCSP_SINGLERESP_add1_ext_i2d()
int OCSP_SINGLERESP_add1_ext_i2d (OCSP_SINGLERESP * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 223 of file ocsp_ext.c.
References X509V3_add1_i2d().
OCSP_SINGLERESP_add_ext()
int OCSP_SINGLERESP_add_ext (OCSP_SINGLERESP * x, X509_EXTENSION * ex, int loc)
Definition at line 229 of file ocsp_ext.c.
References NULL.
OCSP_SINGLERESP_delete_ext()
X509_EXTENSION* OCSP_SINGLERESP_delete_ext (OCSP_SINGLERESP * x, int loc)
Definition at line 212 of file ocsp_ext.c.
References X509v3_delete_ext().
OCSP_SINGLERESP_get0_id()
const OCSP_CERTID* OCSP_SINGLERESP_get0_id (const OCSP_SINGLERESP * x)
Definition at line 362 of file ocsp_cl.c.
OCSP_SINGLERESP_get1_ext_d2i()
void* OCSP_SINGLERESP_get1_ext_d2i (OCSP_SINGLERESP * x, int nid, int * crit, int * idx)
Definition at line 217 of file ocsp_ext.c.
OCSP_SINGLERESP_get_ext()
X509_EXTENSION* OCSP_SINGLERESP_get_ext (OCSP_SINGLERESP * x, int loc)
Definition at line 207 of file ocsp_ext.c.
References X509v3_get_ext().
OCSP_SINGLERESP_get_ext_by_critical()
int OCSP_SINGLERESP_get_ext_by_critical (OCSP_SINGLERESP * x, int crit, int lastpos)
Definition at line 201 of file ocsp_ext.c.
References X509v3_get_ext_by_critical().
OCSP_SINGLERESP_get_ext_by_NID()
int OCSP_SINGLERESP_get_ext_by_NID (OCSP_SINGLERESP * x, int nid, int lastpos)
Definition at line 190 of file ocsp_ext.c.
References X509v3_get_ext_by_NID().
OCSP_SINGLERESP_get_ext_by_OBJ()
int OCSP_SINGLERESP_get_ext_by_OBJ (OCSP_SINGLERESP * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 195 of file ocsp_ext.c.
References X509v3_get_ext_by_OBJ().
OCSP_SINGLERESP_get_ext_count()
int OCSP_SINGLERESP_get_ext_count (OCSP_SINGLERESP * x)
Definition at line 185 of file ocsp_ext.c.
References X509v3_get_ext_count().
OCSP_url_svcloc_new()
X509_EXTENSION* OCSP_url_svcloc_new (X509_NAME * issuer, const char ** urls)
Definition at line 433 of file ocsp_ext.c.
References ASN1_STRING_set(), GENERAL_NAME::d, GEN_URI, GENERAL_NAME::ia5, ACCESS_DESCRIPTION::location, ACCESS_DESCRIPTION::method, NID_ad_OCSP, NID_id_pkix_OCSP_serviceLocator, NULL, OBJ_nid2obj(), GENERAL_NAME::type, X509_NAME_dup(), and X509V3_EXT_i2d().
STACK_OF()
const STACK_OF (X509) const