crypto/ocsp/ocsp_ht.c File Reference
ocsp_ht.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "e_os.h"
#include <openssl/asn1.h>
#include <openssl/ocsp.h>
#include <openssl/err.h>
#include <openssl/buffer.h>
Data Structures
struct OCSP_REQ_CTX
Macros
#define OCSP_MAX_RESP_LENGTH (100 * 1024)
#define OCSP_MAX_LINE_LEN 4096;
#define OHS_NOREAD 0x1000
#define OHS_ERROR (0 | OHS_NOREAD)
#define OHS_FIRSTLINE 1
#define OHS_HEADERS 2
#define OHS_ASN1_HEADER 3
#define OHS_ASN1_CONTENT 4
#define OHS_ASN1_WRITE_INIT (5 | OHS_NOREAD)
#define OHS_ASN1_WRITE (6 | OHS_NOREAD)
#define OHS_ASN1_FLUSH (7 | OHS_NOREAD)
#define OHS_DONE (8 | OHS_NOREAD)
#define OHS_HTTP_HEADER (9 | OHS_NOREAD)
Functions
OCSP_REQ_CTX * OCSP_REQ_CTX_new (BIO *io, int maxline)
void OCSP_REQ_CTX_free (OCSP_REQ_CTX *rctx)
BIO * OCSP_REQ_CTX_get0_mem_bio (OCSP_REQ_CTX *rctx)
void OCSP_set_max_response_length (OCSP_REQ_CTX *rctx, unsigned long len)
int OCSP_REQ_CTX_i2d (OCSP_REQ_CTX *rctx, const ASN1_ITEM *it, ASN1_VALUE *val)
int OCSP_REQ_CTX_nbio_d2i (OCSP_REQ_CTX *rctx, ASN1_VALUE **pval, const ASN1_ITEM *it)
int OCSP_REQ_CTX_http (OCSP_REQ_CTX *rctx, const char *op, const char *path)
int OCSP_REQ_CTX_set1_req (OCSP_REQ_CTX *rctx, OCSP_REQUEST *req)
int OCSP_REQ_CTX_add1_header (OCSP_REQ_CTX *rctx, const char *name, const char *value)
OCSP_REQ_CTX * OCSP_sendreq_new (BIO *io, const char *path, OCSP_REQUEST *req, int maxline)
int OCSP_REQ_CTX_nbio (OCSP_REQ_CTX *rctx)
int OCSP_sendreq_nbio (OCSP_RESPONSE **presp, OCSP_REQ_CTX *rctx)
OCSP_RESPONSE * OCSP_sendreq_bio (BIO *b, const char *path, OCSP_REQUEST *req)
Macro Definition Documentation
OCSP_MAX_LINE_LEN
#define OCSP_MAX_LINE_LEN 4096;
Definition at line 35 of file ocsp_ht.c.
Referenced by OCSP_REQ_CTX_new().
OCSP_MAX_RESP_LENGTH
#define OCSP_MAX_RESP_LENGTH (100 * 1024)
Definition at line 34 of file ocsp_ht.c.
Referenced by OCSP_REQ_CTX_new(), and OCSP_set_max_response_length().
OHS_ASN1_CONTENT
#define OHS_ASN1_CONTENT 4
Definition at line 50 of file ocsp_ht.c.
OHS_ASN1_FLUSH
#define OHS_ASN1_FLUSH (7 | OHS_NOREAD)
Definition at line 56 of file ocsp_ht.c.
Referenced by OCSP_REQ_CTX_nbio().
OHS_ASN1_HEADER
#define OHS_ASN1_HEADER 3
Definition at line 48 of file ocsp_ht.c.
OHS_ASN1_WRITE
#define OHS_ASN1_WRITE (6 | OHS_NOREAD)
Definition at line 54 of file ocsp_ht.c.
Referenced by OCSP_REQ_CTX_nbio().
OHS_ASN1_WRITE_INIT
#define OHS_ASN1_WRITE_INIT (5 | OHS_NOREAD)
Definition at line 52 of file ocsp_ht.c.
Referenced by OCSP_REQ_CTX_i2d(), and OCSP_REQ_CTX_nbio().
OHS_DONE
#define OHS_DONE (8 | OHS_NOREAD)
Definition at line 58 of file ocsp_ht.c.
OHS_ERROR
#define OHS_ERROR (0 | OHS_NOREAD)
Definition at line 42 of file ocsp_ht.c.
Referenced by OCSP_REQ_CTX_nbio(), OCSP_REQ_CTX_nbio_d2i(), and OCSP_REQ_CTX_new().
OHS_FIRSTLINE
#define OHS_FIRSTLINE 1
Definition at line 44 of file ocsp_ht.c.
Referenced by OCSP_REQ_CTX_nbio().
OHS_HEADERS
#define OHS_HEADERS 2
Definition at line 46 of file ocsp_ht.c.
Referenced by OCSP_REQ_CTX_nbio().
OHS_HTTP_HEADER
#define OHS_HTTP_HEADER (9 | OHS_NOREAD)
Definition at line 60 of file ocsp_ht.c.
Referenced by OCSP_REQ_CTX_add1_header(), OCSP_REQ_CTX_http(), and OCSP_REQ_CTX_nbio().
OHS_NOREAD
#define OHS_NOREAD 0x1000
Definition at line 40 of file ocsp_ht.c.
Referenced by OCSP_REQ_CTX_nbio().
Function Documentation
OCSP_REQ_CTX_add1_header()
int OCSP_REQ_CTX_add1_header (OCSP_REQ_CTX * rctx, const char * name, const char * value)
Definition at line 160 of file ocsp_ht.c.
References BIO_puts(), BIO_write(), and OHS_HTTP_HEADER.
OCSP_REQ_CTX_free()
void OCSP_REQ_CTX_free (OCSP_REQ_CTX * rctx)
Definition at line 86 of file ocsp_ht.c.
References BIO_free(), and OPENSSL_free.
Referenced by OCSP_REQ_CTX_new(), OCSP_sendreq_bio(), and OCSP_sendreq_new().
OCSP_REQ_CTX_get0_mem_bio()
BIO* OCSP_REQ_CTX_get0_mem_bio (OCSP_REQ_CTX * rctx)
Definition at line 95 of file ocsp_ht.c.
OCSP_REQ_CTX_http()
int OCSP_REQ_CTX_http (OCSP_REQ_CTX * rctx, const char * op, const char * path)
Definition at line 141 of file ocsp_ht.c.
References BIO_printf(), and OHS_HTTP_HEADER.
Referenced by OCSP_sendreq_new().
OCSP_REQ_CTX_i2d()
int OCSP_REQ_CTX_i2d (OCSP_REQ_CTX * rctx, const ASN1_ITEM * it, ASN1_VALUE * val)
Definition at line 108 of file ocsp_ht.c.
References ASN1_item_i2d(), ASN1_item_i2d_bio(), BIO_printf(), NULL, and OHS_ASN1_WRITE_INIT.
Referenced by OCSP_REQ_CTX_set1_req().
OCSP_REQ_CTX_nbio()
int OCSP_REQ_CTX_nbio (OCSP_REQ_CTX * rctx)
Definition at line 272 of file ocsp_ht.c.
References BIO_flush, BIO_get_mem_data, BIO_gets(), BIO_read(), BIO_reset, BIO_should_retry, BIO_write(), NULL, OHS_ASN1_FLUSH, OHS_ASN1_WRITE, OHS_ASN1_WRITE_INIT, OHS_ERROR, OHS_FIRSTLINE, OHS_HEADERS, OHS_HTTP_HEADER, and OHS_NOREAD.
Referenced by OCSP_REQ_CTX_nbio_d2i().
OCSP_REQ_CTX_nbio_d2i()
int OCSP_REQ_CTX_nbio_d2i (OCSP_REQ_CTX * rctx, ASN1_VALUE ** pval, const ASN1_ITEM * it)
Definition at line 122 of file ocsp_ht.c.
References ASN1_item_d2i(), BIO_get_mem_data, len, NULL, OCSP_REQ_CTX_nbio(), and OHS_ERROR.
Referenced by OCSP_sendreq_nbio(), X509_CRL_http_nbio(), and X509_http_nbio().
OCSP_REQ_CTX_new()
OCSP_REQ_CTX* OCSP_REQ_CTX_new (BIO * io, int maxline)
Definition at line 64 of file ocsp_ht.c.
References BIO_new(), BIO_s_mem(), OCSP_REQ_CTX::io, NULL, OCSP_MAX_LINE_LEN, OCSP_MAX_RESP_LENGTH, OCSP_REQ_CTX_free(), OHS_ERROR, OPENSSL_malloc, and OPENSSL_zalloc.
Referenced by OCSP_sendreq_new().
OCSP_REQ_CTX_set1_req()
int OCSP_REQ_CTX_set1_req (OCSP_REQ_CTX * rctx, OCSP_REQUEST * req)
Definition at line 154 of file ocsp_ht.c.
References ASN1_ITEM_rptr, and OCSP_REQ_CTX_i2d().
Referenced by OCSP_sendreq_new().
OCSP_sendreq_bio()
OCSP_RESPONSE* OCSP_sendreq_bio (BIO * b, const char * path, OCSP_REQUEST * req)
Definition at line 478 of file ocsp_ht.c.
References BIO_should_retry, ctx, NULL, OCSP_REQ_CTX_free(), OCSP_sendreq_nbio(), and OCSP_sendreq_new().
OCSP_sendreq_nbio()
int OCSP_sendreq_nbio (OCSP_RESPONSE ** presp, OCSP_REQ_CTX * rctx)
Definition at line 469 of file ocsp_ht.c.
References ASN1_ITEM_rptr, and OCSP_REQ_CTX_nbio_d2i().
Referenced by OCSP_sendreq_bio().
OCSP_sendreq_new()
OCSP_REQ_CTX* OCSP_sendreq_new (BIO * io, const char * path, OCSP_REQUEST * req, int maxline)
Definition at line 179 of file ocsp_ht.c.
References NULL, OCSP_REQ_CTX_free(), OCSP_REQ_CTX_http(), OCSP_REQ_CTX_new(), and OCSP_REQ_CTX_set1_req().
Referenced by OCSP_sendreq_bio().
OCSP_set_max_response_length()
void OCSP_set_max_response_length (OCSP_REQ_CTX * rctx, unsigned long len)
Definition at line 100 of file ocsp_ht.c.
References len, and OCSP_MAX_RESP_LENGTH.