crypto/ocsp/ocsp_srv.c File Reference
ocsp_srv.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/x509.h>
#include <openssl/pem.h>
#include <openssl/x509v3.h>
#include <openssl/ocsp.h>
#include "ocsp_lcl.h"
Functions
int OCSP_request_onereq_count (OCSP_REQUEST *req)
OCSP_ONEREQ * OCSP_request_onereq_get0 (OCSP_REQUEST *req, int i)
OCSP_CERTID * OCSP_onereq_get0_id (OCSP_ONEREQ *one)
int OCSP_id_get0_info (ASN1_OCTET_STRING **piNameHash, ASN1_OBJECT **pmd, ASN1_OCTET_STRING **pikeyHash, ASN1_INTEGER **pserial, OCSP_CERTID *cid)
int OCSP_request_is_signed (OCSP_REQUEST *req)
OCSP_RESPONSE * OCSP_response_create (int status, OCSP_BASICRESP *bs)
OCSP_SINGLERESP * OCSP_basic_add1_status (OCSP_BASICRESP *rsp, OCSP_CERTID *cid, int status, int reason, ASN1_TIME *revtime, ASN1_TIME *thisupd, ASN1_TIME *nextupd)
int OCSP_basic_add1_cert (OCSP_BASICRESP *resp, X509 *cert)
int OCSP_basic_sign (OCSP_BASICRESP *brsp, X509 *signer, EVP_PKEY *key, const EVP_MD *dgst, STACK_OF(X509) *certs, unsigned long flags)
int OCSP_RESPID_set_by_name (OCSP_RESPID *respid, X509 *cert)
int OCSP_RESPID_set_by_key (OCSP_RESPID *respid, X509 *cert)
int OCSP_RESPID_match (OCSP_RESPID *respid, X509 *cert)
Function Documentation
OCSP_basic_add1_cert()
int OCSP_basic_add1_cert (OCSP_BASICRESP * resp, X509 * cert)
Definition at line 159 of file ocsp_srv.c.
Referenced by OCSP_basic_sign().
OCSP_basic_add1_status()
OCSP_SINGLERESP* OCSP_basic_add1_status (OCSP_BASICRESP * rsp, OCSP_CERTID * cid, int status, int reason, ASN1_TIME * revtime, ASN1_TIME * thisupd, ASN1_TIME * nextupd)
Definition at line 86 of file ocsp_srv.c.
References ASN1_ENUMERATED_set(), ASN1_TIME_to_generalizedtime(), NULL, OCSP_CERTID_dup(), OCSP_F_OCSP_BASIC_ADD1_STATUS, OCSP_R_NO_REVOKED_TIME, OCSP_REVOKED_STATUS_NOSTATUS, OCSPerr, V_OCSP_CERTSTATUS_GOOD, V_OCSP_CERTSTATUS_REVOKED, and V_OCSP_CERTSTATUS_UNKNOWN.
OCSP_basic_sign()
int OCSP_basic_sign (OCSP_BASICRESP * brsp, X509 * signer, EVP_PKEY * key, const EVP_MD * dgst, STACK_OF(X509) * certs, unsigned long flags)
Definition at line 171 of file ocsp_srv.c.
References OCSP_basic_add1_cert(), OCSP_BASICRESP_sign, OCSP_F_OCSP_BASIC_SIGN, OCSP_NOCERTS, OCSP_NOTIME, OCSP_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE, OCSP_RESPID_KEY, OCSP_RESPID_set_by_key(), OCSP_RESPID_set_by_name(), OCSPerr, X509_check_private_key(), and X509_gmtime_adj().
OCSP_id_get0_info()
int OCSP_id_get0_info (ASN1_OCTET_STRING ** piNameHash, ASN1_OBJECT ** pmd, ASN1_OCTET_STRING ** pikeyHash, ASN1_INTEGER ** pserial, OCSP_CERTID * cid)
Definition at line 39 of file ocsp_srv.c.
OCSP_onereq_get0_id()
OCSP_CERTID* OCSP_onereq_get0_id (OCSP_ONEREQ * one)
Definition at line 34 of file ocsp_srv.c.
OCSP_request_is_signed()
int OCSP_request_is_signed (OCSP_REQUEST * req)
Definition at line 56 of file ocsp_srv.c.
OCSP_request_onereq_count()
int OCSP_request_onereq_count (OCSP_REQUEST * req)
Definition at line 24 of file ocsp_srv.c.
OCSP_request_onereq_get0()
OCSP_ONEREQ* OCSP_request_onereq_get0 (OCSP_REQUEST * req, int i)
Definition at line 29 of file ocsp_srv.c.
OCSP_RESPID_match()
int OCSP_RESPID_match (OCSP_RESPID * respid, X509 * cert)
Definition at line 253 of file ocsp_srv.c.
OCSP_RESPID_set_by_key()
int OCSP_RESPID_set_by_key (OCSP_RESPID * respid, X509 * cert)
Definition at line 229 of file ocsp_srv.c.
Referenced by OCSP_basic_sign().
OCSP_RESPID_set_by_name()
int OCSP_RESPID_set_by_name (OCSP_RESPID * respid, X509 * cert)
Definition at line 219 of file ocsp_srv.c.
Referenced by OCSP_basic_sign().
OCSP_response_create()
OCSP_RESPONSE* OCSP_response_create (int status, OCSP_BASICRESP * bs)
Definition at line 64 of file ocsp_srv.c.
References ASN1_ENUMERATED_set(), ASN1_item_pack(), ASN1_ITEM_rptr, NID_id_pkix_OCSP_basic, NULL, and OBJ_nid2obj().