crypto/ocsp/ocsp_cl.c File Reference
ocsp_cl.c File Reference
#include <stdio.h>
#include <time.h>
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/x509.h>
#include <openssl/pem.h>
#include <openssl/x509v3.h>
#include <openssl/ocsp.h>
#include "ocsp_lcl.h"
Functions
OCSP_ONEREQ * OCSP_request_add0_id (OCSP_REQUEST *req, OCSP_CERTID *cid)
int OCSP_request_set1_name (OCSP_REQUEST *req, X509_NAME *nm)
int OCSP_request_add1_cert (OCSP_REQUEST *req, X509 *cert)
int OCSP_request_sign (OCSP_REQUEST *req, X509 *signer, EVP_PKEY *key, const EVP_MD *dgst, STACK_OF(X509) *certs, unsigned long flags)
int OCSP_response_status (OCSP_RESPONSE *resp)
OCSP_BASICRESP * OCSP_response_get1_basic (OCSP_RESPONSE *resp)
const ASN1_OCTET_STRING * OCSP_resp_get0_signature (const OCSP_BASICRESP *bs)
int OCSP_resp_count (OCSP_BASICRESP *bs)
OCSP_SINGLERESP * OCSP_resp_get0 (OCSP_BASICRESP *bs, int idx)
const ASN1_GENERALIZEDTIME * OCSP_resp_get0_produced_at (const OCSP_BASICRESP *bs)
const STACK_OF (X509)
int OCSP_resp_get0_id (const OCSP_BASICRESP *bs, const ASN1_OCTET_STRING **pid, const X509_NAME **pname)
int OCSP_resp_find (OCSP_BASICRESP *bs, OCSP_CERTID *id, int last)
int OCSP_single_get0_status (OCSP_SINGLERESP *single, int *reason, ASN1_GENERALIZEDTIME **revtime, ASN1_GENERALIZEDTIME **thisupd, ASN1_GENERALIZEDTIME **nextupd)
int OCSP_resp_find_status (OCSP_BASICRESP *bs, OCSP_CERTID *id, int *status, int *reason, ASN1_GENERALIZEDTIME **revtime, ASN1_GENERALIZEDTIME **thisupd, ASN1_GENERALIZEDTIME **nextupd)
int OCSP_check_validity (ASN1_GENERALIZEDTIME *thisupd, ASN1_GENERALIZEDTIME *nextupd, long nsec, long maxsec)
const OCSP_CERTID * OCSP_SINGLERESP_get0_id (const OCSP_SINGLERESP *single)
Function Documentation
OCSP_check_validity()
int OCSP_check_validity (ASN1_GENERALIZEDTIME * thisupd, ASN1_GENERALIZEDTIME * nextupd, long nsec, long maxsec)
Definition at line 307 of file ocsp_cl.c.
OCSP_request_add0_id()
OCSP_ONEREQ* OCSP_request_add0_id (OCSP_REQUEST * req, OCSP_CERTID * cid)
Definition at line 30 of file ocsp_cl.c.
References NULL.
OCSP_request_add1_cert()
int OCSP_request_add1_cert (OCSP_REQUEST * req, X509 * cert)
Definition at line 69 of file ocsp_cl.c.
Referenced by OCSP_request_sign().
OCSP_request_set1_name()
int OCSP_request_set1_name (OCSP_REQUEST * req, X509_NAME * nm)
Definition at line 50 of file ocsp_cl.c.
References GENERAL_NAME::d, GENERAL_NAME::directoryName, gen, GEN_DIRNAME, NULL, GENERAL_NAME::type, and X509_NAME_set().
Referenced by OCSP_request_sign().
OCSP_request_sign()
int OCSP_request_sign (OCSP_REQUEST * req, X509 * signer, EVP_PKEY * key, const EVP_MD * dgst, STACK_OF(X509) * certs, unsigned long flags)
Definition at line 95 of file ocsp_cl.c.
References NULL, OCSP_F_OCSP_REQUEST_SIGN, OCSP_NOCERTS, OCSP_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE, OCSP_request_add1_cert(), OCSP_request_set1_name(), OCSP_REQUEST_sign, OCSPerr, X509_check_private_key(), and X509_get_subject_name().
OCSP_resp_count()
int OCSP_resp_count (OCSP_BASICRESP * bs)
Definition at line 173 of file ocsp_cl.c.
OCSP_resp_find()
int OCSP_resp_find (OCSP_BASICRESP * bs, OCSP_CERTID * id, int last)
Definition at line 219 of file ocsp_cl.c.
References OCSP_id_cmp(), and STACK_OF().
Referenced by OCSP_resp_find_status().
OCSP_resp_find_status()
int OCSP_resp_find_status (OCSP_BASICRESP * bs, OCSP_CERTID * id, int * status, int * reason, ASN1_GENERALIZEDTIME ** revtime, ASN1_GENERALIZEDTIME ** thisupd, ASN1_GENERALIZEDTIME ** nextupd)
Definition at line 279 of file ocsp_cl.c.
References OCSP_resp_find(), OCSP_resp_get0(), and OCSP_single_get0_status().
OCSP_resp_get0()
OCSP_SINGLERESP* OCSP_resp_get0 (OCSP_BASICRESP * bs, int idx)
Definition at line 182 of file ocsp_cl.c.
Referenced by OCSP_resp_find_status().
OCSP_resp_get0_id()
int OCSP_resp_get0_id (const OCSP_BASICRESP * bs, const ASN1_OCTET_STRING ** pid, const X509_NAME ** pname)
Definition at line 199 of file ocsp_cl.c.
References NULL, V_OCSP_RESPID_KEY, and V_OCSP_RESPID_NAME.
OCSP_resp_get0_produced_at()
const ASN1_GENERALIZEDTIME* OCSP_resp_get0_produced_at (const OCSP_BASICRESP * bs)
Definition at line 189 of file ocsp_cl.c.
OCSP_resp_get0_signature()
const ASN1_OCTET_STRING* OCSP_resp_get0_signature (const OCSP_BASICRESP * bs)
Definition at line 164 of file ocsp_cl.c.
OCSP_response_get1_basic()
OCSP_BASICRESP* OCSP_response_get1_basic (OCSP_RESPONSE * resp)
Definition at line 148 of file ocsp_cl.c.
References ASN1_ITEM_rptr, ASN1_item_unpack(), NID_id_pkix_OCSP_basic, NULL, OBJ_obj2nid(), OCSP_F_OCSP_RESPONSE_GET1_BASIC, OCSP_R_NO_RESPONSE_DATA, OCSP_R_NOT_BASIC_RESPONSE, and OCSPerr.
OCSP_response_status()
int OCSP_response_status (OCSP_RESPONSE * resp)
Definition at line 138 of file ocsp_cl.c.
References ASN1_ENUMERATED_get().
OCSP_single_get0_status()
int OCSP_single_get0_status (OCSP_SINGLERESP * single, int * reason, ASN1_GENERALIZEDTIME ** revtime, ASN1_GENERALIZEDTIME ** thisupd, ASN1_GENERALIZEDTIME ** nextupd)
Definition at line 245 of file ocsp_cl.c.
Referenced by OCSP_resp_find_status().
OCSP_SINGLERESP_get0_id()
const OCSP_CERTID* OCSP_SINGLERESP_get0_id (const OCSP_SINGLERESP * single)
Definition at line 362 of file ocsp_cl.c.
STACK_OF()
const STACK_OF (X509)
Definition at line 194 of file ocsp_cl.c.
Referenced by OCSP_resp_find().