crypto/ocsp/ocsp_prn.c File Reference
ocsp_prn.c File Reference
#include <openssl/bio.h>
#include <openssl/err.h>
#include <openssl/ocsp.h>
#include "ocsp_lcl.h"
#include "internal/cryptlib.h"
#include <openssl/pem.h>
Data Structures
struct OCSP_TBLSTR
Macros
#define table2string(s, tbl) do_table2string(s, tbl, OSSL_NELEM(tbl))
Functions
const char * OCSP_response_status_str (long s)
const char * OCSP_cert_status_str (long s)
const char * OCSP_crl_reason_str (long s)
int OCSP_REQUEST_print (BIO *bp, OCSP_REQUEST *o, unsigned long flags)
int OCSP_RESPONSE_print (BIO *bp, OCSP_RESPONSE *o, unsigned long flags)
Macro Definition Documentation
table2string
#define table2string (s, tbl) do_table2string(s, tbl, OSSL_NELEM(tbl))
Definition at line 47 of file ocsp_prn.c.
Referenced by OCSP_cert_status_str(), OCSP_crl_reason_str(), and OCSP_response_status_str().
Function Documentation
OCSP_cert_status_str()
const char* OCSP_cert_status_str (long s)
Definition at line 62 of file ocsp_prn.c.
References table2string, V_OCSP_CERTSTATUS_GOOD, V_OCSP_CERTSTATUS_REVOKED, and V_OCSP_CERTSTATUS_UNKNOWN.
OCSP_crl_reason_str()
const char* OCSP_crl_reason_str (long s)
Definition at line 72 of file ocsp_prn.c.
References OCSP_REVOKED_STATUS_AFFILIATIONCHANGED, OCSP_REVOKED_STATUS_CACOMPROMISE, OCSP_REVOKED_STATUS_CERTIFICATEHOLD, OCSP_REVOKED_STATUS_CESSATIONOFOPERATION, OCSP_REVOKED_STATUS_KEYCOMPROMISE, OCSP_REVOKED_STATUS_REMOVEFROMCRL, OCSP_REVOKED_STATUS_SUPERSEDED, OCSP_REVOKED_STATUS_UNSPECIFIED, and table2string.
OCSP_REQUEST_print()
int OCSP_REQUEST_print (BIO * bp, OCSP_REQUEST * o, unsigned long flags)
Definition at line 87 of file ocsp_prn.c.
References ASN1_INTEGER_get(), BIO_printf(), BIO_write(), GENERAL_NAME_print(), and NULL.
OCSP_RESPONSE_print()
int OCSP_RESPONSE_print (BIO * bp, OCSP_RESPONSE * o, unsigned long flags)
Definition at line 132 of file ocsp_prn.c.
OCSP_response_status_str()
const char* OCSP_response_status_str (long s)
Definition at line 49 of file ocsp_prn.c.
References OCSP_RESPONSE_STATUS_INTERNALERROR, OCSP_RESPONSE_STATUS_MALFORMEDREQUEST, OCSP_RESPONSE_STATUS_SIGREQUIRED, OCSP_RESPONSE_STATUS_SUCCESSFUL, OCSP_RESPONSE_STATUS_TRYLATER, OCSP_RESPONSE_STATUS_UNAUTHORIZED, and table2string.