crypto/ocsp/ocsp_ext.c File Reference
ocsp_ext.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/x509.h>
#include <openssl/ocsp.h>
#include "ocsp_lcl.h"
#include <openssl/rand.h>
#include <openssl/x509v3.h>
Functions
int OCSP_REQUEST_get_ext_count (OCSP_REQUEST *x)
int OCSP_REQUEST_get_ext_by_NID (OCSP_REQUEST *x, int nid, int lastpos)
int OCSP_REQUEST_get_ext_by_OBJ (OCSP_REQUEST *x, const ASN1_OBJECT *obj, int lastpos)
int OCSP_REQUEST_get_ext_by_critical (OCSP_REQUEST *x, int crit, int lastpos)
X509_EXTENSION * OCSP_REQUEST_get_ext (OCSP_REQUEST *x, int loc)
X509_EXTENSION * OCSP_REQUEST_delete_ext (OCSP_REQUEST *x, int loc)
void * OCSP_REQUEST_get1_ext_d2i (OCSP_REQUEST *x, int nid, int *crit, int *idx)
int OCSP_REQUEST_add1_ext_i2d (OCSP_REQUEST *x, int nid, void *value, int crit, unsigned long flags)
int OCSP_REQUEST_add_ext (OCSP_REQUEST *x, X509_EXTENSION *ex, int loc)
int OCSP_ONEREQ_get_ext_count (OCSP_ONEREQ *x)
int OCSP_ONEREQ_get_ext_by_NID (OCSP_ONEREQ *x, int nid, int lastpos)
int OCSP_ONEREQ_get_ext_by_OBJ (OCSP_ONEREQ *x, const ASN1_OBJECT *obj, int lastpos)
int OCSP_ONEREQ_get_ext_by_critical (OCSP_ONEREQ *x, int crit, int lastpos)
X509_EXTENSION * OCSP_ONEREQ_get_ext (OCSP_ONEREQ *x, int loc)
X509_EXTENSION * OCSP_ONEREQ_delete_ext (OCSP_ONEREQ *x, int loc)
void * OCSP_ONEREQ_get1_ext_d2i (OCSP_ONEREQ *x, int nid, int *crit, int *idx)
int OCSP_ONEREQ_add1_ext_i2d (OCSP_ONEREQ *x, int nid, void *value, int crit, unsigned long flags)
int OCSP_ONEREQ_add_ext (OCSP_ONEREQ *x, X509_EXTENSION *ex, int loc)
int OCSP_BASICRESP_get_ext_count (OCSP_BASICRESP *x)
int OCSP_BASICRESP_get_ext_by_NID (OCSP_BASICRESP *x, int nid, int lastpos)
int OCSP_BASICRESP_get_ext_by_OBJ (OCSP_BASICRESP *x, const ASN1_OBJECT *obj, int lastpos)
int OCSP_BASICRESP_get_ext_by_critical (OCSP_BASICRESP *x, int crit, int lastpos)
X509_EXTENSION * OCSP_BASICRESP_get_ext (OCSP_BASICRESP *x, int loc)
X509_EXTENSION * OCSP_BASICRESP_delete_ext (OCSP_BASICRESP *x, int loc)
void * OCSP_BASICRESP_get1_ext_d2i (OCSP_BASICRESP *x, int nid, int *crit, int *idx)
int OCSP_BASICRESP_add1_ext_i2d (OCSP_BASICRESP *x, int nid, void *value, int crit, unsigned long flags)
int OCSP_BASICRESP_add_ext (OCSP_BASICRESP *x, X509_EXTENSION *ex, int loc)
int OCSP_SINGLERESP_get_ext_count (OCSP_SINGLERESP *x)
int OCSP_SINGLERESP_get_ext_by_NID (OCSP_SINGLERESP *x, int nid, int lastpos)
int OCSP_SINGLERESP_get_ext_by_OBJ (OCSP_SINGLERESP *x, const ASN1_OBJECT *obj, int lastpos)
int OCSP_SINGLERESP_get_ext_by_critical (OCSP_SINGLERESP *x, int crit, int lastpos)
X509_EXTENSION * OCSP_SINGLERESP_get_ext (OCSP_SINGLERESP *x, int loc)
X509_EXTENSION * OCSP_SINGLERESP_delete_ext (OCSP_SINGLERESP *x, int loc)
void * OCSP_SINGLERESP_get1_ext_d2i (OCSP_SINGLERESP *x, int nid, int *crit, int *idx)
int OCSP_SINGLERESP_add1_ext_i2d (OCSP_SINGLERESP *x, int nid, void *value, int crit, unsigned long flags)
int OCSP_SINGLERESP_add_ext (OCSP_SINGLERESP *x, X509_EXTENSION *ex, int loc)
int OCSP_request_add1_nonce (OCSP_REQUEST *req, unsigned char *val, int len)
int OCSP_basic_add1_nonce (OCSP_BASICRESP *resp, unsigned char *val, int len)
int OCSP_check_nonce (OCSP_REQUEST *req, OCSP_BASICRESP *bs)
int OCSP_copy_nonce (OCSP_BASICRESP *resp, OCSP_REQUEST *req)
X509_EXTENSION * OCSP_crlID_new (const char *url, long *n, char *tim)
X509_EXTENSION * OCSP_accept_responses_new (char **oids)
X509_EXTENSION * OCSP_archive_cutoff_new (char *tim)
X509_EXTENSION * OCSP_url_svcloc_new (X509_NAME *issuer, const char **urls)
Function Documentation
OCSP_accept_responses_new()
X509_EXTENSION* OCSP_accept_responses_new (char ** oids)
Definition at line 392 of file ocsp_ext.c.
References ASN1_OBJECT_free(), nid, NID_id_pkix_OCSP_acceptableResponses, NID_undef, NULL, OBJ_nid2obj(), OBJ_txt2nid(), STACK_OF, and X509V3_EXT_i2d().
OCSP_archive_cutoff_new()
X509_EXTENSION* OCSP_archive_cutoff_new (char * tim)
Definition at line 413 of file ocsp_ext.c.
References ASN1_GENERALIZEDTIME_set_string(), NID_id_pkix_OCSP_archiveCutoff, NULL, and X509V3_EXT_i2d().
OCSP_basic_add1_nonce()
int OCSP_basic_add1_nonce (OCSP_BASICRESP * resp, unsigned char * val, int len)
Definition at line 289 of file ocsp_ext.c.
OCSP_BASICRESP_add1_ext_i2d()
int OCSP_BASICRESP_add1_ext_i2d (OCSP_BASICRESP * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 170 of file ocsp_ext.c.
References X509V3_add1_i2d().
OCSP_BASICRESP_add_ext()
int OCSP_BASICRESP_add_ext (OCSP_BASICRESP * x, X509_EXTENSION * ex, int loc)
Definition at line 177 of file ocsp_ext.c.
References NULL.
Referenced by OCSP_copy_nonce().
OCSP_BASICRESP_delete_ext()
X509_EXTENSION* OCSP_BASICRESP_delete_ext (OCSP_BASICRESP * x, int loc)
Definition at line 158 of file ocsp_ext.c.
References X509v3_delete_ext().
OCSP_BASICRESP_get1_ext_d2i()
void* OCSP_BASICRESP_get1_ext_d2i (OCSP_BASICRESP * x, int nid, int * crit, int * idx)
Definition at line 163 of file ocsp_ext.c.
OCSP_BASICRESP_get_ext()
X509_EXTENSION* OCSP_BASICRESP_get_ext (OCSP_BASICRESP * x, int loc)
Definition at line 153 of file ocsp_ext.c.
References X509v3_get_ext().
Referenced by OCSP_check_nonce().
OCSP_BASICRESP_get_ext_by_critical()
int OCSP_BASICRESP_get_ext_by_critical (OCSP_BASICRESP * x, int crit, int lastpos)
Definition at line 146 of file ocsp_ext.c.
References X509v3_get_ext_by_critical().
OCSP_BASICRESP_get_ext_by_NID()
int OCSP_BASICRESP_get_ext_by_NID (OCSP_BASICRESP * x, int nid, int lastpos)
Definition at line 133 of file ocsp_ext.c.
References X509v3_get_ext_by_NID().
Referenced by OCSP_check_nonce().
OCSP_BASICRESP_get_ext_by_OBJ()
int OCSP_BASICRESP_get_ext_by_OBJ (OCSP_BASICRESP * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 139 of file ocsp_ext.c.
References X509v3_get_ext_by_OBJ().
OCSP_BASICRESP_get_ext_count()
int OCSP_BASICRESP_get_ext_count (OCSP_BASICRESP * x)
Definition at line 128 of file ocsp_ext.c.
References X509v3_get_ext_count().
OCSP_check_nonce()
int OCSP_check_nonce (OCSP_REQUEST * req, OCSP_BASICRESP * bs)
Definition at line 309 of file ocsp_ext.c.
References ASN1_OCTET_STRING_cmp(), NID_id_pkix_OCSP_Nonce, OCSP_BASICRESP_get_ext(), OCSP_BASICRESP_get_ext_by_NID(), OCSP_REQUEST_get_ext(), OCSP_REQUEST_get_ext_by_NID(), and X509_EXTENSION_get_data().
OCSP_copy_nonce()
int OCSP_copy_nonce (OCSP_BASICRESP * resp, OCSP_REQUEST * req)
Definition at line 347 of file ocsp_ext.c.
References NID_id_pkix_OCSP_Nonce, OCSP_BASICRESP_add_ext(), OCSP_REQUEST_get_ext(), and OCSP_REQUEST_get_ext_by_NID().
OCSP_crlID_new()
X509_EXTENSION* OCSP_crlID_new (const char * url, long * n, char * tim)
Definition at line 360 of file ocsp_ext.c.
References ASN1_GENERALIZEDTIME_set_string(), ASN1_INTEGER_set(), ASN1_STRING_set(), NID_id_pkix_OCSP_CrlID, NULL, and X509V3_EXT_i2d().
OCSP_ONEREQ_add1_ext_i2d()
int OCSP_ONEREQ_add1_ext_i2d (OCSP_ONEREQ * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 114 of file ocsp_ext.c.
References X509V3_add1_i2d().
OCSP_ONEREQ_add_ext()
int OCSP_ONEREQ_add_ext (OCSP_ONEREQ * x, X509_EXTENSION * ex, int loc)
Definition at line 121 of file ocsp_ext.c.
References NULL.
OCSP_ONEREQ_delete_ext()
X509_EXTENSION* OCSP_ONEREQ_delete_ext (OCSP_ONEREQ * x, int loc)
Definition at line 104 of file ocsp_ext.c.
References X509v3_delete_ext().
OCSP_ONEREQ_get1_ext_d2i()
void* OCSP_ONEREQ_get1_ext_d2i (OCSP_ONEREQ * x, int nid, int * crit, int * idx)
Definition at line 109 of file ocsp_ext.c.
OCSP_ONEREQ_get_ext()
X509_EXTENSION* OCSP_ONEREQ_get_ext (OCSP_ONEREQ * x, int loc)
Definition at line 99 of file ocsp_ext.c.
References X509v3_get_ext().
OCSP_ONEREQ_get_ext_by_critical()
int OCSP_ONEREQ_get_ext_by_critical (OCSP_ONEREQ * x, int crit, int lastpos)
Definition at line 93 of file ocsp_ext.c.
References X509v3_get_ext_by_critical().
OCSP_ONEREQ_get_ext_by_NID()
int OCSP_ONEREQ_get_ext_by_NID (OCSP_ONEREQ * x, int nid, int lastpos)
Definition at line 82 of file ocsp_ext.c.
References X509v3_get_ext_by_NID().
OCSP_ONEREQ_get_ext_by_OBJ()
int OCSP_ONEREQ_get_ext_by_OBJ (OCSP_ONEREQ * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 87 of file ocsp_ext.c.
References X509v3_get_ext_by_OBJ().
OCSP_ONEREQ_get_ext_count()
int OCSP_ONEREQ_get_ext_count (OCSP_ONEREQ * x)
Definition at line 77 of file ocsp_ext.c.
References X509v3_get_ext_count().
OCSP_REQUEST_add1_ext_i2d()
int OCSP_REQUEST_add1_ext_i2d (OCSP_REQUEST * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 62 of file ocsp_ext.c.
References X509V3_add1_i2d().
OCSP_request_add1_nonce()
int OCSP_request_add1_nonce (OCSP_REQUEST * req, unsigned char * val, int len)
Definition at line 282 of file ocsp_ext.c.
OCSP_REQUEST_add_ext()
int OCSP_REQUEST_add_ext (OCSP_REQUEST * x, X509_EXTENSION * ex, int loc)
Definition at line 69 of file ocsp_ext.c.
References NULL.
OCSP_REQUEST_delete_ext()
X509_EXTENSION* OCSP_REQUEST_delete_ext (OCSP_REQUEST * x, int loc)
Definition at line 52 of file ocsp_ext.c.
References X509v3_delete_ext().
OCSP_REQUEST_get1_ext_d2i()
void* OCSP_REQUEST_get1_ext_d2i (OCSP_REQUEST * x, int nid, int * crit, int * idx)
Definition at line 57 of file ocsp_ext.c.
OCSP_REQUEST_get_ext()
X509_EXTENSION* OCSP_REQUEST_get_ext (OCSP_REQUEST * x, int loc)
Definition at line 47 of file ocsp_ext.c.
References X509v3_get_ext().
Referenced by OCSP_check_nonce(), and OCSP_copy_nonce().
OCSP_REQUEST_get_ext_by_critical()
int OCSP_REQUEST_get_ext_by_critical (OCSP_REQUEST * x, int crit, int lastpos)
Definition at line 41 of file ocsp_ext.c.
References X509v3_get_ext_by_critical().
OCSP_REQUEST_get_ext_by_NID()
int OCSP_REQUEST_get_ext_by_NID (OCSP_REQUEST * x, int nid, int lastpos)
Definition at line 28 of file ocsp_ext.c.
References X509v3_get_ext_by_NID().
Referenced by OCSP_check_nonce(), and OCSP_copy_nonce().
OCSP_REQUEST_get_ext_by_OBJ()
int OCSP_REQUEST_get_ext_by_OBJ (OCSP_REQUEST * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 34 of file ocsp_ext.c.
References X509v3_get_ext_by_OBJ().
OCSP_REQUEST_get_ext_count()
int OCSP_REQUEST_get_ext_count (OCSP_REQUEST * x)
Definition at line 23 of file ocsp_ext.c.
References X509v3_get_ext_count().
OCSP_SINGLERESP_add1_ext_i2d()
int OCSP_SINGLERESP_add1_ext_i2d (OCSP_SINGLERESP * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 223 of file ocsp_ext.c.
References X509V3_add1_i2d().
OCSP_SINGLERESP_add_ext()
int OCSP_SINGLERESP_add_ext (OCSP_SINGLERESP * x, X509_EXTENSION * ex, int loc)
Definition at line 229 of file ocsp_ext.c.
References NULL.
OCSP_SINGLERESP_delete_ext()
X509_EXTENSION* OCSP_SINGLERESP_delete_ext (OCSP_SINGLERESP * x, int loc)
Definition at line 212 of file ocsp_ext.c.
References X509v3_delete_ext().
OCSP_SINGLERESP_get1_ext_d2i()
void* OCSP_SINGLERESP_get1_ext_d2i (OCSP_SINGLERESP * x, int nid, int * crit, int * idx)
Definition at line 217 of file ocsp_ext.c.
OCSP_SINGLERESP_get_ext()
X509_EXTENSION* OCSP_SINGLERESP_get_ext (OCSP_SINGLERESP * x, int loc)
Definition at line 207 of file ocsp_ext.c.
References X509v3_get_ext().
OCSP_SINGLERESP_get_ext_by_critical()
int OCSP_SINGLERESP_get_ext_by_critical (OCSP_SINGLERESP * x, int crit, int lastpos)
Definition at line 201 of file ocsp_ext.c.
References X509v3_get_ext_by_critical().
OCSP_SINGLERESP_get_ext_by_NID()
int OCSP_SINGLERESP_get_ext_by_NID (OCSP_SINGLERESP * x, int nid, int lastpos)
Definition at line 190 of file ocsp_ext.c.
References X509v3_get_ext_by_NID().
OCSP_SINGLERESP_get_ext_by_OBJ()
int OCSP_SINGLERESP_get_ext_by_OBJ (OCSP_SINGLERESP * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 195 of file ocsp_ext.c.
References X509v3_get_ext_by_OBJ().
OCSP_SINGLERESP_get_ext_count()
int OCSP_SINGLERESP_get_ext_count (OCSP_SINGLERESP * x)
Definition at line 185 of file ocsp_ext.c.
References X509v3_get_ext_count().
OCSP_url_svcloc_new()
X509_EXTENSION* OCSP_url_svcloc_new (X509_NAME * issuer, const char ** urls)
Definition at line 433 of file ocsp_ext.c.
References ASN1_STRING_set(), GENERAL_NAME::d, GEN_URI, GENERAL_NAME::ia5, ACCESS_DESCRIPTION::location, ACCESS_DESCRIPTION::method, NID_ad_OCSP, NID_id_pkix_OCSP_serviceLocator, NULL, OBJ_nid2obj(), GENERAL_NAME::type, X509_NAME_dup(), and X509V3_EXT_i2d().