include/openssl/conf.h File Reference
conf.h File Reference
#include <openssl/bio.h>
#include <openssl/lhash.h>
#include <openssl/stack.h>
#include <openssl/safestack.h>
#include <openssl/e_os2.h>
#include <openssl/ossl_typ.h>
Data Structures
struct CONF_VALUE
struct CONF_METHOD
struct CONF
Macros
#define CONF_MFLAGS_IGNORE_ERRORS 0x1
#define CONF_MFLAGS_IGNORE_RETURN_CODES 0x2
#define CONF_MFLAGS_SILENT 0x4
#define CONF_MFLAGS_NO_DSO 0x8
#define CONF_MFLAGS_IGNORE_MISSING_FILE 0x10
#define CONF_MFLAGS_DEFAULT_SECTION 0x20
#define OPENSSL_no_config() OPENSSL_init_crypto(OPENSSL_INIT_NO_LOAD_CONFIG, NULL)
#define NCONF_get_number(c, g, n, r) NCONF_get_number_e(c,g,n,r)
#define CONF_modules_free() while(0) continue
#define CONF_F_CONF_DUMP_FP 104
#define CONF_F_CONF_LOAD 100
#define CONF_F_CONF_LOAD_FP 103
#define CONF_F_CONF_PARSE_LIST 119
#define CONF_F_DEF_LOAD 120
#define CONF_F_DEF_LOAD_BIO 121
#define CONF_F_MODULE_INIT 115
#define CONF_F_MODULE_LOAD_DSO 117
#define CONF_F_MODULE_RUN 118
#define CONF_F_NCONF_DUMP_BIO 105
#define CONF_F_NCONF_DUMP_FP 106
#define CONF_F_NCONF_GET_NUMBER_E 112
#define CONF_F_NCONF_GET_SECTION 108
#define CONF_F_NCONF_GET_STRING 109
#define CONF_F_NCONF_LOAD 113
#define CONF_F_NCONF_LOAD_BIO 110
#define CONF_F_NCONF_LOAD_FP 114
#define CONF_F_NCONF_NEW 111
#define CONF_F_STR_COPY 101
#define CONF_R_ERROR_LOADING_DSO 110
#define CONF_R_LIST_CANNOT_BE_NULL 115
#define CONF_R_MISSING_CLOSE_SQUARE_BRACKET 100
#define CONF_R_MISSING_EQUAL_SIGN 101
#define CONF_R_MISSING_INIT_FUNCTION 112
#define CONF_R_MODULE_INITIALIZATION_ERROR 109
#define CONF_R_NO_CLOSE_BRACE 102
#define CONF_R_NO_CONF 105
#define CONF_R_NO_CONF_OR_ENVIRONMENT_VARIABLE 106
#define CONF_R_NO_SECTION 107
#define CONF_R_NO_SUCH_FILE 114
#define CONF_R_NO_VALUE 108
#define CONF_R_UNABLE_TO_CREATE_NEW_SECTION 103
#define CONF_R_UNKNOWN_MODULE_NAME 113
#define CONF_R_VARIABLE_HAS_NO_VALUE 104
Typedefs
typedef int conf_init_func(CONF_IMODULE *md, const CONF *cnf)
typedef void conf_finish_func(CONF_IMODULE *md)
Functions
DEFINE_LHASH_OF (CONF_VALUE)
int CONF_set_default_method (CONF_METHOD *meth)
void CONF_set_nconf (CONF *conf, LHASH_OF(CONF_VALUE) *hash)
LHASH_OF (CONF_VALUE) *CONF_load(LHASH_OF(CONF_VALUE) *conf
STACK_OF (CONF_VALUE) *CONF_get_section(LHASH_OF(CONF_VALUE) *conf
char * CONF_get_string (LHASH_OF(CONF_VALUE) *conf, const char *group, const char *name)
long CONF_get_number (LHASH_OF(CONF_VALUE) *conf, const char *group, const char *name)
void CONF_free (LHASH_OF(CONF_VALUE) *conf)
int CONF_dump_fp (LHASH_OF(CONF_VALUE) *conf, FILE *out)
int CONF_dump_bio (LHASH_OF(CONF_VALUE) *conf, BIO *out)
CONF * NCONF_new (CONF_METHOD *meth)
CONF_METHOD * NCONF_default (void)
CONF_METHOD * NCONF_WIN32 (void)
void NCONF_free (CONF *conf)
void NCONF_free_data (CONF *conf)
int NCONF_load (CONF *conf, const char *file, long *eline)
int NCONF_load_fp (CONF *conf, FILE *fp, long *eline)
int NCONF_load_bio (CONF *conf, BIO *bp, long *eline)
char * NCONF_get_string (const CONF *conf, const char *group, const char *name)
int NCONF_get_number_e (const CONF *conf, const char *group, const char *name, long *result)
int NCONF_dump_fp (const CONF *conf, FILE *out)
int NCONF_dump_bio (const CONF *conf, BIO *out)
int CONF_modules_load (const CONF *cnf, const char *appname, unsigned long flags)
int CONF_modules_load_file (const char *filename, const char *appname, unsigned long flags)
void CONF_modules_unload (int all)
void CONF_modules_finish (void)
int CONF_module_add (const char *name, conf_init_func *ifunc, conf_finish_func *ffunc)
const char * CONF_imodule_get_name (const CONF_IMODULE *md)
const char * CONF_imodule_get_value (const CONF_IMODULE *md)
void * CONF_imodule_get_usr_data (const CONF_IMODULE *md)
void CONF_imodule_set_usr_data (CONF_IMODULE *md, void *usr_data)
CONF_MODULE * CONF_imodule_get_module (const CONF_IMODULE *md)
unsigned long CONF_imodule_get_flags (const CONF_IMODULE *md)
void CONF_imodule_set_flags (CONF_IMODULE *md, unsigned long flags)
void * CONF_module_get_usr_data (CONF_MODULE *pmod)
void CONF_module_set_usr_data (CONF_MODULE *pmod, void *usr_data)
char * CONF_get1_default_config_file (void)
int CONF_parse_list (const char *list, int sep, int nospc, int(*list_cb)(const char *elem, int len, void *usr), void *arg)
void OPENSSL_load_builtin_modules (void)
int ERR_load_CONF_strings (void)
Variables
const char * file
const char long * eline
FILE * fp
BIO * bp
const char * section
Macro Definition Documentation
CONF_F_CONF_DUMP_FP
#define CONF_F_CONF_DUMP_FP 104
Definition at line 176 of file conf.h.
CONF_F_CONF_LOAD
#define CONF_F_CONF_LOAD 100
Definition at line 177 of file conf.h.
Referenced by LHASH_OF().
CONF_F_CONF_LOAD_FP
#define CONF_F_CONF_LOAD_FP 103
Definition at line 178 of file conf.h.
Referenced by LHASH_OF().
CONF_F_CONF_PARSE_LIST
#define CONF_F_CONF_PARSE_LIST 119
Definition at line 179 of file conf.h.
CONF_F_DEF_LOAD
#define CONF_F_DEF_LOAD 120
Definition at line 180 of file conf.h.
CONF_F_DEF_LOAD_BIO
#define CONF_F_DEF_LOAD_BIO 121
Definition at line 181 of file conf.h.
CONF_F_MODULE_INIT
#define CONF_F_MODULE_INIT 115
Definition at line 182 of file conf.h.
CONF_F_MODULE_LOAD_DSO
#define CONF_F_MODULE_LOAD_DSO 117
Definition at line 183 of file conf.h.
CONF_F_MODULE_RUN
#define CONF_F_MODULE_RUN 118
Definition at line 184 of file conf.h.
CONF_F_NCONF_DUMP_BIO
#define CONF_F_NCONF_DUMP_BIO 105
Definition at line 185 of file conf.h.
CONF_F_NCONF_DUMP_FP
#define CONF_F_NCONF_DUMP_FP 106
Definition at line 186 of file conf.h.
CONF_F_NCONF_GET_NUMBER_E
#define CONF_F_NCONF_GET_NUMBER_E 112
Definition at line 187 of file conf.h.
Referenced by NCONF_get_number_e().
CONF_F_NCONF_GET_SECTION
#define CONF_F_NCONF_GET_SECTION 108
Definition at line 188 of file conf.h.
Referenced by NCONF_load_bio().
CONF_F_NCONF_GET_STRING
#define CONF_F_NCONF_GET_STRING 109
Definition at line 189 of file conf.h.
Referenced by NCONF_get_string().
CONF_F_NCONF_LOAD
#define CONF_F_NCONF_LOAD 113
Definition at line 190 of file conf.h.
Referenced by NCONF_load().
CONF_F_NCONF_LOAD_BIO
#define CONF_F_NCONF_LOAD_BIO 110
Definition at line 191 of file conf.h.
Referenced by NCONF_load_bio().
CONF_F_NCONF_LOAD_FP
#define CONF_F_NCONF_LOAD_FP 114
Definition at line 192 of file conf.h.
CONF_F_NCONF_NEW
#define CONF_F_NCONF_NEW 111
Definition at line 193 of file conf.h.
CONF_F_STR_COPY
#define CONF_F_STR_COPY 101
Definition at line 194 of file conf.h.
CONF_MFLAGS_DEFAULT_SECTION
#define CONF_MFLAGS_DEFAULT_SECTION 0x20
Definition at line 68 of file conf.h.
CONF_MFLAGS_IGNORE_ERRORS
#define CONF_MFLAGS_IGNORE_ERRORS 0x1
Definition at line 63 of file conf.h.
CONF_MFLAGS_IGNORE_MISSING_FILE
#define CONF_MFLAGS_IGNORE_MISSING_FILE 0x10
Definition at line 67 of file conf.h.
CONF_MFLAGS_IGNORE_RETURN_CODES
#define CONF_MFLAGS_IGNORE_RETURN_CODES 0x2
Definition at line 64 of file conf.h.
CONF_MFLAGS_NO_DSO
#define CONF_MFLAGS_NO_DSO 0x8
Definition at line 66 of file conf.h.
CONF_MFLAGS_SILENT
#define CONF_MFLAGS_SILENT 0x4
Definition at line 65 of file conf.h.
CONF_modules_free
#define CONF_modules_free () while(0) continue
Definition at line 142 of file conf.h.
CONF_R_ERROR_LOADING_DSO
#define CONF_R_ERROR_LOADING_DSO 110
Definition at line 197 of file conf.h.
CONF_R_LIST_CANNOT_BE_NULL
#define CONF_R_LIST_CANNOT_BE_NULL 115
Definition at line 198 of file conf.h.
CONF_R_MISSING_CLOSE_SQUARE_BRACKET
#define CONF_R_MISSING_CLOSE_SQUARE_BRACKET 100
Definition at line 199 of file conf.h.
CONF_R_MISSING_EQUAL_SIGN
#define CONF_R_MISSING_EQUAL_SIGN 101
Definition at line 200 of file conf.h.
CONF_R_MISSING_INIT_FUNCTION
#define CONF_R_MISSING_INIT_FUNCTION 112
Definition at line 201 of file conf.h.
CONF_R_MODULE_INITIALIZATION_ERROR
#define CONF_R_MODULE_INITIALIZATION_ERROR 109
Definition at line 202 of file conf.h.
CONF_R_NO_CLOSE_BRACE
#define CONF_R_NO_CLOSE_BRACE 102
Definition at line 203 of file conf.h.
CONF_R_NO_CONF
#define CONF_R_NO_CONF 105
Definition at line 204 of file conf.h.
Referenced by NCONF_load(), and NCONF_load_bio().
CONF_R_NO_CONF_OR_ENVIRONMENT_VARIABLE
#define CONF_R_NO_CONF_OR_ENVIRONMENT_VARIABLE 106
Definition at line 205 of file conf.h.
Referenced by NCONF_get_string().
CONF_R_NO_SECTION
#define CONF_R_NO_SECTION 107
Definition at line 206 of file conf.h.
Referenced by NCONF_load_bio().
CONF_R_NO_SUCH_FILE
#define CONF_R_NO_SUCH_FILE 114
Definition at line 207 of file conf.h.
CONF_R_NO_VALUE
#define CONF_R_NO_VALUE 108
Definition at line 208 of file conf.h.
Referenced by NCONF_get_string().
CONF_R_UNABLE_TO_CREATE_NEW_SECTION
#define CONF_R_UNABLE_TO_CREATE_NEW_SECTION 103
Definition at line 209 of file conf.h.
CONF_R_UNKNOWN_MODULE_NAME
#define CONF_R_UNKNOWN_MODULE_NAME 113
Definition at line 210 of file conf.h.
CONF_R_VARIABLE_HAS_NO_VALUE
#define CONF_R_VARIABLE_HAS_NO_VALUE 104
Definition at line 211 of file conf.h.
NCONF_get_number
#define NCONF_get_number (c, g, n, r) NCONF_get_number_e(c,g,n,r)
Definition at line 131 of file conf.h.
OPENSSL_no_config
#define OPENSSL_no_config () OPENSSL_init_crypto(OPENSSL_INIT_NO_LOAD_CONFIG, NULL)
Definition at line 95 of file conf.h.
Typedef Documentation
conf_finish_func
typedef void conf_finish_func(CONF_IMODULE *md)
Definition at line 61 of file conf.h.
conf_init_func
typedef int conf_init_func(CONF_IMODULE *md, const CONF *cnf)
Definition at line 60 of file conf.h.
Function Documentation
CONF_dump_bio()
int CONF_dump_bio (LHASH_OF(CONF_VALUE) * conf, BIO * out)
Definition at line 164 of file conf_lib.c.
CONF_dump_fp()
int CONF_dump_fp (LHASH_OF(CONF_VALUE) * conf, FILE * out)
Definition at line 149 of file conf_lib.c.
CONF_free()
void CONF_free (LHASH_OF(CONF_VALUE) * conf)
Definition at line 141 of file conf_lib.c.
References CONF_set_nconf(), and NCONF_free_data().
CONF_get1_default_config_file()
char* CONF_get1_default_config_file (void)
Definition at line 476 of file conf_mod.c.
References file, len, NULL, OPENSSL_CONF, OPENSSL_malloc, OPENSSL_strdup, OPENSSL_strlcat(), OPENSSL_strlcpy(), and X509_get_default_cert_area().
CONF_get_number()
long CONF_get_number (LHASH_OF(CONF_VALUE) * conf, const char * group, const char * name)
Definition at line 120 of file conf_lib.c.
References CONF_set_nconf(), ERR_clear_error(), NCONF_get_number_e(), and NULL.
CONF_get_string()
char* CONF_get_string (LHASH_OF(CONF_VALUE) * conf, const char * group, const char * name)
Definition at line 108 of file conf_lib.c.
References CONF_set_nconf(), NCONF_get_string(), and NULL.
CONF_imodule_get_flags()
unsigned long CONF_imodule_get_flags (const CONF_IMODULE * md)
Definition at line 454 of file conf_mod.c.
CONF_imodule_get_module()
CONF_MODULE* CONF_imodule_get_module (const CONF_IMODULE * md)
Definition at line 449 of file conf_mod.c.
CONF_imodule_get_name()
const char* CONF_imodule_get_name (const CONF_IMODULE * md)
Definition at line 429 of file conf_mod.c.
CONF_imodule_get_usr_data()
void* CONF_imodule_get_usr_data (const CONF_IMODULE * md)
Definition at line 439 of file conf_mod.c.
CONF_imodule_get_value()
const char* CONF_imodule_get_value (const CONF_IMODULE * md)
Definition at line 434 of file conf_mod.c.
CONF_imodule_set_flags()
void CONF_imodule_set_flags (CONF_IMODULE * md, unsigned long flags)
Definition at line 459 of file conf_mod.c.
References flags.
CONF_imodule_set_usr_data()
void CONF_imodule_set_usr_data (CONF_IMODULE * md, void * usr_data)
Definition at line 444 of file conf_mod.c.
References CONF_MODULE::usr_data.
CONF_module_add()
int CONF_module_add (const char * name, conf_init_func * ifunc, conf_finish_func * ffunc)
Definition at line 412 of file conf_mod.c.
Referenced by ASN1_add_oid_module(), ASN1_add_stable_module(), ENGINE_add_conf_module(), EVP_add_alg_module(), and SSL_add_ssl_module().
CONF_module_get_usr_data()
void* CONF_module_get_usr_data (CONF_MODULE * pmod)
Definition at line 464 of file conf_mod.c.
CONF_module_set_usr_data()
void CONF_module_set_usr_data (CONF_MODULE * pmod, void * usr_data)
Definition at line 469 of file conf_mod.c.
References CONF_MODULE::usr_data.
CONF_modules_finish()
void CONF_modules_finish (void)
Definition at line 385 of file conf_mod.c.
Referenced by conf_modules_free_int().
CONF_modules_load()
int CONF_modules_load (const CONF * cnf, const char * appname, unsigned long flags)
CONF_modules_load_file()
int CONF_modules_load_file (const char * filename, const char * appname, unsigned long flags)
Definition at line 112 of file conf_mod.c.
References file, and NULL.
CONF_modules_unload()
void CONF_modules_unload (int all)
Definition at line 354 of file conf_mod.c.
Referenced by conf_modules_free_int().
CONF_parse_list()
int CONF_parse_list (const char * list, int sep, int nospc, int(*)(const char *elem, int len, void *usr) list_cb, void * arg)
Definition at line 511 of file conf_mod.c.
Referenced by ASN1_str2mask(), ENGINE_set_default_string(), and tls1_set_groups_list().
CONF_set_default_method()
int CONF_set_default_method (CONF_METHOD * meth)
Definition at line 38 of file conf_lib.c.
CONF_set_nconf()
void CONF_set_nconf (CONF * conf, LHASH_OF(CONF_VALUE) * hash)
Definition at line 24 of file conf_lib.c.
Referenced by CONF_free(), CONF_get_number(), CONF_get_string(), STACK_OF(), X509V3_EXT_conf(), X509V3_EXT_conf_nid(), X509V3_EXT_CRL_add_conf(), and X509V3_EXT_REQ_add_conf().
DEFINE_LHASH_OF()
DEFINE_LHASH_OF (CONF_VALUE)
ERR_load_CONF_strings()
int ERR_load_CONF_strings (void)
Definition at line 69 of file conf_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
LHASH_OF()
LHASH_OF (CONF_VALUE)
NCONF_default()
CONF_METHOD* NCONF_default (void)
Definition at line 68 of file conf_def.c.
NCONF_dump_bio()
int NCONF_dump_bio (const CONF * conf, BIO * out)
Definition at line 318 of file conf_lib.c.
NCONF_dump_fp()
int NCONF_dump_fp (const CONF * conf, FILE * out)
Definition at line 304 of file conf_lib.c.
NCONF_free()
void NCONF_free (CONF * conf)
Definition at line 195 of file conf_lib.c.
References NULL.
NCONF_free_data()
void NCONF_free_data (CONF * conf)
Definition at line 202 of file conf_lib.c.
References NULL.
Referenced by CONF_free().
NCONF_get_number_e()
int NCONF_get_number_e (const CONF * conf, const char * group, const char * name, long * result)
Definition at line 280 of file conf_lib.c.
References CONF_F_NCONF_GET_NUMBER_E, CONFerr, ERR_R_PASSED_NULL_PARAMETER, NCONF_get_string(), and NULL.
Referenced by CONF_get_number().
NCONF_get_string()
char* NCONF_get_string (const CONF * conf, const char * group, const char * name)
Definition at line 259 of file conf_lib.c.
References _CONF_get_string(), CONF_F_NCONF_GET_STRING, CONF_R_NO_CONF_OR_ENVIRONMENT_VARIABLE, CONF_R_NO_VALUE, CONFerr, ERR_add_error_data(), and NULL.
Referenced by CONF_get_string(), and NCONF_get_number_e().
NCONF_load()
int NCONF_load (CONF * conf, const char * file, long * eline)
Definition at line 209 of file conf_lib.c.
References CONF_F_NCONF_LOAD, CONF_R_NO_CONF, CONFerr, and NULL.
NCONF_load_bio()
int NCONF_load_bio (CONF * conf, BIO * bp, long * eline)
Definition at line 234 of file conf_lib.c.
References CONF_F_NCONF_GET_SECTION, CONF_F_NCONF_LOAD_BIO, CONF_R_NO_CONF, CONF_R_NO_SECTION, CONFerr, NULL, section, and STACK_OF().
NCONF_load_fp()
int NCONF_load_fp (CONF * conf, FILE * fp, long * eline)
Definition at line 220 of file conf_lib.c.
NCONF_new()
CONF* NCONF_new (CONF_METHOD * meth)
Definition at line 179 of file conf_lib.c.
NCONF_WIN32()
CONF_METHOD* NCONF_WIN32 (void)
Definition at line 73 of file conf_def.c.
OPENSSL_load_builtin_modules()
void OPENSSL_load_builtin_modules (void)
Definition at line 20 of file conf_mall.c.
References ASN1_add_oid_module(), ASN1_add_stable_module(), ENGINE_add_conf_module(), and EVP_add_alg_module().
STACK_OF()
STACK_OF (CONF_VALUE)
Variable Documentation
bp
BIO* bp
Definition at line 78 of file conf.h.
Referenced by bn_mul_mont(), bn_sqr_comba4(), BN_uadd(), BN_ucmp(), BN_usub(), d2i_PKCS8PrivateKey_fp(), LHASH_OF(), main(), OPENSSL_LH_node_stats(), OPENSSL_LH_node_usage_stats(), OPENSSL_LH_stats(), and parse_name().
eline
BIO long * eline
Definition at line 72 of file conf.h.
Referenced by LHASH_OF().
file
const char* file
Definition at line 72 of file conf.h.
Referenced by CONF_get1_default_config_file(), CONF_modules_load_file(), ERR_put_error(), load_key(), load_pubkey(), and openssl_fopen().
fp
FILE* fp
Definition at line 75 of file conf.h.
Referenced by bio_open_owner(), BN_CTX_end(), comp_zlib_cleanup_int(), IDEA_set_decrypt_key(), LHASH_OF(), and ssl3_ctx_callback_ctrl().
section
const char * section
Definition at line 81 of file conf.h.
Referenced by NCONF_load_bio().