include/openssl/bio.h File Reference
bio.h File Reference
#include <openssl/e_os2.h>
#include <stdio.h>
#include <stdarg.h>
#include <openssl/crypto.h>
#include <stdint.h>
Data Structures
struct bio_dgram_sctp_sndinfo
struct bio_dgram_sctp_rcvinfo
struct bio_dgram_sctp_prinfo
union BIO_sock_info_u
Macros
#define BIO_TYPE_DESCRIPTOR 0x0100 /* socket, fd, connect or accept */
#define BIO_TYPE_FILTER 0x0200
#define BIO_TYPE_SOURCE_SINK 0x0400
#define BIO_TYPE_NONE 0
#define BIO_TYPE_MEM (1|BIO_TYPE_SOURCE_SINK)
#define BIO_TYPE_FILE (2|BIO_TYPE_SOURCE_SINK)
#define BIO_TYPE_FD (4|BIO_TYPE_SOURCE_SINK|BIO_TYPE_DESCRIPTOR)
#define BIO_TYPE_SOCKET (5|BIO_TYPE_SOURCE_SINK|BIO_TYPE_DESCRIPTOR)
#define BIO_TYPE_NULL (6|BIO_TYPE_SOURCE_SINK)
#define BIO_TYPE_SSL (7|BIO_TYPE_FILTER)
#define BIO_TYPE_MD (8|BIO_TYPE_FILTER)
#define BIO_TYPE_BUFFER (9|BIO_TYPE_FILTER)
#define BIO_TYPE_CIPHER (10|BIO_TYPE_FILTER)
#define BIO_TYPE_BASE64 (11|BIO_TYPE_FILTER)
#define BIO_TYPE_CONNECT (12|BIO_TYPE_SOURCE_SINK|BIO_TYPE_DESCRIPTOR)
#define BIO_TYPE_ACCEPT (13|BIO_TYPE_SOURCE_SINK|BIO_TYPE_DESCRIPTOR)
#define BIO_TYPE_NBIO_TEST (16|BIO_TYPE_FILTER)/* server proxy BIO */
#define BIO_TYPE_NULL_FILTER (17|BIO_TYPE_FILTER)
#define BIO_TYPE_BIO (19|BIO_TYPE_SOURCE_SINK)/* half a BIO pair */
#define BIO_TYPE_LINEBUFFER (20|BIO_TYPE_FILTER)
#define BIO_TYPE_DGRAM (21|BIO_TYPE_SOURCE_SINK|BIO_TYPE_DESCRIPTOR)
#define BIO_TYPE_ASN1 (22|BIO_TYPE_FILTER)
#define BIO_TYPE_COMP (23|BIO_TYPE_FILTER)
#define BIO_TYPE_DGRAM_SCTP (24|BIO_TYPE_SOURCE_SINK|BIO_TYPE_DESCRIPTOR)
#define BIO_TYPE_START 128
#define BIO_NOCLOSE 0x00
#define BIO_CLOSE 0x01
#define BIO_CTRL_RESET 1/* opt - rewind/zero etc */
#define BIO_CTRL_EOF 2/* opt - are we at the eof */
#define BIO_CTRL_INFO 3/* opt - extra tit-bits */
#define BIO_CTRL_SET 4/* man - set the 'IO' type */
#define BIO_CTRL_GET 5/* man - get the 'IO' type */
#define BIO_CTRL_PUSH 6/* opt - internal, used to signify change */
#define BIO_CTRL_POP 7/* opt - internal, used to signify change */
#define BIO_CTRL_GET_CLOSE 8/* man - set the 'close' on free */
#define BIO_CTRL_SET_CLOSE 9/* man - set the 'close' on free */
#define BIO_CTRL_PENDING 10/* opt - is their more data buffered */
#define BIO_CTRL_FLUSH 11/* opt - 'flush' buffered output */
#define BIO_CTRL_DUP 12/* man - extra stuff for 'duped' BIO */
#define BIO_CTRL_WPENDING 13/* opt - number of bytes still to write */
#define BIO_CTRL_SET_CALLBACK 14/* opt - set callback function */
#define BIO_CTRL_GET_CALLBACK 15/* opt - set callback function */
#define BIO_CTRL_SET_FILENAME 30/* BIO_s_file special */
#define BIO_CTRL_DGRAM_CONNECT 31/* BIO dgram special */
#define BIO_CTRL_DGRAM_SET_CONNECTED
#define BIO_CTRL_DGRAM_SET_RECV_TIMEOUT 33/* setsockopt, essentially */
#define BIO_CTRL_DGRAM_GET_RECV_TIMEOUT 34/* getsockopt, essentially */
#define BIO_CTRL_DGRAM_SET_SEND_TIMEOUT 35/* setsockopt, essentially */
#define BIO_CTRL_DGRAM_GET_SEND_TIMEOUT 36/* getsockopt, essentially */
#define BIO_CTRL_DGRAM_GET_RECV_TIMER_EXP 37/* flag whether the last */
#define BIO_CTRL_DGRAM_GET_SEND_TIMER_EXP 38/* I/O operation tiemd out */
#define BIO_CTRL_DGRAM_MTU_DISCOVER 39/* set DF bit on egress packets */
#define BIO_CTRL_DGRAM_QUERY_MTU 40/* as kernel for current MTU */
#define BIO_CTRL_DGRAM_GET_FALLBACK_MTU 47
#define BIO_CTRL_DGRAM_GET_MTU 41/* get cached value for MTU */
#define BIO_CTRL_DGRAM_SET_MTU
#define BIO_CTRL_DGRAM_MTU_EXCEEDED
#define BIO_CTRL_DGRAM_GET_PEER 46
#define BIO_CTRL_DGRAM_SET_PEER 44/* Destination for the data */
#define BIO_CTRL_DGRAM_SET_NEXT_TIMEOUT
#define BIO_CTRL_DGRAM_SET_DONT_FRAG 48
#define BIO_CTRL_DGRAM_GET_MTU_OVERHEAD 49
#define BIO_CTRL_DGRAM_SET_PEEK_MODE 50
#define BIO_CTRL_DGRAM_SCTP_SET_IN_HANDSHAKE 50
#define BIO_CTRL_DGRAM_SCTP_ADD_AUTH_KEY 51
#define BIO_CTRL_DGRAM_SCTP_NEXT_AUTH_KEY 52
#define BIO_CTRL_DGRAM_SCTP_AUTH_CCS_RCVD 53
#define BIO_CTRL_DGRAM_SCTP_GET_SNDINFO 60
#define BIO_CTRL_DGRAM_SCTP_SET_SNDINFO 61
#define BIO_CTRL_DGRAM_SCTP_GET_RCVINFO 62
#define BIO_CTRL_DGRAM_SCTP_SET_RCVINFO 63
#define BIO_CTRL_DGRAM_SCTP_GET_PRINFO 64
#define BIO_CTRL_DGRAM_SCTP_SET_PRINFO 65
#define BIO_CTRL_DGRAM_SCTP_SAVE_SHUTDOWN 70
#define BIO_FP_READ 0x02
#define BIO_FP_WRITE 0x04
#define BIO_FP_APPEND 0x08
#define BIO_FP_TEXT 0x10
#define BIO_FLAGS_READ 0x01
#define BIO_FLAGS_WRITE 0x02
#define BIO_FLAGS_IO_SPECIAL 0x04
#define BIO_FLAGS_RWS (BIO_FLAGS_READ|BIO_FLAGS_WRITE|BIO_FLAGS_IO_SPECIAL)
#define BIO_FLAGS_SHOULD_RETRY 0x08
#define BIO_FLAGS_UPLINK 0
#define BIO_FLAGS_BASE64_NO_NL 0x100
#define BIO_FLAGS_MEM_RDONLY 0x200
#define BIO_FLAGS_NONCLEAR_RST 0x400
#define BIO_get_flags(b) BIO_test_flags(b, ~(0x0))
#define BIO_set_retry_special(b) BIO_set_flags(b, (BIO_FLAGS_IO_SPECIAL|BIO_FLAGS_SHOULD_RETRY))
#define BIO_set_retry_read(b) BIO_set_flags(b, (BIO_FLAGS_READ|BIO_FLAGS_SHOULD_RETRY))
#define BIO_set_retry_write(b) BIO_set_flags(b, (BIO_FLAGS_WRITE|BIO_FLAGS_SHOULD_RETRY))
#define BIO_clear_retry_flags(b) BIO_clear_flags(b, (BIO_FLAGS_RWS|BIO_FLAGS_SHOULD_RETRY))
#define BIO_get_retry_flags(b) BIO_test_flags(b, (BIO_FLAGS_RWS|BIO_FLAGS_SHOULD_RETRY))
#define BIO_should_read(a) BIO_test_flags(a, BIO_FLAGS_READ)
#define BIO_should_write(a) BIO_test_flags(a, BIO_FLAGS_WRITE)
#define BIO_should_io_special(a) BIO_test_flags(a, BIO_FLAGS_IO_SPECIAL)
#define BIO_retry_type(a) BIO_test_flags(a, BIO_FLAGS_RWS)
#define BIO_should_retry(a) BIO_test_flags(a, BIO_FLAGS_SHOULD_RETRY)
#define BIO_RR_SSL_X509_LOOKUP 0x01
#define BIO_RR_CONNECT 0x02
#define BIO_RR_ACCEPT 0x03
#define BIO_CB_FREE 0x01
#define BIO_CB_READ 0x02
#define BIO_CB_WRITE 0x03
#define BIO_CB_PUTS 0x04
#define BIO_CB_GETS 0x05
#define BIO_CB_CTRL 0x06
#define BIO_CB_RETURN 0x80
#define BIO_CB_return(a) ((a)|BIO_CB_RETURN)
#define BIO_cb_pre(a) (!((a)&BIO_CB_RETURN))
#define BIO_cb_post(a) ((a)&BIO_CB_RETURN)
#define BIO_C_SET_CONNECT 100
#define BIO_C_DO_STATE_MACHINE 101
#define BIO_C_SET_NBIO 102
#define BIO_C_SET_FD 104
#define BIO_C_GET_FD 105
#define BIO_C_SET_FILE_PTR 106
#define BIO_C_GET_FILE_PTR 107
#define BIO_C_SET_FILENAME 108
#define BIO_C_SET_SSL 109
#define BIO_C_GET_SSL 110
#define BIO_C_SET_MD 111
#define BIO_C_GET_MD 112
#define BIO_C_GET_CIPHER_STATUS 113
#define BIO_C_SET_BUF_MEM 114
#define BIO_C_GET_BUF_MEM_PTR 115
#define BIO_C_GET_BUFF_NUM_LINES 116
#define BIO_C_SET_BUFF_SIZE 117
#define BIO_C_SET_ACCEPT 118
#define BIO_C_SSL_MODE 119
#define BIO_C_GET_MD_CTX 120
#define BIO_C_SET_BUFF_READ_DATA 122/* data to read first */
#define BIO_C_GET_CONNECT 123
#define BIO_C_GET_ACCEPT 124
#define BIO_C_SET_SSL_RENEGOTIATE_BYTES 125
#define BIO_C_GET_SSL_NUM_RENEGOTIATES 126
#define BIO_C_SET_SSL_RENEGOTIATE_TIMEOUT 127
#define BIO_C_FILE_SEEK 128
#define BIO_C_GET_CIPHER_CTX 129
#define BIO_C_SET_BUF_MEM_EOF_RETURN
#define BIO_C_SET_BIND_MODE 131
#define BIO_C_GET_BIND_MODE 132
#define BIO_C_FILE_TELL 133
#define BIO_C_GET_SOCKS 134
#define BIO_C_SET_SOCKS 135
#define BIO_C_SET_WRITE_BUF_SIZE 136/* for BIO_s_bio */
#define BIO_C_GET_WRITE_BUF_SIZE 137
#define BIO_C_MAKE_BIO_PAIR 138
#define BIO_C_DESTROY_BIO_PAIR 139
#define BIO_C_GET_WRITE_GUARANTEE 140
#define BIO_C_GET_READ_REQUEST 141
#define BIO_C_SHUTDOWN_WR 142
#define BIO_C_NREAD0 143
#define BIO_C_NREAD 144
#define BIO_C_NWRITE0 145
#define BIO_C_NWRITE 146
#define BIO_C_RESET_READ_REQUEST 147
#define BIO_C_SET_MD_CTX 148
#define BIO_C_SET_PREFIX 149
#define BIO_C_GET_PREFIX 150
#define BIO_C_SET_SUFFIX 151
#define BIO_C_GET_SUFFIX 152
#define BIO_C_SET_EX_ARG 153
#define BIO_C_GET_EX_ARG 154
#define BIO_C_SET_CONNECT_MODE 155
#define BIO_set_app_data(s, arg) BIO_set_ex_data(s,0,arg)
#define BIO_get_app_data(s) BIO_get_ex_data(s,0)
#define BIO_set_nbio(b, n) BIO_ctrl(b,BIO_C_SET_NBIO,(n),NULL)
#define BIO_FAMILY_IPV4 4
#define BIO_FAMILY_IPV6 6
#define BIO_FAMILY_IPANY 256
#define BIO_set_conn_hostname(b, name) BIO_ctrl(b,BIO_C_SET_CONNECT,0,(char *)name)
#define BIO_set_conn_port(b, port) BIO_ctrl(b,BIO_C_SET_CONNECT,1,(char *)port)
#define BIO_set_conn_address(b, addr) BIO_ctrl(b,BIO_C_SET_CONNECT,2,(char *)addr)
#define BIO_set_conn_ip_family(b, f) BIO_int_ctrl(b,BIO_C_SET_CONNECT,3,f)
#define BIO_get_conn_hostname(b) ((const char *)BIO_ptr_ctrl(b,BIO_C_GET_CONNECT,0))
#define BIO_get_conn_port(b) ((const char *)BIO_ptr_ctrl(b,BIO_C_GET_CONNECT,1))
#define BIO_get_conn_address(b) ((const BIO_ADDR *)BIO_ptr_ctrl(b,BIO_C_GET_CONNECT,2))
#define BIO_get_conn_ip_family(b) BIO_ctrl(b,BIO_C_GET_CONNECT,3,NULL)
#define BIO_set_conn_mode(b, n) BIO_ctrl(b,BIO_C_SET_CONNECT_MODE,(n),NULL)
#define BIO_set_accept_name(b, name) BIO_ctrl(b,BIO_C_SET_ACCEPT,0,(char *)name)
#define BIO_set_accept_port(b, port) BIO_ctrl(b,BIO_C_SET_ACCEPT,1,(char *)port)
#define BIO_get_accept_name(b) ((const char *)BIO_ptr_ctrl(b,BIO_C_GET_ACCEPT,0))
#define BIO_get_accept_port(b) ((const char *)BIO_ptr_ctrl(b,BIO_C_GET_ACCEPT,1))
#define BIO_get_peer_name(b) ((const char *)BIO_ptr_ctrl(b,BIO_C_GET_ACCEPT,2))
#define BIO_get_peer_port(b) ((const char *)BIO_ptr_ctrl(b,BIO_C_GET_ACCEPT,3))
#define BIO_set_nbio_accept(b, n) BIO_ctrl(b,BIO_C_SET_ACCEPT,2,(n)?(void *)"a":NULL)
#define BIO_set_accept_bios(b, bio) BIO_ctrl(b,BIO_C_SET_ACCEPT,3,(char *)bio)
#define BIO_set_accept_ip_family(b, f) BIO_int_ctrl(b,BIO_C_SET_ACCEPT,4,f)
#define BIO_get_accept_ip_family(b) BIO_ctrl(b,BIO_C_GET_ACCEPT,4,NULL)
#define BIO_BIND_NORMAL 0
#define BIO_BIND_REUSEADDR BIO_SOCK_REUSEADDR
#define BIO_BIND_REUSEADDR_IF_UNUSED BIO_SOCK_REUSEADDR
#define BIO_set_bind_mode(b, mode) BIO_ctrl(b,BIO_C_SET_BIND_MODE,mode,NULL)
#define BIO_get_bind_mode(b) BIO_ctrl(b,BIO_C_GET_BIND_MODE,0,NULL)
#define BIO_do_connect(b) BIO_do_handshake(b)
#define BIO_do_accept(b) BIO_do_handshake(b)
#define BIO_do_handshake(b) BIO_ctrl(b,BIO_C_DO_STATE_MACHINE,0,NULL)
#define BIO_set_fd(b, fd, c) BIO_int_ctrl(b,BIO_C_SET_FD,c,fd)
#define BIO_get_fd(b, c) BIO_ctrl(b,BIO_C_GET_FD,0,(char *)c)
#define BIO_set_fp(b, fp, c) BIO_ctrl(b,BIO_C_SET_FILE_PTR,c,(char *)fp)
#define BIO_get_fp(b, fpp) BIO_ctrl(b,BIO_C_GET_FILE_PTR,0,(char *)fpp)
#define BIO_seek(b, ofs) (int)BIO_ctrl(b,BIO_C_FILE_SEEK,ofs,NULL)
#define BIO_tell(b) (int)BIO_ctrl(b,BIO_C_FILE_TELL,0,NULL)
#define BIO_read_filename(b, name)
#define BIO_write_filename(b, name)
#define BIO_append_filename(b, name)
#define BIO_rw_filename(b, name)
#define BIO_set_ssl(b, ssl, c) BIO_ctrl(b,BIO_C_SET_SSL,c,(char *)ssl)
#define BIO_get_ssl(b, sslp) BIO_ctrl(b,BIO_C_GET_SSL,0,(char *)sslp)
#define BIO_set_ssl_mode(b, client) BIO_ctrl(b,BIO_C_SSL_MODE,client,NULL)
#define BIO_set_ssl_renegotiate_bytes(b, num) BIO_ctrl(b,BIO_C_SET_SSL_RENEGOTIATE_BYTES,num,NULL)
#define BIO_get_num_renegotiates(b) BIO_ctrl(b,BIO_C_GET_SSL_NUM_RENEGOTIATES,0,NULL)
#define BIO_set_ssl_renegotiate_timeout(b, seconds) BIO_ctrl(b,BIO_C_SET_SSL_RENEGOTIATE_TIMEOUT,seconds,NULL)
#define BIO_get_mem_data(b, pp) BIO_ctrl(b,BIO_CTRL_INFO,0,(char *)pp)
#define BIO_set_mem_buf(b, bm, c) BIO_ctrl(b,BIO_C_SET_BUF_MEM,c,(char *)bm)
#define BIO_get_mem_ptr(b, pp) BIO_ctrl(b,BIO_C_GET_BUF_MEM_PTR,0,(char *)pp)
#define BIO_set_mem_eof_return(b, v) BIO_ctrl(b,BIO_C_SET_BUF_MEM_EOF_RETURN,v,NULL)
#define BIO_get_buffer_num_lines(b) BIO_ctrl(b,BIO_C_GET_BUFF_NUM_LINES,0,NULL)
#define BIO_set_buffer_size(b, size) BIO_ctrl(b,BIO_C_SET_BUFF_SIZE,size,NULL)
#define BIO_set_read_buffer_size(b, size) BIO_int_ctrl(b,BIO_C_SET_BUFF_SIZE,size,0)
#define BIO_set_write_buffer_size(b, size) BIO_int_ctrl(b,BIO_C_SET_BUFF_SIZE,size,1)
#define BIO_set_buffer_read_data(b, buf, num) BIO_ctrl(b,BIO_C_SET_BUFF_READ_DATA,num,buf)
#define BIO_dup_state(b, ret) BIO_ctrl(b,BIO_CTRL_DUP,0,(char *)(ret))
#define BIO_reset(b) (int)BIO_ctrl(b,BIO_CTRL_RESET,0,NULL)
#define BIO_eof(b) (int)BIO_ctrl(b,BIO_CTRL_EOF,0,NULL)
#define BIO_set_close(b, c) (int)BIO_ctrl(b,BIO_CTRL_SET_CLOSE,(c),NULL)
#define BIO_get_close(b) (int)BIO_ctrl(b,BIO_CTRL_GET_CLOSE,0,NULL)
#define BIO_pending(b) (int)BIO_ctrl(b,BIO_CTRL_PENDING,0,NULL)
#define BIO_wpending(b) (int)BIO_ctrl(b,BIO_CTRL_WPENDING,0,NULL)
#define BIO_flush(b) (int)BIO_ctrl(b,BIO_CTRL_FLUSH,0,NULL)
#define BIO_get_info_callback(b, cbp)
#define BIO_set_info_callback(b, cb) (int)BIO_callback_ctrl(b,BIO_CTRL_SET_CALLBACK,cb)
#define BIO_buffer_get_num_lines(b) BIO_ctrl(b,BIO_CTRL_GET,0,NULL)
#define BIO_set_write_buf_size(b, size) (int)BIO_ctrl(b,BIO_C_SET_WRITE_BUF_SIZE,size,NULL)
#define BIO_get_write_buf_size(b, size) (size_t)BIO_ctrl(b,BIO_C_GET_WRITE_BUF_SIZE,size,NULL)
#define BIO_make_bio_pair(b1, b2) (int)BIO_ctrl(b1,BIO_C_MAKE_BIO_PAIR,0,b2)
#define BIO_destroy_bio_pair(b) (int)BIO_ctrl(b,BIO_C_DESTROY_BIO_PAIR,0,NULL)
#define BIO_shutdown_wr(b) (int)BIO_ctrl(b, BIO_C_SHUTDOWN_WR, 0, NULL)
#define BIO_get_write_guarantee(b) (int)BIO_ctrl(b,BIO_C_GET_WRITE_GUARANTEE,0,NULL)
#define BIO_get_read_request(b) (int)BIO_ctrl(b,BIO_C_GET_READ_REQUEST,0,NULL)
#define BIO_ctrl_dgram_connect(b, peer) (int)BIO_ctrl(b,BIO_CTRL_DGRAM_CONNECT,0, (char *)peer)
#define BIO_ctrl_set_connected(b, peer) (int)BIO_ctrl(b, BIO_CTRL_DGRAM_SET_CONNECTED, 0, (char *)peer)
#define BIO_dgram_recv_timedout(b) (int)BIO_ctrl(b, BIO_CTRL_DGRAM_GET_RECV_TIMER_EXP, 0, NULL)
#define BIO_dgram_send_timedout(b) (int)BIO_ctrl(b, BIO_CTRL_DGRAM_GET_SEND_TIMER_EXP, 0, NULL)
#define BIO_dgram_get_peer(b, peer) (int)BIO_ctrl(b, BIO_CTRL_DGRAM_GET_PEER, 0, (char *)peer)
#define BIO_dgram_set_peer(b, peer) (int)BIO_ctrl(b, BIO_CTRL_DGRAM_SET_PEER, 0, (char *)peer)
#define BIO_dgram_get_mtu_overhead(b) (unsigned int)BIO_ctrl((b), BIO_CTRL_DGRAM_GET_MTU_OVERHEAD, 0, NULL)
#define BIO_get_ex_new_index(l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_BIO, l, p, newf, dupf, freef)
#define BIO_sock_cleanup() while(0) continue
#define BIO_SOCK_REUSEADDR 0x01
#define BIO_SOCK_V6_ONLY 0x02
#define BIO_SOCK_KEEPALIVE 0x04
#define BIO_SOCK_NONBLOCK 0x08
#define BIO_SOCK_NODELAY 0x10
#define __bio_h__attr__(x)
#define BIO_F_ACPT_STATE 100
#define BIO_F_ADDR_STRINGS 134
#define BIO_F_BIO_ACCEPT 101
#define BIO_F_BIO_ACCEPT_EX 137
#define BIO_F_BIO_ADDR_NEW 144
#define BIO_F_BIO_CALLBACK_CTRL 131
#define BIO_F_BIO_CONNECT 138
#define BIO_F_BIO_CTRL 103
#define BIO_F_BIO_GETS 104
#define BIO_F_BIO_GET_HOST_IP 106
#define BIO_F_BIO_GET_NEW_INDEX 102
#define BIO_F_BIO_GET_PORT 107
#define BIO_F_BIO_LISTEN 139
#define BIO_F_BIO_LOOKUP 135
#define BIO_F_BIO_MAKE_PAIR 121
#define BIO_F_BIO_NEW 108
#define BIO_F_BIO_NEW_FILE 109
#define BIO_F_BIO_NEW_MEM_BUF 126
#define BIO_F_BIO_NREAD 123
#define BIO_F_BIO_NREAD0 124
#define BIO_F_BIO_NWRITE 125
#define BIO_F_BIO_NWRITE0 122
#define BIO_F_BIO_PARSE_HOSTSERV 136
#define BIO_F_BIO_PUTS 110
#define BIO_F_BIO_READ 111
#define BIO_F_BIO_READ_EX 105
#define BIO_F_BIO_READ_INTERN 120
#define BIO_F_BIO_SOCKET 140
#define BIO_F_BIO_SOCKET_NBIO 142
#define BIO_F_BIO_SOCK_INFO 141
#define BIO_F_BIO_SOCK_INIT 112
#define BIO_F_BIO_WRITE 113
#define BIO_F_BIO_WRITE_EX 119
#define BIO_F_BIO_WRITE_INTERN 128
#define BIO_F_BUFFER_CTRL 114
#define BIO_F_CONN_CTRL 127
#define BIO_F_CONN_STATE 115
#define BIO_F_DGRAM_SCTP_READ 132
#define BIO_F_DGRAM_SCTP_WRITE 133
#define BIO_F_FILE_CTRL 116
#define BIO_F_FILE_READ 130
#define BIO_F_LINEBUFFER_CTRL 129
#define BIO_F_MEM_WRITE 117
#define BIO_F_SSL_NEW 118
#define BIO_R_ACCEPT_ERROR 100
#define BIO_R_ADDRINFO_ADDR_IS_NOT_AF_INET 141
#define BIO_R_AMBIGUOUS_HOST_OR_SERVICE 129
#define BIO_R_BAD_FOPEN_MODE 101
#define BIO_R_BROKEN_PIPE 124
#define BIO_R_CONNECT_ERROR 103
#define BIO_R_GETHOSTBYNAME_ADDR_IS_NOT_AF_INET 107
#define BIO_R_GETSOCKNAME_ERROR 132
#define BIO_R_GETSOCKNAME_TRUNCATED_ADDRESS 133
#define BIO_R_GETTING_SOCKTYPE 134
#define BIO_R_INVALID_ARGUMENT 125
#define BIO_R_INVALID_SOCKET 135
#define BIO_R_IN_USE 123
#define BIO_R_LENGTH_TOO_LONG 102
#define BIO_R_LISTEN_V6_ONLY 136
#define BIO_R_LOOKUP_RETURNED_NOTHING 142
#define BIO_R_MALFORMED_HOST_OR_SERVICE 130
#define BIO_R_NBIO_CONNECT_ERROR 110
#define BIO_R_NO_ACCEPT_ADDR_OR_SERVICE_SPECIFIED 143
#define BIO_R_NO_HOSTNAME_OR_SERVICE_SPECIFIED 144
#define BIO_R_NO_PORT_DEFINED 113
#define BIO_R_NO_SUCH_FILE 128
#define BIO_R_NULL_PARAMETER 115
#define BIO_R_UNABLE_TO_BIND_SOCKET 117
#define BIO_R_UNABLE_TO_CREATE_SOCKET 118
#define BIO_R_UNABLE_TO_KEEPALIVE 137
#define BIO_R_UNABLE_TO_LISTEN_SOCKET 119
#define BIO_R_UNABLE_TO_NODELAY 138
#define BIO_R_UNABLE_TO_REUSEADDR 139
#define BIO_R_UNAVAILABLE_IP_FAMILY 145
#define BIO_R_UNINITIALIZED 120
#define BIO_R_UNKNOWN_INFO_TYPE 140
#define BIO_R_UNSUPPORTED_IP_FAMILY 146
#define BIO_R_UNSUPPORTED_METHOD 121
#define BIO_R_UNSUPPORTED_PROTOCOL_FAMILY 131
#define BIO_R_WRITE_TO_READ_ONLY_BIO 126
#define BIO_R_WSASTARTUP 122
Typedefs
typedef long(* BIO_callback_fn) (BIO *b, int oper, const char *argp, int argi, long argl, long ret)
typedef long(* BIO_callback_fn_ex) (BIO *b, int oper, const char *argp, size_t len, int argi, long argl, int ret, size_t *processed)
typedef void bio_info_cb(BIO *, int, const char *, int, long, long)
typedef int asn1_ps_func(BIO *b, unsigned char **pbuf, int *plen, void *parg)
Enumerations
enum BIO_hostserv_priorities { BIO_PARSE_PRIO_HOST, BIO_PARSE_PRIO_SERV }
enum BIO_lookup_type { BIO_LOOKUP_CLIENT, BIO_LOOKUP_SERVER }
enum BIO_sock_info_type { BIO_SOCK_INFO_ADDRESS }
Functions
int BIO_get_new_index (void)
void BIO_set_flags (BIO *b, int flags)
int BIO_test_flags (const BIO *b, int flags)
void BIO_clear_flags (BIO *b, int flags)
BIO_callback_fn BIO_get_callback (const BIO *b)
void BIO_set_callback (BIO *b, BIO_callback_fn callback)
BIO_callback_fn_ex BIO_get_callback_ex (const BIO *b)
void BIO_set_callback_ex (BIO *b, BIO_callback_fn_ex callback)
char * BIO_get_callback_arg (const BIO *b)
void BIO_set_callback_arg (BIO *b, char *arg)
const char * BIO_method_name (const BIO *b)
int BIO_method_type (const BIO *b)
size_t BIO_ctrl_pending (BIO *b)
size_t BIO_ctrl_wpending (BIO *b)
size_t BIO_ctrl_get_write_guarantee (BIO *b)
size_t BIO_ctrl_get_read_request (BIO *b)
int BIO_ctrl_reset_read_request (BIO *b)
int BIO_set_ex_data (BIO *bio, int idx, void *data)
void * BIO_get_ex_data (BIO *bio, int idx)
uint64_t BIO_number_read (BIO *bio)
uint64_t BIO_number_written (BIO *bio)
int BIO_asn1_set_prefix (BIO *b, asn1_ps_func *prefix, asn1_ps_func *prefix_free)
int BIO_asn1_get_prefix (BIO *b, asn1_ps_func **pprefix, asn1_ps_func **pprefix_free)
int BIO_asn1_set_suffix (BIO *b, asn1_ps_func *suffix, asn1_ps_func *suffix_free)
int BIO_asn1_get_suffix (BIO *b, asn1_ps_func **psuffix, asn1_ps_func **psuffix_free)
const BIO_METHOD * BIO_s_file (void)
BIO * BIO_new_file (const char *filename, const char *mode)
BIO * BIO_new_fp (FILE *stream, int close_flag)
BIO * BIO_new (const BIO_METHOD *type)
int BIO_free (BIO *a)
void BIO_set_data (BIO *a, void *ptr)
void * BIO_get_data (BIO *a)
void BIO_set_init (BIO *a, int init)
int BIO_get_init (BIO *a)
void BIO_set_shutdown (BIO *a, int shut)
int BIO_get_shutdown (BIO *a)
void BIO_vfree (BIO *a)
int BIO_up_ref (BIO *a)
int BIO_read (BIO *b, void *data, int dlen)
int BIO_read_ex (BIO *b, void *data, size_t dlen, size_t *readbytes)
int BIO_gets (BIO *bp, char *buf, int size)
int BIO_write (BIO *b, const void *data, int dlen)
int BIO_write_ex (BIO *b, const void *data, size_t dlen, size_t *written)
int BIO_puts (BIO *bp, const char *buf)
int BIO_indent (BIO *b, int indent, int max)
long BIO_ctrl (BIO *bp, int cmd, long larg, void *parg)
long BIO_callback_ctrl (BIO *b, int cmd, void(*fp)(BIO *, int, const char *, int, long, long))
void * BIO_ptr_ctrl (BIO *bp, int cmd, long larg)
long BIO_int_ctrl (BIO *bp, int cmd, long larg, int iarg)
BIO * BIO_push (BIO *b, BIO *append)
BIO * BIO_pop (BIO *b)
void BIO_free_all (BIO *a)
BIO * BIO_find_type (BIO *b, int bio_type)
BIO * BIO_next (BIO *b)
void BIO_set_next (BIO *b, BIO *next)
BIO * BIO_get_retry_BIO (BIO *bio, int *reason)
int BIO_get_retry_reason (BIO *bio)
void BIO_set_retry_reason (BIO *bio, int reason)
BIO * BIO_dup_chain (BIO *in)
int BIO_nread0 (BIO *bio, char **buf)
int BIO_nread (BIO *bio, char **buf, int num)
int BIO_nwrite0 (BIO *bio, char **buf)
int BIO_nwrite (BIO *bio, char **buf, int num)
long BIO_debug_callback (BIO *bio, int cmd, const char *argp, int argi, long argl, long ret)
const BIO_METHOD * BIO_s_mem (void)
const BIO_METHOD * BIO_s_secmem (void)
BIO * BIO_new_mem_buf (const void *buf, int len)
const BIO_METHOD * BIO_s_socket (void)
const BIO_METHOD * BIO_s_connect (void)
const BIO_METHOD * BIO_s_accept (void)
const BIO_METHOD * BIO_s_fd (void)
const BIO_METHOD * BIO_s_log (void)
const BIO_METHOD * BIO_s_bio (void)
const BIO_METHOD * BIO_s_null (void)
const BIO_METHOD * BIO_f_null (void)
const BIO_METHOD * BIO_f_buffer (void)
const BIO_METHOD * BIO_f_linebuffer (void)
const BIO_METHOD * BIO_f_nbio_test (void)
const BIO_METHOD * BIO_s_datagram (void)
int BIO_dgram_non_fatal_error (int error)
BIO * BIO_new_dgram (int fd, int close_flag)
const BIO_METHOD * BIO_s_datagram_sctp (void)
BIO * BIO_new_dgram_sctp (int fd, int close_flag)
int BIO_dgram_is_sctp (BIO *bio)
int BIO_dgram_sctp_notification_cb (BIO *b, void(*handle_notifications)(BIO *bio, void *context, void *buf), void *context)
int BIO_dgram_sctp_wait_for_dry (BIO *b)
int BIO_dgram_sctp_msg_waiting (BIO *b)
int BIO_sock_should_retry (int i)
int BIO_sock_non_fatal_error (int error)
int BIO_fd_should_retry (int i)
int BIO_fd_non_fatal_error (int error)
int BIO_dump_cb (int(*cb)(const void *data, size_t len, void *u), void *u, const char *s, int len)
int BIO_dump_indent_cb (int(*cb)(const void *data, size_t len, void *u), void *u, const char *s, int len, int indent)
int BIO_dump (BIO *b, const char *bytes, int len)
int BIO_dump_indent (BIO *b, const char *bytes, int len, int indent)
int BIO_dump_fp (FILE *fp, const char *s, int len)
int BIO_dump_indent_fp (FILE *fp, const char *s, int len, int indent)
int BIO_hex_string (BIO *out, int indent, int width, unsigned char *data, int datalen)
BIO_ADDR * BIO_ADDR_new (void)
int BIO_ADDR_rawmake (BIO_ADDR *ap, int family, const void *where, size_t wherelen, unsigned short port)
void BIO_ADDR_free (BIO_ADDR *)
void BIO_ADDR_clear (BIO_ADDR *ap)
int BIO_ADDR_family (const BIO_ADDR *ap)
int BIO_ADDR_rawaddress (const BIO_ADDR *ap, void *p, size_t *l)
unsigned short BIO_ADDR_rawport (const BIO_ADDR *ap)
char * BIO_ADDR_hostname_string (const BIO_ADDR *ap, int numeric)
char * BIO_ADDR_service_string (const BIO_ADDR *ap, int numeric)
char * BIO_ADDR_path_string (const BIO_ADDR *ap)
const BIO_ADDRINFO * BIO_ADDRINFO_next (const BIO_ADDRINFO *bai)
int BIO_ADDRINFO_family (const BIO_ADDRINFO *bai)
int BIO_ADDRINFO_socktype (const BIO_ADDRINFO *bai)
int BIO_ADDRINFO_protocol (const BIO_ADDRINFO *bai)
const BIO_ADDR * BIO_ADDRINFO_address (const BIO_ADDRINFO *bai)
void BIO_ADDRINFO_free (BIO_ADDRINFO *bai)
int BIO_parse_hostserv (const char *hostserv, char **host, char **service, enum BIO_hostserv_priorities hostserv_prio)
int BIO_lookup (const char *host, const char *service, enum BIO_lookup_type lookup_type, int family, int socktype, BIO_ADDRINFO **res)
int BIO_sock_error (int sock)
int BIO_socket_ioctl (int fd, long type, void *arg)
int BIO_socket_nbio (int fd, int mode)
int BIO_sock_init (void)
int BIO_set_tcp_ndelay (int sock, int turn_on)
int BIO_sock_info (int sock, enum BIO_sock_info_type type, union BIO_sock_info_u *info)
int BIO_socket (int domain, int socktype, int protocol, int options)
int BIO_connect (int sock, const BIO_ADDR *addr, int options)
int BIO_listen (int sock, const BIO_ADDR *addr, int options)
int BIO_accept_ex (int accept_sock, BIO_ADDR *addr, int options)
int BIO_closesocket (int sock)
BIO * BIO_new_socket (int sock, int close_flag)
BIO * BIO_new_connect (const char *host_port)
BIO * BIO_new_accept (const char *host_port)
BIO * BIO_new_fd (int fd, int close_flag)
int BIO_new_bio_pair (BIO **bio1, size_t writebuf1, BIO **bio2, size_t writebuf2)
void BIO_copy_next_retry (BIO *b)
int BIO_printf (BIO *bio, const char *format,...) __bio_h__attr__((__format__(__printf__
int int BIO_vprintf (BIO *bio, const char *format, va_list args) __bio_h__attr__((__format__(__printf__
int int int BIO_snprintf (char *buf, size_t n, const char *format,...) __bio_h__attr__((__format__(__printf__
int int int int BIO_vsnprintf (char *buf, size_t n, const char *format, va_list args) __bio_h__attr__((__format__(__printf__
int int int int BIO_METHOD * BIO_meth_new (int type, const char *name)
void BIO_meth_free (BIO_METHOD *biom)
int BIO_meth_set_write (BIO_METHOD *biom, int(*write)(BIO *, const char *, int))
int BIO_meth_set_write_ex (BIO_METHOD *biom, int(*bwrite)(BIO *, const char *, size_t, size_t *))
int BIO_meth_set_read (BIO_METHOD *biom, int(*read)(BIO *, char *, int))
int BIO_meth_set_read_ex (BIO_METHOD *biom, int(*bread)(BIO *, char *, size_t, size_t *))
int BIO_meth_set_puts (BIO_METHOD *biom, int(*puts)(BIO *, const char *))
int BIO_meth_set_gets (BIO_METHOD *biom, int(*gets)(BIO *, char *, int))
int BIO_meth_set_ctrl (BIO_METHOD *biom, long(*ctrl)(BIO *, int, long, void *))
int BIO_meth_set_create (BIO_METHOD *biom, int(*create)(BIO *))
int BIO_meth_set_destroy (BIO_METHOD *biom, int(*destroy)(BIO *))
int BIO_meth_set_callback_ctrl (BIO_METHOD *biom, long(*callback_ctrl)(BIO *, int, bio_info_cb *))
int ERR_load_BIO_strings (void)
Variables
int(*)(BIO *, const char *, int) BIO_meth_get_write (BIO_METHOD *biom)
int(*)(BIO *, const char *, size_t, size_t *) BIO_meth_get_write_ex (BIO_METHOD *biom)
int(*)(BIO *, char *, int) BIO_meth_get_read (BIO_METHOD *biom)
int(*)(BIO *, char *, size_t, size_t *) BIO_meth_get_read_ex (BIO_METHOD *biom)
int(*)(BIO *, const char *) BIO_meth_get_puts (BIO_METHOD *biom)
int(*)(BIO *, char *, int) BIO_meth_get_gets (BIO_METHOD *biom)
long(*)(BIO *, int, long, void *) BIO_meth_get_ctrl (BIO_METHOD *biom)
int(*)(BIO *) BIO_meth_get_create (BIO_METHOD *bion)
int(*)(BIO *) BIO_meth_get_destroy (BIO_METHOD *biom)
long(*)(BIO *, int, bio_info_cb *) BIO_meth_get_callback_ctrl (BIO_METHOD *biom)
Macro Definition Documentation
__bio_h__attr__
#define __bio_h__attr__ (x)
Definition at line 730 of file bio.h.
BIO_append_filename
#define BIO_append_filename (b, name)
Value:
(int)BIO_ctrl(b,BIO_C_SET_FILENAME, \
                BIO_CLOSE|BIO_FP_APPEND,name)
Definition at line 436 of file bio.h.
BIO_BIND_NORMAL
#define BIO_BIND_NORMAL 0
Definition at line 395 of file bio.h.
BIO_BIND_REUSEADDR
#define BIO_BIND_REUSEADDR BIO_SOCK_REUSEADDR
Definition at line 396 of file bio.h.
BIO_BIND_REUSEADDR_IF_UNUSED
#define BIO_BIND_REUSEADDR_IF_UNUSED BIO_SOCK_REUSEADDR
Definition at line 397 of file bio.h.
BIO_buffer_get_num_lines
#define BIO_buffer_get_num_lines (b) BIO_ctrl(b,BIO_CTRL_GET,0,NULL)
Definition at line 491 of file bio.h.
BIO_C_DESTROY_BIO_PAIR
#define BIO_C_DESTROY_BIO_PAIR 139
Definition at line 337 of file bio.h.
BIO_C_DO_STATE_MACHINE
#define BIO_C_DO_STATE_MACHINE 101
Definition at line 297 of file bio.h.
BIO_C_FILE_SEEK
#define BIO_C_FILE_SEEK 128
Definition at line 324 of file bio.h.
BIO_C_FILE_TELL
#define BIO_C_FILE_TELL 133
Definition at line 330 of file bio.h.
BIO_C_GET_ACCEPT
#define BIO_C_GET_ACCEPT 124
Definition at line 320 of file bio.h.
BIO_C_GET_BIND_MODE
#define BIO_C_GET_BIND_MODE 132
Definition at line 329 of file bio.h.
BIO_C_GET_BUF_MEM_PTR
#define BIO_C_GET_BUF_MEM_PTR 115
Definition at line 311 of file bio.h.
BIO_C_GET_BUFF_NUM_LINES
#define BIO_C_GET_BUFF_NUM_LINES 116
Definition at line 312 of file bio.h.
BIO_C_GET_CIPHER_CTX
#define BIO_C_GET_CIPHER_CTX 129
Definition at line 325 of file bio.h.
BIO_C_GET_CIPHER_STATUS
#define BIO_C_GET_CIPHER_STATUS 113
Definition at line 309 of file bio.h.
BIO_C_GET_CONNECT
#define BIO_C_GET_CONNECT 123
Definition at line 319 of file bio.h.
BIO_C_GET_EX_ARG
#define BIO_C_GET_EX_ARG 154
Definition at line 354 of file bio.h.
BIO_C_GET_FD
#define BIO_C_GET_FD 105
Definition at line 301 of file bio.h.
BIO_C_GET_FILE_PTR
#define BIO_C_GET_FILE_PTR 107
Definition at line 303 of file bio.h.
BIO_C_GET_MD
#define BIO_C_GET_MD 112
Definition at line 308 of file bio.h.
BIO_C_GET_MD_CTX
#define BIO_C_GET_MD_CTX 120
Definition at line 316 of file bio.h.
BIO_C_GET_PREFIX
#define BIO_C_GET_PREFIX 150
Definition at line 349 of file bio.h.
BIO_C_GET_READ_REQUEST
#define BIO_C_GET_READ_REQUEST 141
Definition at line 339 of file bio.h.
Referenced by BIO_ctrl_get_read_request().
BIO_C_GET_SOCKS
#define BIO_C_GET_SOCKS 134
Definition at line 331 of file bio.h.
BIO_C_GET_SSL
#define BIO_C_GET_SSL 110
Definition at line 306 of file bio.h.
BIO_C_GET_SSL_NUM_RENEGOTIATES
#define BIO_C_GET_SSL_NUM_RENEGOTIATES 126
Definition at line 322 of file bio.h.
BIO_C_GET_SUFFIX
#define BIO_C_GET_SUFFIX 152
Definition at line 351 of file bio.h.
BIO_C_GET_WRITE_BUF_SIZE
#define BIO_C_GET_WRITE_BUF_SIZE 137
Definition at line 335 of file bio.h.
BIO_C_GET_WRITE_GUARANTEE
#define BIO_C_GET_WRITE_GUARANTEE 140
Definition at line 338 of file bio.h.
Referenced by BIO_ctrl_get_write_guarantee().
BIO_C_MAKE_BIO_PAIR
#define BIO_C_MAKE_BIO_PAIR 138
Definition at line 336 of file bio.h.
BIO_C_NREAD
#define BIO_C_NREAD 144
Definition at line 342 of file bio.h.
BIO_C_NREAD0
#define BIO_C_NREAD0 143
Definition at line 341 of file bio.h.
BIO_C_NWRITE
#define BIO_C_NWRITE 146
Definition at line 344 of file bio.h.
BIO_C_NWRITE0
#define BIO_C_NWRITE0 145
Definition at line 343 of file bio.h.
BIO_C_RESET_READ_REQUEST
#define BIO_C_RESET_READ_REQUEST 147
Definition at line 345 of file bio.h.
Referenced by BIO_ctrl_reset_read_request().
BIO_C_SET_ACCEPT
#define BIO_C_SET_ACCEPT 118
Definition at line 314 of file bio.h.
BIO_C_SET_BIND_MODE
#define BIO_C_SET_BIND_MODE 131
Definition at line 328 of file bio.h.
BIO_C_SET_BUF_MEM
#define BIO_C_SET_BUF_MEM 114
Definition at line 310 of file bio.h.
BIO_C_SET_BUF_MEM_EOF_RETURN
#define BIO_C_SET_BUF_MEM_EOF_RETURN
Value:
130/* return end of input
                                                     * value */
Definition at line 326 of file bio.h.
BIO_C_SET_BUFF_READ_DATA
#define BIO_C_SET_BUFF_READ_DATA 122/* data to read first */
Definition at line 318 of file bio.h.
BIO_C_SET_BUFF_SIZE
#define BIO_C_SET_BUFF_SIZE 117
Definition at line 313 of file bio.h.
BIO_C_SET_CONNECT
#define BIO_C_SET_CONNECT 100
Definition at line 296 of file bio.h.
BIO_C_SET_CONNECT_MODE
#define BIO_C_SET_CONNECT_MODE 155
Definition at line 356 of file bio.h.
BIO_C_SET_EX_ARG
#define BIO_C_SET_EX_ARG 153
Definition at line 353 of file bio.h.
BIO_C_SET_FD
#define BIO_C_SET_FD 104
Definition at line 300 of file bio.h.
BIO_C_SET_FILE_PTR
#define BIO_C_SET_FILE_PTR 106
Definition at line 302 of file bio.h.
BIO_C_SET_FILENAME
#define BIO_C_SET_FILENAME 108
Definition at line 304 of file bio.h.
BIO_C_SET_MD
#define BIO_C_SET_MD 111
Definition at line 307 of file bio.h.
BIO_C_SET_MD_CTX
#define BIO_C_SET_MD_CTX 148
Definition at line 346 of file bio.h.
BIO_C_SET_NBIO
#define BIO_C_SET_NBIO 102
Definition at line 298 of file bio.h.
BIO_C_SET_PREFIX
#define BIO_C_SET_PREFIX 149
Definition at line 348 of file bio.h.
BIO_C_SET_SOCKS
#define BIO_C_SET_SOCKS 135
Definition at line 332 of file bio.h.
BIO_C_SET_SSL
#define BIO_C_SET_SSL 109
Definition at line 305 of file bio.h.
BIO_C_SET_SSL_RENEGOTIATE_BYTES
#define BIO_C_SET_SSL_RENEGOTIATE_BYTES 125
Definition at line 321 of file bio.h.
BIO_C_SET_SSL_RENEGOTIATE_TIMEOUT
#define BIO_C_SET_SSL_RENEGOTIATE_TIMEOUT 127
Definition at line 323 of file bio.h.
BIO_C_SET_SUFFIX
#define BIO_C_SET_SUFFIX 151
Definition at line 350 of file bio.h.
BIO_C_SET_WRITE_BUF_SIZE
#define BIO_C_SET_WRITE_BUF_SIZE 136/* for BIO_s_bio */
Definition at line 334 of file bio.h.
BIO_C_SHUTDOWN_WR
#define BIO_C_SHUTDOWN_WR 142
Definition at line 340 of file bio.h.
BIO_C_SSL_MODE
#define BIO_C_SSL_MODE 119
Definition at line 315 of file bio.h.
BIO_CB_CTRL
#define BIO_CB_CTRL 0x06
Definition at line 229 of file bio.h.
BIO_CB_FREE
#define BIO_CB_FREE 0x01
Definition at line 224 of file bio.h.
BIO_CB_GETS
#define BIO_CB_GETS 0x05
Definition at line 228 of file bio.h.
BIO_cb_post
#define BIO_cb_post (a) ((a)&BIO_CB_RETURN)
Definition at line 238 of file bio.h.
BIO_cb_pre
#define BIO_cb_pre (a) (!((a)&BIO_CB_RETURN))
Definition at line 237 of file bio.h.
BIO_CB_PUTS
#define BIO_CB_PUTS 0x04
Definition at line 227 of file bio.h.
BIO_CB_READ
#define BIO_CB_READ 0x02
Definition at line 225 of file bio.h.
BIO_CB_RETURN
#define BIO_CB_RETURN 0x80
Definition at line 235 of file bio.h.
BIO_CB_return
#define BIO_CB_return (a) ((a)|BIO_CB_RETURN)
Definition at line 236 of file bio.h.
BIO_CB_WRITE
#define BIO_CB_WRITE 0x03
Definition at line 226 of file bio.h.
BIO_clear_retry_flags
#define BIO_clear_retry_flags (b) BIO_clear_flags(b, (BIO_FLAGS_RWS|BIO_FLAGS_SHOULD_RETRY))
Definition at line 195 of file bio.h.
Referenced by ossl_statem_client_post_process_message(), ossl_statem_server_post_process_message(), and tls_post_process_client_key_exchange().
BIO_CLOSE
#define BIO_CLOSE 0x01
Definition at line 73 of file bio.h.
BIO_CTRL_DGRAM_CONNECT
#define BIO_CTRL_DGRAM_CONNECT 31/* BIO dgram special */
Definition at line 97 of file bio.h.
BIO_ctrl_dgram_connect
#define BIO_ctrl_dgram_connect (b, peer) (int)BIO_ctrl(b,BIO_CTRL_DGRAM_CONNECT,0, (char *)peer)
Definition at line 507 of file bio.h.
BIO_CTRL_DGRAM_GET_FALLBACK_MTU
#define BIO_CTRL_DGRAM_GET_FALLBACK_MTU 47
Definition at line 113 of file bio.h.
Referenced by dtls1_check_timeout_num().
BIO_CTRL_DGRAM_GET_MTU
#define BIO_CTRL_DGRAM_GET_MTU 41/* get cached value for MTU */
Definition at line 114 of file bio.h.
BIO_CTRL_DGRAM_GET_MTU_OVERHEAD
#define BIO_CTRL_DGRAM_GET_MTU_OVERHEAD 49
Definition at line 130 of file bio.h.
BIO_CTRL_DGRAM_GET_PEER
#define BIO_CTRL_DGRAM_GET_PEER 46
Definition at line 123 of file bio.h.
BIO_CTRL_DGRAM_GET_RECV_TIMEOUT
#define BIO_CTRL_DGRAM_GET_RECV_TIMEOUT 34/* getsockopt, essentially */
Definition at line 101 of file bio.h.
BIO_CTRL_DGRAM_GET_RECV_TIMER_EXP
#define BIO_CTRL_DGRAM_GET_RECV_TIMER_EXP 37/* flag whether the last */
Definition at line 105 of file bio.h.
BIO_CTRL_DGRAM_GET_SEND_TIMEOUT
#define BIO_CTRL_DGRAM_GET_SEND_TIMEOUT 36/* getsockopt, essentially */
Definition at line 103 of file bio.h.
BIO_CTRL_DGRAM_GET_SEND_TIMER_EXP
#define BIO_CTRL_DGRAM_GET_SEND_TIMER_EXP 38/* I/O operation tiemd out */
Definition at line 106 of file bio.h.
BIO_CTRL_DGRAM_MTU_DISCOVER
#define BIO_CTRL_DGRAM_MTU_DISCOVER 39/* set DF bit on egress packets */
Definition at line 109 of file bio.h.
BIO_CTRL_DGRAM_MTU_EXCEEDED
#define BIO_CTRL_DGRAM_MTU_EXCEEDED
Value:
43/* check whether the MTU was
                                              * exceed in the previous write
                                              * operation */
Definition at line 119 of file bio.h.
BIO_CTRL_DGRAM_QUERY_MTU
#define BIO_CTRL_DGRAM_QUERY_MTU 40/* as kernel for current MTU */
Definition at line 112 of file bio.h.
Referenced by dtls1_query_mtu().
BIO_CTRL_DGRAM_SCTP_ADD_AUTH_KEY
#define BIO_CTRL_DGRAM_SCTP_ADD_AUTH_KEY 51
Definition at line 137 of file bio.h.
Referenced by ossl_statem_server_post_work(), tls_client_key_exchange_post_work(), and tls_post_process_client_key_exchange().
BIO_CTRL_DGRAM_SCTP_AUTH_CCS_RCVD
#define BIO_CTRL_DGRAM_SCTP_AUTH_CCS_RCVD 53
Definition at line 139 of file bio.h.
BIO_CTRL_DGRAM_SCTP_GET_PRINFO
#define BIO_CTRL_DGRAM_SCTP_GET_PRINFO 64
Definition at line 144 of file bio.h.
BIO_CTRL_DGRAM_SCTP_GET_RCVINFO
#define BIO_CTRL_DGRAM_SCTP_GET_RCVINFO 62
Definition at line 142 of file bio.h.
Referenced by dtls1_buffer_record().
BIO_CTRL_DGRAM_SCTP_GET_SNDINFO
#define BIO_CTRL_DGRAM_SCTP_GET_SNDINFO 60
Definition at line 140 of file bio.h.
BIO_CTRL_DGRAM_SCTP_NEXT_AUTH_KEY
#define BIO_CTRL_DGRAM_SCTP_NEXT_AUTH_KEY 52
Definition at line 138 of file bio.h.
Referenced by ossl_statem_client_post_work(), and ossl_statem_server_post_work().
BIO_CTRL_DGRAM_SCTP_SAVE_SHUTDOWN
#define BIO_CTRL_DGRAM_SCTP_SAVE_SHUTDOWN 70
Definition at line 146 of file bio.h.
BIO_CTRL_DGRAM_SCTP_SET_IN_HANDSHAKE
#define BIO_CTRL_DGRAM_SCTP_SET_IN_HANDSHAKE 50
Definition at line 136 of file bio.h.
BIO_CTRL_DGRAM_SCTP_SET_PRINFO
#define BIO_CTRL_DGRAM_SCTP_SET_PRINFO 65
Definition at line 145 of file bio.h.
BIO_CTRL_DGRAM_SCTP_SET_RCVINFO
#define BIO_CTRL_DGRAM_SCTP_SET_RCVINFO 63
Definition at line 143 of file bio.h.
BIO_CTRL_DGRAM_SCTP_SET_SNDINFO
#define BIO_CTRL_DGRAM_SCTP_SET_SNDINFO 61
Definition at line 141 of file bio.h.
BIO_CTRL_DGRAM_SET_CONNECTED
#define BIO_CTRL_DGRAM_SET_CONNECTED
Value:
32/* allow for an externally connected
                                         * socket to be passed in */
Definition at line 98 of file bio.h.
BIO_CTRL_DGRAM_SET_DONT_FRAG
#define BIO_CTRL_DGRAM_SET_DONT_FRAG 48
Definition at line 128 of file bio.h.
BIO_CTRL_DGRAM_SET_MTU
#define BIO_CTRL_DGRAM_SET_MTU
Value:
42/* set cached value for MTU.
                                              * want to use this if asking
                                              * the kernel fails */
Definition at line 115 of file bio.h.
Referenced by dtls1_query_mtu().
BIO_CTRL_DGRAM_SET_NEXT_TIMEOUT
#define BIO_CTRL_DGRAM_SET_NEXT_TIMEOUT
Value:
45/* Next DTLS handshake timeout
                                              * to adjust socket timeouts */
Definition at line 126 of file bio.h.
Referenced by dtls1_stop_timer().
BIO_CTRL_DGRAM_SET_PEEK_MODE
#define BIO_CTRL_DGRAM_SET_PEEK_MODE 50
Definition at line 132 of file bio.h.
BIO_CTRL_DGRAM_SET_PEER
#define BIO_CTRL_DGRAM_SET_PEER 44/* Destination for the data */
Definition at line 124 of file bio.h.
BIO_CTRL_DGRAM_SET_RECV_TIMEOUT
#define BIO_CTRL_DGRAM_SET_RECV_TIMEOUT 33/* setsockopt, essentially */
Definition at line 100 of file bio.h.
BIO_CTRL_DGRAM_SET_SEND_TIMEOUT
#define BIO_CTRL_DGRAM_SET_SEND_TIMEOUT 35/* setsockopt, essentially */
Definition at line 102 of file bio.h.
BIO_CTRL_DUP
#define BIO_CTRL_DUP 12/* man - extra stuff for 'duped' BIO */
Definition at line 89 of file bio.h.
BIO_CTRL_EOF
#define BIO_CTRL_EOF 2/* opt - are we at the eof */
Definition at line 79 of file bio.h.
BIO_CTRL_FLUSH
#define BIO_CTRL_FLUSH 11/* opt - 'flush' buffered output */
Definition at line 88 of file bio.h.
BIO_CTRL_GET
#define BIO_CTRL_GET 5/* man - get the 'IO' type */
Definition at line 82 of file bio.h.
BIO_CTRL_GET_CALLBACK
#define BIO_CTRL_GET_CALLBACK 15/* opt - set callback function */
Definition at line 92 of file bio.h.
BIO_CTRL_GET_CLOSE
#define BIO_CTRL_GET_CLOSE 8/* man - set the 'close' on free */
Definition at line 85 of file bio.h.
BIO_CTRL_INFO
#define BIO_CTRL_INFO 3/* opt - extra tit-bits */
Definition at line 80 of file bio.h.
BIO_CTRL_PENDING
#define BIO_CTRL_PENDING 10/* opt - is their more data buffered */
Definition at line 87 of file bio.h.
Referenced by BIO_ctrl_pending().
BIO_CTRL_POP
#define BIO_CTRL_POP 7/* opt - internal, used to signify change */
Definition at line 84 of file bio.h.
BIO_CTRL_PUSH
#define BIO_CTRL_PUSH 6/* opt - internal, used to signify change */
Definition at line 83 of file bio.h.
Referenced by BIO_push().
BIO_CTRL_RESET
#define BIO_CTRL_RESET 1/* opt - rewind/zero etc */
Definition at line 78 of file bio.h.
BIO_CTRL_SET
#define BIO_CTRL_SET 4/* man - set the 'IO' type */
Definition at line 81 of file bio.h.
BIO_CTRL_SET_CALLBACK
#define BIO_CTRL_SET_CALLBACK 14/* opt - set callback function */
Definition at line 91 of file bio.h.
BIO_CTRL_SET_CLOSE
#define BIO_CTRL_SET_CLOSE 9/* man - set the 'close' on free */
Definition at line 86 of file bio.h.
BIO_ctrl_set_connected
#define BIO_ctrl_set_connected (b, peer) (int)BIO_ctrl(b, BIO_CTRL_DGRAM_SET_CONNECTED, 0, (char *)peer)
Definition at line 509 of file bio.h.
BIO_CTRL_SET_FILENAME
#define BIO_CTRL_SET_FILENAME 30/* BIO_s_file special */
Definition at line 94 of file bio.h.
BIO_CTRL_WPENDING
#define BIO_CTRL_WPENDING 13/* opt - number of bytes still to write */
Definition at line 90 of file bio.h.
Referenced by BIO_ctrl_wpending().
BIO_destroy_bio_pair
#define BIO_destroy_bio_pair (b) (int)BIO_ctrl(b,BIO_C_DESTROY_BIO_PAIR,0,NULL)
Definition at line 497 of file bio.h.
BIO_dgram_get_mtu_overhead
#define BIO_dgram_get_mtu_overhead (b) (unsigned int)BIO_ctrl((b), BIO_CTRL_DGRAM_GET_MTU_OVERHEAD, 0, NULL)
Definition at line 519 of file bio.h.
Referenced by dtls1_query_mtu().
BIO_dgram_get_peer
#define BIO_dgram_get_peer (b, peer) (int)BIO_ctrl(b, BIO_CTRL_DGRAM_GET_PEER, 0, (char *)peer)
Definition at line 515 of file bio.h.
BIO_dgram_recv_timedout
#define BIO_dgram_recv_timedout (b) (int)BIO_ctrl(b, BIO_CTRL_DGRAM_GET_RECV_TIMER_EXP, 0, NULL)
Definition at line 511 of file bio.h.
BIO_dgram_send_timedout
#define BIO_dgram_send_timedout (b) (int)BIO_ctrl(b, BIO_CTRL_DGRAM_GET_SEND_TIMER_EXP, 0, NULL)
Definition at line 513 of file bio.h.
BIO_dgram_set_peer
#define BIO_dgram_set_peer (b, peer) (int)BIO_ctrl(b, BIO_CTRL_DGRAM_SET_PEER, 0, (char *)peer)
Definition at line 517 of file bio.h.
BIO_do_accept
#define BIO_do_accept (b) BIO_do_handshake(b)
Definition at line 403 of file bio.h.
BIO_do_connect
#define BIO_do_connect (b) BIO_do_handshake(b)
Definition at line 402 of file bio.h.
BIO_do_handshake
#define BIO_do_handshake (b) BIO_ctrl(b,BIO_C_DO_STATE_MACHINE,0,NULL)
Definition at line 406 of file bio.h.
BIO_dup_state
#define BIO_dup_state (b, ret) BIO_ctrl(b,BIO_CTRL_DUP,0,(char *)(ret))
Definition at line 474 of file bio.h.
BIO_eof
#define BIO_eof (b) (int)BIO_ctrl(b,BIO_CTRL_EOF,0,NULL)
Definition at line 477 of file bio.h.
BIO_F_ACPT_STATE
#define BIO_F_ACPT_STATE 100
Definition at line 788 of file bio.h.
BIO_F_ADDR_STRINGS
#define BIO_F_ADDR_STRINGS 134
Definition at line 789 of file bio.h.
BIO_F_BIO_ACCEPT
#define BIO_F_BIO_ACCEPT 101
Definition at line 790 of file bio.h.
BIO_F_BIO_ACCEPT_EX
#define BIO_F_BIO_ACCEPT_EX 137
Definition at line 791 of file bio.h.
Referenced by BIO_accept_ex().
BIO_F_BIO_ADDR_NEW
#define BIO_F_BIO_ADDR_NEW 144
Definition at line 792 of file bio.h.
BIO_F_BIO_CALLBACK_CTRL
#define BIO_F_BIO_CALLBACK_CTRL 131
Definition at line 793 of file bio.h.
BIO_F_BIO_CONNECT
#define BIO_F_BIO_CONNECT 138
Definition at line 794 of file bio.h.
Referenced by BIO_connect().
BIO_F_BIO_CTRL
#define BIO_F_BIO_CTRL 103
Definition at line 795 of file bio.h.
BIO_F_BIO_GET_HOST_IP
#define BIO_F_BIO_GET_HOST_IP 106
Definition at line 797 of file bio.h.
BIO_F_BIO_GET_NEW_INDEX
#define BIO_F_BIO_GET_NEW_INDEX 102
Definition at line 798 of file bio.h.
BIO_F_BIO_GET_PORT
#define BIO_F_BIO_GET_PORT 107
Definition at line 799 of file bio.h.
BIO_F_BIO_GETS
#define BIO_F_BIO_GETS 104
Definition at line 796 of file bio.h.
BIO_F_BIO_LISTEN
#define BIO_F_BIO_LISTEN 139
Definition at line 800 of file bio.h.
Referenced by BIO_listen().
BIO_F_BIO_LOOKUP
#define BIO_F_BIO_LOOKUP 135
Definition at line 801 of file bio.h.
BIO_F_BIO_MAKE_PAIR
#define BIO_F_BIO_MAKE_PAIR 121
Definition at line 802 of file bio.h.
BIO_F_BIO_NEW
#define BIO_F_BIO_NEW 108
Definition at line 803 of file bio.h.
Referenced by BIO_new().
BIO_F_BIO_NEW_FILE
#define BIO_F_BIO_NEW_FILE 109
Definition at line 804 of file bio.h.
BIO_F_BIO_NEW_MEM_BUF
#define BIO_F_BIO_NEW_MEM_BUF 126
Definition at line 805 of file bio.h.
BIO_F_BIO_NREAD
#define BIO_F_BIO_NREAD 123
Definition at line 806 of file bio.h.
BIO_F_BIO_NREAD0
#define BIO_F_BIO_NREAD0 124
Definition at line 807 of file bio.h.
BIO_F_BIO_NWRITE
#define BIO_F_BIO_NWRITE 125
Definition at line 808 of file bio.h.
BIO_F_BIO_NWRITE0
#define BIO_F_BIO_NWRITE0 122
Definition at line 809 of file bio.h.
BIO_F_BIO_PARSE_HOSTSERV
#define BIO_F_BIO_PARSE_HOSTSERV 136
Definition at line 810 of file bio.h.
Referenced by BIO_parse_hostserv().
BIO_F_BIO_PUTS
#define BIO_F_BIO_PUTS 110
Definition at line 811 of file bio.h.
BIO_F_BIO_READ
#define BIO_F_BIO_READ 111
Definition at line 812 of file bio.h.
BIO_F_BIO_READ_EX
#define BIO_F_BIO_READ_EX 105
Definition at line 813 of file bio.h.
BIO_F_BIO_READ_INTERN
#define BIO_F_BIO_READ_INTERN 120
Definition at line 814 of file bio.h.
BIO_F_BIO_SOCK_INFO
#define BIO_F_BIO_SOCK_INFO 141
Definition at line 817 of file bio.h.
BIO_F_BIO_SOCK_INIT
#define BIO_F_BIO_SOCK_INIT 112
Definition at line 818 of file bio.h.
Referenced by BIO_sock_init().
BIO_F_BIO_SOCKET
#define BIO_F_BIO_SOCKET 140
Definition at line 815 of file bio.h.
Referenced by BIO_socket().
BIO_F_BIO_SOCKET_NBIO
#define BIO_F_BIO_SOCKET_NBIO 142
Definition at line 816 of file bio.h.
BIO_F_BIO_WRITE
#define BIO_F_BIO_WRITE 113
Definition at line 819 of file bio.h.
BIO_F_BIO_WRITE_EX
#define BIO_F_BIO_WRITE_EX 119
Definition at line 820 of file bio.h.
BIO_F_BIO_WRITE_INTERN
#define BIO_F_BIO_WRITE_INTERN 128
Definition at line 821 of file bio.h.
BIO_F_BUFFER_CTRL
#define BIO_F_BUFFER_CTRL 114
Definition at line 822 of file bio.h.
BIO_F_CONN_CTRL
#define BIO_F_CONN_CTRL 127
Definition at line 823 of file bio.h.
BIO_F_CONN_STATE
#define BIO_F_CONN_STATE 115
Definition at line 824 of file bio.h.
BIO_F_DGRAM_SCTP_READ
#define BIO_F_DGRAM_SCTP_READ 132
Definition at line 825 of file bio.h.
BIO_F_DGRAM_SCTP_WRITE
#define BIO_F_DGRAM_SCTP_WRITE 133
Definition at line 826 of file bio.h.
BIO_F_FILE_CTRL
#define BIO_F_FILE_CTRL 116
Definition at line 827 of file bio.h.
BIO_F_FILE_READ
#define BIO_F_FILE_READ 130
Definition at line 828 of file bio.h.
BIO_F_LINEBUFFER_CTRL
#define BIO_F_LINEBUFFER_CTRL 129
Definition at line 829 of file bio.h.
BIO_F_MEM_WRITE
#define BIO_F_MEM_WRITE 117
Definition at line 830 of file bio.h.
BIO_F_SSL_NEW
#define BIO_F_SSL_NEW 118
Definition at line 831 of file bio.h.
BIO_FAMILY_IPANY
#define BIO_FAMILY_IPANY 256
Definition at line 368 of file bio.h.
BIO_FAMILY_IPV4
#define BIO_FAMILY_IPV4 4
Definition at line 366 of file bio.h.
BIO_FAMILY_IPV6
#define BIO_FAMILY_IPV6 6
Definition at line 367 of file bio.h.
BIO_FLAGS_BASE64_NO_NL
#define BIO_FLAGS_BASE64_NO_NL 0x100
Definition at line 168 of file bio.h.
BIO_FLAGS_IO_SPECIAL
#define BIO_FLAGS_IO_SPECIAL 0x04
Definition at line 157 of file bio.h.
BIO_FLAGS_MEM_RDONLY
#define BIO_FLAGS_MEM_RDONLY 0x200
Definition at line 175 of file bio.h.
Referenced by CMS_dataFinal().
BIO_FLAGS_NONCLEAR_RST
#define BIO_FLAGS_NONCLEAR_RST 0x400
Definition at line 176 of file bio.h.
BIO_FLAGS_READ
#define BIO_FLAGS_READ 0x01
Definition at line 155 of file bio.h.
Referenced by dtls1_read_failed().
BIO_FLAGS_RWS
#define BIO_FLAGS_RWS (BIO_FLAGS_READ|BIO_FLAGS_WRITE|BIO_FLAGS_IO_SPECIAL)
Definition at line 158 of file bio.h.
BIO_FLAGS_SHOULD_RETRY
#define BIO_FLAGS_SHOULD_RETRY 0x08
Definition at line 159 of file bio.h.
BIO_FLAGS_UPLINK
#define BIO_FLAGS_UPLINK 0
Definition at line 165 of file bio.h.
BIO_FLAGS_WRITE
#define BIO_FLAGS_WRITE 0x02
Definition at line 156 of file bio.h.
BIO_flush
#define BIO_flush (b) (int)BIO_ctrl(b,BIO_CTRL_FLUSH,0,NULL)
Definition at line 485 of file bio.h.
Referenced by OCSP_REQ_CTX_nbio(), ssl3_dispatch_alert(), and statem_flush().
BIO_FP_APPEND
#define BIO_FP_APPEND 0x08
Definition at line 152 of file bio.h.
BIO_FP_READ
#define BIO_FP_READ 0x02
Definition at line 150 of file bio.h.
BIO_FP_TEXT
#define BIO_FP_TEXT 0x10
Definition at line 153 of file bio.h.
Referenced by main().
BIO_FP_WRITE
#define BIO_FP_WRITE 0x04
Definition at line 151 of file bio.h.
BIO_get_accept_ip_family
#define BIO_get_accept_ip_family (b) BIO_ctrl(b,BIO_C_GET_ACCEPT,4,NULL)
Definition at line 392 of file bio.h.
BIO_get_accept_name
#define BIO_get_accept_name (b) ((const char *)BIO_ptr_ctrl(b,BIO_C_GET_ACCEPT,0))
Definition at line 384 of file bio.h.
BIO_get_accept_port
#define BIO_get_accept_port (b) ((const char *)BIO_ptr_ctrl(b,BIO_C_GET_ACCEPT,1))
Definition at line 385 of file bio.h.
BIO_get_app_data
#define BIO_get_app_data (s) BIO_get_ex_data(s,0)
Definition at line 359 of file bio.h.
BIO_get_bind_mode
#define BIO_get_bind_mode (b) BIO_ctrl(b,BIO_C_GET_BIND_MODE,0,NULL)
Definition at line 399 of file bio.h.
BIO_get_buffer_num_lines
#define BIO_get_buffer_num_lines (b) BIO_ctrl(b,BIO_C_GET_BUFF_NUM_LINES,0,NULL)
Definition at line 467 of file bio.h.
BIO_get_close
#define BIO_get_close (b) (int)BIO_ctrl(b,BIO_CTRL_GET_CLOSE,0,NULL)
Definition at line 479 of file bio.h.
BIO_get_conn_address
#define BIO_get_conn_address (b) ((const BIO_ADDR *)BIO_ptr_ctrl(b,BIO_C_GET_CONNECT,2))
Definition at line 377 of file bio.h.
BIO_get_conn_hostname
#define BIO_get_conn_hostname (b) ((const char *)BIO_ptr_ctrl(b,BIO_C_GET_CONNECT,0))
Definition at line 375 of file bio.h.
BIO_get_conn_ip_family
#define BIO_get_conn_ip_family (b) BIO_ctrl(b,BIO_C_GET_CONNECT,3,NULL)
Definition at line 378 of file bio.h.
BIO_get_conn_port
#define BIO_get_conn_port (b) ((const char *)BIO_ptr_ctrl(b,BIO_C_GET_CONNECT,1))
Definition at line 376 of file bio.h.
BIO_get_ex_new_index
#define BIO_get_ex_new_index (l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_BIO, l, p, newf, dupf, freef)
Definition at line 522 of file bio.h.
BIO_get_fd
#define BIO_get_fd (b, c) BIO_ctrl(b,BIO_C_GET_FD,0,(char *)c)
Definition at line 410 of file bio.h.
Referenced by SSL_set_rfd(), and SSL_set_wfd().
BIO_get_flags
#define BIO_get_flags (b) BIO_test_flags(b, ~(0x0))
Definition at line 186 of file bio.h.
BIO_get_fp
#define BIO_get_fp (b, fpp) BIO_ctrl(b,BIO_C_GET_FILE_PTR,0,(char *)fpp)
Definition at line 414 of file bio.h.
BIO_get_info_callback
#define BIO_get_info_callback (b, cbp)
Value:
(int)BIO_ctrl(b,BIO_CTRL_GET_CALLBACK,0, \
                                                   cbp)
Definition at line 486 of file bio.h.
BIO_get_mem_data
#define BIO_get_mem_data (b, pp) BIO_ctrl(b,BIO_CTRL_INFO,0,(char *)pp)
Definition at line 460 of file bio.h.
Referenced by CMS_dataFinal(), OCSP_REQ_CTX_nbio(), and OCSP_REQ_CTX_nbio_d2i().
BIO_get_mem_ptr
#define BIO_get_mem_ptr (b, pp) BIO_ctrl(b,BIO_C_GET_BUF_MEM_PTR,0,(char *)pp)
Definition at line 462 of file bio.h.
BIO_get_num_renegotiates
#define BIO_get_num_renegotiates (b) BIO_ctrl(b,BIO_C_GET_SSL_NUM_RENEGOTIATES,0,NULL)
Definition at line 452 of file bio.h.
BIO_get_peer_name
#define BIO_get_peer_name (b) ((const char *)BIO_ptr_ctrl(b,BIO_C_GET_ACCEPT,2))
Definition at line 386 of file bio.h.
BIO_get_peer_port
#define BIO_get_peer_port (b) ((const char *)BIO_ptr_ctrl(b,BIO_C_GET_ACCEPT,3))
Definition at line 387 of file bio.h.
BIO_get_read_request
#define BIO_get_read_request (b) (int)BIO_ctrl(b,BIO_C_GET_READ_REQUEST,0,NULL)
Definition at line 501 of file bio.h.
BIO_get_retry_flags
#define BIO_get_retry_flags (b) BIO_test_flags(b, (BIO_FLAGS_RWS|BIO_FLAGS_SHOULD_RETRY))
Definition at line 197 of file bio.h.
Referenced by BIO_copy_next_retry().
BIO_get_ssl
#define BIO_get_ssl (b, sslp) BIO_ctrl(b,BIO_C_GET_SSL,0,(char *)sslp)
Definition at line 448 of file bio.h.
BIO_get_write_buf_size
#define BIO_get_write_buf_size (b, size) (size_t)BIO_ctrl(b,BIO_C_GET_WRITE_BUF_SIZE,size,NULL)
Definition at line 495 of file bio.h.
BIO_get_write_guarantee
#define BIO_get_write_guarantee (b) (int)BIO_ctrl(b,BIO_C_GET_WRITE_GUARANTEE,0,NULL)
Definition at line 500 of file bio.h.
BIO_make_bio_pair
#define BIO_make_bio_pair (b1, b2) (int)BIO_ctrl(b1,BIO_C_MAKE_BIO_PAIR,0,b2)
Definition at line 496 of file bio.h.
BIO_NOCLOSE
#define BIO_NOCLOSE 0x00
Definition at line 72 of file bio.h.
Referenced by dup_bio_err(), dup_bio_in(), dup_bio_out(), ERR_print_errors_fp(), LHASH_OF(), main(), OPENSSL_LH_node_stats(), OPENSSL_LH_node_usage_stats(), OPENSSL_LH_stats(), SSL_set_rfd(), and SSL_set_wfd().
BIO_pending
#define BIO_pending (b) (int)BIO_ctrl(b,BIO_CTRL_PENDING,0,NULL)
Definition at line 480 of file bio.h.
BIO_R_ACCEPT_ERROR
#define BIO_R_ACCEPT_ERROR 100
Definition at line 834 of file bio.h.
Referenced by BIO_accept_ex().
BIO_R_ADDRINFO_ADDR_IS_NOT_AF_INET
#define BIO_R_ADDRINFO_ADDR_IS_NOT_AF_INET 141
Definition at line 835 of file bio.h.
BIO_R_AMBIGUOUS_HOST_OR_SERVICE
#define BIO_R_AMBIGUOUS_HOST_OR_SERVICE 129
Definition at line 836 of file bio.h.
Referenced by BIO_parse_hostserv().
BIO_R_BAD_FOPEN_MODE
#define BIO_R_BAD_FOPEN_MODE 101
Definition at line 837 of file bio.h.
BIO_R_BROKEN_PIPE
#define BIO_R_BROKEN_PIPE 124
Definition at line 838 of file bio.h.
BIO_R_CONNECT_ERROR
#define BIO_R_CONNECT_ERROR 103
Definition at line 839 of file bio.h.
Referenced by BIO_connect().
BIO_R_GETHOSTBYNAME_ADDR_IS_NOT_AF_INET
#define BIO_R_GETHOSTBYNAME_ADDR_IS_NOT_AF_INET 107
Definition at line 840 of file bio.h.
BIO_R_GETSOCKNAME_ERROR
#define BIO_R_GETSOCKNAME_ERROR 132
Definition at line 841 of file bio.h.
BIO_R_GETSOCKNAME_TRUNCATED_ADDRESS
#define BIO_R_GETSOCKNAME_TRUNCATED_ADDRESS 133
Definition at line 842 of file bio.h.
BIO_R_GETTING_SOCKTYPE
#define BIO_R_GETTING_SOCKTYPE 134
Definition at line 843 of file bio.h.
Referenced by BIO_listen().
BIO_R_IN_USE
#define BIO_R_IN_USE 123
Definition at line 846 of file bio.h.
BIO_R_INVALID_ARGUMENT
#define BIO_R_INVALID_ARGUMENT 125
Definition at line 844 of file bio.h.
BIO_R_INVALID_SOCKET
#define BIO_R_INVALID_SOCKET 135
Definition at line 845 of file bio.h.
Referenced by BIO_connect(), and BIO_listen().
BIO_R_LENGTH_TOO_LONG
#define BIO_R_LENGTH_TOO_LONG 102
Definition at line 847 of file bio.h.
BIO_R_LISTEN_V6_ONLY
#define BIO_R_LISTEN_V6_ONLY 136
Definition at line 848 of file bio.h.
Referenced by BIO_listen().
BIO_R_LOOKUP_RETURNED_NOTHING
#define BIO_R_LOOKUP_RETURNED_NOTHING 142
Definition at line 849 of file bio.h.
BIO_R_MALFORMED_HOST_OR_SERVICE
#define BIO_R_MALFORMED_HOST_OR_SERVICE 130
Definition at line 850 of file bio.h.
Referenced by BIO_parse_hostserv().
BIO_R_NBIO_CONNECT_ERROR
#define BIO_R_NBIO_CONNECT_ERROR 110
Definition at line 851 of file bio.h.
BIO_R_NO_ACCEPT_ADDR_OR_SERVICE_SPECIFIED
#define BIO_R_NO_ACCEPT_ADDR_OR_SERVICE_SPECIFIED 143
Definition at line 852 of file bio.h.
BIO_R_NO_HOSTNAME_OR_SERVICE_SPECIFIED
#define BIO_R_NO_HOSTNAME_OR_SERVICE_SPECIFIED 144
Definition at line 853 of file bio.h.
BIO_R_NO_PORT_DEFINED
#define BIO_R_NO_PORT_DEFINED 113
Definition at line 854 of file bio.h.
BIO_R_NO_SUCH_FILE
#define BIO_R_NO_SUCH_FILE 128
Definition at line 855 of file bio.h.
BIO_R_NULL_PARAMETER
#define BIO_R_NULL_PARAMETER 115
Definition at line 856 of file bio.h.
BIO_R_UNABLE_TO_BIND_SOCKET
#define BIO_R_UNABLE_TO_BIND_SOCKET 117
Definition at line 857 of file bio.h.
Referenced by BIO_listen().
BIO_R_UNABLE_TO_CREATE_SOCKET
#define BIO_R_UNABLE_TO_CREATE_SOCKET 118
Definition at line 858 of file bio.h.
Referenced by BIO_socket().
BIO_R_UNABLE_TO_KEEPALIVE
#define BIO_R_UNABLE_TO_KEEPALIVE 137
Definition at line 859 of file bio.h.
Referenced by BIO_connect(), and BIO_listen().
BIO_R_UNABLE_TO_LISTEN_SOCKET
#define BIO_R_UNABLE_TO_LISTEN_SOCKET 119
Definition at line 860 of file bio.h.
Referenced by BIO_listen().
BIO_R_UNABLE_TO_NODELAY
#define BIO_R_UNABLE_TO_NODELAY 138
Definition at line 861 of file bio.h.
Referenced by BIO_connect(), and BIO_listen().
BIO_R_UNABLE_TO_REUSEADDR
#define BIO_R_UNABLE_TO_REUSEADDR 139
Definition at line 862 of file bio.h.
Referenced by BIO_listen().
BIO_R_UNAVAILABLE_IP_FAMILY
#define BIO_R_UNAVAILABLE_IP_FAMILY 145
Definition at line 863 of file bio.h.
BIO_R_UNINITIALIZED
#define BIO_R_UNINITIALIZED 120
Definition at line 864 of file bio.h.
BIO_R_UNKNOWN_INFO_TYPE
#define BIO_R_UNKNOWN_INFO_TYPE 140
Definition at line 865 of file bio.h.
BIO_R_UNSUPPORTED_IP_FAMILY
#define BIO_R_UNSUPPORTED_IP_FAMILY 146
Definition at line 866 of file bio.h.
BIO_R_UNSUPPORTED_METHOD
#define BIO_R_UNSUPPORTED_METHOD 121
Definition at line 867 of file bio.h.
BIO_R_UNSUPPORTED_PROTOCOL_FAMILY
#define BIO_R_UNSUPPORTED_PROTOCOL_FAMILY 131
Definition at line 868 of file bio.h.
BIO_R_WRITE_TO_READ_ONLY_BIO
#define BIO_R_WRITE_TO_READ_ONLY_BIO 126
Definition at line 869 of file bio.h.
BIO_R_WSASTARTUP
#define BIO_R_WSASTARTUP 122
Definition at line 870 of file bio.h.
Referenced by BIO_sock_init().
BIO_read_filename
#define BIO_read_filename (b, name)
Value:
(int)BIO_ctrl(b,BIO_C_SET_FILENAME, \
                BIO_CLOSE|BIO_FP_READ,(char *)name)
Definition at line 431 of file bio.h.
Referenced by SRP_VBASE_init().
BIO_reset
#define BIO_reset (b) (int)BIO_ctrl(b,BIO_CTRL_RESET,0,NULL)
Definition at line 476 of file bio.h.
Referenced by OCSP_REQ_CTX_nbio().
BIO_retry_type
#define BIO_retry_type (a) BIO_test_flags(a, BIO_FLAGS_RWS)
Definition at line 204 of file bio.h.
BIO_RR_ACCEPT
#define BIO_RR_ACCEPT 0x03
Definition at line 221 of file bio.h.
Referenced by SSL_get_error().
BIO_RR_CONNECT
#define BIO_RR_CONNECT 0x02
Definition at line 219 of file bio.h.
Referenced by SSL_get_error().
BIO_RR_SSL_X509_LOOKUP
#define BIO_RR_SSL_X509_LOOKUP 0x01
Definition at line 217 of file bio.h.
BIO_rw_filename
#define BIO_rw_filename (b, name)
Value:
(int)BIO_ctrl(b,BIO_C_SET_FILENAME, \
                BIO_CLOSE|BIO_FP_READ|BIO_FP_WRITE,name)
Definition at line 438 of file bio.h.
BIO_seek
#define BIO_seek (b, ofs) (int)BIO_ctrl(b,BIO_C_FILE_SEEK,ofs,NULL)
Definition at line 417 of file bio.h.
BIO_set_accept_bios
#define BIO_set_accept_bios (b, bio) BIO_ctrl(b,BIO_C_SET_ACCEPT,3,(char *)bio)
Definition at line 390 of file bio.h.
BIO_set_accept_ip_family
#define BIO_set_accept_ip_family (b, f) BIO_int_ctrl(b,BIO_C_SET_ACCEPT,4,f)
Definition at line 391 of file bio.h.
BIO_set_accept_name
#define BIO_set_accept_name (b, name) BIO_ctrl(b,BIO_C_SET_ACCEPT,0,(char *)name)
Definition at line 382 of file bio.h.
BIO_set_accept_port
#define BIO_set_accept_port (b, port) BIO_ctrl(b,BIO_C_SET_ACCEPT,1,(char *)port)
Definition at line 383 of file bio.h.
BIO_set_app_data
#define BIO_set_app_data (s, arg) BIO_set_ex_data(s,0,arg)
Definition at line 358 of file bio.h.
BIO_set_bind_mode
#define BIO_set_bind_mode (b, mode) BIO_ctrl(b,BIO_C_SET_BIND_MODE,mode,NULL)
Definition at line 398 of file bio.h.
BIO_set_buffer_read_data
#define BIO_set_buffer_read_data (b, buf, num) BIO_ctrl(b,BIO_C_SET_BUFF_READ_DATA,num,buf)
Definition at line 471 of file bio.h.
BIO_set_buffer_size
#define BIO_set_buffer_size (b, size) BIO_ctrl(b,BIO_C_SET_BUFF_SIZE,size,NULL)
Definition at line 468 of file bio.h.
BIO_set_close
#define BIO_set_close (b, c) (int)BIO_ctrl(b,BIO_CTRL_SET_CLOSE,(c),NULL)
Definition at line 478 of file bio.h.
BIO_set_conn_address
#define BIO_set_conn_address (b, addr) BIO_ctrl(b,BIO_C_SET_CONNECT,2,(char *)addr)
Definition at line 373 of file bio.h.
BIO_set_conn_hostname
#define BIO_set_conn_hostname (b, name) BIO_ctrl(b,BIO_C_SET_CONNECT,0,(char *)name)
Definition at line 371 of file bio.h.
BIO_set_conn_ip_family
#define BIO_set_conn_ip_family (b, f) BIO_int_ctrl(b,BIO_C_SET_CONNECT,3,f)
Definition at line 374 of file bio.h.
BIO_set_conn_mode
#define BIO_set_conn_mode (b, n) BIO_ctrl(b,BIO_C_SET_CONNECT_MODE,(n),NULL)
Definition at line 379 of file bio.h.
BIO_set_conn_port
#define BIO_set_conn_port (b, port) BIO_ctrl(b,BIO_C_SET_CONNECT,1,(char *)port)
Definition at line 372 of file bio.h.
Referenced by process_responder().
BIO_set_fd
#define BIO_set_fd (b, fd, c) BIO_int_ctrl(b,BIO_C_SET_FD,c,fd)
Definition at line 409 of file bio.h.
Referenced by SSL_set_rfd(), and SSL_set_wfd().
BIO_set_fp
#define BIO_set_fp (b, fp, c) BIO_ctrl(b,BIO_C_SET_FILE_PTR,c,(char *)fp)
Definition at line 413 of file bio.h.
Referenced by OPENSSL_LH_node_stats(), OPENSSL_LH_node_usage_stats(), and OPENSSL_LH_stats().
BIO_set_info_callback
#define BIO_set_info_callback (b, cb) (int)BIO_callback_ctrl(b,BIO_CTRL_SET_CALLBACK,cb)
Definition at line 488 of file bio.h.
BIO_set_mem_buf
#define BIO_set_mem_buf (b, bm, c) BIO_ctrl(b,BIO_C_SET_BUF_MEM,c,(char *)bm)
Definition at line 461 of file bio.h.
BIO_set_mem_eof_return
#define BIO_set_mem_eof_return (b, v) BIO_ctrl(b,BIO_C_SET_BUF_MEM_EOF_RETURN,v,NULL)
Definition at line 463 of file bio.h.
Referenced by CMS_dataFinal(), and create_ssl_objects().
BIO_set_nbio
#define BIO_set_nbio (b, n) BIO_ctrl(b,BIO_C_SET_NBIO,(n),NULL)
Definition at line 361 of file bio.h.
BIO_set_nbio_accept
#define BIO_set_nbio_accept (b, n) BIO_ctrl(b,BIO_C_SET_ACCEPT,2,(n)?(void *)"a":NULL)
Definition at line 389 of file bio.h.
BIO_set_read_buffer_size
#define BIO_set_read_buffer_size (b, size) BIO_int_ctrl(b,BIO_C_SET_BUFF_SIZE,size,0)
Definition at line 469 of file bio.h.
Referenced by ssl_init_wbio_buffer().
BIO_set_retry_read
#define BIO_set_retry_read (b) BIO_set_flags(b, (BIO_FLAGS_READ|BIO_FLAGS_SHOULD_RETRY))
Definition at line 189 of file bio.h.
Referenced by ossl_statem_client_post_process_message(), ossl_statem_server_post_process_message(), and tls_post_process_client_key_exchange().
BIO_set_retry_special
#define BIO_set_retry_special (b) BIO_set_flags(b, (BIO_FLAGS_IO_SPECIAL|BIO_FLAGS_SHOULD_RETRY))
Definition at line 187 of file bio.h.
BIO_set_retry_write
#define BIO_set_retry_write (b) BIO_set_flags(b, (BIO_FLAGS_WRITE|BIO_FLAGS_SHOULD_RETRY))
Definition at line 191 of file bio.h.
BIO_set_ssl
#define BIO_set_ssl (b, ssl, c) BIO_ctrl(b,BIO_C_SET_SSL,c,(char *)ssl)
Definition at line 447 of file bio.h.
BIO_set_ssl_mode
#define BIO_set_ssl_mode (b, client) BIO_ctrl(b,BIO_C_SSL_MODE,client,NULL)
Definition at line 449 of file bio.h.
BIO_set_ssl_renegotiate_bytes
#define BIO_set_ssl_renegotiate_bytes (b, num) BIO_ctrl(b,BIO_C_SET_SSL_RENEGOTIATE_BYTES,num,NULL)
Definition at line 450 of file bio.h.
BIO_set_ssl_renegotiate_timeout
#define BIO_set_ssl_renegotiate_timeout (b, seconds) BIO_ctrl(b,BIO_C_SET_SSL_RENEGOTIATE_TIMEOUT,seconds,NULL)
Definition at line 454 of file bio.h.
BIO_set_write_buf_size
#define BIO_set_write_buf_size (b, size) (int)BIO_ctrl(b,BIO_C_SET_WRITE_BUF_SIZE,size,NULL)
Definition at line 494 of file bio.h.
BIO_set_write_buffer_size
#define BIO_set_write_buffer_size (b, size) BIO_int_ctrl(b,BIO_C_SET_BUFF_SIZE,size,1)
Definition at line 470 of file bio.h.
BIO_should_io_special
#define BIO_should_io_special (a) BIO_test_flags(a, BIO_FLAGS_IO_SPECIAL)
Definition at line 203 of file bio.h.
Referenced by SSL_get_error().
BIO_should_read
#define BIO_should_read (a) BIO_test_flags(a, BIO_FLAGS_READ)
Definition at line 201 of file bio.h.
Referenced by SSL_get_error().
BIO_should_retry
#define BIO_should_retry (a) BIO_test_flags(a, BIO_FLAGS_SHOULD_RETRY)
Definition at line 205 of file bio.h.
Referenced by BIO_get_retry_BIO(), OCSP_REQ_CTX_nbio(), and OCSP_sendreq_bio().
BIO_should_write
#define BIO_should_write (a) BIO_test_flags(a, BIO_FLAGS_WRITE)
Definition at line 202 of file bio.h.
Referenced by SSL_get_error().
BIO_shutdown_wr
#define BIO_shutdown_wr (b) (int)BIO_ctrl(b, BIO_C_SHUTDOWN_WR, 0, NULL)
Definition at line 498 of file bio.h.
BIO_sock_cleanup
#define BIO_sock_cleanup () while(0) continue
Definition at line 675 of file bio.h.
BIO_SOCK_KEEPALIVE
#define BIO_SOCK_KEEPALIVE 0x04
Definition at line 696 of file bio.h.
Referenced by BIO_connect(), and BIO_listen().
BIO_SOCK_NODELAY
#define BIO_SOCK_NODELAY 0x10
Definition at line 698 of file bio.h.
Referenced by BIO_connect(), and BIO_listen().
BIO_SOCK_NONBLOCK
#define BIO_SOCK_NONBLOCK 0x08
Definition at line 697 of file bio.h.
Referenced by BIO_accept_ex(), BIO_connect(), and BIO_listen().
BIO_SOCK_REUSEADDR
#define BIO_SOCK_REUSEADDR 0x01
Definition at line 694 of file bio.h.
Referenced by BIO_get_accept_socket(), and BIO_listen().
BIO_SOCK_V6_ONLY
#define BIO_SOCK_V6_ONLY 0x02
Definition at line 695 of file bio.h.
Referenced by BIO_listen().
BIO_tell
#define BIO_tell (b) (int)BIO_ctrl(b,BIO_C_FILE_TELL,0,NULL)
Definition at line 418 of file bio.h.
BIO_TYPE_ACCEPT
#define BIO_TYPE_ACCEPT (13|BIO_TYPE_SOURCE_SINK|BIO_TYPE_DESCRIPTOR)
Definition at line 53 of file bio.h.
BIO_TYPE_ASN1
#define BIO_TYPE_ASN1 (22|BIO_TYPE_FILTER)
Definition at line 60 of file bio.h.
BIO_TYPE_BASE64
#define BIO_TYPE_BASE64 (11|BIO_TYPE_FILTER)
Definition at line 51 of file bio.h.
BIO_TYPE_BIO
#define BIO_TYPE_BIO (19|BIO_TYPE_SOURCE_SINK)/* half a BIO pair */
Definition at line 57 of file bio.h.
BIO_TYPE_BUFFER
#define BIO_TYPE_BUFFER (9|BIO_TYPE_FILTER)
Definition at line 49 of file bio.h.
BIO_TYPE_CIPHER
#define BIO_TYPE_CIPHER (10|BIO_TYPE_FILTER)
Definition at line 50 of file bio.h.
BIO_TYPE_COMP
#define BIO_TYPE_COMP (23|BIO_TYPE_FILTER)
Definition at line 61 of file bio.h.
Referenced by comp_zlib_cleanup_int().
BIO_TYPE_CONNECT
#define BIO_TYPE_CONNECT (12|BIO_TYPE_SOURCE_SINK|BIO_TYPE_DESCRIPTOR)
Definition at line 52 of file bio.h.
BIO_TYPE_DESCRIPTOR
#define BIO_TYPE_DESCRIPTOR 0x0100 /* socket, fd, connect or accept */
Definition at line 35 of file bio.h.
BIO_TYPE_DGRAM
#define BIO_TYPE_DGRAM (21|BIO_TYPE_SOURCE_SINK|BIO_TYPE_DESCRIPTOR)
Definition at line 59 of file bio.h.
BIO_TYPE_DGRAM_SCTP
#define BIO_TYPE_DGRAM_SCTP (24|BIO_TYPE_SOURCE_SINK|BIO_TYPE_DESCRIPTOR)
Definition at line 63 of file bio.h.
Referenced by BIO_dgram_is_sctp().
BIO_TYPE_FD
#define BIO_TYPE_FD (4|BIO_TYPE_SOURCE_SINK|BIO_TYPE_DESCRIPTOR)
Definition at line 44 of file bio.h.
BIO_TYPE_FILE
#define BIO_TYPE_FILE (2|BIO_TYPE_SOURCE_SINK)
Definition at line 42 of file bio.h.
BIO_TYPE_FILTER
#define BIO_TYPE_FILTER 0x0200
Definition at line 36 of file bio.h.
BIO_TYPE_LINEBUFFER
#define BIO_TYPE_LINEBUFFER (20|BIO_TYPE_FILTER)
Definition at line 58 of file bio.h.
BIO_TYPE_MD
#define BIO_TYPE_MD (8|BIO_TYPE_FILTER)
Definition at line 48 of file bio.h.
Referenced by cms_DigestAlgorithm_find_ctx(), and PKCS7_signatureVerify().
BIO_TYPE_MEM
#define BIO_TYPE_MEM (1|BIO_TYPE_SOURCE_SINK)
Definition at line 41 of file bio.h.
Referenced by CMS_dataFinal().
BIO_TYPE_NBIO_TEST
#define BIO_TYPE_NBIO_TEST (16|BIO_TYPE_FILTER)/* server proxy BIO */
Definition at line 55 of file bio.h.
BIO_TYPE_NONE
#define BIO_TYPE_NONE 0
Definition at line 40 of file bio.h.
BIO_TYPE_NULL
#define BIO_TYPE_NULL (6|BIO_TYPE_SOURCE_SINK)
Definition at line 46 of file bio.h.
BIO_TYPE_NULL_FILTER
#define BIO_TYPE_NULL_FILTER (17|BIO_TYPE_FILTER)
Definition at line 56 of file bio.h.
BIO_TYPE_SOCKET
#define BIO_TYPE_SOCKET (5|BIO_TYPE_SOURCE_SINK|BIO_TYPE_DESCRIPTOR)
Definition at line 45 of file bio.h.
Referenced by SSL_set_rfd(), and SSL_set_wfd().
BIO_TYPE_SOURCE_SINK
#define BIO_TYPE_SOURCE_SINK 0x0400
Definition at line 37 of file bio.h.
BIO_TYPE_SSL
#define BIO_TYPE_SSL (7|BIO_TYPE_FILTER)
Definition at line 47 of file bio.h.
Referenced by BIO_ssl_copy_session_id(), and BIO_ssl_shutdown().
BIO_TYPE_START
#define BIO_TYPE_START 128
Definition at line 66 of file bio.h.
Referenced by BIO_get_new_index().
BIO_wpending
#define BIO_wpending (b) (int)BIO_ctrl(b,BIO_CTRL_WPENDING,0,NULL)
Definition at line 481 of file bio.h.
BIO_write_filename
#define BIO_write_filename (b, name)
Value:
(int)BIO_ctrl(b,BIO_C_SET_FILENAME, \
                BIO_CLOSE|BIO_FP_WRITE,name)
Definition at line 434 of file bio.h.
Typedef Documentation
asn1_ps_func
typedef int asn1_ps_func(BIO *b, unsigned char **pbuf, int *plen, void *parg)
Definition at line 264 of file bio.h.
BIO_callback_fn
typedef long(* BIO_callback_fn) (BIO *b, int oper, const char *argp, int argi, long argl, long ret)
Definition at line 240 of file bio.h.
BIO_callback_fn_ex
typedef long(* BIO_callback_fn_ex) (BIO *b, int oper, const char *argp, size_t len, int argi, long argl, int ret, size_t *processed)
Definition at line 242 of file bio.h.
bio_info_cb
typedef void bio_info_cb(BIO *, int, const char *, int, long, long)
Definition at line 259 of file bio.h.
Enumeration Type Documentation
BIO_hostserv_priorities
enum BIO_hostserv_priorities
Enumerator
BIO_PARSE_PRIO_HOST
BIO_PARSE_PRIO_SERV
Definition at line 659 of file bio.h.
BIO_lookup_type
enum BIO_lookup_type
Enumerator
BIO_LOOKUP_CLIENT
BIO_LOOKUP_SERVER
Definition at line 664 of file bio.h.
BIO_sock_info_type
enum BIO_sock_info_type
Enumerator
BIO_SOCK_INFO_ADDRESS
Definition at line 688 of file bio.h.
Function Documentation
BIO_accept_ex()
int BIO_accept_ex (int accept_sock, BIO_ADDR * addr, int options)
Definition at line 234 of file b_sock2.c.
References BIO_ADDR_sockaddr_noconst(), BIO_F_BIO_ACCEPT_EX, BIO_R_ACCEPT_ERROR, BIO_SOCK_NONBLOCK, BIO_sock_should_retry(), BIO_socket_nbio(), BIOerr, closesocket, get_last_socket_error, len, NULL, SYS_F_ACCEPT, and SYSerr.
BIO_ADDR_clear()
void BIO_ADDR_clear (BIO_ADDR * ap)
Definition at line 80 of file b_addr.c.
BIO_ADDR_family()
int BIO_ADDR_family (const BIO_ADDR * ap)
Definition at line 150 of file b_addr.c.
Referenced by BIO_listen().
BIO_ADDR_free()
void BIO_ADDR_free (BIO_ADDR *)
Definition at line 75 of file b_addr.c.
References OPENSSL_free.
BIO_ADDR_hostname_string()
char* BIO_ADDR_hostname_string (const BIO_ADDR * ap, int numeric)
Definition at line 288 of file b_addr.c.
References NULL.
BIO_ADDR_new()
BIO_ADDR* BIO_ADDR_new (void)
Definition at line 62 of file b_addr.c.
Referenced by main().
BIO_ADDR_path_string()
char* BIO_ADDR_path_string (const BIO_ADDR * ap)
Definition at line 308 of file b_addr.c.
References NULL, and OPENSSL_strdup.
BIO_ADDR_rawaddress()
int BIO_ADDR_rawaddress (const BIO_ADDR * ap, void * p, size_t * l)
Definition at line 155 of file b_addr.c.
References len, and NULL.
BIO_ADDR_rawmake()
int BIO_ADDR_rawmake (BIO_ADDR * ap, int family, const void * where, size_t wherelen, unsigned short port)
Definition at line 112 of file b_addr.c.
BIO_ADDR_rawport()
unsigned short BIO_ADDR_rawport (const BIO_ADDR * ap)
Definition at line 189 of file b_addr.c.
BIO_ADDR_service_string()
char* BIO_ADDR_service_string (const BIO_ADDR * ap, int numeric)
Definition at line 298 of file b_addr.c.
References NULL.
BIO_ADDRINFO_address()
const BIO_ADDR* BIO_ADDRINFO_address (const BIO_ADDRINFO * bai)
Definition at line 431 of file b_addr.c.
References NULL.
Referenced by BIO_get_accept_socket().
BIO_ADDRINFO_family()
int BIO_ADDRINFO_family (const BIO_ADDRINFO * bai)
Definition at line 372 of file b_addr.c.
References NULL.
Referenced by BIO_get_accept_socket().
BIO_ADDRINFO_free()
void BIO_ADDRINFO_free (BIO_ADDRINFO * bai)
Definition at line 438 of file b_addr.c.
References NULL, and OPENSSL_free.
Referenced by BIO_CONNECT_free(), and BIO_get_accept_socket().
BIO_ADDRINFO_next()
const BIO_ADDRINFO* BIO_ADDRINFO_next (const BIO_ADDRINFO * bai)
Definition at line 365 of file b_addr.c.
References NULL.
BIO_ADDRINFO_protocol()
int BIO_ADDRINFO_protocol (const BIO_ADDRINFO * bai)
Definition at line 386 of file b_addr.c.
References NULL.
Referenced by BIO_get_accept_socket().
BIO_ADDRINFO_socktype()
int BIO_ADDRINFO_socktype (const BIO_ADDRINFO * bai)
Definition at line 379 of file b_addr.c.
References NULL.
Referenced by BIO_get_accept_socket().
BIO_asn1_get_prefix()
int BIO_asn1_get_prefix (BIO * b, asn1_ps_func ** pprefix, asn1_ps_func ** pprefix_free)
Definition at line 425 of file bio_asn1.c.
BIO_asn1_get_suffix()
int BIO_asn1_get_suffix (BIO * b, asn1_ps_func ** psuffix, asn1_ps_func ** psuffix_free)
Definition at line 437 of file bio_asn1.c.
BIO_asn1_set_prefix()
int BIO_asn1_set_prefix (BIO * b, asn1_ps_func * prefix, asn1_ps_func * prefix_free)
Definition at line 419 of file bio_asn1.c.
BIO_asn1_set_suffix()
int BIO_asn1_set_suffix (BIO * b, asn1_ps_func * suffix, asn1_ps_func * suffix_free)
Definition at line 431 of file bio_asn1.c.
BIO_callback_ctrl()
long BIO_callback_ctrl (BIO * b, int cmd, void(*)(BIO *, int, const char *, int, long, long) fp)
BIO_clear_flags()
void BIO_clear_flags (BIO * b, int flags)
Definition at line 189 of file bio_lib.c.
BIO_closesocket()
int BIO_closesocket (int sock)
Definition at line 264 of file b_sock2.c.
References closesocket.
Referenced by BIO_get_accept_socket().
BIO_connect()
int BIO_connect (int sock, const BIO_ADDR * addr, int options)
Definition at line 77 of file b_sock2.c.
References BIO_ADDR_sockaddr(), BIO_ADDR_sockaddr_size(), BIO_F_BIO_CONNECT, BIO_R_CONNECT_ERROR, BIO_R_INVALID_SOCKET, BIO_R_UNABLE_TO_KEEPALIVE, BIO_R_UNABLE_TO_NODELAY, BIO_SOCK_KEEPALIVE, BIO_SOCK_NODELAY, BIO_SOCK_NONBLOCK, BIO_sock_should_retry(), BIO_socket_nbio(), BIOerr, get_last_socket_error, SYS_F_CONNECT, SYS_F_SETSOCKOPT, and SYSerr.
BIO_copy_next_retry()
void BIO_copy_next_retry (BIO * b)
Definition at line 742 of file bio_lib.c.
References BIO_get_retry_flags, and BIO_set_flags().
BIO_ctrl()
long BIO_ctrl (BIO * bp, int cmd, long larg, void * parg)
Definition at line 509 of file bio_lib.c.
Referenced by BIO_ctrl_get_read_request(), BIO_ctrl_get_write_guarantee(), BIO_ctrl_pending(), BIO_ctrl_reset_read_request(), BIO_ctrl_wpending(), BIO_int_ctrl(), BIO_ptr_ctrl(), BIO_push(), dtls1_buffer_record(), dtls1_check_timeout_num(), dtls1_query_mtu(), dtls1_stop_timer(), ossl_statem_client_post_work(), ossl_statem_server_post_work(), tls_client_key_exchange_post_work(), and tls_post_process_client_key_exchange().
BIO_ctrl_get_read_request()
size_t BIO_ctrl_get_read_request (BIO * b)
Definition at line 734 of file bss_bio.c.
References BIO_C_GET_READ_REQUEST, BIO_ctrl(), and NULL.
BIO_ctrl_get_write_guarantee()
size_t BIO_ctrl_get_write_guarantee (BIO * b)
Definition at line 729 of file bss_bio.c.
References BIO_C_GET_WRITE_GUARANTEE, BIO_ctrl(), and NULL.
BIO_ctrl_pending()
size_t BIO_ctrl_pending (BIO * b)
Definition at line 571 of file bio_lib.c.
References BIO_ctrl(), BIO_CTRL_PENDING, and NULL.
BIO_ctrl_reset_read_request()
int BIO_ctrl_reset_read_request (BIO * b)
Definition at line 739 of file bss_bio.c.
References BIO_C_RESET_READ_REQUEST, BIO_ctrl(), and NULL.
BIO_ctrl_wpending()
size_t BIO_ctrl_wpending (BIO * b)
Definition at line 576 of file bio_lib.c.
References BIO_ctrl(), BIO_CTRL_WPENDING, and NULL.
BIO_debug_callback()
long BIO_debug_callback (BIO * bio, int cmd, const char * argp, int argi, long argl, long ret)
Definition at line 17 of file bio_cb.c.
BIO_dgram_is_sctp()
int BIO_dgram_is_sctp (BIO * bio)
Definition at line 940 of file bss_dgram.c.
References BIO_method_type(), and BIO_TYPE_DGRAM_SCTP.
Referenced by dtls1_buffer_record(), dtls1_get_record(), dtls1_process_buffered_records(), dtls1_start_timer(), dtls1_write_app_data_bytes(), ossl_statem_client_pre_work(), ossl_statem_server_post_process_message(), ossl_statem_server_pre_work(), tls_finish_handshake(), and tls_post_process_client_key_exchange().
BIO_dgram_non_fatal_error()
int BIO_dgram_non_fatal_error (int error)
Definition at line 1875 of file bss_dgram.c.
BIO_dgram_sctp_msg_waiting()
int BIO_dgram_sctp_msg_waiting (BIO * b)
Definition at line 1786 of file bss_dgram.c.
References NULL.
Referenced by ossl_statem_client_post_process_message(), ossl_statem_server_post_process_message(), and tls_post_process_client_key_exchange().
BIO_dgram_sctp_notification_cb()
int BIO_dgram_sctp_notification_cb (BIO * b, void(*)(BIO *bio, void *context, void *buf) handle_notifications, void * context)
Definition at line 1597 of file bss_dgram.c.
BIO_dgram_sctp_wait_for_dry()
int BIO_dgram_sctp_wait_for_dry (BIO * b)
Definition at line 1628 of file bss_dgram.c.
BIO_dump()
int BIO_dump (BIO * b, const char * bytes, int len)
Definition at line 125 of file b_dump.c.
References BIO_dump_cb().
BIO_dump_cb()
int BIO_dump_cb (int(*)(const void *data, size_t len, void *u) cb, void * u, const char * s, int len)
Definition at line 21 of file b_dump.c.
References BIO_dump_indent_cb(), and cb.
Referenced by BIO_dump(), and BIO_dump_fp().
BIO_dump_fp()
int BIO_dump_fp (FILE * fp, const char * s, int len)
Definition at line 109 of file b_dump.c.
References BIO_dump_cb().
Referenced by aes_ccm_decrypt(), aes_ccm_encrypt(), aes_gcm_decrypt(), aes_gcm_encrypt(), and tls1_generate_master_secret().
BIO_dump_indent()
int BIO_dump_indent (BIO * b, const char * bytes, int len, int indent)
Definition at line 130 of file b_dump.c.
References BIO_dump_indent_cb().
Referenced by SSL_SESSION_print().
BIO_dump_indent_cb()
int BIO_dump_indent_cb (int(*)(const void *data, size_t len, void *u) cb, void * u, const char * s, int len, int indent)
Definition at line 27 of file b_dump.c.
Referenced by BIO_dump_cb(), BIO_dump_indent(), and BIO_dump_indent_fp().
BIO_dump_indent_fp()
int BIO_dump_indent_fp (FILE * fp, const char * s, int len, int indent)
Definition at line 114 of file b_dump.c.
References BIO_dump_indent_cb().
BIO_dup_chain()
BIO* BIO_dup_chain (BIO * in)
Definition at line 698 of file bio_lib.c.
BIO_f_buffer()
const BIO_METHOD* BIO_f_buffer (void)
Definition at line 42 of file bf_buff.c.
Referenced by SMIME_crlf_copy(), and ssl_init_wbio_buffer().
BIO_f_linebuffer()
const BIO_METHOD* BIO_f_linebuffer (void)
Definition at line 47 of file bf_lbuf.c.
BIO_f_nbio_test()
const BIO_METHOD* BIO_f_nbio_test (void)
Definition at line 51 of file bf_nbio.c.
BIO_f_null()
const BIO_METHOD* BIO_f_null (void)
Definition at line 44 of file bf_null.c.
BIO_fd_non_fatal_error()
int BIO_fd_non_fatal_error (int error)
Definition at line 231 of file bss_fd.c.
Referenced by BIO_fd_should_retry().
BIO_fd_should_retry()
int BIO_fd_should_retry (int i)
Definition at line 219 of file bss_fd.c.
References BIO_fd_non_fatal_error(), and get_last_sys_error.
BIO_find_type()
BIO* BIO_find_type (BIO * b, int bio_type)
Definition at line 648 of file bio_lib.c.
References NULL.
Referenced by BIO_ssl_copy_session_id(), BIO_ssl_shutdown(), CMS_dataFinal(), cms_DigestAlgorithm_find_ctx(), and PKCS7_signatureVerify().
BIO_free()
int BIO_free (BIO * a)
Definition at line 109 of file bio_lib.c.
Referenced by BIO_free_all(), BIO_vfree(), CMS_dataInit(), cms_DigestAlgorithm_init_bio(), CMS_sign_receipt(), create_ssl_objects(), FuzzerCleanup(), LHASH_OF(), OCSP_REQ_CTX_free(), OPENSSL_LH_node_stats(), OPENSSL_LH_node_usage_stats(), OPENSSL_LH_stats(), ssl3_free_digest_list(), ssl_free_wbio_buffer(), ssl_init_wbio_buffer(), STACK_OF(), TS_CONF_load_key(), and X509_load_cert_crl_file().
BIO_free_all()
void BIO_free_all (BIO * a)
Definition at line 682 of file bio_lib.c.
References BIO_free(), and NULL.
Referenced by set_keylog_file(), SSL_set0_rbio(), SSL_set0_wbio(), and TS_VERIFY_CTX_cleanup().
BIO_get_callback()
BIO_callback_fn BIO_get_callback (const BIO * b)
Definition at line 204 of file bio_lib.c.
BIO_get_callback_arg()
char* BIO_get_callback_arg (const BIO * b)
Definition at line 229 of file bio_lib.c.
BIO_get_callback_ex()
BIO_callback_fn_ex BIO_get_callback_ex (const BIO * b)
Definition at line 214 of file bio_lib.c.
BIO_get_data()
void* BIO_get_data (BIO * a)
Definition at line 147 of file bio_lib.c.
Referenced by BIO_ssl_copy_session_id(), BIO_ssl_shutdown(), comp_zlib_cleanup_int(), and mempacket_test_inject().
BIO_get_ex_data()
void* BIO_get_ex_data (BIO * bio, int idx)
Definition at line 753 of file bio_lib.c.
BIO_get_init()
int BIO_get_init (BIO * a)
Definition at line 157 of file bio_lib.c.
BIO_get_new_index()
int BIO_get_new_index (void)
Definition at line 22 of file bio_meth.c.
References BIO_TYPE_START, and RUN_ONCE.
BIO_get_retry_BIO()
BIO* BIO_get_retry_BIO (BIO * bio, int * reason)
Definition at line 620 of file bio_lib.c.
References BIO_should_retry, and NULL.
BIO_get_retry_reason()
int BIO_get_retry_reason (BIO * bio)
Definition at line 638 of file bio_lib.c.
Referenced by SSL_get_error().
BIO_get_shutdown()
int BIO_get_shutdown (BIO * a)
Definition at line 167 of file bio_lib.c.
BIO_gets()
int BIO_gets (BIO * bp, char * buf, int size)
Definition at line 431 of file bio_lib.c.
Referenced by OCSP_REQ_CTX_nbio(), and SMIME_crlf_copy().
BIO_hex_string()
int BIO_hex_string (BIO * out, int indent, int width, unsigned char * data, int datalen)
Definition at line 135 of file b_dump.c.
Referenced by SCT_print().
BIO_indent()
int BIO_indent (BIO * b, int indent, int max)
Definition at line 479 of file bio_lib.c.
References BIO_puts(), and max.
Referenced by X509_signature_dump().
BIO_int_ctrl()
long BIO_int_ctrl (BIO * bp, int cmd, long larg, int iarg)
Definition at line 491 of file bio_lib.c.
References BIO_ctrl().
BIO_listen()
int BIO_listen (int sock, const BIO_ADDR * addr, int options)
Definition at line 153 of file b_sock2.c.
References BIO_ADDR_family(), BIO_ADDR_sockaddr(), BIO_ADDR_sockaddr_size(), BIO_F_BIO_LISTEN, BIO_R_GETTING_SOCKTYPE, BIO_R_INVALID_SOCKET, BIO_R_LISTEN_V6_ONLY, BIO_R_UNABLE_TO_BIND_SOCKET, BIO_R_UNABLE_TO_KEEPALIVE, BIO_R_UNABLE_TO_LISTEN_SOCKET, BIO_R_UNABLE_TO_NODELAY, BIO_R_UNABLE_TO_REUSEADDR, BIO_SOCK_KEEPALIVE, BIO_SOCK_NODELAY, BIO_SOCK_NONBLOCK, BIO_SOCK_REUSEADDR, BIO_SOCK_V6_ONLY, BIO_socket_nbio(), BIOerr, get_last_socket_error, MAX_LISTEN, SYS_F_BIND, SYS_F_GETSOCKOPT, SYS_F_LISTEN, SYS_F_SETSOCKOPT, and SYSerr.
Referenced by BIO_get_accept_socket().
BIO_lookup()
int BIO_lookup (const char * host, const char * service, enum BIO_lookup_type lookup_type, int family, int socktype, BIO_ADDRINFO ** res)
Definition at line 654 of file b_addr.c.
Referenced by BIO_get_accept_socket().
BIO_meth_free()
void BIO_meth_free (BIO_METHOD * biom)
Definition at line 47 of file bio_meth.c.
References OPENSSL_free.
Referenced by bio_f_tls_dump_filter_free(), and bio_s_mempacket_test_free().
BIO_meth_new()
int int int int BIO_METHOD* BIO_meth_new (int type, const char * name)
Definition at line 36 of file bio_meth.c.
References NULL, OPENSSL_zalloc, and type.
BIO_meth_set_callback_ctrl()
int BIO_meth_set_callback_ctrl (BIO_METHOD * biom, long(*)(BIO *, int, bio_info_cb *) callback_ctrl)
Definition at line 208 of file bio_meth.c.
BIO_meth_set_create()
int BIO_meth_set_create (BIO_METHOD * biom, int(*)(BIO *) create)
Definition at line 186 of file bio_meth.c.
BIO_meth_set_ctrl()
int BIO_meth_set_ctrl (BIO_METHOD * biom, long(*)(BIO *, int, long, void *) ctrl)
Definition at line 174 of file bio_meth.c.
BIO_meth_set_destroy()
int BIO_meth_set_destroy (BIO_METHOD * biom, int(*)(BIO *) destroy)
Definition at line 197 of file bio_meth.c.
BIO_meth_set_gets()
int BIO_meth_set_gets (BIO_METHOD * biom, int(*)(BIO *, char *, int) gets)
Definition at line 162 of file bio_meth.c.
BIO_meth_set_puts()
int BIO_meth_set_puts (BIO_METHOD * biom, int(*)(BIO *, const char *) puts)
Definition at line 150 of file bio_meth.c.
BIO_meth_set_read()
int BIO_meth_set_read (BIO_METHOD * biom, int(*)(BIO *, char *, int) read)
Definition at line 129 of file bio_meth.c.
References bread_conv().
BIO_meth_set_read_ex()
int BIO_meth_set_read_ex (BIO_METHOD * biom, int(*)(BIO *, char *, size_t, size_t *) bread)
Definition at line 137 of file bio_meth.c.
References NULL.
BIO_meth_set_write()
int BIO_meth_set_write (BIO_METHOD * biom, int(*)(BIO *, const char *, int) write)
Definition at line 83 of file bio_meth.c.
References bwrite_conv().
BIO_meth_set_write_ex()
int BIO_meth_set_write_ex (BIO_METHOD * biom, int(*)(BIO *, const char *, size_t, size_t *) bwrite)
Definition at line 91 of file bio_meth.c.
References NULL.
BIO_method_name()
const char* BIO_method_name (const BIO * b)
Definition at line 234 of file bio_lib.c.
BIO_method_type()
int BIO_method_type (const BIO * b)
Definition at line 239 of file bio_lib.c.
Referenced by BIO_dgram_is_sctp(), SSL_set_rfd(), and SSL_set_wfd().
BIO_new()
BIO* BIO_new (const BIO_METHOD * type)
Definition at line 72 of file bio_lib.c.
References BIO_F_BIO_NEW, BIOerr, CRYPTO_EX_INDEX_BIO, CRYPTO_free_ex_data(), CRYPTO_new_ex_data(), CRYPTO_THREAD_lock_free(), CRYPTO_THREAD_lock_new(), ERR_R_INIT_FAIL, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, and OPENSSL_zalloc.
Referenced by cms_content_bio(), cms_DigestAlgorithm_init_bio(), create_ssl_objects(), OCSP_REQ_CTX_new(), OPENSSL_LH_node_stats(), OPENSSL_LH_node_usage_stats(), OPENSSL_LH_stats(), SMIME_crlf_copy(), SRP_VBASE_init(), ssl3_init_finished_mac(), ssl_init_wbio_buffer(), SSL_set_rfd(), and SSL_set_wfd().
BIO_new_accept()
BIO* BIO_new_accept (const char * host_port)
Definition at line 548 of file bss_acpt.c.
BIO_new_bio_pair()
int BIO_new_bio_pair (BIO ** bio1, size_t writebuf1, BIO ** bio2, size_t writebuf2)
Definition at line 686 of file bss_bio.c.
References NULL.
BIO_new_connect()
BIO* BIO_new_connect (const char * host_port)
Definition at line 536 of file bss_conn.c.
Referenced by process_responder().
BIO_new_dgram()
BIO* BIO_new_dgram (int fd, int close_flag)
Definition at line 150 of file bss_dgram.c.
BIO_new_dgram_sctp()
BIO* BIO_new_dgram_sctp (int fd, int close_flag)
Definition at line 819 of file bss_dgram.c.
BIO_new_fd()
BIO* BIO_new_fd (int fd, int close_flag)
Definition at line 81 of file bss_fd.c.
BIO_new_file()
BIO* BIO_new_file (const char * filename, const char * mode)
Definition at line 68 of file bss_file.c.
Referenced by LHASH_OF(), STACK_OF(), TS_CONF_load_key(), and X509_load_cert_crl_file().
BIO_new_fp()
BIO* BIO_new_fp (FILE * stream, int close_flag)
Definition at line 101 of file bss_file.c.
Referenced by dup_bio_err(), dup_bio_in(), dup_bio_out(), ERR_print_errors_fp(), LHASH_OF(), and main().
BIO_new_mem_buf()
BIO* BIO_new_mem_buf (const void * buf, int len)
Definition at line 81 of file bss_mem.c.
Referenced by cms_content_bio(), and CMS_sign_receipt().
BIO_new_socket()
BIO* BIO_new_socket (int sock, int close_flag)
Definition at line 60 of file bss_sock.c.
BIO_next()
BIO* BIO_next (BIO * b)
Definition at line 670 of file bio_lib.c.
References NULL.
Referenced by cms_DigestAlgorithm_find_ctx(), PKCS7_signatureVerify(), and SSL_get_wbio().
BIO_nread()
int BIO_nread (BIO * bio, char ** buf, int num)
Definition at line 765 of file bss_bio.c.
BIO_nread0()
int BIO_nread0 (BIO * bio, char ** buf)
Definition at line 749 of file bss_bio.c.
BIO_number_read()
uint64_t BIO_number_read (BIO * bio)
Definition at line 758 of file bio_lib.c.
BIO_number_written()
uint64_t BIO_number_written (BIO * bio)
Definition at line 765 of file bio_lib.c.
BIO_nwrite()
int BIO_nwrite (BIO * bio, char ** buf, int num)
Definition at line 796 of file bss_bio.c.
BIO_nwrite0()
int BIO_nwrite0 (BIO * bio, char ** buf)
Definition at line 780 of file bss_bio.c.
BIO_parse_hostserv()
int BIO_parse_hostserv (const char * hostserv, char ** host, char ** service, enum BIO_hostserv_priorities hostserv_prio)
Definition at line 491 of file b_addr.c.
References BIO_F_BIO_PARSE_HOSTSERV, BIO_PARSE_PRIO_HOST, BIO_R_AMBIGUOUS_HOST_OR_SERVICE, BIO_R_MALFORMED_HOST_OR_SERVICE, BIOerr, ERR_R_MALLOC_FAILURE, h, NULL, and OPENSSL_strndup.
Referenced by BIO_get_accept_socket().
BIO_pop()
BIO* BIO_pop (BIO * b)
Definition at line 600 of file bio_lib.c.
Referenced by ssl_free_wbio_buffer(), and SSL_set0_wbio().
BIO_printf()
int BIO_printf (BIO * bio, const char * format, ...)
BIO_ptr_ctrl()
void* BIO_ptr_ctrl (BIO * bp, int cmd, long larg)
Definition at line 499 of file bio_lib.c.
References BIO_ctrl(), and NULL.
BIO_push()
BIO* BIO_push (BIO * b, BIO * append)
Definition at line 582 of file bio_lib.c.
References BIO_ctrl(), BIO_CTRL_PUSH, and NULL.
Referenced by CMS_dataInit(), create_ssl_objects(), process_responder(), SMIME_crlf_copy(), ssl_init_wbio_buffer(), and SSL_set0_wbio().
BIO_puts()
int BIO_puts (BIO * bp, const char * buf)
Definition at line 386 of file bio_lib.c.
Referenced by BIO_indent(), OCSP_REQ_CTX_add1_header(), ssl_print_groups(), ssl_print_point_formats(), ssl_print_tmp_key(), SSL_SESSION_print(), SSL_SESSION_print_keylog(), TS_STATUS_INFO_print_bio(), verify_callback(), X509_REQ_print_ex(), and X509_signature_print().
BIO_read()
int BIO_read (BIO * b, void * data, int dlen)
Definition at line 287 of file bio_lib.c.
Referenced by b2i_PVK_bio(), OCSP_REQ_CTX_nbio(), and SMIME_crlf_copy().
BIO_read_ex()
int BIO_read_ex (BIO * b, void * data, size_t dlen, size_t * readbytes)
Definition at line 305 of file bio_lib.c.
BIO_s_accept()
const BIO_METHOD* BIO_s_accept (void)
Definition at line 71 of file bss_acpt.c.
BIO_s_bio()
const BIO_METHOD* BIO_s_bio (void)
Definition at line 56 of file bss_bio.c.
BIO_s_connect()
const BIO_METHOD* BIO_s_connect (void)
Definition at line 244 of file bss_conn.c.
BIO_s_datagram()
const BIO_METHOD* BIO_s_datagram (void)
Definition at line 145 of file bss_dgram.c.
BIO_s_datagram_sctp()
const BIO_METHOD* BIO_s_datagram_sctp (void)
Definition at line 814 of file bss_dgram.c.
BIO_s_fd()
const BIO_METHOD* BIO_s_fd (void)
Definition at line 76 of file bss_fd.c.
BIO_s_file()
const BIO_METHOD* BIO_s_file (void)
Definition at line 114 of file bss_file.c.
Referenced by OPENSSL_LH_node_stats(), OPENSSL_LH_node_usage_stats(), OPENSSL_LH_stats(), and SRP_VBASE_init().
BIO_s_log()
const BIO_METHOD* BIO_s_log (void)
Definition at line 102 of file bss_log.c.
BIO_s_mem()
const BIO_METHOD* BIO_s_mem (void)
Definition at line 71 of file bss_mem.c.
Referenced by cms_content_bio(), create_ssl_objects(), OCSP_REQ_CTX_new(), and ssl3_init_finished_mac().
BIO_s_null()
const BIO_METHOD* BIO_s_null (void)
Definition at line 39 of file bss_null.c.
Referenced by cms_content_bio().
BIO_s_secmem()
const BIO_METHOD* BIO_s_secmem (void)
Definition at line 76 of file bss_mem.c.
BIO_s_socket()
const BIO_METHOD* BIO_s_socket (void)
Definition at line 55 of file bss_sock.c.
Referenced by SSL_set_rfd(), and SSL_set_wfd().
BIO_set_callback()
void BIO_set_callback (BIO * b, BIO_callback_fn callback)
Definition at line 209 of file bio_lib.c.
References cb.
BIO_set_callback_arg()
void BIO_set_callback_arg (BIO * b, char * arg)
Definition at line 224 of file bio_lib.c.
BIO_set_callback_ex()
void BIO_set_callback_ex (BIO * b, BIO_callback_fn_ex callback)
Definition at line 219 of file bio_lib.c.
References cb.
BIO_set_data()
void BIO_set_data (BIO * a, void * ptr)
Definition at line 142 of file bio_lib.c.
References ptr.
Referenced by comp_zlib_cleanup_int().
BIO_set_ex_data()
int BIO_set_ex_data (BIO * bio, int idx, void * data)
Definition at line 748 of file bio_lib.c.
BIO_set_flags()
void BIO_set_flags (BIO * b, int flags)
Definition at line 199 of file bio_lib.c.
References flags.
Referenced by BIO_copy_next_retry(), CMS_dataFinal(), and dtls1_read_failed().
BIO_set_init()
void BIO_set_init (BIO * a, int init)
Definition at line 152 of file bio_lib.c.
Referenced by comp_zlib_cleanup_int().
BIO_set_next()
void BIO_set_next (BIO * b, BIO * next)
Definition at line 677 of file bio_lib.c.
BIO_set_retry_reason()
void BIO_set_retry_reason (BIO * bio, int reason)
Definition at line 643 of file bio_lib.c.
BIO_set_shutdown()
void BIO_set_shutdown (BIO * a, int shut)
Definition at line 162 of file bio_lib.c.
BIO_set_tcp_ndelay()
int BIO_set_tcp_ndelay (int sock, int turn_on)
Definition at line 289 of file b_sock.c.
BIO_snprintf()
int int int BIO_snprintf (char * buf, size_t n, const char * format, ...)
BIO_sock_error()
int BIO_sock_error (int sock)
Definition at line 93 of file b_sock.c.
References get_last_socket_error.
BIO_sock_info()
int BIO_sock_info (int sock, enum BIO_sock_info_type type, union BIO_sock_info_u * info)
Definition at line 352 of file b_sock.c.
References BIO_SOCK_INFO_ADDRESS.
BIO_sock_init()
int BIO_sock_init (void)
Definition at line 126 of file b_sock.c.
References BIO_F_BIO_SOCK_INIT, BIO_R_WSASTARTUP, BIOerr, SYS_F_WSASTARTUP, and SYSerr.
Referenced by BIO_get_accept_socket(), and BIO_socket().
BIO_sock_non_fatal_error()
int BIO_sock_non_fatal_error (int error)
Definition at line 183 of file bss_sock.c.
Referenced by BIO_sock_should_retry().
BIO_sock_should_retry()
int BIO_sock_should_retry (int i)
Definition at line 171 of file bss_sock.c.
References BIO_sock_non_fatal_error(), and get_last_socket_error.
Referenced by BIO_accept_ex(), and BIO_connect().
BIO_socket()
int BIO_socket (int domain, int socktype, int protocol, int options)
Definition at line 40 of file b_sock2.c.
References BIO_F_BIO_SOCKET, BIO_R_UNABLE_TO_CREATE_SOCKET, BIO_sock_init(), BIOerr, get_last_socket_error, SYS_F_SOCKET, and SYSerr.
Referenced by BIO_get_accept_socket().
BIO_socket_ioctl()
int BIO_socket_ioctl (int fd, long type, void * arg)
Definition at line 172 of file b_sock.c.
BIO_socket_nbio()
int BIO_socket_nbio (int fd, int mode)
Definition at line 308 of file b_sock.c.
Referenced by BIO_accept_ex(), BIO_connect(), and BIO_listen().
BIO_test_flags()
int BIO_test_flags (const BIO * b, int flags)
Definition at line 194 of file bio_lib.c.
BIO_up_ref()
int BIO_up_ref (BIO * a)
Definition at line 177 of file bio_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by create_ssl_objects(), SSL_set_bio(), SSL_set_rfd(), and SSL_set_wfd().
BIO_vfree()
void BIO_vfree (BIO * a)
Definition at line 172 of file bio_lib.c.
References BIO_free().
BIO_vprintf()
int int BIO_vprintf (BIO * bio, const char * format, va_list args)
BIO_vsnprintf()
int int int int BIO_vsnprintf (char * buf, size_t n, const char * format, va_list args)
BIO_write()
int BIO_write (BIO * b, const void * data, int dlen)
Definition at line 354 of file bio_lib.c.
Referenced by ASN1_GENERALIZEDTIME_print(), ASN1_TIME_print(), ASN1_UTCTIME_print(), OCSP_REQ_CTX_add1_header(), OCSP_REQ_CTX_nbio(), OCSP_REQUEST_print(), SMIME_crlf_copy(), TS_ASN1_INTEGER_print_bio(), TS_ext_print_bio(), TS_REQ_print_bio(), TS_TST_INFO_print_bio(), X509_REQ_print_ex(), and X509_signature_dump().
BIO_write_ex()
int BIO_write_ex (BIO * b, const void * data, size_t dlen, size_t * written)
Definition at line 372 of file bio_lib.c.
ERR_load_BIO_strings()
int ERR_load_BIO_strings (void)
Definition at line 120 of file bio_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
Variable Documentation
BIO_meth_get_callback_ctrl
long(*)(BIO *, int, bio_info_cb *) BIO_meth_get_callback_ctrl(BIO_METHOD *biom)
Definition at line 771 of file bio.h.
BIO_meth_get_create
int(*)(BIO *) BIO_meth_get_create(BIO_METHOD *bion)
Definition at line 767 of file bio.h.
BIO_meth_get_ctrl
long(*)(BIO *, int, long, void *) BIO_meth_get_ctrl(BIO_METHOD *biom)
Definition at line 764 of file bio.h.
BIO_meth_get_destroy
int(*)(BIO *) BIO_meth_get_destroy(BIO_METHOD *biom)
Definition at line 769 of file bio.h.
BIO_meth_get_gets
int(*)(BIO *, char *, int) BIO_meth_get_gets(BIO_METHOD *biom)
Definition at line 761 of file bio.h.
BIO_meth_get_puts
int(*)(BIO *, const char *) BIO_meth_get_puts(BIO_METHOD *biom)
Definition at line 758 of file bio.h.
BIO_meth_get_read
int(*)(BIO *, char *, int) BIO_meth_get_read(BIO_METHOD *biom)
Definition at line 752 of file bio.h.
BIO_meth_get_read_ex
int(*)(BIO *, char *, size_t, size_t *) BIO_meth_get_read_ex(BIO_METHOD *biom)
Definition at line 753 of file bio.h.
BIO_meth_get_write
int(*)(BIO *, const char *, int) BIO_meth_get_write(BIO_METHOD *biom)
Definition at line 745 of file bio.h.
BIO_meth_get_write_ex
int(*)(BIO *, const char *, size_t, size_t *) BIO_meth_get_write_ex(BIO_METHOD *biom)
Definition at line 746 of file bio.h.