include/openssl/comp.h File Reference
comp.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/crypto.h>
Macros
#define COMP_zlib_cleanup() while(0) continue
#define COMP_F_BIO_ZLIB_FLUSH 99
#define COMP_F_BIO_ZLIB_NEW 100
#define COMP_F_BIO_ZLIB_READ 101
#define COMP_F_BIO_ZLIB_WRITE 102
#define COMP_R_ZLIB_DEFLATE_ERROR 99
#define COMP_R_ZLIB_INFLATE_ERROR 100
#define COMP_R_ZLIB_NOT_SUPPORTED 101
Functions
COMP_CTX * COMP_CTX_new (COMP_METHOD *meth)
const COMP_METHOD * COMP_CTX_get_method (const COMP_CTX *ctx)
int COMP_CTX_get_type (const COMP_CTX *comp)
int COMP_get_type (const COMP_METHOD *meth)
const char * COMP_get_name (const COMP_METHOD *meth)
void COMP_CTX_free (COMP_CTX *ctx)
int COMP_compress_block (COMP_CTX *ctx, unsigned char *out, int olen, unsigned char *in, int ilen)
int COMP_expand_block (COMP_CTX *ctx, unsigned char *out, int olen, unsigned char *in, int ilen)
COMP_METHOD * COMP_zlib (void)
int ERR_load_COMP_strings (void)
Macro Definition Documentation
COMP_F_BIO_ZLIB_FLUSH
#define COMP_F_BIO_ZLIB_FLUSH 99
Definition at line 58 of file comp.h.
COMP_F_BIO_ZLIB_NEW
#define COMP_F_BIO_ZLIB_NEW 100
Definition at line 59 of file comp.h.
Referenced by comp_zlib_cleanup_int().
COMP_F_BIO_ZLIB_READ
#define COMP_F_BIO_ZLIB_READ 101
Definition at line 60 of file comp.h.
COMP_F_BIO_ZLIB_WRITE
#define COMP_F_BIO_ZLIB_WRITE 102
Definition at line 61 of file comp.h.
COMP_R_ZLIB_DEFLATE_ERROR
#define COMP_R_ZLIB_DEFLATE_ERROR 99
Definition at line 64 of file comp.h.
COMP_R_ZLIB_INFLATE_ERROR
#define COMP_R_ZLIB_INFLATE_ERROR 100
Definition at line 65 of file comp.h.
COMP_R_ZLIB_NOT_SUPPORTED
#define COMP_R_ZLIB_NOT_SUPPORTED 101
Definition at line 66 of file comp.h.
Referenced by comp_zlib_cleanup_int().
COMP_zlib_cleanup
#define COMP_zlib_cleanup () while(0) continue
Definition at line 38 of file comp.h.
Function Documentation
COMP_compress_block()
int COMP_compress_block (COMP_CTX * ctx, unsigned char * out, int olen, unsigned char * in, int ilen)
Definition at line 57 of file comp_lib.c.
Referenced by ssl3_do_compress().
COMP_CTX_free()
void COMP_CTX_free (COMP_CTX * ctx)
Definition at line 46 of file comp_lib.c.
References NULL, and OPENSSL_free.
Referenced by ssl_clear_cipher_ctx().
COMP_CTX_get_method()
const COMP_METHOD* COMP_CTX_get_method (const COMP_CTX * ctx)
Definition at line 31 of file comp_lib.c.
Referenced by SSL_get_current_compression(), and SSL_get_current_expansion().
COMP_CTX_get_type()
int COMP_CTX_get_type (const COMP_CTX * comp)
Definition at line 88 of file comp_lib.c.
References NID_undef.
COMP_CTX_new()
COMP_CTX* COMP_CTX_new (COMP_METHOD * meth)
Definition at line 17 of file comp_lib.c.
COMP_expand_block()
int COMP_expand_block (COMP_CTX * ctx, unsigned char * out, int olen, unsigned char * in, int ilen)
Definition at line 72 of file comp_lib.c.
Referenced by ssl3_do_uncompress().
COMP_get_name()
const char* COMP_get_name (const COMP_METHOD * meth)
Definition at line 41 of file comp_lib.c.
Referenced by SSL_COMP_get_name().
COMP_get_type()
int COMP_get_type (const COMP_METHOD * meth)
Definition at line 36 of file comp_lib.c.
Referenced by SSL_COMP_add_compression_method().
COMP_zlib()
COMP_METHOD* COMP_zlib (void)
Definition at line 209 of file c_zlib.c.
Referenced by comp_zlib_cleanup_int(), and DEFINE_RUN_ONCE_STATIC().
ERR_load_COMP_strings()
int ERR_load_COMP_strings (void)
Definition at line 38 of file comp_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().