apps/opt.c File Reference
opt.c File Reference
#include "apps.h"
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <ctype.h>
#include <limits.h>
#include <openssl/bio.h>
#include <openssl/x509v3.h>
Macros
#define MAX_OPT_HELP_WIDTH 30
Enumerations
enum range { OPT_V_ENUM, OPT_X_ENUM }
Functions
char * opt_progname (const char *argv0)
char * opt_getprog (void)
char * opt_init (int ac, char **av, const OPTIONS *o)
int opt_format_error (const char *s, unsigned long flags)
int opt_format (const char *s, unsigned long flags, int *result)
int opt_cipher (const char *name, const EVP_CIPHER **cipherp)
int opt_md (const char *name, const EVP_MD **mdp)
int opt_pair (const char *name, const OPT_PAIR *pairs, int *result)
int opt_int (const char *value, int *result)
int opt_long (const char *value, long *result)
int opt_ulong (const char *value, unsigned long *result)
int opt_verify (int opt, X509_VERIFY_PARAM *vpm)
int opt_next (void)
char * opt_arg (void)
char * opt_flag (void)
char * opt_unknown (void)
char ** opt_rest (void)
int opt_num_rest (void)
void opt_help (const OPTIONS *list)
Variables
const char OPT_HELP_STR [] = "--"
const char OPT_MORE_STR [] = "---"
Macro Definition Documentation
MAX_OPT_HELP_WIDTH
#define MAX_OPT_HELP_WIDTH 30
Definition at line 24 of file opt.c.
Enumeration Type Documentation
range
enum range
Enumerator
OPT_V_ENUM
OPT_X_ENUM
Definition at line 433 of file opt.c.
Function Documentation
opt_arg()
char* opt_arg (void)
Definition at line 750 of file opt.c.
Referenced by opt_verify().
opt_cipher()
int opt_cipher (const char * name, const EVP_CIPHER ** cipherp)
Definition at line 277 of file opt.c.
References bio_err, BIO_printf(), and EVP_get_cipherbyname().
opt_flag()
char* opt_flag (void)
Definition at line 756 of file opt.c.
opt_format()
int opt_format (const char * s, unsigned long flags, int * result)
Definition at line 200 of file opt.c.
References FORMAT_ASN1, FORMAT_ENGINE, FORMAT_HTTP, FORMAT_MSBLOB, FORMAT_NSS, FORMAT_PEM, FORMAT_PKCS12, FORMAT_PVK, FORMAT_SMIME, FORMAT_TEXT, OPT_FMT_ENGINE, OPT_FMT_HTTP, OPT_FMT_MSBLOB, OPT_FMT_NSS, OPT_FMT_PEMDER, OPT_FMT_PKCS12, OPT_FMT_PVK, OPT_FMT_SMIME, OPT_FMT_TEXT, and opt_format_error().
opt_format_error()
int opt_format_error (const char * s, unsigned long flags)
Definition at line 182 of file opt.c.
References bio_err, BIO_printf(), and OPT_FMT_PEMDER.
Referenced by opt_format().
opt_getprog()
char* opt_getprog (void)
Definition at line 110 of file opt.c.
Referenced by app_malloc(), and parse_name().
opt_help()
void opt_help (const OPTIONS * list)
Definition at line 821 of file opt.c.
References OPTIONS::name, OPT_HELP_STR, OPT_MORE_STR, and OPTIONS::valtype.
opt_init()
char* opt_init (int ac, char ** av, const OPTIONS * o)
Definition at line 116 of file opt.c.
opt_int()
int opt_int (const char * value, int * result)
Definition at line 315 of file opt.c.
References bio_err, BIO_printf(), and opt_long().
opt_long()
int opt_long (const char * value, long * result)
Definition at line 331 of file opt.c.
References bio_err, BIO_printf(), and errno.
Referenced by opt_int().
opt_md()
int opt_md (const char * name, const EVP_MD ** mdp)
Definition at line 289 of file opt.c.
References bio_err, BIO_printf(), and EVP_get_digestbyname().
opt_next()
int opt_next (void)
Definition at line 595 of file opt.c.
opt_num_rest()
int opt_num_rest (void)
Definition at line 774 of file opt.c.
References opt_rest(), and pp.
opt_pair()
int opt_pair (const char * name, const OPT_PAIR * pairs, int * result)
Definition at line 299 of file opt.c.
References bio_err, BIO_printf(), and pp.
opt_progname()
char* opt_progname (const char * argv0)
Definition at line 94 of file opt.c.
opt_rest()
char** opt_rest (void)
Definition at line 768 of file opt.c.
Referenced by opt_num_rest().
opt_ulong()
int opt_ulong (const char * value, unsigned long * result)
Definition at line 406 of file opt.c.
References bio_err, BIO_printf(), and errno.
opt_unknown()
char* opt_unknown (void)
Definition at line 762 of file opt.c.
opt_verify()
int opt_verify (int opt, X509_VERIFY_PARAM * vpm)
Definition at line 435 of file opt.c.
References bio_err, BIO_printf(), NULL, OBJ_txt2obj(), opt_arg(), and t.
Variable Documentation
OPT_HELP_STR
const char OPT_HELP_STR[] = "--"
Definition at line 25 of file opt.c.
Referenced by opt_help().
OPT_MORE_STR
const char OPT_MORE_STR[] = "---"
Definition at line 26 of file opt.c.
Referenced by opt_help().