crypto/pkcs12/p12_utl.c File Reference
p12_utl.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/pkcs12.h>
Functions
unsigned char * OPENSSL_asc2uni (const char *asc, int asclen, unsigned char **uni, int *unilen)
char * OPENSSL_uni2asc (const unsigned char *uni, int unilen)
unsigned char * OPENSSL_utf82uni (const char *asc, int asclen, unsigned char **uni, int *unilen)
char * OPENSSL_uni2utf8 (const unsigned char *uni, int unilen)
int i2d_PKCS12_bio (BIO *bp, PKCS12 *p12)
int i2d_PKCS12_fp (FILE *fp, PKCS12 *p12)
PKCS12 * d2i_PKCS12_bio (BIO *bp, PKCS12 **p12)
PKCS12 * d2i_PKCS12_fp (FILE *fp, PKCS12 **p12)
Function Documentation
d2i_PKCS12_bio()
PKCS12* d2i_PKCS12_bio (BIO * bp, PKCS12 ** p12)
Definition at line 227 of file p12_utl.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_PKCS12_fp()
PKCS12* d2i_PKCS12_fp (FILE * fp, PKCS12 ** p12)
Definition at line 233 of file p12_utl.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
i2d_PKCS12_bio()
int i2d_PKCS12_bio (BIO * bp, PKCS12 * p12)
Definition at line 215 of file p12_utl.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_PKCS12_fp()
int i2d_PKCS12_fp (FILE * fp, PKCS12 * p12)
Definition at line 221 of file p12_utl.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
OPENSSL_asc2uni()
unsigned char* OPENSSL_asc2uni (const char * asc, int asclen, unsigned char ** uni, int * unilen)
Definition at line 16 of file p12_utl.c.
References NULL, and OPENSSL_malloc.
OPENSSL_uni2asc()
char* OPENSSL_uni2asc (const unsigned char * uni, int unilen)
Definition at line 41 of file p12_utl.c.
References NULL, and OPENSSL_malloc.
Referenced by print_attribs().
OPENSSL_uni2utf8()
char* OPENSSL_uni2utf8 (const unsigned char * uni, int unilen)
Definition at line 171 of file p12_utl.c.
References NULL.
Referenced by PKCS12_get_friendlyname().
OPENSSL_utf82uni()
unsigned char* OPENSSL_utf82uni (const char * asc, int asclen, unsigned char ** uni, int * unilen)
Definition at line 70 of file p12_utl.c.