crypto/pkcs12/p12_sbag.c File Reference
p12_sbag.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/pkcs12.h>
#include "p12_lcl.h"
Functions
ASN1_TYPE * PKCS12_get_attr (const PKCS12_SAFEBAG *bag, int attr_nid)
const ASN1_TYPE * PKCS12_SAFEBAG_get0_attr (const PKCS12_SAFEBAG *bag, int attr_nid)
ASN1_TYPE * PKCS8_get_attr (PKCS8_PRIV_KEY_INFO *p8, int attr_nid)
const PKCS8_PRIV_KEY_INFO * PKCS12_SAFEBAG_get0_p8inf (const PKCS12_SAFEBAG *bag)
const X509_SIG * PKCS12_SAFEBAG_get0_pkcs8 (const PKCS12_SAFEBAG *bag)
const STACK_OF (PKCS12_SAFEBAG)
const ASN1_OBJECT * PKCS12_SAFEBAG_get0_type (const PKCS12_SAFEBAG *bag)
int PKCS12_SAFEBAG_get_nid (const PKCS12_SAFEBAG *bag)
int PKCS12_SAFEBAG_get_bag_nid (const PKCS12_SAFEBAG *bag)
X509 * PKCS12_SAFEBAG_get1_cert (const PKCS12_SAFEBAG *bag)
X509_CRL * PKCS12_SAFEBAG_get1_crl (const PKCS12_SAFEBAG *bag)
PKCS12_SAFEBAG * PKCS12_SAFEBAG_create_cert (X509 *x509)
PKCS12_SAFEBAG * PKCS12_SAFEBAG_create_crl (X509_CRL *crl)
PKCS12_SAFEBAG * PKCS12_SAFEBAG_create0_p8inf (PKCS8_PRIV_KEY_INFO *p8)
PKCS12_SAFEBAG * PKCS12_SAFEBAG_create0_pkcs8 (X509_SIG *p8)
PKCS12_SAFEBAG * PKCS12_SAFEBAG_create_pkcs8_encrypt (int pbe_nid, const char *pass, int passlen, unsigned char *salt, int saltlen, int iter, PKCS8_PRIV_KEY_INFO *p8inf)
Function Documentation
PKCS12_get_attr()
ASN1_TYPE* PKCS12_get_attr (const PKCS12_SAFEBAG * bag, int attr_nid)
Definition at line 16 of file p12_sbag.c.
References PKCS12_get_attr_gen().
PKCS12_SAFEBAG_create0_p8inf()
PKCS12_SAFEBAG* PKCS12_SAFEBAG_create0_p8inf (PKCS8_PRIV_KEY_INFO * p8)
Definition at line 108 of file p12_sbag.c.
References ERR_R_MALLOC_FAILURE, NID_keyBag, NULL, OBJ_nid2obj(), PKCS12_F_PKCS12_SAFEBAG_CREATE0_P8INF, and PKCS12err.
Referenced by PKCS12_add_key().
PKCS12_SAFEBAG_create0_pkcs8()
PKCS12_SAFEBAG* PKCS12_SAFEBAG_create0_pkcs8 (X509_SIG * p8)
Definition at line 123 of file p12_sbag.c.
References ERR_R_MALLOC_FAILURE, NID_pkcs8ShroudedKeyBag, NULL, OBJ_nid2obj(), PKCS12_F_PKCS12_SAFEBAG_CREATE0_PKCS8, and PKCS12err.
Referenced by PKCS12_SAFEBAG_create_pkcs8_encrypt().
PKCS12_SAFEBAG_create_cert()
PKCS12_SAFEBAG* PKCS12_SAFEBAG_create_cert (X509 * x509)
Definition at line 94 of file p12_sbag.c.
References ASN1_ITEM_rptr, NID_certBag, NID_x509Certificate, and PKCS12_item_pack_safebag().
Referenced by PKCS12_add_cert().
PKCS12_SAFEBAG_create_crl()
PKCS12_SAFEBAG* PKCS12_SAFEBAG_create_crl (X509_CRL * crl)
Definition at line 100 of file p12_sbag.c.
References ASN1_ITEM_rptr, NID_crlBag, NID_x509Crl, and PKCS12_item_pack_safebag().
PKCS12_SAFEBAG_create_pkcs8_encrypt()
PKCS12_SAFEBAG* PKCS12_SAFEBAG_create_pkcs8_encrypt (int pbe_nid, const char * pass, int passlen, unsigned char * salt, int saltlen, int iter, PKCS8_PRIV_KEY_INFO * p8inf)
Definition at line 137 of file p12_sbag.c.
References ERR_R_MALLOC_FAILURE, EVP_get_cipherbynid, NULL, PKCS12_F_PKCS12_SAFEBAG_CREATE_PKCS8_ENCRYPT, PKCS12_SAFEBAG_create0_pkcs8(), PKCS12err, and PKCS8_encrypt().
Referenced by PKCS12_add_key().
PKCS12_SAFEBAG_get0_attr()
const ASN1_TYPE* PKCS12_SAFEBAG_get0_attr (const PKCS12_SAFEBAG * bag, int attr_nid)
Definition at line 22 of file p12_sbag.c.
References PKCS12_get_attr_gen().
Referenced by PKCS12_get_friendlyname().
PKCS12_SAFEBAG_get0_p8inf()
const PKCS8_PRIV_KEY_INFO* PKCS12_SAFEBAG_get0_p8inf (const PKCS12_SAFEBAG * bag)
Definition at line 33 of file p12_sbag.c.
References NID_keyBag, NULL, and PKCS12_SAFEBAG_get_nid().
PKCS12_SAFEBAG_get0_pkcs8()
const X509_SIG* PKCS12_SAFEBAG_get0_pkcs8 (const PKCS12_SAFEBAG * bag)
Definition at line 40 of file p12_sbag.c.
References NID_pkcs8ShroudedKeyBag, NULL, and OBJ_obj2nid().
PKCS12_SAFEBAG_get0_type()
const ASN1_OBJECT* PKCS12_SAFEBAG_get0_type (const PKCS12_SAFEBAG * bag)
Definition at line 55 of file p12_sbag.c.
PKCS12_SAFEBAG_get1_cert()
X509* PKCS12_SAFEBAG_get1_cert (const PKCS12_SAFEBAG * bag)
Definition at line 74 of file p12_sbag.c.
References ASN1_ITEM_rptr, ASN1_item_unpack(), NID_certBag, NID_x509Certificate, NULL, OBJ_obj2nid(), and PKCS12_SAFEBAG_get_nid().
PKCS12_SAFEBAG_get1_crl()
X509_CRL* PKCS12_SAFEBAG_get1_crl (const PKCS12_SAFEBAG * bag)
Definition at line 84 of file p12_sbag.c.
References ASN1_ITEM_rptr, ASN1_item_unpack(), NID_crlBag, NID_x509Crl, NULL, OBJ_obj2nid(), and PKCS12_SAFEBAG_get_nid().
PKCS12_SAFEBAG_get_bag_nid()
int PKCS12_SAFEBAG_get_bag_nid (const PKCS12_SAFEBAG * bag)
Definition at line 65 of file p12_sbag.c.
References NID_certBag, NID_crlBag, NID_secretBag, OBJ_obj2nid(), and PKCS12_SAFEBAG_get_nid().
PKCS12_SAFEBAG_get_nid()
int PKCS12_SAFEBAG_get_nid (const PKCS12_SAFEBAG * bag)
Definition at line 60 of file p12_sbag.c.
References OBJ_obj2nid().
Referenced by PKCS12_SAFEBAG_get0_p8inf(), PKCS12_SAFEBAG_get1_cert(), PKCS12_SAFEBAG_get1_crl(), and PKCS12_SAFEBAG_get_bag_nid().
PKCS8_get_attr()
ASN1_TYPE* PKCS8_get_attr (PKCS8_PRIV_KEY_INFO * p8, int attr_nid)
Definition at line 28 of file p12_sbag.c.
References PKCS12_get_attr_gen().
STACK_OF()
const STACK_OF (PKCS12_SAFEBAG)
Definition at line 47 of file p12_sbag.c.
References NID_safeContentsBag, NULL, and OBJ_obj2nid().