crypto/pkcs12/p12_crt.c File Reference
p12_crt.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/pkcs12.h>
#include "p12_lcl.h"
Functions
PKCS12 * PKCS12_create (const char *pass, const char *name, EVP_PKEY *pkey, X509 *cert, STACK_OF(X509) *ca, int nid_key, int nid_cert, int iter, int mac_iter, int keytype)
PKCS12_SAFEBAG * PKCS12_add_cert (STACK_OF(PKCS12_SAFEBAG) **pbags, X509 *cert)
PKCS12_SAFEBAG * PKCS12_add_key (STACK_OF(PKCS12_SAFEBAG) **pbags, EVP_PKEY *key, int key_usage, int iter, int nid_key, const char *pass)
int PKCS12_add_safe (STACK_OF(PKCS7) **psafes, STACK_OF(PKCS12_SAFEBAG) *bags, int nid_safe, int iter, const char *pass)
PKCS12 * PKCS12_add_safes (STACK_OF(PKCS7) *safes, int nid_p7)
Function Documentation
PKCS12_add_cert()
PKCS12_SAFEBAG* PKCS12_add_cert (STACK_OF(PKCS12_SAFEBAG) ** pbags, X509 * cert)
Definition at line 134 of file p12_crt.c.
References NULL, PKCS12_add_friendlyname, PKCS12_add_localkeyid(), PKCS12_SAFEBAG_create_cert(), X509_alias_get0(), and X509_keyid_get0().
PKCS12_add_key()
PKCS12_SAFEBAG* PKCS12_add_key (STACK_OF(PKCS12_SAFEBAG) ** pbags, EVP_PKEY * key, int key_usage, int iter, int nid_key, const char * pass)
Definition at line 171 of file p12_crt.c.
References EVP_PKEY2PKCS8(), NULL, PKCS12_SAFEBAG_create0_p8inf(), PKCS12_SAFEBAG_create_pkcs8_encrypt(), and PKCS8_add_keyusage().
PKCS12_add_safe()
int PKCS12_add_safe (STACK_OF(PKCS7) ** psafes, STACK_OF(PKCS12_SAFEBAG) * bags, int nid_safe, int iter, const char * pass)
Definition at line 205 of file p12_crt.c.
References NID_pbe_WithSHA1And3_Key_TripleDES_CBC, NID_pbe_WithSHA1And40BitRC2_CBC, NULL, PKCS12_pack_p7data(), and PKCS12_pack_p7encdata().
PKCS12_add_safes()
PKCS12* PKCS12_add_safes (STACK_OF(PKCS7) * safes, int nid_p7)
Definition at line 274 of file p12_crt.c.
References NID_pkcs7_data, NULL, PKCS12_init(), and PKCS12_pack_authsafes().
PKCS12_create()
PKCS12* PKCS12_create (const char * pass, const char * name, EVP_PKEY * pkey, X509 * cert, STACK_OF(X509) * ca, int nid_key, int nid_cert, int iter, int mac_iter, int keytype)
Definition at line 31 of file p12_crt.c.