crypto/pkcs12/p12_p8d.c File Reference
p12_p8d.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/pkcs12.h>
Functions
PKCS8_PRIV_KEY_INFO * PKCS8_decrypt (const X509_SIG *p8, const char *pass, int passlen)
Function Documentation
PKCS8_decrypt()
PKCS8_PRIV_KEY_INFO* PKCS8_decrypt (const X509_SIG * p8, const char * pass, int passlen)
Definition at line 14 of file p12_p8d.c.
References ASN1_ITEM_rptr, PKCS12_item_decrypt_d2i(), and X509_SIG_get0().
Referenced by PKCS12_decrypt_skey().