crypto/pkcs12/p12_init.c File Reference
p12_init.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/pkcs12.h>
#include "p12_lcl.h"
Functions
PKCS12 * PKCS12_init (int mode)
Function Documentation
PKCS12_init()
PKCS12* PKCS12_init (int mode)
Definition at line 17 of file p12_init.c.
References ASN1_INTEGER_set(), ERR_R_MALLOC_FAILURE, NID_pkcs7_data, NULL, OBJ_nid2obj(), PKCS12_F_PKCS12_INIT, PKCS12_R_UNSUPPORTED_PKCS12_MODE, and PKCS12err.
Referenced by PKCS12_add_safes().