crypto/pkcs12/p12_decr.c File Reference
p12_decr.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/pkcs12.h>
Functions
unsigned char * PKCS12_pbe_crypt (const X509_ALGOR *algor, const char *pass, int passlen, const unsigned char *in, int inlen, unsigned char **data, int *datalen, int en_de)
void * PKCS12_item_decrypt_d2i (const X509_ALGOR *algor, const ASN1_ITEM *it, const char *pass, int passlen, const ASN1_OCTET_STRING *oct, int zbuf)
ASN1_OCTET_STRING * PKCS12_item_i2d_encrypt (X509_ALGOR *algor, const ASN1_ITEM *it, const char *pass, int passlen, void *obj, int zbuf)
Function Documentation
PKCS12_item_decrypt_d2i()
void* PKCS12_item_decrypt_d2i (const X509_ALGOR * algor, const ASN1_ITEM * it, const char * pass, int passlen, const ASN1_OCTET_STRING * oct, int zbuf)
Definition at line 82 of file p12_decr.c.
Referenced by PKCS12_pack_p7encdata(), and PKCS8_decrypt().
PKCS12_item_i2d_encrypt()
ASN1_OCTET_STRING* PKCS12_item_i2d_encrypt (X509_ALGOR * algor, const ASN1_ITEM * it, const char * pass, int passlen, void * obj, int zbuf)
Definition at line 124 of file p12_decr.c.
References ASN1_item_i2d(), ERR_R_MALLOC_FAILURE, in, inlen, NULL, OPENSSL_cleanse(), OPENSSL_free, PKCS12_F_PKCS12_ITEM_I2D_ENCRYPT, PKCS12_pbe_crypt(), PKCS12_R_ENCODE_ERROR, PKCS12_R_ENCRYPT_ERROR, and PKCS12err.
Referenced by PKCS12_pack_p7encdata(), and PKCS8_set0_pbe().
PKCS12_pbe_crypt()
unsigned char* PKCS12_pbe_crypt (const X509_ALGOR * algor, const char * pass, int passlen, const unsigned char * in, int inlen, unsigned char ** data, int * datalen, int en_de)
Definition at line 23 of file p12_decr.c.
Referenced by PKCS12_item_i2d_encrypt().