crypto/pkcs12/p12_attr.c File Reference
p12_attr.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/pkcs12.h>
#include "p12_lcl.h"
Functions
int PKCS12_add_localkeyid (PKCS12_SAFEBAG *bag, unsigned char *name, int namelen)
int PKCS8_add_keyusage (PKCS8_PRIV_KEY_INFO *p8, int usage)
int PKCS12_add_friendlyname_asc (PKCS12_SAFEBAG *bag, const char *name, int namelen)
int PKCS12_add_friendlyname_utf8 (PKCS12_SAFEBAG *bag, const char *name, int namelen)
int PKCS12_add_friendlyname_uni (PKCS12_SAFEBAG *bag, const unsigned char *name, int namelen)
int PKCS12_add_CSPName_asc (PKCS12_SAFEBAG *bag, const char *name, int namelen)
ASN1_TYPE * PKCS12_get_attr_gen (const STACK_OF(X509_ATTRIBUTE) *attrs, int attr_nid)
char * PKCS12_get_friendlyname (PKCS12_SAFEBAG *bag)
const STACK_OF (X509_ATTRIBUTE)
Function Documentation
PKCS12_add_CSPName_asc()
int PKCS12_add_CSPName_asc (PKCS12_SAFEBAG * bag, const char * name, int namelen)
Definition at line 68 of file p12_attr.c.
References MBSTRING_ASC, and NID_ms_csp_name.
PKCS12_add_friendlyname_asc()
int PKCS12_add_friendlyname_asc (PKCS12_SAFEBAG * bag, const char * name, int namelen)
Definition at line 38 of file p12_attr.c.
References MBSTRING_ASC, and NID_friendlyName.
PKCS12_add_friendlyname_uni()
int PKCS12_add_friendlyname_uni (PKCS12_SAFEBAG * bag, const unsigned char * name, int namelen)
Definition at line 58 of file p12_attr.c.
References MBSTRING_BMP, and NID_friendlyName.
PKCS12_add_friendlyname_utf8()
int PKCS12_add_friendlyname_utf8 (PKCS12_SAFEBAG * bag, const char * name, int namelen)
Definition at line 48 of file p12_attr.c.
References MBSTRING_UTF8, and NID_friendlyName.
PKCS12_add_localkeyid()
int PKCS12_add_localkeyid (PKCS12_SAFEBAG * bag, unsigned char * name, int namelen)
Definition at line 17 of file p12_attr.c.
References NID_localKeyID, and V_ASN1_OCTET_STRING.
Referenced by PKCS12_add_cert().
PKCS12_get_attr_gen()
ASN1_TYPE* PKCS12_get_attr_gen (const STACK_OF(X509_ATTRIBUTE) * attrs, int attr_nid)
Definition at line 77 of file p12_attr.c.
References X509_ATTRIBUTE_get0_type(), X509at_get_attr(), and X509at_get_attr_by_NID().
Referenced by PKCS12_get_attr(), PKCS12_SAFEBAG_get0_attr(), and PKCS8_get_attr().
PKCS12_get_friendlyname()
char* PKCS12_get_friendlyname (PKCS12_SAFEBAG * bag)
Definition at line 87 of file p12_attr.c.
References ASN1_TYPE::bmpstring, NID_friendlyName, NULL, OPENSSL_uni2utf8(), PKCS12_SAFEBAG_get0_attr(), ASN1_TYPE::type, V_ASN1_BMPSTRING, and ASN1_TYPE::value.
PKCS8_add_keyusage()
int PKCS8_add_keyusage (PKCS8_PRIV_KEY_INFO * p8, int usage)
Definition at line 29 of file p12_attr.c.
References NID_key_usage, PKCS8_pkey_add1_attr_by_NID(), and V_ASN1_BIT_STRING.
Referenced by PKCS12_add_key().
STACK_OF()
const STACK_OF (X509_ATTRIBUTE)
Definition at line 99 of file p12_attr.c.