crypto/pkcs12/p12_mutl.c File Reference
p12_mutl.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/crypto.h>
#include <openssl/hmac.h>
#include <openssl/rand.h>
#include <openssl/pkcs12.h>
#include "p12_lcl.h"
Macros
#define TK26_MAC_KEY_LEN 32
Functions
int PKCS12_mac_present (const PKCS12 *p12)
void PKCS12_get0_mac (const ASN1_OCTET_STRING **pmac, const X509_ALGOR **pmacalg, const ASN1_OCTET_STRING **psalt, const ASN1_INTEGER **piter, const PKCS12 *p12)
int PKCS12_gen_mac (PKCS12 *p12, const char *pass, int passlen, unsigned char *mac, unsigned int *maclen)
int PKCS12_verify_mac (PKCS12 *p12, const char *pass, int passlen)
int PKCS12_set_mac (PKCS12 *p12, const char *pass, int passlen, unsigned char *salt, int saltlen, int iter, const EVP_MD *md_type)
int PKCS12_setup_mac (PKCS12 *p12, int iter, unsigned char *salt, int saltlen, const EVP_MD *md_type)
Macro Definition Documentation
TK26_MAC_KEY_LEN
#define TK26_MAC_KEY_LEN 32
Definition at line 47 of file p12_mutl.c.
Function Documentation
PKCS12_gen_mac()
int PKCS12_gen_mac (PKCS12 * p12, const char * pass, int passlen, unsigned char * mac, unsigned int * maclen)
Definition at line 139 of file p12_mutl.c.
PKCS12_get0_mac()
void PKCS12_get0_mac (const ASN1_OCTET_STRING ** pmac, const X509_ALGOR ** pmacalg, const ASN1_OCTET_STRING ** psalt, const ASN1_INTEGER ** piter, const PKCS12 * p12)
Definition at line 23 of file p12_mutl.c.
References NULL, and X509_SIG_get0().
PKCS12_mac_present()
int PKCS12_mac_present (const PKCS12 * p12)
Definition at line 18 of file p12_mutl.c.
PKCS12_set_mac()
int PKCS12_set_mac (PKCS12 * p12, const char * pass, int passlen, unsigned char * salt, int saltlen, int iter, const EVP_MD * md_type)
Definition at line 171 of file p12_mutl.c.
References EVP_MAX_MD_SIZE, EVP_sha1(), PKCS12_ERROR, PKCS12_F_PKCS12_SET_MAC, PKCS12_R_MAC_SETUP_ERROR, PKCS12_setup_mac(), and PKCS12err.
PKCS12_setup_mac()
int PKCS12_setup_mac (PKCS12 * p12, int iter, unsigned char * salt, int saltlen, const EVP_MD * md_type)
Definition at line 202 of file p12_mutl.c.
References ASN1_INTEGER_set(), ERR_R_MALLOC_FAILURE, EVP_MD_type(), NULL, OBJ_nid2obj(), OPENSSL_malloc, PKCS12_ERROR, PKCS12_F_PKCS12_SETUP_MAC, PKCS12_SALT_LEN, PKCS12err, RAND_bytes(), V_ASN1_NULL, X509_ALGOR_set0(), and X509_SIG_getm().
Referenced by PKCS12_set_mac().
PKCS12_verify_mac()
int PKCS12_verify_mac (PKCS12 * p12, const char * pass, int passlen)
Definition at line 146 of file p12_mutl.c.
References EVP_MAX_MD_SIZE, NULL, PKCS12_F_PKCS12_VERIFY_MAC, PKCS12_R_MAC_ABSENT, and PKCS12err.
Referenced by PKCS12_newpass().