crypto/pkcs12/p12_add.c File Reference
p12_add.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/pkcs12.h>
#include "p12_lcl.h"
Functions
PKCS12_SAFEBAG * PKCS12_item_pack_safebag (void *obj, const ASN1_ITEM *it, int nid1, int nid2)
PKCS7 * PKCS12_pack_p7data (STACK_OF(PKCS12_SAFEBAG) *sk)
STACK_OF (PKCS12_SAFEBAG)
PKCS7 * PKCS12_pack_p7encdata (int pbe_nid, const char *pass, int passlen, unsigned char *salt, int saltlen, int iter, STACK_OF(PKCS12_SAFEBAG) *bags)
PKCS8_PRIV_KEY_INFO * PKCS12_decrypt_skey (const PKCS12_SAFEBAG *bag, const char *pass, int passlen)
int PKCS12_pack_authsafes (PKCS12 *p12, STACK_OF(PKCS7) *safes)
STACK_OF (PKCS7)
Function Documentation
PKCS12_decrypt_skey()
PKCS8_PRIV_KEY_INFO* PKCS12_decrypt_skey (const PKCS12_SAFEBAG * bag, const char * pass, int passlen)
Definition at line 141 of file p12_add.c.
References PKCS8_decrypt().
PKCS12_item_pack_safebag()
PKCS12_SAFEBAG* PKCS12_item_pack_safebag (void * obj, const ASN1_ITEM * it, int nid1, int nid2)
Definition at line 17 of file p12_add.c.
References ASN1_item_pack(), ERR_R_MALLOC_FAILURE, NULL, OBJ_nid2obj(), PKCS12_F_PKCS12_ITEM_PACK_SAFEBAG, and PKCS12err.
Referenced by PKCS12_SAFEBAG_create_cert(), and PKCS12_SAFEBAG_create_crl().
PKCS12_pack_authsafes()
int PKCS12_pack_authsafes (PKCS12 * p12, STACK_OF(PKCS7) * safes)
Definition at line 147 of file p12_add.c.
References ASN1_item_pack(), and ASN1_ITEM_rptr.
Referenced by PKCS12_add_safes().
PKCS12_pack_p7data()
PKCS7* PKCS12_pack_p7data (STACK_OF(PKCS12_SAFEBAG) * sk)
Definition at line 46 of file p12_add.c.
References ASN1_item_pack(), ASN1_ITEM_rptr, PKCS7::d, PKCS7::data, ERR_R_MALLOC_FAILURE, NID_pkcs7_data, NULL, OBJ_nid2obj(), PKCS12_F_PKCS12_PACK_P7DATA, PKCS12_R_CANT_PACK_STRUCTURE, PKCS12err, and PKCS7::type.
Referenced by PKCS12_add_safe().
PKCS12_pack_p7encdata()
PKCS7* PKCS12_pack_p7encdata (int pbe_nid, const char * pass, int passlen, unsigned char * salt, int saltlen, int iter, STACK_OF(PKCS12_SAFEBAG) * bags)
Definition at line 84 of file p12_add.c.
References PKCS7_ENC_CONTENT::algorithm, ASN1_ITEM_rptr, PKCS7::d, PKCS7_ENC_CONTENT::enc_data, PKCS7_ENCRYPT::enc_data, PKCS7::encrypted, ERR_R_MALLOC_FAILURE, EVP_get_cipherbynid, NID_pkcs7_encrypted, NULL, PKCS12_F_PKCS12_PACK_P7ENCDATA, PKCS12_item_decrypt_d2i(), PKCS12_item_i2d_encrypt(), PKCS12_R_ENCRYPT_ERROR, PKCS12_R_ERROR_SETTING_ENCRYPTED_DATA_TYPE, PKCS12err, PKCS5_pbe2_set(), PKCS5_pbe_set(), PKCS7_set_type(), PKCS7_type_is_encrypted, and STACK_OF().
Referenced by PKCS12_add_safe().
STACK_OF() [1/2]
STACK_OF (PKCS12_SAFEBAG)
Definition at line 72 of file p12_add.c.
References ASN1_ITEM_rptr, ASN1_item_unpack(), PKCS7::d, PKCS7::data, NULL, PKCS12_F_PKCS12_UNPACK_P7DATA, PKCS12_R_CONTENT_TYPE_NOT_DATA, PKCS12err, and PKCS7_type_is_data.
Referenced by PKCS12_pack_p7encdata().
STACK_OF() [2/2]
STACK_OF (PKCS7)
Definition at line 155 of file p12_add.c.
References ASN1_ITEM_rptr, ASN1_item_unpack(), NULL, PKCS12_F_PKCS12_UNPACK_AUTHSAFES, PKCS12_R_CONTENT_TYPE_NOT_DATA, PKCS12err, and PKCS7_type_is_data.