crypto/evp/p_lib.c File Reference
p_lib.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/bn.h>
#include <openssl/err.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include <openssl/rsa.h>
#include <openssl/dsa.h>
#include <openssl/dh.h>
#include <openssl/engine.h>
#include "internal/asn1_int.h"
#include "internal/evp_int.h"
Functions
int EVP_PKEY_bits (const EVP_PKEY *pkey)
int EVP_PKEY_security_bits (const EVP_PKEY *pkey)
int EVP_PKEY_size (EVP_PKEY *pkey)
int EVP_PKEY_save_parameters (EVP_PKEY *pkey, int mode)
int EVP_PKEY_copy_parameters (EVP_PKEY *to, const EVP_PKEY *from)
int EVP_PKEY_missing_parameters (const EVP_PKEY *pkey)
int EVP_PKEY_cmp_parameters (const EVP_PKEY *a, const EVP_PKEY *b)
int EVP_PKEY_cmp (const EVP_PKEY *a, const EVP_PKEY *b)
EVP_PKEY * EVP_PKEY_new (void)
int EVP_PKEY_up_ref (EVP_PKEY *pkey)
int EVP_PKEY_set_type (EVP_PKEY *pkey, int type)
int EVP_PKEY_set_type_str (EVP_PKEY *pkey, const char *str, int len)
int EVP_PKEY_assign (EVP_PKEY *pkey, int type, void *key)
void * EVP_PKEY_get0 (const EVP_PKEY *pkey)
const unsigned char * EVP_PKEY_get0_hmac (const EVP_PKEY *pkey, size_t *len)
const unsigned char * EVP_PKEY_get0_poly1305 (const EVP_PKEY *pkey, size_t *len)
const unsigned char * EVP_PKEY_get0_siphash (const EVP_PKEY *pkey, size_t *len)
int EVP_PKEY_set1_RSA (EVP_PKEY *pkey, RSA *key)
RSA * EVP_PKEY_get0_RSA (EVP_PKEY *pkey)
RSA * EVP_PKEY_get1_RSA (EVP_PKEY *pkey)
int EVP_PKEY_set1_DSA (EVP_PKEY *pkey, DSA *key)
DSA * EVP_PKEY_get0_DSA (EVP_PKEY *pkey)
DSA * EVP_PKEY_get1_DSA (EVP_PKEY *pkey)
int EVP_PKEY_set1_EC_KEY (EVP_PKEY *pkey, EC_KEY *key)
EC_KEY * EVP_PKEY_get0_EC_KEY (EVP_PKEY *pkey)
EC_KEY * EVP_PKEY_get1_EC_KEY (EVP_PKEY *pkey)
int EVP_PKEY_set1_DH (EVP_PKEY *pkey, DH *key)
DH * EVP_PKEY_get0_DH (EVP_PKEY *pkey)
DH * EVP_PKEY_get1_DH (EVP_PKEY *pkey)
int EVP_PKEY_type (int type)
int EVP_PKEY_id (const EVP_PKEY *pkey)
int EVP_PKEY_base_id (const EVP_PKEY *pkey)
void EVP_PKEY_free (EVP_PKEY *x)
int EVP_PKEY_print_public (BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx)
int EVP_PKEY_print_private (BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx)
int EVP_PKEY_print_params (BIO *out, const EVP_PKEY *pkey, int indent, ASN1_PCTX *pctx)
int EVP_PKEY_get_default_digest_nid (EVP_PKEY *pkey, int *pnid)
int EVP_PKEY_set1_tls_encodedpoint (EVP_PKEY *pkey, const unsigned char *pt, size_t ptlen)
size_t EVP_PKEY_get1_tls_encodedpoint (EVP_PKEY *pkey, unsigned char **ppt)
Function Documentation
EVP_PKEY_assign()
int EVP_PKEY_assign (EVP_PKEY * pkey, int type, void * key)
Definition at line 227 of file p_lib.c.
References EVP_PKEY_set_type(), key, and NULL.
EVP_PKEY_base_id()
int EVP_PKEY_base_id (const EVP_PKEY * pkey)
Definition at line 412 of file p_lib.c.
References EVP_PKEY_type().
EVP_PKEY_bits()
int EVP_PKEY_bits (const EVP_PKEY * pkey)
Definition at line 27 of file p_lib.c.
Referenced by ssl_print_tmp_key().
EVP_PKEY_cmp()
int EVP_PKEY_cmp (const EVP_PKEY * a, const EVP_PKEY * b)
Definition at line 117 of file p_lib.c.
EVP_PKEY_cmp_parameters()
int EVP_PKEY_cmp_parameters (const EVP_PKEY * a, const EVP_PKEY * b)
Definition at line 108 of file p_lib.c.
Referenced by EVP_PKEY_copy_parameters().
EVP_PKEY_copy_parameters()
int EVP_PKEY_copy_parameters (EVP_PKEY * to, const EVP_PKEY * from)
Definition at line 73 of file p_lib.c.
References EVP_F_EVP_PKEY_COPY_PARAMETERS, EVP_PKEY_cmp_parameters(), EVP_PKEY_missing_parameters(), EVP_PKEY_NONE, EVP_PKEY_set_type(), EVP_R_DIFFERENT_KEY_TYPES, EVP_R_DIFFERENT_PARAMETERS, EVP_R_MISSING_PARAMETERS, and EVPerr.
EVP_PKEY_free()
void EVP_PKEY_free (EVP_PKEY * x)
Definition at line 417 of file p_lib.c.
References CRYPTO_DOWN_REF, NULL, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by CMS_SignerInfo_set1_signer_cert(), CTLOG_free(), EVP_PKCS82PKEY(), EVP_PKEY_CTX_free(), SCT_CTX_free(), ssl3_clear(), ssl3_ctx_ctrl(), ssl3_free(), ssl_excert_free(), ssl_print_tmp_key(), tls_construct_stoc_key_share(), TS_RESP_CTX_free(), TS_RESP_CTX_set_signer_key(), and X509_PKEY_free().
EVP_PKEY_get0()
void* EVP_PKEY_get0 (const EVP_PKEY * pkey)
Definition at line 235 of file p_lib.c.
Referenced by EVP_PKEY_get0_hmac(), EVP_PKEY_get0_poly1305(), and EVP_PKEY_get0_siphash().
EVP_PKEY_get0_DH()
DH* EVP_PKEY_get0_DH (EVP_PKEY * pkey)
Definition at line 373 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_DH, EVP_PKEY_DH, EVP_PKEY_DHX, EVP_R_EXPECTING_A_DH_KEY, EVPerr, and NULL.
EVP_PKEY_get0_DSA()
DSA* EVP_PKEY_get0_DSA (EVP_PKEY * pkey)
Definition at line 317 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_DSA, EVP_PKEY_DSA, EVP_R_EXPECTING_A_DSA_KEY, EVPerr, and NULL.
Referenced by i2d_PublicKey().
EVP_PKEY_get0_EC_KEY()
EC_KEY* EVP_PKEY_get0_EC_KEY (EVP_PKEY * pkey)
Definition at line 345 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_EC_KEY, EVP_PKEY_EC, EVP_R_EXPECTING_A_EC_KEY, EVPerr, and NULL.
Referenced by i2d_PublicKey().
EVP_PKEY_get0_hmac()
const unsigned char* EVP_PKEY_get0_hmac (const EVP_PKEY * pkey, size_t * len)
Definition at line 240 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_HMAC, EVP_PKEY_get0(), EVP_PKEY_HMAC, EVP_R_EXPECTING_AN_HMAC_KEY, EVPerr, and NULL.
EVP_PKEY_get0_poly1305()
const unsigned char* EVP_PKEY_get0_poly1305 (const EVP_PKEY * pkey, size_t * len)
Definition at line 253 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_POLY1305, EVP_PKEY_get0(), EVP_PKEY_POLY1305, EVP_R_EXPECTING_A_POLY1305_KEY, EVPerr, and NULL.
EVP_PKEY_get0_RSA()
RSA* EVP_PKEY_get0_RSA (EVP_PKEY * pkey)
Definition at line 290 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_RSA, EVP_PKEY_RSA, EVP_R_EXPECTING_AN_RSA_KEY, EVPerr, and NULL.
Referenced by i2d_PublicKey().
EVP_PKEY_get0_siphash()
const unsigned char* EVP_PKEY_get0_siphash (const EVP_PKEY * pkey, size_t * len)
Definition at line 267 of file p_lib.c.
References EVP_F_EVP_PKEY_GET0_SIPHASH, EVP_PKEY_get0(), EVP_PKEY_SIPHASH, EVP_R_EXPECTING_A_SIPHASH_KEY, EVPerr, and NULL.
EVP_PKEY_get1_DH()
DH* EVP_PKEY_get1_DH (EVP_PKEY * pkey)
Definition at line 382 of file p_lib.c.
EVP_PKEY_get1_DSA()
DSA* EVP_PKEY_get1_DSA (EVP_PKEY * pkey)
Definition at line 326 of file p_lib.c.
EVP_PKEY_get1_EC_KEY()
EC_KEY* EVP_PKEY_get1_EC_KEY (EVP_PKEY * pkey)
Definition at line 354 of file p_lib.c.
Referenced by ssl_print_tmp_key().
EVP_PKEY_get1_RSA()
RSA* EVP_PKEY_get1_RSA (EVP_PKEY * pkey)
Definition at line 299 of file p_lib.c.
EVP_PKEY_get1_tls_encodedpoint()
size_t EVP_PKEY_get1_tls_encodedpoint (EVP_PKEY * pkey, unsigned char ** ppt)
Definition at line 506 of file p_lib.c.
Referenced by tls_construct_stoc_key_share().
EVP_PKEY_get_default_digest_nid()
int EVP_PKEY_get_default_digest_nid (EVP_PKEY * pkey, int * pnid)
Definition at line 490 of file p_lib.c.
Referenced by PKCS7_add_signature().
EVP_PKEY_id()
int EVP_PKEY_id (const EVP_PKEY * pkey)
Definition at line 407 of file p_lib.c.
Referenced by i2d_PublicKey(), ssl_cert_type(), and ssl_print_tmp_key().
EVP_PKEY_missing_parameters()
int EVP_PKEY_missing_parameters (const EVP_PKEY * pkey)
Definition at line 101 of file p_lib.c.
Referenced by EVP_PKEY_copy_parameters().
EVP_PKEY_new()
EVP_PKEY* EVP_PKEY_new (void)
Definition at line 138 of file p_lib.c.
Referenced by d2i_PrivateKey_bio(), d2i_PrivateKey_fp(), d2i_PUBKEY_bio(), d2i_PUBKEY_fp(), and EVP_PKCS82PKEY().
EVP_PKEY_print_params()
int EVP_PKEY_print_params (BIO * out, const EVP_PKEY * pkey, int indent, ASN1_PCTX * pctx)
Definition at line 475 of file p_lib.c.
EVP_PKEY_print_private()
int EVP_PKEY_print_private (BIO * out, const EVP_PKEY * pkey, int indent, ASN1_PCTX * pctx)
Definition at line 466 of file p_lib.c.
EVP_PKEY_print_public()
int EVP_PKEY_print_public (BIO * out, const EVP_PKEY * pkey, int indent, ASN1_PCTX * pctx)
Definition at line 457 of file p_lib.c.
Referenced by X509_REQ_print_ex().
EVP_PKEY_save_parameters()
int EVP_PKEY_save_parameters (EVP_PKEY * pkey, int mode)
Definition at line 50 of file p_lib.c.
References EVP_PKEY_DSA.
EVP_PKEY_security_bits()
int EVP_PKEY_security_bits (const EVP_PKEY * pkey)
Definition at line 34 of file p_lib.c.
References NULL.
Referenced by ssl3_ctx_ctrl(), and ssl_get_auto_dh().
EVP_PKEY_set1_DH()
int EVP_PKEY_set1_DH (EVP_PKEY * pkey, DH * key)
Definition at line 365 of file p_lib.c.
EVP_PKEY_set1_DSA()
int EVP_PKEY_set1_DSA (EVP_PKEY * pkey, DSA * key)
Definition at line 309 of file p_lib.c.
EVP_PKEY_set1_EC_KEY()
int EVP_PKEY_set1_EC_KEY (EVP_PKEY * pkey, EC_KEY * key)
Definition at line 337 of file p_lib.c.
EVP_PKEY_set1_RSA()
int EVP_PKEY_set1_RSA (EVP_PKEY * pkey, RSA * key)
Definition at line 282 of file p_lib.c.
EVP_PKEY_set1_tls_encodedpoint()
int EVP_PKEY_set1_tls_encodedpoint (EVP_PKEY * pkey, const unsigned char * pt, size_t ptlen)
Definition at line 495 of file p_lib.c.
EVP_PKEY_set_type()
int EVP_PKEY_set_type (EVP_PKEY * pkey, int type)
Definition at line 217 of file p_lib.c.
Referenced by EVP_PKCS82PKEY(), EVP_PKEY_assign(), and EVP_PKEY_copy_parameters().
EVP_PKEY_set_type_str()
int EVP_PKEY_set_type_str (EVP_PKEY * pkey, const char * str, int len)
Definition at line 222 of file p_lib.c.
EVP_PKEY_size()
int EVP_PKEY_size (EVP_PKEY * pkey)
Definition at line 43 of file p_lib.c.
Referenced by ASN1_item_sign_ctx(), ASN1_sign(), and EVP_SignFinal().
EVP_PKEY_type()
int EVP_PKEY_type (int type)
Definition at line 391 of file p_lib.c.
Referenced by EVP_PKEY_base_id(), and X509_get_signature_type().
EVP_PKEY_up_ref()
int EVP_PKEY_up_ref (EVP_PKEY * pkey)
Definition at line 159 of file p_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by TS_RESP_CTX_set_signer_key().