crypto/evp/p_verify.c File Reference
p_verify.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/evp.h>
#include <openssl/objects.h>
#include <openssl/x509.h>
#include "internal/evp_int.h"
Functions
int EVP_VerifyFinal (EVP_MD_CTX *ctx, const unsigned char *sigbuf, unsigned int siglen, EVP_PKEY *pkey)
Function Documentation
EVP_VerifyFinal()
int EVP_VerifyFinal (EVP_MD_CTX * ctx, const unsigned char * sigbuf, unsigned int siglen, EVP_PKEY * pkey)
Definition at line 17 of file p_verify.c.
References ERR_R_MALLOC_FAILURE, EVP_DigestFinal_ex(), EVP_F_EVP_VERIFYFINAL, EVP_MAX_MD_SIZE, EVP_MD_CTX_copy_ex(), EVP_MD_CTX_FLAG_FINALISE, EVP_MD_CTX_free(), EVP_MD_CTX_md(), EVP_MD_CTX_new(), EVP_MD_CTX_test_flags(), EVP_PKEY_CTX_free(), EVP_PKEY_CTX_new(), EVP_PKEY_CTX_set_signature_md, EVP_PKEY_verify(), EVP_PKEY_verify_init(), EVPerr, and NULL.
Referenced by PKCS7_signatureVerify().