ssl/packet_locl.h File Reference
packet_locl.h File Reference
#include <string.h>
#include <openssl/bn.h>
#include <openssl/buffer.h>
#include <openssl/crypto.h>
#include <openssl/e_os2.h>
#include "internal/numbers.h"
Data Structures
struct PACKET
struct WPACKET_SUB
struct WPACKET
Macros
#define WPACKET_FLAGS_NONE 0
#define WPACKET_FLAGS_NON_ZERO_LENGTH 1
#define WPACKET_FLAGS_ABANDON_ON_ZERO_LENGTH 2
#define WPACKET_start_sub_packet_u8(pkt) WPACKET_start_sub_packet_len__((pkt), 1)
#define WPACKET_start_sub_packet_u16(pkt) WPACKET_start_sub_packet_len__((pkt), 2)
#define WPACKET_start_sub_packet_u24(pkt) WPACKET_start_sub_packet_len__((pkt), 3)
#define WPACKET_start_sub_packet_u32(pkt) WPACKET_start_sub_packet_len__((pkt), 4)
#define WPACKET_sub_allocate_bytes_u8(pkt, len, bytes) WPACKET_sub_allocate_bytes__((pkt), (len), (bytes), 1)
#define WPACKET_sub_allocate_bytes_u16(pkt, len, bytes) WPACKET_sub_allocate_bytes__((pkt), (len), (bytes), 2)
#define WPACKET_sub_allocate_bytes_u24(pkt, len, bytes) WPACKET_sub_allocate_bytes__((pkt), (len), (bytes), 3)
#define WPACKET_sub_allocate_bytes_u32(pkt, len, bytes) WPACKET_sub_allocate_bytes__((pkt), (len), (bytes), 4)
#define WPACKET_sub_reserve_bytes_u8(pkt, len, bytes) WPACKET_reserve_bytes__((pkt), (len), (bytes), 1)
#define WPACKET_sub_reserve_bytes_u16(pkt, len, bytes) WPACKET_sub_reserve_bytes__((pkt), (len), (bytes), 2)
#define WPACKET_sub_reserve_bytes_u24(pkt, len, bytes) WPACKET_sub_reserve_bytes__((pkt), (len), (bytes), 3)
#define WPACKET_sub_reserve_bytes_u32(pkt, len, bytes) WPACKET_sub_reserve_bytes__((pkt), (len), (bytes), 4)
#define WPACKET_put_bytes_u8(pkt, val) WPACKET_put_bytes__((pkt), (val), 1)
#define WPACKET_put_bytes_u16(pkt, val) WPACKET_put_bytes__((pkt), (val), 2)
#define WPACKET_put_bytes_u24(pkt, val) WPACKET_put_bytes__((pkt), (val), 3)
#define WPACKET_put_bytes_u32(pkt, val) WPACKET_put_bytes__((pkt), (val), 4)
#define WPACKET_sub_memcpy_u8(pkt, src, len) WPACKET_sub_memcpy__((pkt), (src), (len), 1)
#define WPACKET_sub_memcpy_u16(pkt, src, len) WPACKET_sub_memcpy__((pkt), (src), (len), 2)
#define WPACKET_sub_memcpy_u24(pkt, src, len) WPACKET_sub_memcpy__((pkt), (src), (len), 3)
#define WPACKET_sub_memcpy_u32(pkt, src, len) WPACKET_sub_memcpy__((pkt), (src), (len), 4)
Functions
int WPACKET_init_len (WPACKET *pkt, BUF_MEM *buf, size_t lenbytes)
int WPACKET_init (WPACKET *pkt, BUF_MEM *buf)
int WPACKET_init_static_len (WPACKET *pkt, unsigned char *buf, size_t len, size_t lenbytes)
int WPACKET_set_flags (WPACKET *pkt, unsigned int flags)
int WPACKET_close (WPACKET *pkt)
int WPACKET_finish (WPACKET *pkt)
int WPACKET_fill_lengths (WPACKET *pkt)
int WPACKET_start_sub_packet_len__ (WPACKET *pkt, size_t lenbytes)
int WPACKET_start_sub_packet (WPACKET *pkt)
int WPACKET_allocate_bytes (WPACKET *pkt, size_t len, unsigned char **allocbytes)
int WPACKET_sub_allocate_bytes__ (WPACKET *pkt, size_t len, unsigned char **allocbytes, size_t lenbytes)
int WPACKET_reserve_bytes (WPACKET *pkt, size_t len, unsigned char **allocbytes)
int WPACKET_sub_reserve_bytes__ (WPACKET *pkt, size_t len, unsigned char **allocbytes, size_t lenbytes)
int WPACKET_put_bytes__ (WPACKET *pkt, unsigned int val, size_t bytes)
int WPACKET_set_max_size (WPACKET *pkt, size_t maxsize)
int WPACKET_memcpy (WPACKET *pkt, const void *src, size_t len)
int WPACKET_sub_memcpy__ (WPACKET *pkt, const void *src, size_t len, size_t lenbytes)
int WPACKET_get_total_written (WPACKET *pkt, size_t *written)
int WPACKET_get_length (WPACKET *pkt, size_t *len)
unsigned char * WPACKET_get_curr (WPACKET *pkt)
void WPACKET_cleanup (WPACKET *pkt)
Macro Definition Documentation
WPACKET_FLAGS_ABANDON_ON_ZERO_LENGTH
#define WPACKET_FLAGS_ABANDON_ON_ZERO_LENGTH 2
Definition at line 659 of file packet_locl.h.
Referenced by tls_construct_extensions().
WPACKET_FLAGS_NON_ZERO_LENGTH
#define WPACKET_FLAGS_NON_ZERO_LENGTH 1
Definition at line 653 of file packet_locl.h.
Referenced by tls_construct_ctos_srp().
WPACKET_FLAGS_NONE
#define WPACKET_FLAGS_NONE 0
Definition at line 650 of file packet_locl.h.
WPACKET_put_bytes_u16
#define WPACKET_put_bytes_u16 (pkt, val) WPACKET_put_bytes__((pkt), (val), 2)
Definition at line 823 of file packet_locl.h.
Referenced by dtls_construct_change_cipher_spec(), ssl3_put_cipher_by_char(), tls_construct_ctos_alpn(), tls_construct_ctos_ems(), tls_construct_ctos_etm(), tls_construct_ctos_key_share(), tls_construct_ctos_npn(), tls_construct_ctos_padding(), tls_construct_ctos_psk_kex_modes(), tls_construct_ctos_renegotiate(), tls_construct_ctos_sct(), tls_construct_ctos_server_name(), tls_construct_ctos_session_ticket(), tls_construct_ctos_sig_algs(), tls_construct_ctos_srp(), tls_construct_ctos_status_request(), tls_construct_ctos_supported_versions(), tls_construct_ctos_use_srtp(), tls_construct_server_hello(), tls_construct_stoc_alpn(), tls_construct_stoc_ec_pt_formats(), tls_construct_stoc_ems(), tls_construct_stoc_etm(), tls_construct_stoc_key_share(), tls_construct_stoc_psk(), tls_construct_stoc_renegotiate(), tls_construct_stoc_server_name(), tls_construct_stoc_session_ticket(), tls_construct_stoc_status_request(), and tls_construct_stoc_use_srtp().
WPACKET_put_bytes_u24
#define WPACKET_put_bytes_u24 (pkt, val) WPACKET_put_bytes__((pkt), (val), 3)
Definition at line 825 of file packet_locl.h.
WPACKET_put_bytes_u32
#define WPACKET_put_bytes_u32 (pkt, val) WPACKET_put_bytes__((pkt), (val), 4)
Definition at line 827 of file packet_locl.h.
WPACKET_put_bytes_u8
#define WPACKET_put_bytes_u8 (pkt, val) WPACKET_put_bytes__((pkt), (val), 1)
Definition at line 821 of file packet_locl.h.
Referenced by ssl3_get_req_cert_type(), ssl3_set_handshake_header(), tls_construct_cert_status_body(), tls_construct_change_cipher_spec(), tls_construct_client_certificate(), tls_construct_ctos_psk_kex_modes(), tls_construct_ctos_server_name(), tls_construct_ctos_status_request(), tls_construct_ctos_use_srtp(), tls_construct_key_update(), tls_construct_server_certificate(), tls_construct_server_hello(), and tls_construct_stoc_use_srtp().
WPACKET_start_sub_packet_u16
#define WPACKET_start_sub_packet_u16 (pkt) WPACKET_start_sub_packet_len__((pkt), 2)
Definition at line 724 of file packet_locl.h.
Referenced by tls_construct_ctos_alpn(), tls_construct_ctos_key_share(), tls_construct_ctos_psk_kex_modes(), tls_construct_ctos_renegotiate(), tls_construct_ctos_server_name(), tls_construct_ctos_sig_algs(), tls_construct_ctos_srp(), tls_construct_ctos_status_request(), tls_construct_ctos_supported_versions(), tls_construct_ctos_use_srtp(), tls_construct_extensions(), tls_construct_stoc_alpn(), tls_construct_stoc_ec_pt_formats(), tls_construct_stoc_key_share(), tls_construct_stoc_psk(), tls_construct_stoc_renegotiate(), tls_construct_stoc_status_request(), and tls_construct_stoc_use_srtp().
WPACKET_start_sub_packet_u24
#define WPACKET_start_sub_packet_u24 (pkt) WPACKET_start_sub_packet_len__((pkt), 3)
Definition at line 726 of file packet_locl.h.
Referenced by ssl3_output_cert_chain(), and ssl3_set_handshake_header().
WPACKET_start_sub_packet_u32
#define WPACKET_start_sub_packet_u32 (pkt) WPACKET_start_sub_packet_len__((pkt), 4)
Definition at line 728 of file packet_locl.h.
WPACKET_start_sub_packet_u8
#define WPACKET_start_sub_packet_u8 (pkt) WPACKET_start_sub_packet_len__((pkt), 1)
Definition at line 722 of file packet_locl.h.
Referenced by tls_construct_ctos_psk_kex_modes(), tls_construct_ctos_srp(), tls_construct_ctos_supported_versions(), and tls_construct_stoc_renegotiate().
WPACKET_sub_allocate_bytes_u16
#define WPACKET_sub_allocate_bytes_u16 (pkt, len, bytes) WPACKET_sub_allocate_bytes__((pkt), (len), (bytes), 2)
Definition at line 763 of file packet_locl.h.
Referenced by tls_construct_ctos_padding(), and tls_construct_ctos_status_request().
WPACKET_sub_allocate_bytes_u24
#define WPACKET_sub_allocate_bytes_u24 (pkt, len, bytes) WPACKET_sub_allocate_bytes__((pkt), (len), (bytes), 3)
Definition at line 765 of file packet_locl.h.
WPACKET_sub_allocate_bytes_u32
#define WPACKET_sub_allocate_bytes_u32 (pkt, len, bytes) WPACKET_sub_allocate_bytes__((pkt), (len), (bytes), 4)
Definition at line 767 of file packet_locl.h.
WPACKET_sub_allocate_bytes_u8
#define WPACKET_sub_allocate_bytes_u8 (pkt, len, bytes) WPACKET_sub_allocate_bytes__((pkt), (len), (bytes), 1)
Definition at line 761 of file packet_locl.h.
Referenced by tls_construct_next_proto().
WPACKET_sub_memcpy_u16
#define WPACKET_sub_memcpy_u16 (pkt, src, len) WPACKET_sub_memcpy__((pkt), (src), (len), 2)
Definition at line 847 of file packet_locl.h.
Referenced by tls_construct_ctos_alpn(), tls_construct_ctos_server_name(), tls_construct_ctos_session_ticket(), and tls_construct_stoc_key_share().
WPACKET_sub_memcpy_u24
#define WPACKET_sub_memcpy_u24 (pkt, src, len) WPACKET_sub_memcpy__((pkt), (src), (len), 3)
Definition at line 849 of file packet_locl.h.
Referenced by tls_construct_cert_status_body().
WPACKET_sub_memcpy_u32
#define WPACKET_sub_memcpy_u32 (pkt, src, len) WPACKET_sub_memcpy__((pkt), (src), (len), 4)
Definition at line 851 of file packet_locl.h.
WPACKET_sub_memcpy_u8
#define WPACKET_sub_memcpy_u8 (pkt, src, len) WPACKET_sub_memcpy__((pkt), (src), (len), 1)
Definition at line 845 of file packet_locl.h.
Referenced by tls_construct_ctos_renegotiate(), tls_construct_next_proto(), tls_construct_server_hello(), tls_construct_stoc_alpn(), and tls_construct_stoc_ec_pt_formats().
WPACKET_sub_reserve_bytes_u16
#define WPACKET_sub_reserve_bytes_u16 (pkt, len, bytes) WPACKET_sub_reserve_bytes__((pkt), (len), (bytes), 2)
Definition at line 801 of file packet_locl.h.
WPACKET_sub_reserve_bytes_u24
#define WPACKET_sub_reserve_bytes_u24 (pkt, len, bytes) WPACKET_sub_reserve_bytes__((pkt), (len), (bytes), 3)
Definition at line 803 of file packet_locl.h.
WPACKET_sub_reserve_bytes_u32
#define WPACKET_sub_reserve_bytes_u32 (pkt, len, bytes) WPACKET_sub_reserve_bytes__((pkt), (len), (bytes), 4)
Definition at line 805 of file packet_locl.h.
WPACKET_sub_reserve_bytes_u8
#define WPACKET_sub_reserve_bytes_u8 (pkt, len, bytes) WPACKET_reserve_bytes__((pkt), (len), (bytes), 1)
Definition at line 799 of file packet_locl.h.
Function Documentation
WPACKET_allocate_bytes()
int WPACKET_allocate_bytes (WPACKET * pkt, size_t len, unsigned char ** allocbytes)
Definition at line 15 of file packet.c.
References len, and WPACKET_reserve_bytes().
Referenced by tls_construct_ctos_status_request(), WPACKET_memcpy(), WPACKET_put_bytes__(), WPACKET_start_sub_packet_len__(), and WPACKET_sub_allocate_bytes__().
WPACKET_cleanup()
void WPACKET_cleanup (WPACKET * pkt)
Definition at line 408 of file packet.c.
References NULL, and OPENSSL_free.
WPACKET_close()
int WPACKET_close (WPACKET * pkt)
Definition at line 243 of file packet.c.
References NULL.
Referenced by dtls1_close_construct_packet(), tls_close_construct_packet(), tls_construct_ctos_alpn(), tls_construct_ctos_psk_kex_modes(), tls_construct_ctos_renegotiate(), tls_construct_ctos_server_name(), tls_construct_ctos_sig_algs(), tls_construct_ctos_srp(), tls_construct_ctos_status_request(), tls_construct_ctos_supported_versions(), tls_construct_ctos_use_srtp(), tls_construct_extensions(), tls_construct_stoc_alpn(), tls_construct_stoc_ec_pt_formats(), tls_construct_stoc_key_share(), tls_construct_stoc_psk(), tls_construct_stoc_renegotiate(), tls_construct_stoc_status_request(), tls_construct_stoc_use_srtp(), WPACKET_sub_allocate_bytes__(), and WPACKET_sub_memcpy__().
WPACKET_fill_lengths()
int WPACKET_fill_lengths (WPACKET * pkt)
Definition at line 227 of file packet.c.
References NULL.
WPACKET_finish()
int WPACKET_finish (WPACKET * pkt)
Definition at line 255 of file packet.c.
WPACKET_get_curr()
unsigned char* WPACKET_get_curr (WPACKET * pkt)
Definition at line 403 of file packet.c.
References GETBUF.
Referenced by WPACKET_reserve_bytes().
WPACKET_get_length()
int WPACKET_get_length (WPACKET * pkt, size_t * len)
Definition at line 391 of file packet.c.
References NULL.
Referenced by dtls1_close_construct_packet(), and tls_close_construct_packet().
WPACKET_get_total_written()
int WPACKET_get_total_written (WPACKET * pkt, size_t * written)
Definition at line 379 of file packet.c.
References NULL.
Referenced by tls_construct_ctos_padding().
WPACKET_init()
int WPACKET_init (WPACKET * pkt, BUF_MEM * buf)
Definition at line 148 of file packet.c.
WPACKET_init_len()
int WPACKET_init_len (WPACKET * pkt, BUF_MEM * buf, size_t lenbytes)
Definition at line 134 of file packet.c.
WPACKET_init_static_len()
int WPACKET_init_static_len (WPACKET * pkt, unsigned char * buf, size_t len, size_t lenbytes)
Definition at line 117 of file packet.c.
WPACKET_memcpy()
int WPACKET_memcpy (WPACKET * pkt, const void * src, size_t len)
Definition at line 353 of file packet.c.
References WPACKET_allocate_bytes().
Referenced by ssl3_get_req_cert_type(), tls_construct_ctos_srp(), tls_construct_finished(), tls_construct_server_hello(), tls_construct_stoc_cryptopro_bug(), tls_construct_stoc_renegotiate(), and WPACKET_sub_memcpy__().
WPACKET_put_bytes__()
int WPACKET_put_bytes__ (WPACKET * pkt, unsigned int val, size_t bytes)
Definition at line 312 of file packet.c.
References data, and WPACKET_allocate_bytes().
WPACKET_reserve_bytes()
int WPACKET_reserve_bytes (WPACKET * pkt, size_t len, unsigned char ** allocbytes)
Definition at line 39 of file packet.c.
References BUF_MEM_grow(), DEFAULT_BUF_SIZE, if(), NULL, SIZE_MAX, and WPACKET_get_curr().
Referenced by WPACKET_allocate_bytes(), and WPACKET_sub_reserve_bytes__().
WPACKET_set_flags()
int WPACKET_set_flags (WPACKET * pkt, unsigned int flags)
Definition at line 153 of file packet.c.
References flags, and NULL.
Referenced by tls_construct_ctos_srp(), and tls_construct_extensions().
WPACKET_set_max_size()
int WPACKET_set_max_size (WPACKET * pkt, size_t maxsize)
Definition at line 327 of file packet.c.
References NULL.
Referenced by tls_construct_client_hello().
WPACKET_start_sub_packet()
int WPACKET_start_sub_packet (WPACKET * pkt)
Definition at line 307 of file packet.c.
References WPACKET_start_sub_packet_len__().
WPACKET_start_sub_packet_len__()
int WPACKET_start_sub_packet_len__ (WPACKET * pkt, size_t lenbytes)
Definition at line 275 of file packet.c.
References GETBUF, NULL, OPENSSL_zalloc, and WPACKET_allocate_bytes().
Referenced by WPACKET_start_sub_packet(), WPACKET_sub_allocate_bytes__(), and WPACKET_sub_memcpy__().
WPACKET_sub_allocate_bytes__()
int WPACKET_sub_allocate_bytes__ (WPACKET * pkt, size_t len, unsigned char ** allocbytes, size_t lenbytes)
Definition at line 25 of file packet.c.
References WPACKET_allocate_bytes(), WPACKET_close(), and WPACKET_start_sub_packet_len__().
WPACKET_sub_memcpy__()
int WPACKET_sub_memcpy__ (WPACKET * pkt, const void * src, size_t len, size_t lenbytes)
Definition at line 368 of file packet.c.
References WPACKET_close(), WPACKET_memcpy(), and WPACKET_start_sub_packet_len__().
WPACKET_sub_reserve_bytes__()
int WPACKET_sub_reserve_bytes__ (WPACKET * pkt, size_t len, unsigned char ** allocbytes, size_t lenbytes)
Definition at line 71 of file packet.c.
References WPACKET_reserve_bytes().