ssl/packet.c File Reference
packet.c File Reference
#include <assert.h>
#include "packet_locl.h"
Macros
#define DEFAULT_BUF_SIZE 256
#define GETBUF(p)
Functions
int WPACKET_allocate_bytes (WPACKET *pkt, size_t len, unsigned char **allocbytes)
int WPACKET_sub_allocate_bytes__ (WPACKET *pkt, size_t len, unsigned char **allocbytes, size_t lenbytes)
int WPACKET_reserve_bytes (WPACKET *pkt, size_t len, unsigned char **allocbytes)
int WPACKET_sub_reserve_bytes__ (WPACKET *pkt, size_t len, unsigned char **allocbytes, size_t lenbytes)
int WPACKET_init_static_len (WPACKET *pkt, unsigned char *buf, size_t len, size_t lenbytes)
int WPACKET_init_len (WPACKET *pkt, BUF_MEM *buf, size_t lenbytes)
int WPACKET_init (WPACKET *pkt, BUF_MEM *buf)
int WPACKET_set_flags (WPACKET *pkt, unsigned int flags)
int WPACKET_fill_lengths (WPACKET *pkt)
int WPACKET_close (WPACKET *pkt)
int WPACKET_finish (WPACKET *pkt)
int WPACKET_start_sub_packet_len__ (WPACKET *pkt, size_t lenbytes)
int WPACKET_start_sub_packet (WPACKET *pkt)
int WPACKET_put_bytes__ (WPACKET *pkt, unsigned int val, size_t size)
int WPACKET_set_max_size (WPACKET *pkt, size_t maxsize)
int WPACKET_memcpy (WPACKET *pkt, const void *src, size_t len)
int WPACKET_sub_memcpy__ (WPACKET *pkt, const void *src, size_t len, size_t lenbytes)
int WPACKET_get_total_written (WPACKET *pkt, size_t *written)
int WPACKET_get_length (WPACKET *pkt, size_t *len)
unsigned char * WPACKET_get_curr (WPACKET *pkt)
void WPACKET_cleanup (WPACKET *pkt)
Macro Definition Documentation
DEFAULT_BUF_SIZE
#define DEFAULT_BUF_SIZE 256
Definition at line 13 of file packet.c.
Referenced by WPACKET_reserve_bytes().
GETBUF
#define GETBUF (p)
Value:
(((p)->staticbuf != NULL) \
                     ? (p)->staticbuf : (unsigned char *)(p)->buf->data)
Definition at line 36 of file packet.c.
Referenced by WPACKET_get_curr(), and WPACKET_start_sub_packet_len__().
Function Documentation
WPACKET_allocate_bytes()
int WPACKET_allocate_bytes (WPACKET * pkt, size_t len, unsigned char ** allocbytes)
Definition at line 15 of file packet.c.
References len, and WPACKET_reserve_bytes().
Referenced by tls_construct_ctos_status_request(), WPACKET_memcpy(), WPACKET_put_bytes__(), WPACKET_start_sub_packet_len__(), and WPACKET_sub_allocate_bytes__().
WPACKET_cleanup()
void WPACKET_cleanup (WPACKET * pkt)
Definition at line 408 of file packet.c.
References NULL, and OPENSSL_free.
WPACKET_close()
int WPACKET_close (WPACKET * pkt)
Definition at line 243 of file packet.c.
References NULL.
Referenced by dtls1_close_construct_packet(), tls_close_construct_packet(), tls_construct_ctos_alpn(), tls_construct_ctos_psk_kex_modes(), tls_construct_ctos_renegotiate(), tls_construct_ctos_server_name(), tls_construct_ctos_sig_algs(), tls_construct_ctos_srp(), tls_construct_ctos_status_request(), tls_construct_ctos_supported_versions(), tls_construct_ctos_use_srtp(), tls_construct_extensions(), tls_construct_stoc_alpn(), tls_construct_stoc_ec_pt_formats(), tls_construct_stoc_key_share(), tls_construct_stoc_psk(), tls_construct_stoc_renegotiate(), tls_construct_stoc_status_request(), tls_construct_stoc_use_srtp(), WPACKET_sub_allocate_bytes__(), and WPACKET_sub_memcpy__().
WPACKET_fill_lengths()
int WPACKET_fill_lengths (WPACKET * pkt)
Definition at line 227 of file packet.c.
References NULL.
WPACKET_finish()
int WPACKET_finish (WPACKET * pkt)
Definition at line 255 of file packet.c.
WPACKET_get_curr()
unsigned char* WPACKET_get_curr (WPACKET * pkt)
Definition at line 403 of file packet.c.
References GETBUF.
Referenced by WPACKET_reserve_bytes().
WPACKET_get_length()
int WPACKET_get_length (WPACKET * pkt, size_t * len)
Definition at line 391 of file packet.c.
References NULL.
Referenced by dtls1_close_construct_packet(), and tls_close_construct_packet().
WPACKET_get_total_written()
int WPACKET_get_total_written (WPACKET * pkt, size_t * written)
Definition at line 379 of file packet.c.
References NULL.
Referenced by tls_construct_ctos_padding().
WPACKET_init()
int WPACKET_init (WPACKET * pkt, BUF_MEM * buf)
Definition at line 148 of file packet.c.
WPACKET_init_len()
int WPACKET_init_len (WPACKET * pkt, BUF_MEM * buf, size_t lenbytes)
Definition at line 134 of file packet.c.
WPACKET_init_static_len()
int WPACKET_init_static_len (WPACKET * pkt, unsigned char * buf, size_t len, size_t lenbytes)
Definition at line 117 of file packet.c.
WPACKET_memcpy()
int WPACKET_memcpy (WPACKET * pkt, const void * src, size_t len)
Definition at line 353 of file packet.c.
References WPACKET_allocate_bytes().
Referenced by ssl3_get_req_cert_type(), tls_construct_ctos_srp(), tls_construct_finished(), tls_construct_server_hello(), tls_construct_stoc_cryptopro_bug(), tls_construct_stoc_renegotiate(), and WPACKET_sub_memcpy__().
WPACKET_put_bytes__()
int WPACKET_put_bytes__ (WPACKET * pkt, unsigned int val, size_t size)
Definition at line 312 of file packet.c.
References data, and WPACKET_allocate_bytes().
WPACKET_reserve_bytes()
int WPACKET_reserve_bytes (WPACKET * pkt, size_t len, unsigned char ** allocbytes)
Definition at line 39 of file packet.c.
References BUF_MEM_grow(), DEFAULT_BUF_SIZE, if(), NULL, SIZE_MAX, and WPACKET_get_curr().
Referenced by WPACKET_allocate_bytes(), and WPACKET_sub_reserve_bytes__().
WPACKET_set_flags()
int WPACKET_set_flags (WPACKET * pkt, unsigned int flags)
Definition at line 153 of file packet.c.
References flags, and NULL.
Referenced by tls_construct_ctos_srp(), and tls_construct_extensions().
WPACKET_set_max_size()
int WPACKET_set_max_size (WPACKET * pkt, size_t maxsize)
Definition at line 327 of file packet.c.
References NULL.
Referenced by tls_construct_client_hello().
WPACKET_start_sub_packet()
int WPACKET_start_sub_packet (WPACKET * pkt)
Definition at line 307 of file packet.c.
References WPACKET_start_sub_packet_len__().
WPACKET_start_sub_packet_len__()
int WPACKET_start_sub_packet_len__ (WPACKET * pkt, size_t lenbytes)
Definition at line 275 of file packet.c.
References GETBUF, NULL, OPENSSL_zalloc, and WPACKET_allocate_bytes().
Referenced by WPACKET_start_sub_packet(), WPACKET_sub_allocate_bytes__(), and WPACKET_sub_memcpy__().
WPACKET_sub_allocate_bytes__()
int WPACKET_sub_allocate_bytes__ (WPACKET * pkt, size_t len, unsigned char ** allocbytes, size_t lenbytes)
Definition at line 25 of file packet.c.
References WPACKET_allocate_bytes(), WPACKET_close(), and WPACKET_start_sub_packet_len__().
WPACKET_sub_memcpy__()
int WPACKET_sub_memcpy__ (WPACKET * pkt, const void * src, size_t len, size_t lenbytes)
Definition at line 368 of file packet.c.
References WPACKET_close(), WPACKET_memcpy(), and WPACKET_start_sub_packet_len__().
WPACKET_sub_reserve_bytes__()
int WPACKET_sub_reserve_bytes__ (WPACKET * pkt, size_t len, unsigned char ** allocbytes, size_t lenbytes)
Definition at line 71 of file packet.c.
References WPACKET_reserve_bytes().