crypto/x509v3/pcy_node.c File Reference
pcy_node.c File Reference
#include <openssl/asn1.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include "pcy_int.h"
Functions
STACK_OF (X509_POLICY_NODE)
X509_POLICY_NODE * tree_find_sk (STACK_OF(X509_POLICY_NODE) *nodes, const ASN1_OBJECT *id)
X509_POLICY_NODE * level_find_node (const X509_POLICY_LEVEL *level, const X509_POLICY_NODE *parent, const ASN1_OBJECT *id)
X509_POLICY_NODE * level_add_node (X509_POLICY_LEVEL *level, X509_POLICY_DATA *data, X509_POLICY_NODE *parent, X509_POLICY_TREE *tree)
void policy_node_free (X509_POLICY_NODE *node)
int policy_node_match (const X509_POLICY_LEVEL *lvl, const X509_POLICY_NODE *node, const ASN1_OBJECT *oid)
Function Documentation
level_add_node()
X509_POLICY_NODE* level_add_node (X509_POLICY_LEVEL * level, X509_POLICY_DATA * data, X509_POLICY_NODE * parent, X509_POLICY_TREE * tree)
Definition at line 61 of file pcy_node.c.
References data, NID_any_policy, NULL, OBJ_obj2nid(), OPENSSL_zalloc, and policy_node_free().
level_find_node()
X509_POLICY_NODE* level_find_node (const X509_POLICY_LEVEL * level, const X509_POLICY_NODE * parent, const ASN1_OBJECT * id)
Definition at line 45 of file pcy_node.c.
References NULL, and OBJ_cmp().
policy_node_free()
void policy_node_free (X509_POLICY_NODE * node)
Definition at line 108 of file pcy_node.c.
References OPENSSL_free.
Referenced by level_add_node().
policy_node_match()
int policy_node_match (const X509_POLICY_LEVEL * lvl, const X509_POLICY_NODE * node, const ASN1_OBJECT * oid)
Definition at line 118 of file pcy_node.c.
References OBJ_cmp(), POLICY_DATA_FLAG_MAP_MASK, and X509_V_FLAG_INHIBIT_MAP.
STACK_OF()
STACK_OF (X509_POLICY_NODE)
Definition at line 22 of file pcy_node.c.
tree_find_sk()
X509_POLICY_NODE* tree_find_sk (STACK_OF(X509_POLICY_NODE) * nodes, const ASN1_OBJECT * id)
Definition at line 27 of file pcy_node.c.