crypto/x509v3/pcy_int.h File Reference
pcy_int.h File Reference
Data Structures
struct X509_POLICY_DATA
struct X509_POLICY_CACHE
struct X509_POLICY_NODE
struct X509_POLICY_LEVEL
struct X509_POLICY_TREE
Macros
#define POLICY_DATA_FLAG_MAPPED 0x1
#define POLICY_DATA_FLAG_MAPPED_ANY 0x2
#define POLICY_DATA_FLAG_MAP_MASK 0x3
#define POLICY_DATA_FLAG_SHARED_QUALIFIERS 0x4
#define POLICY_DATA_FLAG_EXTRA_NODE 0x8
#define POLICY_DATA_FLAG_CRITICAL 0x10
#define POLICY_FLAG_ANY_POLICY 0x2
#define node_data_critical(data) (data->flags & POLICY_DATA_FLAG_CRITICAL)
#define node_critical(node) node_data_critical(node->data)
Functions
X509_POLICY_DATA * policy_data_new (POLICYINFO *policy, const ASN1_OBJECT *id, int crit)
void policy_data_free (X509_POLICY_DATA *data)
X509_POLICY_DATA * policy_cache_find_data (const X509_POLICY_CACHE *cache, const ASN1_OBJECT *id)
int policy_cache_set_mapping (X509 *x, POLICY_MAPPINGS *maps)
STACK_OF (X509_POLICY_NODE) *policy_node_cmp_new(void)
void policy_cache_init (void)
void policy_cache_free (X509_POLICY_CACHE *cache)
X509_POLICY_NODE * level_find_node (const X509_POLICY_LEVEL *level, const X509_POLICY_NODE *parent, const ASN1_OBJECT *id)
X509_POLICY_NODE * tree_find_sk (STACK_OF(X509_POLICY_NODE) *sk, const ASN1_OBJECT *id)
X509_POLICY_NODE * level_add_node (X509_POLICY_LEVEL *level, X509_POLICY_DATA *data, X509_POLICY_NODE *parent, X509_POLICY_TREE *tree)
void policy_node_free (X509_POLICY_NODE *node)
int policy_node_match (const X509_POLICY_LEVEL *lvl, const X509_POLICY_NODE *node, const ASN1_OBJECT *oid)
const X509_POLICY_CACHE * policy_cache_set (X509 *x)
Macro Definition Documentation
node_critical
#define node_critical (node) node_data_critical(node->data)
Definition at line 134 of file pcy_int.h.
node_data_critical
#define node_data_critical (data) (data->flags & POLICY_DATA_FLAG_CRITICAL)
Definition at line 133 of file pcy_int.h.
POLICY_DATA_FLAG_CRITICAL
#define POLICY_DATA_FLAG_CRITICAL 0x10
Definition at line 61 of file pcy_int.h.
POLICY_DATA_FLAG_EXTRA_NODE
#define POLICY_DATA_FLAG_EXTRA_NODE 0x8
Definition at line 57 of file pcy_int.h.
POLICY_DATA_FLAG_MAP_MASK
#define POLICY_DATA_FLAG_MAP_MASK 0x3
Definition at line 49 of file pcy_int.h.
Referenced by policy_node_match().
POLICY_DATA_FLAG_MAPPED
#define POLICY_DATA_FLAG_MAPPED 0x1
Definition at line 38 of file pcy_int.h.
POLICY_DATA_FLAG_MAPPED_ANY
#define POLICY_DATA_FLAG_MAPPED_ANY 0x2
Definition at line 45 of file pcy_int.h.
POLICY_DATA_FLAG_SHARED_QUALIFIERS
#define POLICY_DATA_FLAG_SHARED_QUALIFIERS 0x4
Definition at line 53 of file pcy_int.h.
Referenced by policy_data_free().
POLICY_FLAG_ANY_POLICY
#define POLICY_FLAG_ANY_POLICY 0x2
Definition at line 129 of file pcy_int.h.
Referenced by STACK_OF().
Function Documentation
level_add_node()
X509_POLICY_NODE* level_add_node (X509_POLICY_LEVEL * level, X509_POLICY_DATA * data, X509_POLICY_NODE * parent, X509_POLICY_TREE * tree)
Definition at line 61 of file pcy_node.c.
References data, NID_any_policy, NULL, OBJ_obj2nid(), OPENSSL_zalloc, and policy_node_free().
level_find_node()
X509_POLICY_NODE* level_find_node (const X509_POLICY_LEVEL * level, const X509_POLICY_NODE * parent, const ASN1_OBJECT * id)
Definition at line 45 of file pcy_node.c.
References NULL, and OBJ_cmp().
policy_cache_find_data()
X509_POLICY_DATA* policy_cache_find_data (const X509_POLICY_CACHE * cache, const ASN1_OBJECT * id)
Definition at line 190 of file pcy_cache.c.
policy_cache_free()
void policy_cache_free (X509_POLICY_CACHE * cache)
Definition at line 168 of file pcy_cache.c.
References OPENSSL_free, and policy_data_free().
policy_cache_init()
void policy_cache_init (void)
policy_cache_set()
const X509_POLICY_CACHE* policy_cache_set (X509 * x)
Definition at line 177 of file pcy_cache.c.
References CRYPTO_THREAD_write_lock(), and NULL.
policy_cache_set_mapping()
int policy_cache_set_mapping (X509 * x, POLICY_MAPPINGS * maps)
Definition at line 22 of file pcy_map.c.
References data.
policy_data_free()
void policy_data_free (X509_POLICY_DATA * data)
Definition at line 18 of file pcy_data.c.
References ASN1_OBJECT_free(), OPENSSL_free, and POLICY_DATA_FLAG_SHARED_QUALIFIERS.
Referenced by policy_cache_free().
policy_data_new()
X509_POLICY_DATA* policy_data_new (POLICYINFO * policy, const ASN1_OBJECT * id, int crit)
Definition at line 38 of file pcy_data.c.
policy_node_free()
void policy_node_free (X509_POLICY_NODE * node)
Definition at line 108 of file pcy_node.c.
References OPENSSL_free.
Referenced by level_add_node().
policy_node_match()
int policy_node_match (const X509_POLICY_LEVEL * lvl, const X509_POLICY_NODE * node, const ASN1_OBJECT * oid)
Definition at line 118 of file pcy_node.c.
References OBJ_cmp(), POLICY_DATA_FLAG_MAP_MASK, and X509_V_FLAG_INHIBIT_MAP.
STACK_OF()
STACK_OF (X509_POLICY_NODE)
Definition at line 35 of file pcy_lib.c.
References NULL, and POLICY_FLAG_ANY_POLICY.
tree_find_sk()
X509_POLICY_NODE* tree_find_sk (STACK_OF(X509_POLICY_NODE) * sk, const ASN1_OBJECT * id)
Definition at line 27 of file pcy_node.c.