include/openssl/pem2.h File Reference
pem2.h File Reference
Functions
int ERR_load_PEM_strings (void)
Function Documentation
ERR_load_PEM_strings()
int ERR_load_PEM_strings (void)
Definition at line 105 of file pem_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().