crypto/pem/pem_pkey.c File Reference
pem_pkey.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/buffer.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include <openssl/pkcs12.h>
#include <openssl/pem.h>
#include <openssl/engine.h>
#include <openssl/dh.h>
#include "internal/asn1_int.h"
#include "internal/evp_int.h"
Functions
int pem_check_suffix (const char *pem_str, const char *suffix)
EVP_PKEY * PEM_read_bio_PrivateKey (BIO *bp, EVP_PKEY **x, pem_password_cb *cb, void *u)
int PEM_write_bio_PrivateKey (BIO *bp, EVP_PKEY *x, const EVP_CIPHER *enc, unsigned char *kstr, int klen, pem_password_cb *cb, void *u)
int PEM_write_bio_PrivateKey_traditional (BIO *bp, EVP_PKEY *x, const EVP_CIPHER *enc, unsigned char *kstr, int klen, pem_password_cb *cb, void *u)
EVP_PKEY * PEM_read_bio_Parameters (BIO *bp, EVP_PKEY **x)
int PEM_write_bio_Parameters (BIO *bp, EVP_PKEY *x)
EVP_PKEY * PEM_read_PrivateKey (FILE *fp, EVP_PKEY **x, pem_password_cb *cb, void *u)
int PEM_write_PrivateKey (FILE *fp, EVP_PKEY *x, const EVP_CIPHER *enc, unsigned char *kstr, int klen, pem_password_cb *cb, void *u)
DH * PEM_read_bio_DHparams (BIO *bp, DH **x, pem_password_cb *cb, void *u)
DH * PEM_read_DHparams (FILE *fp, DH **x, pem_password_cb *cb, void *u)
Function Documentation
pem_check_suffix()
int pem_check_suffix (const char * pem_str, const char * suffix)
Definition at line 843 of file pem_lib.c.
PEM_read_bio_DHparams()
DH* PEM_read_bio_DHparams (BIO * bp, DH ** x, pem_password_cb * cb, void * u)
Definition at line 202 of file pem_pkey.c.
References data, len, and NULL.
PEM_read_bio_Parameters()
EVP_PKEY* PEM_read_bio_Parameters (BIO * bp, EVP_PKEY ** x)
Definition at line 114 of file pem_pkey.c.
References data, len, and NULL.
PEM_read_bio_PrivateKey()
EVP_PKEY* PEM_read_bio_PrivateKey (BIO * bp, EVP_PKEY ** x, pem_password_cb * cb, void * u)
Definition at line 25 of file pem_pkey.c.
References data, len, and NULL.
Referenced by PEM_read_bio_DSAPrivateKey(), PEM_read_bio_ECPrivateKey(), PEM_read_bio_RSAPrivateKey(), and TS_CONF_load_key().
PEM_read_DHparams()
DH* PEM_read_DHparams (FILE * fp, DH ** x, pem_password_cb * cb, void * u)
Definition at line 227 of file pem_pkey.c.
PEM_read_PrivateKey()
EVP_PKEY* PEM_read_PrivateKey (FILE * fp, EVP_PKEY ** x, pem_password_cb * cb, void * u)
Definition at line 164 of file pem_pkey.c.
Referenced by IMPLEMENT_PEM_rw_const(), IMPLEMENT_PEM_write_cb_const(), and PEM_read_RSAPrivateKey().
PEM_write_bio_Parameters()
int PEM_write_bio_Parameters (BIO * bp, EVP_PKEY * x)
Definition at line 152 of file pem_pkey.c.
References BIO_snprintf(), NULL, and PEM_ASN1_write_bio().
PEM_write_bio_PrivateKey()
int PEM_write_bio_PrivateKey (BIO * bp, EVP_PKEY * x, const EVP_CIPHER * enc, unsigned char * kstr, int klen, pem_password_cb * cb, void * u)
Definition at line 93 of file pem_pkey.c.
References NULL, PEM_write_bio_PKCS8PrivateKey(), and PEM_write_bio_PrivateKey_traditional().
PEM_write_bio_PrivateKey_traditional()
int PEM_write_bio_PrivateKey_traditional (BIO * bp, EVP_PKEY * x, const EVP_CIPHER * enc, unsigned char * kstr, int klen, pem_password_cb * cb, void * u)
Definition at line 103 of file pem_pkey.c.
References BIO_snprintf(), i2d_PrivateKey(), and PEM_ASN1_write_bio().
Referenced by PEM_write_bio_PrivateKey().
PEM_write_PrivateKey()
int PEM_write_PrivateKey (FILE * fp, EVP_PKEY * x, const EVP_CIPHER * enc, unsigned char * kstr, int klen, pem_password_cb * cb, void * u)
Definition at line 180 of file pem_pkey.c.