include/openssl/pem.h File Reference
pem.h File Reference
#include <openssl/e_os2.h>
#include <openssl/bio.h>
#include <openssl/stack.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include <openssl/pem2.h>
#include <openssl/symhacks.h>
Data Structures
struct PEM_USER
struct PEM_CTX
Macros
#define PEM_BUFSIZE 1024
#define PEM_STRING_X509_OLD "X509 CERTIFICATE"
#define PEM_STRING_X509 "CERTIFICATE"
#define PEM_STRING_X509_TRUSTED "TRUSTED CERTIFICATE"
#define PEM_STRING_X509_REQ_OLD "NEW CERTIFICATE REQUEST"
#define PEM_STRING_X509_REQ "CERTIFICATE REQUEST"
#define PEM_STRING_X509_CRL "X509 CRL"
#define PEM_STRING_EVP_PKEY "ANY PRIVATE KEY"
#define PEM_STRING_PUBLIC "PUBLIC KEY"
#define PEM_STRING_RSA "RSA PRIVATE KEY"
#define PEM_STRING_RSA_PUBLIC "RSA PUBLIC KEY"
#define PEM_STRING_DSA "DSA PRIVATE KEY"
#define PEM_STRING_DSA_PUBLIC "DSA PUBLIC KEY"
#define PEM_STRING_PKCS7 "PKCS7"
#define PEM_STRING_PKCS7_SIGNED "PKCS #7 SIGNED DATA"
#define PEM_STRING_PKCS8 "ENCRYPTED PRIVATE KEY"
#define PEM_STRING_PKCS8INF "PRIVATE KEY"
#define PEM_STRING_DHPARAMS "DH PARAMETERS"
#define PEM_STRING_DHXPARAMS "X9.42 DH PARAMETERS"
#define PEM_STRING_SSL_SESSION "SSL SESSION PARAMETERS"
#define PEM_STRING_DSAPARAMS "DSA PARAMETERS"
#define PEM_STRING_ECDSA_PUBLIC "ECDSA PUBLIC KEY"
#define PEM_STRING_ECPARAMETERS "EC PARAMETERS"
#define PEM_STRING_ECPRIVATEKEY "EC PRIVATE KEY"
#define PEM_STRING_PARAMETERS "PARAMETERS"
#define PEM_STRING_CMS "CMS"
#define PEM_TYPE_ENCRYPTED 10
#define PEM_TYPE_MIC_ONLY 20
#define PEM_TYPE_MIC_CLEAR 30
#define PEM_TYPE_CLEAR 40
#define IMPLEMENT_PEM_read_fp(name, type, str, asn1)
#define IMPLEMENT_PEM_write_fp(name, type, str, asn1)
#define IMPLEMENT_PEM_write_fp_const(name, type, str, asn1)
#define IMPLEMENT_PEM_write_cb_fp(name, type, str, asn1)
#define IMPLEMENT_PEM_write_cb_fp_const(name, type, str, asn1)
#define IMPLEMENT_PEM_read_bio(name, type, str, asn1)
#define IMPLEMENT_PEM_write_bio(name, type, str, asn1)
#define IMPLEMENT_PEM_write_bio_const(name, type, str, asn1)
#define IMPLEMENT_PEM_write_cb_bio(name, type, str, asn1)
#define IMPLEMENT_PEM_write_cb_bio_const(name, type, str, asn1)
#define IMPLEMENT_PEM_write(name, type, str, asn1)
#define IMPLEMENT_PEM_write_const(name, type, str, asn1)
#define IMPLEMENT_PEM_write_cb(name, type, str, asn1)
#define IMPLEMENT_PEM_write_cb_const(name, type, str, asn1)
#define IMPLEMENT_PEM_read(name, type, str, asn1)
#define IMPLEMENT_PEM_rw(name, type, str, asn1)
#define IMPLEMENT_PEM_rw_const(name, type, str, asn1)
#define IMPLEMENT_PEM_rw_cb(name, type, str, asn1)
#define DECLARE_PEM_read_fp(name, type) type *PEM_read_##name(FILE *fp, type **x, pem_password_cb *cb, void *u);
#define DECLARE_PEM_write_fp(name, type) int PEM_write_##name(FILE *fp, type *x);
#define DECLARE_PEM_write_fp_const(name, type) int PEM_write_##name(FILE *fp, const type *x);
#define DECLARE_PEM_write_cb_fp(name, type)
#define DECLARE_PEM_read_bio(name, type) type *PEM_read_bio_##name(BIO *bp, type **x, pem_password_cb *cb, void *u);
#define DECLARE_PEM_write_bio(name, type) int PEM_write_bio_##name(BIO *bp, type *x);
#define DECLARE_PEM_write_bio_const(name, type) int PEM_write_bio_##name(BIO *bp, const type *x);
#define DECLARE_PEM_write_cb_bio(name, type)
#define DECLARE_PEM_write(name, type)
#define DECLARE_PEM_write_const(name, type)
#define DECLARE_PEM_write_cb(name, type)
#define DECLARE_PEM_read(name, type)
#define DECLARE_PEM_rw(name, type)
#define DECLARE_PEM_rw_const(name, type)
#define DECLARE_PEM_rw_cb(name, type)
#define PEM_F_B2I_DSS 127
#define PEM_F_B2I_PVK_BIO 128
#define PEM_F_B2I_RSA 129
#define PEM_F_CHECK_BITLEN_DSA 130
#define PEM_F_CHECK_BITLEN_RSA 131
#define PEM_F_D2I_PKCS8PRIVATEKEY_BIO 120
#define PEM_F_D2I_PKCS8PRIVATEKEY_FP 121
#define PEM_F_DO_B2I 132
#define PEM_F_DO_B2I_BIO 133
#define PEM_F_DO_BLOB_HEADER 134
#define PEM_F_DO_PK8PKEY 126
#define PEM_F_DO_PK8PKEY_FP 125
#define PEM_F_DO_PVK_BODY 135
#define PEM_F_DO_PVK_HEADER 136
#define PEM_F_I2B_PVK 137
#define PEM_F_I2B_PVK_BIO 138
#define PEM_F_LOAD_IV 101
#define PEM_F_PEM_ASN1_READ 102
#define PEM_F_PEM_ASN1_READ_BIO 103
#define PEM_F_PEM_ASN1_WRITE 104
#define PEM_F_PEM_ASN1_WRITE_BIO 105
#define PEM_F_PEM_DEF_CALLBACK 100
#define PEM_F_PEM_DO_HEADER 106
#define PEM_F_PEM_GET_EVP_CIPHER_INFO 107
#define PEM_F_PEM_READ 108
#define PEM_F_PEM_READ_BIO 109
#define PEM_F_PEM_READ_BIO_DHPARAMS 141
#define PEM_F_PEM_READ_BIO_PARAMETERS 140
#define PEM_F_PEM_READ_BIO_PRIVATEKEY 123
#define PEM_F_PEM_READ_DHPARAMS 142
#define PEM_F_PEM_READ_PRIVATEKEY 124
#define PEM_F_PEM_SIGNFINAL 112
#define PEM_F_PEM_WRITE 113
#define PEM_F_PEM_WRITE_BIO 114
#define PEM_F_PEM_WRITE_PRIVATEKEY 139
#define PEM_F_PEM_X509_INFO_READ 115
#define PEM_F_PEM_X509_INFO_READ_BIO 116
#define PEM_F_PEM_X509_INFO_WRITE_BIO 117
#define PEM_R_BAD_BASE64_DECODE 100
#define PEM_R_BAD_DECRYPT 101
#define PEM_R_BAD_END_LINE 102
#define PEM_R_BAD_IV_CHARS 103
#define PEM_R_BAD_MAGIC_NUMBER 116
#define PEM_R_BAD_PASSWORD_READ 104
#define PEM_R_BAD_VERSION_NUMBER 117
#define PEM_R_BIO_WRITE_FAILURE 118
#define PEM_R_CIPHER_IS_NULL 127
#define PEM_R_ERROR_CONVERTING_PRIVATE_KEY 115
#define PEM_R_EXPECTING_PRIVATE_KEY_BLOB 119
#define PEM_R_EXPECTING_PUBLIC_KEY_BLOB 120
#define PEM_R_HEADER_TOO_LONG 128
#define PEM_R_INCONSISTENT_HEADER 121
#define PEM_R_KEYBLOB_HEADER_PARSE_ERROR 122
#define PEM_R_KEYBLOB_TOO_SHORT 123
#define PEM_R_MISSING_DEK_IV 129
#define PEM_R_NOT_DEK_INFO 105
#define PEM_R_NOT_ENCRYPTED 106
#define PEM_R_NOT_PROC_TYPE 107
#define PEM_R_NO_START_LINE 108
#define PEM_R_PROBLEMS_GETTING_PASSWORD 109
#define PEM_R_PVK_DATA_TOO_SHORT 124
#define PEM_R_PVK_TOO_SHORT 125
#define PEM_R_READ_KEY 111
#define PEM_R_SHORT_HEADER 112
#define PEM_R_UNEXPECTED_DEK_IV 130
#define PEM_R_UNSUPPORTED_CIPHER 113
#define PEM_R_UNSUPPORTED_ENCRYPTION 114
#define PEM_R_UNSUPPORTED_KEY_COMPONENTS 126
Typedefs
typedef int pem_password_cb(char *buf, int size, int rwflag, void *userdata)
Functions
int PEM_get_EVP_CIPHER_INFO (char *header, EVP_CIPHER_INFO *cipher)
int PEM_do_header (EVP_CIPHER_INFO *cipher, unsigned char *data, long *len, pem_password_cb *callback, void *u)
int PEM_read_bio (BIO *bp, char **name, char **header, unsigned char **data, long *len)
int PEM_write_bio (BIO *bp, const char *name, const char *hdr, const unsigned char *data, long len)
int PEM_bytes_read_bio (unsigned char **pdata, long *plen, char **pnm, const char *name, BIO *bp, pem_password_cb *cb, void *u)
void * PEM_ASN1_read_bio (d2i_of_void *d2i, const char *name, BIO *bp, void **x, pem_password_cb *cb, void *u)
int PEM_ASN1_write_bio (i2d_of_void *i2d, const char *name, BIO *bp, void *x, const EVP_CIPHER *enc, unsigned char *kstr, int klen, pem_password_cb *cb, void *u)
STACK_OF (X509_INFO) *PEM_X509_INFO_read_bio(BIO *bp
int PEM_X509_INFO_write_bio (BIO *bp, X509_INFO *xi, EVP_CIPHER *enc, unsigned char *kstr, int klen, pem_password_cb *cd, void *u)
int PEM_read (FILE *fp, char **name, char **header, unsigned char **data, long *len)
int PEM_write (FILE *fp, const char *name, const char *hdr, const unsigned char *data, long len)
void * PEM_ASN1_read (d2i_of_void *d2i, const char *name, FILE *fp, void **x, pem_password_cb *cb, void *u)
int PEM_ASN1_write (i2d_of_void *i2d, const char *name, FILE *fp, void *x, const EVP_CIPHER *enc, unsigned char *kstr, int klen, pem_password_cb *callback, void *u)
int PEM_SignInit (EVP_MD_CTX *ctx, EVP_MD *type)
int PEM_SignUpdate (EVP_MD_CTX *ctx, unsigned char *d, unsigned int cnt)
int PEM_SignFinal (EVP_MD_CTX *ctx, unsigned char *sigret, unsigned int *siglen, EVP_PKEY *pkey)
int PEM_def_callback (char *buf, int num, int w, void *key)
void PEM_proc_type (char *buf, int type)
void PEM_dek_info (char *buf, const char *type, int len, char *str)
DECLARE_PEM_rw (X509, X509) DECLARE_PEM_rw(X509_AUX
X509 DECLARE_PEM_rw (X509_REQ, X509_REQ) DECLARE_PEM_write(X509_REQ_NEW
X509 X509_REQ DECLARE_PEM_rw (X509_CRL, X509_CRL) DECLARE_PEM_rw(PKCS7
X509 X509_REQ PKCS7 DECLARE_PEM_rw (NETSCAPE_CERT_SEQUENCE, NETSCAPE_CERT_SEQUENCE) DECLARE_PEM_rw(PKCS8
X509 X509_REQ PKCS7 X509_SIG DECLARE_PEM_rw (PKCS8_PRIV_KEY_INFO, PKCS8_PRIV_KEY_INFO) DECLARE_PEM_rw_cb(RSAPrivateKey
X509 X509_REQ PKCS7 X509_SIG RSA DECLARE_PEM_rw_const (RSAPublicKey, RSA) DECLARE_PEM_rw(RSA_PUBKEY
X509 X509_REQ PKCS7 X509_SIG RSA RSA DECLARE_PEM_rw_cb (DSAPrivateKey, DSA) DECLARE_PEM_rw(DSA_PUBKEY
X509 X509_REQ PKCS7 X509_SIG RSA RSA DSA DECLARE_PEM_rw_const (DSAparams, DSA) DECLARE_PEM_rw_const(ECPKParameters
X509 X509_REQ PKCS7 X509_SIG RSA RSA DSA EC_GROUP DECLARE_PEM_rw_cb (ECPrivateKey, EC_KEY) DECLARE_PEM_rw(EC_PUBKEY
X509 X509_REQ PKCS7 X509_SIG RSA RSA DSA EC_GROUP EC_KEY DECLARE_PEM_rw_const (DHparams, DH) DECLARE_PEM_write_const(DHxparams
X509 X509_REQ PKCS7 X509_SIG RSA RSA DSA EC_GROUP EC_KEY DH DECLARE_PEM_rw_cb (PrivateKey, EVP_PKEY) DECLARE_PEM_rw(PUBKEY
X509 X509_REQ PKCS7 X509_SIG RSA RSA DSA EC_GROUP EC_KEY DH EVP_PKEY int PEM_write_bio_PrivateKey_traditional (BIO *bp, EVP_PKEY *x, const EVP_CIPHER *enc, unsigned char *kstr, int klen, pem_password_cb *cb, void *u)
int PEM_write_bio_PKCS8PrivateKey_nid (BIO *bp, EVP_PKEY *x, int nid, char *kstr, int klen, pem_password_cb *cb, void *u)
int PEM_write_bio_PKCS8PrivateKey (BIO *, EVP_PKEY *, const EVP_CIPHER *, char *, int, pem_password_cb *, void *)
int i2d_PKCS8PrivateKey_bio (BIO *bp, EVP_PKEY *x, const EVP_CIPHER *enc, char *kstr, int klen, pem_password_cb *cb, void *u)
int i2d_PKCS8PrivateKey_nid_bio (BIO *bp, EVP_PKEY *x, int nid, char *kstr, int klen, pem_password_cb *cb, void *u)
EVP_PKEY * d2i_PKCS8PrivateKey_bio (BIO *bp, EVP_PKEY **x, pem_password_cb *cb, void *u)
int i2d_PKCS8PrivateKey_fp (FILE *fp, EVP_PKEY *x, const EVP_CIPHER *enc, char *kstr, int klen, pem_password_cb *cb, void *u)
int i2d_PKCS8PrivateKey_nid_fp (FILE *fp, EVP_PKEY *x, int nid, char *kstr, int klen, pem_password_cb *cb, void *u)
int PEM_write_PKCS8PrivateKey_nid (FILE *fp, EVP_PKEY *x, int nid, char *kstr, int klen, pem_password_cb *cb, void *u)
EVP_PKEY * d2i_PKCS8PrivateKey_fp (FILE *fp, EVP_PKEY **x, pem_password_cb *cb, void *u)
int PEM_write_PKCS8PrivateKey (FILE *fp, EVP_PKEY *x, const EVP_CIPHER *enc, char *kstr, int klen, pem_password_cb *cd, void *u)
EVP_PKEY * PEM_read_bio_Parameters (BIO *bp, EVP_PKEY **x)
int PEM_write_bio_Parameters (BIO *bp, EVP_PKEY *x)
EVP_PKEY * b2i_PrivateKey (const unsigned char **in, long length)
EVP_PKEY * b2i_PublicKey (const unsigned char **in, long length)
EVP_PKEY * b2i_PrivateKey_bio (BIO *in)
EVP_PKEY * b2i_PublicKey_bio (BIO *in)
int i2b_PrivateKey_bio (BIO *out, EVP_PKEY *pk)
int i2b_PublicKey_bio (BIO *out, EVP_PKEY *pk)
EVP_PKEY * b2i_PVK_bio (BIO *in, pem_password_cb *cb, void *u)
int i2b_PVK_bio (BIO *out, EVP_PKEY *pk, int enclevel, pem_password_cb *cb, void *u)
int ERR_load_PEM_strings (void)
Variables
pem_password_cb * cb
pem_password_cb void * u
Macro Definition Documentation
DECLARE_PEM_read
#define DECLARE_PEM_read (name, type)
Value:
DECLARE_PEM_read_bio(name, type) \
        DECLARE_PEM_read_fp(name, type)
Definition at line 269 of file pem.h.
DECLARE_PEM_read_bio
#define DECLARE_PEM_read_bio (name, type) type *PEM_read_bio_##name(BIO *bp, type **x, pem_password_cb *cb, void *u);
Definition at line 247 of file pem.h.
DECLARE_PEM_read_fp
#define DECLARE_PEM_read_fp (name, type) type *PEM_read_##name(FILE *fp, type **x, pem_password_cb *cb, void *u);
Definition at line 232 of file pem.h.
DECLARE_PEM_rw
#define DECLARE_PEM_rw (name, type)
Value:
DECLARE_PEM_read(name, type) \
        DECLARE_PEM_write(name, type)
Definition at line 272 of file pem.h.
DECLARE_PEM_rw_cb
#define DECLARE_PEM_rw_cb (name, type)
Value:
DECLARE_PEM_read(name, type) \
        DECLARE_PEM_write_cb(name, type)
Definition at line 278 of file pem.h.
DECLARE_PEM_rw_const
#define DECLARE_PEM_rw_const (name, type)
Value:
DECLARE_PEM_read(name, type) \
        DECLARE_PEM_write_const(name, type)
Definition at line 275 of file pem.h.
DECLARE_PEM_write
#define DECLARE_PEM_write (name, type)
Value:
DECLARE_PEM_write_bio(name, type) \
        DECLARE_PEM_write_fp(name, type)
Definition at line 260 of file pem.h.
DECLARE_PEM_write_bio
#define DECLARE_PEM_write_bio (name, type) int PEM_write_bio_##name(BIO *bp, type *x);
Definition at line 250 of file pem.h.
DECLARE_PEM_write_bio_const
#define DECLARE_PEM_write_bio_const (name, type) int PEM_write_bio_##name(BIO *bp, const type *x);
Definition at line 253 of file pem.h.
DECLARE_PEM_write_cb
#define DECLARE_PEM_write_cb (name, type)
Value:
DECLARE_PEM_write_cb_bio(name, type) \
        DECLARE_PEM_write_cb_fp(name, type)
Definition at line 266 of file pem.h.
DECLARE_PEM_write_cb_bio
#define DECLARE_PEM_write_cb_bio (name, type)
Value:
int PEM_write_bio_##name(BIO *bp, type *x, const EVP_CIPHER *enc, \
             unsigned char *kstr, int klen, pem_password_cb *cb, void *u);
Definition at line 256 of file pem.h.
DECLARE_PEM_write_cb_fp
#define DECLARE_PEM_write_cb_fp (name, type)
Value:
int PEM_write_##name(FILE *fp, type *x, const EVP_CIPHER *enc, \
             unsigned char *kstr, int klen, pem_password_cb *cb, void *u);
Definition at line 241 of file pem.h.
DECLARE_PEM_write_const
#define DECLARE_PEM_write_const (name, type)
Value:
DECLARE_PEM_write_bio_const(name, type) \
        DECLARE_PEM_write_fp_const(name, type)
Definition at line 263 of file pem.h.
DECLARE_PEM_write_fp
#define DECLARE_PEM_write_fp (name, type) int PEM_write_##name(FILE *fp, type *x);
Definition at line 235 of file pem.h.
DECLARE_PEM_write_fp_const
#define DECLARE_PEM_write_fp_const (name, type) int PEM_write_##name(FILE *fp, const type *x);
Definition at line 238 of file pem.h.
IMPLEMENT_PEM_read
#define IMPLEMENT_PEM_read (name, type, str, asn1)
Value:
IMPLEMENT_PEM_read_bio(name, type, str, asn1) \
        IMPLEMENT_PEM_read_fp(name, type, str, asn1)
Definition at line 206 of file pem.h.
IMPLEMENT_PEM_read_bio
#define IMPLEMENT_PEM_read_bio (name, type, str, asn1)
Value:
type *PEM_read_bio_##name(BIO *bp, type **x, pem_password_cb *cb, void *u)\
{ \
return PEM_ASN1_read_bio((d2i_of_void *)d2i_##asn1, str,bp,(void **)x,cb,u); \
}
Definition at line 158 of file pem.h.
IMPLEMENT_PEM_read_fp
#define IMPLEMENT_PEM_read_fp (name, type, str, asn1)
Value:
type *PEM_read_##name(FILE *fp, type **x, pem_password_cb *cb, void *u)\
{ \
return PEM_ASN1_read((d2i_of_void *)d2i_##asn1, str,fp,(void **)x,cb,u); \
}
Definition at line 122 of file pem.h.
IMPLEMENT_PEM_rw
#define IMPLEMENT_PEM_rw (name, type, str, asn1)
Value:
IMPLEMENT_PEM_read(name, type, str, asn1) \
        IMPLEMENT_PEM_write(name, type, str, asn1)
Definition at line 210 of file pem.h.
IMPLEMENT_PEM_rw_cb
#define IMPLEMENT_PEM_rw_cb (name, type, str, asn1)
Value:
IMPLEMENT_PEM_read(name, type, str, asn1) \
        IMPLEMENT_PEM_write_cb(name, type, str, asn1)
Definition at line 218 of file pem.h.
IMPLEMENT_PEM_rw_const
#define IMPLEMENT_PEM_rw_const (name, type, str, asn1)
Value:
IMPLEMENT_PEM_read(name, type, str, asn1) \
        IMPLEMENT_PEM_write_const(name, type, str, asn1)
Definition at line 214 of file pem.h.
IMPLEMENT_PEM_write
#define IMPLEMENT_PEM_write (name, type, str, asn1)
Value:
IMPLEMENT_PEM_write_bio(name, type, str, asn1) \
        IMPLEMENT_PEM_write_fp(name, type, str, asn1)
Definition at line 190 of file pem.h.
IMPLEMENT_PEM_write_bio
#define IMPLEMENT_PEM_write_bio (name, type, str, asn1)
Value:
int PEM_write_bio_##name(BIO *bp, type *x) \
{ \
return PEM_ASN1_write_bio((i2d_of_void *)i2d_##asn1,str,bp,x,NULL,NULL,0,NULL,NULL); \
}
Definition at line 164 of file pem.h.
IMPLEMENT_PEM_write_bio_const
#define IMPLEMENT_PEM_write_bio_const (name, type, str, asn1)
Value:
int PEM_write_bio_##name(BIO *bp, const type *x) \
{ \
return PEM_ASN1_write_bio((i2d_of_void *)i2d_##asn1,str,bp,(void *)x,NULL,NULL,0,NULL,NULL); \
}
Definition at line 170 of file pem.h.
IMPLEMENT_PEM_write_cb
#define IMPLEMENT_PEM_write_cb (name, type, str, asn1)
Value:
IMPLEMENT_PEM_write_cb_bio(name, type, str, asn1) \
        IMPLEMENT_PEM_write_cb_fp(name, type, str, asn1)
Definition at line 198 of file pem.h.
IMPLEMENT_PEM_write_cb_bio
#define IMPLEMENT_PEM_write_cb_bio (name, type, str, asn1)
Value:
int PEM_write_bio_##name(BIO *bp, type *x, const EVP_CIPHER *enc, \
             unsigned char *kstr, int klen, pem_password_cb *cb, void *u) \
        { \
        return PEM_ASN1_write_bio((i2d_of_void *)i2d_##asn1,str,bp,x,enc,kstr,klen,cb,u); \
        }
Definition at line 176 of file pem.h.
IMPLEMENT_PEM_write_cb_bio_const
#define IMPLEMENT_PEM_write_cb_bio_const (name, type, str, asn1)
Value:
int PEM_write_bio_##name(BIO *bp, type *x, const EVP_CIPHER *enc, \
             unsigned char *kstr, int klen, pem_password_cb *cb, void *u) \
        { \
        return PEM_ASN1_write_bio((i2d_of_void *)i2d_##asn1,str,bp,(void *)x,enc,kstr,klen,cb,u); \
        }
Definition at line 183 of file pem.h.
IMPLEMENT_PEM_write_cb_const
#define IMPLEMENT_PEM_write_cb_const (name, type, str, asn1)
Value:
IMPLEMENT_PEM_write_cb_bio_const(name, type, str, asn1) \
        IMPLEMENT_PEM_write_cb_fp_const(name, type, str, asn1)
Definition at line 202 of file pem.h.
IMPLEMENT_PEM_write_cb_fp
#define IMPLEMENT_PEM_write_cb_fp (name, type, str, asn1)
Value:
int PEM_write_##name(FILE *fp, type *x, const EVP_CIPHER *enc, \
             unsigned char *kstr, int klen, pem_password_cb *cb, \
                  void *u) \
        { \
        return PEM_ASN1_write((i2d_of_void *)i2d_##asn1,str,fp,x,enc,kstr,klen,cb,u); \
        }
Definition at line 140 of file pem.h.
IMPLEMENT_PEM_write_cb_fp_const
#define IMPLEMENT_PEM_write_cb_fp_const (name, type, str, asn1)
Value:
int PEM_write_##name(FILE *fp, type *x, const EVP_CIPHER *enc, \
             unsigned char *kstr, int klen, pem_password_cb *cb, \
                  void *u) \
        { \
        return PEM_ASN1_write((i2d_of_void *)i2d_##asn1,str,fp,x,enc,kstr,klen,cb,u); \
        }
Definition at line 148 of file pem.h.
IMPLEMENT_PEM_write_const
#define IMPLEMENT_PEM_write_const (name, type, str, asn1)
Value:
IMPLEMENT_PEM_write_bio_const(name, type, str, asn1) \
        IMPLEMENT_PEM_write_fp_const(name, type, str, asn1)
Definition at line 194 of file pem.h.
IMPLEMENT_PEM_write_fp
#define IMPLEMENT_PEM_write_fp (name, type, str, asn1)
Value:
int PEM_write_##name(FILE *fp, type *x) \
{ \
return PEM_ASN1_write((i2d_of_void *)i2d_##asn1,str,fp,x,NULL,NULL,0,NULL,NULL); \
}
Definition at line 128 of file pem.h.
IMPLEMENT_PEM_write_fp_const
#define IMPLEMENT_PEM_write_fp_const (name, type, str, asn1)
Value:
int PEM_write_##name(FILE *fp, const type *x) \
{ \
return PEM_ASN1_write((i2d_of_void *)i2d_##asn1,str,fp,(void *)x,NULL,NULL,0,NULL,NULL); \
}
Definition at line 134 of file pem.h.
PEM_BUFSIZE
#define PEM_BUFSIZE 1024
Definition at line 24 of file pem.h.
PEM_F_B2I_DSS
#define PEM_F_B2I_DSS 127
Definition at line 427 of file pem.h.
PEM_F_B2I_PVK_BIO
#define PEM_F_B2I_PVK_BIO 128
Definition at line 428 of file pem.h.
Referenced by b2i_PVK_bio().
PEM_F_B2I_RSA
#define PEM_F_B2I_RSA 129
Definition at line 429 of file pem.h.
PEM_F_CHECK_BITLEN_DSA
#define PEM_F_CHECK_BITLEN_DSA 130
Definition at line 430 of file pem.h.
PEM_F_CHECK_BITLEN_RSA
#define PEM_F_CHECK_BITLEN_RSA 131
Definition at line 431 of file pem.h.
PEM_F_D2I_PKCS8PRIVATEKEY_BIO
#define PEM_F_D2I_PKCS8PRIVATEKEY_BIO 120
Definition at line 432 of file pem.h.
PEM_F_D2I_PKCS8PRIVATEKEY_FP
#define PEM_F_D2I_PKCS8PRIVATEKEY_FP 121
Definition at line 433 of file pem.h.
PEM_F_DO_B2I
#define PEM_F_DO_B2I 132
Definition at line 434 of file pem.h.
PEM_F_DO_B2I_BIO
#define PEM_F_DO_B2I_BIO 133
Definition at line 435 of file pem.h.
PEM_F_DO_BLOB_HEADER
#define PEM_F_DO_BLOB_HEADER 134
Definition at line 436 of file pem.h.
PEM_F_DO_PK8PKEY
#define PEM_F_DO_PK8PKEY 126
Definition at line 437 of file pem.h.
PEM_F_DO_PK8PKEY_FP
#define PEM_F_DO_PK8PKEY_FP 125
Definition at line 438 of file pem.h.
PEM_F_DO_PVK_BODY
#define PEM_F_DO_PVK_BODY 135
Definition at line 439 of file pem.h.
PEM_F_DO_PVK_HEADER
#define PEM_F_DO_PVK_HEADER 136
Definition at line 440 of file pem.h.
PEM_F_I2B_PVK
#define PEM_F_I2B_PVK 137
Definition at line 441 of file pem.h.
PEM_F_I2B_PVK_BIO
#define PEM_F_I2B_PVK_BIO 138
Definition at line 442 of file pem.h.
PEM_F_LOAD_IV
#define PEM_F_LOAD_IV 101
Definition at line 443 of file pem.h.
PEM_F_PEM_ASN1_READ
#define PEM_F_PEM_ASN1_READ 102
Definition at line 444 of file pem.h.
PEM_F_PEM_ASN1_READ_BIO
#define PEM_F_PEM_ASN1_READ_BIO 103
Definition at line 445 of file pem.h.
PEM_F_PEM_ASN1_WRITE
#define PEM_F_PEM_ASN1_WRITE 104
Definition at line 446 of file pem.h.
PEM_F_PEM_ASN1_WRITE_BIO
#define PEM_F_PEM_ASN1_WRITE_BIO 105
Definition at line 447 of file pem.h.
PEM_F_PEM_DEF_CALLBACK
#define PEM_F_PEM_DEF_CALLBACK 100
Definition at line 448 of file pem.h.
PEM_F_PEM_DO_HEADER
#define PEM_F_PEM_DO_HEADER 106
Definition at line 449 of file pem.h.
PEM_F_PEM_GET_EVP_CIPHER_INFO
#define PEM_F_PEM_GET_EVP_CIPHER_INFO 107
Definition at line 450 of file pem.h.
PEM_F_PEM_READ
#define PEM_F_PEM_READ 108
Definition at line 451 of file pem.h.
PEM_F_PEM_READ_BIO
#define PEM_F_PEM_READ_BIO 109
Definition at line 452 of file pem.h.
PEM_F_PEM_READ_BIO_DHPARAMS
#define PEM_F_PEM_READ_BIO_DHPARAMS 141
Definition at line 453 of file pem.h.
PEM_F_PEM_READ_BIO_PARAMETERS
#define PEM_F_PEM_READ_BIO_PARAMETERS 140
Definition at line 454 of file pem.h.
PEM_F_PEM_READ_BIO_PRIVATEKEY
#define PEM_F_PEM_READ_BIO_PRIVATEKEY 123
Definition at line 455 of file pem.h.
PEM_F_PEM_READ_DHPARAMS
#define PEM_F_PEM_READ_DHPARAMS 142
Definition at line 456 of file pem.h.
PEM_F_PEM_READ_PRIVATEKEY
#define PEM_F_PEM_READ_PRIVATEKEY 124
Definition at line 457 of file pem.h.
PEM_F_PEM_SIGNFINAL
#define PEM_F_PEM_SIGNFINAL 112
Definition at line 458 of file pem.h.
PEM_F_PEM_WRITE
#define PEM_F_PEM_WRITE 113
Definition at line 459 of file pem.h.
PEM_F_PEM_WRITE_BIO
#define PEM_F_PEM_WRITE_BIO 114
Definition at line 460 of file pem.h.
PEM_F_PEM_WRITE_PRIVATEKEY
#define PEM_F_PEM_WRITE_PRIVATEKEY 139
Definition at line 461 of file pem.h.
PEM_F_PEM_X509_INFO_READ
#define PEM_F_PEM_X509_INFO_READ 115
Definition at line 462 of file pem.h.
PEM_F_PEM_X509_INFO_READ_BIO
#define PEM_F_PEM_X509_INFO_READ_BIO 116
Definition at line 463 of file pem.h.
PEM_F_PEM_X509_INFO_WRITE_BIO
#define PEM_F_PEM_X509_INFO_WRITE_BIO 117
Definition at line 464 of file pem.h.
PEM_R_BAD_BASE64_DECODE
#define PEM_R_BAD_BASE64_DECODE 100
Definition at line 467 of file pem.h.
PEM_R_BAD_DECRYPT
#define PEM_R_BAD_DECRYPT 101
Definition at line 468 of file pem.h.
PEM_R_BAD_END_LINE
#define PEM_R_BAD_END_LINE 102
Definition at line 469 of file pem.h.
PEM_R_BAD_IV_CHARS
#define PEM_R_BAD_IV_CHARS 103
Definition at line 470 of file pem.h.
PEM_R_BAD_MAGIC_NUMBER
#define PEM_R_BAD_MAGIC_NUMBER 116
Definition at line 471 of file pem.h.
PEM_R_BAD_PASSWORD_READ
#define PEM_R_BAD_PASSWORD_READ 104
Definition at line 472 of file pem.h.
PEM_R_BAD_VERSION_NUMBER
#define PEM_R_BAD_VERSION_NUMBER 117
Definition at line 473 of file pem.h.
PEM_R_BIO_WRITE_FAILURE
#define PEM_R_BIO_WRITE_FAILURE 118
Definition at line 474 of file pem.h.
PEM_R_CIPHER_IS_NULL
#define PEM_R_CIPHER_IS_NULL 127
Definition at line 475 of file pem.h.
PEM_R_ERROR_CONVERTING_PRIVATE_KEY
#define PEM_R_ERROR_CONVERTING_PRIVATE_KEY 115
Definition at line 476 of file pem.h.
PEM_R_EXPECTING_PRIVATE_KEY_BLOB
#define PEM_R_EXPECTING_PRIVATE_KEY_BLOB 119
Definition at line 477 of file pem.h.
PEM_R_EXPECTING_PUBLIC_KEY_BLOB
#define PEM_R_EXPECTING_PUBLIC_KEY_BLOB 120
Definition at line 478 of file pem.h.
PEM_R_HEADER_TOO_LONG
#define PEM_R_HEADER_TOO_LONG 128
Definition at line 479 of file pem.h.
PEM_R_INCONSISTENT_HEADER
#define PEM_R_INCONSISTENT_HEADER 121
Definition at line 480 of file pem.h.
PEM_R_KEYBLOB_HEADER_PARSE_ERROR
#define PEM_R_KEYBLOB_HEADER_PARSE_ERROR 122
Definition at line 481 of file pem.h.
PEM_R_KEYBLOB_TOO_SHORT
#define PEM_R_KEYBLOB_TOO_SHORT 123
Definition at line 482 of file pem.h.
PEM_R_MISSING_DEK_IV
#define PEM_R_MISSING_DEK_IV 129
Definition at line 483 of file pem.h.
PEM_R_NO_START_LINE
#define PEM_R_NO_START_LINE 108
Definition at line 487 of file pem.h.
PEM_R_NOT_DEK_INFO
#define PEM_R_NOT_DEK_INFO 105
Definition at line 484 of file pem.h.
PEM_R_NOT_ENCRYPTED
#define PEM_R_NOT_ENCRYPTED 106
Definition at line 485 of file pem.h.
PEM_R_NOT_PROC_TYPE
#define PEM_R_NOT_PROC_TYPE 107
Definition at line 486 of file pem.h.
PEM_R_PROBLEMS_GETTING_PASSWORD
#define PEM_R_PROBLEMS_GETTING_PASSWORD 109
Definition at line 488 of file pem.h.
PEM_R_PVK_DATA_TOO_SHORT
#define PEM_R_PVK_DATA_TOO_SHORT 124
Definition at line 489 of file pem.h.
Referenced by b2i_PVK_bio().
PEM_R_PVK_TOO_SHORT
#define PEM_R_PVK_TOO_SHORT 125
Definition at line 490 of file pem.h.
PEM_R_READ_KEY
#define PEM_R_READ_KEY 111
Definition at line 491 of file pem.h.
PEM_R_SHORT_HEADER
#define PEM_R_SHORT_HEADER 112
Definition at line 492 of file pem.h.
PEM_R_UNEXPECTED_DEK_IV
#define PEM_R_UNEXPECTED_DEK_IV 130
Definition at line 493 of file pem.h.
PEM_R_UNSUPPORTED_CIPHER
#define PEM_R_UNSUPPORTED_CIPHER 113
Definition at line 494 of file pem.h.
PEM_R_UNSUPPORTED_ENCRYPTION
#define PEM_R_UNSUPPORTED_ENCRYPTION 114
Definition at line 495 of file pem.h.
PEM_R_UNSUPPORTED_KEY_COMPONENTS
#define PEM_R_UNSUPPORTED_KEY_COMPONENTS 126
Definition at line 496 of file pem.h.
PEM_STRING_CMS
#define PEM_STRING_CMS "CMS"
Definition at line 50 of file pem.h.
PEM_STRING_DHPARAMS
#define PEM_STRING_DHPARAMS "DH PARAMETERS"
Definition at line 42 of file pem.h.
PEM_STRING_DHXPARAMS
#define PEM_STRING_DHXPARAMS "X9.42 DH PARAMETERS"
Definition at line 43 of file pem.h.
PEM_STRING_DSA
#define PEM_STRING_DSA "DSA PRIVATE KEY"
Definition at line 36 of file pem.h.
PEM_STRING_DSA_PUBLIC
#define PEM_STRING_DSA_PUBLIC "DSA PUBLIC KEY"
Definition at line 37 of file pem.h.
PEM_STRING_DSAPARAMS
#define PEM_STRING_DSAPARAMS "DSA PARAMETERS"
Definition at line 45 of file pem.h.
PEM_STRING_ECDSA_PUBLIC
#define PEM_STRING_ECDSA_PUBLIC "ECDSA PUBLIC KEY"
Definition at line 46 of file pem.h.
PEM_STRING_ECPARAMETERS
#define PEM_STRING_ECPARAMETERS "EC PARAMETERS"
Definition at line 47 of file pem.h.
PEM_STRING_ECPRIVATEKEY
#define PEM_STRING_ECPRIVATEKEY "EC PRIVATE KEY"
Definition at line 48 of file pem.h.
PEM_STRING_EVP_PKEY
#define PEM_STRING_EVP_PKEY "ANY PRIVATE KEY"
Definition at line 32 of file pem.h.
PEM_STRING_PARAMETERS
#define PEM_STRING_PARAMETERS "PARAMETERS"
Definition at line 49 of file pem.h.
PEM_STRING_PKCS7
#define PEM_STRING_PKCS7 "PKCS7"
Definition at line 38 of file pem.h.
PEM_STRING_PKCS7_SIGNED
#define PEM_STRING_PKCS7_SIGNED "PKCS #7 SIGNED DATA"
Definition at line 39 of file pem.h.
PEM_STRING_PKCS8
#define PEM_STRING_PKCS8 "ENCRYPTED PRIVATE KEY"
Definition at line 40 of file pem.h.
PEM_STRING_PKCS8INF
#define PEM_STRING_PKCS8INF "PRIVATE KEY"
Definition at line 41 of file pem.h.
PEM_STRING_PUBLIC
#define PEM_STRING_PUBLIC "PUBLIC KEY"
Definition at line 33 of file pem.h.
PEM_STRING_RSA
#define PEM_STRING_RSA "RSA PRIVATE KEY"
Definition at line 34 of file pem.h.
PEM_STRING_RSA_PUBLIC
#define PEM_STRING_RSA_PUBLIC "RSA PUBLIC KEY"
Definition at line 35 of file pem.h.
PEM_STRING_SSL_SESSION
#define PEM_STRING_SSL_SESSION "SSL SESSION PARAMETERS"
Definition at line 44 of file pem.h.
PEM_STRING_X509
#define PEM_STRING_X509 "CERTIFICATE"
Definition at line 27 of file pem.h.
PEM_STRING_X509_CRL
#define PEM_STRING_X509_CRL "X509 CRL"
Definition at line 31 of file pem.h.
PEM_STRING_X509_OLD
#define PEM_STRING_X509_OLD "X509 CERTIFICATE"
Definition at line 26 of file pem.h.
PEM_STRING_X509_REQ
#define PEM_STRING_X509_REQ "CERTIFICATE REQUEST"
Definition at line 30 of file pem.h.
PEM_STRING_X509_REQ_OLD
#define PEM_STRING_X509_REQ_OLD "NEW CERTIFICATE REQUEST"
Definition at line 29 of file pem.h.
PEM_STRING_X509_TRUSTED
#define PEM_STRING_X509_TRUSTED "TRUSTED CERTIFICATE"
Definition at line 28 of file pem.h.
PEM_TYPE_CLEAR
#define PEM_TYPE_CLEAR 40
Definition at line 55 of file pem.h.
PEM_TYPE_ENCRYPTED
#define PEM_TYPE_ENCRYPTED 10
Definition at line 52 of file pem.h.
PEM_TYPE_MIC_CLEAR
#define PEM_TYPE_MIC_CLEAR 30
Definition at line 54 of file pem.h.
PEM_TYPE_MIC_ONLY
#define PEM_TYPE_MIC_ONLY 20
Definition at line 53 of file pem.h.
Typedef Documentation
pem_password_cb
typedef int pem_password_cb(char *buf, int size, int rwflag, void *userdata)
Definition at line 281 of file pem.h.
Function Documentation
b2i_PrivateKey()
EVP_PKEY* b2i_PrivateKey (const unsigned char ** in, long length)
Definition at line 370 of file pvkfmt.c.
b2i_PrivateKey_bio()
EVP_PKEY* b2i_PrivateKey_bio (BIO * in)
Definition at line 380 of file pvkfmt.c.
b2i_PublicKey()
EVP_PKEY* b2i_PublicKey (const unsigned char ** in, long length)
Definition at line 375 of file pvkfmt.c.
b2i_PublicKey_bio()
EVP_PKEY* b2i_PublicKey_bio (BIO * in)
Definition at line 385 of file pvkfmt.c.
b2i_PVK_bio()
EVP_PKEY* b2i_PVK_bio (BIO * in, pem_password_cb * cb, void * u)
Definition at line 732 of file pvkfmt.c.
References BIO_read(), NULL, PEM_F_B2I_PVK_BIO, PEM_R_PVK_DATA_TOO_SHORT, and PEMerr.
d2i_PKCS8PrivateKey_bio()
EVP_PKEY* d2i_PKCS8PrivateKey_bio (BIO * bp, EVP_PKEY ** x, pem_password_cb * cb, void * u)
Definition at line 112 of file pem_pk8.c.
References NULL.
d2i_PKCS8PrivateKey_fp()
EVP_PKEY* d2i_PKCS8PrivateKey_fp (FILE * fp, EVP_PKEY ** x, pem_password_cb * cb, void * u)
Definition at line 192 of file pem_pk8.c.
References bp.
DECLARE_PEM_rw() [1/5]
DECLARE_PEM_rw (X509 , X509)
DECLARE_PEM_rw() [2/5]
X509 DECLARE_PEM_rw (X509_REQ , X509_REQ)
DECLARE_PEM_rw() [3/5]
X509 X509_REQ DECLARE_PEM_rw (X509_CRL , X509_CRL)
DECLARE_PEM_rw() [4/5]
X509 X509_REQ PKCS7 DECLARE_PEM_rw (NETSCAPE_CERT_SEQUENCE , NETSCAPE_CERT_SEQUENCE)
DECLARE_PEM_rw() [5/5]
X509 X509_REQ PKCS7 X509_SIG DECLARE_PEM_rw (PKCS8_PRIV_KEY_INFO , PKCS8_PRIV_KEY_INFO)
DECLARE_PEM_rw_cb() [1/3]
X509 X509_REQ PKCS7 X509_SIG RSA RSA DECLARE_PEM_rw_cb (DSAPrivateKey , DSA)
DECLARE_PEM_rw_cb() [2/3]
X509 X509_REQ PKCS7 X509_SIG RSA RSA DSA EC_GROUP DECLARE_PEM_rw_cb (ECPrivateKey , EC_KEY)
DECLARE_PEM_rw_cb() [3/3]
X509 X509_REQ PKCS7 X509_SIG RSA RSA DSA EC_GROUP EC_KEY DH DECLARE_PEM_rw_cb (PrivateKey , EVP_PKEY)
DECLARE_PEM_rw_const() [1/3]
X509 X509_REQ PKCS7 X509_SIG RSA DECLARE_PEM_rw_const (RSAPublicKey , RSA)
DECLARE_PEM_rw_const() [2/3]
X509 X509_REQ PKCS7 X509_SIG RSA RSA DSA DECLARE_PEM_rw_const (DSAparams , DSA)
DECLARE_PEM_rw_const() [3/3]
X509 X509_REQ PKCS7 X509_SIG RSA RSA DSA EC_GROUP EC_KEY DECLARE_PEM_rw_const (DHparams , DH)
ERR_load_PEM_strings()
int ERR_load_PEM_strings (void)
Definition at line 105 of file pem_err.c.
i2b_PrivateKey_bio()
int i2b_PrivateKey_bio (BIO * out, EVP_PKEY * pk)
Definition at line 586 of file pvkfmt.c.
i2b_PublicKey_bio()
int i2b_PublicKey_bio (BIO * out, EVP_PKEY * pk)
Definition at line 591 of file pvkfmt.c.
i2b_PVK_bio()
int i2b_PVK_bio (BIO * out, EVP_PKEY * pk, int enclevel, pem_password_cb * cb, void * u)
Definition at line 850 of file pvkfmt.c.
References NULL.
i2d_PKCS8PrivateKey_bio()
int i2d_PKCS8PrivateKey_bio (BIO * bp, EVP_PKEY * x, const EVP_CIPHER * enc, char * kstr, int klen, pem_password_cb * cb, void * u)
Definition at line 49 of file pem_pk8.c.
i2d_PKCS8PrivateKey_fp()
int i2d_PKCS8PrivateKey_fp (FILE * fp, EVP_PKEY * x, const EVP_CIPHER * enc, char * kstr, int klen, pem_password_cb * cb, void * u)
Definition at line 149 of file pem_pk8.c.
i2d_PKCS8PrivateKey_nid_bio()
int i2d_PKCS8PrivateKey_nid_bio (BIO * bp, EVP_PKEY * x, int nid, char * kstr, int klen, pem_password_cb * cb, void * u)
Definition at line 56 of file pem_pk8.c.
i2d_PKCS8PrivateKey_nid_fp()
int i2d_PKCS8PrivateKey_nid_fp (FILE * fp, EVP_PKEY * x, int nid, char * kstr, int klen, pem_password_cb * cb, void * u)
Definition at line 155 of file pem_pk8.c.
PEM_ASN1_read()
void* PEM_ASN1_read (d2i_of_void * d2i, const char * name, FILE * fp, void ** x, pem_password_cb * cb, void * u)
Definition at line 119 of file pem_lib.c.
PEM_ASN1_read_bio()
void* PEM_ASN1_read_bio (d2i_of_void * d2i, const char * name, BIO * bp, void ** x, pem_password_cb * cb, void * u)
Definition at line 20 of file pem_oth.c.
References data, len, and NULL.
PEM_ASN1_write()
int PEM_ASN1_write (i2d_of_void * i2d, const char * name, FILE * fp, void * x, const EVP_CIPHER * enc, unsigned char * kstr, int klen, pem_password_cb * callback, void * u)
Definition at line 276 of file pem_lib.c.
PEM_ASN1_write_bio()
int PEM_ASN1_write_bio (i2d_of_void * i2d, const char * name, BIO * bp, void * x, const EVP_CIPHER * enc, unsigned char * kstr, int klen, pem_password_cb * cb, void * u)
Definition at line 294 of file pem_lib.c.
References ctx, and NULL.
Referenced by PEM_write_bio_Parameters(), and PEM_write_bio_PrivateKey_traditional().
PEM_bytes_read_bio()
int PEM_bytes_read_bio (unsigned char ** pdata, long * plen, char ** pnm, const char * name, BIO * bp, pem_password_cb * cb, void * u)
Definition at line 231 of file pem_lib.c.
PEM_def_callback()
int PEM_def_callback (char * buf, int num, int w, void * key)
Definition at line 31 of file pem_lib.c.
PEM_dek_info()
void PEM_dek_info (char * buf, const char * type, int len, char * str)
Definition at line 98 of file pem_lib.c.
PEM_do_header()
int PEM_do_header (EVP_CIPHER_INFO * cipher, unsigned char * data, long * len, pem_password_cb * callback, void * u)
Definition at line 392 of file pem_lib.c.
PEM_get_EVP_CIPHER_INFO()
int PEM_get_EVP_CIPHER_INFO (char * header, EVP_CIPHER_INFO * cipher)
Definition at line 465 of file pem_lib.c.
PEM_proc_type()
void PEM_proc_type (char * buf, int type)
Definition at line 80 of file pem_lib.c.
PEM_read()
int PEM_read (FILE * fp, char ** name, char ** header, unsigned char ** data, long * len)
Definition at line 647 of file pem_lib.c.
PEM_read_bio()
int PEM_read_bio (BIO * bp, char ** name, char ** header, unsigned char ** data, long * len)
Definition at line 664 of file pem_lib.c.
References ctx, and EVP_ENCODE_CTX_new().
PEM_read_bio_Parameters()
EVP_PKEY* PEM_read_bio_Parameters (BIO * bp, EVP_PKEY ** x)
Definition at line 114 of file pem_pkey.c.
References data, len, and NULL.
PEM_SignFinal()
int PEM_SignFinal (EVP_MD_CTX * ctx, unsigned char * sigret, unsigned int * siglen, EVP_PKEY * pkey)
Definition at line 27 of file pem_sign.c.
PEM_SignInit()
int PEM_SignInit (EVP_MD_CTX * ctx, EVP_MD * type)
Definition at line 17 of file pem_sign.c.
References EVP_DigestInit_ex(), and NULL.
PEM_SignUpdate()
int PEM_SignUpdate (EVP_MD_CTX * ctx, unsigned char * d, unsigned int cnt)
Definition at line 22 of file pem_sign.c.
References EVP_DigestUpdate().
PEM_write()
int PEM_write (FILE * fp, const char * name, const char * hdr, const unsigned char * data, long len)
Definition at line 568 of file pem_lib.c.
PEM_write_bio()
int PEM_write_bio (BIO * bp, const char * name, const char * hdr, const unsigned char * data, long len)
Definition at line 585 of file pem_lib.c.
PEM_write_bio_Parameters()
int PEM_write_bio_Parameters (BIO * bp, EVP_PKEY * x)
Definition at line 152 of file pem_pkey.c.
References BIO_snprintf(), NULL, and PEM_ASN1_write_bio().
PEM_write_bio_PKCS8PrivateKey()
int PEM_write_bio_PKCS8PrivateKey (BIO * , EVP_PKEY * , const EVP_CIPHER * , char * , int , pem_password_cb * , void *)
Definition at line 42 of file pem_pk8.c.
Referenced by PEM_write_bio_PrivateKey().
PEM_write_bio_PKCS8PrivateKey_nid()
int PEM_write_bio_PKCS8PrivateKey_nid (BIO * bp, EVP_PKEY * x, int nid, char * kstr, int klen, pem_password_cb * cb, void * u)
Definition at line 35 of file pem_pk8.c.
PEM_write_bio_PrivateKey_traditional()
X509 X509_REQ PKCS7 X509_SIG RSA RSA DSA EC_GROUP EC_KEY DH EVP_PKEY int PEM_write_bio_PrivateKey_traditional (BIO * bp, EVP_PKEY * x, const EVP_CIPHER * enc, unsigned char * kstr, int klen, pem_password_cb * cb, void * u)
Definition at line 103 of file pem_pkey.c.
References BIO_snprintf(), i2d_PrivateKey(), and PEM_ASN1_write_bio().
Referenced by PEM_write_bio_PrivateKey().
PEM_write_PKCS8PrivateKey()
int PEM_write_PKCS8PrivateKey (FILE * fp, EVP_PKEY * x, const EVP_CIPHER * enc, char * kstr, int klen, pem_password_cb * cd, void * u)
Definition at line 169 of file pem_pk8.c.
PEM_write_PKCS8PrivateKey_nid()
int PEM_write_PKCS8PrivateKey_nid (FILE * fp, EVP_PKEY * x, int nid, char * kstr, int klen, pem_password_cb * cb, void * u)
Definition at line 162 of file pem_pk8.c.
PEM_X509_INFO_write_bio()
int PEM_X509_INFO_write_bio (BIO * bp, X509_INFO * xi, EVP_CIPHER * enc, unsigned char * kstr, int klen, pem_password_cb * cd, void * u)
Definition at line 247 of file pem_info.c.
STACK_OF()
STACK_OF (X509_INFO)
Variable Documentation
cb
pem_password_cb* cb
Definition at line 301 of file pem.h.
u
pem_password_cb void * u
Definition at line 301 of file pem.h.
Referenced by DES_encrypt1(), DES_encrypt2(), srp_generate_client_master_secret(), srp_generate_server_master_secret(), SSL_CTX_set_default_passwd_cb_userdata(), and SSL_set_default_passwd_cb_userdata().