crypto/pem/pem_lib.c File Reference
pem_lib.c File Reference
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include "internal/cryptlib.h"
#include <openssl/buffer.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/rand.h>
#include <openssl/x509.h>
#include <openssl/pem.h>
#include <openssl/pkcs12.h>
#include "internal/asn1_int.h"
#include <openssl/des.h>
#include <openssl/engine.h>
Macros
#define MIN_LENGTH 4
Functions
int pem_check_suffix (const char *pem_str, const char *suffix)
int PEM_def_callback (char *buf, int num, int w, void *key)
void PEM_proc_type (char *buf, int type)
void PEM_dek_info (char *buf, const char *type, int len, char *str)
void * PEM_ASN1_read (d2i_of_void *d2i, const char *name, FILE *fp, void **x, pem_password_cb *cb, void *u)
int PEM_bytes_read_bio (unsigned char **pdata, long *plen, char **pnm, const char *name, BIO *bp, pem_password_cb *cb, void *u)
int PEM_ASN1_write (i2d_of_void *i2d, const char *name, FILE *fp, void *x, const EVP_CIPHER *enc, unsigned char *kstr, int klen, pem_password_cb *callback, void *u)
int PEM_ASN1_write_bio (i2d_of_void *i2d, const char *name, BIO *bp, void *x, const EVP_CIPHER *enc, unsigned char *kstr, int klen, pem_password_cb *callback, void *u)
int PEM_do_header (EVP_CIPHER_INFO *cipher, unsigned char *data, long *plen, pem_password_cb *callback, void *u)
int PEM_get_EVP_CIPHER_INFO (char *header, EVP_CIPHER_INFO *cipher)
int PEM_write (FILE *fp, const char *name, const char *header, const unsigned char *data, long len)
int PEM_write_bio (BIO *bp, const char *name, const char *header, const unsigned char *data, long len)
int PEM_read (FILE *fp, char **name, char **header, unsigned char **data, long *len)
int PEM_read_bio (BIO *bp, char **name, char **header, unsigned char **data, long *len)
Macro Definition Documentation
MIN_LENGTH
#define MIN_LENGTH 4
Definition at line 25 of file pem_lib.c.
Function Documentation
PEM_ASN1_read()
void* PEM_ASN1_read (d2i_of_void * d2i, const char * name, FILE * fp, void ** x, pem_password_cb * cb, void * u)
Definition at line 119 of file pem_lib.c.
PEM_ASN1_write()
int PEM_ASN1_write (i2d_of_void * i2d, const char * name, FILE * fp, void * x, const EVP_CIPHER * enc, unsigned char * kstr, int klen, pem_password_cb * callback, void * u)
Definition at line 276 of file pem_lib.c.
PEM_ASN1_write_bio()
int PEM_ASN1_write_bio (i2d_of_void * i2d, const char * name, BIO * bp, void * x, const EVP_CIPHER * enc, unsigned char * kstr, int klen, pem_password_cb * callback, void * u)
Definition at line 294 of file pem_lib.c.
References ctx, and NULL.
Referenced by PEM_write_bio_Parameters(), and PEM_write_bio_PrivateKey_traditional().
PEM_bytes_read_bio()
int PEM_bytes_read_bio (unsigned char ** pdata, long * plen, char ** pnm, const char * name, BIO * bp, pem_password_cb * cb, void * u)
Definition at line 231 of file pem_lib.c.
pem_check_suffix()
int pem_check_suffix (const char * pem_str, const char * suffix)
Definition at line 843 of file pem_lib.c.
PEM_def_callback()
int PEM_def_callback (char * buf, int num, int w, void * key)
Definition at line 31 of file pem_lib.c.
PEM_dek_info()
void PEM_dek_info (char * buf, const char * type, int len, char * str)
Definition at line 98 of file pem_lib.c.
PEM_do_header()
int PEM_do_header (EVP_CIPHER_INFO * cipher, unsigned char * data, long * plen, pem_password_cb * callback, void * u)
Definition at line 392 of file pem_lib.c.
PEM_get_EVP_CIPHER_INFO()
int PEM_get_EVP_CIPHER_INFO (char * header, EVP_CIPHER_INFO * cipher)
Definition at line 465 of file pem_lib.c.
PEM_proc_type()
void PEM_proc_type (char * buf, int type)
Definition at line 80 of file pem_lib.c.
PEM_read()
int PEM_read (FILE * fp, char ** name, char ** header, unsigned char ** data, long * len)
Definition at line 647 of file pem_lib.c.
PEM_read_bio()
int PEM_read_bio (BIO * bp, char ** name, char ** header, unsigned char ** data, long * len)
Definition at line 664 of file pem_lib.c.
References ctx, and EVP_ENCODE_CTX_new().
PEM_write()
int PEM_write (FILE * fp, const char * name, const char * header, const unsigned char * data, long len)
Definition at line 568 of file pem_lib.c.
PEM_write_bio()
int PEM_write_bio (BIO * bp, const char * name, const char * header, const unsigned char * data, long len)
Definition at line 585 of file pem_lib.c.