crypto/pkcs7/pk7_smime.c File Reference
pk7_smime.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/x509.h>
#include <openssl/x509v3.h>
Macros
#define BUFFERSIZE 4096
Functions
PKCS7 * PKCS7_sign (X509 *signcert, EVP_PKEY *pkey, STACK_OF(X509) *certs, BIO *data, int flags)
int PKCS7_final (PKCS7 *p7, BIO *data, int flags)
PKCS7_SIGNER_INFO * PKCS7_sign_add_signer (PKCS7 *p7, X509 *signcert, EVP_PKEY *pkey, const EVP_MD *md, int flags)
int PKCS7_verify (PKCS7 *p7, STACK_OF(X509) *certs, X509_STORE *store, BIO *indata, BIO *out, int flags)
STACK_OF (X509)
PKCS7 * PKCS7_encrypt (STACK_OF(X509) *certs, BIO *in, const EVP_CIPHER *cipher, int flags)
int PKCS7_decrypt (PKCS7 *p7, EVP_PKEY *pkey, X509 *cert, BIO *data, int flags)
Macro Definition Documentation
BUFFERSIZE
#define BUFFERSIZE 4096
Definition at line 18 of file pk7_smime.c.
Function Documentation
PKCS7_decrypt()
int PKCS7_decrypt (PKCS7 * p7, EVP_PKEY * pkey, X509 * cert, BIO * data, int flags)
Definition at line 477 of file pk7_smime.c.
PKCS7_encrypt()
PKCS7* PKCS7_encrypt (STACK_OF(X509) * certs, BIO * in, const EVP_CIPHER * cipher, int flags)
Definition at line 436 of file pk7_smime.c.
PKCS7_final()
int PKCS7_final (PKCS7 * p7, BIO * data, int flags)
Definition at line 65 of file pk7_smime.c.
Referenced by PKCS7_sign().
PKCS7_sign()
PKCS7* PKCS7_sign (X509 * signcert, EVP_PKEY * pkey, STACK_OF(X509) * certs, BIO * data, int flags)
Definition at line 22 of file pk7_smime.c.
References ERR_R_MALLOC_FAILURE, NID_pkcs7_data, NID_pkcs7_signed, NULL, PKCS7_add_certificate(), PKCS7_content_new(), PKCS7_DETACHED, PKCS7_F_PKCS7_SIGN, PKCS7_final(), PKCS7_NOCERTS, PKCS7_PARTIAL, PKCS7_R_PKCS7_ADD_SIGNER_ERROR, PKCS7_set_detached, PKCS7_set_type(), PKCS7_sign_add_signer(), PKCS7_STREAM, and PKCS7err.
PKCS7_sign_add_signer()
PKCS7_SIGNER_INFO* PKCS7_sign_add_signer (PKCS7 * p7, X509 * signcert, EVP_PKEY * pkey, const EVP_MD * md, int flags)
Definition at line 109 of file pk7_smime.c.
Referenced by PKCS7_sign().
PKCS7_verify()
int PKCS7_verify (PKCS7 * p7, STACK_OF(X509) * certs, X509_STORE * store, BIO * indata, BIO * out, int flags)
Definition at line 204 of file pk7_smime.c.
STACK_OF()
STACK_OF (X509)
Definition at line 372 of file pk7_smime.c.
References PKCS7::d, ERR_R_MALLOC_FAILURE, PKCS7_ISSUER_AND_SERIAL::issuer, PKCS7_SIGNER_INFO::issuer_and_serial, NULL, PKCS7_F_PKCS7_GET0_SIGNERS, PKCS7_NOINTERN, PKCS7_R_INVALID_NULL_POINTER, PKCS7_R_NO_SIGNERS, PKCS7_R_SIGNER_CERTIFICATE_NOT_FOUND, PKCS7_R_WRONG_CONTENT_TYPE, PKCS7_type_is_signed, PKCS7err, PKCS7_ISSUER_AND_SERIAL::serial, PKCS7::sign, and X509_find_by_issuer_and_serial().