crypto/pkcs7/pk7_lib.c File Reference
pk7_lib.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/x509.h>
#include "internal/asn1_int.h"
#include "internal/evp_int.h"
Functions
long PKCS7_ctrl (PKCS7 *p7, int cmd, long larg, char *parg)
int PKCS7_content_new (PKCS7 *p7, int type)
int PKCS7_set_content (PKCS7 *p7, PKCS7 *p7_data)
int PKCS7_set_type (PKCS7 *p7, int type)
int PKCS7_set0_type_other (PKCS7 *p7, int type, ASN1_TYPE *other)
int PKCS7_add_signer (PKCS7 *p7, PKCS7_SIGNER_INFO *psi)
int PKCS7_add_certificate (PKCS7 *p7, X509 *x509)
int PKCS7_add_crl (PKCS7 *p7, X509_CRL *crl)
int PKCS7_SIGNER_INFO_set (PKCS7_SIGNER_INFO *p7i, X509 *x509, EVP_PKEY *pkey, const EVP_MD *dgst)
PKCS7_SIGNER_INFO * PKCS7_add_signature (PKCS7 *p7, X509 *x509, EVP_PKEY *pkey, const EVP_MD *dgst)
int PKCS7_set_digest (PKCS7 *p7, const EVP_MD *md)
STACK_OF (PKCS7_SIGNER_INFO)
void PKCS7_SIGNER_INFO_get0_algs (PKCS7_SIGNER_INFO *si, EVP_PKEY **pk, X509_ALGOR **pdig, X509_ALGOR **psig)
void PKCS7_RECIP_INFO_get0_alg (PKCS7_RECIP_INFO *ri, X509_ALGOR **penc)
PKCS7_RECIP_INFO * PKCS7_add_recipient (PKCS7 *p7, X509 *x509)
int PKCS7_add_recipient_info (PKCS7 *p7, PKCS7_RECIP_INFO *ri)
int PKCS7_RECIP_INFO_set (PKCS7_RECIP_INFO *p7i, X509 *x509)
X509 * PKCS7_cert_from_signer_info (PKCS7 *p7, PKCS7_SIGNER_INFO *si)
int PKCS7_set_cipher (PKCS7 *p7, const EVP_CIPHER *cipher)
int PKCS7_stream (unsigned char ***boundary, PKCS7 *p7)
Function Documentation
PKCS7_add_certificate()
int PKCS7_add_certificate (PKCS7 * p7, X509 * x509)
Definition at line 239 of file pk7_lib.c.
References PKCS7::d, ERR_R_MALLOC_FAILURE, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, NULL, OBJ_obj2nid(), PKCS7_F_PKCS7_ADD_CERTIFICATE, PKCS7_R_WRONG_CONTENT_TYPE, PKCS7err, PKCS7::sign, PKCS7::signed_and_enveloped, STACK_OF(), PKCS7::type, and X509_up_ref().
Referenced by PKCS7_sign().
PKCS7_add_crl()
int PKCS7_add_crl (PKCS7 * p7, X509_CRL * crl)
Definition at line 271 of file pk7_lib.c.
References PKCS7::d, ERR_R_MALLOC_FAILURE, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, NULL, OBJ_obj2nid(), PKCS7_F_PKCS7_ADD_CRL, PKCS7_R_WRONG_CONTENT_TYPE, PKCS7err, PKCS7::sign, PKCS7::signed_and_enveloped, STACK_OF(), PKCS7::type, and X509_CRL_up_ref().
PKCS7_add_recipient()
PKCS7_RECIP_INFO* PKCS7_add_recipient (PKCS7 * p7, X509 * x509)
Definition at line 423 of file pk7_lib.c.
References NULL, PKCS7_add_recipient_info(), and PKCS7_RECIP_INFO_set().
PKCS7_add_recipient_info()
int PKCS7_add_recipient_info (PKCS7 * p7, PKCS7_RECIP_INFO * ri)
Definition at line 439 of file pk7_lib.c.
References PKCS7::d, PKCS7::enveloped, NID_pkcs7_enveloped, NID_pkcs7_signedAndEnveloped, OBJ_obj2nid(), PKCS7_F_PKCS7_ADD_RECIPIENT_INFO, PKCS7_R_WRONG_CONTENT_TYPE, PKCS7err, PKCS7::signed_and_enveloped, STACK_OF(), and PKCS7::type.
Referenced by PKCS7_add_recipient().
PKCS7_add_signature()
PKCS7_SIGNER_INFO* PKCS7_add_signature (PKCS7 * p7, X509 * x509, EVP_PKEY * pkey, const EVP_MD * dgst)
Definition at line 350 of file pk7_lib.c.
References EVP_get_digestbynid, EVP_PKEY_get_default_digest_nid(), NULL, PKCS7_add_signer(), PKCS7_F_PKCS7_ADD_SIGNATURE, PKCS7_R_NO_DEFAULT_DIGEST, PKCS7_SIGNER_INFO_set(), and PKCS7err.
PKCS7_add_signer()
int PKCS7_add_signer (PKCS7 * p7, PKCS7_SIGNER_INFO * psi)
Definition at line 186 of file pk7_lib.c.
References PKCS7::d, PKCS7_SIGNER_INFO::digest_alg, ERR_R_MALLOC_FAILURE, nid, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, NULL, OBJ_nid2obj(), OBJ_obj2nid(), PKCS7_F_PKCS7_ADD_SIGNER, PKCS7_R_WRONG_CONTENT_TYPE, PKCS7err, PKCS7::sign, PKCS7::signed_and_enveloped, STACK_OF(), PKCS7::type, and V_ASN1_NULL.
Referenced by PKCS7_add_signature().
PKCS7_cert_from_signer_info()
X509* PKCS7_cert_from_signer_info (PKCS7 * p7, PKCS7_SIGNER_INFO * si)
Definition at line 507 of file pk7_lib.c.
References PKCS7::d, PKCS7_ISSUER_AND_SERIAL::issuer, PKCS7_SIGNER_INFO::issuer_and_serial, NULL, PKCS7_type_is_signed, PKCS7::sign, and X509_find_by_issuer_and_serial().
PKCS7_content_new()
int PKCS7_content_new (PKCS7 * p7, int type)
Definition at line 63 of file pk7_lib.c.
Referenced by PKCS7_sign().
PKCS7_ctrl()
long PKCS7_ctrl (PKCS7 * p7, int cmd, long larg, char * parg)
Definition at line 17 of file pk7_lib.c.
References nid.
PKCS7_RECIP_INFO_get0_alg()
void PKCS7_RECIP_INFO_get0_alg (PKCS7_RECIP_INFO * ri, X509_ALGOR ** penc)
Definition at line 417 of file pk7_lib.c.
References PKCS7_RECIP_INFO::key_enc_algor.
PKCS7_RECIP_INFO_set()
int PKCS7_RECIP_INFO_set (PKCS7_RECIP_INFO * p7i, X509 * x509)
Definition at line 463 of file pk7_lib.c.
Referenced by PKCS7_add_recipient().
PKCS7_set0_type_other()
int PKCS7_set0_type_other (PKCS7 * p7, int type, ASN1_TYPE * other)
Definition at line 179 of file pk7_lib.c.
References PKCS7::d, OBJ_nid2obj(), PKCS7::other, and PKCS7::type.
PKCS7_set_cipher()
int PKCS7_set_cipher (PKCS7 * p7, const EVP_CIPHER * cipher)
Definition at line 518 of file pk7_lib.c.
PKCS7_set_content()
int PKCS7_set_content (PKCS7 * p7, PKCS7 * p7_data)
Definition at line 80 of file pk7_lib.c.
References PKCS7_SIGNED::contents, PKCS7_DIGEST::contents, PKCS7::d, PKCS7::digest, NID_pkcs7_data, NID_pkcs7_digest, NID_pkcs7_encrypted, NID_pkcs7_enveloped, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, OBJ_obj2nid(), PKCS7_F_PKCS7_SET_CONTENT, PKCS7_R_UNSUPPORTED_CONTENT_TYPE, PKCS7err, PKCS7::sign, and PKCS7::type.
PKCS7_set_digest()
int PKCS7_set_digest (PKCS7 * p7, const EVP_MD * md)
Definition at line 378 of file pk7_lib.c.
PKCS7_set_type()
int PKCS7_set_type (PKCS7 * p7, int type)
Definition at line 107 of file pk7_lib.c.
References ASN1_INTEGER_set(), PKCS7_ENC_CONTENT::content_type, PKCS7::d, PKCS7::data, PKCS7::digest, PKCS7_ENVELOPE::enc_data, PKCS7_SIGN_ENVELOPE::enc_data, PKCS7_ENCRYPT::enc_data, PKCS7::encrypted, PKCS7::enveloped, NID_pkcs7_data, NID_pkcs7_digest, NID_pkcs7_encrypted, NID_pkcs7_enveloped, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, NULL, obj, OBJ_nid2obj(), PKCS7_F_PKCS7_SET_TYPE, PKCS7_R_UNSUPPORTED_CONTENT_TYPE, PKCS7err, PKCS7::sign, PKCS7::signed_and_enveloped, PKCS7::type, PKCS7_SIGNED::version, PKCS7_ENVELOPE::version, PKCS7_SIGN_ENVELOPE::version, PKCS7_DIGEST::version, and PKCS7_ENCRYPT::version.
Referenced by PKCS12_pack_p7encdata(), and PKCS7_sign().
PKCS7_SIGNER_INFO_get0_algs()
void PKCS7_SIGNER_INFO_get0_algs (PKCS7_SIGNER_INFO * si, EVP_PKEY ** pk, X509_ALGOR ** pdig, X509_ALGOR ** psig)
Definition at line 406 of file pk7_lib.c.
References PKCS7_SIGNER_INFO::digest_alg, PKCS7_SIGNER_INFO::digest_enc_alg, and PKCS7_SIGNER_INFO::pkey.
PKCS7_SIGNER_INFO_set()
int PKCS7_SIGNER_INFO_set (PKCS7_SIGNER_INFO * p7i, X509 * x509, EVP_PKEY * pkey, const EVP_MD * dgst)
Definition at line 304 of file pk7_lib.c.
Referenced by PKCS7_add_signature().
PKCS7_stream()
int PKCS7_stream (unsigned char *** boundary, PKCS7 * p7)
Definition at line 548 of file pk7_lib.c.
References ASN1_STRING_FLAG_NDEF, PKCS7_SIGNED::contents, PKCS7::d, PKCS7::data, PKCS7_ENC_CONTENT::enc_data, PKCS7_ENVELOPE::enc_data, PKCS7_SIGN_ENVELOPE::enc_data, PKCS7::enveloped, NID_pkcs7_data, NID_pkcs7_enveloped, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, NULL, OBJ_obj2nid(), PKCS7::sign, PKCS7::signed_and_enveloped, and PKCS7::type.
STACK_OF()
STACK_OF (PKCS7_SIGNER_INFO)
Definition at line 394 of file pk7_lib.c.
References PKCS7::d, NULL, PKCS7_type_is_signed, PKCS7_type_is_signedAndEnveloped, PKCS7::ptr, PKCS7::sign, and PKCS7::signed_and_enveloped.
Referenced by PKCS7_add_certificate(), PKCS7_add_crl(), PKCS7_add_recipient_info(), and PKCS7_add_signer().