crypto/pkcs7/pk7_doit.c File Reference
pk7_doit.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/rand.h>
#include <openssl/objects.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/err.h>
Functions
BIO * PKCS7_dataInit (PKCS7 *p7, BIO *bio)
BIO * PKCS7_dataDecode (PKCS7 *p7, EVP_PKEY *pkey, BIO *in_bio, X509 *pcert)
int PKCS7_dataFinal (PKCS7 *p7, BIO *bio)
int PKCS7_SIGNER_INFO_sign (PKCS7_SIGNER_INFO *si)
int PKCS7_dataVerify (X509_STORE *cert_store, X509_STORE_CTX *ctx, BIO *bio, PKCS7 *p7, PKCS7_SIGNER_INFO *si)
int PKCS7_signatureVerify (BIO *bio, PKCS7 *p7, PKCS7_SIGNER_INFO *si, X509 *x509)
PKCS7_ISSUER_AND_SERIAL * PKCS7_get_issuer_and_serial (PKCS7 *p7, int idx)
ASN1_TYPE * PKCS7_get_signed_attribute (PKCS7_SIGNER_INFO *si, int nid)
ASN1_TYPE * PKCS7_get_attribute (PKCS7_SIGNER_INFO *si, int nid)
ASN1_OCTET_STRING * PKCS7_digest_from_attributes (STACK_OF(X509_ATTRIBUTE) *sk)
int PKCS7_set_signed_attributes (PKCS7_SIGNER_INFO *p7si, STACK_OF(X509_ATTRIBUTE) *sk)
int PKCS7_set_attributes (PKCS7_SIGNER_INFO *p7si, STACK_OF(X509_ATTRIBUTE) *sk)
int PKCS7_add_signed_attribute (PKCS7_SIGNER_INFO *p7si, int nid, int atrtype, void *value)
int PKCS7_add_attribute (PKCS7_SIGNER_INFO *p7si, int nid, int atrtype, void *value)
Function Documentation
PKCS7_add_attribute()
int PKCS7_add_attribute (PKCS7_SIGNER_INFO * p7si, int nid, int atrtype, void * value)
Definition at line 1136 of file pk7_doit.c.
PKCS7_add_signed_attribute()
int PKCS7_add_signed_attribute (PKCS7_SIGNER_INFO * p7si, int nid, int atrtype, void * value)
Definition at line 1130 of file pk7_doit.c.
Referenced by PKCS7_add0_attrib_signing_time(), PKCS7_add_attrib_content_type(), and PKCS7_add_attrib_smimecap().
PKCS7_dataDecode()
BIO* PKCS7_dataDecode (PKCS7 * p7, EVP_PKEY * pkey, BIO * in_bio, X509 * pcert)
Definition at line 354 of file pk7_doit.c.
PKCS7_dataFinal()
int PKCS7_dataFinal (PKCS7 * p7, BIO * bio)
Definition at line 639 of file pk7_doit.c.
References PKCS7::d, PKCS7::data, PKCS7_ENC_CONTENT::enc_data, PKCS7_ENVELOPE::enc_data, PKCS7_SIGN_ENVELOPE::enc_data, PKCS7::enveloped, ERR_R_MALLOC_FAILURE, EVP_MD_CTX_new(), NID_pkcs7_data, NID_pkcs7_enveloped, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, NULL, OBJ_obj2nid(), PKCS7_F_PKCS7_DATAFINAL, PKCS7_R_INVALID_NULL_POINTER, PKCS7_R_NO_CONTENT, PKCS7_S_HEADER, PKCS7err, PKCS7::ptr, PKCS7::sign, PKCS7::signed_and_enveloped, STACK_OF, PKCS7::state, and PKCS7::type.
PKCS7_dataInit()
BIO* PKCS7_dataInit (PKCS7 * p7, BIO * bio)
Definition at line 193 of file pk7_doit.c.
PKCS7_dataVerify()
int PKCS7_dataVerify (X509_STORE * cert_store, X509_STORE_CTX * ctx, BIO * bio, PKCS7 * p7, PKCS7_SIGNER_INFO * si)
Definition at line 876 of file pk7_doit.c.
References STACK_OF.
PKCS7_digest_from_attributes()
ASN1_OCTET_STRING* PKCS7_digest_from_attributes (STACK_OF(X509_ATTRIBUTE) * sk)
Definition at line 1084 of file pk7_doit.c.
Referenced by PKCS7_signatureVerify().
PKCS7_get_attribute()
ASN1_TYPE* PKCS7_get_attribute (PKCS7_SIGNER_INFO * si, int nid)
Definition at line 1070 of file pk7_doit.c.
PKCS7_get_issuer_and_serial()
PKCS7_ISSUER_AND_SERIAL* PKCS7_get_issuer_and_serial (PKCS7 * p7, int idx)
Definition at line 1045 of file pk7_doit.c.
PKCS7_get_signed_attribute()
ASN1_TYPE* PKCS7_get_signed_attribute (PKCS7_SIGNER_INFO * si, int nid)
Definition at line 1065 of file pk7_doit.c.
Referenced by PKCS7_add_attrib_content_type(), and STACK_OF().
PKCS7_set_attributes()
int PKCS7_set_attributes (PKCS7_SIGNER_INFO * p7si, STACK_OF(X509_ATTRIBUTE) * sk)
Definition at line 1111 of file pk7_doit.c.
References NULL, and X509_ATTRIBUTE_dup().
PKCS7_set_signed_attributes()
int PKCS7_set_signed_attributes (PKCS7_SIGNER_INFO * p7si, STACK_OF(X509_ATTRIBUTE) * sk)
Definition at line 1092 of file pk7_doit.c.
References NULL, and X509_ATTRIBUTE_dup().
PKCS7_signatureVerify()
int PKCS7_signatureVerify (BIO * bio, PKCS7 * p7, PKCS7_SIGNER_INFO * si, X509 * x509)
Definition at line 933 of file pk7_doit.c.
References ASN1_item_i2d(), ASN1_ITEM_rptr, BIO_find_type(), BIO_get_md_ctx, BIO_next(), BIO_TYPE_MD, PKCS7_SIGNER_INFO::digest_alg, PKCS7_SIGNER_INFO::enc_digest, ERR_R_ASN1_LIB, ERR_R_INTERNAL_ERROR, ERR_R_MALLOC_FAILURE, EVP_DigestFinal_ex(), EVP_get_digestbynid, EVP_MAX_MD_SIZE, EVP_MD_CTX_copy_ex(), EVP_MD_CTX_free(), EVP_MD_CTX_md(), EVP_MD_CTX_new(), EVP_MD_CTX_type, EVP_MD_pkey_type(), EVP_VerifyFinal(), EVP_VerifyInit_ex, EVP_VerifyUpdate, NULL, OBJ_obj2nid(), OPENSSL_free, PKCS7_digest_from_attributes(), PKCS7_F_PKCS7_SIGNATUREVERIFY, PKCS7_R_DIGEST_FAILURE, PKCS7_R_SIGNATURE_FAILURE, PKCS7_R_UNABLE_TO_FIND_MESSAGE_DIGEST, PKCS7_R_WRONG_PKCS7_TYPE, PKCS7_type_is_signed, PKCS7_type_is_signedAndEnveloped, PKCS7err, STACK_OF, and X509_get0_pubkey().
PKCS7_SIGNER_INFO_sign()
int PKCS7_SIGNER_INFO_sign (PKCS7_SIGNER_INFO * si)
Definition at line 813 of file pk7_doit.c.