crypto/pkcs7/pk7_attr.c File Reference
pk7_attr.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <openssl/bio.h>
#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include <openssl/pem.h>
#include <openssl/pkcs7.h>
#include <openssl/x509.h>
#include <openssl/err.h>
Functions
int PKCS7_add_attrib_smimecap (PKCS7_SIGNER_INFO *si, STACK_OF(X509_ALGOR) *cap)
STACK_OF (X509_ALGOR)
int PKCS7_simple_smimecap (STACK_OF(X509_ALGOR) *sk, int nid, int arg)
int PKCS7_add_attrib_content_type (PKCS7_SIGNER_INFO *si, ASN1_OBJECT *coid)
int PKCS7_add0_attrib_signing_time (PKCS7_SIGNER_INFO *si, ASN1_TIME *t)
int PKCS7_add1_attrib_digest (PKCS7_SIGNER_INFO *si, const unsigned char *md, int mdlen)
Function Documentation
PKCS7_add0_attrib_signing_time()
int PKCS7_add0_attrib_signing_time (PKCS7_SIGNER_INFO * si, ASN1_TIME * t)
Definition at line 96 of file pk7_attr.c.
References ERR_R_MALLOC_FAILURE, NID_pkcs9_signingTime, NULL, PKCS7_add_signed_attribute(), PKCS7_F_PKCS7_ADD0_ATTRIB_SIGNING_TIME, PKCS7err, V_ASN1_UTCTIME, and X509_gmtime_adj().
PKCS7_add1_attrib_digest()
int PKCS7_add1_attrib_digest (PKCS7_SIGNER_INFO * si, const unsigned char * md, int mdlen)
Definition at line 107 of file pk7_attr.c.
PKCS7_add_attrib_content_type()
int PKCS7_add_attrib_content_type (PKCS7_SIGNER_INFO * si, ASN1_OBJECT * coid)
Definition at line 86 of file pk7_attr.c.
References NID_pkcs7_data, NID_pkcs9_contentType, OBJ_nid2obj(), PKCS7_add_signed_attribute(), PKCS7_get_signed_attribute(), and V_ASN1_OBJECT.
PKCS7_add_attrib_smimecap()
int PKCS7_add_attrib_smimecap (PKCS7_SIGNER_INFO * si, STACK_OF(X509_ALGOR) * cap)
Definition at line 20 of file pk7_attr.c.
References ASN1_item_i2d(), ASN1_ITEM_rptr, ASN1_STRING_new(), ERR_R_MALLOC_FAILURE, NID_SMIMECapabilities, NULL, PKCS7_add_signed_attribute(), PKCS7_F_PKCS7_ADD_ATTRIB_SMIMECAP, PKCS7err, seq, and V_ASN1_SEQUENCE.
PKCS7_simple_smimecap()
int PKCS7_simple_smimecap (STACK_OF(X509_ALGOR) * sk, int nid, int arg)
Definition at line 50 of file pk7_attr.c.
STACK_OF()
STACK_OF (X509_ALGOR)
Definition at line 35 of file pk7_attr.c.
References ASN1_item_d2i(), ASN1_ITEM_rptr, NID_SMIMECapabilities, NULL, PKCS7_get_signed_attribute(), ASN1_TYPE::sequence, STACK_OF(), ASN1_TYPE::type, V_ASN1_SEQUENCE, and ASN1_TYPE::value.
Referenced by STACK_OF().