include/openssl/pkcs12.h File Reference
pkcs12.h File Reference
#include <openssl/bio.h>
#include <openssl/x509.h>
Macros
#define PKCS12_KEY_ID 1
#define PKCS12_IV_ID 2
#define PKCS12_MAC_ID 3
#define PKCS12_DEFAULT_ITER PKCS5_DEFAULT_ITER
#define PKCS12_MAC_KEY_LENGTH 20
#define PKCS12_SALT_LEN 8
#define PKCS12_key_gen PKCS12_key_gen_utf8
#define PKCS12_add_friendlyname PKCS12_add_friendlyname_utf8
#define KEY_EX 0x10
#define KEY_SIG 0x80
#define PKCS12_ERROR 0
#define PKCS12_OK 1
#define M_PKCS12_bag_type PKCS12_bag_type
#define M_PKCS12_cert_bag_type PKCS12_cert_bag_type
#define M_PKCS12_crl_bag_type PKCS12_cert_bag_type
#define PKCS12_certbag2x509 PKCS12_SAFEBAG_get1_cert
#define PKCS12_certbag2scrl PKCS12_SAFEBAG_get1_crl
#define PKCS12_bag_type PKCS12_SAFEBAG_get_nid
#define PKCS12_cert_bag_type PKCS12_SAFEBAG_get_bag_nid
#define PKCS12_x5092certbag PKCS12_SAFEBAG_create_cert
#define PKCS12_x509crl2certbag PKCS12_SAFEBAG_create_crl
#define PKCS12_MAKE_KEYBAG PKCS12_SAFEBAG_create0_p8inf
#define PKCS12_MAKE_SHKEYBAG PKCS12_SAFEBAG_create_pkcs8_encrypt
#define PKCS12_F_PKCS12_CREATE 105
#define PKCS12_F_PKCS12_GEN_MAC 107
#define PKCS12_F_PKCS12_INIT 109
#define PKCS12_F_PKCS12_ITEM_DECRYPT_D2I 106
#define PKCS12_F_PKCS12_ITEM_I2D_ENCRYPT 108
#define PKCS12_F_PKCS12_ITEM_PACK_SAFEBAG 117
#define PKCS12_F_PKCS12_KEY_GEN_ASC 110
#define PKCS12_F_PKCS12_KEY_GEN_UNI 111
#define PKCS12_F_PKCS12_KEY_GEN_UTF8 116
#define PKCS12_F_PKCS12_NEWPASS 128
#define PKCS12_F_PKCS12_PACK_P7DATA 114
#define PKCS12_F_PKCS12_PACK_P7ENCDATA 115
#define PKCS12_F_PKCS12_PARSE 118
#define PKCS12_F_PKCS12_PBE_CRYPT 119
#define PKCS12_F_PKCS12_PBE_KEYIVGEN 120
#define PKCS12_F_PKCS12_SAFEBAG_CREATE0_P8INF 112
#define PKCS12_F_PKCS12_SAFEBAG_CREATE0_PKCS8 113
#define PKCS12_F_PKCS12_SAFEBAG_CREATE_PKCS8_ENCRYPT 133
#define PKCS12_F_PKCS12_SETUP_MAC 122
#define PKCS12_F_PKCS12_SET_MAC 123
#define PKCS12_F_PKCS12_UNPACK_AUTHSAFES 130
#define PKCS12_F_PKCS12_UNPACK_P7DATA 131
#define PKCS12_F_PKCS12_VERIFY_MAC 126
#define PKCS12_F_PKCS8_ENCRYPT 125
#define PKCS12_F_PKCS8_SET0_PBE 132
#define PKCS12_R_CANT_PACK_STRUCTURE 100
#define PKCS12_R_CONTENT_TYPE_NOT_DATA 121
#define PKCS12_R_DECODE_ERROR 101
#define PKCS12_R_ENCODE_ERROR 102
#define PKCS12_R_ENCRYPT_ERROR 103
#define PKCS12_R_ERROR_SETTING_ENCRYPTED_DATA_TYPE 120
#define PKCS12_R_INVALID_NULL_ARGUMENT 104
#define PKCS12_R_INVALID_NULL_PKCS12_POINTER 105
#define PKCS12_R_IV_GEN_ERROR 106
#define PKCS12_R_KEY_GEN_ERROR 107
#define PKCS12_R_MAC_ABSENT 108
#define PKCS12_R_MAC_GENERATION_ERROR 109
#define PKCS12_R_MAC_SETUP_ERROR 110
#define PKCS12_R_MAC_STRING_SET_ERROR 111
#define PKCS12_R_MAC_VERIFY_FAILURE 113
#define PKCS12_R_PARSE_ERROR 114
#define PKCS12_R_PKCS12_ALGOR_CIPHERINIT_ERROR 115
#define PKCS12_R_PKCS12_CIPHERFINAL_ERROR 116
#define PKCS12_R_PKCS12_PBE_CRYPT_ERROR 117
#define PKCS12_R_UNKNOWN_DIGEST_ALGORITHM 118
#define PKCS12_R_UNSUPPORTED_PKCS12_MODE 119
Functions
ASN1_TYPE * PKCS8_get_attr (PKCS8_PRIV_KEY_INFO *p8, int attr_nid)
int PKCS12_mac_present (const PKCS12 *p12)
void PKCS12_get0_mac (const ASN1_OCTET_STRING **pmac, const X509_ALGOR **pmacalg, const ASN1_OCTET_STRING **psalt, const ASN1_INTEGER **piter, const PKCS12 *p12)
const ASN1_TYPE * PKCS12_SAFEBAG_get0_attr (const PKCS12_SAFEBAG *bag, int attr_nid)
const ASN1_OBJECT * PKCS12_SAFEBAG_get0_type (const PKCS12_SAFEBAG *bag)
int PKCS12_SAFEBAG_get_nid (const PKCS12_SAFEBAG *bag)
int PKCS12_SAFEBAG_get_bag_nid (const PKCS12_SAFEBAG *bag)
X509 * PKCS12_SAFEBAG_get1_cert (const PKCS12_SAFEBAG *bag)
X509_CRL * PKCS12_SAFEBAG_get1_crl (const PKCS12_SAFEBAG *bag)
const STACK_OF (PKCS12_SAFEBAG) *PKCS12_SAFEBAG_get0_safes(const PKCS12_SAFEBAG *bag)
const PKCS8_PRIV_KEY_INFO * PKCS12_SAFEBAG_get0_p8inf (const PKCS12_SAFEBAG *bag)
const X509_SIG * PKCS12_SAFEBAG_get0_pkcs8 (const PKCS12_SAFEBAG *bag)
PKCS12_SAFEBAG * PKCS12_SAFEBAG_create_cert (X509 *x509)
PKCS12_SAFEBAG * PKCS12_SAFEBAG_create_crl (X509_CRL *crl)
PKCS12_SAFEBAG * PKCS12_SAFEBAG_create0_p8inf (PKCS8_PRIV_KEY_INFO *p8)
PKCS12_SAFEBAG * PKCS12_SAFEBAG_create0_pkcs8 (X509_SIG *p8)
PKCS12_SAFEBAG * PKCS12_SAFEBAG_create_pkcs8_encrypt (int pbe_nid, const char *pass, int passlen, unsigned char *salt, int saltlen, int iter, PKCS8_PRIV_KEY_INFO *p8inf)
PKCS12_SAFEBAG * PKCS12_item_pack_safebag (void *obj, const ASN1_ITEM *it, int nid1, int nid2)
PKCS8_PRIV_KEY_INFO * PKCS8_decrypt (const X509_SIG *p8, const char *pass, int passlen)
PKCS8_PRIV_KEY_INFO * PKCS12_decrypt_skey (const PKCS12_SAFEBAG *bag, const char *pass, int passlen)
X509_SIG * PKCS8_encrypt (int pbe_nid, const EVP_CIPHER *cipher, const char *pass, int passlen, unsigned char *salt, int saltlen, int iter, PKCS8_PRIV_KEY_INFO *p8)
X509_SIG * PKCS8_set0_pbe (const char *pass, int passlen, PKCS8_PRIV_KEY_INFO *p8inf, X509_ALGOR *pbe)
PKCS7 * PKCS12_pack_p7data (STACK_OF(PKCS12_SAFEBAG) *sk)
PKCS7 * PKCS12_pack_p7encdata (int pbe_nid, const char *pass, int passlen, unsigned char *salt, int saltlen, int iter, STACK_OF(PKCS12_SAFEBAG) *bags)
int PKCS12_pack_authsafes (PKCS12 *p12, STACK_OF(PKCS7) *safes)
STACK_OF (PKCS7) *PKCS12_unpack_authsafes(const PKCS12 *p12)
int PKCS12_add_localkeyid (PKCS12_SAFEBAG *bag, unsigned char *name, int namelen)
int PKCS12_add_friendlyname_asc (PKCS12_SAFEBAG *bag, const char *name, int namelen)
int PKCS12_add_friendlyname_utf8 (PKCS12_SAFEBAG *bag, const char *name, int namelen)
int PKCS12_add_CSPName_asc (PKCS12_SAFEBAG *bag, const char *name, int namelen)
int PKCS12_add_friendlyname_uni (PKCS12_SAFEBAG *bag, const unsigned char *name, int namelen)
int PKCS8_add_keyusage (PKCS8_PRIV_KEY_INFO *p8, int usage)
ASN1_TYPE * PKCS12_get_attr_gen (const STACK_OF(X509_ATTRIBUTE) *attrs, int attr_nid)
char * PKCS12_get_friendlyname (PKCS12_SAFEBAG *bag)
const STACK_OF (X509_ATTRIBUTE) *PKCS12_SAFEBAG_get0_attrs(const PKCS12_SAFEBAG *bag)
unsigned char * PKCS12_pbe_crypt (const X509_ALGOR *algor, const char *pass, int passlen, const unsigned char *in, int inlen, unsigned char **data, int *datalen, int en_de)
void * PKCS12_item_decrypt_d2i (const X509_ALGOR *algor, const ASN1_ITEM *it, const char *pass, int passlen, const ASN1_OCTET_STRING *oct, int zbuf)
ASN1_OCTET_STRING * PKCS12_item_i2d_encrypt (X509_ALGOR *algor, const ASN1_ITEM *it, const char *pass, int passlen, void *obj, int zbuf)
PKCS12 * PKCS12_init (int mode)
int PKCS12_key_gen_asc (const char *pass, int passlen, unsigned char *salt, int saltlen, int id, int iter, int n, unsigned char *out, const EVP_MD *md_type)
int PKCS12_key_gen_uni (unsigned char *pass, int passlen, unsigned char *salt, int saltlen, int id, int iter, int n, unsigned char *out, const EVP_MD *md_type)
int PKCS12_key_gen_utf8 (const char *pass, int passlen, unsigned char *salt, int saltlen, int id, int iter, int n, unsigned char *out, const EVP_MD *md_type)
int PKCS12_PBE_keyivgen (EVP_CIPHER_CTX *ctx, const char *pass, int passlen, ASN1_TYPE *param, const EVP_CIPHER *cipher, const EVP_MD *md_type, int en_de)
int PKCS12_gen_mac (PKCS12 *p12, const char *pass, int passlen, unsigned char *mac, unsigned int *maclen)
int PKCS12_verify_mac (PKCS12 *p12, const char *pass, int passlen)
int PKCS12_set_mac (PKCS12 *p12, const char *pass, int passlen, unsigned char *salt, int saltlen, int iter, const EVP_MD *md_type)
int PKCS12_setup_mac (PKCS12 *p12, int iter, unsigned char *salt, int saltlen, const EVP_MD *md_type)
unsigned char * OPENSSL_asc2uni (const char *asc, int asclen, unsigned char **uni, int *unilen)
char * OPENSSL_uni2asc (const unsigned char *uni, int unilen)
unsigned char * OPENSSL_utf82uni (const char *asc, int asclen, unsigned char **uni, int *unilen)
char * OPENSSL_uni2utf8 (const unsigned char *uni, int unilen)
void PKCS12_PBE_add (void)
int PKCS12_parse (PKCS12 *p12, const char *pass, EVP_PKEY **pkey, X509 **cert, STACK_OF(X509) **ca)
PKCS12 * PKCS12_create (const char *pass, const char *name, EVP_PKEY *pkey, X509 *cert, STACK_OF(X509) *ca, int nid_key, int nid_cert, int iter, int mac_iter, int keytype)
PKCS12_SAFEBAG * PKCS12_add_cert (STACK_OF(PKCS12_SAFEBAG) **pbags, X509 *cert)
PKCS12_SAFEBAG * PKCS12_add_key (STACK_OF(PKCS12_SAFEBAG) **pbags, EVP_PKEY *key, int key_usage, int iter, int key_nid, const char *pass)
int PKCS12_add_safe (STACK_OF(PKCS7) **psafes, STACK_OF(PKCS12_SAFEBAG) *bags, int safe_nid, int iter, const char *pass)
PKCS12 * PKCS12_add_safes (STACK_OF(PKCS7) *safes, int p7_nid)
int i2d_PKCS12_bio (BIO *bp, PKCS12 *p12)
int i2d_PKCS12_fp (FILE *fp, PKCS12 *p12)
PKCS12 * d2i_PKCS12_bio (BIO *bp, PKCS12 **p12)
PKCS12 * d2i_PKCS12_fp (FILE *fp, PKCS12 **p12)
int PKCS12_newpass (PKCS12 *p12, const char *oldpass, const char *newpass)
int ERR_load_PKCS12_strings (void)
Variables
const char * pass
const char int passlen
Macro Definition Documentation
KEY_EX
#define KEY_EX 0x10
Definition at line 39 of file pkcs12.h.
KEY_SIG
#define KEY_SIG 0x80
Definition at line 40 of file pkcs12.h.
M_PKCS12_bag_type
#define M_PKCS12_bag_type PKCS12_bag_type
Definition at line 59 of file pkcs12.h.
M_PKCS12_cert_bag_type
#define M_PKCS12_cert_bag_type PKCS12_cert_bag_type
Definition at line 60 of file pkcs12.h.
M_PKCS12_crl_bag_type
#define M_PKCS12_crl_bag_type PKCS12_cert_bag_type
Definition at line 61 of file pkcs12.h.
PKCS12_add_friendlyname
#define PKCS12_add_friendlyname PKCS12_add_friendlyname_utf8
Definition at line 35 of file pkcs12.h.
Referenced by PKCS12_add_cert().
PKCS12_bag_type
#define PKCS12_bag_type PKCS12_SAFEBAG_get_nid
Definition at line 65 of file pkcs12.h.
PKCS12_cert_bag_type
#define PKCS12_cert_bag_type PKCS12_SAFEBAG_get_bag_nid
Definition at line 66 of file pkcs12.h.
PKCS12_certbag2scrl
#define PKCS12_certbag2scrl PKCS12_SAFEBAG_get1_crl
Definition at line 64 of file pkcs12.h.
PKCS12_certbag2x509
#define PKCS12_certbag2x509 PKCS12_SAFEBAG_get1_cert
Definition at line 63 of file pkcs12.h.
PKCS12_DEFAULT_ITER
#define PKCS12_DEFAULT_ITER PKCS5_DEFAULT_ITER
Definition at line 26 of file pkcs12.h.
PKCS12_ERROR
#define PKCS12_ERROR 0
Definition at line 52 of file pkcs12.h.
Referenced by PKCS12_set_mac(), and PKCS12_setup_mac().
PKCS12_F_PKCS12_CREATE
#define PKCS12_F_PKCS12_CREATE 105
Definition at line 230 of file pkcs12.h.
PKCS12_F_PKCS12_GEN_MAC
#define PKCS12_F_PKCS12_GEN_MAC 107
Definition at line 231 of file pkcs12.h.
PKCS12_F_PKCS12_INIT
#define PKCS12_F_PKCS12_INIT 109
Definition at line 232 of file pkcs12.h.
Referenced by PKCS12_init().
PKCS12_F_PKCS12_ITEM_DECRYPT_D2I
#define PKCS12_F_PKCS12_ITEM_DECRYPT_D2I 106
Definition at line 233 of file pkcs12.h.
PKCS12_F_PKCS12_ITEM_I2D_ENCRYPT
#define PKCS12_F_PKCS12_ITEM_I2D_ENCRYPT 108
Definition at line 234 of file pkcs12.h.
Referenced by PKCS12_item_i2d_encrypt().
PKCS12_F_PKCS12_ITEM_PACK_SAFEBAG
#define PKCS12_F_PKCS12_ITEM_PACK_SAFEBAG 117
Definition at line 235 of file pkcs12.h.
Referenced by PKCS12_item_pack_safebag().
PKCS12_F_PKCS12_KEY_GEN_ASC
#define PKCS12_F_PKCS12_KEY_GEN_ASC 110
Definition at line 236 of file pkcs12.h.
PKCS12_F_PKCS12_KEY_GEN_UNI
#define PKCS12_F_PKCS12_KEY_GEN_UNI 111
Definition at line 237 of file pkcs12.h.
PKCS12_F_PKCS12_KEY_GEN_UTF8
#define PKCS12_F_PKCS12_KEY_GEN_UTF8 116
Definition at line 238 of file pkcs12.h.
PKCS12_F_PKCS12_NEWPASS
#define PKCS12_F_PKCS12_NEWPASS 128
Definition at line 239 of file pkcs12.h.
Referenced by PKCS12_newpass().
PKCS12_F_PKCS12_PACK_P7DATA
#define PKCS12_F_PKCS12_PACK_P7DATA 114
Definition at line 240 of file pkcs12.h.
Referenced by PKCS12_pack_p7data().
PKCS12_F_PKCS12_PACK_P7ENCDATA
#define PKCS12_F_PKCS12_PACK_P7ENCDATA 115
Definition at line 241 of file pkcs12.h.
Referenced by PKCS12_pack_p7encdata().
PKCS12_F_PKCS12_PARSE
#define PKCS12_F_PKCS12_PARSE 118
Definition at line 242 of file pkcs12.h.
PKCS12_F_PKCS12_PBE_CRYPT
#define PKCS12_F_PKCS12_PBE_CRYPT 119
Definition at line 243 of file pkcs12.h.
PKCS12_F_PKCS12_PBE_KEYIVGEN
#define PKCS12_F_PKCS12_PBE_KEYIVGEN 120
Definition at line 244 of file pkcs12.h.
PKCS12_F_PKCS12_SAFEBAG_CREATE0_P8INF
#define PKCS12_F_PKCS12_SAFEBAG_CREATE0_P8INF 112
Definition at line 245 of file pkcs12.h.
Referenced by PKCS12_SAFEBAG_create0_p8inf().
PKCS12_F_PKCS12_SAFEBAG_CREATE0_PKCS8
#define PKCS12_F_PKCS12_SAFEBAG_CREATE0_PKCS8 113
Definition at line 246 of file pkcs12.h.
Referenced by PKCS12_SAFEBAG_create0_pkcs8().
PKCS12_F_PKCS12_SAFEBAG_CREATE_PKCS8_ENCRYPT
#define PKCS12_F_PKCS12_SAFEBAG_CREATE_PKCS8_ENCRYPT 133
Definition at line 247 of file pkcs12.h.
Referenced by PKCS12_SAFEBAG_create_pkcs8_encrypt().
PKCS12_F_PKCS12_SET_MAC
#define PKCS12_F_PKCS12_SET_MAC 123
Definition at line 249 of file pkcs12.h.
Referenced by PKCS12_set_mac().
PKCS12_F_PKCS12_SETUP_MAC
#define PKCS12_F_PKCS12_SETUP_MAC 122
Definition at line 248 of file pkcs12.h.
Referenced by PKCS12_setup_mac().
PKCS12_F_PKCS12_UNPACK_AUTHSAFES
#define PKCS12_F_PKCS12_UNPACK_AUTHSAFES 130
Definition at line 250 of file pkcs12.h.
Referenced by STACK_OF().
PKCS12_F_PKCS12_UNPACK_P7DATA
#define PKCS12_F_PKCS12_UNPACK_P7DATA 131
Definition at line 251 of file pkcs12.h.
Referenced by STACK_OF().
PKCS12_F_PKCS12_VERIFY_MAC
#define PKCS12_F_PKCS12_VERIFY_MAC 126
Definition at line 252 of file pkcs12.h.
Referenced by PKCS12_verify_mac().
PKCS12_F_PKCS8_ENCRYPT
#define PKCS12_F_PKCS8_ENCRYPT 125
Definition at line 253 of file pkcs12.h.
PKCS12_F_PKCS8_SET0_PBE
#define PKCS12_F_PKCS8_SET0_PBE 132
Definition at line 254 of file pkcs12.h.
Referenced by PKCS8_set0_pbe().
PKCS12_IV_ID
#define PKCS12_IV_ID 2
Definition at line 21 of file pkcs12.h.
PKCS12_key_gen
#define PKCS12_key_gen PKCS12_key_gen_utf8
Definition at line 34 of file pkcs12.h.
PKCS12_KEY_ID
#define PKCS12_KEY_ID 1
Definition at line 20 of file pkcs12.h.
PKCS12_MAC_ID
#define PKCS12_MAC_ID 3
Definition at line 22 of file pkcs12.h.
PKCS12_MAC_KEY_LENGTH
#define PKCS12_MAC_KEY_LENGTH 20
Definition at line 29 of file pkcs12.h.
PKCS12_MAKE_KEYBAG
#define PKCS12_MAKE_KEYBAG PKCS12_SAFEBAG_create0_p8inf
Definition at line 69 of file pkcs12.h.
PKCS12_MAKE_SHKEYBAG
#define PKCS12_MAKE_SHKEYBAG PKCS12_SAFEBAG_create_pkcs8_encrypt
Definition at line 70 of file pkcs12.h.
PKCS12_OK
#define PKCS12_OK 1
Definition at line 53 of file pkcs12.h.
PKCS12_R_CANT_PACK_STRUCTURE
#define PKCS12_R_CANT_PACK_STRUCTURE 100
Definition at line 257 of file pkcs12.h.
Referenced by PKCS12_pack_p7data().
PKCS12_R_CONTENT_TYPE_NOT_DATA
#define PKCS12_R_CONTENT_TYPE_NOT_DATA 121
Definition at line 258 of file pkcs12.h.
Referenced by STACK_OF().
PKCS12_R_DECODE_ERROR
#define PKCS12_R_DECODE_ERROR 101
Definition at line 259 of file pkcs12.h.
PKCS12_R_ENCODE_ERROR
#define PKCS12_R_ENCODE_ERROR 102
Definition at line 260 of file pkcs12.h.
Referenced by PKCS12_item_i2d_encrypt().
PKCS12_R_ENCRYPT_ERROR
#define PKCS12_R_ENCRYPT_ERROR 103
Definition at line 261 of file pkcs12.h.
Referenced by PKCS12_item_i2d_encrypt(), PKCS12_pack_p7encdata(), and PKCS8_set0_pbe().
PKCS12_R_ERROR_SETTING_ENCRYPTED_DATA_TYPE
#define PKCS12_R_ERROR_SETTING_ENCRYPTED_DATA_TYPE 120
Definition at line 262 of file pkcs12.h.
Referenced by PKCS12_pack_p7encdata().
PKCS12_R_INVALID_NULL_ARGUMENT
#define PKCS12_R_INVALID_NULL_ARGUMENT 104
Definition at line 263 of file pkcs12.h.
PKCS12_R_INVALID_NULL_PKCS12_POINTER
#define PKCS12_R_INVALID_NULL_PKCS12_POINTER 105
Definition at line 264 of file pkcs12.h.
Referenced by PKCS12_newpass().
PKCS12_R_IV_GEN_ERROR
#define PKCS12_R_IV_GEN_ERROR 106
Definition at line 265 of file pkcs12.h.
PKCS12_R_KEY_GEN_ERROR
#define PKCS12_R_KEY_GEN_ERROR 107
Definition at line 266 of file pkcs12.h.
PKCS12_R_MAC_ABSENT
#define PKCS12_R_MAC_ABSENT 108
Definition at line 267 of file pkcs12.h.
Referenced by PKCS12_verify_mac().
PKCS12_R_MAC_GENERATION_ERROR
#define PKCS12_R_MAC_GENERATION_ERROR 109
Definition at line 268 of file pkcs12.h.
PKCS12_R_MAC_SETUP_ERROR
#define PKCS12_R_MAC_SETUP_ERROR 110
Definition at line 269 of file pkcs12.h.
Referenced by PKCS12_set_mac().
PKCS12_R_MAC_STRING_SET_ERROR
#define PKCS12_R_MAC_STRING_SET_ERROR 111
Definition at line 270 of file pkcs12.h.
PKCS12_R_MAC_VERIFY_FAILURE
#define PKCS12_R_MAC_VERIFY_FAILURE 113
Definition at line 271 of file pkcs12.h.
Referenced by PKCS12_newpass().
PKCS12_R_PARSE_ERROR
#define PKCS12_R_PARSE_ERROR 114
Definition at line 272 of file pkcs12.h.
PKCS12_R_PKCS12_ALGOR_CIPHERINIT_ERROR
#define PKCS12_R_PKCS12_ALGOR_CIPHERINIT_ERROR 115
Definition at line 273 of file pkcs12.h.
PKCS12_R_PKCS12_CIPHERFINAL_ERROR
#define PKCS12_R_PKCS12_CIPHERFINAL_ERROR 116
Definition at line 274 of file pkcs12.h.
PKCS12_R_PKCS12_PBE_CRYPT_ERROR
#define PKCS12_R_PKCS12_PBE_CRYPT_ERROR 117
Definition at line 275 of file pkcs12.h.
PKCS12_R_UNKNOWN_DIGEST_ALGORITHM
#define PKCS12_R_UNKNOWN_DIGEST_ALGORITHM 118
Definition at line 276 of file pkcs12.h.
PKCS12_R_UNSUPPORTED_PKCS12_MODE
#define PKCS12_R_UNSUPPORTED_PKCS12_MODE 119
Definition at line 277 of file pkcs12.h.
Referenced by PKCS12_init().
PKCS12_SALT_LEN
#define PKCS12_SALT_LEN 8
Definition at line 31 of file pkcs12.h.
Referenced by PKCS12_setup_mac().
PKCS12_x5092certbag
#define PKCS12_x5092certbag PKCS12_SAFEBAG_create_cert
Definition at line 67 of file pkcs12.h.
PKCS12_x509crl2certbag
#define PKCS12_x509crl2certbag PKCS12_SAFEBAG_create_crl
Definition at line 68 of file pkcs12.h.
Function Documentation
d2i_PKCS12_bio()
PKCS12* d2i_PKCS12_bio (BIO * bp, PKCS12 ** p12)
Definition at line 227 of file p12_utl.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_PKCS12_fp()
PKCS12* d2i_PKCS12_fp (FILE * fp, PKCS12 ** p12)
Definition at line 233 of file p12_utl.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
ERR_load_PKCS12_strings()
int ERR_load_PKCS12_strings (void)
Definition at line 85 of file pk12err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
i2d_PKCS12_bio()
int i2d_PKCS12_bio (BIO * bp, PKCS12 * p12)
Definition at line 215 of file p12_utl.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_PKCS12_fp()
int i2d_PKCS12_fp (FILE * fp, PKCS12 * p12)
Definition at line 221 of file p12_utl.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
OPENSSL_asc2uni()
unsigned char* OPENSSL_asc2uni (const char * asc, int asclen, unsigned char ** uni, int * unilen)
Definition at line 16 of file p12_utl.c.
References NULL, and OPENSSL_malloc.
OPENSSL_uni2asc()
char* OPENSSL_uni2asc (const unsigned char * uni, int unilen)
Definition at line 41 of file p12_utl.c.
References NULL, and OPENSSL_malloc.
Referenced by print_attribs().
OPENSSL_uni2utf8()
char* OPENSSL_uni2utf8 (const unsigned char * uni, int unilen)
Definition at line 171 of file p12_utl.c.
References NULL.
Referenced by PKCS12_get_friendlyname().
OPENSSL_utf82uni()
unsigned char* OPENSSL_utf82uni (const char * asc, int asclen, unsigned char ** uni, int * unilen)
Definition at line 70 of file p12_utl.c.
PKCS12_add_cert()
PKCS12_SAFEBAG* PKCS12_add_cert (STACK_OF(PKCS12_SAFEBAG) ** pbags, X509 * cert)
Definition at line 134 of file p12_crt.c.
References NULL, PKCS12_add_friendlyname, PKCS12_add_localkeyid(), PKCS12_SAFEBAG_create_cert(), X509_alias_get0(), and X509_keyid_get0().
PKCS12_add_CSPName_asc()
int PKCS12_add_CSPName_asc (PKCS12_SAFEBAG * bag, const char * name, int namelen)
Definition at line 68 of file p12_attr.c.
References MBSTRING_ASC, and NID_ms_csp_name.
PKCS12_add_friendlyname_asc()
int PKCS12_add_friendlyname_asc (PKCS12_SAFEBAG * bag, const char * name, int namelen)
Definition at line 38 of file p12_attr.c.
References MBSTRING_ASC, and NID_friendlyName.
PKCS12_add_friendlyname_uni()
int PKCS12_add_friendlyname_uni (PKCS12_SAFEBAG * bag, const unsigned char * name, int namelen)
Definition at line 58 of file p12_attr.c.
References MBSTRING_BMP, and NID_friendlyName.
PKCS12_add_friendlyname_utf8()
int PKCS12_add_friendlyname_utf8 (PKCS12_SAFEBAG * bag, const char * name, int namelen)
Definition at line 48 of file p12_attr.c.
References MBSTRING_UTF8, and NID_friendlyName.
PKCS12_add_key()
PKCS12_SAFEBAG* PKCS12_add_key (STACK_OF(PKCS12_SAFEBAG) ** pbags, EVP_PKEY * key, int key_usage, int iter, int key_nid, const char * pass)
Definition at line 171 of file p12_crt.c.
References EVP_PKEY2PKCS8(), NULL, PKCS12_SAFEBAG_create0_p8inf(), PKCS12_SAFEBAG_create_pkcs8_encrypt(), and PKCS8_add_keyusage().
PKCS12_add_localkeyid()
int PKCS12_add_localkeyid (PKCS12_SAFEBAG * bag, unsigned char * name, int namelen)
Definition at line 17 of file p12_attr.c.
References NID_localKeyID, and V_ASN1_OCTET_STRING.
Referenced by PKCS12_add_cert().
PKCS12_add_safe()
int PKCS12_add_safe (STACK_OF(PKCS7) ** psafes, STACK_OF(PKCS12_SAFEBAG) * bags, int safe_nid, int iter, const char * pass)
Definition at line 205 of file p12_crt.c.
References NID_pbe_WithSHA1And3_Key_TripleDES_CBC, NID_pbe_WithSHA1And40BitRC2_CBC, NULL, PKCS12_pack_p7data(), and PKCS12_pack_p7encdata().
PKCS12_add_safes()
PKCS12* PKCS12_add_safes (STACK_OF(PKCS7) * safes, int p7_nid)
Definition at line 274 of file p12_crt.c.
References NID_pkcs7_data, NULL, PKCS12_init(), and PKCS12_pack_authsafes().
PKCS12_create()
PKCS12* PKCS12_create (const char * pass, const char * name, EVP_PKEY * pkey, X509 * cert, STACK_OF(X509) * ca, int nid_key, int nid_cert, int iter, int mac_iter, int keytype)
Definition at line 31 of file p12_crt.c.
PKCS12_decrypt_skey()
PKCS8_PRIV_KEY_INFO* PKCS12_decrypt_skey (const PKCS12_SAFEBAG * bag, const char * pass, int passlen)
Definition at line 141 of file p12_add.c.
References PKCS8_decrypt().
PKCS12_gen_mac()
int PKCS12_gen_mac (PKCS12 * p12, const char * pass, int passlen, unsigned char * mac, unsigned int * maclen)
Definition at line 139 of file p12_mutl.c.
PKCS12_get0_mac()
void PKCS12_get0_mac (const ASN1_OCTET_STRING ** pmac, const X509_ALGOR ** pmacalg, const ASN1_OCTET_STRING ** psalt, const ASN1_INTEGER ** piter, const PKCS12 * p12)
Definition at line 23 of file p12_mutl.c.
References NULL, and X509_SIG_get0().
PKCS12_get_attr_gen()
ASN1_TYPE* PKCS12_get_attr_gen (const STACK_OF(X509_ATTRIBUTE) * attrs, int attr_nid)
Definition at line 77 of file p12_attr.c.
References X509_ATTRIBUTE_get0_type(), X509at_get_attr(), and X509at_get_attr_by_NID().
Referenced by PKCS12_get_attr(), PKCS12_SAFEBAG_get0_attr(), and PKCS8_get_attr().
PKCS12_get_friendlyname()
char* PKCS12_get_friendlyname (PKCS12_SAFEBAG * bag)
Definition at line 87 of file p12_attr.c.
References ASN1_TYPE::bmpstring, NID_friendlyName, NULL, OPENSSL_uni2utf8(), PKCS12_SAFEBAG_get0_attr(), ASN1_TYPE::type, V_ASN1_BMPSTRING, and ASN1_TYPE::value.
PKCS12_init()
PKCS12* PKCS12_init (int mode)
Definition at line 17 of file p12_init.c.
References ASN1_INTEGER_set(), ERR_R_MALLOC_FAILURE, NID_pkcs7_data, NULL, OBJ_nid2obj(), PKCS12_F_PKCS12_INIT, PKCS12_R_UNSUPPORTED_PKCS12_MODE, and PKCS12err.
Referenced by PKCS12_add_safes().
PKCS12_item_decrypt_d2i()
void* PKCS12_item_decrypt_d2i (const X509_ALGOR * algor, const ASN1_ITEM * it, const char * pass, int passlen, const ASN1_OCTET_STRING * oct, int zbuf)
Definition at line 82 of file p12_decr.c.
Referenced by PKCS12_pack_p7encdata(), and PKCS8_decrypt().
PKCS12_item_i2d_encrypt()
ASN1_OCTET_STRING* PKCS12_item_i2d_encrypt (X509_ALGOR * algor, const ASN1_ITEM * it, const char * pass, int passlen, void * obj, int zbuf)
Definition at line 124 of file p12_decr.c.
References ASN1_item_i2d(), ERR_R_MALLOC_FAILURE, in, inlen, NULL, OPENSSL_cleanse(), OPENSSL_free, PKCS12_F_PKCS12_ITEM_I2D_ENCRYPT, PKCS12_pbe_crypt(), PKCS12_R_ENCODE_ERROR, PKCS12_R_ENCRYPT_ERROR, and PKCS12err.
Referenced by PKCS12_pack_p7encdata(), and PKCS8_set0_pbe().
PKCS12_item_pack_safebag()
PKCS12_SAFEBAG* PKCS12_item_pack_safebag (void * obj, const ASN1_ITEM * it, int nid1, int nid2)
Definition at line 17 of file p12_add.c.
References ASN1_item_pack(), ERR_R_MALLOC_FAILURE, NULL, OBJ_nid2obj(), PKCS12_F_PKCS12_ITEM_PACK_SAFEBAG, and PKCS12err.
Referenced by PKCS12_SAFEBAG_create_cert(), and PKCS12_SAFEBAG_create_crl().
PKCS12_key_gen_asc()
int PKCS12_key_gen_asc (const char * pass, int passlen, unsigned char * salt, int saltlen, int id, int iter, int n, unsigned char * out, const EVP_MD * md_type)
Definition at line 30 of file p12_key.c.
PKCS12_key_gen_uni()
int PKCS12_key_gen_uni (unsigned char * pass, int passlen, unsigned char * salt, int saltlen, int id, int iter, int n, unsigned char * out, const EVP_MD * md_type)
Definition at line 76 of file p12_key.c.
PKCS12_key_gen_utf8()
int PKCS12_key_gen_utf8 (const char * pass, int passlen, unsigned char * salt, int saltlen, int id, int iter, int n, unsigned char * out, const EVP_MD * md_type)
Definition at line 53 of file p12_key.c.
PKCS12_mac_present()
int PKCS12_mac_present (const PKCS12 * p12)
Definition at line 18 of file p12_mutl.c.
PKCS12_newpass()
int PKCS12_newpass (PKCS12 * p12, const char * oldpass, const char * newpass)
Definition at line 32 of file p12_npas.c.
References PKCS12_F_PKCS12_NEWPASS, PKCS12_R_INVALID_NULL_PKCS12_POINTER, PKCS12_R_MAC_VERIFY_FAILURE, PKCS12_verify_mac(), and PKCS12err.
PKCS12_pack_authsafes()
int PKCS12_pack_authsafes (PKCS12 * p12, STACK_OF(PKCS7) * safes)
Definition at line 147 of file p12_add.c.
References ASN1_item_pack(), and ASN1_ITEM_rptr.
Referenced by PKCS12_add_safes().
PKCS12_pack_p7data()
PKCS7* PKCS12_pack_p7data (STACK_OF(PKCS12_SAFEBAG) * sk)
Definition at line 46 of file p12_add.c.
References ASN1_item_pack(), ASN1_ITEM_rptr, PKCS7::d, PKCS7::data, ERR_R_MALLOC_FAILURE, NID_pkcs7_data, NULL, OBJ_nid2obj(), PKCS12_F_PKCS12_PACK_P7DATA, PKCS12_R_CANT_PACK_STRUCTURE, PKCS12err, and PKCS7::type.
Referenced by PKCS12_add_safe().
PKCS12_pack_p7encdata()
PKCS7* PKCS12_pack_p7encdata (int pbe_nid, const char * pass, int passlen, unsigned char * salt, int saltlen, int iter, STACK_OF(PKCS12_SAFEBAG) * bags)
Definition at line 84 of file p12_add.c.
References PKCS7_ENC_CONTENT::algorithm, ASN1_ITEM_rptr, PKCS7::d, PKCS7_ENC_CONTENT::enc_data, PKCS7_ENCRYPT::enc_data, PKCS7::encrypted, ERR_R_MALLOC_FAILURE, EVP_get_cipherbynid, NID_pkcs7_encrypted, NULL, PKCS12_F_PKCS12_PACK_P7ENCDATA, PKCS12_item_decrypt_d2i(), PKCS12_item_i2d_encrypt(), PKCS12_R_ENCRYPT_ERROR, PKCS12_R_ERROR_SETTING_ENCRYPTED_DATA_TYPE, PKCS12err, PKCS5_pbe2_set(), PKCS5_pbe_set(), PKCS7_set_type(), PKCS7_type_is_encrypted, and STACK_OF().
Referenced by PKCS12_add_safe().
PKCS12_parse()
int PKCS12_parse (PKCS12 * p12, const char * pass, EVP_PKEY ** pkey, X509 ** cert, STACK_OF(X509) ** ca)
Definition at line 32 of file p12_kiss.c.
PKCS12_PBE_add()
void PKCS12_PBE_add (void)
Definition at line 16 of file p12_crpt.c.
PKCS12_pbe_crypt()
unsigned char* PKCS12_pbe_crypt (const X509_ALGOR * algor, const char * pass, int passlen, const unsigned char * in, int inlen, unsigned char ** data, int * datalen, int en_de)
Definition at line 23 of file p12_decr.c.
Referenced by PKCS12_item_i2d_encrypt().
PKCS12_PBE_keyivgen()
int PKCS12_PBE_keyivgen (EVP_CIPHER_CTX * ctx, const char * pass, int passlen, ASN1_TYPE * param, const EVP_CIPHER * cipher, const EVP_MD * md_type, int en_de)
Definition at line 20 of file p12_crpt.c.
PKCS12_SAFEBAG_create0_p8inf()
PKCS12_SAFEBAG* PKCS12_SAFEBAG_create0_p8inf (PKCS8_PRIV_KEY_INFO * p8)
Definition at line 108 of file p12_sbag.c.
References ERR_R_MALLOC_FAILURE, NID_keyBag, NULL, OBJ_nid2obj(), PKCS12_F_PKCS12_SAFEBAG_CREATE0_P8INF, and PKCS12err.
Referenced by PKCS12_add_key().
PKCS12_SAFEBAG_create0_pkcs8()
PKCS12_SAFEBAG* PKCS12_SAFEBAG_create0_pkcs8 (X509_SIG * p8)
Definition at line 123 of file p12_sbag.c.
References ERR_R_MALLOC_FAILURE, NID_pkcs8ShroudedKeyBag, NULL, OBJ_nid2obj(), PKCS12_F_PKCS12_SAFEBAG_CREATE0_PKCS8, and PKCS12err.
Referenced by PKCS12_SAFEBAG_create_pkcs8_encrypt().
PKCS12_SAFEBAG_create_cert()
PKCS12_SAFEBAG* PKCS12_SAFEBAG_create_cert (X509 * x509)
Definition at line 94 of file p12_sbag.c.
References ASN1_ITEM_rptr, NID_certBag, NID_x509Certificate, and PKCS12_item_pack_safebag().
Referenced by PKCS12_add_cert().
PKCS12_SAFEBAG_create_crl()
PKCS12_SAFEBAG* PKCS12_SAFEBAG_create_crl (X509_CRL * crl)
Definition at line 100 of file p12_sbag.c.
References ASN1_ITEM_rptr, NID_crlBag, NID_x509Crl, and PKCS12_item_pack_safebag().
PKCS12_SAFEBAG_create_pkcs8_encrypt()
PKCS12_SAFEBAG* PKCS12_SAFEBAG_create_pkcs8_encrypt (int pbe_nid, const char * pass, int passlen, unsigned char * salt, int saltlen, int iter, PKCS8_PRIV_KEY_INFO * p8inf)
Definition at line 137 of file p12_sbag.c.
References ERR_R_MALLOC_FAILURE, EVP_get_cipherbynid, NULL, PKCS12_F_PKCS12_SAFEBAG_CREATE_PKCS8_ENCRYPT, PKCS12_SAFEBAG_create0_pkcs8(), PKCS12err, and PKCS8_encrypt().
Referenced by PKCS12_add_key().
PKCS12_SAFEBAG_get0_attr()
const ASN1_TYPE* PKCS12_SAFEBAG_get0_attr (const PKCS12_SAFEBAG * bag, int attr_nid)
Definition at line 22 of file p12_sbag.c.
References PKCS12_get_attr_gen().
Referenced by PKCS12_get_friendlyname().
PKCS12_SAFEBAG_get0_p8inf()
const PKCS8_PRIV_KEY_INFO* PKCS12_SAFEBAG_get0_p8inf (const PKCS12_SAFEBAG * bag)
Definition at line 33 of file p12_sbag.c.
References NID_keyBag, NULL, and PKCS12_SAFEBAG_get_nid().
PKCS12_SAFEBAG_get0_pkcs8()
const X509_SIG* PKCS12_SAFEBAG_get0_pkcs8 (const PKCS12_SAFEBAG * bag)
Definition at line 40 of file p12_sbag.c.
References NID_pkcs8ShroudedKeyBag, NULL, and OBJ_obj2nid().
PKCS12_SAFEBAG_get0_type()
const ASN1_OBJECT* PKCS12_SAFEBAG_get0_type (const PKCS12_SAFEBAG * bag)
Definition at line 55 of file p12_sbag.c.
PKCS12_SAFEBAG_get1_cert()
X509* PKCS12_SAFEBAG_get1_cert (const PKCS12_SAFEBAG * bag)
Definition at line 74 of file p12_sbag.c.
References ASN1_ITEM_rptr, ASN1_item_unpack(), NID_certBag, NID_x509Certificate, NULL, OBJ_obj2nid(), and PKCS12_SAFEBAG_get_nid().
PKCS12_SAFEBAG_get1_crl()
X509_CRL* PKCS12_SAFEBAG_get1_crl (const PKCS12_SAFEBAG * bag)
Definition at line 84 of file p12_sbag.c.
References ASN1_ITEM_rptr, ASN1_item_unpack(), NID_crlBag, NID_x509Crl, NULL, OBJ_obj2nid(), and PKCS12_SAFEBAG_get_nid().
PKCS12_SAFEBAG_get_bag_nid()
int PKCS12_SAFEBAG_get_bag_nid (const PKCS12_SAFEBAG * bag)
Definition at line 65 of file p12_sbag.c.
References NID_certBag, NID_crlBag, NID_secretBag, OBJ_obj2nid(), and PKCS12_SAFEBAG_get_nid().
PKCS12_SAFEBAG_get_nid()
int PKCS12_SAFEBAG_get_nid (const PKCS12_SAFEBAG * bag)
Definition at line 60 of file p12_sbag.c.
References OBJ_obj2nid().
Referenced by PKCS12_SAFEBAG_get0_p8inf(), PKCS12_SAFEBAG_get1_cert(), PKCS12_SAFEBAG_get1_crl(), and PKCS12_SAFEBAG_get_bag_nid().
PKCS12_set_mac()
int PKCS12_set_mac (PKCS12 * p12, const char * pass, int passlen, unsigned char * salt, int saltlen, int iter, const EVP_MD * md_type)
Definition at line 171 of file p12_mutl.c.
References EVP_MAX_MD_SIZE, EVP_sha1(), PKCS12_ERROR, PKCS12_F_PKCS12_SET_MAC, PKCS12_R_MAC_SETUP_ERROR, PKCS12_setup_mac(), and PKCS12err.
PKCS12_setup_mac()
int PKCS12_setup_mac (PKCS12 * p12, int iter, unsigned char * salt, int saltlen, const EVP_MD * md_type)
Definition at line 202 of file p12_mutl.c.
References ASN1_INTEGER_set(), ERR_R_MALLOC_FAILURE, EVP_MD_type(), NULL, OBJ_nid2obj(), OPENSSL_malloc, PKCS12_ERROR, PKCS12_F_PKCS12_SETUP_MAC, PKCS12_SALT_LEN, PKCS12err, RAND_bytes(), V_ASN1_NULL, X509_ALGOR_set0(), and X509_SIG_getm().
Referenced by PKCS12_set_mac().
PKCS12_verify_mac()
int PKCS12_verify_mac (PKCS12 * p12, const char * pass, int passlen)
Definition at line 146 of file p12_mutl.c.
References EVP_MAX_MD_SIZE, NULL, PKCS12_F_PKCS12_VERIFY_MAC, PKCS12_R_MAC_ABSENT, and PKCS12err.
Referenced by PKCS12_newpass().
PKCS8_add_keyusage()
int PKCS8_add_keyusage (PKCS8_PRIV_KEY_INFO * p8, int usage)
Definition at line 29 of file p12_attr.c.
References NID_key_usage, PKCS8_pkey_add1_attr_by_NID(), and V_ASN1_BIT_STRING.
Referenced by PKCS12_add_key().
PKCS8_decrypt()
PKCS8_PRIV_KEY_INFO* PKCS8_decrypt (const X509_SIG * p8, const char * pass, int passlen)
Definition at line 14 of file p12_p8d.c.
References ASN1_ITEM_rptr, PKCS12_item_decrypt_d2i(), and X509_SIG_get0().
Referenced by PKCS12_decrypt_skey().
PKCS8_encrypt()
X509_SIG* PKCS8_encrypt (int pbe_nid, const EVP_CIPHER * cipher, const char * pass, int passlen, unsigned char * salt, int saltlen, int iter, PKCS8_PRIV_KEY_INFO * p8)
Definition at line 15 of file p12_p8e.c.
Referenced by PKCS12_SAFEBAG_create_pkcs8_encrypt().
PKCS8_get_attr()
ASN1_TYPE* PKCS8_get_attr (PKCS8_PRIV_KEY_INFO * p8, int attr_nid)
Definition at line 28 of file p12_sbag.c.
References PKCS12_get_attr_gen().
PKCS8_set0_pbe()
X509_SIG* PKCS8_set0_pbe (const char * pass, int passlen, PKCS8_PRIV_KEY_INFO * p8inf, X509_ALGOR * pbe)
Definition at line 44 of file p12_p8e.c.
References ASN1_ITEM_rptr, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_zalloc, PKCS12_F_PKCS8_SET0_PBE, PKCS12_item_i2d_encrypt(), PKCS12_R_ENCRYPT_ERROR, and PKCS12err.
STACK_OF() [1/3]
const STACK_OF (PKCS12_SAFEBAG) const
STACK_OF() [2/3]
STACK_OF (PKCS7) const
STACK_OF() [3/3]
const STACK_OF (X509_ATTRIBUTE) const
Variable Documentation
pass
const char* pass
Definition at line 124 of file pkcs12.h.
Referenced by CMS_RecipientInfo_set0_password(), load_key(), and load_pubkey().
passlen
const char int passlen
Definition at line 124 of file pkcs12.h.
Referenced by CMS_RecipientInfo_set0_password().