include/openssl/pkcs7.h File Reference
pkcs7.h File Reference
#include <openssl/asn1.h>
#include <openssl/bio.h>
#include <openssl/e_os2.h>
#include <openssl/symhacks.h>
#include <openssl/ossl_typ.h>
Data Structures
struct PKCS7_ISSUER_AND_SERIAL
struct PKCS7_SIGNER_INFO
struct PKCS7_RECIP_INFO
struct PKCS7_SIGNED
struct PKCS7_ENC_CONTENT
struct PKCS7_ENVELOPE
struct PKCS7_SIGN_ENVELOPE
struct PKCS7_DIGEST
struct PKCS7_ENCRYPT
struct PKCS7
Macros
#define PKCS7_S_HEADER 0
#define PKCS7_S_BODY 1
#define PKCS7_S_TAIL 2
#define PKCS7_OP_SET_DETACHED_SIGNATURE 1
#define PKCS7_OP_GET_DETACHED_SIGNATURE 2
#define PKCS7_get_signed_attributes(si) ((si)->auth_attr)
#define PKCS7_get_attributes(si) ((si)->unauth_attr)
#define PKCS7_type_is_signed(a) (OBJ_obj2nid((a)->type) == NID_pkcs7_signed)
#define PKCS7_type_is_encrypted(a) (OBJ_obj2nid((a)->type) == NID_pkcs7_encrypted)
#define PKCS7_type_is_enveloped(a) (OBJ_obj2nid((a)->type) == NID_pkcs7_enveloped)
#define PKCS7_type_is_signedAndEnveloped(a) (OBJ_obj2nid((a)->type) == NID_pkcs7_signedAndEnveloped)
#define PKCS7_type_is_data(a) (OBJ_obj2nid((a)->type) == NID_pkcs7_data)
#define PKCS7_type_is_digest(a) (OBJ_obj2nid((a)->type) == NID_pkcs7_digest)
#define PKCS7_set_detached(p, v) PKCS7_ctrl(p,PKCS7_OP_SET_DETACHED_SIGNATURE,v,NULL)
#define PKCS7_get_detached(p) PKCS7_ctrl(p,PKCS7_OP_GET_DETACHED_SIGNATURE,0,NULL)
#define PKCS7_is_detached(p7) (PKCS7_type_is_signed(p7) && PKCS7_get_detached(p7))
#define PKCS7_TEXT 0x1
#define PKCS7_NOCERTS 0x2
#define PKCS7_NOSIGS 0x4
#define PKCS7_NOCHAIN 0x8
#define PKCS7_NOINTERN 0x10
#define PKCS7_NOVERIFY 0x20
#define PKCS7_DETACHED 0x40
#define PKCS7_BINARY 0x80
#define PKCS7_NOATTR 0x100
#define PKCS7_NOSMIMECAP 0x200
#define PKCS7_NOOLDMIMETYPE 0x400
#define PKCS7_CRLFEOL 0x800
#define PKCS7_STREAM 0x1000
#define PKCS7_NOCRL 0x2000
#define PKCS7_PARTIAL 0x4000
#define PKCS7_REUSE_DIGEST 0x8000
#define PKCS7_NO_DUAL_CONTENT 0x10000
#define SMIME_TEXT PKCS7_TEXT
#define SMIME_NOCERTS PKCS7_NOCERTS
#define SMIME_NOSIGS PKCS7_NOSIGS
#define SMIME_NOCHAIN PKCS7_NOCHAIN
#define SMIME_NOINTERN PKCS7_NOINTERN
#define SMIME_NOVERIFY PKCS7_NOVERIFY
#define SMIME_DETACHED PKCS7_DETACHED
#define SMIME_BINARY PKCS7_BINARY
#define SMIME_NOATTR PKCS7_NOATTR
#define SMIME_ASCIICRLF 0x80000
#define PKCS7_F_DO_PKCS7_SIGNED_ATTRIB 136
#define PKCS7_F_PKCS7_ADD0_ATTRIB_SIGNING_TIME 135
#define PKCS7_F_PKCS7_ADD_ATTRIB_SMIMECAP 118
#define PKCS7_F_PKCS7_ADD_CERTIFICATE 100
#define PKCS7_F_PKCS7_ADD_CRL 101
#define PKCS7_F_PKCS7_ADD_RECIPIENT_INFO 102
#define PKCS7_F_PKCS7_ADD_SIGNATURE 131
#define PKCS7_F_PKCS7_ADD_SIGNER 103
#define PKCS7_F_PKCS7_BIO_ADD_DIGEST 125
#define PKCS7_F_PKCS7_COPY_EXISTING_DIGEST 138
#define PKCS7_F_PKCS7_CTRL 104
#define PKCS7_F_PKCS7_DATADECODE 112
#define PKCS7_F_PKCS7_DATAFINAL 128
#define PKCS7_F_PKCS7_DATAINIT 105
#define PKCS7_F_PKCS7_DATAVERIFY 107
#define PKCS7_F_PKCS7_DECRYPT 114
#define PKCS7_F_PKCS7_DECRYPT_RINFO 133
#define PKCS7_F_PKCS7_ENCODE_RINFO 132
#define PKCS7_F_PKCS7_ENCRYPT 115
#define PKCS7_F_PKCS7_FINAL 134
#define PKCS7_F_PKCS7_FIND_DIGEST 127
#define PKCS7_F_PKCS7_GET0_SIGNERS 124
#define PKCS7_F_PKCS7_RECIP_INFO_SET 130
#define PKCS7_F_PKCS7_SET_CIPHER 108
#define PKCS7_F_PKCS7_SET_CONTENT 109
#define PKCS7_F_PKCS7_SET_DIGEST 126
#define PKCS7_F_PKCS7_SET_TYPE 110
#define PKCS7_F_PKCS7_SIGN 116
#define PKCS7_F_PKCS7_SIGNATUREVERIFY 113
#define PKCS7_F_PKCS7_SIGNER_INFO_SET 129
#define PKCS7_F_PKCS7_SIGNER_INFO_SIGN 139
#define PKCS7_F_PKCS7_SIGN_ADD_SIGNER 137
#define PKCS7_F_PKCS7_SIMPLE_SMIMECAP 119
#define PKCS7_F_PKCS7_VERIFY 117
#define PKCS7_R_CERTIFICATE_VERIFY_ERROR 117
#define PKCS7_R_CIPHER_HAS_NO_OBJECT_IDENTIFIER 144
#define PKCS7_R_CIPHER_NOT_INITIALIZED 116
#define PKCS7_R_CONTENT_AND_DATA_PRESENT 118
#define PKCS7_R_CTRL_ERROR 152
#define PKCS7_R_DECRYPT_ERROR 119
#define PKCS7_R_DIGEST_FAILURE 101
#define PKCS7_R_ENCRYPTION_CTRL_FAILURE 149
#define PKCS7_R_ENCRYPTION_NOT_SUPPORTED_FOR_THIS_KEY_TYPE 150
#define PKCS7_R_ERROR_ADDING_RECIPIENT 120
#define PKCS7_R_ERROR_SETTING_CIPHER 121
#define PKCS7_R_INVALID_NULL_POINTER 143
#define PKCS7_R_INVALID_SIGNED_DATA_TYPE 155
#define PKCS7_R_NO_CONTENT 122
#define PKCS7_R_NO_DEFAULT_DIGEST 151
#define PKCS7_R_NO_MATCHING_DIGEST_TYPE_FOUND 154
#define PKCS7_R_NO_RECIPIENT_MATCHES_CERTIFICATE 115
#define PKCS7_R_NO_SIGNATURES_ON_DATA 123
#define PKCS7_R_NO_SIGNERS 142
#define PKCS7_R_OPERATION_NOT_SUPPORTED_ON_THIS_TYPE 104
#define PKCS7_R_PKCS7_ADD_SIGNATURE_ERROR 124
#define PKCS7_R_PKCS7_ADD_SIGNER_ERROR 153
#define PKCS7_R_PKCS7_DATASIGN 145
#define PKCS7_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE 127
#define PKCS7_R_SIGNATURE_FAILURE 105
#define PKCS7_R_SIGNER_CERTIFICATE_NOT_FOUND 128
#define PKCS7_R_SIGNING_CTRL_FAILURE 147
#define PKCS7_R_SIGNING_NOT_SUPPORTED_FOR_THIS_KEY_TYPE 148
#define PKCS7_R_SMIME_TEXT_ERROR 129
#define PKCS7_R_UNABLE_TO_FIND_CERTIFICATE 106
#define PKCS7_R_UNABLE_TO_FIND_MEM_BIO 107
#define PKCS7_R_UNABLE_TO_FIND_MESSAGE_DIGEST 108
#define PKCS7_R_UNKNOWN_DIGEST_TYPE 109
#define PKCS7_R_UNKNOWN_OPERATION 110
#define PKCS7_R_UNSUPPORTED_CIPHER_TYPE 111
#define PKCS7_R_UNSUPPORTED_CONTENT_TYPE 112
#define PKCS7_R_WRONG_CONTENT_TYPE 113
#define PKCS7_R_WRONG_PKCS7_TYPE 114
Functions
int PKCS7_ISSUER_AND_SERIAL_digest (PKCS7_ISSUER_AND_SERIAL *data, const EVP_MD *type, unsigned char *md, unsigned int *len)
PKCS7 * d2i_PKCS7_fp (FILE *fp, PKCS7 **p7)
int i2d_PKCS7_fp (FILE *fp, PKCS7 *p7)
PKCS7 * PKCS7_dup (PKCS7 *p7)
PKCS7 * d2i_PKCS7_bio (BIO *bp, PKCS7 **p7)
int i2d_PKCS7_bio (BIO *bp, PKCS7 *p7)
int i2d_PKCS7_bio_stream (BIO *out, PKCS7 *p7, BIO *in, int flags)
int PEM_write_bio_PKCS7_stream (BIO *out, PKCS7 *p7, BIO *in, int flags)
long PKCS7_ctrl (PKCS7 *p7, int cmd, long larg, char *parg)
int PKCS7_set_type (PKCS7 *p7, int type)
int PKCS7_set0_type_other (PKCS7 *p7, int type, ASN1_TYPE *other)
int PKCS7_set_content (PKCS7 *p7, PKCS7 *p7_data)
int PKCS7_SIGNER_INFO_set (PKCS7_SIGNER_INFO *p7i, X509 *x509, EVP_PKEY *pkey, const EVP_MD *dgst)
int PKCS7_SIGNER_INFO_sign (PKCS7_SIGNER_INFO *si)
int PKCS7_add_signer (PKCS7 *p7, PKCS7_SIGNER_INFO *p7i)
int PKCS7_add_certificate (PKCS7 *p7, X509 *x509)
int PKCS7_add_crl (PKCS7 *p7, X509_CRL *x509)
int PKCS7_content_new (PKCS7 *p7, int nid)
int PKCS7_dataVerify (X509_STORE *cert_store, X509_STORE_CTX *ctx, BIO *bio, PKCS7 *p7, PKCS7_SIGNER_INFO *si)
int PKCS7_signatureVerify (BIO *bio, PKCS7 *p7, PKCS7_SIGNER_INFO *si, X509 *x509)
BIO * PKCS7_dataInit (PKCS7 *p7, BIO *bio)
int PKCS7_dataFinal (PKCS7 *p7, BIO *bio)
BIO * PKCS7_dataDecode (PKCS7 *p7, EVP_PKEY *pkey, BIO *in_bio, X509 *pcert)
PKCS7_SIGNER_INFO * PKCS7_add_signature (PKCS7 *p7, X509 *x509, EVP_PKEY *pkey, const EVP_MD *dgst)
X509 * PKCS7_cert_from_signer_info (PKCS7 *p7, PKCS7_SIGNER_INFO *si)
int PKCS7_set_digest (PKCS7 *p7, const EVP_MD *md)
STACK_OF (PKCS7_SIGNER_INFO) *PKCS7_get_signer_info(PKCS7 *p7)
PKCS7_RECIP_INFO * PKCS7_add_recipient (PKCS7 *p7, X509 *x509)
void PKCS7_SIGNER_INFO_get0_algs (PKCS7_SIGNER_INFO *si, EVP_PKEY **pk, X509_ALGOR **pdig, X509_ALGOR **psig)
void PKCS7_RECIP_INFO_get0_alg (PKCS7_RECIP_INFO *ri, X509_ALGOR **penc)
int PKCS7_add_recipient_info (PKCS7 *p7, PKCS7_RECIP_INFO *ri)
int PKCS7_RECIP_INFO_set (PKCS7_RECIP_INFO *p7i, X509 *x509)
int PKCS7_set_cipher (PKCS7 *p7, const EVP_CIPHER *cipher)
int PKCS7_stream (unsigned char ***boundary, PKCS7 *p7)
PKCS7_ISSUER_AND_SERIAL * PKCS7_get_issuer_and_serial (PKCS7 *p7, int idx)
ASN1_OCTET_STRING * PKCS7_digest_from_attributes (STACK_OF(X509_ATTRIBUTE) *sk)
int PKCS7_add_signed_attribute (PKCS7_SIGNER_INFO *p7si, int nid, int type, void *data)
int PKCS7_add_attribute (PKCS7_SIGNER_INFO *p7si, int nid, int atrtype, void *value)
ASN1_TYPE * PKCS7_get_attribute (PKCS7_SIGNER_INFO *si, int nid)
ASN1_TYPE * PKCS7_get_signed_attribute (PKCS7_SIGNER_INFO *si, int nid)
int PKCS7_set_signed_attributes (PKCS7_SIGNER_INFO *p7si, STACK_OF(X509_ATTRIBUTE) *sk)
int PKCS7_set_attributes (PKCS7_SIGNER_INFO *p7si, STACK_OF(X509_ATTRIBUTE) *sk)
PKCS7 * PKCS7_sign (X509 *signcert, EVP_PKEY *pkey, STACK_OF(X509) *certs, BIO *data, int flags)
PKCS7_SIGNER_INFO * PKCS7_sign_add_signer (PKCS7 *p7, X509 *signcert, EVP_PKEY *pkey, const EVP_MD *md, int flags)
int PKCS7_final (PKCS7 *p7, BIO *data, int flags)
int PKCS7_verify (PKCS7 *p7, STACK_OF(X509) *certs, X509_STORE *store, BIO *indata, BIO *out, int flags)
STACK_OF (X509) *PKCS7_get0_signers(PKCS7 *p7
PKCS7 * PKCS7_encrypt (STACK_OF(X509) *certs, BIO *in, const EVP_CIPHER *cipher, int flags)
int PKCS7_decrypt (PKCS7 *p7, EVP_PKEY *pkey, X509 *cert, BIO *data, int flags)
int PKCS7_add_attrib_smimecap (PKCS7_SIGNER_INFO *si, STACK_OF(X509_ALGOR) *cap)
STACK_OF (X509_ALGOR) *PKCS7_get_smimecap(PKCS7_SIGNER_INFO *si)
int PKCS7_simple_smimecap (STACK_OF(X509_ALGOR) *sk, int nid, int arg)
int PKCS7_add_attrib_content_type (PKCS7_SIGNER_INFO *si, ASN1_OBJECT *coid)
int PKCS7_add0_attrib_signing_time (PKCS7_SIGNER_INFO *si, ASN1_TIME *t)
int PKCS7_add1_attrib_digest (PKCS7_SIGNER_INFO *si, const unsigned char *md, int mdlen)
int SMIME_write_PKCS7 (BIO *bio, PKCS7 *p7, BIO *data, int flags)
PKCS7 * SMIME_read_PKCS7 (BIO *bio, BIO **bcont)
BIO * BIO_new_PKCS7 (BIO *out, PKCS7 *p7)
int ERR_load_PKCS7_strings (void)
Variables
int flags
Macro Definition Documentation
PKCS7_BINARY
#define PKCS7_BINARY 0x80
Definition at line 177 of file pkcs7.h.
PKCS7_CRLFEOL
#define PKCS7_CRLFEOL 0x800
Definition at line 181 of file pkcs7.h.
PKCS7_DETACHED
#define PKCS7_DETACHED 0x40
Definition at line 176 of file pkcs7.h.
Referenced by PKCS7_sign().
PKCS7_F_DO_PKCS7_SIGNED_ATTRIB
#define PKCS7_F_DO_PKCS7_SIGNED_ATTRIB 136
Definition at line 326 of file pkcs7.h.
PKCS7_F_PKCS7_ADD0_ATTRIB_SIGNING_TIME
#define PKCS7_F_PKCS7_ADD0_ATTRIB_SIGNING_TIME 135
Definition at line 327 of file pkcs7.h.
Referenced by PKCS7_add0_attrib_signing_time().
PKCS7_F_PKCS7_ADD_ATTRIB_SMIMECAP
#define PKCS7_F_PKCS7_ADD_ATTRIB_SMIMECAP 118
Definition at line 328 of file pkcs7.h.
Referenced by PKCS7_add_attrib_smimecap().
PKCS7_F_PKCS7_ADD_CERTIFICATE
#define PKCS7_F_PKCS7_ADD_CERTIFICATE 100
Definition at line 329 of file pkcs7.h.
Referenced by PKCS7_add_certificate().
PKCS7_F_PKCS7_ADD_CRL
#define PKCS7_F_PKCS7_ADD_CRL 101
Definition at line 330 of file pkcs7.h.
Referenced by PKCS7_add_crl().
PKCS7_F_PKCS7_ADD_RECIPIENT_INFO
#define PKCS7_F_PKCS7_ADD_RECIPIENT_INFO 102
Definition at line 331 of file pkcs7.h.
Referenced by PKCS7_add_recipient_info().
PKCS7_F_PKCS7_ADD_SIGNATURE
#define PKCS7_F_PKCS7_ADD_SIGNATURE 131
Definition at line 332 of file pkcs7.h.
Referenced by PKCS7_add_signature().
PKCS7_F_PKCS7_ADD_SIGNER
#define PKCS7_F_PKCS7_ADD_SIGNER 103
Definition at line 333 of file pkcs7.h.
Referenced by PKCS7_add_signer().
PKCS7_F_PKCS7_BIO_ADD_DIGEST
#define PKCS7_F_PKCS7_BIO_ADD_DIGEST 125
Definition at line 334 of file pkcs7.h.
PKCS7_F_PKCS7_COPY_EXISTING_DIGEST
#define PKCS7_F_PKCS7_COPY_EXISTING_DIGEST 138
Definition at line 335 of file pkcs7.h.
PKCS7_F_PKCS7_CTRL
#define PKCS7_F_PKCS7_CTRL 104
Definition at line 336 of file pkcs7.h.
PKCS7_F_PKCS7_DATADECODE
#define PKCS7_F_PKCS7_DATADECODE 112
Definition at line 337 of file pkcs7.h.
PKCS7_F_PKCS7_DATAFINAL
#define PKCS7_F_PKCS7_DATAFINAL 128
Definition at line 338 of file pkcs7.h.
Referenced by PKCS7_dataFinal().
PKCS7_F_PKCS7_DATAINIT
#define PKCS7_F_PKCS7_DATAINIT 105
Definition at line 339 of file pkcs7.h.
PKCS7_F_PKCS7_DATAVERIFY
#define PKCS7_F_PKCS7_DATAVERIFY 107
Definition at line 340 of file pkcs7.h.
PKCS7_F_PKCS7_DECRYPT
#define PKCS7_F_PKCS7_DECRYPT 114
Definition at line 341 of file pkcs7.h.
PKCS7_F_PKCS7_DECRYPT_RINFO
#define PKCS7_F_PKCS7_DECRYPT_RINFO 133
Definition at line 342 of file pkcs7.h.
PKCS7_F_PKCS7_ENCODE_RINFO
#define PKCS7_F_PKCS7_ENCODE_RINFO 132
Definition at line 343 of file pkcs7.h.
PKCS7_F_PKCS7_ENCRYPT
#define PKCS7_F_PKCS7_ENCRYPT 115
Definition at line 344 of file pkcs7.h.
PKCS7_F_PKCS7_FINAL
#define PKCS7_F_PKCS7_FINAL 134
Definition at line 345 of file pkcs7.h.
PKCS7_F_PKCS7_FIND_DIGEST
#define PKCS7_F_PKCS7_FIND_DIGEST 127
Definition at line 346 of file pkcs7.h.
PKCS7_F_PKCS7_GET0_SIGNERS
#define PKCS7_F_PKCS7_GET0_SIGNERS 124
Definition at line 347 of file pkcs7.h.
Referenced by STACK_OF().
PKCS7_F_PKCS7_RECIP_INFO_SET
#define PKCS7_F_PKCS7_RECIP_INFO_SET 130
Definition at line 348 of file pkcs7.h.
PKCS7_F_PKCS7_SET_CIPHER
#define PKCS7_F_PKCS7_SET_CIPHER 108
Definition at line 349 of file pkcs7.h.
PKCS7_F_PKCS7_SET_CONTENT
#define PKCS7_F_PKCS7_SET_CONTENT 109
Definition at line 350 of file pkcs7.h.
Referenced by PKCS7_set_content().
PKCS7_F_PKCS7_SET_DIGEST
#define PKCS7_F_PKCS7_SET_DIGEST 126
Definition at line 351 of file pkcs7.h.
PKCS7_F_PKCS7_SET_TYPE
#define PKCS7_F_PKCS7_SET_TYPE 110
Definition at line 352 of file pkcs7.h.
Referenced by PKCS7_set_type().
PKCS7_F_PKCS7_SIGN
#define PKCS7_F_PKCS7_SIGN 116
Definition at line 353 of file pkcs7.h.
Referenced by PKCS7_sign().
PKCS7_F_PKCS7_SIGN_ADD_SIGNER
#define PKCS7_F_PKCS7_SIGN_ADD_SIGNER 137
Definition at line 357 of file pkcs7.h.
PKCS7_F_PKCS7_SIGNATUREVERIFY
#define PKCS7_F_PKCS7_SIGNATUREVERIFY 113
Definition at line 354 of file pkcs7.h.
Referenced by PKCS7_signatureVerify().
PKCS7_F_PKCS7_SIGNER_INFO_SET
#define PKCS7_F_PKCS7_SIGNER_INFO_SET 129
Definition at line 355 of file pkcs7.h.
PKCS7_F_PKCS7_SIGNER_INFO_SIGN
#define PKCS7_F_PKCS7_SIGNER_INFO_SIGN 139
Definition at line 356 of file pkcs7.h.
PKCS7_F_PKCS7_SIMPLE_SMIMECAP
#define PKCS7_F_PKCS7_SIMPLE_SMIMECAP 119
Definition at line 358 of file pkcs7.h.
PKCS7_F_PKCS7_VERIFY
#define PKCS7_F_PKCS7_VERIFY 117
Definition at line 359 of file pkcs7.h.
PKCS7_get_attributes
#define PKCS7_get_attributes (si) ((si)->unauth_attr)
Definition at line 151 of file pkcs7.h.
PKCS7_get_detached
#define PKCS7_get_detached (p) PKCS7_ctrl(p,PKCS7_OP_GET_DETACHED_SIGNATURE,0,NULL)
Definition at line 163 of file pkcs7.h.
PKCS7_get_signed_attributes
#define PKCS7_get_signed_attributes (si) ((si)->auth_attr)
Definition at line 150 of file pkcs7.h.
PKCS7_is_detached
#define PKCS7_is_detached (p7) (PKCS7_type_is_signed(p7) && PKCS7_get_detached(p7))
Definition at line 166 of file pkcs7.h.
PKCS7_NO_DUAL_CONTENT
#define PKCS7_NO_DUAL_CONTENT 0x10000
Definition at line 186 of file pkcs7.h.
PKCS7_NOATTR
#define PKCS7_NOATTR 0x100
Definition at line 178 of file pkcs7.h.
PKCS7_NOCERTS
#define PKCS7_NOCERTS 0x2
Definition at line 171 of file pkcs7.h.
Referenced by PKCS7_sign().
PKCS7_NOCHAIN
#define PKCS7_NOCHAIN 0x8
Definition at line 173 of file pkcs7.h.
PKCS7_NOCRL
#define PKCS7_NOCRL 0x2000
Definition at line 183 of file pkcs7.h.
PKCS7_NOINTERN
#define PKCS7_NOINTERN 0x10
Definition at line 174 of file pkcs7.h.
Referenced by STACK_OF().
PKCS7_NOOLDMIMETYPE
#define PKCS7_NOOLDMIMETYPE 0x400
Definition at line 180 of file pkcs7.h.
PKCS7_NOSIGS
#define PKCS7_NOSIGS 0x4
Definition at line 172 of file pkcs7.h.
PKCS7_NOSMIMECAP
#define PKCS7_NOSMIMECAP 0x200
Definition at line 179 of file pkcs7.h.
PKCS7_NOVERIFY
#define PKCS7_NOVERIFY 0x20
Definition at line 175 of file pkcs7.h.
PKCS7_OP_GET_DETACHED_SIGNATURE
#define PKCS7_OP_GET_DETACHED_SIGNATURE 2
Definition at line 148 of file pkcs7.h.
PKCS7_OP_SET_DETACHED_SIGNATURE
#define PKCS7_OP_SET_DETACHED_SIGNATURE 1
Definition at line 147 of file pkcs7.h.
PKCS7_PARTIAL
#define PKCS7_PARTIAL 0x4000
Definition at line 184 of file pkcs7.h.
Referenced by PKCS7_sign().
PKCS7_R_CERTIFICATE_VERIFY_ERROR
#define PKCS7_R_CERTIFICATE_VERIFY_ERROR 117
Definition at line 362 of file pkcs7.h.
PKCS7_R_CIPHER_HAS_NO_OBJECT_IDENTIFIER
#define PKCS7_R_CIPHER_HAS_NO_OBJECT_IDENTIFIER 144
Definition at line 363 of file pkcs7.h.
PKCS7_R_CIPHER_NOT_INITIALIZED
#define PKCS7_R_CIPHER_NOT_INITIALIZED 116
Definition at line 364 of file pkcs7.h.
PKCS7_R_CONTENT_AND_DATA_PRESENT
#define PKCS7_R_CONTENT_AND_DATA_PRESENT 118
Definition at line 365 of file pkcs7.h.
PKCS7_R_CTRL_ERROR
#define PKCS7_R_CTRL_ERROR 152
Definition at line 366 of file pkcs7.h.
PKCS7_R_DECRYPT_ERROR
#define PKCS7_R_DECRYPT_ERROR 119
Definition at line 367 of file pkcs7.h.
PKCS7_R_DIGEST_FAILURE
#define PKCS7_R_DIGEST_FAILURE 101
Definition at line 368 of file pkcs7.h.
Referenced by PKCS7_signatureVerify().
PKCS7_R_ENCRYPTION_CTRL_FAILURE
#define PKCS7_R_ENCRYPTION_CTRL_FAILURE 149
Definition at line 369 of file pkcs7.h.
PKCS7_R_ENCRYPTION_NOT_SUPPORTED_FOR_THIS_KEY_TYPE
#define PKCS7_R_ENCRYPTION_NOT_SUPPORTED_FOR_THIS_KEY_TYPE 150
Definition at line 370 of file pkcs7.h.
PKCS7_R_ERROR_ADDING_RECIPIENT
#define PKCS7_R_ERROR_ADDING_RECIPIENT 120
Definition at line 371 of file pkcs7.h.
PKCS7_R_ERROR_SETTING_CIPHER
#define PKCS7_R_ERROR_SETTING_CIPHER 121
Definition at line 372 of file pkcs7.h.
PKCS7_R_INVALID_NULL_POINTER
#define PKCS7_R_INVALID_NULL_POINTER 143
Definition at line 373 of file pkcs7.h.
Referenced by PKCS7_dataFinal(), and STACK_OF().
PKCS7_R_INVALID_SIGNED_DATA_TYPE
#define PKCS7_R_INVALID_SIGNED_DATA_TYPE 155
Definition at line 374 of file pkcs7.h.
PKCS7_R_NO_CONTENT
#define PKCS7_R_NO_CONTENT 122
Definition at line 375 of file pkcs7.h.
Referenced by PKCS7_dataFinal().
PKCS7_R_NO_DEFAULT_DIGEST
#define PKCS7_R_NO_DEFAULT_DIGEST 151
Definition at line 376 of file pkcs7.h.
Referenced by PKCS7_add_signature().
PKCS7_R_NO_MATCHING_DIGEST_TYPE_FOUND
#define PKCS7_R_NO_MATCHING_DIGEST_TYPE_FOUND 154
Definition at line 377 of file pkcs7.h.
PKCS7_R_NO_RECIPIENT_MATCHES_CERTIFICATE
#define PKCS7_R_NO_RECIPIENT_MATCHES_CERTIFICATE 115
Definition at line 378 of file pkcs7.h.
PKCS7_R_NO_SIGNATURES_ON_DATA
#define PKCS7_R_NO_SIGNATURES_ON_DATA 123
Definition at line 379 of file pkcs7.h.
PKCS7_R_NO_SIGNERS
#define PKCS7_R_NO_SIGNERS 142
Definition at line 380 of file pkcs7.h.
Referenced by STACK_OF().
PKCS7_R_OPERATION_NOT_SUPPORTED_ON_THIS_TYPE
#define PKCS7_R_OPERATION_NOT_SUPPORTED_ON_THIS_TYPE 104
Definition at line 381 of file pkcs7.h.
PKCS7_R_PKCS7_ADD_SIGNATURE_ERROR
#define PKCS7_R_PKCS7_ADD_SIGNATURE_ERROR 124
Definition at line 382 of file pkcs7.h.
PKCS7_R_PKCS7_ADD_SIGNER_ERROR
#define PKCS7_R_PKCS7_ADD_SIGNER_ERROR 153
Definition at line 383 of file pkcs7.h.
Referenced by PKCS7_sign().
PKCS7_R_PKCS7_DATASIGN
#define PKCS7_R_PKCS7_DATASIGN 145
Definition at line 384 of file pkcs7.h.
PKCS7_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE
#define PKCS7_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE 127
Definition at line 385 of file pkcs7.h.
PKCS7_R_SIGNATURE_FAILURE
#define PKCS7_R_SIGNATURE_FAILURE 105
Definition at line 386 of file pkcs7.h.
Referenced by PKCS7_signatureVerify().
PKCS7_R_SIGNER_CERTIFICATE_NOT_FOUND
#define PKCS7_R_SIGNER_CERTIFICATE_NOT_FOUND 128
Definition at line 387 of file pkcs7.h.
Referenced by STACK_OF().
PKCS7_R_SIGNING_CTRL_FAILURE
#define PKCS7_R_SIGNING_CTRL_FAILURE 147
Definition at line 388 of file pkcs7.h.
PKCS7_R_SIGNING_NOT_SUPPORTED_FOR_THIS_KEY_TYPE
#define PKCS7_R_SIGNING_NOT_SUPPORTED_FOR_THIS_KEY_TYPE 148
Definition at line 389 of file pkcs7.h.
PKCS7_R_SMIME_TEXT_ERROR
#define PKCS7_R_SMIME_TEXT_ERROR 129
Definition at line 390 of file pkcs7.h.
PKCS7_R_UNABLE_TO_FIND_CERTIFICATE
#define PKCS7_R_UNABLE_TO_FIND_CERTIFICATE 106
Definition at line 391 of file pkcs7.h.
PKCS7_R_UNABLE_TO_FIND_MEM_BIO
#define PKCS7_R_UNABLE_TO_FIND_MEM_BIO 107
Definition at line 392 of file pkcs7.h.
PKCS7_R_UNABLE_TO_FIND_MESSAGE_DIGEST
#define PKCS7_R_UNABLE_TO_FIND_MESSAGE_DIGEST 108
Definition at line 393 of file pkcs7.h.
Referenced by PKCS7_signatureVerify().
PKCS7_R_UNKNOWN_DIGEST_TYPE
#define PKCS7_R_UNKNOWN_DIGEST_TYPE 109
Definition at line 394 of file pkcs7.h.
PKCS7_R_UNKNOWN_OPERATION
#define PKCS7_R_UNKNOWN_OPERATION 110
Definition at line 395 of file pkcs7.h.
PKCS7_R_UNSUPPORTED_CIPHER_TYPE
#define PKCS7_R_UNSUPPORTED_CIPHER_TYPE 111
Definition at line 396 of file pkcs7.h.
PKCS7_R_UNSUPPORTED_CONTENT_TYPE
#define PKCS7_R_UNSUPPORTED_CONTENT_TYPE 112
Definition at line 397 of file pkcs7.h.
Referenced by PKCS7_set_content(), and PKCS7_set_type().
PKCS7_R_WRONG_CONTENT_TYPE
#define PKCS7_R_WRONG_CONTENT_TYPE 113
Definition at line 398 of file pkcs7.h.
Referenced by PKCS7_add_certificate(), PKCS7_add_crl(), PKCS7_add_recipient_info(), PKCS7_add_signer(), and STACK_OF().
PKCS7_R_WRONG_PKCS7_TYPE
#define PKCS7_R_WRONG_PKCS7_TYPE 114
Definition at line 399 of file pkcs7.h.
Referenced by PKCS7_signatureVerify().
PKCS7_REUSE_DIGEST
#define PKCS7_REUSE_DIGEST 0x8000
Definition at line 185 of file pkcs7.h.
PKCS7_S_BODY
#define PKCS7_S_BODY 1
Definition at line 116 of file pkcs7.h.
PKCS7_S_HEADER
#define PKCS7_S_HEADER 0
Definition at line 115 of file pkcs7.h.
Referenced by PKCS7_dataFinal().
PKCS7_S_TAIL
#define PKCS7_S_TAIL 2
Definition at line 117 of file pkcs7.h.
PKCS7_set_detached
#define PKCS7_set_detached (p, v) PKCS7_ctrl(p,PKCS7_OP_SET_DETACHED_SIGNATURE,v,NULL)
Definition at line 161 of file pkcs7.h.
Referenced by PKCS7_sign().
PKCS7_STREAM
#define PKCS7_STREAM 0x1000
Definition at line 182 of file pkcs7.h.
Referenced by PKCS7_sign().
PKCS7_TEXT
#define PKCS7_TEXT 0x1
Definition at line 170 of file pkcs7.h.
PKCS7_type_is_data
#define PKCS7_type_is_data (a) (OBJ_obj2nid((a)->type) == NID_pkcs7_data)
Definition at line 158 of file pkcs7.h.
Referenced by STACK_OF().
PKCS7_type_is_digest
#define PKCS7_type_is_digest (a) (OBJ_obj2nid((a)->type) == NID_pkcs7_digest)
Definition at line 159 of file pkcs7.h.
PKCS7_type_is_encrypted
#define PKCS7_type_is_encrypted (a) (OBJ_obj2nid((a)->type) == NID_pkcs7_encrypted)
Definition at line 154 of file pkcs7.h.
Referenced by PKCS12_pack_p7encdata().
PKCS7_type_is_enveloped
#define PKCS7_type_is_enveloped (a) (OBJ_obj2nid((a)->type) == NID_pkcs7_enveloped)
Definition at line 155 of file pkcs7.h.
PKCS7_type_is_signed
#define PKCS7_type_is_signed (a) (OBJ_obj2nid((a)->type) == NID_pkcs7_signed)
Definition at line 153 of file pkcs7.h.
Referenced by PKCS7_cert_from_signer_info(), PKCS7_signatureVerify(), and STACK_OF().
PKCS7_type_is_signedAndEnveloped
#define PKCS7_type_is_signedAndEnveloped (a) (OBJ_obj2nid((a)->type) == NID_pkcs7_signedAndEnveloped)
Definition at line 156 of file pkcs7.h.
Referenced by PKCS7_signatureVerify(), and STACK_OF().
SMIME_ASCIICRLF
#define SMIME_ASCIICRLF 0x80000
Definition at line 201 of file pkcs7.h.
SMIME_BINARY
#define SMIME_BINARY PKCS7_BINARY
Definition at line 197 of file pkcs7.h.
Referenced by SMIME_crlf_copy().
SMIME_DETACHED
#define SMIME_DETACHED PKCS7_DETACHED
Definition at line 196 of file pkcs7.h.
SMIME_NOATTR
#define SMIME_NOATTR PKCS7_NOATTR
Definition at line 198 of file pkcs7.h.
SMIME_NOCERTS
#define SMIME_NOCERTS PKCS7_NOCERTS
Definition at line 191 of file pkcs7.h.
SMIME_NOCHAIN
#define SMIME_NOCHAIN PKCS7_NOCHAIN
Definition at line 193 of file pkcs7.h.
SMIME_NOINTERN
#define SMIME_NOINTERN PKCS7_NOINTERN
Definition at line 194 of file pkcs7.h.
SMIME_NOSIGS
#define SMIME_NOSIGS PKCS7_NOSIGS
Definition at line 192 of file pkcs7.h.
SMIME_NOVERIFY
#define SMIME_NOVERIFY PKCS7_NOVERIFY
Definition at line 195 of file pkcs7.h.
SMIME_TEXT
#define SMIME_TEXT PKCS7_TEXT
Definition at line 190 of file pkcs7.h.
Referenced by SMIME_crlf_copy().
Function Documentation
BIO_new_PKCS7()
BIO* BIO_new_PKCS7 (BIO * out, PKCS7 * p7)
Definition at line 21 of file bio_pk7.c.
d2i_PKCS7_bio()
PKCS7* d2i_PKCS7_bio (BIO * bp, PKCS7 ** p7)
Definition at line 166 of file x_all.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_PKCS7_fp()
PKCS7* d2i_PKCS7_fp (FILE * fp, PKCS7 ** p7)
Definition at line 155 of file x_all.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
ERR_load_PKCS7_strings()
int ERR_load_PKCS7_strings (void)
Definition at line 121 of file pkcs7err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
i2d_PKCS7_bio()
int i2d_PKCS7_bio (BIO * bp, PKCS7 * p7)
Definition at line 171 of file x_all.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_PKCS7_bio_stream()
int i2d_PKCS7_bio_stream (BIO * out, PKCS7 * p7, BIO * in, int flags)
Definition at line 18 of file pk7_mime.c.
i2d_PKCS7_fp()
int i2d_PKCS7_fp (FILE * fp, PKCS7 * p7)
Definition at line 160 of file x_all.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
PEM_write_bio_PKCS7_stream()
int PEM_write_bio_PKCS7_stream (BIO * out, PKCS7 * p7, BIO * in, int flags)
Definition at line 24 of file pk7_mime.c.
PKCS7_add0_attrib_signing_time()
int PKCS7_add0_attrib_signing_time (PKCS7_SIGNER_INFO * si, ASN1_TIME * t)
Definition at line 96 of file pk7_attr.c.
References ERR_R_MALLOC_FAILURE, NID_pkcs9_signingTime, NULL, PKCS7_add_signed_attribute(), PKCS7_F_PKCS7_ADD0_ATTRIB_SIGNING_TIME, PKCS7err, V_ASN1_UTCTIME, and X509_gmtime_adj().
PKCS7_add1_attrib_digest()
int PKCS7_add1_attrib_digest (PKCS7_SIGNER_INFO * si, const unsigned char * md, int mdlen)
Definition at line 107 of file pk7_attr.c.
PKCS7_add_attrib_content_type()
int PKCS7_add_attrib_content_type (PKCS7_SIGNER_INFO * si, ASN1_OBJECT * coid)
Definition at line 86 of file pk7_attr.c.
References NID_pkcs7_data, NID_pkcs9_contentType, OBJ_nid2obj(), PKCS7_add_signed_attribute(), PKCS7_get_signed_attribute(), and V_ASN1_OBJECT.
PKCS7_add_attrib_smimecap()
int PKCS7_add_attrib_smimecap (PKCS7_SIGNER_INFO * si, STACK_OF(X509_ALGOR) * cap)
Definition at line 20 of file pk7_attr.c.
References ASN1_item_i2d(), ASN1_ITEM_rptr, ASN1_STRING_new(), ERR_R_MALLOC_FAILURE, NID_SMIMECapabilities, NULL, PKCS7_add_signed_attribute(), PKCS7_F_PKCS7_ADD_ATTRIB_SMIMECAP, PKCS7err, seq, and V_ASN1_SEQUENCE.
PKCS7_add_attribute()
int PKCS7_add_attribute (PKCS7_SIGNER_INFO * p7si, int nid, int atrtype, void * value)
Definition at line 1136 of file pk7_doit.c.
PKCS7_add_certificate()
int PKCS7_add_certificate (PKCS7 * p7, X509 * x509)
Definition at line 239 of file pk7_lib.c.
References PKCS7::d, ERR_R_MALLOC_FAILURE, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, NULL, OBJ_obj2nid(), PKCS7_F_PKCS7_ADD_CERTIFICATE, PKCS7_R_WRONG_CONTENT_TYPE, PKCS7err, PKCS7::sign, PKCS7::signed_and_enveloped, STACK_OF(), PKCS7::type, and X509_up_ref().
Referenced by PKCS7_sign().
PKCS7_add_crl()
int PKCS7_add_crl (PKCS7 * p7, X509_CRL * x509)
Definition at line 271 of file pk7_lib.c.
References PKCS7::d, ERR_R_MALLOC_FAILURE, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, NULL, OBJ_obj2nid(), PKCS7_F_PKCS7_ADD_CRL, PKCS7_R_WRONG_CONTENT_TYPE, PKCS7err, PKCS7::sign, PKCS7::signed_and_enveloped, STACK_OF(), PKCS7::type, and X509_CRL_up_ref().
PKCS7_add_recipient()
PKCS7_RECIP_INFO* PKCS7_add_recipient (PKCS7 * p7, X509 * x509)
Definition at line 423 of file pk7_lib.c.
References NULL, PKCS7_add_recipient_info(), and PKCS7_RECIP_INFO_set().
PKCS7_add_recipient_info()
int PKCS7_add_recipient_info (PKCS7 * p7, PKCS7_RECIP_INFO * ri)
Definition at line 439 of file pk7_lib.c.
References PKCS7::d, PKCS7::enveloped, NID_pkcs7_enveloped, NID_pkcs7_signedAndEnveloped, OBJ_obj2nid(), PKCS7_F_PKCS7_ADD_RECIPIENT_INFO, PKCS7_R_WRONG_CONTENT_TYPE, PKCS7err, PKCS7::signed_and_enveloped, STACK_OF(), and PKCS7::type.
Referenced by PKCS7_add_recipient().
PKCS7_add_signature()
PKCS7_SIGNER_INFO* PKCS7_add_signature (PKCS7 * p7, X509 * x509, EVP_PKEY * pkey, const EVP_MD * dgst)
Definition at line 350 of file pk7_lib.c.
References EVP_get_digestbynid, EVP_PKEY_get_default_digest_nid(), NULL, PKCS7_add_signer(), PKCS7_F_PKCS7_ADD_SIGNATURE, PKCS7_R_NO_DEFAULT_DIGEST, PKCS7_SIGNER_INFO_set(), and PKCS7err.
PKCS7_add_signed_attribute()
int PKCS7_add_signed_attribute (PKCS7_SIGNER_INFO * p7si, int nid, int type, void * data)
Definition at line 1130 of file pk7_doit.c.
Referenced by PKCS7_add0_attrib_signing_time(), PKCS7_add_attrib_content_type(), and PKCS7_add_attrib_smimecap().
PKCS7_add_signer()
int PKCS7_add_signer (PKCS7 * p7, PKCS7_SIGNER_INFO * p7i)
Definition at line 186 of file pk7_lib.c.
References PKCS7::d, PKCS7_SIGNER_INFO::digest_alg, ERR_R_MALLOC_FAILURE, nid, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, NULL, OBJ_nid2obj(), OBJ_obj2nid(), PKCS7_F_PKCS7_ADD_SIGNER, PKCS7_R_WRONG_CONTENT_TYPE, PKCS7err, PKCS7::sign, PKCS7::signed_and_enveloped, STACK_OF(), PKCS7::type, and V_ASN1_NULL.
Referenced by PKCS7_add_signature().
PKCS7_cert_from_signer_info()
X509* PKCS7_cert_from_signer_info (PKCS7 * p7, PKCS7_SIGNER_INFO * si)
Definition at line 507 of file pk7_lib.c.
References PKCS7::d, PKCS7_ISSUER_AND_SERIAL::issuer, PKCS7_SIGNER_INFO::issuer_and_serial, NULL, PKCS7_type_is_signed, PKCS7::sign, and X509_find_by_issuer_and_serial().
PKCS7_content_new()
int PKCS7_content_new (PKCS7 * p7, int nid)
Definition at line 63 of file pk7_lib.c.
Referenced by PKCS7_sign().
PKCS7_ctrl()
long PKCS7_ctrl (PKCS7 * p7, int cmd, long larg, char * parg)
Definition at line 17 of file pk7_lib.c.
References nid.
PKCS7_dataDecode()
BIO* PKCS7_dataDecode (PKCS7 * p7, EVP_PKEY * pkey, BIO * in_bio, X509 * pcert)
Definition at line 354 of file pk7_doit.c.
PKCS7_dataFinal()
int PKCS7_dataFinal (PKCS7 * p7, BIO * bio)
Definition at line 639 of file pk7_doit.c.
References PKCS7::d, PKCS7::data, PKCS7_ENC_CONTENT::enc_data, PKCS7_ENVELOPE::enc_data, PKCS7_SIGN_ENVELOPE::enc_data, PKCS7::enveloped, ERR_R_MALLOC_FAILURE, EVP_MD_CTX_new(), NID_pkcs7_data, NID_pkcs7_enveloped, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, NULL, OBJ_obj2nid(), PKCS7_F_PKCS7_DATAFINAL, PKCS7_R_INVALID_NULL_POINTER, PKCS7_R_NO_CONTENT, PKCS7_S_HEADER, PKCS7err, PKCS7::ptr, PKCS7::sign, PKCS7::signed_and_enveloped, STACK_OF, PKCS7::state, and PKCS7::type.
PKCS7_dataInit()
BIO* PKCS7_dataInit (PKCS7 * p7, BIO * bio)
Definition at line 193 of file pk7_doit.c.
PKCS7_dataVerify()
int PKCS7_dataVerify (X509_STORE * cert_store, X509_STORE_CTX * ctx, BIO * bio, PKCS7 * p7, PKCS7_SIGNER_INFO * si)
Definition at line 876 of file pk7_doit.c.
References STACK_OF.
PKCS7_decrypt()
int PKCS7_decrypt (PKCS7 * p7, EVP_PKEY * pkey, X509 * cert, BIO * data, int flags)
Definition at line 477 of file pk7_smime.c.
PKCS7_digest_from_attributes()
ASN1_OCTET_STRING* PKCS7_digest_from_attributes (STACK_OF(X509_ATTRIBUTE) * sk)
Definition at line 1084 of file pk7_doit.c.
Referenced by PKCS7_signatureVerify().
PKCS7_dup()
PKCS7* PKCS7_dup (PKCS7 * p7)
PKCS7_encrypt()
PKCS7* PKCS7_encrypt (STACK_OF(X509) * certs, BIO * in, const EVP_CIPHER * cipher, int flags)
Definition at line 436 of file pk7_smime.c.
PKCS7_final()
int PKCS7_final (PKCS7 * p7, BIO * data, int flags)
Definition at line 65 of file pk7_smime.c.
Referenced by PKCS7_sign().
PKCS7_get_attribute()
ASN1_TYPE* PKCS7_get_attribute (PKCS7_SIGNER_INFO * si, int nid)
Definition at line 1070 of file pk7_doit.c.
PKCS7_get_issuer_and_serial()
PKCS7_ISSUER_AND_SERIAL* PKCS7_get_issuer_and_serial (PKCS7 * p7, int idx)
Definition at line 1045 of file pk7_doit.c.
PKCS7_get_signed_attribute()
ASN1_TYPE* PKCS7_get_signed_attribute (PKCS7_SIGNER_INFO * si, int nid)
Definition at line 1065 of file pk7_doit.c.
Referenced by PKCS7_add_attrib_content_type(), and STACK_OF().
PKCS7_ISSUER_AND_SERIAL_digest()
int PKCS7_ISSUER_AND_SERIAL_digest (PKCS7_ISSUER_AND_SERIAL * data, const EVP_MD * type, unsigned char * md, unsigned int * len)
Definition at line 405 of file x_all.c.
PKCS7_RECIP_INFO_get0_alg()
void PKCS7_RECIP_INFO_get0_alg (PKCS7_RECIP_INFO * ri, X509_ALGOR ** penc)
Definition at line 417 of file pk7_lib.c.
References PKCS7_RECIP_INFO::key_enc_algor.
PKCS7_RECIP_INFO_set()
int PKCS7_RECIP_INFO_set (PKCS7_RECIP_INFO * p7i, X509 * x509)
Definition at line 463 of file pk7_lib.c.
Referenced by PKCS7_add_recipient().
PKCS7_set0_type_other()
int PKCS7_set0_type_other (PKCS7 * p7, int type, ASN1_TYPE * other)
Definition at line 179 of file pk7_lib.c.
References PKCS7::d, OBJ_nid2obj(), PKCS7::other, and PKCS7::type.
PKCS7_set_attributes()
int PKCS7_set_attributes (PKCS7_SIGNER_INFO * p7si, STACK_OF(X509_ATTRIBUTE) * sk)
Definition at line 1111 of file pk7_doit.c.
References NULL, and X509_ATTRIBUTE_dup().
PKCS7_set_cipher()
int PKCS7_set_cipher (PKCS7 * p7, const EVP_CIPHER * cipher)
Definition at line 518 of file pk7_lib.c.
PKCS7_set_content()
int PKCS7_set_content (PKCS7 * p7, PKCS7 * p7_data)
Definition at line 80 of file pk7_lib.c.
References PKCS7_SIGNED::contents, PKCS7_DIGEST::contents, PKCS7::d, PKCS7::digest, NID_pkcs7_data, NID_pkcs7_digest, NID_pkcs7_encrypted, NID_pkcs7_enveloped, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, OBJ_obj2nid(), PKCS7_F_PKCS7_SET_CONTENT, PKCS7_R_UNSUPPORTED_CONTENT_TYPE, PKCS7err, PKCS7::sign, and PKCS7::type.
PKCS7_set_digest()
int PKCS7_set_digest (PKCS7 * p7, const EVP_MD * md)
Definition at line 378 of file pk7_lib.c.
PKCS7_set_signed_attributes()
int PKCS7_set_signed_attributes (PKCS7_SIGNER_INFO * p7si, STACK_OF(X509_ATTRIBUTE) * sk)
Definition at line 1092 of file pk7_doit.c.
References NULL, and X509_ATTRIBUTE_dup().
PKCS7_set_type()
int PKCS7_set_type (PKCS7 * p7, int type)
Definition at line 107 of file pk7_lib.c.
References ASN1_INTEGER_set(), PKCS7_ENC_CONTENT::content_type, PKCS7::d, PKCS7::data, PKCS7::digest, PKCS7_ENVELOPE::enc_data, PKCS7_SIGN_ENVELOPE::enc_data, PKCS7_ENCRYPT::enc_data, PKCS7::encrypted, PKCS7::enveloped, NID_pkcs7_data, NID_pkcs7_digest, NID_pkcs7_encrypted, NID_pkcs7_enveloped, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, NULL, obj, OBJ_nid2obj(), PKCS7_F_PKCS7_SET_TYPE, PKCS7_R_UNSUPPORTED_CONTENT_TYPE, PKCS7err, PKCS7::sign, PKCS7::signed_and_enveloped, PKCS7::type, PKCS7_SIGNED::version, PKCS7_ENVELOPE::version, PKCS7_SIGN_ENVELOPE::version, PKCS7_DIGEST::version, and PKCS7_ENCRYPT::version.
Referenced by PKCS12_pack_p7encdata(), and PKCS7_sign().
PKCS7_sign()
PKCS7* PKCS7_sign (X509 * signcert, EVP_PKEY * pkey, STACK_OF(X509) * certs, BIO * data, int flags)
Definition at line 22 of file pk7_smime.c.
References ERR_R_MALLOC_FAILURE, NID_pkcs7_data, NID_pkcs7_signed, NULL, PKCS7_add_certificate(), PKCS7_content_new(), PKCS7_DETACHED, PKCS7_F_PKCS7_SIGN, PKCS7_final(), PKCS7_NOCERTS, PKCS7_PARTIAL, PKCS7_R_PKCS7_ADD_SIGNER_ERROR, PKCS7_set_detached, PKCS7_set_type(), PKCS7_sign_add_signer(), PKCS7_STREAM, and PKCS7err.
PKCS7_sign_add_signer()
PKCS7_SIGNER_INFO* PKCS7_sign_add_signer (PKCS7 * p7, X509 * signcert, EVP_PKEY * pkey, const EVP_MD * md, int flags)
Definition at line 109 of file pk7_smime.c.
Referenced by PKCS7_sign().
PKCS7_signatureVerify()
int PKCS7_signatureVerify (BIO * bio, PKCS7 * p7, PKCS7_SIGNER_INFO * si, X509 * x509)
Definition at line 933 of file pk7_doit.c.
References ASN1_item_i2d(), ASN1_ITEM_rptr, BIO_find_type(), BIO_get_md_ctx, BIO_next(), BIO_TYPE_MD, PKCS7_SIGNER_INFO::digest_alg, PKCS7_SIGNER_INFO::enc_digest, ERR_R_ASN1_LIB, ERR_R_INTERNAL_ERROR, ERR_R_MALLOC_FAILURE, EVP_DigestFinal_ex(), EVP_get_digestbynid, EVP_MAX_MD_SIZE, EVP_MD_CTX_copy_ex(), EVP_MD_CTX_free(), EVP_MD_CTX_md(), EVP_MD_CTX_new(), EVP_MD_CTX_type, EVP_MD_pkey_type(), EVP_VerifyFinal(), EVP_VerifyInit_ex, EVP_VerifyUpdate, NULL, OBJ_obj2nid(), OPENSSL_free, PKCS7_digest_from_attributes(), PKCS7_F_PKCS7_SIGNATUREVERIFY, PKCS7_R_DIGEST_FAILURE, PKCS7_R_SIGNATURE_FAILURE, PKCS7_R_UNABLE_TO_FIND_MESSAGE_DIGEST, PKCS7_R_WRONG_PKCS7_TYPE, PKCS7_type_is_signed, PKCS7_type_is_signedAndEnveloped, PKCS7err, STACK_OF, and X509_get0_pubkey().
PKCS7_SIGNER_INFO_get0_algs()
void PKCS7_SIGNER_INFO_get0_algs (PKCS7_SIGNER_INFO * si, EVP_PKEY ** pk, X509_ALGOR ** pdig, X509_ALGOR ** psig)
Definition at line 406 of file pk7_lib.c.
References PKCS7_SIGNER_INFO::digest_alg, PKCS7_SIGNER_INFO::digest_enc_alg, and PKCS7_SIGNER_INFO::pkey.
PKCS7_SIGNER_INFO_set()
int PKCS7_SIGNER_INFO_set (PKCS7_SIGNER_INFO * p7i, X509 * x509, EVP_PKEY * pkey, const EVP_MD * dgst)
Definition at line 304 of file pk7_lib.c.
Referenced by PKCS7_add_signature().
PKCS7_SIGNER_INFO_sign()
int PKCS7_SIGNER_INFO_sign (PKCS7_SIGNER_INFO * si)
Definition at line 813 of file pk7_doit.c.
PKCS7_simple_smimecap()
int PKCS7_simple_smimecap (STACK_OF(X509_ALGOR) * sk, int nid, int arg)
Definition at line 50 of file pk7_attr.c.
PKCS7_stream()
int PKCS7_stream (unsigned char *** boundary, PKCS7 * p7)
Definition at line 548 of file pk7_lib.c.
References ASN1_STRING_FLAG_NDEF, PKCS7_SIGNED::contents, PKCS7::d, PKCS7::data, PKCS7_ENC_CONTENT::enc_data, PKCS7_ENVELOPE::enc_data, PKCS7_SIGN_ENVELOPE::enc_data, PKCS7::enveloped, NID_pkcs7_data, NID_pkcs7_enveloped, NID_pkcs7_signed, NID_pkcs7_signedAndEnveloped, NULL, OBJ_obj2nid(), PKCS7::sign, PKCS7::signed_and_enveloped, and PKCS7::type.
PKCS7_verify()
int PKCS7_verify (PKCS7 * p7, STACK_OF(X509) * certs, X509_STORE * store, BIO * indata, BIO * out, int flags)
Definition at line 204 of file pk7_smime.c.
SMIME_read_PKCS7()
PKCS7* SMIME_read_PKCS7 (BIO * bio, BIO ** bcont)
Definition at line 46 of file pk7_mime.c.
References ASN1_ITEM_rptr, and SMIME_read_ASN1().
SMIME_write_PKCS7()
int SMIME_write_PKCS7 (BIO * bio, PKCS7 * p7, BIO * data, int flags)
Definition at line 30 of file pk7_mime.c.
References ASN1_ITEM_rptr, PKCS7::d, NID_pkcs7_signed, NID_undef, NULL, OBJ_obj2nid(), PKCS7::sign, SMIME_OLDMIME, SMIME_write_ASN1(), STACK_OF, and PKCS7::type.
STACK_OF() [1/3]
STACK_OF (PKCS7_SIGNER_INFO)
Definition at line 394 of file pk7_lib.c.
References PKCS7::d, NULL, PKCS7_type_is_signed, PKCS7_type_is_signedAndEnveloped, PKCS7::ptr, PKCS7::sign, and PKCS7::signed_and_enveloped.
Referenced by PKCS7_add_certificate(), PKCS7_add_crl(), PKCS7_add_recipient_info(), and PKCS7_add_signer().
STACK_OF() [2/3]
STACK_OF (X509)
Definition at line 478 of file cms_lib.c.
STACK_OF() [3/3]
STACK_OF (X509_ALGOR)
Definition at line 35 of file pk7_attr.c.
Variable Documentation
flags
int flags
Definition at line 294 of file pkcs7.h.
Referenced by ASN1_PCTX_set_cert_flags(), ASN1_PCTX_set_flags(), ASN1_PCTX_set_nm_flags(), ASN1_PCTX_set_oid_flags(), ASN1_PCTX_set_str_flags(), BIO_set_flags(), BN_with_flags(), CONF_imodule_set_flags(), DH_meth_new(), DH_meth_set_flags(), DH_set_flags(), DH_test_flags(), DSA_meth_new(), DSA_meth_set_flags(), DSA_set_flags(), DSA_test_flags(), EC_KEY_set_enc_flags(), EC_KEY_set_flags(), ENGINE_cmd_is_executable(), ENGINE_set_default_string(), ENGINE_set_flags(), ERR_set_error_data(), EVP_CIPHER_CTX_set_flags(), EVP_MD_CTX_set_flags(), LP_find_file(), openssl_fopen(), RSA_meth_new(), RSA_meth_set_flags(), RSA_set_flags(), RSA_test_flags(), SSL_CONF_CTX_set_flags(), SSL_CTX_dane_set_flags(), SSL_dane_set_flags(), TS_RESP_CTX_add_flags(), WPACKET_set_flags(), X509_chain_check_suiteb(), X509_VERIFY_PARAM_set_flags(), X509_VERIFY_PARAM_set_hostflags(), X509_VERIFY_PARAM_set_inh_flags(), and X509V3_set_ctx().