crypto/evp/pmeth_gn.c File Reference
pmeth_gn.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/evp.h>
#include "internal/bn_int.h"
#include "internal/evp_int.h"
Functions
int EVP_PKEY_paramgen_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_paramgen (EVP_PKEY_CTX *ctx, EVP_PKEY **ppkey)
int EVP_PKEY_keygen_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_keygen (EVP_PKEY_CTX *ctx, EVP_PKEY **ppkey)
void EVP_PKEY_CTX_set_cb (EVP_PKEY_CTX *ctx, EVP_PKEY_gen_cb *cb)
EVP_PKEY_gen_cb * EVP_PKEY_CTX_get_cb (EVP_PKEY_CTX *ctx)
void evp_pkey_set_cb_translate (BN_GENCB *cb, EVP_PKEY_CTX *ctx)
int EVP_PKEY_CTX_get_keygen_info (EVP_PKEY_CTX *ctx, int idx)
EVP_PKEY * EVP_PKEY_new_mac_key (int type, ENGINE *e, const unsigned char *key, int keylen)
Function Documentation
EVP_PKEY_CTX_get_cb()
EVP_PKEY_gen_cb* EVP_PKEY_CTX_get_cb (EVP_PKEY_CTX * ctx)
Definition at line 120 of file pmeth_gn.c.
EVP_PKEY_CTX_get_keygen_info()
int EVP_PKEY_CTX_get_keygen_info (EVP_PKEY_CTX * ctx, int idx)
Definition at line 143 of file pmeth_gn.c.
EVP_PKEY_CTX_set_cb()
void EVP_PKEY_CTX_set_cb (EVP_PKEY_CTX * ctx, EVP_PKEY_gen_cb * cb)
Definition at line 115 of file pmeth_gn.c.
References cb.
EVP_PKEY_keygen()
int EVP_PKEY_keygen (EVP_PKEY_CTX * ctx, EVP_PKEY ** ppkey)
Definition at line 85 of file pmeth_gn.c.
Referenced by EVP_PKEY_new_mac_key().
EVP_PKEY_keygen_init()
int EVP_PKEY_keygen_init (EVP_PKEY_CTX * ctx)
Definition at line 68 of file pmeth_gn.c.
Referenced by EVP_PKEY_new_mac_key().
EVP_PKEY_new_mac_key()
EVP_PKEY* EVP_PKEY_new_mac_key (int type, ENGINE * e, const unsigned char * key, int keylen)
Definition at line 152 of file pmeth_gn.c.
References EVP_PKEY_CTX_free(), EVP_PKEY_CTX_new_id(), EVP_PKEY_CTX_set_mac_key, EVP_PKEY_keygen(), EVP_PKEY_keygen_init(), mac_key, and NULL.
EVP_PKEY_paramgen()
int EVP_PKEY_paramgen (EVP_PKEY_CTX * ctx, EVP_PKEY ** ppkey)
Definition at line 35 of file pmeth_gn.c.
EVP_PKEY_paramgen_init()
int EVP_PKEY_paramgen_init (EVP_PKEY_CTX * ctx)
Definition at line 18 of file pmeth_gn.c.
evp_pkey_set_cb_translate()
void evp_pkey_set_cb_translate (BN_GENCB * cb, EVP_PKEY_CTX * ctx)
Definition at line 138 of file pmeth_gn.c.
References BN_GENCB_set().