crypto/evp/pmeth_lib.c File Reference
pmeth_lib.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "internal/cryptlib.h"
#include <openssl/engine.h>
#include <openssl/evp.h>
#include <openssl/x509v3.h>
#include "internal/asn1_int.h"
#include "internal/evp_int.h"
#include "internal/numbers.h"
Typedefs
typedef int sk_cmp_fn_type(const char *const *a, const char *const *b)
Functions
DECLARE_OBJ_BSEARCH_CMP_FN (const EVP_PKEY_METHOD *, const EVP_PKEY_METHOD *, pmeth)
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const EVP_PKEY_METHOD *, const EVP_PKEY_METHOD *, pmeth)
const EVP_PKEY_METHOD * EVP_PKEY_meth_find (int type)
EVP_PKEY_METHOD * EVP_PKEY_meth_new (int id, int flags)
void EVP_PKEY_meth_get0_info (int *ppkey_id, int *pflags, const EVP_PKEY_METHOD *meth)
void EVP_PKEY_meth_copy (EVP_PKEY_METHOD *dst, const EVP_PKEY_METHOD *src)
void EVP_PKEY_meth_free (EVP_PKEY_METHOD *pmeth)
EVP_PKEY_CTX * EVP_PKEY_CTX_new (EVP_PKEY *pkey, ENGINE *e)
EVP_PKEY_CTX * EVP_PKEY_CTX_new_id (int id, ENGINE *e)
EVP_PKEY_CTX * EVP_PKEY_CTX_dup (EVP_PKEY_CTX *pctx)
int EVP_PKEY_meth_add0 (const EVP_PKEY_METHOD *pmeth)
void EVP_PKEY_CTX_free (EVP_PKEY_CTX *ctx)
int EVP_PKEY_CTX_ctrl (EVP_PKEY_CTX *ctx, int keytype, int optype, int cmd, int p1, void *p2)
int EVP_PKEY_CTX_ctrl_str (EVP_PKEY_CTX *ctx, const char *name, const char *value)
int EVP_PKEY_CTX_str2ctrl (EVP_PKEY_CTX *ctx, int cmd, const char *str)
int EVP_PKEY_CTX_hex2ctrl (EVP_PKEY_CTX *ctx, int cmd, const char *hex)
int EVP_PKEY_CTX_md (EVP_PKEY_CTX *ctx, int optype, int cmd, const char *md)
int EVP_PKEY_CTX_get_operation (EVP_PKEY_CTX *ctx)
void EVP_PKEY_CTX_set0_keygen_info (EVP_PKEY_CTX *ctx, int *dat, int datlen)
void EVP_PKEY_CTX_set_data (EVP_PKEY_CTX *ctx, void *data)
void * EVP_PKEY_CTX_get_data (EVP_PKEY_CTX *ctx)
EVP_PKEY * EVP_PKEY_CTX_get0_pkey (EVP_PKEY_CTX *ctx)
EVP_PKEY * EVP_PKEY_CTX_get0_peerkey (EVP_PKEY_CTX *ctx)
void EVP_PKEY_CTX_set_app_data (EVP_PKEY_CTX *ctx, void *data)
void * EVP_PKEY_CTX_get_app_data (EVP_PKEY_CTX *ctx)
void EVP_PKEY_meth_set_init (EVP_PKEY_METHOD *pmeth, int(*init)(EVP_PKEY_CTX *ctx))
void EVP_PKEY_meth_set_copy (EVP_PKEY_METHOD *pmeth, int(*copy)(EVP_PKEY_CTX *dst, EVP_PKEY_CTX *src))
void EVP_PKEY_meth_set_cleanup (EVP_PKEY_METHOD *pmeth, void(*cleanup)(EVP_PKEY_CTX *ctx))
void EVP_PKEY_meth_set_paramgen (EVP_PKEY_METHOD *pmeth, int(*paramgen_init)(EVP_PKEY_CTX *ctx), int(*paramgen)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey))
void EVP_PKEY_meth_set_keygen (EVP_PKEY_METHOD *pmeth, int(*keygen_init)(EVP_PKEY_CTX *ctx), int(*keygen)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey))
void EVP_PKEY_meth_set_sign (EVP_PKEY_METHOD *pmeth, int(*sign_init)(EVP_PKEY_CTX *ctx), int(*sign)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen))
void EVP_PKEY_meth_set_verify (EVP_PKEY_METHOD *pmeth, int(*verify_init)(EVP_PKEY_CTX *ctx), int(*verify)(EVP_PKEY_CTX *ctx, const unsigned char *sig, size_t siglen, const unsigned char *tbs, size_t tbslen))
void EVP_PKEY_meth_set_verify_recover (EVP_PKEY_METHOD *pmeth, int(*verify_recover_init)(EVP_PKEY_CTX *ctx), int(*verify_recover)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen))
void EVP_PKEY_meth_set_signctx (EVP_PKEY_METHOD *pmeth, int(*signctx_init)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx), int(*signctx)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, EVP_MD_CTX *mctx))
void EVP_PKEY_meth_set_verifyctx (EVP_PKEY_METHOD *pmeth, int(*verifyctx_init)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx), int(*verifyctx)(EVP_PKEY_CTX *ctx, const unsigned char *sig, int siglen, EVP_MD_CTX *mctx))
void EVP_PKEY_meth_set_encrypt (EVP_PKEY_METHOD *pmeth, int(*encrypt_init)(EVP_PKEY_CTX *ctx), int(*encryptfn)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen))
void EVP_PKEY_meth_set_decrypt (EVP_PKEY_METHOD *pmeth, int(*decrypt_init)(EVP_PKEY_CTX *ctx), int(*decrypt)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen))
void EVP_PKEY_meth_set_derive (EVP_PKEY_METHOD *pmeth, int(*derive_init)(EVP_PKEY_CTX *ctx), int(*derive)(EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen))
void EVP_PKEY_meth_set_ctrl (EVP_PKEY_METHOD *pmeth, int(*ctrl)(EVP_PKEY_CTX *ctx, int type, int p1, void *p2), int(*ctrl_str)(EVP_PKEY_CTX *ctx, const char *type, const char *value))
void EVP_PKEY_meth_get_init (EVP_PKEY_METHOD *pmeth, int(**pinit)(EVP_PKEY_CTX *ctx))
void EVP_PKEY_meth_get_copy (EVP_PKEY_METHOD *pmeth, int(**pcopy)(EVP_PKEY_CTX *dst, EVP_PKEY_CTX *src))
void EVP_PKEY_meth_get_cleanup (EVP_PKEY_METHOD *pmeth, void(**pcleanup)(EVP_PKEY_CTX *ctx))
void EVP_PKEY_meth_get_paramgen (EVP_PKEY_METHOD *pmeth, int(**pparamgen_init)(EVP_PKEY_CTX *ctx), int(**pparamgen)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey))
void EVP_PKEY_meth_get_keygen (EVP_PKEY_METHOD *pmeth, int(**pkeygen_init)(EVP_PKEY_CTX *ctx), int(**pkeygen)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey))
void EVP_PKEY_meth_get_sign (EVP_PKEY_METHOD *pmeth, int(**psign_init)(EVP_PKEY_CTX *ctx), int(**psign)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen))
void EVP_PKEY_meth_get_verify (EVP_PKEY_METHOD *pmeth, int(**pverify_init)(EVP_PKEY_CTX *ctx), int(**pverify)(EVP_PKEY_CTX *ctx, const unsigned char *sig, size_t siglen, const unsigned char *tbs, size_t tbslen))
void EVP_PKEY_meth_get_verify_recover (EVP_PKEY_METHOD *pmeth, int(**pverify_recover_init)(EVP_PKEY_CTX *ctx), int(**pverify_recover)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen))
void EVP_PKEY_meth_get_signctx (EVP_PKEY_METHOD *pmeth, int(**psignctx_init)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx), int(**psignctx)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, EVP_MD_CTX *mctx))
void EVP_PKEY_meth_get_verifyctx (EVP_PKEY_METHOD *pmeth, int(**pverifyctx_init)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx), int(**pverifyctx)(EVP_PKEY_CTX *ctx, const unsigned char *sig, int siglen, EVP_MD_CTX *mctx))
void EVP_PKEY_meth_get_encrypt (EVP_PKEY_METHOD *pmeth, int(**pencrypt_init)(EVP_PKEY_CTX *ctx), int(**pencryptfn)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen))
void EVP_PKEY_meth_get_decrypt (EVP_PKEY_METHOD *pmeth, int(**pdecrypt_init)(EVP_PKEY_CTX *ctx), int(**pdecrypt)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen))
void EVP_PKEY_meth_get_derive (EVP_PKEY_METHOD *pmeth, int(**pderive_init)(EVP_PKEY_CTX *ctx), int(**pderive)(EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen))
void EVP_PKEY_meth_get_ctrl (EVP_PKEY_METHOD *pmeth, int(**pctrl)(EVP_PKEY_CTX *ctx, int type, int p1, void *p2), int(**pctrl_str)(EVP_PKEY_CTX *ctx, const char *type, const char *value))
Typedef Documentation
sk_cmp_fn_type
typedef int sk_cmp_fn_type(const char *const *a, const char *const *b)
Definition at line 20 of file pmeth_lib.c.
Function Documentation
DECLARE_OBJ_BSEARCH_CMP_FN()
DECLARE_OBJ_BSEARCH_CMP_FN (const EVP_PKEY_METHOD * , const EVP_PKEY_METHOD * , pmeth)
EVP_PKEY_CTX_ctrl()
int EVP_PKEY_CTX_ctrl (EVP_PKEY_CTX * ctx, int keytype, int optype, int cmd, int p1, void * p2)
Definition at line 304 of file pmeth_lib.c.
Referenced by EVP_DigestInit_ex(), and RSA_pkey_ctx_ctrl().
EVP_PKEY_CTX_ctrl_str()
int EVP_PKEY_CTX_ctrl_str (EVP_PKEY_CTX * ctx, const char * name, const char * value)
Definition at line 334 of file pmeth_lib.c.
References EVP_F_EVP_PKEY_CTX_CTRL_STR, EVP_PKEY_CTRL_MD, EVP_PKEY_CTX_md(), EVP_PKEY_OP_TYPE_SIG, EVP_R_COMMAND_NOT_SUPPORTED, and EVPerr.
Referenced by pkey_ctrl_string().
EVP_PKEY_CTX_dup()
EVP_PKEY_CTX* EVP_PKEY_CTX_dup (EVP_PKEY_CTX * pctx)
Definition at line 233 of file pmeth_lib.c.
Referenced by EVP_DigestSignFinal().
EVP_PKEY_CTX_free()
void EVP_PKEY_CTX_free (EVP_PKEY_CTX * ctx)
Definition at line 290 of file pmeth_lib.c.
References ENGINE_finish(), EVP_PKEY_free(), NULL, and OPENSSL_free.
Referenced by EVP_DigestSignFinal(), EVP_MD_CTX_reset(), EVP_PKEY_new_mac_key(), EVP_SignFinal(), and EVP_VerifyFinal().
EVP_PKEY_CTX_get0_peerkey()
EVP_PKEY* EVP_PKEY_CTX_get0_peerkey (EVP_PKEY_CTX * ctx)
Definition at line 412 of file pmeth_lib.c.
EVP_PKEY_CTX_get0_pkey()
EVP_PKEY* EVP_PKEY_CTX_get0_pkey (EVP_PKEY_CTX * ctx)
Definition at line 407 of file pmeth_lib.c.
Referenced by ASN1_item_sign_ctx().
EVP_PKEY_CTX_get_app_data()
void* EVP_PKEY_CTX_get_app_data (EVP_PKEY_CTX * ctx)
Definition at line 422 of file pmeth_lib.c.
EVP_PKEY_CTX_get_data()
void* EVP_PKEY_CTX_get_data (EVP_PKEY_CTX * ctx)
Definition at line 402 of file pmeth_lib.c.
EVP_PKEY_CTX_get_operation()
int EVP_PKEY_CTX_get_operation (EVP_PKEY_CTX * ctx)
Definition at line 386 of file pmeth_lib.c.
EVP_PKEY_CTX_hex2ctrl()
int EVP_PKEY_CTX_hex2ctrl (EVP_PKEY_CTX * ctx, int cmd, const char * hex)
Definition at line 359 of file pmeth_lib.c.
References NULL, OPENSSL_free, and OPENSSL_hexstr2buf().
EVP_PKEY_CTX_md()
int EVP_PKEY_CTX_md (EVP_PKEY_CTX * ctx, int optype, int cmd, const char * md)
Definition at line 375 of file pmeth_lib.c.
Referenced by EVP_PKEY_CTX_ctrl_str().
EVP_PKEY_CTX_new()
EVP_PKEY_CTX* EVP_PKEY_CTX_new (EVP_PKEY * pkey, ENGINE * e)
Definition at line 223 of file pmeth_lib.c.
Referenced by EVP_SignFinal(), and EVP_VerifyFinal().
EVP_PKEY_CTX_new_id()
EVP_PKEY_CTX* EVP_PKEY_CTX_new_id (int id, ENGINE * e)
Definition at line 228 of file pmeth_lib.c.
Referenced by EVP_PKEY_new_mac_key().
EVP_PKEY_CTX_set0_keygen_info()
void EVP_PKEY_CTX_set0_keygen_info (EVP_PKEY_CTX * ctx, int * dat, int datlen)
Definition at line 391 of file pmeth_lib.c.
EVP_PKEY_CTX_set_app_data()
void EVP_PKEY_CTX_set_app_data (EVP_PKEY_CTX * ctx, void * data)
Definition at line 417 of file pmeth_lib.c.
References data.
EVP_PKEY_CTX_set_data()
void EVP_PKEY_CTX_set_data (EVP_PKEY_CTX * ctx, void * data)
Definition at line 397 of file pmeth_lib.c.
References data.
EVP_PKEY_CTX_str2ctrl()
int EVP_PKEY_CTX_str2ctrl (EVP_PKEY_CTX * ctx, int cmd, const char * str)
Definition at line 349 of file pmeth_lib.c.
References len.
EVP_PKEY_meth_add0()
int EVP_PKEY_meth_add0 (const EVP_PKEY_METHOD * pmeth)
Definition at line 277 of file pmeth_lib.c.
References NULL.
EVP_PKEY_meth_copy()
void EVP_PKEY_meth_copy (EVP_PKEY_METHOD * dst, const EVP_PKEY_METHOD * src)
Definition at line 176 of file pmeth_lib.c.
EVP_PKEY_meth_find()
const EVP_PKEY_METHOD* EVP_PKEY_meth_find (int type)
Definition at line 72 of file pmeth_lib.c.
References t.
EVP_PKEY_meth_free()
void EVP_PKEY_meth_free (EVP_PKEY_METHOD * pmeth)
Definition at line 217 of file pmeth_lib.c.
References EVP_PKEY_FLAG_DYNAMIC, and OPENSSL_free.
Referenced by engine_pkey_meths_free().
EVP_PKEY_meth_get0_info()
void EVP_PKEY_meth_get0_info (int * ppkey_id, int * pflags, const EVP_PKEY_METHOD * meth)
Definition at line 167 of file pmeth_lib.c.
EVP_PKEY_meth_get_cleanup()
void EVP_PKEY_meth_get_cleanup (EVP_PKEY_METHOD * pmeth, void(**)(EVP_PKEY_CTX *ctx) pcleanup)
Definition at line 585 of file pmeth_lib.c.
EVP_PKEY_meth_get_copy()
void EVP_PKEY_meth_get_copy (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *dst, EVP_PKEY_CTX *src) pcopy)
Definition at line 578 of file pmeth_lib.c.
EVP_PKEY_meth_get_ctrl()
void EVP_PKEY_meth_get_ctrl (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx, int type, int p1, void *p2) pctrl, int(**)(EVP_PKEY_CTX *ctx, const char *type, const char *value) pctrl_str)
Definition at line 726 of file pmeth_lib.c.
EVP_PKEY_meth_get_decrypt()
void EVP_PKEY_meth_get_decrypt (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pdecrypt_init, int(**)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen) pdecrypt)
Definition at line 700 of file pmeth_lib.c.
EVP_PKEY_meth_get_derive()
void EVP_PKEY_meth_get_derive (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pderive_init, int(**)(EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen) pderive)
Definition at line 714 of file pmeth_lib.c.
EVP_PKEY_meth_get_encrypt()
void EVP_PKEY_meth_get_encrypt (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pencrypt_init, int(**)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen) pencryptfn)
Definition at line 686 of file pmeth_lib.c.
EVP_PKEY_meth_get_init()
void EVP_PKEY_meth_get_init (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pinit)
Definition at line 572 of file pmeth_lib.c.
EVP_PKEY_meth_get_keygen()
void EVP_PKEY_meth_get_keygen (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pkeygen_init, int(**)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey) pkeygen)
Definition at line 602 of file pmeth_lib.c.
EVP_PKEY_meth_get_paramgen()
void EVP_PKEY_meth_get_paramgen (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pparamgen_init, int(**)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey) pparamgen)
Definition at line 591 of file pmeth_lib.c.
EVP_PKEY_meth_get_sign()
void EVP_PKEY_meth_get_sign (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) psign_init, int(**)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen) psign)
Definition at line 613 of file pmeth_lib.c.
EVP_PKEY_meth_get_signctx()
void EVP_PKEY_meth_get_signctx (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx) psignctx_init, int(**)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, EVP_MD_CTX *mctx) psignctx)
Definition at line 658 of file pmeth_lib.c.
EVP_PKEY_meth_get_verify()
void EVP_PKEY_meth_get_verify (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pverify_init, int(**)(EVP_PKEY_CTX *ctx, const unsigned char *sig, size_t siglen, const unsigned char *tbs, size_t tbslen) pverify)
Definition at line 626 of file pmeth_lib.c.
EVP_PKEY_meth_get_verify_recover()
void EVP_PKEY_meth_get_verify_recover (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx) pverify_recover_init, int(**)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen) pverify_recover)
Definition at line 640 of file pmeth_lib.c.
EVP_PKEY_meth_get_verifyctx()
void EVP_PKEY_meth_get_verifyctx (EVP_PKEY_METHOD * pmeth, int(**)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx) pverifyctx_init, int(**)(EVP_PKEY_CTX *ctx, const unsigned char *sig, int siglen, EVP_MD_CTX *mctx) pverifyctx)
Definition at line 672 of file pmeth_lib.c.
EVP_PKEY_meth_new()
EVP_PKEY_METHOD* EVP_PKEY_meth_new (int id, int flags)
Definition at line 154 of file pmeth_lib.c.
References EVP_PKEY_FLAG_DYNAMIC, NULL, and OPENSSL_zalloc.
EVP_PKEY_meth_set_cleanup()
void EVP_PKEY_meth_set_cleanup (EVP_PKEY_METHOD * pmeth, void(*)(EVP_PKEY_CTX *ctx) cleanup)
Definition at line 440 of file pmeth_lib.c.
EVP_PKEY_meth_set_copy()
void EVP_PKEY_meth_set_copy (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *dst, EVP_PKEY_CTX *src) copy)
Definition at line 433 of file pmeth_lib.c.
EVP_PKEY_meth_set_ctrl()
void EVP_PKEY_meth_set_ctrl (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx, int type, int p1, void *p2) ctrl, int(*)(EVP_PKEY_CTX *ctx, const char *type, const char *value) ctrl_str)
Definition at line 561 of file pmeth_lib.c.
EVP_PKEY_meth_set_decrypt()
void EVP_PKEY_meth_set_decrypt (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) decrypt_init, int(*)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen) decrypt)
Definition at line 539 of file pmeth_lib.c.
EVP_PKEY_meth_set_derive()
void EVP_PKEY_meth_set_derive (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) derive_init, int(*)(EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen) derive)
Definition at line 551 of file pmeth_lib.c.
EVP_PKEY_meth_set_encrypt()
void EVP_PKEY_meth_set_encrypt (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) encrypt_init, int(*)(EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen) encryptfn)
Definition at line 527 of file pmeth_lib.c.
EVP_PKEY_meth_set_init()
void EVP_PKEY_meth_set_init (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) init)
Definition at line 427 of file pmeth_lib.c.
EVP_PKEY_meth_set_keygen()
void EVP_PKEY_meth_set_keygen (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) keygen_init, int(*)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey) keygen)
Definition at line 455 of file pmeth_lib.c.
EVP_PKEY_meth_set_paramgen()
void EVP_PKEY_meth_set_paramgen (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) paramgen_init, int(*)(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey) paramgen)
Definition at line 446 of file pmeth_lib.c.
EVP_PKEY_meth_set_sign()
void EVP_PKEY_meth_set_sign (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) sign_init, int(*)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen) sign)
Definition at line 464 of file pmeth_lib.c.
EVP_PKEY_meth_set_signctx()
void EVP_PKEY_meth_set_signctx (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx) signctx_init, int(*)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, EVP_MD_CTX *mctx) signctx)
Definition at line 503 of file pmeth_lib.c.
EVP_PKEY_meth_set_verify()
void EVP_PKEY_meth_set_verify (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) verify_init, int(*)(EVP_PKEY_CTX *ctx, const unsigned char *sig, size_t siglen, const unsigned char *tbs, size_t tbslen) verify)
Definition at line 475 of file pmeth_lib.c.
EVP_PKEY_meth_set_verify_recover()
void EVP_PKEY_meth_set_verify_recover (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx) verify_recover_init, int(*)(EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen) verify_recover)
Definition at line 487 of file pmeth_lib.c.
EVP_PKEY_meth_set_verifyctx()
void EVP_PKEY_meth_set_verifyctx (EVP_PKEY_METHOD * pmeth, int(*)(EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx) verifyctx_init, int(*)(EVP_PKEY_CTX *ctx, const unsigned char *sig, int siglen, EVP_MD_CTX *mctx) verifyctx)
Definition at line 515 of file pmeth_lib.c.
IMPLEMENT_OBJ_BSEARCH_CMP_FN()
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const EVP_PKEY_METHOD * , const EVP_PKEY_METHOD * , pmeth)