crypto/evp/pmeth_fn.c File Reference
pmeth_fn.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/evp.h>
#include "internal/evp_int.h"
Macros
#define M_check_autoarg(ctx, arg, arglen, err)
Functions
int EVP_PKEY_sign_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_sign (EVP_PKEY_CTX *ctx, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen)
int EVP_PKEY_verify_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_verify (EVP_PKEY_CTX *ctx, const unsigned char *sig, size_t siglen, const unsigned char *tbs, size_t tbslen)
int EVP_PKEY_verify_recover_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_verify_recover (EVP_PKEY_CTX *ctx, unsigned char *rout, size_t *routlen, const unsigned char *sig, size_t siglen)
int EVP_PKEY_encrypt_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_encrypt (EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen)
int EVP_PKEY_decrypt_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_decrypt (EVP_PKEY_CTX *ctx, unsigned char *out, size_t *outlen, const unsigned char *in, size_t inlen)
int EVP_PKEY_derive_init (EVP_PKEY_CTX *ctx)
int EVP_PKEY_derive_set_peer (EVP_PKEY_CTX *ctx, EVP_PKEY *peer)
int EVP_PKEY_derive (EVP_PKEY_CTX *ctx, unsigned char *key, size_t *pkeylen)
Macro Definition Documentation
M_check_autoarg
#define M_check_autoarg (ctx, arg, arglen, err)
Value:
if (ctx->pmeth->flags & EVP_PKEY_FLAG_AUTOARGLEN) {           \
        size_t pksize = (size_t)EVP_PKEY_size(ctx->pkey);         \
                                                                  \
        if (pksize == 0) {                                        \
            EVPerr(err, EVP_R_INVALID_KEY); /*ckerr_ignore*/      \
            return 0;                                             \
        }                                                         \
        if (!arg) {                                               \
            *arglen = pksize;                                     \
            return 1;                                             \
        }                                                         \
        if (*arglen < pksize) {                                   \
            EVPerr(err, EVP_R_BUFFER_TOO_SMALL); /*ckerr_ignore*/ \
            return 0;                                             \
        }                                                         \
    }
Definition at line 17 of file pmeth_fn.c.
Referenced by EVP_PKEY_derive(), EVP_PKEY_sign(), and EVP_PKEY_verify_recover().
Function Documentation
EVP_PKEY_decrypt()
int EVP_PKEY_decrypt (EVP_PKEY_CTX * ctx, unsigned char * out, size_t * outlen, const unsigned char * in, size_t inlen)
Definition at line 187 of file pmeth_fn.c.
EVP_PKEY_decrypt_init()
int EVP_PKEY_decrypt_init (EVP_PKEY_CTX * ctx)
Definition at line 170 of file pmeth_fn.c.
EVP_PKEY_derive()
int EVP_PKEY_derive (EVP_PKEY_CTX * ctx, unsigned char * key, size_t * pkeylen)
Definition at line 284 of file pmeth_fn.c.
References EVP_F_EVP_PKEY_DERIVE, EVP_PKEY_OP_DERIVE, EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE, EVP_R_OPERATON_NOT_INITIALIZED, EVPerr, and M_check_autoarg.
EVP_PKEY_derive_init()
int EVP_PKEY_derive_init (EVP_PKEY_CTX * ctx)
Definition at line 204 of file pmeth_fn.c.
EVP_PKEY_derive_set_peer()
int EVP_PKEY_derive_set_peer (EVP_PKEY_CTX * ctx, EVP_PKEY * peer)
Definition at line 221 of file pmeth_fn.c.
EVP_PKEY_encrypt()
int EVP_PKEY_encrypt (EVP_PKEY_CTX * ctx, unsigned char * out, size_t * outlen, const unsigned char * in, size_t inlen)
Definition at line 153 of file pmeth_fn.c.
EVP_PKEY_encrypt_init()
int EVP_PKEY_encrypt_init (EVP_PKEY_CTX * ctx)
Definition at line 136 of file pmeth_fn.c.
EVP_PKEY_sign()
int EVP_PKEY_sign (EVP_PKEY_CTX * ctx, unsigned char * sig, size_t * siglen, const unsigned char * tbs, size_t tbslen)
Definition at line 52 of file pmeth_fn.c.
References EVP_F_EVP_PKEY_SIGN, EVP_PKEY_OP_SIGN, EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE, EVP_R_OPERATON_NOT_INITIALIZED, EVPerr, and M_check_autoarg.
Referenced by EVP_SignFinal().
EVP_PKEY_sign_init()
int EVP_PKEY_sign_init (EVP_PKEY_CTX * ctx)
Definition at line 35 of file pmeth_fn.c.
Referenced by EVP_SignFinal().
EVP_PKEY_verify()
int EVP_PKEY_verify (EVP_PKEY_CTX * ctx, const unsigned char * sig, size_t siglen, const unsigned char * tbs, size_t tbslen)
Definition at line 86 of file pmeth_fn.c.
References EVP_F_EVP_PKEY_VERIFY, EVP_PKEY_OP_VERIFY, EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE, EVP_R_OPERATON_NOT_INITIALIZED, and EVPerr.
Referenced by EVP_VerifyFinal().
EVP_PKEY_verify_init()
int EVP_PKEY_verify_init (EVP_PKEY_CTX * ctx)
Definition at line 69 of file pmeth_fn.c.
Referenced by EVP_VerifyFinal().
EVP_PKEY_verify_recover()
int EVP_PKEY_verify_recover (EVP_PKEY_CTX * ctx, unsigned char * rout, size_t * routlen, const unsigned char * sig, size_t siglen)
Definition at line 119 of file pmeth_fn.c.
References EVP_F_EVP_PKEY_VERIFY_RECOVER, EVP_PKEY_OP_VERIFYRECOVER, EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE, EVP_R_OPERATON_NOT_INITIALIZED, EVPerr, and M_check_autoarg.
EVP_PKEY_verify_recover_init()
int EVP_PKEY_verify_recover_init (EVP_PKEY_CTX * ctx)
Definition at line 102 of file pmeth_fn.c.