crypto/ppccap.c File Reference
ppccap.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>
#include <signal.h>
#include <unistd.h>
#include <openssl/crypto.h>
#include <openssl/bn.h>
#include "ppc_arch.h"
Macros
#define HWCAP 16 /* AT_HWCAP */
#define HWCAP_PPC64 (1U << 30)
#define HWCAP_ALTIVEC (1U << 28)
#define HWCAP_FPU (1U << 27)
#define HWCAP_POWER6_EXT (1U << 9)
#define HWCAP_VSX (1U << 7)
#define HWCAP2 26 /* AT_HWCAP2 */
#define HWCAP_VEC_CRYPTO (1U << 25)
#define HWCAP_ARCH_3_00 (1U << 23)
Functions
void sha256_block_p8 (void *ctx, const void *inp, size_t len)
void sha256_block_ppc (void *ctx, const void *inp, size_t len)
void sha256_block_data_order (void *ctx, const void *inp, size_t len)
void sha512_block_p8 (void *ctx, const void *inp, size_t len)
void sha512_block_ppc (void *ctx, const void *inp, size_t len)
void sha512_block_data_order (void *ctx, const void *inp, size_t len)
void ChaCha20_ctr32_int (unsigned char *out, const unsigned char *inp, size_t len, const unsigned int key[8], const unsigned int counter[4])
void ChaCha20_ctr32_vmx (unsigned char *out, const unsigned char *inp, size_t len, const unsigned int key[8], const unsigned int counter[4])
void ChaCha20_ctr32 (unsigned char *out, const unsigned char *inp, size_t len, const unsigned int key[8], const unsigned int counter[4])
void poly1305_init_int (void *ctx, const unsigned char key[16])
void poly1305_blocks (void *ctx, const unsigned char *inp, size_t len, unsigned int padbit)
void poly1305_emit (void *ctx, unsigned char mac[16], const unsigned int nonce[4])
void poly1305_init_fpu (void *ctx, const unsigned char key[16])
void poly1305_blocks_fpu (void *ctx, const unsigned char *inp, size_t len, unsigned int padbit)
void poly1305_emit_fpu (void *ctx, unsigned char mac[16], const unsigned int nonce[4])
int poly1305_init (void *ctx, const unsigned char key[16], void *func[2])
void OPENSSL_fpu_probe (void)
void OPENSSL_ppc64_probe (void)
void OPENSSL_altivec_probe (void)
void OPENSSL_crypto207_probe (void)
void OPENSSL_madd300_probe (void)
void OPENSSL_cpuid_setup (void)
Variables
unsigned int OPENSSL_ppccap_P = 0
Macro Definition Documentation
HWCAP
#define HWCAP 16 /* AT_HWCAP */
Definition at line 169 of file ppccap.c.
HWCAP2
#define HWCAP2 26 /* AT_HWCAP2 */
Definition at line 176 of file ppccap.c.
HWCAP_ALTIVEC
#define HWCAP_ALTIVEC (1U << 28)
Definition at line 171 of file ppccap.c.
HWCAP_ARCH_3_00
#define HWCAP_ARCH_3_00 (1U << 23)
Definition at line 178 of file ppccap.c.
HWCAP_FPU
#define HWCAP_FPU (1U << 27)
Definition at line 172 of file ppccap.c.
HWCAP_POWER6_EXT
#define HWCAP_POWER6_EXT (1U << 9)
Definition at line 173 of file ppccap.c.
HWCAP_PPC64
#define HWCAP_PPC64 (1U << 30)
Definition at line 170 of file ppccap.c.
HWCAP_VEC_CRYPTO
#define HWCAP_VEC_CRYPTO (1U << 25)
Definition at line 177 of file ppccap.c.
HWCAP_VSX
#define HWCAP_VSX (1U << 7)
Definition at line 174 of file ppccap.c.
Function Documentation
ChaCha20_ctr32()
void ChaCha20_ctr32 (unsigned char * out, const unsigned char * inp, size_t len, const unsigned int key[8], const unsigned int counter[4])
Definition at line 84 of file ppccap.c.
ChaCha20_ctr32_int()
void ChaCha20_ctr32_int (unsigned char * out, const unsigned char * inp, size_t len, const unsigned int key[8], const unsigned int counter[4])
Referenced by sha512_block_data_order().
ChaCha20_ctr32_vmx()
void ChaCha20_ctr32_vmx (unsigned char * out, const unsigned char * inp, size_t len, const unsigned int key[8], const unsigned int counter[4])
OPENSSL_altivec_probe()
void OPENSSL_altivec_probe (void)
OPENSSL_cpuid_setup()
void OPENSSL_cpuid_setup (void)
Definition at line 183 of file ppccap.c.
References e, NULL, OPENSSL_ppccap_P, PPC_ALTIVEC, PPC_CRYPTO207, PPC_FPU, PPC_FPU64, and PPC_MADD300.
OPENSSL_crypto207_probe()
void OPENSSL_crypto207_probe (void)
OPENSSL_fpu_probe()
void OPENSSL_fpu_probe (void)
OPENSSL_madd300_probe()
void OPENSSL_madd300_probe (void)
OPENSSL_ppc64_probe()
void OPENSSL_ppc64_probe (void)
poly1305_blocks()
void poly1305_blocks (void * ctx, const unsigned char * inp, size_t len, unsigned int padbit)
Definition at line 81 of file poly1305_base2_44.c.
Referenced by poly1305_init().
poly1305_blocks_fpu()
void poly1305_blocks_fpu (void * ctx, const unsigned char * inp, size_t len, unsigned int padbit)
Referenced by poly1305_init().
poly1305_emit()
void poly1305_emit (void * ctx, unsigned char mac[16], const unsigned int nonce[4])
Definition at line 135 of file poly1305_base2_44.c.
References poly1305_internal::h, t, and U32TO8.
Referenced by poly1305_init().
poly1305_emit_fpu()
void poly1305_emit_fpu (void * ctx, unsigned char mac[16], const unsigned int nonce[4])
Referenced by poly1305_init().
poly1305_init()
int poly1305_init (void * ctx, const unsigned char key[16], void * func[2])
Definition at line 105 of file ppccap.c.
References ecp_nistz256_from_mont(), ecp_nistz256_mul_mont(), ecp_nistz256_to_mont(), in, OPENSSL_ppccap_P, poly1305_blocks(), poly1305_blocks_fpu(), poly1305_emit(), poly1305_emit_fpu(), poly1305_init_fpu(), poly1305_init_int(), and PPC_FPU.
poly1305_init_fpu()
void poly1305_init_fpu (void * ctx, const unsigned char key[16])
Referenced by poly1305_init().
poly1305_init_int()
void poly1305_init_int (void * ctx, const unsigned char key[16])
Referenced by poly1305_init().
sha256_block_data_order()
void sha256_block_data_order (void * ctx, const void * inp, size_t len)
Definition at line 63 of file ppccap.c.
References ctx, len, OPENSSL_ppccap_P, PPC_CRYPTO207, sha256_block_p8(), sha256_block_ppc(), sha512_block_p8(), and sha512_block_ppc().
sha256_block_p8()
void sha256_block_p8 (void * ctx, const void * inp, size_t len)
Referenced by sha256_block_data_order().
sha256_block_ppc()
void sha256_block_ppc (void * ctx, const void * inp, size_t len)
Referenced by sha256_block_data_order().
sha512_block_data_order()
void sha512_block_data_order (void * ctx, const void * inp, size_t len)
Definition at line 71 of file ppccap.c.
References ChaCha20_ctr32_int(), OPENSSL_ppccap_P, PPC_CRYPTO207, sha512_block_p8(), and sha512_block_ppc().
sha512_block_p8()
void sha512_block_p8 (void * ctx, const void * inp, size_t len)
Referenced by sha256_block_data_order(), and sha512_block_data_order().
sha512_block_ppc()
void sha512_block_ppc (void * ctx, const void * inp, size_t len)
Referenced by sha256_block_data_order(), and sha512_block_data_order().
Variable Documentation
OPENSSL_ppccap_P
unsigned int OPENSSL_ppccap_P = 0
Definition at line 30 of file ppccap.c.
Referenced by OPENSSL_cpuid_setup(), poly1305_init(), sha256_block_data_order(), and sha512_block_data_order().