ssl/pqueue.c File Reference
pqueue.c File Reference
#include "ssl_locl.h"
#include <openssl/bn.h>
Data Structures
struct pqueue
Functions
pitem * pitem_new (unsigned char *prio64be, void *data)
void pitem_free (pitem *item)
pqueue * pqueue_new ()
void pqueue_free (pqueue *pq)
pitem * pqueue_insert (pqueue *pq, pitem *item)
pitem * pqueue_peek (pqueue *pq)
pitem * pqueue_pop (pqueue *pq)
pitem * pqueue_find (pqueue *pq, unsigned char *prio64be)
pitem * pqueue_iterator (pqueue *pq)
pitem * pqueue_next (pitem **item)
size_t pqueue_size (pqueue *pq)
Function Documentation
pitem_free()
void pitem_free (pitem * item)
Definition at line 32 of file pqueue.c.
References OPENSSL_free.
Referenced by dtls1_buffer_record(), dtls1_clear_received_buffer(), dtls1_clear_sent_buffer(), and DTLS_RECORD_LAYER_clear().
pitem_new()
pitem* pitem_new (unsigned char * prio64be, void * data)
Definition at line 18 of file pqueue.c.
References data, NULL, and OPENSSL_malloc.
Referenced by dtls1_buffer_record().
pqueue_find()
pitem* pqueue_find (pqueue * pq, unsigned char * prio64be)
Definition at line 100 of file pqueue.c.
pqueue_free()
void pqueue_free (pqueue * pq)
Definition at line 44 of file pqueue.c.
References OPENSSL_free.
Referenced by dtls1_new(), DTLS_RECORD_LAYER_free(), and DTLS_RECORD_LAYER_new().
pqueue_insert()
pitem* pqueue_insert (pqueue * pq, pitem * item)
Definition at line 49 of file pqueue.c.
References NULL.
Referenced by dtls1_buffer_record().
pqueue_iterator()
pitem* pqueue_iterator (pqueue * pq)
Definition at line 125 of file pqueue.c.
References pqueue_peek().
pqueue_new()
pqueue* pqueue_new (void)
Definition at line 37 of file pqueue.c.
References OPENSSL_zalloc.
Referenced by dtls1_new(), and DTLS_RECORD_LAYER_new().
pqueue_next()
pitem* pqueue_next (pitem ** item)
Definition at line 130 of file pqueue.c.
pqueue_peek()
pitem* pqueue_peek (pqueue * pq)
Definition at line 85 of file pqueue.c.
Referenced by dtls1_process_buffered_records(), and pqueue_iterator().
pqueue_pop()
pitem* pqueue_pop (pqueue * pq)
Definition at line 90 of file pqueue.c.
References NULL.
Referenced by dtls1_clear_received_buffer(), dtls1_clear_sent_buffer(), dtls1_retrieve_buffered_record(), and DTLS_RECORD_LAYER_clear().
pqueue_size()
size_t pqueue_size (pqueue * pq)
Definition at line 144 of file pqueue.c.
References pqueue::count, and NULL.
Referenced by dtls1_buffer_record().