crypto/rand/rand_egd.c File Reference
rand_egd.c File Reference
#include <openssl/opensslconf.h>
#include <openssl/crypto.h>
#include <openssl/e_os2.h>
#include <openssl/rand.h>
#include <stddef.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <string.h>
#include <errno.h>
Functions
int RAND_query_egd_bytes (const char *path, unsigned char *buf, int bytes)
int RAND_egd_bytes (const char *path, int bytes)
int RAND_egd (const char *path)
Function Documentation
RAND_egd()
int RAND_egd (const char * path)
Definition at line 242 of file rand_egd.c.
References RAND_egd_bytes().
Referenced by app_RAND_load_file(), and app_RAND_load_files().
RAND_egd_bytes()
int RAND_egd_bytes (const char * path, int bytes)
Definition at line 229 of file rand_egd.c.
Referenced by RAND_egd().
RAND_query_egd_bytes()
int RAND_query_egd_bytes (const char * path, unsigned char * buf, int bytes)
Definition at line 92 of file rand_egd.c.