crypto/rand/rand_lib.c File Reference
rand_lib.c File Reference
#include <stdio.h>
#include <time.h>
#include "internal/cryptlib.h"
#include <openssl/opensslconf.h>
#include "internal/rand.h"
#include <openssl/engine.h>
Functions
int RAND_set_rand_method (const RAND_METHOD *meth)
const RAND_METHOD * RAND_get_rand_method (void)
int RAND_set_rand_engine (ENGINE *engine)
void rand_cleanup_int (void)
void RAND_seed (const void *buf, int num)
void RAND_add (const void *buf, int num, double entropy)
int RAND_bytes (unsigned char *buf, int num)
int RAND_pseudo_bytes (unsigned char *buf, int num)
int RAND_status (void)
Function Documentation
RAND_add()
void RAND_add (const void * buf, int num, double entropy)
Definition at line 95 of file rand_lib.c.
Referenced by EVP_PKEY2PKCS8().
RAND_bytes()
int RAND_bytes (unsigned char * buf, int num)
Definition at line 102 of file rand_lib.c.
Referenced by CMS_ReceiptRequest_create0(), EVP_CIPHER_CTX_rand_key(), PKCS12_setup_mac(), RSA_padding_add_PKCS1_type_2(), RSA_padding_add_SSLv23(), SRP_Calc_A_param(), SRP_create_verifier_BN(), ssl_fill_hello_random(), and SSL_srp_server_param_with_username().
rand_cleanup_int()
void rand_cleanup_int (void)
Definition at line 80 of file rand_lib.c.
References NULL, RAND_get_rand_method(), and RAND_set_rand_method().
RAND_get_rand_method()
const RAND_METHOD* RAND_get_rand_method (void)
Definition at line 39 of file rand_lib.c.
Referenced by rand_cleanup_int(), and RAND_status().
RAND_pseudo_bytes()
int RAND_pseudo_bytes (unsigned char * buf, int num)
Definition at line 111 of file rand_lib.c.
RAND_seed()
void RAND_seed (const void * buf, int num)
Definition at line 88 of file rand_lib.c.
Referenced by main(), and ossl_ecdsa_sign().
RAND_set_rand_engine()
int RAND_set_rand_engine (ENGINE * engine)
Definition at line 61 of file rand_lib.c.
References ENGINE_finish(), ENGINE_get_RAND(), ENGINE_init(), NULL, and RAND_set_rand_method().
RAND_set_rand_method()
int RAND_set_rand_method (const RAND_METHOD * meth)
Definition at line 29 of file rand_lib.c.
References ENGINE_finish().
Referenced by rand_cleanup_int(), RAND_set_rand_engine(), and restore_rand().
RAND_status()
int RAND_status (void)
Definition at line 120 of file rand_lib.c.
References RAND_get_rand_method().