ssl/record/rec_layer_d1.c File Reference
rec_layer_d1.c File Reference
#include <stdio.h>
#include <errno.h>
#include "../ssl_locl.h"
#include <openssl/evp.h>
#include <openssl/buffer.h>
#include "record_locl.h"
#include <assert.h>
Macros
#define USE_SOCKETS
#define dtls1_get_unprocessed_record(s)
Functions
int DTLS_RECORD_LAYER_new (RECORD_LAYER *rl)
void DTLS_RECORD_LAYER_free (RECORD_LAYER *rl)
void DTLS_RECORD_LAYER_clear (RECORD_LAYER *rl)
void DTLS_RECORD_LAYER_set_saved_w_epoch (RECORD_LAYER *rl, unsigned short e)
void DTLS_RECORD_LAYER_resync_write (RECORD_LAYER *rl)
void DTLS_RECORD_LAYER_set_write_sequence (RECORD_LAYER *rl, unsigned char *seq)
int dtls1_buffer_record (SSL *s, record_pqueue *queue, unsigned char *priority)
int dtls1_retrieve_buffered_record (SSL *s, record_pqueue *queue)
int dtls1_process_buffered_records (SSL *s)
int dtls1_read_bytes (SSL *s, int type, int *recvd_type, unsigned char *buf, size_t len, int peek, size_t *readbytes)
int dtls1_write_bytes (SSL *s, int type, const void *buf, size_t len, size_t *written)
int do_dtls1_write (SSL *s, int type, const unsigned char *buf, size_t len, int create_empty_fragment, size_t *written)
DTLS1_BITMAP * dtls1_get_bitmap (SSL *s, SSL3_RECORD *rr, unsigned int *is_next_epoch)
void dtls1_reset_seq_numbers (SSL *s, int rw)
Macro Definition Documentation
dtls1_get_unprocessed_record
#define dtls1_get_unprocessed_record (s)
Value:
dtls1_retrieve_buffered_record((s), \
                   &((s)->rlayer.d->unprocessed_rcds))
Definition at line 226 of file rec_layer_d1.c.
Referenced by dtls1_process_buffered_records().
USE_SOCKETS
#define USE_SOCKETS
Definition at line 12 of file rec_layer_d1.c.
Function Documentation
do_dtls1_write()
int do_dtls1_write (SSL * s, int type, const unsigned char * buf, size_t len, int create_empty_fragment, size_t * written)
Definition at line 916 of file rec_layer_d1.c.
dtls1_buffer_record()
int dtls1_buffer_record (SSL * s, record_pqueue * queue, unsigned char * priority)
Definition at line 145 of file rec_layer_d1.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_SCTP_GET_RCVINFO, BIO_dgram_is_sctp(), SSL3_BUFFER::buf, ERR_R_INTERNAL_ERROR, NULL, OPENSSL_free, OPENSSL_malloc, DTLS1_RECORD_DATA::packet, DTLS1_RECORD_DATA::packet_length, pitem_free(), pitem_new(), pqueue_insert(), pqueue_size(), record_pqueue::q, DTLS1_RECORD_DATA::rbuf, DTLS1_RECORD_DATA::recordinfo, DTLS1_RECORD_DATA::rrec, ssl3_setup_buffers(), SSL_F_DTLS1_BUFFER_RECORD, SSL_get_rbio(), SSL_get_state(), SSLerr, TLS_ST_CR_FINISHED, and TLS_ST_SR_FINISHED.
Referenced by dtls1_get_record(), and dtls1_process_buffered_records().
dtls1_get_bitmap()
DTLS1_BITMAP* dtls1_get_bitmap (SSL * s, SSL3_RECORD * rr, unsigned int * is_next_epoch)
Definition at line 1117 of file rec_layer_d1.c.
References SSL3_RECORD::epoch, NULL, SSL3_RT_ALERT, SSL3_RT_HANDSHAKE, and SSL3_RECORD::type.
Referenced by dtls1_get_record(), and dtls1_process_buffered_records().
dtls1_process_buffered_records()
int dtls1_process_buffered_records (SSL * s)
Definition at line 230 of file rec_layer_d1.c.
References BIO_dgram_is_sctp(), dtls1_buffer_record(), dtls1_get_bitmap(), dtls1_get_unprocessed_record, dtls1_process_record(), dtls1_record_replay_check(), ERR_R_INTERNAL_ERROR, SSL3_RECORD::length, NULL, pqueue_peek(), RECORD_LAYER_get_rbuf, RECORD_LAYER_get_rrec, RECORD_LAYER_reset_packet_length, SSL3_BUFFER_get_left, SSL3_RECORD_get_seq_num, SSL_F_DTLS1_PROCESS_BUFFERED_RECORDS, SSL_get_rbio(), and SSLerr.
Referenced by dtls1_get_record().
dtls1_read_bytes()
int dtls1_read_bytes (SSL * s, int type, int * recvd_type, unsigned char * buf, size_t len, int peek, size_t * readbytes)
Definition at line 339 of file rec_layer_d1.c.
dtls1_reset_seq_numbers()
void dtls1_reset_seq_numbers (SSL * s, int rw)
Definition at line 1142 of file rec_layer_d1.c.
References dtls1_clear_received_buffer(), seq, and SSL3_CC_READ.
Referenced by ossl_statem_client_post_work(), and ossl_statem_server_post_work().
dtls1_retrieve_buffered_record()
int dtls1_retrieve_buffered_record (SSL * s, record_pqueue * queue)
Definition at line 205 of file rec_layer_d1.c.
References pqueue_pop(), and record_pqueue::q.
dtls1_write_bytes()
int dtls1_write_bytes (SSL * s, int type, const void * buf, size_t len, size_t * written)
Definition at line 905 of file rec_layer_d1.c.
Referenced by dtls1_write_app_data_bytes().
DTLS_RECORD_LAYER_clear()
void DTLS_RECORD_LAYER_clear (RECORD_LAYER * rl)
Definition at line 55 of file rec_layer_d1.c.
References SSL3_BUFFER::buf, DTLS_RECORD_LAYER::buffered_app_data, RECORD_LAYER::d, NULL, OPENSSL_free, pitem_free(), pqueue_pop(), DTLS_RECORD_LAYER::processed_rcds, record_pqueue::q, DTLS1_RECORD_DATA::rbuf, and DTLS_RECORD_LAYER::unprocessed_rcds.
Referenced by dtls1_clear(), DTLS_RECORD_LAYER_free(), and RECORD_LAYER_clear().
DTLS_RECORD_LAYER_free()
void DTLS_RECORD_LAYER_free (RECORD_LAYER * rl)
Definition at line 45 of file rec_layer_d1.c.
References DTLS_RECORD_LAYER::buffered_app_data, RECORD_LAYER::d, DTLS_RECORD_LAYER_clear(), NULL, OPENSSL_free, pqueue_free(), DTLS_RECORD_LAYER::processed_rcds, record_pqueue::q, and DTLS_RECORD_LAYER::unprocessed_rcds.
Referenced by dtls1_free().
DTLS_RECORD_LAYER_new()
int DTLS_RECORD_LAYER_new (RECORD_LAYER * rl)
Definition at line 19 of file rec_layer_d1.c.
References DTLS_RECORD_LAYER::buffered_app_data, RECORD_LAYER::d, NULL, OPENSSL_free, OPENSSL_malloc, pqueue_free(), pqueue_new(), DTLS_RECORD_LAYER::processed_rcds, record_pqueue::q, and DTLS_RECORD_LAYER::unprocessed_rcds.
Referenced by dtls1_new().
DTLS_RECORD_LAYER_resync_write()
void DTLS_RECORD_LAYER_resync_write (RECORD_LAYER * rl)
Definition at line 112 of file rec_layer_d1.c.
References RECORD_LAYER::read_sequence, and RECORD_LAYER::write_sequence.
DTLS_RECORD_LAYER_set_saved_w_epoch()
void DTLS_RECORD_LAYER_set_saved_w_epoch (RECORD_LAYER * rl, unsigned short e)
Definition at line 96 of file rec_layer_d1.c.
References DTLS_RECORD_LAYER::curr_write_sequence, RECORD_LAYER::d, e, DTLS_RECORD_LAYER::last_write_sequence, DTLS_RECORD_LAYER::w_epoch, and RECORD_LAYER::write_sequence.
DTLS_RECORD_LAYER_set_write_sequence()
void DTLS_RECORD_LAYER_set_write_sequence (RECORD_LAYER * rl, unsigned char * seq)
Definition at line 117 of file rec_layer_d1.c.
References SEQ_NUM_SIZE, and RECORD_LAYER::write_sequence.