ssl/record/rec_layer_s3.c File Reference
rec_layer_s3.c File Reference
#include <stdio.h>
#include <assert.h>
#include <limits.h>
#include <errno.h>
#include "../ssl_locl.h"
#include <openssl/evp.h>
#include <openssl/buffer.h>
#include <openssl/rand.h>
#include "record_locl.h"
Macros
#define USE_SOCKETS
#define EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK 0
Functions
void RECORD_LAYER_init (RECORD_LAYER *rl, SSL *s)
void RECORD_LAYER_clear (RECORD_LAYER *rl)
void RECORD_LAYER_release (RECORD_LAYER *rl)
int RECORD_LAYER_read_pending (const RECORD_LAYER *rl)
int RECORD_LAYER_write_pending (const RECORD_LAYER *rl)
int RECORD_LAYER_set_data (RECORD_LAYER *rl, const unsigned char *buf, size_t len)
void RECORD_LAYER_reset_read_sequence (RECORD_LAYER *rl)
void RECORD_LAYER_reset_write_sequence (RECORD_LAYER *rl)
size_t ssl3_pending (const SSL *s)
void SSL_CTX_set_default_read_buffer_len (SSL_CTX *ctx, size_t len)
void SSL_set_default_read_buffer_len (SSL *s, size_t len)
const char * SSL_rstate_string_long (const SSL *s)
const char * SSL_rstate_string (const SSL *s)
int ssl3_read_n (SSL *s, size_t n, size_t max, int extend, int clearold, size_t *readbytes)
int ssl3_write_bytes (SSL *s, int type, const void *buf_, size_t len, size_t *written)
int do_ssl3_write (SSL *s, int type, const unsigned char *buf, size_t *pipelens, size_t numpipes, int create_empty_fragment, size_t *written)
int ssl3_write_pending (SSL *s, int type, const unsigned char *buf, size_t len, size_t *written)
int ssl3_read_bytes (SSL *s, int type, int *recvd_type, unsigned char *buf, size_t len, int peek, size_t *readbytes)
void ssl3_record_sequence_update (unsigned char *seq)
int RECORD_LAYER_is_sslv2_record (RECORD_LAYER *rl)
size_t RECORD_LAYER_get_rrec_length (RECORD_LAYER *rl)
Macro Definition Documentation
EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK
#define EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK 0
Definition at line 27 of file rec_layer_s3.c.
USE_SOCKETS
#define USE_SOCKETS
Definition at line 14 of file rec_layer_s3.c.
Function Documentation
do_ssl3_write()
int do_ssl3_write (SSL * s, int type, const unsigned char * buf, size_t * pipelens, size_t numpipes, int create_empty_fragment, size_t * written)
Definition at line 625 of file rec_layer_s3.c.
Referenced by ssl3_dispatch_alert().
RECORD_LAYER_clear()
void RECORD_LAYER_clear (RECORD_LAYER * rl)
Definition at line 37 of file rec_layer_s3.c.
References RECORD_LAYER::alert_fragment, RECORD_LAYER::alert_fragment_len, RECORD_LAYER::d, DTLS_RECORD_LAYER_clear(), RECORD_LAYER::handshake_fragment, RECORD_LAYER::handshake_fragment_len, NULL, RECORD_LAYER::numrpipes, RECORD_LAYER::packet, RECORD_LAYER::packet_length, RECORD_LAYER::rbuf, RECORD_LAYER_reset_read_sequence(), RECORD_LAYER_reset_write_sequence(), RECORD_LAYER::rrec, RECORD_LAYER::rstate, RECORD_LAYER::s, SSL3_BUFFER_clear(), SSL3_RECORD_clear(), ssl3_release_write_buffer(), SSL_MAX_PIPELINES, SSL_ST_READ_HEADER, RECORD_LAYER::wnum, RECORD_LAYER::wpend_buf, RECORD_LAYER::wpend_ret, RECORD_LAYER::wpend_tot, and RECORD_LAYER::wpend_type.
RECORD_LAYER_get_rrec_length()
size_t RECORD_LAYER_get_rrec_length (RECORD_LAYER * rl)
Definition at line 1608 of file rec_layer_s3.c.
References RECORD_LAYER::rrec, and SSL3_RECORD_get_length.
Referenced by tls_get_message_header().
RECORD_LAYER_init()
void RECORD_LAYER_init (RECORD_LAYER * rl, SSL * s)
Definition at line 30 of file rec_layer_s3.c.
References RECORD_LAYER_set_first_record, RECORD_LAYER::rrec, RECORD_LAYER::s, SSL3_RECORD_clear(), and SSL_MAX_PIPELINES.
Referenced by SSL_new().
RECORD_LAYER_is_sslv2_record()
int RECORD_LAYER_is_sslv2_record (RECORD_LAYER * rl)
Definition at line 1600 of file rec_layer_s3.c.
References RECORD_LAYER::rrec, and SSL3_RECORD_is_sslv2_record.
Referenced by tls_get_message_header().
RECORD_LAYER_read_pending()
int RECORD_LAYER_read_pending (const RECORD_LAYER * rl)
Definition at line 80 of file rec_layer_s3.c.
References RECORD_LAYER::rbuf, and SSL3_BUFFER_get_left.
Referenced by SSL_has_pending().
RECORD_LAYER_release()
void RECORD_LAYER_release (RECORD_LAYER * rl)
Definition at line 71 of file rec_layer_s3.c.
References RECORD_LAYER::numwpipes, RECORD_LAYER::rbuf, RECORD_LAYER::rrec, RECORD_LAYER::s, SSL3_BUFFER_is_initialised, SSL3_RECORD_release(), ssl3_release_read_buffer(), ssl3_release_write_buffer(), and SSL_MAX_PIPELINES.
RECORD_LAYER_reset_read_sequence()
void RECORD_LAYER_reset_read_sequence (RECORD_LAYER * rl)
Definition at line 108 of file rec_layer_s3.c.
Referenced by RECORD_LAYER_clear().
RECORD_LAYER_reset_write_sequence()
void RECORD_LAYER_reset_write_sequence (RECORD_LAYER * rl)
Definition at line 113 of file rec_layer_s3.c.
Referenced by RECORD_LAYER_clear().
RECORD_LAYER_set_data()
int RECORD_LAYER_set_data (RECORD_LAYER * rl, const unsigned char * buf, size_t len)
Definition at line 91 of file rec_layer_s3.c.
RECORD_LAYER_write_pending()
int RECORD_LAYER_write_pending (const RECORD_LAYER * rl)
Definition at line 85 of file rec_layer_s3.c.
References RECORD_LAYER::numwpipes, SSL3_BUFFER_get_left, and RECORD_LAYER::wbuf.
Referenced by ssl3_send_alert().
ssl3_pending()
size_t ssl3_pending (const SSL * s)
Definition at line 118 of file rec_layer_s3.c.
References RECORD_LAYER_get_numrpipes, SSL3_RECORD_get_length, SSL3_RECORD_get_type, SSL3_RT_APPLICATION_DATA, and SSL_ST_READ_BODY.
ssl3_read_bytes()
int ssl3_read_bytes (SSL * s, int type, int * recvd_type, unsigned char * buf, size_t len, int peek, size_t * readbytes)
Definition at line 1093 of file rec_layer_s3.c.
ssl3_read_n()
int ssl3_read_n (SSL * s, size_t n, size_t max, int extend, int clearold, size_t * readbytes)
Definition at line 176 of file rec_layer_s3.c.
References SSL3_BUFFER::buf, ERR_R_INTERNAL_ERROR, SSL3_BUFFER::left, SSL3_BUFFER::len, len, NULL, SSL3_BUFFER::offset, SSL3_ALIGN_PAYLOAD, SSL3_RT_APPLICATION_DATA, SSL3_RT_HEADER_LENGTH, ssl3_setup_read_buffer(), SSL_F_SSL3_READ_N, SSL_IS_DTLS, and SSLerr.
Referenced by dtls1_get_record().
ssl3_record_sequence_update()
void ssl3_record_sequence_update (unsigned char * seq)
Definition at line 1585 of file rec_layer_s3.c.
ssl3_write_bytes()
int ssl3_write_bytes (SSL * s, int type, const void * buf_, size_t len, size_t * written)
Definition at line 339 of file rec_layer_s3.c.
ssl3_write_pending()
int ssl3_write_pending (SSL * s, int type, const unsigned char * buf, size_t len, size_t * written)
Definition at line 1004 of file rec_layer_s3.c.
SSL_CTX_set_default_read_buffer_len()
void SSL_CTX_set_default_read_buffer_len (SSL_CTX * ctx, size_t len)
Definition at line 135 of file rec_layer_s3.c.
References len.
SSL_rstate_string()
const char* SSL_rstate_string (const SSL * s)
Definition at line 159 of file rec_layer_s3.c.
References SSL_ST_READ_BODY, SSL_ST_READ_DONE, and SSL_ST_READ_HEADER.
SSL_rstate_string_long()
const char* SSL_rstate_string_long (const SSL * s)
Definition at line 145 of file rec_layer_s3.c.
References SSL_ST_READ_BODY, SSL_ST_READ_DONE, and SSL_ST_READ_HEADER.
SSL_set_default_read_buffer_len()
void SSL_set_default_read_buffer_len (SSL * s, size_t len)
Definition at line 140 of file rec_layer_s3.c.
References RECORD_LAYER_get_rbuf, and SSL3_BUFFER_set_default_len.
Referenced by SSL_new().