ssl/record/record_locl.h File Reference
record_locl.h File Reference
Macros
#define MAX_WARN_ALERT_COUNT 5
#define RECORD_LAYER_get_rbuf(rl) (&(rl)->rbuf)
#define RECORD_LAYER_get_wbuf(rl) ((rl)->wbuf)
#define RECORD_LAYER_get_rrec(rl) ((rl)->rrec)
#define RECORD_LAYER_set_packet(rl, p) ((rl)->packet = (p))
#define RECORD_LAYER_reset_packet_length(rl) ((rl)->packet_length = 0)
#define RECORD_LAYER_get_rstate(rl) ((rl)->rstate)
#define RECORD_LAYER_set_rstate(rl, st) ((rl)->rstate = (st))
#define RECORD_LAYER_get_read_sequence(rl) ((rl)->read_sequence)
#define RECORD_LAYER_get_write_sequence(rl) ((rl)->write_sequence)
#define RECORD_LAYER_get_numrpipes(rl) ((rl)->numrpipes)
#define RECORD_LAYER_set_numrpipes(rl, n) ((rl)->numrpipes = (n))
#define RECORD_LAYER_inc_empty_record_count(rl) ((rl)->empty_record_count++)
#define RECORD_LAYER_reset_empty_record_count(rl) ((rl)->empty_record_count = 0)
#define RECORD_LAYER_get_empty_record_count(rl) ((rl)->empty_record_count)
#define RECORD_LAYER_is_first_record(rl) ((rl)->is_first_record)
#define RECORD_LAYER_set_first_record(rl) ((rl)->is_first_record = 1)
#define RECORD_LAYER_clear_first_record(rl) ((rl)->is_first_record = 0)
#define DTLS_RECORD_LAYER_get_r_epoch(rl) ((rl)->d->r_epoch)
#define SSL3_BUFFER_get_buf(b) ((b)->buf)
#define SSL3_BUFFER_set_buf(b, n) ((b)->buf = (n))
#define SSL3_BUFFER_get_len(b) ((b)->len)
#define SSL3_BUFFER_set_len(b, l) ((b)->len = (l))
#define SSL3_BUFFER_get_left(b) ((b)->left)
#define SSL3_BUFFER_set_left(b, l) ((b)->left = (l))
#define SSL3_BUFFER_sub_left(b, l) ((b)->left -= (l))
#define SSL3_BUFFER_get_offset(b) ((b)->offset)
#define SSL3_BUFFER_set_offset(b, o) ((b)->offset = (o))
#define SSL3_BUFFER_add_offset(b, o) ((b)->offset += (o))
#define SSL3_BUFFER_is_initialised(b) ((b)->buf != NULL)
#define SSL3_BUFFER_set_default_len(b, l) ((b)->default_len = (l))
#define SSL3_RECORD_get_type(r) ((r)->type)
#define SSL3_RECORD_set_type(r, t) ((r)->type = (t))
#define SSL3_RECORD_get_length(r) ((r)->length)
#define SSL3_RECORD_set_length(r, l) ((r)->length = (l))
#define SSL3_RECORD_add_length(r, l) ((r)->length += (l))
#define SSL3_RECORD_sub_length(r, l) ((r)->length -= (l))
#define SSL3_RECORD_get_data(r) ((r)->data)
#define SSL3_RECORD_set_data(r, d) ((r)->data = (d))
#define SSL3_RECORD_get_input(r) ((r)->input)
#define SSL3_RECORD_set_input(r, i) ((r)->input = (i))
#define SSL3_RECORD_reset_input(r) ((r)->input = (r)->data)
#define SSL3_RECORD_get_seq_num(r) ((r)->seq_num)
#define SSL3_RECORD_get_off(r) ((r)->off)
#define SSL3_RECORD_set_off(r, o) ((r)->off = (o))
#define SSL3_RECORD_add_off(r, o) ((r)->off += (o))
#define SSL3_RECORD_get_epoch(r) ((r)->epoch)
#define SSL3_RECORD_is_sslv2_record(r) ((r)->rec_version == SSL2_VERSION)
#define SSL3_RECORD_is_read(r) ((r)->read)
#define SSL3_RECORD_set_read(r) ((r)->read = 1)
Functions
__owur int ssl3_read_n (SSL *s, size_t n, size_t max, int extend, int clearold, size_t *readbytes)
void RECORD_LAYER_set_write_sequence (RECORD_LAYER *rl, const unsigned char *ws)
DTLS1_BITMAP * dtls1_get_bitmap (SSL *s, SSL3_RECORD *rr, unsigned int *is_next_epoch)
int dtls1_process_buffered_records (SSL *s)
int dtls1_retrieve_buffered_record (SSL *s, record_pqueue *queue)
int dtls1_buffer_record (SSL *s, record_pqueue *q, unsigned char *priority)
void ssl3_record_sequence_update (unsigned char *seq)
int dtls1_record_replay_check (SSL *s, DTLS1_BITMAP *bitmap)
void dtls1_record_bitmap_update (SSL *s, DTLS1_BITMAP *bitmap)
void SSL3_BUFFER_clear (SSL3_BUFFER *b)
void SSL3_BUFFER_set_data (SSL3_BUFFER *b, const unsigned char *d, size_t n)
void SSL3_BUFFER_release (SSL3_BUFFER *b)
__owur int ssl3_setup_read_buffer (SSL *s)
__owur int ssl3_setup_write_buffer (SSL *s, size_t numwpipes, size_t len)
int ssl3_release_read_buffer (SSL *s)
int ssl3_release_write_buffer (SSL *s)
void SSL3_RECORD_clear (SSL3_RECORD *r, size_t)
void SSL3_RECORD_release (SSL3_RECORD *r, size_t num_recs)
void SSL3_RECORD_set_seq_num (SSL3_RECORD *r, const unsigned char *seq_num)
int ssl3_get_record (SSL *s)
__owur int ssl3_do_compress (SSL *ssl, SSL3_RECORD *wr)
__owur int ssl3_do_uncompress (SSL *ssl, SSL3_RECORD *rr)
void ssl3_cbc_copy_mac (unsigned char *out, const SSL3_RECORD *rec, size_t md_size)
__owur int ssl3_cbc_remove_padding (SSL3_RECORD *rec, size_t block_size, size_t mac_size)
__owur int tls1_cbc_remove_padding (const SSL *s, SSL3_RECORD *rec, size_t block_size, size_t mac_size)
int dtls1_process_record (SSL *s, DTLS1_BITMAP *bitmap)
__owur int dtls1_get_record (SSL *s)
Macro Definition Documentation
DTLS_RECORD_LAYER_get_r_epoch
#define DTLS_RECORD_LAYER_get_r_epoch (rl) ((rl)->d->r_epoch)
Definition at line 39 of file record_locl.h.
MAX_WARN_ALERT_COUNT
#define MAX_WARN_ALERT_COUNT 5
Definition at line 17 of file record_locl.h.
RECORD_LAYER_clear_first_record
#define RECORD_LAYER_clear_first_record (rl) ((rl)->is_first_record = 0)
Definition at line 38 of file record_locl.h.
RECORD_LAYER_get_empty_record_count
#define RECORD_LAYER_get_empty_record_count (rl) ((rl)->empty_record_count)
Definition at line 35 of file record_locl.h.
RECORD_LAYER_get_numrpipes
#define RECORD_LAYER_get_numrpipes (rl) ((rl)->numrpipes)
Definition at line 30 of file record_locl.h.
Referenced by ssl3_pending().
RECORD_LAYER_get_rbuf
#define RECORD_LAYER_get_rbuf (rl) (&(rl)->rbuf)
Definition at line 21 of file record_locl.h.
Referenced by dtls1_process_buffered_records(), ssl3_release_read_buffer(), ssl3_setup_read_buffer(), and SSL_set_default_read_buffer_len().
RECORD_LAYER_get_read_sequence
#define RECORD_LAYER_get_read_sequence (rl) ((rl)->read_sequence)
Definition at line 28 of file record_locl.h.
Referenced by dtls1_get_record(), and dtls1_record_bitmap_update().
RECORD_LAYER_get_rrec
#define RECORD_LAYER_get_rrec (rl) ((rl)->rrec)
Definition at line 23 of file record_locl.h.
Referenced by dtls1_get_record(), and dtls1_process_buffered_records().
RECORD_LAYER_get_rstate
#define RECORD_LAYER_get_rstate (rl) ((rl)->rstate)
Definition at line 26 of file record_locl.h.
Referenced by dtls1_get_record().
RECORD_LAYER_get_wbuf
#define RECORD_LAYER_get_wbuf (rl) ((rl)->wbuf)
Definition at line 22 of file record_locl.h.
Referenced by ssl3_release_write_buffer(), and ssl3_setup_write_buffer().
RECORD_LAYER_get_write_sequence
#define RECORD_LAYER_get_write_sequence (rl) ((rl)->write_sequence)
Definition at line 29 of file record_locl.h.
RECORD_LAYER_inc_empty_record_count
#define RECORD_LAYER_inc_empty_record_count (rl) ((rl)->empty_record_count++)
Definition at line 32 of file record_locl.h.
RECORD_LAYER_is_first_record
#define RECORD_LAYER_is_first_record (rl) ((rl)->is_first_record)
Definition at line 36 of file record_locl.h.
RECORD_LAYER_reset_empty_record_count
#define RECORD_LAYER_reset_empty_record_count (rl) ((rl)->empty_record_count = 0)
Definition at line 33 of file record_locl.h.
RECORD_LAYER_reset_packet_length
#define RECORD_LAYER_reset_packet_length (rl) ((rl)->packet_length = 0)
Definition at line 25 of file record_locl.h.
Referenced by dtls1_get_record(), and dtls1_process_buffered_records().
RECORD_LAYER_set_first_record
#define RECORD_LAYER_set_first_record (rl) ((rl)->is_first_record = 1)
Definition at line 37 of file record_locl.h.
Referenced by RECORD_LAYER_init().
RECORD_LAYER_set_numrpipes
#define RECORD_LAYER_set_numrpipes (rl, n) ((rl)->numrpipes = (n))
Definition at line 31 of file record_locl.h.
RECORD_LAYER_set_packet
#define RECORD_LAYER_set_packet (rl, p) ((rl)->packet = (p))
Definition at line 24 of file record_locl.h.
Referenced by ssl3_setup_read_buffer().
RECORD_LAYER_set_rstate
#define RECORD_LAYER_set_rstate (rl, st) ((rl)->rstate = (st))
Definition at line 27 of file record_locl.h.
Referenced by dtls1_get_record().
SSL3_BUFFER_add_offset
#define SSL3_BUFFER_add_offset (b, o) ((b)->offset += (o))
Definition at line 68 of file record_locl.h.
SSL3_BUFFER_get_buf
#define SSL3_BUFFER_get_buf (b) ((b)->buf)
Definition at line 59 of file record_locl.h.
SSL3_BUFFER_get_left
#define SSL3_BUFFER_get_left (b) ((b)->left)
Definition at line 63 of file record_locl.h.
Referenced by dtls1_process_buffered_records(), RECORD_LAYER_read_pending(), and RECORD_LAYER_write_pending().
SSL3_BUFFER_get_len
#define SSL3_BUFFER_get_len (b) ((b)->len)
Definition at line 61 of file record_locl.h.
Referenced by dtls1_get_record().
SSL3_BUFFER_get_offset
#define SSL3_BUFFER_get_offset (b) ((b)->offset)
Definition at line 66 of file record_locl.h.
SSL3_BUFFER_is_initialised
#define SSL3_BUFFER_is_initialised (b) ((b)->buf != NULL)
Definition at line 69 of file record_locl.h.
Referenced by RECORD_LAYER_release().
SSL3_BUFFER_set_buf
#define SSL3_BUFFER_set_buf (b, n) ((b)->buf = (n))
Definition at line 60 of file record_locl.h.
SSL3_BUFFER_set_default_len
#define SSL3_BUFFER_set_default_len (b, l) ((b)->default_len = (l))
Definition at line 70 of file record_locl.h.
Referenced by SSL_set_default_read_buffer_len().
SSL3_BUFFER_set_left
#define SSL3_BUFFER_set_left (b, l) ((b)->left = (l))
Definition at line 64 of file record_locl.h.
SSL3_BUFFER_set_len
#define SSL3_BUFFER_set_len (b, l) ((b)->len = (l))
Definition at line 62 of file record_locl.h.
SSL3_BUFFER_set_offset
#define SSL3_BUFFER_set_offset (b, o) ((b)->offset = (o))
Definition at line 67 of file record_locl.h.
SSL3_BUFFER_sub_left
#define SSL3_BUFFER_sub_left (b, l) ((b)->left -= (l))
Definition at line 65 of file record_locl.h.
SSL3_RECORD_add_length
#define SSL3_RECORD_add_length (r, l) ((r)->length += (l))
Definition at line 86 of file record_locl.h.
SSL3_RECORD_add_off
#define SSL3_RECORD_add_off (r, o) ((r)->off += (o))
Definition at line 96 of file record_locl.h.
SSL3_RECORD_get_data
#define SSL3_RECORD_get_data (r) ((r)->data)
Definition at line 88 of file record_locl.h.
SSL3_RECORD_get_epoch
#define SSL3_RECORD_get_epoch (r) ((r)->epoch)
Definition at line 97 of file record_locl.h.
SSL3_RECORD_get_input
#define SSL3_RECORD_get_input (r) ((r)->input)
Definition at line 90 of file record_locl.h.
SSL3_RECORD_get_length
#define SSL3_RECORD_get_length (r) ((r)->length)
Definition at line 84 of file record_locl.h.
Referenced by RECORD_LAYER_get_rrec_length(), and ssl3_pending().
SSL3_RECORD_get_off
#define SSL3_RECORD_get_off (r) ((r)->off)
Definition at line 94 of file record_locl.h.
SSL3_RECORD_get_seq_num
#define SSL3_RECORD_get_seq_num (r) ((r)->seq_num)
Definition at line 93 of file record_locl.h.
Referenced by dtls1_process_buffered_records().
SSL3_RECORD_get_type
#define SSL3_RECORD_get_type (r) ((r)->type)
Definition at line 82 of file record_locl.h.
Referenced by ssl3_pending().
SSL3_RECORD_is_read
#define SSL3_RECORD_is_read (r) ((r)->read)
Definition at line 100 of file record_locl.h.
SSL3_RECORD_is_sslv2_record
#define SSL3_RECORD_is_sslv2_record (r) ((r)->rec_version == SSL2_VERSION)
Definition at line 98 of file record_locl.h.
Referenced by RECORD_LAYER_is_sslv2_record().
SSL3_RECORD_reset_input
#define SSL3_RECORD_reset_input (r) ((r)->input = (r)->data)
Definition at line 92 of file record_locl.h.
SSL3_RECORD_set_data
#define SSL3_RECORD_set_data (r, d) ((r)->data = (d))
Definition at line 89 of file record_locl.h.
SSL3_RECORD_set_input
#define SSL3_RECORD_set_input (r, i) ((r)->input = (i))
Definition at line 91 of file record_locl.h.
SSL3_RECORD_set_length
#define SSL3_RECORD_set_length (r, l) ((r)->length = (l))
Definition at line 85 of file record_locl.h.
SSL3_RECORD_set_off
#define SSL3_RECORD_set_off (r, o) ((r)->off = (o))
Definition at line 95 of file record_locl.h.
SSL3_RECORD_set_read
#define SSL3_RECORD_set_read (r) ((r)->read = 1)
Definition at line 101 of file record_locl.h.
SSL3_RECORD_set_type
#define SSL3_RECORD_set_type (r, t) ((r)->type = (t))
Definition at line 83 of file record_locl.h.
SSL3_RECORD_sub_length
#define SSL3_RECORD_sub_length (r, l) ((r)->length -= (l))
Definition at line 87 of file record_locl.h.
Function Documentation
dtls1_buffer_record()
int dtls1_buffer_record (SSL * s, record_pqueue * q, unsigned char * priority)
Definition at line 145 of file rec_layer_d1.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_SCTP_GET_RCVINFO, BIO_dgram_is_sctp(), SSL3_BUFFER::buf, ERR_R_INTERNAL_ERROR, NULL, OPENSSL_free, OPENSSL_malloc, DTLS1_RECORD_DATA::packet, DTLS1_RECORD_DATA::packet_length, pitem_free(), pitem_new(), pqueue_insert(), pqueue_size(), record_pqueue::q, DTLS1_RECORD_DATA::rbuf, DTLS1_RECORD_DATA::recordinfo, DTLS1_RECORD_DATA::rrec, ssl3_setup_buffers(), SSL_F_DTLS1_BUFFER_RECORD, SSL_get_rbio(), SSL_get_state(), SSLerr, TLS_ST_CR_FINISHED, and TLS_ST_SR_FINISHED.
Referenced by dtls1_get_record(), and dtls1_process_buffered_records().
dtls1_get_bitmap()
DTLS1_BITMAP* dtls1_get_bitmap (SSL * s, SSL3_RECORD * rr, unsigned int * is_next_epoch)
Definition at line 1117 of file rec_layer_d1.c.
References SSL3_RECORD::epoch, NULL, SSL3_RT_ALERT, SSL3_RT_HANDSHAKE, and SSL3_RECORD::type.
Referenced by dtls1_get_record(), and dtls1_process_buffered_records().
dtls1_get_record()
__owur int dtls1_get_record (SSL * s)
Definition at line 1585 of file ssl3_record.c.
References BIO_dgram_is_sctp(), dtls1_buffer_record(), dtls1_get_bitmap(), dtls1_get_processed_record, dtls1_process_buffered_records(), dtls1_process_record(), dtls1_record_replay_check(), DTLS1_RT_HEADER_LENGTH, DTLS_RECORD_LAYER_get_unprocessed_rcds, SSL3_RECORD::epoch, SSL3_RECORD::length, n2s, NULL, ossl_statem_get_in_handshake(), RECORD_LAYER_get_packet, RECORD_LAYER_get_packet_length, RECORD_LAYER_get_read_sequence, RECORD_LAYER_get_rrec, RECORD_LAYER_get_rstate, RECORD_LAYER_reset_packet_length, RECORD_LAYER_set_rstate, SSL3_RECORD::seq_num, SSL3_BUFFER_get_len, ssl3_read_n(), SSL3_RT_HEADER, SSL3_RT_MAX_ENCRYPTED_LENGTH, SSL_get_rbio(), SSL_in_init(), SSL_ST_READ_BODY, SSL_ST_READ_HEADER, and SSL3_RECORD::type.
dtls1_process_buffered_records()
int dtls1_process_buffered_records (SSL * s)
Definition at line 230 of file rec_layer_d1.c.
References BIO_dgram_is_sctp(), dtls1_buffer_record(), dtls1_get_bitmap(), dtls1_get_unprocessed_record, dtls1_process_record(), dtls1_record_replay_check(), ERR_R_INTERNAL_ERROR, SSL3_RECORD::length, NULL, pqueue_peek(), RECORD_LAYER_get_rbuf, RECORD_LAYER_get_rrec, RECORD_LAYER_reset_packet_length, SSL3_BUFFER_get_left, SSL3_RECORD_get_seq_num, SSL_F_DTLS1_PROCESS_BUFFERED_RECORDS, SSL_get_rbio(), and SSLerr.
Referenced by dtls1_get_record().
dtls1_process_record()
int dtls1_process_record (SSL * s, DTLS1_BITMAP * bitmap)
Definition at line 1370 of file ssl3_record.c.
Referenced by dtls1_get_record(), and dtls1_process_buffered_records().
dtls1_record_bitmap_update()
void dtls1_record_bitmap_update (SSL * s, DTLS1_BITMAP * bitmap)
Definition at line 59 of file dtls1_bitmap.c.
References RECORD_LAYER_get_read_sequence, and seq.
dtls1_record_replay_check()
int dtls1_record_replay_check (SSL * s, DTLS1_BITMAP * bitmap)
Definition at line 38 of file dtls1_bitmap.c.
References seq.
Referenced by dtls1_get_record(), and dtls1_process_buffered_records().
dtls1_retrieve_buffered_record()
int dtls1_retrieve_buffered_record (SSL * s, record_pqueue * queue)
Definition at line 205 of file rec_layer_d1.c.
References pqueue_pop(), and record_pqueue::q.
RECORD_LAYER_set_write_sequence()
void RECORD_LAYER_set_write_sequence (RECORD_LAYER * rl, const unsigned char * ws)
SSL3_BUFFER_clear()
void SSL3_BUFFER_clear (SSL3_BUFFER * b)
Definition at line 25 of file ssl3_buffer.c.
References SSL3_BUFFER::left, and SSL3_BUFFER::offset.
Referenced by RECORD_LAYER_clear().
SSL3_BUFFER_release()
void SSL3_BUFFER_release (SSL3_BUFFER * b)
Definition at line 31 of file ssl3_buffer.c.
References SSL3_BUFFER::buf, NULL, and OPENSSL_free.
SSL3_BUFFER_set_data()
void SSL3_BUFFER_set_data (SSL3_BUFFER * b, const unsigned char * d, size_t n)
Definition at line 13 of file ssl3_buffer.c.
References SSL3_BUFFER::buf, SSL3_BUFFER::left, NULL, and SSL3_BUFFER::offset.
ssl3_cbc_copy_mac()
void ssl3_cbc_copy_mac (unsigned char * out, const SSL3_RECORD * rec, size_t md_size)
Definition at line 1298 of file ssl3_record.c.
ssl3_cbc_remove_padding()
__owur int ssl3_cbc_remove_padding (SSL3_RECORD * rec, size_t block_size, size_t mac_size)
Definition at line 1178 of file ssl3_record.c.
References SSL3_RECORD::data, and SSL3_RECORD::length.
Referenced by ssl3_enc().
ssl3_do_compress()
__owur int ssl3_do_compress (SSL * ssl, SSL3_RECORD * wr)
Definition at line 616 of file ssl3_record.c.
References COMP_compress_block(), SSL3_RECORD::data, SSL3_RECORD::input, SSL3_RECORD::length, and SSL3_RT_MAX_COMPRESSED_OVERHEAD.
ssl3_do_uncompress()
__owur int ssl3_do_uncompress (SSL * ssl, SSL3_RECORD * rr)
Definition at line 592 of file ssl3_record.c.
References SSL3_RECORD::comp, COMP_expand_block(), SSL3_RECORD::data, SSL3_RECORD::length, NULL, OPENSSL_malloc, SSL3_RT_MAX_ENCRYPTED_LENGTH, and SSL3_RT_MAX_PLAIN_LENGTH.
ssl3_get_record()
int ssl3_get_record (SSL * s)
Definition at line 126 of file ssl3_record.c.
ssl3_read_n()
__owur int ssl3_read_n (SSL * s, size_t n, size_t max, int extend, int clearold, size_t * readbytes)
Definition at line 176 of file rec_layer_s3.c.
References SSL3_BUFFER::buf, ERR_R_INTERNAL_ERROR, SSL3_BUFFER::left, SSL3_BUFFER::len, len, NULL, SSL3_BUFFER::offset, SSL3_ALIGN_PAYLOAD, SSL3_RT_APPLICATION_DATA, SSL3_RT_HEADER_LENGTH, ssl3_setup_read_buffer(), SSL_F_SSL3_READ_N, SSL_IS_DTLS, and SSLerr.
Referenced by dtls1_get_record().
SSL3_RECORD_clear()
void SSL3_RECORD_clear (SSL3_RECORD * r, size_t)
Definition at line 37 of file ssl3_record.c.
References SSL3_RECORD::comp.
Referenced by RECORD_LAYER_clear(), and RECORD_LAYER_init().
SSL3_RECORD_release()
void SSL3_RECORD_release (SSL3_RECORD * r, size_t num_recs)
Definition at line 50 of file ssl3_record.c.
References SSL3_RECORD::comp, NULL, and OPENSSL_free.
Referenced by RECORD_LAYER_release().
ssl3_record_sequence_update()
void ssl3_record_sequence_update (unsigned char * seq)
Definition at line 1585 of file rec_layer_s3.c.
SSL3_RECORD_set_seq_num()
void SSL3_RECORD_set_seq_num (SSL3_RECORD * r, const unsigned char * seq_num)
Definition at line 60 of file ssl3_record.c.
References SSL3_RECORD::seq_num, and SEQ_NUM_SIZE.
ssl3_release_read_buffer()
int ssl3_release_read_buffer (SSL * s)
Definition at line 155 of file ssl3_buffer.c.
References SSL3_BUFFER::buf, NULL, OPENSSL_free, and RECORD_LAYER_get_rbuf.
Referenced by RECORD_LAYER_release().
ssl3_release_write_buffer()
int ssl3_release_write_buffer (SSL * s)
Definition at line 138 of file ssl3_buffer.c.
References SSL3_BUFFER::buf, NULL, OPENSSL_free, and RECORD_LAYER_get_wbuf.
Referenced by RECORD_LAYER_clear(), and RECORD_LAYER_release().
ssl3_setup_read_buffer()
__owur int ssl3_setup_read_buffer (SSL * s)
Definition at line 37 of file ssl3_buffer.c.
References SSL3_BUFFER::buf, SSL3_BUFFER::default_len, DTLS1_RT_HEADER_LENGTH, ERR_R_MALLOC_FAILURE, SSL3_BUFFER::len, len, NULL, OPENSSL_malloc, RECORD_LAYER_get_rbuf, RECORD_LAYER_set_packet, SSL3_ALIGN_PAYLOAD, SSL3_RT_HEADER_LENGTH, SSL3_RT_MAX_COMPRESSED_OVERHEAD, SSL3_RT_MAX_ENCRYPTED_OVERHEAD, SSL3_RT_MAX_PLAIN_LENGTH, ssl_allow_compression(), SSL_F_SSL3_SETUP_READ_BUFFER, SSL_IS_DTLS, and SSLerr.
Referenced by ssl3_read_n(), and ssl3_setup_buffers().
ssl3_setup_write_buffer()
__owur int ssl3_setup_write_buffer (SSL * s, size_t numwpipes, size_t len)
Definition at line 77 of file ssl3_buffer.c.
References SSL3_BUFFER::buf, DTLS1_RT_HEADER_LENGTH, ERR_R_MALLOC_FAILURE, SSL3_BUFFER::len, len, NULL, OPENSSL_malloc, RECORD_LAYER_get_wbuf, SSL3_ALIGN_PAYLOAD, SSL3_RT_HEADER_LENGTH, SSL3_RT_MAX_COMPRESSED_OVERHEAD, SSL3_RT_SEND_MAX_ENCRYPTED_OVERHEAD, ssl_allow_compression(), SSL_F_SSL3_SETUP_WRITE_BUFFER, SSL_IS_DTLS, SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS, and SSLerr.
Referenced by ssl3_setup_buffers().
tls1_cbc_remove_padding()
__owur int tls1_cbc_remove_padding (const SSL * s, SSL3_RECORD * rec, size_t block_size, size_t mac_size)
Definition at line 1212 of file ssl3_record.c.
References SSL3_RECORD::data, EVP_CIPH_FLAG_AEAD_CIPHER, EVP_CIPHER_CTX_cipher(), EVP_CIPHER_flags(), SSL3_RECORD::input, SSL3_RECORD::length, SSL3_RECORD::orig_len, and SSL_USE_EXPLICIT_IV.