ssl/record/record.h File Reference
record.h File Reference
Data Structures
struct SSL3_BUFFER
struct SSL3_RECORD
struct DTLS1_BITMAP
struct record_pqueue
struct DTLS1_RECORD_DATA
struct DTLS_RECORD_LAYER
struct RECORD_LAYER
Macros
#define SEQ_NUM_SIZE 8
#define MIN_SSL2_RECORD_LEN 9
#define RECORD_LAYER_set_read_ahead(rl, ra) ((rl)->read_ahead = (ra))
#define RECORD_LAYER_get_read_ahead(rl) ((rl)->read_ahead)
#define RECORD_LAYER_get_packet(rl) ((rl)->packet)
#define RECORD_LAYER_get_packet_length(rl) ((rl)->packet_length)
#define RECORD_LAYER_add_packet_length(rl, inc) ((rl)->packet_length += (inc))
#define DTLS_RECORD_LAYER_get_w_epoch(rl) ((rl)->d->w_epoch)
#define DTLS_RECORD_LAYER_get_processed_rcds(rl) ((rl)->d->processed_rcds)
#define DTLS_RECORD_LAYER_get_unprocessed_rcds(rl) ((rl)->d->unprocessed_rcds)
Functions
void RECORD_LAYER_init (RECORD_LAYER *rl, SSL *s)
void RECORD_LAYER_clear (RECORD_LAYER *rl)
void RECORD_LAYER_release (RECORD_LAYER *rl)
int RECORD_LAYER_read_pending (const RECORD_LAYER *rl)
int RECORD_LAYER_write_pending (const RECORD_LAYER *rl)
int RECORD_LAYER_set_data (RECORD_LAYER *rl, const unsigned char *buf, size_t len)
void RECORD_LAYER_reset_read_sequence (RECORD_LAYER *rl)
void RECORD_LAYER_reset_write_sequence (RECORD_LAYER *rl)
int RECORD_LAYER_is_sslv2_record (RECORD_LAYER *rl)
size_t RECORD_LAYER_get_rrec_length (RECORD_LAYER *rl)
__owur size_t ssl3_pending (const SSL *s)
__owur int ssl3_write_bytes (SSL *s, int type, const void *buf, size_t len, size_t *written)
int do_ssl3_write (SSL *s, int type, const unsigned char *buf, size_t *pipelens, size_t numpipes, int create_empty_fragment, size_t *written)
__owur int ssl3_read_bytes (SSL *s, int type, int *recvd_type, unsigned char *buf, size_t len, int peek, size_t *readbytes)
__owur int ssl3_setup_buffers (SSL *s)
__owur int ssl3_enc (SSL *s, SSL3_RECORD *inrecs, size_t n_recs, int send)
__owur int n_ssl3_mac (SSL *ssl, SSL3_RECORD *rec, unsigned char *md, int send)
__owur int ssl3_write_pending (SSL *s, int type, const unsigned char *buf, size_t len, size_t *written)
__owur int tls1_enc (SSL *s, SSL3_RECORD *recs, size_t n_recs, int send)
__owur int tls1_mac (SSL *ssl, SSL3_RECORD *rec, unsigned char *md, int send)
__owur int tls13_enc (SSL *s, SSL3_RECORD *recs, size_t n_recs, int send)
int DTLS_RECORD_LAYER_new (RECORD_LAYER *rl)
void DTLS_RECORD_LAYER_free (RECORD_LAYER *rl)
void DTLS_RECORD_LAYER_clear (RECORD_LAYER *rl)
void DTLS_RECORD_LAYER_set_saved_w_epoch (RECORD_LAYER *rl, unsigned short e)
void DTLS_RECORD_LAYER_resync_write (RECORD_LAYER *rl)
void DTLS_RECORD_LAYER_set_write_sequence (RECORD_LAYER *rl, unsigned char *seq)
__owur int dtls1_read_bytes (SSL *s, int type, int *recvd_type, unsigned char *buf, size_t len, int peek, size_t *readbytes)
__owur int dtls1_write_bytes (SSL *s, int type, const void *buf, size_t len, size_t *written)
int do_dtls1_write (SSL *s, int type, const unsigned char *buf, size_t len, int create_empty_fragment, size_t *written)
void dtls1_reset_seq_numbers (SSL *s, int rw)
Macro Definition Documentation
DTLS_RECORD_LAYER_get_processed_rcds
#define DTLS_RECORD_LAYER_get_processed_rcds (rl) ((rl)->d->processed_rcds)
Definition at line 201 of file record.h.
DTLS_RECORD_LAYER_get_unprocessed_rcds
#define DTLS_RECORD_LAYER_get_unprocessed_rcds (rl) ((rl)->d->unprocessed_rcds)
Definition at line 203 of file record.h.
Referenced by dtls1_get_record().
DTLS_RECORD_LAYER_get_w_epoch
#define DTLS_RECORD_LAYER_get_w_epoch (rl) ((rl)->d->w_epoch)
Definition at line 200 of file record.h.
MIN_SSL2_RECORD_LEN
#define MIN_SSL2_RECORD_LEN 9
Definition at line 193 of file record.h.
RECORD_LAYER_add_packet_length
#define RECORD_LAYER_add_packet_length (rl, inc) ((rl)->packet_length += (inc))
Definition at line 199 of file record.h.
RECORD_LAYER_get_packet
#define RECORD_LAYER_get_packet (rl) ((rl)->packet)
Definition at line 197 of file record.h.
Referenced by dtls1_get_record().
RECORD_LAYER_get_packet_length
#define RECORD_LAYER_get_packet_length (rl) ((rl)->packet_length)
Definition at line 198 of file record.h.
Referenced by dtls1_get_record().
RECORD_LAYER_get_read_ahead
#define RECORD_LAYER_get_read_ahead (rl) ((rl)->read_ahead)
Definition at line 196 of file record.h.
Referenced by SSL_ctrl(), and SSL_get_read_ahead().
RECORD_LAYER_set_read_ahead
#define RECORD_LAYER_set_read_ahead (rl, ra) ((rl)->read_ahead = (ra))
Definition at line 195 of file record.h.
Referenced by SSL_ctrl(), SSL_new(), and SSL_set_read_ahead().
SEQ_NUM_SIZE
#define SEQ_NUM_SIZE 8
Definition at line 30 of file record.h.
Referenced by DTLS_RECORD_LAYER_set_write_sequence(), and SSL3_RECORD_set_seq_num().
Function Documentation
do_dtls1_write()
int do_dtls1_write (SSL * s, int type, const unsigned char * buf, size_t len, int create_empty_fragment, size_t * written)
Definition at line 916 of file rec_layer_d1.c.
do_ssl3_write()
int do_ssl3_write (SSL * s, int type, const unsigned char * buf, size_t * pipelens, size_t numpipes, int create_empty_fragment, size_t * written)
Definition at line 625 of file rec_layer_s3.c.
Referenced by ssl3_dispatch_alert().
dtls1_read_bytes()
__owur int dtls1_read_bytes (SSL * s, int type, int * recvd_type, unsigned char * buf, size_t len, int peek, size_t * readbytes)
Definition at line 339 of file rec_layer_d1.c.
dtls1_reset_seq_numbers()
void dtls1_reset_seq_numbers (SSL * s, int rw)
Definition at line 1142 of file rec_layer_d1.c.
References dtls1_clear_received_buffer(), seq, and SSL3_CC_READ.
Referenced by ossl_statem_client_post_work(), and ossl_statem_server_post_work().
dtls1_write_bytes()
__owur int dtls1_write_bytes (SSL * s, int type, const void * buf, size_t len, size_t * written)
Definition at line 905 of file rec_layer_d1.c.
Referenced by dtls1_write_app_data_bytes().
DTLS_RECORD_LAYER_clear()
void DTLS_RECORD_LAYER_clear (RECORD_LAYER * rl)
Definition at line 55 of file rec_layer_d1.c.
References SSL3_BUFFER::buf, DTLS_RECORD_LAYER::buffered_app_data, RECORD_LAYER::d, NULL, OPENSSL_free, pitem_free(), pqueue_pop(), DTLS_RECORD_LAYER::processed_rcds, record_pqueue::q, DTLS1_RECORD_DATA::rbuf, and DTLS_RECORD_LAYER::unprocessed_rcds.
Referenced by dtls1_clear(), DTLS_RECORD_LAYER_free(), and RECORD_LAYER_clear().
DTLS_RECORD_LAYER_free()
void DTLS_RECORD_LAYER_free (RECORD_LAYER * rl)
Definition at line 45 of file rec_layer_d1.c.
References DTLS_RECORD_LAYER::buffered_app_data, RECORD_LAYER::d, DTLS_RECORD_LAYER_clear(), NULL, OPENSSL_free, pqueue_free(), DTLS_RECORD_LAYER::processed_rcds, record_pqueue::q, and DTLS_RECORD_LAYER::unprocessed_rcds.
Referenced by dtls1_free().
DTLS_RECORD_LAYER_new()
int DTLS_RECORD_LAYER_new (RECORD_LAYER * rl)
Definition at line 19 of file rec_layer_d1.c.
References DTLS_RECORD_LAYER::buffered_app_data, RECORD_LAYER::d, NULL, OPENSSL_free, OPENSSL_malloc, pqueue_free(), pqueue_new(), DTLS_RECORD_LAYER::processed_rcds, record_pqueue::q, and DTLS_RECORD_LAYER::unprocessed_rcds.
Referenced by dtls1_new().
DTLS_RECORD_LAYER_resync_write()
void DTLS_RECORD_LAYER_resync_write (RECORD_LAYER * rl)
Definition at line 112 of file rec_layer_d1.c.
References RECORD_LAYER::read_sequence, and RECORD_LAYER::write_sequence.
DTLS_RECORD_LAYER_set_saved_w_epoch()
void DTLS_RECORD_LAYER_set_saved_w_epoch (RECORD_LAYER * rl, unsigned short e)
Definition at line 96 of file rec_layer_d1.c.
References DTLS_RECORD_LAYER::curr_write_sequence, RECORD_LAYER::d, e, DTLS_RECORD_LAYER::last_write_sequence, DTLS_RECORD_LAYER::w_epoch, and RECORD_LAYER::write_sequence.
DTLS_RECORD_LAYER_set_write_sequence()
void DTLS_RECORD_LAYER_set_write_sequence (RECORD_LAYER * rl, unsigned char * seq)
Definition at line 117 of file rec_layer_d1.c.
References SEQ_NUM_SIZE, and RECORD_LAYER::write_sequence.
n_ssl3_mac()
__owur int n_ssl3_mac (SSL * ssl, SSL3_RECORD * rec, unsigned char * md, int send)
Definition at line 949 of file ssl3_record.c.
RECORD_LAYER_clear()
void RECORD_LAYER_clear (RECORD_LAYER * rl)
Definition at line 37 of file rec_layer_s3.c.
References RECORD_LAYER::alert_fragment, RECORD_LAYER::alert_fragment_len, RECORD_LAYER::d, DTLS_RECORD_LAYER_clear(), RECORD_LAYER::handshake_fragment, RECORD_LAYER::handshake_fragment_len, NULL, RECORD_LAYER::numrpipes, RECORD_LAYER::packet, RECORD_LAYER::packet_length, RECORD_LAYER::rbuf, RECORD_LAYER_reset_read_sequence(), RECORD_LAYER_reset_write_sequence(), RECORD_LAYER::rrec, RECORD_LAYER::rstate, RECORD_LAYER::s, SSL3_BUFFER_clear(), SSL3_RECORD_clear(), ssl3_release_write_buffer(), SSL_MAX_PIPELINES, SSL_ST_READ_HEADER, RECORD_LAYER::wnum, RECORD_LAYER::wpend_buf, RECORD_LAYER::wpend_ret, RECORD_LAYER::wpend_tot, and RECORD_LAYER::wpend_type.
RECORD_LAYER_get_rrec_length()
size_t RECORD_LAYER_get_rrec_length (RECORD_LAYER * rl)
Definition at line 1608 of file rec_layer_s3.c.
References RECORD_LAYER::rrec, and SSL3_RECORD_get_length.
Referenced by tls_get_message_header().
RECORD_LAYER_init()
void RECORD_LAYER_init (RECORD_LAYER * rl, SSL * s)
Definition at line 30 of file rec_layer_s3.c.
References RECORD_LAYER_set_first_record, RECORD_LAYER::rrec, RECORD_LAYER::s, SSL3_RECORD_clear(), and SSL_MAX_PIPELINES.
Referenced by SSL_new().
RECORD_LAYER_is_sslv2_record()
int RECORD_LAYER_is_sslv2_record (RECORD_LAYER * rl)
Definition at line 1600 of file rec_layer_s3.c.
References RECORD_LAYER::rrec, and SSL3_RECORD_is_sslv2_record.
Referenced by tls_get_message_header().
RECORD_LAYER_read_pending()
int RECORD_LAYER_read_pending (const RECORD_LAYER * rl)
Definition at line 80 of file rec_layer_s3.c.
References RECORD_LAYER::rbuf, and SSL3_BUFFER_get_left.
Referenced by SSL_has_pending().
RECORD_LAYER_release()
void RECORD_LAYER_release (RECORD_LAYER * rl)
Definition at line 71 of file rec_layer_s3.c.
References RECORD_LAYER::numwpipes, RECORD_LAYER::rbuf, RECORD_LAYER::rrec, RECORD_LAYER::s, SSL3_BUFFER_is_initialised, SSL3_RECORD_release(), ssl3_release_read_buffer(), ssl3_release_write_buffer(), and SSL_MAX_PIPELINES.
RECORD_LAYER_reset_read_sequence()
void RECORD_LAYER_reset_read_sequence (RECORD_LAYER * rl)
Definition at line 108 of file rec_layer_s3.c.
References RECORD_LAYER::read_sequence.
Referenced by RECORD_LAYER_clear().
RECORD_LAYER_reset_write_sequence()
void RECORD_LAYER_reset_write_sequence (RECORD_LAYER * rl)
Definition at line 113 of file rec_layer_s3.c.
References RECORD_LAYER::write_sequence.
Referenced by RECORD_LAYER_clear().
RECORD_LAYER_set_data()
int RECORD_LAYER_set_data (RECORD_LAYER * rl, const unsigned char * buf, size_t len)
Definition at line 91 of file rec_layer_s3.c.
RECORD_LAYER_write_pending()
int RECORD_LAYER_write_pending (const RECORD_LAYER * rl)
Definition at line 85 of file rec_layer_s3.c.
References RECORD_LAYER::numwpipes, SSL3_BUFFER_get_left, and RECORD_LAYER::wbuf.
Referenced by ssl3_send_alert().
ssl3_enc()
__owur int ssl3_enc (SSL * s, SSL3_RECORD * inrecs, size_t n_recs, int send)
Definition at line 645 of file ssl3_record.c.
References SSL3_RECORD::data, EVP_Cipher(), EVP_CIPHER_CTX_block_size(), EVP_CIPHER_CTX_cipher(), EVP_MD_CTX_md(), EVP_MD_CTX_size, SSL3_RECORD::input, SSL3_RECORD::length, NULL, and ssl3_cbc_remove_padding().
ssl3_pending()
__owur size_t ssl3_pending (const SSL * s)
Definition at line 118 of file rec_layer_s3.c.
References RECORD_LAYER_get_numrpipes, SSL3_RECORD_get_length, SSL3_RECORD_get_type, SSL3_RT_APPLICATION_DATA, and SSL_ST_READ_BODY.
ssl3_read_bytes()
__owur int ssl3_read_bytes (SSL * s, int type, int * recvd_type, unsigned char * buf, size_t len, int peek, size_t * readbytes)
Definition at line 1093 of file rec_layer_s3.c.
ssl3_setup_buffers()
__owur int ssl3_setup_buffers (SSL * s)
Definition at line 129 of file ssl3_buffer.c.
References ssl3_setup_read_buffer(), and ssl3_setup_write_buffer().
Referenced by dtls1_buffer_record().
ssl3_write_bytes()
__owur int ssl3_write_bytes (SSL * s, int type, const void * buf, size_t len, size_t * written)
Definition at line 339 of file rec_layer_s3.c.
ssl3_write_pending()
__owur int ssl3_write_pending (SSL * s, int type, const unsigned char * buf, size_t len, size_t * written)
Definition at line 1004 of file rec_layer_s3.c.
tls13_enc()
__owur int tls13_enc (SSL * s, SSL3_RECORD * recs, size_t n_recs, int send)
Definition at line 24 of file ssl3_record_tls13.c.
References ctx.
tls1_enc()
__owur int tls1_enc (SSL * s, SSL3_RECORD * recs, size_t n_recs, int send)
Definition at line 732 of file ssl3_record.c.
References SSL_MAX_PIPELINES.
tls1_mac()
__owur int tls1_mac (SSL * ssl, SSL3_RECORD * rec, unsigned char * md, int send)
Definition at line 1045 of file ssl3_record.c.