include/openssl/rsa.h File Reference
rsa.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/asn1.h>
#include <openssl/bio.h>
#include <openssl/crypto.h>
#include <openssl/ossl_typ.h>
#include <openssl/bn.h>
Data Structures
struct RSA_PSS_PARAMS
struct RSA_OAEP_PARAMS
Macros
#define OPENSSL_RSA_MAX_MODULUS_BITS 16384
#define OPENSSL_RSA_FIPS_MIN_MODULUS_BITS 1024
#define OPENSSL_RSA_SMALL_MODULUS_BITS 3072
#define OPENSSL_RSA_MAX_PUBEXP_BITS 64
#define RSA_3 0x3L
#define RSA_F4 0x10001L
#define RSA_METHOD_FLAG_NO_CHECK
#define RSA_FLAG_CACHE_PUBLIC 0x0002
#define RSA_FLAG_CACHE_PRIVATE 0x0004
#define RSA_FLAG_BLINDING 0x0008
#define RSA_FLAG_THREAD_SAFE 0x0010
#define RSA_FLAG_EXT_PKEY 0x0020
#define RSA_FLAG_NO_BLINDING 0x0080
#define RSA_FLAG_NO_CONSTTIME 0x0000
#define RSA_FLAG_NO_EXP_CONSTTIME RSA_FLAG_NO_CONSTTIME
#define EVP_PKEY_CTX_set_rsa_padding(ctx, pad) RSA_pkey_ctx_ctrl(ctx, -1, EVP_PKEY_CTRL_RSA_PADDING, pad, NULL)
#define EVP_PKEY_CTX_get_rsa_padding(ctx, ppad) RSA_pkey_ctx_ctrl(ctx, -1, EVP_PKEY_CTRL_GET_RSA_PADDING, 0, ppad)
#define EVP_PKEY_CTX_set_rsa_pss_saltlen(ctx, len)
#define RSA_PSS_SALTLEN_DIGEST -1
#define RSA_PSS_SALTLEN_AUTO -2
#define RSA_PSS_SALTLEN_MAX -3
#define RSA_PSS_SALTLEN_MAX_SIGN -2
#define EVP_PKEY_CTX_set_rsa_pss_keygen_saltlen(ctx, len)
#define EVP_PKEY_CTX_get_rsa_pss_saltlen(ctx, plen)
#define EVP_PKEY_CTX_set_rsa_keygen_bits(ctx, bits)
#define EVP_PKEY_CTX_set_rsa_keygen_pubexp(ctx, pubexp)
#define EVP_PKEY_CTX_set_rsa_mgf1_md(ctx, md)
#define EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md(ctx, md)
#define EVP_PKEY_CTX_set_rsa_oaep_md(ctx, md)
#define EVP_PKEY_CTX_get_rsa_mgf1_md(ctx, pmd)
#define EVP_PKEY_CTX_get_rsa_oaep_md(ctx, pmd)
#define EVP_PKEY_CTX_set0_rsa_oaep_label(ctx, l, llen)
#define EVP_PKEY_CTX_get0_rsa_oaep_label(ctx, l)
#define EVP_PKEY_CTX_rsa_pss_keygen_md(ctx, md)
#define EVP_PKEY_CTRL_RSA_PADDING (EVP_PKEY_ALG_CTRL + 1)
#define EVP_PKEY_CTRL_RSA_PSS_SALTLEN (EVP_PKEY_ALG_CTRL + 2)
#define EVP_PKEY_CTRL_RSA_KEYGEN_BITS (EVP_PKEY_ALG_CTRL + 3)
#define EVP_PKEY_CTRL_RSA_KEYGEN_PUBEXP (EVP_PKEY_ALG_CTRL + 4)
#define EVP_PKEY_CTRL_RSA_MGF1_MD (EVP_PKEY_ALG_CTRL + 5)
#define EVP_PKEY_CTRL_GET_RSA_PADDING (EVP_PKEY_ALG_CTRL + 6)
#define EVP_PKEY_CTRL_GET_RSA_PSS_SALTLEN (EVP_PKEY_ALG_CTRL + 7)
#define EVP_PKEY_CTRL_GET_RSA_MGF1_MD (EVP_PKEY_ALG_CTRL + 8)
#define EVP_PKEY_CTRL_RSA_OAEP_MD (EVP_PKEY_ALG_CTRL + 9)
#define EVP_PKEY_CTRL_RSA_OAEP_LABEL (EVP_PKEY_ALG_CTRL + 10)
#define EVP_PKEY_CTRL_GET_RSA_OAEP_MD (EVP_PKEY_ALG_CTRL + 11)
#define EVP_PKEY_CTRL_GET_RSA_OAEP_LABEL (EVP_PKEY_ALG_CTRL + 12)
#define RSA_PKCS1_PADDING 1
#define RSA_SSLV23_PADDING 2
#define RSA_NO_PADDING 3
#define RSA_PKCS1_OAEP_PADDING 4
#define RSA_X931_PADDING 5
#define RSA_PKCS1_PSS_PADDING 6
#define RSA_PKCS1_PADDING_SIZE 11
#define RSA_set_app_data(s, arg) RSA_set_ex_data(s,0,arg)
#define RSA_get_app_data(s) RSA_get_ex_data(s,0)
#define RSA_get_ex_new_index(l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_RSA, l, p, newf, dupf, freef)
#define RSA_FLAG_FIPS_METHOD 0x0400
#define RSA_FLAG_NON_FIPS_ALLOW 0x0400
#define RSA_FLAG_CHECKED 0x0800
#define RSA_F_CHECK_PADDING_MD 140
#define RSA_F_ENCODE_PKCS1 146
#define RSA_F_INT_RSA_VERIFY 145
#define RSA_F_OLD_RSA_PRIV_DECODE 147
#define RSA_F_PKEY_PSS_INIT 165
#define RSA_F_PKEY_RSA_CTRL 143
#define RSA_F_PKEY_RSA_CTRL_STR 144
#define RSA_F_PKEY_RSA_SIGN 142
#define RSA_F_PKEY_RSA_VERIFY 149
#define RSA_F_PKEY_RSA_VERIFYRECOVER 141
#define RSA_F_RSA_ALGOR_TO_MD 156
#define RSA_F_RSA_BUILTIN_KEYGEN 129
#define RSA_F_RSA_CHECK_KEY 123
#define RSA_F_RSA_CHECK_KEY_EX 160
#define RSA_F_RSA_CMS_DECRYPT 159
#define RSA_F_RSA_CMS_VERIFY 158
#define RSA_F_RSA_ITEM_VERIFY 148
#define RSA_F_RSA_METH_DUP 161
#define RSA_F_RSA_METH_NEW 162
#define RSA_F_RSA_METH_SET1_NAME 163
#define RSA_F_RSA_MGF1_TO_MD 157
#define RSA_F_RSA_NEW_METHOD 106
#define RSA_F_RSA_NULL 124
#define RSA_F_RSA_NULL_PRIVATE_DECRYPT 132
#define RSA_F_RSA_NULL_PRIVATE_ENCRYPT 133
#define RSA_F_RSA_NULL_PUBLIC_DECRYPT 134
#define RSA_F_RSA_NULL_PUBLIC_ENCRYPT 135
#define RSA_F_RSA_OSSL_PRIVATE_DECRYPT 101
#define RSA_F_RSA_OSSL_PRIVATE_ENCRYPT 102
#define RSA_F_RSA_OSSL_PUBLIC_DECRYPT 103
#define RSA_F_RSA_OSSL_PUBLIC_ENCRYPT 104
#define RSA_F_RSA_PADDING_ADD_NONE 107
#define RSA_F_RSA_PADDING_ADD_PKCS1_OAEP 121
#define RSA_F_RSA_PADDING_ADD_PKCS1_OAEP_MGF1 154
#define RSA_F_RSA_PADDING_ADD_PKCS1_PSS 125
#define RSA_F_RSA_PADDING_ADD_PKCS1_PSS_MGF1 152
#define RSA_F_RSA_PADDING_ADD_PKCS1_TYPE_1 108
#define RSA_F_RSA_PADDING_ADD_PKCS1_TYPE_2 109
#define RSA_F_RSA_PADDING_ADD_SSLV23 110
#define RSA_F_RSA_PADDING_ADD_X931 127
#define RSA_F_RSA_PADDING_CHECK_NONE 111
#define RSA_F_RSA_PADDING_CHECK_PKCS1_OAEP 122
#define RSA_F_RSA_PADDING_CHECK_PKCS1_OAEP_MGF1 153
#define RSA_F_RSA_PADDING_CHECK_PKCS1_TYPE_1 112
#define RSA_F_RSA_PADDING_CHECK_PKCS1_TYPE_2 113
#define RSA_F_RSA_PADDING_CHECK_SSLV23 114
#define RSA_F_RSA_PADDING_CHECK_X931 128
#define RSA_F_RSA_PARAM_DECODE 164
#define RSA_F_RSA_PRINT 115
#define RSA_F_RSA_PRINT_FP 116
#define RSA_F_RSA_PRIV_DECODE 150
#define RSA_F_RSA_PRIV_ENCODE 138
#define RSA_F_RSA_PSS_GET_PARAM 151
#define RSA_F_RSA_PSS_TO_CTX 155
#define RSA_F_RSA_PUB_DECODE 139
#define RSA_F_RSA_SETUP_BLINDING 136
#define RSA_F_RSA_SIGN 117
#define RSA_F_RSA_SIGN_ASN1_OCTET_STRING 118
#define RSA_F_RSA_VERIFY 119
#define RSA_F_RSA_VERIFY_ASN1_OCTET_STRING 120
#define RSA_F_RSA_VERIFY_PKCS1_PSS_MGF1 126
#define RSA_R_ALGORITHM_MISMATCH 100
#define RSA_R_BAD_E_VALUE 101
#define RSA_R_BAD_FIXED_HEADER_DECRYPT 102
#define RSA_R_BAD_PAD_BYTE_COUNT 103
#define RSA_R_BAD_SIGNATURE 104
#define RSA_R_BLOCK_TYPE_IS_NOT_01 106
#define RSA_R_BLOCK_TYPE_IS_NOT_02 107
#define RSA_R_DATA_GREATER_THAN_MOD_LEN 108
#define RSA_R_DATA_TOO_LARGE 109
#define RSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE 110
#define RSA_R_DATA_TOO_LARGE_FOR_MODULUS 132
#define RSA_R_DATA_TOO_SMALL 111
#define RSA_R_DATA_TOO_SMALL_FOR_KEY_SIZE 122
#define RSA_R_DIGEST_DOES_NOT_MATCH 158
#define RSA_R_DIGEST_NOT_ALLOWED 145
#define RSA_R_DIGEST_TOO_BIG_FOR_RSA_KEY 112
#define RSA_R_DMP1_NOT_CONGRUENT_TO_D 124
#define RSA_R_DMQ1_NOT_CONGRUENT_TO_D 125
#define RSA_R_D_E_NOT_CONGRUENT_TO_1 123
#define RSA_R_FIRST_OCTET_INVALID 133
#define RSA_R_ILLEGAL_OR_UNSUPPORTED_PADDING_MODE 144
#define RSA_R_INVALID_DIGEST 157
#define RSA_R_INVALID_DIGEST_LENGTH 143
#define RSA_R_INVALID_HEADER 137
#define RSA_R_INVALID_LABEL 160
#define RSA_R_INVALID_MESSAGE_LENGTH 131
#define RSA_R_INVALID_MGF1_MD 156
#define RSA_R_INVALID_OAEP_PARAMETERS 161
#define RSA_R_INVALID_PADDING 138
#define RSA_R_INVALID_PADDING_MODE 141
#define RSA_R_INVALID_PSS_PARAMETERS 149
#define RSA_R_INVALID_PSS_SALTLEN 146
#define RSA_R_INVALID_SALT_LENGTH 150
#define RSA_R_INVALID_TRAILER 139
#define RSA_R_INVALID_X931_DIGEST 142
#define RSA_R_IQMP_NOT_INVERSE_OF_Q 126
#define RSA_R_KEY_SIZE_TOO_SMALL 120
#define RSA_R_LAST_OCTET_INVALID 134
#define RSA_R_MGF1_DIGEST_NOT_ALLOWED 152
#define RSA_R_MODULUS_TOO_LARGE 105
#define RSA_R_NO_PUBLIC_EXPONENT 140
#define RSA_R_NULL_BEFORE_BLOCK_MISSING 113
#define RSA_R_N_DOES_NOT_EQUAL_P_Q 127
#define RSA_R_OAEP_DECODING_ERROR 121
#define RSA_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE 148
#define RSA_R_PADDING_CHECK_FAILED 114
#define RSA_R_PKCS_DECODING_ERROR 159
#define RSA_R_PSS_SALTLEN_TOO_SMALL 164
#define RSA_R_P_NOT_PRIME 128
#define RSA_R_Q_NOT_PRIME 129
#define RSA_R_RSA_OPERATIONS_NOT_SUPPORTED 130
#define RSA_R_SLEN_CHECK_FAILED 136
#define RSA_R_SLEN_RECOVERY_FAILED 135
#define RSA_R_SSLV3_ROLLBACK_ATTACK 115
#define RSA_R_THE_ASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD 116
#define RSA_R_UNKNOWN_ALGORITHM_TYPE 117
#define RSA_R_UNKNOWN_DIGEST 166
#define RSA_R_UNKNOWN_MASK_DIGEST 151
#define RSA_R_UNKNOWN_PADDING_TYPE 118
#define RSA_R_UNSUPPORTED_ENCRYPTION_TYPE 162
#define RSA_R_UNSUPPORTED_LABEL_SOURCE 163
#define RSA_R_UNSUPPORTED_MASK_ALGORITHM 153
#define RSA_R_UNSUPPORTED_MASK_PARAMETER 154
#define RSA_R_UNSUPPORTED_SIGNATURE_TYPE 155
#define RSA_R_VALUE_MISSING 147
#define RSA_R_WRONG_SIGNATURE_LENGTH 119
Functions
RSA * RSA_new (void)
RSA * RSA_new_method (ENGINE *engine)
int RSA_bits (const RSA *rsa)
int RSA_size (const RSA *rsa)
int RSA_security_bits (const RSA *rsa)
int RSA_set0_key (RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d)
int RSA_set0_factors (RSA *r, BIGNUM *p, BIGNUM *q)
int RSA_set0_crt_params (RSA *r, BIGNUM *dmp1, BIGNUM *dmq1, BIGNUM *iqmp)
void RSA_get0_key (const RSA *r, const BIGNUM **n, const BIGNUM **e, const BIGNUM **d)
void RSA_get0_factors (const RSA *r, const BIGNUM **p, const BIGNUM **q)
void RSA_get0_crt_params (const RSA *r, const BIGNUM **dmp1, const BIGNUM **dmq1, const BIGNUM **iqmp)
void RSA_clear_flags (RSA *r, int flags)
int RSA_test_flags (const RSA *r, int flags)
void RSA_set_flags (RSA *r, int flags)
ENGINE * RSA_get0_engine (const RSA *r)
DEPRECATEDIN_0_9_8 (RSA *RSA_generate_key(int bits, unsigned long e, void(*callback)(int, int, void *), void *cb_arg)) int RSA_generate_key_ex(RSA *rsa
int RSA_X931_derive_ex (RSA *rsa, BIGNUM *p1, BIGNUM *p2, BIGNUM *q1, BIGNUM *q2, const BIGNUM *Xp1, const BIGNUM *Xp2, const BIGNUM *Xp, const BIGNUM *Xq1, const BIGNUM *Xq2, const BIGNUM *Xq, const BIGNUM *e, BN_GENCB *cb)
int RSA_X931_generate_key_ex (RSA *rsa, int bits, const BIGNUM *e, BN_GENCB *cb)
int RSA_check_key (const RSA *)
int RSA_check_key_ex (const RSA *, BN_GENCB *cb)
int RSA_public_encrypt (int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding)
int RSA_private_encrypt (int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding)
int RSA_public_decrypt (int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding)
int RSA_private_decrypt (int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding)
void RSA_free (RSA *r)
int RSA_up_ref (RSA *r)
int RSA_flags (const RSA *r)
void RSA_set_default_method (const RSA_METHOD *meth)
const RSA_METHOD * RSA_get_default_method (void)
const RSA_METHOD * RSA_get_method (const RSA *rsa)
int RSA_set_method (RSA *rsa, const RSA_METHOD *meth)
const RSA_METHOD * RSA_PKCS1_OpenSSL (void)
const RSA_METHOD * RSA_null_method (void)
int RSA_pkey_ctx_ctrl (EVP_PKEY_CTX *ctx, int optype, int cmd, int p1, void *p2)
DECLARE_ASN1_ENCODE_FUNCTIONS_const (RSA, RSAPublicKey) DECLARE_ASN1_ENCODE_FUNCTIONS_const(RSA
int RSA_print_fp (FILE *fp, const RSA *r, int offset)
int RSA_print (BIO *bp, const RSA *r, int offset)
int RSA_sign (int type, const unsigned char *m, unsigned int m_length, unsigned char *sigret, unsigned int *siglen, RSA *rsa)
int RSA_verify (int type, const unsigned char *m, unsigned int m_length, const unsigned char *sigbuf, unsigned int siglen, RSA *rsa)
int RSA_sign_ASN1_OCTET_STRING (int type, const unsigned char *m, unsigned int m_length, unsigned char *sigret, unsigned int *siglen, RSA *rsa)
int RSA_verify_ASN1_OCTET_STRING (int type, const unsigned char *m, unsigned int m_length, unsigned char *sigbuf, unsigned int siglen, RSA *rsa)
int RSA_blinding_on (RSA *rsa, BN_CTX *ctx)
void RSA_blinding_off (RSA *rsa)
BN_BLINDING * RSA_setup_blinding (RSA *rsa, BN_CTX *ctx)
int RSA_padding_add_PKCS1_type_1 (unsigned char *to, int tlen, const unsigned char *f, int fl)
int RSA_padding_check_PKCS1_type_1 (unsigned char *to, int tlen, const unsigned char *f, int fl, int rsa_len)
int RSA_padding_add_PKCS1_type_2 (unsigned char *to, int tlen, const unsigned char *f, int fl)
int RSA_padding_check_PKCS1_type_2 (unsigned char *to, int tlen, const unsigned char *f, int fl, int rsa_len)
int PKCS1_MGF1 (unsigned char *mask, long len, const unsigned char *seed, long seedlen, const EVP_MD *dgst)
int RSA_padding_add_PKCS1_OAEP (unsigned char *to, int tlen, const unsigned char *f, int fl, const unsigned char *p, int pl)
int RSA_padding_check_PKCS1_OAEP (unsigned char *to, int tlen, const unsigned char *f, int fl, int rsa_len, const unsigned char *p, int pl)
int RSA_padding_add_PKCS1_OAEP_mgf1 (unsigned char *to, int tlen, const unsigned char *from, int flen, const unsigned char *param, int plen, const EVP_MD *md, const EVP_MD *mgf1md)
int RSA_padding_check_PKCS1_OAEP_mgf1 (unsigned char *to, int tlen, const unsigned char *from, int flen, int num, const unsigned char *param, int plen, const EVP_MD *md, const EVP_MD *mgf1md)
int RSA_padding_add_SSLv23 (unsigned char *to, int tlen, const unsigned char *f, int fl)
int RSA_padding_check_SSLv23 (unsigned char *to, int tlen, const unsigned char *f, int fl, int rsa_len)
int RSA_padding_add_none (unsigned char *to, int tlen, const unsigned char *f, int fl)
int RSA_padding_check_none (unsigned char *to, int tlen, const unsigned char *f, int fl, int rsa_len)
int RSA_padding_add_X931 (unsigned char *to, int tlen, const unsigned char *f, int fl)
int RSA_padding_check_X931 (unsigned char *to, int tlen, const unsigned char *f, int fl, int rsa_len)
int RSA_X931_hash_id (int nid)
int RSA_verify_PKCS1_PSS (RSA *rsa, const unsigned char *mHash, const EVP_MD *Hash, const unsigned char *EM, int sLen)
int RSA_padding_add_PKCS1_PSS (RSA *rsa, unsigned char *EM, const unsigned char *mHash, const EVP_MD *Hash, int sLen)
int RSA_verify_PKCS1_PSS_mgf1 (RSA *rsa, const unsigned char *mHash, const EVP_MD *Hash, const EVP_MD *mgf1Hash, const unsigned char *EM, int sLen)
int RSA_padding_add_PKCS1_PSS_mgf1 (RSA *rsa, unsigned char *EM, const unsigned char *mHash, const EVP_MD *Hash, const EVP_MD *mgf1Hash, int sLen)
int RSA_set_ex_data (RSA *r, int idx, void *arg)
void * RSA_get_ex_data (const RSA *r, int idx)
RSA * RSAPublicKey_dup (RSA *rsa)
RSA * RSAPrivateKey_dup (RSA *rsa)
RSA_METHOD * RSA_meth_new (const char *name, int flags)
void RSA_meth_free (RSA_METHOD *meth)
RSA_METHOD * RSA_meth_dup (const RSA_METHOD *meth)
const char * RSA_meth_get0_name (const RSA_METHOD *meth)
int RSA_meth_set1_name (RSA_METHOD *meth, const char *name)
int RSA_meth_get_flags (RSA_METHOD *meth)
int RSA_meth_set_flags (RSA_METHOD *meth, int flags)
void * RSA_meth_get0_app_data (const RSA_METHOD *meth)
int RSA_meth_set0_app_data (RSA_METHOD *meth, void *app_data)
int RSA_meth_set_pub_enc (RSA_METHOD *rsa, int(*pub_enc)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding))
int RSA_meth_set_pub_dec (RSA_METHOD *rsa, int(*pub_dec)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding))
int RSA_meth_set_priv_enc (RSA_METHOD *rsa, int(*priv_enc)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding))
int RSA_meth_set_priv_dec (RSA_METHOD *rsa, int(*priv_dec)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding))
int RSA_meth_set_mod_exp (RSA_METHOD *rsa, int(*mod_exp)(BIGNUM *r0, const BIGNUM *I, RSA *rsa, BN_CTX *ctx))
int RSA_meth_set_bn_mod_exp (RSA_METHOD *rsa, int(*bn_mod_exp)(BIGNUM *r, const BIGNUM *a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *m_ctx))
int RSA_meth_set_init (RSA_METHOD *rsa, int(*init)(RSA *rsa))
int RSA_meth_set_finish (RSA_METHOD *rsa, int(*finish)(RSA *rsa))
int RSA_meth_set_sign (RSA_METHOD *rsa, int(*sign)(int type, const unsigned char *m, unsigned int m_length, unsigned char *sigret, unsigned int *siglen, const RSA *rsa))
int RSA_meth_set_verify (RSA_METHOD *rsa, int(*verify)(int dtype, const unsigned char *m, unsigned int m_length, const unsigned char *sigbuf, unsigned int siglen, const RSA *rsa))
int RSA_meth_set_keygen (RSA_METHOD *rsa, int(*keygen)(RSA *rsa, int bits, BIGNUM *e, BN_GENCB *cb))
int ERR_load_RSA_strings (void)
Variables
int bits
int BIGNUM * e
int BIGNUM BN_GENCB * cb
int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) RSA_meth_get_pub_enc (const RSA_METHOD *meth)
int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) RSA_meth_get_pub_dec (const RSA_METHOD *meth)
int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) RSA_meth_get_priv_enc (const RSA_METHOD *meth)
int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) RSA_meth_get_priv_dec (const RSA_METHOD *meth)
int(*)(BIGNUM *r0, const BIGNUM *I, RSA *rsa, BN_CTX *ctx) RSA_meth_get_mod_exp (const RSA_METHOD *meth)
int(*)(BIGNUM *r, const BIGNUM *a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *m_ctx) RSA_meth_get_bn_mod_exp (const RSA_METHOD *meth)
int(*)(RSA *rsa) RSA_meth_get_init (const RSA_METHOD *meth)
int(*)(RSA *rsa) RSA_meth_get_finish (const RSA_METHOD *meth)
int(*)(int type, const unsigned char *m, unsigned int m_length, unsigned char *sigret, unsigned int *siglen, const RSA *rsa) RSA_meth_get_sign (const RSA_METHOD *meth)
int(*)(int dtype, const unsigned char *m, unsigned int m_length, const unsigned char *sigbuf, unsigned int siglen, const RSA *rsa) RSA_meth_get_verify (const RSA_METHOD *meth)
int(*)(RSA *rsa, int bits, BIGNUM *e, BN_GENCB *cb) RSA_meth_get_keygen (const RSA_METHOD *meth)
Macro Definition Documentation
EVP_PKEY_CTRL_GET_RSA_MGF1_MD
#define EVP_PKEY_CTRL_GET_RSA_MGF1_MD (EVP_PKEY_ALG_CTRL + 8)
Definition at line 164 of file rsa.h.
EVP_PKEY_CTRL_GET_RSA_OAEP_LABEL
#define EVP_PKEY_CTRL_GET_RSA_OAEP_LABEL (EVP_PKEY_ALG_CTRL + 12)
Definition at line 170 of file rsa.h.
EVP_PKEY_CTRL_GET_RSA_OAEP_MD
#define EVP_PKEY_CTRL_GET_RSA_OAEP_MD (EVP_PKEY_ALG_CTRL + 11)
Definition at line 169 of file rsa.h.
EVP_PKEY_CTRL_GET_RSA_PADDING
#define EVP_PKEY_CTRL_GET_RSA_PADDING (EVP_PKEY_ALG_CTRL + 6)
Definition at line 162 of file rsa.h.
EVP_PKEY_CTRL_GET_RSA_PSS_SALTLEN
#define EVP_PKEY_CTRL_GET_RSA_PSS_SALTLEN (EVP_PKEY_ALG_CTRL + 7)
Definition at line 163 of file rsa.h.
EVP_PKEY_CTRL_RSA_KEYGEN_BITS
#define EVP_PKEY_CTRL_RSA_KEYGEN_BITS (EVP_PKEY_ALG_CTRL + 3)
Definition at line 158 of file rsa.h.
EVP_PKEY_CTRL_RSA_KEYGEN_PUBEXP
#define EVP_PKEY_CTRL_RSA_KEYGEN_PUBEXP (EVP_PKEY_ALG_CTRL + 4)
Definition at line 159 of file rsa.h.
EVP_PKEY_CTRL_RSA_MGF1_MD
#define EVP_PKEY_CTRL_RSA_MGF1_MD (EVP_PKEY_ALG_CTRL + 5)
Definition at line 160 of file rsa.h.
EVP_PKEY_CTRL_RSA_OAEP_LABEL
#define EVP_PKEY_CTRL_RSA_OAEP_LABEL (EVP_PKEY_ALG_CTRL + 10)
Definition at line 167 of file rsa.h.
EVP_PKEY_CTRL_RSA_OAEP_MD
#define EVP_PKEY_CTRL_RSA_OAEP_MD (EVP_PKEY_ALG_CTRL + 9)
Definition at line 166 of file rsa.h.
EVP_PKEY_CTRL_RSA_PADDING
#define EVP_PKEY_CTRL_RSA_PADDING (EVP_PKEY_ALG_CTRL + 1)
Definition at line 155 of file rsa.h.
EVP_PKEY_CTRL_RSA_PSS_SALTLEN
#define EVP_PKEY_CTRL_RSA_PSS_SALTLEN (EVP_PKEY_ALG_CTRL + 2)
Definition at line 156 of file rsa.h.
EVP_PKEY_CTX_get0_rsa_oaep_label
#define EVP_PKEY_CTX_get0_rsa_oaep_label (ctx, l)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_RSA, EVP_PKEY_OP_TYPE_CRYPT,  \
                                EVP_PKEY_CTRL_GET_RSA_OAEP_LABEL, 0, (void *)l)
Definition at line 146 of file rsa.h.
EVP_PKEY_CTX_get_rsa_mgf1_md
#define EVP_PKEY_CTX_get_rsa_mgf1_md (ctx, pmd)
Value:
RSA_pkey_ctx_ctrl(ctx, EVP_PKEY_OP_TYPE_SIG | EVP_PKEY_OP_TYPE_CRYPT, \
                          EVP_PKEY_CTRL_GET_RSA_MGF1_MD, 0, (void *)pmd)
Definition at line 134 of file rsa.h.
EVP_PKEY_CTX_get_rsa_oaep_md
#define EVP_PKEY_CTX_get_rsa_oaep_md (ctx, pmd)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_RSA, EVP_PKEY_OP_TYPE_CRYPT,  \
                                EVP_PKEY_CTRL_GET_RSA_OAEP_MD, 0, (void *)pmd)
Definition at line 138 of file rsa.h.
EVP_PKEY_CTX_get_rsa_padding
#define EVP_PKEY_CTX_get_rsa_padding (ctx, ppad) RSA_pkey_ctx_ctrl(ctx, -1, EVP_PKEY_CTRL_GET_RSA_PADDING, 0, ppad)
Definition at line 91 of file rsa.h.
EVP_PKEY_CTX_get_rsa_pss_saltlen
#define EVP_PKEY_CTX_get_rsa_pss_saltlen (ctx, plen)
Value:
RSA_pkey_ctx_ctrl(ctx, (EVP_PKEY_OP_SIGN|EVP_PKEY_OP_VERIFY), \
                          EVP_PKEY_CTRL_GET_RSA_PSS_SALTLEN, 0, plen)
Definition at line 110 of file rsa.h.
EVP_PKEY_CTX_rsa_pss_keygen_md
#define EVP_PKEY_CTX_rsa_pss_keygen_md (ctx, md)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_RSA_PSS, \
                                  EVP_PKEY_OP_TYPE_KEYGEN, EVP_PKEY_CTRL_MD, \
                                  0, (void *)md)
Definition at line 150 of file rsa.h.
EVP_PKEY_CTX_set0_rsa_oaep_label
#define EVP_PKEY_CTX_set0_rsa_oaep_label (ctx, l, llen)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_RSA, EVP_PKEY_OP_TYPE_CRYPT,  \
                                EVP_PKEY_CTRL_RSA_OAEP_LABEL, llen, (void *)l)
Definition at line 142 of file rsa.h.
EVP_PKEY_CTX_set_rsa_keygen_bits
#define EVP_PKEY_CTX_set_rsa_keygen_bits (ctx, bits)
Value:
RSA_pkey_ctx_ctrl(ctx, EVP_PKEY_OP_KEYGEN, \
                          EVP_PKEY_CTRL_RSA_KEYGEN_BITS, bits, NULL)
Definition at line 114 of file rsa.h.
EVP_PKEY_CTX_set_rsa_keygen_pubexp
#define EVP_PKEY_CTX_set_rsa_keygen_pubexp (ctx, pubexp)
Value:
RSA_pkey_ctx_ctrl(ctx, EVP_PKEY_OP_KEYGEN, \
                          EVP_PKEY_CTRL_RSA_KEYGEN_PUBEXP, 0, pubexp)
Definition at line 118 of file rsa.h.
EVP_PKEY_CTX_set_rsa_mgf1_md
#define EVP_PKEY_CTX_set_rsa_mgf1_md (ctx, md)
Value:
RSA_pkey_ctx_ctrl(ctx, EVP_PKEY_OP_TYPE_SIG | EVP_PKEY_OP_TYPE_CRYPT, \
                          EVP_PKEY_CTRL_RSA_MGF1_MD, 0, (void *)md)
Definition at line 122 of file rsa.h.
EVP_PKEY_CTX_set_rsa_oaep_md
#define EVP_PKEY_CTX_set_rsa_oaep_md (ctx, md)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_RSA, EVP_PKEY_OP_TYPE_CRYPT,  \
                                EVP_PKEY_CTRL_RSA_OAEP_MD, 0, (void *)md)
Definition at line 130 of file rsa.h.
EVP_PKEY_CTX_set_rsa_padding
#define EVP_PKEY_CTX_set_rsa_padding (ctx, pad) RSA_pkey_ctx_ctrl(ctx, -1, EVP_PKEY_CTRL_RSA_PADDING, pad, NULL)
Definition at line 88 of file rsa.h.
EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md
#define EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md (ctx, md)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_RSA_PSS, EVP_PKEY_OP_KEYGEN, \
                          EVP_PKEY_CTRL_RSA_MGF1_MD, 0, (void *)md)
Definition at line 126 of file rsa.h.
EVP_PKEY_CTX_set_rsa_pss_keygen_saltlen
#define EVP_PKEY_CTX_set_rsa_pss_keygen_saltlen (ctx, len)
Value:
EVP_PKEY_CTX_ctrl(ctx, EVP_PKEY_RSA_PSS, EVP_PKEY_OP_KEYGEN, \
                          EVP_PKEY_CTRL_RSA_PSS_SALTLEN, len, NULL)
Definition at line 106 of file rsa.h.
EVP_PKEY_CTX_set_rsa_pss_saltlen
#define EVP_PKEY_CTX_set_rsa_pss_saltlen (ctx, len)
Value:
RSA_pkey_ctx_ctrl(ctx, (EVP_PKEY_OP_SIGN|EVP_PKEY_OP_VERIFY), \
                          EVP_PKEY_CTRL_RSA_PSS_SALTLEN, len, NULL)
Definition at line 94 of file rsa.h.
OPENSSL_RSA_FIPS_MIN_MODULUS_BITS
#define OPENSSL_RSA_FIPS_MIN_MODULUS_BITS 1024
Definition at line 33 of file rsa.h.
OPENSSL_RSA_MAX_MODULUS_BITS
#define OPENSSL_RSA_MAX_MODULUS_BITS 16384
Definition at line 30 of file rsa.h.
OPENSSL_RSA_MAX_PUBEXP_BITS
#define OPENSSL_RSA_MAX_PUBEXP_BITS 64
Definition at line 41 of file rsa.h.
OPENSSL_RSA_SMALL_MODULUS_BITS
#define OPENSSL_RSA_SMALL_MODULUS_BITS 3072
Definition at line 36 of file rsa.h.
RSA_3
#define RSA_3 0x3L
Definition at line 44 of file rsa.h.
RSA_F4
#define RSA_F4 0x10001L
Definition at line 45 of file rsa.h.
RSA_F_CHECK_PADDING_MD
#define RSA_F_CHECK_PADDING_MD 140
Definition at line 483 of file rsa.h.
RSA_F_ENCODE_PKCS1
#define RSA_F_ENCODE_PKCS1 146
Definition at line 484 of file rsa.h.
RSA_F_INT_RSA_VERIFY
#define RSA_F_INT_RSA_VERIFY 145
Definition at line 485 of file rsa.h.
RSA_F_OLD_RSA_PRIV_DECODE
#define RSA_F_OLD_RSA_PRIV_DECODE 147
Definition at line 486 of file rsa.h.
RSA_F_PKEY_PSS_INIT
#define RSA_F_PKEY_PSS_INIT 165
Definition at line 487 of file rsa.h.
RSA_F_PKEY_RSA_CTRL
#define RSA_F_PKEY_RSA_CTRL 143
Definition at line 488 of file rsa.h.
RSA_F_PKEY_RSA_CTRL_STR
#define RSA_F_PKEY_RSA_CTRL_STR 144
Definition at line 489 of file rsa.h.
RSA_F_PKEY_RSA_SIGN
#define RSA_F_PKEY_RSA_SIGN 142
Definition at line 490 of file rsa.h.
RSA_F_PKEY_RSA_VERIFY
#define RSA_F_PKEY_RSA_VERIFY 149
Definition at line 491 of file rsa.h.
RSA_F_PKEY_RSA_VERIFYRECOVER
#define RSA_F_PKEY_RSA_VERIFYRECOVER 141
Definition at line 492 of file rsa.h.
RSA_F_RSA_ALGOR_TO_MD
#define RSA_F_RSA_ALGOR_TO_MD 156
Definition at line 493 of file rsa.h.
RSA_F_RSA_BUILTIN_KEYGEN
#define RSA_F_RSA_BUILTIN_KEYGEN 129
Definition at line 494 of file rsa.h.
RSA_F_RSA_CHECK_KEY
#define RSA_F_RSA_CHECK_KEY 123
Definition at line 495 of file rsa.h.
RSA_F_RSA_CHECK_KEY_EX
#define RSA_F_RSA_CHECK_KEY_EX 160
Definition at line 496 of file rsa.h.
RSA_F_RSA_CMS_DECRYPT
#define RSA_F_RSA_CMS_DECRYPT 159
Definition at line 497 of file rsa.h.
RSA_F_RSA_CMS_VERIFY
#define RSA_F_RSA_CMS_VERIFY 158
Definition at line 498 of file rsa.h.
RSA_F_RSA_ITEM_VERIFY
#define RSA_F_RSA_ITEM_VERIFY 148
Definition at line 499 of file rsa.h.
RSA_F_RSA_METH_DUP
#define RSA_F_RSA_METH_DUP 161
Definition at line 500 of file rsa.h.
RSA_F_RSA_METH_NEW
#define RSA_F_RSA_METH_NEW 162
Definition at line 501 of file rsa.h.
Referenced by RSA_meth_new().
RSA_F_RSA_METH_SET1_NAME
#define RSA_F_RSA_METH_SET1_NAME 163
Definition at line 502 of file rsa.h.
Referenced by RSA_meth_set1_name().
RSA_F_RSA_MGF1_TO_MD
#define RSA_F_RSA_MGF1_TO_MD 157
Definition at line 503 of file rsa.h.
RSA_F_RSA_NEW_METHOD
#define RSA_F_RSA_NEW_METHOD 106
Definition at line 504 of file rsa.h.
RSA_F_RSA_NULL
#define RSA_F_RSA_NULL 124
Definition at line 505 of file rsa.h.
RSA_F_RSA_NULL_PRIVATE_DECRYPT
#define RSA_F_RSA_NULL_PRIVATE_DECRYPT 132
Definition at line 506 of file rsa.h.
RSA_F_RSA_NULL_PRIVATE_ENCRYPT
#define RSA_F_RSA_NULL_PRIVATE_ENCRYPT 133
Definition at line 507 of file rsa.h.
RSA_F_RSA_NULL_PUBLIC_DECRYPT
#define RSA_F_RSA_NULL_PUBLIC_DECRYPT 134
Definition at line 508 of file rsa.h.
RSA_F_RSA_NULL_PUBLIC_ENCRYPT
#define RSA_F_RSA_NULL_PUBLIC_ENCRYPT 135
Definition at line 509 of file rsa.h.
RSA_F_RSA_OSSL_PRIVATE_DECRYPT
#define RSA_F_RSA_OSSL_PRIVATE_DECRYPT 101
Definition at line 510 of file rsa.h.
RSA_F_RSA_OSSL_PRIVATE_ENCRYPT
#define RSA_F_RSA_OSSL_PRIVATE_ENCRYPT 102
Definition at line 511 of file rsa.h.
RSA_F_RSA_OSSL_PUBLIC_DECRYPT
#define RSA_F_RSA_OSSL_PUBLIC_DECRYPT 103
Definition at line 512 of file rsa.h.
RSA_F_RSA_OSSL_PUBLIC_ENCRYPT
#define RSA_F_RSA_OSSL_PUBLIC_ENCRYPT 104
Definition at line 513 of file rsa.h.
RSA_F_RSA_PADDING_ADD_NONE
#define RSA_F_RSA_PADDING_ADD_NONE 107
Definition at line 514 of file rsa.h.
Referenced by RSA_padding_add_none().
RSA_F_RSA_PADDING_ADD_PKCS1_OAEP
#define RSA_F_RSA_PADDING_ADD_PKCS1_OAEP 121
Definition at line 515 of file rsa.h.
RSA_F_RSA_PADDING_ADD_PKCS1_OAEP_MGF1
#define RSA_F_RSA_PADDING_ADD_PKCS1_OAEP_MGF1 154
Definition at line 516 of file rsa.h.
RSA_F_RSA_PADDING_ADD_PKCS1_PSS
#define RSA_F_RSA_PADDING_ADD_PKCS1_PSS 125
Definition at line 517 of file rsa.h.
RSA_F_RSA_PADDING_ADD_PKCS1_PSS_MGF1
#define RSA_F_RSA_PADDING_ADD_PKCS1_PSS_MGF1 152
Definition at line 518 of file rsa.h.
RSA_F_RSA_PADDING_ADD_PKCS1_TYPE_1
#define RSA_F_RSA_PADDING_ADD_PKCS1_TYPE_1 108
Definition at line 519 of file rsa.h.
Referenced by RSA_padding_add_PKCS1_type_1().
RSA_F_RSA_PADDING_ADD_PKCS1_TYPE_2
#define RSA_F_RSA_PADDING_ADD_PKCS1_TYPE_2 109
Definition at line 520 of file rsa.h.
Referenced by RSA_padding_add_PKCS1_type_2().
RSA_F_RSA_PADDING_ADD_SSLV23
#define RSA_F_RSA_PADDING_ADD_SSLV23 110
Definition at line 521 of file rsa.h.
Referenced by RSA_padding_add_SSLv23().
RSA_F_RSA_PADDING_ADD_X931
#define RSA_F_RSA_PADDING_ADD_X931 127
Definition at line 522 of file rsa.h.
Referenced by RSA_padding_add_X931().
RSA_F_RSA_PADDING_CHECK_NONE
#define RSA_F_RSA_PADDING_CHECK_NONE 111
Definition at line 523 of file rsa.h.
Referenced by RSA_padding_check_none().
RSA_F_RSA_PADDING_CHECK_PKCS1_OAEP
#define RSA_F_RSA_PADDING_CHECK_PKCS1_OAEP 122
Definition at line 524 of file rsa.h.
RSA_F_RSA_PADDING_CHECK_PKCS1_OAEP_MGF1
#define RSA_F_RSA_PADDING_CHECK_PKCS1_OAEP_MGF1 153
Definition at line 525 of file rsa.h.
RSA_F_RSA_PADDING_CHECK_PKCS1_TYPE_1
#define RSA_F_RSA_PADDING_CHECK_PKCS1_TYPE_1 112
Definition at line 526 of file rsa.h.
Referenced by RSA_padding_check_PKCS1_type_1().
RSA_F_RSA_PADDING_CHECK_PKCS1_TYPE_2
#define RSA_F_RSA_PADDING_CHECK_PKCS1_TYPE_2 113
Definition at line 527 of file rsa.h.
Referenced by RSA_padding_check_PKCS1_type_2().
RSA_F_RSA_PADDING_CHECK_SSLV23
#define RSA_F_RSA_PADDING_CHECK_SSLV23 114
Definition at line 528 of file rsa.h.
RSA_F_RSA_PADDING_CHECK_X931
#define RSA_F_RSA_PADDING_CHECK_X931 128
Definition at line 529 of file rsa.h.
Referenced by RSA_padding_check_X931().
RSA_F_RSA_PARAM_DECODE
#define RSA_F_RSA_PARAM_DECODE 164
Definition at line 530 of file rsa.h.
RSA_F_RSA_PRINT
#define RSA_F_RSA_PRINT 115
Definition at line 531 of file rsa.h.
RSA_F_RSA_PRINT_FP
#define RSA_F_RSA_PRINT_FP 116
Definition at line 532 of file rsa.h.
RSA_F_RSA_PRIV_DECODE
#define RSA_F_RSA_PRIV_DECODE 150
Definition at line 533 of file rsa.h.
RSA_F_RSA_PRIV_ENCODE
#define RSA_F_RSA_PRIV_ENCODE 138
Definition at line 534 of file rsa.h.
RSA_F_RSA_PSS_GET_PARAM
#define RSA_F_RSA_PSS_GET_PARAM 151
Definition at line 535 of file rsa.h.
RSA_F_RSA_PSS_TO_CTX
#define RSA_F_RSA_PSS_TO_CTX 155
Definition at line 536 of file rsa.h.
RSA_F_RSA_PUB_DECODE
#define RSA_F_RSA_PUB_DECODE 139
Definition at line 537 of file rsa.h.
RSA_F_RSA_SETUP_BLINDING
#define RSA_F_RSA_SETUP_BLINDING 136
Definition at line 538 of file rsa.h.
RSA_F_RSA_SIGN
#define RSA_F_RSA_SIGN 117
Definition at line 539 of file rsa.h.
RSA_F_RSA_SIGN_ASN1_OCTET_STRING
#define RSA_F_RSA_SIGN_ASN1_OCTET_STRING 118
Definition at line 540 of file rsa.h.
RSA_F_RSA_VERIFY
#define RSA_F_RSA_VERIFY 119
Definition at line 541 of file rsa.h.
RSA_F_RSA_VERIFY_ASN1_OCTET_STRING
#define RSA_F_RSA_VERIFY_ASN1_OCTET_STRING 120
Definition at line 542 of file rsa.h.
RSA_F_RSA_VERIFY_PKCS1_PSS_MGF1
#define RSA_F_RSA_VERIFY_PKCS1_PSS_MGF1 126
Definition at line 543 of file rsa.h.
RSA_FLAG_BLINDING
#define RSA_FLAG_BLINDING 0x0008
Definition at line 52 of file rsa.h.
Referenced by RSA_blinding_off().
RSA_FLAG_CACHE_PRIVATE
#define RSA_FLAG_CACHE_PRIVATE 0x0004
Definition at line 51 of file rsa.h.
RSA_FLAG_CACHE_PUBLIC
#define RSA_FLAG_CACHE_PUBLIC 0x0002
Definition at line 50 of file rsa.h.
RSA_FLAG_CHECKED
#define RSA_FLAG_CHECKED 0x0800
Definition at line 389 of file rsa.h.
RSA_FLAG_EXT_PKEY
#define RSA_FLAG_EXT_PKEY 0x0020
Definition at line 60 of file rsa.h.
RSA_FLAG_FIPS_METHOD
#define RSA_FLAG_FIPS_METHOD 0x0400
Definition at line 376 of file rsa.h.
RSA_FLAG_NO_BLINDING
#define RSA_FLAG_NO_BLINDING 0x0080
Definition at line 68 of file rsa.h.
Referenced by RSA_blinding_off().
RSA_FLAG_NO_CONSTTIME
#define RSA_FLAG_NO_CONSTTIME 0x0000
Definition at line 73 of file rsa.h.
RSA_FLAG_NO_EXP_CONSTTIME
#define RSA_FLAG_NO_EXP_CONSTTIME RSA_FLAG_NO_CONSTTIME
Definition at line 85 of file rsa.h.
RSA_FLAG_NON_FIPS_ALLOW
#define RSA_FLAG_NON_FIPS_ALLOW 0x0400
Definition at line 384 of file rsa.h.
RSA_FLAG_THREAD_SAFE
#define RSA_FLAG_THREAD_SAFE 0x0010
Definition at line 53 of file rsa.h.
RSA_get_app_data
#define RSA_get_app_data (s) RSA_get_ex_data(s,0)
Definition at line 183 of file rsa.h.
RSA_get_ex_new_index
#define RSA_get_ex_new_index (l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_RSA, l, p, newf, dupf, freef)
Definition at line 361 of file rsa.h.
RSA_METHOD_FLAG_NO_CHECK
#define RSA_METHOD_FLAG_NO_CHECK
Value:
0x0001/* don't check pub/private
                                                * match */
Definition at line 47 of file rsa.h.
RSA_NO_PADDING
#define RSA_NO_PADDING 3
Definition at line 174 of file rsa.h.
RSA_PKCS1_OAEP_PADDING
#define RSA_PKCS1_OAEP_PADDING 4
Definition at line 175 of file rsa.h.
RSA_PKCS1_PADDING
#define RSA_PKCS1_PADDING 1
Definition at line 172 of file rsa.h.
RSA_PKCS1_PADDING_SIZE
#define RSA_PKCS1_PADDING_SIZE 11
Definition at line 180 of file rsa.h.
Referenced by RSA_padding_add_PKCS1_type_1().
RSA_PKCS1_PSS_PADDING
#define RSA_PKCS1_PSS_PADDING 6
Definition at line 178 of file rsa.h.
RSA_PSS_SALTLEN_AUTO
#define RSA_PSS_SALTLEN_AUTO -2
Definition at line 100 of file rsa.h.
RSA_PSS_SALTLEN_DIGEST
#define RSA_PSS_SALTLEN_DIGEST -1
Definition at line 98 of file rsa.h.
RSA_PSS_SALTLEN_MAX
#define RSA_PSS_SALTLEN_MAX -3
Definition at line 102 of file rsa.h.
RSA_PSS_SALTLEN_MAX_SIGN
#define RSA_PSS_SALTLEN_MAX_SIGN -2
Definition at line 104 of file rsa.h.
RSA_R_ALGORITHM_MISMATCH
#define RSA_R_ALGORITHM_MISMATCH 100
Definition at line 546 of file rsa.h.
RSA_R_BAD_E_VALUE
#define RSA_R_BAD_E_VALUE 101
Definition at line 547 of file rsa.h.
RSA_R_BAD_FIXED_HEADER_DECRYPT
#define RSA_R_BAD_FIXED_HEADER_DECRYPT 102
Definition at line 548 of file rsa.h.
Referenced by RSA_padding_check_PKCS1_type_1().
RSA_R_BAD_PAD_BYTE_COUNT
#define RSA_R_BAD_PAD_BYTE_COUNT 103
Definition at line 549 of file rsa.h.
Referenced by RSA_padding_check_PKCS1_type_1().
RSA_R_BAD_SIGNATURE
#define RSA_R_BAD_SIGNATURE 104
Definition at line 550 of file rsa.h.
RSA_R_BLOCK_TYPE_IS_NOT_01
#define RSA_R_BLOCK_TYPE_IS_NOT_01 106
Definition at line 551 of file rsa.h.
Referenced by RSA_padding_check_PKCS1_type_1().
RSA_R_BLOCK_TYPE_IS_NOT_02
#define RSA_R_BLOCK_TYPE_IS_NOT_02 107
Definition at line 552 of file rsa.h.
RSA_R_D_E_NOT_CONGRUENT_TO_1
#define RSA_R_D_E_NOT_CONGRUENT_TO_1 123
Definition at line 564 of file rsa.h.
RSA_R_DATA_GREATER_THAN_MOD_LEN
#define RSA_R_DATA_GREATER_THAN_MOD_LEN 108
Definition at line 553 of file rsa.h.
RSA_R_DATA_TOO_LARGE
#define RSA_R_DATA_TOO_LARGE 109
Definition at line 554 of file rsa.h.
Referenced by RSA_padding_check_none(), and RSA_padding_check_PKCS1_type_1().
RSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE
#define RSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE 110
Definition at line 555 of file rsa.h.
Referenced by RSA_padding_add_none(), RSA_padding_add_PKCS1_type_1(), RSA_padding_add_PKCS1_type_2(), RSA_padding_add_SSLv23(), and RSA_padding_add_X931().
RSA_R_DATA_TOO_LARGE_FOR_MODULUS
#define RSA_R_DATA_TOO_LARGE_FOR_MODULUS 132
Definition at line 556 of file rsa.h.
RSA_R_DATA_TOO_SMALL
#define RSA_R_DATA_TOO_SMALL 111
Definition at line 557 of file rsa.h.
RSA_R_DATA_TOO_SMALL_FOR_KEY_SIZE
#define RSA_R_DATA_TOO_SMALL_FOR_KEY_SIZE 122
Definition at line 558 of file rsa.h.
Referenced by RSA_padding_add_none().
RSA_R_DIGEST_DOES_NOT_MATCH
#define RSA_R_DIGEST_DOES_NOT_MATCH 158
Definition at line 559 of file rsa.h.
RSA_R_DIGEST_NOT_ALLOWED
#define RSA_R_DIGEST_NOT_ALLOWED 145
Definition at line 560 of file rsa.h.
RSA_R_DIGEST_TOO_BIG_FOR_RSA_KEY
#define RSA_R_DIGEST_TOO_BIG_FOR_RSA_KEY 112
Definition at line 561 of file rsa.h.
RSA_R_DMP1_NOT_CONGRUENT_TO_D
#define RSA_R_DMP1_NOT_CONGRUENT_TO_D 124
Definition at line 562 of file rsa.h.
RSA_R_DMQ1_NOT_CONGRUENT_TO_D
#define RSA_R_DMQ1_NOT_CONGRUENT_TO_D 125
Definition at line 563 of file rsa.h.
RSA_R_FIRST_OCTET_INVALID
#define RSA_R_FIRST_OCTET_INVALID 133
Definition at line 565 of file rsa.h.
RSA_R_ILLEGAL_OR_UNSUPPORTED_PADDING_MODE
#define RSA_R_ILLEGAL_OR_UNSUPPORTED_PADDING_MODE 144
Definition at line 566 of file rsa.h.
RSA_R_INVALID_DIGEST
#define RSA_R_INVALID_DIGEST 157
Definition at line 567 of file rsa.h.
RSA_R_INVALID_DIGEST_LENGTH
#define RSA_R_INVALID_DIGEST_LENGTH 143
Definition at line 568 of file rsa.h.
RSA_R_INVALID_HEADER
#define RSA_R_INVALID_HEADER 137
Definition at line 569 of file rsa.h.
Referenced by RSA_padding_check_X931().
RSA_R_INVALID_LABEL
#define RSA_R_INVALID_LABEL 160
Definition at line 570 of file rsa.h.
RSA_R_INVALID_MESSAGE_LENGTH
#define RSA_R_INVALID_MESSAGE_LENGTH 131
Definition at line 571 of file rsa.h.
RSA_R_INVALID_MGF1_MD
#define RSA_R_INVALID_MGF1_MD 156
Definition at line 572 of file rsa.h.
RSA_R_INVALID_OAEP_PARAMETERS
#define RSA_R_INVALID_OAEP_PARAMETERS 161
Definition at line 573 of file rsa.h.
RSA_R_INVALID_PADDING
#define RSA_R_INVALID_PADDING 138
Definition at line 574 of file rsa.h.
Referenced by RSA_padding_check_PKCS1_type_1().
RSA_R_INVALID_PADDING_MODE
#define RSA_R_INVALID_PADDING_MODE 141
Definition at line 575 of file rsa.h.
RSA_R_INVALID_PSS_PARAMETERS
#define RSA_R_INVALID_PSS_PARAMETERS 149
Definition at line 576 of file rsa.h.
RSA_R_INVALID_PSS_SALTLEN
#define RSA_R_INVALID_PSS_SALTLEN 146
Definition at line 577 of file rsa.h.
RSA_R_INVALID_SALT_LENGTH
#define RSA_R_INVALID_SALT_LENGTH 150
Definition at line 578 of file rsa.h.
RSA_R_INVALID_TRAILER
#define RSA_R_INVALID_TRAILER 139
Definition at line 579 of file rsa.h.
RSA_R_INVALID_X931_DIGEST
#define RSA_R_INVALID_X931_DIGEST 142
Definition at line 580 of file rsa.h.
RSA_R_IQMP_NOT_INVERSE_OF_Q
#define RSA_R_IQMP_NOT_INVERSE_OF_Q 126
Definition at line 581 of file rsa.h.
RSA_R_KEY_SIZE_TOO_SMALL
#define RSA_R_KEY_SIZE_TOO_SMALL 120
Definition at line 582 of file rsa.h.
RSA_R_LAST_OCTET_INVALID
#define RSA_R_LAST_OCTET_INVALID 134
Definition at line 583 of file rsa.h.
RSA_R_MGF1_DIGEST_NOT_ALLOWED
#define RSA_R_MGF1_DIGEST_NOT_ALLOWED 152
Definition at line 584 of file rsa.h.
RSA_R_MODULUS_TOO_LARGE
#define RSA_R_MODULUS_TOO_LARGE 105
Definition at line 585 of file rsa.h.
RSA_R_N_DOES_NOT_EQUAL_P_Q
#define RSA_R_N_DOES_NOT_EQUAL_P_Q 127
Definition at line 588 of file rsa.h.
RSA_R_NO_PUBLIC_EXPONENT
#define RSA_R_NO_PUBLIC_EXPONENT 140
Definition at line 586 of file rsa.h.
RSA_R_NULL_BEFORE_BLOCK_MISSING
#define RSA_R_NULL_BEFORE_BLOCK_MISSING 113
Definition at line 587 of file rsa.h.
Referenced by RSA_padding_check_PKCS1_type_1().
RSA_R_OAEP_DECODING_ERROR
#define RSA_R_OAEP_DECODING_ERROR 121
Definition at line 589 of file rsa.h.
RSA_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE
#define RSA_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE 148
Definition at line 590 of file rsa.h.
RSA_R_P_NOT_PRIME
#define RSA_R_P_NOT_PRIME 128
Definition at line 594 of file rsa.h.
RSA_R_PADDING_CHECK_FAILED
#define RSA_R_PADDING_CHECK_FAILED 114
Definition at line 591 of file rsa.h.
RSA_R_PKCS_DECODING_ERROR
#define RSA_R_PKCS_DECODING_ERROR 159
Definition at line 592 of file rsa.h.
RSA_R_PSS_SALTLEN_TOO_SMALL
#define RSA_R_PSS_SALTLEN_TOO_SMALL 164
Definition at line 593 of file rsa.h.
RSA_R_Q_NOT_PRIME
#define RSA_R_Q_NOT_PRIME 129
Definition at line 595 of file rsa.h.
RSA_R_RSA_OPERATIONS_NOT_SUPPORTED
#define RSA_R_RSA_OPERATIONS_NOT_SUPPORTED 130
Definition at line 596 of file rsa.h.
RSA_R_SLEN_CHECK_FAILED
#define RSA_R_SLEN_CHECK_FAILED 136
Definition at line 597 of file rsa.h.
RSA_R_SLEN_RECOVERY_FAILED
#define RSA_R_SLEN_RECOVERY_FAILED 135
Definition at line 598 of file rsa.h.
RSA_R_SSLV3_ROLLBACK_ATTACK
#define RSA_R_SSLV3_ROLLBACK_ATTACK 115
Definition at line 599 of file rsa.h.
RSA_R_THE_ASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD
#define RSA_R_THE_ASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD 116
Definition at line 600 of file rsa.h.
RSA_R_UNKNOWN_ALGORITHM_TYPE
#define RSA_R_UNKNOWN_ALGORITHM_TYPE 117
Definition at line 601 of file rsa.h.
RSA_R_UNKNOWN_DIGEST
#define RSA_R_UNKNOWN_DIGEST 166
Definition at line 602 of file rsa.h.
RSA_R_UNKNOWN_MASK_DIGEST
#define RSA_R_UNKNOWN_MASK_DIGEST 151
Definition at line 603 of file rsa.h.
RSA_R_UNKNOWN_PADDING_TYPE
#define RSA_R_UNKNOWN_PADDING_TYPE 118
Definition at line 604 of file rsa.h.
RSA_R_UNSUPPORTED_ENCRYPTION_TYPE
#define RSA_R_UNSUPPORTED_ENCRYPTION_TYPE 162
Definition at line 605 of file rsa.h.
RSA_R_UNSUPPORTED_LABEL_SOURCE
#define RSA_R_UNSUPPORTED_LABEL_SOURCE 163
Definition at line 606 of file rsa.h.
RSA_R_UNSUPPORTED_MASK_ALGORITHM
#define RSA_R_UNSUPPORTED_MASK_ALGORITHM 153
Definition at line 607 of file rsa.h.
RSA_R_UNSUPPORTED_MASK_PARAMETER
#define RSA_R_UNSUPPORTED_MASK_PARAMETER 154
Definition at line 608 of file rsa.h.
RSA_R_UNSUPPORTED_SIGNATURE_TYPE
#define RSA_R_UNSUPPORTED_SIGNATURE_TYPE 155
Definition at line 609 of file rsa.h.
RSA_R_VALUE_MISSING
#define RSA_R_VALUE_MISSING 147
Definition at line 610 of file rsa.h.
RSA_R_WRONG_SIGNATURE_LENGTH
#define RSA_R_WRONG_SIGNATURE_LENGTH 119
Definition at line 611 of file rsa.h.
RSA_set_app_data
#define RSA_set_app_data (s, arg) RSA_set_ex_data(s,0,arg)
Definition at line 182 of file rsa.h.
RSA_SSLV23_PADDING
#define RSA_SSLV23_PADDING 2
Definition at line 173 of file rsa.h.
RSA_X931_PADDING
#define RSA_X931_PADDING 5
Definition at line 176 of file rsa.h.
Function Documentation
DECLARE_ASN1_ENCODE_FUNCTIONS_const()
DECLARE_ASN1_ENCODE_FUNCTIONS_const (RSA , RSAPublicKey)
DEPRECATEDIN_0_9_8()
DEPRECATEDIN_0_9_8 (RSA * RSA_generate_keyint bits, unsigned long e, void(*callback)(int, int, void *), void *cb_arg)
ERR_load_RSA_strings()
int ERR_load_RSA_strings (void)
Definition at line 183 of file rsa_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
PKCS1_MGF1()
int PKCS1_MGF1 (unsigned char * mask, long len, const unsigned char * seed, long seedlen, const EVP_MD * dgst)
Definition at line 247 of file rsa_oaep.c.
RSA_bits()
int RSA_bits (const RSA * rsa)
Definition at line 18 of file rsa_crpt.c.
References BN_num_bits().
RSA_blinding_off()
void RSA_blinding_off (RSA * rsa)
Definition at line 57 of file rsa_crpt.c.
References BN_BLINDING_free(), NULL, RSA_FLAG_BLINDING, and RSA_FLAG_NO_BLINDING.
RSA_blinding_on()
int RSA_blinding_on (RSA * rsa, BN_CTX * ctx)
Definition at line 65 of file rsa_crpt.c.
RSA_check_key()
int RSA_check_key (const RSA *)
Definition at line 14 of file rsa_chk.c.
References NULL, and RSA_check_key_ex().
RSA_check_key_ex()
int RSA_check_key_ex (const RSA * , BN_GENCB * cb)
Definition at line 19 of file rsa_chk.c.
Referenced by RSA_check_key().
RSA_clear_flags()
void RSA_clear_flags (RSA * r, int flags)
Definition at line 295 of file rsa_lib.c.
RSA_flags()
int RSA_flags (const RSA * r)
Definition at line 52 of file rsa_crpt.c.
References NULL.
RSA_free()
void RSA_free (RSA * r)
Definition at line 126 of file rsa_lib.c.
References BN_BLINDING_free(), BN_clear_free(), CRYPTO_DOWN_REF, CRYPTO_EX_INDEX_RSA, CRYPTO_free_ex_data(), CRYPTO_THREAD_lock_free(), ENGINE_finish(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by RSA_generate_key().
RSA_get0_crt_params()
void RSA_get0_crt_params (const RSA * r, const BIGNUM ** dmp1, const BIGNUM ** dmq1, const BIGNUM ** iqmp)
Definition at line 283 of file rsa_lib.c.
References NULL.
RSA_get0_engine()
ENGINE* RSA_get0_engine (const RSA * r)
Definition at line 310 of file rsa_lib.c.
RSA_get0_factors()
void RSA_get0_factors (const RSA * r, const BIGNUM ** p, const BIGNUM ** q)
Definition at line 275 of file rsa_lib.c.
References NULL.
RSA_get0_key()
void RSA_get0_key (const RSA * r, const BIGNUM ** n, const BIGNUM ** e, const BIGNUM ** d)
Definition at line 264 of file rsa_lib.c.
References NULL.
RSA_get_default_method()
const RSA_METHOD* RSA_get_default_method (void)
Definition at line 34 of file rsa_lib.c.
RSA_get_ex_data()
void* RSA_get_ex_data (const RSA * r, int idx)
Definition at line 181 of file rsa_lib.c.
RSA_get_method()
const RSA_METHOD* RSA_get_method (const RSA * rsa)
Definition at line 47 of file rsa_lib.c.
RSA_meth_dup()
RSA_METHOD* RSA_meth_dup (const RSA_METHOD * meth)
Definition at line 40 of file rsa_meth.c.
RSA_meth_free()
void RSA_meth_free (RSA_METHOD * meth)
Definition at line 32 of file rsa_meth.c.
References NULL, and OPENSSL_free.
RSA_meth_get0_app_data()
void* RSA_meth_get0_app_data (const RSA_METHOD * meth)
Definition at line 89 of file rsa_meth.c.
RSA_meth_get0_name()
const char* RSA_meth_get0_name (const RSA_METHOD * meth)
Definition at line 58 of file rsa_meth.c.
RSA_meth_get_flags()
int RSA_meth_get_flags (RSA_METHOD * meth)
Definition at line 78 of file rsa_meth.c.
RSA_meth_new()
RSA_METHOD* RSA_meth_new (const char * name, int flags)
Definition at line 14 of file rsa_meth.c.
References ERR_R_MALLOC_FAILURE, flags, NULL, OPENSSL_free, OPENSSL_strdup, OPENSSL_zalloc, RSA_F_RSA_METH_NEW, and RSAerr.
RSA_meth_set0_app_data()
int RSA_meth_set0_app_data (RSA_METHOD * meth, void * app_data)
Definition at line 94 of file rsa_meth.c.
RSA_meth_set1_name()
int RSA_meth_set1_name (RSA_METHOD * meth, const char * name)
Definition at line 63 of file rsa_meth.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_strdup, RSA_F_RSA_METH_SET1_NAME, and RSAerr.
RSA_meth_set_bn_mod_exp()
int RSA_meth_set_bn_mod_exp (RSA_METHOD * rsa, int(*)(BIGNUM *r, const BIGNUM *a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *m_ctx) bn_mod_exp)
Definition at line 187 of file rsa_meth.c.
RSA_meth_set_finish()
int RSA_meth_set_finish (RSA_METHOD * rsa, int(*)(RSA *rsa) finish)
Definition at line 217 of file rsa_meth.c.
RSA_meth_set_flags()
int RSA_meth_set_flags (RSA_METHOD * meth, int flags)
Definition at line 83 of file rsa_meth.c.
References flags.
RSA_meth_set_init()
int RSA_meth_set_init (RSA_METHOD * rsa, int(*)(RSA *rsa) init)
Definition at line 205 of file rsa_meth.c.
RSA_meth_set_keygen()
int RSA_meth_set_keygen (RSA_METHOD * rsa, int(*)(RSA *rsa, int bits, BIGNUM *e, BN_GENCB *cb) keygen)
Definition at line 266 of file rsa_meth.c.
RSA_meth_set_mod_exp()
int RSA_meth_set_mod_exp (RSA_METHOD * rsa, int(*)(BIGNUM *r0, const BIGNUM *I, RSA *rsa, BN_CTX *ctx) mod_exp)
Definition at line 171 of file rsa_meth.c.
RSA_meth_set_priv_dec()
int RSA_meth_set_priv_dec (RSA_METHOD * rsa, int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) priv_dec)
Definition at line 155 of file rsa_meth.c.
RSA_meth_set_priv_enc()
int RSA_meth_set_priv_enc (RSA_METHOD * rsa, int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) priv_enc)
Definition at line 139 of file rsa_meth.c.
RSA_meth_set_pub_dec()
int RSA_meth_set_pub_dec (RSA_METHOD * rsa, int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) pub_dec)
Definition at line 123 of file rsa_meth.c.
RSA_meth_set_pub_enc()
int RSA_meth_set_pub_enc (RSA_METHOD * rsa, int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) pub_enc)
Definition at line 107 of file rsa_meth.c.
RSA_meth_set_sign()
int RSA_meth_set_sign (RSA_METHOD * rsa, int(*)(int type, const unsigned char *m, unsigned int m_length, unsigned char *sigret, unsigned int *siglen, const RSA *rsa) sign)
Definition at line 232 of file rsa_meth.c.
RSA_meth_set_verify()
int RSA_meth_set_verify (RSA_METHOD * rsa, int(*)(int dtype, const unsigned char *m, unsigned int m_length, const unsigned char *sigbuf, unsigned int siglen, const RSA *rsa) verify)
Definition at line 250 of file rsa_meth.c.
RSA_new()
RSA* RSA_new (void)
Definition at line 22 of file rsa_lib.c.
References NULL, and RSA_new_method().
Referenced by d2i_RSA_PUBKEY_bio(), d2i_RSA_PUBKEY_fp(), main(), and RSA_generate_key().
RSA_new_method()
RSA* RSA_new_method (ENGINE * engine)
Definition at line 72 of file rsa_lib.c.
Referenced by RSA_new().
RSA_null_method()
const RSA_METHOD* RSA_null_method (void)
Definition at line 50 of file rsa_null.c.
RSA_padding_add_none()
int RSA_padding_add_none (unsigned char * to, int tlen, const unsigned char * f, int fl)
Definition at line 14 of file rsa_none.c.
References RSA_F_RSA_PADDING_ADD_NONE, RSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE, RSA_R_DATA_TOO_SMALL_FOR_KEY_SIZE, and RSAerr.
RSA_padding_add_PKCS1_OAEP()
int RSA_padding_add_PKCS1_OAEP (unsigned char * to, int tlen, const unsigned char * f, int fl, const unsigned char * p, int pl)
Definition at line 33 of file rsa_oaep.c.
References NULL, and RSA_padding_add_PKCS1_OAEP_mgf1().
RSA_padding_add_PKCS1_OAEP_mgf1()
int RSA_padding_add_PKCS1_OAEP_mgf1 (unsigned char * to, int tlen, const unsigned char * from, int flen, const unsigned char * param, int plen, const EVP_MD * md, const EVP_MD * mgf1md)
Definition at line 41 of file rsa_oaep.c.
Referenced by RSA_padding_add_PKCS1_OAEP().
RSA_padding_add_PKCS1_PSS()
int RSA_padding_add_PKCS1_PSS (RSA * rsa, unsigned char * EM, const unsigned char * mHash, const EVP_MD * Hash, int sLen)
Definition at line 132 of file rsa_pss.c.
References NULL, and RSA_padding_add_PKCS1_PSS_mgf1().
RSA_padding_add_PKCS1_PSS_mgf1()
int RSA_padding_add_PKCS1_PSS_mgf1 (RSA * rsa, unsigned char * EM, const unsigned char * mHash, const EVP_MD * Hash, const EVP_MD * mgf1Hash, int sLen)
Definition at line 139 of file rsa_pss.c.
Referenced by RSA_padding_add_PKCS1_PSS().
RSA_padding_add_PKCS1_type_1()
int RSA_padding_add_PKCS1_type_1 (unsigned char * to, int tlen, const unsigned char * f, int fl)
Definition at line 18 of file rsa_pk1.c.
References RSA_F_RSA_PADDING_ADD_PKCS1_TYPE_1, RSA_PKCS1_PADDING_SIZE, RSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE, and RSAerr.
RSA_padding_add_PKCS1_type_2()
int RSA_padding_add_PKCS1_type_2 (unsigned char * to, int tlen, const unsigned char * f, int fl)
Definition at line 117 of file rsa_pk1.c.
References RAND_bytes(), RSA_F_RSA_PADDING_ADD_PKCS1_TYPE_2, RSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE, and RSAerr.
RSA_padding_add_SSLv23()
int RSA_padding_add_SSLv23 (unsigned char * to, int tlen, const unsigned char * f, int fl)
Definition at line 16 of file rsa_ssl.c.
References RAND_bytes(), RSA_F_RSA_PADDING_ADD_SSLV23, RSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE, and RSAerr.
RSA_padding_add_X931()
int RSA_padding_add_X931 (unsigned char * to, int tlen, const unsigned char * f, int fl)
Definition at line 16 of file rsa_x931.c.
References RSA_F_RSA_PADDING_ADD_X931, RSA_R_DATA_TOO_LARGE_FOR_KEY_SIZE, and RSAerr.
RSA_padding_check_none()
int RSA_padding_check_none (unsigned char * to, int tlen, const unsigned char * f, int fl, int rsa_len)
Definition at line 31 of file rsa_none.c.
References RSA_F_RSA_PADDING_CHECK_NONE, RSA_R_DATA_TOO_LARGE, and RSAerr.
RSA_padding_check_PKCS1_OAEP()
int RSA_padding_check_PKCS1_OAEP (unsigned char * to, int tlen, const unsigned char * f, int fl, int rsa_len, const unsigned char * p, int pl)
Definition at line 111 of file rsa_oaep.c.
References NULL, and RSA_padding_check_PKCS1_OAEP_mgf1().
RSA_padding_check_PKCS1_OAEP_mgf1()
int RSA_padding_check_PKCS1_OAEP_mgf1 (unsigned char * to, int tlen, const unsigned char * from, int flen, int num, const unsigned char * param, int plen, const EVP_MD * md, const EVP_MD * mgf1md)
Definition at line 119 of file rsa_oaep.c.
Referenced by RSA_padding_check_PKCS1_OAEP().
RSA_padding_check_PKCS1_type_1()
int RSA_padding_check_PKCS1_type_1 (unsigned char * to, int tlen, const unsigned char * f, int fl, int rsa_len)
Definition at line 44 of file rsa_pk1.c.
References RSA_F_RSA_PADDING_CHECK_PKCS1_TYPE_1, RSA_R_BAD_FIXED_HEADER_DECRYPT, RSA_R_BAD_PAD_BYTE_COUNT, RSA_R_BLOCK_TYPE_IS_NOT_01, RSA_R_DATA_TOO_LARGE, RSA_R_INVALID_PADDING, RSA_R_NULL_BEFORE_BLOCK_MISSING, and RSAerr.
RSA_padding_check_PKCS1_type_2()
int RSA_padding_check_PKCS1_type_2 (unsigned char * to, int tlen, const unsigned char * f, int fl, int rsa_len)
Definition at line 154 of file rsa_pk1.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_zalloc, RSA_F_RSA_PADDING_CHECK_PKCS1_TYPE_2, and RSAerr.
RSA_padding_check_SSLv23()
int RSA_padding_check_SSLv23 (unsigned char * to, int tlen, const unsigned char * f, int fl, int rsa_len)
Definition at line 55 of file rsa_ssl.c.
RSA_padding_check_X931()
int RSA_padding_check_X931 (unsigned char * to, int tlen, const unsigned char * f, int fl, int rsa_len)
Definition at line 53 of file rsa_x931.c.
References RSA_F_RSA_PADDING_CHECK_X931, RSA_R_INVALID_HEADER, and RSAerr.
RSA_PKCS1_OpenSSL()
const RSA_METHOD* RSA_PKCS1_OpenSSL (void)
Definition at line 46 of file rsa_ossl.c.
RSA_pkey_ctx_ctrl()
int RSA_pkey_ctx_ctrl (EVP_PKEY_CTX * ctx, int optype, int cmd, int p1, void * p2)
Definition at line 315 of file rsa_lib.c.
References EVP_PKEY_CTX_ctrl(), EVP_PKEY_RSA, EVP_PKEY_RSA_PSS, and NULL.
RSA_print()
int RSA_print (BIO * bp, const RSA * r, int offset)
Definition at line 32 of file rsa_prn.c.
RSA_print_fp()
int RSA_print_fp (FILE * fp, const RSA * r, int offset)
Definition at line 16 of file rsa_prn.c.
RSA_private_decrypt()
int RSA_private_decrypt (int flen, const unsigned char * from, unsigned char * to, RSA * rsa, int padding)
Definition at line 40 of file rsa_crpt.c.
RSA_private_encrypt()
int RSA_private_encrypt (int flen, const unsigned char * from, unsigned char * to, RSA * rsa, int padding)
Definition at line 34 of file rsa_crpt.c.
RSA_public_decrypt()
int RSA_public_decrypt (int flen, const unsigned char * from, unsigned char * to, RSA * rsa, int padding)
Definition at line 46 of file rsa_crpt.c.
RSA_public_encrypt()
int RSA_public_encrypt (int flen, const unsigned char * from, unsigned char * to, RSA * rsa, int padding)
Definition at line 28 of file rsa_crpt.c.
RSA_security_bits()
int RSA_security_bits (const RSA * rsa)
Definition at line 186 of file rsa_lib.c.
References BN_num_bits(), and BN_security_bits().
RSA_set0_crt_params()
int RSA_set0_crt_params (RSA * r, BIGNUM * dmp1, BIGNUM * dmq1, BIGNUM * iqmp)
Definition at line 238 of file rsa_lib.c.
References BN_free(), and NULL.
RSA_set0_factors()
int RSA_set0_factors (RSA * r, BIGNUM * p, BIGNUM * q)
Definition at line 217 of file rsa_lib.c.
References BN_free(), NULL, and q.
RSA_set0_key()
int RSA_set0_key (RSA * r, BIGNUM * n, BIGNUM * e, BIGNUM * d)
Definition at line 191 of file rsa_lib.c.
References BN_free(), e, and NULL.
RSA_set_default_method()
void RSA_set_default_method (const RSA_METHOD * meth)
Definition at line 29 of file rsa_lib.c.
RSA_set_ex_data()
int RSA_set_ex_data (RSA * r, int idx, void * arg)
Definition at line 176 of file rsa_lib.c.
RSA_set_flags()
void RSA_set_flags (RSA * r, int flags)
Definition at line 305 of file rsa_lib.c.
References flags.
RSA_set_method()
int RSA_set_method (RSA * rsa, const RSA_METHOD * meth)
Definition at line 52 of file rsa_lib.c.
References ENGINE_finish(), and NULL.
RSA_setup_blinding()
BN_BLINDING* RSA_setup_blinding (RSA * rsa, BN_CTX * ctx)
Definition at line 111 of file rsa_crpt.c.
References ctx, and e.
RSA_sign()
int RSA_sign (int type, const unsigned char * m, unsigned int m_length, unsigned char * sigret, unsigned int * siglen, RSA * rsa)
Definition at line 69 of file rsa_sign.c.
RSA_sign_ASN1_OCTET_STRING()
int RSA_sign_ASN1_OCTET_STRING (int type, const unsigned char * m, unsigned int m_length, unsigned char * sigret, unsigned int * siglen, RSA * rsa)
Definition at line 17 of file rsa_saos.c.
RSA_size()
int RSA_size (const RSA * rsa)
Definition at line 23 of file rsa_crpt.c.
References BN_num_bytes.
RSA_test_flags()
int RSA_test_flags (const RSA * r, int flags)
Definition at line 300 of file rsa_lib.c.
References flags.
RSA_up_ref()
int RSA_up_ref (RSA * r)
Definition at line 164 of file rsa_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
RSA_verify()
int RSA_verify (int type, const unsigned char * m, unsigned int m_length, const unsigned char * sigbuf, unsigned int siglen, RSA * rsa)
Definition at line 239 of file rsa_sign.c.
References int_rsa_verify(), and NULL.
RSA_verify_ASN1_OCTET_STRING()
int RSA_verify_ASN1_OCTET_STRING (int type, const unsigned char * m, unsigned int m_length, unsigned char * sigbuf, unsigned int siglen, RSA * rsa)
Definition at line 54 of file rsa_saos.c.
RSA_verify_PKCS1_PSS()
int RSA_verify_PKCS1_PSS (RSA * rsa, const unsigned char * mHash, const EVP_MD * Hash, const unsigned char * EM, int sLen)
Definition at line 25 of file rsa_pss.c.
References NULL, and RSA_verify_PKCS1_PSS_mgf1().
RSA_verify_PKCS1_PSS_mgf1()
int RSA_verify_PKCS1_PSS_mgf1 (RSA * rsa, const unsigned char * mHash, const EVP_MD * Hash, const EVP_MD * mgf1Hash, const unsigned char * EM, int sLen)
Definition at line 32 of file rsa_pss.c.
Referenced by RSA_verify_PKCS1_PSS().
RSA_X931_derive_ex()
int RSA_X931_derive_ex (RSA * rsa, BIGNUM * p1, BIGNUM * p2, BIGNUM * q1, BIGNUM * q2, const BIGNUM * Xp1, const BIGNUM * Xp2, const BIGNUM * Xp, const BIGNUM * Xq1, const BIGNUM * Xq2, const BIGNUM * Xq, const BIGNUM * e, BN_GENCB * cb)
Definition at line 19 of file rsa_x931g.c.
References ctx, and NULL.
Referenced by RSA_X931_generate_key_ex().
RSA_X931_generate_key_ex()
int RSA_X931_generate_key_ex (RSA * rsa, int bits, const BIGNUM * e, BN_GENCB * cb)
Definition at line 142 of file rsa_x931g.c.
References BN_CTX_end(), BN_CTX_free(), BN_CTX_get(), BN_CTX_new(), BN_CTX_start(), BN_new(), BN_X931_generate_prime_ex(), BN_X931_generate_Xpq(), ctx, NULL, and RSA_X931_derive_ex().
RSA_X931_hash_id()
int RSA_X931_hash_id (int nid)
Definition at line 99 of file rsa_x931.c.
References NID_sha1, NID_sha256, NID_sha384, and NID_sha512.
RSAPrivateKey_dup()
RSA* RSAPrivateKey_dup (RSA * rsa)
RSAPublicKey_dup()
RSA* RSAPublicKey_dup (RSA * rsa)
Variable Documentation
bits
int bits
Definition at line 211 of file rsa.h.
cb
int BIGNUM BN_GENCB* cb
Definition at line 211 of file rsa.h.
e
int BIGNUM* e
Definition at line 211 of file rsa.h.
Referenced by DTLS_RECORD_LAYER_set_saved_w_epoch(), ENGINE_register_all_ciphers(), ENGINE_register_all_complete(), ENGINE_register_all_DH(), ENGINE_register_all_digests(), ENGINE_register_all_DSA(), ENGINE_register_all_EC(), ENGINE_register_all_pkey_asn1_meths(), ENGINE_register_all_pkey_meths(), ENGINE_register_all_RAND(), ENGINE_register_all_RSA(), EVP_PKEY_asn1_find_str(), OPENSSL_cpuid_setup(), RSA_generate_key(), RSA_set0_key(), RSA_setup_blinding(), SSL_CTX_set_client_cert_engine(), TS_CONF_set_default_engine(), and X25519_public_from_private().
RSA_meth_get_bn_mod_exp
int(*)(BIGNUM *r, const BIGNUM *a, const BIGNUM *p, const BIGNUM *m, BN_CTX *ctx, BN_MONT_CTX *m_ctx) RSA_meth_get_bn_mod_exp(const RSA_METHOD *meth)
Definition at line 433 of file rsa.h.
RSA_meth_get_finish
int(*)(RSA *rsa) RSA_meth_get_finish(const RSA_METHOD *meth)
Definition at line 445 of file rsa.h.
RSA_meth_get_init
int(*)(RSA *rsa) RSA_meth_get_init(const RSA_METHOD *meth)
Definition at line 443 of file rsa.h.
RSA_meth_get_keygen
int(*)(RSA *rsa, int bits, BIGNUM *e, BN_GENCB *cb) RSA_meth_get_keygen(const RSA_METHOD *meth)
Definition at line 466 of file rsa.h.
RSA_meth_get_mod_exp
int(*)(BIGNUM *r0, const BIGNUM *I, RSA *rsa, BN_CTX *ctx) RSA_meth_get_mod_exp(const RSA_METHOD *meth)
Definition at line 428 of file rsa.h.
RSA_meth_get_priv_dec
int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) RSA_meth_get_priv_dec(const RSA_METHOD *meth)
Definition at line 421 of file rsa.h.
RSA_meth_get_priv_enc
int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) RSA_meth_get_priv_enc(const RSA_METHOD *meth)
Definition at line 414 of file rsa.h.
RSA_meth_get_pub_dec
int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) RSA_meth_get_pub_dec(const RSA_METHOD *meth)
Definition at line 407 of file rsa.h.
RSA_meth_get_pub_enc
int(*)(int flen, const unsigned char *from, unsigned char *to, RSA *rsa, int padding) RSA_meth_get_pub_enc(const RSA_METHOD *meth)
Definition at line 400 of file rsa.h.
RSA_meth_get_sign
int(*)(int type, const unsigned char *m, unsigned int m_length, unsigned char *sigret, unsigned int *siglen, const RSA *rsa) RSA_meth_get_sign(const RSA_METHOD *meth)
Definition at line 447 of file rsa.h.
RSA_meth_get_verify
int(*)(int dtype, const unsigned char *m, unsigned int m_length, const unsigned char *sigbuf, unsigned int siglen, const RSA *rsa) RSA_meth_get_verify(const RSA_METHOD *meth)
Definition at line 457 of file rsa.h.