crypto/rsa/rsa_lib.c File Reference
rsa_lib.c File Reference
#include <stdio.h>
#include <openssl/crypto.h>
#include "internal/cryptlib.h"
#include <openssl/lhash.h>
#include "internal/bn_int.h"
#include <openssl/engine.h>
#include <openssl/evp.h>
#include "internal/evp_int.h"
#include "rsa_locl.h"
Functions
RSA * RSA_new (void)
void RSA_set_default_method (const RSA_METHOD *meth)
const RSA_METHOD * RSA_get_default_method (void)
const RSA_METHOD * RSA_get_method (const RSA *rsa)
int RSA_set_method (RSA *rsa, const RSA_METHOD *meth)
RSA * RSA_new_method (ENGINE *engine)
void RSA_free (RSA *r)
int RSA_up_ref (RSA *r)
int RSA_set_ex_data (RSA *r, int idx, void *arg)
void * RSA_get_ex_data (const RSA *r, int idx)
int RSA_security_bits (const RSA *rsa)
int RSA_set0_key (RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d)
int RSA_set0_factors (RSA *r, BIGNUM *p, BIGNUM *q)
int RSA_set0_crt_params (RSA *r, BIGNUM *dmp1, BIGNUM *dmq1, BIGNUM *iqmp)
void RSA_get0_key (const RSA *r, const BIGNUM **n, const BIGNUM **e, const BIGNUM **d)
void RSA_get0_factors (const RSA *r, const BIGNUM **p, const BIGNUM **q)
void RSA_get0_crt_params (const RSA *r, const BIGNUM **dmp1, const BIGNUM **dmq1, const BIGNUM **iqmp)
void RSA_clear_flags (RSA *r, int flags)
int RSA_test_flags (const RSA *r, int flags)
void RSA_set_flags (RSA *r, int flags)
ENGINE * RSA_get0_engine (const RSA *r)
int RSA_pkey_ctx_ctrl (EVP_PKEY_CTX *ctx, int optype, int cmd, int p1, void *p2)
Function Documentation
RSA_clear_flags()
void RSA_clear_flags (RSA * r, int flags)
Definition at line 295 of file rsa_lib.c.
RSA_free()
void RSA_free (RSA * r)
Definition at line 126 of file rsa_lib.c.
References BN_BLINDING_free(), BN_clear_free(), CRYPTO_DOWN_REF, CRYPTO_EX_INDEX_RSA, CRYPTO_free_ex_data(), CRYPTO_THREAD_lock_free(), ENGINE_finish(), NULL, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by RSA_generate_key().
RSA_get0_crt_params()
void RSA_get0_crt_params (const RSA * r, const BIGNUM ** dmp1, const BIGNUM ** dmq1, const BIGNUM ** iqmp)
Definition at line 283 of file rsa_lib.c.
References NULL.
RSA_get0_engine()
ENGINE* RSA_get0_engine (const RSA * r)
Definition at line 310 of file rsa_lib.c.
RSA_get0_factors()
void RSA_get0_factors (const RSA * r, const BIGNUM ** p, const BIGNUM ** q)
Definition at line 275 of file rsa_lib.c.
References NULL.
RSA_get0_key()
void RSA_get0_key (const RSA * r, const BIGNUM ** n, const BIGNUM ** e, const BIGNUM ** d)
Definition at line 264 of file rsa_lib.c.
References NULL.
RSA_get_default_method()
const RSA_METHOD* RSA_get_default_method (void)
Definition at line 34 of file rsa_lib.c.
RSA_get_ex_data()
void* RSA_get_ex_data (const RSA * r, int idx)
Definition at line 181 of file rsa_lib.c.
RSA_get_method()
const RSA_METHOD* RSA_get_method (const RSA * rsa)
Definition at line 47 of file rsa_lib.c.
RSA_new()
RSA* RSA_new (void)
Definition at line 22 of file rsa_lib.c.
References NULL, and RSA_new_method().
Referenced by d2i_RSA_PUBKEY_bio(), d2i_RSA_PUBKEY_fp(), main(), and RSA_generate_key().
RSA_new_method()
RSA* RSA_new_method (ENGINE * engine)
Definition at line 72 of file rsa_lib.c.
Referenced by RSA_new().
RSA_pkey_ctx_ctrl()
int RSA_pkey_ctx_ctrl (EVP_PKEY_CTX * ctx, int optype, int cmd, int p1, void * p2)
Definition at line 315 of file rsa_lib.c.
References EVP_PKEY_CTX_ctrl(), EVP_PKEY_RSA, EVP_PKEY_RSA_PSS, and NULL.
RSA_security_bits()
int RSA_security_bits (const RSA * rsa)
Definition at line 186 of file rsa_lib.c.
References BN_num_bits(), and BN_security_bits().
RSA_set0_crt_params()
int RSA_set0_crt_params (RSA * r, BIGNUM * dmp1, BIGNUM * dmq1, BIGNUM * iqmp)
Definition at line 238 of file rsa_lib.c.
References BN_free(), and NULL.
RSA_set0_factors()
int RSA_set0_factors (RSA * r, BIGNUM * p, BIGNUM * q)
Definition at line 217 of file rsa_lib.c.
References BN_free(), NULL, and q.
RSA_set0_key()
int RSA_set0_key (RSA * r, BIGNUM * n, BIGNUM * e, BIGNUM * d)
Definition at line 191 of file rsa_lib.c.
References BN_free(), e, and NULL.
RSA_set_default_method()
void RSA_set_default_method (const RSA_METHOD * meth)
Definition at line 29 of file rsa_lib.c.
RSA_set_ex_data()
int RSA_set_ex_data (RSA * r, int idx, void * arg)
Definition at line 176 of file rsa_lib.c.
RSA_set_flags()
void RSA_set_flags (RSA * r, int flags)
Definition at line 305 of file rsa_lib.c.
References flags.
RSA_set_method()
int RSA_set_method (RSA * rsa, const RSA_METHOD * meth)
Definition at line 52 of file rsa_lib.c.
References ENGINE_finish(), and NULL.
RSA_test_flags()
int RSA_test_flags (const RSA * r, int flags)
Definition at line 300 of file rsa_lib.c.
References flags.
RSA_up_ref()
int RSA_up_ref (RSA * r)
Definition at line 164 of file rsa_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.