crypto/rsa/rsa_depr.c File Reference
rsa_depr.c File Reference
#include <openssl/opensslconf.h>
#include <stdio.h>
#include <time.h>
#include "internal/cryptlib.h"
#include <openssl/bn.h>
#include <openssl/rsa.h>
Functions
RSA * RSA_generate_key (int bits, unsigned long e_value, void(*callback)(int, int, void *), void *cb_arg)
Function Documentation
RSA_generate_key()
RSA* RSA_generate_key (int bits, unsigned long e_value, void(*)(int, int, void *) callback, void * cb_arg)
Definition at line 27 of file rsa_depr.c.
References BN_free(), BN_GENCB_free(), BN_GENCB_new(), BN_GENCB_set_old(), BN_new(), BN_set_bit(), callback, cb, e, NULL, RSA_free(), RSA_generate_key_ex(), and RSA_new().