crypto/rsa/rsa_oaep.c File Reference
rsa_oaep.c File Reference
#include "internal/constant_time_locl.h"
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/bn.h>
#include <openssl/evp.h>
#include <openssl/rand.h>
#include <openssl/sha.h>
#include "rsa_locl.h"
Functions
int RSA_padding_add_PKCS1_OAEP (unsigned char *to, int tlen, const unsigned char *from, int flen, const unsigned char *param, int plen)
int RSA_padding_add_PKCS1_OAEP_mgf1 (unsigned char *to, int tlen, const unsigned char *from, int flen, const unsigned char *param, int plen, const EVP_MD *md, const EVP_MD *mgf1md)
int RSA_padding_check_PKCS1_OAEP (unsigned char *to, int tlen, const unsigned char *from, int flen, int num, const unsigned char *param, int plen)
int RSA_padding_check_PKCS1_OAEP_mgf1 (unsigned char *to, int tlen, const unsigned char *from, int flen, int num, const unsigned char *param, int plen, const EVP_MD *md, const EVP_MD *mgf1md)
int PKCS1_MGF1 (unsigned char *mask, long len, const unsigned char *seed, long seedlen, const EVP_MD *dgst)
Function Documentation
PKCS1_MGF1()
int PKCS1_MGF1 (unsigned char * mask, long len, const unsigned char * seed, long seedlen, const EVP_MD * dgst)
Definition at line 247 of file rsa_oaep.c.
RSA_padding_add_PKCS1_OAEP()
int RSA_padding_add_PKCS1_OAEP (unsigned char * to, int tlen, const unsigned char * from, int flen, const unsigned char * param, int plen)
Definition at line 33 of file rsa_oaep.c.
References NULL, and RSA_padding_add_PKCS1_OAEP_mgf1().
RSA_padding_add_PKCS1_OAEP_mgf1()
int RSA_padding_add_PKCS1_OAEP_mgf1 (unsigned char * to, int tlen, const unsigned char * from, int flen, const unsigned char * param, int plen, const EVP_MD * md, const EVP_MD * mgf1md)
Definition at line 41 of file rsa_oaep.c.
Referenced by RSA_padding_add_PKCS1_OAEP().
RSA_padding_check_PKCS1_OAEP()
int RSA_padding_check_PKCS1_OAEP (unsigned char * to, int tlen, const unsigned char * from, int flen, int num, const unsigned char * param, int plen)
Definition at line 111 of file rsa_oaep.c.
References NULL, and RSA_padding_check_PKCS1_OAEP_mgf1().
RSA_padding_check_PKCS1_OAEP_mgf1()
int RSA_padding_check_PKCS1_OAEP_mgf1 (unsigned char * to, int tlen, const unsigned char * from, int flen, int num, const unsigned char * param, int plen, const EVP_MD * md, const EVP_MD * mgf1md)
Definition at line 119 of file rsa_oaep.c.
Referenced by RSA_padding_check_PKCS1_OAEP().