crypto/rsa/rsa_x931g.c File Reference
rsa_x931g.c File Reference
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <openssl/err.h>
#include <openssl/bn.h>
#include "rsa_locl.h"
Functions
int RSA_X931_derive_ex (RSA *rsa, BIGNUM *p1, BIGNUM *p2, BIGNUM *q1, BIGNUM *q2, const BIGNUM *Xp1, const BIGNUM *Xp2, const BIGNUM *Xp, const BIGNUM *Xq1, const BIGNUM *Xq2, const BIGNUM *Xq, const BIGNUM *e, BN_GENCB *cb)
int RSA_X931_generate_key_ex (RSA *rsa, int bits, const BIGNUM *e, BN_GENCB *cb)
Function Documentation
RSA_X931_derive_ex()
int RSA_X931_derive_ex (RSA * rsa, BIGNUM * p1, BIGNUM * p2, BIGNUM * q1, BIGNUM * q2, const BIGNUM * Xp1, const BIGNUM * Xp2, const BIGNUM * Xp, const BIGNUM * Xq1, const BIGNUM * Xq2, const BIGNUM * Xq, const BIGNUM * e, BN_GENCB * cb)
Definition at line 19 of file rsa_x931g.c.
References ctx, and NULL.
Referenced by RSA_X931_generate_key_ex().
RSA_X931_generate_key_ex()
int RSA_X931_generate_key_ex (RSA * rsa, int bits, const BIGNUM * e, BN_GENCB * cb)
Definition at line 142 of file rsa_x931g.c.
References BN_CTX_end(), BN_CTX_free(), BN_CTX_get(), BN_CTX_new(), BN_CTX_start(), BN_new(), BN_X931_generate_prime_ex(), BN_X931_generate_Xpq(), ctx, NULL, and RSA_X931_derive_ex().