test/rsa_test.c File Reference
rsa_test.c File Reference
#include <stdio.h>
#include <string.h>
#include "e_os.h"
#include <openssl/crypto.h>
#include <openssl/err.h>
#include <openssl/rand.h>
#include <openssl/bn.h>
#include <openssl/rsa.h>
Macros
#define SetKey
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
SetKey
#define SetKey
Value:
RSA_set0_key(key,                                           \
                 BN_bin2bn(n, sizeof(n)-1, NULL),               \
                 BN_bin2bn(e, sizeof(e)-1, NULL),               \
                 BN_bin2bn(d, sizeof(d)-1, NULL));              \
    RSA_set0_factors(key,                                       \
                     BN_bin2bn(p, sizeof(p)-1, NULL),           \
                     BN_bin2bn(q, sizeof(q)-1, NULL));          \
    RSA_set0_crt_params(key,                                    \
                        BN_bin2bn(dmp1, sizeof(dmp1)-1, NULL),  \
                        BN_bin2bn(dmq1, sizeof(dmq1)-1, NULL),  \
                        BN_bin2bn(iqmp, sizeof(iqmp)-1, NULL)); \
    memcpy(c, ctext_ex, sizeof(ctext_ex) - 1);                  \
    return (sizeof(ctext_ex) - 1);
Definition at line 30 of file rsa_test.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 223 of file rsa_test.c.
References CRYPTO_MEM_CHECK_ON, CRYPTO_mem_ctrl(), CRYPTO_set_mem_debug(), key, RAND_seed(), and RSA_new().