ssl/s3_msg.c File Reference
s3_msg.c File Reference
#include "ssl_locl.h"
Macros
#define USE_SOCKETS
Functions
int ssl3_do_change_cipher_spec (SSL *s)
int ssl3_send_alert (SSL *s, int level, int desc)
int ssl3_dispatch_alert (SSL *s)
Macro Definition Documentation
USE_SOCKETS
#define USE_SOCKETS
Definition at line 10 of file s3_msg.c.
Function Documentation
ssl3_dispatch_alert()
int ssl3_dispatch_alert (SSL * s)
Definition at line 90 of file s3_msg.c.
References BIO_flush, cb, do_ssl3_write(), NULL, SSL3_AL_FATAL, SSL3_RT_ALERT, SSL_CB_WRITE_ALERT, and type.
ssl3_do_change_cipher_spec()
int ssl3_do_change_cipher_spec (SSL * s)
Definition at line 13 of file s3_msg.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL3_CHANGE_CIPHER_CLIENT_READ, SSL3_CHANGE_CIPHER_SERVER_READ, SSL_F_SSL3_DO_CHANGE_CIPHER_SPEC, SSL_R_CCS_RECEIVED_EARLY, and SSLerr.
ssl3_send_alert()
int ssl3_send_alert (SSL * s, int level, int desc)
Definition at line 63 of file s3_msg.c.
References NULL, RECORD_LAYER_write_pending(), SSL3_AL_FATAL, SSL3_VERSION, SSL_AD_HANDSHAKE_FAILURE, SSL_AD_PROTOCOL_VERSION, and SSL_CTX_remove_session().
Referenced by dtls_construct_change_cipher_spec(), ossl_statem_server_read_transition(), tls1_set_server_sigalgs(), tls_client_key_exchange_post_work(), tls_construct_cert_status(), tls_construct_change_cipher_spec(), tls_construct_client_certificate(), tls_construct_finished(), tls_construct_key_update(), tls_construct_next_proto(), tls_construct_server_certificate(), tls_construct_server_done(), tls_construct_server_hello(), tls_get_message_header(), tls_prepare_client_certificate(), tls_process_cert_status(), and tls_setup_handshake().