ssl/s3_lib.c File Reference
s3_lib.c File Reference
#include <stdio.h>
#include <openssl/objects.h>
#include "ssl_locl.h"
#include <openssl/md5.h>
#include <openssl/dh.h>
#include <openssl/rand.h>
Macros
#define SSL3_NUM_CIPHERS OSSL_NELEM(ssl3_ciphers)
Functions
void ssl_sort_cipher_list (void)
long ssl3_default_timeout (void)
int ssl3_num_ciphers (void)
const SSL_CIPHER * ssl3_get_cipher (unsigned int u)
int ssl3_set_handshake_header (SSL *s, WPACKET *pkt, int htype)
int ssl3_handshake_write (SSL *s)
int ssl3_new (SSL *s)
void ssl3_free (SSL *s)
void ssl3_clear (SSL *s)
long ssl3_ctrl (SSL *s, int cmd, long larg, void *parg)
long ssl3_callback_ctrl (SSL *s, int cmd, void(*fp)(void))
long ssl3_ctx_ctrl (SSL_CTX *ctx, int cmd, long larg, void *parg)
long ssl3_ctx_callback_ctrl (SSL_CTX *ctx, int cmd, void(*fp)(void))
const SSL_CIPHER * ssl3_get_cipher_by_id (uint32_t id)
const SSL_CIPHER * ssl3_get_cipher_by_char (const unsigned char *p)
int ssl3_put_cipher_by_char (const SSL_CIPHER *c, WPACKET *pkt, size_t *len)
const SSL_CIPHER * ssl3_choose_cipher (SSL *s, STACK_OF(SSL_CIPHER) *clnt, STACK_OF(SSL_CIPHER) *srvr)
int ssl3_get_req_cert_type (SSL *s, WPACKET *pkt)
int ssl3_shutdown (SSL *s)
int ssl3_write (SSL *s, const void *buf, size_t len, size_t *written)
int ssl3_read (SSL *s, void *buf, size_t len, size_t *readbytes)
int ssl3_peek (SSL *s, void *buf, size_t len, size_t *readbytes)
int ssl3_renegotiate (SSL *s)
int ssl3_renegotiate_check (SSL *s, int initok)
long ssl_get_algorithm2 (SSL *s)
int ssl_fill_hello_random (SSL *s, int server, unsigned char *result, size_t len)
int ssl_generate_master_secret (SSL *s, unsigned char *pms, size_t pmslen, int free_pms)
EVP_PKEY * ssl_generate_pkey (EVP_PKEY *pm)
EVP_PKEY * ssl_generate_pkey_curve (int id)
int ssl_derive (SSL *s, EVP_PKEY *privkey, EVP_PKEY *pubkey, int gensecret)
EVP_PKEY * ssl_dh_to_pkey (DH *dh)
Variables
const SSL3_ENC_METHOD SSLv3_enc_data
Macro Definition Documentation
SSL3_NUM_CIPHERS
#define SSL3_NUM_CIPHERS OSSL_NELEM(ssl3_ciphers)
Definition at line 57 of file s3_lib.c.
Referenced by ssl3_get_cipher(), and ssl3_num_ciphers().
Function Documentation
ssl3_callback_ctrl()
long ssl3_callback_ctrl (SSL * s, int cmd, void(*)(void) fp)
Definition at line 3276 of file s3_lib.c.
ssl3_choose_cipher()
const SSL_CIPHER* ssl3_choose_cipher (SSL * s, STACK_OF(SSL_CIPHER) * clnt, STACK_OF(SSL_CIPHER) * srvr)
Definition at line 3639 of file s3_lib.c.
ssl3_clear()
void ssl3_clear (SSL * s)
Definition at line 2921 of file s3_lib.c.
References EVP_PKEY_free(), NULL, OPENSSL_clear_free, OPENSSL_free, ssl3_cleanup_key_block(), ssl3_free_digest_list(), SSL3_VERSION, and ssl_free_wbio_buffer().
Referenced by tls1_clear().
ssl3_ctrl()
long ssl3_ctrl (SSL * s, int cmd, long larg, void * parg)
Definition at line 2962 of file s3_lib.c.
ssl3_ctx_callback_ctrl()
long ssl3_ctx_callback_ctrl (SSL_CTX * ctx, int cmd, void(*)(void) fp)
Definition at line 3546 of file s3_lib.c.
References fp, SSL_CTRL_SET_NOT_RESUMABLE_SESS_CB, SSL_CTRL_SET_SRP_GIVE_CLIENT_PWD_CB, SSL_CTRL_SET_SRP_VERIFY_PARAM_CB, SSL_CTRL_SET_TLS_EXT_SRP_USERNAME_CB, SSL_CTRL_SET_TLSEXT_SERVERNAME_CB, SSL_CTRL_SET_TLSEXT_STATUS_REQ_CB, SSL_CTRL_SET_TLSEXT_TICKET_KEY_CB, SSL_CTRL_SET_TMP_DH_CB, and SSL_kSRP.
ssl3_ctx_ctrl()
long ssl3_ctx_ctrl (SSL_CTX * ctx, int cmd, long larg, void * parg)
Definition at line 3304 of file s3_lib.c.
References EC_GROUP_get_curve_name(), EC_KEY_get0_group(), EC_R_MISSING_PARAMETERS, ERR_R_MALLOC_FAILURE, ERR_R_PASSED_NULL_PARAMETER, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, EVP_PKEY_free(), EVP_PKEY_security_bits(), nid, NID_undef, NULL, SSL_CTRL_GET_TLSEXT_TICKET_KEYS, SSL_CTRL_SET_DH_AUTO, SSL_CTRL_SET_TLSEXT_SERVERNAME_ARG, SSL_CTRL_SET_TLSEXT_TICKET_KEYS, SSL_CTRL_SET_TMP_DH, SSL_CTRL_SET_TMP_DH_CB, SSL_CTRL_SET_TMP_ECDH, ssl_ctx_security(), ssl_dh_to_pkey(), SSL_F_SSL3_CTX_CTRL, SSL_R_DH_KEY_TOO_SMALL, SSL_SECOP_TMP_DH, SSLerr, and tls1_set_groups().
ssl3_default_timeout()
long ssl3_default_timeout (void)
Definition at line 2833 of file s3_lib.c.
ssl3_free()
void ssl3_free (SSL * s)
Definition at line 2892 of file s3_lib.c.
References EVP_PKEY_free(), NULL, OPENSSL_clear_free, OPENSSL_free, ssl3_cleanup_key_block(), ssl3_free_digest_list(), and SSL_SRP_CTX_free().
Referenced by dtls1_free(), dtls1_new(), and tls1_free().
ssl3_get_cipher()
const SSL_CIPHER* ssl3_get_cipher (unsigned int u)
Definition at line 2847 of file s3_lib.c.
References SSL3_NUM_CIPHERS.
Referenced by main().
ssl3_get_cipher_by_char()
const SSL_CIPHER* ssl3_get_cipher_by_char (const unsigned char * p)
Definition at line 3610 of file s3_lib.c.
References SSL3_CK_CIPHERSUITE_FLAG, and ssl3_get_cipher_by_id().
ssl3_get_cipher_by_id()
const SSL_CIPHER* ssl3_get_cipher_by_id (uint32_t id)
Definition at line 3598 of file s3_lib.c.
Referenced by ssl3_get_cipher_by_char().
ssl3_get_req_cert_type()
int ssl3_get_req_cert_type (SSL * s, WPACKET * pkt)
Definition at line 3759 of file s3_lib.c.
References SSL3_CT_DSS_EPHEMERAL_DH, SSL3_CT_DSS_SIGN, SSL3_CT_RSA_EPHEMERAL_DH, SSL3_CT_RSA_SIGN, SSL3_VERSION, SSL_aDSS, SSL_aECDSA, SSL_aRSA, SSL_kDHE, SSL_kGOST, SSL_SECOP_SIGALG_MASK, ssl_set_sig_mask(), TLS1_VERSION, TLS_CT_ECDSA_SIGN, TLS_CT_GOST01_SIGN, TLS_CT_GOST12_512_SIGN, TLS_CT_GOST12_SIGN, WPACKET_memcpy(), and WPACKET_put_bytes_u8.
ssl3_handshake_write()
int ssl3_handshake_write (SSL * s)
Definition at line 2869 of file s3_lib.c.
References ssl3_do_write(), and SSL3_RT_HANDSHAKE.
ssl3_new()
int ssl3_new (SSL * s)
Definition at line 2874 of file s3_lib.c.
References NULL, OPENSSL_zalloc, and SSL_SRP_CTX_init().
Referenced by dtls1_new(), and tls1_new().
ssl3_num_ciphers()
int ssl3_num_ciphers (void)
Definition at line 2842 of file s3_lib.c.
References SSL3_NUM_CIPHERS.
Referenced by main().
ssl3_peek()
int ssl3_peek (SSL * s, void * buf, size_t len, size_t * readbytes)
Definition at line 3925 of file s3_lib.c.
ssl3_put_cipher_by_char()
int ssl3_put_cipher_by_char (const SSL_CIPHER * c, WPACKET * pkt, size_t * len)
Definition at line 3617 of file s3_lib.c.
References SSL3_CK_CIPHERSUITE_FLAG, and WPACKET_put_bytes_u16.
ssl3_read()
int ssl3_read (SSL * s, void * buf, size_t len, size_t * readbytes)
Definition at line 3920 of file s3_lib.c.
ssl3_renegotiate()
int ssl3_renegotiate (SSL * s)
Definition at line 3930 of file s3_lib.c.
References NULL.
ssl3_renegotiate_check()
int ssl3_renegotiate_check (SSL * s, int initok)
Definition at line 3947 of file s3_lib.c.
ssl3_set_handshake_header()
int ssl3_set_handshake_header (SSL * s, WPACKET * pkt, int htype)
Definition at line 2855 of file s3_lib.c.
References SSL3_MT_CHANGE_CIPHER_SPEC, WPACKET_put_bytes_u8, and WPACKET_start_sub_packet_u24.
ssl3_shutdown()
int ssl3_shutdown (SSL * s)
Definition at line 3828 of file s3_lib.c.
ssl3_write()
int ssl3_write (SSL * s, const void * buf, size_t len, size_t * written)
Definition at line 3879 of file s3_lib.c.
ssl_derive()
int ssl_derive (SSL * s, EVP_PKEY * privkey, EVP_PKEY * pubkey, int gensecret)
Definition at line 4136 of file s3_lib.c.
Referenced by tls_construct_stoc_key_share().
ssl_dh_to_pkey()
EVP_PKEY* ssl_dh_to_pkey (DH * dh)
Definition at line 4193 of file s3_lib.c.
Referenced by ssl3_ctx_ctrl().
ssl_fill_hello_random()
int ssl_fill_hello_random (SSL * s, int server, unsigned char * result, size_t len)
Definition at line 3996 of file s3_lib.c.
References l2n, NULL, RAND_bytes(), SSL_MODE_SEND_CLIENTHELLO_TIME, and SSL_MODE_SEND_SERVERHELLO_TIME.
ssl_generate_master_secret()
int ssl_generate_master_secret (SSL * s, unsigned char * pms, size_t pmslen, int free_pms)
Definition at line 4016 of file s3_lib.c.
Referenced by tls_client_key_exchange_post_work().
ssl_generate_pkey()
EVP_PKEY* ssl_generate_pkey (EVP_PKEY * pm)
Definition at line 4080 of file s3_lib.c.
Referenced by tls_construct_stoc_key_share().
ssl_generate_pkey_curve()
EVP_PKEY* ssl_generate_pkey_curve (int id)
Definition at line 4103 of file s3_lib.c.
ssl_get_algorithm2()
long ssl_get_algorithm2 (SSL * s)
Definition at line 3976 of file s3_lib.c.
References NULL, SSL_ENC_FLAG_SHA256_PRF, SSL_HANDSHAKE_MAC_DEFAULT, SSL_HANDSHAKE_MAC_SHA256, SSL_HANDSHAKE_MAC_SHA384, SSL_PSK, TLS1_PRF, TLS1_PRF_SHA256, and TLS1_PRF_SHA384.
Referenced by ssl_handshake_md(), and ssl_prf_md().
ssl_sort_cipher_list()
void ssl_sort_cipher_list (void)
Definition at line 2808 of file s3_lib.c.
Variable Documentation
SSLv3_enc_data
const SSL3_ENC_METHOD SSLv3_enc_data
Initial value:
= {
    ssl3_enc,
    n_ssl3_mac,
    ssl3_setup_key_block,
    ssl3_generate_master_secret,
    ssl3_change_cipher_state,
    ssl3_final_finish_mac,
    SSL3_MD_CLIENT_FINISHED_CONST, 4,
    SSL3_MD_SERVER_FINISHED_CONST, 4,
    ssl3_alert_code,
    (int (*)(SSL *, unsigned char *, size_t, const char *,
             size_t, const unsigned char *, size_t,
             int use_context))ssl_undefined_function,
    0,
    ssl3_set_handshake_header,
    tls_close_construct_packet,
    ssl3_handshake_write
}
Definition at line 2814 of file s3_lib.c.