ssl/s3_enc.c File Reference
s3_enc.c File Reference
#include <stdio.h>
#include "ssl_locl.h"
#include <openssl/evp.h>
#include <openssl/md5.h>
Functions
int ssl3_change_cipher_state (SSL *s, int which)
int ssl3_setup_key_block (SSL *s)
void ssl3_cleanup_key_block (SSL *s)
int ssl3_init_finished_mac (SSL *s)
void ssl3_free_digest_list (SSL *s)
int ssl3_finish_mac (SSL *s, const unsigned char *buf, size_t len)
int ssl3_digest_cached_records (SSL *s, int keep)
size_t ssl3_final_finish_mac (SSL *s, const char *sender, size_t len, unsigned char *p)
int ssl3_generate_master_secret (SSL *s, unsigned char *out, unsigned char *p, size_t len, size_t *secret_size)
int ssl3_alert_code (int code)
Function Documentation
ssl3_alert_code()
int ssl3_alert_code (int code)
Definition at line 527 of file s3_enc.c.
References SSL3_AD_BAD_CERTIFICATE, SSL3_AD_BAD_RECORD_MAC, SSL3_AD_CERTIFICATE_EXPIRED, SSL3_AD_CERTIFICATE_REVOKED, SSL3_AD_CERTIFICATE_UNKNOWN, SSL3_AD_CLOSE_NOTIFY, SSL3_AD_DECOMPRESSION_FAILURE, SSL3_AD_HANDSHAKE_FAILURE, SSL3_AD_ILLEGAL_PARAMETER, SSL3_AD_NO_CERTIFICATE, SSL3_AD_UNEXPECTED_MESSAGE, SSL3_AD_UNSUPPORTED_CERTIFICATE, SSL_AD_ACCESS_DENIED, SSL_AD_BAD_CERTIFICATE, SSL_AD_BAD_CERTIFICATE_HASH_VALUE, SSL_AD_BAD_CERTIFICATE_STATUS_RESPONSE, SSL_AD_BAD_RECORD_MAC, SSL_AD_CERTIFICATE_EXPIRED, SSL_AD_CERTIFICATE_REVOKED, SSL_AD_CERTIFICATE_UNKNOWN, SSL_AD_CERTIFICATE_UNOBTAINABLE, SSL_AD_CLOSE_NOTIFY, SSL_AD_DECODE_ERROR, SSL_AD_DECOMPRESSION_FAILURE, SSL_AD_DECRYPT_ERROR, SSL_AD_DECRYPTION_FAILED, SSL_AD_EXPORT_RESTRICTION, SSL_AD_HANDSHAKE_FAILURE, SSL_AD_ILLEGAL_PARAMETER, SSL_AD_INAPPROPRIATE_FALLBACK, SSL_AD_INSUFFICIENT_SECURITY, SSL_AD_INTERNAL_ERROR, SSL_AD_NO_APPLICATION_PROTOCOL, SSL_AD_NO_CERTIFICATE, SSL_AD_NO_RENEGOTIATION, SSL_AD_PROTOCOL_VERSION, SSL_AD_RECORD_OVERFLOW, SSL_AD_UNEXPECTED_MESSAGE, SSL_AD_UNKNOWN_CA, SSL_AD_UNKNOWN_PSK_IDENTITY, SSL_AD_UNRECOGNIZED_NAME, SSL_AD_UNSUPPORTED_CERTIFICATE, SSL_AD_UNSUPPORTED_EXTENSION, SSL_AD_USER_CANCELLED, TLS1_AD_INAPPROPRIATE_FALLBACK, TLS1_AD_NO_APPLICATION_PROTOCOL, and TLS1_AD_UNKNOWN_PSK_IDENTITY.
ssl3_change_cipher_state()
int ssl3_change_cipher_state (SSL * s, int which)
Definition at line 104 of file s3_enc.c.
References EVP_MAX_IV_LENGTH, EVP_MAX_KEY_LENGTH, and key.
ssl3_cleanup_key_block()
void ssl3_cleanup_key_block (SSL * s)
Definition at line 328 of file s3_enc.c.
References NULL, and OPENSSL_clear_free.
Referenced by ssl3_clear(), and ssl3_free().
ssl3_digest_cached_records()
int ssl3_digest_cached_records (SSL * s, int keep)
Definition at line 376 of file s3_enc.c.
Referenced by tls1_final_finish_mac(), tls1_generate_master_secret(), tls_construct_server_done(), tls_construct_server_hello(), and tls_post_process_client_key_exchange().
ssl3_final_finish_mac()
size_t ssl3_final_finish_mac (SSL * s, const char * sender, size_t len, unsigned char * p)
Definition at line 411 of file s3_enc.c.
ssl3_finish_mac()
int ssl3_finish_mac (SSL * s, const unsigned char * buf, size_t len)
Definition at line 362 of file s3_enc.c.
References NULL.
ssl3_free_digest_list()
void ssl3_free_digest_list (SSL * s)
Definition at line 354 of file s3_enc.c.
References BIO_free(), EVP_MD_CTX_free(), and NULL.
Referenced by ssl3_clear(), ssl3_free(), and ssl3_init_finished_mac().
ssl3_generate_master_secret()
int ssl3_generate_master_secret (SSL * s, unsigned char * out, unsigned char * p, size_t len, size_t * secret_size)
Definition at line 455 of file s3_enc.c.
ssl3_init_finished_mac()
int ssl3_init_finished_mac (SSL * s)
Definition at line 335 of file s3_enc.c.
References BIO_new(), BIO_s_mem(), ERR_R_MALLOC_FAILURE, NULL, ssl3_free_digest_list(), SSL_F_SSL3_INIT_FINISHED_MAC, and SSLerr.
Referenced by ossl_statem_client_pre_work(), ossl_statem_server_post_work(), and tls_setup_handshake().
ssl3_setup_key_block()
int ssl3_setup_key_block (SSL * s)
Definition at line 261 of file s3_enc.c.