apps/s_apps.h File Reference
s_apps.h File Reference
#include <openssl/opensslconf.h>
Macros
#define PORT "4433"
#define PROTOCOL "tcp"
Typedefs
typedef int(* do_server_cb) (int s, int stype, unsigned char *context)
Functions
int do_server (int *accept_sock, const char *host, const char *port, int family, int type, do_server_cb cb, unsigned char *context, int naccept)
int ssl_print_tmp_key (BIO *out, SSL *s)
int init_client (int *sock, const char *host, const char *port, int family, int type)
int should_retry (int i)
long bio_dump_callback (BIO *bio, int cmd, const char *argp, int argi, long argl, long ret)
int generate_cookie_callback (SSL *ssl, unsigned char *cookie, unsigned int *cookie_len)
int verify_cookie_callback (SSL *ssl, const unsigned char *cookie, unsigned int cookie_len)
void ssl_ctx_set_excert (SSL_CTX *ctx, SSL_EXCERT *exc)
void ssl_excert_free (SSL_EXCERT *exc)
int args_excert (int option, SSL_EXCERT **pexc)
int load_excert (SSL_EXCERT **pexc)
void print_verify_detail (SSL *s, BIO *bio)
void print_ssl_summary (SSL *s)
Macro Definition Documentation
PORT
#define PORT "4433"
Definition at line 45 of file s_apps.h.
PROTOCOL
#define PROTOCOL "tcp"
Definition at line 46 of file s_apps.h.
Typedef Documentation
do_server_cb
typedef int(* do_server_cb) (int s, int stype, unsigned char *context)
Definition at line 48 of file s_apps.h.
Function Documentation
args_excert()
int args_excert (int option, SSL_EXCERT ** pexc)
Definition at line 922 of file s_cb.c.
References NULL.
bio_dump_callback()
long bio_dump_callback (BIO * bio, int cmd, const char * argp, int argi, long argl, long ret)
Definition at line 416 of file s_cb.c.
do_server()
int do_server (int * accept_sock, const char * host, const char * port, int family, int type, do_server_cb cb, unsigned char * context, int naccept)
Definition at line 130 of file s_socket.c.
References NULL.
generate_cookie_callback()
int generate_cookie_callback (SSL * ssl, unsigned char * cookie, unsigned int * cookie_len)
Definition at line 666 of file s_cb.c.
init_client()
int init_client (int * sock, const char * host, const char * port, int family, int type)
Definition at line 57 of file s_socket.c.
References NULL.
load_excert()
int load_excert (SSL_EXCERT ** pexc)
Definition at line 882 of file s_cb.c.
References bio_err, BIO_printf(), FORMAT_PEM, load_cert(), load_certs(), load_key(), NULL, and ssl_excert_free().
print_ssl_summary()
void print_ssl_summary (SSL * s)
Definition at line 1089 of file s_cb.c.
print_verify_detail()
void print_verify_detail (SSL * s, BIO * bio)
Definition at line 1041 of file s_cb.c.
should_retry()
int should_retry (int i)
ssl_ctx_set_excert()
void ssl_ctx_set_excert (SSL_CTX * ctx, SSL_EXCERT * exc)
Definition at line 840 of file s_cb.c.
References SSL_CTX_set_cert_cb().
ssl_excert_free()
void ssl_excert_free (SSL_EXCERT * exc)
Definition at line 866 of file s_cb.c.
References EVP_PKEY_free(), and OPENSSL_free.
Referenced by load_excert().
ssl_print_tmp_key()
int ssl_print_tmp_key (BIO * out, SSL * s)
Definition at line 379 of file s_cb.c.
References BIO_printf(), BIO_puts(), EC_curve_nid2nist(), EC_GROUP_get_curve_name(), EC_KEY_free(), EC_KEY_get0_group(), EVP_PKEY_bits(), EVP_PKEY_DH, EVP_PKEY_EC, EVP_PKEY_free(), EVP_PKEY_get1_EC_KEY(), EVP_PKEY_id(), EVP_PKEY_RSA, key, nid, OBJ_nid2sn(), and SSL_get_server_tmp_key.
verify_cookie_callback()
int verify_cookie_callback (SSL * ssl, const unsigned char * cookie, unsigned int cookie_len)
Definition at line 712 of file s_cb.c.