apps/s_cb.c File Reference
s_cb.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "apps.h"
#include <openssl/err.h>
#include <openssl/rand.h>
#include <openssl/x509.h>
#include <openssl/ssl.h>
#include <openssl/bn.h>
#include <openssl/dh.h>
#include "s_apps.h"
Data Structures
struct SSL_EXCERT
struct security_debug_ex
Macros
#define USE_SOCKETS
#define COOKIE_SECRET_LENGTH 16
#define TLSA_TAIL_SIZE 12
Enumerations
enum range { OPT_V_ENUM, OPT_X_ENUM }
Functions
int verify_callback (int ok, X509_STORE_CTX *ctx)
int set_cert_stuff (SSL_CTX *ctx, char *cert_file, char *key_file)
int set_cert_key_stuff (SSL_CTX *ctx, X509 *cert, EVP_PKEY *key, STACK_OF(X509) *chain, int build_chain)
int ssl_print_sigalgs (BIO *out, SSL *s)
int ssl_print_point_formats (BIO *out, SSL *s)
int ssl_print_groups (BIO *out, SSL *s, int noshared)
int ssl_print_tmp_key (BIO *out, SSL *s)
long bio_dump_callback (BIO *bio, int cmd, const char *argp, int argi, long argl, long ret)
void apps_ssl_info_callback (const SSL *s, int where, int ret)
void msg_cb (int write_p, int version, int content_type, const void *buf, size_t len, SSL *ssl, void *arg)
void tlsext_cb (SSL *s, int client_server, int type, const unsigned char *data, int len, void *arg)
int generate_cookie_callback (SSL *ssl, unsigned char *cookie, unsigned int *cookie_len)
int verify_cookie_callback (SSL *ssl, const unsigned char *cookie, unsigned int cookie_len)
void ssl_ctx_set_excert (SSL_CTX *ctx, SSL_EXCERT *exc)
void ssl_excert_free (SSL_EXCERT *exc)
int load_excert (SSL_EXCERT **pexc)
int args_excert (int opt, SSL_EXCERT **pexc)
void print_verify_detail (SSL *s, BIO *bio)
void print_ssl_summary (SSL *s)
int config_ctx (SSL_CONF_CTX *cctx, STACK_OF(OPENSSL_STRING) *str, SSL_CTX *ctx)
int ssl_ctx_add_crls (SSL_CTX *ctx, STACK_OF(X509_CRL) *crls, int crl_download)
int ssl_load_stores (SSL_CTX *ctx, const char *vfyCApath, const char *vfyCAfile, const char *chCApath, const char *chCAfile, STACK_OF(X509_CRL) *crls, int crl_download)
void ssl_ctx_security_debug (SSL_CTX *ctx, int verbose)
int set_keylog_file (SSL_CTX *ctx, const char *keylog_file)
Variables
VERIFY_CB_ARGS verify_args = { 0, 0, X509_V_OK, 0 }
Macro Definition Documentation
COOKIE_SECRET_LENGTH
#define COOKIE_SECRET_LENGTH 16
Definition at line 27 of file s_cb.c.
TLSA_TAIL_SIZE
#define TLSA_TAIL_SIZE 12
USE_SOCKETS
#define USE_SOCKETS
Definition at line 14 of file s_cb.c.
Enumeration Type Documentation
range
enum range
Enumerator
OPT_V_ENUM
OPT_X_ENUM
Definition at line 920 of file s_cb.c.
Function Documentation
apps_ssl_info_callback()
void apps_ssl_info_callback (const SSL * s, int where, int ret)
Definition at line 438 of file s_cb.c.
args_excert()
int args_excert (int opt, SSL_EXCERT ** pexc)
Definition at line 922 of file s_cb.c.
References NULL.
bio_dump_callback()
long bio_dump_callback (BIO * bio, int cmd, const char * argp, int argi, long argl, long ret)
Definition at line 416 of file s_cb.c.
config_ctx()
int config_ctx (SSL_CONF_CTX * cctx, STACK_OF(OPENSSL_STRING) * str, SSL_CTX * ctx)
Definition at line 1128 of file s_cb.c.
References SSL_CONF_CTX_set_ssl_ctx().
generate_cookie_callback()
int generate_cookie_callback (SSL * ssl, unsigned char * cookie, unsigned int * cookie_len)
Definition at line 666 of file s_cb.c.
load_excert()
int load_excert (SSL_EXCERT ** pexc)
Definition at line 882 of file s_cb.c.
References bio_err, BIO_printf(), FORMAT_PEM, load_cert(), load_certs(), load_key(), NULL, and ssl_excert_free().
msg_cb()
void msg_cb (int write_p, int version, int content_type, const void * buf, size_t len, SSL * ssl, void * arg)
Definition at line 533 of file s_cb.c.
print_ssl_summary()
void print_ssl_summary (SSL * s)
Definition at line 1089 of file s_cb.c.
print_verify_detail()
void print_verify_detail (SSL * s, BIO * bio)
Definition at line 1041 of file s_cb.c.
set_cert_key_stuff()
int set_cert_key_stuff (SSL_CTX * ctx, X509 * cert, EVP_PKEY * key, STACK_OF(X509) * chain, int build_chain)
Definition at line 144 of file s_cb.c.
set_cert_stuff()
int set_cert_stuff (SSL_CTX * ctx, char * cert_file, char * key_file)
Definition at line 107 of file s_cb.c.
References bio_err, BIO_printf(), ERR_print_errors(), NULL, SSL_CTX_check_private_key(), SSL_CTX_use_certificate_file(), SSL_CTX_use_PrivateKey_file(), and SSL_FILETYPE_PEM.
set_keylog_file()
int set_keylog_file (SSL_CTX * ctx, const char * keylog_file)
Definition at line 1376 of file s_cb.c.
References BIO_free_all().
ssl_ctx_add_crls()
int ssl_ctx_add_crls (SSL_CTX * ctx, STACK_OF(X509_CRL) * crls, int crl_download)
Definition at line 1166 of file s_cb.c.
References SSL_CTX_get_cert_store().
ssl_ctx_security_debug()
void ssl_ctx_security_debug (SSL_CTX * ctx, int verbose)
Definition at line 1350 of file s_cb.c.
ssl_ctx_set_excert()
void ssl_ctx_set_excert (SSL_CTX * ctx, SSL_EXCERT * exc)
Definition at line 840 of file s_cb.c.
References SSL_CTX_set_cert_cb().
ssl_excert_free()
void ssl_excert_free (SSL_EXCERT * exc)
Definition at line 866 of file s_cb.c.
References EVP_PKEY_free(), and OPENSSL_free.
Referenced by load_excert().
ssl_load_stores()
int ssl_load_stores (SSL_CTX * ctx, const char * vfyCApath, const char * vfyCAfile, const char * chCApath, const char * chCAfile, STACK_OF(X509_CRL) * crls, int crl_download)
Definition at line 1176 of file s_cb.c.
References NULL, X509_STORE_load_locations(), and X509_STORE_new().
ssl_print_groups()
int ssl_print_groups (BIO * out, SSL * s, int noshared)
Definition at line 328 of file s_cb.c.
References app_malloc(), BIO_printf(), BIO_puts(), EC_curve_nid2nist(), nid, NULL, OBJ_nid2sn(), OPENSSL_free, SSL_get1_groups, SSL_get_shared_group, and TLSEXT_nid_unknown.
ssl_print_point_formats()
int ssl_print_point_formats (BIO * out, SSL * s)
Definition at line 294 of file s_cb.c.
References BIO_printf(), BIO_puts(), SSL_get0_ec_point_formats, TLSEXT_ECPOINTFORMAT_ansiX962_compressed_char2, TLSEXT_ECPOINTFORMAT_ansiX962_compressed_prime, and TLSEXT_ECPOINTFORMAT_uncompressed.
ssl_print_sigalgs()
int ssl_print_sigalgs (BIO * out, SSL * s)
Definition at line 279 of file s_cb.c.
References nid, and SSL_is_server().
ssl_print_tmp_key()
int ssl_print_tmp_key (BIO * out, SSL * s)
Definition at line 379 of file s_cb.c.
References BIO_printf(), BIO_puts(), EC_curve_nid2nist(), EC_GROUP_get_curve_name(), EC_KEY_free(), EC_KEY_get0_group(), EVP_PKEY_bits(), EVP_PKEY_DH, EVP_PKEY_EC, EVP_PKEY_free(), EVP_PKEY_get1_EC_KEY(), EVP_PKEY_id(), EVP_PKEY_RSA, key, nid, OBJ_nid2sn(), and SSL_get_server_tmp_key.
tlsext_cb()
void tlsext_cb (SSL * s, int client_server, int type, const unsigned char * data, int len, void * arg)
Definition at line 653 of file s_cb.c.
verify_callback()
static int verify_callback (int ok, X509_STORE_CTX * ctx)
Definition at line 45 of file s_cb.c.
References ASN1_TIME_print(), bio_err, BIO_printf(), BIO_puts(), VERIFY_CB_ARGS::depth, VERIFY_CB_ARGS::error, policies_print(), VERIFY_CB_ARGS::quiet, VERIFY_CB_ARGS::return_error, X509_get0_notAfter(), X509_get0_notBefore(), X509_get_issuer_name(), X509_get_subject_name(), X509_NAME_print_ex(), X509_STORE_CTX_get_current_cert(), X509_STORE_CTX_get_error(), X509_STORE_CTX_get_error_depth(), X509_V_ERR_CERT_CHAIN_TOO_LONG, X509_V_ERR_CERT_HAS_EXPIRED, X509_V_ERR_CERT_NOT_YET_VALID, X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD, X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD, X509_V_ERR_NO_EXPLICIT_POLICY, X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT, X509_V_OK, X509_verify_cert_error_string(), and XN_FLAG_ONELINE.
verify_cookie_callback()
int verify_cookie_callback (SSL * ssl, const unsigned char * cookie, unsigned int cookie_len)
Definition at line 712 of file s_cb.c.
Variable Documentation
verify_args
VERIFY_CB_ARGS verify_args = { 0, 0, X509_V_OK, 0 }
Definition at line 29 of file s_cb.c.