crypto/des/set_key.c File Reference
set_key.c File Reference
#include <openssl/crypto.h>
#include "des_locl.h"
Macros
#define NUM_WEAK_KEY 16
#define HPERM_OP(a, t, n, m)
Functions
void DES_set_odd_parity (DES_cblock *key)
int DES_check_key_parity (const_DES_cblock *key)
int DES_is_weak_key (const_DES_cblock *key)
int DES_set_key (const_DES_cblock *key, DES_key_schedule *schedule)
int DES_set_key_checked (const_DES_cblock *key, DES_key_schedule *schedule)
void DES_set_key_unchecked (const_DES_cblock *key, DES_key_schedule *schedule)
int DES_key_sched (const_DES_cblock *key, DES_key_schedule *schedule)
Macro Definition Documentation
HPERM_OP
#define HPERM_OP (a, t, n, m)
Value:
((t)=((((a)<<(16-(n)))^(a))&(m)),\
        (a)=(a)^(t)^(t>>(16-(n))))
Definition at line 129 of file set_key.c.
NUM_WEAK_KEY
#define NUM_WEAK_KEY 16
Definition at line 83 of file set_key.c.
Referenced by DES_is_weak_key().
Function Documentation
DES_check_key_parity()
int DES_check_key_parity (const_DES_cblock * key)
Definition at line 62 of file set_key.c.
References DES_KEY_SZ.
Referenced by DES_set_key_checked().
DES_is_weak_key()
int DES_is_weak_key (const_DES_cblock * key)
Definition at line 105 of file set_key.c.
References NUM_WEAK_KEY.
Referenced by DES_set_key_checked().
DES_key_sched()
int DES_key_sched (const_DES_cblock * key, DES_key_schedule * schedule)
Definition at line 378 of file set_key.c.
References DES_set_key().
DES_set_key()
int DES_set_key (const_DES_cblock * key, DES_key_schedule * schedule)
Definition at line 287 of file set_key.c.
References DES_check_key, DES_set_key_checked(), and DES_set_key_unchecked().
Referenced by DES_key_sched().
DES_set_key_checked()
int DES_set_key_checked (const_DES_cblock * key, DES_key_schedule * schedule)
Definition at line 302 of file set_key.c.
References DES_check_key_parity(), DES_is_weak_key(), and DES_set_key_unchecked().
Referenced by DES_set_key().
DES_set_key_unchecked()
void DES_set_key_unchecked (const_DES_cblock * key, DES_key_schedule * schedule)
Definition at line 312 of file set_key.c.
Referenced by DES_set_key(), DES_set_key_checked(), and DES_string_to_key().
DES_set_odd_parity()
void DES_set_odd_parity (DES_cblock * key)
Definition at line 54 of file set_key.c.
References DES_KEY_SZ.
Referenced by DES_string_to_key().