crypto/sparcv9cap.c File Reference
sparcv9cap.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>
#include <signal.h>
#include <sys/time.h>
#include <unistd.h>
#include <openssl/bn.h>
#include "sparc_arch.h"
Functions
int bn_mul_mont (BN_ULONG *rp, const BN_ULONG *ap, const BN_ULONG *bp, const BN_ULONG *np, const BN_ULONG *n0, int num)
unsigned long _sparcv9_rdtick (void)
void _sparcv9_vis1_probe (void)
unsigned long _sparcv9_vis1_instrument (void)
void _sparcv9_vis2_probe (void)
void _sparcv9_fmadd_probe (void)
unsigned long _sparcv9_rdcfr (void)
void _sparcv9_vis3_probe (void)
void _sparcv9_fjaesx_probe (void)
unsigned long _sparcv9_random (void)
size_t _sparcv9_vis1_instrument_bus (unsigned int *, size_t)
size_t _sparcv9_vis1_instrument_bus2 (unsigned int *, size_t, size_t)
unsigned long OPENSSL_rdtsc (void)
size_t OPENSSL_instrument_bus (unsigned int *out, size_t cnt)
size_t OPENSSL_instrument_bus2 (unsigned int *out, size_t cnt, size_t max)
void OPENSSL_cpuid_setup (void)
Variables
unsigned int OPENSSL_sparcv9cap_P [2] = { SPARCV9_TICK_PRIVILEGED, 0 }
Function Documentation
_sparcv9_fjaesx_probe()
void _sparcv9_fjaesx_probe (void)
Referenced by bn_mul_mont().
_sparcv9_fmadd_probe()
void _sparcv9_fmadd_probe (void)
Referenced by bn_mul_mont().
_sparcv9_random()
unsigned long _sparcv9_random (void)
Referenced by bn_mul_mont().
_sparcv9_rdcfr()
unsigned long _sparcv9_rdcfr (void)
Referenced by bn_mul_mont().
_sparcv9_rdtick()
unsigned long _sparcv9_rdtick (void)
Referenced by bn_mul_mont(), and OPENSSL_rdtsc().
_sparcv9_vis1_instrument()
unsigned long _sparcv9_vis1_instrument (void)
Referenced by bn_mul_mont().
_sparcv9_vis1_instrument_bus()
size_t _sparcv9_vis1_instrument_bus (unsigned int * , size_t)
Referenced by bn_mul_mont().
_sparcv9_vis1_instrument_bus2()
size_t _sparcv9_vis1_instrument_bus2 (unsigned int * , size_t , size_t)
Referenced by bn_mul_mont().
_sparcv9_vis1_probe()
void _sparcv9_vis1_probe (void)
Referenced by bn_mul_mont().
_sparcv9_vis2_probe()
void _sparcv9_vis2_probe (void)
Referenced by bn_mul_mont().
_sparcv9_vis3_probe()
void _sparcv9_vis3_probe (void)
Referenced by bn_mul_mont().
bn_mul_mont()
int bn_mul_mont (BN_ULONG * rp, const BN_ULONG * ap, const BN_ULONG * bp, const BN_ULONG * np, const BN_ULONG * n0, int num)
Definition at line 26 of file sparcv9cap.c.
References _sparcv9_fjaesx_probe(), _sparcv9_fmadd_probe(), _sparcv9_random(), _sparcv9_rdcfr(), _sparcv9_rdtick(), _sparcv9_vis1_instrument(), _sparcv9_vis1_instrument_bus(), _sparcv9_vis1_instrument_bus2(), _sparcv9_vis1_probe(), _sparcv9_vis2_probe(), _sparcv9_vis3_probe(), bp, CFR_MONTMUL, CFR_MONTSQR, SPARCV9_FMADD, SPARCV9_PREFER_FPU, SPARCV9_VIS1, and SPARCV9_VIS3.
Referenced by bn_sqr_comba4().
OPENSSL_cpuid_setup()
void OPENSSL_cpuid_setup (void)
Definition at line 148 of file sparcv9cap.c.
References e.
OPENSSL_instrument_bus()
size_t OPENSSL_instrument_bus (unsigned int * out, size_t cnt)
Definition at line 113 of file sparcv9cap.c.
OPENSSL_instrument_bus2()
size_t OPENSSL_instrument_bus2 (unsigned int * out, size_t cnt, size_t max)
Definition at line 122 of file sparcv9cap.c.
OPENSSL_rdtsc()
unsigned long OPENSSL_rdtsc (void)
Definition at line 101 of file sparcv9cap.c.
References _sparcv9_rdtick(), and SPARCV9_TICK_PRIVILEGED.
Variable Documentation
OPENSSL_sparcv9cap_P
unsigned int OPENSSL_sparcv9cap_P[2] = { SPARCV9_TICK_PRIVILEGED, 0 }
Definition at line 24 of file sparcv9cap.c.