include/openssl/srp.h File Reference
srp.h File Reference
#include <openssl/opensslconf.h>
#include <stdio.h>
#include <string.h>
#include <openssl/safestack.h>
#include <openssl/bn.h>
#include <openssl/crypto.h>
Data Structures
struct SRP_gN_cache
struct SRP_user_pwd
struct SRP_VBASE
struct SRP_gN
Macros
#define SRP_NO_ERROR 0
#define SRP_ERR_VBASE_INCOMPLETE_FILE 1
#define SRP_ERR_VBASE_BN_LIB 2
#define SRP_ERR_OPEN_FILE 3
#define SRP_ERR_MEMORY 4
#define DB_srptype 0
#define DB_srpverifier 1
#define DB_srpsalt 2
#define DB_srpid 3
#define DB_srpgN 4
#define DB_srpinfo 5
#define DB_NUMBER 6
#define DB_SRP_INDEX 'I'
#define DB_SRP_VALID 'V'
#define DB_SRP_REVOKED 'R'
#define DB_SRP_MODIF 'v'
#define SRP_MINIMAL_N 1024
Functions
void SRP_user_pwd_free (SRP_user_pwd *user_pwd)
SRP_VBASE * SRP_VBASE_new (char *seed_key)
void SRP_VBASE_free (SRP_VBASE *vb)
int SRP_VBASE_init (SRP_VBASE *vb, char *verifier_file)
SRP_user_pwd * SRP_VBASE_get1_by_user (SRP_VBASE *vb, char *username)
char * SRP_create_verifier (const char *user, const char *pass, char **salt, char **verifier, const char *N, const char *g)
int SRP_create_verifier_BN (const char *user, const char *pass, BIGNUM **salt, BIGNUM **verifier, const BIGNUM *N, const BIGNUM *g)
char * SRP_check_known_gN_param (const BIGNUM *g, const BIGNUM *N)
SRP_gN * SRP_get_default_gN (const char *id)
BIGNUM * SRP_Calc_server_key (const BIGNUM *A, const BIGNUM *v, const BIGNUM *u, const BIGNUM *b, const BIGNUM *N)
BIGNUM * SRP_Calc_B (const BIGNUM *b, const BIGNUM *N, const BIGNUM *g, const BIGNUM *v)
int SRP_Verify_A_mod_N (const BIGNUM *A, const BIGNUM *N)
BIGNUM * SRP_Calc_u (const BIGNUM *A, const BIGNUM *B, const BIGNUM *N)
BIGNUM * SRP_Calc_x (const BIGNUM *s, const char *user, const char *pass)
BIGNUM * SRP_Calc_A (const BIGNUM *a, const BIGNUM *N, const BIGNUM *g)
BIGNUM * SRP_Calc_client_key (const BIGNUM *N, const BIGNUM *B, const BIGNUM *g, const BIGNUM *x, const BIGNUM *a, const BIGNUM *u)
int SRP_Verify_B_mod_N (const BIGNUM *B, const BIGNUM *N)
Macro Definition Documentation
DB_NUMBER
#define DB_NUMBER 6
Definition at line 98 of file srp.h.
DB_SRP_INDEX
#define DB_SRP_INDEX 'I'
Definition at line 100 of file srp.h.
Referenced by SRP_VBASE_init().
DB_SRP_MODIF
#define DB_SRP_MODIF 'v'
Definition at line 103 of file srp.h.
DB_SRP_REVOKED
#define DB_SRP_REVOKED 'R'
Definition at line 102 of file srp.h.
DB_SRP_VALID
#define DB_SRP_VALID 'V'
Definition at line 101 of file srp.h.
DB_srpgN
#define DB_srpgN 4
Definition at line 95 of file srp.h.
DB_srpid
#define DB_srpid 3
Definition at line 94 of file srp.h.
Referenced by SRP_VBASE_init().
DB_srpinfo
#define DB_srpinfo 5
Definition at line 96 of file srp.h.
DB_srpsalt
#define DB_srpsalt 2
Definition at line 93 of file srp.h.
DB_srptype
#define DB_srptype 0
Definition at line 91 of file srp.h.
Referenced by SRP_VBASE_init().
DB_srpverifier
#define DB_srpverifier 1
Definition at line 92 of file srp.h.
SRP_ERR_MEMORY
#define SRP_ERR_MEMORY 4
Definition at line 89 of file srp.h.
Referenced by SRP_VBASE_init().
SRP_ERR_OPEN_FILE
#define SRP_ERR_OPEN_FILE 3
Definition at line 88 of file srp.h.
Referenced by SRP_VBASE_init().
SRP_ERR_VBASE_BN_LIB
#define SRP_ERR_VBASE_BN_LIB 2
Definition at line 87 of file srp.h.
SRP_ERR_VBASE_INCOMPLETE_FILE
#define SRP_ERR_VBASE_INCOMPLETE_FILE 1
Definition at line 86 of file srp.h.
Referenced by SRP_VBASE_init().
SRP_MINIMAL_N
#define SRP_MINIMAL_N 1024
Definition at line 124 of file srp.h.
Referenced by SSL_CTX_SRP_CTX_free(), SSL_CTX_SRP_CTX_init(), and SSL_SRP_CTX_free().
SRP_NO_ERROR
#define SRP_NO_ERROR 0
Definition at line 85 of file srp.h.
Function Documentation
SRP_Calc_A()
BIGNUM* SRP_Calc_A (const BIGNUM * a, const BIGNUM * N, const BIGNUM * g)
Definition at line 154 of file srp_lib.c.
References BN_CTX_free(), BN_CTX_new(), BN_free(), BN_mod_exp(), BN_new(), and NULL.
Referenced by SRP_Calc_A_param().
SRP_Calc_B()
BIGNUM* SRP_Calc_B (const BIGNUM * b, const BIGNUM * N, const BIGNUM * g, const BIGNUM * v)
Definition at line 83 of file srp_lib.c.
References B, and NULL.
Referenced by SSL_srp_server_param_with_username().
SRP_Calc_client_key()
BIGNUM* SRP_Calc_client_key (const BIGNUM * N, const BIGNUM * B, const BIGNUM * g, const BIGNUM * x, const BIGNUM * a, const BIGNUM * u)
Definition at line 170 of file srp_lib.c.
References NULL.
SRP_Calc_server_key()
BIGNUM* SRP_Calc_server_key (const BIGNUM * A, const BIGNUM * v, const BIGNUM * u, const BIGNUM * b, const BIGNUM * N)
Definition at line 53 of file srp_lib.c.
References NULL.
SRP_Calc_u()
BIGNUM* SRP_Calc_u (const BIGNUM * A, const BIGNUM * B, const BIGNUM * N)
Definition at line 47 of file srp_lib.c.
SRP_Calc_x()
BIGNUM* SRP_Calc_x (const BIGNUM * s, const char * user, const char * pass)
Definition at line 115 of file srp_lib.c.
References BN_bin2bn(), BN_bn2bin(), BN_num_bytes, EVP_DigestFinal_ex(), EVP_DigestInit_ex(), EVP_DigestUpdate(), EVP_MD_CTX_free(), EVP_MD_CTX_new(), EVP_sha1(), NULL, OPENSSL_free, OPENSSL_malloc, and SHA_DIGEST_LENGTH.
Referenced by SRP_create_verifier_BN().
SRP_check_known_gN_param()
char* SRP_check_known_gN_param (const BIGNUM * g, const BIGNUM * N)
Definition at line 255 of file srp_lib.c.
References BN_cmp(), SRP_gN::id, KNOWN_GN_NUMBER, and NULL.
Referenced by srp_verify_server_param().
SRP_create_verifier()
char* SRP_create_verifier (const char * user, const char * pass, char ** salt, char ** verifier, const char * N, const char * g)
Definition at line 543 of file srp_vfy.c.
References len, MAX_LEN, and NULL.
SRP_create_verifier_BN()
int SRP_create_verifier_BN (const char * user, const char * pass, BIGNUM ** salt, BIGNUM ** verifier, const BIGNUM * N, const BIGNUM * g)
Definition at line 630 of file srp_vfy.c.
References BN_bin2bn(), BN_clear_free(), BN_CTX_free(), BN_CTX_new(), BN_mod_exp(), BN_new(), MAX_LEN, NULL, RAND_bytes(), SRP_Calc_x(), and SRP_RANDOM_SALT_LEN.
Referenced by SSL_set_srp_server_param_pw().
SRP_get_default_gN()
SRP_gN* SRP_get_default_gN (const char * id)
Definition at line 268 of file srp_lib.c.
References NULL.
Referenced by SRP_VBASE_init(), and SSL_set_srp_server_param_pw().
SRP_user_pwd_free()
void SRP_user_pwd_free (SRP_user_pwd * user_pwd)
Definition at line 141 of file srp_vfy.c.
References BN_clear_free(), BN_free(), SRP_user_pwd::id, SRP_user_pwd::info, NULL, OPENSSL_free, SRP_user_pwd::s, and SRP_user_pwd::v.
Referenced by SRP_VBASE_free().
SRP_VBASE_free()
void SRP_VBASE_free (SRP_VBASE * vb)
Definition at line 256 of file srp_vfy.c.
References OPENSSL_free, SRP_VBASE::seed_key, and SRP_user_pwd_free().
SRP_VBASE_get1_by_user()
SRP_user_pwd* SRP_VBASE_get1_by_user (SRP_VBASE * vb, char * username)
Definition at line 491 of file srp_vfy.c.
References NULL, and SHA_DIGEST_LENGTH.
SRP_VBASE_init()
int SRP_VBASE_init (SRP_VBASE * vb, char * verifier_file)
Definition at line 344 of file srp_vfy.c.
References BIO_new(), BIO_read_filename, BIO_s_file(), DB_NUMBER, DB_SRP_INDEX, DB_srpid, DB_srptype, SRP_gN::id, in, SRP_gN::N, NULL, OPENSSL_malloc, OPENSSL_strdup, pp, SRP_VBASE::seed_key, SRP_ERR_MEMORY, SRP_ERR_OPEN_FILE, SRP_ERR_VBASE_INCOMPLETE_FILE, SRP_get_default_gN(), STACK_OF, and TXT_DB_read().
SRP_VBASE_new()
SRP_VBASE* SRP_VBASE_new (char * seed_key)
Definition at line 233 of file srp_vfy.c.
References SRP_VBASE::default_g, SRP_VBASE::default_N, NULL, OPENSSL_free, OPENSSL_malloc, OPENSSL_strdup, and SRP_VBASE::seed_key.
SRP_Verify_A_mod_N()
int SRP_Verify_A_mod_N (const BIGNUM * A, const BIGNUM * N)
Definition at line 233 of file srp_lib.c.
References SRP_Verify_B_mod_N().
SRP_Verify_B_mod_N()
int SRP_Verify_B_mod_N (const BIGNUM * B, const BIGNUM * N)
Definition at line 212 of file srp_lib.c.
Referenced by SRP_Verify_A_mod_N().