crypto/srp/srp_lib.c File Reference
srp_lib.c File Reference
#include "internal/cryptlib.h"
#include <openssl/sha.h>
#include <openssl/srp.h>
#include <openssl/evp.h>
#include "internal/bn_srp.h"
Macros
#define KNOWN_GN_NUMBER sizeof(knowngN) / sizeof(SRP_gN)
Functions
BIGNUM * SRP_Calc_u (const BIGNUM *A, const BIGNUM *B, const BIGNUM *N)
BIGNUM * SRP_Calc_server_key (const BIGNUM *A, const BIGNUM *v, const BIGNUM *u, const BIGNUM *b, const BIGNUM *N)
BIGNUM * SRP_Calc_B (const BIGNUM *b, const BIGNUM *N, const BIGNUM *g, const BIGNUM *v)
BIGNUM * SRP_Calc_x (const BIGNUM *s, const char *user, const char *pass)
BIGNUM * SRP_Calc_A (const BIGNUM *a, const BIGNUM *N, const BIGNUM *g)
BIGNUM * SRP_Calc_client_key (const BIGNUM *N, const BIGNUM *B, const BIGNUM *g, const BIGNUM *x, const BIGNUM *a, const BIGNUM *u)
int SRP_Verify_B_mod_N (const BIGNUM *B, const BIGNUM *N)
int SRP_Verify_A_mod_N (const BIGNUM *A, const BIGNUM *N)
char * SRP_check_known_gN_param (const BIGNUM *g, const BIGNUM *N)
SRP_gN * SRP_get_default_gN (const char *id)
Macro Definition Documentation
KNOWN_GN_NUMBER
#define KNOWN_GN_NUMBER sizeof(knowngN) / sizeof(SRP_gN)
Definition at line 249 of file srp_lib.c.
Referenced by SRP_check_known_gN_param().
Function Documentation
SRP_Calc_A()
BIGNUM* SRP_Calc_A (const BIGNUM * a, const BIGNUM * N, const BIGNUM * g)
Definition at line 154 of file srp_lib.c.
References BN_CTX_free(), BN_CTX_new(), BN_free(), BN_mod_exp(), BN_new(), and NULL.
Referenced by SRP_Calc_A_param().
SRP_Calc_B()
BIGNUM* SRP_Calc_B (const BIGNUM * b, const BIGNUM * N, const BIGNUM * g, const BIGNUM * v)
Definition at line 83 of file srp_lib.c.
References B, and NULL.
Referenced by SSL_srp_server_param_with_username().
SRP_Calc_client_key()
BIGNUM* SRP_Calc_client_key (const BIGNUM * N, const BIGNUM * B, const BIGNUM * g, const BIGNUM * x, const BIGNUM * a, const BIGNUM * u)
Definition at line 170 of file srp_lib.c.
References NULL.
SRP_Calc_server_key()
BIGNUM* SRP_Calc_server_key (const BIGNUM * A, const BIGNUM * v, const BIGNUM * u, const BIGNUM * b, const BIGNUM * N)
Definition at line 53 of file srp_lib.c.
References NULL.
SRP_Calc_u()
BIGNUM* SRP_Calc_u (const BIGNUM * A, const BIGNUM * B, const BIGNUM * N)
Definition at line 47 of file srp_lib.c.
SRP_Calc_x()
BIGNUM* SRP_Calc_x (const BIGNUM * s, const char * user, const char * pass)
Definition at line 115 of file srp_lib.c.
References BN_bin2bn(), BN_bn2bin(), BN_num_bytes, EVP_DigestFinal_ex(), EVP_DigestInit_ex(), EVP_DigestUpdate(), EVP_MD_CTX_free(), EVP_MD_CTX_new(), EVP_sha1(), NULL, OPENSSL_free, OPENSSL_malloc, and SHA_DIGEST_LENGTH.
Referenced by SRP_create_verifier_BN().
SRP_check_known_gN_param()
char* SRP_check_known_gN_param (const BIGNUM * g, const BIGNUM * N)
Definition at line 255 of file srp_lib.c.
References BN_cmp(), SRP_gN::id, KNOWN_GN_NUMBER, and NULL.
Referenced by srp_verify_server_param().
SRP_get_default_gN()
SRP_gN* SRP_get_default_gN (const char * id)
Definition at line 268 of file srp_lib.c.
References NULL.
Referenced by SRP_VBASE_init(), and SSL_set_srp_server_param_pw().
SRP_Verify_A_mod_N()
int SRP_Verify_A_mod_N (const BIGNUM * A, const BIGNUM * N)
Definition at line 233 of file srp_lib.c.
References SRP_Verify_B_mod_N().
SRP_Verify_B_mod_N()
int SRP_Verify_B_mod_N (const BIGNUM * B, const BIGNUM * N)
Definition at line 212 of file srp_lib.c.
Referenced by SRP_Verify_A_mod_N().