crypto/srp/srp_vfy.c File Reference
srp_vfy.c File Reference
#include "internal/cryptlib.h"
#include <openssl/sha.h>
#include <openssl/srp.h>
#include <openssl/evp.h>
#include <openssl/buffer.h>
#include <openssl/rand.h>
#include <openssl/txt_db.h>
Macros
#define SRP_RANDOM_SALT_LEN 20
#define MAX_LEN 2500
Functions
void SRP_user_pwd_free (SRP_user_pwd *user_pwd)
SRP_VBASE * SRP_VBASE_new (char *seed_key)
void SRP_VBASE_free (SRP_VBASE *vb)
int SRP_VBASE_init (SRP_VBASE *vb, char *verifier_file)
SRP_user_pwd * SRP_VBASE_get_by_user (SRP_VBASE *vb, char *username)
SRP_user_pwd * SRP_VBASE_get1_by_user (SRP_VBASE *vb, char *username)
char * SRP_create_verifier (const char *user, const char *pass, char **salt, char **verifier, const char *N, const char *g)
int SRP_create_verifier_BN (const char *user, const char *pass, BIGNUM **salt, BIGNUM **verifier, const BIGNUM *N, const BIGNUM *g)
Macro Definition Documentation
MAX_LEN
#define MAX_LEN 2500
Definition at line 20 of file srp_vfy.c.
Referenced by SRP_create_verifier(), and SRP_create_verifier_BN().
SRP_RANDOM_SALT_LEN
#define SRP_RANDOM_SALT_LEN 20
Definition at line 19 of file srp_vfy.c.
Referenced by SRP_create_verifier_BN().
Function Documentation
SRP_create_verifier()
char* SRP_create_verifier (const char * user, const char * pass, char ** salt, char ** verifier, const char * N, const char * g)
Definition at line 543 of file srp_vfy.c.
References len, MAX_LEN, and NULL.
SRP_create_verifier_BN()
int SRP_create_verifier_BN (const char * user, const char * pass, BIGNUM ** salt, BIGNUM ** verifier, const BIGNUM * N, const BIGNUM * g)
Definition at line 630 of file srp_vfy.c.
References BN_bin2bn(), BN_clear_free(), BN_CTX_free(), BN_CTX_new(), BN_mod_exp(), BN_new(), MAX_LEN, NULL, RAND_bytes(), SRP_Calc_x(), and SRP_RANDOM_SALT_LEN.
Referenced by SSL_set_srp_server_param_pw().
SRP_user_pwd_free()
void SRP_user_pwd_free (SRP_user_pwd * user_pwd)
Definition at line 141 of file srp_vfy.c.
References BN_clear_free(), BN_free(), SRP_user_pwd::id, SRP_user_pwd::info, NULL, OPENSSL_free, SRP_user_pwd::s, and SRP_user_pwd::v.
Referenced by SRP_VBASE_free().
SRP_VBASE_free()
void SRP_VBASE_free (SRP_VBASE * vb)
Definition at line 256 of file srp_vfy.c.
References OPENSSL_free, SRP_VBASE::seed_key, and SRP_user_pwd_free().
SRP_VBASE_get1_by_user()
SRP_user_pwd* SRP_VBASE_get1_by_user (SRP_VBASE * vb, char * username)
Definition at line 491 of file srp_vfy.c.
References NULL, and SHA_DIGEST_LENGTH.
SRP_VBASE_get_by_user()
SRP_user_pwd* SRP_VBASE_get_by_user (SRP_VBASE * vb, char * username)
Definition at line 481 of file srp_vfy.c.
SRP_VBASE_init()
int SRP_VBASE_init (SRP_VBASE * vb, char * verifier_file)
Definition at line 344 of file srp_vfy.c.
References BIO_new(), BIO_read_filename, BIO_s_file(), DB_NUMBER, DB_SRP_INDEX, DB_srpid, DB_srptype, SRP_gN::id, in, SRP_gN::N, NULL, OPENSSL_malloc, OPENSSL_strdup, pp, SRP_VBASE::seed_key, SRP_ERR_MEMORY, SRP_ERR_OPEN_FILE, SRP_ERR_VBASE_INCOMPLETE_FILE, SRP_get_default_gN(), STACK_OF, and TXT_DB_read().
SRP_VBASE_new()
SRP_VBASE* SRP_VBASE_new (char * seed_key)
Definition at line 233 of file srp_vfy.c.
References SRP_VBASE::default_g, SRP_VBASE::default_N, NULL, OPENSSL_free, OPENSSL_malloc, OPENSSL_strdup, and SRP_VBASE::seed_key.