ssl/record/ssl3_record.c File Reference
ssl3_record.c File Reference
#include <assert.h>
#include "../ssl_locl.h"
#include "internal/constant_time_locl.h"
#include <openssl/rand.h>
#include "record_locl.h"
Macros
#define MAX_EMPTY_RECORDS 32
#define SSL2_RT_HEADER_LENGTH 2
#define MAX_PADDING 256
#define CBC_MAC_ROTATE_IN_PLACE
#define dtls1_get_processed_record(s)
Functions
void SSL3_RECORD_clear (SSL3_RECORD *r, size_t num_recs)
void SSL3_RECORD_release (SSL3_RECORD *r, size_t num_recs)
void SSL3_RECORD_set_seq_num (SSL3_RECORD *r, const unsigned char *seq_num)
int ssl3_get_record (SSL *s)
int ssl3_do_uncompress (SSL *ssl, SSL3_RECORD *rr)
int ssl3_do_compress (SSL *ssl, SSL3_RECORD *wr)
int ssl3_enc (SSL *s, SSL3_RECORD *inrecs, size_t n_recs, int send)
int tls1_enc (SSL *s, SSL3_RECORD *recs, size_t n_recs, int send)
int n_ssl3_mac (SSL *ssl, SSL3_RECORD *rec, unsigned char *md, int send)
int tls1_mac (SSL *ssl, SSL3_RECORD *rec, unsigned char *md, int send)
int ssl3_cbc_remove_padding (SSL3_RECORD *rec, size_t block_size, size_t mac_size)
int tls1_cbc_remove_padding (const SSL *s, SSL3_RECORD *rec, size_t block_size, size_t mac_size)
void ssl3_cbc_copy_mac (unsigned char *out, const SSL3_RECORD *rec, size_t md_size)
int dtls1_process_record (SSL *s, DTLS1_BITMAP *bitmap)
int dtls1_get_record (SSL *s)
Macro Definition Documentation
CBC_MAC_ROTATE_IN_PLACE
#define CBC_MAC_ROTATE_IN_PLACE
Definition at line 1296 of file ssl3_record.c.
dtls1_get_processed_record
#define dtls1_get_processed_record (s)
Value:
dtls1_retrieve_buffered_record((s), \
                   &(DTLS_RECORD_LAYER_get_processed_rcds(&s->rlayer)))
Definition at line 1571 of file ssl3_record.c.
Referenced by dtls1_get_record().
MAX_EMPTY_RECORDS
#define MAX_EMPTY_RECORDS 32
Definition at line 110 of file ssl3_record.c.
MAX_PADDING
#define MAX_PADDING 256
Definition at line 721 of file ssl3_record.c.
SSL2_RT_HEADER_LENGTH
#define SSL2_RT_HEADER_LENGTH 2
Definition at line 112 of file ssl3_record.c.
Function Documentation
dtls1_get_record()
int dtls1_get_record (SSL * s)
Definition at line 1585 of file ssl3_record.c.
References BIO_dgram_is_sctp(), dtls1_buffer_record(), dtls1_get_bitmap(), dtls1_get_processed_record, dtls1_process_buffered_records(), dtls1_process_record(), dtls1_record_replay_check(), DTLS1_RT_HEADER_LENGTH, DTLS_RECORD_LAYER_get_unprocessed_rcds, SSL3_RECORD::epoch, SSL3_RECORD::length, n2s, NULL, ossl_statem_get_in_handshake(), RECORD_LAYER_get_packet, RECORD_LAYER_get_packet_length, RECORD_LAYER_get_read_sequence, RECORD_LAYER_get_rrec, RECORD_LAYER_get_rstate, RECORD_LAYER_reset_packet_length, RECORD_LAYER_set_rstate, SSL3_RECORD::seq_num, SSL3_BUFFER_get_len, ssl3_read_n(), SSL3_RT_HEADER, SSL3_RT_MAX_ENCRYPTED_LENGTH, SSL_get_rbio(), SSL_in_init(), SSL_ST_READ_BODY, SSL_ST_READ_HEADER, and SSL3_RECORD::type.
dtls1_process_record()
int dtls1_process_record (SSL * s, DTLS1_BITMAP * bitmap)
Definition at line 1370 of file ssl3_record.c.
Referenced by dtls1_get_record(), and dtls1_process_buffered_records().
n_ssl3_mac()
int n_ssl3_mac (SSL * ssl, SSL3_RECORD * rec, unsigned char * md, int send)
Definition at line 949 of file ssl3_record.c.
ssl3_cbc_copy_mac()
void ssl3_cbc_copy_mac (unsigned char * out, const SSL3_RECORD * rec, size_t md_size)
Definition at line 1298 of file ssl3_record.c.
ssl3_cbc_remove_padding()
int ssl3_cbc_remove_padding (SSL3_RECORD * rec, size_t block_size, size_t mac_size)
Definition at line 1178 of file ssl3_record.c.
References SSL3_RECORD::data, and SSL3_RECORD::length.
Referenced by ssl3_enc().
ssl3_do_compress()
int ssl3_do_compress (SSL * ssl, SSL3_RECORD * wr)
Definition at line 616 of file ssl3_record.c.
References COMP_compress_block(), SSL3_RECORD::data, SSL3_RECORD::input, SSL3_RECORD::length, and SSL3_RT_MAX_COMPRESSED_OVERHEAD.
ssl3_do_uncompress()
int ssl3_do_uncompress (SSL * ssl, SSL3_RECORD * rr)
Definition at line 592 of file ssl3_record.c.
References SSL3_RECORD::comp, COMP_expand_block(), SSL3_RECORD::data, SSL3_RECORD::length, NULL, OPENSSL_malloc, SSL3_RT_MAX_ENCRYPTED_LENGTH, and SSL3_RT_MAX_PLAIN_LENGTH.
ssl3_enc()
int ssl3_enc (SSL * s, SSL3_RECORD * inrecs, size_t n_recs, int send)
Definition at line 645 of file ssl3_record.c.
References SSL3_RECORD::data, EVP_Cipher(), EVP_CIPHER_CTX_block_size(), EVP_CIPHER_CTX_cipher(), EVP_MD_CTX_md(), EVP_MD_CTX_size, SSL3_RECORD::input, SSL3_RECORD::length, NULL, and ssl3_cbc_remove_padding().
ssl3_get_record()
int ssl3_get_record (SSL * s)
Definition at line 126 of file ssl3_record.c.
SSL3_RECORD_clear()
void SSL3_RECORD_clear (SSL3_RECORD * r, size_t num_recs)
Definition at line 37 of file ssl3_record.c.
References SSL3_RECORD::comp.
Referenced by RECORD_LAYER_clear(), and RECORD_LAYER_init().
SSL3_RECORD_release()
void SSL3_RECORD_release (SSL3_RECORD * r, size_t num_recs)
Definition at line 50 of file ssl3_record.c.
References SSL3_RECORD::comp, NULL, and OPENSSL_free.
Referenced by RECORD_LAYER_release().
SSL3_RECORD_set_seq_num()
void SSL3_RECORD_set_seq_num (SSL3_RECORD * r, const unsigned char * seq_num)
Definition at line 60 of file ssl3_record.c.
References SSL3_RECORD::seq_num, and SEQ_NUM_SIZE.
tls1_cbc_remove_padding()
int tls1_cbc_remove_padding (const SSL * s, SSL3_RECORD * rec, size_t block_size, size_t mac_size)
Definition at line 1212 of file ssl3_record.c.
References SSL3_RECORD::data, EVP_CIPH_FLAG_AEAD_CIPHER, EVP_CIPHER_CTX_cipher(), EVP_CIPHER_flags(), SSL3_RECORD::input, SSL3_RECORD::length, SSL3_RECORD::orig_len, and SSL_USE_EXPLICIT_IV.
tls1_enc()
int tls1_enc (SSL * s, SSL3_RECORD * recs, size_t n_recs, int send)
Definition at line 732 of file ssl3_record.c.
References SSL_MAX_PIPELINES.
tls1_mac()
int tls1_mac (SSL * ssl, SSL3_RECORD * rec, unsigned char * md, int send)
Definition at line 1045 of file ssl3_record.c.