ssl/record/ssl3_buffer.c File Reference
ssl3_buffer.c File Reference
#include "../ssl_locl.h"
#include "record_locl.h"
Functions
void SSL3_BUFFER_set_data (SSL3_BUFFER *b, const unsigned char *d, size_t n)
void SSL3_BUFFER_clear (SSL3_BUFFER *b)
void SSL3_BUFFER_release (SSL3_BUFFER *b)
int ssl3_setup_read_buffer (SSL *s)
int ssl3_setup_write_buffer (SSL *s, size_t numwpipes, size_t len)
int ssl3_setup_buffers (SSL *s)
int ssl3_release_write_buffer (SSL *s)
int ssl3_release_read_buffer (SSL *s)
Function Documentation
SSL3_BUFFER_clear()
void SSL3_BUFFER_clear (SSL3_BUFFER * b)
Definition at line 25 of file ssl3_buffer.c.
References SSL3_BUFFER::left, and SSL3_BUFFER::offset.
Referenced by RECORD_LAYER_clear().
SSL3_BUFFER_release()
void SSL3_BUFFER_release (SSL3_BUFFER * b)
Definition at line 31 of file ssl3_buffer.c.
References SSL3_BUFFER::buf, NULL, and OPENSSL_free.
SSL3_BUFFER_set_data()
void SSL3_BUFFER_set_data (SSL3_BUFFER * b, const unsigned char * d, size_t n)
Definition at line 13 of file ssl3_buffer.c.
References SSL3_BUFFER::buf, SSL3_BUFFER::left, NULL, and SSL3_BUFFER::offset.
ssl3_release_read_buffer()
int ssl3_release_read_buffer (SSL * s)
Definition at line 155 of file ssl3_buffer.c.
References SSL3_BUFFER::buf, NULL, OPENSSL_free, and RECORD_LAYER_get_rbuf.
Referenced by RECORD_LAYER_release().
ssl3_release_write_buffer()
int ssl3_release_write_buffer (SSL * s)
Definition at line 138 of file ssl3_buffer.c.
References SSL3_BUFFER::buf, NULL, OPENSSL_free, and RECORD_LAYER_get_wbuf.
Referenced by RECORD_LAYER_clear(), and RECORD_LAYER_release().
ssl3_setup_buffers()
int ssl3_setup_buffers (SSL * s)
Definition at line 129 of file ssl3_buffer.c.
References ssl3_setup_read_buffer(), and ssl3_setup_write_buffer().
Referenced by dtls1_buffer_record().
ssl3_setup_read_buffer()
int ssl3_setup_read_buffer (SSL * s)
Definition at line 37 of file ssl3_buffer.c.
References SSL3_BUFFER::buf, SSL3_BUFFER::default_len, DTLS1_RT_HEADER_LENGTH, ERR_R_MALLOC_FAILURE, SSL3_BUFFER::len, len, NULL, OPENSSL_malloc, RECORD_LAYER_get_rbuf, RECORD_LAYER_set_packet, SSL3_ALIGN_PAYLOAD, SSL3_RT_HEADER_LENGTH, SSL3_RT_MAX_COMPRESSED_OVERHEAD, SSL3_RT_MAX_ENCRYPTED_OVERHEAD, SSL3_RT_MAX_PLAIN_LENGTH, ssl_allow_compression(), SSL_F_SSL3_SETUP_READ_BUFFER, SSL_IS_DTLS, and SSLerr.
Referenced by ssl3_read_n(), and ssl3_setup_buffers().
ssl3_setup_write_buffer()
int ssl3_setup_write_buffer (SSL * s, size_t numwpipes, size_t len)
Definition at line 77 of file ssl3_buffer.c.
References SSL3_BUFFER::buf, DTLS1_RT_HEADER_LENGTH, ERR_R_MALLOC_FAILURE, SSL3_BUFFER::len, len, NULL, OPENSSL_malloc, RECORD_LAYER_get_wbuf, SSL3_ALIGN_PAYLOAD, SSL3_RT_HEADER_LENGTH, SSL3_RT_MAX_COMPRESSED_OVERHEAD, SSL3_RT_SEND_MAX_ENCRYPTED_OVERHEAD, ssl_allow_compression(), SSL_F_SSL3_SETUP_WRITE_BUFFER, SSL_IS_DTLS, SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS, and SSLerr.
Referenced by ssl3_setup_buffers().