ssl/ssl_locl.h File Reference
ssl_locl.h File Reference
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <errno.h>
#include "e_os.h"
#include <openssl/buffer.h>
#include <openssl/comp.h>
#include <openssl/bio.h>
#include <openssl/stack.h>
#include <openssl/rsa.h>
#include <openssl/dsa.h>
#include <openssl/err.h>
#include <openssl/ssl.h>
#include <openssl/async.h>
#include <openssl/symhacks.h>
#include <openssl/ct.h>
#include "record/record.h"
#include "statem/statem.h"
#include "packet_locl.h"
#include "internal/dane.h"
#include "internal/refcount.h"
Data Structures
struct SSL_CIPHER
struct SSL_METHOD
struct SSL_SESSION
struct SRP_CTX
struct SSL_COMP
struct SSL_CTX
struct ssl_crock_st
struct SIGALG_LOOKUP
struct SSL3_STATE
struct dtls1_retransmit_state
struct hm_header_st
struct dtls1_timeout_st
struct hm_fragment
struct piterator
struct DTLS1_STATE
struct CERT_PKEY
struct custom_ext_method
struct custom_ext_methods
struct CERT
struct SSL3_ENC_METHOD
struct SSL3_COMP
struct RAW_EXTENSION
struct CLIENTHELLO_MSG
struct openssl_ssl_test_functions
Macros
#define c2l(c, l)
#define c2ln(c, l1, l2, n)
#define l2c(l, c)
#define n2l(c, l)
#define n2l8(c, l)
#define l2n(l, c)
#define l2n6(l, c)
#define l2n8(l, c)
#define l2cn(l1, l2, c, n)
#define n2s(c, s)
#define s2n(s, c)
#define n2l3(c, l)
#define l2n3(l, c)
#define dtls_ver_ordinal(v1) (((v1) == DTLS1_BAD_VER) ? 0xff00 : (v1))
#define DTLS_VERSION_GT(v1, v2) (dtls_ver_ordinal(v1) < dtls_ver_ordinal(v2))
#define DTLS_VERSION_GE(v1, v2) (dtls_ver_ordinal(v1) <= dtls_ver_ordinal(v2))
#define DTLS_VERSION_LT(v1, v2) (dtls_ver_ordinal(v1) > dtls_ver_ordinal(v2))
#define DTLS_VERSION_LE(v1, v2) (dtls_ver_ordinal(v1) >= dtls_ver_ordinal(v2))
#define SSL_DECRYPT 0
#define SSL_ENCRYPT 1
#define TWO_BYTE_BIT 0x80
#define SEC_ESC_BIT 0x40
#define TWO_BYTE_MASK 0x7fff
#define THREE_BYTE_MASK 0x3fff
#define INC32(a) ((a)=((a)+1)&0xffffffffL)
#define DEC32(a) ((a)=((a)-1)&0xffffffffL)
#define MAX_MAC_SIZE 20 /* up from 16 for SSLv3 */
#define SSL_kRSA 0x00000001U
#define SSL_kDHE 0x00000002U
#define SSL_kEDH SSL_kDHE
#define SSL_kECDHE 0x00000004U
#define SSL_kEECDH SSL_kECDHE
#define SSL_kPSK 0x00000008U
#define SSL_kGOST 0x00000010U
#define SSL_kSRP 0x00000020U
#define SSL_kRSAPSK 0x00000040U
#define SSL_kECDHEPSK 0x00000080U
#define SSL_kDHEPSK 0x00000100U
#define SSL_PSK (SSL_kPSK | SSL_kRSAPSK | SSL_kECDHEPSK | SSL_kDHEPSK)
#define SSL_kANY 0x00000000U
#define SSL_aRSA 0x00000001U
#define SSL_aDSS 0x00000002U
#define SSL_aNULL 0x00000004U
#define SSL_aECDSA 0x00000008U
#define SSL_aPSK 0x00000010U
#define SSL_aGOST01 0x00000020U
#define SSL_aSRP 0x00000040U
#define SSL_aGOST12 0x00000080U
#define SSL_aANY 0x00000000U
#define SSL_DES 0x00000001U
#define SSL_3DES 0x00000002U
#define SSL_RC4 0x00000004U
#define SSL_RC2 0x00000008U
#define SSL_IDEA 0x00000010U
#define SSL_eNULL 0x00000020U
#define SSL_AES128 0x00000040U
#define SSL_AES256 0x00000080U
#define SSL_CAMELLIA128 0x00000100U
#define SSL_CAMELLIA256 0x00000200U
#define SSL_eGOST2814789CNT 0x00000400U
#define SSL_SEED 0x00000800U
#define SSL_AES128GCM 0x00001000U
#define SSL_AES256GCM 0x00002000U
#define SSL_AES128CCM 0x00004000U
#define SSL_AES256CCM 0x00008000U
#define SSL_AES128CCM8 0x00010000U
#define SSL_AES256CCM8 0x00020000U
#define SSL_eGOST2814789CNT12 0x00040000U
#define SSL_CHACHA20POLY1305 0x00080000U
#define SSL_AESGCM (SSL_AES128GCM | SSL_AES256GCM)
#define SSL_AESCCM (SSL_AES128CCM | SSL_AES256CCM | SSL_AES128CCM8 | SSL_AES256CCM8)
#define SSL_AES (SSL_AES128|SSL_AES256|SSL_AESGCM|SSL_AESCCM)
#define SSL_CAMELLIA (SSL_CAMELLIA128|SSL_CAMELLIA256)
#define SSL_CHACHA20 (SSL_CHACHA20POLY1305)
#define SSL_MD5 0x00000001U
#define SSL_SHA1 0x00000002U
#define SSL_GOST94 0x00000004U
#define SSL_GOST89MAC 0x00000008U
#define SSL_SHA256 0x00000010U
#define SSL_SHA384 0x00000020U
#define SSL_AEAD 0x00000040U
#define SSL_GOST12_256 0x00000080U
#define SSL_GOST89MAC12 0x00000100U
#define SSL_GOST12_512 0x00000200U
#define SSL_MD_MD5_IDX 0
#define SSL_MD_SHA1_IDX 1
#define SSL_MD_GOST94_IDX 2
#define SSL_MD_GOST89MAC_IDX 3
#define SSL_MD_SHA256_IDX 4
#define SSL_MD_SHA384_IDX 5
#define SSL_MD_GOST12_256_IDX 6
#define SSL_MD_GOST89MAC12_IDX 7
#define SSL_MD_GOST12_512_IDX 8
#define SSL_MD_MD5_SHA1_IDX 9
#define SSL_MD_SHA224_IDX 10
#define SSL_MD_SHA512_IDX 11
#define SSL_MAX_DIGEST 12
#define SSL_HANDSHAKE_MAC_MASK 0xFF
#define SSL_HANDSHAKE_MAC_MD5_SHA1 SSL_MD_MD5_SHA1_IDX
#define SSL_HANDSHAKE_MAC_SHA256 SSL_MD_SHA256_IDX
#define SSL_HANDSHAKE_MAC_SHA384 SSL_MD_SHA384_IDX
#define SSL_HANDSHAKE_MAC_GOST94 SSL_MD_GOST94_IDX
#define SSL_HANDSHAKE_MAC_GOST12_256 SSL_MD_GOST12_256_IDX
#define SSL_HANDSHAKE_MAC_GOST12_512 SSL_MD_GOST12_512_IDX
#define SSL_HANDSHAKE_MAC_DEFAULT SSL_HANDSHAKE_MAC_MD5_SHA1
#define TLS1_PRF_DGST_SHIFT 8
#define TLS1_PRF_SHA1_MD5 (SSL_MD_MD5_SHA1_IDX << TLS1_PRF_DGST_SHIFT)
#define TLS1_PRF_SHA256 (SSL_MD_SHA256_IDX << TLS1_PRF_DGST_SHIFT)
#define TLS1_PRF_SHA384 (SSL_MD_SHA384_IDX << TLS1_PRF_DGST_SHIFT)
#define TLS1_PRF_GOST94 (SSL_MD_GOST94_IDX << TLS1_PRF_DGST_SHIFT)
#define TLS1_PRF_GOST12_256 (SSL_MD_GOST12_256_IDX << TLS1_PRF_DGST_SHIFT)
#define TLS1_PRF_GOST12_512 (SSL_MD_GOST12_512_IDX << TLS1_PRF_DGST_SHIFT)
#define TLS1_PRF (SSL_MD_MD5_SHA1_IDX << TLS1_PRF_DGST_SHIFT)
#define TLS1_STREAM_MAC 0x10000
#define SSL_STRONG_MASK 0x0000001FU
#define SSL_DEFAULT_MASK 0X00000020U
#define SSL_STRONG_NONE 0x00000001U
#define SSL_LOW 0x00000002U
#define SSL_MEDIUM 0x00000004U
#define SSL_HIGH 0x00000008U
#define SSL_FIPS 0x00000010U
#define SSL_NOT_DEFAULT 0x00000020U
#define SSL3_CK_CIPHERSUITE_FLAG 0x03000000
#define SSL_IS_DTLS(s) (s->method->ssl3_enc->enc_flags & SSL_ENC_FLAG_DTLS)
#define SSL_IS_TLS13(s)
#define SSL_IS_FIRST_HANDSHAKE(S) ((s)->s3->tmp.finish_md_len == 0)
#define SSL_USE_EXPLICIT_IV(s) (s->method->ssl3_enc->enc_flags & SSL_ENC_FLAG_EXPLICIT_IV)
#define SSL_USE_SIGALGS(s) (s->method->ssl3_enc->enc_flags & SSL_ENC_FLAG_SIGALGS)
#define SSL_USE_TLS1_2_CIPHERS(s) (s->method->ssl3_enc->enc_flags & SSL_ENC_FLAG_TLS1_2_CIPHERS)
#define SSL_CLIENT_USE_TLS1_2_CIPHERS(s)
#define SSL_CLIENT_USE_SIGALGS(s) SSL_CLIENT_USE_TLS1_2_CIPHERS(s)
#define SSL_READ_ETM(s) (s->s3->flags & TLS1_FLAGS_ENCRYPT_THEN_MAC_READ)
#define SSL_WRITE_ETM(s) (s->s3->flags & TLS1_FLAGS_ENCRYPT_THEN_MAC_WRITE)
#define SSL_PKEY_RSA 0
#define SSL_PKEY_DSA_SIGN 1
#define SSL_PKEY_ECC 2
#define SSL_PKEY_GOST01 3
#define SSL_PKEY_GOST12_256 4
#define SSL_PKEY_GOST12_512 5
#define SSL_PKEY_NUM 6
#define SSL_PKEY_GOST_EC SSL_PKEY_NUM+1
#define SSL_PKEY_RSA_PSS_SIGN SSL_PKEY_RSA
#define TLS_CIPHER_LEN 2
#define SSL_SESS_FLAG_EXTMS 0x1
#define TLSEXT_KEYNAME_LENGTH 16
#define DTLS1_SCTP_AUTH_LABEL "EXPORTER_DTLS_OVER_SCTP"
#define DTLS1_MAX_MTU_OVERHEAD 48
#define DTLS1_SKIP_RECORD_HEADER 2
#define EXPLICIT_PRIME_CURVE_TYPE 1
#define EXPLICIT_CHAR2_CURVE_TYPE 2
#define NAMED_CURVE_TYPE 3
#define tls1_suiteb(s) (s->cert->cert_flags & SSL_CERT_FLAG_SUITEB_128_LOS)
#define SSL_CERT_FLAGS_CHECK_TLS_STRICT (SSL_CERT_FLAG_SUITEB_128_LOS|SSL_CERT_FLAG_TLS_STRICT)
#define SSL_EXT_FLAG_RECEIVED 0x1
#define SSL_EXT_FLAG_SENT 0x2
#define FP_ICC (int (*)(const void *,const void *))
#define ssl_set_handshake_header(s, pkt, htype) s->method->ssl3_enc->set_handshake_header((s), (pkt), (htype))
#define ssl_close_construct_packet(s, pkt, htype) s->method->ssl3_enc->close_construct_packet((s), (pkt), (htype))
#define ssl_do_write(s) s->method->ssl3_enc->do_write(s)
#define SSL_ENC_FLAG_EXPLICIT_IV 0x1
#define SSL_ENC_FLAG_SIGALGS 0x2
#define SSL_ENC_FLAG_SHA256_PRF 0x4
#define SSL_ENC_FLAG_DTLS 0x8
#define SSL_ENC_FLAG_TLS1_2_CIPHERS 0x10
#define TLSEXT_STATUSTYPE_nothing -1
#define TLSEXT_SIGALG_ecdsa_secp256r1_sha256 0x0403
#define TLSEXT_SIGALG_ecdsa_secp384r1_sha384 0x0503
#define TLSEXT_SIGALG_ecdsa_secp521r1_sha512 0x0603
#define TLSEXT_SIGALG_ecdsa_sha1 0x0203
#define TLSEXT_SIGALG_rsa_pss_sha256 0x0804
#define TLSEXT_SIGALG_rsa_pss_sha384 0x0805
#define TLSEXT_SIGALG_rsa_pss_sha512 0x0806
#define TLSEXT_SIGALG_rsa_pkcs1_sha256 0x0401
#define TLSEXT_SIGALG_rsa_pkcs1_sha384 0x0501
#define TLSEXT_SIGALG_rsa_pkcs1_sha512 0x0601
#define TLSEXT_SIGALG_rsa_pkcs1_sha1 0x0201
#define TLSEXT_SIGALG_dsa_sha256 0x0402
#define TLSEXT_SIGALG_dsa_sha384 0x0502
#define TLSEXT_SIGALG_dsa_sha512 0x0602
#define TLSEXT_SIGALG_dsa_sha1 0x0202
#define TLSEXT_SIGALG_gostr34102012_256_gostr34112012_256 0xeeee
#define TLSEXT_SIGALG_gostr34102012_512_gostr34112012_512 0xefef
#define TLSEXT_SIGALG_gostr34102001_gostr3411 0xeded
#define TLSEXT_KEX_MODE_KE 0x00
#define TLSEXT_KEX_MODE_KE_DHE 0x01
#define TLSEXT_KEX_MODE_FLAG_NONE 0
#define TLSEXT_KEX_MODE_FLAG_KE 1
#define TLSEXT_KEX_MODE_FLAG_KE_DHE 2
#define TLSEXT_PSK_BAD_IDENTITY -1
#define SSL_USE_PSS(s)
#define TLSEXT_signature_rsa_pss 0x0101
#define MAX_COMPRESSIONS_SIZE 255
#define SSL_METHOD_NO_FIPS (1U<<0)
#define SSL_METHOD_NO_SUITEB (1U<<1)
#define IMPLEMENT_tls_meth_func(version, flags, mask, func_name, s_accept, s_connect, enc_data)
#define IMPLEMENT_ssl3_meth_func(func_name, s_accept, s_connect)
#define IMPLEMENT_dtls1_meth_func(version, flags, mask, func_name, s_accept, s_connect, enc_data)
#define TLS_CURVE_TYPE 0x3
#define TLS_CURVE_PRIME 0x0
#define TLS_CURVE_CHAR2 0x1
#define TLS_CURVE_CUSTOM 0x2
#define bytestogroup(bytes) ((unsigned int)(bytes[0] << 8 | bytes[1]))
#define MASTER_SECRET_LABEL "CLIENT_RANDOM"
#define CLIENT_HANDSHAKE_LABEL "CLIENT_HANDSHAKE_TRAFFIC_SECRET"
#define SERVER_HANDSHAKE_LABEL "SERVER_HANDSHAKE_TRAFFIC_SECRET"
#define CLIENT_APPLICATION_LABEL "CLIENT_TRAFFIC_SECRET_0"
#define SERVER_APPLICATION_LABEL "SERVER_TRAFFIC_SECRET_0"
Enumerations
enum TLSEXT_INDEX {
TLSEXT_IDX_renegotiate, TLSEXT_IDX_server_name, TLSEXT_IDX_srp, TLSEXT_IDX_ec_point_formats,
TLSEXT_IDX_supported_groups, TLSEXT_IDX_session_ticket, TLSEXT_IDX_signature_algorithms, TLSEXT_IDX_status_request,
TLSEXT_IDX_next_proto_neg, TLSEXT_IDX_application_layer_protocol_negotiation, TLSEXT_IDX_use_srtp, TLSEXT_IDX_encrypt_then_mac,
TLSEXT_IDX_signed_certificate_timestamp, TLSEXT_IDX_extended_master_secret, TLSEXT_IDX_supported_versions, TLSEXT_IDX_psk_kex_modes,
TLSEXT_IDX_key_share, TLSEXT_IDX_cryptopro_bug, TLSEXT_IDX_padding, TLSEXT_IDX_psk
}
enum TICKET_RETURN {
TICKET_FATAL_ERR_MALLOC, TICKET_FATAL_ERR_OTHER, TICKET_NONE, TICKET_EMPTY,
TICKET_NO_DECRYPT, TICKET_SUCCESS, TICKET_SUCCESS_RENEW
}
Functions
DEFINE_LHASH_OF (SSL_SESSION)
DEFINE_LHASH_OF (X509_NAME)
pitem * pitem_new (unsigned char *prio64be, void *data)
void pitem_free (pitem *item)
pqueue * pqueue_new (void)
void pqueue_free (pqueue *pq)
pitem * pqueue_insert (pqueue *pq, pitem *item)
pitem * pqueue_peek (pqueue *pq)
pitem * pqueue_pop (pqueue *pq)
pitem * pqueue_find (pqueue *pq, unsigned char *prio64be)
pitem * pqueue_iterator (pqueue *pq)
pitem * pqueue_next (piterator *iter)
size_t pqueue_size (pqueue *pq)
__owur const SSL_METHOD * ssl_bad_method (int ver)
__owur const SSL_METHOD * sslv3_method (void)
__owur const SSL_METHOD * sslv3_server_method (void)
__owur const SSL_METHOD * sslv3_client_method (void)
__owur const SSL_METHOD * tlsv1_method (void)
__owur const SSL_METHOD * tlsv1_server_method (void)
__owur const SSL_METHOD * tlsv1_client_method (void)
__owur const SSL_METHOD * tlsv1_1_method (void)
__owur const SSL_METHOD * tlsv1_1_server_method (void)
__owur const SSL_METHOD * tlsv1_1_client_method (void)
__owur const SSL_METHOD * tlsv1_2_method (void)
__owur const SSL_METHOD * tlsv1_2_server_method (void)
__owur const SSL_METHOD * tlsv1_2_client_method (void)
__owur const SSL_METHOD * tlsv1_3_method (void)
__owur const SSL_METHOD * tlsv1_3_server_method (void)
__owur const SSL_METHOD * tlsv1_3_client_method (void)
__owur const SSL_METHOD * dtlsv1_method (void)
__owur const SSL_METHOD * dtlsv1_server_method (void)
__owur const SSL_METHOD * dtlsv1_client_method (void)
__owur const SSL_METHOD * dtls_bad_ver_client_method (void)
__owur const SSL_METHOD * dtlsv1_2_method (void)
__owur const SSL_METHOD * dtlsv1_2_server_method (void)
__owur const SSL_METHOD * dtlsv1_2_client_method (void)
const char * ssl_protocol_to_string (int version)
void ssl_clear_cipher_ctx (SSL *s)
int ssl_clear_bad_session (SSL *s)
__owur CERT * ssl_cert_new (void)
__owur CERT * ssl_cert_dup (CERT *cert)
void ssl_cert_clear_certs (CERT *c)
void ssl_cert_free (CERT *c)
__owur int ssl_get_new_session (SSL *s, int session)
__owur int ssl_get_prev_session (SSL *s, CLIENTHELLO_MSG *hello, int *al)
__owur SSL_SESSION * ssl_session_dup (SSL_SESSION *src, int ticket)
__owur int ssl_cipher_id_cmp (const SSL_CIPHER *a, const SSL_CIPHER *b)
DECLARE_OBJ_BSEARCH_GLOBAL_CMP_FN (SSL_CIPHER, SSL_CIPHER, ssl_cipher_id)
__owur int ssl_cipher_ptr_id_cmp (const SSL_CIPHER *const *ap, const SSL_CIPHER *const *bp)
__owur STACK_OF (SSL_CIPHER) *ssl_create_cipher_list(const SSL_METHOD *meth
void ssl_update_cache (SSL *s, int mode)
__owur int ssl_cipher_get_evp (const SSL_SESSION *s, const EVP_CIPHER **enc, const EVP_MD **md, int *mac_pkey_type, size_t *mac_secret_size, SSL_COMP **comp, int use_etm)
__owur int ssl_cipher_get_overhead (const SSL_CIPHER *c, size_t *mac_overhead, size_t *int_overhead, size_t *blocksize, size_t *ext_overhead)
__owur int ssl_cipher_get_cert_index (const SSL_CIPHER *c)
__owur const SSL_CIPHER * ssl_get_cipher_by_char (SSL *ssl, const unsigned char *ptr)
__owur int ssl_cert_set0_chain (SSL *s, SSL_CTX *ctx, STACK_OF(X509) *chain)
__owur int ssl_cert_set1_chain (SSL *s, SSL_CTX *ctx, STACK_OF(X509) *chain)
__owur int ssl_cert_add0_chain_cert (SSL *s, SSL_CTX *ctx, X509 *x)
__owur int ssl_cert_add1_chain_cert (SSL *s, SSL_CTX *ctx, X509 *x)
__owur int ssl_cert_select_current (CERT *c, X509 *x)
__owur int ssl_cert_set_current (CERT *c, long arg)
__owur X509 * ssl_cert_get0_next_certificate (CERT *c, int first)
void ssl_cert_set_cert_cb (CERT *c, int(*cb)(SSL *ssl, void *arg), void *arg)
__owur int ssl_verify_cert_chain (SSL *s, STACK_OF(X509) *sk)
__owur int ssl_build_cert_chain (SSL *s, SSL_CTX *ctx, int flags)
__owur int ssl_cert_set_cert_store (CERT *c, X509_STORE *store, int chain, int ref)
__owur int ssl_security (const SSL *s, int op, int bits, int nid, void *other)
__owur int ssl_ctx_security (const SSL_CTX *ctx, int op, int bits, int nid, void *other)
int ssl_undefined_function (SSL *s)
__owur int ssl_undefined_void_function (void)
__owur int ssl_undefined_const_function (const SSL *s)
__owur int ssl_get_server_cert_serverinfo (SSL *s, const unsigned char **serverinfo, size_t *serverinfo_length)
__owur int ssl_cert_type (const X509 *x, const EVP_PKEY *pkey)
void ssl_set_masks (SSL *s)
__owur int ssl_verify_alarm_type (long type)
void ssl_sort_cipher_list (void)
void ssl_load_ciphers (void)
__owur int ssl_fill_hello_random (SSL *s, int server, unsigned char *field, size_t len)
__owur int ssl_generate_master_secret (SSL *s, unsigned char *pms, size_t pmslen, int free_pms)
__owur EVP_PKEY * ssl_generate_pkey (EVP_PKEY *pm)
__owur int ssl_derive (SSL *s, EVP_PKEY *privkey, EVP_PKEY *pubkey, int genmaster)
__owur EVP_PKEY * ssl_dh_to_pkey (DH *dh)
__owur const SSL_CIPHER * ssl3_get_cipher_by_id (uint32_t id)
__owur const SSL_CIPHER * ssl3_get_cipher_by_char (const unsigned char *p)
__owur int ssl3_put_cipher_by_char (const SSL_CIPHER *c, WPACKET *pkt, size_t *len)
int ssl3_init_finished_mac (SSL *s)
__owur int ssl3_setup_key_block (SSL *s)
__owur int ssl3_change_cipher_state (SSL *s, int which)
void ssl3_cleanup_key_block (SSL *s)
__owur int ssl3_do_write (SSL *s, int type)
int ssl3_send_alert (SSL *s, int level, int desc)
__owur int ssl3_generate_master_secret (SSL *s, unsigned char *out, unsigned char *p, size_t len, size_t *secret_size)
__owur int ssl3_get_req_cert_type (SSL *s, WPACKET *pkt)
__owur int ssl3_num_ciphers (void)
__owur const SSL_CIPHER * ssl3_get_cipher (unsigned int u)
int ssl3_renegotiate (SSL *ssl)
int ssl3_renegotiate_check (SSL *ssl, int initok)
__owur int ssl3_dispatch_alert (SSL *s)
__owur size_t ssl3_final_finish_mac (SSL *s, const char *sender, size_t slen, unsigned char *p)
__owur int ssl3_finish_mac (SSL *s, const unsigned char *buf, size_t len)
void ssl3_free_digest_list (SSL *s)
__owur unsigned long ssl3_output_cert_chain (SSL *s, WPACKET *pkt, CERT_PKEY *cpk, int *al)
__owur const SSL_CIPHER * ssl3_choose_cipher (SSL *ssl, STACK_OF(SSL_CIPHER) *clnt, STACK_OF(SSL_CIPHER) *srvr)
__owur int ssl3_digest_cached_records (SSL *s, int keep)
__owur int ssl3_new (SSL *s)
void ssl3_free (SSL *s)
__owur int ssl3_read (SSL *s, void *buf, size_t len, size_t *readbytes)
__owur int ssl3_peek (SSL *s, void *buf, size_t len, size_t *readbytes)
__owur int ssl3_write (SSL *s, const void *buf, size_t len, size_t *written)
__owur int ssl3_shutdown (SSL *s)
void ssl3_clear (SSL *s)
__owur long ssl3_ctrl (SSL *s, int cmd, long larg, void *parg)
__owur long ssl3_ctx_ctrl (SSL_CTX *s, int cmd, long larg, void *parg)
__owur long ssl3_callback_ctrl (SSL *s, int cmd, void(*fp)(void))
__owur long ssl3_ctx_callback_ctrl (SSL_CTX *s, int cmd, void(*fp)(void))
__owur int ssl3_do_change_cipher_spec (SSL *ssl)
__owur long ssl3_default_timeout (void)
__owur int ssl3_set_handshake_header (SSL *s, WPACKET *pkt, int htype)
__owur int tls_close_construct_packet (SSL *s, WPACKET *pkt, int htype)
__owur int tls_setup_handshake (SSL *s)
__owur int dtls1_set_handshake_header (SSL *s, WPACKET *pkt, int htype)
__owur int dtls1_close_construct_packet (SSL *s, WPACKET *pkt, int htype)
__owur int ssl3_handshake_write (SSL *s)
__owur int ssl_allow_compression (SSL *s)
__owur int ssl_version_supported (const SSL *s, int version)
__owur int ssl_set_client_hello_version (SSL *s)
__owur int ssl_check_version_downgrade (SSL *s)
__owur int ssl_set_version_bound (int method_version, int version, int *bound)
__owur int ssl_choose_server_version (SSL *s, CLIENTHELLO_MSG *hello)
__owur int ssl_choose_client_version (SSL *s, int version)
int ssl_get_client_min_max_version (const SSL *s, int *min_version, int *max_version)
__owur long tls1_default_timeout (void)
__owur int dtls1_do_write (SSL *s, int type)
void dtls1_set_message_header (SSL *s, unsigned char mt, size_t len, size_t frag_off, size_t frag_len)
int dtls1_write_app_data_bytes (SSL *s, int type, const void *buf_, size_t len, size_t *written)
__owur int dtls1_read_failed (SSL *s, int code)
__owur int dtls1_buffer_message (SSL *s, int ccs)
__owur int dtls1_retransmit_message (SSL *s, unsigned short seq, int *found)
__owur int dtls1_get_queue_priority (unsigned short seq, int is_ccs)
int dtls1_retransmit_buffered_messages (SSL *s)
void dtls1_clear_received_buffer (SSL *s)
void dtls1_clear_sent_buffer (SSL *s)
void dtls1_get_message_header (unsigned char *data, struct hm_header_st *msg_hdr)
__owur long dtls1_default_timeout (void)
__owur struct timeval * dtls1_get_timeout (SSL *s, struct timeval *timeleft)
__owur int dtls1_check_timeout_num (SSL *s)
__owur int dtls1_handle_timeout (SSL *s)
void dtls1_start_timer (SSL *s)
void dtls1_stop_timer (SSL *s)
__owur int dtls1_is_timer_expired (SSL *s)
void dtls1_double_timeout (SSL *s)
__owur int dtls_raw_hello_verify_request (WPACKET *pkt, unsigned char *cookie, size_t cookie_len)
__owur int dtls1_send_newsession_ticket (SSL *s)
__owur size_t dtls1_min_mtu (SSL *s)
void dtls1_hm_fragment_free (hm_fragment *frag)
__owur int dtls1_query_mtu (SSL *s)
__owur int tls1_new (SSL *s)
void tls1_free (SSL *s)
void tls1_clear (SSL *s)
long tls1_ctrl (SSL *s, int cmd, long larg, void *parg)
long tls1_callback_ctrl (SSL *s, int cmd, void(*fp)(void))
__owur int dtls1_new (SSL *s)
void dtls1_free (SSL *s)
void dtls1_clear (SSL *s)
long dtls1_ctrl (SSL *s, int cmd, long larg, void *parg)
__owur int dtls1_shutdown (SSL *s)
__owur int dtls1_dispatch_alert (SSL *s)
__owur int ssl_init_wbio_buffer (SSL *s)
void ssl_free_wbio_buffer (SSL *s)
__owur int tls1_change_cipher_state (SSL *s, int which)
__owur int tls1_setup_key_block (SSL *s)
__owur size_t tls1_final_finish_mac (SSL *s, const char *str, size_t slen, unsigned char *p)
__owur int tls1_generate_master_secret (SSL *s, unsigned char *out, unsigned char *p, size_t len, size_t *secret_size)
__owur int tls13_setup_key_block (SSL *s)
__owur size_t tls13_final_finish_mac (SSL *s, const char *str, size_t slen, unsigned char *p)
__owur int tls13_change_cipher_state (SSL *s, int which)
__owur int tls13_update_key (SSL *s, int send)
__owur int tls13_hkdf_expand (SSL *s, const EVP_MD *md, const unsigned char *secret, const unsigned char *label, size_t labellen, const unsigned char *hash, unsigned char *out, size_t outlen)
__owur int tls13_derive_key (SSL *s, const unsigned char *secret, unsigned char *key, size_t keylen)
__owur int tls13_derive_iv (SSL *s, const unsigned char *secret, unsigned char *iv, size_t ivlen)
__owur int tls13_derive_finishedkey (SSL *s, const EVP_MD *md, const unsigned char *secret, unsigned char *fin, size_t finlen)
int tls13_generate_secret (SSL *s, const EVP_MD *md, const unsigned char *prevsecret, const unsigned char *insecret, size_t insecretlen, unsigned char *outsecret)
__owur int tls13_generate_handshake_secret (SSL *s, const unsigned char *insecret, size_t insecretlen)
__owur int tls13_generate_master_secret (SSL *s, unsigned char *out, unsigned char *prev, size_t prevlen, size_t *secret_size)
__owur int tls1_export_keying_material (SSL *s, unsigned char *out, size_t olen, const char *label, size_t llen, const unsigned char *p, size_t plen, int use_context)
__owur int tls1_alert_code (int code)
__owur int tls13_alert_code (int code)
__owur int ssl3_alert_code (int code)
__owur int ssl_ok (SSL *s)
__owur int ssl_check_srvr_ecc_cert_and_alg (X509 *x, SSL *s)
SSL_COMP * ssl3_comp_find (STACK_OF(SSL_COMP) *sk, int n)
__owur int tls1_ec_curve_id2nid (int curve_id, unsigned int *pflags)
__owur int tls1_ec_nid2curve_id (int nid)
__owur int tls1_check_curve (SSL *s, const unsigned char *p, size_t len)
__owur int tls1_shared_group (SSL *s, int nmatch)
__owur int tls1_set_groups (unsigned char **pext, size_t *pextlen, int *curves, size_t ncurves)
__owur int tls1_set_groups_list (unsigned char **pext, size_t *pextlen, const char *str)
void tls1_get_formatlist (SSL *s, const unsigned char **pformats, size_t *num_formats)
__owur int tls1_check_ec_tmp_key (SSL *s, unsigned long id)
__owur EVP_PKEY * ssl_generate_pkey_curve (int id)
__owur int tls1_shared_list (SSL *s, const unsigned char *l1, size_t l1len, const unsigned char *l2, size_t l2len, int nmatch)
__owur int tls_curve_allowed (SSL *s, const unsigned char *curve, int op)
__owur int tls1_get_curvelist (SSL *s, int sess, const unsigned char **pcurves, size_t *num_curves)
void ssl_set_default_md (SSL *s)
__owur int tls1_set_server_sigalgs (SSL *s)
__owur TICKET_RETURN tls_get_ticket_from_client (SSL *s, CLIENTHELLO_MSG *hello, SSL_SESSION **ret)
__owur TICKET_RETURN tls_decrypt_ticket (SSL *s, const unsigned char *etick, size_t eticklen, const unsigned char *sess_id, size_t sesslen, SSL_SESSION **psess)
__owur int tls_use_ticket (SSL *s)
void ssl_set_sig_mask (uint32_t *pmask_a, SSL *s, int op)
__owur int tls1_set_sigalgs_list (CERT *c, const char *str, int client)
__owur int tls1_set_sigalgs (CERT *c, const int *salg, size_t salglen, int client)
int tls1_check_chain (SSL *s, X509 *x, EVP_PKEY *pk, STACK_OF(X509) *chain, int idx)
void tls1_set_cert_validity (SSL *s)
__owur int ssl_validate_ct (SSL *s)
__owur DH * ssl_get_auto_dh (SSL *s)
__owur int ssl_security_cert (SSL *s, SSL_CTX *ctx, X509 *x, int vfy, int is_ee)
__owur int ssl_security_cert_chain (SSL *s, STACK_OF(X509) *sk, X509 *ex, int vfy)
int tls_choose_sigalg (SSL *s, int *al)
__owur EVP_MD_CTX * ssl_replace_hash (EVP_MD_CTX **hash, const EVP_MD *md)
void ssl_clear_hash_ctx (EVP_MD_CTX **hash)
__owur long ssl_get_algorithm2 (SSL *s)
__owur int tls12_copy_sigalgs (SSL *s, WPACKET *pkt, const uint16_t *psig, size_t psiglen)
__owur int tls1_save_sigalgs (SSL *s, PACKET *pkt)
__owur int tls1_process_sigalgs (SSL *s)
__owur int tls1_set_peer_legacy_sigalg (SSL *s, const EVP_PKEY *pkey)
__owur size_t tls12_get_psigalgs (SSL *s, int sent, const uint16_t **psigs)
__owur int tls12_check_peer_sigalg (SSL *s, uint16_t, EVP_PKEY *pkey)
void ssl_set_client_disabled (SSL *s)
__owur int ssl_cipher_disabled (SSL *s, const SSL_CIPHER *c, int op)
__owur int ssl_handshake_hash (SSL *s, unsigned char *out, size_t outlen, size_t *hashlen)
__owur const EVP_MD * ssl_md (int idx)
__owur const EVP_MD * ssl_handshake_md (SSL *s)
__owur const EVP_MD * ssl_prf_md (SSL *s)
__owur int ssl_log_rsa_client_key_exchange (SSL *ssl, const uint8_t *encrypted_premaster, size_t encrypted_premaster_len, const uint8_t *premaster, size_t premaster_len)
__owur int ssl_log_secret (SSL *ssl, const char *label, const uint8_t *secret, size_t secret_len)
__owur char ssl3_cbc_record_digest_supported (const EVP_MD_CTX *ctx)
__owur int ssl3_cbc_digest_record (const EVP_MD_CTX *ctx, unsigned char *md_out, size_t *md_out_size, const unsigned char header[13], const unsigned char *data, size_t data_plus_mac_size, size_t data_plus_mac_plus_padding_size, const unsigned char *mac_secret, size_t mac_secret_length, char is_sslv3)
__owur int tls_fips_digest_extra (const EVP_CIPHER_CTX *cipher_ctx, EVP_MD_CTX *mac_ctx, const unsigned char *data, size_t data_len, size_t orig_len)
__owur int srp_generate_server_master_secret (SSL *s)
__owur int srp_generate_client_master_secret (SSL *s)
__owur int srp_verify_server_param (SSL *s, int *al)
void custom_ext_init (custom_ext_methods *meths)
__owur int custom_ext_parse (SSL *s, int server, unsigned int ext_type, const unsigned char *ext_data, size_t ext_size, int *al)
__owur int custom_ext_add (SSL *s, int server, WPACKET *pkt, int *al)
__owur int custom_exts_copy (custom_ext_methods *dst, const custom_ext_methods *src)
void custom_exts_free (custom_ext_methods *exts)
void ssl_comp_free_compression_methods_int (void)
Variables
SSL3_ENC_METHOD ssl3_undef_enc_method
const SSL3_ENC_METHOD TLSv1_enc_data
const SSL3_ENC_METHOD TLSv1_1_enc_data
const SSL3_ENC_METHOD TLSv1_2_enc_data
const SSL3_ENC_METHOD TLSv1_3_enc_data
const SSL3_ENC_METHOD SSLv3_enc_data
const SSL3_ENC_METHOD DTLSv1_enc_data
const SSL3_ENC_METHOD DTLSv1_2_enc_data
__owur ** sorted
__owur const char * rule_str
__owur const char CERT * c
Macro Definition Documentation
bytestogroup
#define bytestogroup (bytes) ((unsigned int)(bytes[0] << 8 | bytes[1]))
Definition at line 2217 of file ssl_locl.h.
Referenced by tls_construct_ctos_key_share().
c2l
#define c2l (c, l)
Value:
(l = ((unsigned long)(*((c)++)))     , \
                         l|=(((unsigned long)(*((c)++)))<< 8), \
                         l|=(((unsigned long)(*((c)++)))<<16), \
                         l|=(((unsigned long)(*((c)++)))<<24))
Definition at line 78 of file ssl_locl.h.
c2ln
#define c2ln (c, l1, l2, n)
Value:
{ \
                        c+=n; \
                        l1=l2=0; \
                        switch (n) { \
                        case 8: l2 =((unsigned long)(*(--(c))))<<24; \
                        case 7: l2|=((unsigned long)(*(--(c))))<<16; \
                        case 6: l2|=((unsigned long)(*(--(c))))<< 8; \
                        case 5: l2|=((unsigned long)(*(--(c))));     \
                        case 4: l1 =((unsigned long)(*(--(c))))<<24; \
                        case 3: l1|=((unsigned long)(*(--(c))))<<16; \
                        case 2: l1|=((unsigned long)(*(--(c))))<< 8; \
                        case 1: l1|=((unsigned long)(*(--(c))));     \
                                } \
                        }
Definition at line 84 of file ssl_locl.h.
CLIENT_APPLICATION_LABEL
#define CLIENT_APPLICATION_LABEL "CLIENT_TRAFFIC_SECRET_0"
Definition at line 2335 of file ssl_locl.h.
CLIENT_HANDSHAKE_LABEL
#define CLIENT_HANDSHAKE_LABEL "CLIENT_HANDSHAKE_TRAFFIC_SECRET"
Definition at line 2333 of file ssl_locl.h.
DEC32
#define DEC32 (a) ((a)=((a)-1)&0xffffffffL)
Definition at line 189 of file ssl_locl.h.
DTLS1_MAX_MTU_OVERHEAD
#define DTLS1_MAX_MTU_OVERHEAD 48
Definition at line 1404 of file ssl_locl.h.
DTLS1_SCTP_AUTH_LABEL
#define DTLS1_SCTP_AUTH_LABEL "EXPORTER_DTLS_OVER_SCTP"
Definition at line 1400 of file ssl_locl.h.
Referenced by ossl_statem_server_post_work(), tls_client_key_exchange_post_work(), and tls_post_process_client_key_exchange().
DTLS1_SKIP_RECORD_HEADER
#define DTLS1_SKIP_RECORD_HEADER 2
Definition at line 1410 of file ssl_locl.h.
dtls_ver_ordinal
#define dtls_ver_ordinal (v1) (((v1) == DTLS1_BAD_VER) ? 0xff00 : (v1))
Definition at line 172 of file ssl_locl.h.
DTLS_VERSION_GE
#define DTLS_VERSION_GE (v1, v2) (dtls_ver_ordinal(v1) <= dtls_ver_ordinal(v2))
Definition at line 174 of file ssl_locl.h.
DTLS_VERSION_GT
#define DTLS_VERSION_GT (v1, v2) (dtls_ver_ordinal(v1) < dtls_ver_ordinal(v2))
Definition at line 173 of file ssl_locl.h.
Referenced by ssl_set_version_bound().
DTLS_VERSION_LE
#define DTLS_VERSION_LE (v1, v2) (dtls_ver_ordinal(v1) >= dtls_ver_ordinal(v2))
Definition at line 176 of file ssl_locl.h.
DTLS_VERSION_LT
#define DTLS_VERSION_LT (v1, v2) (dtls_ver_ordinal(v1) > dtls_ver_ordinal(v2))
Definition at line 175 of file ssl_locl.h.
Referenced by ssl_set_version_bound().
EXPLICIT_CHAR2_CURVE_TYPE
#define EXPLICIT_CHAR2_CURVE_TYPE 2
Definition at line 1502 of file ssl_locl.h.
EXPLICIT_PRIME_CURVE_TYPE
#define EXPLICIT_PRIME_CURVE_TYPE 1
Definition at line 1501 of file ssl_locl.h.
FP_ICC
#define FP_ICC (int (*)(const void *,const void *))
Definition at line 1638 of file ssl_locl.h.
IMPLEMENT_dtls1_meth_func
#define IMPLEMENT_dtls1_meth_func (version, flags, mask, func_name, s_accept, s_connect, enc_data)
Definition at line 1920 of file ssl_locl.h.
IMPLEMENT_ssl3_meth_func
#define IMPLEMENT_ssl3_meth_func (func_name, s_accept, s_connect)
Definition at line 1883 of file ssl_locl.h.
IMPLEMENT_tls_meth_func
#define IMPLEMENT_tls_meth_func (version, flags, mask, func_name, s_accept, s_connect, enc_data)
Definition at line 1845 of file ssl_locl.h.
INC32
#define INC32 (a) ((a)=((a)+1)&0xffffffffL)
Definition at line 188 of file ssl_locl.h.
l2c
#define l2c (l, c)
Value:
(*((c)++)=(unsigned char)(((l))&0xff), \
                         *((c)++)=(unsigned char)(((l)>> 8)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>16)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>24)&0xff))
Definition at line 99 of file ssl_locl.h.
l2cn
#define l2cn (l1, l2, c, n)
Value:
{ \
                        c+=n; \
                        switch (n) { \
                        case 8: *(--(c))=(unsigned char)(((l2)>>24)&0xff); \
                        case 7: *(--(c))=(unsigned char)(((l2)>>16)&0xff); \
                        case 6: *(--(c))=(unsigned char)(((l2)>> 8)&0xff); \
                        case 5: *(--(c))=(unsigned char)(((l2)    )&0xff); \
                        case 4: *(--(c))=(unsigned char)(((l1)>>24)&0xff); \
                        case 3: *(--(c))=(unsigned char)(((l1)>>16)&0xff); \
                        case 2: *(--(c))=(unsigned char)(((l1)>> 8)&0xff); \
                        case 1: *(--(c))=(unsigned char)(((l1)    )&0xff); \
                                } \
                        }
Definition at line 141 of file ssl_locl.h.
l2n
#define l2n (l, c)
Value:
(*((c)++)=(unsigned char)(((l)>>24)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>16)&0xff), \
                         *((c)++)=(unsigned char)(((l)>> 8)&0xff), \
                         *((c)++)=(unsigned char)(((l)    )&0xff))
Definition at line 119 of file ssl_locl.h.
l2n3
#define l2n3 (l, c)
Value:
(((c)[0]=(unsigned char)(((l)>>16)&0xff), \
                           (c)[1]=(unsigned char)(((l)>> 8)&0xff), \
                           (c)[2]=(unsigned char)(((l)    )&0xff)),(c)+=3)
Definition at line 164 of file ssl_locl.h.
l2n6
#define l2n6 (l, c)
Value:
(*((c)++)=(unsigned char)(((l)>>40)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>32)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>24)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>16)&0xff), \
                         *((c)++)=(unsigned char)(((l)>> 8)&0xff), \
                         *((c)++)=(unsigned char)(((l)    )&0xff))
Definition at line 124 of file ssl_locl.h.
l2n8
#define l2n8 (l, c)
Value:
(*((c)++)=(unsigned char)(((l)>>56)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>48)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>40)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>32)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>24)&0xff), \
                         *((c)++)=(unsigned char)(((l)>>16)&0xff), \
                         *((c)++)=(unsigned char)(((l)>> 8)&0xff), \
                         *((c)++)=(unsigned char)(((l)    )&0xff))
Definition at line 131 of file ssl_locl.h.
MASTER_SECRET_LABEL
#define MASTER_SECRET_LABEL "CLIENT_RANDOM"
Definition at line 2332 of file ssl_locl.h.
Referenced by tls_construct_finished().
MAX_COMPRESSIONS_SIZE
#define MAX_COMPRESSIONS_SIZE 255
Definition at line 1788 of file ssl_locl.h.
MAX_MAC_SIZE
#define MAX_MAC_SIZE 20 /* up from 16 for SSLv3 */
Definition at line 190 of file ssl_locl.h.
n2l
#define n2l (c, l)
Value:
(l =((unsigned long)(*((c)++)))<<24, \
                         l|=((unsigned long)(*((c)++)))<<16, \
                         l|=((unsigned long)(*((c)++)))<< 8, \
                         l|=((unsigned long)(*((c)++))))
Definition at line 104 of file ssl_locl.h.
n2l3
#define n2l3 (c, l)
Value:
((l =(((unsigned long)((c)[0]))<<16)| \
                              (((unsigned long)((c)[1]))<< 8)| \
                              (((unsigned long)((c)[2]))    )),(c)+=3)
Definition at line 160 of file ssl_locl.h.
Referenced by dtls1_get_message_header(), and tls_get_message_header().
n2l8
#define n2l8 (c, l)
Value:
(l =((uint64_t)(*((c)++)))<<56, \
                         l|=((uint64_t)(*((c)++)))<<48, \
                         l|=((uint64_t)(*((c)++)))<<40, \
                         l|=((uint64_t)(*((c)++)))<<32, \
                         l|=((uint64_t)(*((c)++)))<<24, \
                         l|=((uint64_t)(*((c)++)))<<16, \
                         l|=((uint64_t)(*((c)++)))<< 8, \
                         l|=((uint64_t)(*((c)++))))
Definition at line 109 of file ssl_locl.h.
n2s
#define n2s (c, s)
Value:
((s=(((unsigned int)((c)[0]))<< 8)| \
                             (((unsigned int)((c)[1]))    )),(c)+=2)
Definition at line 155 of file ssl_locl.h.
NAMED_CURVE_TYPE
#define NAMED_CURVE_TYPE 3
Definition at line 1503 of file ssl_locl.h.
Referenced by tls1_check_curve().
s2n
#define s2n (s, c)
Value:
(((c)[0]=(unsigned char)(((s)>> 8)&0xff), \
                           (c)[1]=(unsigned char)(((s)    )&0xff)),(c)+=2)
Definition at line 157 of file ssl_locl.h.
SEC_ESC_BIT
#define SEC_ESC_BIT 0x40
Definition at line 184 of file ssl_locl.h.
SERVER_APPLICATION_LABEL
#define SERVER_APPLICATION_LABEL "SERVER_TRAFFIC_SECRET_0"
Definition at line 2336 of file ssl_locl.h.
SERVER_HANDSHAKE_LABEL
#define SERVER_HANDSHAKE_LABEL "SERVER_HANDSHAKE_TRAFFIC_SECRET"
Definition at line 2334 of file ssl_locl.h.
SSL3_CK_CIPHERSUITE_FLAG
#define SSL3_CK_CIPHERSUITE_FLAG 0x03000000
Definition at line 357 of file ssl_locl.h.
Referenced by ssl3_get_cipher_by_char(), and ssl3_put_cipher_by_char().
SSL_3DES
#define SSL_3DES 0x00000002U
Definition at line 257 of file ssl_locl.h.
SSL_aANY
#define SSL_aANY 0x00000000U
Definition at line 253 of file ssl_locl.h.
SSL_aDSS
#define SSL_aDSS 0x00000002U
Definition at line 239 of file ssl_locl.h.
Referenced by ssl3_get_req_cert_type(), and ssl_cipher_get_cert_index().
SSL_AEAD
#define SSL_AEAD 0x00000040U
Definition at line 292 of file ssl_locl.h.
Referenced by SSL_CIPHER_is_aead(), tls_construct_stoc_etm(), and tls_parse_stoc_etm().
SSL_aECDSA
#define SSL_aECDSA 0x00000008U
Definition at line 243 of file ssl_locl.h.
Referenced by ssl3_get_req_cert_type(), ssl_check_srvr_ecc_cert_and_alg(), ssl_cipher_get_cert_index(), and tls_construct_stoc_ec_pt_formats().
SSL_AES
#define SSL_AES (SSL_AES128|SSL_AES256|SSL_AESGCM|SSL_AESCCM)
Definition at line 279 of file ssl_locl.h.
SSL_AES128
#define SSL_AES128 0x00000040U
Definition at line 262 of file ssl_locl.h.
SSL_AES128CCM
#define SSL_AES128CCM 0x00004000U
Definition at line 270 of file ssl_locl.h.
SSL_AES128CCM8
#define SSL_AES128CCM8 0x00010000U
Definition at line 272 of file ssl_locl.h.
SSL_AES128GCM
#define SSL_AES128GCM 0x00001000U
Definition at line 268 of file ssl_locl.h.
SSL_AES256
#define SSL_AES256 0x00000080U
Definition at line 263 of file ssl_locl.h.
SSL_AES256CCM
#define SSL_AES256CCM 0x00008000U
Definition at line 271 of file ssl_locl.h.
SSL_AES256CCM8
#define SSL_AES256CCM8 0x00020000U
Definition at line 273 of file ssl_locl.h.
SSL_AES256GCM
#define SSL_AES256GCM 0x00002000U
Definition at line 269 of file ssl_locl.h.
SSL_AESCCM
#define SSL_AESCCM (SSL_AES128CCM | SSL_AES256CCM | SSL_AES128CCM8 | SSL_AES256CCM8)
Definition at line 278 of file ssl_locl.h.
SSL_AESGCM
#define SSL_AESGCM (SSL_AES128GCM | SSL_AES256GCM)
Definition at line 277 of file ssl_locl.h.
SSL_aGOST01
#define SSL_aGOST01 0x00000020U
Definition at line 247 of file ssl_locl.h.
Referenced by ssl_cipher_get_cert_index().
SSL_aGOST12
#define SSL_aGOST12 0x00000080U
Definition at line 251 of file ssl_locl.h.
Referenced by ssl_cipher_get_cert_index().
SSL_aNULL
#define SSL_aNULL 0x00000004U
Definition at line 241 of file ssl_locl.h.
Referenced by ssl_get_auto_dh().
SSL_aPSK
#define SSL_aPSK 0x00000010U
Definition at line 245 of file ssl_locl.h.
Referenced by ssl_get_auto_dh(), and ssl_set_client_disabled().
SSL_aRSA
#define SSL_aRSA 0x00000001U
Definition at line 237 of file ssl_locl.h.
Referenced by ssl3_get_req_cert_type(), and ssl_cipher_get_cert_index().
SSL_aSRP
#define SSL_aSRP 0x00000040U
Definition at line 249 of file ssl_locl.h.
Referenced by ssl_set_client_disabled().
SSL_CAMELLIA
#define SSL_CAMELLIA (SSL_CAMELLIA128|SSL_CAMELLIA256)
Definition at line 280 of file ssl_locl.h.
SSL_CAMELLIA128
#define SSL_CAMELLIA128 0x00000100U
Definition at line 264 of file ssl_locl.h.
SSL_CAMELLIA256
#define SSL_CAMELLIA256 0x00000200U
Definition at line 265 of file ssl_locl.h.
SSL_CERT_FLAGS_CHECK_TLS_STRICT
#define SSL_CERT_FLAGS_CHECK_TLS_STRICT (SSL_CERT_FLAG_SUITEB_128_LOS|SSL_CERT_FLAG_TLS_STRICT)
Definition at line 1524 of file ssl_locl.h.
SSL_CHACHA20
#define SSL_CHACHA20 (SSL_CHACHA20POLY1305)
Definition at line 281 of file ssl_locl.h.
SSL_CHACHA20POLY1305
#define SSL_CHACHA20POLY1305 0x00080000U
Definition at line 275 of file ssl_locl.h.
SSL_CLIENT_USE_SIGALGS
#define SSL_CLIENT_USE_SIGALGS (s) SSL_CLIENT_USE_TLS1_2_CIPHERS(s)
Definition at line 395 of file ssl_locl.h.
Referenced by tls_construct_ctos_sig_algs().
SSL_CLIENT_USE_TLS1_2_CIPHERS
#define SSL_CLIENT_USE_TLS1_2_CIPHERS (s)
Value:
((!SSL_IS_DTLS(s) && s->client_version >= TLS1_2_VERSION) || \
     (SSL_IS_DTLS(s) && DTLS_VERSION_GE(s->client_version, DTLS1_2_VERSION)))
Definition at line 388 of file ssl_locl.h.
ssl_close_construct_packet
#define ssl_close_construct_packet (s, pkt, htype) s->method->ssl3_enc->close_construct_packet((s), (pkt), (htype))
Definition at line 1673 of file ssl_locl.h.
SSL_DECRYPT
#define SSL_DECRYPT 0
Definition at line 180 of file ssl_locl.h.
SSL_DEFAULT_MASK
#define SSL_DEFAULT_MASK 0X00000020U
Definition at line 345 of file ssl_locl.h.
SSL_DES
#define SSL_DES 0x00000001U
Definition at line 256 of file ssl_locl.h.
ssl_do_write
#define ssl_do_write (s) s->method->ssl3_enc->do_write(s)
Definition at line 1675 of file ssl_locl.h.
SSL_eGOST2814789CNT
#define SSL_eGOST2814789CNT 0x00000400U
Definition at line 266 of file ssl_locl.h.
Referenced by tls_construct_stoc_etm().
SSL_eGOST2814789CNT12
#define SSL_eGOST2814789CNT12 0x00040000U
Definition at line 274 of file ssl_locl.h.
Referenced by tls_construct_stoc_etm().
SSL_ENC_FLAG_DTLS
#define SSL_ENC_FLAG_DTLS 0x8
Definition at line 1686 of file ssl_locl.h.
SSL_ENC_FLAG_EXPLICIT_IV
#define SSL_ENC_FLAG_EXPLICIT_IV 0x1
Definition at line 1680 of file ssl_locl.h.
SSL_ENC_FLAG_SHA256_PRF
#define SSL_ENC_FLAG_SHA256_PRF 0x4
Definition at line 1684 of file ssl_locl.h.
Referenced by ssl_get_algorithm2().
SSL_ENC_FLAG_SIGALGS
#define SSL_ENC_FLAG_SIGALGS 0x2
Definition at line 1682 of file ssl_locl.h.
SSL_ENC_FLAG_TLS1_2_CIPHERS
#define SSL_ENC_FLAG_TLS1_2_CIPHERS 0x10
Definition at line 1691 of file ssl_locl.h.
SSL_ENCRYPT
#define SSL_ENCRYPT 1
Definition at line 181 of file ssl_locl.h.
SSL_eNULL
#define SSL_eNULL 0x00000020U
Definition at line 261 of file ssl_locl.h.
SSL_EXT_FLAG_RECEIVED
#define SSL_EXT_FLAG_RECEIVED 0x1
Definition at line 1547 of file ssl_locl.h.
SSL_EXT_FLAG_SENT
#define SSL_EXT_FLAG_SENT 0x2
Definition at line 1552 of file ssl_locl.h.
SSL_FIPS
#define SSL_FIPS 0x00000010U
Definition at line 351 of file ssl_locl.h.
SSL_GOST12_256
#define SSL_GOST12_256 0x00000080U
Definition at line 293 of file ssl_locl.h.
SSL_GOST12_512
#define SSL_GOST12_512 0x00000200U
Definition at line 295 of file ssl_locl.h.
SSL_GOST89MAC
#define SSL_GOST89MAC 0x00000008U
Definition at line 288 of file ssl_locl.h.
SSL_GOST89MAC12
#define SSL_GOST89MAC12 0x00000100U
Definition at line 294 of file ssl_locl.h.
SSL_GOST94
#define SSL_GOST94 0x00000004U
Definition at line 287 of file ssl_locl.h.
SSL_HANDSHAKE_MAC_DEFAULT
#define SSL_HANDSHAKE_MAC_DEFAULT SSL_HANDSHAKE_MAC_MD5_SHA1
Definition at line 326 of file ssl_locl.h.
Referenced by ssl_get_algorithm2().
SSL_HANDSHAKE_MAC_GOST12_256
#define SSL_HANDSHAKE_MAC_GOST12_256 SSL_MD_GOST12_256_IDX
Definition at line 324 of file ssl_locl.h.
SSL_HANDSHAKE_MAC_GOST12_512
#define SSL_HANDSHAKE_MAC_GOST12_512 SSL_MD_GOST12_512_IDX
Definition at line 325 of file ssl_locl.h.
SSL_HANDSHAKE_MAC_GOST94
#define SSL_HANDSHAKE_MAC_GOST94 SSL_MD_GOST94_IDX
Definition at line 323 of file ssl_locl.h.
SSL_HANDSHAKE_MAC_MASK
#define SSL_HANDSHAKE_MAC_MASK 0xFF
Definition at line 319 of file ssl_locl.h.
SSL_HANDSHAKE_MAC_MD5_SHA1
#define SSL_HANDSHAKE_MAC_MD5_SHA1 SSL_MD_MD5_SHA1_IDX
Definition at line 320 of file ssl_locl.h.
SSL_HANDSHAKE_MAC_SHA256
#define SSL_HANDSHAKE_MAC_SHA256 SSL_MD_SHA256_IDX
Definition at line 321 of file ssl_locl.h.
Referenced by ssl_get_algorithm2().
SSL_HANDSHAKE_MAC_SHA384
#define SSL_HANDSHAKE_MAC_SHA384 SSL_MD_SHA384_IDX
Definition at line 322 of file ssl_locl.h.
Referenced by ssl_get_algorithm2().
SSL_HIGH
#define SSL_HIGH 0x00000008U
Definition at line 350 of file ssl_locl.h.
SSL_IDEA
#define SSL_IDEA 0x00000010U
Definition at line 260 of file ssl_locl.h.
SSL_IS_DTLS
#define SSL_IS_DTLS (s) (s->method->ssl3_enc->enc_flags & SSL_ENC_FLAG_DTLS)
Definition at line 360 of file ssl_locl.h.
Referenced by ossl_statem_client_construct_message(), ossl_statem_client_post_work(), ossl_statem_client_pre_work(), ossl_statem_server_construct_message(), ossl_statem_server_post_work(), ossl_statem_server_pre_work(), ssl3_read_n(), ssl3_setup_read_buffer(), ssl3_setup_write_buffer(), SSL_is_dtls(), tls_client_key_exchange_post_work(), tls_construct_client_hello(), tls_construct_extensions(), tls_finish_handshake(), tls_post_process_client_key_exchange(), and tls_setup_handshake().
SSL_IS_FIRST_HANDSHAKE
#define SSL_IS_FIRST_HANDSHAKE (S) ((s)->s3->tmp.finish_md_len == 0)
Definition at line 367 of file ssl_locl.h.
Referenced by tls_construct_ctos_alpn(), tls_construct_ctos_npn(), tls_parse_ctos_alpn(), tls_parse_ctos_npn(), tls_parse_stoc_npn(), and tls_setup_handshake().
SSL_IS_TLS13
#define SSL_IS_TLS13 (s)
Value:
(!SSL_IS_DTLS(s) \
                          && (s)->method->version >= TLS1_3_VERSION \
                          && (s)->method->version != TLS_ANY_VERSION)
Definition at line 363 of file ssl_locl.h.
Referenced by ossl_statem_client_post_work(), ossl_statem_client_read_transition(), ossl_statem_client_write_transition(), ossl_statem_server_post_work(), ossl_statem_server_pre_work(), ossl_statem_server_read_transition(), ossl_statem_server_write_transition(), ssl_choose_server_version(), SSL_key_update(), SSL_renegotiate(), SSL_renegotiate_abbreviated(), tls1_generate_master_secret(), tls_construct_client_certificate(), tls_construct_extensions(), tls_construct_finished(), tls_construct_server_certificate(), tls_construct_server_hello(), tls_construct_stoc_status_request(), tls_parse_stoc_status_request(), and tls_process_finished().
SSL_kANY
#define SSL_kANY 0x00000000U
Definition at line 233 of file ssl_locl.h.
SSL_kDHE
#define SSL_kDHE 0x00000002U
Definition at line 210 of file ssl_locl.h.
Referenced by ssl3_get_req_cert_type().
SSL_kDHEPSK
#define SSL_kDHEPSK 0x00000100U
Definition at line 226 of file ssl_locl.h.
SSL_kECDHE
#define SSL_kECDHE 0x00000004U
Definition at line 214 of file ssl_locl.h.
Referenced by tls_construct_stoc_ec_pt_formats().
SSL_kECDHEPSK
#define SSL_kECDHEPSK 0x00000080U
Definition at line 225 of file ssl_locl.h.
SSL_kEDH
#define SSL_kEDH SSL_kDHE
Definition at line 212 of file ssl_locl.h.
SSL_kEECDH
#define SSL_kEECDH SSL_kECDHE
Definition at line 216 of file ssl_locl.h.
SSL_kGOST
#define SSL_kGOST 0x00000010U
Definition at line 220 of file ssl_locl.h.
Referenced by ssl3_get_req_cert_type().
SSL_kPSK
#define SSL_kPSK 0x00000008U
Definition at line 218 of file ssl_locl.h.
Referenced by tls_client_key_exchange_post_work().
SSL_kRSA
#define SSL_kRSA 0x00000001U
Definition at line 208 of file ssl_locl.h.
SSL_kRSAPSK
#define SSL_kRSAPSK 0x00000040U
Definition at line 224 of file ssl_locl.h.
SSL_kSRP
#define SSL_kSRP 0x00000020U
Definition at line 222 of file ssl_locl.h.
Referenced by ssl3_ctx_callback_ctrl(), ssl_set_client_disabled(), and tls_client_key_exchange_post_work().
SSL_LOW
#define SSL_LOW 0x00000002U
Definition at line 348 of file ssl_locl.h.
SSL_MAX_DIGEST
#define SSL_MAX_DIGEST 12
Definition at line 314 of file ssl_locl.h.
SSL_MD5
#define SSL_MD5 0x00000001U
Definition at line 285 of file ssl_locl.h.
SSL_MD_GOST12_256_IDX
#define SSL_MD_GOST12_256_IDX 6
Definition at line 308 of file ssl_locl.h.
Referenced by ssl_set_default_md().
SSL_MD_GOST12_512_IDX
#define SSL_MD_GOST12_512_IDX 8
Definition at line 310 of file ssl_locl.h.
Referenced by ssl_set_default_md().
SSL_MD_GOST89MAC12_IDX
#define SSL_MD_GOST89MAC12_IDX 7
Definition at line 309 of file ssl_locl.h.
SSL_MD_GOST89MAC_IDX
#define SSL_MD_GOST89MAC_IDX 3
Definition at line 305 of file ssl_locl.h.
SSL_MD_GOST94_IDX
#define SSL_MD_GOST94_IDX 2
Definition at line 304 of file ssl_locl.h.
Referenced by ssl_set_default_md().
SSL_MD_MD5_IDX
#define SSL_MD_MD5_IDX 0
Definition at line 302 of file ssl_locl.h.
SSL_MD_MD5_SHA1_IDX
#define SSL_MD_MD5_SHA1_IDX 9
Definition at line 311 of file ssl_locl.h.
Referenced by ssl_set_default_md().
SSL_MD_SHA1_IDX
#define SSL_MD_SHA1_IDX 1
Definition at line 303 of file ssl_locl.h.
Referenced by ssl_set_default_md().
SSL_MD_SHA224_IDX
#define SSL_MD_SHA224_IDX 10
Definition at line 312 of file ssl_locl.h.
SSL_MD_SHA256_IDX
#define SSL_MD_SHA256_IDX 4
Definition at line 306 of file ssl_locl.h.
SSL_MD_SHA384_IDX
#define SSL_MD_SHA384_IDX 5
Definition at line 307 of file ssl_locl.h.
SSL_MD_SHA512_IDX
#define SSL_MD_SHA512_IDX 11
Definition at line 313 of file ssl_locl.h.
SSL_MEDIUM
#define SSL_MEDIUM 0x00000004U
Definition at line 349 of file ssl_locl.h.
SSL_METHOD_NO_FIPS
#define SSL_METHOD_NO_FIPS (1U<<0)
Definition at line 1842 of file ssl_locl.h.
SSL_METHOD_NO_SUITEB
#define SSL_METHOD_NO_SUITEB (1U<<1)
Definition at line 1843 of file ssl_locl.h.
SSL_NOT_DEFAULT
#define SSL_NOT_DEFAULT 0x00000020U
Definition at line 352 of file ssl_locl.h.
SSL_PKEY_DSA_SIGN
#define SSL_PKEY_DSA_SIGN 1
Definition at line 403 of file ssl_locl.h.
Referenced by ssl_cert_type(), ssl_cipher_get_cert_index(), ssl_set_default_md(), ssl_set_masks(), and tls1_set_cert_validity().
SSL_PKEY_ECC
#define SSL_PKEY_ECC 2
Definition at line 404 of file ssl_locl.h.
Referenced by ssl_cert_type(), ssl_cipher_get_cert_index(), ssl_set_default_md(), ssl_set_masks(), and tls1_set_cert_validity().
SSL_PKEY_GOST01
#define SSL_PKEY_GOST01 3
Definition at line 405 of file ssl_locl.h.
Referenced by ssl_cert_type(), ssl_cipher_get_cert_index(), ssl_set_default_md(), and tls1_set_cert_validity().
SSL_PKEY_GOST12_256
#define SSL_PKEY_GOST12_256 4
Definition at line 406 of file ssl_locl.h.
Referenced by ssl_cert_type(), ssl_set_default_md(), and tls1_set_cert_validity().
SSL_PKEY_GOST12_512
#define SSL_PKEY_GOST12_512 5
Definition at line 407 of file ssl_locl.h.
Referenced by ssl_cert_type(), ssl_set_default_md(), and tls1_set_cert_validity().
SSL_PKEY_GOST_EC
#define SSL_PKEY_GOST_EC SSL_PKEY_NUM+1
Definition at line 413 of file ssl_locl.h.
Referenced by ssl_cipher_get_cert_index().
SSL_PKEY_NUM
#define SSL_PKEY_NUM 6
Definition at line 408 of file ssl_locl.h.
Referenced by SSL_CONF_CTX_free(), and tls1_set_server_sigalgs().
SSL_PKEY_RSA
#define SSL_PKEY_RSA 0
Definition at line 402 of file ssl_locl.h.
Referenced by ssl_cert_type(), ssl_cipher_get_cert_index(), ssl_set_default_md(), ssl_set_masks(), and tls1_set_cert_validity().
SSL_PKEY_RSA_PSS_SIGN
#define SSL_PKEY_RSA_PSS_SIGN SSL_PKEY_RSA
Definition at line 419 of file ssl_locl.h.
SSL_PSK
#define SSL_PSK (SSL_kPSK | SSL_kRSAPSK | SSL_kECDHEPSK | SSL_kDHEPSK)
Definition at line 230 of file ssl_locl.h.
Referenced by ssl_get_algorithm2(), ssl_set_client_disabled(), tls_construct_client_key_exchange(), and tls_process_client_key_exchange().
SSL_RC2
#define SSL_RC2 0x00000008U
Definition at line 259 of file ssl_locl.h.
SSL_RC4
#define SSL_RC4 0x00000004U
Definition at line 258 of file ssl_locl.h.
Referenced by tls_construct_stoc_etm(), and tls_parse_stoc_etm().
SSL_READ_ETM
#define SSL_READ_ETM (s) (s->s3->flags & TLS1_FLAGS_ENCRYPT_THEN_MAC_READ)
Definition at line 398 of file ssl_locl.h.
Referenced by DTLS_get_data_mtu().
SSL_SEED
#define SSL_SEED 0x00000800U
Definition at line 267 of file ssl_locl.h.
SSL_SESS_FLAG_EXTMS
#define SSL_SESS_FLAG_EXTMS 0x1
Definition at line 602 of file ssl_locl.h.
Referenced by SSL_ctrl(), SSL_SESSION_print(), tls1_generate_master_secret(), and tls_parse_stoc_ems().
ssl_set_handshake_header
#define ssl_set_handshake_header (s, pkt, htype) s->method->ssl3_enc->set_handshake_header((s), (pkt), (htype))
Definition at line 1671 of file ssl_locl.h.
SSL_SHA1
#define SSL_SHA1 0x00000002U
Definition at line 286 of file ssl_locl.h.
SSL_SHA256
#define SSL_SHA256 0x00000010U
Definition at line 289 of file ssl_locl.h.
SSL_SHA384
#define SSL_SHA384 0x00000020U
Definition at line 290 of file ssl_locl.h.
SSL_STRONG_MASK
#define SSL_STRONG_MASK 0x0000001FU
Definition at line 344 of file ssl_locl.h.
SSL_STRONG_NONE
#define SSL_STRONG_NONE 0x00000001U
Definition at line 347 of file ssl_locl.h.
SSL_USE_EXPLICIT_IV
#define SSL_USE_EXPLICIT_IV (s) (s->method->ssl3_enc->enc_flags & SSL_ENC_FLAG_EXPLICIT_IV)
Definition at line 370 of file ssl_locl.h.
Referenced by tls1_cbc_remove_padding().
SSL_USE_PSS
#define SSL_USE_PSS (s)
Value:
(s->s3->tmp.peer_sigalg != NULL && \
                        s->s3->tmp.peer_sigalg->sig == EVP_PKEY_RSA_PSS)
Definition at line 1781 of file ssl_locl.h.
SSL_USE_SIGALGS
#define SSL_USE_SIGALGS (s) (s->method->ssl3_enc->enc_flags & SSL_ENC_FLAG_SIGALGS)
Definition at line 376 of file ssl_locl.h.
Referenced by ssl_set_default_md().
SSL_USE_TLS1_2_CIPHERS
#define SSL_USE_TLS1_2_CIPHERS (s) (s->method->ssl3_enc->enc_flags & SSL_ENC_FLAG_TLS1_2_CIPHERS)
Definition at line 382 of file ssl_locl.h.
SSL_WRITE_ETM
#define SSL_WRITE_ETM (s) (s->s3->flags & TLS1_FLAGS_ENCRYPT_THEN_MAC_WRITE)
Definition at line 399 of file ssl_locl.h.
THREE_BYTE_MASK
#define THREE_BYTE_MASK 0x3fff
Definition at line 186 of file ssl_locl.h.
TLS1_PRF
#define TLS1_PRF (SSL_MD_MD5_SHA1_IDX << TLS1_PRF_DGST_SHIFT)
Definition at line 336 of file ssl_locl.h.
Referenced by ssl_get_algorithm2().
TLS1_PRF_DGST_SHIFT
#define TLS1_PRF_DGST_SHIFT 8
Definition at line 329 of file ssl_locl.h.
Referenced by ssl_prf_md().
TLS1_PRF_GOST12_256
#define TLS1_PRF_GOST12_256 (SSL_MD_GOST12_256_IDX << TLS1_PRF_DGST_SHIFT)
Definition at line 334 of file ssl_locl.h.
TLS1_PRF_GOST12_512
#define TLS1_PRF_GOST12_512 (SSL_MD_GOST12_512_IDX << TLS1_PRF_DGST_SHIFT)
Definition at line 335 of file ssl_locl.h.
TLS1_PRF_GOST94
#define TLS1_PRF_GOST94 (SSL_MD_GOST94_IDX << TLS1_PRF_DGST_SHIFT)
Definition at line 333 of file ssl_locl.h.
TLS1_PRF_SHA1_MD5
#define TLS1_PRF_SHA1_MD5 (SSL_MD_MD5_SHA1_IDX << TLS1_PRF_DGST_SHIFT)
Definition at line 330 of file ssl_locl.h.
TLS1_PRF_SHA256
#define TLS1_PRF_SHA256 (SSL_MD_SHA256_IDX << TLS1_PRF_DGST_SHIFT)
Definition at line 331 of file ssl_locl.h.
Referenced by ssl_get_algorithm2().
TLS1_PRF_SHA384
#define TLS1_PRF_SHA384 (SSL_MD_SHA384_IDX << TLS1_PRF_DGST_SHIFT)
Definition at line 332 of file ssl_locl.h.
Referenced by ssl_get_algorithm2().
TLS1_STREAM_MAC
#define TLS1_STREAM_MAC 0x10000
Definition at line 342 of file ssl_locl.h.
tls1_suiteb
#define tls1_suiteb (s) (s->cert->cert_flags & SSL_CERT_FLAG_SUITEB_128_LOS)
Definition at line 1522 of file ssl_locl.h.
Referenced by ssl_verify_cert_chain(), tls12_get_psigalgs(), tls1_check_curve(), tls1_check_ec_tmp_key(), and tls1_get_curvelist().
TLS_CIPHER_LEN
#define TLS_CIPHER_LEN 2
Definition at line 436 of file ssl_locl.h.
Referenced by SSL_ctrl().
TLS_CURVE_CHAR2
#define TLS_CURVE_CHAR2 0x1
Definition at line 2214 of file ssl_locl.h.
Referenced by tls_curve_allowed().
TLS_CURVE_CUSTOM
#define TLS_CURVE_CUSTOM 0x2
Definition at line 2215 of file ssl_locl.h.
TLS_CURVE_PRIME
#define TLS_CURVE_PRIME 0x0
Definition at line 2213 of file ssl_locl.h.
TLS_CURVE_TYPE
#define TLS_CURVE_TYPE 0x3
Definition at line 2212 of file ssl_locl.h.
TLSEXT_KEX_MODE_FLAG_KE
#define TLSEXT_KEX_MODE_FLAG_KE 1
Definition at line 1775 of file ssl_locl.h.
Referenced by tls_construct_ctos_psk_kex_modes().
TLSEXT_KEX_MODE_FLAG_KE_DHE
#define TLSEXT_KEX_MODE_FLAG_KE_DHE 2
Definition at line 1776 of file ssl_locl.h.
Referenced by tls_construct_ctos_psk_kex_modes().
TLSEXT_KEX_MODE_FLAG_NONE
#define TLSEXT_KEX_MODE_FLAG_NONE 0
Definition at line 1774 of file ssl_locl.h.
TLSEXT_KEX_MODE_KE
#define TLSEXT_KEX_MODE_KE 0x00
Definition at line 1768 of file ssl_locl.h.
Referenced by tls_construct_ctos_psk_kex_modes().
TLSEXT_KEX_MODE_KE_DHE
#define TLSEXT_KEX_MODE_KE_DHE 0x01
Definition at line 1769 of file ssl_locl.h.
Referenced by tls_construct_ctos_psk_kex_modes().
TLSEXT_KEYNAME_LENGTH
#define TLSEXT_KEYNAME_LENGTH 16
Definition at line 635 of file ssl_locl.h.
TLSEXT_PSK_BAD_IDENTITY
#define TLSEXT_PSK_BAD_IDENTITY -1
Definition at line 1779 of file ssl_locl.h.
TLSEXT_SIGALG_dsa_sha1
#define TLSEXT_SIGALG_dsa_sha1 0x0202
Definition at line 1762 of file ssl_locl.h.
TLSEXT_SIGALG_dsa_sha256
#define TLSEXT_SIGALG_dsa_sha256 0x0402
Definition at line 1759 of file ssl_locl.h.
TLSEXT_SIGALG_dsa_sha384
#define TLSEXT_SIGALG_dsa_sha384 0x0502
Definition at line 1760 of file ssl_locl.h.
TLSEXT_SIGALG_dsa_sha512
#define TLSEXT_SIGALG_dsa_sha512 0x0602
Definition at line 1761 of file ssl_locl.h.
TLSEXT_SIGALG_ecdsa_secp256r1_sha256
#define TLSEXT_SIGALG_ecdsa_secp256r1_sha256 0x0403
Definition at line 1748 of file ssl_locl.h.
TLSEXT_SIGALG_ecdsa_secp384r1_sha384
#define TLSEXT_SIGALG_ecdsa_secp384r1_sha384 0x0503
Definition at line 1749 of file ssl_locl.h.
TLSEXT_SIGALG_ecdsa_secp521r1_sha512
#define TLSEXT_SIGALG_ecdsa_secp521r1_sha512 0x0603
Definition at line 1750 of file ssl_locl.h.
TLSEXT_SIGALG_ecdsa_sha1
#define TLSEXT_SIGALG_ecdsa_sha1 0x0203
Definition at line 1751 of file ssl_locl.h.
TLSEXT_SIGALG_gostr34102001_gostr3411
#define TLSEXT_SIGALG_gostr34102001_gostr3411 0xeded
Definition at line 1765 of file ssl_locl.h.
TLSEXT_SIGALG_gostr34102012_256_gostr34112012_256
#define TLSEXT_SIGALG_gostr34102012_256_gostr34112012_256 0xeeee
Definition at line 1763 of file ssl_locl.h.
TLSEXT_SIGALG_gostr34102012_512_gostr34112012_512
#define TLSEXT_SIGALG_gostr34102012_512_gostr34112012_512 0xefef
Definition at line 1764 of file ssl_locl.h.
TLSEXT_SIGALG_rsa_pkcs1_sha1
#define TLSEXT_SIGALG_rsa_pkcs1_sha1 0x0201
Definition at line 1758 of file ssl_locl.h.
TLSEXT_SIGALG_rsa_pkcs1_sha256
#define TLSEXT_SIGALG_rsa_pkcs1_sha256 0x0401
Definition at line 1755 of file ssl_locl.h.
TLSEXT_SIGALG_rsa_pkcs1_sha384
#define TLSEXT_SIGALG_rsa_pkcs1_sha384 0x0501
Definition at line 1756 of file ssl_locl.h.
TLSEXT_SIGALG_rsa_pkcs1_sha512
#define TLSEXT_SIGALG_rsa_pkcs1_sha512 0x0601
Definition at line 1757 of file ssl_locl.h.
TLSEXT_SIGALG_rsa_pss_sha256
#define TLSEXT_SIGALG_rsa_pss_sha256 0x0804
Definition at line 1752 of file ssl_locl.h.
TLSEXT_SIGALG_rsa_pss_sha384
#define TLSEXT_SIGALG_rsa_pss_sha384 0x0805
Definition at line 1753 of file ssl_locl.h.
TLSEXT_SIGALG_rsa_pss_sha512
#define TLSEXT_SIGALG_rsa_pss_sha512 0x0806
Definition at line 1754 of file ssl_locl.h.
TLSEXT_signature_rsa_pss
#define TLSEXT_signature_rsa_pss 0x0101
Definition at line 1785 of file ssl_locl.h.
TLSEXT_STATUSTYPE_nothing
#define TLSEXT_STATUSTYPE_nothing -1
Definition at line 1745 of file ssl_locl.h.
Referenced by tls_parse_stoc_status_request(), and tls_process_initial_server_flight().
TWO_BYTE_BIT
#define TWO_BYTE_BIT 0x80
Definition at line 183 of file ssl_locl.h.
TWO_BYTE_MASK
#define TWO_BYTE_MASK 0x7fff
Definition at line 185 of file ssl_locl.h.
Enumeration Type Documentation
TICKET_RETURN
enum TICKET_RETURN
Enumerator
TICKET_FATAL_ERR_MALLOC
TICKET_FATAL_ERR_OTHER
TICKET_NONE
TICKET_EMPTY
TICKET_NO_DECRYPT
TICKET_SUCCESS
TICKET_SUCCESS_RENEW
Definition at line 2244 of file ssl_locl.h.
TLSEXT_INDEX
enum TLSEXT_INDEX
Enumerator
TLSEXT_IDX_renegotiate
TLSEXT_IDX_server_name
TLSEXT_IDX_srp
TLSEXT_IDX_ec_point_formats
TLSEXT_IDX_supported_groups
TLSEXT_IDX_session_ticket
TLSEXT_IDX_signature_algorithms
TLSEXT_IDX_status_request
TLSEXT_IDX_next_proto_neg
TLSEXT_IDX_application_layer_protocol_negotiation
TLSEXT_IDX_use_srtp
TLSEXT_IDX_encrypt_then_mac
TLSEXT_IDX_signed_certificate_timestamp
TLSEXT_IDX_extended_master_secret
TLSEXT_IDX_supported_versions
TLSEXT_IDX_psk_kex_modes
TLSEXT_IDX_key_share
TLSEXT_IDX_cryptopro_bug
TLSEXT_IDX_padding
TLSEXT_IDX_psk
Definition at line 1718 of file ssl_locl.h.
Function Documentation
custom_ext_add()
__owur int custom_ext_add (SSL * s, int server, WPACKET * pkt, int * al)
Definition at line 77 of file t1_ext.c.
References custom_ext_methods::meths_count.
Referenced by tls_construct_extensions().
custom_ext_init()
void custom_ext_init (custom_ext_methods * meths)
Definition at line 31 of file t1_ext.c.
References custom_ext_method::ext_flags, custom_ext_methods::meths, and custom_ext_methods::meths_count.
Referenced by tls_collect_extensions(), and tls_construct_extensions().
custom_ext_parse()
__owur int custom_ext_parse (SSL * s, int server, unsigned int ext_type, const unsigned char * ext_data, size_t ext_size, int * al)
Definition at line 40 of file t1_ext.c.
custom_exts_copy()
__owur int custom_exts_copy (custom_ext_methods * dst, const custom_ext_methods * src)
Definition at line 133 of file t1_ext.c.
References custom_ext_methods::meths, custom_ext_methods::meths_count, NULL, and OPENSSL_memdup.
custom_exts_free()
void custom_exts_free (custom_ext_methods * exts)
Definition at line 146 of file t1_ext.c.
References custom_ext_methods::meths, and OPENSSL_free.
DECLARE_OBJ_BSEARCH_GLOBAL_CMP_FN()
DECLARE_OBJ_BSEARCH_GLOBAL_CMP_FN (SSL_CIPHER , SSL_CIPHER , ssl_cipher_id)
DEFINE_LHASH_OF() [1/2]
DEFINE_LHASH_OF (SSL_SESSION)
DEFINE_LHASH_OF() [2/2]
DEFINE_LHASH_OF (X509_NAME)
dtls1_buffer_message()
__owur int dtls1_buffer_message (SSL * s, int ccs)
Definition at line 971 of file statem_dtls.c.
References OPENSSL_assert.
Referenced by dtls1_close_construct_packet().
dtls1_check_timeout_num()
__owur int dtls1_check_timeout_num (SSL * s)
Definition at line 341 of file d1_lib.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_GET_FALLBACK_MTU, DTLS1_TMO_ALERT_COUNT, NULL, SSL_F_DTLS1_CHECK_TIMEOUT_NUM, SSL_get_options(), SSL_get_wbio(), SSL_OP_NO_QUERY_MTU, SSL_R_READ_TIMEOUT_EXPIRED, and SSLerr.
Referenced by dtls1_handle_timeout().
dtls1_clear()
void dtls1_clear (SSL * s)
Definition at line 159 of file d1_lib.c.
References DTLS_RECORD_LAYER_clear().
dtls1_clear_received_buffer()
void dtls1_clear_received_buffer (SSL * s)
Definition at line 119 of file d1_lib.c.
References dtls1_hm_fragment_free(), NULL, pitem_free(), and pqueue_pop().
Referenced by dtls1_reset_seq_numbers().
dtls1_clear_sent_buffer()
void dtls1_clear_sent_buffer (SSL * s)
Definition at line 131 of file d1_lib.c.
References dtls1_hm_fragment_free(), NULL, pitem_free(), and pqueue_pop().
Referenced by dtls1_stop_timer(), and ossl_statem_server_pre_work().
dtls1_close_construct_packet()
__owur int dtls1_close_construct_packet (SSL * s, WPACKET * pkt, int htype)
Definition at line 1199 of file statem_dtls.c.
References dtls1_buffer_message(), DTLS1_HM_HEADER_LENGTH, DTLS1_MT_HELLO_VERIFY_REQUEST, SSL3_MT_CHANGE_CIPHER_SPEC, WPACKET_close(), and WPACKET_get_length().
dtls1_ctrl()
long dtls1_ctrl (SSL * s, int cmd, long larg, void * parg)
Definition at line 203 of file d1_lib.c.
dtls1_default_timeout()
__owur long dtls1_default_timeout (void)
Definition at line 66 of file d1_lib.c.
dtls1_dispatch_alert()
__owur int dtls1_dispatch_alert (SSL * s)
Definition at line 48 of file d1_msg.c.
References cb, NULL, and type.
dtls1_do_write()
__owur int dtls1_do_write (SSL * s, int type)
Definition at line 110 of file statem_dtls.c.
dtls1_double_timeout()
void dtls1_double_timeout (SSL * s)
Definition at line 321 of file d1_lib.c.
References dtls1_start_timer().
Referenced by dtls1_handle_timeout().
dtls1_free()
void dtls1_free (SSL * s)
Definition at line 144 of file d1_lib.c.
References DTLS_RECORD_LAYER_free(), and ssl3_free().
dtls1_get_message_header()
void dtls1_get_message_header (unsigned char * data, struct hm_header_st * msg_hdr)
Definition at line 1164 of file statem_dtls.c.
References hm_header_st::frag_len, hm_header_st::frag_off, hm_header_st::msg_len, n2l3, n2s, hm_header_st::seq, and hm_header_st::type.
dtls1_get_queue_priority()
__owur int dtls1_get_queue_priority (unsigned short seq, int is_ccs)
Definition at line 934 of file statem_dtls.c.
References hm_header_st::is_ccs.
dtls1_get_timeout()
__owur struct timeval* dtls1_get_timeout (SSL * s, struct timeval * timeleft)
Definition at line 263 of file d1_lib.c.
References NULL.
Referenced by dtls1_is_timer_expired().
dtls1_handle_timeout()
__owur int dtls1_handle_timeout (SSL * s)
Definition at line 365 of file d1_lib.c.
References dtls1_check_timeout_num(), dtls1_double_timeout(), dtls1_is_timer_expired(), dtls1_retransmit_buffered_messages(), dtls1_start_timer(), and DTLS1_TMO_READ_COUNT.
Referenced by dtls1_read_failed().
dtls1_hm_fragment_free()
void dtls1_hm_fragment_free (hm_fragment * frag)
Definition at line 92 of file statem_dtls.c.
References EVP_CIPHER_CTX_free(), EVP_MD_CTX_free(), hm_fragment::fragment, hm_header_st::is_ccs, hm_fragment::msg_header, OPENSSL_free, hm_fragment::reassembly, hm_header_st::saved_retransmit_state, and dtls1_retransmit_state::write_hash.
Referenced by dtls1_clear_received_buffer(), and dtls1_clear_sent_buffer().
dtls1_is_timer_expired()
__owur int dtls1_is_timer_expired (SSL * s)
Definition at line 303 of file d1_lib.c.
References dtls1_get_timeout(), and NULL.
Referenced by dtls1_handle_timeout(), and dtls1_read_failed().
dtls1_min_mtu()
__owur size_t dtls1_min_mtu (SSL * s)
Definition at line 922 of file d1_lib.c.
Referenced by dtls1_query_mtu().
dtls1_new()
__owur int dtls1_new (SSL * s)
Definition at line 75 of file d1_lib.c.
References DTLS1_STATE::buffered_messages, DTLS1_STATE::cookie_len, DTLS_RECORD_LAYER_new(), DTLS1_STATE::link_mtu, DTLS1_STATE::mtu, NULL, OPENSSL_free, OPENSSL_zalloc, pqueue_free(), pqueue_new(), DTLS1_STATE::sent_messages, ssl3_free(), and ssl3_new().
dtls1_query_mtu()
__owur int dtls1_query_mtu (SSL * s)
Definition at line 886 of file d1_lib.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_QUERY_MTU, BIO_CTRL_DGRAM_SET_MTU, BIO_dgram_get_mtu_overhead, dtls1_min_mtu(), NULL, SSL_get_options(), SSL_get_wbio(), and SSL_OP_NO_QUERY_MTU.
dtls1_read_failed()
__owur int dtls1_read_failed (SSL * s, int code)
Definition at line 910 of file statem_dtls.c.
References BIO_FLAGS_READ, BIO_set_flags(), code, dtls1_handle_timeout(), dtls1_is_timer_expired(), ERR_R_INTERNAL_ERROR, SSL_F_DTLS1_READ_FAILED, SSL_get_rbio(), SSL_in_init(), and SSLerr.
dtls1_retransmit_buffered_messages()
int dtls1_retransmit_buffered_messages (SSL * s)
Definition at line 949 of file statem_dtls.c.
Referenced by dtls1_handle_timeout().
dtls1_retransmit_message()
__owur int dtls1_retransmit_message (SSL * s, unsigned short seq, int * found)
Definition at line 1035 of file statem_dtls.c.
dtls1_send_newsession_ticket()
__owur int dtls1_send_newsession_ticket (SSL * s)
dtls1_set_handshake_header()
__owur int dtls1_set_handshake_header (SSL * s, WPACKET * pkt, int htype)
Definition at line 1175 of file statem_dtls.c.
References SSL3_MT_CHANGE_CIPHER_SPEC.
dtls1_set_message_header()
void dtls1_set_message_header (SSL * s, unsigned char mt, size_t len, size_t frag_off, size_t frag_len)
Definition at line 1113 of file statem_dtls.c.
dtls1_shutdown()
__owur int dtls1_shutdown (SSL * s)
Definition at line 861 of file d1_lib.c.
dtls1_start_timer()
void dtls1_start_timer (SSL * s)
Definition at line 239 of file d1_lib.c.
References BIO_dgram_is_sctp(), and SSL_get_wbio().
Referenced by dtls1_double_timeout(), and dtls1_handle_timeout().
dtls1_stop_timer()
void dtls1_stop_timer (SSL * s)
Definition at line 329 of file d1_lib.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_SET_NEXT_TIMEOUT, dtls1_clear_sent_buffer(), and SSL_get_rbio().
dtls1_write_app_data_bytes()
int dtls1_write_app_data_bytes (SSL * s, int type, const void * buf_, size_t len, size_t * written)
Definition at line 13 of file d1_msg.c.
References BIO_dgram_is_sctp(), dtls1_write_bytes(), ossl_statem_get_in_handshake(), ossl_statem_in_sctp_read_sock(), SSL3_RT_MAX_PLAIN_LENGTH, SSL_F_DTLS1_WRITE_APP_DATA_BYTES, SSL_get_wbio(), SSL_in_init(), SSL_R_DTLS_MESSAGE_TOO_BIG, SSL_R_SSL_HANDSHAKE_FAILURE, and SSLerr.
dtls_bad_ver_client_method()
__owur const SSL_METHOD* dtls_bad_ver_client_method (void)
dtls_raw_hello_verify_request()
__owur int dtls_raw_hello_verify_request (WPACKET * pkt, unsigned char * cookie, size_t cookie_len)
Definition at line 1127 of file statem_srvr.c.
Referenced by dtls_construct_hello_verify_request().
dtlsv1_2_client_method()
__owur const SSL_METHOD* dtlsv1_2_client_method (void)
Referenced by DTLSv1_2_client_method().
dtlsv1_2_method()
__owur const SSL_METHOD* dtlsv1_2_method (void)
Referenced by DTLSv1_2_method().
dtlsv1_2_server_method()
__owur const SSL_METHOD* dtlsv1_2_server_method (void)
Referenced by DTLSv1_2_server_method().
dtlsv1_client_method()
__owur const SSL_METHOD* dtlsv1_client_method (void)
Referenced by DTLSv1_client_method().
dtlsv1_method()
__owur const SSL_METHOD* dtlsv1_method (void)
Referenced by DTLSv1_method().
dtlsv1_server_method()
__owur const SSL_METHOD* dtlsv1_server_method (void)
Referenced by DTLSv1_server_method().
pitem_free()
void pitem_free (pitem * item)
Definition at line 32 of file pqueue.c.
References OPENSSL_free.
Referenced by dtls1_buffer_record(), dtls1_clear_received_buffer(), dtls1_clear_sent_buffer(), and DTLS_RECORD_LAYER_clear().
pitem_new()
pitem* pitem_new (unsigned char * prio64be, void * data)
Definition at line 18 of file pqueue.c.
References data, NULL, and OPENSSL_malloc.
Referenced by dtls1_buffer_record().
pqueue_find()
pitem* pqueue_find (pqueue * pq, unsigned char * prio64be)
Definition at line 100 of file pqueue.c.
pqueue_free()
void pqueue_free (pqueue * pq)
Definition at line 44 of file pqueue.c.
References OPENSSL_free.
Referenced by dtls1_new(), DTLS_RECORD_LAYER_free(), and DTLS_RECORD_LAYER_new().
pqueue_insert()
pitem* pqueue_insert (pqueue * pq, pitem * item)
Definition at line 49 of file pqueue.c.
References NULL.
Referenced by dtls1_buffer_record().
pqueue_iterator()
pitem* pqueue_iterator (pqueue * pq)
Definition at line 125 of file pqueue.c.
References pqueue_peek().
pqueue_new()
pqueue* pqueue_new (void)
Definition at line 37 of file pqueue.c.
References OPENSSL_zalloc.
Referenced by dtls1_new(), and DTLS_RECORD_LAYER_new().
pqueue_next()
pitem* pqueue_next (piterator * iter)
pqueue_peek()
pitem* pqueue_peek (pqueue * pq)
Definition at line 85 of file pqueue.c.
Referenced by dtls1_process_buffered_records(), and pqueue_iterator().
pqueue_pop()
pitem* pqueue_pop (pqueue * pq)
Definition at line 90 of file pqueue.c.
References NULL.
Referenced by dtls1_clear_received_buffer(), dtls1_clear_sent_buffer(), dtls1_retrieve_buffered_record(), and DTLS_RECORD_LAYER_clear().
pqueue_size()
size_t pqueue_size (pqueue * pq)
Definition at line 144 of file pqueue.c.
References pqueue::count, and NULL.
Referenced by dtls1_buffer_record().
srp_generate_client_master_secret()
__owur int srp_generate_client_master_secret (SSL * s)
Definition at line 310 of file tls_srp.c.
References NULL, and u.
Referenced by tls_client_key_exchange_post_work().
srp_generate_server_master_secret()
__owur int srp_generate_server_master_secret (SSL * s)
Definition at line 284 of file tls_srp.c.
References NULL, and u.
srp_verify_server_param()
__owur int srp_verify_server_param (SSL * s, int * al)
Definition at line 350 of file tls_srp.c.
References SRP_CTX::B, BN_is_zero(), BN_num_bits(), BN_ucmp(), SRP_CTX::g, SRP_CTX::N, SRP_CTX::SRP_cb_arg, SRP_check_known_gN_param(), SRP_CTX::SRP_verify_param_callback, SSL3_AD_ILLEGAL_PARAMETER, SRP_CTX::strength, and TLS1_AD_INSUFFICIENT_SECURITY.
ssl3_alert_code()
__owur int ssl3_alert_code (int code)
Definition at line 527 of file s3_enc.c.
References SSL3_AD_BAD_CERTIFICATE, SSL3_AD_BAD_RECORD_MAC, SSL3_AD_CERTIFICATE_EXPIRED, SSL3_AD_CERTIFICATE_REVOKED, SSL3_AD_CERTIFICATE_UNKNOWN, SSL3_AD_CLOSE_NOTIFY, SSL3_AD_DECOMPRESSION_FAILURE, SSL3_AD_HANDSHAKE_FAILURE, SSL3_AD_ILLEGAL_PARAMETER, SSL3_AD_NO_CERTIFICATE, SSL3_AD_UNEXPECTED_MESSAGE, SSL3_AD_UNSUPPORTED_CERTIFICATE, SSL_AD_ACCESS_DENIED, SSL_AD_BAD_CERTIFICATE, SSL_AD_BAD_CERTIFICATE_HASH_VALUE, SSL_AD_BAD_CERTIFICATE_STATUS_RESPONSE, SSL_AD_BAD_RECORD_MAC, SSL_AD_CERTIFICATE_EXPIRED, SSL_AD_CERTIFICATE_REVOKED, SSL_AD_CERTIFICATE_UNKNOWN, SSL_AD_CERTIFICATE_UNOBTAINABLE, SSL_AD_CLOSE_NOTIFY, SSL_AD_DECODE_ERROR, SSL_AD_DECOMPRESSION_FAILURE, SSL_AD_DECRYPT_ERROR, SSL_AD_DECRYPTION_FAILED, SSL_AD_EXPORT_RESTRICTION, SSL_AD_HANDSHAKE_FAILURE, SSL_AD_ILLEGAL_PARAMETER, SSL_AD_INAPPROPRIATE_FALLBACK, SSL_AD_INSUFFICIENT_SECURITY, SSL_AD_INTERNAL_ERROR, SSL_AD_NO_APPLICATION_PROTOCOL, SSL_AD_NO_CERTIFICATE, SSL_AD_NO_RENEGOTIATION, SSL_AD_PROTOCOL_VERSION, SSL_AD_RECORD_OVERFLOW, SSL_AD_UNEXPECTED_MESSAGE, SSL_AD_UNKNOWN_CA, SSL_AD_UNKNOWN_PSK_IDENTITY, SSL_AD_UNRECOGNIZED_NAME, SSL_AD_UNSUPPORTED_CERTIFICATE, SSL_AD_UNSUPPORTED_EXTENSION, SSL_AD_USER_CANCELLED, TLS1_AD_INAPPROPRIATE_FALLBACK, TLS1_AD_NO_APPLICATION_PROTOCOL, and TLS1_AD_UNKNOWN_PSK_IDENTITY.
ssl3_callback_ctrl()
__owur long ssl3_callback_ctrl (SSL * s, int cmd, void(*)(void) fp)
Definition at line 3276 of file s3_lib.c.
ssl3_cbc_digest_record()
__owur int ssl3_cbc_digest_record (const EVP_MD_CTX * ctx, unsigned char * md_out, size_t * md_out_size, const unsigned char header[13], const unsigned char * data, size_t data_plus_mac_size, size_t data_plus_mac_plus_padding_size, const unsigned char * mac_secret, size_t mac_secret_length, char is_sslv3)
Definition at line 129 of file s3_cbc.c.
ssl3_cbc_record_digest_supported()
__owur char ssl3_cbc_record_digest_supported (const EVP_MD_CTX * ctx)
Definition at line 90 of file s3_cbc.c.
References EVP_MD_CTX_type, FIPS_mode(), NID_md5, NID_sha1, NID_sha224, NID_sha256, NID_sha384, and NID_sha512.
ssl3_change_cipher_state()
__owur int ssl3_change_cipher_state (SSL * s, int which)
Definition at line 104 of file s3_enc.c.
References EVP_MAX_IV_LENGTH, EVP_MAX_KEY_LENGTH, and key.
ssl3_choose_cipher()
__owur const SSL_CIPHER* ssl3_choose_cipher (SSL * ssl, STACK_OF(SSL_CIPHER) * clnt, STACK_OF(SSL_CIPHER) * srvr)
Definition at line 3639 of file s3_lib.c.
ssl3_cleanup_key_block()
void ssl3_cleanup_key_block (SSL * s)
Definition at line 328 of file s3_enc.c.
References NULL, and OPENSSL_clear_free.
Referenced by ssl3_clear(), and ssl3_free().
ssl3_clear()
void ssl3_clear (SSL * s)
Definition at line 2921 of file s3_lib.c.
References EVP_PKEY_free(), NULL, OPENSSL_clear_free, OPENSSL_free, ssl3_cleanup_key_block(), ssl3_free_digest_list(), SSL3_VERSION, and ssl_free_wbio_buffer().
Referenced by tls1_clear().
ssl3_comp_find()
SSL_COMP* ssl3_comp_find (STACK_OF(SSL_COMP) * sk, int n)
Definition at line 1763 of file ssl_ciph.c.
References NULL, SSL_COMP_add_compression_method(), and STACK_OF().
ssl3_ctrl()
__owur long ssl3_ctrl (SSL * s, int cmd, long larg, void * parg)
Definition at line 2962 of file s3_lib.c.
ssl3_ctx_callback_ctrl()
__owur long ssl3_ctx_callback_ctrl (SSL_CTX * s, int cmd, void(*)(void) fp)
Definition at line 3546 of file s3_lib.c.
References fp, SSL_CTRL_SET_NOT_RESUMABLE_SESS_CB, SSL_CTRL_SET_SRP_GIVE_CLIENT_PWD_CB, SSL_CTRL_SET_SRP_VERIFY_PARAM_CB, SSL_CTRL_SET_TLS_EXT_SRP_USERNAME_CB, SSL_CTRL_SET_TLSEXT_SERVERNAME_CB, SSL_CTRL_SET_TLSEXT_STATUS_REQ_CB, SSL_CTRL_SET_TLSEXT_TICKET_KEY_CB, SSL_CTRL_SET_TMP_DH_CB, and SSL_kSRP.
ssl3_ctx_ctrl()
__owur long ssl3_ctx_ctrl (SSL_CTX * s, int cmd, long larg, void * parg)
Definition at line 3304 of file s3_lib.c.
References EC_GROUP_get_curve_name(), EC_KEY_get0_group(), EC_R_MISSING_PARAMETERS, ERR_R_MALLOC_FAILURE, ERR_R_PASSED_NULL_PARAMETER, ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, EVP_PKEY_free(), EVP_PKEY_security_bits(), nid, NID_undef, NULL, SSL_CTRL_GET_TLSEXT_TICKET_KEYS, SSL_CTRL_SET_DH_AUTO, SSL_CTRL_SET_TLSEXT_SERVERNAME_ARG, SSL_CTRL_SET_TLSEXT_TICKET_KEYS, SSL_CTRL_SET_TMP_DH, SSL_CTRL_SET_TMP_DH_CB, SSL_CTRL_SET_TMP_ECDH, ssl_ctx_security(), ssl_dh_to_pkey(), SSL_F_SSL3_CTX_CTRL, SSL_R_DH_KEY_TOO_SMALL, SSL_SECOP_TMP_DH, SSLerr, and tls1_set_groups().
ssl3_default_timeout()
__owur long ssl3_default_timeout (void)
Definition at line 2833 of file s3_lib.c.
ssl3_digest_cached_records()
__owur int ssl3_digest_cached_records (SSL * s, int keep)
Definition at line 376 of file s3_enc.c.
Referenced by tls1_final_finish_mac(), tls1_generate_master_secret(), tls_construct_server_done(), tls_construct_server_hello(), and tls_post_process_client_key_exchange().
ssl3_dispatch_alert()
__owur int ssl3_dispatch_alert (SSL * s)
Definition at line 90 of file s3_msg.c.
References BIO_flush, cb, do_ssl3_write(), NULL, SSL3_AL_FATAL, SSL3_RT_ALERT, SSL_CB_WRITE_ALERT, and type.
ssl3_do_change_cipher_spec()
__owur int ssl3_do_change_cipher_spec (SSL * ssl)
Definition at line 13 of file s3_msg.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL3_CHANGE_CIPHER_CLIENT_READ, SSL3_CHANGE_CIPHER_SERVER_READ, SSL_F_SSL3_DO_CHANGE_CIPHER_SPEC, SSL_R_CCS_RECEIVED_EARLY, and SSLerr.
ssl3_do_write()
__owur int ssl3_do_write (SSL * s, int type)
Definition at line 30 of file statem_lib.c.
Referenced by ssl3_handshake_write().
ssl3_final_finish_mac()
__owur size_t ssl3_final_finish_mac (SSL * s, const char * sender, size_t slen, unsigned char * p)
Definition at line 411 of file s3_enc.c.
ssl3_finish_mac()
__owur int ssl3_finish_mac (SSL * s, const unsigned char * buf, size_t len)
Definition at line 362 of file s3_enc.c.
References NULL.
ssl3_free()
void ssl3_free (SSL * s)
Definition at line 2892 of file s3_lib.c.
References EVP_PKEY_free(), NULL, OPENSSL_clear_free, OPENSSL_free, ssl3_cleanup_key_block(), ssl3_free_digest_list(), and SSL_SRP_CTX_free().
Referenced by dtls1_free(), dtls1_new(), and tls1_free().
ssl3_free_digest_list()
void ssl3_free_digest_list (SSL * s)
Definition at line 354 of file s3_enc.c.
References BIO_free(), EVP_MD_CTX_free(), and NULL.
Referenced by ssl3_clear(), ssl3_free(), and ssl3_init_finished_mac().
ssl3_generate_master_secret()
__owur int ssl3_generate_master_secret (SSL * s, unsigned char * out, unsigned char * p, size_t len, size_t * secret_size)
Definition at line 455 of file s3_enc.c.
ssl3_get_cipher()
__owur const SSL_CIPHER* ssl3_get_cipher (unsigned int u)
Definition at line 2847 of file s3_lib.c.
References SSL3_NUM_CIPHERS.
Referenced by main().
ssl3_get_cipher_by_char()
__owur const SSL_CIPHER* ssl3_get_cipher_by_char (const unsigned char * p)
Definition at line 3610 of file s3_lib.c.
References SSL3_CK_CIPHERSUITE_FLAG, and ssl3_get_cipher_by_id().
ssl3_get_cipher_by_id()
__owur const SSL_CIPHER* ssl3_get_cipher_by_id (uint32_t id)
Definition at line 3598 of file s3_lib.c.
Referenced by ssl3_get_cipher_by_char().
ssl3_get_req_cert_type()
__owur int ssl3_get_req_cert_type (SSL * s, WPACKET * pkt)
Definition at line 3759 of file s3_lib.c.
References SSL3_CT_DSS_EPHEMERAL_DH, SSL3_CT_DSS_SIGN, SSL3_CT_RSA_EPHEMERAL_DH, SSL3_CT_RSA_SIGN, SSL3_VERSION, SSL_aDSS, SSL_aECDSA, SSL_aRSA, SSL_kDHE, SSL_kGOST, SSL_SECOP_SIGALG_MASK, ssl_set_sig_mask(), TLS1_VERSION, TLS_CT_ECDSA_SIGN, TLS_CT_GOST01_SIGN, TLS_CT_GOST12_512_SIGN, TLS_CT_GOST12_SIGN, WPACKET_memcpy(), and WPACKET_put_bytes_u8.
ssl3_handshake_write()
__owur int ssl3_handshake_write (SSL * s)
Definition at line 2869 of file s3_lib.c.
References ssl3_do_write(), and SSL3_RT_HANDSHAKE.
ssl3_init_finished_mac()
int ssl3_init_finished_mac (SSL * s)
Definition at line 335 of file s3_enc.c.
References BIO_new(), BIO_s_mem(), ERR_R_MALLOC_FAILURE, NULL, ssl3_free_digest_list(), SSL_F_SSL3_INIT_FINISHED_MAC, and SSLerr.
Referenced by ossl_statem_client_pre_work(), ossl_statem_server_post_work(), and tls_setup_handshake().
ssl3_new()
__owur int ssl3_new (SSL * s)
Definition at line 2874 of file s3_lib.c.
References NULL, OPENSSL_zalloc, and SSL_SRP_CTX_init().
Referenced by dtls1_new(), and tls1_new().
ssl3_num_ciphers()
__owur int ssl3_num_ciphers (void)
Definition at line 2842 of file s3_lib.c.
References SSL3_NUM_CIPHERS.
Referenced by main().
ssl3_output_cert_chain()
__owur unsigned long ssl3_output_cert_chain (SSL * s, WPACKET * pkt, CERT_PKEY * cpk, int * al)
Definition at line 864 of file statem_lib.c.
References SSL_AD_INTERNAL_ERROR, and WPACKET_start_sub_packet_u24.
Referenced by tls_construct_client_certificate(), and tls_construct_server_certificate().
ssl3_peek()
__owur int ssl3_peek (SSL * s, void * buf, size_t len, size_t * readbytes)
Definition at line 3925 of file s3_lib.c.
ssl3_put_cipher_by_char()
__owur int ssl3_put_cipher_by_char (const SSL_CIPHER * c, WPACKET * pkt, size_t * len)
Definition at line 3617 of file s3_lib.c.
References SSL3_CK_CIPHERSUITE_FLAG, and WPACKET_put_bytes_u16.
ssl3_read()
__owur int ssl3_read (SSL * s, void * buf, size_t len, size_t * readbytes)
Definition at line 3920 of file s3_lib.c.
ssl3_renegotiate()
int ssl3_renegotiate (SSL * ssl)
Definition at line 3930 of file s3_lib.c.
References NULL.
ssl3_renegotiate_check()
int ssl3_renegotiate_check (SSL * ssl, int initok)
Definition at line 3947 of file s3_lib.c.
ssl3_send_alert()
int ssl3_send_alert (SSL * s, int level, int desc)
Definition at line 63 of file s3_msg.c.
References NULL, RECORD_LAYER_write_pending(), SSL3_AL_FATAL, SSL3_VERSION, SSL_AD_HANDSHAKE_FAILURE, SSL_AD_PROTOCOL_VERSION, and SSL_CTX_remove_session().
Referenced by dtls_construct_change_cipher_spec(), ossl_statem_server_read_transition(), tls1_set_server_sigalgs(), tls_client_key_exchange_post_work(), tls_construct_cert_status(), tls_construct_change_cipher_spec(), tls_construct_client_certificate(), tls_construct_finished(), tls_construct_key_update(), tls_construct_next_proto(), tls_construct_server_certificate(), tls_construct_server_done(), tls_construct_server_hello(), tls_get_message_header(), tls_prepare_client_certificate(), tls_process_cert_status(), and tls_setup_handshake().
ssl3_set_handshake_header()
__owur int ssl3_set_handshake_header (SSL * s, WPACKET * pkt, int htype)
Definition at line 2855 of file s3_lib.c.
References SSL3_MT_CHANGE_CIPHER_SPEC, WPACKET_put_bytes_u8, and WPACKET_start_sub_packet_u24.
ssl3_setup_key_block()
__owur int ssl3_setup_key_block (SSL * s)
Definition at line 261 of file s3_enc.c.
ssl3_shutdown()
__owur int ssl3_shutdown (SSL * s)
Definition at line 3828 of file s3_lib.c.
ssl3_write()
__owur int ssl3_write (SSL * s, const void * buf, size_t len, size_t * written)
Definition at line 3879 of file s3_lib.c.
ssl_allow_compression()
__owur int ssl_allow_compression (SSL * s)
Definition at line 1222 of file statem_lib.c.
References NULL, SSL_OP_NO_COMPRESSION, SSL_SECOP_COMPRESSION, and ssl_security().
Referenced by ssl3_setup_read_buffer(), and ssl3_setup_write_buffer().
ssl_bad_method()
__owur const SSL_METHOD* ssl_bad_method (int ver)
Definition at line 3104 of file ssl_lib.c.
References ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, NULL, SSL_F_SSL_BAD_METHOD, and SSLerr.
ssl_build_cert_chain()
__owur int ssl_build_cert_chain (SSL * s, SSL_CTX * ctx, int flags)
Definition at line 747 of file ssl_cert.c.
References CERT::cert_flags, CERT::chain_store, ERR_add_error_data(), ERR_clear_error(), ERR_GET_LIB, ERR_GET_REASON, ERR_LIB_X509, ERR_peek_last_error(), ERR_R_MALLOC_FAILURE, ERR_R_X509_LIB, EXFLAG_SS, CERT::key, NULL, SSL_BUILD_CHAIN_FLAG_CHECK, SSL_BUILD_CHAIN_FLAG_CLEAR_ERROR, SSL_BUILD_CHAIN_FLAG_IGNORE_ERROR, SSL_BUILD_CHAIN_FLAG_NO_ROOT, SSL_BUILD_CHAIN_FLAG_UNTRUSTED, SSL_CERT_FLAG_SUITEB_128_LOS, SSL_F_SSL_BUILD_CERT_CHAIN, SSL_R_CERTIFICATE_VERIFY_FAILED, SSL_R_NO_CERTIFICATE_SET, ssl_security_cert(), SSLerr, STACK_OF(), X509_get_extension_flags(), X509_R_CERT_ALREADY_IN_HASH_TABLE, X509_STORE_add_cert(), X509_STORE_CTX_free(), X509_STORE_CTX_get_error(), X509_STORE_CTX_init(), X509_STORE_CTX_new(), X509_STORE_CTX_set_flags(), X509_STORE_free(), X509_STORE_new(), X509_verify_cert(), and X509_verify_cert_error_string().
ssl_cert_add0_chain_cert()
__owur int ssl_cert_add0_chain_cert (SSL * s, SSL_CTX * ctx, X509 * x)
Definition at line 300 of file ssl_cert.c.
References SSL_F_SSL_CERT_ADD0_CHAIN_CERT, ssl_security_cert(), and SSLerr.
Referenced by ssl_cert_add1_chain_cert().
ssl_cert_add1_chain_cert()
__owur int ssl_cert_add1_chain_cert (SSL * s, SSL_CTX * ctx, X509 * x)
Definition at line 318 of file ssl_cert.c.
References ssl_cert_add0_chain_cert(), and X509_up_ref().
ssl_cert_clear_certs()
void ssl_cert_clear_certs (CERT * c)
Definition at line 215 of file ssl_cert.c.
Referenced by SSL_certs_clear().
ssl_cert_dup()
__owur CERT* ssl_cert_dup (CERT * cert)
Definition at line 81 of file ssl_cert.c.
Referenced by SSL_new(), and SSL_set_SSL_CTX().
ssl_cert_free()
void ssl_cert_free (CERT * c)
Definition at line 234 of file ssl_cert.c.
Referenced by SSL_copy_session_id(), and SSL_set_SSL_CTX().
ssl_cert_get0_next_certificate()
__owur X509* ssl_cert_get0_next_certificate (CERT * c, int first)
ssl_cert_new()
__owur CERT* ssl_cert_new (void)
Definition at line 57 of file ssl_cert.c.
ssl_cert_select_current()
__owur int ssl_cert_select_current (CERT * c, X509 * x)
Definition at line 326 of file ssl_cert.c.
ssl_cert_set0_chain()
__owur int ssl_cert_set0_chain (SSL * s, SSL_CTX * ctx, STACK_OF(X509) * chain)
Definition at line 267 of file ssl_cert.c.
References SSL_F_SSL_CERT_SET0_CHAIN, ssl_security_cert(), and SSLerr.
Referenced by ssl_cert_set1_chain().
ssl_cert_set1_chain()
__owur int ssl_cert_set1_chain (SSL * s, SSL_CTX * ctx, STACK_OF(X509) * chain)
Definition at line 285 of file ssl_cert.c.
References NULL, ssl_cert_set0_chain(), and STACK_OF().
ssl_cert_set_cert_cb()
void ssl_cert_set_cert_cb (CERT * c, int(*)(SSL *ssl, void *arg) cb, void * arg)
Definition at line 372 of file ssl_cert.c.
ssl_cert_set_cert_store()
__owur int ssl_cert_set_cert_store (CERT * c, X509_STORE * store, int chain, int ref)
Definition at line 866 of file ssl_cert.c.
References CERT::chain_store, CERT::verify_store, X509_STORE_free(), and X509_STORE_up_ref().
ssl_cert_set_current()
__owur int ssl_cert_set_current (CERT * c, long arg)
Definition at line 349 of file ssl_cert.c.
ssl_cert_type()
__owur int ssl_cert_type (const X509 * x, const EVP_PKEY * pkey)
Definition at line 1126 of file statem_lib.c.
References EVP_PKEY_DSA, EVP_PKEY_EC, EVP_PKEY_id(), EVP_PKEY_RSA, NID_id_GostR3410_2001, NID_id_GostR3410_2012_256, NID_id_GostR3410_2012_512, NULL, SSL_PKEY_DSA_SIGN, SSL_PKEY_ECC, SSL_PKEY_GOST01, SSL_PKEY_GOST12_256, SSL_PKEY_GOST12_512, SSL_PKEY_RSA, and X509_get0_pubkey().
ssl_check_srvr_ecc_cert_and_alg()
__owur int ssl_check_srvr_ecc_cert_and_alg (X509 * x, SSL * s)
Definition at line 2852 of file ssl_lib.c.
References SSL_aECDSA, SSL_F_SSL_CHECK_SRVR_ECC_CERT_AND_ALG, SSL_R_ECC_CERT_NOT_FOR_SIGNING, SSLerr, X509_get_key_usage(), and X509v3_KU_DIGITAL_SIGNATURE.
ssl_check_version_downgrade()
__owur int ssl_check_version_downgrade (SSL * s)
Definition at line 1377 of file statem_lib.c.
ssl_choose_client_version()
__owur int ssl_choose_client_version (SSL * s, int version)
Definition at line 1622 of file statem_lib.c.
References SSL_R_WRONG_SSL_VERSION, TLS1_3_VERSION, TLS1_3_VERSION_DRAFT, and TLS_ANY_VERSION.
ssl_choose_server_version()
__owur int ssl_choose_server_version (SSL * s, CLIENTHELLO_MSG * hello)
Definition at line 1476 of file statem_lib.c.
References CLIENTHELLO_MSG::legacy_version, and SSL_IS_TLS13.
ssl_cipher_disabled()
__owur int ssl_cipher_disabled (SSL * s, const SSL_CIPHER * c, int op)
Definition at line 1041 of file t1_lib.c.
ssl_cipher_get_cert_index()
__owur int ssl_cipher_get_cert_index (const SSL_CIPHER * c)
Definition at line 1901 of file ssl_ciph.c.
References SSL_aDSS, SSL_aECDSA, SSL_aGOST01, SSL_aGOST12, SSL_aRSA, SSL_PKEY_DSA_SIGN, SSL_PKEY_ECC, SSL_PKEY_GOST01, SSL_PKEY_GOST_EC, and SSL_PKEY_RSA.
ssl_cipher_get_evp()
__owur int ssl_cipher_get_evp (const SSL_SESSION * s, const EVP_CIPHER ** enc, const EVP_MD ** md, int * mac_pkey_type, size_t * mac_secret_size, SSL_COMP ** comp, int use_etm)
Definition at line 506 of file ssl_ciph.c.
Referenced by SSL_SESSION_print().
ssl_cipher_get_overhead()
__owur int ssl_cipher_get_overhead (const SSL_CIPHER * c, size_t * mac_overhead, size_t * int_overhead, size_t * blocksize, size_t * ext_overhead)
Definition at line 1978 of file ssl_ciph.c.
References in.
Referenced by DTLS_get_data_mtu(), and main().
ssl_cipher_id_cmp()
__owur int ssl_cipher_id_cmp (const SSL_CIPHER * a, const SSL_CIPHER * b)
Definition at line 2024 of file ssl_lib.c.
ssl_cipher_ptr_id_cmp()
__owur int ssl_cipher_ptr_id_cmp (const SSL_CIPHER *const * ap, const SSL_CIPHER *const * bp)
Definition at line 2033 of file ssl_lib.c.
ssl_clear_bad_session()
int ssl_clear_bad_session (SSL * s)
Definition at line 1031 of file ssl_sess.c.
References NULL, SSL_CTX_remove_session(), SSL_in_before(), SSL_in_init(), and SSL_SENT_SHUTDOWN.
Referenced by SSL_clear(), and SSL_set_session().
ssl_clear_cipher_ctx()
void ssl_clear_cipher_ctx (SSL * s)
Definition at line 3275 of file ssl_lib.c.
References COMP_CTX_free(), EVP_CIPHER_CTX_free(), and NULL.
ssl_clear_hash_ctx()
void ssl_clear_hash_ctx (EVP_MD_CTX ** hash)
Definition at line 3759 of file ssl_lib.c.
References EVP_MD_CTX_free(), and NULL.
ssl_comp_free_compression_methods_int()
void ssl_comp_free_compression_methods_int (void)
Definition at line 1816 of file ssl_ciph.c.
References NULL, and STACK_OF().
ssl_ctx_security()
__owur int ssl_ctx_security (const SSL_CTX * ctx, int op, int bits, int nid, void * other)
Definition at line 967 of file ssl_cert.c.
References NULL.
Referenced by ssl3_ctx_ctrl().
ssl_derive()
__owur int ssl_derive (SSL * s, EVP_PKEY * privkey, EVP_PKEY * pubkey, int genmaster)
Definition at line 4136 of file s3_lib.c.
Referenced by tls_construct_stoc_key_share().
ssl_dh_to_pkey()
__owur EVP_PKEY* ssl_dh_to_pkey (DH * dh)
Definition at line 4193 of file s3_lib.c.
Referenced by ssl3_ctx_ctrl().
ssl_fill_hello_random()
__owur int ssl_fill_hello_random (SSL * s, int server, unsigned char * field, size_t len)
Definition at line 3996 of file s3_lib.c.
References l2n, NULL, RAND_bytes(), SSL_MODE_SEND_CLIENTHELLO_TIME, and SSL_MODE_SEND_SERVERHELLO_TIME.
ssl_free_wbio_buffer()
void ssl_free_wbio_buffer (SSL * s)
Definition at line 3371 of file ssl_lib.c.
References BIO_free(), BIO_pop(), and NULL.
Referenced by ssl3_clear().
ssl_generate_master_secret()
__owur int ssl_generate_master_secret (SSL * s, unsigned char * pms, size_t pmslen, int free_pms)
Definition at line 4016 of file s3_lib.c.
Referenced by tls_client_key_exchange_post_work().
ssl_generate_pkey()
__owur EVP_PKEY* ssl_generate_pkey (EVP_PKEY * pm)
Definition at line 4080 of file s3_lib.c.
Referenced by tls_construct_stoc_key_share().
ssl_generate_pkey_curve()
__owur EVP_PKEY* ssl_generate_pkey_curve (int id)
Definition at line 4103 of file s3_lib.c.
ssl_get_algorithm2()
__owur long ssl_get_algorithm2 (SSL * s)
Definition at line 3976 of file s3_lib.c.
References NULL, SSL_ENC_FLAG_SHA256_PRF, SSL_HANDSHAKE_MAC_DEFAULT, SSL_HANDSHAKE_MAC_SHA256, SSL_HANDSHAKE_MAC_SHA384, SSL_PSK, TLS1_PRF, TLS1_PRF_SHA256, and TLS1_PRF_SHA384.
Referenced by ssl_handshake_md(), and ssl_prf_md().
ssl_get_auto_dh()
__owur DH* ssl_get_auto_dh (SSL * s)
Definition at line 2141 of file t1_lib.c.
References BN_free(), BN_get_rfc3526_prime_3072(), BN_get_rfc3526_prime_8192(), BN_new(), BN_set_word(), DH_free(), DH_get_1024_160(), DH_get_2048_224(), DH_new(), DH_set0_pqg(), EVP_PKEY_security_bits(), NULL, SSL_aNULL, and SSL_aPSK.
ssl_get_cipher_by_char()
__owur const SSL_CIPHER* ssl_get_cipher_by_char (SSL * ssl, const unsigned char * ptr)
Definition at line 1921 of file ssl_ciph.c.
References NULL.
ssl_get_client_min_max_version()
int ssl_get_client_min_max_version (const SSL * s, int * min_version, int * max_version)
Definition at line 1693 of file statem_lib.c.
References NULL, TLS_ANY_VERSION, and version_info::version.
Referenced by ssl_set_client_disabled(), tls_construct_ctos_supported_versions(), and tls_construct_extensions().
ssl_get_new_session()
__owur int ssl_get_new_session (SSL * s, int session)
Definition at line 303 of file ssl_sess.c.
References cb, and NULL.
Referenced by tls_construct_client_hello().
ssl_get_prev_session()
__owur int ssl_get_prev_session (SSL * s, CLIENTHELLO_MSG * hello, int * al)
Definition at line 461 of file ssl_sess.c.
ssl_get_server_cert_serverinfo()
__owur int ssl_get_server_cert_serverinfo (SSL * s, const unsigned char ** serverinfo, size_t * serverinfo_length)
Definition at line 2867 of file ssl_lib.c.
References NULL.
ssl_handshake_hash()
__owur int ssl_handshake_hash (SSL * s, unsigned char * out, size_t outlen, size_t * hashlen)
Definition at line 3767 of file ssl_lib.c.
Referenced by tls1_final_finish_mac(), and tls1_generate_master_secret().
ssl_handshake_md()
__owur const EVP_MD* ssl_handshake_md (SSL * s)
Definition at line 619 of file ssl_ciph.c.
References EVP_sha256(), ssl_get_algorithm2(), and ssl_md().
Referenced by tls13_derive_key(), and tls13_generate_handshake_secret().
ssl_init_wbio_buffer()
__owur int ssl_init_wbio_buffer (SSL * s)
Definition at line 3350 of file ssl_lib.c.
References BIO_f_buffer(), BIO_free(), BIO_new(), BIO_push(), BIO_set_read_buffer_size, ERR_R_BUF_LIB, NULL, SSL_F_SSL_INIT_WBIO_BUFFER, and SSLerr.
ssl_load_ciphers()
void ssl_load_ciphers (void)
Definition at line 377 of file ssl_ciph.c.
References t.
Referenced by DEFINE_RUN_ONCE_STATIC().
ssl_log_rsa_client_key_exchange()
__owur int ssl_log_rsa_client_key_exchange (SSL * ssl, const uint8_t * encrypted_premaster, size_t encrypted_premaster_len, const uint8_t * premaster, size_t premaster_len)
Definition at line 4372 of file ssl_lib.c.
References ERR_R_INTERNAL_ERROR, SSL_F_SSL_LOG_RSA_CLIENT_KEY_EXCHANGE, and SSLerr.
ssl_log_secret()
__owur int ssl_log_secret (SSL * ssl, const char * label, const uint8_t * secret, size_t secret_len)
Definition at line 4392 of file ssl_lib.c.
Referenced by tls_construct_finished().
ssl_md()
__owur const EVP_MD* ssl_md (int idx)
Definition at line 611 of file ssl_ciph.c.
Referenced by ssl_handshake_md(), ssl_prf_md(), and ssl_set_default_md().
ssl_ok()
__owur int ssl_ok (SSL * s)
Definition at line 3587 of file ssl_lib.c.
ssl_prf_md()
__owur const EVP_MD* ssl_prf_md (SSL * s)
Definition at line 624 of file ssl_ciph.c.
References ssl_get_algorithm2(), ssl_md(), and TLS1_PRF_DGST_SHIFT.
ssl_protocol_to_string()
const char* ssl_protocol_to_string (int version)
Definition at line 3110 of file ssl_lib.c.
References DTLS1_2_VERSION, DTLS1_BAD_VER, DTLS1_VERSION, SSL3_VERSION, TLS1_1_VERSION, TLS1_2_VERSION, TLS1_3_VERSION, and TLS1_VERSION.
Referenced by SSL_CIPHER_get_version(), SSL_get_version(), and SSL_SESSION_print().
ssl_replace_hash()
__owur EVP_MD_CTX* ssl_replace_hash (EVP_MD_CTX ** hash, const EVP_MD * md)
Definition at line 3747 of file ssl_lib.c.
ssl_security()
__owur int ssl_security (const SSL * s, int op, int bits, int nid, void * other)
Definition at line 962 of file ssl_cert.c.
References NULL.
Referenced by ssl_allow_compression(), tls_curve_allowed(), and tls_use_ticket().
ssl_security_cert()
__owur int ssl_security_cert (SSL * s, SSL_CTX * ctx, X509 * x, int vfy, int is_ee)
Definition at line 2221 of file t1_lib.c.
References SSL_SECOP_PEER.
Referenced by ssl_build_cert_chain(), ssl_cert_add0_chain_cert(), ssl_cert_set0_chain(), SSL_CTX_use_certificate(), ssl_security_cert_chain(), and SSL_use_certificate().
ssl_security_cert_chain()
__owur int ssl_security_cert_chain (SSL * s, STACK_OF(X509) * sk, X509 * ex, int vfy)
Definition at line 2243 of file t1_lib.c.
References NULL, and ssl_security_cert().
ssl_session_dup()
__owur SSL_SESSION* ssl_session_dup (SSL_SESSION * src, int ticket)
Definition at line 126 of file ssl_sess.c.
References CRYPTO_dup_ex_data(), CRYPTO_EX_INDEX_SSL_SESSION, CRYPTO_THREAD_lock_new(), ERR_R_MALLOC_FAILURE, NULL, OPENSSL_malloc, OPENSSL_memdup, OPENSSL_strdup, SSL_F_SSL_SESSION_DUP, SSL_SESSION_free(), SSLerr, and X509_up_ref().
ssl_set_client_disabled()
void ssl_set_client_disabled (SSL * s)
Definition at line 1012 of file t1_lib.c.
References SSL_aPSK, SSL_aSRP, ssl_get_client_min_max_version(), SSL_kSRP, SSL_PSK, SSL_SECOP_SIGALG_MASK, and ssl_set_sig_mask().
Referenced by STACK_OF().
ssl_set_client_hello_version()
__owur int ssl_set_client_hello_version (SSL * s)
Definition at line 1784 of file statem_lib.c.
Referenced by tls_construct_client_hello().
ssl_set_default_md()
void ssl_set_default_md (SSL * s)
Definition at line 1066 of file t1_lib.c.
References ssl_md(), SSL_MD_GOST12_256_IDX, SSL_MD_GOST12_512_IDX, SSL_MD_GOST94_IDX, SSL_MD_MD5_SHA1_IDX, SSL_MD_SHA1_IDX, SSL_PKEY_DSA_SIGN, SSL_PKEY_ECC, SSL_PKEY_GOST01, SSL_PKEY_GOST12_256, SSL_PKEY_GOST12_512, SSL_PKEY_RSA, and SSL_USE_SIGALGS.
Referenced by tls1_set_server_sigalgs().
ssl_set_masks()
void ssl_set_masks (SSL * s)
Definition at line 2752 of file ssl_lib.c.
References CERT_PKEY_SIGN, CERT_PKEY_VALID, CERT::dh_tmp, CERT::dh_tmp_auto, CERT::dh_tmp_cb, NULL, SSL_PKEY_DSA_SIGN, SSL_PKEY_ECC, and SSL_PKEY_RSA.
ssl_set_sig_mask()
void ssl_set_sig_mask (uint32_t * pmask_a, SSL * s, int op)
Definition at line 1414 of file t1_lib.c.
References tls12_get_psigalgs().
Referenced by ssl3_get_req_cert_type(), and ssl_set_client_disabled().
ssl_set_version_bound()
__owur int ssl_set_version_bound (int method_version, int version, int * bound)
Definition at line 1422 of file statem_lib.c.
References DTLS1_BAD_VER, DTLS_ANY_VERSION, DTLS_MAX_VERSION, DTLS_VERSION_GT, DTLS_VERSION_LT, TLS_ANY_VERSION, and TLS_MAX_VERSION.
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
ssl_sort_cipher_list()
void ssl_sort_cipher_list (void)
Definition at line 2808 of file s3_lib.c.
ssl_undefined_const_function()
__owur int ssl_undefined_const_function (const SSL * s)
Definition at line 3099 of file ssl_lib.c.
ssl_undefined_function()
int ssl_undefined_function (SSL * s)
Definition at line 3086 of file ssl_lib.c.
References ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, SSL_F_SSL_UNDEFINED_FUNCTION, and SSLerr.
Referenced by SSL_new().
ssl_undefined_void_function()
__owur int ssl_undefined_void_function (void)
Definition at line 3092 of file ssl_lib.c.
References ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, SSL_F_SSL_UNDEFINED_VOID_FUNCTION, and SSLerr.
ssl_update_cache()
void ssl_update_cache (SSL * s, int mode)
Definition at line 2881 of file ssl_lib.c.
References NULL, SSL_CTX_add_session(), SSL_CTX_flush_sessions(), SSL_SESS_CACHE_CLIENT, SSL_SESS_CACHE_NO_AUTO_CLEAR, SSL_SESS_CACHE_NO_INTERNAL_STORE, SSL_SESSION_free(), and SSL_SESSION_up_ref().
ssl_validate_ct()
__owur int ssl_validate_ct (SSL * s)
Definition at line 4165 of file ssl_lib.c.
ssl_verify_alarm_type()
__owur int ssl_verify_alarm_type (long type)
Definition at line 1153 of file statem_lib.c.
References SSL_AD_BAD_CERTIFICATE, SSL_AD_CERTIFICATE_EXPIRED, SSL_AD_CERTIFICATE_REVOKED, SSL_AD_CERTIFICATE_UNKNOWN, SSL_AD_DECRYPT_ERROR, SSL_AD_HANDSHAKE_FAILURE, SSL_AD_INTERNAL_ERROR, SSL_AD_UNKNOWN_CA, SSL_AD_UNSUPPORTED_CERTIFICATE, X509_V_ERR_APPLICATION_VERIFICATION, X509_V_ERR_CA_KEY_TOO_SMALL, X509_V_ERR_CA_MD_TOO_WEAK, X509_V_ERR_CERT_CHAIN_TOO_LONG, X509_V_ERR_CERT_HAS_EXPIRED, X509_V_ERR_CERT_NOT_YET_VALID, X509_V_ERR_CERT_REJECTED, X509_V_ERR_CERT_REVOKED, X509_V_ERR_CERT_SIGNATURE_FAILURE, X509_V_ERR_CERT_UNTRUSTED, X509_V_ERR_CRL_HAS_EXPIRED, X509_V_ERR_CRL_NOT_YET_VALID, X509_V_ERR_CRL_SIGNATURE_FAILURE, X509_V_ERR_DANE_NO_MATCH, X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT, X509_V_ERR_EE_KEY_TOO_SMALL, X509_V_ERR_EMAIL_MISMATCH, X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD, X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD, X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD, X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD, X509_V_ERR_HOSTNAME_MISMATCH, X509_V_ERR_INVALID_CA, X509_V_ERR_INVALID_CALL, X509_V_ERR_INVALID_PURPOSE, X509_V_ERR_IP_ADDRESS_MISMATCH, X509_V_ERR_OUT_OF_MEM, X509_V_ERR_PATH_LENGTH_EXCEEDED, X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN, X509_V_ERR_STORE_LOOKUP, X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY, X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE, X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE, X509_V_ERR_UNABLE_TO_GET_CRL, X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER, X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT, X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY, X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE, and X509_V_ERR_UNSPECIFIED.
ssl_verify_cert_chain()
__owur int ssl_verify_cert_chain (SSL * s, STACK_OF(X509) * sk)
Definition at line 378 of file ssl_cert.c.
References DANETLS_ENABLED, ERR_R_MALLOC_FAILURE, ERR_R_X509_LIB, NULL, SSL_F_SSL_VERIFY_CERT_CHAIN, SSL_get_ex_data_X509_STORE_CTX_idx(), SSL_get_security_level(), SSLerr, tls1_suiteb, X509_STORE_CTX_free(), X509_STORE_CTX_get0_param(), X509_STORE_CTX_get_error(), X509_STORE_CTX_init(), X509_STORE_CTX_new(), X509_STORE_CTX_set0_dane(), X509_STORE_CTX_set_default(), X509_STORE_CTX_set_ex_data(), X509_STORE_CTX_set_flags(), X509_STORE_CTX_set_verify_cb(), X509_verify_cert(), X509_VERIFY_PARAM_move_peername(), X509_VERIFY_PARAM_set1(), and X509_VERIFY_PARAM_set_auth_level().
ssl_version_supported()
__owur int ssl_version_supported (const SSL * s, int version)
Definition at line 1339 of file statem_lib.c.
Referenced by tls_construct_client_hello().
sslv3_client_method()
__owur const SSL_METHOD* sslv3_client_method (void)
Referenced by SSLv3_client_method().
sslv3_method()
__owur const SSL_METHOD* sslv3_method (void)
Referenced by SSLv3_method().
sslv3_server_method()
__owur const SSL_METHOD* sslv3_server_method (void)
Referenced by SSLv3_server_method().
STACK_OF()
__owur STACK_OF (SSL_CIPHER) const
tls12_check_peer_sigalg()
__owur int tls12_check_peer_sigalg (SSL * s, uint16_t , EVP_PKEY * pkey)
Definition at line 887 of file t1_lib.c.
tls12_copy_sigalgs()
__owur int tls12_copy_sigalgs (SSL * s, WPACKET * pkt, const uint16_t * psig, size_t psiglen)
Definition at line 1457 of file t1_lib.c.
Referenced by tls_construct_ctos_sig_algs().
tls12_get_psigalgs()
__owur size_t tls12_get_psigalgs (SSL * s, int sent, const uint16_t ** psigs)
Definition at line 844 of file t1_lib.c.
References SSL_CERT_FLAG_SUITEB_128_LOS, and tls1_suiteb.
Referenced by ssl_set_sig_mask(), and tls_construct_ctos_sig_algs().
tls13_alert_code()
__owur int tls13_alert_code (int code)
Definition at line 501 of file tls13_enc.c.
References code, SSL_AD_MISSING_EXTENSION, and tls1_alert_code().
tls13_change_cipher_state()
__owur int tls13_change_cipher_state (SSL * s, int which)
Definition at line 313 of file tls13_enc.c.
tls13_derive_finishedkey()
__owur int tls13_derive_finishedkey (SSL * s, const EVP_MD * md, const unsigned char * secret, unsigned char * fin, size_t finlen)
Definition at line 102 of file tls13_enc.c.
tls13_derive_iv()
__owur int tls13_derive_iv (SSL * s, const unsigned char * secret, unsigned char * iv, size_t ivlen)
Definition at line 93 of file tls13_enc.c.
tls13_derive_key()
__owur int tls13_derive_key (SSL * s, const unsigned char * secret, unsigned char * key, size_t keylen)
Definition at line 80 of file tls13_enc.c.
References NULL, ssl_handshake_md(), and tls13_hkdf_expand().
tls13_final_finish_mac()
__owur size_t tls13_final_finish_mac (SSL * s, const char * str, size_t slen, unsigned char * p)
Definition at line 189 of file tls13_enc.c.
tls13_generate_handshake_secret()
__owur int tls13_generate_handshake_secret (SSL * s, const unsigned char * insecret, size_t insecretlen)
Definition at line 162 of file tls13_enc.c.
References ssl_handshake_md(), and tls13_generate_secret().
Referenced by tls_construct_stoc_key_share().
tls13_generate_master_secret()
__owur int tls13_generate_master_secret (SSL * s, unsigned char * out, unsigned char * prev, size_t prevlen, size_t * secret_size)
Definition at line 175 of file tls13_enc.c.
tls13_generate_secret()
int tls13_generate_secret (SSL * s, const EVP_MD * md, const unsigned char * prevsecret, const unsigned char * insecret, size_t insecretlen, unsigned char * outsecret)
Definition at line 117 of file tls13_enc.c.
Referenced by tls13_generate_handshake_secret().
tls13_hkdf_expand()
__owur int tls13_hkdf_expand (SSL * s, const EVP_MD * md, const unsigned char * secret, const unsigned char * label, size_t labellen, const unsigned char * hash, unsigned char * out, size_t outlen)
Definition at line 26 of file tls13_enc.c.
Referenced by tls13_derive_key().
tls13_setup_key_block()
__owur int tls13_setup_key_block (SSL * s)
Definition at line 226 of file tls13_enc.c.
tls13_update_key()
__owur int tls13_update_key (SSL * s, int send)
Definition at line 462 of file tls13_enc.c.
Referenced by ossl_statem_client_post_work(), and ossl_statem_server_post_work().
tls1_alert_code()
__owur int tls1_alert_code (int code)
Definition at line 642 of file t1_enc.c.
References code, SSL3_AD_BAD_CERTIFICATE, SSL3_AD_BAD_RECORD_MAC, SSL3_AD_CERTIFICATE_EXPIRED, SSL3_AD_CERTIFICATE_REVOKED, SSL3_AD_CERTIFICATE_UNKNOWN, SSL3_AD_CLOSE_NOTIFY, SSL3_AD_DECOMPRESSION_FAILURE, SSL3_AD_HANDSHAKE_FAILURE, SSL3_AD_ILLEGAL_PARAMETER, SSL3_AD_UNEXPECTED_MESSAGE, SSL3_AD_UNSUPPORTED_CERTIFICATE, SSL_AD_ACCESS_DENIED, SSL_AD_BAD_CERTIFICATE, SSL_AD_BAD_CERTIFICATE_HASH_VALUE, SSL_AD_BAD_CERTIFICATE_STATUS_RESPONSE, SSL_AD_BAD_RECORD_MAC, SSL_AD_CERTIFICATE_EXPIRED, SSL_AD_CERTIFICATE_REVOKED, SSL_AD_CERTIFICATE_UNKNOWN, SSL_AD_CERTIFICATE_UNOBTAINABLE, SSL_AD_CLOSE_NOTIFY, SSL_AD_DECODE_ERROR, SSL_AD_DECOMPRESSION_FAILURE, SSL_AD_DECRYPT_ERROR, SSL_AD_DECRYPTION_FAILED, SSL_AD_EXPORT_RESTRICTION, SSL_AD_HANDSHAKE_FAILURE, SSL_AD_ILLEGAL_PARAMETER, SSL_AD_INAPPROPRIATE_FALLBACK, SSL_AD_INSUFFICIENT_SECURITY, SSL_AD_INTERNAL_ERROR, SSL_AD_NO_APPLICATION_PROTOCOL, SSL_AD_NO_CERTIFICATE, SSL_AD_NO_RENEGOTIATION, SSL_AD_PROTOCOL_VERSION, SSL_AD_RECORD_OVERFLOW, SSL_AD_UNEXPECTED_MESSAGE, SSL_AD_UNKNOWN_CA, SSL_AD_UNKNOWN_PSK_IDENTITY, SSL_AD_UNRECOGNIZED_NAME, SSL_AD_UNSUPPORTED_CERTIFICATE, SSL_AD_UNSUPPORTED_EXTENSION, SSL_AD_USER_CANCELLED, TLS1_AD_ACCESS_DENIED, TLS1_AD_BAD_CERTIFICATE_HASH_VALUE, TLS1_AD_BAD_CERTIFICATE_STATUS_RESPONSE, TLS1_AD_CERTIFICATE_UNOBTAINABLE, TLS1_AD_DECODE_ERROR, TLS1_AD_DECRYPT_ERROR, TLS1_AD_DECRYPTION_FAILED, TLS1_AD_EXPORT_RESTRICTION, TLS1_AD_INAPPROPRIATE_FALLBACK, TLS1_AD_INSUFFICIENT_SECURITY, TLS1_AD_INTERNAL_ERROR, TLS1_AD_NO_APPLICATION_PROTOCOL, TLS1_AD_NO_RENEGOTIATION, TLS1_AD_PROTOCOL_VERSION, TLS1_AD_RECORD_OVERFLOW, TLS1_AD_UNKNOWN_CA, TLS1_AD_UNKNOWN_PSK_IDENTITY, TLS1_AD_UNRECOGNIZED_NAME, TLS1_AD_UNSUPPORTED_EXTENSION, and TLS1_AD_USER_CANCELLED.
Referenced by tls13_alert_code().
tls1_callback_ctrl()
long tls1_callback_ctrl (SSL * s, int cmd, void(*)(void) fp)
tls1_change_cipher_state()
__owur int tls1_change_cipher_state (SSL * s, int which)
Definition at line 103 of file t1_enc.c.
References EVP_MAX_IV_LENGTH, EVP_MAX_KEY_LENGTH, and key.
tls1_check_chain()
int tls1_check_chain (SSL * s, X509 * x, EVP_PKEY * pk, STACK_OF(X509) * chain, int idx)
Definition at line 1875 of file t1_lib.c.
Referenced by SSL_check_chain(), and tls1_set_cert_validity().
tls1_check_curve()
__owur int tls1_check_curve (SSL * s, const unsigned char * p, size_t len)
Definition at line 284 of file t1_lib.c.
References NAMED_CURVE_TYPE, SSL_SECOP_CURVE_CHECK, TLS1_CK_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS1_CK_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, tls1_get_curvelist(), tls1_suiteb, tls_curve_allowed(), TLSEXT_curve_P_256, and TLSEXT_curve_P_384.
tls1_check_ec_tmp_key()
__owur int tls1_check_ec_tmp_key (SSL * s, unsigned long id)
Definition at line 635 of file t1_lib.c.
References TLS1_CK_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS1_CK_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, tls1_suiteb, TLSEXT_curve_P_256, and TLSEXT_curve_P_384.
tls1_clear()
void tls1_clear (SSL * s)
Definition at line 115 of file t1_lib.c.
References ssl3_clear(), TLS_ANY_VERSION, and TLS_MAX_VERSION.
tls1_ctrl()
long tls1_ctrl (SSL * s, int cmd, long larg, void * parg)
tls1_default_timeout()
__owur long tls1_default_timeout (void)
Definition at line 92 of file t1_lib.c.
tls1_ec_curve_id2nid()
__owur int tls1_ec_curve_id2nid (int curve_id, unsigned int * pflags)
Definition at line 188 of file t1_lib.c.
References tls_curve_info::flags, tls_curve_info::nid, and OSSL_NELEM.
tls1_ec_nid2curve_id()
__owur int tls1_ec_nid2curve_id (int nid)
Definition at line 200 of file t1_lib.c.
References OSSL_NELEM.
Referenced by tls1_set_groups().
tls1_export_keying_material()
__owur int tls1_export_keying_material (SSL * s, unsigned char * out, size_t olen, const char * label, size_t llen, const unsigned char * p, size_t plen, int use_context)
Definition at line 559 of file t1_enc.c.
References NULL, OPENSSL_malloc, SSL3_RANDOM_SIZE, TLS_MD_CLIENT_FINISH_CONST, TLS_MD_CLIENT_FINISH_CONST_SIZE, TLS_MD_EXTENDED_MASTER_SECRET_CONST, TLS_MD_EXTENDED_MASTER_SECRET_CONST_SIZE, TLS_MD_KEY_EXPANSION_CONST, TLS_MD_KEY_EXPANSION_CONST_SIZE, TLS_MD_MASTER_SECRET_CONST, TLS_MD_MASTER_SECRET_CONST_SIZE, TLS_MD_SERVER_FINISH_CONST, and TLS_MD_SERVER_FINISH_CONST_SIZE.
tls1_final_finish_mac()
__owur size_t tls1_final_finish_mac (SSL * s, const char * str, size_t slen, unsigned char * p)
Definition at line 463 of file t1_enc.c.
References EVP_MAX_MD_SIZE, ssl3_digest_cached_records(), and ssl_handshake_hash().
tls1_free()
void tls1_free (SSL * s)
Definition at line 109 of file t1_lib.c.
References OPENSSL_free, and ssl3_free().
tls1_generate_master_secret()
__owur int tls1_generate_master_secret (SSL * s, unsigned char * out, unsigned char * p, size_t len, size_t * secret_size)
Definition at line 483 of file t1_enc.c.
References BIO_dump_fp(), EVP_MAX_MD_SIZE, ssl3_digest_cached_records(), ssl_handshake_hash(), SSL_IS_TLS13, and SSL_SESS_FLAG_EXTMS.
tls1_get_curvelist()
__owur int tls1_get_curvelist (SSL * s, int sess, const unsigned char ** pcurves, size_t * num_curves)
Definition at line 222 of file t1_lib.c.
References SSL_CERT_FLAG_SUITEB_128_LOS, and tls1_suiteb.
Referenced by tls1_check_curve(), and tls_construct_ctos_key_share().
tls1_get_formatlist()
void tls1_get_formatlist (SSL * s, const unsigned char ** pformats, size_t * num_formats)
Definition at line 548 of file t1_lib.c.
Referenced by tls_construct_stoc_ec_pt_formats().
tls1_new()
__owur int tls1_new (SSL * s)
Definition at line 101 of file t1_lib.c.
References ssl3_new().
tls1_process_sigalgs()
__owur int tls1_process_sigalgs (SSL * s)
Definition at line 1581 of file t1_lib.c.
Referenced by tls1_set_server_sigalgs().
tls1_save_sigalgs()
__owur int tls1_save_sigalgs (SSL * s, PACKET * pkt)
Definition at line 1545 of file t1_lib.c.
tls1_set_cert_validity()
void tls1_set_cert_validity (SSL * s)
Definition at line 2124 of file t1_lib.c.
References NULL, SSL_PKEY_DSA_SIGN, SSL_PKEY_ECC, SSL_PKEY_GOST01, SSL_PKEY_GOST12_256, SSL_PKEY_GOST12_512, SSL_PKEY_RSA, and tls1_check_chain().
tls1_set_groups()
__owur int tls1_set_groups (unsigned char ** pext, size_t * pextlen, int * curves, size_t ncurves)
Definition at line 384 of file t1_lib.c.
References NULL, OPENSSL_free, OPENSSL_malloc, s2n, and tls1_ec_nid2curve_id().
Referenced by ssl3_ctx_ctrl().
tls1_set_groups_list()
__owur int tls1_set_groups_list (unsigned char ** pext, size_t * pextlen, const char * str)
Definition at line 452 of file t1_lib.c.
References CONF_parse_list(), and nid_cb_st::nidcnt.
Referenced by SSL_CTX_ctrl().
tls1_set_peer_legacy_sigalg()
__owur int tls1_set_peer_legacy_sigalg (SSL * s, const EVP_PKEY * pkey)
Definition at line 826 of file t1_lib.c.
tls1_set_server_sigalgs()
__owur int tls1_set_server_sigalgs (SSL * s)
Definition at line 1088 of file t1_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_ILLEGAL_PARAMETER, SSL_AD_INTERNAL_ERROR, SSL_F_TLS1_SET_SERVER_SIGALGS, SSL_PKEY_NUM, SSL_R_NO_SHARED_SIGNATURE_ALGORITHMS, ssl_set_default_md(), SSLerr, and tls1_process_sigalgs().
tls1_set_sigalgs()
__owur int tls1_set_sigalgs (CERT * c, const int * salg, size_t salglen, int client)
Definition at line 1786 of file t1_lib.c.
tls1_set_sigalgs_list()
__owur int tls1_set_sigalgs_list (CERT * c, const char * str, int client)
Definition at line 1775 of file t1_lib.c.
Referenced by SSL_CTX_ctrl().
tls1_setup_key_block()
__owur int tls1_setup_key_block (SSL * s)
Definition at line 369 of file t1_enc.c.
tls1_shared_group()
__owur int tls1_shared_group (SSL * s, int nmatch)
Definition at line 321 of file t1_lib.c.
tls1_shared_list()
__owur int tls1_shared_list (SSL * s, const unsigned char * l1, size_t l1len, const unsigned char * l2, size_t l2len, int nmatch)
tls_choose_sigalg()
int tls_choose_sigalg (SSL * s, int * al)
Definition at line 2276 of file t1_lib.c.
tls_close_construct_packet()
__owur int tls_close_construct_packet (SSL * s, WPACKET * pkt, int htype)
Definition at line 61 of file statem_lib.c.
References SSL3_MT_CHANGE_CIPHER_SPEC, WPACKET_close(), and WPACKET_get_length().
tls_curve_allowed()
__owur int tls_curve_allowed (SSL * s, const unsigned char * curve, int op)
Definition at line 268 of file t1_lib.c.
References tls_curve_info::flags, tls_curve_info::nid, OSSL_NELEM, tls_curve_info::secbits, ssl_security(), and TLS_CURVE_CHAR2.
Referenced by check_in_list(), tls1_check_curve(), and tls_construct_ctos_key_share().
tls_decrypt_ticket()
__owur TICKET_RETURN tls_decrypt_ticket (SSL * s, const unsigned char * etick, size_t eticklen, const unsigned char * sess_id, size_t sesslen, SSL_SESSION ** psess)
Definition at line 1224 of file t1_lib.c.
tls_fips_digest_extra()
__owur int tls_fips_digest_extra (const EVP_CIPHER_CTX * cipher_ctx, EVP_MD_CTX * mac_ctx, const unsigned char * data, size_t data_len, size_t orig_len)
Definition at line 493 of file s3_cbc.c.
tls_get_ticket_from_client()
__owur TICKET_RETURN tls_get_ticket_from_client (SSL * s, CLIENTHELLO_MSG * hello, SSL_SESSION ** ret)
Definition at line 1154 of file t1_lib.c.
tls_setup_handshake()
__owur int tls_setup_handshake (SSL * s)
Definition at line 75 of file statem_lib.c.
References SSL3_AL_FATAL, ssl3_init_finished_mac(), ssl3_send_alert(), SSL_AD_HANDSHAKE_FAILURE, SSL_F_TLS_SETUP_HANDSHAKE, SSL_IS_DTLS, SSL_IS_FIRST_HANDSHAKE, SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION, SSL_R_UNSAFE_LEGACY_RENEGOTIATION_DISABLED, and SSLerr.
tls_use_ticket()
__owur int tls_use_ticket (SSL * s)
Definition at line 1058 of file t1_lib.c.
References NULL, SSL_OP_NO_TICKET, SSL_SECOP_TICKET, and ssl_security().
Referenced by tls_construct_ctos_session_ticket(), and tls_construct_stoc_session_ticket().
tlsv1_1_client_method()
__owur const SSL_METHOD* tlsv1_1_client_method (void)
Referenced by TLSv1_1_client_method().
tlsv1_1_method()
__owur const SSL_METHOD* tlsv1_1_method (void)
Referenced by TLSv1_1_method().
tlsv1_1_server_method()
__owur const SSL_METHOD* tlsv1_1_server_method (void)
Referenced by TLSv1_1_server_method().
tlsv1_2_client_method()
__owur const SSL_METHOD* tlsv1_2_client_method (void)
Referenced by TLSv1_2_client_method().
tlsv1_2_method()
__owur const SSL_METHOD* tlsv1_2_method (void)
Referenced by IMPLEMENT_tls_meth_func().
tlsv1_2_server_method()
__owur const SSL_METHOD* tlsv1_2_server_method (void)
Referenced by TLSv1_2_server_method().
tlsv1_3_client_method()
__owur const SSL_METHOD* tlsv1_3_client_method (void)
tlsv1_3_method()
__owur const SSL_METHOD* tlsv1_3_method (void)
tlsv1_3_server_method()
__owur const SSL_METHOD* tlsv1_3_server_method (void)
tlsv1_client_method()
__owur const SSL_METHOD* tlsv1_client_method (void)
Referenced by TLSv1_client_method().
tlsv1_method()
__owur const SSL_METHOD* tlsv1_method (void)
Referenced by TLSv1_method().
tlsv1_server_method()
__owur const SSL_METHOD* tlsv1_server_method (void)
Referenced by TLSv1_server_method().
Variable Documentation
c
__owur const char CERT* c
Definition at line 1992 of file ssl_locl.h.
DTLSv1_2_enc_data
const SSL3_ENC_METHOD DTLSv1_2_enc_data
Definition at line 48 of file d1_lib.c.
DTLSv1_enc_data
const SSL3_ENC_METHOD DTLSv1_enc_data
Definition at line 31 of file d1_lib.c.
rule_str
__owur const char* rule_str
Definition at line 1992 of file ssl_locl.h.
sorted
__owur ** sorted
Definition at line 1992 of file ssl_locl.h.
ssl3_undef_enc_method
SSL3_ENC_METHOD ssl3_undef_enc_method
Definition at line 57 of file ssl_lib.c.
SSLv3_enc_data
const SSL3_ENC_METHOD SSLv3_enc_data
Definition at line 2814 of file s3_lib.c.
TLSv1_1_enc_data
const SSL3_ENC_METHOD TLSv1_1_enc_data
Definition at line 40 of file t1_lib.c.
TLSv1_2_enc_data
const SSL3_ENC_METHOD TLSv1_2_enc_data
Definition at line 57 of file t1_lib.c.
TLSv1_3_enc_data
const SSL3_ENC_METHOD TLSv1_3_enc_data
Definition at line 75 of file t1_lib.c.
TLSv1_enc_data
const SSL3_ENC_METHOD TLSv1_enc_data
Definition at line 23 of file t1_lib.c.