ssl/ssl_txt.c File Reference
ssl_txt.c File Reference
#include <stdio.h>
#include <openssl/buffer.h>
#include "ssl_locl.h"
Functions
int SSL_SESSION_print_fp (FILE *fp, const SSL_SESSION *x)
int SSL_SESSION_print (BIO *bp, const SSL_SESSION *x)
int SSL_SESSION_print_keylog (BIO *bp, const SSL_SESSION *x)
Function Documentation
SSL_SESSION_print()
int SSL_SESSION_print (BIO * bp, const SSL_SESSION * x)
Definition at line 58 of file ssl_txt.c.
References BIO_dump_indent(), BIO_printf(), BIO_puts(), NULL, ssl_cipher_get_evp(), ssl_protocol_to_string(), SSL_SESS_FLAG_EXTMS, and X509_verify_cert_error_string().
SSL_SESSION_print_fp()
int SSL_SESSION_print_fp (FILE * fp, const SSL_SESSION * x)
Definition at line 42 of file ssl_txt.c.
SSL_SESSION_print_keylog()
int SSL_SESSION_print_keylog (BIO * bp, const SSL_SESSION * x)
Definition at line 183 of file ssl_txt.c.
References BIO_printf(), BIO_puts(), and NULL.