ssl/ssl_sess.c File Reference
ssl_sess.c File Reference
#include <stdio.h>
#include <openssl/lhash.h>
#include <openssl/rand.h>
#include <openssl/engine.h>
#include "ssl_locl.h"
#include "statem/statem_locl.h"
Data Structures
struct TIMEOUT_PARAM
Macros
#define MAX_SESS_ID_ATTEMPTS 10
Functions
SSL_SESSION * SSL_get_session (const SSL *ssl)
SSL_SESSION * SSL_get1_session (SSL *ssl)
int SSL_SESSION_set_ex_data (SSL_SESSION *s, int idx, void *arg)
void * SSL_SESSION_get_ex_data (const SSL_SESSION *s, int idx)
SSL_SESSION * SSL_SESSION_new (void)
SSL_SESSION * ssl_session_dup (SSL_SESSION *src, int ticket)
const unsigned char * SSL_SESSION_get_id (const SSL_SESSION *s, unsigned int *len)
const unsigned char * SSL_SESSION_get0_id_context (const SSL_SESSION *s, unsigned int *len)
unsigned int SSL_SESSION_get_compress_id (const SSL_SESSION *s)
int ssl_get_new_session (SSL *s, int session)
int ssl_get_prev_session (SSL *s, CLIENTHELLO_MSG *hello, int *al)
int SSL_CTX_add_session (SSL_CTX *ctx, SSL_SESSION *c)
int SSL_CTX_remove_session (SSL_CTX *ctx, SSL_SESSION *c)
void SSL_SESSION_free (SSL_SESSION *ss)
int SSL_SESSION_up_ref (SSL_SESSION *ss)
int SSL_set_session (SSL *s, SSL_SESSION *session)
int SSL_SESSION_set1_id (SSL_SESSION *s, const unsigned char *sid, unsigned int sid_len)
long SSL_SESSION_set_timeout (SSL_SESSION *s, long t)
long SSL_SESSION_get_timeout (const SSL_SESSION *s)
long SSL_SESSION_get_time (const SSL_SESSION *s)
long SSL_SESSION_set_time (SSL_SESSION *s, long t)
int SSL_SESSION_get_protocol_version (const SSL_SESSION *s)
const SSL_CIPHER * SSL_SESSION_get0_cipher (const SSL_SESSION *s)
const char * SSL_SESSION_get0_hostname (const SSL_SESSION *s)
int SSL_SESSION_has_ticket (const SSL_SESSION *s)
unsigned long SSL_SESSION_get_ticket_lifetime_hint (const SSL_SESSION *s)
void SSL_SESSION_get0_ticket (const SSL_SESSION *s, const unsigned char **tick, size_t *len)
X509 * SSL_SESSION_get0_peer (SSL_SESSION *s)
int SSL_SESSION_set1_id_context (SSL_SESSION *s, const unsigned char *sid_ctx, unsigned int sid_ctx_len)
long SSL_CTX_set_timeout (SSL_CTX *s, long t)
long SSL_CTX_get_timeout (const SSL_CTX *s)
int SSL_set_session_secret_cb (SSL *s, tls_session_secret_cb_fn tls_session_secret_cb, void *arg)
int SSL_set_session_ticket_ext_cb (SSL *s, tls_session_ticket_ext_cb_fn cb, void *arg)
int SSL_set_session_ticket_ext (SSL *s, void *ext_data, int ext_len)
IMPLEMENT_LHASH_DOALL_ARG (SSL_SESSION, TIMEOUT_PARAM)
void SSL_CTX_flush_sessions (SSL_CTX *s, long t)
int ssl_clear_bad_session (SSL *s)
void SSL_CTX_sess_set_new_cb (SSL_CTX *ctx, int(*cb)(struct ssl_st *ssl, SSL_SESSION *sess))
void SSL_CTX_sess_set_remove_cb (SSL_CTX *ctx, void(*cb)(SSL_CTX *ctx, SSL_SESSION *sess))
void SSL_CTX_sess_set_get_cb (SSL_CTX *ctx, SSL_SESSION *(*cb)(struct ssl_st *ssl, const unsigned char *data, int len, int *copy))
void SSL_CTX_set_info_callback (SSL_CTX *ctx, void(*cb)(const SSL *ssl, int type, int val))
void SSL_CTX_set_client_cert_cb (SSL_CTX *ctx, int(*cb)(SSL *ssl, X509 **x509, EVP_PKEY **pkey))
int SSL_CTX_set_client_cert_engine (SSL_CTX *ctx, ENGINE *e)
void SSL_CTX_set_cookie_generate_cb (SSL_CTX *ctx, int(*cb)(SSL *ssl, unsigned char *cookie, unsigned int *cookie_len))
void SSL_CTX_set_cookie_verify_cb (SSL_CTX *ctx, int(*cb)(SSL *ssl, const unsigned char *cookie, unsigned int cookie_len))
Variables
int(*)(SSL *ssl, SSL_SESSION *sess) SSL_CTX_sess_get_new_cb (SSL_CTX *ctx)
void(*)(SSL_CTX *ctx, SSL_SESSION *sess) SSL_CTX_sess_get_remove_cb (SSL_CTX *ctx)
SSL_SESSION *(*)(SSL *ssl, const unsigned char *data, int len, int *copy) SSL_CTX_sess_get_get_cb (SSL_CTX *ctx)
void(*)(const SSL *ssl, int type, int val) SSL_CTX_get_info_callback (SSL_CTX *ctx)
int(*)(SSL *ssl, X509 **x509, EVP_PKEY **pkey) SSL_CTX_get_client_cert_cb (SSL_CTX *ctx)
Macro Definition Documentation
MAX_SESS_ID_ATTEMPTS
#define MAX_SESS_ID_ATTEMPTS 10
Definition at line 279 of file ssl_sess.c.
Function Documentation
IMPLEMENT_LHASH_DOALL_ARG()
IMPLEMENT_LHASH_DOALL_ARG (SSL_SESSION , TIMEOUT_PARAM)
ssl_clear_bad_session()
int ssl_clear_bad_session (SSL * s)
Definition at line 1031 of file ssl_sess.c.
References NULL, SSL_CTX_remove_session(), SSL_in_before(), SSL_in_init(), and SSL_SENT_SHUTDOWN.
Referenced by SSL_clear(), and SSL_set_session().
SSL_CTX_add_session()
int SSL_CTX_add_session (SSL_CTX * ctx, SSL_SESSION * c)
Definition at line 648 of file ssl_sess.c.
Referenced by ssl_update_cache().
SSL_CTX_flush_sessions()
void SSL_CTX_flush_sessions (SSL_CTX * s, long t)
Definition at line 1013 of file ssl_sess.c.
References CRYPTO_THREAD_write_lock(), TIMEOUT_PARAM::ctx, NULL, t, and TIMEOUT_PARAM::time.
Referenced by ssl_update_cache().
SSL_CTX_get_timeout()
long SSL_CTX_get_timeout (const SSL_CTX * s)
Definition at line 934 of file ssl_sess.c.
References NULL.
SSL_CTX_remove_session()
int SSL_CTX_remove_session (SSL_CTX * ctx, SSL_SESSION * c)
Definition at line 725 of file ssl_sess.c.
Referenced by ssl3_send_alert(), and ssl_clear_bad_session().
SSL_CTX_sess_set_get_cb()
void SSL_CTX_sess_set_get_cb (SSL_CTX * ctx, SSL_SESSION *(*)(struct ssl_st *ssl, const unsigned char *data, int len, int *copy) cb)
Definition at line 1111 of file ssl_sess.c.
References cb.
SSL_CTX_sess_set_new_cb()
void SSL_CTX_sess_set_new_cb (SSL_CTX * ctx, int(*)(struct ssl_st *ssl, SSL_SESSION *sess) cb)
Definition at line 1090 of file ssl_sess.c.
References cb.
SSL_CTX_sess_set_remove_cb()
void SSL_CTX_sess_set_remove_cb (SSL_CTX * ctx, void(*)(SSL_CTX *ctx, SSL_SESSION *sess) cb)
Definition at line 1100 of file ssl_sess.c.
References cb.
SSL_CTX_set_client_cert_cb()
void SSL_CTX_set_client_cert_cb (SSL_CTX * ctx, int(*)(SSL *ssl, X509 **x509, EVP_PKEY **pkey) cb)
Definition at line 1137 of file ssl_sess.c.
References cb.
SSL_CTX_set_client_cert_engine()
int SSL_CTX_set_client_cert_engine (SSL_CTX * ctx, ENGINE * e)
Definition at line 1150 of file ssl_sess.c.
References e, ENGINE_finish(), ENGINE_get_ssl_client_cert_function(), ENGINE_init(), ERR_R_ENGINE_LIB, SSL_F_SSL_CTX_SET_CLIENT_CERT_ENGINE, SSL_R_NO_CLIENT_CERT_METHOD, and SSLerr.
SSL_CTX_set_cookie_generate_cb()
void SSL_CTX_set_cookie_generate_cb (SSL_CTX * ctx, int(*)(SSL *ssl, unsigned char *cookie, unsigned int *cookie_len) cb)
Definition at line 1167 of file ssl_sess.c.
SSL_CTX_set_cookie_verify_cb()
void SSL_CTX_set_cookie_verify_cb (SSL_CTX * ctx, int(*)(SSL *ssl, const unsigned char *cookie, unsigned int cookie_len) cb)
Definition at line 1175 of file ssl_sess.c.
SSL_CTX_set_info_callback()
void SSL_CTX_set_info_callback (SSL_CTX * ctx, void(*)(const SSL *ssl, int type, int val) cb)
Definition at line 1126 of file ssl_sess.c.
References cb.
SSL_CTX_set_timeout()
long SSL_CTX_set_timeout (SSL_CTX * s, long t)
Definition at line 924 of file ssl_sess.c.
References NULL, and t.
SSL_get1_session()
SSL_SESSION* SSL_get1_session (SSL * ssl)
Definition at line 63 of file ssl_sess.c.
References CRYPTO_THREAD_read_lock(), CRYPTO_THREAD_unlock(), and SSL_SESSION_up_ref().
ssl_get_new_session()
int ssl_get_new_session (SSL * s, int session)
Definition at line 303 of file ssl_sess.c.
References cb, and NULL.
Referenced by tls_construct_client_hello().
ssl_get_prev_session()
int ssl_get_prev_session (SSL * s, CLIENTHELLO_MSG * hello, int * al)
Definition at line 461 of file ssl_sess.c.
SSL_get_session()
SSL_SESSION* SSL_get_session (const SSL * ssl)
Definition at line 57 of file ssl_sess.c.
Referenced by SSL_copy_session_id().
ssl_session_dup()
SSL_SESSION* ssl_session_dup (SSL_SESSION * src, int ticket)
Definition at line 126 of file ssl_sess.c.
References CRYPTO_dup_ex_data(), CRYPTO_EX_INDEX_SSL_SESSION, CRYPTO_THREAD_lock_new(), ERR_R_MALLOC_FAILURE, NULL, OPENSSL_malloc, OPENSSL_memdup, OPENSSL_strdup, SSL_F_SSL_SESSION_DUP, SSL_SESSION_free(), SSLerr, and X509_up_ref().
SSL_SESSION_free()
void SSL_SESSION_free (SSL_SESSION * ss)
Definition at line 758 of file ssl_sess.c.
References CRYPTO_DOWN_REF, CRYPTO_EX_INDEX_SSL_SESSION, CRYPTO_free_ex_data(), CRYPTO_THREAD_lock_free(), NULL, OPENSSL_cleanse(), OPENSSL_clear_free, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by SSL_clear(), ssl_session_dup(), SSL_set_session(), and ssl_update_cache().
SSL_SESSION_get0_cipher()
const SSL_CIPHER* SSL_SESSION_get0_cipher (const SSL_SESSION * s)
Definition at line 877 of file ssl_sess.c.
SSL_SESSION_get0_hostname()
const char* SSL_SESSION_get0_hostname (const SSL_SESSION * s)
Definition at line 882 of file ssl_sess.c.
SSL_SESSION_get0_id_context()
const unsigned char* SSL_SESSION_get0_id_context (const SSL_SESSION * s, unsigned int * len)
Definition at line 255 of file ssl_sess.c.
References NULL.
SSL_SESSION_get0_peer()
X509* SSL_SESSION_get0_peer (SSL_SESSION * s)
Definition at line 905 of file ssl_sess.c.
SSL_SESSION_get0_ticket()
void SSL_SESSION_get0_ticket (const SSL_SESSION * s, const unsigned char ** tick, size_t * len)
Definition at line 897 of file ssl_sess.c.
References NULL.
SSL_SESSION_get_compress_id()
unsigned int SSL_SESSION_get_compress_id (const SSL_SESSION * s)
Definition at line 263 of file ssl_sess.c.
SSL_SESSION_get_ex_data()
void* SSL_SESSION_get_ex_data (const SSL_SESSION * s, int idx)
Definition at line 85 of file ssl_sess.c.
SSL_SESSION_get_id()
const unsigned char* SSL_SESSION_get_id (const SSL_SESSION * s, unsigned int * len)
Definition at line 249 of file ssl_sess.c.
SSL_SESSION_get_protocol_version()
int SSL_SESSION_get_protocol_version (const SSL_SESSION * s)
Definition at line 872 of file ssl_sess.c.
SSL_SESSION_get_ticket_lifetime_hint()
unsigned long SSL_SESSION_get_ticket_lifetime_hint (const SSL_SESSION * s)
Definition at line 892 of file ssl_sess.c.
SSL_SESSION_get_time()
long SSL_SESSION_get_time (const SSL_SESSION * s)
Definition at line 857 of file ssl_sess.c.
References NULL.
SSL_SESSION_get_timeout()
long SSL_SESSION_get_timeout (const SSL_SESSION * s)
Definition at line 850 of file ssl_sess.c.
References NULL.
SSL_SESSION_has_ticket()
int SSL_SESSION_has_ticket (const SSL_SESSION * s)
Definition at line 887 of file ssl_sess.c.
SSL_SESSION_new()
SSL_SESSION* SSL_SESSION_new (void)
Definition at line 90 of file ssl_sess.c.
References CRYPTO_EX_INDEX_SSL_SESSION, CRYPTO_new_ex_data(), CRYPTO_THREAD_lock_free(), CRYPTO_THREAD_lock_new(), ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_INIT_LOAD_SSL_STRINGS, OPENSSL_init_ssl(), OPENSSL_zalloc, SSL_F_SSL_SESSION_NEW, and SSLerr.
SSL_SESSION_set1_id()
int SSL_SESSION_set1_id (SSL_SESSION * s, const unsigned char * sid, unsigned int sid_len)
Definition at line 829 of file ssl_sess.c.
References SSL_F_SSL_SESSION_SET1_ID, SSL_MAX_SSL_SESSION_ID_LENGTH, SSL_R_SSL_SESSION_ID_TOO_LONG, and SSLerr.
SSL_SESSION_set1_id_context()
int SSL_SESSION_set1_id_context (SSL_SESSION * s, const unsigned char * sid_ctx, unsigned int sid_ctx_len)
Definition at line 910 of file ssl_sess.c.
References SSL_F_SSL_SESSION_SET1_ID_CONTEXT, SSL_MAX_SID_CTX_LENGTH, SSL_R_SSL_SESSION_ID_CONTEXT_TOO_LONG, and SSLerr.
SSL_SESSION_set_ex_data()
int SSL_SESSION_set_ex_data (SSL_SESSION * s, int idx, void * arg)
Definition at line 80 of file ssl_sess.c.
SSL_SESSION_set_time()
long SSL_SESSION_set_time (SSL_SESSION * s, long t)
Definition at line 864 of file ssl_sess.c.
References NULL, and t.
SSL_SESSION_set_timeout()
long SSL_SESSION_set_timeout (SSL_SESSION * s, long t)
Definition at line 842 of file ssl_sess.c.
References NULL, and t.
SSL_SESSION_up_ref()
int SSL_SESSION_up_ref (SSL_SESSION * ss)
Definition at line 799 of file ssl_sess.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by SSL_get1_session(), SSL_set_session(), and ssl_update_cache().
SSL_set_session()
int SSL_set_session (SSL * s, SSL_SESSION * session)
Definition at line 811 of file ssl_sess.c.
References NULL, ssl_clear_bad_session(), SSL_SESSION_free(), SSL_SESSION_up_ref(), and SSL_set_ssl_method().
Referenced by SSL_copy_session_id().
SSL_set_session_secret_cb()
int SSL_set_session_secret_cb (SSL * s, tls_session_secret_cb_fn tls_session_secret_cb, void * arg)
Definition at line 941 of file ssl_sess.c.
SSL_set_session_ticket_ext()
int SSL_set_session_ticket_ext (SSL * s, void * ext_data, int ext_len)
Definition at line 962 of file ssl_sess.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_malloc, SSL_F_SSL_SET_SESSION_TICKET_EXT, SSLerr, and TLS1_VERSION.
SSL_set_session_ticket_ext_cb()
int SSL_set_session_ticket_ext_cb (SSL * s, tls_session_ticket_ext_cb_fn cb, void * arg)
Definition at line 952 of file ssl_sess.c.
Variable Documentation
SSL_CTX_get_client_cert_cb
int(*)(SSL *ssl, X509 **x509, EVP_PKEY **pkey) SSL_CTX_get_client_cert_cb(SSL_CTX *ctx)
Definition at line 1144 of file ssl_sess.c.
SSL_CTX_get_info_callback
void(*)(const SSL *ssl, int type, int val) SSL_CTX_get_info_callback(SSL_CTX *ctx)
Definition at line 1132 of file ssl_sess.c.
SSL_CTX_sess_get_get_cb
SSL_SESSION*(*)(SSL *ssl, const unsigned char *data, int len, int *copy) SSL_CTX_sess_get_get_cb(SSL_CTX *ctx)
Definition at line 1119 of file ssl_sess.c.
SSL_CTX_sess_get_new_cb
int(*)(SSL *ssl, SSL_SESSION *sess) SSL_CTX_sess_get_new_cb(SSL_CTX *ctx)
Definition at line 1096 of file ssl_sess.c.
SSL_CTX_sess_get_remove_cb
void(*)(SSL_CTX *ctx, SSL_SESSION *sess) SSL_CTX_sess_get_remove_cb(SSL_CTX *ctx)
Definition at line 1106 of file ssl_sess.c.