ssl/ssl_rsa.c File Reference
ssl_rsa.c File Reference
#include <stdio.h>
#include "ssl_locl.h"
#include <openssl/bio.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include <openssl/pem.h>
Functions
int SSL_use_certificate (SSL *ssl, X509 *x)
int SSL_use_certificate_file (SSL *ssl, const char *file, int type)
int SSL_use_certificate_ASN1 (SSL *ssl, const unsigned char *d, int len)
int SSL_use_RSAPrivateKey (SSL *ssl, RSA *rsa)
int SSL_use_RSAPrivateKey_file (SSL *ssl, const char *file, int type)
int SSL_use_RSAPrivateKey_ASN1 (SSL *ssl, const unsigned char *d, long len)
int SSL_use_PrivateKey (SSL *ssl, EVP_PKEY *pkey)
int SSL_use_PrivateKey_file (SSL *ssl, const char *file, int type)
int SSL_use_PrivateKey_ASN1 (int type, SSL *ssl, const unsigned char *d, long len)
int SSL_CTX_use_certificate (SSL_CTX *ctx, X509 *x)
int SSL_CTX_use_certificate_file (SSL_CTX *ctx, const char *file, int type)
int SSL_CTX_use_certificate_ASN1 (SSL_CTX *ctx, int len, const unsigned char *d)
int SSL_CTX_use_RSAPrivateKey (SSL_CTX *ctx, RSA *rsa)
int SSL_CTX_use_RSAPrivateKey_file (SSL_CTX *ctx, const char *file, int type)
int SSL_CTX_use_RSAPrivateKey_ASN1 (SSL_CTX *ctx, const unsigned char *d, long len)
int SSL_CTX_use_PrivateKey (SSL_CTX *ctx, EVP_PKEY *pkey)
int SSL_CTX_use_PrivateKey_file (SSL_CTX *ctx, const char *file, int type)
int SSL_CTX_use_PrivateKey_ASN1 (int type, SSL_CTX *ctx, const unsigned char *d, long len)
int SSL_CTX_use_certificate_chain_file (SSL_CTX *ctx, const char *file)
int SSL_use_certificate_chain_file (SSL *ssl, const char *file)
int SSL_CTX_use_serverinfo (SSL_CTX *ctx, const unsigned char *serverinfo, size_t serverinfo_length)
int SSL_CTX_use_serverinfo_file (SSL_CTX *ctx, const char *file)
Function Documentation
SSL_CTX_use_certificate()
int SSL_CTX_use_certificate (SSL_CTX * ctx, X509 * x)
Definition at line 296 of file ssl_rsa.c.
References ERR_R_PASSED_NULL_PARAMETER, NULL, SSL_F_SSL_CTX_USE_CERTIFICATE, ssl_security_cert(), and SSLerr.
SSL_CTX_use_certificate_ASN1()
int SSL_CTX_use_certificate_ASN1 (SSL_CTX * ctx, int len, const unsigned char * d)
Definition at line 413 of file ssl_rsa.c.
SSL_CTX_use_certificate_chain_file()
int SSL_CTX_use_certificate_chain_file (SSL_CTX * ctx, const char * file)
Definition at line 682 of file ssl_rsa.c.
SSL_CTX_use_certificate_file()
int SSL_CTX_use_certificate_file (SSL_CTX * ctx, const char * file, int type)
Definition at line 372 of file ssl_rsa.c.
References in.
Referenced by create_ssl_ctx_pair(), and set_cert_stuff().
SSL_CTX_use_PrivateKey()
int SSL_CTX_use_PrivateKey (SSL_CTX * ctx, EVP_PKEY * pkey)
Definition at line 514 of file ssl_rsa.c.
References ERR_R_PASSED_NULL_PARAMETER, NULL, SSL_F_SSL_CTX_USE_PRIVATEKEY, and SSLerr.
SSL_CTX_use_PrivateKey_ASN1()
int SSL_CTX_use_PrivateKey_ASN1 (int type, SSL_CTX * ctx, const unsigned char * d, long len)
Definition at line 562 of file ssl_rsa.c.
SSL_CTX_use_PrivateKey_file()
int SSL_CTX_use_PrivateKey_file (SSL_CTX * ctx, const char * file, int type)
Definition at line 523 of file ssl_rsa.c.
Referenced by create_ssl_ctx_pair(), and set_cert_stuff().
SSL_CTX_use_RSAPrivateKey()
int SSL_CTX_use_RSAPrivateKey (SSL_CTX * ctx, RSA * rsa)
Definition at line 430 of file ssl_rsa.c.
SSL_CTX_use_RSAPrivateKey_ASN1()
int SSL_CTX_use_RSAPrivateKey_ASN1 (SSL_CTX * ctx, const unsigned char * d, long len)
Definition at line 495 of file ssl_rsa.c.
SSL_CTX_use_RSAPrivateKey_file()
int SSL_CTX_use_RSAPrivateKey_file (SSL_CTX * ctx, const char * file, int type)
Definition at line 456 of file ssl_rsa.c.
SSL_CTX_use_serverinfo()
int SSL_CTX_use_serverinfo (SSL_CTX * ctx, const unsigned char * serverinfo, size_t serverinfo_length)
Definition at line 841 of file ssl_rsa.c.
References ERR_R_PASSED_NULL_PARAMETER, NULL, SSL_F_SSL_CTX_USE_SERVERINFO, and SSLerr.
SSL_CTX_use_serverinfo_file()
int SSL_CTX_use_serverinfo_file (SSL_CTX * ctx, const char * file)
Definition at line 879 of file ssl_rsa.c.
References NULL.
SSL_use_certificate()
int SSL_use_certificate (SSL * ssl, X509 * x)
Definition at line 20 of file ssl_rsa.c.
References ERR_R_PASSED_NULL_PARAMETER, NULL, SSL_F_SSL_USE_CERTIFICATE, ssl_security_cert(), and SSLerr.
SSL_use_certificate_ASN1()
int SSL_use_certificate_ASN1 (SSL * ssl, const unsigned char * d, int len)
Definition at line 77 of file ssl_rsa.c.
SSL_use_certificate_chain_file()
int SSL_use_certificate_chain_file (SSL * ssl, const char * file)
Definition at line 687 of file ssl_rsa.c.
SSL_use_certificate_file()
int SSL_use_certificate_file (SSL * ssl, const char * file, int type)
Definition at line 36 of file ssl_rsa.c.
References in.
SSL_use_PrivateKey()
int SSL_use_PrivateKey (SSL * ssl, EVP_PKEY * pkey)
Definition at line 226 of file ssl_rsa.c.
SSL_use_PrivateKey_ASN1()
int SSL_use_PrivateKey_ASN1 (int type, SSL * ssl, const unsigned char * d, long len)
Definition at line 278 of file ssl_rsa.c.
SSL_use_PrivateKey_file()
int SSL_use_PrivateKey_file (SSL * ssl, const char * file, int type)
Definition at line 238 of file ssl_rsa.c.
SSL_use_RSAPrivateKey()
int SSL_use_RSAPrivateKey (SSL * ssl, RSA * rsa)
Definition at line 94 of file ssl_rsa.c.
SSL_use_RSAPrivateKey_ASN1()
int SSL_use_RSAPrivateKey_ASN1 (SSL * ssl, const unsigned char * d, long len)
Definition at line 208 of file ssl_rsa.c.
SSL_use_RSAPrivateKey_file()
int SSL_use_RSAPrivateKey_file (SSL * ssl, const char * file, int type)
Definition at line 168 of file ssl_rsa.c.