ssl/ssl_lib.c File Reference
ssl_lib.c File Reference
#include <assert.h>
#include <stdio.h>
#include "ssl_locl.h"
#include <openssl/objects.h>
#include <openssl/lhash.h>
#include <openssl/x509v3.h>
#include <openssl/rand.h>
#include <openssl/ocsp.h>
#include <openssl/dh.h>
#include <openssl/engine.h>
#include <openssl/async.h>
#include <openssl/ct.h>
Data Structures
struct ssl_async_args
Functions
int SSL_clear (SSL *s)
int SSL_CTX_set_ssl_version (SSL_CTX *ctx, const SSL_METHOD *meth)
SSL * SSL_new (SSL_CTX *ctx)
int SSL_is_dtls (const SSL *s)
int SSL_up_ref (SSL *s)
int SSL_CTX_set_session_id_context (SSL_CTX *ctx, const unsigned char *sid_ctx, unsigned int sid_ctx_len)
int SSL_set_session_id_context (SSL *ssl, const unsigned char *sid_ctx, unsigned int sid_ctx_len)
int SSL_CTX_set_generate_session_id (SSL_CTX *ctx, GEN_SESSION_CB cb)
int SSL_set_generate_session_id (SSL *ssl, GEN_SESSION_CB cb)
int SSL_has_matching_session_id (const SSL *ssl, const unsigned char *id, unsigned int id_len)
int SSL_CTX_set_purpose (SSL_CTX *s, int purpose)
int SSL_set_purpose (SSL *s, int purpose)
int SSL_CTX_set_trust (SSL_CTX *s, int trust)
int SSL_set_trust (SSL *s, int trust)
int SSL_set1_host (SSL *s, const char *hostname)
int SSL_add1_host (SSL *s, const char *hostname)
void SSL_set_hostflags (SSL *s, unsigned int flags)
const char * SSL_get0_peername (SSL *s)
int SSL_CTX_dane_enable (SSL_CTX *ctx)
unsigned long SSL_CTX_dane_set_flags (SSL_CTX *ctx, unsigned long flags)
unsigned long SSL_CTX_dane_clear_flags (SSL_CTX *ctx, unsigned long flags)
int SSL_dane_enable (SSL *s, const char *basedomain)
unsigned long SSL_dane_set_flags (SSL *ssl, unsigned long flags)
unsigned long SSL_dane_clear_flags (SSL *ssl, unsigned long flags)
int SSL_get0_dane_authority (SSL *s, X509 **mcert, EVP_PKEY **mspki)
int SSL_get0_dane_tlsa (SSL *s, uint8_t *usage, uint8_t *selector, uint8_t *mtype, unsigned const char **data, size_t *dlen)
SSL_DANE * SSL_get0_dane (SSL *s)
int SSL_dane_tlsa_add (SSL *s, uint8_t usage, uint8_t selector, uint8_t mtype, unsigned char *data, size_t dlen)
int SSL_CTX_dane_mtype_set (SSL_CTX *ctx, const EVP_MD *md, uint8_t mtype, uint8_t ord)
int SSL_CTX_set1_param (SSL_CTX *ctx, X509_VERIFY_PARAM *vpm)
int SSL_set1_param (SSL *ssl, X509_VERIFY_PARAM *vpm)
X509_VERIFY_PARAM * SSL_CTX_get0_param (SSL_CTX *ctx)
X509_VERIFY_PARAM * SSL_get0_param (SSL *ssl)
void SSL_certs_clear (SSL *s)
void SSL_free (SSL *s)
void SSL_set0_rbio (SSL *s, BIO *rbio)
void SSL_set0_wbio (SSL *s, BIO *wbio)
void SSL_set_bio (SSL *s, BIO *rbio, BIO *wbio)
BIO * SSL_get_rbio (const SSL *s)
BIO * SSL_get_wbio (const SSL *s)
int SSL_get_fd (const SSL *s)
int SSL_get_rfd (const SSL *s)
int SSL_get_wfd (const SSL *s)
int SSL_set_fd (SSL *s, int fd)
int SSL_set_wfd (SSL *s, int fd)
int SSL_set_rfd (SSL *s, int fd)
size_t SSL_get_finished (const SSL *s, void *buf, size_t count)
size_t SSL_get_peer_finished (const SSL *s, void *buf, size_t count)
int SSL_get_verify_mode (const SSL *s)
int SSL_get_verify_depth (const SSL *s)
int SSL_CTX_get_verify_mode (const SSL_CTX *ctx)
int SSL_CTX_get_verify_depth (const SSL_CTX *ctx)
void SSL_set_verify (SSL *s, int mode, int(*callback)(int ok, X509_STORE_CTX *ctx))
void SSL_set_verify_depth (SSL *s, int depth)
void SSL_set_read_ahead (SSL *s, int yes)
int SSL_get_read_ahead (const SSL *s)
int SSL_pending (const SSL *s)
int SSL_has_pending (const SSL *s)
X509 * SSL_get_peer_certificate (const SSL *s)
STACK_OF (X509)
int SSL_copy_session_id (SSL *t, const SSL *f)
int SSL_CTX_check_private_key (const SSL_CTX *ctx)
int SSL_check_private_key (const SSL *ssl)
int SSL_waiting_for_async (SSL *s)
int SSL_get_all_async_fds (SSL *s, OSSL_ASYNC_FD *fds, size_t *numfds)
int SSL_get_changed_async_fds (SSL *s, OSSL_ASYNC_FD *addfd, size_t *numaddfds, OSSL_ASYNC_FD *delfd, size_t *numdelfds)
int SSL_accept (SSL *s)
int SSL_connect (SSL *s)
long SSL_get_default_timeout (const SSL *s)
int SSL_read (SSL *s, void *buf, int num)
int SSL_read_ex (SSL *s, void *buf, size_t num, size_t *readbytes)
int SSL_peek (SSL *s, void *buf, int num)
int SSL_peek_ex (SSL *s, void *buf, size_t num, size_t *readbytes)
int SSL_write (SSL *s, const void *buf, int num)
int SSL_write_ex (SSL *s, const void *buf, size_t num, size_t *written)
int SSL_shutdown (SSL *s)
int SSL_key_update (SSL *s, int updatetype)
int SSL_get_key_update_type (SSL *s)
int SSL_renegotiate (SSL *s)
int SSL_renegotiate_abbreviated (SSL *s)
int SSL_renegotiate_pending (SSL *s)
long SSL_ctrl (SSL *s, int cmd, long larg, void *parg)
long SSL_callback_ctrl (SSL *s, int cmd, void(*fp)(void))
LHASH_OF (SSL_SESSION)
long SSL_CTX_ctrl (SSL_CTX *ctx, int cmd, long larg, void *parg)
long SSL_CTX_callback_ctrl (SSL_CTX *ctx, int cmd, void(*fp)(void))
int ssl_cipher_id_cmp (const SSL_CIPHER *a, const SSL_CIPHER *b)
int ssl_cipher_ptr_id_cmp (const SSL_CIPHER *const *ap, const SSL_CIPHER *const *bp)
STACK_OF (SSL_CIPHER)
const char * SSL_get_cipher_list (const SSL *s, int n)
int SSL_CTX_set_cipher_list (SSL_CTX *ctx, const char *str)
int SSL_set_cipher_list (SSL *s, const char *str)
char * SSL_get_shared_ciphers (const SSL *s, char *buf, int len)
const char * SSL_get_servername (const SSL *s, const int type)
int SSL_get_servername_type (const SSL *s)
int SSL_select_next_proto (unsigned char **out, unsigned char *outlen, const unsigned char *server, unsigned int server_len, const unsigned char *client, unsigned int client_len)
void SSL_get0_next_proto_negotiated (const SSL *s, const unsigned char **data, unsigned *len)
void SSL_CTX_set_npn_advertised_cb (SSL_CTX *ctx, SSL_CTX_npn_advertised_cb_func cb, void *arg)
void SSL_CTX_set_npn_select_cb (SSL_CTX *ctx, SSL_CTX_npn_select_cb_func cb, void *arg)
int SSL_CTX_set_alpn_protos (SSL_CTX *ctx, const unsigned char *protos, unsigned int protos_len)
int SSL_set_alpn_protos (SSL *ssl, const unsigned char *protos, unsigned int protos_len)
void SSL_CTX_set_alpn_select_cb (SSL_CTX *ctx, SSL_CTX_alpn_select_cb_func cb, void *arg)
void SSL_get0_alpn_selected (const SSL *ssl, const unsigned char **data, unsigned int *len)
int SSL_export_keying_material (SSL *s, unsigned char *out, size_t olen, const char *label, size_t llen, const unsigned char *p, size_t plen, int use_context)
SSL_CTX * SSL_CTX_new (const SSL_METHOD *meth)
int SSL_CTX_up_ref (SSL_CTX *ctx)
void SSL_CTX_free (SSL_CTX *a)
void SSL_CTX_set_default_passwd_cb (SSL_CTX *ctx, pem_password_cb *cb)
void SSL_CTX_set_default_passwd_cb_userdata (SSL_CTX *ctx, void *u)
pem_password_cb * SSL_CTX_get_default_passwd_cb (SSL_CTX *ctx)
void * SSL_CTX_get_default_passwd_cb_userdata (SSL_CTX *ctx)
void SSL_set_default_passwd_cb (SSL *s, pem_password_cb *cb)
void SSL_set_default_passwd_cb_userdata (SSL *s, void *u)
pem_password_cb * SSL_get_default_passwd_cb (SSL *s)
void * SSL_get_default_passwd_cb_userdata (SSL *s)
void SSL_CTX_set_cert_verify_callback (SSL_CTX *ctx, int(*cb)(X509_STORE_CTX *, void *), void *arg)
void SSL_CTX_set_verify (SSL_CTX *ctx, int mode, int(*cb)(int, X509_STORE_CTX *))
void SSL_CTX_set_verify_depth (SSL_CTX *ctx, int depth)
void SSL_CTX_set_cert_cb (SSL_CTX *c, int(*cb)(SSL *ssl, void *arg), void *arg)
void SSL_set_cert_cb (SSL *s, int(*cb)(SSL *ssl, void *arg), void *arg)
void ssl_set_masks (SSL *s)
int ssl_check_srvr_ecc_cert_and_alg (X509 *x, SSL *s)
int ssl_get_server_cert_serverinfo (SSL *s, const unsigned char **serverinfo, size_t *serverinfo_length)
void ssl_update_cache (SSL *s, int mode)
const SSL_METHOD * SSL_CTX_get_ssl_method (SSL_CTX *ctx)
const SSL_METHOD * SSL_get_ssl_method (SSL *s)
int SSL_set_ssl_method (SSL *s, const SSL_METHOD *meth)
int SSL_get_error (const SSL *s, int i)
int SSL_do_handshake (SSL *s)
void SSL_set_accept_state (SSL *s)
void SSL_set_connect_state (SSL *s)
int ssl_undefined_function (SSL *s)
int ssl_undefined_void_function (void)
int ssl_undefined_const_function (const SSL *s)
const SSL_METHOD * ssl_bad_method (int ver)
const char * ssl_protocol_to_string (int version)
const char * SSL_get_version (const SSL *s)
SSL * SSL_dup (SSL *s)
void ssl_clear_cipher_ctx (SSL *s)
X509 * SSL_get_certificate (const SSL *s)
EVP_PKEY * SSL_get_privatekey (const SSL *s)
X509 * SSL_CTX_get0_certificate (const SSL_CTX *ctx)
EVP_PKEY * SSL_CTX_get0_privatekey (const SSL_CTX *ctx)
const SSL_CIPHER * SSL_get_current_cipher (const SSL *s)
const COMP_METHOD * SSL_get_current_compression (SSL *s)
const COMP_METHOD * SSL_get_current_expansion (SSL *s)
int ssl_init_wbio_buffer (SSL *s)
void ssl_free_wbio_buffer (SSL *s)
void SSL_CTX_set_quiet_shutdown (SSL_CTX *ctx, int mode)
int SSL_CTX_get_quiet_shutdown (const SSL_CTX *ctx)
void SSL_set_quiet_shutdown (SSL *s, int mode)
int SSL_get_quiet_shutdown (const SSL *s)
void SSL_set_shutdown (SSL *s, int mode)
int SSL_get_shutdown (const SSL *s)
int SSL_version (const SSL *s)
int SSL_client_version (const SSL *s)
SSL_CTX * SSL_get_SSL_CTX (const SSL *ssl)
SSL_CTX * SSL_set_SSL_CTX (SSL *ssl, SSL_CTX *ctx)
int SSL_CTX_set_default_verify_paths (SSL_CTX *ctx)
int SSL_CTX_set_default_verify_dir (SSL_CTX *ctx)
int SSL_CTX_set_default_verify_file (SSL_CTX *ctx)
int SSL_CTX_load_verify_locations (SSL_CTX *ctx, const char *CAfile, const char *CApath)
void SSL_set_info_callback (SSL *ssl, void(*cb)(const SSL *ssl, int type, int val))
void SSL_set_verify_result (SSL *ssl, long arg)
long SSL_get_verify_result (const SSL *ssl)
size_t SSL_get_client_random (const SSL *ssl, unsigned char *out, size_t outlen)
size_t SSL_get_server_random (const SSL *ssl, unsigned char *out, size_t outlen)
size_t SSL_SESSION_get_master_key (const SSL_SESSION *session, unsigned char *out, size_t outlen)
int SSL_set_ex_data (SSL *s, int idx, void *arg)
void * SSL_get_ex_data (const SSL *s, int idx)
int SSL_CTX_set_ex_data (SSL_CTX *s, int idx, void *arg)
void * SSL_CTX_get_ex_data (const SSL_CTX *s, int idx)
int ssl_ok (SSL *s)
X509_STORE * SSL_CTX_get_cert_store (const SSL_CTX *ctx)
void SSL_CTX_set_cert_store (SSL_CTX *ctx, X509_STORE *store)
void SSL_CTX_set1_cert_store (SSL_CTX *ctx, X509_STORE *store)
int SSL_want (const SSL *s)
void SSL_CTX_set_tmp_dh_callback (SSL_CTX *ctx, DH *(*dh)(SSL *ssl, int is_export, int keylength))
Set the callback for generating temporary DH keys.
void SSL_set_tmp_dh_callback (SSL *ssl, DH *(*dh)(SSL *ssl, int is_export, int keylength))
int SSL_CTX_use_psk_identity_hint (SSL_CTX *ctx, const char *identity_hint)
int SSL_use_psk_identity_hint (SSL *s, const char *identity_hint)
const char * SSL_get_psk_identity_hint (const SSL *s)
const char * SSL_get_psk_identity (const SSL *s)
void SSL_set_psk_client_callback (SSL *s, SSL_psk_client_cb_func cb)
void SSL_CTX_set_psk_client_callback (SSL_CTX *ctx, SSL_psk_client_cb_func cb)
void SSL_set_psk_server_callback (SSL *s, SSL_psk_server_cb_func cb)
void SSL_CTX_set_psk_server_callback (SSL_CTX *ctx, SSL_psk_server_cb_func cb)
void SSL_CTX_set_msg_callback (SSL_CTX *ctx, void(*cb)(int write_p, int version, int content_type, const void *buf, size_t len, SSL *ssl, void *arg))
void SSL_set_msg_callback (SSL *ssl, void(*cb)(int write_p, int version, int content_type, const void *buf, size_t len, SSL *ssl, void *arg))
void SSL_CTX_set_not_resumable_session_callback (SSL_CTX *ctx, int(*cb)(SSL *ssl, int is_forward_secure))
void SSL_set_not_resumable_session_callback (SSL *ssl, int(*cb)(SSL *ssl, int is_forward_secure))
EVP_MD_CTX * ssl_replace_hash (EVP_MD_CTX **hash, const EVP_MD *md)
void ssl_clear_hash_ctx (EVP_MD_CTX **hash)
int ssl_handshake_hash (SSL *s, unsigned char *out, size_t outlen, size_t *hashlen)
int SSL_session_reused (SSL *s)
int SSL_is_server (SSL *s)
void SSL_set_debug (SSL *s, int debug)
void SSL_set_security_level (SSL *s, int level)
int SSL_get_security_level (const SSL *s)
void SSL_set_security_callback (SSL *s, int(*cb)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex))
void SSL_set0_security_ex_data (SSL *s, void *ex)
void * SSL_get0_security_ex_data (const SSL *s)
void SSL_CTX_set_security_level (SSL_CTX *ctx, int level)
int SSL_CTX_get_security_level (const SSL_CTX *ctx)
void SSL_CTX_set_security_callback (SSL_CTX *ctx, int(*cb)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex))
void SSL_CTX_set0_security_ex_data (SSL_CTX *ctx, void *ex)
void * SSL_CTX_get0_security_ex_data (const SSL_CTX *ctx)
unsigned long SSL_CTX_get_options (const SSL_CTX *ctx)
unsigned long SSL_get_options (const SSL *s)
unsigned long SSL_CTX_set_options (SSL_CTX *ctx, unsigned long op)
unsigned long SSL_set_options (SSL *s, unsigned long op)
unsigned long SSL_CTX_clear_options (SSL_CTX *ctx, unsigned long op)
unsigned long SSL_clear_options (SSL *s, unsigned long op)
IMPLEMENT_OBJ_BSEARCH_GLOBAL_CMP_FN (SSL_CIPHER, SSL_CIPHER, ssl_cipher_id)
const STACK_OF (SCT)
int SSL_set_ct_validation_callback (SSL *s, ssl_ct_validation_cb callback, void *arg)
int SSL_CTX_set_ct_validation_callback (SSL_CTX *ctx, ssl_ct_validation_cb callback, void *arg)
int SSL_ct_is_enabled (const SSL *s)
int SSL_CTX_ct_is_enabled (const SSL_CTX *ctx)
int ssl_validate_ct (SSL *s)
int SSL_CTX_enable_ct (SSL_CTX *ctx, int validation_mode)
int SSL_enable_ct (SSL *s, int validation_mode)
int SSL_CTX_set_default_ctlog_list_file (SSL_CTX *ctx)
int SSL_CTX_set_ctlog_list_file (SSL_CTX *ctx, const char *path)
void SSL_CTX_set0_ctlog_store (SSL_CTX *ctx, CTLOG_STORE *logs)
const CTLOG_STORE * SSL_CTX_get0_ctlog_store (const SSL_CTX *ctx)
void SSL_CTX_set_keylog_callback (SSL_CTX *ctx, SSL_CTX_keylog_cb_func cb)
SSL_CTX_keylog_cb_func SSL_CTX_get_keylog_callback (const SSL_CTX *ctx)
int ssl_log_rsa_client_key_exchange (SSL *ssl, const uint8_t *encrypted_premaster, size_t encrypted_premaster_len, const uint8_t *premaster, size_t premaster_len)
int ssl_log_secret (SSL *ssl, const char *label, const uint8_t *secret, size_t secret_len)
Variables
const char SSL_version_str [] = OPENSSL_VERSION_TEXT
SSL3_ENC_METHOD ssl3_undef_enc_method
int(*)(int, X509_STORE_CTX *) SSL_get_verify_callback (const SSL *s)
int(*)(int, X509_STORE_CTX *) SSL_CTX_get_verify_callback (const SSL_CTX *ctx)
void(*)(const SSL *, int, int) SSL_get_info_callback (const SSL *ssl)
int(*)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex) SSL_get_security_callback (const SSL *s)
int(*)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex) SSL_CTX_get_security_callback (const SSL_CTX *ctx)
Function Documentation
IMPLEMENT_OBJ_BSEARCH_GLOBAL_CMP_FN()
IMPLEMENT_OBJ_BSEARCH_GLOBAL_CMP_FN (SSL_CIPHER , SSL_CIPHER , ssl_cipher_id)
Referenced by SSL_clear_options().
LHASH_OF()
LHASH_OF (SSL_SESSION)
Definition at line 1890 of file ssl_lib.c.
SSL_accept()
int SSL_accept (SSL * s)
Definition at line 1455 of file ssl_lib.c.
References NULL, SSL_do_handshake(), and SSL_set_accept_state().
SSL_add1_host()
int SSL_add1_host (SSL * s, const char * hostname)
Definition at line 788 of file ssl_lib.c.
References X509_VERIFY_PARAM_add1_host().
ssl_bad_method()
const SSL_METHOD* ssl_bad_method (int ver)
Definition at line 3104 of file ssl_lib.c.
References ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, NULL, SSL_F_SSL_BAD_METHOD, and SSLerr.
SSL_callback_ctrl()
long SSL_callback_ctrl (SSL * s, int cmd, void(*)(void) fp)
Definition at line 1875 of file ssl_lib.c.
References ssl_async_args::buf, len, and SSL_CTRL_SET_MSG_CALLBACK.
Referenced by SSL_set_not_resumable_session_callback(), and SSL_set_tmp_dh_callback().
SSL_certs_clear()
void SSL_certs_clear (SSL * s)
Definition at line 957 of file ssl_lib.c.
References ssl_cert_clear_certs().
SSL_check_private_key()
int SSL_check_private_key (const SSL * ssl)
Definition at line 1409 of file ssl_lib.c.
References ERR_R_PASSED_NULL_PARAMETER, NULL, SSL_F_SSL_CHECK_PRIVATE_KEY, SSL_R_NO_CERTIFICATE_ASSIGNED, SSL_R_NO_PRIVATE_KEY_ASSIGNED, SSLerr, and X509_check_private_key().
ssl_check_srvr_ecc_cert_and_alg()
int ssl_check_srvr_ecc_cert_and_alg (X509 * x, SSL * s)
Definition at line 2852 of file ssl_lib.c.
References SSL_aECDSA, SSL_F_SSL_CHECK_SRVR_ECC_CERT_AND_ALG, SSL_R_ECC_CERT_NOT_FOR_SIGNING, SSLerr, X509_get_key_usage(), and X509v3_KU_DIGITAL_SIGNATURE.
ssl_cipher_id_cmp()
int ssl_cipher_id_cmp (const SSL_CIPHER * a, const SSL_CIPHER * b)
Definition at line 2024 of file ssl_lib.c.
ssl_cipher_ptr_id_cmp()
int ssl_cipher_ptr_id_cmp (const SSL_CIPHER *const * ap, const SSL_CIPHER *const * bp)
Definition at line 2033 of file ssl_lib.c.
SSL_clear()
int SSL_clear (SSL * s)
Definition at line 442 of file ssl_lib.c.
References BUF_MEM_free(), ERR_R_INTERNAL_ERROR, NULL, ossl_statem_clear(), ssl_clear_bad_session(), SSL_F_SSL_CLEAR, SSL_NOTHING, SSL_R_NO_METHOD_SPECIFIED, SSL_SESSION_free(), and SSLerr.
Referenced by SSL_new().
ssl_clear_cipher_ctx()
void ssl_clear_cipher_ctx (SSL * s)
Definition at line 3275 of file ssl_lib.c.
References COMP_CTX_free(), EVP_CIPHER_CTX_free(), and NULL.
ssl_clear_hash_ctx()
void ssl_clear_hash_ctx (EVP_MD_CTX ** hash)
Definition at line 3759 of file ssl_lib.c.
References EVP_MD_CTX_free(), and NULL.
SSL_clear_options()
unsigned long SSL_clear_options (SSL * s, unsigned long op)
Definition at line 3915 of file ssl_lib.c.
References IMPLEMENT_OBJ_BSEARCH_GLOBAL_CMP_FN(), and STACK_OF().
SSL_client_version()
int SSL_client_version (const SSL * s)
Definition at line 3418 of file ssl_lib.c.
SSL_connect()
int SSL_connect (SSL * s)
Definition at line 1465 of file ssl_lib.c.
References NULL, SSL_do_handshake(), and SSL_set_connect_state().
SSL_copy_session_id()
int SSL_copy_session_id (SSL * t, const SSL * f)
Definition at line 1365 of file ssl_lib.c.
References CRYPTO_UP_REF, ssl_cert_free(), SSL_get_session(), SSL_set_session(), and SSL_set_session_id_context().
Referenced by BIO_ssl_copy_session_id().
SSL_ct_is_enabled()
int SSL_ct_is_enabled (const SSL * s)
Definition at line 4155 of file ssl_lib.c.
References NULL.
SSL_ctrl()
long SSL_ctrl (SSL * s, int cmd, long larg, void * parg)
Definition at line 1791 of file ssl_lib.c.
References NULL, ossl_statem_get_in_handshake(), RECORD_LAYER_get_read_ahead, RECORD_LAYER_set_read_ahead, SSL3_RT_MAX_PLAIN_LENGTH, SSL_CTRL_CERT_FLAGS, SSL_CTRL_CLEAR_CERT_FLAGS, SSL_CTRL_CLEAR_MODE, SSL_CTRL_GET_EXTMS_SUPPORT, SSL_CTRL_GET_MAX_CERT_LIST, SSL_CTRL_GET_RAW_CIPHERLIST, SSL_CTRL_GET_READ_AHEAD, SSL_CTRL_GET_RI_SUPPORT, SSL_CTRL_MODE, SSL_CTRL_SET_MAX_CERT_LIST, SSL_CTRL_SET_MAX_PIPELINES, SSL_CTRL_SET_MAX_PROTO_VERSION, SSL_CTRL_SET_MAX_SEND_FRAGMENT, SSL_CTRL_SET_MIN_PROTO_VERSION, SSL_CTRL_SET_MSG_CALLBACK_ARG, SSL_CTRL_SET_READ_AHEAD, SSL_CTRL_SET_SPLIT_SEND_FRAGMENT, SSL_in_init(), SSL_MAX_PIPELINES, SSL_SESS_FLAG_EXTMS, ssl_set_version_bound(), and TLS_CIPHER_LEN.
SSL_CTX_callback_ctrl()
long SSL_CTX_callback_ctrl (SSL_CTX * ctx, int cmd, void(*)(void) fp)
Definition at line 2009 of file ssl_lib.c.
References ssl_async_args::buf, len, and SSL_CTRL_SET_MSG_CALLBACK.
Referenced by SSL_CTX_set_not_resumable_session_callback(), and SSL_CTX_set_tmp_dh_callback().
SSL_CTX_check_private_key()
int SSL_CTX_check_private_key (const SSL_CTX * ctx)
Definition at line 1394 of file ssl_lib.c.
References NULL, SSL_F_SSL_CTX_CHECK_PRIVATE_KEY, SSL_R_NO_CERTIFICATE_ASSIGNED, SSL_R_NO_PRIVATE_KEY_ASSIGNED, SSLerr, and X509_check_private_key().
Referenced by create_ssl_ctx_pair(), and set_cert_stuff().
SSL_CTX_clear_options()
unsigned long SSL_CTX_clear_options (SSL_CTX * ctx, unsigned long op)
Definition at line 3910 of file ssl_lib.c.
SSL_CTX_ct_is_enabled()
int SSL_CTX_ct_is_enabled (const SSL_CTX * ctx)
Definition at line 4160 of file ssl_lib.c.
References NULL.
Referenced by SSL_CTX_add_client_custom_ext().
SSL_CTX_ctrl()
long SSL_CTX_ctrl (SSL_CTX * ctx, int cmd, long larg, void * parg)
Definition at line 1895 of file ssl_lib.c.
References NULL, SSL3_RT_MAX_PLAIN_LENGTH, SSL_CTRL_CERT_FLAGS, SSL_CTRL_CLEAR_CERT_FLAGS, SSL_CTRL_CLEAR_MODE, SSL_CTRL_GET_MAX_CERT_LIST, SSL_CTRL_GET_READ_AHEAD, SSL_CTRL_GET_SESS_CACHE_MODE, SSL_CTRL_GET_SESS_CACHE_SIZE, SSL_CTRL_MODE, SSL_CTRL_SESS_ACCEPT, SSL_CTRL_SESS_ACCEPT_GOOD, SSL_CTRL_SESS_ACCEPT_RENEGOTIATE, SSL_CTRL_SESS_CACHE_FULL, SSL_CTRL_SESS_CB_HIT, SSL_CTRL_SESS_CONNECT, SSL_CTRL_SESS_CONNECT_GOOD, SSL_CTRL_SESS_CONNECT_RENEGOTIATE, SSL_CTRL_SESS_HIT, SSL_CTRL_SESS_MISSES, SSL_CTRL_SESS_NUMBER, SSL_CTRL_SESS_TIMEOUTS, SSL_CTRL_SET_CLIENT_SIGALGS_LIST, SSL_CTRL_SET_GROUPS_LIST, SSL_CTRL_SET_MAX_CERT_LIST, SSL_CTRL_SET_MAX_PIPELINES, SSL_CTRL_SET_MAX_PROTO_VERSION, SSL_CTRL_SET_MAX_SEND_FRAGMENT, SSL_CTRL_SET_MIN_PROTO_VERSION, SSL_CTRL_SET_MSG_CALLBACK_ARG, SSL_CTRL_SET_READ_AHEAD, SSL_CTRL_SET_SESS_CACHE_MODE, SSL_CTRL_SET_SESS_CACHE_SIZE, SSL_CTRL_SET_SIGALGS_LIST, SSL_CTRL_SET_SPLIT_SEND_FRAGMENT, SSL_MAX_PIPELINES, ssl_set_version_bound(), tls1_set_groups_list(), and tls1_set_sigalgs_list().
SSL_CTX_dane_clear_flags()
unsigned long SSL_CTX_dane_clear_flags (SSL_CTX * ctx, unsigned long flags)
Definition at line 816 of file ssl_lib.c.
SSL_CTX_dane_enable()
int SSL_CTX_dane_enable (SSL_CTX * ctx)
Definition at line 803 of file ssl_lib.c.
SSL_CTX_dane_mtype_set()
int SSL_CTX_dane_mtype_set (SSL_CTX * ctx, const EVP_MD * md, uint8_t mtype, uint8_t ord)
Definition at line 931 of file ssl_lib.c.
SSL_CTX_dane_set_flags()
unsigned long SSL_CTX_dane_set_flags (SSL_CTX * ctx, unsigned long flags)
Definition at line 808 of file ssl_lib.c.
References flags.
SSL_CTX_enable_ct()
int SSL_CTX_enable_ct (SSL_CTX * ctx, int validation_mode)
Definition at line 4261 of file ssl_lib.c.
References SSL_CT_VALIDATION_PERMISSIVE, SSL_CTX_set_ct_validation_callback(), SSL_F_SSL_CTX_ENABLE_CT, SSL_R_INVALID_CT_VALIDATION_TYPE, and SSLerr.
SSL_CTX_free()
void SSL_CTX_free (SSL_CTX * a)
Definition at line 2621 of file ssl_lib.c.
References CRYPTO_DOWN_REF, NULL, REF_ASSERT_ISNT, REF_PRINT_COUNT, and X509_VERIFY_PARAM_free().
Referenced by create_ssl_ctx_pair(), and SSL_set_SSL_CTX().
SSL_CTX_get0_certificate()
X509* SSL_CTX_get0_certificate (const SSL_CTX * ctx)
Definition at line 3309 of file ssl_lib.c.
References NULL.
SSL_CTX_get0_ctlog_store()
const CTLOG_STORE* SSL_CTX_get0_ctlog_store (const SSL_CTX * ctx)
Definition at line 4303 of file ssl_lib.c.
SSL_CTX_get0_param()
X509_VERIFY_PARAM* SSL_CTX_get0_param (SSL_CTX * ctx)
Definition at line 947 of file ssl_lib.c.
SSL_CTX_get0_privatekey()
EVP_PKEY* SSL_CTX_get0_privatekey (const SSL_CTX * ctx)
Definition at line 3317 of file ssl_lib.c.
References NULL.
SSL_CTX_get0_security_ex_data()
void* SSL_CTX_get0_security_ex_data (const SSL_CTX * ctx)
Definition at line 3880 of file ssl_lib.c.
SSL_CTX_get_cert_store()
X509_STORE* SSL_CTX_get_cert_store (const SSL_CTX * ctx)
Definition at line 3592 of file ssl_lib.c.
Referenced by ssl_ctx_add_crls().
SSL_CTX_get_default_passwd_cb()
pem_password_cb* SSL_CTX_get_default_passwd_cb (SSL_CTX * ctx)
Definition at line 2692 of file ssl_lib.c.
SSL_CTX_get_default_passwd_cb_userdata()
void* SSL_CTX_get_default_passwd_cb_userdata (SSL_CTX * ctx)
Definition at line 2697 of file ssl_lib.c.
SSL_CTX_get_ex_data()
void* SSL_CTX_get_ex_data (const SSL_CTX * s, int idx)
Definition at line 3582 of file ssl_lib.c.
SSL_CTX_get_keylog_callback()
SSL_CTX_keylog_cb_func SSL_CTX_get_keylog_callback (const SSL_CTX * ctx)
Definition at line 4315 of file ssl_lib.c.
SSL_CTX_get_options()
unsigned long SSL_CTX_get_options (const SSL_CTX * ctx)
Definition at line 3890 of file ssl_lib.c.
SSL_CTX_get_quiet_shutdown()
int SSL_CTX_get_quiet_shutdown (const SSL_CTX * ctx)
Definition at line 3388 of file ssl_lib.c.
SSL_CTX_get_security_level()
int SSL_CTX_get_security_level (const SSL_CTX * ctx)
Definition at line 3853 of file ssl_lib.c.
SSL_CTX_get_ssl_method()
const SSL_METHOD* SSL_CTX_get_ssl_method (SSL_CTX * ctx)
Definition at line 2912 of file ssl_lib.c.
SSL_CTX_get_verify_depth()
int SSL_CTX_get_verify_depth (const SSL_CTX * ctx)
Definition at line 1262 of file ssl_lib.c.
References X509_VERIFY_PARAM_get_depth().
SSL_CTX_get_verify_mode()
int SSL_CTX_get_verify_mode (const SSL_CTX * ctx)
Definition at line 1257 of file ssl_lib.c.
SSL_CTX_load_verify_locations()
int SSL_CTX_load_verify_locations (SSL_CTX * ctx, const char * CAfile, const char * CApath)
Definition at line 3504 of file ssl_lib.c.
References X509_STORE_load_locations().
Referenced by ctx_set_verify_locations().
SSL_CTX_new()
SSL_CTX* SSL_CTX_new (const SSL_METHOD * meth)
Definition at line 2466 of file ssl_lib.c.
Referenced by create_ssl_ctx_pair(), main(), and process_responder().
SSL_CTX_set0_ctlog_store()
void SSL_CTX_set0_ctlog_store (SSL_CTX * ctx, CTLOG_STORE * logs)
Definition at line 4297 of file ssl_lib.c.
References CTLOG_STORE_free().
SSL_CTX_set0_security_ex_data()
void SSL_CTX_set0_security_ex_data (SSL_CTX * ctx, void * ex)
Definition at line 3875 of file ssl_lib.c.
References ex.
SSL_CTX_set1_cert_store()
void SSL_CTX_set1_cert_store (SSL_CTX * ctx, X509_STORE * store)
Definition at line 3603 of file ssl_lib.c.
References NULL, SSL_CTX_set_cert_store(), and X509_STORE_up_ref().
SSL_CTX_set1_param()
int SSL_CTX_set1_param (SSL_CTX * ctx, X509_VERIFY_PARAM * vpm)
Definition at line 937 of file ssl_lib.c.
References X509_VERIFY_PARAM_set1().
SSL_CTX_set_alpn_protos()
int SSL_CTX_set_alpn_protos (SSL_CTX * ctx, const unsigned char * protos, unsigned int protos_len)
Definition at line 2346 of file ssl_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_memdup, SSL_F_SSL_CTX_SET_ALPN_PROTOS, and SSLerr.
SSL_CTX_set_alpn_select_cb()
void SSL_CTX_set_alpn_select_cb (SSL_CTX * ctx, SSL_CTX_alpn_select_cb_func cb, void * arg)
Definition at line 2384 of file ssl_lib.c.
SSL_CTX_set_cert_cb()
void SSL_CTX_set_cert_cb (SSL_CTX * c, int(*)(SSL *ssl, void *arg) cb, void * arg)
Definition at line 2742 of file ssl_lib.c.
Referenced by ssl_ctx_set_excert().
SSL_CTX_set_cert_store()
void SSL_CTX_set_cert_store (SSL_CTX * ctx, X509_STORE * store)
Definition at line 3597 of file ssl_lib.c.
References X509_STORE_free().
Referenced by SSL_CTX_set1_cert_store().
SSL_CTX_set_cert_verify_callback()
void SSL_CTX_set_cert_verify_callback (SSL_CTX * ctx, int(*)(X509_STORE_CTX *, void *) cb, void * arg)
Definition at line 2722 of file ssl_lib.c.
SSL_CTX_set_cipher_list()
int SSL_CTX_set_cipher_list (SSL_CTX * ctx, const char * str)
specify the ciphers to be used by default by the SSL_CTX
Definition at line 2129 of file ssl_lib.c.
References NULL, SSL_F_SSL_CTX_SET_CIPHER_LIST, SSL_R_NO_CIPHER_MATCH, SSLerr, and STACK_OF().
SSL_CTX_set_ct_validation_callback()
int SSL_CTX_set_ct_validation_callback (SSL_CTX * ctx, ssl_ct_validation_cb callback, void * arg)
Definition at line 4135 of file ssl_lib.c.
Referenced by SSL_CTX_enable_ct().
SSL_CTX_set_ctlog_list_file()
int SSL_CTX_set_ctlog_list_file (SSL_CTX * ctx, const char * path)
Definition at line 4292 of file ssl_lib.c.
References CTLOG_STORE_load_file().
Referenced by ctx_set_ctlog_list_file().
SSL_CTX_set_default_ctlog_list_file()
int SSL_CTX_set_default_ctlog_list_file (SSL_CTX * ctx)
Definition at line 4287 of file ssl_lib.c.
References CTLOG_STORE_load_default_file().
Referenced by ctx_set_ctlog_list_file().
SSL_CTX_set_default_passwd_cb()
void SSL_CTX_set_default_passwd_cb (SSL_CTX * ctx, pem_password_cb * cb)
Definition at line 2682 of file ssl_lib.c.
References cb.
SSL_CTX_set_default_passwd_cb_userdata()
void SSL_CTX_set_default_passwd_cb_userdata (SSL_CTX * ctx, void * u)
Definition at line 2687 of file ssl_lib.c.
References u.
SSL_CTX_set_default_verify_dir()
int SSL_CTX_set_default_verify_dir (SSL_CTX * ctx)
Definition at line 3473 of file ssl_lib.c.
Referenced by ctx_set_verify_locations().
SSL_CTX_set_default_verify_file()
int SSL_CTX_set_default_verify_file (SSL_CTX * ctx)
Definition at line 3488 of file ssl_lib.c.
Referenced by ctx_set_verify_locations().
SSL_CTX_set_default_verify_paths()
int SSL_CTX_set_default_verify_paths (SSL_CTX * ctx)
Definition at line 3468 of file ssl_lib.c.
References X509_STORE_set_default_paths().
SSL_CTX_set_ex_data()
int SSL_CTX_set_ex_data (SSL_CTX * s, int idx, void * arg)
Definition at line 3577 of file ssl_lib.c.
SSL_CTX_set_generate_session_id()
int SSL_CTX_set_generate_session_id (SSL_CTX * ctx, GEN_SESSION_CB cb)
Definition at line 722 of file ssl_lib.c.
References cb, CRYPTO_THREAD_unlock(), and CRYPTO_THREAD_write_lock().
SSL_CTX_set_keylog_callback()
void SSL_CTX_set_keylog_callback (SSL_CTX * ctx, SSL_CTX_keylog_cb_func cb)
Definition at line 4310 of file ssl_lib.c.
References cb.
SSL_CTX_set_msg_callback()
void SSL_CTX_set_msg_callback (SSL_CTX * ctx, void(*)(int write_p, int version, int content_type, const void *buf, size_t len, SSL *ssl, void *arg) cb)
Definition at line 3707 of file ssl_lib.c.
SSL_CTX_set_not_resumable_session_callback()
void SSL_CTX_set_not_resumable_session_callback (SSL_CTX * ctx, int(*)(SSL *ssl, int is_forward_secure) cb)
Definition at line 3723 of file ssl_lib.c.
References cb, SSL_CTRL_SET_NOT_RESUMABLE_SESS_CB, and SSL_CTX_callback_ctrl().
SSL_CTX_set_npn_advertised_cb()
void SSL_CTX_set_npn_advertised_cb (SSL_CTX * ctx, SSL_CTX_npn_advertised_cb_func cb, void * arg)
Definition at line 2314 of file ssl_lib.c.
SSL_CTX_set_npn_select_cb()
void SSL_CTX_set_npn_select_cb (SSL_CTX * ctx, SSL_CTX_npn_select_cb_func cb, void * arg)
Definition at line 2332 of file ssl_lib.c.
SSL_CTX_set_options()
unsigned long SSL_CTX_set_options (SSL_CTX * ctx, unsigned long op)
Definition at line 3900 of file ssl_lib.c.
SSL_CTX_set_psk_client_callback()
void SSL_CTX_set_psk_client_callback (SSL_CTX * ctx, SSL_psk_client_cb_func cb)
Definition at line 3691 of file ssl_lib.c.
References cb.
SSL_CTX_set_psk_server_callback()
void SSL_CTX_set_psk_server_callback (SSL_CTX * ctx, SSL_psk_server_cb_func cb)
Definition at line 3701 of file ssl_lib.c.
References cb.
Referenced by main().
SSL_CTX_set_purpose()
int SSL_CTX_set_purpose (SSL_CTX * s, int purpose)
Definition at line 763 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_purpose().
SSL_CTX_set_quiet_shutdown()
void SSL_CTX_set_quiet_shutdown (SSL_CTX * ctx, int mode)
Definition at line 3383 of file ssl_lib.c.
SSL_CTX_set_security_callback()
void SSL_CTX_set_security_callback (SSL_CTX * ctx, int(*)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex) cb)
Definition at line 3858 of file ssl_lib.c.
References cb.
SSL_CTX_set_security_level()
void SSL_CTX_set_security_level (SSL_CTX * ctx, int level)
Definition at line 3848 of file ssl_lib.c.
SSL_CTX_set_session_id_context()
int SSL_CTX_set_session_id_context (SSL_CTX * ctx, const unsigned char * sid_ctx, unsigned int sid_ctx_len)
Definition at line 694 of file ssl_lib.c.
References SSL_F_SSL_CTX_SET_SESSION_ID_CONTEXT, SSL_R_SSL_SESSION_ID_CONTEXT_TOO_LONG, and SSLerr.
SSL_CTX_set_ssl_version()
int SSL_CTX_set_ssl_version (SSL_CTX * ctx, const SSL_METHOD * meth)
Used to change an SSL_CTXs default SSL method type
Definition at line 505 of file ssl_lib.c.
References NULL, SSL_DEFAULT_CIPHER_LIST, SSL_F_SSL_CTX_SET_SSL_VERSION, SSL_R_SSL_LIBRARY_HAS_NO_CIPHERS, SSLerr, and STACK_OF().
SSL_CTX_set_tmp_dh_callback()
void SSL_CTX_set_tmp_dh_callback (SSL_CTX * ctx, DH *(*)(SSL *ssl, int is_export, int keylength) dh)
Set the callback for generating temporary DH keys.
Parameters
ctx the SSL context.
dh the callback
Definition at line 3622 of file ssl_lib.c.
References SSL_CTRL_SET_TMP_DH_CB, and SSL_CTX_callback_ctrl().
SSL_CTX_set_trust()
int SSL_CTX_set_trust (SSL_CTX * s, int trust)
Definition at line 773 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_trust().
SSL_CTX_set_verify()
void SSL_CTX_set_verify (SSL_CTX * ctx, int mode, int(*)(int, X509_STORE_CTX *) cb)
Definition at line 2730 of file ssl_lib.c.
References cb.
SSL_CTX_set_verify_depth()
void SSL_CTX_set_verify_depth (SSL_CTX * ctx, int depth)
Definition at line 2737 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_depth().
SSL_CTX_up_ref()
int SSL_CTX_up_ref (SSL_CTX * ctx)
Definition at line 2609 of file ssl_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by SSL_new(), and SSL_set_SSL_CTX().
SSL_CTX_use_psk_identity_hint()
int SSL_CTX_use_psk_identity_hint (SSL_CTX * ctx, const char * identity_hint)
Definition at line 3637 of file ssl_lib.c.
References NULL, OPENSSL_free, OPENSSL_strdup, PSK_MAX_IDENTITY_LEN, SSL_F_SSL_CTX_USE_PSK_IDENTITY_HINT, SSL_R_DATA_LENGTH_TOO_LONG, and SSLerr.
SSL_dane_clear_flags()
unsigned long SSL_dane_clear_flags (SSL * ssl, unsigned long flags)
Definition at line 875 of file ssl_lib.c.
SSL_dane_enable()
int SSL_dane_enable (SSL * s, const char * basedomain)
Definition at line 824 of file ssl_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, SSL_F_SSL_DANE_ENABLE, SSL_R_CONTEXT_NOT_DANE_ENABLED, SSL_R_DANE_ALREADY_ENABLED, SSL_R_ERROR_SETTING_TLSA_BASE_DOMAIN, SSL_set_tlsext_host_name, SSLerr, and X509_VERIFY_PARAM_set1_host().
SSL_dane_set_flags()
unsigned long SSL_dane_set_flags (SSL * ssl, unsigned long flags)
Definition at line 867 of file ssl_lib.c.
References flags.
SSL_dane_tlsa_add()
int SSL_dane_tlsa_add (SSL * s, uint8_t usage, uint8_t selector, uint8_t mtype, unsigned char * data, size_t dlen)
Definition at line 925 of file ssl_lib.c.
SSL_do_handshake()
int SSL_do_handshake (SSL * s)
Definition at line 3043 of file ssl_lib.c.
Referenced by SSL_accept(), and SSL_connect().
SSL_dup()
SSL* SSL_dup (SSL * s)
Definition at line 3148 of file ssl_lib.c.
References STACK_OF().
SSL_enable_ct()
int SSL_enable_ct (SSL * s, int validation_mode)
Definition at line 4274 of file ssl_lib.c.
References SSL_CT_VALIDATION_PERMISSIVE, SSL_F_SSL_ENABLE_CT, SSL_R_INVALID_CT_VALIDATION_TYPE, SSL_set_ct_validation_callback(), and SSLerr.
SSL_export_keying_material()
int SSL_export_keying_material (SSL * s, unsigned char * out, size_t olen, const char * label, size_t llen, const unsigned char * p, size_t plen, int use_context)
Definition at line 2410 of file ssl_lib.c.
Referenced by ossl_statem_server_post_work(), tls_client_key_exchange_post_work(), and tls_post_process_client_key_exchange().
SSL_free()
void SSL_free (SSL * s)
Definition at line 962 of file ssl_lib.c.
References CRYPTO_DOWN_REF, NULL, REF_ASSERT_ISNT, REF_PRINT_COUNT, and X509_VERIFY_PARAM_free().
Referenced by create_ssl_objects(), and SSL_new().
ssl_free_wbio_buffer()
void ssl_free_wbio_buffer (SSL * s)
Definition at line 3371 of file ssl_lib.c.
References BIO_free(), BIO_pop(), and NULL.
Referenced by ssl3_clear().
SSL_get0_alpn_selected()
void SSL_get0_alpn_selected (const SSL * ssl, const unsigned char ** data, unsigned int * len)
Definition at line 2398 of file ssl_lib.c.
References NULL.
SSL_get0_dane()
SSL_DANE* SSL_get0_dane (SSL * s)
Definition at line 920 of file ssl_lib.c.
SSL_get0_dane_authority()
int SSL_get0_dane_authority (SSL * s, X509 ** mcert, EVP_PKEY ** mspki)
Definition at line 883 of file ssl_lib.c.
References DANETLS_ENABLED, NULL, and X509_V_OK.
SSL_get0_dane_tlsa()
int SSL_get0_dane_tlsa (SSL * s, uint8_t * usage, uint8_t * selector, uint8_t * mtype, unsigned const char ** data, size_t * dlen)
Definition at line 898 of file ssl_lib.c.
References DANETLS_ENABLED, and X509_V_OK.
SSL_get0_next_proto_negotiated()
void SSL_get0_next_proto_negotiated (const SSL * s, const unsigned char ** data, unsigned * len)
Definition at line 2293 of file ssl_lib.c.
SSL_get0_param()
X509_VERIFY_PARAM* SSL_get0_param (SSL * ssl)
Definition at line 952 of file ssl_lib.c.
SSL_get0_peername()
const char* SSL_get0_peername (SSL * s)
Definition at line 798 of file ssl_lib.c.
References X509_VERIFY_PARAM_get0_peername().
SSL_get0_security_ex_data()
void* SSL_get0_security_ex_data (const SSL * s)
Definition at line 3843 of file ssl_lib.c.
SSL_get_all_async_fds()
int SSL_get_all_async_fds (SSL * s, OSSL_ASYNC_FD * fds, size_t * numfds)
Definition at line 1435 of file ssl_lib.c.
References ASYNC_WAIT_CTX_get_all_fds(), ctx, and NULL.
Referenced by wait_for_async().
SSL_get_certificate()
X509* SSL_get_certificate (const SSL * s)
Definition at line 3293 of file ssl_lib.c.
References NULL.
SSL_get_changed_async_fds()
int SSL_get_changed_async_fds (SSL * s, OSSL_ASYNC_FD * addfd, size_t * numaddfds, OSSL_ASYNC_FD * delfd, size_t * numdelfds)
Definition at line 1444 of file ssl_lib.c.
References ASYNC_WAIT_CTX_get_changed_fds(), ctx, and NULL.
SSL_get_cipher_list()
const char* SSL_get_cipher_list (const SSL * s, int n)
The old interface to get the same thing as SSL_get_ciphers()
Definition at line 2103 of file ssl_lib.c.
SSL_get_client_random()
size_t SSL_get_client_random (const SSL * ssl, unsigned char * out, size_t outlen)
Definition at line 3536 of file ssl_lib.c.
SSL_get_current_cipher()
const SSL_CIPHER* SSL_get_current_cipher (const SSL * s)
Definition at line 3325 of file ssl_lib.c.
References NULL.
Referenced by DTLS_get_data_mtu().
SSL_get_current_compression()
const COMP_METHOD* SSL_get_current_compression (SSL * s)
Definition at line 3332 of file ssl_lib.c.
References COMP_CTX_get_method(), and NULL.
SSL_get_current_expansion()
const COMP_METHOD* SSL_get_current_expansion (SSL * s)
Definition at line 3341 of file ssl_lib.c.
References COMP_CTX_get_method(), and NULL.
SSL_get_default_passwd_cb()
pem_password_cb* SSL_get_default_passwd_cb (SSL * s)
Definition at line 2712 of file ssl_lib.c.
SSL_get_default_passwd_cb_userdata()
void* SSL_get_default_passwd_cb_userdata (SSL * s)
Definition at line 2717 of file ssl_lib.c.
SSL_get_default_timeout()
long SSL_get_default_timeout (const SSL * s)
Definition at line 1475 of file ssl_lib.c.
SSL_get_error()
int SSL_get_error (const SSL * s, int i)
Definition at line 2946 of file ssl_lib.c.
References BIO_get_retry_reason(), BIO_RR_ACCEPT, BIO_RR_CONNECT, BIO_should_io_special, BIO_should_read, BIO_should_write, ERR_GET_LIB, ERR_LIB_SYS, ERR_peek_error(), SSL_AD_CLOSE_NOTIFY, SSL_ERROR_NONE, SSL_ERROR_SSL, SSL_ERROR_SYSCALL, SSL_ERROR_WANT_ACCEPT, SSL_ERROR_WANT_ASYNC, SSL_ERROR_WANT_ASYNC_JOB, SSL_ERROR_WANT_CONNECT, SSL_ERROR_WANT_READ, SSL_ERROR_WANT_WRITE, SSL_ERROR_WANT_X509_LOOKUP, SSL_ERROR_ZERO_RETURN, SSL_get_rbio(), SSL_RECEIVED_SHUTDOWN, SSL_want_async, SSL_want_async_job, SSL_want_read, SSL_want_write, and SSL_want_x509_lookup.
SSL_get_ex_data()
void* SSL_get_ex_data (const SSL * s, int idx)
Definition at line 3572 of file ssl_lib.c.
SSL_get_fd()
int SSL_get_fd (const SSL * s)
Definition at line 1123 of file ssl_lib.c.
References SSL_get_rfd().
SSL_get_finished()
size_t SSL_get_finished (const SSL * s, void * buf, size_t count)
Definition at line 1216 of file ssl_lib.c.
SSL_get_key_update_type()
int SSL_get_key_update_type (SSL * s)
Definition at line 1749 of file ssl_lib.c.
SSL_get_options()
unsigned long SSL_get_options (const SSL * s)
Definition at line 3895 of file ssl_lib.c.
Referenced by dtls1_check_timeout_num(), dtls1_query_mtu(), and tls_construct_stoc_cryptopro_bug().
SSL_get_peer_certificate()
X509* SSL_get_peer_certificate (const SSL * s)
Definition at line 1327 of file ssl_lib.c.
References NULL, and X509_up_ref().
SSL_get_peer_finished()
size_t SSL_get_peer_finished (const SSL * s, void * buf, size_t count)
Definition at line 1230 of file ssl_lib.c.
SSL_get_privatekey()
EVP_PKEY* SSL_get_privatekey (const SSL * s)
Definition at line 3301 of file ssl_lib.c.
References NULL.
SSL_get_psk_identity()
const char* SSL_get_psk_identity (const SSL * s)
Definition at line 3679 of file ssl_lib.c.
References NULL.
SSL_get_psk_identity_hint()
const char* SSL_get_psk_identity_hint (const SSL * s)
Definition at line 3672 of file ssl_lib.c.
References NULL.
SSL_get_quiet_shutdown()
int SSL_get_quiet_shutdown (const SSL * s)
Definition at line 3398 of file ssl_lib.c.
SSL_get_rbio()
BIO* SSL_get_rbio (const SSL * s)
Definition at line 1106 of file ssl_lib.c.
Referenced by dtls1_buffer_record(), dtls1_get_record(), dtls1_process_buffered_records(), dtls1_read_failed(), dtls1_stop_timer(), ossl_statem_client_post_process_message(), ossl_statem_server_post_process_message(), SSL_get_error(), SSL_set_bio(), SSL_set_wfd(), and tls_post_process_client_key_exchange().
SSL_get_read_ahead()
int SSL_get_read_ahead (const SSL * s)
Definition at line 1289 of file ssl_lib.c.
References RECORD_LAYER_get_read_ahead.
SSL_get_rfd()
int SSL_get_rfd (const SSL * s)
Definition at line 1128 of file ssl_lib.c.
Referenced by SSL_get_fd().
SSL_get_security_level()
int SSL_get_security_level (const SSL * s)
Definition at line 3818 of file ssl_lib.c.
Referenced by ssl_verify_cert_chain().
ssl_get_server_cert_serverinfo()
int ssl_get_server_cert_serverinfo (SSL * s, const unsigned char ** serverinfo, size_t * serverinfo_length)
Definition at line 2867 of file ssl_lib.c.
References NULL.
SSL_get_server_random()
size_t SSL_get_server_random (const SSL * ssl, unsigned char * out, size_t outlen)
Definition at line 3546 of file ssl_lib.c.
SSL_get_servername()
const char* SSL_get_servername (const SSL * s, const int type)
return a servername extension value if provided in Client Hello, or NULL. So far, only host_name types are defined (RFC 3546).
Definition at line 2208 of file ssl_lib.c.
References NULL, and TLSEXT_NAMETYPE_host_name.
SSL_get_servername_type()
int SSL_get_servername_type (const SSL * s)
Definition at line 2217 of file ssl_lib.c.
References TLSEXT_NAMETYPE_host_name.
SSL_get_shared_ciphers()
char* SSL_get_shared_ciphers (const SSL * s, char * buf, int len)
Definition at line 2168 of file ssl_lib.c.
References STACK_OF().
SSL_get_shutdown()
int SSL_get_shutdown (const SSL * s)
Definition at line 3408 of file ssl_lib.c.
SSL_get_SSL_CTX()
SSL_CTX* SSL_get_SSL_CTX (const SSL * ssl)
Definition at line 3423 of file ssl_lib.c.
SSL_get_ssl_method()
const SSL_METHOD* SSL_get_ssl_method (SSL * s)
Definition at line 2917 of file ssl_lib.c.
SSL_get_verify_depth()
int SSL_get_verify_depth (const SSL * s)
Definition at line 1248 of file ssl_lib.c.
References X509_VERIFY_PARAM_get_depth().
SSL_get_verify_mode()
int SSL_get_verify_mode (const SSL * s)
Definition at line 1243 of file ssl_lib.c.
SSL_get_verify_result()
long SSL_get_verify_result (const SSL * ssl)
Definition at line 3531 of file ssl_lib.c.
SSL_get_version()
const char* SSL_get_version (const SSL * s)
Definition at line 3143 of file ssl_lib.c.
References ssl_protocol_to_string().
SSL_get_wbio()
BIO* SSL_get_wbio (const SSL * s)
Definition at line 1111 of file ssl_lib.c.
References BIO_next(), and NULL.
Referenced by dtls1_check_timeout_num(), dtls1_query_mtu(), dtls1_start_timer(), dtls1_write_app_data_bytes(), ossl_statem_client_post_work(), ossl_statem_client_pre_work(), ossl_statem_server_post_process_message(), ossl_statem_server_post_work(), ossl_statem_server_pre_work(), SSL_set_bio(), SSL_set_rfd(), tls_client_key_exchange_post_work(), tls_finish_handshake(), and tls_post_process_client_key_exchange().
SSL_get_wfd()
int SSL_get_wfd (const SSL * s)
Definition at line 1140 of file ssl_lib.c.
ssl_handshake_hash()
int ssl_handshake_hash (SSL * s, unsigned char * out, size_t outlen, size_t * hashlen)
Definition at line 3767 of file ssl_lib.c.
Referenced by tls1_final_finish_mac(), and tls1_generate_master_secret().
SSL_has_matching_session_id()
int SSL_has_matching_session_id (const SSL * ssl, const unsigned char * id, unsigned int id_len)
Definition at line 738 of file ssl_lib.c.
References CRYPTO_THREAD_read_lock(), CRYPTO_THREAD_unlock(), and NULL.
SSL_has_pending()
int SSL_has_pending (const SSL * s)
Definition at line 1311 of file ssl_lib.c.
References RECORD_LAYER_read_pending(), and SSL_pending().
ssl_init_wbio_buffer()
int ssl_init_wbio_buffer (SSL * s)
Definition at line 3350 of file ssl_lib.c.
References BIO_f_buffer(), BIO_free(), BIO_new(), BIO_push(), BIO_set_read_buffer_size, ERR_R_BUF_LIB, NULL, SSL_F_SSL_INIT_WBIO_BUFFER, and SSLerr.
SSL_is_dtls()
int SSL_is_dtls (const SSL * s)
Definition at line 677 of file ssl_lib.c.
References SSL_IS_DTLS.
Referenced by create_ssl_objects().
SSL_is_server()
int SSL_is_server (SSL * s)
Definition at line 3799 of file ssl_lib.c.
Referenced by ssl_print_sigalgs().
SSL_key_update()
int SSL_key_update (SSL * s, int updatetype)
Definition at line 1721 of file ssl_lib.c.
References ossl_statem_set_in_init(), SSL_F_SSL_KEY_UPDATE, SSL_is_init_finished(), SSL_IS_TLS13, SSL_KEY_UPDATE_NOT_REQUESTED, SSL_KEY_UPDATE_REQUESTED, SSL_R_INVALID_KEY_UPDATE_TYPE, SSL_R_STILL_IN_INIT, SSL_R_WRONG_SSL_VERSION, and SSLerr.
ssl_log_rsa_client_key_exchange()
int ssl_log_rsa_client_key_exchange (SSL * ssl, const uint8_t * encrypted_premaster, size_t encrypted_premaster_len, const uint8_t * premaster, size_t premaster_len)
Definition at line 4372 of file ssl_lib.c.
References ERR_R_INTERNAL_ERROR, SSL_F_SSL_LOG_RSA_CLIENT_KEY_EXCHANGE, and SSLerr.
ssl_log_secret()
int ssl_log_secret (SSL * ssl, const char * label, const uint8_t * secret, size_t secret_len)
Definition at line 4392 of file ssl_lib.c.
Referenced by tls_construct_finished().
SSL_new()
SSL* SSL_new (SSL_CTX * ctx)
Definition at line 521 of file ssl_lib.c.
References CRYPTO_EX_INDEX_SSL, CRYPTO_new_ex_data(), CRYPTO_THREAD_lock_new(), ctx, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_assert, OPENSSL_free, OPENSSL_malloc, OPENSSL_memdup, OPENSSL_zalloc, RECORD_LAYER_init(), RECORD_LAYER_set_read_ahead, ssl_async_args::s, ssl_cert_dup(), SSL_clear(), SSL_CTX_up_ref(), SSL_F_SSL_NEW, SSL_free(), SSL_KEY_UPDATE_NONE, SSL_R_NULL_SSL_CTX, SSL_R_SSL_CTX_HAS_NO_DEFAULT_SSL_VERSION, SSL_set_ct_validation_callback(), SSL_set_default_read_buffer_len(), ssl_undefined_function(), SSLerr, X509_V_OK, X509_VERIFY_PARAM_inherit(), and X509_VERIFY_PARAM_new().
Referenced by create_ssl_objects().
ssl_ok()
int ssl_ok (SSL * s)
Definition at line 3587 of file ssl_lib.c.
SSL_peek()
int SSL_peek (SSL * s, void * buf, int num)
Definition at line 1586 of file ssl_lib.c.
SSL_peek_ex()
int SSL_peek_ex (SSL * s, void * buf, size_t num, size_t * readbytes)
Definition at line 1608 of file ssl_lib.c.
References ASYNC_get_current_job(), NULL, SSL_F_SSL_PEEK_EX, SSL_MODE_ASYNC, SSL_R_UNINITIALIZED, SSL_RECEIVED_SHUTDOWN, and SSLerr.
SSL_pending()
int SSL_pending (const SSL * s)
Definition at line 1294 of file ssl_lib.c.
Referenced by SSL_has_pending().
ssl_protocol_to_string()
const char* ssl_protocol_to_string (int version)
Definition at line 3110 of file ssl_lib.c.
References DTLS1_2_VERSION, DTLS1_BAD_VER, DTLS1_VERSION, SSL3_VERSION, TLS1_1_VERSION, TLS1_2_VERSION, TLS1_3_VERSION, and TLS1_VERSION.
Referenced by SSL_CIPHER_get_version(), SSL_get_version(), and SSL_SESSION_print().
SSL_read()
int SSL_read (SSL * s, void * buf, int num)
Definition at line 1534 of file ssl_lib.c.
SSL_read_ex()
int SSL_read_ex (SSL * s, void * buf, size_t num, size_t * readbytes)
Definition at line 1556 of file ssl_lib.c.
References ASYNC_get_current_job(), NULL, SSL_F_SSL_READ_EX, SSL_MODE_ASYNC, SSL_NOTHING, SSL_R_UNINITIALIZED, SSL_RECEIVED_SHUTDOWN, and SSLerr.
SSL_renegotiate()
int SSL_renegotiate (SSL * s)
Definition at line 1754 of file ssl_lib.c.
References SSL_F_SSL_RENEGOTIATE, SSL_IS_TLS13, SSL_R_WRONG_SSL_VERSION, and SSLerr.
SSL_renegotiate_abbreviated()
int SSL_renegotiate_abbreviated (SSL * s)
Definition at line 1769 of file ssl_lib.c.
References SSL_IS_TLS13.
SSL_renegotiate_pending()
int SSL_renegotiate_pending (SSL * s)
Definition at line 1782 of file ssl_lib.c.
ssl_replace_hash()
EVP_MD_CTX* ssl_replace_hash (EVP_MD_CTX ** hash, const EVP_MD * md)
Definition at line 3747 of file ssl_lib.c.
SSL_select_next_proto()
int SSL_select_next_proto (unsigned char ** out, unsigned char * outlen, const unsigned char * server, unsigned int server_len, const unsigned char * client, unsigned int client_len)
Definition at line 2246 of file ssl_lib.c.
SSL_SESSION_get_master_key()
size_t SSL_SESSION_get_master_key (const SSL_SESSION * session, unsigned char * out, size_t outlen)
Definition at line 3556 of file ssl_lib.c.
SSL_session_reused()
int SSL_session_reused (SSL * s)
Definition at line 3794 of file ssl_lib.c.
SSL_set0_rbio()
void SSL_set0_rbio (SSL * s, BIO * rbio)
Definition at line 1044 of file ssl_lib.c.
References BIO_free_all().
Referenced by SSL_set_bio(), and SSL_set_rfd().
SSL_set0_security_ex_data()
void SSL_set0_security_ex_data (SSL * s, void * ex)
Definition at line 3838 of file ssl_lib.c.
References ex.
SSL_set0_wbio()
void SSL_set0_wbio (SSL * s, BIO * wbio)
Definition at line 1050 of file ssl_lib.c.
References BIO_free_all(), BIO_pop(), BIO_push(), and NULL.
Referenced by SSL_set_bio(), and SSL_set_wfd().
SSL_set1_host()
int SSL_set1_host (SSL * s, const char * hostname)
Definition at line 783 of file ssl_lib.c.
References X509_VERIFY_PARAM_set1_host().
SSL_set1_param()
int SSL_set1_param (SSL * ssl, X509_VERIFY_PARAM * vpm)
Definition at line 942 of file ssl_lib.c.
References X509_VERIFY_PARAM_set1().
SSL_set_accept_state()
void SSL_set_accept_state (SSL * s)
Definition at line 3068 of file ssl_lib.c.
References ossl_statem_clear().
Referenced by SSL_accept().
SSL_set_alpn_protos()
int SSL_set_alpn_protos (SSL * ssl, const unsigned char * protos, unsigned int protos_len)
Definition at line 2365 of file ssl_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_memdup, SSL_F_SSL_SET_ALPN_PROTOS, and SSLerr.
SSL_set_bio()
void SSL_set_bio (SSL * s, BIO * rbio, BIO * wbio)
Definition at line 1066 of file ssl_lib.c.
References BIO_up_ref(), NULL, SSL_get_rbio(), SSL_get_wbio(), SSL_set0_rbio(), and SSL_set0_wbio().
Referenced by create_ssl_objects().
SSL_set_cert_cb()
void SSL_set_cert_cb (SSL * s, int(*)(SSL *ssl, void *arg) cb, void * arg)
Definition at line 2747 of file ssl_lib.c.
SSL_set_cipher_list()
int SSL_set_cipher_list (SSL * s, const char * str)
specify the ciphers to be used by the SSL
Definition at line 2152 of file ssl_lib.c.
References NULL, SSL_F_SSL_SET_CIPHER_LIST, SSL_R_NO_CIPHER_MATCH, SSLerr, and STACK_OF().
SSL_set_connect_state()
void SSL_set_connect_state (SSL * s)
Definition at line 3077 of file ssl_lib.c.
References ossl_statem_clear().
Referenced by SSL_connect().
SSL_set_ct_validation_callback()
int SSL_set_ct_validation_callback (SSL * s, ssl_ct_validation_cb callback, void * arg)
Definition at line 4106 of file ssl_lib.c.
Referenced by SSL_enable_ct(), and SSL_new().
SSL_set_debug()
void SSL_set_debug (SSL * s, int debug)
Definition at line 3805 of file ssl_lib.c.
SSL_set_default_passwd_cb()
void SSL_set_default_passwd_cb (SSL * s, pem_password_cb * cb)
Definition at line 2702 of file ssl_lib.c.
References cb.
SSL_set_default_passwd_cb_userdata()
void SSL_set_default_passwd_cb_userdata (SSL * s, void * u)
Definition at line 2707 of file ssl_lib.c.
References u.
SSL_set_ex_data()
int SSL_set_ex_data (SSL * s, int idx, void * arg)
Definition at line 3567 of file ssl_lib.c.
SSL_set_fd()
int SSL_set_fd (SSL * s, int fd)
Definition at line 1153 of file ssl_lib.c.
SSL_set_generate_session_id()
int SSL_set_generate_session_id (SSL * ssl, GEN_SESSION_CB cb)
Definition at line 730 of file ssl_lib.c.
References cb, CRYPTO_THREAD_unlock(), and CRYPTO_THREAD_write_lock().
SSL_set_hostflags()
void SSL_set_hostflags (SSL * s, unsigned int flags)
Definition at line 793 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_hostflags().
SSL_set_info_callback()
void SSL_set_info_callback (SSL * ssl, void(*)(const SSL *ssl, int type, int val) cb)
Definition at line 3510 of file ssl_lib.c.
References cb.
ssl_set_masks()
void ssl_set_masks (SSL * s)
Definition at line 2752 of file ssl_lib.c.
References CERT_PKEY_SIGN, CERT_PKEY_VALID, CERT::dh_tmp, CERT::dh_tmp_auto, CERT::dh_tmp_cb, NULL, SSL_PKEY_DSA_SIGN, SSL_PKEY_ECC, and SSL_PKEY_RSA.
SSL_set_msg_callback()
void SSL_set_msg_callback (SSL * ssl, void(*)(int write_p, int version, int content_type, const void *buf, size_t len, SSL *ssl, void *arg) cb)
Definition at line 3715 of file ssl_lib.c.
SSL_set_not_resumable_session_callback()
void SSL_set_not_resumable_session_callback (SSL * ssl, int(*)(SSL *ssl, int is_forward_secure) cb)
Definition at line 3732 of file ssl_lib.c.
References cb, SSL_callback_ctrl(), and SSL_CTRL_SET_NOT_RESUMABLE_SESS_CB.
SSL_set_options()
unsigned long SSL_set_options (SSL * s, unsigned long op)
Definition at line 3905 of file ssl_lib.c.
SSL_set_psk_client_callback()
void SSL_set_psk_client_callback (SSL * s, SSL_psk_client_cb_func cb)
Definition at line 3686 of file ssl_lib.c.
References cb.
SSL_set_psk_server_callback()
void SSL_set_psk_server_callback (SSL * s, SSL_psk_server_cb_func cb)
Definition at line 3696 of file ssl_lib.c.
References cb.
SSL_set_purpose()
int SSL_set_purpose (SSL * s, int purpose)
Definition at line 768 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_purpose().
SSL_set_quiet_shutdown()
void SSL_set_quiet_shutdown (SSL * s, int mode)
Definition at line 3393 of file ssl_lib.c.
SSL_set_read_ahead()
void SSL_set_read_ahead (SSL * s, int yes)
Definition at line 1284 of file ssl_lib.c.
References RECORD_LAYER_set_read_ahead.
SSL_set_rfd()
int SSL_set_rfd (SSL * s, int fd)
Definition at line 1192 of file ssl_lib.c.
References BIO_get_fd, BIO_method_type(), BIO_new(), BIO_NOCLOSE, BIO_s_socket(), BIO_set_fd, BIO_TYPE_SOCKET, BIO_up_ref(), ERR_R_BUF_LIB, NULL, SSL_F_SSL_SET_RFD, SSL_get_wbio(), SSL_set0_rbio(), and SSLerr.
SSL_set_security_callback()
void SSL_set_security_callback (SSL * s, int(*)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex) cb)
Definition at line 3823 of file ssl_lib.c.
References cb.
SSL_set_security_level()
void SSL_set_security_level (SSL * s, int level)
Definition at line 3813 of file ssl_lib.c.
SSL_set_session_id_context()
int SSL_set_session_id_context (SSL * ssl, const unsigned char * sid_ctx, unsigned int sid_ctx_len)
Definition at line 708 of file ssl_lib.c.
References SSL_F_SSL_SET_SESSION_ID_CONTEXT, SSL_MAX_SID_CTX_LENGTH, SSL_R_SSL_SESSION_ID_CONTEXT_TOO_LONG, and SSLerr.
Referenced by SSL_copy_session_id().
SSL_set_shutdown()
void SSL_set_shutdown (SSL * s, int mode)
Definition at line 3403 of file ssl_lib.c.
SSL_set_SSL_CTX()
SSL_CTX* SSL_set_SSL_CTX (SSL * ssl, SSL_CTX * ctx)
Definition at line 3428 of file ssl_lib.c.
References ctx, NULL, OPENSSL_assert, ssl_cert_dup(), ssl_cert_free(), SSL_CTX_free(), and SSL_CTX_up_ref().
SSL_set_ssl_method()
int SSL_set_ssl_method (SSL * s, const SSL_METHOD * meth)
Definition at line 2922 of file ssl_lib.c.
Referenced by SSL_set_session().
SSL_set_tmp_dh_callback()
void SSL_set_tmp_dh_callback (SSL * ssl, DH *(*)(SSL *ssl, int is_export, int keylength) dh)
Definition at line 3629 of file ssl_lib.c.
References SSL_callback_ctrl(), and SSL_CTRL_SET_TMP_DH_CB.
SSL_set_trust()
int SSL_set_trust (SSL * s, int trust)
Definition at line 778 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_trust().
SSL_set_verify()
void SSL_set_verify (SSL * s, int mode, int(*)(int ok, X509_STORE_CTX *ctx) callback)
Definition at line 1271 of file ssl_lib.c.
References callback, and NULL.
SSL_set_verify_depth()
void SSL_set_verify_depth (SSL * s, int depth)
Definition at line 1279 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_depth().
SSL_set_verify_result()
void SSL_set_verify_result (SSL * ssl, long arg)
Definition at line 3526 of file ssl_lib.c.
SSL_set_wfd()
int SSL_set_wfd (SSL * s, int fd)
Definition at line 1171 of file ssl_lib.c.
References BIO_get_fd, BIO_method_type(), BIO_new(), BIO_NOCLOSE, BIO_s_socket(), BIO_set_fd, BIO_TYPE_SOCKET, BIO_up_ref(), ERR_R_BUF_LIB, NULL, SSL_F_SSL_SET_WFD, SSL_get_rbio(), SSL_set0_wbio(), and SSLerr.
SSL_shutdown()
int SSL_shutdown (SSL * s)
Definition at line 1689 of file ssl_lib.c.
References ASYNC_get_current_job(), ssl_async_args::f, ssl_async_args::func_other, NULL, ssl_async_args::OTHERFUNC, ssl_async_args::s, SSL_F_SSL_SHUTDOWN, SSL_in_init(), SSL_MODE_ASYNC, SSL_R_UNINITIALIZED, SSLerr, and ssl_async_args::type.
Referenced by BIO_ssl_shutdown().
ssl_undefined_const_function()
int ssl_undefined_const_function (const SSL * s)
Definition at line 3099 of file ssl_lib.c.
ssl_undefined_function()
int ssl_undefined_function (SSL * s)
Definition at line 3086 of file ssl_lib.c.
References ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, SSL_F_SSL_UNDEFINED_FUNCTION, and SSLerr.
Referenced by SSL_new().
ssl_undefined_void_function()
int ssl_undefined_void_function (void)
Definition at line 3092 of file ssl_lib.c.
References ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED, SSL_F_SSL_UNDEFINED_VOID_FUNCTION, and SSLerr.
SSL_up_ref()
int SSL_up_ref (SSL * s)
Definition at line 682 of file ssl_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
ssl_update_cache()
void ssl_update_cache (SSL * s, int mode)
Definition at line 2881 of file ssl_lib.c.
References NULL, SSL_CTX_add_session(), SSL_CTX_flush_sessions(), SSL_SESS_CACHE_CLIENT, SSL_SESS_CACHE_NO_AUTO_CLEAR, SSL_SESS_CACHE_NO_INTERNAL_STORE, SSL_SESSION_free(), and SSL_SESSION_up_ref().
SSL_use_psk_identity_hint()
int SSL_use_psk_identity_hint (SSL * s, const char * identity_hint)
Definition at line 3653 of file ssl_lib.c.
References NULL, OPENSSL_free, OPENSSL_strdup, PSK_MAX_IDENTITY_LEN, SSL_F_SSL_USE_PSK_IDENTITY_HINT, SSL_R_DATA_LENGTH_TOO_LONG, and SSLerr.
ssl_validate_ct()
int ssl_validate_ct (SSL * s)
Definition at line 4165 of file ssl_lib.c.
SSL_version()
int SSL_version (const SSL * s)
Definition at line 3413 of file ssl_lib.c.
SSL_waiting_for_async()
int SSL_waiting_for_async (SSL * s)
Definition at line 1427 of file ssl_lib.c.
SSL_want()
int SSL_want (const SSL * s)
Definition at line 3610 of file ssl_lib.c.
SSL_write()
int SSL_write (SSL * s, const void * buf, int num)
Definition at line 1636 of file ssl_lib.c.
SSL_write_ex()
int SSL_write_ex (SSL * s, const void * buf, size_t num, size_t * written)
Definition at line 1658 of file ssl_lib.c.
References ASYNC_get_current_job(), NULL, SSL_F_SSL_WRITE_EX, SSL_MODE_ASYNC, SSL_NOTHING, SSL_R_PROTOCOL_IS_SHUTDOWN, SSL_R_UNINITIALIZED, SSL_SENT_SHUTDOWN, and SSLerr.
STACK_OF() [1/3]
STACK_OF (X509)
Definition at line 1344 of file ssl_lib.c.
References NULL.
Referenced by SSL_clear_options(), SSL_CTX_set_cipher_list(), SSL_CTX_set_ssl_version(), SSL_dup(), SSL_get_shared_ciphers(), SSL_set_cipher_list(), and STACK_OF().
STACK_OF() [2/3]
STACK_OF (SSL_CIPHER)
return a STACK of the ciphers available for the SSL and in order of preference
return a STACK of the ciphers available for the SSL and in order of algorithm id
return a STACK of the ciphers available for the SSL_CTX and in order of preference
Definition at line 2045 of file ssl_lib.c.
References NULL, ssl_set_client_disabled(), and STACK_OF().
STACK_OF() [3/3]
const STACK_OF (SCT)
Definition at line 4068 of file ssl_lib.c.
References CT_F_O2I_SCT_LIST, CT_R_SCT_LIST_INVALID, CTerr, MAX_SCT_LIST_SIZE, n2s, NULL, o2i_SCT(), SCT_free(), SCT_LIST_free(), and STACK_OF().
Variable Documentation
mtype
uint8_t mtype
Definition at line 93 of file ssl_lib.c.
nid
int nid
Definition at line 95 of file ssl_lib.c.
ord
uint8_t ord
Definition at line 94 of file ssl_lib.c.
ssl3_undef_enc_method
SSL3_ENC_METHOD ssl3_undef_enc_method
Initial value:
= {
    (int (*)(SSL *, SSL3_RECORD *, size_t, int))ssl_undefined_function,
    (int (*)(SSL *, SSL3_RECORD *, unsigned char *, int))ssl_undefined_function,
    ssl_undefined_function,
    (int (*)(SSL *, unsigned char *, unsigned char *, size_t, size_t *))
        ssl_undefined_function,
    (int (*)(SSL *, int))ssl_undefined_function,
    (size_t (*)(SSL *, const char *, size_t, unsigned char *))
        ssl_undefined_function,
    NULL,
    0,
    NULL,
    0,
    (int (*)(int))ssl_undefined_function,
    (int (*)(SSL *, unsigned char *, size_t, const char *,
             size_t, const unsigned char *, size_t,
             int use_context))ssl_undefined_function,
}
Definition at line 57 of file ssl_lib.c.
SSL_CTX_get_security_callback
int(*)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex) SSL_CTX_get_security_callback(const SSL_CTX *ctx)
Definition at line 3866 of file ssl_lib.c.
SSL_CTX_get_verify_callback
int(*)(int, X509_STORE_CTX *) SSL_CTX_get_verify_callback(const SSL_CTX *ctx)
Definition at line 1267 of file ssl_lib.c.
SSL_get_info_callback
void(*)(const SSL * , int , int) SSL_get_info_callback(const SSL *ssl)
Definition at line 3520 of file ssl_lib.c.
SSL_get_security_callback
int(*)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex) SSL_get_security_callback(const SSL *s)
Definition at line 3831 of file ssl_lib.c.
SSL_get_verify_callback
int(*)(int, X509_STORE_CTX *) SSL_get_verify_callback(const SSL *s)
Definition at line 1253 of file ssl_lib.c.
SSL_version_str
const char SSL_version_str[] = OPENSSL_VERSION_TEXT
Definition at line 55 of file ssl_lib.c.