ssl/ssl_cert.c File Reference
ssl_cert.c File Reference
#include <stdio.h>
#include "e_os.h"
#include <sys/types.h>
#include "internal/o_dir.h"
#include <openssl/lhash.h>
#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/x509v3.h>
#include <openssl/dh.h>
#include <openssl/bn.h>
#include <openssl/crypto.h>
#include "ssl_locl.h"
#include "internal/thread_once.h"
Functions
DEFINE_RUN_ONCE_STATIC (ssl_x509_store_ctx_init)
int SSL_get_ex_data_X509_STORE_CTX_idx (void)
CERT * ssl_cert_new (void)
CERT * ssl_cert_dup (CERT *cert)
void ssl_cert_clear_certs (CERT *c)
void ssl_cert_free (CERT *c)
int ssl_cert_set0_chain (SSL *s, SSL_CTX *ctx, STACK_OF(X509) *chain)
int ssl_cert_set1_chain (SSL *s, SSL_CTX *ctx, STACK_OF(X509) *chain)
int ssl_cert_add0_chain_cert (SSL *s, SSL_CTX *ctx, X509 *x)
int ssl_cert_add1_chain_cert (SSL *s, SSL_CTX *ctx, X509 *x)
int ssl_cert_select_current (CERT *c, X509 *x)
int ssl_cert_set_current (CERT *c, long op)
void ssl_cert_set_cert_cb (CERT *c, int(*cb)(SSL *ssl, void *arg), void *arg)
int ssl_verify_cert_chain (SSL *s, STACK_OF(X509) *sk)
STACK_OF (X509_NAME)
void SSL_set_client_CA_list (SSL *s, STACK_OF(X509_NAME) *name_list)
void SSL_CTX_set_client_CA_list (SSL_CTX *ctx, STACK_OF(X509_NAME) *name_list)
int SSL_add_client_CA (SSL *ssl, X509 *x)
int SSL_CTX_add_client_CA (SSL_CTX *ctx, X509 *x)
int SSL_add_file_cert_subjects_to_stack (STACK_OF(X509_NAME) *stack, const char *file)
int SSL_add_dir_cert_subjects_to_stack (STACK_OF(X509_NAME) *stack, const char *dir)
int ssl_build_cert_chain (SSL *s, SSL_CTX *ctx, int flags)
int ssl_cert_set_cert_store (CERT *c, X509_STORE *store, int chain, int ref)
int ssl_security (const SSL *s, int op, int bits, int nid, void *other)
int ssl_ctx_security (const SSL_CTX *ctx, int op, int bits, int nid, void *other)
Function Documentation
DEFINE_RUN_ONCE_STATIC()
DEFINE_RUN_ONCE_STATIC (ssl_x509_store_ctx_init)
Definition at line 41 of file ssl_cert.c.
SSL_add_client_CA()
int SSL_add_client_CA (SSL * ssl, X509 * x)
Definition at line 541 of file ssl_cert.c.
SSL_add_dir_cert_subjects_to_stack()
int SSL_add_dir_cert_subjects_to_stack (STACK_OF(X509_NAME) * stack, const char * dir)
Add a directory of certs to a stack.
Parameters
stack the stack to append to.
dir the directory to append from. All files in this directory will be examined as potential certs. Any that are acceptable to SSL_add_dir_cert_subjects_to_stack() that are not already in the stack will be included.
Returns
1 for success, 0 for failure. Note that in the case of failure some certs may have been added to stack.
Definition at line 701 of file ssl_cert.c.
References NULL.
SSL_add_file_cert_subjects_to_stack()
int SSL_add_file_cert_subjects_to_stack (STACK_OF(X509_NAME) * stack, const char * file)
Add a file of certs to a stack.
Parameters
stack the stack to add to.
file the file to add from. All certs in this file that are not already in the stack will be added.
Returns
1 for success, 0 for failure. Note that in the case of failure some certs may have been added to stack.
Definition at line 640 of file ssl_cert.c.
References in, and NULL.
ssl_build_cert_chain()
int ssl_build_cert_chain (SSL * s, SSL_CTX * ctx, int flags)
Definition at line 747 of file ssl_cert.c.
References CERT::cert_flags, CERT::chain_store, ERR_add_error_data(), ERR_clear_error(), ERR_GET_LIB, ERR_GET_REASON, ERR_LIB_X509, ERR_peek_last_error(), ERR_R_MALLOC_FAILURE, ERR_R_X509_LIB, EXFLAG_SS, CERT::key, NULL, SSL_BUILD_CHAIN_FLAG_CHECK, SSL_BUILD_CHAIN_FLAG_CLEAR_ERROR, SSL_BUILD_CHAIN_FLAG_IGNORE_ERROR, SSL_BUILD_CHAIN_FLAG_NO_ROOT, SSL_BUILD_CHAIN_FLAG_UNTRUSTED, SSL_CERT_FLAG_SUITEB_128_LOS, SSL_F_SSL_BUILD_CERT_CHAIN, SSL_R_CERTIFICATE_VERIFY_FAILED, SSL_R_NO_CERTIFICATE_SET, ssl_security_cert(), SSLerr, STACK_OF(), X509_get_extension_flags(), X509_R_CERT_ALREADY_IN_HASH_TABLE, X509_STORE_add_cert(), X509_STORE_CTX_free(), X509_STORE_CTX_get_error(), X509_STORE_CTX_init(), X509_STORE_CTX_new(), X509_STORE_CTX_set_flags(), X509_STORE_free(), X509_STORE_new(), X509_verify_cert(), and X509_verify_cert_error_string().
ssl_cert_add0_chain_cert()
int ssl_cert_add0_chain_cert (SSL * s, SSL_CTX * ctx, X509 * x)
Definition at line 300 of file ssl_cert.c.
References SSL_F_SSL_CERT_ADD0_CHAIN_CERT, ssl_security_cert(), and SSLerr.
Referenced by ssl_cert_add1_chain_cert().
ssl_cert_add1_chain_cert()
int ssl_cert_add1_chain_cert (SSL * s, SSL_CTX * ctx, X509 * x)
Definition at line 318 of file ssl_cert.c.
References ssl_cert_add0_chain_cert(), and X509_up_ref().
ssl_cert_clear_certs()
void ssl_cert_clear_certs (CERT * c)
Definition at line 215 of file ssl_cert.c.
Referenced by SSL_certs_clear().
ssl_cert_dup()
CERT* ssl_cert_dup (CERT * cert)
Definition at line 81 of file ssl_cert.c.
Referenced by SSL_new(), and SSL_set_SSL_CTX().
ssl_cert_free()
void ssl_cert_free (CERT * c)
Definition at line 234 of file ssl_cert.c.
Referenced by SSL_copy_session_id(), and SSL_set_SSL_CTX().
ssl_cert_new()
CERT* ssl_cert_new (void)
Definition at line 57 of file ssl_cert.c.
ssl_cert_select_current()
int ssl_cert_select_current (CERT * c, X509 * x)
Definition at line 326 of file ssl_cert.c.
ssl_cert_set0_chain()
int ssl_cert_set0_chain (SSL * s, SSL_CTX * ctx, STACK_OF(X509) * chain)
Definition at line 267 of file ssl_cert.c.
References SSL_F_SSL_CERT_SET0_CHAIN, ssl_security_cert(), and SSLerr.
Referenced by ssl_cert_set1_chain().
ssl_cert_set1_chain()
int ssl_cert_set1_chain (SSL * s, SSL_CTX * ctx, STACK_OF(X509) * chain)
Definition at line 285 of file ssl_cert.c.
References NULL, ssl_cert_set0_chain(), and STACK_OF().
ssl_cert_set_cert_cb()
void ssl_cert_set_cert_cb (CERT * c, int(*)(SSL *ssl, void *arg) cb, void * arg)
Definition at line 372 of file ssl_cert.c.
ssl_cert_set_cert_store()
int ssl_cert_set_cert_store (CERT * c, X509_STORE * store, int chain, int ref)
Definition at line 866 of file ssl_cert.c.
References CERT::chain_store, CERT::verify_store, X509_STORE_free(), and X509_STORE_up_ref().
ssl_cert_set_current()
int ssl_cert_set_current (CERT * c, long op)
Definition at line 349 of file ssl_cert.c.
SSL_CTX_add_client_CA()
int SSL_CTX_add_client_CA (SSL_CTX * ctx, X509 * x)
Definition at line 546 of file ssl_cert.c.
ssl_ctx_security()
int ssl_ctx_security (const SSL_CTX * ctx, int op, int bits, int nid, void * other)
Definition at line 967 of file ssl_cert.c.
References NULL.
Referenced by ssl3_ctx_ctrl().
SSL_CTX_set_client_CA_list()
void SSL_CTX_set_client_CA_list (SSL_CTX * ctx, STACK_OF(X509_NAME) * name_list)
Definition at line 497 of file ssl_cert.c.
SSL_get_ex_data_X509_STORE_CTX_idx()
int SSL_get_ex_data_X509_STORE_CTX_idx (void)
Definition at line 49 of file ssl_cert.c.
References RUN_ONCE.
Referenced by ssl_verify_cert_chain().
ssl_security()
int ssl_security (const SSL * s, int op, int bits, int nid, void * other)
Definition at line 962 of file ssl_cert.c.
References NULL.
Referenced by ssl_allow_compression(), tls_curve_allowed(), and tls_use_ticket().
SSL_set_client_CA_list()
void SSL_set_client_CA_list (SSL * s, STACK_OF(X509_NAME) * name_list)
Definition at line 492 of file ssl_cert.c.
ssl_verify_cert_chain()
int ssl_verify_cert_chain (SSL * s, STACK_OF(X509) * sk)
Definition at line 378 of file ssl_cert.c.
References DANETLS_ENABLED, ERR_R_MALLOC_FAILURE, ERR_R_X509_LIB, NULL, SSL_F_SSL_VERIFY_CERT_CHAIN, SSL_get_ex_data_X509_STORE_CTX_idx(), SSL_get_security_level(), SSLerr, tls1_suiteb, X509_STORE_CTX_free(), X509_STORE_CTX_get0_param(), X509_STORE_CTX_get_error(), X509_STORE_CTX_init(), X509_STORE_CTX_new(), X509_STORE_CTX_set0_dane(), X509_STORE_CTX_set_default(), X509_STORE_CTX_set_ex_data(), X509_STORE_CTX_set_flags(), X509_STORE_CTX_set_verify_cb(), X509_verify_cert(), X509_VERIFY_PARAM_move_peername(), X509_VERIFY_PARAM_set1(), and X509_VERIFY_PARAM_set_auth_level().
STACK_OF()
STACK_OF (X509_NAME)
Load CA certs from a file into a ::STACK. Note that it is somewhat misnamed; it doesn't really have anything to do with clients (except that a common use for a stack of CAs is to send it to the client). Actually, it doesn't have much to do with CAs, either, since it will load any old cert.
Parameters
file the file containing one or more certs.
Returns
a ::STACK containing the certs.
Definition at line 470 of file ssl_cert.c.
Referenced by ssl_build_cert_chain(), and ssl_cert_set1_chain().