ssl/ssl_ciph.c File Reference
ssl_ciph.c File Reference
#include <stdio.h>
#include <ctype.h>
#include <openssl/objects.h>
#include <openssl/comp.h>
#include <openssl/engine.h>
#include <openssl/crypto.h>
#include "ssl_locl.h"
#include "internal/thread_once.h"
Data Structures
struct ssl_cipher_table
struct CIPHER_ORDER
Macros
#define SSL_ENC_DES_IDX 0
#define SSL_ENC_3DES_IDX 1
#define SSL_ENC_RC4_IDX 2
#define SSL_ENC_RC2_IDX 3
#define SSL_ENC_IDEA_IDX 4
#define SSL_ENC_NULL_IDX 5
#define SSL_ENC_AES128_IDX 6
#define SSL_ENC_AES256_IDX 7
#define SSL_ENC_CAMELLIA128_IDX 8
#define SSL_ENC_CAMELLIA256_IDX 9
#define SSL_ENC_GOST89_IDX 10
#define SSL_ENC_SEED_IDX 11
#define SSL_ENC_AES128GCM_IDX 12
#define SSL_ENC_AES256GCM_IDX 13
#define SSL_ENC_AES128CCM_IDX 14
#define SSL_ENC_AES256CCM_IDX 15
#define SSL_ENC_AES128CCM8_IDX 16
#define SSL_ENC_AES256CCM8_IDX 17
#define SSL_ENC_GOST8912_IDX 18
#define SSL_ENC_CHACHA_IDX 19
#define SSL_ENC_NUM_IDX 20
#define SSL_COMP_NULL_IDX 0
#define SSL_COMP_ZLIB_IDX 1
#define SSL_COMP_NUM_IDX 2
#define SSL_MD_NUM_IDX SSL_MAX_DIGEST
#define ssl_cipher_info_lookup(table, x) ssl_cipher_info_find(table, OSSL_NELEM(table), x)
#define CIPHER_ADD 1
#define CIPHER_KILL 2
#define CIPHER_DEL 3
#define CIPHER_ORD 4
#define CIPHER_SPECIAL 5
#define CIPHER_BUMP 6
#define ITEM_SEP(a) (((a) == ':') || ((a) == ' ') || ((a) == ';') || ((a) == ','))
Functions
void ssl_load_ciphers (void)
DEFINE_RUN_ONCE_STATIC (do_load_builtin_compressions)
int ssl_cipher_get_evp (const SSL_SESSION *s, const EVP_CIPHER **enc, const EVP_MD **md, int *mac_pkey_type, size_t *mac_secret_size, SSL_COMP **comp, int use_etm)
const EVP_MD * ssl_md (int idx)
const EVP_MD * ssl_handshake_md (SSL *s)
const EVP_MD * ssl_prf_md (SSL *s)
STACK_OF (SSL_CIPHER)
char * SSL_CIPHER_description (const SSL_CIPHER *cipher, char *buf, int len)
const char * SSL_CIPHER_get_version (const SSL_CIPHER *c)
const char * SSL_CIPHER_get_name (const SSL_CIPHER *c)
int SSL_CIPHER_get_bits (const SSL_CIPHER *c, int *alg_bits)
uint32_t SSL_CIPHER_get_id (const SSL_CIPHER *c)
SSL_COMP * ssl3_comp_find (STACK_OF(SSL_COMP) *sk, int n)
void ssl_comp_free_compression_methods_int (void)
int SSL_COMP_add_compression_method (int id, COMP_METHOD *cm)
const char * SSL_COMP_get_name (const COMP_METHOD *comp)
const char * SSL_COMP_get0_name (const SSL_COMP *comp)
int SSL_COMP_get_id (const SSL_COMP *comp)
int ssl_cipher_get_cert_index (const SSL_CIPHER *c)
const SSL_CIPHER * ssl_get_cipher_by_char (SSL *ssl, const unsigned char *ptr)
const SSL_CIPHER * SSL_CIPHER_find (SSL *ssl, const unsigned char *ptr)
int SSL_CIPHER_get_cipher_nid (const SSL_CIPHER *c)
int SSL_CIPHER_get_digest_nid (const SSL_CIPHER *c)
int SSL_CIPHER_get_kx_nid (const SSL_CIPHER *c)
int SSL_CIPHER_get_auth_nid (const SSL_CIPHER *c)
int SSL_CIPHER_is_aead (const SSL_CIPHER *c)
int ssl_cipher_get_overhead (const SSL_CIPHER *c, size_t *mac_overhead, size_t *int_overhead, size_t *blocksize, size_t *ext_overhead)
Macro Definition Documentation
CIPHER_ADD
#define CIPHER_ADD 1
Definition at line 204 of file ssl_ciph.c.
CIPHER_BUMP
#define CIPHER_BUMP 6
Definition at line 213 of file ssl_ciph.c.
CIPHER_DEL
#define CIPHER_DEL 3
Definition at line 206 of file ssl_ciph.c.
CIPHER_KILL
#define CIPHER_KILL 2
Definition at line 205 of file ssl_ciph.c.
CIPHER_ORD
#define CIPHER_ORD 4
Definition at line 207 of file ssl_ciph.c.
CIPHER_SPECIAL
#define CIPHER_SPECIAL 5
Definition at line 208 of file ssl_ciph.c.
ITEM_SEP
#define ITEM_SEP (a) (((a) == ':') || ((a) == ' ') || ((a) == ';') || ((a) == ','))
Definition at line 629 of file ssl_ciph.c.
ssl_cipher_info_lookup
#define ssl_cipher_info_lookup (table, x) ssl_cipher_info_find(table, OSSL_NELEM(table), x)
Definition at line 185 of file ssl_ciph.c.
Referenced by SSL_CIPHER_get_auth_nid(), SSL_CIPHER_get_cipher_nid(), SSL_CIPHER_get_digest_nid(), and SSL_CIPHER_get_kx_nid().
SSL_COMP_NULL_IDX
#define SSL_COMP_NULL_IDX 0
Definition at line 109 of file ssl_ciph.c.
SSL_COMP_NUM_IDX
#define SSL_COMP_NUM_IDX 2
Definition at line 111 of file ssl_ciph.c.
SSL_COMP_ZLIB_IDX
#define SSL_COMP_ZLIB_IDX 1
Definition at line 110 of file ssl_ciph.c.
SSL_ENC_3DES_IDX
#define SSL_ENC_3DES_IDX 1
Definition at line 52 of file ssl_ciph.c.
SSL_ENC_AES128_IDX
#define SSL_ENC_AES128_IDX 6
Definition at line 57 of file ssl_ciph.c.
SSL_ENC_AES128CCM8_IDX
#define SSL_ENC_AES128CCM8_IDX 16
Definition at line 67 of file ssl_ciph.c.
SSL_ENC_AES128CCM_IDX
#define SSL_ENC_AES128CCM_IDX 14
Definition at line 65 of file ssl_ciph.c.
SSL_ENC_AES128GCM_IDX
#define SSL_ENC_AES128GCM_IDX 12
Definition at line 63 of file ssl_ciph.c.
SSL_ENC_AES256_IDX
#define SSL_ENC_AES256_IDX 7
Definition at line 58 of file ssl_ciph.c.
SSL_ENC_AES256CCM8_IDX
#define SSL_ENC_AES256CCM8_IDX 17
Definition at line 68 of file ssl_ciph.c.
SSL_ENC_AES256CCM_IDX
#define SSL_ENC_AES256CCM_IDX 15
Definition at line 66 of file ssl_ciph.c.
SSL_ENC_AES256GCM_IDX
#define SSL_ENC_AES256GCM_IDX 13
Definition at line 64 of file ssl_ciph.c.
SSL_ENC_CAMELLIA128_IDX
#define SSL_ENC_CAMELLIA128_IDX 8
Definition at line 59 of file ssl_ciph.c.
SSL_ENC_CAMELLIA256_IDX
#define SSL_ENC_CAMELLIA256_IDX 9
Definition at line 60 of file ssl_ciph.c.
SSL_ENC_CHACHA_IDX
#define SSL_ENC_CHACHA_IDX 19
Definition at line 70 of file ssl_ciph.c.
SSL_ENC_DES_IDX
#define SSL_ENC_DES_IDX 0
Definition at line 51 of file ssl_ciph.c.
SSL_ENC_GOST8912_IDX
#define SSL_ENC_GOST8912_IDX 18
Definition at line 69 of file ssl_ciph.c.
SSL_ENC_GOST89_IDX
#define SSL_ENC_GOST89_IDX 10
Definition at line 61 of file ssl_ciph.c.
SSL_ENC_IDEA_IDX
#define SSL_ENC_IDEA_IDX 4
Definition at line 55 of file ssl_ciph.c.
SSL_ENC_NULL_IDX
#define SSL_ENC_NULL_IDX 5
Definition at line 56 of file ssl_ciph.c.
SSL_ENC_NUM_IDX
#define SSL_ENC_NUM_IDX 20
Definition at line 71 of file ssl_ciph.c.
SSL_ENC_RC2_IDX
#define SSL_ENC_RC2_IDX 3
Definition at line 54 of file ssl_ciph.c.
SSL_ENC_RC4_IDX
#define SSL_ENC_RC4_IDX 2
Definition at line 53 of file ssl_ciph.c.
SSL_ENC_SEED_IDX
#define SSL_ENC_SEED_IDX 11
Definition at line 62 of file ssl_ciph.c.
SSL_MD_NUM_IDX
#define SSL_MD_NUM_IDX SSL_MAX_DIGEST
Function Documentation
DEFINE_RUN_ONCE_STATIC()
DEFINE_RUN_ONCE_STATIC (do_load_builtin_compressions)
Definition at line 478 of file ssl_ciph.c.
References COMP_zlib(), CRYPTO_MEM_CHECK_DISABLE, CRYPTO_mem_ctrl(), and NULL.
ssl3_comp_find()
SSL_COMP* ssl3_comp_find (STACK_OF(SSL_COMP) * sk, int n)
Definition at line 1763 of file ssl_ciph.c.
References NULL, SSL_COMP_add_compression_method(), and STACK_OF().
SSL_CIPHER_description()
char* SSL_CIPHER_description (const SSL_CIPHER * cipher, char * buf, int len)
Definition at line 1531 of file ssl_ciph.c.
SSL_CIPHER_find()
const SSL_CIPHER* SSL_CIPHER_find (SSL * ssl, const unsigned char * ptr)
Definition at line 1930 of file ssl_ciph.c.
SSL_CIPHER_get_auth_nid()
int SSL_CIPHER_get_auth_nid (const SSL_CIPHER * c)
Definition at line 1964 of file ssl_ciph.c.
References ssl_cipher_table::nid, NID_undef, and ssl_cipher_info_lookup.
SSL_CIPHER_get_bits()
int SSL_CIPHER_get_bits (const SSL_CIPHER * c, int * alg_bits)
Definition at line 1746 of file ssl_ciph.c.
ssl_cipher_get_cert_index()
int ssl_cipher_get_cert_index (const SSL_CIPHER * c)
Definition at line 1901 of file ssl_ciph.c.
References SSL_aDSS, SSL_aECDSA, SSL_aGOST01, SSL_aGOST12, SSL_aRSA, SSL_PKEY_DSA_SIGN, SSL_PKEY_ECC, SSL_PKEY_GOST01, SSL_PKEY_GOST_EC, and SSL_PKEY_RSA.
SSL_CIPHER_get_cipher_nid()
int SSL_CIPHER_get_cipher_nid (const SSL_CIPHER * c)
Definition at line 1935 of file ssl_ciph.c.
References ssl_cipher_table::nid, NID_undef, NULL, and ssl_cipher_info_lookup.
SSL_CIPHER_get_digest_nid()
int SSL_CIPHER_get_digest_nid (const SSL_CIPHER * c)
Definition at line 1946 of file ssl_ciph.c.
References ssl_cipher_table::nid, NID_undef, and ssl_cipher_info_lookup.
ssl_cipher_get_evp()
int ssl_cipher_get_evp (const SSL_SESSION * s, const EVP_CIPHER ** enc, const EVP_MD ** md, int * mac_pkey_type, size_t * mac_secret_size, SSL_COMP ** comp, int use_etm)
Definition at line 506 of file ssl_ciph.c.
Referenced by SSL_SESSION_print().
SSL_CIPHER_get_id()
uint32_t SSL_CIPHER_get_id (const SSL_CIPHER * c)
Definition at line 1758 of file ssl_ciph.c.
SSL_CIPHER_get_kx_nid()
int SSL_CIPHER_get_kx_nid (const SSL_CIPHER * c)
Definition at line 1955 of file ssl_ciph.c.
References ssl_cipher_table::nid, NID_undef, and ssl_cipher_info_lookup.
SSL_CIPHER_get_name()
const char* SSL_CIPHER_get_name (const SSL_CIPHER * c)
Definition at line 1738 of file ssl_ciph.c.
References NULL.
ssl_cipher_get_overhead()
int ssl_cipher_get_overhead (const SSL_CIPHER * c, size_t * mac_overhead, size_t * int_overhead, size_t * blocksize, size_t * ext_overhead)
Definition at line 1978 of file ssl_ciph.c.
References in.
Referenced by DTLS_get_data_mtu(), and main().
SSL_CIPHER_get_version()
const char* SSL_CIPHER_get_version (const SSL_CIPHER * c)
Definition at line 1723 of file ssl_ciph.c.
References NULL, ssl_protocol_to_string(), and TLS1_VERSION.
SSL_CIPHER_is_aead()
int SSL_CIPHER_is_aead (const SSL_CIPHER * c)
Definition at line 1973 of file ssl_ciph.c.
References SSL_AEAD.
SSL_COMP_add_compression_method()
int SSL_COMP_add_compression_method (int id, COMP_METHOD * cm)
Definition at line 1823 of file ssl_ciph.c.
References COMP_get_type(), CRYPTO_MEM_CHECK_DISABLE, CRYPTO_MEM_CHECK_ENABLE, CRYPTO_mem_ctrl(), ERR_R_MALLOC_FAILURE, NID_undef, NULL, OPENSSL_malloc, SSL_F_SSL_COMP_ADD_COMPRESSION_METHOD, SSL_R_COMPRESSION_ID_NOT_WITHIN_PRIVATE_RANGE, and SSLerr.
Referenced by ssl3_comp_find().
ssl_comp_free_compression_methods_int()
void ssl_comp_free_compression_methods_int (void)
Definition at line 1816 of file ssl_ciph.c.
References NULL, and STACK_OF().
SSL_COMP_get0_name()
const char* SSL_COMP_get0_name (const SSL_COMP * comp)
Definition at line 1882 of file ssl_ciph.c.
References NULL.
SSL_COMP_get_id()
int SSL_COMP_get_id (const SSL_COMP * comp)
Definition at line 1891 of file ssl_ciph.c.
SSL_COMP_get_name()
const char* SSL_COMP_get_name (const COMP_METHOD * comp)
Definition at line 1873 of file ssl_ciph.c.
References COMP_get_name(), and NULL.
ssl_get_cipher_by_char()
const SSL_CIPHER* ssl_get_cipher_by_char (SSL * ssl, const unsigned char * ptr)
Definition at line 1921 of file ssl_ciph.c.
References NULL.
ssl_handshake_md()
const EVP_MD* ssl_handshake_md (SSL * s)
Definition at line 619 of file ssl_ciph.c.
Referenced by tls13_derive_key(), and tls13_generate_handshake_secret().
ssl_load_ciphers()
void ssl_load_ciphers (void)
Definition at line 377 of file ssl_ciph.c.
References t.
Referenced by DEFINE_RUN_ONCE_STATIC().
ssl_md()
const EVP_MD* ssl_md (int idx)
Definition at line 611 of file ssl_ciph.c.
Referenced by ssl_handshake_md(), ssl_prf_md(), and ssl_set_default_md().
ssl_prf_md()
const EVP_MD* ssl_prf_md (SSL * s)
Definition at line 624 of file ssl_ciph.c.
References ssl_get_algorithm2(), ssl_md(), and TLS1_PRF_DGST_SHIFT.
STACK_OF()
STACK_OF (SSL_CIPHER)
Definition at line 1297 of file ssl_ciph.c.
Referenced by ssl3_comp_find(), and ssl_comp_free_compression_methods_int().