include/openssl/ssl.h File Reference
ssl.h File Reference
#include <openssl/e_os2.h>
#include <openssl/opensslconf.h>
#include <openssl/comp.h>
#include <openssl/bio.h>
#include <openssl/x509.h>
#include <openssl/crypto.h>
#include <openssl/lhash.h>
#include <openssl/buffer.h>
#include <openssl/pem.h>
#include <openssl/hmac.h>
#include <openssl/async.h>
#include <openssl/safestack.h>
#include <openssl/symhacks.h>
#include <openssl/ct.h>
#include <openssl/ssl2.h>
#include <openssl/ssl3.h>
#include <openssl/tls1.h>
#include <openssl/dtls1.h>
#include <openssl/srtp.h>
Data Structures
struct SRTP_PROTECTION_PROFILE
Macros
#define SSL_SESSION_ASN1_VERSION 0x0001
#define SSL_MAX_SSL_SESSION_ID_LENGTH 32
#define SSL_MAX_SID_CTX_LENGTH 32
#define SSL_MIN_RSA_MODULUS_LENGTH_IN_BYTES (512/8)
#define SSL_MAX_KEY_ARG_LENGTH 8
#define SSL_MAX_MASTER_KEY_LENGTH 48
#define TLS13_MAX_RESUMPTION_MASTER_LENGTH 64
#define SSL_MAX_PIPELINES 32
#define SSL_TXT_LOW "LOW"
#define SSL_TXT_MEDIUM "MEDIUM"
#define SSL_TXT_HIGH "HIGH"
#define SSL_TXT_FIPS "FIPS"
#define SSL_TXT_aNULL "aNULL"
#define SSL_TXT_eNULL "eNULL"
#define SSL_TXT_NULL "NULL"
#define SSL_TXT_kRSA "kRSA"
#define SSL_TXT_kDHr "kDHr"
#define SSL_TXT_kDHd "kDHd"
#define SSL_TXT_kDH "kDH"
#define SSL_TXT_kEDH "kEDH"/* alias for kDHE */
#define SSL_TXT_kDHE "kDHE"
#define SSL_TXT_kECDHr "kECDHr"
#define SSL_TXT_kECDHe "kECDHe"
#define SSL_TXT_kECDH "kECDH"
#define SSL_TXT_kEECDH "kEECDH"/* alias for kECDHE */
#define SSL_TXT_kECDHE "kECDHE"
#define SSL_TXT_kPSK "kPSK"
#define SSL_TXT_kRSAPSK "kRSAPSK"
#define SSL_TXT_kECDHEPSK "kECDHEPSK"
#define SSL_TXT_kDHEPSK "kDHEPSK"
#define SSL_TXT_kGOST "kGOST"
#define SSL_TXT_kSRP "kSRP"
#define SSL_TXT_aRSA "aRSA"
#define SSL_TXT_aDSS "aDSS"
#define SSL_TXT_aDH "aDH"
#define SSL_TXT_aECDH "aECDH"
#define SSL_TXT_aECDSA "aECDSA"
#define SSL_TXT_aPSK "aPSK"
#define SSL_TXT_aGOST94 "aGOST94"
#define SSL_TXT_aGOST01 "aGOST01"
#define SSL_TXT_aGOST12 "aGOST12"
#define SSL_TXT_aGOST "aGOST"
#define SSL_TXT_aSRP "aSRP"
#define SSL_TXT_DSS "DSS"
#define SSL_TXT_DH "DH"
#define SSL_TXT_DHE "DHE"/* same as "kDHE:-ADH" */
#define SSL_TXT_EDH "EDH"/* alias for DHE */
#define SSL_TXT_ADH "ADH"
#define SSL_TXT_RSA "RSA"
#define SSL_TXT_ECDH "ECDH"
#define SSL_TXT_EECDH "EECDH"/* alias for ECDHE" */
#define SSL_TXT_ECDHE "ECDHE"/* same as "kECDHE:-AECDH" */
#define SSL_TXT_AECDH "AECDH"
#define SSL_TXT_ECDSA "ECDSA"
#define SSL_TXT_PSK "PSK"
#define SSL_TXT_SRP "SRP"
#define SSL_TXT_DES "DES"
#define SSL_TXT_3DES "3DES"
#define SSL_TXT_RC4 "RC4"
#define SSL_TXT_RC2 "RC2"
#define SSL_TXT_IDEA "IDEA"
#define SSL_TXT_SEED "SEED"
#define SSL_TXT_AES128 "AES128"
#define SSL_TXT_AES256 "AES256"
#define SSL_TXT_AES "AES"
#define SSL_TXT_AES_GCM "AESGCM"
#define SSL_TXT_AES_CCM "AESCCM"
#define SSL_TXT_AES_CCM_8 "AESCCM8"
#define SSL_TXT_CAMELLIA128 "CAMELLIA128"
#define SSL_TXT_CAMELLIA256 "CAMELLIA256"
#define SSL_TXT_CAMELLIA "CAMELLIA"
#define SSL_TXT_CHACHA20 "CHACHA20"
#define SSL_TXT_GOST "GOST89"
#define SSL_TXT_MD5 "MD5"
#define SSL_TXT_SHA1 "SHA1"
#define SSL_TXT_SHA "SHA"/* same as "SHA1" */
#define SSL_TXT_GOST94 "GOST94"
#define SSL_TXT_GOST89MAC "GOST89MAC"
#define SSL_TXT_GOST12 "GOST12"
#define SSL_TXT_GOST89MAC12 "GOST89MAC12"
#define SSL_TXT_SHA256 "SHA256"
#define SSL_TXT_SHA384 "SHA384"
#define SSL_TXT_SSLV3 "SSLv3"
#define SSL_TXT_TLSV1 "TLSv1"
#define SSL_TXT_TLSV1_1 "TLSv1.1"
#define SSL_TXT_TLSV1_2 "TLSv1.2"
#define SSL_TXT_ALL "ALL"
#define SSL_TXT_CMPALL "COMPLEMENTOFALL"
#define SSL_TXT_CMPDEF "COMPLEMENTOFDEFAULT"
#define SSL_DEFAULT_CIPHER_LIST "ALL:!COMPLEMENTOFDEFAULT:!eNULL"
#define SSL_SENT_SHUTDOWN 1
#define SSL_RECEIVED_SHUTDOWN 2
#define SSL_FILETYPE_ASN1 X509_FILETYPE_ASN1
#define SSL_FILETYPE_PEM X509_FILETYPE_PEM
#define SSL_OP_LEGACY_SERVER_CONNECT 0x00000004U
#define SSL_OP_NETSCAPE_REUSE_CIPHER_CHANGE_BUG 0x0U
#define SSL_OP_TLSEXT_PADDING 0x00000010U
#define SSL_OP_MICROSOFT_BIG_SSLV3_BUFFER 0x0U
#define SSL_OP_SAFARI_ECDHE_ECDSA_BUG 0x00000040U
#define SSL_OP_SSLEAY_080_CLIENT_DH_BUG 0x0
#define SSL_OP_TLS_D5_BUG 0x0U
#define SSL_OP_TLS_BLOCK_PADDING_BUG 0x0U
#define SSL_OP_MSIE_SSLV2_RSA_PADDING 0x0
#define SSL_OP_SSLREF2_REUSE_CERT_TYPE_BUG 0x0
#define SSL_OP_MICROSOFT_SESS_ID_BUG 0x0
#define SSL_OP_NETSCAPE_CHALLENGE_BUG 0x0
#define SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS 0x00000800U
#define SSL_OP_ALL 0x80000BFFU
#define SSL_OP_NO_QUERY_MTU 0x00001000U
#define SSL_OP_COOKIE_EXCHANGE 0x00002000U
#define SSL_OP_NO_TICKET 0x00004000U
#define SSL_OP_CISCO_ANYCONNECT 0x00008000U
#define SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION 0x00010000U
#define SSL_OP_NO_COMPRESSION 0x00020000U
#define SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION 0x00040000U
#define SSL_OP_NO_ENCRYPT_THEN_MAC 0x00080000U
#define SSL_OP_SINGLE_ECDH_USE 0x0
#define SSL_OP_SINGLE_DH_USE 0x0
#define SSL_OP_EPHEMERAL_RSA 0x0
#define SSL_OP_CIPHER_SERVER_PREFERENCE 0x00400000U
#define SSL_OP_TLS_ROLLBACK_BUG 0x00800000U
#define SSL_OP_NO_SSLv2 0x00000000U
#define SSL_OP_NO_SSLv3 0x02000000U
#define SSL_OP_NO_TLSv1 0x04000000U
#define SSL_OP_NO_TLSv1_2 0x08000000U
#define SSL_OP_NO_TLSv1_1 0x10000000U
#define SSL_OP_NO_TLSv1_3 0x20000000U
#define SSL_OP_NO_DTLSv1 0x04000000U
#define SSL_OP_NO_DTLSv1_2 0x08000000U
#define SSL_OP_NO_SSL_MASK
#define SSL_OP_NO_DTLS_MASK (SSL_OP_NO_DTLSv1|SSL_OP_NO_DTLSv1_2)
#define SSL_OP_PKCS1_CHECK_1 0x0
#define SSL_OP_PKCS1_CHECK_2 0x0
#define SSL_OP_NETSCAPE_CA_DN_BUG 0x0
#define SSL_OP_NETSCAPE_DEMO_CIPHER_CHANGE_BUG 0x0U
#define SSL_OP_CRYPTOPRO_TLSEXT_BUG 0x80000000U
#define SSL_MODE_ENABLE_PARTIAL_WRITE 0x00000001U
#define SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER 0x00000002U
#define SSL_MODE_AUTO_RETRY 0x00000004U
#define SSL_MODE_NO_AUTO_CHAIN 0x00000008U
#define SSL_MODE_RELEASE_BUFFERS 0x00000010U
#define SSL_MODE_SEND_CLIENTHELLO_TIME 0x00000020U
#define SSL_MODE_SEND_SERVERHELLO_TIME 0x00000040U
#define SSL_MODE_SEND_FALLBACK_SCSV 0x00000080U
#define SSL_MODE_ASYNC 0x00000100U
#define SSL_CERT_FLAG_TLS_STRICT 0x00000001U
#define SSL_CERT_FLAG_SUITEB_128_LOS_ONLY 0x10000
#define SSL_CERT_FLAG_SUITEB_192_LOS 0x20000
#define SSL_CERT_FLAG_SUITEB_128_LOS 0x30000
#define SSL_CERT_FLAG_BROKEN_PROTOCOL 0x10000000
#define SSL_BUILD_CHAIN_FLAG_UNTRUSTED 0x1
#define SSL_BUILD_CHAIN_FLAG_NO_ROOT 0x2
#define SSL_BUILD_CHAIN_FLAG_CHECK 0x4
#define SSL_BUILD_CHAIN_FLAG_IGNORE_ERROR 0x8
#define SSL_BUILD_CHAIN_FLAG_CLEAR_ERROR 0x10
#define CERT_PKEY_VALID 0x1
#define CERT_PKEY_SIGN 0x2
#define CERT_PKEY_EE_SIGNATURE 0x10
#define CERT_PKEY_CA_SIGNATURE 0x20
#define CERT_PKEY_EE_PARAM 0x40
#define CERT_PKEY_CA_PARAM 0x80
#define CERT_PKEY_EXPLICIT_SIGN 0x100
#define CERT_PKEY_ISSUER_NAME 0x200
#define CERT_PKEY_CERT_TYPE 0x400
#define CERT_PKEY_SUITEB 0x800
#define SSL_CONF_FLAG_CMDLINE 0x1
#define SSL_CONF_FLAG_FILE 0x2
#define SSL_CONF_FLAG_CLIENT 0x4
#define SSL_CONF_FLAG_SERVER 0x8
#define SSL_CONF_FLAG_SHOW_ERRORS 0x10
#define SSL_CONF_FLAG_CERTIFICATE 0x20
#define SSL_CONF_FLAG_REQUIRE_PRIVATE 0x40
#define SSL_CONF_TYPE_UNKNOWN 0x0
#define SSL_CONF_TYPE_STRING 0x1
#define SSL_CONF_TYPE_FILE 0x2
#define SSL_CONF_TYPE_DIR 0x3
#define SSL_CONF_TYPE_NONE 0x4
#define SSL_CTX_set_mode(ctx, op) SSL_CTX_ctrl((ctx),SSL_CTRL_MODE,(op),NULL)
#define SSL_CTX_clear_mode(ctx, op) SSL_CTX_ctrl((ctx),SSL_CTRL_CLEAR_MODE,(op),NULL)
#define SSL_CTX_get_mode(ctx) SSL_CTX_ctrl((ctx),SSL_CTRL_MODE,0,NULL)
#define SSL_clear_mode(ssl, op) SSL_ctrl((ssl),SSL_CTRL_CLEAR_MODE,(op),NULL)
#define SSL_set_mode(ssl, op) SSL_ctrl((ssl),SSL_CTRL_MODE,(op),NULL)
#define SSL_get_mode(ssl) SSL_ctrl((ssl),SSL_CTRL_MODE,0,NULL)
#define SSL_set_mtu(ssl, mtu) SSL_ctrl((ssl),SSL_CTRL_SET_MTU,(mtu),NULL)
#define DTLS_set_link_mtu(ssl, mtu) SSL_ctrl((ssl),DTLS_CTRL_SET_LINK_MTU,(mtu),NULL)
#define DTLS_get_link_min_mtu(ssl) SSL_ctrl((ssl),DTLS_CTRL_GET_LINK_MIN_MTU,0,NULL)
#define SSL_get_secure_renegotiation_support(ssl) SSL_ctrl((ssl), SSL_CTRL_GET_RI_SUPPORT, 0, NULL)
#define SSL_heartbeat(ssl) SSL_ctrl((ssl),SSL_CTRL_DTLS_EXT_SEND_HEARTBEAT,0,NULL)
#define SSL_CTX_set_cert_flags(ctx, op) SSL_CTX_ctrl((ctx),SSL_CTRL_CERT_FLAGS,(op),NULL)
#define SSL_set_cert_flags(s, op) SSL_ctrl((s),SSL_CTRL_CERT_FLAGS,(op),NULL)
#define SSL_CTX_clear_cert_flags(ctx, op) SSL_CTX_ctrl((ctx),SSL_CTRL_CLEAR_CERT_FLAGS,(op),NULL)
#define SSL_clear_cert_flags(s, op) SSL_ctrl((s),SSL_CTRL_CLEAR_CERT_FLAGS,(op),NULL)
#define SSL_CTX_set_msg_callback_arg(ctx, arg) SSL_CTX_ctrl((ctx), SSL_CTRL_SET_MSG_CALLBACK_ARG, 0, (arg))
#define SSL_set_msg_callback_arg(ssl, arg) SSL_ctrl((ssl), SSL_CTRL_SET_MSG_CALLBACK_ARG, 0, (arg))
#define SSL_get_extms_support(s) SSL_ctrl((s),SSL_CTRL_GET_EXTMS_SUPPORT,0,NULL)
#define SSL_MAX_CERT_LIST_DEFAULT 1024*100
#define SSL_SESSION_CACHE_MAX_SIZE_DEFAULT (1024*20)
#define SSL_SESS_CACHE_OFF 0x0000
#define SSL_SESS_CACHE_CLIENT 0x0001
#define SSL_SESS_CACHE_SERVER 0x0002
#define SSL_SESS_CACHE_BOTH (SSL_SESS_CACHE_CLIENT|SSL_SESS_CACHE_SERVER)
#define SSL_SESS_CACHE_NO_AUTO_CLEAR 0x0080
#define SSL_SESS_CACHE_NO_INTERNAL_LOOKUP 0x0100
#define SSL_SESS_CACHE_NO_INTERNAL_STORE 0x0200
#define SSL_SESS_CACHE_NO_INTERNAL (SSL_SESS_CACHE_NO_INTERNAL_LOOKUP|SSL_SESS_CACHE_NO_INTERNAL_STORE)
#define SSL_CTX_sess_number(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_NUMBER,0,NULL)
#define SSL_CTX_sess_connect(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_CONNECT,0,NULL)
#define SSL_CTX_sess_connect_good(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_CONNECT_GOOD,0,NULL)
#define SSL_CTX_sess_connect_renegotiate(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_CONNECT_RENEGOTIATE,0,NULL)
#define SSL_CTX_sess_accept(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_ACCEPT,0,NULL)
#define SSL_CTX_sess_accept_renegotiate(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_ACCEPT_RENEGOTIATE,0,NULL)
#define SSL_CTX_sess_accept_good(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_ACCEPT_GOOD,0,NULL)
#define SSL_CTX_sess_hits(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_HIT,0,NULL)
#define SSL_CTX_sess_cb_hits(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_CB_HIT,0,NULL)
#define SSL_CTX_sess_misses(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_MISSES,0,NULL)
#define SSL_CTX_sess_timeouts(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_TIMEOUTS,0,NULL)
#define SSL_CTX_sess_cache_full(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_CACHE_FULL,0,NULL)
#define SSL_CTX_set_npn_advertised_cb SSL_CTX_set_next_protos_advertised_cb
#define SSL_CTX_set_npn_select_cb SSL_CTX_set_next_proto_select_cb
#define SSL_get0_npn_negotiated SSL_get0_next_proto_negotiated
#define OPENSSL_NPN_UNSUPPORTED 0
#define OPENSSL_NPN_NEGOTIATED 1
#define OPENSSL_NPN_NO_OVERLAP 2
#define PSK_MAX_IDENTITY_LEN 128
#define PSK_MAX_PSK_LEN 256
#define SSL_NOTHING 1
#define SSL_WRITING 2
#define SSL_READING 3
#define SSL_X509_LOOKUP 4
#define SSL_ASYNC_PAUSED 5
#define SSL_ASYNC_NO_JOBS 6
#define SSL_want_nothing(s) (SSL_want(s) == SSL_NOTHING)
#define SSL_want_read(s) (SSL_want(s) == SSL_READING)
#define SSL_want_write(s) (SSL_want(s) == SSL_WRITING)
#define SSL_want_x509_lookup(s) (SSL_want(s) == SSL_X509_LOOKUP)
#define SSL_want_async(s) (SSL_want(s) == SSL_ASYNC_PAUSED)
#define SSL_want_async_job(s) (SSL_want(s) == SSL_ASYNC_NO_JOBS)
#define SSL_MAC_FLAG_READ_MAC_STREAM 1
#define SSL_MAC_FLAG_WRITE_MAC_STREAM 2
#define SSL_set_app_data(s, arg) (SSL_set_ex_data(s,0,(char *)arg))
#define SSL_get_app_data(s) (SSL_get_ex_data(s,0))
#define SSL_SESSION_set_app_data(s, a) (SSL_SESSION_set_ex_data(s,0,(char *)a))
#define SSL_SESSION_get_app_data(s) (SSL_SESSION_get_ex_data(s,0))
#define SSL_CTX_get_app_data(ctx) (SSL_CTX_get_ex_data(ctx,0))
#define SSL_CTX_set_app_data(ctx, arg) (SSL_CTX_set_ex_data(ctx,0,(char *)arg))
#define SSL_KEY_UPDATE_NONE -1
#define SSL_KEY_UPDATE_NOT_REQUESTED 0
#define SSL_KEY_UPDATE_REQUESTED 1
#define SSL_ST_CONNECT 0x1000
#define SSL_ST_ACCEPT 0x2000
#define SSL_ST_MASK 0x0FFF
#define SSL_CB_LOOP 0x01
#define SSL_CB_EXIT 0x02
#define SSL_CB_READ 0x04
#define SSL_CB_WRITE 0x08
#define SSL_CB_ALERT 0x4000/* used in callback */
#define SSL_CB_READ_ALERT (SSL_CB_ALERT|SSL_CB_READ)
#define SSL_CB_WRITE_ALERT (SSL_CB_ALERT|SSL_CB_WRITE)
#define SSL_CB_ACCEPT_LOOP (SSL_ST_ACCEPT|SSL_CB_LOOP)
#define SSL_CB_ACCEPT_EXIT (SSL_ST_ACCEPT|SSL_CB_EXIT)
#define SSL_CB_CONNECT_LOOP (SSL_ST_CONNECT|SSL_CB_LOOP)
#define SSL_CB_CONNECT_EXIT (SSL_ST_CONNECT|SSL_CB_EXIT)
#define SSL_CB_HANDSHAKE_START 0x10
#define SSL_CB_HANDSHAKE_DONE 0x20
#define SSL_in_connect_init(a) (SSL_in_init(a) && !SSL_is_server(a))
#define SSL_in_accept_init(a) (SSL_in_init(a) && SSL_is_server(a))
#define SSL_ST_READ_HEADER 0xF0
#define SSL_ST_READ_BODY 0xF1
#define SSL_ST_READ_DONE 0xF2
#define SSL_VERIFY_NONE 0x00
#define SSL_VERIFY_PEER 0x01
#define SSL_VERIFY_FAIL_IF_NO_PEER_CERT 0x02
#define SSL_VERIFY_CLIENT_ONCE 0x04
#define OpenSSL_add_ssl_algorithms() SSL_library_init()
#define SSLeay_add_ssl_algorithms() SSL_library_init()
#define SSL_get_cipher(s) SSL_CIPHER_get_name(SSL_get_current_cipher(s))
#define SSL_get_cipher_bits(s, np) SSL_CIPHER_get_bits(SSL_get_current_cipher(s),np)
#define SSL_get_cipher_version(s) SSL_CIPHER_get_version(SSL_get_current_cipher(s))
#define SSL_get_cipher_name(s) SSL_CIPHER_get_name(SSL_get_current_cipher(s))
#define SSL_get_time(a) SSL_SESSION_get_time(a)
#define SSL_set_time(a, b) SSL_SESSION_set_time((a),(b))
#define SSL_get_timeout(a) SSL_SESSION_get_timeout(a)
#define SSL_set_timeout(a, b) SSL_SESSION_set_timeout((a),(b))
#define d2i_SSL_SESSION_bio(bp, s_id) ASN1_d2i_bio_of(SSL_SESSION,SSL_SESSION_new,d2i_SSL_SESSION,bp,s_id)
#define i2d_SSL_SESSION_bio(bp, s_id) ASN1_i2d_bio_of(SSL_SESSION,i2d_SSL_SESSION,bp,s_id)
#define SSL_AD_REASON_OFFSET
#define SSL_AD_CLOSE_NOTIFY SSL3_AD_CLOSE_NOTIFY
#define SSL_AD_UNEXPECTED_MESSAGE SSL3_AD_UNEXPECTED_MESSAGE
#define SSL_AD_BAD_RECORD_MAC SSL3_AD_BAD_RECORD_MAC
#define SSL_AD_DECRYPTION_FAILED TLS1_AD_DECRYPTION_FAILED
#define SSL_AD_RECORD_OVERFLOW TLS1_AD_RECORD_OVERFLOW
#define SSL_AD_DECOMPRESSION_FAILURE SSL3_AD_DECOMPRESSION_FAILURE
#define SSL_AD_HANDSHAKE_FAILURE SSL3_AD_HANDSHAKE_FAILURE
#define SSL_AD_NO_CERTIFICATE SSL3_AD_NO_CERTIFICATE
#define SSL_AD_BAD_CERTIFICATE SSL3_AD_BAD_CERTIFICATE
#define SSL_AD_UNSUPPORTED_CERTIFICATE SSL3_AD_UNSUPPORTED_CERTIFICATE
#define SSL_AD_CERTIFICATE_REVOKED SSL3_AD_CERTIFICATE_REVOKED
#define SSL_AD_CERTIFICATE_EXPIRED SSL3_AD_CERTIFICATE_EXPIRED
#define SSL_AD_CERTIFICATE_UNKNOWN SSL3_AD_CERTIFICATE_UNKNOWN
#define SSL_AD_ILLEGAL_PARAMETER SSL3_AD_ILLEGAL_PARAMETER
#define SSL_AD_UNKNOWN_CA TLS1_AD_UNKNOWN_CA
#define SSL_AD_ACCESS_DENIED TLS1_AD_ACCESS_DENIED
#define SSL_AD_DECODE_ERROR TLS1_AD_DECODE_ERROR
#define SSL_AD_DECRYPT_ERROR TLS1_AD_DECRYPT_ERROR
#define SSL_AD_EXPORT_RESTRICTION TLS1_AD_EXPORT_RESTRICTION
#define SSL_AD_PROTOCOL_VERSION TLS1_AD_PROTOCOL_VERSION
#define SSL_AD_INSUFFICIENT_SECURITY TLS1_AD_INSUFFICIENT_SECURITY
#define SSL_AD_INTERNAL_ERROR TLS1_AD_INTERNAL_ERROR
#define SSL_AD_USER_CANCELLED TLS1_AD_USER_CANCELLED
#define SSL_AD_NO_RENEGOTIATION TLS1_AD_NO_RENEGOTIATION
#define SSL_AD_MISSING_EXTENSION TLS13_AD_MISSING_EXTENSION
#define SSL_AD_UNSUPPORTED_EXTENSION TLS1_AD_UNSUPPORTED_EXTENSION
#define SSL_AD_CERTIFICATE_UNOBTAINABLE TLS1_AD_CERTIFICATE_UNOBTAINABLE
#define SSL_AD_UNRECOGNIZED_NAME TLS1_AD_UNRECOGNIZED_NAME
#define SSL_AD_BAD_CERTIFICATE_STATUS_RESPONSE TLS1_AD_BAD_CERTIFICATE_STATUS_RESPONSE
#define SSL_AD_BAD_CERTIFICATE_HASH_VALUE TLS1_AD_BAD_CERTIFICATE_HASH_VALUE
#define SSL_AD_UNKNOWN_PSK_IDENTITY TLS1_AD_UNKNOWN_PSK_IDENTITY
#define SSL_AD_INAPPROPRIATE_FALLBACK TLS1_AD_INAPPROPRIATE_FALLBACK
#define SSL_AD_NO_APPLICATION_PROTOCOL TLS1_AD_NO_APPLICATION_PROTOCOL
#define SSL_ERROR_NONE 0
#define SSL_ERROR_SSL 1
#define SSL_ERROR_WANT_READ 2
#define SSL_ERROR_WANT_WRITE 3
#define SSL_ERROR_WANT_X509_LOOKUP 4
#define SSL_ERROR_SYSCALL
#define SSL_ERROR_ZERO_RETURN 6
#define SSL_ERROR_WANT_CONNECT 7
#define SSL_ERROR_WANT_ACCEPT 8
#define SSL_ERROR_WANT_ASYNC 9
#define SSL_ERROR_WANT_ASYNC_JOB 10
#define SSL_CTRL_SET_TMP_DH 3
#define SSL_CTRL_SET_TMP_ECDH 4
#define SSL_CTRL_SET_TMP_DH_CB 6
#define SSL_CTRL_GET_CLIENT_CERT_REQUEST 9
#define SSL_CTRL_GET_NUM_RENEGOTIATIONS 10
#define SSL_CTRL_CLEAR_NUM_RENEGOTIATIONS 11
#define SSL_CTRL_GET_TOTAL_RENEGOTIATIONS 12
#define SSL_CTRL_GET_FLAGS 13
#define SSL_CTRL_EXTRA_CHAIN_CERT 14
#define SSL_CTRL_SET_MSG_CALLBACK 15
#define SSL_CTRL_SET_MSG_CALLBACK_ARG 16
#define SSL_CTRL_SET_MTU 17
#define SSL_CTRL_SESS_NUMBER 20
#define SSL_CTRL_SESS_CONNECT 21
#define SSL_CTRL_SESS_CONNECT_GOOD 22
#define SSL_CTRL_SESS_CONNECT_RENEGOTIATE 23
#define SSL_CTRL_SESS_ACCEPT 24
#define SSL_CTRL_SESS_ACCEPT_GOOD 25
#define SSL_CTRL_SESS_ACCEPT_RENEGOTIATE 26
#define SSL_CTRL_SESS_HIT 27
#define SSL_CTRL_SESS_CB_HIT 28
#define SSL_CTRL_SESS_MISSES 29
#define SSL_CTRL_SESS_TIMEOUTS 30
#define SSL_CTRL_SESS_CACHE_FULL 31
#define SSL_CTRL_MODE 33
#define SSL_CTRL_GET_READ_AHEAD 40
#define SSL_CTRL_SET_READ_AHEAD 41
#define SSL_CTRL_SET_SESS_CACHE_SIZE 42
#define SSL_CTRL_GET_SESS_CACHE_SIZE 43
#define SSL_CTRL_SET_SESS_CACHE_MODE 44
#define SSL_CTRL_GET_SESS_CACHE_MODE 45
#define SSL_CTRL_GET_MAX_CERT_LIST 50
#define SSL_CTRL_SET_MAX_CERT_LIST 51
#define SSL_CTRL_SET_MAX_SEND_FRAGMENT 52
#define SSL_CTRL_SET_TLSEXT_SERVERNAME_CB 53
#define SSL_CTRL_SET_TLSEXT_SERVERNAME_ARG 54
#define SSL_CTRL_SET_TLSEXT_HOSTNAME 55
#define SSL_CTRL_SET_TLSEXT_DEBUG_CB 56
#define SSL_CTRL_SET_TLSEXT_DEBUG_ARG 57
#define SSL_CTRL_GET_TLSEXT_TICKET_KEYS 58
#define SSL_CTRL_SET_TLSEXT_TICKET_KEYS 59
#define SSL_CTRL_SET_TLSEXT_STATUS_REQ_CB 63
#define SSL_CTRL_SET_TLSEXT_STATUS_REQ_CB_ARG 64
#define SSL_CTRL_SET_TLSEXT_STATUS_REQ_TYPE 65
#define SSL_CTRL_GET_TLSEXT_STATUS_REQ_EXTS 66
#define SSL_CTRL_SET_TLSEXT_STATUS_REQ_EXTS 67
#define SSL_CTRL_GET_TLSEXT_STATUS_REQ_IDS 68
#define SSL_CTRL_SET_TLSEXT_STATUS_REQ_IDS 69
#define SSL_CTRL_GET_TLSEXT_STATUS_REQ_OCSP_RESP 70
#define SSL_CTRL_SET_TLSEXT_STATUS_REQ_OCSP_RESP 71
#define SSL_CTRL_SET_TLSEXT_TICKET_KEY_CB 72
#define SSL_CTRL_SET_TLS_EXT_SRP_USERNAME_CB 75
#define SSL_CTRL_SET_SRP_VERIFY_PARAM_CB 76
#define SSL_CTRL_SET_SRP_GIVE_CLIENT_PWD_CB 77
#define SSL_CTRL_SET_SRP_ARG 78
#define SSL_CTRL_SET_TLS_EXT_SRP_USERNAME 79
#define SSL_CTRL_SET_TLS_EXT_SRP_STRENGTH 80
#define SSL_CTRL_SET_TLS_EXT_SRP_PASSWORD 81
#define SSL_CTRL_DTLS_EXT_SEND_HEARTBEAT 85
#define SSL_CTRL_GET_DTLS_EXT_HEARTBEAT_PENDING 86
#define SSL_CTRL_SET_DTLS_EXT_HEARTBEAT_NO_REQUESTS 87
#define DTLS_CTRL_GET_TIMEOUT 73
#define DTLS_CTRL_HANDLE_TIMEOUT 74
#define SSL_CTRL_GET_RI_SUPPORT 76
#define SSL_CTRL_CLEAR_MODE 78
#define SSL_CTRL_SET_NOT_RESUMABLE_SESS_CB 79
#define SSL_CTRL_GET_EXTRA_CHAIN_CERTS 82
#define SSL_CTRL_CLEAR_EXTRA_CHAIN_CERTS 83
#define SSL_CTRL_CHAIN 88
#define SSL_CTRL_CHAIN_CERT 89
#define SSL_CTRL_GET_GROUPS 90
#define SSL_CTRL_SET_GROUPS 91
#define SSL_CTRL_SET_GROUPS_LIST 92
#define SSL_CTRL_GET_SHARED_GROUP 93
#define SSL_CTRL_SET_SIGALGS 97
#define SSL_CTRL_SET_SIGALGS_LIST 98
#define SSL_CTRL_CERT_FLAGS 99
#define SSL_CTRL_CLEAR_CERT_FLAGS 100
#define SSL_CTRL_SET_CLIENT_SIGALGS 101
#define SSL_CTRL_SET_CLIENT_SIGALGS_LIST 102
#define SSL_CTRL_GET_CLIENT_CERT_TYPES 103
#define SSL_CTRL_SET_CLIENT_CERT_TYPES 104
#define SSL_CTRL_BUILD_CERT_CHAIN 105
#define SSL_CTRL_SET_VERIFY_CERT_STORE 106
#define SSL_CTRL_SET_CHAIN_CERT_STORE 107
#define SSL_CTRL_GET_PEER_SIGNATURE_NID 108
#define SSL_CTRL_GET_SERVER_TMP_KEY 109
#define SSL_CTRL_GET_RAW_CIPHERLIST 110
#define SSL_CTRL_GET_EC_POINT_FORMATS 111
#define SSL_CTRL_GET_CHAIN_CERTS 115
#define SSL_CTRL_SELECT_CURRENT_CERT 116
#define SSL_CTRL_SET_CURRENT_CERT 117
#define SSL_CTRL_SET_DH_AUTO 118
#define DTLS_CTRL_SET_LINK_MTU 120
#define DTLS_CTRL_GET_LINK_MIN_MTU 121
#define SSL_CTRL_GET_EXTMS_SUPPORT 122
#define SSL_CTRL_SET_MIN_PROTO_VERSION 123
#define SSL_CTRL_SET_MAX_PROTO_VERSION 124
#define SSL_CTRL_SET_SPLIT_SEND_FRAGMENT 125
#define SSL_CTRL_SET_MAX_PIPELINES 126
#define SSL_CTRL_GET_TLSEXT_STATUS_REQ_TYPE 127
#define SSL_CTRL_GET_TLSEXT_STATUS_REQ_CB 128
#define SSL_CTRL_GET_TLSEXT_STATUS_REQ_CB_ARG 129
#define SSL_CERT_SET_FIRST 1
#define SSL_CERT_SET_NEXT 2
#define SSL_CERT_SET_SERVER 3
#define DTLSv1_get_timeout(ssl, arg) SSL_ctrl(ssl,DTLS_CTRL_GET_TIMEOUT,0, (void *)arg)
#define DTLSv1_handle_timeout(ssl) SSL_ctrl(ssl,DTLS_CTRL_HANDLE_TIMEOUT,0, NULL)
#define SSL_num_renegotiations(ssl) SSL_ctrl((ssl),SSL_CTRL_GET_NUM_RENEGOTIATIONS,0,NULL)
#define SSL_clear_num_renegotiations(ssl) SSL_ctrl((ssl),SSL_CTRL_CLEAR_NUM_RENEGOTIATIONS,0,NULL)
#define SSL_total_renegotiations(ssl) SSL_ctrl((ssl),SSL_CTRL_GET_TOTAL_RENEGOTIATIONS,0,NULL)
#define SSL_CTX_set_tmp_dh(ctx, dh) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_TMP_DH,0,(char *)dh)
#define SSL_CTX_set_tmp_ecdh(ctx, ecdh) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_TMP_ECDH,0,(char *)ecdh)
#define SSL_CTX_set_dh_auto(ctx, onoff) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_DH_AUTO,onoff,NULL)
#define SSL_set_dh_auto(s, onoff) SSL_ctrl(s,SSL_CTRL_SET_DH_AUTO,onoff,NULL)
#define SSL_set_tmp_dh(ssl, dh) SSL_ctrl(ssl,SSL_CTRL_SET_TMP_DH,0,(char *)dh)
#define SSL_set_tmp_ecdh(ssl, ecdh) SSL_ctrl(ssl,SSL_CTRL_SET_TMP_ECDH,0,(char *)ecdh)
#define SSL_CTX_add_extra_chain_cert(ctx, x509) SSL_CTX_ctrl(ctx,SSL_CTRL_EXTRA_CHAIN_CERT,0,(char *)x509)
#define SSL_CTX_get_extra_chain_certs(ctx, px509) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_EXTRA_CHAIN_CERTS,0,px509)
#define SSL_CTX_get_extra_chain_certs_only(ctx, px509) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_EXTRA_CHAIN_CERTS,1,px509)
#define SSL_CTX_clear_extra_chain_certs(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_CLEAR_EXTRA_CHAIN_CERTS,0,NULL)
#define SSL_CTX_set0_chain(ctx, sk) SSL_CTX_ctrl(ctx,SSL_CTRL_CHAIN,0,(char *)sk)
#define SSL_CTX_set1_chain(ctx, sk) SSL_CTX_ctrl(ctx,SSL_CTRL_CHAIN,1,(char *)sk)
#define SSL_CTX_add0_chain_cert(ctx, x509) SSL_CTX_ctrl(ctx,SSL_CTRL_CHAIN_CERT,0,(char *)x509)
#define SSL_CTX_add1_chain_cert(ctx, x509) SSL_CTX_ctrl(ctx,SSL_CTRL_CHAIN_CERT,1,(char *)x509)
#define SSL_CTX_get0_chain_certs(ctx, px509) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_CHAIN_CERTS,0,px509)
#define SSL_CTX_clear_chain_certs(ctx) SSL_CTX_set0_chain(ctx,NULL)
#define SSL_CTX_build_cert_chain(ctx, flags) SSL_CTX_ctrl(ctx,SSL_CTRL_BUILD_CERT_CHAIN, flags, NULL)
#define SSL_CTX_select_current_cert(ctx, x509) SSL_CTX_ctrl(ctx,SSL_CTRL_SELECT_CURRENT_CERT,0,(char *)x509)
#define SSL_CTX_set_current_cert(ctx, op) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_CURRENT_CERT, op, NULL)
#define SSL_CTX_set0_verify_cert_store(ctx, st) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_VERIFY_CERT_STORE,0,(char *)st)
#define SSL_CTX_set1_verify_cert_store(ctx, st) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_VERIFY_CERT_STORE,1,(char *)st)
#define SSL_CTX_set0_chain_cert_store(ctx, st) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_CHAIN_CERT_STORE,0,(char *)st)
#define SSL_CTX_set1_chain_cert_store(ctx, st) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_CHAIN_CERT_STORE,1,(char *)st)
#define SSL_set0_chain(ctx, sk) SSL_ctrl(ctx,SSL_CTRL_CHAIN,0,(char *)sk)
#define SSL_set1_chain(ctx, sk) SSL_ctrl(ctx,SSL_CTRL_CHAIN,1,(char *)sk)
#define SSL_add0_chain_cert(ctx, x509) SSL_ctrl(ctx,SSL_CTRL_CHAIN_CERT,0,(char *)x509)
#define SSL_add1_chain_cert(ctx, x509) SSL_ctrl(ctx,SSL_CTRL_CHAIN_CERT,1,(char *)x509)
#define SSL_get0_chain_certs(ctx, px509) SSL_ctrl(ctx,SSL_CTRL_GET_CHAIN_CERTS,0,px509)
#define SSL_clear_chain_certs(ctx) SSL_set0_chain(ctx,NULL)
#define SSL_build_cert_chain(s, flags) SSL_ctrl(s,SSL_CTRL_BUILD_CERT_CHAIN, flags, NULL)
#define SSL_select_current_cert(ctx, x509) SSL_ctrl(ctx,SSL_CTRL_SELECT_CURRENT_CERT,0,(char *)x509)
#define SSL_set_current_cert(ctx, op) SSL_ctrl(ctx,SSL_CTRL_SET_CURRENT_CERT, op, NULL)
#define SSL_set0_verify_cert_store(s, st) SSL_ctrl(s,SSL_CTRL_SET_VERIFY_CERT_STORE,0,(char *)st)
#define SSL_set1_verify_cert_store(s, st) SSL_ctrl(s,SSL_CTRL_SET_VERIFY_CERT_STORE,1,(char *)st)
#define SSL_set0_chain_cert_store(s, st) SSL_ctrl(s,SSL_CTRL_SET_CHAIN_CERT_STORE,0,(char *)st)
#define SSL_set1_chain_cert_store(s, st) SSL_ctrl(s,SSL_CTRL_SET_CHAIN_CERT_STORE,1,(char *)st)
#define SSL_get1_groups(ctx, s) SSL_ctrl(ctx,SSL_CTRL_GET_GROUPS,0,(char *)s)
#define SSL_get1_curves(ctx, s) SSL_get1_groups((ctx), (s))
#define SSL_CTX_set1_groups(ctx, glist, glistlen) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_GROUPS,glistlen,(char *)glist)
#define SSL_CTX_set1_groups_list(ctx, s) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_GROUPS_LIST,0,(char *)s)
#define SSL_CTX_set1_curves(ctx, clist, clistlen) SSL_CTX_set1_groups((ctx), (clist), (clistlen))
#define SSL_CTX_set1_curves_list(ctx, s) SSL_CTX_set1_groups_list((ctx), (s))
#define SSL_set1_groups(ctx, glist, glistlen) SSL_ctrl(ctx,SSL_CTRL_SET_GROUPS,glistlen,(char *)glist)
#define SSL_set1_groups_list(ctx, s) SSL_ctrl(ctx,SSL_CTRL_SET_GROUPS_LIST,0,(char *)s)
#define SSL_set1_curves(ctx, clist, clistlen) SSL_set1_groups((ctx), (clist), (clistlen))
#define SSL_set1_curves_list(ctx, s) SSL_set1_groups_list((ctx), (s))
#define SSL_get_shared_group(s, n) SSL_ctrl(s,SSL_CTRL_GET_SHARED_GROUP,n,NULL)
#define SSL_get_shared_curve(s, n) SSL_get_shared_group((s), (n))
#define SSL_CTX_set1_sigalgs(ctx, slist, slistlen) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_SIGALGS,slistlen,(int *)slist)
#define SSL_CTX_set1_sigalgs_list(ctx, s) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_SIGALGS_LIST,0,(char *)s)
#define SSL_set1_sigalgs(ctx, slist, slistlen) SSL_ctrl(ctx,SSL_CTRL_SET_SIGALGS,slistlen,(int *)slist)
#define SSL_set1_sigalgs_list(ctx, s) SSL_ctrl(ctx,SSL_CTRL_SET_SIGALGS_LIST,0,(char *)s)
#define SSL_CTX_set1_client_sigalgs(ctx, slist, slistlen) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_CLIENT_SIGALGS,slistlen,(int *)slist)
#define SSL_CTX_set1_client_sigalgs_list(ctx, s) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_CLIENT_SIGALGS_LIST,0,(char *)s)
#define SSL_set1_client_sigalgs(ctx, slist, slistlen) SSL_ctrl(ctx,SSL_CTRL_SET_CLIENT_SIGALGS,clistlen,(int *)slist)
#define SSL_set1_client_sigalgs_list(ctx, s) SSL_ctrl(ctx,SSL_CTRL_SET_CLIENT_SIGALGS_LIST,0,(char *)s)
#define SSL_get0_certificate_types(s, clist) SSL_ctrl(s, SSL_CTRL_GET_CLIENT_CERT_TYPES, 0, (char *)clist)
#define SSL_CTX_set1_client_certificate_types(ctx, clist, clistlen) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_CLIENT_CERT_TYPES,clistlen,(char *)clist)
#define SSL_set1_client_certificate_types(s, clist, clistlen) SSL_ctrl(s,SSL_CTRL_SET_CLIENT_CERT_TYPES,clistlen,(char *)clist)
#define SSL_get_peer_signature_nid(s, pn) SSL_ctrl(s,SSL_CTRL_GET_PEER_SIGNATURE_NID,0,pn)
#define SSL_get_server_tmp_key(s, pk) SSL_ctrl(s,SSL_CTRL_GET_SERVER_TMP_KEY,0,pk)
#define SSL_get0_raw_cipherlist(s, plst) SSL_ctrl(s,SSL_CTRL_GET_RAW_CIPHERLIST,0,plst)
#define SSL_get0_ec_point_formats(s, plst) SSL_ctrl(s,SSL_CTRL_GET_EC_POINT_FORMATS,0,plst)
#define SSL_CTX_set_min_proto_version(ctx, version) SSL_CTX_ctrl(ctx, SSL_CTRL_SET_MIN_PROTO_VERSION, version, NULL)
#define SSL_CTX_set_max_proto_version(ctx, version) SSL_CTX_ctrl(ctx, SSL_CTRL_SET_MAX_PROTO_VERSION, version, NULL)
#define SSL_set_min_proto_version(s, version) SSL_ctrl(s, SSL_CTRL_SET_MIN_PROTO_VERSION, version, NULL)
#define SSL_set_max_proto_version(s, version) SSL_ctrl(s, SSL_CTRL_SET_MAX_PROTO_VERSION, version, NULL)
#define SSL_CTX_need_tmp_RSA(ctx) 0
#define SSL_CTX_set_tmp_rsa(ctx, rsa) 1
#define SSL_need_tmp_RSA(ssl) 0
#define SSL_set_tmp_rsa(ssl, rsa) 1
#define SSL_CTX_set_ecdh_auto(dummy, onoff) ((onoff) != 0)
#define SSL_set_ecdh_auto(dummy, onoff) ((onoff) != 0)
#define SSL_CTX_set_tmp_rsa_callback(ctx, cb) while(0) (cb)(NULL, 0, 0)
#define SSL_set_tmp_rsa_callback(ssl, cb) while(0) (cb)(NULL, 0, 0)
#define SSL_load_error_strings()
#define SSLv23_method TLS_method
#define SSLv23_server_method TLS_server_method
#define SSLv23_client_method TLS_client_method
#define SSL_library_init() OPENSSL_init_ssl(0, NULL)
#define SSL_get0_session SSL_get_session/* just peek at pointer */
#define SSL_get_ex_new_index(l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_SSL, l, p, newf, dupf, freef)
#define SSL_SESSION_get_ex_new_index(l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_SSL_SESSION, l, p, newf, dupf, freef)
#define SSL_CTX_get_ex_new_index(l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_SSL_CTX, l, p, newf, dupf, freef)
#define SSL_CTX_sess_set_cache_size(ctx, t) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_SESS_CACHE_SIZE,t,NULL)
#define SSL_CTX_sess_get_cache_size(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_SESS_CACHE_SIZE,0,NULL)
#define SSL_CTX_set_session_cache_mode(ctx, m) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_SESS_CACHE_MODE,m,NULL)
#define SSL_CTX_get_session_cache_mode(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_SESS_CACHE_MODE,0,NULL)
#define SSL_CTX_get_default_read_ahead(ctx) SSL_CTX_get_read_ahead(ctx)
#define SSL_CTX_set_default_read_ahead(ctx, m) SSL_CTX_set_read_ahead(ctx,m)
#define SSL_CTX_get_read_ahead(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_READ_AHEAD,0,NULL)
#define SSL_CTX_set_read_ahead(ctx, m) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_READ_AHEAD,m,NULL)
#define SSL_CTX_get_max_cert_list(ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_MAX_CERT_LIST,0,NULL)
#define SSL_CTX_set_max_cert_list(ctx, m) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_MAX_CERT_LIST,m,NULL)
#define SSL_get_max_cert_list(ssl) SSL_ctrl(ssl,SSL_CTRL_GET_MAX_CERT_LIST,0,NULL)
#define SSL_set_max_cert_list(ssl, m) SSL_ctrl(ssl,SSL_CTRL_SET_MAX_CERT_LIST,m,NULL)
#define SSL_CTX_set_max_send_fragment(ctx, m) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_MAX_SEND_FRAGMENT,m,NULL)
#define SSL_set_max_send_fragment(ssl, m) SSL_ctrl(ssl,SSL_CTRL_SET_MAX_SEND_FRAGMENT,m,NULL)
#define SSL_CTX_set_split_send_fragment(ctx, m) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_SPLIT_SEND_FRAGMENT,m,NULL)
#define SSL_set_split_send_fragment(ssl, m) SSL_ctrl(ssl,SSL_CTRL_SET_SPLIT_SEND_FRAGMENT,m,NULL)
#define SSL_CTX_set_max_pipelines(ctx, m) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_MAX_PIPELINES,m,NULL)
#define SSL_set_max_pipelines(ssl, m) SSL_ctrl(ssl,SSL_CTRL_SET_MAX_PIPELINES,m,NULL)
#define SSL_COMP_free_compression_methods() while(0) continue
#define SSL_cache_hit(s) SSL_session_reused(s)
#define SSL_disable_ct(s) ((void) SSL_set_validation_callback((s), NULL, NULL))
#define SSL_CTX_disable_ct(ctx) ((void) SSL_CTX_set_validation_callback((ctx), NULL, NULL))
#define SSL_SECOP_OTHER_TYPE 0xffff0000
#define SSL_SECOP_OTHER_NONE 0
#define SSL_SECOP_OTHER_CIPHER (1 << 16)
#define SSL_SECOP_OTHER_CURVE (2 << 16)
#define SSL_SECOP_OTHER_DH (3 << 16)
#define SSL_SECOP_OTHER_PKEY (4 << 16)
#define SSL_SECOP_OTHER_SIGALG (5 << 16)
#define SSL_SECOP_OTHER_CERT (6 << 16)
#define SSL_SECOP_PEER 0x1000
#define SSL_SECOP_CIPHER_SUPPORTED (1 | SSL_SECOP_OTHER_CIPHER)
#define SSL_SECOP_CIPHER_SHARED (2 | SSL_SECOP_OTHER_CIPHER)
#define SSL_SECOP_CIPHER_CHECK (3 | SSL_SECOP_OTHER_CIPHER)
#define SSL_SECOP_CURVE_SUPPORTED (4 | SSL_SECOP_OTHER_CURVE)
#define SSL_SECOP_CURVE_SHARED (5 | SSL_SECOP_OTHER_CURVE)
#define SSL_SECOP_CURVE_CHECK (6 | SSL_SECOP_OTHER_CURVE)
#define SSL_SECOP_TMP_DH (7 | SSL_SECOP_OTHER_PKEY)
#define SSL_SECOP_VERSION (9 | SSL_SECOP_OTHER_NONE)
#define SSL_SECOP_TICKET (10 | SSL_SECOP_OTHER_NONE)
#define SSL_SECOP_SIGALG_SUPPORTED (11 | SSL_SECOP_OTHER_SIGALG)
#define SSL_SECOP_SIGALG_SHARED (12 | SSL_SECOP_OTHER_SIGALG)
#define SSL_SECOP_SIGALG_CHECK (13 | SSL_SECOP_OTHER_SIGALG)
#define SSL_SECOP_SIGALG_MASK (14 | SSL_SECOP_OTHER_SIGALG)
#define SSL_SECOP_COMPRESSION (15 | SSL_SECOP_OTHER_NONE)
#define SSL_SECOP_EE_KEY (16 | SSL_SECOP_OTHER_CERT)
#define SSL_SECOP_CA_KEY (17 | SSL_SECOP_OTHER_CERT)
#define SSL_SECOP_CA_MD (18 | SSL_SECOP_OTHER_CERT)
#define SSL_SECOP_PEER_EE_KEY (SSL_SECOP_EE_KEY | SSL_SECOP_PEER)
#define SSL_SECOP_PEER_CA_KEY (SSL_SECOP_CA_KEY | SSL_SECOP_PEER)
#define SSL_SECOP_PEER_CA_MD (SSL_SECOP_CA_MD | SSL_SECOP_PEER)
#define OPENSSL_INIT_NO_LOAD_SSL_STRINGS 0x00100000L
#define OPENSSL_INIT_LOAD_SSL_STRINGS 0x00200000L
#define OPENSSL_INIT_SSL_DEFAULT (OPENSSL_INIT_LOAD_SSL_STRINGS | OPENSSL_INIT_LOAD_CRYPTO_STRINGS)
#define SSL_F_ADD_CLIENT_KEY_SHARE_EXT 438
#define SSL_F_ADD_KEY_SHARE 512
#define SSL_F_CHECK_SUITEB_CIPHER_LIST 331
#define SSL_F_CT_MOVE_SCTS 345
#define SSL_F_CT_STRICT 349
#define SSL_F_D2I_SSL_SESSION 103
#define SSL_F_DANE_CTX_ENABLE 347
#define SSL_F_DANE_MTYPE_SET 393
#define SSL_F_DANE_TLSA_ADD 394
#define SSL_F_DERIVE_SECRET_KEY_AND_IV 514
#define SSL_F_DO_DTLS1_WRITE 245
#define SSL_F_DO_SSL3_WRITE 104
#define SSL_F_DTLS1_BUFFER_RECORD 247
#define SSL_F_DTLS1_CHECK_TIMEOUT_NUM 318
#define SSL_F_DTLS1_HEARTBEAT 305
#define SSL_F_DTLS1_PREPROCESS_FRAGMENT 288
#define SSL_F_DTLS1_PROCESS_BUFFERED_RECORDS 424
#define SSL_F_DTLS1_PROCESS_RECORD 257
#define SSL_F_DTLS1_READ_BYTES 258
#define SSL_F_DTLS1_READ_FAILED 339
#define SSL_F_DTLS1_RETRANSMIT_MESSAGE 390
#define SSL_F_DTLS1_WRITE_APP_DATA_BYTES 268
#define SSL_F_DTLSV1_LISTEN 350
#define SSL_F_DTLS_CONSTRUCT_CHANGE_CIPHER_SPEC 371
#define SSL_F_DTLS_CONSTRUCT_HELLO_VERIFY_REQUEST 385
#define SSL_F_DTLS_GET_REASSEMBLED_MESSAGE 370
#define SSL_F_DTLS_PROCESS_HELLO_VERIFY 386
#define SSL_F_FINAL_EC_PT_FORMATS 485
#define SSL_F_FINAL_EMS 486
#define SSL_F_FINAL_KEY_SHARE 503
#define SSL_F_FINAL_RENEGOTIATE 483
#define SSL_F_FINAL_SIG_ALGS 497
#define SSL_F_NSS_KEYLOG_INT 500
#define SSL_F_OPENSSL_INIT_SSL 342
#define SSL_F_OSSL_STATEM_CLIENT13_READ_TRANSITION 436
#define SSL_F_OSSL_STATEM_CLIENT_CONSTRUCT_MESSAGE 430
#define SSL_F_OSSL_STATEM_CLIENT_READ_TRANSITION 417
#define SSL_F_OSSL_STATEM_SERVER13_READ_TRANSITION 437
#define SSL_F_OSSL_STATEM_SERVER_CONSTRUCT_MESSAGE 431
#define SSL_F_OSSL_STATEM_SERVER_READ_TRANSITION 418
#define SSL_F_PROCESS_KEY_SHARE_EXT 439
#define SSL_F_READ_STATE_MACHINE 352
#define SSL_F_SSL3_CHANGE_CIPHER_STATE 129
#define SSL_F_SSL3_CHECK_CERT_AND_ALGORITHM 130
#define SSL_F_SSL3_CTRL 213
#define SSL_F_SSL3_CTX_CTRL 133
#define SSL_F_SSL3_DIGEST_CACHED_RECORDS 293
#define SSL_F_SSL3_DO_CHANGE_CIPHER_SPEC 292
#define SSL_F_SSL3_FINAL_FINISH_MAC 285
#define SSL_F_SSL3_GENERATE_KEY_BLOCK 238
#define SSL_F_SSL3_GENERATE_MASTER_SECRET 388
#define SSL_F_SSL3_GET_RECORD 143
#define SSL_F_SSL3_INIT_FINISHED_MAC 397
#define SSL_F_SSL3_OUTPUT_CERT_CHAIN 147
#define SSL_F_SSL3_READ_BYTES 148
#define SSL_F_SSL3_READ_N 149
#define SSL_F_SSL3_SETUP_KEY_BLOCK 157
#define SSL_F_SSL3_SETUP_READ_BUFFER 156
#define SSL_F_SSL3_SETUP_WRITE_BUFFER 291
#define SSL_F_SSL3_WRITE_BYTES 158
#define SSL_F_SSL3_WRITE_PENDING 159
#define SSL_F_SSL_ADD_CERT_CHAIN 316
#define SSL_F_SSL_ADD_CERT_TO_BUF 319
#define SSL_F_SSL_ADD_CERT_TO_WPACKET 493
#define SSL_F_SSL_ADD_CLIENTHELLO_RENEGOTIATE_EXT 298
#define SSL_F_SSL_ADD_CLIENTHELLO_TLSEXT 277
#define SSL_F_SSL_ADD_CLIENTHELLO_USE_SRTP_EXT 307
#define SSL_F_SSL_ADD_DIR_CERT_SUBJECTS_TO_STACK 215
#define SSL_F_SSL_ADD_FILE_CERT_SUBJECTS_TO_STACK 216
#define SSL_F_SSL_ADD_SERVERHELLO_RENEGOTIATE_EXT 299
#define SSL_F_SSL_ADD_SERVERHELLO_TLSEXT 278
#define SSL_F_SSL_ADD_SERVERHELLO_USE_SRTP_EXT 308
#define SSL_F_SSL_BAD_METHOD 160
#define SSL_F_SSL_BUILD_CERT_CHAIN 332
#define SSL_F_SSL_BYTES_TO_CIPHER_LIST 161
#define SSL_F_SSL_CERT_ADD0_CHAIN_CERT 346
#define SSL_F_SSL_CERT_DUP 221
#define SSL_F_SSL_CERT_NEW 162
#define SSL_F_SSL_CERT_SET0_CHAIN 340
#define SSL_F_SSL_CHECK_PRIVATE_KEY 163
#define SSL_F_SSL_CHECK_SERVERHELLO_TLSEXT 280
#define SSL_F_SSL_CHECK_SRVR_ECC_CERT_AND_ALG 279
#define SSL_F_SSL_CIPHER_LIST_TO_BYTES 425
#define SSL_F_SSL_CIPHER_PROCESS_RULESTR 230
#define SSL_F_SSL_CIPHER_STRENGTH_SORT 231
#define SSL_F_SSL_CLEAR 164
#define SSL_F_SSL_COMP_ADD_COMPRESSION_METHOD 165
#define SSL_F_SSL_CONF_CMD 334
#define SSL_F_SSL_CREATE_CIPHER_LIST 166
#define SSL_F_SSL_CTRL 232
#define SSL_F_SSL_CTX_CHECK_PRIVATE_KEY 168
#define SSL_F_SSL_CTX_ENABLE_CT 398
#define SSL_F_SSL_CTX_MAKE_PROFILES 309
#define SSL_F_SSL_CTX_NEW 169
#define SSL_F_SSL_CTX_SET_ALPN_PROTOS 343
#define SSL_F_SSL_CTX_SET_CIPHER_LIST 269
#define SSL_F_SSL_CTX_SET_CLIENT_CERT_ENGINE 290
#define SSL_F_SSL_CTX_SET_CT_VALIDATION_CALLBACK 396
#define SSL_F_SSL_CTX_SET_SESSION_ID_CONTEXT 219
#define SSL_F_SSL_CTX_SET_SSL_VERSION 170
#define SSL_F_SSL_CTX_USE_CERTIFICATE 171
#define SSL_F_SSL_CTX_USE_CERTIFICATE_ASN1 172
#define SSL_F_SSL_CTX_USE_CERTIFICATE_FILE 173
#define SSL_F_SSL_CTX_USE_PRIVATEKEY 174
#define SSL_F_SSL_CTX_USE_PRIVATEKEY_ASN1 175
#define SSL_F_SSL_CTX_USE_PRIVATEKEY_FILE 176
#define SSL_F_SSL_CTX_USE_PSK_IDENTITY_HINT 272
#define SSL_F_SSL_CTX_USE_RSAPRIVATEKEY 177
#define SSL_F_SSL_CTX_USE_RSAPRIVATEKEY_ASN1 178
#define SSL_F_SSL_CTX_USE_RSAPRIVATEKEY_FILE 179
#define SSL_F_SSL_CTX_USE_SERVERINFO 336
#define SSL_F_SSL_CTX_USE_SERVERINFO_FILE 337
#define SSL_F_SSL_DANE_DUP 403
#define SSL_F_SSL_DANE_ENABLE 395
#define SSL_F_SSL_DO_CONFIG 391
#define SSL_F_SSL_DO_HANDSHAKE 180
#define SSL_F_SSL_DUP_CA_LIST 408
#define SSL_F_SSL_ENABLE_CT 402
#define SSL_F_SSL_GET_NEW_SESSION 181
#define SSL_F_SSL_GET_PREV_SESSION 217
#define SSL_F_SSL_GET_SERVER_CERT_INDEX 322
#define SSL_F_SSL_GET_SIGN_PKEY 183
#define SSL_F_SSL_INIT_WBIO_BUFFER 184
#define SSL_F_SSL_KEY_UPDATE 515
#define SSL_F_SSL_LOAD_CLIENT_CA_FILE 185
#define SSL_F_SSL_LOG_MASTER_SECRET 498
#define SSL_F_SSL_LOG_RSA_CLIENT_KEY_EXCHANGE 499
#define SSL_F_SSL_MODULE_INIT 392
#define SSL_F_SSL_NEW 186
#define SSL_F_SSL_PARSE_CLIENTHELLO_RENEGOTIATE_EXT 300
#define SSL_F_SSL_PARSE_CLIENTHELLO_TLSEXT 302
#define SSL_F_SSL_PARSE_CLIENTHELLO_USE_SRTP_EXT 310
#define SSL_F_SSL_PARSE_SERVERHELLO_RENEGOTIATE_EXT 301
#define SSL_F_SSL_PARSE_SERVERHELLO_TLSEXT 303
#define SSL_F_SSL_PARSE_SERVERHELLO_USE_SRTP_EXT 311
#define SSL_F_SSL_PEEK 270
#define SSL_F_SSL_PEEK_EX 432
#define SSL_F_SSL_READ 223
#define SSL_F_SSL_READ_EX 434
#define SSL_F_SSL_RENEGOTIATE 516
#define SSL_F_SSL_SCAN_CLIENTHELLO_TLSEXT 320
#define SSL_F_SSL_SCAN_SERVERHELLO_TLSEXT 321
#define SSL_F_SSL_SESSION_DUP 348
#define SSL_F_SSL_SESSION_NEW 189
#define SSL_F_SSL_SESSION_PRINT_FP 190
#define SSL_F_SSL_SESSION_SET1_ID 423
#define SSL_F_SSL_SESSION_SET1_ID_CONTEXT 312
#define SSL_F_SSL_SET_ALPN_PROTOS 344
#define SSL_F_SSL_SET_CERT 191
#define SSL_F_SSL_SET_CIPHER_LIST 271
#define SSL_F_SSL_SET_CT_VALIDATION_CALLBACK 399
#define SSL_F_SSL_SET_FD 192
#define SSL_F_SSL_SET_PKEY 193
#define SSL_F_SSL_SET_RFD 194
#define SSL_F_SSL_SET_SESSION 195
#define SSL_F_SSL_SET_SESSION_ID_CONTEXT 218
#define SSL_F_SSL_SET_SESSION_TICKET_EXT 294
#define SSL_F_SSL_SET_WFD 196
#define SSL_F_SSL_SHUTDOWN 224
#define SSL_F_SSL_SRP_CTX_INIT 313
#define SSL_F_SSL_START_ASYNC_JOB 389
#define SSL_F_SSL_UNDEFINED_FUNCTION 197
#define SSL_F_SSL_UNDEFINED_VOID_FUNCTION 244
#define SSL_F_SSL_USE_CERTIFICATE 198
#define SSL_F_SSL_USE_CERTIFICATE_ASN1 199
#define SSL_F_SSL_USE_CERTIFICATE_FILE 200
#define SSL_F_SSL_USE_PRIVATEKEY 201
#define SSL_F_SSL_USE_PRIVATEKEY_ASN1 202
#define SSL_F_SSL_USE_PRIVATEKEY_FILE 203
#define SSL_F_SSL_USE_PSK_IDENTITY_HINT 273
#define SSL_F_SSL_USE_RSAPRIVATEKEY 204
#define SSL_F_SSL_USE_RSAPRIVATEKEY_ASN1 205
#define SSL_F_SSL_USE_RSAPRIVATEKEY_FILE 206
#define SSL_F_SSL_VALIDATE_CT 400
#define SSL_F_SSL_VERIFY_CERT_CHAIN 207
#define SSL_F_SSL_WRITE 208
#define SSL_F_SSL_WRITE_EX 433
#define SSL_F_STATE_MACHINE 353
#define SSL_F_TLS12_CHECK_PEER_SIGALG 333
#define SSL_F_TLS13_CHANGE_CIPHER_STATE 440
#define SSL_F_TLS13_SETUP_KEY_BLOCK 441
#define SSL_F_TLS1_CHANGE_CIPHER_STATE 209
#define SSL_F_TLS1_CHECK_DUPLICATE_EXTENSIONS 341
#define SSL_F_TLS1_ENC 401
#define SSL_F_TLS1_EXPORT_KEYING_MATERIAL 314
#define SSL_F_TLS1_GET_CURVELIST 338
#define SSL_F_TLS1_PRF 284
#define SSL_F_TLS1_SETUP_KEY_BLOCK 211
#define SSL_F_TLS1_SET_SERVER_SIGALGS 335
#define SSL_F_TLS_CHOOSE_SIGALG 513
#define SSL_F_TLS_CLIENT_KEY_EXCHANGE_POST_WORK 354
#define SSL_F_TLS_COLLECT_EXTENSIONS 435
#define SSL_F_TLS_CONSTRUCT_CERTIFICATE_REQUEST 372
#define SSL_F_TLS_CONSTRUCT_CERT_STATUS 429
#define SSL_F_TLS_CONSTRUCT_CERT_STATUS_BODY 494
#define SSL_F_TLS_CONSTRUCT_CERT_VERIFY 496
#define SSL_F_TLS_CONSTRUCT_CHANGE_CIPHER_SPEC 427
#define SSL_F_TLS_CONSTRUCT_CKE_DHE 404
#define SSL_F_TLS_CONSTRUCT_CKE_ECDHE 405
#define SSL_F_TLS_CONSTRUCT_CKE_GOST 406
#define SSL_F_TLS_CONSTRUCT_CKE_PSK_PREAMBLE 407
#define SSL_F_TLS_CONSTRUCT_CKE_RSA 409
#define SSL_F_TLS_CONSTRUCT_CKE_SRP 410
#define SSL_F_TLS_CONSTRUCT_CLIENT_CERTIFICATE 484
#define SSL_F_TLS_CONSTRUCT_CLIENT_HELLO 487
#define SSL_F_TLS_CONSTRUCT_CLIENT_KEY_EXCHANGE 488
#define SSL_F_TLS_CONSTRUCT_CLIENT_VERIFY 489
#define SSL_F_TLS_CONSTRUCT_CTOS_ALPN 466
#define SSL_F_TLS_CONSTRUCT_CTOS_CERTIFICATE 355
#define SSL_F_TLS_CONSTRUCT_CTOS_EC_PT_FORMATS 467
#define SSL_F_TLS_CONSTRUCT_CTOS_EMS 468
#define SSL_F_TLS_CONSTRUCT_CTOS_ETM 469
#define SSL_F_TLS_CONSTRUCT_CTOS_HELLO 356
#define SSL_F_TLS_CONSTRUCT_CTOS_KEY_EXCHANGE 357
#define SSL_F_TLS_CONSTRUCT_CTOS_KEY_SHARE 470
#define SSL_F_TLS_CONSTRUCT_CTOS_NPN 471
#define SSL_F_TLS_CONSTRUCT_CTOS_PADDING 472
#define SSL_F_TLS_CONSTRUCT_CTOS_PSK 501
#define SSL_F_TLS_CONSTRUCT_CTOS_PSK_KEX_MODES 509
#define SSL_F_TLS_CONSTRUCT_CTOS_RENEGOTIATE 473
#define SSL_F_TLS_CONSTRUCT_CTOS_SCT 474
#define SSL_F_TLS_CONSTRUCT_CTOS_SERVER_NAME 475
#define SSL_F_TLS_CONSTRUCT_CTOS_SESSION_TICKET 476
#define SSL_F_TLS_CONSTRUCT_CTOS_SIG_ALGS 477
#define SSL_F_TLS_CONSTRUCT_CTOS_SRP 478
#define SSL_F_TLS_CONSTRUCT_CTOS_STATUS_REQUEST 479
#define SSL_F_TLS_CONSTRUCT_CTOS_SUPPORTED_GROUPS 480
#define SSL_F_TLS_CONSTRUCT_CTOS_SUPPORTED_VERSIONS 481
#define SSL_F_TLS_CONSTRUCT_CTOS_USE_SRTP 482
#define SSL_F_TLS_CONSTRUCT_CTOS_VERIFY 358
#define SSL_F_TLS_CONSTRUCT_ENCRYPTED_EXTENSIONS 443
#define SSL_F_TLS_CONSTRUCT_EXTENSIONS 447
#define SSL_F_TLS_CONSTRUCT_FINISHED 359
#define SSL_F_TLS_CONSTRUCT_HELLO_REQUEST 373
#define SSL_F_TLS_CONSTRUCT_HELLO_RETRY_REQUEST 510
#define SSL_F_TLS_CONSTRUCT_KEY_UPDATE 517
#define SSL_F_TLS_CONSTRUCT_NEW_SESSION_TICKET 428
#define SSL_F_TLS_CONSTRUCT_NEXT_PROTO 426
#define SSL_F_TLS_CONSTRUCT_SERVER_CERTIFICATE 490
#define SSL_F_TLS_CONSTRUCT_SERVER_HELLO 491
#define SSL_F_TLS_CONSTRUCT_SERVER_KEY_EXCHANGE 492
#define SSL_F_TLS_CONSTRUCT_STOC_ALPN 451
#define SSL_F_TLS_CONSTRUCT_STOC_CERTIFICATE 374
#define SSL_F_TLS_CONSTRUCT_STOC_CRYPTOPRO_BUG 452
#define SSL_F_TLS_CONSTRUCT_STOC_DONE 375
#define SSL_F_TLS_CONSTRUCT_STOC_EC_PT_FORMATS 453
#define SSL_F_TLS_CONSTRUCT_STOC_EMS 454
#define SSL_F_TLS_CONSTRUCT_STOC_ETM 455
#define SSL_F_TLS_CONSTRUCT_STOC_HELLO 376
#define SSL_F_TLS_CONSTRUCT_STOC_KEY_EXCHANGE 377
#define SSL_F_TLS_CONSTRUCT_STOC_KEY_SHARE 456
#define SSL_F_TLS_CONSTRUCT_STOC_NEXT_PROTO_NEG 457
#define SSL_F_TLS_CONSTRUCT_STOC_PSK 504
#define SSL_F_TLS_CONSTRUCT_STOC_RENEGOTIATE 458
#define SSL_F_TLS_CONSTRUCT_STOC_SERVER_NAME 459
#define SSL_F_TLS_CONSTRUCT_STOC_SESSION_TICKET 460
#define SSL_F_TLS_CONSTRUCT_STOC_STATUS_REQUEST 461
#define SSL_F_TLS_CONSTRUCT_STOC_USE_SRTP 462
#define SSL_F_TLS_GET_MESSAGE_BODY 351
#define SSL_F_TLS_GET_MESSAGE_HEADER 387
#define SSL_F_TLS_PARSE_CLIENTHELLO_TLSEXT 449
#define SSL_F_TLS_PARSE_CTOS_KEY_SHARE 463
#define SSL_F_TLS_PARSE_CTOS_PSK 505
#define SSL_F_TLS_PARSE_CTOS_RENEGOTIATE 464
#define SSL_F_TLS_PARSE_CTOS_USE_SRTP 465
#define SSL_F_TLS_PARSE_STOC_KEY_SHARE 445
#define SSL_F_TLS_PARSE_STOC_PSK 502
#define SSL_F_TLS_PARSE_STOC_RENEGOTIATE 448
#define SSL_F_TLS_PARSE_STOC_USE_SRTP 446
#define SSL_F_TLS_POST_PROCESS_CLIENT_HELLO 378
#define SSL_F_TLS_POST_PROCESS_CLIENT_KEY_EXCHANGE 384
#define SSL_F_TLS_PREPARE_CLIENT_CERTIFICATE 360
#define SSL_F_TLS_PROCESS_CERTIFICATE_REQUEST 361
#define SSL_F_TLS_PROCESS_CERT_STATUS 362
#define SSL_F_TLS_PROCESS_CERT_STATUS_BODY 495
#define SSL_F_TLS_PROCESS_CERT_VERIFY 379
#define SSL_F_TLS_PROCESS_CHANGE_CIPHER_SPEC 363
#define SSL_F_TLS_PROCESS_CKE_DHE 411
#define SSL_F_TLS_PROCESS_CKE_ECDHE 412
#define SSL_F_TLS_PROCESS_CKE_GOST 413
#define SSL_F_TLS_PROCESS_CKE_PSK_PREAMBLE 414
#define SSL_F_TLS_PROCESS_CKE_RSA 415
#define SSL_F_TLS_PROCESS_CKE_SRP 416
#define SSL_F_TLS_PROCESS_CLIENT_CERTIFICATE 380
#define SSL_F_TLS_PROCESS_CLIENT_HELLO 381
#define SSL_F_TLS_PROCESS_CLIENT_KEY_EXCHANGE 382
#define SSL_F_TLS_PROCESS_ENCRYPTED_EXTENSIONS 444
#define SSL_F_TLS_PROCESS_FINISHED 364
#define SSL_F_TLS_PROCESS_HELLO_REQ 507
#define SSL_F_TLS_PROCESS_HELLO_RETRY_REQUEST 511
#define SSL_F_TLS_PROCESS_INITIAL_SERVER_FLIGHT 442
#define SSL_F_TLS_PROCESS_KEY_EXCHANGE 365
#define SSL_F_TLS_PROCESS_KEY_UPDATE 518
#define SSL_F_TLS_PROCESS_NEW_SESSION_TICKET 366
#define SSL_F_TLS_PROCESS_NEXT_PROTO 383
#define SSL_F_TLS_PROCESS_SERVER_CERTIFICATE 367
#define SSL_F_TLS_PROCESS_SERVER_DONE 368
#define SSL_F_TLS_PROCESS_SERVER_HELLO 369
#define SSL_F_TLS_PROCESS_SKE_DHE 419
#define SSL_F_TLS_PROCESS_SKE_ECDHE 420
#define SSL_F_TLS_PROCESS_SKE_PSK_PREAMBLE 421
#define SSL_F_TLS_PROCESS_SKE_SRP 422
#define SSL_F_TLS_PSK_DO_BINDER 506
#define SSL_F_TLS_SCAN_CLIENTHELLO_TLSEXT 450
#define SSL_F_TLS_SETUP_HANDSHAKE 508
#define SSL_F_USE_CERTIFICATE_CHAIN_FILE 220
#define SSL_R_APP_DATA_IN_HANDSHAKE 100
#define SSL_R_ATTEMPT_TO_REUSE_SESSION_IN_DIFFERENT_CONTEXT 272
#define SSL_R_AT_LEAST_TLS_1_0_NEEDED_IN_FIPS_MODE 143
#define SSL_R_AT_LEAST_TLS_1_2_NEEDED_IN_SUITEB_MODE 158
#define SSL_R_BAD_CHANGE_CIPHER_SPEC 103
#define SSL_R_BAD_DATA 390
#define SSL_R_BAD_DATA_RETURNED_BY_CALLBACK 106
#define SSL_R_BAD_DECOMPRESSION 107
#define SSL_R_BAD_DH_VALUE 102
#define SSL_R_BAD_DIGEST_LENGTH 111
#define SSL_R_BAD_ECC_CERT 304
#define SSL_R_BAD_ECPOINT 306
#define SSL_R_BAD_EXTENSION 110
#define SSL_R_BAD_HANDSHAKE_LENGTH 332
#define SSL_R_BAD_HELLO_REQUEST 105
#define SSL_R_BAD_KEY_SHARE 108
#define SSL_R_BAD_KEY_UPDATE 122
#define SSL_R_BAD_LENGTH 271
#define SSL_R_BAD_PACKET_LENGTH 115
#define SSL_R_BAD_PROTOCOL_VERSION_NUMBER 116
#define SSL_R_BAD_PSK_IDENTITY 114
#define SSL_R_BAD_RECORD_TYPE 443
#define SSL_R_BAD_RSA_ENCRYPT 119
#define SSL_R_BAD_SIGNATURE 123
#define SSL_R_BAD_SRP_A_LENGTH 347
#define SSL_R_BAD_SRP_PARAMETERS 371
#define SSL_R_BAD_SRTP_MKI_VALUE 352
#define SSL_R_BAD_SRTP_PROTECTION_PROFILE_LIST 353
#define SSL_R_BAD_SSL_FILETYPE 124
#define SSL_R_BAD_VALUE 384
#define SSL_R_BAD_WRITE_RETRY 127
#define SSL_R_BIO_NOT_SET 128
#define SSL_R_BLOCK_CIPHER_PAD_IS_WRONG 129
#define SSL_R_BN_LIB 130
#define SSL_R_CANNOT_CHANGE_CIPHER 109
#define SSL_R_CA_DN_LENGTH_MISMATCH 131
#define SSL_R_CA_KEY_TOO_SMALL 397
#define SSL_R_CA_MD_TOO_WEAK 398
#define SSL_R_CCS_RECEIVED_EARLY 133
#define SSL_R_CERTIFICATE_VERIFY_FAILED 134
#define SSL_R_CERT_CB_ERROR 377
#define SSL_R_CERT_LENGTH_MISMATCH 135
#define SSL_R_CIPHER_CODE_WRONG_LENGTH 137
#define SSL_R_CIPHER_OR_HASH_UNAVAILABLE 138
#define SSL_R_CLIENTHELLO_TLSEXT 226
#define SSL_R_COMPRESSED_LENGTH_TOO_LONG 140
#define SSL_R_COMPRESSION_DISABLED 343
#define SSL_R_COMPRESSION_FAILURE 141
#define SSL_R_COMPRESSION_ID_NOT_WITHIN_PRIVATE_RANGE 307
#define SSL_R_COMPRESSION_LIBRARY_ERROR 142
#define SSL_R_CONNECTION_TYPE_NOT_SET 144
#define SSL_R_CONTEXT_NOT_DANE_ENABLED 167
#define SSL_R_COOKIE_GEN_CALLBACK_FAILURE 400
#define SSL_R_COOKIE_MISMATCH 308
#define SSL_R_CUSTOM_EXT_HANDLER_ALREADY_INSTALLED 206
#define SSL_R_DANE_ALREADY_ENABLED 172
#define SSL_R_DANE_CANNOT_OVERRIDE_MTYPE_FULL 173
#define SSL_R_DANE_NOT_ENABLED 175
#define SSL_R_DANE_TLSA_BAD_CERTIFICATE 180
#define SSL_R_DANE_TLSA_BAD_CERTIFICATE_USAGE 184
#define SSL_R_DANE_TLSA_BAD_DATA_LENGTH 189
#define SSL_R_DANE_TLSA_BAD_DIGEST_LENGTH 192
#define SSL_R_DANE_TLSA_BAD_MATCHING_TYPE 200
#define SSL_R_DANE_TLSA_BAD_PUBLIC_KEY 201
#define SSL_R_DANE_TLSA_BAD_SELECTOR 202
#define SSL_R_DANE_TLSA_NULL_DATA 203
#define SSL_R_DATA_BETWEEN_CCS_AND_FINISHED 145
#define SSL_R_DATA_LENGTH_TOO_LONG 146
#define SSL_R_DECRYPTION_FAILED 147
#define SSL_R_DECRYPTION_FAILED_OR_BAD_RECORD_MAC 281
#define SSL_R_DH_KEY_TOO_SMALL 394
#define SSL_R_DH_PUBLIC_VALUE_LENGTH_IS_WRONG 148
#define SSL_R_DIGEST_CHECK_FAILED 149
#define SSL_R_DTLS_MESSAGE_TOO_BIG 334
#define SSL_R_DUPLICATE_COMPRESSION_ID 309
#define SSL_R_ECC_CERT_NOT_FOR_SIGNING 318
#define SSL_R_ECDH_REQUIRED_FOR_SUITEB_MODE 374
#define SSL_R_EE_KEY_TOO_SMALL 399
#define SSL_R_EMPTY_SRTP_PROTECTION_PROFILE_LIST 354
#define SSL_R_ENCRYPTED_LENGTH_TOO_LONG 150
#define SSL_R_ERROR_IN_RECEIVED_CIPHER_LIST 151
#define SSL_R_ERROR_SETTING_TLSA_BASE_DOMAIN 204
#define SSL_R_EXCESSIVE_MESSAGE_SIZE 152
#define SSL_R_EXTRA_DATA_IN_MESSAGE 153
#define SSL_R_FAILED_TO_INIT_ASYNC 405
#define SSL_R_FRAGMENTED_CLIENT_HELLO 401
#define SSL_R_GOT_A_FIN_BEFORE_A_CCS 154
#define SSL_R_HTTPS_PROXY_REQUEST 155
#define SSL_R_HTTP_REQUEST 156
#define SSL_R_ILLEGAL_SUITEB_DIGEST 380
#define SSL_R_INAPPROPRIATE_FALLBACK 373
#define SSL_R_INCONSISTENT_COMPRESSION 340
#define SSL_R_INCONSISTENT_EXTMS 104
#define SSL_R_INVALID_COMMAND 280
#define SSL_R_INVALID_COMPRESSION_ALGORITHM 341
#define SSL_R_INVALID_CONFIGURATION_NAME 113
#define SSL_R_INVALID_CT_VALIDATION_TYPE 212
#define SSL_R_INVALID_KEY_UPDATE_TYPE 120
#define SSL_R_INVALID_NULL_CMD_NAME 385
#define SSL_R_INVALID_SEQUENCE_NUMBER 402
#define SSL_R_INVALID_SERVERINFO_DATA 388
#define SSL_R_INVALID_SRP_USERNAME 357
#define SSL_R_INVALID_STATUS_RESPONSE 328
#define SSL_R_INVALID_TICKET_KEYS_LENGTH 325
#define SSL_R_LENGTH_MISMATCH 159
#define SSL_R_LENGTH_TOO_LONG 404
#define SSL_R_LENGTH_TOO_SHORT 160
#define SSL_R_LIBRARY_BUG 274
#define SSL_R_LIBRARY_HAS_NO_CIPHERS 161
#define SSL_R_MISSING_DSA_SIGNING_CERT 165
#define SSL_R_MISSING_ECDSA_SIGNING_CERT 381
#define SSL_R_MISSING_RSA_CERTIFICATE 168
#define SSL_R_MISSING_RSA_ENCRYPTING_CERT 169
#define SSL_R_MISSING_RSA_SIGNING_CERT 170
#define SSL_R_MISSING_SIGALGS_EXTENSION 112
#define SSL_R_MISSING_SRP_PARAM 358
#define SSL_R_MISSING_TMP_DH_KEY 171
#define SSL_R_MISSING_TMP_ECDH_KEY 311
#define SSL_R_NO_CERTIFICATES_RETURNED 176
#define SSL_R_NO_CERTIFICATE_ASSIGNED 177
#define SSL_R_NO_CERTIFICATE_SET 179
#define SSL_R_NO_CIPHERS_AVAILABLE 181
#define SSL_R_NO_CIPHERS_SPECIFIED 183
#define SSL_R_NO_CIPHER_MATCH 185
#define SSL_R_NO_CLIENT_CERT_METHOD 331
#define SSL_R_NO_COMPRESSION_SPECIFIED 187
#define SSL_R_NO_GOST_CERTIFICATE_SENT_BY_PEER 330
#define SSL_R_NO_METHOD_SPECIFIED 188
#define SSL_R_NO_PEM_EXTENSIONS 389
#define SSL_R_NO_PRIVATE_KEY_ASSIGNED 190
#define SSL_R_NO_PROTOCOLS_AVAILABLE 191
#define SSL_R_NO_RENEGOTIATION 339
#define SSL_R_NO_REQUIRED_DIGEST 324
#define SSL_R_NO_SHARED_CIPHER 193
#define SSL_R_NO_SHARED_GROUPS 410
#define SSL_R_NO_SHARED_SIGNATURE_ALGORITHMS 376
#define SSL_R_NO_SRTP_PROFILES 359
#define SSL_R_NO_SUITABLE_KEY_SHARE 101
#define SSL_R_NO_SUITABLE_SIGNATURE_ALGORITHM 118
#define SSL_R_NO_VALID_SCTS 216
#define SSL_R_NO_VERIFY_COOKIE_CALLBACK 403
#define SSL_R_NULL_SSL_CTX 195
#define SSL_R_NULL_SSL_METHOD_PASSED 196
#define SSL_R_OLD_SESSION_CIPHER_NOT_RETURNED 197
#define SSL_R_OLD_SESSION_COMPRESSION_ALGORITHM_NOT_RETURNED 344
#define SSL_R_PACKET_LENGTH_TOO_LONG 198
#define SSL_R_PARSE_TLSEXT 227
#define SSL_R_PATH_TOO_LONG 270
#define SSL_R_PEER_DID_NOT_RETURN_A_CERTIFICATE 199
#define SSL_R_PEM_NAME_BAD_PREFIX 391
#define SSL_R_PEM_NAME_TOO_SHORT 392
#define SSL_R_PIPELINE_FAILURE 406
#define SSL_R_PROTOCOL_IS_SHUTDOWN 207
#define SSL_R_PSK_IDENTITY_NOT_FOUND 223
#define SSL_R_PSK_NO_CLIENT_CB 224
#define SSL_R_PSK_NO_SERVER_CB 225
#define SSL_R_READ_BIO_NOT_SET 211
#define SSL_R_READ_TIMEOUT_EXPIRED 312
#define SSL_R_RECORD_LENGTH_MISMATCH 213
#define SSL_R_RECORD_TOO_SMALL 298
#define SSL_R_RENEGOTIATE_EXT_TOO_LONG 335
#define SSL_R_RENEGOTIATION_ENCODING_ERR 336
#define SSL_R_RENEGOTIATION_MISMATCH 337
#define SSL_R_REQUIRED_CIPHER_MISSING 215
#define SSL_R_REQUIRED_COMPRESSION_ALGORITHM_MISSING 342
#define SSL_R_SCSV_RECEIVED_WHEN_RENEGOTIATING 345
#define SSL_R_SCT_VERIFICATION_FAILED 208
#define SSL_R_SERVERHELLO_TLSEXT 275
#define SSL_R_SESSION_ID_CONTEXT_UNINITIALIZED 277
#define SSL_R_SHUTDOWN_WHILE_IN_INIT 407
#define SSL_R_SIGNATURE_ALGORITHMS_ERROR 360
#define SSL_R_SIGNATURE_FOR_NON_SIGNING_CERTIFICATE 220
#define SSL_R_SRP_A_CALC 361
#define SSL_R_SRTP_COULD_NOT_ALLOCATE_PROFILES 362
#define SSL_R_SRTP_PROTECTION_PROFILE_LIST_TOO_LONG 363
#define SSL_R_SRTP_UNKNOWN_PROTECTION_PROFILE 364
#define SSL_R_SSL3_EXT_INVALID_SERVERNAME 319
#define SSL_R_SSL3_EXT_INVALID_SERVERNAME_TYPE 320
#define SSL_R_SSL3_SESSION_ID_TOO_LONG 300
#define SSL_R_SSLV3_ALERT_BAD_CERTIFICATE 1042
#define SSL_R_SSLV3_ALERT_BAD_RECORD_MAC 1020
#define SSL_R_SSLV3_ALERT_CERTIFICATE_EXPIRED 1045
#define SSL_R_SSLV3_ALERT_CERTIFICATE_REVOKED 1044
#define SSL_R_SSLV3_ALERT_CERTIFICATE_UNKNOWN 1046
#define SSL_R_SSLV3_ALERT_DECOMPRESSION_FAILURE 1030
#define SSL_R_SSLV3_ALERT_HANDSHAKE_FAILURE 1040
#define SSL_R_SSLV3_ALERT_ILLEGAL_PARAMETER 1047
#define SSL_R_SSLV3_ALERT_NO_CERTIFICATE 1041
#define SSL_R_SSLV3_ALERT_UNEXPECTED_MESSAGE 1010
#define SSL_R_SSLV3_ALERT_UNSUPPORTED_CERTIFICATE 1043
#define SSL_R_SSL_COMMAND_SECTION_EMPTY 117
#define SSL_R_SSL_COMMAND_SECTION_NOT_FOUND 125
#define SSL_R_SSL_CTX_HAS_NO_DEFAULT_SSL_VERSION 228
#define SSL_R_SSL_HANDSHAKE_FAILURE 229
#define SSL_R_SSL_LIBRARY_HAS_NO_CIPHERS 230
#define SSL_R_SSL_NEGATIVE_LENGTH 372
#define SSL_R_SSL_SECTION_EMPTY 126
#define SSL_R_SSL_SECTION_NOT_FOUND 136
#define SSL_R_SSL_SESSION_ID_CALLBACK_FAILED 301
#define SSL_R_SSL_SESSION_ID_CONFLICT 302
#define SSL_R_SSL_SESSION_ID_CONTEXT_TOO_LONG 273
#define SSL_R_SSL_SESSION_ID_HAS_BAD_LENGTH 303
#define SSL_R_SSL_SESSION_ID_TOO_LONG 408
#define SSL_R_SSL_SESSION_VERSION_MISMATCH 210
#define SSL_R_STILL_IN_INIT 121
#define SSL_R_TLSV1_ALERT_ACCESS_DENIED 1049
#define SSL_R_TLSV1_ALERT_DECODE_ERROR 1050
#define SSL_R_TLSV1_ALERT_DECRYPTION_FAILED 1021
#define SSL_R_TLSV1_ALERT_DECRYPT_ERROR 1051
#define SSL_R_TLSV1_ALERT_EXPORT_RESTRICTION 1060
#define SSL_R_TLSV1_ALERT_INAPPROPRIATE_FALLBACK 1086
#define SSL_R_TLSV1_ALERT_INSUFFICIENT_SECURITY 1071
#define SSL_R_TLSV1_ALERT_INTERNAL_ERROR 1080
#define SSL_R_TLSV1_ALERT_NO_RENEGOTIATION 1100
#define SSL_R_TLSV1_ALERT_PROTOCOL_VERSION 1070
#define SSL_R_TLSV1_ALERT_RECORD_OVERFLOW 1022
#define SSL_R_TLSV1_ALERT_UNKNOWN_CA 1048
#define SSL_R_TLSV1_ALERT_USER_CANCELLED 1090
#define SSL_R_TLSV1_BAD_CERTIFICATE_HASH_VALUE 1114
#define SSL_R_TLSV1_BAD_CERTIFICATE_STATUS_RESPONSE 1113
#define SSL_R_TLSV1_CERTIFICATE_UNOBTAINABLE 1111
#define SSL_R_TLSV1_UNRECOGNIZED_NAME 1112
#define SSL_R_TLSV1_UNSUPPORTED_EXTENSION 1110
#define SSL_R_TLS_HEARTBEAT_PEER_DOESNT_ACCEPT 365
#define SSL_R_TLS_HEARTBEAT_PENDING 366
#define SSL_R_TLS_ILLEGAL_EXPORTER_LABEL 367
#define SSL_R_TLS_INVALID_ECPOINTFORMAT_LIST 157
#define SSL_R_TOO_MANY_KEY_UPDATES 132
#define SSL_R_TOO_MANY_WARN_ALERTS 409
#define SSL_R_UNABLE_TO_FIND_ECDH_PARAMETERS 314
#define SSL_R_UNABLE_TO_FIND_PUBLIC_KEY_PARAMETERS 239
#define SSL_R_UNABLE_TO_LOAD_SSL3_MD5_ROUTINES 242
#define SSL_R_UNABLE_TO_LOAD_SSL3_SHA1_ROUTINES 243
#define SSL_R_UNEXPECTED_MESSAGE 244
#define SSL_R_UNEXPECTED_RECORD 245
#define SSL_R_UNINITIALIZED 276
#define SSL_R_UNKNOWN_ALERT_TYPE 246
#define SSL_R_UNKNOWN_CERTIFICATE_TYPE 247
#define SSL_R_UNKNOWN_CIPHER_RETURNED 248
#define SSL_R_UNKNOWN_CIPHER_TYPE 249
#define SSL_R_UNKNOWN_CMD_NAME 386
#define SSL_R_UNKNOWN_COMMAND 139
#define SSL_R_UNKNOWN_DIGEST 368
#define SSL_R_UNKNOWN_KEY_EXCHANGE_TYPE 250
#define SSL_R_UNKNOWN_PKEY_TYPE 251
#define SSL_R_UNKNOWN_PROTOCOL 252
#define SSL_R_UNKNOWN_SSL_VERSION 254
#define SSL_R_UNKNOWN_STATE 255
#define SSL_R_UNSAFE_LEGACY_RENEGOTIATION_DISABLED 338
#define SSL_R_UNSUPPORTED_COMPRESSION_ALGORITHM 257
#define SSL_R_UNSUPPORTED_ELLIPTIC_CURVE 315
#define SSL_R_UNSUPPORTED_PROTOCOL 258
#define SSL_R_UNSUPPORTED_SSL_VERSION 259
#define SSL_R_UNSUPPORTED_STATUS_TYPE 329
#define SSL_R_USE_SRTP_NOT_NEGOTIATED 369
#define SSL_R_VERSION_TOO_HIGH 166
#define SSL_R_VERSION_TOO_LOW 396
#define SSL_R_WRONG_CERTIFICATE_TYPE 383
#define SSL_R_WRONG_CIPHER_RETURNED 261
#define SSL_R_WRONG_CURVE 378
#define SSL_R_WRONG_SIGNATURE_LENGTH 264
#define SSL_R_WRONG_SIGNATURE_SIZE 265
#define SSL_R_WRONG_SIGNATURE_TYPE 370
#define SSL_R_WRONG_SSL_VERSION 266
#define SSL_R_WRONG_VERSION_NUMBER 267
#define SSL_R_X509_LIB 268
#define SSL_R_X509_VERIFICATION_SETUP_PROBLEMS 269
Typedefs
typedef struct tls_sigalgs_st TLS_SIGALGS
typedef int(* tls_session_ticket_ext_cb_fn) (SSL *s, const unsigned char *data, int len, void *arg)
typedef int(* tls_session_secret_cb_fn) (SSL *s, void *secret, int *secret_len, STACK_OF(SSL_CIPHER) *peer_ciphers, const SSL_CIPHER **cipher, void *arg)
typedef int(* custom_ext_add_cb) (SSL *s, unsigned int ext_type, const unsigned char **out, size_t *outlen, int *al, void *add_arg)
typedef void(* custom_ext_free_cb) (SSL *s, unsigned int ext_type, const unsigned char *out, void *add_arg)
typedef int(* custom_ext_parse_cb) (SSL *s, unsigned int ext_type, const unsigned char *in, size_t inlen, int *al, void *parse_arg)
typedef int(* SSL_verify_cb) (int preverify_ok, X509_STORE_CTX *x509_ctx)
typedef int(* GEN_SESSION_CB) (const SSL *ssl, unsigned char *id, unsigned int *id_len)
typedef int(* SSL_CTX_npn_advertised_cb_func) (SSL *ssl, const unsigned char **out, unsigned int *outlen, void *arg)
typedef int(* SSL_CTX_npn_select_cb_func) (SSL *s, unsigned char **out, unsigned char *outlen, const unsigned char *in, unsigned int inlen, void *arg)
typedef int(* SSL_CTX_alpn_select_cb_func) (SSL *ssl, const unsigned char **out, unsigned char *outlen, const unsigned char *in, unsigned int inlen, void *arg)
typedef unsigned int(* SSL_psk_client_cb_func) (SSL *ssl, const char *hint, char *identity, unsigned int max_identity_len, unsigned char *psk, unsigned int max_psk_len)
typedef unsigned int(* SSL_psk_server_cb_func) (SSL *ssl, const char *identity, unsigned char *psk, unsigned int max_psk_len)
typedef void(* SSL_CTX_keylog_cb_func) (const SSL *ssl, const char *line)
typedef int(* ssl_ct_validation_cb) (const CT_POLICY_EVAL_CTX *ctx, const STACK_OF(SCT) *scts, void *arg)
Enumerations
enum OSSL_HANDSHAKE_STATE {
TLS_ST_BEFORE, TLS_ST_OK, DTLS_ST_CR_HELLO_VERIFY_REQUEST, TLS_ST_CR_SRVR_HELLO,
TLS_ST_CR_CERT, TLS_ST_CR_CERT_STATUS, TLS_ST_CR_KEY_EXCH, TLS_ST_CR_CERT_REQ,
TLS_ST_CR_SRVR_DONE, TLS_ST_CR_SESSION_TICKET, TLS_ST_CR_CHANGE, TLS_ST_CR_FINISHED,
TLS_ST_CW_CLNT_HELLO, TLS_ST_CW_CERT, TLS_ST_CW_KEY_EXCH, TLS_ST_CW_CERT_VRFY,
TLS_ST_CW_CHANGE, TLS_ST_CW_NEXT_PROTO, TLS_ST_CW_FINISHED, TLS_ST_SW_HELLO_REQ,
TLS_ST_SR_CLNT_HELLO, DTLS_ST_SW_HELLO_VERIFY_REQUEST, TLS_ST_SW_SRVR_HELLO, TLS_ST_SW_CERT,
TLS_ST_SW_KEY_EXCH, TLS_ST_SW_CERT_REQ, TLS_ST_SW_SRVR_DONE, TLS_ST_SR_CERT,
TLS_ST_SR_KEY_EXCH, TLS_ST_SR_CERT_VRFY, TLS_ST_SR_NEXT_PROTO, TLS_ST_SR_CHANGE,
TLS_ST_SR_FINISHED, TLS_ST_SW_SESSION_TICKET, TLS_ST_SW_CERT_STATUS, TLS_ST_SW_CHANGE,
TLS_ST_SW_FINISHED, TLS_ST_SW_ENCRYPTED_EXTENSIONS, TLS_ST_CR_ENCRYPTED_EXTENSIONS, TLS_ST_CR_CERT_VRFY,
TLS_ST_SW_CERT_VRFY, TLS_ST_CR_HELLO_REQ, TLS_ST_SW_HELLO_RETRY_REQUEST, TLS_ST_CR_HELLO_RETRY_REQUEST,
TLS_ST_SW_KEY_UPDATE, TLS_ST_CW_KEY_UPDATE, TLS_ST_SR_KEY_UPDATE, TLS_ST_CR_KEY_UPDATE
}
enum { SSL_CT_VALIDATION_PERMISSIVE = 0, SSL_CT_VALIDATION_STRICT }
Functions
STACK_OF (SSL_CIPHER)
STACK_OF (SSL_COMP)
unsigned long SSL_CTX_get_options (const SSL_CTX *ctx)
unsigned long SSL_get_options (const SSL *s)
unsigned long SSL_CTX_clear_options (SSL_CTX *ctx, unsigned long op)
unsigned long SSL_clear_options (SSL *s, unsigned long op)
unsigned long SSL_CTX_set_options (SSL_CTX *ctx, unsigned long op)
unsigned long SSL_set_options (SSL *s, unsigned long op)
void SSL_CTX_set_msg_callback (SSL_CTX *ctx, void(*cb)(int write_p, int version, int content_type, const void *buf, size_t len, SSL *ssl, void *arg))
void SSL_set_msg_callback (SSL *ssl, void(*cb)(int write_p, int version, int content_type, const void *buf, size_t len, SSL *ssl, void *arg))
__owur int SSL_SRP_CTX_init (SSL *s)
__owur int SSL_CTX_SRP_CTX_init (SSL_CTX *ctx)
int SSL_SRP_CTX_free (SSL *ctx)
int SSL_CTX_SRP_CTX_free (SSL_CTX *ctx)
__owur int SSL_srp_server_param_with_username (SSL *s, int *ad)
__owur int SRP_Calc_A_param (SSL *s)
LHASH_OF (SSL_SESSION) *SSL_CTX_sessions(SSL_CTX *ctx)
void SSL_CTX_sess_set_new_cb (SSL_CTX *ctx, int(*new_session_cb)(struct ssl_st *ssl, SSL_SESSION *sess))
void SSL_CTX_sess_set_remove_cb (SSL_CTX *ctx, void(*remove_session_cb)(struct ssl_ctx_st *ctx, SSL_SESSION *sess))
void SSL_CTX_sess_set_get_cb (SSL_CTX *ctx, SSL_SESSION *(*get_session_cb)(struct ssl_st *ssl, const unsigned char *data, int len, int *copy))
void SSL_CTX_set_info_callback (SSL_CTX *ctx, void(*cb)(const SSL *ssl, int type, int val))
void SSL_CTX_set_client_cert_cb (SSL_CTX *ctx, int(*client_cert_cb)(SSL *ssl, X509 **x509, EVP_PKEY **pkey))
__owur int SSL_CTX_set_client_cert_engine (SSL_CTX *ctx, ENGINE *e)
void SSL_CTX_set_cookie_generate_cb (SSL_CTX *ctx, int(*app_gen_cookie_cb)(SSL *ssl, unsigned char *cookie, unsigned int *cookie_len))
void SSL_CTX_set_cookie_verify_cb (SSL_CTX *ctx, int(*app_verify_cookie_cb)(SSL *ssl, const unsigned char *cookie, unsigned int cookie_len))
void SSL_CTX_set_next_protos_advertised_cb (SSL_CTX *s, SSL_CTX_npn_advertised_cb_func cb, void *arg)
void SSL_CTX_set_next_proto_select_cb (SSL_CTX *s, SSL_CTX_npn_select_cb_func cb, void *arg)
void SSL_get0_next_proto_negotiated (const SSL *s, const unsigned char **data, unsigned *len)
__owur int SSL_select_next_proto (unsigned char **out, unsigned char *outlen, const unsigned char *in, unsigned int inlen, const unsigned char *client, unsigned int client_len)
__owur int SSL_CTX_set_alpn_protos (SSL_CTX *ctx, const unsigned char *protos, unsigned int protos_len)
__owur int SSL_set_alpn_protos (SSL *ssl, const unsigned char *protos, unsigned int protos_len)
void SSL_CTX_set_alpn_select_cb (SSL_CTX *ctx, SSL_CTX_alpn_select_cb_func cb, void *arg)
void SSL_get0_alpn_selected (const SSL *ssl, const unsigned char **data, unsigned int *len)
void SSL_CTX_set_psk_client_callback (SSL_CTX *ctx, SSL_psk_client_cb_func cb)
void SSL_set_psk_client_callback (SSL *ssl, SSL_psk_client_cb_func cb)
void SSL_CTX_set_psk_server_callback (SSL_CTX *ctx, SSL_psk_server_cb_func cb)
void SSL_set_psk_server_callback (SSL *ssl, SSL_psk_server_cb_func cb)
__owur int SSL_CTX_use_psk_identity_hint (SSL_CTX *ctx, const char *identity_hint)
__owur int SSL_use_psk_identity_hint (SSL *s, const char *identity_hint)
const char * SSL_get_psk_identity_hint (const SSL *s)
const char * SSL_get_psk_identity (const SSL *s)
__owur int SSL_CTX_has_client_custom_ext (const SSL_CTX *ctx, unsigned int ext_type)
__owur int SSL_CTX_add_client_custom_ext (SSL_CTX *ctx, unsigned int ext_type, custom_ext_add_cb add_cb, custom_ext_free_cb free_cb, void *add_arg, custom_ext_parse_cb parse_cb, void *parse_arg)
__owur int SSL_CTX_add_server_custom_ext (SSL_CTX *ctx, unsigned int ext_type, custom_ext_add_cb add_cb, custom_ext_free_cb free_cb, void *add_arg, custom_ext_parse_cb parse_cb, void *parse_arg)
__owur int SSL_extension_supported (unsigned int ext_type)
void SSL_CTX_set_keylog_callback (SSL_CTX *ctx, SSL_CTX_keylog_cb_func cb)
SSL_CTX_keylog_cb_func SSL_CTX_get_keylog_callback (const SSL_CTX *ctx)
int SSL_in_init (SSL *s)
int SSL_in_before (SSL *s)
int SSL_is_init_finished (SSL *s)
size_t SSL_get_finished (const SSL *s, void *buf, size_t count)
size_t SSL_get_peer_finished (const SSL *s, void *buf, size_t count)
DECLARE_PEM_rw (SSL_SESSION, SSL_SESSION) __owur const BIO_METHOD *BIO_f_ssl(void)
__owur BIO * BIO_new_ssl (SSL_CTX *ctx, int client)
__owur BIO * BIO_new_ssl_connect (SSL_CTX *ctx)
__owur BIO * BIO_new_buffer_ssl_connect (SSL_CTX *ctx)
__owur int BIO_ssl_copy_session_id (BIO *to, BIO *from)
void BIO_ssl_shutdown (BIO *ssl_bio)
__owur int SSL_CTX_set_cipher_list (SSL_CTX *, const char *str)
__owur SSL_CTX * SSL_CTX_new (const SSL_METHOD *meth)
int SSL_CTX_up_ref (SSL_CTX *ctx)
void SSL_CTX_free (SSL_CTX *)
__owur long SSL_CTX_set_timeout (SSL_CTX *ctx, long t)
__owur long SSL_CTX_get_timeout (const SSL_CTX *ctx)
__owur X509_STORE * SSL_CTX_get_cert_store (const SSL_CTX *)
void SSL_CTX_set_cert_store (SSL_CTX *, X509_STORE *)
void SSL_CTX_set1_cert_store (SSL_CTX *, X509_STORE *)
__owur int SSL_want (const SSL *s)
__owur int SSL_clear (SSL *s)
void SSL_CTX_flush_sessions (SSL_CTX *ctx, long tm)
__owur const SSL_CIPHER * SSL_get_current_cipher (const SSL *s)
__owur int SSL_CIPHER_get_bits (const SSL_CIPHER *c, int *alg_bits)
__owur const char * SSL_CIPHER_get_version (const SSL_CIPHER *c)
__owur const char * SSL_CIPHER_get_name (const SSL_CIPHER *c)
__owur uint32_t SSL_CIPHER_get_id (const SSL_CIPHER *c)
__owur int SSL_CIPHER_get_kx_nid (const SSL_CIPHER *c)
__owur int SSL_CIPHER_get_auth_nid (const SSL_CIPHER *c)
__owur int SSL_CIPHER_is_aead (const SSL_CIPHER *c)
__owur int SSL_get_fd (const SSL *s)
__owur int SSL_get_rfd (const SSL *s)
__owur int SSL_get_wfd (const SSL *s)
__owur const char * SSL_get_cipher_list (const SSL *s, int n)
__owur char * SSL_get_shared_ciphers (const SSL *s, char *buf, int len)
__owur int SSL_get_read_ahead (const SSL *s)
__owur int SSL_pending (const SSL *s)
__owur int SSL_has_pending (const SSL *s)
__owur int SSL_set_fd (SSL *s, int fd)
__owur int SSL_set_rfd (SSL *s, int fd)
__owur int SSL_set_wfd (SSL *s, int fd)
void SSL_set0_rbio (SSL *s, BIO *rbio)
void SSL_set0_wbio (SSL *s, BIO *wbio)
void SSL_set_bio (SSL *s, BIO *rbio, BIO *wbio)
__owur BIO * SSL_get_rbio (const SSL *s)
__owur BIO * SSL_get_wbio (const SSL *s)
__owur int SSL_set_cipher_list (SSL *s, const char *str)
void SSL_set_read_ahead (SSL *s, int yes)
__owur int SSL_get_verify_mode (const SSL *s)
__owur int SSL_get_verify_depth (const SSL *s)
__owur SSL_verify_cb SSL_get_verify_callback (const SSL *s)
void SSL_set_verify (SSL *s, int mode, SSL_verify_cb callback)
void SSL_set_verify_depth (SSL *s, int depth)
void SSL_set_cert_cb (SSL *s, int(*cb)(SSL *ssl, void *arg), void *arg)
__owur int SSL_use_RSAPrivateKey (SSL *ssl, RSA *rsa)
__owur int SSL_use_RSAPrivateKey_ASN1 (SSL *ssl, const unsigned char *d, long len)
__owur int SSL_use_PrivateKey (SSL *ssl, EVP_PKEY *pkey)
__owur int SSL_use_PrivateKey_ASN1 (int pk, SSL *ssl, const unsigned char *d, long len)
__owur int SSL_use_certificate (SSL *ssl, X509 *x)
__owur int SSL_use_certificate_ASN1 (SSL *ssl, const unsigned char *d, int len)
__owur int SSL_CTX_use_serverinfo (SSL_CTX *ctx, const unsigned char *serverinfo, size_t serverinfo_length)
__owur int SSL_CTX_use_serverinfo_file (SSL_CTX *ctx, const char *file)
__owur int SSL_use_RSAPrivateKey_file (SSL *ssl, const char *file, int type)
__owur int SSL_use_PrivateKey_file (SSL *ssl, const char *file, int type)
__owur int SSL_use_certificate_file (SSL *ssl, const char *file, int type)
__owur int SSL_CTX_use_RSAPrivateKey_file (SSL_CTX *ctx, const char *file, int type)
__owur int SSL_CTX_use_PrivateKey_file (SSL_CTX *ctx, const char *file, int type)
__owur int SSL_CTX_use_certificate_file (SSL_CTX *ctx, const char *file, int type)
__owur int SSL_CTX_use_certificate_chain_file (SSL_CTX *ctx, const char *file)
__owur int SSL_use_certificate_chain_file (SSL *ssl, const char *file)
__owur STACK_OF (X509_NAME) *SSL_load_client_CA_file(const char *file)
__owur int SSL_add_file_cert_subjects_to_stack (STACK_OF(X509_NAME) *stackCAs, const char *file)
int SSL_add_dir_cert_subjects_to_stack (STACK_OF(X509_NAME) *stackCAs, const char *dir)
__owur const char * SSL_state_string (const SSL *s)
__owur const char * SSL_rstate_string (const SSL *s)
__owur const char * SSL_state_string_long (const SSL *s)
__owur const char * SSL_rstate_string_long (const SSL *s)
__owur long SSL_SESSION_get_time (const SSL_SESSION *s)
__owur long SSL_SESSION_set_time (SSL_SESSION *s, long t)
__owur long SSL_SESSION_get_timeout (const SSL_SESSION *s)
__owur long SSL_SESSION_set_timeout (SSL_SESSION *s, long t)
__owur int SSL_SESSION_get_protocol_version (const SSL_SESSION *s)
__owur const char * SSL_SESSION_get0_hostname (const SSL_SESSION *s)
__owur const SSL_CIPHER * SSL_SESSION_get0_cipher (const SSL_SESSION *s)
__owur int SSL_SESSION_has_ticket (const SSL_SESSION *s)
__owur unsigned long SSL_SESSION_get_ticket_lifetime_hint (const SSL_SESSION *s)
void SSL_SESSION_get0_ticket (const SSL_SESSION *s, const unsigned char **tick, size_t *len)
__owur int SSL_copy_session_id (SSL *to, const SSL *from)
__owur X509 * SSL_SESSION_get0_peer (SSL_SESSION *s)
__owur int SSL_SESSION_set1_id_context (SSL_SESSION *s, const unsigned char *sid_ctx, unsigned int sid_ctx_len)
__owur int SSL_SESSION_set1_id (SSL_SESSION *s, const unsigned char *sid, unsigned int sid_len)
__owur SSL_SESSION * SSL_SESSION_new (void)
const unsigned char * SSL_SESSION_get_id (const SSL_SESSION *s, unsigned int *len)
const unsigned char * SSL_SESSION_get0_id_context (const SSL_SESSION *s, unsigned int *len)
__owur unsigned int SSL_SESSION_get_compress_id (const SSL_SESSION *s)
int SSL_SESSION_print_fp (FILE *fp, const SSL_SESSION *ses)
int SSL_SESSION_print (BIO *fp, const SSL_SESSION *ses)
int SSL_SESSION_print_keylog (BIO *bp, const SSL_SESSION *x)
int SSL_SESSION_up_ref (SSL_SESSION *ses)
void SSL_SESSION_free (SSL_SESSION *ses)
__owur int i2d_SSL_SESSION (SSL_SESSION *in, unsigned char **pp)
__owur int SSL_set_session (SSL *to, SSL_SESSION *session)
__owur int SSL_CTX_add_session (SSL_CTX *s, SSL_SESSION *c)
int SSL_CTX_remove_session (SSL_CTX *, SSL_SESSION *c)
__owur int SSL_CTX_set_generate_session_id (SSL_CTX *, GEN_SESSION_CB)
__owur int SSL_set_generate_session_id (SSL *, GEN_SESSION_CB)
__owur int SSL_has_matching_session_id (const SSL *ssl, const unsigned char *id, unsigned int id_len)
SSL_SESSION * d2i_SSL_SESSION (SSL_SESSION **a, const unsigned char **pp, long length)
__owur STACK_OF (X509) *SSL_get_peer_cert_chain(const SSL *s)
__owur int SSL_CTX_get_verify_mode (const SSL_CTX *ctx)
__owur int SSL_CTX_get_verify_depth (const SSL_CTX *ctx)
__owur SSL_verify_cb SSL_CTX_get_verify_callback (const SSL_CTX *ctx)
void SSL_CTX_set_verify (SSL_CTX *ctx, int mode, SSL_verify_cb callback)
void SSL_CTX_set_verify_depth (SSL_CTX *ctx, int depth)
void SSL_CTX_set_cert_verify_callback (SSL_CTX *ctx, int(*cb)(X509_STORE_CTX *, void *), void *arg)
void SSL_CTX_set_cert_cb (SSL_CTX *c, int(*cb)(SSL *ssl, void *arg), void *arg)
__owur int SSL_CTX_use_RSAPrivateKey (SSL_CTX *ctx, RSA *rsa)
__owur int SSL_CTX_use_RSAPrivateKey_ASN1 (SSL_CTX *ctx, const unsigned char *d, long len)
__owur int SSL_CTX_use_PrivateKey (SSL_CTX *ctx, EVP_PKEY *pkey)
__owur int SSL_CTX_use_PrivateKey_ASN1 (int pk, SSL_CTX *ctx, const unsigned char *d, long len)
__owur int SSL_CTX_use_certificate (SSL_CTX *ctx, X509 *x)
__owur int SSL_CTX_use_certificate_ASN1 (SSL_CTX *ctx, int len, const unsigned char *d)
void SSL_CTX_set_default_passwd_cb (SSL_CTX *ctx, pem_password_cb *cb)
void SSL_CTX_set_default_passwd_cb_userdata (SSL_CTX *ctx, void *u)
pem_password_cb * SSL_CTX_get_default_passwd_cb (SSL_CTX *ctx)
void * SSL_CTX_get_default_passwd_cb_userdata (SSL_CTX *ctx)
void SSL_set_default_passwd_cb (SSL *s, pem_password_cb *cb)
void SSL_set_default_passwd_cb_userdata (SSL *s, void *u)
pem_password_cb * SSL_get_default_passwd_cb (SSL *s)
void * SSL_get_default_passwd_cb_userdata (SSL *s)
__owur int SSL_CTX_check_private_key (const SSL_CTX *ctx)
__owur int SSL_check_private_key (const SSL *ctx)
__owur int SSL_CTX_set_session_id_context (SSL_CTX *ctx, const unsigned char *sid_ctx, unsigned int sid_ctx_len)
SSL * SSL_new (SSL_CTX *ctx)
int SSL_up_ref (SSL *s)
int SSL_is_dtls (const SSL *s)
__owur int SSL_set_session_id_context (SSL *ssl, const unsigned char *sid_ctx, unsigned int sid_ctx_len)
__owur int SSL_CTX_set_purpose (SSL_CTX *s, int purpose)
__owur int SSL_set_purpose (SSL *s, int purpose)
__owur int SSL_CTX_set_trust (SSL_CTX *s, int trust)
__owur int SSL_set_trust (SSL *s, int trust)
__owur int SSL_set1_host (SSL *s, const char *hostname)
__owur int SSL_add1_host (SSL *s, const char *hostname)
__owur const char * SSL_get0_peername (SSL *s)
void SSL_set_hostflags (SSL *s, unsigned int flags)
__owur int SSL_CTX_dane_enable (SSL_CTX *ctx)
__owur int SSL_CTX_dane_mtype_set (SSL_CTX *ctx, const EVP_MD *md, uint8_t mtype, uint8_t ord)
__owur int SSL_dane_enable (SSL *s, const char *basedomain)
__owur int SSL_dane_tlsa_add (SSL *s, uint8_t usage, uint8_t selector, uint8_t mtype, unsigned char *data, size_t dlen)
__owur int SSL_get0_dane_authority (SSL *s, X509 **mcert, EVP_PKEY **mspki)
__owur int SSL_get0_dane_tlsa (SSL *s, uint8_t *usage, uint8_t *selector, uint8_t *mtype, unsigned const char **data, size_t *dlen)
SSL_DANE * SSL_get0_dane (SSL *ssl)
unsigned long SSL_CTX_dane_set_flags (SSL_CTX *ctx, unsigned long flags)
unsigned long SSL_CTX_dane_clear_flags (SSL_CTX *ctx, unsigned long flags)
unsigned long SSL_dane_set_flags (SSL *ssl, unsigned long flags)
unsigned long SSL_dane_clear_flags (SSL *ssl, unsigned long flags)
__owur int SSL_CTX_set1_param (SSL_CTX *ctx, X509_VERIFY_PARAM *vpm)
__owur int SSL_set1_param (SSL *ssl, X509_VERIFY_PARAM *vpm)
__owur X509_VERIFY_PARAM * SSL_CTX_get0_param (SSL_CTX *ctx)
__owur X509_VERIFY_PARAM * SSL_get0_param (SSL *ssl)
int SSL_CTX_set_srp_username (SSL_CTX *ctx, char *name)
int SSL_CTX_set_srp_password (SSL_CTX *ctx, char *password)
int SSL_CTX_set_srp_strength (SSL_CTX *ctx, int strength)
int SSL_CTX_set_srp_client_pwd_callback (SSL_CTX *ctx, char *(*cb)(SSL *, void *))
int SSL_CTX_set_srp_verify_param_callback (SSL_CTX *ctx, int(*cb)(SSL *, void *))
int SSL_CTX_set_srp_username_callback (SSL_CTX *ctx, int(*cb)(SSL *, int *, void *))
int SSL_CTX_set_srp_cb_arg (SSL_CTX *ctx, void *arg)
int SSL_set_srp_server_param (SSL *s, const BIGNUM *N, const BIGNUM *g, BIGNUM *sa, BIGNUM *v, char *info)
int SSL_set_srp_server_param_pw (SSL *s, const char *user, const char *pass, const char *grp)
__owur BIGNUM * SSL_get_srp_g (SSL *s)
__owur BIGNUM * SSL_get_srp_N (SSL *s)
__owur char * SSL_get_srp_username (SSL *s)
__owur char * SSL_get_srp_userinfo (SSL *s)
void SSL_certs_clear (SSL *s)
void SSL_free (SSL *ssl)
__owur int SSL_accept (SSL *ssl)
__owur int SSL_connect (SSL *ssl)
__owur int SSL_read (SSL *ssl, void *buf, int num)
__owur int SSL_read_ex (SSL *ssl, void *buf, size_t num, size_t *readbytes)
__owur int SSL_peek (SSL *ssl, void *buf, int num)
__owur int SSL_peek_ex (SSL *ssl, void *buf, size_t num, size_t *readbytes)
__owur int SSL_write (SSL *ssl, const void *buf, int num)
__owur int SSL_write_ex (SSL *s, const void *buf, size_t num, size_t *written)
long SSL_ctrl (SSL *ssl, int cmd, long larg, void *parg)
long SSL_callback_ctrl (SSL *, int, void(*)(void))
long SSL_CTX_ctrl (SSL_CTX *ctx, int cmd, long larg, void *parg)
long SSL_CTX_callback_ctrl (SSL_CTX *, int, void(*)(void))
__owur int SSL_get_error (const SSL *s, int ret_code)
__owur const char * SSL_get_version (const SSL *s)
__owur int SSL_CTX_set_ssl_version (SSL_CTX *ctx, const SSL_METHOD *meth)
DEPRECATEDIN_1_1_0 (__owur const SSL_METHOD *SSLv3_method(void)) DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *SSLv3_server_method(void)) DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *SSLv3_client_method(void)) __owur const SSL_METHOD *TLS_method(void)
__owur const SSL_METHOD * TLS_server_method (void)
__owur const SSL_METHOD * TLS_client_method (void)
__owur const SSL_METHOD * DTLS_server_method (void)
__owur const SSL_METHOD * DTLS_client_method (void)
__owur size_t DTLS_get_data_mtu (const SSL *s)
__owur int SSL_do_handshake (SSL *s)
int SSL_key_update (SSL *s, int updatetype)
int SSL_get_key_update_type (SSL *s)
int SSL_renegotiate (SSL *s)
int SSL_renegotiate_abbreviated (SSL *s)
__owur int SSL_renegotiate_pending (SSL *s)
int SSL_shutdown (SSL *s)
__owur const SSL_METHOD * SSL_CTX_get_ssl_method (SSL_CTX *ctx)
__owur const SSL_METHOD * SSL_get_ssl_method (SSL *s)
__owur int SSL_set_ssl_method (SSL *s, const SSL_METHOD *method)
__owur const char * SSL_alert_type_string_long (int value)
__owur const char * SSL_alert_type_string (int value)
__owur const char * SSL_alert_desc_string_long (int value)
__owur const char * SSL_alert_desc_string (int value)
void SSL_set_client_CA_list (SSL *s, STACK_OF(X509_NAME) *name_list)
void SSL_CTX_set_client_CA_list (SSL_CTX *ctx, STACK_OF(X509_NAME) *name_list)
__owur int SSL_add_client_CA (SSL *ssl, X509 *x)
__owur int SSL_CTX_add_client_CA (SSL_CTX *ctx, X509 *x)
void SSL_set_connect_state (SSL *s)
void SSL_set_accept_state (SSL *s)
__owur long SSL_get_default_timeout (const SSL *s)
__owur char * SSL_CIPHER_description (const SSL_CIPHER *, char *buf, int size)
__owur SSL * SSL_dup (SSL *ssl)
__owur X509 * SSL_get_certificate (const SSL *ssl)
struct evp_pkey_st * SSL_get_privatekey (const SSL *ssl)
__owur X509 * SSL_CTX_get0_certificate (const SSL_CTX *ctx)
__owur EVP_PKEY * SSL_CTX_get0_privatekey (const SSL_CTX *ctx)
void SSL_CTX_set_quiet_shutdown (SSL_CTX *ctx, int mode)
__owur int SSL_CTX_get_quiet_shutdown (const SSL_CTX *ctx)
void SSL_set_quiet_shutdown (SSL *ssl, int mode)
__owur int SSL_get_quiet_shutdown (const SSL *ssl)
void SSL_set_shutdown (SSL *ssl, int mode)
__owur int SSL_get_shutdown (const SSL *ssl)
__owur int SSL_version (const SSL *ssl)
__owur int SSL_client_version (const SSL *s)
__owur int SSL_CTX_set_default_verify_paths (SSL_CTX *ctx)
__owur int SSL_CTX_set_default_verify_dir (SSL_CTX *ctx)
__owur int SSL_CTX_set_default_verify_file (SSL_CTX *ctx)
__owur int SSL_CTX_load_verify_locations (SSL_CTX *ctx, const char *CAfile, const char *CApath)
__owur SSL_SESSION * SSL_get_session (const SSL *ssl)
__owur SSL_SESSION * SSL_get1_session (SSL *ssl)
__owur SSL_CTX * SSL_get_SSL_CTX (const SSL *ssl)
SSL_CTX * SSL_set_SSL_CTX (SSL *ssl, SSL_CTX *ctx)
void SSL_set_info_callback (SSL *ssl, void(*cb)(const SSL *ssl, int type, int val))
__owur OSSL_HANDSHAKE_STATE SSL_get_state (const SSL *ssl)
void SSL_set_verify_result (SSL *ssl, long v)
__owur long SSL_get_verify_result (const SSL *ssl)
__owur size_t SSL_get_client_random (const SSL *ssl, unsigned char *out, size_t outlen)
__owur size_t SSL_get_server_random (const SSL *ssl, unsigned char *out, size_t outlen)
__owur size_t SSL_SESSION_get_master_key (const SSL_SESSION *ssl, unsigned char *out, size_t outlen)
__owur int SSL_set_ex_data (SSL *ssl, int idx, void *data)
void * SSL_get_ex_data (const SSL *ssl, int idx)
__owur int SSL_SESSION_set_ex_data (SSL_SESSION *ss, int idx, void *data)
void * SSL_SESSION_get_ex_data (const SSL_SESSION *ss, int idx)
__owur int SSL_CTX_set_ex_data (SSL_CTX *ssl, int idx, void *data)
void * SSL_CTX_get_ex_data (const SSL_CTX *ssl, int idx)
__owur int SSL_get_ex_data_X509_STORE_CTX_idx (void)
void SSL_CTX_set_default_read_buffer_len (SSL_CTX *ctx, size_t len)
void SSL_set_default_read_buffer_len (SSL *s, size_t len)
void SSL_CTX_set_tmp_dh_callback (SSL_CTX *ctx, DH *(*dh)(SSL *ssl, int is_export, int keylength))
Set the callback for generating temporary DH keys.
void SSL_set_tmp_dh_callback (SSL *ssl, DH *(*dh)(SSL *ssl, int is_export, int keylength))
__owur const COMP_METHOD * SSL_get_current_compression (SSL *s)
__owur const COMP_METHOD * SSL_get_current_expansion (SSL *s)
__owur const char * SSL_COMP_get_name (const COMP_METHOD *comp)
__owur const char * SSL_COMP_get0_name (const SSL_COMP *comp)
__owur int SSL_COMP_get_id (const SSL_COMP *comp)
__owur int SSL_COMP_add_compression_method (int id, COMP_METHOD *cm)
const SSL_CIPHER * SSL_CIPHER_find (SSL *ssl, const unsigned char *ptr)
int SSL_CIPHER_get_cipher_nid (const SSL_CIPHER *c)
int SSL_CIPHER_get_digest_nid (const SSL_CIPHER *c)
__owur int SSL_set_session_ticket_ext (SSL *s, void *ext_data, int ext_len)
__owur int SSL_set_session_ticket_ext_cb (SSL *s, tls_session_ticket_ext_cb_fn cb, void *arg)
__owur int SSL_set_session_secret_cb (SSL *s, tls_session_secret_cb_fn tls_session_secret_cb, void *arg)
void SSL_CTX_set_not_resumable_session_callback (SSL_CTX *ctx, int(*cb)(SSL *ssl, int is_forward_secure))
void SSL_set_not_resumable_session_callback (SSL *ssl, int(*cb)(SSL *ssl, int is_forward_secure))
__owur int SSL_session_reused (SSL *s)
__owur int SSL_is_server (SSL *s)
__owur __owur SSL_CONF_CTX * SSL_CONF_CTX_new (void)
int SSL_CONF_CTX_finish (SSL_CONF_CTX *cctx)
void SSL_CONF_CTX_free (SSL_CONF_CTX *cctx)
unsigned int SSL_CONF_CTX_set_flags (SSL_CONF_CTX *cctx, unsigned int flags)
__owur unsigned int SSL_CONF_CTX_clear_flags (SSL_CONF_CTX *cctx, unsigned int flags)
__owur int SSL_CONF_CTX_set1_prefix (SSL_CONF_CTX *cctx, const char *pre)
void SSL_CONF_CTX_set_ssl (SSL_CONF_CTX *cctx, SSL *ssl)
void SSL_CONF_CTX_set_ssl_ctx (SSL_CONF_CTX *cctx, SSL_CTX *ctx)
__owur int SSL_CONF_cmd (SSL_CONF_CTX *cctx, const char *cmd, const char *value)
__owur int SSL_CONF_cmd_argv (SSL_CONF_CTX *cctx, int *pargc, char ***pargv)
__owur int SSL_CONF_cmd_value_type (SSL_CONF_CTX *cctx, const char *cmd)
void SSL_add_ssl_module (void)
int SSL_config (SSL *s, const char *name)
int SSL_CTX_config (SSL_CTX *ctx, const char *name)
void SSL_trace (int write_p, int version, int content_type, const void *buf, size_t len, SSL *ssl, void *arg)
__owur const char * SSL_CIPHER_standard_name (const SSL_CIPHER *c)
int DTLSv1_listen (SSL *s, BIO_ADDR *client)
int SSL_set_ct_validation_callback (SSL *s, ssl_ct_validation_cb callback, void *arg)
int SSL_CTX_set_ct_validation_callback (SSL_CTX *ctx, ssl_ct_validation_cb callback, void *arg)
int SSL_enable_ct (SSL *s, int validation_mode)
int SSL_CTX_enable_ct (SSL_CTX *ctx, int validation_mode)
int SSL_ct_is_enabled (const SSL *s)
int SSL_CTX_ct_is_enabled (const SSL_CTX *ctx)
const STACK_OF (SCT) *SSL_get0_peer_scts(SSL *s)
int SSL_CTX_set_default_ctlog_list_file (SSL_CTX *ctx)
int SSL_CTX_set_ctlog_list_file (SSL_CTX *ctx, const char *path)
void SSL_CTX_set0_ctlog_store (SSL_CTX *ctx, CTLOG_STORE *logs)
const CTLOG_STORE * SSL_CTX_get0_ctlog_store (const SSL_CTX *ctx)
void SSL_set_security_level (SSL *s, int level)
__owur int SSL_get_security_level (const SSL *s)
void SSL_set_security_callback (SSL *s, int(*cb)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex))
void SSL_set0_security_ex_data (SSL *s, void *ex)
__owur void * SSL_get0_security_ex_data (const SSL *s)
void SSL_CTX_set_security_level (SSL_CTX *ctx, int level)
__owur int SSL_CTX_get_security_level (const SSL_CTX *ctx)
void SSL_CTX_set_security_callback (SSL_CTX *ctx, int(*cb)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex))
void SSL_CTX_set0_security_ex_data (SSL_CTX *ctx, void *ex)
__owur void * SSL_CTX_get0_security_ex_data (const SSL_CTX *ctx)
int OPENSSL_init_ssl (uint64_t opts, const OPENSSL_INIT_SETTINGS *settings)
__owur const struct openssl_ssl_test_functions * SSL_test_functions (void)
int ERR_load_SSL_strings (void)
Variables
int(*)(struct ssl_st *ssl, SSL_SESSION *sess) SSL_CTX_sess_get_new_cb (SSL_CTX *ctx)
void(*)(struct ssl_ctx_st *ctx, SSL_SESSION *sess) SSL_CTX_sess_get_remove_cb (SSL_CTX *ctx)
SSL_SESSION *(*)(struct ssl_st *ssl, const unsigned char *data, int len, int *copy) SSL_CTX_sess_get_get_cb (SSL_CTX *ctx)
void(*)(const SSL *ssl, int type, int val) SSL_CTX_get_info_callback (SSL_CTX *ctx)
int(*)(SSL *ssl, X509 **x509, EVP_PKEY **pkey) SSL_CTX_get_client_cert_cb (SSL_CTX *ctx)
void(*)(const SSL *ssl, int type, int val) SSL_get_info_callback (const SSL *ssl)
int(*)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex) SSL_get_security_callback (const SSL *s)
int(*)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex) SSL_CTX_get_security_callback (const SSL_CTX *ctx)
const char SSL_version_str []
Macro Definition Documentation
CERT_PKEY_CA_PARAM
#define CERT_PKEY_CA_PARAM 0x80
Definition at line 458 of file ssl.h.
CERT_PKEY_CA_SIGNATURE
#define CERT_PKEY_CA_SIGNATURE 0x20
Definition at line 454 of file ssl.h.
CERT_PKEY_CERT_TYPE
#define CERT_PKEY_CERT_TYPE 0x400
Definition at line 464 of file ssl.h.
CERT_PKEY_EE_PARAM
#define CERT_PKEY_EE_PARAM 0x40
Definition at line 456 of file ssl.h.
CERT_PKEY_EE_SIGNATURE
#define CERT_PKEY_EE_SIGNATURE 0x10
Definition at line 452 of file ssl.h.
CERT_PKEY_EXPLICIT_SIGN
#define CERT_PKEY_EXPLICIT_SIGN 0x100
Definition at line 460 of file ssl.h.
CERT_PKEY_ISSUER_NAME
#define CERT_PKEY_ISSUER_NAME 0x200
Definition at line 462 of file ssl.h.
CERT_PKEY_SIGN
#define CERT_PKEY_SIGN 0x2
Definition at line 450 of file ssl.h.
Referenced by ssl_set_masks().
CERT_PKEY_SUITEB
#define CERT_PKEY_SUITEB 0x800
Definition at line 466 of file ssl.h.
CERT_PKEY_VALID
#define CERT_PKEY_VALID 0x1
Definition at line 448 of file ssl.h.
Referenced by ssl_set_masks().
d2i_SSL_SESSION_bio
#define d2i_SSL_SESSION_bio (bp, s_id) ASN1_d2i_bio_of(SSL_SESSION,SSL_SESSION_new,d2i_SSL_SESSION,bp,s_id)
Definition at line 977 of file ssl.h.
DTLS_CTRL_GET_LINK_MIN_MTU
#define DTLS_CTRL_GET_LINK_MIN_MTU 121
DTLS_CTRL_GET_TIMEOUT
#define DTLS_CTRL_GET_TIMEOUT 73
DTLS_CTRL_HANDLE_TIMEOUT
#define DTLS_CTRL_HANDLE_TIMEOUT 74
DTLS_CTRL_SET_LINK_MTU
#define DTLS_CTRL_SET_LINK_MTU 120
DTLS_get_link_min_mtu
#define DTLS_get_link_min_mtu (ssl) SSL_ctrl((ssl),DTLS_CTRL_GET_LINK_MIN_MTU,0,NULL)
Definition at line 510 of file ssl.h.
DTLS_set_link_mtu
#define DTLS_set_link_mtu (ssl, mtu) SSL_ctrl((ssl),DTLS_CTRL_SET_LINK_MTU,(mtu),NULL)
Definition at line 508 of file ssl.h.
DTLSv1_get_timeout
#define DTLSv1_get_timeout (ssl, arg) SSL_ctrl(ssl,DTLS_CTRL_GET_TIMEOUT,0, (void *)arg)
DTLSv1_handle_timeout
#define DTLSv1_handle_timeout (ssl) SSL_ctrl(ssl,DTLS_CTRL_HANDLE_TIMEOUT,0, NULL)
i2d_SSL_SESSION_bio
#define i2d_SSL_SESSION_bio (bp, s_id) ASN1_i2d_bio_of(SSL_SESSION,i2d_SSL_SESSION,bp,s_id)
Definition at line 978 of file ssl.h.
OpenSSL_add_ssl_algorithms
#define OpenSSL_add_ssl_algorithms () SSL_library_init()
Definition at line 958 of file ssl.h.
OPENSSL_INIT_LOAD_SSL_STRINGS
#define OPENSSL_INIT_LOAD_SSL_STRINGS 0x00200000L
Definition at line 2064 of file ssl.h.
Referenced by SSL_SESSION_new().
OPENSSL_INIT_NO_LOAD_SSL_STRINGS
#define OPENSSL_INIT_NO_LOAD_SSL_STRINGS 0x00100000L
Definition at line 2063 of file ssl.h.
OPENSSL_INIT_SSL_DEFAULT
#define OPENSSL_INIT_SSL_DEFAULT (OPENSSL_INIT_LOAD_SSL_STRINGS | OPENSSL_INIT_LOAD_CRYPTO_STRINGS)
Definition at line 2066 of file ssl.h.
OPENSSL_NPN_NEGOTIATED
#define OPENSSL_NPN_NEGOTIATED 1
Definition at line 692 of file ssl.h.
OPENSSL_NPN_NO_OVERLAP
#define OPENSSL_NPN_NO_OVERLAP 2
Definition at line 693 of file ssl.h.
OPENSSL_NPN_UNSUPPORTED
#define OPENSSL_NPN_UNSUPPORTED 0
Definition at line 691 of file ssl.h.
PSK_MAX_IDENTITY_LEN
#define PSK_MAX_IDENTITY_LEN 128
Definition at line 716 of file ssl.h.
Referenced by SSL_CTX_use_psk_identity_hint(), and SSL_use_psk_identity_hint().
PSK_MAX_PSK_LEN
#define PSK_MAX_PSK_LEN 256
Definition at line 717 of file ssl.h.
SSL_AD_ACCESS_DENIED
#define SSL_AD_ACCESS_DENIED TLS1_AD_ACCESS_DENIED
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_BAD_CERTIFICATE
#define SSL_AD_BAD_CERTIFICATE SSL3_AD_BAD_CERTIFICATE
Referenced by ssl3_alert_code(), ssl_verify_alarm_type(), and tls1_alert_code().
SSL_AD_BAD_CERTIFICATE_HASH_VALUE
#define SSL_AD_BAD_CERTIFICATE_HASH_VALUE TLS1_AD_BAD_CERTIFICATE_HASH_VALUE
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_BAD_CERTIFICATE_STATUS_RESPONSE
#define SSL_AD_BAD_CERTIFICATE_STATUS_RESPONSE TLS1_AD_BAD_CERTIFICATE_STATUS_RESPONSE
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_BAD_RECORD_MAC
#define SSL_AD_BAD_RECORD_MAC SSL3_AD_BAD_RECORD_MAC
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_CERTIFICATE_EXPIRED
#define SSL_AD_CERTIFICATE_EXPIRED SSL3_AD_CERTIFICATE_EXPIRED
Referenced by ssl3_alert_code(), ssl_verify_alarm_type(), and tls1_alert_code().
SSL_AD_CERTIFICATE_REVOKED
#define SSL_AD_CERTIFICATE_REVOKED SSL3_AD_CERTIFICATE_REVOKED
Referenced by ssl3_alert_code(), ssl_verify_alarm_type(), and tls1_alert_code().
SSL_AD_CERTIFICATE_UNKNOWN
#define SSL_AD_CERTIFICATE_UNKNOWN SSL3_AD_CERTIFICATE_UNKNOWN
Referenced by ssl3_alert_code(), ssl_verify_alarm_type(), and tls1_alert_code().
SSL_AD_CERTIFICATE_UNOBTAINABLE
#define SSL_AD_CERTIFICATE_UNOBTAINABLE TLS1_AD_CERTIFICATE_UNOBTAINABLE
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_CLOSE_NOTIFY
#define SSL_AD_CLOSE_NOTIFY SSL3_AD_CLOSE_NOTIFY
Referenced by ssl3_alert_code(), SSL_get_error(), and tls1_alert_code().
SSL_AD_DECODE_ERROR
#define SSL_AD_DECODE_ERROR TLS1_AD_DECODE_ERROR
Referenced by ssl3_alert_code(), tls1_alert_code(), and tls_process_new_session_ticket().
SSL_AD_DECOMPRESSION_FAILURE
#define SSL_AD_DECOMPRESSION_FAILURE SSL3_AD_DECOMPRESSION_FAILURE
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_DECRYPT_ERROR
#define SSL_AD_DECRYPT_ERROR TLS1_AD_DECRYPT_ERROR
Referenced by ssl3_alert_code(), ssl_verify_alarm_type(), and tls1_alert_code().
SSL_AD_DECRYPTION_FAILED
#define SSL_AD_DECRYPTION_FAILED TLS1_AD_DECRYPTION_FAILED
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_EXPORT_RESTRICTION
#define SSL_AD_EXPORT_RESTRICTION TLS1_AD_EXPORT_RESTRICTION
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_HANDSHAKE_FAILURE
#define SSL_AD_HANDSHAKE_FAILURE SSL3_AD_HANDSHAKE_FAILURE
Referenced by ssl3_alert_code(), ssl3_send_alert(), ssl_verify_alarm_type(), tls1_alert_code(), tls_construct_client_hello(), tls_post_process_client_hello(), tls_process_initial_server_flight(), and tls_setup_handshake().
SSL_AD_ILLEGAL_PARAMETER
#define SSL_AD_ILLEGAL_PARAMETER SSL3_AD_ILLEGAL_PARAMETER
Referenced by ssl3_alert_code(), tls1_alert_code(), tls1_set_server_sigalgs(), tls_get_message_header(), and tls_process_key_update().
SSL_AD_INAPPROPRIATE_FALLBACK
#define SSL_AD_INAPPROPRIATE_FALLBACK TLS1_AD_INAPPROPRIATE_FALLBACK
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_INSUFFICIENT_SECURITY
#define SSL_AD_INSUFFICIENT_SECURITY TLS1_AD_INSUFFICIENT_SECURITY
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_INTERNAL_ERROR
#define SSL_AD_INTERNAL_ERROR TLS1_AD_INTERNAL_ERROR
Referenced by dtls_construct_change_cipher_spec(), ssl3_alert_code(), ssl3_output_cert_chain(), SSL_srp_server_param_with_username(), ssl_verify_alarm_type(), tls1_alert_code(), tls1_set_server_sigalgs(), tls_client_key_exchange_post_work(), tls_collect_extensions(), tls_construct_cert_status(), tls_construct_change_cipher_spec(), tls_construct_client_certificate(), tls_construct_extensions(), tls_construct_finished(), tls_construct_key_update(), tls_construct_next_proto(), tls_construct_server_certificate(), tls_construct_server_done(), tls_construct_server_hello(), tls_construct_server_key_exchange(), tls_construct_stoc_key_share(), tls_parse_stoc_key_share(), tls_prepare_client_certificate(), tls_process_cert_verify(), tls_process_client_certificate(), tls_process_client_hello(), tls_process_finished(), and tls_process_server_done().
SSL_AD_MISSING_EXTENSION
#define SSL_AD_MISSING_EXTENSION TLS13_AD_MISSING_EXTENSION
Referenced by tls13_alert_code().
SSL_AD_NO_APPLICATION_PROTOCOL
#define SSL_AD_NO_APPLICATION_PROTOCOL TLS1_AD_NO_APPLICATION_PROTOCOL
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_NO_CERTIFICATE
#define SSL_AD_NO_CERTIFICATE SSL3_AD_NO_CERTIFICATE
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_NO_RENEGOTIATION
#define SSL_AD_NO_RENEGOTIATION TLS1_AD_NO_RENEGOTIATION
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_PROTOCOL_VERSION
#define SSL_AD_PROTOCOL_VERSION TLS1_AD_PROTOCOL_VERSION
Referenced by ssl3_alert_code(), ssl3_send_alert(), and tls1_alert_code().
SSL_AD_REASON_OFFSET
#define SSL_AD_REASON_OFFSET
Value:
1000/* offset to get SSL_R_... value
                                              * from SSL_AD_... */
SSL_AD_RECORD_OVERFLOW
#define SSL_AD_RECORD_OVERFLOW TLS1_AD_RECORD_OVERFLOW
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_UNEXPECTED_MESSAGE
#define SSL_AD_UNEXPECTED_MESSAGE SSL3_AD_UNEXPECTED_MESSAGE
Referenced by ssl3_alert_code(), tls1_alert_code(), tls_get_message_header(), and tls_process_finished().
SSL_AD_UNKNOWN_CA
#define SSL_AD_UNKNOWN_CA TLS1_AD_UNKNOWN_CA
Referenced by ssl3_alert_code(), ssl_verify_alarm_type(), and tls1_alert_code().
SSL_AD_UNKNOWN_PSK_IDENTITY
#define SSL_AD_UNKNOWN_PSK_IDENTITY TLS1_AD_UNKNOWN_PSK_IDENTITY
Referenced by ssl3_alert_code(), SSL_srp_server_param_with_username(), and tls1_alert_code().
SSL_AD_UNRECOGNIZED_NAME
#define SSL_AD_UNRECOGNIZED_NAME TLS1_AD_UNRECOGNIZED_NAME
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_AD_UNSUPPORTED_CERTIFICATE
#define SSL_AD_UNSUPPORTED_CERTIFICATE SSL3_AD_UNSUPPORTED_CERTIFICATE
Referenced by ssl3_alert_code(), ssl_verify_alarm_type(), and tls1_alert_code().
SSL_AD_UNSUPPORTED_EXTENSION
#define SSL_AD_UNSUPPORTED_EXTENSION TLS1_AD_UNSUPPORTED_EXTENSION
Referenced by ssl3_alert_code(), tls1_alert_code(), tls_parse_stoc_alpn(), and tls_parse_stoc_npn().
SSL_AD_USER_CANCELLED
#define SSL_AD_USER_CANCELLED TLS1_AD_USER_CANCELLED
Referenced by ssl3_alert_code(), and tls1_alert_code().
SSL_add0_chain_cert
#define SSL_add0_chain_cert (ctx, x509) SSL_ctrl(ctx,SSL_CTRL_CHAIN_CERT,0,(char *)x509)
SSL_add1_chain_cert
#define SSL_add1_chain_cert (ctx, x509) SSL_ctrl(ctx,SSL_CTRL_CHAIN_CERT,1,(char *)x509)
SSL_ASYNC_NO_JOBS
#define SSL_ASYNC_NO_JOBS 6
Definition at line 766 of file ssl.h.
SSL_ASYNC_PAUSED
#define SSL_ASYNC_PAUSED 5
Definition at line 765 of file ssl.h.
SSL_build_cert_chain
#define SSL_build_cert_chain (s, flags) SSL_ctrl(s,SSL_CTRL_BUILD_CERT_CHAIN, flags, NULL)
SSL_BUILD_CHAIN_FLAG_CHECK
#define SSL_BUILD_CHAIN_FLAG_CHECK 0x4
Definition at line 440 of file ssl.h.
Referenced by ssl_build_cert_chain().
SSL_BUILD_CHAIN_FLAG_CLEAR_ERROR
#define SSL_BUILD_CHAIN_FLAG_CLEAR_ERROR 0x10
Definition at line 444 of file ssl.h.
Referenced by ssl_build_cert_chain().
SSL_BUILD_CHAIN_FLAG_IGNORE_ERROR
#define SSL_BUILD_CHAIN_FLAG_IGNORE_ERROR 0x8
Definition at line 442 of file ssl.h.
Referenced by ssl_build_cert_chain().
SSL_BUILD_CHAIN_FLAG_NO_ROOT
#define SSL_BUILD_CHAIN_FLAG_NO_ROOT 0x2
Definition at line 438 of file ssl.h.
Referenced by ssl_build_cert_chain().
SSL_BUILD_CHAIN_FLAG_UNTRUSTED
#define SSL_BUILD_CHAIN_FLAG_UNTRUSTED 0x1
Definition at line 436 of file ssl.h.
Referenced by ssl_build_cert_chain().
SSL_cache_hit
#define SSL_cache_hit (s) SSL_session_reused(s)
Definition at line 1845 of file ssl.h.
SSL_CB_ACCEPT_EXIT
#define SSL_CB_ACCEPT_EXIT (SSL_ST_ACCEPT|SSL_CB_EXIT)
Definition at line 919 of file ssl.h.
SSL_CB_ACCEPT_LOOP
#define SSL_CB_ACCEPT_LOOP (SSL_ST_ACCEPT|SSL_CB_LOOP)
Definition at line 918 of file ssl.h.
SSL_CB_ALERT
#define SSL_CB_ALERT 0x4000/* used in callback */
Definition at line 915 of file ssl.h.
SSL_CB_CONNECT_EXIT
#define SSL_CB_CONNECT_EXIT (SSL_ST_CONNECT|SSL_CB_EXIT)
Definition at line 921 of file ssl.h.
SSL_CB_CONNECT_LOOP
#define SSL_CB_CONNECT_LOOP (SSL_ST_CONNECT|SSL_CB_LOOP)
Definition at line 920 of file ssl.h.
SSL_CB_EXIT
#define SSL_CB_EXIT 0x02
Definition at line 912 of file ssl.h.
SSL_CB_HANDSHAKE_DONE
#define SSL_CB_HANDSHAKE_DONE 0x20
Definition at line 923 of file ssl.h.
SSL_CB_HANDSHAKE_START
#define SSL_CB_HANDSHAKE_START 0x10
Definition at line 922 of file ssl.h.
SSL_CB_LOOP
#define SSL_CB_LOOP 0x01
Definition at line 911 of file ssl.h.
SSL_CB_READ
#define SSL_CB_READ 0x04
Definition at line 913 of file ssl.h.
SSL_CB_READ_ALERT
#define SSL_CB_READ_ALERT (SSL_CB_ALERT|SSL_CB_READ)
Definition at line 916 of file ssl.h.
SSL_CB_WRITE
#define SSL_CB_WRITE 0x08
Definition at line 914 of file ssl.h.
SSL_CB_WRITE_ALERT
#define SSL_CB_WRITE_ALERT (SSL_CB_ALERT|SSL_CB_WRITE)
Definition at line 917 of file ssl.h.
Referenced by ssl3_dispatch_alert().
SSL_CERT_FLAG_BROKEN_PROTOCOL
#define SSL_CERT_FLAG_BROKEN_PROTOCOL 0x10000000
Definition at line 432 of file ssl.h.
SSL_CERT_FLAG_SUITEB_128_LOS
#define SSL_CERT_FLAG_SUITEB_128_LOS 0x30000
Definition at line 429 of file ssl.h.
Referenced by ssl_build_cert_chain(), tls12_get_psigalgs(), and tls1_get_curvelist().
SSL_CERT_FLAG_SUITEB_128_LOS_ONLY
#define SSL_CERT_FLAG_SUITEB_128_LOS_ONLY 0x10000
Definition at line 425 of file ssl.h.
SSL_CERT_FLAG_SUITEB_192_LOS
#define SSL_CERT_FLAG_SUITEB_192_LOS 0x20000
Definition at line 427 of file ssl.h.
SSL_CERT_FLAG_TLS_STRICT
#define SSL_CERT_FLAG_TLS_STRICT 0x00000001U
Definition at line 422 of file ssl.h.
SSL_CERT_SET_FIRST
#define SSL_CERT_SET_FIRST 1
SSL_CERT_SET_NEXT
#define SSL_CERT_SET_NEXT 2
SSL_CERT_SET_SERVER
#define SSL_CERT_SET_SERVER 3
SSL_clear_cert_flags
#define SSL_clear_cert_flags (s, op) SSL_ctrl((s),SSL_CTRL_CLEAR_CERT_FLAGS,(op),NULL)
Definition at line 527 of file ssl.h.
SSL_clear_chain_certs
#define SSL_clear_chain_certs (ctx) SSL_set0_chain(ctx,NULL)
SSL_clear_mode
#define SSL_clear_mode (ssl, op) SSL_ctrl((ssl),SSL_CTRL_CLEAR_MODE,(op),NULL)
Definition at line 500 of file ssl.h.
SSL_clear_num_renegotiations
#define SSL_clear_num_renegotiations (ssl) SSL_ctrl((ssl),SSL_CTRL_CLEAR_NUM_RENEGOTIATIONS,0,NULL)
SSL_COMP_free_compression_methods
#define SSL_COMP_free_compression_methods () while(0) continue
Definition at line 1816 of file ssl.h.
SSL_CONF_FLAG_CERTIFICATE
#define SSL_CONF_FLAG_CERTIFICATE 0x20
Definition at line 473 of file ssl.h.
SSL_CONF_FLAG_CLIENT
#define SSL_CONF_FLAG_CLIENT 0x4
Definition at line 470 of file ssl.h.
SSL_CONF_FLAG_CMDLINE
#define SSL_CONF_FLAG_CMDLINE 0x1
Definition at line 468 of file ssl.h.
SSL_CONF_FLAG_FILE
#define SSL_CONF_FLAG_FILE 0x2
Definition at line 469 of file ssl.h.
SSL_CONF_FLAG_REQUIRE_PRIVATE
#define SSL_CONF_FLAG_REQUIRE_PRIVATE 0x40
Definition at line 474 of file ssl.h.
SSL_CONF_FLAG_SERVER
#define SSL_CONF_FLAG_SERVER 0x8
Definition at line 471 of file ssl.h.
SSL_CONF_FLAG_SHOW_ERRORS
#define SSL_CONF_FLAG_SHOW_ERRORS 0x10
Definition at line 472 of file ssl.h.
SSL_CONF_TYPE_DIR
#define SSL_CONF_TYPE_DIR 0x3
Definition at line 479 of file ssl.h.
SSL_CONF_TYPE_FILE
#define SSL_CONF_TYPE_FILE 0x2
Definition at line 478 of file ssl.h.
SSL_CONF_TYPE_NONE
#define SSL_CONF_TYPE_NONE 0x4
Definition at line 480 of file ssl.h.
SSL_CONF_TYPE_STRING
#define SSL_CONF_TYPE_STRING 0x1
Definition at line 477 of file ssl.h.
SSL_CONF_TYPE_UNKNOWN
#define SSL_CONF_TYPE_UNKNOWN 0x0
Definition at line 476 of file ssl.h.
SSL_CTRL_BUILD_CERT_CHAIN
#define SSL_CTRL_BUILD_CERT_CHAIN 105
SSL_CTRL_CERT_FLAGS
#define SSL_CTRL_CERT_FLAGS 99
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_CHAIN
#define SSL_CTRL_CHAIN 88
SSL_CTRL_CHAIN_CERT
#define SSL_CTRL_CHAIN_CERT 89
SSL_CTRL_CLEAR_CERT_FLAGS
#define SSL_CTRL_CLEAR_CERT_FLAGS 100
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_CLEAR_EXTRA_CHAIN_CERTS
#define SSL_CTRL_CLEAR_EXTRA_CHAIN_CERTS 83
SSL_CTRL_CLEAR_MODE
#define SSL_CTRL_CLEAR_MODE 78
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_CLEAR_NUM_RENEGOTIATIONS
#define SSL_CTRL_CLEAR_NUM_RENEGOTIATIONS 11
SSL_CTRL_DTLS_EXT_SEND_HEARTBEAT
#define SSL_CTRL_DTLS_EXT_SEND_HEARTBEAT 85
SSL_CTRL_EXTRA_CHAIN_CERT
#define SSL_CTRL_EXTRA_CHAIN_CERT 14
SSL_CTRL_GET_CHAIN_CERTS
#define SSL_CTRL_GET_CHAIN_CERTS 115
SSL_CTRL_GET_CLIENT_CERT_REQUEST
#define SSL_CTRL_GET_CLIENT_CERT_REQUEST 9
SSL_CTRL_GET_CLIENT_CERT_TYPES
#define SSL_CTRL_GET_CLIENT_CERT_TYPES 103
SSL_CTRL_GET_DTLS_EXT_HEARTBEAT_PENDING
#define SSL_CTRL_GET_DTLS_EXT_HEARTBEAT_PENDING 86
SSL_CTRL_GET_EC_POINT_FORMATS
#define SSL_CTRL_GET_EC_POINT_FORMATS 111
SSL_CTRL_GET_EXTMS_SUPPORT
#define SSL_CTRL_GET_EXTMS_SUPPORT 122
Referenced by SSL_ctrl().
SSL_CTRL_GET_EXTRA_CHAIN_CERTS
#define SSL_CTRL_GET_EXTRA_CHAIN_CERTS 82
SSL_CTRL_GET_FLAGS
#define SSL_CTRL_GET_FLAGS 13
SSL_CTRL_GET_GROUPS
#define SSL_CTRL_GET_GROUPS 90
SSL_CTRL_GET_MAX_CERT_LIST
#define SSL_CTRL_GET_MAX_CERT_LIST 50
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_GET_NUM_RENEGOTIATIONS
#define SSL_CTRL_GET_NUM_RENEGOTIATIONS 10
SSL_CTRL_GET_PEER_SIGNATURE_NID
#define SSL_CTRL_GET_PEER_SIGNATURE_NID 108
SSL_CTRL_GET_RAW_CIPHERLIST
#define SSL_CTRL_GET_RAW_CIPHERLIST 110
Referenced by SSL_ctrl().
SSL_CTRL_GET_READ_AHEAD
#define SSL_CTRL_GET_READ_AHEAD 40
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_GET_RI_SUPPORT
#define SSL_CTRL_GET_RI_SUPPORT 76
Referenced by SSL_ctrl().
SSL_CTRL_GET_SERVER_TMP_KEY
#define SSL_CTRL_GET_SERVER_TMP_KEY 109
SSL_CTRL_GET_SESS_CACHE_MODE
#define SSL_CTRL_GET_SESS_CACHE_MODE 45
Referenced by SSL_CTX_ctrl().
SSL_CTRL_GET_SESS_CACHE_SIZE
#define SSL_CTRL_GET_SESS_CACHE_SIZE 43
Referenced by SSL_CTX_ctrl().
SSL_CTRL_GET_SHARED_GROUP
#define SSL_CTRL_GET_SHARED_GROUP 93
SSL_CTRL_GET_TLSEXT_STATUS_REQ_CB
#define SSL_CTRL_GET_TLSEXT_STATUS_REQ_CB 128
SSL_CTRL_GET_TLSEXT_STATUS_REQ_CB_ARG
#define SSL_CTRL_GET_TLSEXT_STATUS_REQ_CB_ARG 129
SSL_CTRL_GET_TLSEXT_STATUS_REQ_EXTS
#define SSL_CTRL_GET_TLSEXT_STATUS_REQ_EXTS 66
SSL_CTRL_GET_TLSEXT_STATUS_REQ_IDS
#define SSL_CTRL_GET_TLSEXT_STATUS_REQ_IDS 68
SSL_CTRL_GET_TLSEXT_STATUS_REQ_OCSP_RESP
#define SSL_CTRL_GET_TLSEXT_STATUS_REQ_OCSP_RESP 70
SSL_CTRL_GET_TLSEXT_STATUS_REQ_TYPE
#define SSL_CTRL_GET_TLSEXT_STATUS_REQ_TYPE 127
SSL_CTRL_GET_TLSEXT_TICKET_KEYS
#define SSL_CTRL_GET_TLSEXT_TICKET_KEYS 58
Referenced by ssl3_ctx_ctrl().
SSL_CTRL_GET_TOTAL_RENEGOTIATIONS
#define SSL_CTRL_GET_TOTAL_RENEGOTIATIONS 12
SSL_CTRL_MODE
#define SSL_CTRL_MODE 33
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_SELECT_CURRENT_CERT
#define SSL_CTRL_SELECT_CURRENT_CERT 116
SSL_CTRL_SESS_ACCEPT
#define SSL_CTRL_SESS_ACCEPT 24
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SESS_ACCEPT_GOOD
#define SSL_CTRL_SESS_ACCEPT_GOOD 25
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SESS_ACCEPT_RENEGOTIATE
#define SSL_CTRL_SESS_ACCEPT_RENEGOTIATE 26
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SESS_CACHE_FULL
#define SSL_CTRL_SESS_CACHE_FULL 31
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SESS_CB_HIT
#define SSL_CTRL_SESS_CB_HIT 28
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SESS_CONNECT
#define SSL_CTRL_SESS_CONNECT 21
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SESS_CONNECT_GOOD
#define SSL_CTRL_SESS_CONNECT_GOOD 22
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SESS_CONNECT_RENEGOTIATE
#define SSL_CTRL_SESS_CONNECT_RENEGOTIATE 23
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SESS_HIT
#define SSL_CTRL_SESS_HIT 27
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SESS_MISSES
#define SSL_CTRL_SESS_MISSES 29
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SESS_NUMBER
#define SSL_CTRL_SESS_NUMBER 20
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SESS_TIMEOUTS
#define SSL_CTRL_SESS_TIMEOUTS 30
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SET_CHAIN_CERT_STORE
#define SSL_CTRL_SET_CHAIN_CERT_STORE 107
SSL_CTRL_SET_CLIENT_CERT_TYPES
#define SSL_CTRL_SET_CLIENT_CERT_TYPES 104
SSL_CTRL_SET_CLIENT_SIGALGS
#define SSL_CTRL_SET_CLIENT_SIGALGS 101
SSL_CTRL_SET_CLIENT_SIGALGS_LIST
#define SSL_CTRL_SET_CLIENT_SIGALGS_LIST 102
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SET_CURRENT_CERT
#define SSL_CTRL_SET_CURRENT_CERT 117
SSL_CTRL_SET_DH_AUTO
#define SSL_CTRL_SET_DH_AUTO 118
Referenced by ssl3_ctx_ctrl().
SSL_CTRL_SET_DTLS_EXT_HEARTBEAT_NO_REQUESTS
#define SSL_CTRL_SET_DTLS_EXT_HEARTBEAT_NO_REQUESTS 87
SSL_CTRL_SET_GROUPS
#define SSL_CTRL_SET_GROUPS 91
SSL_CTRL_SET_GROUPS_LIST
#define SSL_CTRL_SET_GROUPS_LIST 92
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SET_MAX_CERT_LIST
#define SSL_CTRL_SET_MAX_CERT_LIST 51
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_SET_MAX_PIPELINES
#define SSL_CTRL_SET_MAX_PIPELINES 126
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_SET_MAX_PROTO_VERSION
#define SSL_CTRL_SET_MAX_PROTO_VERSION 124
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_SET_MAX_SEND_FRAGMENT
#define SSL_CTRL_SET_MAX_SEND_FRAGMENT 52
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_SET_MIN_PROTO_VERSION
#define SSL_CTRL_SET_MIN_PROTO_VERSION 123
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_SET_MSG_CALLBACK
#define SSL_CTRL_SET_MSG_CALLBACK 15
Referenced by SSL_callback_ctrl(), and SSL_CTX_callback_ctrl().
SSL_CTRL_SET_MSG_CALLBACK_ARG
#define SSL_CTRL_SET_MSG_CALLBACK_ARG 16
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_SET_MTU
#define SSL_CTRL_SET_MTU 17
SSL_CTRL_SET_NOT_RESUMABLE_SESS_CB
#define SSL_CTRL_SET_NOT_RESUMABLE_SESS_CB 79
Referenced by ssl3_ctx_callback_ctrl(), SSL_CTX_set_not_resumable_session_callback(), and SSL_set_not_resumable_session_callback().
SSL_CTRL_SET_READ_AHEAD
#define SSL_CTRL_SET_READ_AHEAD 41
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_SET_SESS_CACHE_MODE
#define SSL_CTRL_SET_SESS_CACHE_MODE 44
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SET_SESS_CACHE_SIZE
#define SSL_CTRL_SET_SESS_CACHE_SIZE 42
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SET_SIGALGS
#define SSL_CTRL_SET_SIGALGS 97
SSL_CTRL_SET_SIGALGS_LIST
#define SSL_CTRL_SET_SIGALGS_LIST 98
Referenced by SSL_CTX_ctrl().
SSL_CTRL_SET_SPLIT_SEND_FRAGMENT
#define SSL_CTRL_SET_SPLIT_SEND_FRAGMENT 125
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
SSL_CTRL_SET_SRP_ARG
#define SSL_CTRL_SET_SRP_ARG 78
SSL_CTRL_SET_SRP_GIVE_CLIENT_PWD_CB
#define SSL_CTRL_SET_SRP_GIVE_CLIENT_PWD_CB 77
Referenced by ssl3_ctx_callback_ctrl(), and SSL_CTX_set_srp_client_pwd_callback().
SSL_CTRL_SET_SRP_VERIFY_PARAM_CB
#define SSL_CTRL_SET_SRP_VERIFY_PARAM_CB 76
Referenced by ssl3_ctx_callback_ctrl(), and SSL_CTX_set_srp_verify_param_callback().
SSL_CTRL_SET_TLS_EXT_SRP_PASSWORD
#define SSL_CTRL_SET_TLS_EXT_SRP_PASSWORD 81
Referenced by SSL_CTX_set_srp_password().
SSL_CTRL_SET_TLS_EXT_SRP_STRENGTH
#define SSL_CTRL_SET_TLS_EXT_SRP_STRENGTH 80
Referenced by SSL_CTX_set_srp_strength().
SSL_CTRL_SET_TLS_EXT_SRP_USERNAME
#define SSL_CTRL_SET_TLS_EXT_SRP_USERNAME 79
Referenced by SSL_CTX_set_srp_username().
SSL_CTRL_SET_TLS_EXT_SRP_USERNAME_CB
#define SSL_CTRL_SET_TLS_EXT_SRP_USERNAME_CB 75
Referenced by ssl3_ctx_callback_ctrl(), and SSL_CTX_set_srp_username_callback().
SSL_CTRL_SET_TLSEXT_DEBUG_ARG
#define SSL_CTRL_SET_TLSEXT_DEBUG_ARG 57
SSL_CTRL_SET_TLSEXT_DEBUG_CB
#define SSL_CTRL_SET_TLSEXT_DEBUG_CB 56
SSL_CTRL_SET_TLSEXT_HOSTNAME
#define SSL_CTRL_SET_TLSEXT_HOSTNAME 55
SSL_CTRL_SET_TLSEXT_SERVERNAME_ARG
#define SSL_CTRL_SET_TLSEXT_SERVERNAME_ARG 54
Referenced by ssl3_ctx_ctrl().
SSL_CTRL_SET_TLSEXT_SERVERNAME_CB
#define SSL_CTRL_SET_TLSEXT_SERVERNAME_CB 53
Referenced by ssl3_ctx_callback_ctrl().
SSL_CTRL_SET_TLSEXT_STATUS_REQ_CB
#define SSL_CTRL_SET_TLSEXT_STATUS_REQ_CB 63
Referenced by ssl3_ctx_callback_ctrl().
SSL_CTRL_SET_TLSEXT_STATUS_REQ_CB_ARG
#define SSL_CTRL_SET_TLSEXT_STATUS_REQ_CB_ARG 64
SSL_CTRL_SET_TLSEXT_STATUS_REQ_EXTS
#define SSL_CTRL_SET_TLSEXT_STATUS_REQ_EXTS 67
SSL_CTRL_SET_TLSEXT_STATUS_REQ_IDS
#define SSL_CTRL_SET_TLSEXT_STATUS_REQ_IDS 69
SSL_CTRL_SET_TLSEXT_STATUS_REQ_OCSP_RESP
#define SSL_CTRL_SET_TLSEXT_STATUS_REQ_OCSP_RESP 71
SSL_CTRL_SET_TLSEXT_STATUS_REQ_TYPE
#define SSL_CTRL_SET_TLSEXT_STATUS_REQ_TYPE 65
SSL_CTRL_SET_TLSEXT_TICKET_KEY_CB
#define SSL_CTRL_SET_TLSEXT_TICKET_KEY_CB 72
Referenced by ssl3_ctx_callback_ctrl().
SSL_CTRL_SET_TLSEXT_TICKET_KEYS
#define SSL_CTRL_SET_TLSEXT_TICKET_KEYS 59
Referenced by ssl3_ctx_ctrl().
SSL_CTRL_SET_TMP_DH
#define SSL_CTRL_SET_TMP_DH 3
Referenced by ssl3_ctx_ctrl().
SSL_CTRL_SET_TMP_DH_CB
#define SSL_CTRL_SET_TMP_DH_CB 6
Referenced by ssl3_ctx_callback_ctrl(), ssl3_ctx_ctrl(), SSL_CTX_set_tmp_dh_callback(), and SSL_set_tmp_dh_callback().
SSL_CTRL_SET_TMP_ECDH
#define SSL_CTRL_SET_TMP_ECDH 4
Referenced by ssl3_ctx_ctrl().
SSL_CTRL_SET_VERIFY_CERT_STORE
#define SSL_CTRL_SET_VERIFY_CERT_STORE 106
SSL_CTX_add0_chain_cert
#define SSL_CTX_add0_chain_cert (ctx, x509) SSL_CTX_ctrl(ctx,SSL_CTRL_CHAIN_CERT,0,(char *)x509)
SSL_CTX_add1_chain_cert
#define SSL_CTX_add1_chain_cert (ctx, x509) SSL_CTX_ctrl(ctx,SSL_CTRL_CHAIN_CERT,1,(char *)x509)
SSL_CTX_add_extra_chain_cert
#define SSL_CTX_add_extra_chain_cert (ctx, x509) SSL_CTX_ctrl(ctx,SSL_CTRL_EXTRA_CHAIN_CERT,0,(char *)x509)
SSL_CTX_build_cert_chain
#define SSL_CTX_build_cert_chain (ctx, flags) SSL_CTX_ctrl(ctx,SSL_CTRL_BUILD_CERT_CHAIN, flags, NULL)
SSL_CTX_clear_cert_flags
#define SSL_CTX_clear_cert_flags (ctx, op) SSL_CTX_ctrl((ctx),SSL_CTRL_CLEAR_CERT_FLAGS,(op),NULL)
Definition at line 525 of file ssl.h.
SSL_CTX_clear_chain_certs
#define SSL_CTX_clear_chain_certs (ctx) SSL_CTX_set0_chain(ctx,NULL)
SSL_CTX_clear_extra_chain_certs
#define SSL_CTX_clear_extra_chain_certs (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_CLEAR_EXTRA_CHAIN_CERTS,0,NULL)
SSL_CTX_clear_mode
#define SSL_CTX_clear_mode (ctx, op) SSL_CTX_ctrl((ctx),SSL_CTRL_CLEAR_MODE,(op),NULL)
Definition at line 496 of file ssl.h.
SSL_CTX_disable_ct
#define SSL_CTX_disable_ct (ctx) ((void) SSL_CTX_set_validation_callback((ctx), NULL, NULL))
Definition at line 1909 of file ssl.h.
SSL_CTX_get0_chain_certs
#define SSL_CTX_get0_chain_certs (ctx, px509) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_CHAIN_CERTS,0,px509)
SSL_CTX_get_app_data
#define SSL_CTX_get_app_data (ctx) (SSL_CTX_get_ex_data(ctx,0))
Definition at line 824 of file ssl.h.
SSL_CTX_get_default_read_ahead
#define SSL_CTX_get_default_read_ahead (ctx) SSL_CTX_get_read_ahead(ctx)
Definition at line 1766 of file ssl.h.
SSL_CTX_get_ex_new_index
#define SSL_CTX_get_ex_new_index (l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_SSL_CTX, l, p, newf, dupf, freef)
Definition at line 1750 of file ssl.h.
SSL_CTX_get_extra_chain_certs
#define SSL_CTX_get_extra_chain_certs (ctx, px509) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_EXTRA_CHAIN_CERTS,0,px509)
SSL_CTX_get_extra_chain_certs_only
#define SSL_CTX_get_extra_chain_certs_only (ctx, px509) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_EXTRA_CHAIN_CERTS,1,px509)
SSL_CTX_get_max_cert_list
#define SSL_CTX_get_max_cert_list (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_MAX_CERT_LIST,0,NULL)
Definition at line 1772 of file ssl.h.
SSL_CTX_get_mode
#define SSL_CTX_get_mode (ctx) SSL_CTX_ctrl((ctx),SSL_CTRL_MODE,0,NULL)
Definition at line 498 of file ssl.h.
SSL_CTX_get_read_ahead
#define SSL_CTX_get_read_ahead (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_READ_AHEAD,0,NULL)
Definition at line 1768 of file ssl.h.
SSL_CTX_get_session_cache_mode
#define SSL_CTX_get_session_cache_mode (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_SESS_CACHE_MODE,0,NULL)
Definition at line 1763 of file ssl.h.
SSL_CTX_need_tmp_RSA
#define SSL_CTX_need_tmp_RSA (ctx) 0
SSL_CTX_select_current_cert
#define SSL_CTX_select_current_cert (ctx, x509) SSL_CTX_ctrl(ctx,SSL_CTRL_SELECT_CURRENT_CERT,0,(char *)x509)
SSL_CTX_sess_accept
#define SSL_CTX_sess_accept (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_ACCEPT,0,NULL)
Definition at line 596 of file ssl.h.
SSL_CTX_sess_accept_good
#define SSL_CTX_sess_accept_good (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_ACCEPT_GOOD,0,NULL)
Definition at line 600 of file ssl.h.
SSL_CTX_sess_accept_renegotiate
#define SSL_CTX_sess_accept_renegotiate (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_ACCEPT_RENEGOTIATE,0,NULL)
Definition at line 598 of file ssl.h.
SSL_CTX_sess_cache_full
#define SSL_CTX_sess_cache_full (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_CACHE_FULL,0,NULL)
Definition at line 610 of file ssl.h.
SSL_CTX_sess_cb_hits
#define SSL_CTX_sess_cb_hits (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_CB_HIT,0,NULL)
Definition at line 604 of file ssl.h.
SSL_CTX_sess_connect
#define SSL_CTX_sess_connect (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_CONNECT,0,NULL)
Definition at line 590 of file ssl.h.
SSL_CTX_sess_connect_good
#define SSL_CTX_sess_connect_good (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_CONNECT_GOOD,0,NULL)
Definition at line 592 of file ssl.h.
SSL_CTX_sess_connect_renegotiate
#define SSL_CTX_sess_connect_renegotiate (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_CONNECT_RENEGOTIATE,0,NULL)
Definition at line 594 of file ssl.h.
SSL_CTX_sess_get_cache_size
#define SSL_CTX_sess_get_cache_size (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_GET_SESS_CACHE_SIZE,0,NULL)
Definition at line 1759 of file ssl.h.
SSL_CTX_sess_hits
#define SSL_CTX_sess_hits (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_HIT,0,NULL)
Definition at line 602 of file ssl.h.
SSL_CTX_sess_misses
#define SSL_CTX_sess_misses (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_MISSES,0,NULL)
Definition at line 606 of file ssl.h.
SSL_CTX_sess_number
#define SSL_CTX_sess_number (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_NUMBER,0,NULL)
Definition at line 588 of file ssl.h.
SSL_CTX_sess_set_cache_size
#define SSL_CTX_sess_set_cache_size (ctx, t) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_SESS_CACHE_SIZE,t,NULL)
Definition at line 1757 of file ssl.h.
SSL_CTX_sess_timeouts
#define SSL_CTX_sess_timeouts (ctx) SSL_CTX_ctrl(ctx,SSL_CTRL_SESS_TIMEOUTS,0,NULL)
Definition at line 608 of file ssl.h.
SSL_CTX_set0_chain
#define SSL_CTX_set0_chain (ctx, sk) SSL_CTX_ctrl(ctx,SSL_CTRL_CHAIN,0,(char *)sk)
SSL_CTX_set0_chain_cert_store
#define SSL_CTX_set0_chain_cert_store (ctx, st) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_CHAIN_CERT_STORE,0,(char *)st)
SSL_CTX_set0_verify_cert_store
#define SSL_CTX_set0_verify_cert_store (ctx, st) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_VERIFY_CERT_STORE,0,(char *)st)
SSL_CTX_set1_chain
#define SSL_CTX_set1_chain (ctx, sk) SSL_CTX_ctrl(ctx,SSL_CTRL_CHAIN,1,(char *)sk)
SSL_CTX_set1_chain_cert_store
#define SSL_CTX_set1_chain_cert_store (ctx, st) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_CHAIN_CERT_STORE,1,(char *)st)
SSL_CTX_set1_client_certificate_types
#define SSL_CTX_set1_client_certificate_types (ctx, clist, clistlen) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_CLIENT_CERT_TYPES,clistlen,(char *)clist)
SSL_CTX_set1_client_sigalgs
#define SSL_CTX_set1_client_sigalgs (ctx, slist, slistlen) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_CLIENT_SIGALGS,slistlen,(int *)slist)
SSL_CTX_set1_client_sigalgs_list
#define SSL_CTX_set1_client_sigalgs_list (ctx, s) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_CLIENT_SIGALGS_LIST,0,(char *)s)
SSL_CTX_set1_curves
#define SSL_CTX_set1_curves (ctx, clist, clistlen) SSL_CTX_set1_groups((ctx), (clist), (clistlen))
SSL_CTX_set1_curves_list
#define SSL_CTX_set1_curves_list (ctx, s) SSL_CTX_set1_groups_list((ctx), (s))
SSL_CTX_set1_groups
#define SSL_CTX_set1_groups (ctx, glist, glistlen) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_GROUPS,glistlen,(char *)glist)
SSL_CTX_set1_groups_list
#define SSL_CTX_set1_groups_list (ctx, s) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_GROUPS_LIST,0,(char *)s)
SSL_CTX_set1_sigalgs
#define SSL_CTX_set1_sigalgs (ctx, slist, slistlen) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_SIGALGS,slistlen,(int *)slist)
SSL_CTX_set1_sigalgs_list
#define SSL_CTX_set1_sigalgs_list (ctx, s) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_SIGALGS_LIST,0,(char *)s)
SSL_CTX_set1_verify_cert_store
#define SSL_CTX_set1_verify_cert_store (ctx, st) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_VERIFY_CERT_STORE,1,(char *)st)
SSL_CTX_set_app_data
#define SSL_CTX_set_app_data (ctx, arg) (SSL_CTX_set_ex_data(ctx,0,(char *)arg))
Definition at line 825 of file ssl.h.
SSL_CTX_set_cert_flags
#define SSL_CTX_set_cert_flags (ctx, op) SSL_CTX_ctrl((ctx),SSL_CTRL_CERT_FLAGS,(op),NULL)
Definition at line 521 of file ssl.h.
SSL_CTX_set_current_cert
#define SSL_CTX_set_current_cert (ctx, op) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_CURRENT_CERT, op, NULL)
SSL_CTX_set_default_read_ahead
#define SSL_CTX_set_default_read_ahead (ctx, m) SSL_CTX_set_read_ahead(ctx,m)
Definition at line 1767 of file ssl.h.
SSL_CTX_set_dh_auto
#define SSL_CTX_set_dh_auto (ctx, onoff) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_DH_AUTO,onoff,NULL)
Referenced by create_ssl_ctx_pair().
SSL_CTX_set_ecdh_auto
#define SSL_CTX_set_ecdh_auto (dummy, onoff) ((onoff) != 0)
SSL_CTX_set_max_cert_list
#define SSL_CTX_set_max_cert_list (ctx, m) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_MAX_CERT_LIST,m,NULL)
Definition at line 1774 of file ssl.h.
SSL_CTX_set_max_pipelines
#define SSL_CTX_set_max_pipelines (ctx, m) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_MAX_PIPELINES,m,NULL)
Definition at line 1789 of file ssl.h.
SSL_CTX_set_max_proto_version
#define SSL_CTX_set_max_proto_version (ctx, version) SSL_CTX_ctrl(ctx, SSL_CTRL_SET_MAX_PROTO_VERSION, version, NULL)
SSL_CTX_set_max_send_fragment
#define SSL_CTX_set_max_send_fragment (ctx, m) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_MAX_SEND_FRAGMENT,m,NULL)
Definition at line 1781 of file ssl.h.
SSL_CTX_set_min_proto_version
#define SSL_CTX_set_min_proto_version (ctx, version) SSL_CTX_ctrl(ctx, SSL_CTRL_SET_MIN_PROTO_VERSION, version, NULL)
SSL_CTX_set_mode
#define SSL_CTX_set_mode (ctx, op) SSL_CTX_ctrl((ctx),SSL_CTRL_MODE,(op),NULL)
Definition at line 494 of file ssl.h.
Referenced by process_responder().
SSL_CTX_set_msg_callback_arg
#define SSL_CTX_set_msg_callback_arg (ctx, arg) SSL_CTX_ctrl((ctx), SSL_CTRL_SET_MSG_CALLBACK_ARG, 0, (arg))
Definition at line 538 of file ssl.h.
SSL_CTX_set_npn_advertised_cb
#define SSL_CTX_set_npn_advertised_cb SSL_CTX_set_next_protos_advertised_cb
Definition at line 668 of file ssl.h.
SSL_CTX_set_npn_select_cb
#define SSL_CTX_set_npn_select_cb SSL_CTX_set_next_proto_select_cb
Definition at line 679 of file ssl.h.
SSL_CTX_set_read_ahead
#define SSL_CTX_set_read_ahead (ctx, m) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_READ_AHEAD,m,NULL)
Definition at line 1770 of file ssl.h.
SSL_CTX_set_session_cache_mode
#define SSL_CTX_set_session_cache_mode (ctx, m) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_SESS_CACHE_MODE,m,NULL)
Definition at line 1761 of file ssl.h.
SSL_CTX_set_split_send_fragment
#define SSL_CTX_set_split_send_fragment (ctx, m) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_SPLIT_SEND_FRAGMENT,m,NULL)
Definition at line 1785 of file ssl.h.
SSL_CTX_set_tmp_dh
#define SSL_CTX_set_tmp_dh (ctx, dh) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_TMP_DH,0,(char *)dh)
SSL_CTX_set_tmp_ecdh
#define SSL_CTX_set_tmp_ecdh (ctx, ecdh) SSL_CTX_ctrl(ctx,SSL_CTRL_SET_TMP_ECDH,0,(char *)ecdh)
SSL_CTX_set_tmp_rsa
#define SSL_CTX_set_tmp_rsa (ctx, rsa) 1
SSL_CTX_set_tmp_rsa_callback
#define SSL_CTX_set_tmp_rsa_callback (ctx, cb) while(0) (cb)(NULL, 0, 0)
SSL_DEFAULT_CIPHER_LIST
#define SSL_DEFAULT_CIPHER_LIST "ALL:!COMPLEMENTOFDEFAULT:!eNULL"
Definition at line 198 of file ssl.h.
Referenced by SSL_CTX_set_ssl_version().
SSL_disable_ct
#define SSL_disable_ct (s) ((void) SSL_set_validation_callback((s), NULL, NULL))
Definition at line 1907 of file ssl.h.
SSL_ERROR_NONE
#define SSL_ERROR_NONE 0
Referenced by SSL_get_error(), and SSL_srp_server_param_with_username().
SSL_ERROR_SSL
#define SSL_ERROR_SSL 1
Referenced by SSL_get_error().
SSL_ERROR_SYSCALL
#define SSL_ERROR_SYSCALL
Value:
5/* look at error stack/return
                                           * value/errno */
Referenced by SSL_get_error().
SSL_ERROR_WANT_ACCEPT
#define SSL_ERROR_WANT_ACCEPT 8
Referenced by SSL_get_error().
SSL_ERROR_WANT_ASYNC
#define SSL_ERROR_WANT_ASYNC 9
Referenced by SSL_get_error().
SSL_ERROR_WANT_ASYNC_JOB
#define SSL_ERROR_WANT_ASYNC_JOB 10
Referenced by SSL_get_error().
SSL_ERROR_WANT_CONNECT
#define SSL_ERROR_WANT_CONNECT 7
Referenced by SSL_get_error().
SSL_ERROR_WANT_READ
#define SSL_ERROR_WANT_READ 2
Referenced by SSL_get_error().
SSL_ERROR_WANT_WRITE
#define SSL_ERROR_WANT_WRITE 3
Referenced by SSL_get_error().
SSL_ERROR_WANT_X509_LOOKUP
#define SSL_ERROR_WANT_X509_LOOKUP 4
Referenced by SSL_get_error().
SSL_ERROR_ZERO_RETURN
#define SSL_ERROR_ZERO_RETURN 6
Referenced by SSL_get_error().
SSL_F_ADD_CLIENT_KEY_SHARE_EXT
#define SSL_F_ADD_CLIENT_KEY_SHARE_EXT 438
Definition at line 2088 of file ssl.h.
SSL_F_ADD_KEY_SHARE
#define SSL_F_ADD_KEY_SHARE 512
Definition at line 2089 of file ssl.h.
SSL_F_CHECK_SUITEB_CIPHER_LIST
#define SSL_F_CHECK_SUITEB_CIPHER_LIST 331
Definition at line 2090 of file ssl.h.
SSL_F_CT_MOVE_SCTS
#define SSL_F_CT_MOVE_SCTS 345
Definition at line 2091 of file ssl.h.
SSL_F_CT_STRICT
#define SSL_F_CT_STRICT 349
Definition at line 2092 of file ssl.h.
SSL_F_D2I_SSL_SESSION
#define SSL_F_D2I_SSL_SESSION 103
Definition at line 2093 of file ssl.h.
SSL_F_DANE_CTX_ENABLE
#define SSL_F_DANE_CTX_ENABLE 347
Definition at line 2094 of file ssl.h.
SSL_F_DANE_MTYPE_SET
#define SSL_F_DANE_MTYPE_SET 393
Definition at line 2095 of file ssl.h.
SSL_F_DANE_TLSA_ADD
#define SSL_F_DANE_TLSA_ADD 394
Definition at line 2096 of file ssl.h.
SSL_F_DERIVE_SECRET_KEY_AND_IV
#define SSL_F_DERIVE_SECRET_KEY_AND_IV 514
Definition at line 2097 of file ssl.h.
SSL_F_DO_DTLS1_WRITE
#define SSL_F_DO_DTLS1_WRITE 245
Definition at line 2098 of file ssl.h.
SSL_F_DO_SSL3_WRITE
#define SSL_F_DO_SSL3_WRITE 104
Definition at line 2099 of file ssl.h.
SSL_F_DTLS1_BUFFER_RECORD
#define SSL_F_DTLS1_BUFFER_RECORD 247
Definition at line 2100 of file ssl.h.
Referenced by dtls1_buffer_record().
SSL_F_DTLS1_CHECK_TIMEOUT_NUM
#define SSL_F_DTLS1_CHECK_TIMEOUT_NUM 318
Definition at line 2101 of file ssl.h.
Referenced by dtls1_check_timeout_num().
SSL_F_DTLS1_HEARTBEAT
#define SSL_F_DTLS1_HEARTBEAT 305
Definition at line 2102 of file ssl.h.
SSL_F_DTLS1_PREPROCESS_FRAGMENT
#define SSL_F_DTLS1_PREPROCESS_FRAGMENT 288
Definition at line 2103 of file ssl.h.
SSL_F_DTLS1_PROCESS_BUFFERED_RECORDS
#define SSL_F_DTLS1_PROCESS_BUFFERED_RECORDS 424
Definition at line 2104 of file ssl.h.
Referenced by dtls1_process_buffered_records().
SSL_F_DTLS1_PROCESS_RECORD
#define SSL_F_DTLS1_PROCESS_RECORD 257
Definition at line 2105 of file ssl.h.
SSL_F_DTLS1_READ_BYTES
#define SSL_F_DTLS1_READ_BYTES 258
Definition at line 2106 of file ssl.h.
SSL_F_DTLS1_READ_FAILED
#define SSL_F_DTLS1_READ_FAILED 339
Definition at line 2107 of file ssl.h.
Referenced by dtls1_read_failed().
SSL_F_DTLS1_RETRANSMIT_MESSAGE
#define SSL_F_DTLS1_RETRANSMIT_MESSAGE 390
Definition at line 2108 of file ssl.h.
SSL_F_DTLS1_WRITE_APP_DATA_BYTES
#define SSL_F_DTLS1_WRITE_APP_DATA_BYTES 268
Definition at line 2109 of file ssl.h.
Referenced by dtls1_write_app_data_bytes().
SSL_F_DTLS_CONSTRUCT_CHANGE_CIPHER_SPEC
#define SSL_F_DTLS_CONSTRUCT_CHANGE_CIPHER_SPEC 371
Definition at line 2111 of file ssl.h.
Referenced by dtls_construct_change_cipher_spec().
SSL_F_DTLS_CONSTRUCT_HELLO_VERIFY_REQUEST
#define SSL_F_DTLS_CONSTRUCT_HELLO_VERIFY_REQUEST 385
Definition at line 2112 of file ssl.h.
Referenced by dtls_construct_hello_verify_request().
SSL_F_DTLS_GET_REASSEMBLED_MESSAGE
#define SSL_F_DTLS_GET_REASSEMBLED_MESSAGE 370
Definition at line 2113 of file ssl.h.
SSL_F_DTLS_PROCESS_HELLO_VERIFY
#define SSL_F_DTLS_PROCESS_HELLO_VERIFY 386
Definition at line 2114 of file ssl.h.
SSL_F_DTLSV1_LISTEN
#define SSL_F_DTLSV1_LISTEN 350
Definition at line 2110 of file ssl.h.
SSL_F_FINAL_EC_PT_FORMATS
#define SSL_F_FINAL_EC_PT_FORMATS 485
Definition at line 2115 of file ssl.h.
SSL_F_FINAL_EMS
#define SSL_F_FINAL_EMS 486
Definition at line 2116 of file ssl.h.
SSL_F_FINAL_KEY_SHARE
#define SSL_F_FINAL_KEY_SHARE 503
Definition at line 2117 of file ssl.h.
SSL_F_FINAL_RENEGOTIATE
#define SSL_F_FINAL_RENEGOTIATE 483
Definition at line 2118 of file ssl.h.
SSL_F_FINAL_SIG_ALGS
#define SSL_F_FINAL_SIG_ALGS 497
Definition at line 2119 of file ssl.h.
SSL_F_NSS_KEYLOG_INT
#define SSL_F_NSS_KEYLOG_INT 500
Definition at line 2120 of file ssl.h.
SSL_F_OPENSSL_INIT_SSL
#define SSL_F_OPENSSL_INIT_SSL 342
Definition at line 2121 of file ssl.h.
SSL_F_OSSL_STATEM_CLIENT13_READ_TRANSITION
#define SSL_F_OSSL_STATEM_CLIENT13_READ_TRANSITION 436
Definition at line 2122 of file ssl.h.
SSL_F_OSSL_STATEM_CLIENT_CONSTRUCT_MESSAGE
#define SSL_F_OSSL_STATEM_CLIENT_CONSTRUCT_MESSAGE 430
Definition at line 2123 of file ssl.h.
SSL_F_OSSL_STATEM_CLIENT_READ_TRANSITION
#define SSL_F_OSSL_STATEM_CLIENT_READ_TRANSITION 417
Definition at line 2124 of file ssl.h.
SSL_F_OSSL_STATEM_SERVER13_READ_TRANSITION
#define SSL_F_OSSL_STATEM_SERVER13_READ_TRANSITION 437
Definition at line 2125 of file ssl.h.
SSL_F_OSSL_STATEM_SERVER_CONSTRUCT_MESSAGE
#define SSL_F_OSSL_STATEM_SERVER_CONSTRUCT_MESSAGE 431
Definition at line 2126 of file ssl.h.
SSL_F_OSSL_STATEM_SERVER_READ_TRANSITION
#define SSL_F_OSSL_STATEM_SERVER_READ_TRANSITION 418
Definition at line 2127 of file ssl.h.
Referenced by ossl_statem_server_read_transition().
SSL_F_PROCESS_KEY_SHARE_EXT
#define SSL_F_PROCESS_KEY_SHARE_EXT 439
Definition at line 2128 of file ssl.h.
SSL_F_READ_STATE_MACHINE
#define SSL_F_READ_STATE_MACHINE 352
Definition at line 2129 of file ssl.h.
SSL_F_SSL3_CHANGE_CIPHER_STATE
#define SSL_F_SSL3_CHANGE_CIPHER_STATE 129
Definition at line 2130 of file ssl.h.
SSL_F_SSL3_CHECK_CERT_AND_ALGORITHM
#define SSL_F_SSL3_CHECK_CERT_AND_ALGORITHM 130
Definition at line 2131 of file ssl.h.
SSL_F_SSL3_CTRL
#define SSL_F_SSL3_CTRL 213
Definition at line 2132 of file ssl.h.
SSL_F_SSL3_CTX_CTRL
#define SSL_F_SSL3_CTX_CTRL 133
Definition at line 2133 of file ssl.h.
Referenced by ssl3_ctx_ctrl().
SSL_F_SSL3_DIGEST_CACHED_RECORDS
#define SSL_F_SSL3_DIGEST_CACHED_RECORDS 293
Definition at line 2134 of file ssl.h.
SSL_F_SSL3_DO_CHANGE_CIPHER_SPEC
#define SSL_F_SSL3_DO_CHANGE_CIPHER_SPEC 292
Definition at line 2135 of file ssl.h.
Referenced by ssl3_do_change_cipher_spec().
SSL_F_SSL3_FINAL_FINISH_MAC
#define SSL_F_SSL3_FINAL_FINISH_MAC 285
Definition at line 2136 of file ssl.h.
SSL_F_SSL3_GENERATE_KEY_BLOCK
#define SSL_F_SSL3_GENERATE_KEY_BLOCK 238
Definition at line 2137 of file ssl.h.
SSL_F_SSL3_GENERATE_MASTER_SECRET
#define SSL_F_SSL3_GENERATE_MASTER_SECRET 388
Definition at line 2138 of file ssl.h.
SSL_F_SSL3_GET_RECORD
#define SSL_F_SSL3_GET_RECORD 143
Definition at line 2139 of file ssl.h.
SSL_F_SSL3_INIT_FINISHED_MAC
#define SSL_F_SSL3_INIT_FINISHED_MAC 397
Definition at line 2140 of file ssl.h.
Referenced by ssl3_init_finished_mac().
SSL_F_SSL3_OUTPUT_CERT_CHAIN
#define SSL_F_SSL3_OUTPUT_CERT_CHAIN 147
Definition at line 2141 of file ssl.h.
SSL_F_SSL3_READ_BYTES
#define SSL_F_SSL3_READ_BYTES 148
Definition at line 2142 of file ssl.h.
SSL_F_SSL3_READ_N
#define SSL_F_SSL3_READ_N 149
Definition at line 2143 of file ssl.h.
Referenced by ssl3_read_n().
SSL_F_SSL3_SETUP_KEY_BLOCK
#define SSL_F_SSL3_SETUP_KEY_BLOCK 157
Definition at line 2144 of file ssl.h.
SSL_F_SSL3_SETUP_READ_BUFFER
#define SSL_F_SSL3_SETUP_READ_BUFFER 156
Definition at line 2145 of file ssl.h.
Referenced by ssl3_setup_read_buffer().
SSL_F_SSL3_SETUP_WRITE_BUFFER
#define SSL_F_SSL3_SETUP_WRITE_BUFFER 291
Definition at line 2146 of file ssl.h.
Referenced by ssl3_setup_write_buffer().
SSL_F_SSL3_WRITE_BYTES
#define SSL_F_SSL3_WRITE_BYTES 158
Definition at line 2147 of file ssl.h.
SSL_F_SSL3_WRITE_PENDING
#define SSL_F_SSL3_WRITE_PENDING 159
Definition at line 2148 of file ssl.h.
SSL_F_SSL_ADD_CERT_CHAIN
#define SSL_F_SSL_ADD_CERT_CHAIN 316
Definition at line 2149 of file ssl.h.
SSL_F_SSL_ADD_CERT_TO_BUF
#define SSL_F_SSL_ADD_CERT_TO_BUF 319
Definition at line 2150 of file ssl.h.
SSL_F_SSL_ADD_CERT_TO_WPACKET
#define SSL_F_SSL_ADD_CERT_TO_WPACKET 493
Definition at line 2151 of file ssl.h.
SSL_F_SSL_ADD_CLIENTHELLO_RENEGOTIATE_EXT
#define SSL_F_SSL_ADD_CLIENTHELLO_RENEGOTIATE_EXT 298
Definition at line 2152 of file ssl.h.
SSL_F_SSL_ADD_CLIENTHELLO_TLSEXT
#define SSL_F_SSL_ADD_CLIENTHELLO_TLSEXT 277
Definition at line 2153 of file ssl.h.
SSL_F_SSL_ADD_CLIENTHELLO_USE_SRTP_EXT
#define SSL_F_SSL_ADD_CLIENTHELLO_USE_SRTP_EXT 307
Definition at line 2154 of file ssl.h.
SSL_F_SSL_ADD_DIR_CERT_SUBJECTS_TO_STACK
#define SSL_F_SSL_ADD_DIR_CERT_SUBJECTS_TO_STACK 215
Definition at line 2155 of file ssl.h.
SSL_F_SSL_ADD_FILE_CERT_SUBJECTS_TO_STACK
#define SSL_F_SSL_ADD_FILE_CERT_SUBJECTS_TO_STACK 216
Definition at line 2156 of file ssl.h.
SSL_F_SSL_ADD_SERVERHELLO_RENEGOTIATE_EXT
#define SSL_F_SSL_ADD_SERVERHELLO_RENEGOTIATE_EXT 299
Definition at line 2157 of file ssl.h.
SSL_F_SSL_ADD_SERVERHELLO_TLSEXT
#define SSL_F_SSL_ADD_SERVERHELLO_TLSEXT 278
Definition at line 2158 of file ssl.h.
SSL_F_SSL_ADD_SERVERHELLO_USE_SRTP_EXT
#define SSL_F_SSL_ADD_SERVERHELLO_USE_SRTP_EXT 308
Definition at line 2159 of file ssl.h.
SSL_F_SSL_BAD_METHOD
#define SSL_F_SSL_BAD_METHOD 160
Definition at line 2160 of file ssl.h.
Referenced by ssl_bad_method().
SSL_F_SSL_BUILD_CERT_CHAIN
#define SSL_F_SSL_BUILD_CERT_CHAIN 332
Definition at line 2161 of file ssl.h.
Referenced by ssl_build_cert_chain().
SSL_F_SSL_BYTES_TO_CIPHER_LIST
#define SSL_F_SSL_BYTES_TO_CIPHER_LIST 161
Definition at line 2162 of file ssl.h.
SSL_F_SSL_CERT_ADD0_CHAIN_CERT
#define SSL_F_SSL_CERT_ADD0_CHAIN_CERT 346
Definition at line 2163 of file ssl.h.
Referenced by ssl_cert_add0_chain_cert().
SSL_F_SSL_CERT_DUP
#define SSL_F_SSL_CERT_DUP 221
Definition at line 2164 of file ssl.h.
SSL_F_SSL_CERT_NEW
#define SSL_F_SSL_CERT_NEW 162
Definition at line 2165 of file ssl.h.
SSL_F_SSL_CERT_SET0_CHAIN
#define SSL_F_SSL_CERT_SET0_CHAIN 340
Definition at line 2166 of file ssl.h.
Referenced by ssl_cert_set0_chain().
SSL_F_SSL_CHECK_PRIVATE_KEY
#define SSL_F_SSL_CHECK_PRIVATE_KEY 163
Definition at line 2167 of file ssl.h.
Referenced by SSL_check_private_key().
SSL_F_SSL_CHECK_SERVERHELLO_TLSEXT
#define SSL_F_SSL_CHECK_SERVERHELLO_TLSEXT 280
Definition at line 2168 of file ssl.h.
SSL_F_SSL_CHECK_SRVR_ECC_CERT_AND_ALG
#define SSL_F_SSL_CHECK_SRVR_ECC_CERT_AND_ALG 279
Definition at line 2169 of file ssl.h.
Referenced by ssl_check_srvr_ecc_cert_and_alg().
SSL_F_SSL_CIPHER_LIST_TO_BYTES
#define SSL_F_SSL_CIPHER_LIST_TO_BYTES 425
Definition at line 2170 of file ssl.h.
SSL_F_SSL_CIPHER_PROCESS_RULESTR
#define SSL_F_SSL_CIPHER_PROCESS_RULESTR 230
Definition at line 2171 of file ssl.h.
SSL_F_SSL_CIPHER_STRENGTH_SORT
#define SSL_F_SSL_CIPHER_STRENGTH_SORT 231
Definition at line 2172 of file ssl.h.
SSL_F_SSL_CLEAR
#define SSL_F_SSL_CLEAR 164
Definition at line 2173 of file ssl.h.
Referenced by SSL_clear().
SSL_F_SSL_COMP_ADD_COMPRESSION_METHOD
#define SSL_F_SSL_COMP_ADD_COMPRESSION_METHOD 165
Definition at line 2174 of file ssl.h.
Referenced by SSL_COMP_add_compression_method().
SSL_F_SSL_CONF_CMD
#define SSL_F_SSL_CONF_CMD 334
Definition at line 2175 of file ssl.h.
Referenced by SSL_CONF_cmd().
SSL_F_SSL_CREATE_CIPHER_LIST
#define SSL_F_SSL_CREATE_CIPHER_LIST 166
Definition at line 2176 of file ssl.h.
SSL_F_SSL_CTRL
#define SSL_F_SSL_CTRL 232
Definition at line 2177 of file ssl.h.
SSL_F_SSL_CTX_CHECK_PRIVATE_KEY
#define SSL_F_SSL_CTX_CHECK_PRIVATE_KEY 168
Definition at line 2178 of file ssl.h.
Referenced by SSL_CTX_check_private_key().
SSL_F_SSL_CTX_ENABLE_CT
#define SSL_F_SSL_CTX_ENABLE_CT 398
Definition at line 2179 of file ssl.h.
Referenced by SSL_CTX_enable_ct().
SSL_F_SSL_CTX_MAKE_PROFILES
#define SSL_F_SSL_CTX_MAKE_PROFILES 309
Definition at line 2180 of file ssl.h.
SSL_F_SSL_CTX_NEW
#define SSL_F_SSL_CTX_NEW 169
Definition at line 2181 of file ssl.h.
SSL_F_SSL_CTX_SET_ALPN_PROTOS
#define SSL_F_SSL_CTX_SET_ALPN_PROTOS 343
Definition at line 2182 of file ssl.h.
Referenced by SSL_CTX_set_alpn_protos().
SSL_F_SSL_CTX_SET_CIPHER_LIST
#define SSL_F_SSL_CTX_SET_CIPHER_LIST 269
Definition at line 2183 of file ssl.h.
Referenced by SSL_CTX_set_cipher_list().
SSL_F_SSL_CTX_SET_CLIENT_CERT_ENGINE
#define SSL_F_SSL_CTX_SET_CLIENT_CERT_ENGINE 290
Definition at line 2184 of file ssl.h.
Referenced by SSL_CTX_set_client_cert_engine().
SSL_F_SSL_CTX_SET_CT_VALIDATION_CALLBACK
#define SSL_F_SSL_CTX_SET_CT_VALIDATION_CALLBACK 396
Definition at line 2185 of file ssl.h.
SSL_F_SSL_CTX_SET_SESSION_ID_CONTEXT
#define SSL_F_SSL_CTX_SET_SESSION_ID_CONTEXT 219
Definition at line 2186 of file ssl.h.
Referenced by SSL_CTX_set_session_id_context().
SSL_F_SSL_CTX_SET_SSL_VERSION
#define SSL_F_SSL_CTX_SET_SSL_VERSION 170
Definition at line 2187 of file ssl.h.
Referenced by SSL_CTX_set_ssl_version().
SSL_F_SSL_CTX_USE_CERTIFICATE
#define SSL_F_SSL_CTX_USE_CERTIFICATE 171
Definition at line 2188 of file ssl.h.
Referenced by SSL_CTX_use_certificate().
SSL_F_SSL_CTX_USE_CERTIFICATE_ASN1
#define SSL_F_SSL_CTX_USE_CERTIFICATE_ASN1 172
Definition at line 2189 of file ssl.h.
SSL_F_SSL_CTX_USE_CERTIFICATE_FILE
#define SSL_F_SSL_CTX_USE_CERTIFICATE_FILE 173
Definition at line 2190 of file ssl.h.
SSL_F_SSL_CTX_USE_PRIVATEKEY
#define SSL_F_SSL_CTX_USE_PRIVATEKEY 174
Definition at line 2191 of file ssl.h.
Referenced by SSL_CTX_use_PrivateKey().
SSL_F_SSL_CTX_USE_PRIVATEKEY_ASN1
#define SSL_F_SSL_CTX_USE_PRIVATEKEY_ASN1 175
Definition at line 2192 of file ssl.h.
SSL_F_SSL_CTX_USE_PRIVATEKEY_FILE
#define SSL_F_SSL_CTX_USE_PRIVATEKEY_FILE 176
Definition at line 2193 of file ssl.h.
SSL_F_SSL_CTX_USE_PSK_IDENTITY_HINT
#define SSL_F_SSL_CTX_USE_PSK_IDENTITY_HINT 272
Definition at line 2194 of file ssl.h.
Referenced by SSL_CTX_use_psk_identity_hint().
SSL_F_SSL_CTX_USE_RSAPRIVATEKEY
#define SSL_F_SSL_CTX_USE_RSAPRIVATEKEY 177
Definition at line 2195 of file ssl.h.
SSL_F_SSL_CTX_USE_RSAPRIVATEKEY_ASN1
#define SSL_F_SSL_CTX_USE_RSAPRIVATEKEY_ASN1 178
Definition at line 2196 of file ssl.h.
SSL_F_SSL_CTX_USE_RSAPRIVATEKEY_FILE
#define SSL_F_SSL_CTX_USE_RSAPRIVATEKEY_FILE 179
Definition at line 2197 of file ssl.h.
SSL_F_SSL_CTX_USE_SERVERINFO
#define SSL_F_SSL_CTX_USE_SERVERINFO 336
Definition at line 2198 of file ssl.h.
Referenced by SSL_CTX_use_serverinfo().
SSL_F_SSL_CTX_USE_SERVERINFO_FILE
#define SSL_F_SSL_CTX_USE_SERVERINFO_FILE 337
Definition at line 2199 of file ssl.h.
SSL_F_SSL_DANE_DUP
#define SSL_F_SSL_DANE_DUP 403
Definition at line 2200 of file ssl.h.
SSL_F_SSL_DANE_ENABLE
#define SSL_F_SSL_DANE_ENABLE 395
Definition at line 2201 of file ssl.h.
Referenced by SSL_dane_enable().
SSL_F_SSL_DO_CONFIG
#define SSL_F_SSL_DO_CONFIG 391
Definition at line 2202 of file ssl.h.
SSL_F_SSL_DO_HANDSHAKE
#define SSL_F_SSL_DO_HANDSHAKE 180
Definition at line 2203 of file ssl.h.
SSL_F_SSL_DUP_CA_LIST
#define SSL_F_SSL_DUP_CA_LIST 408
Definition at line 2204 of file ssl.h.
SSL_F_SSL_ENABLE_CT
#define SSL_F_SSL_ENABLE_CT 402
Definition at line 2205 of file ssl.h.
Referenced by SSL_enable_ct().
SSL_F_SSL_GET_NEW_SESSION
#define SSL_F_SSL_GET_NEW_SESSION 181
Definition at line 2206 of file ssl.h.
SSL_F_SSL_GET_PREV_SESSION
#define SSL_F_SSL_GET_PREV_SESSION 217
Definition at line 2207 of file ssl.h.
SSL_F_SSL_GET_SERVER_CERT_INDEX
#define SSL_F_SSL_GET_SERVER_CERT_INDEX 322
Definition at line 2208 of file ssl.h.
SSL_F_SSL_GET_SIGN_PKEY
#define SSL_F_SSL_GET_SIGN_PKEY 183
Definition at line 2209 of file ssl.h.
SSL_F_SSL_INIT_WBIO_BUFFER
#define SSL_F_SSL_INIT_WBIO_BUFFER 184
Definition at line 2210 of file ssl.h.
Referenced by ssl_init_wbio_buffer().
SSL_F_SSL_KEY_UPDATE
#define SSL_F_SSL_KEY_UPDATE 515
Definition at line 2211 of file ssl.h.
Referenced by SSL_key_update().
SSL_F_SSL_LOAD_CLIENT_CA_FILE
#define SSL_F_SSL_LOAD_CLIENT_CA_FILE 185
Definition at line 2212 of file ssl.h.
SSL_F_SSL_LOG_MASTER_SECRET
#define SSL_F_SSL_LOG_MASTER_SECRET 498
Definition at line 2213 of file ssl.h.
SSL_F_SSL_LOG_RSA_CLIENT_KEY_EXCHANGE
#define SSL_F_SSL_LOG_RSA_CLIENT_KEY_EXCHANGE 499
Definition at line 2214 of file ssl.h.
Referenced by ssl_log_rsa_client_key_exchange().
SSL_F_SSL_MODULE_INIT
#define SSL_F_SSL_MODULE_INIT 392
Definition at line 2215 of file ssl.h.
SSL_F_SSL_NEW
#define SSL_F_SSL_NEW 186
Definition at line 2216 of file ssl.h.
Referenced by SSL_new().
SSL_F_SSL_PARSE_CLIENTHELLO_RENEGOTIATE_EXT
#define SSL_F_SSL_PARSE_CLIENTHELLO_RENEGOTIATE_EXT 300
Definition at line 2217 of file ssl.h.
SSL_F_SSL_PARSE_CLIENTHELLO_TLSEXT
#define SSL_F_SSL_PARSE_CLIENTHELLO_TLSEXT 302
Definition at line 2218 of file ssl.h.
SSL_F_SSL_PARSE_CLIENTHELLO_USE_SRTP_EXT
#define SSL_F_SSL_PARSE_CLIENTHELLO_USE_SRTP_EXT 310
Definition at line 2219 of file ssl.h.
SSL_F_SSL_PARSE_SERVERHELLO_RENEGOTIATE_EXT
#define SSL_F_SSL_PARSE_SERVERHELLO_RENEGOTIATE_EXT 301
Definition at line 2220 of file ssl.h.
SSL_F_SSL_PARSE_SERVERHELLO_TLSEXT
#define SSL_F_SSL_PARSE_SERVERHELLO_TLSEXT 303
Definition at line 2221 of file ssl.h.
SSL_F_SSL_PARSE_SERVERHELLO_USE_SRTP_EXT
#define SSL_F_SSL_PARSE_SERVERHELLO_USE_SRTP_EXT 311
Definition at line 2222 of file ssl.h.
SSL_F_SSL_PEEK
#define SSL_F_SSL_PEEK 270
Definition at line 2223 of file ssl.h.
SSL_F_SSL_PEEK_EX
#define SSL_F_SSL_PEEK_EX 432
Definition at line 2224 of file ssl.h.
Referenced by SSL_peek_ex().
SSL_F_SSL_READ
#define SSL_F_SSL_READ 223
Definition at line 2225 of file ssl.h.
SSL_F_SSL_READ_EX
#define SSL_F_SSL_READ_EX 434
Definition at line 2226 of file ssl.h.
Referenced by SSL_read_ex().
SSL_F_SSL_RENEGOTIATE
#define SSL_F_SSL_RENEGOTIATE 516
Definition at line 2227 of file ssl.h.
Referenced by SSL_renegotiate().
SSL_F_SSL_SCAN_CLIENTHELLO_TLSEXT
#define SSL_F_SSL_SCAN_CLIENTHELLO_TLSEXT 320
Definition at line 2228 of file ssl.h.
SSL_F_SSL_SCAN_SERVERHELLO_TLSEXT
#define SSL_F_SSL_SCAN_SERVERHELLO_TLSEXT 321
Definition at line 2229 of file ssl.h.
SSL_F_SSL_SESSION_DUP
#define SSL_F_SSL_SESSION_DUP 348
Definition at line 2230 of file ssl.h.
Referenced by ssl_session_dup().
SSL_F_SSL_SESSION_NEW
#define SSL_F_SSL_SESSION_NEW 189
Definition at line 2231 of file ssl.h.
Referenced by SSL_SESSION_new().
SSL_F_SSL_SESSION_PRINT_FP
#define SSL_F_SSL_SESSION_PRINT_FP 190
Definition at line 2232 of file ssl.h.
SSL_F_SSL_SESSION_SET1_ID
#define SSL_F_SSL_SESSION_SET1_ID 423
Definition at line 2233 of file ssl.h.
Referenced by SSL_SESSION_set1_id().
SSL_F_SSL_SESSION_SET1_ID_CONTEXT
#define SSL_F_SSL_SESSION_SET1_ID_CONTEXT 312
Definition at line 2234 of file ssl.h.
Referenced by SSL_SESSION_set1_id_context().
SSL_F_SSL_SET_ALPN_PROTOS
#define SSL_F_SSL_SET_ALPN_PROTOS 344
Definition at line 2235 of file ssl.h.
Referenced by SSL_set_alpn_protos().
SSL_F_SSL_SET_CERT
#define SSL_F_SSL_SET_CERT 191
Definition at line 2236 of file ssl.h.
SSL_F_SSL_SET_CIPHER_LIST
#define SSL_F_SSL_SET_CIPHER_LIST 271
Definition at line 2237 of file ssl.h.
Referenced by SSL_set_cipher_list().
SSL_F_SSL_SET_CT_VALIDATION_CALLBACK
#define SSL_F_SSL_SET_CT_VALIDATION_CALLBACK 399
Definition at line 2238 of file ssl.h.
SSL_F_SSL_SET_FD
#define SSL_F_SSL_SET_FD 192
Definition at line 2239 of file ssl.h.
SSL_F_SSL_SET_PKEY
#define SSL_F_SSL_SET_PKEY 193
Definition at line 2240 of file ssl.h.
SSL_F_SSL_SET_RFD
#define SSL_F_SSL_SET_RFD 194
Definition at line 2241 of file ssl.h.
Referenced by SSL_set_rfd().
SSL_F_SSL_SET_SESSION
#define SSL_F_SSL_SET_SESSION 195
Definition at line 2242 of file ssl.h.
SSL_F_SSL_SET_SESSION_ID_CONTEXT
#define SSL_F_SSL_SET_SESSION_ID_CONTEXT 218
Definition at line 2243 of file ssl.h.
Referenced by SSL_set_session_id_context().
SSL_F_SSL_SET_SESSION_TICKET_EXT
#define SSL_F_SSL_SET_SESSION_TICKET_EXT 294
Definition at line 2244 of file ssl.h.
Referenced by SSL_set_session_ticket_ext().
SSL_F_SSL_SET_WFD
#define SSL_F_SSL_SET_WFD 196
Definition at line 2245 of file ssl.h.
Referenced by SSL_set_wfd().
SSL_F_SSL_SHUTDOWN
#define SSL_F_SSL_SHUTDOWN 224
Definition at line 2246 of file ssl.h.
Referenced by SSL_shutdown().
SSL_F_SSL_SRP_CTX_INIT
#define SSL_F_SSL_SRP_CTX_INIT 313
Definition at line 2247 of file ssl.h.
Referenced by SSL_SRP_CTX_init().
SSL_F_SSL_START_ASYNC_JOB
#define SSL_F_SSL_START_ASYNC_JOB 389
Definition at line 2248 of file ssl.h.
SSL_F_SSL_UNDEFINED_FUNCTION
#define SSL_F_SSL_UNDEFINED_FUNCTION 197
Definition at line 2249 of file ssl.h.
Referenced by ssl_undefined_function().
SSL_F_SSL_UNDEFINED_VOID_FUNCTION
#define SSL_F_SSL_UNDEFINED_VOID_FUNCTION 244
Definition at line 2250 of file ssl.h.
Referenced by ssl_undefined_void_function().
SSL_F_SSL_USE_CERTIFICATE
#define SSL_F_SSL_USE_CERTIFICATE 198
Definition at line 2251 of file ssl.h.
Referenced by SSL_use_certificate().
SSL_F_SSL_USE_CERTIFICATE_ASN1
#define SSL_F_SSL_USE_CERTIFICATE_ASN1 199
Definition at line 2252 of file ssl.h.
SSL_F_SSL_USE_CERTIFICATE_FILE
#define SSL_F_SSL_USE_CERTIFICATE_FILE 200
Definition at line 2253 of file ssl.h.
SSL_F_SSL_USE_PRIVATEKEY
#define SSL_F_SSL_USE_PRIVATEKEY 201
Definition at line 2254 of file ssl.h.
SSL_F_SSL_USE_PRIVATEKEY_ASN1
#define SSL_F_SSL_USE_PRIVATEKEY_ASN1 202
Definition at line 2255 of file ssl.h.
SSL_F_SSL_USE_PRIVATEKEY_FILE
#define SSL_F_SSL_USE_PRIVATEKEY_FILE 203
Definition at line 2256 of file ssl.h.
SSL_F_SSL_USE_PSK_IDENTITY_HINT
#define SSL_F_SSL_USE_PSK_IDENTITY_HINT 273
Definition at line 2257 of file ssl.h.
Referenced by SSL_use_psk_identity_hint().
SSL_F_SSL_USE_RSAPRIVATEKEY
#define SSL_F_SSL_USE_RSAPRIVATEKEY 204
Definition at line 2258 of file ssl.h.
SSL_F_SSL_USE_RSAPRIVATEKEY_ASN1
#define SSL_F_SSL_USE_RSAPRIVATEKEY_ASN1 205
Definition at line 2259 of file ssl.h.
SSL_F_SSL_USE_RSAPRIVATEKEY_FILE
#define SSL_F_SSL_USE_RSAPRIVATEKEY_FILE 206
Definition at line 2260 of file ssl.h.
SSL_F_SSL_VALIDATE_CT
#define SSL_F_SSL_VALIDATE_CT 400
Definition at line 2261 of file ssl.h.
SSL_F_SSL_VERIFY_CERT_CHAIN
#define SSL_F_SSL_VERIFY_CERT_CHAIN 207
Definition at line 2262 of file ssl.h.
Referenced by ssl_verify_cert_chain().
SSL_F_SSL_WRITE
#define SSL_F_SSL_WRITE 208
Definition at line 2263 of file ssl.h.
SSL_F_SSL_WRITE_EX
#define SSL_F_SSL_WRITE_EX 433
Definition at line 2264 of file ssl.h.
Referenced by SSL_write_ex().
SSL_F_STATE_MACHINE
#define SSL_F_STATE_MACHINE 353
Definition at line 2265 of file ssl.h.
SSL_F_TLS12_CHECK_PEER_SIGALG
#define SSL_F_TLS12_CHECK_PEER_SIGALG 333
Definition at line 2266 of file ssl.h.
SSL_F_TLS13_CHANGE_CIPHER_STATE
#define SSL_F_TLS13_CHANGE_CIPHER_STATE 440
Definition at line 2267 of file ssl.h.
SSL_F_TLS13_SETUP_KEY_BLOCK
#define SSL_F_TLS13_SETUP_KEY_BLOCK 441
Definition at line 2268 of file ssl.h.
SSL_F_TLS1_CHANGE_CIPHER_STATE
#define SSL_F_TLS1_CHANGE_CIPHER_STATE 209
Definition at line 2269 of file ssl.h.
SSL_F_TLS1_CHECK_DUPLICATE_EXTENSIONS
#define SSL_F_TLS1_CHECK_DUPLICATE_EXTENSIONS 341
Definition at line 2270 of file ssl.h.
SSL_F_TLS1_ENC
#define SSL_F_TLS1_ENC 401
Definition at line 2271 of file ssl.h.
SSL_F_TLS1_EXPORT_KEYING_MATERIAL
#define SSL_F_TLS1_EXPORT_KEYING_MATERIAL 314
Definition at line 2272 of file ssl.h.
SSL_F_TLS1_GET_CURVELIST
#define SSL_F_TLS1_GET_CURVELIST 338
Definition at line 2273 of file ssl.h.
SSL_F_TLS1_PRF
#define SSL_F_TLS1_PRF 284
Definition at line 2274 of file ssl.h.
SSL_F_TLS1_SET_SERVER_SIGALGS
#define SSL_F_TLS1_SET_SERVER_SIGALGS 335
Definition at line 2276 of file ssl.h.
Referenced by tls1_set_server_sigalgs().
SSL_F_TLS1_SETUP_KEY_BLOCK
#define SSL_F_TLS1_SETUP_KEY_BLOCK 211
Definition at line 2275 of file ssl.h.
SSL_F_TLS_CHOOSE_SIGALG
#define SSL_F_TLS_CHOOSE_SIGALG 513
Definition at line 2277 of file ssl.h.
SSL_F_TLS_CLIENT_KEY_EXCHANGE_POST_WORK
#define SSL_F_TLS_CLIENT_KEY_EXCHANGE_POST_WORK 354
Definition at line 2278 of file ssl.h.
Referenced by tls_client_key_exchange_post_work().
SSL_F_TLS_COLLECT_EXTENSIONS
#define SSL_F_TLS_COLLECT_EXTENSIONS 435
Definition at line 2279 of file ssl.h.
Referenced by tls_collect_extensions().
SSL_F_TLS_CONSTRUCT_CERT_STATUS
#define SSL_F_TLS_CONSTRUCT_CERT_STATUS 429
Definition at line 2281 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CERT_STATUS_BODY
#define SSL_F_TLS_CONSTRUCT_CERT_STATUS_BODY 494
Definition at line 2282 of file ssl.h.
Referenced by tls_construct_cert_status_body().
SSL_F_TLS_CONSTRUCT_CERT_VERIFY
#define SSL_F_TLS_CONSTRUCT_CERT_VERIFY 496
Definition at line 2283 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CERTIFICATE_REQUEST
#define SSL_F_TLS_CONSTRUCT_CERTIFICATE_REQUEST 372
Definition at line 2280 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CHANGE_CIPHER_SPEC
#define SSL_F_TLS_CONSTRUCT_CHANGE_CIPHER_SPEC 427
Definition at line 2284 of file ssl.h.
Referenced by tls_construct_change_cipher_spec().
SSL_F_TLS_CONSTRUCT_CKE_DHE
#define SSL_F_TLS_CONSTRUCT_CKE_DHE 404
Definition at line 2285 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CKE_ECDHE
#define SSL_F_TLS_CONSTRUCT_CKE_ECDHE 405
Definition at line 2286 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CKE_GOST
#define SSL_F_TLS_CONSTRUCT_CKE_GOST 406
Definition at line 2287 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CKE_PSK_PREAMBLE
#define SSL_F_TLS_CONSTRUCT_CKE_PSK_PREAMBLE 407
Definition at line 2288 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CKE_RSA
#define SSL_F_TLS_CONSTRUCT_CKE_RSA 409
Definition at line 2289 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CKE_SRP
#define SSL_F_TLS_CONSTRUCT_CKE_SRP 410
Definition at line 2290 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CLIENT_CERTIFICATE
#define SSL_F_TLS_CONSTRUCT_CLIENT_CERTIFICATE 484
Definition at line 2291 of file ssl.h.
Referenced by tls_construct_client_certificate().
SSL_F_TLS_CONSTRUCT_CLIENT_HELLO
#define SSL_F_TLS_CONSTRUCT_CLIENT_HELLO 487
Definition at line 2292 of file ssl.h.
Referenced by tls_construct_client_hello().
SSL_F_TLS_CONSTRUCT_CLIENT_KEY_EXCHANGE
#define SSL_F_TLS_CONSTRUCT_CLIENT_KEY_EXCHANGE 488
Definition at line 2293 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CLIENT_VERIFY
#define SSL_F_TLS_CONSTRUCT_CLIENT_VERIFY 489
Definition at line 2294 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CTOS_ALPN
#define SSL_F_TLS_CONSTRUCT_CTOS_ALPN 466
Definition at line 2295 of file ssl.h.
Referenced by tls_construct_ctos_alpn().
SSL_F_TLS_CONSTRUCT_CTOS_CERTIFICATE
#define SSL_F_TLS_CONSTRUCT_CTOS_CERTIFICATE 355
Definition at line 2296 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CTOS_EC_PT_FORMATS
#define SSL_F_TLS_CONSTRUCT_CTOS_EC_PT_FORMATS 467
Definition at line 2297 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CTOS_EMS
#define SSL_F_TLS_CONSTRUCT_CTOS_EMS 468
Definition at line 2298 of file ssl.h.
Referenced by tls_construct_ctos_ems().
SSL_F_TLS_CONSTRUCT_CTOS_ETM
#define SSL_F_TLS_CONSTRUCT_CTOS_ETM 469
Definition at line 2299 of file ssl.h.
Referenced by tls_construct_ctos_etm().
SSL_F_TLS_CONSTRUCT_CTOS_HELLO
#define SSL_F_TLS_CONSTRUCT_CTOS_HELLO 356
Definition at line 2300 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CTOS_KEY_EXCHANGE
#define SSL_F_TLS_CONSTRUCT_CTOS_KEY_EXCHANGE 357
Definition at line 2301 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CTOS_KEY_SHARE
#define SSL_F_TLS_CONSTRUCT_CTOS_KEY_SHARE 470
Definition at line 2302 of file ssl.h.
Referenced by tls_construct_ctos_key_share().
SSL_F_TLS_CONSTRUCT_CTOS_NPN
#define SSL_F_TLS_CONSTRUCT_CTOS_NPN 471
Definition at line 2303 of file ssl.h.
Referenced by tls_construct_ctos_npn().
SSL_F_TLS_CONSTRUCT_CTOS_PADDING
#define SSL_F_TLS_CONSTRUCT_CTOS_PADDING 472
Definition at line 2304 of file ssl.h.
Referenced by tls_construct_ctos_padding().
SSL_F_TLS_CONSTRUCT_CTOS_PSK
#define SSL_F_TLS_CONSTRUCT_CTOS_PSK 501
Definition at line 2305 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CTOS_PSK_KEX_MODES
#define SSL_F_TLS_CONSTRUCT_CTOS_PSK_KEX_MODES 509
Definition at line 2306 of file ssl.h.
Referenced by tls_construct_ctos_psk_kex_modes().
SSL_F_TLS_CONSTRUCT_CTOS_RENEGOTIATE
#define SSL_F_TLS_CONSTRUCT_CTOS_RENEGOTIATE 473
Definition at line 2307 of file ssl.h.
Referenced by tls_construct_ctos_renegotiate().
SSL_F_TLS_CONSTRUCT_CTOS_SCT
#define SSL_F_TLS_CONSTRUCT_CTOS_SCT 474
Definition at line 2308 of file ssl.h.
Referenced by tls_construct_ctos_sct().
SSL_F_TLS_CONSTRUCT_CTOS_SERVER_NAME
#define SSL_F_TLS_CONSTRUCT_CTOS_SERVER_NAME 475
Definition at line 2309 of file ssl.h.
Referenced by tls_construct_ctos_server_name().
SSL_F_TLS_CONSTRUCT_CTOS_SESSION_TICKET
#define SSL_F_TLS_CONSTRUCT_CTOS_SESSION_TICKET 476
Definition at line 2310 of file ssl.h.
Referenced by tls_construct_ctos_session_ticket().
SSL_F_TLS_CONSTRUCT_CTOS_SIG_ALGS
#define SSL_F_TLS_CONSTRUCT_CTOS_SIG_ALGS 477
Definition at line 2311 of file ssl.h.
Referenced by tls_construct_ctos_sig_algs().
SSL_F_TLS_CONSTRUCT_CTOS_SRP
#define SSL_F_TLS_CONSTRUCT_CTOS_SRP 478
Definition at line 2312 of file ssl.h.
Referenced by tls_construct_ctos_srp().
SSL_F_TLS_CONSTRUCT_CTOS_STATUS_REQUEST
#define SSL_F_TLS_CONSTRUCT_CTOS_STATUS_REQUEST 479
Definition at line 2313 of file ssl.h.
Referenced by tls_construct_ctos_status_request().
SSL_F_TLS_CONSTRUCT_CTOS_SUPPORTED_GROUPS
#define SSL_F_TLS_CONSTRUCT_CTOS_SUPPORTED_GROUPS 480
Definition at line 2314 of file ssl.h.
SSL_F_TLS_CONSTRUCT_CTOS_SUPPORTED_VERSIONS
#define SSL_F_TLS_CONSTRUCT_CTOS_SUPPORTED_VERSIONS 481
Definition at line 2315 of file ssl.h.
Referenced by tls_construct_ctos_supported_versions().
SSL_F_TLS_CONSTRUCT_CTOS_USE_SRTP
#define SSL_F_TLS_CONSTRUCT_CTOS_USE_SRTP 482
Definition at line 2316 of file ssl.h.
Referenced by tls_construct_ctos_use_srtp().
SSL_F_TLS_CONSTRUCT_CTOS_VERIFY
#define SSL_F_TLS_CONSTRUCT_CTOS_VERIFY 358
Definition at line 2317 of file ssl.h.
SSL_F_TLS_CONSTRUCT_ENCRYPTED_EXTENSIONS
#define SSL_F_TLS_CONSTRUCT_ENCRYPTED_EXTENSIONS 443
Definition at line 2318 of file ssl.h.
SSL_F_TLS_CONSTRUCT_EXTENSIONS
#define SSL_F_TLS_CONSTRUCT_EXTENSIONS 447
Definition at line 2319 of file ssl.h.
Referenced by tls_construct_extensions().
SSL_F_TLS_CONSTRUCT_FINISHED
#define SSL_F_TLS_CONSTRUCT_FINISHED 359
Definition at line 2320 of file ssl.h.
Referenced by tls_construct_finished().
SSL_F_TLS_CONSTRUCT_HELLO_REQUEST
#define SSL_F_TLS_CONSTRUCT_HELLO_REQUEST 373
Definition at line 2321 of file ssl.h.
SSL_F_TLS_CONSTRUCT_HELLO_RETRY_REQUEST
#define SSL_F_TLS_CONSTRUCT_HELLO_RETRY_REQUEST 510
Definition at line 2322 of file ssl.h.
SSL_F_TLS_CONSTRUCT_KEY_UPDATE
#define SSL_F_TLS_CONSTRUCT_KEY_UPDATE 517
Definition at line 2323 of file ssl.h.
Referenced by tls_construct_key_update().
SSL_F_TLS_CONSTRUCT_NEW_SESSION_TICKET
#define SSL_F_TLS_CONSTRUCT_NEW_SESSION_TICKET 428
Definition at line 2324 of file ssl.h.
SSL_F_TLS_CONSTRUCT_NEXT_PROTO
#define SSL_F_TLS_CONSTRUCT_NEXT_PROTO 426
Definition at line 2325 of file ssl.h.
Referenced by tls_construct_next_proto().
SSL_F_TLS_CONSTRUCT_SERVER_CERTIFICATE
#define SSL_F_TLS_CONSTRUCT_SERVER_CERTIFICATE 490
Definition at line 2326 of file ssl.h.
Referenced by tls_construct_server_certificate().
SSL_F_TLS_CONSTRUCT_SERVER_HELLO
#define SSL_F_TLS_CONSTRUCT_SERVER_HELLO 491
Definition at line 2327 of file ssl.h.
Referenced by tls_construct_server_hello().
SSL_F_TLS_CONSTRUCT_SERVER_KEY_EXCHANGE
#define SSL_F_TLS_CONSTRUCT_SERVER_KEY_EXCHANGE 492
Definition at line 2328 of file ssl.h.
SSL_F_TLS_CONSTRUCT_STOC_ALPN
#define SSL_F_TLS_CONSTRUCT_STOC_ALPN 451
Definition at line 2329 of file ssl.h.
Referenced by tls_construct_stoc_alpn().
SSL_F_TLS_CONSTRUCT_STOC_CERTIFICATE
#define SSL_F_TLS_CONSTRUCT_STOC_CERTIFICATE 374
Definition at line 2330 of file ssl.h.
SSL_F_TLS_CONSTRUCT_STOC_CRYPTOPRO_BUG
#define SSL_F_TLS_CONSTRUCT_STOC_CRYPTOPRO_BUG 452
Definition at line 2331 of file ssl.h.
Referenced by tls_construct_stoc_cryptopro_bug().
SSL_F_TLS_CONSTRUCT_STOC_DONE
#define SSL_F_TLS_CONSTRUCT_STOC_DONE 375
Definition at line 2332 of file ssl.h.
SSL_F_TLS_CONSTRUCT_STOC_EC_PT_FORMATS
#define SSL_F_TLS_CONSTRUCT_STOC_EC_PT_FORMATS 453
Definition at line 2333 of file ssl.h.
Referenced by tls_construct_stoc_ec_pt_formats().
SSL_F_TLS_CONSTRUCT_STOC_EMS
#define SSL_F_TLS_CONSTRUCT_STOC_EMS 454
Definition at line 2334 of file ssl.h.
Referenced by tls_construct_stoc_ems().
SSL_F_TLS_CONSTRUCT_STOC_ETM
#define SSL_F_TLS_CONSTRUCT_STOC_ETM 455
Definition at line 2335 of file ssl.h.
Referenced by tls_construct_stoc_etm().
SSL_F_TLS_CONSTRUCT_STOC_HELLO
#define SSL_F_TLS_CONSTRUCT_STOC_HELLO 376
Definition at line 2336 of file ssl.h.
SSL_F_TLS_CONSTRUCT_STOC_KEY_EXCHANGE
#define SSL_F_TLS_CONSTRUCT_STOC_KEY_EXCHANGE 377
Definition at line 2337 of file ssl.h.
SSL_F_TLS_CONSTRUCT_STOC_KEY_SHARE
#define SSL_F_TLS_CONSTRUCT_STOC_KEY_SHARE 456
Definition at line 2338 of file ssl.h.
Referenced by tls_construct_stoc_key_share().
SSL_F_TLS_CONSTRUCT_STOC_NEXT_PROTO_NEG
#define SSL_F_TLS_CONSTRUCT_STOC_NEXT_PROTO_NEG 457
Definition at line 2339 of file ssl.h.
SSL_F_TLS_CONSTRUCT_STOC_PSK
#define SSL_F_TLS_CONSTRUCT_STOC_PSK 504
Definition at line 2340 of file ssl.h.
Referenced by tls_construct_stoc_psk().
SSL_F_TLS_CONSTRUCT_STOC_RENEGOTIATE
#define SSL_F_TLS_CONSTRUCT_STOC_RENEGOTIATE 458
Definition at line 2341 of file ssl.h.
Referenced by tls_construct_stoc_renegotiate().
SSL_F_TLS_CONSTRUCT_STOC_SERVER_NAME
#define SSL_F_TLS_CONSTRUCT_STOC_SERVER_NAME 459
Definition at line 2342 of file ssl.h.
Referenced by tls_construct_stoc_server_name().
SSL_F_TLS_CONSTRUCT_STOC_SESSION_TICKET
#define SSL_F_TLS_CONSTRUCT_STOC_SESSION_TICKET 460
Definition at line 2343 of file ssl.h.
Referenced by tls_construct_stoc_session_ticket().
SSL_F_TLS_CONSTRUCT_STOC_STATUS_REQUEST
#define SSL_F_TLS_CONSTRUCT_STOC_STATUS_REQUEST 461
Definition at line 2344 of file ssl.h.
Referenced by tls_construct_stoc_status_request().
SSL_F_TLS_CONSTRUCT_STOC_USE_SRTP
#define SSL_F_TLS_CONSTRUCT_STOC_USE_SRTP 462
Definition at line 2345 of file ssl.h.
Referenced by tls_construct_stoc_use_srtp().
SSL_F_TLS_GET_MESSAGE_BODY
#define SSL_F_TLS_GET_MESSAGE_BODY 351
Definition at line 2346 of file ssl.h.
SSL_F_TLS_GET_MESSAGE_HEADER
#define SSL_F_TLS_GET_MESSAGE_HEADER 387
Definition at line 2347 of file ssl.h.
Referenced by tls_get_message_header().
SSL_F_TLS_PARSE_CLIENTHELLO_TLSEXT
#define SSL_F_TLS_PARSE_CLIENTHELLO_TLSEXT 449
Definition at line 2348 of file ssl.h.
SSL_F_TLS_PARSE_CTOS_KEY_SHARE
#define SSL_F_TLS_PARSE_CTOS_KEY_SHARE 463
Definition at line 2349 of file ssl.h.
SSL_F_TLS_PARSE_CTOS_PSK
#define SSL_F_TLS_PARSE_CTOS_PSK 505
Definition at line 2350 of file ssl.h.
SSL_F_TLS_PARSE_CTOS_RENEGOTIATE
#define SSL_F_TLS_PARSE_CTOS_RENEGOTIATE 464
Definition at line 2351 of file ssl.h.
SSL_F_TLS_PARSE_CTOS_USE_SRTP
#define SSL_F_TLS_PARSE_CTOS_USE_SRTP 465
Definition at line 2352 of file ssl.h.
SSL_F_TLS_PARSE_STOC_KEY_SHARE
#define SSL_F_TLS_PARSE_STOC_KEY_SHARE 445
Definition at line 2353 of file ssl.h.
Referenced by tls_parse_stoc_key_share().
SSL_F_TLS_PARSE_STOC_PSK
#define SSL_F_TLS_PARSE_STOC_PSK 502
Definition at line 2354 of file ssl.h.
SSL_F_TLS_PARSE_STOC_RENEGOTIATE
#define SSL_F_TLS_PARSE_STOC_RENEGOTIATE 448
Definition at line 2355 of file ssl.h.
SSL_F_TLS_PARSE_STOC_USE_SRTP
#define SSL_F_TLS_PARSE_STOC_USE_SRTP 446
Definition at line 2356 of file ssl.h.
SSL_F_TLS_POST_PROCESS_CLIENT_HELLO
#define SSL_F_TLS_POST_PROCESS_CLIENT_HELLO 378
Definition at line 2357 of file ssl.h.
SSL_F_TLS_POST_PROCESS_CLIENT_KEY_EXCHANGE
#define SSL_F_TLS_POST_PROCESS_CLIENT_KEY_EXCHANGE 384
Definition at line 2358 of file ssl.h.
Referenced by tls_post_process_client_key_exchange().
SSL_F_TLS_PREPARE_CLIENT_CERTIFICATE
#define SSL_F_TLS_PREPARE_CLIENT_CERTIFICATE 360
Definition at line 2359 of file ssl.h.
SSL_F_TLS_PROCESS_CERT_STATUS
#define SSL_F_TLS_PROCESS_CERT_STATUS 362
Definition at line 2361 of file ssl.h.
SSL_F_TLS_PROCESS_CERT_STATUS_BODY
#define SSL_F_TLS_PROCESS_CERT_STATUS_BODY 495
Definition at line 2362 of file ssl.h.
SSL_F_TLS_PROCESS_CERT_VERIFY
#define SSL_F_TLS_PROCESS_CERT_VERIFY 379
Definition at line 2363 of file ssl.h.
SSL_F_TLS_PROCESS_CERTIFICATE_REQUEST
#define SSL_F_TLS_PROCESS_CERTIFICATE_REQUEST 361
Definition at line 2360 of file ssl.h.
SSL_F_TLS_PROCESS_CHANGE_CIPHER_SPEC
#define SSL_F_TLS_PROCESS_CHANGE_CIPHER_SPEC 363
Definition at line 2364 of file ssl.h.
SSL_F_TLS_PROCESS_CKE_DHE
#define SSL_F_TLS_PROCESS_CKE_DHE 411
Definition at line 2365 of file ssl.h.
SSL_F_TLS_PROCESS_CKE_ECDHE
#define SSL_F_TLS_PROCESS_CKE_ECDHE 412
Definition at line 2366 of file ssl.h.
SSL_F_TLS_PROCESS_CKE_GOST
#define SSL_F_TLS_PROCESS_CKE_GOST 413
Definition at line 2367 of file ssl.h.
SSL_F_TLS_PROCESS_CKE_PSK_PREAMBLE
#define SSL_F_TLS_PROCESS_CKE_PSK_PREAMBLE 414
Definition at line 2368 of file ssl.h.
SSL_F_TLS_PROCESS_CKE_RSA
#define SSL_F_TLS_PROCESS_CKE_RSA 415
Definition at line 2369 of file ssl.h.
SSL_F_TLS_PROCESS_CKE_SRP
#define SSL_F_TLS_PROCESS_CKE_SRP 416
Definition at line 2370 of file ssl.h.
SSL_F_TLS_PROCESS_CLIENT_CERTIFICATE
#define SSL_F_TLS_PROCESS_CLIENT_CERTIFICATE 380
Definition at line 2371 of file ssl.h.
SSL_F_TLS_PROCESS_CLIENT_HELLO
#define SSL_F_TLS_PROCESS_CLIENT_HELLO 381
Definition at line 2372 of file ssl.h.
SSL_F_TLS_PROCESS_CLIENT_KEY_EXCHANGE
#define SSL_F_TLS_PROCESS_CLIENT_KEY_EXCHANGE 382
Definition at line 2373 of file ssl.h.
SSL_F_TLS_PROCESS_ENCRYPTED_EXTENSIONS
#define SSL_F_TLS_PROCESS_ENCRYPTED_EXTENSIONS 444
Definition at line 2374 of file ssl.h.
SSL_F_TLS_PROCESS_FINISHED
#define SSL_F_TLS_PROCESS_FINISHED 364
Definition at line 2375 of file ssl.h.
Referenced by tls_process_finished().
SSL_F_TLS_PROCESS_HELLO_REQ
#define SSL_F_TLS_PROCESS_HELLO_REQ 507
Definition at line 2376 of file ssl.h.
SSL_F_TLS_PROCESS_HELLO_RETRY_REQUEST
#define SSL_F_TLS_PROCESS_HELLO_RETRY_REQUEST 511
Definition at line 2377 of file ssl.h.
SSL_F_TLS_PROCESS_INITIAL_SERVER_FLIGHT
#define SSL_F_TLS_PROCESS_INITIAL_SERVER_FLIGHT 442
Definition at line 2378 of file ssl.h.
SSL_F_TLS_PROCESS_KEY_EXCHANGE
#define SSL_F_TLS_PROCESS_KEY_EXCHANGE 365
Definition at line 2379 of file ssl.h.
SSL_F_TLS_PROCESS_KEY_UPDATE
#define SSL_F_TLS_PROCESS_KEY_UPDATE 518
Definition at line 2380 of file ssl.h.
Referenced by tls_process_key_update().
SSL_F_TLS_PROCESS_NEW_SESSION_TICKET
#define SSL_F_TLS_PROCESS_NEW_SESSION_TICKET 366
Definition at line 2381 of file ssl.h.
SSL_F_TLS_PROCESS_NEXT_PROTO
#define SSL_F_TLS_PROCESS_NEXT_PROTO 383
Definition at line 2382 of file ssl.h.
SSL_F_TLS_PROCESS_SERVER_CERTIFICATE
#define SSL_F_TLS_PROCESS_SERVER_CERTIFICATE 367
Definition at line 2383 of file ssl.h.
SSL_F_TLS_PROCESS_SERVER_DONE
#define SSL_F_TLS_PROCESS_SERVER_DONE 368
Definition at line 2384 of file ssl.h.
SSL_F_TLS_PROCESS_SERVER_HELLO
#define SSL_F_TLS_PROCESS_SERVER_HELLO 369
Definition at line 2385 of file ssl.h.
SSL_F_TLS_PROCESS_SKE_DHE
#define SSL_F_TLS_PROCESS_SKE_DHE 419
Definition at line 2386 of file ssl.h.
SSL_F_TLS_PROCESS_SKE_ECDHE
#define SSL_F_TLS_PROCESS_SKE_ECDHE 420
Definition at line 2387 of file ssl.h.
SSL_F_TLS_PROCESS_SKE_PSK_PREAMBLE
#define SSL_F_TLS_PROCESS_SKE_PSK_PREAMBLE 421
Definition at line 2388 of file ssl.h.
SSL_F_TLS_PROCESS_SKE_SRP
#define SSL_F_TLS_PROCESS_SKE_SRP 422
Definition at line 2389 of file ssl.h.
SSL_F_TLS_PSK_DO_BINDER
#define SSL_F_TLS_PSK_DO_BINDER 506
Definition at line 2390 of file ssl.h.
SSL_F_TLS_SCAN_CLIENTHELLO_TLSEXT
#define SSL_F_TLS_SCAN_CLIENTHELLO_TLSEXT 450
Definition at line 2391 of file ssl.h.
SSL_F_TLS_SETUP_HANDSHAKE
#define SSL_F_TLS_SETUP_HANDSHAKE 508
Definition at line 2392 of file ssl.h.
Referenced by tls_setup_handshake().
SSL_F_USE_CERTIFICATE_CHAIN_FILE
#define SSL_F_USE_CERTIFICATE_CHAIN_FILE 220
Definition at line 2393 of file ssl.h.
SSL_FILETYPE_ASN1
#define SSL_FILETYPE_ASN1 X509_FILETYPE_ASN1
Definition at line 218 of file ssl.h.
SSL_FILETYPE_PEM
#define SSL_FILETYPE_PEM X509_FILETYPE_PEM
Definition at line 219 of file ssl.h.
Referenced by create_ssl_ctx_pair(), and set_cert_stuff().
SSL_get0_certificate_types
#define SSL_get0_certificate_types (s, clist) SSL_ctrl(s, SSL_CTRL_GET_CLIENT_CERT_TYPES, 0, (char *)clist)
SSL_get0_chain_certs
#define SSL_get0_chain_certs (ctx, px509) SSL_ctrl(ctx,SSL_CTRL_GET_CHAIN_CERTS,0,px509)
SSL_get0_ec_point_formats
#define SSL_get0_ec_point_formats (s, plst) SSL_ctrl(s,SSL_CTRL_GET_EC_POINT_FORMATS,0,plst)
Referenced by ssl_print_point_formats().
SSL_get0_npn_negotiated
#define SSL_get0_npn_negotiated SSL_get0_next_proto_negotiated
Definition at line 683 of file ssl.h.
SSL_get0_raw_cipherlist
#define SSL_get0_raw_cipherlist (s, plst) SSL_ctrl(s,SSL_CTRL_GET_RAW_CIPHERLIST,0,plst)
SSL_get0_session
#define SSL_get0_session SSL_get_session/* just peek at pointer */
Definition at line 1720 of file ssl.h.
SSL_get1_curves
#define SSL_get1_curves (ctx, s) SSL_get1_groups((ctx), (s))
SSL_get1_groups
#define SSL_get1_groups (ctx, s) SSL_ctrl(ctx,SSL_CTRL_GET_GROUPS,0,(char *)s)
Referenced by ssl_print_groups().
SSL_get_app_data
#define SSL_get_app_data (s) (SSL_get_ex_data(s,0))
Definition at line 821 of file ssl.h.
SSL_get_cipher
#define SSL_get_cipher (s) SSL_CIPHER_get_name(SSL_get_current_cipher(s))
Definition at line 964 of file ssl.h.
SSL_get_cipher_bits
#define SSL_get_cipher_bits (s, np) SSL_CIPHER_get_bits(SSL_get_current_cipher(s),np)
Definition at line 966 of file ssl.h.
SSL_get_cipher_name
#define SSL_get_cipher_name (s) SSL_CIPHER_get_name(SSL_get_current_cipher(s))
Definition at line 970 of file ssl.h.
SSL_get_cipher_version
#define SSL_get_cipher_version (s) SSL_CIPHER_get_version(SSL_get_current_cipher(s))
Definition at line 968 of file ssl.h.
SSL_get_ex_new_index
#define SSL_get_ex_new_index (l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_SSL, l, p, newf, dupf, freef)
Definition at line 1742 of file ssl.h.
SSL_get_extms_support
#define SSL_get_extms_support (s) SSL_ctrl((s),SSL_CTRL_GET_EXTMS_SUPPORT,0,NULL)
Definition at line 541 of file ssl.h.
SSL_get_max_cert_list
#define SSL_get_max_cert_list (ssl) SSL_ctrl(ssl,SSL_CTRL_GET_MAX_CERT_LIST,0,NULL)
Definition at line 1776 of file ssl.h.
SSL_get_mode
#define SSL_get_mode (ssl) SSL_ctrl((ssl),SSL_CTRL_MODE,0,NULL)
Definition at line 504 of file ssl.h.
SSL_get_peer_signature_nid
#define SSL_get_peer_signature_nid (s, pn) SSL_ctrl(s,SSL_CTRL_GET_PEER_SIGNATURE_NID,0,pn)
SSL_get_secure_renegotiation_support
#define SSL_get_secure_renegotiation_support (ssl) SSL_ctrl((ssl), SSL_CTRL_GET_RI_SUPPORT, 0, NULL)
Definition at line 513 of file ssl.h.
SSL_get_server_tmp_key
#define SSL_get_server_tmp_key (s, pk) SSL_ctrl(s,SSL_CTRL_GET_SERVER_TMP_KEY,0,pk)
Referenced by ssl_print_tmp_key().
SSL_get_shared_curve
#define SSL_get_shared_curve (s, n) SSL_get_shared_group((s), (n))
SSL_get_shared_group
#define SSL_get_shared_group (s, n) SSL_ctrl(s,SSL_CTRL_GET_SHARED_GROUP,n,NULL)
Referenced by ssl_print_groups().
SSL_get_time
#define SSL_get_time (a) SSL_SESSION_get_time(a)
Definition at line 972 of file ssl.h.
SSL_get_timeout
#define SSL_get_timeout (a) SSL_SESSION_get_timeout(a)
Definition at line 974 of file ssl.h.
SSL_heartbeat
#define SSL_heartbeat (ssl) SSL_ctrl((ssl),SSL_CTRL_DTLS_EXT_SEND_HEARTBEAT,0,NULL)
Definition at line 517 of file ssl.h.
SSL_in_accept_init
#define SSL_in_accept_init (a) (SSL_in_init(a) && SSL_is_server(a))
Definition at line 927 of file ssl.h.
SSL_in_connect_init
#define SSL_in_connect_init (a) (SSL_in_init(a) && !SSL_is_server(a))
Definition at line 926 of file ssl.h.
SSL_KEY_UPDATE_NONE
#define SSL_KEY_UPDATE_NONE -1
Definition at line 830 of file ssl.h.
Referenced by SSL_new(), and tls_construct_key_update().
SSL_KEY_UPDATE_NOT_REQUESTED
#define SSL_KEY_UPDATE_NOT_REQUESTED 0
Definition at line 832 of file ssl.h.
Referenced by SSL_key_update().
SSL_KEY_UPDATE_REQUESTED
#define SSL_KEY_UPDATE_REQUESTED 1
Definition at line 833 of file ssl.h.
Referenced by SSL_key_update().
SSL_library_init
#define SSL_library_init () OPENSSL_init_ssl(0, NULL)
Definition at line 1691 of file ssl.h.
SSL_load_error_strings
#define SSL_load_error_strings ()
Value:
OPENSSL_init_ssl(OPENSSL_INIT_LOAD_SSL_STRINGS \
                     | OPENSSL_INIT_LOAD_CRYPTO_STRINGS, NULL)
Definition at line 1412 of file ssl.h.
SSL_MAC_FLAG_READ_MAC_STREAM
#define SSL_MAC_FLAG_READ_MAC_STREAM 1
Definition at line 776 of file ssl.h.
SSL_MAC_FLAG_WRITE_MAC_STREAM
#define SSL_MAC_FLAG_WRITE_MAC_STREAM 2
Definition at line 777 of file ssl.h.
SSL_MAX_CERT_LIST_DEFAULT
#define SSL_MAX_CERT_LIST_DEFAULT 1024*100
Definition at line 557 of file ssl.h.
SSL_MAX_KEY_ARG_LENGTH
#define SSL_MAX_KEY_ARG_LENGTH 8
Definition at line 78 of file ssl.h.
SSL_MAX_MASTER_KEY_LENGTH
#define SSL_MAX_MASTER_KEY_LENGTH 48
Definition at line 79 of file ssl.h.
Referenced by SRP_Calc_A_param(), and SSL_srp_server_param_with_username().
SSL_MAX_PIPELINES
#define SSL_MAX_PIPELINES 32
Definition at line 83 of file ssl.h.
Referenced by RECORD_LAYER_clear(), RECORD_LAYER_init(), RECORD_LAYER_release(), SSL_ctrl(), SSL_CTX_ctrl(), and tls1_enc().
SSL_MAX_SID_CTX_LENGTH
#define SSL_MAX_SID_CTX_LENGTH 32
Definition at line 75 of file ssl.h.
Referenced by SSL_SESSION_set1_id_context(), and SSL_set_session_id_context().
SSL_MAX_SSL_SESSION_ID_LENGTH
#define SSL_MAX_SSL_SESSION_ID_LENGTH 32
Definition at line 74 of file ssl.h.
Referenced by SSL_SESSION_set1_id().
SSL_MIN_RSA_MODULUS_LENGTH_IN_BYTES
#define SSL_MIN_RSA_MODULUS_LENGTH_IN_BYTES (512/8)
Definition at line 77 of file ssl.h.
SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER
#define SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER 0x00000002U
Definition at line 383 of file ssl.h.
SSL_MODE_ASYNC
#define SSL_MODE_ASYNC 0x00000100U
Definition at line 415 of file ssl.h.
Referenced by SSL_peek_ex(), SSL_read_ex(), SSL_shutdown(), and SSL_write_ex().
SSL_MODE_AUTO_RETRY
#define SSL_MODE_AUTO_RETRY 0x00000004U
Definition at line 387 of file ssl.h.
Referenced by process_responder().
SSL_MODE_ENABLE_PARTIAL_WRITE
#define SSL_MODE_ENABLE_PARTIAL_WRITE 0x00000001U
Definition at line 376 of file ssl.h.
SSL_MODE_NO_AUTO_CHAIN
#define SSL_MODE_NO_AUTO_CHAIN 0x00000008U
Definition at line 389 of file ssl.h.
SSL_MODE_RELEASE_BUFFERS
#define SSL_MODE_RELEASE_BUFFERS 0x00000010U
Definition at line 395 of file ssl.h.
SSL_MODE_SEND_CLIENTHELLO_TIME
#define SSL_MODE_SEND_CLIENTHELLO_TIME 0x00000020U
Definition at line 401 of file ssl.h.
Referenced by ssl_fill_hello_random().
SSL_MODE_SEND_FALLBACK_SCSV
#define SSL_MODE_SEND_FALLBACK_SCSV 0x00000080U
Definition at line 411 of file ssl.h.
SSL_MODE_SEND_SERVERHELLO_TIME
#define SSL_MODE_SEND_SERVERHELLO_TIME 0x00000040U
Definition at line 402 of file ssl.h.
Referenced by ssl_fill_hello_random().
SSL_need_tmp_RSA
#define SSL_need_tmp_RSA (ssl) 0
SSL_NOTHING
#define SSL_NOTHING 1
Definition at line 761 of file ssl.h.
Referenced by SSL_clear(), SSL_read_ex(), SSL_write_ex(), statem_flush(), and tls_prepare_client_certificate().
SSL_num_renegotiations
#define SSL_num_renegotiations (ssl) SSL_ctrl((ssl),SSL_CTRL_GET_NUM_RENEGOTIATIONS,0,NULL)
SSL_OP_ALL
#define SSL_OP_ALL 0x80000BFFU
Definition at line 305 of file ssl.h.
SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION
#define SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION 0x00040000U
Definition at line 324 of file ssl.h.
Referenced by tls_setup_handshake().
SSL_OP_CIPHER_SERVER_PREFERENCE
#define SSL_OP_CIPHER_SERVER_PREFERENCE 0x00400000U
Definition at line 336 of file ssl.h.
SSL_OP_CISCO_ANYCONNECT
#define SSL_OP_CISCO_ANYCONNECT 0x00008000U
Definition at line 316 of file ssl.h.
SSL_OP_COOKIE_EXCHANGE
#define SSL_OP_COOKIE_EXCHANGE 0x00002000U
Definition at line 310 of file ssl.h.
SSL_OP_CRYPTOPRO_TLSEXT_BUG
#define SSL_OP_CRYPTOPRO_TLSEXT_BUG 0x80000000U
Definition at line 370 of file ssl.h.
Referenced by tls_construct_stoc_cryptopro_bug().
SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS
#define SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS 0x00000800U
Definition at line 299 of file ssl.h.
Referenced by ssl3_setup_write_buffer().
SSL_OP_EPHEMERAL_RSA
#define SSL_OP_EPHEMERAL_RSA 0x0
Definition at line 332 of file ssl.h.
SSL_OP_LEGACY_SERVER_CONNECT
#define SSL_OP_LEGACY_SERVER_CONNECT 0x00000004U
Definition at line 270 of file ssl.h.
SSL_OP_MICROSOFT_BIG_SSLV3_BUFFER
#define SSL_OP_MICROSOFT_BIG_SSLV3_BUFFER 0x0U
Definition at line 275 of file ssl.h.
SSL_OP_MICROSOFT_SESS_ID_BUG
#define SSL_OP_MICROSOFT_SESS_ID_BUG 0x0
Definition at line 288 of file ssl.h.
SSL_OP_MSIE_SSLV2_RSA_PADDING
#define SSL_OP_MSIE_SSLV2_RSA_PADDING 0x0
Definition at line 284 of file ssl.h.
SSL_OP_NETSCAPE_CA_DN_BUG
#define SSL_OP_NETSCAPE_CA_DN_BUG 0x0
Definition at line 363 of file ssl.h.
SSL_OP_NETSCAPE_CHALLENGE_BUG
#define SSL_OP_NETSCAPE_CHALLENGE_BUG 0x0
Definition at line 289 of file ssl.h.
SSL_OP_NETSCAPE_DEMO_CIPHER_CHANGE_BUG
#define SSL_OP_NETSCAPE_DEMO_CIPHER_CHANGE_BUG 0x0U
Definition at line 364 of file ssl.h.
SSL_OP_NETSCAPE_REUSE_CIPHER_CHANGE_BUG
#define SSL_OP_NETSCAPE_REUSE_CIPHER_CHANGE_BUG 0x0U
Definition at line 273 of file ssl.h.
SSL_OP_NO_COMPRESSION
#define SSL_OP_NO_COMPRESSION 0x00020000U
Definition at line 322 of file ssl.h.
Referenced by ssl_allow_compression().
SSL_OP_NO_DTLS_MASK
#define SSL_OP_NO_DTLS_MASK (SSL_OP_NO_DTLSv1|SSL_OP_NO_DTLSv1_2)
Definition at line 357 of file ssl.h.
SSL_OP_NO_DTLSv1
#define SSL_OP_NO_DTLSv1 0x04000000U
Definition at line 352 of file ssl.h.
SSL_OP_NO_DTLSv1_2
#define SSL_OP_NO_DTLSv1_2 0x08000000U
Definition at line 353 of file ssl.h.
SSL_OP_NO_ENCRYPT_THEN_MAC
#define SSL_OP_NO_ENCRYPT_THEN_MAC 0x00080000U
Definition at line 326 of file ssl.h.
Referenced by tls_construct_ctos_etm(), tls_parse_ctos_etm(), and tls_parse_stoc_etm().
SSL_OP_NO_QUERY_MTU
#define SSL_OP_NO_QUERY_MTU 0x00001000U
Definition at line 308 of file ssl.h.
Referenced by dtls1_check_timeout_num(), and dtls1_query_mtu().
SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION
#define SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION 0x00010000U
Definition at line 320 of file ssl.h.
SSL_OP_NO_SSL_MASK
#define SSL_OP_NO_SSL_MASK
Value:
(SSL_OP_NO_SSLv3|\
        SSL_OP_NO_TLSv1|SSL_OP_NO_TLSv1_1|SSL_OP_NO_TLSv1_2|SSL_OP_NO_TLSv1_3)
Definition at line 355 of file ssl.h.
SSL_OP_NO_SSLv2
#define SSL_OP_NO_SSLv2 0x00000000U
Definition at line 345 of file ssl.h.
SSL_OP_NO_SSLv3
#define SSL_OP_NO_SSLv3 0x02000000U
Definition at line 346 of file ssl.h.
SSL_OP_NO_TICKET
#define SSL_OP_NO_TICKET 0x00004000U
Definition at line 312 of file ssl.h.
Referenced by tls_use_ticket().
SSL_OP_NO_TLSv1
#define SSL_OP_NO_TLSv1 0x04000000U
Definition at line 347 of file ssl.h.
SSL_OP_NO_TLSv1_1
#define SSL_OP_NO_TLSv1_1 0x10000000U
Definition at line 349 of file ssl.h.
SSL_OP_NO_TLSv1_2
#define SSL_OP_NO_TLSv1_2 0x08000000U
Definition at line 348 of file ssl.h.
SSL_OP_NO_TLSv1_3
#define SSL_OP_NO_TLSv1_3 0x20000000U
Definition at line 350 of file ssl.h.
SSL_OP_PKCS1_CHECK_1
#define SSL_OP_PKCS1_CHECK_1 0x0
Definition at line 361 of file ssl.h.
SSL_OP_PKCS1_CHECK_2
#define SSL_OP_PKCS1_CHECK_2 0x0
Definition at line 362 of file ssl.h.
SSL_OP_SAFARI_ECDHE_ECDSA_BUG
#define SSL_OP_SAFARI_ECDHE_ECDSA_BUG 0x00000040U
Definition at line 276 of file ssl.h.
SSL_OP_SINGLE_DH_USE
#define SSL_OP_SINGLE_DH_USE 0x0
Definition at line 330 of file ssl.h.
SSL_OP_SINGLE_ECDH_USE
#define SSL_OP_SINGLE_ECDH_USE 0x0
Definition at line 328 of file ssl.h.
SSL_OP_SSLEAY_080_CLIENT_DH_BUG
#define SSL_OP_SSLEAY_080_CLIENT_DH_BUG 0x0
Definition at line 278 of file ssl.h.
SSL_OP_SSLREF2_REUSE_CERT_TYPE_BUG
#define SSL_OP_SSLREF2_REUSE_CERT_TYPE_BUG 0x0
Definition at line 286 of file ssl.h.
SSL_OP_TLS_BLOCK_PADDING_BUG
#define SSL_OP_TLS_BLOCK_PADDING_BUG 0x0U
Definition at line 281 of file ssl.h.
SSL_OP_TLS_D5_BUG
#define SSL_OP_TLS_D5_BUG 0x0U
Definition at line 279 of file ssl.h.
SSL_OP_TLS_ROLLBACK_BUG
#define SSL_OP_TLS_ROLLBACK_BUG 0x00800000U
Definition at line 343 of file ssl.h.
SSL_OP_TLSEXT_PADDING
#define SSL_OP_TLSEXT_PADDING 0x00000010U
Definition at line 274 of file ssl.h.
Referenced by tls_construct_ctos_padding().
SSL_R_APP_DATA_IN_HANDSHAKE
#define SSL_R_APP_DATA_IN_HANDSHAKE 100
Definition at line 2396 of file ssl.h.
SSL_R_AT_LEAST_TLS_1_0_NEEDED_IN_FIPS_MODE
#define SSL_R_AT_LEAST_TLS_1_0_NEEDED_IN_FIPS_MODE 143
Definition at line 2398 of file ssl.h.
SSL_R_AT_LEAST_TLS_1_2_NEEDED_IN_SUITEB_MODE
#define SSL_R_AT_LEAST_TLS_1_2_NEEDED_IN_SUITEB_MODE 158
Definition at line 2399 of file ssl.h.
SSL_R_ATTEMPT_TO_REUSE_SESSION_IN_DIFFERENT_CONTEXT
#define SSL_R_ATTEMPT_TO_REUSE_SESSION_IN_DIFFERENT_CONTEXT 272
Definition at line 2397 of file ssl.h.
SSL_R_BAD_CHANGE_CIPHER_SPEC
#define SSL_R_BAD_CHANGE_CIPHER_SPEC 103
Definition at line 2400 of file ssl.h.
Referenced by tls_get_message_header().
SSL_R_BAD_DATA
#define SSL_R_BAD_DATA 390
Definition at line 2401 of file ssl.h.
SSL_R_BAD_DATA_RETURNED_BY_CALLBACK
#define SSL_R_BAD_DATA_RETURNED_BY_CALLBACK 106
Definition at line 2402 of file ssl.h.
SSL_R_BAD_DECOMPRESSION
#define SSL_R_BAD_DECOMPRESSION 107
Definition at line 2403 of file ssl.h.
SSL_R_BAD_DH_VALUE
#define SSL_R_BAD_DH_VALUE 102
Definition at line 2404 of file ssl.h.
SSL_R_BAD_DIGEST_LENGTH
#define SSL_R_BAD_DIGEST_LENGTH 111
Definition at line 2405 of file ssl.h.
SSL_R_BAD_ECC_CERT
#define SSL_R_BAD_ECC_CERT 304
Definition at line 2406 of file ssl.h.
SSL_R_BAD_ECPOINT
#define SSL_R_BAD_ECPOINT 306
Definition at line 2407 of file ssl.h.
SSL_R_BAD_EXTENSION
#define SSL_R_BAD_EXTENSION 110
Definition at line 2408 of file ssl.h.
SSL_R_BAD_HANDSHAKE_LENGTH
#define SSL_R_BAD_HANDSHAKE_LENGTH 332
Definition at line 2409 of file ssl.h.
SSL_R_BAD_HELLO_REQUEST
#define SSL_R_BAD_HELLO_REQUEST 105
Definition at line 2410 of file ssl.h.
SSL_R_BAD_KEY_SHARE
#define SSL_R_BAD_KEY_SHARE 108
Definition at line 2411 of file ssl.h.
SSL_R_BAD_KEY_UPDATE
#define SSL_R_BAD_KEY_UPDATE 122
Definition at line 2412 of file ssl.h.
SSL_R_BAD_LENGTH
#define SSL_R_BAD_LENGTH 271
Definition at line 2413 of file ssl.h.
SSL_R_BAD_PACKET_LENGTH
#define SSL_R_BAD_PACKET_LENGTH 115
Definition at line 2414 of file ssl.h.
SSL_R_BAD_PROTOCOL_VERSION_NUMBER
#define SSL_R_BAD_PROTOCOL_VERSION_NUMBER 116
Definition at line 2415 of file ssl.h.
SSL_R_BAD_PSK_IDENTITY
#define SSL_R_BAD_PSK_IDENTITY 114
Definition at line 2416 of file ssl.h.
SSL_R_BAD_RECORD_TYPE
#define SSL_R_BAD_RECORD_TYPE 443
Definition at line 2417 of file ssl.h.
SSL_R_BAD_RSA_ENCRYPT
#define SSL_R_BAD_RSA_ENCRYPT 119
Definition at line 2418 of file ssl.h.
SSL_R_BAD_SIGNATURE
#define SSL_R_BAD_SIGNATURE 123
Definition at line 2419 of file ssl.h.
SSL_R_BAD_SRP_A_LENGTH
#define SSL_R_BAD_SRP_A_LENGTH 347
Definition at line 2420 of file ssl.h.
SSL_R_BAD_SRP_PARAMETERS
#define SSL_R_BAD_SRP_PARAMETERS 371
Definition at line 2421 of file ssl.h.
SSL_R_BAD_SRTP_MKI_VALUE
#define SSL_R_BAD_SRTP_MKI_VALUE 352
Definition at line 2422 of file ssl.h.
SSL_R_BAD_SRTP_PROTECTION_PROFILE_LIST
#define SSL_R_BAD_SRTP_PROTECTION_PROFILE_LIST 353
Definition at line 2423 of file ssl.h.
SSL_R_BAD_SSL_FILETYPE
#define SSL_R_BAD_SSL_FILETYPE 124
Definition at line 2424 of file ssl.h.
SSL_R_BAD_VALUE
#define SSL_R_BAD_VALUE 384
Definition at line 2425 of file ssl.h.
SSL_R_BAD_WRITE_RETRY
#define SSL_R_BAD_WRITE_RETRY 127
Definition at line 2426 of file ssl.h.
SSL_R_BIO_NOT_SET
#define SSL_R_BIO_NOT_SET 128
Definition at line 2427 of file ssl.h.
SSL_R_BLOCK_CIPHER_PAD_IS_WRONG
#define SSL_R_BLOCK_CIPHER_PAD_IS_WRONG 129
Definition at line 2428 of file ssl.h.
SSL_R_BN_LIB
#define SSL_R_BN_LIB 130
Definition at line 2429 of file ssl.h.
SSL_R_CA_DN_LENGTH_MISMATCH
#define SSL_R_CA_DN_LENGTH_MISMATCH 131
Definition at line 2431 of file ssl.h.
SSL_R_CA_KEY_TOO_SMALL
#define SSL_R_CA_KEY_TOO_SMALL 397
Definition at line 2432 of file ssl.h.
SSL_R_CA_MD_TOO_WEAK
#define SSL_R_CA_MD_TOO_WEAK 398
Definition at line 2433 of file ssl.h.
SSL_R_CANNOT_CHANGE_CIPHER
#define SSL_R_CANNOT_CHANGE_CIPHER 109
Definition at line 2430 of file ssl.h.
SSL_R_CCS_RECEIVED_EARLY
#define SSL_R_CCS_RECEIVED_EARLY 133
Definition at line 2434 of file ssl.h.
Referenced by ssl3_do_change_cipher_spec(), and tls_get_message_header().
SSL_R_CERT_CB_ERROR
#define SSL_R_CERT_CB_ERROR 377
Definition at line 2436 of file ssl.h.
SSL_R_CERT_LENGTH_MISMATCH
#define SSL_R_CERT_LENGTH_MISMATCH 135
Definition at line 2437 of file ssl.h.
SSL_R_CERTIFICATE_VERIFY_FAILED
#define SSL_R_CERTIFICATE_VERIFY_FAILED 134
Definition at line 2435 of file ssl.h.
Referenced by ssl_build_cert_chain().
SSL_R_CIPHER_CODE_WRONG_LENGTH
#define SSL_R_CIPHER_CODE_WRONG_LENGTH 137
Definition at line 2438 of file ssl.h.
SSL_R_CIPHER_OR_HASH_UNAVAILABLE
#define SSL_R_CIPHER_OR_HASH_UNAVAILABLE 138
Definition at line 2439 of file ssl.h.
SSL_R_CLIENTHELLO_TLSEXT
#define SSL_R_CLIENTHELLO_TLSEXT 226
Definition at line 2440 of file ssl.h.
SSL_R_COMPRESSED_LENGTH_TOO_LONG
#define SSL_R_COMPRESSED_LENGTH_TOO_LONG 140
Definition at line 2441 of file ssl.h.
SSL_R_COMPRESSION_DISABLED
#define SSL_R_COMPRESSION_DISABLED 343
Definition at line 2442 of file ssl.h.
SSL_R_COMPRESSION_FAILURE
#define SSL_R_COMPRESSION_FAILURE 141
Definition at line 2443 of file ssl.h.
SSL_R_COMPRESSION_ID_NOT_WITHIN_PRIVATE_RANGE
#define SSL_R_COMPRESSION_ID_NOT_WITHIN_PRIVATE_RANGE 307
Definition at line 2444 of file ssl.h.
Referenced by SSL_COMP_add_compression_method().
SSL_R_COMPRESSION_LIBRARY_ERROR
#define SSL_R_COMPRESSION_LIBRARY_ERROR 142
Definition at line 2445 of file ssl.h.
SSL_R_CONNECTION_TYPE_NOT_SET
#define SSL_R_CONNECTION_TYPE_NOT_SET 144
Definition at line 2446 of file ssl.h.
SSL_R_CONTEXT_NOT_DANE_ENABLED
#define SSL_R_CONTEXT_NOT_DANE_ENABLED 167
Definition at line 2447 of file ssl.h.
Referenced by SSL_dane_enable().
SSL_R_COOKIE_GEN_CALLBACK_FAILURE
#define SSL_R_COOKIE_GEN_CALLBACK_FAILURE 400
Definition at line 2448 of file ssl.h.
Referenced by dtls_construct_hello_verify_request().
SSL_R_COOKIE_MISMATCH
#define SSL_R_COOKIE_MISMATCH 308
Definition at line 2449 of file ssl.h.
SSL_R_CUSTOM_EXT_HANDLER_ALREADY_INSTALLED
#define SSL_R_CUSTOM_EXT_HANDLER_ALREADY_INSTALLED 206
Definition at line 2450 of file ssl.h.
SSL_R_DANE_ALREADY_ENABLED
#define SSL_R_DANE_ALREADY_ENABLED 172
Definition at line 2451 of file ssl.h.
Referenced by SSL_dane_enable().
SSL_R_DANE_CANNOT_OVERRIDE_MTYPE_FULL
#define SSL_R_DANE_CANNOT_OVERRIDE_MTYPE_FULL 173
Definition at line 2452 of file ssl.h.
SSL_R_DANE_NOT_ENABLED
#define SSL_R_DANE_NOT_ENABLED 175
Definition at line 2453 of file ssl.h.
SSL_R_DANE_TLSA_BAD_CERTIFICATE
#define SSL_R_DANE_TLSA_BAD_CERTIFICATE 180
Definition at line 2454 of file ssl.h.
SSL_R_DANE_TLSA_BAD_CERTIFICATE_USAGE
#define SSL_R_DANE_TLSA_BAD_CERTIFICATE_USAGE 184
Definition at line 2455 of file ssl.h.
SSL_R_DANE_TLSA_BAD_DATA_LENGTH
#define SSL_R_DANE_TLSA_BAD_DATA_LENGTH 189
Definition at line 2456 of file ssl.h.
SSL_R_DANE_TLSA_BAD_DIGEST_LENGTH
#define SSL_R_DANE_TLSA_BAD_DIGEST_LENGTH 192
Definition at line 2457 of file ssl.h.
SSL_R_DANE_TLSA_BAD_MATCHING_TYPE
#define SSL_R_DANE_TLSA_BAD_MATCHING_TYPE 200
Definition at line 2458 of file ssl.h.
SSL_R_DANE_TLSA_BAD_PUBLIC_KEY
#define SSL_R_DANE_TLSA_BAD_PUBLIC_KEY 201
Definition at line 2459 of file ssl.h.
SSL_R_DANE_TLSA_BAD_SELECTOR
#define SSL_R_DANE_TLSA_BAD_SELECTOR 202
Definition at line 2460 of file ssl.h.
SSL_R_DANE_TLSA_NULL_DATA
#define SSL_R_DANE_TLSA_NULL_DATA 203
Definition at line 2461 of file ssl.h.
SSL_R_DATA_BETWEEN_CCS_AND_FINISHED
#define SSL_R_DATA_BETWEEN_CCS_AND_FINISHED 145
Definition at line 2462 of file ssl.h.
SSL_R_DATA_LENGTH_TOO_LONG
#define SSL_R_DATA_LENGTH_TOO_LONG 146
Definition at line 2463 of file ssl.h.
Referenced by SSL_CTX_use_psk_identity_hint(), and SSL_use_psk_identity_hint().
SSL_R_DECRYPTION_FAILED
#define SSL_R_DECRYPTION_FAILED 147
Definition at line 2464 of file ssl.h.
SSL_R_DECRYPTION_FAILED_OR_BAD_RECORD_MAC
#define SSL_R_DECRYPTION_FAILED_OR_BAD_RECORD_MAC 281
Definition at line 2465 of file ssl.h.
SSL_R_DH_KEY_TOO_SMALL
#define SSL_R_DH_KEY_TOO_SMALL 394
Definition at line 2466 of file ssl.h.
Referenced by ssl3_ctx_ctrl().
SSL_R_DH_PUBLIC_VALUE_LENGTH_IS_WRONG
#define SSL_R_DH_PUBLIC_VALUE_LENGTH_IS_WRONG 148
Definition at line 2467 of file ssl.h.
SSL_R_DIGEST_CHECK_FAILED
#define SSL_R_DIGEST_CHECK_FAILED 149
Definition at line 2468 of file ssl.h.
SSL_R_DTLS_MESSAGE_TOO_BIG
#define SSL_R_DTLS_MESSAGE_TOO_BIG 334
Definition at line 2469 of file ssl.h.
Referenced by dtls1_write_app_data_bytes().
SSL_R_DUPLICATE_COMPRESSION_ID
#define SSL_R_DUPLICATE_COMPRESSION_ID 309
Definition at line 2470 of file ssl.h.
SSL_R_ECC_CERT_NOT_FOR_SIGNING
#define SSL_R_ECC_CERT_NOT_FOR_SIGNING 318
Definition at line 2471 of file ssl.h.
Referenced by ssl_check_srvr_ecc_cert_and_alg().
SSL_R_ECDH_REQUIRED_FOR_SUITEB_MODE
#define SSL_R_ECDH_REQUIRED_FOR_SUITEB_MODE 374
Definition at line 2472 of file ssl.h.
SSL_R_EE_KEY_TOO_SMALL
#define SSL_R_EE_KEY_TOO_SMALL 399
Definition at line 2473 of file ssl.h.
SSL_R_EMPTY_SRTP_PROTECTION_PROFILE_LIST
#define SSL_R_EMPTY_SRTP_PROTECTION_PROFILE_LIST 354
Definition at line 2474 of file ssl.h.
SSL_R_ENCRYPTED_LENGTH_TOO_LONG
#define SSL_R_ENCRYPTED_LENGTH_TOO_LONG 150
Definition at line 2475 of file ssl.h.
SSL_R_ERROR_IN_RECEIVED_CIPHER_LIST
#define SSL_R_ERROR_IN_RECEIVED_CIPHER_LIST 151
Definition at line 2476 of file ssl.h.
SSL_R_ERROR_SETTING_TLSA_BASE_DOMAIN
#define SSL_R_ERROR_SETTING_TLSA_BASE_DOMAIN 204
Definition at line 2477 of file ssl.h.
Referenced by SSL_dane_enable().
SSL_R_EXCESSIVE_MESSAGE_SIZE
#define SSL_R_EXCESSIVE_MESSAGE_SIZE 152
Definition at line 2478 of file ssl.h.
Referenced by tls_get_message_header().
SSL_R_EXTRA_DATA_IN_MESSAGE
#define SSL_R_EXTRA_DATA_IN_MESSAGE 153
Definition at line 2479 of file ssl.h.
SSL_R_FAILED_TO_INIT_ASYNC
#define SSL_R_FAILED_TO_INIT_ASYNC 405
Definition at line 2480 of file ssl.h.
SSL_R_FRAGMENTED_CLIENT_HELLO
#define SSL_R_FRAGMENTED_CLIENT_HELLO 401
Definition at line 2481 of file ssl.h.
SSL_R_GOT_A_FIN_BEFORE_A_CCS
#define SSL_R_GOT_A_FIN_BEFORE_A_CCS 154
Definition at line 2482 of file ssl.h.
Referenced by tls_process_finished().
SSL_R_HTTP_REQUEST
#define SSL_R_HTTP_REQUEST 156
Definition at line 2484 of file ssl.h.
SSL_R_HTTPS_PROXY_REQUEST
#define SSL_R_HTTPS_PROXY_REQUEST 155
Definition at line 2483 of file ssl.h.
SSL_R_ILLEGAL_SUITEB_DIGEST
#define SSL_R_ILLEGAL_SUITEB_DIGEST 380
Definition at line 2485 of file ssl.h.
SSL_R_INAPPROPRIATE_FALLBACK
#define SSL_R_INAPPROPRIATE_FALLBACK 373
Definition at line 2486 of file ssl.h.
SSL_R_INCONSISTENT_COMPRESSION
#define SSL_R_INCONSISTENT_COMPRESSION 340
Definition at line 2487 of file ssl.h.
SSL_R_INCONSISTENT_EXTMS
#define SSL_R_INCONSISTENT_EXTMS 104
Definition at line 2488 of file ssl.h.
SSL_R_INVALID_COMMAND
#define SSL_R_INVALID_COMMAND 280
Definition at line 2489 of file ssl.h.
SSL_R_INVALID_COMPRESSION_ALGORITHM
#define SSL_R_INVALID_COMPRESSION_ALGORITHM 341
Definition at line 2490 of file ssl.h.
SSL_R_INVALID_CONFIGURATION_NAME
#define SSL_R_INVALID_CONFIGURATION_NAME 113
Definition at line 2491 of file ssl.h.
SSL_R_INVALID_CT_VALIDATION_TYPE
#define SSL_R_INVALID_CT_VALIDATION_TYPE 212
Definition at line 2492 of file ssl.h.
Referenced by SSL_CTX_enable_ct(), and SSL_enable_ct().
SSL_R_INVALID_KEY_UPDATE_TYPE
#define SSL_R_INVALID_KEY_UPDATE_TYPE 120
Definition at line 2493 of file ssl.h.
Referenced by SSL_key_update().
SSL_R_INVALID_NULL_CMD_NAME
#define SSL_R_INVALID_NULL_CMD_NAME 385
Definition at line 2494 of file ssl.h.
Referenced by SSL_CONF_cmd().
SSL_R_INVALID_SEQUENCE_NUMBER
#define SSL_R_INVALID_SEQUENCE_NUMBER 402
Definition at line 2495 of file ssl.h.
SSL_R_INVALID_SERVERINFO_DATA
#define SSL_R_INVALID_SERVERINFO_DATA 388
Definition at line 2496 of file ssl.h.
SSL_R_INVALID_SRP_USERNAME
#define SSL_R_INVALID_SRP_USERNAME 357
Definition at line 2497 of file ssl.h.
SSL_R_INVALID_STATUS_RESPONSE
#define SSL_R_INVALID_STATUS_RESPONSE 328
Definition at line 2498 of file ssl.h.
SSL_R_INVALID_TICKET_KEYS_LENGTH
#define SSL_R_INVALID_TICKET_KEYS_LENGTH 325
Definition at line 2499 of file ssl.h.
SSL_R_LENGTH_MISMATCH
#define SSL_R_LENGTH_MISMATCH 159
Definition at line 2500 of file ssl.h.
SSL_R_LENGTH_TOO_LONG
#define SSL_R_LENGTH_TOO_LONG 404
Definition at line 2501 of file ssl.h.
SSL_R_LENGTH_TOO_SHORT
#define SSL_R_LENGTH_TOO_SHORT 160
Definition at line 2502 of file ssl.h.
SSL_R_LIBRARY_BUG
#define SSL_R_LIBRARY_BUG 274
Definition at line 2503 of file ssl.h.
SSL_R_LIBRARY_HAS_NO_CIPHERS
#define SSL_R_LIBRARY_HAS_NO_CIPHERS 161
Definition at line 2504 of file ssl.h.
SSL_R_MISSING_DSA_SIGNING_CERT
#define SSL_R_MISSING_DSA_SIGNING_CERT 165
Definition at line 2505 of file ssl.h.
SSL_R_MISSING_ECDSA_SIGNING_CERT
#define SSL_R_MISSING_ECDSA_SIGNING_CERT 381
Definition at line 2506 of file ssl.h.
SSL_R_MISSING_RSA_CERTIFICATE
#define SSL_R_MISSING_RSA_CERTIFICATE 168
Definition at line 2507 of file ssl.h.
SSL_R_MISSING_RSA_ENCRYPTING_CERT
#define SSL_R_MISSING_RSA_ENCRYPTING_CERT 169
Definition at line 2508 of file ssl.h.
SSL_R_MISSING_RSA_SIGNING_CERT
#define SSL_R_MISSING_RSA_SIGNING_CERT 170
Definition at line 2509 of file ssl.h.
SSL_R_MISSING_SIGALGS_EXTENSION
#define SSL_R_MISSING_SIGALGS_EXTENSION 112
Definition at line 2510 of file ssl.h.
SSL_R_MISSING_SRP_PARAM
#define SSL_R_MISSING_SRP_PARAM 358
Definition at line 2511 of file ssl.h.
SSL_R_MISSING_TMP_DH_KEY
#define SSL_R_MISSING_TMP_DH_KEY 171
Definition at line 2512 of file ssl.h.
SSL_R_MISSING_TMP_ECDH_KEY
#define SSL_R_MISSING_TMP_ECDH_KEY 311
Definition at line 2513 of file ssl.h.
SSL_R_NO_CERTIFICATE_ASSIGNED
#define SSL_R_NO_CERTIFICATE_ASSIGNED 177
Definition at line 2515 of file ssl.h.
Referenced by SSL_check_private_key(), and SSL_CTX_check_private_key().
SSL_R_NO_CERTIFICATE_SET
#define SSL_R_NO_CERTIFICATE_SET 179
Definition at line 2516 of file ssl.h.
Referenced by ssl_build_cert_chain().
SSL_R_NO_CERTIFICATES_RETURNED
#define SSL_R_NO_CERTIFICATES_RETURNED 176
Definition at line 2514 of file ssl.h.
SSL_R_NO_CIPHER_MATCH
#define SSL_R_NO_CIPHER_MATCH 185
Definition at line 2519 of file ssl.h.
Referenced by SSL_CTX_set_cipher_list(), and SSL_set_cipher_list().
SSL_R_NO_CIPHERS_AVAILABLE
#define SSL_R_NO_CIPHERS_AVAILABLE 181
Definition at line 2517 of file ssl.h.
SSL_R_NO_CIPHERS_SPECIFIED
#define SSL_R_NO_CIPHERS_SPECIFIED 183
Definition at line 2518 of file ssl.h.
SSL_R_NO_CLIENT_CERT_METHOD
#define SSL_R_NO_CLIENT_CERT_METHOD 331
Definition at line 2520 of file ssl.h.
Referenced by SSL_CTX_set_client_cert_engine().
SSL_R_NO_COMPRESSION_SPECIFIED
#define SSL_R_NO_COMPRESSION_SPECIFIED 187
Definition at line 2521 of file ssl.h.
SSL_R_NO_GOST_CERTIFICATE_SENT_BY_PEER
#define SSL_R_NO_GOST_CERTIFICATE_SENT_BY_PEER 330
Definition at line 2522 of file ssl.h.
SSL_R_NO_METHOD_SPECIFIED
#define SSL_R_NO_METHOD_SPECIFIED 188
Definition at line 2523 of file ssl.h.
Referenced by SSL_clear().
SSL_R_NO_PEM_EXTENSIONS
#define SSL_R_NO_PEM_EXTENSIONS 389
Definition at line 2524 of file ssl.h.
SSL_R_NO_PRIVATE_KEY_ASSIGNED
#define SSL_R_NO_PRIVATE_KEY_ASSIGNED 190
Definition at line 2525 of file ssl.h.
Referenced by SSL_check_private_key(), and SSL_CTX_check_private_key().
SSL_R_NO_PROTOCOLS_AVAILABLE
#define SSL_R_NO_PROTOCOLS_AVAILABLE 191
Definition at line 2526 of file ssl.h.
SSL_R_NO_RENEGOTIATION
#define SSL_R_NO_RENEGOTIATION 339
Definition at line 2527 of file ssl.h.
SSL_R_NO_REQUIRED_DIGEST
#define SSL_R_NO_REQUIRED_DIGEST 324
Definition at line 2528 of file ssl.h.
SSL_R_NO_SHARED_CIPHER
#define SSL_R_NO_SHARED_CIPHER 193
Definition at line 2529 of file ssl.h.
SSL_R_NO_SHARED_GROUPS
#define SSL_R_NO_SHARED_GROUPS 410
Definition at line 2530 of file ssl.h.
SSL_R_NO_SHARED_SIGNATURE_ALGORITHMS
#define SSL_R_NO_SHARED_SIGNATURE_ALGORITHMS 376
Definition at line 2531 of file ssl.h.
Referenced by tls1_set_server_sigalgs().
SSL_R_NO_SRTP_PROFILES
#define SSL_R_NO_SRTP_PROFILES 359
Definition at line 2532 of file ssl.h.
SSL_R_NO_SUITABLE_KEY_SHARE
#define SSL_R_NO_SUITABLE_KEY_SHARE 101
Definition at line 2533 of file ssl.h.
Referenced by tls_construct_ctos_key_share().
SSL_R_NO_SUITABLE_SIGNATURE_ALGORITHM
#define SSL_R_NO_SUITABLE_SIGNATURE_ALGORITHM 118
Definition at line 2534 of file ssl.h.
SSL_R_NO_VALID_SCTS
#define SSL_R_NO_VALID_SCTS 216
Definition at line 2535 of file ssl.h.
SSL_R_NO_VERIFY_COOKIE_CALLBACK
#define SSL_R_NO_VERIFY_COOKIE_CALLBACK 403
Definition at line 2536 of file ssl.h.
SSL_R_NULL_SSL_CTX
#define SSL_R_NULL_SSL_CTX 195
Definition at line 2537 of file ssl.h.
Referenced by SSL_new().
SSL_R_NULL_SSL_METHOD_PASSED
#define SSL_R_NULL_SSL_METHOD_PASSED 196
Definition at line 2538 of file ssl.h.
SSL_R_OLD_SESSION_CIPHER_NOT_RETURNED
#define SSL_R_OLD_SESSION_CIPHER_NOT_RETURNED 197
Definition at line 2539 of file ssl.h.
SSL_R_OLD_SESSION_COMPRESSION_ALGORITHM_NOT_RETURNED
#define SSL_R_OLD_SESSION_COMPRESSION_ALGORITHM_NOT_RETURNED 344
Definition at line 2540 of file ssl.h.
SSL_R_PACKET_LENGTH_TOO_LONG
#define SSL_R_PACKET_LENGTH_TOO_LONG 198
Definition at line 2541 of file ssl.h.
SSL_R_PARSE_TLSEXT
#define SSL_R_PARSE_TLSEXT 227
Definition at line 2542 of file ssl.h.
SSL_R_PATH_TOO_LONG
#define SSL_R_PATH_TOO_LONG 270
Definition at line 2543 of file ssl.h.
SSL_R_PEER_DID_NOT_RETURN_A_CERTIFICATE
#define SSL_R_PEER_DID_NOT_RETURN_A_CERTIFICATE 199
Definition at line 2544 of file ssl.h.
Referenced by ossl_statem_server_read_transition().
SSL_R_PEM_NAME_BAD_PREFIX
#define SSL_R_PEM_NAME_BAD_PREFIX 391
Definition at line 2545 of file ssl.h.
SSL_R_PEM_NAME_TOO_SHORT
#define SSL_R_PEM_NAME_TOO_SHORT 392
Definition at line 2546 of file ssl.h.
SSL_R_PIPELINE_FAILURE
#define SSL_R_PIPELINE_FAILURE 406
Definition at line 2547 of file ssl.h.
SSL_R_PROTOCOL_IS_SHUTDOWN
#define SSL_R_PROTOCOL_IS_SHUTDOWN 207
Definition at line 2548 of file ssl.h.
Referenced by SSL_write_ex().
SSL_R_PSK_IDENTITY_NOT_FOUND
#define SSL_R_PSK_IDENTITY_NOT_FOUND 223
Definition at line 2549 of file ssl.h.
SSL_R_PSK_NO_CLIENT_CB
#define SSL_R_PSK_NO_CLIENT_CB 224
Definition at line 2550 of file ssl.h.
SSL_R_PSK_NO_SERVER_CB
#define SSL_R_PSK_NO_SERVER_CB 225
Definition at line 2551 of file ssl.h.
SSL_R_READ_BIO_NOT_SET
#define SSL_R_READ_BIO_NOT_SET 211
Definition at line 2552 of file ssl.h.
SSL_R_READ_TIMEOUT_EXPIRED
#define SSL_R_READ_TIMEOUT_EXPIRED 312
Definition at line 2553 of file ssl.h.
Referenced by dtls1_check_timeout_num().
SSL_R_RECORD_LENGTH_MISMATCH
#define SSL_R_RECORD_LENGTH_MISMATCH 213
Definition at line 2554 of file ssl.h.
SSL_R_RECORD_TOO_SMALL
#define SSL_R_RECORD_TOO_SMALL 298
Definition at line 2555 of file ssl.h.
SSL_R_RENEGOTIATE_EXT_TOO_LONG
#define SSL_R_RENEGOTIATE_EXT_TOO_LONG 335
Definition at line 2556 of file ssl.h.
SSL_R_RENEGOTIATION_ENCODING_ERR
#define SSL_R_RENEGOTIATION_ENCODING_ERR 336
Definition at line 2557 of file ssl.h.
SSL_R_RENEGOTIATION_MISMATCH
#define SSL_R_RENEGOTIATION_MISMATCH 337
Definition at line 2558 of file ssl.h.
SSL_R_REQUIRED_CIPHER_MISSING
#define SSL_R_REQUIRED_CIPHER_MISSING 215
Definition at line 2559 of file ssl.h.
SSL_R_REQUIRED_COMPRESSION_ALGORITHM_MISSING
#define SSL_R_REQUIRED_COMPRESSION_ALGORITHM_MISSING 342
Definition at line 2560 of file ssl.h.
SSL_R_SCSV_RECEIVED_WHEN_RENEGOTIATING
#define SSL_R_SCSV_RECEIVED_WHEN_RENEGOTIATING 345
Definition at line 2561 of file ssl.h.
SSL_R_SCT_VERIFICATION_FAILED
#define SSL_R_SCT_VERIFICATION_FAILED 208
Definition at line 2562 of file ssl.h.
SSL_R_SERVERHELLO_TLSEXT
#define SSL_R_SERVERHELLO_TLSEXT 275
Definition at line 2563 of file ssl.h.
SSL_R_SESSION_ID_CONTEXT_UNINITIALIZED
#define SSL_R_SESSION_ID_CONTEXT_UNINITIALIZED 277
Definition at line 2564 of file ssl.h.
SSL_R_SHUTDOWN_WHILE_IN_INIT
#define SSL_R_SHUTDOWN_WHILE_IN_INIT 407
Definition at line 2565 of file ssl.h.
SSL_R_SIGNATURE_ALGORITHMS_ERROR
#define SSL_R_SIGNATURE_ALGORITHMS_ERROR 360
Definition at line 2566 of file ssl.h.
SSL_R_SIGNATURE_FOR_NON_SIGNING_CERTIFICATE
#define SSL_R_SIGNATURE_FOR_NON_SIGNING_CERTIFICATE 220
Definition at line 2567 of file ssl.h.
SSL_R_SRP_A_CALC
#define SSL_R_SRP_A_CALC 361
Definition at line 2568 of file ssl.h.
SSL_R_SRTP_COULD_NOT_ALLOCATE_PROFILES
#define SSL_R_SRTP_COULD_NOT_ALLOCATE_PROFILES 362
Definition at line 2569 of file ssl.h.
SSL_R_SRTP_PROTECTION_PROFILE_LIST_TOO_LONG
#define SSL_R_SRTP_PROTECTION_PROFILE_LIST_TOO_LONG 363
Definition at line 2570 of file ssl.h.
SSL_R_SRTP_UNKNOWN_PROTECTION_PROFILE
#define SSL_R_SRTP_UNKNOWN_PROTECTION_PROFILE 364
Definition at line 2571 of file ssl.h.
SSL_R_SSL3_EXT_INVALID_SERVERNAME
#define SSL_R_SSL3_EXT_INVALID_SERVERNAME 319
Definition at line 2572 of file ssl.h.
SSL_R_SSL3_EXT_INVALID_SERVERNAME_TYPE
#define SSL_R_SSL3_EXT_INVALID_SERVERNAME_TYPE 320
Definition at line 2573 of file ssl.h.
SSL_R_SSL3_SESSION_ID_TOO_LONG
#define SSL_R_SSL3_SESSION_ID_TOO_LONG 300
Definition at line 2574 of file ssl.h.
SSL_R_SSL_COMMAND_SECTION_EMPTY
#define SSL_R_SSL_COMMAND_SECTION_EMPTY 117
Definition at line 2586 of file ssl.h.
SSL_R_SSL_COMMAND_SECTION_NOT_FOUND
#define SSL_R_SSL_COMMAND_SECTION_NOT_FOUND 125
Definition at line 2587 of file ssl.h.
SSL_R_SSL_CTX_HAS_NO_DEFAULT_SSL_VERSION
#define SSL_R_SSL_CTX_HAS_NO_DEFAULT_SSL_VERSION 228
Definition at line 2588 of file ssl.h.
Referenced by SSL_new().
SSL_R_SSL_HANDSHAKE_FAILURE
#define SSL_R_SSL_HANDSHAKE_FAILURE 229
Definition at line 2589 of file ssl.h.
Referenced by dtls1_write_app_data_bytes().
SSL_R_SSL_LIBRARY_HAS_NO_CIPHERS
#define SSL_R_SSL_LIBRARY_HAS_NO_CIPHERS 230
Definition at line 2590 of file ssl.h.
Referenced by SSL_CTX_set_ssl_version().
SSL_R_SSL_NEGATIVE_LENGTH
#define SSL_R_SSL_NEGATIVE_LENGTH 372
Definition at line 2591 of file ssl.h.
SSL_R_SSL_SECTION_EMPTY
#define SSL_R_SSL_SECTION_EMPTY 126
Definition at line 2592 of file ssl.h.
SSL_R_SSL_SECTION_NOT_FOUND
#define SSL_R_SSL_SECTION_NOT_FOUND 136
Definition at line 2593 of file ssl.h.
SSL_R_SSL_SESSION_ID_CALLBACK_FAILED
#define SSL_R_SSL_SESSION_ID_CALLBACK_FAILED 301
Definition at line 2594 of file ssl.h.
SSL_R_SSL_SESSION_ID_CONFLICT
#define SSL_R_SSL_SESSION_ID_CONFLICT 302
Definition at line 2595 of file ssl.h.
SSL_R_SSL_SESSION_ID_CONTEXT_TOO_LONG
#define SSL_R_SSL_SESSION_ID_CONTEXT_TOO_LONG 273
Definition at line 2596 of file ssl.h.
Referenced by SSL_CTX_set_session_id_context(), SSL_SESSION_set1_id_context(), and SSL_set_session_id_context().
SSL_R_SSL_SESSION_ID_HAS_BAD_LENGTH
#define SSL_R_SSL_SESSION_ID_HAS_BAD_LENGTH 303
Definition at line 2597 of file ssl.h.
SSL_R_SSL_SESSION_ID_TOO_LONG
#define SSL_R_SSL_SESSION_ID_TOO_LONG 408
Definition at line 2598 of file ssl.h.
Referenced by SSL_SESSION_set1_id().
SSL_R_SSL_SESSION_VERSION_MISMATCH
#define SSL_R_SSL_SESSION_VERSION_MISMATCH 210
Definition at line 2599 of file ssl.h.
SSL_R_SSLV3_ALERT_BAD_CERTIFICATE
#define SSL_R_SSLV3_ALERT_BAD_CERTIFICATE 1042
Definition at line 2575 of file ssl.h.
SSL_R_SSLV3_ALERT_BAD_RECORD_MAC
#define SSL_R_SSLV3_ALERT_BAD_RECORD_MAC 1020
Definition at line 2576 of file ssl.h.
SSL_R_SSLV3_ALERT_CERTIFICATE_EXPIRED
#define SSL_R_SSLV3_ALERT_CERTIFICATE_EXPIRED 1045
Definition at line 2577 of file ssl.h.
SSL_R_SSLV3_ALERT_CERTIFICATE_REVOKED
#define SSL_R_SSLV3_ALERT_CERTIFICATE_REVOKED 1044
Definition at line 2578 of file ssl.h.
SSL_R_SSLV3_ALERT_CERTIFICATE_UNKNOWN
#define SSL_R_SSLV3_ALERT_CERTIFICATE_UNKNOWN 1046
Definition at line 2579 of file ssl.h.
SSL_R_SSLV3_ALERT_DECOMPRESSION_FAILURE
#define SSL_R_SSLV3_ALERT_DECOMPRESSION_FAILURE 1030
Definition at line 2580 of file ssl.h.
SSL_R_SSLV3_ALERT_HANDSHAKE_FAILURE
#define SSL_R_SSLV3_ALERT_HANDSHAKE_FAILURE 1040
Definition at line 2581 of file ssl.h.
SSL_R_SSLV3_ALERT_ILLEGAL_PARAMETER
#define SSL_R_SSLV3_ALERT_ILLEGAL_PARAMETER 1047
Definition at line 2582 of file ssl.h.
SSL_R_SSLV3_ALERT_NO_CERTIFICATE
#define SSL_R_SSLV3_ALERT_NO_CERTIFICATE 1041
Definition at line 2583 of file ssl.h.
SSL_R_SSLV3_ALERT_UNEXPECTED_MESSAGE
#define SSL_R_SSLV3_ALERT_UNEXPECTED_MESSAGE 1010
Definition at line 2584 of file ssl.h.
SSL_R_SSLV3_ALERT_UNSUPPORTED_CERTIFICATE
#define SSL_R_SSLV3_ALERT_UNSUPPORTED_CERTIFICATE 1043
Definition at line 2585 of file ssl.h.
SSL_R_STILL_IN_INIT
#define SSL_R_STILL_IN_INIT 121
Definition at line 2600 of file ssl.h.
Referenced by SSL_key_update().
SSL_R_TLS_HEARTBEAT_PEER_DOESNT_ACCEPT
#define SSL_R_TLS_HEARTBEAT_PEER_DOESNT_ACCEPT 365
Definition at line 2619 of file ssl.h.
SSL_R_TLS_HEARTBEAT_PENDING
#define SSL_R_TLS_HEARTBEAT_PENDING 366
Definition at line 2620 of file ssl.h.
SSL_R_TLS_ILLEGAL_EXPORTER_LABEL
#define SSL_R_TLS_ILLEGAL_EXPORTER_LABEL 367
Definition at line 2621 of file ssl.h.
SSL_R_TLS_INVALID_ECPOINTFORMAT_LIST
#define SSL_R_TLS_INVALID_ECPOINTFORMAT_LIST 157
Definition at line 2622 of file ssl.h.
SSL_R_TLSV1_ALERT_ACCESS_DENIED
#define SSL_R_TLSV1_ALERT_ACCESS_DENIED 1049
Definition at line 2601 of file ssl.h.
SSL_R_TLSV1_ALERT_DECODE_ERROR
#define SSL_R_TLSV1_ALERT_DECODE_ERROR 1050
Definition at line 2602 of file ssl.h.
SSL_R_TLSV1_ALERT_DECRYPT_ERROR
#define SSL_R_TLSV1_ALERT_DECRYPT_ERROR 1051
Definition at line 2604 of file ssl.h.
SSL_R_TLSV1_ALERT_DECRYPTION_FAILED
#define SSL_R_TLSV1_ALERT_DECRYPTION_FAILED 1021
Definition at line 2603 of file ssl.h.
SSL_R_TLSV1_ALERT_EXPORT_RESTRICTION
#define SSL_R_TLSV1_ALERT_EXPORT_RESTRICTION 1060
Definition at line 2605 of file ssl.h.
SSL_R_TLSV1_ALERT_INAPPROPRIATE_FALLBACK
#define SSL_R_TLSV1_ALERT_INAPPROPRIATE_FALLBACK 1086
Definition at line 2606 of file ssl.h.
SSL_R_TLSV1_ALERT_INSUFFICIENT_SECURITY
#define SSL_R_TLSV1_ALERT_INSUFFICIENT_SECURITY 1071
Definition at line 2607 of file ssl.h.
SSL_R_TLSV1_ALERT_INTERNAL_ERROR
#define SSL_R_TLSV1_ALERT_INTERNAL_ERROR 1080
Definition at line 2608 of file ssl.h.
SSL_R_TLSV1_ALERT_NO_RENEGOTIATION
#define SSL_R_TLSV1_ALERT_NO_RENEGOTIATION 1100
Definition at line 2609 of file ssl.h.
SSL_R_TLSV1_ALERT_PROTOCOL_VERSION
#define SSL_R_TLSV1_ALERT_PROTOCOL_VERSION 1070
Definition at line 2610 of file ssl.h.
SSL_R_TLSV1_ALERT_RECORD_OVERFLOW
#define SSL_R_TLSV1_ALERT_RECORD_OVERFLOW 1022
Definition at line 2611 of file ssl.h.
SSL_R_TLSV1_ALERT_UNKNOWN_CA
#define SSL_R_TLSV1_ALERT_UNKNOWN_CA 1048
Definition at line 2612 of file ssl.h.
SSL_R_TLSV1_ALERT_USER_CANCELLED
#define SSL_R_TLSV1_ALERT_USER_CANCELLED 1090
Definition at line 2613 of file ssl.h.
SSL_R_TLSV1_BAD_CERTIFICATE_HASH_VALUE
#define SSL_R_TLSV1_BAD_CERTIFICATE_HASH_VALUE 1114
Definition at line 2614 of file ssl.h.
SSL_R_TLSV1_BAD_CERTIFICATE_STATUS_RESPONSE
#define SSL_R_TLSV1_BAD_CERTIFICATE_STATUS_RESPONSE 1113
Definition at line 2615 of file ssl.h.
SSL_R_TLSV1_CERTIFICATE_UNOBTAINABLE
#define SSL_R_TLSV1_CERTIFICATE_UNOBTAINABLE 1111
Definition at line 2616 of file ssl.h.
SSL_R_TLSV1_UNRECOGNIZED_NAME
#define SSL_R_TLSV1_UNRECOGNIZED_NAME 1112
Definition at line 2617 of file ssl.h.
SSL_R_TLSV1_UNSUPPORTED_EXTENSION
#define SSL_R_TLSV1_UNSUPPORTED_EXTENSION 1110
Definition at line 2618 of file ssl.h.
SSL_R_TOO_MANY_KEY_UPDATES
#define SSL_R_TOO_MANY_KEY_UPDATES 132
Definition at line 2623 of file ssl.h.
Referenced by tls_process_key_update().
SSL_R_TOO_MANY_WARN_ALERTS
#define SSL_R_TOO_MANY_WARN_ALERTS 409
Definition at line 2624 of file ssl.h.
SSL_R_UNABLE_TO_FIND_ECDH_PARAMETERS
#define SSL_R_UNABLE_TO_FIND_ECDH_PARAMETERS 314
Definition at line 2625 of file ssl.h.
SSL_R_UNABLE_TO_FIND_PUBLIC_KEY_PARAMETERS
#define SSL_R_UNABLE_TO_FIND_PUBLIC_KEY_PARAMETERS 239
Definition at line 2626 of file ssl.h.
SSL_R_UNABLE_TO_LOAD_SSL3_MD5_ROUTINES
#define SSL_R_UNABLE_TO_LOAD_SSL3_MD5_ROUTINES 242
Definition at line 2627 of file ssl.h.
SSL_R_UNABLE_TO_LOAD_SSL3_SHA1_ROUTINES
#define SSL_R_UNABLE_TO_LOAD_SSL3_SHA1_ROUTINES 243
Definition at line 2628 of file ssl.h.
SSL_R_UNEXPECTED_MESSAGE
#define SSL_R_UNEXPECTED_MESSAGE 244
Definition at line 2629 of file ssl.h.
Referenced by ossl_statem_server_read_transition().
SSL_R_UNEXPECTED_RECORD
#define SSL_R_UNEXPECTED_RECORD 245
Definition at line 2630 of file ssl.h.
SSL_R_UNINITIALIZED
#define SSL_R_UNINITIALIZED 276
Definition at line 2631 of file ssl.h.
Referenced by SSL_peek_ex(), SSL_read_ex(), SSL_shutdown(), and SSL_write_ex().
SSL_R_UNKNOWN_ALERT_TYPE
#define SSL_R_UNKNOWN_ALERT_TYPE 246
Definition at line 2632 of file ssl.h.
SSL_R_UNKNOWN_CERTIFICATE_TYPE
#define SSL_R_UNKNOWN_CERTIFICATE_TYPE 247
Definition at line 2633 of file ssl.h.
SSL_R_UNKNOWN_CIPHER_RETURNED
#define SSL_R_UNKNOWN_CIPHER_RETURNED 248
Definition at line 2634 of file ssl.h.
SSL_R_UNKNOWN_CIPHER_TYPE
#define SSL_R_UNKNOWN_CIPHER_TYPE 249
Definition at line 2635 of file ssl.h.
SSL_R_UNKNOWN_CMD_NAME
#define SSL_R_UNKNOWN_CMD_NAME 386
Definition at line 2636 of file ssl.h.
SSL_R_UNKNOWN_COMMAND
#define SSL_R_UNKNOWN_COMMAND 139
Definition at line 2637 of file ssl.h.
SSL_R_UNKNOWN_DIGEST
#define SSL_R_UNKNOWN_DIGEST 368
Definition at line 2638 of file ssl.h.
SSL_R_UNKNOWN_KEY_EXCHANGE_TYPE
#define SSL_R_UNKNOWN_KEY_EXCHANGE_TYPE 250
Definition at line 2639 of file ssl.h.
SSL_R_UNKNOWN_PKEY_TYPE
#define SSL_R_UNKNOWN_PKEY_TYPE 251
Definition at line 2640 of file ssl.h.
SSL_R_UNKNOWN_PROTOCOL
#define SSL_R_UNKNOWN_PROTOCOL 252
Definition at line 2641 of file ssl.h.
SSL_R_UNKNOWN_SSL_VERSION
#define SSL_R_UNKNOWN_SSL_VERSION 254
Definition at line 2642 of file ssl.h.
SSL_R_UNKNOWN_STATE
#define SSL_R_UNKNOWN_STATE 255
Definition at line 2643 of file ssl.h.
SSL_R_UNSAFE_LEGACY_RENEGOTIATION_DISABLED
#define SSL_R_UNSAFE_LEGACY_RENEGOTIATION_DISABLED 338
Definition at line 2644 of file ssl.h.
Referenced by tls_setup_handshake().
SSL_R_UNSUPPORTED_COMPRESSION_ALGORITHM
#define SSL_R_UNSUPPORTED_COMPRESSION_ALGORITHM 257
Definition at line 2645 of file ssl.h.
SSL_R_UNSUPPORTED_ELLIPTIC_CURVE
#define SSL_R_UNSUPPORTED_ELLIPTIC_CURVE 315
Definition at line 2646 of file ssl.h.
SSL_R_UNSUPPORTED_PROTOCOL
#define SSL_R_UNSUPPORTED_PROTOCOL 258
Definition at line 2647 of file ssl.h.
SSL_R_UNSUPPORTED_SSL_VERSION
#define SSL_R_UNSUPPORTED_SSL_VERSION 259
Definition at line 2648 of file ssl.h.
SSL_R_UNSUPPORTED_STATUS_TYPE
#define SSL_R_UNSUPPORTED_STATUS_TYPE 329
Definition at line 2649 of file ssl.h.
SSL_R_USE_SRTP_NOT_NEGOTIATED
#define SSL_R_USE_SRTP_NOT_NEGOTIATED 369
Definition at line 2650 of file ssl.h.
SSL_R_VERSION_TOO_HIGH
#define SSL_R_VERSION_TOO_HIGH 166
Definition at line 2651 of file ssl.h.
SSL_R_VERSION_TOO_LOW
#define SSL_R_VERSION_TOO_LOW 396
Definition at line 2652 of file ssl.h.
SSL_R_WRONG_CERTIFICATE_TYPE
#define SSL_R_WRONG_CERTIFICATE_TYPE 383
Definition at line 2653 of file ssl.h.
SSL_R_WRONG_CIPHER_RETURNED
#define SSL_R_WRONG_CIPHER_RETURNED 261
Definition at line 2654 of file ssl.h.
SSL_R_WRONG_CURVE
#define SSL_R_WRONG_CURVE 378
Definition at line 2655 of file ssl.h.
SSL_R_WRONG_SIGNATURE_LENGTH
#define SSL_R_WRONG_SIGNATURE_LENGTH 264
Definition at line 2656 of file ssl.h.
SSL_R_WRONG_SIGNATURE_SIZE
#define SSL_R_WRONG_SIGNATURE_SIZE 265
Definition at line 2657 of file ssl.h.
SSL_R_WRONG_SIGNATURE_TYPE
#define SSL_R_WRONG_SIGNATURE_TYPE 370
Definition at line 2658 of file ssl.h.
SSL_R_WRONG_SSL_VERSION
#define SSL_R_WRONG_SSL_VERSION 266
Definition at line 2659 of file ssl.h.
Referenced by ssl_choose_client_version(), SSL_key_update(), and SSL_renegotiate().
SSL_R_WRONG_VERSION_NUMBER
#define SSL_R_WRONG_VERSION_NUMBER 267
Definition at line 2660 of file ssl.h.
SSL_R_X509_LIB
#define SSL_R_X509_LIB 268
Definition at line 2661 of file ssl.h.
SSL_R_X509_VERIFICATION_SETUP_PROBLEMS
#define SSL_R_X509_VERIFICATION_SETUP_PROBLEMS 269
Definition at line 2662 of file ssl.h.
SSL_READING
#define SSL_READING 3
Definition at line 763 of file ssl.h.
Referenced by ossl_statem_client_post_process_message(), ossl_statem_server_post_process_message(), tls_get_message_body(), tls_get_message_header(), and tls_post_process_client_key_exchange().
SSL_RECEIVED_SHUTDOWN
#define SSL_RECEIVED_SHUTDOWN 2
Definition at line 208 of file ssl.h.
Referenced by SSL_get_error(), SSL_peek_ex(), and SSL_read_ex().
SSL_SECOP_CA_KEY
#define SSL_SECOP_CA_KEY (17 | SSL_SECOP_OTHER_CERT)
Definition at line 2025 of file ssl.h.
SSL_SECOP_CA_MD
#define SSL_SECOP_CA_MD (18 | SSL_SECOP_OTHER_CERT)
Definition at line 2027 of file ssl.h.
SSL_SECOP_CIPHER_CHECK
#define SSL_SECOP_CIPHER_CHECK (3 | SSL_SECOP_OTHER_CIPHER)
Definition at line 1999 of file ssl.h.
SSL_SECOP_CIPHER_SHARED
#define SSL_SECOP_CIPHER_SHARED (2 | SSL_SECOP_OTHER_CIPHER)
Definition at line 1997 of file ssl.h.
SSL_SECOP_CIPHER_SUPPORTED
#define SSL_SECOP_CIPHER_SUPPORTED (1 | SSL_SECOP_OTHER_CIPHER)
Definition at line 1995 of file ssl.h.
SSL_SECOP_COMPRESSION
#define SSL_SECOP_COMPRESSION (15 | SSL_SECOP_OTHER_NONE)
Definition at line 2021 of file ssl.h.
Referenced by ssl_allow_compression().
SSL_SECOP_CURVE_CHECK
#define SSL_SECOP_CURVE_CHECK (6 | SSL_SECOP_OTHER_CURVE)
Definition at line 2005 of file ssl.h.
Referenced by check_in_list(), and tls1_check_curve().
SSL_SECOP_CURVE_SHARED
#define SSL_SECOP_CURVE_SHARED (5 | SSL_SECOP_OTHER_CURVE)
Definition at line 2003 of file ssl.h.
SSL_SECOP_CURVE_SUPPORTED
#define SSL_SECOP_CURVE_SUPPORTED (4 | SSL_SECOP_OTHER_CURVE)
Definition at line 2001 of file ssl.h.
Referenced by tls_construct_ctos_key_share().
SSL_SECOP_EE_KEY
#define SSL_SECOP_EE_KEY (16 | SSL_SECOP_OTHER_CERT)
Definition at line 2023 of file ssl.h.
SSL_SECOP_OTHER_CERT
#define SSL_SECOP_OTHER_CERT (6 << 16)
Definition at line 1986 of file ssl.h.
SSL_SECOP_OTHER_CIPHER
#define SSL_SECOP_OTHER_CIPHER (1 << 16)
Definition at line 1981 of file ssl.h.
SSL_SECOP_OTHER_CURVE
#define SSL_SECOP_OTHER_CURVE (2 << 16)
Definition at line 1982 of file ssl.h.
SSL_SECOP_OTHER_DH
#define SSL_SECOP_OTHER_DH (3 << 16)
Definition at line 1983 of file ssl.h.
SSL_SECOP_OTHER_NONE
#define SSL_SECOP_OTHER_NONE 0
Definition at line 1980 of file ssl.h.
SSL_SECOP_OTHER_PKEY
#define SSL_SECOP_OTHER_PKEY (4 << 16)
Definition at line 1984 of file ssl.h.
SSL_SECOP_OTHER_SIGALG
#define SSL_SECOP_OTHER_SIGALG (5 << 16)
Definition at line 1985 of file ssl.h.
SSL_SECOP_OTHER_TYPE
#define SSL_SECOP_OTHER_TYPE 0xffff0000
Definition at line 1979 of file ssl.h.
SSL_SECOP_PEER
#define SSL_SECOP_PEER 0x1000
Definition at line 1989 of file ssl.h.
Referenced by ssl_security_cert().
SSL_SECOP_PEER_CA_KEY
#define SSL_SECOP_PEER_CA_KEY (SSL_SECOP_CA_KEY | SSL_SECOP_PEER)
Definition at line 2031 of file ssl.h.
SSL_SECOP_PEER_CA_MD
#define SSL_SECOP_PEER_CA_MD (SSL_SECOP_CA_MD | SSL_SECOP_PEER)
Definition at line 2033 of file ssl.h.
SSL_SECOP_PEER_EE_KEY
#define SSL_SECOP_PEER_EE_KEY (SSL_SECOP_EE_KEY | SSL_SECOP_PEER)
Definition at line 2029 of file ssl.h.
SSL_SECOP_SIGALG_CHECK
#define SSL_SECOP_SIGALG_CHECK (13 | SSL_SECOP_OTHER_SIGALG)
Definition at line 2017 of file ssl.h.
SSL_SECOP_SIGALG_MASK
#define SSL_SECOP_SIGALG_MASK (14 | SSL_SECOP_OTHER_SIGALG)
Definition at line 2019 of file ssl.h.
Referenced by ssl3_get_req_cert_type(), and ssl_set_client_disabled().
SSL_SECOP_SIGALG_SHARED
#define SSL_SECOP_SIGALG_SHARED (12 | SSL_SECOP_OTHER_SIGALG)
Definition at line 2015 of file ssl.h.
SSL_SECOP_SIGALG_SUPPORTED
#define SSL_SECOP_SIGALG_SUPPORTED (11 | SSL_SECOP_OTHER_SIGALG)
Definition at line 2013 of file ssl.h.
SSL_SECOP_TICKET
#define SSL_SECOP_TICKET (10 | SSL_SECOP_OTHER_NONE)
Definition at line 2011 of file ssl.h.
Referenced by tls_use_ticket().
SSL_SECOP_TMP_DH
#define SSL_SECOP_TMP_DH (7 | SSL_SECOP_OTHER_PKEY)
Definition at line 2007 of file ssl.h.
Referenced by ssl3_ctx_ctrl().
SSL_SECOP_VERSION
#define SSL_SECOP_VERSION (9 | SSL_SECOP_OTHER_NONE)
Definition at line 2009 of file ssl.h.
SSL_select_current_cert
#define SSL_select_current_cert (ctx, x509) SSL_ctrl(ctx,SSL_CTRL_SELECT_CURRENT_CERT,0,(char *)x509)
SSL_SENT_SHUTDOWN
#define SSL_SENT_SHUTDOWN 1
Definition at line 207 of file ssl.h.
Referenced by ssl_clear_bad_session(), and SSL_write_ex().
SSL_SESS_CACHE_BOTH
#define SSL_SESS_CACHE_BOTH (SSL_SESS_CACHE_CLIENT|SSL_SESS_CACHE_SERVER)
Definition at line 579 of file ssl.h.
SSL_SESS_CACHE_CLIENT
#define SSL_SESS_CACHE_CLIENT 0x0001
Definition at line 577 of file ssl.h.
Referenced by ssl_update_cache().
SSL_SESS_CACHE_NO_AUTO_CLEAR
#define SSL_SESS_CACHE_NO_AUTO_CLEAR 0x0080
Definition at line 580 of file ssl.h.
Referenced by ssl_update_cache().
SSL_SESS_CACHE_NO_INTERNAL
#define SSL_SESS_CACHE_NO_INTERNAL (SSL_SESS_CACHE_NO_INTERNAL_LOOKUP|SSL_SESS_CACHE_NO_INTERNAL_STORE)
Definition at line 584 of file ssl.h.
SSL_SESS_CACHE_NO_INTERNAL_LOOKUP
#define SSL_SESS_CACHE_NO_INTERNAL_LOOKUP 0x0100
Definition at line 582 of file ssl.h.
SSL_SESS_CACHE_NO_INTERNAL_STORE
#define SSL_SESS_CACHE_NO_INTERNAL_STORE 0x0200
Definition at line 583 of file ssl.h.
Referenced by ssl_update_cache().
SSL_SESS_CACHE_OFF
#define SSL_SESS_CACHE_OFF 0x0000
Definition at line 576 of file ssl.h.
SSL_SESS_CACHE_SERVER
#define SSL_SESS_CACHE_SERVER 0x0002
Definition at line 578 of file ssl.h.
Referenced by tls_construct_server_hello().
SSL_SESSION_ASN1_VERSION
#define SSL_SESSION_ASN1_VERSION 0x0001
Definition at line 72 of file ssl.h.
SSL_SESSION_CACHE_MAX_SIZE_DEFAULT
#define SSL_SESSION_CACHE_MAX_SIZE_DEFAULT (1024*20)
Definition at line 559 of file ssl.h.
SSL_SESSION_get_app_data
#define SSL_SESSION_get_app_data (s) (SSL_SESSION_get_ex_data(s,0))
Definition at line 823 of file ssl.h.
SSL_SESSION_get_ex_new_index
#define SSL_SESSION_get_ex_new_index (l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_SSL_SESSION, l, p, newf, dupf, freef)
Definition at line 1746 of file ssl.h.
SSL_SESSION_set_app_data
#define SSL_SESSION_set_app_data (s, a) (SSL_SESSION_set_ex_data(s,0,(char *)a))
Definition at line 822 of file ssl.h.
SSL_set0_chain
#define SSL_set0_chain (ctx, sk) SSL_ctrl(ctx,SSL_CTRL_CHAIN,0,(char *)sk)
SSL_set0_chain_cert_store
#define SSL_set0_chain_cert_store (s, st) SSL_ctrl(s,SSL_CTRL_SET_CHAIN_CERT_STORE,0,(char *)st)
SSL_set0_verify_cert_store
#define SSL_set0_verify_cert_store (s, st) SSL_ctrl(s,SSL_CTRL_SET_VERIFY_CERT_STORE,0,(char *)st)
SSL_set1_chain
#define SSL_set1_chain (ctx, sk) SSL_ctrl(ctx,SSL_CTRL_CHAIN,1,(char *)sk)
SSL_set1_chain_cert_store
#define SSL_set1_chain_cert_store (s, st) SSL_ctrl(s,SSL_CTRL_SET_CHAIN_CERT_STORE,1,(char *)st)
SSL_set1_client_certificate_types
#define SSL_set1_client_certificate_types (s, clist, clistlen) SSL_ctrl(s,SSL_CTRL_SET_CLIENT_CERT_TYPES,clistlen,(char *)clist)
SSL_set1_client_sigalgs
#define SSL_set1_client_sigalgs (ctx, slist, slistlen) SSL_ctrl(ctx,SSL_CTRL_SET_CLIENT_SIGALGS,clistlen,(int *)slist)
SSL_set1_client_sigalgs_list
#define SSL_set1_client_sigalgs_list (ctx, s) SSL_ctrl(ctx,SSL_CTRL_SET_CLIENT_SIGALGS_LIST,0,(char *)s)
SSL_set1_curves
#define SSL_set1_curves (ctx, clist, clistlen) SSL_set1_groups((ctx), (clist), (clistlen))
SSL_set1_curves_list
#define SSL_set1_curves_list (ctx, s) SSL_set1_groups_list((ctx), (s))
SSL_set1_groups
#define SSL_set1_groups (ctx, glist, glistlen) SSL_ctrl(ctx,SSL_CTRL_SET_GROUPS,glistlen,(char *)glist)
SSL_set1_groups_list
#define SSL_set1_groups_list (ctx, s) SSL_ctrl(ctx,SSL_CTRL_SET_GROUPS_LIST,0,(char *)s)
SSL_set1_sigalgs
#define SSL_set1_sigalgs (ctx, slist, slistlen) SSL_ctrl(ctx,SSL_CTRL_SET_SIGALGS,slistlen,(int *)slist)
SSL_set1_sigalgs_list
#define SSL_set1_sigalgs_list (ctx, s) SSL_ctrl(ctx,SSL_CTRL_SET_SIGALGS_LIST,0,(char *)s)
SSL_set1_verify_cert_store
#define SSL_set1_verify_cert_store (s, st) SSL_ctrl(s,SSL_CTRL_SET_VERIFY_CERT_STORE,1,(char *)st)
SSL_set_app_data
#define SSL_set_app_data (s, arg) (SSL_set_ex_data(s,0,(char *)arg))
Definition at line 820 of file ssl.h.
SSL_set_cert_flags
#define SSL_set_cert_flags (s, op) SSL_ctrl((s),SSL_CTRL_CERT_FLAGS,(op),NULL)
Definition at line 523 of file ssl.h.
SSL_set_current_cert
#define SSL_set_current_cert (ctx, op) SSL_ctrl(ctx,SSL_CTRL_SET_CURRENT_CERT, op, NULL)
SSL_set_dh_auto
#define SSL_set_dh_auto (s, onoff) SSL_ctrl(s,SSL_CTRL_SET_DH_AUTO,onoff,NULL)
SSL_set_ecdh_auto
#define SSL_set_ecdh_auto (dummy, onoff) ((onoff) != 0)
SSL_set_max_cert_list
#define SSL_set_max_cert_list (ssl, m) SSL_ctrl(ssl,SSL_CTRL_SET_MAX_CERT_LIST,m,NULL)
Definition at line 1778 of file ssl.h.
SSL_set_max_pipelines
#define SSL_set_max_pipelines (ssl, m) SSL_ctrl(ssl,SSL_CTRL_SET_MAX_PIPELINES,m,NULL)
Definition at line 1791 of file ssl.h.
SSL_set_max_proto_version
#define SSL_set_max_proto_version (s, version) SSL_ctrl(s, SSL_CTRL_SET_MAX_PROTO_VERSION, version, NULL)
SSL_set_max_send_fragment
#define SSL_set_max_send_fragment (ssl, m) SSL_ctrl(ssl,SSL_CTRL_SET_MAX_SEND_FRAGMENT,m,NULL)
Definition at line 1783 of file ssl.h.
SSL_set_min_proto_version
#define SSL_set_min_proto_version (s, version) SSL_ctrl(s, SSL_CTRL_SET_MIN_PROTO_VERSION, version, NULL)
SSL_set_mode
#define SSL_set_mode (ssl, op) SSL_ctrl((ssl),SSL_CTRL_MODE,(op),NULL)
Definition at line 502 of file ssl.h.
SSL_set_msg_callback_arg
#define SSL_set_msg_callback_arg (ssl, arg) SSL_ctrl((ssl), SSL_CTRL_SET_MSG_CALLBACK_ARG, 0, (arg))
Definition at line 539 of file ssl.h.
SSL_set_mtu
#define SSL_set_mtu (ssl, mtu) SSL_ctrl((ssl),SSL_CTRL_SET_MTU,(mtu),NULL)
Definition at line 506 of file ssl.h.
SSL_set_split_send_fragment
#define SSL_set_split_send_fragment (ssl, m) SSL_ctrl(ssl,SSL_CTRL_SET_SPLIT_SEND_FRAGMENT,m,NULL)
Definition at line 1787 of file ssl.h.
SSL_set_time
#define SSL_set_time (a, b) SSL_SESSION_set_time((a),(b))
Definition at line 973 of file ssl.h.
SSL_set_timeout
#define SSL_set_timeout (a, b) SSL_SESSION_set_timeout((a),(b))
Definition at line 975 of file ssl.h.
SSL_set_tmp_dh
#define SSL_set_tmp_dh (ssl, dh) SSL_ctrl(ssl,SSL_CTRL_SET_TMP_DH,0,(char *)dh)
SSL_set_tmp_ecdh
#define SSL_set_tmp_ecdh (ssl, ecdh) SSL_ctrl(ssl,SSL_CTRL_SET_TMP_ECDH,0,(char *)ecdh)
SSL_set_tmp_rsa
#define SSL_set_tmp_rsa (ssl, rsa) 1
SSL_set_tmp_rsa_callback
#define SSL_set_tmp_rsa_callback (ssl, cb) while(0) (cb)(NULL, 0, 0)
SSL_ST_ACCEPT
#define SSL_ST_ACCEPT 0x2000
Definition at line 907 of file ssl.h.
SSL_ST_CONNECT
#define SSL_ST_CONNECT 0x1000
Definition at line 906 of file ssl.h.
SSL_ST_MASK
#define SSL_ST_MASK 0x0FFF
Definition at line 909 of file ssl.h.
SSL_ST_READ_BODY
#define SSL_ST_READ_BODY 0xF1
Definition at line 937 of file ssl.h.
Referenced by dtls1_get_record(), ssl3_pending(), SSL_rstate_string(), and SSL_rstate_string_long().
SSL_ST_READ_DONE
#define SSL_ST_READ_DONE 0xF2
Definition at line 938 of file ssl.h.
Referenced by SSL_rstate_string(), and SSL_rstate_string_long().
SSL_ST_READ_HEADER
#define SSL_ST_READ_HEADER 0xF0
Definition at line 936 of file ssl.h.
Referenced by dtls1_get_record(), RECORD_LAYER_clear(), SSL_rstate_string(), and SSL_rstate_string_long().
SSL_total_renegotiations
#define SSL_total_renegotiations (ssl) SSL_ctrl((ssl),SSL_CTRL_GET_TOTAL_RENEGOTIATIONS,0,NULL)
SSL_TXT_3DES
#define SSL_TXT_3DES "3DES"
Definition at line 143 of file ssl.h.
SSL_TXT_aDH
#define SSL_TXT_aDH "aDH"
Definition at line 118 of file ssl.h.
SSL_TXT_ADH
#define SSL_TXT_ADH "ADH"
Definition at line 132 of file ssl.h.
SSL_TXT_aDSS
#define SSL_TXT_aDSS "aDSS"
Definition at line 117 of file ssl.h.
SSL_TXT_aECDH
#define SSL_TXT_aECDH "aECDH"
Definition at line 119 of file ssl.h.
SSL_TXT_AECDH
#define SSL_TXT_AECDH "AECDH"
Definition at line 137 of file ssl.h.
SSL_TXT_aECDSA
#define SSL_TXT_aECDSA "aECDSA"
Definition at line 120 of file ssl.h.
SSL_TXT_AES
#define SSL_TXT_AES "AES"
Definition at line 150 of file ssl.h.
SSL_TXT_AES128
#define SSL_TXT_AES128 "AES128"
Definition at line 148 of file ssl.h.
SSL_TXT_AES256
#define SSL_TXT_AES256 "AES256"
Definition at line 149 of file ssl.h.
SSL_TXT_AES_CCM
#define SSL_TXT_AES_CCM "AESCCM"
Definition at line 152 of file ssl.h.
SSL_TXT_AES_CCM_8
#define SSL_TXT_AES_CCM_8 "AESCCM8"
Definition at line 153 of file ssl.h.
SSL_TXT_AES_GCM
#define SSL_TXT_AES_GCM "AESGCM"
Definition at line 151 of file ssl.h.
SSL_TXT_aGOST
#define SSL_TXT_aGOST "aGOST"
Definition at line 125 of file ssl.h.
SSL_TXT_aGOST01
#define SSL_TXT_aGOST01 "aGOST01"
Definition at line 123 of file ssl.h.
SSL_TXT_aGOST12
#define SSL_TXT_aGOST12 "aGOST12"
Definition at line 124 of file ssl.h.
SSL_TXT_aGOST94
#define SSL_TXT_aGOST94 "aGOST94"
Definition at line 122 of file ssl.h.
SSL_TXT_ALL
#define SSL_TXT_ALL "ALL"
Definition at line 175 of file ssl.h.
SSL_TXT_aNULL
#define SSL_TXT_aNULL "aNULL"
Definition at line 94 of file ssl.h.
SSL_TXT_aPSK
#define SSL_TXT_aPSK "aPSK"
Definition at line 121 of file ssl.h.
SSL_TXT_aRSA
#define SSL_TXT_aRSA "aRSA"
Definition at line 116 of file ssl.h.
SSL_TXT_aSRP
#define SSL_TXT_aSRP "aSRP"
Definition at line 126 of file ssl.h.
SSL_TXT_CAMELLIA
#define SSL_TXT_CAMELLIA "CAMELLIA"
Definition at line 156 of file ssl.h.
SSL_TXT_CAMELLIA128
#define SSL_TXT_CAMELLIA128 "CAMELLIA128"
Definition at line 154 of file ssl.h.
SSL_TXT_CAMELLIA256
#define SSL_TXT_CAMELLIA256 "CAMELLIA256"
Definition at line 155 of file ssl.h.
SSL_TXT_CHACHA20
#define SSL_TXT_CHACHA20 "CHACHA20"
Definition at line 157 of file ssl.h.
SSL_TXT_CMPALL
#define SSL_TXT_CMPALL "COMPLEMENTOFALL"
Definition at line 191 of file ssl.h.
SSL_TXT_CMPDEF
#define SSL_TXT_CMPDEF "COMPLEMENTOFDEFAULT"
Definition at line 192 of file ssl.h.
SSL_TXT_DES
#define SSL_TXT_DES "DES"
Definition at line 142 of file ssl.h.
SSL_TXT_DH
#define SSL_TXT_DH "DH"
Definition at line 129 of file ssl.h.
SSL_TXT_DHE
#define SSL_TXT_DHE "DHE"/* same as "kDHE:-ADH" */
Definition at line 130 of file ssl.h.
SSL_TXT_DSS
#define SSL_TXT_DSS "DSS"
Definition at line 128 of file ssl.h.
SSL_TXT_ECDH
#define SSL_TXT_ECDH "ECDH"
Definition at line 134 of file ssl.h.
SSL_TXT_ECDHE
#define SSL_TXT_ECDHE "ECDHE"/* same as "kECDHE:-AECDH" */
Definition at line 136 of file ssl.h.
SSL_TXT_ECDSA
#define SSL_TXT_ECDSA "ECDSA"
Definition at line 138 of file ssl.h.
SSL_TXT_EDH
#define SSL_TXT_EDH "EDH"/* alias for DHE */
Definition at line 131 of file ssl.h.
SSL_TXT_EECDH
#define SSL_TXT_EECDH "EECDH"/* alias for ECDHE" */
Definition at line 135 of file ssl.h.
SSL_TXT_eNULL
#define SSL_TXT_eNULL "eNULL"
Definition at line 95 of file ssl.h.
SSL_TXT_FIPS
#define SSL_TXT_FIPS "FIPS"
Definition at line 92 of file ssl.h.
SSL_TXT_GOST
#define SSL_TXT_GOST "GOST89"
Definition at line 158 of file ssl.h.
SSL_TXT_GOST12
#define SSL_TXT_GOST12 "GOST12"
Definition at line 165 of file ssl.h.
SSL_TXT_GOST89MAC
#define SSL_TXT_GOST89MAC "GOST89MAC"
Definition at line 164 of file ssl.h.
SSL_TXT_GOST89MAC12
#define SSL_TXT_GOST89MAC12 "GOST89MAC12"
Definition at line 166 of file ssl.h.
SSL_TXT_GOST94
#define SSL_TXT_GOST94 "GOST94"
Definition at line 163 of file ssl.h.
SSL_TXT_HIGH
#define SSL_TXT_HIGH "HIGH"
Definition at line 91 of file ssl.h.
SSL_TXT_IDEA
#define SSL_TXT_IDEA "IDEA"
Definition at line 146 of file ssl.h.
SSL_TXT_kDH
#define SSL_TXT_kDH "kDH"
Definition at line 101 of file ssl.h.
SSL_TXT_kDHd
#define SSL_TXT_kDHd "kDHd"
Definition at line 100 of file ssl.h.
SSL_TXT_kDHE
#define SSL_TXT_kDHE "kDHE"
Definition at line 103 of file ssl.h.
SSL_TXT_kDHEPSK
#define SSL_TXT_kDHEPSK "kDHEPSK"
Definition at line 112 of file ssl.h.
SSL_TXT_kDHr
#define SSL_TXT_kDHr "kDHr"
Definition at line 99 of file ssl.h.
SSL_TXT_kECDH
#define SSL_TXT_kECDH "kECDH"
Definition at line 106 of file ssl.h.
SSL_TXT_kECDHe
#define SSL_TXT_kECDHe "kECDHe"
Definition at line 105 of file ssl.h.
SSL_TXT_kECDHE
#define SSL_TXT_kECDHE "kECDHE"
Definition at line 108 of file ssl.h.
SSL_TXT_kECDHEPSK
#define SSL_TXT_kECDHEPSK "kECDHEPSK"
Definition at line 111 of file ssl.h.
SSL_TXT_kECDHr
#define SSL_TXT_kECDHr "kECDHr"
Definition at line 104 of file ssl.h.
SSL_TXT_kEDH
#define SSL_TXT_kEDH "kEDH"/* alias for kDHE */
Definition at line 102 of file ssl.h.
SSL_TXT_kEECDH
#define SSL_TXT_kEECDH "kEECDH"/* alias for kECDHE */
Definition at line 107 of file ssl.h.
SSL_TXT_kGOST
#define SSL_TXT_kGOST "kGOST"
Definition at line 113 of file ssl.h.
SSL_TXT_kPSK
#define SSL_TXT_kPSK "kPSK"
Definition at line 109 of file ssl.h.
SSL_TXT_kRSA
#define SSL_TXT_kRSA "kRSA"
Definition at line 98 of file ssl.h.
SSL_TXT_kRSAPSK
#define SSL_TXT_kRSAPSK "kRSAPSK"
Definition at line 110 of file ssl.h.
SSL_TXT_kSRP
#define SSL_TXT_kSRP "kSRP"
Definition at line 114 of file ssl.h.
SSL_TXT_LOW
#define SSL_TXT_LOW "LOW"
Definition at line 89 of file ssl.h.
SSL_TXT_MD5
#define SSL_TXT_MD5 "MD5"
Definition at line 160 of file ssl.h.
SSL_TXT_MEDIUM
#define SSL_TXT_MEDIUM "MEDIUM"
Definition at line 90 of file ssl.h.
SSL_TXT_NULL
#define SSL_TXT_NULL "NULL"
Definition at line 96 of file ssl.h.
SSL_TXT_PSK
#define SSL_TXT_PSK "PSK"
Definition at line 139 of file ssl.h.
SSL_TXT_RC2
#define SSL_TXT_RC2 "RC2"
Definition at line 145 of file ssl.h.
SSL_TXT_RC4
#define SSL_TXT_RC4 "RC4"
Definition at line 144 of file ssl.h.
SSL_TXT_RSA
#define SSL_TXT_RSA "RSA"
Definition at line 133 of file ssl.h.
SSL_TXT_SEED
#define SSL_TXT_SEED "SEED"
Definition at line 147 of file ssl.h.
SSL_TXT_SHA
#define SSL_TXT_SHA "SHA"/* same as "SHA1" */
Definition at line 162 of file ssl.h.
SSL_TXT_SHA1
#define SSL_TXT_SHA1 "SHA1"
Definition at line 161 of file ssl.h.
SSL_TXT_SHA256
#define SSL_TXT_SHA256 "SHA256"
Definition at line 167 of file ssl.h.
SSL_TXT_SHA384
#define SSL_TXT_SHA384 "SHA384"
Definition at line 168 of file ssl.h.
SSL_TXT_SRP
#define SSL_TXT_SRP "SRP"
Definition at line 140 of file ssl.h.
SSL_TXT_SSLV3
#define SSL_TXT_SSLV3 "SSLv3"
Definition at line 170 of file ssl.h.
SSL_TXT_TLSV1
#define SSL_TXT_TLSV1 "TLSv1"
Definition at line 171 of file ssl.h.
SSL_TXT_TLSV1_1
#define SSL_TXT_TLSV1_1 "TLSv1.1"
Definition at line 172 of file ssl.h.
SSL_TXT_TLSV1_2
#define SSL_TXT_TLSV1_2 "TLSv1.2"
Definition at line 173 of file ssl.h.
SSL_VERIFY_CLIENT_ONCE
#define SSL_VERIFY_CLIENT_ONCE 0x04
Definition at line 956 of file ssl.h.
SSL_VERIFY_FAIL_IF_NO_PEER_CERT
#define SSL_VERIFY_FAIL_IF_NO_PEER_CERT 0x02
Definition at line 955 of file ssl.h.
Referenced by ossl_statem_server_read_transition().
SSL_VERIFY_NONE
#define SSL_VERIFY_NONE 0x00
Definition at line 953 of file ssl.h.
SSL_VERIFY_PEER
#define SSL_VERIFY_PEER 0x01
Definition at line 954 of file ssl.h.
Referenced by ossl_statem_server_read_transition(), and tls_construct_server_hello().
SSL_want_async
#define SSL_want_async (s) (SSL_want(s) == SSL_ASYNC_PAUSED)
Definition at line 773 of file ssl.h.
Referenced by SSL_get_error().
SSL_want_async_job
#define SSL_want_async_job (s) (SSL_want(s) == SSL_ASYNC_NO_JOBS)
Definition at line 774 of file ssl.h.
Referenced by SSL_get_error().
SSL_want_nothing
#define SSL_want_nothing (s) (SSL_want(s) == SSL_NOTHING)
Definition at line 769 of file ssl.h.
SSL_want_read
#define SSL_want_read (s) (SSL_want(s) == SSL_READING)
Definition at line 770 of file ssl.h.
Referenced by SSL_get_error().
SSL_want_write
#define SSL_want_write (s) (SSL_want(s) == SSL_WRITING)
Definition at line 771 of file ssl.h.
Referenced by SSL_get_error().
SSL_want_x509_lookup
#define SSL_want_x509_lookup (s) (SSL_want(s) == SSL_X509_LOOKUP)
Definition at line 772 of file ssl.h.
Referenced by SSL_get_error().
SSL_WRITING
#define SSL_WRITING 2
Definition at line 762 of file ssl.h.
Referenced by statem_flush().
SSL_X509_LOOKUP
#define SSL_X509_LOOKUP 4
Definition at line 764 of file ssl.h.
Referenced by tls_prepare_client_certificate().
SSLeay_add_ssl_algorithms
#define SSLeay_add_ssl_algorithms () SSL_library_init()
Definition at line 960 of file ssl.h.
SSLv23_client_method
#define SSLv23_client_method TLS_client_method
SSLv23_method
#define SSLv23_method TLS_method
SSLv23_server_method
#define SSLv23_server_method TLS_server_method
TLS13_MAX_RESUMPTION_MASTER_LENGTH
#define TLS13_MAX_RESUMPTION_MASTER_LENGTH 64
Definition at line 80 of file ssl.h.
Typedef Documentation
custom_ext_add_cb
typedef int(* custom_ext_add_cb) (SSL *s, unsigned int ext_type, const unsigned char **out, size_t *outlen, int *al, void *add_arg)
Definition at line 255 of file ssl.h.
custom_ext_free_cb
typedef void(* custom_ext_free_cb) (SSL *s, unsigned int ext_type, const unsigned char *out, void *add_arg)
Definition at line 259 of file ssl.h.
custom_ext_parse_cb
typedef int(* custom_ext_parse_cb) (SSL *s, unsigned int ext_type, const unsigned char *in, size_t inlen, int *al, void *parse_arg)
Definition at line 262 of file ssl.h.
GEN_SESSION_CB
typedef int(* GEN_SESSION_CB) (const SSL *ssl, unsigned char *id, unsigned int *id_len)
Definition at line 573 of file ssl.h.
ssl_ct_validation_cb
typedef int(* ssl_ct_validation_cb) (const CT_POLICY_EVAL_CTX *ctx, const STACK_OF(SCT) *scts, void *arg)
Definition at line 1887 of file ssl.h.
SSL_CTX_alpn_select_cb_func
typedef int(* SSL_CTX_alpn_select_cb_func) (SSL *ssl, const unsigned char **out, unsigned char *outlen, const unsigned char *in, unsigned int inlen, void *arg)
Definition at line 699 of file ssl.h.
SSL_CTX_keylog_cb_func
typedef void(* SSL_CTX_keylog_cb_func) (const SSL *ssl, const char *line)
Definition at line 783 of file ssl.h.
SSL_CTX_npn_advertised_cb_func
typedef int(* SSL_CTX_npn_advertised_cb_func) (SSL *ssl, const unsigned char **out, unsigned int *outlen, void *arg)
Definition at line 661 of file ssl.h.
SSL_CTX_npn_select_cb_func
typedef int(* SSL_CTX_npn_select_cb_func) (SSL *s, unsigned char **out, unsigned char *outlen, const unsigned char *in, unsigned int inlen, void *arg)
Definition at line 670 of file ssl.h.
SSL_psk_client_cb_func
typedef unsigned int(* SSL_psk_client_cb_func) (SSL *ssl, const char *hint, char *identity, unsigned int max_identity_len, unsigned char *psk, unsigned int max_psk_len)
Definition at line 718 of file ssl.h.
SSL_psk_server_cb_func
typedef unsigned int(* SSL_psk_server_cb_func) (SSL *ssl, const char *identity, unsigned char *psk, unsigned int max_psk_len)
Definition at line 727 of file ssl.h.
SSL_verify_cb
typedef int(* SSL_verify_cb) (int preverify_ok, X509_STORE_CTX *x509_ctx)
Definition at line 267 of file ssl.h.
tls_session_secret_cb_fn
typedef int(* tls_session_secret_cb_fn) (SSL *s, void *secret, int *secret_len, STACK_OF(SSL_CIPHER) *peer_ciphers, const SSL_CIPHER **cipher, void *arg)
Definition at line 248 of file ssl.h.
tls_session_ticket_ext_cb_fn
typedef int(* tls_session_ticket_ext_cb_fn) (SSL *s, const unsigned char *data, int len, void *arg)
Definition at line 245 of file ssl.h.
TLS_SIGALGS
typedef struct tls_sigalgs_st TLS_SIGALGS
Definition at line 230 of file ssl.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SSL_CT_VALIDATION_PERMISSIVE
SSL_CT_VALIDATION_STRICT
Definition at line 1917 of file ssl.h.
OSSL_HANDSHAKE_STATE
enum OSSL_HANDSHAKE_STATE
Enumerator
TLS_ST_BEFORE
TLS_ST_OK
DTLS_ST_CR_HELLO_VERIFY_REQUEST
TLS_ST_CR_SRVR_HELLO
TLS_ST_CR_CERT
TLS_ST_CR_CERT_STATUS
TLS_ST_CR_KEY_EXCH
TLS_ST_CR_CERT_REQ
TLS_ST_CR_SRVR_DONE
TLS_ST_CR_SESSION_TICKET
TLS_ST_CR_CHANGE
TLS_ST_CR_FINISHED
TLS_ST_CW_CLNT_HELLO
TLS_ST_CW_CERT
TLS_ST_CW_KEY_EXCH
TLS_ST_CW_CERT_VRFY
TLS_ST_CW_CHANGE
TLS_ST_CW_NEXT_PROTO
TLS_ST_CW_FINISHED
TLS_ST_SW_HELLO_REQ
TLS_ST_SR_CLNT_HELLO
DTLS_ST_SW_HELLO_VERIFY_REQUEST
TLS_ST_SW_SRVR_HELLO
TLS_ST_SW_CERT
TLS_ST_SW_KEY_EXCH
TLS_ST_SW_CERT_REQ
TLS_ST_SW_SRVR_DONE
TLS_ST_SR_CERT
TLS_ST_SR_KEY_EXCH
TLS_ST_SR_CERT_VRFY
TLS_ST_SR_NEXT_PROTO
TLS_ST_SR_CHANGE
TLS_ST_SR_FINISHED
TLS_ST_SW_SESSION_TICKET
TLS_ST_SW_CERT_STATUS
TLS_ST_SW_CHANGE
TLS_ST_SW_FINISHED
TLS_ST_SW_ENCRYPTED_EXTENSIONS
TLS_ST_CR_ENCRYPTED_EXTENSIONS
TLS_ST_CR_CERT_VRFY
TLS_ST_SW_CERT_VRFY
TLS_ST_CR_HELLO_REQ
TLS_ST_SW_HELLO_RETRY_REQUEST
TLS_ST_CR_HELLO_RETRY_REQUEST
TLS_ST_SW_KEY_UPDATE
TLS_ST_CW_KEY_UPDATE
TLS_ST_SR_KEY_UPDATE
TLS_ST_CR_KEY_UPDATE
Definition at line 847 of file ssl.h.
Function Documentation
BIO_new_buffer_ssl_connect()
__owur BIO* BIO_new_buffer_ssl_connect (SSL_CTX * ctx)
Definition at line 442 of file bio_ssl.c.
BIO_new_ssl()
__owur BIO* BIO_new_ssl (SSL_CTX * ctx, int client)
Definition at line 479 of file bio_ssl.c.
Referenced by process_responder().
BIO_new_ssl_connect()
__owur BIO* BIO_new_ssl_connect (SSL_CTX * ctx)
Definition at line 461 of file bio_ssl.c.
BIO_ssl_copy_session_id()
__owur int BIO_ssl_copy_session_id (BIO * to, BIO * from)
Definition at line 499 of file bio_ssl.c.
References BIO_find_type(), BIO_get_data(), BIO_TYPE_SSL, NULL, BIO_SSL::ssl, and SSL_copy_session_id().
BIO_ssl_shutdown()
void BIO_ssl_shutdown (BIO * ssl_bio)
Definition at line 515 of file bio_ssl.c.
References BIO_find_type(), BIO_get_data(), BIO_TYPE_SSL, NULL, and SSL_shutdown().
d2i_SSL_SESSION()
SSL_SESSION* d2i_SSL_SESSION (SSL_SESSION ** a, const unsigned char ** pp, long length)
DECLARE_PEM_rw()
DECLARE_PEM_rw (SSL_SESSION , SSL_SESSION) const
DEPRECATEDIN_1_1_0()
DEPRECATEDIN_1_1_0 (__owur const SSL_METHOD * SSLv3_methodvoid) const
DTLS_client_method()
__owur const SSL_METHOD* DTLS_client_method (void)
DTLS_get_data_mtu()
__owur size_t DTLS_get_data_mtu (const SSL * s)
Definition at line 927 of file d1_lib.c.
References DTLS1_RT_HEADER_LENGTH, NULL, ssl_cipher_get_overhead(), SSL_get_current_cipher(), and SSL_READ_ETM.
DTLS_server_method()
__owur const SSL_METHOD* DTLS_server_method (void)
DTLSv1_listen()
int DTLSv1_listen (SSL * s, BIO_ADDR * client)
Definition at line 421 of file d1_lib.c.
ERR_load_SSL_strings()
int ERR_load_SSL_strings (void)
Definition at line 821 of file ssl_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by DEFINE_RUN_ONCE_STATIC().
i2d_SSL_SESSION()
__owur int i2d_SSL_SESSION (SSL_SESSION * in, unsigned char ** pp)
LHASH_OF()
LHASH_OF (SSL_SESSION)
Definition at line 1890 of file ssl_lib.c.
OPENSSL_init_ssl()
int OPENSSL_init_ssl (uint64_t opts, const OPENSSL_INIT_SETTINGS * settings)
Definition at line 177 of file ssl_init.c.
Referenced by SSL_SESSION_new().
SRP_Calc_A_param()
__owur int SRP_Calc_A_param (SSL * s)
Definition at line 381 of file tls_srp.c.
References BN_bin2bn(), OPENSSL_cleanse(), RAND_bytes(), SRP_Calc_A(), and SSL_MAX_MASTER_KEY_LENGTH.
SSL_accept()
__owur int SSL_accept (SSL * ssl)
Definition at line 1455 of file ssl_lib.c.
References NULL, SSL_do_handshake(), and SSL_set_accept_state().
SSL_add1_host()
__owur int SSL_add1_host (SSL * s, const char * hostname)
Definition at line 788 of file ssl_lib.c.
References X509_VERIFY_PARAM_add1_host().
SSL_add_client_CA()
__owur int SSL_add_client_CA (SSL * ssl, X509 * x)
Definition at line 541 of file ssl_cert.c.
SSL_add_dir_cert_subjects_to_stack()
int SSL_add_dir_cert_subjects_to_stack (STACK_OF(X509_NAME) * stack, const char * dir)
Add a directory of certs to a stack.
Parameters
stack the stack to append to.
dir the directory to append from. All files in this directory will be examined as potential certs. Any that are acceptable to SSL_add_dir_cert_subjects_to_stack() that are not already in the stack will be included.
Returns
1 for success, 0 for failure. Note that in the case of failure some certs may have been added to stack.
Definition at line 701 of file ssl_cert.c.
References NULL.
SSL_add_file_cert_subjects_to_stack()
__owur int SSL_add_file_cert_subjects_to_stack (STACK_OF(X509_NAME) * stack, const char * file)
Add a file of certs to a stack.
Parameters
stack the stack to add to.
file the file to add from. All certs in this file that are not already in the stack will be added.
Returns
1 for success, 0 for failure. Note that in the case of failure some certs may have been added to stack.
Definition at line 640 of file ssl_cert.c.
References in, and NULL.
SSL_add_ssl_module()
void SSL_add_ssl_module (void)
Definition at line 119 of file ssl_mcnf.c.
References CONF_module_add().
Referenced by DEFINE_RUN_ONCE_STATIC().
SSL_alert_desc_string()
__owur const char* SSL_alert_desc_string (int value)
Definition at line 226 of file ssl_stat.c.
References SSL3_AD_BAD_CERTIFICATE, SSL3_AD_BAD_RECORD_MAC, SSL3_AD_CERTIFICATE_EXPIRED, SSL3_AD_CERTIFICATE_REVOKED, SSL3_AD_CERTIFICATE_UNKNOWN, SSL3_AD_CLOSE_NOTIFY, SSL3_AD_DECOMPRESSION_FAILURE, SSL3_AD_HANDSHAKE_FAILURE, SSL3_AD_ILLEGAL_PARAMETER, SSL3_AD_NO_CERTIFICATE, SSL3_AD_UNEXPECTED_MESSAGE, SSL3_AD_UNSUPPORTED_CERTIFICATE, TLS1_AD_ACCESS_DENIED, TLS1_AD_BAD_CERTIFICATE_HASH_VALUE, TLS1_AD_BAD_CERTIFICATE_STATUS_RESPONSE, TLS1_AD_CERTIFICATE_UNOBTAINABLE, TLS1_AD_DECODE_ERROR, TLS1_AD_DECRYPT_ERROR, TLS1_AD_DECRYPTION_FAILED, TLS1_AD_EXPORT_RESTRICTION, TLS1_AD_INSUFFICIENT_SECURITY, TLS1_AD_INTERNAL_ERROR, TLS1_AD_NO_RENEGOTIATION, TLS1_AD_PROTOCOL_VERSION, TLS1_AD_RECORD_OVERFLOW, TLS1_AD_UNKNOWN_CA, TLS1_AD_UNKNOWN_PSK_IDENTITY, TLS1_AD_UNRECOGNIZED_NAME, TLS1_AD_UNSUPPORTED_EXTENSION, and TLS1_AD_USER_CANCELLED.
SSL_alert_desc_string_long()
__owur const char* SSL_alert_desc_string_long (int value)
Definition at line 294 of file ssl_stat.c.
References SSL3_AD_BAD_CERTIFICATE, SSL3_AD_BAD_RECORD_MAC, SSL3_AD_CERTIFICATE_EXPIRED, SSL3_AD_CERTIFICATE_REVOKED, SSL3_AD_CERTIFICATE_UNKNOWN, SSL3_AD_CLOSE_NOTIFY, SSL3_AD_DECOMPRESSION_FAILURE, SSL3_AD_HANDSHAKE_FAILURE, SSL3_AD_ILLEGAL_PARAMETER, SSL3_AD_NO_CERTIFICATE, SSL3_AD_UNEXPECTED_MESSAGE, SSL3_AD_UNSUPPORTED_CERTIFICATE, TLS1_AD_ACCESS_DENIED, TLS1_AD_BAD_CERTIFICATE_HASH_VALUE, TLS1_AD_BAD_CERTIFICATE_STATUS_RESPONSE, TLS1_AD_CERTIFICATE_UNOBTAINABLE, TLS1_AD_DECODE_ERROR, TLS1_AD_DECRYPT_ERROR, TLS1_AD_DECRYPTION_FAILED, TLS1_AD_EXPORT_RESTRICTION, TLS1_AD_INSUFFICIENT_SECURITY, TLS1_AD_INTERNAL_ERROR, TLS1_AD_NO_APPLICATION_PROTOCOL, TLS1_AD_NO_RENEGOTIATION, TLS1_AD_PROTOCOL_VERSION, TLS1_AD_RECORD_OVERFLOW, TLS1_AD_UNKNOWN_CA, TLS1_AD_UNKNOWN_PSK_IDENTITY, TLS1_AD_UNRECOGNIZED_NAME, TLS1_AD_UNSUPPORTED_EXTENSION, and TLS1_AD_USER_CANCELLED.
SSL_alert_type_string()
__owur const char* SSL_alert_type_string (int value)
Definition at line 214 of file ssl_stat.c.
References SSL3_AL_FATAL, and SSL3_AL_WARNING.
SSL_alert_type_string_long()
__owur const char* SSL_alert_type_string_long (int value)
Definition at line 202 of file ssl_stat.c.
References SSL3_AL_FATAL, and SSL3_AL_WARNING.
SSL_callback_ctrl()
long SSL_callback_ctrl (SSL * , int , void(*)(void))
Definition at line 1875 of file ssl_lib.c.
References ssl_async_args::buf, len, and SSL_CTRL_SET_MSG_CALLBACK.
Referenced by SSL_set_not_resumable_session_callback(), and SSL_set_tmp_dh_callback().
SSL_certs_clear()
void SSL_certs_clear (SSL * s)
Definition at line 957 of file ssl_lib.c.
References ssl_cert_clear_certs().
SSL_check_private_key()
__owur int SSL_check_private_key (const SSL * ctx)
Definition at line 1409 of file ssl_lib.c.
References ERR_R_PASSED_NULL_PARAMETER, NULL, SSL_F_SSL_CHECK_PRIVATE_KEY, SSL_R_NO_CERTIFICATE_ASSIGNED, SSL_R_NO_PRIVATE_KEY_ASSIGNED, SSLerr, and X509_check_private_key().
SSL_CIPHER_description()
__owur char* SSL_CIPHER_description (const SSL_CIPHER * , char * buf, int size)
Definition at line 1531 of file ssl_ciph.c.
SSL_CIPHER_find()
const SSL_CIPHER* SSL_CIPHER_find (SSL * ssl, const unsigned char * ptr)
Definition at line 1930 of file ssl_ciph.c.
SSL_CIPHER_get_auth_nid()
__owur int SSL_CIPHER_get_auth_nid (const SSL_CIPHER * c)
Definition at line 1964 of file ssl_ciph.c.
References ssl_cipher_table::nid, NID_undef, and ssl_cipher_info_lookup.
SSL_CIPHER_get_bits()
__owur int SSL_CIPHER_get_bits (const SSL_CIPHER * c, int * alg_bits)
Definition at line 1746 of file ssl_ciph.c.
SSL_CIPHER_get_cipher_nid()
int SSL_CIPHER_get_cipher_nid (const SSL_CIPHER * c)
Definition at line 1935 of file ssl_ciph.c.
References ssl_cipher_table::nid, NID_undef, NULL, and ssl_cipher_info_lookup.
SSL_CIPHER_get_digest_nid()
int SSL_CIPHER_get_digest_nid (const SSL_CIPHER * c)
Definition at line 1946 of file ssl_ciph.c.
References ssl_cipher_table::nid, NID_undef, and ssl_cipher_info_lookup.
SSL_CIPHER_get_id()
__owur uint32_t SSL_CIPHER_get_id (const SSL_CIPHER * c)
Definition at line 1758 of file ssl_ciph.c.
SSL_CIPHER_get_kx_nid()
__owur int SSL_CIPHER_get_kx_nid (const SSL_CIPHER * c)
Definition at line 1955 of file ssl_ciph.c.
References ssl_cipher_table::nid, NID_undef, and ssl_cipher_info_lookup.
SSL_CIPHER_get_name()
__owur const char* SSL_CIPHER_get_name (const SSL_CIPHER * c)
Definition at line 1738 of file ssl_ciph.c.
References NULL.
SSL_CIPHER_get_version()
__owur const char* SSL_CIPHER_get_version (const SSL_CIPHER * c)
Definition at line 1723 of file ssl_ciph.c.
References NULL, ssl_protocol_to_string(), and TLS1_VERSION.
SSL_CIPHER_is_aead()
__owur int SSL_CIPHER_is_aead (const SSL_CIPHER * c)
Definition at line 1973 of file ssl_ciph.c.
References SSL_AEAD.
SSL_CIPHER_standard_name()
__owur const char* SSL_CIPHER_standard_name (const SSL_CIPHER * c)
Definition at line 1378 of file t1_trce.c.
SSL_clear()
__owur int SSL_clear (SSL * s)
Definition at line 442 of file ssl_lib.c.
References BUF_MEM_free(), ERR_R_INTERNAL_ERROR, NULL, ossl_statem_clear(), ssl_clear_bad_session(), SSL_F_SSL_CLEAR, SSL_NOTHING, SSL_R_NO_METHOD_SPECIFIED, SSL_SESSION_free(), and SSLerr.
Referenced by SSL_new().
SSL_clear_options()
unsigned long SSL_clear_options (SSL * s, unsigned long op)
Definition at line 3915 of file ssl_lib.c.
References IMPLEMENT_OBJ_BSEARCH_GLOBAL_CMP_FN(), and STACK_OF().
SSL_client_version()
__owur int SSL_client_version (const SSL * s)
Definition at line 3418 of file ssl_lib.c.
SSL_COMP_add_compression_method()
__owur int SSL_COMP_add_compression_method (int id, COMP_METHOD * cm)
Definition at line 1823 of file ssl_ciph.c.
References COMP_get_type(), CRYPTO_MEM_CHECK_DISABLE, CRYPTO_MEM_CHECK_ENABLE, CRYPTO_mem_ctrl(), ERR_R_MALLOC_FAILURE, NID_undef, NULL, OPENSSL_malloc, SSL_F_SSL_COMP_ADD_COMPRESSION_METHOD, SSL_R_COMPRESSION_ID_NOT_WITHIN_PRIVATE_RANGE, and SSLerr.
Referenced by ssl3_comp_find().
SSL_COMP_get0_name()
__owur const char* SSL_COMP_get0_name (const SSL_COMP * comp)
Definition at line 1882 of file ssl_ciph.c.
References NULL.
SSL_COMP_get_id()
__owur int SSL_COMP_get_id (const SSL_COMP * comp)
Definition at line 1891 of file ssl_ciph.c.
SSL_COMP_get_name()
__owur const char* SSL_COMP_get_name (const COMP_METHOD * comp)
Definition at line 1873 of file ssl_ciph.c.
References COMP_get_name(), and NULL.
SSL_CONF_cmd()
__owur int SSL_CONF_cmd (SSL_CONF_CTX * cctx, const char * cmd, const char * value)
Definition at line 691 of file ssl_conf.c.
References NULL, SSL_F_SSL_CONF_CMD, SSL_R_INVALID_NULL_CMD_NAME, and SSLerr.
SSL_CONF_cmd_argv()
__owur int SSL_CONF_cmd_argv (SSL_CONF_CTX * cctx, int * pargc, char *** pargv)
Definition at line 731 of file ssl_conf.c.
SSL_CONF_cmd_value_type()
__owur int SSL_CONF_cmd_value_type (SSL_CONF_CTX * cctx, const char * cmd)
Definition at line 764 of file ssl_conf.c.
SSL_CONF_CTX_clear_flags()
__owur unsigned int SSL_CONF_CTX_clear_flags (SSL_CONF_CTX * cctx, unsigned int flags)
Definition at line 833 of file ssl_conf.c.
SSL_CONF_CTX_finish()
int SSL_CONF_CTX_finish (SSL_CONF_CTX * cctx)
Definition at line 782 of file ssl_conf.c.
SSL_CONF_CTX_free()
void SSL_CONF_CTX_free (SSL_CONF_CTX * cctx)
Definition at line 815 of file ssl_conf.c.
References OPENSSL_free, and SSL_PKEY_NUM.
SSL_CONF_CTX_new()
__owur __owur SSL_CONF_CTX* SSL_CONF_CTX_new (void)
Definition at line 775 of file ssl_conf.c.
SSL_CONF_CTX_set1_prefix()
__owur int SSL_CONF_CTX_set1_prefix (SSL_CONF_CTX * cctx, const char * pre)
Definition at line 839 of file ssl_conf.c.
References NULL, OPENSSL_free, and OPENSSL_strdup.
SSL_CONF_CTX_set_flags()
unsigned int SSL_CONF_CTX_set_flags (SSL_CONF_CTX * cctx, unsigned int flags)
Definition at line 827 of file ssl_conf.c.
References flags.
SSL_CONF_CTX_set_ssl()
void SSL_CONF_CTX_set_ssl (SSL_CONF_CTX * cctx, SSL * ssl)
Definition at line 856 of file ssl_conf.c.
References NULL.
SSL_CONF_CTX_set_ssl_ctx()
void SSL_CONF_CTX_set_ssl_ctx (SSL_CONF_CTX * cctx, SSL_CTX * ctx)
Definition at line 875 of file ssl_conf.c.
References ctx, and NULL.
Referenced by config_ctx().
SSL_config()
int SSL_config (SSL * s, const char * name)
Definition at line 191 of file ssl_mcnf.c.
SSL_connect()
__owur int SSL_connect (SSL * ssl)
Definition at line 1465 of file ssl_lib.c.
References NULL, SSL_do_handshake(), and SSL_set_connect_state().
SSL_copy_session_id()
__owur int SSL_copy_session_id (SSL * to, const SSL * from)
Definition at line 1365 of file ssl_lib.c.
References CRYPTO_UP_REF, ssl_cert_free(), SSL_get_session(), SSL_set_session(), and SSL_set_session_id_context().
Referenced by BIO_ssl_copy_session_id().
SSL_ct_is_enabled()
int SSL_ct_is_enabled (const SSL * s)
Definition at line 4155 of file ssl_lib.c.
References NULL.
SSL_ctrl()
long SSL_ctrl (SSL * ssl, int cmd, long larg, void * parg)
Definition at line 1791 of file ssl_lib.c.
References NULL, ossl_statem_get_in_handshake(), RECORD_LAYER_get_read_ahead, RECORD_LAYER_set_read_ahead, SSL3_RT_MAX_PLAIN_LENGTH, SSL_CTRL_CERT_FLAGS, SSL_CTRL_CLEAR_CERT_FLAGS, SSL_CTRL_CLEAR_MODE, SSL_CTRL_GET_EXTMS_SUPPORT, SSL_CTRL_GET_MAX_CERT_LIST, SSL_CTRL_GET_RAW_CIPHERLIST, SSL_CTRL_GET_READ_AHEAD, SSL_CTRL_GET_RI_SUPPORT, SSL_CTRL_MODE, SSL_CTRL_SET_MAX_CERT_LIST, SSL_CTRL_SET_MAX_PIPELINES, SSL_CTRL_SET_MAX_PROTO_VERSION, SSL_CTRL_SET_MAX_SEND_FRAGMENT, SSL_CTRL_SET_MIN_PROTO_VERSION, SSL_CTRL_SET_MSG_CALLBACK_ARG, SSL_CTRL_SET_READ_AHEAD, SSL_CTRL_SET_SPLIT_SEND_FRAGMENT, SSL_in_init(), SSL_MAX_PIPELINES, SSL_SESS_FLAG_EXTMS, ssl_set_version_bound(), and TLS_CIPHER_LEN.
SSL_CTX_add_client_CA()
__owur int SSL_CTX_add_client_CA (SSL_CTX * ctx, X509 * x)
Definition at line 546 of file ssl_cert.c.
SSL_CTX_add_client_custom_ext()
__owur int SSL_CTX_add_client_custom_ext (SSL_CTX * ctx, unsigned int ext_type, custom_ext_add_cb add_cb, custom_ext_free_cb free_cb, void * add_arg, custom_ext_parse_cb parse_cb, void * parse_arg)
Definition at line 205 of file t1_ext.c.
References SSL_CTX_ct_is_enabled(), and TLSEXT_TYPE_signed_certificate_timestamp.
SSL_CTX_add_server_custom_ext()
__owur int SSL_CTX_add_server_custom_ext (SSL_CTX * ctx, unsigned int ext_type, custom_ext_add_cb add_cb, custom_ext_free_cb free_cb, void * add_arg, custom_ext_parse_cb parse_cb, void * parse_arg)
Definition at line 225 of file t1_ext.c.
SSL_CTX_add_session()
__owur int SSL_CTX_add_session (SSL_CTX * s, SSL_SESSION * c)
Definition at line 648 of file ssl_sess.c.
Referenced by ssl_update_cache().
SSL_CTX_callback_ctrl()
long SSL_CTX_callback_ctrl (SSL_CTX * , int , void(*)(void))
Definition at line 2009 of file ssl_lib.c.
References ssl_async_args::buf, len, and SSL_CTRL_SET_MSG_CALLBACK.
Referenced by SSL_CTX_set_not_resumable_session_callback(), and SSL_CTX_set_tmp_dh_callback().
SSL_CTX_check_private_key()
__owur int SSL_CTX_check_private_key (const SSL_CTX * ctx)
Definition at line 1394 of file ssl_lib.c.
References NULL, SSL_F_SSL_CTX_CHECK_PRIVATE_KEY, SSL_R_NO_CERTIFICATE_ASSIGNED, SSL_R_NO_PRIVATE_KEY_ASSIGNED, SSLerr, and X509_check_private_key().
Referenced by create_ssl_ctx_pair(), and set_cert_stuff().
SSL_CTX_clear_options()
unsigned long SSL_CTX_clear_options (SSL_CTX * ctx, unsigned long op)
Definition at line 3910 of file ssl_lib.c.
SSL_CTX_config()
int SSL_CTX_config (SSL_CTX * ctx, const char * name)
Definition at line 196 of file ssl_mcnf.c.
SSL_CTX_ct_is_enabled()
int SSL_CTX_ct_is_enabled (const SSL_CTX * ctx)
Definition at line 4160 of file ssl_lib.c.
References NULL.
Referenced by SSL_CTX_add_client_custom_ext().
SSL_CTX_ctrl()
long SSL_CTX_ctrl (SSL_CTX * ctx, int cmd, long larg, void * parg)
Definition at line 1895 of file ssl_lib.c.
References NULL, SSL3_RT_MAX_PLAIN_LENGTH, SSL_CTRL_CERT_FLAGS, SSL_CTRL_CLEAR_CERT_FLAGS, SSL_CTRL_CLEAR_MODE, SSL_CTRL_GET_MAX_CERT_LIST, SSL_CTRL_GET_READ_AHEAD, SSL_CTRL_GET_SESS_CACHE_MODE, SSL_CTRL_GET_SESS_CACHE_SIZE, SSL_CTRL_MODE, SSL_CTRL_SESS_ACCEPT, SSL_CTRL_SESS_ACCEPT_GOOD, SSL_CTRL_SESS_ACCEPT_RENEGOTIATE, SSL_CTRL_SESS_CACHE_FULL, SSL_CTRL_SESS_CB_HIT, SSL_CTRL_SESS_CONNECT, SSL_CTRL_SESS_CONNECT_GOOD, SSL_CTRL_SESS_CONNECT_RENEGOTIATE, SSL_CTRL_SESS_HIT, SSL_CTRL_SESS_MISSES, SSL_CTRL_SESS_NUMBER, SSL_CTRL_SESS_TIMEOUTS, SSL_CTRL_SET_CLIENT_SIGALGS_LIST, SSL_CTRL_SET_GROUPS_LIST, SSL_CTRL_SET_MAX_CERT_LIST, SSL_CTRL_SET_MAX_PIPELINES, SSL_CTRL_SET_MAX_PROTO_VERSION, SSL_CTRL_SET_MAX_SEND_FRAGMENT, SSL_CTRL_SET_MIN_PROTO_VERSION, SSL_CTRL_SET_MSG_CALLBACK_ARG, SSL_CTRL_SET_READ_AHEAD, SSL_CTRL_SET_SESS_CACHE_MODE, SSL_CTRL_SET_SESS_CACHE_SIZE, SSL_CTRL_SET_SIGALGS_LIST, SSL_CTRL_SET_SPLIT_SEND_FRAGMENT, SSL_MAX_PIPELINES, ssl_set_version_bound(), tls1_set_groups_list(), and tls1_set_sigalgs_list().
SSL_CTX_dane_clear_flags()
unsigned long SSL_CTX_dane_clear_flags (SSL_CTX * ctx, unsigned long flags)
Definition at line 816 of file ssl_lib.c.
SSL_CTX_dane_enable()
__owur int SSL_CTX_dane_enable (SSL_CTX * ctx)
Definition at line 803 of file ssl_lib.c.
SSL_CTX_dane_mtype_set()
__owur int SSL_CTX_dane_mtype_set (SSL_CTX * ctx, const EVP_MD * md, uint8_t mtype, uint8_t ord)
Definition at line 931 of file ssl_lib.c.
SSL_CTX_dane_set_flags()
unsigned long SSL_CTX_dane_set_flags (SSL_CTX * ctx, unsigned long flags)
Definition at line 808 of file ssl_lib.c.
References flags.
SSL_CTX_enable_ct()
int SSL_CTX_enable_ct (SSL_CTX * ctx, int validation_mode)
Definition at line 4261 of file ssl_lib.c.
References SSL_CT_VALIDATION_PERMISSIVE, SSL_CTX_set_ct_validation_callback(), SSL_F_SSL_CTX_ENABLE_CT, SSL_R_INVALID_CT_VALIDATION_TYPE, and SSLerr.
SSL_CTX_flush_sessions()
void SSL_CTX_flush_sessions (SSL_CTX * ctx, long tm)
Definition at line 1013 of file ssl_sess.c.
References CRYPTO_THREAD_write_lock(), TIMEOUT_PARAM::ctx, NULL, t, and TIMEOUT_PARAM::time.
Referenced by ssl_update_cache().
SSL_CTX_free()
void SSL_CTX_free (SSL_CTX *)
Definition at line 2621 of file ssl_lib.c.
References CRYPTO_DOWN_REF, NULL, REF_ASSERT_ISNT, REF_PRINT_COUNT, and X509_VERIFY_PARAM_free().
Referenced by create_ssl_ctx_pair(), and SSL_set_SSL_CTX().
SSL_CTX_get0_certificate()
__owur X509* SSL_CTX_get0_certificate (const SSL_CTX * ctx)
Definition at line 3309 of file ssl_lib.c.
References NULL.
SSL_CTX_get0_ctlog_store()
const CTLOG_STORE* SSL_CTX_get0_ctlog_store (const SSL_CTX * ctx)
Definition at line 4303 of file ssl_lib.c.
SSL_CTX_get0_param()
__owur X509_VERIFY_PARAM* SSL_CTX_get0_param (SSL_CTX * ctx)
Definition at line 947 of file ssl_lib.c.
SSL_CTX_get0_privatekey()
__owur EVP_PKEY* SSL_CTX_get0_privatekey (const SSL_CTX * ctx)
Definition at line 3317 of file ssl_lib.c.
References NULL.
SSL_CTX_get0_security_ex_data()
__owur void* SSL_CTX_get0_security_ex_data (const SSL_CTX * ctx)
Definition at line 3880 of file ssl_lib.c.
SSL_CTX_get_cert_store()
__owur X509_STORE* SSL_CTX_get_cert_store (const SSL_CTX *)
Definition at line 3592 of file ssl_lib.c.
Referenced by ssl_ctx_add_crls().
SSL_CTX_get_default_passwd_cb()
pem_password_cb* SSL_CTX_get_default_passwd_cb (SSL_CTX * ctx)
Definition at line 2692 of file ssl_lib.c.
SSL_CTX_get_default_passwd_cb_userdata()
void* SSL_CTX_get_default_passwd_cb_userdata (SSL_CTX * ctx)
Definition at line 2697 of file ssl_lib.c.
SSL_CTX_get_ex_data()
void* SSL_CTX_get_ex_data (const SSL_CTX * ssl, int idx)
Definition at line 3582 of file ssl_lib.c.
SSL_CTX_get_keylog_callback()
SSL_CTX_keylog_cb_func SSL_CTX_get_keylog_callback (const SSL_CTX * ctx)
Definition at line 4315 of file ssl_lib.c.
SSL_CTX_get_options()
unsigned long SSL_CTX_get_options (const SSL_CTX * ctx)
Definition at line 3890 of file ssl_lib.c.
SSL_CTX_get_quiet_shutdown()
__owur int SSL_CTX_get_quiet_shutdown (const SSL_CTX * ctx)
Definition at line 3388 of file ssl_lib.c.
SSL_CTX_get_security_level()
__owur int SSL_CTX_get_security_level (const SSL_CTX * ctx)
Definition at line 3853 of file ssl_lib.c.
SSL_CTX_get_ssl_method()
__owur const SSL_METHOD* SSL_CTX_get_ssl_method (SSL_CTX * ctx)
Definition at line 2912 of file ssl_lib.c.
SSL_CTX_get_timeout()
__owur long SSL_CTX_get_timeout (const SSL_CTX * ctx)
Definition at line 934 of file ssl_sess.c.
References NULL.
SSL_CTX_get_verify_callback()
__owur SSL_verify_cb SSL_CTX_get_verify_callback (const SSL_CTX * ctx)
SSL_CTX_get_verify_depth()
__owur int SSL_CTX_get_verify_depth (const SSL_CTX * ctx)
Definition at line 1262 of file ssl_lib.c.
References X509_VERIFY_PARAM_get_depth().
SSL_CTX_get_verify_mode()
__owur int SSL_CTX_get_verify_mode (const SSL_CTX * ctx)
Definition at line 1257 of file ssl_lib.c.
SSL_CTX_has_client_custom_ext()
__owur int SSL_CTX_has_client_custom_ext (const SSL_CTX * ctx, unsigned int ext_type)
Definition at line 199 of file t1_ext.c.
SSL_CTX_load_verify_locations()
__owur int SSL_CTX_load_verify_locations (SSL_CTX * ctx, const char * CAfile, const char * CApath)
Definition at line 3504 of file ssl_lib.c.
References X509_STORE_load_locations().
Referenced by ctx_set_verify_locations().
SSL_CTX_new()
__owur SSL_CTX* SSL_CTX_new (const SSL_METHOD * meth)
Definition at line 2466 of file ssl_lib.c.
Referenced by create_ssl_ctx_pair(), main(), and process_responder().
SSL_CTX_remove_session()
int SSL_CTX_remove_session (SSL_CTX * , SSL_SESSION * c)
Definition at line 725 of file ssl_sess.c.
Referenced by ssl3_send_alert(), and ssl_clear_bad_session().
SSL_CTX_sess_set_get_cb()
void SSL_CTX_sess_set_get_cb (SSL_CTX * ctx, SSL_SESSION *(*)(struct ssl_st *ssl, const unsigned char *data, int len, int *copy) get_session_cb)
Definition at line 1111 of file ssl_sess.c.
References cb.
SSL_CTX_sess_set_new_cb()
void SSL_CTX_sess_set_new_cb (SSL_CTX * ctx, int(*)(struct ssl_st *ssl, SSL_SESSION *sess) new_session_cb)
Definition at line 1090 of file ssl_sess.c.
References cb.
SSL_CTX_sess_set_remove_cb()
void SSL_CTX_sess_set_remove_cb (SSL_CTX * ctx, void(*)(struct ssl_ctx_st *ctx, SSL_SESSION *sess) remove_session_cb)
SSL_CTX_set0_ctlog_store()
void SSL_CTX_set0_ctlog_store (SSL_CTX * ctx, CTLOG_STORE * logs)
Definition at line 4297 of file ssl_lib.c.
References CTLOG_STORE_free().
SSL_CTX_set0_security_ex_data()
void SSL_CTX_set0_security_ex_data (SSL_CTX * ctx, void * ex)
Definition at line 3875 of file ssl_lib.c.
References ex.
SSL_CTX_set1_cert_store()
void SSL_CTX_set1_cert_store (SSL_CTX * , X509_STORE *)
Definition at line 3603 of file ssl_lib.c.
References NULL, SSL_CTX_set_cert_store(), and X509_STORE_up_ref().
SSL_CTX_set1_param()
__owur int SSL_CTX_set1_param (SSL_CTX * ctx, X509_VERIFY_PARAM * vpm)
Definition at line 937 of file ssl_lib.c.
References X509_VERIFY_PARAM_set1().
SSL_CTX_set_alpn_protos()
__owur int SSL_CTX_set_alpn_protos (SSL_CTX * ctx, const unsigned char * protos, unsigned int protos_len)
Definition at line 2346 of file ssl_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_memdup, SSL_F_SSL_CTX_SET_ALPN_PROTOS, and SSLerr.
SSL_CTX_set_alpn_select_cb()
void SSL_CTX_set_alpn_select_cb (SSL_CTX * ctx, SSL_CTX_alpn_select_cb_func cb, void * arg)
Definition at line 2384 of file ssl_lib.c.
SSL_CTX_set_cert_cb()
void SSL_CTX_set_cert_cb (SSL_CTX * c, int(*)(SSL *ssl, void *arg) cb, void * arg)
Definition at line 2742 of file ssl_lib.c.
Referenced by ssl_ctx_set_excert().
SSL_CTX_set_cert_store()
void SSL_CTX_set_cert_store (SSL_CTX * , X509_STORE *)
Definition at line 3597 of file ssl_lib.c.
References X509_STORE_free().
Referenced by SSL_CTX_set1_cert_store().
SSL_CTX_set_cert_verify_callback()
void SSL_CTX_set_cert_verify_callback (SSL_CTX * ctx, int(*)(X509_STORE_CTX *, void *) cb, void * arg)
Definition at line 2722 of file ssl_lib.c.
SSL_CTX_set_cipher_list()
__owur int SSL_CTX_set_cipher_list (SSL_CTX * ctx, const char * str)
specify the ciphers to be used by default by the SSL_CTX
Definition at line 2129 of file ssl_lib.c.
References NULL, SSL_F_SSL_CTX_SET_CIPHER_LIST, SSL_R_NO_CIPHER_MATCH, SSLerr, and STACK_OF().
SSL_CTX_set_client_CA_list()
void SSL_CTX_set_client_CA_list (SSL_CTX * ctx, STACK_OF(X509_NAME) * name_list)
Definition at line 497 of file ssl_cert.c.
SSL_CTX_set_client_cert_cb()
void SSL_CTX_set_client_cert_cb (SSL_CTX * ctx, int(*)(SSL *ssl, X509 **x509, EVP_PKEY **pkey) client_cert_cb)
Definition at line 1137 of file ssl_sess.c.
References cb.
SSL_CTX_set_client_cert_engine()
__owur int SSL_CTX_set_client_cert_engine (SSL_CTX * ctx, ENGINE * e)
Definition at line 1150 of file ssl_sess.c.
References e, ENGINE_finish(), ENGINE_get_ssl_client_cert_function(), ENGINE_init(), ERR_R_ENGINE_LIB, SSL_F_SSL_CTX_SET_CLIENT_CERT_ENGINE, SSL_R_NO_CLIENT_CERT_METHOD, and SSLerr.
SSL_CTX_set_cookie_generate_cb()
void SSL_CTX_set_cookie_generate_cb (SSL_CTX * ctx, int(*)(SSL *ssl, unsigned char *cookie, unsigned int *cookie_len) app_gen_cookie_cb)
Definition at line 1167 of file ssl_sess.c.
SSL_CTX_set_cookie_verify_cb()
void SSL_CTX_set_cookie_verify_cb (SSL_CTX * ctx, int(*)(SSL *ssl, const unsigned char *cookie, unsigned int cookie_len) app_verify_cookie_cb)
Definition at line 1175 of file ssl_sess.c.
SSL_CTX_set_ct_validation_callback()
int SSL_CTX_set_ct_validation_callback (SSL_CTX * ctx, ssl_ct_validation_cb callback, void * arg)
Definition at line 4135 of file ssl_lib.c.
Referenced by SSL_CTX_enable_ct().
SSL_CTX_set_ctlog_list_file()
int SSL_CTX_set_ctlog_list_file (SSL_CTX * ctx, const char * path)
Definition at line 4292 of file ssl_lib.c.
References CTLOG_STORE_load_file().
Referenced by ctx_set_ctlog_list_file().
SSL_CTX_set_default_ctlog_list_file()
int SSL_CTX_set_default_ctlog_list_file (SSL_CTX * ctx)
Definition at line 4287 of file ssl_lib.c.
References CTLOG_STORE_load_default_file().
Referenced by ctx_set_ctlog_list_file().
SSL_CTX_set_default_passwd_cb()
void SSL_CTX_set_default_passwd_cb (SSL_CTX * ctx, pem_password_cb * cb)
Definition at line 2682 of file ssl_lib.c.
References cb.
SSL_CTX_set_default_passwd_cb_userdata()
void SSL_CTX_set_default_passwd_cb_userdata (SSL_CTX * ctx, void * u)
Definition at line 2687 of file ssl_lib.c.
References u.
SSL_CTX_set_default_read_buffer_len()
void SSL_CTX_set_default_read_buffer_len (SSL_CTX * ctx, size_t len)
Definition at line 135 of file rec_layer_s3.c.
References len.
SSL_CTX_set_default_verify_dir()
__owur int SSL_CTX_set_default_verify_dir (SSL_CTX * ctx)
Definition at line 3473 of file ssl_lib.c.
Referenced by ctx_set_verify_locations().
SSL_CTX_set_default_verify_file()
__owur int SSL_CTX_set_default_verify_file (SSL_CTX * ctx)
Definition at line 3488 of file ssl_lib.c.
Referenced by ctx_set_verify_locations().
SSL_CTX_set_default_verify_paths()
__owur int SSL_CTX_set_default_verify_paths (SSL_CTX * ctx)
Definition at line 3468 of file ssl_lib.c.
References X509_STORE_set_default_paths().
SSL_CTX_set_ex_data()
__owur int SSL_CTX_set_ex_data (SSL_CTX * ssl, int idx, void * data)
Definition at line 3577 of file ssl_lib.c.
SSL_CTX_set_generate_session_id()
__owur int SSL_CTX_set_generate_session_id (SSL_CTX * , GEN_SESSION_CB)
Definition at line 722 of file ssl_lib.c.
References cb, CRYPTO_THREAD_unlock(), and CRYPTO_THREAD_write_lock().
SSL_CTX_set_info_callback()
void SSL_CTX_set_info_callback (SSL_CTX * ctx, void(*)(const SSL *ssl, int type, int val) cb)
Definition at line 1126 of file ssl_sess.c.
References cb.
SSL_CTX_set_keylog_callback()
void SSL_CTX_set_keylog_callback (SSL_CTX * ctx, SSL_CTX_keylog_cb_func cb)
Definition at line 4310 of file ssl_lib.c.
References cb.
SSL_CTX_set_msg_callback()
void SSL_CTX_set_msg_callback (SSL_CTX * ctx, void(*)(int write_p, int version, int content_type, const void *buf, size_t len, SSL *ssl, void *arg) cb)
Definition at line 3707 of file ssl_lib.c.
SSL_CTX_set_next_proto_select_cb()
void SSL_CTX_set_next_proto_select_cb (SSL_CTX * s, SSL_CTX_npn_select_cb_func cb, void * arg)
SSL_CTX_set_next_protos_advertised_cb()
void SSL_CTX_set_next_protos_advertised_cb (SSL_CTX * s, SSL_CTX_npn_advertised_cb_func cb, void * arg)
SSL_CTX_set_not_resumable_session_callback()
void SSL_CTX_set_not_resumable_session_callback (SSL_CTX * ctx, int(*)(SSL *ssl, int is_forward_secure) cb)
Definition at line 3723 of file ssl_lib.c.
References cb, SSL_CTRL_SET_NOT_RESUMABLE_SESS_CB, and SSL_CTX_callback_ctrl().
SSL_CTX_set_options()
unsigned long SSL_CTX_set_options (SSL_CTX * ctx, unsigned long op)
Definition at line 3900 of file ssl_lib.c.
SSL_CTX_set_psk_client_callback()
void SSL_CTX_set_psk_client_callback (SSL_CTX * ctx, SSL_psk_client_cb_func cb)
Definition at line 3691 of file ssl_lib.c.
References cb.
SSL_CTX_set_psk_server_callback()
void SSL_CTX_set_psk_server_callback (SSL_CTX * ctx, SSL_psk_server_cb_func cb)
Definition at line 3701 of file ssl_lib.c.
References cb.
Referenced by main().
SSL_CTX_set_purpose()
__owur int SSL_CTX_set_purpose (SSL_CTX * s, int purpose)
Definition at line 763 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_purpose().
SSL_CTX_set_quiet_shutdown()
void SSL_CTX_set_quiet_shutdown (SSL_CTX * ctx, int mode)
Definition at line 3383 of file ssl_lib.c.
SSL_CTX_set_security_callback()
void SSL_CTX_set_security_callback (SSL_CTX * ctx, int(*)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex) cb)
Definition at line 3858 of file ssl_lib.c.
References cb.
SSL_CTX_set_security_level()
void SSL_CTX_set_security_level (SSL_CTX * ctx, int level)
Definition at line 3848 of file ssl_lib.c.
SSL_CTX_set_session_id_context()
__owur int SSL_CTX_set_session_id_context (SSL_CTX * ctx, const unsigned char * sid_ctx, unsigned int sid_ctx_len)
Definition at line 694 of file ssl_lib.c.
References SSL_F_SSL_CTX_SET_SESSION_ID_CONTEXT, SSL_R_SSL_SESSION_ID_CONTEXT_TOO_LONG, and SSLerr.
SSL_CTX_set_srp_cb_arg()
int SSL_CTX_set_srp_cb_arg (SSL_CTX * ctx, void * arg)
Definition at line 450 of file tls_srp.c.
SSL_CTX_set_srp_client_pwd_callback()
int SSL_CTX_set_srp_client_pwd_callback (SSL_CTX * ctx, char *(*)(SSL *, void *) cb)
Definition at line 462 of file tls_srp.c.
References cb, SSL_CTRL_SET_SRP_GIVE_CLIENT_PWD_CB, and tls1_ctx_callback_ctrl.
SSL_CTX_set_srp_password()
int SSL_CTX_set_srp_password (SSL_CTX * ctx, char * password)
Definition at line 432 of file tls_srp.c.
References SSL_CTRL_SET_TLS_EXT_SRP_PASSWORD, and tls1_ctx_ctrl.
SSL_CTX_set_srp_strength()
int SSL_CTX_set_srp_strength (SSL_CTX * ctx, int strength)
Definition at line 437 of file tls_srp.c.
References NULL, SSL_CTRL_SET_TLS_EXT_SRP_STRENGTH, and tls1_ctx_ctrl.
SSL_CTX_set_srp_username()
int SSL_CTX_set_srp_username (SSL_CTX * ctx, char * name)
Definition at line 427 of file tls_srp.c.
References SSL_CTRL_SET_TLS_EXT_SRP_USERNAME, and tls1_ctx_ctrl.
SSL_CTX_set_srp_username_callback()
int SSL_CTX_set_srp_username_callback (SSL_CTX * ctx, int(*)(SSL *, int *, void *) cb)
Definition at line 455 of file tls_srp.c.
References cb, SSL_CTRL_SET_TLS_EXT_SRP_USERNAME_CB, and tls1_ctx_callback_ctrl.
SSL_CTX_set_srp_verify_param_callback()
int SSL_CTX_set_srp_verify_param_callback (SSL_CTX * ctx, int(*)(SSL *, void *) cb)
Definition at line 443 of file tls_srp.c.
References cb, SSL_CTRL_SET_SRP_VERIFY_PARAM_CB, and tls1_ctx_callback_ctrl.
SSL_CTX_set_ssl_version()
__owur int SSL_CTX_set_ssl_version (SSL_CTX * ctx, const SSL_METHOD * meth)
Used to change an SSL_CTXs default SSL method type
Definition at line 505 of file ssl_lib.c.
References NULL, SSL_DEFAULT_CIPHER_LIST, SSL_F_SSL_CTX_SET_SSL_VERSION, SSL_R_SSL_LIBRARY_HAS_NO_CIPHERS, SSLerr, and STACK_OF().
SSL_CTX_set_timeout()
__owur long SSL_CTX_set_timeout (SSL_CTX * ctx, long t)
Definition at line 924 of file ssl_sess.c.
References NULL, and t.
SSL_CTX_set_tmp_dh_callback()
void SSL_CTX_set_tmp_dh_callback (SSL_CTX * ctx, DH *(*)(SSL *ssl, int is_export, int keylength) dh)
Set the callback for generating temporary DH keys.
Parameters
ctx the SSL context.
dh the callback
Definition at line 3622 of file ssl_lib.c.
References SSL_CTRL_SET_TMP_DH_CB, and SSL_CTX_callback_ctrl().
SSL_CTX_set_trust()
__owur int SSL_CTX_set_trust (SSL_CTX * s, int trust)
Definition at line 773 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_trust().
SSL_CTX_set_verify()
void SSL_CTX_set_verify (SSL_CTX * ctx, int mode, SSL_verify_cb callback)
SSL_CTX_set_verify_depth()
void SSL_CTX_set_verify_depth (SSL_CTX * ctx, int depth)
Definition at line 2737 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_depth().
SSL_CTX_SRP_CTX_free()
int SSL_CTX_SRP_CTX_free (SSL_CTX * ctx)
SSL_CTX_SRP_CTX_init()
__owur int SSL_CTX_SRP_CTX_init (SSL_CTX * ctx)
SSL_CTX_up_ref()
int SSL_CTX_up_ref (SSL_CTX * ctx)
Definition at line 2609 of file ssl_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by SSL_new(), and SSL_set_SSL_CTX().
SSL_CTX_use_certificate()
__owur int SSL_CTX_use_certificate (SSL_CTX * ctx, X509 * x)
Definition at line 296 of file ssl_rsa.c.
References ERR_R_PASSED_NULL_PARAMETER, NULL, SSL_F_SSL_CTX_USE_CERTIFICATE, ssl_security_cert(), and SSLerr.
SSL_CTX_use_certificate_ASN1()
__owur int SSL_CTX_use_certificate_ASN1 (SSL_CTX * ctx, int len, const unsigned char * d)
Definition at line 413 of file ssl_rsa.c.
SSL_CTX_use_certificate_chain_file()
__owur int SSL_CTX_use_certificate_chain_file (SSL_CTX * ctx, const char * file)
Definition at line 682 of file ssl_rsa.c.
SSL_CTX_use_certificate_file()
__owur int SSL_CTX_use_certificate_file (SSL_CTX * ctx, const char * file, int type)
Definition at line 372 of file ssl_rsa.c.
References in.
Referenced by create_ssl_ctx_pair(), and set_cert_stuff().
SSL_CTX_use_PrivateKey()
__owur int SSL_CTX_use_PrivateKey (SSL_CTX * ctx, EVP_PKEY * pkey)
Definition at line 514 of file ssl_rsa.c.
References ERR_R_PASSED_NULL_PARAMETER, NULL, SSL_F_SSL_CTX_USE_PRIVATEKEY, and SSLerr.
SSL_CTX_use_PrivateKey_ASN1()
__owur int SSL_CTX_use_PrivateKey_ASN1 (int pk, SSL_CTX * ctx, const unsigned char * d, long len)
Definition at line 562 of file ssl_rsa.c.
SSL_CTX_use_PrivateKey_file()
__owur int SSL_CTX_use_PrivateKey_file (SSL_CTX * ctx, const char * file, int type)
Definition at line 523 of file ssl_rsa.c.
Referenced by create_ssl_ctx_pair(), and set_cert_stuff().
SSL_CTX_use_psk_identity_hint()
__owur int SSL_CTX_use_psk_identity_hint (SSL_CTX * ctx, const char * identity_hint)
Definition at line 3637 of file ssl_lib.c.
References NULL, OPENSSL_free, OPENSSL_strdup, PSK_MAX_IDENTITY_LEN, SSL_F_SSL_CTX_USE_PSK_IDENTITY_HINT, SSL_R_DATA_LENGTH_TOO_LONG, and SSLerr.
SSL_CTX_use_RSAPrivateKey()
__owur int SSL_CTX_use_RSAPrivateKey (SSL_CTX * ctx, RSA * rsa)
Definition at line 430 of file ssl_rsa.c.
SSL_CTX_use_RSAPrivateKey_ASN1()
__owur int SSL_CTX_use_RSAPrivateKey_ASN1 (SSL_CTX * ctx, const unsigned char * d, long len)
Definition at line 495 of file ssl_rsa.c.
SSL_CTX_use_RSAPrivateKey_file()
__owur int SSL_CTX_use_RSAPrivateKey_file (SSL_CTX * ctx, const char * file, int type)
Definition at line 456 of file ssl_rsa.c.
SSL_CTX_use_serverinfo()
__owur int SSL_CTX_use_serverinfo (SSL_CTX * ctx, const unsigned char * serverinfo, size_t serverinfo_length)
Definition at line 841 of file ssl_rsa.c.
References ERR_R_PASSED_NULL_PARAMETER, NULL, SSL_F_SSL_CTX_USE_SERVERINFO, and SSLerr.
SSL_CTX_use_serverinfo_file()
__owur int SSL_CTX_use_serverinfo_file (SSL_CTX * ctx, const char * file)
Definition at line 879 of file ssl_rsa.c.
References NULL.
SSL_dane_clear_flags()
unsigned long SSL_dane_clear_flags (SSL * ssl, unsigned long flags)
Definition at line 875 of file ssl_lib.c.
SSL_dane_enable()
__owur int SSL_dane_enable (SSL * s, const char * basedomain)
Definition at line 824 of file ssl_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, SSL_F_SSL_DANE_ENABLE, SSL_R_CONTEXT_NOT_DANE_ENABLED, SSL_R_DANE_ALREADY_ENABLED, SSL_R_ERROR_SETTING_TLSA_BASE_DOMAIN, SSL_set_tlsext_host_name, SSLerr, and X509_VERIFY_PARAM_set1_host().
SSL_dane_set_flags()
unsigned long SSL_dane_set_flags (SSL * ssl, unsigned long flags)
Definition at line 867 of file ssl_lib.c.
References flags.
SSL_dane_tlsa_add()
__owur int SSL_dane_tlsa_add (SSL * s, uint8_t usage, uint8_t selector, uint8_t mtype, unsigned char * data, size_t dlen)
Definition at line 925 of file ssl_lib.c.
SSL_do_handshake()
__owur int SSL_do_handshake (SSL * s)
Definition at line 3043 of file ssl_lib.c.
Referenced by SSL_accept(), and SSL_connect().
SSL_dup()
__owur SSL* SSL_dup (SSL * ssl)
Definition at line 3148 of file ssl_lib.c.
References STACK_OF().
SSL_enable_ct()
int SSL_enable_ct (SSL * s, int validation_mode)
Definition at line 4274 of file ssl_lib.c.
References SSL_CT_VALIDATION_PERMISSIVE, SSL_F_SSL_ENABLE_CT, SSL_R_INVALID_CT_VALIDATION_TYPE, SSL_set_ct_validation_callback(), and SSLerr.
SSL_extension_supported()
__owur int SSL_extension_supported (unsigned int ext_type)
Definition at line 235 of file t1_ext.c.
References TLSEXT_TYPE_application_layer_protocol_negotiation, TLSEXT_TYPE_ec_point_formats, TLSEXT_TYPE_encrypt_then_mac, TLSEXT_TYPE_extended_master_secret, TLSEXT_TYPE_key_share, TLSEXT_TYPE_next_proto_neg, TLSEXT_TYPE_padding, TLSEXT_TYPE_renegotiate, TLSEXT_TYPE_server_name, TLSEXT_TYPE_session_ticket, TLSEXT_TYPE_signature_algorithms, TLSEXT_TYPE_signed_certificate_timestamp, TLSEXT_TYPE_srp, TLSEXT_TYPE_status_request, TLSEXT_TYPE_supported_groups, TLSEXT_TYPE_supported_versions, and TLSEXT_TYPE_use_srtp.
SSL_free()
void SSL_free (SSL * ssl)
Definition at line 962 of file ssl_lib.c.
References CRYPTO_DOWN_REF, NULL, REF_ASSERT_ISNT, REF_PRINT_COUNT, and X509_VERIFY_PARAM_free().
Referenced by create_ssl_objects(), and SSL_new().
SSL_get0_alpn_selected()
void SSL_get0_alpn_selected (const SSL * ssl, const unsigned char ** data, unsigned int * len)
Definition at line 2398 of file ssl_lib.c.
References NULL.
SSL_get0_dane()
SSL_DANE* SSL_get0_dane (SSL * ssl)
Definition at line 920 of file ssl_lib.c.
SSL_get0_dane_authority()
__owur int SSL_get0_dane_authority (SSL * s, X509 ** mcert, EVP_PKEY ** mspki)
Definition at line 883 of file ssl_lib.c.
References DANETLS_ENABLED, NULL, and X509_V_OK.
SSL_get0_dane_tlsa()
__owur int SSL_get0_dane_tlsa (SSL * s, uint8_t * usage, uint8_t * selector, uint8_t * mtype, unsigned const char ** data, size_t * dlen)
Definition at line 898 of file ssl_lib.c.
References DANETLS_ENABLED, and X509_V_OK.
SSL_get0_next_proto_negotiated()
void SSL_get0_next_proto_negotiated (const SSL * s, const unsigned char ** data, unsigned * len)
Definition at line 2293 of file ssl_lib.c.
SSL_get0_param()
__owur X509_VERIFY_PARAM* SSL_get0_param (SSL * ssl)
Definition at line 952 of file ssl_lib.c.
SSL_get0_peername()
__owur const char* SSL_get0_peername (SSL * s)
Definition at line 798 of file ssl_lib.c.
References X509_VERIFY_PARAM_get0_peername().
SSL_get0_security_ex_data()
__owur void* SSL_get0_security_ex_data (const SSL * s)
Definition at line 3843 of file ssl_lib.c.
SSL_get1_session()
__owur SSL_SESSION* SSL_get1_session (SSL * ssl)
Definition at line 63 of file ssl_sess.c.
References CRYPTO_THREAD_read_lock(), CRYPTO_THREAD_unlock(), and SSL_SESSION_up_ref().
SSL_get_certificate()
__owur X509* SSL_get_certificate (const SSL * ssl)
Definition at line 3293 of file ssl_lib.c.
References NULL.
SSL_get_cipher_list()
__owur const char* SSL_get_cipher_list (const SSL * s, int n)
The old interface to get the same thing as SSL_get_ciphers()
Definition at line 2103 of file ssl_lib.c.
SSL_get_client_random()
__owur size_t SSL_get_client_random (const SSL * ssl, unsigned char * out, size_t outlen)
Definition at line 3536 of file ssl_lib.c.
SSL_get_current_cipher()
__owur const SSL_CIPHER* SSL_get_current_cipher (const SSL * s)
Definition at line 3325 of file ssl_lib.c.
References NULL.
Referenced by DTLS_get_data_mtu().
SSL_get_current_compression()
__owur const COMP_METHOD* SSL_get_current_compression (SSL * s)
Definition at line 3332 of file ssl_lib.c.
References COMP_CTX_get_method(), and NULL.
SSL_get_current_expansion()
__owur const COMP_METHOD* SSL_get_current_expansion (SSL * s)
Definition at line 3341 of file ssl_lib.c.
References COMP_CTX_get_method(), and NULL.
SSL_get_default_passwd_cb()
pem_password_cb* SSL_get_default_passwd_cb (SSL * s)
Definition at line 2712 of file ssl_lib.c.
SSL_get_default_passwd_cb_userdata()
void* SSL_get_default_passwd_cb_userdata (SSL * s)
Definition at line 2717 of file ssl_lib.c.
SSL_get_default_timeout()
__owur long SSL_get_default_timeout (const SSL * s)
Definition at line 1475 of file ssl_lib.c.
SSL_get_error()
__owur int SSL_get_error (const SSL * s, int ret_code)
Definition at line 2946 of file ssl_lib.c.
References BIO_get_retry_reason(), BIO_RR_ACCEPT, BIO_RR_CONNECT, BIO_should_io_special, BIO_should_read, BIO_should_write, ERR_GET_LIB, ERR_LIB_SYS, ERR_peek_error(), SSL_AD_CLOSE_NOTIFY, SSL_ERROR_NONE, SSL_ERROR_SSL, SSL_ERROR_SYSCALL, SSL_ERROR_WANT_ACCEPT, SSL_ERROR_WANT_ASYNC, SSL_ERROR_WANT_ASYNC_JOB, SSL_ERROR_WANT_CONNECT, SSL_ERROR_WANT_READ, SSL_ERROR_WANT_WRITE, SSL_ERROR_WANT_X509_LOOKUP, SSL_ERROR_ZERO_RETURN, SSL_get_rbio(), SSL_RECEIVED_SHUTDOWN, SSL_want_async, SSL_want_async_job, SSL_want_read, SSL_want_write, and SSL_want_x509_lookup.
SSL_get_ex_data()
void* SSL_get_ex_data (const SSL * ssl, int idx)
Definition at line 3572 of file ssl_lib.c.
SSL_get_ex_data_X509_STORE_CTX_idx()
__owur int SSL_get_ex_data_X509_STORE_CTX_idx (void)
Definition at line 49 of file ssl_cert.c.
References RUN_ONCE.
Referenced by ssl_verify_cert_chain().
SSL_get_fd()
__owur int SSL_get_fd (const SSL * s)
Definition at line 1123 of file ssl_lib.c.
References SSL_get_rfd().
SSL_get_finished()
size_t SSL_get_finished (const SSL * s, void * buf, size_t count)
Definition at line 1216 of file ssl_lib.c.
SSL_get_key_update_type()
int SSL_get_key_update_type (SSL * s)
Definition at line 1749 of file ssl_lib.c.
SSL_get_options()
unsigned long SSL_get_options (const SSL * s)
Definition at line 3895 of file ssl_lib.c.
Referenced by dtls1_check_timeout_num(), dtls1_query_mtu(), and tls_construct_stoc_cryptopro_bug().
SSL_get_peer_finished()
size_t SSL_get_peer_finished (const SSL * s, void * buf, size_t count)
Definition at line 1230 of file ssl_lib.c.
SSL_get_privatekey()
struct evp_pkey_st* SSL_get_privatekey (const SSL * ssl)
Definition at line 3301 of file ssl_lib.c.
References NULL.
SSL_get_psk_identity()
const char* SSL_get_psk_identity (const SSL * s)
Definition at line 3679 of file ssl_lib.c.
References NULL.
SSL_get_psk_identity_hint()
const char* SSL_get_psk_identity_hint (const SSL * s)
Definition at line 3672 of file ssl_lib.c.
References NULL.
SSL_get_quiet_shutdown()
__owur int SSL_get_quiet_shutdown (const SSL * ssl)
Definition at line 3398 of file ssl_lib.c.
SSL_get_rbio()
__owur BIO* SSL_get_rbio (const SSL * s)
Definition at line 1106 of file ssl_lib.c.
Referenced by dtls1_buffer_record(), dtls1_get_record(), dtls1_process_buffered_records(), dtls1_read_failed(), dtls1_stop_timer(), ossl_statem_client_post_process_message(), ossl_statem_server_post_process_message(), SSL_get_error(), SSL_set_bio(), SSL_set_wfd(), and tls_post_process_client_key_exchange().
SSL_get_read_ahead()
__owur int SSL_get_read_ahead (const SSL * s)
Definition at line 1289 of file ssl_lib.c.
References RECORD_LAYER_get_read_ahead.
SSL_get_rfd()
__owur int SSL_get_rfd (const SSL * s)
Definition at line 1128 of file ssl_lib.c.
Referenced by SSL_get_fd().
SSL_get_security_level()
__owur int SSL_get_security_level (const SSL * s)
Definition at line 3818 of file ssl_lib.c.
Referenced by ssl_verify_cert_chain().
SSL_get_server_random()
__owur size_t SSL_get_server_random (const SSL * ssl, unsigned char * out, size_t outlen)
Definition at line 3546 of file ssl_lib.c.
SSL_get_session()
__owur SSL_SESSION* SSL_get_session (const SSL * ssl)
Definition at line 57 of file ssl_sess.c.
Referenced by SSL_copy_session_id().
SSL_get_shared_ciphers()
__owur char* SSL_get_shared_ciphers (const SSL * s, char * buf, int len)
Definition at line 2168 of file ssl_lib.c.
References STACK_OF().
SSL_get_shutdown()
__owur int SSL_get_shutdown (const SSL * ssl)
Definition at line 3408 of file ssl_lib.c.
SSL_get_srp_g()
__owur BIGNUM* SSL_get_srp_g (SSL * s)
Definition at line 396 of file tls_srp.c.
References NULL.
SSL_get_srp_N()
__owur BIGNUM* SSL_get_srp_N (SSL * s)
Definition at line 403 of file tls_srp.c.
References NULL.
SSL_get_srp_userinfo()
__owur char* SSL_get_srp_userinfo (SSL * s)
Definition at line 417 of file tls_srp.c.
References NULL.
SSL_get_srp_username()
__owur char* SSL_get_srp_username (SSL * s)
Definition at line 410 of file tls_srp.c.
References NULL.
SSL_get_SSL_CTX()
__owur SSL_CTX* SSL_get_SSL_CTX (const SSL * ssl)
Definition at line 3423 of file ssl_lib.c.
SSL_get_ssl_method()
__owur const SSL_METHOD* SSL_get_ssl_method (SSL * s)
Definition at line 2917 of file ssl_lib.c.
SSL_get_state()
__owur OSSL_HANDSHAKE_STATE SSL_get_state (const SSL * ssl)
Definition at line 64 of file statem.c.
Referenced by dtls1_buffer_record(), SSL_state_string(), and SSL_state_string_long().
SSL_get_verify_callback()
__owur SSL_verify_cb SSL_get_verify_callback (const SSL * s)
SSL_get_verify_depth()
__owur int SSL_get_verify_depth (const SSL * s)
Definition at line 1248 of file ssl_lib.c.
References X509_VERIFY_PARAM_get_depth().
SSL_get_verify_mode()
__owur int SSL_get_verify_mode (const SSL * s)
Definition at line 1243 of file ssl_lib.c.
SSL_get_verify_result()
__owur long SSL_get_verify_result (const SSL * ssl)
Definition at line 3531 of file ssl_lib.c.
SSL_get_version()
__owur const char* SSL_get_version (const SSL * s)
Definition at line 3143 of file ssl_lib.c.
References ssl_protocol_to_string().
SSL_get_wbio()
__owur BIO* SSL_get_wbio (const SSL * s)
Definition at line 1111 of file ssl_lib.c.
References BIO_next(), and NULL.
Referenced by dtls1_check_timeout_num(), dtls1_query_mtu(), dtls1_start_timer(), dtls1_write_app_data_bytes(), ossl_statem_client_post_work(), ossl_statem_client_pre_work(), ossl_statem_server_post_process_message(), ossl_statem_server_post_work(), ossl_statem_server_pre_work(), SSL_set_bio(), SSL_set_rfd(), tls_client_key_exchange_post_work(), tls_finish_handshake(), and tls_post_process_client_key_exchange().
SSL_get_wfd()
__owur int SSL_get_wfd (const SSL * s)
Definition at line 1140 of file ssl_lib.c.
SSL_has_matching_session_id()
__owur int SSL_has_matching_session_id (const SSL * ssl, const unsigned char * id, unsigned int id_len)
Definition at line 738 of file ssl_lib.c.
References CRYPTO_THREAD_read_lock(), CRYPTO_THREAD_unlock(), and NULL.
SSL_has_pending()
__owur int SSL_has_pending (const SSL * s)
Definition at line 1311 of file ssl_lib.c.
References RECORD_LAYER_read_pending(), and SSL_pending().
SSL_in_before()
int SSL_in_before (SSL * s)
Definition at line 79 of file statem.c.
References MSG_FLOW_UNINITED, and TLS_ST_BEFORE.
Referenced by ssl_clear_bad_session().
SSL_in_init()
int SSL_in_init (SSL * s)
Definition at line 69 of file statem.c.
Referenced by dtls1_get_record(), dtls1_read_failed(), dtls1_write_app_data_bytes(), ssl_clear_bad_session(), SSL_ctrl(), and SSL_shutdown().
SSL_is_dtls()
int SSL_is_dtls (const SSL * s)
Definition at line 677 of file ssl_lib.c.
References SSL_IS_DTLS.
Referenced by create_ssl_objects().
SSL_is_init_finished()
int SSL_is_init_finished (SSL * s)
Definition at line 74 of file statem.c.
References TLS_ST_OK.
Referenced by SSL_key_update().
SSL_is_server()
__owur int SSL_is_server (SSL * s)
Definition at line 3799 of file ssl_lib.c.
Referenced by ssl_print_sigalgs().
SSL_key_update()
int SSL_key_update (SSL * s, int updatetype)
Definition at line 1721 of file ssl_lib.c.
References ossl_statem_set_in_init(), SSL_F_SSL_KEY_UPDATE, SSL_is_init_finished(), SSL_IS_TLS13, SSL_KEY_UPDATE_NOT_REQUESTED, SSL_KEY_UPDATE_REQUESTED, SSL_R_INVALID_KEY_UPDATE_TYPE, SSL_R_STILL_IN_INIT, SSL_R_WRONG_SSL_VERSION, and SSLerr.
SSL_new()
SSL* SSL_new (SSL_CTX * ctx)
Definition at line 521 of file ssl_lib.c.
References CRYPTO_EX_INDEX_SSL, CRYPTO_new_ex_data(), CRYPTO_THREAD_lock_new(), ctx, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_assert, OPENSSL_free, OPENSSL_malloc, OPENSSL_memdup, OPENSSL_zalloc, RECORD_LAYER_init(), RECORD_LAYER_set_read_ahead, ssl_async_args::s, ssl_cert_dup(), SSL_clear(), SSL_CTX_up_ref(), SSL_F_SSL_NEW, SSL_free(), SSL_KEY_UPDATE_NONE, SSL_R_NULL_SSL_CTX, SSL_R_SSL_CTX_HAS_NO_DEFAULT_SSL_VERSION, SSL_set_ct_validation_callback(), SSL_set_default_read_buffer_len(), ssl_undefined_function(), SSLerr, X509_V_OK, X509_VERIFY_PARAM_inherit(), and X509_VERIFY_PARAM_new().
Referenced by create_ssl_objects().
SSL_peek()
__owur int SSL_peek (SSL * ssl, void * buf, int num)
Definition at line 1586 of file ssl_lib.c.
SSL_peek_ex()
__owur int SSL_peek_ex (SSL * ssl, void * buf, size_t num, size_t * readbytes)
Definition at line 1608 of file ssl_lib.c.
References ASYNC_get_current_job(), NULL, SSL_F_SSL_PEEK_EX, SSL_MODE_ASYNC, SSL_R_UNINITIALIZED, SSL_RECEIVED_SHUTDOWN, and SSLerr.
SSL_pending()
__owur int SSL_pending (const SSL * s)
Definition at line 1294 of file ssl_lib.c.
Referenced by SSL_has_pending().
SSL_read()
__owur int SSL_read (SSL * ssl, void * buf, int num)
Definition at line 1534 of file ssl_lib.c.
SSL_read_ex()
__owur int SSL_read_ex (SSL * ssl, void * buf, size_t num, size_t * readbytes)
Definition at line 1556 of file ssl_lib.c.
References ASYNC_get_current_job(), NULL, SSL_F_SSL_READ_EX, SSL_MODE_ASYNC, SSL_NOTHING, SSL_R_UNINITIALIZED, SSL_RECEIVED_SHUTDOWN, and SSLerr.
SSL_renegotiate()
int SSL_renegotiate (SSL * s)
Definition at line 1754 of file ssl_lib.c.
References SSL_F_SSL_RENEGOTIATE, SSL_IS_TLS13, SSL_R_WRONG_SSL_VERSION, and SSLerr.
SSL_renegotiate_abbreviated()
int SSL_renegotiate_abbreviated (SSL * s)
Definition at line 1769 of file ssl_lib.c.
References SSL_IS_TLS13.
SSL_renegotiate_pending()
__owur int SSL_renegotiate_pending (SSL * s)
Definition at line 1782 of file ssl_lib.c.
SSL_rstate_string()
__owur const char* SSL_rstate_string (const SSL * s)
Definition at line 159 of file rec_layer_s3.c.
References SSL_ST_READ_BODY, SSL_ST_READ_DONE, and SSL_ST_READ_HEADER.
SSL_rstate_string_long()
__owur const char* SSL_rstate_string_long (const SSL * s)
Definition at line 145 of file rec_layer_s3.c.
References SSL_ST_READ_BODY, SSL_ST_READ_DONE, and SSL_ST_READ_HEADER.
SSL_select_next_proto()
__owur int SSL_select_next_proto (unsigned char ** out, unsigned char * outlen, const unsigned char * in, unsigned int inlen, const unsigned char * client, unsigned int client_len)
Definition at line 2246 of file ssl_lib.c.
SSL_SESSION_free()
void SSL_SESSION_free (SSL_SESSION * ses)
Definition at line 758 of file ssl_sess.c.
References CRYPTO_DOWN_REF, CRYPTO_EX_INDEX_SSL_SESSION, CRYPTO_free_ex_data(), CRYPTO_THREAD_lock_free(), NULL, OPENSSL_cleanse(), OPENSSL_clear_free, OPENSSL_free, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by SSL_clear(), ssl_session_dup(), SSL_set_session(), and ssl_update_cache().
SSL_SESSION_get0_cipher()
__owur const SSL_CIPHER* SSL_SESSION_get0_cipher (const SSL_SESSION * s)
Definition at line 877 of file ssl_sess.c.
SSL_SESSION_get0_hostname()
__owur const char* SSL_SESSION_get0_hostname (const SSL_SESSION * s)
Definition at line 882 of file ssl_sess.c.
SSL_SESSION_get0_id_context()
const unsigned char* SSL_SESSION_get0_id_context (const SSL_SESSION * s, unsigned int * len)
Definition at line 255 of file ssl_sess.c.
References NULL.
SSL_SESSION_get0_peer()
__owur X509* SSL_SESSION_get0_peer (SSL_SESSION * s)
Definition at line 905 of file ssl_sess.c.
SSL_SESSION_get0_ticket()
void SSL_SESSION_get0_ticket (const SSL_SESSION * s, const unsigned char ** tick, size_t * len)
Definition at line 897 of file ssl_sess.c.
References NULL.
SSL_SESSION_get_compress_id()
__owur unsigned int SSL_SESSION_get_compress_id (const SSL_SESSION * s)
Definition at line 263 of file ssl_sess.c.
SSL_SESSION_get_ex_data()
void* SSL_SESSION_get_ex_data (const SSL_SESSION * ss, int idx)
Definition at line 85 of file ssl_sess.c.
SSL_SESSION_get_id()
const unsigned char* SSL_SESSION_get_id (const SSL_SESSION * s, unsigned int * len)
Definition at line 249 of file ssl_sess.c.
SSL_SESSION_get_master_key()
__owur size_t SSL_SESSION_get_master_key (const SSL_SESSION * ssl, unsigned char * out, size_t outlen)
Definition at line 3556 of file ssl_lib.c.
SSL_SESSION_get_protocol_version()
__owur int SSL_SESSION_get_protocol_version (const SSL_SESSION * s)
Definition at line 872 of file ssl_sess.c.
SSL_SESSION_get_ticket_lifetime_hint()
__owur unsigned long SSL_SESSION_get_ticket_lifetime_hint (const SSL_SESSION * s)
Definition at line 892 of file ssl_sess.c.
SSL_SESSION_get_time()
__owur long SSL_SESSION_get_time (const SSL_SESSION * s)
Definition at line 857 of file ssl_sess.c.
References NULL.
SSL_SESSION_get_timeout()
__owur long SSL_SESSION_get_timeout (const SSL_SESSION * s)
Definition at line 850 of file ssl_sess.c.
References NULL.
SSL_SESSION_has_ticket()
__owur int SSL_SESSION_has_ticket (const SSL_SESSION * s)
Definition at line 887 of file ssl_sess.c.
SSL_SESSION_new()
__owur SSL_SESSION* SSL_SESSION_new (void)
Definition at line 90 of file ssl_sess.c.
References CRYPTO_EX_INDEX_SSL_SESSION, CRYPTO_new_ex_data(), CRYPTO_THREAD_lock_free(), CRYPTO_THREAD_lock_new(), ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_INIT_LOAD_SSL_STRINGS, OPENSSL_init_ssl(), OPENSSL_zalloc, SSL_F_SSL_SESSION_NEW, and SSLerr.
SSL_SESSION_print()
int SSL_SESSION_print (BIO * fp, const SSL_SESSION * ses)
Definition at line 58 of file ssl_txt.c.
References BIO_dump_indent(), BIO_printf(), BIO_puts(), NULL, ssl_cipher_get_evp(), ssl_protocol_to_string(), SSL_SESS_FLAG_EXTMS, and X509_verify_cert_error_string().
SSL_SESSION_print_fp()
int SSL_SESSION_print_fp (FILE * fp, const SSL_SESSION * ses)
Definition at line 42 of file ssl_txt.c.
SSL_SESSION_print_keylog()
int SSL_SESSION_print_keylog (BIO * bp, const SSL_SESSION * x)
Definition at line 183 of file ssl_txt.c.
References BIO_printf(), BIO_puts(), and NULL.
SSL_session_reused()
__owur int SSL_session_reused (SSL * s)
Definition at line 3794 of file ssl_lib.c.
SSL_SESSION_set1_id()
__owur int SSL_SESSION_set1_id (SSL_SESSION * s, const unsigned char * sid, unsigned int sid_len)
Definition at line 829 of file ssl_sess.c.
References SSL_F_SSL_SESSION_SET1_ID, SSL_MAX_SSL_SESSION_ID_LENGTH, SSL_R_SSL_SESSION_ID_TOO_LONG, and SSLerr.
SSL_SESSION_set1_id_context()
__owur int SSL_SESSION_set1_id_context (SSL_SESSION * s, const unsigned char * sid_ctx, unsigned int sid_ctx_len)
Definition at line 910 of file ssl_sess.c.
References SSL_F_SSL_SESSION_SET1_ID_CONTEXT, SSL_MAX_SID_CTX_LENGTH, SSL_R_SSL_SESSION_ID_CONTEXT_TOO_LONG, and SSLerr.
SSL_SESSION_set_ex_data()
__owur int SSL_SESSION_set_ex_data (SSL_SESSION * ss, int idx, void * data)
Definition at line 80 of file ssl_sess.c.
SSL_SESSION_set_time()
__owur long SSL_SESSION_set_time (SSL_SESSION * s, long t)
Definition at line 864 of file ssl_sess.c.
References NULL, and t.
SSL_SESSION_set_timeout()
__owur long SSL_SESSION_set_timeout (SSL_SESSION * s, long t)
Definition at line 842 of file ssl_sess.c.
References NULL, and t.
SSL_SESSION_up_ref()
int SSL_SESSION_up_ref (SSL_SESSION * ses)
Definition at line 799 of file ssl_sess.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by SSL_get1_session(), SSL_set_session(), and ssl_update_cache().
SSL_set0_rbio()
void SSL_set0_rbio (SSL * s, BIO * rbio)
Definition at line 1044 of file ssl_lib.c.
References BIO_free_all().
Referenced by SSL_set_bio(), and SSL_set_rfd().
SSL_set0_security_ex_data()
void SSL_set0_security_ex_data (SSL * s, void * ex)
Definition at line 3838 of file ssl_lib.c.
References ex.
SSL_set0_wbio()
void SSL_set0_wbio (SSL * s, BIO * wbio)
Definition at line 1050 of file ssl_lib.c.
References BIO_free_all(), BIO_pop(), BIO_push(), and NULL.
Referenced by SSL_set_bio(), and SSL_set_wfd().
SSL_set1_host()
__owur int SSL_set1_host (SSL * s, const char * hostname)
Definition at line 783 of file ssl_lib.c.
References X509_VERIFY_PARAM_set1_host().
SSL_set1_param()
__owur int SSL_set1_param (SSL * ssl, X509_VERIFY_PARAM * vpm)
Definition at line 942 of file ssl_lib.c.
References X509_VERIFY_PARAM_set1().
SSL_set_accept_state()
void SSL_set_accept_state (SSL * s)
Definition at line 3068 of file ssl_lib.c.
References ossl_statem_clear().
Referenced by SSL_accept().
SSL_set_alpn_protos()
__owur int SSL_set_alpn_protos (SSL * ssl, const unsigned char * protos, unsigned int protos_len)
Definition at line 2365 of file ssl_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_memdup, SSL_F_SSL_SET_ALPN_PROTOS, and SSLerr.
SSL_set_bio()
void SSL_set_bio (SSL * s, BIO * rbio, BIO * wbio)
Definition at line 1066 of file ssl_lib.c.
References BIO_up_ref(), NULL, SSL_get_rbio(), SSL_get_wbio(), SSL_set0_rbio(), and SSL_set0_wbio().
Referenced by create_ssl_objects().
SSL_set_cert_cb()
void SSL_set_cert_cb (SSL * s, int(*)(SSL *ssl, void *arg) cb, void * arg)
Definition at line 2747 of file ssl_lib.c.
SSL_set_cipher_list()
__owur int SSL_set_cipher_list (SSL * s, const char * str)
specify the ciphers to be used by the SSL
Definition at line 2152 of file ssl_lib.c.
References NULL, SSL_F_SSL_SET_CIPHER_LIST, SSL_R_NO_CIPHER_MATCH, SSLerr, and STACK_OF().
SSL_set_client_CA_list()
void SSL_set_client_CA_list (SSL * s, STACK_OF(X509_NAME) * name_list)
Definition at line 492 of file ssl_cert.c.
SSL_set_connect_state()
void SSL_set_connect_state (SSL * s)
Definition at line 3077 of file ssl_lib.c.
References ossl_statem_clear().
Referenced by SSL_connect().
SSL_set_ct_validation_callback()
int SSL_set_ct_validation_callback (SSL * s, ssl_ct_validation_cb callback, void * arg)
Definition at line 4106 of file ssl_lib.c.
Referenced by SSL_enable_ct(), and SSL_new().
SSL_set_default_passwd_cb()
void SSL_set_default_passwd_cb (SSL * s, pem_password_cb * cb)
Definition at line 2702 of file ssl_lib.c.
References cb.
SSL_set_default_passwd_cb_userdata()
void SSL_set_default_passwd_cb_userdata (SSL * s, void * u)
Definition at line 2707 of file ssl_lib.c.
References u.
SSL_set_default_read_buffer_len()
void SSL_set_default_read_buffer_len (SSL * s, size_t len)
Definition at line 140 of file rec_layer_s3.c.
References RECORD_LAYER_get_rbuf, and SSL3_BUFFER_set_default_len.
Referenced by SSL_new().
SSL_set_ex_data()
__owur int SSL_set_ex_data (SSL * ssl, int idx, void * data)
Definition at line 3567 of file ssl_lib.c.
SSL_set_fd()
__owur int SSL_set_fd (SSL * s, int fd)
Definition at line 1153 of file ssl_lib.c.
SSL_set_generate_session_id()
__owur int SSL_set_generate_session_id (SSL * , GEN_SESSION_CB)
Definition at line 730 of file ssl_lib.c.
References cb, CRYPTO_THREAD_unlock(), and CRYPTO_THREAD_write_lock().
SSL_set_hostflags()
void SSL_set_hostflags (SSL * s, unsigned int flags)
Definition at line 793 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_hostflags().
SSL_set_info_callback()
void SSL_set_info_callback (SSL * ssl, void(*)(const SSL *ssl, int type, int val) cb)
Definition at line 3510 of file ssl_lib.c.
References cb.
SSL_set_msg_callback()
void SSL_set_msg_callback (SSL * ssl, void(*)(int write_p, int version, int content_type, const void *buf, size_t len, SSL *ssl, void *arg) cb)
Definition at line 3715 of file ssl_lib.c.
SSL_set_not_resumable_session_callback()
void SSL_set_not_resumable_session_callback (SSL * ssl, int(*)(SSL *ssl, int is_forward_secure) cb)
Definition at line 3732 of file ssl_lib.c.
References cb, SSL_callback_ctrl(), and SSL_CTRL_SET_NOT_RESUMABLE_SESS_CB.
SSL_set_options()
unsigned long SSL_set_options (SSL * s, unsigned long op)
Definition at line 3905 of file ssl_lib.c.
SSL_set_psk_client_callback()
void SSL_set_psk_client_callback (SSL * ssl, SSL_psk_client_cb_func cb)
Definition at line 3686 of file ssl_lib.c.
References cb.
SSL_set_psk_server_callback()
void SSL_set_psk_server_callback (SSL * ssl, SSL_psk_server_cb_func cb)
Definition at line 3696 of file ssl_lib.c.
References cb.
SSL_set_purpose()
__owur int SSL_set_purpose (SSL * s, int purpose)
Definition at line 768 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_purpose().
SSL_set_quiet_shutdown()
void SSL_set_quiet_shutdown (SSL * ssl, int mode)
Definition at line 3393 of file ssl_lib.c.
SSL_set_read_ahead()
void SSL_set_read_ahead (SSL * s, int yes)
Definition at line 1284 of file ssl_lib.c.
References RECORD_LAYER_set_read_ahead.
SSL_set_rfd()
__owur int SSL_set_rfd (SSL * s, int fd)
Definition at line 1192 of file ssl_lib.c.
References BIO_get_fd, BIO_method_type(), BIO_new(), BIO_NOCLOSE, BIO_s_socket(), BIO_set_fd, BIO_TYPE_SOCKET, BIO_up_ref(), ERR_R_BUF_LIB, NULL, SSL_F_SSL_SET_RFD, SSL_get_wbio(), SSL_set0_rbio(), and SSLerr.
SSL_set_security_callback()
void SSL_set_security_callback (SSL * s, int(*)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex) cb)
Definition at line 3823 of file ssl_lib.c.
References cb.
SSL_set_security_level()
void SSL_set_security_level (SSL * s, int level)
Definition at line 3813 of file ssl_lib.c.
SSL_set_session()
__owur int SSL_set_session (SSL * to, SSL_SESSION * session)
Definition at line 811 of file ssl_sess.c.
References NULL, ssl_clear_bad_session(), SSL_SESSION_free(), SSL_SESSION_up_ref(), and SSL_set_ssl_method().
Referenced by SSL_copy_session_id().
SSL_set_session_id_context()
__owur int SSL_set_session_id_context (SSL * ssl, const unsigned char * sid_ctx, unsigned int sid_ctx_len)
Definition at line 708 of file ssl_lib.c.
References SSL_F_SSL_SET_SESSION_ID_CONTEXT, SSL_MAX_SID_CTX_LENGTH, SSL_R_SSL_SESSION_ID_CONTEXT_TOO_LONG, and SSLerr.
Referenced by SSL_copy_session_id().
SSL_set_session_secret_cb()
__owur int SSL_set_session_secret_cb (SSL * s, tls_session_secret_cb_fn tls_session_secret_cb, void * arg)
Definition at line 941 of file ssl_sess.c.
SSL_set_session_ticket_ext()
__owur int SSL_set_session_ticket_ext (SSL * s, void * ext_data, int ext_len)
Definition at line 962 of file ssl_sess.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, OPENSSL_malloc, SSL_F_SSL_SET_SESSION_TICKET_EXT, SSLerr, and TLS1_VERSION.
SSL_set_session_ticket_ext_cb()
__owur int SSL_set_session_ticket_ext_cb (SSL * s, tls_session_ticket_ext_cb_fn cb, void * arg)
Definition at line 952 of file ssl_sess.c.
SSL_set_shutdown()
void SSL_set_shutdown (SSL * ssl, int mode)
Definition at line 3403 of file ssl_lib.c.
SSL_set_srp_server_param()
int SSL_set_srp_server_param (SSL * s, const BIGNUM * N, const BIGNUM * g, BIGNUM * sa, BIGNUM * v, char * info)
Definition at line 236 of file tls_srp.c.
References BN_copy(), BN_dup(), BN_free(), and NULL.
SSL_set_srp_server_param_pw()
int SSL_set_srp_server_param_pw (SSL * s, const char * user, const char * pass, const char * grp)
Definition at line 217 of file tls_srp.c.
References BN_clear_free(), BN_dup(), SRP_gN::g, SRP_gN::N, NULL, SRP_create_verifier_BN(), and SRP_get_default_gN().
SSL_set_SSL_CTX()
SSL_CTX* SSL_set_SSL_CTX (SSL * ssl, SSL_CTX * ctx)
Definition at line 3428 of file ssl_lib.c.
References ctx, NULL, OPENSSL_assert, ssl_cert_dup(), ssl_cert_free(), SSL_CTX_free(), and SSL_CTX_up_ref().
SSL_set_ssl_method()
__owur int SSL_set_ssl_method (SSL * s, const SSL_METHOD * method)
Definition at line 2922 of file ssl_lib.c.
Referenced by SSL_set_session().
SSL_set_tmp_dh_callback()
void SSL_set_tmp_dh_callback (SSL * ssl, DH *(*)(SSL *ssl, int is_export, int keylength) dh)
Definition at line 3629 of file ssl_lib.c.
References SSL_callback_ctrl(), and SSL_CTRL_SET_TMP_DH_CB.
SSL_set_trust()
__owur int SSL_set_trust (SSL * s, int trust)
Definition at line 778 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_trust().
SSL_set_verify()
void SSL_set_verify (SSL * s, int mode, SSL_verify_cb callback)
SSL_set_verify_depth()
void SSL_set_verify_depth (SSL * s, int depth)
Definition at line 1279 of file ssl_lib.c.
References X509_VERIFY_PARAM_set_depth().
SSL_set_verify_result()
void SSL_set_verify_result (SSL * ssl, long v)
Definition at line 3526 of file ssl_lib.c.
SSL_set_wfd()
__owur int SSL_set_wfd (SSL * s, int fd)
Definition at line 1171 of file ssl_lib.c.
References BIO_get_fd, BIO_method_type(), BIO_new(), BIO_NOCLOSE, BIO_s_socket(), BIO_set_fd, BIO_TYPE_SOCKET, BIO_up_ref(), ERR_R_BUF_LIB, NULL, SSL_F_SSL_SET_WFD, SSL_get_rbio(), SSL_set0_wbio(), and SSLerr.
SSL_shutdown()
int SSL_shutdown (SSL * s)
Definition at line 1689 of file ssl_lib.c.
References ASYNC_get_current_job(), ssl_async_args::f, ssl_async_args::func_other, NULL, ssl_async_args::OTHERFUNC, ssl_async_args::s, SSL_F_SSL_SHUTDOWN, SSL_in_init(), SSL_MODE_ASYNC, SSL_R_UNINITIALIZED, SSLerr, and ssl_async_args::type.
Referenced by BIO_ssl_shutdown().
SSL_SRP_CTX_free()
int SSL_SRP_CTX_free (SSL * ctx)
Referenced by ssl3_free().
SSL_SRP_CTX_init()
__owur int SSL_SRP_CTX_init (SSL * s)
Referenced by ssl3_new().
SSL_srp_server_param_with_username()
__owur int SSL_srp_server_param_with_username (SSL * s, int * ad)
Definition at line 181 of file tls_srp.c.
References BN_bin2bn(), NULL, OPENSSL_cleanse(), RAND_bytes(), SRP_Calc_B(), SSL3_AL_FATAL, SSL_AD_INTERNAL_ERROR, SSL_AD_UNKNOWN_PSK_IDENTITY, SSL_ERROR_NONE, and SSL_MAX_MASTER_KEY_LENGTH.
SSL_state_string()
__owur const char* SSL_state_string (const SSL * s)
Definition at line 121 of file ssl_stat.c.
References DTLS_ST_CR_HELLO_VERIFY_REQUEST, DTLS_ST_SW_HELLO_VERIFY_REQUEST, ossl_statem_in_error(), SSL_get_state(), TLS_ST_BEFORE, TLS_ST_CR_CERT, TLS_ST_CR_CERT_REQ, TLS_ST_CR_CERT_STATUS, TLS_ST_CR_CHANGE, TLS_ST_CR_FINISHED, TLS_ST_CR_KEY_EXCH, TLS_ST_CR_SESSION_TICKET, TLS_ST_CR_SRVR_DONE, TLS_ST_CR_SRVR_HELLO, TLS_ST_CW_CERT, TLS_ST_CW_CERT_VRFY, TLS_ST_CW_CHANGE, TLS_ST_CW_CLNT_HELLO, TLS_ST_CW_FINISHED, TLS_ST_CW_KEY_EXCH, TLS_ST_CW_NEXT_PROTO, TLS_ST_OK, TLS_ST_SR_CERT, TLS_ST_SR_CERT_VRFY, TLS_ST_SR_CHANGE, TLS_ST_SR_CLNT_HELLO, TLS_ST_SR_FINISHED, TLS_ST_SR_KEY_EXCH, TLS_ST_SR_NEXT_PROTO, TLS_ST_SW_CERT, TLS_ST_SW_CERT_REQ, TLS_ST_SW_CERT_STATUS, TLS_ST_SW_CHANGE, TLS_ST_SW_FINISHED, TLS_ST_SW_HELLO_REQ, TLS_ST_SW_KEY_EXCH, TLS_ST_SW_SESSION_TICKET, TLS_ST_SW_SRVR_DONE, and TLS_ST_SW_SRVR_HELLO.
SSL_state_string_long()
__owur const char* SSL_state_string_long (const SSL * s)
Definition at line 40 of file ssl_stat.c.
References DTLS_ST_CR_HELLO_VERIFY_REQUEST, DTLS_ST_SW_HELLO_VERIFY_REQUEST, ossl_statem_in_error(), SSL_get_state(), TLS_ST_BEFORE, TLS_ST_CR_CERT, TLS_ST_CR_CERT_REQ, TLS_ST_CR_CERT_STATUS, TLS_ST_CR_CHANGE, TLS_ST_CR_FINISHED, TLS_ST_CR_KEY_EXCH, TLS_ST_CR_SESSION_TICKET, TLS_ST_CR_SRVR_DONE, TLS_ST_CR_SRVR_HELLO, TLS_ST_CW_CERT, TLS_ST_CW_CERT_VRFY, TLS_ST_CW_CHANGE, TLS_ST_CW_CLNT_HELLO, TLS_ST_CW_FINISHED, TLS_ST_CW_KEY_EXCH, TLS_ST_CW_NEXT_PROTO, TLS_ST_OK, TLS_ST_SR_CERT, TLS_ST_SR_CERT_VRFY, TLS_ST_SR_CHANGE, TLS_ST_SR_CLNT_HELLO, TLS_ST_SR_FINISHED, TLS_ST_SR_KEY_EXCH, TLS_ST_SR_NEXT_PROTO, TLS_ST_SW_CERT, TLS_ST_SW_CERT_REQ, TLS_ST_SW_CERT_STATUS, TLS_ST_SW_CHANGE, TLS_ST_SW_FINISHED, TLS_ST_SW_HELLO_REQ, TLS_ST_SW_KEY_EXCH, TLS_ST_SW_SESSION_TICKET, TLS_ST_SW_SRVR_DONE, and TLS_ST_SW_SRVR_HELLO.
SSL_test_functions()
__owur const struct openssl_ssl_test_functions* SSL_test_functions (void)
Definition at line 19 of file ssl_utst.c.
SSL_trace()
void SSL_trace (int write_p, int version, int content_type, const void * buf, size_t len, SSL * ssl, void * arg)
Definition at line 1383 of file t1_trce.c.
SSL_up_ref()
int SSL_up_ref (SSL * s)
Definition at line 682 of file ssl_lib.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
SSL_use_certificate()
__owur int SSL_use_certificate (SSL * ssl, X509 * x)
Definition at line 20 of file ssl_rsa.c.
References ERR_R_PASSED_NULL_PARAMETER, NULL, SSL_F_SSL_USE_CERTIFICATE, ssl_security_cert(), and SSLerr.
SSL_use_certificate_ASN1()
__owur int SSL_use_certificate_ASN1 (SSL * ssl, const unsigned char * d, int len)
Definition at line 77 of file ssl_rsa.c.
SSL_use_certificate_chain_file()
__owur int SSL_use_certificate_chain_file (SSL * ssl, const char * file)
Definition at line 687 of file ssl_rsa.c.
SSL_use_certificate_file()
__owur int SSL_use_certificate_file (SSL * ssl, const char * file, int type)
Definition at line 36 of file ssl_rsa.c.
References in.
SSL_use_PrivateKey()
__owur int SSL_use_PrivateKey (SSL * ssl, EVP_PKEY * pkey)
Definition at line 226 of file ssl_rsa.c.
SSL_use_PrivateKey_ASN1()
__owur int SSL_use_PrivateKey_ASN1 (int pk, SSL * ssl, const unsigned char * d, long len)
Definition at line 278 of file ssl_rsa.c.
SSL_use_PrivateKey_file()
__owur int SSL_use_PrivateKey_file (SSL * ssl, const char * file, int type)
Definition at line 238 of file ssl_rsa.c.
SSL_use_psk_identity_hint()
__owur int SSL_use_psk_identity_hint (SSL * s, const char * identity_hint)
Definition at line 3653 of file ssl_lib.c.
References NULL, OPENSSL_free, OPENSSL_strdup, PSK_MAX_IDENTITY_LEN, SSL_F_SSL_USE_PSK_IDENTITY_HINT, SSL_R_DATA_LENGTH_TOO_LONG, and SSLerr.
SSL_use_RSAPrivateKey()
__owur int SSL_use_RSAPrivateKey (SSL * ssl, RSA * rsa)
Definition at line 94 of file ssl_rsa.c.
SSL_use_RSAPrivateKey_ASN1()
__owur int SSL_use_RSAPrivateKey_ASN1 (SSL * ssl, const unsigned char * d, long len)
Definition at line 208 of file ssl_rsa.c.
SSL_use_RSAPrivateKey_file()
__owur int SSL_use_RSAPrivateKey_file (SSL * ssl, const char * file, int type)
Definition at line 168 of file ssl_rsa.c.
SSL_version()
__owur int SSL_version (const SSL * ssl)
Definition at line 3413 of file ssl_lib.c.
SSL_want()
__owur int SSL_want (const SSL * s)
Definition at line 3610 of file ssl_lib.c.
SSL_write()
__owur int SSL_write (SSL * ssl, const void * buf, int num)
Definition at line 1636 of file ssl_lib.c.
SSL_write_ex()
__owur int SSL_write_ex (SSL * s, const void * buf, size_t num, size_t * written)
Definition at line 1658 of file ssl_lib.c.
References ASYNC_get_current_job(), NULL, SSL_F_SSL_WRITE_EX, SSL_MODE_ASYNC, SSL_NOTHING, SSL_R_PROTOCOL_IS_SHUTDOWN, SSL_R_UNINITIALIZED, SSL_SENT_SHUTDOWN, and SSLerr.
STACK_OF() [1/5]
STACK_OF (SSL_CIPHER)
return a STACK of the ciphers available for the SSL and in order of preference
return a STACK of the ciphers available for the SSL and in order of algorithm id
return a STACK of the ciphers available for the SSL_CTX and in order of preference
Definition at line 1297 of file ssl_ciph.c.
References NULL, ssl_set_client_disabled(), and STACK_OF().
Referenced by ssl3_comp_find(), and ssl_comp_free_compression_methods_int().
STACK_OF() [2/5]
STACK_OF (SSL_COMP)
STACK_OF() [3/5]
__owur STACK_OF (X509_NAME) const
STACK_OF() [4/5]
__owur STACK_OF (X509) const
STACK_OF() [5/5]
const STACK_OF (SCT)
Definition at line 257 of file ct_oct.c.
References CT_F_O2I_SCT_LIST, CT_R_SCT_LIST_INVALID, CTerr, MAX_SCT_LIST_SIZE, n2s, NULL, o2i_SCT(), SCT_free(), SCT_LIST_free(), and STACK_OF().
Referenced by i2o_SCT_LIST(), and STACK_OF().
TLS_client_method()
__owur const SSL_METHOD* TLS_client_method (void)
Referenced by process_responder().
TLS_server_method()
__owur const SSL_METHOD* TLS_server_method (void)
Variable Documentation
SSL_CTX_get_client_cert_cb
int(*)(SSL *ssl, X509 **x509, EVP_PKEY **pkey) SSL_CTX_get_client_cert_cb(SSL_CTX *ctx)
Definition at line 642 of file ssl.h.
SSL_CTX_get_info_callback
void(*)(const SSL *ssl, int type, int val) SSL_CTX_get_info_callback(SSL_CTX *ctx)
Definition at line 637 of file ssl.h.
SSL_CTX_get_security_callback
int(*)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex) SSL_CTX_get_security_callback(const SSL_CTX *ctx)
Definition at line 2053 of file ssl.h.
SSL_CTX_sess_get_get_cb
SSL_SESSION*(*)(struct ssl_st *ssl, const unsigned char *data, int len, int *copy) SSL_CTX_sess_get_get_cb(SSL_CTX *ctx)
Definition at line 631 of file ssl.h.
SSL_CTX_sess_get_new_cb
int(*)(struct ssl_st *ssl, SSL_SESSION *sess) SSL_CTX_sess_get_new_cb(SSL_CTX *ctx)
Definition at line 616 of file ssl.h.
SSL_CTX_sess_get_remove_cb
void(*)(struct ssl_ctx_st *ctx, SSL_SESSION *sess) SSL_CTX_sess_get_remove_cb(SSL_CTX *ctx)
Definition at line 623 of file ssl.h.
SSL_get_info_callback
void(*)(const SSL *ssl, int type, int val) SSL_get_info_callback(const SSL *ssl)
Definition at line 1727 of file ssl.h.
SSL_get_security_callback
int(*)(const SSL *s, const SSL_CTX *ctx, int op, int bits, int nid, void *other, void *ex) SSL_get_security_callback(const SSL *s)
Definition at line 2041 of file ssl.h.
SSL_version_str
const char SSL_version_str[]
Definition at line 55 of file ssl_lib.c.