ssl/ssl_init.c File Reference
ssl_init.c File Reference
#include "e_os.h"
#include "internal/err.h"
#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <assert.h>
#include "ssl_locl.h"
#include "internal/thread_once.h"
Functions
DEFINE_RUN_ONCE_STATIC (ossl_init_ssl_base)
DEFINE_RUN_ONCE_STATIC (ossl_init_load_ssl_strings)
DEFINE_RUN_ONCE_STATIC (ossl_init_no_load_ssl_strings)
int OPENSSL_init_ssl (uint64_t opts, const OPENSSL_INIT_SETTINGS *settings)
Function Documentation
DEFINE_RUN_ONCE_STATIC() [1/3]
DEFINE_RUN_ONCE_STATIC (ossl_init_ssl_base)
Definition at line 25 of file ssl_init.c.
References EVP_add_cipher(), EVP_add_digest(), EVP_add_digest_alias, EVP_aes_128_cbc(), EVP_aes_128_cbc_hmac_sha1(), EVP_aes_128_cbc_hmac_sha256(), EVP_aes_128_ccm(), EVP_aes_128_gcm(), EVP_aes_192_cbc(), EVP_aes_256_cbc(), EVP_aes_256_cbc_hmac_sha1(), EVP_aes_256_cbc_hmac_sha256(), EVP_aes_256_ccm(), EVP_aes_256_gcm(), EVP_camellia_128_cbc(), EVP_camellia_256_cbc(), EVP_chacha20_poly1305(), EVP_des_cbc(), EVP_des_ede3_cbc(), EVP_idea_cbc(), EVP_md5(), EVP_md5_sha1(), EVP_rc2_40_cbc(), EVP_rc2_cbc(), EVP_rc4(), EVP_rc4_hmac_md5(), EVP_seed_cbc(), EVP_sha1(), EVP_sha224(), EVP_sha256(), EVP_sha384(), EVP_sha512(), OPENSSL_atexit(), SN_md5, SN_sha1, SN_sha1WithRSA, SN_sha1WithRSAEncryption, SSL_add_ssl_module(), and ssl_load_ciphers().
DEFINE_RUN_ONCE_STATIC() [2/3]
DEFINE_RUN_ONCE_STATIC (ossl_init_load_ssl_strings)
Definition at line 117 of file ssl_init.c.
References ERR_load_SSL_strings().
DEFINE_RUN_ONCE_STATIC() [3/3]
DEFINE_RUN_ONCE_STATIC (ossl_init_no_load_ssl_strings)
Definition at line 134 of file ssl_init.c.
OPENSSL_init_ssl()
int OPENSSL_init_ssl (uint64_t opts, const OPENSSL_INIT_SETTINGS * settings)
Definition at line 177 of file ssl_init.c.
Referenced by SSL_SESSION_new().