ssl/ssl_stat.c File Reference
ssl_stat.c File Reference
#include <stdio.h>
#include "ssl_locl.h"
Functions
const char * SSL_state_string_long (const SSL *s)
const char * SSL_state_string (const SSL *s)
const char * SSL_alert_type_string_long (int value)
const char * SSL_alert_type_string (int value)
const char * SSL_alert_desc_string (int value)
const char * SSL_alert_desc_string_long (int value)
Function Documentation
SSL_alert_desc_string()
const char* SSL_alert_desc_string (int value)
Definition at line 226 of file ssl_stat.c.
References SSL3_AD_BAD_CERTIFICATE, SSL3_AD_BAD_RECORD_MAC, SSL3_AD_CERTIFICATE_EXPIRED, SSL3_AD_CERTIFICATE_REVOKED, SSL3_AD_CERTIFICATE_UNKNOWN, SSL3_AD_CLOSE_NOTIFY, SSL3_AD_DECOMPRESSION_FAILURE, SSL3_AD_HANDSHAKE_FAILURE, SSL3_AD_ILLEGAL_PARAMETER, SSL3_AD_NO_CERTIFICATE, SSL3_AD_UNEXPECTED_MESSAGE, SSL3_AD_UNSUPPORTED_CERTIFICATE, TLS1_AD_ACCESS_DENIED, TLS1_AD_BAD_CERTIFICATE_HASH_VALUE, TLS1_AD_BAD_CERTIFICATE_STATUS_RESPONSE, TLS1_AD_CERTIFICATE_UNOBTAINABLE, TLS1_AD_DECODE_ERROR, TLS1_AD_DECRYPT_ERROR, TLS1_AD_DECRYPTION_FAILED, TLS1_AD_EXPORT_RESTRICTION, TLS1_AD_INSUFFICIENT_SECURITY, TLS1_AD_INTERNAL_ERROR, TLS1_AD_NO_RENEGOTIATION, TLS1_AD_PROTOCOL_VERSION, TLS1_AD_RECORD_OVERFLOW, TLS1_AD_UNKNOWN_CA, TLS1_AD_UNKNOWN_PSK_IDENTITY, TLS1_AD_UNRECOGNIZED_NAME, TLS1_AD_UNSUPPORTED_EXTENSION, and TLS1_AD_USER_CANCELLED.
SSL_alert_desc_string_long()
const char* SSL_alert_desc_string_long (int value)
Definition at line 294 of file ssl_stat.c.
References SSL3_AD_BAD_CERTIFICATE, SSL3_AD_BAD_RECORD_MAC, SSL3_AD_CERTIFICATE_EXPIRED, SSL3_AD_CERTIFICATE_REVOKED, SSL3_AD_CERTIFICATE_UNKNOWN, SSL3_AD_CLOSE_NOTIFY, SSL3_AD_DECOMPRESSION_FAILURE, SSL3_AD_HANDSHAKE_FAILURE, SSL3_AD_ILLEGAL_PARAMETER, SSL3_AD_NO_CERTIFICATE, SSL3_AD_UNEXPECTED_MESSAGE, SSL3_AD_UNSUPPORTED_CERTIFICATE, TLS1_AD_ACCESS_DENIED, TLS1_AD_BAD_CERTIFICATE_HASH_VALUE, TLS1_AD_BAD_CERTIFICATE_STATUS_RESPONSE, TLS1_AD_CERTIFICATE_UNOBTAINABLE, TLS1_AD_DECODE_ERROR, TLS1_AD_DECRYPT_ERROR, TLS1_AD_DECRYPTION_FAILED, TLS1_AD_EXPORT_RESTRICTION, TLS1_AD_INSUFFICIENT_SECURITY, TLS1_AD_INTERNAL_ERROR, TLS1_AD_NO_APPLICATION_PROTOCOL, TLS1_AD_NO_RENEGOTIATION, TLS1_AD_PROTOCOL_VERSION, TLS1_AD_RECORD_OVERFLOW, TLS1_AD_UNKNOWN_CA, TLS1_AD_UNKNOWN_PSK_IDENTITY, TLS1_AD_UNRECOGNIZED_NAME, TLS1_AD_UNSUPPORTED_EXTENSION, and TLS1_AD_USER_CANCELLED.
SSL_alert_type_string()
const char* SSL_alert_type_string (int value)
Definition at line 214 of file ssl_stat.c.
References SSL3_AL_FATAL, and SSL3_AL_WARNING.
SSL_alert_type_string_long()
const char* SSL_alert_type_string_long (int value)
Definition at line 202 of file ssl_stat.c.
References SSL3_AL_FATAL, and SSL3_AL_WARNING.
SSL_state_string()
const char* SSL_state_string (const SSL * s)
Definition at line 121 of file ssl_stat.c.
References DTLS_ST_CR_HELLO_VERIFY_REQUEST, DTLS_ST_SW_HELLO_VERIFY_REQUEST, ossl_statem_in_error(), SSL_get_state(), TLS_ST_BEFORE, TLS_ST_CR_CERT, TLS_ST_CR_CERT_REQ, TLS_ST_CR_CERT_STATUS, TLS_ST_CR_CHANGE, TLS_ST_CR_FINISHED, TLS_ST_CR_KEY_EXCH, TLS_ST_CR_SESSION_TICKET, TLS_ST_CR_SRVR_DONE, TLS_ST_CR_SRVR_HELLO, TLS_ST_CW_CERT, TLS_ST_CW_CERT_VRFY, TLS_ST_CW_CHANGE, TLS_ST_CW_CLNT_HELLO, TLS_ST_CW_FINISHED, TLS_ST_CW_KEY_EXCH, TLS_ST_CW_NEXT_PROTO, TLS_ST_OK, TLS_ST_SR_CERT, TLS_ST_SR_CERT_VRFY, TLS_ST_SR_CHANGE, TLS_ST_SR_CLNT_HELLO, TLS_ST_SR_FINISHED, TLS_ST_SR_KEY_EXCH, TLS_ST_SR_NEXT_PROTO, TLS_ST_SW_CERT, TLS_ST_SW_CERT_REQ, TLS_ST_SW_CERT_STATUS, TLS_ST_SW_CHANGE, TLS_ST_SW_FINISHED, TLS_ST_SW_HELLO_REQ, TLS_ST_SW_KEY_EXCH, TLS_ST_SW_SESSION_TICKET, TLS_ST_SW_SRVR_DONE, and TLS_ST_SW_SRVR_HELLO.
SSL_state_string_long()
const char* SSL_state_string_long (const SSL * s)
Definition at line 40 of file ssl_stat.c.
References DTLS_ST_CR_HELLO_VERIFY_REQUEST, DTLS_ST_SW_HELLO_VERIFY_REQUEST, ossl_statem_in_error(), SSL_get_state(), TLS_ST_BEFORE, TLS_ST_CR_CERT, TLS_ST_CR_CERT_REQ, TLS_ST_CR_CERT_STATUS, TLS_ST_CR_CHANGE, TLS_ST_CR_FINISHED, TLS_ST_CR_KEY_EXCH, TLS_ST_CR_SESSION_TICKET, TLS_ST_CR_SRVR_DONE, TLS_ST_CR_SRVR_HELLO, TLS_ST_CW_CERT, TLS_ST_CW_CERT_VRFY, TLS_ST_CW_CHANGE, TLS_ST_CW_CLNT_HELLO, TLS_ST_CW_FINISHED, TLS_ST_CW_KEY_EXCH, TLS_ST_CW_NEXT_PROTO, TLS_ST_OK, TLS_ST_SR_CERT, TLS_ST_SR_CERT_VRFY, TLS_ST_SR_CHANGE, TLS_ST_SR_CLNT_HELLO, TLS_ST_SR_FINISHED, TLS_ST_SR_KEY_EXCH, TLS_ST_SR_NEXT_PROTO, TLS_ST_SW_CERT, TLS_ST_SW_CERT_REQ, TLS_ST_SW_CERT_STATUS, TLS_ST_SW_CHANGE, TLS_ST_SW_FINISHED, TLS_ST_SW_HELLO_REQ, TLS_ST_SW_KEY_EXCH, TLS_ST_SW_SESSION_TICKET, TLS_ST_SW_SRVR_DONE, and TLS_ST_SW_SRVR_HELLO.