ssl/ssl_err.c File Reference
ssl_err.c File Reference
#include <stdio.h>
#include <openssl/err.h>
#include <openssl/ssl.h>
Macros
#define ERR_FUNC(func) ERR_PACK(ERR_LIB_SSL,func,0)
#define ERR_REASON(reason) ERR_PACK(ERR_LIB_SSL,0,reason)
Functions
int ERR_load_SSL_strings (void)
Macro Definition Documentation
ERR_FUNC
#define ERR_FUNC (func) ERR_PACK(ERR_LIB_SSL,func,0)
Definition at line 18 of file ssl_err.c.
ERR_REASON
#define ERR_REASON (reason) ERR_PACK(ERR_LIB_SSL,0,reason)
Definition at line 19 of file ssl_err.c.
Function Documentation
ERR_load_SSL_strings()
int ERR_load_SSL_strings (void)
Definition at line 821 of file ssl_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by DEFINE_RUN_ONCE_STATIC().