test/ssltestlib.c File Reference
ssltestlib.c File Reference
#include <string.h>
#include "ssltestlib.h"
Data Structures
struct MEMPACKET
struct MEMPACKET_TEST_CTX
Macros
#define BIO_TYPE_TLS_DUMP_FILTER (0x80 | BIO_TYPE_FILTER)
#define BIO_TYPE_MEMPACKET_TEST 0x81
#define RECORD_CONTENT_TYPE 0
#define RECORD_VERSION_HI 1
#define RECORD_VERSION_LO 2
#define RECORD_EPOCH_HI 3
#define RECORD_EPOCH_LO 4
#define RECORD_SEQUENCE_START 5
#define RECORD_SEQUENCE_END 10
#define RECORD_LEN_HI 11
#define RECORD_LEN_LO 12
#define MSG_TYPE 0
#define MSG_LEN_HI 1
#define MSG_LEN_MID 2
#define MSG_LEN_LO 3
#define MSG_SEQ_HI 4
#define MSG_SEQ_LO 5
#define MSG_FRAG_OFF_HI 6
#define MSG_FRAG_OFF_MID 7
#define MSG_FRAG_OFF_LO 8
#define MSG_FRAG_LEN_HI 9
#define MSG_FRAG_LEN_MID 10
#define MSG_FRAG_LEN_LO 11
#define EPOCH_HI 4
#define EPOCH_LO 5
#define RECORD_SEQUENCE 10
#define RECORD_LEN_HI 11
#define RECORD_LEN_LO 12
#define STANDARD_PACKET 0
#define MAXLOOPS 1000000
Functions
const BIO_METHOD * bio_f_tls_dump_filter (void)
void bio_f_tls_dump_filter_free (void)
const BIO_METHOD * bio_s_mempacket_test (void)
void bio_s_mempacket_test_free (void)
int mempacket_test_inject (BIO *bio, const char *in, int inl, int pktnum, int type)
int create_ssl_ctx_pair (const SSL_METHOD *sm, const SSL_METHOD *cm, SSL_CTX **sctx, SSL_CTX **cctx, char *certfile, char *privkeyfile)
int create_ssl_objects (SSL_CTX *serverctx, SSL_CTX *clientctx, SSL **sssl, SSL **cssl, BIO *s_to_c_fbio, BIO *c_to_s_fbio)
int create_ssl_connection (SSL *serverssl, SSL *clientssl)
Macro Definition Documentation
BIO_TYPE_MEMPACKET_TEST
#define BIO_TYPE_MEMPACKET_TEST 0x81
Definition at line 25 of file ssltestlib.c.
BIO_TYPE_TLS_DUMP_FILTER
#define BIO_TYPE_TLS_DUMP_FILTER (0x80 | BIO_TYPE_FILTER)
Definition at line 23 of file ssltestlib.c.
EPOCH_HI
#define EPOCH_HI 4
Definition at line 316 of file ssltestlib.c.
EPOCH_LO
#define EPOCH_LO 5
Definition at line 317 of file ssltestlib.c.
MAXLOOPS
#define MAXLOOPS 1000000
Definition at line 567 of file ssltestlib.c.
MSG_FRAG_LEN_HI
#define MSG_FRAG_LEN_HI 9
Definition at line 96 of file ssltestlib.c.
MSG_FRAG_LEN_LO
#define MSG_FRAG_LEN_LO 11
Definition at line 98 of file ssltestlib.c.
MSG_FRAG_LEN_MID
#define MSG_FRAG_LEN_MID 10
Definition at line 97 of file ssltestlib.c.
MSG_FRAG_OFF_HI
#define MSG_FRAG_OFF_HI 6
Definition at line 93 of file ssltestlib.c.
MSG_FRAG_OFF_LO
#define MSG_FRAG_OFF_LO 8
Definition at line 95 of file ssltestlib.c.
MSG_FRAG_OFF_MID
#define MSG_FRAG_OFF_MID 7
Definition at line 94 of file ssltestlib.c.
MSG_LEN_HI
#define MSG_LEN_HI 1
Definition at line 88 of file ssltestlib.c.
MSG_LEN_LO
#define MSG_LEN_LO 3
Definition at line 90 of file ssltestlib.c.
MSG_LEN_MID
#define MSG_LEN_MID 2
Definition at line 89 of file ssltestlib.c.
MSG_SEQ_HI
#define MSG_SEQ_HI 4
Definition at line 91 of file ssltestlib.c.
MSG_SEQ_LO
#define MSG_SEQ_LO 5
Definition at line 92 of file ssltestlib.c.
MSG_TYPE
#define MSG_TYPE 0
Definition at line 87 of file ssltestlib.c.
RECORD_CONTENT_TYPE
#define RECORD_CONTENT_TYPE 0
Definition at line 77 of file ssltestlib.c.
RECORD_EPOCH_HI
#define RECORD_EPOCH_HI 3
Definition at line 80 of file ssltestlib.c.
RECORD_EPOCH_LO
#define RECORD_EPOCH_LO 4
Definition at line 81 of file ssltestlib.c.
RECORD_LEN_HI [1/2]
#define RECORD_LEN_HI 11
Definition at line 319 of file ssltestlib.c.
RECORD_LEN_HI [2/2]
#define RECORD_LEN_HI 11
Definition at line 319 of file ssltestlib.c.
RECORD_LEN_LO [1/2]
#define RECORD_LEN_LO 12
Definition at line 320 of file ssltestlib.c.
RECORD_LEN_LO [2/2]
#define RECORD_LEN_LO 12
Definition at line 320 of file ssltestlib.c.
RECORD_SEQUENCE
#define RECORD_SEQUENCE 10
Definition at line 318 of file ssltestlib.c.
RECORD_SEQUENCE_END
#define RECORD_SEQUENCE_END 10
Definition at line 83 of file ssltestlib.c.
RECORD_SEQUENCE_START
#define RECORD_SEQUENCE_START 5
Definition at line 82 of file ssltestlib.c.
RECORD_VERSION_HI
#define RECORD_VERSION_HI 1
Definition at line 78 of file ssltestlib.c.
RECORD_VERSION_LO
#define RECORD_VERSION_LO 2
Definition at line 79 of file ssltestlib.c.
STANDARD_PACKET
#define STANDARD_PACKET 0
Definition at line 322 of file ssltestlib.c.
Function Documentation
bio_f_tls_dump_filter()
const BIO_METHOD* bio_f_tls_dump_filter (void)
Definition at line 31 of file ssltestlib.c.
bio_f_tls_dump_filter_free()
void bio_f_tls_dump_filter_free (void)
Definition at line 49 of file ssltestlib.c.
References BIO_meth_free().
bio_s_mempacket_test()
const BIO_METHOD* bio_s_mempacket_test (void)
Definition at line 265 of file ssltestlib.c.
Referenced by create_ssl_objects().
bio_s_mempacket_test_free()
void bio_s_mempacket_test_free (void)
Definition at line 283 of file ssltestlib.c.
References BIO_meth_free().
create_ssl_connection()
int create_ssl_connection (SSL * serverssl, SSL * clientssl)
Definition at line 644 of file ssltestlib.c.
create_ssl_ctx_pair()
int create_ssl_ctx_pair (const SSL_METHOD * sm, const SSL_METHOD * cm, SSL_CTX ** sctx, SSL_CTX ** cctx, char * certfile, char * privkeyfile)
Definition at line 525 of file ssltestlib.c.
References NULL, SSL_CTX_check_private_key(), SSL_CTX_free(), SSL_CTX_new(), SSL_CTX_set_dh_auto, SSL_CTX_use_certificate_file(), SSL_CTX_use_PrivateKey_file(), and SSL_FILETYPE_PEM.
create_ssl_objects()
int create_ssl_objects (SSL_CTX * serverctx, SSL_CTX * clientctx, SSL ** sssl, SSL ** cssl, BIO * s_to_c_fbio, BIO * c_to_s_fbio)
Definition at line 572 of file ssltestlib.c.
References BIO_free(), BIO_new(), BIO_push(), BIO_s_mem(), bio_s_mempacket_test(), BIO_set_mem_eof_return, BIO_up_ref(), NULL, SSL_free(), SSL_is_dtls(), SSL_new(), and SSL_set_bio().
mempacket_test_inject()
int mempacket_test_inject (BIO * bio, const char * in, int inl, int pktnum, int type)
Definition at line 388 of file ssltestlib.c.
References BIO_get_data(), ctx, NULL, and OPENSSL_malloc.