test/ssltestlib.h File Reference
ssltestlib.h File Reference
#include <openssl/ssl.h>
Macros
#define INJECT_PACKET 1
#define INJECT_PACKET_IGNORE_REC_SEQ 2
Functions
int create_ssl_ctx_pair (const SSL_METHOD *sm, const SSL_METHOD *cm, SSL_CTX **sctx, SSL_CTX **cctx, char *certfile, char *privkeyfile)
int create_ssl_objects (SSL_CTX *serverctx, SSL_CTX *clientctx, SSL **sssl, SSL **cssl, BIO *s_to_c_fbio, BIO *c_to_s_fbio)
int create_ssl_connection (SSL *serverssl, SSL *clientssl)
const BIO_METHOD * bio_f_tls_dump_filter (void)
void bio_f_tls_dump_filter_free (void)
const BIO_METHOD * bio_s_mempacket_test (void)
void bio_s_mempacket_test_free (void)
int mempacket_test_inject (BIO *bio, const char *in, int inl, int pktnum, int type)
Macro Definition Documentation
INJECT_PACKET
#define INJECT_PACKET 1
Definition at line 30 of file ssltestlib.h.
INJECT_PACKET_IGNORE_REC_SEQ
#define INJECT_PACKET_IGNORE_REC_SEQ 2
Definition at line 31 of file ssltestlib.h.
Function Documentation
bio_f_tls_dump_filter()
const BIO_METHOD* bio_f_tls_dump_filter (void)
Definition at line 31 of file ssltestlib.c.
bio_f_tls_dump_filter_free()
void bio_f_tls_dump_filter_free (void)
Definition at line 49 of file ssltestlib.c.
References BIO_meth_free().
bio_s_mempacket_test()
const BIO_METHOD* bio_s_mempacket_test (void)
Definition at line 265 of file ssltestlib.c.
Referenced by create_ssl_objects().
bio_s_mempacket_test_free()
void bio_s_mempacket_test_free (void)
Definition at line 283 of file ssltestlib.c.
References BIO_meth_free().
create_ssl_connection()
int create_ssl_connection (SSL * serverssl, SSL * clientssl)
Definition at line 644 of file ssltestlib.c.
create_ssl_ctx_pair()
int create_ssl_ctx_pair (const SSL_METHOD * sm, const SSL_METHOD * cm, SSL_CTX ** sctx, SSL_CTX ** cctx, char * certfile, char * privkeyfile)
Definition at line 525 of file ssltestlib.c.
References NULL, SSL_CTX_check_private_key(), SSL_CTX_free(), SSL_CTX_new(), SSL_CTX_set_dh_auto, SSL_CTX_use_certificate_file(), SSL_CTX_use_PrivateKey_file(), and SSL_FILETYPE_PEM.
create_ssl_objects()
int create_ssl_objects (SSL_CTX * serverctx, SSL_CTX * clientctx, SSL ** sssl, SSL ** cssl, BIO * s_to_c_fbio, BIO * c_to_s_fbio)
Definition at line 572 of file ssltestlib.c.
References BIO_free(), BIO_new(), BIO_push(), BIO_s_mem(), bio_s_mempacket_test(), BIO_set_mem_eof_return, BIO_up_ref(), NULL, SSL_free(), SSL_is_dtls(), SSL_new(), and SSL_set_bio().
mempacket_test_inject()
int mempacket_test_inject (BIO * bio, const char * in, int inl, int pktnum, int type)
Definition at line 388 of file ssltestlib.c.
References BIO_get_data(), ctx, NULL, and OPENSSL_malloc.