crypto/stack/stack.c File Reference
stack.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include "internal/numbers.h"
#include <openssl/stack.h>
#include <openssl/objects.h>
#include <errno.h>
Data Structures
struct OPENSSL_STACK
Macros
#define MIN_NODES 4
Functions
OPENSSL_sk_compfunc OPENSSL_sk_set_cmp_func (OPENSSL_STACK *sk, OPENSSL_sk_compfunc c)
OPENSSL_STACK * OPENSSL_sk_dup (const OPENSSL_STACK *sk)
OPENSSL_STACK * OPENSSL_sk_deep_copy (const OPENSSL_STACK *sk, OPENSSL_sk_copyfunc copy_func, OPENSSL_sk_freefunc free_func)
OPENSSL_STACK * OPENSSL_sk_new_null (void)
OPENSSL_STACK * OPENSSL_sk_new (OPENSSL_sk_compfunc c)
int OPENSSL_sk_insert (OPENSSL_STACK *st, const void *data, int loc)
void * OPENSSL_sk_delete_ptr (OPENSSL_STACK *st, const void *p)
void * OPENSSL_sk_delete (OPENSSL_STACK *st, int loc)
int OPENSSL_sk_find (OPENSSL_STACK *st, const void *data)
int OPENSSL_sk_find_ex (OPENSSL_STACK *st, const void *data)
int OPENSSL_sk_push (OPENSSL_STACK *st, const void *data)
int OPENSSL_sk_unshift (OPENSSL_STACK *st, const void *data)
void * OPENSSL_sk_shift (OPENSSL_STACK *st)
void * OPENSSL_sk_pop (OPENSSL_STACK *st)
void OPENSSL_sk_zero (OPENSSL_STACK *st)
void OPENSSL_sk_pop_free (OPENSSL_STACK *st, OPENSSL_sk_freefunc func)
void OPENSSL_sk_free (OPENSSL_STACK *st)
int OPENSSL_sk_num (const OPENSSL_STACK *st)
void * OPENSSL_sk_value (const OPENSSL_STACK *st, int i)
void * OPENSSL_sk_set (OPENSSL_STACK *st, int i, const void *data)
void OPENSSL_sk_sort (OPENSSL_STACK *st)
int OPENSSL_sk_is_sorted (const OPENSSL_STACK *st)
Macro Definition Documentation
MIN_NODES
#define MIN_NODES 4
Definition at line 25 of file stack.c.
Function Documentation
OPENSSL_sk_deep_copy()
OPENSSL_STACK* OPENSSL_sk_deep_copy (const OPENSSL_STACK * sk, OPENSSL_sk_copyfunc copy_func, OPENSSL_sk_freefunc free_func)
Definition at line 62 of file stack.c.
OPENSSL_sk_delete()
void* OPENSSL_sk_delete (OPENSSL_STACK * st, int loc)
Definition at line 169 of file stack.c.
Referenced by OPENSSL_sk_delete_ptr(), OPENSSL_sk_pop(), and OPENSSL_sk_shift().
OPENSSL_sk_delete_ptr()
void* OPENSSL_sk_delete_ptr (OPENSSL_STACK * st, const void * p)
Definition at line 159 of file stack.c.
References NULL, and OPENSSL_sk_delete().
OPENSSL_sk_dup()
OPENSSL_STACK* OPENSSL_sk_dup (const OPENSSL_STACK * sk)
Definition at line 40 of file stack.c.
OPENSSL_sk_find()
int OPENSSL_sk_find (OPENSSL_STACK * st, const void * data)
Definition at line 209 of file stack.c.
OPENSSL_sk_find_ex()
int OPENSSL_sk_find_ex (OPENSSL_STACK * st, const void * data)
Definition at line 214 of file stack.c.
OPENSSL_sk_free()
void OPENSSL_sk_free (OPENSSL_STACK * st)
Definition at line 269 of file stack.c.
References NULL, and OPENSSL_free.
Referenced by OPENSSL_sk_pop_free().
OPENSSL_sk_insert()
int OPENSSL_sk_insert (OPENSSL_STACK * st, const void * data, int loc)
Definition at line 121 of file stack.c.
References OPENSSL_STACK::data, loc, NULL, OPENSSL_STACK::num_alloc, OPENSSL_realloc, and SIZE_MAX.
Referenced by OPENSSL_sk_push(), and OPENSSL_sk_unshift().
OPENSSL_sk_is_sorted()
int OPENSSL_sk_is_sorted (const OPENSSL_STACK * st)
Definition at line 307 of file stack.c.
References NULL.
OPENSSL_sk_new()
OPENSSL_STACK* OPENSSL_sk_new (OPENSSL_sk_compfunc c)
Definition at line 104 of file stack.c.
Referenced by OPENSSL_sk_new_null().
OPENSSL_sk_new_null()
OPENSSL_STACK* OPENSSL_sk_new_null (void)
Definition at line 99 of file stack.c.
References NULL, and OPENSSL_sk_new().
OPENSSL_sk_num()
int OPENSSL_sk_num (const OPENSSL_STACK * st)
Definition at line 277 of file stack.c.
References NULL.
OPENSSL_sk_pop()
void* OPENSSL_sk_pop (OPENSSL_STACK * st)
Definition at line 238 of file stack.c.
References NULL, and OPENSSL_sk_delete().
OPENSSL_sk_pop_free()
void OPENSSL_sk_pop_free (OPENSSL_STACK * st, OPENSSL_sk_freefunc func)
Definition at line 257 of file stack.c.
References NULL, and OPENSSL_sk_free().
OPENSSL_sk_push()
int OPENSSL_sk_push (OPENSSL_STACK * st, const void * data)
Definition at line 219 of file stack.c.
References OPENSSL_sk_insert().
OPENSSL_sk_set()
void* OPENSSL_sk_set (OPENSSL_STACK * st, int i, const void * data)
Definition at line 291 of file stack.c.
References OPENSSL_STACK::data, and NULL.
OPENSSL_sk_set_cmp_func()
OPENSSL_sk_compfunc OPENSSL_sk_set_cmp_func (OPENSSL_STACK * sk, OPENSSL_sk_compfunc c)
Definition at line 29 of file stack.c.
OPENSSL_sk_shift()
void* OPENSSL_sk_shift (OPENSSL_STACK * st)
Definition at line 229 of file stack.c.
References NULL, and OPENSSL_sk_delete().
OPENSSL_sk_sort()
void OPENSSL_sk_sort (OPENSSL_STACK * st)
Definition at line 299 of file stack.c.
References NULL.
OPENSSL_sk_unshift()
int OPENSSL_sk_unshift (OPENSSL_STACK * st, const void * data)
Definition at line 224 of file stack.c.
References OPENSSL_sk_insert().
OPENSSL_sk_value()
void* OPENSSL_sk_value (const OPENSSL_STACK * st, int i)
Definition at line 284 of file stack.c.
References NULL.
OPENSSL_sk_zero()
void OPENSSL_sk_zero (OPENSSL_STACK * st)
Definition at line 247 of file stack.c.
References NULL.