include/openssl/stack.h File Reference
stack.h File Reference
Macros
#define _STACK OPENSSL_STACK
#define sk_num OPENSSL_sk_num
#define sk_value OPENSSL_sk_value
#define sk_set OPENSSL_sk_set
#define sk_new OPENSSL_sk_new
#define sk_new_null OPENSSL_sk_new_null
#define sk_free OPENSSL_sk_free
#define sk_pop_free OPENSSL_sk_pop_free
#define sk_deep_copy OPENSSL_sk_deep_copy
#define sk_insert OPENSSL_sk_insert
#define sk_delete OPENSSL_sk_delete
#define sk_delete_ptr OPENSSL_sk_delete_ptr
#define sk_find OPENSSL_sk_find
#define sk_find_ex OPENSSL_sk_find_ex
#define sk_push OPENSSL_sk_push
#define sk_unshift OPENSSL_sk_unshift
#define sk_shift OPENSSL_sk_shift
#define sk_pop OPENSSL_sk_pop
#define sk_zero OPENSSL_sk_zero
#define sk_set_cmp_func OPENSSL_sk_set_cmp_func
#define sk_dup OPENSSL_sk_dup
#define sk_sort OPENSSL_sk_sort
#define sk_is_sorted OPENSSL_sk_is_sorted
Typedefs
typedef int(* OPENSSL_sk_compfunc) (const void *, const void *)
typedef void(* OPENSSL_sk_freefunc) (void *)
typedef void *(* OPENSSL_sk_copyfunc) (const void *)
Functions
int OPENSSL_sk_num (const OPENSSL_STACK *)
void * OPENSSL_sk_value (const OPENSSL_STACK *, int)
void * OPENSSL_sk_set (OPENSSL_STACK *st, int i, const void *data)
OPENSSL_STACK * OPENSSL_sk_new (OPENSSL_sk_compfunc cmp)
OPENSSL_STACK * OPENSSL_sk_new_null (void)
void OPENSSL_sk_free (OPENSSL_STACK *)
void OPENSSL_sk_pop_free (OPENSSL_STACK *st, void(*func)(void *))
OPENSSL_STACK * OPENSSL_sk_deep_copy (const OPENSSL_STACK *, OPENSSL_sk_copyfunc c, OPENSSL_sk_freefunc f)
int OPENSSL_sk_insert (OPENSSL_STACK *sk, const void *data, int where)
void * OPENSSL_sk_delete (OPENSSL_STACK *st, int loc)
void * OPENSSL_sk_delete_ptr (OPENSSL_STACK *st, const void *p)
int OPENSSL_sk_find (OPENSSL_STACK *st, const void *data)
int OPENSSL_sk_find_ex (OPENSSL_STACK *st, const void *data)
int OPENSSL_sk_push (OPENSSL_STACK *st, const void *data)
int OPENSSL_sk_unshift (OPENSSL_STACK *st, const void *data)
void * OPENSSL_sk_shift (OPENSSL_STACK *st)
void * OPENSSL_sk_pop (OPENSSL_STACK *st)
void OPENSSL_sk_zero (OPENSSL_STACK *st)
OPENSSL_sk_compfunc OPENSSL_sk_set_cmp_func (OPENSSL_STACK *sk, OPENSSL_sk_compfunc cmp)
OPENSSL_STACK * OPENSSL_sk_dup (const OPENSSL_STACK *st)
void OPENSSL_sk_sort (OPENSSL_STACK *st)
int OPENSSL_sk_is_sorted (const OPENSSL_STACK *st)
Macro Definition Documentation
_STACK
#define _STACK OPENSSL_STACK
Definition at line 49 of file stack.h.
sk_deep_copy
#define sk_deep_copy OPENSSL_sk_deep_copy
Definition at line 57 of file stack.h.
sk_delete
#define sk_delete OPENSSL_sk_delete
Definition at line 59 of file stack.h.
sk_delete_ptr
#define sk_delete_ptr OPENSSL_sk_delete_ptr
Definition at line 60 of file stack.h.
sk_dup
#define sk_dup OPENSSL_sk_dup
Definition at line 69 of file stack.h.
sk_find
#define sk_find OPENSSL_sk_find
Definition at line 61 of file stack.h.
sk_find_ex
#define sk_find_ex OPENSSL_sk_find_ex
Definition at line 62 of file stack.h.
sk_free
#define sk_free OPENSSL_sk_free
Definition at line 55 of file stack.h.
sk_insert
#define sk_insert OPENSSL_sk_insert
Definition at line 58 of file stack.h.
sk_is_sorted
#define sk_is_sorted OPENSSL_sk_is_sorted
Definition at line 71 of file stack.h.
sk_new
#define sk_new OPENSSL_sk_new
Definition at line 53 of file stack.h.
sk_new_null
#define sk_new_null OPENSSL_sk_new_null
Definition at line 54 of file stack.h.
sk_num
#define sk_num OPENSSL_sk_num
Definition at line 50 of file stack.h.
sk_pop
#define sk_pop OPENSSL_sk_pop
Definition at line 66 of file stack.h.
sk_pop_free
#define sk_pop_free OPENSSL_sk_pop_free
Definition at line 56 of file stack.h.
sk_push
#define sk_push OPENSSL_sk_push
Definition at line 63 of file stack.h.
sk_set
#define sk_set OPENSSL_sk_set
Definition at line 52 of file stack.h.
sk_set_cmp_func
#define sk_set_cmp_func OPENSSL_sk_set_cmp_func
Definition at line 68 of file stack.h.
sk_shift
#define sk_shift OPENSSL_sk_shift
Definition at line 65 of file stack.h.
sk_sort
#define sk_sort OPENSSL_sk_sort
Definition at line 70 of file stack.h.
sk_unshift
#define sk_unshift OPENSSL_sk_unshift
Definition at line 64 of file stack.h.
sk_value
#define sk_value OPENSSL_sk_value
Definition at line 51 of file stack.h.
sk_zero
#define sk_zero OPENSSL_sk_zero
Definition at line 67 of file stack.h.
Typedef Documentation
OPENSSL_sk_compfunc
typedef int(* OPENSSL_sk_compfunc) (const void *, const void *)
Definition at line 19 of file stack.h.
OPENSSL_sk_copyfunc
typedef void*(* OPENSSL_sk_copyfunc) (const void *)
Definition at line 21 of file stack.h.
OPENSSL_sk_freefunc
typedef void(* OPENSSL_sk_freefunc) (void *)
Definition at line 20 of file stack.h.
Function Documentation
OPENSSL_sk_deep_copy()
OPENSSL_STACK* OPENSSL_sk_deep_copy (const OPENSSL_STACK * , OPENSSL_sk_copyfunc c, OPENSSL_sk_freefunc f)
Definition at line 62 of file stack.c.
OPENSSL_sk_delete()
void* OPENSSL_sk_delete (OPENSSL_STACK * st, int loc)
Definition at line 169 of file stack.c.
Referenced by OPENSSL_sk_delete_ptr(), OPENSSL_sk_pop(), and OPENSSL_sk_shift().
OPENSSL_sk_delete_ptr()
void* OPENSSL_sk_delete_ptr (OPENSSL_STACK * st, const void * p)
Definition at line 159 of file stack.c.
References NULL, and OPENSSL_sk_delete().
OPENSSL_sk_dup()
OPENSSL_STACK* OPENSSL_sk_dup (const OPENSSL_STACK * st)
Definition at line 40 of file stack.c.
OPENSSL_sk_find()
int OPENSSL_sk_find (OPENSSL_STACK * st, const void * data)
Definition at line 209 of file stack.c.
OPENSSL_sk_find_ex()
int OPENSSL_sk_find_ex (OPENSSL_STACK * st, const void * data)
Definition at line 214 of file stack.c.
OPENSSL_sk_free()
void OPENSSL_sk_free (OPENSSL_STACK *)
Definition at line 269 of file stack.c.
References NULL, and OPENSSL_free.
Referenced by OPENSSL_sk_pop_free().
OPENSSL_sk_insert()
int OPENSSL_sk_insert (OPENSSL_STACK * sk, const void * data, int where)
Definition at line 121 of file stack.c.
References OPENSSL_STACK::data, loc, NULL, OPENSSL_STACK::num_alloc, OPENSSL_realloc, and SIZE_MAX.
Referenced by OPENSSL_sk_push(), and OPENSSL_sk_unshift().
OPENSSL_sk_is_sorted()
int OPENSSL_sk_is_sorted (const OPENSSL_STACK * st)
Definition at line 307 of file stack.c.
References NULL.
OPENSSL_sk_new()
OPENSSL_STACK* OPENSSL_sk_new (OPENSSL_sk_compfunc cmp)
Definition at line 104 of file stack.c.
Referenced by OPENSSL_sk_new_null().
OPENSSL_sk_new_null()
OPENSSL_STACK* OPENSSL_sk_new_null (void)
Definition at line 99 of file stack.c.
References NULL, and OPENSSL_sk_new().
OPENSSL_sk_num()
int OPENSSL_sk_num (const OPENSSL_STACK *)
Definition at line 277 of file stack.c.
References NULL.
OPENSSL_sk_pop()
void* OPENSSL_sk_pop (OPENSSL_STACK * st)
Definition at line 238 of file stack.c.
References NULL, and OPENSSL_sk_delete().
OPENSSL_sk_pop_free()
void OPENSSL_sk_pop_free (OPENSSL_STACK * st, void(*)(void *) func)
Definition at line 257 of file stack.c.
References NULL, and OPENSSL_sk_free().
OPENSSL_sk_push()
int OPENSSL_sk_push (OPENSSL_STACK * st, const void * data)
Definition at line 219 of file stack.c.
References OPENSSL_sk_insert().
OPENSSL_sk_set()
void* OPENSSL_sk_set (OPENSSL_STACK * st, int i, const void * data)
Definition at line 291 of file stack.c.
References OPENSSL_STACK::data, and NULL.
OPENSSL_sk_set_cmp_func()
OPENSSL_sk_compfunc OPENSSL_sk_set_cmp_func (OPENSSL_STACK * sk, OPENSSL_sk_compfunc cmp)
Definition at line 29 of file stack.c.
OPENSSL_sk_shift()
void* OPENSSL_sk_shift (OPENSSL_STACK * st)
Definition at line 229 of file stack.c.
References NULL, and OPENSSL_sk_delete().
OPENSSL_sk_sort()
void OPENSSL_sk_sort (OPENSSL_STACK * st)
Definition at line 299 of file stack.c.
References NULL.
OPENSSL_sk_unshift()
int OPENSSL_sk_unshift (OPENSSL_STACK * st, const void * data)
Definition at line 224 of file stack.c.
References OPENSSL_sk_insert().
OPENSSL_sk_value()
void* OPENSSL_sk_value (const OPENSSL_STACK * , int)
Definition at line 284 of file stack.c.
References NULL.
OPENSSL_sk_zero()
void OPENSSL_sk_zero (OPENSSL_STACK * st)
Definition at line 247 of file stack.c.
References NULL.