ssl/statem/statem_locl.h File Reference
statem_locl.h File Reference
Macros
#define HELLO_VERIFY_REQUEST_MAX_LENGTH 258
#define SERVER_HELLO_MAX_LENGTH 20000
#define HELLO_RETRY_REQUEST_MAX_LENGTH 20000
#define ENCRYPTED_EXTENSIONS_MAX_LENGTH 20000
#define SERVER_KEY_EXCH_MAX_LENGTH 102400
#define SERVER_HELLO_DONE_MAX_LENGTH 0
#define KEY_UPDATE_MAX_LENGTH 1
#define CCS_MAX_LENGTH 1
#define FINISHED_MAX_LENGTH 64
#define MAX_KEY_UPDATE_MESSAGES 32
#define EXT_TLS_ONLY 0x0001
#define EXT_DTLS_ONLY 0x0002
#define EXT_TLS_IMPLEMENTATION_ONLY 0x0004
#define EXT_SSL3_ALLOWED 0x0008
#define EXT_TLS1_2_AND_BELOW_ONLY 0x0010
#define EXT_TLS1_3_ONLY 0x0020
#define EXT_CLIENT_HELLO 0x0040
#define EXT_TLS1_2_SERVER_HELLO 0x0080
#define EXT_TLS1_3_SERVER_HELLO 0x0100
#define EXT_TLS1_3_ENCRYPTED_EXTENSIONS 0x0200
#define EXT_TLS1_3_HELLO_RETRY_REQUEST 0x0400
#define EXT_TLS1_3_CERTIFICATE 0x0800
#define EXT_TLS1_3_NEW_SESSION_TICKET 0x1000
#define TLSEXT_TYPE_cryptopro_bug 0xfde8
Typedefs
typedef int(* confunc_f) (SSL *s, WPACKET *pkt)
Enumerations
enum MSG_PROCESS_RETURN { MSG_PROCESS_ERROR, MSG_PROCESS_FINISHED_READING, MSG_PROCESS_CONTINUE_PROCESSING, MSG_PROCESS_CONTINUE_READING }
Functions
int statem_flush (SSL *s)
int check_in_list (SSL *s, unsigned int group_id, const unsigned char *groups, size_t num_groups, int checkallow)
int ossl_statem_client_read_transition (SSL *s, int mt)
WRITE_TRAN ossl_statem_client_write_transition (SSL *s)
WORK_STATE ossl_statem_client_pre_work (SSL *s, WORK_STATE wst)
WORK_STATE ossl_statem_client_post_work (SSL *s, WORK_STATE wst)
int ossl_statem_client_construct_message (SSL *s, WPACKET *pkt, confunc_f *confunc, int *mt)
size_t ossl_statem_client_max_message_size (SSL *s)
MSG_PROCESS_RETURN ossl_statem_client_process_message (SSL *s, PACKET *pkt)
WORK_STATE ossl_statem_client_post_process_message (SSL *s, WORK_STATE wst)
int ossl_statem_server_read_transition (SSL *s, int mt)
WRITE_TRAN ossl_statem_server_write_transition (SSL *s)
WORK_STATE ossl_statem_server_pre_work (SSL *s, WORK_STATE wst)
WORK_STATE ossl_statem_server_post_work (SSL *s, WORK_STATE wst)
int ossl_statem_server_construct_message (SSL *s, WPACKET *pkt, confunc_f *confunc, int *mt)
size_t ossl_statem_server_max_message_size (SSL *s)
MSG_PROCESS_RETURN ossl_statem_server_process_message (SSL *s, PACKET *pkt)
WORK_STATE ossl_statem_server_post_process_message (SSL *s, WORK_STATE wst)
__owur int tls_get_message_header (SSL *s, int *mt)
__owur int tls_get_message_body (SSL *s, size_t *len)
__owur int dtls_get_message (SSL *s, int *mt, size_t *len)
__owur int tls_process_initial_server_flight (SSL *s, int *al)
__owur MSG_PROCESS_RETURN tls_process_change_cipher_spec (SSL *s, PACKET *pkt)
__owur MSG_PROCESS_RETURN tls_process_finished (SSL *s, PACKET *pkt)
__owur int tls_construct_change_cipher_spec (SSL *s, WPACKET *pkt)
__owur int dtls_construct_change_cipher_spec (SSL *s, WPACKET *pkt)
__owur int tls_construct_finished (SSL *s, WPACKET *pkt)
__owur int tls_construct_key_update (SSL *s, WPACKET *pkt)
__owur MSG_PROCESS_RETURN tls_process_key_update (SSL *s, PACKET *pkt)
__owur WORK_STATE tls_finish_handshake (SSL *s, WORK_STATE wst, int clearbufs)
__owur WORK_STATE dtls_wait_for_dry (SSL *s)
__owur int tls_construct_client_hello (SSL *s, WPACKET *pkt)
__owur MSG_PROCESS_RETURN tls_process_server_hello (SSL *s, PACKET *pkt)
__owur MSG_PROCESS_RETURN tls_process_certificate_request (SSL *s, PACKET *pkt)
__owur MSG_PROCESS_RETURN tls_process_new_session_ticket (SSL *s, PACKET *pkt)
__owur int tls_process_cert_status_body (SSL *s, PACKET *pkt, int *al)
__owur MSG_PROCESS_RETURN tls_process_cert_status (SSL *s, PACKET *pkt)
__owur MSG_PROCESS_RETURN tls_process_server_done (SSL *s, PACKET *pkt)
__owur int tls_construct_cert_verify (SSL *s, WPACKET *pkt)
__owur WORK_STATE tls_prepare_client_certificate (SSL *s, WORK_STATE wst)
__owur int tls_construct_client_certificate (SSL *s, WPACKET *pkt)
__owur int ssl_do_client_cert_cb (SSL *s, X509 **px509, EVP_PKEY **ppkey)
__owur int tls_construct_client_key_exchange (SSL *s, WPACKET *pkt)
__owur int tls_client_key_exchange_post_work (SSL *s)
__owur int tls_construct_cert_status_body (SSL *s, WPACKET *pkt)
__owur int tls_construct_cert_status (SSL *s, WPACKET *pkt)
__owur MSG_PROCESS_RETURN tls_process_key_exchange (SSL *s, PACKET *pkt)
__owur MSG_PROCESS_RETURN tls_process_server_certificate (SSL *s, PACKET *pkt)
__owur int ssl3_check_cert_and_algorithm (SSL *s)
__owur int tls_construct_next_proto (SSL *s, WPACKET *pkt)
__owur MSG_PROCESS_RETURN tls_process_hello_req (SSL *s, PACKET *pkt)
__owur MSG_PROCESS_RETURN dtls_process_hello_verify (SSL *s, PACKET *pkt)
__owur MSG_PROCESS_RETURN tls_process_client_hello (SSL *s, PACKET *pkt)
__owur WORK_STATE tls_post_process_client_hello (SSL *s, WORK_STATE wst)
__owur int tls_construct_server_hello (SSL *s, WPACKET *pkt)
__owur int dtls_construct_hello_verify_request (SSL *s, WPACKET *pkt)
__owur int tls_construct_server_certificate (SSL *s, WPACKET *pkt)
__owur int tls_construct_server_key_exchange (SSL *s, WPACKET *pkt)
__owur int tls_construct_certificate_request (SSL *s, WPACKET *pkt)
__owur int tls_construct_server_done (SSL *s, WPACKET *pkt)
__owur MSG_PROCESS_RETURN tls_process_client_certificate (SSL *s, PACKET *pkt)
__owur MSG_PROCESS_RETURN tls_process_client_key_exchange (SSL *s, PACKET *pkt)
__owur WORK_STATE tls_post_process_client_key_exchange (SSL *s, WORK_STATE wst)
__owur MSG_PROCESS_RETURN tls_process_cert_verify (SSL *s, PACKET *pkt)
__owur MSG_PROCESS_RETURN tls_process_next_proto (SSL *s, PACKET *pkt)
__owur int tls_construct_new_session_ticket (SSL *s, WPACKET *pkt)
__owur int tls_collect_extensions (SSL *s, PACKET *packet, unsigned int context, RAW_EXTENSION **res, int *al)
__owur int tls_parse_extension (SSL *s, TLSEXT_INDEX idx, int context, RAW_EXTENSION *exts, X509 *x, size_t chainidx, int *al)
__owur int tls_parse_all_extensions (SSL *s, int context, RAW_EXTENSION *exts, X509 *x, size_t chainidx, int *al)
__owur int tls_construct_extensions (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
__owur int tls_psk_do_binder (SSL *s, const EVP_MD *md, const unsigned char *msgstart, size_t binderoffset, const unsigned char *binderin, unsigned char *binderout, SSL_SESSION *sess, int sign)
int tls_parse_ctos_renegotiate (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_server_name (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_srp (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_ec_pt_formats (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_supported_groups (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_session_ticket (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_sig_algs (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_status_request (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_npn (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_alpn (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_use_srtp (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_etm (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_key_share (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_ems (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_psk_kex_modes (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_ctos_psk (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_renegotiate (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_server_name (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_ec_pt_formats (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_session_ticket (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_status_request (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_next_proto_neg (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_alpn (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_use_srtp (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_etm (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_ems (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_key_share (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_cryptopro_bug (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_stoc_psk (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_renegotiate (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_server_name (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_srp (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_ec_pt_formats (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_supported_groups (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_session_ticket (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_sig_algs (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_status_request (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_npn (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_alpn (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_use_srtp (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_etm (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_sct (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_ems (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_supported_versions (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_key_share (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_psk_kex_modes (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_padding (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_construct_ctos_psk (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_renegotiate (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_server_name (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_ec_pt_formats (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_session_ticket (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_status_request (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_sct (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_npn (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_alpn (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_use_srtp (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_etm (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_ems (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_key_share (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int tls_parse_stoc_psk (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
Macro Definition Documentation
CCS_MAX_LENGTH
#define CCS_MAX_LENGTH 1
Definition at line 27 of file statem_locl.h.
Referenced by ossl_statem_client_max_message_size(), and ossl_statem_server_max_message_size().
ENCRYPTED_EXTENSIONS_MAX_LENGTH
#define ENCRYPTED_EXTENSIONS_MAX_LENGTH 20000
Definition at line 23 of file statem_locl.h.
Referenced by ossl_statem_client_max_message_size().
EXT_CLIENT_HELLO
#define EXT_CLIENT_HELLO 0x0040
Definition at line 47 of file statem_locl.h.
Referenced by tls_collect_extensions(), tls_construct_extensions(), and tls_parse_all_extensions().
EXT_DTLS_ONLY
#define EXT_DTLS_ONLY 0x0002
Definition at line 38 of file statem_locl.h.
EXT_SSL3_ALLOWED
#define EXT_SSL3_ALLOWED 0x0008
Definition at line 42 of file statem_locl.h.
Referenced by tls_construct_extensions().
EXT_TLS1_2_AND_BELOW_ONLY
#define EXT_TLS1_2_AND_BELOW_ONLY 0x0010
Definition at line 44 of file statem_locl.h.
Referenced by tls_construct_extensions().
EXT_TLS1_2_SERVER_HELLO
#define EXT_TLS1_2_SERVER_HELLO 0x0080
Definition at line 49 of file statem_locl.h.
Referenced by tls_collect_extensions(), tls_construct_extensions(), tls_construct_server_hello(), and tls_parse_all_extensions().
EXT_TLS1_3_CERTIFICATE
#define EXT_TLS1_3_CERTIFICATE 0x0800
Definition at line 53 of file statem_locl.h.
EXT_TLS1_3_ENCRYPTED_EXTENSIONS
#define EXT_TLS1_3_ENCRYPTED_EXTENSIONS 0x0200
Definition at line 51 of file statem_locl.h.
EXT_TLS1_3_HELLO_RETRY_REQUEST
#define EXT_TLS1_3_HELLO_RETRY_REQUEST 0x0400
Definition at line 52 of file statem_locl.h.
EXT_TLS1_3_NEW_SESSION_TICKET
#define EXT_TLS1_3_NEW_SESSION_TICKET 0x1000
Definition at line 54 of file statem_locl.h.
EXT_TLS1_3_ONLY
#define EXT_TLS1_3_ONLY 0x0020
Definition at line 46 of file statem_locl.h.
Referenced by tls_construct_extensions().
EXT_TLS1_3_SERVER_HELLO
#define EXT_TLS1_3_SERVER_HELLO 0x0100
Definition at line 50 of file statem_locl.h.
Referenced by tls_construct_server_hello().
EXT_TLS_IMPLEMENTATION_ONLY
#define EXT_TLS_IMPLEMENTATION_ONLY 0x0004
Definition at line 40 of file statem_locl.h.
Referenced by tls_construct_extensions().
EXT_TLS_ONLY
#define EXT_TLS_ONLY 0x0001
Definition at line 36 of file statem_locl.h.
FINISHED_MAX_LENGTH
#define FINISHED_MAX_LENGTH 64
Definition at line 29 of file statem_locl.h.
Referenced by ossl_statem_client_max_message_size(), and ossl_statem_server_max_message_size().
HELLO_RETRY_REQUEST_MAX_LENGTH
#define HELLO_RETRY_REQUEST_MAX_LENGTH 20000
Definition at line 22 of file statem_locl.h.
Referenced by ossl_statem_client_max_message_size().
HELLO_VERIFY_REQUEST_MAX_LENGTH
#define HELLO_VERIFY_REQUEST_MAX_LENGTH 258
Definition at line 20 of file statem_locl.h.
Referenced by ossl_statem_client_max_message_size().
KEY_UPDATE_MAX_LENGTH
#define KEY_UPDATE_MAX_LENGTH 1
Definition at line 26 of file statem_locl.h.
Referenced by ossl_statem_client_max_message_size(), and ossl_statem_server_max_message_size().
MAX_KEY_UPDATE_MESSAGES
#define MAX_KEY_UPDATE_MESSAGES 32
Definition at line 32 of file statem_locl.h.
Referenced by tls_process_key_update().
SERVER_HELLO_DONE_MAX_LENGTH
#define SERVER_HELLO_DONE_MAX_LENGTH 0
Definition at line 25 of file statem_locl.h.
Referenced by ossl_statem_client_max_message_size().
SERVER_HELLO_MAX_LENGTH
#define SERVER_HELLO_MAX_LENGTH 20000
Definition at line 21 of file statem_locl.h.
Referenced by ossl_statem_client_max_message_size().
SERVER_KEY_EXCH_MAX_LENGTH
#define SERVER_KEY_EXCH_MAX_LENGTH 102400
Definition at line 24 of file statem_locl.h.
Referenced by ossl_statem_client_max_message_size().
TLSEXT_TYPE_cryptopro_bug
#define TLSEXT_TYPE_cryptopro_bug 0xfde8
Definition at line 266 of file statem_locl.h.
Typedef Documentation
confunc_f
typedef int(* confunc_f) (SSL *s, WPACKET *pkt)
Definition at line 74 of file statem_locl.h.
Enumeration Type Documentation
MSG_PROCESS_RETURN
enum MSG_PROCESS_RETURN
Enumerator
MSG_PROCESS_ERROR
MSG_PROCESS_FINISHED_READING
MSG_PROCESS_CONTINUE_PROCESSING
MSG_PROCESS_CONTINUE_READING
Definition at line 57 of file statem_locl.h.
Function Documentation
check_in_list()
int check_in_list (SSL * s, unsigned int group_id, const unsigned char * groups, size_t num_groups, int checkallow)
Definition at line 1810 of file statem_lib.c.
References NULL, SSL_SECOP_CURVE_CHECK, and tls_curve_allowed().
dtls_construct_change_cipher_spec()
__owur int dtls_construct_change_cipher_spec (SSL * s, WPACKET * pkt)
Definition at line 875 of file statem_dtls.c.
References DTLS1_BAD_VER, ERR_R_INTERNAL_ERROR, SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_DTLS_CONSTRUCT_CHANGE_CIPHER_SPEC, SSLerr, and WPACKET_put_bytes_u16.
Referenced by ossl_statem_client_construct_message(), and ossl_statem_server_construct_message().
dtls_construct_hello_verify_request()
__owur int dtls_construct_hello_verify_request (SSL * s, WPACKET * pkt)
Definition at line 1138 of file statem_srvr.c.
References dtls_raw_hello_verify_request(), ERR_R_INTERNAL_ERROR, NULL, SSL_F_DTLS_CONSTRUCT_HELLO_VERIFY_REQUEST, SSL_R_COOKIE_GEN_CALLBACK_FAILURE, and SSLerr.
Referenced by ossl_statem_server_construct_message().
dtls_get_message()
__owur int dtls_get_message (SSL * s, int * mt, size_t * len)
Definition at line 323 of file statem_dtls.c.
References hm_header_st::msg_len.
dtls_process_hello_verify()
__owur MSG_PROCESS_RETURN dtls_process_hello_verify (SSL * s, PACKET * pkt)
Definition at line 1137 of file statem_clnt.c.
Referenced by ossl_statem_client_process_message().
dtls_wait_for_dry()
__owur WORK_STATE dtls_wait_for_dry (SSL * s)
Definition at line 890 of file statem_dtls.c.
Referenced by ossl_statem_client_pre_work(), and ossl_statem_server_pre_work().
ossl_statem_client_construct_message()
int ossl_statem_client_construct_message (SSL * s, WPACKET * pkt, confunc_f * confunc, int * mt)
Definition at line 754 of file statem_clnt.c.
References dtls_construct_change_cipher_spec(), SSL3_MT_CERTIFICATE, SSL3_MT_CERTIFICATE_VERIFY, SSL3_MT_CHANGE_CIPHER_SPEC, SSL3_MT_CLIENT_HELLO, SSL3_MT_CLIENT_KEY_EXCHANGE, SSL3_MT_FINISHED, SSL3_MT_KEY_UPDATE, SSL3_MT_NEXT_PROTO, SSL_IS_DTLS, tls_construct_cert_verify(), tls_construct_change_cipher_spec(), tls_construct_client_certificate(), tls_construct_client_hello(), tls_construct_client_key_exchange(), tls_construct_finished(), tls_construct_key_update(), tls_construct_next_proto(), TLS_ST_CW_CERT, TLS_ST_CW_CERT_VRFY, TLS_ST_CW_CHANGE, TLS_ST_CW_CLNT_HELLO, TLS_ST_CW_FINISHED, TLS_ST_CW_KEY_EXCH, TLS_ST_CW_KEY_UPDATE, and TLS_ST_CW_NEXT_PROTO.
ossl_statem_client_max_message_size()
size_t ossl_statem_client_max_message_size (SSL * s)
Definition at line 816 of file statem_clnt.c.
References CCS_MAX_LENGTH, DTLS1_BAD_VER, DTLS_ST_CR_HELLO_VERIFY_REQUEST, ENCRYPTED_EXTENSIONS_MAX_LENGTH, FINISHED_MAX_LENGTH, HELLO_RETRY_REQUEST_MAX_LENGTH, HELLO_VERIFY_REQUEST_MAX_LENGTH, KEY_UPDATE_MAX_LENGTH, SERVER_HELLO_DONE_MAX_LENGTH, SERVER_HELLO_MAX_LENGTH, SERVER_KEY_EXCH_MAX_LENGTH, SSL3_RT_MAX_PLAIN_LENGTH, TLS_ST_CR_CERT, TLS_ST_CR_CERT_REQ, TLS_ST_CR_CERT_STATUS, TLS_ST_CR_CERT_VRFY, TLS_ST_CR_CHANGE, TLS_ST_CR_ENCRYPTED_EXTENSIONS, TLS_ST_CR_FINISHED, TLS_ST_CR_HELLO_RETRY_REQUEST, TLS_ST_CR_KEY_EXCH, TLS_ST_CR_KEY_UPDATE, TLS_ST_CR_SESSION_TICKET, TLS_ST_CR_SRVR_DONE, and TLS_ST_CR_SRVR_HELLO.
ossl_statem_client_post_process_message()
WORK_STATE ossl_statem_client_post_process_message (SSL * s, WORK_STATE wst)
Definition at line 939 of file statem_clnt.c.
References BIO_clear_retry_flags, BIO_dgram_sctp_msg_waiting(), BIO_set_retry_read, ossl_statem_set_sctp_read_sock(), SSL_get_rbio(), SSL_READING, tls_prepare_client_certificate(), TLS_ST_CR_CERT_REQ, TLS_ST_CR_SRVR_DONE, WORK_ERROR, WORK_FINISHED_STOP, and WORK_MORE_A.
ossl_statem_client_post_work()
WORK_STATE ossl_statem_client_post_work (SSL * s, WORK_STATE wst)
Definition at line 655 of file statem_clnt.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_SCTP_NEXT_AUTH_KEY, dtls1_reset_seq_numbers(), NULL, SSL3_CC_APPLICATION, SSL3_CC_WRITE, SSL3_CHANGE_CIPHER_CLIENT_WRITE, SSL_get_wbio(), SSL_IS_DTLS, SSL_IS_TLS13, statem_flush(), tls13_update_key(), tls_client_key_exchange_post_work(), TLS_ST_CW_CHANGE, TLS_ST_CW_CLNT_HELLO, TLS_ST_CW_FINISHED, TLS_ST_CW_KEY_EXCH, TLS_ST_CW_KEY_UPDATE, WORK_ERROR, WORK_FINISHED_CONTINUE, WORK_MORE_A, and WORK_MORE_B.
ossl_statem_client_pre_work()
WORK_STATE ossl_statem_client_pre_work (SSL * s, WORK_STATE wst)
Definition at line 606 of file statem_clnt.c.
References BIO_dgram_is_sctp(), dtls_wait_for_dry(), ossl_statem_set_error(), ssl3_init_finished_mac(), SSL_get_wbio(), SSL_IS_DTLS, tls_finish_handshake(), TLS_ST_CW_CHANGE, TLS_ST_CW_CLNT_HELLO, TLS_ST_OK, WORK_ERROR, and WORK_FINISHED_CONTINUE.
ossl_statem_client_process_message()
MSG_PROCESS_RETURN ossl_statem_client_process_message (SSL * s, PACKET * pkt)
Definition at line 879 of file statem_clnt.c.
References dtls_process_hello_verify(), DTLS_ST_CR_HELLO_VERIFY_REQUEST, MSG_PROCESS_ERROR, tls_process_server_hello(), TLS_ST_CR_HELLO_RETRY_REQUEST, and TLS_ST_CR_SRVR_HELLO.
ossl_statem_client_read_transition()
int ossl_statem_client_read_transition (SSL * s, int mt)
Definition at line 223 of file statem_clnt.c.
References SSL_IS_TLS13.
ossl_statem_client_write_transition()
WRITE_TRAN ossl_statem_client_write_transition (SSL * s)
Definition at line 470 of file statem_clnt.c.
References SSL_IS_TLS13.
ossl_statem_server_construct_message()
int ossl_statem_server_construct_message (SSL * s, WPACKET * pkt, confunc_f * confunc, int * mt)
Definition at line 867 of file statem_srvr.c.
References DTLS1_MT_HELLO_VERIFY_REQUEST, dtls_construct_change_cipher_spec(), dtls_construct_hello_verify_request(), DTLS_ST_SW_HELLO_VERIFY_REQUEST, NULL, SSL3_MT_CERTIFICATE, SSL3_MT_CERTIFICATE_REQUEST, SSL3_MT_CERTIFICATE_STATUS, SSL3_MT_CERTIFICATE_VERIFY, SSL3_MT_CHANGE_CIPHER_SPEC, SSL3_MT_FINISHED, SSL3_MT_HELLO_REQUEST, SSL3_MT_NEWSESSION_TICKET, SSL3_MT_SERVER_DONE, SSL3_MT_SERVER_HELLO, SSL3_MT_SERVER_KEY_EXCHANGE, SSL_IS_DTLS, tls_construct_cert_status(), tls_construct_cert_verify(), tls_construct_certificate_request(), tls_construct_change_cipher_spec(), tls_construct_finished(), tls_construct_new_session_ticket(), tls_construct_server_certificate(), tls_construct_server_done(), tls_construct_server_hello(), tls_construct_server_key_exchange(), TLS_ST_SW_CERT, TLS_ST_SW_CERT_REQ, TLS_ST_SW_CERT_STATUS, TLS_ST_SW_CERT_VRFY, TLS_ST_SW_CHANGE, TLS_ST_SW_ENCRYPTED_EXTENSIONS, TLS_ST_SW_FINISHED, TLS_ST_SW_HELLO_REQ, TLS_ST_SW_KEY_EXCH, TLS_ST_SW_SESSION_TICKET, TLS_ST_SW_SRVR_DONE, and TLS_ST_SW_SRVR_HELLO.
ossl_statem_server_max_message_size()
size_t ossl_statem_server_max_message_size (SSL * s)
Definition at line 985 of file statem_srvr.c.
References CCS_MAX_LENGTH, CLIENT_HELLO_MAX_LENGTH, CLIENT_KEY_EXCH_MAX_LENGTH, FINISHED_MAX_LENGTH, KEY_UPDATE_MAX_LENGTH, NEXT_PROTO_MAX_LENGTH, SSL3_RT_MAX_PLAIN_LENGTH, TLS_ST_SR_CERT, TLS_ST_SR_CERT_VRFY, TLS_ST_SR_CHANGE, TLS_ST_SR_CLNT_HELLO, TLS_ST_SR_FINISHED, TLS_ST_SR_KEY_EXCH, TLS_ST_SR_KEY_UPDATE, and TLS_ST_SR_NEXT_PROTO.
ossl_statem_server_post_process_message()
WORK_STATE ossl_statem_server_post_process_message (SSL * s, WORK_STATE wst)
Definition at line 1067 of file statem_srvr.c.
References BIO_clear_retry_flags, BIO_dgram_is_sctp(), BIO_dgram_sctp_msg_waiting(), BIO_set_retry_read, ossl_statem_set_sctp_read_sock(), SSL_get_rbio(), SSL_get_wbio(), SSL_READING, tls_post_process_client_hello(), tls_post_process_client_key_exchange(), TLS_ST_SR_CERT_VRFY, TLS_ST_SR_CLNT_HELLO, TLS_ST_SR_KEY_EXCH, WORK_ERROR, WORK_FINISHED_CONTINUE, and WORK_MORE_A.
ossl_statem_server_post_work()
WORK_STATE ossl_statem_server_post_work (SSL * s, WORK_STATE wst)
Definition at line 712 of file statem_srvr.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_SCTP_ADD_AUTH_KEY, BIO_CTRL_DGRAM_SCTP_NEXT_AUTH_KEY, DTLS1_BAD_VER, dtls1_reset_seq_numbers(), DTLS1_SCTP_AUTH_LABEL, DTLS_ST_SW_HELLO_VERIFY_REQUEST, NULL, ossl_statem_set_error(), SSL3_CC_APPLICATION, SSL3_CC_HANDSHAKE, SSL3_CC_WRITE, SSL3_CHANGE_CIPHER_SERVER_READ, SSL3_CHANGE_CIPHER_SERVER_WRITE, ssl3_init_finished_mac(), SSL_export_keying_material(), SSL_get_wbio(), SSL_IS_DTLS, SSL_IS_TLS13, statem_flush(), tls13_update_key(), TLS_ST_SW_CHANGE, TLS_ST_SW_FINISHED, TLS_ST_SW_HELLO_REQ, TLS_ST_SW_HELLO_RETRY_REQUEST, TLS_ST_SW_KEY_UPDATE, TLS_ST_SW_SESSION_TICKET, TLS_ST_SW_SRVR_DONE, TLS_ST_SW_SRVR_HELLO, WORK_ERROR, WORK_FINISHED_CONTINUE, and WORK_MORE_A.
ossl_statem_server_pre_work()
WORK_STATE ossl_statem_server_pre_work (SSL * s, WORK_STATE wst)
Definition at line 626 of file statem_srvr.c.
References BIO_dgram_is_sctp(), dtls1_clear_sent_buffer(), DTLS_ST_SW_HELLO_VERIFY_REQUEST, dtls_wait_for_dry(), ossl_statem_set_error(), SSL_get_wbio(), SSL_IS_DTLS, SSL_IS_TLS13, tls_finish_handshake(), TLS_ST_OK, TLS_ST_SW_CHANGE, TLS_ST_SW_HELLO_REQ, TLS_ST_SW_SESSION_TICKET, TLS_ST_SW_SRVR_DONE, TLS_ST_SW_SRVR_HELLO, WORK_ERROR, and WORK_FINISHED_CONTINUE.
ossl_statem_server_process_message()
MSG_PROCESS_RETURN ossl_statem_server_process_message (SSL * s, PACKET * pkt)
Definition at line 1025 of file statem_srvr.c.
References MSG_PROCESS_ERROR, tls_process_cert_verify(), tls_process_change_cipher_spec(), tls_process_client_certificate(), tls_process_client_hello(), tls_process_client_key_exchange(), tls_process_finished(), tls_process_key_update(), tls_process_next_proto(), TLS_ST_SR_CERT, TLS_ST_SR_CERT_VRFY, TLS_ST_SR_CHANGE, TLS_ST_SR_CLNT_HELLO, TLS_ST_SR_FINISHED, TLS_ST_SR_KEY_EXCH, TLS_ST_SR_KEY_UPDATE, and TLS_ST_SR_NEXT_PROTO.
ossl_statem_server_read_transition()
int ossl_statem_server_read_transition (SSL * s, int mt)
Definition at line 160 of file statem_srvr.c.
References DTLS_ST_SW_HELLO_VERIFY_REQUEST, NULL, SSL3_AD_HANDSHAKE_FAILURE, SSL3_AD_UNEXPECTED_MESSAGE, SSL3_AL_FATAL, SSL3_MT_CERTIFICATE, SSL3_MT_CERTIFICATE_VERIFY, SSL3_MT_CHANGE_CIPHER_SPEC, SSL3_MT_CLIENT_HELLO, SSL3_MT_CLIENT_KEY_EXCHANGE, SSL3_MT_FINISHED, SSL3_MT_NEXT_PROTO, ssl3_send_alert(), SSL3_VERSION, SSL_F_OSSL_STATEM_SERVER_READ_TRANSITION, SSL_IS_TLS13, SSL_R_PEER_DID_NOT_RETURN_A_CERTIFICATE, SSL_R_UNEXPECTED_MESSAGE, SSL_VERIFY_FAIL_IF_NO_PEER_CERT, SSL_VERIFY_PEER, SSLerr, TLS_ST_BEFORE, TLS_ST_OK, TLS_ST_SR_CERT, TLS_ST_SR_CERT_VRFY, TLS_ST_SR_CHANGE, TLS_ST_SR_CLNT_HELLO, TLS_ST_SR_FINISHED, TLS_ST_SR_KEY_EXCH, TLS_ST_SR_NEXT_PROTO, TLS_ST_SW_FINISHED, and TLS_ST_SW_SRVR_DONE.
ossl_statem_server_write_transition()
WRITE_TRAN ossl_statem_server_write_transition (SSL * s)
Definition at line 491 of file statem_srvr.c.
References SSL_IS_TLS13.
ssl3_check_cert_and_algorithm()
__owur int ssl3_check_cert_and_algorithm (SSL * s)
Definition at line 3234 of file statem_clnt.c.
Referenced by tls_process_initial_server_flight().
ssl_do_client_cert_cb()
__owur int ssl_do_client_cert_cb (SSL * s, X509 ** px509, EVP_PKEY ** ppkey)
Definition at line 3384 of file statem_clnt.c.
References ENGINE_load_ssl_client_cert(), and NULL.
statem_flush()
int statem_flush (SSL * s)
Definition at line 768 of file statem.c.
References BIO_flush, SSL_NOTHING, and SSL_WRITING.
Referenced by ossl_statem_client_post_work(), and ossl_statem_server_post_work().
tls_client_key_exchange_post_work()
__owur int tls_client_key_exchange_post_work (SSL * s)
Definition at line 3051 of file statem_clnt.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_SCTP_ADD_AUTH_KEY, DTLS1_SCTP_AUTH_LABEL, ERR_R_INTERNAL_ERROR, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_clear_free, srp_generate_client_master_secret(), SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_export_keying_material(), SSL_F_TLS_CLIENT_KEY_EXCHANGE_POST_WORK, ssl_generate_master_secret(), SSL_get_wbio(), SSL_IS_DTLS, SSL_kPSK, SSL_kSRP, and SSLerr.
Referenced by ossl_statem_client_post_work().
tls_collect_extensions()
__owur int tls_collect_extensions (SSL * s, PACKET * packet, unsigned int context, RAW_EXTENSION ** res, int * al)
Definition at line 384 of file extensions.c.
References custom_ext_init(), ERR_R_MALLOC_FAILURE, EXT_CLIENT_HELLO, EXT_TLS1_2_SERVER_HELLO, custom_ext_methods::meths_count, NULL, OPENSSL_zalloc, OSSL_NELEM, SSL_AD_INTERNAL_ERROR, SSL_F_TLS_COLLECT_EXTENSIONS, and SSLerr.
tls_construct_cert_status()
__owur int tls_construct_cert_status (SSL * s, WPACKET * pkt)
Definition at line 3447 of file statem_srvr.c.
References SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, and tls_construct_cert_status_body().
Referenced by ossl_statem_server_construct_message().
tls_construct_cert_status_body()
__owur int tls_construct_cert_status_body (SSL * s, WPACKET * pkt)
Definition at line 3435 of file statem_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CERT_STATUS_BODY, SSLerr, WPACKET_put_bytes_u8, and WPACKET_sub_memcpy_u24.
Referenced by tls_construct_cert_status(), and tls_construct_stoc_status_request().
tls_construct_cert_verify()
__owur int tls_construct_cert_verify (SSL * s, WPACKET * pkt)
Definition at line 172 of file statem_lib.c.
References NULL.
Referenced by ossl_statem_client_construct_message(), and ossl_statem_server_construct_message().
tls_construct_certificate_request()
__owur int tls_construct_certificate_request (SSL * s, WPACKET * pkt)
Definition at line 2367 of file statem_srvr.c.
Referenced by ossl_statem_server_construct_message().
tls_construct_change_cipher_spec()
__owur int tls_construct_change_cipher_spec (SSL * s, WPACKET * pkt)
Definition at line 730 of file statem_lib.c.
References ERR_R_INTERNAL_ERROR, SSL3_AL_FATAL, SSL3_MT_CCS, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CHANGE_CIPHER_SPEC, SSLerr, and WPACKET_put_bytes_u8.
Referenced by ossl_statem_client_construct_message(), and ossl_statem_server_construct_message().
tls_construct_client_certificate()
__owur int tls_construct_client_certificate (SSL * s, WPACKET * pkt)
Definition at line 3211 of file statem_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL3_AL_FATAL, ssl3_output_cert_chain(), ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CLIENT_CERTIFICATE, SSL_IS_TLS13, SSLerr, and WPACKET_put_bytes_u8.
Referenced by ossl_statem_client_construct_message().
tls_construct_client_hello()
__owur int tls_construct_client_hello (SSL * s, WPACKET * pkt)
Definition at line 968 of file statem_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL3_RT_MAX_PLAIN_LENGTH, SSL_AD_HANDSHAKE_FAILURE, SSL_F_TLS_CONSTRUCT_CLIENT_HELLO, ssl_get_new_session(), SSL_IS_DTLS, ssl_set_client_hello_version(), ssl_version_supported(), SSLerr, and WPACKET_set_max_size().
Referenced by ossl_statem_client_construct_message().
tls_construct_client_key_exchange()
__owur int tls_construct_client_key_exchange (SSL * s, WPACKET * pkt)
Definition at line 3006 of file statem_clnt.c.
References SSL_PSK.
Referenced by ossl_statem_client_construct_message().
tls_construct_ctos_alpn()
int tls_construct_ctos_alpn (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 342 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_ALPN, SSL_IS_FIRST_HANDSHAKE, SSLerr, TLSEXT_TYPE_application_layer_protocol_negotiation, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_sub_memcpy_u16.
tls_construct_ctos_ec_pt_formats()
int tls_construct_ctos_ec_pt_formats (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 111 of file extensions_clnt.c.
tls_construct_ctos_ems()
int tls_construct_ctos_ems (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 442 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CTOS_EMS, SSLerr, TLSEXT_TYPE_extended_master_secret, and WPACKET_put_bytes_u16.
tls_construct_ctos_etm()
int tls_construct_ctos_etm (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 406 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CTOS_ETM, SSL_OP_NO_ENCRYPT_THEN_MAC, SSLerr, TLSEXT_TYPE_encrypt_then_mac, and WPACKET_put_bytes_u16.
tls_construct_ctos_key_share()
int tls_construct_ctos_key_share (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 575 of file extensions_clnt.c.
References bytestogroup, ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_KEY_SHARE, SSL_R_NO_SUITABLE_KEY_SHARE, SSL_SECOP_CURVE_SUPPORTED, SSLerr, tls1_get_curvelist(), tls_curve_allowed(), TLSEXT_TYPE_key_share, WPACKET_put_bytes_u16, and WPACKET_start_sub_packet_u16.
tls_construct_ctos_npn()
int tls_construct_ctos_npn (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 322 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_NPN, SSL_IS_FIRST_HANDSHAKE, SSLerr, TLSEXT_TYPE_next_proto_neg, and WPACKET_put_bytes_u16.
tls_construct_ctos_padding()
int tls_construct_ctos_padding (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 642 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, F5_WORKAROUND_MAX_MSG_LEN, F5_WORKAROUND_MIN_MSG_LEN, SSL_F_TLS_CONSTRUCT_CTOS_PADDING, SSL_OP_TLSEXT_PADDING, SSLerr, TLSEXT_TYPE_padding, WPACKET_get_total_written(), WPACKET_put_bytes_u16, and WPACKET_sub_allocate_bytes_u16.
tls_construct_ctos_psk()
int tls_construct_ctos_psk (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 689 of file extensions_clnt.c.
References NULL.
tls_construct_ctos_psk_kex_modes()
int tls_construct_ctos_psk_kex_modes (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 506 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CTOS_PSK_KEX_MODES, SSLerr, TLSEXT_KEX_MODE_FLAG_KE, TLSEXT_KEX_MODE_FLAG_KE_DHE, TLSEXT_KEX_MODE_KE, TLSEXT_KEX_MODE_KE_DHE, TLSEXT_TYPE_psk_kex_modes, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_put_bytes_u8, WPACKET_start_sub_packet_u16, and WPACKET_start_sub_packet_u8.
tls_construct_ctos_renegotiate()
int tls_construct_ctos_renegotiate (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 15 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CTOS_RENEGOTIATE, SSLerr, TLSEXT_TYPE_renegotiate, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_sub_memcpy_u8.
tls_construct_ctos_sct()
int tls_construct_ctos_sct (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 422 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_SCT, SSLerr, TLSEXT_TYPE_signed_certificate_timestamp, and WPACKET_put_bytes_u16.
tls_construct_ctos_server_name()
int tls_construct_ctos_server_name (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 34 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_SERVER_NAME, SSLerr, TLSEXT_NAMETYPE_host_name, TLSEXT_TYPE_server_name, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_put_bytes_u8, WPACKET_start_sub_packet_u16, and WPACKET_sub_memcpy_u16.
tls_construct_ctos_session_ticket()
int tls_construct_ctos_session_ticket (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 186 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, OPENSSL_malloc, SSL_F_TLS_CONSTRUCT_CTOS_SESSION_TICKET, SSLerr, TLS1_3_VERSION, tls_use_ticket(), TLSEXT_TYPE_session_ticket, WPACKET_put_bytes_u16, and WPACKET_sub_memcpy_u16.
tls_construct_ctos_sig_algs()
int tls_construct_ctos_sig_algs (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 228 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SSL_CLIENT_USE_SIGALGS, SSL_F_TLS_CONSTRUCT_CTOS_SIG_ALGS, SSLerr, tls12_copy_sigalgs(), tls12_get_psigalgs(), TLSEXT_TYPE_signature_algorithms, WPACKET_close(), WPACKET_put_bytes_u16, and WPACKET_start_sub_packet_u16.
tls_construct_ctos_srp()
int tls_construct_ctos_srp (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 59 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_SRP, SSLerr, TLSEXT_TYPE_srp, WPACKET_close(), WPACKET_FLAGS_NON_ZERO_LENGTH, WPACKET_memcpy(), WPACKET_put_bytes_u16, WPACKET_set_flags(), WPACKET_start_sub_packet_u16, and WPACKET_start_sub_packet_u8.
tls_construct_ctos_status_request()
int tls_construct_ctos_status_request (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 254 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_CTOS_STATUS_REQUEST, SSLerr, TLSEXT_STATUSTYPE_ocsp, TLSEXT_TYPE_status_request, WPACKET_allocate_bytes(), WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_put_bytes_u8, WPACKET_start_sub_packet_u16, and WPACKET_sub_allocate_bytes_u16.
tls_construct_ctos_supported_groups()
int tls_construct_ctos_supported_groups (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 135 of file extensions_clnt.c.
References NULL.
tls_construct_ctos_supported_versions()
int tls_construct_ctos_supported_versions (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 454 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CTOS_SUPPORTED_VERSIONS, ssl_get_client_min_max_version(), SSLerr, TLS1_3_VERSION, TLS1_3_VERSION_DRAFT, TLSEXT_TYPE_supported_versions, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_start_sub_packet_u8.
tls_construct_ctos_use_srtp()
int tls_construct_ctos_use_srtp (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 366 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, SRTP_PROTECTION_PROFILE::id, NULL, SSL_F_TLS_CONSTRUCT_CTOS_USE_SRTP, SSLerr, STACK_OF, TLSEXT_TYPE_use_srtp, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_put_bytes_u8, and WPACKET_start_sub_packet_u16.
tls_construct_extensions()
__owur int tls_construct_extensions (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 587 of file extensions.c.
References EXTENSION_DEFINITION::construct_ctos, EXTENSION_DEFINITION::construct_stoc, EXTENSION_DEFINITION::context, custom_ext_add(), custom_ext_init(), ERR_R_INTERNAL_ERROR, EXT_CLIENT_HELLO, EXT_SSL3_ALLOWED, EXT_TLS1_2_AND_BELOW_ONLY, EXT_TLS1_2_SERVER_HELLO, EXT_TLS1_3_ONLY, EXT_TLS_IMPLEMENTATION_ONLY, NULL, OSSL_NELEM, SSL3_VERSION, SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_EXTENSIONS, ssl_get_client_min_max_version(), SSL_IS_DTLS, SSL_IS_TLS13, SSLerr, TLS1_3_VERSION, WPACKET_close(), WPACKET_FLAGS_ABANDON_ON_ZERO_LENGTH, WPACKET_set_flags(), and WPACKET_start_sub_packet_u16.
Referenced by tls_construct_server_hello().
tls_construct_finished()
__owur int tls_construct_finished (SSL * s, WPACKET * pkt)
Definition at line 439 of file statem_lib.c.
References ERR_R_INTERNAL_ERROR, EVP_MAX_MD_SIZE, MASTER_SECRET_LABEL, OPENSSL_assert, SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_FINISHED, SSL_IS_TLS13, ssl_log_secret(), SSLerr, and WPACKET_memcpy().
Referenced by ossl_statem_client_construct_message(), and ossl_statem_server_construct_message().
tls_construct_key_update()
__owur int tls_construct_key_update (SSL * s, WPACKET * pkt)
Definition at line 498 of file statem_lib.c.
References ERR_R_INTERNAL_ERROR, SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_KEY_UPDATE, SSL_KEY_UPDATE_NONE, SSLerr, and WPACKET_put_bytes_u8.
Referenced by ossl_statem_client_construct_message().
tls_construct_new_session_ticket()
__owur int tls_construct_new_session_ticket (SSL * s, WPACKET * pkt)
Definition at line 3259 of file statem_srvr.c.
References ctx, len, and NULL.
Referenced by ossl_statem_server_construct_message().
tls_construct_next_proto()
__owur int tls_construct_next_proto (SSL * s, WPACKET * pkt)
Definition at line 3308 of file statem_clnt.c.
References ERR_R_INTERNAL_ERROR, len, NULL, SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_NEXT_PROTO, SSLerr, WPACKET_sub_allocate_bytes_u8, and WPACKET_sub_memcpy_u8.
Referenced by ossl_statem_client_construct_message().
tls_construct_server_certificate()
__owur int tls_construct_server_certificate (SSL * s, WPACKET * pkt)
Definition at line 3235 of file statem_srvr.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL3_AL_FATAL, ssl3_output_cert_chain(), ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_SERVER_CERTIFICATE, SSL_IS_TLS13, SSLerr, and WPACKET_put_bytes_u8.
Referenced by ossl_statem_server_construct_message().
tls_construct_server_done()
__owur int tls_construct_server_done (SSL * s, WPACKET * pkt)
Definition at line 2015 of file statem_srvr.c.
References SSL3_AL_FATAL, ssl3_digest_cached_records(), ssl3_send_alert(), and SSL_AD_INTERNAL_ERROR.
Referenced by ossl_statem_server_construct_message().
tls_construct_server_hello()
__owur int tls_construct_server_hello (SSL * s, WPACKET * pkt)
Definition at line 1934 of file statem_srvr.c.
References ERR_R_INTERNAL_ERROR, EXT_TLS1_2_SERVER_HELLO, EXT_TLS1_3_SERVER_HELLO, len, NULL, SSL3_AL_FATAL, ssl3_digest_cached_records(), SSL3_RANDOM_SIZE, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_SERVER_HELLO, SSL_IS_TLS13, SSL_SESS_CACHE_SERVER, SSL_VERIFY_PEER, SSLerr, TLS1_3_VERSION_DRAFT, tls_construct_extensions(), WPACKET_memcpy(), WPACKET_put_bytes_u16, WPACKET_put_bytes_u8, and WPACKET_sub_memcpy_u8.
Referenced by ossl_statem_server_construct_message().
tls_construct_server_key_exchange()
__owur int tls_construct_server_key_exchange (SSL * s, WPACKET * pkt)
Definition at line 2026 of file statem_srvr.c.
References EVP_MD_CTX_new(), NULL, SIGALG_LOOKUP::sigalg, SSL_AD_INTERNAL_ERROR, and type.
Referenced by ossl_statem_server_construct_message().
tls_construct_stoc_alpn()
int tls_construct_stoc_alpn (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 911 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_STOC_ALPN, SSLerr, TLSEXT_TYPE_application_layer_protocol_negotiation, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_sub_memcpy_u8.
tls_construct_stoc_cryptopro_bug()
int tls_construct_stoc_cryptopro_bug (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1068 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_STOC_CRYPTOPRO_BUG, SSL_get_options(), SSL_OP_CRYPTOPRO_TLSEXT_BUG, SSLerr, and WPACKET_memcpy().
tls_construct_stoc_ec_pt_formats()
int tls_construct_stoc_ec_pt_formats (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 805 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_aECDSA, SSL_F_TLS_CONSTRUCT_STOC_EC_PT_FORMATS, SSL_kECDHE, SSLerr, tls1_get_formatlist(), TLSEXT_TYPE_ec_point_formats, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_sub_memcpy_u8.
tls_construct_stoc_ems()
int tls_construct_stoc_ems (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 980 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_STOC_EMS, SSLerr, TLS1_FLAGS_RECEIVED_EXTMS, TLSEXT_TYPE_extended_master_secret, and WPACKET_put_bytes_u16.
tls_construct_stoc_etm()
int tls_construct_stoc_etm (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 953 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_AEAD, SSL_eGOST2814789CNT, SSL_eGOST2814789CNT12, SSL_F_TLS_CONSTRUCT_STOC_ETM, SSL_RC4, SSLerr, TLSEXT_TYPE_encrypt_then_mac, and WPACKET_put_bytes_u16.
tls_construct_stoc_key_share()
int tls_construct_stoc_key_share (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 995 of file extensions_srvr.c.
References ERR_R_EC_LIB, ERR_R_INTERNAL_ERROR, ERR_R_MALLOC_FAILURE, EVP_PKEY_free(), EVP_PKEY_get1_tls_encodedpoint(), NULL, OPENSSL_free, SSL_AD_INTERNAL_ERROR, ssl_derive(), SSL_F_TLS_CONSTRUCT_STOC_KEY_SHARE, ssl_generate_pkey(), SSLerr, tls13_generate_handshake_secret(), TLSEXT_TYPE_key_share, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_sub_memcpy_u16.
tls_construct_stoc_next_proto_neg()
int tls_construct_stoc_next_proto_neg (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 882 of file extensions_srvr.c.
tls_construct_stoc_psk()
int tls_construct_stoc_psk (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1093 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_STOC_PSK, SSLerr, TLSEXT_TYPE_psk, WPACKET_close(), WPACKET_put_bytes_u16, and WPACKET_start_sub_packet_u16.
tls_construct_stoc_renegotiate()
int tls_construct_stoc_renegotiate (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 766 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_STOC_RENEGOTIATE, SSLerr, TLSEXT_TYPE_renegotiate, WPACKET_close(), WPACKET_memcpy(), WPACKET_put_bytes_u16, WPACKET_start_sub_packet_u16, and WPACKET_start_sub_packet_u8.
tls_construct_stoc_server_name()
int tls_construct_stoc_server_name (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 788 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_STOC_SERVER_NAME, SSLerr, TLSEXT_TYPE_server_name, and WPACKET_put_bytes_u16.
tls_construct_stoc_session_ticket()
int tls_construct_stoc_session_ticket (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 831 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_STOC_SESSION_TICKET, SSLerr, tls_use_ticket(), TLSEXT_TYPE_session_ticket, and WPACKET_put_bytes_u16.
tls_construct_stoc_status_request()
int tls_construct_stoc_status_request (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 850 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_STOC_STATUS_REQUEST, SSL_IS_TLS13, SSLerr, tls_construct_cert_status_body(), TLSEXT_TYPE_status_request, WPACKET_close(), WPACKET_put_bytes_u16, and WPACKET_start_sub_packet_u16.
tls_construct_stoc_use_srtp()
int tls_construct_stoc_use_srtp (SSL * s, WPACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 933 of file extensions_srvr.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_F_TLS_CONSTRUCT_STOC_USE_SRTP, SSLerr, TLSEXT_TYPE_use_srtp, WPACKET_close(), WPACKET_put_bytes_u16, WPACKET_put_bytes_u8, and WPACKET_start_sub_packet_u16.
tls_finish_handshake()
__owur WORK_STATE tls_finish_handshake (SSL * s, WORK_STATE wst, int clearbufs)
Definition at line 884 of file statem_lib.c.
References BIO_dgram_is_sctp(), cb, NULL, SSL_get_wbio(), SSL_IS_DTLS, and type.
Referenced by ossl_statem_client_pre_work(), and ossl_statem_server_pre_work().
tls_get_message_body()
__owur int tls_get_message_body (SSL * s, size_t * len)
Definition at line 1061 of file statem_lib.c.
References NULL, SSL3_MT_CHANGE_CIPHER_SPEC, SSL3_MT_FINISHED, SSL3_RT_HANDSHAKE, and SSL_READING.
tls_get_message_header()
__owur int tls_get_message_header (SSL * s, int * mt)
Definition at line 959 of file statem_lib.c.
References n2l3, RECORD_LAYER_get_rrec_length(), RECORD_LAYER_is_sslv2_record(), SSL3_AL_FATAL, SSL3_HM_HEADER_LENGTH, SSL3_MT_CCS, SSL3_MT_CHANGE_CIPHER_SPEC, SSL3_MT_HELLO_REQUEST, SSL3_RT_CHANGE_CIPHER_SPEC, SSL3_RT_HANDSHAKE, ssl3_send_alert(), SSL_AD_ILLEGAL_PARAMETER, SSL_AD_UNEXPECTED_MESSAGE, SSL_F_TLS_GET_MESSAGE_HEADER, SSL_R_BAD_CHANGE_CIPHER_SPEC, SSL_R_CCS_RECEIVED_EARLY, SSL_R_EXCESSIVE_MESSAGE_SIZE, SSL_READING, SSLerr, and TLS_ST_OK.
tls_parse_all_extensions()
__owur int tls_parse_all_extensions (SSL * s, int context, RAW_EXTENSION * exts, X509 * x, size_t chainidx, int * al)
Definition at line 545 of file extensions.c.
References EXTENSION_DEFINITION::context, EXT_CLIENT_HELLO, EXT_TLS1_2_SERVER_HELLO, EXTENSION_DEFINITION::final, NULL, OSSL_NELEM, and tls_parse_extension().
tls_parse_ctos_alpn()
int tls_parse_ctos_alpn (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 342 of file extensions_srvr.c.
References SSL_IS_FIRST_HANDSHAKE.
tls_parse_ctos_ec_pt_formats()
int tls_parse_ctos_ec_pt_formats (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 166 of file extensions_srvr.c.
tls_parse_ctos_ems()
int tls_parse_ctos_ems (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 650 of file extensions_srvr.c.
tls_parse_ctos_etm()
int tls_parse_ctos_etm (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 450 of file extensions_srvr.c.
References SSL_OP_NO_ENCRYPT_THEN_MAC.
tls_parse_ctos_key_share()
int tls_parse_ctos_key_share (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 493 of file extensions_srvr.c.
tls_parse_ctos_npn()
int tls_parse_ctos_npn (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 323 of file extensions_srvr.c.
References SSL_IS_FIRST_HANDSHAKE.
tls_parse_ctos_psk()
int tls_parse_ctos_psk (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 664 of file extensions_srvr.c.
References NULL.
tls_parse_ctos_psk_kex_modes()
int tls_parse_ctos_psk_kex_modes (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 464 of file extensions_srvr.c.
tls_parse_ctos_renegotiate()
int tls_parse_ctos_renegotiate (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 17 of file extensions_srvr.c.
References data.
tls_parse_ctos_server_name()
int tls_parse_ctos_server_name (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 76 of file extensions_srvr.c.
tls_parse_ctos_session_ticket()
int tls_parse_ctos_session_ticket (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 190 of file extensions_srvr.c.
tls_parse_ctos_sig_algs()
int tls_parse_ctos_sig_algs (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 204 of file extensions_srvr.c.
tls_parse_ctos_srp()
int tls_parse_ctos_srp (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 141 of file extensions_srvr.c.
tls_parse_ctos_status_request()
int tls_parse_ctos_status_request (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 224 of file extensions_srvr.c.
References NULL.
tls_parse_ctos_supported_groups()
int tls_parse_ctos_supported_groups (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 623 of file extensions_srvr.c.
tls_parse_ctos_use_srtp()
int tls_parse_ctos_use_srtp (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 379 of file extensions_srvr.c.
References NULL, and STACK_OF.
tls_parse_extension()
__owur int tls_parse_extension (SSL * s, TLSEXT_INDEX idx, int context, RAW_EXTENSION * exts, X509 * x, size_t chainidx, int * al)
Definition at line 475 of file extensions.c.
Referenced by tls_parse_all_extensions().
tls_parse_stoc_alpn()
int tls_parse_stoc_alpn (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1076 of file extensions_clnt.c.
References len, and SSL_AD_UNSUPPORTED_EXTENSION.
tls_parse_stoc_ec_pt_formats()
int tls_parse_stoc_ec_pt_formats (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 883 of file extensions_clnt.c.
tls_parse_stoc_ems()
int tls_parse_stoc_ems (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1180 of file extensions_clnt.c.
References SSL_SESS_FLAG_EXTMS, and TLS1_FLAGS_RECEIVED_EXTMS.
tls_parse_stoc_etm()
int tls_parse_stoc_etm (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1168 of file extensions_clnt.c.
References SSL_AEAD, SSL_OP_NO_ENCRYPT_THEN_MAC, and SSL_RC4.
tls_parse_stoc_key_share()
int tls_parse_stoc_key_share (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1190 of file extensions_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL_AD_INTERNAL_ERROR, SSL_F_TLS_PARSE_STOC_KEY_SHARE, and SSLerr.
tls_parse_stoc_npn()
int tls_parse_stoc_npn (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1025 of file extensions_clnt.c.
References NULL, SSL_AD_UNSUPPORTED_EXTENSION, and SSL_IS_FIRST_HANDSHAKE.
tls_parse_stoc_psk()
int tls_parse_stoc_psk (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1297 of file extensions_clnt.c.
tls_parse_stoc_renegotiate()
int tls_parse_stoc_renegotiate (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 801 of file extensions_clnt.c.
References data.
tls_parse_stoc_sct()
int tls_parse_stoc_sct (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 971 of file extensions_clnt.c.
References NULL.
tls_parse_stoc_server_name()
int tls_parse_stoc_server_name (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 859 of file extensions_clnt.c.
References NULL.
tls_parse_stoc_session_ticket()
int tls_parse_stoc_session_ticket (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 918 of file extensions_clnt.c.
References NULL.
tls_parse_stoc_status_request()
int tls_parse_stoc_status_request (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 940 of file extensions_clnt.c.
References SSL_IS_TLS13, and TLSEXT_STATUSTYPE_nothing.
tls_parse_stoc_use_srtp()
int tls_parse_stoc_use_srtp (SSL * s, PACKET * pkt, unsigned int context, X509 * x, size_t chainidx, int * al)
Definition at line 1114 of file extensions_clnt.c.
References STACK_OF.
tls_post_process_client_hello()
__owur WORK_STATE tls_post_process_client_hello (SSL * s, WORK_STATE wst)
Definition at line 1830 of file statem_srvr.c.
References SSL_AD_HANDSHAKE_FAILURE.
Referenced by ossl_statem_server_post_process_message().
tls_post_process_client_key_exchange()
__owur WORK_STATE tls_post_process_client_key_exchange (SSL * s, WORK_STATE wst)
Definition at line 2997 of file statem_srvr.c.
References BIO_clear_retry_flags, BIO_ctrl(), BIO_CTRL_DGRAM_SCTP_ADD_AUTH_KEY, BIO_dgram_is_sctp(), BIO_dgram_sctp_msg_waiting(), BIO_set_retry_read, DTLS1_SCTP_AUTH_LABEL, ERR_R_INTERNAL_ERROR, NULL, ossl_statem_set_error(), ossl_statem_set_sctp_read_sock(), ssl3_digest_cached_records(), SSL_export_keying_material(), SSL_F_TLS_POST_PROCESS_CLIENT_KEY_EXCHANGE, SSL_get_rbio(), SSL_get_wbio(), SSL_IS_DTLS, SSL_READING, SSLerr, WORK_ERROR, WORK_FINISHED_CONTINUE, WORK_MORE_A, and WORK_MORE_B.
Referenced by ossl_statem_server_post_process_message().
tls_prepare_client_certificate()
__owur WORK_STATE tls_prepare_client_certificate (SSL * s, WORK_STATE wst)
Definition at line 3136 of file statem_clnt.c.
References NULL, ossl_statem_set_error(), SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_NOTHING, SSL_X509_LOOKUP, and WORK_MORE_A.
Referenced by ossl_statem_client_post_process_message().
tls_process_cert_status()
__owur MSG_PROCESS_RETURN tls_process_cert_status (SSL * s, PACKET * pkt)
Definition at line 2493 of file statem_clnt.c.
References MSG_PROCESS_CONTINUE_READING, MSG_PROCESS_ERROR, ossl_statem_set_error(), SSL3_AL_FATAL, ssl3_send_alert(), and tls_process_cert_status_body().
tls_process_cert_status_body()
__owur int tls_process_cert_status_body (SSL * s, PACKET * pkt, int * al)
Definition at line 2458 of file statem_clnt.c.
References type.
Referenced by tls_process_cert_status().
tls_process_cert_verify()
__owur MSG_PROCESS_RETURN tls_process_cert_verify (SSL * s, PACKET * pkt)
Definition at line 276 of file statem_lib.c.
References data, NULL, and SSL_AD_INTERNAL_ERROR.
Referenced by ossl_statem_server_process_message().
tls_process_certificate_request()
__owur MSG_PROCESS_RETURN tls_process_certificate_request (SSL * s, PACKET * pkt)
Definition at line 2196 of file statem_clnt.c.
tls_process_change_cipher_spec()
__owur MSG_PROCESS_RETURN tls_process_change_cipher_spec (SSL * s, PACKET * pkt)
Definition at line 585 of file statem_lib.c.
Referenced by ossl_statem_server_process_message().
tls_process_client_certificate()
__owur MSG_PROCESS_RETURN tls_process_client_certificate (SSL * s, PACKET * pkt)
Definition at line 3074 of file statem_srvr.c.
References SSL_AD_INTERNAL_ERROR.
Referenced by ossl_statem_server_process_message().
tls_process_client_hello()
__owur MSG_PROCESS_RETURN tls_process_client_hello (SSL * s, PACKET * pkt)
Definition at line 1223 of file statem_srvr.c.
References SSL_AD_INTERNAL_ERROR.
Referenced by ossl_statem_server_process_message().
tls_process_client_key_exchange()
__owur MSG_PROCESS_RETURN tls_process_client_key_exchange (SSL * s, PACKET * pkt)
Definition at line 2938 of file statem_srvr.c.
References SSL_PSK.
Referenced by ossl_statem_server_process_message().
tls_process_finished()
__owur MSG_PROCESS_RETURN tls_process_finished (SSL * s, PACKET * pkt)
Definition at line 652 of file statem_lib.c.
References SSL_AD_INTERNAL_ERROR, SSL_AD_UNEXPECTED_MESSAGE, SSL_F_TLS_PROCESS_FINISHED, SSL_IS_TLS13, SSL_R_GOT_A_FIN_BEFORE_A_CCS, and SSLerr.
Referenced by ossl_statem_server_process_message().
tls_process_hello_req()
__owur MSG_PROCESS_RETURN tls_process_hello_req (SSL * s, PACKET * pkt)
Definition at line 3331 of file statem_clnt.c.
tls_process_initial_server_flight()
__owur int tls_process_initial_server_flight (SSL * s, int * al)
Definition at line 2512 of file statem_clnt.c.
References NULL, ssl3_check_cert_and_algorithm(), SSL_AD_HANDSHAKE_FAILURE, and TLSEXT_STATUSTYPE_nothing.
tls_process_key_exchange()
__owur MSG_PROCESS_RETURN tls_process_key_exchange (SSL * s, PACKET * pkt)
Definition at line 2016 of file statem_clnt.c.
References NULL.
tls_process_key_update()
__owur MSG_PROCESS_RETURN tls_process_key_update (SSL * s, PACKET * pkt)
Definition at line 513 of file statem_lib.c.
References MAX_KEY_UPDATE_MESSAGES, SSL_AD_ILLEGAL_PARAMETER, SSL_F_TLS_PROCESS_KEY_UPDATE, SSL_R_TOO_MANY_KEY_UPDATES, and SSLerr.
Referenced by ossl_statem_server_process_message().
tls_process_new_session_ticket()
__owur MSG_PROCESS_RETURN tls_process_new_session_ticket (SSL * s, PACKET * pkt)
Definition at line 2324 of file statem_clnt.c.
References NULL, and SSL_AD_DECODE_ERROR.
tls_process_next_proto()
__owur MSG_PROCESS_RETURN tls_process_next_proto (SSL * s, PACKET * pkt)
Definition at line 3462 of file statem_srvr.c.
Referenced by ossl_statem_server_process_message().
tls_process_server_certificate()
__owur MSG_PROCESS_RETURN tls_process_server_certificate (SSL * s, PACKET * pkt)
Definition at line 1542 of file statem_clnt.c.
tls_process_server_done()
__owur MSG_PROCESS_RETURN tls_process_server_done (SSL * s, PACKET * pkt)
Definition at line 2558 of file statem_clnt.c.
References SSL_AD_INTERNAL_ERROR.
tls_process_server_hello()
__owur MSG_PROCESS_RETURN tls_process_server_hello (SSL * s, PACKET * pkt)
Definition at line 1171 of file statem_clnt.c.
References STACK_OF.
Referenced by ossl_statem_client_process_message().
tls_psk_do_binder()
__owur int tls_psk_do_binder (SSL * s, const EVP_MD * md, const unsigned char * msgstart, size_t binderoffset, const unsigned char * binderin, unsigned char * binderout, SSL_SESSION * sess, int sign)
Definition at line 1093 of file extensions.c.