ssl/statem/statem_lib.c File Reference
statem_lib.c File Reference
#include <limits.h>
#include <string.h>
#include <stdio.h>
#include "../ssl_locl.h"
#include "statem_locl.h"
#include <openssl/buffer.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
Data Structures
struct version_info
Macros
#define TLS13_TBS_START_SIZE 64
#define TLS13_TBS_PREAMBLE_SIZE (TLS13_TBS_START_SIZE + 33 + 1)
Functions
int ssl3_do_write (SSL *s, int type)
int tls_close_construct_packet (SSL *s, WPACKET *pkt, int htype)
int tls_setup_handshake (SSL *s)
int tls_construct_cert_verify (SSL *s, WPACKET *pkt)
MSG_PROCESS_RETURN tls_process_cert_verify (SSL *s, PACKET *pkt)
int tls_construct_finished (SSL *s, WPACKET *pkt)
int tls_construct_key_update (SSL *s, WPACKET *pkt)
MSG_PROCESS_RETURN tls_process_key_update (SSL *s, PACKET *pkt)
MSG_PROCESS_RETURN tls_process_change_cipher_spec (SSL *s, PACKET *pkt)
MSG_PROCESS_RETURN tls_process_finished (SSL *s, PACKET *pkt)
int tls_construct_change_cipher_spec (SSL *s, WPACKET *pkt)
unsigned long ssl3_output_cert_chain (SSL *s, WPACKET *pkt, CERT_PKEY *cpk, int *al)
WORK_STATE tls_finish_handshake (SSL *s, WORK_STATE wst, int clearbufs)
int tls_get_message_header (SSL *s, int *mt)
int tls_get_message_body (SSL *s, size_t *len)
int ssl_cert_type (const X509 *x, const EVP_PKEY *pk)
int ssl_verify_alarm_type (long type)
int ssl_allow_compression (SSL *s)
int ssl_version_supported (const SSL *s, int version)
int ssl_check_version_downgrade (SSL *s)
int ssl_set_version_bound (int method_version, int version, int *bound)
int ssl_choose_server_version (SSL *s, CLIENTHELLO_MSG *hello)
int ssl_choose_client_version (SSL *s, int version)
int ssl_get_client_min_max_version (const SSL *s, int *min_version, int *max_version)
int ssl_set_client_hello_version (SSL *s)
int check_in_list (SSL *s, unsigned int group_id, const unsigned char *groups, size_t num_groups, int checkallow)
Macro Definition Documentation
TLS13_TBS_PREAMBLE_SIZE
#define TLS13_TBS_PREAMBLE_SIZE (TLS13_TBS_START_SIZE + 33 + 1)
Definition at line 123 of file statem_lib.c.
TLS13_TBS_START_SIZE
#define TLS13_TBS_START_SIZE 64
Definition at line 122 of file statem_lib.c.
Function Documentation
check_in_list()
int check_in_list (SSL * s, unsigned int group_id, const unsigned char * groups, size_t num_groups, int checkallow)
Definition at line 1810 of file statem_lib.c.
References NULL, SSL_SECOP_CURVE_CHECK, and tls_curve_allowed().
ssl3_do_write()
int ssl3_do_write (SSL * s, int type)
Definition at line 30 of file statem_lib.c.
Referenced by ssl3_handshake_write().
ssl3_output_cert_chain()
unsigned long ssl3_output_cert_chain (SSL * s, WPACKET * pkt, CERT_PKEY * cpk, int * al)
Definition at line 864 of file statem_lib.c.
References SSL_AD_INTERNAL_ERROR, and WPACKET_start_sub_packet_u24.
Referenced by tls_construct_client_certificate(), and tls_construct_server_certificate().
ssl_allow_compression()
int ssl_allow_compression (SSL * s)
Definition at line 1222 of file statem_lib.c.
References NULL, SSL_OP_NO_COMPRESSION, SSL_SECOP_COMPRESSION, and ssl_security().
Referenced by ssl3_setup_read_buffer(), and ssl3_setup_write_buffer().
ssl_cert_type()
int ssl_cert_type (const X509 * x, const EVP_PKEY * pk)
Definition at line 1126 of file statem_lib.c.
References EVP_PKEY_DSA, EVP_PKEY_EC, EVP_PKEY_id(), EVP_PKEY_RSA, NID_id_GostR3410_2001, NID_id_GostR3410_2012_256, NID_id_GostR3410_2012_512, NULL, SSL_PKEY_DSA_SIGN, SSL_PKEY_ECC, SSL_PKEY_GOST01, SSL_PKEY_GOST12_256, SSL_PKEY_GOST12_512, SSL_PKEY_RSA, and X509_get0_pubkey().
ssl_check_version_downgrade()
int ssl_check_version_downgrade (SSL * s)
Definition at line 1377 of file statem_lib.c.
ssl_choose_client_version()
int ssl_choose_client_version (SSL * s, int version)
Definition at line 1622 of file statem_lib.c.
References SSL_R_WRONG_SSL_VERSION, TLS1_3_VERSION, TLS1_3_VERSION_DRAFT, and TLS_ANY_VERSION.
ssl_choose_server_version()
int ssl_choose_server_version (SSL * s, CLIENTHELLO_MSG * hello)
Definition at line 1476 of file statem_lib.c.
References CLIENTHELLO_MSG::legacy_version, and SSL_IS_TLS13.
ssl_get_client_min_max_version()
int ssl_get_client_min_max_version (const SSL * s, int * min_version, int * max_version)
Definition at line 1693 of file statem_lib.c.
References NULL, TLS_ANY_VERSION, and version_info::version.
Referenced by ssl_set_client_disabled(), tls_construct_ctos_supported_versions(), and tls_construct_extensions().
ssl_set_client_hello_version()
int ssl_set_client_hello_version (SSL * s)
Definition at line 1784 of file statem_lib.c.
Referenced by tls_construct_client_hello().
ssl_set_version_bound()
int ssl_set_version_bound (int method_version, int version, int * bound)
Definition at line 1422 of file statem_lib.c.
References DTLS1_BAD_VER, DTLS_ANY_VERSION, DTLS_MAX_VERSION, DTLS_VERSION_GT, DTLS_VERSION_LT, TLS_ANY_VERSION, and TLS_MAX_VERSION.
Referenced by SSL_ctrl(), and SSL_CTX_ctrl().
ssl_verify_alarm_type()
int ssl_verify_alarm_type (long type)
Definition at line 1153 of file statem_lib.c.
References SSL_AD_BAD_CERTIFICATE, SSL_AD_CERTIFICATE_EXPIRED, SSL_AD_CERTIFICATE_REVOKED, SSL_AD_CERTIFICATE_UNKNOWN, SSL_AD_DECRYPT_ERROR, SSL_AD_HANDSHAKE_FAILURE, SSL_AD_INTERNAL_ERROR, SSL_AD_UNKNOWN_CA, SSL_AD_UNSUPPORTED_CERTIFICATE, X509_V_ERR_APPLICATION_VERIFICATION, X509_V_ERR_CA_KEY_TOO_SMALL, X509_V_ERR_CA_MD_TOO_WEAK, X509_V_ERR_CERT_CHAIN_TOO_LONG, X509_V_ERR_CERT_HAS_EXPIRED, X509_V_ERR_CERT_NOT_YET_VALID, X509_V_ERR_CERT_REJECTED, X509_V_ERR_CERT_REVOKED, X509_V_ERR_CERT_SIGNATURE_FAILURE, X509_V_ERR_CERT_UNTRUSTED, X509_V_ERR_CRL_HAS_EXPIRED, X509_V_ERR_CRL_NOT_YET_VALID, X509_V_ERR_CRL_SIGNATURE_FAILURE, X509_V_ERR_DANE_NO_MATCH, X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT, X509_V_ERR_EE_KEY_TOO_SMALL, X509_V_ERR_EMAIL_MISMATCH, X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD, X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD, X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD, X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD, X509_V_ERR_HOSTNAME_MISMATCH, X509_V_ERR_INVALID_CA, X509_V_ERR_INVALID_CALL, X509_V_ERR_INVALID_PURPOSE, X509_V_ERR_IP_ADDRESS_MISMATCH, X509_V_ERR_OUT_OF_MEM, X509_V_ERR_PATH_LENGTH_EXCEEDED, X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN, X509_V_ERR_STORE_LOOKUP, X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY, X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE, X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE, X509_V_ERR_UNABLE_TO_GET_CRL, X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER, X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT, X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY, X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE, and X509_V_ERR_UNSPECIFIED.
ssl_version_supported()
int ssl_version_supported (const SSL * s, int version)
Definition at line 1339 of file statem_lib.c.
Referenced by tls_construct_client_hello().
tls_close_construct_packet()
int tls_close_construct_packet (SSL * s, WPACKET * pkt, int htype)
Definition at line 61 of file statem_lib.c.
References SSL3_MT_CHANGE_CIPHER_SPEC, WPACKET_close(), and WPACKET_get_length().
tls_construct_cert_verify()
int tls_construct_cert_verify (SSL * s, WPACKET * pkt)
Definition at line 172 of file statem_lib.c.
References NULL.
Referenced by ossl_statem_client_construct_message(), and ossl_statem_server_construct_message().
tls_construct_change_cipher_spec()
int tls_construct_change_cipher_spec (SSL * s, WPACKET * pkt)
Definition at line 730 of file statem_lib.c.
References ERR_R_INTERNAL_ERROR, SSL3_AL_FATAL, SSL3_MT_CCS, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CHANGE_CIPHER_SPEC, SSLerr, and WPACKET_put_bytes_u8.
Referenced by ossl_statem_client_construct_message(), and ossl_statem_server_construct_message().
tls_construct_finished()
int tls_construct_finished (SSL * s, WPACKET * pkt)
Definition at line 439 of file statem_lib.c.
References ERR_R_INTERNAL_ERROR, EVP_MAX_MD_SIZE, MASTER_SECRET_LABEL, OPENSSL_assert, SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_FINISHED, SSL_IS_TLS13, ssl_log_secret(), SSLerr, and WPACKET_memcpy().
Referenced by ossl_statem_client_construct_message(), and ossl_statem_server_construct_message().
tls_construct_key_update()
int tls_construct_key_update (SSL * s, WPACKET * pkt)
Definition at line 498 of file statem_lib.c.
References ERR_R_INTERNAL_ERROR, SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_KEY_UPDATE, SSL_KEY_UPDATE_NONE, SSLerr, and WPACKET_put_bytes_u8.
Referenced by ossl_statem_client_construct_message().
tls_finish_handshake()
WORK_STATE tls_finish_handshake (SSL * s, WORK_STATE wst, int clearbufs)
Definition at line 884 of file statem_lib.c.
References BIO_dgram_is_sctp(), cb, NULL, SSL_get_wbio(), SSL_IS_DTLS, and type.
Referenced by ossl_statem_client_pre_work(), and ossl_statem_server_pre_work().
tls_get_message_body()
int tls_get_message_body (SSL * s, size_t * len)
Definition at line 1061 of file statem_lib.c.
References NULL, SSL3_MT_CHANGE_CIPHER_SPEC, SSL3_MT_FINISHED, SSL3_RT_HANDSHAKE, and SSL_READING.
tls_get_message_header()
int tls_get_message_header (SSL * s, int * mt)
Definition at line 959 of file statem_lib.c.
References n2l3, RECORD_LAYER_get_rrec_length(), RECORD_LAYER_is_sslv2_record(), SSL3_AL_FATAL, SSL3_HM_HEADER_LENGTH, SSL3_MT_CCS, SSL3_MT_CHANGE_CIPHER_SPEC, SSL3_MT_HELLO_REQUEST, SSL3_RT_CHANGE_CIPHER_SPEC, SSL3_RT_HANDSHAKE, ssl3_send_alert(), SSL_AD_ILLEGAL_PARAMETER, SSL_AD_UNEXPECTED_MESSAGE, SSL_F_TLS_GET_MESSAGE_HEADER, SSL_R_BAD_CHANGE_CIPHER_SPEC, SSL_R_CCS_RECEIVED_EARLY, SSL_R_EXCESSIVE_MESSAGE_SIZE, SSL_READING, SSLerr, and TLS_ST_OK.
tls_process_cert_verify()
MSG_PROCESS_RETURN tls_process_cert_verify (SSL * s, PACKET * pkt)
Definition at line 276 of file statem_lib.c.
References data, NULL, and SSL_AD_INTERNAL_ERROR.
Referenced by ossl_statem_server_process_message().
tls_process_change_cipher_spec()
MSG_PROCESS_RETURN tls_process_change_cipher_spec (SSL * s, PACKET * pkt)
Definition at line 585 of file statem_lib.c.
Referenced by ossl_statem_server_process_message().
tls_process_finished()
MSG_PROCESS_RETURN tls_process_finished (SSL * s, PACKET * pkt)
Definition at line 652 of file statem_lib.c.
References SSL_AD_INTERNAL_ERROR, SSL_AD_UNEXPECTED_MESSAGE, SSL_F_TLS_PROCESS_FINISHED, SSL_IS_TLS13, SSL_R_GOT_A_FIN_BEFORE_A_CCS, and SSLerr.
Referenced by ossl_statem_server_process_message().
tls_process_key_update()
MSG_PROCESS_RETURN tls_process_key_update (SSL * s, PACKET * pkt)
Definition at line 513 of file statem_lib.c.
References MAX_KEY_UPDATE_MESSAGES, SSL_AD_ILLEGAL_PARAMETER, SSL_F_TLS_PROCESS_KEY_UPDATE, SSL_R_TOO_MANY_KEY_UPDATES, and SSLerr.
Referenced by ossl_statem_server_process_message().
tls_setup_handshake()
int tls_setup_handshake (SSL * s)
Definition at line 75 of file statem_lib.c.
References SSL3_AL_FATAL, ssl3_init_finished_mac(), ssl3_send_alert(), SSL_AD_HANDSHAKE_FAILURE, SSL_F_TLS_SETUP_HANDSHAKE, SSL_IS_DTLS, SSL_IS_FIRST_HANDSHAKE, SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION, SSL_R_UNSAFE_LEGACY_RENEGOTIATION_DISABLED, and SSLerr.