ssl/statem/statem.h File Reference
statem.h File Reference
Data Structures
struct OSSL_STATEM
Enumerations
enum WORK_STATE {
WORK_ERROR, WORK_FINISHED_STOP, WORK_FINISHED_CONTINUE, WORK_MORE_A,
WORK_MORE_B
}
enum WRITE_TRAN { WRITE_TRAN_ERROR, WRITE_TRAN_CONTINUE, WRITE_TRAN_FINISHED }
enum MSG_FLOW_STATE {
MSG_FLOW_UNINITED, MSG_FLOW_ERROR, MSG_FLOW_READING, MSG_FLOW_WRITING,
MSG_FLOW_FINISHED
}
enum READ_STATE { READ_STATE_HEADER, READ_STATE_BODY, READ_STATE_POST_PROCESS }
enum WRITE_STATE { WRITE_STATE_TRANSITION, WRITE_STATE_PRE_WORK, WRITE_STATE_SEND, WRITE_STATE_POST_WORK }
Functions
__owur int ossl_statem_accept (SSL *s)
__owur int ossl_statem_connect (SSL *s)
void ossl_statem_clear (SSL *s)
void ossl_statem_set_renegotiate (SSL *s)
void ossl_statem_set_error (SSL *s)
int ossl_statem_in_error (const SSL *s)
void ossl_statem_set_in_init (SSL *s, int init)
int ossl_statem_get_in_handshake (SSL *s)
void ossl_statem_set_in_handshake (SSL *s, int inhand)
void ossl_statem_set_hello_verify_done (SSL *s)
__owur int ossl_statem_app_data_allowed (SSL *s)
void ossl_statem_set_sctp_read_sock (SSL *s, int read_sock)
__owur int ossl_statem_in_sctp_read_sock (SSL *s)
Enumeration Type Documentation
MSG_FLOW_STATE
enum MSG_FLOW_STATE
Enumerator
MSG_FLOW_UNINITED
MSG_FLOW_ERROR
MSG_FLOW_READING
MSG_FLOW_WRITING
MSG_FLOW_FINISHED
Definition at line 44 of file statem.h.
READ_STATE
enum READ_STATE
Enumerator
READ_STATE_HEADER
READ_STATE_BODY
READ_STATE_POST_PROCESS
Definition at line 58 of file statem.h.
WORK_STATE
enum WORK_STATE
Enumerator
WORK_ERROR
WORK_FINISHED_STOP
WORK_FINISHED_CONTINUE
WORK_MORE_A
WORK_MORE_B
Definition at line 20 of file statem.h.
WRITE_STATE
enum WRITE_STATE
Enumerator
WRITE_STATE_TRANSITION
WRITE_STATE_PRE_WORK
WRITE_STATE_SEND
WRITE_STATE_POST_WORK
Definition at line 65 of file statem.h.
WRITE_TRAN
enum WRITE_TRAN
Enumerator
WRITE_TRAN_ERROR
WRITE_TRAN_CONTINUE
WRITE_TRAN_FINISHED
Definition at line 34 of file statem.h.
Function Documentation
ossl_statem_accept()
__owur int ossl_statem_accept (SSL * s)
Definition at line 173 of file statem.c.
ossl_statem_app_data_allowed()
__owur int ossl_statem_app_data_allowed (SSL * s)
Definition at line 787 of file statem.c.
References MSG_FLOW_UNINITED, TLS_ST_BEFORE, TLS_ST_CW_CLNT_HELLO, and TLS_ST_SR_CLNT_HELLO.
ossl_statem_clear()
void ossl_statem_clear (SSL * s)
Definition at line 95 of file statem.c.
References MSG_FLOW_UNINITED, and TLS_ST_BEFORE.
Referenced by SSL_clear(), SSL_set_accept_state(), and SSL_set_connect_state().
ossl_statem_connect()
__owur int ossl_statem_connect (SSL * s)
Definition at line 168 of file statem.c.
ossl_statem_get_in_handshake()
int ossl_statem_get_in_handshake (SSL * s)
Definition at line 141 of file statem.c.
Referenced by dtls1_get_record(), dtls1_write_app_data_bytes(), and SSL_ctrl().
ossl_statem_in_error()
int ossl_statem_in_error (const SSL * s)
Definition at line 128 of file statem.c.
References MSG_FLOW_ERROR.
Referenced by SSL_state_string(), and SSL_state_string_long().
ossl_statem_in_sctp_read_sock()
__owur int ossl_statem_in_sctp_read_sock (SSL * s)
Definition at line 834 of file statem.c.
Referenced by dtls1_write_app_data_bytes().
ossl_statem_set_error()
void ossl_statem_set_error (SSL * s)
Definition at line 116 of file statem.c.
References MSG_FLOW_ERROR.
Referenced by ossl_statem_client_pre_work(), ossl_statem_server_post_work(), ossl_statem_server_pre_work(), tls_post_process_client_key_exchange(), tls_prepare_client_certificate(), and tls_process_cert_status().
ossl_statem_set_hello_verify_done()
void ossl_statem_set_hello_verify_done (SSL * s)
Definition at line 154 of file statem.c.
References MSG_FLOW_UNINITED, and TLS_ST_SR_CLNT_HELLO.
ossl_statem_set_in_handshake()
void ossl_statem_set_in_handshake (SSL * s, int inhand)
Definition at line 146 of file statem.c.
ossl_statem_set_in_init()
void ossl_statem_set_in_init (SSL * s, int init)
Definition at line 136 of file statem.c.
Referenced by SSL_key_update().
ossl_statem_set_renegotiate()
void ossl_statem_set_renegotiate (SSL * s)
Definition at line 106 of file statem.c.
References TLS_ST_SW_HELLO_REQ.
ossl_statem_set_sctp_read_sock()
void ossl_statem_set_sctp_read_sock (SSL * s, int read_sock)
Definition at line 821 of file statem.c.
Referenced by ossl_statem_client_post_process_message(), ossl_statem_server_post_process_message(), and tls_post_process_client_key_exchange().