ssl/statem/statem_clnt.c File Reference
statem_clnt.c File Reference
#include <stdio.h>
#include <time.h>
#include "../ssl_locl.h"
#include "statem_locl.h"
#include <openssl/buffer.h>
#include <openssl/rand.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/md5.h>
#include <openssl/dh.h>
#include <openssl/bn.h>
#include <openssl/engine.h>
Macros
#define has_bits(i, m) (((i)&(m)) == (m))
Functions
int ossl_statem_client_read_transition (SSL *s, int mt)
WRITE_TRAN ossl_statem_client_write_transition (SSL *s)
WORK_STATE ossl_statem_client_pre_work (SSL *s, WORK_STATE wst)
WORK_STATE ossl_statem_client_post_work (SSL *s, WORK_STATE wst)
int ossl_statem_client_construct_message (SSL *s, WPACKET *pkt, confunc_f *confunc, int *mt)
size_t ossl_statem_client_max_message_size (SSL *s)
MSG_PROCESS_RETURN ossl_statem_client_process_message (SSL *s, PACKET *pkt)
WORK_STATE ossl_statem_client_post_process_message (SSL *s, WORK_STATE wst)
int tls_construct_client_hello (SSL *s, WPACKET *pkt)
MSG_PROCESS_RETURN dtls_process_hello_verify (SSL *s, PACKET *pkt)
MSG_PROCESS_RETURN tls_process_server_hello (SSL *s, PACKET *pkt)
MSG_PROCESS_RETURN tls_process_server_certificate (SSL *s, PACKET *pkt)
MSG_PROCESS_RETURN tls_process_key_exchange (SSL *s, PACKET *pkt)
MSG_PROCESS_RETURN tls_process_certificate_request (SSL *s, PACKET *pkt)
MSG_PROCESS_RETURN tls_process_new_session_ticket (SSL *s, PACKET *pkt)
int tls_process_cert_status_body (SSL *s, PACKET *pkt, int *al)
MSG_PROCESS_RETURN tls_process_cert_status (SSL *s, PACKET *pkt)
int tls_process_initial_server_flight (SSL *s, int *al)
MSG_PROCESS_RETURN tls_process_server_done (SSL *s, PACKET *pkt)
int tls_construct_client_key_exchange (SSL *s, WPACKET *pkt)
int tls_client_key_exchange_post_work (SSL *s)
WORK_STATE tls_prepare_client_certificate (SSL *s, WORK_STATE wst)
int tls_construct_client_certificate (SSL *s, WPACKET *pkt)
int ssl3_check_cert_and_algorithm (SSL *s)
int tls_construct_next_proto (SSL *s, WPACKET *pkt)
MSG_PROCESS_RETURN tls_process_hello_req (SSL *s, PACKET *pkt)
int ssl_do_client_cert_cb (SSL *s, X509 **px509, EVP_PKEY **ppkey)
Macro Definition Documentation
has_bits
#define has_bits (i, m) (((i)&(m)) == (m))
Definition at line 3232 of file statem_clnt.c.
Function Documentation
dtls_process_hello_verify()
MSG_PROCESS_RETURN dtls_process_hello_verify (SSL * s, PACKET * pkt)
Definition at line 1137 of file statem_clnt.c.
Referenced by ossl_statem_client_process_message().
ossl_statem_client_construct_message()
int ossl_statem_client_construct_message (SSL * s, WPACKET * pkt, confunc_f * confunc, int * mt)
Definition at line 754 of file statem_clnt.c.
References dtls_construct_change_cipher_spec(), SSL3_MT_CERTIFICATE, SSL3_MT_CERTIFICATE_VERIFY, SSL3_MT_CHANGE_CIPHER_SPEC, SSL3_MT_CLIENT_HELLO, SSL3_MT_CLIENT_KEY_EXCHANGE, SSL3_MT_FINISHED, SSL3_MT_KEY_UPDATE, SSL3_MT_NEXT_PROTO, SSL_IS_DTLS, tls_construct_cert_verify(), tls_construct_change_cipher_spec(), tls_construct_client_certificate(), tls_construct_client_hello(), tls_construct_client_key_exchange(), tls_construct_finished(), tls_construct_key_update(), tls_construct_next_proto(), TLS_ST_CW_CERT, TLS_ST_CW_CERT_VRFY, TLS_ST_CW_CHANGE, TLS_ST_CW_CLNT_HELLO, TLS_ST_CW_FINISHED, TLS_ST_CW_KEY_EXCH, TLS_ST_CW_KEY_UPDATE, and TLS_ST_CW_NEXT_PROTO.
ossl_statem_client_max_message_size()
size_t ossl_statem_client_max_message_size (SSL * s)
Definition at line 816 of file statem_clnt.c.
References CCS_MAX_LENGTH, DTLS1_BAD_VER, DTLS_ST_CR_HELLO_VERIFY_REQUEST, ENCRYPTED_EXTENSIONS_MAX_LENGTH, FINISHED_MAX_LENGTH, HELLO_RETRY_REQUEST_MAX_LENGTH, HELLO_VERIFY_REQUEST_MAX_LENGTH, KEY_UPDATE_MAX_LENGTH, SERVER_HELLO_DONE_MAX_LENGTH, SERVER_HELLO_MAX_LENGTH, SERVER_KEY_EXCH_MAX_LENGTH, SSL3_RT_MAX_PLAIN_LENGTH, TLS_ST_CR_CERT, TLS_ST_CR_CERT_REQ, TLS_ST_CR_CERT_STATUS, TLS_ST_CR_CERT_VRFY, TLS_ST_CR_CHANGE, TLS_ST_CR_ENCRYPTED_EXTENSIONS, TLS_ST_CR_FINISHED, TLS_ST_CR_HELLO_RETRY_REQUEST, TLS_ST_CR_KEY_EXCH, TLS_ST_CR_KEY_UPDATE, TLS_ST_CR_SESSION_TICKET, TLS_ST_CR_SRVR_DONE, and TLS_ST_CR_SRVR_HELLO.
ossl_statem_client_post_process_message()
WORK_STATE ossl_statem_client_post_process_message (SSL * s, WORK_STATE wst)
Definition at line 939 of file statem_clnt.c.
References BIO_clear_retry_flags, BIO_dgram_sctp_msg_waiting(), BIO_set_retry_read, ossl_statem_set_sctp_read_sock(), SSL_get_rbio(), SSL_READING, tls_prepare_client_certificate(), TLS_ST_CR_CERT_REQ, TLS_ST_CR_SRVR_DONE, WORK_ERROR, WORK_FINISHED_STOP, and WORK_MORE_A.
ossl_statem_client_post_work()
WORK_STATE ossl_statem_client_post_work (SSL * s, WORK_STATE wst)
Definition at line 655 of file statem_clnt.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_SCTP_NEXT_AUTH_KEY, dtls1_reset_seq_numbers(), NULL, SSL3_CC_APPLICATION, SSL3_CC_WRITE, SSL3_CHANGE_CIPHER_CLIENT_WRITE, SSL_get_wbio(), SSL_IS_DTLS, SSL_IS_TLS13, statem_flush(), tls13_update_key(), tls_client_key_exchange_post_work(), TLS_ST_CW_CHANGE, TLS_ST_CW_CLNT_HELLO, TLS_ST_CW_FINISHED, TLS_ST_CW_KEY_EXCH, TLS_ST_CW_KEY_UPDATE, WORK_ERROR, WORK_FINISHED_CONTINUE, WORK_MORE_A, and WORK_MORE_B.
ossl_statem_client_pre_work()
WORK_STATE ossl_statem_client_pre_work (SSL * s, WORK_STATE wst)
Definition at line 606 of file statem_clnt.c.
References BIO_dgram_is_sctp(), dtls_wait_for_dry(), ossl_statem_set_error(), ssl3_init_finished_mac(), SSL_get_wbio(), SSL_IS_DTLS, tls_finish_handshake(), TLS_ST_CW_CHANGE, TLS_ST_CW_CLNT_HELLO, TLS_ST_OK, WORK_ERROR, and WORK_FINISHED_CONTINUE.
ossl_statem_client_process_message()
MSG_PROCESS_RETURN ossl_statem_client_process_message (SSL * s, PACKET * pkt)
Definition at line 879 of file statem_clnt.c.
References dtls_process_hello_verify(), DTLS_ST_CR_HELLO_VERIFY_REQUEST, MSG_PROCESS_ERROR, tls_process_server_hello(), TLS_ST_CR_HELLO_RETRY_REQUEST, and TLS_ST_CR_SRVR_HELLO.
ossl_statem_client_read_transition()
int ossl_statem_client_read_transition (SSL * s, int mt)
Definition at line 223 of file statem_clnt.c.
References SSL_IS_TLS13.
ossl_statem_client_write_transition()
WRITE_TRAN ossl_statem_client_write_transition (SSL * s)
Definition at line 470 of file statem_clnt.c.
References SSL_IS_TLS13.
ssl3_check_cert_and_algorithm()
int ssl3_check_cert_and_algorithm (SSL * s)
Definition at line 3234 of file statem_clnt.c.
Referenced by tls_process_initial_server_flight().
ssl_do_client_cert_cb()
int ssl_do_client_cert_cb (SSL * s, X509 ** px509, EVP_PKEY ** ppkey)
Definition at line 3384 of file statem_clnt.c.
References ENGINE_load_ssl_client_cert(), and NULL.
tls_client_key_exchange_post_work()
int tls_client_key_exchange_post_work (SSL * s)
Definition at line 3051 of file statem_clnt.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_SCTP_ADD_AUTH_KEY, DTLS1_SCTP_AUTH_LABEL, ERR_R_INTERNAL_ERROR, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_clear_free, srp_generate_client_master_secret(), SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_export_keying_material(), SSL_F_TLS_CLIENT_KEY_EXCHANGE_POST_WORK, ssl_generate_master_secret(), SSL_get_wbio(), SSL_IS_DTLS, SSL_kPSK, SSL_kSRP, and SSLerr.
Referenced by ossl_statem_client_post_work().
tls_construct_client_certificate()
int tls_construct_client_certificate (SSL * s, WPACKET * pkt)
Definition at line 3211 of file statem_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL3_AL_FATAL, ssl3_output_cert_chain(), ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CLIENT_CERTIFICATE, SSL_IS_TLS13, SSLerr, and WPACKET_put_bytes_u8.
Referenced by ossl_statem_client_construct_message().
tls_construct_client_hello()
int tls_construct_client_hello (SSL * s, WPACKET * pkt)
Definition at line 968 of file statem_clnt.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL3_RT_MAX_PLAIN_LENGTH, SSL_AD_HANDSHAKE_FAILURE, SSL_F_TLS_CONSTRUCT_CLIENT_HELLO, ssl_get_new_session(), SSL_IS_DTLS, ssl_set_client_hello_version(), ssl_version_supported(), SSLerr, and WPACKET_set_max_size().
Referenced by ossl_statem_client_construct_message().
tls_construct_client_key_exchange()
int tls_construct_client_key_exchange (SSL * s, WPACKET * pkt)
Definition at line 3006 of file statem_clnt.c.
References SSL_PSK.
Referenced by ossl_statem_client_construct_message().
tls_construct_next_proto()
int tls_construct_next_proto (SSL * s, WPACKET * pkt)
Definition at line 3308 of file statem_clnt.c.
References ERR_R_INTERNAL_ERROR, len, NULL, SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_NEXT_PROTO, SSLerr, WPACKET_sub_allocate_bytes_u8, and WPACKET_sub_memcpy_u8.
Referenced by ossl_statem_client_construct_message().
tls_prepare_client_certificate()
WORK_STATE tls_prepare_client_certificate (SSL * s, WORK_STATE wst)
Definition at line 3136 of file statem_clnt.c.
References NULL, ossl_statem_set_error(), SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_NOTHING, SSL_X509_LOOKUP, and WORK_MORE_A.
Referenced by ossl_statem_client_post_process_message().
tls_process_cert_status()
MSG_PROCESS_RETURN tls_process_cert_status (SSL * s, PACKET * pkt)
Definition at line 2493 of file statem_clnt.c.
References MSG_PROCESS_CONTINUE_READING, MSG_PROCESS_ERROR, ossl_statem_set_error(), SSL3_AL_FATAL, ssl3_send_alert(), and tls_process_cert_status_body().
tls_process_cert_status_body()
int tls_process_cert_status_body (SSL * s, PACKET * pkt, int * al)
Definition at line 2458 of file statem_clnt.c.
References type.
Referenced by tls_process_cert_status().
tls_process_certificate_request()
MSG_PROCESS_RETURN tls_process_certificate_request (SSL * s, PACKET * pkt)
Definition at line 2196 of file statem_clnt.c.
tls_process_hello_req()
MSG_PROCESS_RETURN tls_process_hello_req (SSL * s, PACKET * pkt)
Definition at line 3331 of file statem_clnt.c.
tls_process_initial_server_flight()
int tls_process_initial_server_flight (SSL * s, int * al)
Definition at line 2512 of file statem_clnt.c.
References NULL, ssl3_check_cert_and_algorithm(), SSL_AD_HANDSHAKE_FAILURE, and TLSEXT_STATUSTYPE_nothing.
tls_process_key_exchange()
MSG_PROCESS_RETURN tls_process_key_exchange (SSL * s, PACKET * pkt)
Definition at line 2016 of file statem_clnt.c.
References NULL.
tls_process_new_session_ticket()
MSG_PROCESS_RETURN tls_process_new_session_ticket (SSL * s, PACKET * pkt)
Definition at line 2324 of file statem_clnt.c.
References NULL, and SSL_AD_DECODE_ERROR.
tls_process_server_certificate()
MSG_PROCESS_RETURN tls_process_server_certificate (SSL * s, PACKET * pkt)
Definition at line 1542 of file statem_clnt.c.
tls_process_server_done()
MSG_PROCESS_RETURN tls_process_server_done (SSL * s, PACKET * pkt)
Definition at line 2558 of file statem_clnt.c.
References SSL_AD_INTERNAL_ERROR.
tls_process_server_hello()
MSG_PROCESS_RETURN tls_process_server_hello (SSL * s, PACKET * pkt)
Definition at line 1171 of file statem_clnt.c.
References STACK_OF.
Referenced by ossl_statem_client_process_message().