ssl/statem/statem_srvr.c File Reference
statem_srvr.c File Reference
#include <stdio.h>
#include "../ssl_locl.h"
#include "statem_locl.h"
#include "internal/constant_time_locl.h"
#include <openssl/buffer.h>
#include <openssl/rand.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/hmac.h>
#include <openssl/x509.h>
#include <openssl/dh.h>
#include <openssl/bn.h>
#include <openssl/md5.h>
Macros
#define CLIENT_HELLO_MAX_LENGTH 131396
#define CLIENT_KEY_EXCH_MAX_LENGTH 2048
#define NEXT_PROTO_MAX_LENGTH 514
#define SSLV2_CIPHER_LEN 3
Functions
int ossl_statem_server_read_transition (SSL *s, int mt)
WRITE_TRAN ossl_statem_server_write_transition (SSL *s)
WORK_STATE ossl_statem_server_pre_work (SSL *s, WORK_STATE wst)
WORK_STATE ossl_statem_server_post_work (SSL *s, WORK_STATE wst)
int ossl_statem_server_construct_message (SSL *s, WPACKET *pkt, confunc_f *confunc, int *mt)
size_t ossl_statem_server_max_message_size (SSL *s)
MSG_PROCESS_RETURN ossl_statem_server_process_message (SSL *s, PACKET *pkt)
WORK_STATE ossl_statem_server_post_process_message (SSL *s, WORK_STATE wst)
int dtls_raw_hello_verify_request (WPACKET *pkt, unsigned char *cookie, size_t cookie_len)
int dtls_construct_hello_verify_request (SSL *s, WPACKET *pkt)
MSG_PROCESS_RETURN tls_process_client_hello (SSL *s, PACKET *pkt)
WORK_STATE tls_post_process_client_hello (SSL *s, WORK_STATE wst)
int tls_construct_server_hello (SSL *s, WPACKET *pkt)
int tls_construct_server_done (SSL *s, WPACKET *pkt)
int tls_construct_server_key_exchange (SSL *s, WPACKET *pkt)
int tls_construct_certificate_request (SSL *s, WPACKET *pkt)
MSG_PROCESS_RETURN tls_process_client_key_exchange (SSL *s, PACKET *pkt)
WORK_STATE tls_post_process_client_key_exchange (SSL *s, WORK_STATE wst)
MSG_PROCESS_RETURN tls_process_client_certificate (SSL *s, PACKET *pkt)
int tls_construct_server_certificate (SSL *s, WPACKET *pkt)
int tls_construct_new_session_ticket (SSL *s, WPACKET *pkt)
int tls_construct_cert_status_body (SSL *s, WPACKET *pkt)
int tls_construct_cert_status (SSL *s, WPACKET *pkt)
MSG_PROCESS_RETURN tls_process_next_proto (SSL *s, PACKET *pkt)
Macro Definition Documentation
CLIENT_HELLO_MAX_LENGTH
#define CLIENT_HELLO_MAX_LENGTH 131396
Definition at line 976 of file statem_srvr.c.
Referenced by ossl_statem_server_max_message_size().
CLIENT_KEY_EXCH_MAX_LENGTH
#define CLIENT_KEY_EXCH_MAX_LENGTH 2048
Definition at line 978 of file statem_srvr.c.
Referenced by ossl_statem_server_max_message_size().
NEXT_PROTO_MAX_LENGTH
#define NEXT_PROTO_MAX_LENGTH 514
Definition at line 979 of file statem_srvr.c.
Referenced by ossl_statem_server_max_message_size().
SSLV2_CIPHER_LEN
#define SSLV2_CIPHER_LEN 3
Definition at line 3510 of file statem_srvr.c.
Function Documentation
dtls_construct_hello_verify_request()
int dtls_construct_hello_verify_request (SSL * s, WPACKET * pkt)
Definition at line 1138 of file statem_srvr.c.
References dtls_raw_hello_verify_request(), ERR_R_INTERNAL_ERROR, NULL, SSL_F_DTLS_CONSTRUCT_HELLO_VERIFY_REQUEST, SSL_R_COOKIE_GEN_CALLBACK_FAILURE, and SSLerr.
Referenced by ossl_statem_server_construct_message().
dtls_raw_hello_verify_request()
int dtls_raw_hello_verify_request (WPACKET * pkt, unsigned char * cookie, size_t cookie_len)
Definition at line 1127 of file statem_srvr.c.
Referenced by dtls_construct_hello_verify_request().
ossl_statem_server_construct_message()
int ossl_statem_server_construct_message (SSL * s, WPACKET * pkt, confunc_f * confunc, int * mt)
Definition at line 867 of file statem_srvr.c.
References DTLS1_MT_HELLO_VERIFY_REQUEST, dtls_construct_change_cipher_spec(), dtls_construct_hello_verify_request(), DTLS_ST_SW_HELLO_VERIFY_REQUEST, NULL, SSL3_MT_CERTIFICATE, SSL3_MT_CERTIFICATE_REQUEST, SSL3_MT_CERTIFICATE_STATUS, SSL3_MT_CERTIFICATE_VERIFY, SSL3_MT_CHANGE_CIPHER_SPEC, SSL3_MT_FINISHED, SSL3_MT_HELLO_REQUEST, SSL3_MT_NEWSESSION_TICKET, SSL3_MT_SERVER_DONE, SSL3_MT_SERVER_HELLO, SSL3_MT_SERVER_KEY_EXCHANGE, SSL_IS_DTLS, tls_construct_cert_status(), tls_construct_cert_verify(), tls_construct_certificate_request(), tls_construct_change_cipher_spec(), tls_construct_finished(), tls_construct_new_session_ticket(), tls_construct_server_certificate(), tls_construct_server_done(), tls_construct_server_hello(), tls_construct_server_key_exchange(), TLS_ST_SW_CERT, TLS_ST_SW_CERT_REQ, TLS_ST_SW_CERT_STATUS, TLS_ST_SW_CERT_VRFY, TLS_ST_SW_CHANGE, TLS_ST_SW_ENCRYPTED_EXTENSIONS, TLS_ST_SW_FINISHED, TLS_ST_SW_HELLO_REQ, TLS_ST_SW_KEY_EXCH, TLS_ST_SW_SESSION_TICKET, TLS_ST_SW_SRVR_DONE, and TLS_ST_SW_SRVR_HELLO.
ossl_statem_server_max_message_size()
size_t ossl_statem_server_max_message_size (SSL * s)
Definition at line 985 of file statem_srvr.c.
References CCS_MAX_LENGTH, CLIENT_HELLO_MAX_LENGTH, CLIENT_KEY_EXCH_MAX_LENGTH, FINISHED_MAX_LENGTH, KEY_UPDATE_MAX_LENGTH, NEXT_PROTO_MAX_LENGTH, SSL3_RT_MAX_PLAIN_LENGTH, TLS_ST_SR_CERT, TLS_ST_SR_CERT_VRFY, TLS_ST_SR_CHANGE, TLS_ST_SR_CLNT_HELLO, TLS_ST_SR_FINISHED, TLS_ST_SR_KEY_EXCH, TLS_ST_SR_KEY_UPDATE, and TLS_ST_SR_NEXT_PROTO.
ossl_statem_server_post_process_message()
WORK_STATE ossl_statem_server_post_process_message (SSL * s, WORK_STATE wst)
Definition at line 1067 of file statem_srvr.c.
References BIO_clear_retry_flags, BIO_dgram_is_sctp(), BIO_dgram_sctp_msg_waiting(), BIO_set_retry_read, ossl_statem_set_sctp_read_sock(), SSL_get_rbio(), SSL_get_wbio(), SSL_READING, tls_post_process_client_hello(), tls_post_process_client_key_exchange(), TLS_ST_SR_CERT_VRFY, TLS_ST_SR_CLNT_HELLO, TLS_ST_SR_KEY_EXCH, WORK_ERROR, WORK_FINISHED_CONTINUE, and WORK_MORE_A.
ossl_statem_server_post_work()
WORK_STATE ossl_statem_server_post_work (SSL * s, WORK_STATE wst)
Definition at line 712 of file statem_srvr.c.
References BIO_ctrl(), BIO_CTRL_DGRAM_SCTP_ADD_AUTH_KEY, BIO_CTRL_DGRAM_SCTP_NEXT_AUTH_KEY, DTLS1_BAD_VER, dtls1_reset_seq_numbers(), DTLS1_SCTP_AUTH_LABEL, DTLS_ST_SW_HELLO_VERIFY_REQUEST, NULL, ossl_statem_set_error(), SSL3_CC_APPLICATION, SSL3_CC_HANDSHAKE, SSL3_CC_WRITE, SSL3_CHANGE_CIPHER_SERVER_READ, SSL3_CHANGE_CIPHER_SERVER_WRITE, ssl3_init_finished_mac(), SSL_export_keying_material(), SSL_get_wbio(), SSL_IS_DTLS, SSL_IS_TLS13, statem_flush(), tls13_update_key(), TLS_ST_SW_CHANGE, TLS_ST_SW_FINISHED, TLS_ST_SW_HELLO_REQ, TLS_ST_SW_HELLO_RETRY_REQUEST, TLS_ST_SW_KEY_UPDATE, TLS_ST_SW_SESSION_TICKET, TLS_ST_SW_SRVR_DONE, TLS_ST_SW_SRVR_HELLO, WORK_ERROR, WORK_FINISHED_CONTINUE, and WORK_MORE_A.
ossl_statem_server_pre_work()
WORK_STATE ossl_statem_server_pre_work (SSL * s, WORK_STATE wst)
Definition at line 626 of file statem_srvr.c.
References BIO_dgram_is_sctp(), dtls1_clear_sent_buffer(), DTLS_ST_SW_HELLO_VERIFY_REQUEST, dtls_wait_for_dry(), ossl_statem_set_error(), SSL_get_wbio(), SSL_IS_DTLS, SSL_IS_TLS13, tls_finish_handshake(), TLS_ST_OK, TLS_ST_SW_CHANGE, TLS_ST_SW_HELLO_REQ, TLS_ST_SW_SESSION_TICKET, TLS_ST_SW_SRVR_DONE, TLS_ST_SW_SRVR_HELLO, WORK_ERROR, and WORK_FINISHED_CONTINUE.
ossl_statem_server_process_message()
MSG_PROCESS_RETURN ossl_statem_server_process_message (SSL * s, PACKET * pkt)
Definition at line 1025 of file statem_srvr.c.
References MSG_PROCESS_ERROR, tls_process_cert_verify(), tls_process_change_cipher_spec(), tls_process_client_certificate(), tls_process_client_hello(), tls_process_client_key_exchange(), tls_process_finished(), tls_process_key_update(), tls_process_next_proto(), TLS_ST_SR_CERT, TLS_ST_SR_CERT_VRFY, TLS_ST_SR_CHANGE, TLS_ST_SR_CLNT_HELLO, TLS_ST_SR_FINISHED, TLS_ST_SR_KEY_EXCH, TLS_ST_SR_KEY_UPDATE, and TLS_ST_SR_NEXT_PROTO.
ossl_statem_server_read_transition()
int ossl_statem_server_read_transition (SSL * s, int mt)
Definition at line 160 of file statem_srvr.c.
References DTLS_ST_SW_HELLO_VERIFY_REQUEST, NULL, SSL3_AD_HANDSHAKE_FAILURE, SSL3_AD_UNEXPECTED_MESSAGE, SSL3_AL_FATAL, SSL3_MT_CERTIFICATE, SSL3_MT_CERTIFICATE_VERIFY, SSL3_MT_CHANGE_CIPHER_SPEC, SSL3_MT_CLIENT_HELLO, SSL3_MT_CLIENT_KEY_EXCHANGE, SSL3_MT_FINISHED, SSL3_MT_NEXT_PROTO, ssl3_send_alert(), SSL3_VERSION, SSL_F_OSSL_STATEM_SERVER_READ_TRANSITION, SSL_IS_TLS13, SSL_R_PEER_DID_NOT_RETURN_A_CERTIFICATE, SSL_R_UNEXPECTED_MESSAGE, SSL_VERIFY_FAIL_IF_NO_PEER_CERT, SSL_VERIFY_PEER, SSLerr, TLS_ST_BEFORE, TLS_ST_OK, TLS_ST_SR_CERT, TLS_ST_SR_CERT_VRFY, TLS_ST_SR_CHANGE, TLS_ST_SR_CLNT_HELLO, TLS_ST_SR_FINISHED, TLS_ST_SR_KEY_EXCH, TLS_ST_SR_NEXT_PROTO, TLS_ST_SW_FINISHED, and TLS_ST_SW_SRVR_DONE.
ossl_statem_server_write_transition()
WRITE_TRAN ossl_statem_server_write_transition (SSL * s)
Definition at line 491 of file statem_srvr.c.
References SSL_IS_TLS13.
tls_construct_cert_status()
int tls_construct_cert_status (SSL * s, WPACKET * pkt)
Definition at line 3447 of file statem_srvr.c.
References SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, and tls_construct_cert_status_body().
Referenced by ossl_statem_server_construct_message().
tls_construct_cert_status_body()
int tls_construct_cert_status_body (SSL * s, WPACKET * pkt)
Definition at line 3435 of file statem_srvr.c.
References ERR_R_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_CERT_STATUS_BODY, SSLerr, WPACKET_put_bytes_u8, and WPACKET_sub_memcpy_u24.
Referenced by tls_construct_cert_status(), and tls_construct_stoc_status_request().
tls_construct_certificate_request()
int tls_construct_certificate_request (SSL * s, WPACKET * pkt)
Definition at line 2367 of file statem_srvr.c.
Referenced by ossl_statem_server_construct_message().
tls_construct_new_session_ticket()
int tls_construct_new_session_ticket (SSL * s, WPACKET * pkt)
Definition at line 3259 of file statem_srvr.c.
References ctx, len, and NULL.
Referenced by ossl_statem_server_construct_message().
tls_construct_server_certificate()
int tls_construct_server_certificate (SSL * s, WPACKET * pkt)
Definition at line 3235 of file statem_srvr.c.
References ERR_R_INTERNAL_ERROR, NULL, SSL3_AL_FATAL, ssl3_output_cert_chain(), ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_SERVER_CERTIFICATE, SSL_IS_TLS13, SSLerr, and WPACKET_put_bytes_u8.
Referenced by ossl_statem_server_construct_message().
tls_construct_server_done()
int tls_construct_server_done (SSL * s, WPACKET * pkt)
Definition at line 2015 of file statem_srvr.c.
References SSL3_AL_FATAL, ssl3_digest_cached_records(), ssl3_send_alert(), and SSL_AD_INTERNAL_ERROR.
Referenced by ossl_statem_server_construct_message().
tls_construct_server_hello()
int tls_construct_server_hello (SSL * s, WPACKET * pkt)
Definition at line 1934 of file statem_srvr.c.
References ERR_R_INTERNAL_ERROR, EXT_TLS1_2_SERVER_HELLO, EXT_TLS1_3_SERVER_HELLO, len, NULL, SSL3_AL_FATAL, ssl3_digest_cached_records(), SSL3_RANDOM_SIZE, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_TLS_CONSTRUCT_SERVER_HELLO, SSL_IS_TLS13, SSL_SESS_CACHE_SERVER, SSL_VERIFY_PEER, SSLerr, TLS1_3_VERSION_DRAFT, tls_construct_extensions(), WPACKET_memcpy(), WPACKET_put_bytes_u16, WPACKET_put_bytes_u8, and WPACKET_sub_memcpy_u8.
Referenced by ossl_statem_server_construct_message().
tls_construct_server_key_exchange()
int tls_construct_server_key_exchange (SSL * s, WPACKET * pkt)
Definition at line 2026 of file statem_srvr.c.
References EVP_MD_CTX_new(), NULL, SIGALG_LOOKUP::sigalg, SSL_AD_INTERNAL_ERROR, and type.
Referenced by ossl_statem_server_construct_message().
tls_post_process_client_hello()
WORK_STATE tls_post_process_client_hello (SSL * s, WORK_STATE wst)
Definition at line 1830 of file statem_srvr.c.
References SSL_AD_HANDSHAKE_FAILURE.
Referenced by ossl_statem_server_post_process_message().
tls_post_process_client_key_exchange()
WORK_STATE tls_post_process_client_key_exchange (SSL * s, WORK_STATE wst)
Definition at line 2997 of file statem_srvr.c.
References BIO_clear_retry_flags, BIO_ctrl(), BIO_CTRL_DGRAM_SCTP_ADD_AUTH_KEY, BIO_dgram_is_sctp(), BIO_dgram_sctp_msg_waiting(), BIO_set_retry_read, DTLS1_SCTP_AUTH_LABEL, ERR_R_INTERNAL_ERROR, NULL, ossl_statem_set_error(), ossl_statem_set_sctp_read_sock(), ssl3_digest_cached_records(), SSL_export_keying_material(), SSL_F_TLS_POST_PROCESS_CLIENT_KEY_EXCHANGE, SSL_get_rbio(), SSL_get_wbio(), SSL_IS_DTLS, SSL_READING, SSLerr, WORK_ERROR, WORK_FINISHED_CONTINUE, WORK_MORE_A, and WORK_MORE_B.
Referenced by ossl_statem_server_post_process_message().
tls_process_client_certificate()
MSG_PROCESS_RETURN tls_process_client_certificate (SSL * s, PACKET * pkt)
Definition at line 3074 of file statem_srvr.c.
References SSL_AD_INTERNAL_ERROR.
Referenced by ossl_statem_server_process_message().
tls_process_client_hello()
MSG_PROCESS_RETURN tls_process_client_hello (SSL * s, PACKET * pkt)
Definition at line 1223 of file statem_srvr.c.
References SSL_AD_INTERNAL_ERROR.
Referenced by ossl_statem_server_process_message().
tls_process_client_key_exchange()
MSG_PROCESS_RETURN tls_process_client_key_exchange (SSL * s, PACKET * pkt)
Definition at line 2938 of file statem_srvr.c.
References SSL_PSK.
Referenced by ossl_statem_server_process_message().
tls_process_next_proto()
MSG_PROCESS_RETURN tls_process_next_proto (SSL * s, PACKET * pkt)
Definition at line 3462 of file statem_srvr.c.
Referenced by ossl_statem_server_process_message().