ssl/statem/statem.c File Reference
statem.c File Reference
#include <openssl/rand.h>
#include "../ssl_locl.h"
#include "statem_locl.h"
Typedefs
typedef void(* info_cb) (const SSL *, int, int)
Enumerations
enum SUB_STATE_RETURN { SUB_STATE_ERROR, SUB_STATE_FINISHED, SUB_STATE_END_HANDSHAKE }
Functions
OSSL_HANDSHAKE_STATE SSL_get_state (const SSL *ssl)
int SSL_in_init (SSL *s)
int SSL_is_init_finished (SSL *s)
int SSL_in_before (SSL *s)
void ossl_statem_clear (SSL *s)
void ossl_statem_set_renegotiate (SSL *s)
void ossl_statem_set_error (SSL *s)
int ossl_statem_in_error (const SSL *s)
void ossl_statem_set_in_init (SSL *s, int init)
int ossl_statem_get_in_handshake (SSL *s)
void ossl_statem_set_in_handshake (SSL *s, int inhand)
void ossl_statem_set_hello_verify_done (SSL *s)
int ossl_statem_connect (SSL *s)
int ossl_statem_accept (SSL *s)
int statem_flush (SSL *s)
int ossl_statem_app_data_allowed (SSL *s)
void ossl_statem_set_sctp_read_sock (SSL *s, int read_sock)
int ossl_statem_in_sctp_read_sock (SSL *s)
Typedef Documentation
info_cb
typedef void(* info_cb) (const SSL *, int, int)
Definition at line 178 of file statem.c.
Enumeration Type Documentation
SUB_STATE_RETURN
enum SUB_STATE_RETURN
Enumerator
SUB_STATE_ERROR
SUB_STATE_FINISHED
SUB_STATE_END_HANDSHAKE
Definition at line 49 of file statem.c.
Function Documentation
ossl_statem_accept()
int ossl_statem_accept (SSL * s)
Definition at line 173 of file statem.c.
ossl_statem_app_data_allowed()
int ossl_statem_app_data_allowed (SSL * s)
Definition at line 787 of file statem.c.
References MSG_FLOW_UNINITED, TLS_ST_BEFORE, TLS_ST_CW_CLNT_HELLO, and TLS_ST_SR_CLNT_HELLO.
ossl_statem_clear()
void ossl_statem_clear (SSL * s)
Definition at line 95 of file statem.c.
References MSG_FLOW_UNINITED, and TLS_ST_BEFORE.
Referenced by SSL_clear(), SSL_set_accept_state(), and SSL_set_connect_state().
ossl_statem_connect()
int ossl_statem_connect (SSL * s)
Definition at line 168 of file statem.c.
ossl_statem_get_in_handshake()
int ossl_statem_get_in_handshake (SSL * s)
Definition at line 141 of file statem.c.
Referenced by dtls1_get_record(), dtls1_write_app_data_bytes(), and SSL_ctrl().
ossl_statem_in_error()
int ossl_statem_in_error (const SSL * s)
Definition at line 128 of file statem.c.
References MSG_FLOW_ERROR.
Referenced by SSL_state_string(), and SSL_state_string_long().
ossl_statem_in_sctp_read_sock()
int ossl_statem_in_sctp_read_sock (SSL * s)
Definition at line 834 of file statem.c.
Referenced by dtls1_write_app_data_bytes().
ossl_statem_set_error()
void ossl_statem_set_error (SSL * s)
Definition at line 116 of file statem.c.
References MSG_FLOW_ERROR.
Referenced by ossl_statem_client_pre_work(), ossl_statem_server_post_work(), ossl_statem_server_pre_work(), tls_post_process_client_key_exchange(), tls_prepare_client_certificate(), and tls_process_cert_status().
ossl_statem_set_hello_verify_done()
void ossl_statem_set_hello_verify_done (SSL * s)
Definition at line 154 of file statem.c.
References MSG_FLOW_UNINITED, and TLS_ST_SR_CLNT_HELLO.
ossl_statem_set_in_handshake()
void ossl_statem_set_in_handshake (SSL * s, int inhand)
Definition at line 146 of file statem.c.
ossl_statem_set_in_init()
void ossl_statem_set_in_init (SSL * s, int init)
Definition at line 136 of file statem.c.
Referenced by SSL_key_update().
ossl_statem_set_renegotiate()
void ossl_statem_set_renegotiate (SSL * s)
Definition at line 106 of file statem.c.
References TLS_ST_SW_HELLO_REQ.
ossl_statem_set_sctp_read_sock()
void ossl_statem_set_sctp_read_sock (SSL * s, int read_sock)
Definition at line 821 of file statem.c.
Referenced by ossl_statem_client_post_process_message(), ossl_statem_server_post_process_message(), and tls_post_process_client_key_exchange().
SSL_get_state()
OSSL_HANDSHAKE_STATE SSL_get_state (const SSL * ssl)
Definition at line 64 of file statem.c.
Referenced by dtls1_buffer_record(), SSL_state_string(), and SSL_state_string_long().
SSL_in_before()
int SSL_in_before (SSL * s)
Definition at line 79 of file statem.c.
References MSG_FLOW_UNINITED, and TLS_ST_BEFORE.
Referenced by ssl_clear_bad_session().
SSL_in_init()
int SSL_in_init (SSL * s)
Definition at line 69 of file statem.c.
Referenced by dtls1_get_record(), dtls1_read_failed(), dtls1_write_app_data_bytes(), ssl_clear_bad_session(), SSL_ctrl(), and SSL_shutdown().
SSL_is_init_finished()
int SSL_is_init_finished (SSL * s)
Definition at line 74 of file statem.c.
References TLS_ST_OK.
Referenced by SSL_key_update().
statem_flush()
int statem_flush (SSL * s)
Definition at line 768 of file statem.c.
References BIO_flush, SSL_NOTHING, and SSL_WRITING.
Referenced by ossl_statem_client_post_work(), and ossl_statem_server_post_work().