ssl/statem/statem_dtls.c File Reference
statem_dtls.c File Reference
#include <limits.h>
#include <string.h>
#include <stdio.h>
#include "../ssl_locl.h"
#include "statem_locl.h"
#include <openssl/buffer.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
Macros
#define RSMBLY_BITMASK_SIZE(msg_len) (((msg_len) + 7) / 8)
#define RSMBLY_BITMASK_MARK(bitmask, start, end)
#define RSMBLY_BITMASK_IS_COMPLETE(bitmask, msg_len, is_complete)
Functions
void dtls1_hm_fragment_free (hm_fragment *frag)
int dtls1_do_write (SSL *s, int type)
int dtls_get_message (SSL *s, int *mt, size_t *len)
int dtls_construct_change_cipher_spec (SSL *s, WPACKET *pkt)
WORK_STATE dtls_wait_for_dry (SSL *s)
int dtls1_read_failed (SSL *s, int code)
int dtls1_get_queue_priority (unsigned short seq, int is_ccs)
int dtls1_retransmit_buffered_messages (SSL *s)
int dtls1_buffer_message (SSL *s, int is_ccs)
int dtls1_retransmit_message (SSL *s, unsigned short seq, int *found)
void dtls1_set_message_header (SSL *s, unsigned char mt, size_t len, size_t frag_off, size_t frag_len)
void dtls1_get_message_header (unsigned char *data, struct hm_header_st *msg_hdr)
int dtls1_set_handshake_header (SSL *s, WPACKET *pkt, int htype)
int dtls1_close_construct_packet (SSL *s, WPACKET *pkt, int htype)
Macro Definition Documentation
RSMBLY_BITMASK_IS_COMPLETE
#define RSMBLY_BITMASK_IS_COMPLETE (bitmask, msg_len, is_complete)
Value:
{ \
                        long ii; \
                        OPENSSL_assert((msg_len) > 0); \
                        is_complete = 1; \
                        if (bitmask[(((msg_len) - 1) >> 3)] != bitmask_end_values[((msg_len) & 7)]) is_complete = 0; \
                        if (is_complete) for (ii = (((msg_len) - 1) >> 3) - 1; ii >= 0 ; ii--) \
                                if (bitmask[ii] != 0xff) { is_complete = 0; break; } }
Definition at line 33 of file statem_dtls.c.
RSMBLY_BITMASK_MARK
#define RSMBLY_BITMASK_MARK (bitmask, start, end)
Value:
{ \
                        if ((end) - (start) <= 8) { \
                                long ii; \
                                for (ii = (start); ii < (end); ii++) bitmask[((ii) >> 3)] |= (1 << ((ii) & 7)); \
                        } else { \
                                long ii; \
                                bitmask[((start) >> 3)] |= bitmask_start_values[((start) & 7)]; \
                                for (ii = (((start) >> 3) + 1); ii < ((((end) - 1)) >> 3); ii++) bitmask[ii] = 0xff; \
                                bitmask[(((end) - 1) >> 3)] |= bitmask_end_values[((end) & 7)]; \
                        } }
Definition at line 22 of file statem_dtls.c.
RSMBLY_BITMASK_SIZE
#define RSMBLY_BITMASK_SIZE (msg_len) (((msg_len) + 7) / 8)
Definition at line 20 of file statem_dtls.c.
Function Documentation
dtls1_buffer_message()
int dtls1_buffer_message (SSL * s, int is_ccs)
Definition at line 971 of file statem_dtls.c.
References OPENSSL_assert.
Referenced by dtls1_close_construct_packet().
dtls1_close_construct_packet()
int dtls1_close_construct_packet (SSL * s, WPACKET * pkt, int htype)
Definition at line 1199 of file statem_dtls.c.
References dtls1_buffer_message(), DTLS1_HM_HEADER_LENGTH, DTLS1_MT_HELLO_VERIFY_REQUEST, SSL3_MT_CHANGE_CIPHER_SPEC, WPACKET_close(), and WPACKET_get_length().
dtls1_do_write()
int dtls1_do_write (SSL * s, int type)
Definition at line 110 of file statem_dtls.c.
dtls1_get_message_header()
void dtls1_get_message_header (unsigned char * data, struct hm_header_st * msg_hdr)
Definition at line 1164 of file statem_dtls.c.
References hm_header_st::frag_len, hm_header_st::frag_off, hm_header_st::msg_len, n2l3, n2s, hm_header_st::seq, and hm_header_st::type.
dtls1_get_queue_priority()
int dtls1_get_queue_priority (unsigned short seq, int is_ccs)
Definition at line 934 of file statem_dtls.c.
References hm_header_st::is_ccs.
dtls1_hm_fragment_free()
void dtls1_hm_fragment_free (hm_fragment * frag)
Definition at line 92 of file statem_dtls.c.
References EVP_CIPHER_CTX_free(), EVP_MD_CTX_free(), hm_fragment::fragment, hm_header_st::is_ccs, hm_fragment::msg_header, OPENSSL_free, hm_fragment::reassembly, hm_header_st::saved_retransmit_state, and dtls1_retransmit_state::write_hash.
Referenced by dtls1_clear_received_buffer(), and dtls1_clear_sent_buffer().
dtls1_read_failed()
int dtls1_read_failed (SSL * s, int code)
Definition at line 910 of file statem_dtls.c.
References BIO_FLAGS_READ, BIO_set_flags(), code, dtls1_handle_timeout(), dtls1_is_timer_expired(), ERR_R_INTERNAL_ERROR, SSL_F_DTLS1_READ_FAILED, SSL_get_rbio(), SSL_in_init(), and SSLerr.
dtls1_retransmit_buffered_messages()
int dtls1_retransmit_buffered_messages (SSL * s)
Definition at line 949 of file statem_dtls.c.
Referenced by dtls1_handle_timeout().
dtls1_retransmit_message()
int dtls1_retransmit_message (SSL * s, unsigned short seq, int * found)
Definition at line 1035 of file statem_dtls.c.
dtls1_set_handshake_header()
int dtls1_set_handshake_header (SSL * s, WPACKET * pkt, int htype)
Definition at line 1175 of file statem_dtls.c.
References SSL3_MT_CHANGE_CIPHER_SPEC.
dtls1_set_message_header()
void dtls1_set_message_header (SSL * s, unsigned char mt, size_t len, size_t frag_off, size_t frag_len)
Definition at line 1113 of file statem_dtls.c.
dtls_construct_change_cipher_spec()
int dtls_construct_change_cipher_spec (SSL * s, WPACKET * pkt)
Definition at line 875 of file statem_dtls.c.
References DTLS1_BAD_VER, ERR_R_INTERNAL_ERROR, SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_INTERNAL_ERROR, SSL_F_DTLS_CONSTRUCT_CHANGE_CIPHER_SPEC, SSLerr, and WPACKET_put_bytes_u16.
Referenced by ossl_statem_client_construct_message(), and ossl_statem_server_construct_message().
dtls_get_message()
int dtls_get_message (SSL * s, int * mt, size_t * len)
Definition at line 323 of file statem_dtls.c.
References hm_header_st::msg_len.
dtls_wait_for_dry()
WORK_STATE dtls_wait_for_dry (SSL * s)
Definition at line 890 of file statem_dtls.c.
Referenced by ossl_statem_client_pre_work(), and ossl_statem_server_pre_work().