crypto/des/str2key.c File Reference
str2key.c File Reference
#include <openssl/crypto.h>
#include "des_locl.h"
Functions
void DES_string_to_key (const char *str, DES_cblock *key)
void DES_string_to_2keys (const char *str, DES_cblock *key1, DES_cblock *key2)
Function Documentation
DES_string_to_2keys()
void DES_string_to_2keys (const char * str, DES_cblock * key1, DES_cblock * key2)
Definition at line 45 of file str2key.c.
DES_string_to_key()
void DES_string_to_key (const char * str, DES_cblock * key)
Definition at line 13 of file str2key.c.
References DES_cbc_cksum(), DES_set_key_unchecked(), DES_set_odd_parity(), and OPENSSL_cleanse().