EXTENSION_DEFINITION Struct Reference
EXTENSION_DEFINITION Struct Reference
Data Fields
unsigned int type
unsigned int context
int(* init)(SSL *s, unsigned int context)
int(* parse_ctos)(SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int(* parse_stoc)(SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int(* construct_stoc)(SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int(* construct_ctos)(SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
int(* final)(SSL *s, unsigned int context, int sent, int *al)
Detailed Description
Definition at line 48 of file extensions.c.
Field Documentation
construct_ctos
int(* construct_ctos) (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
Definition at line 71 of file extensions.c.
Referenced by tls_construct_extensions().
construct_stoc
int(* construct_stoc) (SSL *s, WPACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
Definition at line 68 of file extensions.c.
Referenced by tls_construct_extensions().
context
unsigned int context
Definition at line 55 of file extensions.c.
Referenced by tls_construct_extensions(), and tls_parse_all_extensions().
final
int(* final) (SSL *s, unsigned int context, int sent, int *al)
Definition at line 78 of file extensions.c.
Referenced by tls_parse_all_extensions().
init
int(* init) (SSL *s, unsigned int context)
Definition at line 60 of file extensions.c.
parse_ctos
int(* parse_ctos) (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
Definition at line 62 of file extensions.c.
parse_stoc
int(* parse_stoc) (SSL *s, PACKET *pkt, unsigned int context, X509 *x, size_t chainidx, int *al)
Definition at line 65 of file extensions.c.
type
unsigned int type
Definition at line 50 of file extensions.c.
The documentation for this struct was generated from the following file:
ssl/statem/extensions.c