ssl/t1_ext.c File Reference
t1_ext.c File Reference
#include <openssl/ct.h>
#include "ssl_locl.h"
Functions
void custom_ext_init (custom_ext_methods *exts)
int custom_ext_parse (SSL *s, int server, unsigned int ext_type, const unsigned char *ext_data, size_t ext_size, int *al)
int custom_ext_add (SSL *s, int server, WPACKET *pkt, int *al)
int custom_exts_copy (custom_ext_methods *dst, const custom_ext_methods *src)
void custom_exts_free (custom_ext_methods *exts)
int SSL_CTX_has_client_custom_ext (const SSL_CTX *ctx, unsigned int ext_type)
int SSL_CTX_add_client_custom_ext (SSL_CTX *ctx, unsigned int ext_type, custom_ext_add_cb add_cb, custom_ext_free_cb free_cb, void *add_arg, custom_ext_parse_cb parse_cb, void *parse_arg)
int SSL_CTX_add_server_custom_ext (SSL_CTX *ctx, unsigned int ext_type, custom_ext_add_cb add_cb, custom_ext_free_cb free_cb, void *add_arg, custom_ext_parse_cb parse_cb, void *parse_arg)
int SSL_extension_supported (unsigned int ext_type)
Function Documentation
custom_ext_add()
int custom_ext_add (SSL * s, int server, WPACKET * pkt, int * al)
Definition at line 77 of file t1_ext.c.
References custom_ext_methods::meths_count.
Referenced by tls_construct_extensions().
custom_ext_init()
void custom_ext_init (custom_ext_methods * exts)
Definition at line 31 of file t1_ext.c.
References custom_ext_method::ext_flags, custom_ext_methods::meths, and custom_ext_methods::meths_count.
Referenced by tls_collect_extensions(), and tls_construct_extensions().
custom_ext_parse()
int custom_ext_parse (SSL * s, int server, unsigned int ext_type, const unsigned char * ext_data, size_t ext_size, int * al)
Definition at line 40 of file t1_ext.c.
custom_exts_copy()
int custom_exts_copy (custom_ext_methods * dst, const custom_ext_methods * src)
Definition at line 133 of file t1_ext.c.
References custom_ext_methods::meths, custom_ext_methods::meths_count, NULL, and OPENSSL_memdup.
custom_exts_free()
void custom_exts_free (custom_ext_methods * exts)
Definition at line 146 of file t1_ext.c.
References custom_ext_methods::meths, and OPENSSL_free.
SSL_CTX_add_client_custom_ext()
int SSL_CTX_add_client_custom_ext (SSL_CTX * ctx, unsigned int ext_type, custom_ext_add_cb add_cb, custom_ext_free_cb free_cb, void * add_arg, custom_ext_parse_cb parse_cb, void * parse_arg)
Definition at line 205 of file t1_ext.c.
References SSL_CTX_ct_is_enabled(), and TLSEXT_TYPE_signed_certificate_timestamp.
SSL_CTX_add_server_custom_ext()
int SSL_CTX_add_server_custom_ext (SSL_CTX * ctx, unsigned int ext_type, custom_ext_add_cb add_cb, custom_ext_free_cb free_cb, void * add_arg, custom_ext_parse_cb parse_cb, void * parse_arg)
Definition at line 225 of file t1_ext.c.
SSL_CTX_has_client_custom_ext()
int SSL_CTX_has_client_custom_ext (const SSL_CTX * ctx, unsigned int ext_type)
Definition at line 199 of file t1_ext.c.
SSL_extension_supported()
int SSL_extension_supported (unsigned int ext_type)
Definition at line 235 of file t1_ext.c.
References TLSEXT_TYPE_application_layer_protocol_negotiation, TLSEXT_TYPE_ec_point_formats, TLSEXT_TYPE_encrypt_then_mac, TLSEXT_TYPE_extended_master_secret, TLSEXT_TYPE_key_share, TLSEXT_TYPE_next_proto_neg, TLSEXT_TYPE_padding, TLSEXT_TYPE_renegotiate, TLSEXT_TYPE_server_name, TLSEXT_TYPE_session_ticket, TLSEXT_TYPE_signature_algorithms, TLSEXT_TYPE_signed_certificate_timestamp, TLSEXT_TYPE_srp, TLSEXT_TYPE_status_request, TLSEXT_TYPE_supported_groups, TLSEXT_TYPE_supported_versions, and TLSEXT_TYPE_use_srtp.