ssl/t1_enc.c File Reference
t1_enc.c File Reference
#include <stdio.h>
#include "ssl_locl.h"
#include <openssl/comp.h>
#include <openssl/evp.h>
#include <openssl/kdf.h>
#include <openssl/rand.h>
Functions
int tls1_change_cipher_state (SSL *s, int which)
int tls1_setup_key_block (SSL *s)
size_t tls1_final_finish_mac (SSL *s, const char *str, size_t slen, unsigned char *out)
int tls1_generate_master_secret (SSL *s, unsigned char *out, unsigned char *p, size_t len, size_t *secret_size)
int tls1_export_keying_material (SSL *s, unsigned char *out, size_t olen, const char *label, size_t llen, const unsigned char *context, size_t contextlen, int use_context)
int tls1_alert_code (int code)
Function Documentation
tls1_alert_code()
int tls1_alert_code (int code)
Definition at line 642 of file t1_enc.c.
References SSL3_AD_BAD_CERTIFICATE, SSL3_AD_BAD_RECORD_MAC, SSL3_AD_CERTIFICATE_EXPIRED, SSL3_AD_CERTIFICATE_REVOKED, SSL3_AD_CERTIFICATE_UNKNOWN, SSL3_AD_CLOSE_NOTIFY, SSL3_AD_DECOMPRESSION_FAILURE, SSL3_AD_HANDSHAKE_FAILURE, SSL3_AD_ILLEGAL_PARAMETER, SSL3_AD_UNEXPECTED_MESSAGE, SSL3_AD_UNSUPPORTED_CERTIFICATE, SSL_AD_ACCESS_DENIED, SSL_AD_BAD_CERTIFICATE, SSL_AD_BAD_CERTIFICATE_HASH_VALUE, SSL_AD_BAD_CERTIFICATE_STATUS_RESPONSE, SSL_AD_BAD_RECORD_MAC, SSL_AD_CERTIFICATE_EXPIRED, SSL_AD_CERTIFICATE_REVOKED, SSL_AD_CERTIFICATE_UNKNOWN, SSL_AD_CERTIFICATE_UNOBTAINABLE, SSL_AD_CLOSE_NOTIFY, SSL_AD_DECODE_ERROR, SSL_AD_DECOMPRESSION_FAILURE, SSL_AD_DECRYPT_ERROR, SSL_AD_DECRYPTION_FAILED, SSL_AD_EXPORT_RESTRICTION, SSL_AD_HANDSHAKE_FAILURE, SSL_AD_ILLEGAL_PARAMETER, SSL_AD_INAPPROPRIATE_FALLBACK, SSL_AD_INSUFFICIENT_SECURITY, SSL_AD_INTERNAL_ERROR, SSL_AD_NO_APPLICATION_PROTOCOL, SSL_AD_NO_CERTIFICATE, SSL_AD_NO_RENEGOTIATION, SSL_AD_PROTOCOL_VERSION, SSL_AD_RECORD_OVERFLOW, SSL_AD_UNEXPECTED_MESSAGE, SSL_AD_UNKNOWN_CA, SSL_AD_UNKNOWN_PSK_IDENTITY, SSL_AD_UNRECOGNIZED_NAME, SSL_AD_UNSUPPORTED_CERTIFICATE, SSL_AD_UNSUPPORTED_EXTENSION, SSL_AD_USER_CANCELLED, TLS1_AD_ACCESS_DENIED, TLS1_AD_BAD_CERTIFICATE_HASH_VALUE, TLS1_AD_BAD_CERTIFICATE_STATUS_RESPONSE, TLS1_AD_CERTIFICATE_UNOBTAINABLE, TLS1_AD_DECODE_ERROR, TLS1_AD_DECRYPT_ERROR, TLS1_AD_DECRYPTION_FAILED, TLS1_AD_EXPORT_RESTRICTION, TLS1_AD_INAPPROPRIATE_FALLBACK, TLS1_AD_INSUFFICIENT_SECURITY, TLS1_AD_INTERNAL_ERROR, TLS1_AD_NO_APPLICATION_PROTOCOL, TLS1_AD_NO_RENEGOTIATION, TLS1_AD_PROTOCOL_VERSION, TLS1_AD_RECORD_OVERFLOW, TLS1_AD_UNKNOWN_CA, TLS1_AD_UNKNOWN_PSK_IDENTITY, TLS1_AD_UNRECOGNIZED_NAME, TLS1_AD_UNSUPPORTED_EXTENSION, and TLS1_AD_USER_CANCELLED.
tls1_change_cipher_state()
int tls1_change_cipher_state (SSL * s, int which)
Definition at line 103 of file t1_enc.c.
References EVP_MAX_IV_LENGTH, EVP_MAX_KEY_LENGTH, and key.
tls1_export_keying_material()
int tls1_export_keying_material (SSL * s, unsigned char * out, size_t olen, const char * label, size_t llen, const unsigned char * context, size_t contextlen, int use_context)
Definition at line 559 of file t1_enc.c.
References NULL, OPENSSL_malloc, SSL3_RANDOM_SIZE, TLS_MD_CLIENT_FINISH_CONST, TLS_MD_CLIENT_FINISH_CONST_SIZE, TLS_MD_EXTENDED_MASTER_SECRET_CONST, TLS_MD_EXTENDED_MASTER_SECRET_CONST_SIZE, TLS_MD_KEY_EXPANSION_CONST, TLS_MD_KEY_EXPANSION_CONST_SIZE, TLS_MD_MASTER_SECRET_CONST, TLS_MD_MASTER_SECRET_CONST_SIZE, TLS_MD_SERVER_FINISH_CONST, and TLS_MD_SERVER_FINISH_CONST_SIZE.
tls1_final_finish_mac()
size_t tls1_final_finish_mac (SSL * s, const char * str, size_t slen, unsigned char * out)
Definition at line 463 of file t1_enc.c.
References EVP_MAX_MD_SIZE, ssl3_digest_cached_records(), and ssl_handshake_hash().
tls1_generate_master_secret()
int tls1_generate_master_secret (SSL * s, unsigned char * out, unsigned char * p, size_t len, size_t * secret_size)
Definition at line 483 of file t1_enc.c.
References BIO_dump_fp(), EVP_MAX_MD_SIZE, ssl3_digest_cached_records(), ssl_handshake_hash(), SSL_IS_TLS13, and SSL_SESS_FLAG_EXTMS.
tls1_setup_key_block()
int tls1_setup_key_block (SSL * s)
Definition at line 369 of file t1_enc.c.