ssl/t1_lib.c File Reference
t1_lib.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/hmac.h>
#include <openssl/ocsp.h>
#include <openssl/conf.h>
#include <openssl/x509v3.h>
#include <openssl/dh.h>
#include <openssl/bn.h>
#include "ssl_locl.h"
#include <openssl/ct.h>
Data Structures
struct tls_curve_info
struct nid_cb_st
struct sig_cb_st
Macros
#define MAX_CURVELIST 28
#define TLS_MAX_SIGALGCNT (OSSL_NELEM(sigalg_lookup_tbl) * 2)
#define TLS_MAX_SIGSTRING_LEN 40
#define CERT_PKEY_VALID_FLAGS (CERT_PKEY_EE_SIGNATURE|CERT_PKEY_EE_PARAM)
#define CERT_PKEY_STRICT_FLAGS
Functions
long tls1_default_timeout (void)
int tls1_new (SSL *s)
void tls1_free (SSL *s)
void tls1_clear (SSL *s)
int tls1_ec_curve_id2nid (int curve_id, unsigned int *pflags)
int tls1_ec_nid2curve_id (int nid)
int tls1_get_curvelist (SSL *s, int sess, const unsigned char **pcurves, size_t *num_curves)
int tls_curve_allowed (SSL *s, const unsigned char *curve, int op)
int tls1_check_curve (SSL *s, const unsigned char *p, size_t len)
int tls1_shared_group (SSL *s, int nmatch)
int tls1_set_groups (unsigned char **pext, size_t *pextlen, int *groups, size_t ngroups)
int tls1_set_groups_list (unsigned char **pext, size_t *pextlen, const char *str)
void tls1_get_formatlist (SSL *s, const unsigned char **pformats, size_t *num_formats)
int tls1_check_ec_tmp_key (SSL *s, unsigned long cid)
int tls1_set_peer_legacy_sigalg (SSL *s, const EVP_PKEY *pkey)
size_t tls12_get_psigalgs (SSL *s, int sent, const uint16_t **psigs)
int tls12_check_peer_sigalg (SSL *s, uint16_t sig, EVP_PKEY *pkey)
int SSL_get_peer_signature_type_nid (const SSL *s, int *pnid)
void ssl_set_client_disabled (SSL *s)
int ssl_cipher_disabled (SSL *s, const SSL_CIPHER *c, int op)
int tls_use_ticket (SSL *s)
void ssl_set_default_md (SSL *s)
int tls1_set_server_sigalgs (SSL *s)
TICKET_RETURN tls_get_ticket_from_client (SSL *s, CLIENTHELLO_MSG *hello, SSL_SESSION **ret)
TICKET_RETURN tls_decrypt_ticket (SSL *s, const unsigned char *etick, size_t eticklen, const unsigned char *sess_id, size_t sesslen, SSL_SESSION **psess)
void ssl_set_sig_mask (uint32_t *pmask_a, SSL *s, int op)
int tls12_copy_sigalgs (SSL *s, WPACKET *pkt, const uint16_t *psig, size_t psiglen)
int tls1_save_sigalgs (SSL *s, PACKET *pkt)
int tls1_process_sigalgs (SSL *s)
int SSL_get_sigalgs (SSL *s, int idx, int *psign, int *phash, int *psignhash, unsigned char *rsig, unsigned char *rhash)
int SSL_get_shared_sigalgs (SSL *s, int idx, int *psign, int *phash, int *psignhash, unsigned char *rsig, unsigned char *rhash)
int tls1_set_sigalgs_list (CERT *c, const char *str, int client)
int tls1_set_sigalgs (CERT *c, const int *psig_nids, size_t salglen, int client)
int tls1_check_chain (SSL *s, X509 *x, EVP_PKEY *pk, STACK_OF(X509) *chain, int idx)
void tls1_set_cert_validity (SSL *s)
int SSL_check_chain (SSL *s, X509 *x, EVP_PKEY *pk, STACK_OF(X509) *chain)
DH * ssl_get_auto_dh (SSL *s)
int ssl_security_cert (SSL *s, SSL_CTX *ctx, X509 *x, int vfy, int is_ee)
int ssl_security_cert_chain (SSL *s, STACK_OF(X509) *sk, X509 *x, int vfy)
int tls_choose_sigalg (SSL *s, int *al)
Variables
SSL3_ENC_METHOD const TLSv1_enc_data
SSL3_ENC_METHOD const TLSv1_1_enc_data
SSL3_ENC_METHOD const TLSv1_2_enc_data
SSL3_ENC_METHOD const TLSv1_3_enc_data
Macro Definition Documentation
CERT_PKEY_STRICT_FLAGS
#define CERT_PKEY_STRICT_FLAGS
Value:
(CERT_PKEY_VALID_FLAGS|CERT_PKEY_CA_SIGNATURE|CERT_PKEY_CA_PARAM \
         | CERT_PKEY_ISSUER_NAME|CERT_PKEY_CERT_TYPE)
Definition at line 1871 of file t1_lib.c.
CERT_PKEY_VALID_FLAGS
#define CERT_PKEY_VALID_FLAGS (CERT_PKEY_EE_SIGNATURE|CERT_PKEY_EE_PARAM)
Definition at line 1868 of file t1_lib.c.
MAX_CURVELIST
#define MAX_CURVELIST 28
Definition at line 416 of file t1_lib.c.
TLS_MAX_SIGALGCNT
#define TLS_MAX_SIGALGCNT (OSSL_NELEM(sigalg_lookup_tbl) * 2)
Definition at line 1697 of file t1_lib.c.
TLS_MAX_SIGSTRING_LEN
#define TLS_MAX_SIGSTRING_LEN 40
Definition at line 1721 of file t1_lib.c.
Function Documentation
SSL_check_chain()
int SSL_check_chain (SSL * s, X509 * x, EVP_PKEY * pk, STACK_OF(X509) * chain)
Definition at line 2135 of file t1_lib.c.
References tls1_check_chain().
ssl_cipher_disabled()
int ssl_cipher_disabled (SSL * s, const SSL_CIPHER * c, int op)
Definition at line 1041 of file t1_lib.c.
ssl_get_auto_dh()
DH* ssl_get_auto_dh (SSL * s)
Definition at line 2141 of file t1_lib.c.
References BN_free(), BN_get_rfc3526_prime_3072(), BN_get_rfc3526_prime_8192(), BN_new(), BN_set_word(), DH_free(), DH_get_1024_160(), DH_get_2048_224(), DH_new(), DH_set0_pqg(), EVP_PKEY_security_bits(), NULL, SSL_aNULL, and SSL_aPSK.
SSL_get_peer_signature_type_nid()
int SSL_get_peer_signature_type_nid (const SSL * s, int * pnid)
Definition at line 994 of file t1_lib.c.
References NULL.
SSL_get_shared_sigalgs()
int SSL_get_shared_sigalgs (SSL * s, int idx, int * psign, int * phash, int * psignhash, unsigned char * rsig, unsigned char * rhash)
Definition at line 1672 of file t1_lib.c.
SSL_get_sigalgs()
int SSL_get_sigalgs (SSL * s, int idx, int * psign, int * phash, int * psignhash, unsigned char * rsig, unsigned char * rhash)
Definition at line 1643 of file t1_lib.c.
ssl_security_cert()
int ssl_security_cert (SSL * s, SSL_CTX * ctx, X509 * x, int vfy, int is_ee)
Definition at line 2221 of file t1_lib.c.
References SSL_SECOP_PEER.
Referenced by ssl_build_cert_chain(), ssl_cert_add0_chain_cert(), ssl_cert_set0_chain(), SSL_CTX_use_certificate(), ssl_security_cert_chain(), and SSL_use_certificate().
ssl_security_cert_chain()
int ssl_security_cert_chain (SSL * s, STACK_OF(X509) * sk, X509 * x, int vfy)
Definition at line 2243 of file t1_lib.c.
References NULL, and ssl_security_cert().
ssl_set_client_disabled()
void ssl_set_client_disabled (SSL * s)
Definition at line 1012 of file t1_lib.c.
References SSL_aPSK, SSL_aSRP, ssl_get_client_min_max_version(), SSL_kSRP, SSL_PSK, SSL_SECOP_SIGALG_MASK, and ssl_set_sig_mask().
Referenced by STACK_OF().
ssl_set_default_md()
void ssl_set_default_md (SSL * s)
Definition at line 1066 of file t1_lib.c.
References ssl_md(), SSL_MD_GOST12_256_IDX, SSL_MD_GOST12_512_IDX, SSL_MD_GOST94_IDX, SSL_MD_MD5_SHA1_IDX, SSL_MD_SHA1_IDX, SSL_PKEY_DSA_SIGN, SSL_PKEY_ECC, SSL_PKEY_GOST01, SSL_PKEY_GOST12_256, SSL_PKEY_GOST12_512, SSL_PKEY_RSA, and SSL_USE_SIGALGS.
Referenced by tls1_set_server_sigalgs().
ssl_set_sig_mask()
void ssl_set_sig_mask (uint32_t * pmask_a, SSL * s, int op)
Definition at line 1414 of file t1_lib.c.
References tls12_get_psigalgs().
Referenced by ssl3_get_req_cert_type(), and ssl_set_client_disabled().
tls12_check_peer_sigalg()
int tls12_check_peer_sigalg (SSL * s, uint16_t sig, EVP_PKEY * pkey)
Definition at line 887 of file t1_lib.c.
tls12_copy_sigalgs()
int tls12_copy_sigalgs (SSL * s, WPACKET * pkt, const uint16_t * psig, size_t psiglen)
Definition at line 1457 of file t1_lib.c.
Referenced by tls_construct_ctos_sig_algs().
tls12_get_psigalgs()
size_t tls12_get_psigalgs (SSL * s, int sent, const uint16_t ** psigs)
Definition at line 844 of file t1_lib.c.
References SSL_CERT_FLAG_SUITEB_128_LOS, and tls1_suiteb.
Referenced by ssl_set_sig_mask(), and tls_construct_ctos_sig_algs().
tls1_check_chain()
int tls1_check_chain (SSL * s, X509 * x, EVP_PKEY * pk, STACK_OF(X509) * chain, int idx)
Definition at line 1875 of file t1_lib.c.
Referenced by SSL_check_chain(), and tls1_set_cert_validity().
tls1_check_curve()
int tls1_check_curve (SSL * s, const unsigned char * p, size_t len)
Definition at line 284 of file t1_lib.c.
References NAMED_CURVE_TYPE, SSL_SECOP_CURVE_CHECK, TLS1_CK_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS1_CK_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, tls1_get_curvelist(), tls1_suiteb, tls_curve_allowed(), TLSEXT_curve_P_256, and TLSEXT_curve_P_384.
tls1_check_ec_tmp_key()
int tls1_check_ec_tmp_key (SSL * s, unsigned long cid)
Definition at line 635 of file t1_lib.c.
References TLS1_CK_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS1_CK_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, tls1_suiteb, TLSEXT_curve_P_256, and TLSEXT_curve_P_384.
tls1_clear()
void tls1_clear (SSL * s)
Definition at line 115 of file t1_lib.c.
References ssl3_clear(), TLS_ANY_VERSION, and TLS_MAX_VERSION.
tls1_default_timeout()
long tls1_default_timeout (void)
Definition at line 92 of file t1_lib.c.
tls1_ec_curve_id2nid()
int tls1_ec_curve_id2nid (int curve_id, unsigned int * pflags)
Definition at line 188 of file t1_lib.c.
References tls_curve_info::flags, tls_curve_info::nid, and OSSL_NELEM.
tls1_ec_nid2curve_id()
int tls1_ec_nid2curve_id (int nid)
Definition at line 200 of file t1_lib.c.
References OSSL_NELEM.
Referenced by tls1_set_groups().
tls1_free()
void tls1_free (SSL * s)
Definition at line 109 of file t1_lib.c.
References OPENSSL_free, and ssl3_free().
tls1_get_curvelist()
int tls1_get_curvelist (SSL * s, int sess, const unsigned char ** pcurves, size_t * num_curves)
Definition at line 222 of file t1_lib.c.
References SSL_CERT_FLAG_SUITEB_128_LOS, and tls1_suiteb.
Referenced by tls1_check_curve(), and tls_construct_ctos_key_share().
tls1_get_formatlist()
void tls1_get_formatlist (SSL * s, const unsigned char ** pformats, size_t * num_formats)
Definition at line 548 of file t1_lib.c.
Referenced by tls_construct_stoc_ec_pt_formats().
tls1_new()
int tls1_new (SSL * s)
Definition at line 101 of file t1_lib.c.
References ssl3_new().
tls1_process_sigalgs()
int tls1_process_sigalgs (SSL * s)
Definition at line 1581 of file t1_lib.c.
Referenced by tls1_set_server_sigalgs().
tls1_save_sigalgs()
int tls1_save_sigalgs (SSL * s, PACKET * pkt)
Definition at line 1545 of file t1_lib.c.
tls1_set_cert_validity()
void tls1_set_cert_validity (SSL * s)
Definition at line 2124 of file t1_lib.c.
References NULL, SSL_PKEY_DSA_SIGN, SSL_PKEY_ECC, SSL_PKEY_GOST01, SSL_PKEY_GOST12_256, SSL_PKEY_GOST12_512, SSL_PKEY_RSA, and tls1_check_chain().
tls1_set_groups()
int tls1_set_groups (unsigned char ** pext, size_t * pextlen, int * groups, size_t ngroups)
Definition at line 384 of file t1_lib.c.
References NULL, OPENSSL_free, OPENSSL_malloc, s2n, and tls1_ec_nid2curve_id().
Referenced by ssl3_ctx_ctrl().
tls1_set_groups_list()
int tls1_set_groups_list (unsigned char ** pext, size_t * pextlen, const char * str)
Definition at line 452 of file t1_lib.c.
References CONF_parse_list(), and nid_cb_st::nidcnt.
Referenced by SSL_CTX_ctrl().
tls1_set_peer_legacy_sigalg()
int tls1_set_peer_legacy_sigalg (SSL * s, const EVP_PKEY * pkey)
Definition at line 826 of file t1_lib.c.
tls1_set_server_sigalgs()
int tls1_set_server_sigalgs (SSL * s)
Definition at line 1088 of file t1_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_free, SSL3_AL_FATAL, ssl3_send_alert(), SSL_AD_ILLEGAL_PARAMETER, SSL_AD_INTERNAL_ERROR, SSL_F_TLS1_SET_SERVER_SIGALGS, SSL_PKEY_NUM, SSL_R_NO_SHARED_SIGNATURE_ALGORITHMS, ssl_set_default_md(), SSLerr, and tls1_process_sigalgs().
tls1_set_sigalgs()
int tls1_set_sigalgs (CERT * c, const int * psig_nids, size_t salglen, int client)
Definition at line 1786 of file t1_lib.c.
tls1_set_sigalgs_list()
int tls1_set_sigalgs_list (CERT * c, const char * str, int client)
Definition at line 1775 of file t1_lib.c.
Referenced by SSL_CTX_ctrl().
tls1_shared_group()
int tls1_shared_group (SSL * s, int nmatch)
Definition at line 321 of file t1_lib.c.
tls_choose_sigalg()
int tls_choose_sigalg (SSL * s, int * al)
Definition at line 2276 of file t1_lib.c.
tls_curve_allowed()
int tls_curve_allowed (SSL * s, const unsigned char * curve, int op)
Definition at line 268 of file t1_lib.c.
References tls_curve_info::flags, tls_curve_info::nid, OSSL_NELEM, tls_curve_info::secbits, ssl_security(), and TLS_CURVE_CHAR2.
Referenced by check_in_list(), tls1_check_curve(), and tls_construct_ctos_key_share().
tls_decrypt_ticket()
TICKET_RETURN tls_decrypt_ticket (SSL * s, const unsigned char * etick, size_t eticklen, const unsigned char * sess_id, size_t sesslen, SSL_SESSION ** psess)
Definition at line 1224 of file t1_lib.c.
tls_get_ticket_from_client()
TICKET_RETURN tls_get_ticket_from_client (SSL * s, CLIENTHELLO_MSG * hello, SSL_SESSION ** ret)
Definition at line 1154 of file t1_lib.c.
tls_use_ticket()
int tls_use_ticket (SSL * s)
Definition at line 1058 of file t1_lib.c.
References NULL, SSL_OP_NO_TICKET, SSL_SECOP_TICKET, and ssl_security().
Referenced by tls_construct_ctos_session_ticket(), and tls_construct_stoc_session_ticket().
Variable Documentation
TLSv1_1_enc_data
SSL3_ENC_METHOD const TLSv1_1_enc_data
Initial value:
= {
    tls1_enc,
    tls1_mac,
    tls1_setup_key_block,
    tls1_generate_master_secret,
    tls1_change_cipher_state,
    tls1_final_finish_mac,
    TLS_MD_CLIENT_FINISH_CONST, TLS_MD_CLIENT_FINISH_CONST_SIZE,
    TLS_MD_SERVER_FINISH_CONST, TLS_MD_SERVER_FINISH_CONST_SIZE,
    tls1_alert_code,
    tls1_export_keying_material,
    SSL_ENC_FLAG_EXPLICIT_IV,
    ssl3_set_handshake_header,
    tls_close_construct_packet,
    ssl3_handshake_write
}
Definition at line 40 of file t1_lib.c.
TLSv1_2_enc_data
SSL3_ENC_METHOD const TLSv1_2_enc_data
Initial value:
= {
    tls1_enc,
    tls1_mac,
    tls1_setup_key_block,
    tls1_generate_master_secret,
    tls1_change_cipher_state,
    tls1_final_finish_mac,
    TLS_MD_CLIENT_FINISH_CONST, TLS_MD_CLIENT_FINISH_CONST_SIZE,
    TLS_MD_SERVER_FINISH_CONST, TLS_MD_SERVER_FINISH_CONST_SIZE,
    tls1_alert_code,
    tls1_export_keying_material,
    SSL_ENC_FLAG_EXPLICIT_IV | SSL_ENC_FLAG_SIGALGS | SSL_ENC_FLAG_SHA256_PRF
        | SSL_ENC_FLAG_TLS1_2_CIPHERS,
    ssl3_set_handshake_header,
    tls_close_construct_packet,
    ssl3_handshake_write
}
Definition at line 57 of file t1_lib.c.
TLSv1_3_enc_data
SSL3_ENC_METHOD const TLSv1_3_enc_data
Initial value:
= {
    tls13_enc,
    tls1_mac,
    tls13_setup_key_block,
    tls13_generate_master_secret,
    tls13_change_cipher_state,
    tls13_final_finish_mac,
    TLS_MD_CLIENT_FINISH_CONST, TLS_MD_CLIENT_FINISH_CONST_SIZE,
    TLS_MD_SERVER_FINISH_CONST, TLS_MD_SERVER_FINISH_CONST_SIZE,
    tls13_alert_code,
    tls1_export_keying_material,
    SSL_ENC_FLAG_SIGALGS | SSL_ENC_FLAG_SHA256_PRF,
    ssl3_set_handshake_header,
    tls_close_construct_packet,
    ssl3_handshake_write
}
Definition at line 75 of file t1_lib.c.
TLSv1_enc_data
SSL3_ENC_METHOD const TLSv1_enc_data
Initial value:
= {
    tls1_enc,
    tls1_mac,
    tls1_setup_key_block,
    tls1_generate_master_secret,
    tls1_change_cipher_state,
    tls1_final_finish_mac,
    TLS_MD_CLIENT_FINISH_CONST, TLS_MD_CLIENT_FINISH_CONST_SIZE,
    TLS_MD_SERVER_FINISH_CONST, TLS_MD_SERVER_FINISH_CONST_SIZE,
    tls1_alert_code,
    tls1_export_keying_material,
    0,
    ssl3_set_handshake_header,
    tls_close_construct_packet,
    ssl3_handshake_write
}
Definition at line 23 of file t1_lib.c.