crypto/asn1/t_bitst.c File Reference
t_bitst.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/conf.h>
#include <openssl/x509v3.h>
Functions
int ASN1_BIT_STRING_name_print (BIO *out, ASN1_BIT_STRING *bs, BIT_STRING_BITNAME *tbl, int indent)
int ASN1_BIT_STRING_set_asc (ASN1_BIT_STRING *bs, const char *name, int value, BIT_STRING_BITNAME *tbl)
int ASN1_BIT_STRING_num_asc (const char *name, BIT_STRING_BITNAME *tbl)
Function Documentation
ASN1_BIT_STRING_name_print()
int ASN1_BIT_STRING_name_print (BIO * out, ASN1_BIT_STRING * bs, BIT_STRING_BITNAME * tbl, int indent)
Definition at line 15 of file t_bitst.c.
ASN1_BIT_STRING_num_asc()
int ASN1_BIT_STRING_num_asc (const char * name, BIT_STRING_BITNAME * tbl)
Definition at line 47 of file t_bitst.c.
References BIT_STRING_BITNAME::bitnum, BIT_STRING_BITNAME::lname, and BIT_STRING_BITNAME::sname.
Referenced by ASN1_BIT_STRING_set_asc().
ASN1_BIT_STRING_set_asc()
int ASN1_BIT_STRING_set_asc (ASN1_BIT_STRING * bs, const char * name, int value, BIT_STRING_BITNAME * tbl)
Definition at line 33 of file t_bitst.c.
References ASN1_BIT_STRING_num_asc(), and ASN1_BIT_STRING_set_bit().