crypto/asn1/tasn_enc.c File Reference
tasn_enc.c File Reference
#include <stddef.h>
#include <string.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include <openssl/objects.h>
#include "internal/asn1_int.h"
#include "asn1_locl.h"
Data Structures
struct DER_ENC
Functions
int ASN1_item_ndef_i2d (ASN1_VALUE *val, unsigned char **out, const ASN1_ITEM *it)
int ASN1_item_i2d (ASN1_VALUE *val, unsigned char **out, const ASN1_ITEM *it)
int ASN1_item_ex_i2d (ASN1_VALUE **pval, unsigned char **out, const ASN1_ITEM *it, int tag, int aclass)
Function Documentation
ASN1_item_ex_i2d()
int ASN1_item_ex_i2d (ASN1_VALUE ** pval, unsigned char ** out, const ASN1_ITEM * it, int tag, int aclass)
Definition at line 80 of file tasn_enc.c.
References NULL.
ASN1_item_i2d()
int ASN1_item_i2d (ASN1_VALUE * val, unsigned char ** out, const ASN1_ITEM * it)
Definition at line 42 of file tasn_enc.c.
Referenced by ASN1_item_pack(), ASN1_item_sign_ctx(), OCSP_REQ_CTX_i2d(), PKCS12_item_i2d_encrypt(), PKCS7_add_attrib_smimecap(), PKCS7_signatureVerify(), and X509_REQ_add_extensions_nid().
ASN1_item_ndef_i2d()
int ASN1_item_ndef_i2d (ASN1_VALUE * val, unsigned char ** out, const ASN1_ITEM * it)
Definition at line 36 of file tasn_enc.c.