crypto/asn1/tasn_fre.c File Reference
tasn_fre.c File Reference
#include <stddef.h>
#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include <openssl/objects.h>
#include "asn1_locl.h"
Functions
void ASN1_item_free (ASN1_VALUE *val, const ASN1_ITEM *it)
void ASN1_item_ex_free (ASN1_VALUE **pval, const ASN1_ITEM *it)
void asn1_template_free (ASN1_VALUE **pval, const ASN1_TEMPLATE *tt)
void asn1_primitive_free (ASN1_VALUE **pval, const ASN1_ITEM *it, int embed)
Function Documentation
ASN1_item_ex_free()
void ASN1_item_ex_free (ASN1_VALUE ** pval, const ASN1_ITEM * it)
Definition at line 26 of file tasn_fre.c.
ASN1_item_free()
void ASN1_item_free (ASN1_VALUE * val, const ASN1_ITEM * it)
Definition at line 21 of file tasn_fre.c.
asn1_primitive_free()
void asn1_primitive_free (ASN1_VALUE ** pval, const ASN1_ITEM * it, int embed)
Definition at line 150 of file tasn_fre.c.
References ASN1_ITYPE_MSTRING, ASN1_OBJECT_free(), asn1_string_embed_free(), ASN1_TYPE::asn1_value, NULL, OPENSSL_free, ASN1_PRIMITIVE_FUNCS::prim_free, ASN1_TYPE::type, V_ASN1_ANY, V_ASN1_BOOLEAN, V_ASN1_NULL, V_ASN1_OBJECT, and ASN1_TYPE::value.
Referenced by ASN1_TYPE_set().
asn1_template_free()
void asn1_template_free (ASN1_VALUE ** pval, const ASN1_TEMPLATE * tt)
Definition at line 126 of file tasn_fre.c.
References ASN1_TFLG_EMBED, ASN1_TFLG_SK_MASK, and STACK_OF.