crypto/asn1/tasn_dec.c File Reference
tasn_dec.c File Reference
#include <stddef.h>
#include <string.h>
#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include <openssl/objects.h>
#include <openssl/buffer.h>
#include <openssl/err.h>
#include "internal/numbers.h"
#include "asn1_locl.h"
Macros
#define asn1_tlc_clear(c) if (c) (c)->valid = 0
#define asn1_tlc_clear_nc(c) (c)->valid = 0
#define ASN1_MAX_STRING_NEST 5
Functions
unsigned long ASN1_tag2bit (int tag)
ASN1_VALUE * ASN1_item_d2i (ASN1_VALUE **pval, const unsigned char **in, long len, const ASN1_ITEM *it)
int ASN1_item_ex_d2i (ASN1_VALUE **pval, const unsigned char **in, long len, const ASN1_ITEM *it, int tag, int aclass, char opt, ASN1_TLC *ctx)
Macro Definition Documentation
ASN1_MAX_STRING_NEST
#define ASN1_MAX_STRING_NEST 5
Definition at line 963 of file tasn_dec.c.
asn1_tlc_clear
#define asn1_tlc_clear (c) if (c) (c)->valid = 0
Definition at line 84 of file tasn_dec.c.
asn1_tlc_clear_nc
#define asn1_tlc_clear_nc (c) (c)->valid = 0
Definition at line 86 of file tasn_dec.c.
Function Documentation
ASN1_item_d2i()
ASN1_VALUE* ASN1_item_d2i (ASN1_VALUE ** pval, const unsigned char ** in, long len, const ASN1_ITEM * it)
Definition at line 95 of file tasn_dec.c.
Referenced by OCSP_REQ_CTX_nbio_d2i(), STACK_OF(), and X509V3_EXT_d2i().
ASN1_item_ex_d2i()
int ASN1_item_ex_d2i (ASN1_VALUE ** pval, const unsigned char ** in, long len, const ASN1_ITEM * it, int tag, int aclass, char opt, ASN1_TLC * ctx)
Definition at line 109 of file tasn_dec.c.
ASN1_tag2bit()
unsigned long ASN1_tag2bit (int tag)
Definition at line 75 of file tasn_dec.c.