crypto/engine/tb_dsa.c File Reference
tb_dsa.c File Reference
#include "eng_int.h"
Functions
void ENGINE_unregister_DSA (ENGINE *e)
int ENGINE_register_DSA (ENGINE *e)
void ENGINE_register_all_DSA ()
int ENGINE_set_default_DSA (ENGINE *e)
ENGINE * ENGINE_get_default_DSA (void)
const DSA_METHOD * ENGINE_get_DSA (const ENGINE *e)
int ENGINE_set_DSA (ENGINE *e, const DSA_METHOD *dsa_meth)
Function Documentation
ENGINE_get_default_DSA()
ENGINE* ENGINE_get_default_DSA (void)
Definition at line 56 of file tb_dsa.c.
References engine_table_select().
ENGINE_get_DSA()
const DSA_METHOD* ENGINE_get_DSA (const ENGINE * e)
Definition at line 62 of file tb_dsa.c.
ENGINE_register_all_DSA()
void ENGINE_register_all_DSA (void)
Definition at line 34 of file tb_dsa.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_DSA().
ENGINE_register_DSA()
int ENGINE_register_DSA (ENGINE * e)
Definition at line 25 of file tb_dsa.c.
References engine_table_register().
Referenced by ENGINE_register_all_DSA(), and ENGINE_register_complete().
ENGINE_set_default_DSA()
int ENGINE_set_default_DSA (ENGINE * e)
Definition at line 42 of file tb_dsa.c.
References engine_table_register().
Referenced by ENGINE_set_default().
ENGINE_set_DSA()
int ENGINE_set_DSA (ENGINE * e, const DSA_METHOD * dsa_meth)
Definition at line 68 of file tb_dsa.c.
ENGINE_unregister_DSA()
void ENGINE_unregister_DSA (ENGINE * e)
Definition at line 15 of file tb_dsa.c.
References engine_table_unregister().