crypto/engine/tb_dh.c File Reference
tb_dh.c File Reference
#include "eng_int.h"
Functions
void ENGINE_unregister_DH (ENGINE *e)
int ENGINE_register_DH (ENGINE *e)
void ENGINE_register_all_DH ()
int ENGINE_set_default_DH (ENGINE *e)
ENGINE * ENGINE_get_default_DH (void)
const DH_METHOD * ENGINE_get_DH (const ENGINE *e)
int ENGINE_set_DH (ENGINE *e, const DH_METHOD *dh_meth)
Function Documentation
ENGINE_get_default_DH()
ENGINE* ENGINE_get_default_DH (void)
Definition at line 56 of file tb_dh.c.
References engine_table_select().
ENGINE_get_DH()
const DH_METHOD* ENGINE_get_DH (const ENGINE * e)
Definition at line 62 of file tb_dh.c.
ENGINE_register_all_DH()
void ENGINE_register_all_DH (void)
Definition at line 34 of file tb_dh.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_DH().
ENGINE_register_DH()
int ENGINE_register_DH (ENGINE * e)
Definition at line 25 of file tb_dh.c.
References engine_table_register().
Referenced by ENGINE_register_all_DH(), and ENGINE_register_complete().
ENGINE_set_default_DH()
int ENGINE_set_default_DH (ENGINE * e)
Definition at line 42 of file tb_dh.c.
References engine_table_register().
Referenced by ENGINE_set_default().
ENGINE_set_DH()
int ENGINE_set_DH (ENGINE * e, const DH_METHOD * dh_meth)
Definition at line 68 of file tb_dh.c.
ENGINE_unregister_DH()
void ENGINE_unregister_DH (ENGINE * e)
Definition at line 15 of file tb_dh.c.
References engine_table_unregister().