crypto/engine/tb_cipher.c File Reference
tb_cipher.c File Reference
#include "eng_int.h"
Functions
void ENGINE_unregister_ciphers (ENGINE *e)
int ENGINE_register_ciphers (ENGINE *e)
void ENGINE_register_all_ciphers ()
int ENGINE_set_default_ciphers (ENGINE *e)
ENGINE * ENGINE_get_cipher_engine (int nid)
const EVP_CIPHER * ENGINE_get_cipher (ENGINE *e, int nid)
ENGINE_CIPHERS_PTR ENGINE_get_ciphers (const ENGINE *e)
int ENGINE_set_ciphers (ENGINE *e, ENGINE_CIPHERS_PTR f)
Function Documentation
ENGINE_get_cipher()
const EVP_CIPHER* ENGINE_get_cipher (ENGINE * e, int nid)
Definition at line 69 of file tb_cipher.c.
ENGINE_get_cipher_engine()
ENGINE* ENGINE_get_cipher_engine (int nid)
Definition at line 63 of file tb_cipher.c.
References engine_table_select().
ENGINE_get_ciphers()
ENGINE_CIPHERS_PTR ENGINE_get_ciphers (const ENGINE * e)
Definition at line 81 of file tb_cipher.c.
ENGINE_register_all_ciphers()
void ENGINE_register_all_ciphers (void)
Definition at line 37 of file tb_cipher.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_ciphers().
ENGINE_register_ciphers()
int ENGINE_register_ciphers (ENGINE * e)
Definition at line 24 of file tb_cipher.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_register_all_ciphers(), and ENGINE_register_complete().
ENGINE_set_ciphers()
int ENGINE_set_ciphers (ENGINE * e, ENGINE_CIPHERS_PTR f)
Definition at line 87 of file tb_cipher.c.
ENGINE_set_default_ciphers()
int ENGINE_set_default_ciphers (ENGINE * e)
Definition at line 45 of file tb_cipher.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_set_default().
ENGINE_unregister_ciphers()
void ENGINE_unregister_ciphers (ENGINE * e)
Definition at line 14 of file tb_cipher.c.
References engine_table_unregister().