crypto/engine/tb_eckey.c File Reference
tb_eckey.c File Reference
#include "eng_int.h"
Functions
void ENGINE_unregister_EC (ENGINE *e)
int ENGINE_register_EC (ENGINE *e)
void ENGINE_register_all_EC ()
int ENGINE_set_default_EC (ENGINE *e)
ENGINE * ENGINE_get_default_EC (void)
const EC_KEY_METHOD * ENGINE_get_EC (const ENGINE *e)
int ENGINE_set_EC (ENGINE *e, const EC_KEY_METHOD *ec_meth)
Function Documentation
ENGINE_get_default_EC()
ENGINE* ENGINE_get_default_EC (void)
Definition at line 56 of file tb_eckey.c.
References engine_table_select().
ENGINE_get_EC()
const EC_KEY_METHOD* ENGINE_get_EC (const ENGINE * e)
Definition at line 62 of file tb_eckey.c.
ENGINE_register_all_EC()
void ENGINE_register_all_EC (void)
Definition at line 34 of file tb_eckey.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_EC().
ENGINE_register_EC()
int ENGINE_register_EC (ENGINE * e)
Definition at line 25 of file tb_eckey.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_register_all_EC(), and ENGINE_register_complete().
ENGINE_set_default_EC()
int ENGINE_set_default_EC (ENGINE * e)
Definition at line 42 of file tb_eckey.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_set_default().
ENGINE_set_EC()
int ENGINE_set_EC (ENGINE * e, const EC_KEY_METHOD * ec_meth)
Definition at line 68 of file tb_eckey.c.
ENGINE_unregister_EC()
void ENGINE_unregister_EC (ENGINE * e)
Definition at line 15 of file tb_eckey.c.
References engine_table_unregister().