crypto/engine/tb_pkmeth.c File Reference
tb_pkmeth.c File Reference
#include "eng_int.h"
#include <openssl/evp.h>
Functions
void ENGINE_unregister_pkey_meths (ENGINE *e)
int ENGINE_register_pkey_meths (ENGINE *e)
void ENGINE_register_all_pkey_meths ()
int ENGINE_set_default_pkey_meths (ENGINE *e)
ENGINE * ENGINE_get_pkey_meth_engine (int nid)
const EVP_PKEY_METHOD * ENGINE_get_pkey_meth (ENGINE *e, int nid)
ENGINE_PKEY_METHS_PTR ENGINE_get_pkey_meths (const ENGINE *e)
int ENGINE_set_pkey_meths (ENGINE *e, ENGINE_PKEY_METHS_PTR f)
void engine_pkey_meths_free (ENGINE *e)
Function Documentation
ENGINE_get_pkey_meth()
const EVP_PKEY_METHOD* ENGINE_get_pkey_meth (ENGINE * e, int nid)
Definition at line 70 of file tb_pkmeth.c.
ENGINE_get_pkey_meth_engine()
ENGINE* ENGINE_get_pkey_meth_engine (int nid)
Definition at line 64 of file tb_pkmeth.c.
References engine_table_select().
ENGINE_get_pkey_meths()
ENGINE_PKEY_METHS_PTR ENGINE_get_pkey_meths (const ENGINE * e)
Definition at line 83 of file tb_pkmeth.c.
engine_pkey_meths_free()
void engine_pkey_meths_free (ENGINE * e)
Definition at line 100 of file tb_pkmeth.c.
References EVP_PKEY_meth_free(), and NULL.
Referenced by engine_free_util().
ENGINE_register_all_pkey_meths()
void ENGINE_register_all_pkey_meths (void)
Definition at line 38 of file tb_pkmeth.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_pkey_meths().
ENGINE_register_pkey_meths()
int ENGINE_register_pkey_meths (ENGINE * e)
Definition at line 25 of file tb_pkmeth.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_register_all_pkey_meths(), and ENGINE_register_complete().
ENGINE_set_default_pkey_meths()
int ENGINE_set_default_pkey_meths (ENGINE * e)
Definition at line 46 of file tb_pkmeth.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_set_default().
ENGINE_set_pkey_meths()
int ENGINE_set_pkey_meths (ENGINE * e, ENGINE_PKEY_METHS_PTR f)
Definition at line 89 of file tb_pkmeth.c.
ENGINE_unregister_pkey_meths()
void ENGINE_unregister_pkey_meths (ENGINE * e)
Definition at line 15 of file tb_pkmeth.c.
References engine_table_unregister().