crypto/engine/tb_asnmth.c File Reference
tb_asnmth.c File Reference
#include "eng_int.h"
#include <openssl/evp.h>
#include "internal/asn1_int.h"
Data Structures
struct ENGINE_FIND_STR
Functions
void ENGINE_unregister_pkey_asn1_meths (ENGINE *e)
int ENGINE_register_pkey_asn1_meths (ENGINE *e)
void ENGINE_register_all_pkey_asn1_meths (void)
int ENGINE_set_default_pkey_asn1_meths (ENGINE *e)
ENGINE * ENGINE_get_pkey_asn1_meth_engine (int nid)
const EVP_PKEY_ASN1_METHOD * ENGINE_get_pkey_asn1_meth (ENGINE *e, int nid)
ENGINE_PKEY_ASN1_METHS_PTR ENGINE_get_pkey_asn1_meths (const ENGINE *e)
int ENGINE_set_pkey_asn1_meths (ENGINE *e, ENGINE_PKEY_ASN1_METHS_PTR f)
void engine_pkey_asn1_meths_free (ENGINE *e)
const EVP_PKEY_ASN1_METHOD * ENGINE_get_pkey_asn1_meth_str (ENGINE *e, const char *str, int len)
const EVP_PKEY_ASN1_METHOD * ENGINE_pkey_asn1_find_str (ENGINE **pe, const char *str, int len)
Function Documentation
ENGINE_get_pkey_asn1_meth()
const EVP_PKEY_ASN1_METHOD* ENGINE_get_pkey_asn1_meth (ENGINE * e, int nid)
Definition at line 82 of file tb_asnmth.c.
ENGINE_get_pkey_asn1_meth_engine()
ENGINE* ENGINE_get_pkey_asn1_meth_engine (int nid)
Definition at line 73 of file tb_asnmth.c.
References engine_table_select().
ENGINE_get_pkey_asn1_meth_str()
const EVP_PKEY_ASN1_METHOD* ENGINE_get_pkey_asn1_meth_str (ENGINE * e, const char * str, int len)
Definition at line 135 of file tb_asnmth.c.
References NULL.
ENGINE_get_pkey_asn1_meths()
ENGINE_PKEY_ASN1_METHS_PTR ENGINE_get_pkey_asn1_meths (const ENGINE * e)
Definition at line 95 of file tb_asnmth.c.
ENGINE_pkey_asn1_find_str()
const EVP_PKEY_ASN1_METHOD* ENGINE_pkey_asn1_find_str (ENGINE ** pe, const char * str, int len)
Definition at line 182 of file tb_asnmth.c.
References ENGINE_FIND_STR::ameth, CRYPTO_THREAD_write_lock(), ENGINE_FIND_STR::e, ENGINE_F_ENGINE_PKEY_ASN1_FIND_STR, engine_lock_init, engine_table_doall(), ENGINEerr, ERR_R_MALLOC_FAILURE, global_engine_lock, ENGINE_FIND_STR::len, len, NULL, RUN_ONCE, and ENGINE_FIND_STR::str.
Referenced by EVP_PKEY_asn1_find_str().
engine_pkey_asn1_meths_free()
void engine_pkey_asn1_meths_free (ENGINE * e)
Definition at line 112 of file tb_asnmth.c.
References EVP_PKEY_asn1_free(), and NULL.
Referenced by engine_free_util().
ENGINE_register_all_pkey_asn1_meths()
void ENGINE_register_all_pkey_asn1_meths (void)
Definition at line 47 of file tb_asnmth.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_pkey_asn1_meths().
ENGINE_register_pkey_asn1_meths()
int ENGINE_register_pkey_asn1_meths (ENGINE * e)
Definition at line 34 of file tb_asnmth.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_register_all_pkey_asn1_meths().
ENGINE_set_default_pkey_asn1_meths()
int ENGINE_set_default_pkey_asn1_meths (ENGINE * e)
Definition at line 55 of file tb_asnmth.c.
References engine_table_register(), and NULL.
Referenced by ENGINE_set_default().
ENGINE_set_pkey_asn1_meths()
int ENGINE_set_pkey_asn1_meths (ENGINE * e, ENGINE_PKEY_ASN1_METHS_PTR f)
Definition at line 101 of file tb_asnmth.c.
ENGINE_unregister_pkey_asn1_meths()
void ENGINE_unregister_pkey_asn1_meths (ENGINE * e)
Definition at line 24 of file tb_asnmth.c.
References engine_table_unregister().