crypto/engine/tb_rand.c File Reference
tb_rand.c File Reference
#include "eng_int.h"
Functions
void ENGINE_unregister_RAND (ENGINE *e)
int ENGINE_register_RAND (ENGINE *e)
void ENGINE_register_all_RAND ()
int ENGINE_set_default_RAND (ENGINE *e)
ENGINE * ENGINE_get_default_RAND (void)
const RAND_METHOD * ENGINE_get_RAND (const ENGINE *e)
int ENGINE_set_RAND (ENGINE *e, const RAND_METHOD *rand_meth)
Function Documentation
ENGINE_get_default_RAND()
ENGINE* ENGINE_get_default_RAND (void)
Definition at line 56 of file tb_rand.c.
References engine_table_select().
ENGINE_get_RAND()
const RAND_METHOD* ENGINE_get_RAND (const ENGINE * e)
Definition at line 62 of file tb_rand.c.
Referenced by RAND_set_rand_engine().
ENGINE_register_all_RAND()
void ENGINE_register_all_RAND (void)
Definition at line 34 of file tb_rand.c.
References e, ENGINE_get_first(), ENGINE_get_next(), and ENGINE_register_RAND().
ENGINE_register_RAND()
int ENGINE_register_RAND (ENGINE * e)
Definition at line 25 of file tb_rand.c.
References engine_table_register().
Referenced by ENGINE_register_all_RAND(), and ENGINE_register_complete().
ENGINE_set_default_RAND()
int ENGINE_set_default_RAND (ENGINE * e)
Definition at line 42 of file tb_rand.c.
References engine_table_register().
Referenced by ENGINE_set_default().
ENGINE_set_RAND()
int ENGINE_set_RAND (ENGINE * e, const RAND_METHOD * rand_meth)
Definition at line 68 of file tb_rand.c.
ENGINE_unregister_RAND()
void ENGINE_unregister_RAND (ENGINE * e)
Definition at line 15 of file tb_rand.c.
References engine_table_unregister().