apps/testdsa.h File Reference
testdsa.h File Reference
Functions
DSA * get_dsa512 (void)
DSA * get_dsa1024 (void)
DSA * get_dsa2048 (void)
Function Documentation
get_dsa1024()
DSA * get_dsa1024 (void)
Definition at line 138 of file testdsa.h.
References BN_bin2bn(), DSA_new(), NULL, and q.
get_dsa2048()
DSA * get_dsa2048 (void)
Definition at line 257 of file testdsa.h.
References BN_bin2bn(), DSA_new(), NULL, and q.
get_dsa512()
DSA * get_dsa512 (void)
Definition at line 52 of file testdsa.h.
References BN_bin2bn(), DSA_new(), NULL, and q.