crypto/threads_none.c File Reference
threads_none.c File Reference
#include <openssl/crypto.h>
Macros
#define OPENSSL_CRYPTO_THREAD_LOCAL_KEY_MAX 256
Functions
CRYPTO_RWLOCK * CRYPTO_THREAD_lock_new (void)
int CRYPTO_THREAD_read_lock (CRYPTO_RWLOCK *lock)
int CRYPTO_THREAD_write_lock (CRYPTO_RWLOCK *lock)
int CRYPTO_THREAD_unlock (CRYPTO_RWLOCK *lock)
void CRYPTO_THREAD_lock_free (CRYPTO_RWLOCK *lock)
int CRYPTO_THREAD_run_once (CRYPTO_ONCE *once, void(*init)(void))
int CRYPTO_THREAD_init_local (CRYPTO_THREAD_LOCAL *key, void(*cleanup)(void *))
void * CRYPTO_THREAD_get_local (CRYPTO_THREAD_LOCAL *key)
int CRYPTO_THREAD_set_local (CRYPTO_THREAD_LOCAL *key, void *val)
int CRYPTO_THREAD_cleanup_local (CRYPTO_THREAD_LOCAL *key)
CRYPTO_THREAD_ID CRYPTO_THREAD_get_current_id (void)
int CRYPTO_THREAD_compare_id (CRYPTO_THREAD_ID a, CRYPTO_THREAD_ID b)
int CRYPTO_atomic_add (int *val, int amount, int *ret, CRYPTO_RWLOCK *lock)
Macro Definition Documentation
OPENSSL_CRYPTO_THREAD_LOCAL_KEY_MAX
#define OPENSSL_CRYPTO_THREAD_LOCAL_KEY_MAX 256
Definition at line 64 of file threads_none.c.
Referenced by CRYPTO_THREAD_cleanup_local(), CRYPTO_THREAD_get_local(), and CRYPTO_THREAD_set_local().
Function Documentation
CRYPTO_atomic_add()
int CRYPTO_atomic_add (int * val, int amount, int * ret, CRYPTO_RWLOCK * lock)
Definition at line 116 of file threads_none.c.
Referenced by engine_free_util().
CRYPTO_THREAD_cleanup_local()
int CRYPTO_THREAD_cleanup_local (CRYPTO_THREAD_LOCAL * key)
Definition at line 100 of file threads_none.c.
References OPENSSL_CRYPTO_THREAD_LOCAL_KEY_MAX.
Referenced by async_deinit().
CRYPTO_THREAD_compare_id()
int CRYPTO_THREAD_compare_id (CRYPTO_THREAD_ID a, CRYPTO_THREAD_ID b)
Definition at line 111 of file threads_none.c.
Referenced by BN_BLINDING_is_current_thread().
CRYPTO_THREAD_get_current_id()
CRYPTO_THREAD_ID CRYPTO_THREAD_get_current_id (void)
Definition at line 106 of file threads_none.c.
Referenced by BN_BLINDING_is_current_thread(), and BN_BLINDING_set_current_thread().
CRYPTO_THREAD_get_local()
void* CRYPTO_THREAD_get_local (CRYPTO_THREAD_LOCAL * key)
Definition at line 82 of file threads_none.c.
References key, NULL, and OPENSSL_CRYPTO_THREAD_LOCAL_KEY_MAX.
Referenced by async_get_ctx().
CRYPTO_THREAD_init_local()
int CRYPTO_THREAD_init_local (CRYPTO_THREAD_LOCAL * key, void(*)(void *) cleanup)
Definition at line 68 of file threads_none.c.
Referenced by async_init(), and DEFINE_RUN_ONCE_STATIC().
CRYPTO_THREAD_lock_free()
void CRYPTO_THREAD_lock_free (CRYPTO_RWLOCK * lock)
Definition at line 43 of file threads_none.c.
References NULL, and OPENSSL_free.
Referenced by bio_cleanup(), BIO_new(), BN_BLINDING_free(), CRYPTO_secure_malloc_done(), DH_free(), DSA_free(), DSO_free(), EC_ec_pre_comp_free(), EC_KEY_free(), EC_nistp224_pre_comp_free(), EC_nistp256_pre_comp_free(), EC_nistp521_pre_comp_free(), EC_nistz256_pre_comp_free(), err_cleanup(), RSA_free(), SSL_SESSION_free(), and SSL_SESSION_new().
CRYPTO_THREAD_lock_new()
CRYPTO_RWLOCK* CRYPTO_THREAD_lock_new (void)
Definition at line 14 of file threads_none.c.
References NULL, and OPENSSL_zalloc.
Referenced by BIO_new(), DEFINE_RUN_ONCE(), DEFINE_RUN_ONCE_STATIC(), SSL_new(), ssl_session_dup(), and SSL_SESSION_new().
CRYPTO_THREAD_read_lock()
int CRYPTO_THREAD_read_lock (CRYPTO_RWLOCK * lock)
Definition at line 25 of file threads_none.c.
References OPENSSL_assert.
Referenced by SSL_get1_session(), and SSL_has_matching_session_id().
CRYPTO_THREAD_run_once()
int CRYPTO_THREAD_run_once (CRYPTO_ONCE * once, void(*)(void) init)
Definition at line 53 of file threads_none.c.
CRYPTO_THREAD_set_local()
int CRYPTO_THREAD_set_local (CRYPTO_THREAD_LOCAL * key, void * val)
Definition at line 90 of file threads_none.c.
References key, and OPENSSL_CRYPTO_THREAD_LOCAL_KEY_MAX.
CRYPTO_THREAD_unlock()
int CRYPTO_THREAD_unlock (CRYPTO_RWLOCK * lock)
Definition at line 37 of file threads_none.c.
References OPENSSL_assert.
Referenced by BN_BLINDING_unlock(), CRYPTO_secure_actual_size(), CRYPTO_secure_free(), ENGINE_ctrl(), ENGINE_finish(), engine_unlocked_finish(), SSL_CTX_set_generate_session_id(), SSL_get1_session(), SSL_has_matching_session_id(), SSL_set_generate_session_id(), and X509_STORE_unlock().
CRYPTO_THREAD_write_lock()
int CRYPTO_THREAD_write_lock (CRYPTO_RWLOCK * lock)
Definition at line 31 of file threads_none.c.
References OPENSSL_assert.
Referenced by BN_BLINDING_lock(), CRYPTO_secure_actual_size(), CRYPTO_secure_free(), ENGINE_add(), ENGINE_by_id(), ENGINE_ctrl(), ENGINE_finish(), ENGINE_pkey_asn1_find_str(), ENGINE_remove(), engine_table_cleanup(), engine_table_unregister(), engine_unlocked_finish(), policy_cache_set(), SSL_CTX_flush_sessions(), SSL_CTX_set_generate_session_id(), SSL_set_generate_session_id(), X509_check_ca(), and X509_STORE_lock().