ssl/tls13_enc.c File Reference
tls13_enc.c File Reference
#include <stdlib.h>
#include "ssl_locl.h"
#include <openssl/evp.h>
#include <openssl/kdf.h>
Macros
#define TLS13_MAX_LABEL_LEN 246
Functions
int tls13_hkdf_expand (SSL *s, const EVP_MD *md, const unsigned char *secret, const unsigned char *label, size_t labellen, const unsigned char *hash, unsigned char *out, size_t outlen)
int tls13_derive_key (SSL *s, const unsigned char *secret, unsigned char *key, size_t keylen)
int tls13_derive_iv (SSL *s, const unsigned char *secret, unsigned char *iv, size_t ivlen)
int tls13_derive_finishedkey (SSL *s, const EVP_MD *md, const unsigned char *secret, unsigned char *fin, size_t finlen)
int tls13_generate_secret (SSL *s, const EVP_MD *md, const unsigned char *prevsecret, const unsigned char *insecret, size_t insecretlen, unsigned char *outsecret)
int tls13_generate_handshake_secret (SSL *s, const unsigned char *insecret, size_t insecretlen)
int tls13_generate_master_secret (SSL *s, unsigned char *out, unsigned char *prev, size_t prevlen, size_t *secret_size)
size_t tls13_final_finish_mac (SSL *s, const char *str, size_t slen, unsigned char *out)
int tls13_setup_key_block (SSL *s)
int tls13_change_cipher_state (SSL *s, int which)
int tls13_update_key (SSL *s, int send)
int tls13_alert_code (int code)
Macro Definition Documentation
TLS13_MAX_LABEL_LEN
#define TLS13_MAX_LABEL_LEN 246
Definition at line 15 of file tls13_enc.c.
Function Documentation
tls13_alert_code()
int tls13_alert_code (int code)
Definition at line 501 of file tls13_enc.c.
References code, SSL_AD_MISSING_EXTENSION, and tls1_alert_code().
tls13_change_cipher_state()
int tls13_change_cipher_state (SSL * s, int which)
Definition at line 313 of file tls13_enc.c.
tls13_derive_finishedkey()
int tls13_derive_finishedkey (SSL * s, const EVP_MD * md, const unsigned char * secret, unsigned char * fin, size_t finlen)
Definition at line 102 of file tls13_enc.c.
tls13_derive_iv()
int tls13_derive_iv (SSL * s, const unsigned char * secret, unsigned char * iv, size_t ivlen)
Definition at line 93 of file tls13_enc.c.
tls13_derive_key()
int tls13_derive_key (SSL * s, const unsigned char * secret, unsigned char * key, size_t keylen)
Definition at line 80 of file tls13_enc.c.
References NULL, ssl_handshake_md(), and tls13_hkdf_expand().
tls13_final_finish_mac()
size_t tls13_final_finish_mac (SSL * s, const char * str, size_t slen, unsigned char * out)
Definition at line 189 of file tls13_enc.c.
tls13_generate_handshake_secret()
int tls13_generate_handshake_secret (SSL * s, const unsigned char * insecret, size_t insecretlen)
Definition at line 162 of file tls13_enc.c.
References ssl_handshake_md(), and tls13_generate_secret().
Referenced by tls_construct_stoc_key_share().
tls13_generate_master_secret()
int tls13_generate_master_secret (SSL * s, unsigned char * out, unsigned char * prev, size_t prevlen, size_t * secret_size)
Definition at line 175 of file tls13_enc.c.
tls13_generate_secret()
int tls13_generate_secret (SSL * s, const EVP_MD * md, const unsigned char * prevsecret, const unsigned char * insecret, size_t insecretlen, unsigned char * outsecret)
Definition at line 117 of file tls13_enc.c.
Referenced by tls13_generate_handshake_secret().
tls13_hkdf_expand()
int tls13_hkdf_expand (SSL * s, const EVP_MD * md, const unsigned char * secret, const unsigned char * label, size_t labellen, const unsigned char * hash, unsigned char * out, size_t outlen)
Definition at line 26 of file tls13_enc.c.
Referenced by tls13_derive_key().
tls13_setup_key_block()
int tls13_setup_key_block (SSL * s)
Definition at line 226 of file tls13_enc.c.
tls13_update_key()
int tls13_update_key (SSL * s, int send)
Definition at line 462 of file tls13_enc.c.
Referenced by ossl_statem_client_post_work(), and ossl_statem_server_post_work().