test/tls13secretstest.c File Reference
tls13secretstest.c File Reference
#include <openssl/ssl.h>
#include <openssl/evp.h>
#include "../ssl/ssl_locl.h"
#include "testutil.h"
#include "test_main.h"
Macros
#define IVLEN 12
#define KEYLEN 16
Functions
int ssl3_digest_cached_records (SSL *s, int keep)
int ssl_handshake_hash (SSL *s, unsigned char *out, size_t outlen, size_t *hashlen)
const EVP_MD * ssl_handshake_md (SSL *s)
void RECORD_LAYER_reset_read_sequence (RECORD_LAYER *rl)
void RECORD_LAYER_reset_write_sequence (RECORD_LAYER *rl)
int ssl_cipher_get_evp (const SSL_SESSION *s, const EVP_CIPHER **enc, const EVP_MD **md, int *mac_pkey_type, size_t *mac_secret_size, SSL_COMP **comp, int use_etm)
int tls1_alert_code (int code)
int ssl_log_secret (SSL *ssl, const char *label, const uint8_t *secret, size_t secret_len)
void register_tests ()
Macro Definition Documentation
IVLEN
#define IVLEN 12
Definition at line 17 of file tls13secretstest.c.
KEYLEN
#define KEYLEN 16
Definition at line 18 of file tls13secretstest.c.
Function Documentation
RECORD_LAYER_reset_read_sequence()
void RECORD_LAYER_reset_read_sequence (RECORD_LAYER * rl)
Definition at line 166 of file tls13secretstest.c.
References RECORD_LAYER::read_sequence.
RECORD_LAYER_reset_write_sequence()
void RECORD_LAYER_reset_write_sequence (RECORD_LAYER * rl)
Definition at line 170 of file tls13secretstest.c.
References RECORD_LAYER::write_sequence.
register_tests()
void register_tests (void)
Definition at line 372 of file tls13secretstest.c.
References ADD_TEST.
ssl3_digest_cached_records()
int ssl3_digest_cached_records (SSL * s, int keep)
Definition at line 135 of file tls13secretstest.c.
ssl_cipher_get_evp()
int ssl_cipher_get_evp (const SSL_SESSION * s, const EVP_CIPHER ** enc, const EVP_MD ** md, int * mac_pkey_type, size_t * mac_secret_size, SSL_COMP ** comp, int use_etm)
Definition at line 174 of file tls13secretstest.c.
ssl_handshake_hash()
int ssl_handshake_hash (SSL * s, unsigned char * out, size_t outlen, size_t * hashlen)
Definition at line 143 of file tls13secretstest.c.
ssl_handshake_md()
const EVP_MD* ssl_handshake_md (SSL * s)
Definition at line 161 of file tls13secretstest.c.
References EVP_sha256(), ssl_get_algorithm2(), and ssl_md().
ssl_log_secret()
int ssl_log_secret (SSL * ssl, const char * label, const uint8_t * secret, size_t secret_len)
Definition at line 187 of file tls13secretstest.c.
tls1_alert_code()
int tls1_alert_code (int code)
Definition at line 182 of file tls13secretstest.c.
References code.
Referenced by tls13_alert_code().