ssl/tls_srp.c File Reference
tls_srp.c File Reference
#include <openssl/crypto.h>
#include <openssl/rand.h>
#include <openssl/err.h>
#include "ssl_locl.h"
#include <openssl/srp.h>
Macros
#define tls1_ctx_ctrl ssl3_ctx_ctrl
#define tls1_ctx_callback_ctrl ssl3_ctx_callback_ctrl
Functions
int SSL_CTX_SRP_CTX_free (struct ssl_ctx_st *ctx)
int SSL_SRP_CTX_free (struct ssl_st *s)
int SSL_SRP_CTX_init (struct ssl_st *s)
int SSL_CTX_SRP_CTX_init (struct ssl_ctx_st *ctx)
int SSL_srp_server_param_with_username (SSL *s, int *ad)
int SSL_set_srp_server_param_pw (SSL *s, const char *user, const char *pass, const char *grp)
int SSL_set_srp_server_param (SSL *s, const BIGNUM *N, const BIGNUM *g, BIGNUM *sa, BIGNUM *v, char *info)
int srp_generate_server_master_secret (SSL *s)
int srp_generate_client_master_secret (SSL *s)
int srp_verify_server_param (SSL *s, int *al)
int SRP_Calc_A_param (SSL *s)
BIGNUM * SSL_get_srp_g (SSL *s)
BIGNUM * SSL_get_srp_N (SSL *s)
char * SSL_get_srp_username (SSL *s)
char * SSL_get_srp_userinfo (SSL *s)
int SSL_CTX_set_srp_username (SSL_CTX *ctx, char *name)
int SSL_CTX_set_srp_password (SSL_CTX *ctx, char *password)
int SSL_CTX_set_srp_strength (SSL_CTX *ctx, int strength)
int SSL_CTX_set_srp_verify_param_callback (SSL_CTX *ctx, int(*cb)(SSL *, void *))
int SSL_CTX_set_srp_cb_arg (SSL_CTX *ctx, void *arg)
int SSL_CTX_set_srp_username_callback (SSL_CTX *ctx, int(*cb)(SSL *, int *, void *))
int SSL_CTX_set_srp_client_pwd_callback (SSL_CTX *ctx, char *(*cb)(SSL *, void *))
Macro Definition Documentation
tls1_ctx_callback_ctrl
#define tls1_ctx_callback_ctrl ssl3_ctx_callback_ctrl
Definition at line 425 of file tls_srp.c.
Referenced by SSL_CTX_set_srp_client_pwd_callback(), SSL_CTX_set_srp_username_callback(), and SSL_CTX_set_srp_verify_param_callback().
tls1_ctx_ctrl
#define tls1_ctx_ctrl ssl3_ctx_ctrl
Definition at line 424 of file tls_srp.c.
Referenced by SSL_CTX_set_srp_password(), SSL_CTX_set_srp_strength(), and SSL_CTX_set_srp_username().
Function Documentation
SRP_Calc_A_param()
int SRP_Calc_A_param (SSL * s)
Definition at line 381 of file tls_srp.c.
References BN_bin2bn(), OPENSSL_cleanse(), RAND_bytes(), SRP_Calc_A(), and SSL_MAX_MASTER_KEY_LENGTH.
srp_generate_client_master_secret()
int srp_generate_client_master_secret (SSL * s)
Definition at line 310 of file tls_srp.c.
References NULL, and u.
Referenced by tls_client_key_exchange_post_work().
srp_generate_server_master_secret()
int srp_generate_server_master_secret (SSL * s)
Definition at line 284 of file tls_srp.c.
References NULL, and u.
srp_verify_server_param()
int srp_verify_server_param (SSL * s, int * al)
Definition at line 350 of file tls_srp.c.
References SRP_CTX::B, BN_is_zero(), BN_num_bits(), BN_ucmp(), SRP_CTX::g, SRP_CTX::N, SRP_CTX::SRP_cb_arg, SRP_check_known_gN_param(), SRP_CTX::SRP_verify_param_callback, SSL3_AD_ILLEGAL_PARAMETER, SRP_CTX::strength, and TLS1_AD_INSUFFICIENT_SECURITY.
SSL_CTX_set_srp_cb_arg()
int SSL_CTX_set_srp_cb_arg (SSL_CTX * ctx, void * arg)
Definition at line 450 of file tls_srp.c.
SSL_CTX_set_srp_client_pwd_callback()
int SSL_CTX_set_srp_client_pwd_callback (SSL_CTX * ctx, char *(*)(SSL *, void *) cb)
Definition at line 462 of file tls_srp.c.
References cb, SSL_CTRL_SET_SRP_GIVE_CLIENT_PWD_CB, and tls1_ctx_callback_ctrl.
SSL_CTX_set_srp_password()
int SSL_CTX_set_srp_password (SSL_CTX * ctx, char * password)
Definition at line 432 of file tls_srp.c.
References SSL_CTRL_SET_TLS_EXT_SRP_PASSWORD, and tls1_ctx_ctrl.
SSL_CTX_set_srp_strength()
int SSL_CTX_set_srp_strength (SSL_CTX * ctx, int strength)
Definition at line 437 of file tls_srp.c.
References NULL, SSL_CTRL_SET_TLS_EXT_SRP_STRENGTH, and tls1_ctx_ctrl.
SSL_CTX_set_srp_username()
int SSL_CTX_set_srp_username (SSL_CTX * ctx, char * name)
Definition at line 427 of file tls_srp.c.
References SSL_CTRL_SET_TLS_EXT_SRP_USERNAME, and tls1_ctx_ctrl.
SSL_CTX_set_srp_username_callback()
int SSL_CTX_set_srp_username_callback (SSL_CTX * ctx, int(*)(SSL *, int *, void *) cb)
Definition at line 455 of file tls_srp.c.
References cb, SSL_CTRL_SET_TLS_EXT_SRP_USERNAME_CB, and tls1_ctx_callback_ctrl.
SSL_CTX_set_srp_verify_param_callback()
int SSL_CTX_set_srp_verify_param_callback (SSL_CTX * ctx, int(*)(SSL *, void *) cb)
Definition at line 443 of file tls_srp.c.
References cb, SSL_CTRL_SET_SRP_VERIFY_PARAM_CB, and tls1_ctx_callback_ctrl.
SSL_CTX_SRP_CTX_free()
int SSL_CTX_SRP_CTX_free (struct ssl_ctx_st * ctx)
Definition at line 18 of file tls_srp.c.
References SRP_CTX::A, SRP_CTX::a, SRP_CTX::B, SRP_CTX::b, BN_free(), SRP_CTX::g, SRP_CTX::info, SRP_CTX::login, SRP_CTX::N, NULL, OPENSSL_free, SRP_CTX::s, SRP_CTX::SRP_cb_arg, SSL_CTX::srp_ctx, SRP_CTX::SRP_give_srp_client_pwd_callback, SRP_CTX::srp_Mask, SRP_MINIMAL_N, SRP_CTX::SRP_verify_param_callback, SRP_CTX::strength, SRP_CTX::TLS_ext_srp_username_callback, and SRP_CTX::v.
SSL_CTX_SRP_CTX_init()
int SSL_CTX_SRP_CTX_init (struct ssl_ctx_st * ctx)
Definition at line 151 of file tls_srp.c.
References SRP_CTX::A, SRP_CTX::a, SRP_CTX::B, SRP_CTX::b, SRP_CTX::g, SRP_CTX::info, SRP_CTX::login, SRP_CTX::N, NULL, SRP_CTX::s, SRP_CTX::SRP_cb_arg, SSL_CTX::srp_ctx, SRP_CTX::SRP_give_srp_client_pwd_callback, SRP_CTX::srp_Mask, SRP_MINIMAL_N, SRP_CTX::SRP_verify_param_callback, SRP_CTX::strength, SRP_CTX::TLS_ext_srp_username_callback, and SRP_CTX::v.
SSL_get_srp_g()
BIGNUM* SSL_get_srp_g (SSL * s)
Definition at line 396 of file tls_srp.c.
References NULL.
SSL_get_srp_N()
BIGNUM* SSL_get_srp_N (SSL * s)
Definition at line 403 of file tls_srp.c.
References NULL.
SSL_get_srp_userinfo()
char* SSL_get_srp_userinfo (SSL * s)
Definition at line 417 of file tls_srp.c.
References NULL.
SSL_get_srp_username()
char* SSL_get_srp_username (SSL * s)
Definition at line 410 of file tls_srp.c.
References NULL.
SSL_set_srp_server_param()
int SSL_set_srp_server_param (SSL * s, const BIGNUM * N, const BIGNUM * g, BIGNUM * sa, BIGNUM * v, char * info)
Definition at line 236 of file tls_srp.c.
References BN_copy(), BN_dup(), BN_free(), and NULL.
SSL_set_srp_server_param_pw()
int SSL_set_srp_server_param_pw (SSL * s, const char * user, const char * pass, const char * grp)
Definition at line 217 of file tls_srp.c.
References BN_clear_free(), BN_dup(), SRP_gN::g, SRP_gN::N, NULL, SRP_create_verifier_BN(), and SRP_get_default_gN().
SSL_SRP_CTX_free()
int SSL_SRP_CTX_free (struct ssl_st * s)
Definition at line 50 of file tls_srp.c.
References SRP_CTX::A, SRP_CTX::a, SRP_CTX::B, SRP_CTX::b, BN_free(), SRP_CTX::g, SRP_CTX::info, SRP_CTX::login, SRP_CTX::N, NULL, OPENSSL_free, SRP_CTX::s, SRP_CTX::SRP_cb_arg, ssl_crock_st::srp_ctx, SRP_CTX::SRP_give_srp_client_pwd_callback, SRP_CTX::srp_Mask, SRP_MINIMAL_N, SRP_CTX::SRP_verify_param_callback, SRP_CTX::strength, SRP_CTX::TLS_ext_srp_username_callback, and SRP_CTX::v.
SSL_SRP_CTX_init()
int SSL_SRP_CTX_init (struct ssl_st * s)
Definition at line 82 of file tls_srp.c.
References SRP_CTX::A, SRP_CTX::a, SRP_CTX::B, SRP_CTX::b, BN_dup(), BN_free(), ctx, ssl_crock_st::ctx, ERR_R_BN_LIB, ERR_R_INTERNAL_ERROR, SRP_CTX::g, SRP_CTX::info, SRP_CTX::login, SRP_CTX::N, NULL, OPENSSL_free, OPENSSL_strdup, SRP_CTX::s, SRP_CTX::SRP_cb_arg, ssl_crock_st::srp_ctx, SRP_CTX::SRP_give_srp_client_pwd_callback, SRP_CTX::srp_Mask, SRP_CTX::SRP_verify_param_callback, SSL_F_SSL_SRP_CTX_INIT, SSLerr, SRP_CTX::strength, SRP_CTX::TLS_ext_srp_username_callback, and SRP_CTX::v.
SSL_srp_server_param_with_username()
int SSL_srp_server_param_with_username (SSL * s, int * ad)
Definition at line 181 of file tls_srp.c.
References BN_bin2bn(), NULL, OPENSSL_cleanse(), RAND_bytes(), SRP_Calc_B(), SSL3_AL_FATAL, SSL_AD_INTERNAL_ERROR, SSL_AD_UNKNOWN_PSK_IDENTITY, SSL_ERROR_NONE, and SSL_MAX_MASTER_KEY_LENGTH.