include/openssl/ts.h File Reference
ts.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/symhacks.h>
#include <openssl/buffer.h>
#include <openssl/evp.h>
#include <openssl/bio.h>
#include <openssl/stack.h>
#include <openssl/asn1.h>
#include <openssl/safestack.h>
#include <openssl/rsa.h>
#include <openssl/dsa.h>
#include <openssl/dh.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
Macros
#define TS_STATUS_GRANTED 0
#define TS_STATUS_GRANTED_WITH_MODS 1
#define TS_STATUS_REJECTION 2
#define TS_STATUS_WAITING 3
#define TS_STATUS_REVOCATION_WARNING 4
#define TS_STATUS_REVOCATION_NOTIFICATION 5
#define TS_INFO_BAD_ALG 0
#define TS_INFO_BAD_REQUEST 2
#define TS_INFO_BAD_DATA_FORMAT 5
#define TS_INFO_TIME_NOT_AVAILABLE 14
#define TS_INFO_UNACCEPTED_POLICY 15
#define TS_INFO_UNACCEPTED_EXTENSION 16
#define TS_INFO_ADD_INFO_NOT_AVAILABLE 17
#define TS_INFO_SYSTEM_FAILURE 25
#define TS_TSA_NAME 0x01
#define TS_ORDERING 0x02
#define TS_ESS_CERT_ID_CHAIN 0x04
#define TS_MAX_CLOCK_PRECISION_DIGITS 6
#define TS_MAX_STATUS_LENGTH (1024 * 1024)
#define TS_VFY_SIGNATURE (1u << 0)
#define TS_VFY_VERSION (1u << 1)
#define TS_VFY_POLICY (1u << 2)
#define TS_VFY_IMPRINT (1u << 3)
#define TS_VFY_DATA (1u << 4)
#define TS_VFY_NONCE (1u << 5)
#define TS_VFY_SIGNER (1u << 6)
#define TS_VFY_TSA_NAME (1u << 7)
#define TS_VFY_ALL_IMPRINT
#define TS_VFY_ALL_DATA
#define TS_F_DEF_SERIAL_CB 110
#define TS_F_DEF_TIME_CB 111
#define TS_F_ESS_ADD_SIGNING_CERT 112
#define TS_F_ESS_CERT_ID_NEW_INIT 113
#define TS_F_ESS_SIGNING_CERT_NEW_INIT 114
#define TS_F_INT_TS_RESP_VERIFY_TOKEN 149
#define TS_F_PKCS7_TO_TS_TST_INFO 148
#define TS_F_TS_ACCURACY_SET_MICROS 115
#define TS_F_TS_ACCURACY_SET_MILLIS 116
#define TS_F_TS_ACCURACY_SET_SECONDS 117
#define TS_F_TS_CHECK_IMPRINTS 100
#define TS_F_TS_CHECK_NONCES 101
#define TS_F_TS_CHECK_POLICY 102
#define TS_F_TS_CHECK_SIGNING_CERTS 103
#define TS_F_TS_CHECK_STATUS_INFO 104
#define TS_F_TS_COMPUTE_IMPRINT 145
#define TS_F_TS_CONF_INVALID 151
#define TS_F_TS_CONF_LOAD_CERT 153
#define TS_F_TS_CONF_LOAD_CERTS 154
#define TS_F_TS_CONF_LOAD_KEY 155
#define TS_F_TS_CONF_LOOKUP_FAIL 152
#define TS_F_TS_CONF_SET_DEFAULT_ENGINE 146
#define TS_F_TS_GET_STATUS_TEXT 105
#define TS_F_TS_MSG_IMPRINT_SET_ALGO 118
#define TS_F_TS_REQ_SET_MSG_IMPRINT 119
#define TS_F_TS_REQ_SET_NONCE 120
#define TS_F_TS_REQ_SET_POLICY_ID 121
#define TS_F_TS_RESP_CREATE_RESPONSE 122
#define TS_F_TS_RESP_CREATE_TST_INFO 123
#define TS_F_TS_RESP_CTX_ADD_FAILURE_INFO 124
#define TS_F_TS_RESP_CTX_ADD_MD 125
#define TS_F_TS_RESP_CTX_ADD_POLICY 126
#define TS_F_TS_RESP_CTX_NEW 127
#define TS_F_TS_RESP_CTX_SET_ACCURACY 128
#define TS_F_TS_RESP_CTX_SET_CERTS 129
#define TS_F_TS_RESP_CTX_SET_DEF_POLICY 130
#define TS_F_TS_RESP_CTX_SET_SIGNER_CERT 131
#define TS_F_TS_RESP_CTX_SET_STATUS_INFO 132
#define TS_F_TS_RESP_GET_POLICY 133
#define TS_F_TS_RESP_SET_GENTIME_WITH_PRECISION 134
#define TS_F_TS_RESP_SET_STATUS_INFO 135
#define TS_F_TS_RESP_SET_TST_INFO 150
#define TS_F_TS_RESP_SIGN 136
#define TS_F_TS_RESP_VERIFY_SIGNATURE 106
#define TS_F_TS_TST_INFO_SET_ACCURACY 137
#define TS_F_TS_TST_INFO_SET_MSG_IMPRINT 138
#define TS_F_TS_TST_INFO_SET_NONCE 139
#define TS_F_TS_TST_INFO_SET_POLICY_ID 140
#define TS_F_TS_TST_INFO_SET_SERIAL 141
#define TS_F_TS_TST_INFO_SET_TIME 142
#define TS_F_TS_TST_INFO_SET_TSA 143
#define TS_F_TS_VERIFY 108
#define TS_F_TS_VERIFY_CERT 109
#define TS_F_TS_VERIFY_CTX_NEW 144
#define TS_R_BAD_PKCS7_TYPE 132
#define TS_R_BAD_TYPE 133
#define TS_R_CANNOT_LOAD_CERT 137
#define TS_R_CANNOT_LOAD_KEY 138
#define TS_R_CERTIFICATE_VERIFY_ERROR 100
#define TS_R_COULD_NOT_SET_ENGINE 127
#define TS_R_COULD_NOT_SET_TIME 115
#define TS_R_DETACHED_CONTENT 134
#define TS_R_ESS_ADD_SIGNING_CERT_ERROR 116
#define TS_R_ESS_SIGNING_CERTIFICATE_ERROR 101
#define TS_R_INVALID_NULL_POINTER 102
#define TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE 117
#define TS_R_MESSAGE_IMPRINT_MISMATCH 103
#define TS_R_NONCE_MISMATCH 104
#define TS_R_NONCE_NOT_RETURNED 105
#define TS_R_NO_CONTENT 106
#define TS_R_NO_TIME_STAMP_TOKEN 107
#define TS_R_PKCS7_ADD_SIGNATURE_ERROR 118
#define TS_R_PKCS7_ADD_SIGNED_ATTR_ERROR 119
#define TS_R_PKCS7_TO_TS_TST_INFO_FAILED 129
#define TS_R_POLICY_MISMATCH 108
#define TS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE 120
#define TS_R_RESPONSE_SETUP_ERROR 121
#define TS_R_SIGNATURE_FAILURE 109
#define TS_R_THERE_MUST_BE_ONE_SIGNER 110
#define TS_R_TIME_SYSCALL_ERROR 122
#define TS_R_TOKEN_NOT_PRESENT 130
#define TS_R_TOKEN_PRESENT 131
#define TS_R_TSA_NAME_MISMATCH 111
#define TS_R_TSA_UNTRUSTED 112
#define TS_R_TST_INFO_SETUP_ERROR 123
#define TS_R_TS_DATASIGN 124
#define TS_R_UNACCEPTABLE_POLICY 125
#define TS_R_UNSUPPORTED_MD_ALGORITHM 126
#define TS_R_UNSUPPORTED_VERSION 113
#define TS_R_VAR_BAD_VALUE 135
#define TS_R_VAR_LOOKUP_FAILURE 136
#define TS_R_WRONG_CONTENT_TYPE 114
Typedefs
typedef ASN1_INTEGER *(* TS_serial_cb) (struct TS_resp_ctx *, void *)
typedef int(* TS_time_cb) (struct TS_resp_ctx *, void *, long *sec, long *usec)
typedef int(* TS_extension_cb) (struct TS_resp_ctx *, X509_EXTENSION *, void *)
Functions
TS_REQ * TS_REQ_new (void)
void TS_REQ_free (TS_REQ *a)
int i2d_TS_REQ (const TS_REQ *a, unsigned char **pp)
TS_REQ * d2i_TS_REQ (TS_REQ **a, const unsigned char **pp, long length)
TS_REQ * TS_REQ_dup (TS_REQ *a)
TS_REQ * d2i_TS_REQ_fp (FILE *fp, TS_REQ **a)
int i2d_TS_REQ_fp (FILE *fp, TS_REQ *a)
TS_REQ * d2i_TS_REQ_bio (BIO *fp, TS_REQ **a)
int i2d_TS_REQ_bio (BIO *fp, TS_REQ *a)
TS_MSG_IMPRINT * TS_MSG_IMPRINT_new (void)
void TS_MSG_IMPRINT_free (TS_MSG_IMPRINT *a)
int i2d_TS_MSG_IMPRINT (const TS_MSG_IMPRINT *a, unsigned char **pp)
TS_MSG_IMPRINT * d2i_TS_MSG_IMPRINT (TS_MSG_IMPRINT **a, const unsigned char **pp, long length)
TS_MSG_IMPRINT * TS_MSG_IMPRINT_dup (TS_MSG_IMPRINT *a)
TS_MSG_IMPRINT * d2i_TS_MSG_IMPRINT_fp (FILE *fp, TS_MSG_IMPRINT **a)
int i2d_TS_MSG_IMPRINT_fp (FILE *fp, TS_MSG_IMPRINT *a)
TS_MSG_IMPRINT * d2i_TS_MSG_IMPRINT_bio (BIO *bio, TS_MSG_IMPRINT **a)
int i2d_TS_MSG_IMPRINT_bio (BIO *bio, TS_MSG_IMPRINT *a)
TS_RESP * TS_RESP_new (void)
void TS_RESP_free (TS_RESP *a)
int i2d_TS_RESP (const TS_RESP *a, unsigned char **pp)
TS_RESP * d2i_TS_RESP (TS_RESP **a, const unsigned char **pp, long length)
TS_TST_INFO * PKCS7_to_TS_TST_INFO (PKCS7 *token)
TS_RESP * TS_RESP_dup (TS_RESP *a)
TS_RESP * d2i_TS_RESP_fp (FILE *fp, TS_RESP **a)
int i2d_TS_RESP_fp (FILE *fp, TS_RESP *a)
TS_RESP * d2i_TS_RESP_bio (BIO *bio, TS_RESP **a)
int i2d_TS_RESP_bio (BIO *bio, TS_RESP *a)
TS_STATUS_INFO * TS_STATUS_INFO_new (void)
void TS_STATUS_INFO_free (TS_STATUS_INFO *a)
int i2d_TS_STATUS_INFO (const TS_STATUS_INFO *a, unsigned char **pp)
TS_STATUS_INFO * d2i_TS_STATUS_INFO (TS_STATUS_INFO **a, const unsigned char **pp, long length)
TS_STATUS_INFO * TS_STATUS_INFO_dup (TS_STATUS_INFO *a)
TS_TST_INFO * TS_TST_INFO_new (void)
void TS_TST_INFO_free (TS_TST_INFO *a)
int i2d_TS_TST_INFO (const TS_TST_INFO *a, unsigned char **pp)
TS_TST_INFO * d2i_TS_TST_INFO (TS_TST_INFO **a, const unsigned char **pp, long length)
TS_TST_INFO * TS_TST_INFO_dup (TS_TST_INFO *a)
TS_TST_INFO * d2i_TS_TST_INFO_fp (FILE *fp, TS_TST_INFO **a)
int i2d_TS_TST_INFO_fp (FILE *fp, TS_TST_INFO *a)
TS_TST_INFO * d2i_TS_TST_INFO_bio (BIO *bio, TS_TST_INFO **a)
int i2d_TS_TST_INFO_bio (BIO *bio, TS_TST_INFO *a)
TS_ACCURACY * TS_ACCURACY_new (void)
void TS_ACCURACY_free (TS_ACCURACY *a)
int i2d_TS_ACCURACY (const TS_ACCURACY *a, unsigned char **pp)
TS_ACCURACY * d2i_TS_ACCURACY (TS_ACCURACY **a, const unsigned char **pp, long length)
TS_ACCURACY * TS_ACCURACY_dup (TS_ACCURACY *a)
ESS_ISSUER_SERIAL * ESS_ISSUER_SERIAL_new (void)
void ESS_ISSUER_SERIAL_free (ESS_ISSUER_SERIAL *a)
int i2d_ESS_ISSUER_SERIAL (const ESS_ISSUER_SERIAL *a, unsigned char **pp)
ESS_ISSUER_SERIAL * d2i_ESS_ISSUER_SERIAL (ESS_ISSUER_SERIAL **a, const unsigned char **pp, long length)
ESS_ISSUER_SERIAL * ESS_ISSUER_SERIAL_dup (ESS_ISSUER_SERIAL *a)
ESS_CERT_ID * ESS_CERT_ID_new (void)
void ESS_CERT_ID_free (ESS_CERT_ID *a)
int i2d_ESS_CERT_ID (const ESS_CERT_ID *a, unsigned char **pp)
ESS_CERT_ID * d2i_ESS_CERT_ID (ESS_CERT_ID **a, const unsigned char **pp, long length)
ESS_CERT_ID * ESS_CERT_ID_dup (ESS_CERT_ID *a)
ESS_SIGNING_CERT * ESS_SIGNING_CERT_new (void)
void ESS_SIGNING_CERT_free (ESS_SIGNING_CERT *a)
int i2d_ESS_SIGNING_CERT (const ESS_SIGNING_CERT *a, unsigned char **pp)
ESS_SIGNING_CERT * d2i_ESS_SIGNING_CERT (ESS_SIGNING_CERT **a, const unsigned char **pp, long length)
ESS_SIGNING_CERT * ESS_SIGNING_CERT_dup (ESS_SIGNING_CERT *a)
int TS_REQ_set_version (TS_REQ *a, long version)
long TS_REQ_get_version (const TS_REQ *a)
int TS_STATUS_INFO_set_status (TS_STATUS_INFO *a, int i)
const ASN1_INTEGER * TS_STATUS_INFO_get0_status (const TS_STATUS_INFO *a)
const STACK_OF (ASN1_UTF8STRING) *TS_STATUS_INFO_get0_text(const TS_STATUS_INFO *a)
const ASN1_BIT_STRING * TS_STATUS_INFO_get0_failure_info (const TS_STATUS_INFO *a)
int TS_REQ_set_msg_imprint (TS_REQ *a, TS_MSG_IMPRINT *msg_imprint)
TS_MSG_IMPRINT * TS_REQ_get_msg_imprint (TS_REQ *a)
int TS_MSG_IMPRINT_set_algo (TS_MSG_IMPRINT *a, X509_ALGOR *alg)
X509_ALGOR * TS_MSG_IMPRINT_get_algo (TS_MSG_IMPRINT *a)
int TS_MSG_IMPRINT_set_msg (TS_MSG_IMPRINT *a, unsigned char *d, int len)
ASN1_OCTET_STRING * TS_MSG_IMPRINT_get_msg (TS_MSG_IMPRINT *a)
int TS_REQ_set_policy_id (TS_REQ *a, const ASN1_OBJECT *policy)
ASN1_OBJECT * TS_REQ_get_policy_id (TS_REQ *a)
int TS_REQ_set_nonce (TS_REQ *a, const ASN1_INTEGER *nonce)
const ASN1_INTEGER * TS_REQ_get_nonce (const TS_REQ *a)
int TS_REQ_set_cert_req (TS_REQ *a, int cert_req)
int TS_REQ_get_cert_req (const TS_REQ *a)
STACK_OF (X509_EXTENSION) *TS_REQ_get_exts(TS_REQ *a)
void TS_REQ_ext_free (TS_REQ *a)
int TS_REQ_get_ext_count (TS_REQ *a)
int TS_REQ_get_ext_by_NID (TS_REQ *a, int nid, int lastpos)
int TS_REQ_get_ext_by_OBJ (TS_REQ *a, const ASN1_OBJECT *obj, int lastpos)
int TS_REQ_get_ext_by_critical (TS_REQ *a, int crit, int lastpos)
X509_EXTENSION * TS_REQ_get_ext (TS_REQ *a, int loc)
X509_EXTENSION * TS_REQ_delete_ext (TS_REQ *a, int loc)
int TS_REQ_add_ext (TS_REQ *a, X509_EXTENSION *ex, int loc)
void * TS_REQ_get_ext_d2i (TS_REQ *a, int nid, int *crit, int *idx)
int TS_REQ_print_bio (BIO *bio, TS_REQ *a)
int TS_RESP_set_status_info (TS_RESP *a, TS_STATUS_INFO *info)
TS_STATUS_INFO * TS_RESP_get_status_info (TS_RESP *a)
void TS_RESP_set_tst_info (TS_RESP *a, PKCS7 *p7, TS_TST_INFO *tst_info)
PKCS7 * TS_RESP_get_token (TS_RESP *a)
TS_TST_INFO * TS_RESP_get_tst_info (TS_RESP *a)
int TS_TST_INFO_set_version (TS_TST_INFO *a, long version)
long TS_TST_INFO_get_version (const TS_TST_INFO *a)
int TS_TST_INFO_set_policy_id (TS_TST_INFO *a, ASN1_OBJECT *policy_id)
ASN1_OBJECT * TS_TST_INFO_get_policy_id (TS_TST_INFO *a)
int TS_TST_INFO_set_msg_imprint (TS_TST_INFO *a, TS_MSG_IMPRINT *msg_imprint)
TS_MSG_IMPRINT * TS_TST_INFO_get_msg_imprint (TS_TST_INFO *a)
int TS_TST_INFO_set_serial (TS_TST_INFO *a, const ASN1_INTEGER *serial)
const ASN1_INTEGER * TS_TST_INFO_get_serial (const TS_TST_INFO *a)
int TS_TST_INFO_set_time (TS_TST_INFO *a, const ASN1_GENERALIZEDTIME *gtime)
const ASN1_GENERALIZEDTIME * TS_TST_INFO_get_time (const TS_TST_INFO *a)
int TS_TST_INFO_set_accuracy (TS_TST_INFO *a, TS_ACCURACY *accuracy)
TS_ACCURACY * TS_TST_INFO_get_accuracy (TS_TST_INFO *a)
int TS_ACCURACY_set_seconds (TS_ACCURACY *a, const ASN1_INTEGER *seconds)
const ASN1_INTEGER * TS_ACCURACY_get_seconds (const TS_ACCURACY *a)
int TS_ACCURACY_set_millis (TS_ACCURACY *a, const ASN1_INTEGER *millis)
const ASN1_INTEGER * TS_ACCURACY_get_millis (const TS_ACCURACY *a)
int TS_ACCURACY_set_micros (TS_ACCURACY *a, const ASN1_INTEGER *micros)
const ASN1_INTEGER * TS_ACCURACY_get_micros (const TS_ACCURACY *a)
int TS_TST_INFO_set_ordering (TS_TST_INFO *a, int ordering)
int TS_TST_INFO_get_ordering (const TS_TST_INFO *a)
int TS_TST_INFO_set_nonce (TS_TST_INFO *a, const ASN1_INTEGER *nonce)
const ASN1_INTEGER * TS_TST_INFO_get_nonce (const TS_TST_INFO *a)
int TS_TST_INFO_set_tsa (TS_TST_INFO *a, GENERAL_NAME *tsa)
GENERAL_NAME * TS_TST_INFO_get_tsa (TS_TST_INFO *a)
void TS_TST_INFO_ext_free (TS_TST_INFO *a)
int TS_TST_INFO_get_ext_count (TS_TST_INFO *a)
int TS_TST_INFO_get_ext_by_NID (TS_TST_INFO *a, int nid, int lastpos)
int TS_TST_INFO_get_ext_by_OBJ (TS_TST_INFO *a, const ASN1_OBJECT *obj, int lastpos)
int TS_TST_INFO_get_ext_by_critical (TS_TST_INFO *a, int crit, int lastpos)
X509_EXTENSION * TS_TST_INFO_get_ext (TS_TST_INFO *a, int loc)
X509_EXTENSION * TS_TST_INFO_delete_ext (TS_TST_INFO *a, int loc)
int TS_TST_INFO_add_ext (TS_TST_INFO *a, X509_EXTENSION *ex, int loc)
void * TS_TST_INFO_get_ext_d2i (TS_TST_INFO *a, int nid, int *crit, int *idx)
TS_RESP_CTX * TS_RESP_CTX_new (void)
void TS_RESP_CTX_free (TS_RESP_CTX *ctx)
int TS_RESP_CTX_set_signer_cert (TS_RESP_CTX *ctx, X509 *signer)
int TS_RESP_CTX_set_signer_key (TS_RESP_CTX *ctx, EVP_PKEY *key)
int TS_RESP_CTX_set_signer_digest (TS_RESP_CTX *ctx, const EVP_MD *signer_digest)
int TS_RESP_CTX_set_def_policy (TS_RESP_CTX *ctx, const ASN1_OBJECT *def_policy)
int TS_RESP_CTX_set_certs (TS_RESP_CTX *ctx, STACK_OF(X509) *certs)
int TS_RESP_CTX_add_policy (TS_RESP_CTX *ctx, const ASN1_OBJECT *policy)
int TS_RESP_CTX_add_md (TS_RESP_CTX *ctx, const EVP_MD *md)
int TS_RESP_CTX_set_accuracy (TS_RESP_CTX *ctx, int secs, int millis, int micros)
int TS_RESP_CTX_set_clock_precision_digits (TS_RESP_CTX *ctx, unsigned clock_precision_digits)
void TS_RESP_CTX_add_flags (TS_RESP_CTX *ctx, int flags)
void TS_RESP_CTX_set_serial_cb (TS_RESP_CTX *ctx, TS_serial_cb cb, void *data)
void TS_RESP_CTX_set_time_cb (TS_RESP_CTX *ctx, TS_time_cb cb, void *data)
void TS_RESP_CTX_set_extension_cb (TS_RESP_CTX *ctx, TS_extension_cb cb, void *data)
int TS_RESP_CTX_set_status_info (TS_RESP_CTX *ctx, int status, const char *text)
int TS_RESP_CTX_set_status_info_cond (TS_RESP_CTX *ctx, int status, const char *text)
int TS_RESP_CTX_add_failure_info (TS_RESP_CTX *ctx, int failure)
TS_REQ * TS_RESP_CTX_get_request (TS_RESP_CTX *ctx)
TS_TST_INFO * TS_RESP_CTX_get_tst_info (TS_RESP_CTX *ctx)
TS_RESP * TS_RESP_create_response (TS_RESP_CTX *ctx, BIO *req_bio)
int TS_RESP_verify_signature (PKCS7 *token, STACK_OF(X509) *certs, X509_STORE *store, X509 **signer_out)
int TS_RESP_verify_response (TS_VERIFY_CTX *ctx, TS_RESP *response)
int TS_RESP_verify_token (TS_VERIFY_CTX *ctx, PKCS7 *token)
TS_VERIFY_CTX * TS_VERIFY_CTX_new (void)
void TS_VERIFY_CTX_init (TS_VERIFY_CTX *ctx)
void TS_VERIFY_CTX_free (TS_VERIFY_CTX *ctx)
void TS_VERIFY_CTX_cleanup (TS_VERIFY_CTX *ctx)
int TS_VERIFY_CTX_set_flags (TS_VERIFY_CTX *ctx, int f)
int TS_VERIFY_CTX_add_flags (TS_VERIFY_CTX *ctx, int f)
BIO * TS_VERIFY_CTX_set_data (TS_VERIFY_CTX *ctx, BIO *b)
unsigned char * TS_VERIFY_CTX_set_imprint (TS_VERIFY_CTX *ctx, unsigned char *hexstr, long len)
X509_STORE * TS_VERIFY_CTX_set_store (TS_VERIFY_CTX *ctx, X509_STORE *s)
STACK_OF (X509) *TS_VERIFY_CTS_set_certs(TS_VERIFY_CTX *ctx
TS_VERIFY_CTX * TS_REQ_to_TS_VERIFY_CTX (TS_REQ *req, TS_VERIFY_CTX *ctx)
int TS_RESP_print_bio (BIO *bio, TS_RESP *a)
int TS_STATUS_INFO_print_bio (BIO *bio, TS_STATUS_INFO *a)
int TS_TST_INFO_print_bio (BIO *bio, TS_TST_INFO *a)
int TS_ASN1_INTEGER_print_bio (BIO *bio, const ASN1_INTEGER *num)
int TS_OBJ_print_bio (BIO *bio, const ASN1_OBJECT *obj)
int TS_ext_print_bio (BIO *bio, const STACK_OF(X509_EXTENSION) *extensions)
int TS_X509_ALGOR_print_bio (BIO *bio, const X509_ALGOR *alg)
int TS_MSG_IMPRINT_print_bio (BIO *bio, TS_MSG_IMPRINT *msg)
X509 * TS_CONF_load_cert (const char *file)
EVP_PKEY * TS_CONF_load_key (const char *file, const char *pass)
const char * TS_CONF_get_tsa_section (CONF *conf, const char *section)
int TS_CONF_set_serial (CONF *conf, const char *section, TS_serial_cb cb, TS_RESP_CTX *ctx)
int TS_CONF_set_crypto_device (CONF *conf, const char *section, const char *device)
int TS_CONF_set_default_engine (const char *name)
int TS_CONF_set_signer_cert (CONF *conf, const char *section, const char *cert, TS_RESP_CTX *ctx)
int TS_CONF_set_certs (CONF *conf, const char *section, const char *certs, TS_RESP_CTX *ctx)
int TS_CONF_set_signer_key (CONF *conf, const char *section, const char *key, const char *pass, TS_RESP_CTX *ctx)
int TS_CONF_set_signer_digest (CONF *conf, const char *section, const char *md, TS_RESP_CTX *ctx)
int TS_CONF_set_def_policy (CONF *conf, const char *section, const char *policy, TS_RESP_CTX *ctx)
int TS_CONF_set_policies (CONF *conf, const char *section, TS_RESP_CTX *ctx)
int TS_CONF_set_digests (CONF *conf, const char *section, TS_RESP_CTX *ctx)
int TS_CONF_set_accuracy (CONF *conf, const char *section, TS_RESP_CTX *ctx)
int TS_CONF_set_clock_precision_digits (CONF *conf, const char *section, TS_RESP_CTX *ctx)
int TS_CONF_set_ordering (CONF *conf, const char *section, TS_RESP_CTX *ctx)
int TS_CONF_set_tsa_name (CONF *conf, const char *section, TS_RESP_CTX *ctx)
int TS_CONF_set_ess_cert_id_chain (CONF *conf, const char *section, TS_RESP_CTX *ctx)
int ERR_load_TS_strings (void)
Macro Definition Documentation
TS_ESS_CERT_ID_CHAIN
#define TS_ESS_CERT_ID_CHAIN 0x04
Definition at line 279 of file ts.h.
TS_F_DEF_SERIAL_CB
#define TS_F_DEF_SERIAL_CB 110
Definition at line 544 of file ts.h.
TS_F_DEF_TIME_CB
#define TS_F_DEF_TIME_CB 111
Definition at line 545 of file ts.h.
TS_F_ESS_ADD_SIGNING_CERT
#define TS_F_ESS_ADD_SIGNING_CERT 112
Definition at line 546 of file ts.h.
TS_F_ESS_CERT_ID_NEW_INIT
#define TS_F_ESS_CERT_ID_NEW_INIT 113
Definition at line 547 of file ts.h.
TS_F_ESS_SIGNING_CERT_NEW_INIT
#define TS_F_ESS_SIGNING_CERT_NEW_INIT 114
Definition at line 548 of file ts.h.
TS_F_INT_TS_RESP_VERIFY_TOKEN
#define TS_F_INT_TS_RESP_VERIFY_TOKEN 149
Definition at line 549 of file ts.h.
TS_F_PKCS7_TO_TS_TST_INFO
#define TS_F_PKCS7_TO_TS_TST_INFO 148
Definition at line 550 of file ts.h.
TS_F_TS_ACCURACY_SET_MICROS
#define TS_F_TS_ACCURACY_SET_MICROS 115
Definition at line 551 of file ts.h.
Referenced by TS_ACCURACY_set_micros().
TS_F_TS_ACCURACY_SET_MILLIS
#define TS_F_TS_ACCURACY_SET_MILLIS 116
Definition at line 552 of file ts.h.
Referenced by TS_ACCURACY_set_millis().
TS_F_TS_ACCURACY_SET_SECONDS
#define TS_F_TS_ACCURACY_SET_SECONDS 117
Definition at line 553 of file ts.h.
Referenced by TS_ACCURACY_set_seconds().
TS_F_TS_CHECK_IMPRINTS
#define TS_F_TS_CHECK_IMPRINTS 100
Definition at line 554 of file ts.h.
TS_F_TS_CHECK_NONCES
#define TS_F_TS_CHECK_NONCES 101
Definition at line 555 of file ts.h.
TS_F_TS_CHECK_POLICY
#define TS_F_TS_CHECK_POLICY 102
Definition at line 556 of file ts.h.
TS_F_TS_CHECK_SIGNING_CERTS
#define TS_F_TS_CHECK_SIGNING_CERTS 103
Definition at line 557 of file ts.h.
TS_F_TS_CHECK_STATUS_INFO
#define TS_F_TS_CHECK_STATUS_INFO 104
Definition at line 558 of file ts.h.
TS_F_TS_COMPUTE_IMPRINT
#define TS_F_TS_COMPUTE_IMPRINT 145
Definition at line 559 of file ts.h.
TS_F_TS_CONF_INVALID
#define TS_F_TS_CONF_INVALID 151
Definition at line 560 of file ts.h.
TS_F_TS_CONF_LOAD_CERT
#define TS_F_TS_CONF_LOAD_CERT 153
Definition at line 561 of file ts.h.
TS_F_TS_CONF_LOAD_CERTS
#define TS_F_TS_CONF_LOAD_CERTS 154
Definition at line 562 of file ts.h.
Referenced by STACK_OF().
TS_F_TS_CONF_LOAD_KEY
#define TS_F_TS_CONF_LOAD_KEY 155
Definition at line 563 of file ts.h.
Referenced by TS_CONF_load_key().
TS_F_TS_CONF_LOOKUP_FAIL
#define TS_F_TS_CONF_LOOKUP_FAIL 152
Definition at line 564 of file ts.h.
TS_F_TS_CONF_SET_DEFAULT_ENGINE
#define TS_F_TS_CONF_SET_DEFAULT_ENGINE 146
Definition at line 565 of file ts.h.
TS_F_TS_GET_STATUS_TEXT
#define TS_F_TS_GET_STATUS_TEXT 105
Definition at line 566 of file ts.h.
TS_F_TS_MSG_IMPRINT_SET_ALGO
#define TS_F_TS_MSG_IMPRINT_SET_ALGO 118
Definition at line 567 of file ts.h.
Referenced by TS_MSG_IMPRINT_set_algo().
TS_F_TS_REQ_SET_MSG_IMPRINT
#define TS_F_TS_REQ_SET_MSG_IMPRINT 119
Definition at line 568 of file ts.h.
Referenced by TS_REQ_set_msg_imprint().
TS_F_TS_REQ_SET_NONCE
#define TS_F_TS_REQ_SET_NONCE 120
Definition at line 569 of file ts.h.
Referenced by TS_REQ_set_nonce().
TS_F_TS_REQ_SET_POLICY_ID
#define TS_F_TS_REQ_SET_POLICY_ID 121
Definition at line 570 of file ts.h.
Referenced by TS_REQ_set_policy_id().
TS_F_TS_RESP_CREATE_RESPONSE
#define TS_F_TS_RESP_CREATE_RESPONSE 122
Definition at line 571 of file ts.h.
TS_F_TS_RESP_CREATE_TST_INFO
#define TS_F_TS_RESP_CREATE_TST_INFO 123
Definition at line 572 of file ts.h.
TS_F_TS_RESP_CTX_ADD_FAILURE_INFO
#define TS_F_TS_RESP_CTX_ADD_FAILURE_INFO 124
Definition at line 573 of file ts.h.
Referenced by TS_RESP_CTX_add_failure_info().
TS_F_TS_RESP_CTX_ADD_MD
#define TS_F_TS_RESP_CTX_ADD_MD 125
Definition at line 574 of file ts.h.
TS_F_TS_RESP_CTX_ADD_POLICY
#define TS_F_TS_RESP_CTX_ADD_POLICY 126
Definition at line 575 of file ts.h.
Referenced by TS_RESP_CTX_add_policy().
TS_F_TS_RESP_CTX_NEW
#define TS_F_TS_RESP_CTX_NEW 127
Definition at line 576 of file ts.h.
Referenced by TS_RESP_CTX_new().
TS_F_TS_RESP_CTX_SET_ACCURACY
#define TS_F_TS_RESP_CTX_SET_ACCURACY 128
Definition at line 577 of file ts.h.
Referenced by TS_RESP_CTX_set_accuracy().
TS_F_TS_RESP_CTX_SET_CERTS
#define TS_F_TS_RESP_CTX_SET_CERTS 129
Definition at line 578 of file ts.h.
Referenced by TS_RESP_CTX_set_certs().
TS_F_TS_RESP_CTX_SET_DEF_POLICY
#define TS_F_TS_RESP_CTX_SET_DEF_POLICY 130
Definition at line 579 of file ts.h.
Referenced by TS_RESP_CTX_set_def_policy().
TS_F_TS_RESP_CTX_SET_SIGNER_CERT
#define TS_F_TS_RESP_CTX_SET_SIGNER_CERT 131
Definition at line 580 of file ts.h.
Referenced by TS_RESP_CTX_set_signer_cert().
TS_F_TS_RESP_CTX_SET_STATUS_INFO
#define TS_F_TS_RESP_CTX_SET_STATUS_INFO 132
Definition at line 581 of file ts.h.
TS_F_TS_RESP_GET_POLICY
#define TS_F_TS_RESP_GET_POLICY 133
Definition at line 582 of file ts.h.
TS_F_TS_RESP_SET_GENTIME_WITH_PRECISION
#define TS_F_TS_RESP_SET_GENTIME_WITH_PRECISION 134
Definition at line 583 of file ts.h.
TS_F_TS_RESP_SET_STATUS_INFO
#define TS_F_TS_RESP_SET_STATUS_INFO 135
Definition at line 584 of file ts.h.
Referenced by TS_RESP_set_status_info().
TS_F_TS_RESP_SET_TST_INFO
#define TS_F_TS_RESP_SET_TST_INFO 150
Definition at line 585 of file ts.h.
TS_F_TS_RESP_SIGN
#define TS_F_TS_RESP_SIGN 136
Definition at line 586 of file ts.h.
TS_F_TS_RESP_VERIFY_SIGNATURE
#define TS_F_TS_RESP_VERIFY_SIGNATURE 106
Definition at line 587 of file ts.h.
TS_F_TS_TST_INFO_SET_ACCURACY
#define TS_F_TS_TST_INFO_SET_ACCURACY 137
Definition at line 588 of file ts.h.
Referenced by TS_TST_INFO_set_accuracy().
TS_F_TS_TST_INFO_SET_MSG_IMPRINT
#define TS_F_TS_TST_INFO_SET_MSG_IMPRINT 138
Definition at line 589 of file ts.h.
Referenced by TS_TST_INFO_set_msg_imprint().
TS_F_TS_TST_INFO_SET_NONCE
#define TS_F_TS_TST_INFO_SET_NONCE 139
Definition at line 590 of file ts.h.
Referenced by TS_TST_INFO_set_nonce().
TS_F_TS_TST_INFO_SET_POLICY_ID
#define TS_F_TS_TST_INFO_SET_POLICY_ID 140
Definition at line 591 of file ts.h.
Referenced by TS_TST_INFO_set_policy_id().
TS_F_TS_TST_INFO_SET_SERIAL
#define TS_F_TS_TST_INFO_SET_SERIAL 141
Definition at line 592 of file ts.h.
Referenced by TS_TST_INFO_set_serial().
TS_F_TS_TST_INFO_SET_TIME
#define TS_F_TS_TST_INFO_SET_TIME 142
Definition at line 593 of file ts.h.
Referenced by TS_TST_INFO_set_time().
TS_F_TS_TST_INFO_SET_TSA
#define TS_F_TS_TST_INFO_SET_TSA 143
Definition at line 594 of file ts.h.
Referenced by TS_TST_INFO_set_tsa().
TS_F_TS_VERIFY
#define TS_F_TS_VERIFY 108
Definition at line 595 of file ts.h.
TS_F_TS_VERIFY_CERT
#define TS_F_TS_VERIFY_CERT 109
Definition at line 596 of file ts.h.
TS_F_TS_VERIFY_CTX_NEW
#define TS_F_TS_VERIFY_CTX_NEW 144
Definition at line 597 of file ts.h.
Referenced by TS_VERIFY_CTX_new().
TS_INFO_ADD_INFO_NOT_AVAILABLE
#define TS_INFO_ADD_INFO_NOT_AVAILABLE 17
Definition at line 53 of file ts.h.
Referenced by TS_STATUS_INFO_print_bio().
TS_INFO_BAD_ALG
#define TS_INFO_BAD_ALG 0
Definition at line 47 of file ts.h.
Referenced by TS_STATUS_INFO_print_bio().
TS_INFO_BAD_DATA_FORMAT
#define TS_INFO_BAD_DATA_FORMAT 5
Definition at line 49 of file ts.h.
Referenced by TS_STATUS_INFO_print_bio().
TS_INFO_BAD_REQUEST
#define TS_INFO_BAD_REQUEST 2
Definition at line 48 of file ts.h.
Referenced by TS_STATUS_INFO_print_bio().
TS_INFO_SYSTEM_FAILURE
#define TS_INFO_SYSTEM_FAILURE 25
Definition at line 54 of file ts.h.
Referenced by TS_STATUS_INFO_print_bio().
TS_INFO_TIME_NOT_AVAILABLE
#define TS_INFO_TIME_NOT_AVAILABLE 14
Definition at line 50 of file ts.h.
Referenced by TS_STATUS_INFO_print_bio().
TS_INFO_UNACCEPTED_EXTENSION
#define TS_INFO_UNACCEPTED_EXTENSION 16
Definition at line 52 of file ts.h.
Referenced by TS_STATUS_INFO_print_bio().
TS_INFO_UNACCEPTED_POLICY
#define TS_INFO_UNACCEPTED_POLICY 15
Definition at line 51 of file ts.h.
Referenced by TS_STATUS_INFO_print_bio().
TS_MAX_CLOCK_PRECISION_DIGITS
#define TS_MAX_CLOCK_PRECISION_DIGITS 6
Definition at line 349 of file ts.h.
Referenced by TS_RESP_CTX_set_clock_precision_digits().
TS_MAX_STATUS_LENGTH
#define TS_MAX_STATUS_LENGTH (1024 * 1024)
Definition at line 352 of file ts.h.
TS_ORDERING
#define TS_ORDERING 0x02
Definition at line 272 of file ts.h.
TS_R_BAD_PKCS7_TYPE
#define TS_R_BAD_PKCS7_TYPE 132
Definition at line 600 of file ts.h.
TS_R_BAD_TYPE
#define TS_R_BAD_TYPE 133
Definition at line 601 of file ts.h.
TS_R_CANNOT_LOAD_CERT
#define TS_R_CANNOT_LOAD_CERT 137
Definition at line 602 of file ts.h.
Referenced by STACK_OF().
TS_R_CANNOT_LOAD_KEY
#define TS_R_CANNOT_LOAD_KEY 138
Definition at line 603 of file ts.h.
Referenced by TS_CONF_load_key().
TS_R_CERTIFICATE_VERIFY_ERROR
#define TS_R_CERTIFICATE_VERIFY_ERROR 100
Definition at line 604 of file ts.h.
TS_R_COULD_NOT_SET_ENGINE
#define TS_R_COULD_NOT_SET_ENGINE 127
Definition at line 605 of file ts.h.
TS_R_COULD_NOT_SET_TIME
#define TS_R_COULD_NOT_SET_TIME 115
Definition at line 606 of file ts.h.
TS_R_DETACHED_CONTENT
#define TS_R_DETACHED_CONTENT 134
Definition at line 607 of file ts.h.
TS_R_ESS_ADD_SIGNING_CERT_ERROR
#define TS_R_ESS_ADD_SIGNING_CERT_ERROR 116
Definition at line 608 of file ts.h.
TS_R_ESS_SIGNING_CERTIFICATE_ERROR
#define TS_R_ESS_SIGNING_CERTIFICATE_ERROR 101
Definition at line 609 of file ts.h.
TS_R_INVALID_NULL_POINTER
#define TS_R_INVALID_NULL_POINTER 102
Definition at line 610 of file ts.h.
TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE
#define TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE 117
Definition at line 611 of file ts.h.
Referenced by TS_RESP_CTX_set_signer_cert().
TS_R_MESSAGE_IMPRINT_MISMATCH
#define TS_R_MESSAGE_IMPRINT_MISMATCH 103
Definition at line 612 of file ts.h.
TS_R_NO_CONTENT
#define TS_R_NO_CONTENT 106
Definition at line 615 of file ts.h.
TS_R_NO_TIME_STAMP_TOKEN
#define TS_R_NO_TIME_STAMP_TOKEN 107
Definition at line 616 of file ts.h.
TS_R_NONCE_MISMATCH
#define TS_R_NONCE_MISMATCH 104
Definition at line 613 of file ts.h.
TS_R_NONCE_NOT_RETURNED
#define TS_R_NONCE_NOT_RETURNED 105
Definition at line 614 of file ts.h.
TS_R_PKCS7_ADD_SIGNATURE_ERROR
#define TS_R_PKCS7_ADD_SIGNATURE_ERROR 118
Definition at line 617 of file ts.h.
TS_R_PKCS7_ADD_SIGNED_ATTR_ERROR
#define TS_R_PKCS7_ADD_SIGNED_ATTR_ERROR 119
Definition at line 618 of file ts.h.
TS_R_PKCS7_TO_TS_TST_INFO_FAILED
#define TS_R_PKCS7_TO_TS_TST_INFO_FAILED 129
Definition at line 619 of file ts.h.
TS_R_POLICY_MISMATCH
#define TS_R_POLICY_MISMATCH 108
Definition at line 620 of file ts.h.
TS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE
#define TS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE 120
Definition at line 621 of file ts.h.
TS_R_RESPONSE_SETUP_ERROR
#define TS_R_RESPONSE_SETUP_ERROR 121
Definition at line 622 of file ts.h.
TS_R_SIGNATURE_FAILURE
#define TS_R_SIGNATURE_FAILURE 109
Definition at line 623 of file ts.h.
TS_R_THERE_MUST_BE_ONE_SIGNER
#define TS_R_THERE_MUST_BE_ONE_SIGNER 110
Definition at line 624 of file ts.h.
TS_R_TIME_SYSCALL_ERROR
#define TS_R_TIME_SYSCALL_ERROR 122
Definition at line 625 of file ts.h.
TS_R_TOKEN_NOT_PRESENT
#define TS_R_TOKEN_NOT_PRESENT 130
Definition at line 626 of file ts.h.
TS_R_TOKEN_PRESENT
#define TS_R_TOKEN_PRESENT 131
Definition at line 627 of file ts.h.
TS_R_TS_DATASIGN
#define TS_R_TS_DATASIGN 124
Definition at line 631 of file ts.h.
TS_R_TSA_NAME_MISMATCH
#define TS_R_TSA_NAME_MISMATCH 111
Definition at line 628 of file ts.h.
TS_R_TSA_UNTRUSTED
#define TS_R_TSA_UNTRUSTED 112
Definition at line 629 of file ts.h.
TS_R_TST_INFO_SETUP_ERROR
#define TS_R_TST_INFO_SETUP_ERROR 123
Definition at line 630 of file ts.h.
TS_R_UNACCEPTABLE_POLICY
#define TS_R_UNACCEPTABLE_POLICY 125
Definition at line 632 of file ts.h.
TS_R_UNSUPPORTED_MD_ALGORITHM
#define TS_R_UNSUPPORTED_MD_ALGORITHM 126
Definition at line 633 of file ts.h.
TS_R_UNSUPPORTED_VERSION
#define TS_R_UNSUPPORTED_VERSION 113
Definition at line 634 of file ts.h.
TS_R_VAR_BAD_VALUE
#define TS_R_VAR_BAD_VALUE 135
Definition at line 635 of file ts.h.
TS_R_VAR_LOOKUP_FAILURE
#define TS_R_VAR_LOOKUP_FAILURE 136
Definition at line 636 of file ts.h.
TS_R_WRONG_CONTENT_TYPE
#define TS_R_WRONG_CONTENT_TYPE 114
Definition at line 637 of file ts.h.
TS_STATUS_GRANTED
#define TS_STATUS_GRANTED 0
Definition at line 39 of file ts.h.
TS_STATUS_GRANTED_WITH_MODS
#define TS_STATUS_GRANTED_WITH_MODS 1
Definition at line 40 of file ts.h.
TS_STATUS_REJECTION
#define TS_STATUS_REJECTION 2
Definition at line 41 of file ts.h.
TS_STATUS_REVOCATION_NOTIFICATION
#define TS_STATUS_REVOCATION_NOTIFICATION 5
Definition at line 44 of file ts.h.
TS_STATUS_REVOCATION_WARNING
#define TS_STATUS_REVOCATION_WARNING 4
Definition at line 43 of file ts.h.
TS_STATUS_WAITING
#define TS_STATUS_WAITING 3
Definition at line 42 of file ts.h.
TS_TSA_NAME
#define TS_TSA_NAME 0x01
Definition at line 269 of file ts.h.
TS_VFY_ALL_DATA
#define TS_VFY_ALL_DATA
Value:
(TS_VFY_SIGNATURE       \
                                 | TS_VFY_VERSION       \
                                 | TS_VFY_POLICY        \
                                 | TS_VFY_DATA          \
                                 | TS_VFY_NONCE         \
                                 | TS_VFY_SIGNER        \
                                 | TS_VFY_TSA_NAME)
Definition at line 435 of file ts.h.
TS_VFY_ALL_IMPRINT
#define TS_VFY_ALL_IMPRINT
Value:
(TS_VFY_SIGNATURE       \
                                 | TS_VFY_VERSION       \
                                 | TS_VFY_POLICY        \
                                 | TS_VFY_IMPRINT       \
                                 | TS_VFY_NONCE         \
                                 | TS_VFY_SIGNER        \
                                 | TS_VFY_TSA_NAME)
Definition at line 428 of file ts.h.
TS_VFY_DATA
#define TS_VFY_DATA (1u << 4)
Definition at line 419 of file ts.h.
TS_VFY_IMPRINT
#define TS_VFY_IMPRINT (1u << 3)
Definition at line 413 of file ts.h.
TS_VFY_NONCE
#define TS_VFY_NONCE (1u << 5)
Definition at line 421 of file ts.h.
TS_VFY_POLICY
#define TS_VFY_POLICY (1u << 2)
Definition at line 408 of file ts.h.
TS_VFY_SIGNATURE
#define TS_VFY_SIGNATURE (1u << 0)
Definition at line 404 of file ts.h.
TS_VFY_SIGNER
#define TS_VFY_SIGNER (1u << 6)
Definition at line 423 of file ts.h.
TS_VFY_TSA_NAME
#define TS_VFY_TSA_NAME (1u << 7)
Definition at line 425 of file ts.h.
TS_VFY_VERSION
#define TS_VFY_VERSION (1u << 1)
Definition at line 406 of file ts.h.
Typedef Documentation
TS_extension_cb
typedef int(* TS_extension_cb) (struct TS_resp_ctx *, X509_EXTENSION *, void *)
Definition at line 300 of file ts.h.
TS_serial_cb
typedef ASN1_INTEGER*(* TS_serial_cb) (struct TS_resp_ctx *, void *)
Definition at line 285 of file ts.h.
TS_time_cb
typedef int(* TS_time_cb) (struct TS_resp_ctx *, void *, long *sec, long *usec)
Definition at line 292 of file ts.h.
Function Documentation
d2i_ESS_CERT_ID()
ESS_CERT_ID* d2i_ESS_CERT_ID (ESS_CERT_ID ** a, const unsigned char ** pp, long length)
d2i_ESS_ISSUER_SERIAL()
ESS_ISSUER_SERIAL* d2i_ESS_ISSUER_SERIAL (ESS_ISSUER_SERIAL ** a, const unsigned char ** pp, long length)
d2i_ESS_SIGNING_CERT()
ESS_SIGNING_CERT* d2i_ESS_SIGNING_CERT (ESS_SIGNING_CERT ** a, const unsigned char ** pp, long length)
d2i_TS_ACCURACY()
TS_ACCURACY* d2i_TS_ACCURACY (TS_ACCURACY ** a, const unsigned char ** pp, long length)
d2i_TS_MSG_IMPRINT()
TS_MSG_IMPRINT* d2i_TS_MSG_IMPRINT (TS_MSG_IMPRINT ** a, const unsigned char ** pp, long length)
d2i_TS_MSG_IMPRINT_bio()
TS_MSG_IMPRINT* d2i_TS_MSG_IMPRINT_bio (BIO * bio, TS_MSG_IMPRINT ** a)
d2i_TS_MSG_IMPRINT_fp()
TS_MSG_IMPRINT* d2i_TS_MSG_IMPRINT_fp (FILE * fp, TS_MSG_IMPRINT ** a)
d2i_TS_REQ()
TS_REQ* d2i_TS_REQ (TS_REQ ** a, const unsigned char ** pp, long length)
d2i_TS_REQ_bio()
TS_REQ* d2i_TS_REQ_bio (BIO * fp, TS_REQ ** a)
d2i_TS_REQ_fp()
TS_REQ* d2i_TS_REQ_fp (FILE * fp, TS_REQ ** a)
d2i_TS_RESP()
TS_RESP* d2i_TS_RESP (TS_RESP ** a, const unsigned char ** pp, long length)
d2i_TS_RESP_bio()
TS_RESP* d2i_TS_RESP_bio (BIO * bio, TS_RESP ** a)
d2i_TS_RESP_fp()
TS_RESP* d2i_TS_RESP_fp (FILE * fp, TS_RESP ** a)
d2i_TS_STATUS_INFO()
TS_STATUS_INFO* d2i_TS_STATUS_INFO (TS_STATUS_INFO ** a, const unsigned char ** pp, long length)
d2i_TS_TST_INFO()
TS_TST_INFO* d2i_TS_TST_INFO (TS_TST_INFO ** a, const unsigned char ** pp, long length)
d2i_TS_TST_INFO_bio()
TS_TST_INFO* d2i_TS_TST_INFO_bio (BIO * bio, TS_TST_INFO ** a)
d2i_TS_TST_INFO_fp()
TS_TST_INFO* d2i_TS_TST_INFO_fp (FILE * fp, TS_TST_INFO ** a)
ERR_load_TS_strings()
int ERR_load_TS_strings (void)
Definition at line 134 of file ts_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
ESS_CERT_ID_dup()
ESS_CERT_ID* ESS_CERT_ID_dup (ESS_CERT_ID * a)
ESS_CERT_ID_free()
void ESS_CERT_ID_free (ESS_CERT_ID * a)
ESS_CERT_ID_new()
ESS_CERT_ID* ESS_CERT_ID_new (void)
ESS_ISSUER_SERIAL_dup()
ESS_ISSUER_SERIAL* ESS_ISSUER_SERIAL_dup (ESS_ISSUER_SERIAL * a)
ESS_ISSUER_SERIAL_free()
void ESS_ISSUER_SERIAL_free (ESS_ISSUER_SERIAL * a)
ESS_ISSUER_SERIAL_new()
ESS_ISSUER_SERIAL* ESS_ISSUER_SERIAL_new (void)
ESS_SIGNING_CERT_dup()
ESS_SIGNING_CERT* ESS_SIGNING_CERT_dup (ESS_SIGNING_CERT * a)
ESS_SIGNING_CERT_free()
void ESS_SIGNING_CERT_free (ESS_SIGNING_CERT * a)
ESS_SIGNING_CERT_new()
ESS_SIGNING_CERT* ESS_SIGNING_CERT_new (void)
i2d_ESS_CERT_ID()
int i2d_ESS_CERT_ID (const ESS_CERT_ID * a, unsigned char ** pp)
i2d_ESS_ISSUER_SERIAL()
int i2d_ESS_ISSUER_SERIAL (const ESS_ISSUER_SERIAL * a, unsigned char ** pp)
i2d_ESS_SIGNING_CERT()
int i2d_ESS_SIGNING_CERT (const ESS_SIGNING_CERT * a, unsigned char ** pp)
i2d_TS_ACCURACY()
int i2d_TS_ACCURACY (const TS_ACCURACY * a, unsigned char ** pp)
i2d_TS_MSG_IMPRINT()
int i2d_TS_MSG_IMPRINT (const TS_MSG_IMPRINT * a, unsigned char ** pp)
i2d_TS_MSG_IMPRINT_bio()
int i2d_TS_MSG_IMPRINT_bio (BIO * bio, TS_MSG_IMPRINT * a)
i2d_TS_MSG_IMPRINT_fp()
int i2d_TS_MSG_IMPRINT_fp (FILE * fp, TS_MSG_IMPRINT * a)
i2d_TS_REQ()
int i2d_TS_REQ (const TS_REQ * a, unsigned char ** pp)
i2d_TS_REQ_bio()
int i2d_TS_REQ_bio (BIO * fp, TS_REQ * a)
i2d_TS_REQ_fp()
int i2d_TS_REQ_fp (FILE * fp, TS_REQ * a)
i2d_TS_RESP()
int i2d_TS_RESP (const TS_RESP * a, unsigned char ** pp)
i2d_TS_RESP_bio()
int i2d_TS_RESP_bio (BIO * bio, TS_RESP * a)
i2d_TS_RESP_fp()
int i2d_TS_RESP_fp (FILE * fp, TS_RESP * a)
i2d_TS_STATUS_INFO()
int i2d_TS_STATUS_INFO (const TS_STATUS_INFO * a, unsigned char ** pp)
i2d_TS_TST_INFO()
int i2d_TS_TST_INFO (const TS_TST_INFO * a, unsigned char ** pp)
i2d_TS_TST_INFO_bio()
int i2d_TS_TST_INFO_bio (BIO * bio, TS_TST_INFO * a)
i2d_TS_TST_INFO_fp()
int i2d_TS_TST_INFO_fp (FILE * fp, TS_TST_INFO * a)
PKCS7_to_TS_TST_INFO()
TS_TST_INFO* PKCS7_to_TS_TST_INFO (PKCS7 * token)
Referenced by TS_RESP_verify_token().
STACK_OF() [1/3]
const STACK_OF (ASN1_UTF8STRING) const
STACK_OF() [2/3]
STACK_OF (X509_EXTENSION)
Definition at line 132 of file ts_req_utils.c.
References attr, ERR_R_MALLOC_FAILURE, ERR_R_PASSED_NULL_PARAMETER, NULL, X509_EXTENSION_dup(), X509_F_X509V3_ADD_EXT, and X509err.
Referenced by X509_REVOKED_set_serialNumber().
STACK_OF() [3/3]
STACK_OF (X509)
Definition at line 478 of file cms_lib.c.
TS_ACCURACY_dup()
TS_ACCURACY* TS_ACCURACY_dup (TS_ACCURACY * a)
Referenced by TS_TST_INFO_set_accuracy().
TS_ACCURACY_free()
void TS_ACCURACY_free (TS_ACCURACY * a)
Referenced by TS_TST_INFO_set_accuracy().
TS_ACCURACY_get_micros()
const ASN1_INTEGER* TS_ACCURACY_get_micros (const TS_ACCURACY * a)
Definition at line 235 of file ts_rsp_utils.c.
TS_ACCURACY_get_millis()
const ASN1_INTEGER* TS_ACCURACY_get_millis (const TS_ACCURACY * a)
Definition at line 212 of file ts_rsp_utils.c.
TS_ACCURACY_get_seconds()
const ASN1_INTEGER* TS_ACCURACY_get_seconds (const TS_ACCURACY * a)
Definition at line 189 of file ts_rsp_utils.c.
TS_ACCURACY_new()
TS_ACCURACY* TS_ACCURACY_new (void)
TS_ACCURACY_set_micros()
int TS_ACCURACY_set_micros (TS_ACCURACY * a, const ASN1_INTEGER * micros)
Definition at line 217 of file ts_rsp_utils.c.
References ASN1_INTEGER_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_ACCURACY_SET_MICROS, and TSerr.
TS_ACCURACY_set_millis()
int TS_ACCURACY_set_millis (TS_ACCURACY * a, const ASN1_INTEGER * millis)
Definition at line 194 of file ts_rsp_utils.c.
References ASN1_INTEGER_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_ACCURACY_SET_MILLIS, and TSerr.
TS_ACCURACY_set_seconds()
int TS_ACCURACY_set_seconds (TS_ACCURACY * a, const ASN1_INTEGER * seconds)
Definition at line 173 of file ts_rsp_utils.c.
References ASN1_INTEGER_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_ACCURACY_SET_SECONDS, and TSerr.
TS_ASN1_INTEGER_print_bio()
int TS_ASN1_INTEGER_print_bio (BIO * bio, const ASN1_INTEGER * num)
Definition at line 19 of file ts_lib.c.
References ASN1_INTEGER_to_BN(), BIO_write(), BN_bn2hex(), BN_free(), BN_new(), NULL, and OPENSSL_free.
Referenced by TS_REQ_print_bio(), and TS_TST_INFO_print_bio().
TS_CONF_get_tsa_section()
const char* TS_CONF_get_tsa_section (CONF * conf, const char * section)
Definition at line 115 of file ts_conf.c.
TS_CONF_load_cert()
X509* TS_CONF_load_cert (const char * file)
Definition at line 43 of file ts_conf.c.
TS_CONF_load_key()
EVP_PKEY* TS_CONF_load_key (const char * file, const char * pass)
Definition at line 86 of file ts_conf.c.
References BIO_free(), BIO_new_file(), key, NULL, PEM_read_bio_PrivateKey(), TS_F_TS_CONF_LOAD_KEY, TS_R_CANNOT_LOAD_KEY, and TSerr.
TS_CONF_set_accuracy()
int TS_CONF_set_accuracy (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 374 of file ts_conf.c.
TS_CONF_set_certs()
int TS_CONF_set_certs (CONF * conf, const char * section, const char * certs, TS_RESP_CTX * ctx)
Definition at line 211 of file ts_conf.c.
TS_CONF_set_clock_precision_digits()
int TS_CONF_set_clock_precision_digits (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 411 of file ts_conf.c.
TS_CONF_set_crypto_device()
int TS_CONF_set_crypto_device (CONF * conf, const char * section, const char * device)
Definition at line 143 of file ts_conf.c.
TS_CONF_set_def_policy()
int TS_CONF_set_def_policy (CONF * conf, const char * section, const char * policy, TS_RESP_CTX * ctx)
Definition at line 280 of file ts_conf.c.
TS_CONF_set_default_engine()
int TS_CONF_set_default_engine (const char * name)
Definition at line 160 of file ts_conf.c.
References e, and NULL.
TS_CONF_set_digests()
int TS_CONF_set_digests (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 336 of file ts_conf.c.
TS_CONF_set_ess_cert_id_chain()
int TS_CONF_set_ess_cert_id_chain (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 463 of file ts_conf.c.
TS_CONF_set_ordering()
int TS_CONF_set_ordering (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 453 of file ts_conf.c.
TS_CONF_set_policies()
int TS_CONF_set_policies (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 304 of file ts_conf.c.
TS_CONF_set_serial()
int TS_CONF_set_serial (CONF * conf, const char * section, TS_serial_cb cb, TS_RESP_CTX * ctx)
Definition at line 125 of file ts_conf.c.
TS_CONF_set_signer_cert()
int TS_CONF_set_signer_cert (CONF * conf, const char * section, const char * cert, TS_RESP_CTX * ctx)
Definition at line 187 of file ts_conf.c.
TS_CONF_set_signer_digest()
int TS_CONF_set_signer_digest (CONF * conf, const char * section, const char * md, TS_RESP_CTX * ctx)
Definition at line 256 of file ts_conf.c.
TS_CONF_set_signer_key()
int TS_CONF_set_signer_key (CONF * conf, const char * section, const char * key, const char * pass, TS_RESP_CTX * ctx)
Definition at line 233 of file ts_conf.c.
TS_CONF_set_tsa_name()
int TS_CONF_set_tsa_name (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 458 of file ts_conf.c.
TS_ext_print_bio()
int TS_ext_print_bio (BIO * bio, const STACK_OF(X509_EXTENSION) * extensions)
Definition at line 49 of file ts_lib.c.
References ASN1_STRING_print(), BIO_printf(), BIO_write(), ex, i2a_ASN1_OBJECT(), obj, X509_EXTENSION_get_critical(), X509_EXTENSION_get_data(), X509_EXTENSION_get_object(), X509V3_EXT_print(), X509v3_get_ext(), and X509v3_get_ext_count().
Referenced by TS_REQ_print_bio().
TS_MSG_IMPRINT_dup()
TS_MSG_IMPRINT* TS_MSG_IMPRINT_dup (TS_MSG_IMPRINT * a)
Referenced by TS_REQ_set_msg_imprint(), and TS_TST_INFO_set_msg_imprint().
TS_MSG_IMPRINT_free()
void TS_MSG_IMPRINT_free (TS_MSG_IMPRINT * a)
Referenced by TS_REQ_set_msg_imprint(), and TS_TST_INFO_set_msg_imprint().
TS_MSG_IMPRINT_get_algo()
X509_ALGOR* TS_MSG_IMPRINT_get_algo (TS_MSG_IMPRINT * a)
Definition at line 64 of file ts_req_utils.c.
TS_MSG_IMPRINT_get_msg()
ASN1_OCTET_STRING* TS_MSG_IMPRINT_get_msg (TS_MSG_IMPRINT * a)
Definition at line 74 of file ts_req_utils.c.
TS_MSG_IMPRINT_new()
TS_MSG_IMPRINT* TS_MSG_IMPRINT_new (void)
TS_MSG_IMPRINT_print_bio()
int TS_MSG_IMPRINT_print_bio (BIO * bio, TS_MSG_IMPRINT * msg)
Definition at line 81 of file ts_lib.c.
Referenced by TS_REQ_print_bio(), and TS_TST_INFO_print_bio().
TS_MSG_IMPRINT_set_algo()
int TS_MSG_IMPRINT_set_algo (TS_MSG_IMPRINT * a, X509_ALGOR * alg)
Definition at line 48 of file ts_req_utils.c.
References ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_MSG_IMPRINT_SET_ALGO, TSerr, and X509_ALGOR_dup().
TS_MSG_IMPRINT_set_msg()
int TS_MSG_IMPRINT_set_msg (TS_MSG_IMPRINT * a, unsigned char * d, int len)
Definition at line 69 of file ts_req_utils.c.
References ASN1_OCTET_STRING_set().
TS_OBJ_print_bio()
int TS_OBJ_print_bio (BIO * bio, const ASN1_OBJECT * obj)
Definition at line 39 of file ts_lib.c.
References BIO_printf(), and OBJ_obj2txt().
Referenced by TS_REQ_print_bio(), and TS_TST_INFO_print_bio().
TS_REQ_add_ext()
int TS_REQ_add_ext (TS_REQ * a, X509_EXTENSION * ex, int loc)
Definition at line 175 of file ts_req_utils.c.
References NULL.
TS_REQ_delete_ext()
X509_EXTENSION* TS_REQ_delete_ext (TS_REQ * a, int loc)
Definition at line 170 of file ts_req_utils.c.
References X509v3_delete_ext().
TS_REQ_dup()
TS_REQ* TS_REQ_dup (TS_REQ * a)
TS_REQ_ext_free()
void TS_REQ_ext_free (TS_REQ * a)
Definition at line 137 of file ts_req_utils.c.
References NULL.
TS_REQ_free()
void TS_REQ_free (TS_REQ * a)
TS_REQ_get_cert_req()
int TS_REQ_get_cert_req (const TS_REQ * a)
Definition at line 127 of file ts_req_utils.c.
TS_REQ_get_ext()
X509_EXTENSION* TS_REQ_get_ext (TS_REQ * a, int loc)
Definition at line 165 of file ts_req_utils.c.
References X509v3_get_ext().
TS_REQ_get_ext_by_critical()
int TS_REQ_get_ext_by_critical (TS_REQ * a, int crit, int lastpos)
Definition at line 160 of file ts_req_utils.c.
References X509v3_get_ext_by_critical().
TS_REQ_get_ext_by_NID()
int TS_REQ_get_ext_by_NID (TS_REQ * a, int nid, int lastpos)
Definition at line 150 of file ts_req_utils.c.
References X509v3_get_ext_by_NID().
TS_REQ_get_ext_by_OBJ()
int TS_REQ_get_ext_by_OBJ (TS_REQ * a, const ASN1_OBJECT * obj, int lastpos)
Definition at line 155 of file ts_req_utils.c.
References X509v3_get_ext_by_OBJ().
TS_REQ_get_ext_count()
int TS_REQ_get_ext_count (TS_REQ * a)
Definition at line 145 of file ts_req_utils.c.
References X509v3_get_ext_count().
TS_REQ_get_ext_d2i()
void* TS_REQ_get_ext_d2i (TS_REQ * a, int nid, int * crit, int * idx)
Definition at line 180 of file ts_req_utils.c.
TS_REQ_get_msg_imprint()
TS_MSG_IMPRINT* TS_REQ_get_msg_imprint (TS_REQ * a)
Definition at line 43 of file ts_req_utils.c.
TS_REQ_get_nonce()
const ASN1_INTEGER* TS_REQ_get_nonce (const TS_REQ * a)
Definition at line 116 of file ts_req_utils.c.
TS_REQ_get_policy_id()
ASN1_OBJECT* TS_REQ_get_policy_id (TS_REQ * a)
Definition at line 95 of file ts_req_utils.c.
Referenced by TS_REQ_print_bio().
TS_REQ_get_version()
long TS_REQ_get_version (const TS_REQ * a)
Definition at line 22 of file ts_req_utils.c.
References ASN1_INTEGER_get().
Referenced by TS_REQ_print_bio().
TS_REQ_new()
TS_REQ* TS_REQ_new (void)
TS_REQ_print_bio()
int TS_REQ_print_bio (BIO * bio, TS_REQ * a)
Definition at line 18 of file ts_req_print.c.
References BIO_printf(), BIO_write(), NULL, TS_ASN1_INTEGER_print_bio(), TS_ext_print_bio(), TS_MSG_IMPRINT_print_bio(), TS_OBJ_print_bio(), TS_REQ_get_policy_id(), and TS_REQ_get_version().
TS_REQ_set_cert_req()
int TS_REQ_set_cert_req (TS_REQ * a, int cert_req)
Definition at line 121 of file ts_req_utils.c.
TS_REQ_set_msg_imprint()
int TS_REQ_set_msg_imprint (TS_REQ * a, TS_MSG_IMPRINT * msg_imprint)
Definition at line 27 of file ts_req_utils.c.
References ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_REQ_SET_MSG_IMPRINT, TS_MSG_IMPRINT_dup(), TS_MSG_IMPRINT_free(), and TSerr.
TS_REQ_set_nonce()
int TS_REQ_set_nonce (TS_REQ * a, const ASN1_INTEGER * nonce)
Definition at line 100 of file ts_req_utils.c.
References ASN1_INTEGER_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_REQ_SET_NONCE, and TSerr.
TS_REQ_set_policy_id()
int TS_REQ_set_policy_id (TS_REQ * a, const ASN1_OBJECT * policy)
Definition at line 79 of file ts_req_utils.c.
References ASN1_OBJECT_free(), ERR_R_MALLOC_FAILURE, NULL, OBJ_dup(), TS_F_TS_REQ_SET_POLICY_ID, and TSerr.
TS_REQ_set_version()
int TS_REQ_set_version (TS_REQ * a, long version)
Definition at line 17 of file ts_req_utils.c.
References ASN1_INTEGER_set().
TS_REQ_to_TS_VERIFY_CTX()
TS_VERIFY_CTX* TS_REQ_to_TS_VERIFY_CTX (TS_REQ * req, TS_VERIFY_CTX * ctx)
Definition at line 100 of file ts_verify_ctx.c.
TS_RESP_create_response()
TS_RESP* TS_RESP_create_response (TS_RESP_CTX * ctx, BIO * req_bio)
Definition at line 371 of file ts_rsp_sign.c.
TS_RESP_CTX_add_failure_info()
int TS_RESP_CTX_add_failure_info (TS_RESP_CTX * ctx, int failure)
Definition at line 337 of file ts_rsp_sign.c.
References ASN1_BIT_STRING_set_bit(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_RESP_CTX_ADD_FAILURE_INFO, and TSerr.
TS_RESP_CTX_add_flags()
void TS_RESP_CTX_add_flags (TS_RESP_CTX * ctx, int flags)
Definition at line 268 of file ts_rsp_sign.c.
References flags.
TS_RESP_CTX_add_md()
int TS_RESP_CTX_add_md (TS_RESP_CTX * ctx, const EVP_MD * md)
Definition at line 221 of file ts_rsp_sign.c.
TS_RESP_CTX_add_policy()
int TS_RESP_CTX_add_policy (TS_RESP_CTX * ctx, const ASN1_OBJECT * policy)
Definition at line 202 of file ts_rsp_sign.c.
References ASN1_OBJECT_free(), ERR_R_MALLOC_FAILURE, NULL, OBJ_dup(), TS_F_TS_RESP_CTX_ADD_POLICY, and TSerr.
TS_RESP_CTX_free()
void TS_RESP_CTX_free (TS_RESP_CTX * ctx)
Definition at line 131 of file ts_rsp_sign.c.
References ASN1_OBJECT_free(), EVP_PKEY_free(), and OPENSSL_free.
TS_RESP_CTX_get_request()
TS_REQ* TS_RESP_CTX_get_request (TS_RESP_CTX * ctx)
Definition at line 351 of file ts_rsp_sign.c.
TS_RESP_CTX_get_tst_info()
TS_TST_INFO* TS_RESP_CTX_get_tst_info (TS_RESP_CTX * ctx)
Definition at line 356 of file ts_rsp_sign.c.
TS_RESP_CTX_new()
TS_RESP_CTX* TS_RESP_CTX_new (void)
Definition at line 113 of file ts_rsp_sign.c.
References ctx, ERR_R_MALLOC_FAILURE, EVP_sha256(), NULL, OPENSSL_zalloc, TS_F_TS_RESP_CTX_NEW, and TSerr.
TS_RESP_CTX_set_accuracy()
int TS_RESP_CTX_set_accuracy (TS_RESP_CTX * ctx, int secs, int millis, int micros)
Definition at line 243 of file ts_rsp_sign.c.
References ASN1_INTEGER_set(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_RESP_CTX_SET_ACCURACY, TS_RESP_CTX_accuracy_free, and TSerr.
TS_RESP_CTX_set_certs()
int TS_RESP_CTX_set_certs (TS_RESP_CTX * ctx, STACK_OF(X509) * certs)
Definition at line 187 of file ts_rsp_sign.c.
References ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_RESP_CTX_SET_CERTS, and TSerr.
TS_RESP_CTX_set_clock_precision_digits()
int TS_RESP_CTX_set_clock_precision_digits (TS_RESP_CTX * ctx, unsigned clock_precision_digits)
Definition at line 361 of file ts_rsp_sign.c.
References TS_MAX_CLOCK_PRECISION_DIGITS.
TS_RESP_CTX_set_def_policy()
int TS_RESP_CTX_set_def_policy (TS_RESP_CTX * ctx, const ASN1_OBJECT * def_policy)
Definition at line 176 of file ts_rsp_sign.c.
References ASN1_OBJECT_free(), ERR_R_MALLOC_FAILURE, NULL, OBJ_dup(), TS_F_TS_RESP_CTX_SET_DEF_POLICY, and TSerr.
TS_RESP_CTX_set_extension_cb()
void TS_RESP_CTX_set_extension_cb (TS_RESP_CTX * ctx, TS_extension_cb cb, void * data)
Definition at line 285 of file ts_rsp_sign.c.
References cb, and data.
TS_RESP_CTX_set_serial_cb()
void TS_RESP_CTX_set_serial_cb (TS_RESP_CTX * ctx, TS_serial_cb cb, void * data)
Definition at line 273 of file ts_rsp_sign.c.
References cb, and data.
TS_RESP_CTX_set_signer_cert()
int TS_RESP_CTX_set_signer_cert (TS_RESP_CTX * ctx, X509 * signer)
Definition at line 148 of file ts_rsp_sign.c.
References TS_F_TS_RESP_CTX_SET_SIGNER_CERT, TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE, TSerr, X509_check_purpose(), X509_PURPOSE_TIMESTAMP_SIGN, and X509_up_ref().
TS_RESP_CTX_set_signer_digest()
int TS_RESP_CTX_set_signer_digest (TS_RESP_CTX * ctx, const EVP_MD * signer_digest)
Definition at line 170 of file ts_rsp_sign.c.
TS_RESP_CTX_set_signer_key()
int TS_RESP_CTX_set_signer_key (TS_RESP_CTX * ctx, EVP_PKEY * key)
Definition at line 161 of file ts_rsp_sign.c.
References EVP_PKEY_free(), EVP_PKEY_up_ref(), and key.
TS_RESP_CTX_set_status_info()
int TS_RESP_CTX_set_status_info (TS_RESP_CTX * ctx, int status, const char * text)
Definition at line 292 of file ts_rsp_sign.c.
References NULL.
TS_RESP_CTX_set_status_info_cond()
int TS_RESP_CTX_set_status_info_cond (TS_RESP_CTX * ctx, int status, const char * text)
Definition at line 325 of file ts_rsp_sign.c.
TS_RESP_CTX_set_time_cb()
void TS_RESP_CTX_set_time_cb (TS_RESP_CTX * ctx, TS_time_cb cb, void * data)
Definition at line 279 of file ts_rsp_sign.c.
References cb, and data.
TS_RESP_dup()
TS_RESP* TS_RESP_dup (TS_RESP * a)
TS_RESP_free()
void TS_RESP_free (TS_RESP * a)
TS_RESP_get_status_info()
TS_STATUS_INFO* TS_RESP_get_status_info (TS_RESP * a)
Definition at line 34 of file ts_rsp_utils.c.
TS_RESP_get_token()
PKCS7* TS_RESP_get_token (TS_RESP * a)
Definition at line 48 of file ts_rsp_utils.c.
TS_RESP_get_tst_info()
TS_TST_INFO* TS_RESP_get_tst_info (TS_RESP * a)
Definition at line 53 of file ts_rsp_utils.c.
TS_RESP_new()
TS_RESP* TS_RESP_new (void)
TS_RESP_print_bio()
int TS_RESP_print_bio (BIO * bio, TS_RESP * a)
Definition at line 28 of file ts_rsp_print.c.
References BIO_printf(), NULL, TS_STATUS_INFO_print_bio(), and TS_TST_INFO_print_bio().
TS_RESP_set_status_info()
int TS_RESP_set_status_info (TS_RESP * a, TS_STATUS_INFO * info)
Definition at line 17 of file ts_rsp_utils.c.
References ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_RESP_SET_STATUS_INFO, TS_STATUS_INFO_dup(), TS_STATUS_INFO_free(), and TSerr.
TS_RESP_set_tst_info()
void TS_RESP_set_tst_info (TS_RESP * a, PKCS7 * p7, TS_TST_INFO * tst_info)
Definition at line 40 of file ts_rsp_utils.c.
References TS_TST_INFO_free().
TS_RESP_verify_response()
int TS_RESP_verify_response (TS_VERIFY_CTX * ctx, TS_RESP * response)
Definition at line 299 of file ts_rsp_verify.c.
TS_RESP_verify_signature()
int TS_RESP_verify_signature (PKCS7 * token, STACK_OF(X509) * certs, X509_STORE * store, X509 ** signer_out)
Definition at line 88 of file ts_rsp_verify.c.
References NULL, and STACK_OF.
TS_RESP_verify_token()
int TS_RESP_verify_token (TS_VERIFY_CTX * ctx, PKCS7 * token)
Definition at line 319 of file ts_rsp_verify.c.
References PKCS7_to_TS_TST_INFO().
TS_STATUS_INFO_dup()
TS_STATUS_INFO* TS_STATUS_INFO_dup (TS_STATUS_INFO * a)
Referenced by TS_RESP_set_status_info().
TS_STATUS_INFO_free()
void TS_STATUS_INFO_free (TS_STATUS_INFO * a)
Referenced by TS_RESP_set_status_info().
TS_STATUS_INFO_get0_failure_info()
const ASN1_BIT_STRING* TS_STATUS_INFO_get0_failure_info (const TS_STATUS_INFO * a)
Definition at line 362 of file ts_rsp_utils.c.
TS_STATUS_INFO_get0_status()
const ASN1_INTEGER* TS_STATUS_INFO_get0_status (const TS_STATUS_INFO * a)
Definition at line 351 of file ts_rsp_utils.c.
TS_STATUS_INFO_new()
TS_STATUS_INFO* TS_STATUS_INFO_new (void)
TS_STATUS_INFO_print_bio()
int TS_STATUS_INFO_print_bio (BIO * bio, TS_STATUS_INFO * a)
Definition at line 42 of file ts_rsp_print.c.
References ASN1_INTEGER_get(), ASN1_STRING_print_ex(), BIO_printf(), BIO_puts(), NULL, OSSL_NELEM, TS_INFO_ADD_INFO_NOT_AVAILABLE, TS_INFO_BAD_ALG, TS_INFO_BAD_DATA_FORMAT, TS_INFO_BAD_REQUEST, TS_INFO_SYSTEM_FAILURE, TS_INFO_TIME_NOT_AVAILABLE, TS_INFO_UNACCEPTED_EXTENSION, and TS_INFO_UNACCEPTED_POLICY.
Referenced by TS_RESP_print_bio().
TS_STATUS_INFO_set_status()
int TS_STATUS_INFO_set_status (TS_STATUS_INFO * a, int i)
Definition at line 346 of file ts_rsp_utils.c.
References ASN1_INTEGER_set().
TS_TST_INFO_add_ext()
int TS_TST_INFO_add_ext (TS_TST_INFO * a, X509_EXTENSION * ex, int loc)
Definition at line 336 of file ts_rsp_utils.c.
References NULL.
TS_TST_INFO_delete_ext()
X509_EXTENSION* TS_TST_INFO_delete_ext (TS_TST_INFO * a, int loc)
Definition at line 331 of file ts_rsp_utils.c.
References X509v3_delete_ext().
TS_TST_INFO_dup()
TS_TST_INFO* TS_TST_INFO_dup (TS_TST_INFO * a)
TS_TST_INFO_ext_free()
void TS_TST_INFO_ext_free (TS_TST_INFO * a)
Definition at line 298 of file ts_rsp_utils.c.
References NULL.
TS_TST_INFO_free()
void TS_TST_INFO_free (TS_TST_INFO * a)
Referenced by TS_RESP_set_tst_info().
TS_TST_INFO_get_accuracy()
TS_ACCURACY* TS_TST_INFO_get_accuracy (TS_TST_INFO * a)
Definition at line 168 of file ts_rsp_utils.c.
TS_TST_INFO_get_ext()
X509_EXTENSION* TS_TST_INFO_get_ext (TS_TST_INFO * a, int loc)
Definition at line 326 of file ts_rsp_utils.c.
References X509v3_get_ext().
TS_TST_INFO_get_ext_by_critical()
int TS_TST_INFO_get_ext_by_critical (TS_TST_INFO * a, int crit, int lastpos)
Definition at line 321 of file ts_rsp_utils.c.
References X509v3_get_ext_by_critical().
TS_TST_INFO_get_ext_by_NID()
int TS_TST_INFO_get_ext_by_NID (TS_TST_INFO * a, int nid, int lastpos)
Definition at line 311 of file ts_rsp_utils.c.
References X509v3_get_ext_by_NID().
TS_TST_INFO_get_ext_by_OBJ()
int TS_TST_INFO_get_ext_by_OBJ (TS_TST_INFO * a, const ASN1_OBJECT * obj, int lastpos)
Definition at line 316 of file ts_rsp_utils.c.
References X509v3_get_ext_by_OBJ().
TS_TST_INFO_get_ext_count()
int TS_TST_INFO_get_ext_count (TS_TST_INFO * a)
Definition at line 306 of file ts_rsp_utils.c.
References X509v3_get_ext_count().
TS_TST_INFO_get_ext_d2i()
void* TS_TST_INFO_get_ext_d2i (TS_TST_INFO * a, int nid, int * crit, int * idx)
Definition at line 341 of file ts_rsp_utils.c.
TS_TST_INFO_get_msg_imprint()
TS_MSG_IMPRINT* TS_TST_INFO_get_msg_imprint (TS_TST_INFO * a)
Definition at line 105 of file ts_rsp_utils.c.
TS_TST_INFO_get_nonce()
const ASN1_INTEGER* TS_TST_INFO_get_nonce (const TS_TST_INFO * a)
Definition at line 267 of file ts_rsp_utils.c.
TS_TST_INFO_get_ordering()
int TS_TST_INFO_get_ordering (const TS_TST_INFO * a)
Definition at line 246 of file ts_rsp_utils.c.
TS_TST_INFO_get_policy_id()
ASN1_OBJECT* TS_TST_INFO_get_policy_id (TS_TST_INFO * a)
Definition at line 84 of file ts_rsp_utils.c.
TS_TST_INFO_get_serial()
const ASN1_INTEGER* TS_TST_INFO_get_serial (const TS_TST_INFO * a)
Definition at line 126 of file ts_rsp_utils.c.
TS_TST_INFO_get_time()
const ASN1_GENERALIZEDTIME* TS_TST_INFO_get_time (const TS_TST_INFO * a)
Definition at line 147 of file ts_rsp_utils.c.
TS_TST_INFO_get_tsa()
GENERAL_NAME* TS_TST_INFO_get_tsa (TS_TST_INFO * a)
Definition at line 288 of file ts_rsp_utils.c.
TS_TST_INFO_get_version()
long TS_TST_INFO_get_version (const TS_TST_INFO * a)
Definition at line 63 of file ts_rsp_utils.c.
References ASN1_INTEGER_get().
TS_TST_INFO_new()
TS_TST_INFO* TS_TST_INFO_new (void)
TS_TST_INFO_print_bio()
int TS_TST_INFO_print_bio (BIO * bio, TS_TST_INFO * a)
Definition at line 118 of file ts_rsp_print.c.
References ASN1_GENERALIZEDTIME_print(), ASN1_INTEGER_get(), BIO_printf(), BIO_write(), NULL, TS_ASN1_INTEGER_print_bio(), TS_MSG_IMPRINT_print_bio(), and TS_OBJ_print_bio().
Referenced by TS_RESP_print_bio().
TS_TST_INFO_set_accuracy()
int TS_TST_INFO_set_accuracy (TS_TST_INFO * a, TS_ACCURACY * accuracy)
Definition at line 152 of file ts_rsp_utils.c.
References ERR_R_MALLOC_FAILURE, NULL, TS_ACCURACY_dup(), TS_ACCURACY_free(), TS_F_TS_TST_INFO_SET_ACCURACY, and TSerr.
TS_TST_INFO_set_msg_imprint()
int TS_TST_INFO_set_msg_imprint (TS_TST_INFO * a, TS_MSG_IMPRINT * msg_imprint)
Definition at line 89 of file ts_rsp_utils.c.
References ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_TST_INFO_SET_MSG_IMPRINT, TS_MSG_IMPRINT_dup(), TS_MSG_IMPRINT_free(), and TSerr.
TS_TST_INFO_set_nonce()
int TS_TST_INFO_set_nonce (TS_TST_INFO * a, const ASN1_INTEGER * nonce)
Definition at line 251 of file ts_rsp_utils.c.
References ASN1_INTEGER_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_TST_INFO_SET_NONCE, and TSerr.
TS_TST_INFO_set_ordering()
int TS_TST_INFO_set_ordering (TS_TST_INFO * a, int ordering)
Definition at line 240 of file ts_rsp_utils.c.
TS_TST_INFO_set_policy_id()
int TS_TST_INFO_set_policy_id (TS_TST_INFO * a, ASN1_OBJECT * policy_id)
Definition at line 68 of file ts_rsp_utils.c.
References ASN1_OBJECT_free(), ERR_R_MALLOC_FAILURE, NULL, OBJ_dup(), TS_F_TS_TST_INFO_SET_POLICY_ID, and TSerr.
TS_TST_INFO_set_serial()
int TS_TST_INFO_set_serial (TS_TST_INFO * a, const ASN1_INTEGER * serial)
Definition at line 110 of file ts_rsp_utils.c.
References ASN1_INTEGER_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_TST_INFO_SET_SERIAL, and TSerr.
TS_TST_INFO_set_time()
int TS_TST_INFO_set_time (TS_TST_INFO * a, const ASN1_GENERALIZEDTIME * gtime)
Definition at line 131 of file ts_rsp_utils.c.
References ASN1_STRING_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_TST_INFO_SET_TIME, and TSerr.
TS_TST_INFO_set_tsa()
int TS_TST_INFO_set_tsa (TS_TST_INFO * a, GENERAL_NAME * tsa)
Definition at line 272 of file ts_rsp_utils.c.
References ERR_R_MALLOC_FAILURE, GENERAL_NAME_dup(), NULL, TS_F_TS_TST_INFO_SET_TSA, and TSerr.
TS_TST_INFO_set_version()
int TS_TST_INFO_set_version (TS_TST_INFO * a, long version)
Definition at line 58 of file ts_rsp_utils.c.
References ASN1_INTEGER_set().
TS_VERIFY_CTX_add_flags()
int TS_VERIFY_CTX_add_flags (TS_VERIFY_CTX * ctx, int f)
Definition at line 39 of file ts_verify_ctx.c.
TS_VERIFY_CTX_cleanup()
void TS_VERIFY_CTX_cleanup (TS_VERIFY_CTX * ctx)
Definition at line 78 of file ts_verify_ctx.c.
References ASN1_OBJECT_free(), BIO_free_all(), OPENSSL_free, TS_VERIFY_CTX_init(), and X509_STORE_free().
Referenced by TS_VERIFY_CTX_free().
TS_VERIFY_CTX_free()
void TS_VERIFY_CTX_free (TS_VERIFY_CTX * ctx)
Definition at line 30 of file ts_verify_ctx.c.
References OPENSSL_free, and TS_VERIFY_CTX_cleanup().
TS_VERIFY_CTX_init()
void TS_VERIFY_CTX_init (TS_VERIFY_CTX * ctx)
Definition at line 24 of file ts_verify_ctx.c.
References NULL, and OPENSSL_assert.
Referenced by TS_VERIFY_CTX_cleanup().
TS_VERIFY_CTX_new()
TS_VERIFY_CTX* TS_VERIFY_CTX_new (void)
Definition at line 15 of file ts_verify_ctx.c.
References ctx, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_zalloc, TS_F_TS_VERIFY_CTX_NEW, and TSerr.
TS_VERIFY_CTX_set_data()
BIO* TS_VERIFY_CTX_set_data (TS_VERIFY_CTX * ctx, BIO * b)
Definition at line 51 of file ts_verify_ctx.c.
TS_VERIFY_CTX_set_flags()
int TS_VERIFY_CTX_set_flags (TS_VERIFY_CTX * ctx, int f)
Definition at line 45 of file ts_verify_ctx.c.
TS_VERIFY_CTX_set_imprint()
unsigned char* TS_VERIFY_CTX_set_imprint (TS_VERIFY_CTX * ctx, unsigned char * hexstr, long len)
Definition at line 70 of file ts_verify_ctx.c.
References len.
TS_VERIFY_CTX_set_store()
X509_STORE* TS_VERIFY_CTX_set_store (TS_VERIFY_CTX * ctx, X509_STORE * s)
Definition at line 57 of file ts_verify_ctx.c.
TS_X509_ALGOR_print_bio()
int TS_X509_ALGOR_print_bio (BIO * bio, const X509_ALGOR * alg)
Definition at line 74 of file ts_lib.c.
References BIO_printf(), NID_undef, OBJ_nid2ln(), and OBJ_obj2nid().