crypto/ts/ts_verify_ctx.c File Reference
ts_verify_ctx.c File Reference
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/ts.h>
#include "ts_lcl.h"
Functions
TS_VERIFY_CTX * TS_VERIFY_CTX_new (void)
void TS_VERIFY_CTX_init (TS_VERIFY_CTX *ctx)
void TS_VERIFY_CTX_free (TS_VERIFY_CTX *ctx)
int TS_VERIFY_CTX_add_flags (TS_VERIFY_CTX *ctx, int f)
int TS_VERIFY_CTX_set_flags (TS_VERIFY_CTX *ctx, int f)
BIO * TS_VERIFY_CTX_set_data (TS_VERIFY_CTX *ctx, BIO *b)
X509_STORE * TS_VERIFY_CTX_set_store (TS_VERIFY_CTX *ctx, X509_STORE *s)
STACK_OF (X509)
unsigned char * TS_VERIFY_CTX_set_imprint (TS_VERIFY_CTX *ctx, unsigned char *hexstr, long len)
void TS_VERIFY_CTX_cleanup (TS_VERIFY_CTX *ctx)
TS_VERIFY_CTX * TS_REQ_to_TS_VERIFY_CTX (TS_REQ *req, TS_VERIFY_CTX *ctx)
Function Documentation
STACK_OF()
STACK_OF (X509)
Definition at line 63 of file ts_verify_ctx.c.
TS_REQ_to_TS_VERIFY_CTX()
TS_VERIFY_CTX* TS_REQ_to_TS_VERIFY_CTX (TS_REQ * req, TS_VERIFY_CTX * ctx)
Definition at line 100 of file ts_verify_ctx.c.
TS_VERIFY_CTX_add_flags()
int TS_VERIFY_CTX_add_flags (TS_VERIFY_CTX * ctx, int f)
Definition at line 39 of file ts_verify_ctx.c.
TS_VERIFY_CTX_cleanup()
void TS_VERIFY_CTX_cleanup (TS_VERIFY_CTX * ctx)
Definition at line 78 of file ts_verify_ctx.c.
References ASN1_OBJECT_free(), BIO_free_all(), OPENSSL_free, TS_VERIFY_CTX_init(), and X509_STORE_free().
Referenced by TS_VERIFY_CTX_free().
TS_VERIFY_CTX_free()
void TS_VERIFY_CTX_free (TS_VERIFY_CTX * ctx)
Definition at line 30 of file ts_verify_ctx.c.
References OPENSSL_free, and TS_VERIFY_CTX_cleanup().
TS_VERIFY_CTX_init()
void TS_VERIFY_CTX_init (TS_VERIFY_CTX * ctx)
Definition at line 24 of file ts_verify_ctx.c.
References NULL, and OPENSSL_assert.
Referenced by TS_VERIFY_CTX_cleanup().
TS_VERIFY_CTX_new()
TS_VERIFY_CTX* TS_VERIFY_CTX_new (void)
Definition at line 15 of file ts_verify_ctx.c.
References ctx, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_zalloc, TS_F_TS_VERIFY_CTX_NEW, and TSerr.
TS_VERIFY_CTX_set_data()
BIO* TS_VERIFY_CTX_set_data (TS_VERIFY_CTX * ctx, BIO * b)
Definition at line 51 of file ts_verify_ctx.c.
TS_VERIFY_CTX_set_flags()
int TS_VERIFY_CTX_set_flags (TS_VERIFY_CTX * ctx, int f)
Definition at line 45 of file ts_verify_ctx.c.
TS_VERIFY_CTX_set_imprint()
unsigned char* TS_VERIFY_CTX_set_imprint (TS_VERIFY_CTX * ctx, unsigned char * hexstr, long len)
Definition at line 70 of file ts_verify_ctx.c.
References len.
TS_VERIFY_CTX_set_store()
X509_STORE* TS_VERIFY_CTX_set_store (TS_VERIFY_CTX * ctx, X509_STORE * s)
Definition at line 57 of file ts_verify_ctx.c.