crypto/ts/ts_req_utils.c File Reference
ts_req_utils.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/x509v3.h>
#include <openssl/ts.h>
#include "ts_lcl.h"
Functions
int TS_REQ_set_version (TS_REQ *a, long version)
long TS_REQ_get_version (const TS_REQ *a)
int TS_REQ_set_msg_imprint (TS_REQ *a, TS_MSG_IMPRINT *msg_imprint)
TS_MSG_IMPRINT * TS_REQ_get_msg_imprint (TS_REQ *a)
int TS_MSG_IMPRINT_set_algo (TS_MSG_IMPRINT *a, X509_ALGOR *alg)
X509_ALGOR * TS_MSG_IMPRINT_get_algo (TS_MSG_IMPRINT *a)
int TS_MSG_IMPRINT_set_msg (TS_MSG_IMPRINT *a, unsigned char *d, int len)
ASN1_OCTET_STRING * TS_MSG_IMPRINT_get_msg (TS_MSG_IMPRINT *a)
int TS_REQ_set_policy_id (TS_REQ *a, const ASN1_OBJECT *policy)
ASN1_OBJECT * TS_REQ_get_policy_id (TS_REQ *a)
int TS_REQ_set_nonce (TS_REQ *a, const ASN1_INTEGER *nonce)
const ASN1_INTEGER * TS_REQ_get_nonce (const TS_REQ *a)
int TS_REQ_set_cert_req (TS_REQ *a, int cert_req)
int TS_REQ_get_cert_req (const TS_REQ *a)
STACK_OF (X509_EXTENSION)
void TS_REQ_ext_free (TS_REQ *a)
int TS_REQ_get_ext_count (TS_REQ *a)
int TS_REQ_get_ext_by_NID (TS_REQ *a, int nid, int lastpos)
int TS_REQ_get_ext_by_OBJ (TS_REQ *a, const ASN1_OBJECT *obj, int lastpos)
int TS_REQ_get_ext_by_critical (TS_REQ *a, int crit, int lastpos)
X509_EXTENSION * TS_REQ_get_ext (TS_REQ *a, int loc)
X509_EXTENSION * TS_REQ_delete_ext (TS_REQ *a, int loc)
int TS_REQ_add_ext (TS_REQ *a, X509_EXTENSION *ex, int loc)
void * TS_REQ_get_ext_d2i (TS_REQ *a, int nid, int *crit, int *idx)
Function Documentation
STACK_OF()
STACK_OF (X509_EXTENSION)
Definition at line 132 of file ts_req_utils.c.
TS_MSG_IMPRINT_get_algo()
X509_ALGOR* TS_MSG_IMPRINT_get_algo (TS_MSG_IMPRINT * a)
Definition at line 64 of file ts_req_utils.c.
TS_MSG_IMPRINT_get_msg()
ASN1_OCTET_STRING* TS_MSG_IMPRINT_get_msg (TS_MSG_IMPRINT * a)
Definition at line 74 of file ts_req_utils.c.
TS_MSG_IMPRINT_set_algo()
int TS_MSG_IMPRINT_set_algo (TS_MSG_IMPRINT * a, X509_ALGOR * alg)
Definition at line 48 of file ts_req_utils.c.
References ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_MSG_IMPRINT_SET_ALGO, TSerr, and X509_ALGOR_dup().
TS_MSG_IMPRINT_set_msg()
int TS_MSG_IMPRINT_set_msg (TS_MSG_IMPRINT * a, unsigned char * d, int len)
Definition at line 69 of file ts_req_utils.c.
References ASN1_OCTET_STRING_set().
TS_REQ_add_ext()
int TS_REQ_add_ext (TS_REQ * a, X509_EXTENSION * ex, int loc)
Definition at line 175 of file ts_req_utils.c.
References NULL.
TS_REQ_delete_ext()
X509_EXTENSION* TS_REQ_delete_ext (TS_REQ * a, int loc)
Definition at line 170 of file ts_req_utils.c.
References X509v3_delete_ext().
TS_REQ_ext_free()
void TS_REQ_ext_free (TS_REQ * a)
Definition at line 137 of file ts_req_utils.c.
References NULL.
TS_REQ_get_cert_req()
int TS_REQ_get_cert_req (const TS_REQ * a)
Definition at line 127 of file ts_req_utils.c.
TS_REQ_get_ext()
X509_EXTENSION* TS_REQ_get_ext (TS_REQ * a, int loc)
Definition at line 165 of file ts_req_utils.c.
References X509v3_get_ext().
TS_REQ_get_ext_by_critical()
int TS_REQ_get_ext_by_critical (TS_REQ * a, int crit, int lastpos)
Definition at line 160 of file ts_req_utils.c.
References X509v3_get_ext_by_critical().
TS_REQ_get_ext_by_NID()
int TS_REQ_get_ext_by_NID (TS_REQ * a, int nid, int lastpos)
Definition at line 150 of file ts_req_utils.c.
References X509v3_get_ext_by_NID().
TS_REQ_get_ext_by_OBJ()
int TS_REQ_get_ext_by_OBJ (TS_REQ * a, const ASN1_OBJECT * obj, int lastpos)
Definition at line 155 of file ts_req_utils.c.
References X509v3_get_ext_by_OBJ().
TS_REQ_get_ext_count()
int TS_REQ_get_ext_count (TS_REQ * a)
Definition at line 145 of file ts_req_utils.c.
References X509v3_get_ext_count().
TS_REQ_get_ext_d2i()
void* TS_REQ_get_ext_d2i (TS_REQ * a, int nid, int * crit, int * idx)
Definition at line 180 of file ts_req_utils.c.
TS_REQ_get_msg_imprint()
TS_MSG_IMPRINT* TS_REQ_get_msg_imprint (TS_REQ * a)
Definition at line 43 of file ts_req_utils.c.
TS_REQ_get_nonce()
const ASN1_INTEGER* TS_REQ_get_nonce (const TS_REQ * a)
Definition at line 116 of file ts_req_utils.c.
TS_REQ_get_policy_id()
ASN1_OBJECT* TS_REQ_get_policy_id (TS_REQ * a)
Definition at line 95 of file ts_req_utils.c.
Referenced by TS_REQ_print_bio().
TS_REQ_get_version()
long TS_REQ_get_version (const TS_REQ * a)
Definition at line 22 of file ts_req_utils.c.
References ASN1_INTEGER_get().
Referenced by TS_REQ_print_bio().
TS_REQ_set_cert_req()
int TS_REQ_set_cert_req (TS_REQ * a, int cert_req)
Definition at line 121 of file ts_req_utils.c.
TS_REQ_set_msg_imprint()
int TS_REQ_set_msg_imprint (TS_REQ * a, TS_MSG_IMPRINT * msg_imprint)
Definition at line 27 of file ts_req_utils.c.
References ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_REQ_SET_MSG_IMPRINT, TS_MSG_IMPRINT_dup(), TS_MSG_IMPRINT_free(), and TSerr.
TS_REQ_set_nonce()
int TS_REQ_set_nonce (TS_REQ * a, const ASN1_INTEGER * nonce)
Definition at line 100 of file ts_req_utils.c.
References ASN1_INTEGER_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_REQ_SET_NONCE, and TSerr.
TS_REQ_set_policy_id()
int TS_REQ_set_policy_id (TS_REQ * a, const ASN1_OBJECT * policy)
Definition at line 79 of file ts_req_utils.c.
References ASN1_OBJECT_free(), ERR_R_MALLOC_FAILURE, NULL, OBJ_dup(), TS_F_TS_REQ_SET_POLICY_ID, and TSerr.
TS_REQ_set_version()
int TS_REQ_set_version (TS_REQ * a, long version)
Definition at line 17 of file ts_req_utils.c.
References ASN1_INTEGER_set().