crypto/ts/ts_conf.c File Reference
ts_conf.c File Reference
#include <string.h>
#include <openssl/crypto.h>
#include "internal/cryptlib.h"
#include <openssl/pem.h>
#include <openssl/engine.h>
#include <openssl/ts.h>
Macros
#define BASE_SECTION "tsa"
#define ENV_DEFAULT_TSA "default_tsa"
#define ENV_SERIAL "serial"
#define ENV_CRYPTO_DEVICE "crypto_device"
#define ENV_SIGNER_CERT "signer_cert"
#define ENV_CERTS "certs"
#define ENV_SIGNER_KEY "signer_key"
#define ENV_SIGNER_DIGEST "signer_digest"
#define ENV_DEFAULT_POLICY "default_policy"
#define ENV_OTHER_POLICIES "other_policies"
#define ENV_DIGESTS "digests"
#define ENV_ACCURACY "accuracy"
#define ENV_ORDERING "ordering"
#define ENV_TSA_NAME "tsa_name"
#define ENV_ESS_CERT_ID_CHAIN "ess_cert_id_chain"
#define ENV_VALUE_SECS "secs"
#define ENV_VALUE_MILLISECS "millisecs"
#define ENV_VALUE_MICROSECS "microsecs"
#define ENV_CLOCK_PRECISION_DIGITS "clock_precision_digits"
#define ENV_VALUE_YES "yes"
#define ENV_VALUE_NO "no"
Functions
X509 * TS_CONF_load_cert (const char *file)
STACK_OF (X509)
EVP_PKEY * TS_CONF_load_key (const char *file, const char *pass)
const char * TS_CONF_get_tsa_section (CONF *conf, const char *section)
int TS_CONF_set_serial (CONF *conf, const char *section, TS_serial_cb cb, TS_RESP_CTX *ctx)
int TS_CONF_set_crypto_device (CONF *conf, const char *section, const char *device)
int TS_CONF_set_default_engine (const char *name)
int TS_CONF_set_signer_cert (CONF *conf, const char *section, const char *cert, TS_RESP_CTX *ctx)
int TS_CONF_set_certs (CONF *conf, const char *section, const char *certs, TS_RESP_CTX *ctx)
int TS_CONF_set_signer_key (CONF *conf, const char *section, const char *key, const char *pass, TS_RESP_CTX *ctx)
int TS_CONF_set_signer_digest (CONF *conf, const char *section, const char *md, TS_RESP_CTX *ctx)
int TS_CONF_set_def_policy (CONF *conf, const char *section, const char *policy, TS_RESP_CTX *ctx)
int TS_CONF_set_policies (CONF *conf, const char *section, TS_RESP_CTX *ctx)
int TS_CONF_set_digests (CONF *conf, const char *section, TS_RESP_CTX *ctx)
int TS_CONF_set_accuracy (CONF *conf, const char *section, TS_RESP_CTX *ctx)
int TS_CONF_set_clock_precision_digits (CONF *conf, const char *section, TS_RESP_CTX *ctx)
int TS_CONF_set_ordering (CONF *conf, const char *section, TS_RESP_CTX *ctx)
int TS_CONF_set_tsa_name (CONF *conf, const char *section, TS_RESP_CTX *ctx)
int TS_CONF_set_ess_cert_id_chain (CONF *conf, const char *section, TS_RESP_CTX *ctx)
Macro Definition Documentation
BASE_SECTION
#define BASE_SECTION "tsa"
Definition at line 19 of file ts_conf.c.
ENV_ACCURACY
#define ENV_ACCURACY "accuracy"
Definition at line 30 of file ts_conf.c.
ENV_CERTS
#define ENV_CERTS "certs"
Definition at line 24 of file ts_conf.c.
ENV_CLOCK_PRECISION_DIGITS
#define ENV_CLOCK_PRECISION_DIGITS "clock_precision_digits"
Definition at line 37 of file ts_conf.c.
ENV_CRYPTO_DEVICE
#define ENV_CRYPTO_DEVICE "crypto_device"
Definition at line 22 of file ts_conf.c.
ENV_DEFAULT_POLICY
#define ENV_DEFAULT_POLICY "default_policy"
Definition at line 27 of file ts_conf.c.
ENV_DEFAULT_TSA
#define ENV_DEFAULT_TSA "default_tsa"
Definition at line 20 of file ts_conf.c.
ENV_DIGESTS
#define ENV_DIGESTS "digests"
Definition at line 29 of file ts_conf.c.
ENV_ESS_CERT_ID_CHAIN
#define ENV_ESS_CERT_ID_CHAIN "ess_cert_id_chain"
Definition at line 33 of file ts_conf.c.
ENV_ORDERING
#define ENV_ORDERING "ordering"
Definition at line 31 of file ts_conf.c.
ENV_OTHER_POLICIES
#define ENV_OTHER_POLICIES "other_policies"
Definition at line 28 of file ts_conf.c.
ENV_SERIAL
#define ENV_SERIAL "serial"
Definition at line 21 of file ts_conf.c.
ENV_SIGNER_CERT
#define ENV_SIGNER_CERT "signer_cert"
Definition at line 23 of file ts_conf.c.
ENV_SIGNER_DIGEST
#define ENV_SIGNER_DIGEST "signer_digest"
Definition at line 26 of file ts_conf.c.
ENV_SIGNER_KEY
#define ENV_SIGNER_KEY "signer_key"
Definition at line 25 of file ts_conf.c.
ENV_TSA_NAME
#define ENV_TSA_NAME "tsa_name"
Definition at line 32 of file ts_conf.c.
ENV_VALUE_MICROSECS
#define ENV_VALUE_MICROSECS "microsecs"
Definition at line 36 of file ts_conf.c.
ENV_VALUE_MILLISECS
#define ENV_VALUE_MILLISECS "millisecs"
Definition at line 35 of file ts_conf.c.
ENV_VALUE_NO
#define ENV_VALUE_NO "no"
Definition at line 39 of file ts_conf.c.
ENV_VALUE_SECS
#define ENV_VALUE_SECS "secs"
Definition at line 34 of file ts_conf.c.
ENV_VALUE_YES
#define ENV_VALUE_YES "yes"
Definition at line 38 of file ts_conf.c.
Function Documentation
STACK_OF()
STACK_OF (X509)
Definition at line 58 of file ts_conf.c.
References BIO_free(), BIO_new_file(), NULL, TS_F_TS_CONF_LOAD_CERTS, TS_R_CANNOT_LOAD_CERT, TSerr, X509_INFO::x509, and X509_INFO_free().
TS_CONF_get_tsa_section()
const char* TS_CONF_get_tsa_section (CONF * conf, const char * section)
Definition at line 115 of file ts_conf.c.
TS_CONF_load_cert()
X509* TS_CONF_load_cert (const char * file)
Definition at line 43 of file ts_conf.c.
TS_CONF_load_key()
EVP_PKEY* TS_CONF_load_key (const char * file, const char * pass)
Definition at line 86 of file ts_conf.c.
References BIO_free(), BIO_new_file(), key, NULL, PEM_read_bio_PrivateKey(), TS_F_TS_CONF_LOAD_KEY, TS_R_CANNOT_LOAD_KEY, and TSerr.
TS_CONF_set_accuracy()
int TS_CONF_set_accuracy (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 374 of file ts_conf.c.
TS_CONF_set_certs()
int TS_CONF_set_certs (CONF * conf, const char * section, const char * certs, TS_RESP_CTX * ctx)
Definition at line 211 of file ts_conf.c.
TS_CONF_set_clock_precision_digits()
int TS_CONF_set_clock_precision_digits (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 411 of file ts_conf.c.
TS_CONF_set_crypto_device()
int TS_CONF_set_crypto_device (CONF * conf, const char * section, const char * device)
Definition at line 143 of file ts_conf.c.
TS_CONF_set_def_policy()
int TS_CONF_set_def_policy (CONF * conf, const char * section, const char * policy, TS_RESP_CTX * ctx)
Definition at line 280 of file ts_conf.c.
TS_CONF_set_default_engine()
int TS_CONF_set_default_engine (const char * name)
Definition at line 160 of file ts_conf.c.
References e, and NULL.
TS_CONF_set_digests()
int TS_CONF_set_digests (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 336 of file ts_conf.c.
TS_CONF_set_ess_cert_id_chain()
int TS_CONF_set_ess_cert_id_chain (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 463 of file ts_conf.c.
TS_CONF_set_ordering()
int TS_CONF_set_ordering (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 453 of file ts_conf.c.
TS_CONF_set_policies()
int TS_CONF_set_policies (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 304 of file ts_conf.c.
TS_CONF_set_serial()
int TS_CONF_set_serial (CONF * conf, const char * section, TS_serial_cb cb, TS_RESP_CTX * ctx)
Definition at line 125 of file ts_conf.c.
TS_CONF_set_signer_cert()
int TS_CONF_set_signer_cert (CONF * conf, const char * section, const char * cert, TS_RESP_CTX * ctx)
Definition at line 187 of file ts_conf.c.
TS_CONF_set_signer_digest()
int TS_CONF_set_signer_digest (CONF * conf, const char * section, const char * md, TS_RESP_CTX * ctx)
Definition at line 256 of file ts_conf.c.
TS_CONF_set_signer_key()
int TS_CONF_set_signer_key (CONF * conf, const char * section, const char * key, const char * pass, TS_RESP_CTX * ctx)
Definition at line 233 of file ts_conf.c.
TS_CONF_set_tsa_name()
int TS_CONF_set_tsa_name (CONF * conf, const char * section, TS_RESP_CTX * ctx)
Definition at line 458 of file ts_conf.c.