crypto/ts/ts_rsp_print.c File Reference
ts_rsp_print.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/bn.h>
#include <openssl/x509v3.h>
#include <openssl/ts.h>
#include "ts_lcl.h"
Data Structures
struct status_map_st
Functions
int TS_RESP_print_bio (BIO *bio, TS_RESP *a)
int TS_STATUS_INFO_print_bio (BIO *bio, TS_STATUS_INFO *a)
int TS_TST_INFO_print_bio (BIO *bio, TS_TST_INFO *a)
Function Documentation
TS_RESP_print_bio()
int TS_RESP_print_bio (BIO * bio, TS_RESP * a)
Definition at line 28 of file ts_rsp_print.c.
References BIO_printf(), NULL, TS_STATUS_INFO_print_bio(), and TS_TST_INFO_print_bio().
TS_STATUS_INFO_print_bio()
int TS_STATUS_INFO_print_bio (BIO * bio, TS_STATUS_INFO * a)
Definition at line 42 of file ts_rsp_print.c.
References ASN1_INTEGER_get(), ASN1_STRING_print_ex(), BIO_printf(), BIO_puts(), NULL, OSSL_NELEM, TS_INFO_ADD_INFO_NOT_AVAILABLE, TS_INFO_BAD_ALG, TS_INFO_BAD_DATA_FORMAT, TS_INFO_BAD_REQUEST, TS_INFO_SYSTEM_FAILURE, TS_INFO_TIME_NOT_AVAILABLE, TS_INFO_UNACCEPTED_EXTENSION, and TS_INFO_UNACCEPTED_POLICY.
Referenced by TS_RESP_print_bio().
TS_TST_INFO_print_bio()
int TS_TST_INFO_print_bio (BIO * bio, TS_TST_INFO * a)
Definition at line 118 of file ts_rsp_print.c.
References ASN1_GENERALIZEDTIME_print(), ASN1_INTEGER_get(), BIO_printf(), BIO_write(), NULL, TS_ASN1_INTEGER_print_bio(), TS_MSG_IMPRINT_print_bio(), and TS_OBJ_print_bio().
Referenced by TS_RESP_print_bio().