crypto/ts/ts_rsp_utils.c File Reference
ts_rsp_utils.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/ts.h>
#include <openssl/pkcs7.h>
#include "ts_lcl.h"
Functions
int TS_RESP_set_status_info (TS_RESP *a, TS_STATUS_INFO *status_info)
TS_STATUS_INFO * TS_RESP_get_status_info (TS_RESP *a)
void TS_RESP_set_tst_info (TS_RESP *a, PKCS7 *p7, TS_TST_INFO *tst_info)
PKCS7 * TS_RESP_get_token (TS_RESP *a)
TS_TST_INFO * TS_RESP_get_tst_info (TS_RESP *a)
int TS_TST_INFO_set_version (TS_TST_INFO *a, long version)
long TS_TST_INFO_get_version (const TS_TST_INFO *a)
int TS_TST_INFO_set_policy_id (TS_TST_INFO *a, ASN1_OBJECT *policy)
ASN1_OBJECT * TS_TST_INFO_get_policy_id (TS_TST_INFO *a)
int TS_TST_INFO_set_msg_imprint (TS_TST_INFO *a, TS_MSG_IMPRINT *msg_imprint)
TS_MSG_IMPRINT * TS_TST_INFO_get_msg_imprint (TS_TST_INFO *a)
int TS_TST_INFO_set_serial (TS_TST_INFO *a, const ASN1_INTEGER *serial)
const ASN1_INTEGER * TS_TST_INFO_get_serial (const TS_TST_INFO *a)
int TS_TST_INFO_set_time (TS_TST_INFO *a, const ASN1_GENERALIZEDTIME *gtime)
const ASN1_GENERALIZEDTIME * TS_TST_INFO_get_time (const TS_TST_INFO *a)
int TS_TST_INFO_set_accuracy (TS_TST_INFO *a, TS_ACCURACY *accuracy)
TS_ACCURACY * TS_TST_INFO_get_accuracy (TS_TST_INFO *a)
int TS_ACCURACY_set_seconds (TS_ACCURACY *a, const ASN1_INTEGER *seconds)
const ASN1_INTEGER * TS_ACCURACY_get_seconds (const TS_ACCURACY *a)
int TS_ACCURACY_set_millis (TS_ACCURACY *a, const ASN1_INTEGER *millis)
const ASN1_INTEGER * TS_ACCURACY_get_millis (const TS_ACCURACY *a)
int TS_ACCURACY_set_micros (TS_ACCURACY *a, const ASN1_INTEGER *micros)
const ASN1_INTEGER * TS_ACCURACY_get_micros (const TS_ACCURACY *a)
int TS_TST_INFO_set_ordering (TS_TST_INFO *a, int ordering)
int TS_TST_INFO_get_ordering (const TS_TST_INFO *a)
int TS_TST_INFO_set_nonce (TS_TST_INFO *a, const ASN1_INTEGER *nonce)
const ASN1_INTEGER * TS_TST_INFO_get_nonce (const TS_TST_INFO *a)
int TS_TST_INFO_set_tsa (TS_TST_INFO *a, GENERAL_NAME *tsa)
GENERAL_NAME * TS_TST_INFO_get_tsa (TS_TST_INFO *a)
STACK_OF (X509_EXTENSION)
void TS_TST_INFO_ext_free (TS_TST_INFO *a)
int TS_TST_INFO_get_ext_count (TS_TST_INFO *a)
int TS_TST_INFO_get_ext_by_NID (TS_TST_INFO *a, int nid, int lastpos)
int TS_TST_INFO_get_ext_by_OBJ (TS_TST_INFO *a, const ASN1_OBJECT *obj, int lastpos)
int TS_TST_INFO_get_ext_by_critical (TS_TST_INFO *a, int crit, int lastpos)
X509_EXTENSION * TS_TST_INFO_get_ext (TS_TST_INFO *a, int loc)
X509_EXTENSION * TS_TST_INFO_delete_ext (TS_TST_INFO *a, int loc)
int TS_TST_INFO_add_ext (TS_TST_INFO *a, X509_EXTENSION *ex, int loc)
void * TS_TST_INFO_get_ext_d2i (TS_TST_INFO *a, int nid, int *crit, int *idx)
int TS_STATUS_INFO_set_status (TS_STATUS_INFO *a, int i)
const ASN1_INTEGER * TS_STATUS_INFO_get0_status (const TS_STATUS_INFO *a)
const STACK_OF (ASN1_UTF8STRING)
const ASN1_BIT_STRING * TS_STATUS_INFO_get0_failure_info (const TS_STATUS_INFO *a)
Function Documentation
STACK_OF() [1/2]
STACK_OF (X509_EXTENSION)
Definition at line 293 of file ts_rsp_utils.c.
STACK_OF() [2/2]
const STACK_OF (ASN1_UTF8STRING)
Definition at line 356 of file ts_rsp_utils.c.
TS_ACCURACY_get_micros()
const ASN1_INTEGER* TS_ACCURACY_get_micros (const TS_ACCURACY * a)
Definition at line 235 of file ts_rsp_utils.c.
TS_ACCURACY_get_millis()
const ASN1_INTEGER* TS_ACCURACY_get_millis (const TS_ACCURACY * a)
Definition at line 212 of file ts_rsp_utils.c.
TS_ACCURACY_get_seconds()
const ASN1_INTEGER* TS_ACCURACY_get_seconds (const TS_ACCURACY * a)
Definition at line 189 of file ts_rsp_utils.c.
TS_ACCURACY_set_micros()
int TS_ACCURACY_set_micros (TS_ACCURACY * a, const ASN1_INTEGER * micros)
Definition at line 217 of file ts_rsp_utils.c.
References ASN1_INTEGER_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_ACCURACY_SET_MICROS, and TSerr.
TS_ACCURACY_set_millis()
int TS_ACCURACY_set_millis (TS_ACCURACY * a, const ASN1_INTEGER * millis)
Definition at line 194 of file ts_rsp_utils.c.
References ASN1_INTEGER_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_ACCURACY_SET_MILLIS, and TSerr.
TS_ACCURACY_set_seconds()
int TS_ACCURACY_set_seconds (TS_ACCURACY * a, const ASN1_INTEGER * seconds)
Definition at line 173 of file ts_rsp_utils.c.
References ASN1_INTEGER_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_ACCURACY_SET_SECONDS, and TSerr.
TS_RESP_get_status_info()
TS_STATUS_INFO* TS_RESP_get_status_info (TS_RESP * a)
Definition at line 34 of file ts_rsp_utils.c.
TS_RESP_get_token()
PKCS7* TS_RESP_get_token (TS_RESP * a)
Definition at line 48 of file ts_rsp_utils.c.
TS_RESP_get_tst_info()
TS_TST_INFO* TS_RESP_get_tst_info (TS_RESP * a)
Definition at line 53 of file ts_rsp_utils.c.
TS_RESP_set_status_info()
int TS_RESP_set_status_info (TS_RESP * a, TS_STATUS_INFO * status_info)
Definition at line 17 of file ts_rsp_utils.c.
References ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_RESP_SET_STATUS_INFO, TS_STATUS_INFO_dup(), TS_STATUS_INFO_free(), and TSerr.
TS_RESP_set_tst_info()
void TS_RESP_set_tst_info (TS_RESP * a, PKCS7 * p7, TS_TST_INFO * tst_info)
Definition at line 40 of file ts_rsp_utils.c.
References TS_TST_INFO_free().
TS_STATUS_INFO_get0_failure_info()
const ASN1_BIT_STRING* TS_STATUS_INFO_get0_failure_info (const TS_STATUS_INFO * a)
Definition at line 362 of file ts_rsp_utils.c.
TS_STATUS_INFO_get0_status()
const ASN1_INTEGER* TS_STATUS_INFO_get0_status (const TS_STATUS_INFO * a)
Definition at line 351 of file ts_rsp_utils.c.
TS_STATUS_INFO_set_status()
int TS_STATUS_INFO_set_status (TS_STATUS_INFO * a, int i)
Definition at line 346 of file ts_rsp_utils.c.
References ASN1_INTEGER_set().
TS_TST_INFO_add_ext()
int TS_TST_INFO_add_ext (TS_TST_INFO * a, X509_EXTENSION * ex, int loc)
Definition at line 336 of file ts_rsp_utils.c.
References NULL.
TS_TST_INFO_delete_ext()
X509_EXTENSION* TS_TST_INFO_delete_ext (TS_TST_INFO * a, int loc)
Definition at line 331 of file ts_rsp_utils.c.
References X509v3_delete_ext().
TS_TST_INFO_ext_free()
void TS_TST_INFO_ext_free (TS_TST_INFO * a)
Definition at line 298 of file ts_rsp_utils.c.
References NULL.
TS_TST_INFO_get_accuracy()
TS_ACCURACY* TS_TST_INFO_get_accuracy (TS_TST_INFO * a)
Definition at line 168 of file ts_rsp_utils.c.
TS_TST_INFO_get_ext()
X509_EXTENSION* TS_TST_INFO_get_ext (TS_TST_INFO * a, int loc)
Definition at line 326 of file ts_rsp_utils.c.
References X509v3_get_ext().
TS_TST_INFO_get_ext_by_critical()
int TS_TST_INFO_get_ext_by_critical (TS_TST_INFO * a, int crit, int lastpos)
Definition at line 321 of file ts_rsp_utils.c.
References X509v3_get_ext_by_critical().
TS_TST_INFO_get_ext_by_NID()
int TS_TST_INFO_get_ext_by_NID (TS_TST_INFO * a, int nid, int lastpos)
Definition at line 311 of file ts_rsp_utils.c.
References X509v3_get_ext_by_NID().
TS_TST_INFO_get_ext_by_OBJ()
int TS_TST_INFO_get_ext_by_OBJ (TS_TST_INFO * a, const ASN1_OBJECT * obj, int lastpos)
Definition at line 316 of file ts_rsp_utils.c.
References X509v3_get_ext_by_OBJ().
TS_TST_INFO_get_ext_count()
int TS_TST_INFO_get_ext_count (TS_TST_INFO * a)
Definition at line 306 of file ts_rsp_utils.c.
References X509v3_get_ext_count().
TS_TST_INFO_get_ext_d2i()
void* TS_TST_INFO_get_ext_d2i (TS_TST_INFO * a, int nid, int * crit, int * idx)
Definition at line 341 of file ts_rsp_utils.c.
TS_TST_INFO_get_msg_imprint()
TS_MSG_IMPRINT* TS_TST_INFO_get_msg_imprint (TS_TST_INFO * a)
Definition at line 105 of file ts_rsp_utils.c.
TS_TST_INFO_get_nonce()
const ASN1_INTEGER* TS_TST_INFO_get_nonce (const TS_TST_INFO * a)
Definition at line 267 of file ts_rsp_utils.c.
TS_TST_INFO_get_ordering()
int TS_TST_INFO_get_ordering (const TS_TST_INFO * a)
Definition at line 246 of file ts_rsp_utils.c.
TS_TST_INFO_get_policy_id()
ASN1_OBJECT* TS_TST_INFO_get_policy_id (TS_TST_INFO * a)
Definition at line 84 of file ts_rsp_utils.c.
TS_TST_INFO_get_serial()
const ASN1_INTEGER* TS_TST_INFO_get_serial (const TS_TST_INFO * a)
Definition at line 126 of file ts_rsp_utils.c.
TS_TST_INFO_get_time()
const ASN1_GENERALIZEDTIME* TS_TST_INFO_get_time (const TS_TST_INFO * a)
Definition at line 147 of file ts_rsp_utils.c.
TS_TST_INFO_get_tsa()
GENERAL_NAME* TS_TST_INFO_get_tsa (TS_TST_INFO * a)
Definition at line 288 of file ts_rsp_utils.c.
TS_TST_INFO_get_version()
long TS_TST_INFO_get_version (const TS_TST_INFO * a)
Definition at line 63 of file ts_rsp_utils.c.
References ASN1_INTEGER_get().
TS_TST_INFO_set_accuracy()
int TS_TST_INFO_set_accuracy (TS_TST_INFO * a, TS_ACCURACY * accuracy)
Definition at line 152 of file ts_rsp_utils.c.
References ERR_R_MALLOC_FAILURE, NULL, TS_ACCURACY_dup(), TS_ACCURACY_free(), TS_F_TS_TST_INFO_SET_ACCURACY, and TSerr.
TS_TST_INFO_set_msg_imprint()
int TS_TST_INFO_set_msg_imprint (TS_TST_INFO * a, TS_MSG_IMPRINT * msg_imprint)
Definition at line 89 of file ts_rsp_utils.c.
References ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_TST_INFO_SET_MSG_IMPRINT, TS_MSG_IMPRINT_dup(), TS_MSG_IMPRINT_free(), and TSerr.
TS_TST_INFO_set_nonce()
int TS_TST_INFO_set_nonce (TS_TST_INFO * a, const ASN1_INTEGER * nonce)
Definition at line 251 of file ts_rsp_utils.c.
References ASN1_INTEGER_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_TST_INFO_SET_NONCE, and TSerr.
TS_TST_INFO_set_ordering()
int TS_TST_INFO_set_ordering (TS_TST_INFO * a, int ordering)
Definition at line 240 of file ts_rsp_utils.c.
TS_TST_INFO_set_policy_id()
int TS_TST_INFO_set_policy_id (TS_TST_INFO * a, ASN1_OBJECT * policy)
Definition at line 68 of file ts_rsp_utils.c.
References ASN1_OBJECT_free(), ERR_R_MALLOC_FAILURE, NULL, OBJ_dup(), TS_F_TS_TST_INFO_SET_POLICY_ID, and TSerr.
TS_TST_INFO_set_serial()
int TS_TST_INFO_set_serial (TS_TST_INFO * a, const ASN1_INTEGER * serial)
Definition at line 110 of file ts_rsp_utils.c.
References ASN1_INTEGER_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_TST_INFO_SET_SERIAL, and TSerr.
TS_TST_INFO_set_time()
int TS_TST_INFO_set_time (TS_TST_INFO * a, const ASN1_GENERALIZEDTIME * gtime)
Definition at line 131 of file ts_rsp_utils.c.
References ASN1_STRING_dup(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_TST_INFO_SET_TIME, and TSerr.
TS_TST_INFO_set_tsa()
int TS_TST_INFO_set_tsa (TS_TST_INFO * a, GENERAL_NAME * tsa)
Definition at line 272 of file ts_rsp_utils.c.
References ERR_R_MALLOC_FAILURE, GENERAL_NAME_dup(), NULL, TS_F_TS_TST_INFO_SET_TSA, and TSerr.
TS_TST_INFO_set_version()
int TS_TST_INFO_set_version (TS_TST_INFO * a, long version)
Definition at line 58 of file ts_rsp_utils.c.
References ASN1_INTEGER_set().