crypto/ts/ts_rsp_sign.c File Reference
ts_rsp_sign.c File Reference
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/ts.h>
#include <openssl/pkcs7.h>
#include "ts_lcl.h"
Macros
#define TS_RESP_CTX_accuracy_free(ctx)
Functions
TS_RESP_CTX * TS_RESP_CTX_new ()
void TS_RESP_CTX_free (TS_RESP_CTX *ctx)
int TS_RESP_CTX_set_signer_cert (TS_RESP_CTX *ctx, X509 *signer)
int TS_RESP_CTX_set_signer_key (TS_RESP_CTX *ctx, EVP_PKEY *key)
int TS_RESP_CTX_set_signer_digest (TS_RESP_CTX *ctx, const EVP_MD *md)
int TS_RESP_CTX_set_def_policy (TS_RESP_CTX *ctx, const ASN1_OBJECT *def_policy)
int TS_RESP_CTX_set_certs (TS_RESP_CTX *ctx, STACK_OF(X509) *certs)
int TS_RESP_CTX_add_policy (TS_RESP_CTX *ctx, const ASN1_OBJECT *policy)
int TS_RESP_CTX_add_md (TS_RESP_CTX *ctx, const EVP_MD *md)
int TS_RESP_CTX_set_accuracy (TS_RESP_CTX *ctx, int secs, int millis, int micros)
void TS_RESP_CTX_add_flags (TS_RESP_CTX *ctx, int flags)
void TS_RESP_CTX_set_serial_cb (TS_RESP_CTX *ctx, TS_serial_cb cb, void *data)
void TS_RESP_CTX_set_time_cb (TS_RESP_CTX *ctx, TS_time_cb cb, void *data)
void TS_RESP_CTX_set_extension_cb (TS_RESP_CTX *ctx, TS_extension_cb cb, void *data)
int TS_RESP_CTX_set_status_info (TS_RESP_CTX *ctx, int status, const char *text)
int TS_RESP_CTX_set_status_info_cond (TS_RESP_CTX *ctx, int status, const char *text)
int TS_RESP_CTX_add_failure_info (TS_RESP_CTX *ctx, int failure)
TS_REQ * TS_RESP_CTX_get_request (TS_RESP_CTX *ctx)
TS_TST_INFO * TS_RESP_CTX_get_tst_info (TS_RESP_CTX *ctx)
int TS_RESP_CTX_set_clock_precision_digits (TS_RESP_CTX *ctx, unsigned precision)
TS_RESP * TS_RESP_create_response (TS_RESP_CTX *ctx, BIO *req_bio)
Macro Definition Documentation
TS_RESP_CTX_accuracy_free
#define TS_RESP_CTX_accuracy_free (ctx)
Value:
ASN1_INTEGER_free(ctx->seconds);        \
        ctx->seconds = NULL;                    \
        ASN1_INTEGER_free(ctx->millis);         \
        ctx->millis = NULL;                     \
        ASN1_INTEGER_free(ctx->micros);         \
        ctx->micros = NULL;
Definition at line 235 of file ts_rsp_sign.c.
Referenced by TS_RESP_CTX_set_accuracy().
Function Documentation
TS_RESP_create_response()
TS_RESP* TS_RESP_create_response (TS_RESP_CTX * ctx, BIO * req_bio)
Definition at line 371 of file ts_rsp_sign.c.
TS_RESP_CTX_add_failure_info()
int TS_RESP_CTX_add_failure_info (TS_RESP_CTX * ctx, int failure)
Definition at line 337 of file ts_rsp_sign.c.
References ASN1_BIT_STRING_set_bit(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_RESP_CTX_ADD_FAILURE_INFO, and TSerr.
TS_RESP_CTX_add_flags()
void TS_RESP_CTX_add_flags (TS_RESP_CTX * ctx, int flags)
Definition at line 268 of file ts_rsp_sign.c.
References flags.
TS_RESP_CTX_add_md()
int TS_RESP_CTX_add_md (TS_RESP_CTX * ctx, const EVP_MD * md)
Definition at line 221 of file ts_rsp_sign.c.
TS_RESP_CTX_add_policy()
int TS_RESP_CTX_add_policy (TS_RESP_CTX * ctx, const ASN1_OBJECT * policy)
Definition at line 202 of file ts_rsp_sign.c.
References ASN1_OBJECT_free(), ERR_R_MALLOC_FAILURE, NULL, OBJ_dup(), TS_F_TS_RESP_CTX_ADD_POLICY, and TSerr.
TS_RESP_CTX_free()
void TS_RESP_CTX_free (TS_RESP_CTX * ctx)
Definition at line 131 of file ts_rsp_sign.c.
References ASN1_OBJECT_free(), EVP_PKEY_free(), and OPENSSL_free.
TS_RESP_CTX_get_request()
TS_REQ* TS_RESP_CTX_get_request (TS_RESP_CTX * ctx)
Definition at line 351 of file ts_rsp_sign.c.
TS_RESP_CTX_get_tst_info()
TS_TST_INFO* TS_RESP_CTX_get_tst_info (TS_RESP_CTX * ctx)
Definition at line 356 of file ts_rsp_sign.c.
TS_RESP_CTX_new()
TS_RESP_CTX* TS_RESP_CTX_new (void)
Definition at line 113 of file ts_rsp_sign.c.
References ctx, ERR_R_MALLOC_FAILURE, EVP_sha256(), NULL, OPENSSL_zalloc, TS_F_TS_RESP_CTX_NEW, and TSerr.
TS_RESP_CTX_set_accuracy()
int TS_RESP_CTX_set_accuracy (TS_RESP_CTX * ctx, int secs, int millis, int micros)
Definition at line 243 of file ts_rsp_sign.c.
References ASN1_INTEGER_set(), ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_RESP_CTX_SET_ACCURACY, TS_RESP_CTX_accuracy_free, and TSerr.
TS_RESP_CTX_set_certs()
int TS_RESP_CTX_set_certs (TS_RESP_CTX * ctx, STACK_OF(X509) * certs)
Definition at line 187 of file ts_rsp_sign.c.
References ERR_R_MALLOC_FAILURE, NULL, TS_F_TS_RESP_CTX_SET_CERTS, and TSerr.
TS_RESP_CTX_set_clock_precision_digits()
int TS_RESP_CTX_set_clock_precision_digits (TS_RESP_CTX * ctx, unsigned precision)
Definition at line 361 of file ts_rsp_sign.c.
References TS_MAX_CLOCK_PRECISION_DIGITS.
TS_RESP_CTX_set_def_policy()
int TS_RESP_CTX_set_def_policy (TS_RESP_CTX * ctx, const ASN1_OBJECT * def_policy)
Definition at line 176 of file ts_rsp_sign.c.
References ASN1_OBJECT_free(), ERR_R_MALLOC_FAILURE, NULL, OBJ_dup(), TS_F_TS_RESP_CTX_SET_DEF_POLICY, and TSerr.
TS_RESP_CTX_set_extension_cb()
void TS_RESP_CTX_set_extension_cb (TS_RESP_CTX * ctx, TS_extension_cb cb, void * data)
Definition at line 285 of file ts_rsp_sign.c.
References cb, and data.
TS_RESP_CTX_set_serial_cb()
void TS_RESP_CTX_set_serial_cb (TS_RESP_CTX * ctx, TS_serial_cb cb, void * data)
Definition at line 273 of file ts_rsp_sign.c.
References cb, and data.
TS_RESP_CTX_set_signer_cert()
int TS_RESP_CTX_set_signer_cert (TS_RESP_CTX * ctx, X509 * signer)
Definition at line 148 of file ts_rsp_sign.c.
References TS_F_TS_RESP_CTX_SET_SIGNER_CERT, TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE, TSerr, X509_check_purpose(), X509_PURPOSE_TIMESTAMP_SIGN, and X509_up_ref().
TS_RESP_CTX_set_signer_digest()
int TS_RESP_CTX_set_signer_digest (TS_RESP_CTX * ctx, const EVP_MD * md)
Definition at line 170 of file ts_rsp_sign.c.
TS_RESP_CTX_set_signer_key()
int TS_RESP_CTX_set_signer_key (TS_RESP_CTX * ctx, EVP_PKEY * key)
Definition at line 161 of file ts_rsp_sign.c.
References EVP_PKEY_free(), EVP_PKEY_up_ref(), and key.
TS_RESP_CTX_set_status_info()
int TS_RESP_CTX_set_status_info (TS_RESP_CTX * ctx, int status, const char * text)
Definition at line 292 of file ts_rsp_sign.c.
References NULL.
TS_RESP_CTX_set_status_info_cond()
int TS_RESP_CTX_set_status_info_cond (TS_RESP_CTX * ctx, int status, const char * text)
Definition at line 325 of file ts_rsp_sign.c.
TS_RESP_CTX_set_time_cb()
void TS_RESP_CTX_set_time_cb (TS_RESP_CTX * ctx, TS_time_cb cb, void * data)
Definition at line 279 of file ts_rsp_sign.c.
References cb, and data.