crypto/ts/ts_lib.c File Reference
ts_lib.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/objects.h>
#include <openssl/bn.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/ts.h>
#include "ts_lcl.h"
Functions
int TS_ASN1_INTEGER_print_bio (BIO *bio, const ASN1_INTEGER *num)
int TS_OBJ_print_bio (BIO *bio, const ASN1_OBJECT *obj)
int TS_ext_print_bio (BIO *bio, const STACK_OF(X509_EXTENSION) *extensions)
int TS_X509_ALGOR_print_bio (BIO *bio, const X509_ALGOR *alg)
int TS_MSG_IMPRINT_print_bio (BIO *bio, TS_MSG_IMPRINT *a)
Function Documentation
TS_ASN1_INTEGER_print_bio()
int TS_ASN1_INTEGER_print_bio (BIO * bio, const ASN1_INTEGER * num)
Definition at line 19 of file ts_lib.c.
References ASN1_INTEGER_to_BN(), BIO_write(), BN_bn2hex(), BN_free(), BN_new(), NULL, and OPENSSL_free.
Referenced by TS_REQ_print_bio(), and TS_TST_INFO_print_bio().
TS_ext_print_bio()
int TS_ext_print_bio (BIO * bio, const STACK_OF(X509_EXTENSION) * extensions)
Definition at line 49 of file ts_lib.c.
References ASN1_STRING_print(), BIO_printf(), BIO_write(), ex, i2a_ASN1_OBJECT(), obj, X509_EXTENSION_get_critical(), X509_EXTENSION_get_data(), X509_EXTENSION_get_object(), X509V3_EXT_print(), X509v3_get_ext(), and X509v3_get_ext_count().
Referenced by TS_REQ_print_bio().
TS_MSG_IMPRINT_print_bio()
int TS_MSG_IMPRINT_print_bio (BIO * bio, TS_MSG_IMPRINT * a)
Definition at line 81 of file ts_lib.c.
Referenced by TS_REQ_print_bio(), and TS_TST_INFO_print_bio().
TS_OBJ_print_bio()
int TS_OBJ_print_bio (BIO * bio, const ASN1_OBJECT * obj)
Definition at line 39 of file ts_lib.c.
References BIO_printf(), and OBJ_obj2txt().
Referenced by TS_REQ_print_bio(), and TS_TST_INFO_print_bio().
TS_X509_ALGOR_print_bio()
int TS_X509_ALGOR_print_bio (BIO * bio, const X509_ALGOR * alg)
Definition at line 74 of file ts_lib.c.
References BIO_printf(), NID_undef, OBJ_nid2ln(), and OBJ_obj2nid().