include/openssl/txt_db.h File Reference
txt_db.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/bio.h>
#include <openssl/stack.h>
#include <openssl/lhash.h>
Data Structures
struct TXT_DB
Macros
#define DB_ERROR_OK 0
#define DB_ERROR_MALLOC 1
#define DB_ERROR_INDEX_CLASH 2
#define DB_ERROR_INDEX_OUT_OF_RANGE 3
#define DB_ERROR_NO_INDEX 4
#define DB_ERROR_INSERT_INDEX_CLASH 5
#define DB_ERROR_WRONG_NUM_FIELDS 6
Typedefs
typedef OPENSSL_STRING * OPENSSL_PSTRING
Functions
TXT_DB * TXT_DB_read (BIO *in, int num)
long TXT_DB_write (BIO *out, TXT_DB *db)
int TXT_DB_create_index (TXT_DB *db, int field, int(*qual)(OPENSSL_STRING *), OPENSSL_LH_HASHFUNC hash, OPENSSL_LH_COMPFUNC cmp)
void TXT_DB_free (TXT_DB *db)
OPENSSL_STRING * TXT_DB_get_by_index (TXT_DB *db, int idx, OPENSSL_STRING *value)
int TXT_DB_insert (TXT_DB *db, OPENSSL_STRING *value)
Macro Definition Documentation
DB_ERROR_INDEX_CLASH
#define DB_ERROR_INDEX_CLASH 2
Definition at line 20 of file txt_db.h.
Referenced by TXT_DB_insert().
DB_ERROR_INDEX_OUT_OF_RANGE
#define DB_ERROR_INDEX_OUT_OF_RANGE 3
Definition at line 21 of file txt_db.h.
DB_ERROR_INSERT_INDEX_CLASH
#define DB_ERROR_INSERT_INDEX_CLASH 5
Definition at line 23 of file txt_db.h.
DB_ERROR_MALLOC
#define DB_ERROR_MALLOC 1
Definition at line 19 of file txt_db.h.
Referenced by TXT_DB_insert().
DB_ERROR_NO_INDEX
#define DB_ERROR_NO_INDEX 4
Definition at line 22 of file txt_db.h.
DB_ERROR_OK
#define DB_ERROR_OK 0
Definition at line 18 of file txt_db.h.
DB_ERROR_WRONG_NUM_FIELDS
#define DB_ERROR_WRONG_NUM_FIELDS 6
Definition at line 24 of file txt_db.h.
Typedef Documentation
OPENSSL_PSTRING
typedef OPENSSL_STRING* OPENSSL_PSTRING
Definition at line 30 of file txt_db.h.
Function Documentation
TXT_DB_create_index()
int TXT_DB_create_index (TXT_DB * db, int field, int(*)(OPENSSL_STRING *) qual, OPENSSL_LH_HASHFUNC hash, OPENSSL_LH_COMPFUNC cmp)
Definition at line 147 of file txt_db.c.
References LHASH_OF.
Referenced by index_index().
TXT_DB_free()
void TXT_DB_free (TXT_DB * db)
Definition at line 265 of file txt_db.c.
References max, NULL, TXT_DB::num_fields, OPENSSL_free, and TXT_DB::qual.
Referenced by free_index().
TXT_DB_get_by_index()
OPENSSL_STRING* TXT_DB_get_by_index (TXT_DB * db, int idx, OPENSSL_STRING * value)
Definition at line 127 of file txt_db.c.
TXT_DB_insert()
int TXT_DB_insert (TXT_DB * db, OPENSSL_STRING * value)
Definition at line 229 of file txt_db.c.
References TXT_DB::arg1, TXT_DB::arg_row, DB_ERROR_INDEX_CLASH, DB_ERROR_MALLOC, TXT_DB::error, NULL, TXT_DB::num_fields, and TXT_DB::qual.
TXT_DB_read()
TXT_DB* TXT_DB_read (BIO * in, int num)
Definition at line 20 of file txt_db.c.
Referenced by SRP_VBASE_init().
TXT_DB_write()
long TXT_DB_write (BIO * out, TXT_DB * db)
Definition at line 182 of file txt_db.c.