crypto/txt_db/txt_db.c File Reference
txt_db.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "internal/cryptlib.h"
#include <openssl/buffer.h>
#include <openssl/txt_db.h>
Macros
#define BUFSIZE 512
Functions
TXT_DB * TXT_DB_read (BIO *in, int num)
OPENSSL_STRING * TXT_DB_get_by_index (TXT_DB *db, int idx, OPENSSL_STRING *value)
int TXT_DB_create_index (TXT_DB *db, int field, int(*qual)(OPENSSL_STRING *), OPENSSL_LH_HASHFUNC hash, OPENSSL_LH_COMPFUNC cmp)
long TXT_DB_write (BIO *out, TXT_DB *db)
int TXT_DB_insert (TXT_DB *db, OPENSSL_STRING *row)
void TXT_DB_free (TXT_DB *db)
Macro Definition Documentation
BUFSIZE
#define BUFSIZE 512
Definition at line 18 of file txt_db.c.
Function Documentation
TXT_DB_create_index()
int TXT_DB_create_index (TXT_DB * db, int field, int(*)(OPENSSL_STRING *) qual, OPENSSL_LH_HASHFUNC hash, OPENSSL_LH_COMPFUNC cmp)
Definition at line 147 of file txt_db.c.
References LHASH_OF.
Referenced by index_index().
TXT_DB_free()
void TXT_DB_free (TXT_DB * db)
Definition at line 265 of file txt_db.c.
References max, NULL, TXT_DB::num_fields, OPENSSL_free, and TXT_DB::qual.
Referenced by free_index().
TXT_DB_get_by_index()
OPENSSL_STRING* TXT_DB_get_by_index (TXT_DB * db, int idx, OPENSSL_STRING * value)
Definition at line 127 of file txt_db.c.
TXT_DB_insert()
int TXT_DB_insert (TXT_DB * db, OPENSSL_STRING * row)
Definition at line 229 of file txt_db.c.
References TXT_DB::arg1, TXT_DB::arg_row, DB_ERROR_INDEX_CLASH, DB_ERROR_MALLOC, TXT_DB::error, NULL, TXT_DB::num_fields, and TXT_DB::qual.
TXT_DB_read()
TXT_DB* TXT_DB_read (BIO * in, int num)
Definition at line 20 of file txt_db.c.
Referenced by SRP_VBASE_init().
TXT_DB_write()
long TXT_DB_write (BIO * out, TXT_DB * db)
Definition at line 182 of file txt_db.c.