include/openssl/ui.h File Reference
ui.h File Reference
#include <openssl/opensslconf.h>
#include <openssl/crypto.h>
#include <openssl/safestack.h>
#include <openssl/pem.h>
#include <openssl/ossl_typ.h>
Macros
#define UI_INPUT_FLAG_ECHO 0x01
#define UI_INPUT_FLAG_DEFAULT_PWD 0x02
#define UI_INPUT_FLAG_USER_BASE 16
#define UI_CTRL_PRINT_ERRORS 1
#define UI_CTRL_IS_REDOABLE 2
#define UI_set_app_data(s, arg) UI_set_ex_data(s,0,arg)
#define UI_get_app_data(s) UI_get_ex_data(s,0)
#define UI_get_ex_new_index(l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_UI, l, p, newf, dupf, freef)
#define UI_F_CLOSE_CONSOLE 115
#define UI_F_ECHO_CONSOLE 116
#define UI_F_GENERAL_ALLOCATE_BOOLEAN 108
#define UI_F_GENERAL_ALLOCATE_PROMPT 109
#define UI_F_NOECHO_CONSOLE 117
#define UI_F_OPEN_CONSOLE 114
#define UI_F_UI_CREATE_METHOD 112
#define UI_F_UI_CTRL 111
#define UI_F_UI_DUP_ERROR_STRING 101
#define UI_F_UI_DUP_INFO_STRING 102
#define UI_F_UI_DUP_INPUT_BOOLEAN 110
#define UI_F_UI_DUP_INPUT_STRING 103
#define UI_F_UI_DUP_VERIFY_STRING 106
#define UI_F_UI_GET0_RESULT 107
#define UI_F_UI_NEW_METHOD 104
#define UI_F_UI_PROCESS 113
#define UI_F_UI_SET_RESULT 105
#define UI_R_COMMON_OK_AND_CANCEL_CHARACTERS 104
#define UI_R_INDEX_TOO_LARGE 102
#define UI_R_INDEX_TOO_SMALL 103
#define UI_R_NO_RESULT_BUFFER 105
#define UI_R_PROCESSING_ERROR 107
#define UI_R_RESULT_TOO_LARGE 100
#define UI_R_RESULT_TOO_SMALL 101
#define UI_R_SYSASSIGN_ERROR 109
#define UI_R_SYSDASSGN_ERROR 110
#define UI_R_SYSQIOW_ERROR 111
#define UI_R_UNKNOWN_CONTROL_COMMAND 106
#define UI_R_UNKNOWN_TTYGET_ERRNO_VALUE 108
Enumerations
enum UI_string_types {
UIT_NONE = 0, UIT_PROMPT, UIT_VERIFY, UIT_BOOLEAN,
UIT_INFO, UIT_ERROR
}
Functions
UI * UI_new (void)
UI * UI_new_method (const UI_METHOD *method)
void UI_free (UI *ui)
int UI_add_input_string (UI *ui, const char *prompt, int flags, char *result_buf, int minsize, int maxsize)
int UI_dup_input_string (UI *ui, const char *prompt, int flags, char *result_buf, int minsize, int maxsize)
int UI_add_verify_string (UI *ui, const char *prompt, int flags, char *result_buf, int minsize, int maxsize, const char *test_buf)
int UI_dup_verify_string (UI *ui, const char *prompt, int flags, char *result_buf, int minsize, int maxsize, const char *test_buf)
int UI_add_input_boolean (UI *ui, const char *prompt, const char *action_desc, const char *ok_chars, const char *cancel_chars, int flags, char *result_buf)
int UI_dup_input_boolean (UI *ui, const char *prompt, const char *action_desc, const char *ok_chars, const char *cancel_chars, int flags, char *result_buf)
int UI_add_info_string (UI *ui, const char *text)
int UI_dup_info_string (UI *ui, const char *text)
int UI_add_error_string (UI *ui, const char *text)
int UI_dup_error_string (UI *ui, const char *text)
char * UI_construct_prompt (UI *ui_method, const char *object_desc, const char *object_name)
void * UI_add_user_data (UI *ui, void *user_data)
void * UI_get0_user_data (UI *ui)
const char * UI_get0_result (UI *ui, int i)
int UI_process (UI *ui)
int UI_ctrl (UI *ui, int cmd, long i, void *p, void(*f)(void))
int UI_set_ex_data (UI *r, int idx, void *arg)
void * UI_get_ex_data (UI *r, int idx)
void UI_set_default_method (const UI_METHOD *meth)
const UI_METHOD * UI_get_default_method (void)
const UI_METHOD * UI_get_method (UI *ui)
const UI_METHOD * UI_set_method (UI *ui, const UI_METHOD *meth)
UI_METHOD * UI_OpenSSL (void)
UI_METHOD * UI_create_method (const char *name)
void UI_destroy_method (UI_METHOD *ui_method)
int UI_method_set_opener (UI_METHOD *method, int(*opener)(UI *ui))
int UI_method_set_writer (UI_METHOD *method, int(*writer)(UI *ui, UI_STRING *uis))
int UI_method_set_flusher (UI_METHOD *method, int(*flusher)(UI *ui))
int UI_method_set_reader (UI_METHOD *method, int(*reader)(UI *ui, UI_STRING *uis))
int UI_method_set_closer (UI_METHOD *method, int(*closer)(UI *ui))
int UI_method_set_prompt_constructor (UI_METHOD *method, char *(*prompt_constructor)(UI *ui, const char *object_desc, const char *object_name))
int UI_method_set_ex_data (UI_METHOD *method, int idx, void *data)
const void * UI_method_get_ex_data (const UI_METHOD *method, int idx)
enum UI_string_types UI_get_string_type (UI_STRING *uis)
int UI_get_input_flags (UI_STRING *uis)
const char * UI_get0_output_string (UI_STRING *uis)
const char * UI_get0_action_string (UI_STRING *uis)
const char * UI_get0_result_string (UI_STRING *uis)
const char * UI_get0_test_string (UI_STRING *uis)
int UI_get_result_minsize (UI_STRING *uis)
int UI_get_result_maxsize (UI_STRING *uis)
int UI_set_result (UI *ui, UI_STRING *uis, const char *result)
int UI_UTIL_read_pw_string (char *buf, int length, const char *prompt, int verify)
int UI_UTIL_read_pw (char *buf, char *buff, int size, const char *prompt, int verify)
UI_METHOD * UI_UTIL_wrap_read_pem_callback (pem_password_cb *cb, int rwflag)
int ERR_load_UI_strings (void)
Variables
int(*)(UI *) UI_method_get_opener (const UI_METHOD *method)
int(*)(UI *, UI_STRING *) UI_method_get_writer (const UI_METHOD *method)
int(*)(UI *) UI_method_get_flusher (const UI_METHOD *method)
int(*)(UI *, UI_STRING *) UI_method_get_reader (const UI_METHOD *method)
int(*)(UI *) UI_method_get_closer (const UI_METHOD *method)
char *(*)(UI *, const char *, const char *) UI_method_get_prompt_constructor (const UI_METHOD *method)
Macro Definition Documentation
UI_CTRL_IS_REDOABLE
#define UI_CTRL_IS_REDOABLE 2
Definition at line 189 of file ui.h.
Referenced by UI_ctrl().
UI_CTRL_PRINT_ERRORS
#define UI_CTRL_PRINT_ERRORS 1
Definition at line 183 of file ui.h.
Referenced by UI_ctrl().
UI_F_CLOSE_CONSOLE
#define UI_F_CLOSE_CONSOLE 115
Definition at line 345 of file ui.h.
UI_F_ECHO_CONSOLE
#define UI_F_ECHO_CONSOLE 116
Definition at line 346 of file ui.h.
UI_F_GENERAL_ALLOCATE_BOOLEAN
#define UI_F_GENERAL_ALLOCATE_BOOLEAN 108
Definition at line 347 of file ui.h.
UI_F_GENERAL_ALLOCATE_PROMPT
#define UI_F_GENERAL_ALLOCATE_PROMPT 109
Definition at line 348 of file ui.h.
UI_F_NOECHO_CONSOLE
#define UI_F_NOECHO_CONSOLE 117
Definition at line 349 of file ui.h.
UI_F_OPEN_CONSOLE
#define UI_F_OPEN_CONSOLE 114
Definition at line 350 of file ui.h.
UI_F_UI_CREATE_METHOD
#define UI_F_UI_CREATE_METHOD 112
Definition at line 351 of file ui.h.
UI_F_UI_CTRL
#define UI_F_UI_CTRL 111
Definition at line 352 of file ui.h.
Referenced by UI_ctrl().
UI_F_UI_DUP_ERROR_STRING
#define UI_F_UI_DUP_ERROR_STRING 101
Definition at line 353 of file ui.h.
Referenced by UI_dup_error_string().
UI_F_UI_DUP_INFO_STRING
#define UI_F_UI_DUP_INFO_STRING 102
Definition at line 354 of file ui.h.
Referenced by UI_dup_info_string().
UI_F_UI_DUP_INPUT_BOOLEAN
#define UI_F_UI_DUP_INPUT_BOOLEAN 110
Definition at line 355 of file ui.h.
Referenced by UI_dup_input_boolean().
UI_F_UI_DUP_INPUT_STRING
#define UI_F_UI_DUP_INPUT_STRING 103
Definition at line 356 of file ui.h.
Referenced by UI_dup_input_string().
UI_F_UI_DUP_VERIFY_STRING
#define UI_F_UI_DUP_VERIFY_STRING 106
Definition at line 357 of file ui.h.
Referenced by UI_dup_verify_string().
UI_F_UI_GET0_RESULT
#define UI_F_UI_GET0_RESULT 107
Definition at line 358 of file ui.h.
Referenced by UI_get0_result().
UI_F_UI_NEW_METHOD
#define UI_F_UI_NEW_METHOD 104
Definition at line 359 of file ui.h.
UI_F_UI_PROCESS
#define UI_F_UI_PROCESS 113
Definition at line 360 of file ui.h.
UI_F_UI_SET_RESULT
#define UI_F_UI_SET_RESULT 105
Definition at line 361 of file ui.h.
Referenced by UI_set_result().
UI_get_app_data
#define UI_get_app_data (s) UI_get_ex_data(s,0)
Definition at line 193 of file ui.h.
UI_get_ex_new_index
#define UI_get_ex_new_index (l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_UI, l, p, newf, dupf, freef)
Definition at line 195 of file ui.h.
UI_INPUT_FLAG_DEFAULT_PWD
#define UI_INPUT_FLAG_DEFAULT_PWD 0x02
Definition at line 114 of file ui.h.
UI_INPUT_FLAG_ECHO
#define UI_INPUT_FLAG_ECHO 0x01
Definition at line 106 of file ui.h.
UI_INPUT_FLAG_USER_BASE
#define UI_INPUT_FLAG_USER_BASE 16
Definition at line 126 of file ui.h.
UI_R_COMMON_OK_AND_CANCEL_CHARACTERS
#define UI_R_COMMON_OK_AND_CANCEL_CHARACTERS 104
Definition at line 364 of file ui.h.
UI_R_INDEX_TOO_LARGE
#define UI_R_INDEX_TOO_LARGE 102
Definition at line 365 of file ui.h.
Referenced by UI_get0_result().
UI_R_INDEX_TOO_SMALL
#define UI_R_INDEX_TOO_SMALL 103
Definition at line 366 of file ui.h.
Referenced by UI_get0_result().
UI_R_NO_RESULT_BUFFER
#define UI_R_NO_RESULT_BUFFER 105
Definition at line 367 of file ui.h.
Referenced by UI_set_result().
UI_R_PROCESSING_ERROR
#define UI_R_PROCESSING_ERROR 107
Definition at line 368 of file ui.h.
UI_R_RESULT_TOO_LARGE
#define UI_R_RESULT_TOO_LARGE 100
Definition at line 369 of file ui.h.
Referenced by UI_set_result().
UI_R_RESULT_TOO_SMALL
#define UI_R_RESULT_TOO_SMALL 101
Definition at line 370 of file ui.h.
Referenced by UI_set_result().
UI_R_SYSASSIGN_ERROR
#define UI_R_SYSASSIGN_ERROR 109
Definition at line 371 of file ui.h.
UI_R_SYSDASSGN_ERROR
#define UI_R_SYSDASSGN_ERROR 110
Definition at line 372 of file ui.h.
UI_R_SYSQIOW_ERROR
#define UI_R_SYSQIOW_ERROR 111
Definition at line 373 of file ui.h.
UI_R_UNKNOWN_CONTROL_COMMAND
#define UI_R_UNKNOWN_CONTROL_COMMAND 106
Definition at line 374 of file ui.h.
Referenced by UI_ctrl().
UI_R_UNKNOWN_TTYGET_ERRNO_VALUE
#define UI_R_UNKNOWN_TTYGET_ERRNO_VALUE 108
Definition at line 375 of file ui.h.
UI_set_app_data
#define UI_set_app_data (s, arg) UI_set_ex_data(s,0,arg)
Definition at line 192 of file ui.h.
Enumeration Type Documentation
UI_string_types
enum UI_string_types
Enumerator
UIT_NONE
UIT_PROMPT
UIT_VERIFY
UIT_BOOLEAN
UIT_INFO
UIT_ERROR
Definition at line 263 of file ui.h.
Function Documentation
ERR_load_UI_strings()
int ERR_load_UI_strings (void)
Definition at line 62 of file ui_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
UI_add_error_string()
int UI_add_error_string (UI * ui, const char * text)
Definition at line 334 of file ui_lib.c.
UI_add_info_string()
int UI_add_info_string (UI * ui, const char * text)
Definition at line 312 of file ui_lib.c.
UI_add_input_boolean()
int UI_add_input_boolean (UI * ui, const char * prompt, const char * action_desc, const char * ok_chars, const char * cancel_chars, int flags, char * result_buf)
Definition at line 251 of file ui_lib.c.
UI_add_input_string()
int UI_add_input_string (UI * ui, const char * prompt, int flags, char * result_buf, int minsize, int maxsize)
Definition at line 196 of file ui_lib.c.
UI_add_user_data()
void* UI_add_user_data (UI * ui, void * user_data)
Definition at line 389 of file ui_lib.c.
UI_add_verify_string()
int UI_add_verify_string (UI * ui, const char * prompt, int flags, char * result_buf, int minsize, int maxsize, const char * test_buf)
Definition at line 223 of file ui_lib.c.
UI_construct_prompt()
char* UI_construct_prompt (UI * ui_method, const char * object_desc, const char * object_name)
Definition at line 355 of file ui_lib.c.
References len, NULL, OPENSSL_malloc, OPENSSL_strlcat(), and OPENSSL_strlcpy().
UI_create_method()
UI_METHOD* UI_create_method (const char * name)
Definition at line 562 of file ui_lib.c.
UI_ctrl()
int UI_ctrl (UI * ui, int cmd, long i, void * p, void(*)(void) f)
Definition at line 503 of file ui_lib.c.
References ERR_R_PASSED_NULL_PARAMETER, NULL, UI_CTRL_IS_REDOABLE, UI_CTRL_PRINT_ERRORS, UI_F_UI_CTRL, UI_FLAG_PRINT_ERRORS, UI_FLAG_REDOABLE, UI_R_UNKNOWN_CONTROL_COMMAND, and UIerr.
UI_destroy_method()
void UI_destroy_method (UI_METHOD * ui_method)
Definition at line 584 of file ui_lib.c.
UI_dup_error_string()
int UI_dup_error_string (UI * ui, const char * text)
Definition at line 340 of file ui_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_strdup, UI_F_UI_DUP_ERROR_STRING, and UIerr.
UI_dup_info_string()
int UI_dup_info_string (UI * ui, const char * text)
Definition at line 318 of file ui_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_strdup, UI_F_UI_DUP_INFO_STRING, and UIerr.
UI_dup_input_boolean()
int UI_dup_input_boolean (UI * ui, const char * prompt, const char * action_desc, const char * ok_chars, const char * cancel_chars, int flags, char * result_buf)
Definition at line 260 of file ui_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_strdup, UI_F_UI_DUP_INPUT_BOOLEAN, and UIerr.
UI_dup_input_string()
int UI_dup_input_string (UI * ui, const char * prompt, int flags, char * result_buf, int minsize, int maxsize)
Definition at line 205 of file ui_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_strdup, UI_F_UI_DUP_INPUT_STRING, and UIerr.
UI_dup_verify_string()
int UI_dup_verify_string (UI * ui, const char * prompt, int flags, char * result_buf, int minsize, int maxsize, const char * test_buf)
Definition at line 232 of file ui_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_strdup, UI_F_UI_DUP_VERIFY_STRING, and UIerr.
UI_free()
void UI_free (UI * ui)
Definition at line 74 of file ui_lib.c.
References NULL.
UI_get0_action_string()
const char* UI_get0_action_string (UI_STRING * uis)
Definition at line 724 of file ui_lib.c.
References NULL, UIT_BOOLEAN, UIT_ERROR, UIT_INFO, UIT_NONE, UIT_PROMPT, and UIT_VERIFY.
UI_get0_output_string()
const char* UI_get0_output_string (UI_STRING * uis)
Definition at line 719 of file ui_lib.c.
UI_get0_result()
const char* UI_get0_result (UI * ui, int i)
Definition at line 401 of file ui_lib.c.
References NULL, UI_F_UI_GET0_RESULT, UI_get0_result_string(), UI_R_INDEX_TOO_LARGE, UI_R_INDEX_TOO_SMALL, and UIerr.
UI_get0_result_string()
const char* UI_get0_result_string (UI_STRING * uis)
Definition at line 739 of file ui_lib.c.
References NULL, UIT_BOOLEAN, UIT_ERROR, UIT_INFO, UIT_NONE, UIT_PROMPT, and UIT_VERIFY.
Referenced by UI_get0_result().
UI_get0_test_string()
const char* UI_get0_test_string (UI_STRING * uis)
Definition at line 754 of file ui_lib.c.
References NULL, UIT_BOOLEAN, UIT_ERROR, UIT_INFO, UIT_NONE, UIT_PROMPT, and UIT_VERIFY.
UI_get0_user_data()
void* UI_get0_user_data (UI * ui)
Definition at line 396 of file ui_lib.c.
UI_get_default_method()
const UI_METHOD* UI_get_default_method (void)
Definition at line 543 of file ui_lib.c.
UI_get_ex_data()
void* UI_get_ex_data (UI * r, int idx)
Definition at line 533 of file ui_lib.c.
UI_get_input_flags()
int UI_get_input_flags (UI_STRING * uis)
Definition at line 714 of file ui_lib.c.
UI_get_method()
const UI_METHOD* UI_get_method (UI * ui)
Definition at line 551 of file ui_lib.c.
UI_get_result_maxsize()
int UI_get_result_maxsize (UI_STRING * uis)
Definition at line 784 of file ui_lib.c.
References UIT_BOOLEAN, UIT_ERROR, UIT_INFO, UIT_NONE, UIT_PROMPT, and UIT_VERIFY.
UI_get_result_minsize()
int UI_get_result_minsize (UI_STRING * uis)
Definition at line 769 of file ui_lib.c.
References UIT_BOOLEAN, UIT_ERROR, UIT_INFO, UIT_NONE, UIT_PROMPT, and UIT_VERIFY.
UI_get_string_type()
enum UI_string_types UI_get_string_type (UI_STRING * uis)
Definition at line 709 of file ui_lib.c.
UI_method_get_ex_data()
const void* UI_method_get_ex_data (const UI_METHOD * method, int idx)
Definition at line 704 of file ui_lib.c.
UI_method_set_closer()
int UI_method_set_closer (UI_METHOD * method, int(*)(UI *ui) closer)
Definition at line 633 of file ui_lib.c.
References NULL.
UI_method_set_ex_data()
int UI_method_set_ex_data (UI_METHOD * method, int idx, void * data)
Definition at line 656 of file ui_lib.c.
UI_method_set_flusher()
int UI_method_set_flusher (UI_METHOD * method, int(*)(UI *ui) flusher)
Definition at line 614 of file ui_lib.c.
References NULL.
UI_method_set_opener()
int UI_method_set_opener (UI_METHOD * method, int(*)(UI *ui) opener)
Definition at line 595 of file ui_lib.c.
References NULL.
UI_method_set_prompt_constructor()
int UI_method_set_prompt_constructor (UI_METHOD * method, char *(*)(UI *ui, const char *object_desc, const char *object_name) prompt_constructor)
Definition at line 642 of file ui_lib.c.
References NULL.
UI_method_set_reader()
int UI_method_set_reader (UI_METHOD * method, int(*)(UI *ui, UI_STRING *uis) reader)
Definition at line 623 of file ui_lib.c.
References NULL.
UI_method_set_writer()
int UI_method_set_writer (UI_METHOD * method, int(*)(UI *ui, UI_STRING *uis) writer)
Definition at line 604 of file ui_lib.c.
References NULL.
UI_new()
UI* UI_new (void)
Definition at line 20 of file ui_lib.c.
References NULL, and UI_new_method().
UI_new_method()
UI* UI_new_method (const UI_METHOD * method)
Definition at line 25 of file ui_lib.c.
Referenced by UI_new().
UI_OpenSSL()
UI_METHOD* UI_OpenSSL (void)
Definition at line 206 of file ui_openssl.c.
UI_process()
int UI_process (UI * ui)
Definition at line 428 of file ui_lib.c.
UI_set_default_method()
void UI_set_default_method (const UI_METHOD * meth)
Definition at line 538 of file ui_lib.c.
UI_set_ex_data()
int UI_set_ex_data (UI * r, int idx, void * arg)
Definition at line 528 of file ui_lib.c.
UI_set_method()
const UI_METHOD* UI_set_method (UI * ui, const UI_METHOD * meth)
Definition at line 556 of file ui_lib.c.
UI_set_result()
int UI_set_result (UI * ui, UI_STRING * uis, const char * result)
Definition at line 799 of file ui_lib.c.
References BIO_snprintf(), DECIMAL_SIZE, ERR_add_error_data(), NULL, OPENSSL_strlcpy(), UI_F_UI_SET_RESULT, UI_FLAG_REDOABLE, UI_R_NO_RESULT_BUFFER, UI_R_RESULT_TOO_LARGE, UI_R_RESULT_TOO_SMALL, UIerr, UIT_BOOLEAN, UIT_ERROR, UIT_INFO, UIT_NONE, UIT_PROMPT, and UIT_VERIFY.
UI_UTIL_read_pw()
int UI_UTIL_read_pw (char * buf, char * buff, int size, const char * prompt, int verify)
Definition at line 31 of file ui_util.c.
UI_UTIL_read_pw_string()
int UI_UTIL_read_pw_string (char * buf, int length, const char * prompt, int verify)
Definition at line 18 of file ui_util.c.
UI_UTIL_wrap_read_pem_callback()
UI_METHOD* UI_UTIL_wrap_read_pem_callback (pem_password_cb * cb, int rwflag)
Definition at line 139 of file ui_util.c.
References data, and NULL.
Variable Documentation
UI_method_get_closer
int(*)(UI *) UI_method_get_closer(const UI_METHOD *method)
Definition at line 293 of file ui.h.
UI_method_get_flusher
int(*)(UI *) UI_method_get_flusher(const UI_METHOD *method)
Definition at line 291 of file ui.h.
UI_method_get_opener
int(*)(UI *) UI_method_get_opener(const UI_METHOD *method)
Definition at line 289 of file ui.h.
UI_method_get_prompt_constructor
char*(*)(UI *, const char *, const char *) UI_method_get_prompt_constructor(const UI_METHOD *method)
Definition at line 294 of file ui.h.
UI_method_get_reader
int(*)(UI *, UI_STRING *) UI_method_get_reader(const UI_METHOD *method)
Definition at line 292 of file ui.h.
UI_method_get_writer
int(*)(UI *, UI_STRING *) UI_method_get_writer(const UI_METHOD *method)
Definition at line 290 of file ui.h.