crypto/x509v3/v3_lib.c File Reference
v3_lib.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/conf.h>
#include <openssl/x509v3.h>
#include "ext_dat.h"
#include "standard_exts.h"
Functions
DECLARE_OBJ_BSEARCH_CMP_FN (const X509V3_EXT_METHOD *, const X509V3_EXT_METHOD *, ext)
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const X509V3_EXT_METHOD *, const X509V3_EXT_METHOD *, ext)
const X509V3_EXT_METHOD * X509V3_EXT_get_nid (int nid)
const X509V3_EXT_METHOD * X509V3_EXT_get (X509_EXTENSION *ext)
int X509V3_EXT_add_list (X509V3_EXT_METHOD *extlist)
int X509V3_EXT_add_alias (int nid_to, int nid_from)
void X509V3_EXT_cleanup (void)
int X509V3_add_standard_extensions (void)
void * X509V3_EXT_d2i (X509_EXTENSION *ext)
void * X509V3_get_d2i (const STACK_OF(X509_EXTENSION) *x, int nid, int *crit, int *idx)
int X509V3_add1_i2d (STACK_OF(X509_EXTENSION) **x, int nid, void *value, int crit, unsigned long flags)
Function Documentation
DECLARE_OBJ_BSEARCH_CMP_FN()
DECLARE_OBJ_BSEARCH_CMP_FN (const X509V3_EXT_METHOD * , const X509V3_EXT_METHOD * , ext)
IMPLEMENT_OBJ_BSEARCH_CMP_FN()
IMPLEMENT_OBJ_BSEARCH_CMP_FN (const X509V3_EXT_METHOD * , const X509V3_EXT_METHOD * , ext)
X509V3_add1_i2d()
int X509V3_add1_i2d (STACK_OF(X509_EXTENSION) ** x, int nid, void * value, int crit, unsigned long flags)
Definition at line 218 of file v3_lib.c.
Referenced by OCSP_BASICRESP_add1_ext_i2d(), OCSP_ONEREQ_add1_ext_i2d(), OCSP_REQUEST_add1_ext_i2d(), OCSP_SINGLERESP_add1_ext_i2d(), X509_add1_ext_i2d(), X509_CRL_add1_ext_i2d(), and X509_REVOKED_add1_ext_i2d().
X509V3_add_standard_extensions()
int X509V3_add_standard_extensions (void)
Definition at line 123 of file v3_lib.c.
X509V3_EXT_add_alias()
int X509V3_EXT_add_alias (int nid_to, int nid_from)
Definition at line 87 of file v3_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_malloc, X509V3_EXT_add(), X509V3_EXT_DYNAMIC, X509V3_EXT_get_nid(), X509V3_F_X509V3_EXT_ADD_ALIAS, X509V3_R_EXTENSION_NOT_FOUND, and X509V3err.
X509V3_EXT_add_list()
int X509V3_EXT_add_list (X509V3_EXT_METHOD * extlist)
Definition at line 79 of file v3_lib.c.
References X509V3_EXT_add().
X509V3_EXT_cleanup()
void X509V3_EXT_cleanup (void)
Definition at line 106 of file v3_lib.c.
X509V3_EXT_d2i()
void* X509V3_EXT_d2i (X509_EXTENSION * ext)
Definition at line 130 of file v3_lib.c.
References ASN1_item_d2i(), ASN1_ITEM_ptr, ASN1_STRING_get0_data(), ASN1_STRING_length(), NULL, X509_EXTENSION_get_data(), and X509V3_EXT_get().
X509V3_EXT_get()
const X509V3_EXT_METHOD* X509V3_EXT_get (X509_EXTENSION * ext)
Definition at line 71 of file v3_lib.c.
References nid, NID_undef, NULL, OBJ_obj2nid(), X509_EXTENSION_get_object(), and X509V3_EXT_get_nid().
Referenced by X509V3_EXT_d2i().
X509V3_EXT_get_nid()
const X509V3_EXT_METHOD* X509V3_EXT_get_nid (int nid)
Definition at line 52 of file v3_lib.c.
References t.
Referenced by X509V3_EXT_add_alias(), X509V3_EXT_get(), and X509V3_EXT_i2d().
X509V3_get_d2i()
void* X509V3_get_d2i (const STACK_OF(X509_EXTENSION) * x, int nid, int * crit, int * idx)
Definition at line 163 of file v3_lib.c.