crypto/x509v3/v3_asid.c File Reference
v3_asid.c File Reference
#include <stdio.h>
#include <string.h>
#include "internal/cryptlib.h"
#include <openssl/conf.h>
#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include <openssl/x509v3.h>
#include <openssl/x509.h>
#include "internal/x509_int.h"
#include <openssl/bn.h>
#include "ext_dat.h"
Macros
#define validation_err(_err_)
Functions
ASN1_SEQUENCE (ASRange)
int X509v3_asid_inherits (ASIdentifiers *asid)
int X509v3_asid_subset (ASIdentifiers *a, ASIdentifiers *b)
int X509v3_asid_validate_path (X509_STORE_CTX *ctx)
int X509v3_asid_validate_resource_set (STACK_OF(X509) *chain, ASIdentifiers *ext, int allow_inheritance)
Macro Definition Documentation
validation_err
#define validation_err (_err_)
Value:
do {                                  \
    if (ctx != NULL) {                  \
      ctx->error = _err_;               \
      ctx->error_depth = i;             \
      ctx->current_cert = x;            \
      ret = ctx->verify_cb(0, ctx);     \
    } else {                            \
      ret = 0;                          \
    }                                   \
    if (!ret)                           \
      goto done;                        \
  } while (0)
Definition at line 693 of file v3_asid.c.
Function Documentation
ASN1_SEQUENCE()
ASN1_SEQUENCE (ASRange)
X509v3_asid_inherits()
int X509v3_asid_inherits (ASIdentifiers * asid)
Definition at line 634 of file v3_asid.c.
References ASIdentifierChoice_inherit, ASIdentifiers::asnum, ASIdentifiers::rdi, and ASIdentifierChoice::type.
Referenced by X509v3_asid_subset(), and X509v3_asid_validate_resource_set().
X509v3_asid_subset()
int X509v3_asid_subset (ASIdentifiers * a, ASIdentifiers * b)
Definition at line 677 of file v3_asid.c.
References X509v3_asid_inherits().
X509v3_asid_validate_path()
int X509v3_asid_validate_path (X509_STORE_CTX * ctx)
Definition at line 831 of file v3_asid.c.
X509v3_asid_validate_resource_set()
int X509v3_asid_validate_resource_set (STACK_OF(X509) * chain, ASIdentifiers * ext, int allow_inheritance)
Definition at line 840 of file v3_asid.c.
References X509v3_asid_inherits().