crypto/x509v3/v3_utl.c File Reference
v3_utl.c File Reference
#include <stdio.h>
#include <ctype.h>
#include "internal/cryptlib.h"
#include <openssl/conf.h>
#include <openssl/x509v3.h>
#include "internal/x509_int.h"
#include <openssl/bn.h>
#include "ext_dat.h"
Data Structures
struct IPV6_STAT
Macros
#define HDR_NAME 1
#define HDR_VALUE 2
#define LABEL_START (1 << 0)
#define LABEL_END (1 << 1)
#define LABEL_HYPHEN (1 << 2)
#define LABEL_IDNA (1 << 3)
Typedefs
typedef int(* equal_fn) (const unsigned char *pattern, size_t pattern_len, const unsigned char *subject, size_t subject_len, unsigned int flags)
Functions
int X509V3_add_value_uchar (const char *name, const unsigned char *value, STACK_OF(CONF_VALUE) **extlist)
void X509V3_conf_free (CONF_VALUE *conf)
int X509V3_add_value_bool (const char *name, int asn1_bool, STACK_OF(CONF_VALUE) **extlist)
int X509V3_add_value_bool_nf (const char *name, int asn1_bool, STACK_OF(CONF_VALUE) **extlist)
char * i2s_ASN1_ENUMERATED (X509V3_EXT_METHOD *method, const ASN1_ENUMERATED *a)
char * i2s_ASN1_INTEGER (X509V3_EXT_METHOD *method, const ASN1_INTEGER *a)
ASN1_INTEGER * s2i_ASN1_INTEGER (X509V3_EXT_METHOD *method, const char *value)
int X509V3_add_value_int (const char *name, const ASN1_INTEGER *aint, STACK_OF(CONF_VALUE) **extlist)
int X509V3_get_value_bool (const CONF_VALUE *value, int *asn1_bool)
int X509V3_get_value_int (const CONF_VALUE *value, ASN1_INTEGER **aint)
STACK_OF (CONF_VALUE)
int name_cmp (const char *name, const char *cmp)
void X509_email_free (STACK_OF(OPENSSL_STRING) *sk)
int X509_check_host (X509 *x, const char *chk, size_t chklen, unsigned int flags, char **peername)
int X509_check_email (X509 *x, const char *chk, size_t chklen, unsigned int flags)
int X509_check_ip (X509 *x, const unsigned char *chk, size_t chklen, unsigned int flags)
int X509_check_ip_asc (X509 *x, const char *ipasc, unsigned int flags)
ASN1_OCTET_STRING * a2i_IPADDRESS (const char *ipasc)
ASN1_OCTET_STRING * a2i_IPADDRESS_NC (const char *ipasc)
int a2i_ipadd (unsigned char *ipout, const char *ipasc)
int X509V3_NAME_from_section (X509_NAME *nm, STACK_OF(CONF_VALUE) *dn_sk, unsigned long chtype)
Macro Definition Documentation
HDR_NAME
#define HDR_NAME 1
Definition at line 236 of file v3_utl.c.
HDR_VALUE
#define HDR_VALUE 2
Definition at line 237 of file v3_utl.c.
LABEL_END
#define LABEL_END (1 << 1)
Definition at line 646 of file v3_utl.c.
LABEL_HYPHEN
#define LABEL_HYPHEN (1 << 2)
Definition at line 647 of file v3_utl.c.
LABEL_IDNA
#define LABEL_IDNA (1 << 3)
Definition at line 648 of file v3_utl.c.
LABEL_START
#define LABEL_START (1 << 0)
Definition at line 645 of file v3_utl.c.
Typedef Documentation
equal_fn
typedef int(* equal_fn) (const unsigned char *pattern, size_t pattern_len, const unsigned char *subject, size_t subject_len, unsigned int flags)
Definition at line 485 of file v3_utl.c.
Function Documentation
a2i_ipadd()
int a2i_ipadd (unsigned char * ipout, const char * ipasc)
Definition at line 984 of file v3_utl.c.
Referenced by X509_check_ip_asc(), and X509_VERIFY_PARAM_set1_ip_asc().
a2i_IPADDRESS()
ASN1_OCTET_STRING* a2i_IPADDRESS (const char * ipasc)
Definition at line 919 of file v3_utl.c.
a2i_IPADDRESS_NC()
ASN1_OCTET_STRING* a2i_IPADDRESS_NC (const char * ipasc)
Definition at line 942 of file v3_utl.c.
i2s_ASN1_ENUMERATED()
char* i2s_ASN1_ENUMERATED (X509V3_EXT_METHOD * method, const ASN1_ENUMERATED * a)
Definition at line 97 of file v3_utl.c.
References ASN1_ENUMERATED_to_BN(), BN_bn2dec(), BN_free(), ERR_R_MALLOC_FAILURE, NULL, X509V3_F_I2S_ASN1_ENUMERATED, and X509V3err.
Referenced by i2s_ASN1_ENUMERATED_TABLE().
i2s_ASN1_INTEGER()
char* i2s_ASN1_INTEGER (X509V3_EXT_METHOD * method, const ASN1_INTEGER * a)
Definition at line 111 of file v3_utl.c.
References ASN1_INTEGER_to_BN(), BN_bn2dec(), BN_free(), ERR_R_MALLOC_FAILURE, NULL, X509V3_F_I2S_ASN1_INTEGER, and X509V3err.
name_cmp()
int name_cmp (const char * name, const char * cmp)
Definition at line 356 of file v3_utl.c.
References len.
s2i_ASN1_INTEGER()
ASN1_INTEGER* s2i_ASN1_INTEGER (X509V3_EXT_METHOD * method, const char * value)
Definition at line 125 of file v3_utl.c.
References NULL.
Referenced by X509V3_get_value_int().
STACK_OF()
STACK_OF (CONF_VALUE)
Definition at line 243 of file v3_utl.c.
References q.
X509_check_email()
int X509_check_email (X509 * x, const char * chk, size_t chklen, unsigned int flags)
Definition at line 874 of file v3_utl.c.
References NULL.
Referenced by print_cert_checks().
X509_check_host()
int X509_check_host (X509 * x, const char * chk, size_t chklen, unsigned int flags, char ** peername)
Definition at line 855 of file v3_utl.c.
References NULL.
Referenced by print_cert_checks().
X509_check_ip()
int X509_check_ip (X509 * x, const unsigned char * chk, size_t chklen, unsigned int flags)
Definition at line 893 of file v3_utl.c.
References NULL.
X509_check_ip_asc()
int X509_check_ip_asc (X509 * x, const char * ipasc, unsigned int flags)
Definition at line 901 of file v3_utl.c.
References a2i_ipadd(), and NULL.
Referenced by print_cert_checks().
X509_email_free()
void X509_email_free (STACK_OF(OPENSSL_STRING) * sk)
Definition at line 480 of file v3_utl.c.
X509V3_add_value_bool()
int X509V3_add_value_bool (const char * name, int asn1_bool, STACK_OF(CONF_VALUE) ** extlist)
Definition at line 81 of file v3_utl.c.
References X509V3_add_value().
X509V3_add_value_bool_nf()
int X509V3_add_value_bool_nf (const char * name, int asn1_bool, STACK_OF(CONF_VALUE) ** extlist)
Definition at line 89 of file v3_utl.c.
References X509V3_add_value().
X509V3_add_value_int()
int X509V3_add_value_int (const char * name, const ASN1_INTEGER * aint, STACK_OF(CONF_VALUE) ** extlist)
Definition at line 178 of file v3_utl.c.
X509V3_add_value_uchar()
int X509V3_add_value_uchar (const char * name, const unsigned char * value, STACK_OF(CONF_VALUE) ** extlist)
Definition at line 63 of file v3_utl.c.
References X509V3_add_value().
X509V3_conf_free()
void X509V3_conf_free (CONF_VALUE * conf)
Definition at line 71 of file v3_utl.c.
X509V3_get_value_bool()
int X509V3_get_value_bool (const CONF_VALUE * value, int * asn1_bool)
Definition at line 193 of file v3_utl.c.
References NULL, CONF_VALUE::value, X509V3_conf_err, X509V3_F_X509V3_GET_VALUE_BOOL, X509V3_R_INVALID_BOOLEAN_STRING, and X509V3err.
X509V3_get_value_int()
int X509V3_get_value_int (const CONF_VALUE * value, ASN1_INTEGER ** aint)
Definition at line 224 of file v3_utl.c.
References NULL, s2i_ASN1_INTEGER(), CONF_VALUE::value, and X509V3_conf_err.
X509V3_NAME_from_section()
int X509V3_NAME_from_section (X509_NAME * nm, STACK_OF(CONF_VALUE) * dn_sk, unsigned long chtype)
Definition at line 1149 of file v3_utl.c.
References CONF_VALUE::name, os_toascii, type, CONF_VALUE::value, and X509_NAME_add_entry_by_txt().