crypto/x509v3/v3_conf.c File Reference
v3_conf.c File Reference
#include <stdio.h>
#include <ctype.h>
#include "internal/cryptlib.h"
#include <openssl/conf.h>
#include <openssl/x509.h>
#include "internal/x509_int.h"
#include <openssl/x509v3.h>
Functions
X509_EXTENSION * X509V3_EXT_nconf_nid (CONF *conf, X509V3_CTX *ctx, int ext_nid, const char *value)
X509_EXTENSION * X509V3_EXT_i2d (int ext_nid, int crit, void *ext_struc)
int X509V3_EXT_add_nconf_sk (CONF *conf, X509V3_CTX *ctx, const char *section, STACK_OF(X509_EXTENSION) **sk)
int X509V3_EXT_add_nconf (CONF *conf, X509V3_CTX *ctx, const char *section, X509 *cert)
int X509V3_EXT_CRL_add_nconf (CONF *conf, X509V3_CTX *ctx, const char *section, X509_CRL *crl)
int X509V3_EXT_REQ_add_nconf (CONF *conf, X509V3_CTX *ctx, const char *section, X509_REQ *req)
char * X509V3_get_string (X509V3_CTX *ctx, const char *name, const char *section)
void X509V3_string_free (X509V3_CTX *ctx, char *str)
void X509V3_section_free (X509V3_CTX *ctx, STACK_OF(CONF_VALUE) *section)
void X509V3_set_nconf (X509V3_CTX *ctx, CONF *conf)
void X509V3_set_ctx (X509V3_CTX *ctx, X509 *issuer, X509 *subj, X509_REQ *req, X509_CRL *crl, int flags)
X509_EXTENSION * X509V3_EXT_conf (LHASH_OF(CONF_VALUE) *conf, X509V3_CTX *ctx, const char *name, const char *value)
X509_EXTENSION * X509V3_EXT_conf_nid (LHASH_OF(CONF_VALUE) *conf, X509V3_CTX *ctx, int ext_nid, const char *value)
void X509V3_set_conf_lhash (X509V3_CTX *ctx, LHASH_OF(CONF_VALUE) *lhash)
int X509V3_EXT_add_conf (LHASH_OF(CONF_VALUE) *conf, X509V3_CTX *ctx, const char *section, X509 *cert)
int X509V3_EXT_CRL_add_conf (LHASH_OF(CONF_VALUE) *conf, X509V3_CTX *ctx, const char *section, X509_CRL *crl)
int X509V3_EXT_REQ_add_conf (LHASH_OF(CONF_VALUE) *conf, X509V3_CTX *ctx, const char *section, X509_REQ *req)
Function Documentation
X509V3_EXT_add_conf()
int X509V3_EXT_add_conf (LHASH_OF(CONF_VALUE) * conf, X509V3_CTX * ctx, const char * section, X509 * cert)
Definition at line 481 of file v3_conf.c.
X509V3_EXT_add_nconf()
int X509V3_EXT_add_nconf (CONF * conf, X509V3_CTX * ctx, const char * section, X509 * cert)
Definition at line 327 of file v3_conf.c.
X509V3_EXT_add_nconf_sk()
int X509V3_EXT_add_nconf_sk (CONF * conf, X509V3_CTX * ctx, const char * section, STACK_OF(X509_EXTENSION) ** sk)
Definition at line 300 of file v3_conf.c.
X509V3_EXT_conf()
X509_EXTENSION* X509V3_EXT_conf (LHASH_OF(CONF_VALUE) * conf, X509V3_CTX * ctx, const char * name, const char * value)
Definition at line 440 of file v3_conf.c.
References CONF_set_nconf().
X509V3_EXT_conf_nid()
X509_EXTENSION* X509V3_EXT_conf_nid (LHASH_OF(CONF_VALUE) * conf, X509V3_CTX * ctx, int ext_nid, const char * value)
Definition at line 450 of file v3_conf.c.
References CONF_set_nconf(), and X509V3_EXT_nconf_nid().
X509V3_EXT_CRL_add_conf()
int X509V3_EXT_CRL_add_conf (LHASH_OF(CONF_VALUE) * conf, X509V3_CTX * ctx, const char * section, X509_CRL * crl)
Definition at line 491 of file v3_conf.c.
References CONF_set_nconf(), and X509V3_EXT_CRL_add_nconf().
X509V3_EXT_CRL_add_nconf()
int X509V3_EXT_CRL_add_nconf (CONF * conf, X509V3_CTX * ctx, const char * section, X509_CRL * crl)
Definition at line 338 of file v3_conf.c.
Referenced by X509V3_EXT_CRL_add_conf().
X509V3_EXT_i2d()
X509_EXTENSION* X509V3_EXT_i2d (int ext_nid, int crit, void * ext_struc)
Definition at line 177 of file v3_conf.c.
References NULL, X509V3_EXT_get_nid(), X509V3_F_X509V3_EXT_I2D, X509V3_R_UNKNOWN_EXTENSION, and X509V3err.
Referenced by OCSP_accept_responses_new(), OCSP_archive_cutoff_new(), OCSP_crlID_new(), and OCSP_url_svcloc_new().
X509V3_EXT_nconf_nid()
X509_EXTENSION* X509V3_EXT_nconf_nid (CONF * conf, X509V3_CTX * ctx, int ext_nid, const char * value)
Definition at line 55 of file v3_conf.c.
Referenced by X509V3_EXT_conf_nid().
X509V3_EXT_REQ_add_conf()
int X509V3_EXT_REQ_add_conf (LHASH_OF(CONF_VALUE) * conf, X509V3_CTX * ctx, const char * section, X509_REQ * req)
Definition at line 501 of file v3_conf.c.
References CONF_set_nconf(), and X509V3_EXT_REQ_add_nconf().
X509V3_EXT_REQ_add_nconf()
int X509V3_EXT_REQ_add_nconf (CONF * conf, X509V3_CTX * ctx, const char * section, X509_REQ * req)
Definition at line 349 of file v3_conf.c.
Referenced by X509V3_EXT_REQ_add_conf().
X509V3_get_string()
char* X509V3_get_string (X509V3_CTX * ctx, const char * name, const char * section)
Definition at line 366 of file v3_conf.c.
References NULL, X509V3_F_X509V3_GET_STRING, X509V3_R_OPERATION_NOT_DEFINED, and X509V3err.
X509V3_section_free()
void X509V3_section_free (X509V3_CTX * ctx, STACK_OF(CONF_VALUE) * section)
Definition at line 397 of file v3_conf.c.
X509V3_set_conf_lhash()
void X509V3_set_conf_lhash (X509V3_CTX * ctx, LHASH_OF(CONF_VALUE) * lhash)
Definition at line 475 of file v3_conf.c.
X509V3_set_ctx()
void X509V3_set_ctx (X509V3_CTX * ctx, X509 * issuer, X509 * subj, X509_REQ * req, X509_CRL * crl, int flags)
Definition at line 428 of file v3_conf.c.
References flags.
X509V3_set_nconf()
void X509V3_set_nconf (X509V3_CTX * ctx, CONF * conf)
Definition at line 422 of file v3_conf.c.
Referenced by ASN1_generate_nconf().
X509V3_string_free()
void X509V3_string_free (X509V3_CTX * ctx, char * str)
Definition at line 389 of file v3_conf.c.