crypto/x509v3/v3_purp.c File Reference
v3_purp.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include "internal/numbers.h"
#include <openssl/x509v3.h>
#include <openssl/x509_vfy.h>
#include "internal/x509_int.h"
Macros
#define X509_PURPOSE_COUNT OSSL_NELEM(xstandard)
#define V1_ROOT (EXFLAG_V1|EXFLAG_SS)
#define ku_reject(x, usage) (((x)->ex_flags & EXFLAG_KUSAGE) && !((x)->ex_kusage & (usage)))
#define xku_reject(x, usage) (((x)->ex_flags & EXFLAG_XKUSAGE) && !((x)->ex_xkusage & (usage)))
#define ns_reject(x, usage) (((x)->ex_flags & EXFLAG_NSCERT) && !((x)->ex_nscert & (usage)))
#define KU_TLS KU_DIGITAL_SIGNATURE|KU_KEY_ENCIPHERMENT|KU_KEY_AGREEMENT
Functions
int X509_check_purpose (X509 *x, int id, int ca)
int X509_PURPOSE_set (int *p, int purpose)
int X509_PURPOSE_get_count (void)
X509_PURPOSE * X509_PURPOSE_get0 (int idx)
int X509_PURPOSE_get_by_sname (const char *sname)
int X509_PURPOSE_get_by_id (int purpose)
int X509_PURPOSE_add (int id, int trust, int flags, int(*ck)(const X509_PURPOSE *, const X509 *, int), const char *name, const char *sname, void *arg)
void X509_PURPOSE_cleanup (void)
int X509_PURPOSE_get_id (const X509_PURPOSE *xp)
char * X509_PURPOSE_get0_name (const X509_PURPOSE *xp)
char * X509_PURPOSE_get0_sname (const X509_PURPOSE *xp)
int X509_PURPOSE_get_trust (const X509_PURPOSE *xp)
DECLARE_OBJ_BSEARCH_CMP_FN (int, int, nid)
IMPLEMENT_OBJ_BSEARCH_CMP_FN (int, int, nid)
int X509_supported_extension (X509_EXTENSION *ex)
void X509_set_proxy_flag (X509 *x)
void X509_set_proxy_pathlen (X509 *x, long l)
int X509_check_ca (X509 *x)
int X509_check_issued (X509 *issuer, X509 *subject)
int X509_check_akid (X509 *issuer, AUTHORITY_KEYID *akid)
uint32_t X509_get_extension_flags (X509 *x)
uint32_t X509_get_key_usage (X509 *x)
uint32_t X509_get_extended_key_usage (X509 *x)
const ASN1_OCTET_STRING * X509_get0_subject_key_id (X509 *x)
long X509_get_pathlen (X509 *x)
long X509_get_proxy_pathlen (X509 *x)
Macro Definition Documentation
ku_reject
#define ku_reject (x, usage) (((x)->ex_flags & EXFLAG_KUSAGE) && !((x)->ex_kusage & (usage)))
Definition at line 339 of file v3_purp.c.
KU_TLS
#define KU_TLS KU_DIGITAL_SIGNATURE|KU_KEY_ENCIPHERMENT|KU_KEY_AGREEMENT
Definition at line 587 of file v3_purp.c.
ns_reject
#define ns_reject (x, usage) (((x)->ex_flags & EXFLAG_NSCERT) && !((x)->ex_nscert & (usage)))
Definition at line 343 of file v3_purp.c.
V1_ROOT
#define V1_ROOT (EXFLAG_V1|EXFLAG_SS)
Definition at line 338 of file v3_purp.c.
X509_PURPOSE_COUNT
#define X509_PURPOSE_COUNT OSSL_NELEM(xstandard)
Definition at line 63 of file v3_purp.c.
Referenced by X509_PURPOSE_get_count().
xku_reject
#define xku_reject (x, usage) (((x)->ex_flags & EXFLAG_XKUSAGE) && !((x)->ex_xkusage & (usage)))
Definition at line 341 of file v3_purp.c.
Function Documentation
DECLARE_OBJ_BSEARCH_CMP_FN()
DECLARE_OBJ_BSEARCH_CMP_FN (int , int , nid)
IMPLEMENT_OBJ_BSEARCH_CMP_FN()
IMPLEMENT_OBJ_BSEARCH_CMP_FN (int , int , nid)
X509_check_akid()
int X509_check_akid (X509 * issuer, AUTHORITY_KEYID * akid)
Definition at line 778 of file v3_purp.c.
References ASN1_INTEGER_cmp(), ASN1_OCTET_STRING_cmp(), GENERAL_NAME::d, GENERAL_NAME::dirn, gen, GEN_DIRNAME, NULL, GENERAL_NAME::type, X509_get_issuer_name(), X509_get_serialNumber(), X509_NAME_cmp(), X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH, X509_V_ERR_AKID_SKID_MISMATCH, and X509_V_OK.
X509_check_ca()
int X509_check_ca (X509 * x)
Definition at line 541 of file v3_purp.c.
References CRYPTO_THREAD_write_lock(), and EXFLAG_SET.
X509_check_issued()
int X509_check_issued (X509 * issuer, X509 * subject)
Definition at line 756 of file v3_purp.c.
References X509_get_issuer_name(), X509_get_subject_name(), X509_NAME_cmp(), and X509_V_ERR_SUBJECT_ISSUER_MISMATCH.
X509_check_purpose()
int X509_check_purpose (X509 * x, int id, int ca)
Definition at line 77 of file v3_purp.c.
Referenced by TS_RESP_CTX_set_signer_cert(), X509_cmp(), X509_get0_subject_key_id(), X509_get_extended_key_usage(), X509_get_extension_flags(), X509_get_key_usage(), X509_get_pathlen(), and X509_get_proxy_pathlen().
X509_get0_subject_key_id()
const ASN1_OCTET_STRING* X509_get0_subject_key_id (X509 * x)
Definition at line 842 of file v3_purp.c.
References X509_check_purpose().
X509_get_extended_key_usage()
uint32_t X509_get_extended_key_usage (X509 * x)
Definition at line 833 of file v3_purp.c.
References EXFLAG_XKUSAGE, UINT32_MAX, and X509_check_purpose().
X509_get_extension_flags()
uint32_t X509_get_extension_flags (X509 * x)
Definition at line 817 of file v3_purp.c.
References X509_check_purpose().
Referenced by ssl_build_cert_chain().
X509_get_key_usage()
uint32_t X509_get_key_usage (X509 * x)
Definition at line 824 of file v3_purp.c.
References EXFLAG_KUSAGE, UINT32_MAX, and X509_check_purpose().
Referenced by ssl_check_srvr_ecc_cert_and_alg().
X509_get_pathlen()
long X509_get_pathlen (X509 * x)
Definition at line 849 of file v3_purp.c.
References EXFLAG_BCONS, and X509_check_purpose().
X509_get_proxy_pathlen()
long X509_get_proxy_pathlen (X509 * x)
Definition at line 858 of file v3_purp.c.
References EXFLAG_PROXY, and X509_check_purpose().
X509_PURPOSE_add()
int X509_PURPOSE_add (int id, int trust, int flags, int(*)(const X509_PURPOSE *, const X509 *, int) ck, const char * name, const char * sname, void * arg)
Definition at line 149 of file v3_purp.c.
X509_PURPOSE_cleanup()
void X509_PURPOSE_cleanup (void)
Definition at line 230 of file v3_purp.c.
X509_PURPOSE_get0()
X509_PURPOSE* X509_PURPOSE_get0 (int idx)
Definition at line 113 of file v3_purp.c.
Referenced by X509_PURPOSE_get_by_sname().
X509_PURPOSE_get0_name()
char* X509_PURPOSE_get0_name (const X509_PURPOSE * xp)
Definition at line 241 of file v3_purp.c.
References X509_PURPOSE::name.
X509_PURPOSE_get0_sname()
char* X509_PURPOSE_get0_sname (const X509_PURPOSE * xp)
Definition at line 246 of file v3_purp.c.
References X509_PURPOSE::sname.
X509_PURPOSE_get_by_id()
int X509_PURPOSE_get_by_id (int purpose)
Definition at line 134 of file v3_purp.c.
Referenced by X509_PURPOSE_set().
X509_PURPOSE_get_by_sname()
int X509_PURPOSE_get_by_sname (const char * sname)
Definition at line 122 of file v3_purp.c.
References X509_PURPOSE::sname, X509_PURPOSE_get0(), and X509_PURPOSE_get_count().
X509_PURPOSE_get_count()
int X509_PURPOSE_get_count (void)
Definition at line 106 of file v3_purp.c.
References X509_PURPOSE_COUNT.
Referenced by X509_PURPOSE_get_by_sname().
X509_PURPOSE_get_id()
int X509_PURPOSE_get_id (const X509_PURPOSE * xp)
Definition at line 236 of file v3_purp.c.
References X509_PURPOSE::purpose.
X509_PURPOSE_get_trust()
int X509_PURPOSE_get_trust (const X509_PURPOSE * xp)
Definition at line 251 of file v3_purp.c.
References X509_PURPOSE::trust.
X509_PURPOSE_set()
int X509_PURPOSE_set (int * p, int purpose)
Definition at line 96 of file v3_purp.c.
References X509_PURPOSE_get_by_id(), X509V3_F_X509_PURPOSE_SET, X509V3_R_INVALID_PURPOSE, and X509V3err.
Referenced by X509_VERIFY_PARAM_set_purpose().
X509_set_proxy_flag()
void X509_set_proxy_flag (X509 * x)
Definition at line 531 of file v3_purp.c.
References EXFLAG_PROXY.
X509_set_proxy_pathlen()
void X509_set_proxy_pathlen (X509 * x, long l)
Definition at line 536 of file v3_purp.c.
X509_supported_extension()
int X509_supported_extension (X509_EXTENSION * ex)
Definition at line 264 of file v3_purp.c.
References NID_basic_constraints, NID_certificate_policies, NID_ext_key_usage, NID_inhibit_any_policy, NID_key_usage, NID_name_constraints, NID_netscape_cert_type, NID_policy_constraints, NID_policy_mappings, NID_proxyCertInfo, NID_sbgp_autonomousSysNum, NID_sbgp_ipAddrBlock, NID_subject_alt_name, NID_undef, OBJ_obj2nid(), OSSL_NELEM, and X509_EXTENSION_get_object().