crypto/x509v3/v3_addr.c File Reference
v3_addr.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "internal/cryptlib.h"
#include <openssl/conf.h>
#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include <openssl/buffer.h>
#include <openssl/x509v3.h>
#include "internal/x509_int.h"
#include "ext_dat.h"
Macros
#define ADDR_RAW_BUF_LEN 16
#define addr_prefixlen(bs) ((int) ((bs)->length * 8 - ((bs)->flags & 7)))
#define validation_err(_err_)
Functions
ASN1_SEQUENCE (IPAddressRange)
int X509v3_addr_inherits (IPAddrBlocks *addr)
int X509v3_addr_subset (IPAddrBlocks *a, IPAddrBlocks *b)
int X509v3_addr_validate_path (X509_STORE_CTX *ctx)
int X509v3_addr_validate_resource_set (STACK_OF(X509) *chain, IPAddrBlocks *ext, int allow_inheritance)
Macro Definition Documentation
addr_prefixlen
#define addr_prefixlen (bs) ((int) ((bs)->length * 8 - ((bs)->flags & 7)))
ADDR_RAW_BUF_LEN
#define ADDR_RAW_BUF_LEN 16
validation_err
#define validation_err (_err_)
Value:
do {                                  \
    if (ctx != NULL) {                  \
      ctx->error = _err_;               \
      ctx->error_depth = i;             \
      ctx->current_cert = x;            \
      ret = ctx->verify_cb(0, ctx);     \
    } else {                            \
      ret = 0;                          \
    }                                   \
    if (!ret)                           \
      goto done;                        \
  } while (0)
Definition at line 1153 of file v3_addr.c.
Function Documentation
ASN1_SEQUENCE()
ASN1_SEQUENCE (IPAddressRange)
X509v3_addr_inherits()
int X509v3_addr_inherits (IPAddrBlocks * addr)
Definition at line 1074 of file v3_addr.c.
References IPAddressFamily::ipAddressChoice, IPAddressChoice_inherit, and IPAddressChoice::type.
Referenced by X509v3_addr_subset(), and X509v3_addr_validate_resource_set().
X509v3_addr_subset()
int X509v3_addr_subset (IPAddrBlocks * a, IPAddrBlocks * b)
Definition at line 1127 of file v3_addr.c.
References X509v3_addr_inherits().
X509v3_addr_validate_path()
int X509v3_addr_validate_path (X509_STORE_CTX * ctx)
Definition at line 1284 of file v3_addr.c.
X509v3_addr_validate_resource_set()
int X509v3_addr_validate_resource_set (STACK_OF(X509) * chain, IPAddrBlocks * ext, int allow_inheritance)
Definition at line 1293 of file v3_addr.c.
References X509v3_addr_inherits().