crypto/x509v3/v3_alt.c File Reference
v3_alt.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/conf.h>
#include <openssl/x509v3.h>
#include "ext_dat.h"
Functions
STACK_OF (CONF_VALUE)
int GENERAL_NAME_print (BIO *out, GENERAL_NAME *gen)
GENERAL_NAMES * v2i_GENERAL_NAMES (const X509V3_EXT_METHOD *method, X509V3_CTX *ctx, STACK_OF(CONF_VALUE) *nval)
GENERAL_NAME * v2i_GENERAL_NAME (const X509V3_EXT_METHOD *method, X509V3_CTX *ctx, CONF_VALUE *cnf)
GENERAL_NAME * a2i_GENERAL_NAME (GENERAL_NAME *out, const X509V3_EXT_METHOD *method, X509V3_CTX *ctx, int gen_type, const char *value, int is_nc)
GENERAL_NAME * v2i_GENERAL_NAME_ex (GENERAL_NAME *out, const X509V3_EXT_METHOD *method, X509V3_CTX *ctx, CONF_VALUE *cnf, int is_nc)
Variables
const X509V3_EXT_METHOD v3_alt [3]
Function Documentation
a2i_GENERAL_NAME()
GENERAL_NAME* a2i_GENERAL_NAME (GENERAL_NAME * out, const X509V3_EXT_METHOD * method, X509V3_CTX * ctx, int gen_type, const char * value, int is_nc)
Definition at line 384 of file v3_alt.c.
GENERAL_NAME_print()
int GENERAL_NAME_print (BIO * out, GENERAL_NAME * gen)
Definition at line 130 of file v3_alt.c.
Referenced by OCSP_REQUEST_print().
STACK_OF()
STACK_OF (CONF_VALUE)
Definition at line 49 of file v3_alt.c.
v2i_GENERAL_NAME()
GENERAL_NAME* v2i_GENERAL_NAME (const X509V3_EXT_METHOD * method, X509V3_CTX * ctx, CONF_VALUE * cnf)
Definition at line 378 of file v3_alt.c.
References NULL, and v2i_GENERAL_NAME_ex().
Referenced by v2i_GENERAL_NAMES().
v2i_GENERAL_NAME_ex()
GENERAL_NAME* v2i_GENERAL_NAME_ex (GENERAL_NAME * out, const X509V3_EXT_METHOD * method, X509V3_CTX * ctx, CONF_VALUE * cnf, int is_nc)
Definition at line 475 of file v3_alt.c.
Referenced by v2i_GENERAL_NAME().
v2i_GENERAL_NAMES()
GENERAL_NAMES* v2i_GENERAL_NAMES (const X509V3_EXT_METHOD * method, X509V3_CTX * ctx, STACK_OF(CONF_VALUE) * nval)
Definition at line 354 of file v3_alt.c.
References ERR_R_MALLOC_FAILURE, gen, NULL, v2i_GENERAL_NAME(), X509V3_F_V2I_GENERAL_NAMES, and X509V3err.
Variable Documentation
v3_alt
const X509V3_EXT_METHOD v3_alt[3]
Initial value:
= {
    {NID_subject_alt_name, 0, ASN1_ITEM_ref(GENERAL_NAMES),
     0, 0, 0, 0,
     0, 0,
     (X509V3_EXT_I2V) i2v_GENERAL_NAMES,
     (X509V3_EXT_V2I)v2i_subject_alt,
     NULL, NULL, NULL},
    {NID_issuer_alt_name, 0, ASN1_ITEM_ref(GENERAL_NAMES),
     0, 0, 0, 0,
     0, 0,
     (X509V3_EXT_I2V) i2v_GENERAL_NAMES,
     (X509V3_EXT_V2I)v2i_issuer_alt,
     NULL, NULL, NULL},
    {NID_certificate_issuer, 0, ASN1_ITEM_ref(GENERAL_NAMES),
     0, 0, 0, 0,
     0, 0,
     (X509V3_EXT_I2V) i2v_GENERAL_NAMES,
     NULL, NULL, NULL, NULL},
}
Definition at line 27 of file v3_alt.c.