crypto/include/internal/x509_int.h File Reference
x509_int.h File Reference
#include "internal/refcount.h"
Data Structures
struct X509_NAME_ENTRY
struct X509_NAME
struct X509_REQ_INFO
struct X509_REQ
struct X509_CRL_INFO
struct X509_CRL
struct X509_REVOKED
struct X509_CERT_AUX
struct X509_CINF
struct X509
struct X509_STORE_CTX
struct PKCS8_PRIV_KEY_INFO
struct X509_SIG
struct X509_OBJECT
Functions
int a2i_ipadd (unsigned char *ipout, const char *ipasc)
int x509_set1_time (ASN1_TIME **ptm, const ASN1_TIME *tm)
Function Documentation
a2i_ipadd()
int a2i_ipadd (unsigned char * ipout, const char * ipasc)
Definition at line 984 of file v3_utl.c.
Referenced by X509_check_ip_asc(), and X509_VERIFY_PARAM_set1_ip_asc().
x509_set1_time()
int x509_set1_time (ASN1_TIME ** ptm, const ASN1_TIME * tm)
Definition at line 60 of file x509_set.c.
References ASN1_STRING_dup(), in, and NULL.
Referenced by X509_CRL_set1_lastUpdate(), X509_CRL_set1_nextUpdate(), X509_set1_notAfter(), and X509_set1_notBefore().