crypto/x509/x509_trs.c File Reference
x509_trs.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/x509v3.h>
#include "internal/x509_int.h"
Macros
#define X509_TRUST_COUNT OSSL_NELEM(trstandard)
Functions
int X509_check_trust (X509 *x, int id, int flags)
int X509_TRUST_get_count (void)
X509_TRUST * X509_TRUST_get0 (int idx)
int X509_TRUST_get_by_id (int id)
int X509_TRUST_set (int *t, int trust)
int X509_TRUST_add (int id, int flags, int(*ck)(X509_TRUST *, X509 *, int), const char *name, int arg1, void *arg2)
void X509_TRUST_cleanup (void)
int X509_TRUST_get_flags (const X509_TRUST *xp)
char * X509_TRUST_get0_name (const X509_TRUST *xp)
int X509_TRUST_get_trust (const X509_TRUST *xp)
Variables
int(*)(int, X509 *, int) X509_TRUST_set_default (int(*trust)(int, X509 *, int))
Macro Definition Documentation
X509_TRUST_COUNT
#define X509_TRUST_COUNT OSSL_NELEM(trstandard)
Definition at line 48 of file x509_trs.c.
Referenced by X509_TRUST_get_count().
Function Documentation
X509_check_trust()
int X509_check_trust (X509 * x, int id, int flags)
Definition at line 65 of file x509_trs.c.
X509_TRUST_add()
int X509_TRUST_add (int id, int flags, int(*)(X509_TRUST *, X509 *, int) ck, const char * name, int arg1, void * arg2)
Definition at line 122 of file x509_trs.c.
X509_TRUST_cleanup()
void X509_TRUST_cleanup (void)
Definition at line 195 of file x509_trs.c.
X509_TRUST_get0()
X509_TRUST* X509_TRUST_get0 (int idx)
Definition at line 88 of file x509_trs.c.
X509_TRUST_get0_name()
char* X509_TRUST_get0_name (const X509_TRUST * xp)
Definition at line 206 of file x509_trs.c.
References X509_TRUST::name.
X509_TRUST_get_by_id()
int X509_TRUST_get_by_id (int id)
Definition at line 97 of file x509_trs.c.
Referenced by X509_TRUST_set().
X509_TRUST_get_count()
int X509_TRUST_get_count (void)
Definition at line 81 of file x509_trs.c.
References X509_TRUST_COUNT.
X509_TRUST_get_flags()
int X509_TRUST_get_flags (const X509_TRUST * xp)
Definition at line 201 of file x509_trs.c.
References X509_TRUST::flags.
X509_TRUST_get_trust()
int X509_TRUST_get_trust (const X509_TRUST * xp)
Definition at line 211 of file x509_trs.c.
References X509_TRUST::trust.
X509_TRUST_set()
int X509_TRUST_set (int * t, int trust)
Definition at line 112 of file x509_trs.c.
References X509_F_X509_TRUST_SET, X509_R_INVALID_TRUST, X509_TRUST_get_by_id(), and X509err.
Referenced by X509_VERIFY_PARAM_set_trust().
Variable Documentation
X509_TRUST_set_default
int(*)(int, X509 *, int) X509_TRUST_set_default(int(*trust)(int, X509 *, int))
Definition at line 57 of file x509_trs.c.