crypto/x509/x509_ext.c File Reference
x509_ext.c File Reference
#include <stdio.h>
#include <openssl/stack.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include "internal/x509_int.h"
#include <openssl/x509v3.h>
Functions
int X509_CRL_get_ext_count (const X509_CRL *x)
int X509_CRL_get_ext_by_NID (const X509_CRL *x, int nid, int lastpos)
int X509_CRL_get_ext_by_OBJ (const X509_CRL *x, const ASN1_OBJECT *obj, int lastpos)
int X509_CRL_get_ext_by_critical (const X509_CRL *x, int crit, int lastpos)
X509_EXTENSION * X509_CRL_get_ext (const X509_CRL *x, int loc)
X509_EXTENSION * X509_CRL_delete_ext (X509_CRL *x, int loc)
void * X509_CRL_get_ext_d2i (const X509_CRL *x, int nid, int *crit, int *idx)
int X509_CRL_add1_ext_i2d (X509_CRL *x, int nid, void *value, int crit, unsigned long flags)
int X509_CRL_add_ext (X509_CRL *x, X509_EXTENSION *ex, int loc)
int X509_get_ext_count (const X509 *x)
int X509_get_ext_by_NID (const X509 *x, int nid, int lastpos)
int X509_get_ext_by_OBJ (const X509 *x, const ASN1_OBJECT *obj, int lastpos)
int X509_get_ext_by_critical (const X509 *x, int crit, int lastpos)
X509_EXTENSION * X509_get_ext (const X509 *x, int loc)
X509_EXTENSION * X509_delete_ext (X509 *x, int loc)
int X509_add_ext (X509 *x, X509_EXTENSION *ex, int loc)
void * X509_get_ext_d2i (const X509 *x, int nid, int *crit, int *idx)
int X509_add1_ext_i2d (X509 *x, int nid, void *value, int crit, unsigned long flags)
int X509_REVOKED_get_ext_count (const X509_REVOKED *x)
int X509_REVOKED_get_ext_by_NID (const X509_REVOKED *x, int nid, int lastpos)
int X509_REVOKED_get_ext_by_OBJ (const X509_REVOKED *x, const ASN1_OBJECT *obj, int lastpos)
int X509_REVOKED_get_ext_by_critical (const X509_REVOKED *x, int crit, int lastpos)
X509_EXTENSION * X509_REVOKED_get_ext (const X509_REVOKED *x, int loc)
X509_EXTENSION * X509_REVOKED_delete_ext (X509_REVOKED *x, int loc)
int X509_REVOKED_add_ext (X509_REVOKED *x, X509_EXTENSION *ex, int loc)
void * X509_REVOKED_get_ext_d2i (const X509_REVOKED *x, int nid, int *crit, int *idx)
int X509_REVOKED_add1_ext_i2d (X509_REVOKED *x, int nid, void *value, int crit, unsigned long flags)
Function Documentation
X509_add1_ext_i2d()
int X509_add1_ext_i2d (X509 * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 108 of file x509_ext.c.
References X509V3_add1_i2d().
X509_add_ext()
int X509_add_ext (X509 * x, X509_EXTENSION * ex, int loc)
Definition at line 98 of file x509_ext.c.
References NULL.
X509_CRL_add1_ext_i2d()
int X509_CRL_add1_ext_i2d (X509_CRL * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 56 of file x509_ext.c.
References X509V3_add1_i2d().
X509_CRL_add_ext()
int X509_CRL_add_ext (X509_CRL * x, X509_EXTENSION * ex, int loc)
Definition at line 62 of file x509_ext.c.
References NULL.
X509_CRL_delete_ext()
X509_EXTENSION* X509_CRL_delete_ext (X509_CRL * x, int loc)
Definition at line 46 of file x509_ext.c.
References X509v3_delete_ext().
X509_CRL_get_ext()
X509_EXTENSION* X509_CRL_get_ext (const X509_CRL * x, int loc)
Definition at line 41 of file x509_ext.c.
References X509v3_get_ext().
X509_CRL_get_ext_by_critical()
int X509_CRL_get_ext_by_critical (const X509_CRL * x, int crit, int lastpos)
Definition at line 36 of file x509_ext.c.
References X509v3_get_ext_by_critical().
X509_CRL_get_ext_by_NID()
int X509_CRL_get_ext_by_NID (const X509_CRL * x, int nid, int lastpos)
Definition at line 25 of file x509_ext.c.
References X509v3_get_ext_by_NID().
X509_CRL_get_ext_by_OBJ()
int X509_CRL_get_ext_by_OBJ (const X509_CRL * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 30 of file x509_ext.c.
References X509v3_get_ext_by_OBJ().
X509_CRL_get_ext_count()
int X509_CRL_get_ext_count (const X509_CRL * x)
Definition at line 20 of file x509_ext.c.
References X509v3_get_ext_count().
X509_CRL_get_ext_d2i()
void* X509_CRL_get_ext_d2i (const X509_CRL * x, int nid, int * crit, int * idx)
Definition at line 51 of file x509_ext.c.
X509_delete_ext()
X509_EXTENSION* X509_delete_ext (X509 * x, int loc)
Definition at line 93 of file x509_ext.c.
References X509v3_delete_ext().
X509_get_ext()
X509_EXTENSION* X509_get_ext (const X509 * x, int loc)
Definition at line 88 of file x509_ext.c.
References X509v3_get_ext().
X509_get_ext_by_critical()
int X509_get_ext_by_critical (const X509 * x, int crit, int lastpos)
Definition at line 82 of file x509_ext.c.
References X509v3_get_ext_by_critical().
X509_get_ext_by_NID()
int X509_get_ext_by_NID (const X509 * x, int nid, int lastpos)
Definition at line 72 of file x509_ext.c.
References X509v3_get_ext_by_NID().
X509_get_ext_by_OBJ()
int X509_get_ext_by_OBJ (const X509 * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 77 of file x509_ext.c.
References X509v3_get_ext_by_OBJ().
X509_get_ext_count()
int X509_get_ext_count (const X509 * x)
Definition at line 67 of file x509_ext.c.
References X509v3_get_ext_count().
X509_get_ext_d2i()
void* X509_get_ext_d2i (const X509 * x, int nid, int * crit, int * idx)
Definition at line 103 of file x509_ext.c.
X509_REVOKED_add1_ext_i2d()
int X509_REVOKED_add1_ext_i2d (X509_REVOKED * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 156 of file x509_ext.c.
References X509V3_add1_i2d().
X509_REVOKED_add_ext()
int X509_REVOKED_add_ext (X509_REVOKED * x, X509_EXTENSION * ex, int loc)
Definition at line 146 of file x509_ext.c.
References NULL.
X509_REVOKED_delete_ext()
X509_EXTENSION* X509_REVOKED_delete_ext (X509_REVOKED * x, int loc)
Definition at line 141 of file x509_ext.c.
References X509v3_delete_ext().
X509_REVOKED_get_ext()
X509_EXTENSION* X509_REVOKED_get_ext (const X509_REVOKED * x, int loc)
Definition at line 136 of file x509_ext.c.
References X509v3_get_ext().
X509_REVOKED_get_ext_by_critical()
int X509_REVOKED_get_ext_by_critical (const X509_REVOKED * x, int crit, int lastpos)
Definition at line 131 of file x509_ext.c.
References X509v3_get_ext_by_critical().
X509_REVOKED_get_ext_by_NID()
int X509_REVOKED_get_ext_by_NID (const X509_REVOKED * x, int nid, int lastpos)
Definition at line 120 of file x509_ext.c.
References X509v3_get_ext_by_NID().
X509_REVOKED_get_ext_by_OBJ()
int X509_REVOKED_get_ext_by_OBJ (const X509_REVOKED * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 125 of file x509_ext.c.
References X509v3_get_ext_by_OBJ().
X509_REVOKED_get_ext_count()
int X509_REVOKED_get_ext_count (const X509_REVOKED * x)
Definition at line 115 of file x509_ext.c.
References X509v3_get_ext_count().
X509_REVOKED_get_ext_d2i()
void* X509_REVOKED_get_ext_d2i (const X509_REVOKED * x, int nid, int * crit, int * idx)
Definition at line 151 of file x509_ext.c.