crypto/x509/x509cset.c File Reference
x509cset.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include "internal/x509_int.h"
Functions
int X509_CRL_set_version (X509_CRL *x, long version)
int X509_CRL_set_issuer_name (X509_CRL *x, X509_NAME *name)
int X509_CRL_set1_lastUpdate (X509_CRL *x, const ASN1_TIME *tm)
int X509_CRL_set1_nextUpdate (X509_CRL *x, const ASN1_TIME *tm)
int X509_CRL_sort (X509_CRL *c)
int X509_CRL_up_ref (X509_CRL *crl)
long X509_CRL_get_version (const X509_CRL *crl)
const ASN1_TIME * X509_CRL_get0_lastUpdate (const X509_CRL *crl)
const ASN1_TIME * X509_CRL_get0_nextUpdate (const X509_CRL *crl)
ASN1_TIME * X509_CRL_get_lastUpdate (X509_CRL *crl)
ASN1_TIME * X509_CRL_get_nextUpdate (X509_CRL *crl)
X509_NAME * X509_CRL_get_issuer (const X509_CRL *crl)
const STACK_OF (X509_EXTENSION)
STACK_OF (X509_REVOKED)
void X509_CRL_get0_signature (const X509_CRL *crl, const ASN1_BIT_STRING **psig, const X509_ALGOR **palg)
int X509_CRL_get_signature_nid (const X509_CRL *crl)
const ASN1_TIME * X509_REVOKED_get0_revocationDate (const X509_REVOKED *x)
int X509_REVOKED_set_revocationDate (X509_REVOKED *x, ASN1_TIME *tm)
const ASN1_INTEGER * X509_REVOKED_get0_serialNumber (const X509_REVOKED *x)
int X509_REVOKED_set_serialNumber (X509_REVOKED *x, ASN1_INTEGER *serial)
int i2d_re_X509_CRL_tbs (X509_CRL *crl, unsigned char **pp)
Function Documentation
i2d_re_X509_CRL_tbs()
int i2d_re_X509_CRL_tbs (X509_CRL * crl, unsigned char ** pp)
Definition at line 178 of file x509cset.c.
STACK_OF() [1/2]
const STACK_OF (X509_EXTENSION)
Definition at line 110 of file x509cset.c.
Referenced by X509_REVOKED_set_serialNumber().
STACK_OF() [2/2]
STACK_OF (X509_REVOKED)
Definition at line 115 of file x509cset.c.
X509_CRL_get0_lastUpdate()
const ASN1_TIME* X509_CRL_get0_lastUpdate (const X509_CRL * crl)
Definition at line 83 of file x509cset.c.
X509_CRL_get0_nextUpdate()
const ASN1_TIME* X509_CRL_get0_nextUpdate (const X509_CRL * crl)
Definition at line 88 of file x509cset.c.
X509_CRL_get0_signature()
void X509_CRL_get0_signature (const X509_CRL * crl, const ASN1_BIT_STRING ** psig, const X509_ALGOR ** palg)
Definition at line 120 of file x509cset.c.
References NULL.
X509_CRL_get_issuer()
X509_NAME* X509_CRL_get_issuer (const X509_CRL * crl)
Definition at line 105 of file x509cset.c.
X509_CRL_get_lastUpdate()
ASN1_TIME* X509_CRL_get_lastUpdate (X509_CRL * crl)
Definition at line 94 of file x509cset.c.
X509_CRL_get_nextUpdate()
ASN1_TIME* X509_CRL_get_nextUpdate (X509_CRL * crl)
Definition at line 99 of file x509cset.c.
X509_CRL_get_signature_nid()
int X509_CRL_get_signature_nid (const X509_CRL * crl)
Definition at line 129 of file x509cset.c.
References OBJ_obj2nid().
X509_CRL_get_version()
long X509_CRL_get_version (const X509_CRL * crl)
Definition at line 78 of file x509cset.c.
References ASN1_INTEGER_get().
X509_CRL_set1_lastUpdate()
int X509_CRL_set1_lastUpdate (X509_CRL * x, const ASN1_TIME * tm)
Definition at line 36 of file x509cset.c.
References NULL, and x509_set1_time().
X509_CRL_set1_nextUpdate()
int X509_CRL_set1_nextUpdate (X509_CRL * x, const ASN1_TIME * tm)
Definition at line 43 of file x509cset.c.
References NULL, and x509_set1_time().
X509_CRL_set_issuer_name()
int X509_CRL_set_issuer_name (X509_CRL * x, X509_NAME * name)
Definition at line 29 of file x509cset.c.
References NULL, and X509_NAME_set().
X509_CRL_set_version()
int X509_CRL_set_version (X509_CRL * x, long version)
Definition at line 18 of file x509cset.c.
References ASN1_INTEGER_set(), and NULL.
X509_CRL_sort()
int X509_CRL_sort (X509_CRL * c)
Definition at line 50 of file x509cset.c.
X509_CRL_up_ref()
int X509_CRL_up_ref (X509_CRL * crl)
Definition at line 66 of file x509cset.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by CMS_add1_crl(), PKCS7_add_crl(), STACK_OF(), and X509_OBJECT_up_ref_count().
X509_REVOKED_get0_revocationDate()
const ASN1_TIME* X509_REVOKED_get0_revocationDate (const X509_REVOKED * x)
Definition at line 134 of file x509cset.c.
X509_REVOKED_get0_serialNumber()
const ASN1_INTEGER* X509_REVOKED_get0_serialNumber (const X509_REVOKED * x)
Definition at line 156 of file x509cset.c.
X509_REVOKED_set_revocationDate()
int X509_REVOKED_set_revocationDate (X509_REVOKED * x, ASN1_TIME * tm)
Definition at line 139 of file x509cset.c.
References ASN1_STRING_dup(), in, and NULL.
X509_REVOKED_set_serialNumber()
int X509_REVOKED_set_serialNumber (X509_REVOKED * x, ASN1_INTEGER * serial)
Definition at line 161 of file x509cset.c.
References ASN1_STRING_copy(), in, NULL, and STACK_OF().