crypto/x509/x509_d2.c File Reference
x509_d2.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/crypto.h>
#include <openssl/x509.h>
Functions
int X509_STORE_set_default_paths (X509_STORE *ctx)
int X509_STORE_load_locations (X509_STORE *ctx, const char *file, const char *path)
Function Documentation
X509_STORE_load_locations()
int X509_STORE_load_locations (X509_STORE * ctx, const char * file, const char * path)
Definition at line 35 of file x509_d2.c.
Referenced by SSL_CTX_load_verify_locations(), and ssl_load_stores().
X509_STORE_set_default_paths()
int X509_STORE_set_default_paths (X509_STORE * ctx)
Definition at line 15 of file x509_d2.c.
Referenced by SSL_CTX_set_default_verify_paths().