include/openssl/x509v3.h File Reference
x509v3.h File Reference
#include <openssl/bio.h>
#include <openssl/x509.h>
#include <openssl/conf.h>
Data Structures
struct X509V3_EXT_METHOD
struct X509V3_CONF_METHOD
struct X509V3_CTX
struct BASIC_CONSTRAINTS
struct PKEY_USAGE_PERIOD
struct OTHERNAME
struct EDIPARTYNAME
struct GENERAL_NAME
struct ACCESS_DESCRIPTION
struct DIST_POINT_NAME
struct DIST_POINT
struct AUTHORITY_KEYID
struct SXNETID
struct SXNET
struct NOTICEREF
struct USERNOTICE
struct POLICYQUALINFO
struct POLICYINFO
struct POLICY_MAPPING
struct GENERAL_SUBTREE
struct NAME_CONSTRAINTS
struct POLICY_CONSTRAINTS
struct PROXY_POLICY
struct PROXY_CERT_INFO_EXTENSION
struct ISSUING_DIST_POINT
struct X509_PURPOSE
struct ASRange
struct ASIdOrRange
struct ASIdentifierChoice
struct ASIdentifiers
struct IPAddressRange
struct IPAddressOrRange
struct IPAddressChoice
struct IPAddressFamily
Macros
#define CTX_TEST 0x1
#define X509V3_CTX_REPLACE 0x2
#define X509V3_EXT_DYNAMIC 0x1
#define X509V3_EXT_CTX_DEP 0x2
#define X509V3_EXT_MULTILINE 0x4
#define GEN_OTHERNAME 0
#define GEN_EMAIL 1
#define GEN_DNS 2
#define GEN_X400 3
#define GEN_DIRNAME 4
#define GEN_EDIPARTY 5
#define GEN_URI 6
#define GEN_IPADD 7
#define GEN_RID 8
#define CRLDP_ALL_REASONS 0x807f
#define CRL_REASON_NONE -1
#define CRL_REASON_UNSPECIFIED 0
#define CRL_REASON_KEY_COMPROMISE 1
#define CRL_REASON_CA_COMPROMISE 2
#define CRL_REASON_AFFILIATION_CHANGED 3
#define CRL_REASON_SUPERSEDED 4
#define CRL_REASON_CESSATION_OF_OPERATION 5
#define CRL_REASON_CERTIFICATE_HOLD 6
#define CRL_REASON_REMOVE_FROM_CRL 8
#define CRL_REASON_PRIVILEGE_WITHDRAWN 9
#define CRL_REASON_AA_COMPROMISE 10
#define IDP_PRESENT 0x1
#define IDP_INVALID 0x2
#define IDP_ONLYUSER 0x4
#define IDP_ONLYCA 0x8
#define IDP_ONLYATTR 0x10
#define IDP_INDIRECT 0x20
#define IDP_REASONS 0x40
#define X509V3_conf_err(val)
#define X509V3_set_ctx_test(ctx) X509V3_set_ctx(ctx, NULL, NULL, NULL, NULL, CTX_TEST)
#define X509V3_set_ctx_nodb(ctx) (ctx)->db = NULL;
#define EXT_BITSTRING(nid, table)
#define EXT_IA5STRING(nid)
#define EXT_END { -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define EXFLAG_BCONS 0x1
#define EXFLAG_KUSAGE 0x2
#define EXFLAG_XKUSAGE 0x4
#define EXFLAG_NSCERT 0x8
#define EXFLAG_CA 0x10
#define EXFLAG_SI 0x20
#define EXFLAG_V1 0x40
#define EXFLAG_INVALID 0x80
#define EXFLAG_SET 0x100
#define EXFLAG_CRITICAL 0x200
#define EXFLAG_PROXY 0x400
#define EXFLAG_INVALID_POLICY 0x800
#define EXFLAG_FRESHEST 0x1000
#define EXFLAG_SS 0x2000
#define KU_DIGITAL_SIGNATURE 0x0080
#define KU_NON_REPUDIATION 0x0040
#define KU_KEY_ENCIPHERMENT 0x0020
#define KU_DATA_ENCIPHERMENT 0x0010
#define KU_KEY_AGREEMENT 0x0008
#define KU_KEY_CERT_SIGN 0x0004
#define KU_CRL_SIGN 0x0002
#define KU_ENCIPHER_ONLY 0x0001
#define KU_DECIPHER_ONLY 0x8000
#define NS_SSL_CLIENT 0x80
#define NS_SSL_SERVER 0x40
#define NS_SMIME 0x20
#define NS_OBJSIGN 0x10
#define NS_SSL_CA 0x04
#define NS_SMIME_CA 0x02
#define NS_OBJSIGN_CA 0x01
#define NS_ANY_CA (NS_SSL_CA|NS_SMIME_CA|NS_OBJSIGN_CA)
#define XKU_SSL_SERVER 0x1
#define XKU_SSL_CLIENT 0x2
#define XKU_SMIME 0x4
#define XKU_CODE_SIGN 0x8
#define XKU_SGC 0x10
#define XKU_OCSP_SIGN 0x20
#define XKU_TIMESTAMP 0x40
#define XKU_DVCS 0x80
#define XKU_ANYEKU 0x100
#define X509_PURPOSE_DYNAMIC 0x1
#define X509_PURPOSE_DYNAMIC_NAME 0x2
#define X509_PURPOSE_SSL_CLIENT 1
#define X509_PURPOSE_SSL_SERVER 2
#define X509_PURPOSE_NS_SSL_SERVER 3
#define X509_PURPOSE_SMIME_SIGN 4
#define X509_PURPOSE_SMIME_ENCRYPT 5
#define X509_PURPOSE_CRL_SIGN 6
#define X509_PURPOSE_ANY 7
#define X509_PURPOSE_OCSP_HELPER 8
#define X509_PURPOSE_TIMESTAMP_SIGN 9
#define X509_PURPOSE_MIN 1
#define X509_PURPOSE_MAX 9
#define X509V3_EXT_UNKNOWN_MASK (0xfL << 16)
#define X509V3_EXT_DEFAULT 0
#define X509V3_EXT_ERROR_UNKNOWN (1L << 16)
#define X509V3_EXT_PARSE_UNKNOWN (2L << 16)
#define X509V3_EXT_DUMP_UNKNOWN (3L << 16)
#define X509V3_ADD_OP_MASK 0xfL
#define X509V3_ADD_DEFAULT 0L
#define X509V3_ADD_APPEND 1L
#define X509V3_ADD_REPLACE 2L
#define X509V3_ADD_REPLACE_EXISTING 3L
#define X509V3_ADD_KEEP_EXISTING 4L
#define X509V3_ADD_DELETE 5L
#define X509V3_ADD_SILENT 0x10
#define hex_to_string OPENSSL_buf2hexstr
#define string_to_hex OPENSSL_hexstr2buf
#define X509_CHECK_FLAG_ALWAYS_CHECK_SUBJECT 0x1
#define X509_CHECK_FLAG_NO_WILDCARDS 0x2
#define X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS 0x4
#define X509_CHECK_FLAG_MULTI_LABEL_WILDCARDS 0x8
#define X509_CHECK_FLAG_SINGLE_LABEL_SUBDOMAINS 0x10
#define X509_CHECK_FLAG_NEVER_CHECK_SUBJECT 0x20
#define _X509_CHECK_FLAG_DOT_SUBDOMAINS 0x8000
#define ASIdOrRange_id 0
#define ASIdOrRange_range 1
#define ASIdentifierChoice_inherit 0
#define ASIdentifierChoice_asIdsOrRanges 1
#define IPAddressOrRange_addressPrefix 0
#define IPAddressOrRange_addressRange 1
#define IPAddressChoice_inherit 0
#define IPAddressChoice_addressesOrRanges 1
#define V3_ASID_ASNUM 0
#define V3_ASID_RDI 1
#define IANA_AFI_IPV4 1
#define IANA_AFI_IPV6 2
#define X509V3_F_A2I_GENERAL_NAME 164
#define X509V3_F_ADDR_VALIDATE_PATH_INTERNAL 166
#define X509V3_F_ASIDENTIFIERCHOICE_CANONIZE 161
#define X509V3_F_ASIDENTIFIERCHOICE_IS_CANONICAL 162
#define X509V3_F_COPY_EMAIL 122
#define X509V3_F_COPY_ISSUER 123
#define X509V3_F_DO_DIRNAME 144
#define X509V3_F_DO_EXT_I2D 135
#define X509V3_F_DO_EXT_NCONF 151
#define X509V3_F_GNAMES_FROM_SECTNAME 156
#define X509V3_F_I2S_ASN1_ENUMERATED 121
#define X509V3_F_I2S_ASN1_IA5STRING 149
#define X509V3_F_I2S_ASN1_INTEGER 120
#define X509V3_F_I2V_AUTHORITY_INFO_ACCESS 138
#define X509V3_F_NOTICE_SECTION 132
#define X509V3_F_NREF_NOS 133
#define X509V3_F_POLICY_SECTION 131
#define X509V3_F_PROCESS_PCI_VALUE 150
#define X509V3_F_R2I_CERTPOL 130
#define X509V3_F_R2I_PCI 155
#define X509V3_F_S2I_ASN1_IA5STRING 100
#define X509V3_F_S2I_ASN1_INTEGER 108
#define X509V3_F_S2I_ASN1_OCTET_STRING 112
#define X509V3_F_S2I_SKEY_ID 115
#define X509V3_F_SET_DIST_POINT_NAME 158
#define X509V3_F_SXNET_ADD_ID_ASC 125
#define X509V3_F_SXNET_ADD_ID_INTEGER 126
#define X509V3_F_SXNET_ADD_ID_ULONG 127
#define X509V3_F_SXNET_GET_ID_ASC 128
#define X509V3_F_SXNET_GET_ID_ULONG 129
#define X509V3_F_V2I_ASIDENTIFIERS 163
#define X509V3_F_V2I_ASN1_BIT_STRING 101
#define X509V3_F_V2I_AUTHORITY_INFO_ACCESS 139
#define X509V3_F_V2I_AUTHORITY_KEYID 119
#define X509V3_F_V2I_BASIC_CONSTRAINTS 102
#define X509V3_F_V2I_CRLD 134
#define X509V3_F_V2I_EXTENDED_KEY_USAGE 103
#define X509V3_F_V2I_GENERAL_NAMES 118
#define X509V3_F_V2I_GENERAL_NAME_EX 117
#define X509V3_F_V2I_IDP 157
#define X509V3_F_V2I_IPADDRBLOCKS 159
#define X509V3_F_V2I_ISSUER_ALT 153
#define X509V3_F_V2I_NAME_CONSTRAINTS 147
#define X509V3_F_V2I_POLICY_CONSTRAINTS 146
#define X509V3_F_V2I_POLICY_MAPPINGS 145
#define X509V3_F_V2I_SUBJECT_ALT 154
#define X509V3_F_V2I_TLS_FEATURE 165
#define X509V3_F_V3_GENERIC_EXTENSION 116
#define X509V3_F_X509V3_ADD1_I2D 140
#define X509V3_F_X509V3_ADD_VALUE 105
#define X509V3_F_X509V3_EXT_ADD 104
#define X509V3_F_X509V3_EXT_ADD_ALIAS 106
#define X509V3_F_X509V3_EXT_I2D 136
#define X509V3_F_X509V3_EXT_NCONF 152
#define X509V3_F_X509V3_GET_SECTION 142
#define X509V3_F_X509V3_GET_STRING 143
#define X509V3_F_X509V3_GET_VALUE_BOOL 110
#define X509V3_F_X509V3_PARSE_LIST 109
#define X509V3_F_X509_PURPOSE_ADD 137
#define X509V3_F_X509_PURPOSE_SET 141
#define X509V3_R_BAD_IP_ADDRESS 118
#define X509V3_R_BAD_OBJECT 119
#define X509V3_R_BN_DEC2BN_ERROR 100
#define X509V3_R_BN_TO_ASN1_INTEGER_ERROR 101
#define X509V3_R_DIRNAME_ERROR 149
#define X509V3_R_DISTPOINT_ALREADY_SET 160
#define X509V3_R_DUPLICATE_ZONE_ID 133
#define X509V3_R_ERROR_CONVERTING_ZONE 131
#define X509V3_R_ERROR_CREATING_EXTENSION 144
#define X509V3_R_ERROR_IN_EXTENSION 128
#define X509V3_R_EXPECTED_A_SECTION_NAME 137
#define X509V3_R_EXTENSION_EXISTS 145
#define X509V3_R_EXTENSION_NAME_ERROR 115
#define X509V3_R_EXTENSION_NOT_FOUND 102
#define X509V3_R_EXTENSION_SETTING_NOT_SUPPORTED 103
#define X509V3_R_EXTENSION_VALUE_ERROR 116
#define X509V3_R_ILLEGAL_EMPTY_EXTENSION 151
#define X509V3_R_INCORRECT_POLICY_SYNTAX_TAG 152
#define X509V3_R_INVALID_ASNUMBER 162
#define X509V3_R_INVALID_ASRANGE 163
#define X509V3_R_INVALID_BOOLEAN_STRING 104
#define X509V3_R_INVALID_EXTENSION_STRING 105
#define X509V3_R_INVALID_INHERITANCE 165
#define X509V3_R_INVALID_IPADDRESS 166
#define X509V3_R_INVALID_MULTIPLE_RDNS 161
#define X509V3_R_INVALID_NAME 106
#define X509V3_R_INVALID_NULL_ARGUMENT 107
#define X509V3_R_INVALID_NULL_NAME 108
#define X509V3_R_INVALID_NULL_VALUE 109
#define X509V3_R_INVALID_NUMBER 140
#define X509V3_R_INVALID_NUMBERS 141
#define X509V3_R_INVALID_OBJECT_IDENTIFIER 110
#define X509V3_R_INVALID_OPTION 138
#define X509V3_R_INVALID_POLICY_IDENTIFIER 134
#define X509V3_R_INVALID_PROXY_POLICY_SETTING 153
#define X509V3_R_INVALID_PURPOSE 146
#define X509V3_R_INVALID_SAFI 164
#define X509V3_R_INVALID_SECTION 135
#define X509V3_R_INVALID_SYNTAX 143
#define X509V3_R_ISSUER_DECODE_ERROR 126
#define X509V3_R_MISSING_VALUE 124
#define X509V3_R_NEED_ORGANIZATION_AND_NUMBERS 142
#define X509V3_R_NO_CONFIG_DATABASE 136
#define X509V3_R_NO_ISSUER_CERTIFICATE 121
#define X509V3_R_NO_ISSUER_DETAILS 127
#define X509V3_R_NO_POLICY_IDENTIFIER 139
#define X509V3_R_NO_PROXY_CERT_POLICY_LANGUAGE_DEFINED 154
#define X509V3_R_NO_PUBLIC_KEY 114
#define X509V3_R_NO_SUBJECT_DETAILS 125
#define X509V3_R_OPERATION_NOT_DEFINED 148
#define X509V3_R_OTHERNAME_ERROR 147
#define X509V3_R_POLICY_LANGUAGE_ALREADY_DEFINED 155
#define X509V3_R_POLICY_PATH_LENGTH 156
#define X509V3_R_POLICY_PATH_LENGTH_ALREADY_DEFINED 157
#define X509V3_R_POLICY_WHEN_PROXY_LANGUAGE_REQUIRES_NO_POLICY 159
#define X509V3_R_SECTION_NOT_FOUND 150
#define X509V3_R_UNABLE_TO_GET_ISSUER_DETAILS 122
#define X509V3_R_UNABLE_TO_GET_ISSUER_KEYID 123
#define X509V3_R_UNKNOWN_BIT_STRING_ARGUMENT 111
#define X509V3_R_UNKNOWN_EXTENSION 129
#define X509V3_R_UNKNOWN_EXTENSION_NAME 130
#define X509V3_R_UNKNOWN_OPTION 120
#define X509V3_R_UNSUPPORTED_OPTION 117
#define X509V3_R_UNSUPPORTED_TYPE 167
#define X509V3_R_USER_TOO_LONG 132
Typedefs
typedef void *(* X509V3_EXT_NEW) (void)
typedef void(* X509V3_EXT_FREE) (void *)
typedef void *(* X509V3_EXT_D2I) (void *, const unsigned char **, long)
typedef int(* X509V3_EXT_I2D) (void *, unsigned char **)
typedef void * ext
typedef void STACK_OF(CONF_VALUE) *extlist)
typedef void *(* X509V3_EXT_V2I) (const struct v3_ext_method *method, struct v3_ext_ctx *ctx, STACK_OF(CONF_VALUE) *values)
typedef char *(* X509V3_EXT_I2S) (const struct v3_ext_method *method, void *ext)
typedef void *(* X509V3_EXT_S2I) (const struct v3_ext_method *method, struct v3_ext_ctx *ctx, const char *str)
typedef int(* X509V3_EXT_I2R) (const struct v3_ext_method *method, void *ext, BIO *out, int indent)
typedef void *(* X509V3_EXT_R2I) (const struct v3_ext_method *method, struct v3_ext_ctx *ctx, const char *str)
typedef BIT_STRING_BITNAME ENUMERATED_NAMES
Functions
typedef STACK_OF (CONF_VALUE) *(*X509V3_EXT_I2V)(const struct v3_ext_method *method
typedef STACK_OF (ACCESS_DESCRIPTION) AUTHORITY_INFO_ACCESS
typedef STACK_OF (ASN1_OBJECT) EXTENDED_KEY_USAGE
typedef STACK_OF (ASN1_INTEGER) TLS_FEATURE
typedef STACK_OF (GENERAL_NAME) GENERAL_NAMES
typedef STACK_OF (DIST_POINT) CRL_DIST_POINTS
typedef STACK_OF (POLICYINFO) CERTIFICATEPOLICIES
typedef STACK_OF (POLICY_MAPPING) POLICY_MAPPINGS
int SXNET_add_id_asc (SXNET **psx, const char *zone, const char *user, int userlen)
int SXNET_add_id_ulong (SXNET **psx, unsigned long lzone, const char *user, int userlen)
int SXNET_add_id_INTEGER (SXNET **psx, ASN1_INTEGER *izone, const char *user, int userlen)
ASN1_OCTET_STRING * SXNET_get_id_asc (SXNET *sx, const char *zone)
ASN1_OCTET_STRING * SXNET_get_id_ulong (SXNET *sx, unsigned long lzone)
ASN1_OCTET_STRING * SXNET_get_id_INTEGER (SXNET *sx, ASN1_INTEGER *zone)
GENERAL_NAME * GENERAL_NAME_dup (GENERAL_NAME *a)
int GENERAL_NAME_cmp (GENERAL_NAME *a, GENERAL_NAME *b)
ASN1_BIT_STRING * v2i_ASN1_BIT_STRING (X509V3_EXT_METHOD *method, X509V3_CTX *ctx, STACK_OF(CONF_VALUE) *nval)
char * i2s_ASN1_IA5STRING (X509V3_EXT_METHOD *method, ASN1_IA5STRING *ia5)
ASN1_IA5STRING * s2i_ASN1_IA5STRING (X509V3_EXT_METHOD *method, X509V3_CTX *ctx, const char *str)
int GENERAL_NAME_print (BIO *out, GENERAL_NAME *gen)
GENERAL_NAMES * v2i_GENERAL_NAMES (const X509V3_EXT_METHOD *method, X509V3_CTX *ctx, STACK_OF(CONF_VALUE) *nval)
int OTHERNAME_cmp (OTHERNAME *a, OTHERNAME *b)
void GENERAL_NAME_set0_value (GENERAL_NAME *a, int type, void *value)
void * GENERAL_NAME_get0_value (GENERAL_NAME *a, int *ptype)
int GENERAL_NAME_set0_othername (GENERAL_NAME *gen, ASN1_OBJECT *oid, ASN1_TYPE *value)
int GENERAL_NAME_get0_otherName (GENERAL_NAME *gen, ASN1_OBJECT **poid, ASN1_TYPE **pvalue)
char * i2s_ASN1_OCTET_STRING (X509V3_EXT_METHOD *method, const ASN1_OCTET_STRING *ia5)
ASN1_OCTET_STRING * s2i_ASN1_OCTET_STRING (X509V3_EXT_METHOD *method, X509V3_CTX *ctx, const char *str)
int i2a_ACCESS_DESCRIPTION (BIO *bp, const ACCESS_DESCRIPTION *a)
int DIST_POINT_set_dpname (DIST_POINT_NAME *dpn, X509_NAME *iname)
int NAME_CONSTRAINTS_check (X509 *x, NAME_CONSTRAINTS *nc)
int NAME_CONSTRAINTS_check_CN (X509 *x, NAME_CONSTRAINTS *nc)
GENERAL_NAME * a2i_GENERAL_NAME (GENERAL_NAME *out, const X509V3_EXT_METHOD *method, X509V3_CTX *ctx, int gen_type, const char *value, int is_nc)
char * X509V3_get_string (X509V3_CTX *ctx, const char *name, const char *section)
void X509V3_string_free (X509V3_CTX *ctx, char *str)
void X509V3_section_free (X509V3_CTX *ctx, STACK_OF(CONF_VALUE) *section)
void X509V3_set_ctx (X509V3_CTX *ctx, X509 *issuer, X509 *subject, X509_REQ *req, X509_CRL *crl, int flags)
int X509V3_add_value (const char *name, const char *value, STACK_OF(CONF_VALUE) **extlist)
int X509V3_add_value_uchar (const char *name, const unsigned char *value, STACK_OF(CONF_VALUE) **extlist)
int X509V3_add_value_bool (const char *name, int asn1_bool, STACK_OF(CONF_VALUE) **extlist)
int X509V3_add_value_int (const char *name, const ASN1_INTEGER *aint, STACK_OF(CONF_VALUE) **extlist)
char * i2s_ASN1_INTEGER (X509V3_EXT_METHOD *meth, const ASN1_INTEGER *aint)
ASN1_INTEGER * s2i_ASN1_INTEGER (X509V3_EXT_METHOD *meth, const char *value)
char * i2s_ASN1_ENUMERATED (X509V3_EXT_METHOD *meth, const ASN1_ENUMERATED *aint)
char * i2s_ASN1_ENUMERATED_TABLE (X509V3_EXT_METHOD *meth, const ASN1_ENUMERATED *aint)
int X509V3_EXT_add (X509V3_EXT_METHOD *ext)
int X509V3_EXT_add_list (X509V3_EXT_METHOD *extlist)
int X509V3_EXT_add_alias (int nid_to, int nid_from)
void X509V3_EXT_cleanup (void)
const X509V3_EXT_METHOD * X509V3_EXT_get (X509_EXTENSION *ext)
const X509V3_EXT_METHOD * X509V3_EXT_get_nid (int nid)
int X509V3_add_standard_extensions (void)
void * X509V3_EXT_d2i (X509_EXTENSION *ext)
void * X509V3_get_d2i (const STACK_OF(X509_EXTENSION) *x, int nid, int *crit, int *idx)
X509_EXTENSION * X509V3_EXT_i2d (int ext_nid, int crit, void *ext_struc)
int X509V3_add1_i2d (STACK_OF(X509_EXTENSION) **x, int nid, void *value, int crit, unsigned long flags)
void X509V3_EXT_val_prn (BIO *out, STACK_OF(CONF_VALUE) *val, int indent, int ml)
int X509V3_EXT_print (BIO *out, X509_EXTENSION *ext, unsigned long flag, int indent)
int X509V3_EXT_print_fp (FILE *out, X509_EXTENSION *ext, int flag, int indent)
int X509V3_extensions_print (BIO *out, const char *title, const STACK_OF(X509_EXTENSION) *exts, unsigned long flag, int indent)
int X509_check_ca (X509 *x)
int X509_check_purpose (X509 *x, int id, int ca)
int X509_supported_extension (X509_EXTENSION *ex)
int X509_PURPOSE_set (int *p, int purpose)
int X509_check_issued (X509 *issuer, X509 *subject)
int X509_check_akid (X509 *issuer, AUTHORITY_KEYID *akid)
void X509_set_proxy_flag (X509 *x)
void X509_set_proxy_pathlen (X509 *x, long l)
long X509_get_proxy_pathlen (X509 *x)
uint32_t X509_get_extension_flags (X509 *x)
uint32_t X509_get_key_usage (X509 *x)
uint32_t X509_get_extended_key_usage (X509 *x)
const ASN1_OCTET_STRING * X509_get0_subject_key_id (X509 *x)
int X509_PURPOSE_get_count (void)
X509_PURPOSE * X509_PURPOSE_get0 (int idx)
int X509_PURPOSE_get_by_sname (const char *sname)
int X509_PURPOSE_get_by_id (int id)
int X509_PURPOSE_add (int id, int trust, int flags, int(*ck)(const X509_PURPOSE *, const X509 *, int), const char *name, const char *sname, void *arg)
char * X509_PURPOSE_get0_name (const X509_PURPOSE *xp)
char * X509_PURPOSE_get0_sname (const X509_PURPOSE *xp)
int X509_PURPOSE_get_trust (const X509_PURPOSE *xp)
void X509_PURPOSE_cleanup (void)
int X509_PURPOSE_get_id (const X509_PURPOSE *)
STACK_OF (OPENSSL_STRING) *X509_get1_email(X509 *x)
void X509_email_free (STACK_OF(OPENSSL_STRING) *sk)
int X509_check_host (X509 *x, const char *chk, size_t chklen, unsigned int flags, char **peername)
int X509_check_email (X509 *x, const char *chk, size_t chklen, unsigned int flags)
int X509_check_ip (X509 *x, const unsigned char *chk, size_t chklen, unsigned int flags)
int X509_check_ip_asc (X509 *x, const char *ipasc, unsigned int flags)
ASN1_OCTET_STRING * a2i_IPADDRESS (const char *ipasc)
ASN1_OCTET_STRING * a2i_IPADDRESS_NC (const char *ipasc)
int X509V3_NAME_from_section (X509_NAME *nm, STACK_OF(CONF_VALUE) *dn_sk, unsigned long chtype)
void X509_POLICY_NODE_print (BIO *out, X509_POLICY_NODE *node, int indent)
typedef STACK_OF (ASIdOrRange) ASIdOrRanges
typedef STACK_OF (IPAddressOrRange) IPAddressOrRanges
typedef STACK_OF (IPAddressFamily) IPAddrBlocks
int X509v3_asid_add_inherit (ASIdentifiers *asid, int which)
int X509v3_asid_add_id_or_range (ASIdentifiers *asid, int which, ASN1_INTEGER *min, ASN1_INTEGER *max)
int X509v3_addr_add_inherit (IPAddrBlocks *addr, const unsigned afi, const unsigned *safi)
int X509v3_addr_add_prefix (IPAddrBlocks *addr, const unsigned afi, const unsigned *safi, unsigned char *a, const int prefixlen)
int X509v3_addr_add_range (IPAddrBlocks *addr, const unsigned afi, const unsigned *safi, unsigned char *min, unsigned char *max)
unsigned X509v3_addr_get_afi (const IPAddressFamily *f)
int X509v3_addr_get_range (IPAddressOrRange *aor, const unsigned afi, unsigned char *min, unsigned char *max, const int length)
int X509v3_asid_is_canonical (ASIdentifiers *asid)
int X509v3_addr_is_canonical (IPAddrBlocks *addr)
int X509v3_asid_canonize (ASIdentifiers *asid)
int X509v3_addr_canonize (IPAddrBlocks *addr)
int X509v3_asid_inherits (ASIdentifiers *asid)
int X509v3_addr_inherits (IPAddrBlocks *addr)
int X509v3_asid_subset (ASIdentifiers *a, ASIdentifiers *b)
int X509v3_addr_subset (IPAddrBlocks *a, IPAddrBlocks *b)
int X509v3_asid_validate_path (X509_STORE_CTX *)
int X509v3_addr_validate_path (X509_STORE_CTX *)
int X509v3_asid_validate_resource_set (STACK_OF(X509) *chain, ASIdentifiers *ext, int allow_inheritance)
int X509v3_addr_validate_resource_set (STACK_OF(X509) *chain, IPAddrBlocks *ext, int allow_inheritance)
int ERR_load_X509V3_strings (void)
Variables
ASN1_BIT_STRING * bits
GENERAL_NAME * gen
const char * section
Macro Definition Documentation
_X509_CHECK_FLAG_DOT_SUBDOMAINS
#define _X509_CHECK_FLAG_DOT_SUBDOMAINS 0x8000
Definition at line 700 of file x509v3.h.
ASIdentifierChoice_asIdsOrRanges
#define ASIdentifierChoice_asIdsOrRanges 1
Definition at line 738 of file x509v3.h.
ASIdentifierChoice_inherit
#define ASIdentifierChoice_inherit 0
Definition at line 737 of file x509v3.h.
Referenced by X509v3_asid_inherits().
ASIdOrRange_id
#define ASIdOrRange_id 0
Definition at line 723 of file x509v3.h.
ASIdOrRange_range
#define ASIdOrRange_range 1
Definition at line 724 of file x509v3.h.
CRL_REASON_AA_COMPROMISE
#define CRL_REASON_AA_COMPROMISE 10
Definition at line 193 of file x509v3.h.
CRL_REASON_AFFILIATION_CHANGED
#define CRL_REASON_AFFILIATION_CHANGED 3
Definition at line 187 of file x509v3.h.
CRL_REASON_CA_COMPROMISE
#define CRL_REASON_CA_COMPROMISE 2
Definition at line 186 of file x509v3.h.
CRL_REASON_CERTIFICATE_HOLD
#define CRL_REASON_CERTIFICATE_HOLD 6
Definition at line 190 of file x509v3.h.
CRL_REASON_CESSATION_OF_OPERATION
#define CRL_REASON_CESSATION_OF_OPERATION 5
Definition at line 189 of file x509v3.h.
CRL_REASON_KEY_COMPROMISE
#define CRL_REASON_KEY_COMPROMISE 1
Definition at line 185 of file x509v3.h.
CRL_REASON_NONE
#define CRL_REASON_NONE -1
Definition at line 183 of file x509v3.h.
CRL_REASON_PRIVILEGE_WITHDRAWN
#define CRL_REASON_PRIVILEGE_WITHDRAWN 9
Definition at line 192 of file x509v3.h.
CRL_REASON_REMOVE_FROM_CRL
#define CRL_REASON_REMOVE_FROM_CRL 8
Definition at line 191 of file x509v3.h.
CRL_REASON_SUPERSEDED
#define CRL_REASON_SUPERSEDED 4
Definition at line 188 of file x509v3.h.
CRL_REASON_UNSPECIFIED
#define CRL_REASON_UNSPECIFIED 0
Definition at line 184 of file x509v3.h.
CRLDP_ALL_REASONS
#define CRLDP_ALL_REASONS 0x807f
Definition at line 181 of file x509v3.h.
CTX_TEST
#define CTX_TEST 0x1
Definition at line 79 of file x509v3.h.
EXFLAG_BCONS
#define EXFLAG_BCONS 0x1
Definition at line 348 of file x509v3.h.
Referenced by X509_get_pathlen().
EXFLAG_CA
#define EXFLAG_CA 0x10
Definition at line 353 of file x509v3.h.
EXFLAG_CRITICAL
#define EXFLAG_CRITICAL 0x200
Definition at line 360 of file x509v3.h.
EXFLAG_FRESHEST
#define EXFLAG_FRESHEST 0x1000
Definition at line 364 of file x509v3.h.
EXFLAG_INVALID
#define EXFLAG_INVALID 0x80
Definition at line 357 of file x509v3.h.
EXFLAG_INVALID_POLICY
#define EXFLAG_INVALID_POLICY 0x800
Definition at line 363 of file x509v3.h.
EXFLAG_KUSAGE
#define EXFLAG_KUSAGE 0x2
Definition at line 349 of file x509v3.h.
Referenced by X509_get_key_usage().
EXFLAG_NSCERT
#define EXFLAG_NSCERT 0x8
Definition at line 351 of file x509v3.h.
EXFLAG_PROXY
#define EXFLAG_PROXY 0x400
Definition at line 361 of file x509v3.h.
Referenced by X509_get_proxy_pathlen(), and X509_set_proxy_flag().
EXFLAG_SET
#define EXFLAG_SET 0x100
Definition at line 359 of file x509v3.h.
Referenced by X509_check_ca().
EXFLAG_SI
#define EXFLAG_SI 0x20
Definition at line 355 of file x509v3.h.
EXFLAG_SS
#define EXFLAG_SS 0x2000
Definition at line 366 of file x509v3.h.
Referenced by ssl_build_cert_chain().
EXFLAG_V1
#define EXFLAG_V1 0x40
Definition at line 356 of file x509v3.h.
EXFLAG_XKUSAGE
#define EXFLAG_XKUSAGE 0x4
Definition at line 350 of file x509v3.h.
Referenced by X509_get_extended_key_usage().
EXT_BITSTRING
#define EXT_BITSTRING (nid, table)
Value:
{ nid, 0, ASN1_ITEM_ref(ASN1_BIT_STRING), \
                        0,0,0,0, \
                        0,0, \
                        (X509V3_EXT_I2V)i2v_ASN1_BIT_STRING, \
                        (X509V3_EXT_V2I)v2i_ASN1_BIT_STRING, \
                        NULL, NULL, \
                        table}
Definition at line 329 of file x509v3.h.
EXT_END
#define EXT_END { -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
Definition at line 344 of file x509v3.h.
EXT_IA5STRING
#define EXT_IA5STRING (nid)
Value:
{ nid, 0, ASN1_ITEM_ref(ASN1_IA5STRING), \
                        0,0,0,0, \
                        (X509V3_EXT_I2S)i2s_ASN1_IA5STRING, \
                        (X509V3_EXT_S2I)s2i_ASN1_IA5STRING, \
                        0,0,0,0, \
                        NULL}
Definition at line 337 of file x509v3.h.
GEN_DIRNAME
#define GEN_DIRNAME 4
Definition at line 127 of file x509v3.h.
Referenced by OCSP_request_set1_name(), OCSP_request_verify(), and X509_check_akid().
GEN_DNS
#define GEN_DNS 2
Definition at line 125 of file x509v3.h.
GEN_EDIPARTY
#define GEN_EDIPARTY 5
Definition at line 128 of file x509v3.h.
GEN_EMAIL
#define GEN_EMAIL 1
Definition at line 124 of file x509v3.h.
GEN_IPADD
#define GEN_IPADD 7
Definition at line 130 of file x509v3.h.
GEN_OTHERNAME
#define GEN_OTHERNAME 0
Definition at line 123 of file x509v3.h.
GEN_RID
#define GEN_RID 8
Definition at line 131 of file x509v3.h.
GEN_URI
#define GEN_URI 6
Definition at line 129 of file x509v3.h.
Referenced by OCSP_url_svcloc_new().
GEN_X400
#define GEN_X400 3
Definition at line 126 of file x509v3.h.
hex_to_string
#define hex_to_string OPENSSL_buf2hexstr
Definition at line 632 of file x509v3.h.
IANA_AFI_IPV4
#define IANA_AFI_IPV4 1
Definition at line 811 of file x509v3.h.
IANA_AFI_IPV6
#define IANA_AFI_IPV6 2
Definition at line 812 of file x509v3.h.
IDP_INDIRECT
#define IDP_INDIRECT 0x20
Definition at line 318 of file x509v3.h.
IDP_INVALID
#define IDP_INVALID 0x2
Definition at line 310 of file x509v3.h.
IDP_ONLYATTR
#define IDP_ONLYATTR 0x10
Definition at line 316 of file x509v3.h.
IDP_ONLYCA
#define IDP_ONLYCA 0x8
Definition at line 314 of file x509v3.h.
IDP_ONLYUSER
#define IDP_ONLYUSER 0x4
Definition at line 312 of file x509v3.h.
IDP_PRESENT
#define IDP_PRESENT 0x1
Definition at line 308 of file x509v3.h.
IDP_REASONS
#define IDP_REASONS 0x40
Definition at line 320 of file x509v3.h.
IPAddressChoice_addressesOrRanges
#define IPAddressChoice_addressesOrRanges 1
Definition at line 776 of file x509v3.h.
IPAddressChoice_inherit
#define IPAddressChoice_inherit 0
Definition at line 775 of file x509v3.h.
Referenced by X509v3_addr_inherits().
IPAddressOrRange_addressPrefix
#define IPAddressOrRange_addressPrefix 0
Definition at line 761 of file x509v3.h.
IPAddressOrRange_addressRange
#define IPAddressOrRange_addressRange 1
Definition at line 762 of file x509v3.h.
KU_CRL_SIGN
#define KU_CRL_SIGN 0x0002
Definition at line 374 of file x509v3.h.
KU_DATA_ENCIPHERMENT
#define KU_DATA_ENCIPHERMENT 0x0010
Definition at line 371 of file x509v3.h.
KU_DECIPHER_ONLY
#define KU_DECIPHER_ONLY 0x8000
Definition at line 376 of file x509v3.h.
KU_DIGITAL_SIGNATURE
#define KU_DIGITAL_SIGNATURE 0x0080
Definition at line 368 of file x509v3.h.
KU_ENCIPHER_ONLY
#define KU_ENCIPHER_ONLY 0x0001
Definition at line 375 of file x509v3.h.
KU_KEY_AGREEMENT
#define KU_KEY_AGREEMENT 0x0008
Definition at line 372 of file x509v3.h.
KU_KEY_CERT_SIGN
#define KU_KEY_CERT_SIGN 0x0004
Definition at line 373 of file x509v3.h.
KU_KEY_ENCIPHERMENT
#define KU_KEY_ENCIPHERMENT 0x0020
Definition at line 370 of file x509v3.h.
KU_NON_REPUDIATION
#define KU_NON_REPUDIATION 0x0040
Definition at line 369 of file x509v3.h.
NS_ANY_CA
#define NS_ANY_CA (NS_SSL_CA|NS_SMIME_CA|NS_OBJSIGN_CA)
Definition at line 385 of file x509v3.h.
NS_OBJSIGN
#define NS_OBJSIGN 0x10
Definition at line 381 of file x509v3.h.
NS_OBJSIGN_CA
#define NS_OBJSIGN_CA 0x01
Definition at line 384 of file x509v3.h.
NS_SMIME
#define NS_SMIME 0x20
Definition at line 380 of file x509v3.h.
NS_SMIME_CA
#define NS_SMIME_CA 0x02
Definition at line 383 of file x509v3.h.
NS_SSL_CA
#define NS_SSL_CA 0x04
Definition at line 382 of file x509v3.h.
NS_SSL_CLIENT
#define NS_SSL_CLIENT 0x80
Definition at line 378 of file x509v3.h.
NS_SSL_SERVER
#define NS_SSL_SERVER 0x40
Definition at line 379 of file x509v3.h.
string_to_hex
#define string_to_hex OPENSSL_hexstr2buf
Definition at line 633 of file x509v3.h.
V3_ASID_ASNUM
#define V3_ASID_ASNUM 0
Definition at line 802 of file x509v3.h.
V3_ASID_RDI
#define V3_ASID_RDI 1
Definition at line 803 of file x509v3.h.
X509_CHECK_FLAG_ALWAYS_CHECK_SUBJECT
#define X509_CHECK_FLAG_ALWAYS_CHECK_SUBJECT 0x1
Definition at line 684 of file x509v3.h.
X509_CHECK_FLAG_MULTI_LABEL_WILDCARDS
#define X509_CHECK_FLAG_MULTI_LABEL_WILDCARDS 0x8
Definition at line 690 of file x509v3.h.
X509_CHECK_FLAG_NEVER_CHECK_SUBJECT
#define X509_CHECK_FLAG_NEVER_CHECK_SUBJECT 0x20
Definition at line 694 of file x509v3.h.
X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS
#define X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS 0x4
Definition at line 688 of file x509v3.h.
X509_CHECK_FLAG_NO_WILDCARDS
#define X509_CHECK_FLAG_NO_WILDCARDS 0x2
Definition at line 686 of file x509v3.h.
X509_CHECK_FLAG_SINGLE_LABEL_SUBDOMAINS
#define X509_CHECK_FLAG_SINGLE_LABEL_SUBDOMAINS 0x10
Definition at line 692 of file x509v3.h.
X509_PURPOSE_ANY
#define X509_PURPOSE_ANY 7
Definition at line 416 of file x509v3.h.
X509_PURPOSE_CRL_SIGN
#define X509_PURPOSE_CRL_SIGN 6
Definition at line 415 of file x509v3.h.
X509_PURPOSE_DYNAMIC
#define X509_PURPOSE_DYNAMIC 0x1
Definition at line 397 of file x509v3.h.
X509_PURPOSE_DYNAMIC_NAME
#define X509_PURPOSE_DYNAMIC_NAME 0x2
Definition at line 398 of file x509v3.h.
X509_PURPOSE_MAX
#define X509_PURPOSE_MAX 9
Definition at line 421 of file x509v3.h.
X509_PURPOSE_MIN
#define X509_PURPOSE_MIN 1
Definition at line 420 of file x509v3.h.
X509_PURPOSE_NS_SSL_SERVER
#define X509_PURPOSE_NS_SSL_SERVER 3
Definition at line 412 of file x509v3.h.
X509_PURPOSE_OCSP_HELPER
#define X509_PURPOSE_OCSP_HELPER 8
Definition at line 417 of file x509v3.h.
X509_PURPOSE_SMIME_ENCRYPT
#define X509_PURPOSE_SMIME_ENCRYPT 5
Definition at line 414 of file x509v3.h.
X509_PURPOSE_SMIME_SIGN
#define X509_PURPOSE_SMIME_SIGN 4
Definition at line 413 of file x509v3.h.
X509_PURPOSE_SSL_CLIENT
#define X509_PURPOSE_SSL_CLIENT 1
Definition at line 410 of file x509v3.h.
X509_PURPOSE_SSL_SERVER
#define X509_PURPOSE_SSL_SERVER 2
Definition at line 411 of file x509v3.h.
X509_PURPOSE_TIMESTAMP_SIGN
#define X509_PURPOSE_TIMESTAMP_SIGN 9
Definition at line 418 of file x509v3.h.
Referenced by TS_RESP_CTX_set_signer_cert().
X509V3_ADD_APPEND
#define X509V3_ADD_APPEND 1L
Definition at line 439 of file x509v3.h.
X509V3_ADD_DEFAULT
#define X509V3_ADD_DEFAULT 0L
Definition at line 438 of file x509v3.h.
X509V3_ADD_DELETE
#define X509V3_ADD_DELETE 5L
Definition at line 443 of file x509v3.h.
X509V3_ADD_KEEP_EXISTING
#define X509V3_ADD_KEEP_EXISTING 4L
Definition at line 442 of file x509v3.h.
X509V3_ADD_OP_MASK
#define X509V3_ADD_OP_MASK 0xfL
Definition at line 437 of file x509v3.h.
X509V3_ADD_REPLACE
#define X509V3_ADD_REPLACE 2L
Definition at line 440 of file x509v3.h.
X509V3_ADD_REPLACE_EXISTING
#define X509V3_ADD_REPLACE_EXISTING 3L
Definition at line 441 of file x509v3.h.
X509V3_ADD_SILENT
#define X509V3_ADD_SILENT 0x10
Definition at line 444 of file x509v3.h.
X509V3_conf_err
#define X509V3_conf_err (val)
Value:
ERR_add_error_data(6, "section:", val->section, \
",name:", val->name, ",value:", val->value);
Definition at line 322 of file x509v3.h.
Referenced by v2i_ASN1_BIT_STRING(), X509V3_get_value_bool(), and X509V3_get_value_int().
X509V3_CTX_REPLACE
#define X509V3_CTX_REPLACE 0x2
Definition at line 80 of file x509v3.h.
X509V3_EXT_CTX_DEP
#define X509V3_EXT_CTX_DEP 0x2
Definition at line 97 of file x509v3.h.
X509V3_EXT_DEFAULT
#define X509V3_EXT_DEFAULT 0
Definition at line 427 of file x509v3.h.
X509V3_EXT_DUMP_UNKNOWN
#define X509V3_EXT_DUMP_UNKNOWN (3L << 16)
Definition at line 433 of file x509v3.h.
X509V3_EXT_DYNAMIC
#define X509V3_EXT_DYNAMIC 0x1
Definition at line 96 of file x509v3.h.
Referenced by X509V3_EXT_add_alias().
X509V3_EXT_ERROR_UNKNOWN
#define X509V3_EXT_ERROR_UNKNOWN (1L << 16)
Definition at line 429 of file x509v3.h.
X509V3_EXT_MULTILINE
#define X509V3_EXT_MULTILINE 0x4
Definition at line 98 of file x509v3.h.
X509V3_EXT_PARSE_UNKNOWN
#define X509V3_EXT_PARSE_UNKNOWN (2L << 16)
Definition at line 431 of file x509v3.h.
X509V3_EXT_UNKNOWN_MASK
#define X509V3_EXT_UNKNOWN_MASK (0xfL << 16)
Definition at line 425 of file x509v3.h.
X509V3_F_A2I_GENERAL_NAME
#define X509V3_F_A2I_GENERAL_NAME 164
Definition at line 875 of file x509v3.h.
X509V3_F_ADDR_VALIDATE_PATH_INTERNAL
#define X509V3_F_ADDR_VALIDATE_PATH_INTERNAL 166
Definition at line 876 of file x509v3.h.
X509V3_F_ASIDENTIFIERCHOICE_CANONIZE
#define X509V3_F_ASIDENTIFIERCHOICE_CANONIZE 161
Definition at line 877 of file x509v3.h.
X509V3_F_ASIDENTIFIERCHOICE_IS_CANONICAL
#define X509V3_F_ASIDENTIFIERCHOICE_IS_CANONICAL 162
Definition at line 878 of file x509v3.h.
X509V3_F_COPY_EMAIL
#define X509V3_F_COPY_EMAIL 122
Definition at line 879 of file x509v3.h.
X509V3_F_COPY_ISSUER
#define X509V3_F_COPY_ISSUER 123
Definition at line 880 of file x509v3.h.
X509V3_F_DO_DIRNAME
#define X509V3_F_DO_DIRNAME 144
Definition at line 881 of file x509v3.h.
X509V3_F_DO_EXT_I2D
#define X509V3_F_DO_EXT_I2D 135
Definition at line 882 of file x509v3.h.
X509V3_F_DO_EXT_NCONF
#define X509V3_F_DO_EXT_NCONF 151
Definition at line 883 of file x509v3.h.
X509V3_F_GNAMES_FROM_SECTNAME
#define X509V3_F_GNAMES_FROM_SECTNAME 156
Definition at line 884 of file x509v3.h.
X509V3_F_I2S_ASN1_ENUMERATED
#define X509V3_F_I2S_ASN1_ENUMERATED 121
Definition at line 885 of file x509v3.h.
Referenced by i2s_ASN1_ENUMERATED().
X509V3_F_I2S_ASN1_IA5STRING
#define X509V3_F_I2S_ASN1_IA5STRING 149
Definition at line 886 of file x509v3.h.
Referenced by i2s_ASN1_IA5STRING().
X509V3_F_I2S_ASN1_INTEGER
#define X509V3_F_I2S_ASN1_INTEGER 120
Definition at line 887 of file x509v3.h.
Referenced by i2s_ASN1_INTEGER().
X509V3_F_I2V_AUTHORITY_INFO_ACCESS
#define X509V3_F_I2V_AUTHORITY_INFO_ACCESS 138
Definition at line 888 of file x509v3.h.
X509V3_F_NOTICE_SECTION
#define X509V3_F_NOTICE_SECTION 132
Definition at line 889 of file x509v3.h.
X509V3_F_NREF_NOS
#define X509V3_F_NREF_NOS 133
Definition at line 890 of file x509v3.h.
X509V3_F_POLICY_SECTION
#define X509V3_F_POLICY_SECTION 131
Definition at line 891 of file x509v3.h.
X509V3_F_PROCESS_PCI_VALUE
#define X509V3_F_PROCESS_PCI_VALUE 150
Definition at line 892 of file x509v3.h.
X509V3_F_R2I_CERTPOL
#define X509V3_F_R2I_CERTPOL 130
Definition at line 893 of file x509v3.h.
X509V3_F_R2I_PCI
#define X509V3_F_R2I_PCI 155
Definition at line 894 of file x509v3.h.
X509V3_F_S2I_ASN1_IA5STRING
#define X509V3_F_S2I_ASN1_IA5STRING 100
Definition at line 895 of file x509v3.h.
Referenced by s2i_ASN1_IA5STRING().
X509V3_F_S2I_ASN1_INTEGER
#define X509V3_F_S2I_ASN1_INTEGER 108
Definition at line 896 of file x509v3.h.
X509V3_F_S2I_ASN1_OCTET_STRING
#define X509V3_F_S2I_ASN1_OCTET_STRING 112
Definition at line 897 of file x509v3.h.
Referenced by s2i_ASN1_OCTET_STRING().
X509V3_F_S2I_SKEY_ID
#define X509V3_F_S2I_SKEY_ID 115
Definition at line 898 of file x509v3.h.
X509V3_F_SET_DIST_POINT_NAME
#define X509V3_F_SET_DIST_POINT_NAME 158
Definition at line 899 of file x509v3.h.
X509V3_F_SXNET_ADD_ID_ASC
#define X509V3_F_SXNET_ADD_ID_ASC 125
Definition at line 900 of file x509v3.h.
X509V3_F_SXNET_ADD_ID_INTEGER
#define X509V3_F_SXNET_ADD_ID_INTEGER 126
Definition at line 901 of file x509v3.h.
X509V3_F_SXNET_ADD_ID_ULONG
#define X509V3_F_SXNET_ADD_ID_ULONG 127
Definition at line 902 of file x509v3.h.
X509V3_F_SXNET_GET_ID_ASC
#define X509V3_F_SXNET_GET_ID_ASC 128
Definition at line 903 of file x509v3.h.
X509V3_F_SXNET_GET_ID_ULONG
#define X509V3_F_SXNET_GET_ID_ULONG 129
Definition at line 904 of file x509v3.h.
X509V3_F_V2I_ASIDENTIFIERS
#define X509V3_F_V2I_ASIDENTIFIERS 163
Definition at line 905 of file x509v3.h.
X509V3_F_V2I_ASN1_BIT_STRING
#define X509V3_F_V2I_ASN1_BIT_STRING 101
Definition at line 906 of file x509v3.h.
Referenced by v2i_ASN1_BIT_STRING().
X509V3_F_V2I_AUTHORITY_INFO_ACCESS
#define X509V3_F_V2I_AUTHORITY_INFO_ACCESS 139
Definition at line 907 of file x509v3.h.
X509V3_F_V2I_AUTHORITY_KEYID
#define X509V3_F_V2I_AUTHORITY_KEYID 119
Definition at line 908 of file x509v3.h.
X509V3_F_V2I_BASIC_CONSTRAINTS
#define X509V3_F_V2I_BASIC_CONSTRAINTS 102
Definition at line 909 of file x509v3.h.
X509V3_F_V2I_CRLD
#define X509V3_F_V2I_CRLD 134
Definition at line 910 of file x509v3.h.
X509V3_F_V2I_EXTENDED_KEY_USAGE
#define X509V3_F_V2I_EXTENDED_KEY_USAGE 103
Definition at line 911 of file x509v3.h.
X509V3_F_V2I_GENERAL_NAME_EX
#define X509V3_F_V2I_GENERAL_NAME_EX 117
Definition at line 913 of file x509v3.h.
X509V3_F_V2I_GENERAL_NAMES
#define X509V3_F_V2I_GENERAL_NAMES 118
Definition at line 912 of file x509v3.h.
Referenced by v2i_GENERAL_NAMES().
X509V3_F_V2I_IDP
#define X509V3_F_V2I_IDP 157
Definition at line 914 of file x509v3.h.
X509V3_F_V2I_IPADDRBLOCKS
#define X509V3_F_V2I_IPADDRBLOCKS 159
Definition at line 915 of file x509v3.h.
X509V3_F_V2I_ISSUER_ALT
#define X509V3_F_V2I_ISSUER_ALT 153
Definition at line 916 of file x509v3.h.
X509V3_F_V2I_NAME_CONSTRAINTS
#define X509V3_F_V2I_NAME_CONSTRAINTS 147
Definition at line 917 of file x509v3.h.
X509V3_F_V2I_POLICY_CONSTRAINTS
#define X509V3_F_V2I_POLICY_CONSTRAINTS 146
Definition at line 918 of file x509v3.h.
X509V3_F_V2I_POLICY_MAPPINGS
#define X509V3_F_V2I_POLICY_MAPPINGS 145
Definition at line 919 of file x509v3.h.
X509V3_F_V2I_SUBJECT_ALT
#define X509V3_F_V2I_SUBJECT_ALT 154
Definition at line 920 of file x509v3.h.
X509V3_F_V2I_TLS_FEATURE
#define X509V3_F_V2I_TLS_FEATURE 165
Definition at line 921 of file x509v3.h.
X509V3_F_V3_GENERIC_EXTENSION
#define X509V3_F_V3_GENERIC_EXTENSION 116
Definition at line 922 of file x509v3.h.
X509V3_F_X509_PURPOSE_ADD
#define X509V3_F_X509_PURPOSE_ADD 137
Definition at line 933 of file x509v3.h.
X509V3_F_X509_PURPOSE_SET
#define X509V3_F_X509_PURPOSE_SET 141
Definition at line 934 of file x509v3.h.
Referenced by X509_PURPOSE_set().
X509V3_F_X509V3_ADD1_I2D
#define X509V3_F_X509V3_ADD1_I2D 140
Definition at line 923 of file x509v3.h.
X509V3_F_X509V3_ADD_VALUE
#define X509V3_F_X509V3_ADD_VALUE 105
Definition at line 924 of file x509v3.h.
X509V3_F_X509V3_EXT_ADD
#define X509V3_F_X509V3_EXT_ADD 104
Definition at line 925 of file x509v3.h.
X509V3_F_X509V3_EXT_ADD_ALIAS
#define X509V3_F_X509V3_EXT_ADD_ALIAS 106
Definition at line 926 of file x509v3.h.
Referenced by X509V3_EXT_add_alias().
X509V3_F_X509V3_EXT_I2D
#define X509V3_F_X509V3_EXT_I2D 136
Definition at line 927 of file x509v3.h.
Referenced by X509V3_EXT_i2d().
X509V3_F_X509V3_EXT_NCONF
#define X509V3_F_X509V3_EXT_NCONF 152
Definition at line 928 of file x509v3.h.
X509V3_F_X509V3_GET_SECTION
#define X509V3_F_X509V3_GET_SECTION 142
Definition at line 929 of file x509v3.h.
X509V3_F_X509V3_GET_STRING
#define X509V3_F_X509V3_GET_STRING 143
Definition at line 930 of file x509v3.h.
Referenced by X509V3_get_string().
X509V3_F_X509V3_GET_VALUE_BOOL
#define X509V3_F_X509V3_GET_VALUE_BOOL 110
Definition at line 931 of file x509v3.h.
Referenced by X509V3_get_value_bool().
X509V3_F_X509V3_PARSE_LIST
#define X509V3_F_X509V3_PARSE_LIST 109
Definition at line 932 of file x509v3.h.
X509V3_R_BAD_IP_ADDRESS
#define X509V3_R_BAD_IP_ADDRESS 118
Definition at line 937 of file x509v3.h.
X509V3_R_BAD_OBJECT
#define X509V3_R_BAD_OBJECT 119
Definition at line 938 of file x509v3.h.
X509V3_R_BN_DEC2BN_ERROR
#define X509V3_R_BN_DEC2BN_ERROR 100
Definition at line 939 of file x509v3.h.
X509V3_R_BN_TO_ASN1_INTEGER_ERROR
#define X509V3_R_BN_TO_ASN1_INTEGER_ERROR 101
Definition at line 940 of file x509v3.h.
X509V3_R_DIRNAME_ERROR
#define X509V3_R_DIRNAME_ERROR 149
Definition at line 941 of file x509v3.h.
X509V3_R_DISTPOINT_ALREADY_SET
#define X509V3_R_DISTPOINT_ALREADY_SET 160
Definition at line 942 of file x509v3.h.
X509V3_R_DUPLICATE_ZONE_ID
#define X509V3_R_DUPLICATE_ZONE_ID 133
Definition at line 943 of file x509v3.h.
X509V3_R_ERROR_CONVERTING_ZONE
#define X509V3_R_ERROR_CONVERTING_ZONE 131
Definition at line 944 of file x509v3.h.
X509V3_R_ERROR_CREATING_EXTENSION
#define X509V3_R_ERROR_CREATING_EXTENSION 144
Definition at line 945 of file x509v3.h.
X509V3_R_ERROR_IN_EXTENSION
#define X509V3_R_ERROR_IN_EXTENSION 128
Definition at line 946 of file x509v3.h.
X509V3_R_EXPECTED_A_SECTION_NAME
#define X509V3_R_EXPECTED_A_SECTION_NAME 137
Definition at line 947 of file x509v3.h.
X509V3_R_EXTENSION_EXISTS
#define X509V3_R_EXTENSION_EXISTS 145
Definition at line 948 of file x509v3.h.
X509V3_R_EXTENSION_NAME_ERROR
#define X509V3_R_EXTENSION_NAME_ERROR 115
Definition at line 949 of file x509v3.h.
X509V3_R_EXTENSION_NOT_FOUND
#define X509V3_R_EXTENSION_NOT_FOUND 102
Definition at line 950 of file x509v3.h.
Referenced by X509V3_EXT_add_alias().
X509V3_R_EXTENSION_SETTING_NOT_SUPPORTED
#define X509V3_R_EXTENSION_SETTING_NOT_SUPPORTED 103
Definition at line 951 of file x509v3.h.
X509V3_R_EXTENSION_VALUE_ERROR
#define X509V3_R_EXTENSION_VALUE_ERROR 116
Definition at line 952 of file x509v3.h.
X509V3_R_ILLEGAL_EMPTY_EXTENSION
#define X509V3_R_ILLEGAL_EMPTY_EXTENSION 151
Definition at line 953 of file x509v3.h.
X509V3_R_INCORRECT_POLICY_SYNTAX_TAG
#define X509V3_R_INCORRECT_POLICY_SYNTAX_TAG 152
Definition at line 954 of file x509v3.h.
X509V3_R_INVALID_ASNUMBER
#define X509V3_R_INVALID_ASNUMBER 162
Definition at line 955 of file x509v3.h.
X509V3_R_INVALID_ASRANGE
#define X509V3_R_INVALID_ASRANGE 163
Definition at line 956 of file x509v3.h.
X509V3_R_INVALID_BOOLEAN_STRING
#define X509V3_R_INVALID_BOOLEAN_STRING 104
Definition at line 957 of file x509v3.h.
Referenced by X509V3_get_value_bool().
X509V3_R_INVALID_EXTENSION_STRING
#define X509V3_R_INVALID_EXTENSION_STRING 105
Definition at line 958 of file x509v3.h.
X509V3_R_INVALID_INHERITANCE
#define X509V3_R_INVALID_INHERITANCE 165
Definition at line 959 of file x509v3.h.
X509V3_R_INVALID_IPADDRESS
#define X509V3_R_INVALID_IPADDRESS 166
Definition at line 960 of file x509v3.h.
X509V3_R_INVALID_MULTIPLE_RDNS
#define X509V3_R_INVALID_MULTIPLE_RDNS 161
Definition at line 961 of file x509v3.h.
X509V3_R_INVALID_NAME
#define X509V3_R_INVALID_NAME 106
Definition at line 962 of file x509v3.h.
X509V3_R_INVALID_NULL_ARGUMENT
#define X509V3_R_INVALID_NULL_ARGUMENT 107
Definition at line 963 of file x509v3.h.
Referenced by s2i_ASN1_IA5STRING().
X509V3_R_INVALID_NULL_NAME
#define X509V3_R_INVALID_NULL_NAME 108
Definition at line 964 of file x509v3.h.
X509V3_R_INVALID_NULL_VALUE
#define X509V3_R_INVALID_NULL_VALUE 109
Definition at line 965 of file x509v3.h.
X509V3_R_INVALID_NUMBER
#define X509V3_R_INVALID_NUMBER 140
Definition at line 966 of file x509v3.h.
X509V3_R_INVALID_NUMBERS
#define X509V3_R_INVALID_NUMBERS 141
Definition at line 967 of file x509v3.h.
X509V3_R_INVALID_OBJECT_IDENTIFIER
#define X509V3_R_INVALID_OBJECT_IDENTIFIER 110
Definition at line 968 of file x509v3.h.
X509V3_R_INVALID_OPTION
#define X509V3_R_INVALID_OPTION 138
Definition at line 969 of file x509v3.h.
X509V3_R_INVALID_POLICY_IDENTIFIER
#define X509V3_R_INVALID_POLICY_IDENTIFIER 134
Definition at line 970 of file x509v3.h.
X509V3_R_INVALID_PROXY_POLICY_SETTING
#define X509V3_R_INVALID_PROXY_POLICY_SETTING 153
Definition at line 971 of file x509v3.h.
X509V3_R_INVALID_PURPOSE
#define X509V3_R_INVALID_PURPOSE 146
Definition at line 972 of file x509v3.h.
Referenced by X509_PURPOSE_set().
X509V3_R_INVALID_SAFI
#define X509V3_R_INVALID_SAFI 164
Definition at line 973 of file x509v3.h.
X509V3_R_INVALID_SECTION
#define X509V3_R_INVALID_SECTION 135
Definition at line 974 of file x509v3.h.
X509V3_R_INVALID_SYNTAX
#define X509V3_R_INVALID_SYNTAX 143
Definition at line 975 of file x509v3.h.
X509V3_R_ISSUER_DECODE_ERROR
#define X509V3_R_ISSUER_DECODE_ERROR 126
Definition at line 976 of file x509v3.h.
X509V3_R_MISSING_VALUE
#define X509V3_R_MISSING_VALUE 124
Definition at line 977 of file x509v3.h.
X509V3_R_NEED_ORGANIZATION_AND_NUMBERS
#define X509V3_R_NEED_ORGANIZATION_AND_NUMBERS 142
Definition at line 978 of file x509v3.h.
X509V3_R_NO_CONFIG_DATABASE
#define X509V3_R_NO_CONFIG_DATABASE 136
Definition at line 979 of file x509v3.h.
X509V3_R_NO_ISSUER_CERTIFICATE
#define X509V3_R_NO_ISSUER_CERTIFICATE 121
Definition at line 980 of file x509v3.h.
X509V3_R_NO_ISSUER_DETAILS
#define X509V3_R_NO_ISSUER_DETAILS 127
Definition at line 981 of file x509v3.h.
X509V3_R_NO_POLICY_IDENTIFIER
#define X509V3_R_NO_POLICY_IDENTIFIER 139
Definition at line 982 of file x509v3.h.
X509V3_R_NO_PROXY_CERT_POLICY_LANGUAGE_DEFINED
#define X509V3_R_NO_PROXY_CERT_POLICY_LANGUAGE_DEFINED 154
Definition at line 983 of file x509v3.h.
X509V3_R_NO_PUBLIC_KEY
#define X509V3_R_NO_PUBLIC_KEY 114
Definition at line 984 of file x509v3.h.
X509V3_R_NO_SUBJECT_DETAILS
#define X509V3_R_NO_SUBJECT_DETAILS 125
Definition at line 985 of file x509v3.h.
X509V3_R_OPERATION_NOT_DEFINED
#define X509V3_R_OPERATION_NOT_DEFINED 148
Definition at line 986 of file x509v3.h.
Referenced by X509V3_get_string().
X509V3_R_OTHERNAME_ERROR
#define X509V3_R_OTHERNAME_ERROR 147
Definition at line 987 of file x509v3.h.
X509V3_R_POLICY_LANGUAGE_ALREADY_DEFINED
#define X509V3_R_POLICY_LANGUAGE_ALREADY_DEFINED 155
Definition at line 988 of file x509v3.h.
X509V3_R_POLICY_PATH_LENGTH
#define X509V3_R_POLICY_PATH_LENGTH 156
Definition at line 989 of file x509v3.h.
X509V3_R_POLICY_PATH_LENGTH_ALREADY_DEFINED
#define X509V3_R_POLICY_PATH_LENGTH_ALREADY_DEFINED 157
Definition at line 990 of file x509v3.h.
X509V3_R_POLICY_WHEN_PROXY_LANGUAGE_REQUIRES_NO_POLICY
#define X509V3_R_POLICY_WHEN_PROXY_LANGUAGE_REQUIRES_NO_POLICY 159
Definition at line 991 of file x509v3.h.
X509V3_R_SECTION_NOT_FOUND
#define X509V3_R_SECTION_NOT_FOUND 150
Definition at line 992 of file x509v3.h.
X509V3_R_UNABLE_TO_GET_ISSUER_DETAILS
#define X509V3_R_UNABLE_TO_GET_ISSUER_DETAILS 122
Definition at line 993 of file x509v3.h.
X509V3_R_UNABLE_TO_GET_ISSUER_KEYID
#define X509V3_R_UNABLE_TO_GET_ISSUER_KEYID 123
Definition at line 994 of file x509v3.h.
X509V3_R_UNKNOWN_BIT_STRING_ARGUMENT
#define X509V3_R_UNKNOWN_BIT_STRING_ARGUMENT 111
Definition at line 995 of file x509v3.h.
Referenced by v2i_ASN1_BIT_STRING().
X509V3_R_UNKNOWN_EXTENSION
#define X509V3_R_UNKNOWN_EXTENSION 129
Definition at line 996 of file x509v3.h.
Referenced by X509V3_EXT_i2d().
X509V3_R_UNKNOWN_EXTENSION_NAME
#define X509V3_R_UNKNOWN_EXTENSION_NAME 130
Definition at line 997 of file x509v3.h.
X509V3_R_UNKNOWN_OPTION
#define X509V3_R_UNKNOWN_OPTION 120
Definition at line 998 of file x509v3.h.
X509V3_R_UNSUPPORTED_OPTION
#define X509V3_R_UNSUPPORTED_OPTION 117
Definition at line 999 of file x509v3.h.
X509V3_R_UNSUPPORTED_TYPE
#define X509V3_R_UNSUPPORTED_TYPE 167
Definition at line 1000 of file x509v3.h.
X509V3_R_USER_TOO_LONG
#define X509V3_R_USER_TOO_LONG 132
Definition at line 1001 of file x509v3.h.
X509V3_set_ctx_nodb
#define X509V3_set_ctx_nodb (ctx) (ctx)->db = NULL;
Definition at line 327 of file x509v3.h.
X509V3_set_ctx_test
#define X509V3_set_ctx_test (ctx) X509V3_set_ctx(ctx, NULL, NULL, NULL, NULL, CTX_TEST)
Definition at line 325 of file x509v3.h.
XKU_ANYEKU
#define XKU_ANYEKU 0x100
Definition at line 395 of file x509v3.h.
XKU_CODE_SIGN
#define XKU_CODE_SIGN 0x8
Definition at line 390 of file x509v3.h.
XKU_DVCS
#define XKU_DVCS 0x80
Definition at line 394 of file x509v3.h.
XKU_OCSP_SIGN
#define XKU_OCSP_SIGN 0x20
Definition at line 392 of file x509v3.h.
XKU_SGC
#define XKU_SGC 0x10
Definition at line 391 of file x509v3.h.
XKU_SMIME
#define XKU_SMIME 0x4
Definition at line 389 of file x509v3.h.
XKU_SSL_CLIENT
#define XKU_SSL_CLIENT 0x2
Definition at line 388 of file x509v3.h.
XKU_SSL_SERVER
#define XKU_SSL_SERVER 0x1
Definition at line 387 of file x509v3.h.
XKU_TIMESTAMP
#define XKU_TIMESTAMP 0x40
Definition at line 393 of file x509v3.h.
Typedef Documentation
ENUMERATED_NAMES
typedef BIT_STRING_BITNAME ENUMERATED_NAMES
Definition at line 100 of file x509v3.h.
ext
typedef void* ext
Definition at line 32 of file x509v3.h.
STACK_OF
STACK_OF
Load CA certs from a file into a ::STACK. Note that it is somewhat misnamed; it doesn't really have anything to do with clients (except that a common use for a stack of CAs is to send it to the client). Actually, it doesn't have much to do with CAs, either, since it will load any old cert.
Parameters
file the file containing one or more certs.
Returns
a ::STACK containing the certs.
return a STACK of the ciphers available for the SSL and in order of algorithm id
return a STACK of the ciphers available for the SSL_CTX and in order of preference
Definition at line 33 of file x509v3.h.
X509V3_EXT_D2I
typedef void*(* X509V3_EXT_D2I) (void *, const unsigned char **, long)
Definition at line 29 of file x509v3.h.
X509V3_EXT_FREE
typedef void(* X509V3_EXT_FREE) (void *)
Definition at line 28 of file x509v3.h.
X509V3_EXT_I2D
typedef int(* X509V3_EXT_I2D) (void *, unsigned char **)
Definition at line 30 of file x509v3.h.
X509V3_EXT_I2R
typedef int(* X509V3_EXT_I2R) (const struct v3_ext_method *method, void *ext, BIO *out, int indent)
Definition at line 41 of file x509v3.h.
X509V3_EXT_I2S
typedef char*(* X509V3_EXT_I2S) (const struct v3_ext_method *method, void *ext)
Definition at line 37 of file x509v3.h.
X509V3_EXT_NEW
typedef void*(* X509V3_EXT_NEW) (void)
Definition at line 27 of file x509v3.h.
X509V3_EXT_R2I
typedef void*(* X509V3_EXT_R2I) (const struct v3_ext_method *method, struct v3_ext_ctx *ctx, const char *str)
Definition at line 43 of file x509v3.h.
X509V3_EXT_S2I
typedef void*(* X509V3_EXT_S2I) (const struct v3_ext_method *method, struct v3_ext_ctx *ctx, const char *str)
Definition at line 39 of file x509v3.h.
X509V3_EXT_V2I
typedef void*(* X509V3_EXT_V2I) (const struct v3_ext_method *method, struct v3_ext_ctx *ctx, STACK_OF(CONF_VALUE) *values)
Definition at line 34 of file x509v3.h.
Function Documentation
a2i_GENERAL_NAME()
GENERAL_NAME* a2i_GENERAL_NAME (GENERAL_NAME * out, const X509V3_EXT_METHOD * method, X509V3_CTX * ctx, int gen_type, const char * value, int is_nc)
Definition at line 384 of file v3_alt.c.
a2i_IPADDRESS()
ASN1_OCTET_STRING* a2i_IPADDRESS (const char * ipasc)
Definition at line 919 of file v3_utl.c.
a2i_IPADDRESS_NC()
ASN1_OCTET_STRING* a2i_IPADDRESS_NC (const char * ipasc)
Definition at line 942 of file v3_utl.c.
DIST_POINT_set_dpname()
int DIST_POINT_set_dpname (DIST_POINT_NAME * dpn, X509_NAME * iname)
Definition at line 483 of file v3_crld.c.
ERR_load_X509V3_strings()
int ERR_load_X509V3_strings (void)
Definition at line 177 of file v3err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
GENERAL_NAME_cmp()
int GENERAL_NAME_cmp (GENERAL_NAME * a, GENERAL_NAME * b)
GENERAL_NAME_dup()
GENERAL_NAME* GENERAL_NAME_dup (GENERAL_NAME * a)
Referenced by TS_TST_INFO_set_tsa().
GENERAL_NAME_get0_otherName()
int GENERAL_NAME_get0_otherName (GENERAL_NAME * gen, ASN1_OBJECT ** poid, ASN1_TYPE ** pvalue)
GENERAL_NAME_get0_value()
void* GENERAL_NAME_get0_value (GENERAL_NAME * a, int * ptype)
GENERAL_NAME_print()
int GENERAL_NAME_print (BIO * out, GENERAL_NAME * gen)
Definition at line 130 of file v3_alt.c.
Referenced by OCSP_REQUEST_print().
GENERAL_NAME_set0_othername()
int GENERAL_NAME_set0_othername (GENERAL_NAME * gen, ASN1_OBJECT * oid, ASN1_TYPE * value)
GENERAL_NAME_set0_value()
void GENERAL_NAME_set0_value (GENERAL_NAME * a, int type, void * value)
i2a_ACCESS_DESCRIPTION()
int i2a_ACCESS_DESCRIPTION (BIO * bp, const ACCESS_DESCRIPTION * a)
i2s_ASN1_ENUMERATED()
char* i2s_ASN1_ENUMERATED (X509V3_EXT_METHOD * meth, const ASN1_ENUMERATED * aint)
Definition at line 97 of file v3_utl.c.
References ASN1_ENUMERATED_to_BN(), BN_bn2dec(), BN_free(), ERR_R_MALLOC_FAILURE, NULL, X509V3_F_I2S_ASN1_ENUMERATED, and X509V3err.
Referenced by i2s_ASN1_ENUMERATED_TABLE().
i2s_ASN1_ENUMERATED_TABLE()
char* i2s_ASN1_ENUMERATED_TABLE (X509V3_EXT_METHOD * meth, const ASN1_ENUMERATED * aint)
Definition at line 41 of file v3_enum.c.
References ASN1_ENUMERATED_get(), BIT_STRING_BITNAME::bitnum, i2s_ASN1_ENUMERATED(), BIT_STRING_BITNAME::lname, and OPENSSL_strdup.
i2s_ASN1_IA5STRING()
char* i2s_ASN1_IA5STRING (X509V3_EXT_METHOD * method, ASN1_IA5STRING * ia5)
Definition at line 28 of file v3_ia5.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_malloc, X509V3_F_I2S_ASN1_IA5STRING, and X509V3err.
i2s_ASN1_INTEGER()
char* i2s_ASN1_INTEGER (X509V3_EXT_METHOD * meth, const ASN1_INTEGER * aint)
Definition at line 111 of file v3_utl.c.
References ASN1_INTEGER_to_BN(), BN_bn2dec(), BN_free(), ERR_R_MALLOC_FAILURE, NULL, X509V3_F_I2S_ASN1_INTEGER, and X509V3err.
i2s_ASN1_OCTET_STRING()
char* i2s_ASN1_OCTET_STRING (X509V3_EXT_METHOD * method, const ASN1_OCTET_STRING * ia5)
Definition at line 27 of file v3_skey.c.
References OPENSSL_buf2hexstr().
NAME_CONSTRAINTS_check()
int NAME_CONSTRAINTS_check (X509 * x, NAME_CONSTRAINTS * nc)
NAME_CONSTRAINTS_check_CN()
int NAME_CONSTRAINTS_check_CN (X509 * x, NAME_CONSTRAINTS * nc)
OTHERNAME_cmp()
int OTHERNAME_cmp (OTHERNAME * a, OTHERNAME * b)
s2i_ASN1_IA5STRING()
ASN1_IA5STRING* s2i_ASN1_IA5STRING (X509V3_EXT_METHOD * method, X509V3_CTX * ctx, const char * str)
Definition at line 43 of file v3_ia5.c.
References ASN1_STRING_set(), ebcdic2ascii(), ERR_R_MALLOC_FAILURE, NULL, X509V3_F_S2I_ASN1_IA5STRING, X509V3_R_INVALID_NULL_ARGUMENT, and X509V3err.
s2i_ASN1_INTEGER()
ASN1_INTEGER* s2i_ASN1_INTEGER (X509V3_EXT_METHOD * meth, const char * value)
Definition at line 125 of file v3_utl.c.
References NULL.
Referenced by X509V3_get_value_int().
s2i_ASN1_OCTET_STRING()
ASN1_OCTET_STRING* s2i_ASN1_OCTET_STRING (X509V3_EXT_METHOD * method, X509V3_CTX * ctx, const char * str)
Definition at line 33 of file v3_skey.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_hexstr2buf(), X509V3_F_S2I_ASN1_OCTET_STRING, and X509V3err.
STACK_OF() [1/12]
typedef STACK_OF (CONF_VALUE) const
STACK_OF() [2/12]
typedef STACK_OF (ACCESS_DESCRIPTION)
STACK_OF() [3/12]
typedef STACK_OF (ASN1_OBJECT)
STACK_OF() [4/12]
typedef STACK_OF (ASN1_INTEGER)
STACK_OF() [5/12]
typedef STACK_OF (GENERAL_NAME)
STACK_OF() [6/12]
typedef STACK_OF (DIST_POINT)
STACK_OF() [7/12]
typedef STACK_OF (POLICYINFO)
STACK_OF() [8/12]
typedef STACK_OF (POLICY_MAPPING)
STACK_OF() [9/12]
STACK_OF (OPENSSL_STRING)
STACK_OF() [10/12]
typedef STACK_OF (ASIdOrRange)
STACK_OF() [11/12]
typedef STACK_OF (IPAddressOrRange)
STACK_OF() [12/12]
typedef STACK_OF (IPAddressFamily)
SXNET_add_id_asc()
int SXNET_add_id_asc (SXNET ** psx, const char * zone, const char * user, int userlen)
SXNET_add_id_INTEGER()
int SXNET_add_id_INTEGER (SXNET ** psx, ASN1_INTEGER * izone, const char * user, int userlen)
SXNET_add_id_ulong()
int SXNET_add_id_ulong (SXNET ** psx, unsigned long lzone, const char * user, int userlen)
SXNET_get_id_asc()
ASN1_OCTET_STRING* SXNET_get_id_asc (SXNET * sx, const char * zone)
SXNET_get_id_INTEGER()
ASN1_OCTET_STRING* SXNET_get_id_INTEGER (SXNET * sx, ASN1_INTEGER * zone)
SXNET_get_id_ulong()
ASN1_OCTET_STRING* SXNET_get_id_ulong (SXNET * sx, unsigned long lzone)
v2i_ASN1_BIT_STRING()
ASN1_BIT_STRING* v2i_ASN1_BIT_STRING (X509V3_EXT_METHOD * method, X509V3_CTX * ctx, STACK_OF(CONF_VALUE) * nval)
Definition at line 58 of file v3_bitst.c.
References ASN1_BIT_STRING_set_bit(), BIT_STRING_BITNAME::bitnum, ERR_R_MALLOC_FAILURE, BIT_STRING_BITNAME::lname, CONF_VALUE::name, NULL, BIT_STRING_BITNAME::sname, X509V3_conf_err, X509V3_F_V2I_ASN1_BIT_STRING, X509V3_R_UNKNOWN_BIT_STRING_ARGUMENT, and X509V3err.
v2i_GENERAL_NAMES()
GENERAL_NAMES* v2i_GENERAL_NAMES (const X509V3_EXT_METHOD * method, X509V3_CTX * ctx, STACK_OF(CONF_VALUE) * nval)
Definition at line 354 of file v3_alt.c.
References ERR_R_MALLOC_FAILURE, gen, NULL, v2i_GENERAL_NAME(), X509V3_F_V2I_GENERAL_NAMES, and X509V3err.
X509_check_akid()
int X509_check_akid (X509 * issuer, AUTHORITY_KEYID * akid)
Definition at line 778 of file v3_purp.c.
References ASN1_INTEGER_cmp(), ASN1_OCTET_STRING_cmp(), GENERAL_NAME::d, GENERAL_NAME::dirn, gen, GEN_DIRNAME, NULL, GENERAL_NAME::type, X509_get_issuer_name(), X509_get_serialNumber(), X509_NAME_cmp(), X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH, X509_V_ERR_AKID_SKID_MISMATCH, and X509_V_OK.
X509_check_ca()
int X509_check_ca (X509 * x)
Definition at line 541 of file v3_purp.c.
References CRYPTO_THREAD_write_lock(), and EXFLAG_SET.
X509_check_email()
int X509_check_email (X509 * x, const char * chk, size_t chklen, unsigned int flags)
Definition at line 874 of file v3_utl.c.
References NULL.
Referenced by print_cert_checks().
X509_check_host()
int X509_check_host (X509 * x, const char * chk, size_t chklen, unsigned int flags, char ** peername)
Definition at line 855 of file v3_utl.c.
References NULL.
Referenced by print_cert_checks().
X509_check_ip()
int X509_check_ip (X509 * x, const unsigned char * chk, size_t chklen, unsigned int flags)
Definition at line 893 of file v3_utl.c.
References NULL.
X509_check_ip_asc()
int X509_check_ip_asc (X509 * x, const char * ipasc, unsigned int flags)
Definition at line 901 of file v3_utl.c.
References a2i_ipadd(), and NULL.
Referenced by print_cert_checks().
X509_check_issued()
int X509_check_issued (X509 * issuer, X509 * subject)
Definition at line 756 of file v3_purp.c.
References X509_get_issuer_name(), X509_get_subject_name(), X509_NAME_cmp(), and X509_V_ERR_SUBJECT_ISSUER_MISMATCH.
X509_check_purpose()
int X509_check_purpose (X509 * x, int id, int ca)
Definition at line 77 of file v3_purp.c.
Referenced by TS_RESP_CTX_set_signer_cert(), X509_cmp(), X509_get0_subject_key_id(), X509_get_extended_key_usage(), X509_get_extension_flags(), X509_get_key_usage(), X509_get_pathlen(), and X509_get_proxy_pathlen().
X509_email_free()
void X509_email_free (STACK_OF(OPENSSL_STRING) * sk)
Definition at line 480 of file v3_utl.c.
X509_get0_subject_key_id()
const ASN1_OCTET_STRING* X509_get0_subject_key_id (X509 * x)
Definition at line 842 of file v3_purp.c.
References X509_check_purpose().
X509_get_extended_key_usage()
uint32_t X509_get_extended_key_usage (X509 * x)
Definition at line 833 of file v3_purp.c.
References EXFLAG_XKUSAGE, UINT32_MAX, and X509_check_purpose().
X509_get_extension_flags()
uint32_t X509_get_extension_flags (X509 * x)
Definition at line 817 of file v3_purp.c.
References X509_check_purpose().
Referenced by ssl_build_cert_chain().
X509_get_key_usage()
uint32_t X509_get_key_usage (X509 * x)
Definition at line 824 of file v3_purp.c.
References EXFLAG_KUSAGE, UINT32_MAX, and X509_check_purpose().
Referenced by ssl_check_srvr_ecc_cert_and_alg().
X509_get_proxy_pathlen()
long X509_get_proxy_pathlen (X509 * x)
Definition at line 858 of file v3_purp.c.
References EXFLAG_PROXY, and X509_check_purpose().
X509_POLICY_NODE_print()
void X509_POLICY_NODE_print (BIO * out, X509_POLICY_NODE * node, int indent)
X509_PURPOSE_add()
int X509_PURPOSE_add (int id, int trust, int flags, int(*)(const X509_PURPOSE *, const X509 *, int) ck, const char * name, const char * sname, void * arg)
Definition at line 149 of file v3_purp.c.
X509_PURPOSE_cleanup()
void X509_PURPOSE_cleanup (void)
Definition at line 230 of file v3_purp.c.
X509_PURPOSE_get0()
X509_PURPOSE* X509_PURPOSE_get0 (int idx)
Definition at line 113 of file v3_purp.c.
Referenced by X509_PURPOSE_get_by_sname().
X509_PURPOSE_get0_name()
char* X509_PURPOSE_get0_name (const X509_PURPOSE * xp)
Definition at line 241 of file v3_purp.c.
References X509_PURPOSE::name.
X509_PURPOSE_get0_sname()
char* X509_PURPOSE_get0_sname (const X509_PURPOSE * xp)
Definition at line 246 of file v3_purp.c.
References X509_PURPOSE::sname.
X509_PURPOSE_get_by_id()
int X509_PURPOSE_get_by_id (int id)
Definition at line 134 of file v3_purp.c.
Referenced by X509_PURPOSE_set().
X509_PURPOSE_get_by_sname()
int X509_PURPOSE_get_by_sname (const char * sname)
Definition at line 122 of file v3_purp.c.
References X509_PURPOSE::sname, X509_PURPOSE_get0(), and X509_PURPOSE_get_count().
X509_PURPOSE_get_count()
int X509_PURPOSE_get_count (void)
Definition at line 106 of file v3_purp.c.
References X509_PURPOSE_COUNT.
Referenced by X509_PURPOSE_get_by_sname().
X509_PURPOSE_get_id()
int X509_PURPOSE_get_id (const X509_PURPOSE *)
Definition at line 236 of file v3_purp.c.
References X509_PURPOSE::purpose.
X509_PURPOSE_get_trust()
int X509_PURPOSE_get_trust (const X509_PURPOSE * xp)
Definition at line 251 of file v3_purp.c.
References X509_PURPOSE::trust.
X509_PURPOSE_set()
int X509_PURPOSE_set (int * p, int purpose)
Definition at line 96 of file v3_purp.c.
References X509_PURPOSE_get_by_id(), X509V3_F_X509_PURPOSE_SET, X509V3_R_INVALID_PURPOSE, and X509V3err.
Referenced by X509_VERIFY_PARAM_set_purpose().
X509_set_proxy_flag()
void X509_set_proxy_flag (X509 * x)
Definition at line 531 of file v3_purp.c.
References EXFLAG_PROXY.
X509_set_proxy_pathlen()
void X509_set_proxy_pathlen (X509 * x, long l)
Definition at line 536 of file v3_purp.c.
X509_supported_extension()
int X509_supported_extension (X509_EXTENSION * ex)
Definition at line 264 of file v3_purp.c.
References NID_basic_constraints, NID_certificate_policies, NID_ext_key_usage, NID_inhibit_any_policy, NID_key_usage, NID_name_constraints, NID_netscape_cert_type, NID_policy_constraints, NID_policy_mappings, NID_proxyCertInfo, NID_sbgp_autonomousSysNum, NID_sbgp_ipAddrBlock, NID_subject_alt_name, NID_undef, OBJ_obj2nid(), OSSL_NELEM, and X509_EXTENSION_get_object().
X509V3_add1_i2d()
int X509V3_add1_i2d (STACK_OF(X509_EXTENSION) ** x, int nid, void * value, int crit, unsigned long flags)
Definition at line 218 of file v3_lib.c.
Referenced by OCSP_BASICRESP_add1_ext_i2d(), OCSP_ONEREQ_add1_ext_i2d(), OCSP_REQUEST_add1_ext_i2d(), OCSP_SINGLERESP_add1_ext_i2d(), X509_add1_ext_i2d(), X509_CRL_add1_ext_i2d(), and X509_REVOKED_add1_ext_i2d().
X509V3_add_standard_extensions()
int X509V3_add_standard_extensions (void)
Definition at line 123 of file v3_lib.c.
X509V3_add_value()
int X509V3_add_value (const char * name, const char * value, STACK_OF(CONF_VALUE) ** extlist)
Referenced by X509V3_add_value_bool(), X509V3_add_value_bool_nf(), and X509V3_add_value_uchar().
X509V3_add_value_bool()
int X509V3_add_value_bool (const char * name, int asn1_bool, STACK_OF(CONF_VALUE) ** extlist)
Definition at line 81 of file v3_utl.c.
References X509V3_add_value().
X509V3_add_value_int()
int X509V3_add_value_int (const char * name, const ASN1_INTEGER * aint, STACK_OF(CONF_VALUE) ** extlist)
Definition at line 178 of file v3_utl.c.
X509V3_add_value_uchar()
int X509V3_add_value_uchar (const char * name, const unsigned char * value, STACK_OF(CONF_VALUE) ** extlist)
Definition at line 63 of file v3_utl.c.
References X509V3_add_value().
X509v3_addr_add_inherit()
int X509v3_addr_add_inherit (IPAddrBlocks * addr, const unsigned afi, const unsigned * safi)
X509v3_addr_add_prefix()
int X509v3_addr_add_prefix (IPAddrBlocks * addr, const unsigned afi, const unsigned * safi, unsigned char * a, const int prefixlen)
X509v3_addr_add_range()
int X509v3_addr_add_range (IPAddrBlocks * addr, const unsigned afi, const unsigned * safi, unsigned char * min, unsigned char * max)
X509v3_addr_canonize()
int X509v3_addr_canonize (IPAddrBlocks * addr)
X509v3_addr_get_afi()
unsigned X509v3_addr_get_afi (const IPAddressFamily * f)
X509v3_addr_get_range()
int X509v3_addr_get_range (IPAddressOrRange * aor, const unsigned afi, unsigned char * min, unsigned char * max, const int length)
X509v3_addr_inherits()
int X509v3_addr_inherits (IPAddrBlocks * addr)
Definition at line 1074 of file v3_addr.c.
References IPAddressFamily::ipAddressChoice, IPAddressChoice_inherit, and IPAddressChoice::type.
Referenced by X509v3_addr_subset(), and X509v3_addr_validate_resource_set().
X509v3_addr_is_canonical()
int X509v3_addr_is_canonical (IPAddrBlocks * addr)
X509v3_addr_subset()
int X509v3_addr_subset (IPAddrBlocks * a, IPAddrBlocks * b)
Definition at line 1127 of file v3_addr.c.
References X509v3_addr_inherits().
X509v3_addr_validate_path()
int X509v3_addr_validate_path (X509_STORE_CTX *)
Definition at line 1284 of file v3_addr.c.
X509v3_addr_validate_resource_set()
int X509v3_addr_validate_resource_set (STACK_OF(X509) * chain, IPAddrBlocks * ext, int allow_inheritance)
Definition at line 1293 of file v3_addr.c.
References X509v3_addr_inherits().
X509v3_asid_add_id_or_range()
int X509v3_asid_add_id_or_range (ASIdentifiers * asid, int which, ASN1_INTEGER * min, ASN1_INTEGER * max)
X509v3_asid_add_inherit()
int X509v3_asid_add_inherit (ASIdentifiers * asid, int which)
X509v3_asid_canonize()
int X509v3_asid_canonize (ASIdentifiers * asid)
X509v3_asid_inherits()
int X509v3_asid_inherits (ASIdentifiers * asid)
Definition at line 634 of file v3_asid.c.
References ASIdentifierChoice_inherit, ASIdentifiers::asnum, ASIdentifiers::rdi, and ASIdentifierChoice::type.
Referenced by X509v3_asid_subset(), and X509v3_asid_validate_resource_set().
X509v3_asid_is_canonical()
int X509v3_asid_is_canonical (ASIdentifiers * asid)
X509v3_asid_subset()
int X509v3_asid_subset (ASIdentifiers * a, ASIdentifiers * b)
Definition at line 677 of file v3_asid.c.
References X509v3_asid_inherits().
X509v3_asid_validate_path()
int X509v3_asid_validate_path (X509_STORE_CTX *)
Definition at line 831 of file v3_asid.c.
X509v3_asid_validate_resource_set()
int X509v3_asid_validate_resource_set (STACK_OF(X509) * chain, ASIdentifiers * ext, int allow_inheritance)
Definition at line 840 of file v3_asid.c.
References X509v3_asid_inherits().
X509V3_EXT_add()
int X509V3_EXT_add (X509V3_EXT_METHOD * ext)
Referenced by X509V3_EXT_add_alias(), and X509V3_EXT_add_list().
X509V3_EXT_add_alias()
int X509V3_EXT_add_alias (int nid_to, int nid_from)
Definition at line 87 of file v3_lib.c.
References ERR_R_MALLOC_FAILURE, NULL, OPENSSL_malloc, X509V3_EXT_add(), X509V3_EXT_DYNAMIC, X509V3_EXT_get_nid(), X509V3_F_X509V3_EXT_ADD_ALIAS, X509V3_R_EXTENSION_NOT_FOUND, and X509V3err.
X509V3_EXT_add_list()
int X509V3_EXT_add_list (X509V3_EXT_METHOD * extlist)
Definition at line 79 of file v3_lib.c.
References X509V3_EXT_add().
X509V3_EXT_cleanup()
void X509V3_EXT_cleanup (void)
Definition at line 106 of file v3_lib.c.
X509V3_EXT_d2i()
void* X509V3_EXT_d2i (X509_EXTENSION * ext)
Definition at line 130 of file v3_lib.c.
References ASN1_item_d2i(), ASN1_ITEM_ptr, ASN1_STRING_get0_data(), ASN1_STRING_length(), NULL, X509_EXTENSION_get_data(), and X509V3_EXT_get().
X509V3_EXT_get()
const X509V3_EXT_METHOD* X509V3_EXT_get (X509_EXTENSION * ext)
Definition at line 71 of file v3_lib.c.
References nid, NID_undef, NULL, OBJ_obj2nid(), X509_EXTENSION_get_object(), and X509V3_EXT_get_nid().
Referenced by X509V3_EXT_d2i().
X509V3_EXT_get_nid()
const X509V3_EXT_METHOD* X509V3_EXT_get_nid (int nid)
Definition at line 52 of file v3_lib.c.
References t.
Referenced by X509V3_EXT_add_alias(), X509V3_EXT_get(), and X509V3_EXT_i2d().
X509V3_EXT_i2d()
X509_EXTENSION* X509V3_EXT_i2d (int ext_nid, int crit, void * ext_struc)
Definition at line 177 of file v3_conf.c.
References NULL, X509V3_EXT_get_nid(), X509V3_F_X509V3_EXT_I2D, X509V3_R_UNKNOWN_EXTENSION, and X509V3err.
Referenced by OCSP_accept_responses_new(), OCSP_archive_cutoff_new(), OCSP_crlID_new(), and OCSP_url_svcloc_new().
X509V3_EXT_print()
int X509V3_EXT_print (BIO * out, X509_EXTENSION * ext, unsigned long flag, int indent)
Definition at line 69 of file v3_prn.c.
Referenced by TS_ext_print_bio(), and X509_REQ_print_ex().
X509V3_EXT_print_fp()
int X509V3_EXT_print_fp (FILE * out, X509_EXTENSION * ext, int flag, int indent)
Definition at line 199 of file v3_prn.c.
X509V3_EXT_val_prn()
void X509V3_EXT_val_prn (BIO * out, STACK_OF(CONF_VALUE) * val, int indent, int ml)
Definition at line 24 of file v3_prn.c.
X509V3_extensions_print()
int X509V3_extensions_print (BIO * out, const char * title, const STACK_OF(X509_EXTENSION) * exts, unsigned long flag, int indent)
Definition at line 138 of file v3_prn.c.
X509V3_get_d2i()
void* X509V3_get_d2i (const STACK_OF(X509_EXTENSION) * x, int nid, int * crit, int * idx)
Definition at line 163 of file v3_lib.c.
X509V3_get_string()
char* X509V3_get_string (X509V3_CTX * ctx, const char * name, const char * section)
Definition at line 366 of file v3_conf.c.
References NULL, X509V3_F_X509V3_GET_STRING, X509V3_R_OPERATION_NOT_DEFINED, and X509V3err.
X509V3_NAME_from_section()
int X509V3_NAME_from_section (X509_NAME * nm, STACK_OF(CONF_VALUE) * dn_sk, unsigned long chtype)
Definition at line 1149 of file v3_utl.c.
References CONF_VALUE::name, os_toascii, type, CONF_VALUE::value, and X509_NAME_add_entry_by_txt().
X509V3_section_free()
void X509V3_section_free (X509V3_CTX * ctx, STACK_OF(CONF_VALUE) * section)
Definition at line 397 of file v3_conf.c.
X509V3_set_ctx()
void X509V3_set_ctx (X509V3_CTX * ctx, X509 * issuer, X509 * subject, X509_REQ * req, X509_CRL * crl, int flags)
Definition at line 428 of file v3_conf.c.
References flags.
X509V3_string_free()
void X509V3_string_free (X509V3_CTX * ctx, char * str)
Definition at line 389 of file v3_conf.c.
Variable Documentation
bits
ASN1_BIT_STRING* bits
Definition at line 475 of file x509v3.h.
gen
GENERAL_NAMES * gen
Definition at line 482 of file x509v3.h.
Referenced by OCSP_request_set1_name(), OCSP_request_verify(), v2i_GENERAL_NAMES(), and X509_check_akid().
section
const char* section
Definition at line 594 of file x509v3.h.