crypto/x509/x509_vpm.c File Reference
x509_vpm.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/crypto.h>
#include <openssl/lhash.h>
#include <openssl/buffer.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include "internal/x509_int.h"
#include "x509_lcl.h"
Macros
#define SET_HOST 0
#define ADD_HOST 1
#define test_x509_verify_param_copy(field, def)
#define x509_verify_param_copy(field, def)
#define vpm_empty_id NULL, 0U, NULL, NULL, 0, NULL, 0
Functions
X509_VERIFY_PARAM * X509_VERIFY_PARAM_new (void)
void X509_VERIFY_PARAM_free (X509_VERIFY_PARAM *param)
int X509_VERIFY_PARAM_inherit (X509_VERIFY_PARAM *dest, const X509_VERIFY_PARAM *src)
int X509_VERIFY_PARAM_set1 (X509_VERIFY_PARAM *to, const X509_VERIFY_PARAM *from)
int X509_VERIFY_PARAM_set1_name (X509_VERIFY_PARAM *param, const char *name)
int X509_VERIFY_PARAM_set_flags (X509_VERIFY_PARAM *param, unsigned long flags)
int X509_VERIFY_PARAM_clear_flags (X509_VERIFY_PARAM *param, unsigned long flags)
unsigned long X509_VERIFY_PARAM_get_flags (X509_VERIFY_PARAM *param)
uint32_t X509_VERIFY_PARAM_get_inh_flags (const X509_VERIFY_PARAM *param)
int X509_VERIFY_PARAM_set_inh_flags (X509_VERIFY_PARAM *param, uint32_t flags)
int X509_VERIFY_PARAM_set_purpose (X509_VERIFY_PARAM *param, int purpose)
int X509_VERIFY_PARAM_set_trust (X509_VERIFY_PARAM *param, int trust)
void X509_VERIFY_PARAM_set_depth (X509_VERIFY_PARAM *param, int depth)
void X509_VERIFY_PARAM_set_auth_level (X509_VERIFY_PARAM *param, int auth_level)
time_t X509_VERIFY_PARAM_get_time (const X509_VERIFY_PARAM *param)
void X509_VERIFY_PARAM_set_time (X509_VERIFY_PARAM *param, time_t t)
int X509_VERIFY_PARAM_add0_policy (X509_VERIFY_PARAM *param, ASN1_OBJECT *policy)
int X509_VERIFY_PARAM_set1_policies (X509_VERIFY_PARAM *param, STACK_OF(ASN1_OBJECT) *policies)
int X509_VERIFY_PARAM_set1_host (X509_VERIFY_PARAM *param, const char *name, size_t namelen)
int X509_VERIFY_PARAM_add1_host (X509_VERIFY_PARAM *param, const char *name, size_t namelen)
void X509_VERIFY_PARAM_set_hostflags (X509_VERIFY_PARAM *param, unsigned int flags)
char * X509_VERIFY_PARAM_get0_peername (X509_VERIFY_PARAM *param)
void X509_VERIFY_PARAM_move_peername (X509_VERIFY_PARAM *to, X509_VERIFY_PARAM *from)
int X509_VERIFY_PARAM_set1_email (X509_VERIFY_PARAM *param, const char *email, size_t emaillen)
int X509_VERIFY_PARAM_set1_ip (X509_VERIFY_PARAM *param, const unsigned char *ip, size_t iplen)
int X509_VERIFY_PARAM_set1_ip_asc (X509_VERIFY_PARAM *param, const char *ipasc)
int X509_VERIFY_PARAM_get_depth (const X509_VERIFY_PARAM *param)
int X509_VERIFY_PARAM_get_auth_level (const X509_VERIFY_PARAM *param)
const char * X509_VERIFY_PARAM_get0_name (const X509_VERIFY_PARAM *param)
DECLARE_OBJ_BSEARCH_CMP_FN (X509_VERIFY_PARAM, X509_VERIFY_PARAM, table)
IMPLEMENT_OBJ_BSEARCH_CMP_FN (X509_VERIFY_PARAM, X509_VERIFY_PARAM, table)
int X509_VERIFY_PARAM_add0_table (X509_VERIFY_PARAM *param)
int X509_VERIFY_PARAM_get_count (void)
const X509_VERIFY_PARAM * X509_VERIFY_PARAM_get0 (int id)
const X509_VERIFY_PARAM * X509_VERIFY_PARAM_lookup (const char *name)
void X509_VERIFY_PARAM_table_cleanup (void)
Macro Definition Documentation
ADD_HOST
#define ADD_HOST 1
Definition at line 25 of file x509_vpm.c.
SET_HOST
#define SET_HOST 0
Definition at line 24 of file x509_vpm.c.
test_x509_verify_param_copy
#define test_x509_verify_param_copy (field, def)
Value:
(to_overwrite || \
                ((src->field != def) && (to_default || (dest->field == def))))
Definition at line 146 of file x509_vpm.c.
Referenced by X509_VERIFY_PARAM_inherit().
vpm_empty_id
#define vpm_empty_id NULL, 0U, NULL, NULL, 0, NULL, 0
Definition at line 463 of file x509_vpm.c.
x509_verify_param_copy
#define x509_verify_param_copy (field, def)
Value:
if (test_x509_verify_param_copy(field, def)) \
                dest->field = src->field
Definition at line 152 of file x509_vpm.c.
Referenced by X509_VERIFY_PARAM_inherit().
Function Documentation
DECLARE_OBJ_BSEARCH_CMP_FN()
DECLARE_OBJ_BSEARCH_CMP_FN (X509_VERIFY_PARAM , X509_VERIFY_PARAM , table)
IMPLEMENT_OBJ_BSEARCH_CMP_FN()
IMPLEMENT_OBJ_BSEARCH_CMP_FN (X509_VERIFY_PARAM , X509_VERIFY_PARAM , table)
X509_VERIFY_PARAM_add0_policy()
int X509_VERIFY_PARAM_add0_policy (X509_VERIFY_PARAM * param, ASN1_OBJECT * policy)
Definition at line 334 of file x509_vpm.c.
X509_VERIFY_PARAM_add0_table()
int X509_VERIFY_PARAM_add0_table (X509_VERIFY_PARAM * param)
Definition at line 545 of file x509_vpm.c.
X509_VERIFY_PARAM_add1_host()
int X509_VERIFY_PARAM_add1_host (X509_VERIFY_PARAM * param, const char * name, size_t namelen)
Definition at line 386 of file x509_vpm.c.
Referenced by SSL_add1_host().
X509_VERIFY_PARAM_clear_flags()
int X509_VERIFY_PARAM_clear_flags (X509_VERIFY_PARAM * param, unsigned long flags)
Definition at line 280 of file x509_vpm.c.
X509_VERIFY_PARAM_free()
void X509_VERIFY_PARAM_free (X509_VERIFY_PARAM * param)
Definition at line 100 of file x509_vpm.c.
References ASN1_OBJECT_free(), and NULL.
Referenced by SSL_CTX_free(), SSL_free(), X509_STORE_CTX_cleanup(), X509_STORE_CTX_set0_param(), and X509_VERIFY_PARAM_table_cleanup().
X509_VERIFY_PARAM_get0()
const X509_VERIFY_PARAM* X509_VERIFY_PARAM_get0 (int id)
Definition at line 574 of file x509_vpm.c.
References OSSL_NELEM.
X509_VERIFY_PARAM_get0_name()
const char* X509_VERIFY_PARAM_get0_name (const X509_VERIFY_PARAM * param)
Definition at line 458 of file x509_vpm.c.
X509_VERIFY_PARAM_get0_peername()
char* X509_VERIFY_PARAM_get0_peername (X509_VERIFY_PARAM * param)
Definition at line 398 of file x509_vpm.c.
Referenced by SSL_get0_peername().
X509_VERIFY_PARAM_get_auth_level()
int X509_VERIFY_PARAM_get_auth_level (const X509_VERIFY_PARAM * param)
Definition at line 453 of file x509_vpm.c.
X509_VERIFY_PARAM_get_count()
int X509_VERIFY_PARAM_get_count (void)
Definition at line 566 of file x509_vpm.c.
References OSSL_NELEM.
X509_VERIFY_PARAM_get_depth()
int X509_VERIFY_PARAM_get_depth (const X509_VERIFY_PARAM * param)
Definition at line 448 of file x509_vpm.c.
Referenced by SSL_CTX_get_verify_depth(), and SSL_get_verify_depth().
X509_VERIFY_PARAM_get_flags()
unsigned long X509_VERIFY_PARAM_get_flags (X509_VERIFY_PARAM * param)
Definition at line 287 of file x509_vpm.c.
X509_VERIFY_PARAM_get_inh_flags()
uint32_t X509_VERIFY_PARAM_get_inh_flags (const X509_VERIFY_PARAM * param)
Definition at line 292 of file x509_vpm.c.
X509_VERIFY_PARAM_get_time()
time_t X509_VERIFY_PARAM_get_time (const X509_VERIFY_PARAM * param)
Definition at line 323 of file x509_vpm.c.
X509_VERIFY_PARAM_inherit()
int X509_VERIFY_PARAM_inherit (X509_VERIFY_PARAM * dest, const X509_VERIFY_PARAM * src)
Definition at line 156 of file x509_vpm.c.
References NULL, test_x509_verify_param_copy, X509_TRUST_DEFAULT, X509_V_FLAG_USE_CHECK_TIME, x509_verify_param_copy, X509_VERIFY_PARAM_set1_policies(), X509_VP_FLAG_DEFAULT, X509_VP_FLAG_LOCKED, X509_VP_FLAG_ONCE, X509_VP_FLAG_OVERWRITE, and X509_VP_FLAG_RESET_FLAGS.
Referenced by SSL_new(), and X509_STORE_CTX_set_default().
X509_VERIFY_PARAM_lookup()
const X509_VERIFY_PARAM* X509_VERIFY_PARAM_lookup (const char * name)
Definition at line 582 of file x509_vpm.c.
Referenced by X509_STORE_CTX_set_default().
X509_VERIFY_PARAM_move_peername()
void X509_VERIFY_PARAM_move_peername (X509_VERIFY_PARAM * to, X509_VERIFY_PARAM * from)
Definition at line 408 of file x509_vpm.c.
References if(), NULL, and OPENSSL_free.
Referenced by ssl_verify_cert_chain().
X509_VERIFY_PARAM_new()
X509_VERIFY_PARAM* X509_VERIFY_PARAM_new (void)
Definition at line 83 of file x509_vpm.c.
References NULL, OPENSSL_zalloc, and X509_TRUST_DEFAULT.
Referenced by SSL_new().
X509_VERIFY_PARAM_set1()
int X509_VERIFY_PARAM_set1 (X509_VERIFY_PARAM * to, const X509_VERIFY_PARAM * from)
Definition at line 230 of file x509_vpm.c.
Referenced by SSL_CTX_set1_param(), SSL_set1_param(), ssl_verify_cert_chain(), and X509_STORE_set1_param().
X509_VERIFY_PARAM_set1_email()
int X509_VERIFY_PARAM_set1_email (X509_VERIFY_PARAM * param, const char * email, size_t emaillen)
Definition at line 421 of file x509_vpm.c.
X509_VERIFY_PARAM_set1_host()
int X509_VERIFY_PARAM_set1_host (X509_VERIFY_PARAM * param, const char * name, size_t namelen)
Definition at line 380 of file x509_vpm.c.
Referenced by SSL_dane_enable(), and SSL_set1_host().
X509_VERIFY_PARAM_set1_ip()
int X509_VERIFY_PARAM_set1_ip (X509_VERIFY_PARAM * param, const unsigned char * ip, size_t iplen)
Definition at line 428 of file x509_vpm.c.
Referenced by X509_VERIFY_PARAM_set1_ip_asc().
X509_VERIFY_PARAM_set1_ip_asc()
int X509_VERIFY_PARAM_set1_ip_asc (X509_VERIFY_PARAM * param, const char * ipasc)
Definition at line 437 of file x509_vpm.c.
References a2i_ipadd(), and X509_VERIFY_PARAM_set1_ip().
X509_VERIFY_PARAM_set1_name()
int X509_VERIFY_PARAM_set1_name (X509_VERIFY_PARAM * param, const char * name)
Definition at line 263 of file x509_vpm.c.
References OPENSSL_free, and OPENSSL_strdup.
X509_VERIFY_PARAM_set1_policies()
int X509_VERIFY_PARAM_set1_policies (X509_VERIFY_PARAM * param, STACK_OF(ASN1_OBJECT) * policies)
Definition at line 347 of file x509_vpm.c.
Referenced by X509_VERIFY_PARAM_inherit().
X509_VERIFY_PARAM_set_auth_level()
void X509_VERIFY_PARAM_set_auth_level (X509_VERIFY_PARAM * param, int auth_level)
Definition at line 318 of file x509_vpm.c.
Referenced by ssl_verify_cert_chain().
X509_VERIFY_PARAM_set_depth()
void X509_VERIFY_PARAM_set_depth (X509_VERIFY_PARAM * param, int depth)
Definition at line 313 of file x509_vpm.c.
Referenced by SSL_CTX_set_verify_depth(), SSL_set_verify_depth(), X509_STORE_CTX_set_depth(), and X509_STORE_set_depth().
X509_VERIFY_PARAM_set_flags()
int X509_VERIFY_PARAM_set_flags (X509_VERIFY_PARAM * param, unsigned long flags)
Definition at line 272 of file x509_vpm.c.
References flags, X509_V_FLAG_POLICY_CHECK, and X509_V_FLAG_POLICY_MASK.
Referenced by X509_STORE_CTX_set_flags(), and X509_STORE_set_flags().
X509_VERIFY_PARAM_set_hostflags()
void X509_VERIFY_PARAM_set_hostflags (X509_VERIFY_PARAM * param, unsigned int flags)
Definition at line 392 of file x509_vpm.c.
References flags.
Referenced by SSL_set_hostflags().
X509_VERIFY_PARAM_set_inh_flags()
int X509_VERIFY_PARAM_set_inh_flags (X509_VERIFY_PARAM * param, uint32_t flags)
Definition at line 297 of file x509_vpm.c.
References flags.
X509_VERIFY_PARAM_set_purpose()
int X509_VERIFY_PARAM_set_purpose (X509_VERIFY_PARAM * param, int purpose)
Definition at line 303 of file x509_vpm.c.
References X509_PURPOSE_set().
Referenced by SSL_CTX_set_purpose(), SSL_set_purpose(), and X509_STORE_set_purpose().
X509_VERIFY_PARAM_set_time()
void X509_VERIFY_PARAM_set_time (X509_VERIFY_PARAM * param, time_t t)
Definition at line 328 of file x509_vpm.c.
References t, and X509_V_FLAG_USE_CHECK_TIME.
Referenced by X509_STORE_CTX_set_time().
X509_VERIFY_PARAM_set_trust()
int X509_VERIFY_PARAM_set_trust (X509_VERIFY_PARAM * param, int trust)
Definition at line 308 of file x509_vpm.c.
References X509_TRUST_set().
Referenced by SSL_CTX_set_trust(), SSL_set_trust(), and X509_STORE_set_trust().
X509_VERIFY_PARAM_table_cleanup()
void X509_VERIFY_PARAM_table_cleanup (void)
Definition at line 596 of file x509_vpm.c.
References NULL, and X509_VERIFY_PARAM_free().