crypto/x509/x509spki.c File Reference
x509spki.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/x509.h>
Functions
int NETSCAPE_SPKI_set_pubkey (NETSCAPE_SPKI *x, EVP_PKEY *pkey)
EVP_PKEY * NETSCAPE_SPKI_get_pubkey (NETSCAPE_SPKI *x)
NETSCAPE_SPKI * NETSCAPE_SPKI_b64_decode (const char *str, int len)
char * NETSCAPE_SPKI_b64_encode (NETSCAPE_SPKI *spki)
Function Documentation
NETSCAPE_SPKI_b64_decode()
NETSCAPE_SPKI* NETSCAPE_SPKI_b64_decode (const char * str, int len)
Definition at line 30 of file x509spki.c.
References ERR_R_MALLOC_FAILURE, EVP_DecodeBlock(), NULL, OPENSSL_free, OPENSSL_malloc, X509_F_NETSCAPE_SPKI_B64_DECODE, X509_R_BASE64_DECODE_ERROR, and X509err.
NETSCAPE_SPKI_b64_encode()
char* NETSCAPE_SPKI_b64_encode (NETSCAPE_SPKI * spki)
Definition at line 56 of file x509spki.c.
References ERR_R_MALLOC_FAILURE, EVP_EncodeBlock(), NULL, OPENSSL_free, OPENSSL_malloc, X509_F_NETSCAPE_SPKI_B64_ENCODE, and X509err.
NETSCAPE_SPKI_get_pubkey()
EVP_PKEY* NETSCAPE_SPKI_get_pubkey (NETSCAPE_SPKI * x)
Definition at line 21 of file x509spki.c.
References NULL, NETSCAPE_SPKAC::pubkey, NETSCAPE_SPKI::spkac, and X509_PUBKEY_get().
NETSCAPE_SPKI_set_pubkey()
int NETSCAPE_SPKI_set_pubkey (NETSCAPE_SPKI * x, EVP_PKEY * pkey)
Definition at line 14 of file x509spki.c.
References NULL, NETSCAPE_SPKAC::pubkey, NETSCAPE_SPKI::spkac, and X509_PUBKEY_set().