crypto/x509/x509_req.c File Reference
x509_req.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/bn.h>
#include <openssl/evp.h>
#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include <openssl/x509.h>
#include "internal/x509_int.h"
#include <openssl/objects.h>
#include <openssl/buffer.h>
#include <openssl/pem.h>
Functions
X509_REQ * X509_to_X509_REQ (X509 *x, EVP_PKEY *pkey, const EVP_MD *md)
EVP_PKEY * X509_REQ_get_pubkey (X509_REQ *req)
EVP_PKEY * X509_REQ_get0_pubkey (X509_REQ *req)
X509_PUBKEY * X509_REQ_get_X509_PUBKEY (X509_REQ *req)
int X509_REQ_check_private_key (X509_REQ *x, EVP_PKEY *k)
int X509_REQ_extension_nid (int req_nid)
int * X509_REQ_get_extension_nids (void)
void X509_REQ_set_extension_nids (int *nids)
STACK_OF (X509_EXTENSION)
int X509_REQ_add_extensions_nid (X509_REQ *req, STACK_OF(X509_EXTENSION) *exts, int nid)
int X509_REQ_add_extensions (X509_REQ *req, STACK_OF(X509_EXTENSION) *exts)
int X509_REQ_get_attr_count (const X509_REQ *req)
int X509_REQ_get_attr_by_NID (const X509_REQ *req, int nid, int lastpos)
int X509_REQ_get_attr_by_OBJ (const X509_REQ *req, const ASN1_OBJECT *obj, int lastpos)
X509_ATTRIBUTE * X509_REQ_get_attr (const X509_REQ *req, int loc)
X509_ATTRIBUTE * X509_REQ_delete_attr (X509_REQ *req, int loc)
int X509_REQ_add1_attr (X509_REQ *req, X509_ATTRIBUTE *attr)
int X509_REQ_add1_attr_by_OBJ (X509_REQ *req, const ASN1_OBJECT *obj, int type, const unsigned char *bytes, int len)
int X509_REQ_add1_attr_by_NID (X509_REQ *req, int nid, int type, const unsigned char *bytes, int len)
int X509_REQ_add1_attr_by_txt (X509_REQ *req, const char *attrname, int type, const unsigned char *bytes, int len)
long X509_REQ_get_version (const X509_REQ *req)
X509_NAME * X509_REQ_get_subject_name (const X509_REQ *req)
void X509_REQ_get0_signature (const X509_REQ *req, const ASN1_BIT_STRING **psig, const X509_ALGOR **palg)
int X509_REQ_get_signature_nid (const X509_REQ *req)
int i2d_re_X509_REQ_tbs (X509_REQ *req, unsigned char **pp)
Function Documentation
i2d_re_X509_REQ_tbs()
int i2d_re_X509_REQ_tbs (X509_REQ * req, unsigned char ** pp)
Definition at line 294 of file x509_req.c.
STACK_OF()
STACK_OF (X509_EXTENSION)
Definition at line 153 of file x509_req.c.
References attr, and NULL.
X509_REQ_add1_attr()
int X509_REQ_add1_attr (X509_REQ * req, X509_ATTRIBUTE * attr)
Definition at line 233 of file x509_req.c.
X509_REQ_add1_attr_by_NID()
int X509_REQ_add1_attr_by_NID (X509_REQ * req, int nid, int type, const unsigned char * bytes, int len)
Definition at line 250 of file x509_req.c.
Referenced by X509_REQ_add_extensions_nid().
X509_REQ_add1_attr_by_OBJ()
int X509_REQ_add1_attr_by_OBJ (X509_REQ * req, const ASN1_OBJECT * obj, int type, const unsigned char * bytes, int len)
Definition at line 240 of file x509_req.c.
X509_REQ_add1_attr_by_txt()
int X509_REQ_add1_attr_by_txt (X509_REQ * req, const char * attrname, int type, const unsigned char * bytes, int len)
Definition at line 260 of file x509_req.c.
X509_REQ_add_extensions()
int X509_REQ_add_extensions (X509_REQ * req, STACK_OF(X509_EXTENSION) * exts)
Definition at line 200 of file x509_req.c.
References NID_ext_req, and X509_REQ_add_extensions_nid().
X509_REQ_add_extensions_nid()
int X509_REQ_add_extensions_nid (X509_REQ * req, STACK_OF(X509_EXTENSION) * exts, int nid)
Definition at line 183 of file x509_req.c.
References ASN1_item_i2d(), ASN1_ITEM_rptr, NULL, OPENSSL_free, V_ASN1_SEQUENCE, and X509_REQ_add1_attr_by_NID().
Referenced by X509_REQ_add_extensions().
X509_REQ_check_private_key()
int X509_REQ_check_private_key (X509_REQ * x, EVP_PKEY * k)
Definition at line 82 of file x509_req.c.
X509_REQ_delete_attr()
X509_ATTRIBUTE* X509_REQ_delete_attr (X509_REQ * req, int loc)
Definition at line 228 of file x509_req.c.
References X509at_delete_attr().
X509_REQ_extension_nid()
int X509_REQ_extension_nid (int req_nid)
Definition at line 131 of file x509_req.c.
References nid.
Referenced by X509_REQ_print_ex().
X509_REQ_get0_pubkey()
EVP_PKEY* X509_REQ_get0_pubkey (X509_REQ * req)
Definition at line 70 of file x509_req.c.
References NULL, and X509_PUBKEY_get0().
Referenced by X509_REQ_print_ex().
X509_REQ_get0_signature()
void X509_REQ_get0_signature (const X509_REQ * req, const ASN1_BIT_STRING ** psig, const X509_ALGOR ** palg)
Definition at line 280 of file x509_req.c.
References NULL.
Referenced by X509_REQ_print_ex().
X509_REQ_get_attr()
X509_ATTRIBUTE* X509_REQ_get_attr (const X509_REQ * req, int loc)
Definition at line 223 of file x509_req.c.
References X509at_get_attr().
Referenced by X509_REQ_print_ex().
X509_REQ_get_attr_by_NID()
int X509_REQ_get_attr_by_NID (const X509_REQ * req, int nid, int lastpos)
Definition at line 212 of file x509_req.c.
References X509at_get_attr_by_NID().
X509_REQ_get_attr_by_OBJ()
int X509_REQ_get_attr_by_OBJ (const X509_REQ * req, const ASN1_OBJECT * obj, int lastpos)
Definition at line 217 of file x509_req.c.
References X509at_get_attr_by_OBJ().
X509_REQ_get_attr_count()
int X509_REQ_get_attr_count (const X509_REQ * req)
Definition at line 207 of file x509_req.c.
References X509at_get_attr_count().
Referenced by X509_REQ_print_ex().
X509_REQ_get_extension_nids()
int* X509_REQ_get_extension_nids (void)
Definition at line 143 of file x509_req.c.
X509_REQ_get_pubkey()
EVP_PKEY* X509_REQ_get_pubkey (X509_REQ * req)
Definition at line 63 of file x509_req.c.
References NULL, and X509_PUBKEY_get().
X509_REQ_get_signature_nid()
int X509_REQ_get_signature_nid (const X509_REQ * req)
Definition at line 289 of file x509_req.c.
References OBJ_obj2nid().
X509_REQ_get_subject_name()
X509_NAME* X509_REQ_get_subject_name (const X509_REQ * req)
Definition at line 275 of file x509_req.c.
Referenced by X509_REQ_print_ex().
X509_REQ_get_version()
long X509_REQ_get_version (const X509_REQ * req)
Definition at line 270 of file x509_req.c.
References ASN1_INTEGER_get().
Referenced by X509_REQ_print_ex().
X509_REQ_get_X509_PUBKEY()
X509_PUBKEY* X509_REQ_get_X509_PUBKEY (X509_REQ * req)
Definition at line 77 of file x509_req.c.
Referenced by X509_REQ_print_ex().
X509_REQ_set_extension_nids()
void X509_REQ_set_extension_nids (int * nids)
Definition at line 148 of file x509_req.c.
X509_to_X509_REQ()
X509_REQ* X509_to_X509_REQ (X509 * x, EVP_PKEY * pkey, const EVP_MD * md)
Definition at line 22 of file x509_req.c.