crypto/x509/x509_set.c File Reference
x509_set.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include "internal/x509_int.h"
Functions
int X509_set_version (X509 *x, long version)
int X509_set_serialNumber (X509 *x, ASN1_INTEGER *serial)
int X509_set_issuer_name (X509 *x, X509_NAME *name)
int X509_set_subject_name (X509 *x, X509_NAME *name)
int x509_set1_time (ASN1_TIME **ptm, const ASN1_TIME *tm)
int X509_set1_notBefore (X509 *x, const ASN1_TIME *tm)
int X509_set1_notAfter (X509 *x, const ASN1_TIME *tm)
int X509_set_pubkey (X509 *x, EVP_PKEY *pkey)
int X509_up_ref (X509 *x)
long X509_get_version (const X509 *x)
const ASN1_TIME * X509_get0_notBefore (const X509 *x)
const ASN1_TIME * X509_get0_notAfter (const X509 *x)
ASN1_TIME * X509_getm_notBefore (const X509 *x)
ASN1_TIME * X509_getm_notAfter (const X509 *x)
int X509_get_signature_type (const X509 *x)
X509_PUBKEY * X509_get_X509_PUBKEY (const X509 *x)
const STACK_OF (X509_EXTENSION)
void X509_get0_uids (const X509 *x, const ASN1_BIT_STRING **piuid, const ASN1_BIT_STRING **psuid)
const X509_ALGOR * X509_get0_tbs_sigalg (const X509 *x)
Function Documentation
STACK_OF()
const STACK_OF (X509_EXTENSION)
Definition at line 142 of file x509_set.c.
X509_get0_notAfter()
const ASN1_TIME* X509_get0_notAfter (const X509 * x)
Definition at line 117 of file x509_set.c.
Referenced by verify_callback().
X509_get0_notBefore()
const ASN1_TIME* X509_get0_notBefore (const X509 * x)
Definition at line 112 of file x509_set.c.
Referenced by verify_callback(), and x509_check_cert_time().
X509_get0_tbs_sigalg()
const X509_ALGOR* X509_get0_tbs_sigalg (const X509 * x)
Definition at line 156 of file x509_set.c.
X509_get0_uids()
void X509_get0_uids (const X509 * x, const ASN1_BIT_STRING ** piuid, const ASN1_BIT_STRING ** psuid)
Definition at line 147 of file x509_set.c.
References NULL.
X509_get_signature_type()
int X509_get_signature_type (const X509 * x)
Definition at line 132 of file x509_set.c.
References EVP_PKEY_type(), and OBJ_obj2nid().
X509_get_version()
long X509_get_version (const X509 * x)
Definition at line 107 of file x509_set.c.
References ASN1_INTEGER_get().
X509_get_X509_PUBKEY()
X509_PUBKEY* X509_get_X509_PUBKEY (const X509 * x)
Definition at line 137 of file x509_set.c.
Referenced by SCT_CTX_set1_issuer().
X509_getm_notAfter()
ASN1_TIME* X509_getm_notAfter (const X509 * x)
Definition at line 127 of file x509_set.c.
Referenced by set_cert_times().
X509_getm_notBefore()
ASN1_TIME* X509_getm_notBefore (const X509 * x)
Definition at line 122 of file x509_set.c.
Referenced by set_cert_times().
X509_set1_notAfter()
int X509_set1_notAfter (X509 * x, const ASN1_TIME * tm)
Definition at line 81 of file x509_set.c.
References NULL, and x509_set1_time().
X509_set1_notBefore()
int X509_set1_notBefore (X509 * x, const ASN1_TIME * tm)
Definition at line 74 of file x509_set.c.
References NULL, and x509_set1_time().
x509_set1_time()
int x509_set1_time (ASN1_TIME ** ptm, const ASN1_TIME * tm)
Definition at line 60 of file x509_set.c.
References ASN1_STRING_dup(), in, and NULL.
Referenced by X509_CRL_set1_lastUpdate(), X509_CRL_set1_nextUpdate(), X509_set1_notAfter(), and X509_set1_notBefore().
X509_set_issuer_name()
int X509_set_issuer_name (X509 * x, X509_NAME * name)
Definition at line 46 of file x509_set.c.
References NULL, and X509_NAME_set().
X509_set_pubkey()
int X509_set_pubkey (X509 * x, EVP_PKEY * pkey)
Definition at line 88 of file x509_set.c.
References NULL, and X509_PUBKEY_set().
X509_set_serialNumber()
int X509_set_serialNumber (X509 * x, ASN1_INTEGER * serial)
Definition at line 34 of file x509_set.c.
References ASN1_STRING_copy(), in, and NULL.
X509_set_subject_name()
int X509_set_subject_name (X509 * x, X509_NAME * name)
Definition at line 53 of file x509_set.c.
References NULL, and X509_NAME_set().
X509_set_version()
int X509_set_version (X509 * x, long version)
Definition at line 18 of file x509_set.c.
References ASN1_INTEGER_set(), and NULL.
X509_up_ref()
int X509_up_ref (X509 * x)
Definition at line 95 of file x509_set.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by CMS_SignerInfo_set1_signer_cert(), CT_POLICY_EVAL_CTX_set1_issuer(), PKCS7_add_certificate(), ssl_cert_add1_chain_cert(), SSL_get_peer_certificate(), ssl_session_dup(), STACK_OF(), TS_RESP_CTX_set_signer_cert(), and X509_OBJECT_up_ref_count().