crypto/x509/x509_vfy.c File Reference
x509_vfy.c File Reference
#include <stdio.h>
#include <time.h>
#include <errno.h>
#include <limits.h>
#include "internal/cryptlib.h"
#include <openssl/crypto.h>
#include <openssl/lhash.h>
#include <openssl/buffer.h>
#include <openssl/evp.h>
#include <openssl/asn1.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/objects.h>
#include <internal/dane.h>
#include <internal/x509_int.h>
#include "x509_lcl.h"
Macros
#define CRL_SCORE_NOCRITICAL 0x100
#define CRL_SCORE_SCOPE 0x080
#define CRL_SCORE_TIME 0x040
#define CRL_SCORE_ISSUER_NAME 0x020
#define CRL_SCORE_VALID (CRL_SCORE_NOCRITICAL|CRL_SCORE_TIME|CRL_SCORE_SCOPE)
#define CRL_SCORE_ISSUER_CERT 0x018
#define CRL_SCORE_SAME_PATH 0x008
#define CRL_SCORE_AKID 0x004
#define CRL_SCORE_TIME_DELTA 0x002
#define DANETLS_NONE 256 /* impossible uint8_t */
#define S_DOUNTRUSTED (1 << 0) /* Search untrusted chain */
#define S_DOTRUSTED (1 << 1) /* Search trusted store */
#define S_DOALTERNATE (1 << 2) /* Retry with pruned alternate chain */
Functions
int X509_verify_cert (X509_STORE_CTX *ctx)
int x509_check_cert_time (X509_STORE_CTX *ctx, X509 *x, int depth)
int X509_cmp_current_time (const ASN1_TIME *ctm)
int X509_cmp_time (const ASN1_TIME *ctm, time_t *cmp_time)
ASN1_TIME * X509_gmtime_adj (ASN1_TIME *s, long adj)
ASN1_TIME * X509_time_adj (ASN1_TIME *s, long offset_sec, time_t *in_tm)
ASN1_TIME * X509_time_adj_ex (ASN1_TIME *s, int offset_day, long offset_sec, time_t *in_tm)
int X509_get_pubkey_parameters (EVP_PKEY *pkey, STACK_OF(X509) *chain)
X509_CRL * X509_CRL_diff (X509_CRL *base, X509_CRL *newer, EVP_PKEY *skey, const EVP_MD *md, unsigned int flags)
int X509_STORE_CTX_set_ex_data (X509_STORE_CTX *ctx, int idx, void *data)
void * X509_STORE_CTX_get_ex_data (X509_STORE_CTX *ctx, int idx)
int X509_STORE_CTX_get_error (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set_error (X509_STORE_CTX *ctx, int err)
int X509_STORE_CTX_get_error_depth (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set_error_depth (X509_STORE_CTX *ctx, int depth)
X509 * X509_STORE_CTX_get_current_cert (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set_current_cert (X509_STORE_CTX *ctx, X509 *x)
X509 * X509_STORE_CTX_get0_current_issuer (X509_STORE_CTX *ctx)
X509_CRL * X509_STORE_CTX_get0_current_crl (X509_STORE_CTX *ctx)
X509_STORE_CTX * X509_STORE_CTX_get0_parent_ctx (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set_cert (X509_STORE_CTX *ctx, X509 *x)
void X509_STORE_CTX_set0_crls (X509_STORE_CTX *ctx, STACK_OF(X509_CRL) *sk)
int X509_STORE_CTX_set_purpose (X509_STORE_CTX *ctx, int purpose)
int X509_STORE_CTX_set_trust (X509_STORE_CTX *ctx, int trust)
int X509_STORE_CTX_purpose_inherit (X509_STORE_CTX *ctx, int def_purpose, int purpose, int trust)
X509_STORE_CTX * X509_STORE_CTX_new (void)
void X509_STORE_CTX_free (X509_STORE_CTX *ctx)
int X509_STORE_CTX_init (X509_STORE_CTX *ctx, X509_STORE *store, X509 *x509, STACK_OF(X509) *chain)
void X509_STORE_CTX_set0_trusted_stack (X509_STORE_CTX *ctx, STACK_OF(X509) *sk)
void X509_STORE_CTX_cleanup (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set_depth (X509_STORE_CTX *ctx, int depth)
void X509_STORE_CTX_set_flags (X509_STORE_CTX *ctx, unsigned long flags)
void X509_STORE_CTX_set_time (X509_STORE_CTX *ctx, unsigned long flags, time_t t)
X509 * X509_STORE_CTX_get0_cert (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set0_untrusted (X509_STORE_CTX *ctx, STACK_OF(X509) *sk)
void X509_STORE_CTX_set0_verified_chain (X509_STORE_CTX *ctx, STACK_OF(X509) *sk)
void X509_STORE_CTX_set_verify_cb (X509_STORE_CTX *ctx, X509_STORE_CTX_verify_cb verify_cb)
X509_STORE_CTX_verify_cb X509_STORE_CTX_get_verify_cb (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set_verify (X509_STORE_CTX *ctx, X509_STORE_CTX_verify_fn verify)
X509_STORE_CTX_verify_fn X509_STORE_CTX_get_verify (X509_STORE_CTX *ctx)
X509_STORE_CTX_get_issuer_fn X509_STORE_CTX_get_get_issuer (X509_STORE_CTX *ctx)
X509_STORE_CTX_check_issued_fn X509_STORE_CTX_get_check_issued (X509_STORE_CTX *ctx)
X509_STORE_CTX_check_revocation_fn X509_STORE_CTX_get_check_revocation (X509_STORE_CTX *ctx)
X509_STORE_CTX_get_crl_fn X509_STORE_CTX_get_get_crl (X509_STORE_CTX *ctx)
X509_STORE_CTX_check_crl_fn X509_STORE_CTX_get_check_crl (X509_STORE_CTX *ctx)
X509_STORE_CTX_cert_crl_fn X509_STORE_CTX_get_cert_crl (X509_STORE_CTX *ctx)
X509_STORE_CTX_check_policy_fn X509_STORE_CTX_get_check_policy (X509_STORE_CTX *ctx)
X509_STORE_CTX_lookup_certs_fn X509_STORE_CTX_get_lookup_certs (X509_STORE_CTX *ctx)
X509_STORE_CTX_lookup_crls_fn X509_STORE_CTX_get_lookup_crls (X509_STORE_CTX *ctx)
X509_STORE_CTX_cleanup_fn X509_STORE_CTX_get_cleanup (X509_STORE_CTX *ctx)
X509_POLICY_TREE * X509_STORE_CTX_get0_policy_tree (X509_STORE_CTX *ctx)
int X509_STORE_CTX_get_explicit_policy (X509_STORE_CTX *ctx)
int X509_STORE_CTX_get_num_untrusted (X509_STORE_CTX *ctx)
int X509_STORE_CTX_set_default (X509_STORE_CTX *ctx, const char *name)
X509_VERIFY_PARAM * X509_STORE_CTX_get0_param (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set0_param (X509_STORE_CTX *ctx, X509_VERIFY_PARAM *param)
void X509_STORE_CTX_set0_dane (X509_STORE_CTX *ctx, SSL_DANE *dane)
Macro Definition Documentation
CRL_SCORE_AKID
#define CRL_SCORE_AKID 0x004
Definition at line 60 of file x509_vfy.c.
CRL_SCORE_ISSUER_CERT
#define CRL_SCORE_ISSUER_CERT 0x018
Definition at line 52 of file x509_vfy.c.
CRL_SCORE_ISSUER_NAME
#define CRL_SCORE_ISSUER_NAME 0x020
Definition at line 44 of file x509_vfy.c.
CRL_SCORE_NOCRITICAL
#define CRL_SCORE_NOCRITICAL 0x100
Definition at line 32 of file x509_vfy.c.
CRL_SCORE_SAME_PATH
#define CRL_SCORE_SAME_PATH 0x008
Definition at line 56 of file x509_vfy.c.
CRL_SCORE_SCOPE
#define CRL_SCORE_SCOPE 0x080
Definition at line 36 of file x509_vfy.c.
CRL_SCORE_TIME
#define CRL_SCORE_TIME 0x040
Definition at line 40 of file x509_vfy.c.
CRL_SCORE_TIME_DELTA
#define CRL_SCORE_TIME_DELTA 0x002
Definition at line 64 of file x509_vfy.c.
CRL_SCORE_VALID
#define CRL_SCORE_VALID (CRL_SCORE_NOCRITICAL|CRL_SCORE_TIME|CRL_SCORE_SCOPE)
Definition at line 48 of file x509_vfy.c.
DANETLS_NONE
#define DANETLS_NONE 256 /* impossible uint8_t */
Definition at line 2577 of file x509_vfy.c.
S_DOALTERNATE
#define S_DOALTERNATE (1 << 2) /* Retry with pruned alternate chain */
S_DOTRUSTED
#define S_DOTRUSTED (1 << 1) /* Search trusted store */
S_DOUNTRUSTED
#define S_DOUNTRUSTED (1 << 0) /* Search untrusted chain */
Function Documentation
x509_check_cert_time()
int x509_check_cert_time (X509_STORE_CTX * ctx, X509 * x, int depth)
Definition at line 1638 of file x509_vfy.c.
References NULL, X509_cmp_time(), X509_get0_notBefore(), X509_V_FLAG_NO_CHECK_TIME, and X509_V_FLAG_USE_CHECK_TIME.
X509_cmp_current_time()
int X509_cmp_current_time (const ASN1_TIME * ctm)
Definition at line 1750 of file x509_vfy.c.
References NULL, and X509_cmp_time().
X509_cmp_time()
int X509_cmp_time (const ASN1_TIME * ctm, time_t * cmp_time)
Definition at line 1755 of file x509_vfy.c.
References if(), NULL, V_ASN1_UTCTIME, and X509_time_adj().
Referenced by x509_check_cert_time(), and X509_cmp_current_time().
X509_CRL_diff()
X509_CRL* X509_CRL_diff (X509_CRL * base, X509_CRL * newer, EVP_PKEY * skey, const EVP_MD * md, unsigned int flags)
Definition at line 1938 of file x509_vfy.c.
X509_get_pubkey_parameters()
int X509_get_pubkey_parameters (EVP_PKEY * pkey, STACK_OF(X509) * chain)
Definition at line 1901 of file x509_vfy.c.
X509_gmtime_adj()
ASN1_TIME* X509_gmtime_adj (ASN1_TIME * s, long adj)
Definition at line 1872 of file x509_vfy.c.
References NULL, and X509_time_adj().
Referenced by OCSP_basic_sign(), PKCS7_add0_attrib_signing_time(), and set_cert_times().
X509_STORE_CTX_cleanup()
void X509_STORE_CTX_cleanup (X509_STORE_CTX * ctx)
Definition at line 2370 of file x509_vfy.c.
References CRYPTO_EX_INDEX_X509_STORE_CTX, CRYPTO_free_ex_data(), NULL, X509_policy_tree_free(), and X509_VERIFY_PARAM_free().
Referenced by X509_STORE_CTX_free().
X509_STORE_CTX_free()
void X509_STORE_CTX_free (X509_STORE_CTX * ctx)
Definition at line 2212 of file x509_vfy.c.
References NULL, OPENSSL_free, and X509_STORE_CTX_cleanup().
Referenced by ssl_build_cert_chain(), and ssl_verify_cert_chain().
X509_STORE_CTX_get0_cert()
X509* X509_STORE_CTX_get0_cert (X509_STORE_CTX * ctx)
Definition at line 2412 of file x509_vfy.c.
X509_STORE_CTX_get0_current_crl()
X509_CRL* X509_STORE_CTX_get0_current_crl (X509_STORE_CTX * ctx)
Definition at line 2100 of file x509_vfy.c.
X509_STORE_CTX_get0_current_issuer()
X509* X509_STORE_CTX_get0_current_issuer (X509_STORE_CTX * ctx)
Definition at line 2095 of file x509_vfy.c.
X509_STORE_CTX_get0_param()
X509_VERIFY_PARAM* X509_STORE_CTX_get0_param (X509_STORE_CTX * ctx)
Definition at line 2529 of file x509_vfy.c.
Referenced by ssl_verify_cert_chain().
X509_STORE_CTX_get0_parent_ctx()
X509_STORE_CTX* X509_STORE_CTX_get0_parent_ctx (X509_STORE_CTX * ctx)
Definition at line 2105 of file x509_vfy.c.
X509_STORE_CTX_get0_policy_tree()
X509_POLICY_TREE* X509_STORE_CTX_get0_policy_tree (X509_STORE_CTX * ctx)
Definition at line 2505 of file x509_vfy.c.
Referenced by policies_print().
X509_STORE_CTX_get_cert_crl()
X509_STORE_CTX_cert_crl_fn X509_STORE_CTX_get_cert_crl (X509_STORE_CTX * ctx)
Definition at line 2480 of file x509_vfy.c.
X509_STORE_CTX_get_check_crl()
X509_STORE_CTX_check_crl_fn X509_STORE_CTX_get_check_crl (X509_STORE_CTX * ctx)
Definition at line 2475 of file x509_vfy.c.
X509_STORE_CTX_get_check_issued()
X509_STORE_CTX_check_issued_fn X509_STORE_CTX_get_check_issued (X509_STORE_CTX * ctx)
Definition at line 2460 of file x509_vfy.c.
X509_STORE_CTX_get_check_policy()
X509_STORE_CTX_check_policy_fn X509_STORE_CTX_get_check_policy (X509_STORE_CTX * ctx)
Definition at line 2485 of file x509_vfy.c.
X509_STORE_CTX_get_check_revocation()
X509_STORE_CTX_check_revocation_fn X509_STORE_CTX_get_check_revocation (X509_STORE_CTX * ctx)
Definition at line 2465 of file x509_vfy.c.
X509_STORE_CTX_get_cleanup()
X509_STORE_CTX_cleanup_fn X509_STORE_CTX_get_cleanup (X509_STORE_CTX * ctx)
Definition at line 2500 of file x509_vfy.c.
X509_STORE_CTX_get_current_cert()
X509* X509_STORE_CTX_get_current_cert (X509_STORE_CTX * ctx)
Definition at line 2073 of file x509_vfy.c.
Referenced by verify_callback().
X509_STORE_CTX_get_error()
int X509_STORE_CTX_get_error (X509_STORE_CTX * ctx)
Definition at line 2053 of file x509_vfy.c.
Referenced by ssl_build_cert_chain(), ssl_verify_cert_chain(), and verify_callback().
X509_STORE_CTX_get_error_depth()
int X509_STORE_CTX_get_error_depth (X509_STORE_CTX * ctx)
Definition at line 2063 of file x509_vfy.c.
Referenced by verify_callback().
X509_STORE_CTX_get_ex_data()
void* X509_STORE_CTX_get_ex_data (X509_STORE_CTX * ctx, int idx)
Definition at line 2048 of file x509_vfy.c.
X509_STORE_CTX_get_explicit_policy()
int X509_STORE_CTX_get_explicit_policy (X509_STORE_CTX * ctx)
Definition at line 2510 of file x509_vfy.c.
Referenced by policies_print().
X509_STORE_CTX_get_get_crl()
X509_STORE_CTX_get_crl_fn X509_STORE_CTX_get_get_crl (X509_STORE_CTX * ctx)
Definition at line 2470 of file x509_vfy.c.
X509_STORE_CTX_get_get_issuer()
X509_STORE_CTX_get_issuer_fn X509_STORE_CTX_get_get_issuer (X509_STORE_CTX * ctx)
Definition at line 2455 of file x509_vfy.c.
X509_STORE_CTX_get_lookup_certs()
X509_STORE_CTX_lookup_certs_fn X509_STORE_CTX_get_lookup_certs (X509_STORE_CTX * ctx)
Definition at line 2490 of file x509_vfy.c.
X509_STORE_CTX_get_lookup_crls()
X509_STORE_CTX_lookup_crls_fn X509_STORE_CTX_get_lookup_crls (X509_STORE_CTX * ctx)
Definition at line 2495 of file x509_vfy.c.
X509_STORE_CTX_get_num_untrusted()
int X509_STORE_CTX_get_num_untrusted (X509_STORE_CTX * ctx)
Definition at line 2515 of file x509_vfy.c.
X509_STORE_CTX_get_verify()
X509_STORE_CTX_verify_fn X509_STORE_CTX_get_verify (X509_STORE_CTX * ctx)
Definition at line 2450 of file x509_vfy.c.
X509_STORE_CTX_get_verify_cb()
X509_STORE_CTX_verify_cb X509_STORE_CTX_get_verify_cb (X509_STORE_CTX * ctx)
Definition at line 2439 of file x509_vfy.c.
X509_STORE_CTX_init()
int X509_STORE_CTX_init (X509_STORE_CTX * ctx, X509_STORE * store, X509 * x509, STACK_OF(X509) * chain)
Definition at line 2221 of file x509_vfy.c.
Referenced by ssl_build_cert_chain(), and ssl_verify_cert_chain().
X509_STORE_CTX_new()
X509_STORE_CTX* X509_STORE_CTX_new (void)
Definition at line 2201 of file x509_vfy.c.
References ctx, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_zalloc, X509_F_X509_STORE_CTX_NEW, and X509err.
Referenced by OCSP_request_verify(), ssl_build_cert_chain(), and ssl_verify_cert_chain().
X509_STORE_CTX_purpose_inherit()
int X509_STORE_CTX_purpose_inherit (X509_STORE_CTX * ctx, int def_purpose, int purpose, int trust)
Definition at line 2150 of file x509_vfy.c.
Referenced by X509_STORE_CTX_set_purpose(), and X509_STORE_CTX_set_trust().
X509_STORE_CTX_set0_crls()
void X509_STORE_CTX_set0_crls (X509_STORE_CTX * ctx, STACK_OF(X509_CRL) * sk)
Definition at line 2115 of file x509_vfy.c.
X509_STORE_CTX_set0_dane()
void X509_STORE_CTX_set0_dane (X509_STORE_CTX * ctx, SSL_DANE * dane)
Definition at line 2540 of file x509_vfy.c.
Referenced by ssl_verify_cert_chain().
X509_STORE_CTX_set0_param()
void X509_STORE_CTX_set0_param (X509_STORE_CTX * ctx, X509_VERIFY_PARAM * param)
Definition at line 2534 of file x509_vfy.c.
References X509_VERIFY_PARAM_free().
X509_STORE_CTX_set0_trusted_stack()
void X509_STORE_CTX_set0_trusted_stack (X509_STORE_CTX * ctx, STACK_OF(X509) * sk)
Definition at line 2363 of file x509_vfy.c.
X509_STORE_CTX_set0_untrusted()
void X509_STORE_CTX_set0_untrusted (X509_STORE_CTX * ctx, STACK_OF(X509) * sk)
Definition at line 2422 of file x509_vfy.c.
X509_STORE_CTX_set0_verified_chain()
void X509_STORE_CTX_set0_verified_chain (X509_STORE_CTX * ctx, STACK_OF(X509) * sk)
Definition at line 2427 of file x509_vfy.c.
X509_STORE_CTX_set_cert()
void X509_STORE_CTX_set_cert (X509_STORE_CTX * ctx, X509 * x)
Definition at line 2110 of file x509_vfy.c.
X509_STORE_CTX_set_current_cert()
void X509_STORE_CTX_set_current_cert (X509_STORE_CTX * ctx, X509 * x)
Definition at line 2078 of file x509_vfy.c.
X509_STORE_CTX_set_default()
int X509_STORE_CTX_set_default (X509_STORE_CTX * ctx, const char * name)
Definition at line 2520 of file x509_vfy.c.
References X509_VERIFY_PARAM_inherit(), and X509_VERIFY_PARAM_lookup().
Referenced by ssl_verify_cert_chain().
X509_STORE_CTX_set_depth()
void X509_STORE_CTX_set_depth (X509_STORE_CTX * ctx, int depth)
Definition at line 2396 of file x509_vfy.c.
References X509_VERIFY_PARAM_set_depth().
X509_STORE_CTX_set_error()
void X509_STORE_CTX_set_error (X509_STORE_CTX * ctx, int err)
Definition at line 2058 of file x509_vfy.c.
X509_STORE_CTX_set_error_depth()
void X509_STORE_CTX_set_error_depth (X509_STORE_CTX * ctx, int depth)
Definition at line 2068 of file x509_vfy.c.
X509_STORE_CTX_set_ex_data()
int X509_STORE_CTX_set_ex_data (X509_STORE_CTX * ctx, int idx, void * data)
Definition at line 2043 of file x509_vfy.c.
Referenced by ssl_verify_cert_chain().
X509_STORE_CTX_set_flags()
void X509_STORE_CTX_set_flags (X509_STORE_CTX * ctx, unsigned long flags)
Definition at line 2401 of file x509_vfy.c.
References X509_VERIFY_PARAM_set_flags().
Referenced by ssl_build_cert_chain(), and ssl_verify_cert_chain().
X509_STORE_CTX_set_purpose()
int X509_STORE_CTX_set_purpose (X509_STORE_CTX * ctx, int purpose)
Definition at line 2120 of file x509_vfy.c.
References X509_STORE_CTX_purpose_inherit().
X509_STORE_CTX_set_time()
void X509_STORE_CTX_set_time (X509_STORE_CTX * ctx, unsigned long flags, time_t t)
Definition at line 2406 of file x509_vfy.c.
References X509_VERIFY_PARAM_set_time().
X509_STORE_CTX_set_trust()
int X509_STORE_CTX_set_trust (X509_STORE_CTX * ctx, int trust)
Definition at line 2130 of file x509_vfy.c.
References X509_STORE_CTX_purpose_inherit().
X509_STORE_CTX_set_verify()
void X509_STORE_CTX_set_verify (X509_STORE_CTX * ctx, X509_STORE_CTX_verify_fn verify)
Definition at line 2444 of file x509_vfy.c.
X509_STORE_CTX_set_verify_cb()
void X509_STORE_CTX_set_verify_cb (X509_STORE_CTX * ctx, X509_STORE_CTX_verify_cb verify_cb)
Definition at line 2433 of file x509_vfy.c.
Referenced by ssl_verify_cert_chain().
X509_time_adj()
ASN1_TIME* X509_time_adj (ASN1_TIME * s, long offset_sec, time_t * in_tm)
Definition at line 1877 of file x509_vfy.c.
References X509_time_adj_ex().
Referenced by X509_cmp_time(), and X509_gmtime_adj().
X509_time_adj_ex()
ASN1_TIME* X509_time_adj_ex (ASN1_TIME * s, int offset_day, long offset_sec, time_t * in_tm)
Definition at line 1882 of file x509_vfy.c.
References ASN1_GENERALIZEDTIME_adj(), ASN1_STRING_FLAG_MSTRING, ASN1_TIME_adj(), ASN1_UTCTIME_adj(), t, V_ASN1_GENERALIZEDTIME, and V_ASN1_UTCTIME.
Referenced by set_cert_times(), and X509_time_adj().
X509_verify_cert()
int X509_verify_cert (X509_STORE_CTX * ctx)
Definition at line 251 of file x509_vfy.c.
Referenced by ssl_build_cert_chain(), and ssl_verify_cert_chain().