crypto/x509/x509name.c File Reference
x509name.c File Reference
#include <stdio.h>
#include <openssl/stack.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include "internal/x509_int.h"
Functions
int X509_NAME_get_text_by_NID (X509_NAME *name, int nid, char *buf, int len)
int X509_NAME_get_text_by_OBJ (X509_NAME *name, const ASN1_OBJECT *obj, char *buf, int len)
int X509_NAME_entry_count (const X509_NAME *name)
int X509_NAME_get_index_by_NID (X509_NAME *name, int nid, int lastpos)
int X509_NAME_get_index_by_OBJ (X509_NAME *name, const ASN1_OBJECT *obj, int lastpos)
X509_NAME_ENTRY * X509_NAME_get_entry (const X509_NAME *name, int loc)
X509_NAME_ENTRY * X509_NAME_delete_entry (X509_NAME *name, int loc)
int X509_NAME_add_entry_by_OBJ (X509_NAME *name, const ASN1_OBJECT *obj, int type, const unsigned char *bytes, int len, int loc, int set)
int X509_NAME_add_entry_by_NID (X509_NAME *name, int nid, int type, const unsigned char *bytes, int len, int loc, int set)
int X509_NAME_add_entry_by_txt (X509_NAME *name, const char *field, int type, const unsigned char *bytes, int len, int loc, int set)
int X509_NAME_add_entry (X509_NAME *name, const X509_NAME_ENTRY *ne, int loc, int set)
X509_NAME_ENTRY * X509_NAME_ENTRY_create_by_txt (X509_NAME_ENTRY **ne, const char *field, int type, const unsigned char *bytes, int len)
X509_NAME_ENTRY * X509_NAME_ENTRY_create_by_NID (X509_NAME_ENTRY **ne, int nid, int type, const unsigned char *bytes, int len)
X509_NAME_ENTRY * X509_NAME_ENTRY_create_by_OBJ (X509_NAME_ENTRY **ne, const ASN1_OBJECT *obj, int type, const unsigned char *bytes, int len)
int X509_NAME_ENTRY_set_object (X509_NAME_ENTRY *ne, const ASN1_OBJECT *obj)
int X509_NAME_ENTRY_set_data (X509_NAME_ENTRY *ne, int type, const unsigned char *bytes, int len)
ASN1_OBJECT * X509_NAME_ENTRY_get_object (const X509_NAME_ENTRY *ne)
ASN1_STRING * X509_NAME_ENTRY_get_data (const X509_NAME_ENTRY *ne)
int X509_NAME_ENTRY_set (const X509_NAME_ENTRY *ne)
Function Documentation
X509_NAME_add_entry()
int X509_NAME_add_entry (X509_NAME * name, const X509_NAME_ENTRY * ne, int loc, int set)
Definition at line 181 of file x509name.c.
References ERR_R_MALLOC_FAILURE, NULL, STACK_OF, X509_F_X509_NAME_ADD_ENTRY, X509_NAME_ENTRY_dup(), and X509err.
X509_NAME_add_entry_by_NID()
int X509_NAME_add_entry_by_NID (X509_NAME * name, int nid, int type, const unsigned char * bytes, int len, int loc, int set)
Definition at line 149 of file x509name.c.
Referenced by parse_name().
X509_NAME_add_entry_by_OBJ()
int X509_NAME_add_entry_by_OBJ (X509_NAME * name, const ASN1_OBJECT * obj, int type, const unsigned char * bytes, int len, int loc, int set)
Definition at line 134 of file x509name.c.
X509_NAME_add_entry_by_txt()
int X509_NAME_add_entry_by_txt (X509_NAME * name, const char * field, int type, const unsigned char * bytes, int len, int loc, int set)
Definition at line 163 of file x509name.c.
Referenced by X509V3_NAME_from_section().
X509_NAME_delete_entry()
X509_NAME_ENTRY* X509_NAME_delete_entry (X509_NAME * name, int loc)
Definition at line 94 of file x509name.c.
X509_NAME_entry_count()
int X509_NAME_entry_count (const X509_NAME * name)
Definition at line 47 of file x509name.c.
References NULL.
X509_NAME_ENTRY_create_by_NID()
X509_NAME_ENTRY* X509_NAME_ENTRY_create_by_NID (X509_NAME_ENTRY ** ne, int nid, int type, const unsigned char * bytes, int len)
Definition at line 261 of file x509name.c.
References ASN1_OBJECT_free(), NULL, obj, OBJ_nid2obj(), X509_F_X509_NAME_ENTRY_CREATE_BY_NID, X509_NAME_ENTRY_create_by_OBJ(), X509_R_UNKNOWN_NID, and X509err.
X509_NAME_ENTRY_create_by_OBJ()
X509_NAME_ENTRY* X509_NAME_ENTRY_create_by_OBJ (X509_NAME_ENTRY ** ne, const ASN1_OBJECT * obj, int type, const unsigned char * bytes, int len)
Definition at line 279 of file x509name.c.
Referenced by X509_NAME_ENTRY_create_by_NID(), and X509_NAME_ENTRY_create_by_txt().
X509_NAME_ENTRY_create_by_txt()
X509_NAME_ENTRY* X509_NAME_ENTRY_create_by_txt (X509_NAME_ENTRY ** ne, const char * field, int type, const unsigned char * bytes, int len)
Definition at line 241 of file x509name.c.
References ASN1_OBJECT_free(), ERR_add_error_data(), NULL, obj, OBJ_txt2obj(), X509_F_X509_NAME_ENTRY_CREATE_BY_TXT, X509_NAME_ENTRY_create_by_OBJ(), X509_R_INVALID_FIELD_NAME, and X509err.
X509_NAME_ENTRY_get_data()
ASN1_STRING* X509_NAME_ENTRY_get_data (const X509_NAME_ENTRY * ne)
Definition at line 350 of file x509name.c.
References NULL.
X509_NAME_ENTRY_get_object()
ASN1_OBJECT* X509_NAME_ENTRY_get_object (const X509_NAME_ENTRY * ne)
Definition at line 343 of file x509name.c.
References NULL.
X509_NAME_ENTRY_set()
int X509_NAME_ENTRY_set (const X509_NAME_ENTRY * ne)
Definition at line 357 of file x509name.c.
X509_NAME_ENTRY_set_data()
int X509_NAME_ENTRY_set_data (X509_NAME_ENTRY * ne, int type, const unsigned char * bytes, int len)
Definition at line 318 of file x509name.c.
References ASN1_PRINTABLE_type(), ASN1_STRING_set(), ASN1_STRING_set_by_NID(), MBSTRING_FLAG, NULL, OBJ_obj2nid(), type, V_ASN1_APP_CHOOSE, and V_ASN1_UNDEF.
X509_NAME_ENTRY_set_object()
int X509_NAME_ENTRY_set_object (X509_NAME_ENTRY * ne, const ASN1_OBJECT * obj)
Definition at line 306 of file x509name.c.
References ASN1_OBJECT_free(), ERR_R_PASSED_NULL_PARAMETER, NULL, OBJ_dup(), X509_F_X509_NAME_ENTRY_SET_OBJECT, and X509err.
X509_NAME_get_entry()
X509_NAME_ENTRY* X509_NAME_get_entry (const X509_NAME * name, int loc)
Definition at line 85 of file x509name.c.
References NULL.
X509_NAME_get_index_by_NID()
int X509_NAME_get_index_by_NID (X509_NAME * name, int nid, int lastpos)
Definition at line 54 of file x509name.c.
References NULL, obj, OBJ_nid2obj(), and X509_NAME_get_index_by_OBJ().
X509_NAME_get_index_by_OBJ()
int X509_NAME_get_index_by_OBJ (X509_NAME * name, const ASN1_OBJECT * obj, int lastpos)
Definition at line 65 of file x509name.c.
References NULL, OBJ_cmp(), and STACK_OF.
Referenced by X509_NAME_get_index_by_NID().
X509_NAME_get_text_by_NID()
int X509_NAME_get_text_by_NID (X509_NAME * name, int nid, char * buf, int len)
Definition at line 19 of file x509name.c.
X509_NAME_get_text_by_OBJ()
int X509_NAME_get_text_by_OBJ (X509_NAME * name, const ASN1_OBJECT * obj, char * buf, int len)
Definition at line 29 of file x509name.c.