crypto/x509/x509rset.c File Reference
x509rset.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include "internal/x509_int.h"
Functions
int X509_REQ_set_version (X509_REQ *x, long version)
int X509_REQ_set_subject_name (X509_REQ *x, X509_NAME *name)
int X509_REQ_set_pubkey (X509_REQ *x, EVP_PKEY *pkey)
Function Documentation
X509_REQ_set_pubkey()
int X509_REQ_set_pubkey (X509_REQ * x, EVP_PKEY * pkey)
Definition at line 34 of file x509rset.c.
References NULL, and X509_PUBKEY_set().
X509_REQ_set_subject_name()
int X509_REQ_set_subject_name (X509_REQ * x, X509_NAME * name)
Definition at line 26 of file x509rset.c.
References NULL, and X509_NAME_set().
X509_REQ_set_version()
int X509_REQ_set_version (X509_REQ * x, long version)
Definition at line 18 of file x509rset.c.
References ASN1_INTEGER_set(), and NULL.