crypto/x509/x509_v3.c File Reference
x509_v3.c File Reference
#include <stdio.h>
#include <openssl/stack.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include "x509_lcl.h"
Functions
int X509v3_get_ext_count (const STACK_OF(X509_EXTENSION) *x)
int X509v3_get_ext_by_NID (const STACK_OF(X509_EXTENSION) *x, int nid, int lastpos)
int X509v3_get_ext_by_OBJ (const STACK_OF(X509_EXTENSION) *sk, const ASN1_OBJECT *obj, int lastpos)
int X509v3_get_ext_by_critical (const STACK_OF(X509_EXTENSION) *sk, int crit, int lastpos)
X509_EXTENSION * X509v3_get_ext (const STACK_OF(X509_EXTENSION) *x, int loc)
X509_EXTENSION * X509v3_delete_ext (STACK_OF(X509_EXTENSION) *x, int loc)
STACK_OF (X509_EXTENSION)
X509_EXTENSION * X509_EXTENSION_create_by_NID (X509_EXTENSION **ex, int nid, int crit, ASN1_OCTET_STRING *data)
X509_EXTENSION * X509_EXTENSION_create_by_OBJ (X509_EXTENSION **ex, const ASN1_OBJECT *obj, int crit, ASN1_OCTET_STRING *data)
int X509_EXTENSION_set_object (X509_EXTENSION *ex, const ASN1_OBJECT *obj)
int X509_EXTENSION_set_critical (X509_EXTENSION *ex, int crit)
int X509_EXTENSION_set_data (X509_EXTENSION *ex, ASN1_OCTET_STRING *data)
ASN1_OBJECT * X509_EXTENSION_get_object (X509_EXTENSION *ex)
ASN1_OCTET_STRING * X509_EXTENSION_get_data (X509_EXTENSION *ex)
int X509_EXTENSION_get_critical (const X509_EXTENSION *ex)
Function Documentation
STACK_OF()
STACK_OF (X509_EXTENSION)
Definition at line 96 of file x509_v3.c.
References ERR_R_MALLOC_FAILURE, ERR_R_PASSED_NULL_PARAMETER, NULL, X509_EXTENSION_dup(), X509_F_X509V3_ADD_EXT, and X509err.
X509_EXTENSION_create_by_NID()
X509_EXTENSION* X509_EXTENSION_create_by_NID (X509_EXTENSION ** ex, int nid, int crit, ASN1_OCTET_STRING * data)
Definition at line 135 of file x509_v3.c.
References obj.
X509_EXTENSION_create_by_OBJ()
X509_EXTENSION* X509_EXTENSION_create_by_OBJ (X509_EXTENSION ** ex, const ASN1_OBJECT * obj, int crit, ASN1_OCTET_STRING * data)
Definition at line 153 of file x509_v3.c.
X509_EXTENSION_get_critical()
int X509_EXTENSION_get_critical (const X509_EXTENSION * ex)
Definition at line 227 of file x509_v3.c.
References NULL.
Referenced by TS_ext_print_bio(), and X509_REQ_print_ex().
X509_EXTENSION_get_data()
ASN1_OCTET_STRING* X509_EXTENSION_get_data (X509_EXTENSION * ex)
Definition at line 220 of file x509_v3.c.
References NULL.
Referenced by OCSP_check_nonce(), TS_ext_print_bio(), X509_REQ_print_ex(), and X509V3_EXT_d2i().
X509_EXTENSION_get_object()
ASN1_OBJECT* X509_EXTENSION_get_object (X509_EXTENSION * ex)
Definition at line 213 of file x509_v3.c.
References NULL.
Referenced by TS_ext_print_bio(), X509_REQ_print_ex(), X509_supported_extension(), and X509V3_EXT_get().
X509_EXTENSION_set_critical()
int X509_EXTENSION_set_critical (X509_EXTENSION * ex, int crit)
Definition at line 193 of file x509_v3.c.
References NULL.
X509_EXTENSION_set_data()
int X509_EXTENSION_set_data (X509_EXTENSION * ex, ASN1_OCTET_STRING * data)
Definition at line 201 of file x509_v3.c.
References ASN1_OCTET_STRING_set(), and NULL.
X509_EXTENSION_set_object()
int X509_EXTENSION_set_object (X509_EXTENSION * ex, const ASN1_OBJECT * obj)
Definition at line 184 of file x509_v3.c.
References ASN1_OBJECT_free(), NULL, and OBJ_dup().
X509v3_delete_ext()
X509_EXTENSION* X509v3_delete_ext (STACK_OF(X509_EXTENSION) * x, int loc)
Definition at line 86 of file x509_v3.c.
Referenced by OCSP_BASICRESP_delete_ext(), OCSP_ONEREQ_delete_ext(), OCSP_REQUEST_delete_ext(), OCSP_SINGLERESP_delete_ext(), TS_REQ_delete_ext(), TS_TST_INFO_delete_ext(), X509_CRL_delete_ext(), X509_delete_ext(), and X509_REVOKED_delete_ext().
X509v3_get_ext()
X509_EXTENSION* X509v3_get_ext (const STACK_OF(X509_EXTENSION) * x, int loc)
Definition at line 78 of file x509_v3.c.
References NULL.
Referenced by OCSP_BASICRESP_get_ext(), OCSP_ONEREQ_get_ext(), OCSP_REQUEST_get_ext(), OCSP_SINGLERESP_get_ext(), TS_ext_print_bio(), TS_REQ_get_ext(), TS_TST_INFO_get_ext(), X509_CRL_get_ext(), X509_get_ext(), and X509_REVOKED_get_ext().
X509v3_get_ext_by_critical()
int X509v3_get_ext_by_critical (const STACK_OF(X509_EXTENSION) * sk, int crit, int lastpos)
Definition at line 58 of file x509_v3.c.
References ex, and NULL.
Referenced by OCSP_BASICRESP_get_ext_by_critical(), OCSP_ONEREQ_get_ext_by_critical(), OCSP_REQUEST_get_ext_by_critical(), OCSP_SINGLERESP_get_ext_by_critical(), TS_REQ_get_ext_by_critical(), TS_TST_INFO_get_ext_by_critical(), X509_CRL_get_ext_by_critical(), X509_get_ext_by_critical(), and X509_REVOKED_get_ext_by_critical().
X509v3_get_ext_by_NID()
int X509v3_get_ext_by_NID (const STACK_OF(X509_EXTENSION) * x, int nid, int lastpos)
Definition at line 27 of file x509_v3.c.
References NULL, obj, OBJ_nid2obj(), and X509v3_get_ext_by_OBJ().
Referenced by OCSP_BASICRESP_get_ext_by_NID(), OCSP_ONEREQ_get_ext_by_NID(), OCSP_REQUEST_get_ext_by_NID(), OCSP_SINGLERESP_get_ext_by_NID(), TS_REQ_get_ext_by_NID(), TS_TST_INFO_get_ext_by_NID(), X509_CRL_get_ext_by_NID(), X509_get_ext_by_NID(), and X509_REVOKED_get_ext_by_NID().
X509v3_get_ext_by_OBJ()
int X509v3_get_ext_by_OBJ (const STACK_OF(X509_EXTENSION) * sk, const ASN1_OBJECT * obj, int lastpos)
Definition at line 38 of file x509_v3.c.
References ex, NULL, and OBJ_cmp().
Referenced by OCSP_BASICRESP_get_ext_by_OBJ(), OCSP_ONEREQ_get_ext_by_OBJ(), OCSP_REQUEST_get_ext_by_OBJ(), OCSP_SINGLERESP_get_ext_by_OBJ(), TS_REQ_get_ext_by_OBJ(), TS_TST_INFO_get_ext_by_OBJ(), X509_CRL_get_ext_by_OBJ(), X509_get_ext_by_OBJ(), X509_REVOKED_get_ext_by_OBJ(), and X509v3_get_ext_by_NID().
X509v3_get_ext_count()
int X509v3_get_ext_count (const STACK_OF(X509_EXTENSION) * x)
Definition at line 20 of file x509_v3.c.
References NULL.
Referenced by OCSP_BASICRESP_get_ext_count(), OCSP_ONEREQ_get_ext_count(), OCSP_REQUEST_get_ext_count(), OCSP_SINGLERESP_get_ext_count(), TS_ext_print_bio(), TS_REQ_get_ext_count(), TS_TST_INFO_get_ext_count(), X509_CRL_get_ext_count(), X509_get_ext_count(), and X509_REVOKED_get_ext_count().