include/openssl/x509_vfy.h File Reference
x509_vfy.h File Reference
#include <openssl/x509.h>
#include <openssl/opensslconf.h>
#include <openssl/lhash.h>
#include <openssl/bio.h>
#include <openssl/crypto.h>
#include <openssl/symhacks.h>
Macros
#define X509_LU_RETRY -1
#define X509_LU_FAIL 0
#define X509_STORE_CTX_set_app_data(ctx, data) X509_STORE_CTX_set_ex_data(ctx,0,data)
#define X509_STORE_CTX_get_app_data(ctx) X509_STORE_CTX_get_ex_data(ctx,0)
#define X509_L_FILE_LOAD 1
#define X509_L_ADD_DIR 2
#define X509_LOOKUP_load_file(x, name, type) X509_LOOKUP_ctrl((x),X509_L_FILE_LOAD,(name),(long)(type),NULL)
#define X509_LOOKUP_add_dir(x, name, type) X509_LOOKUP_ctrl((x),X509_L_ADD_DIR,(name),(long)(type),NULL)
#define X509_V_OK 0
#define X509_V_ERR_UNSPECIFIED 1
#define X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT 2
#define X509_V_ERR_UNABLE_TO_GET_CRL 3
#define X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE 4
#define X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE 5
#define X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY 6
#define X509_V_ERR_CERT_SIGNATURE_FAILURE 7
#define X509_V_ERR_CRL_SIGNATURE_FAILURE 8
#define X509_V_ERR_CERT_NOT_YET_VALID 9
#define X509_V_ERR_CERT_HAS_EXPIRED 10
#define X509_V_ERR_CRL_NOT_YET_VALID 11
#define X509_V_ERR_CRL_HAS_EXPIRED 12
#define X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD 13
#define X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD 14
#define X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD 15
#define X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD 16
#define X509_V_ERR_OUT_OF_MEM 17
#define X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT 18
#define X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN 19
#define X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY 20
#define X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE 21
#define X509_V_ERR_CERT_CHAIN_TOO_LONG 22
#define X509_V_ERR_CERT_REVOKED 23
#define X509_V_ERR_INVALID_CA 24
#define X509_V_ERR_PATH_LENGTH_EXCEEDED 25
#define X509_V_ERR_INVALID_PURPOSE 26
#define X509_V_ERR_CERT_UNTRUSTED 27
#define X509_V_ERR_CERT_REJECTED 28
#define X509_V_ERR_SUBJECT_ISSUER_MISMATCH 29
#define X509_V_ERR_AKID_SKID_MISMATCH 30
#define X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH 31
#define X509_V_ERR_KEYUSAGE_NO_CERTSIGN 32
#define X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER 33
#define X509_V_ERR_UNHANDLED_CRITICAL_EXTENSION 34
#define X509_V_ERR_KEYUSAGE_NO_CRL_SIGN 35
#define X509_V_ERR_UNHANDLED_CRITICAL_CRL_EXTENSION 36
#define X509_V_ERR_INVALID_NON_CA 37
#define X509_V_ERR_PROXY_PATH_LENGTH_EXCEEDED 38
#define X509_V_ERR_KEYUSAGE_NO_DIGITAL_SIGNATURE 39
#define X509_V_ERR_PROXY_CERTIFICATES_NOT_ALLOWED 40
#define X509_V_ERR_INVALID_EXTENSION 41
#define X509_V_ERR_INVALID_POLICY_EXTENSION 42
#define X509_V_ERR_NO_EXPLICIT_POLICY 43
#define X509_V_ERR_DIFFERENT_CRL_SCOPE 44
#define X509_V_ERR_UNSUPPORTED_EXTENSION_FEATURE 45
#define X509_V_ERR_UNNESTED_RESOURCE 46
#define X509_V_ERR_PERMITTED_VIOLATION 47
#define X509_V_ERR_EXCLUDED_VIOLATION 48
#define X509_V_ERR_SUBTREE_MINMAX 49
#define X509_V_ERR_APPLICATION_VERIFICATION 50
#define X509_V_ERR_UNSUPPORTED_CONSTRAINT_TYPE 51
#define X509_V_ERR_UNSUPPORTED_CONSTRAINT_SYNTAX 52
#define X509_V_ERR_UNSUPPORTED_NAME_SYNTAX 53
#define X509_V_ERR_CRL_PATH_VALIDATION_ERROR 54
#define X509_V_ERR_PATH_LOOP 55
#define X509_V_ERR_SUITE_B_INVALID_VERSION 56
#define X509_V_ERR_SUITE_B_INVALID_ALGORITHM 57
#define X509_V_ERR_SUITE_B_INVALID_CURVE 58
#define X509_V_ERR_SUITE_B_INVALID_SIGNATURE_ALGORITHM 59
#define X509_V_ERR_SUITE_B_LOS_NOT_ALLOWED 60
#define X509_V_ERR_SUITE_B_CANNOT_SIGN_P_384_WITH_P_256 61
#define X509_V_ERR_HOSTNAME_MISMATCH 62
#define X509_V_ERR_EMAIL_MISMATCH 63
#define X509_V_ERR_IP_ADDRESS_MISMATCH 64
#define X509_V_ERR_DANE_NO_MATCH 65
#define X509_V_ERR_EE_KEY_TOO_SMALL 66
#define X509_V_ERR_CA_KEY_TOO_SMALL 67
#define X509_V_ERR_CA_MD_TOO_WEAK 68
#define X509_V_ERR_INVALID_CALL 69
#define X509_V_ERR_STORE_LOOKUP 70
#define X509_V_ERR_NO_VALID_SCTS 71
#define X509_V_ERR_PROXY_SUBJECT_NAME_VIOLATION 72
#define X509_V_FLAG_CB_ISSUER_CHECK 0x0 /* Deprecated */
#define X509_V_FLAG_USE_CHECK_TIME 0x2
#define X509_V_FLAG_CRL_CHECK 0x4
#define X509_V_FLAG_CRL_CHECK_ALL 0x8
#define X509_V_FLAG_IGNORE_CRITICAL 0x10
#define X509_V_FLAG_X509_STRICT 0x20
#define X509_V_FLAG_ALLOW_PROXY_CERTS 0x40
#define X509_V_FLAG_POLICY_CHECK 0x80
#define X509_V_FLAG_EXPLICIT_POLICY 0x100
#define X509_V_FLAG_INHIBIT_ANY 0x200
#define X509_V_FLAG_INHIBIT_MAP 0x400
#define X509_V_FLAG_NOTIFY_POLICY 0x800
#define X509_V_FLAG_EXTENDED_CRL_SUPPORT 0x1000
#define X509_V_FLAG_USE_DELTAS 0x2000
#define X509_V_FLAG_CHECK_SS_SIGNATURE 0x4000
#define X509_V_FLAG_TRUSTED_FIRST 0x8000
#define X509_V_FLAG_SUITEB_128_LOS_ONLY 0x10000
#define X509_V_FLAG_SUITEB_192_LOS 0x20000
#define X509_V_FLAG_SUITEB_128_LOS 0x30000
#define X509_V_FLAG_PARTIAL_CHAIN 0x80000
#define X509_V_FLAG_NO_ALT_CHAINS 0x100000
#define X509_V_FLAG_NO_CHECK_TIME 0x200000
#define X509_VP_FLAG_DEFAULT 0x1
#define X509_VP_FLAG_OVERWRITE 0x2
#define X509_VP_FLAG_RESET_FLAGS 0x4
#define X509_VP_FLAG_LOCKED 0x8
#define X509_VP_FLAG_ONCE 0x10
#define X509_V_FLAG_POLICY_MASK
#define X509_STORE_set_verify_func(ctx, func) X509_STORE_set_verify((ctx),(func))
#define X509_STORE_set_verify_cb_func(ctx, func) X509_STORE_set_verify_cb((ctx),(func))
#define X509_STORE_set_lookup_crls_cb(ctx, func) X509_STORE_set_lookup_crls((ctx), (func))
#define X509_STORE_get_ex_new_index(l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_X509_STORE, l, p, newf, dupf, freef)
#define X509_STORE_CTX_get_chain X509_STORE_CTX_get0_chain
#define X509_STORE_CTX_set_chain X509_STORE_CTX_set0_untrusted
#define X509_STORE_CTX_trusted_stack X509_STORE_CTX_set0_trusted_stack
#define X509_STORE_get_by_subject X509_STORE_CTX_get_by_subject
#define X509_STORE_get1_cert X509_STORE_CTX_get1_certs
#define X509_STORE_get1_crl X509_STORE_CTX_get1_crls
#define X509_STORE_CTX_get_ex_new_index(l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_X509_STORE_CTX, l, p, newf, dupf, freef)
#define DANE_FLAG_NO_DANE_EE_NAMECHECKS (1L << 0)
#define X509_PCY_TREE_FAILURE -2 /* Failure to satisfy explicit policy */
#define X509_PCY_TREE_INVALID -1 /* Inconsistent or invalid extensions */
#define X509_PCY_TREE_INTERNAL 0 /* Internal error, most likely malloc */
#define X509_PCY_TREE_VALID 1 /* The policy tree is valid */
#define X509_PCY_TREE_EMPTY 2 /* The policy tree is empty */
#define X509_PCY_TREE_EXPLICIT 4 /* Explicit policy required */
Typedefs
typedef int(* X509_STORE_CTX_verify_cb) (int, X509_STORE_CTX *)
typedef int(* X509_STORE_CTX_verify_fn) (X509_STORE_CTX *)
typedef int(* X509_STORE_CTX_get_issuer_fn) (X509 **issuer, X509_STORE_CTX *ctx, X509 *x)
typedef int(* X509_STORE_CTX_check_issued_fn) (X509_STORE_CTX *ctx, X509 *x, X509 *issuer)
typedef int(* X509_STORE_CTX_check_revocation_fn) (X509_STORE_CTX *ctx)
typedef int(* X509_STORE_CTX_get_crl_fn) (X509_STORE_CTX *ctx, X509_CRL **crl, X509 *x)
typedef int(* X509_STORE_CTX_check_crl_fn) (X509_STORE_CTX *ctx, X509_CRL *crl)
typedef int(* X509_STORE_CTX_cert_crl_fn) (X509_STORE_CTX *ctx, X509_CRL *crl, X509 *x)
typedef int(* X509_STORE_CTX_check_policy_fn) (X509_STORE_CTX *ctx)
typedef X509_NAME * nm
typedef int(* X509_STORE_CTX_cleanup_fn) (X509_STORE_CTX *ctx)
Enumerations
enum X509_LOOKUP_TYPE { X509_LU_NONE = 0, X509_LU_X509, X509_LU_CRL }
Functions
int X509_STORE_set_depth (X509_STORE *store, int depth)
typedef STACK_OF (X509) *(*X509_STORE_CTX_lookup_certs_fn)(X509_STORE_CTX *ctx
typedef STACK_OF (X509_CRL) *(*X509_STORE_CTX_lookup_crls_fn)(X509_STORE_CTX *ctx
void X509_STORE_CTX_set_depth (X509_STORE_CTX *ctx, int depth)
int X509_OBJECT_idx_by_subject (STACK_OF(X509_OBJECT) *h, X509_LOOKUP_TYPE type, X509_NAME *name)
X509_OBJECT * X509_OBJECT_retrieve_by_subject (STACK_OF(X509_OBJECT) *h, X509_LOOKUP_TYPE type, X509_NAME *name)
X509_OBJECT * X509_OBJECT_retrieve_match (STACK_OF(X509_OBJECT) *h, X509_OBJECT *x)
int X509_OBJECT_up_ref_count (X509_OBJECT *a)
X509_OBJECT * X509_OBJECT_new (void)
void X509_OBJECT_free (X509_OBJECT *a)
X509_LOOKUP_TYPE X509_OBJECT_get_type (const X509_OBJECT *a)
X509 * X509_OBJECT_get0_X509 (const X509_OBJECT *a)
X509_CRL * X509_OBJECT_get0_X509_CRL (X509_OBJECT *a)
X509_STORE * X509_STORE_new (void)
void X509_STORE_free (X509_STORE *v)
int X509_STORE_lock (X509_STORE *ctx)
int X509_STORE_unlock (X509_STORE *ctx)
int X509_STORE_up_ref (X509_STORE *v)
STACK_OF (X509_OBJECT) *X509_STORE_get0_objects(X509_STORE *v)
int X509_STORE_set_flags (X509_STORE *ctx, unsigned long flags)
int X509_STORE_set_purpose (X509_STORE *ctx, int purpose)
int X509_STORE_set_trust (X509_STORE *ctx, int trust)
int X509_STORE_set1_param (X509_STORE *ctx, X509_VERIFY_PARAM *pm)
X509_VERIFY_PARAM * X509_STORE_get0_param (X509_STORE *ctx)
void X509_STORE_set_verify (X509_STORE *ctx, X509_STORE_CTX_verify_fn verify)
void X509_STORE_CTX_set_verify (X509_STORE_CTX *ctx, X509_STORE_CTX_verify_fn verify)
X509_STORE_CTX_verify_fn X509_STORE_get_verify (X509_STORE *ctx)
void X509_STORE_set_verify_cb (X509_STORE *ctx, X509_STORE_CTX_verify_cb verify_cb)
X509_STORE_CTX_verify_cb X509_STORE_get_verify_cb (X509_STORE *ctx)
void X509_STORE_set_get_issuer (X509_STORE *ctx, X509_STORE_CTX_get_issuer_fn get_issuer)
X509_STORE_CTX_get_issuer_fn X509_STORE_get_get_issuer (X509_STORE *ctx)
void X509_STORE_set_check_issued (X509_STORE *ctx, X509_STORE_CTX_check_issued_fn check_issued)
X509_STORE_CTX_check_issued_fn X509_STORE_get_check_issued (X509_STORE *ctx)
void X509_STORE_set_check_revocation (X509_STORE *ctx, X509_STORE_CTX_check_revocation_fn check_revocation)
X509_STORE_CTX_check_revocation_fn X509_STORE_get_check_revocation (X509_STORE *ctx)
void X509_STORE_set_get_crl (X509_STORE *ctx, X509_STORE_CTX_get_crl_fn get_crl)
X509_STORE_CTX_get_crl_fn X509_STORE_get_get_crl (X509_STORE *ctx)
void X509_STORE_set_check_crl (X509_STORE *ctx, X509_STORE_CTX_check_crl_fn check_crl)
X509_STORE_CTX_check_crl_fn X509_STORE_get_check_crl (X509_STORE *ctx)
void X509_STORE_set_cert_crl (X509_STORE *ctx, X509_STORE_CTX_cert_crl_fn cert_crl)
X509_STORE_CTX_cert_crl_fn X509_STORE_get_cert_crl (X509_STORE *ctx)
void X509_STORE_set_check_policy (X509_STORE *ctx, X509_STORE_CTX_check_policy_fn check_policy)
X509_STORE_CTX_check_policy_fn X509_STORE_get_check_policy (X509_STORE *ctx)
void X509_STORE_set_lookup_certs (X509_STORE *ctx, X509_STORE_CTX_lookup_certs_fn lookup_certs)
X509_STORE_CTX_lookup_certs_fn X509_STORE_get_lookup_certs (X509_STORE *ctx)
void X509_STORE_set_lookup_crls (X509_STORE *ctx, X509_STORE_CTX_lookup_crls_fn lookup_crls)
X509_STORE_CTX_lookup_crls_fn X509_STORE_get_lookup_crls (X509_STORE *ctx)
void X509_STORE_set_cleanup (X509_STORE *ctx, X509_STORE_CTX_cleanup_fn cleanup)
X509_STORE_CTX_cleanup_fn X509_STORE_get_cleanup (X509_STORE *ctx)
int X509_STORE_set_ex_data (X509_STORE *ctx, int idx, void *data)
void * X509_STORE_get_ex_data (X509_STORE *ctx, int idx)
X509_STORE_CTX * X509_STORE_CTX_new (void)
int X509_STORE_CTX_get1_issuer (X509 **issuer, X509_STORE_CTX *ctx, X509 *x)
void X509_STORE_CTX_free (X509_STORE_CTX *ctx)
int X509_STORE_CTX_init (X509_STORE_CTX *ctx, X509_STORE *store, X509 *x509, STACK_OF(X509) *chain)
void X509_STORE_CTX_set0_trusted_stack (X509_STORE_CTX *ctx, STACK_OF(X509) *sk)
void X509_STORE_CTX_cleanup (X509_STORE_CTX *ctx)
X509_STORE * X509_STORE_CTX_get0_store (X509_STORE_CTX *ctx)
X509 * X509_STORE_CTX_get0_cert (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set0_untrusted (X509_STORE_CTX *ctx, STACK_OF(X509) *sk)
void X509_STORE_CTX_set_verify_cb (X509_STORE_CTX *ctx, X509_STORE_CTX_verify_cb verify)
X509_STORE_CTX_verify_cb X509_STORE_CTX_get_verify_cb (X509_STORE_CTX *ctx)
X509_STORE_CTX_verify_fn X509_STORE_CTX_get_verify (X509_STORE_CTX *ctx)
X509_STORE_CTX_get_issuer_fn X509_STORE_CTX_get_get_issuer (X509_STORE_CTX *ctx)
X509_STORE_CTX_check_issued_fn X509_STORE_CTX_get_check_issued (X509_STORE_CTX *ctx)
X509_STORE_CTX_check_revocation_fn X509_STORE_CTX_get_check_revocation (X509_STORE_CTX *ctx)
X509_STORE_CTX_get_crl_fn X509_STORE_CTX_get_get_crl (X509_STORE_CTX *ctx)
X509_STORE_CTX_check_crl_fn X509_STORE_CTX_get_check_crl (X509_STORE_CTX *ctx)
X509_STORE_CTX_cert_crl_fn X509_STORE_CTX_get_cert_crl (X509_STORE_CTX *ctx)
X509_STORE_CTX_check_policy_fn X509_STORE_CTX_get_check_policy (X509_STORE_CTX *ctx)
X509_STORE_CTX_lookup_certs_fn X509_STORE_CTX_get_lookup_certs (X509_STORE_CTX *ctx)
X509_STORE_CTX_lookup_crls_fn X509_STORE_CTX_get_lookup_crls (X509_STORE_CTX *ctx)
X509_STORE_CTX_cleanup_fn X509_STORE_CTX_get_cleanup (X509_STORE_CTX *ctx)
X509_LOOKUP * X509_STORE_add_lookup (X509_STORE *v, X509_LOOKUP_METHOD *m)
X509_LOOKUP_METHOD * X509_LOOKUP_hash_dir (void)
X509_LOOKUP_METHOD * X509_LOOKUP_file (void)
int X509_STORE_add_cert (X509_STORE *ctx, X509 *x)
int X509_STORE_add_crl (X509_STORE *ctx, X509_CRL *x)
int X509_STORE_CTX_get_by_subject (X509_STORE_CTX *vs, X509_LOOKUP_TYPE type, X509_NAME *name, X509_OBJECT *ret)
X509_OBJECT * X509_STORE_CTX_get_obj_by_subject (X509_STORE_CTX *vs, X509_LOOKUP_TYPE type, X509_NAME *name)
int X509_LOOKUP_ctrl (X509_LOOKUP *ctx, int cmd, const char *argc, long argl, char **ret)
int X509_load_cert_file (X509_LOOKUP *ctx, const char *file, int type)
int X509_load_crl_file (X509_LOOKUP *ctx, const char *file, int type)
int X509_load_cert_crl_file (X509_LOOKUP *ctx, const char *file, int type)
X509_LOOKUP * X509_LOOKUP_new (X509_LOOKUP_METHOD *method)
void X509_LOOKUP_free (X509_LOOKUP *ctx)
int X509_LOOKUP_init (X509_LOOKUP *ctx)
int X509_LOOKUP_by_subject (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type, X509_NAME *name, X509_OBJECT *ret)
int X509_LOOKUP_by_issuer_serial (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type, X509_NAME *name, ASN1_INTEGER *serial, X509_OBJECT *ret)
int X509_LOOKUP_by_fingerprint (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type, const unsigned char *bytes, int len, X509_OBJECT *ret)
int X509_LOOKUP_by_alias (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type, const char *str, int len, X509_OBJECT *ret)
int X509_LOOKUP_shutdown (X509_LOOKUP *ctx)
int X509_STORE_load_locations (X509_STORE *ctx, const char *file, const char *dir)
int X509_STORE_set_default_paths (X509_STORE *ctx)
int X509_STORE_CTX_set_ex_data (X509_STORE_CTX *ctx, int idx, void *data)
void * X509_STORE_CTX_get_ex_data (X509_STORE_CTX *ctx, int idx)
int X509_STORE_CTX_get_error (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set_error (X509_STORE_CTX *ctx, int s)
int X509_STORE_CTX_get_error_depth (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set_error_depth (X509_STORE_CTX *ctx, int depth)
X509 * X509_STORE_CTX_get_current_cert (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set_current_cert (X509_STORE_CTX *ctx, X509 *x)
X509 * X509_STORE_CTX_get0_current_issuer (X509_STORE_CTX *ctx)
X509_CRL * X509_STORE_CTX_get0_current_crl (X509_STORE_CTX *ctx)
X509_STORE_CTX * X509_STORE_CTX_get0_parent_ctx (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set_cert (X509_STORE_CTX *c, X509 *x)
void X509_STORE_CTX_set0_verified_chain (X509_STORE_CTX *c, STACK_OF(X509) *sk)
void X509_STORE_CTX_set0_crls (X509_STORE_CTX *c, STACK_OF(X509_CRL) *sk)
int X509_STORE_CTX_set_purpose (X509_STORE_CTX *ctx, int purpose)
int X509_STORE_CTX_set_trust (X509_STORE_CTX *ctx, int trust)
int X509_STORE_CTX_purpose_inherit (X509_STORE_CTX *ctx, int def_purpose, int purpose, int trust)
void X509_STORE_CTX_set_flags (X509_STORE_CTX *ctx, unsigned long flags)
void X509_STORE_CTX_set_time (X509_STORE_CTX *ctx, unsigned long flags, time_t t)
X509_POLICY_TREE * X509_STORE_CTX_get0_policy_tree (X509_STORE_CTX *ctx)
int X509_STORE_CTX_get_explicit_policy (X509_STORE_CTX *ctx)
int X509_STORE_CTX_get_num_untrusted (X509_STORE_CTX *ctx)
X509_VERIFY_PARAM * X509_STORE_CTX_get0_param (X509_STORE_CTX *ctx)
void X509_STORE_CTX_set0_param (X509_STORE_CTX *ctx, X509_VERIFY_PARAM *param)
int X509_STORE_CTX_set_default (X509_STORE_CTX *ctx, const char *name)
void X509_STORE_CTX_set0_dane (X509_STORE_CTX *ctx, SSL_DANE *dane)
X509_VERIFY_PARAM * X509_VERIFY_PARAM_new (void)
void X509_VERIFY_PARAM_free (X509_VERIFY_PARAM *param)
int X509_VERIFY_PARAM_inherit (X509_VERIFY_PARAM *to, const X509_VERIFY_PARAM *from)
int X509_VERIFY_PARAM_set1 (X509_VERIFY_PARAM *to, const X509_VERIFY_PARAM *from)
int X509_VERIFY_PARAM_set1_name (X509_VERIFY_PARAM *param, const char *name)
int X509_VERIFY_PARAM_set_flags (X509_VERIFY_PARAM *param, unsigned long flags)
int X509_VERIFY_PARAM_clear_flags (X509_VERIFY_PARAM *param, unsigned long flags)
unsigned long X509_VERIFY_PARAM_get_flags (X509_VERIFY_PARAM *param)
int X509_VERIFY_PARAM_set_purpose (X509_VERIFY_PARAM *param, int purpose)
int X509_VERIFY_PARAM_set_trust (X509_VERIFY_PARAM *param, int trust)
void X509_VERIFY_PARAM_set_depth (X509_VERIFY_PARAM *param, int depth)
void X509_VERIFY_PARAM_set_auth_level (X509_VERIFY_PARAM *param, int auth_level)
time_t X509_VERIFY_PARAM_get_time (const X509_VERIFY_PARAM *param)
void X509_VERIFY_PARAM_set_time (X509_VERIFY_PARAM *param, time_t t)
int X509_VERIFY_PARAM_add0_policy (X509_VERIFY_PARAM *param, ASN1_OBJECT *policy)
int X509_VERIFY_PARAM_set1_policies (X509_VERIFY_PARAM *param, STACK_OF(ASN1_OBJECT) *policies)
int X509_VERIFY_PARAM_set_inh_flags (X509_VERIFY_PARAM *param, uint32_t flags)
uint32_t X509_VERIFY_PARAM_get_inh_flags (const X509_VERIFY_PARAM *param)
int X509_VERIFY_PARAM_set1_host (X509_VERIFY_PARAM *param, const char *name, size_t namelen)
int X509_VERIFY_PARAM_add1_host (X509_VERIFY_PARAM *param, const char *name, size_t namelen)
void X509_VERIFY_PARAM_set_hostflags (X509_VERIFY_PARAM *param, unsigned int flags)
char * X509_VERIFY_PARAM_get0_peername (X509_VERIFY_PARAM *)
void X509_VERIFY_PARAM_move_peername (X509_VERIFY_PARAM *, X509_VERIFY_PARAM *)
int X509_VERIFY_PARAM_set1_email (X509_VERIFY_PARAM *param, const char *email, size_t emaillen)
int X509_VERIFY_PARAM_set1_ip (X509_VERIFY_PARAM *param, const unsigned char *ip, size_t iplen)
int X509_VERIFY_PARAM_set1_ip_asc (X509_VERIFY_PARAM *param, const char *ipasc)
int X509_VERIFY_PARAM_get_depth (const X509_VERIFY_PARAM *param)
int X509_VERIFY_PARAM_get_auth_level (const X509_VERIFY_PARAM *param)
const char * X509_VERIFY_PARAM_get0_name (const X509_VERIFY_PARAM *param)
int X509_VERIFY_PARAM_add0_table (X509_VERIFY_PARAM *param)
int X509_VERIFY_PARAM_get_count (void)
const X509_VERIFY_PARAM * X509_VERIFY_PARAM_get0 (int id)
const X509_VERIFY_PARAM * X509_VERIFY_PARAM_lookup (const char *name)
void X509_VERIFY_PARAM_table_cleanup (void)
int X509_policy_check (X509_POLICY_TREE **ptree, int *pexplicit_policy, STACK_OF(X509) *certs, STACK_OF(ASN1_OBJECT) *policy_oids, unsigned int flags)
void X509_policy_tree_free (X509_POLICY_TREE *tree)
int X509_policy_tree_level_count (const X509_POLICY_TREE *tree)
X509_POLICY_LEVEL * X509_policy_tree_get0_level (const X509_POLICY_TREE *tree, int i)
STACK_OF (X509_POLICY_NODE) *X509_policy_tree_get0_policies(const X509_POLICY_TREE *tree)
int X509_policy_level_node_count (X509_POLICY_LEVEL *level)
X509_POLICY_NODE * X509_policy_level_get0_node (X509_POLICY_LEVEL *level, int i)
const ASN1_OBJECT * X509_policy_node_get0_policy (const X509_POLICY_NODE *node)
STACK_OF (POLICYQUALINFO) *X509_policy_node_get0_qualifiers(const X509_POLICY_NODE *node)
const X509_POLICY_NODE * X509_policy_node_get0_parent (const X509_POLICY_NODE *node)
Macro Definition Documentation
DANE_FLAG_NO_DANE_EE_NAMECHECKS
#define DANE_FLAG_NO_DANE_EE_NAMECHECKS (1L << 0)
Definition at line 442 of file x509_vfy.h.
X509_L_ADD_DIR
#define X509_L_ADD_DIR 2
Definition at line 91 of file x509_vfy.h.
X509_L_FILE_LOAD
#define X509_L_FILE_LOAD 1
Definition at line 90 of file x509_vfy.h.
X509_LOOKUP_add_dir
#define X509_LOOKUP_add_dir (x, name, type) X509_LOOKUP_ctrl((x),X509_L_ADD_DIR,(name),(long)(type),NULL)
Definition at line 96 of file x509_vfy.h.
X509_LOOKUP_load_file
#define X509_LOOKUP_load_file (x, name, type) X509_LOOKUP_ctrl((x),X509_L_FILE_LOAD,(name),(long)(type),NULL)
Definition at line 93 of file x509_vfy.h.
X509_LU_FAIL
#define X509_LU_FAIL 0
Definition at line 54 of file x509_vfy.h.
X509_LU_RETRY
#define X509_LU_RETRY -1
Definition at line 53 of file x509_vfy.h.
X509_PCY_TREE_EMPTY
#define X509_PCY_TREE_EMPTY 2 /* The policy tree is empty */
Definition at line 508 of file x509_vfy.h.
X509_PCY_TREE_EXPLICIT
#define X509_PCY_TREE_EXPLICIT 4 /* Explicit policy required */
Definition at line 509 of file x509_vfy.h.
X509_PCY_TREE_FAILURE
#define X509_PCY_TREE_FAILURE -2 /* Failure to satisfy explicit policy */
Definition at line 499 of file x509_vfy.h.
X509_PCY_TREE_INTERNAL
#define X509_PCY_TREE_INTERNAL 0 /* Internal error, most likely malloc */
Definition at line 501 of file x509_vfy.h.
X509_PCY_TREE_INVALID
#define X509_PCY_TREE_INVALID -1 /* Inconsistent or invalid extensions */
Definition at line 500 of file x509_vfy.h.
X509_PCY_TREE_VALID
#define X509_PCY_TREE_VALID 1 /* The policy tree is valid */
Definition at line 507 of file x509_vfy.h.
X509_STORE_CTX_get_app_data
#define X509_STORE_CTX_get_app_data (ctx) X509_STORE_CTX_get_ex_data(ctx,0)
Definition at line 87 of file x509_vfy.h.
X509_STORE_CTX_get_chain
#define X509_STORE_CTX_get_chain X509_STORE_CTX_get0_chain
Definition at line 356 of file x509_vfy.h.
X509_STORE_CTX_get_ex_new_index
#define X509_STORE_CTX_get_ex_new_index (l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_X509_STORE_CTX, l, p, newf, dupf, freef)
Definition at line 403 of file x509_vfy.h.
X509_STORE_CTX_set_app_data
#define X509_STORE_CTX_set_app_data (ctx, data) X509_STORE_CTX_set_ex_data(ctx,0,data)
Definition at line 85 of file x509_vfy.h.
X509_STORE_CTX_set_chain
#define X509_STORE_CTX_set_chain X509_STORE_CTX_set0_untrusted
Definition at line 357 of file x509_vfy.h.
X509_STORE_CTX_trusted_stack
#define X509_STORE_CTX_trusted_stack X509_STORE_CTX_set0_trusted_stack
Definition at line 358 of file x509_vfy.h.
X509_STORE_get1_cert
#define X509_STORE_get1_cert X509_STORE_CTX_get1_certs
Definition at line 360 of file x509_vfy.h.
X509_STORE_get1_crl
#define X509_STORE_get1_crl X509_STORE_CTX_get1_crls
Definition at line 361 of file x509_vfy.h.
X509_STORE_get_by_subject
#define X509_STORE_get_by_subject X509_STORE_CTX_get_by_subject
Definition at line 359 of file x509_vfy.h.
X509_STORE_get_ex_new_index
#define X509_STORE_get_ex_new_index (l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_X509_STORE, l, p, newf, dupf, freef)
Definition at line 321 of file x509_vfy.h.
X509_STORE_set_lookup_crls_cb
#define X509_STORE_set_lookup_crls_cb (ctx, func) X509_STORE_set_lookup_crls((ctx), (func))
Definition at line 314 of file x509_vfy.h.
Referenced by store_setup_crl_download().
X509_STORE_set_verify_cb_func
#define X509_STORE_set_verify_cb_func (ctx, func) X509_STORE_set_verify_cb((ctx),(func))
Definition at line 285 of file x509_vfy.h.
X509_STORE_set_verify_func
#define X509_STORE_set_verify_func (ctx, func) X509_STORE_set_verify((ctx),(func))
Definition at line 278 of file x509_vfy.h.
X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH
#define X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH 31
Definition at line 131 of file x509_vfy.h.
Referenced by X509_check_akid(), and X509_verify_cert_error_string().
X509_V_ERR_AKID_SKID_MISMATCH
#define X509_V_ERR_AKID_SKID_MISMATCH 30
Definition at line 130 of file x509_vfy.h.
Referenced by X509_check_akid(), and X509_verify_cert_error_string().
X509_V_ERR_APPLICATION_VERIFICATION
#define X509_V_ERR_APPLICATION_VERIFICATION 50
Definition at line 151 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_CA_KEY_TOO_SMALL
#define X509_V_ERR_CA_KEY_TOO_SMALL 67
Definition at line 173 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_CA_MD_TOO_WEAK
#define X509_V_ERR_CA_MD_TOO_WEAK 68
Definition at line 174 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_CERT_CHAIN_TOO_LONG
#define X509_V_ERR_CERT_CHAIN_TOO_LONG 22
Definition at line 121 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), verify_callback(), and X509_verify_cert_error_string().
X509_V_ERR_CERT_HAS_EXPIRED
#define X509_V_ERR_CERT_HAS_EXPIRED 10
Definition at line 109 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), verify_callback(), and X509_verify_cert_error_string().
X509_V_ERR_CERT_NOT_YET_VALID
#define X509_V_ERR_CERT_NOT_YET_VALID 9
Definition at line 108 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), verify_callback(), and X509_verify_cert_error_string().
X509_V_ERR_CERT_REJECTED
#define X509_V_ERR_CERT_REJECTED 28
Definition at line 127 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_CERT_REVOKED
#define X509_V_ERR_CERT_REVOKED 23
Definition at line 122 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_CERT_SIGNATURE_FAILURE
#define X509_V_ERR_CERT_SIGNATURE_FAILURE 7
Definition at line 106 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_CERT_UNTRUSTED
#define X509_V_ERR_CERT_UNTRUSTED 27
Definition at line 126 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_CRL_HAS_EXPIRED
#define X509_V_ERR_CRL_HAS_EXPIRED 12
Definition at line 111 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_CRL_NOT_YET_VALID
#define X509_V_ERR_CRL_NOT_YET_VALID 11
Definition at line 110 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_CRL_PATH_VALIDATION_ERROR
#define X509_V_ERR_CRL_PATH_VALIDATION_ERROR 54
Definition at line 155 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_CRL_SIGNATURE_FAILURE
#define X509_V_ERR_CRL_SIGNATURE_FAILURE 8
Definition at line 107 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_DANE_NO_MATCH
#define X509_V_ERR_DANE_NO_MATCH 65
Definition at line 170 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT
#define X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT 18
Definition at line 117 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_DIFFERENT_CRL_SCOPE
#define X509_V_ERR_DIFFERENT_CRL_SCOPE 44
Definition at line 144 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_EE_KEY_TOO_SMALL
#define X509_V_ERR_EE_KEY_TOO_SMALL 66
Definition at line 172 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_EMAIL_MISMATCH
#define X509_V_ERR_EMAIL_MISMATCH 63
Definition at line 167 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD
#define X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD 14
Definition at line 113 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), verify_callback(), and X509_verify_cert_error_string().
X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD
#define X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD 13
Definition at line 112 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), verify_callback(), and X509_verify_cert_error_string().
X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD
#define X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD 15
Definition at line 114 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD
#define X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD 16
Definition at line 115 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_EXCLUDED_VIOLATION
#define X509_V_ERR_EXCLUDED_VIOLATION 48
Definition at line 148 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_HOSTNAME_MISMATCH
#define X509_V_ERR_HOSTNAME_MISMATCH 62
Definition at line 166 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_INVALID_CA
#define X509_V_ERR_INVALID_CA 24
Definition at line 123 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_INVALID_CALL
#define X509_V_ERR_INVALID_CALL 69
Definition at line 176 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_INVALID_EXTENSION
#define X509_V_ERR_INVALID_EXTENSION 41
Definition at line 141 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_INVALID_NON_CA
#define X509_V_ERR_INVALID_NON_CA 37
Definition at line 137 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_INVALID_POLICY_EXTENSION
#define X509_V_ERR_INVALID_POLICY_EXTENSION 42
Definition at line 142 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_INVALID_PURPOSE
#define X509_V_ERR_INVALID_PURPOSE 26
Definition at line 125 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_IP_ADDRESS_MISMATCH
#define X509_V_ERR_IP_ADDRESS_MISMATCH 64
Definition at line 168 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_KEYUSAGE_NO_CERTSIGN
#define X509_V_ERR_KEYUSAGE_NO_CERTSIGN 32
Definition at line 132 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_KEYUSAGE_NO_CRL_SIGN
#define X509_V_ERR_KEYUSAGE_NO_CRL_SIGN 35
Definition at line 135 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_KEYUSAGE_NO_DIGITAL_SIGNATURE
#define X509_V_ERR_KEYUSAGE_NO_DIGITAL_SIGNATURE 39
Definition at line 139 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_NO_EXPLICIT_POLICY
#define X509_V_ERR_NO_EXPLICIT_POLICY 43
Definition at line 143 of file x509_vfy.h.
Referenced by verify_callback(), and X509_verify_cert_error_string().
X509_V_ERR_NO_VALID_SCTS
#define X509_V_ERR_NO_VALID_SCTS 71
Definition at line 180 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_OUT_OF_MEM
#define X509_V_ERR_OUT_OF_MEM 17
Definition at line 116 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_PATH_LENGTH_EXCEEDED
#define X509_V_ERR_PATH_LENGTH_EXCEEDED 25
Definition at line 124 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_PATH_LOOP
#define X509_V_ERR_PATH_LOOP 55
Definition at line 157 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_PERMITTED_VIOLATION
#define X509_V_ERR_PERMITTED_VIOLATION 47
Definition at line 147 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_PROXY_CERTIFICATES_NOT_ALLOWED
#define X509_V_ERR_PROXY_CERTIFICATES_NOT_ALLOWED 40
Definition at line 140 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_PROXY_PATH_LENGTH_EXCEEDED
#define X509_V_ERR_PROXY_PATH_LENGTH_EXCEEDED 38
Definition at line 138 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_PROXY_SUBJECT_NAME_VIOLATION
#define X509_V_ERR_PROXY_SUBJECT_NAME_VIOLATION 72
Definition at line 182 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN
#define X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN 19
Definition at line 118 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_STORE_LOOKUP
#define X509_V_ERR_STORE_LOOKUP 70
Definition at line 178 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_SUBJECT_ISSUER_MISMATCH
#define X509_V_ERR_SUBJECT_ISSUER_MISMATCH 29
Definition at line 129 of file x509_vfy.h.
Referenced by X509_check_issued(), and X509_verify_cert_error_string().
X509_V_ERR_SUBTREE_MINMAX
#define X509_V_ERR_SUBTREE_MINMAX 49
Definition at line 149 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_SUITE_B_CANNOT_SIGN_P_384_WITH_P_256
#define X509_V_ERR_SUITE_B_CANNOT_SIGN_P_384_WITH_P_256 61
Definition at line 164 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_SUITE_B_INVALID_ALGORITHM
#define X509_V_ERR_SUITE_B_INVALID_ALGORITHM 57
Definition at line 160 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_SUITE_B_INVALID_CURVE
#define X509_V_ERR_SUITE_B_INVALID_CURVE 58
Definition at line 161 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_SUITE_B_INVALID_SIGNATURE_ALGORITHM
#define X509_V_ERR_SUITE_B_INVALID_SIGNATURE_ALGORITHM 59
Definition at line 162 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_SUITE_B_INVALID_VERSION
#define X509_V_ERR_SUITE_B_INVALID_VERSION 56
Definition at line 159 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_SUITE_B_LOS_NOT_ALLOWED
#define X509_V_ERR_SUITE_B_LOS_NOT_ALLOWED 60
Definition at line 163 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY
#define X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY 6
Definition at line 105 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE
#define X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE 4
Definition at line 103 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE
#define X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE 5
Definition at line 104 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_UNABLE_TO_GET_CRL
#define X509_V_ERR_UNABLE_TO_GET_CRL 3
Definition at line 102 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER
#define X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER 33
Definition at line 133 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT
#define X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT 2
Definition at line 101 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), verify_callback(), and X509_verify_cert_error_string().
X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY
#define X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY 20
Definition at line 119 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE
#define X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE 21
Definition at line 120 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_UNHANDLED_CRITICAL_CRL_EXTENSION
#define X509_V_ERR_UNHANDLED_CRITICAL_CRL_EXTENSION 36
Definition at line 136 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_UNHANDLED_CRITICAL_EXTENSION
#define X509_V_ERR_UNHANDLED_CRITICAL_EXTENSION 34
Definition at line 134 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_UNNESTED_RESOURCE
#define X509_V_ERR_UNNESTED_RESOURCE 46
Definition at line 146 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_UNSPECIFIED
#define X509_V_ERR_UNSPECIFIED 1
Definition at line 100 of file x509_vfy.h.
Referenced by ssl_verify_alarm_type(), and X509_verify_cert_error_string().
X509_V_ERR_UNSUPPORTED_CONSTRAINT_SYNTAX
#define X509_V_ERR_UNSUPPORTED_CONSTRAINT_SYNTAX 52
Definition at line 153 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_UNSUPPORTED_CONSTRAINT_TYPE
#define X509_V_ERR_UNSUPPORTED_CONSTRAINT_TYPE 51
Definition at line 152 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_UNSUPPORTED_EXTENSION_FEATURE
#define X509_V_ERR_UNSUPPORTED_EXTENSION_FEATURE 45
Definition at line 145 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_ERR_UNSUPPORTED_NAME_SYNTAX
#define X509_V_ERR_UNSUPPORTED_NAME_SYNTAX 53
Definition at line 154 of file x509_vfy.h.
Referenced by X509_verify_cert_error_string().
X509_V_FLAG_ALLOW_PROXY_CERTS
#define X509_V_FLAG_ALLOW_PROXY_CERTS 0x40
Definition at line 200 of file x509_vfy.h.
X509_V_FLAG_CB_ISSUER_CHECK
#define X509_V_FLAG_CB_ISSUER_CHECK 0x0 /* Deprecated */
Definition at line 187 of file x509_vfy.h.
X509_V_FLAG_CHECK_SS_SIGNATURE
#define X509_V_FLAG_CHECK_SS_SIGNATURE 0x4000
Definition at line 216 of file x509_vfy.h.
X509_V_FLAG_CRL_CHECK
#define X509_V_FLAG_CRL_CHECK 0x4
Definition at line 192 of file x509_vfy.h.
X509_V_FLAG_CRL_CHECK_ALL
#define X509_V_FLAG_CRL_CHECK_ALL 0x8
Definition at line 194 of file x509_vfy.h.
X509_V_FLAG_EXPLICIT_POLICY
#define X509_V_FLAG_EXPLICIT_POLICY 0x100
Definition at line 204 of file x509_vfy.h.
X509_V_FLAG_EXTENDED_CRL_SUPPORT
#define X509_V_FLAG_EXTENDED_CRL_SUPPORT 0x1000
Definition at line 212 of file x509_vfy.h.
X509_V_FLAG_IGNORE_CRITICAL
#define X509_V_FLAG_IGNORE_CRITICAL 0x10
Definition at line 196 of file x509_vfy.h.
X509_V_FLAG_INHIBIT_ANY
#define X509_V_FLAG_INHIBIT_ANY 0x200
Definition at line 206 of file x509_vfy.h.
X509_V_FLAG_INHIBIT_MAP
#define X509_V_FLAG_INHIBIT_MAP 0x400
Definition at line 208 of file x509_vfy.h.
Referenced by policy_node_match().
X509_V_FLAG_NO_ALT_CHAINS
#define X509_V_FLAG_NO_ALT_CHAINS 0x100000
Definition at line 232 of file x509_vfy.h.
X509_V_FLAG_NO_CHECK_TIME
#define X509_V_FLAG_NO_CHECK_TIME 0x200000
Definition at line 234 of file x509_vfy.h.
Referenced by x509_check_cert_time().
X509_V_FLAG_NOTIFY_POLICY
#define X509_V_FLAG_NOTIFY_POLICY 0x800
Definition at line 210 of file x509_vfy.h.
X509_V_FLAG_PARTIAL_CHAIN
#define X509_V_FLAG_PARTIAL_CHAIN 0x80000
Definition at line 226 of file x509_vfy.h.
X509_V_FLAG_POLICY_CHECK
#define X509_V_FLAG_POLICY_CHECK 0x80
Definition at line 202 of file x509_vfy.h.
Referenced by X509_VERIFY_PARAM_set_flags().
X509_V_FLAG_POLICY_MASK
#define X509_V_FLAG_POLICY_MASK
Value:
(X509_V_FLAG_POLICY_CHECK \
                                | X509_V_FLAG_EXPLICIT_POLICY \
                                | X509_V_FLAG_INHIBIT_ANY \
                                | X509_V_FLAG_INHIBIT_MAP)
Definition at line 243 of file x509_vfy.h.
Referenced by X509_VERIFY_PARAM_set_flags().
X509_V_FLAG_SUITEB_128_LOS
#define X509_V_FLAG_SUITEB_128_LOS 0x30000
Definition at line 224 of file x509_vfy.h.
Referenced by X509_chain_check_suiteb(), and X509_CRL_check_suiteb().
X509_V_FLAG_SUITEB_128_LOS_ONLY
#define X509_V_FLAG_SUITEB_128_LOS_ONLY 0x10000
Definition at line 220 of file x509_vfy.h.
X509_V_FLAG_SUITEB_192_LOS
#define X509_V_FLAG_SUITEB_192_LOS 0x20000
Definition at line 222 of file x509_vfy.h.
X509_V_FLAG_TRUSTED_FIRST
#define X509_V_FLAG_TRUSTED_FIRST 0x8000
Definition at line 218 of file x509_vfy.h.
X509_V_FLAG_USE_CHECK_TIME
#define X509_V_FLAG_USE_CHECK_TIME 0x2
Definition at line 190 of file x509_vfy.h.
Referenced by x509_check_cert_time(), X509_VERIFY_PARAM_inherit(), and X509_VERIFY_PARAM_set_time().
X509_V_FLAG_USE_DELTAS
#define X509_V_FLAG_USE_DELTAS 0x2000
Definition at line 214 of file x509_vfy.h.
X509_V_FLAG_X509_STRICT
#define X509_V_FLAG_X509_STRICT 0x20
Definition at line 198 of file x509_vfy.h.
X509_V_OK
#define X509_V_OK 0
Definition at line 99 of file x509_vfy.h.
Referenced by SSL_get0_dane_authority(), SSL_get0_dane_tlsa(), SSL_new(), verify_callback(), X509_chain_check_suiteb(), X509_check_akid(), X509_CRL_check_suiteb(), and X509_verify_cert_error_string().
X509_VP_FLAG_DEFAULT
#define X509_VP_FLAG_DEFAULT 0x1
Definition at line 236 of file x509_vfy.h.
Referenced by X509_VERIFY_PARAM_inherit().
X509_VP_FLAG_LOCKED
#define X509_VP_FLAG_LOCKED 0x8
Definition at line 239 of file x509_vfy.h.
Referenced by X509_VERIFY_PARAM_inherit().
X509_VP_FLAG_ONCE
#define X509_VP_FLAG_ONCE 0x10
Definition at line 240 of file x509_vfy.h.
Referenced by X509_VERIFY_PARAM_inherit().
X509_VP_FLAG_OVERWRITE
#define X509_VP_FLAG_OVERWRITE 0x2
Definition at line 237 of file x509_vfy.h.
Referenced by X509_VERIFY_PARAM_inherit().
X509_VP_FLAG_RESET_FLAGS
#define X509_VP_FLAG_RESET_FLAGS 0x4
Definition at line 238 of file x509_vfy.h.
Referenced by X509_VERIFY_PARAM_inherit().
Typedef Documentation
nm
X509_NAME * nm
Definition at line 77 of file x509_vfy.h.
X509_STORE_CTX_cert_crl_fn
typedef int(* X509_STORE_CTX_cert_crl_fn) (X509_STORE_CTX *ctx, X509_CRL *crl, X509 *x)
Definition at line 73 of file x509_vfy.h.
X509_STORE_CTX_check_crl_fn
typedef int(* X509_STORE_CTX_check_crl_fn) (X509_STORE_CTX *ctx, X509_CRL *crl)
Definition at line 72 of file x509_vfy.h.
X509_STORE_CTX_check_issued_fn
typedef int(* X509_STORE_CTX_check_issued_fn) (X509_STORE_CTX *ctx, X509 *x, X509 *issuer)
Definition at line 67 of file x509_vfy.h.
X509_STORE_CTX_check_policy_fn
typedef int(* X509_STORE_CTX_check_policy_fn) (X509_STORE_CTX *ctx)
Definition at line 75 of file x509_vfy.h.
X509_STORE_CTX_check_revocation_fn
typedef int(* X509_STORE_CTX_check_revocation_fn) (X509_STORE_CTX *ctx)
Definition at line 69 of file x509_vfy.h.
X509_STORE_CTX_cleanup_fn
typedef int(* X509_STORE_CTX_cleanup_fn) (X509_STORE_CTX *ctx)
Definition at line 80 of file x509_vfy.h.
X509_STORE_CTX_get_crl_fn
typedef int(* X509_STORE_CTX_get_crl_fn) (X509_STORE_CTX *ctx, X509_CRL **crl, X509 *x)
Definition at line 70 of file x509_vfy.h.
X509_STORE_CTX_get_issuer_fn
typedef int(* X509_STORE_CTX_get_issuer_fn) (X509 **issuer, X509_STORE_CTX *ctx, X509 *x)
Definition at line 65 of file x509_vfy.h.
X509_STORE_CTX_verify_cb
typedef int(* X509_STORE_CTX_verify_cb) (int, X509_STORE_CTX *)
Definition at line 63 of file x509_vfy.h.
X509_STORE_CTX_verify_fn
typedef int(* X509_STORE_CTX_verify_fn) (X509_STORE_CTX *)
Definition at line 64 of file x509_vfy.h.
Enumeration Type Documentation
X509_LOOKUP_TYPE
enum X509_LOOKUP_TYPE
Enumerator
X509_LU_NONE
X509_LU_X509
X509_LU_CRL
Definition at line 47 of file x509_vfy.h.
Function Documentation
STACK_OF() [1/5]
typedef STACK_OF (X509)
Definition at line 478 of file cms_lib.c.
References CMS_CertificateChoices::certificate, CMS_CertificateChoices::d, NULL, STACK_OF(), CMS_CertificateChoices::type, and X509_up_ref().
STACK_OF() [2/5]
typedef STACK_OF (X509_CRL)
Definition at line 506 of file cms_lib.c.
References NULL, STACK_OF(), and X509_CRL_up_ref().
STACK_OF() [3/5]
STACK_OF (X509_OBJECT)
Definition at line 495 of file x509_lu.c.
Referenced by X509_STORE_add_lookup(), and X509_STORE_free().
STACK_OF() [4/5]
STACK_OF (X509_POLICY_NODE) const
STACK_OF() [5/5]
STACK_OF (POLICYQUALINFO) const
X509_load_cert_crl_file()
int X509_load_cert_crl_file (X509_LOOKUP * ctx, const char * file, int type)
Definition at line 189 of file by_file.c.
References BIO_free(), BIO_new_file(), X509_INFO::crl, ERR_R_PEM_LIB, ERR_R_SYS_LIB, in, NULL, STACK_OF, X509_INFO::x509, X509_F_X509_LOAD_CERT_CRL_FILE, X509_FILETYPE_PEM, X509_INFO_free(), X509_load_cert_file(), X509_STORE_add_cert(), X509_STORE_add_crl(), and X509err.
X509_load_cert_file()
int X509_load_cert_file (X509_LOOKUP * ctx, const char * file, int type)
Definition at line 75 of file by_file.c.
Referenced by X509_load_cert_crl_file().
X509_load_crl_file()
int X509_load_crl_file (X509_LOOKUP * ctx, const char * file, int type)
Definition at line 132 of file by_file.c.
X509_LOOKUP_by_alias()
int X509_LOOKUP_by_alias (X509_LOOKUP * ctx, X509_LOOKUP_TYPE type, const char * str, int len, X509_OBJECT * ret)
Definition at line 112 of file x509_lu.c.
X509_LOOKUP_by_fingerprint()
int X509_LOOKUP_by_fingerprint (X509_LOOKUP * ctx, X509_LOOKUP_TYPE type, const unsigned char * bytes, int len, X509_OBJECT * ret)
Definition at line 103 of file x509_lu.c.
X509_LOOKUP_by_issuer_serial()
int X509_LOOKUP_by_issuer_serial (X509_LOOKUP * ctx, X509_LOOKUP_TYPE type, X509_NAME * name, ASN1_INTEGER * serial, X509_OBJECT * ret)
Definition at line 94 of file x509_lu.c.
X509_LOOKUP_by_subject()
int X509_LOOKUP_by_subject (X509_LOOKUP * ctx, X509_LOOKUP_TYPE type, X509_NAME * name, X509_OBJECT * ret)
Definition at line 84 of file x509_lu.c.
X509_LOOKUP_ctrl()
int X509_LOOKUP_ctrl (X509_LOOKUP * ctx, int cmd, const char * argc, long argl, char ** ret)
Definition at line 73 of file x509_lu.c.
X509_LOOKUP_file()
X509_LOOKUP_METHOD* X509_LOOKUP_file (void)
Definition at line 36 of file by_file.c.
X509_LOOKUP_free()
void X509_LOOKUP_free (X509_LOOKUP * ctx)
Definition at line 34 of file x509_lu.c.
References NULL, and OPENSSL_free.
Referenced by X509_STORE_add_lookup(), and X509_STORE_free().
X509_LOOKUP_hash_dir()
X509_LOOKUP_METHOD* X509_LOOKUP_hash_dir (void)
Definition at line 66 of file by_dir.c.
X509_LOOKUP_init()
int X509_LOOKUP_init (X509_LOOKUP * ctx)
Definition at line 53 of file x509_lu.c.
References NULL.
X509_LOOKUP_new()
X509_LOOKUP* X509_LOOKUP_new (X509_LOOKUP_METHOD * method)
Definition at line 18 of file x509_lu.c.
Referenced by X509_STORE_add_lookup().
X509_LOOKUP_shutdown()
int X509_LOOKUP_shutdown (X509_LOOKUP * ctx)
Definition at line 63 of file x509_lu.c.
References NULL.
Referenced by X509_STORE_free().
X509_OBJECT_free()
void X509_OBJECT_free (X509_OBJECT * a)
Definition at line 422 of file x509_lu.c.
References NULL, OPENSSL_free, X509_LU_CRL, X509_LU_NONE, and X509_LU_X509.
X509_OBJECT_get0_X509()
X509* X509_OBJECT_get0_X509 (const X509_OBJECT * a)
Definition at line 390 of file x509_lu.c.
References NULL, and X509_LU_X509.
X509_OBJECT_get0_X509_CRL()
X509_CRL* X509_OBJECT_get0_X509_CRL (X509_OBJECT * a)
Definition at line 397 of file x509_lu.c.
References NULL, and X509_LU_CRL.
X509_OBJECT_get_type()
X509_LOOKUP_TYPE X509_OBJECT_get_type (const X509_OBJECT * a)
Definition at line 404 of file x509_lu.c.
X509_OBJECT_idx_by_subject()
int X509_OBJECT_idx_by_subject (STACK_OF(X509_OBJECT) * h, X509_LOOKUP_TYPE type, X509_NAME * name)
Definition at line 478 of file x509_lu.c.
X509_OBJECT_new()
X509_OBJECT* X509_OBJECT_new (void)
Definition at line 409 of file x509_lu.c.
Referenced by X509_STORE_CTX_get1_issuer().
X509_OBJECT_retrieve_by_subject()
X509_OBJECT* X509_OBJECT_retrieve_by_subject (STACK_OF(X509_OBJECT) * h, X509_LOOKUP_TYPE type, X509_NAME * name)
Definition at line 484 of file x509_lu.c.
X509_OBJECT_retrieve_match()
X509_OBJECT* X509_OBJECT_retrieve_match (STACK_OF(X509_OBJECT) * h, X509_OBJECT * x)
Definition at line 586 of file x509_lu.c.
X509_OBJECT_up_ref_count()
int X509_OBJECT_up_ref_count (X509_OBJECT * a)
Definition at line 377 of file x509_lu.c.
References X509_CRL_up_ref(), X509_LU_CRL, X509_LU_NONE, X509_LU_X509, and X509_up_ref().
X509_policy_check()
int X509_policy_check (X509_POLICY_TREE ** ptree, int * pexplicit_policy, STACK_OF(X509) * certs, STACK_OF(ASN1_OBJECT) * policy_oids, unsigned int flags)
Definition at line 635 of file pcy_tree.c.
X509_policy_level_get0_node()
X509_POLICY_NODE* X509_policy_level_get0_node (X509_POLICY_LEVEL * level, int i)
Definition at line 72 of file pcy_lib.c.
References NULL.
X509_policy_level_node_count()
int X509_policy_level_node_count (X509_POLICY_LEVEL * level)
Definition at line 58 of file pcy_lib.c.
X509_policy_node_get0_parent()
const X509_POLICY_NODE* X509_policy_node_get0_parent (const X509_POLICY_NODE * node)
Definition at line 102 of file pcy_lib.c.
References NULL.
X509_policy_node_get0_policy()
const ASN1_OBJECT* X509_policy_node_get0_policy (const X509_POLICY_NODE * node)
Definition at line 86 of file pcy_lib.c.
References NULL.
X509_policy_tree_free()
void X509_policy_tree_free (X509_POLICY_TREE * tree)
Definition at line 604 of file pcy_tree.c.
Referenced by X509_STORE_CTX_cleanup().
X509_policy_tree_get0_level()
X509_POLICY_LEVEL* X509_policy_tree_get0_level (const X509_POLICY_TREE * tree, int i)
Definition at line 27 of file pcy_lib.c.
References NULL.
X509_policy_tree_level_count()
int X509_policy_tree_level_count (const X509_POLICY_TREE * tree)
Definition at line 20 of file pcy_lib.c.
X509_STORE_add_cert()
int X509_STORE_add_cert (X509_STORE * ctx, X509 * x)
Definition at line 308 of file x509_lu.c.
References obj.
Referenced by ssl_build_cert_chain(), and X509_load_cert_crl_file().
X509_STORE_add_crl()
int X509_STORE_add_crl (X509_STORE * ctx, X509_CRL * x)
Definition at line 343 of file x509_lu.c.
References obj.
Referenced by X509_load_cert_crl_file().
X509_STORE_add_lookup()
X509_LOOKUP* X509_STORE_add_lookup (X509_STORE * v, X509_LOOKUP_METHOD * m)
Definition at line 232 of file x509_lu.c.
References NULL, STACK_OF(), X509_LOOKUP_free(), and X509_LOOKUP_new().
X509_STORE_CTX_cleanup()
void X509_STORE_CTX_cleanup (X509_STORE_CTX * ctx)
Definition at line 2370 of file x509_vfy.c.
References CRYPTO_EX_INDEX_X509_STORE_CTX, CRYPTO_free_ex_data(), NULL, X509_policy_tree_free(), and X509_VERIFY_PARAM_free().
Referenced by X509_STORE_CTX_free().
X509_STORE_CTX_free()
void X509_STORE_CTX_free (X509_STORE_CTX * ctx)
Definition at line 2212 of file x509_vfy.c.
References NULL, OPENSSL_free, and X509_STORE_CTX_cleanup().
Referenced by ssl_build_cert_chain(), and ssl_verify_cert_chain().
X509_STORE_CTX_get0_cert()
X509* X509_STORE_CTX_get0_cert (X509_STORE_CTX * ctx)
Definition at line 2412 of file x509_vfy.c.
X509_STORE_CTX_get0_current_crl()
X509_CRL* X509_STORE_CTX_get0_current_crl (X509_STORE_CTX * ctx)
Definition at line 2100 of file x509_vfy.c.
X509_STORE_CTX_get0_current_issuer()
X509* X509_STORE_CTX_get0_current_issuer (X509_STORE_CTX * ctx)
Definition at line 2095 of file x509_vfy.c.
X509_STORE_CTX_get0_param()
X509_VERIFY_PARAM* X509_STORE_CTX_get0_param (X509_STORE_CTX * ctx)
Definition at line 2529 of file x509_vfy.c.
Referenced by ssl_verify_cert_chain().
X509_STORE_CTX_get0_parent_ctx()
X509_STORE_CTX* X509_STORE_CTX_get0_parent_ctx (X509_STORE_CTX * ctx)
Definition at line 2105 of file x509_vfy.c.
X509_STORE_CTX_get0_policy_tree()
X509_POLICY_TREE* X509_STORE_CTX_get0_policy_tree (X509_STORE_CTX * ctx)
Definition at line 2505 of file x509_vfy.c.
Referenced by policies_print().
X509_STORE_CTX_get0_store()
X509_STORE* X509_STORE_CTX_get0_store (X509_STORE_CTX * ctx)
Definition at line 858 of file x509_lu.c.
X509_STORE_CTX_get1_issuer()
int X509_STORE_CTX_get1_issuer (X509 ** issuer, X509_STORE_CTX * ctx, X509 * x)
Definition at line 625 of file x509_lu.c.
References NULL, obj, and X509_OBJECT_new().
X509_STORE_CTX_get_by_subject()
int X509_STORE_CTX_get_by_subject (X509_STORE_CTX * vs, X509_LOOKUP_TYPE type, X509_NAME * name, X509_OBJECT * ret)
Definition at line 275 of file x509_lu.c.
X509_STORE_CTX_get_cert_crl()
X509_STORE_CTX_cert_crl_fn X509_STORE_CTX_get_cert_crl (X509_STORE_CTX * ctx)
Definition at line 2480 of file x509_vfy.c.
X509_STORE_CTX_get_check_crl()
X509_STORE_CTX_check_crl_fn X509_STORE_CTX_get_check_crl (X509_STORE_CTX * ctx)
Definition at line 2475 of file x509_vfy.c.
X509_STORE_CTX_get_check_issued()
X509_STORE_CTX_check_issued_fn X509_STORE_CTX_get_check_issued (X509_STORE_CTX * ctx)
Definition at line 2460 of file x509_vfy.c.
X509_STORE_CTX_get_check_policy()
X509_STORE_CTX_check_policy_fn X509_STORE_CTX_get_check_policy (X509_STORE_CTX * ctx)
Definition at line 2485 of file x509_vfy.c.
X509_STORE_CTX_get_check_revocation()
X509_STORE_CTX_check_revocation_fn X509_STORE_CTX_get_check_revocation (X509_STORE_CTX * ctx)
Definition at line 2465 of file x509_vfy.c.
X509_STORE_CTX_get_cleanup()
X509_STORE_CTX_cleanup_fn X509_STORE_CTX_get_cleanup (X509_STORE_CTX * ctx)
Definition at line 2500 of file x509_vfy.c.
X509_STORE_CTX_get_current_cert()
X509* X509_STORE_CTX_get_current_cert (X509_STORE_CTX * ctx)
Definition at line 2073 of file x509_vfy.c.
Referenced by verify_callback().
X509_STORE_CTX_get_error()
int X509_STORE_CTX_get_error (X509_STORE_CTX * ctx)
Definition at line 2053 of file x509_vfy.c.
Referenced by ssl_build_cert_chain(), ssl_verify_cert_chain(), and verify_callback().
X509_STORE_CTX_get_error_depth()
int X509_STORE_CTX_get_error_depth (X509_STORE_CTX * ctx)
Definition at line 2063 of file x509_vfy.c.
Referenced by verify_callback().
X509_STORE_CTX_get_ex_data()
void* X509_STORE_CTX_get_ex_data (X509_STORE_CTX * ctx, int idx)
Definition at line 2048 of file x509_vfy.c.
X509_STORE_CTX_get_explicit_policy()
int X509_STORE_CTX_get_explicit_policy (X509_STORE_CTX * ctx)
Definition at line 2510 of file x509_vfy.c.
Referenced by policies_print().
X509_STORE_CTX_get_get_crl()
X509_STORE_CTX_get_crl_fn X509_STORE_CTX_get_get_crl (X509_STORE_CTX * ctx)
Definition at line 2470 of file x509_vfy.c.
X509_STORE_CTX_get_get_issuer()
X509_STORE_CTX_get_issuer_fn X509_STORE_CTX_get_get_issuer (X509_STORE_CTX * ctx)
Definition at line 2455 of file x509_vfy.c.
X509_STORE_CTX_get_lookup_certs()
X509_STORE_CTX_lookup_certs_fn X509_STORE_CTX_get_lookup_certs (X509_STORE_CTX * ctx)
Definition at line 2490 of file x509_vfy.c.
X509_STORE_CTX_get_lookup_crls()
X509_STORE_CTX_lookup_crls_fn X509_STORE_CTX_get_lookup_crls (X509_STORE_CTX * ctx)
Definition at line 2495 of file x509_vfy.c.
X509_STORE_CTX_get_num_untrusted()
int X509_STORE_CTX_get_num_untrusted (X509_STORE_CTX * ctx)
Definition at line 2515 of file x509_vfy.c.
X509_STORE_CTX_get_obj_by_subject()
X509_OBJECT* X509_STORE_CTX_get_obj_by_subject (X509_STORE_CTX * vs, X509_LOOKUP_TYPE type, X509_NAME * name)
Definition at line 260 of file x509_lu.c.
X509_STORE_CTX_get_verify()
X509_STORE_CTX_verify_fn X509_STORE_CTX_get_verify (X509_STORE_CTX * ctx)
Definition at line 2450 of file x509_vfy.c.
X509_STORE_CTX_get_verify_cb()
X509_STORE_CTX_verify_cb X509_STORE_CTX_get_verify_cb (X509_STORE_CTX * ctx)
Definition at line 2439 of file x509_vfy.c.
X509_STORE_CTX_init()
int X509_STORE_CTX_init (X509_STORE_CTX * ctx, X509_STORE * store, X509 * x509, STACK_OF(X509) * chain)
Definition at line 2221 of file x509_vfy.c.
Referenced by ssl_build_cert_chain(), and ssl_verify_cert_chain().
X509_STORE_CTX_new()
X509_STORE_CTX* X509_STORE_CTX_new (void)
Definition at line 2201 of file x509_vfy.c.
References ctx, ERR_R_MALLOC_FAILURE, NULL, OPENSSL_zalloc, X509_F_X509_STORE_CTX_NEW, and X509err.
Referenced by OCSP_request_verify(), ssl_build_cert_chain(), and ssl_verify_cert_chain().
X509_STORE_CTX_purpose_inherit()
int X509_STORE_CTX_purpose_inherit (X509_STORE_CTX * ctx, int def_purpose, int purpose, int trust)
Definition at line 2150 of file x509_vfy.c.
Referenced by X509_STORE_CTX_set_purpose(), and X509_STORE_CTX_set_trust().
X509_STORE_CTX_set0_crls()
void X509_STORE_CTX_set0_crls (X509_STORE_CTX * c, STACK_OF(X509_CRL) * sk)
Definition at line 2115 of file x509_vfy.c.
X509_STORE_CTX_set0_dane()
void X509_STORE_CTX_set0_dane (X509_STORE_CTX * ctx, SSL_DANE * dane)
Definition at line 2540 of file x509_vfy.c.
Referenced by ssl_verify_cert_chain().
X509_STORE_CTX_set0_param()
void X509_STORE_CTX_set0_param (X509_STORE_CTX * ctx, X509_VERIFY_PARAM * param)
Definition at line 2534 of file x509_vfy.c.
References X509_VERIFY_PARAM_free().
X509_STORE_CTX_set0_trusted_stack()
void X509_STORE_CTX_set0_trusted_stack (X509_STORE_CTX * ctx, STACK_OF(X509) * sk)
Definition at line 2363 of file x509_vfy.c.
X509_STORE_CTX_set0_untrusted()
void X509_STORE_CTX_set0_untrusted (X509_STORE_CTX * ctx, STACK_OF(X509) * sk)
Definition at line 2422 of file x509_vfy.c.
X509_STORE_CTX_set0_verified_chain()
void X509_STORE_CTX_set0_verified_chain (X509_STORE_CTX * c, STACK_OF(X509) * sk)
Definition at line 2427 of file x509_vfy.c.
X509_STORE_CTX_set_cert()
void X509_STORE_CTX_set_cert (X509_STORE_CTX * c, X509 * x)
Definition at line 2110 of file x509_vfy.c.
X509_STORE_CTX_set_current_cert()
void X509_STORE_CTX_set_current_cert (X509_STORE_CTX * ctx, X509 * x)
Definition at line 2078 of file x509_vfy.c.
X509_STORE_CTX_set_default()
int X509_STORE_CTX_set_default (X509_STORE_CTX * ctx, const char * name)
Definition at line 2520 of file x509_vfy.c.
References X509_VERIFY_PARAM_inherit(), and X509_VERIFY_PARAM_lookup().
Referenced by ssl_verify_cert_chain().
X509_STORE_CTX_set_depth()
void X509_STORE_CTX_set_depth (X509_STORE_CTX * ctx, int depth)
Definition at line 2396 of file x509_vfy.c.
References X509_VERIFY_PARAM_set_depth().
X509_STORE_CTX_set_error()
void X509_STORE_CTX_set_error (X509_STORE_CTX * ctx, int s)
Definition at line 2058 of file x509_vfy.c.
X509_STORE_CTX_set_error_depth()
void X509_STORE_CTX_set_error_depth (X509_STORE_CTX * ctx, int depth)
Definition at line 2068 of file x509_vfy.c.
X509_STORE_CTX_set_ex_data()
int X509_STORE_CTX_set_ex_data (X509_STORE_CTX * ctx, int idx, void * data)
Definition at line 2043 of file x509_vfy.c.
Referenced by ssl_verify_cert_chain().
X509_STORE_CTX_set_flags()
void X509_STORE_CTX_set_flags (X509_STORE_CTX * ctx, unsigned long flags)
Definition at line 2401 of file x509_vfy.c.
References X509_VERIFY_PARAM_set_flags().
Referenced by ssl_build_cert_chain(), and ssl_verify_cert_chain().
X509_STORE_CTX_set_purpose()
int X509_STORE_CTX_set_purpose (X509_STORE_CTX * ctx, int purpose)
Definition at line 2120 of file x509_vfy.c.
References X509_STORE_CTX_purpose_inherit().
X509_STORE_CTX_set_time()
void X509_STORE_CTX_set_time (X509_STORE_CTX * ctx, unsigned long flags, time_t t)
Definition at line 2406 of file x509_vfy.c.
References X509_VERIFY_PARAM_set_time().
X509_STORE_CTX_set_trust()
int X509_STORE_CTX_set_trust (X509_STORE_CTX * ctx, int trust)
Definition at line 2130 of file x509_vfy.c.
References X509_STORE_CTX_purpose_inherit().
X509_STORE_CTX_set_verify()
void X509_STORE_CTX_set_verify (X509_STORE_CTX * ctx, X509_STORE_CTX_verify_fn verify)
Definition at line 2444 of file x509_vfy.c.
X509_STORE_CTX_set_verify_cb()
void X509_STORE_CTX_set_verify_cb (X509_STORE_CTX * ctx, X509_STORE_CTX_verify_cb verify)
Definition at line 2433 of file x509_vfy.c.
Referenced by ssl_verify_cert_chain().
X509_STORE_free()
void X509_STORE_free (X509_STORE * v)
Definition at line 190 of file x509_lu.c.
References CRYPTO_DOWN_REF, NULL, REF_ASSERT_ISNT, REF_PRINT_COUNT, STACK_OF(), X509_LOOKUP_free(), and X509_LOOKUP_shutdown().
Referenced by ssl_build_cert_chain(), ssl_cert_set_cert_store(), SSL_CTX_set_cert_store(), and TS_VERIFY_CTX_cleanup().
X509_STORE_get0_param()
X509_VERIFY_PARAM* X509_STORE_get0_param (X509_STORE * ctx)
Definition at line 712 of file x509_lu.c.
X509_STORE_get_cert_crl()
X509_STORE_CTX_cert_crl_fn X509_STORE_get_cert_crl (X509_STORE * ctx)
Definition at line 799 of file x509_lu.c.
X509_STORE_get_check_crl()
X509_STORE_CTX_check_crl_fn X509_STORE_get_check_crl (X509_STORE * ctx)
Definition at line 788 of file x509_lu.c.
X509_STORE_get_check_issued()
X509_STORE_CTX_check_issued_fn X509_STORE_get_check_issued (X509_STORE * ctx)
Definition at line 755 of file x509_lu.c.
X509_STORE_get_check_policy()
X509_STORE_CTX_check_policy_fn X509_STORE_get_check_policy (X509_STORE * ctx)
Definition at line 810 of file x509_lu.c.
X509_STORE_get_check_revocation()
X509_STORE_CTX_check_revocation_fn X509_STORE_get_check_revocation (X509_STORE * ctx)
Definition at line 766 of file x509_lu.c.
X509_STORE_get_cleanup()
X509_STORE_CTX_cleanup_fn X509_STORE_get_cleanup (X509_STORE * ctx)
Definition at line 843 of file x509_lu.c.
X509_STORE_get_ex_data()
void* X509_STORE_get_ex_data (X509_STORE * ctx, int idx)
Definition at line 853 of file x509_lu.c.
X509_STORE_get_get_crl()
X509_STORE_CTX_get_crl_fn X509_STORE_get_get_crl (X509_STORE * ctx)
Definition at line 777 of file x509_lu.c.
X509_STORE_get_get_issuer()
X509_STORE_CTX_get_issuer_fn X509_STORE_get_get_issuer (X509_STORE * ctx)
Definition at line 744 of file x509_lu.c.
X509_STORE_get_lookup_certs()
X509_STORE_CTX_lookup_certs_fn X509_STORE_get_lookup_certs (X509_STORE * ctx)
Definition at line 821 of file x509_lu.c.
X509_STORE_get_lookup_crls()
X509_STORE_CTX_lookup_crls_fn X509_STORE_get_lookup_crls (X509_STORE * ctx)
Definition at line 832 of file x509_lu.c.
X509_STORE_get_verify()
X509_STORE_CTX_verify_fn X509_STORE_get_verify (X509_STORE * ctx)
Definition at line 722 of file x509_lu.c.
X509_STORE_get_verify_cb()
X509_STORE_CTX_verify_cb X509_STORE_get_verify_cb (X509_STORE * ctx)
Definition at line 733 of file x509_lu.c.
X509_STORE_load_locations()
int X509_STORE_load_locations (X509_STORE * ctx, const char * file, const char * dir)
Definition at line 35 of file x509_d2.c.
Referenced by SSL_CTX_load_verify_locations(), and ssl_load_stores().
X509_STORE_lock()
int X509_STORE_lock (X509_STORE * ctx)
Definition at line 43 of file x509_lu.c.
References CRYPTO_THREAD_write_lock().
X509_STORE_new()
X509_STORE* X509_STORE_new (void)
Definition at line 142 of file x509_lu.c.
Referenced by setup_verify(), ssl_build_cert_chain(), and ssl_load_stores().
X509_STORE_set1_param()
int X509_STORE_set1_param (X509_STORE * ctx, X509_VERIFY_PARAM * pm)
Definition at line 707 of file x509_lu.c.
References X509_VERIFY_PARAM_set1().
X509_STORE_set_cert_crl()
void X509_STORE_set_cert_crl (X509_STORE * ctx, X509_STORE_CTX_cert_crl_fn cert_crl)
Definition at line 793 of file x509_lu.c.
X509_STORE_set_check_crl()
void X509_STORE_set_check_crl (X509_STORE * ctx, X509_STORE_CTX_check_crl_fn check_crl)
Definition at line 782 of file x509_lu.c.
X509_STORE_set_check_issued()
void X509_STORE_set_check_issued (X509_STORE * ctx, X509_STORE_CTX_check_issued_fn check_issued)
Definition at line 749 of file x509_lu.c.
X509_STORE_set_check_policy()
void X509_STORE_set_check_policy (X509_STORE * ctx, X509_STORE_CTX_check_policy_fn check_policy)
Definition at line 804 of file x509_lu.c.
X509_STORE_set_check_revocation()
void X509_STORE_set_check_revocation (X509_STORE * ctx, X509_STORE_CTX_check_revocation_fn check_revocation)
Definition at line 760 of file x509_lu.c.
X509_STORE_set_cleanup()
void X509_STORE_set_cleanup (X509_STORE * ctx, X509_STORE_CTX_cleanup_fn cleanup)
Definition at line 837 of file x509_lu.c.
X509_STORE_set_default_paths()
int X509_STORE_set_default_paths (X509_STORE * ctx)
Definition at line 15 of file x509_d2.c.
Referenced by SSL_CTX_set_default_verify_paths().
X509_STORE_set_depth()
int X509_STORE_set_depth (X509_STORE * store, int depth)
Definition at line 691 of file x509_lu.c.
References X509_VERIFY_PARAM_set_depth().
X509_STORE_set_ex_data()
int X509_STORE_set_ex_data (X509_STORE * ctx, int idx, void * data)
Definition at line 848 of file x509_lu.c.
X509_STORE_set_flags()
int X509_STORE_set_flags (X509_STORE * ctx, unsigned long flags)
Definition at line 686 of file x509_lu.c.
References X509_VERIFY_PARAM_set_flags().
X509_STORE_set_get_crl()
void X509_STORE_set_get_crl (X509_STORE * ctx, X509_STORE_CTX_get_crl_fn get_crl)
Definition at line 771 of file x509_lu.c.
X509_STORE_set_get_issuer()
void X509_STORE_set_get_issuer (X509_STORE * ctx, X509_STORE_CTX_get_issuer_fn get_issuer)
Definition at line 738 of file x509_lu.c.
X509_STORE_set_lookup_certs()
void X509_STORE_set_lookup_certs (X509_STORE * ctx, X509_STORE_CTX_lookup_certs_fn lookup_certs)
Definition at line 815 of file x509_lu.c.
X509_STORE_set_lookup_crls()
void X509_STORE_set_lookup_crls (X509_STORE * ctx, X509_STORE_CTX_lookup_crls_fn lookup_crls)
Definition at line 826 of file x509_lu.c.
X509_STORE_set_purpose()
int X509_STORE_set_purpose (X509_STORE * ctx, int purpose)
Definition at line 697 of file x509_lu.c.
References X509_VERIFY_PARAM_set_purpose().
X509_STORE_set_trust()
int X509_STORE_set_trust (X509_STORE * ctx, int trust)
Definition at line 702 of file x509_lu.c.
References X509_VERIFY_PARAM_set_trust().
X509_STORE_set_verify()
void X509_STORE_set_verify (X509_STORE * ctx, X509_STORE_CTX_verify_fn verify)
Definition at line 717 of file x509_lu.c.
X509_STORE_set_verify_cb()
void X509_STORE_set_verify_cb (X509_STORE * ctx, X509_STORE_CTX_verify_cb verify_cb)
Definition at line 727 of file x509_lu.c.
X509_STORE_unlock()
int X509_STORE_unlock (X509_STORE * ctx)
Definition at line 48 of file x509_lu.c.
References CRYPTO_THREAD_unlock().
X509_STORE_up_ref()
int X509_STORE_up_ref (X509_STORE * v)
Definition at line 220 of file x509_lu.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by ssl_cert_set_cert_store(), and SSL_CTX_set1_cert_store().
X509_VERIFY_PARAM_add0_policy()
int X509_VERIFY_PARAM_add0_policy (X509_VERIFY_PARAM * param, ASN1_OBJECT * policy)
Definition at line 334 of file x509_vpm.c.
X509_VERIFY_PARAM_add0_table()
int X509_VERIFY_PARAM_add0_table (X509_VERIFY_PARAM * param)
Definition at line 545 of file x509_vpm.c.
X509_VERIFY_PARAM_add1_host()
int X509_VERIFY_PARAM_add1_host (X509_VERIFY_PARAM * param, const char * name, size_t namelen)
Definition at line 386 of file x509_vpm.c.
Referenced by SSL_add1_host().
X509_VERIFY_PARAM_clear_flags()
int X509_VERIFY_PARAM_clear_flags (X509_VERIFY_PARAM * param, unsigned long flags)
Definition at line 280 of file x509_vpm.c.
X509_VERIFY_PARAM_free()
void X509_VERIFY_PARAM_free (X509_VERIFY_PARAM * param)
Definition at line 100 of file x509_vpm.c.
References ASN1_OBJECT_free(), and NULL.
Referenced by SSL_CTX_free(), SSL_free(), X509_STORE_CTX_cleanup(), X509_STORE_CTX_set0_param(), and X509_VERIFY_PARAM_table_cleanup().
X509_VERIFY_PARAM_get0()
const X509_VERIFY_PARAM* X509_VERIFY_PARAM_get0 (int id)
Definition at line 574 of file x509_vpm.c.
References OSSL_NELEM.
X509_VERIFY_PARAM_get0_name()
const char* X509_VERIFY_PARAM_get0_name (const X509_VERIFY_PARAM * param)
Definition at line 458 of file x509_vpm.c.
X509_VERIFY_PARAM_get0_peername()
char* X509_VERIFY_PARAM_get0_peername (X509_VERIFY_PARAM *)
Definition at line 398 of file x509_vpm.c.
Referenced by SSL_get0_peername().
X509_VERIFY_PARAM_get_auth_level()
int X509_VERIFY_PARAM_get_auth_level (const X509_VERIFY_PARAM * param)
Definition at line 453 of file x509_vpm.c.
X509_VERIFY_PARAM_get_count()
int X509_VERIFY_PARAM_get_count (void)
Definition at line 566 of file x509_vpm.c.
References OSSL_NELEM.
X509_VERIFY_PARAM_get_depth()
int X509_VERIFY_PARAM_get_depth (const X509_VERIFY_PARAM * param)
Definition at line 448 of file x509_vpm.c.
Referenced by SSL_CTX_get_verify_depth(), and SSL_get_verify_depth().
X509_VERIFY_PARAM_get_flags()
unsigned long X509_VERIFY_PARAM_get_flags (X509_VERIFY_PARAM * param)
Definition at line 287 of file x509_vpm.c.
X509_VERIFY_PARAM_get_inh_flags()
uint32_t X509_VERIFY_PARAM_get_inh_flags (const X509_VERIFY_PARAM * param)
Definition at line 292 of file x509_vpm.c.
X509_VERIFY_PARAM_get_time()
time_t X509_VERIFY_PARAM_get_time (const X509_VERIFY_PARAM * param)
Definition at line 323 of file x509_vpm.c.
X509_VERIFY_PARAM_inherit()
int X509_VERIFY_PARAM_inherit (X509_VERIFY_PARAM * to, const X509_VERIFY_PARAM * from)
Definition at line 156 of file x509_vpm.c.
References NULL, test_x509_verify_param_copy, X509_TRUST_DEFAULT, X509_V_FLAG_USE_CHECK_TIME, x509_verify_param_copy, X509_VERIFY_PARAM_set1_policies(), X509_VP_FLAG_DEFAULT, X509_VP_FLAG_LOCKED, X509_VP_FLAG_ONCE, X509_VP_FLAG_OVERWRITE, and X509_VP_FLAG_RESET_FLAGS.
Referenced by SSL_new(), and X509_STORE_CTX_set_default().
X509_VERIFY_PARAM_lookup()
const X509_VERIFY_PARAM* X509_VERIFY_PARAM_lookup (const char * name)
Definition at line 582 of file x509_vpm.c.
Referenced by X509_STORE_CTX_set_default().
X509_VERIFY_PARAM_move_peername()
void X509_VERIFY_PARAM_move_peername (X509_VERIFY_PARAM * , X509_VERIFY_PARAM *)
Definition at line 408 of file x509_vpm.c.
References if(), NULL, and OPENSSL_free.
Referenced by ssl_verify_cert_chain().
X509_VERIFY_PARAM_new()
X509_VERIFY_PARAM* X509_VERIFY_PARAM_new (void)
Definition at line 83 of file x509_vpm.c.
References NULL, OPENSSL_zalloc, and X509_TRUST_DEFAULT.
Referenced by SSL_new().
X509_VERIFY_PARAM_set1()
int X509_VERIFY_PARAM_set1 (X509_VERIFY_PARAM * to, const X509_VERIFY_PARAM * from)
Definition at line 230 of file x509_vpm.c.
Referenced by SSL_CTX_set1_param(), SSL_set1_param(), ssl_verify_cert_chain(), and X509_STORE_set1_param().
X509_VERIFY_PARAM_set1_email()
int X509_VERIFY_PARAM_set1_email (X509_VERIFY_PARAM * param, const char * email, size_t emaillen)
Definition at line 421 of file x509_vpm.c.
X509_VERIFY_PARAM_set1_host()
int X509_VERIFY_PARAM_set1_host (X509_VERIFY_PARAM * param, const char * name, size_t namelen)
Definition at line 380 of file x509_vpm.c.
Referenced by SSL_dane_enable(), and SSL_set1_host().
X509_VERIFY_PARAM_set1_ip()
int X509_VERIFY_PARAM_set1_ip (X509_VERIFY_PARAM * param, const unsigned char * ip, size_t iplen)
Definition at line 428 of file x509_vpm.c.
Referenced by X509_VERIFY_PARAM_set1_ip_asc().
X509_VERIFY_PARAM_set1_ip_asc()
int X509_VERIFY_PARAM_set1_ip_asc (X509_VERIFY_PARAM * param, const char * ipasc)
Definition at line 437 of file x509_vpm.c.
References a2i_ipadd(), and X509_VERIFY_PARAM_set1_ip().
X509_VERIFY_PARAM_set1_name()
int X509_VERIFY_PARAM_set1_name (X509_VERIFY_PARAM * param, const char * name)
Definition at line 263 of file x509_vpm.c.
References OPENSSL_free, and OPENSSL_strdup.
X509_VERIFY_PARAM_set1_policies()
int X509_VERIFY_PARAM_set1_policies (X509_VERIFY_PARAM * param, STACK_OF(ASN1_OBJECT) * policies)
Definition at line 347 of file x509_vpm.c.
Referenced by X509_VERIFY_PARAM_inherit().
X509_VERIFY_PARAM_set_auth_level()
void X509_VERIFY_PARAM_set_auth_level (X509_VERIFY_PARAM * param, int auth_level)
Definition at line 318 of file x509_vpm.c.
Referenced by ssl_verify_cert_chain().
X509_VERIFY_PARAM_set_depth()
void X509_VERIFY_PARAM_set_depth (X509_VERIFY_PARAM * param, int depth)
Definition at line 313 of file x509_vpm.c.
Referenced by SSL_CTX_set_verify_depth(), SSL_set_verify_depth(), X509_STORE_CTX_set_depth(), and X509_STORE_set_depth().
X509_VERIFY_PARAM_set_flags()
int X509_VERIFY_PARAM_set_flags (X509_VERIFY_PARAM * param, unsigned long flags)
Definition at line 272 of file x509_vpm.c.
References flags, X509_V_FLAG_POLICY_CHECK, and X509_V_FLAG_POLICY_MASK.
Referenced by X509_STORE_CTX_set_flags(), and X509_STORE_set_flags().
X509_VERIFY_PARAM_set_hostflags()
void X509_VERIFY_PARAM_set_hostflags (X509_VERIFY_PARAM * param, unsigned int flags)
Definition at line 392 of file x509_vpm.c.
References flags.
Referenced by SSL_set_hostflags().
X509_VERIFY_PARAM_set_inh_flags()
int X509_VERIFY_PARAM_set_inh_flags (X509_VERIFY_PARAM * param, uint32_t flags)
Definition at line 297 of file x509_vpm.c.
References flags.
X509_VERIFY_PARAM_set_purpose()
int X509_VERIFY_PARAM_set_purpose (X509_VERIFY_PARAM * param, int purpose)
Definition at line 303 of file x509_vpm.c.
References X509_PURPOSE_set().
Referenced by SSL_CTX_set_purpose(), SSL_set_purpose(), and X509_STORE_set_purpose().
X509_VERIFY_PARAM_set_time()
void X509_VERIFY_PARAM_set_time (X509_VERIFY_PARAM * param, time_t t)
Definition at line 328 of file x509_vpm.c.
References t, and X509_V_FLAG_USE_CHECK_TIME.
Referenced by X509_STORE_CTX_set_time().
X509_VERIFY_PARAM_set_trust()
int X509_VERIFY_PARAM_set_trust (X509_VERIFY_PARAM * param, int trust)
Definition at line 308 of file x509_vpm.c.
References X509_TRUST_set().
Referenced by SSL_CTX_set_trust(), SSL_set_trust(), and X509_STORE_set_trust().
X509_VERIFY_PARAM_table_cleanup()
void X509_VERIFY_PARAM_table_cleanup (void)
Definition at line 596 of file x509_vpm.c.
References NULL, and X509_VERIFY_PARAM_free().