crypto/x509/x509_cmp.c File Reference
x509_cmp.c File Reference
#include <stdio.h>
#include <ctype.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include <openssl/objects.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include "internal/x509_int.h"
Functions
int X509_issuer_and_serial_cmp (const X509 *a, const X509 *b)
unsigned long X509_issuer_and_serial_hash (X509 *a)
int X509_issuer_name_cmp (const X509 *a, const X509 *b)
int X509_subject_name_cmp (const X509 *a, const X509 *b)
int X509_CRL_cmp (const X509_CRL *a, const X509_CRL *b)
int X509_CRL_match (const X509_CRL *a, const X509_CRL *b)
X509_NAME * X509_get_issuer_name (const X509 *a)
unsigned long X509_issuer_name_hash (X509 *x)
unsigned long X509_issuer_name_hash_old (X509 *x)
X509_NAME * X509_get_subject_name (const X509 *a)
ASN1_INTEGER * X509_get_serialNumber (X509 *a)
const ASN1_INTEGER * X509_get0_serialNumber (const X509 *a)
unsigned long X509_subject_name_hash (X509 *x)
unsigned long X509_subject_name_hash_old (X509 *x)
int X509_cmp (const X509 *a, const X509 *b)
int X509_NAME_cmp (const X509_NAME *a, const X509_NAME *b)
unsigned long X509_NAME_hash (X509_NAME *x)
unsigned long X509_NAME_hash_old (X509_NAME *x)
X509 * X509_find_by_issuer_and_serial (STACK_OF(X509) *sk, X509_NAME *name, ASN1_INTEGER *serial)
X509 * X509_find_by_subject (STACK_OF(X509) *sk, X509_NAME *name)
EVP_PKEY * X509_get0_pubkey (const X509 *x)
EVP_PKEY * X509_get_pubkey (X509 *x)
int X509_check_private_key (const X509 *x, const EVP_PKEY *k)
int X509_chain_check_suiteb (int *perror_depth, X509 *x, STACK_OF(X509) *chain, unsigned long flags)
int X509_CRL_check_suiteb (X509_CRL *crl, EVP_PKEY *pk, unsigned long flags)
STACK_OF (X509)
Function Documentation
STACK_OF()
STACK_OF (X509)
Definition at line 449 of file x509_cmp.c.
X509_chain_check_suiteb()
int X509_chain_check_suiteb (int * perror_depth, X509 * x, STACK_OF(X509) * chain, unsigned long flags)
Definition at line 347 of file x509_cmp.c.
References flags, NULL, X509_get0_pubkey(), X509_V_FLAG_SUITEB_128_LOS, and X509_V_OK.
X509_check_private_key()
int X509_check_private_key (const X509 * x, const EVP_PKEY * k)
Definition at line 279 of file x509_cmp.c.
Referenced by OCSP_basic_sign(), OCSP_request_sign(), SSL_check_private_key(), and SSL_CTX_check_private_key().
X509_cmp()
int X509_cmp (const X509 * a, const X509 * b)
Definition at line 135 of file x509_cmp.c.
References SHA_DIGEST_LENGTH, and X509_check_purpose().
X509_CRL_check_suiteb()
int X509_CRL_check_suiteb (X509_CRL * crl, EVP_PKEY * pk, unsigned long flags)
Definition at line 422 of file x509_cmp.c.
References OBJ_obj2nid(), X509_V_FLAG_SUITEB_128_LOS, and X509_V_OK.
X509_CRL_cmp()
int X509_CRL_cmp (const X509_CRL * a, const X509_CRL * b)
Definition at line 73 of file x509_cmp.c.
References X509_NAME_cmp().
X509_CRL_match()
int X509_CRL_match (const X509_CRL * a, const X509_CRL * b)
Definition at line 78 of file x509_cmp.c.
X509_find_by_issuer_and_serial()
X509* X509_find_by_issuer_and_serial (STACK_OF(X509) * sk, X509_NAME * name, ASN1_INTEGER * serial)
Definition at line 232 of file x509_cmp.c.
References NULL, and X509_issuer_and_serial_cmp().
Referenced by PKCS7_cert_from_signer_info(), and STACK_OF().
X509_find_by_subject()
X509* X509_find_by_subject (STACK_OF(X509) * sk, X509_NAME * name)
Definition at line 252 of file x509_cmp.c.
References NULL, X509_get_subject_name(), and X509_NAME_cmp().
X509_get0_pubkey()
EVP_PKEY* X509_get0_pubkey (const X509 * x)
Definition at line 265 of file x509_cmp.c.
References NULL, and X509_PUBKEY_get0().
Referenced by CMS_add1_recipient_cert(), PKCS7_signatureVerify(), SCT_validate(), ssl_cert_type(), and X509_chain_check_suiteb().
X509_get0_serialNumber()
const ASN1_INTEGER* X509_get0_serialNumber (const X509 * a)
Definition at line 110 of file x509_cmp.c.
Referenced by OCSP_cert_to_id().
X509_get_issuer_name()
X509_NAME* X509_get_issuer_name (const X509 * a)
Definition at line 83 of file x509_cmp.c.
Referenced by OCSP_cert_to_id(), verify_callback(), X509_check_akid(), and X509_check_issued().
X509_get_pubkey()
EVP_PKEY* X509_get_pubkey (X509 * x)
Definition at line 272 of file x509_cmp.c.
References NULL, and X509_PUBKEY_get().
Referenced by CMS_SignerInfo_set1_signer_cert().
X509_get_serialNumber()
ASN1_INTEGER* X509_get_serialNumber (X509 * a)
Definition at line 105 of file x509_cmp.c.
Referenced by X509_check_akid().
X509_get_subject_name()
X509_NAME* X509_get_subject_name (const X509 * a)
Definition at line 100 of file x509_cmp.c.
Referenced by OCSP_cert_to_id(), OCSP_request_sign(), verify_callback(), X509_check_issued(), X509_find_by_subject(), and X509_ocspid_print().
X509_issuer_and_serial_cmp()
int X509_issuer_and_serial_cmp (const X509 * a, const X509 * b)
Definition at line 19 of file x509_cmp.c.
References ASN1_INTEGER_cmp(), and X509_NAME_cmp().
Referenced by X509_find_by_issuer_and_serial().
X509_issuer_and_serial_hash()
unsigned long X509_issuer_and_serial_hash (X509 * a)
Definition at line 33 of file x509_cmp.c.
X509_issuer_name_cmp()
int X509_issuer_name_cmp (const X509 * a, const X509 * b)
Definition at line 63 of file x509_cmp.c.
References X509_NAME_cmp().
X509_issuer_name_hash()
unsigned long X509_issuer_name_hash (X509 * x)
Definition at line 88 of file x509_cmp.c.
References X509_NAME_hash().
X509_issuer_name_hash_old()
unsigned long X509_issuer_name_hash_old (X509 * x)
Definition at line 94 of file x509_cmp.c.
References X509_NAME_hash_old().
X509_NAME_cmp()
int X509_NAME_cmp (const X509_NAME * a, const X509_NAME * b)
Definition at line 157 of file x509_cmp.c.
Referenced by X509_check_akid(), X509_check_issued(), X509_CRL_cmp(), X509_find_by_subject(), X509_issuer_and_serial_cmp(), X509_issuer_name_cmp(), and X509_subject_name_cmp().
X509_NAME_hash()
unsigned long X509_NAME_hash (X509_NAME * x)
Definition at line 184 of file x509_cmp.c.
Referenced by X509_issuer_name_hash(), and X509_subject_name_hash().
X509_NAME_hash_old()
unsigned long X509_NAME_hash_old (X509_NAME * x)
Definition at line 207 of file x509_cmp.c.
References EVP_MD_CTX_new().
Referenced by X509_issuer_name_hash_old(), and X509_subject_name_hash_old().
X509_subject_name_cmp()
int X509_subject_name_cmp (const X509 * a, const X509 * b)
Definition at line 68 of file x509_cmp.c.
References X509_NAME_cmp().
X509_subject_name_hash()
unsigned long X509_subject_name_hash (X509 * x)
Definition at line 115 of file x509_cmp.c.
References X509_NAME_hash().
X509_subject_name_hash_old()
unsigned long X509_subject_name_hash_old (X509 * x)
Definition at line 121 of file x509_cmp.c.
References X509_NAME_hash_old().