crypto/x509/x509_lu.c File Reference
x509_lu.c File Reference
#include <stdio.h>
#include "internal/cryptlib.h"
#include <openssl/lhash.h>
#include <openssl/x509.h>
#include "internal/x509_int.h"
#include <openssl/x509v3.h>
#include "x509_lcl.h"
Functions
X509_LOOKUP * X509_LOOKUP_new (X509_LOOKUP_METHOD *method)
void X509_LOOKUP_free (X509_LOOKUP *ctx)
int X509_STORE_lock (X509_STORE *s)
int X509_STORE_unlock (X509_STORE *s)
int X509_LOOKUP_init (X509_LOOKUP *ctx)
int X509_LOOKUP_shutdown (X509_LOOKUP *ctx)
int X509_LOOKUP_ctrl (X509_LOOKUP *ctx, int cmd, const char *argc, long argl, char **ret)
int X509_LOOKUP_by_subject (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type, X509_NAME *name, X509_OBJECT *ret)
int X509_LOOKUP_by_issuer_serial (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type, X509_NAME *name, ASN1_INTEGER *serial, X509_OBJECT *ret)
int X509_LOOKUP_by_fingerprint (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type, const unsigned char *bytes, int len, X509_OBJECT *ret)
int X509_LOOKUP_by_alias (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type, const char *str, int len, X509_OBJECT *ret)
X509_STORE * X509_STORE_new (void)
void X509_STORE_free (X509_STORE *vfy)
int X509_STORE_up_ref (X509_STORE *vfy)
X509_LOOKUP * X509_STORE_add_lookup (X509_STORE *v, X509_LOOKUP_METHOD *m)
X509_OBJECT * X509_STORE_CTX_get_obj_by_subject (X509_STORE_CTX *vs, X509_LOOKUP_TYPE type, X509_NAME *name)
int X509_STORE_CTX_get_by_subject (X509_STORE_CTX *vs, X509_LOOKUP_TYPE type, X509_NAME *name, X509_OBJECT *ret)
int X509_STORE_add_cert (X509_STORE *ctx, X509 *x)
int X509_STORE_add_crl (X509_STORE *ctx, X509_CRL *x)
int X509_OBJECT_up_ref_count (X509_OBJECT *a)
X509 * X509_OBJECT_get0_X509 (const X509_OBJECT *a)
X509_CRL * X509_OBJECT_get0_X509_CRL (X509_OBJECT *a)
X509_LOOKUP_TYPE X509_OBJECT_get_type (const X509_OBJECT *a)
X509_OBJECT * X509_OBJECT_new ()
void X509_OBJECT_free (X509_OBJECT *a)
int X509_OBJECT_idx_by_subject (STACK_OF(X509_OBJECT) *h, X509_LOOKUP_TYPE type, X509_NAME *name)
X509_OBJECT * X509_OBJECT_retrieve_by_subject (STACK_OF(X509_OBJECT) *h, X509_LOOKUP_TYPE type, X509_NAME *name)
STACK_OF (X509_OBJECT)
STACK_OF (X509)
STACK_OF (X509_CRL)
X509_OBJECT * X509_OBJECT_retrieve_match (STACK_OF(X509_OBJECT) *h, X509_OBJECT *x)
int X509_STORE_CTX_get1_issuer (X509 **issuer, X509_STORE_CTX *ctx, X509 *x)
int X509_STORE_set_flags (X509_STORE *ctx, unsigned long flags)
int X509_STORE_set_depth (X509_STORE *ctx, int depth)
int X509_STORE_set_purpose (X509_STORE *ctx, int purpose)
int X509_STORE_set_trust (X509_STORE *ctx, int trust)
int X509_STORE_set1_param (X509_STORE *ctx, X509_VERIFY_PARAM *param)
X509_VERIFY_PARAM * X509_STORE_get0_param (X509_STORE *ctx)
void X509_STORE_set_verify (X509_STORE *ctx, X509_STORE_CTX_verify_fn verify)
X509_STORE_CTX_verify_fn X509_STORE_get_verify (X509_STORE *ctx)
void X509_STORE_set_verify_cb (X509_STORE *ctx, X509_STORE_CTX_verify_cb verify_cb)
X509_STORE_CTX_verify_cb X509_STORE_get_verify_cb (X509_STORE *ctx)
void X509_STORE_set_get_issuer (X509_STORE *ctx, X509_STORE_CTX_get_issuer_fn get_issuer)
X509_STORE_CTX_get_issuer_fn X509_STORE_get_get_issuer (X509_STORE *ctx)
void X509_STORE_set_check_issued (X509_STORE *ctx, X509_STORE_CTX_check_issued_fn check_issued)
X509_STORE_CTX_check_issued_fn X509_STORE_get_check_issued (X509_STORE *ctx)
void X509_STORE_set_check_revocation (X509_STORE *ctx, X509_STORE_CTX_check_revocation_fn check_revocation)
X509_STORE_CTX_check_revocation_fn X509_STORE_get_check_revocation (X509_STORE *ctx)
void X509_STORE_set_get_crl (X509_STORE *ctx, X509_STORE_CTX_get_crl_fn get_crl)
X509_STORE_CTX_get_crl_fn X509_STORE_get_get_crl (X509_STORE *ctx)
void X509_STORE_set_check_crl (X509_STORE *ctx, X509_STORE_CTX_check_crl_fn check_crl)
X509_STORE_CTX_check_crl_fn X509_STORE_get_check_crl (X509_STORE *ctx)
void X509_STORE_set_cert_crl (X509_STORE *ctx, X509_STORE_CTX_cert_crl_fn cert_crl)
X509_STORE_CTX_cert_crl_fn X509_STORE_get_cert_crl (X509_STORE *ctx)
void X509_STORE_set_check_policy (X509_STORE *ctx, X509_STORE_CTX_check_policy_fn check_policy)
X509_STORE_CTX_check_policy_fn X509_STORE_get_check_policy (X509_STORE *ctx)
void X509_STORE_set_lookup_certs (X509_STORE *ctx, X509_STORE_CTX_lookup_certs_fn lookup_certs)
X509_STORE_CTX_lookup_certs_fn X509_STORE_get_lookup_certs (X509_STORE *ctx)
void X509_STORE_set_lookup_crls (X509_STORE *ctx, X509_STORE_CTX_lookup_crls_fn lookup_crls)
X509_STORE_CTX_lookup_crls_fn X509_STORE_get_lookup_crls (X509_STORE *ctx)
void X509_STORE_set_cleanup (X509_STORE *ctx, X509_STORE_CTX_cleanup_fn ctx_cleanup)
X509_STORE_CTX_cleanup_fn X509_STORE_get_cleanup (X509_STORE *ctx)
int X509_STORE_set_ex_data (X509_STORE *ctx, int idx, void *data)
void * X509_STORE_get_ex_data (X509_STORE *ctx, int idx)
X509_STORE * X509_STORE_CTX_get0_store (X509_STORE_CTX *ctx)
Function Documentation
STACK_OF() [1/3]
STACK_OF (X509_OBJECT)
Definition at line 495 of file x509_lu.c.
Referenced by X509_STORE_add_lookup(), and X509_STORE_free().
STACK_OF() [2/3]
STACK_OF (X509)
Definition at line 500 of file x509_lu.c.
STACK_OF() [3/3]
STACK_OF (X509_CRL)
Definition at line 548 of file x509_lu.c.
X509_LOOKUP_by_alias()
int X509_LOOKUP_by_alias (X509_LOOKUP * ctx, X509_LOOKUP_TYPE type, const char * str, int len, X509_OBJECT * ret)
Definition at line 112 of file x509_lu.c.
X509_LOOKUP_by_fingerprint()
int X509_LOOKUP_by_fingerprint (X509_LOOKUP * ctx, X509_LOOKUP_TYPE type, const unsigned char * bytes, int len, X509_OBJECT * ret)
Definition at line 103 of file x509_lu.c.
X509_LOOKUP_by_issuer_serial()
int X509_LOOKUP_by_issuer_serial (X509_LOOKUP * ctx, X509_LOOKUP_TYPE type, X509_NAME * name, ASN1_INTEGER * serial, X509_OBJECT * ret)
Definition at line 94 of file x509_lu.c.
X509_LOOKUP_by_subject()
int X509_LOOKUP_by_subject (X509_LOOKUP * ctx, X509_LOOKUP_TYPE type, X509_NAME * name, X509_OBJECT * ret)
Definition at line 84 of file x509_lu.c.
X509_LOOKUP_ctrl()
int X509_LOOKUP_ctrl (X509_LOOKUP * ctx, int cmd, const char * argc, long argl, char ** ret)
Definition at line 73 of file x509_lu.c.
X509_LOOKUP_free()
void X509_LOOKUP_free (X509_LOOKUP * ctx)
Definition at line 34 of file x509_lu.c.
References NULL, and OPENSSL_free.
Referenced by X509_STORE_add_lookup(), and X509_STORE_free().
X509_LOOKUP_init()
int X509_LOOKUP_init (X509_LOOKUP * ctx)
Definition at line 53 of file x509_lu.c.
References NULL.
X509_LOOKUP_new()
X509_LOOKUP* X509_LOOKUP_new (X509_LOOKUP_METHOD * method)
Definition at line 18 of file x509_lu.c.
Referenced by X509_STORE_add_lookup().
X509_LOOKUP_shutdown()
int X509_LOOKUP_shutdown (X509_LOOKUP * ctx)
Definition at line 63 of file x509_lu.c.
References NULL.
Referenced by X509_STORE_free().
X509_OBJECT_free()
void X509_OBJECT_free (X509_OBJECT * a)
Definition at line 422 of file x509_lu.c.
References NULL, OPENSSL_free, X509_LU_CRL, X509_LU_NONE, and X509_LU_X509.
X509_OBJECT_get0_X509()
X509* X509_OBJECT_get0_X509 (const X509_OBJECT * a)
Definition at line 390 of file x509_lu.c.
References NULL, and X509_LU_X509.
X509_OBJECT_get0_X509_CRL()
X509_CRL* X509_OBJECT_get0_X509_CRL (X509_OBJECT * a)
Definition at line 397 of file x509_lu.c.
References NULL, and X509_LU_CRL.
X509_OBJECT_get_type()
X509_LOOKUP_TYPE X509_OBJECT_get_type (const X509_OBJECT * a)
Definition at line 404 of file x509_lu.c.
X509_OBJECT_idx_by_subject()
int X509_OBJECT_idx_by_subject (STACK_OF(X509_OBJECT) * h, X509_LOOKUP_TYPE type, X509_NAME * name)
Definition at line 478 of file x509_lu.c.
X509_OBJECT_new()
X509_OBJECT* X509_OBJECT_new (void)
Definition at line 409 of file x509_lu.c.
Referenced by X509_STORE_CTX_get1_issuer().
X509_OBJECT_retrieve_by_subject()
X509_OBJECT* X509_OBJECT_retrieve_by_subject (STACK_OF(X509_OBJECT) * h, X509_LOOKUP_TYPE type, X509_NAME * name)
Definition at line 484 of file x509_lu.c.
X509_OBJECT_retrieve_match()
X509_OBJECT* X509_OBJECT_retrieve_match (STACK_OF(X509_OBJECT) * h, X509_OBJECT * x)
Definition at line 586 of file x509_lu.c.
X509_OBJECT_up_ref_count()
int X509_OBJECT_up_ref_count (X509_OBJECT * a)
Definition at line 377 of file x509_lu.c.
References X509_CRL_up_ref(), X509_LU_CRL, X509_LU_NONE, X509_LU_X509, and X509_up_ref().
X509_STORE_add_cert()
int X509_STORE_add_cert (X509_STORE * ctx, X509 * x)
Definition at line 308 of file x509_lu.c.
References obj.
Referenced by ssl_build_cert_chain(), and X509_load_cert_crl_file().
X509_STORE_add_crl()
int X509_STORE_add_crl (X509_STORE * ctx, X509_CRL * x)
Definition at line 343 of file x509_lu.c.
References obj.
Referenced by X509_load_cert_crl_file().
X509_STORE_add_lookup()
X509_LOOKUP* X509_STORE_add_lookup (X509_STORE * v, X509_LOOKUP_METHOD * m)
Definition at line 232 of file x509_lu.c.
References NULL, STACK_OF(), X509_LOOKUP_free(), and X509_LOOKUP_new().
X509_STORE_CTX_get0_store()
X509_STORE* X509_STORE_CTX_get0_store (X509_STORE_CTX * ctx)
Definition at line 858 of file x509_lu.c.
X509_STORE_CTX_get1_issuer()
int X509_STORE_CTX_get1_issuer (X509 ** issuer, X509_STORE_CTX * ctx, X509 * x)
Definition at line 625 of file x509_lu.c.
References NULL, obj, and X509_OBJECT_new().
X509_STORE_CTX_get_by_subject()
int X509_STORE_CTX_get_by_subject (X509_STORE_CTX * vs, X509_LOOKUP_TYPE type, X509_NAME * name, X509_OBJECT * ret)
Definition at line 275 of file x509_lu.c.
X509_STORE_CTX_get_obj_by_subject()
X509_OBJECT* X509_STORE_CTX_get_obj_by_subject (X509_STORE_CTX * vs, X509_LOOKUP_TYPE type, X509_NAME * name)
Definition at line 260 of file x509_lu.c.
X509_STORE_free()
void X509_STORE_free (X509_STORE * vfy)
Definition at line 190 of file x509_lu.c.
References CRYPTO_DOWN_REF, NULL, REF_ASSERT_ISNT, REF_PRINT_COUNT, STACK_OF(), X509_LOOKUP_free(), and X509_LOOKUP_shutdown().
Referenced by ssl_build_cert_chain(), ssl_cert_set_cert_store(), SSL_CTX_set_cert_store(), and TS_VERIFY_CTX_cleanup().
X509_STORE_get0_param()
X509_VERIFY_PARAM* X509_STORE_get0_param (X509_STORE * ctx)
Definition at line 712 of file x509_lu.c.
X509_STORE_get_cert_crl()
X509_STORE_CTX_cert_crl_fn X509_STORE_get_cert_crl (X509_STORE * ctx)
Definition at line 799 of file x509_lu.c.
X509_STORE_get_check_crl()
X509_STORE_CTX_check_crl_fn X509_STORE_get_check_crl (X509_STORE * ctx)
Definition at line 788 of file x509_lu.c.
X509_STORE_get_check_issued()
X509_STORE_CTX_check_issued_fn X509_STORE_get_check_issued (X509_STORE * ctx)
Definition at line 755 of file x509_lu.c.
X509_STORE_get_check_policy()
X509_STORE_CTX_check_policy_fn X509_STORE_get_check_policy (X509_STORE * ctx)
Definition at line 810 of file x509_lu.c.
X509_STORE_get_check_revocation()
X509_STORE_CTX_check_revocation_fn X509_STORE_get_check_revocation (X509_STORE * ctx)
Definition at line 766 of file x509_lu.c.
X509_STORE_get_cleanup()
X509_STORE_CTX_cleanup_fn X509_STORE_get_cleanup (X509_STORE * ctx)
Definition at line 843 of file x509_lu.c.
X509_STORE_get_ex_data()
void* X509_STORE_get_ex_data (X509_STORE * ctx, int idx)
Definition at line 853 of file x509_lu.c.
X509_STORE_get_get_crl()
X509_STORE_CTX_get_crl_fn X509_STORE_get_get_crl (X509_STORE * ctx)
Definition at line 777 of file x509_lu.c.
X509_STORE_get_get_issuer()
X509_STORE_CTX_get_issuer_fn X509_STORE_get_get_issuer (X509_STORE * ctx)
Definition at line 744 of file x509_lu.c.
X509_STORE_get_lookup_certs()
X509_STORE_CTX_lookup_certs_fn X509_STORE_get_lookup_certs (X509_STORE * ctx)
Definition at line 821 of file x509_lu.c.
X509_STORE_get_lookup_crls()
X509_STORE_CTX_lookup_crls_fn X509_STORE_get_lookup_crls (X509_STORE * ctx)
Definition at line 832 of file x509_lu.c.
X509_STORE_get_verify()
X509_STORE_CTX_verify_fn X509_STORE_get_verify (X509_STORE * ctx)
Definition at line 722 of file x509_lu.c.
X509_STORE_get_verify_cb()
X509_STORE_CTX_verify_cb X509_STORE_get_verify_cb (X509_STORE * ctx)
Definition at line 733 of file x509_lu.c.
X509_STORE_lock()
int X509_STORE_lock (X509_STORE * s)
Definition at line 43 of file x509_lu.c.
References CRYPTO_THREAD_write_lock().
X509_STORE_new()
X509_STORE* X509_STORE_new (void)
Definition at line 142 of file x509_lu.c.
Referenced by setup_verify(), ssl_build_cert_chain(), and ssl_load_stores().
X509_STORE_set1_param()
int X509_STORE_set1_param (X509_STORE * ctx, X509_VERIFY_PARAM * param)
Definition at line 707 of file x509_lu.c.
References X509_VERIFY_PARAM_set1().
X509_STORE_set_cert_crl()
void X509_STORE_set_cert_crl (X509_STORE * ctx, X509_STORE_CTX_cert_crl_fn cert_crl)
Definition at line 793 of file x509_lu.c.
X509_STORE_set_check_crl()
void X509_STORE_set_check_crl (X509_STORE * ctx, X509_STORE_CTX_check_crl_fn check_crl)
Definition at line 782 of file x509_lu.c.
X509_STORE_set_check_issued()
void X509_STORE_set_check_issued (X509_STORE * ctx, X509_STORE_CTX_check_issued_fn check_issued)
Definition at line 749 of file x509_lu.c.
X509_STORE_set_check_policy()
void X509_STORE_set_check_policy (X509_STORE * ctx, X509_STORE_CTX_check_policy_fn check_policy)
Definition at line 804 of file x509_lu.c.
X509_STORE_set_check_revocation()
void X509_STORE_set_check_revocation (X509_STORE * ctx, X509_STORE_CTX_check_revocation_fn check_revocation)
Definition at line 760 of file x509_lu.c.
X509_STORE_set_cleanup()
void X509_STORE_set_cleanup (X509_STORE * ctx, X509_STORE_CTX_cleanup_fn ctx_cleanup)
Definition at line 837 of file x509_lu.c.
X509_STORE_set_depth()
int X509_STORE_set_depth (X509_STORE * ctx, int depth)
Definition at line 691 of file x509_lu.c.
References X509_VERIFY_PARAM_set_depth().
X509_STORE_set_ex_data()
int X509_STORE_set_ex_data (X509_STORE * ctx, int idx, void * data)
Definition at line 848 of file x509_lu.c.
X509_STORE_set_flags()
int X509_STORE_set_flags (X509_STORE * ctx, unsigned long flags)
Definition at line 686 of file x509_lu.c.
References X509_VERIFY_PARAM_set_flags().
X509_STORE_set_get_crl()
void X509_STORE_set_get_crl (X509_STORE * ctx, X509_STORE_CTX_get_crl_fn get_crl)
Definition at line 771 of file x509_lu.c.
X509_STORE_set_get_issuer()
void X509_STORE_set_get_issuer (X509_STORE * ctx, X509_STORE_CTX_get_issuer_fn get_issuer)
Definition at line 738 of file x509_lu.c.
X509_STORE_set_lookup_certs()
void X509_STORE_set_lookup_certs (X509_STORE * ctx, X509_STORE_CTX_lookup_certs_fn lookup_certs)
Definition at line 815 of file x509_lu.c.
X509_STORE_set_lookup_crls()
void X509_STORE_set_lookup_crls (X509_STORE * ctx, X509_STORE_CTX_lookup_crls_fn lookup_crls)
Definition at line 826 of file x509_lu.c.
X509_STORE_set_purpose()
int X509_STORE_set_purpose (X509_STORE * ctx, int purpose)
Definition at line 697 of file x509_lu.c.
References X509_VERIFY_PARAM_set_purpose().
X509_STORE_set_trust()
int X509_STORE_set_trust (X509_STORE * ctx, int trust)
Definition at line 702 of file x509_lu.c.
References X509_VERIFY_PARAM_set_trust().
X509_STORE_set_verify()
void X509_STORE_set_verify (X509_STORE * ctx, X509_STORE_CTX_verify_fn verify)
Definition at line 717 of file x509_lu.c.
X509_STORE_set_verify_cb()
void X509_STORE_set_verify_cb (X509_STORE * ctx, X509_STORE_CTX_verify_cb verify_cb)
Definition at line 727 of file x509_lu.c.
X509_STORE_unlock()
int X509_STORE_unlock (X509_STORE * s)
Definition at line 48 of file x509_lu.c.
References CRYPTO_THREAD_unlock().
X509_STORE_up_ref()
int X509_STORE_up_ref (X509_STORE * vfy)
Definition at line 220 of file x509_lu.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by ssl_cert_set_cert_store(), and SSL_CTX_set1_cert_store().