crypto/x509/x509_att.c File Reference
x509_att.c File Reference
#include <stdio.h>
#include <openssl/stack.h>
#include "internal/cryptlib.h"
#include <openssl/asn1.h>
#include <openssl/objects.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include "x509_lcl.h"
Functions
int X509at_get_attr_count (const STACK_OF(X509_ATTRIBUTE) *x)
int X509at_get_attr_by_NID (const STACK_OF(X509_ATTRIBUTE) *x, int nid, int lastpos)
int X509at_get_attr_by_OBJ (const STACK_OF(X509_ATTRIBUTE) *sk, const ASN1_OBJECT *obj, int lastpos)
X509_ATTRIBUTE * X509at_get_attr (const STACK_OF(X509_ATTRIBUTE) *x, int loc)
X509_ATTRIBUTE * X509at_delete_attr (STACK_OF(X509_ATTRIBUTE) *x, int loc)
STACK_OF (X509_ATTRIBUTE)
void * X509at_get0_data_by_OBJ (STACK_OF(X509_ATTRIBUTE) *x, const ASN1_OBJECT *obj, int lastpos, int type)
X509_ATTRIBUTE * X509_ATTRIBUTE_create_by_NID (X509_ATTRIBUTE **attr, int nid, int atrtype, const void *data, int len)
X509_ATTRIBUTE * X509_ATTRIBUTE_create_by_OBJ (X509_ATTRIBUTE **attr, const ASN1_OBJECT *obj, int atrtype, const void *data, int len)
X509_ATTRIBUTE * X509_ATTRIBUTE_create_by_txt (X509_ATTRIBUTE **attr, const char *atrname, int type, const unsigned char *bytes, int len)
int X509_ATTRIBUTE_set1_object (X509_ATTRIBUTE *attr, const ASN1_OBJECT *obj)
int X509_ATTRIBUTE_set1_data (X509_ATTRIBUTE *attr, int attrtype, const void *data, int len)
int X509_ATTRIBUTE_count (const X509_ATTRIBUTE *attr)
ASN1_OBJECT * X509_ATTRIBUTE_get0_object (X509_ATTRIBUTE *attr)
void * X509_ATTRIBUTE_get0_data (X509_ATTRIBUTE *attr, int idx, int atrtype, void *data)
ASN1_TYPE * X509_ATTRIBUTE_get0_type (X509_ATTRIBUTE *attr, int idx)
Function Documentation
STACK_OF()
STACK_OF (X509_ATTRIBUTE)
Definition at line 73 of file x509_att.c.
References attr, bytes, ERR_R_MALLOC_FAILURE, ERR_R_PASSED_NULL_PARAMETER, len, NULL, obj, type, X509_ATTRIBUTE_dup(), X509_F_X509AT_ADD1_ATTR, and X509err.
X509_ATTRIBUTE_count()
int X509_ATTRIBUTE_count (const X509_ATTRIBUTE * attr)
Definition at line 296 of file x509_att.c.
References NULL.
Referenced by print_attribs(), X509_REQ_print_ex(), and X509at_get0_data_by_OBJ().
X509_ATTRIBUTE_create_by_NID()
X509_ATTRIBUTE* X509_ATTRIBUTE_create_by_NID (X509_ATTRIBUTE ** attr, int nid, int atrtype, const void * data, int len)
Definition at line 168 of file x509_att.c.
References obj.
X509_ATTRIBUTE_create_by_OBJ()
X509_ATTRIBUTE* X509_ATTRIBUTE_create_by_OBJ (X509_ATTRIBUTE ** attr, const ASN1_OBJECT * obj, int atrtype, const void * data, int len)
Definition at line 186 of file x509_att.c.
Referenced by X509_ATTRIBUTE_create_by_txt().
X509_ATTRIBUTE_create_by_txt()
X509_ATTRIBUTE* X509_ATTRIBUTE_create_by_txt (X509_ATTRIBUTE ** attr, const char * atrname, int type, const unsigned char * bytes, int len)
Definition at line 216 of file x509_att.c.
References ASN1_OBJECT_free(), ERR_add_error_data(), NULL, obj, OBJ_txt2obj(), X509_ATTRIBUTE_create_by_OBJ(), X509_F_X509_ATTRIBUTE_CREATE_BY_TXT, X509_R_INVALID_FIELD_NAME, and X509err.
X509_ATTRIBUTE_get0_data()
void* X509_ATTRIBUTE_get0_data (X509_ATTRIBUTE * attr, int idx, int atrtype, void * data)
Definition at line 310 of file x509_att.c.
Referenced by X509at_get0_data_by_OBJ().
X509_ATTRIBUTE_get0_object()
ASN1_OBJECT* X509_ATTRIBUTE_get0_object (X509_ATTRIBUTE * attr)
Definition at line 303 of file x509_att.c.
References NULL.
Referenced by print_attribs(), and X509_REQ_print_ex().
X509_ATTRIBUTE_get0_type()
ASN1_TYPE* X509_ATTRIBUTE_get0_type (X509_ATTRIBUTE * attr, int idx)
Definition at line 324 of file x509_att.c.
Referenced by PKCS12_get_attr_gen(), print_attribs(), and X509_REQ_print_ex().
X509_ATTRIBUTE_set1_data()
int X509_ATTRIBUTE_set1_data (X509_ATTRIBUTE * attr, int attrtype, const void * data, int len)
Definition at line 245 of file x509_att.c.
References ASN1_STRING_free(), ASN1_STRING_set(), ASN1_STRING_set_by_NID(), ASN1_STRING_type_new(), ASN1_TYPE_set(), ASN1_TYPE_set1(), ERR_R_ASN1_LIB, ERR_R_MALLOC_FAILURE, MBSTRING_FLAG, NULL, OBJ_obj2nid(), X509_F_X509_ATTRIBUTE_SET1_DATA, and X509err.
X509_ATTRIBUTE_set1_object()
int X509_ATTRIBUTE_set1_object (X509_ATTRIBUTE * attr, const ASN1_OBJECT * obj)
Definition at line 236 of file x509_att.c.
References ASN1_OBJECT_free(), NULL, and OBJ_dup().
X509at_delete_attr()
X509_ATTRIBUTE* X509at_delete_attr (STACK_OF(X509_ATTRIBUTE) * x, int loc)
Definition at line 63 of file x509_att.c.
Referenced by CMS_signed_delete_attr(), CMS_unsigned_delete_attr(), EVP_PKEY_delete_attr(), and X509_REQ_delete_attr().
X509at_get0_data_by_OBJ()
void* X509at_get0_data_by_OBJ (STACK_OF(X509_ATTRIBUTE) * x, const ASN1_OBJECT * obj, int lastpos, int type)
Definition at line 152 of file x509_att.c.
References NULL, X509_ATTRIBUTE_count(), X509_ATTRIBUTE_get0_data(), X509at_get_attr(), and X509at_get_attr_by_OBJ().
Referenced by CMS_signed_get0_data_by_OBJ(), and CMS_unsigned_get0_data_by_OBJ().
X509at_get_attr()
X509_ATTRIBUTE* X509at_get_attr (const STACK_OF(X509_ATTRIBUTE) * x, int loc)
Definition at line 55 of file x509_att.c.
References NULL.
Referenced by CMS_signed_get_attr(), CMS_unsigned_get_attr(), EVP_PKEY_get_attr(), PKCS12_get_attr_gen(), X509_REQ_get_attr(), and X509at_get0_data_by_OBJ().
X509at_get_attr_by_NID()
int X509at_get_attr_by_NID (const STACK_OF(X509_ATTRIBUTE) * x, int nid, int lastpos)
Definition at line 25 of file x509_att.c.
References NULL, obj, OBJ_nid2obj(), and X509at_get_attr_by_OBJ().
Referenced by CMS_signed_get_attr_by_NID(), CMS_unsigned_get_attr_by_NID(), EVP_PKEY_get_attr_by_NID(), PKCS12_get_attr_gen(), and X509_REQ_get_attr_by_NID().
X509at_get_attr_by_OBJ()
int X509at_get_attr_by_OBJ (const STACK_OF(X509_ATTRIBUTE) * sk, const ASN1_OBJECT * obj, int lastpos)
Definition at line 35 of file x509_att.c.
References ex, NULL, and OBJ_cmp().
Referenced by CMS_signed_get_attr_by_OBJ(), CMS_unsigned_get_attr_by_OBJ(), EVP_PKEY_get_attr_by_OBJ(), X509_REQ_get_attr_by_OBJ(), X509at_get0_data_by_OBJ(), and X509at_get_attr_by_NID().
X509at_get_attr_count()
int X509at_get_attr_count (const STACK_OF(X509_ATTRIBUTE) * x)
Definition at line 20 of file x509_att.c.
Referenced by CMS_signed_get_attr_count(), CMS_unsigned_get_attr_count(), EVP_PKEY_get_attr_count(), and X509_REQ_get_attr_count().