include/openssl/x509.h File Reference
x509.h File Reference
#include <openssl/e_os2.h>
#include <openssl/ossl_typ.h>
#include <openssl/symhacks.h>
#include <openssl/buffer.h>
#include <openssl/evp.h>
#include <openssl/bio.h>
#include <openssl/stack.h>
#include <openssl/asn1.h>
#include <openssl/safestack.h>
#include <openssl/ec.h>
#include <openssl/rsa.h>
#include <openssl/dsa.h>
#include <openssl/dh.h>
#include <openssl/sha.h>
#include <openssl/x509_vfy.h>
#include <openssl/pkcs7.h>
Data Structures
struct X509_ALGOR
struct X509_VAL
struct X509_TRUST
struct X509_PKEY
struct X509_INFO
struct NETSCAPE_SPKAC
struct NETSCAPE_SPKI
struct NETSCAPE_CERT_SEQUENCE
struct PBEPARAM
struct PBE2PARAM
struct PBKDF2PARAM
Macros
#define X509_FILETYPE_PEM 1
#define X509_FILETYPE_ASN1 2
#define X509_FILETYPE_DEFAULT 3
#define X509v3_KU_DIGITAL_SIGNATURE 0x0080
#define X509v3_KU_NON_REPUDIATION 0x0040
#define X509v3_KU_KEY_ENCIPHERMENT 0x0020
#define X509v3_KU_DATA_ENCIPHERMENT 0x0010
#define X509v3_KU_KEY_AGREEMENT 0x0008
#define X509v3_KU_KEY_CERT_SIGN 0x0004
#define X509v3_KU_CRL_SIGN 0x0002
#define X509v3_KU_ENCIPHER_ONLY 0x0001
#define X509v3_KU_DECIPHER_ONLY 0x8000
#define X509v3_KU_UNDEF 0xffff
#define X509_EX_V_NETSCAPE_HACK 0x8000
#define X509_EX_V_INIT 0x0001
#define X509_TRUST_DEFAULT 0 /* Only valid in purpose settings */
#define X509_TRUST_COMPAT 1
#define X509_TRUST_SSL_CLIENT 2
#define X509_TRUST_SSL_SERVER 3
#define X509_TRUST_EMAIL 4
#define X509_TRUST_OBJECT_SIGN 5
#define X509_TRUST_OCSP_SIGN 6
#define X509_TRUST_OCSP_REQUEST 7
#define X509_TRUST_TSA 8
#define X509_TRUST_MIN 1
#define X509_TRUST_MAX 8
#define X509_TRUST_DYNAMIC (1U << 0)
#define X509_TRUST_DYNAMIC_NAME (1U << 1)
#define X509_TRUST_NO_SS_COMPAT (1U << 2)
#define X509_TRUST_DO_SS_COMPAT (1U << 3)
#define X509_TRUST_OK_ANY_EKU (1U << 4)
#define X509_TRUST_TRUSTED 1
#define X509_TRUST_REJECTED 2
#define X509_TRUST_UNTRUSTED 3
#define X509_FLAG_COMPAT 0
#define X509_FLAG_NO_HEADER 1L
#define X509_FLAG_NO_VERSION (1L << 1)
#define X509_FLAG_NO_SERIAL (1L << 2)
#define X509_FLAG_NO_SIGNAME (1L << 3)
#define X509_FLAG_NO_ISSUER (1L << 4)
#define X509_FLAG_NO_VALIDITY (1L << 5)
#define X509_FLAG_NO_SUBJECT (1L << 6)
#define X509_FLAG_NO_PUBKEY (1L << 7)
#define X509_FLAG_NO_EXTENSIONS (1L << 8)
#define X509_FLAG_NO_SIGDUMP (1L << 9)
#define X509_FLAG_NO_AUX (1L << 10)
#define X509_FLAG_NO_ATTRIBUTES (1L << 11)
#define X509_FLAG_NO_IDS (1L << 12)
#define XN_FLAG_SEP_MASK (0xf << 16)
#define XN_FLAG_COMPAT 0/* Traditional; use old X509_NAME_print */
#define XN_FLAG_SEP_COMMA_PLUS (1 << 16)/* RFC2253 ,+ */
#define XN_FLAG_SEP_CPLUS_SPC (2 << 16)/* ,+ spaced: more readable */
#define XN_FLAG_SEP_SPLUS_SPC (3 << 16)/* ;+ spaced */
#define XN_FLAG_SEP_MULTILINE (4 << 16)/* One line per field */
#define XN_FLAG_DN_REV (1 << 20)/* Reverse DN order */
#define XN_FLAG_FN_MASK (0x3 << 21)
#define XN_FLAG_FN_SN 0/* Object short name */
#define XN_FLAG_FN_LN (1 << 21)/* Object long name */
#define XN_FLAG_FN_OID (2 << 21)/* Always use OIDs */
#define XN_FLAG_FN_NONE (3 << 21)/* No field names */
#define XN_FLAG_SPC_EQ (1 << 23)/* Put spaces round '=' */
#define XN_FLAG_DUMP_UNKNOWN_FIELDS (1 << 24)
#define XN_FLAG_FN_ALIGN
#define XN_FLAG_RFC2253
#define XN_FLAG_ONELINE
#define XN_FLAG_MULTILINE
#define X509_EXT_PACK_UNKNOWN 1
#define X509_EXT_PACK_STRING 2
#define X509_extract_key(x) X509_get_pubkey(x)/*****/
#define X509_REQ_extract_key(a) X509_REQ_get_pubkey(a)
#define X509_name_cmp(a, b) X509_NAME_cmp((a),(b))
#define X509_get_ex_new_index(l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_X509, l, p, newf, dupf, freef)
#define X509_get_notBefore X509_getm_notBefore
#define X509_get_notAfter X509_getm_notAfter
#define X509_set_notBefore X509_set1_notBefore
#define X509_set_notAfter X509_set1_notAfter
#define X509_CRL_set_lastUpdate X509_CRL_set1_lastUpdate
#define X509_CRL_set_nextUpdate X509_CRL_set1_nextUpdate
#define X509_F_ADD_CERT_DIR 100
#define X509_F_BUILD_CHAIN 106
#define X509_F_BY_FILE_CTRL 101
#define X509_F_CHECK_NAME_CONSTRAINTS 149
#define X509_F_CHECK_POLICY 145
#define X509_F_DANE_I2D 107
#define X509_F_DIR_CTRL 102
#define X509_F_GET_CERT_BY_SUBJECT 103
#define X509_F_NETSCAPE_SPKI_B64_DECODE 129
#define X509_F_NETSCAPE_SPKI_B64_ENCODE 130
#define X509_F_X509AT_ADD1_ATTR 135
#define X509_F_X509V3_ADD_EXT 104
#define X509_F_X509_ATTRIBUTE_CREATE_BY_NID 136
#define X509_F_X509_ATTRIBUTE_CREATE_BY_OBJ 137
#define X509_F_X509_ATTRIBUTE_CREATE_BY_TXT 140
#define X509_F_X509_ATTRIBUTE_GET0_DATA 139
#define X509_F_X509_ATTRIBUTE_SET1_DATA 138
#define X509_F_X509_CHECK_PRIVATE_KEY 128
#define X509_F_X509_CRL_DIFF 105
#define X509_F_X509_CRL_PRINT_FP 147
#define X509_F_X509_EXTENSION_CREATE_BY_NID 108
#define X509_F_X509_EXTENSION_CREATE_BY_OBJ 109
#define X509_F_X509_GET_PUBKEY_PARAMETERS 110
#define X509_F_X509_LOAD_CERT_CRL_FILE 132
#define X509_F_X509_LOAD_CERT_FILE 111
#define X509_F_X509_LOAD_CRL_FILE 112
#define X509_F_X509_NAME_ADD_ENTRY 113
#define X509_F_X509_NAME_ENTRY_CREATE_BY_NID 114
#define X509_F_X509_NAME_ENTRY_CREATE_BY_TXT 131
#define X509_F_X509_NAME_ENTRY_SET_OBJECT 115
#define X509_F_X509_NAME_ONELINE 116
#define X509_F_X509_NAME_PRINT 117
#define X509_F_X509_OBJECT_NEW 150
#define X509_F_X509_PRINT_EX_FP 118
#define X509_F_X509_PUBKEY_DECODE 148
#define X509_F_X509_PUBKEY_GET0 119
#define X509_F_X509_PUBKEY_SET 120
#define X509_F_X509_REQ_CHECK_PRIVATE_KEY 144
#define X509_F_X509_REQ_PRINT_EX 121
#define X509_F_X509_REQ_PRINT_FP 122
#define X509_F_X509_REQ_TO_X509 123
#define X509_F_X509_STORE_ADD_CERT 124
#define X509_F_X509_STORE_ADD_CRL 125
#define X509_F_X509_STORE_CTX_GET1_ISSUER 146
#define X509_F_X509_STORE_CTX_INIT 143
#define X509_F_X509_STORE_CTX_NEW 142
#define X509_F_X509_STORE_CTX_PURPOSE_INHERIT 134
#define X509_F_X509_TO_X509_REQ 126
#define X509_F_X509_TRUST_ADD 133
#define X509_F_X509_TRUST_SET 141
#define X509_F_X509_VERIFY_CERT 127
#define X509_R_AKID_MISMATCH 110
#define X509_R_BAD_SELECTOR 133
#define X509_R_BAD_X509_FILETYPE 100
#define X509_R_BASE64_DECODE_ERROR 118
#define X509_R_CANT_CHECK_DH_KEY 114
#define X509_R_CERT_ALREADY_IN_HASH_TABLE 101
#define X509_R_CRL_ALREADY_DELTA 127
#define X509_R_CRL_VERIFY_FAILURE 131
#define X509_R_IDP_MISMATCH 128
#define X509_R_INVALID_DIRECTORY 113
#define X509_R_INVALID_FIELD_NAME 119
#define X509_R_INVALID_TRUST 123
#define X509_R_ISSUER_MISMATCH 129
#define X509_R_KEY_TYPE_MISMATCH 115
#define X509_R_KEY_VALUES_MISMATCH 116
#define X509_R_LOADING_CERT_DIR 103
#define X509_R_LOADING_DEFAULTS 104
#define X509_R_METHOD_NOT_SUPPORTED 124
#define X509_R_NAME_TOO_LONG 134
#define X509_R_NEWER_CRL_NOT_NEWER 132
#define X509_R_NO_CERT_SET_FOR_US_TO_VERIFY 105
#define X509_R_NO_CRL_NUMBER 130
#define X509_R_PUBLIC_KEY_DECODE_ERROR 125
#define X509_R_PUBLIC_KEY_ENCODE_ERROR 126
#define X509_R_SHOULD_RETRY 106
#define X509_R_UNABLE_TO_FIND_PARAMETERS_IN_CHAIN 107
#define X509_R_UNABLE_TO_GET_CERTS_PUBLIC_KEY 108
#define X509_R_UNKNOWN_KEY_TYPE 117
#define X509_R_UNKNOWN_NID 109
#define X509_R_UNKNOWN_PURPOSE_ID 121
#define X509_R_UNKNOWN_TRUST_ID 120
#define X509_R_UNSUPPORTED_ALGORITHM 111
#define X509_R_WRONG_LOOKUP_TYPE 112
#define X509_R_WRONG_TYPE 122
Functions
typedef STACK_OF (X509_ALGOR) X509_ALGORS
typedef STACK_OF (X509_EXTENSION) X509_EXTENSIONS
void X509_CRL_set_default_method (const X509_CRL_METHOD *meth)
X509_CRL_METHOD * X509_CRL_METHOD_new (int(*crl_init)(X509_CRL *crl), int(*crl_free)(X509_CRL *crl), int(*crl_lookup)(X509_CRL *crl, X509_REVOKED **ret, ASN1_INTEGER *ser, X509_NAME *issuer), int(*crl_verify)(X509_CRL *crl, EVP_PKEY *pk))
void X509_CRL_METHOD_free (X509_CRL_METHOD *m)
void X509_CRL_set_meth_data (X509_CRL *crl, void *dat)
void * X509_CRL_get_meth_data (X509_CRL *crl)
const char * X509_verify_cert_error_string (long n)
int X509_verify (X509 *a, EVP_PKEY *r)
int X509_REQ_verify (X509_REQ *a, EVP_PKEY *r)
int X509_CRL_verify (X509_CRL *a, EVP_PKEY *r)
int NETSCAPE_SPKI_verify (NETSCAPE_SPKI *a, EVP_PKEY *r)
NETSCAPE_SPKI * NETSCAPE_SPKI_b64_decode (const char *str, int len)
char * NETSCAPE_SPKI_b64_encode (NETSCAPE_SPKI *x)
EVP_PKEY * NETSCAPE_SPKI_get_pubkey (NETSCAPE_SPKI *x)
int NETSCAPE_SPKI_set_pubkey (NETSCAPE_SPKI *x, EVP_PKEY *pkey)
int NETSCAPE_SPKI_print (BIO *out, NETSCAPE_SPKI *spki)
int X509_signature_dump (BIO *bp, const ASN1_STRING *sig, int indent)
int X509_signature_print (BIO *bp, const X509_ALGOR *alg, const ASN1_STRING *sig)
int X509_sign (X509 *x, EVP_PKEY *pkey, const EVP_MD *md)
int X509_sign_ctx (X509 *x, EVP_MD_CTX *ctx)
int X509_http_nbio (OCSP_REQ_CTX *rctx, X509 **pcert)
int X509_REQ_sign (X509_REQ *x, EVP_PKEY *pkey, const EVP_MD *md)
int X509_REQ_sign_ctx (X509_REQ *x, EVP_MD_CTX *ctx)
int X509_CRL_sign (X509_CRL *x, EVP_PKEY *pkey, const EVP_MD *md)
int X509_CRL_sign_ctx (X509_CRL *x, EVP_MD_CTX *ctx)
int X509_CRL_http_nbio (OCSP_REQ_CTX *rctx, X509_CRL **pcrl)
int NETSCAPE_SPKI_sign (NETSCAPE_SPKI *x, EVP_PKEY *pkey, const EVP_MD *md)
int X509_pubkey_digest (const X509 *data, const EVP_MD *type, unsigned char *md, unsigned int *len)
int X509_digest (const X509 *data, const EVP_MD *type, unsigned char *md, unsigned int *len)
int X509_CRL_digest (const X509_CRL *data, const EVP_MD *type, unsigned char *md, unsigned int *len)
int X509_REQ_digest (const X509_REQ *data, const EVP_MD *type, unsigned char *md, unsigned int *len)
int X509_NAME_digest (const X509_NAME *data, const EVP_MD *type, unsigned char *md, unsigned int *len)
X509 * d2i_X509_fp (FILE *fp, X509 **x509)
int i2d_X509_fp (FILE *fp, X509 *x509)
X509_CRL * d2i_X509_CRL_fp (FILE *fp, X509_CRL **crl)
int i2d_X509_CRL_fp (FILE *fp, X509_CRL *crl)
X509_REQ * d2i_X509_REQ_fp (FILE *fp, X509_REQ **req)
int i2d_X509_REQ_fp (FILE *fp, X509_REQ *req)
RSA * d2i_RSAPrivateKey_fp (FILE *fp, RSA **rsa)
int i2d_RSAPrivateKey_fp (FILE *fp, RSA *rsa)
RSA * d2i_RSAPublicKey_fp (FILE *fp, RSA **rsa)
int i2d_RSAPublicKey_fp (FILE *fp, RSA *rsa)
RSA * d2i_RSA_PUBKEY_fp (FILE *fp, RSA **rsa)
int i2d_RSA_PUBKEY_fp (FILE *fp, RSA *rsa)
DSA * d2i_DSA_PUBKEY_fp (FILE *fp, DSA **dsa)
int i2d_DSA_PUBKEY_fp (FILE *fp, DSA *dsa)
DSA * d2i_DSAPrivateKey_fp (FILE *fp, DSA **dsa)
int i2d_DSAPrivateKey_fp (FILE *fp, DSA *dsa)
EC_KEY * d2i_EC_PUBKEY_fp (FILE *fp, EC_KEY **eckey)
int i2d_EC_PUBKEY_fp (FILE *fp, EC_KEY *eckey)
EC_KEY * d2i_ECPrivateKey_fp (FILE *fp, EC_KEY **eckey)
int i2d_ECPrivateKey_fp (FILE *fp, EC_KEY *eckey)
X509_SIG * d2i_PKCS8_fp (FILE *fp, X509_SIG **p8)
int i2d_PKCS8_fp (FILE *fp, X509_SIG *p8)
PKCS8_PRIV_KEY_INFO * d2i_PKCS8_PRIV_KEY_INFO_fp (FILE *fp, PKCS8_PRIV_KEY_INFO **p8inf)
int i2d_PKCS8_PRIV_KEY_INFO_fp (FILE *fp, PKCS8_PRIV_KEY_INFO *p8inf)
int i2d_PKCS8PrivateKeyInfo_fp (FILE *fp, EVP_PKEY *key)
int i2d_PrivateKey_fp (FILE *fp, EVP_PKEY *pkey)
EVP_PKEY * d2i_PrivateKey_fp (FILE *fp, EVP_PKEY **a)
int i2d_PUBKEY_fp (FILE *fp, EVP_PKEY *pkey)
EVP_PKEY * d2i_PUBKEY_fp (FILE *fp, EVP_PKEY **a)
X509 * d2i_X509_bio (BIO *bp, X509 **x509)
int i2d_X509_bio (BIO *bp, X509 *x509)
X509_CRL * d2i_X509_CRL_bio (BIO *bp, X509_CRL **crl)
int i2d_X509_CRL_bio (BIO *bp, X509_CRL *crl)
X509_REQ * d2i_X509_REQ_bio (BIO *bp, X509_REQ **req)
int i2d_X509_REQ_bio (BIO *bp, X509_REQ *req)
RSA * d2i_RSAPrivateKey_bio (BIO *bp, RSA **rsa)
int i2d_RSAPrivateKey_bio (BIO *bp, RSA *rsa)
RSA * d2i_RSAPublicKey_bio (BIO *bp, RSA **rsa)
int i2d_RSAPublicKey_bio (BIO *bp, RSA *rsa)
RSA * d2i_RSA_PUBKEY_bio (BIO *bp, RSA **rsa)
int i2d_RSA_PUBKEY_bio (BIO *bp, RSA *rsa)
DSA * d2i_DSA_PUBKEY_bio (BIO *bp, DSA **dsa)
int i2d_DSA_PUBKEY_bio (BIO *bp, DSA *dsa)
DSA * d2i_DSAPrivateKey_bio (BIO *bp, DSA **dsa)
int i2d_DSAPrivateKey_bio (BIO *bp, DSA *dsa)
EC_KEY * d2i_EC_PUBKEY_bio (BIO *bp, EC_KEY **eckey)
int i2d_EC_PUBKEY_bio (BIO *bp, EC_KEY *eckey)
EC_KEY * d2i_ECPrivateKey_bio (BIO *bp, EC_KEY **eckey)
int i2d_ECPrivateKey_bio (BIO *bp, EC_KEY *eckey)
X509_SIG * d2i_PKCS8_bio (BIO *bp, X509_SIG **p8)
int i2d_PKCS8_bio (BIO *bp, X509_SIG *p8)
PKCS8_PRIV_KEY_INFO * d2i_PKCS8_PRIV_KEY_INFO_bio (BIO *bp, PKCS8_PRIV_KEY_INFO **p8inf)
int i2d_PKCS8_PRIV_KEY_INFO_bio (BIO *bp, PKCS8_PRIV_KEY_INFO *p8inf)
int i2d_PKCS8PrivateKeyInfo_bio (BIO *bp, EVP_PKEY *key)
int i2d_PrivateKey_bio (BIO *bp, EVP_PKEY *pkey)
EVP_PKEY * d2i_PrivateKey_bio (BIO *bp, EVP_PKEY **a)
int i2d_PUBKEY_bio (BIO *bp, EVP_PKEY *pkey)
EVP_PKEY * d2i_PUBKEY_bio (BIO *bp, EVP_PKEY **a)
X509 * X509_dup (X509 *x509)
X509_ATTRIBUTE * X509_ATTRIBUTE_dup (X509_ATTRIBUTE *xa)
X509_EXTENSION * X509_EXTENSION_dup (X509_EXTENSION *ex)
X509_CRL * X509_CRL_dup (X509_CRL *crl)
X509_REVOKED * X509_REVOKED_dup (X509_REVOKED *rev)
X509_REQ * X509_REQ_dup (X509_REQ *req)
X509_ALGOR * X509_ALGOR_dup (X509_ALGOR *xn)
int X509_ALGOR_set0 (X509_ALGOR *alg, ASN1_OBJECT *aobj, int ptype, void *pval)
void X509_ALGOR_get0 (const ASN1_OBJECT **paobj, int *pptype, const void **ppval, const X509_ALGOR *algor)
void X509_ALGOR_set_md (X509_ALGOR *alg, const EVP_MD *md)
int X509_ALGOR_cmp (const X509_ALGOR *a, const X509_ALGOR *b)
X509_NAME * X509_NAME_dup (X509_NAME *xn)
X509_NAME_ENTRY * X509_NAME_ENTRY_dup (X509_NAME_ENTRY *ne)
int X509_cmp_time (const ASN1_TIME *s, time_t *t)
int X509_cmp_current_time (const ASN1_TIME *s)
ASN1_TIME * X509_time_adj (ASN1_TIME *s, long adj, time_t *t)
ASN1_TIME * X509_time_adj_ex (ASN1_TIME *s, int offset_day, long offset_sec, time_t *t)
ASN1_TIME * X509_gmtime_adj (ASN1_TIME *s, long adj)
const char * X509_get_default_cert_area (void)
const char * X509_get_default_cert_dir (void)
const char * X509_get_default_cert_file (void)
const char * X509_get_default_cert_dir_env (void)
const char * X509_get_default_cert_file_env (void)
const char * X509_get_default_private_dir (void)
X509_REQ * X509_to_X509_REQ (X509 *x, EVP_PKEY *pkey, const EVP_MD *md)
X509 * X509_REQ_to_X509 (X509_REQ *r, int days, EVP_PKEY *pkey)
int X509_PUBKEY_set (X509_PUBKEY **x, EVP_PKEY *pkey)
EVP_PKEY * X509_PUBKEY_get0 (X509_PUBKEY *key)
EVP_PKEY * X509_PUBKEY_get (X509_PUBKEY *key)
int X509_get_pubkey_parameters (EVP_PKEY *pkey, STACK_OF(X509) *chain)
long X509_get_pathlen (X509 *x)
int i2d_PUBKEY (EVP_PKEY *a, unsigned char **pp)
EVP_PKEY * d2i_PUBKEY (EVP_PKEY **a, const unsigned char **pp, long length)
int i2d_RSA_PUBKEY (RSA *a, unsigned char **pp)
RSA * d2i_RSA_PUBKEY (RSA **a, const unsigned char **pp, long length)
int i2d_DSA_PUBKEY (DSA *a, unsigned char **pp)
DSA * d2i_DSA_PUBKEY (DSA **a, const unsigned char **pp, long length)
int i2d_EC_PUBKEY (EC_KEY *a, unsigned char **pp)
EC_KEY * d2i_EC_PUBKEY (EC_KEY **a, const unsigned char **pp, long length)
void X509_SIG_get0 (const X509_SIG *sig, const X509_ALGOR **palg, const ASN1_OCTET_STRING **pdigest)
void X509_SIG_getm (X509_SIG *sig, X509_ALGOR **palg, ASN1_OCTET_STRING **pdigest)
X509_ATTRIBUTE * X509_ATTRIBUTE_create (int nid, int atrtype, void *value)
int X509_NAME_set (X509_NAME **xn, X509_NAME *name)
int X509_set_ex_data (X509 *r, int idx, void *arg)
void * X509_get_ex_data (X509 *r, int idx)
int i2d_X509_AUX (X509 *a, unsigned char **pp)
X509 * d2i_X509_AUX (X509 **a, const unsigned char **pp, long length)
int i2d_re_X509_tbs (X509 *x, unsigned char **pp)
void X509_get0_signature (const ASN1_BIT_STRING **psig, const X509_ALGOR **palg, const X509 *x)
int X509_get_signature_nid (const X509 *x)
int X509_trusted (const X509 *x)
int X509_alias_set1 (X509 *x, const unsigned char *name, int len)
int X509_keyid_set1 (X509 *x, const unsigned char *id, int len)
unsigned char * X509_alias_get0 (X509 *x, int *len)
unsigned char * X509_keyid_get0 (X509 *x, int *len)
int X509_TRUST_set (int *t, int trust)
int X509_add1_trust_object (X509 *x, const ASN1_OBJECT *obj)
int X509_add1_reject_object (X509 *x, const ASN1_OBJECT *obj)
void X509_trust_clear (X509 *x)
void X509_reject_clear (X509 *x)
STACK_OF (ASN1_OBJECT) *X509_get0_trust_objects(X509 *x)
int X509_CRL_add0_revoked (X509_CRL *crl, X509_REVOKED *rev)
int X509_CRL_get0_by_serial (X509_CRL *crl, X509_REVOKED **ret, ASN1_INTEGER *serial)
int X509_CRL_get0_by_cert (X509_CRL *crl, X509_REVOKED **ret, X509 *x)
X509_PKEY * X509_PKEY_new (void)
void X509_PKEY_free (X509_PKEY *a)
X509_INFO * X509_INFO_new (void)
void X509_INFO_free (X509_INFO *a)
char * X509_NAME_oneline (const X509_NAME *a, char *buf, int size)
int ASN1_verify (i2d_of_void *i2d, X509_ALGOR *algor1, ASN1_BIT_STRING *signature, char *data, EVP_PKEY *pkey)
int ASN1_digest (i2d_of_void *i2d, const EVP_MD *type, char *data, unsigned char *md, unsigned int *len)
int ASN1_sign (i2d_of_void *i2d, X509_ALGOR *algor1, X509_ALGOR *algor2, ASN1_BIT_STRING *signature, char *data, EVP_PKEY *pkey, const EVP_MD *type)
int ASN1_item_digest (const ASN1_ITEM *it, const EVP_MD *type, void *data, unsigned char *md, unsigned int *len)
int ASN1_item_verify (const ASN1_ITEM *it, X509_ALGOR *algor1, ASN1_BIT_STRING *signature, void *data, EVP_PKEY *pkey)
int ASN1_item_sign (const ASN1_ITEM *it, X509_ALGOR *algor1, X509_ALGOR *algor2, ASN1_BIT_STRING *signature, void *data, EVP_PKEY *pkey, const EVP_MD *type)
int ASN1_item_sign_ctx (const ASN1_ITEM *it, X509_ALGOR *algor1, X509_ALGOR *algor2, ASN1_BIT_STRING *signature, void *asn, EVP_MD_CTX *ctx)
long X509_get_version (const X509 *x)
int X509_set_version (X509 *x, long version)
int X509_set_serialNumber (X509 *x, ASN1_INTEGER *serial)
ASN1_INTEGER * X509_get_serialNumber (X509 *x)
const ASN1_INTEGER * X509_get0_serialNumber (const X509 *x)
int X509_set_issuer_name (X509 *x, X509_NAME *name)
X509_NAME * X509_get_issuer_name (const X509 *a)
int X509_set_subject_name (X509 *x, X509_NAME *name)
X509_NAME * X509_get_subject_name (const X509 *a)
const ASN1_TIME * X509_get0_notBefore (const X509 *x)
ASN1_TIME * X509_getm_notBefore (const X509 *x)
int X509_set1_notBefore (X509 *x, const ASN1_TIME *tm)
const ASN1_TIME * X509_get0_notAfter (const X509 *x)
ASN1_TIME * X509_getm_notAfter (const X509 *x)
int X509_set1_notAfter (X509 *x, const ASN1_TIME *tm)
int X509_set_pubkey (X509 *x, EVP_PKEY *pkey)
int X509_up_ref (X509 *x)
int X509_get_signature_type (const X509 *x)
X509_PUBKEY * X509_get_X509_PUBKEY (const X509 *x)
void X509_get0_uids (const X509 *x, const ASN1_BIT_STRING **piuid, const ASN1_BIT_STRING **psuid)
const X509_ALGOR * X509_get0_tbs_sigalg (const X509 *x)
EVP_PKEY * X509_get0_pubkey (const X509 *x)
EVP_PKEY * X509_get_pubkey (X509 *x)
ASN1_BIT_STRING * X509_get0_pubkey_bitstr (const X509 *x)
int X509_certificate_type (const X509 *x, const EVP_PKEY *pubkey)
long X509_REQ_get_version (const X509_REQ *req)
int X509_REQ_set_version (X509_REQ *x, long version)
X509_NAME * X509_REQ_get_subject_name (const X509_REQ *req)
int X509_REQ_set_subject_name (X509_REQ *req, X509_NAME *name)
void X509_REQ_get0_signature (const X509_REQ *req, const ASN1_BIT_STRING **psig, const X509_ALGOR **palg)
int X509_REQ_get_signature_nid (const X509_REQ *req)
int i2d_re_X509_REQ_tbs (X509_REQ *req, unsigned char **pp)
int X509_REQ_set_pubkey (X509_REQ *x, EVP_PKEY *pkey)
EVP_PKEY * X509_REQ_get_pubkey (X509_REQ *req)
EVP_PKEY * X509_REQ_get0_pubkey (X509_REQ *req)
X509_PUBKEY * X509_REQ_get_X509_PUBKEY (X509_REQ *req)
int X509_REQ_extension_nid (int nid)
int * X509_REQ_get_extension_nids (void)
void X509_REQ_set_extension_nids (int *nids)
int X509_REQ_add_extensions_nid (X509_REQ *req, STACK_OF(X509_EXTENSION) *exts, int nid)
int X509_REQ_add_extensions (X509_REQ *req, STACK_OF(X509_EXTENSION) *exts)
int X509_REQ_get_attr_count (const X509_REQ *req)
int X509_REQ_get_attr_by_NID (const X509_REQ *req, int nid, int lastpos)
int X509_REQ_get_attr_by_OBJ (const X509_REQ *req, const ASN1_OBJECT *obj, int lastpos)
X509_ATTRIBUTE * X509_REQ_get_attr (const X509_REQ *req, int loc)
X509_ATTRIBUTE * X509_REQ_delete_attr (X509_REQ *req, int loc)
int X509_REQ_add1_attr (X509_REQ *req, X509_ATTRIBUTE *attr)
int X509_REQ_add1_attr_by_OBJ (X509_REQ *req, const ASN1_OBJECT *obj, int type, const unsigned char *bytes, int len)
int X509_REQ_add1_attr_by_NID (X509_REQ *req, int nid, int type, const unsigned char *bytes, int len)
int X509_REQ_add1_attr_by_txt (X509_REQ *req, const char *attrname, int type, const unsigned char *bytes, int len)
int X509_CRL_set_version (X509_CRL *x, long version)
int X509_CRL_set_issuer_name (X509_CRL *x, X509_NAME *name)
int X509_CRL_set1_lastUpdate (X509_CRL *x, const ASN1_TIME *tm)
int X509_CRL_set1_nextUpdate (X509_CRL *x, const ASN1_TIME *tm)
int X509_CRL_sort (X509_CRL *crl)
int X509_CRL_up_ref (X509_CRL *crl)
long X509_CRL_get_version (const X509_CRL *crl)
const ASN1_TIME * X509_CRL_get0_lastUpdate (const X509_CRL *crl)
const ASN1_TIME * X509_CRL_get0_nextUpdate (const X509_CRL *crl)
X509_NAME * X509_CRL_get_issuer (const X509_CRL *crl)
STACK_OF (X509_REVOKED) *X509_CRL_get_REVOKED(X509_CRL *crl)
void X509_CRL_get0_signature (const X509_CRL *crl, const ASN1_BIT_STRING **psig, const X509_ALGOR **palg)
int X509_CRL_get_signature_nid (const X509_CRL *crl)
int i2d_re_X509_CRL_tbs (X509_CRL *req, unsigned char **pp)
const ASN1_INTEGER * X509_REVOKED_get0_serialNumber (const X509_REVOKED *x)
int X509_REVOKED_set_serialNumber (X509_REVOKED *x, ASN1_INTEGER *serial)
const ASN1_TIME * X509_REVOKED_get0_revocationDate (const X509_REVOKED *x)
int X509_REVOKED_set_revocationDate (X509_REVOKED *r, ASN1_TIME *tm)
X509_CRL * X509_CRL_diff (X509_CRL *base, X509_CRL *newer, EVP_PKEY *skey, const EVP_MD *md, unsigned int flags)
int X509_REQ_check_private_key (X509_REQ *x509, EVP_PKEY *pkey)
int X509_check_private_key (const X509 *x509, const EVP_PKEY *pkey)
int X509_chain_check_suiteb (int *perror_depth, X509 *x, STACK_OF(X509) *chain, unsigned long flags)
int X509_CRL_check_suiteb (X509_CRL *crl, EVP_PKEY *pk, unsigned long flags)
STACK_OF (X509) *X509_chain_up_ref(STACK_OF(X509) *chain)
int X509_issuer_and_serial_cmp (const X509 *a, const X509 *b)
unsigned long X509_issuer_and_serial_hash (X509 *a)
int X509_issuer_name_cmp (const X509 *a, const X509 *b)
unsigned long X509_issuer_name_hash (X509 *a)
int X509_subject_name_cmp (const X509 *a, const X509 *b)
unsigned long X509_subject_name_hash (X509 *x)
unsigned long X509_issuer_name_hash_old (X509 *a)
unsigned long X509_subject_name_hash_old (X509 *x)
int X509_cmp (const X509 *a, const X509 *b)
int X509_NAME_cmp (const X509_NAME *a, const X509_NAME *b)
unsigned long X509_NAME_hash (X509_NAME *x)
unsigned long X509_NAME_hash_old (X509_NAME *x)
int X509_CRL_cmp (const X509_CRL *a, const X509_CRL *b)
int X509_CRL_match (const X509_CRL *a, const X509_CRL *b)
int X509_aux_print (BIO *out, X509 *x, int indent)
int X509_print_ex_fp (FILE *bp, X509 *x, unsigned long nmflag, unsigned long cflag)
int X509_print_fp (FILE *bp, X509 *x)
int X509_CRL_print_fp (FILE *bp, X509_CRL *x)
int X509_REQ_print_fp (FILE *bp, X509_REQ *req)
int X509_NAME_print_ex_fp (FILE *fp, const X509_NAME *nm, int indent, unsigned long flags)
int X509_NAME_print (BIO *bp, const X509_NAME *name, int obase)
int X509_NAME_print_ex (BIO *out, const X509_NAME *nm, int indent, unsigned long flags)
int X509_print_ex (BIO *bp, X509 *x, unsigned long nmflag, unsigned long cflag)
int X509_print (BIO *bp, X509 *x)
int X509_ocspid_print (BIO *bp, X509 *x)
int X509_CRL_print (BIO *bp, X509_CRL *x)
int X509_REQ_print_ex (BIO *bp, X509_REQ *x, unsigned long nmflag, unsigned long cflag)
int X509_REQ_print (BIO *bp, X509_REQ *req)
int X509_NAME_entry_count (const X509_NAME *name)
int X509_NAME_get_text_by_NID (X509_NAME *name, int nid, char *buf, int len)
int X509_NAME_get_text_by_OBJ (X509_NAME *name, const ASN1_OBJECT *obj, char *buf, int len)
int X509_NAME_get_index_by_NID (X509_NAME *name, int nid, int lastpos)
int X509_NAME_get_index_by_OBJ (X509_NAME *name, const ASN1_OBJECT *obj, int lastpos)
X509_NAME_ENTRY * X509_NAME_get_entry (const X509_NAME *name, int loc)
X509_NAME_ENTRY * X509_NAME_delete_entry (X509_NAME *name, int loc)
int X509_NAME_add_entry (X509_NAME *name, const X509_NAME_ENTRY *ne, int loc, int set)
int X509_NAME_add_entry_by_OBJ (X509_NAME *name, const ASN1_OBJECT *obj, int type, const unsigned char *bytes, int len, int loc, int set)
int X509_NAME_add_entry_by_NID (X509_NAME *name, int nid, int type, const unsigned char *bytes, int len, int loc, int set)
X509_NAME_ENTRY * X509_NAME_ENTRY_create_by_txt (X509_NAME_ENTRY **ne, const char *field, int type, const unsigned char *bytes, int len)
X509_NAME_ENTRY * X509_NAME_ENTRY_create_by_NID (X509_NAME_ENTRY **ne, int nid, int type, const unsigned char *bytes, int len)
int X509_NAME_add_entry_by_txt (X509_NAME *name, const char *field, int type, const unsigned char *bytes, int len, int loc, int set)
X509_NAME_ENTRY * X509_NAME_ENTRY_create_by_OBJ (X509_NAME_ENTRY **ne, const ASN1_OBJECT *obj, int type, const unsigned char *bytes, int len)
int X509_NAME_ENTRY_set_object (X509_NAME_ENTRY *ne, const ASN1_OBJECT *obj)
int X509_NAME_ENTRY_set_data (X509_NAME_ENTRY *ne, int type, const unsigned char *bytes, int len)
ASN1_OBJECT * X509_NAME_ENTRY_get_object (const X509_NAME_ENTRY *ne)
ASN1_STRING * X509_NAME_ENTRY_get_data (const X509_NAME_ENTRY *ne)
int X509_NAME_ENTRY_set (const X509_NAME_ENTRY *ne)
int X509_NAME_get0_der (X509_NAME *nm, const unsigned char **pder, size_t *pderlen)
int X509v3_get_ext_count (const STACK_OF(X509_EXTENSION) *x)
int X509v3_get_ext_by_NID (const STACK_OF(X509_EXTENSION) *x, int nid, int lastpos)
int X509v3_get_ext_by_OBJ (const STACK_OF(X509_EXTENSION) *x, const ASN1_OBJECT *obj, int lastpos)
int X509v3_get_ext_by_critical (const STACK_OF(X509_EXTENSION) *x, int crit, int lastpos)
X509_EXTENSION * X509v3_get_ext (const STACK_OF(X509_EXTENSION) *x, int loc)
X509_EXTENSION * X509v3_delete_ext (STACK_OF(X509_EXTENSION) *x, int loc)
int X509_get_ext_count (const X509 *x)
int X509_get_ext_by_NID (const X509 *x, int nid, int lastpos)
int X509_get_ext_by_OBJ (const X509 *x, const ASN1_OBJECT *obj, int lastpos)
int X509_get_ext_by_critical (const X509 *x, int crit, int lastpos)
X509_EXTENSION * X509_get_ext (const X509 *x, int loc)
X509_EXTENSION * X509_delete_ext (X509 *x, int loc)
int X509_add_ext (X509 *x, X509_EXTENSION *ex, int loc)
void * X509_get_ext_d2i (const X509 *x, int nid, int *crit, int *idx)
int X509_add1_ext_i2d (X509 *x, int nid, void *value, int crit, unsigned long flags)
int X509_CRL_get_ext_count (const X509_CRL *x)
int X509_CRL_get_ext_by_NID (const X509_CRL *x, int nid, int lastpos)
int X509_CRL_get_ext_by_OBJ (const X509_CRL *x, const ASN1_OBJECT *obj, int lastpos)
int X509_CRL_get_ext_by_critical (const X509_CRL *x, int crit, int lastpos)
X509_EXTENSION * X509_CRL_get_ext (const X509_CRL *x, int loc)
X509_EXTENSION * X509_CRL_delete_ext (X509_CRL *x, int loc)
int X509_CRL_add_ext (X509_CRL *x, X509_EXTENSION *ex, int loc)
void * X509_CRL_get_ext_d2i (const X509_CRL *x, int nid, int *crit, int *idx)
int X509_CRL_add1_ext_i2d (X509_CRL *x, int nid, void *value, int crit, unsigned long flags)
int X509_REVOKED_get_ext_count (const X509_REVOKED *x)
int X509_REVOKED_get_ext_by_NID (const X509_REVOKED *x, int nid, int lastpos)
int X509_REVOKED_get_ext_by_OBJ (const X509_REVOKED *x, const ASN1_OBJECT *obj, int lastpos)
int X509_REVOKED_get_ext_by_critical (const X509_REVOKED *x, int crit, int lastpos)
X509_EXTENSION * X509_REVOKED_get_ext (const X509_REVOKED *x, int loc)
X509_EXTENSION * X509_REVOKED_delete_ext (X509_REVOKED *x, int loc)
int X509_REVOKED_add_ext (X509_REVOKED *x, X509_EXTENSION *ex, int loc)
void * X509_REVOKED_get_ext_d2i (const X509_REVOKED *x, int nid, int *crit, int *idx)
int X509_REVOKED_add1_ext_i2d (X509_REVOKED *x, int nid, void *value, int crit, unsigned long flags)
X509_EXTENSION * X509_EXTENSION_create_by_NID (X509_EXTENSION **ex, int nid, int crit, ASN1_OCTET_STRING *data)
X509_EXTENSION * X509_EXTENSION_create_by_OBJ (X509_EXTENSION **ex, const ASN1_OBJECT *obj, int crit, ASN1_OCTET_STRING *data)
int X509_EXTENSION_set_object (X509_EXTENSION *ex, const ASN1_OBJECT *obj)
int X509_EXTENSION_set_critical (X509_EXTENSION *ex, int crit)
int X509_EXTENSION_set_data (X509_EXTENSION *ex, ASN1_OCTET_STRING *data)
ASN1_OBJECT * X509_EXTENSION_get_object (X509_EXTENSION *ex)
ASN1_OCTET_STRING * X509_EXTENSION_get_data (X509_EXTENSION *ne)
int X509_EXTENSION_get_critical (const X509_EXTENSION *ex)
int X509at_get_attr_count (const STACK_OF(X509_ATTRIBUTE) *x)
int X509at_get_attr_by_NID (const STACK_OF(X509_ATTRIBUTE) *x, int nid, int lastpos)
int X509at_get_attr_by_OBJ (const STACK_OF(X509_ATTRIBUTE) *sk, const ASN1_OBJECT *obj, int lastpos)
X509_ATTRIBUTE * X509at_get_attr (const STACK_OF(X509_ATTRIBUTE) *x, int loc)
X509_ATTRIBUTE * X509at_delete_attr (STACK_OF(X509_ATTRIBUTE) *x, int loc)
STACK_OF (X509_ATTRIBUTE) *X509at_add1_attr(STACK_OF(X509_ATTRIBUTE) **x
void * X509at_get0_data_by_OBJ (STACK_OF(X509_ATTRIBUTE) *x, const ASN1_OBJECT *obj, int lastpos, int type)
X509_ATTRIBUTE * X509_ATTRIBUTE_create_by_NID (X509_ATTRIBUTE **attr, int nid, int atrtype, const void *data, int len)
X509_ATTRIBUTE * X509_ATTRIBUTE_create_by_OBJ (X509_ATTRIBUTE **attr, const ASN1_OBJECT *obj, int atrtype, const void *data, int len)
X509_ATTRIBUTE * X509_ATTRIBUTE_create_by_txt (X509_ATTRIBUTE **attr, const char *atrname, int type, const unsigned char *bytes, int len)
int X509_ATTRIBUTE_set1_object (X509_ATTRIBUTE *attr, const ASN1_OBJECT *obj)
int X509_ATTRIBUTE_set1_data (X509_ATTRIBUTE *attr, int attrtype, const void *data, int len)
void * X509_ATTRIBUTE_get0_data (X509_ATTRIBUTE *attr, int idx, int atrtype, void *data)
int X509_ATTRIBUTE_count (const X509_ATTRIBUTE *attr)
ASN1_OBJECT * X509_ATTRIBUTE_get0_object (X509_ATTRIBUTE *attr)
ASN1_TYPE * X509_ATTRIBUTE_get0_type (X509_ATTRIBUTE *attr, int idx)
int EVP_PKEY_get_attr_count (const EVP_PKEY *key)
int EVP_PKEY_get_attr_by_NID (const EVP_PKEY *key, int nid, int lastpos)
int EVP_PKEY_get_attr_by_OBJ (const EVP_PKEY *key, const ASN1_OBJECT *obj, int lastpos)
X509_ATTRIBUTE * EVP_PKEY_get_attr (const EVP_PKEY *key, int loc)
X509_ATTRIBUTE * EVP_PKEY_delete_attr (EVP_PKEY *key, int loc)
int EVP_PKEY_add1_attr (EVP_PKEY *key, X509_ATTRIBUTE *attr)
int EVP_PKEY_add1_attr_by_OBJ (EVP_PKEY *key, const ASN1_OBJECT *obj, int type, const unsigned char *bytes, int len)
int EVP_PKEY_add1_attr_by_NID (EVP_PKEY *key, int nid, int type, const unsigned char *bytes, int len)
int EVP_PKEY_add1_attr_by_txt (EVP_PKEY *key, const char *attrname, int type, const unsigned char *bytes, int len)
int X509_verify_cert (X509_STORE_CTX *ctx)
X509 * X509_find_by_issuer_and_serial (STACK_OF(X509) *sk, X509_NAME *name, ASN1_INTEGER *serial)
X509 * X509_find_by_subject (STACK_OF(X509) *sk, X509_NAME *name)
int PKCS5_pbe_set0_algor (X509_ALGOR *algor, int alg, int iter, const unsigned char *salt, int saltlen)
X509_ALGOR * PKCS5_pbe_set (int alg, int iter, const unsigned char *salt, int saltlen)
X509_ALGOR * PKCS5_pbe2_set (const EVP_CIPHER *cipher, int iter, unsigned char *salt, int saltlen)
X509_ALGOR * PKCS5_pbe2_set_iv (const EVP_CIPHER *cipher, int iter, unsigned char *salt, int saltlen, unsigned char *aiv, int prf_nid)
X509_ALGOR * PKCS5_pbe2_set_scrypt (const EVP_CIPHER *cipher, const unsigned char *salt, int saltlen, unsigned char *aiv, uint64_t N, uint64_t r, uint64_t p)
X509_ALGOR * PKCS5_pbkdf2_set (int iter, unsigned char *salt, int saltlen, int prf_nid, int keylen)
EVP_PKEY * EVP_PKCS82PKEY (const PKCS8_PRIV_KEY_INFO *p8)
PKCS8_PRIV_KEY_INFO * EVP_PKEY2PKCS8 (EVP_PKEY *pkey)
int PKCS8_pkey_set0 (PKCS8_PRIV_KEY_INFO *priv, ASN1_OBJECT *aobj, int version, int ptype, void *pval, unsigned char *penc, int penclen)
int PKCS8_pkey_get0 (const ASN1_OBJECT **ppkalg, const unsigned char **pk, int *ppklen, const X509_ALGOR **pa, const PKCS8_PRIV_KEY_INFO *p8)
int PKCS8_pkey_add1_attr_by_NID (PKCS8_PRIV_KEY_INFO *p8, int nid, int type, const unsigned char *bytes, int len)
int X509_PUBKEY_set0_param (X509_PUBKEY *pub, ASN1_OBJECT *aobj, int ptype, void *pval, unsigned char *penc, int penclen)
int X509_PUBKEY_get0_param (ASN1_OBJECT **ppkalg, const unsigned char **pk, int *ppklen, X509_ALGOR **pa, X509_PUBKEY *pub)
int X509_check_trust (X509 *x, int id, int flags)
int X509_TRUST_get_count (void)
X509_TRUST * X509_TRUST_get0 (int idx)
int X509_TRUST_get_by_id (int id)
int X509_TRUST_add (int id, int flags, int(*ck)(X509_TRUST *, X509 *, int), const char *name, int arg1, void *arg2)
void X509_TRUST_cleanup (void)
int X509_TRUST_get_flags (const X509_TRUST *xp)
char * X509_TRUST_get0_name (const X509_TRUST *xp)
int X509_TRUST_get_trust (const X509_TRUST *xp)
int ERR_load_X509_strings (void)
Variables
int(*)(int, X509 *, int) X509_TRUST_set_default (int(*trust)(int, X509 *, int))
X509_EXTENSION * ex
X509_EXTENSION int loc
X509_ATTRIBUTE * attr
const ASN1_OBJECT * obj
const ASN1_OBJECT int type
const ASN1_OBJECT int const unsigned char * bytes
const ASN1_OBJECT int const unsigned char int len
int nid
const char * attrname
Macro Definition Documentation
X509_CRL_set_lastUpdate
#define X509_CRL_set_lastUpdate X509_CRL_set1_lastUpdate
Definition at line 701 of file x509.h.
X509_CRL_set_nextUpdate
#define X509_CRL_set_nextUpdate X509_CRL_set1_nextUpdate
Definition at line 702 of file x509.h.
X509_EX_V_INIT
#define X509_EX_V_INIT 0x0001
Definition at line 78 of file x509.h.
X509_EX_V_NETSCAPE_HACK
#define X509_EX_V_NETSCAPE_HACK 0x8000
Definition at line 77 of file x509.h.
X509_EXT_PACK_STRING
#define X509_EXT_PACK_STRING 2
Definition at line 317 of file x509.h.
X509_EXT_PACK_UNKNOWN
#define X509_EXT_PACK_UNKNOWN 1
Definition at line 316 of file x509.h.
X509_extract_key
#define X509_extract_key (x) X509_get_pubkey(x)/*****/
Definition at line 319 of file x509.h.
X509_F_ADD_CERT_DIR
#define X509_F_ADD_CERT_DIR 100
Definition at line 1032 of file x509.h.
X509_F_BUILD_CHAIN
#define X509_F_BUILD_CHAIN 106
Definition at line 1033 of file x509.h.
X509_F_BY_FILE_CTRL
#define X509_F_BY_FILE_CTRL 101
Definition at line 1034 of file x509.h.
X509_F_CHECK_NAME_CONSTRAINTS
#define X509_F_CHECK_NAME_CONSTRAINTS 149
Definition at line 1035 of file x509.h.
X509_F_CHECK_POLICY
#define X509_F_CHECK_POLICY 145
Definition at line 1036 of file x509.h.
X509_F_DANE_I2D
#define X509_F_DANE_I2D 107
Definition at line 1037 of file x509.h.
X509_F_DIR_CTRL
#define X509_F_DIR_CTRL 102
Definition at line 1038 of file x509.h.
X509_F_GET_CERT_BY_SUBJECT
#define X509_F_GET_CERT_BY_SUBJECT 103
Definition at line 1039 of file x509.h.
X509_F_NETSCAPE_SPKI_B64_DECODE
#define X509_F_NETSCAPE_SPKI_B64_DECODE 129
Definition at line 1040 of file x509.h.
Referenced by NETSCAPE_SPKI_b64_decode().
X509_F_NETSCAPE_SPKI_B64_ENCODE
#define X509_F_NETSCAPE_SPKI_B64_ENCODE 130
Definition at line 1041 of file x509.h.
Referenced by NETSCAPE_SPKI_b64_encode().
X509_F_X509_ATTRIBUTE_CREATE_BY_NID
#define X509_F_X509_ATTRIBUTE_CREATE_BY_NID 136
Definition at line 1044 of file x509.h.
X509_F_X509_ATTRIBUTE_CREATE_BY_OBJ
#define X509_F_X509_ATTRIBUTE_CREATE_BY_OBJ 137
Definition at line 1045 of file x509.h.
X509_F_X509_ATTRIBUTE_CREATE_BY_TXT
#define X509_F_X509_ATTRIBUTE_CREATE_BY_TXT 140
Definition at line 1046 of file x509.h.
Referenced by X509_ATTRIBUTE_create_by_txt().
X509_F_X509_ATTRIBUTE_GET0_DATA
#define X509_F_X509_ATTRIBUTE_GET0_DATA 139
Definition at line 1047 of file x509.h.
X509_F_X509_ATTRIBUTE_SET1_DATA
#define X509_F_X509_ATTRIBUTE_SET1_DATA 138
Definition at line 1048 of file x509.h.
Referenced by X509_ATTRIBUTE_set1_data().
X509_F_X509_CHECK_PRIVATE_KEY
#define X509_F_X509_CHECK_PRIVATE_KEY 128
Definition at line 1049 of file x509.h.
X509_F_X509_CRL_DIFF
#define X509_F_X509_CRL_DIFF 105
Definition at line 1050 of file x509.h.
X509_F_X509_CRL_PRINT_FP
#define X509_F_X509_CRL_PRINT_FP 147
Definition at line 1051 of file x509.h.
X509_F_X509_EXTENSION_CREATE_BY_NID
#define X509_F_X509_EXTENSION_CREATE_BY_NID 108
Definition at line 1052 of file x509.h.
X509_F_X509_EXTENSION_CREATE_BY_OBJ
#define X509_F_X509_EXTENSION_CREATE_BY_OBJ 109
Definition at line 1053 of file x509.h.
X509_F_X509_GET_PUBKEY_PARAMETERS
#define X509_F_X509_GET_PUBKEY_PARAMETERS 110
Definition at line 1054 of file x509.h.
X509_F_X509_LOAD_CERT_CRL_FILE
#define X509_F_X509_LOAD_CERT_CRL_FILE 132
Definition at line 1055 of file x509.h.
Referenced by X509_load_cert_crl_file().
X509_F_X509_LOAD_CERT_FILE
#define X509_F_X509_LOAD_CERT_FILE 111
Definition at line 1056 of file x509.h.
X509_F_X509_LOAD_CRL_FILE
#define X509_F_X509_LOAD_CRL_FILE 112
Definition at line 1057 of file x509.h.
X509_F_X509_NAME_ADD_ENTRY
#define X509_F_X509_NAME_ADD_ENTRY 113
Definition at line 1058 of file x509.h.
Referenced by X509_NAME_add_entry().
X509_F_X509_NAME_ENTRY_CREATE_BY_NID
#define X509_F_X509_NAME_ENTRY_CREATE_BY_NID 114
Definition at line 1059 of file x509.h.
Referenced by X509_NAME_ENTRY_create_by_NID().
X509_F_X509_NAME_ENTRY_CREATE_BY_TXT
#define X509_F_X509_NAME_ENTRY_CREATE_BY_TXT 131
Definition at line 1060 of file x509.h.
Referenced by X509_NAME_ENTRY_create_by_txt().
X509_F_X509_NAME_ENTRY_SET_OBJECT
#define X509_F_X509_NAME_ENTRY_SET_OBJECT 115
Definition at line 1061 of file x509.h.
Referenced by X509_NAME_ENTRY_set_object().
X509_F_X509_NAME_ONELINE
#define X509_F_X509_NAME_ONELINE 116
Definition at line 1062 of file x509.h.
X509_F_X509_NAME_PRINT
#define X509_F_X509_NAME_PRINT 117
Definition at line 1063 of file x509.h.
X509_F_X509_OBJECT_NEW
#define X509_F_X509_OBJECT_NEW 150
Definition at line 1064 of file x509.h.
X509_F_X509_PRINT_EX_FP
#define X509_F_X509_PRINT_EX_FP 118
Definition at line 1065 of file x509.h.
X509_F_X509_PUBKEY_DECODE
#define X509_F_X509_PUBKEY_DECODE 148
Definition at line 1066 of file x509.h.
X509_F_X509_PUBKEY_GET0
#define X509_F_X509_PUBKEY_GET0 119
Definition at line 1067 of file x509.h.
X509_F_X509_PUBKEY_SET
#define X509_F_X509_PUBKEY_SET 120
Definition at line 1068 of file x509.h.
X509_F_X509_REQ_CHECK_PRIVATE_KEY
#define X509_F_X509_REQ_CHECK_PRIVATE_KEY 144
Definition at line 1069 of file x509.h.
X509_F_X509_REQ_PRINT_EX
#define X509_F_X509_REQ_PRINT_EX 121
Definition at line 1070 of file x509.h.
Referenced by X509_REQ_print_ex().
X509_F_X509_REQ_PRINT_FP
#define X509_F_X509_REQ_PRINT_FP 122
Definition at line 1071 of file x509.h.
X509_F_X509_REQ_TO_X509
#define X509_F_X509_REQ_TO_X509 123
Definition at line 1072 of file x509.h.
X509_F_X509_STORE_ADD_CERT
#define X509_F_X509_STORE_ADD_CERT 124
Definition at line 1073 of file x509.h.
X509_F_X509_STORE_ADD_CRL
#define X509_F_X509_STORE_ADD_CRL 125
Definition at line 1074 of file x509.h.
X509_F_X509_STORE_CTX_GET1_ISSUER
#define X509_F_X509_STORE_CTX_GET1_ISSUER 146
Definition at line 1075 of file x509.h.
X509_F_X509_STORE_CTX_INIT
#define X509_F_X509_STORE_CTX_INIT 143
Definition at line 1076 of file x509.h.
X509_F_X509_STORE_CTX_NEW
#define X509_F_X509_STORE_CTX_NEW 142
Definition at line 1077 of file x509.h.
Referenced by X509_STORE_CTX_new().
X509_F_X509_STORE_CTX_PURPOSE_INHERIT
#define X509_F_X509_STORE_CTX_PURPOSE_INHERIT 134
Definition at line 1078 of file x509.h.
X509_F_X509_TO_X509_REQ
#define X509_F_X509_TO_X509_REQ 126
Definition at line 1079 of file x509.h.
X509_F_X509_TRUST_ADD
#define X509_F_X509_TRUST_ADD 133
Definition at line 1080 of file x509.h.
X509_F_X509_TRUST_SET
#define X509_F_X509_TRUST_SET 141
Definition at line 1081 of file x509.h.
Referenced by X509_TRUST_set().
X509_F_X509_VERIFY_CERT
#define X509_F_X509_VERIFY_CERT 127
Definition at line 1082 of file x509.h.
X509_F_X509AT_ADD1_ATTR
#define X509_F_X509AT_ADD1_ATTR 135
Definition at line 1042 of file x509.h.
Referenced by STACK_OF().
X509_F_X509V3_ADD_EXT
#define X509_F_X509V3_ADD_EXT 104
Definition at line 1043 of file x509.h.
Referenced by STACK_OF().
X509_FILETYPE_ASN1
#define X509_FILETYPE_ASN1 2
Definition at line 43 of file x509.h.
X509_FILETYPE_DEFAULT
#define X509_FILETYPE_DEFAULT 3
Definition at line 44 of file x509.h.
X509_FILETYPE_PEM
#define X509_FILETYPE_PEM 1
Definition at line 42 of file x509.h.
Referenced by X509_load_cert_crl_file().
X509_FLAG_COMPAT
#define X509_FLAG_COMPAT 0
Definition at line 147 of file x509.h.
Referenced by X509_print(), X509_print_fp(), X509_REQ_print(), and X509_REQ_print_ex().
X509_FLAG_NO_ATTRIBUTES
#define X509_FLAG_NO_ATTRIBUTES (1L << 11)
Definition at line 159 of file x509.h.
Referenced by X509_REQ_print_ex().
X509_FLAG_NO_AUX
#define X509_FLAG_NO_AUX (1L << 10)
Definition at line 158 of file x509.h.
X509_FLAG_NO_EXTENSIONS
#define X509_FLAG_NO_EXTENSIONS (1L << 8)
Definition at line 156 of file x509.h.
Referenced by X509_REQ_print_ex().
X509_FLAG_NO_HEADER
#define X509_FLAG_NO_HEADER 1L
Definition at line 148 of file x509.h.
Referenced by X509_REQ_print_ex().
X509_FLAG_NO_IDS
#define X509_FLAG_NO_IDS (1L << 12)
Definition at line 160 of file x509.h.
X509_FLAG_NO_ISSUER
#define X509_FLAG_NO_ISSUER (1L << 4)
Definition at line 152 of file x509.h.
X509_FLAG_NO_PUBKEY
#define X509_FLAG_NO_PUBKEY (1L << 7)
Definition at line 155 of file x509.h.
Referenced by X509_REQ_print_ex().
X509_FLAG_NO_SERIAL
#define X509_FLAG_NO_SERIAL (1L << 2)
Definition at line 150 of file x509.h.
X509_FLAG_NO_SIGDUMP
#define X509_FLAG_NO_SIGDUMP (1L << 9)
Definition at line 157 of file x509.h.
Referenced by X509_REQ_print_ex().
X509_FLAG_NO_SIGNAME
#define X509_FLAG_NO_SIGNAME (1L << 3)
Definition at line 151 of file x509.h.
X509_FLAG_NO_SUBJECT
#define X509_FLAG_NO_SUBJECT (1L << 6)
Definition at line 154 of file x509.h.
Referenced by X509_REQ_print_ex().
X509_FLAG_NO_VALIDITY
#define X509_FLAG_NO_VALIDITY (1L << 5)
Definition at line 153 of file x509.h.
X509_FLAG_NO_VERSION
#define X509_FLAG_NO_VERSION (1L << 1)
Definition at line 149 of file x509.h.
Referenced by X509_REQ_print_ex().
X509_get_ex_new_index
#define X509_get_ex_new_index (l, p, newf, dupf, freef) CRYPTO_get_ex_new_index(CRYPTO_EX_INDEX_X509, l, p, newf, dupf, freef)
Definition at line 543 of file x509.h.
X509_get_notAfter
#define X509_get_notAfter X509_getm_notAfter
Definition at line 636 of file x509.h.
X509_get_notBefore
#define X509_get_notBefore X509_getm_notBefore
Definition at line 635 of file x509.h.
X509_name_cmp
#define X509_name_cmp (a, b) X509_NAME_cmp((a),(b))
Definition at line 321 of file x509.h.
X509_R_AKID_MISMATCH
#define X509_R_AKID_MISMATCH 110
Definition at line 1085 of file x509.h.
X509_R_BAD_SELECTOR
#define X509_R_BAD_SELECTOR 133
Definition at line 1086 of file x509.h.
X509_R_BAD_X509_FILETYPE
#define X509_R_BAD_X509_FILETYPE 100
Definition at line 1087 of file x509.h.
X509_R_BASE64_DECODE_ERROR
#define X509_R_BASE64_DECODE_ERROR 118
Definition at line 1088 of file x509.h.
Referenced by NETSCAPE_SPKI_b64_decode().
X509_R_CANT_CHECK_DH_KEY
#define X509_R_CANT_CHECK_DH_KEY 114
Definition at line 1089 of file x509.h.
X509_R_CERT_ALREADY_IN_HASH_TABLE
#define X509_R_CERT_ALREADY_IN_HASH_TABLE 101
Definition at line 1090 of file x509.h.
Referenced by ssl_build_cert_chain().
X509_R_CRL_ALREADY_DELTA
#define X509_R_CRL_ALREADY_DELTA 127
Definition at line 1091 of file x509.h.
X509_R_CRL_VERIFY_FAILURE
#define X509_R_CRL_VERIFY_FAILURE 131
Definition at line 1092 of file x509.h.
X509_R_IDP_MISMATCH
#define X509_R_IDP_MISMATCH 128
Definition at line 1093 of file x509.h.
X509_R_INVALID_DIRECTORY
#define X509_R_INVALID_DIRECTORY 113
Definition at line 1094 of file x509.h.
X509_R_INVALID_FIELD_NAME
#define X509_R_INVALID_FIELD_NAME 119
Definition at line 1095 of file x509.h.
Referenced by X509_ATTRIBUTE_create_by_txt(), and X509_NAME_ENTRY_create_by_txt().
X509_R_INVALID_TRUST
#define X509_R_INVALID_TRUST 123
Definition at line 1096 of file x509.h.
Referenced by X509_TRUST_set().
X509_R_ISSUER_MISMATCH
#define X509_R_ISSUER_MISMATCH 129
Definition at line 1097 of file x509.h.
X509_R_KEY_TYPE_MISMATCH
#define X509_R_KEY_TYPE_MISMATCH 115
Definition at line 1098 of file x509.h.
X509_R_KEY_VALUES_MISMATCH
#define X509_R_KEY_VALUES_MISMATCH 116
Definition at line 1099 of file x509.h.
X509_R_LOADING_CERT_DIR
#define X509_R_LOADING_CERT_DIR 103
Definition at line 1100 of file x509.h.
X509_R_LOADING_DEFAULTS
#define X509_R_LOADING_DEFAULTS 104
Definition at line 1101 of file x509.h.
X509_R_METHOD_NOT_SUPPORTED
#define X509_R_METHOD_NOT_SUPPORTED 124
Definition at line 1102 of file x509.h.
X509_R_NAME_TOO_LONG
#define X509_R_NAME_TOO_LONG 134
Definition at line 1103 of file x509.h.
X509_R_NEWER_CRL_NOT_NEWER
#define X509_R_NEWER_CRL_NOT_NEWER 132
Definition at line 1104 of file x509.h.
X509_R_NO_CERT_SET_FOR_US_TO_VERIFY
#define X509_R_NO_CERT_SET_FOR_US_TO_VERIFY 105
Definition at line 1105 of file x509.h.
X509_R_NO_CRL_NUMBER
#define X509_R_NO_CRL_NUMBER 130
Definition at line 1106 of file x509.h.
X509_R_PUBLIC_KEY_DECODE_ERROR
#define X509_R_PUBLIC_KEY_DECODE_ERROR 125
Definition at line 1107 of file x509.h.
X509_R_PUBLIC_KEY_ENCODE_ERROR
#define X509_R_PUBLIC_KEY_ENCODE_ERROR 126
Definition at line 1108 of file x509.h.
X509_R_SHOULD_RETRY
#define X509_R_SHOULD_RETRY 106
Definition at line 1109 of file x509.h.
X509_R_UNABLE_TO_FIND_PARAMETERS_IN_CHAIN
#define X509_R_UNABLE_TO_FIND_PARAMETERS_IN_CHAIN 107
Definition at line 1110 of file x509.h.
X509_R_UNABLE_TO_GET_CERTS_PUBLIC_KEY
#define X509_R_UNABLE_TO_GET_CERTS_PUBLIC_KEY 108
Definition at line 1111 of file x509.h.
X509_R_UNKNOWN_KEY_TYPE
#define X509_R_UNKNOWN_KEY_TYPE 117
Definition at line 1112 of file x509.h.
X509_R_UNKNOWN_NID
#define X509_R_UNKNOWN_NID 109
Definition at line 1113 of file x509.h.
Referenced by X509_NAME_ENTRY_create_by_NID().
X509_R_UNKNOWN_PURPOSE_ID
#define X509_R_UNKNOWN_PURPOSE_ID 121
Definition at line 1114 of file x509.h.
X509_R_UNKNOWN_TRUST_ID
#define X509_R_UNKNOWN_TRUST_ID 120
Definition at line 1115 of file x509.h.
X509_R_UNSUPPORTED_ALGORITHM
#define X509_R_UNSUPPORTED_ALGORITHM 111
Definition at line 1116 of file x509.h.
X509_R_WRONG_LOOKUP_TYPE
#define X509_R_WRONG_LOOKUP_TYPE 112
Definition at line 1117 of file x509.h.
X509_R_WRONG_TYPE
#define X509_R_WRONG_TYPE 122
Definition at line 1118 of file x509.h.
X509_REQ_extract_key
#define X509_REQ_extract_key (a) X509_REQ_get_pubkey(a)
Definition at line 320 of file x509.h.
X509_set_notAfter
#define X509_set_notAfter X509_set1_notAfter
Definition at line 638 of file x509.h.
X509_set_notBefore
#define X509_set_notBefore X509_set1_notBefore
Definition at line 637 of file x509.h.
X509_TRUST_COMPAT
#define X509_TRUST_COMPAT 1
Definition at line 116 of file x509.h.
X509_TRUST_DEFAULT
#define X509_TRUST_DEFAULT 0 /* Only valid in purpose settings */
Definition at line 114 of file x509.h.
Referenced by X509_VERIFY_PARAM_inherit(), and X509_VERIFY_PARAM_new().
X509_TRUST_DO_SS_COMPAT
#define X509_TRUST_DO_SS_COMPAT (1U << 3)
Definition at line 135 of file x509.h.
X509_TRUST_DYNAMIC
#define X509_TRUST_DYNAMIC (1U << 0)
Definition at line 130 of file x509.h.
X509_TRUST_DYNAMIC_NAME
#define X509_TRUST_DYNAMIC_NAME (1U << 1)
Definition at line 131 of file x509.h.
X509_TRUST_EMAIL
#define X509_TRUST_EMAIL 4
Definition at line 119 of file x509.h.
X509_TRUST_MAX
#define X509_TRUST_MAX 8
Definition at line 127 of file x509.h.
X509_TRUST_MIN
#define X509_TRUST_MIN 1
Definition at line 126 of file x509.h.
X509_TRUST_NO_SS_COMPAT
#define X509_TRUST_NO_SS_COMPAT (1U << 2)
Definition at line 133 of file x509.h.
X509_TRUST_OBJECT_SIGN
#define X509_TRUST_OBJECT_SIGN 5
Definition at line 120 of file x509.h.
X509_TRUST_OCSP_REQUEST
#define X509_TRUST_OCSP_REQUEST 7
Definition at line 122 of file x509.h.
X509_TRUST_OCSP_SIGN
#define X509_TRUST_OCSP_SIGN 6
Definition at line 121 of file x509.h.
X509_TRUST_OK_ANY_EKU
#define X509_TRUST_OK_ANY_EKU (1U << 4)
Definition at line 137 of file x509.h.
X509_TRUST_REJECTED
#define X509_TRUST_REJECTED 2
Definition at line 142 of file x509.h.
X509_TRUST_SSL_CLIENT
#define X509_TRUST_SSL_CLIENT 2
Definition at line 117 of file x509.h.
X509_TRUST_SSL_SERVER
#define X509_TRUST_SSL_SERVER 3
Definition at line 118 of file x509.h.
X509_TRUST_TRUSTED
#define X509_TRUST_TRUSTED 1
Definition at line 141 of file x509.h.
X509_TRUST_TSA
#define X509_TRUST_TSA 8
Definition at line 123 of file x509.h.
X509_TRUST_UNTRUSTED
#define X509_TRUST_UNTRUSTED 3
Definition at line 143 of file x509.h.
X509v3_KU_CRL_SIGN
#define X509v3_KU_CRL_SIGN 0x0002
Definition at line 52 of file x509.h.
X509v3_KU_DATA_ENCIPHERMENT
#define X509v3_KU_DATA_ENCIPHERMENT 0x0010
Definition at line 49 of file x509.h.
X509v3_KU_DECIPHER_ONLY
#define X509v3_KU_DECIPHER_ONLY 0x8000
Definition at line 54 of file x509.h.
X509v3_KU_DIGITAL_SIGNATURE
#define X509v3_KU_DIGITAL_SIGNATURE 0x0080
Definition at line 46 of file x509.h.
Referenced by ssl_check_srvr_ecc_cert_and_alg().
X509v3_KU_ENCIPHER_ONLY
#define X509v3_KU_ENCIPHER_ONLY 0x0001
Definition at line 53 of file x509.h.
X509v3_KU_KEY_AGREEMENT
#define X509v3_KU_KEY_AGREEMENT 0x0008
Definition at line 50 of file x509.h.
X509v3_KU_KEY_CERT_SIGN
#define X509v3_KU_KEY_CERT_SIGN 0x0004
Definition at line 51 of file x509.h.
X509v3_KU_KEY_ENCIPHERMENT
#define X509v3_KU_KEY_ENCIPHERMENT 0x0020
Definition at line 48 of file x509.h.
X509v3_KU_NON_REPUDIATION
#define X509v3_KU_NON_REPUDIATION 0x0040
Definition at line 47 of file x509.h.
X509v3_KU_UNDEF
#define X509v3_KU_UNDEF 0xffff
Definition at line 55 of file x509.h.
XN_FLAG_COMPAT
#define XN_FLAG_COMPAT 0/* Traditional; use old X509_NAME_print */
Definition at line 168 of file x509.h.
Referenced by X509_NAME_print_ex_fp(), X509_print(), X509_print_fp(), and X509_REQ_print().
XN_FLAG_DN_REV
#define XN_FLAG_DN_REV (1 << 20)/* Reverse DN order */
Definition at line 174 of file x509.h.
XN_FLAG_DUMP_UNKNOWN_FIELDS
#define XN_FLAG_DUMP_UNKNOWN_FIELDS (1 << 24)
Definition at line 192 of file x509.h.
XN_FLAG_FN_ALIGN
#define XN_FLAG_FN_ALIGN
Value:
(1 << 25)/* Align field names to 20
                                           * characters */
Definition at line 194 of file x509.h.
XN_FLAG_FN_LN
#define XN_FLAG_FN_LN (1 << 21)/* Object long name */
Definition at line 181 of file x509.h.
XN_FLAG_FN_MASK
#define XN_FLAG_FN_MASK (0x3 << 21)
Definition at line 178 of file x509.h.
XN_FLAG_FN_NONE
#define XN_FLAG_FN_NONE (3 << 21)/* No field names */
Definition at line 183 of file x509.h.
XN_FLAG_FN_OID
#define XN_FLAG_FN_OID (2 << 21)/* Always use OIDs */
Definition at line 182 of file x509.h.
XN_FLAG_FN_SN
#define XN_FLAG_FN_SN 0/* Object short name */
Definition at line 180 of file x509.h.
XN_FLAG_MULTILINE
#define XN_FLAG_MULTILINE
Value:
(ASN1_STRFLGS_ESC_CTRL | \
                        ASN1_STRFLGS_ESC_MSB | \
                        XN_FLAG_SEP_MULTILINE | \
                        XN_FLAG_SPC_EQ | \
                        XN_FLAG_FN_LN | \
                        XN_FLAG_FN_ALIGN)
Definition at line 215 of file x509.h.
XN_FLAG_ONELINE
#define XN_FLAG_ONELINE
Value:
(ASN1_STRFLGS_RFC2253 | \
                        ASN1_STRFLGS_ESC_QUOTE | \
                        XN_FLAG_SEP_CPLUS_SPC | \
                        XN_FLAG_SPC_EQ | \
                        XN_FLAG_FN_SN)
Definition at line 207 of file x509.h.
Referenced by verify_callback().
XN_FLAG_RFC2253
#define XN_FLAG_RFC2253
Value:
(ASN1_STRFLGS_RFC2253 | \
                        XN_FLAG_SEP_COMMA_PLUS | \
                        XN_FLAG_DN_REV | \
                        XN_FLAG_FN_SN | \
                        XN_FLAG_DUMP_UNKNOWN_FIELDS)
Definition at line 199 of file x509.h.
XN_FLAG_SEP_COMMA_PLUS
#define XN_FLAG_SEP_COMMA_PLUS (1 << 16)/* RFC2253 ,+ */
Definition at line 169 of file x509.h.
XN_FLAG_SEP_CPLUS_SPC
#define XN_FLAG_SEP_CPLUS_SPC (2 << 16)/* ,+ spaced: more readable */
Definition at line 170 of file x509.h.
XN_FLAG_SEP_MASK
#define XN_FLAG_SEP_MASK (0xf << 16)
Definition at line 166 of file x509.h.
Referenced by X509_REQ_print_ex().
XN_FLAG_SEP_MULTILINE
#define XN_FLAG_SEP_MULTILINE (4 << 16)/* One line per field */
Definition at line 172 of file x509.h.
Referenced by X509_REQ_print_ex().
XN_FLAG_SEP_SPLUS_SPC
#define XN_FLAG_SEP_SPLUS_SPC (3 << 16)/* ;+ spaced */
Definition at line 171 of file x509.h.
XN_FLAG_SPC_EQ
#define XN_FLAG_SPC_EQ (1 << 23)/* Put spaces round '=' */
Definition at line 185 of file x509.h.
Function Documentation
ASN1_digest()
int ASN1_digest (i2d_of_void * i2d, const EVP_MD * type, char * data, unsigned char * md, unsigned int * len)
Definition at line 26 of file a_digest.c.
ASN1_item_digest()
int ASN1_item_digest (const ASN1_ITEM * it, const EVP_MD * type, void * data, unsigned char * md, unsigned int * len)
Definition at line 50 of file a_digest.c.
ASN1_item_sign()
int ASN1_item_sign (const ASN1_ITEM * it, X509_ALGOR * algor1, X509_ALGOR * algor2, ASN1_BIT_STRING * signature, void * data, EVP_PKEY * pkey, const EVP_MD * type)
Definition at line 114 of file a_sign.c.
References ASN1_F_ASN1_ITEM_SIGN, ASN1_item_sign_ctx(), ASN1err, ctx, ERR_R_MALLOC_FAILURE, EVP_DigestSignInit(), EVP_MD_CTX_free(), EVP_MD_CTX_new(), and NULL.
ASN1_item_sign_ctx()
int ASN1_item_sign_ctx (const ASN1_ITEM * it, X509_ALGOR * algor1, X509_ALGOR * algor2, ASN1_BIT_STRING * signature, void * asn, EVP_MD_CTX * ctx)
Definition at line 136 of file a_sign.c.
References ASN1_F_ASN1_ITEM_SIGN_CTX, ASN1_item_i2d(), ASN1_PKEY_SIGPARAM_NULL, ASN1_R_CONTEXT_NOT_INITIALISED, ASN1_R_DIGEST_AND_KEY_TYPE_NOT_SUPPORTED, ASN1_STRING_FLAG_BITS_LEFT, ASN1err, ERR_R_EVP_LIB, ERR_R_MALLOC_FAILURE, EVP_DigestSignFinal(), EVP_DigestSignUpdate, EVP_MD_CTX_md(), EVP_MD_CTX_pkey_ctx(), EVP_MD_nid, EVP_PKEY_CTX_get0_pkey(), EVP_PKEY_size(), NULL, OBJ_find_sigid_by_algs(), OBJ_nid2obj(), OPENSSL_clear_free, OPENSSL_free, OPENSSL_malloc, type, V_ASN1_NULL, V_ASN1_UNDEF, and X509_ALGOR_set0().
Referenced by ASN1_item_sign(), X509_CRL_sign_ctx(), X509_REQ_sign_ctx(), and X509_sign_ctx().
ASN1_item_verify()
int ASN1_item_verify (const ASN1_ITEM * it, X509_ALGOR * algor1, ASN1_BIT_STRING * signature, void * data, EVP_PKEY * pkey)
Definition at line 87 of file a_verify.c.
References ctx, and NULL.
Referenced by NETSCAPE_SPKI_verify(), X509_REQ_verify(), and X509_verify().
ASN1_sign()
int ASN1_sign (i2d_of_void * i2d, X509_ALGOR * algor1, X509_ALGOR * algor2, ASN1_BIT_STRING * signature, char * data, EVP_PKEY * pkey, const EVP_MD * type)
Definition at line 29 of file a_sign.c.
References ASN1_F_ASN1_SIGN, ASN1_OBJECT_free(), ASN1_R_THE_ASN1_OBJECT_IDENTIFIER_IS_NOT_KNOWN_FOR_THIS_MD, ASN1_R_UNKNOWN_OBJECT_TYPE, ASN1_STRING_FLAG_BITS_LEFT, ASN1err, ctx, ERR_R_EVP_LIB, ERR_R_MALLOC_FAILURE, EVP_MD_CTX_free(), EVP_MD_CTX_new(), EVP_PKEY_size(), EVP_SignFinal(), EVP_SignInit_ex, EVP_SignUpdate, NID_dsaWithSHA1, NULL, OBJ_nid2obj(), OPENSSL_clear_free, OPENSSL_free, OPENSSL_malloc, and V_ASN1_NULL.
ASN1_verify()
int ASN1_verify (i2d_of_void * i2d, X509_ALGOR * algor1, ASN1_BIT_STRING * signature, char * data, EVP_PKEY * pkey)
Definition at line 29 of file a_verify.c.
References ctx, EVP_MD_CTX_new(), NULL, and type.
d2i_DSA_PUBKEY()
DSA* d2i_DSA_PUBKEY (DSA ** a, const unsigned char ** pp, long length)
Referenced by d2i_DSA_PUBKEY_bio(), and d2i_DSA_PUBKEY_fp().
d2i_DSA_PUBKEY_bio()
DSA* d2i_DSA_PUBKEY_bio (BIO * bp, DSA ** dsa)
Definition at line 298 of file x_all.c.
References ASN1_d2i_bio_of, d2i_DSA_PUBKEY(), and DSA_new().
d2i_DSA_PUBKEY_fp()
DSA* d2i_DSA_PUBKEY_fp (FILE * fp, DSA ** dsa)
Definition at line 277 of file x_all.c.
References ASN1_d2i_fp_of, d2i_DSA_PUBKEY(), and DSA_new().
d2i_DSAPrivateKey_bio()
DSA* d2i_DSAPrivateKey_bio (BIO * bp, DSA ** dsa)
Definition at line 288 of file x_all.c.
References ASN1_d2i_bio_of, d2i_DSAPrivateKey(), and DSA_new().
d2i_DSAPrivateKey_fp()
DSA* d2i_DSAPrivateKey_fp (FILE * fp, DSA ** dsa)
Definition at line 267 of file x_all.c.
References ASN1_d2i_fp_of, d2i_DSAPrivateKey(), and DSA_new().
d2i_EC_PUBKEY()
EC_KEY* d2i_EC_PUBKEY (EC_KEY ** a, const unsigned char ** pp, long length)
Referenced by d2i_EC_PUBKEY_bio(), and d2i_EC_PUBKEY_fp().
d2i_EC_PUBKEY_bio()
EC_KEY* d2i_EC_PUBKEY_bio (BIO * bp, EC_KEY ** eckey)
Definition at line 332 of file x_all.c.
References ASN1_d2i_bio_of, d2i_EC_PUBKEY(), and EC_KEY_new().
d2i_EC_PUBKEY_fp()
EC_KEY* d2i_EC_PUBKEY_fp (FILE * fp, EC_KEY ** eckey)
Definition at line 312 of file x_all.c.
References ASN1_d2i_fp_of, d2i_EC_PUBKEY(), and EC_KEY_new().
d2i_ECPrivateKey_bio()
EC_KEY* d2i_ECPrivateKey_bio (BIO * bp, EC_KEY ** eckey)
Definition at line 342 of file x_all.c.
References ASN1_d2i_bio_of, d2i_ECPrivateKey(), and EC_KEY_new().
d2i_ECPrivateKey_fp()
EC_KEY* d2i_ECPrivateKey_fp (FILE * fp, EC_KEY ** eckey)
Definition at line 322 of file x_all.c.
References ASN1_d2i_fp_of, d2i_ECPrivateKey(), and EC_KEY_new().
d2i_PKCS8_bio()
X509_SIG* d2i_PKCS8_bio (BIO * bp, X509_SIG ** p8)
Definition at line 425 of file x_all.c.
References ASN1_d2i_bio_of.
d2i_PKCS8_fp()
X509_SIG* d2i_PKCS8_fp (FILE * fp, X509_SIG ** p8)
Definition at line 414 of file x_all.c.
References ASN1_d2i_fp_of.
d2i_PKCS8_PRIV_KEY_INFO_bio()
PKCS8_PRIV_KEY_INFO* d2i_PKCS8_PRIV_KEY_INFO_bio (BIO * bp, PKCS8_PRIV_KEY_INFO ** p8inf)
Definition at line 483 of file x_all.c.
References ASN1_d2i_bio_of.
d2i_PKCS8_PRIV_KEY_INFO_fp()
PKCS8_PRIV_KEY_INFO* d2i_PKCS8_PRIV_KEY_INFO_fp (FILE * fp, PKCS8_PRIV_KEY_INFO ** p8inf)
Definition at line 436 of file x_all.c.
References ASN1_d2i_fp_of.
d2i_PrivateKey_bio()
EVP_PKEY* d2i_PrivateKey_bio (BIO * bp, EVP_PKEY ** a)
Definition at line 513 of file x_all.c.
References ASN1_d2i_bio_of, d2i_AutoPrivateKey(), and EVP_PKEY_new().
d2i_PrivateKey_fp()
EVP_PKEY* d2i_PrivateKey_fp (FILE * fp, EVP_PKEY ** a)
Definition at line 466 of file x_all.c.
References ASN1_d2i_fp_of, d2i_AutoPrivateKey(), and EVP_PKEY_new().
d2i_PUBKEY()
EVP_PKEY* d2i_PUBKEY (EVP_PKEY ** a, const unsigned char ** pp, long length)
Referenced by d2i_PUBKEY_bio(), and d2i_PUBKEY_fp().
d2i_PUBKEY_bio()
EVP_PKEY* d2i_PUBKEY_bio (BIO * bp, EVP_PKEY ** a)
Definition at line 523 of file x_all.c.
References ASN1_d2i_bio_of, d2i_PUBKEY(), and EVP_PKEY_new().
d2i_PUBKEY_fp()
EVP_PKEY* d2i_PUBKEY_fp (FILE * fp, EVP_PKEY ** a)
Definition at line 476 of file x_all.c.
References ASN1_d2i_fp_of, d2i_PUBKEY(), and EVP_PKEY_new().
d2i_RSA_PUBKEY()
RSA* d2i_RSA_PUBKEY (RSA ** a, const unsigned char ** pp, long length)
Referenced by d2i_RSA_PUBKEY_bio(), and d2i_RSA_PUBKEY_fp().
d2i_RSA_PUBKEY_bio()
RSA* d2i_RSA_PUBKEY_bio (BIO * bp, RSA ** rsa)
Definition at line 249 of file x_all.c.
References ASN1_d2i_bio_of, d2i_RSA_PUBKEY(), and RSA_new().
d2i_RSA_PUBKEY_fp()
RSA* d2i_RSA_PUBKEY_fp (FILE * fp, RSA ** rsa)
Definition at line 216 of file x_all.c.
References ASN1_d2i_fp(), D2I_OF, d2i_RSA_PUBKEY(), and RSA_new().
d2i_RSAPrivateKey_bio()
RSA* d2i_RSAPrivateKey_bio (BIO * bp, RSA ** rsa)
Definition at line 234 of file x_all.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_RSAPrivateKey_fp()
RSA* d2i_RSAPrivateKey_fp (FILE * fp, RSA ** rsa)
Definition at line 201 of file x_all.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
d2i_RSAPublicKey_bio()
RSA* d2i_RSAPublicKey_bio (BIO * bp, RSA ** rsa)
Definition at line 244 of file x_all.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_RSAPublicKey_fp()
RSA* d2i_RSAPublicKey_fp (FILE * fp, RSA ** rsa)
Definition at line 211 of file x_all.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
d2i_X509_AUX()
X509* d2i_X509_AUX (X509 ** a, const unsigned char ** pp, long length)
d2i_X509_bio()
X509* d2i_X509_bio (BIO * bp, X509 ** x509)
Definition at line 122 of file x_all.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_X509_CRL_bio()
X509_CRL* d2i_X509_CRL_bio (BIO * bp, X509_CRL ** crl)
Definition at line 144 of file x_all.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_X509_CRL_fp()
X509_CRL* d2i_X509_CRL_fp (FILE * fp, X509_CRL ** crl)
Definition at line 133 of file x_all.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
d2i_X509_fp()
X509* d2i_X509_fp (FILE * fp, X509 ** x509)
Definition at line 111 of file x_all.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
d2i_X509_REQ_bio()
X509_REQ* d2i_X509_REQ_bio (BIO * bp, X509_REQ ** req)
Definition at line 188 of file x_all.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_X509_REQ_fp()
X509_REQ* d2i_X509_REQ_fp (FILE * fp, X509_REQ ** req)
Definition at line 177 of file x_all.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
ERR_load_X509_strings()
int ERR_load_X509_strings (void)
Definition at line 132 of file x509_err.c.
References ERR_func_error_string(), ERR_load_strings(), and NULL.
Referenced by err_load_crypto_strings_int().
EVP_PKCS82PKEY()
EVP_PKEY* EVP_PKCS82PKEY (const PKCS8_PRIV_KEY_INFO * p8)
Definition at line 21 of file evp_pkey.c.
References ERR_add_error_data(), ERR_R_MALLOC_FAILURE, EVP_F_EVP_PKCS82PKEY, EVP_PKEY_free(), EVP_PKEY_new(), EVP_PKEY_set_type(), EVP_R_METHOD_NOT_SUPPORTED, EVP_R_PRIVATE_KEY_DECODE_ERROR, EVP_R_UNSUPPORTED_PRIVATE_KEY_ALGORITHM, EVPerr, i2t_ASN1_OBJECT(), NULL, OBJ_obj2nid(), and PKCS8_pkey_get0().
EVP_PKEY2PKCS8()
PKCS8_PRIV_KEY_INFO* EVP_PKEY2PKCS8 (EVP_PKEY * pkey)
Definition at line 61 of file evp_pkey.c.
References ERR_R_MALLOC_FAILURE, EVP_F_EVP_PKEY2PKCS8, EVP_R_METHOD_NOT_SUPPORTED, EVP_R_PRIVATE_KEY_ENCODE_ERROR, EVP_R_UNSUPPORTED_PRIVATE_KEY_ALGORITHM, EVPerr, NULL, and RAND_add().
Referenced by i2d_PrivateKey(), and PKCS12_add_key().
EVP_PKEY_add1_attr()
int EVP_PKEY_add1_attr (EVP_PKEY * key, X509_ATTRIBUTE * attr)
Definition at line 118 of file evp_pkey.c.
EVP_PKEY_add1_attr_by_NID()
int EVP_PKEY_add1_attr_by_NID (EVP_PKEY * key, int nid, int type, const unsigned char * bytes, int len)
Definition at line 134 of file evp_pkey.c.
EVP_PKEY_add1_attr_by_OBJ()
int EVP_PKEY_add1_attr_by_OBJ (EVP_PKEY * key, const ASN1_OBJECT * obj, int type, const unsigned char * bytes, int len)
Definition at line 125 of file evp_pkey.c.
EVP_PKEY_add1_attr_by_txt()
int EVP_PKEY_add1_attr_by_txt (EVP_PKEY * key, const char * attrname, int type, const unsigned char * bytes, int len)
Definition at line 143 of file evp_pkey.c.
EVP_PKEY_delete_attr()
X509_ATTRIBUTE* EVP_PKEY_delete_attr (EVP_PKEY * key, int loc)
Definition at line 113 of file evp_pkey.c.
References X509at_delete_attr().
EVP_PKEY_get_attr()
X509_ATTRIBUTE* EVP_PKEY_get_attr (const EVP_PKEY * key, int loc)
Definition at line 108 of file evp_pkey.c.
References X509at_get_attr().
EVP_PKEY_get_attr_by_NID()
int EVP_PKEY_get_attr_by_NID (const EVP_PKEY * key, int nid, int lastpos)
Definition at line 97 of file evp_pkey.c.
References X509at_get_attr_by_NID().
EVP_PKEY_get_attr_by_OBJ()
int EVP_PKEY_get_attr_by_OBJ (const EVP_PKEY * key, const ASN1_OBJECT * obj, int lastpos)
Definition at line 102 of file evp_pkey.c.
References X509at_get_attr_by_OBJ().
EVP_PKEY_get_attr_count()
int EVP_PKEY_get_attr_count (const EVP_PKEY * key)
Definition at line 92 of file evp_pkey.c.
References X509at_get_attr_count().
i2d_DSA_PUBKEY()
int i2d_DSA_PUBKEY (DSA * a, unsigned char ** pp)
Referenced by i2d_DSA_PUBKEY_bio(), and i2d_DSA_PUBKEY_fp().
i2d_DSA_PUBKEY_bio()
int i2d_DSA_PUBKEY_bio (BIO * bp, DSA * dsa)
Definition at line 303 of file x_all.c.
References ASN1_i2d_bio_of, and i2d_DSA_PUBKEY().
i2d_DSA_PUBKEY_fp()
int i2d_DSA_PUBKEY_fp (FILE * fp, DSA * dsa)
Definition at line 282 of file x_all.c.
References ASN1_i2d_fp_of, and i2d_DSA_PUBKEY().
i2d_DSAPrivateKey_bio()
int i2d_DSAPrivateKey_bio (BIO * bp, DSA * dsa)
Definition at line 293 of file x_all.c.
References ASN1_i2d_bio_of_const, and i2d_DSAPrivateKey().
i2d_DSAPrivateKey_fp()
int i2d_DSAPrivateKey_fp (FILE * fp, DSA * dsa)
Definition at line 272 of file x_all.c.
References ASN1_i2d_fp_of_const, and i2d_DSAPrivateKey().
i2d_EC_PUBKEY()
int i2d_EC_PUBKEY (EC_KEY * a, unsigned char ** pp)
Referenced by i2d_EC_PUBKEY_bio(), and i2d_EC_PUBKEY_fp().
i2d_EC_PUBKEY_bio()
int i2d_EC_PUBKEY_bio (BIO * bp, EC_KEY * eckey)
Definition at line 337 of file x_all.c.
References ASN1_i2d_bio_of, and i2d_EC_PUBKEY().
i2d_EC_PUBKEY_fp()
int i2d_EC_PUBKEY_fp (FILE * fp, EC_KEY * eckey)
Definition at line 317 of file x_all.c.
References ASN1_i2d_fp_of, and i2d_EC_PUBKEY().
i2d_ECPrivateKey_bio()
int i2d_ECPrivateKey_bio (BIO * bp, EC_KEY * eckey)
Definition at line 347 of file x_all.c.
References ASN1_i2d_bio_of, and i2d_ECPrivateKey().
i2d_ECPrivateKey_fp()
int i2d_ECPrivateKey_fp (FILE * fp, EC_KEY * eckey)
Definition at line 327 of file x_all.c.
References ASN1_i2d_fp_of, and i2d_ECPrivateKey().
i2d_PKCS8_bio()
int i2d_PKCS8_bio (BIO * bp, X509_SIG * p8)
Definition at line 430 of file x_all.c.
References ASN1_i2d_bio_of.
i2d_PKCS8_fp()
int i2d_PKCS8_fp (FILE * fp, X509_SIG * p8)
Definition at line 419 of file x_all.c.
References ASN1_i2d_fp_of.
i2d_PKCS8_PRIV_KEY_INFO_bio()
int i2d_PKCS8_PRIV_KEY_INFO_bio (BIO * bp, PKCS8_PRIV_KEY_INFO * p8inf)
Definition at line 490 of file x_all.c.
References ASN1_i2d_bio_of.
i2d_PKCS8_PRIV_KEY_INFO_fp()
int i2d_PKCS8_PRIV_KEY_INFO_fp (FILE * fp, PKCS8_PRIV_KEY_INFO * p8inf)
Definition at line 443 of file x_all.c.
References ASN1_i2d_fp_of.
i2d_PKCS8PrivateKeyInfo_bio()
int i2d_PKCS8PrivateKeyInfo_bio (BIO * bp, EVP_PKEY * key)
Definition at line 496 of file x_all.c.
i2d_PKCS8PrivateKeyInfo_fp()
int i2d_PKCS8PrivateKeyInfo_fp (FILE * fp, EVP_PKEY * key)
Definition at line 449 of file x_all.c.
i2d_PrivateKey_bio()
int i2d_PrivateKey_bio (BIO * bp, EVP_PKEY * pkey)
Definition at line 508 of file x_all.c.
References ASN1_i2d_bio_of, and i2d_PrivateKey().
i2d_PrivateKey_fp()
int i2d_PrivateKey_fp (FILE * fp, EVP_PKEY * pkey)
Definition at line 461 of file x_all.c.
References ASN1_i2d_fp_of, and i2d_PrivateKey().
i2d_PUBKEY()
int i2d_PUBKEY (EVP_PKEY * a, unsigned char ** pp)
Referenced by i2d_PUBKEY_bio(), and i2d_PUBKEY_fp().
i2d_PUBKEY_bio()
int i2d_PUBKEY_bio (BIO * bp, EVP_PKEY * pkey)
Definition at line 518 of file x_all.c.
References ASN1_i2d_bio_of, and i2d_PUBKEY().
i2d_PUBKEY_fp()
int i2d_PUBKEY_fp (FILE * fp, EVP_PKEY * pkey)
Definition at line 471 of file x_all.c.
References ASN1_i2d_fp_of, and i2d_PUBKEY().
i2d_re_X509_CRL_tbs()
int i2d_re_X509_CRL_tbs (X509_CRL * req, unsigned char ** pp)
Definition at line 178 of file x509cset.c.
i2d_re_X509_REQ_tbs()
int i2d_re_X509_REQ_tbs (X509_REQ * req, unsigned char ** pp)
Definition at line 294 of file x509_req.c.
i2d_re_X509_tbs()
int i2d_re_X509_tbs (X509 * x, unsigned char ** pp)
i2d_RSA_PUBKEY()
int i2d_RSA_PUBKEY (RSA * a, unsigned char ** pp)
Referenced by i2d_RSA_PUBKEY_bio(), and i2d_RSA_PUBKEY_fp().
i2d_RSA_PUBKEY_bio()
int i2d_RSA_PUBKEY_bio (BIO * bp, RSA * rsa)
Definition at line 259 of file x_all.c.
References ASN1_i2d_bio_of, and i2d_RSA_PUBKEY().
i2d_RSA_PUBKEY_fp()
int i2d_RSA_PUBKEY_fp (FILE * fp, RSA * rsa)
Definition at line 228 of file x_all.c.
References ASN1_i2d_fp(), I2D_OF, and i2d_RSA_PUBKEY().
i2d_RSAPrivateKey_bio()
int i2d_RSAPrivateKey_bio (BIO * bp, RSA * rsa)
Definition at line 239 of file x_all.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_RSAPrivateKey_fp()
int i2d_RSAPrivateKey_fp (FILE * fp, RSA * rsa)
Definition at line 206 of file x_all.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
i2d_RSAPublicKey_bio()
int i2d_RSAPublicKey_bio (BIO * bp, RSA * rsa)
Definition at line 254 of file x_all.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_RSAPublicKey_fp()
int i2d_RSAPublicKey_fp (FILE * fp, RSA * rsa)
Definition at line 223 of file x_all.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
i2d_X509_AUX()
int i2d_X509_AUX (X509 * a, unsigned char ** pp)
i2d_X509_bio()
int i2d_X509_bio (BIO * bp, X509 * x509)
Definition at line 127 of file x_all.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_X509_CRL_bio()
int i2d_X509_CRL_bio (BIO * bp, X509_CRL * crl)
Definition at line 149 of file x_all.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_X509_CRL_fp()
int i2d_X509_CRL_fp (FILE * fp, X509_CRL * crl)
Definition at line 138 of file x_all.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
i2d_X509_fp()
int i2d_X509_fp (FILE * fp, X509 * x509)
Definition at line 116 of file x_all.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
i2d_X509_REQ_bio()
int i2d_X509_REQ_bio (BIO * bp, X509_REQ * req)
Definition at line 193 of file x_all.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_X509_REQ_fp()
int i2d_X509_REQ_fp (FILE * fp, X509_REQ * req)
Definition at line 182 of file x_all.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
NETSCAPE_SPKI_b64_decode()
NETSCAPE_SPKI* NETSCAPE_SPKI_b64_decode (const char * str, int len)
Definition at line 30 of file x509spki.c.
References ERR_R_MALLOC_FAILURE, EVP_DecodeBlock(), NULL, OPENSSL_free, OPENSSL_malloc, X509_F_NETSCAPE_SPKI_B64_DECODE, X509_R_BASE64_DECODE_ERROR, and X509err.
NETSCAPE_SPKI_b64_encode()
char* NETSCAPE_SPKI_b64_encode (NETSCAPE_SPKI * x)
Definition at line 56 of file x509spki.c.
References ERR_R_MALLOC_FAILURE, EVP_EncodeBlock(), NULL, OPENSSL_free, OPENSSL_malloc, X509_F_NETSCAPE_SPKI_B64_ENCODE, and X509err.
NETSCAPE_SPKI_get_pubkey()
EVP_PKEY* NETSCAPE_SPKI_get_pubkey (NETSCAPE_SPKI * x)
Definition at line 21 of file x509spki.c.
References NULL, NETSCAPE_SPKAC::pubkey, NETSCAPE_SPKI::spkac, and X509_PUBKEY_get().
NETSCAPE_SPKI_print()
int NETSCAPE_SPKI_print (BIO * out, NETSCAPE_SPKI * spki)
Definition at line 20 of file t_spki.c.
NETSCAPE_SPKI_set_pubkey()
int NETSCAPE_SPKI_set_pubkey (NETSCAPE_SPKI * x, EVP_PKEY * pkey)
Definition at line 14 of file x509spki.c.
References NULL, NETSCAPE_SPKAC::pubkey, NETSCAPE_SPKI::spkac, and X509_PUBKEY_set().
NETSCAPE_SPKI_sign()
int NETSCAPE_SPKI_sign (NETSCAPE_SPKI * x, EVP_PKEY * pkey, const EVP_MD * md)
Definition at line 104 of file x_all.c.
NETSCAPE_SPKI_verify()
int NETSCAPE_SPKI_verify (NETSCAPE_SPKI * a, EVP_PKEY * r)
Definition at line 37 of file x_all.c.
References ASN1_ITEM_rptr, ASN1_item_verify(), NETSCAPE_SPKI::sig_algor, NETSCAPE_SPKI::signature, and NETSCAPE_SPKI::spkac.
PKCS5_pbe2_set()
X509_ALGOR* PKCS5_pbe2_set (const EVP_CIPHER * cipher, int iter, unsigned char * salt, int saltlen)
Referenced by PKCS12_pack_p7encdata().
PKCS5_pbe2_set_iv()
X509_ALGOR* PKCS5_pbe2_set_iv (const EVP_CIPHER * cipher, int iter, unsigned char * salt, int saltlen, unsigned char * aiv, int prf_nid)
PKCS5_pbe2_set_scrypt()
X509_ALGOR* PKCS5_pbe2_set_scrypt (const EVP_CIPHER * cipher, const unsigned char * salt, int saltlen, unsigned char * aiv, uint64_t N, uint64_t r, uint64_t p)
Definition at line 48 of file p5_scrypt.c.
PKCS5_pbe_set()
X509_ALGOR* PKCS5_pbe_set (int alg, int iter, const unsigned char * salt, int saltlen)
Referenced by PKCS12_pack_p7encdata().
PKCS5_pbe_set0_algor()
int PKCS5_pbe_set0_algor (X509_ALGOR * algor, int alg, int iter, const unsigned char * salt, int saltlen)
PKCS5_pbkdf2_set()
X509_ALGOR* PKCS5_pbkdf2_set (int iter, unsigned char * salt, int saltlen, int prf_nid, int keylen)
PKCS8_pkey_add1_attr_by_NID()
int PKCS8_pkey_add1_attr_by_NID (PKCS8_PRIV_KEY_INFO * p8, int nid, int type, const unsigned char * bytes, int len)
Referenced by PKCS8_add_keyusage().
PKCS8_pkey_get0()
int PKCS8_pkey_get0 (const ASN1_OBJECT ** ppkalg, const unsigned char ** pk, int * ppklen, const X509_ALGOR ** pa, const PKCS8_PRIV_KEY_INFO * p8)
Referenced by EVP_PKCS82PKEY().
PKCS8_pkey_set0()
int PKCS8_pkey_set0 (PKCS8_PRIV_KEY_INFO * priv, ASN1_OBJECT * aobj, int version, int ptype, void * pval, unsigned char * penc, int penclen)
STACK_OF() [1/6]
typedef STACK_OF (X509_ALGOR)
Definition at line 35 of file pk7_attr.c.
References ASN1_item_d2i(), ASN1_ITEM_rptr, NID_SMIMECapabilities, NULL, PKCS7_get_signed_attribute(), ASN1_TYPE::sequence, STACK_OF(), ASN1_TYPE::type, V_ASN1_SEQUENCE, and ASN1_TYPE::value.
Referenced by STACK_OF().
STACK_OF() [2/6]
typedef STACK_OF (X509_EXTENSION)
Definition at line 132 of file ts_req_utils.c.
STACK_OF() [3/6]
STACK_OF (ASN1_OBJECT)
STACK_OF() [4/6]
STACK_OF (X509_REVOKED)
Definition at line 115 of file x509cset.c.
STACK_OF() [5/6]
STACK_OF (X509)
Definition at line 478 of file cms_lib.c.
References BIO_free(), BIO_new_file(), CMS_CertificateChoices::certificate, PKCS7::d, CMS_CertificateChoices::d, ERR_R_MALLOC_FAILURE, PKCS7_ISSUER_AND_SERIAL::issuer, PKCS7_SIGNER_INFO::issuer_and_serial, NULL, PKCS7_F_PKCS7_GET0_SIGNERS, PKCS7_NOINTERN, PKCS7_R_INVALID_NULL_POINTER, PKCS7_R_NO_SIGNERS, PKCS7_R_SIGNER_CERTIFICATE_NOT_FOUND, PKCS7_R_WRONG_CONTENT_TYPE, PKCS7_type_is_signed, PKCS7err, PKCS7_ISSUER_AND_SERIAL::serial, PKCS7::sign, STACK_OF(), TS_F_TS_CONF_LOAD_CERTS, TS_R_CANNOT_LOAD_CERT, TSerr, CMS_CertificateChoices::type, X509_INFO::x509, X509_find_by_issuer_and_serial(), X509_INFO_free(), and X509_up_ref().
Referenced by CMS_add0_CertificateChoices(), CMS_add0_RevocationInfoChoice(), cms_DigestAlgorithm_find_ctx(), OCSP_resp_find(), SSL_clear_options(), SSL_CTX_set_cipher_list(), SSL_CTX_set_ssl_version(), SSL_dup(), SSL_get_shared_ciphers(), SSL_set_cipher_list(), and STACK_OF().
STACK_OF() [6/6]
STACK_OF (X509_ATTRIBUTE)
X509_add1_ext_i2d()
int X509_add1_ext_i2d (X509 * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 108 of file x509_ext.c.
References X509V3_add1_i2d().
X509_add1_reject_object()
int X509_add1_reject_object (X509 * x, const ASN1_OBJECT * obj)
X509_add1_trust_object()
int X509_add1_trust_object (X509 * x, const ASN1_OBJECT * obj)
X509_add_ext()
int X509_add_ext (X509 * x, X509_EXTENSION * ex, int loc)
Definition at line 98 of file x509_ext.c.
References NULL.
X509_ALGOR_cmp()
int X509_ALGOR_cmp (const X509_ALGOR * a, const X509_ALGOR * b)
Referenced by X509_verify().
X509_ALGOR_dup()
X509_ALGOR* X509_ALGOR_dup (X509_ALGOR * xn)
Referenced by TS_MSG_IMPRINT_set_algo().
X509_ALGOR_get0()
void X509_ALGOR_get0 (const ASN1_OBJECT ** paobj, int * pptype, const void ** ppval, const X509_ALGOR * algor)
Referenced by cms_DigestAlgorithm_find_ctx(), and cms_DigestAlgorithm_init_bio().
X509_ALGOR_set0()
int X509_ALGOR_set0 (X509_ALGOR * alg, ASN1_OBJECT * aobj, int ptype, void * pval)
Referenced by ASN1_item_sign_ctx(), CMS_add_simple_smimecap(), and PKCS12_setup_mac().
X509_ALGOR_set_md()
void X509_ALGOR_set_md (X509_ALGOR * alg, const EVP_MD * md)
X509_alias_get0()
unsigned char* X509_alias_get0 (X509 * x, int * len)
Referenced by PKCS12_add_cert().
X509_alias_set1()
int X509_alias_set1 (X509 * x, const unsigned char * name, int len)
X509_ATTRIBUTE_count()
int X509_ATTRIBUTE_count (const X509_ATTRIBUTE * attr)
Definition at line 296 of file x509_att.c.
References NULL.
Referenced by print_attribs(), X509_REQ_print_ex(), and X509at_get0_data_by_OBJ().
X509_ATTRIBUTE_create()
X509_ATTRIBUTE* X509_ATTRIBUTE_create (int nid, int atrtype, void * value)
X509_ATTRIBUTE_create_by_NID()
X509_ATTRIBUTE* X509_ATTRIBUTE_create_by_NID (X509_ATTRIBUTE ** attr, int nid, int atrtype, const void * data, int len)
Definition at line 168 of file x509_att.c.
References obj.
X509_ATTRIBUTE_create_by_OBJ()
X509_ATTRIBUTE* X509_ATTRIBUTE_create_by_OBJ (X509_ATTRIBUTE ** attr, const ASN1_OBJECT * obj, int atrtype, const void * data, int len)
Definition at line 186 of file x509_att.c.
Referenced by X509_ATTRIBUTE_create_by_txt().
X509_ATTRIBUTE_create_by_txt()
X509_ATTRIBUTE* X509_ATTRIBUTE_create_by_txt (X509_ATTRIBUTE ** attr, const char * atrname, int type, const unsigned char * bytes, int len)
Definition at line 216 of file x509_att.c.
References ASN1_OBJECT_free(), ERR_add_error_data(), NULL, obj, OBJ_txt2obj(), X509_ATTRIBUTE_create_by_OBJ(), X509_F_X509_ATTRIBUTE_CREATE_BY_TXT, X509_R_INVALID_FIELD_NAME, and X509err.
X509_ATTRIBUTE_dup()
X509_ATTRIBUTE* X509_ATTRIBUTE_dup (X509_ATTRIBUTE * xa)
Referenced by PKCS7_set_attributes(), PKCS7_set_signed_attributes(), and STACK_OF().
X509_ATTRIBUTE_get0_data()
void* X509_ATTRIBUTE_get0_data (X509_ATTRIBUTE * attr, int idx, int atrtype, void * data)
Definition at line 310 of file x509_att.c.
Referenced by X509at_get0_data_by_OBJ().
X509_ATTRIBUTE_get0_object()
ASN1_OBJECT* X509_ATTRIBUTE_get0_object (X509_ATTRIBUTE * attr)
Definition at line 303 of file x509_att.c.
References NULL.
Referenced by print_attribs(), and X509_REQ_print_ex().
X509_ATTRIBUTE_get0_type()
ASN1_TYPE* X509_ATTRIBUTE_get0_type (X509_ATTRIBUTE * attr, int idx)
Definition at line 324 of file x509_att.c.
Referenced by PKCS12_get_attr_gen(), print_attribs(), and X509_REQ_print_ex().
X509_ATTRIBUTE_set1_data()
int X509_ATTRIBUTE_set1_data (X509_ATTRIBUTE * attr, int attrtype, const void * data, int len)
Definition at line 245 of file x509_att.c.
References ASN1_STRING_free(), ASN1_STRING_set(), ASN1_STRING_set_by_NID(), ASN1_STRING_type_new(), ASN1_TYPE_set(), ASN1_TYPE_set1(), ERR_R_ASN1_LIB, ERR_R_MALLOC_FAILURE, MBSTRING_FLAG, NULL, OBJ_obj2nid(), X509_F_X509_ATTRIBUTE_SET1_DATA, and X509err.
X509_ATTRIBUTE_set1_object()
int X509_ATTRIBUTE_set1_object (X509_ATTRIBUTE * attr, const ASN1_OBJECT * obj)
Definition at line 236 of file x509_att.c.
References ASN1_OBJECT_free(), NULL, and OBJ_dup().
X509_aux_print()
int X509_aux_print (BIO * out, X509 * x, int indent)
Definition at line 324 of file t_x509.c.
X509_certificate_type()
int X509_certificate_type (const X509 * x, const EVP_PKEY * pubkey)
Definition at line 16 of file x509type.c.
X509_chain_check_suiteb()
int X509_chain_check_suiteb (int * perror_depth, X509 * x, STACK_OF(X509) * chain, unsigned long flags)
Definition at line 347 of file x509_cmp.c.
References flags, NULL, X509_get0_pubkey(), X509_V_FLAG_SUITEB_128_LOS, and X509_V_OK.
X509_check_private_key()
int X509_check_private_key (const X509 * x509, const EVP_PKEY * pkey)
Definition at line 279 of file x509_cmp.c.
Referenced by OCSP_basic_sign(), OCSP_request_sign(), SSL_check_private_key(), and SSL_CTX_check_private_key().
X509_check_trust()
int X509_check_trust (X509 * x, int id, int flags)
Definition at line 65 of file x509_trs.c.
X509_cmp()
int X509_cmp (const X509 * a, const X509 * b)
Definition at line 135 of file x509_cmp.c.
References SHA_DIGEST_LENGTH, and X509_check_purpose().
X509_cmp_current_time()
int X509_cmp_current_time (const ASN1_TIME * s)
Definition at line 1750 of file x509_vfy.c.
References NULL, and X509_cmp_time().
X509_cmp_time()
int X509_cmp_time (const ASN1_TIME * s, time_t * t)
Definition at line 1755 of file x509_vfy.c.
References if(), NULL, V_ASN1_UTCTIME, and X509_time_adj().
Referenced by x509_check_cert_time(), and X509_cmp_current_time().
X509_CRL_add0_revoked()
int X509_CRL_add0_revoked (X509_CRL * crl, X509_REVOKED * rev)
X509_CRL_add1_ext_i2d()
int X509_CRL_add1_ext_i2d (X509_CRL * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 56 of file x509_ext.c.
References X509V3_add1_i2d().
X509_CRL_add_ext()
int X509_CRL_add_ext (X509_CRL * x, X509_EXTENSION * ex, int loc)
Definition at line 62 of file x509_ext.c.
References NULL.
X509_CRL_check_suiteb()
int X509_CRL_check_suiteb (X509_CRL * crl, EVP_PKEY * pk, unsigned long flags)
Definition at line 422 of file x509_cmp.c.
References OBJ_obj2nid(), X509_V_FLAG_SUITEB_128_LOS, and X509_V_OK.
X509_CRL_cmp()
int X509_CRL_cmp (const X509_CRL * a, const X509_CRL * b)
Definition at line 73 of file x509_cmp.c.
References X509_NAME_cmp().
X509_CRL_delete_ext()
X509_EXTENSION* X509_CRL_delete_ext (X509_CRL * x, int loc)
Definition at line 46 of file x509_ext.c.
References X509v3_delete_ext().
X509_CRL_diff()
X509_CRL* X509_CRL_diff (X509_CRL * base, X509_CRL * newer, EVP_PKEY * skey, const EVP_MD * md, unsigned int flags)
Definition at line 1938 of file x509_vfy.c.
X509_CRL_digest()
int X509_CRL_digest (const X509_CRL * data, const EVP_MD * type, unsigned char * md, unsigned int * len)
Definition at line 377 of file x_all.c.
X509_CRL_dup()
X509_CRL* X509_CRL_dup (X509_CRL * crl)
X509_CRL_get0_by_cert()
int X509_CRL_get0_by_cert (X509_CRL * crl, X509_REVOKED ** ret, X509 * x)
X509_CRL_get0_by_serial()
int X509_CRL_get0_by_serial (X509_CRL * crl, X509_REVOKED ** ret, ASN1_INTEGER * serial)
X509_CRL_get0_lastUpdate()
const ASN1_TIME* X509_CRL_get0_lastUpdate (const X509_CRL * crl)
Definition at line 83 of file x509cset.c.
X509_CRL_get0_nextUpdate()
const ASN1_TIME* X509_CRL_get0_nextUpdate (const X509_CRL * crl)
Definition at line 88 of file x509cset.c.
X509_CRL_get0_signature()
void X509_CRL_get0_signature (const X509_CRL * crl, const ASN1_BIT_STRING ** psig, const X509_ALGOR ** palg)
Definition at line 120 of file x509cset.c.
References NULL.
X509_CRL_get_ext()
X509_EXTENSION* X509_CRL_get_ext (const X509_CRL * x, int loc)
Definition at line 41 of file x509_ext.c.
References X509v3_get_ext().
X509_CRL_get_ext_by_critical()
int X509_CRL_get_ext_by_critical (const X509_CRL * x, int crit, int lastpos)
Definition at line 36 of file x509_ext.c.
References X509v3_get_ext_by_critical().
X509_CRL_get_ext_by_NID()
int X509_CRL_get_ext_by_NID (const X509_CRL * x, int nid, int lastpos)
Definition at line 25 of file x509_ext.c.
References X509v3_get_ext_by_NID().
X509_CRL_get_ext_by_OBJ()
int X509_CRL_get_ext_by_OBJ (const X509_CRL * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 30 of file x509_ext.c.
References X509v3_get_ext_by_OBJ().
X509_CRL_get_ext_count()
int X509_CRL_get_ext_count (const X509_CRL * x)
Definition at line 20 of file x509_ext.c.
References X509v3_get_ext_count().
X509_CRL_get_ext_d2i()
void* X509_CRL_get_ext_d2i (const X509_CRL * x, int nid, int * crit, int * idx)
Definition at line 51 of file x509_ext.c.
X509_CRL_get_issuer()
X509_NAME* X509_CRL_get_issuer (const X509_CRL * crl)
Definition at line 105 of file x509cset.c.
X509_CRL_get_meth_data()
void* X509_CRL_get_meth_data (X509_CRL * crl)
X509_CRL_get_signature_nid()
int X509_CRL_get_signature_nid (const X509_CRL * crl)
Definition at line 129 of file x509cset.c.
References OBJ_obj2nid().
X509_CRL_get_version()
long X509_CRL_get_version (const X509_CRL * crl)
Definition at line 78 of file x509cset.c.
References ASN1_INTEGER_get().
X509_CRL_http_nbio()
int X509_CRL_http_nbio (OCSP_REQ_CTX * rctx, X509_CRL ** pcrl)
Definition at line 96 of file x_all.c.
References ASN1_ITEM_rptr, and OCSP_REQ_CTX_nbio_d2i().
X509_CRL_match()
int X509_CRL_match (const X509_CRL * a, const X509_CRL * b)
Definition at line 78 of file x509_cmp.c.
X509_CRL_METHOD_free()
void X509_CRL_METHOD_free (X509_CRL_METHOD * m)
X509_CRL_METHOD_new()
X509_CRL_METHOD* X509_CRL_METHOD_new (int(*)(X509_CRL *crl) crl_init, int(*)(X509_CRL *crl) crl_free, int(*)(X509_CRL *crl, X509_REVOKED **ret, ASN1_INTEGER *ser, X509_NAME *issuer) crl_lookup, int(*)(X509_CRL *crl, EVP_PKEY *pk) crl_verify)
X509_CRL_print()
int X509_CRL_print (BIO * bp, X509_CRL * x)
Definition at line 35 of file t_crl.c.
X509_CRL_print_fp()
int X509_CRL_print_fp (FILE * bp, X509_CRL * x)
Definition at line 19 of file t_crl.c.
X509_CRL_set1_lastUpdate()
int X509_CRL_set1_lastUpdate (X509_CRL * x, const ASN1_TIME * tm)
Definition at line 36 of file x509cset.c.
References NULL, and x509_set1_time().
X509_CRL_set1_nextUpdate()
int X509_CRL_set1_nextUpdate (X509_CRL * x, const ASN1_TIME * tm)
Definition at line 43 of file x509cset.c.
References NULL, and x509_set1_time().
X509_CRL_set_default_method()
void X509_CRL_set_default_method (const X509_CRL_METHOD * meth)
X509_CRL_set_issuer_name()
int X509_CRL_set_issuer_name (X509_CRL * x, X509_NAME * name)
Definition at line 29 of file x509cset.c.
References NULL, and X509_NAME_set().
X509_CRL_set_meth_data()
void X509_CRL_set_meth_data (X509_CRL * crl, void * dat)
X509_CRL_set_version()
int X509_CRL_set_version (X509_CRL * x, long version)
Definition at line 18 of file x509cset.c.
References ASN1_INTEGER_set(), and NULL.
X509_CRL_sign()
int X509_CRL_sign (X509_CRL * x, EVP_PKEY * pkey, const EVP_MD * md)
Definition at line 80 of file x_all.c.
X509_CRL_sign_ctx()
int X509_CRL_sign_ctx (X509_CRL * x, EVP_MD_CTX * ctx)
Definition at line 87 of file x_all.c.
References ASN1_ITEM_rptr, and ASN1_item_sign_ctx().
X509_CRL_sort()
int X509_CRL_sort (X509_CRL * crl)
Definition at line 50 of file x509cset.c.
X509_CRL_up_ref()
int X509_CRL_up_ref (X509_CRL * crl)
Definition at line 66 of file x509cset.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by CMS_add1_crl(), PKCS7_add_crl(), STACK_OF(), and X509_OBJECT_up_ref_count().
X509_CRL_verify()
int X509_CRL_verify (X509_CRL * a, EVP_PKEY * r)
X509_delete_ext()
X509_EXTENSION* X509_delete_ext (X509 * x, int loc)
Definition at line 93 of file x509_ext.c.
References X509v3_delete_ext().
X509_digest()
int X509_digest (const X509 * data, const EVP_MD * type, unsigned char * md, unsigned int * len)
Definition at line 363 of file x_all.c.
X509_dup()
X509* X509_dup (X509 * x509)
X509_EXTENSION_create_by_NID()
X509_EXTENSION* X509_EXTENSION_create_by_NID (X509_EXTENSION ** ex, int nid, int crit, ASN1_OCTET_STRING * data)
Definition at line 135 of file x509_v3.c.
References obj.
X509_EXTENSION_create_by_OBJ()
X509_EXTENSION* X509_EXTENSION_create_by_OBJ (X509_EXTENSION ** ex, const ASN1_OBJECT * obj, int crit, ASN1_OCTET_STRING * data)
Definition at line 153 of file x509_v3.c.
X509_EXTENSION_dup()
X509_EXTENSION* X509_EXTENSION_dup (X509_EXTENSION * ex)
Referenced by STACK_OF().
X509_EXTENSION_get_critical()
int X509_EXTENSION_get_critical (const X509_EXTENSION * ex)
Definition at line 227 of file x509_v3.c.
References NULL.
Referenced by TS_ext_print_bio(), and X509_REQ_print_ex().
X509_EXTENSION_get_data()
ASN1_OCTET_STRING* X509_EXTENSION_get_data (X509_EXTENSION * ne)
Definition at line 220 of file x509_v3.c.
References NULL.
Referenced by OCSP_check_nonce(), TS_ext_print_bio(), X509_REQ_print_ex(), and X509V3_EXT_d2i().
X509_EXTENSION_get_object()
ASN1_OBJECT* X509_EXTENSION_get_object (X509_EXTENSION * ex)
Definition at line 213 of file x509_v3.c.
References NULL.
Referenced by TS_ext_print_bio(), X509_REQ_print_ex(), X509_supported_extension(), and X509V3_EXT_get().
X509_EXTENSION_set_critical()
int X509_EXTENSION_set_critical (X509_EXTENSION * ex, int crit)
Definition at line 193 of file x509_v3.c.
References NULL.
X509_EXTENSION_set_data()
int X509_EXTENSION_set_data (X509_EXTENSION * ex, ASN1_OCTET_STRING * data)
Definition at line 201 of file x509_v3.c.
References ASN1_OCTET_STRING_set(), and NULL.
X509_EXTENSION_set_object()
int X509_EXTENSION_set_object (X509_EXTENSION * ex, const ASN1_OBJECT * obj)
Definition at line 184 of file x509_v3.c.
References ASN1_OBJECT_free(), NULL, and OBJ_dup().
X509_find_by_issuer_and_serial()
X509* X509_find_by_issuer_and_serial (STACK_OF(X509) * sk, X509_NAME * name, ASN1_INTEGER * serial)
Definition at line 232 of file x509_cmp.c.
References NULL, and X509_issuer_and_serial_cmp().
Referenced by PKCS7_cert_from_signer_info(), and STACK_OF().
X509_find_by_subject()
X509* X509_find_by_subject (STACK_OF(X509) * sk, X509_NAME * name)
Definition at line 252 of file x509_cmp.c.
References NULL, X509_get_subject_name(), and X509_NAME_cmp().
X509_get0_notAfter()
const ASN1_TIME* X509_get0_notAfter (const X509 * x)
Definition at line 117 of file x509_set.c.
Referenced by verify_callback().
X509_get0_notBefore()
const ASN1_TIME* X509_get0_notBefore (const X509 * x)
Definition at line 112 of file x509_set.c.
Referenced by verify_callback(), and x509_check_cert_time().
X509_get0_pubkey()
EVP_PKEY* X509_get0_pubkey (const X509 * x)
Definition at line 265 of file x509_cmp.c.
References NULL, and X509_PUBKEY_get0().
Referenced by CMS_add1_recipient_cert(), PKCS7_signatureVerify(), SCT_validate(), ssl_cert_type(), and X509_chain_check_suiteb().
X509_get0_pubkey_bitstr()
ASN1_BIT_STRING* X509_get0_pubkey_bitstr (const X509 * x)
Referenced by OCSP_cert_to_id(), and X509_ocspid_print().
X509_get0_serialNumber()
const ASN1_INTEGER* X509_get0_serialNumber (const X509 * x)
Definition at line 110 of file x509_cmp.c.
Referenced by OCSP_cert_to_id().
X509_get0_signature()
void X509_get0_signature (const ASN1_BIT_STRING ** psig, const X509_ALGOR ** palg, const X509 * x)
X509_get0_tbs_sigalg()
const X509_ALGOR* X509_get0_tbs_sigalg (const X509 * x)
Definition at line 156 of file x509_set.c.
X509_get0_uids()
void X509_get0_uids (const X509 * x, const ASN1_BIT_STRING ** piuid, const ASN1_BIT_STRING ** psuid)
Definition at line 147 of file x509_set.c.
References NULL.
X509_get_default_cert_area()
const char* X509_get_default_cert_area (void)
Definition at line 20 of file x509_def.c.
References X509_CERT_AREA.
Referenced by CONF_get1_default_config_file().
X509_get_default_cert_dir()
const char* X509_get_default_cert_dir (void)
Definition at line 25 of file x509_def.c.
References X509_CERT_DIR.
X509_get_default_cert_dir_env()
const char* X509_get_default_cert_dir_env (void)
Definition at line 35 of file x509_def.c.
References X509_CERT_DIR_EVP.
X509_get_default_cert_file()
const char* X509_get_default_cert_file (void)
Definition at line 30 of file x509_def.c.
References X509_CERT_FILE.
X509_get_default_cert_file_env()
const char* X509_get_default_cert_file_env (void)
Definition at line 40 of file x509_def.c.
References X509_CERT_FILE_EVP.
X509_get_default_private_dir()
const char* X509_get_default_private_dir (void)
Definition at line 15 of file x509_def.c.
References X509_PRIVATE_DIR.
X509_get_ex_data()
void* X509_get_ex_data (X509 * r, int idx)
X509_get_ext()
X509_EXTENSION* X509_get_ext (const X509 * x, int loc)
Definition at line 88 of file x509_ext.c.
References X509v3_get_ext().
X509_get_ext_by_critical()
int X509_get_ext_by_critical (const X509 * x, int crit, int lastpos)
Definition at line 82 of file x509_ext.c.
References X509v3_get_ext_by_critical().
X509_get_ext_by_NID()
int X509_get_ext_by_NID (const X509 * x, int nid, int lastpos)
Definition at line 72 of file x509_ext.c.
References X509v3_get_ext_by_NID().
X509_get_ext_by_OBJ()
int X509_get_ext_by_OBJ (const X509 * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 77 of file x509_ext.c.
References X509v3_get_ext_by_OBJ().
X509_get_ext_count()
int X509_get_ext_count (const X509 * x)
Definition at line 67 of file x509_ext.c.
References X509v3_get_ext_count().
X509_get_ext_d2i()
void* X509_get_ext_d2i (const X509 * x, int nid, int * crit, int * idx)
Definition at line 103 of file x509_ext.c.
X509_get_issuer_name()
X509_NAME* X509_get_issuer_name (const X509 * a)
Definition at line 83 of file x509_cmp.c.
Referenced by OCSP_cert_to_id(), verify_callback(), X509_check_akid(), and X509_check_issued().
X509_get_pathlen()
long X509_get_pathlen (X509 * x)
Definition at line 849 of file v3_purp.c.
References EXFLAG_BCONS, and X509_check_purpose().
X509_get_pubkey()
EVP_PKEY* X509_get_pubkey (X509 * x)
Definition at line 272 of file x509_cmp.c.
References NULL, and X509_PUBKEY_get().
Referenced by CMS_SignerInfo_set1_signer_cert().
X509_get_pubkey_parameters()
int X509_get_pubkey_parameters (EVP_PKEY * pkey, STACK_OF(X509) * chain)
Definition at line 1901 of file x509_vfy.c.
X509_get_serialNumber()
ASN1_INTEGER* X509_get_serialNumber (X509 * x)
Definition at line 105 of file x509_cmp.c.
Referenced by X509_check_akid().
X509_get_signature_nid()
int X509_get_signature_nid (const X509 * x)
X509_get_signature_type()
int X509_get_signature_type (const X509 * x)
Definition at line 132 of file x509_set.c.
References EVP_PKEY_type(), and OBJ_obj2nid().
X509_get_subject_name()
X509_NAME* X509_get_subject_name (const X509 * a)
Definition at line 100 of file x509_cmp.c.
Referenced by OCSP_cert_to_id(), OCSP_request_sign(), verify_callback(), X509_check_issued(), X509_find_by_subject(), and X509_ocspid_print().
X509_get_version()
long X509_get_version (const X509 * x)
Definition at line 107 of file x509_set.c.
References ASN1_INTEGER_get().
X509_get_X509_PUBKEY()
X509_PUBKEY* X509_get_X509_PUBKEY (const X509 * x)
Definition at line 137 of file x509_set.c.
Referenced by SCT_CTX_set1_issuer().
X509_getm_notAfter()
ASN1_TIME* X509_getm_notAfter (const X509 * x)
Definition at line 127 of file x509_set.c.
Referenced by set_cert_times().
X509_getm_notBefore()
ASN1_TIME* X509_getm_notBefore (const X509 * x)
Definition at line 122 of file x509_set.c.
Referenced by set_cert_times().
X509_gmtime_adj()
ASN1_TIME* X509_gmtime_adj (ASN1_TIME * s, long adj)
Definition at line 1872 of file x509_vfy.c.
References NULL, and X509_time_adj().
Referenced by OCSP_basic_sign(), PKCS7_add0_attrib_signing_time(), and set_cert_times().
X509_http_nbio()
int X509_http_nbio (OCSP_REQ_CTX * rctx, X509 ** pcert)
Definition at line 60 of file x_all.c.
References ASN1_ITEM_rptr, and OCSP_REQ_CTX_nbio_d2i().
X509_INFO_free()
void X509_INFO_free (X509_INFO * a)
Definition at line 29 of file x_info.c.
References X509_INFO::crl, X509_INFO::enc_data, NULL, OPENSSL_free, X509_INFO::x509, X509_PKEY_free(), and X509_INFO::x_pkey.
Referenced by STACK_OF(), and X509_load_cert_crl_file().
X509_INFO_new()
X509_INFO* X509_INFO_new (void)
Definition at line 16 of file x_info.c.
X509_issuer_and_serial_cmp()
int X509_issuer_and_serial_cmp (const X509 * a, const X509 * b)
Definition at line 19 of file x509_cmp.c.
References ASN1_INTEGER_cmp(), and X509_NAME_cmp().
Referenced by X509_find_by_issuer_and_serial().
X509_issuer_and_serial_hash()
unsigned long X509_issuer_and_serial_hash (X509 * a)
Definition at line 33 of file x509_cmp.c.
X509_issuer_name_cmp()
int X509_issuer_name_cmp (const X509 * a, const X509 * b)
Definition at line 63 of file x509_cmp.c.
References X509_NAME_cmp().
X509_issuer_name_hash()
unsigned long X509_issuer_name_hash (X509 * a)
Definition at line 88 of file x509_cmp.c.
References X509_NAME_hash().
X509_issuer_name_hash_old()
unsigned long X509_issuer_name_hash_old (X509 * a)
Definition at line 94 of file x509_cmp.c.
References X509_NAME_hash_old().
X509_keyid_get0()
unsigned char* X509_keyid_get0 (X509 * x, int * len)
Referenced by PKCS12_add_cert().
X509_keyid_set1()
int X509_keyid_set1 (X509 * x, const unsigned char * id, int len)
X509_NAME_add_entry()
int X509_NAME_add_entry (X509_NAME * name, const X509_NAME_ENTRY * ne, int loc, int set)
Definition at line 181 of file x509name.c.
References ERR_R_MALLOC_FAILURE, NULL, STACK_OF, X509_F_X509_NAME_ADD_ENTRY, X509_NAME_ENTRY_dup(), and X509err.
X509_NAME_add_entry_by_NID()
int X509_NAME_add_entry_by_NID (X509_NAME * name, int nid, int type, const unsigned char * bytes, int len, int loc, int set)
Definition at line 149 of file x509name.c.
Referenced by parse_name().
X509_NAME_add_entry_by_OBJ()
int X509_NAME_add_entry_by_OBJ (X509_NAME * name, const ASN1_OBJECT * obj, int type, const unsigned char * bytes, int len, int loc, int set)
Definition at line 134 of file x509name.c.
X509_NAME_add_entry_by_txt()
int X509_NAME_add_entry_by_txt (X509_NAME * name, const char * field, int type, const unsigned char * bytes, int len, int loc, int set)
Definition at line 163 of file x509name.c.
Referenced by X509V3_NAME_from_section().
X509_NAME_cmp()
int X509_NAME_cmp (const X509_NAME * a, const X509_NAME * b)
Definition at line 157 of file x509_cmp.c.
Referenced by X509_check_akid(), X509_check_issued(), X509_CRL_cmp(), X509_find_by_subject(), X509_issuer_and_serial_cmp(), X509_issuer_name_cmp(), and X509_subject_name_cmp().
X509_NAME_delete_entry()
X509_NAME_ENTRY* X509_NAME_delete_entry (X509_NAME * name, int loc)
Definition at line 94 of file x509name.c.
X509_NAME_digest()
int X509_NAME_digest (const X509_NAME * data, const EVP_MD * type, unsigned char * md, unsigned int * len)
Definition at line 398 of file x_all.c.
X509_NAME_dup()
X509_NAME* X509_NAME_dup (X509_NAME * xn)
Referenced by OCSP_url_svcloc_new(), and X509_NAME_set().
X509_NAME_entry_count()
int X509_NAME_entry_count (const X509_NAME * name)
Definition at line 47 of file x509name.c.
References NULL.
X509_NAME_ENTRY_create_by_NID()
X509_NAME_ENTRY* X509_NAME_ENTRY_create_by_NID (X509_NAME_ENTRY ** ne, int nid, int type, const unsigned char * bytes, int len)
Definition at line 261 of file x509name.c.
References ASN1_OBJECT_free(), NULL, obj, OBJ_nid2obj(), X509_F_X509_NAME_ENTRY_CREATE_BY_NID, X509_NAME_ENTRY_create_by_OBJ(), X509_R_UNKNOWN_NID, and X509err.
X509_NAME_ENTRY_create_by_OBJ()
X509_NAME_ENTRY* X509_NAME_ENTRY_create_by_OBJ (X509_NAME_ENTRY ** ne, const ASN1_OBJECT * obj, int type, const unsigned char * bytes, int len)
Definition at line 279 of file x509name.c.
Referenced by X509_NAME_ENTRY_create_by_NID(), and X509_NAME_ENTRY_create_by_txt().
X509_NAME_ENTRY_create_by_txt()
X509_NAME_ENTRY* X509_NAME_ENTRY_create_by_txt (X509_NAME_ENTRY ** ne, const char * field, int type, const unsigned char * bytes, int len)
Definition at line 241 of file x509name.c.
References ASN1_OBJECT_free(), ERR_add_error_data(), NULL, obj, OBJ_txt2obj(), X509_F_X509_NAME_ENTRY_CREATE_BY_TXT, X509_NAME_ENTRY_create_by_OBJ(), X509_R_INVALID_FIELD_NAME, and X509err.
X509_NAME_ENTRY_dup()
X509_NAME_ENTRY* X509_NAME_ENTRY_dup (X509_NAME_ENTRY * ne)
Referenced by X509_NAME_add_entry().
X509_NAME_ENTRY_get_data()
ASN1_STRING* X509_NAME_ENTRY_get_data (const X509_NAME_ENTRY * ne)
Definition at line 350 of file x509name.c.
References NULL.
X509_NAME_ENTRY_get_object()
ASN1_OBJECT* X509_NAME_ENTRY_get_object (const X509_NAME_ENTRY * ne)
Definition at line 343 of file x509name.c.
References NULL.
X509_NAME_ENTRY_set()
int X509_NAME_ENTRY_set (const X509_NAME_ENTRY * ne)
Definition at line 357 of file x509name.c.
X509_NAME_ENTRY_set_data()
int X509_NAME_ENTRY_set_data (X509_NAME_ENTRY * ne, int type, const unsigned char * bytes, int len)
Definition at line 318 of file x509name.c.
References ASN1_PRINTABLE_type(), ASN1_STRING_set(), ASN1_STRING_set_by_NID(), MBSTRING_FLAG, NULL, OBJ_obj2nid(), type, V_ASN1_APP_CHOOSE, and V_ASN1_UNDEF.
X509_NAME_ENTRY_set_object()
int X509_NAME_ENTRY_set_object (X509_NAME_ENTRY * ne, const ASN1_OBJECT * obj)
Definition at line 306 of file x509name.c.
References ASN1_OBJECT_free(), ERR_R_PASSED_NULL_PARAMETER, NULL, OBJ_dup(), X509_F_X509_NAME_ENTRY_SET_OBJECT, and X509err.
X509_NAME_get0_der()
int X509_NAME_get0_der (X509_NAME * nm, const unsigned char ** pder, size_t * pderlen)
Definition at line 546 of file x_name.c.
References if(), and NULL.
X509_NAME_get_entry()
X509_NAME_ENTRY* X509_NAME_get_entry (const X509_NAME * name, int loc)
Definition at line 85 of file x509name.c.
References NULL.
X509_NAME_get_index_by_NID()
int X509_NAME_get_index_by_NID (X509_NAME * name, int nid, int lastpos)
Definition at line 54 of file x509name.c.
References NULL, obj, OBJ_nid2obj(), and X509_NAME_get_index_by_OBJ().
X509_NAME_get_index_by_OBJ()
int X509_NAME_get_index_by_OBJ (X509_NAME * name, const ASN1_OBJECT * obj, int lastpos)
Definition at line 65 of file x509name.c.
References NULL, OBJ_cmp(), and STACK_OF.
Referenced by X509_NAME_get_index_by_NID().
X509_NAME_get_text_by_NID()
int X509_NAME_get_text_by_NID (X509_NAME * name, int nid, char * buf, int len)
Definition at line 19 of file x509name.c.
X509_NAME_get_text_by_OBJ()
int X509_NAME_get_text_by_OBJ (X509_NAME * name, const ASN1_OBJECT * obj, char * buf, int len)
Definition at line 29 of file x509name.c.
X509_NAME_hash()
unsigned long X509_NAME_hash (X509_NAME * x)
Definition at line 184 of file x509_cmp.c.
Referenced by X509_issuer_name_hash(), and X509_subject_name_hash().
X509_NAME_hash_old()
unsigned long X509_NAME_hash_old (X509_NAME * x)
Definition at line 207 of file x509_cmp.c.
References EVP_MD_CTX_new().
Referenced by X509_issuer_name_hash_old(), and X509_subject_name_hash_old().
X509_NAME_oneline()
char* X509_NAME_oneline (const X509_NAME * a, char * buf, int size)
Definition at line 25 of file x509_obj.c.
X509_NAME_print()
int X509_NAME_print (BIO * bp, const X509_NAME * name, int obase)
Definition at line 490 of file x_name.c.
X509_NAME_print_ex()
int X509_NAME_print_ex (BIO * out, const X509_NAME * nm, int indent, unsigned long flags)
Definition at line 529 of file a_strex.c.
Referenced by verify_callback(), and X509_REQ_print_ex().
X509_NAME_print_ex_fp()
int X509_NAME_print_ex_fp (FILE * fp, const X509_NAME * nm, int indent, unsigned long flags)
Definition at line 538 of file a_strex.c.
References XN_FLAG_COMPAT.
X509_NAME_set()
int X509_NAME_set (X509_NAME ** xn, X509_NAME * name)
Definition at line 473 of file x_name.c.
References in, NULL, and X509_NAME_dup().
Referenced by OCSP_request_set1_name(), X509_CRL_set_issuer_name(), X509_REQ_set_subject_name(), X509_set_issuer_name(), and X509_set_subject_name().
X509_ocspid_print()
int X509_ocspid_print (BIO * bp, X509 * x)
Definition at line 218 of file t_x509.c.
References ASN1_STRING_get0_data(), ASN1_STRING_length(), BIO_printf(), EVP_Digest(), EVP_sha1(), NULL, OPENSSL_free, OPENSSL_malloc, SHA_DIGEST_LENGTH, X509_get0_pubkey_bitstr(), and X509_get_subject_name().
X509_PKEY_free()
void X509_PKEY_free (X509_PKEY * a)
Definition at line 36 of file x_pkey.c.
References X509_PKEY::dec_pkey, X509_PKEY::enc_algor, X509_PKEY::enc_pkey, EVP_PKEY_free(), X509_PKEY::key_data, X509_PKEY::key_free, NULL, and OPENSSL_free.
Referenced by X509_INFO_free().
X509_PKEY_new()
X509_PKEY* X509_PKEY_new (void)
Definition at line 16 of file x_pkey.c.
X509_print()
int X509_print (BIO * bp, X509 * x)
Definition at line 42 of file t_x509.c.
References X509_FLAG_COMPAT, X509_print_ex(), and XN_FLAG_COMPAT.
X509_print_ex()
int X509_print_ex (BIO * bp, X509 * x, unsigned long nmflag, unsigned long cflag)
Definition at line 47 of file t_x509.c.
Referenced by X509_print().
X509_print_ex_fp()
int X509_print_ex_fp (FILE * bp, X509 * x, unsigned long nmflag, unsigned long cflag)
Definition at line 25 of file t_x509.c.
Referenced by X509_print_fp().
X509_print_fp()
int X509_print_fp (FILE * bp, X509 * x)
Definition at line 20 of file t_x509.c.
References X509_FLAG_COMPAT, X509_print_ex_fp(), and XN_FLAG_COMPAT.
X509_pubkey_digest()
int X509_pubkey_digest (const X509 * data, const EVP_MD * type, unsigned char * md, unsigned int * len)
Definition at line 353 of file x_all.c.
X509_PUBKEY_get()
EVP_PKEY* X509_PUBKEY_get (X509_PUBKEY * key)
Referenced by NETSCAPE_SPKI_get_pubkey(), SCT_CTX_set1_pubkey(), X509_get_pubkey(), and X509_REQ_get_pubkey().
X509_PUBKEY_get0()
EVP_PKEY* X509_PUBKEY_get0 (X509_PUBKEY * key)
Referenced by X509_get0_pubkey(), and X509_REQ_get0_pubkey().
X509_PUBKEY_get0_param()
int X509_PUBKEY_get0_param (ASN1_OBJECT ** ppkalg, const unsigned char ** pk, int * ppklen, X509_ALGOR ** pa, X509_PUBKEY * pub)
Referenced by X509_REQ_print_ex().
X509_PUBKEY_set()
int X509_PUBKEY_set (X509_PUBKEY ** x, EVP_PKEY * pkey)
Referenced by NETSCAPE_SPKI_set_pubkey(), SCT_validate(), X509_REQ_set_pubkey(), and X509_set_pubkey().
X509_PUBKEY_set0_param()
int X509_PUBKEY_set0_param (X509_PUBKEY * pub, ASN1_OBJECT * aobj, int ptype, void * pval, unsigned char * penc, int penclen)
X509_reject_clear()
void X509_reject_clear (X509 * x)
X509_REQ_add1_attr()
int X509_REQ_add1_attr (X509_REQ * req, X509_ATTRIBUTE * attr)
Definition at line 233 of file x509_req.c.
X509_REQ_add1_attr_by_NID()
int X509_REQ_add1_attr_by_NID (X509_REQ * req, int nid, int type, const unsigned char * bytes, int len)
Definition at line 250 of file x509_req.c.
Referenced by X509_REQ_add_extensions_nid().
X509_REQ_add1_attr_by_OBJ()
int X509_REQ_add1_attr_by_OBJ (X509_REQ * req, const ASN1_OBJECT * obj, int type, const unsigned char * bytes, int len)
Definition at line 240 of file x509_req.c.
X509_REQ_add1_attr_by_txt()
int X509_REQ_add1_attr_by_txt (X509_REQ * req, const char * attrname, int type, const unsigned char * bytes, int len)
Definition at line 260 of file x509_req.c.
X509_REQ_add_extensions()
int X509_REQ_add_extensions (X509_REQ * req, STACK_OF(X509_EXTENSION) * exts)
Definition at line 200 of file x509_req.c.
References NID_ext_req, and X509_REQ_add_extensions_nid().
X509_REQ_add_extensions_nid()
int X509_REQ_add_extensions_nid (X509_REQ * req, STACK_OF(X509_EXTENSION) * exts, int nid)
Definition at line 183 of file x509_req.c.
References ASN1_item_i2d(), ASN1_ITEM_rptr, NULL, OPENSSL_free, V_ASN1_SEQUENCE, and X509_REQ_add1_attr_by_NID().
Referenced by X509_REQ_add_extensions().
X509_REQ_check_private_key()
int X509_REQ_check_private_key (X509_REQ * x509, EVP_PKEY * pkey)
Definition at line 82 of file x509_req.c.
X509_REQ_delete_attr()
X509_ATTRIBUTE* X509_REQ_delete_attr (X509_REQ * req, int loc)
Definition at line 228 of file x509_req.c.
References X509at_delete_attr().
X509_REQ_digest()
int X509_REQ_digest (const X509_REQ * data, const EVP_MD * type, unsigned char * md, unsigned int * len)
Definition at line 391 of file x_all.c.
X509_REQ_dup()
X509_REQ* X509_REQ_dup (X509_REQ * req)
X509_REQ_extension_nid()
int X509_REQ_extension_nid (int nid)
Definition at line 131 of file x509_req.c.
References nid.
Referenced by X509_REQ_print_ex().
X509_REQ_get0_pubkey()
EVP_PKEY* X509_REQ_get0_pubkey (X509_REQ * req)
Definition at line 70 of file x509_req.c.
References NULL, and X509_PUBKEY_get0().
Referenced by X509_REQ_print_ex().
X509_REQ_get0_signature()
void X509_REQ_get0_signature (const X509_REQ * req, const ASN1_BIT_STRING ** psig, const X509_ALGOR ** palg)
Definition at line 280 of file x509_req.c.
References NULL.
Referenced by X509_REQ_print_ex().
X509_REQ_get_attr()
X509_ATTRIBUTE* X509_REQ_get_attr (const X509_REQ * req, int loc)
Definition at line 223 of file x509_req.c.
References X509at_get_attr().
Referenced by X509_REQ_print_ex().
X509_REQ_get_attr_by_NID()
int X509_REQ_get_attr_by_NID (const X509_REQ * req, int nid, int lastpos)
Definition at line 212 of file x509_req.c.
References X509at_get_attr_by_NID().
X509_REQ_get_attr_by_OBJ()
int X509_REQ_get_attr_by_OBJ (const X509_REQ * req, const ASN1_OBJECT * obj, int lastpos)
Definition at line 217 of file x509_req.c.
References X509at_get_attr_by_OBJ().
X509_REQ_get_attr_count()
int X509_REQ_get_attr_count (const X509_REQ * req)
Definition at line 207 of file x509_req.c.
References X509at_get_attr_count().
Referenced by X509_REQ_print_ex().
X509_REQ_get_extension_nids()
int* X509_REQ_get_extension_nids (void)
Definition at line 143 of file x509_req.c.
X509_REQ_get_pubkey()
EVP_PKEY* X509_REQ_get_pubkey (X509_REQ * req)
Definition at line 63 of file x509_req.c.
References NULL, and X509_PUBKEY_get().
X509_REQ_get_signature_nid()
int X509_REQ_get_signature_nid (const X509_REQ * req)
Definition at line 289 of file x509_req.c.
References OBJ_obj2nid().
X509_REQ_get_subject_name()
X509_NAME* X509_REQ_get_subject_name (const X509_REQ * req)
Definition at line 275 of file x509_req.c.
Referenced by X509_REQ_print_ex().
X509_REQ_get_version()
long X509_REQ_get_version (const X509_REQ * req)
Definition at line 270 of file x509_req.c.
References ASN1_INTEGER_get().
Referenced by X509_REQ_print_ex().
X509_REQ_get_X509_PUBKEY()
X509_PUBKEY* X509_REQ_get_X509_PUBKEY (X509_REQ * req)
Definition at line 77 of file x509_req.c.
Referenced by X509_REQ_print_ex().
X509_REQ_print()
int X509_REQ_print (BIO * bp, X509_REQ * req)
Definition at line 195 of file t_req.c.
References X509_FLAG_COMPAT, X509_REQ_print_ex(), and XN_FLAG_COMPAT.
X509_REQ_print_ex()
int X509_REQ_print_ex (BIO * bp, X509_REQ * x, unsigned long nmflag, unsigned long cflag)
Definition at line 37 of file t_req.c.
References ASN1_TYPE::asn1_string, ASN1_STRING_print(), BIO_printf(), BIO_puts(), BIO_write(), ERR_print_errors(), ERR_R_BUF_LIB, EVP_PKEY_print_public(), ex, i2a_ASN1_OBJECT(), NULL, obj, OBJ_obj2nid(), STACK_OF, ASN1_TYPE::type, type, V_ASN1_IA5STRING, V_ASN1_PRINTABLESTRING, V_ASN1_T61STRING, V_ASN1_UTF8STRING, ASN1_TYPE::value, X509_ATTRIBUTE_count(), X509_ATTRIBUTE_get0_object(), X509_ATTRIBUTE_get0_type(), X509_EXTENSION_get_critical(), X509_EXTENSION_get_data(), X509_EXTENSION_get_object(), X509_F_X509_REQ_PRINT_EX, X509_FLAG_COMPAT, X509_FLAG_NO_ATTRIBUTES, X509_FLAG_NO_EXTENSIONS, X509_FLAG_NO_HEADER, X509_FLAG_NO_PUBKEY, X509_FLAG_NO_SIGDUMP, X509_FLAG_NO_SUBJECT, X509_FLAG_NO_VERSION, X509_NAME_print_ex(), X509_PUBKEY_get0_param(), X509_REQ_extension_nid(), X509_REQ_get0_pubkey(), X509_REQ_get0_signature(), X509_REQ_get_attr(), X509_REQ_get_attr_count(), X509_REQ_get_subject_name(), X509_REQ_get_version(), X509_REQ_get_X509_PUBKEY(), X509_signature_print(), X509err, X509V3_EXT_print(), XN_FLAG_SEP_MASK, and XN_FLAG_SEP_MULTILINE.
Referenced by X509_REQ_print().
X509_REQ_print_fp()
int X509_REQ_print_fp (FILE * bp, X509_REQ * req)
Definition at line 21 of file t_req.c.
X509_REQ_set_extension_nids()
void X509_REQ_set_extension_nids (int * nids)
Definition at line 148 of file x509_req.c.
X509_REQ_set_pubkey()
int X509_REQ_set_pubkey (X509_REQ * x, EVP_PKEY * pkey)
Definition at line 34 of file x509rset.c.
References NULL, and X509_PUBKEY_set().
X509_REQ_set_subject_name()
int X509_REQ_set_subject_name (X509_REQ * req, X509_NAME * name)
Definition at line 26 of file x509rset.c.
References NULL, and X509_NAME_set().
X509_REQ_set_version()
int X509_REQ_set_version (X509_REQ * x, long version)
Definition at line 18 of file x509rset.c.
References ASN1_INTEGER_set(), and NULL.
X509_REQ_sign()
int X509_REQ_sign (X509_REQ * x, EVP_PKEY * pkey, const EVP_MD * md)
Definition at line 67 of file x_all.c.
X509_REQ_sign_ctx()
int X509_REQ_sign_ctx (X509_REQ * x, EVP_MD_CTX * ctx)
Definition at line 73 of file x_all.c.
References ASN1_ITEM_rptr, ASN1_item_sign_ctx(), and NULL.
X509_REQ_to_X509()
X509* X509_REQ_to_X509 (X509_REQ * r, int days, EVP_PKEY * pkey)
Definition at line 20 of file x509_r2x.c.
X509_REQ_verify()
int X509_REQ_verify (X509_REQ * a, EVP_PKEY * r)
Definition at line 31 of file x_all.c.
References ASN1_ITEM_rptr, and ASN1_item_verify().
X509_REVOKED_add1_ext_i2d()
int X509_REVOKED_add1_ext_i2d (X509_REVOKED * x, int nid, void * value, int crit, unsigned long flags)
Definition at line 156 of file x509_ext.c.
References X509V3_add1_i2d().
X509_REVOKED_add_ext()
int X509_REVOKED_add_ext (X509_REVOKED * x, X509_EXTENSION * ex, int loc)
Definition at line 146 of file x509_ext.c.
References NULL.
X509_REVOKED_delete_ext()
X509_EXTENSION* X509_REVOKED_delete_ext (X509_REVOKED * x, int loc)
Definition at line 141 of file x509_ext.c.
References X509v3_delete_ext().
X509_REVOKED_dup()
X509_REVOKED* X509_REVOKED_dup (X509_REVOKED * rev)
X509_REVOKED_get0_revocationDate()
const ASN1_TIME* X509_REVOKED_get0_revocationDate (const X509_REVOKED * x)
Definition at line 134 of file x509cset.c.
X509_REVOKED_get0_serialNumber()
const ASN1_INTEGER* X509_REVOKED_get0_serialNumber (const X509_REVOKED * x)
Definition at line 156 of file x509cset.c.
X509_REVOKED_get_ext()
X509_EXTENSION* X509_REVOKED_get_ext (const X509_REVOKED * x, int loc)
Definition at line 136 of file x509_ext.c.
References X509v3_get_ext().
X509_REVOKED_get_ext_by_critical()
int X509_REVOKED_get_ext_by_critical (const X509_REVOKED * x, int crit, int lastpos)
Definition at line 131 of file x509_ext.c.
References X509v3_get_ext_by_critical().
X509_REVOKED_get_ext_by_NID()
int X509_REVOKED_get_ext_by_NID (const X509_REVOKED * x, int nid, int lastpos)
Definition at line 120 of file x509_ext.c.
References X509v3_get_ext_by_NID().
X509_REVOKED_get_ext_by_OBJ()
int X509_REVOKED_get_ext_by_OBJ (const X509_REVOKED * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 125 of file x509_ext.c.
References X509v3_get_ext_by_OBJ().
X509_REVOKED_get_ext_count()
int X509_REVOKED_get_ext_count (const X509_REVOKED * x)
Definition at line 115 of file x509_ext.c.
References X509v3_get_ext_count().
X509_REVOKED_get_ext_d2i()
void* X509_REVOKED_get_ext_d2i (const X509_REVOKED * x, int nid, int * crit, int * idx)
Definition at line 151 of file x509_ext.c.
X509_REVOKED_set_revocationDate()
int X509_REVOKED_set_revocationDate (X509_REVOKED * r, ASN1_TIME * tm)
Definition at line 139 of file x509cset.c.
References ASN1_STRING_dup(), in, and NULL.
X509_REVOKED_set_serialNumber()
int X509_REVOKED_set_serialNumber (X509_REVOKED * x, ASN1_INTEGER * serial)
Definition at line 161 of file x509cset.c.
References ASN1_STRING_copy(), in, NULL, and STACK_OF().
X509_set1_notAfter()
int X509_set1_notAfter (X509 * x, const ASN1_TIME * tm)
Definition at line 81 of file x509_set.c.
References NULL, and x509_set1_time().
X509_set1_notBefore()
int X509_set1_notBefore (X509 * x, const ASN1_TIME * tm)
Definition at line 74 of file x509_set.c.
References NULL, and x509_set1_time().
X509_set_ex_data()
int X509_set_ex_data (X509 * r, int idx, void * arg)
X509_set_issuer_name()
int X509_set_issuer_name (X509 * x, X509_NAME * name)
Definition at line 46 of file x509_set.c.
References NULL, and X509_NAME_set().
X509_set_pubkey()
int X509_set_pubkey (X509 * x, EVP_PKEY * pkey)
Definition at line 88 of file x509_set.c.
References NULL, and X509_PUBKEY_set().
X509_set_serialNumber()
int X509_set_serialNumber (X509 * x, ASN1_INTEGER * serial)
Definition at line 34 of file x509_set.c.
References ASN1_STRING_copy(), in, and NULL.
X509_set_subject_name()
int X509_set_subject_name (X509 * x, X509_NAME * name)
Definition at line 53 of file x509_set.c.
References NULL, and X509_NAME_set().
X509_set_version()
int X509_set_version (X509 * x, long version)
Definition at line 18 of file x509_set.c.
References ASN1_INTEGER_set(), and NULL.
X509_SIG_get0()
void X509_SIG_get0 (const X509_SIG * sig, const X509_ALGOR ** palg, const ASN1_OCTET_STRING ** pdigest)
Referenced by PKCS12_get0_mac(), and PKCS8_decrypt().
X509_SIG_getm()
void X509_SIG_getm (X509_SIG * sig, X509_ALGOR ** palg, ASN1_OCTET_STRING ** pdigest)
Referenced by PKCS12_setup_mac().
X509_sign()
int X509_sign (X509 * x, EVP_PKEY * pkey, const EVP_MD * md)
Definition at line 43 of file x_all.c.
X509_sign_ctx()
int X509_sign_ctx (X509 * x, EVP_MD_CTX * ctx)
Definition at line 51 of file x_all.c.
References ASN1_ITEM_rptr, and ASN1_item_sign_ctx().
X509_signature_dump()
int X509_signature_dump (BIO * bp, const ASN1_STRING * sig, int indent)
Definition at line 275 of file t_x509.c.
References BIO_indent(), BIO_printf(), and BIO_write().
Referenced by X509_signature_print().
X509_signature_print()
int X509_signature_print (BIO * bp, const X509_ALGOR * alg, const ASN1_STRING * sig)
Definition at line 298 of file t_x509.c.
References BIO_puts(), EVP_PKEY_asn1_find(), i2a_ASN1_OBJECT(), NID_undef, NULL, OBJ_find_sigid_algs(), OBJ_obj2nid(), and X509_signature_dump().
Referenced by X509_REQ_print_ex().
X509_subject_name_cmp()
int X509_subject_name_cmp (const X509 * a, const X509 * b)
Definition at line 68 of file x509_cmp.c.
References X509_NAME_cmp().
X509_subject_name_hash()
unsigned long X509_subject_name_hash (X509 * x)
Definition at line 115 of file x509_cmp.c.
References X509_NAME_hash().
X509_subject_name_hash_old()
unsigned long X509_subject_name_hash_old (X509 * x)
Definition at line 121 of file x509_cmp.c.
References X509_NAME_hash_old().
X509_time_adj()
ASN1_TIME* X509_time_adj (ASN1_TIME * s, long adj, time_t * t)
Definition at line 1877 of file x509_vfy.c.
References X509_time_adj_ex().
Referenced by X509_cmp_time(), and X509_gmtime_adj().
X509_time_adj_ex()
ASN1_TIME* X509_time_adj_ex (ASN1_TIME * s, int offset_day, long offset_sec, time_t * t)
Definition at line 1882 of file x509_vfy.c.
References ASN1_GENERALIZEDTIME_adj(), ASN1_STRING_FLAG_MSTRING, ASN1_TIME_adj(), ASN1_UTCTIME_adj(), t, V_ASN1_GENERALIZEDTIME, and V_ASN1_UTCTIME.
Referenced by set_cert_times(), and X509_time_adj().
X509_to_X509_REQ()
X509_REQ* X509_to_X509_REQ (X509 * x, EVP_PKEY * pkey, const EVP_MD * md)
Definition at line 22 of file x509_req.c.
X509_TRUST_add()
int X509_TRUST_add (int id, int flags, int(*)(X509_TRUST *, X509 *, int) ck, const char * name, int arg1, void * arg2)
Definition at line 122 of file x509_trs.c.
X509_TRUST_cleanup()
void X509_TRUST_cleanup (void)
Definition at line 195 of file x509_trs.c.
X509_trust_clear()
void X509_trust_clear (X509 * x)
X509_TRUST_get0()
X509_TRUST* X509_TRUST_get0 (int idx)
Definition at line 88 of file x509_trs.c.
X509_TRUST_get0_name()
char* X509_TRUST_get0_name (const X509_TRUST * xp)
Definition at line 206 of file x509_trs.c.
References X509_TRUST::name.
X509_TRUST_get_by_id()
int X509_TRUST_get_by_id (int id)
Definition at line 97 of file x509_trs.c.
Referenced by X509_TRUST_set().
X509_TRUST_get_count()
int X509_TRUST_get_count (void)
Definition at line 81 of file x509_trs.c.
References X509_TRUST_COUNT.
X509_TRUST_get_flags()
int X509_TRUST_get_flags (const X509_TRUST * xp)
Definition at line 201 of file x509_trs.c.
References X509_TRUST::flags.
X509_TRUST_get_trust()
int X509_TRUST_get_trust (const X509_TRUST * xp)
Definition at line 211 of file x509_trs.c.
References X509_TRUST::trust.
X509_TRUST_set()
int X509_TRUST_set (int * t, int trust)
Definition at line 112 of file x509_trs.c.
References X509_F_X509_TRUST_SET, X509_R_INVALID_TRUST, X509_TRUST_get_by_id(), and X509err.
Referenced by X509_VERIFY_PARAM_set_trust().
X509_trusted()
int X509_trusted (const X509 * x)
X509_up_ref()
int X509_up_ref (X509 * x)
Definition at line 95 of file x509_set.c.
References CRYPTO_UP_REF, REF_ASSERT_ISNT, and REF_PRINT_COUNT.
Referenced by CMS_SignerInfo_set1_signer_cert(), CT_POLICY_EVAL_CTX_set1_issuer(), PKCS7_add_certificate(), ssl_cert_add1_chain_cert(), SSL_get_peer_certificate(), ssl_session_dup(), STACK_OF(), TS_RESP_CTX_set_signer_cert(), and X509_OBJECT_up_ref_count().
X509_verify()
int X509_verify (X509 * a, EVP_PKEY * r)
Definition at line 23 of file x_all.c.
References ASN1_ITEM_rptr, ASN1_item_verify(), and X509_ALGOR_cmp().
X509_verify_cert()
int X509_verify_cert (X509_STORE_CTX * ctx)
Definition at line 251 of file x509_vfy.c.
Referenced by ssl_build_cert_chain(), and ssl_verify_cert_chain().
X509_verify_cert_error_string()
const char* X509_verify_cert_error_string (long n)
Definition at line 22 of file x509_txt.c.
References X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH, X509_V_ERR_AKID_SKID_MISMATCH, X509_V_ERR_APPLICATION_VERIFICATION, X509_V_ERR_CA_KEY_TOO_SMALL, X509_V_ERR_CA_MD_TOO_WEAK, X509_V_ERR_CERT_CHAIN_TOO_LONG, X509_V_ERR_CERT_HAS_EXPIRED, X509_V_ERR_CERT_NOT_YET_VALID, X509_V_ERR_CERT_REJECTED, X509_V_ERR_CERT_REVOKED, X509_V_ERR_CERT_SIGNATURE_FAILURE, X509_V_ERR_CERT_UNTRUSTED, X509_V_ERR_CRL_HAS_EXPIRED, X509_V_ERR_CRL_NOT_YET_VALID, X509_V_ERR_CRL_PATH_VALIDATION_ERROR, X509_V_ERR_CRL_SIGNATURE_FAILURE, X509_V_ERR_DANE_NO_MATCH, X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT, X509_V_ERR_DIFFERENT_CRL_SCOPE, X509_V_ERR_EE_KEY_TOO_SMALL, X509_V_ERR_EMAIL_MISMATCH, X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD, X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD, X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD, X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD, X509_V_ERR_EXCLUDED_VIOLATION, X509_V_ERR_HOSTNAME_MISMATCH, X509_V_ERR_INVALID_CA, X509_V_ERR_INVALID_CALL, X509_V_ERR_INVALID_EXTENSION, X509_V_ERR_INVALID_NON_CA, X509_V_ERR_INVALID_POLICY_EXTENSION, X509_V_ERR_INVALID_PURPOSE, X509_V_ERR_IP_ADDRESS_MISMATCH, X509_V_ERR_KEYUSAGE_NO_CERTSIGN, X509_V_ERR_KEYUSAGE_NO_CRL_SIGN, X509_V_ERR_KEYUSAGE_NO_DIGITAL_SIGNATURE, X509_V_ERR_NO_EXPLICIT_POLICY, X509_V_ERR_NO_VALID_SCTS, X509_V_ERR_OUT_OF_MEM, X509_V_ERR_PATH_LENGTH_EXCEEDED, X509_V_ERR_PATH_LOOP, X509_V_ERR_PERMITTED_VIOLATION, X509_V_ERR_PROXY_CERTIFICATES_NOT_ALLOWED, X509_V_ERR_PROXY_PATH_LENGTH_EXCEEDED, X509_V_ERR_PROXY_SUBJECT_NAME_VIOLATION, X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN, X509_V_ERR_STORE_LOOKUP, X509_V_ERR_SUBJECT_ISSUER_MISMATCH, X509_V_ERR_SUBTREE_MINMAX, X509_V_ERR_SUITE_B_CANNOT_SIGN_P_384_WITH_P_256, X509_V_ERR_SUITE_B_INVALID_ALGORITHM, X509_V_ERR_SUITE_B_INVALID_CURVE, X509_V_ERR_SUITE_B_INVALID_SIGNATURE_ALGORITHM, X509_V_ERR_SUITE_B_INVALID_VERSION, X509_V_ERR_SUITE_B_LOS_NOT_ALLOWED, X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY, X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE, X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE, X509_V_ERR_UNABLE_TO_GET_CRL, X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER, X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT, X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY, X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE, X509_V_ERR_UNHANDLED_CRITICAL_CRL_EXTENSION, X509_V_ERR_UNHANDLED_CRITICAL_EXTENSION, X509_V_ERR_UNNESTED_RESOURCE, X509_V_ERR_UNSPECIFIED, X509_V_ERR_UNSUPPORTED_CONSTRAINT_SYNTAX, X509_V_ERR_UNSUPPORTED_CONSTRAINT_TYPE, X509_V_ERR_UNSUPPORTED_EXTENSION_FEATURE, X509_V_ERR_UNSUPPORTED_NAME_SYNTAX, and X509_V_OK.
Referenced by ssl_build_cert_chain(), SSL_SESSION_print(), and verify_callback().
X509at_delete_attr()
X509_ATTRIBUTE* X509at_delete_attr (STACK_OF(X509_ATTRIBUTE) * x, int loc)
Definition at line 63 of file x509_att.c.
Referenced by CMS_signed_delete_attr(), CMS_unsigned_delete_attr(), EVP_PKEY_delete_attr(), and X509_REQ_delete_attr().
X509at_get0_data_by_OBJ()
void* X509at_get0_data_by_OBJ (STACK_OF(X509_ATTRIBUTE) * x, const ASN1_OBJECT * obj, int lastpos, int type)
Definition at line 152 of file x509_att.c.
References NULL, X509_ATTRIBUTE_count(), X509_ATTRIBUTE_get0_data(), X509at_get_attr(), and X509at_get_attr_by_OBJ().
Referenced by CMS_signed_get0_data_by_OBJ(), and CMS_unsigned_get0_data_by_OBJ().
X509at_get_attr()
X509_ATTRIBUTE* X509at_get_attr (const STACK_OF(X509_ATTRIBUTE) * x, int loc)
Definition at line 55 of file x509_att.c.
References NULL.
Referenced by CMS_signed_get_attr(), CMS_unsigned_get_attr(), EVP_PKEY_get_attr(), PKCS12_get_attr_gen(), X509_REQ_get_attr(), and X509at_get0_data_by_OBJ().
X509at_get_attr_by_NID()
int X509at_get_attr_by_NID (const STACK_OF(X509_ATTRIBUTE) * x, int nid, int lastpos)
Definition at line 25 of file x509_att.c.
References NULL, obj, OBJ_nid2obj(), and X509at_get_attr_by_OBJ().
Referenced by CMS_signed_get_attr_by_NID(), CMS_unsigned_get_attr_by_NID(), EVP_PKEY_get_attr_by_NID(), PKCS12_get_attr_gen(), and X509_REQ_get_attr_by_NID().
X509at_get_attr_by_OBJ()
int X509at_get_attr_by_OBJ (const STACK_OF(X509_ATTRIBUTE) * sk, const ASN1_OBJECT * obj, int lastpos)
Definition at line 35 of file x509_att.c.
References ex, NULL, and OBJ_cmp().
Referenced by CMS_signed_get_attr_by_OBJ(), CMS_unsigned_get_attr_by_OBJ(), EVP_PKEY_get_attr_by_OBJ(), X509_REQ_get_attr_by_OBJ(), X509at_get0_data_by_OBJ(), and X509at_get_attr_by_NID().
X509at_get_attr_count()
int X509at_get_attr_count (const STACK_OF(X509_ATTRIBUTE) * x)
Definition at line 20 of file x509_att.c.
Referenced by CMS_signed_get_attr_count(), CMS_unsigned_get_attr_count(), EVP_PKEY_get_attr_count(), and X509_REQ_get_attr_count().
X509v3_delete_ext()
X509_EXTENSION* X509v3_delete_ext (STACK_OF(X509_EXTENSION) * x, int loc)
Definition at line 86 of file x509_v3.c.
Referenced by OCSP_BASICRESP_delete_ext(), OCSP_ONEREQ_delete_ext(), OCSP_REQUEST_delete_ext(), OCSP_SINGLERESP_delete_ext(), TS_REQ_delete_ext(), TS_TST_INFO_delete_ext(), X509_CRL_delete_ext(), X509_delete_ext(), and X509_REVOKED_delete_ext().
X509v3_get_ext()
X509_EXTENSION* X509v3_get_ext (const STACK_OF(X509_EXTENSION) * x, int loc)
Definition at line 78 of file x509_v3.c.
References NULL.
Referenced by OCSP_BASICRESP_get_ext(), OCSP_ONEREQ_get_ext(), OCSP_REQUEST_get_ext(), OCSP_SINGLERESP_get_ext(), TS_ext_print_bio(), TS_REQ_get_ext(), TS_TST_INFO_get_ext(), X509_CRL_get_ext(), X509_get_ext(), and X509_REVOKED_get_ext().
X509v3_get_ext_by_critical()
int X509v3_get_ext_by_critical (const STACK_OF(X509_EXTENSION) * x, int crit, int lastpos)
Definition at line 58 of file x509_v3.c.
References ex, and NULL.
Referenced by OCSP_BASICRESP_get_ext_by_critical(), OCSP_ONEREQ_get_ext_by_critical(), OCSP_REQUEST_get_ext_by_critical(), OCSP_SINGLERESP_get_ext_by_critical(), TS_REQ_get_ext_by_critical(), TS_TST_INFO_get_ext_by_critical(), X509_CRL_get_ext_by_critical(), X509_get_ext_by_critical(), and X509_REVOKED_get_ext_by_critical().
X509v3_get_ext_by_NID()
int X509v3_get_ext_by_NID (const STACK_OF(X509_EXTENSION) * x, int nid, int lastpos)
Definition at line 27 of file x509_v3.c.
References NULL, obj, OBJ_nid2obj(), and X509v3_get_ext_by_OBJ().
Referenced by OCSP_BASICRESP_get_ext_by_NID(), OCSP_ONEREQ_get_ext_by_NID(), OCSP_REQUEST_get_ext_by_NID(), OCSP_SINGLERESP_get_ext_by_NID(), TS_REQ_get_ext_by_NID(), TS_TST_INFO_get_ext_by_NID(), X509_CRL_get_ext_by_NID(), X509_get_ext_by_NID(), and X509_REVOKED_get_ext_by_NID().
X509v3_get_ext_by_OBJ()
int X509v3_get_ext_by_OBJ (const STACK_OF(X509_EXTENSION) * x, const ASN1_OBJECT * obj, int lastpos)
Definition at line 38 of file x509_v3.c.
References ex, NULL, and OBJ_cmp().
Referenced by OCSP_BASICRESP_get_ext_by_OBJ(), OCSP_ONEREQ_get_ext_by_OBJ(), OCSP_REQUEST_get_ext_by_OBJ(), OCSP_SINGLERESP_get_ext_by_OBJ(), TS_REQ_get_ext_by_OBJ(), TS_TST_INFO_get_ext_by_OBJ(), X509_CRL_get_ext_by_OBJ(), X509_get_ext_by_OBJ(), X509_REVOKED_get_ext_by_OBJ(), and X509v3_get_ext_by_NID().
X509v3_get_ext_count()
int X509v3_get_ext_count (const STACK_OF(X509_EXTENSION) * x)
Definition at line 20 of file x509_v3.c.
References NULL.
Referenced by OCSP_BASICRESP_get_ext_count(), OCSP_ONEREQ_get_ext_count(), OCSP_REQUEST_get_ext_count(), OCSP_SINGLERESP_get_ext_count(), TS_ext_print_bio(), TS_REQ_get_ext_count(), TS_TST_INFO_get_ext_count(), X509_CRL_get_ext_count(), X509_get_ext_count(), and X509_REVOKED_get_ext_count().
Variable Documentation
attr
X509_ATTRIBUTE* attr
Definition at line 898 of file x509.h.
Referenced by print_attribs(), and STACK_OF().
attrname
const char* attrname
Definition at line 909 of file x509.h.
bytes
const char int const unsigned char * bytes
Definition at line 900 of file x509.h.
Referenced by main(), and STACK_OF().
ex
X509_EXTENSION* ex
Definition at line 838 of file x509.h.
Referenced by main(), SSL_CTX_set0_security_ex_data(), SSL_set0_security_ex_data(), TS_ext_print_bio(), X509_REQ_print_ex(), X509at_get_attr_by_OBJ(), X509v3_get_ext_by_critical(), and X509v3_get_ext_by_OBJ().
len
const char int const unsigned char int len
Definition at line 900 of file x509.h.
loc
X509_EXTENSION int loc
Definition at line 838 of file x509.h.
Referenced by OPENSSL_sk_insert().
nid
int nid
Definition at line 905 of file x509.h.
Referenced by ASN1_OBJECT_create(), cms_DigestAlgorithm_find_ctx(), EC_curve_nist2nid(), EC_GROUP_set_curve_name(), EVP_CIPHER_type(), main(), OBJ_txt2nid(), OBJ_txt2obj(), OCSP_accept_responses_new(), OCSP_cert_id_new(), parse_name(), PKCS7_add_signer(), PKCS7_ctrl(), ssl3_ctx_ctrl(), ssl_print_groups(), ssl_print_sigalgs(), ssl_print_tmp_key(), X509_REQ_extension_nid(), and X509V3_EXT_get().
obj
const ASN1_OBJECT* obj
Definition at line 900 of file x509.h.
Referenced by PKCS7_set_type(), STACK_OF(), TS_ext_print_bio(), X509_ATTRIBUTE_create_by_NID(), X509_ATTRIBUTE_create_by_txt(), X509_EXTENSION_create_by_NID(), X509_NAME_ENTRY_create_by_NID(), X509_NAME_ENTRY_create_by_txt(), X509_NAME_get_index_by_NID(), X509_REQ_print_ex(), X509_STORE_add_cert(), X509_STORE_add_crl(), X509_STORE_CTX_get1_issuer(), X509at_get_attr_by_NID(), and X509v3_get_ext_by_NID().
type
const char int type
Definition at line 900 of file x509.h.
X509_TRUST_set_default
int(*)(int, X509 *, int) X509_TRUST_set_default(int(*trust)(int, X509 *, int))
Definition at line 561 of file x509.h.