crypto/x509/x509_txt.c File Reference
x509_txt.c File Reference
#include <stdio.h>
#include <time.h>
#include <errno.h>
#include "internal/cryptlib.h"
#include <openssl/lhash.h>
#include <openssl/buffer.h>
#include <openssl/evp.h>
#include <openssl/asn1.h>
#include <openssl/x509.h>
#include <openssl/objects.h>
Functions
const char * X509_verify_cert_error_string (long n)
Function Documentation
X509_verify_cert_error_string()
const char* X509_verify_cert_error_string (long n)
Definition at line 22 of file x509_txt.c.
References X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH, X509_V_ERR_AKID_SKID_MISMATCH, X509_V_ERR_APPLICATION_VERIFICATION, X509_V_ERR_CA_KEY_TOO_SMALL, X509_V_ERR_CA_MD_TOO_WEAK, X509_V_ERR_CERT_CHAIN_TOO_LONG, X509_V_ERR_CERT_HAS_EXPIRED, X509_V_ERR_CERT_NOT_YET_VALID, X509_V_ERR_CERT_REJECTED, X509_V_ERR_CERT_REVOKED, X509_V_ERR_CERT_SIGNATURE_FAILURE, X509_V_ERR_CERT_UNTRUSTED, X509_V_ERR_CRL_HAS_EXPIRED, X509_V_ERR_CRL_NOT_YET_VALID, X509_V_ERR_CRL_PATH_VALIDATION_ERROR, X509_V_ERR_CRL_SIGNATURE_FAILURE, X509_V_ERR_DANE_NO_MATCH, X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT, X509_V_ERR_DIFFERENT_CRL_SCOPE, X509_V_ERR_EE_KEY_TOO_SMALL, X509_V_ERR_EMAIL_MISMATCH, X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD, X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD, X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD, X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD, X509_V_ERR_EXCLUDED_VIOLATION, X509_V_ERR_HOSTNAME_MISMATCH, X509_V_ERR_INVALID_CA, X509_V_ERR_INVALID_CALL, X509_V_ERR_INVALID_EXTENSION, X509_V_ERR_INVALID_NON_CA, X509_V_ERR_INVALID_POLICY_EXTENSION, X509_V_ERR_INVALID_PURPOSE, X509_V_ERR_IP_ADDRESS_MISMATCH, X509_V_ERR_KEYUSAGE_NO_CERTSIGN, X509_V_ERR_KEYUSAGE_NO_CRL_SIGN, X509_V_ERR_KEYUSAGE_NO_DIGITAL_SIGNATURE, X509_V_ERR_NO_EXPLICIT_POLICY, X509_V_ERR_NO_VALID_SCTS, X509_V_ERR_OUT_OF_MEM, X509_V_ERR_PATH_LENGTH_EXCEEDED, X509_V_ERR_PATH_LOOP, X509_V_ERR_PERMITTED_VIOLATION, X509_V_ERR_PROXY_CERTIFICATES_NOT_ALLOWED, X509_V_ERR_PROXY_PATH_LENGTH_EXCEEDED, X509_V_ERR_PROXY_SUBJECT_NAME_VIOLATION, X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN, X509_V_ERR_STORE_LOOKUP, X509_V_ERR_SUBJECT_ISSUER_MISMATCH, X509_V_ERR_SUBTREE_MINMAX, X509_V_ERR_SUITE_B_CANNOT_SIGN_P_384_WITH_P_256, X509_V_ERR_SUITE_B_INVALID_ALGORITHM, X509_V_ERR_SUITE_B_INVALID_CURVE, X509_V_ERR_SUITE_B_INVALID_SIGNATURE_ALGORITHM, X509_V_ERR_SUITE_B_INVALID_VERSION, X509_V_ERR_SUITE_B_LOS_NOT_ALLOWED, X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY, X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE, X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE, X509_V_ERR_UNABLE_TO_GET_CRL, X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER, X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT, X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY, X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE, X509_V_ERR_UNHANDLED_CRITICAL_CRL_EXTENSION, X509_V_ERR_UNHANDLED_CRITICAL_EXTENSION, X509_V_ERR_UNNESTED_RESOURCE, X509_V_ERR_UNSPECIFIED, X509_V_ERR_UNSUPPORTED_CONSTRAINT_SYNTAX, X509_V_ERR_UNSUPPORTED_CONSTRAINT_TYPE, X509_V_ERR_UNSUPPORTED_EXTENSION_FEATURE, X509_V_ERR_UNSUPPORTED_NAME_SYNTAX, and X509_V_OK.
Referenced by ssl_build_cert_chain(), SSL_SESSION_print(), and verify_callback().