crypto/x509/x_all.c File Reference
x_all.c File Reference
#include <stdio.h>
#include <openssl/stack.h>
#include "internal/cryptlib.h"
#include <openssl/buffer.h>
#include <openssl/asn1.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include "internal/x509_int.h"
#include <openssl/ocsp.h>
#include <openssl/rsa.h>
#include <openssl/dsa.h>
#include <openssl/x509v3.h>
Functions
int X509_verify (X509 *a, EVP_PKEY *r)
int X509_REQ_verify (X509_REQ *a, EVP_PKEY *r)
int NETSCAPE_SPKI_verify (NETSCAPE_SPKI *a, EVP_PKEY *r)
int X509_sign (X509 *x, EVP_PKEY *pkey, const EVP_MD *md)
int X509_sign_ctx (X509 *x, EVP_MD_CTX *ctx)
int X509_http_nbio (OCSP_REQ_CTX *rctx, X509 **pcert)
int X509_REQ_sign (X509_REQ *x, EVP_PKEY *pkey, const EVP_MD *md)
int X509_REQ_sign_ctx (X509_REQ *x, EVP_MD_CTX *ctx)
int X509_CRL_sign (X509_CRL *x, EVP_PKEY *pkey, const EVP_MD *md)
int X509_CRL_sign_ctx (X509_CRL *x, EVP_MD_CTX *ctx)
int X509_CRL_http_nbio (OCSP_REQ_CTX *rctx, X509_CRL **pcrl)
int NETSCAPE_SPKI_sign (NETSCAPE_SPKI *x, EVP_PKEY *pkey, const EVP_MD *md)
X509 * d2i_X509_fp (FILE *fp, X509 **x509)
int i2d_X509_fp (FILE *fp, X509 *x509)
X509 * d2i_X509_bio (BIO *bp, X509 **x509)
int i2d_X509_bio (BIO *bp, X509 *x509)
X509_CRL * d2i_X509_CRL_fp (FILE *fp, X509_CRL **crl)
int i2d_X509_CRL_fp (FILE *fp, X509_CRL *crl)
X509_CRL * d2i_X509_CRL_bio (BIO *bp, X509_CRL **crl)
int i2d_X509_CRL_bio (BIO *bp, X509_CRL *crl)
PKCS7 * d2i_PKCS7_fp (FILE *fp, PKCS7 **p7)
int i2d_PKCS7_fp (FILE *fp, PKCS7 *p7)
PKCS7 * d2i_PKCS7_bio (BIO *bp, PKCS7 **p7)
int i2d_PKCS7_bio (BIO *bp, PKCS7 *p7)
X509_REQ * d2i_X509_REQ_fp (FILE *fp, X509_REQ **req)
int i2d_X509_REQ_fp (FILE *fp, X509_REQ *req)
X509_REQ * d2i_X509_REQ_bio (BIO *bp, X509_REQ **req)
int i2d_X509_REQ_bio (BIO *bp, X509_REQ *req)
RSA * d2i_RSAPrivateKey_fp (FILE *fp, RSA **rsa)
int i2d_RSAPrivateKey_fp (FILE *fp, RSA *rsa)
RSA * d2i_RSAPublicKey_fp (FILE *fp, RSA **rsa)
RSA * d2i_RSA_PUBKEY_fp (FILE *fp, RSA **rsa)
int i2d_RSAPublicKey_fp (FILE *fp, RSA *rsa)
int i2d_RSA_PUBKEY_fp (FILE *fp, RSA *rsa)
RSA * d2i_RSAPrivateKey_bio (BIO *bp, RSA **rsa)
int i2d_RSAPrivateKey_bio (BIO *bp, RSA *rsa)
RSA * d2i_RSAPublicKey_bio (BIO *bp, RSA **rsa)
RSA * d2i_RSA_PUBKEY_bio (BIO *bp, RSA **rsa)
int i2d_RSAPublicKey_bio (BIO *bp, RSA *rsa)
int i2d_RSA_PUBKEY_bio (BIO *bp, RSA *rsa)
DSA * d2i_DSAPrivateKey_fp (FILE *fp, DSA **dsa)
int i2d_DSAPrivateKey_fp (FILE *fp, DSA *dsa)
DSA * d2i_DSA_PUBKEY_fp (FILE *fp, DSA **dsa)
int i2d_DSA_PUBKEY_fp (FILE *fp, DSA *dsa)
DSA * d2i_DSAPrivateKey_bio (BIO *bp, DSA **dsa)
int i2d_DSAPrivateKey_bio (BIO *bp, DSA *dsa)
DSA * d2i_DSA_PUBKEY_bio (BIO *bp, DSA **dsa)
int i2d_DSA_PUBKEY_bio (BIO *bp, DSA *dsa)
EC_KEY * d2i_EC_PUBKEY_fp (FILE *fp, EC_KEY **eckey)
int i2d_EC_PUBKEY_fp (FILE *fp, EC_KEY *eckey)
EC_KEY * d2i_ECPrivateKey_fp (FILE *fp, EC_KEY **eckey)
int i2d_ECPrivateKey_fp (FILE *fp, EC_KEY *eckey)
EC_KEY * d2i_EC_PUBKEY_bio (BIO *bp, EC_KEY **eckey)
int i2d_EC_PUBKEY_bio (BIO *bp, EC_KEY *ecdsa)
EC_KEY * d2i_ECPrivateKey_bio (BIO *bp, EC_KEY **eckey)
int i2d_ECPrivateKey_bio (BIO *bp, EC_KEY *eckey)
int X509_pubkey_digest (const X509 *data, const EVP_MD *type, unsigned char *md, unsigned int *len)
int X509_digest (const X509 *data, const EVP_MD *type, unsigned char *md, unsigned int *len)
int X509_CRL_digest (const X509_CRL *data, const EVP_MD *type, unsigned char *md, unsigned int *len)
int X509_REQ_digest (const X509_REQ *data, const EVP_MD *type, unsigned char *md, unsigned int *len)
int X509_NAME_digest (const X509_NAME *data, const EVP_MD *type, unsigned char *md, unsigned int *len)
int PKCS7_ISSUER_AND_SERIAL_digest (PKCS7_ISSUER_AND_SERIAL *data, const EVP_MD *type, unsigned char *md, unsigned int *len)
X509_SIG * d2i_PKCS8_fp (FILE *fp, X509_SIG **p8)
int i2d_PKCS8_fp (FILE *fp, X509_SIG *p8)
X509_SIG * d2i_PKCS8_bio (BIO *bp, X509_SIG **p8)
int i2d_PKCS8_bio (BIO *bp, X509_SIG *p8)
PKCS8_PRIV_KEY_INFO * d2i_PKCS8_PRIV_KEY_INFO_fp (FILE *fp, PKCS8_PRIV_KEY_INFO **p8inf)
int i2d_PKCS8_PRIV_KEY_INFO_fp (FILE *fp, PKCS8_PRIV_KEY_INFO *p8inf)
int i2d_PKCS8PrivateKeyInfo_fp (FILE *fp, EVP_PKEY *key)
int i2d_PrivateKey_fp (FILE *fp, EVP_PKEY *pkey)
EVP_PKEY * d2i_PrivateKey_fp (FILE *fp, EVP_PKEY **a)
int i2d_PUBKEY_fp (FILE *fp, EVP_PKEY *pkey)
EVP_PKEY * d2i_PUBKEY_fp (FILE *fp, EVP_PKEY **a)
PKCS8_PRIV_KEY_INFO * d2i_PKCS8_PRIV_KEY_INFO_bio (BIO *bp, PKCS8_PRIV_KEY_INFO **p8inf)
int i2d_PKCS8_PRIV_KEY_INFO_bio (BIO *bp, PKCS8_PRIV_KEY_INFO *p8inf)
int i2d_PKCS8PrivateKeyInfo_bio (BIO *bp, EVP_PKEY *key)
int i2d_PrivateKey_bio (BIO *bp, EVP_PKEY *pkey)
EVP_PKEY * d2i_PrivateKey_bio (BIO *bp, EVP_PKEY **a)
int i2d_PUBKEY_bio (BIO *bp, EVP_PKEY *pkey)
EVP_PKEY * d2i_PUBKEY_bio (BIO *bp, EVP_PKEY **a)
Function Documentation
d2i_DSA_PUBKEY_bio()
DSA* d2i_DSA_PUBKEY_bio (BIO * bp, DSA ** dsa)
Definition at line 298 of file x_all.c.
References ASN1_d2i_bio_of, d2i_DSA_PUBKEY(), and DSA_new().
d2i_DSA_PUBKEY_fp()
DSA* d2i_DSA_PUBKEY_fp (FILE * fp, DSA ** dsa)
Definition at line 277 of file x_all.c.
References ASN1_d2i_fp_of, d2i_DSA_PUBKEY(), and DSA_new().
d2i_DSAPrivateKey_bio()
DSA* d2i_DSAPrivateKey_bio (BIO * bp, DSA ** dsa)
Definition at line 288 of file x_all.c.
References ASN1_d2i_bio_of, d2i_DSAPrivateKey(), and DSA_new().
d2i_DSAPrivateKey_fp()
DSA* d2i_DSAPrivateKey_fp (FILE * fp, DSA ** dsa)
Definition at line 267 of file x_all.c.
References ASN1_d2i_fp_of, d2i_DSAPrivateKey(), and DSA_new().
d2i_EC_PUBKEY_bio()
EC_KEY* d2i_EC_PUBKEY_bio (BIO * bp, EC_KEY ** eckey)
Definition at line 332 of file x_all.c.
References ASN1_d2i_bio_of, d2i_EC_PUBKEY(), and EC_KEY_new().
d2i_EC_PUBKEY_fp()
EC_KEY* d2i_EC_PUBKEY_fp (FILE * fp, EC_KEY ** eckey)
Definition at line 312 of file x_all.c.
References ASN1_d2i_fp_of, d2i_EC_PUBKEY(), and EC_KEY_new().
d2i_ECPrivateKey_bio()
EC_KEY* d2i_ECPrivateKey_bio (BIO * bp, EC_KEY ** eckey)
Definition at line 342 of file x_all.c.
References ASN1_d2i_bio_of, d2i_ECPrivateKey(), and EC_KEY_new().
d2i_ECPrivateKey_fp()
EC_KEY* d2i_ECPrivateKey_fp (FILE * fp, EC_KEY ** eckey)
Definition at line 322 of file x_all.c.
References ASN1_d2i_fp_of, d2i_ECPrivateKey(), and EC_KEY_new().
d2i_PKCS7_bio()
PKCS7* d2i_PKCS7_bio (BIO * bp, PKCS7 ** p7)
Definition at line 166 of file x_all.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_PKCS7_fp()
PKCS7* d2i_PKCS7_fp (FILE * fp, PKCS7 ** p7)
Definition at line 155 of file x_all.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
d2i_PKCS8_bio()
X509_SIG* d2i_PKCS8_bio (BIO * bp, X509_SIG ** p8)
Definition at line 425 of file x_all.c.
References ASN1_d2i_bio_of.
d2i_PKCS8_fp()
X509_SIG* d2i_PKCS8_fp (FILE * fp, X509_SIG ** p8)
Definition at line 414 of file x_all.c.
References ASN1_d2i_fp_of.
d2i_PKCS8_PRIV_KEY_INFO_bio()
PKCS8_PRIV_KEY_INFO* d2i_PKCS8_PRIV_KEY_INFO_bio (BIO * bp, PKCS8_PRIV_KEY_INFO ** p8inf)
Definition at line 483 of file x_all.c.
References ASN1_d2i_bio_of.
d2i_PKCS8_PRIV_KEY_INFO_fp()
PKCS8_PRIV_KEY_INFO* d2i_PKCS8_PRIV_KEY_INFO_fp (FILE * fp, PKCS8_PRIV_KEY_INFO ** p8inf)
Definition at line 436 of file x_all.c.
References ASN1_d2i_fp_of.
d2i_PrivateKey_bio()
EVP_PKEY* d2i_PrivateKey_bio (BIO * bp, EVP_PKEY ** a)
Definition at line 513 of file x_all.c.
References ASN1_d2i_bio_of, d2i_AutoPrivateKey(), and EVP_PKEY_new().
d2i_PrivateKey_fp()
EVP_PKEY* d2i_PrivateKey_fp (FILE * fp, EVP_PKEY ** a)
Definition at line 466 of file x_all.c.
References ASN1_d2i_fp_of, d2i_AutoPrivateKey(), and EVP_PKEY_new().
d2i_PUBKEY_bio()
EVP_PKEY* d2i_PUBKEY_bio (BIO * bp, EVP_PKEY ** a)
Definition at line 523 of file x_all.c.
References ASN1_d2i_bio_of, d2i_PUBKEY(), and EVP_PKEY_new().
d2i_PUBKEY_fp()
EVP_PKEY* d2i_PUBKEY_fp (FILE * fp, EVP_PKEY ** a)
Definition at line 476 of file x_all.c.
References ASN1_d2i_fp_of, d2i_PUBKEY(), and EVP_PKEY_new().
d2i_RSA_PUBKEY_bio()
RSA* d2i_RSA_PUBKEY_bio (BIO * bp, RSA ** rsa)
Definition at line 249 of file x_all.c.
References ASN1_d2i_bio_of, d2i_RSA_PUBKEY(), and RSA_new().
d2i_RSA_PUBKEY_fp()
RSA* d2i_RSA_PUBKEY_fp (FILE * fp, RSA ** rsa)
Definition at line 216 of file x_all.c.
References ASN1_d2i_fp(), D2I_OF, d2i_RSA_PUBKEY(), and RSA_new().
d2i_RSAPrivateKey_bio()
RSA* d2i_RSAPrivateKey_bio (BIO * bp, RSA ** rsa)
Definition at line 234 of file x_all.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_RSAPrivateKey_fp()
RSA* d2i_RSAPrivateKey_fp (FILE * fp, RSA ** rsa)
Definition at line 201 of file x_all.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
d2i_RSAPublicKey_bio()
RSA* d2i_RSAPublicKey_bio (BIO * bp, RSA ** rsa)
Definition at line 244 of file x_all.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_RSAPublicKey_fp()
RSA* d2i_RSAPublicKey_fp (FILE * fp, RSA ** rsa)
Definition at line 211 of file x_all.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
d2i_X509_bio()
X509* d2i_X509_bio (BIO * bp, X509 ** x509)
Definition at line 122 of file x_all.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_X509_CRL_bio()
X509_CRL* d2i_X509_CRL_bio (BIO * bp, X509_CRL ** crl)
Definition at line 144 of file x_all.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_X509_CRL_fp()
X509_CRL* d2i_X509_CRL_fp (FILE * fp, X509_CRL ** crl)
Definition at line 133 of file x_all.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
d2i_X509_fp()
X509* d2i_X509_fp (FILE * fp, X509 ** x509)
Definition at line 111 of file x_all.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
d2i_X509_REQ_bio()
X509_REQ* d2i_X509_REQ_bio (BIO * bp, X509_REQ ** req)
Definition at line 188 of file x_all.c.
References ASN1_item_d2i_bio(), and ASN1_ITEM_rptr.
d2i_X509_REQ_fp()
X509_REQ* d2i_X509_REQ_fp (FILE * fp, X509_REQ ** req)
Definition at line 177 of file x_all.c.
References ASN1_item_d2i_fp(), and ASN1_ITEM_rptr.
i2d_DSA_PUBKEY_bio()
int i2d_DSA_PUBKEY_bio (BIO * bp, DSA * dsa)
Definition at line 303 of file x_all.c.
References ASN1_i2d_bio_of, and i2d_DSA_PUBKEY().
i2d_DSA_PUBKEY_fp()
int i2d_DSA_PUBKEY_fp (FILE * fp, DSA * dsa)
Definition at line 282 of file x_all.c.
References ASN1_i2d_fp_of, and i2d_DSA_PUBKEY().
i2d_DSAPrivateKey_bio()
int i2d_DSAPrivateKey_bio (BIO * bp, DSA * dsa)
Definition at line 293 of file x_all.c.
References ASN1_i2d_bio_of_const, and i2d_DSAPrivateKey().
i2d_DSAPrivateKey_fp()
int i2d_DSAPrivateKey_fp (FILE * fp, DSA * dsa)
Definition at line 272 of file x_all.c.
References ASN1_i2d_fp_of_const, and i2d_DSAPrivateKey().
i2d_EC_PUBKEY_bio()
int i2d_EC_PUBKEY_bio (BIO * bp, EC_KEY * ecdsa)
Definition at line 337 of file x_all.c.
References ASN1_i2d_bio_of, and i2d_EC_PUBKEY().
i2d_EC_PUBKEY_fp()
int i2d_EC_PUBKEY_fp (FILE * fp, EC_KEY * eckey)
Definition at line 317 of file x_all.c.
References ASN1_i2d_fp_of, and i2d_EC_PUBKEY().
i2d_ECPrivateKey_bio()
int i2d_ECPrivateKey_bio (BIO * bp, EC_KEY * eckey)
Definition at line 347 of file x_all.c.
References ASN1_i2d_bio_of, and i2d_ECPrivateKey().
i2d_ECPrivateKey_fp()
int i2d_ECPrivateKey_fp (FILE * fp, EC_KEY * eckey)
Definition at line 327 of file x_all.c.
References ASN1_i2d_fp_of, and i2d_ECPrivateKey().
i2d_PKCS7_bio()
int i2d_PKCS7_bio (BIO * bp, PKCS7 * p7)
Definition at line 171 of file x_all.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_PKCS7_fp()
int i2d_PKCS7_fp (FILE * fp, PKCS7 * p7)
Definition at line 160 of file x_all.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
i2d_PKCS8_bio()
int i2d_PKCS8_bio (BIO * bp, X509_SIG * p8)
Definition at line 430 of file x_all.c.
References ASN1_i2d_bio_of.
i2d_PKCS8_fp()
int i2d_PKCS8_fp (FILE * fp, X509_SIG * p8)
Definition at line 419 of file x_all.c.
References ASN1_i2d_fp_of.
i2d_PKCS8_PRIV_KEY_INFO_bio()
int i2d_PKCS8_PRIV_KEY_INFO_bio (BIO * bp, PKCS8_PRIV_KEY_INFO * p8inf)
Definition at line 490 of file x_all.c.
References ASN1_i2d_bio_of.
i2d_PKCS8_PRIV_KEY_INFO_fp()
int i2d_PKCS8_PRIV_KEY_INFO_fp (FILE * fp, PKCS8_PRIV_KEY_INFO * p8inf)
Definition at line 443 of file x_all.c.
References ASN1_i2d_fp_of.
i2d_PKCS8PrivateKeyInfo_bio()
int i2d_PKCS8PrivateKeyInfo_bio (BIO * bp, EVP_PKEY * key)
Definition at line 496 of file x_all.c.
i2d_PKCS8PrivateKeyInfo_fp()
int i2d_PKCS8PrivateKeyInfo_fp (FILE * fp, EVP_PKEY * key)
Definition at line 449 of file x_all.c.
i2d_PrivateKey_bio()
int i2d_PrivateKey_bio (BIO * bp, EVP_PKEY * pkey)
Definition at line 508 of file x_all.c.
References ASN1_i2d_bio_of, and i2d_PrivateKey().
i2d_PrivateKey_fp()
int i2d_PrivateKey_fp (FILE * fp, EVP_PKEY * pkey)
Definition at line 461 of file x_all.c.
References ASN1_i2d_fp_of, and i2d_PrivateKey().
i2d_PUBKEY_bio()
int i2d_PUBKEY_bio (BIO * bp, EVP_PKEY * pkey)
Definition at line 518 of file x_all.c.
References ASN1_i2d_bio_of, and i2d_PUBKEY().
i2d_PUBKEY_fp()
int i2d_PUBKEY_fp (FILE * fp, EVP_PKEY * pkey)
Definition at line 471 of file x_all.c.
References ASN1_i2d_fp_of, and i2d_PUBKEY().
i2d_RSA_PUBKEY_bio()
int i2d_RSA_PUBKEY_bio (BIO * bp, RSA * rsa)
Definition at line 259 of file x_all.c.
References ASN1_i2d_bio_of, and i2d_RSA_PUBKEY().
i2d_RSA_PUBKEY_fp()
int i2d_RSA_PUBKEY_fp (FILE * fp, RSA * rsa)
Definition at line 228 of file x_all.c.
References ASN1_i2d_fp(), I2D_OF, and i2d_RSA_PUBKEY().
i2d_RSAPrivateKey_bio()
int i2d_RSAPrivateKey_bio (BIO * bp, RSA * rsa)
Definition at line 239 of file x_all.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_RSAPrivateKey_fp()
int i2d_RSAPrivateKey_fp (FILE * fp, RSA * rsa)
Definition at line 206 of file x_all.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
i2d_RSAPublicKey_bio()
int i2d_RSAPublicKey_bio (BIO * bp, RSA * rsa)
Definition at line 254 of file x_all.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_RSAPublicKey_fp()
int i2d_RSAPublicKey_fp (FILE * fp, RSA * rsa)
Definition at line 223 of file x_all.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
i2d_X509_bio()
int i2d_X509_bio (BIO * bp, X509 * x509)
Definition at line 127 of file x_all.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_X509_CRL_bio()
int i2d_X509_CRL_bio (BIO * bp, X509_CRL * crl)
Definition at line 149 of file x_all.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_X509_CRL_fp()
int i2d_X509_CRL_fp (FILE * fp, X509_CRL * crl)
Definition at line 138 of file x_all.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
i2d_X509_fp()
int i2d_X509_fp (FILE * fp, X509 * x509)
Definition at line 116 of file x_all.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
i2d_X509_REQ_bio()
int i2d_X509_REQ_bio (BIO * bp, X509_REQ * req)
Definition at line 193 of file x_all.c.
References ASN1_item_i2d_bio(), and ASN1_ITEM_rptr.
i2d_X509_REQ_fp()
int i2d_X509_REQ_fp (FILE * fp, X509_REQ * req)
Definition at line 182 of file x_all.c.
References ASN1_item_i2d_fp(), and ASN1_ITEM_rptr.
NETSCAPE_SPKI_sign()
int NETSCAPE_SPKI_sign (NETSCAPE_SPKI * x, EVP_PKEY * pkey, const EVP_MD * md)
Definition at line 104 of file x_all.c.
NETSCAPE_SPKI_verify()
int NETSCAPE_SPKI_verify (NETSCAPE_SPKI * a, EVP_PKEY * r)
Definition at line 37 of file x_all.c.
References ASN1_ITEM_rptr, ASN1_item_verify(), NETSCAPE_SPKI::sig_algor, NETSCAPE_SPKI::signature, and NETSCAPE_SPKI::spkac.
PKCS7_ISSUER_AND_SERIAL_digest()
int PKCS7_ISSUER_AND_SERIAL_digest (PKCS7_ISSUER_AND_SERIAL * data, const EVP_MD * type, unsigned char * md, unsigned int * len)
Definition at line 405 of file x_all.c.
X509_CRL_digest()
int X509_CRL_digest (const X509_CRL * data, const EVP_MD * type, unsigned char * md, unsigned int * len)
Definition at line 377 of file x_all.c.
X509_CRL_http_nbio()
int X509_CRL_http_nbio (OCSP_REQ_CTX * rctx, X509_CRL ** pcrl)
Definition at line 96 of file x_all.c.
References ASN1_ITEM_rptr, and OCSP_REQ_CTX_nbio_d2i().
X509_CRL_sign()
int X509_CRL_sign (X509_CRL * x, EVP_PKEY * pkey, const EVP_MD * md)
Definition at line 80 of file x_all.c.
X509_CRL_sign_ctx()
int X509_CRL_sign_ctx (X509_CRL * x, EVP_MD_CTX * ctx)
Definition at line 87 of file x_all.c.
References ASN1_ITEM_rptr, and ASN1_item_sign_ctx().
X509_digest()
int X509_digest (const X509 * data, const EVP_MD * type, unsigned char * md, unsigned int * len)
Definition at line 363 of file x_all.c.
X509_http_nbio()
int X509_http_nbio (OCSP_REQ_CTX * rctx, X509 ** pcert)
Definition at line 60 of file x_all.c.
References ASN1_ITEM_rptr, and OCSP_REQ_CTX_nbio_d2i().
X509_NAME_digest()
int X509_NAME_digest (const X509_NAME * data, const EVP_MD * type, unsigned char * md, unsigned int * len)
Definition at line 398 of file x_all.c.
X509_pubkey_digest()
int X509_pubkey_digest (const X509 * data, const EVP_MD * type, unsigned char * md, unsigned int * len)
Definition at line 353 of file x_all.c.
X509_REQ_digest()
int X509_REQ_digest (const X509_REQ * data, const EVP_MD * type, unsigned char * md, unsigned int * len)
Definition at line 391 of file x_all.c.
X509_REQ_sign()
int X509_REQ_sign (X509_REQ * x, EVP_PKEY * pkey, const EVP_MD * md)
Definition at line 67 of file x_all.c.
X509_REQ_sign_ctx()
int X509_REQ_sign_ctx (X509_REQ * x, EVP_MD_CTX * ctx)
Definition at line 73 of file x_all.c.
References ASN1_ITEM_rptr, ASN1_item_sign_ctx(), and NULL.
X509_REQ_verify()
int X509_REQ_verify (X509_REQ * a, EVP_PKEY * r)
Definition at line 31 of file x_all.c.
References ASN1_ITEM_rptr, and ASN1_item_verify().
X509_sign()
int X509_sign (X509 * x, EVP_PKEY * pkey, const EVP_MD * md)
Definition at line 43 of file x_all.c.
X509_sign_ctx()
int X509_sign_ctx (X509 * x, EVP_MD_CTX * ctx)
Definition at line 51 of file x_all.c.
References ASN1_ITEM_rptr, and ASN1_item_sign_ctx().
X509_verify()
int X509_verify (X509 * a, EVP_PKEY * r)
Definition at line 23 of file x_all.c.
References ASN1_ITEM_rptr, ASN1_item_verify(), and X509_ALGOR_cmp().