crypto/x509/x_name.c File Reference
x_name.c File Reference
#include <stdio.h>
#include <ctype.h>
#include "internal/cryptlib.h"
#include <openssl/asn1t.h>
#include <openssl/x509.h>
#include "internal/x509_int.h"
#include "internal/asn1_int.h"
#include "x509_lcl.h"
Macros
#define X509_NAME_MAX (1024 * 1024)
#define ASN1_MASK_CANON
Functions
ASN1_SEQUENCE (X509_NAME_ENTRY)
int X509_NAME_set (X509_NAME **xn, X509_NAME *name)
int X509_NAME_print (BIO *bp, const X509_NAME *name, int obase)
int X509_NAME_get0_der (X509_NAME *nm, const unsigned char **pder, size_t *pderlen)
Macro Definition Documentation
ASN1_MASK_CANON
#define ASN1_MASK_CANON
Value:
(B_ASN1_UTF8STRING | B_ASN1_BMPSTRING | B_ASN1_UNIVERSALSTRING \
        | B_ASN1_PRINTABLESTRING | B_ASN1_T61STRING | B_ASN1_IA5STRING \
        | B_ASN1_VISIBLESTRING)
Definition at line 371 of file x_name.c.
X509_NAME_MAX
#define X509_NAME_MAX (1024 * 1024)
Definition at line 24 of file x_name.c.
Function Documentation
ASN1_SEQUENCE()
ASN1_SEQUENCE (X509_NAME_ENTRY)
X509_NAME_get0_der()
int X509_NAME_get0_der (X509_NAME * nm, const unsigned char ** pder, size_t * pderlen)
Definition at line 546 of file x_name.c.
References if(), and NULL.
X509_NAME_print()
int X509_NAME_print (BIO * bp, const X509_NAME * name, int obase)
Definition at line 490 of file x_name.c.
X509_NAME_set()
int X509_NAME_set (X509_NAME ** xn, X509_NAME * name)
Definition at line 473 of file x_name.c.
References in, NULL, and X509_NAME_dup().
Referenced by OCSP_request_set1_name(), X509_CRL_set_issuer_name(), X509_REQ_set_subject_name(), X509_set_issuer_name(), and X509_set_subject_name().